### ISSUE TITLE
Exercício 22 da aula 2

### ISSUE THREAD

**Issue by todd7** [roger-melo-treinamentos/curso-de-js-roger-melo#1]
No exercício 21 foi pedido

`A let "newName" deverá armazenar uma string ES5 com o mesmo valor que "name" armazena;`

E no exercício 22

`Atribua à "newName" uma template string` 
`A template string deverá resultar no mesmo valor que a "newName" tinha anteriormente (nome e sobrenome com letras iniciais maiúsculas);`

Seria para adicionar uma template string e depois adicionar uma novo valor ?

**Comment by Roger-Melo** [comment]
Oi Edson.

No exercício 21, você armazenará a string que a `name` armazena, só que com as letras iniciais do nome e sobrenome maiúsculas. Ou seja, você usará a `name` para criar/manipular essa nova string ES5.

Então fica:

```javascript
const name = 'walter white'
let newName = // Sua solução aqui. Ela deve resultar em => 'Walter White'
```

No exercício 22, você atribuirá para a `newName` uma template string que deve resultar em `Walter White` também.

Então, no exercício 21 você manipula a string usando ES5 e no exercício 22, usando template strings.
Ambos os exercícios devem resultar em `Walter White`.

Sacou a ideia? Se ainda não tiver entendido, é só dar o toque que explico de outra forma =)

**Comment by todd7** [comment]
Ah sim, agora entendi, valeu!!
