### ISSUE TITLE
Dúvida na refatoração do exercício-17

### ISSUE THREAD

**Issue by thiago-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#10]
Olá, Roger

Minha dúvida é a seguinte: Como a função **clearInput** conseguiu ter acesso à referência do input, se pegamos a referência a este input dentro da função **handleSubmit**?

A seguir o trecho de código a que me refiro:
```
const clearInput = () => {
  input.value = ''
  input.focus()
}

const logMessage = message => {
  console.log(message)
  clearInput()
}

const handleSubmit = event => {
  event.preventDefault()
  
  const input = event.target.input
  const regex = /[a-zA-Z0-9]{7,11}/
  const isAValidValue = regex.test(input.value)
  
  if (isAValidValue) {
    logMessage('O valor inserido no input é válido =)')
    return
  }
  logMessage('Valor inválido =(')
}

form.addEventListener('submit', handleSubmit)
```

**Comment by Roger-Melo** [comment]
Oi Thiago. Excelente pergunta =)

Id's penduram uma propriedade no objeto global (window).

Essa é uma das razões pelas quais ids devem ser únicos em um documento HTML.

Como no index.html foi declarado um atributo `id` com o valor `input`, se você inserir `window.input` (ou simplesmente `input`) no console do browser enquanto roda a aplicação do exercício, o retorno será a referência do input.

Se você retirar o `id="input"` da marcação HTML, salvar e novamente inserir `window.input` no console do browser, undefined será retornado.

Foi um erro meu não ter falado isso. Pretendo abordar esse e outros assuntos em aulas mais aprofundadas sobre o DOM que estou preparando pro futuro.

Ficou claro? Se ainda houverem dúvidas é só dar o toque que explico de outra forma =)

@thiago-viana

**Comment by thiago-viana** [comment]
Entendi. Obrigado, Roger.
