### ISSUE TITLE
Etapa 12, Correção dos exercícios da aula 06 da etapa 11 - Aula 01-01

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#100]
**Esse é o exercício que fiz sozinho e sem ver o vídeo da resolução, confesso que fiquei umas horinhas pensando em como fazer, eu demorei mais pra descobrir como fazer o gif abrir usando o src da tag img do que montar o resto do código haha, não sei se montei certo mas sei que tá funcionando pelo menos =)**

**Ainda tô em duvida se tem algo pra refatorar no código, refatoração não é meu forte mas tô melhorando, gostaria do seu feedback Roger!**

  Neste exercício, vamos praticar um pouco do que vimos até aqui, através da 
  API do GIPHY, que é um website de GIFs (https://giphy.com/).

  - Seu desafio é implementar uma funcionalidade de busca dos GIFs. Quando o 
    usuário digitar o termo de busca no input e pressionar enter, um GIF deve 
    ser exibido na tela. Como neste exemplo: https://youtu.be/RHe-uCJGCeA
  - Observe que o GIF mais recente é inserido acima dos GIFs anteriores;
  - Para fazer requests para a API do GIPHY, você precisará de uma API key. 
    Para obtê-la, siga os seguintes passos:
    - Acesse https://developers.giphy.com/dashboard/ e faça o login;
    - No Dashboard, clique em "Create an App", clique em "API Selected" e em 
      "Next Step";
    - Dê um nome e descrição para o app e crie-o;
    - Clique no código da API key para copiá-la;
  - O submit do form deve ser feito para o endpoint abaixo. Atente-se para os 2
    [PLACEHOLDERS] que devem ser substituídos:
    - https://api.giphy.com/v1/gifs/search?api_key=[SUA_CHAVE_DA_API_AQUI]&limit=1&q=[VALOR_INSERIDO_NO_INPUT]
    - Se quiser testar outras possibilidades, os endpoints da API estão 
      listados na documentação: https://developers.giphy.com/docs/api/endpoint#search
  - Ignore os avisos no console. Para limpá-lo, pressione "ctrl + L".

```js
const searchForm = document.querySelector('form')
const divContainer = document.querySelector('.out')

const getGIFUrl = async value => {
  const apiKey = 'KzIXQtgqGUMJtN1OpYCQ1vyIgURna7UV'

  try {
    const response = await
      fetch(`https://api.giphy.com/v1/gifs/search?api_key=${apiKey}&limit=1&q=${value}`)

    if (response.ok !== true) {
      throw new Error('Não foi possível obter os Dados =(')
    }

    const gifData = await response.json()
    const gifUrl = await gifData.data[0].images.original.url

    return gifUrl
  } catch (error) {
    const h2 = document.createElement('h2')
    h2.textContent = error
    divContainer.insertAdjacentElement('beforebegin', h2)
  }
}

searchForm.addEventListener('submit', async event => {
  event.preventDefault()
  const inputValue = event.target.search.value

  if (inputValue) {
    const img = document.createElement('img')
    img.setAttribute('src', await getGIFUrl(inputValue))
    divContainer.insertAdjacentElement('afterbegin', img)
  }

  searchForm.reset()
})
```

@Roger-Melo

**Comment by RicarGit** [comment]
**Dei uma pequena refatorada no código, ficou um pouco melhor creio eu... adicionei um regex básico também pra relembrar!**

```js
const searchForm = document.querySelector('form')
const divContainer = document.querySelector('.out')

const getGIFUrl = async value => {
  const apiKey = 'KzIXQtgqGUMJtN1OpYCQ1vyIgURna7UV'

  try {
    const response = await
      fetch(`https://api.giphy.com/v1/gifs/search?api_key=${apiKey}&limit=1&q=${value}`)

    if (response.status !== 200) {
      throw new Error('Não foi possível obter os Dados =(')
    }

    const gifData = await response.json()
    const gifUrl = await gifData.data[0].images.original.url

    return gifUrl
  } catch (error) {
    alert(error)
  }
}

const insertGIFIntoDom = async inputValue => {
  const regex = /^[a-zA-z]{3,}$/

  if (regex.test(inputValue)) {
    const img = document.createElement('img')
    img.setAttribute('src', await getGIFUrl(inputValue))
    divContainer.insertAdjacentElement('afterbegin', img)
  }
}

const searchGIF = event => {
  event.preventDefault()
  const inputValue = event.target.search.value

  insertGIFIntoDom(inputValue)
  searchForm.reset()
}

searchForm.addEventListener('submit', searchGIF)
```

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Parabéns pelo esforço em implementar o exercício sozinho e só depois ver a correção =)

Em um primeiro momento, o mais importante é fazer funcionar, como você mesmo disse. Primeiro faça funcionar, depois, melhore.

---

Ao testar o código aqui, o `Error` abaixo foi lançado:

```javascript
throw new Error('Não foi possível obter os Dados =(')
```

Isso aconteceu por que ele está dentro de um `if` que é executado quando a expressão abaixo resulta em `true`:

```javascript
if (response.status !== 200 || gifData) {
  throw new Error('Não foi possível obter os Dados =(')
}
```

A expressão `response.status !== 200 || gifData`, vai resultar retornar true se `response.status !== 200` resultar em um valor truthy **ou** se `gifData` resultar em um valor truthy.

Sendo assim, toda vez que a resposta do request é obtida com sucesso (e `response.status !== 200` resulta em false), `gifData` contém um objeto. E como objeto, tanto vazio como preenchido, é um valor truthy, `gifData` vai retornar `true`, `response.status !== 200 || gifData` vai resultar em `true` e o bloco do if que contém o `Error` será executado.

Sacou a ideia?

---

Há algumas oportunidades de melhoria no código abaixo:

```javascript
const insertGIFIntoDom = async inputValue => {
  const regex = /^[a-zA-z]{3,}$/

  if (regex.test(inputValue && await getGIFUrl(inputValue))) {
    const img = document.createElement('img')
    img.setAttribute('src', await getGIFUrl(inputValue))
    divContainer.insertAdjacentElement('afterbegin', img)
  }
}
```

- Observe que a expressão inserida como condição do `if` está extensa. Isso demanda mais esforço cognitivo em entender o que a condição está checando. Você pode armazenar essa expressão em uma constante na qual o nome deixa mais explícito o que a expressão está verificando.

- Ao invocar `await getGIFUrl(inputValue)` duas vezes, 2 requests são executados. Se essa expressão também for armazenada em uma const, o request será feito apenas uma vez e você pode apenas referenciar a const na expressão do if e como segundo argumento da invocação do `setAttribute`.

- Uma linha em branco pode separar a declaração da `const img` do restante do código dentro do bloco. Assim você separa o conceito de criação do `img` do conceito do uso desse elemento.

---

Ficou claro o que eu disse acima?

@RicarGit

**Comment by RicarGit** [comment]
> if (response.status !== 200 || gifData) {
> throw new Error('Não foi possível obter os Dados =(')
> }

**Eu tava tentando tirar esse erro -> TypeError: gifData.data[0] is undefined quando eu busco uma imagem e ela não existe mas até agora não tive sucesso, ele gera um erro mas não aparece a mensagem que lancei como erro... tirando isso, aqui está o resultado:**
```js
const searchForm = document.querySelector('form')
const divContainer = document.querySelector('.out')

const getGIFUrl = async value => {
  const apiKey = 'KzIXQtgqGUMJtN1OpYCQ1vyIgURna7UV'

  try {
    const response = await
      fetch(`https://api.giphy.com/v1/gifs/search?api_key=${apiKey}&limit=1&q=${value}`)

    if (response.status !== 200) {
      throw new Error('Não foi possível obter os Dados =(')
    }

    const gifData = await response.json()
    const gifUrl = gifData.data[0].images.original.url

    return gifUrl
  } catch (error) {
    alert(error)
  }
}

const insertGIFIntoDom = async inputValue => {
  const regex = /^[a-zA-z]{3,}/
  const gifUrl = await getGIFUrl(inputValue)
  const isInputAndUrlValid = regex.test(inputValue) && gifUrl

  if (isInputAndUrlValid) {
    const img = document.createElement('img')

    img.setAttribute('src', gifUrl)
    divContainer.insertAdjacentElement('afterbegin', img)
  }
}

const searchGIF = event => {
  event.preventDefault()
  const inputValue = event.target.search.value

  insertGIFIntoDom(inputValue)
  searchForm.reset()
}

searchForm.addEventListener('submit', searchGIF)
```

**Confesso que estava esperando por essa aula, buscar dados e renderiza-los na tela, creio que é algo muito importante pois agora estou confiante que consigo criar cards, slides, lista de produtos, tabelas com informações, coisa que antes eu só fazia manualmente, ainda faltam as aulas com bancos de dados mas logo eu chego lá, agradeço a sua ajuda @Roger-Melo**

**Comment by Roger-Melo** [comment]
> Eu tava tentando tirar esse erro -> TypeError: gifData.data[0] is undefined quando eu busco uma imagem e ela não existe mas até agora não tive sucesso, ele gera um erro mas não aparece a mensagem que lancei como erro... tirando isso, aqui está o resultado:

Essa API responde com status 200 mesmo quando a resposta do request vem vazia.

Se você inserir um `console.log(response)` antes do `if` que verifica o status, vai ver que o objeto Response contém `status: 200`. Isso faz com que o `if (response.status !== 200)` não seja executado.

Para resolver isso, você pode inserir um outro `if` após a `gifData` e verificar se o array que a propriedade `data` do `gifData` está vazio. Se estiver, já que o if está dentro de um `try` você pode lançar um erro ou fazer qualquer outra ação:

```javascript
const gifData = await response.json()
const isGifDataEmpty = gifData.data.length === 0

if (isGifDataEmpty) {
  // ...
}

const gifUrl = gifData.data[0].images.original.url
return gifUrl
```

Sacou a ideia?

> Confesso que estava esperando por essa aula, buscar dados e renderiza-los na tela, creio que é algo muito importante pois agora estou confiante que consigo criar cards, slides, lista de produtos, tabelas com informações, coisa que antes eu só fazia manualmente, ainda faltam as aulas com bancos de dados mas logo eu chego lá, agradeço a sua ajuda @Roger-Melo

Sim. Requests são um conceito importante ao construir aplicações web com JavaScript puro. Você ainda irá treiná-los bastante no decorrer do treinamento =)

**Comment by RicarGit** [comment]
**Entendi Roger, eu quis colocar as duas verificações em 1 if e acabei me embananando, agora está assim:**
```js
const getGIFUrl = async value => {
  const apiKey = 'KzIXQtgqGUMJtN1OpYCQ1vyIgURna7UV'

  try {
    const response = await
      fetch(`https://api.giphy.com/v1/gifs/search?api_key=${apiKey}&limit=1&q=${value}`)
    const gifData = await response.json()
    const isGifDataEmpty = gifData.data.length === 0
    const gifUrl = gifData.data[0].images.original.url

    if (response.status !== 200) {
      throw new Error('Não foi possível obter os Dados =(')
    }

    if (isGifDataEmpty) {
      throw new Error('Não foi possível obter os Dados =(')
    }

    return gifUrl
  } catch (error) {
    alert(error)
  }
}
```
**Agora surgiu outra dúvida, eu posso lançar o mesmo erro dentro desse if também usando o new Error ou não vai ter problemas? porque o new estaria criando outro objeto em memória não?**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Sim, o `new` cria um novo objeto. Então são 2 objetos de erro em memória. Não há problema nisso, apenas seja mais claro na mensagem do erro quando `isGifDataEmpty` for `true`. 

Como erros geralmente são lidos por programadores, você pode especificar na mensagem que o objeto de resposta da API veio vazio, ou algo do tipo =)

@RicarGit

**Comment by Roger-Melo** [comment]
Vou fechar a issue Ricardo, mas no que precisar, é só abrir uma nova =)
