### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by LeandroKoshoji** [roger-melo-treinamentos/curso-de-js-roger-melo#1005]
Boa noite professor, tudo bem?

Finalizei a [aplicação conversor de moedas](https://github.com/LeandroKoshoji/conversor-de-moeda) e ficaria muito grato se pudesse avaliar.

Eu já tinha implementado a solução no decorrer do exercício. Inclusive vi a correção do mesmo. Após isso, refiz outros projetos e apaguei o código e refiz a aplicação do zero.

Eu vi que o senhor mostrou que tem como não deixar o resultado da fetch em escopo aberto, porém ainda não consegui entender direito. Vou estudar mais e refatorarei depois a minha aplicação.

Na minha aplicação, eu selecionei os elementos Html através das classes. Porém, gostaria de saber se, por convenção, isso é uma má prática?

**Menores dificuldades**

- Manipular o Dom.
- Lógica da construção da aplicação.

**Maiores dificuldades**

- Muitas vezes me confundo para fazer o tratamento dos erros.
- Perco muito tempo pensando nos nomes das variáveis e funções (rsrs).
- Sinto que melhorei nas refatorações, mas ainda dou umas travadas.

Muito obrigado professor. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @LeandroKoshoji.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @LeandroKoshoji! Tudo certinho, e tu?

Parabéns pelo esforço em construir a quarta aplicação. Você continua demonstrando que pegou bem a lógica até aqui. Também demonstra evolução em relação às análises anteriores =)

> ### Na minha aplicação, eu selecionei os elementos Html através das classes. Porém, gostaria de saber se, por convenção, isso é uma má prática? 

Não chega a ser má prática, mas usar os data-* pra manipular DOM te dá mais flexibilidade e organização. O ideal é deixar os atributos `class` apenas para a estilização e `data-*` para JS.

É o que eu recomendo e é o que você verá durante o treinamento quando manipulações de DOM forem deitas =)

> ### Eu vi que o senhor mostrou que tem como não deixar o resultado da fetch em escopo aberto, porém ainda não consegui entender direito. Vou estudar mais e refatorarei depois a minha aplicação.

Abre uma issue de dúvida explicando o que vc não entendeu que te ajudo. O mesmo vale para tratamento de erros =)

> ### Perco muito tempo pensando nos nomes das variáveis e funções (rsrs).

Escolher bons nomes é complexo mesmo.

Em linhas gerais, um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

> ### Sinto que melhorei nas refatorações, mas ainda dou umas travadas.

Isso é natural. Refatoração vem com a prática e o tempo =)

---

Na real, o que eu mudaria código que você enviou é a organização dos listeners de eventos. Você pode separar e agrupar os callbacks que são apenas referenciados dos callbacks que estão inline no `addEventListener`:

```javascript
invertButton.addEventListener('click', async ()=> {
  // ...
})

currencyOneEl.addEventListener('input', async event => {
  // ...
})

userInputEl.addEventListener('input', multiplyRates)
currencyTwoEl.addEventListener('input', updateRatesIntoDOM)

init()
```

Fique atento também a consistência de seu coding style. Algumas arrow functions foram declaradas com espaço em branco entre os parênteses e o `=>` e outras não.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

**Comment by LeandroKoshoji** [comment]
Boa noite professor,

Muito obrigado pelos apontamentos.

Vou me atentar mais a organização e ao coding style das minhas aplicações.

Um grande abraço.
