### ISSUE TITLE
Etapa 9, Todo-list

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#101]
Olá Roger,
tudo bem?

Finalizei minha primeira versão do to-do list.
Bom, minhas dificuldades principais foram com o bootstrap, e com fazer o  "trash-button" funcionar. 

Estou orgulhoso que consegui desenvolver essa aplicação sem grandes dificuldades. Pelo que me recordo, vi as aulas após desenvolver a mesma e notei que há pontos a serem melhorados como o de apagar um item, e na funcionalidade de busca. 

Estarei realizando uma nova versão com estas melhorias. 

https://github.com/henriquebazi/curso-cjrm/tree/main/todo-list/v-1

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique. Tudo em paz, e contigo?

Sim, nas aulas seguintes as features são adicionadas na aplicação =)

Parabéns pelo esforço em implementar a aplicação sozinho.

Como nas aulas seguintes você verá como implementar as demais features e refatorar a aplicação, vou fazer algumas observações que não se relacionarão com o que você verá nas aulas seguintes.

```javascript
const inputTarget = (event) => input = event.target
const todoClassList = (todo) => todoClass = todo.classList
```

Não sei se foi intencional mas no código acima, as funções estão retornando o resultado da atribuição. Isso não vai afetar a execução da atribuição e o funcionamento do código, mas penso que o fato desse valor ser retornado tenha passado batido enquanto as funções foram implementadas. 

A invocação de `inputTarget(event)` ou `todoClassList(todo)` pode causar confusão. O nome de uma função precisa deixar explícito qual ação ela está fazendo. Sempre nomeie funções com este princípio em mente.

Sobre a função que usa o event, é válido como estudo de abstração separá-lo mas é uma convenção usar e deixar o `event` apenas no escopo da função de callback do evento. Observe que para essas funções serem criadas, duas let tiveram que ser declaradas para sofrerem reatribuição depois.

```javascript
let input = ''
let todoClass = ''
```

Na maior parte do tempo, sempre que possível, eu tento evitar lets e tendo a usar mais consts. Isso é proposital. Let indica mutação. Mutação é o lugar onde se encontram a maior parte de bugs de uma aplicação. Evite sempre que possível.

Eu recomendo que você implemente exercícios e aplicações sozinho, mas tente fazer o mais parecido possível do que eu mostro nas aulas. Depois de realmente conseguir fazer sozinho como foi mostrado, aí é legal experimentar coisas novas. 

Existem princípios por trás da grande maioria das coisas que eu mostro nas aulas, mas que são implícitos.

Nas aulas eu não mostro, por exemplo, o `toLocaleLowerCase`. É interessante você resolver os desafios usando apenas as ferramentas que foram mostradas no treinamento. Pelo menos num primeiro momento. 

```javascript
const clearFormSearch  = () => {
  isFormSearchEmpty = formSearch.firstElementChild.value !== ''

  if(isFormSearchEmpty){
    clearSearchedTodos()
  }
}
```

No código acima, é necessário especificar que `isFormSearchEmpty` é uma `const`.

---

Está ficando mais claro?

@henriquebazi

**Comment by Roger-Melo** [comment]
Henrique, vou fechar a issue. Mas no que precisar, fique à vontade para abrir uma nova ou responder esta =)
