### ISSUE TITLE
Etapa 08 - Aula 01-01 - Correção dos exercícios da aula 02 da etapa 07

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1011]
E ai Roger, tudo bem?

### 1ª Dúvida
Na correção dos exercícios, mais especificamente no exercício **03**, foi implementado o código, para poder iniciar o contador do valor. E, por ventura, cliquei duas vezes, no botão **Iniciar contador**, e percebi que, caso eu clique mais de uma vez, no botão iniciar, ele incrementa de forma acelerada. Eu compreendo que, a cada vez que eu clicar no botão, ele vai chamar o ``setInterval``, porém, tem lidar com tal efeito, de maneira simples?

### 2ª Dúvida
Na lógica do botão **Parar contador**, você implementou o código assim:

~~~javascript
const stopCounter = () => {
  clearInterval(timer);
  counter.textContent = 0;
};

pauseCounterButton.addEventListener('click', () => {
  stopCounter();
});
~~~

A dúvida é boba mas, por que não englobar toda a ``stopCounter`` na função do eventListener, assim:

~~~javascript
const stopCounter = () => {
  clearInterval(timer);
  counter.textContent = 0;
};

pauseCounterButton.addEventListener('click', stopCounter);
~~~

Muito obrigado mais uma vez. Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva. Pode só referenciar a `stopCounter` como callback sim. Não sei pq não fiz isso xD

Sobre o clique duplo no botão de iniciar o contador, dá uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/900#issuecomment-863692317) e se ainda restar alguma dúvida, pode comentar aqui nessa issue =)

**Comment by raphaelprsilva** [comment]
Olá Roger,

Obrigado pelo feedback, mais uma vez. Ficou entendido sim!

**Comment by Roger-Melo** [comment]
Show @raphaelprsilva, no que precisar, é só dar o toque =)
