### ISSUE TITLE
Resumo da Aula 01-03, 01-04, 01-06 e 01-07  da etapa 05

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1012]
## 3 escopos em JavaScript que você deve conhecer - Aula 01-03

> Escopo pode ser definido como a visibilidade de uma  variável, ou seja, dependendo de onde você declara uma variável outras partes do código podem ou não ter acesso a elas.

**Escopo de funções:**

```
function getMessage () {
  let message = 'oi!'

  message// oi
}

message // NOT  DEFINED
```

- 'message' é acessível apenas dentro da função getMessage.
- podemos ter múltiplas funções com o mesmo nome de variáveis dentro delas.

```
const dog =  'Pator-alemão'

function dogWatch() {
  const  dog = 'Samoieda'

  dog // 'Samoieda'
}

dog // 'Pastor-alemão'
```

* O escopo de "dog" é a função dogWatch

## Escopo de blocos:

O escopo de bloco, não necessariamente está relacionado diretamente a funções

```
let radius = 8

if(radius > 0) {
  const PI = 3.14

  let circle = 2 * PI * radius
}

radius //8
PI // NOT DEFINED
circle // NOT DEFINED
```

Em javascript um bloco tem a notação de abertura e fechamento de chaves

**Atenção: let e const tem regras diferentes de escopo da VAR. Antes o ES6 a única forma de prender uma var em escopo de bloco, era declara-lá em uma função**

## Escopo léxico:

```
const external = () => {
  const greet = 'oi'

  const internal = () => {
    let x = 10
    const message = `${greet}. Seu pai tem boi?`

    console.log(message)
  }

  internal()
  
  console.log(x) // x is not defined
}
```

**A função internal consegue acessar a const greet, pois consegue buscar um escopo acima. E todas estão no escopo external.**

**O fluxo de buscar é sempre de fora pra dentro. Exemplo: let x, não é acessível pois o fluxo seria de dentro pra fora.**

## MDN - Mozilla Developer Network - Aula 01-04

Lugar onde podemos encontrar as documentações do javascript

Usar inglês americano e a barra de pesquisa do site é ruim.

## O que é o DOM - Document Object Model - Aula 01-06

> O que é o DOM - Document Object Model é o coração de qualquer modificação em uma web page

**O DOM:**

-  É criado pelo browser, não faz parte da linguagem em si;
-  Quando o HTML é carregado no browser, o DOM é criado;

  **MDN**: O Modelo de Objeto de Documento  (DOM) é uma interface de programação para documentos HTML, XML e SVG . Ele fornece uma representação estruturada do documento como uma árvore. 

O DOM define métodos que permitem acesso à árvore, para que eles possam alterar a estrutura, estilo e conteúdo do documento. 

O DOM fornece uma representação do documento como um grupo estruturado de nós e objetos, possuindo várias propriedades e métodos. Os nós também podem ter manipuladores de eventos que lhe são inerentes, e uma vez que um evento é acionado, os manipuladores de eventos são executados. Essencialmente, ele conecta páginas web a scripts ou linguagens de programação.

## Query selector & query selector all - Aula 01-07

O processo de buscar e selecionar um elemento é chamado de query do DOM

**exemplo:**

index.html

```
<body>
  <h1>Query selector & query selector all</h1>

  <div>
    <p>Hello world!</p>
    <p>Oi</p>
    <p class="error">Essa é uma mensagem de erro</p>
  </div>

  <div class="error"> Outra mensagem de erro</div>

  <script src="app.js"></script>
</body>
```

Para obter uma referência do primeiro paragrafo:

**método mais recomendado de uso**

```
const paragraph = document.querySelector('p') // obtem a primeira tag  p e ignora as outras

console.log(paragraph) //<p>Hello world!</p>
```

Para obter a tag p com class error, usa-se o seletor de classe:

```
const paragraph = document.querySelector('.error')

console.log(paragraph) //<p class="error">Essa é uma mensagem de erro</p>
```

Para obter a class error da segunda div, especificamos qual div é.

```
const errorDiv = document.querySelector('div.error')

console.log(errorDiv) //<div class="error"> Outra mensagem de erro</div>
```

Para obter múltiplos elementos:

```
const paragraphs = document.querySelectorAll('p')// NodeList(3) [p, p, p.error]
```

**Podemos usar a notação de colchetes para obter um item de uma posição especifica no nodelist**

**Podemos utilizar o forEach nesta nodeList**

```
console.log(paragraphs[0])//<p>Hello world!</p>
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @NiksonDiniz, rumo à fluência! 🔥
