### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1016]
Para removermos elementos do DOM, primeiro precisamos obter a referência deste elemento, atribuir a referência a uma constante, e em seguida invocar a partir desta constante o método `remove()`. Vamos ver na prática como seria remover uma determinada `<div>` de uma página HMTL:

```jsx
const div = document.querySelector('div');

div.remove();
```

O código acima já é o suficiente para que quando a página for carregada, o elemento referenciado seja removido imediatamente. Também é possível utilizarmos este método em um escutador de eventos. Imagine que temos uma lista de itens e queremos que, no momento em que algum item da lista seja clicado, ele seja removido. Então primeiro temos que obter a referência desta lista com todos os itens, encadeamos o `forEach()` a referência, e em seguida utilizamos o método `addEventListener()`, utilizando como primeiro argumento o evento `'click'`, e como segundo argumento a função de *callback*, onde como argumento do *callback* temos o `event`, e na função chamamos o `event.target` encadeando o método `remove()` a ele. Vamos ver na prática como ficaria:

```jsx
const lis = document.querySelectorAll('li');

lis.forEach(li => {
	li.addEventListener('click', event => {
		event.target.remove();
	});
});
```

O código acima então já é o suficiente para que ao clicar em um elemento da lista, o mesmo seja removido do DOM.

E como podemos fazer para adicionarmos um elemento no DOM? Primeiro, como sempre, precisamos obter um elemento como referência, elemento no qual queremos inserir um novo elemento. Por exemplo, vamos supor que temos uma `<div class='message'></div>` e queremos inserir alguma mensagem. Com a referência a este elemento, podemos utilizar o `textContent` atribuindo o novo conteúdo, ou adicionando a algum já existente com o *addition assignment*. Vamos ver na prática:

```jsx
const divMessage = document.querySelector('.message');

divMessage.textContent = 'Seja bem-vindo!';
```

O mesmo podemos fazer em uma lista com um botão que adiciona um novo item a esta lista. Podemos utilizar um escutador de eventos no botão, que quando clicado, adiciona um novo elemento. E isto pode ser feito de duas formas: a primeira é utilizando o *addition assignment*, onde apenas adicionamos o novo conteúdo após o conteúdo já existente, utilizando uma *template string* com o novo elemento, ou criamos um novo elemento do zero com o método `document.createElement()` passando o elemento como argumento, adicionamos seu conteúdo com o `textContent`, e após isso chamamos a referência do *parent* da lista com o método `append()` para incluirmos o novo elemento ao final da lista, ou o método `prepend()` para adicionarmos ao início da lista. Vamos ver na prática estas diferentes maneiras (Este exemplo supõe que na página HTML temos uma `<ul>` com itens `<li>` e um `<button>` para adicionar itens):

```jsx
const ul = document.querySelector('ul');

const button = document.querySelector('button');

// Utilizando o innerHTML com addition assignment
button.addEventListener('click', () => {
	ul.innerHTML += '<li>Novo item</li>';
});

// Utilizando a criação do elemento e o método append()
button.addEventListener('click', () => {
	const li = document.createElement('li');
	li.textContent = 'Novo item';
	ul.append(li);
});

// Utilizando a criação do elemento e o método prepend()
button.addEventListener('click', () => {
	const li = document.createElement('li');
	li.textContent = 'Novo item';
	ul.prepend(li);
});
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas, rumo à fluência! 🔥
