### ISSUE TITLE
Etapa 02, nome do vídeo:  Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1017]
dúvida 1:*************
Na bateria de exercícios 4, no exercício 1, da etapa 1,
o resultado ficou:

```const my3FavoriteTVShows = ['Dexter','Prision Break','Breaking Bad']

const sentence = `Minhas 3 séries favoritas são: ${my3FavoriteTVShows.join(', ')}.`
  .replace('Break,', 'Break e ')

console.log(sentence)```
********
Minha dúvida onde 'quebrei bastante a cabeça', fiz alguns testes sem sucesso:

Se eu quiser deixar dinâmico para que substitua a última vírgula da string
e substituir essa última vírgula da string por ' e '.

tentei isolando em outras const com os métodos lastindexOf() e indexOf() mas
sem sucesso e também percebi que na solução dos exercícios você não mostrou
como deixar dinâmico, então pergunto:

Pergunta 1 - É possível resolver o problema somente com o que aprendemos até aqui?
Se sim, se puder me dar uma dica, ok?

Pergunta 2 - Seria através de algo que ainda não vimos, por exemplo, expressões regulares?




<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira.

> ### Se eu quiser deixar dinâmico para que substitua a última vírgula da string e substituir essa última vírgula da string por ' e '.

É possível. A forma como mostrei na resolução é uma das formas, mas até esse momento, não é exigido que seja resolvido de forma dinâmica.

> ### É possível resolver o problema somente com o que aprendemos até aqui? Se sim, se puder me dar uma dica, ok?

Você sempre usará apenas o que viu no treinamento para resolver. Quando é necessário pesquisar por algo que ainda não foi mostrado, isso fica explícito na descrição do exercício.

Essa é outra forma de resolver:

```javascript
const arr = ['x', 'y', 'z']
console.log(arr.join(' e ').replace(' e ', ', '))
```

Mas novamente, não era exigida uma resolução dinâmica. O ideal é sempre fazer funcionar primeiro e ir melhorando aos poucos.

> ### Seria através de algo que ainda não vimos, por exemplo, expressões regulares?

Você verá expressões regulares na etapa 06 =)

**Comment by claudiogmoreira** [comment]
Obrigado!
