### ISSUE TITLE
Etapa 02, nome do vídeo: Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1018]
dúvida 2:******

Na bateria de exercícios 4, no exercício 5, da etapa 1,
o resultado ficou:

```const numberCheck = 39```
```console.log(`A string que a "typeSentence" armazena tem mais de ${numberCheck} caracteres? ```
```${String(typeSentence.length > numberCheck).replace('t','T')}.`)```
*********
Minha dúvida onde 'quebrei bastante a cabeça', fiz alguns testes sem sucesso:

na solução, quando for True, a primeira letra ficará maiúscula,
mas e se for False, como tornar isso dinâmico para o 'F' também ficar Maiúsculo?

Pergunta 1 - É possível resolver o problema somente com o que aprendemos até aqui?
Se sim, se puder me dar uma dica, ok?

Pergunta 2 - Seria através de algo que ainda não vimos, por exemplo, expressões regulares?

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Pergunta 1

Uma outra solução além da que foi mostrada na correção é armazenar o boolean convertido em string em uma const e usar o index da string no replace:

```javascript
const bool = String(typeSentence.length > 39)
console.log(bool.replace(bool[0], bool[0].toUpperCase()))
```

---

Como a pergunta 2 é a mesma da outra issue e parte da pergunta 1 também, as respostas estão na outra issue, ok?

Quando as dúvidas forem da mesma aula, você pode abrir apenas uma issue, se preferir =)

@claudiogmoreira

**Comment by claudiogmoreira** [comment]
Obrigado!
