### ISSUE TITLE
Input type=range e event bubbling

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#102]
A dúvida não está relacionada a nenhuma aula específica.

Tenho 5 inputs type range. Sempre que um deles mudar tenho que executar uma função. O único jeito é fazendo um event listener pra cada um ou tem como aproveitar o event bubbling para não precisar fazer vários event listeners?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

Não é necessário adicionar um evento em cada input. A lógica é a mesma que mostrei na aula sobre [Event bubbling](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890634) e depois na construção do [popup](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890854).

Você pode adicionar o listener de evento no elemento que contém os inputs: 

```html
<div data-js="inputs-container">
  <input data-js="input1" type="range" id="volume" name="volume" min="0" max="11">
  <label for="volume">Volume</label>

  <input data-js="input2" type="range" id="cowbell" name="cowbell" min="0" max="100" value="90" step="10">
  <label for="cowbell">Cowbell</label>
</div>
```

```javascript
const container = document.querySelector('[data-js="inputs-container"]')

container.addEventListener('change', e => {
  console.log(e.target)
})
```

Se o um dos inputs forem modificados, essa mudança irá propagar para a `div` e, como ela contém um listener de evento que "escuta" mudanças, o callback do listener de evento dela será executado =)

Sacou a ideia?

@lucasfads

**Comment by lucasfads** [comment]
Ah, maravilha!
Eu tava na dúvida se o change afetaria o elemento pai.
Obg @Roger-Melo!

**Comment by Roger-Melo** [comment]
No que precisar, estou à disposição =)
