### ISSUE TITLE
Resumo da Aula 02-03 e Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by edmaaralencar** [roger-melo-treinamentos/curso-de-js-roger-melo#1023]
### Concatenação de strings
```
const firstName = "Edmar"
const lastName = "Alencar"
const fullName = firstName + " " + lastName

// Resultado: 'Edmar Alencar'
```

### Acessando letras específicas em uma string
```
const firstName = "Edmar"

firstName[0]

//  Resultado: 'E'
```

### Tamanho de uma string
```
const firstName = "Edmar"
firstName.length

// Resultado: 5
```

### Metodos de string
 - Devem ser terminados com ()
 - Metodos mais utilizados: 
   - toUpperCase: transformar todo o texto em letra maiúscula
   - toLowerCase: transformar todo o texto em letra minúscula
   - indexOf('argumento'): retorna posição do caractere da string
   - lastIndexOf('argumento'): retorna a ultima ocorrência do caractere na string
   - slice(argumento 1, argumento 2): corta toda a string menos na área específica definida pelos argumentos.
        - Argumentos são 2 números.
   - replace('argumento ', 'argumento 2'): substitui uma letra/palavra específica por outra em uma string (apenas a primeira). 
 ```
const firstName = "Edmar"
firstName.toUpperCase()
// Resultado: 'EDMAR'

--------------------------

firstName.toLowerCase()
// Resultado: 'edmar'

--------------------------

firstName.indexOf('d')
// Resultado: 1 

--------------------------

const email = 'edmaralencar@gmail.com'
email.lastIndexOf('a')
// Resultado: 15

--------------------------

email.slice(5, 22)
// Resultado: alencar@gmail.com

--------------------------

email.replace('a', 'y')
// Resultado: edmyralencar@gmail.com
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @edmaaralencar. Rumo à fluência! 🔥
