### ISSUE TITLE
Etapa 2, nome do vídeo: Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1027]
Bom dia Roger, na descrição do primeiro exercício,
diz que quando acontecer loop infinito usando while loop,
como faz para desconectar o servidor? 
houve casos que além de fechar o servidor, precisei reiniciar o windows,
só não entendi como desconecta o servidor...
quando clico com o botão direito no index.html,
tem a opção open live server mas não existe uma opção close live server...

Correção dos exercícios da aula 01 - Aula 02-01
- Desconecte o servidor;

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira. Para desconectar o servidor você pode fazer o mesmo procedimento de quando vai subir o servidor, mas ao invés de clicar em "Open with Live Server", clique em "Stop Live Server":

![menu-live-server](https://user-images.githubusercontent.com/29297788/123558933-78070600-d76f-11eb-8bf7-81c94a6af672.jpg)

Lembrando que esse procedimento precisa ser feito no `index.html` =)

**Comment by claudiogmoreira** [comment]
![como_parar-live-server](https://user-images.githubusercontent.com/43302996/123641058-366e6d80-d7f8-11eb-9a3c-f4ab03e10c42.jpg)
não achei aqui essa opção!
a versão do vscode que tenho é 1.57.1
a versão liveserver é v5.6.1

**Comment by Roger-Melo** [comment]
Ao invés de clicar no nome do arquivo, abra o arquivo clique com o botão direito em qualquer parte do código e a opção deve aparecer =)

@claudiogmoreira

**Comment by Roger-Melo** [comment]
@claudiogmoreira vou fechar a issue mas no que precisar, é só abrir uma nova =)
