### ISSUE TITLE
Etapa 03, Funções - Arrow Function

### ISSUE THREAD

**Issue by marcosmaiadev** [roger-melo-treinamentos/curso-de-js-roger-melo#103]
Estou terminando a parte de objetos, mas fazendo meus resumos, encontrei umas dúvidas simples:

Eu testei para ver se a arrow function também tinha o processo de içamento (como a function declaration). Vi que não.
1) É isso mesmo? arrow function não possui içamento?
A sintaxe da arrow function lembra um pouco o function expression. 
2) Eu posso dizer que a arrow function foi criada 'em cima" ou 'com base" na function expression ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcos.

> 1) É isso mesmo? arrow function não possui içamento?

Isso. Arrow functions, assim como function expressions, não são içadas. Apenas function declarations são.

> A sintaxe da arrow function lembra um pouco o function expression. 

Function expressions são funções armazenadas em variáveis/constantes. Então no código abaixo, tanto a função com a palavra-chave function e a arrow function são function expressions:

```javascript
const getGreet = function () {
  return 'Hi'
}

const getGreet = () => 'Hi'
```

> 2) Eu posso dizer que a arrow function foi criada 'em cima" ou 'com base" na function expression ?

Arrow functions são expressões alternativas e compactas a function expressions que usam a palavra-chave `function`. 

Existem algumas diferenças técnicas entre elas que você verá no treinamento, mais a frente =)

Me deixe saber se está ficando mais claro.

@marcosmaiadev

**Comment by marcosmaiadev** [comment]
@Roger-Melo perfeito. Arrow function é uma versão compacta da function expression. Entendi. Tópico solved. Muito obrigado Roger.

**Comment by Roger-Melo** [comment]
Legal que ficou mais claro, Marcos. No que precisar, fique à vontade para abrir novas issues =)
