### ISSUE TITLE
Resumo da Aula 03-04 switch statement da etapa 2

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#1031]
# Switch Statement
 ## Funciona como uma condicional com if/else if

 Dentro dos parenteses passamos uma variável ou expressão que será verificada 
  em cada case. Cada case é verificada até encontrar um valor correspondente 
  ao valor da const, então o código é executado, mas todos os códigos dos case abaixo também 
  serão executados mesmo que o valor não seja correspondente. 
  Caso não haja nenhuma correspondência, a instrução em default é acionada.
   
```js
 const grade = 'B'

switch (grade) {
  case 'A':
    console.log('Você tirou um A')
  case 'B':
    console.log('Você tirou um B')
  case 'C':
    console.log('Você tirou um C')
  case 'D':
    console.log('Você tirou um D')
  case 'E':
    console.log('Você tirou um E')
  default:
    console.log('Nota inválida')
}

// retorna: 
//Você tirou um B
//Você tirou um C
//Você tirou um D
//Você tirou um E
//Nota inválida
```
## Uso do break 
 Para que apenas o código do case correspondente ao valor da variável seja executado, usamos o break.
 O break encerra a verificação (após o código do case que retornou um valor correspondente ser 
 executado) evitando que os códigos seguintes também sejam executados (mesmo que haja mais alguma correspondência após a primeira, ela será ignorada.)

```js
switch (grade) {
  case 'A':
    console.log('Você tirou um A')
    break
  case 'B':
    console.log('Você tirou um B')
    break
  case 'C':
    console.log('Você tirou um C')
    break
  case 'D':
    console.log('Você tirou um D')
    break
  case 'E':
    console.log('Você tirou um E')
    break
  default:
    console.log('Nota inválida')
}

 retorna: Você tirou um B 

// O primeiro case não teve correspondência e passou para o próximo, onde o valor verificado 
// corresponde à variável (B). O código é executado. 
// O break é acionado e a verificação é encerrada.
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ElaineDelgado, rumo à fluência 🔥
