### ISSUE TITLE
Aplicação: weatherApp

### ISSUE THREAD

**Issue by wsn-nunes** [roger-melo-treinamentos/curso-de-js-roger-melo#1037]
Boa Noite Professor,

Segue a minha aplicação do acuuweather.com

weatherApp

[https://github.com/wsn-nunes/CJRM-weatherApp](url)

Minha maior dificuldade foi na criação da função e o uso de parâmetros.

exemplo :

-> const cityData = gitCityName (cityName) 

inclusive no próprio uso do fetch para fazer a requisição .

este uso ainda complica minha cabeça , mas chegamos até aqui e aproveitamos bastante... 

Como sempre muito obrigado por cada detalhe no aprendizado que não ficou em branco ... muito conteúdo de forma fácil ...

neste modelo eu não fez a refatoração , mas deixando bem claro que entendi , mas tem uns detalhes que precisam ser aperfeiçoados em mim .. em questão de lógica ...

não sei se expliquei muito bem , mas minhas dúvidas são essas apenas...

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @wsn-nunes.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá wsn-nunes.

Parabéns pelo esforço em construir a aplicação =)

---

> ### Minha maior dificuldade foi na criação da função e o uso de parâmetros.

O exemplo `const cityData = gitCityName (cityName)` como criação de função não faz sentido. Vou explicar porque:

- `cityName` não é um parâmetro, mas sim um **argumento**;
- `gitCityName (cityName)` não é uma declaração de função, mas sim uma invocação de `gitCityName` com um espaço antes dos parênteses.

Isso foi mostrado em aulas anteriores, no módulo onde funções foram apresentadas. Se houver qualquer dúvida sobre como declarar uma função, veja as aulas novamente e se alguma dúvida específica restar, abra uma issue que te ajudo.

> ### Inclusive no próprio uso do fetch para fazer a requisição

Eu procurei no repositório do treinamento e não encontrei issues que você abriu sobre dúvidas com o `fetch`.

Recomendo que pergunte mais, que abra mais issues. Quanto mais rápido você tirar dúvidas, menos elas irão escalar.

Se assistiu a aula e tem dúvida, abra a issue no momento em que a dúvida surgir. Não fique com dúvidas.

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar a aplicação e o envio dela.

---

## Link do respositório

O link que você colocou na issue não está apontando para o seu repositório, mas sim para a url `https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/url`.

Para inserir um link em uma issue, ao digitar a issue pressione `ctrl+K`. Você verá que e essa marcação foi inserida no corpo da issue:`[](url)`. Basta inserir o texto do link entre os colchetes e substituir "url" pela url final. 

Exemplo: `[repositório weather app](https://github.com/wsn-nunes/CJRM-weatherApp)`

E na issue vai ficar assim: [repositório weather app](https://github.com/wsn-nunes/CJRM-weatherApp).

## Usabilidade

#### `autofocus` no input 

Quando a página for carregada (ou recarregada), você já pode deixar um foco no input por padrão, usando no input o atributo `autofocus`. Assim o usuário não precisa mover o cursor do mouse e clicar no input para inserir o nome da cidade.

## Lógica

### Variáveis globais

Nunca declare consts ou lets sem as palavras-chave `const` ou `let`, pois isso pendura uma variável global no objeto `window`:

```javascript
getCityWeather = async (cityKey) => {
  // ...
}

console.log(window.getCityWeather) // async (cityKey) => { ... }
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

### Erros lançados por falta de imagens

Ao testar a aplicação, os erros abaixo foram lançados no console:

```
GET http://127.0.0.1:5500/src/dayandnight.jpg 404 (Not Found)
GET http://127.0.0.1:5500/src/day.jpg 404 (Not Found)
GET http://127.0.0.1:5500/src/night.jpg 404 (Not Found)
```

Todos eles indicam a falta de imagens que estão em sua máquina mas não foram subidas para o github. Isso faz com que qualquer parte do código que tente encontrar uma imagem lance um erro, pois a imagem não existe na pasta buscada.

## Organização de código

### console.log esquecidos

O `console.log` é útil apenas no momento em que você está desenvolvendo. Sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

Isso foi falado em análises passadas, então cuidado para não cometer os mesmos erros.

### Comentários

Evite comentários na hora de subir a aplicação para produção ou enviar o código para alguém.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho em atualizá-los.

Se você faz questão de usar comentários como objeto de estudos, é melhor manter duas versões do código: a de produção (sem comentários) e a de desenvolvimento/estudos.

### Idiomas da interface da aplicação

Para ter uma comunicação consistente, o idael é que a aplicação tenha um único idioma: ou português ou inglês. 

O `<p data-js="cityNameClima">` está exibindo uma informação em inglês americano, enquanto o restante da interface está em pt-BR.

### Nomes de variáveis, funções e valores

A consistência no idioma também vale para a nomeação de elementos no código. No caso do `data-js="cityNameClima"`, prefira usar apenas inglês ou português.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Sabendo disso... 

`cityNameApp` e `cityWeatherApp` podem ter o `App` removido.

`cityWeatherTemperature` pode ser renomeada para `cityTemperature` porque `Temperature` já implica que se trata da temperatura do clima. 

`cardImg` pode ser renomeada para `timeImg` ou `weatherImg`, para descrever melhor do que se trata a imagem.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by wsn-nunes** [comment]
Muito Obrigado professor . Assim que eu fizer as alterações abro uma nova issue , entendi perfeitamente os conceitos

**Comment by Roger-Melo** [comment]
Não precisa enviar a aplicação novamente não. Só se tiver alguma dúvida =)

**Comment by wsn-nunes** [comment]
Ok . Obrigado professor ...
