### ISSUE TITLE
Etapa 2, nome do vídeo: Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1038]
Bom dia Roger, gostaria apenas de mostrar como resolvi esse exercício apenas com o aprendizado do treinamento até aqui,
onde eu fui de forma espontânea e imaginando como seria a resolução, bem mais trabalhosa e como muito mais linhas de código. Mas até que foi válido pois não foi fácil resolver, quebrei bastante a cabeça!
Já refiz a solução do exercício para entender a diferença.
O treinamento para mim está sendo muito bom, até aqui estou conseguindo aprender e quero seguir firme até o fim.
Estou curtindo muito o clean code, como tornar o código melhor e semântico.

Se puder comentar algo sobre o processo de aprendizado, se é normal o aluno partir por caminhos mais difíceis no início,
agradeceria, obrigado!

// era a solução que eu tinha na cebeça!
// resolvido de forma individual diferente da resolução do exercício
// aqui fiz somando um item por vez do array

// let sumArr1 = 0
// let sumArr2 = 0
// let sumArr3 = 0
// let sumArr4 = 0

// for(let i = 0; i < 1; i++){

//   for(let j = 0; j < arrays[0].length; j++){
//     //console.log(arrays[i][j])
//     sumArr1 += arrays[i][j]

//   }
//   console.log(`a soma do subArray ${arrays[0]} é ${sumArr1}`)

  
//   for (let k = 0; k < arrays[1].length; k++){
//     //console.log(arrays[1][k])
//     sumArr2 += arrays[1][k]
//   }
//   console.log(`a soma do subArray ${arrays[1]} é ${sumArr2}`)
  
//   for (let l = 0; l < arrays[2].length; l++){
//     //console.log(arrays[2][l])
//     sumArr3 += arrays[2][l]
//   }

//   console.log(`a soma do subArray ${arrays[2]} é ${sumArr3}`)

//   for (let m = 0; m <arrays[3].length; m++){
//     //console.log(arrays[3][m])
//     sumArr4 += arrays[3][m]

//   }
//   console.log(`a soma do subArray ${arrays[3]} é ${sumArr4}`)
  
// }
// console.log(`A soma total é ${sumArr1 + sumArr2 + sumArr3 + sumArr4 }`)

@Roger-Melo

**Comment by claudiogmoreira** [comment]
![console](https://user-images.githubusercontent.com/43302996/123653428-8272df80-d803-11eb-8dcf-f4711002215b.jpg)

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira.

> ### Se puder comentar algo sobre o processo de aprendizado, se é normal o aluno partir por caminhos mais difíceis no início

Sim, é natural =)

É importante entender que não existe **código incorreto**.

O que pode acontecer é um código ser mais complexo e de difícil leitura, ou mais simples, mais fácil de ler, manter, etc.

A desvantagem da abordagem acima é que se `arrays` tivesse um número maior de itens, uma let `sumArr*` e um `for` teriam que ser declarados para cada item.

---

O que que funcionou para mim no início do meu aprendizado foi:

1. Quando travava em um exercício, assistia a correção, apagava o código e implementava-o novamente, sozinho. Se não conseguisse implementar sem olhar a correção do exercício, via a correção. Nessa fase, minhas dúvidas sobre o exercício já estavam mais específicas. Após sanar a dúvida, apagava o código e implementava-o, sozinho.

2. Executava o item acima quantas vezes fossem necessárias, de forma espaçada, para que meu cérebro entendesse o padrão de resolução do exercício.

Esse hábito me deixava mais afiado para os próximos desafios =)
