### ISSUE TITLE
Etapa 07 - Aplicação: Quiz Interativo - Exercícios da aula 01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#104]
Roger, o desafio foi bacana.

Ele mostra que com poucas linhas de js da para fazer algo
bem interativo.

Minhas duvidas.
Eu vi a aula da solução varias vezes umas 6 mais ou menos,
até entender bem. 
Mais vejo que peco na lógica ainda, principalmente no array com loop.
Mais acho que falta bastante pratica e paciência, eu vejo que demoro 
para aprender rápido algo novo no javascript, se eu não vejo funcionando
em algo real eu não consigo vê a utilidade do código.   

Minhas menores dificultardes.
No layout com bootstrap eu peguei bem, pois já conheço bem o
html e css.
E setar os elementos em variáveis.  
Questão de função, por tudo tem que vira uma função né. 

Repositório do código https://github.com/naldowebdeveloper/quiz-interativo 
Página do quiz https://naldowebdeveloper.github.io/quiz-interativo/

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Você está enviando a aplicação [deste](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js) exercício, certo?

Para ter o código da aplicação avaliado, você precisa cumprir todos os requisitos que o exercício descreve. Faltou só o requisito abaixo:

> - Exibe na tela a pontuação que o usuário fez. Não há certo ou errado, apenas faça. Essa exibição de pontos é uma das implementações que faremos na próxima aula =D

Vou deixar a issue aberta e quando tiver implementado esse ajuste, é só me avisar e disponibilizar os links novamente.

E claro, qualquer dúvida, pode contar comigo =)

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo 

Estou enviando novamente

código
>> https://github.com/naldowebdeveloper/quiz-interativo

Página 
>> https://naldowebdeveloper.github.io/quiz-interativo/

**Comment by Roger-Melo** [comment]
Show Ednaldo. Parabéns pelo esforço em implementar a aplicação =)

> Eu vi a aula da solução varias vezes umas 6 mais ou menos, até entender bem.

Você viu e depois implementou sozinho? Se sim, o seu código demonstra que você realmente entendeu bem!

Nas aulas seguintes você verá como melhorar o código dessa aplicação.

> ...eu vejo que demoro para aprender rápido algo novo no javascript...

"Demorar" não é problema. Não aprender, sim.

> Mais vejo que peco na lógica ainda, principalmente no array com loop.

Quais são as dificuldades com arrays e loops?

@naldowebdeveloper

**Comment by Roger-Melo** [comment]
Vou fechar a issue. Se tiver alguma dúvida, é só falar =)
