### ISSUE TITLE
Outras Dúvidas

### ISSUE THREAD

**Issue by CleitonRReis** [roger-melo-treinamentos/curso-de-js-roger-melo#1040]
Fala, Roger! Blz?

Estava fazendo um teste online e me deparei com esses 3 problemas abaixo. Eu não consegui resolvê-los. Será que você consegue fazer um vídeo com a resolução deles ou detalhar como eles podem ser resolvidos?

1º exercício:

Você recebe um array de inteiros a. Sua tarefa é calcular quantos números no array são iguais à média aritmética de seus vizinhos imediatos.

Em outras palavras, conte o número de índices i tais que a [i - 1] + a [i + 1] = 2 * a [i].

* Nota: * Se a [i - 1] ou a [i + 1] não existir, eles devem ser considerados iguais a 0.

Exemplo:

Para a = [2, 4, 6, 6, 3], a saída deve ser contarMediaAritmetica(a) = 3.

=============================================================================================

2º exercício:

Dado um array de inteiros a, sua tarefa é calcular os dígitos que ocorrem o maior número de vezes no array. Retorne o array desses dígitos em ordem crescente.

Exemplo:

Para a = [25, 2, 3, 57, 38, 41], a saída deve ser digitosMaisFrequentes(a) = [2, 3, 5].

Aqui está o número de vezes que cada dígito aparece no array:

0 -> 0
1 -> 1
2 -> 2
3 -> 2
4 -> 1
5 -> 2
6 -> 0
7 -> 1
8 -> 1

O maior número de vezes que qualquer número ocorre na matriz é 2, e os dígitos que aparecem 2 vezes são 2, 3 e 5. Portanto, a resposta é [2, 3, 5].

=============================================================================================

3º exercício:

Você recebe dois arrays de inteiros a e b do mesmo comprimento e um inteiro k. Vamos iterar através do array a da esquerda para a direita, e simultaneamente através do array b da direita para a esquerda, e olhando para os pares (x, y), onde x é de a e y é de b. Esse par é chamado de pequeno se a concatenação xy for estritamente menor que k.

Sua tarefa é retornar o número de pares pequenos que você encontrar durante a iteração simultânea por a e b.

Exemplo:

Para a = [1, 2, 3], b = [1, 2, 3] e k = 31, a saída deve ser
contarParesPequenos(a, b, k) = 2.

Estamos considerando os seguintes pares durante a iteração:

(1, 3). Sua concatenação é igual a 13, que é menor que 31, então o par é pequeno;
(2, 2). Sua concatenação é igual a 22, que é menor que 31, então o par é pequeno;
(3, 1). Sua concatenação é igual a 31, que não é menor que 31, então o par não é pequeno.
Como você pode ver, existem 2 pares pequenos durante a iteração, então a resposta é 2.

Para a = [16, 1, 4, 2, 14], b = [7, 11, 2, 0, 15] e k = 743, a saída deve ser
contarParesPequenos(a, b, k) = 4.

Estamos considerando os seguintes pares durante a iteração:

(16, 15). Sua concatenação é igual a 1615, que é maior que 743, então o par não é pequeno;
(1, 0). Sua concatenação é igual a 10, que é menor que 743, então o par é pequeno;
(4, 2). Sua concatenação é igual a 42, que é menor que 743, então o par é pequeno.
(2, 11). Sua concatenação é igual a 211, que é menor que 743, então o par é pequeno;
(14, 7). Sua concatenação é igual a 147, que é menor que 743, então o par é pequeno.

Existem 4 pares pequenos durante a iteração, então a resposta é 4.

=============================================================================================

Desde já agradeço!
Abs!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Cleiton Reis.

Não sei de onde veio esses testes mas fique atento para não se frustrar. Geralmente esses sites de testes não tem uma SGD - sequência gradativa de dificuldade (ao contrário do CJRM), e isso pode acabar te desmotivando. Por isso eu recomendo focar nos exercícios do treinamento. Além de eles seguirem uma SGD, você nunca ficará sem respota, por que eu corrijo todos. Inclusive, um dos exercícios da etapa atual é um teste de entrevista de emprego que eu mostrei como resolver =)

Ainda sobre foco... o treinamento está com 4 aplicações construídas mas você só enviou a primeira para a análise. 

De forma resumida, eu usaria o reduce no primeiro exercício, filter no segundo e no terceiro iria de forEach até encontrar uma solução mais elegante.
