### ISSUE TITLE
Etapa 09 - Removendo to-dos - Aula 02-02

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1044]
Fala Roger, tudo bem? Eu de novo.... hehe

Eu estava vendo o vídeo sobre como remover os to-dos e, antes de assistir o vídeo, fiz algo semelhante ao que você fez no vídeo, porém, utilizando ``className``. O trecho ficou assim:

~~~javascript
todosContainer.addEventListener('click', event => {
  const clickedElement = event.target;
  console.log(clickedElement.className.includes('delete'));
})
~~~

### A dúvida é:

- Faz sentido usar o ``className``, ao invés de ter que usar o ``classList`` e ter que converter em um array? Eu pergunto, pois achei mais prático.

Obrigado, desde já!

@Roger-Melo

**Comment by Roger-Melo** [comment]
No exemplo da aula pode não fazer tanta diferença, mas fique atento ao tipo de dado retornado por cada um.

Se eu usar o `className` para checar se existe uma classe `delete`, o caso abaixo resulta em um falso positivo:

```javascript
'delete-blablabla'.includes('delete') // true
```

Como o `classList` retorna um array, a comparação é mais precisa:

```javascript
['delete-blablabla'].includes('delete') // false
```

Sacou a ideia?

@raphaelprsilva

**Comment by raphaelprsilva** [comment]
Entendi sim, peguei a ideia.

Fez sentido. Obrigado mais uma vez!

Pode fechar a issue, caso queira.

Abraço!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só dar o toque =)
