### ISSUE TITLE
Etapa 05, Event Bubbling & Event Delegation: Aula 04-02

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1045]
No meu VSCode não existe a opção 'tagName' e sim 'nodeName' , isso é normal?

![image](https://user-images.githubusercontent.com/44072541/123800031-3a18f780-d8bf-11eb-85c3-51426842c56a.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy. Dá uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/326#issuecomment-811613488) e se ainda restarem dúvidas, pode comentar aqui nessa issue =)

**Comment by marcosyoggy** [comment]
Confirmado, clicando nos (...) encontrei a tagName, obrigado Roger.
