### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1046]
<h1 align="center"> 🔥 Quiz Interativo</h1>
<br>

:octocat: **Segue abaixo o link do Quiz no meu repositório do Github.**

[***Link do quiz-Interativo***](https://github.com/Mateus20Barros/interactive-quiz)
<br>

❓ **Quais foram as minhas maiores dúvidas ou dificuldades durante a execução desse exercício?**

> *A minha maior dificuldade nesse exercício foi como exibir os dados do quiz no **``DOM - Document Object Model``** qual a* 
*melhor forma de exibir esses dados. No meu caso eu exibir esses dados em um **``popup``** assim a pessoa ver a nota que*   *obteve no quiz e as estatísticas de desempenho.* 
<br>

❓ **Quais foram as minhas menores dificuldades durante a execução desse exercício?**

> *Minha menor dificuldade nesse exercício foi implementar esse desafio, pois com os grandes conhecimentos da linguagem* 
*adquirido durante o curso, ficou bastante fácil compreender o desafio e resolve-lo. As vezes surgem algumas duvidas, mais com* *a pratica de consultar a documentação do **``MDN``** para sanar as duvidas, vai se desenrolando no projeto.*
<br>

🚀 **Tecnologias usadas**<br>
<img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg" width="35"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg" width="35"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" width="35"/>
<br>
🎯 Para o desenvolvimento desse projeto acabei utilizando apenas ***``HTML``*** ***``CSS``*** e ***``JAVASCRIPT``*** sem qualquer tipo de framework, libs ou algo do gênero. Pois assim pude colocar em pratica os meus conhecimentos sobre as tecnologias usadas para o desenvolvimento do projeto. *"Utilizei apenas a fonte ***``Akaya Kanadaka cursive``*** do ***``Google fonts``***"*
<br>
🏆 by **Mateus Barros**
<br>

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Mateus20Barros** [comment]
👍

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros!

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

- `button`, `redoAgain` e `popup` são nomes poucos descritivos. Eu as nomearia como `buttonSubmitQuiz`, `buttonTryAgain` e `popupFinalScore`;
- `answers` poderia se chamar `correctAnswersAmount`;
- Dates (em `insertDates`) dá a entender que datas serão inseridas, o que não é o caso. Eu a nomearia como `showFinalScore` ou `showScore`;
- `answerItems` poderia ser nomeada como `isAnswerCorrect`, pois armazena um boolean indicando se a resposta está correta.

## Lógica

### `window.location.href`

Sobre o useo dessa propriedade, o ideal é usar apenas o que você viu no treinamento para resolver os desafios. O que não significa que você não possa estudar outras coisas por fora (claro) =)

### Callback do `forEach`

Não é necessário fazer manipulação no DOM a cada execução do callback do `forEach`. Dentro desse callback você só precisa fazer os cálculos da pontuação. 

Depois que as execuções do callback terminarem, aí sim você insere as informações na tela:

```javascript
  userAnswers.forEach((userAnswer, index) => {
    const answerItems = userAnswer === correctAnswers[index]

    if (answerItems) {
      score += 20
      answers += 1
      amountGrades += 2
    }
  })

  insertDates(paragraphPorcentage, `Você acertou ${score}% do Quiz.`, answersResults)
  insertDates(paragraphQuantityQuestions, `Em um total de 5 questões você acertou ${answers}.`, answersQuantity)
  insertDates(paragraphGradeQuiz, `Sua nota no quiz foi "${amountGrades}.0"`, grade)
```

### Evitando repetições de invocações

Uma opção para não repetir várias vezes a invocação da insertDates é deixar a marcação HTML interna da `<div class="popup-content">` como template string, exceto o botão (porque você precisa do botão no DOM para adicionar o listener de click nele):

```html
<section class="keep-popup">
  <div class="popup">
      <h1>Estatísticas & Desempenho</h1>
      <div class="popup-content"></div>
      <div class="keep-button">
        <button class="redo-again">Refazer Quiz</button>
      </div>
  </div>
</section>
```

Faz mais sentido também que os parágrafos sejam `<h2>`:

```javascript
const popupContent = document.querySelector('.popup-content')

const showFinalScore = () => {
  popupContent.innerHTML = `
    <h2 class="paragraph-statistics info-date corrects-answers">Porcentagem de Acertos</h2>
    <p>Você acertou ${score}% do Quiz.</p>

    <h2 class="paragraph-statistics info-date quantity-answers">Números de questões acertadas</h2>
    <p>Em um total de 5 questões você acertou ${answers}.</p>

    <h2 class="paragraph-statistics info-date quiz-grade">Nota do Quiz</h2>
    <p>Sua nota no quiz foi "${amountGrades}.0"</p>
  `
}
```

Assim vc evita ter que selecionar os parágrafos para cada inserção no DOM e pode remover as consts `grade`, `answersResults` e `answersQuantity` no topo do código. A invocação da função ficaria assim:

```javascript
const handleSubmit = event => {
  event.preventDefault()

  const userAnswers = [ 
    // ... 
  ]

  userAnswers.forEach((userAnswer, index) => {
    // ...
  })

  showFinalScore() // invocação da função que insere a pontuação no DOM
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Mateus20Barros** [comment]
Olá @Roger-Melo 

Muito obrigado pelos conselhos sobre refatoração, e outros pontos mais que podem melhor o código.

> As observações fizeram sentido?

Sim, com certeza suas observações fizeram todo sentido, pois da forma que você mostrou nas explicações faz o código ficar bastante limpo e de fácil compreensão.

Assim como muitos falam e eu acredito nessa frase que diz. **Muitas vezes o difícil não e fazer o um código que o computador entenda, mas é um desafio fazer código que outros seres humanos entenda.**

Então @Roger-Melo  valeu pelas observações e vamos segui em frente no curso. 😉 👍 

by *Mateus Barros*

**Comment by Roger-Melo** [comment]
Show @Mateus20Barros. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
