### ISSUE TITLE
Etapa 5, DOM - Aula 02-02

### ISSUE THREAD

**Issue by marcosmaiadev** [roger-melo-treinamentos/curso-de-js-roger-melo#105]
Bem simples. 
Na aba "Elements" do DevTools, quando se seleciona um elemento html, aparece um sinal do lado direito,  de forma meio esmaecida.

```
<section>...</section> == $0
```
O que é esse "== $0" que aparece?

Obrigado! 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcos!

No console do devtools, você pode usar $0, $1, $2, $3, e $4 como atalhos de para os 5 últimos elementos do DOM que você inspecionou ou selecionou no painel elements. $0 retorna o primeiro mais recente elemento selecionado, $1 retorna o segundo mais recente, e assim por diante.

Se você selecionar ou inspecionar qualquer um `<p>` no painel elements, ao executar `$0` no console, a referência do `<p>` será retornada.

Sacou a ideia?

@marcosmaiadev

**Comment by marcosmaiadev** [comment]
Entendi. Esses atalhos, claro, apenas no DevTools né. 
Obrigado, Roger.

**Comment by Roger-Melo** [comment]
Isso. São atalhos que o devTools cria para facilitar a inspeção do código =)

As funcionalidades dele, por si só, dão o conteúdo de um curso. Se tiver interesse, [essa](https://developers.google.com/web/tools/chrome-devtools) é a documentação dele. É útil para consultas rápidas, mas nada que valha a pena para desfocar do mais importante =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só dar o toque =)
