### ISSUE TITLE
Resumo da Aula  01-08, 02-02, 02-03, 02-04 e 02-05 da etapa 05

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1053]
## Outras maneiras de fazer queries no DOM - Aula 01-08

Obter um  elemento através do ID:

```javascript
const title = document.getElementById('title') // não é  necessário  0 '#'

console.log(title)
```

Obter elementos através  do nome da classe:

```javascript
const errors  = document.getElementsByClassName('error')  // não  é necessário o '.'

console.log(errors)
```

**Atenção: o getElement retorna um HTMLCollection,e neste diferente do nodeList, não é possível fazer um forEach. Para utilizar um forEach é necessário transformar o HTMLCollection.**

Obter elementos através do nome da tag:

```javascript
const paragraphs = document.getElementsByTagName('p')

console.log(paragraphs)
```

## Adicionando e modificando conteúdo em uma página - Aula 02-02

Obtendo primeiro paragrafo encontrado na página:

```javascript
const paragraph = document.querySelector('p')

console.log(paragraph) //<p>Hello world!</p>
```

Para pegar somente o texto de dentro do parágrafo:

```javascript
console.log(paragraph. innerText) //Hello world!
```

Para modificar o texto:

```javascript
paragraph.innerText = 'Texto inserido' //<p>Texto inserido</p>
paragraph.innerText += ' Texto inserido'
```

Para modificar vários:

**lembre-se: nodeList aceita forEach**

```javascript
const paragraphs = document.querySelectorAll('p')

paragraphs.forEach((paragraph, index) => {
  paragraph.innerText += ` Novo texto  ${index + 1}`
})
```

Para modificar o HTML:

```javascript
const div = document.querySelector('.content') //obtendo HTML

div.innerHTML = '<h2>Novo h2</h2>'
```

**Se houver html dentro da div, será sobrescrito, caso contrário só adiciona o que foi solicitado.**

exemplo de uso com forEach:

```javascript
const people = ['Pedro', 'João', 'Junior']

people.forEach(person => {
  div.innerHTML += `<p> ${person} </p>`
})
```

**Atenção: innerText e innerHTML são getters(obter) e setters(set: estabelecer)**

## Obtendo e setando atributos - Aula 02-03

```html
index.html
...
  <h1>Obtendo e setando atributos</h1>

  <a href="https://github.com/NiksonDiniz"> Github Nikson</a>

  <p class="error">Mensagem</p>
...
```

Obtendo a referência do link:

```javascript
const link =  document.querySelector('a')
```

Obtendo o valor do href:

```javascript
console.log(link.getAttribute('href'))
```

Modificando ou setando o atributo:

O método setAttribute() recebe dois argumentos:

- O primeiro é o nome  do atributo que queremos  modificar;
- O segundo é o valor que queremos inserir.

```javascript
link.setAttribute('href', 'https://github.com/') 
```

Para modificar o texto do link:

```javascript
link.innerText = 'Website do GitHub'
```

Obtendo a referência de p:

```javascript
const paragraph = document.querySelector('p')
```

Obtendo o valor do atributo class:

```javascript
console.log(paragraph.getAttribute('class')) // error
```

Modificando o valor do atributo:

```javascript
paragraph.setAttribute('class', 'sucess') // modificou o valor da class para sucess
```

Para setar um valor de atributo que não existe no elemento:

**se ele não existe, o javascript cria**

```javascript
paragraph.setAttribute('style', 'color:red')
```

## Modificando estilos CSS (inline) - Aula 02-04

```html
index.html
...
  <h1 style="color: blue;">Modificando estilos CSS (inline)</h1>

  <p class="error">lorem error lorem</p>
...
```

Obtendo a referência do h1 pra adicionar mais estilos

```javascript
const title = document.querySelector('h1')
```

Usando o setAtribute(), ele pode sobrescrever o elemento que já tinha

```javascript
title.setAttribute('margin', '50px') 
//<h1 style="margin: 50px;">Modificando estilos CSS (inline)</h1>
```

Obtendo o valor da propriedade color

```javascript
console.log(title.style.color) // blue
```

Para adicionar um margem como exemplo, usa-se a propriedade style:

**Atenção: Quando se trata de estilos, usar a propriedade style é mais eficiênte que setAtribute()**

```javascript
title.style.margin = '50px'
```

Para modificar a cor

```javascript
title.style.color = 'green'
```

**Atenção: para utilizar nomes de propriedades como por exemplo: font-size, utilizar a notação camelCase: fontSize**

**Caso queira verificar como fica os nomes das propriedades utilizar**

```javascript
console.log(title.style)
```

Para remover a propriedade, basta atribuir valor uma string vazia

```javascript
title.style.margin = ''
```

## Obtendo, adicionando, removendo e alternando classes *CSS* - Aula 02-05

```html
index.html
...
  <h1 class="title">Obtendo, adicionando, removendo e alternando classes CSS</h1>

  <p>lorem error lorem</p>
  <p>lorem ipsum lorem</p>
  <p>lorem ipsum lorem</p>
  <p>lorem success lorem</p>
...
```

```javascript
// obtendo a referência do p
const paragraph = document.querySelector('p')

// verificando quais classes esse elemento tem
console.log(paragraph.classList)//DOMTokenList ["error", value: "error"]

// para adicionar uma class ao p, utilizamos método '.add' da classList
paragraph.classList.add('error')

// para  remover utiliza-se o método .remove da classList
paragraph.classList.remove('error')

//obtendo referência dos paragrafos
const paragraphs = document.querySelectorAll('p')

// adicionando as classes
// Atenção o método innerText só obtem o texto visível, enquanto o textContent mostra visível ou não
// exemplo: se o elemento possuir um display: none, ele estará invisível
paragraphs.forEach( paragraph => {
  if(paragraph.textContent.includes('error')){
    paragraph.classList.add('error')
  }
  
  if(paragraph.textContent.includes('success')){
    paragraph.classList.add('success')
  }
})

// alternando as classes
// obtendo referência do h1
const title = document.querySelector('h1')

// o método .toggle() adiciona a classe se ela não existir e tira se ela existir
title.classList.toggle('test') //<h1 class="title test">
title.classList.toggle('test') //<h1 class="title">
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @NiksonDiniz. Rumo à fluência 🔥
