### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1058]
Vamos conhecer agora mais três eventos que podemos utilizar no DOM, que são o `copy`, o `mousemove` e o `wheel`.

O `copy` é um evento disparado toda vez que copiamos algum texto selecionado na página, seja com o clique do botão direito e em seguida clicando na opção de copiar, seja utilizando as teclas de atalho Ctrl+c. Vamos ver um exemplo onde ao copiar um determinado parágrafo vamos exibir uma mensagem "Texto copiado" no console.

```jsx
const paragraph = document.querySelector('p');

paragraph.addEventListener('copy', () => {
	console.log('Texto copiado');
});
```

O evento `mousemove` poderá ser disparado toda vez que movermos o mouse sobre algum área que tenhamos obtido a referência. Então vamos supor que tenhamos uma `<div>` com altura e largura de 200px e queremos exibir no próprio HTML as posições do eixo x e do eixo y desta área na tela. Partindo do início, vamos supor que tenhamos em nossa estrutura HTML uma `<div class="box"></div>`. A ideia então é pegar a referência deste elemento, adicionar um escutador de eventos `mousemove` e exibir as posições dos eixos x e y do mouse dentro deste elemento:

```jsx
const div = document.querySelector('.box');

div.addEventListener('mousemove', event => {
	div.textContent = `x ${event.offsetX} | y ${event.offsetY}`;
});
```

Lembrando que caso queiramos, podemos exibir no console o `event`, e será mostrada uma lista de tudo o que ocorre no determinado evento que estamos escutando.

O evento `wheel` é o evento de rolagem da tela através do mouse, e apenas do mouse. O evento não será disparado se passarmos pela tela com as setas do teclado ou se utilizarmos a barra de rolagem do browser, por exemplo. Ele é um evento específico de rolagem de tela através da "roda" do mouse. Então vamos utilizar este evento para exibir no console as posições dos eixos x e y do mouse na tela, no momento em que o evento for disparado. Neste exemplo, este evento será escutado a partir do `document`.

```jsx
document.addEventListener('wheel', event => {
	console.log(event.pageX, event.pageY);
});
```

Para mais eventos, segue página do MDN: [https://developer.mozilla.org/en-US/docs/Web/Events](https://developer.mozilla.org/en-US/docs/Web/Events)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. Rumo à fluência 🔥
