### ISSUE TITLE
Etapa 15, Correção dos Exercícios da Aula 02: Aula 03-02

### ISSUE THREAD

**Issue by erichporto** [roger-melo-treinamentos/curso-de-js-roger-melo#1059]
```js
const removeProp = (propToRemove, objs) => objs.map(({[propToRemove]: _, ...obj}) => obj)

```

Roger,

Na resolução da segunda questão do exercício 40, ali no destructuring com a computed property name, você utilizou um underscore. Eu lembro do uso do underscore quando você quer ignorar um argumento opcional, por exemplo 
```js 
[ ].reduce( (acc, item, _, array) => { } )
```
No caso do exercício, o underscore segue a mesma lógica? Está ignorando uma atribuição de valor à propToRemove?

Tentei procurar em outras aulas do curso algo parecido, mas são muitas daí ficou difícil rsrsr. Dei uma pesquisada também na MDN e pela internet algum exemplo desse uso específico do underscore e não encontrei :( 
Quando forço um exemplo direto e quando tento acessar a variável que usei o underscore, dá  ReferenceError, como se ela não 
tivesse sido declarada:

```js
const example = { a: 213, b: 965, c: 522 }

const { [b]: _, ...obj } = example

console.log(b, obj)

```
Agradeço desde já sua ajuda!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @erichporto.

O uso do underscore para nomear é apenas uma convenção para sinalizar que aquela variável/parâmetro não será usada no código.

Observe que isso é diferente de ignorar um identificador opcional. No exemplo abaixo, declarar o parâmetro `item` do callback do `map` é obrigatório. Porém, como eu quero usar apenas o parâmetro `index`, eu nomeio o parâmetro como underscore:

```javascript
arr.map((_, index) => {
  // uso apenas do index aqui dentro
})
```

Nesse [post](https://www.robinwieruch.de/javascript-naming-conventions), em "Javascript naming conventions: underscore" você encontra uma pequena menção sobre isso. 

[Aqui](https://stackoverflow.com/a/27637038/8138956) também tem uma pequena discussão.

Mas no geral, é só um detalhe, nada com que você precise se preocupar =)

**Comment by erichporto** [comment]
Muito obrigado, Roger.. agora sim entendi de vez a ideia do underscore. Percebi melhor a diferença entre ignorar o parâmetro e apenas sinalizar por convenção que não usará ele no código. Os links que você deixou também ajudaram muito no esclarecimento. Abraço!
