### ISSUE TITLE
Etapa 4, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by eduardophilip** [roger-melo-treinamentos/curso-de-js-roger-melo#1060]
```js
const isAnSUV = car => {
  
  const suv = ['Honda HR-V', 'Jeep Renegade', 'Ford EcoSport', 'Hyundai iX35'];
  const isSuv = suv.some(item => item === car);

  return isSuv
}

console.log(isAnSUV('Honda Civic'));
console.log(isAnSUV('Ford EcoSport'));
```

Roger, eu refatorei desta forma, também seria uma boa opção?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @eduardophilip. Com certeza é uma solução válida.

O lance é que até esse ponto do treinamento, eu ainda não apresentei o método `some`. Ele é apresentado na aula 04 da etapa 05. Então é interessante você resolver os exercícios com apenas o que foi mostrado nas aulas anteriores, sacou a ideia? =)

**Comment by eduardophilip** [comment]
Pecebi, Roger! Valeu a dica!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
