### ISSUE TITLE
Resumo da Aula 01-02, 01-03, 01-04 e 02-03 da etapa 04

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#1067]
# Objetos em javascript
Um objeto é uma coleção de dados e funcionalidades, também chamado de propriedades. As propriedades é uma associação de chave e valor. Onde o valor é o conteúdo da chave, se esse conteúdo for uma função, então a propriedade se torna um método.

No geral, os objetos em javascript é uma forma de criar elementos que se a próxima das coisas que temos na vida real e que são tangíveis. por exemplo:
    
Vamos criar o objeto xicara, com algumas características ou propriedades como cor: branca, tamanho: grande, peso: 100g e ele terá um método de tomar o chá.

No javascript criaríamos esse objeto da seguinte forma:
```js
    const xicara = {
        cor: "branca",
        tamanho: "grande",
        peso: "100g",
        tomarCha: function() {
            console.log('bebendo o chá')
        }
    }
```

Para acessarmos as características (propriedades) do objeto xicara utilizamos as anotações de "." ou "[]" 
```js
    console.log(xicara.cor)
```
ou
```js
    console.log(xicara['cor'])
```

O objeto xicara tem uma função, e toda função dentro de um objeto é um método que normalmente é uma ação que o objeto pode fazer.
```js
    xicara.tomarCha()
```
É possivel reatribuir os valores das propriedades em momento de execução como mudar a cor da xicara.
```js
    xicara.cor = "preto"
    ou
    xicara['cor'] = "preto"
        note que com a notação de colchete, a propriedade deve ser passado como string, ou seja entre aspas.
```
## This
Muito utilizado em objetos, o this quando passado a um método, faz referencia ao próprio objeto, e assim conseguimos acessar as propriedades do próprio objeto onde estamos executando o método.
Por exemplo vamos criar um método que muda a cor da xicara
```js
     const xicara = {
        cor: "branca",
        tamanho: "grande",
        peso: "100g",
        tomarCha: function() {
            console.log('bebendo o chá')
        }
        mudarCor: function() {
            this.cor = "vermelho"
        }
    }
```
Ao executar o método mudamos a cor da xicara para vermelho
```js
    xicara.mudarCor()
```
    O this.cor é como se fosse o xicara.cor

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @JuniorAlvesbr. Rumo à fluência! 🙌🏻
