### ISSUE TITLE
Etapa 3, nome do vídeo: Correção dos Exercícios da aula 01- Aula 02-01

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#1068]
## Olá, professor!!
Na correção do exercício 03 o senhor fez o seguinte:

```js
const log = function (value = `Você deve passar um valor um valor como argumento`) {
  console.log(value)
}
for(let i = 0; i < 7; i++) {
  log(`Esta é a ${i + 1}ª vez que essa string é exibida.`)
}
```
## Minha dúvida é: 
Existe alguma razão para no "for" não usarmos o valor inicial da let i como 0 (zero) ? Caso o valor inicial fosse =1, poderia usar apenas ${i} na template string como abaixo: 

```js
const log = function (value = `Você deve passar um valor como argumento`) {
  console.log(value)
}
for (let i = 1; i <= 7; i++) {
  log(`Esta é a ${i}ª vez que essa string é exibida.`)
}
```

Obrigada desde já!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @ElaineDelgado. 

Geralmente, o `for` é inicializado com a let i em `0` quando é necessário usar alguma referência ao index do array que está sendo iterado (`item[i]`) e etc.

No primeiro exemplo ali em cima, eu usei `i + 1` apenas para reforçar (visualmente) que o `index` de um array começa em `0`. Mas a let `i` pode ser declarada recebendo 1 sim, sem problemas =)

**Comment by ElaineDelgado** [comment]
Muito obrigada , professor!!!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
