### ISSUE TITLE
Aula Inaugural - Método ATER

### ISSUE THREAD

**Issue by josemalexandre** [roger-melo-treinamentos/curso-de-js-roger-melo#1069]
Olá Roger!

Uma pequena dúvida. 

No método ATER temos que fazer o resumo das aulas no nosso caderno.

Porém gostaria de saber se, ao invés de resumir no caderno eu fizesse o resumo no próprio PC por meio do bloco de notas ou no Word, o resultado no aprendizado seria o mesmo?

Grato pela atenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @josemalexandre.

Escrever à mão me ajudou mais no começo. Mas lembre-se: feito é melhor que perfeito. Se você se sente mais à vontade em digitar, digite. O importante é resumir e revisar depois =)

Sobre a eficácia de escrita à mão x digitação, existem algumas pesquisas sobre o assunto. Vou deixar uma fonte interessante sobre [aqui](https://www.b9.com.br/shows/naruhodo/naruhodo-282-anotar-a-mao-e-melhor-que-com-computador/) =)

**Comment by Roger-Melo** [comment]
@josemalexandre vou fechar a issue mas no que precisar, é só abrir uma nova =)
