### ISSUE TITLE
Etapa 07, Quiz Interativo

### ISSUE THREAD

**Issue by americosan86** [roger-melo-treinamentos/curso-de-js-roger-melo#107]
Olá Roger,

Segue o link do quiz interativo da etapa 7

https://github.com/americosan86/quiz_interativo7.git

Minha maior dificuldade foi com css, pois conheço muito pouco e demorei um tempo maior para entender sobre.

Minhas menores dificuldades foi a implementação do javascript, estou conseguindo definir a ideia e algumas tentativas com erros e acertos consegui fazer o exercício.

Obrigado pelas suas aulas!

**Comment by Roger-Melo** [comment]
Oi Americo.

Para ter o código da aplicação avaliado, você precisa cumprir todos os requisitos que o exercício descreve. Faltou só o requisito abaixo:

> - Quais foram as suas menores dificuldades durante a execução desse exercício.

Vou deixar a issue aberta e quando tiver implementado esse ajuste, é só me avisar.

E claro, qualquer dúvida, pode contar comigo =)

@americosan86

**Comment by americosan86** [comment]
blz, implementado

**Comment by Roger-Melo** [comment]
Legal! Você fez a sua versão do quiz com um tema diferente e conseguiu implementar o cálculo dos pontos. É perceptível que você sacou isso.

Agora vou deixar abaixo uma observação do que faltou ser implementado e algumas oportunidade de melhoria.

- Pontos devem ser exibidos na tela

Observe que um dos requisitos do exercício é exibir a pontuação na tela:

> - Exibe na tela a pontuação que o usuário fez. Não há certo ou errado, apenas faça. Essa exibição de pontos é uma das implementações que faremos na próxima aula =D

Atualmente, o código da aplicação está exibindo os pontos no console.

Desenvolvedores usam o console do browser. Usuários, não. Isso significa que se essa aplicação for para produção com o código dessa forma, o usuário não vai saber a pontuação dele.

- Uso do `==`

No código abaixo, foi usado o operador de igualdade ("igual a").

```javascript
if(userAnswer == correctAnswers[index]){
  score += part;
}
```

Só que esse operador, por baixo dos panos, executa conversão de tipos, como mostrei [nessa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751262) aula.

Nessa mesma aula eu explico por que você deve fugir desse operador e quais você deve usar.

- Warning no console do devtools

Quando abri o console, foi exibido o warning `DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:5500/bootstrap.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`. 

Isso aconteceu por que o browser tentou fazer download do arquivo `bootstrap.css.map`. E ele tentou fazer o download desse arquivo devido à última linha do `bootstrap.css`:

```css
/*# sourceMappingURL=bootstrap.css.map */
```

Para evitar esse tipo de imprevisto é preferível que o bootstrap (quando não instalado através do npm) seja usado através da tag `<link>`, como foi mostrado na aula.

- Nomeação de constantes

No código abaixo,

```javascript
const part = 100 / correctAnswers.length;
```

`part` é um nome que não deixa claro o que a constante está armazenando. Sempre nomeie constantes e variáveis com um substantivo que deixa explícito o que o valor armazenado representa.

- Linhas em branco

Linhas em branco devem ser usadas para indicar, visualmente, a separação entre conceitos.

No código abaixo, não há uma separação entre os conceitos `armazenar respostas do usuário` e `percorrer as respostas`.

```javascript
const userAnswers = [
  // ...
];
userAnswers.forEach((userAnswer,index) => {
  // ...
})
```

- Estilo de código

Por último vou mencionar o menos urgente, mas importante. 

Existem algumas convenções universais ao escrever um código JavaScript. Elas são tão universais que um programador do outro lado mundo espera vê-las, se olhar o código.

Se você olhar a documentação (MDN), verá que elas são aplicadas nos exemplos.

Vou listá-las e deixar a correção abaixo:

```javascript
// evite inserir espaço em branco antes das vírgulas que separam os itens
const correctAnswers = ['A' , 'B' , 'A' , 'A'];

// prefira
const correctAnswers = ['A', 'B', 'A', 'A'];

// evite não deixar espaço em branco entre argumentos
userAnswers.forEach((userAnswer,index) => {
  // ...
})

// prefira
userAnswers.forEach((userAnswer, index) => {
  // ...
})

// evite deixar a abertura do bloco colada no final da condição do if
if(userAnswer == correctAnswers[index]){
  // ...
}

// prefira
if(userAnswer == correctAnswers[index]) {
  // ...
}

// evite deixar o parêntese colado no if
if(userAnswer == correctAnswers[index]) {
  // ...
}

// prefira
if (userAnswer == correctAnswers[index]) {
  // ...
}
```

É isso. Parabéns pelo esforço em implementar a aplicação. 

Alguma coisa que falei acima não ficou claro?

@americosan86

**Comment by americosan86** [comment]
Ficou sim, obrigado pela correção.

**Comment by Roger-Melo** [comment]
Show. Já que ficou mais claro, vou fechar a issue. No que precisar é só abrir uma nova =)
