### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM 01-08 da etapa 05

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1075]
@Roger-Melo
![outrasManeiras](https://user-images.githubusercontent.com/35525950/124048816-89f5dc80-d9ed-11eb-9e71-0ae66b8795a7.jpeg)

**Comment by Roger-Melo** [comment]
Isso aí @AnaCosta29. Rumo à fluência! 🙌🏻
