### ISSUE TITLE
Etapa 07, Exercícios da aula 01

### ISSUE THREAD

**Issue by joaowilian01** [roger-melo-treinamentos/curso-de-js-roger-melo#108]
Roger, segue o link da minha versão do quiz interativo: https://github.com/joaowilian01/quiz-interativo

Maiores dúvidas ou dificuldades durante a execução desse exercício:
- Interação com os elementos HTML;
- Organização do código;
- Dificuldade para saber para qual elemento o "event" está apontando;
- Decidir qual a melhor maneira de selecionar um elemento para utilizar como referência para posicionar o parágrafo com o score;
- Decidir qual a melhor maneira de selecionar um elemento HTML, para selecionar o "h2" eu inspecionei o elemento e usei a opção "Copy selector" do dev tools

Menores dificuldades durante a execução desse exercício:
- Entender a lógica do cálculo da pontução do usuário

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi João wilian. 

Parabéns pelo esforço em implementar a aplicação. Deu pra perceber que você pegou bem a lógica =)

Antes de falar sobre suas dúvidas, vou deixar abaixo uma oportunidade de melhoria na usabilidade da aplicação.

Quando o form é enviado, os pontos são exibidos no topo da aplicação. Se não houver algo que faça o usuário intuir que os pontos estão no topo, o mais provável é que ele pense que nada aconteceu depois de clicar no botão. Se a fonte tiver um destaque maior (tamanho e/ou cor), talvez esse problema seja amenizado.

Uma outra alternativa seria exibir os pontos próximo do local para onde ele está olhando quando envia o form (botão).

Perceba que em uma tela com uma largura menor, quando clico no botão a exibição dos pontos está no topo da aplicação mas fora da tela.

![quiz-form-enviado](https://user-images.githubusercontent.com/29297788/103721214-e383ce00-4fab-11eb-9151-de4a7a5ee3cc.jpg)

Observe que a `scoreParagraphExists` foi declarada sem a palavra-chave `const`, `let` ou `var`.

Um identificador declarado sem uma das 3 palavras-chave automaticamente se torna uma variável global pendurada no objeto window.

```javascript
const removeScoreParagraph = () => {
  scoreParagraphExists = document.querySelector('[data-score="score"]')
  
  console.log(window.scoreParagraphExists) // exibe null no 1º envio do form e <p> no 2º envio
}
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

Vamos às maiores dúvidas ou dificuldades.

> - Interação com os elementos HTML

Em interações com quais elementos HTML você teve dificuldade? 

> - Organização do código;

Organização de código está relacionada à refatoração. No começo, é normal ter dificuldades em refatorar. Continue praticando e seguindo o método e com o tempo, vai ficar natural.

> - Dificuldade para saber para qual elemento o "event" está apontando;

O `event` é a representação de um objeto (disponibilizado pelo browser) que contém informações sobre o evento que aconteceu.

O objeto que o `event` recebe depende do tipo de evento disparado. Se for um evento `submit`, o objeto recebido será um `SubmitEvent`. Se for um clique, `MouseEvent`, e assim por diante. Cada tipo de evento tem um objeto específico com informações sobre o evento.

> - Decidir qual a melhor maneira de selecionar um elemento para utilizar como referência para posicionar o parágrafo com o score;

Não se preocupe com a melhor maneira agora. Em aulas mais avançadas eu mostro boas práticas na hora de selecionar um elemento. 

> - Decidir qual a melhor maneira de selecionar um elemento HTML, para selecionar o "h2" eu inspecionei o elemento e usei a opção "Copy selector" do dev tools

Não use o devtools para esse tipo de caso. Para manipular um elemento do DOM, o ideal é você identificá-lo. 

No caso do h2, você pode adicionar nele uma classe ou um atributo `data-algumacoisa`. Em aulas mais avançadas eu mostro como e por que fazer isso. 

Seletores CSS extensos deixam o código ilegível e mais complicado. Prefira apenas identificar o elemento e obtê-lo através do seletor CSS:

```javascript
// evite
const h2 = document.querySelector('body > div.quiz.py-4.bg-dark > div > h2')

// prefira
const h2 = document.querySelector('.question')

// ou
const h2 = document.querySelector('[data-js="question"]')
```

Está ficando mais claro?

@joaowilian01

**Comment by joaowilian01** [comment]
Oi Roger!

Primeiro quero agradecer pelo seu feedback e pelas aulas, em todas elas eu aprendo algo novo.

Depois que eu abri essa issue eu já vi mais algumas aulas e cheguei no próximo exercício, mas ainda não o finalizei
pois no exercício 04 pede para voltar a trabalhar na nossa versão do quiz, eu estava esperando a avaliação dessa issue para continuar o exercício.

Como eu já vi mais aulas eu entendi a ideia de fazer o scroll da página para visualizar o score quando o form é submetido.
E achei muito interessante a animação do score, foi muito legal aprender a fazer utilizando JavaScript puro.
Com CSS eu tenho bastante dificuldades, por isso acabei deixando o meu score o mais simples possível, mas vou me esforçar mais para aprender a estilizar também.

A variável `scoreParagraphExists` eu acabei esquecendo mesmo de utilizar uma palavra-chave para declarar. Falha minha.

Acho que a dificuldade com os elementos do HTML é meio geral, saber como e qual elemento eu devo selecionar para adicionar um evento, por exemplo. Mas acho que aos poucos eu vou ganhando mais experiência com isso.

Eu ainda estou um pouco confuso com o atributo `data`, no curso foi a primeira vez que eu vi sobre esse atributo. Vai ter aulas explicando sobre ele? Ele tá em alguma documentação que eu posso estudar?

E as suas refatorações tem me ajudado muito, estou começando a ver o código de maneira diferente, exergando como escrever o mesmo código de maneira diferente, mais limpa e eficiente. Muito obrigado!

**Comment by Roger-Melo** [comment]
Legal João Wilian!

> Acho que a dificuldade com os elementos do HTML é meio geral, saber como e qual elemento eu devo selecionar para adicionar um evento, por exemplo. Mas acho que aos poucos eu vou ganhando mais experiência com isso.

Claro. Com a prática, você irá sacando as nuances. Mas na próxima vez que houver uma dúvida ou dificuldade sobre isso, anote a dúvida em um papel. Isso vai aliviar sua mente e ao mesmo tempo, vai te forçar a sintetizar a dúvida.

Às vezes, apenas o fato de escrever a dúvida já deixa a resposta mais clara. E claro, se a dúvida permanecer, poste ela aqui. As chances são que você mostrará um exemplo de código e qual resultado está tentando alcançar. Essa especificidade ajuda a atacar o problema de forma mais acertada =)

> Eu ainda estou um pouco confuso com o atributo data, no curso foi a primeira vez que eu vi sobre esse atributo. Vai ter aulas explicando sobre ele? Ele tá em alguma documentação que eu posso estudar?

O `data-*` é apenas um atributo para você adicionar informações extras em um elemento. Isso facilita identificar e selecionar um elemento, sem usar `id` e `class`. Na primeira aula da etapa 12 eu mostro por que é preferível você usar esse atributo ao invés de usar `id` ou `class`.

Vou deixar abaixo dois artigos do MDN que falam sobre ele:

- [Using data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes);
- [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*).

E claro, se algo dos artigos ou do que eu falei não tiver ficado claro, é só dar o toque =)

@joaowilian01

**Comment by joaowilian01** [comment]
Muito obrigado pelas dicas! Vou ver a documentação do MDN sobre o atributo `data`

**Comment by Roger-Melo** [comment]
Legal João wilian. Estou fechando a issue, mas quando rolarem nodas dúvidas, estou à disposição =)
