### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#1085]
# Adicionando métodos

Um método de um objeto também é formado por um par: propriedade e seu valor.

Exemplo com o objeto User:

```js
let user = {
  name: 'Guilherme',
  age: 25,
  email: 'guilhermerl.dev@gmail.com',
  city: 'Baía Formosa',
  blogPosts: ['Pão de Queijo', 'Brownie'],
  login: function() {
    console.log('Usuário logado');
  }
};
```

Como a propriedade login recebe uma função então ela agora é um método. Para chamar o método, basta usar a notação de ponto seguida pelo nome do método e um abre fecha parênteses ().

```js
user.login();
```

**Funções criadas fora de um objeto são funções e funções criadas dentro de um objeto são métodos.**

Exemplo do objeto User com mais 1 método:

```js
let user = {
  name: 'Guilherme',
  age: 25,
  email: 'guilhermerl.dev@gmail.com',
  city: 'Baía Formosa',
  blogPosts: ['Pão de Queijo', 'Brownie'],
  login: function() {
    console.log('Usuário logado!');
  },
  logout: function() {
    console.log('Usuário deslogado!');
  }
};
```

Para chamar os métodos:

```js
user.login();

user.logout();
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer. Rumo à fluência! 🔥
