### ISSUE TITLE
Etapa 2, nome do vídeo: While loop e exercicios - Aula 01-04

### ISSUE THREAD

**Issue by bindwkill** [roger-melo-treinamentos/curso-de-js-roger-melo#1086]
Olá professor, minha duvida é em relação ao uso do while na linguagem javascript.

Na aula você comentou sobre a necessidade de ter que inicializar um contador e incrementar ele ao final do bloco "manualmente" quando se usa o while, mas eu sei que dá pra usar o while sem contador e consequentemente sem incremento ou decremento em situações como no código abaixo.
```js
let robos = ['r2d2', 'c3po', 'wall-e']
while(robos.length > 0){
 console.log(robos.pop())
}
```
No caso a condição é ter itens no array e, como no bloco de código eu estou tirando itens dele, eu sei que em algum momento esse array vai estar vazio e o loop terminará.
Eu acredito que deve ter jeitos melhores de fazer isso, pelo menos com arrays, mas minha duvida é se essa 'característica' do while é meio inútil mesmo ou se é valido usar ele dessa forma em situações similares.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @bindwkill.

O while só **precisa** de uma expressão: a condição. Qualquer lógica que você faça que impeça um loop infinito é opcional. Então pode ser feito da forma com que vc fez sim, mas a maioria dos exemplos que você vai encontrar por aí usa algum tipo de contador.

> ### minha duvida é se essa 'característica' do while é meio inútil

Na real, o while foi apresentado nessa etapa apenas como uma alternativa ao for mesmo. Você verá nas etapas mais avançadas que ele será praticamente inútil, pois você aprenderá formas mais modernas e elegantes de percorrer arrays e, o mais importante: verá **quando** cada uma delas deve ser usada =)

**Comment by bindwkill** [comment]
Muito obrigado pela resposta, professor!
