### ISSUE TITLE
Etapa 11, Introdução a promises: Aula 04-03

### ISSUE THREAD

**Issue by rezendenetto** [roger-melo-treinamentos/curso-de-js-roger-melo#1087]
Roger,
 
Por que precisamos fazer a getPokemon retornar a invocação de outra getPokemon, no exemplo logo abaixo
```js
getPokemon('https://pokeapi.co/api/v2/pokemon/1')
    .then(pokemon => {
        console.log(pokemon)
        return getPokemon('https://pokeapi.co/api/v2/pokemon/2')
    })
    .then(console.log)
    .catch(error => console.log(error))
```

e não simplesmente assim 👇
```js
getPokemon('https://pokeapi.co/api/v2/pokemon/1')
    .then(pokemon => {
        console.log(pokemon)
        getPokemon('https://pokeapi.co/api/v2/pokemon/2')
        .then(console.log)
    })
    .catch(error => console.log(error))
```

Quais tipos de problemas poderiam ocorrer no meu código?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rezendenetto.

É possível fazer como no segundo exemplo que você deu sim, afinal, a invocação de `getPokemon()` retorna uma promise. Porém, não é recomendado aninhar invocações de `then`.

Observe que quando há um `then` aninhado, existe uma espécie de "triângulo" na indentação do código. Olha como fica com a indentação correta no then aninhado:

```javascript
getPokemon('https://pokeapi.co/api/v2/pokemon/1')
  .then(pokemon => {
    console.log(pokemon)
    getPokemon('https://pokeapi.co/api/v2/pokemon/2')
      .then(console.log)
  })
  .catch(error => console.log(error))
```

Chamamos isso de callback hell, ou pyramid of doom. Eu mostro isso em uma das aulas, você deve estar chegando lá.

Então sempre que usar `then`, encadeie a invocação do próximo then na invocação do then anterior. Isso deixa o código mais legível =)

Ficou mais claro?

**Comment by rezendenetto** [comment]
Perfeito! Deu pra entender agora.

**Comment by Roger-Melo** [comment]
Show @rezendenetto! No que precisar, é só abrir uma nova issue =)
