### ISSUE TITLE
Etapa 14, Correção dos exercícios da aula 01 da etapa 13 - Aula 01-02

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#109]
Roger, neste exercício você utilizou o método some com as propriedades do objeto.
Em minha resolução, acabei convertendo o array albums e o searchAlbum para Json e utilizei o includes.

Seria errado este método ?

```
const albumsToString = JSON.stringify(albums)
const albumToString = JSON.stringify(searchAlbum)

if (albumsToString.includes(albumToString)) {
  console.log(`${albumToString} existe no array albums.`)
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique. 

Como o exercício deixou em aberto a forma de resolução do problema, a sua forma de resolver o exercício poderia ser diferente da minha sim, sem problemas. Apenas certifique-se de ter executado e entendido a resolução que mostrei na correção.

É necessário cuidado ao usar o `stringify`. Na correção do exercício seguinte (5), eu falei sobre as desvantagens de usá-lo em conversões de objetos =)

@henriquebazi

**Comment by henriquebazi** [comment]
Olá Roger, acabei notando rsrs.

Obrigado!

**Comment by Roger-Melo** [comment]
Legal! Por agora vou fechar a issue, mas no que precisar, estou à disposição =)
