### ISSUE TITLE
Resultado do exercício Quiz interativo 

### ISSUE THREAD

**Issue by MarcosCantarutti** [roger-melo-treinamentos/curso-de-js-roger-melo#11]
Nunca utilizei esse recurso de Issues, espero que seja isso mesmo! rsrs segue abaixo o resultado do exercício sobre o Quiz.

https://github.com/MarcosCantarutti/resultado-exercicio-quiz-interativo-

acredito que tive mais dificuldade em manipular os elementos html/css da página. Como pode ver ficou bem esquisito rsrs.

sobre a parte do JS, entendi bem onde buscar os elementos no form que precisávamos para fazer a comparação com nosso array de respostas corretas. E não sei se inseri a resposta na tela de forma esperada.

obs: estou curtindo bastante o conteúdo até aqui, vejo que tenho uma montanha enorme pra escalar e só tenho por volta de 1hr/2hr por dia pra estudar por conta do meu atual trabalho. Mas acredito que um dia vai  melhorar =).  Obrigado por tudo!

**Comment by Roger-Melo** [comment]
Oi Marcos Cantarutti!

Com a prática você se acostuma com as issues e outros recursos do GitHub e não vai mais conseguir ficar sem =D

Fico feliz que esteja curtindo o treinamento.

Vou continuar trabalhando para superar as expectativas e entregar todo o meu conhecimento para que vocês cheguem no "topo da montanha" da fluência.

Sobre a carga horária de estudos, na escalada para a fluência em JavaScript, direção é mais importante que velocidade. Se você está conseguindo manter a frequência diária de estudos, seja por pelo-menos 1h, parabéns pelo esforço, está na direção certa =)

Sobre o exercício, não sei se chegou a ver mas no começo da descrição dele (aqui), foi pedido que a versão do quiz feita pelo aluno abordasse um tema diferente (não pode ser de filmes) e que as cores fossem diferentes do que foi apresentado na aula.

Esses passos são importantes para que você sinta que o projeto é realmente seu e vai ser personalizado da forma que você escolheu.

Quando fizer estes ajustes, me envie novamente para ajustarmos aos poucos os detalhes restantes, combinado? =)

@MarcosCantarutti

**Comment by MarcosCantarutti** [comment]
Desculpe, parece q dei upload no arquivo errado rsrsr, vê se esta correto agora! Obrigado =)

https://github.com/MarcosCantarutti/resultado-exercicio-quiz-interativo-


[resultado exercicio.zip](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/4694903/resultado.exercicio.zip)

**Comment by Roger-Melo** [comment]
Legal Marcos, parabéns pela aplicação =D

Sobre a exibição da resposta na tela, não tem certo ou errado, o intuito era apenas implementá-la, como você fez =)

Nas aulas seguintes (não sei se já chegou a assisti-las), eu mostro como implementar algumas melhorias nessa aplicação e esclareço se é apropriado o projeto ser parte de seu portifólio.

Quando ao código, tome cuidado com o excesso de linhas em branco:

```javascript
const correctAnswers = ['A', 'A', 'A', 'A']

const form = document.querySelector('.quiz-form')
const score = document.querySelector('#userScore')





form.addEventListener('submit', event => {
```

Linhas em branco são separadores de responsabilidade e apenas uma (quando faz sentido) é o suficiente.

Continue aperfeiçoando e evoluindo de acordo com a progressão do projeto nas próximas aulas.

Parabéns pela aplicação =D

Ps: vou fechar a issue mas se rolarem dúvidas é só perguntar.
