### ISSUE TITLE
Etapa 06, Eventos formulários- Aula 01-01 correção do último exercício da Etapa 05 DOM

### ISSUE THREAD

**Issue by marcosmaiadev** [roger-melo-treinamentos/curso-de-js-roger-melo#110]
```js

//exercício etapa 06, aula 01-01 correção do último exercídio da etapa 05 DOM  
const dogs = [...]
const Ze = dogs.find( dog => dog.name === 'ze')

//exercício etapa 05 , aula 02-01 
const people = [...]
const isFrontEndPeople = people.some( person => person.profession === 'Front-end developer')


```

Você se refere ao método some() da seguinte forma: "quando o some() iterou sobre o array..."...

O some() também recebe um parâmetro que pode ser encadeado com uma propriedade de um objeto do array - que está sendo iterado.

Ok! Até aí lembra uma função qualquer. Mas não possui { chaves } pois não executa e sim, apenas testa uma expressão retornando true or false, certo ?

Outra função muito semelhante é a .find()
Elas possuem sintaxe parecida.
Em ambas, ao tentar usar {chaves} logo após o arrow => não funciona. OK, entendo q é por ser uma expressão de teste e não de execução de bloco de código. Mas ela tem uma "habilidade especial" que é receber um parâmetro através de arrow=>

No javaScript, cada método parece ter um tipo de sintaxe. Mas isso é meio arbitrário. É usando e conhecendo. Algumas tem um, dois ou mais argumentos, que terão usos específicos, conforme o método em si.

Depois de conferir um pouco esses métodos (e alguns outros), não ficou muito claro... Existe um padrão para esse tipo de sintaxe que o some() e find() possuem? 
Tem um nome esse "estilo de ser deles", (sua natureza)?  (alguns iteram, outros retornam valores e outros não.. enfim)
Ou melhor ainda, existe uma taxonomia para sintaxes recorrentes em diferentes métodos? ou.. para separar métodos diferentes. 

Sinto que tem algo subentendido que não estou pegando. Ou é porque não tem mesmo? rs...

Desde já, agradeço pela atenção.
Gd abraço.
MM

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcos!

> Você se refere ao método some() da seguinte forma: "quando o some() iterou sobre o array..."...

Isso. Iterar é apenas um termo técnico para "executar uma ação para cada item de um array".

> O some() também recebe um parâmetro que pode ser encadeado com uma propriedade de um objeto do array - que está sendo iterado.

`some` e `find` recebem uma função como argumento. A declaração da função é que contém um parâmetro.

No código abaixo, 

```javascript
const Ze = dogs.find(dog => dog.name === 'ze')
const isFrontEndPeople = people.some(person => person.profession === 'Front-end developer')
```

`find` recebe uma função que contém um parâmetro `dog` e `some` recebe uma função que contém um parâmetro `person`. `dog` e `person` representam cada item do array.

Os parâmetros `dog` e `person` podem ser declarados dentro de parênteses. Mas quando uma arrow function tem apenas 1 parâmetro, o uso dos parênteses não é obrigatório.

Prefira chamar de parâmetro apenas o nome especificado na declaração da função,

```javascript
// event é um parâmetro
const handleInput = event => {
  // ...
}
```

e chamar de argumento apenas os valores inseridos na invocação de uma função ou método:

```javascript
// 'input' e handleInput são argumentos
myInput.addEventListener('input', handleInput)
```

Você verá pessoas chamando argumento de parâmetro e parâmetro de argumento (às vezes eu mesmo erro). Mas é legal você se acostumar com a terminologia correta, por que é a terminologia que a [documentação](https://developer.mozilla.org/en-US/docs/Glossary/Parameter) usa.

> Ok! Até aí lembra uma função qualquer. Mas não possui { chaves } pois não executa e sim, apenas testa uma expressão retornando true or false, certo ?

Na função abaixo, 

```javascript
const Ze = dogs.find(dog => dog.name === 'ze')
```

a expressão `dog.name === 'ze'` é executada e o resultado dela (boolean) é retornado. Ou seja, o `return` é implícito, neste caso.

É possível alcançar o mesmo resultado declarando um bloco e a palavra-chave `return`,

```javascript
const Ze = dogs.find(dog => {
  return dog.name === 'ze'
})
```

mas não faz muito sentido. Afinal, você pode escrever menos e deixar o código mais enxuto e conciso ao usar o `return` implícito da arrow function.

> Depois de conferir um pouco esses métodos (e alguns outros), não ficou muito claro... Existe um padrão para esse tipo de sintaxe que o some() e find() possuem? 

`some` e `find` são métodos que precisam receber, em sua invocação, uma função (callback) como argumento. Essa função sempre precisa retornar um boolean.

O **por quê** de você decidir qual dos dois usar é o seguinte:

- Preciso checar se um array contém um determinado item e, se ele conter, preciso obter esse item: use o `find`;
- Preciso apenas checar se um dos itens do array corresponde à uma determinada condição e, se corresponder, preciso obter um boolean: use o `some`;

> Tem um nome esse "estilo de ser deles", (sua natureza)? (alguns iteram, outros retornam valores e outros não.. enfim)

Sim. Loops como `for` e `while` tem um estilo mais imperativo. Você especifica, passo-a-passo, o que deve ser executado.

`find` e `some` tem uma pegada mais funcional. Você descreve **o que** você quer, sem a necessidade de especificar o passo-a-passo de como o código deve alcançar o que você quer.

Mas não se preocupe muito com esses termos por agora. 

A grande sacada do JavaScript é que ele é multi-paradigma. Então você pode explorar o melhor de cada paradigma e aproveitar ao máximo o uso da linguagem. E você ainda vai ver muito sobre isso no decorrer do treinamento =)

Está ficando mais claro?

@marcosmaiadev

**Comment by marcosmaiadev** [comment]
Siiiiim, Roger.  Eu mirei uma questão, mas foi bom eu ter colocado todo o raciocínio pois vc me tirou uma grande incógnita. Não estava entendendo direito a sintaxe de 
find () e some() ... O porquê deles não aceitarem {chaves} nos meus testes. Na verdade... Um dos argumentos é uma callback. Então sim... Deveriam poder receber a chaves sim. A questão é que nesse caso precisa ser explícito o comando RETURN que eu tinha esquecido dele. De tanto usar console log (que retorna um valor por padrão, como vc já tinha me falado) esqueci que ao usar uma expressão, esperando um retorno , é necessário explicitar o RETURN. Agora fez todo o sentido isso. E essa forma de escrever é aquela simplificação de usar menos código. Apenas isso. Foi burrice minha msm.
Mas é pq olhei no começo da documentação do MDN está exatamente como vc usa nas aulas , então achei q era uma sintaxe diferente da sintaxe de função. Mas não. Só errei o fato de esquecer do RETURN. (E ainda não entendo 100% do q tá na documentação).

Sobre os paradigmas e estilos, beleza. Vou  c calma msm.
Vc tirou uma dúvida q realmente estava me incomodando. O JS não é arbitrário. TD ainda faz sentido ! ❤️😂

Obrigado pelo esclarecimento.

**Comment by Roger-Melo** [comment]
O `console.log()` não retorna um valor. Na verdade é o oposto. A invocação dele exibe um valor no console, mas nada relacionado à esse valor que ele exibiu é retornado. Como em JavaScript, todo código que não retorna uma valor retorna `undefined`, a invocação do `console.log()` acaba retornando `undefined`.

Não e burrice, você está aprendendo. Essas dúvidas são naturais.

Não entender ainda 100% da documentação é parte do processo. Com a prática, o que está escrito ficará mais claro =)

@marcosmaiadev

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas, no que precisar, é só abrir uma nova =)
