### ISSUE TITLE
Resumo da Aula 02-01 a 02-06 da etapa 01

### ISSUE THREAD

**Issue by ederdaniel22** [roger-melo-treinamentos/curso-de-js-roger-melo#1100]
Neste módulo aprendemos sobre as strings, como criá-las, fazer concatenação simples e com template strings, utilização do método slice para cortar parte da string e métodos: toUpperCase e toLowerCase, para mudar as letras iniciais de uma string e também de strings inteiras.
O resultado da aula 02 módulo 1, bem como a inserção da aula 01 módulo 01, conforme foi pedido em issue anterior, estão neste repositório: https://github.com/ederdaniel22/CJS-RM

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ederdaniel22. Rumo à fluência! 🔥
