### ISSUE TITLE
Resumo da Aula Expressões regulares - Aula 01-04 da etapa 06

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1107]
Quando temos um formulário esperamos que as informações digitadas pelo usuário deem match com algum padrão, por exemplo, um *username* deve ter de 6 a 10 caracteres, não deve ter espaços e nem utilizar caracteres especiais. E como fazemos para verificar? Podemos fazer isso com expressões regulares. *Regex* são utilizados para darmos match em combinações de caracteres em *strings*.

*Podemos testar expressões regulares no site [regex101.com](http://regex101.com)

Toda expressão regular começa e termina com barra `/`. Quando queremos dar match em apenas uma palavra, podemos especificar `^` no início e `$` no fim da palavra para indicar que não pode haver nenhum outro caractere antes ou depois dela. Ou seja, ela inicia e termina apenas nela mesma.

Para darmos match com qualquer caractere podemos utilizar o *character set* que é uma lista de caracteres que definimos com a utilização de colchetes, que ficaria por exemplo `/^[a-z]$/gm`. Nesse caso estamos tentando dar match com qualquer *string* de apenas um caractere minúsculo de a até z. Podemos adicionar caracteres maiúsculos a essa *Regex* adicionando `A-Z` logo após o z minúsculo dentro dos colchetes.

Agora para verificar a quantidade de caracteres, de 6 a 10 por exemplo, utilizamos a abertura e fechamento de chaves, que representa a quantidade de caracteres que queremos dar match, no nosso caso `{6,10}`, logo após o fechamento dos colchetes.

E se quisermos ainda permitir números, dentro dos colchetes logo após a verificação de letras maiúsculas, basta incluirmos a informação `0-9`.

Em *Regex*, o ponto `.` representa qualquer caractere.

Para mais sobre expressões regulares: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas. Rumo à fluência! 🔥
