### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1108]
E aí Roger, tudo bem?

Segue a minha segunda aplicação.
- [Repositório da Aplicação](https://github.com/raphaelprsilva/to-do-list-project)
- [To do List](https://www.elraphael.com.br/todo-list/)

### Maiores Dificuldades
- Não consegui encontrar uma maneira de percorrer o DOM, sem ser através de ``classes`` ou ``ids``;
- Não consegui refatorar algumas partes do código (Lógica das linhas 37 à 47);
- Como não utilizei framework para estilização (minha opção), deixar minimamente responsivo, foi trabalhoso (mas valeu à pena);
- Eu dificilmente saberia utilizar os métodos ``trim()``, ``reset()`` e ``toLowerCase()`` para os propósitos especificados na aplicação;

### Maiores Facilidades
- Honestamente? Não achei quase nenhum aspecto do projeto trivial. Então, não tenho pontos com 'Maiores Facilidades';

Eu tentei fazer o projeto com a minha cara, dando o máximo de mim, com o conhecimento que possuo. Achei esse projeto mais difícil que o anterior, e dificilmente conseguiria sair de alguns 'problemas', se não fossem os pontos destacados nas aulas do projeto.

Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by raphaelprsilva** [comment]
Olá @Roger-Melo, tudo bem?

Antes de te enviar a aplicação, ela estava rodando perfeitamente, mas eu fui testá-la novamente, e:
- Ao adicionar mais items, e após isso, ao tentar filtrá-los, o filtro não funciona;
- Se eu aperto 'Enter', no campo de filtro, aparece um ``?search=`` na barra de navegação, dando um refresh na página, mesmo tendo um ``event.preventDefault()`` no ``eventListener``;

Estou lhe passando isso, pois pode ser que impacte na sua análise. Então, eu vou tentar consertar isso, mas caso você analise antes, já pode servir como feedback para mim.

Abraço!

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva. 

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Não consegui encontrar uma maneira de percorrer o DOM, sem ser através de ``classes`` ou ``ids``. Não consegui refatorar algumas partes do código (Lógica das linhas 37 à 47)

Não tem problema. Antes de qualquer coisa, saiba que o mais importante você já fez, que é fazer funcionar!

Sobre percorrer o DOM sem `classes` ou `ids`, você pode usar o `data-js` para manipulação de DOM e deixar class apenas para a estilização e ids para inputs, por conta da acessibilidade do atributo `for` das labels ou quando você quiser fazer âncoras na sua página. 

Você verá como fazer esse tipo de organização de código e também verá como refatorar o código dessa aplicação nas próximas aulas =)

> ### Eu dificilmente saberia utilizar os métodos ``trim()``, ``reset()`` e ``toLowerCase()`` para os propósitos especificados na aplicação;

Você usará o [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) quando precisar remover possíveis espaços em branco do início e do fim de uma string.

O [reset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset) é um método que restaura os valores padrão dos elementos de um form. Neste caso, como os forms dessa aplicação tem apenas inputs, e o valor padrão de um input é uma string vazia, a invocação do reset faz com que o `value` do input receba uma string vazia.

Já o [toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) retorna uma nova string com todos os caracteres minúsculos, baseado na string no qual ele foi invocado. No caso dessa aplicação, foi necessário usá-lo para ter certeza que iríamos comparar duas strings exatamente iguais, pois em JavaScript, strings são case-sensitive.

> ### Ao adicionar mais items, e após isso, ao tentar filtrá-los, o filtro não funciona;

Isso acontece por que `allTodosItems` está armazenando apenas os to-dos de quando a página é carregada (mesmo quando um novo to-do é adicionado). 

Você pode declarar essa const dentro da da função `filterTodos`, antes de executar `filter` e `forEach`. Isso vai fazer com que ela armazene os to-dos no exato momento antes deles serem filtrados =)

> ### Se eu aperto 'Enter', no campo de filtro, aparece um ``?search=`` na barra de navegação, dando um refresh na página, mesmo tendo um ``event.preventDefault()`` no ``eventListener``;

Neste caso, observe que mesmo que haja um `preventDefault`, o callback `filterTodos` está sendo executado quando o valor do `input` é modificado, e não quando o form é enviado.

Você pode adicionar mais de um event listener em um elemento. Então para impedir que a página seja recarregada no envio desse form, basta executar um callback quando essa ação acontecer:

```javascript
formToSearchTodo.addEventListener('submit', e => e.preventDefault());
formToSearchTodo.addEventListener('input', filterTodos);
```

---

Minha única observação sobre o código em si é que eu nomearia a const findTodo como inputValue ou algo parecido, pois findTodo é um verbo.

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by raphaelprsilva** [comment]
Olá Roger, bom dia!

Obrigado pelo feedback, e sim, eles fazem total sentido.

Valeu mais uma vez.

Pode fechar a issue quando quiser.

Abraço.

**Comment by Roger-Melo** [comment]
Show @raphaelprsilva. No que precisar, é só abrir uma nova issue =)
