### ISSUE TITLE
Etapa 12, JavaScript assíncrono

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#111]
Roger tenho uma dúvida sobre uma situação que ocorreu aqui comigo durante uma ```console.log```  que fiz de uma requisição que está sendo feita.  O código é o seguinte:
```js
const getTodos = () => {
  return new Promise((resolve) => {
    const request = new XMLHttpRequest()

    request.addEventListener('readystatechange', () => {
      if (request.readyState === 4 && request.status === 200) {
        resolve(request.responseText)
      }
    })

    request.open('GET', './todos.json')
    request.send()
  })
}

console.log(1)
console.log(2)

console.log(getTodos())

console.log(3)
console.log(4)

// O resultado que obtive foi exatamente esse:
// 1
// 2 

// Promise

// 3
// 4

}
```
Então a partir daí surgiu meu questionamento, dentro do ```console.log(getTodos())``` estou realizando uma requisição e uma requisição é uma operação assíncrona, logo será executada em outra parte do browser enquanto que as demais instruções da thread são lidas normalmente. Bom, baseado nessa afirmação por que o ```console.log(getTodos())``` exibe imediatamente uma Promise? O certo não seria essa Promise ser exibida posteriormente quando todas as outras instruções da thread forem executadas? 

Obs.: Não coloquei a aula pois este foi um problema que encontrei durante uns testes fora de qualquer aula.
Obrigado desde já =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel!

Exibir no console o objeto que representa a promise e exibir o valor da promise resolvida são duas coisas diferentes.

`console.log(getTodos())` apenas exibe (de forma síncrona) a promise que a invocação da função retorna. Independente se a promise foi resolvida ou não.

Uma promise tem 3 estados:

- pending: estado inicial. Nem fulfilled nem rejected;
- fulfilled: indica que a operação foi completada com sucesso;
- rejected: indica que a operação falhou.

O código abaixo checa os estados do objeto que representa a promise. 

```javascript
console.log(1)
console.log(2)

const makeQuerablePromise  = promise => {
  if (promise.isResolved) {
    return promise
  }

  let isPending = true
  let isRejected = false
  let isFulfilled = false

  const result = promise
    .then(v => {
      isFulfilled = true
      isPending = false

      return v 
    })
    .catch(e => {
      isRejected = true
      isPending = false
      
      throw e
    })

  result.isFulfilled = function () { return isFulfilled }
  result.isPending = function () { return isPending }
  result.isRejected = function () { return isRejected }

  return result
}

const originalPromise = getTodos()
const myPromise = makeQuerablePromise(originalPromise)

console.log("fulfilled:", myPromise.isFulfilled())
console.log("rejected:", myPromise.isRejected())
console.log("pending:", myPromise.isPending())

myPromise.then(data => {
  console.log(data)
  console.log('fulfilled:', myPromise.isFulfilled())
  console.log('rejected:', myPromise.isRejected())
  console.log('pending:', myPromise.isPending())
})

console.log(3)
console.log(4)
```

Ao executá-lo, você verá que a sequência de valores exibidos foi:

- 1
- 2
- fulfilled: false
- rejected: false
- pending: true
- 3
- 4
- **exibiu os dados no console**
- fulfilled: true
- rejected: false
- pending: false

Ou seja, quando você executou o código abaixo,

```javascript
console.log(1)
console.log(2)

console.log(getTodos())

console.log(3)
console.log(4)
```

`console.log(getTodos())` apenas exibiu no console uma promise que ainda não havia completado a operação do request pois estava em seu estado inicial. Nem fulfilled nem rejected. Porém, como uma operação assíncrona está sendo executada, a promise só foi resolvida com sucesso (fulfilled) depois da execução de `console.log(3)` e `console.log(4)`.

Sacou a ideia?

@sou-gabriel

**Comment by sou-gabriel** [comment]
Show de bola Roger saquei a ideia agora. Obrigado pela explicação =)
