### ISSUE TITLE
Etapa 14, Correção dos exercícios da aula 01 da etapa 14 - Aula 02-04

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#112]
Fico feliz em compartilhar minha versão do Carousel. 

```
const buttonNext = document.querySelector('[data-js="carousel__button--next"]')
const buttonPrev = document.querySelector('[data-js="carousel__button--prev"]')
const carousels = document.querySelectorAll('[data-js="carousel__item"]')

let indexForExibition = 0
const lastCarousel = carousels.length-1
const visible = 'carousel__item--visible'
const hidden = 'carousel__item--hidden'

const setCarouselClassList = carousel => {
  carousel.classList.remove(visible)
  carousel.classList.add(hidden)
}

buttonNext.addEventListener('click', () => {
  const isTheLastCarousel = indexForExibition === carousels.length - 1
  const isLessThanTheLast = indexForExibition < carousels.length - 1
  const nextCarousel = indexForExibition+1

  if(isTheLastCarousel){
    indexForExibition = 0

    carousels[0].classList.replace(hidden, visible)
    carousels[lastCarousel].classList.replace(visible, hidden)
    return
  }
  
  carousels.forEach(carousel => setCarouselClassList(carousel))

  if(isLessThanTheLast){
    carousels[nextCarousel].classList.replace(hidden, visible)
    
    indexForExibition ++
  }
})

buttonPrev.addEventListener('click', () =>{
  const isFirstCarousel = indexForExibition === 0
  const isBiggerThanTheFirst = indexForExibition > 0
  const prevCarousel = indexForExibition-1

  if(isFirstCarousel){
    carousels[lastCarousel].classList.add(visible)
    carousels[0].classList .replace(visible, hidden)
    
    indexForExibition = lastCarousel
    return
  }
    
  carousels.forEach(carousel => setCarouselClassList(carousel))
  
  if(isBiggerThanTheFirst){
  carousels[prevCarousel].classList.replace(hidden, visible)
    
  indexForExibition --
  }
})
```

Agora verei a correção do exercicio para ver pontos de melhoria. 
Aguardo seus comentários sobre este código. 

Obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique.

Parabéns pelo esforço em construir o carousel sozinho =)

Como você verá a implementação da lógica no vídeo seguinte, minhas observações serão sobre a organização do código.

```javascript
const buttonNext = document.querySelector('[data-js="carousel__button--next"]')
const buttonPrev = document.querySelector('[data-js="carousel__button--prev"]')
const carousels = document.querySelectorAll('[data-js="carousel__item"]')

let indexForExibition = 0
const lastCarousel = carousels.length-1
const visible = 'carousel__item--visible'
const hidden = 'carousel__item--hidden'
```

No código acima, você pode separar a `let` das consts. E também pode manter separadas as consts que estão relacionadas à lógica da aplicação das consts que selecionam os elementos do DOM. Ficaria assim:

```javascript
const buttonNext = document.querySelector('[data-js="carousel__button--next"]')
const buttonPrev = document.querySelector('[data-js="carousel__button--prev"]')
const carousels = document.querySelectorAll('[data-js="carousel__item"]')

const lastCarousel = carousels.length-1
const visible = 'carousel__item--visible'
const hidden = 'carousel__item--hidden'

let indexForExibition = 0
```

`visible` e `hidden` são nomes genéricos que não deixam explícito o que elas estão armazenando. Como elas armazenam uma classe CSS, se você renomeá-las para `visibleClass`, fica mais claro que elas estão armazenando classes CSS.

`carousel` é o nome do componente que contém os itens (imagens/slides). Faz sentido uma const se chamar `carousels` se ela armazena referências de carrosseis. Como essa const está armazenando os itens do carrossel, ela pode se chamar `slides`.

```javascript
const lastCarousel = carousels.length-1
const isTheLastCarousel = indexForExibition === carousels.length - 1
const isLessThanTheLast = indexForExibition < carousels.length - 1
const nextCarousel = indexForExibition+1
```

Nas linhas acima, há uma inconsistência no uso nos operadores matemáticos nas expressões. Alguns contém um espaço antes e depois, outros não.

Prefira sempre deixar um espaço antes e depois. É uma convenção para melhorar a legibilidade. Você verá a maioria dos códigos (inclusive os de exemplo na [documentação](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition)) utilizando essa convenção.

Quando se usa os operadores de pré e pós incremento, mesmo que eles funcionem ao inserir um espaço antes, o melhor é você encadeá-los imediatamente após a variável ou expressão que deve ser pré ou pós decrementada. Também por convenção.

```javascript
// evite
indexForExibition ++
indexForExibition --

// prefira
indexForExibition++
indexForExibition--
```

O código abaixo, por exemplo, funciona. O que não quer dizer que você **deve** escrevê-lo assim.

```javascript
console .log('olá')
```

Novamente, por legibilidade e organização do código, prefira que a condição do `if` tenha um espaço antes e depois, e que um espaço seja inserido na abertura de um bloco de função:

```javascript
// evite
if(isBiggerThanTheFirst){
  // ...
}

buttonPrev.addEventListener('click', () =>{
  // ...
})

// prefira
if (isBiggerThanTheFirst) {
  // ...
}

buttonPrev.addEventListener('click', () => {
  // ...
})
```

Sacou as ideias?

@henriquebazi

**Comment by henriquebazi** [comment]
Obrigado pelos comentários !

**Comment by Roger-Melo** [comment]
Show Henrique. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
