### ISSUE TITLE
Etapa 0, Aula inaugural

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#1127]
Oi Roger, tudo bom? espero que sim.

Roger conclui a etapa 14 do treinamento e, estou implementando os marcos. Inicialmente consegui um estágio; mas estou em busca de vagas como junior, sei que tenho capacidade para isso, mas minha dúvida seria o seguinte: vou iniciar meus estudos em React e por consequencia a prioridade passará a ser ele, porém ainda quero manter os estudos em JavaScript, contudo, estou pensando seriamente em revisar todas as etapas anteriores por meio das minhas anotação realizadas + exercícios, você recomenda isso ou prossigo na etapa 15?

Obs.: Estava em mente revisar o conteúdo pra fixá-lo ainda mais, refinando então assim meus conhecimentos.

Obrigado desde já professor! 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @sou-gabriel. Parabéns! =D

Bom, pelo que analisei em suas aplicações, você já decorou o CJRM 😂, então recomendo que parta para a etapa 15 sim, mesmo que ela ainda esteja em construção.

Sobre a prioridade ser o React, fique tranquilo. Quando vc usa uma lib como o React ou algum framework JS, vc está usando JS. Toda a lógica da sua aplicação vai depender do seu conhecimento de JS puro. Você revisará os fundamentos naturalmente, seja através do CJRM, da doc, de outros cursos, etc =)

Ah, se quiser posso indicar um treinamento muito bom de React, de uma pessoa em que confio =)

**Comment by sou-gabriel** [comment]
> Bom, pelo que analisei em suas aplicações, você já decorou o CJRM 😂, então recomendo que parta para a etapa 15 sim, mesmo que ela ainda esteja em construção.

Sou tartaruga velha aqui já né Roger 😂. Beleza, estarei seguindo adiante então. Vamo que vamo! 

> Sobre a prioridade ser o React, fique tranquilo. Quando vc usa uma lib como o React ou algum framework JS, vc está usando JS. Toda a lógica da sua aplicação vai depender do seu conhecimento de JS puro. Você revisará os fundamentos naturalmente, seja através do CJRM, da doc, de outros cursos, etc =)

Compreendido 100% Roger, tem total razão.

> Ah, se quiser posso indicar um treinamento muito bom de React, de uma pessoa em que confio =)

Com toda certeza professor, aceito a indicação =)

**Comment by Roger-Melo** [comment]
O curso de React que eu indico de olhos fechados é o [React Ninja](https://queroser.ninja/promocoes/) do @fdaciuk. Só vai que é sucesso =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Ótimo professor, agradeço pela recomendação 😁!

**Comment by sou-gabriel** [comment]
Professor você poderia me tirar apenas uma outra dúvida a respeito dos resumos? 
Vi que você tinha comentado em fazer resumos através de bullets points, até comecei a empregar essa prática e tals, porém meus resumos sempre saem um pouco "grandes", pela sua vivência nos meus resumos aqui no treinamento você acredita que estão bons ou devo tentar otimizá-los?

Me perdoe se essa pergunta não deveria ser feita por aqui, não quis perder a oportunidade professor.

**Comment by Roger-Melo** [comment]
Olá @sou-gabriel. Pode fazer perguntas em issues abertas sim, sem problemas =)

Um resumo em bullet points vai exigir que você escreva tópicos mais curtos com frases-gancho, ou seja, frases que vão te fazer relembrar do que é mais importante. 

Pelo que vi [neste resumo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1160), você está escrevendo bem os bullet points sim. Tente manter essa consistência e, com o tempo, você verá que ficará mais fácil diminuir um pouco mais a extensão dos tópicos =)

E apenas frisando... resumo bom é aquele que você revisa. O resumo é apenas uma ferramenta de revisão =)

**Comment by sou-gabriel** [comment]
Feeeeeeeshow professor, é isso ai. Obrigado pela ajuda =)
