### ISSUE TITLE
Resumo da Aula01-04 e 01-05 da etapa 3

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#1129]
# Aula 01-04 
 
## Argumentos, parametros e default parameters 
 Podemos passar valores para dentro de nossas funções e esses valores serão 
 usados como uma variável local para executar uma ação dentro da função. 

```js 
const myFunc = function (name) {
  console.log(`Oi ${name}!`)
}
```

Passamos um parametro dentro dos parenteses na declaração da função, e como uma variável 
 chamamos esse parametro dentro do bloco de código da função. 
 Ao invocar a função devemos passar o argumento (um valor) que desejamos dar à essa variável, 
o parâmetro. 
```js 
myFunc('Elaine') 
//retorna 'Oi Elaine' 

myFunc()

//retorna: 'Oi undefined', pois não foi definido um valor à variável, então javascript atribui 'undefined' à ela.
```

Podemos passar mais de um parametro em uma função.
 Ao atribuir valores a esses parametros na invocação da função eles deverão estar na mesma 
 ordem em que os paremetros foram declarados entre parenteses.
Dentro do bloco de código os parametros podem ser usados em qualquer ordem.

```js 
const myFunction = function (name, lastName) {
  console.log(`Oi ${name} ${lastName}`)
}
myFunction('Elaine', 'Delgado') 
// retorna 'Oi Elaine Delgado'
```

## Default Parameters 
Podemos declarar um valor default para os parametros, caso nenhum valor seja passado 
 na invocação da função, esse valores iniciais serão retornados. 

```js 
const myOtherFunc = function (name = 'Carlota', lastName = 'Joaquina') {
  console.log(`Oi ${name} ${lastName}`)
}

myOtherFunc()
// retorna: 'Oi Carlota Joaquina' 
// Mas se passarmos um argumento para esses parametros, ele subscreve o valor default: 

myOtherFunc('Elaine','Delgado') 

// Se apenas um argumento for passado, apenas o primeiro parametro é subscrito: 
myOtherFunc('Elaine')
// retorna: 'Oi Elaine Joaquina' 
```

# Aula 01-05
## Retornando Valores

Podemos criar funções para que retornem um valor para que sejam utilizados em alguma 
funcionalidade, e não apenas retornar mensagem no console. 
Case declaremos uma variável dentro do bloco de código essa variável só pode ser 
acessada dentro do escopo da função, ou seja, dentro do bloco de código dessa função.

```js 
const double = function (number) {
  const doubleresult = number * 2
  console.log(doubleresult)
}
double(4)
// retorna: 8, na verdade não é um return, a função está apenas escrevendo no console uma mensagem
// que é o resultado da expressão dentro do escopo.  
```

 Para que a funções retorne um valor que possamaos utilizar seu resultado precisamos 
 usar o 'return': 

```js 

const doubleAgain  = function (number) {
  return number * 2
}

doubleAgain(3) 
// retorna 3, mas para utlizarmos esse valor do return usamos uma variável para armazenar esse resultado: 

const result = doubleAgain(3)
console.log(result) 
// retorna: 6 , agora podemos pegar esse valor e usá-lo onde for necessário, nesse caso
// foi usado para escrever 6 no console. 
```

Utilizando o valor retornado em uma função dentro de outra função: 

```js 
const showResult = function (value) {
  return `O resultado da função double é: ${value}`
}
// passamos a const result que armazena o resultado da function double como argumento da 
// função showResult: 
console.log(showResult(result)) 
// retorna 'O resultado da função double é: 6' no console. 
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @ElaineDelgado. Rumo à fluência! 🔥
