### ISSUE TITLE
Etapa 12, Aplicação Weather - Aula 01-02

### ISSUE THREAD

**Issue by luisotacilio** [roger-melo-treinamentos/curso-de-js-roger-melo#113]
Prof. Roger,

Encaminho para conhecimento/avaliação o projeto/exercício da Etapa 12 - Aplicação: Weather, ("com a minha cara") que finalizei com objetivo treinar e ampliar conhecimento. Dei uma “apimentada” nele: para aumentar grau dificuldade utilizei uma outra API do mesmo tema(clima) e alterei o layout da interface/adicionando data do dia e sigla país. Tentei seguir as recomendações com relação a nome de variável/função, fatoração etc...  (rs...inclusive exclusão dos console.log ao fim da fase de desenvolvimento).

Dificuldade:
Fazer destructuring  dos campos cityWheather e cityIconWeather estão aninhados em uma estrutura complicada: objeto/objeto-array/...objeto...

Atenciosamente 

Luís Otacílio
[https://github.com/luisotacilio/CJRM-Etapa12-Aplicacao-Weather](https://github.com/luisotacilio/CJRM-Etapa12-Aplicacao-Weather)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Luis. 

O repositório é [este](https://github.com/luisotacilio/CJRM-Etapa12-Aplicacao-Weather), certo?

Para inserir um link em issues do GitHub, você precisa inserir `[texto do link](url)`. Já consertei isso na issue que você abriu.

Em breve respondo a issue com a análise da aplicação =)

@luisotacilio

**Comment by luisotacilio** [comment]
Exato!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em dom., 10 de jan. de 2021 às 23:12, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Olá, Luis!

Ficou bem legal a personalização que você fez na aplicação, parabéns pelo esforço =)

Vou deixar abaixo algumas oportunidades de melhoria que identifiquei na análise.

#### `autofocus` no input 

Quando a página for carregada (ou recarregada), você já pode deixar um foco no input por padrão, usando no input o atributo `autofocus`. Assim o usuário não precisa mover o cursor do mouse e clicar no input para inserir o nome da cidade.

#### `weather.js`

Na 6ª linha, `url` foi declarada sem a palavra-chave a palavra-chave `const`, `let` ou `var`.

Um identificador declarado sem uma das 3 palavras-chave automaticamente se torna uma variável global pendurada no objeto window.

```javascript
  url = `${baseUrl}data/2.5/weather?q=${cityName}&appid=${APIKey}&units=metric&lang=pt_br`;
  console.log(window.url) // http://api.openweathermap...
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

---

Prefira implementar um componente/elemento alert ao invés de um alert do navegador. 

Se quiser ver um exemplo, veja [essa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2004309), à partir de 25:09.

#### `app.js`

Não sei se você chegou nesse ponto, mas a partir de um determinado momento no treinamento, eu incentivo que o atributo `data-js` (ao invés de `class`) seja usado para selecionar elementos do DOM. Usar `class` apenas para manipulação de CSS e `data-js` para selecionar elementos do DOM separa mais as responsabilidades e melhora a organização do código. 

---

A invocação da `getImageDayOrNight` foi feita antes da declaração dela. Isso não lançou um erro por que neste caso, declarações de `let` e `const` permanecem não-inicializadas. Você não precisa se preocupar em entender isso agora, mas prefira mover a declaração da `getImageDayOrNight` para acima da invocação dela. Isso também deixa mais intuitiva a procura da declaração da função no código. Quando uma função é invocada, a tendência é procurar pela declaração dela acima/antes da invocação.

---

```javascript
const getImageDayOrNight = (inputNow, inputTime) => {
  if (inputNow < inputTime) {
    formImg.innerHTML = `<img src="./img/sunrise.jpg" title="dia">`;
  } else {
    formImg.innerHTML = `<img src="./img/sunset.jpg" title="noite">`;
  }
};
```

No código acima, se você quiser evitar o `else` (o que, particularmente, prefiro), basta inserir um return abaixo da 1ª linha do `if` e deixar a linha que estava dentro do `else` abaixo do `if`. 

```javascript
const getImageDayOrNight = (inputNow, inputTime) => {
  if (inputNow < inputTime) {
    formImg.innerHTML = `<img src="./img/sunrise.jpg" title="dia">`;
    return
  }
  
  formImg.innerHTML = `<img src="./img/sunset.jpg" title="noite">`;
};
```

`else` tende a deixar o código menos legível, por ser um bloco imediatamente encadeado no `if`.

É possível também deixar a condição do `if` mais legível se você armazená-la em uma const que deixe explícito o que `inputNow < inputTime` significa. Quando estamos trabalhando há um certo tempo com um código, certas expressões ficam óbvias para quem as implementou. E essa mesma expressão pode exigir mais carga cognitiva de alguém que a lê pela primeira vez. A `const` pode se chamar `dayTime`, por exemplo.

```javascript
  if (dayTime) {
    // ...
  }
```

---

Um princípio: use linhas em branco para indicar, visualmente, a separação entre conceitos.

No código abaixo, 

```javascript
form.addEventListener('submit', async (event) => {
  event.preventDefault();
  const nameCity = event.target.city.value;
  showInfoWeather(nameCity);
  form.reset();
});
```

você pode separar, visualmente, os conceitos `evitar que a pág. recarregue`, `declaração de const`, `invocações de métodos`. Ficaria assim:

```javascript
form.addEventListener('submit', async (event) => {
  event.preventDefault();
  
  const nameCity = event.target.city.value;
  
  showInfoWeather(nameCity);
  form.reset();
});
```

Você também pode separar conceitos agrupando-os por assunto. No código abaixo, `evitar que a pág. recarregue`, `operações com o nome da cidade` e o `reset do form` são assuntos diferentes:

```javascript
form.addEventListener('submit', async (event) => {
  event.preventDefault();
  
  const nameCity = event.target.city.value;
  showInfoWeather(nameCity);
  
  form.reset();
});
```

Escolha uma das formas e aplique-a em seu código. Isso vai deixá-lo mais consistente e legível.

Se o bloco conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código dentro de um bloco.

Evite inserir linhas em branco onde elas não são esperadas. Início e fim de blocos, por convenção, precisam ser preenchidos com linhas de código.

```javascript
// evite
const showInfoWeather = async (nameCity) => {
  
  const data = await getDataCityWeather(nameCity);
  
  // ...
};

// prefira
const showInfoWeather = async (nameCity) => {
  const data = await getDataCityWeather(nameCity);
  
  // ...
};
```

---

E um último detalhe. Fique atento à gramática nos nomes dos identificadores. 

`an` deve ser usado quando a palavra seguinte começa com um som de vogal. Quando a palavra seguinte começa com som de consoante, use `a`.

Então o nome correto da const `anDay` seria `aDay`. Mas você também pode nomeá-la apenas como `day`.

O que eu disse acima ficou claro?

@luisotacilio

**Comment by luisotacilio** [comment]
Obrigado, Professor, pelas dicas(muitas...kkk...esperava menos) de
melhorias, serão seguidas.  Pode encerrar a "issue".

Em seg., 11 de jan. de 2021 às 23:33, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal Luis! No que precisar, é só dar o toque. Conte comigo para chegar na fluência =)
