### ISSUE TITLE
Etapa 7, Quiz interativo - Exercício aula 01

### ISSUE THREAD

**Issue by RicardoWBraga** [roger-melo-treinamentos/curso-de-js-roger-melo#114]
Opa Roger, beleza? Segue o que foi pedido...

Maiores dúvidas e dificuldades que percebi até aqui:

- A refatoração do código de forma geral. Tenho procurado separar bem as ações dentro código, mas ainda tenho dúvidas de qual a melhor forma de por isso em prática e de enxergar outras melhorias que possam ser feitas. Acredito que com o tempo e experiência isso melhore naturalmente;
- Fico em dúvida em qual a melhor forma de implementar a lógica da aplicação. Também acredito que seja falta de experiência.
- Nomear as variáveis e constantes me traz dúvidas e toma tempo hahah

Menores dificuldades:

- Pegar as referências dos elementos HTML e manipular os mesmos;
- Criar as funções do exercício;
- Criar e adicionar novo elemento HTML;
- Atrelar um evento a um elemento HTML.

Link do repositório: https://github.com/RicardoWBraga/quiz

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Ricardo! Estou analisando a aplicação e em breve te dou o feedback =)

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Antes de qualquer coisa, parabéns pelo esforço em implementar a aplicação =)

O tema ficou divertido e você foi cuidadoso com as linhas em branco no código, inserindo elas para separar conceitos. Também ficou perceptível que você entendeu bem a lógica.

> - A refatoração do código de forma geral. Tenho procurado separar bem as ações dentro código, mas ainda tenho dúvidas de qual a melhor forma de por isso em prática e de enxergar outras melhorias que possam ser feitas. Acredito que com o tempo e experiência isso melhore naturalmente;

Sim, a masterização para refatorar vem com a prática e o tempo. Num primeiro momento o importante é apenas fazer o código funcionar. Depois, vem a refatoração.

> - Fico em dúvida em qual a melhor forma de implementar a lógica da aplicação. Também acredito que seja falta de experiência.

Não se preocupe tanto agora em encontrar a melhor forma de implementar. Você está aprendendo. Conforme avançar no treinamento e aplicar o método, você conhecerá diferentes formas de resolver um problema e isso te dará mais bagagem para tomar decisões baseadas em fundamentos.

> - Nomear as variáveis e constantes me traz dúvidas e toma tempo hahah

Prefira nomear uma variável como um substantivo que deixa explícito o que ela está armazenando.

`resultAnswers`, por exemplo, é um nome que não deixa tão explícito o que ela está armazenando e, talvez pode chegar a confundir. A tradução dela seria "respostas do resultado". 

Ela pode ter um nome que deixa mais explícito que ela armazena as respostas corretas do quiz, como `correctAnswers`. Isso deixa mais claro o motivo pelo qual ela está sendo usada em uma expressão.

Observe a diferença na forma em que as expressões dos ifs abaixo são lidas.

```javascript
if (answer === resultAnswers[index]) { // resposta é igual ao item de "respostas do resultado"
  // ...
}

if (answer === correctAnswers[index]) { // resposta é igual ao item de "respostas corretas"
  // ...
}
```

Se a variável armazenar um boolean, nomeie com `is` como prefixo. Exemplo: `isOdd`.

Ao nomear uma função, prefira usar um verbo que diga a ação que a função está executando. Exemplo: `getName`.

Vou deixar abaixo outras oportunidades de melhoria.

#### Comentários

Um código legível dispensa comentários (pegou o trocadilho?).

Geralmente, comentários são usados para compensar código não-legível. Não foi o seu caso, você usou para identificar tipos de blocos, mas é melhor evitar.

#### Variáveis globais

Prefira usar variáveis globais apenas quando necessário. Variáveis globais ocupam o escopo global e podem colidir com outras de mesmo nome, que estão no mesmo escopo.

Eu apresento esse princípio apenas em etapas mais avançadas do treinamento, mas como vi que você pegou bem a lógica até aqui, é bom que já saiba =)

Geralmente, uma variável global armazena um valor compartilhado entre funções. Nas aulas seguintes você verá que o código dessa aplicação será refatorado. Mas até este estágio dela, uma boa alternativa é declarar `resultAnswers`, `badMessage`, `coolMessage`, `classRedColor` e `classGreenColor` dentro das funções onde elas são usadas.

#### Declaração de parâmetros

No código abaixo, as duas arrow functions contém apenas um parâmetro e isso faz do parênteses um uso opcional. Porém, o parâmetro de uma arrow function contém parênteses e o de outra, não.

```javascript
const insertResultParagraph = (message) => {
  // ...
}

const setClassColor = classColor => {
  // ...
}
```

Escolha inserir ou remover o uso do parênteses em arrow functions com um parâmetro e aplique essa decisão em todas elas. Isso deixa o código mais consistente.

#### Invocação de função ao invés de método

`insertResultParagraph(coolMessage.replace(/{}/, score))` é uma estratégia que funciona. Se você quiser dar mais expressão e legibilidade ao que esse código está fazendo, ao invés de usar o `replace`, você pode criar uma função que recebe o score por parâmetro e retorna a mensagem. 

A invocação dela ficaria assim:

```javascript
insertResultParagraph(getCoolMessage(score))
```

As orientações acima fizeram sentido?

@RicardoWBraga

**Comment by RicardoWBraga** [comment]
Bom dia Roger!

Perfeito!

Deixei algumas coisas "bobas" passarem, como o que você citou sobre as declarações de parâmetros. Vou reler as orientações algumas vezes, para não esquecer mais hehe, prestar mais atenção daqui em diante e refatorar o código novamente.

Grato pelo feedback! É nois!

**Comment by Roger-Melo** [comment]
Excelente Ricardo. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
