### ISSUE TITLE
Etapa 14, Correção dos exercícios da aula 01 da etapa 14 - Aula 02-04

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#115]
Olá professor Roger. Venho abrir essa issue para compartilhar minha alegria em ter concluído o carousel proposto no exercício 36. 

Realizar este carousel foi um desafio e tanto para mim, pois nunca havia feito um. Minhas maiores dificuldades foi no raciocínio da lógica em si, mesmo com um algoritmo "pronto" durante a descrição do exercício senti grandes dificuldades, mas nada que me desanimasse, pelo contrário. Um ponto legal é que a partir do momento que eu abri o paint e comecei a "desenhar" o que estava acontecendo a cada vez que eu clicava no botão as coisas começaram a fazer mais sentido pra mim, e a partir daí a coisa fluiu de vez. No entanto, minhas maiores facilidades em si foi entender o que cada trecho de código que eu implementava fazia, pois estou me sentindo muito confortável programando em JavaScript, graças aos aprendizado que venho adquirindo durante o curso. Abaixo deixei o script Roger, mas o repositório [é este](https://github.com/sou-gabriel/Carousel-CJRM). 

Muito obrigado desde já! =)
 
```js
const carouselButtonNext = document
  .querySelector('[data-js="carousel__button--next"]')
const carouselButtonPrev = document
  .querySelector('[data-js="carousel__button--prev"]')
const carouselItems = document.querySelectorAll('[data-js="carousel__item"]')

let currentItemIndex = 0

const hideAllSlides = () => {
  carouselItems.forEach(item => {
    item.classList.remove('carousel__item--visible')
    item.classList.add('carousel__item--hidden')
  })
}

const showNextSlide = () => {
  const isTheLastSlide = carouselItems.length - 1 === currentItemIndex

  if (isTheLastSlide) {
    currentItemIndex = 0
    carouselItems[currentItemIndex].classList.remove('carousel__item--hidden')
    carouselItems[currentItemIndex].classList.add('carousel__item--visible')
    return
  } 

  currentItemIndex++
  carouselItems[currentItemIndex].classList.remove('carousel__item--hidden')
  carouselItems[currentItemIndex].classList.add('carousel__item--visible')  
}

const showPreviousSlide = () => {
  const isTheFirstSlide = currentItemIndex === 0
  
  if (isTheFirstSlide) {
    currentItemIndex += 2
    carouselItems[currentItemIndex].classList.remove('carousel__item--hidden')
    carouselItems[currentItemIndex].classList.add('carousel__item--visible')  
    return
  }

  currentItemIndex--
  carouselItems[currentItemIndex].classList.remove('carousel__item--hidden')
  carouselItems[currentItemIndex].classList.add('carousel__item--visible') 
}

carouselButtonNext.addEventListener('click', () => {
  hideAllSlides()
  showNextSlide()
})

carouselButtonPrev.addEventListener('click', () => {
  hideAllSlides()
  showPreviousSlide()
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel. 

Parabéns pelo esforço =)

Na aula você verá algumas formas de abstrair essas repetições de manipulação das classes CSS. Mas o mais importante você já está executando: fazer funcionar primeiro e depois se preocupar com refatoração.

Continue seguindo o método e no que precisar, estou aqui =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Shoooow professor 😁
