### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1156]
Podemos utilizar padrões de *Regex* no JavaScript através do método `test()` que é um método de *Regex*. Imagine que temos uma *string* que veio de um *input* de um formulário e queremos testar se essa *string* possui apenas letras minúsculas e no mínimo 6 caracteres, como se fosse um *username* por exemplo. Primeiro criamos um padrão de *Regex*, o atribuindo a uma constante, e em seguida utilizamos o método `test()` passando o *username* (que deverá conter uma *string*) como argumento do método. Em seguida, vamos exibir o resultado do teste no console. O método `test()` retorna um *Boolean*. Vamos ver na prática:

```jsx
const username = 'ricardo';
const pattern = /^[a-z]{6,}$/;
const result = pattern.test(username);

console.log(result); // true
```

Como nosso *username* tem apenas letras minúsculas e tem mais de 6 caracteres, o teste de *Regex* retorna verdadeiro no console. A verificação utilizando o método `test()` é ideal para fazermos verificações em *inputs*, onde inclusive utilizamos o `^` no início e `$` no fim do padrão para indicarmos que não deve vir nada antes e nem depois da `string`, ela deve ser única para que passe no teste.

Uma outra maneira de testarmos é utilizando o método `search()` que é um método de *strings*. Ele é ideal para procurarmos padrões dentro de textos, por exemplo. Logo não devemos utilizar `^` e `$` no padrão. O método recebe como argumento o padrão. Então vamos criar uma constante que recebe um texto, depois um padrão que verifique se existe uma determinada palavra ou qualquer palavra que atenda o padrão, e depois disso fazemos o teste que retornará a posição do padrão encontrado ou retornará -1 caso não haja *match*. Vamos ver na prática:

```jsx
const paragraph = "Lorem ipsum dolor sit amet";
const pattern = /[A-Z]/;
const result = paragraph.search(pattern);

console.log(result) // 0
```

No exemplo acima, o padrão verifica se há alguma letra maiúscula no texto, e a letra é encontrada logo na primeira posição, retornando zero como resultado. Caso não fosse encontrada nenhuma letra maiúscula, -1 seria retornado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência! 🙌🏻
