### ISSUE TITLE
Etapa 7, Quiz interativo - Exercícios da aula 01

### ISSUE THREAD

**Issue by AngeloBastos** [roger-melo-treinamentos/curso-de-js-roger-melo#116]
E aí Roger, beleza?

### Maiores dúvidas ou dificuldades durante a execução do exercício.

- Fazer a refatoração do código é um processo que me deixar com muita duvida, pois não sei se é a melhor forma de se fazer;
- Nomear as variáveis e funções com um nome significativo;
- Insegurança ao desenvolver o código;
- Tentar desenvolver o código da melhor forma possível, me faz perder muito tempo no desenvolvimento.

### Menores dificuldades durante a execução do exercício.

- Criar as funções do exercício;
- Inserir e manipular os elementos DOM;
- Adicionar um evento ao elemento HTML;
- Fazer a referencias dos elementos.

[Link do repositório](https://github.com/AngeloBastos/quiz-interativo)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Thiago.

Passando para avisar que sua issue foi recebida e visualizada, e que o feedback será publicado aqui em breve =)

@AngeloBastos

**Comment by Roger-Melo** [comment]
Oi Angelo. 

Parabéns pelo esforço em implementar a aplicação =)

Refatoração vai ficar natural com o tempo e a prática. Num primeiro momento, foque em fazer o que você fez: fazer funcionar. Com a prática, você começará a encontrar padrões no código e oportunidades de melhoria. Não se preocupe com "a melhor forma de se fazer", por enquanto.

Se a insegurança ao desenvolver o código está relacionada à lógica, faça a [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x).

O código da aplicação está bom. O que eu vejo como oportunidade de melhoria são as linhas em branco.

Use linhas em branco para indicar, visualmente, a separação entre conceitos.

Seguindo este princípio, você pode adicionar uma linha em branco antes das linhas 22, 35 e 44.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

Eu também removeria a linha em branco 61, para agrupar as invocações dos métodos.

Sacou a ideia?

@AngeloBastos

**Comment by AngeloBastos** [comment]
Olá Roger.

Saquei a ideia sim, obrigado por seu feedback.

**Comment by Roger-Melo** [comment]
Excelente! Já que ficou mais claro, vou fechar a issue. Mas no que precisar, é só abrir uma nova =)
