### ISSUE TITLE
Resumo da Aula 03 da etapa 01

### ISSUE THREAD

**Issue by ederdaniel22** [roger-melo-treinamentos/curso-de-js-roger-melo#1168]
Nesta aula aprendemos sobre os arrays, criação, métodos, concatenação, slice, pop e push.
O resultado está no repositório https://github.com/ederdaniel22/CJS-RM

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ederdaniel22, rumo à fluência! 🙌🏻
