### ISSUE TITLE
Etapa 3, Correção de Exercicios da Aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#117]
Oi professor suas aulas são excelentes... Tenho uma sugestão e uma dúvida

Sugestão: Não sei se mais pra frente o Sr. vai ensinar, mas seria bom um módulo ensinando a enviar o nosso código ao github, pq é bem útil....

Dúvida...

No caso de exercícios onde eu consiga completar a tarefa pedida, porém a resolução é diferente da sua,  por exemplo no exercício 5 eu cheguei a essa resolução

``` 
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

let positivos = 0;
let negativos = 0;
let total = 0;

function positivoNegativo(number) {
for(let i = 0; i < randomNumbers.length; i++){
  if(randomNumbers[i] >= 0 ) { positivos++ } else { negativos++ }
  total++
    }
  return console.log(`O array "randomNumbers" possui ${total} números, sendo ${positivos} positivos e ${negativos} negativos.`)
}

positivoNegativo()
```

Quero saber o que devo fazer, caso consiga resolver mas não igual a sua resolução... Admito que a interpretação de algumas coisas pedidas as vezes pode fazer a gente chegar na resolução diferente, mas o que seria melhor a fazer, reescrever como você, ou deixar pra revisão do modo(sempre depois de terminar o módulo estou refazendo todos os exercícios)

ps: estou muito feliz de conseguir chegar nos resultados, seguindo exatamente as regras ou não rs

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi David.

Fico feliz que esteja percebendo progresso em sua jornada rumo à fluência =)

Obrigado pela sugestão. No momento, estou priorizando entregar o que foi prometido como [conteúdo do treinamento](https://drive.google.com/file/d/13RaAC8qjibWEx5wBhaXsSzPuyY0yeZvA/view?usp=sharing). Caso tenha alguma dificuldade com o Git ou GitHub, [este](https://youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A) conteúdo pode te ajudar.

> Quero saber o que devo fazer, caso consiga resolver mas não igual a sua resolução... Admito que a interpretação de algumas coisas pedidas as vezes pode fazer a gente chegar na resolução diferente, mas o que seria melhor a fazer, reescrever como você, ou deixar pra revisão do modo(sempre depois de terminar o módulo estou refazendo todos os exercícios)

Faça [este](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) passo a passo. Eu usei o termo "errar o exercício", mas as recomendações se aplicam também em casos onde você chegou em uma resolução diferente.

Recomendo isso por que geralmente, resolvo exercícios de uma forma que reforce algum conceito visto nas aulas anteriores. Então o ideal é que na aula de correção, ao se deparar com uma diferença entre resoluções, você apague o código que fez e implemente (sozinho) a resolução que foi mostrada na correção. O fato de implementar sozinho vai fazer o seu cérebro absorver o padrão de raciocínio por trás da resolução.

Após conseguir implementar sozinho a resolução mostrada na correção, você pode implementar variações dela =)

Sacou a ideia?

@davidtheblane

**Comment by davidtheblane** [comment]
Entendi professor, muito obrigado.... 
vou continuar o treinamento muito a aprender... rs

Abraço!

**Comment by Roger-Melo** [comment]
Legal David! No que precisar, é só dar o toque =)
