### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by crjstjanojose** [roger-melo-treinamentos/curso-de-js-roger-melo#1170]
- O link da sua versão do quiz; -> https://github.com/crjstjanojose/cjrm-quiz-esportes

Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
-- Fazer uma implementação para desabilitar todos as opções  e ao efetuar o reset reabilitar que pretendo fazer ainda
-- Fazer o componente progressbar voltar ao estado inicial

 Quais foram as suas menores dificuldades durante a execução desse exercício.
--Montar interface, buscar elementos no Dom, remover elementos, alterar atributos

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose. Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar. Deu pra perceber que você pegou bem a lógica até aqui, os pontos de atenção correspondem mais à organização do código.

---

### Idioma

`gabarito` e `progressbar` são exemplos de que dois idiomas foram usados para implementar o código. O ideal é escolher apenas um idioma e ser consistente nessa escolha.

### Convenção de nomenclatura

As consts `painelResultado` e `btnreiniciar` demonstram que houve também uma divergência na escolha de convenção de nomenclatura, pois uma está em camelCase e a outra, não. Escolha uma convenção e seja consistente com essa escolha.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode "agrupar" as consts do topo do código considerando o tipo de valor que elas armazenam.

No exemplo abaixo, eu agrupei as consts que armazenam elementos do DOM e separei elas da const que armazena as respostas corretas:

```javascript
const painelResultado = document.querySelector("[data-js='painel']");
const progressbar = document.querySelector("[data-js='progressbar']");
const btnenviar = document.querySelector("[data-js='btnenviar']");
const btnreiniciar = document.querySelector("[data-js='btnreiniciar']");
const form = document.querySelector("[data-js='formquiz']");

const gabarito = ["B", "A", "A", "B"];
```

### Fluxo de leitura o código

Isso não impacta no funcionamento do código, mas prefira declarar `resetQuiz` antes de sua invocação. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

### Referência de callbacks

Ao invés de declarar uma função que invoca `resetQuiz`, a própria `resetQuiz` pode ser referenciada como callback:

```javascript
const resetQuiz = () => {
  // ...
};

btnreiniciar.addEventListener("click", resetQuiz);
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?
