### ISSUE TITLE
Resumo da Aula 01-02, 01-03, 01-04 e 01-05 da etapa 06

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1175]
## Eventos em formulários - Aula 01-02

  Formulários existem pra capturar algum tipo de informação do usuário

​    \- ex: email e senha

## O evento submit - Aula 01-03

> ​    Na etapa 05, quando a gente queria adicionar um evento de click num elemento,  a gente atrelava um listener de evento diretamente no evento que seria clicado.  Porém pra escutar o envio de um formulário, ao invés de atrelar o listener de evento no botão, iremos atrelar o listener de eventos no form. Porque é o Form  que está sendo enviado e não o botão que é um elemento dentro do form.

```javascript
// obtendo a referência do form
const form = document.querySelector('.signup-form')
// obtendo a referência do input (primeira forma)
const userNameInput = document.querySelector('#username')

form.addEventListener('submit', event => {
  // evita que a página fique recarregando ao clicar no botão
  event.preventDefault()

  // obtendo valor enviado no input (primeira forma)
  console.log(userNameInput.value)

  // forma alternativa de obter valor do input
  console.log(form.username.value)

  // pelo name do input(modifique id para name no index)
  console.log(form.username.value)
})
```

## Expressões regulares - Aula 01-04

​    Expressões regulares são **padrões utilizados para selecionar combinações de caracteres em uma string**. Em JavaScript, expressões regulares também são objetos. Elas podem ser utilizadas com os métodos exec e test do objeto RegExp, e com os  métodos match, replace, search, e split do objeto String.

**comprimento e padrão**

**Atenção: uma expressão regular começa e termina com barra (/)**

site para teste: https://regex101.com/

**exemplo 1:**
>
>   Regular Expression
>
>   /javascript/gm
>
> 
>
>   Test:
>
>   vai dar match com a palavra javascript que estiver dentro da sting testada
>
>   ex: soahskhajs javascript saushisuh

**exemplo 2:**
>
>   Regular Expression
>
>   /^javascript$/gm
>
> 
>
>   Test:
>
>   só vai dar match se javascript estiver sozinho
>
>   ex:javascript

**exemplo 3:**
>
>   Regular Expression
>
>   os colchetes são carácter sets
>
>   /^[a-z]$/gm
> 
>
>   Test:
>
>   vai dar match em um(somente um) carácter de a - z minúsculo
>
>   ex:a

  

**exemplo 4:**
>
>   Regular Expression
>
>   os colchetes são carácter sets
>
>   /^[a-zA-Z]$/gm
> 
>
>   Test:
>
>   vai dar match em um(somente um) carácter de a - z minúsculo ou maiúscula
>
>   ex: a ou A

**exemplo 5:**
>
>   Regular Expression
>
>   os colchetes são carácter sets
>
>   abertura e fechamento de chaves{} representa um quantificador, que indica quantos caracteres queremos dar match
>
>   /^[a-zA-Z]{6,10}$/gm
> 
>
>   Test:
>
>   vai dar match em uma palavra de 6 à 10 caracteres
>
>   ex:javasc

**exemplo 6:**
>
>   Regular Expression
>
>   os colchetes são carácter sets
>
>   abertura e fechamento de chaves{} representa um quantificador, que indica quantos caracteres queremos dar match
>
>   /^[a-zA-Z]{6,10}$/gm
> 
>
>   Test:
>
>   vai dar match em uma palavra de 6 à 10 caracteres, que tenham letras maiúsculas/minúsculas e números de 0-9
>
>   ex:java12

**exemplo 7:**
>
>   Regular Expression
>
> ​    abertura e fechamento de chaves{} representa um quantificador, que indica quantos caracteres queremos dar match
>
> ​    o ponto(.) representa um único carácter que pode ser qualquer carácter
>
>   /^.{6,10}$/gm
>
>
>   Test:
>
>   vai dar match em uma palavra de 6 à 10 caracteres, que use qualquer carácter
>
>   ex:java12

## Testando padrões de regex - Aula 01-05

```javascript
// verificando se username segue o padrão da regex
const username = 'nikson'
const pattern = /^[a-z]{6,}$/

// Em javascript, toda regex tem o método disponível chamado test()
// O método test() vai tentar dar um match entre a regex e a string
const result = pattern.test(username)

// se der match o retorno é true, se não o retorno é false
console.log(result) // true

// o método search() é um método de string(encadeado na string)
// o valor retornado é o número inteiro que corresponde a posição(index) que o match aconteceu
// retorna -1 quando não ocorre match
const result = username.search(pattern) // retorna 0(index) que ocorre o match de acordo com regex

// Atenção: para testar inputs de formulários o mais indicado é o test()
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @NiksonDiniz, rumo à fluência 🙌🏻
