### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#1176]
Minha versão do [weather application](https://github.com/cdfortes/weather-app)

- Maiores Dificuldades 
Isolar as funções com responsabilidade única, sinto algumas dificuldades ainda! :/

- Menores Dificuldades
Replicar a aplicação sozinho feita na aula

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @cdfortes.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @cdfortes.

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

> ## Isolar as funções com responsabilidade única, sinto algumas dificuldades ainda! :/

Refatoração é uma habilidade que evolui com a prática e o tempo. É natural ter uma certa dificuldade no início. Não se preocupe tanto com a refatoração ao enviar as aplicações. O mais importante é fazer funcionar, depois você vai melhorando o código =)

No código que você enviou, eu mudaria apenas duas coisas:

1. A forma com que o ternário da `changeImgDayOrNight` está sendo usado;
2. A condição do `if` da `insertWeatherDataInDOM`.

## O ternário da `changeImgDayOrNight`

Geralmente ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar uma expressão de reatribuição (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu usaria apenas para obter uma string:

```javascript
timeImg.src = IsDayTime ? './src/day.svg' : './src/night.svg'
```

## A condição do `if` da `insertWeatherDataInDOM`

Cuidado com esse tipo de verificação:

```javascript
if (cityWeather) {
  // ...
}
```

No código acima, mesmo que `cityWeather` armazene um objeto vazio por exemplo, o `if` será executado, pois objeto vazio é um valor [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

Então quando verificar um objeto, prefira verificar se ele possui uma propriedade. 

```javascript
if (obj.prop) {
  // ...
}
```

No código acima, se a propriedade `prop` não existir em `obj`, a expressão `obj.prop` resultará em `undefined`. Como `undefined` é um valor falsy, o `if` não será executado. 

Já no caso de um array vazio (que também é um valor truthy), você pode verficar se ele contém algum item:

```javascript
if (arr.length) {
  // ...
}
```

Assim, se `arr.length` resultar em 0, o `if` não será executado, pois 0 do tipo number é um valor falsy.

Esses tipos de casos inesperados serão mostrados com mais detalhes na etapa de TDD =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by cdfortes** [comment]
Obrigado @Roger-Melo,

Muito pertinentes suas observações, são coisas que escapam mas depois de vc o dizer,  fico a pensar como deixei escapar isso =). Por isso suas analises são tão importantes!

abraço!

**Comment by Roger-Melo** [comment]
Show @cdfortes. No que precisar, é só dar o toque =)
