### ISSUE TITLE
Etapa 8 nome do vídeo: Correção dos exercícios da aula 02 da etapa 08 - Aula 01-01

### ISSUE THREAD

**Issue by crjstjanojose** [roger-melo-treinamentos/curso-de-js-roger-melo#1177]
Alguns exercícios pedem para não modificar o Array Original, entendo que o intuito após visualizar as correções seria de usar o encadeamento de métodos, fiz de uma forma diferente usando o Spread.
Teria algum impacto em grandes volume de dados ou na legibilidade  ?

```js
const newNames = [...names].sort();
console.log(newNames);

const nameCopy = names.map((name) => name).sort();
console.log(newNames);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose.

Não há impacto na legibilidade e performance ao usar o spread. É uma solução válida.

Porém, o desafio é você usar apenas o que viu no treinamento para resolver os exercícios. O spread é apresentado na etapa 14 =)

**Comment by crjstjanojose** [comment]
Bom dia @Roger-Melo 

Usei por "impulso"  já que uso  com React em outro treinamento .

Fechado !

Grato;

**Comment by Roger-Melo** [comment]
Show @crjstjanojose. No que precisar, é só dar o toque =)
