### ISSUE TITLE
Etapa 01, Template Strings - Aula 02-06

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#118]
Olá, Roger. 
Estou iniciando o treinamento agora e querendo seguir o método ATER a risca para ter um melhor aproveitamento me surgiram duas dúvidas em relação a revisão. 

No vídeo que você deixou explicando o método ATER é recomendado que nos resumos nós coloquemos 2 exercícios modelos para praticar como revisão. A dúvida é: Onde conseguir esses exercícios? Como saber que tal exercício é bom para servir como modelo?

Uma outra dúvida é em relação a periodicidade das revisões. De quanto em quanto tempo devo revisar uma aula? 

Obrigado. 

Estou gostando bastante do treinamento e a didática é excelente.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Fico feliz que esteja iniciando. Vamos lá =)

Sobre os exercícios-modelo, ao fazer as baterias de exercícios à cada final de aula você perceberá que eles seguem uma sequência gradativa de dificuldade. Isso significa que os últimos exercícios de cada bateria são mais complexos e, se você resolvê-los, consegue resolver outros que envolvem aquele conteúdo (exercícios-modelo).

Se quiser ver um exemplo, observe que [na bateria mais recente](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-38/app.js) de exercícios, o sétimo exercício é, literalmente, uma aplicação.

Ou seja, é um exercício complexo em que você usará muito do que viu no decorrer do treinamento até o ponto do exercício. Se você conseguir implementá-lo, conseguirá implementar outras aplicações semelhantes. Sacou a ideia?

Sobre a periodicidade das revisões, dentro do CJRM, através dos exercícios, eu vou te fazer relembrar assuntos que você já estudou.

Então se você se deparar com um exercício em que não se lembra ou está com dificuldades em resolver aquele tipo de desafio, isso é um indício que aquele assunto precisa ser revisado.

Uma outra forma complementar de revisão que recomendo é a [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x).

Está ficando mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Olá, Roger. 

Entendi sim. E fico muito feliz de saber que dentro do treinamento a metodologia ATER já vai ser aplicada diretamente.
Fiquei preocupado de ter que ir atrás de outros exercícios e fazer as revisões dos conteúdos estudados sempre que possível. 

Mas como você explicou uma vez que a progressão é gradativa, automáticamente iremos rever os conceitos anteriores e isso é ótimo!

Gostei bastante do conceito de revisão raio-x e pretendo aplicá-la daqui a algumas aulas também. 

Muito obrigado pela resposta!

**Comment by Roger-Melo** [comment]
Legal Hamilton! Já que ficou mais claro vou fechar a issue por agora. Mas não hesite em abrir uma nova issue quando tiver dúvidas =)
