### ISSUE TITLE
Resumo da Aula Validação básica de formulários - Aula 02-02 da etapa 06

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1188]
Para validar dados inseridos em um formulário, podemos ter diversas abordagens de tratamento e *feedback* ao usuário. No exemplo que faremos, o *input* do formulário deverá receber um *username* e ele deverá atender as seguintes regras: conter de 6 a 12 caracteres; ter somente letras maiúsculas ou minúsculas; não ter caracteres especiais nem números. Partindo dessas regras, vamos criar uma expressão regular para testar o valor que virá do *input*.

Então vamos supor que tenhamos um formulário com esse *input* único que tenha o `id` com o valor `username` e também uma *tag* de parágrafo vazia com uma classe chamada `feedback`. O primeiro passo como sempre será obter as referências necessárias. Primeiro vamos obter a referência ao formulário e em seguida ao parágrafo de *feedback*, onde iremos inserir uma mensagem ao usuário dependendo do resultado da validação. Em seguida vamos utilizar um escutador de eventos no formulário, utilizando o evento `submit`. Na função de *callback* vamos inserir o argumento `event`, e utilizar seu método `preventDefault()` para evitar o comportamento padrão de recarregamento da página. Em seguida podemos criar a expressão regular que atenda as regras definidas. E aí basta testamos o valor do *input* com a expressão regular e verificar o retorno para dar uma mensagem de "*username* válido" ou então "*username* inválido". Vamos ver na prática:

```jsx
const form = document.querySelector('form');
const feedback = document.querySelector('.feedback');

form.addEventListener('submit', (event) => {
	event.preventDefault();

	const username = event.target.username.value;
	const regex = /[a-zA-Z]{6,12}/;
	const isAValidUsername = regex.test(username);

	if (isAValidUsername) {
		feedback.textContent = 'Username válido.';
		return;
	}

	feedback.textContent = 'Username inválido. O username deve conter de 6 a 12 caracteres e apenas letras maiúsculas e minúsculas.';
});
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas. Rumo à fluência! 🔥
