### ISSUE TITLE
Etapa 02, Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#119]
Olá, Roger. 

Acabei de finalizar a etapa 1 do treinamento e estou corrigindo os exercícios da última aula. 

No primeiro exercício eu cheguei na solução do problema de uma forma diferente da correção. Segue abaixo o meu código: 

```
const my3FavoriteTVShows = ['Breaking Bad', 'The Office', 'The end of the fucking world']
const sentence = `Minhas 3 séries favoritas são: ${my3FavoriteTVShows.join(' e ')
  .replace(' e ', ', ')}.`
```
Como pode ver eu decidi usar a letra 'e' e dois espaços em branco como separador para os intens do Array, e então substituir a primeira ocorrência por vírgula já que é o único lugar que ela deve aparecer. 

Dessa forma qualquer que seja o terceiro título da série o código ainda vai funcionar. 

Acha que há algum problema em ter implementado dessa forma?

Mais uma vez, obrigado. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Hamilton.

Legal! Neste caso, não há problema em solucionar o exercício de forma diferente da que foi mostrada na correção.

Apenas se certifique de executar e entender o código que foi mostrado, pois você perceberá que em etapas mais avançadas, a forma que eu resolvo um exercício de uma bateria pode influenciar na resolução de um outro exercício das próximas baterias =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Entendido. 

Obrigado, professor.

**Comment by Roger-Melo** [comment]
Legal Hamilton. Qualquer dúvida é só chamar aqui =)

**Comment by Landowski** [comment]
Sou da última turma (Maio/2022). Procurei por este tópico para ver se mais alguém teve dúvida parecida com a minha.

Confesso que fiquei um pouco frustrado com a correção desse exercício, porque creio que me cobrei demais, rs.

No enunciado pedia para não acessar o array via índice (e não foi acessado mesmo); tentei, procurei a "solução MDN" por todo lado até que desisti e fui ver a correção, que acabou parecendo um "hack", ou a famosa "gambiarra", já que depende de acessar uma combinação de caracteres específicos, "hard coded", que poderiam até vir antes e substituir uma outra sequência não desejda, pois a solução não é dinâmica.

Eu meio que fiquei pensando: "puxa vida, eu poderia ter feito isso se soubesse que seria assim", hehehe.

Mas entendo que nessa etapa inicial ainda estamos aprendendo a "pensar fora da caixa" e que existem mil maneiras de se resolver um exercício.

Vamos que vamos. 🚀
