### ISSUE TITLE
Aplicação: To-do

### ISSUE THREAD

**Issue by crjstjanojose** [roger-melo-treinamentos/curso-de-js-roger-melo#1195]
Link do repositório do To-do App refatorado o qual tenho grande dificuldade  pessoal de fazer a refatoração. 

 https://github.com/crjstjanojose/todoapp-cjrm-refactory

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

> ## ...o qual tenho grande dificuldade pessoal de fazer a refatoração

Refatoração é uma habilidade que evolui com a prática e o tempo. É natural ter uma certa dificuldade no início. Não se preocupe tanto com a refatoração ao enviar as aplicações. O mais importante é fazer funcionar, depois você vai melhorando o código =)

Fique atento também aos critérios de envio das aplicações. O ideal seria que as cores da sua versão da aplicação fossem diferentes das cores mostradas na aula, ok?

## Organização de código

As observações que tenho sobre o código são apenas sobre a organização do código. Olha só...

### Indentação

O markup HTML dentro da `insertHTML` pode ter as tags `span` e `i` indentadas em um nível à mais. Assim, fica mais fácil identificar que essas tags estão dentro da `li` =)

### Nomes de variáveis e funções

O "a" que vem após o "A" da `formAaddTodo` pode ser removido.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`insertHTML` é um pouco vaga pois não descreve ao certo do que se trata o HTML. Para deixá-la mais descritiva, eu a nomearia como `insertTodo`.

A expressão `Array.from(clickedElement.classList).includes("delete")` poderia ser armazenada em uma variável que descreve o valor que a expressão gera. Por exemplo, `clickedElementHasDeleteClass`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação, inclusive eliminando o uso da navegação pelo DOM com o `parentNode`.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by crjstjanojose** [comment]
Bom dia,

Sim fizeram sentido e realmente o tempo vai mudando a nossa forma de entender como essas melhorias.

Grato

**Comment by Roger-Melo** [comment]
Show @crjstjanojose. No que precisar, é só abrir uma nova issue =)
