### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by alexvieirasj** [roger-melo-treinamentos/curso-de-js-roger-melo#1196]
Minha versão do **Quiz** https://github.com/alexvieirasj/quiz-application

Maiores Dificuldades:
- Lembrar de certas sintaxes, estou me acostumando a usar o MDN

Menores Dificuldades
- Navegar no DOM para buscar os elementos

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @alexvieirasj.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @alexvieirasj. 

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar. Deu pra perceber que você pegou bem a lógica até aqui, os pontos de atenção correspondem mais à organização do código.

---

Se você quiser, pode usar interpolação ao invés de concatenação ao precisar renderizar o valor de uma variável em uma string. Observe que o código tende a ficar um pouco menor e mais legível:

```javascript
// antes
alert('Voce acertou ' + score + '% do Quiz')

// depois
alert(`Voce acertou ${score}% do Quiz`)
```

Observe também que a palavra "Voce" ficou sem acento no "e".

`usersAnswer` pode ser nomeada como `userAnswer`, com o "user" no singular.

E uma última coisa que eu faria é remover a linha 18 (em branco). Linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código. Além disso, é uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by alexvieirasj** [comment]
Com certeza, todas os apontamentos foram de grande ajuda. Vou fazer um commit de alteração para fazer as correções indicadas. Obrigado pelo retorno.

**Comment by Roger-Melo** [comment]
Show @alexvieirasj. No que precisar, é só abrir uma nova issue =)
