### ISSUE TITLE
DOM

### ISSUE THREAD

**Issue by gbr-jpg** [roger-melo-treinamentos/curso-de-js-roger-melo#12]
Oi professor, estou com uma dúvida. Lendo a documentação do NodeList e do HTMLCollection percebi que a diferença dos dois é que um é estático e o outro é "vivo". Bom, sempre que criarmos um NodeList ele será estático então. Mas ai entra minha dúvida, ele não reconhecerá os novos elementos que eu puser no DOM caso este elemento novo tenha o mesmo nome de classe que o elemento que gerou o NodeList por meio do querySelectorAll ?

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Isso mesmo.

Métodos `get*`, como o `getElementsByTagName`, geram um HTMLCollection dinâmico. 

Se eu tenho um HTML com a marcação abaixo e exibo no console a quantidade de itens do HTMLCollection, ele retorna a quantidade atual de `li`'s (2).

```HTML
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
  </ul>

  <div>Div 1</div>
  <div>Div 2</div>
```

```JavaScript
const lis = document.getElementsByTagName('li')

// HTMLCollection - dinâmico
console.log(lis.length) // 2
```

Mas se eu adicionar uma `li` no DOM e verificar novamente a quantidade de itens do `HTMLCollection`, ele retorna a quantidade atualizada de `li`'s:

```JavaScript
const ul = document.querySelector('ul')
const lis = document.getElementsByTagName('li')

// HTMLCollection - dinâmico
console.log(lis.length) // 2
ul.innerHTML += '<li>Item 3</li>'
console.log(lis.length) // 3
```

Já o `querySelectorAll` retorna um `NodeList` **estático**. Ou seja, a nova `div` não será atualizada automaticamente no NodeList:

```JavaScript
const ul = document.querySelector('ul')
const lis = document.getElementsByTagName('li')
const divs = document.querySelectorAll('div')

// HTMLCollection - dinâmico
console.log(lis.length) // 2
ul.innerHTML += '<li>Item 3</li>'
console.log(lis.length) // 3

// NodeList - estático
console.log(divs.length) // 2
document.body.innerHTML += '<div>Div 3</div>'
console.log(divs.length) // 2
```

NodeLists são estáticos, [exceto quando gerados pela `childNodes`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Live_vs._Static_NodeLists).

Ficou claro?

@gbr-jpg

**Comment by gbr-jpg** [comment]
Claríssimo professor, agora eu entendi =)

**Comment by Roger-Melo** [comment]
@gbr-jpg show.

Vou fechar a issue mas no que precisar, pode perguntar =)
