### ISSUE TITLE
Meu Quiz interativo

### ISSUE THREAD

**Issue by Rodrigo-M-Brazao** [roger-melo-treinamentos/curso-de-js-roger-melo#120]
Queria saber como enviar o quiz?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rodrigo. 

Existem algumas formas. Você pode criar um repositório no GitHub e me enviar o link, ou simplesmente subir os arquivos em seu Google Drive e me enviar o link =)

Independente da forma que escolher, no momento de postar o link não se esqueça de descrever na issue o que o exercício pediu.

Se mais pra frente você perceber que está te fazendo falta, você pode estudar Git e GitHub, mas nada obrigatório por agora.

Fico no aguardo da sua aplicação e no que eu puder ajudar, é só dar o toque =)

@Rodrigo-M-Brazao

**Comment by Roger-Melo** [comment]
Olá @Rodrigo-M-Brazao.

Você resolveu a dúvida? Vou fechar a issue mas no que precisar é só dar o toque que abro novamente.
