### ISSUE TITLE
Etapa 09 - Nome do vídeo: Removendo to-dos

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1206]
### Olá Roger!

***Nessa aula você mostra o método de array ``includes()`` junto ao classList, para verificar se o item clicado possui a classe ``'delete'``.***

```js
todosContainer.addEventListener('click', event => {
    const clickedElement = event.target

    if (Array.from(clickedElement.classList).includes('delete')) {
        clickedElement.parentElement.remove()
    }
})
```
<br>

***❓ Minha duvida é: tem algum problema se fosse colocado o método ``contains()`` que a classList possui, para fazer essa mesma verificação? como o exemplo abaixo:***

```js
todosContainer.addEventListener('click', event => {
    const clickedElement = event.target

    if (clickedElement.classList.contains('delete')) {
        clickedElement.parentElement.remove()
    }
})
```
> Grato *Mateus Barros*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros.

Eu usei o `includes` mas sim, o `contains` pode ser usado tranquilamente neste caso e isso deixaria o código mais conciso, afinal, a transformação em array não seria necessária =)

**Comment by Mateus20Barros** [comment]
ok 👍

**Comment by Roger-Melo** [comment]
Show @Mateus20Barros. No que precisar, é só abrir uma nova issue =)
