### ISSUE TITLE
Resumo da Aula Eventos do teclado - Aula 02-03 da etapa 06

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1207]
É possível com JavaScript capturar informações vindas do teclado. Então a cada tecla pressionada, assim que a mesma é solta, um evento poderá ser capturado, e este evento é o `keyup`. Podemos utilizar o `keyup` para fazer validações em formulários em tempo real. Ou seja, conforme um usuário for digitando um nome de usuário por exemplo, poderemos validar a cada caractere digitado, informando visualmente se aquele *username* é válido ou não. Então vamos imaginar que tenhamos um formulário, com `id` de valor *username*, e vamos verificar se este *username* tem de 6 a 12 caracteres e que também só contenha letras minúsculas e maiúsculas. Se o que foi digitado não atenda a validação, iremos inserir uma borda vermelha no *input*, e caso atenda a validação, iremos inserir uma borda verde no *input*. Para isso vamos precisar criar também duas classes CSS para serem utilizadas: uma de sucesso e uma de erro. Então vamos para a prática, primeiro criando as classes CSS:

```css
input {
	outline: none;
}

.success {
	border: 2px solid green;
}

.error {
	border: 2px solid red;
}
```

Observação: Inseri um `outline: none` no *input* para que não fique com a borda preta quando o input tem o foco.

E agora vamos para a escuta do evento `keyup` no JavaScript:

```jsx
const input = document.querySelector('input');

const usernameRegex = username => /^[a-zA-Z]{6,12}$/.test(username);

input.addEventListener('keyup', event => {
	const isAValidUsername = usernameRegex(event.target.value);

	if (isAValidUsername) {
		event.target.setAttribute('class', 'success');
		return;
	}

	event.target.setAttribute('class', 'error');
});
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Rumo à fluência! 🙌🏻
