### ISSUE TITLE
Conversor de Moedas

### ISSUE THREAD

**Issue by allanpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#1208]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/allanpedro/conversor-de-moedas.git

### Maiores dificuldades durante a implementação

Refatoração do código

### Menores dificuldades durante a implementação

realização a requisição da API

**Comment by Roger-Melo** [comment]
Olá @allanpedro.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @allanpedro. Parabéns pelo esforço em construir a aplicação =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar.

## Propriedades do objeto da `getErrorMessage`

`'unsupported-cod'` e `'malformed-reques'` são propriedades que não existem como Error Responses da API. Acho que quando você copiou o nome dos erros, algumas letras ficaram de fora.

## Indentação

Faltou ajustar a indentação dentro das funções `showAlert` e `showInitialInfo`. 

Na expressão abaixo, 

```javascript
  return Object.keys(conversion_rates)
  .map(getOptionsAsArray)
  .join(' ')
```

é necessário indentar os métodos `map` e `join`, pois não faz sentido eles estarem no mesmo nível de indentação do `return`. Indentar esses métodos  sinaliza, visualmente, que esse encadeamento é uma continuação da linha acima.

Em análises de suas aplicações passadas também houveram observações sobre indentação. Cuidado para não repetir os mesmos erros.

## USD estático

O parágrafo com o `data-js="conversion-precision"` está com "USD" de forma estática. Ou seja, mesmo que o valor do input da primeira moeda seja modificado, "USD" sempre será exibido.

---

As observações fizeram sentido?

**Comment by allanpedro** [comment]
Bom dia profº 

Fizeram sentido sim, obrigado! já estou corrigindo.

**Comment by Roger-Melo** [comment]
Show @allanpedro. No que precisar, é só abrir uma nova issue =)
