### ISSUE TITLE
Etapa 1, Constantes, variáveis e comentários - Aula 01-06

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#121]
Não consigo visualizar meus códigos no console da página.
![2021-02-01 (1)](https://user-images.githubusercontent.com/78214862/106497226-87be3f00-649c-11eb-8174-5e7a7ee4772f.png)
![2021-02-01](https://user-images.githubusercontent.com/78214862/106497260-9147a700-649c-11eb-9d31-868fe61fcc6a.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Yure.

Isso aconteceu por que na tag `<script>`, o atributo `src` está inserido como conteúdo da tag.

Para resolver isso, é necessário apenas inserir o `src="./app.js"` como atributo da tag, e não como conteúdo.

Então ficaria assim:

```html
<script src="./app.js"></script>
```

Sacou a ideia?

Se o problema persistir é só avisar =)

@YureK-a

**Comment by YureK-a** [comment]
> Sacnossa era só isso
