### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#1212]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/RicarGit/Project-Currency-Converter

### Maiores dificuldades durante a implementação

Bom, aí que veio a bomba, eu enrosquei em algo que eu me achava bom, manipulação do DOM, não conseguia passar as informações para os selects, depois não conseguia pegar informações de um select pra comparar com o outro select para extrair as conversões das moedas...

Tentei uma, mexi aqui e ali, desisti, apaguei tudo...
No outro dia tentei mais uma, não conseguia, não entrava na minha cabeça como fazer, desisti, apaguei tudo...
No outro dia tentei pela terceira vez já todo frustrado, desacreditado, não foi de novo...

Fiquei 1 semana sem ver código, descansei a mente, voltei pra academia naquela semana, joguei bastante video-game, fui passear, esqueci que o exercício existia!

Voltei pro computador, mas agora confiante, eu sabia que não era um bicho de sete cabeças, já tinha feito coisa mais difícil, fui fazendo aos poucos, uma coisa de cada vez, sem querer ficar refatorando função antes de terminar, sem se preocupar tanto com nomes de variáveis, quando refatorei eu mudei muitos nomes de variáveis, organização de código, desacoplamento de função, enfim, não está o melhor código do mundo mas "por enquanto" é o melhor que consegui fazer, e dessa vez não tive dificuldade nenhuma!

Obs: eu sei que eu preciso tratar os erros que a API fornece, fiz algo genérico porquê não sabia como receber todos os erros e retornar uma mensagem customizada pra cada erro!

Obs2: eu sei também que a variável que foi criada globalmente com informações da API pra serem usadas em outras funções não é uma boa prática, porém é algo que ainda não sei como fazer, depois de ter postado meu resumo estarei assistindo as correções!

### Menores dificuldades durante a implementação

Buscar dados da API

Lí a documentação dela e achei bem simples, não me lembro de ter visto muito a da accuWeather mas essa me pareceu bem simples, vi que ela tinha um endpoint mais simples que recebia o nome das duas moedas no endpoint e já retornava o valor das moedas convertidas porém não seria viável pra essa aplicação já que ela não fornecia os nomes das moedas pro usuário ter varias opções ali pra selecionar, teria que ser em um input de texto mesmo e a pessoa teria que saber o nome abreviado das moedas, vi também que outro endpoint mais "rico" em informação (Pago) fornecia o nome inteiro da moeda incluindo a bandeira do país e o símbolo da moeda, achei bem bacana, nunca tinha parado pra ler uma documentação dessa forma!

**Comment by Roger-Melo** [comment]
Olá @RicarGit.

Parabéns pelo esforço em construir a aplicação. 

É natural ter uma certa dificuldade neste exercício. O mais importante é fazer funcionar, depois você vai melhorando o código =)

Nas próximas aulas você verá como melhorar o código dessa aplicação. 

Porém, algo que pode ser feito é verificar se o request foi bem sucedido, através da propriedade `ok`:

```javascript
try {
  const response = await fetch(url)

  if (!response.ok) {
    throw new Error('blá blá blá...')
  }

  const exchangeData = await response.json()

  // ...
}
```

De qualquer forma, se houver algum problema de conexão na rede, `await response.json()` iria lançar um erro, mas com a verificação na `ok`, fica mais fácil identificar qual tipo de erro aconteceu devido a mensagem personalizada que `Error()` recebe.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by RicarGit** [comment]
> Porém, algo que pode ser feito é verificar se o request foi bem sucedido, através da propriedade ok

Quer dizer que eu teria que ter duas verificações dentro do try, uma pra response e uma pra resposta da API, então pelo que eu entendi o exchangeData só retorna algum erro que aconteceu entre a API, então se uma conexão falhasse por exemplo até cairia no catch mas exibiria um erro genérico e pra isso eu teria que checar o 'ok' do objeto Response pra fazer um tratamento de erro personalizado (tipo: _sem conexão, verifique sua rede ou contate o seu provedor de internet para mais informações._) correto?

Aproveitando novamente de uma issue, à medida que avançamos no curso, digo avançamos porque creio que não sou só eu mas vão surgindo mais e mais perguntas sobre estrutura de dados, esse seria o meio correto de criar uma aplicação?
Existe um padrão de separação de arquivos js pra determinadas funções?
No caso de POO deveríamos começar a escrever o código já pensando como estruturar orientado à objetos?
Essas mudanças acontecem só durante a refatoração?

Daria até uma ideia de criar uma área de perguntas, as mais frequentes (FAQ) e também as mais interessantes ganhariam uma área somente delas com as respostas ou até mesmo vídeos no YouTube (shorts) respondendo algumas!

**Comment by Roger-Melo** [comment]
> ## Quer dizer que eu teria que ter duas verificações dentro do try...

Isso. Mas fique atento com essa afirmação: "uma pra response e uma pra resposta da API"...

`response` é o objeto que contém a resposta da API, por isso ele tem esse nome. 

```javascript
try {
  const response = await fetch(url)

  if (!response.ok) {
    throw new Error('blá blá blá...')
  }

  const exchangeData = await response.json()

  // ...
}
```

No código acima, a propriedade `ok` do objeto response armazena um boolean que indica se o status da resposta está entre [200 e 299](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses), que são os status que indicam que tudo correu bem com o request e que a resposta foi obtida com sucesso.

Se `if (!response.ok)` resulta em true, isso significa que os dados não foram obtidos, então é necessário lançar um erro para que o `catch` receba esse erro. Como eu mostrei [nas aulas](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1376383), a forma como o fetch trabalha é rejeitando a promise quando acontece um erro de conexão na rede. Quando a internet cai, por exemplo.

Se o primeiro `if` não foi executado, como esse objeto `response` contém a string JSON com as informações que eu preciso, pra parsear esse JSON para objeto javascript, eu encadeio no response a invocação do `.json()`, a expressão `response.json()` resulta em uma promise com o resultado do parseamento do JSON pra javascript (objeto), e pra desencapsular esse resultado, basta inserir `await` antes da expressão:

```javascript
const exchangeData = await response.json()
```

Porém, pode ser que a propriedade `result` do `exchangeData` esteja armazenando [este objeto](https://www.exchangerate-api.com/docs/standard-requests) de erro, e não um objeto de 'success'. Por isso o `if (exchangeData.result === 'error')` é necessário.

---

> ## ...estrutura de dados, esse seria o meio correto de criar uma aplicação?

Mais valioso do que aprender, é aprender e executar o que faz sentido para o seu momento. 

Quando você usa arrays, objetos e funções, você está trabalhando com estruturas de dados. 

Se você se refere à tópicos de algoritimos e estrutura de dados avançados, como árvore binária, Linked Lists, Big O notation, etc, você não vai encontrar isso no CJRM. Por que o CJRM não é um curso de ciência da computação.

O CJRM é um treinamento para iniciantes em front-end que querem construir suas aplicações com JavaScript puro, montar o portfólio, [aplicar e conquistar uma vaga](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo#depoimentos-de-alunos). As vagas de front-end Junior ou Pleno que você encontrar geralmente não vão pedir um conhecimento profundo de algoritimos e estrutura de dados, a não ser que você esteja se candidatando para trabalhar em gigantes como Google, Amazon, Netflix, Spotity, etc.

> ## Existe um padrão de separação de arquivos js pra determinadas funções?

Sim, isso varia de acordo com a arquitetura e ferramentas que o time escolhe seguir. 

Pra React, por exemplo, vc deve pensar sempre o mais simples possível.. sua aplicação vai ter páginas? Começa com um diretório `pages` e separa os componentes de cada página em um diretório dentro desse pages.

Vai ter componentes compartilhados? Cria um diretório `ui` e coloca eles ali.

Um outro importante é ter um diretório resources, pra vc colocar contexts, hooks "globais", utilitários, helpers, etc.

E padronizar sempre criando um index que só exporta tudo do diretório, pra facilitar o import depois, não deixando de lado o arquivo jsconfig.json (ou tsconfig se usar TS), pra fazer os imports absolutos à partir da src.

Esse é o mínimo de um app *production ready* e com esse mínimo você já cobre pelo menos 80% das necessidades de arquitetura que precisa.

> ## No caso de POO deveríamos começar a escrever o código já pensando como estruturar orientado à objetos?

Em JS puro, vc tem a liberdade de extrair o melhor dos paradigmas. Porém, libs como o React vão te forçar a pensar de maneira mais funcional e vc vai levar esses conceitos pelo resto de sua carreira. Se for para escolher, tenha uma pegada mais funcional. Suas aplicações serão mais fáceis de manter.

> ## Essas mudanças acontecem só durante a refatoração?

A forma mais eficaz que eu conheço de escrever código é seguindo o TDD. Refatoração é uma etapa a ser cumprida, quando necessário. Mas TDD é um assunto mais avançado. Se você está iniciando, recomendo ver o que as vagas que te interessam pedem e identificar os pontos mais relevantes nelas.

> ## Não costumo fazer comentários nos códigos, colocar nomes bem explicativos em funções e variáveis elimina a necessidade de comentar?

Com certeza. Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

> ## Commits: Quando realmente é necessário "commitar"?

Existem vários patterns, esse tipo de dúvida fica respondida de forma mais clara quando você trabalha em um time. Não acho que vale a pena se preocupar com isso agora. 

> ## Sobre o curso: nessa etapa 15, vc já diria que estamos em que nível de conhecimento da linguagem, intermediário pra avançado, avançado, saindo do avançado e indo pra algo além do avançado?

Quem vai te dizer isso é a empresa. Não existe resposta certa. 

Se você seguiu o método e chegou na etapa atual do treinamento, provavelmente já consegue construir aplicações com js puro sozinho e conquistar uma vaga de front-end jr =)

@RicarGit

**Comment by RicarGit** [comment]
Obrigado pelas respostas @Roger-Melo!!!

Só mais uma coisinha que reparei no código, após checar o !response.ok reparei que qualquer erro no código cai no if dele e lança o erro de conexão, não sei se é algo errado no meu código mas mudando a chave da API cai no if, colocando uma moeda inválida também cai no if e não vai mais pro if que lança os erros personalizados da API.
O response.ok não teria que vir false somente se fosse erro de conexão?

**Comment by Roger-Melo** [comment]
> ## O response.ok não teria que vir false somente se fosse erro de conexão?

Não. 

A forma como o fetch trabalha é rejeitando a promise [quando acontece um erro de conexão na rede](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful). Quando a internet cai, por exemplo.

Se você inserir uma chave de API incorreta na URL (ou inserir uma moeda inválida) e executar o request, verá que `response` armazena um objeto com a propriedade `ok` armazenando `false` e `exchangeData` armazena o objeto que a API retornou:

```javascript
const APIKey = 'x'

// ...

const fetchExchangeData = async endpoint => {
  try {
    const response = await fetch(endpoint)
    const exchangeData = await response.json()
    
    console.log(response) // {ok: false, …}
    console.log(exchangeData) // {result: "error", …}
    
    // ...
}
```

Então nesse caso, uma alternativa é inverter a ordem dos ifs:

```javascript
const fetchExchangeData = async endpoint => {
  try {
    const response = await fetch(endpoint)
    const exchangeData = await response.json()

    if (exchangeData.result === 'error') {
      throw new Error(getErrorMessage(exchangeData['error-type']))
    }

    if (!response.ok) {
      throw new Error('Sua conexão falhou. Não foi possível obter os dados.')
    }

    return exchangeData
  } catch (error) {
    showAlert(error.message)
  }
}
```

Assim, `!response.ok` só vai resultar em `true` quando o `if` acima não for executado (ou seja, quando o objeto da API não for recebido).

Sacou a ideia?

@RicarGit

**Comment by Roger-Melo** [comment]
@RicarGit vou fechar a issue mas no que precisar, é só reabrir ou abrir uma nova e perguntar =)
