### ISSUE TITLE
Resumo das Aulas 01,02,03,04 da etapa 05

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#1216]
## Document Object Model (DOM)
Toda pagina web é um documento, e quando o navegador renderiza a pagina, é criado uma arvore de nós (nodes) referenciando cada elemento do documento e disponibilizando via API para ser acessado por qualquer linguagem de programação. (normalmente linguagens de script como javascript)

Éssa arvore de nós (nodes) disponibilizada via API é chamada de DOM, então podemos definir que DOM é uma interface de programação para documentos HTML e XML. Ele representa a pagina para que programas possam acessar e modificar sua estrura, stilos e conteudo através de propriedades e métodos.

## querySelector e querySelectorAll
O querySelector() é um método do document que retorna o primeiro elemento que corresponda ao seletor ou grupo de seletores especificados. 
Com ele conseguimos referenciar o elemento para poder altera-lo no DOM.

Já o querySelectorALL retorna um nodeList com todos os elementos que corresponda ao seletor ou grupo de seletores.
O nodelist tem um formato de array, e com isso é possivel iterar pelos itens do nodeList e passar alguns métodos que tem por padrão.

## getAttribute e setAttribute
O getAttribute pega os valores dos atributos de um elemento especifico podendo armazer em memoria.
Já o setAttribute adiciona ou modifica um attributo existente especifico.

## parent, children, sibling
Conforme já mencionado, a arvore do DOM é construída a partir do HTML, e é através dela que podemos ter acesso aos elementos do documento. A arvore do DOM trabalha com conceitos parents (pais), children (filhos), sibling (irmãos) para referenciar os nodes da arvore e comisso acessar os nós adjacentes, assim como os subsequentes e os que pertencem a outros nós (nodes)

## event bubbling e event delegation
Event delegation é quando adicionamos um listenner de evento no pai para tomar ação a partir dos eventos realizados nos elementos filhos. Conseguimos ter acesso ao elemento filho pelo pai através o event target que borbulha do filho quando o evento é realizado no filho.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuniorAlvesbr, rumo à fluência! 🔥
