### ISSUE TITLE
Etapa 3, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by higoroficial-city** [roger-melo-treinamentos/curso-de-js-roger-melo#122]
```js

const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']

let newArray = []
const wordsInUpperCase = function (array = []) {
  
  for (let i = 0; i < millennialWords.length; i++) {
    newArray.push(millennialWords[i].toUpperCase())
  }
  return array
}
console.log(wordsInUpperCase(newArray))

```

Olá Roger, resolvi o exercício 4 desta forma e funcionou igual ao seu. No caso aqui é o uso errado da função ou só outra forma de resolvê-lo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Higor.

Sim, é uma outra forma de alcançar o resultado. Porém, fique atento aos seguintes pontos:

### Nome da função

Nomes de funções precisam ser verbos. O nome precisa descrever a ação que a função está executando. Por isso, o nome que dei à função na correção do exercício foi `transformToUpperCase`.

### Novo array inserido como argumento

Considerando que o nome da função deve ser uma ação, observe que a leitura da invocação da função abaixo não faz sentido:

```javascript
transformToUpperCase(newArray)
```

Fica confuso ler que um novo array está sendo transformado em letras maiúsculas. Por isso o ideal é que o array que contém as palavras a serem transformadas seja inserido como argumento. Veja como a leitura da invocação da função faz mais sentido agora:

```javascript
// antes
transformToUpperCase(newArray)

// depois
transformToUpperCase(millennialWords)
```

### Essa função precisa ser genérica

A ideia principal por trás dessa função é ela ser flexível à ponto de receber arrays diferentes à cada invocação.

No código abaixo,

```javascript
const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']
const anotherWords = ['oi', 'olá', 'alô']

let newArray = []
const wordsInUpperCase = function (array = []) {
  
  for (let i = 0; i < millennialWords.length; i++) {
    newArray.push(millennialWords[i].toUpperCase())
  }

  return array
}

console.log(wordsInUpperCase(newArray))
console.log(wordsInUpperCase(anotherWords))
```

a invocação `wordsInUpperCase(anotherWords)` fez o parâmetro `array` receber o array `anotherWords` (['oi', 'olá', 'alô']), o for loop é executado fazendo os itens do `millennialWords` convertidos em letras maiúsculas serem adicionados novamente no `newArray`, e depois da execução do for loop, array é retornado.

Ou seja, a função `wordsInUpperCase` está fazendo nada com array `['oi', 'olá', 'alô']` que ela recebeu por parâmetro. A invocação `wordsInUpperCase(anotherWords)` apenas retornou no array `['oi', 'olá', 'alô']`, as palavras continuam com letras minúsculas.

Por isso é necessário seguir à risca o que foi mostrado na correção:

- Quando `let newArray = []` é criada dentro da função, à cada invocação da função um novo array é criado na memória;
- O parâmetro `array` precisa ser usado dentro da função, ao invés da `millennialWords`.

Ficaria assim (como mostrado na resolução):

```javascript
const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']
const anotherWords = ['oi', 'olá', 'alô']

const wordsInUpperCase = function (array = []) {
  let newArray = []
  
  for (let i = 0; i < array.length; i++) {
    newArray.push(array[i].toUpperCase())
  }

  return newArray
}

console.log(wordsInUpperCase(millennialWords)) // ["LOL", "YOLO", ...]
console.log(wordsInUpperCase(anotherWords)) // ["OI", "OLÁ", "ALÔ"]
```

Por isso, no começo, aplicando o que eu [recomendei nessa revisão](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/78#issuecomment-721458855), faça seu cérebro se acostumar com a resolução mostrada na correção do exercício. Recomendo isso por que geralmente, resolvo exercícios reforçando algum conceito visto nas aulas anteriores e com base no que está por vir. Vai chegar o momento de inovar a receita. Mas por agora, siga ela à risca =)

Está ficando mais claro?

@higoroficial-city

**Comment by higoroficial-city** [comment]
> Quando let newArray = [] é criada dentro da função, à cada invocação da função um novo array é criado na memória;

Roger, isso aqui foi chave pra mim. Sinceramente não me lembro de ter ouvido isso nas aulas anteriores aos exercícios. Ficarei atento a isso de agora em diante.

Sobre a nomenclatura de variáveis e refatoração de código, confesso que os estou erroneamente negligenciando, por estar focado em aprender a construção do código em si e uso em diferentes cenários (mesmo sabendo que pode não ser a hora pra isso), me esforçando em utilizar a resolução do exercício como último recurso, mas nem sempre é possível. Então devo usar e abusar de sua recomendação de revisão.

E como você pôde perceber, AINDA estou na etapa 03 do curso, com tantos meses já passados, mas é que não gostaria de dar continuidade ser antes ter - quase - completo domínio do assunto anterior... Espero não demorar mais tanto assim.

**Comment by Roger-Melo** [comment]
> Roger, isso aqui foi chave pra mim. Sinceramente não me lembro de ter ouvido isso nas aulas anteriores aos exercícios. Ficarei atento a isso de agora em diante.

Esse assunto será explicado na etapa 5, nas aulas sobre escopo =)

> E como você pôde perceber, AINDA estou na etapa 03 do curso, com tantos meses já passados, mas é que não gostaria de dar continuidade ser antes ter - quase - completo domínio do assunto anterior... Espero não demorar mais tanto assim.

Seja você coelho ou tartaruga, demorar não é problema. Problema é não aprender. Estude no seu ritmo, sem pressa e sem pausa.

No que eu puder ajudar, é só dar o toque =)

@higoroficial-city

**Comment by higoroficial-city** [comment]
> Esse assunto será explicado na etapa 5, nas aulas sobre escopo =)

Ah sim. Mal vejo a hora de chegar lá, escopo ainda me confunde.

> Seja você coelho ou tartaruga, demorar não é problema. Problema é não aprender. Estude no seu ritmo, sem pressa e sem pausa.

Boa dica. Obrigado pela resposta.  :D
