### ISSUE TITLE
Resumo da Aula Parent,Children,Sibling 03-02 da etapa 05

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1222]
@Roger-Melo
![parent_children](https://user-images.githubusercontent.com/35525950/125538646-636f1e68-5660-4d2b-9bdf-82f18bc840f2.jpeg)
![continuacao_parent](https://user-images.githubusercontent.com/35525950/125538677-f4ced828-1488-4ce6-8cf1-aa6e23f1480d.jpeg)

**Comment by Roger-Melo** [comment]
Boa @AnaCosta29, rumo à fluência! 🔥
