### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by Sephyros** [roger-melo-treinamentos/curso-de-js-roger-melo#1224]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Sephyros/procrastination-list

### Maiores dificuldades durante a implementação

Tive uma certa dificuldade devido ter ficado tentando implementar a adição e remoção das classes com o "toggle" ao invés de simplesmente fazer as duas coisas ao mesmo tempo (pesquisar os todos que não possuem o input e adicionar o hidden removendo d-flex e depois separadamente pesquisar os que possuem o input e remover o hidden adicionando o d-flex.

Outro fator que inclusive não consegui realizar devido minha abrangente imaginação foi a refatoração para não "navegar" no parent para remover o li. Posso (e com certeza acho que isso aconteceu) ter entendido de forma errada o exercício, perdi várias horas implementando diversos modos de se achar o li correto para remover mas sempre me perguntava se aquele modo era suficiente ou se algo que fiz poderia mudar devido a alteração do HTML... no fim me perguntei "e se o que for mudar é o ul, ou o li, ou remover o span, e se o texto tiver em um p, ou se tiver que clicar diretamente no li?" no fim resolvi ir pra frente, ignorando a refatoração, o tempo é escasso e me sinto seguro de progredir, talvez foi so uma má interpretação e na verdade eu acabei tentando criar uma bazuca para matar baratas enquanto apenas o chinelo era suficiente...

### Menores dificuldades durante a implementação

No geral foi simples, as aulas anteriores prepararam muitíssimo bem o terreno para a implementação do projeto, utilização do includes, transformações de HTMLCollection para array, adição e remoção de classes nos elementos, obtenção de valores dos elementos e etc. Removi o li de formas menos "amigáveis" até sem querer achar o remove (graças o intelisense) e dar uma olhada no mdn. É muito bom poder focar na linguagem em si e na lógica sem se preocupar com o HTML e CSS

**Comment by Roger-Melo** [comment]
Olá @Sephyros!

Parabéns pelo esforço em construir a segunda aplicação, novamente deu pra perceber que você entendeu bem a lógica até aqui =)

Tenho apenas uma observação sobre nomes de variáveis e funções...

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso, a expressão `Array.from(clickedElement.classList).includes("fa-trash-alt")` pode ser armazenada em uma const que descreve o valor que a expressão gera. Por exemplo, `clickedElementHasDeleteClass`. Isso também deixaria o `if` mais legível =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. 

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Sephyros** [comment]
Boa noite @Roger-Melo!
Sim! fizeram bastante sentido!
Vou me atentar mais  e começar a incorporar esses métodos de nomeação também!
