### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1227]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

:octocat: [Repositório da Aplicação](https://github.com/Mateus20Barros/to-do-list)

### Maiores dificuldades durante a implementação

**Me surgiram algumas dificuldades no desenvolvimento dessa aplicação, não em relação ao que foi mostrado nas aulas, mas sim na hora de implementar as novas funcionalidades que implementei na mesma. A refatoração é um pouco complicado, pois tive um certo problema com isso no meu codigo, o mesmo estava rodando com perfeição sem o ``refactoring``, quando refatorei o mesmo houve bastante ``bug``, quebrei a cabeça mais consegui resolve-los.**

### ⚙️ New Functions

**🔥 Acrescentei um botão para inserir um novo ``to-do`` na lista, pois a aplicação tem duas opções para inserir items na lista, ou clicando no ``botão`` ou pressionando a tecla``enter``**

**🔥 Coloquei um ``overflow: auto;`` no ``CSS`` da ``ul`` que armazena os ``to-dos``, pois assim dando um ``scroll`` nos ``to-dos`` podemos ver os demais itens existentes.**

**🔥 Implementei uma função que mostra a quantidade de ``to-dos`` que existe na lista. O valor é incrementado ou decrementado de acordo com os items inseridos ou removidos da lista. Se existir pelo menos 1 ``to-do`` na lista, o numero com a quantidade de item será mostrado na cor ``verde``, caso contrario, o contador será 0 e sua cor ``vermelha``.**

**🔥 Adicionei outro botão que apaga todos os ``to-dos`` de uma única vez. Nessa parte tive um pouco de dificuldade, pois quando apagar todos os ``to-dos``, o contador será zerado, e quando inserir os novos ``to-dos`` o contador iniciará em 0 é e incrementado em 1 quando um novo ``to-do`` e inserido.**

### Menores dificuldades durante a implementação

**Creio que as minhas menores dificuldades foram implementar as funcionalidades que foram mostradas nas aulas.**

**Optei por fazer a aplicação com ``HTML`` ``CSS`` e ``Javascript`` puro, sem qualquer tipos e biblioteca como o ``bootstrap`` que vem sendo utilizado no curso para agilizar o desenvolvimento do ``CSS`` das aplicações. Assim posso por em pratica os conhecimentos sobre as tecnologias voltadas para o desenvolvimento web.**

**🚀 Hoje tenho a capacidade de implementar algo a mais do que foi desenvolvido nas aulas. Pois dessa forma acho que posso testar o que realmente estou aprendendo no curso, e não simplesmente copiar códigos. 🚀**

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros!

Parabéns pelo esforço em construir a aplicação, deu pra perceber que vc pegou bem a lógica até aqui =)

Minhas observações são as seguintes...

A `changeColorQuantity` pode ser simplificada com o uso de um ternário ao invés de if:

```javascript
const changeColorQuantity = () => {
  showTotalTodos.style.color = todos.length === 0 
    ? 'rgba(255, 0, 0, 1)' 
    : 'rgba(0, 255, 0, .8)'
}
```

Usar ou não usar ternário vai do gosto de cada um. Particularmente, acho que nesse caso o código não fica tão complicado e a função fica mais concisa =)

---

Alguns ajustes que eu faria nos nomes das funções:

- `countTodos` ao invés de `counterTodos`
- `deleteAllTodos` ao invés de `deleteAllEventListener`
- `manipulateClasses` (no plural) ao invés de `manipulateClass`
- `todosToHide` (no plural) ao invés de `todoToHide`
- `searchTodos` ao invés de `formSearchEventListener`
- Como atualmente a `todosContainerEventListener` apenas deleta os todos, eu a nomearia como `deleteTodo`

---

A `deleteAllTodos` pode conter a lógica de remoção dos todos, assim a `removeAllTodos` pode ser removida do código e o `forEach` pode ser substituído apenas por uma atribuição de string vazia para a ul:

```javascript
const deleteAllTodos = () => {
  todosContainer.innerHTML = ''
  setQuantityInfo()
}
```

---

A `addTodoEventListener` pode ser eliminada e `addTodo` pode conter toda a lógica de adicionar todos:

```javascript
const addTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    todosContainer.innerHTML += `
      <li class="flex-box" data-todo="${inputValue}">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
      </li>
    `

    countTodos(++todos.length)
    event.target.reset()
  }
}
```

---

Hoje, eu refatoraria as funções dessa forma:

```javascript
const hideTodos = (todos, inputValue) => {
  const options = { todos, inputValue, returnMatchedTodos: false }
  
  manipulateClasses({
    todos: filterTodos(options),
    classToAdd: 'hidden',
    classToRemove: 'flex-box'
  })
}
```

Inclusive, estou pensando em incluir um exercício que instigue o aluno a deixar essas funções mais claras em relação ao que os argumentos delas significam. Sei que especificar objetos como argumento deixa o código mais verboso. Por outro lado, acho que fica mais legível. 

O que acha?

---

- A `todosContainerEventListener` pode ser eliminada e a lógica ficaria apenas dentro da `deleteTodo`:

```javascript
const deleteTodo = event => {
  const trashDataValue = event.target.dataset.trash
  
  if (trashDataValue) {
    const todo = document.querySelector(`[data-todo="${trashDataValue}"]`)

    todo.remove()
    countTodos(--todos.length)
  }
}
```

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Mateus20Barros** [comment]
### Olá 👋 Roger Melo!

**Cara sensacional suas dicas sobre refatoração, irei dar uma nova olhada e implementar esse ``refactoring`` no meu código  para deixa-lo mais conciso.**

> *Inclusive, estou pensando em incluir um exercício que instigue o aluno a deixar essas funções mais claras em relação ao que os argumentos delas significam. Sei que especificar objetos como argumento deixa o código mais verboso. Por outro lado, acho que fica mais legível.*

**Será um exercício bastante desafiador, pois como você mesmo disse, que especificar objetos como argumento deixa o código verboso, na maioria das vezes quando refatoramos o código aparece alguns ``bugs``, pois algum parâmetro passado como argumento é ``undefined`` ou ``paramenter is not a function`` não é uma função, enfim sempre gera algum problema, mais creio que com esses erros que resolvemos nosso código, ajuda-nos a compreender melhor o que realmente acontece por baixo dos panos na linguagem, e assim chegar a ``fluência em Javascript``.**

**É sim, as observações fizeram sentido, pois sempre é bom adquirir essas formas de ``refactoring`` para que possamos implementar códigos mais concisos e de fácil compreensão, não para o computador, mais sim para outros desenvolvedores, pois isso e realmente um desafio gigantesco, ter que implementar codigos que outros programadores(as) tenha a capacidade de entender assim como quem os escreveu.**

👍 Grato Mateus Barros

**Comment by Roger-Melo** [comment]
Total @Mateus20Barros, o importante é dar um passo de cada vez. Pode parecer muita coisa no começo, mas quebrando os problemas em partes fica mais fácil =)

No que precisar, é só dar o toque =)
