### ISSUE TITLE
Dica de aplicativo para revisar conteúdo

### ISSUE THREAD

**Issue by BernardoOficial** [roger-melo-treinamentos/curso-de-js-roger-melo#123]
Olá, Roger! Tudo bom? Sou novato na plataforma ✌️😊

Queria saber se vc (ou algum colega) tem conhecimento de algum aplicativo/programa em que fosse possível marca o dia/mes/ano em que estudei determinado conteúdo, por exemplo hoje, dia 03/02/2021. E depois de uma quantidade especifica de dias, vamos dizer 30 dias, ele me avisasse que faz um mês que estudei tal conteúdo. Assim, eu terei uma maior organização para revisar o conteúdo do curso.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Bernardo.

Bem-vindo!

Não conheço um app focado nisso, mas costumo usar o [Google Calendar](https://www.google.com/calendar/about/) e ele atende muito bem. Depois que acostumei a usar, é difícil ficar sem =)

@BernardoOficial

**Comment by BernardoOficial** [comment]
@Roger-Melo era isso mesmo que eu procurava. Nesse aplicativo eles tem um opção para organizar o que eu quero.

Vlw, muito obrigado.

**Comment by Roger-Melo** [comment]
Legal Bernardo. Cuidado, calendar vicia =D

Já que ficou mais claro, vou fechar a issue por agora. Quando surgirem novas dúvidas, não hesite em perguntar =)
