### ISSUE TITLE
Aplicação: [To-do List]

### ISSUE THREAD

**Issue by CaioHTeixeira** [roger-melo-treinamentos/curso-de-js-roger-melo#1233]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/CaioHTeixeira/Aplicacao-To-do-List

### Maiores dificuldades durante a implementação

A maior dificuldade foi implementar a parte da exclusão dos todos sem utilizar o parentElement. Não sei se nas aulas anteriores foi passado algo a respeito do dataset, por não ter conseguido pensar em uma solução diferente para a exclusão sem utilizar o parentElement eu acabei vendo a correção e vi que foi usado o dataset e refiz a refatoração da exclusão do zero depois utilizando ele.

Outra coisa que não entendi foi o motivo de você ter pedido pra não usar o parentElement na exclusão mas ter usado o children no inputSearchTodo para pegar as 'lis'. Em tese, ambos não se enquadram na mesma situação de navegação pelo DOM conforme explicado no exercício que futuramente poderia haver mudança? 

Na implementação dos data-todos e data-trash o ideal é pegar o conteúdo das lis e colocar neles realmente? Eu achei estranho pois se o conteúdo delas for muito grande vai ficar uma coisa gigante. 

### Menores dificuldades durante a implementação

A menor dificuldade foi para desenvolver a criação de novos todos.

**Comment by Roger-Melo** [comment]
Olá @CaioHTeixeira .

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @CaioHTeixeira!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

Sobre o dataset eu acrescentei agora, na descrição do exercício, uma dica para a pessoa pesquisar pelo dataset. Valeu pelo feedback =)

> ## Outra coisa que não entendi foi o motivo de você ter pedido pra não usar o parentElement na exclusão mas ter usado o children no inputSearchTodo para pegar as 'lis'. 

Nesse caso, você está apenas obtendo as lis, e não-necesariamente navegando pelo DOM.

Já o uso do `parentElement` pode ser perigoso se você mudar a sua marcação, pois ao alterar a marcação, você pode mudar quem é o `parentElement` e fazer sua aplicação quebrar.

Para evitar isso, é mais seguro criar uma identificação específica para cada li, adicionar essa mesma identificação no botão de deleção e dessa forma, ao clicar no botão, você consegue comparar as identificações e remover a li exata, sem precisar fazer "malabarismos" com `parentElement`, saca? =)

> ## Na implementação dos data-todos e data-trash o ideal é pegar o conteúdo das lis e colocar neles realmente? Eu achei estranho pois se o conteúdo delas for muito grande vai ficar uma coisa gigante.

O necessário é que a li e o botão tenham a mesma identificação. Por se tratar de um to-do list, não é comum que um to-do tenha um texto extenso. E não haveria problema se tivesse.

Há outras formas de gerar uma identificação aleatória, mas para o escopo dessa aplicação, a forma mostrada nas aulas se adequa bem.

Na etapa 15 você verá uma outra forma de gerar ids aleatórios =)

---

Fique atento aos critérios de envio das aplicações. O ideal seria que as cores da sua versão da aplicação fossem diferentes das cores mostradas na aula, ok?

Minhas observações sobre o código são as seguintes...

Como você não está escrevendo JSX, os parênteses usados para envolver o retorno da `addTodo` são opcionais.

Na função `const resetFormAddTodo = () => event.target.reset()` o `event` global está sendo usado.

Mesmo que tenha funcionado, o ideal é que o event seja passado como argumento da função:

```javascript
const resetFormAddTodo = event => event.target.reset()

// invocação da função
resetFormAddTodo(event)
```

Isso por que o [event global](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) foi descontinuado. O VSCode até insere um traço no meio de propriedades e métodos que foram descontinuados/depreciados.

Quando você insere o event como parâmetro de um callback de listener de evento, ao invés de usar o event global, você está usando o [Event interface](https://developer.mozilla.org/en-US/docs/Web/API/Event) =)

Cuidado ao omitir blocos de ifs. [Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos atrás e colocou a segurança de dados em xeque graças a esse tipo de decisão.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by CaioHTeixeira** [comment]
Obrigado pelo feedback, fizeram sentido sim. Com relação ao event, eu achei que estava dando certo por causa do eventDelegation/eventPropagation que você havia mostrado nas aulas anteriores. Aí pensei que mesmo sem passar o event por parâmetro ele reconhecia por isso. 
Esse caso da omissão dos blocos do if que ocorreu com a Apple eu não conhecia. Sempre costumava usar if's sem blocos quando possuía apenas uma linha, vou começar a usar sempre os blocos a partir de hj =)

**Comment by Roger-Melo** [comment]
> ## Eu notei que se digitar algo grande no to-do ele vai pra fora do limite definido

Você pode usar a propriedade [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) no `span`.

Aqui tem um [bom post](https://css-tricks.com/almanac/properties/w/word-break/) sobre isso =)

@CaioHTeixeira

**Comment by CaioHTeixeira** [comment]
Tranquilo, obrigado =)
