### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#1235]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edcabralc/quiz-app.git

### Maiores dificuldades durante a implementação

Tentei remover o forEach de dentro do Listener de Evento para organizar o código, mas a `let score` passa para outro escopo isso gerou um bug que não consegui resolver.

### Menores dificuldades durante a implementação

A lógica do quiz e a manipulação dos elementos do DOM. 
Achei minha evolução, bastante significativa e fico muito feliz por isso.

**Ansioso por seu feedback.**

**Comment by Roger-Melo** [comment]
Olá @edcabralc.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @edcabralc!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém abra a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte superior (não-visível) da tela:

![envio-do-quiz](https://user-images.githubusercontent.com/29297788/125951782-28c16116-b18d-494b-ba5c-fa4bbacc0368.jpg)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

## Lógica

A div `userAnswersFeedback` não precisa ser manipulada a cada execução do `forEach`. 

A única ação que precisa acontecer dentro do `forEach` é o cálculo dos pontos. O `return` pode ser eliminado do `if` e `userAnswersFeedback` pode ser manipulada apenas após o cálculo dos pontos:

```javascript
const showUserScore = (userAnswer, index) => {
  const isACorrectAnswer = userAnswer === correctAnswers[index];

  if (isACorrectAnswer) {
    score += 20;
  }
};

userAnswers.forEach(showUserScore);
userAnswersFeedback.classList.add("show");
userAnswersFeedback.textContent = `Você acertou ${score}% das respostas`;
```

## Organização de código

É apenas uma convenção mas, se possível, prefira manter no topo do código as consts que armazenam elementos do DOM. Nesse caso, o código ficaria assim:

```javascript
const form = document.querySelector("form");
const input = document.querySelectorAll("input");
const userAnswersFeedback = document.querySelector(".answers-container");

const correctAnswers = ["A", "A", "A", "A", "A"];
```

A `const input` não está sendo usada, então ela pode ser removida.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`form` é uma const vaga, pois não descreve sobre o que se trata o form. Como essa aplicação tem apenas um form, isso não é tão crítico. Mas acredito que `quizForm` descreve de forma mais clara sobre o que se trata esse form. Saca?

Seguindo esse mesmo raciocínio, `handleSubmit` pode ser nomeada como `handleQuizSubmit`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by edcabralc** [comment]
Fala, Roger!

Suas observações fizeram total sentido, após refatorar o código e corrigir os erros irei subir para o Netlify .

Grato por sua atenção.

**Comment by Roger-Melo** [comment]
Show @edcabralc. No que precisar, é só abrir uma nova issue =)
