### ISSUE TITLE
Etapa 1, Template strings - Aula 02-06

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#124]
Não consigo adicionar a const na string, mesmo utilizando cifrão e { }. Além disso, não consigo quebrar linhas na string.
![2021-02-03 (1)](https://user-images.githubusercontent.com/78214862/106743410-1cd84980-65fd-11eb-80c6-9f3c29fe946a.png)
![2021-02-03](https://user-images.githubusercontent.com/78214862/106743412-1d70e000-65fd-11eb-8a73-4dbeca00a48d.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Yure.

Como mostrei [na aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/742278), para declarar uma template string é necessário usar **crases**, e não aspas.

Então ao invés de usar '', use ``. 

Entendeu a ideia?

E só uma dica... quando a dúvida for relacionada à código em si, prefira inserir o código na issue ao invés de prints. Isso facilita a leitura do código e me ajuda a te ajudar mais rápido. As instruções de como fazer isso estão descritas no momento em que você clica para abrir uma nova issue:

![Group 305](https://user-images.githubusercontent.com/29297788/106746819-d0433d00-6601-11eb-91ac-028c3d601979.jpg)

Combinado?

Se algo que eu disse acima não ficou claro, é só dar o toque =)

@YureK-a
