### ISSUE TITLE
Resumo da Aula 01-03 e 04 da etapa 02

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#1244]
## Aula 01-03 - Foor Loop

O Foor Loop é um estrutura de repetição que permite executar um codígo determinado número de vezes. Ele permite escolher o valor de início do loop, a condição pra que ele se repita e um incremento pra essa repetição, tudo dentro da sintaxe padrão dele.

Muito utilizado em arrays, ele normalmente gera listas automaticas  e pode inclusive ajudar em montar templates HTML.

### Sintaxe
```javascript
for (let i = 0; i < 5; i++) { }
```
let i = 0 ⇒ variável

i < 5 ⇒ condição

i++ ⇒ incremento

### Percorrendo e Iterando o array names.
```javascript
const names = ['Linus', 'Ada', 'Bill']

for (let i = 0; i < names.length; i++) {
	console.log(names[i])
} 

//Linus
//Ada
//Bill
```
<hr>

## Aula 01-04 - While Loop

O While Loop é bem parecido com o Foor Loop, porém ele é utilizado para se repetir um codigo enquanto sua condição é válida, ele não tem um iniciador de loop, isso deve ser estabelecido antes e também não tem um incrementador na sintaxe, essa parte deve ser feita dentro da condição dele.

### Sintaxe:
```javascript
while(i < 5) { }
```
### Percorrendo e Iterando o array names.
```javascript
const names = ['Linus', 'Ada', 'Bill']
let i = 0;

while (i < names.length) {
	console.log(names[i])
	i++
}
//Linus
//Ada
//Bill
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @davidtheblane, rumo à fluência! 🔥
