### ISSUE TITLE
Aplicação: [To-do list]

### ISSUE THREAD

**Issue by homeromeirelesjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#1245]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/homeromeirelesjunior/to-do-list-app

### Maiores dificuldades durante a implementação

As maiores dificuldades foram na hora de refatorar o código. Não consegui fazer a refatoração na função de busca e filtragem dos Todos, simplesmente todo o tipo de refatoração que eu tentava só parecia que o código mudava de lugar e nada mais.

A parte de remover um todo sem usar a tag `parentElement` também foi chatinha, só depois fui ver sobre o dataset e consegui bolar uma solução, embora não sei se é a mais indicada.

Embora tenha existido algumas dificuldades, todas as aulas e exercícios anteriores foram bem completos e me senti bem preparado. Já é um hábito fazer consultar ao MDN, acho que o importante é saber que a solução existe, a documentação esta ai pra ser consultada né.

### Menores dificuldades durante a implementação

A lógica como um todo foi bem fácil de entender, como e onde aplicar, a resolução já estava na minha mente mesmo nas aulas enquanto o professor estava desenvolvendo em paralelo a mesma aplicação. 

Em comparação a primeira aplicação já me sinto mais confortável na manipulação do DOM e navegar pelo mesmo.

**Comment by Roger-Melo** [comment]
Olá @homeromeirelesjunior.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @homeromeirelesjunior!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

### `autofocus` no `input`

Quando a página for carregada, você já pode deixar por padrão um foco no input de pesquisa ou no de adicionar um to-do, usando no `input` o atributo `autofocus`. Assim o usuário não precisa mover o cursor do mouse e clicar no input para inserir um valor.

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`addTodo` é um verbo e não é descritiva o suficiente para dar a entender que o valor armazenado é um form. Então, eu a nomearia como `formAddTodo`.

Seguindo esse mesmo raciocínio, `searchTodo` pode ser nomeada como `inputSearchTodo`.

## Lógica

### `event` global

Na função `validateNewTodo` o `event` global está sendo usado.

Mesmo que tenha funcionado, o ideal é que o event seja passado como argumento da invocação da função:

```javascript
const validateNewTodo = event => {
  // ...
}

// invocação da função
validateNewTodo(event)
```

Isso por que o [event global](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) foi descontinuado. O VSCode até insere um traço no meio de propriedades e métodos que foram descontinuados/depreciados.

Quando você insere o event como parâmetro de um callback de listener de evento, ao invés de usar o event global, você está usando o [Event interface](https://developer.mozilla.org/en-US/docs/Web/API/Event) =)

---

### Omissão de blocos em `if`s

Cuidado ao omitir blocos de ifs. [Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos atrás e colocou a segurança de dados em xeque por causa desse tipo de decisão.

Observe que `todo` pode ser declarada apenas dentro do `if`, pois o to-do deve ser selecionado no DOM apenas se a condição do `if` resulta em um valor truthy:

```javascript
const removeTodo = event => {
  const clickedElement = event.target
  const dataDeleteValue = clickedElement.dataset.delete

  if (dataDeleteValue) {
    const todo = document.querySelector(`[data-todo="${dataDeleteValue}"]`)
    todo.remove()
  }
}
```

Como `addNewTodo` apenas executa `validateNewTodo` uma possível modificação é renomear `addNewTodo` para `addTodo` e mover a atualização da `ul` de to-dos para uma função `updateTodosList`:

```javascript
const updateTodosList = inputValue => {
  todosList.innerHTML += `
    <li class="list-group-item d-flex align-items-center justify-content-between" data-todo="${inputValue}"> 
      <span>${inputValue}</span>
      <i class="fas fa-trash-alt delete" data-delete="${inputValue}"></i>
    </li>`
}

const addTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    updateTodosList(inputValue)
  }

  event.target.reset()
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by homeromeirelesjunior** [comment]
Opa, @roger-melo-treinamentos/curso-de-js-roger-melo
***@***.***>,

muito obrigado pelo feedback, como sempre, muito pontual nas observações.

Acatei as sugetões e notei que o código ficou mais clean e direto.

No mais, obrigado pela análise!

Forte abraço!

Em sáb., 17 de jul. de 2021 às 14:12, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @homeromeirelesjunior. No que precisar, é só abrir uma nova issue =)
