### ISSUE TITLE
Aplicação: [QUIZ INTERATIVO BY jONATHAN]

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1251]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/jhow221318/Quiz-iterativo.git

### Maiores dificuldades durante a implementação

<h1>Dificuldades</h1>
<p>A minha maior dificuldade que eu tenho é falta de tempo pra estudar , já pensei muito em parar de trabalhar e dedicar de vdd mas infelizmente não posso fazer isso no presente momento.</p>
<h2>Seu curso é muito bom e estou aprendendo muito...</h2>
Por questão de tempo não fiz a refatoração do app.js, tbm usei o bootstrap mas não tehno muito conhecimento no frameWork .

### Menores dificuldades durante a implementação

<h1>Aprendizado</h1>

<ul>Pontos positivos que me fazem aprender:
<li>Explicação muito fácil de entender</li>
<li>Curso muito bem estruturado</li>
<li>Vontade de aprender cada dia mais</li>
</ul>

**Comment by jhow221318** [comment]
Quiz interativo pedido por Roger Mello

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by jhow221318** [comment]
<h1>Bom dia Roger...</h1>
<p> OK... Agradeço a atenção.</p>
<h2>Bom domingo</h2>

**Comment by Roger-Melo** [comment]
Olá @jhow221318!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Na verdade, você fez algo muito diferente do que foi mostrado nas aulas da etapa 7 e a maneira com que o código foi implementado adicionou mais complexidade. 

O que eu recomendo é que você siga esse [passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Lá na frente, vai chegar o momento em que você vai poder improvisar. Mas até lá, eu sugiro você seguir a receita à risca. Evite modificar a receita antes de aprendê-la =)

Faz sentido?

**Comment by jhow221318** [comment]
Blz Roger , como não pudia voltar pra rever as aulas eu improvisei um pouco , agradeço pelo feedback .... Vamos evoluindo mais e mais a cada dia ,ótimo seu curso . Bom dia ...

**Comment by Roger-Melo** [comment]
Legal @jhow221318. Vou fechar essa issue mas no que eu puder ajudar, é só abrir uma nova issue =)
