### ISSUE TITLE
Aplicação: To-do

### ISSUE THREAD

**Issue by alexvieirasj** [roger-melo-treinamentos/curso-de-js-roger-melo#1252]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/alexvieirasj/to-do-list

### Maiores dificuldades durante a implementação

Acho que foi no momento de criar o filtro que oculta e mostra os resultados da busca no input, mas debugando foi me ajudando a entender melhor o fluxo.

### Nova funcionalidade:

Adicionei um **checkbox** ao lado de cada _To do_ possibilitando marcar a "_task_" como feita. Ao marcar o **checkbox** o texto fica com uma linha encima do mesmo, indicando como concluído.

### Menores dificuldades durante a implementação

Utilizar o CSS, HTML e a documentação do Bootstrap, foi de fácil utilização.

**Comment by Roger-Melo** [comment]
Olá @alexvieirasj.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @alexvieirasj!

Parabéns pelo esforço em construir a segunda aplicação do treinamento. Novamente, deu pra perceber que você pegou bem a lógica até aqui =)

Os ajustes que eu faria até esse ponto da aplicação são os seguintes...

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`checkedToDo` é um substantivo, então eu nomearia essa função como `checkTodo`.

`class1` e `class2` são parâmetros que não descrevem do que se tratam as classes. Para ficarem mais descritivos, eles podem ser renomeados como `classToAdd` e `classToRemove`.

### Lógica

Se você quiser, há a opção de deixar o filter da `showSearchResults` mais conciso, através do uso de um ternário:

```javascript
.filter(todo => !match 
  ? !todo.textContent.toLowerCase().includes(inputValue) 
  : todo.textContent.toLowerCase().includes(inputValue)
)
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by alexvieirasj** [comment]
Com certeza, todas os apontamentos fazem muito sentido. Irei fazer um novo commit com as correções apontadas. Obrigado pelas dicas e orientações.

**Comment by Roger-Melo** [comment]
Show @alexvieirasj. No que precisar, é só abrir uma nova issue =)
