### ISSUE TITLE
Aplicação: [weather application]

### ISSUE THREAD

**Issue by MauroGith** [roger-melo-treinamentos/curso-de-js-roger-melo#1253]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/MauroGith/Projetos-JS/tree/main/weather-application

### Maiores dificuldades durante a implementação

A minha maior dificuldade é refatorar funções que precisam acessar ou retornar valores para outras funções, isso ainda me trava um pouco e foi o principal problema nessa implementação

### Menores dificuldades durante a implementação

A parte mais simples foi melhorar as verificações e alterar o estilo

**Comment by Roger-Melo** [comment]
Olá @MauroGith.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @MauroGith!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Organização de código

### Conteúdo dinâmico na marcação HTML

Em minha opinião, em uma leitura rápida, se outra pessoa ler a marcação HTML e algumas tags estiverem sem conteúdo, é mais fácil intuir que o conteúdo daquelas tags serão inseridos de forma dinâmica. Já quando a tag tem um placeholder "Nome da Cidade", "clima", etc... acredito que fica menos intuitivo se aquele valor será dinâmico ou não.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`showCard` é uma const vaga, pois não descreve sobre o que se trata o card. Como essa aplicação tem apenas um card, isso não é tão crítico. Mas acredito que `showCityCard` descreve de forma mais clara sobre o que se trata esse card. Saca?

Seguindo esse mesmo raciocínio, `attDisplayImage` pode ser nomeada como `setTimeImgSrc`.

## Lógica

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para manipular as classes (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu usaria apenas um `if`:

```javascript
const showCityCard = () => {
  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }
}
```

O ternário dentro da `setTimeImgSrc` (antiga attDisplayImage) pode ser mais enxuto, já que o interessante é apenas que `timeImg.src` receba um valor dinâmico:

```javascript
const setTimeImgSrc = IsDayTime => {
  timeImg.src = IsDayTime ? './src/dia.jpg' : './src/noite.jpg'
}
```

## Refactoring

`APIData` é um substantivo que não descreve a ação que a função executa. Então eu a renomearia para `showCityWeatherInfo`. 

Além disso, eu:

- invocaria `showCityCard` no final da `showCityWeatherInfo`
- eliminaria setTimeImgSrc

A `showCityWeatherInfo` ficaria assim:

```javascript
const showCityWeatherInfo = async event => {
  const inputValue = event.target.city.value
  const [{ Key, LocalizedName }] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(Key)

  timeImg.src = IsDayTime ? './src/dia.jpg' : './src/noite.jpg'
  timeIconContainer.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg"/>`
  cityName.textContent = LocalizedName
  cityWeather.textContent = WeatherText
  cityTemperature.textContent = Temperature.Metric.Value
  
  showCityCard()
}
```

Exceto pela parte de requests, de modo geral, o código da `showCityWeatherInfo` faz apenas o que o nome dela diz (manipulação de DOM) e ela não está muito extensa, então acho que neste caso, vale deixar o código dela assim. Extrair os requests para uma função separada também acaba não compensando neste caso.

Você vai ver que é basicamente isso que faço nas aulas seguintes.

---

> ## "A minha maior dificuldade é refatorar funções que precisam acessar ou retornar valores para outras funções, isso ainda me trava um pouco e foi o principal problema nessa implementação"

Você conseguiu. O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo.

Se tiver exemplo de algum código específico que vc queira mostrar em relação a dificuldade que falou acima, pode postar nessa issue ou em outra que te ajudo =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by MauroGith** [comment]
> Olá @MauroGith!
> 
> Parabéns pelo esforço em construir mais essa aplicação do treinamento =)
> 
> Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.
> 
> ## Organização de código
> ### Conteúdo dinâmico na marcação HTML
> Em minha opinião, em uma leitura rápida, se outra pessoa ler a marcação HTML e algumas tags estiverem sem conteúdo, é mais fácil intuir que o conteúdo daquelas tags serão inseridos de forma dinâmica. Já quando a tag tem um placeholder "Nome da Cidade", "clima", etc... acredito que fica menos intuitivo se aquele valor será dinâmico ou não.
> 
> ### Nomes de variáveis e funções
> Um princípio que gosto de seguir ao nomear é:
> 
> * Funções são verbos que descrevem a ação que a função executa.
>   
>   * Exemplos: `getName`, `setName`, `incrementCounter`;
> * Variáveis/consts são substantivos que descrevem o valor armazenado.
>   
>   * Exemplos: `user`, `score`, `color`.
>   * Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`.
>     
>     * Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.
> 
> Considerando isso...
> 
> `showCard` é uma const vaga, pois não descreve sobre o que se trata o card. Como essa aplicação tem apenas um card, isso não é tão crítico. Mas acredito que `showCityCard` descreve de forma mais clara sobre o que se trata esse card. Saca?
> 
> Seguindo esse mesmo raciocínio, `attDisplayImage` pode ser nomeada como `setTimeImgSrc`.
> 
> ## Lógica
> ### Ternário
> Geralmente, ternários não são usados para executar efeitos colaterais.
> 
> O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.
> 
> Sabendo disso, ao invés de usar o ternário para manipular as classes (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu usaria apenas um `if`:
> 
> ```js
> const showCityCard = () => {
>   if (cityCard.classList.contains('d-none')) {
>     cityCard.classList.remove('d-none')
>   }
> }
> ```
> 
> O ternário dentro da `setTimeImgSrc` (antiga attDisplayImage) pode ser mais enxuto, já que o interessante é apenas que `timeImg.src` receba um valor dinâmico:
> 
> ```js
> const setTimeImgSrc = IsDayTime => {
>   timeImg.src = IsDayTime ? './src/dia.jpg' : './src/noite.jpg'
> }
> ```
> 
> ## Refactoring
> `APIData` é um substantivo que não descreve a ação que a função executa. Então eu a renomearia para `showCityWeatherInfo`.
> 
> Além disso, eu:
> 
> * invocaria `showCityCard` no final da `showCityWeatherInfo`
> * eliminaria setTimeImgSrc
> 
> A `showCityWeatherInfo` ficaria assim:
> 
> ```js
> const showCityWeatherInfo = async event => {
>   const inputValue = event.target.city.value
>   const [{ Key, LocalizedName }] = await getCityData(inputValue)
>   const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(Key)
> 
>   timeImg.src = IsDayTime ? './src/dia.jpg' : './src/noite.jpg'
>   timeIconContainer.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg"/>`
>   cityName.textContent = LocalizedName
>   cityWeather.textContent = WeatherText
>   cityTemperature.textContent = Temperature.Metric.Value
>   
>   showCityCard()
> }
> ```
> 
> Exceto pela parte de requests, de modo geral, o código da `showCityWeatherInfo` faz apenas o que o nome dela diz (manipulação de DOM) e ela não está muito extensa, então acho que neste caso, vale deixar o código dela assim. Extrair os requests para uma função separada também acaba não compensando neste caso.
> 
> Você vai ver que é basicamente isso que faço nas aulas seguintes.
> 
> > ## "A minha maior dificuldade é refatorar funções que precisam acessar ou retornar valores para outras funções, isso ainda me trava um pouco e foi o principal problema nessa implementação"
> 
> Você conseguiu. O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo.
> 
> Se tiver exemplo de algum código específico que vc queira mostrar em relação a dificuldade que falou acima, pode postar nessa issue ou em outra que te ajudo =)
> 
> Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.
> 
> Mais uma vez, parabéns pelo esforço =)
> 
> As observações fizeram sentido?

**Comment by MauroGith** [comment]
@Roger-Melo Muito obrigado pela avaliação, vou aplicar as alterações e depois seguir com as aulas !

**Comment by Roger-Melo** [comment]
Show @MauroGith. No que precisar, é só abrir uma nova issue =)
