### ISSUE TITLE
Etapa 6, Correção do exercício 17 - Aula 02-01

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#126]
Oi Roger =)
Estou revisando o conteúdo de etapas passadas do curso, e durante a correção do exercício 17 notei a seguinte situação:
![Capturar](https://user-images.githubusercontent.com/69519457/106905392-02749d80-66db-11eb-8651-662ad78cd533.PNG)
Minha dúvida foi a seguinte: na declaração da ```clearInput``` você referenciou um input que não está declarado naquele escopo. Por que durante a invocação da ```clearInput``` ela referencia o input declarado no escopo da ```handleSubmit``` ? Fiquei um pouco confuso nesta parte.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel!

Respondi essa dúvida [nesta issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/10).

Se depois de ver essa resposta ainda restar alguma dúvida, é só dar o toque que explico de outra forma =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Opa, show de bola Roger, obrigado
