### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1269]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/NiksonDiniz/quiz-interativo

### Maiores dificuldades durante a implementação

Com as  aulas achei muito fácil fazer o código do quiz. 

Mas tenho dificuldades em alguns pontos:
1. Colocar de modo simplificado minha lógica no código;
2. Fatorar o código(exemplo do meu quiz não consegui colocar as 'const' pra fora do forEach(linha 27);
3. Colocar os nomes nas variáveis e funções

### Menores dificuldades durante a implementação

Não sei bem explicar. Mas são coisa do tipo:

1.Fazer o código funcionar.
2. Obter valores do form.
3. Modificar o quiz.
Acho que é só por enquanto! :D

**Comment by Roger-Melo** [comment]
Olá @NiksonDiniz.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @NiksonDiniz!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

Você acertou no local da exibição da pontuação na tela ao clicar no botão, pois o usuário imediatamente vê o resultado do quiz sem ter que rolar a tela =)

## Organização de código

### Comentários

Não é uma regra, mas evite comentários na hora de subir a aplicação para produção ou no código em geral.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Se você realmente faz questão de usar comentários para que eles te ajudem nos estudos, mantenha duas versões do código; a de produção (sem comentários) e a de desenvolvimento/estudos.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`button` é uma const vaga, pois não descreve sobre o que se trata o botão. Como essa aplicação tem apenas um botão, isso não é tão crítico. Mas acredito que `buttonSubmitQuiz` descreve de forma mais clara sobre o que se trata esse botão, saca?

Seguindo esse mesmo raciocínio, `divScore` pode ser nomeada como `scoreContainer`, pois além de descrever do que se trata esse elemento, se a `div` mudar para `section` o nome da const não precisará ser modificado.

Eu também nomearia `insertDivScore` como `showScore` (mesmo motivo acima) e nomearia `insertDivScoreInfo` como `scoreInfo` (daqui a pouco vou falar mais sobre isso).

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover a linha em branco do início do callback do `forEach`. É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código =)

## Lógica

### Callback do `forEach`

Você fez bom uso do `if` sem `else` dentro do callback do `forEach` =)

Uma observação sobre esse callback: a única ação que ele precisa executar é o cálculo dos pontos. Não é necessário criar objetos e manipular DOM à cada execução do callback. Prefira fazer isso depois que os pontos forem calculados:

```javascript
quizForm.addEventListener('submit', event => {
  // ...

  userAnswers.forEach( (userAnswer, index )=> {
    if(userAnswer === correctAnswers[index]) {
      score += 25
    }
  })

  const badScore = {...}
  const goodScore = {...}

  // ...
})
```

### Utilização de objetos

Uma forma de deixar o código mais enxuto na utilização dos objetos `goodScore` e `badScore` seria fazer o seguinte:

- eliminar a propriedade `previousSibling`, pois o local da exibição dos pontos não é influenciado pela pontuação
- substituir a `text` por uma propriedade `score`

Ficaria mais ou menos assim:

```javascript
const showScore = ({ score, className }) => {
  scoreContainer.textContent = `Sua pontuação é ${score}`
  scoreContainer.setAttribute('class', className)
  button.insertAdjacentElement('beforebegin', scoreContainer)
}

// ...

quizForm.addEventListener('submit', event => {
  // ...

  if (score <= 45) {
    showScore({ score, className: 'alert alert-danger' })
    return
  } 
  
  showScore({ score, className: 'alert alert-success' })
})
```

Mas claro, substituir `goodScore` e `badScore` tem um certo custo de legibilidade... mas acredito que `score <= 45` ajuda bastante =)

Em breve, você será apresentado ao ternário e aprenderá como eliminar `if/else`. O código vai ficar ainda mais conciso:

```javascript
const showScore = score => {
  scoreContainer.textContent = `Sua pontuação é ${score}`
  scoreContainer.setAttribute('class', score <= 45 ? 'alert alert-danger' : 'alert alert-success')
  button.insertAdjacentElement('beforebegin', scoreContainer)
}

// ...

quizForm.addEventListener('submit', event => {
  // ...

  userAnswers.forEach( (userAnswer, index )=> {
    if(userAnswer === correctAnswers[index]) {
      score += 25
    }
  })

  showScore(score)
})
```

Não se preocupe em entender isso agora, são cenas dos próximos capítulos =D

---

Sobre as dificuldades que você listou, o mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by NiksonDiniz** [comment]
Faz todo sentido,

Muito Obrigado pelas dicas professor!

Em relação aos comentários no  código, em uma de minhas  tentativas  de refatoração(como disse, sou um pouco ruim nisso), tentei colocar as const na parte de cima. A princípio iria deixar como comentário esses códigos que não deram certo, para o senhor da uma olhada. Aí acabou que deixei passar aqueles e desisti de deixar os outros. 

Em relação ao código:

```javascript
const showScore = ({score, className}) => {
 ...
}
```

Aqui eu não entendo o que está fazendo. Está passando a let score pra dentro da função? Está passando em forma desestruturada?

E nessa parte:

```javascript
showScore({ score, className: 'alert alert-danger' })
```

Só pra confirmar, ela pega a let score e na className só atribue o valor?!

Em relação ao ternário, já conheço um pouco....mas prefiro ver sua explicação. Você explica bem(não estou puxando saco kkk)


Novamente obrigado pelo retorno e espero não ter sido muito extenso na minha resposta.

**Comment by Roger-Melo** [comment]
Olá @NIKSON DINIZ!

No código abaixo, como a função `showScore` espera receber um objeto por parâmetro, o destructuring está sendo feito nas propriedades `score` e `className` desse objeto:

```javascript
const showScore = ({ score, className }) => {
 // ...
}
```

Esse destructuring aplicado diretamente no parâmetro da função é apenas um shortcut disso:

```javascript
const showScore = obj => {
  const { score, className } = obj
  
  // ...
}
```

Lembre-se: parâmetros são variáveis locais da função. Se os `()` esperam receber variáveis - e expressões de destructuring declaram variáveis - faz sentido que o destructuring possa ser inserido dentro dos parênteses. 

Sacou a ideia?

---

Já no código abaixo, a invocação da `showScore` recebe um objeto.

```javascript
showScore({ score, className: 'alert alert-danger' })
```

Esse objeto contém uma propriedade `score` que recebe a let `score`. Então, ao invés de inserir que a propriedade `score` recebe `score`, é possível aplicar shorthand property names. 

Essa feature se baseia no seguinte: se o nome da propriedade e a variável atribuída à propriedade tem o mesmo nome, basta inserir o nome da propriedade:

```javascript
let score = 1

// com shorthand property names
const obj = { score }
obj.score // 1

// sem shorthand property names
const obj2 = { score: score }
obj.score // 1
```

Ambas declarações dos objetos atribuem o valor da let `score` para a propriedade `score`. Mas com shorthand property names vc escreve menos =)

Ficou mais claro?

**Comment by NiksonDiniz** [comment]
Obrigado @Roger-Melo 
Entendi agora o funcionamento.
Pode fechar a issue. :D

**Comment by Roger-Melo** [comment]
Show @NiksonDiniz. No que precisar, é só abrir uma nova issue =)
