### ISSUE TITLE
Etapa 04, Variáveis e escopo de bloco - Aula 02-02

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#127]
Olá novamente, Roger. 

Nessa aula você escreve alguns exemplos para mostar como funciona o escopo de bloco. 
Esse é o código apresentado na aula: 

```
const age = 31

if (true) {
   const age = 41
   const name = 'Roger'

   console.log(`Dentro do 1º bloco de código: ${age} ${name}`)

   if (true) {
      const age = 51
      console.log(`Dentro do 2º bloco de código: ${age}`)

      var test = 'oi'
   }
}

console.log(`Fora do bloco de código: ${age} ${name} ${test}`)
```
Eu percebi que a variável name quando é referenciada no console.log() não é exibida, afinal ela foi declarada dentro do if(). 

Mas por que não é lançado um erro informando que não é possível acessar a variável? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton. 

Um erro informando que a variável não foi definida não é lançado por que o window contém uma propriedade `name` que, por padrão, armazena uma string vazia.

```javascript
console.log(name) // ''
console.log(window.name) // ''
```

Se você executar o código acima, verá que tanto `name` como `window.name` resultam na string vazia. Por isso, `console.log(`${age} ${name} ${test}`)` retorna `31  oi`.

Sacou a ideia?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Saquei sim. 

Tudo faz sentido agora. 

Obrigado!

**Comment by Roger-Melo** [comment]
Legal =)

Vou fechar a issue por agora, mas no que precisar, é só dar o toque.
