### ISSUE TITLE
Etapa 1, Os Primeiros Passos - Aula 04-Exercícios

### ISSUE THREAD

**Issue by betomouse** [roger-melo-treinamentos/curso-de-js-roger-melo#128]
Roger, em todos os exercícios até agora, eu tento criar soluções "dinâmicas" como o exemplo abaixo, mesmo você não exigindo isso no exercício.
No caso eu tentei criar uma solução para tornar a letra maiúscula independente do resultado ser true ou false.
```js
const verify = String(typeSentence.length > 39)
console.log(`A string que a "typeSentence" armazena tem mais de 39 caracteres? ${verify.replace(verify[0], verify[0].toUpperCase())}`)
```
Pergunto: Devo parar com essa "viagem" ? Isso é um "vício" e vai me atrapalhar mais a frente ? O espertão aqui acredita estar dando um 'tranco' no raciocínio lógico. rs 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Alberto.

Tentar soluções diferentes das que foram mostradas é uma forma de aprendizado super válida.

Apenas certifique-se de que você entendeu como implementar a solução da forma que mostrei (e por entender, quero dizer conseguir implementar sozinho).

Aos poucos os exercícios vão ficando mais complexos. Vai chegar o momento em que eles vão exigir mais de você e você precisará executar o que recomendei [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) para que seu cérebro entenda de fato a forma de resolução mostrada.

Mas neste caso específico que você apresentou, deu pra perceber que você entendeu a lógica por trás da forma que resolvi, então tá tudo certo =)

@betomouse

**Comment by betomouse** [comment]
Respondeu sim! Obrigado Roger.

**Comment by Roger-Melo** [comment]
No que precisar, é só dar o toque =)
