### ISSUE TITLE
Resumo da Aula setInterval() e animação da pontuação - Aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1281]
Hoje vamos conhecer mais um método pendurado no objeto `window`, que é o `setInterval()`. Ele executa algo dentro de um intervalo de tempo definido por nós, repetidas vezes. Ou seja, caso queiramos que uma função seja executada de 1 em 1 segundo por exemplo, por um tempo determinado ou indeterminado, basta utilizarmos o método `setInterval()`. Como um primeiro exemplo, vamos mostrar no console a mensagem "*I'm here again!*" com um intervalo de 2 segundos:

```jsx
setInterval(() => {
	console.log('I\'m here again');
}, 2000);
```

Mas podemos também definir uma condição para interromper essa sequência de execuções do `setInterval()`. Esse método, quando armazenado em uma constante, retorna um *Id*. Esse *Id* poderá ser utilizado para interrompermos as execuções através do método `clearInterval()`, que é outro do objeto `window`. O `clearInterval()` recebe como argumento o *Id* armazenado do `setInterval()`. Vamos ver na prática como ficaria a execução de um método que está sendo invocado a cada 1 segundo, e interrompido quando chegarmos a 5 segundos.

```jsx
let counter = 0;

const timer = setInterval(() => {
	console.log('Hi there');

	if (counter === 4) {
		clearInterval(timer);
	}

	counter++;
}, 1000);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Rumo à fluência! 🔥
