### ISSUE TITLE
Etapa 11, nome do vídeo: A Fetch API

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1285]
### Olá @Roger-Melo,
Tenho uma duvida em relação a ``Fetch`` ou ``async/await``, qual dessas duas devo usar, já que ambas faz a mesma coisa?

🔖 Entendi que com a ``Fetch`` temos que encadear o ``then`` e o ``catch`` para podermos obter o resultado ou a falhar da requisição da api usada.

```javascript

fetch('https://jsonplaceholder.typicode.com/users')
    .then(response => {
        console.log('response', response)
        return response.json()
    })
    .then(users => console.log(users))
    .catch(error => console.log(error))

```

🔖 Já com o ``async/await`` nos podemos criar um função que irá mostrar o resultado da requisição sem encadear o ``then`` e o ``catch`` explicitamente.

```javascript

const getUsers = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users')
    return await response.json()
}

const logUsers = async () => {
    const users = await getUsers()
    console.log(users)
}

logUsers()

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros!

> ## Fetch ou async/await, qual dessas duas devo usar, já que ambas faz a mesma coisa?

Algumas variáveis externas vão influenciar nessa decisão:

1. Equipe
2. Suporte aos browsers

### Equipe

Se você trabalha em um time que prefere um ou outro, provavelmente terá que se adaptar ao que o time escolheu =)

### Suporte aos browsers

Se o código que você trabalha é antigo, pode ser que ele suporte apenas then e catch. Fique sempre de olho se a aplicação que você está desenvolvendo precisa suportar navegadores antigos ou se o projeto tem um compiler que permite você usar sintaxe moderna no código ([babel](https://babeljs.io/)). Isso ainda é um tópico que falarei no treinamento, mas como vc tem uma certa experiência, talvez já conheça sobre (e se tiver alguma dúvida, pode perguntar) =)

Vou deixar abaixo links para as tabelas de suporte aos browsers das features:

- [then](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#browser_compatibility)
- [catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch#browser_compatibility)
- [async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#browser_compatibility)
- [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility)

Há também variáveis subjetivas nessa escolha. Para mim, a principal é a legibilidade.

Com `async/await`, você evita aninhamento de callbacks e a leitura do código fica mais simples, pois você lê o código como se ele fosse síncrono.

> ## 🔖 Entendi que com a Fetch temos que encadear o then e o catch para podermos obter o resultado ou a falhar da requisição da api usada.

Usando `async/await`, geralmente você usará `try/catch` para tratar erros de operações assíncronas. Se você ainda não chegou nesta parte do treinamento, ela deve estar perto =)

Respondi as dúvidas?

**Comment by Mateus20Barros** [comment]
obg @Roger-Melo.

Quando enviei essa duvida, eu ainda não tinha chegado em ``try/catch``. Já vi a aula que falar do mesmo, e com sua explicação aqui, me esclareceu em relação a quando usar um ou outro.

👍

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros!

O encadeamento do [finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#the_finally-block) é opcional.

Você irá usá-lo quando precisar que o código dentro do bloco dele sempre seja executado imediatamente após o try/catch, independentemente se um erro foi lançado ou não.

Na real, na maioria dos casos (em JavaScript) você não verá muito o uso do finally por aí. Eu mesmo não mostrei pq não teve necessidade. Tem um outro ponto tb... quando vc usa vários blocos de código juntos, eles tendem a prejudicar a legibilidade do código:

```javascript
try {
  // try_statements
} catch (exception_var) {
  // catch_statements
}
finally {
  // finally_statements
}
```

Não é a coisa mais agradável de se ler e pode piorar se tiver outros blocos de código aninhados ali dentro. Então a galera meio que procura formas de tratar erros deixando o código mais conciso e fácil de ler. 

Inclusive tem uma técnica que gosto bastante que evita `try/catch` na hora de tratar erros, mas isso vc vai ver na etapa 15 =D

Ficou mais claro?

**Comment by Mateus20Barros** [comment]
ficou sim, 👍

**Comment by Roger-Melo** [comment]
Legal @Mateus20Barros. No que precisar, é só abrir uma nova issue =)
