### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#1290]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Mlluiz39/cursoJavaScriptRm/tree/main/meuExec/exercicio-19-etap-07-quiz

### Maiores dificuldades durante a implementação

Não conseguir fazer os radio bottons serem limpos ao submeter o formulario, e não consegui tirar um bug que é quando enviamos o formulario com apenas uma questão selecionada  ele mostrar você acertou apenas 1 pergunta, pois quando selecionamos todas as questões e acertamos apenas uma ele funciona.

### Menores dificuldades durante a implementação

selecionar os elementos do dom.

**Comment by Roger-Melo** [comment]
Olá @Mlluiz39.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Mlluiz39!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Mensagem de agradecimento

"Obrigado por jogar!" está estilizado como se fosse um botão. Uma alternativa seria deixar essa mensagem como um parágrafo abaixo do parágrafo que exibe a pontuação.

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`formElement` pode descrever sobre o que se trata o form. Como essa aplicação tem apenas um form, isso não é tão crítico. Mas acredito que `formSubmitQuiz` descreve de forma mais clara sobre o que se trata esse form, saca?

Seguindo esse mesmo raciocínio, `paragraphElement` pode ser nomeada como `scoreMessage`.

Outros ajustes que eu faria:

- `correcResponse` pode ser nomeada como `correctAnswers` (no plural), pois armazena várias respostas
- `showPopupClose` pode ser renomeada como `closePopup`
- `nameClickedElement` seria `classNameOfClickedElement`, por que ela armazena o nome de uma classe do elemento clicado
- `className` seria `classNames` (plural)
- `closePopup` seria `shouldClosePopup`, pois ela armazena um boolean
- `showCorrectUserResponse` seria `showScore`

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode inserir uma linha em branco antes e depois de setar o `display` do popup como `block`.

Você também pode "agrupar" as consts do topo do código considerando o tipo de valor que elas armazenam.

No exemplo abaixo, eu agrupei as consts que armazenam elementos do DOM e separei elas da const que armazena as respostas corretas:

```javascript
const formElement = document.querySelector('.quiz-form');
const paragraphElement = document.querySelector('.paragraph');
const popupElement = document.querySelector('.popup-wrapper');

const correcResponse = ['B', 'A', 'C', 'A', 'B'];
```

## Lógica

`scoreMessage.textContent.length` sempre resultará em `0` quando o `form` for enviado pela 1ª vez, então faz mais sentido que a condição do `if` verifique a `score`. Você também pode evitar o `else` verificando apenas o caso onde o singular deve ser usado:

```javascript
const showScore = (event) => {
  // ...

  popupElement.style.display = 'block';

  if (score === 1) {
    scoreMessage.textContent = `Você acertou: ${score} pergunta`;
    return
  }

  scoreMessage.textContent = `Você acertou: ${score} perguntas`;
};
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Mlluiz39** [comment]
Boa tarde, fizeram total sentido uma obs: a respeito das quebras de linha pode ter acontecido esse erro por usar o format code do prettier do vscode de resto vou tentar corrigir.

**Comment by Roger-Melo** [comment]
Legal @Mlluiz39. No que precisar, é só abrir uma nova issue =)
