### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by CleitonRReis** [roger-melo-treinamentos/curso-de-js-roger-melo#1298]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação

https://github.com/CleitonRReis/climate

### Maiores dificuldades durante a implementação

Construir a aplicação não foi difícil. A princípio, utilizei **_then/catch_** para o consumo da api, o que foi simples. Porém, quando fui refatorar, utilizei _**_async/await_**_ o que achei bastante complicado, pois não sabia ao certo onde colocar essas palavras. Mas com prática, acredito que se torne simples.

E **_refatorar_** o código, para mim, ainda é bastante complexo, sofri com isso.

OBS: Utilizei outra API de tempo para construir a aplicação.

### Menores dificuldades durante a implementação

Utilizar **_then/catch_** é muito simlpes.

**Comment by Roger-Melo** [comment]
Olá @CleitonRReis.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @CleitonRReis!

Parabéns pelo esforço em construir mais uma aplicação do treinamento. Novamente, você demonstrou ter entendido bem a lógica até esse ponto =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

Não sei se vc vai subir essa aplicação para produção mas se for o caso, vale pensar em como a aparência dela será em telas com largura menor, saca? =)

Um outro detalhe é que no momento em que a aplicação é carregada, as informações de São Paulo são exibidas e a imagem de fundo indica que é dia na cidade quando na verdade não é. Tanto é que estou testando a aplicação à noite e se pesquiso por São Paulo, desta vez é exibido que é noite.

## Features usadas

Vc usou algumas features não vistas até aqui (`charAt`, `substr`). Elas foram bem usadas, apenas tome cuidado para não sair muito do que foi visto nas aulas. O desafio consiste em resolver os exercícios/aplicações com o que foi mostrado. Limitações tendem a exercitar a nossa criatividade =)

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`showInfo` pode ter um nome mais descritivo em relação às informações que ela irá exibir: `showWeatherInfo`.

Dentro da `testCity`, a `invalidCity` presupõe que o valor que a const recebe é um nome de cidade inválido, o que pode não acontecer. Por isso, eu a nomearia apenas como `city`. O parâmetro da `showInfo` e a `cityData` dentro do `try` também podem ser nomeados como `city`.

No objeto que a invocação da `showInfo` recebe, `nameOfCity` poderia ser nomeada como `name`, pois na assinatura `name: city.name`, é inferível que `name` se trata do nome da cidade.

A let body dentro da `isNightInCity` não precisa ser uma let. A não ser que ela tenha sido declarada como let para indicar que o objeto que ela armazena sofrerá mutação no decorrer do código. Mas ainda assim, como ela em si não sofrerá reatribuição, eu a deixaria como `const`.

Como a `body` na verdade armazena uma div com a classe `main`, vc pode nomear essa const como `main`.

### Code styling

No decorrer do código há funções com um parâmetro declaradas com e sem parênteses. Escolha um dos dois estilos de código e seja consistente nessa escolha.

## Lógica

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar atribuições (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu apenas aproveitaria a url que o ternário retorna:

```javascript
// antes
codeIcon.includes('n') ? body.style.backgroundImage = imgNight : body.style.backgroundImage = imgDay;

// depois
body.style.backgroundImage = codeIcon.includes('n') ? imgNight : imgDay
```

---

> E refatorar o código, para mim, ainda é bastante complexo, sofri com isso.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by CleitonRReis** [comment]
Olá, Roger! Blz?

Muito obrigado pelas orientações. Fizeram sentido, sim.

Atualizei o código conforme orientado.

O deixei responsivo para tablets e smartphones, pois pretendo subir a aplicação.

Desde já, agradeço.

Sent from my iPhone

On 24 Jul 2021, at 01:17, Roger Melo ***@***.***> wrote:

﻿

Olá @CleitonRReis<https://github.com/CleitonRReis>!

Parabéns pelo esforço em construir mais uma aplicação do treinamento. Novamente, você demonstrou ter entendido bem a lógica até esse ponto =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

________________________________
Usabilidade

Não sei se vc vai subir essa aplicação para produção mas se for o caso, vale pensar em como a aparência dela será em telas com largura menor, saca? =)

Um outro detalhe é que no momento em que a aplicação é carregada, as informações de São Paulo são exibidas e a imagem de fundo indica que é dia na cidade quando na verdade não é. Tanto é que estou testando a aplicação à noite e se pesquiso por São Paulo, desta vez é exibido que é noite.

Features usadas

Vc usou algumas features não vistas até aqui (charAt, substr). Elas foram bem usadas, apenas tome cuidado para não sair muito do que foi visto nas aulas. O desafio consiste em resolver os exercícios/aplicações com o que foi mostrado. Limitações tendem a exercitar a nossa criatividade =)

Organização de código
Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

  *   Funções são verbos que descrevem a ação que a função executa.
     *   Exemplos: getName, setName, incrementCounter;
  *   Variáveis/consts são substantivos que descrevem o valor armazenado.
     *   Exemplos: user, score, color.
     *   Quando o valor armazenado é um boolean, podem conter is, has ou should.
        *   Exemplos: isOdd, hasSevenItems, shouldUpdate.

Considerando isso...

showInfo pode ter um nome mais descritivo em relação às informações que ela irá exibir: showWeatherInfo.

Dentro da testCity, a invalidCity presupõe que o valor que a const recebe é um nome de cidade inválido, o que pode não acontecer. Por isso, eu a nomearia apenas como city. O parâmetro da showInfo e a cityData dentro do try também podem ser nomeados como city.

No objeto que a invocação da showInfo recebe, nameOfCity poderia ser nomeada como name, pois na assinatura name: city.name, é inferível que name se trata do nome da cidade.

A let body dentro da isNightInCity não precisa ser uma let. A não ser que ela tenha sido declarada como let para indicar que o objeto que ela armazena sofrerá mutação no decorrer do código. Mas ainda assim, como ela em si não sofrerá reatribuição, eu a deixaria como const.

Como a body na verdade armazena uma div com a classe main, vc pode nomear essa const como main.

Code styling

No decorrer do código há funções com um parâmetro declaradas com e sem parênteses. Escolha um dos dois estilos de código e seja consistente nessa escolha.

Lógica
Ternário

Geralmente, ternários não são usados para executar efeitos colaterais.

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar atribuições (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu apenas aproveitaria a url que o ternário retorna:

// antes
codeIcon.includes('n') ? body.style.backgroundImage = imgNight : body.style.backgroundImage = imgDay;

// depois
body.style.backgroundImage = codeIcon.includes('n') ? imgNight : imgDay

________________________________

E refatorar o código, para mim, ainda é bastante complexo, sofri com isso.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Show @CleitonRReis. Se surgir alguma dúvida, é só abrir uma nova issue =)
