### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by gbr-jpg** [roger-melo-treinamentos/curso-de-js-roger-melo#13]
Oi Roger!

Cara durante a correção deste exercício número 3 me veio uma dúvida, por que se eu passar um typeof li.textContent vai me retornar uma string se na verdade o conteúdo desta li é um number ?

*** Bom, consegui resolver o exercício sem maiores dificuldades, porém segui um outro fluxo, eu costumo dar um console.log cada parte para ver se está ocorrendo bem a execução do código e quando me retornou esta "string" no typeof converti logo cada índice para um number e segui o fluxo depois do programa tudo certinho ai revisando a tua correção me veio essa dúvida que mencionei acima. 

![337aaf62-ef94-4365-90d5-c865ad34a139](https://user-images.githubusercontent.com/62727587/83369430-bb3b4d80-a392-11ea-8b30-c8379354f540.png)

**Comment by gbr-jpg** [comment]
> Oi Riger!
> 
> Cara durante a correção deste exercício número 3 me veio uma dúvida, por que se eu passar um typeof li.textContent vai me retornar uma string se na verdade o conteúdo desta é um number ?
>   *** Bom, consegui resolver o exercício sem maiores dificuldades, porém segui um outro fluxo, eu costumo dar um console.log cada parte para ver se está ocorrendo bem a execução do código e quando me retornou esta "string" no typeof converti logo cada índice para um number e segui o fluxo depois do programa tudo certinho ai revisando a tua correção me veio essa dúvida que mencionei acima.
>   ![337aaf62-ef94-4365-90d5-c865ad34a139](https://user-images.githubusercontent.com/62727587/83369430-bb3b4d80-a392-11ea-8b30-c8379354f540.png)

**Comment by Roger-Melo** [comment]
Oi Gabriel. Se tiver qualquer dúvida é só perguntar =)

@gbr-jpg
