### ISSUE TITLE
Etapa 05, Criando e removendo elementos do DOM - Aula 03-04

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#130]
Roger, na aula sobre eventos percebi que quando adcionamos um novo elemento a lista esse novo elemento não herda o evento de click que os outros elementos já tinham. 

Porém percebi um comportamento diferente dependendo de como esse novo elemento for adicionado influencia os demais elementos existentes.

O que percebi foi que quando criamos com o createElement() os novos elementos não recebem o evento de click, porém os antigos permanecem com o que já tinham. 

Agora se utilizamos um template HTML, os novos elementos não recebem o evento de click mas os antigos também os perdem. 

Por que isso acontece. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Não sei se entendi bem sua dúvida. Se possível, poste o código `HTML` e `.js` que está tentando executar. Fica mais fácil assim =)

E só um detalhe, não é possível adicionar eventos em elementos criados com strings. Eu falei sobre isso aos 01:55 [dessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1567479).

Deixe-me saber se está ficando mais claro. Fico no aguardo do código =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
```
const button = document.querySelector('button')

button.addEventListener('click', () => {
   const li = document.createElement('li')

   li.textContent = 'Novo item'

   ul.prepend(li) // Adciona um elemento como primeiro filho de um outro elemento
})
```

Quando criamos um novo item para o TODO da forma acima, esse novo item não recebe o evento de clique como você explicou na aula. Porém os itens que já existem permanecem com seu próprio evento de click. 

Agora: 

```
const button = document.querySelector('button')

button.addEventListener('click', () => {
   ul.innerHTML += `<li>Novo item</li>`
})
```

Quando criamos um novo item da forma acima, esse item também não recebe o evento de click como também os que já existiam perdem os deles. E ai todos os itens do TODO ficam sem o elemento de clique. 

Mas acredito que você já tenha respondido. Que quando criamos um item como string ela não recebe o evento.

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Agora sim entendi o que você quis dizer =D

O fato é o seguinte...

Quando a `innerHTML` é usada para setar o HTML interno de um elemento, todos os elementos desse HTML interno são removidos e substituídos por nós construídos através do parseamento da string que a `innerHTML` recebeu.

Ou seja, quando o código abaixo é executado,

```javascript
ul.innerHTML += `<li>Novo item</li>`
```

o que está acontecendo na verdade é isso:

```javascript
ul.innerHTML = ul.innerHTML + `<li>Novo item</li>`
```

E quando isso ☝️ acontece, o resultado da expressão `ul.innerHTML` à direita do sinal de atribuição (que são as lis) é convertido para string, essa string é concatenada à string `<li>Novo item</li>`, o resultado dessa concatenação é atribuído à `ul.innerHTML`, e o parseamento dessa string para nós do DOM é executado por baixo dos panos.

Então como antes da atribuição, as `lis` da `ul` sofreram essa conversão para string, essa "reconstrução" delas para HTML descartou os eventos que elas tinham.

Pegou a ideia?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Peguei sim, Roger. 

Faz sentido. É como se todos os elementos estivessem sendo refeitos do 0 e por isso perdem o evento. 

Obrigado.

**Comment by Roger-Melo** [comment]
Isso mesmo Hamilton.

Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir outra =)
