### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by LuizGustavoDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1303]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/LuizGustavoDiniz/Quiz-Interativo

### Maiores dificuldades durante a implementação

tive dificuldade para estilizar o form, no javascript em si não tive muitas

### Menores dificuldades durante a implementação

criar elementos e inserir no DOM, a colocar e tirar classes de elementos para fazer a score aparecer na tela, a lógica da
aplicação

**Comment by Roger-Melo** [comment]
Olá @LuizGustavoDiniz.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @LuizGustavoDiniz!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

### Inputs e labels

Ao clicar em uma alternativa, o usuário precisa posicionar o mouse e clicar exatamente no input type radio. Isso pode causar desconforto, pois o input é muito pequeno.

Por isso, eu preferi mostrar na aula como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

### Referência de pontuação

Quando o usuário envia o quiz, o ideal é que seja informado qual é a pontuação máxima. Quando ele ver que fez 50 pontos (por exemplo), se não houver alguma informação dizendo que a pontuação máxima é 150, ele vai supor que a pontuação total é 100 e vai achar que acertou metade do quiz. Sacou?

## Organização de código

### Local do index.html

O index.html [precisa estar na raiz do projeto](https://en.wikipedia.org/wiki/Webserver_directory_index), caso contrário, ao subir o servidor, o que será exibido é a estrutura de diretórios do projeto:

![image](https://user-images.githubusercontent.com/29297788/126886788-254e049e-ba4d-41aa-bee7-3a8c0a76ccac.png)

### Comentários

Não é uma regra, mas evite comentários na hora de subir a aplicação para produção ou no código em geral.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Se você realmente faz questão de usar comentários para que eles te ajudem nos estudos, mantenha duas versões do código; a de produção (sem comentários) e a de desenvolvimento/estudos.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`form` é uma const vaga, pois não descreve sobre o que se trata o form. Como essa aplicação tem apenas um form, isso não é tão crítico. Mas acredito que `quizForm` descreve de forma mais clara sobre o que se trata esse form, saca?

Seguindo esse mesmo raciocínio, `button` pode ser nomeada como `buttonCloseScore`.

`div` é vaga. Uma possibilidade seria renomear `scoreContainer` como `scoreWrapper` e `div` como `scoreContainer`.

Como `scoreConcept` retorna uma mensagem sobre a pontuação, eu a nomearia como `getScoreMessage`.

Se o elemento que `insertScoreDivIntoDom` armazena mudar para `<section>`, o nome dela perde o sentido. Eu a nomearia apenas como `showScore`.

Você está usando camelCase para nomear, mas `ScoreConcept` está em PascalCase.

O array `['Right', 'Right', ...]` não deixa claro quais alternativas são as corretas. O ideal é que essas strings sejam letras ou números.

### Indentação dentro da ScoreConcept

O código da `ScoreConcept` precisa de ajustes na indentação.

## Lógica

Ternário é apresentado apenas na etapa 8. O desafio é vc resolver os exercícios/aplicações usando apenas o que foi visto no treinamento até o ponto onde vc está, saca?

Dentro do callback que fecha a exibição da pontuação, a condição `elementClassName === 'score-container show'` pode facilmente quebrar a aplicação se amanhã alguma classe CSS for adicionada nesse elemento. Por isso, por enquanto o que eu recomendo neste caso é usar o `classList` e de quebra eliminar um `if` do código:

```javascript
scoreWrapper.addEventListener('click', event => {
  const [classNameOfClickedElement] = event.target.classList
  const shouldCloseScoreWrapper = ['close-score', 'score-container']
    .some(className => className === classNameOfClickedElement)

  if (shouldCloseScoreWrapper) {
    scoreWrapper.classList.remove('show')
  }
})
```

Mais à frente, você verá uma forma mais elegante de comparar identificadores de elementos =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by LuizGustavoDiniz** [comment]
Bom diaa professor, obrigadoo pelas observações e dicas, fizeram total sentido.
Vou me atentar mais daqui para frente nessas questões que o sr. falou.
Eu realmente tenho dificuldade em nomear variáveis e funções com nomes mais corretos, mas vou buscar melhorar.
Quando eu entro em uma parte do curso eu tbm busco alguns vídeos e pratico alguns projetos pra absorver mais aquele conteúdo, e as vezes aprendo coisas que não cheguei ainda aqui no curso, que no caso foi o ternário, peço desculpas professor eu nem me atentei de estar usando.
No mais, agradeço muito pelo feedback, me ajuda a melhorar, um ótimo domingo para sr. e família.

**Comment by Roger-Melo** [comment]
Show @LuizGustavoDiniz. No que precisar, é só abrir uma nova issue =)
