### ISSUE TITLE
Etapa 9 , Aviso Importante

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1311]
Olá Roger ,é pra fazer minha própria versão do To-do-List desenvolvido por mim ?
Não vi nas aulas você pedindo isso...
Quais são as regras ?

Obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @jhow221318. Qual é o seu e-mail?

**Comment by jhow221318** [comment]
Meu email é ***@***.***
Boa noite ....

Em sáb, 24 de jul de 2021 23:08, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
@jhow221318 seu e-mail não foi exibido. 

Você precisa responder a issue pelo GitHub ou enviar um e-mail pra oi@rogermelo.com.br sacou?

**Comment by jhow221318** [comment]
Bom dia ? Desculpe não sabia que ele ficava oculto .
Mas em fim o email é : jonathanrepresentacoesja@gmail.com

obrigado ,desculpe te  incomodar no domingo.... Abraço

**Comment by Roger-Melo** [comment]
Tranquilo @jhow221318. Mandei lá xD
