### ISSUE TITLE
Aplicação: [To-do-list]

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1315]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/jhow221318/To-do-list.git

### Maiores dificuldades durante a implementação

Achei bem tranquilo, só não consegui fazer com o que meu listener de eventos funcionasse tanto clicando quanto apertando enter , tentei colocar dois parâmetros separados por virgula mas não deu certo.... No mais tentei fazer sem olhar ... 
Como dito por você eu complico as vezes , podia ser mais simples e faço o mais complicado é uma falha minha tenho que corrigir mas não sei como , eu começo a desenvolver ai vou achando caminhos e vou seguindo ....  

### Menores dificuldades durante a implementação

Estou me acostumando com a sintaxe do javaScript esta ficando bem tranquilo ,tenho que estudar mais objetos , sei a sintaxe do objeto literal e sei colocar métodos neles , mas destructor e outras artimanhas estou meio perdido.

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by jhow221318** [comment]
Vou fechar  a issue porque eu subi o To-do-list do curso me desculpe vou subir de novo e abro outra issue.
ok?

**Comment by Roger-Melo** [comment]
Traquilo @jhow221318. Fico no aguardo =)
