### ISSUE TITLE
Etapa 05, nome do vídeo: "Desenvolvendo um POPUP"

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#1316]
Seria muito bom se você coloca-se na descrição dos videos que tem chamada para fazer os exercícios, o numero do exercício referente a aula. Pois no repositório, esta com nomenclatura de exercicio-01, exercicio-02, exercicio-03, etc. E se ficarmos 3 dias sem acessar o curso, quando vamos fazer o exercício, precisamos ficar procurando qual pasta do exercício é referente a aula que estou.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr. Obrigado pela sugestão =)

Seria tipo isso?

![exercicios-na-descricao](https://user-images.githubusercontent.com/29297788/127045038-d26ab0a4-187c-4961-8582-f5afdb1b4527.jpg)

**Comment by JuniorAlvesbr** [comment]
Isso.
Pelo que vi essa identificação de exercício-01 só tem nessa aula.
tem nas outras aulas?

**Comment by Roger-Melo** [comment]
Na real, à partir do exercício 20 se não me engano, os links das baterias de exercício de cada aula ficam em uma pág. separada, dessa forma:

![01](https://user-images.githubusercontent.com/29297788/127058804-202a2bf5-073a-4402-8951-88a8ab8317a3.jpg)

![02](https://user-images.githubusercontent.com/29297788/127058809-52e8c3a0-f6a6-4b3e-bd40-0aa7ab2356a3.jpg)

> Pelo que vi essa identificação de exercício-01 só tem nessa aula.

Coloquei agora esse link, pra testar se era sobre isso mesmo que vc estava falando. Vou continuar inserindo os links nas demais aulas =)

@JuniorAlvesbr

**Comment by JuniorAlvesbr** [comment]
Isso mesmo, agora ficou show, com esse link direto, fica mais fácil de identificar o exercício da aula.

**Comment by Roger-Melo** [comment]
Legal @JuniorAlvesbr. Se tiver qualquer dúvida ou quando tiver mais sugestões, fique à vontade para abrir uma nova issue =)
