### ISSUE TITLE
Quiz Interativo da etapa 07

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#1319]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/zolive72/Interative-Quiz/

### Maiores dificuldades durante a implementação

Não tive dificuldades em implementar o código em JS, porém demorei muito em concluir o projeto, pois passei muito tempo em buscar informações sobre o framework Bootstrap que eu achei muito interessante e que facilita na construição dos projetos. Em realidade, sempre usei o CSS puro.

### Menores dificuldades durante a implementação

Implementar o código JS foi bastante simple, mas sei que podemos simplificar o código um pouco.

**Comment by Roger-Melo** [comment]
Olá @zolive72.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @zolive72!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## ...passei muito tempo em buscar informações sobre o framework Bootstrap...

O uso do Bootstrap (ou qualquer lib CSS) nas aplicações é opcional, ok?

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Organização de código

### Estilo CSS

Não existe um arquivo `style.css` na raiz do projeto. Isso fez com que na linha `<link rel="stylesheet" href="style.css">`, o browser lançasse um warning ao tentar parsear um arquivo CSS que não existe. Remova a linha e o warning desaparecerá do console.

### Extensão `.htm`

Faltou o "l" no final da extensão do `index`.

Mesmo que a extensão `.htm` ainda possa ser usada, faria mais sentido usá-la nos tempos do MS-DOS e Windows 16 bits. Como hj os nomes dos arquivos podem ter mais de 8 caracteres e as extensões mais de 3, prefira usar `html` (a não ser que exista uma boa razão para usar .htm).

### Backslash em paths

Por [padrão](https://stackoverflow.com/a/1589959/8138956), eu recomendo que vc prefira usar `/` (padrão unix-like) em paths. O `src` da `<script>` ficaria assim:

```html
<script src="./app.js"></script>
```

Mesmo que `\` funcione, em qualquer time que vc for trabalhar as chances são de que o padrão unix-like será aplicado.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode inserir uma linha em branco entre o fim do `forEach` e o `alert`.

## Lógica

Não é necessário inserir `return` dentro do callback do `forEach`, pois nada vai ser feito com o valor no qual a expressão `score += 20` resulta. 

Além disso, o `forEach` não deve ser usado para retornar valores, por que ele [nunca retorna um valor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#return_value) (você ainda verá isso no treinamento).

A única ação que precisa acontecer dentro do `forEach` é o cálculo dos pontos através da mutação na `score`, então ele ficaria assim:

```javascript
  userAnswers.forEach((userAnswer, index) => {
    if (userAnswer === correctAnswers[index]) {
      score += 20;
    }
  })
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by zolive72** [comment]
Boa noite Roger e obrigado pelos comentarios.

### LIB CSS
Entendi que o uso do Bootstrap é opcional. Para mim, foi uma oportunidade conhecer um novo framework através do curso CJRM.

### Estilo CSS
Cometei o arquivo style.css no Visual Studio Code; na realidade o documento .css existe mas não puxei ele para o githhb, pois o documento está vazio por enquanto.

### Extensão .htm
Consertei a extensão para html no documento index.html. Foi um erro de falta de atenção minha.

###Backslash em paths
Substituí o backslash (\) pelo slash (/) como aconselhado nos comentários, seguindo o [padrão](https://stackoverflow.com/questions/1589930/so-what-is-the-right-direction-of-the-paths-slash-or-under-windows/1589959#1589959).

###Linhas em branco e Lógica
Entendi esses tópicos.

**As observações fizeram sentido, obrigado Roger pelos comentários**
