### ISSUE TITLE
Aplicação: [To-do-list-jhow221318]

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1320]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/jhow221318/To-do-list-jhow221318.git

### Maiores dificuldades durante a implementação

Eu coloquei um botão pra cadastrar os To-do-list mas não consegui fazer com que funcionasse tanto com o click quanto com o enter, eu vou desenvolvendo mas na maioria das vezes vou pra caminhos mais difíceis, acho que com o tempo vou encontrar  atalhos e vou fazendo códigos melhores.

### Menores dificuldades durante a implementação

A sintaxe do javaScript eu estou me acostumando, não foi difícil de fazer as funcionalidades mas fiz umas gambiarras , não quis voltar ao código, gostei do resultado agora aguardo o feedback .

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
@jhow221318 o único arquivo no repositório é o `README.md`

**Comment by jhow221318** [comment]
Tô usando  gitHub a pouco tempo ,na hora de subir o código ele foi pra  branches master eu te mandei a main , já atualizei ...

Desculpe .... Por favor ok?

boa tarde...

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Pelo que vi, infelizmente você continua com a mesma lacuna da análise passada.

Essa lacuna é a espinha dorsal - é o principal ponto que vai acelerar ou retardar a sua chegada na fluência. A lacuna é: não seguir o GPS à risca.

Eu acredito que você sabe disso, até pq vc mesmo disse "na maioria das vezes vou pra caminhos mais difíceis".

O código das suas aplicações está **muito** diferente do que mostro nas aulas, e isso demonstra que o GPS não está sendo seguido.

Se alguém que está aprendendo a cozinhar quer aprender a fazer pudim, há duas escolhas: seguir a receita ou ignorar a receita. Se a receita não é seguida, as chances são que essa pessoa fez uma parada que na opinião dela pode até parecer um pudim... mas na verdade é outra coisa.

A minha recomendação é a mesma da análise passada: aprenda a fazer o básico primeiro. Depois de aprender o básico, aí vc improvisa.

Eu vou deixar novamente [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928) o passo a passo que eu recomendo vc seguir.

Não tente achar atalhos. Segue o GPS. Sua chegada na fluência depende disso. Os alunos que já chegaram na fluência seguiram o mesmo passo a passo que você tem acesso.

**Comment by jhow221318** [comment]
Blz , mas sobre a aplicação ,ela estava funcional ? 
Como eu disse anteriormente meu problema é tempo , não tenho tanto tempo pra sentar na frente de um computador e ficar por várias horas dedicado somente a programação.
Mas compreendo que seu feedback é para eu alcançar o bjetivo que é a fluência , suas aulas são muito boas e seu curso é bem bacana . Como você disse eu vou refazer o curso várias vezes , a minha meta é terminar o curso e vim refazendo todos os exercícios, se eu conseguir fazer todos estes sem precisar nenhuma vez rever as aulas,vou me considerar que estou fluente em JavaScript .
Coloco a profissão de programador como a de médico já que eu nunca vou parar de estudar e nem quero eu gosto ... Posso ficar fluente em um ano ou 5 mas vou ficar , nem sempre os melhores nasceram com o dom natural mas tem pessoas que compensa com treino . Romário não treinava foi o melhor do mundo uma vez , o Cristiano Ronaldo  treina mais que qualquer um dos outros atletas foi melhor do mundo 5 vezes .
Vou rever a aula que você colocou no Link mas não vou iniciar o curso novamente se não eu não vou sair do while(1<10){ 
Console.log("recomeçar")
}.kkk 
Mas faço o compromisso de fazer quantas vezes eu precisar o curso ok .  Abraço

**Comment by jhow221318** [comment]
Tudo bem , vou tentar fazer o que vc me falou ,eu tenho muito pouco tempo pra estudar ,mas sobre a aplicação ela ficou funcional ? Obg boa noite

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

> ## mas sobre a aplicação ela ficou funcional

Sim, exceto pelo botão/form de adicionar to-dos. Neste caso, para que o to-do seja adicionado pressionando enter ou o botão, `<button>` precisa estar dentro de um `<form>` e o listener de evento do tipo `submit` deve estar adicionado no `<form>`.

Embora a aplicação esteja funcional em boa parte, houve uma série de decisões que comprometeram a qualidade do código devido à não-aplicação do que foi mostrado nas aulas.

---

> ## ...eu tenho muito pouco tempo pra estudar...

Entendo. Esse é um problema com o qual todos temos que lidar. 

Porém, as pessoas tendem a pensar que se elas pularem partes do método, elas vão economizar tempo e ganhar velocidade. Mas no geral, é exatamente isso que deixa a chegada no resultado mais devagar, pois elas precisam voltar e observar qual lacuna elas deixaram passar e que está impedindo-as de avançar agora.

Eu não encontrei seus resumos entre os mais de [976](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=is%3Aissue+is%3Aopen+label%3A%F0%9F%93%84resumo) que já foram publicados no repositório. Também não encontrei issues de dúvidas que você teve antes mesmo da primeira aplicação (Quiz). Pelo que vi de seu desempenho até aqui, o tempo não é necessariamente o maior problema, mas sim o que está sendo feito com esse tempo.

Se vc conseguir estudar 1h por dia, mas seguindo o [ATER](https://youtu.be/Ex6tyWvK0Nc) à risca, sua performance seria melhor que a atual.

O problema não é "demorar". O problema é não aprender. É exatamente pq vc não tem tempo que precisa treinar bem usando o pouco tempo que tem. Sacou a ideia? =)

**Comment by jhow221318** [comment]
Entendo sim , obg eu vou rever o método ATER , e irei me atentar a estes detalhes observados por vc . Obg abraço , eu nem sabia que tinha que fazer estes resumos . Obg

**Comment by Roger-Melo** [comment]
## > eu nem sabia que tinha que fazer estes resumos

Falei sobre eles e outros assuntos importantes na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928).

Vou fechar essa issue mas no que precisar, é só abrir uma nova =)
