### ISSUE TITLE
Etapa 08, nome do vídeo: Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#1322]
Olá Roger, tudo bom?  Espero que sim! 
Então, no exercício 02 deste video, como o método `.reduce()` ainda estava difícil de entender, eu rersolvi com o `.filter()`, assim:
```js
const crazyNumbers = [937, 5, 395, 402, 501, 333, 502, 781, 3, 691]
const getNumbersBelow501 = item => item < 501
const numbersBelow501 = crazyNumbers.filter(getNumbersBelow501).length

console.log(numbersBelow501) // 5

```
Mas eu entendi como o reduce funciona agora, a minha dúvida é que, caso um exercício que você proponha tenha duas ou mais maneiras de se resolver, qual escolher?
Por que o `.reduce()` seria o mais indicado nessa solução? 
Ah, e quanto às linhas em branco? Eu poderia inserir uma linha em branco entre a declaração de `const crazyNumbers` e a resolução, para demonstrar que existe um problema e uma solução? Obrigado, abraço!

P.S.:O curioso é que eu resolvi o exercício 04 com o `.reduce()`, teoricamente mais difícil, sem problema XD.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @WebDevCampos.

> ## ...caso um exercício que você proponha tenha duas ou mais maneiras de se resolver, qual escolher?

Exercite as duas =D

Se houver alguma dúvida em qual delas eu recomendo, pode abrir uma issue =)

---

> ## Por que o `.reduce()` seria o mais indicado nessa solução?

Nesse caso, a solução que vc fez é válida sim. Eu resolvi com o reduce exatamente para mostrar uma forma alternativa ao filter de se resolver.

Mas em geral, o princípio é:

- Preciso gerar um array com a mesma quantidade de itens do array original? Uso o `map`;
- Preciso gerar um array com uma quantidade de itens menor que a do array original? Uso o `filter`;
- Preciso gerar um outro tipo de valor à partir do array original? Uso o `reduce`.

Esse é o 80/20 de casos de uso desses métodos. 

Pela versatilidade do reduce, ele é capaz de cobrir qualquer caso de uso do `map` e do `filter`, mas isso não significa que ele deve ser usado em todos os casos.

---

> ## Ah, e quanto às linhas em branco?

Eu deixaria uma linha em branco entre `crazyNumbers` e `getNumbersBelow501` para separar consts que armazenam valores de consts que executam/armazenam alguma lógica =)

Ficou mais claro?

**Comment by WebDevCampos** [comment]
Sim, ficou mais claro, obrigado!!

Em ter, 27 de jul de 2021 10:34, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
