### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by edmaaralencar** [roger-melo-treinamentos/curso-de-js-roger-melo#1327]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edmaaralencar/quiz

### Maiores dificuldades durante a implementação

Mexer com Bootstrap (meu primeiro contato com o framework foi nessa aplicação).

### Menores dificuldades durante a implementação

Lógica e implementação do score.

**Comment by Roger-Melo** [comment]
Olá @edmaaralencar.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @edmaaralencar!

Parabéns pelo esforço em construir a primeira aplicação do treinamento. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

### Local da exibição dos pontos

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![exibicao-dos-pontos](https://user-images.githubusercontent.com/29297788/127553537-c49d7d5f-b8d6-439d-b0cf-c1cc2c22e963.jpg)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`div` é uma const vaga, pois não descreve sobre o que se trata a div. `scoreContainer` descreve de forma mais clara sobre o que se trata essa div.

Um outro ponto é renomear `quizDiv` para `quizContainer`. Assim, se amanhã a div for substituída por uma `<section>`, a const não precisará ser renomeada.

Uma pequena correção que vc tb pode fazer é inserir um espaço após o "de" na palavra "denovo". Ficaria "de novo".

Se `currentScore` for nomeada como `score`, o código ficará mais coerente, pois tanto o parâmetro da `insertScoreIntoDOM` quando o argumento que a invocação dela recebe vão ter o mesmo nome.

## Lógica

Em breve você encontrará pontos do treinamento e que eu começo a falar sobre imutabilidade. 

Mas se você quiser, é possível evitar a reatribuição na let `scoreMessage` e o `else`.

Dessa forma:

```javascript
const getScoreMessage = score => {
  if (score === 0) {
    return 'Você não conseguiu acertar nenhuma questão. Quer tentar de novo?'
  }
  
  return `Parabéns, você conseguiu: ${score} pontos de 100. Quer tentar de novo?`
}

const insertScoreIntoDOM = score => {
  const scoreMessage = getScoreMessage(score)
  
  // ...
}
```

Em breve, você será apresentado ao ternário e poderá implementar uma versão ainda mais concisa da função:

```javascript
const getScoreMessage = score => score === 0 
  ? 'Você não conseguiu acertar nenhuma questão. Quer tentar de novo?' 
  : `Parabéns, você conseguiu: ${score} pontos de 100. Quer tentar de novo?`
```

Não se preocupe caso ainda não entenda essa sintaxe, são cenas dos próximos capítulos =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by edmaaralencar** [comment]
Fazem total sentido Roger, eu pensei até em colocar o operador ternário, mas como você não tinha ensinado ainda, não coloquei. Mas de resto, as observações fazem sentidos e vou corrigir, obrigado.

**Comment by Roger-Melo** [comment]
Excelente @edmaaralencar. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
