### ISSUE TITLE
Resumo da Aula Constante e Variáveis e Comentários da etapa - Aula 01-06

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#133]
![WhatsApp Image 2021-02-08 at 10 41 08](https://user-images.githubusercontent.com/49795140/107227944-cc952900-69fa-11eb-8c92-b04fe2489e90.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí Rodrigo!

Nas próximas, veja se consegue enquadrar a folha do caderno na foto. Fica mais legal para ler =)

Rumo à fluência! 👊

**Comment by azulinho10** [comment]
Pode deixar. 👍
