### ISSUE TITLE
Aplicação: Covertor de Moedas

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#1334]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/cdfortes/currency-converter-js

### Maiores dificuldades durante a implementação

A refatoração do código

### Menores dificuldades durante a implementação

Fazer a aplicação sozinho (grandes avanços :), somente com os conhecimentos adquiridos durante o curso e leitura da documentação da API.

**Comment by Roger-Melo** [comment]
Olá @cdfortes.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @cdfortes!

Parabéns pelo esforço em construir mais uma aplicação do treinamento =)

> ## Maiores dificuldades durante a implementação: A refatoração do código

Esse exercício é um pouco mais hardcore, pois é o 1º exercício em que eu não mostrei a implementação da aplicação antes.

Mas lembre-se, o importante é primeiro fazer funcionar, como você fez! Á partir disso, com o conhecimento que você for adquirindo, você pode voltar, tentar refatorar, e melhorar o que você já fez nessa aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Organização de código

### Organização do código em "blocos"

Se a invocação da `setDefaultValues()` ficar no final do código, ele ficará mais organizado, pois no topo ficam as declarações de consts/lets, em seguida as declarações de funções e, no final, as invocações dos métodos.

Assim vc organiza o código em "blocos" nos quais as linhas desses blocos fazem coisas parecidas =)

### Nomes de variáveis e funções

Para deixar mais claro que a `getCurrenciesCodes` obtém os códigos das moedas quando a aplicação é inicializada, eu a nomearia como `getInitialCurrencyCodes` ou `getDefaultCurrenciesCodes` (seguindo a nomenclatura que vc usou).

Também renomearia a `showResultInDOM` como `showUpdatedRates`, para descrever que ela exibe o câmbio atualizado.

## Lógica

Para trabalhar com arrays, sempre prefira trabalhar com métodos de arrays que não lhe induzam a executar efeito colateral (quando possível), exemplo: `map`, `filter` e `reduce`.

```javascript
// antes
codes.forEach((currencyCode) => {
  currencyOne.innerHTML += `<option value="${currencyCode}">${currencyCode}</option>`
})

// depois
const options = codes
  .map(code => `<option value="${code}">${code}</option>`)
  .join('')

currencyOne.innerHTML += options
```

Perceba que não é necessário executar o efeito colateral (manipulação de DOM) a cada iteração do `forEach`. É possível "separar" efeito colateral e manipulação de strings. Isso será mostrado com mais detalhes nas aulas seguintes da construção dessa aplicação, o exemplo foi apenas para dar uma ideia =)

`showUpdatedRates` (antiga `showResultInDOM`) não precisa ser uma função `async`, pois ela não executa operação assíncrona. Então as palavras-chave `async` e `await` podem ser removidas dela:

```javascript
const showUpdatedRates = (conversion_result, conversion_rate) => {
  convertedValue.textContent = conversion_result.toFixed(2)
  conversionPrecision.textContent = 
    `1 ${baseCode} = ${conversion_rate} ${targetCode}`
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by cdfortes** [comment]
Execelente! Fizeram sim prof. Obrgado!

**Comment by Roger-Melo** [comment]
Show @cdfortes. No que precisar, é só abrir uma nova issue =)
