### ISSUE TITLE
Etapa 07, Exercícios Aula 01: Quiz Interativo

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1335]
Olá professor! Tudo bem?a dúvida e seguinte: tenho que usar a mesma estrutura do seu quiz ou posso me arriscar inserindo tudo foi nas aulas anteriores.
Porque pensei passar as perguntas em array de objeto no Javascript e inserindo ela com innerHTML na página.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @AnaCosta29!

Eu recomendo que primeiro vc faça funcionar como mostrei nas aulas e me mostre o código.

Depois que eu analisar e te dar feedback, se vc quiser, vc pode fazer uma versão alternativa usando objetos e me mostrar também =)

Mas lembre-se: o desafio é vc implementar os exercícios/aplicações apenas com o que viu no treinamento até aqui. E eu acho que até o ponto do desafio do quiz, eu não cheguei a mostrar como iterar por objetos, sabe? Por isso penso que seja melhor vc implementar como já mostrei. Depois, conforme vc for progredindo no treinamento, vc verá formas de iterar por objetos e pode refatorar o código da aplicação se quiser =)

**Comment by AnaCosta29** [comment]
Entendi professor.
