### ISSUE TITLE
Etapa 7, Introdução ao Bootstrap: Aula 01-02

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1339]
Alguém teve o mesmo problema?

```js
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Quiz Interativo Aula 01 Etapa 07</title>
</head>
<body>

```
![image](https://user-images.githubusercontent.com/44072541/127744709-e3aafc14-9e99-4a10-822e-b1e1dc0a21d8.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

No momento do carregamento, provavelmente alguma extensão ou configuração pode estar em conflito com o css minificado do Bootstrap, mas isso não afeta o seu código. 

Caso queira remover o warning, você pode seguir [estes passos](https://stackoverflow.com/a/36069603/8138956) e habilitar novamente os source maps em algum momento futuro, quando achar necessário =)

Se o problema persistir, pode comentar novamente aqui na issue =)
