### ISSUE TITLE
Resumo da Aula 01-02 da etapa 01

### ISSUE THREAD

**Issue by emanuelcontinib** [roger-melo-treinamentos/curso-de-js-roger-melo#135]
**Novidades para mim nessa etapa:**

`const m = mozilla[0]`
 [0] busca o caractere na posição indicada;

` const lastLetter = randomWord.length `
 Traz o tamanho da palavra;

` const summerMessageLower = summerMessage.toLowerCase() `
 toLowerCase() e toUpperCase() são métodos de strings;

` const index = winterMessage.indexOf('')`
 Traz a posição do caractere desejado

`const str = harryPotterAuthor.slice(0,4)`
Extrai uma seção de uma string e a retorna como uma nova string, sem modificar a string original, iniciando no primeiro parâmetro até a posição do segundo parâmetro;

`const realBestMovie = bestMovie.replace('La la land', 'Moonlight') `
replace() substitui caracteres da string;

`const reminder = 10 % 3 `
Traz o resto da operação 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Tamo junto Emanuel!

Rumo à fluência! :rocket:
