### ISSUE TITLE
Resumo da Aula Eventos do teclado 02-03 da etapa 06

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1356]
@Roger-Melo
![eventTeclado](https://user-images.githubusercontent.com/35525950/127753735-68d9ea6c-f647-42b3-9a92-0213577d2b4a.jpeg)

**Comment by Roger-Melo** [comment]
Boa @AnaCosta29. Rumo à fluência 🔥
