### ISSUE TITLE
Etapa 14, Prototypes - Aula 03-07

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#136]
Sendo sincero e direto ao ponto: eu não entendi o propósito e o uso das funções estáticas. Poderia dar alguns outros exemplos onde elas seriam usadas? Pq eu usaria isso ao invés de um método "normal"?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

Em JavaScript, é normal ter essa impressão sobre métodos estáticos. Principalmente porque a linguagem tem evoluído para uma pegada cada vez mais funcional. E métodos estáticos fazem mais sentido quando se escolhe implementar usando fortemente o paradigma orientado à objetos. 

Na orientação à objetos, métodos estáticos são usados em casos onde esse tipo de método é importante para a classe, mas não para os objetos (instâncias) que a classe cria. Ou seja, a funcionalidade de um método estático está relacionada à classe, e não aos objetos que ela cria.

Uma prova disso é o método estático [from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).

O `Array.from()` cria um novo array baseado em um array like. 

Não faria sentido fazer algo do tipo:

```javascript
const myArrayLike = [1, 2, 3]
const convertedArray = [].from(myArrayLike)
```

Então faz mais sentido que o método `from` seja estático e seja invocado à partir da classe do que cada objeto (array) que o construtor cria tenha um método `from`. Por que a funcionalidade dele está relacionada ao construtor/classe, e não aos objetos que esse construtor cria.

Um outro exemplo é o método [all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) do construtor `Promise`. Ele é um método estático que recebe como argumento um array de promises, e quando todas as promises desse array forem resolvidas, a expressão `Promise.all(promisesArr)` resulta em uma promise e eu posso encadear um `then()` que será executado quando a expressão resultar na promise. 

Ou seja, é um método usado para que uma determinada ação seja executada apenas quando todas as promises estiverem resolvidas.

Então neste caso, como a funcionalidade do `all()` está mais relacionada ao construtor `Promise` do que às promises que esse construtor cria, percebe que faz mais sentido que ele seja um método estático?

Me diga se está ficando mais claro =)

@lucasfads

**Comment by lucasfads** [comment]
Nesses dois exemplos q vc deu as funções estáticas "constroem" um novo array e uma nova promise. Todos os métodos estáticos funcionam como construtores?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Não necessariamente.

O [freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) por exemplo é um método estático do `Object` que impede que um objeto seja modificado:

```javascript
const obj = {
  prop1: 1,
  prop2: 2
}

Object.freeze(obj)

obj.prop3 = 3
obj.prop3 // undefined
```

Um método estático também pode apenas retornar um boolean:

```javascript
class Instructor {
  constructor (name, role) {
    this.role = role
    this.name = name
  }
  
  static canTeach (instructor) {
    return instructor.role === 'Professor'
  }
}

const instructor1 = new Instructor('Zé', 'Assistente')
const instructor2 = new Instructor('Marcelo', 'Professor')

Instructor.canTeach(instructor1) // false
Instructor.canTeach(instructor2) // true
```

Nenhum desses dois métodos constrói novos objetos. Porém, eles seguem o padrão do que eu mencionei anteriormente: a funcionalidade de um método estático está mais relacionada à classe do que aos objetos que ela cria. Nos dois casos, faz mais sentido que o método seja invocado à partir da classe/construtor do que à partir dos objetos que ela cria.

Faz sentido?

@lucasfads

**Comment by lucasfads** [comment]
Aaaah, esse segundo exemplo, dos instrutores, ajudou muito mais a entender os possíveis usos dos métodos estáticos.

Mais uma pergunta: todo método estático recebe exclusivamente como parâmetro um ou mais objetos dessa mesma classe? (`Array.from()` recebeu um array, `Promise.all()` recebe um array de promises, `Object.freeze()` recebe um objeto, `Instructor.canTeach()` recebeu um instrutor) Ou existem casos diferentes?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal que ajudou!

> Mais uma pergunta: todo método estático recebe exclusivamente como parâmetro um ou mais objetos dessa mesma classe? (Array.from() recebeu um "array-like", Promise.all() recebe um array de promises, Object.freeze() recebe um objeto, Instructor.canTeach() recebeu um instrutor) Ou existem casos diferentes?

Sim. Embora a funcionalidade de um método estático esteja mais relacionada à classe do que aos objetos que ela cria. Sempre vai haver essa relação com o objeto criado. Eu pelo menos não me lembro de nenhum método estático que não receba como argumento o objeto que a classe cria =)

@lucasfads

**Comment by lucasfads** [comment]
Perfeito. Acho que isso conclui minhas dúvidas sobre isso rs
Obg!

@Roger-Melo
