### ISSUE TITLE
Aplicação: quiz_interativo

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1363]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

 https://github.com/AnaCosta29/Quiz_Interativo-CJRM 

### Maiores dificuldades durante a implementação

foi refatorar o codigo apos seu funcionamento,renomear variavéis e limpar a pontução apos envio do formulario

### Menores dificuldades durante a implementação

o uso do bootstrap ,e a mudança de cor do template

**Comment by Roger-Melo** [comment]
Olá @AnaCosta29.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by AnaCosta29** [comment]
‘Show’ professor, faz sentido total… isso de mostrar quantos de acertos foi vacilo meu. Vou corrigir os pontos mencionados pelo senhor valeu.

**Comment by Roger-Melo** [comment]
Legal @AnaCosta29. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
