### ISSUE TITLE
Aplicação: Weather-application

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1366]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Mateus20Barros/weather-application

### Maiores dificuldades durante a implementação

Acho que nesta aplicação tive poucas duvidas em relação ao que eu queria desenvolver para essa aplicação, pois com a base adquirida no curso e usar meus conhecimentos para desenvolver a mesma, me senti mais confortável para desenvolve-la.

Claro que essa parte de `assincronismo com javascript` é um pouco complicado entender, mais nada que a pratica de implementar alguns projetos para cada vez mais solidar os conhecimentos desse conceito.

Minha maior dificuldade foi decidir seu eu deixava a aplicação com opção para mudar o tema, `Dia` e `Noite`, optei por deixar a opção que troca o tema.

### Menores dificuldades durante a implementação

Utilizar os conhecimentos adquiridos durante o treinamento.

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Usabilidade

Não sei se vc vai subir essa aplicação para produção, mas se for o caso, vale pensar em como a aparência dela será em telas com largura menor =)

## Organização de código

### Opcionais em arrow functions

Talvez vc tenha deixado por que prefere, mas apenas lembrando... como são arrow functions que executam apenas uma ação, o `return` e blocos nas funções `getCityUrl` e `getWeatherUrl` são opcionais:

```javascript
const getCityUrl = cityname => 
  `${baseUrl}locations/v1/cities/search?apikey=${APIKey}&q=${cityname}`

const getWeatherUrl = cityKey => 
  `${baseUrl}currentconditions/v1/${cityKey}?apikey=${APIKey}&language=pt-br`
```

### Local de invocações dos métodos

Para não deixar o `setInterval` "perdido", vc pode deixá-lo junto com as invocações dos outros métodos da aplicação.

### Nomes de variáveis e funções

Voltando no princípio de nomeação de variáveis que mencionei [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1046#issuecomment-871371306), `isDayOrNight` pode ser renomeada como `changeCityCardBackground` (verbo) e para deixar a `checkInputValue` mais descritiva em relação ao que ela faz, eu a nomearia como `showFlipCard`.

### Refatoração

Acredito que `getWeatherInfo` e `showCityWeatherInfo` estão com os nomes trocados.

`getWeatherInfo` pode ficar apenas com o request e obtenção dos dados e `showCityWeatherInfo` fica responsável apenas por exibir os dados na tela:

```javascript
const getWeatherInfo = async cityName => {
  const [{ Key, LocalizedName }] = await getCityData(cityName)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(Key)
  return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
}

const showCityWeatherInfo = async cityName => {
  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = await getWeatherInfo(cityName)

  timeIconContainer.innerHTML = `<img src="./assets/src/icons/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  
  changeCityCardBackground(IsDayTime)
}
```

## Lógica

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para setar o display da `flipCard` (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu o usaria apenas para fazer a propriedade `display` receber a string:

```javascript
// antes
const showFlipCard = inputValue => {
  return inputValue === ''
    ? flipCard.style.display = 'none'
    : flipCard.style.display = 'block'
}

// depois
const showFlipCard = inputValue => {
  flipCard.style.display = inputValue === '' ? 'none' : 'block'
}
```

Observe também que o `return` é desnecessário ali no primeiro exemplo, pois nada está sendo feito com o valor que o ternário retorna.

Já no segundo exemplo, vc até pode deixar a função com o retorno implícito e remover os blocos, desde que seja uma escolha consciente:

```javascript
const showFlipCard = inputValue => 
  flipCard.style.display = inputValue === '' ? 'none' : 'block'
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Mateus20Barros** [comment]
Olá @Roger-Melo 
Sim, fizeram sentidos.

A parte responsiva da aplicação eu omiti nesse momento, pois estava querendo terminar a aplicação para dar sequencia no curso. Isso será acrescentado no projeto em alguns dias, pois nas outras aplicações anteriores também terei que aplicar responsividade. 

Já em relação as observações do código, eu irei aplicar esses conceitos observados aqui, assim que possível.

Desde já agradeço pela atenção 👍

**Comment by Roger-Melo** [comment]
> ### **Ao trabalhar com manipulação do `DOM`, é mais aconselhável usar `data-js=` ao invés de manipular através de `classes` e assim deixar as `classes` para manipular somente os estilos da página no `CSS`?**

Exatamente. Pode ser `data-js` ou **[qualquer nome após o traço](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)**. Isso separa mais as responsabilidades dos atributos e deixa o seu código mais organizado =)

@Mateus20Barros

**Comment by Roger-Melo** [comment]
@Mateus20Barros vou fechar a issue mas no que precisar, é só abrir uma nova =)
