### ISSUE TITLE
Aplicação: WeatherApp

### ISSUE THREAD

**Issue by crjstjanojose** [roger-melo-treinamentos/curso-de-js-roger-melo#1382]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/crjstjanojose/weather-app-cjrm

### Maiores dificuldades durante a implementação

Identificar partes para um refatoramento mais eficaz tentei fazer a aplicação sem ficar olhando muito a feita no decorrer das aulas para assim avaliar o meu aprendizado.

### Menores dificuldades durante a implementação

Montar layout, selecionar elementos não tive grandes dificuldades para desenvolver essa versão enviada.

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose!

Parabéns pelo esforço em construir mais uma aplicação do treinamento =)

> ## Identificar partes para um refatoramento mais eficaz tentei fazer a aplicação sem ficar olhando muito a feita no decorrer das aulas para assim avaliar o meu aprendizado.

Boa! É por aí mesmo. Primeiro faz, depois melhora =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

### `autofocus` no `input`

Quando a página for carregada, você já pode deixar por padrão um foco no input de pesquisa, usando no `input` o atributo `autofocus`. Assim o usuário não precisa mover o cursor do mouse e clicar no input para inserir um valor.

### Ortografia

No `<title>`, observe também que a ortografia correta é "weather" ao invés de "weader".

## Lógica

### Ternários

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para remover classes CSS (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu usaria apenas um `if`:

```javascript
// antes
resultado.classList.contains("hidden")
  ? resultado.classList.remove("hidden")
  : "";

// depois
if (resultado.classList.contains("hidden")) {
  resultado.classList.remove("hidden")
}
```

No caso em que a propriedade `src` recebe uma string, ao invés de executar a atribuição, vc pode usar o ternário para selecionar qual string a propriedade vai receber:

```javascript
// antes
IsDayTime
  ? (resultadoImagem.src = "./img/day.svg")
  : (resultadoImagem.src = "./img/night.svg");

// depois
resultadoImagem.src = IsDayTime ? "./img/day.svg" : "./img/night.svg"
```

### Nomes de variáveis e funções

`resultado` é uma const que precisa ter um nome mais descritivo em relação ao valor que ela armazena. Foi necessário investigar a marcação HTML para que eu descobrisse do que se tratava. Como vc está nomeando em pt-BR, provavelmente, um nome como `recipienteDaCidade` ou `conteinerCidade` ficaria mais descritivo =)

### Refatoração

Uma possível abordagem para a refatoração do código poderia ser a seguinte...

Nomear a função de callback do envio do form como `lidaComEnvioFormBusca` e, então, quebrá-la em partes menores.

```javascript
const lidaComEnvioFormBusca = async (event) => {
  event.preventDefault();

  const denominacao = event.target.cidade.value;
  const [{ Key, LocalizedName }] = await obterDadosLocalidade(denominacao);
  const [{ WeatherText, WeatherIcon, IsDayTime, Temperature }] =
    await obterTemperaturaLocalidade(Key);

  gerarHTMLResultado(
    LocalizedName,
    WeatherText,
    WeatherIcon,
    IsDayTime,
    Temperature
  );

  formBusca.reset();
}

formBusca.addEventListener("submit", lidaComEnvioFormBusca);
```

Ela pode ser quebrada em duas partes:

Uma função `pegaInformacoesDoClima`, responsável por executar a requisição, e uma outra função para mostrar as informações do clima na tela. Neste caso, eu renomeei `gerarHTMLResultado` para `mostraInformacoesDoClima`.

Ficaria mais ou menos assim:

```javascript
const pegaInformacoesDoClima = async (cidade) => {
  const [{ Key, LocalizedName }] = await obterDadosLocalidade(cidade);
  const [{ WeatherText, WeatherIcon, IsDayTime, Temperature }] = await obterTemperaturaLocalidade(Key);
  return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
}

const mostraInformacoesDoClima = async (cidade) => {
  const { LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature } = 
    await pegaInformacoesDoClima(cidade)
  
  if (conteinerCidade.classList.contains("hidden")) {
    conteinerCidade.classList.remove("hidden")
  }

  resultadoImagem.src = IsDayTime ? "./img/day.svg" : "./img/night.svg"
  resultadoIcone.src = `./img/icons/${WeatherIcon}.svg`;
  resultadoCidade.innerText = LocalizedName;
  resultadoDescricao.innerText = WeatherText;
  resultadoTemperatura.innerText = Temperature.Metric.Value;
};

const lidaComEnvioFormBusca = (event) => {
  event.preventDefault();

  const cidade = event.target.cidade.value;
  mostraInformacoesDoClima(cidade);
  formBusca.reset();
}

formBusca.addEventListener("submit", lidaComEnvioFormBusca);
```

Essa é uma possibilidade =)

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
@crjstjanojose vou fechar a issue mas no que precisar, é só abrir uma nova =)
