### ISSUE TITLE
Erro durante a refatoração

### ISSUE THREAD

**Issue by gbr-jpg** [roger-melo-treinamentos/curso-de-js-roger-melo#14]
Roger meu código está funcionando certinho como proposto no exercício, analisando a sua refatoração do código na exata hora que pego os parâmetros do inserParagraphIntoDOM e jogo para dentro de um objeto tenho este erro retornado, porém quando não utilizo estes objetos como forma de refatorar o código ele funciona certinho quando invoco a função insertParagraphIntoDOM e passo os argumentos correspondentes a ela
![ALO](https://user-images.githubusercontent.com/62727587/85171311-2b781900-b245-11ea-98dd-096ddabbdb2e.png)  

```
const inputUsername = document.querySelector('#username')
const form = document.querySelector('form')
const button = document.querySelector('.button')

const paragraphValueInput = document.createElement('p')
const paragraphSubmitForm = document.createElement('p')

paragraphSubmitForm.setAttribute('data-feedback', 'submit-feedback')

const testUsername = string => /[a-zA-Z]{6,}/.test(string)

const insertParagraphIntoDOM = (previousSibling, paragraph, text, className) => {
  previousSibling.insertAdjacentElement('afterend', paragraph)
  paragraph.textContent = text
  paragraph.setAttribute('class', className)
}

inputUsername.addEventListener('input', event => {
  const inputValue = event.target.value 
  const checkInputCharacter = testUsername(inputValue)  

  const paragraphSubmitFormExists = document.querySelector('[data-feedback = submit-feedback]') 
  
  if (paragraphSubmitFormExists) {
    paragraphSubmitForm.remove()
  }

  if (!checkInputCharacter) {
    insertParagraphIntoDOM(inputUsername, paragraphValueInput, 'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas', 'username-help-feedback')
    return 
  }  

  insertParagraphIntoDOM(inputUsername, paragraphValueInput, 'Username válido =)', 'username-success-feedback')   
})

form.addEventListener('submit', event => {
  event.preventDefault()
  
  const inputValue = inputUsername.value
  const checkInputValue = testUsername(inputValue)

//  \o/... Roger, é com a implementação deste objeto que a aplicação começa a retornar o erro acima, se eu retirar este objeto e refatorar somente invocando a função insertParagraphIntoDOM e passando os argumentos adequados como fiz nos demais, o código funciona perfeitamente!

  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }
  

  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }

  insertParagraphIntoDOM(button, paragraphSubmitForm, 'Por favor, insira um username válido', 'submit-help-feedback')
})

**Comment by gbr-jpg** [comment]
Ps: é dentro do evento form que está meu objeto destacado pela \o/ kkk

**Comment by Roger-Melo** [comment]
Oi @gbr-jpg!

Pode subir o código do projeto completo pro github para eu testar aqui na minha máquina?

Se preferir, pode me enviar o arquivos zipados também =)

**Comment by gbr-jpg** [comment]
Prontinho Roger, repo criado: https://github.com/gbr-jpg/exercicio-18---CRJM

**Comment by Roger-Melo** [comment]
Oi @gbr-jpg!

O que está acontecendo é o seguinte, na invocação da `insertParagraphIntoDOM`, dentro do if da linha 75, 

```js
  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }
```

um objeto está sendo passado como argumento.

Porém, na declaração da `insertParagraphIntoDOM`, na linha 35,

```js
const insertParagraphIntoDOM = (previousSibling, paragraph, text, className) => {
  previousSibling.insertAdjacentElement('afterend', paragraph)
  paragraph.textContent = text
  paragraph.setAttribute('class', className)
}
```

como o que está sendo recebido pelo parâmetro `previousSibling` é um objeto, na 1º linha dentro da função, a invocação do método `insertAdjacentElement` está encadeada nesse objeto que o `previousSibling` recebeu. Ou seja, o que está acontecendo é + ou - isso: `{...}.insertAdjacentElement(...)`.

Observe que o objeto (abaixo) que o parâmetro `previousSibling` recebeu não contém um método `insertAdjacentElement`:

```js
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }
```

Por isso o erro `previousSibling.insertAdjacentElement is not a function` é exibido.

Então, é necessário fazer com a função `insertParagraphIntoDOM` estar de fato "preparada" para receber um objeto como parâmetro e lidar com esse objeto dentro dela.

Depois de fazer essa modificação na declaração da `insertParagraphIntoDOM`, para tudo funcionar normalmente, faça as invocações dela receberem um objeto como argumento (mostro isso na aula, talvez você ainda não tenha chegado nesse ponto).

Ficou mais claro? Se ainda estiver com dúvidas me avise =)

**Comment by gbr-jpg** [comment]
Entendi Roger, valeu =)

**Comment by gbr-jpg** [comment]
Roger percebi com sua explicação a origem do erro, mas não estou conseguindo resolve-la =/

**Comment by gbr-jpg** [comment]
Boa tarde Roger!
Tá quase lá, mais ainda não ficou totalmente claro o meu entendimento da situação. Ainda estou um pouco confuso com esta situação. Pode me re-explicar por favor =/

**Comment by gbr-jpg** [comment]
Boa tarde Roger!
Tá quase lá, mais ainda não ficou totalmente claro o meu entendimento da situação. Poderia me dar uma re-explicação Roger ?

**Comment by gbr-jpg** [comment]
![copy](https://user-images.githubusercontent.com/62727587/85409517-48119b00-b53c-11ea-8937-8d2aeaf25bca.png)
Roger este ponto que você passa este objeto como argumento da função que me têm quebrado a cabeça, vendo aqui a aula, você faz a mesma coisa, não ?! Me desculpe, eu entendi o porque do erro e tudo mais, mas não estou conseguindo resolve-lo, só me vêm na cabeça: "Desencadear este objeto do parâmetro previousSibling", poderia me nortear para sair deste buraco ?

**Comment by Roger-Melo** [comment]
Entendi sua dúvida. Vamos lá, vou fazer o passo a passo contigo, conforme o código que você disponibilizou no repositório logo acima =)

Se eu inserir um username inválido no input e tentar enviar o form, nenhum erro é lançado e o parágrafo "O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas" é exibido na tela, certo?

Se observarmos o código da função de callback do addEventListener do submit do form, 

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()
  
  const inputValue = inputUsername.value
  const checkInputValue = testUsername(inputValue)
  

  // Roger foi quando eu quis passar os parametros para este objeto que começou a dar erro
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }

  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }

  insertParagraphIntoDOM(button, paragraphSubmitForm, 'Por favor, insira um username válido', 'submit-help-feedback')
})
```

quando enviei o form com o username inválido, `checkInputValue` resultou em `false`, o bloco do if não foi executado e logo abaixo do if, a `insertParagraphIntoDOM()` foi invocada recebendo os 4 parâmetros do código acima.

Na declaração da `insertParagraphIntoDOM`,

```javascript
const insertParagraphIntoDOM = (previousSibling, paragraph, text, className) => {
  previousSibling.insertAdjacentElement('afterend', paragraph)
  paragraph.textContent = text
  paragraph.setAttribute('class', className)
}
```

o parâmetro `previousSibling` recebeu a referência do botão do form, o parâmetro `paragraph` recebeu a referência do parágrafo de envio do form, o parâmetro `text` recebeu a string 'Por favor, insira um username válido' e o parâmetro `className` recebeu a string com a classe CSS.

Quando a `insertParagraphIntoDOM` recebeu esses parâmetros, ela executou o código dentro do bloco dela (considerando os parâmetros recebidos) e o parágrafo de feedback foi inserido na tela como o esperado, correto?

Agora, se eu inserir um username válido no input e enviar o form, o bloco do if abaixo é executado,

```javascript
  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }
```

e `app.js:36 Uncaught TypeError: previousSibling.insertAdjacentElement is not a function` é exibido no console.

O que esse erro está dizendo é que o `insertAdjacentElement` não é uma função adequada para o valor no qual ele foi encadeado.

Se no console, eu clicar na linha do erro, [observe que o erro](https://user-images.githubusercontent.com/29297788/85423154-c0805800-b54c-11ea-948a-cef5c647a41f.jpg) começa na invocação do `insertAdjacentElement`.

O insertAdjacentElement insere um elemento na tela na posição que a gente especificar, e essa posição é relativa ao **elemento** no qual esse método foi invocado.

Ou seja, no código abaixo,

```javascript
previousSibling.insertAdjacentElement('afterend', paragraph)
```

o `insertAdjacentElement` precisa ser encadeado em **um elemento do DOM** que vai ser a referência para o `paragraph` ser inserido na tela.

Só que ao invés de receber um elemento do DOM, como no if um objeto foi passado como argumento da `insertParagraphIntoDOM`,

```javascript
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }

  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }
```

`previousSibling` (abaixo) recebeu esse objeto,

```javascript
const insertParagraphIntoDOM = (previousSibling, paragraph, text, className) => {
  previousSibling.insertAdjacentElement('afterend', paragraph)
  paragraph.textContent = text
  paragraph.setAttribute('class', className)
}
```

e na 1ª linha, encadeou a invocação do `insertAdjacentElement('afterend', paragraph)` na `previousSibling`.

Como o `insertAdjacentElement` precisa ser encadeado **em um elemento do DOM**, o erro dizendo que insertAdjacentElement "is not a function" foi lançado.

Para resolver isso, eu preciso fazer a declaração da `insertParagraphIntoDOM` receber o objeto abaixo como parâmetro.

```javascript
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }
```

Para fazer isso, eu posso fazer com que a `insertParagraphIntoDOM` tenha apenas 1 parâmetro que recebe o objeto:

```javascript
const insertParagraphIntoDOM = obj => {
  obj.previousSibling.insertAdjacentElement('afterend', obj.paragraph)
  obj.paragraph.textContent = obj.text
  obj.paragraph.setAttribute('class', obj.className)
}
```

ou eu posso apenas fazer um destructuring nas propriedades desse objeto que está sendo recebido como parâmetro:

```javascript
const insertParagraphIntoDOM = ({ previousSibling, paragraph, text, className }) => {
  previousSibling.insertAdjacentElement('afterend', paragraph)
  paragraph.textContent = text
  paragraph.setAttribute('class', className)
}
```

Só que se eu fizer isso e salvar, se eu inserir um caractere no input, `Uncaught TypeError: previousSibling.insertAdjacentElement is not a function` é exibido novamente.

Por que isso aconteceu?

Observe que quando eu insiro um valor no input, ele muda de valor e o callback abaixo é executado:

```javascript
inputUsername.addEventListener('input', event => {
  const inputValue = event.target.value 
  const checkInputCharacter = testUsername(inputValue)  

  const paragraphSubmitFormExists = document.querySelector('[data-feedback = submit-feedback]') 
  
  if (paragraphSubmitFormExists) {
    paragraphSubmitForm.remove()
  }

  if (!checkInputCharacter) {
    insertParagraphIntoDOM(inputUsername, paragraphValueInput, 'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas', 'username-help-feedback')
    return 
  }  

  insertParagraphIntoDOM(inputUsername, paragraphValueInput, 'Username válido =)', 'username-success-feedback')   
})
```

Ou seja, quando inseri o input, as invocações da `insertParagraphIntoDOM` dentro desse callback vão lançar esse erro por que elas não estão recebendo um objeto com as propriedades `previousSibling, paragraph, text e className`.

Se eu declarar esses objetos e inserí-los como argumento das invocações da `insertParagraphIntoDOM`,

```javascript
inputUsername.addEventListener('input', event => {
  const inputValue = event.target.value 
  const checkInputCharacter = testUsername(inputValue)  

  const paragraphSubmitFormExists = document.querySelector('[data-feedback = submit-feedback]') 
  
  if (paragraphSubmitFormExists) {
    paragraphSubmitForm.remove()
  }
  // Objeto declarado
  const obj1 = {
    previousSibling: inputUsername,
    paragraph: paragraphValueInput,
    text: 'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas',
    className: 'username-help-feedback'
  }
  
  if (!checkInputCharacter) {
    insertParagraphIntoDOM(obj1)
    return 
  }  
  // Objeto declarado
  const obj2 = {
    previousSibling: inputUsername,
    paragraph: paragraphValueInput,
    text: 'Username válido =)',
    className: 'username-success-feedback'
  }

  insertParagraphIntoDOM(obj2)   
})
```

como a declaração da `insertParagraphIntoDOM` agora está preparada para receber um objeto como parâmetro, quando eu insiro um valor no input, seja ele um username válido ou não, nenhum erro é lançado no console.

Se eu enviar um username válido, tudo funciona perfeitamente, mas, se eu tentar enviar um username inválido, `Uncaught TypeError: previousSibling.insertAdjacentElement is not a function` é exibido novamente no console.

Isso aconteceu por que na última linha dentro do callback do envio do form,

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()
  
  const inputValue = inputUsername.value
  const checkInputValue = testUsername(inputValue)
  

  // Roger foi quando eu quis passar os parametros para este objeto que começou a dar erro
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }

  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }

  insertParagraphIntoDOM(button, paragraphSubmitForm, 'Por favor, insira um username válido', 'submit-help-feedback')
})
```

ainda há uma última ocorrência da invocação da `insertParagraphIntoDOM` que não recebeu um objeto como argumento.

Se eu criar esse objeto e passá-lo como argumento,

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()
  
  const inputValue = inputUsername.value
  const checkInputValue = testUsername(inputValue)
  

  // Roger foi quando eu quis passar os parametros para este objeto que começou a dar erro
  const validSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Dados enviados =)', 
    className: 'submit-success-feedback'
  }

  if (checkInputValue) {
    insertParagraphIntoDOM(validSubmitInfo)
    return   
  }
  // Objeto criado
  const inValidSubmitInfo = {
    previousSibling: button, 
    paragraph: paragraphSubmitForm, 
    text: 'Por favor, insira um username válido', 
    className: 'submit-help-feedback'
  }

  insertParagraphIntoDOM(inValidSubmitInfo)
})
```

a aplicação volta a funcionar normalmente.

Outro ponto de atenção, observe o código abaixo.

```javascript
const paragraphSubmitFormExists = document.querySelector('[data-feedback = submit-feedback]')
```

O `querySelector` recebe um seletor CSS como argumento que precisa ser o mesmo que o elemento contém. Na string acima, espaços em branco foram inseridos e faltaram as aspas duplas do valor do atributo.

Então ficaria assim:

```javascript
const paragraphSubmitFormExists = document.querySelector('[data-feedback="submit-feedback"]')
```

Me deixe saber se ficou mais claro, ok? =)

**Comment by gbr-jpg** [comment]
Roger sem palavras, meu muito obrigado por essa explicação, clareou aqui... finalmente kkk =)
