### ISSUE TITLE
Aplicação: [WeatherApp]

### ISSUE THREAD

**Issue by DanThug** [roger-melo-treinamentos/curso-de-js-roger-melo#1401]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/DanThug/WeatherApp

### Maiores dificuldades durante a implementação

Nomear algumas funções e variáveis, ainda sinto uma certa dificuldade em nomear algumas coisas e desculpe se deixei passar algo importante no código, estou tentando administrar várias tarefas ultimamente. Obrigado desde já pelo feedback :)

### Menores dificuldades durante a implementação

Separar os problemas em funções específicas.

**Comment by Roger-Melo** [comment]
Olá @DanThug.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @DanThug!

Parabéns pelo esforço em construir mais uma aplicação do treinamento. Sua evolução em comparação aos códigos anteriores é notável =)

> ## Nomear algumas funções e variáveis, ainda sinto uma certa dificuldade em nomear algumas coisas...

A habilidade de nomear é aperfeiçoada com a prática e o tempo. O mais importante nesse primeiro momento vc já fez, que é fazer funcionar.

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Organização de código

### Local de declaração de variáveis/funções

Prefira declarar `setDayOrNightBackground`, `showOrHideContainer`, `addIconOnContainer` e `addWeatherInfoOnContainer` antes de suas invocações. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo). 

### Seletor CSS no `querySelector`

Pelo que percebi, vc usou `data-*` para manipular elementos do DOM. Excelente.

Acredito que tenha esquecido de manter esse padrão na `const` bg, pois `.bg` é uma classe CSS.

## Lógica

Bom uso do spread na invocação do `remove` dentro da `setDayOrNightBackground`!

Na `showOrHideContainer`, o uso do ternário é possível mas é discutível que esse seja um bom caso para aplicá-lo, pois o segundo valor que o ternário retorna (`'d-none'`) não será usado. 

Então nesse caso, eu preferiria usar apenas um `if`:

```javascript
const showOrHideContainer = () => {
  const cityCardContainer = document.querySelector('[data-js="city-card"]');
  const isHidden = cityCardContainer.classList.contains('d-none');

  if (isHidden) {
    cityCardContainer.classList.add('d-block');
  }
}
```

Mas claro, nesse estágio do treinamento, o fato de vc tentar atingir um certo resultado de forma diferente do que foi mostrado na aula é um experimento válido =)

### Refatoração

Uma possível refatoração seria renomear `getWeatherInfos` para `getWeatherInfo` (no singular), fazê-la retornar um objeto com informações do clima, e criar uma função `showCityWeather` que contém também o código da `addWeatherInfoOnContainer`. 

Assim, cada função fica com apenas uma única responsabilidade. Ficaria mais ou menos assim:

```javascript
const getWeatherInfo = async city => {
  const [{ Key, LocalizedName }] = await getCityData(city);
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(Key);
  return { IsDayTime, IsDayTime, WeatherIcon, LocalizedName, WeatherText, Temperature }
}

const showCityWeather = async city => {
  const { IsDayTime, WeatherIcon, LocalizedName, WeatherText, Temperature } = await getWeatherInfo(city)
  const cityNameContainer = document.querySelector('[data-js="city-name"]');
  const cityWeatherContainer = document.querySelector('[data-js="city-weather"]');
  const cityTemperatureContainer = document.querySelector('[data-js="city-temperature"]');
  
  cityNameContainer.textContent = LocalizedName;
  cityWeatherContainer.textContent = WeatherText;
  cityTemperatureContainer.textContent = Temperature.Metric.Value;
  setDayOrNightBackground(IsDayTime);
  addIconOnContainer(WeatherIcon);
  showOrHideContainer();
}

cityForm.addEventListener('submit', event => {
  event.preventDefault();

  showCityWeather(event.target.city.value);
  event.target.reset();
});
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by DanThug** [comment]
Show, muito obrigado pelo excelente feedback, irei refatorar o código conforme recomendado. :)

**Comment by Roger-Melo** [comment]
Legal @DanThug. Vou fechar essa issue mas no que precisar, é só abrir uma nova =)
