### ISSUE TITLE
Aplicação: Quiz Interativo Aula 01 Etapa 07

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1404]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/marcosyoggy/Quiz-Interativo-Aula-01-Etapa-07

### Maiores dificuldades durante a implementação

   Ajustar o style CSS, eu até tentei usar o Bootstrap,sem sucesso, então dedicando algum tempo de pesquisa no 'display mdn'
,acho que deu pra criar algo aceitável, a minha idéia original era diferente, mas foi o que consegui.
   Eu decidi usar um Pop-up para exibir os valores, foi bem confuso,pra mim, decidir entre 'setAttribute()' e 'style()'. Os resultados no layout final variam, até consegui fazer funcionar, mas ainda restaram dúvidas na aplicação correta desses atributos.
   Num contexto geral, eu usei apenas as minhas anotações e pesquisa no MDN de alguma questão pontual('setAttribute()' e 'style()'); Mesmo na obtenção das referencias, inserção dos eventos, qualquer mensagem de erro era resolvida de forma rápida, ser detalhista na construção dos resumos das aulas ajudou muito; Mesmo com a ajuda de ferramentas como 'Bootstrap' e 'Miligram' a 'fluência' em CSS vai levar algum tempo;

### Menores dificuldades durante a implementação

   A construção dos blocos 'index.html' e 'app.js' fluiram de forma natural devido a auto-organização dos resumos das aulas, de forma detalhada, resumindo e aplicando no VSCode ao mesmo tempo, em todas as aulas sem exceção, sempre tentando criar algo original do tema proposto.
![Resma Encadernada](https://user-images.githubusercontent.com/44072541/128383126-124b7cba-78ad-44be-b0af-32d00a5138bb.jpg)

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy. Vc precisa postar o link do repositório da aplicação. O link do localhost que vc postou funciona apenas em sua máquina ([como eu havia mostrado aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/733486)) 

Fico no aguardo =)

**Comment by marcosyoggy** [comment]
...vou ser sincero, 'dei uma bela boiada' quando li sobre o link do repositório...então, dei aquela 'fuçada' e espero ter acertado...."Sempre há tempo pra aprender coisas novas"

https://github.com/marcosyoggy/Quiz-Interativo-Aula-01-Etapa-07

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### ...foi bem confuso,pra mim, decidir entre 'setAttribute()' e 'style()'. Os resultados no layout final variam...

O que variou? Pode descrever com mais detalhes?

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Boas decisões

Bom ver que dentro do callback do `forEach`, nada mais foi executado além do cálculo dos pontos e quantidade de questões. Isso é um indício de que vc entendeu a proposta do `forEach` ali =)

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Inputs e labels

Ao clicar em uma alternativa, o usuário precisa posicionar o mouse e clicar exatamente no input type radio. Isso pode causar desconforto, pois o input é muito pequeno.

Por isso, eu preferi mostrar na aula como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

## Organização de código

### Comentários

Não é uma regra, mas evite comentários na hora de subir a aplicação para produção ou no código em geral.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Se você realmente faz questão de usar comentários para que eles te ajudem nos estudos, mantenha duas versões do código; a de produção (sem comentários) e a de desenvolvimento/estudos.

### Indentação

Sempre indente o código corretamente, isso favorece a legibilidade dele. A indentação dentro do callback do `addEventListener` do `form` ficaria dessa forma:

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()

  const input_Names = [
    form.q_number_1.value,
    form.q_number_2.value,
    form.q_number_3.value,
    form.q_number_4.value,
    form.q_number_5.value
  ]

  input_Names.forEach((element, index) => {
    if (element === array_answers[index]) {
      count_Score += 20
      count_Items += 1
    }
  })

  popup_Ref.style.display = 'block'
  count_Items_Ref.textContent = `Voce acertou: ${count_Items} questões.`
  final_Score_Ref.textContent = `O valor total é: ${count_Score} pontos.`
})
```

### console.log esquecido

O `console.log()` é útil apenas no momento em que você está desenvolvendo. Sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

### Função esquecida

`insert_Content` não está sendo usada, então pode ser removida.

### Convenção de nomeação

Você nomeou em snake_case, porém, há uma inconsistência entre a nomeação de `popup_close`, `popup_Ref`, pois a segunda palavra de uma tem a primeira letra maiúscula e a outra não. Escolha um estilo e seja consistente nessa escolha no decorrer da aplicação.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`array_answers` pode ser mais descritiva se for nomeada como `correct_answers`.

Se `input_Names` for renomeada como `answers` e o parâmetro `element` do callback do `forEach` como `answer`, fica mais fácil entender o que o código abaixo está fazendo:

```javascript
answers.forEach((answer, index) => {
  if (answer === correct_answers[index]) {
    count_Score += 20
    count_Items += 1
  }
})
```

O fato do 1º parâmetro do callback do `forEach` ser apenas o singular do nome do array no qual o `forEach` foi encadeado também intensifica a coesão do código.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, prefira deixar apenas uma linha em branco ao invés das linhas 32 e 33 e 45 e 46.

Evite também deixar várias linhas em branco no arquivo apenas para separar comentário e código. 

## Lógica

O `event.stopPropagation()` dentro do callback do click no `popup_close` não é necessário. 

O `stopPropagation` deve ser usado quando algum ancestral do elemento no qual o evento foi encadeado tem o mesmo tipo de evento e vc não quer que esse evento do ancestral seja disparado também.

Sacou a ideia?

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by marcosyoggy** [comment]
....então na intenção de mudar um estilo, eu apenas alterei a classe "popup-Message" para "display: block". Grato pela atenção.

![image](https://user-images.githubusercontent.com/44072541/129035595-229dcf07-f716-459e-b844-7ac2eef18034.png)

**Comment by Roger-Melo** [comment]
Isso mesmo =)

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
