### ISSUE TITLE
Etapa 05, Event Bubbling & Event Delegation: Aula 04-02

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#1405]
Boa tarde, professor Roger. Eu assisti a aula sobre Event bubbling várias vezes e procurei por uma duvida parecida com a minha 
e não achei, por essa razão abri esse issue.

Bom, pelo o que eu entendi, caso um evento de um elemento filho seja realizado, esse evento será propagado para o elemento 
pai e o JavaScript irá "verificar" se o elemento pai possui um evento associado e então, se o elemento pai tiver um evento 
associado, a função de callback desse elemento vai ser disparada e assim por diante. Minha dúvida é a seguinte, o evento 
do elemento pai deve ser o mesmo evento do elemento filho? Pergunto isso pois, com o intuito de consolidar o conhecimento, 
costumo testar algumas possibilidades e nesses testes não obtive o resultado esperado(função de callback do elemento pai ser 
disparada se um elemento filho tiver um evento realizado). Usei o evento 'click' na *ul* e o evento 'mouseenter' nas *lis*. Códigos
abaixo.

* HTML

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Event Bubbling</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <ul>
        <li>Comprar frango</li>
        <li>Ler livros</li>
        <li>Tocar violão</li>
        <li>Pagar as contas</li>
    </ul>

    <script src="/script.js"></script>
</body>
</html>
```

* CSS

```css
ul{
    background-color: honeydew;
}

li{
    background-color: gray;
    margin: 10px;
    padding: 5px;
}
```
* JavaScript

```js

const lis = document.querySelectorAll('li');
const ul = document.querySelector('ul');


ul.addEventListener('click',()=>{
    console.log('Houve um click na ul');
})

lis.forEach(li =>{
    li.addEventListener('mouseenter',event => {
        const clickedElement = event.target;
        clickedElement.style.backgroundColor = 'red';
    })
});

```
* Execução: 

* 1 Mouse fora
![Imagem1](https://user-images.githubusercontent.com/39880705/128391835-ad44f3e9-4815-442c-80c9-6f11871c8947.png)

* 2 Mouse "entra no espaço de uma  *li*
![Imagem2](https://user-images.githubusercontent.com/39880705/128391857-09c812fd-6f07-4d75-94d1-7791b329dd98.png)

* 3 Mouse "entra no espaço de outra  *li*
![Imagem3](https://user-images.githubusercontent.com/39880705/128391890-54940b19-1c9c-419d-b6b2-147b55fc3bf4.png)

* 4 Apenas quando cliquei(evento 'click' do elemento *ul*) a função de callback foi disparada.
![Imagem4](https://user-images.githubusercontent.com/39880705/128391909-2baa11c6-7330-438d-b56b-7367863949e5.png)

A função de callback associada ao evento da *ul* não deveria ter sido disparada "automaticamente" no momento em que a primeira *li* teve seu evento realizado? 
	

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais.

> ### ...o evento do elemento pai deve ser o mesmo evento do elemento filho?

Isso mesmo. Ambos elementos precisam ter o mesmo tipo de evento (um `click`, por exemplo). Se vc substituir o `mouseenter` das `li`s pelo `click`, verá que ao clicar na li, o callback do listener de evento da li e da ul são executados.

Acho que isso não ficou tão claro na aula, então já anotei aqui para inserir uma observação nela em breve.

Respondi a dúvida?

**Comment by ThiagoDeMorais** [comment]
Respondeu sim, muito obrigado!
