### ISSUE TITLE
Resumo da Aula O método sort - Aula 02-02 da etapa 08

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1415]
O método `sort()` ordena elementos de um *array*, alterando o *array* original, e pode receber um argumento, que é opcional. Vamos ver um exemplo onde temos um *array* de nomes, e o objetivo é ordenar alfabeticamente seus elementos. Neste caso não é necessário passar nenhum argumento.

```jsx
const names = ['Carlos', 'Ana', 'Beatriz'];

names.sort();

console.log(names);

// ['Ana', 'Beatriz', 'Carlos'];
```

Podemos também ordenar um *array* de números ou de objetos, porém para isso precisamos passar um argumento para o método `sort()`, que é uma função. Essa função recebe dois argumentos, onde o primeiro é o um item do *array* e o segundo é o item após este primeiro dentro do *array*. O que é feito é uma comparação entre estes dois itens, onde se retornarmos -1 no resultado, o primeiro item virá antes na nova ordem do *array*. Caso retornemos 0, a ordem não é alterada, e se for retornado 1, o segundo item virá antes na nova ordem do *array*. Vamos ver na prática como ficaria uma forma de fazer essa verificação. E logo em seguida veremos uma forma mais enxuta de fazer essa verificação.

```jsx
const scores = [75, 35, 80, 55, 60, 95, 100, 15];

scores.sort((score1, score2) => {
	if (score1 > score2) return -1;
	else if (score1 < score2) return 1;
	return 0;
});

console.log(score);

// [100, 95, 80, 75, 60, 55, 35, 15];
```

Uma maneira mais simples de escrever esta função seria fazer uma subtração do primeiro item pelo segundo caso eu queira uma ordem crescente, ou ainda subtrair o segundo item pelo primeiro caso eu queira o *array* na ordem decrescente. Caso o resultado seja positivo, o número a esquerda do sinal de subtração virá antes no *array*, caso seja negativo, o número a direita do sinal de subtração virá antes, e caso retorne 0, nada será alterado na ordem destes dois elementos. Vamos ver na prática como ficaria, utilizando o mesmo exemplo acima.

```jsx
const scores = [75, 35, 80, 55, 60, 95, 100, 15];

scores.sort((score1, score2) => score2 - score1);

console.log(score);

// [100, 95, 80, 75, 60, 55, 35, 15];
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas. Rumo à fluência 🔥
