### ISSUE TITLE
Etapa 14, nome do vídeo: Mais sobre o Spread Operator

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1416]
### Olá @Roger-Melo .

Tenho uma observação, relacionado ao `Spread Operator`, pois ate o momento do curso onde estou, aprendi sobre o `Spread Operator`, que pemite transformar um array em diversos parâmetros para uma função. 

> **Spread Operator**

```javascript

// using SPREAD to sum all numbers of the numbers array

let numbers = [5, 4, 11]

const sum = (num1, num2, num3) => (num1 + num2 + num3)
const resultSum = sum(...numbers)

console.log(resultSum) // 20

// using SPREAD to add items in a new array

let array1 = ['eggs', 'rice']
let array2 = ['oranges', 'bread', 'butter']
let newArray = [...array1, ...array2]

console.log(newArray) // ['eggs', 'rice', 'oranges', 'bread', 'butter']

```

Recentemente eu fiz uma pesquisa relacionando ao `Spread`, e encontrei um artigo que falava sobre `Rest Operator`, que faz quase a mesma coisa que o `Spread` e que será mostrada logo abaixo. 

---

### Rest Operator

No artigo onde eu li sobre o `rest` eu pude observar que ele é usado/passado como argumento de funções. 

**`📖 Rest nos permite transformar um número indeterminado de parâmetros em um array.`**

> **Rest Operator**

```javascript 

const restOperator = (a, b, ...args) => (a, b, args)
const newArray = restOperator(1, 2, 3, 4, 5, 6)

console.log(newArray) // [3, 4, 5, 6]

```

Na função acima os 2 primeiros números ficaram de fora do array, pois o `rest` apenas envolve no array os argumentos passados após o `...args`.

```javascript 

const insertNumbersInArray = (...args) => args
const newArray = insertNumbersInArray(1, 2, 3, 4, 5, 6)

console.log(newArray) // [1, 2, 3, 4, 5, 6]
```

Já na função acima, todos os numeros passados foram inseridos dentro do array.

> ***Então o `Rest Operator` que é usado dentro de funções como argumento, o mesmo tem sempre que está envolvido em parênteses `(...args)`.***

```javascript

const restOperator = (...args) => {
// function body
}

```

>***Pois se o mesmo não estive envolvido em parênteses,  um `Uncaught SyntaxError: Unexpected token '...'` será gerado.***

```javascript

const restOperator = ...args => {
// function body
}
```

Enfim creio eu que o `Spread` e o `Rest` funcionam dessa forma.

>**Existe outra(s) forma(s) de trabalhar com `Spread` e `Rest`, ou será sempre nessa regra?**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros.

> #### ...encontrei um artigo que falava sobre `Rest Operator`, que faz quase a mesma coisa que o `Spread`

Na real, mesmo que rest parameters e spread operator usem a mesma sintaxe (`...`), o caso de uso deles é oposto. 

> #### ***Então o `Rest Operator` que é usado dentro de funções como argumento, o mesmo tem sempre que está envolvido em parênteses `(...args)`.***

Rest parameters é apresentado na aula 02-01 da etapa 15. Lá vc vai entender, com detalhes, os casos de uso dele e também vai ver as diferenças entre ele e spread. Se depois de ver essa aula ainda restarem dúvidas, pode abrir uma issue que te ajudo, combinado? =)

**Comment by Roger-Melo** [comment]
@Mateus20Barros vou fechar a issue mas no que precisar, é só abrir uma nova =)
