### ISSUE TITLE
Resumo da Aula Encadeando métodos - Aula 02-03 da etapa 08

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1419]
Podemos encadear métodos de *array* sem que seja necessário criar mais constantes para invocar cada método. Esse encadeamento poderá ser feito desde que o retorno de cada método invocado seja um *array* (se quisermos encadear métodos de *string*, o retorno de cada um também deverá ser uma *string*). Por exemplo, vamos imaginar que temos um *array* de objetos, em que cada objeto é um livro com nome e valor, e que queremos a partir deste, criar um novo *array* com livros no valor acima de 20 reais, e em seguida queremos retornar uma *string* para cada elemento contendo o nome e o valor do livro, informando que o livro entrou em promoção. Então nesse caso teremos o uso do `filter()` seguido do `map()`, onde no `filter()` retornaremos um novo *array* com apenas alguns elementos do *array* original, baseado em uma condição, e no `map()` retornaremos um novo *array* com a mesma quantidade de elementos mas com alguma alteração em cada um, baseado no retorno do `filter()`. Vamos ver na prática:

```jsx
const books = [
  { name: "Código Limpo", price: 30 },
  { name: "O milagre da manhã", price: 5 },
  { name: "Alice no País das Maravilhas", price: 10 },
  { name: "Quem Pensa Enriquece", price: 50 },
  { name: "O livro da ciência", price: 40 },
];

const booksOnSale = books
	.filter(({ price }) => price > 20)
	.map(({ name, price }) => `O preço do livro ${name} caiu para R$${price}`);

console.log(booksOnSale);

// 0: "O preço do livro Código Limpo caiu para R$30"
// 1: "O preço do livro Quem Pensa Enriquece caiu para R$50"
// 2: "O preço do livro O livro da ciência caiu para R$40"
```

E por convenção, quando temos encadeamento de métodos, cada invocação fica em uma linha. E caso ultrapasse 80 caracteres, podemos quebrar um trecho do método para a próxima linha. Lembrando que são apenas convenções, que nada disso fará a aplicação quebrar, é apenas uma melhor legibilidade do código.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Rumo à fluência! 🔥
