### ISSUE TITLE
Aplicação: [To-do List]

### ISSUE THREAD

**Issue by edmaaralencar** [roger-melo-treinamentos/curso-de-js-roger-melo#1426]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edmaaralencar/to-do-list

### Maiores dificuldades durante a implementação

Recriação da funcionalidade removeTodo sem o uso do parentElement e entendimento da funcionalidade de filtrar todos (fiquei um pouco confuso).

### Menores dificuldades durante a implementação

Refactoring, adição de todos e forma que você ensinou de remover todos (tinha usado ela antes de ver seu video)

**Comment by Roger-Melo** [comment]
Olá @edmaaralencar.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @edmaaralencar!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Maiores dificuldades: Recriação da funcionalidade removeTodo sem o uso do parentElement e entendimento da funcionalidade de filtrar todos (fiquei um pouco confuso).

Mas conseguiu fazer! O mais importante no primeiro momento vc já fez, que é fazer funcionar. Se tiver com dificuldades de entender alguma coisa, não hesite em abrir uma issue. A vantagem de abrir issues no momento em que dúvidas surgem é que as dúvidas endem a ser mais específicas =)

Se ainda estiver com alguma dúvida nessa funcionalidade, pode comentar ela ali em baixo que te ajudo, ok?

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Boas decisões

No geral, os nomes que vc deu para as variáveis e funções deixaram bem claro o que elas armazenam/executam. Isso mostra que vc ficou atento ao feedback que recebeu na análise passada =)

## Organização de código

### console.log esquecidos

O `console.log` é útil apenas no momento em que você está desenvolvendo. Sei que vc deve ter usado para visualizar algum valor e esquecido, mas sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

### Nomes de variáveis e funções

Acredito que se `index` for nomeada como `todoId`, fica mais intuitivo supor o que a let armazena. 

Nas aulas seguintes vc verá uma outra forma de identificar um todo e, nas aulas da etapa 15, uma forma mais aleatória de gerar esse id.

### Refatoração

Como `addTodo` e `insertTodoIntoDOM` fazem ações muito parecidas, vc vai ver que nas aulas seguintes, eu preferi deixar essa ação compactada em uma função:

```javascript
const addTodo = inputValue => {
  if (inputValue.length) {
    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
      </li>
    `
  }
}
```

A medida em que o código cresce, uma possível alternativa seria separar a geração do template HTML. 

Observe que agora, a distinção de responsabilidades de cada função fica mais clara, por que cada uma tem apenas uma única responsabilidade:

```javascript
const getTodoMarkup = inputValue => `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
  </li>
`

const addTodo = inputValue => {
  if (inputValue.length) {
    todosContainer.innerHTML += getTodoMarkup(inputValue)
  }
}
```

Essa é uma forma de refatorar essa ação =)

## Lógica

### `event`

Na função `insertTodoIntoDOM`, o `event` global está sendo usado. 

Mesmo que tenha funcionado, o ideal é que o `event` seja passado como argumento da invocação da função. Isso por que o [event global](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) foi descontinuado. O VSCode geralmente insere um traço no meio de propriedades e métodos que foram descontinuados/depreciados.

Quando você insere o event como parâmetro de um callback de listener de evento, ao invés de usar o event global, você está usando o [Event interface](https://developer.mozilla.org/en-US/docs/Web/API/Event) =)

### `if`s

Quando possível, evite aninhamento de `if`s, pois eles deixam o código mais complexo de ler e testar. Na etapa 15, vc verá que eu vou mostrar em detalhes uma técnica chamada `return early`. Mas apenas para vc ter uma ideia, no código abaixo, nada acontece se o elemento clicado não tem a class CSS e apenas um `if` é usado:

```javascript
const removeTodo = event => {
  const clickedElement = event.target
  const clickedElementHasDeleteClass = clickedElement.classList.contains('delete')

  if (!clickedElementHasDeleteClass) {
    return
  }
  
  const todosItems = document.querySelectorAll('li')

  todosItems.forEach(todo => {
    const attributeOfLi = todo.dataset.number
    const attributeOfClickedElement = clickedElement.dataset.set

    if (attributeOfLi === attributeOfClickedElement) {
      todo.remove()
    }
  })
}
```

Há formas de reduzir bastante o código dessa função. Mas isso vc vai ver nas refatorações das aulas seguintes xD

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by edmaaralencar** [comment]
Fala Roger, as observações fizeram muito sentido, e já fiz as devidas modificações, muito obrigodo!

**Comment by Roger-Melo** [comment]
Excelente @edmaaralencar. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
