### ISSUE TITLE
Resumo da Aula Null 03-03 / Booleans 04-02 / Comparações 04-03 /Conversões 04-04 da etapa 01

### ISSUE THREAD

**Issue by djailtim** [roger-melo-treinamentos/curso-de-js-roger-melo#143]
![IMG_3057](https://user-images.githubusercontent.com/64450426/107301700-60deaa80-6a52-11eb-9898-082c177f0f59.jpg)
![IMG_3058](https://user-images.githubusercontent.com/64450426/107301706-63d99b00-6a52-11eb-908c-15e135298991.jpg)
![IMG_3059](https://user-images.githubusercontent.com/64450426/107301711-65a35e80-6a52-11eb-8d9a-bc2d5a25d4db.jpg)
![IMG_3060](https://user-images.githubusercontent.com/64450426/107301715-676d2200-6a52-11eb-8149-2127eacf36ec.jpg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa Ailton!

Nas próximas, veja se consegue enquadrar a folha do caderno na foto. Fica mais legal para ler =)

Rumo à fluência! 🚀

**Comment by djailtim** [comment]
Beleza professor!
