### ISSUE TITLE
Etapa 1, nome do vídeo: Aula inaugural

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1435]
Como faço para deixar as cores e a font do meu VSCode de acordo com o seu?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Nas primeiras aulas, o tema era setado através de uma extensão chamada One Dark+ (Sublime Babel) com background em #15202B. Porém, eu acho que essa extensão foi descontinuada.

Hoje, uso o Dark+ (default dark), que é um tema padrão do VSCode =)

Outras extensões que uso são:

- Bracket Pair Colorizer
- Colorize
- Live Server
- VSCode Great Icons

---

O guia completo para configurar o VSCode é a [documentação](https://code.visualstudio.com/docs). Mas, eu recomendo não investir muito tempo em configurá-lo. Isso pode tomar muito do seu tempo =)

**Comment by dracoalv** [comment]
encontrei uma versão recorrente, se não for igual é semelhante, obrigado! pode fechar a issue 😁

**Comment by Roger-Melo** [comment]
Show, no que precisar, é só abrir uma nova issue =)

**Comment by Roger-Melo** [comment]
Oi @dracoalv. 

Sim, vc pode comentar em issues fechadas, mas ao fazer isso, prefira reabrí-las e me marcar: @Roger-Melo =)

> Usei por algumas horas o dark one e acabou me cansando visualmente

O One Dark+ (Sublime Babel)? Eu não tenho mais a extensão que instalava ele e acho que ela foi descontinuada, então não tenho como dar essa informação. 

Mas eu recomendo fortemente que você não se distraia com configurações. Escolha (rápido) qualquer tema que te agrade e foque no que é ensinado nas aulas. Vc verá que, no longo prazo, ter esse tipo de foco vai acelerar sua chegada na fluência, ok? =)

**Comment by dracoalv** [comment]
muito obrigado pela informação, encontrei um e meti as caras no curso!
