### ISSUE TITLE
Etapa 01, nome do vídeo: 05

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1437]
Boa-noite ROGER

Percebi que posso adicionar o JS em qualquer parte do arquivo HTML, seja incorporando, ou à partir de um arquivo externo, mas fiquei com uma dúvida. Tenho o costume de testar meus códigos em vários navegadores para ver como cada um apresenta o resultado e, como o Roger mensionou possíveis problemas de carregamento quando JS está na TAG head, testei o seguinte:

1. Coloque o JS dentro da **TAG body**, abaixo do **Título H1**, como mostra o código abaixo:

```
<!DOCTYPE html>
<html lang="pt">
<head>
	<title>Aula 1</title>
</head>
<body>
	<h1>Learning JavaScript</h1>
	<script>
		alert("Hello world!")
	</script>
</body>
</html>
```

Quando abri com **Google Chrome e com MS Edge**, eles apresentaram primeiro a mensagem e só depois o Título. Mas o **FireFox** apresetou primeiro o Título e depois a mensagem.

Quando mudei, colocando o JS dentro da **TAG Head**, não houve mudanças com **Google Chrome e nem com MS Edge**, mas o **FireFox,** desta vez apresentou a mensagem e só depois o Título.

- Porque isso acontece?
- Terá isto alguma implicação positiva ou negativa quando em Projectos reais?
- O que acontece se eu decido colocar o JS **fora da head e fora de qual que TAG**, assim por exemplo:

```
<!DOCTYPE html>
<html lang="pt">
<head>
	<title>Aula 1</title>
</head>
<body>
	<h1>Learning JavaScript</h1>
</body>
</html>

<script>
	alert("Hello world!")
</script>
```
**Eu testei, vi que funciona, mas desconfiei que não seja o bom fazer isto kkkk 😅😅**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim!

> Tenho o costume de testar meus códigos em vários navegadores para ver como cada um apresenta o resultado

Cada navegador tem um motor próprio para executar JS, ou seja, não existe um motor padrão. Por isso, é normal que aconteçam essas pequenas diferenças.

Porém, nesse momento, eu recomendo fortemente que você não se distraia com isso. 

Teste seu código apenas com o Chrome e, com a versão mais atualizada, se possível, como o recomendado.

> Terá isto alguma implicação positiva ou negativa quando em Projectos reais?

Aplicações utilizam ferramentas que compilam código js moderno para navegadores antigos, se necessário.

Isso será visto etapas mais avançadas do treinamento.

Tente focar apenas no que é passado nas aulas nesse momento e vc verá que, no longo prazo, ter esse foco vai acelerar sua chegada na fluência, ok? =)

**Comment by gerafim** [comment]
Obrigado Roger! Recomendação acolhida! =)

**Comment by Roger-Melo** [comment]
Legal @gerafim. Já que ficou mais claro, vou fechar a issue, mas no que precisar, é só abrir uma nova =)
