### ISSUE TITLE
Resumo da Aula 02 da etapa 03

### ISSUE THREAD

**Issue by daniel-lopes-98435** [roger-melo-treinamentos/curso-de-js-roger-melo#1438]
Variáveis do tipo string, armazenam valores que permitem algumas ações:
> Concatenação, onde podemos agrupar uma ou mais string
Selecionar um item da string pelo seu índice, variável[0], irá apresentar o primeiro caracter de uma variável
Conseguimos saber qual o tamanho de uma variável do tipo string utilizando a propriedade length.
Podemos transforma uma variável do tipo string utilizando os métodos permitidos, exemplo:
> Para transformar um string em maiúscula, utilizamos variável.toUpperCase()
> Para transformar um string em minúscula, utilizamos variável.toLowerCase()
Os dois métodos utilizados acima não alteram a variável original, apenas permitem visualizar a mesma de outra forma

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @daniel-lopes-98435. Rumo à fluência! 🔥
