### ISSUE TITLE
Resumo da Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by lathne** [roger-melo-treinamentos/curso-de-js-roger-melo#1445]
### MÉTODOS DE STRINGS 

Alguns métodos modificam o valor original no qual eles estão executando a ação e outros não. Os métodos `toLowerCase()`, `toUpperCase() `, `slice()` e  `replace()`  não modificam.

`indexOf()` busca o índex do caracter. Ele requer como  _argumento_  o caracter que desejo saber a posição.

`lastIndexOf()` busca a ultima ocorrencia do caractere que você passar por argumento.

`slice()` busca partes da string. Requer dois argumentos. Primeiro argumento é um numero que representa o index do caracter a string vai ser partida. O segundo argumento é um numero que define onde a string deve ser cortada.

`replace()` substitui um caracter de uma string por outro. Requer dois argumentos. O primeiro é a string que a gente quer substituir. Segundo é o caracter que vai substituir. 

##

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @lathne. Rumo à fluência! 🔥

**Comment by lathne** [comment]
Ola Roger. Obrigado pela dedicação e rumo à fluência!!
