### ISSUE TITLE
Resumo da Aula Variáveis e escopo de bloco - Aula 02-02 da etapa 04

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#1449]
Escopo é a área em que o valor de uma variável/a variável está disponível para ser usada.

## Escopo Global

A variável declarada na raiz tem um escopo global, ou seja, pode ser acessada em qualquer parte do código.
No exemplo abaixo, os dois console.log irão conseguir acessar a variável age:

```js
let age = 31;

if (true) {
  console.log(age); // 31
}

console.log(age); // 31
```

---

## Escopo Local

A variável declarada dentro de um bloco de código delimitado por chaves { ... } só poderá ser acessada dentro desse bloco de código:

```js
if (true) {
  let age = 30;
  console.log(age); // 30
}

console.log(age); // Não irá apresentar a variável
```

---

## Variáveis com mesmo nomes em escopos diferentes

**É possível criar uma variável com o mesmo nome, desde que ela não seja criada no mesmo escopo. Dessa forma, teremos 2 variáveis com o mesmo nome, mas que armazenam valores diferentes e terão escopos diferentes.**

No exemplo abaixo, a variável criada dentro do if só poderá ser acessada dentro do if, pois ela tem um escopo local e a variável declarada fora do if poderá ser acessada em qualquer lugar com excessão desse if  que já possui uma variável age declarada.

```js
let age = 31;

if (true) {
  let age = 41;
  console.log(age); // 41
}

console.log(age); // 31
```

Se tivermos if aninhados, 1 variável declarada no escopo global e outra com o mesmo nome declarada no escopo local no 1º if, se tentarmos acessar essa variável no 2º if (2º if está dentro do 1º if), a variável acessada será a que foi declarada mais próxima em relação aos níveis , que neste caso é a que está no 1º if.

```js
let age = 31;

if (true) {
  let age = 41;
  
  if (true) {
    console.log(age); // 41
  }
}
```

No exemplo acima ele pegou o age que armazena 41.

No exemplo abaixo o código continua seguindo a mesma regra. A variável acessada é a mais próxima em relação aos níveis.

```js
let age = 31;

if (true) {
  let age = 41;
  
  if (true) {
    let age = 51;
    console.log(age); // 51
  }
}
```

---

## Importante

Todos esses conceitos mostrados acima se aplicam ao let e const da mesma forma, mas não ao var.

O var, diferente do let e const, ignora o escopo de bloco, ou seja, mesmo ele sendo definido/declarado em um escopo de bloco, ele "vaza" para o escopo global.

```js
if (true) {
  var age = 31;
}

console.log(age); // 31
```

No exemplo acima, se a variável age tivesse sido declarada com let ou const, a variável age não estaria disponível no escopo global.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer. Rumo à fluência! 🔥
