### ISSUE TITLE
Resumo da Aula Correção dos exercícios da Aula 02 da etapa 06

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#145]
## Element.insertAdjacentElement('position', element)
Este método é responsável por inserir um elemento no DOM, consequentemente na página. Além de inserir o elemento ele também é responsável por definir sua posição, mas levando em consideração o elemento na qual este método foi encadeado.

**Argumentos**

1. Pode receber como primeiro argumento algum dos seguintes valores:
- beforebegin
- afterbegin
- beforeend
- afterend

Veja um exemplo mais prático:

```
<!-- **beforebegin** -->
<p>
  <!-- **afterbegin** -->
  foo
  <!-- **beforeend** -->
</p>
<!-- **afterend** -->
```

2. A referência do elemento que será inserido.

**Retorno**

O valor retornado por este método será a referência do elemento que foi inserido na página. Porém, caso a inserção falhe o valor retornado será null.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @sou-gabriel. Ater na veia, rumo à fluência! 👊
