### ISSUE TITLE
Ficar muito tempo sem estudar, voltar e não saber o que fazer

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#1450]
Olá professor, boa tarde.
Venho abrir essa issue, infelizmente, como um depoimento pessoal buscando ajuda acerca de como proceder com o CJRM após uma série de acontecimentos que fizeram eu parar (em partes e depois totalmente) de estudar JavaScript e front-end em geral. O problema agora é voltar a estudar mas não saber como fazer isso.

Fiz a inscrição no CJRM em outubro de 2020. Fiz o curso com garra e dedicação até a etapa 11, de JS Assíncrono, e consegui compreender bem todo o conceito na linguagem até esse ponto. Infelizmente, por alguns problemas pessoais e outras aventuras da vida (consegui um estágio como analista de negócio na faculdade!), parei completamente os estudos de front-end em abril deste ano. Estou conseguindo voltar ao pique que tinha somente há algumas semanas atrás mas estou numa tremenda inércia que está me fazendo mal até psicologicamente: O que vou fazer agora? Esse é meu problema.

Voltar à etapa 0 e rever todo o curso novamente? Refazer todas as listas de atividades? Refazer todos os projetos? Visualizar apenas as anotações e dar continuidade de onde parei? Nessa indecisão e ansiedade, não estou conseguindo me movimentar como antes e isso tem pesado bastante na cabeça.

Não encontrei outra alternativa senão abrir uma issue e tentar falar com você sobre esse assunto. Essa não é a primeira vez que acontece na minha caminhada e acredito que também seja um problema de outras pessoas em algum momento. Espero ter sido claro e gostaria muito de seu feedback de experiência para sair disso e prosperar. 

Obrigado, professor.
@Roger-Melo

**Comment by crjstjanojose** [comment]
Tenho o mesmo problema .

Em ter., 10 de ago. de 2021 às 11:34, Willian Andrade <
***@***.***> escreveu:

**Comment by Roger-Melo** [comment]
Olá @crjstjanojose e @Will-Andrade. 

Li a issue e, assim que eu chegar em casa, respondo com calma =)

**Comment by Roger-Melo** [comment]
Tecnicamente, o que eu recomendo fazer nesse caso é: 

- assista a [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928) novamente;
- faça uma revisão [raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x) à partir da primeira bateria de exercícios. 

Sem assistir às aulas, faça a primeira bateria de exercícios. A partir dessa primeira bateria, se acontecer de vc empacar em algum exercício dessa bateria ou das posteriores, é à partir dali que vc começará a assistir as aulas novamente.

Regra de ouro: rolou dúvida, no momento em que a dúvida surgiu, não hesite em abrir uma issue. Isso vai fazer com que a dúvida seja mais específica e, portanto, mais fácil de ser sanada.

Se a issue não for aberta no momento que a dúvida surgiu, essa dúvida vai escalar e se ela escalar, a issue no futuro que vc abrirá irá ser menos específica e, por consequência, será mais difícil ser ajudado com precisão.

Pelo que vi em seu histórico, você abriu apenas uma issue pedindo ajuda e uma outra para a análise do Quiz. É pouco. Posso estar enganado, mas acho improvável que você teve apenas uma única dúvida durante esse tempo.

Essa é a parte técnica.

---

Todos nós temos um recurso limitado e distribuído igualmente: tempo.

Independente se alguém tem mais dinheiro ou menos, mais preparação ou menos, mais família ou menos... todo mundo tem apenas 24h.

Por isso, quando alguém diz que não estudou por que não tinha tempo, na verdade o que eu entendo é que essa pessoa não priorizou os estudos. E não há nada de certo ou errado nisso, não estou aqui para julgar. 

Mas se o estágio como Analista de Negócios consumiu mais do seu tempo, é por que isso foi uma prioridade maior. Só vc sabe os motivos de ter tomado essa decisão, e tá tudo bem.

Porém, o mercado de Desenvolvimento Front-end é abundante e eu, sinceramente, não conheço outro programa tão estruturado para acelerar sua chegada na fluência. 

O que é prioridade para você vai tomar mais do seu tempo, e isso é uma decisão sua. Você escolhe o que faz com as mesmas 24h que todo mundo tem. 

Se ficou alguma dúvida, é só dar o toque =)

@crjstjanojose, @Will-Andrade.

**Comment by Will-Andrade** [comment]
Olá professor, obrigado pela resposta.
Realmente, tudo isso faz sentido pra mim. Eu de fato abri poucas issues e creio que ter sua expertise como guia nesses momentos teria sido mais benéfico pra mim no longo prazo. Sobre a parte de priorização, exatamente. Eu decidi priorizar os trabalhos no estágio e faculdade para que não deixassem minha vida pior... Agora que estou um pouco mais livre, estou voltando a estudar e focar no que realmente eu quero me especializar, que é o desenvolvimento web. 

Estarei fazendo o processo citado com foco nessa revisão raio-x... sinto que vá me ajudar e em poucos dias terei voltado ao meu gás anterior. Muito obrigado por suas palavras. Não há um método melhor e mais ativo para aprender JS do que o do senhor! Se qualquer outra dúvida me ocorrer, estarei entrando em contato.

Valeu, @Roger-Melo!

**Comment by Roger-Melo** [comment]
Excelente @Will-Andrade. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
