### ISSUE TITLE
Resumo da Aula 1-6 da etapa 1 

### ISSUE THREAD

**Issue by kaiansamuel** [roger-melo-treinamentos/curso-de-js-roger-melo#146]
Javascript o início

Para começarmos precisamos criar um “script” que será linkado pelo Html, como no exemplo de criar um “style.css”. Na parte final do “body” devemos inserir o script: “<script src=”pasta de destino”></script>. É de boas práticas que o script seja introduzido no fim do body, para que o Javascript seja carregado por último.

Variáveis

Variáveis são contêineres que são armazenados valores, sejam eles números, ‘strings’, valores booleanos e até arrays, isso se dá porque o Javascript é uma linguagem dinâmica.
Para criarmos uma variável é necessário usarmos a palavra reservada “var”.
Exemplo:
var num = 5
a variável com o nome “num” recebeu o número 5, logo: 
console.log(num)
//5
Variáveis podem ser criadas também pelas palavras reservadas “let” e “const”, a grosso modo as palavras let e var tem diferenças de escopo (o que vamos estudar mais à frente)
e “const” faz com que os valores inseridos na “const” não possam ser mudados. Para ficar bem claro a palavra “var” vem de “variável” e “const” de “constante”.
Criando a variável, você pode chamá - la pelo seu nome.
Exemplo: 
let myName = ‘Kaian’
Chamando-a:
myName
E depois de chamada podemos mudar o seu valor.
Exemplo:
myName = ‘Samuel’
console.log(myName)
//Samuel

Tipos de Dados em JavaScript

Os tipos de dados são definidos e são: Strings, Numbers, Booleans, Arrays e Objects

Comentários

Os comentários são feitos através do uso de “//” no começo da expressão ou usando o “/* */” no fim das expressões.

Operadores

Os operadores usados para realizar as operações são: “+” - Soma dois números “5+5”;
ou soma duas strings: “Hello” + “world” .
Os operadores simples seguem respectivamente e são eles: ‘’-’’ - Subtração,
“*” - Multiplicação e “/” Divisão. O operador “=” confere um valor à uma variável como já vimos.
O operador “===” Confere igualdade nas comparações e retorna um valor booleano (true ou false).
Exemplo:
let num = 6
Console.log(num === 6)
//true
O operador “!==” Usa a mesma lógica anteriormente explicada, mas ao contrário, então nesse caso “!==” significa a pergunta se é diferente.
Exemplo:
console.log(num! == 6)
//true
console.log(num !== 5)
//false

@Roger-Melo

**Comment by Roger-Melo** [comment]
Ater na veia @kaiansamuel. Rumo à fluência! 👊
