### ISSUE TITLE
Resumo da Aula 01 da etapa 01 a 06

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#1464]
**Local Host:** Meu computador vai ser meu próprio servidor utilizando Live Server.
CTRL+SHIF+P Busca Geral no VS Code.
CTRL+B Aba Lateral Vs Code.
Let:  Variavel utilizada quando os valores podem ser reatribuidos.
Const: Constante para valores fixos.
Var: Não é mais utilizada
Sinal de = lê se: variavel RECEBE valor.
SRC é um atributo
console.log(): Exibe leitura do codigo no dev.
/* Inicia comentario */ finaliza comentario
GIT sistema de versionamento de arquivos. Controle de versão. Registra mudanças no codigo fonte.
'''js : Com essa formatação os codigos ficam destacados na Issue.

Exercicios feitos e refeitos.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @shazenn!

Preciso que me diga seu nome e sobrenome. Assim te identifico na lista dos alunos e posso marcar a issue com a label da sua turma =)

**Comment by shazenn** [comment]
Humberto Bispo

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 10 de ago de 2021 10:57 PM, Roger Melo escreveu:
