### ISSUE TITLE
Aplicação: Weather-Application

### ISSUE THREAD

**Issue by homeromeirelesjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#1468]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/homeromeirelesjunior/weather-app

### Maiores dificuldades durante a implementação

Me sinto mais preparado de uma forma geral, sempre bate uma dúvida aqui ou ali, mas já tinha o "esqueleto" de como resolver a situação. Estou mais habituado a pesquisar no MDN ou semelhantes por respostas do que buscar a resposta diretamente nas aulas. 

A refatoração ainda é um tabu, acho que isso vai melhorando com a experiência, veremos.

A parte de estilização é sempre um problema, mas isso não cabe aqui e nem é o foco do curso.

### Menores dificuldades durante a implementação

Manipular o DOM, configurar os requests. Como eu disse, está tudo muito claro, dúvidas e erros surgem o tempo todo, mas consigo resolve-los sozinhos, sem recorrer as aulas.

**Comment by Roger-Melo** [comment]
Olá @homeromeirelesjunior.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @homeromeirelesjunior!

Parabéns pelo esforço em construir mais uma aplicação do treinamento =)

> ## Estou mais habituado a pesquisar no MDN ou semelhantes por respostas do que buscar a resposta diretamente nas aulas.

Isso é ótimo! Quanto mais vc pratica, a tendência é essa mesmo. Menos aula e mais documentação =D

> ## A refatoração ainda é um tabu, acho que isso vai melhorando com a experiência, veremos.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

> ## A parte de estilização é sempre um problema, mas isso não cabe aqui e nem é o foco do curso.

Sim, mas durante o treinamento, escolha o que ficar mais confortável pra vc, seja alguma lib de CSS ou estilo do zero que vc fez.

Não sei se vc está buscando e se tem dificuldade de base ou alguma específica, mas existem bons materiais para os dois casos. 

[Esse site](https://css-tricks.com/guides/) é o mais completo no assunto que conheço. Se quiser algo mais interativo, [aqui](https://www.codecademy.com/search?query=css) é um bom lugar.

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Lógica

Mesmo que a let `imgTime` sofra uma reatribuição no objeto que ela armazena, ela não precisa ser uma `let`. A vantagem de declará-la como `const` é que isso impede que o valor que ela armazena seja modificado =)

## Organização de código

### Linhas em branco

Geralmente, é uma convenção que a primeira linha do código seja preenchida. Isso não afeta em nada o funcionamento do código, é apenas uma convenção.

### Nomes de variáveis e funções

Acredito que se `handleHTML` for nomeada como `showCityWeatherInfo`, a ação que ela está fazendo fica mais específica no nome.

### Refatoração

Como a  `isDayOrNight` seta uma imagem do tempo, eu a nomearia como `setTimeImg`. 

Observe também que o `if/else` pode ser substituído por um ternário que apenas retorna um valor para a `src`. Isso deixa o código mais conciso:

```javascript
// antes
const isDayOrNight = IsDayTime => {
  if (IsDayTime) {
    imgTime.src = './src/day.svg'
  } else {
    imgTime.src = './src/night.svg'
  }
}

// depois
const setTimeImg = IsDayTime => {
  imgTime.src = IsDayTime ? './src/day.svg' : './src/night.svg'
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço Homero. Sua progressão em relação às análises anteriores é perceptível =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Show @homeromeirelesjunior. No que precisar, é só abrir uma nova issue =)
