### ISSUE TITLE
Etapa 01, Null e undefined - Aula 03-03

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1469]
Boa-noite ROGER
Como diferenciar o "Null", da "String vazia"? Testei só por curiosidade o código abaixo:
```
let emptiness=""
console.log(emptiness, emptiness * 3)

```
Retornou ZERO, o que me levou a crer que "String vazia" equivale a ZERO. Mas então e se eu declarar:
```
let nullValue=Null
let emptyValue=0
let emptyString=""
```
Estas 3 variáveis receberam valor igual?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Na aula 04-04 da etapa 01 você aprederá sobre Conversão de tipos.

O JavaScript executa conversões implícitas de tipos de dados, por baixo dos panos antes, executar alguma ação com valores.

No exemplo abaixo,

```javascript
let emptiness = ''

console.log(emptiness, emptiness * 3) // 0
```

o que está acontecendo com a string, de forma implícita, é isso: `Number('')`.

Você não precisa saber agora o que é `Number()`, isso será mostrado na etapa 14.

Se você executar `Number('')`, verá que o retorno será `0`. Isso significa que, em js, quando há uma tentativa de converter string vazia para número, o retorno é `0`.

Então, o que aconteceu na expressão `emptiness * 3` na verdade é isso: `0 * 3`. Como zero multiplicado por 3 é 0, a expressão `emptiness * 3` resulta em 0.

---

No segundo exemplo que você postou, observe que na primeira linha, a expressão `let nullValue = Null` está tentando atribuir uma variável `Null` (com "N" maiúsculo) para a let `nullValue`. Se esse código for executado, `Uncaught ReferenceError: Null is not defined` é exibido no console pois não existe uma variável `Null` (com "N" maiúsculo) declarada em seu código.

Então eu vou supor que na verdade vc quiz usar o `null` embutido na linguagem, assim: `let nullValue = null`.

Se `nullValue * 3` é executado, o que acontece é o mesmo que mencionei acima, com a diferença de que agora, ao invés de uma string vazia, `null` está sendo convertido em number por baixo dos panos:

```javascript
let nullValue = null

console.log(Number(null))  // 0
console.log(nullValue * 3) // 0
```

Sacou a ideia?

**Comment by gerafim** [comment]
Muito Obrigado ROGER
Saquei a ideia. Tem razão, eu quiz atribuir à Variável "nullValue" o valor "null" e não "Null". 
Obrigado pela explicação detalhada.
