### ISSUE TITLE
Etapa 00, Aula Inaugural

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#147]
Olá, Roger.

Acabei de ver na plataforma do curso que foi adicionada uma Aula inaugural em uma etapa 00 que não existia quando comecei o curso. 

Assisti a aula e gostei bastante, porém ficaram algumas dúcidas. Seguem a baixo. 

1 - )  Em relação aos resumos, mesmo antes dessa aula inaugural eu venho fazendo resumos/anotações de cada aula no final dos arquivos de exemplo que escrevo junto com a aula. 

Inclusive fiz um Fork do repositório e a cada aula e exercício feito eu tenho subido essas aulas, separadas por pastas nesse repositório: https://github.com/Hamiltonspjunior/curso-de-js-roger-melo

Devo postar todos os resumos que fiz até aqui? 

2 - ) Em relação a análise das aplicações, eu não recebi o e-mail que você menciona na aula, que explicaria como essa etapa deve ser feita. Pode me reenviar, por favor? 

 3 - ) Durante a revisão raio-x, depois de resolver cada bateria de exercícios devo rever as aulas de correção e caso tenha errado algum exercício devo aplicar os 3 passos que você ensinou para revisar, certo?

Estou chegando na primeira aplicação do treinamento e estou gostando bastante até agora. 

Obrigado mais uma vez. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

> Devo postar todos os resumos que fiz até aqui?

Sim! É só abrir a issue de resumos e mandar bala =D

> 2 - ) Em relação a análise das aplicações, eu não recebi o e-mail que você menciona na aula, que explicaria como essa etapa deve ser feita. Pode me reenviar, por favor? 

Acabei de enviar =)

> 3 - ) Durante a revisão raio-x, depois de resolver cada bateria de exercícios devo rever as aulas de correção e caso tenha errado algum exercício devo aplicar os 3 passos que você ensinou para revisar, certo?

Isso mesmo. Eu falei com mais detalhes sobre a revisão raio-x [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x).

Se alguma coisa que eu disse acima não tiver ficado clara, é só dar o toque =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Tudo certo, Roger. 

Já recebi o e-mail sobre a análise das aplicações e as dúvidas foram sanadas. 

Estou agora no exercício 18, e logo vou iniciar a etapa da aplicação do Quiz. Em breve enviarei a minha para análise.

**Comment by Roger-Melo** [comment]
Legal @Hamiltonspjunior. Vou fechar a issue por agora, mas ao surgirem novas dúvidas, é só abrir uma nova =)
