### ISSUE TITLE
Etapa 8, nome do vídeo: Correção dos exercícios da aula 01 da etapa 08 - Aula 02-01

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#1471]
1ª )  No exercício 21,

```javascript
/*
  04

  - Exiba no console uma lista dos nomes dos jogos do array abaixo;
  - A lista deve ter a formatação exemplificada abaixo do array, considerando 
    inclusive o traço e o espaço antes de cada nome.
  
  Dica: para quebrar linha, você pode usar dentro da string o caractere 
  especial \n.
*/

/*
  - Nome 1
  - Nome 2
  - Nome 3
*/

const cart = [
  { name: 'Dark Souls III', price: 95.03 },
  { name: 'Shadow of the Tomb Raider', price: 101.19 },
  { name: 'Sekiro: Shadows Die Twice', price: 179.99 },
  { name: 'Resident Evil 2', price: 119.90 },
  { name: 'Death Stranding', price: 149.99 }
]
```

Minha resposta(deu certo)

```javascript
const productList = cart.reduce( (accumulator, { name, _ }) => {
  return accumulator += `- ${name} \n`
}, '')

console.log(productList)
/*
- Dark Souls III 
- Shadow of the Tomb Raider 
- Sekiro: Shadows Die Twice 
- Resident Evil 2 
- Death Stranding 
*/
```

Na sua, você colocou :

```javascript
return `${accumulator}- ${name} \n`
```

Neste caso seria errado o accumulator receber o valor dos nomes do produto igual eu fiz?

Só por curiosidade, tem alguma forma de pesquisar nas issues por dúvidas assim? Minha pesquisa não funcionou.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @NiksonDiniz.

A forma com que vc fez não está errada não =)

Porém, conforme vc for avançando no treinamento, vc verá que eu começarei a falar de um conceito muito utilizado em programação funcional chamado imutabilidade. 

Imutabilidade é apenas um termo técnico para "ao invés de modificar o objeto original, faça uma cópia e então modifique".

No caso desse exercício, eu evitei fazer reatribuição pro `accumulator` por isso. E a reatribuição também é desnecessária nesse caso por que `accumulator` já armazena o valor que a função retornou na execução passada.

Mas o mais importante num primeiro momento vc fez, que é fazer funcionar. Com a prática e o tempo as suas habilidades de refatoração vão melhorando e vc pode voltar no código depois para refatorá-lo =)

> ## Só por curiosidade, tem alguma forma de pesquisar nas issues por dúvidas assim?

Depende de como vc pesquisa. 

Se vc quiser pesquisar apenas por `reduce`, por exemplo, vc pode fazer o seguinte...

Na [página de issues](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues), insira `reduce` no input e pressione `enter`. Vc verá que entre os resultados, estarão as issues de resumos. Se quiser excluir esse tipo de issue da busca, clique no item `label`, segure `alt` e clique na label que vc quer excluir. Assim todas as issues que contém `reduce` e que não são de resumos serão exibidas.

Essa é uma forma. 

Uma outra forma seria pesquisar pelo nome da aula, também excluindo as issues de resumo.

Mas dependendo da especificidade de dúvida, pode ser um pouco complicado pesquisar. Então se sentir que a pesquisa está complexa não precisa se prolongar nesse processo. Pode abrir a issue que te ajudo =)

**Comment by NiksonDiniz** [comment]
Entendi!
Vi um pouco de imutabilidade na faculdade. Mas bem superficialmente.
Vou pesquisar um pouco sobre e não esquecer de não mudar o objeto original.

Em relação a pesquisa, é porque perdi um tempinho procurando algo a respeito, pois fiz um outro bootcamp que o povo não gostava de dúvidas repetidas.

Agradeço sua atenção e consideração em relação as minhas dúvidas!

Obrigado @Roger-Melo

**Comment by Roger-Melo** [comment]
Nada, quando tiver alguma dúvida pode perguntar que te ajudo =)

Vou fechar a issue mas no que precisar, é só abrir uma nova.

@NiksonDiniz
