### ISSUE TITLE
Resumo da Aula 01-03 e 01-04 For e While Loop da etapa 02

### ISSUE THREAD

**Issue by djailtim** [roger-melo-treinamentos/curso-de-js-roger-melo#148]
![image](https://user-images.githubusercontent.com/64450426/107461663-e20c6f00-6b30-11eb-811f-e86ee2d0a153.jpeg)

![image](https://user-images.githubusercontent.com/64450426/107461700-f5b7d580-6b30-11eb-99a0-17109de3ca38.jpeg)

![image](https://user-images.githubusercontent.com/64450426/107461753-0d8f5980-6b31-11eb-9cd8-70bd3c441fb0.jpeg)

![image](https://user-images.githubusercontent.com/64450426/107461784-1c760c00-6b31-11eb-952c-12e4bcb53b90.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @djailtim! 🚀
