### ISSUE TITLE
Resumo da Aula 02/ 03 a 06 da etapa 01

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#1480]
![WhatsApp Image 2021-08-12 at 9 34 18 AM](https://user-images.githubusercontent.com/88742275/129198056-2cf5c307-5cce-4931-8d32-b688b2735ead.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, @shazenn. O faixa-preta é o faixa-branca que não desistiu. Rumo à fluência! 🚀
