### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 03

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1486]
```js
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']

let sentenceCorrect = ''

for (let i = 0; i < sentence.length; i++) {
  if (sentence[i] === 'certeza') {
    continue
  }
  sentenceCorrect += sentence[i]
}
console.log(sentenceCorrect);
```
retorna a frase '**Adúvidaéoprincípiodasabedoria**.'

tentei encadear o método **join** na **sentenceCorrect** e retornou **_Uncaught TypeError: sentenceCorrect.join is not a function_**

não entendi o por que..

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

`sentenceCorrect` é uma string e o `join` é um método de array, não de string. 

Por isso a mensagem do erro diz que `join` is not a function. Não existe uma função `join` disponível a ser encadeada em uma string =)

Sacou a ideia?

**Comment by dracoalv** [comment]
então se eu alterar a let sentenceCorrect para um array vazio, eu posso encadear o método join()?

**Comment by Roger-Melo** [comment]
Pode sim =)

**Comment by dracoalv** [comment]
```js
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']

let sentenceCorrect = []

for (let i = 0; i < sentence.length; i++) {
  if (sentence[i] === 'certeza') {
    continue
  }
  sentenceCorrect += sentence[i]
}
console.log(sentenceCorrect.join(', '));```


Continuou exibindo **Uncaught TypeError: sentenceCorrect.join is not a function**

**Comment by dracoalv** [comment]
Só consegui resolver o método usando o método push no lugar da concatenação
```js
sentenceCorrect += sentence[i]
```
```js
sentenceCorrect.push(sentence[i])
```

**Comment by Roger-Melo** [comment]
No código abaixo, observe que se vc exibir no console o resultado de `sentenceCorrect += sentence[i]`, ela continua armazenando uma string:

```javascript
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']

let sentenceCorrect = []

for (let i = 0; i < sentence.length; i++) {
  if (sentence[i] === 'certeza') {
    continue
  }

  console.log(sentenceCorrect += sentence[i]) // A, AAdúvida, AAdúvidadúvidaé...
  sentenceCorrect += sentence[i]
}
```

Isso aconteceu por que quando o operador `+` é usado entre um array e uma string, o resultado é uma string:

```javascript
console.log([] + 'olá') // olá
```

Por isso, é sempre importante visualizar no console se o valor no qual uma expressão resulta é o valor que vc espera. Inserir `console.log`s no código é fundamental para debugá-lo, então procure usá-lo bastante, ok?

Como à partir da primeira execução do array, `sentenceCorrect` voltou a armazenar uma string, o encadeamento do `join` continua lançando o erro.

> ### Só consegui resolver o exercício usando o método push no lugar da concatenação

Sim, o `push` é um método de array que pode ser usado nesse caso =)

Ficou mais claro?

@dracoalv

**Comment by dracoalv** [comment]
ficou mais claro, vou passar a usar mais o console.log pra entender os resultados, obrigado!!

**Comment by Roger-Melo** [comment]
Legal =)
