### ISSUE TITLE
Resumo da Aula Constantes e variáveis 01-06 da etapa 01

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1488]
Constates e variáveis

Variáveis é fundamental para criação de códigos em varias linguagens de programação, 
seu papel é armazenar valores na memória, podendo ser numéricos, strings, booleanos, Array, 
Objeto e funções. Var é a forma antiga de declarar variáveis (declaração global),
 hoje em dia é mais utilizado o let ou const para declaração de variáveis .
    Existem regras para declaração de variáveis, que são elas: devemos começar com letras, 
cifrão, underline, lembre-se que o Java script é case-sensitivo,
 que diferencia  em minúsculas (a - z) e maiúscula (A - Z). 
    Fique atento com as palavras reservadas, nomes separados e quanto a utilização
 de números no inicio que causam erros.  O javascript segue o padrão de
 Camelcase (que é a denominação em inglês para a prática de escrever as palavras 
compostas ou frases, onde cada palavra é iniciada com maiúsculas e unidas sem espaços. 
É um padrão largamente utilizado em diversas linguagens de programação,
 como Java, C#, Ruby, PHP e Python).

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, @AdrianoRepet. O faixa-preta é o faixa-branca que não desistiu. Rumo à fluência! 🚀
