### ISSUE TITLE
Etapa 03, O método forEach e callbacks - Aula 02-04

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1489]
Boa noite Roger, queria tirar uma duvida com vc , eu estou consultando a documentação sempre que tenho duvida e me surgiu uma que pode ser bem primaria mas não posso deixar de perguntar .
Tento intender esse exemplo de sintaxe do MDN mas estou meio perdido tem como me dar uma explicação  ?

este é o exemplo do forEach()
```js
arr.forEach(callback(currentValue [, index [, array]])[, thisArg]);
```
Não consigo intender ,vejo que tem uma função de callback  com alguns parâmetros index , array e thisArg,
os dois primeiros são valores que são retornados e o currentValue é o item mas fica bem confuso intender com esses colchetes , é uma sintaxe que não vemos muito frequentemente e essas vírgulas estão me deixando mais perdido ainda....
Obrigado e boa noite !!!

@Roger-Melo

**Comment by jhow221318** [comment]
Muito obrigado , que Deus abençoe continuarei estudando mais e mais .... Bom dia !🤜🤛

**Comment by Roger-Melo** [comment]
Show @jhow221318. Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova =)
