### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 03 da etapa 02

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1494]
Na correção deste exercício, reparei que a expressão abaixo foi colocada após o if, no meu raciocínio eu implementei a soma antes do if, notei que o resultado foi o mesmo, porém a minha dúvida é se isso pode implicar no fluxo do loop?
```js
sumNumbers += randomNumbers[i]
```

```js
const randomNumbers = [59, 61, 73, 57, 35, 73, 21, 87, 43]

let sumNumbers = 0
const limit = 400

for (let i = 0; i < randomNumbers.length; i++) {
  sumNumbers += randomNumbers[i]
  
  if(sumNumbers > limit) {
    console.log(`A soma ultrapassou ${limit}. Até aqui, o valor atual é ${sumNumbers}.`);
    break
  }
}

console.log(sumNumbers);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Nesse caso, não há problemas, o resultado é o mesmo e não há impacto significativo no fluxo do loop. 

No código abaixo, `sumNumbers` sempre irá armazenar `6` na 3ª execução do loop, independente se `sumNumbers += randomNumbers[i]` for posicionada antes ou depois do `if`.

```javascript
const randomNumbers = [1, 2, 3, 4]

let sumNumbers = 0
const limit = 3

for (let i = 0; i < randomNumbers.length; i++) {
  sumNumbers += randomNumbers[i]
  console.log(sumNumbers)

  if (sumNumbers > limit) {
    console.log(`A soma ultrapassou ${limit}. Até aqui, o valor atual é ${sumNumbers}.`)
    break
  }
}
```

A única diferença é que se `sumNumbers += randomNumbers[i]` é inserida após o if, o bloco do loop é executado pela 4ª vez. Ou seja, 1x à mais. Mas nesse caso, tanto faz.

Ficou mais claro?

Off-topic: observando seu código, apenas invocações do `console.log` tem `;`. Escolha se irá manter ou descartar o ponto e vírgula e seja consistente nessa escolha no decorrer do código =)

**Comment by dracoalv** [comment]
Entendi, neste caso não implicaria pois o loop seria quebrado da mesma maneira, já que o console.log ta dentro do if, certo?

o console.log com ponto e vírgula no final acontece pq eu uso o atalho log para inserir o console.log, vou passar a escreve-los

**Comment by Roger-Melo** [comment]
> Entendi, neste caso não implicaria pois o loop seria quebrado da mesma maneira, já que o console.log ta dentro do if, certo?

Isso. Na verdade é o `break` que quebra o loop.

Apenas para eu não pecar por falta de clareza:

```javascript
const randomNumbers = [1, 2, 3, 4]

let sumNumbers = 0
const limit = 3

for (let i = 0; i < randomNumbers.length; i++) {
  sumNumbers += randomNumbers[i]

  if (sumNumbers > limit) {
    console.log(`A soma ultrapassou ${limit}. Até aqui, o valor atual é ${sumNumbers}.`)
    break
  }
}
```

No código acima, `sumNumbers += randomNumbers[i]` é executada antes do `if` e vc pode ter um panorama do que está acontecendo nessa tabela:

Execuções do for | valor que `sumNumbers` recebeu | `if` é executado?
:-- | :-: | :-:
1ª execução | 1 | Não, por que 1 não é maior que 3
2ª execução | 3 | Não, por que 3 não é maior que 3
3ª execução | 6 | Sim, por que 6 é maior que 3

No caso acima, `break` para a execução do loop na 3ª execução.

---

No código abaixo: 

```javascript
for (let i = 0; i < randomNumbers.length; i++) {
  if (sumNumbers > limit) {
    console.log(`A soma ultrapassou ${limit}. Até aqui, o valor atual é ${sumNumbers}.`)
    break
  }

  sumNumbers += randomNumbers[i]
}
```

`sumNumbers += randomNumbers[i]` é executada após o `if`, então:

Execuções do for | valor de `sumNumbers` | `if` é executado?
:-- | :-: | :-:
1ª execução | 0 | Não, por que 0 não é maior que 3
2ª execução | 1 | Não, por que 1 não é maior que 3
3ª execução | 3 | Não, por que 3 não é maior que 3
4ª execução | 6 | Sim, por que 6 é maior que 3

Sacou por que há uma execução à mais do loop quando `sumNumbers += randomNumbers[i]` é executada após o `if`?

Para facilitar a visualização, nos dois casos, vc pode inserir um console.log na primeira linha do loop:

```javascript
for (let i = 0; i < randomNumbers.length; i++) {
  console.log(`${i + 1}ª execução do loop`) // 1ª execução do loop, 2ª execução do loop, etc...

  if (sumNumbers > limit) {
    console.log(`A soma ultrapassou ${limit}. Até aqui, o valor atual é ${sumNumbers}.`)
    break
  }

  sumNumbers += randomNumbers[i]
}
```

Ficou mais claro?

@dracoalv

**Comment by dracoalv** [comment]
Ficou mais claro, estou digerindo as informações aos poucos, obrigado pela dedicação na transmissão da informação!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
