### ISSUE TITLE
Etapa 03 - Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1495]
No exercício 6, a let da mensagem a ser exibida nos cases foi armazenada com null, na minha resolução eu armazenei nela uma string vazia, isso é pior? em quais casos devo usar uma ou outra?

```js
let messageInfo = null
```
```js
let messageInfo = ''
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ...isso é pior?

Não é pior. Inclusive, nesse caso, pode ser interessante pois assim, de certa forma, vc demonstra que o valor que a let deve receber é uma string =)

> ...em quais casos devo usar uma ou outra?

Vc usará o `null` quando quiser indicar **intencionalmente** que não existe valor em uma variável. Mas na real, vc verá o `null` sendo usado muito pouco durante o treinamento. Nas etapas iniciais ele é usado apenas para demonstrar que existe e que é diferente de `undefined` =)

Sacou a ideia?

@dracoalv

**Comment by dracoalv** [comment]
ahhh sim, entendi, obrigado!
