### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#1496]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/YureK-a/Meu-portfolio/tree/main/Weather-Application

### Maiores dificuldades durante a implementação

Melhorar a "GetWeatherInfos". Eu não consegui achar uma forma mais adequada de avisar ao usuário de que o valor inserido é inválido, então tive que usar um alert. Anteriormente, eu tentei criar uma função que criava um h1 que receberia o valor do "error", mas eu acabei travando na hora de fazer com que a mensagem só fosse exibida quando o valor era inválido(desculpe, não sei explicar isso direito). Também tentei isolar em uma função a parte que o await é usado mas não consegui também, portanto tive que deixar desse jeito mesmo.

### Menores dificuldades durante a implementação

Organizar o resto do código. Eu imediatamente separei o código em 4 partes, aproveitando do fato das funções e selectors ficarem salvos. Também aproveitei para usar o scrollTo, que por algum motivo, só funciona depois de clicar uma vez no "enter". Sobre a refatoração, eu achei realmente fácil. Os ifs que indicavam se era dia ou noite foram as primeiras coisas que eu mudei, seguidos pelas atribuições de valores que a showWeatherInfos faz.

Não tive dificuldade para mudar as cores do "quadro" que mostra as informações do clima, mas não me veio a mente uma cor que combinasse, então mudei apenas o background da página.

**Comment by Roger-Melo** [comment]
Olá @YureK-a.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

Parabéns pelo esforço em construir mais uma aplicação do treinamento =)

> ## Maiores dificuldades durante a implementação

Sem problemas. Na próxima aplicação, vc verá uma forma de implementar mensagens de erros para o usuário na tela. 

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Sua fluência na linguagem vem com a prática e o tempo, ok?

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Organização de código

### Estrutura de diretórios e arquivos

Prefira seguir a estrutura de arquivos e diretórios mostrada nas aulas. 

A raiz do seu projeto precisa ter um `index.html`, nem que seja pra que esse index tenha links que ao serem clicados direcionem para as aplicações. Se sua estrutura permanecer assim, quando for subir as aplicações para o Netlify, cada aplicação precisará ter um `index.html` na raiz do projeto e vc terá que copiar os arquivos para um novo repositório manualmente.

O código dessa aplicação é relativamente pequeno, não vejo muito sentido em quebrá-lo em 4 arquivos.

## Lógica

Ao invés de invocar `getWeatherInfos` dentro do callback de `'submit'` do `cityForm`, você pode renomeá-la para `showWeatherInfo` e invocá-la dentro do callback de envio do `cityForm`:

```javascript
cityForm.addEventListener('submit', event => {
  event.preventDefault()

  const city = event.target.city.value

  showWeatherInfo(city)
  scroll()
  cityForm.reset()
})
```

Feito isso, na `getWeatherInfo`, vc pode retornar as informações do clima. Assim, quando ela for invocada, a única responsabilidade que ela vai ter é a que está no nome dela (obter informações do clima):

```javascript
const getWeatherInfo = async city => {
  try {
    const cityToSearch = city.trim().toLowerCase()
    const [{ Key, LocalizedName }] = await getCityData(cityToSearch)
    const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await
      getCityWeather(Key)

    if (!Key) {
      throw new Error()
    }

    return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
  } catch (error) {
    alert('Algo deu errado. Verifique se escreveu corretamente.')
  }
}
```

A `showWeatherInfo`, pode receber essas informações e executar a manipulação de DOM. Ficaria mais ou menos assim:

```javascript
const showWeatherInfo = async city => {
  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = 
    await getWeatherInfo(city)

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  cityCard.classList.contains('d-none') ? cityCard.classList.remove('d-none') : false
}
```

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar a manipulação da class `'d-none'` (em que o valor no qual essa expressão resulta não está sendo aproveitado), nesse caso, o ideal é usar `if`: 

```javascript
const showWeatherInfo = async city => {
  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = 
    await getWeatherInfo(city)

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value

  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }
}
```

Feito isso, você pode encapsular esse efeito colateral em uma função:

```javascript
const showCityCard = () => {
  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }
}

const showWeatherInfo = async city => {
  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = 
    await getWeatherInfo(city)

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  showCityCard()  
}
```

### Lançamento de erros

Ao lançar um erro, você precisa especificar uma mensagem de erro como argumento. Então o ideal no `throw new Error` do `try/catch` dentro da `getWeatherInfo` é fazer algo desse tipo:

```javascript
const getWeatherInfo = async city => {
  try {
    // ...

    if (!Key) {
      throw new Error('Algo deu errado. Verifique se escreveu corretamente.')
    }

    return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
  } catch ({ name, message }) {
    alert(`${name}: ${message}`)
  }
}
```

Eu ainda vou aprofundar em tratamento de erros em aulas futuras, mas se vc testar o código acima, se uma cidade inválida é inserida, a verificação da `Key` acontece após o destructuring. Isso significa que se não ouver `Key` pra fazer o destructuring, um erro é lançado na linha da tentativa do destructuring:

```javascript
const getWeatherInfo = async city => {
  try {
    const cityToSearch = city.trim().toLowerCase()
    const [{ Key, LocalizedName }] = await getCityData(cityToSearch) 
    // TypeError: Cannot read property 'Key' of undefined
    
    // ...
```

Para evitar isso, você pode fazer o seguinte...

```javascript
  try {
    const cityToSearch = city.trim().toLowerCase()
    const cityData = await getCityData(cityToSearch)

    if (!cityData.length) {
      throw new Error('Algo deu errado. Verifique se escreveu corretamente.')
    }

    const [{ Key, LocalizedName }] = cityData
    const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await
      getCityWeather(Key)

    return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
  }
```

No código acima, se uma cidade inválida for inserida, o array vazio obtido da API faz com que a expressão `cityData.length` resulte em zero. Como zero é um valor falsy e é necessário que a expressão do if resulte em um valor truthy pra que ele seja executado, basta usar o not. Assim, se uma cidade inválida é inserida, o erro avisando sobre o valor correto a ser inserido é de fato lançado.

Porém, veja também que se a cidade é inválida e o código da `showWeatherInfo` fica assim,

```javascript
const showWeatherInfo = async city => {
  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = 
    await getWeatherInfo(city)

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  showCityCard()  
}
```

um erro "TypeError: Cannot destructure property 'LocalizedName' of '(intermediate value)' as it is undefined." É lançado.

Isso aconteceu pq `await getWeatherInfo(city)` está retornando undefined. 

Por que está retornando undefined?

Por que dentro da `getWeatherInfo`, o `throw new Error('...')` foi executado, a execução da função foi interrompida e ela não retornou um valor. 

Como em js, toda função que não retorna um valor retorna undefined por baixo dos panos, o `TypeError` dizendo que não é possível fazer destructuring na `LocalizedName` foi lançado pq não existe uma propriedade LocalizedName em undefined.

Para resolver isso, você pode apenas verificar o valor que `await getWeatherInfo(city)` retorna:

```javascript
const showWeatherInfo = async city => {
  const weatherInfo = await getWeatherInfo(city)

  if (!weatherInfo) {
    return
  }

  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = weatherInfo

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  showCityCard()  
}
```

Sacou a ideia?

O código ficaria mais ou menos assim:

```javascript
const getWeatherInfo = async city => {
  try {
    const cityToSearch = city.trim().toLowerCase()
    const cityData = await getCityData(cityToSearch)

    if (!cityData.length) {
      throw new Error('Algo deu errado. Verifique se escreveu corretamente.')
    }

    const [{ Key, LocalizedName }] = cityData
    const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await
      getCityWeather(Key)

    return { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon }
  } catch ({ name, message }) {
    alert(`${name}: ${message}`)
  }
}

const showCityCard = () => {
  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }
}

const showWeatherInfo = async city => {
  const weatherInfo = await getWeatherInfo(city)

  if (!weatherInfo) {
    return
  }

  const { LocalizedName, WeatherText, Temperature, IsDayTime, WeatherIcon } = weatherInfo

  timeImg.src = IsDayTime ? '/src/day.svg' : '/src/night.svg'
  timeIconContainer.innerHTML = `<img src="/src/${WeatherIcon}.svg" />`
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  showCityCard()  
}

const scroll = () => {
  setTimeout(() => {
    scrollTo(0, 200)
  }, 300)
}

cityForm.addEventListener('submit', event => {
  event.preventDefault()

  const city = event.target.city.value

  showWeatherInfo(city)
  scroll()
  cityForm.reset()
})
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by YureK-a** [comment]
Muito obrigado professor! Irei estudar as observações para aprimorar o código! =)
