### ISSUE TITLE
Etapa 01, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by viniciusnunhez27** [roger-melo-treinamentos/curso-de-js-roger-melo#1498]
Boa Noite  @Roger-Melo ,

Fiquei com duvida nessa parte do exercicio  ( Exercicio Aula-02).

Duvida:   - Armazene a junção das letras "J" e "S", da programmingLanguage, em uma constante "js";

Resolução dessa etapa seria utilizar os  " [ ] "  buscando as letras J S  dentro da Variavel ? .

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @viniciusnunhez27.

> Resolução dessa etapa seria utilizar os " [ ] " buscando as letras J S dentro da Variavel ?

Isso mesmo. Com a notação `string[index]` vc acessa o caractere que está no index que foi especificado entre os colchetes.

Essa é uma forma de resolver e é a forma que eu mostrei na correção. Em aulas futuras, vc conhecerá outras formas mais avançadas =)

Respondi a dúvida?

**Comment by viniciusnunhez27** [comment]
Era isso mesmo minha duvida @Roger-Melo  , Obrigado .

**Comment by Roger-Melo** [comment]
Show @viniciusnunhez27. No que precisar, é só abrir uma nova issue =)

**Comment by carlosebs** [comment]
Bom dia @Roger,
 também fiz este exercício utilizando o strings.slice(), consegui o resultado,  sendo que com o index fica mais elegante o código.
