### ISSUE TITLE
Etapa 03, nome do vídeo: Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1499]
Boa-tarde ROGER
Na correção do Exercício, Roger fez o seguinte:
```
const randomNumbers = [59, 61, 73, 57, 35, 73, 21, 87, 43]
let sumResult=0
for(let i=0;i<randomNumbers.length;i++){
  if(sumResult>400){
    console.log(`A soma ultrapassou 400. Até aqui, o valor atual é ${sumResult}.`)
    break
  }
  sumResult+=randomNumbers[i]
}
```

Mas antes de eu ver a sua correcção eu tinha feito assim:
```
const randomNumbers = [59, 61, 73, 57, 35, 73, 21, 87, 43]
let sum=0
for(let i=0;i<randomNumbers.length;i++){
  sum+=randomNumbers[i]
  if(sum>400){break}
}
console.log(`A soma ultrapassou 400. Até aqui, o valor atual é ${sum}.`)
```
**Recomenda a forma que eu fiz? ou a metodologia  na sua correção é a mais correcta? Explique-me porque!**

**NOTA: já apaguei a minha resolução e fiz novamente conforme a sua correcção, aprendi.**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Antes de responder, deixa eu dar uma dica.

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, basta inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

Ele ficará assim:

```javascript
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

Lembrando que antes de postar a issue, vc pode clicar em "Preview" para visualizar como ela ficará quando for postada.

---

Pelo que vi, as diferenças entre a forma mostrada na correção e a que vc fez estão no posicionamento da expressão `sumResult += randomNumbers[i]` e do console.log, certo?

Não há problemas em ter colocado o console.log fora do if, já que ele vai ser executado praticamente no mesmo momento em que se estivesse dentro do if.

Sobre o posicionamento da `sumResult += randomNumbers[i]`, dê uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1494).

Se ainda restarem dúvidas, pode comentar aqui nessa issue =)

**Comment by gerafim** [comment]
Obrigado ROGER pelo alerta com relação ao **highlight** do código.  Acolhi a recomendação e passarei a implementar nas próximas vezes.

Ficou clara a explicação, principalmente quando ví a sua resposta à dúvida do @dracoalv

Muito obrigado!

**Comment by Roger-Melo** [comment]
Legal @gerafim. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
