### ISSUE TITLE
Recriando método some

### ISSUE THREAD

**Issue by gbr-jpg** [roger-melo-treinamentos/curso-de-js-roger-melo#15]
Oi Roger, consegui idealizar o método some como proposta no exercício e gostaria do seu feedback sobre a lógica que empreguei, se ela está correta ou não, pois tive uma lógica um pouco diferente da sua quando corrigido o exercício.

**Explicando minha lógica:** Bom Roger, eu estava fazendo de um modo que o laço percorria todos os itens do array e para cada item retornava um boolean, ai surgiu minha ideia.  _"Que tal eu armazenar todos esses booleans gerados neste laço e joga-los dentro de um novo array e quando todos booleans forem gerados eu verifico se nesse array está incluso um true. Legal se houver será retornado um true por causa do método incluse, se não um false kkk" 💭_

Oque você acha professor, está correto este meu raciocinio ?  Abraço
```
const some = (array, test) => {
  const arrayBooleans = []  

  for (let i = 0; i < array.length; i++) {    
    const checkingArray = test(array[i])
    
    arrayBooleans.push(checkingArray)
  }
  const check = arrayBooleans.includes(true)

  console.log(check)
}
some([1, 2, 3], item => item > 2) // true
some([1, 3, 5], item => item === 0) // false
```

**Comment by Roger-Melo** [comment]
Oi @gbr-jpg!

Em JavaScript, existem várias formas de se resolver o mesmo problema.

Se você entendeu a implementação que fiz na revisão e, depois de conseguir executá-la sozinho, fez variações da solução, excelente!

A única coisa que você não pode fazer é seguir com dúvidas =)

**Comment by gbr-jpg** [comment]
Correto professor! =)
