### ISSUE TITLE
Etapa 7, setTimeout e objeto Window: Aula 02-02

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1501]
A intenção era parar o Timer após a 1º chamada do método...

https://github.com/marcosyoggy/setTimeout--Aula-02-02-E07

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Não entendi qual é dúvida, seja mais específico. Quanto mais específica for a dúvida, mais fácil fica ajudá-lo =)

**Comment by Roger-Melo** [comment]
Acho que entendi o problema.

No código abaixo, no 2º clique no `button_Timer`, a invocação da `Stop_Timer()` na última linha do `if` de fato executa o `clearTimeout`:

```javascript
function Stop_Timer() {
  clearTimeout(get_Number_ID)
  
  // ...
}

button_Timer.addEventListener('click', () => {
  if (get_Number_ID >= 1) {
    console.log('Este deveria ser o ponto final do Timer!!!')
    Stop_Timer()
  }

  number_ID = setTimeout((number_Calc) => {
    let sum = number_Calc * 2
    result_Sum = sum
    get_Number_ID = number_ID
    time_Visor.textContent = 'Click no button e...'
    time_Visor_2.textContent = '...a mágica acontece!!!!'

    new_Element_to_Message_1()

    console.log(get_Number_ID)
    console.log(result_Sum)

  }, 2000, 50);
})
```

Porém, após a execução do `if`, tudo o que vem abaixo dele continua sendo executado normalmente. Ou seja, mesmo que o timer com o id anterior tenha sido interrompido, após o `if` um novo timer é iniciado.

Para resolver isso, basta impedir que o código abaixo do `if` seja executado. Você pode fazer isso usando um `return` na última linha do `if`:

```javascript
  if (get_Number_ID >= 1) {
    console.log('Este deveria ser o ponto final do Timer!!!')
    Stop_Timer()
    return
  }
```

Se vc testar esse código agora, do 2º clique em diante nenhum novo timer é iniciado.

Era essa a dúvida?

@marcosyoggy

**Comment by marcosyoggy** [comment]
Sim... eu tinha usado 'return', de fato ele pára o 'Timer', mas clicar novamente no botão, fica  exibindo o conteúdo da 'function stop_Timer', foi com base nisso que gerou a minha dúvida. Pensei que o 'clearTimeout' faria um 'Reset Geral' e nada mais seria processado...Obrigado Roger pela atenção.

**Comment by Roger-Melo** [comment]
Show @marcosyoggy. Se surgir alguma outra dúvida, é só abrir uma nova issue =)
