### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1502]
No exercício 06 da bateria de exercícios 8, é pedido o seguinte:

```js
/*
  - Descomente a invocação da função abaixo e implemente-a;
  - Ela deve retornar um novo array com apenas os números ímpares do array 
    passado por argumento;
  - Exiba o novo array no console, sem inserir um console.log() dentro da  
    função.
*/

// getOddNumbers([83, 52, 31, 73, 98, 37, 61, 56, 12, 24, 35, 3, 34, 80, 42, 211])
```

Estou com dificuldades para digerir a lógica sobre funções e conclui o exercício com o código abaixo, minha dúvida é: tornei a alguma coisa ineficiente, ou menos ineficiente do que a sua resolução?

```js
let oddNewArray = []

const getOddNumbers = function (array = []) {
  for (let i = 0; i < array.length; i++) {
    let arrayNumber = array[i]
    const isOddNumber = arrayNumber % 2 !== 0

    if (isOddNumber) {
      oddNewArray.push(arrayNumber)
    }
  }

  return oddNewArray
}

getOddNumbers([83, 52, 31, 73, 98, 37, 61, 56, 12, 24, 35, 3, 34, 80, 42, 211])

console.log(oddNewArray);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Obrigado por postar o enunciado do exercício, agiliza bastante =)

> ## Estou com dificuldades para digerir a lógica sobre funções

Pode ser mais específico?

---

A diferença entre as resoluções são o local em que o novo array é declarado e a forma com que a `getOddNumbers` foi invocada, certo?

Tem duas coisas nisso, e eu preciso que vc não apenas olhe as próximas linhas, mas execute elas junto comigo, ok?

A primeira é o `return`.

No código abaixo,

```javascript
let oddNewArray = []

const getOddNumbers = function (array = []) {
  for (let i = 0; i < array.length; i++) {
    let arrayNumber = array[i]
    const isOddNumber = arrayNumber % 2 !== 0

    if (isOddNumber) {
      oddNewArray.push(arrayNumber)
    }
  }

  return oddNewArray
}

getOddNumbers([83, 42, 211])

console.log(oddNewArray)
```

como existe um `return oddNewArray` dentro da declaração da `getOddNumbers`, a expressão `getOddNumbers([83, 42, 211])` resulta no valor que o `return` está retornando.

Isso significa que se vc inserir essa expressão de invocação como argumento de um `console.log()`, essa expressão resulta no `oddNewArray` que foi retornado dentro da função:

```javascript
console.log(getOddNumbers([83, 42, 211])) // [ 83, 211 ]
```

Ou seja, se dentro da função há um `return`, a invocação da função resulta nesse valor que o return está retornando. Essa é a primeira coisa que vc precisa sacar.

A segunda coisa é o local onde `oddNewArray` é declarada. Por que é o seguinte...

Funções são blocos que contém um código que pode ser executado quando e quantas vezes você quiser. Certo?

No exercício, a função foi executada apenas uma vez.

Mas olha o que acontece se eu executar a função novamente, passando um array diferente:

```javascript
let oddNewArray = []

const getOddNumbers = function (array = []) {
  for (let i = 0; i < array.length; i++) {
    let arrayNumber = array[i]
    const isOddNumber = arrayNumber % 2 !== 0

    if (isOddNumber) {
      oddNewArray.push(arrayNumber)
    }
  }

  return oddNewArray
}

console.log(getOddNumbers([83, 42, 211])) // [ 83, 211 ]
console.log(getOddNumbers([66, 57, 90]))  // [ 83, 211, 57 ]
```

Na segunda invocação, o retorno foi `[ 83, 211, 57 ]` ao invés de `[57]`.

Isso aconteceu por que a `oddNewArray` continou armazenando o array gerado na 1ª invocação da função.

Agora, olha o que acontece quando `oddNewArray` é inserida dentro da função:

```javascript
const getOddNumbers = function (array = []) {
  let oddNewArray = []

  for (let i = 0; i < array.length; i++) {
    let arrayNumber = array[i]
    const isOddNumber = arrayNumber % 2 !== 0

    if (isOddNumber) {
      oddNewArray.push(arrayNumber)
    }
  }

  return oddNewArray
}

console.log(getOddNumbers([83, 42, 211])) // [ 83, 211 ]
console.log(getOddNumbers([66, 57, 90]))  // [ 57 ]
```

Dessa vez, a segunda invocação da função retornou o array esperado.

E isso aconteceu por que quando vc insere const/let/var dentro de uma função, cada invocação da função declara uma nova const/let/var.

Ou seja, na segunda invocação da função, uma nova `let oddNewArray` foi declarada em outro lugar da memória e não haverá colisão entre as `oddNewArray` das invocações.

Sacou a ideia?

Isso é chamado de escopo, mas não se preocupe. Vc aprenderá isso em aulas futuras.

---

É fundamental que você entenda bem funções antes de continuar. Por isso eu perguntei lá em cima se a pergunta poderia ser mais específica. Se sentir que é necessário, volte nas aulas sobre funções e refaça os exercícios. 

Se tiver com dificuldades de entender alguma coisa, não hesite em abrir uma issue. A vantagem de abrir issues no momento em que dúvidas surgem é que as dúvidas tendem a ser mais específicas =)

Ps: tira o `;` do console.log 😂

**Comment by dracoalv** [comment]
ahhhhhhhh, caraca, agora eu saquei, não fazia ideia disso, to voltando as aulas, ja refiz os exercícios umas 5 vezes, to sentindo mais facilidade agora, mas talvez seja por estar repetindo os exercícios, travei agora foi nas funções de callback, mas estou estudando a fundo para entender, obrigado mais uma vez

**Comment by Roger-Melo** [comment]
Não. Snippets embutidos do VSCode não são editáveis. Vc pode usar o autocomplete e tirar a vírgula ou digitar na mão (que é o que eu indico no começo) =)

**Comment by Roger-Melo** [comment]
Show =)
