### ISSUE TITLE
Resumo da Aula 1 da etapa 3 até 6

### ISSUE THREAD

**Issue by caiobgs** [roger-melo-treinamentos/curso-de-js-roger-melo#1503]
## Aula 1-3  

Fazendo o download do Vs Code, instalando a extensão live server. 

  

**O que é um servidor:** 

Local onde se guarda informações consumidas pelo front end de aplicações, por meio de requests e responses. 

  

**LocalHost:**  

um servidor local, hospedado na minha própria máquina. 

  

**Atalhos:** 

Control + P: input onde se pode acessar todas as features do navegador. 

Control + B: Esconder barra lateral. 

  

## Aula 1-4 

Adicionando javascript ao HTMl utilizando a tag `<script>`. 

A tag pode ser adicionada tanto no `<head>` quanto no `<body>` de forma inline ou importando um arquivo externo, entretanto para evitar problemas ao executar é recomendado utilizá-la acima do fechamento da tag `<body>`. 

  

## Aula 1-5 

Console do browser é um local onde os scripts podem ser testados diretamente no navegador, ajudando a debugar e testar novas funcionalidades 

  

`console.log()`: utilizado para imprimir valores no console. 

  

## Aula 1-6 

**Variável:** 

é responsável por guardar um valor passado para ela. 

  

**formas de declarar variáveis em js:** 

`let`: permite ter novos valores atribuídos durante o script. 

`const`: constante, não permite atribuir novos valores. 

`var`: forma antiga(Pré ES5) de se declarar variaveis. 

  

**Regras para nomear variáveis:** 

* utilizar camelcase para declaração de variáveis. 

* podem conter somente letras, números, under score e números, entretanto não é permitido iniciar com números 

* não é permitido utilizar palavras reservadas pelo sistema. 

* utilizar nomes sugestivos 

  

**Atalhos:** 

Control + ; :utilizado para comentar. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, @caiobgs. O faixa-preta é o faixa-branca que não desistiu. Rumo à fluência! 🚀
