### ISSUE TITLE
Resumo da Aula 2-03da etapa 01

### ISSUE THREAD

**Issue by AleCarraDev** [roger-melo-treinamentos/curso-de-js-roger-melo#1504]
![AULA 02-03(3)](https://user-images.githubusercontent.com/88162484/129455884-40e8f7bd-9bbd-4acc-9909-6a6632811584.jpg)
![AULA 02-03(2)](https://user-images.githubusercontent.com/88162484/129455887-65077359-4c95-4ac6-bccf-8aedc84e6261.jpg)
![AULA 02-03(1)](https://user-images.githubusercontent.com/88162484/129455889-9e3fdf4b-76cc-4dd1-a1c4-994dae84a78a.jpg)
![WhatsApp Image 2021-08-14 at 14 46 41 (3)](https://user-images.githubusercontent.com/88162484/129455909-1d09448d-ecb9-481e-b884-d39f378a6532.jpeg)
![WhatsApp Image 2021-08-14 at 14 46 41 (2)](https://user-images.githubusercontent.com/88162484/129455910-9d39455a-f3b4-4de2-b1ba-e39cbcf09cf0.jpeg)
![WhatsApp Image 2021-08-14 at 14 46 41 (1)](https://user-images.githubusercontent.com/88162484/129455911-73fe9809-f7d6-4c6a-a9b5-73824f520bd2.jpeg)
![WhatsApp Image 2021-08-14 at 14 46 41](https://user-images.githubusercontent.com/88162484/129455912-050556b7-d1f7-45c9-be6c-19979fe61e51.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, @AleCarraDev. O faixa-preta é o faixa-branca que não desistiu. Rumo à fluência! 🚀
