### ISSUE TITLE
Etapa 01, Configuração

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1508]
Roger, ainda sobre as cores dos códigos, estou tendo dificuldades para assimilar quando errei alguma palavra, direto eu erro a palavra length, como no seu VSCode ela fica destacada em laranja, creio que me ajudaria muito.

suas cores
![image](https://user-images.githubusercontent.com/70287096/129456957-498b0d19-700b-4b2b-a1f6-f7d6b70f6dd6.png)

minhas cores
![image](https://user-images.githubusercontent.com/70287096/129456990-e643931b-fd8a-45a4-a0ba-df0d748bf344.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
É como eu disse antes, acho que as pessoas que mantinham essa extensão descontinuaram ela. Isso foi um dos motivos de eu ter parado de usar. Se quiser correr atrás, esse é o [repo](https://github.com/joshpeng/One-Dark). Mas acho perda de tempo se preocupar com esse tipo de detalhe.

**Comment by dracoalv** [comment]
Obrigado, consegui fazer as alterações, esse lenght tava me matando

**Comment by Roger-Melo** [comment]
Show =)

**Comment by dracoalv** [comment]
Roger! boa noite, qual theme você usa atualmente ?
