### ISSUE TITLE
Resumo da Aula 01-02 a 01-04 da Etapa 02

### ISSUE THREAD

**Issue by lathne** [roger-melo-treinamentos/curso-de-js-roger-melo#1509]
### Loops
Existem momentos em que precisamos executar pedaços de códigos multiplas vezes. Ou seja, controlar o fluxo do código. Os laços de repetição são estruturas que modificam o fluxo de programas (percorrem elementos, adiciona, remove ou altera valores)

**Estrutura dos loops**

```
for ( inicialização, condição, incremento) { 
     bloco de codigo
}
```
```
while (condição) {
i++
se não incrementar o valor a condição nunca será false
 }
```
##
ITERAÇÃO
Corresponde a cada vez que o codigo é executado ou percorre um array por exemplo

SINTAXE
A forma como se escreve o codigo

##

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, @lathne. O faixa-preta é o faixa-branca que não desistiu. Rumo à fluência! 🚀

**Comment by lathne** [comment]
Boa professor, valeu!!
