### ISSUE TITLE
Etapa 03, nome do vídeo: Funções de callback

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1510]
Tudo estava indo bem, mas travei nessa história de callback, como assim vc invoca um parâmetro como função? e o parâmetro dessa função é o argumento de onde? não entendi pra onde escorregou os valores e onde resultou o final, omg, um parâmetro tem ligação com o outro?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Em JavaScript, parâmetros podem ser qualquer valor. Inclusive uma função.

Callbacks levam um certo tempo pra clicar na mente. Mas eu recomendo fortemente que você execute esse [passo a passo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574#issuecomment-828888990) **até o final**. Se restar qualquer dúvida, pode responder aqui =)

@dracoalv

**Comment by dracoalv** [comment]
nossa, com aquela explicação tudo fez sentido agora, obrigado mais uma vez!
