### ISSUE TITLE
Resumo da Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by bxzzxnx** [roger-melo-treinamentos/curso-de-js-roger-melo#1511]
### Resumo até a aula 02-06 da Etapa 01

**02-02 Tipos de Dados:**

- `Number, String, Boolean, NaN, Undefined, Object, Symbol, BigInt, Null`

**02-03 Strings:**

`let palavra = 'string'`

`palavra[0]`  = 's'  //Acessando ìndices de string

`palavra.length ` ==  6

`palavra.toUpperCase() `// 'STRING'

`palavra.toLowerCase() `// 'string'

`palavra.indexOf('s') `//  = 0  Se for true Retorna a posição do caractere , se for false retorna -1

**02-04 Métodos String**
`.lastIndexOf()`  Retorna a ultima ocorrência
`.slice()` Possui 2 argumentos, o primeiro é o número que representa o índice a partir do qual deve ser cortado,  e o segundo é o final da extração

```
const email = 'exemplo@exemplo.com'
email.slice(0,15) // 'exemplo@exemplo
````
`.replace()` Substitui um caractere ou string por outra, leva 2 argumentos , A string que vai ser substituída, e a que vai ser realocada

**02-05 Numbers**
`let x = 10`
Incremento  = x + 1 ou x++; // 11
Decremento = x- 1  ou  x--; // 9
Divisão = x / 5 ou x /= 5 // 2
Resto de divisão = x %= 2 // 0

**02-06 Template String**
Aspas simples dentro de aspas simples usando o  \
```
'\' dentro \' fora '
' dentro ' fora
```
Concatenação normal 
```
'A pessoa tem: ' + x+ ' anos'
```
Com o uso de Template String
```
`A pessoa tem: ${x} anos`
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @bxzzxnx, rumo à fluência! 🚀
