### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#1517]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuniorAlvesbr/quiz-estados-brasil

### Maiores dificuldades durante a implementação

Tive dificuldade com o bootStrap, não manjo nada dessa lib.

E ainda tenho muita dificuldade em realizar a lógica e pensar no algoritmo, principalmente na implementação de objetos e arrays.
Eu venho de criar scripts com programação imperativa, e na hora de fazer a lógica eu simplesmente me esqueço de objetos e arrays, e coloco tudo em variáveis, criando muitas variáveis para controlar o fluxo da aplicação.

### Menores dificuldades durante a implementação

Uma vez que eu entendo a lógica, implementar o código para mim não é tão difícil.

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Maiores dificuldades durante a implementação

O uso do Bootstrap é opcional. Fique à vontade para usar CSS puro ou qualquer outra lib.

Mesmo com as dificuldades com a lógica que vc apontou, o mais importante no primeiro momento vc já fez, que é fazer funcionar. Sua chegada na fluência vem com a prática e o tempo, ok?

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que o papel do `forEach` era apenas calcular os pontos. Nenhuma operação desnecessária foi executada dentro dele. Ótimo.

## Usabilidade

### Local da exibição dos pontos

Fique atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível):

![envio-form](https://user-images.githubusercontent.com/29297788/129609206-094484c1-783b-4fee-b261-ba32402b1d35.jpg)

Uma possível solução seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

## Organização de código

### Convenções

Se possível, prefira deixar a invocação do `event.preventDefault()` na primeira linha. É apenas uma convenção para que primeira informação ao começar a ler a função é de que a página não será carregada no envio do form.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Para deixar mais claro que `correctAnswer` e `userAnswer` armazenam várias respostas, prefira nomeá-las como `correctAnswers` e `userAnswers`, no plural.

Para dar mais coesão ao código, prefira nomear o primeiro parâmetro do callback do `forEach` como uma representação singular dos itens do array. Então `element` ficaria como `userAnswer`.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode eliminar a última linha em branco do callback do `forEach`. É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código.

Também é desejável que haja uma separação da invocação do `event.preventDefault()` do código que vem abaixo dele (há não ser em casos onde o bloco tenha apenas 2 linhas):

```javascript
$form.addEventListener('submit', event => {
  event.preventDefault()
  
  let score = 0;

  const userAnswer = [
    $form.inputQuestion1.value,
    $form.inputQuestion2.value,
    $form.inputQuestion3.value,
    $form.inputQuestion4.value,
  ]

  // ...
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
@JuniorAlvesbr, vou fechar a issue mas no que precisar, é só abrir uma nova =)
