### ISSUE TITLE
Resumo da Aula Array 03 da etapa 02

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1519]
/* Para que utilizamos Array?
- Utilizamos para armazenar um lista de valores que geralmente 
tem uma relação entre si, podemos armazenar 
uma lista de números, de string etc...

*/

//Array de String
```js
let heroes = ['Batman', 'Catwoman', 'Iron Man'] 
heroes[2] = 'Spider-Man' // Atribuindo valores no Array

console.log(heroes)
console.log(heroes[0]) // Acessando pelo index
```
// Array de números
```js
const ages = [31, 25, 39, 40]

console.log(ages)
console.log(ages[2]) // Acessando pelo index
```
//Métodos Array

// length retorna a quantidade de item que o Array tem
```js
console.log(heroes.length) 
```
 /* 
 join - retorna uma nova string  com todos os item do Array 
 concatenado e separado por virgula, o join pode receber um
 argumento opcional, um separador.

 exemplo: const joinhHeroes = heroes.join('_')
*/
```js
const joinhHeroes = heroes.join()
console.log(joinhHeroes)
```
/* 
IndexOf - retorna a primeira ocorrência passada no argumento, caso seja
passado no argumento um item que não exista no Array 
o número -1 será retornado

*/
```js
const indexOf25 = ages.indexOf(25)

console.log(indexOf25)
```
/* 
Concat - junta dois Array, o método concat não modifica o Array original

*/
```js
const moreHeroes = heroes.concat(['Superman', 'Wolverine'])
console.log(moreHeroes)
```
/* 
Push - adiciona um nono item no final do Array,
 e retorna o tamanho do Array, 
esse método modifica o Array original

*/
```js
const pushToHeroes = heroes.push('Cyclops', 'Hulk')
console.log(pushToHeroes)
console.log(heroes)
```
/*
Pop - remove o último item do Array e retorna o item removido, 
ele foi executado e se tornou um container que guarda o ultimo item do Array.
O método Pop modifica o Array original.

*/
```js
const popHeroes = heroes.pop()

console.log(popHeroes)
console.log(heroes)
´´´

<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @AdrianoRepet, rumo à fluência! 🚀
