### ISSUE TITLE
Resumo da Aula Numbers da etapa 1

### ISSUE THREAD

**Issue by kaiansamuel** [roger-melo-treinamentos/curso-de-js-roger-melo#152]
Numbers

Nem todo número é uma Number em JavaScript, pois, se ele tiver sido declarado entre aspas é uma string como qualquer outra, então sabemos que não é necessário colocar aspas para declarar um Number em uma variável.
Exemplo:

let idade = 39
console.log(typeOf(idade))
//number

let idadeS = ‘39’
console.log(typeOf(idadeS))
//string

Em JavaScript os Numbers são divididos entre inteiros e decimais. Inteiros são números sem separação de vírgula ou ponto, já os decimais são o exato inverso. Eles são possuem separação por vírgula ou ponto
Exemplo:

// Inteiro
let conta = 1000

//Decimal
let contaD = 1000.00

Operadores Aritméticos

Como já vimos os operadores aritméticos são os mesmos usados nas operaçãos convencionais da matemática, mudando somente os símbolos usados:

“+” - Soma ou concatena
“-” - Subtrai
“*” - Multiplica dois números ou mais
“/” - Divide dois número ou mais
“%” - Resto da divisão
Exemplo:

const reminder = 5 % 2
console.log(reminder)
// 1

A const reminder dividiu 5 por 2, o resto desta operação é 1. Isso muito proveitoso para descobrirmos por exemplo se o número é par ou ímpar.

“**” - Eleva ao expoente
Exemplo:

const level = 5 ** 2
console.log(level)
//25

Ou seja a const level elevou 5 à potência 2.

Ordem das Operações

A Ordem das operações em JavaScript segue a mesma ordem das operações da matemática convencional, sendo realizado primeiro os parênteses, depois os expoentes e raízes, e, terceiro divisão e multiplicação e por último adição e subtração.
Exemplo:

const operation = 8 * (10 -9) ** 3
console.log(operation)
//8

Nesse caso acima primeiro ele realizou o (10 -9) que resulta 1, depois elevou à potência de 3 que é 1, depois multiplicou por 8, resultando em 8.

Operadores de Incremento e Decremento

Se eu quiser atribuir a uma variável mais um número eu posso fazer de duas formas.

let barbecue = 3
barbecue = barbecue +1
//4

Ou:

barbecue += 1
//5

Para isso foi incorporado o Operador de Incremento, para fazermos referência ao acréscimo usamos o sinal de acréscimo “+” duas vezes. A cada vez que isso acontecer ele sera incrementado uma vez.
Exemplo:

barbecue++
//6

E cada vez que ela for passada vai acrescer um a mais.

Para Decrescermos temos que usar o operador de decremento, no caso o “-”, da mesma forma:

barbecue--
//5
Para incrementarmos ou decrementarmos mais do que de 1 em 1, temos que voltar a segunda alternativa de decremento, assim:

barbecue += 5
//10

Decremento:

barbercue -= 5
//5

Operador Nan (Não é um número)

Exemplo:

console.log(15 * ‘oi’)
//nan

Uma observação á ser feita é que o resultado de uma concatenação com string sempre resultará em uma string.
Exemplo:

const role = ‘Eu fui à’ + barbecue + ‘churrascos no mês passado’
console.log(role)
//’Eu fui à 5 churrascos no mês passado’.

Para isso foi criado a “Template Strings”, que concatena de forma mais agradável o código. Para usarmos a Template Strings é necessário usarmos a crase, depois o cifrão “$” e depois os colchetes { }, para inserirmos a variável.
Exemplo:

const rolets = `Eu fui à ${barbecue} churrascos no mês passado`
console.log(rolets)
//eu fui à 5 churrascos no mês passado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @kaiansamuel! 🚀
