### ISSUE TITLE
Resumo da Aula Adicionando to-dos - Aula 01-03 da etapa 09

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1522]
O método `trim()` serve para retirar os espaços no início e no fim de uma *string*. Este método acaba ajudando de certa forma na validação de dados, onde quando um *input* seja de preenchimento obrigatório, seja validado corretamente caso o usuário digite apenas espaços no *input*. Então o método `trim()` retira o excesso de espaços, passando somente caracteres digitados.

O método `reset()` restaura elementos de um *form* para o valor *default*. É bastante útil quando, após enviar os valores de um formulário para serem salvos, os *inputs* precisem ser limpos para que novas informações sejam inseridas.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🚀
