### ISSUE TITLE
Etapa 04, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1524]
```
Crie um objeto "cat" que possui as seguintes propriedades:
...
...
..
.
- sound, que é um método que retorna o miado do gato.
```

como ficaria pra passar essa função em uma arrow function?

```js
  sound: function () {
    return 'mewowww'
  }
  ```

eu tentei
```js
sound: () => 'mewowww'
```

mas retornou diferente no console.log

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Pra ser mais preciso sobre o problema em seu código, eu preciso vê-lo por completo. 

Mas no geral, a forma de declaração e execução de uma arrow function como método é assim:

```javascript
const cat = {
  sound: () => 'meowwww'
}

console.log(cat.sound()) // meowwww
```

Ficou mais claro?

**Comment by dracoalv** [comment]
ficou sim, obrigado!
