### ISSUE TITLE
Etapa 05-02, nome do vídeo: Correção dos exercícios da aula 04 da etapa 11 

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1525]
Boa tarde Roger , minha duvida é a seguinte porque que eu posso retornar um objeto de um map( )
desta forma :
```js
const newBrasil = brasil.map((element,index)=>{
  return {id : index, estado : element}
})
```
O objeto é inserido normalmente no novo array criado, e já quando preciso retornar ele fazendo um distructuring desta forma eu tenho que colocar parênteses  ?

```js
const setArrayNewBrasil = newBrasil.map(({id, estado}) =>
 ({id: id+1, estado: `${estado} pertence ao Brasil.`}))
```
Se eu simplesmente retornar o elemento e tirar o parênteses depois do retorno ```js=>``` da um erro 
```js
const setArrayNewBrasil = newBrasil.map(({id, estado}) => {id: id+1, estado: `${estado} pertence ao Brasil.`})
```
Uncaught SyntaxError: Unexpected token ':'
Espero ter sido claro , obrigado !
Boa tarde...
```
<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Quando uma arrow function retorna apenas uma expressão, é possível usar a sintaxe de concise body dela. Vc pode ver isso no tópico "Function body" [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#function_body). 

Essa sintaxe faz com que o return seja implícito:

```javascript
const getResult = () => 1 + 1

console.log(getResult()) // 2
```

Eu mencionei esse tipo de retorno pela primeira vez aos 20 minutos [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1012887).

Porém, quando uma arrow function que tem um concise body precisa retornar um objeto, observe que se você executar o código abaixo, o resultado será `undefined`:

```javascript
const getObj = () => { 
  prop: 'value' 
}

console.log(getObj()) // undefined
```

Isso aconteceu por que as `{}` após a `=>` estão sendo interpretadas como chaves que abrem e fecham o bloco da função, e não como um objeto. 

Como toda função em JS que não retorna um valor retorna `undefined` por baixo dos panos (e dentro da `getObj` não existe um `return`), a invocação dessa função retorna `undefined`.

Observe também que se vc repousar o mouse sobre `prop`, verá `Unused label.ts(7028)`. Não recomendo pesquisar à fundo sobre isso, não vai te ajudar muito nesse momento. Apenas saiba que a linha `prop: 'value'` está sendo ignorada.

Pra que as chaves sejam de fato interpretadas como um objeto, basta envolvê-las com o [grouping operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping) (parênteses):

```javascript
const getObj = () => ({ 
  prop: 'value' 
})

console.log(getObj()) // { prop: 'value' }
```

Esse é o motivo de ter que envolver o objeto retornado em parênteses: as `{}` precisam ser interpretadas como objetos, e não como o bloco da função.

Já no exemplo que vc deu abaixo:

```javascript
const setArrayNewBrasil = newBrasil.map(({id, estado}) => {id: id+1, estado: `${estado} pertence ao Brasil.`})
```

`id: id + 1,` está sendo ignorada e se vc repousar o mouse sobre `:` de `estado:`, a mensagem `';' expected.ts(1005)` é exibida. Se vc substituir o `:` por ponto e vírgula, a linha é ignorada, o erro não é mais lançado e `[ undefined, undefined ]` é retornado (devido à função não retornar valores).

Ficou mais claro?

Ah, tome cuidado com a formatação. 

Prefira deixar explícito na primeira linha que o retorno é um objeto, como mostrado abaixo, ok? =)

```javascript
const setArrayNewBrasil = newBrasil.map(({ id, estado }) => ({
  id: id + 1, 
  estado: `${estado} pertence ao Brasil.`
}))
```

**Comment by jhow221318** [comment]
Ótimo , muito boa a explicação intendi.
Obrigado boa tarde ...

**Comment by Roger-Melo** [comment]
Show @jhow221318. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
