### ISSUE TITLE
Resumo da Aula 02/ 02 a 06 da etapa 01

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#1529]
Resumo feito em cima do roteiro dos exercícios. 

https://user-images.githubusercontent.com/88742275/129627276-227fa329-d062-4b6c-b59f-2dcb3d557a3c.mp4

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @shazenn, rumo à fluência! 🚀
