### ISSUE TITLE
Resumo da Aula 01-02,03,04 e 05 da etapa 06

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#1533]
## Aula 01-02 - Eventos em formulários

- Formulários existem para capturar informações do usuário
- Para captura essas informações usamos eventos
- Eventos de Envio - Submit events
- Eventos de Teclado - Keyboard event
- Também utilizamos expressões regulares para validar as informações inseridas no formulário.

---

## Aula 01-03 - Evento Submit

- O envio das informações é aguardado pelo formulário(tag <form>) e não pelo botão.
- Prevenir a página de recarregar ao enviar o formulário (**event.preventDefault()**)

**HTML EXEMPLO**

```jsx
<body>
  <h1>O Evento Submit Aula 01-03</h1>

  <form class="signup-form">
    <input type="text" id="username" placeholder="username" autofocus>
    <button>Enviar</button>
  </form>

  <script src="./aula01-03.js"></script>
</body>
```

**Maneiras de se acessar o valor do que foi digitado.**

```jsx
const form = document.querySelector(".signup-form");
const usernameInput = document.querySelector("#username")

form.addEventListener("submit", (event) => {
  event.preventDefault();
  //armazenando na variável adquirida pelo ID do input
  console.log(usernameInput.value);
});

//OU

const form = document.querySelector(".signup-form");
~~const usernameInput = document.querySelector("#username")~~

form.addEventListener("submit", (event) => {
  event.preventDefault();
  //usando referencia do form para o ID do input
  console.log(form.username.value);
});

//OU

const form = document.querySelector(".signup-form");

form.addEventListener("submit", (event) => {
  event.preventDefault();
  //usando target do event e o ID do input
  console.log(event.target.username.value);
});

```

---

## Aula 01-04 - Expressões Regulares

**Lista de expressões regulares MDN**

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

- **Site para testar Regex**

[https://regex101.com](https://regex101.com) → Mudar para ECMA Script (Javascript)

- **Um expressão regular começa e termina com " / "**

```jsx
//Nenhum caracter antes
^
//Nenhum caracter depois
$ 

//Uma única palavra
/^palavra$/

//Qualquer caracter de A a Z
/^[ a - z]$/

//Qualquer caracter incluindo letras maíusculas
/^[ a - zA - Z]$/

//Qualquer palavra incluindo letras maíusculas, com 6 a 10 caracteres 
/^[ a - zA - Z] {6, 10}$/

//Qualquer palavra incluindo letras maíusculas e numeros com 6 a 10 caracteres
/^[ a - zA - Z 0 - 9] {6, 10}$/

//Qualquer com 6 a 10 caracteres
/^.{6, 10}$/
```

---

## Aula 01-05 - Testando padrões regex

- **Método Test()**

Tenta dar um match entre a regex e a string que passamos como parâmetro de invocação dele, retorna um boolean. É o método mais usado.

```jsx
const username = "davibernardo";
//pelo menos 6 letras, sem limite máximo, sem nada antes ou depois.
const pattern = /^[a-z]{6,}$/;
const isAMatch = pattern.test(username);

if (isAMatch) {
  console.log("O teste de regex passou.");
} else {
  console.log("O teste de regex NÃO passou.");
}
//O teste de regex passou.
```

- **Método Search()**

Tenta dar um match entre a string e a regex passada como parâmetro, retorna um numero com a posição do index onde esse match acontece. Caso o match não acontecer retorna (-1).

```jsx
const username = "123davibernardo";
//pelo menos 6 letras, sem limite máximo.
const pattern = /[a-z]{6,}/;

const result = username.search(pattern)
console.log(result)
//3 (index da 1ª letra da var username.)
```

- **Limpar o form após o envio**

```jsx
input.value = ''
```

- **Manter o foco no formulário após envio.**

```jsx
input.focus()
```

<hr>

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @davidtheblane, rumo à fluência! 🚀
