### ISSUE TITLE
Etapa 2, nome do vídeo: Correção dos Exercícios

### ISSUE THREAD

**Issue by luizfrodrigues** [roger-melo-treinamentos/curso-de-js-roger-melo#1534]
Olá Roger, tudo bem?

Na resolução do exercícios verifiquei que em alguns exercícios a condição avaliada as vezes vem antes da operação de iteração e as vezes vem depois da iteração.
Exemplos:

```
for (let i = 0; i < randomNumbers.length; i++) {
  const sumGreaterThanLimit = sumOfRandomNumbers > limit;

  if (sumGreaterThanLimit) {
    break;
  }

  sumOfRandomNumbers += randomNumbers[i];
}

```

```
for (let i = 0; i < randomNumbers.length; i++) {
  const sumGreaterThanLimit = sumOfRandomNumbers > limit;

sumOfRandomNumbers += randomNumbers[i];

  if (sumGreaterThanLimit) {
    break;
  }
```
Minha dúvida é o seguinte: há alguma diferença entre eu usar um caso ou outro? (Considerando que ambos me levam a mesma resposta).

Obrigado e excelentes aulas!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @luizfrodrigues!

Você se refere à posição da expressão `sumOfRandomNumbers += randomNumbers[i]`, certo?

Vou deixar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1494) uma issue em que eu respondo a essa dúvida. Recomendo que leia até o final, pois eu fiz uma tabela em que vc pode visualizar um panorama geral do que está acontecendo a cada execução do loop.

Se ainda restar qualquer dúvida, pode comentar aqui nessa issue que te ajudo =)

**Comment by luizfrodrigues** [comment]
Olá @Roger-Melo! Era essa dúvida mesmo. Eu só estava pensando na questão de se fazer um loop a mais no fluxo. A tabela esclareceu bastante. Obrigado!

**Comment by Roger-Melo** [comment]
Show @luizfrodrigues. No que precisar, é só abrir uma nova issue =)
