### ISSUE TITLE
Resumo da Aula For loop 01-03 da etapa 02

### ISSUE THREAD

**Issue by BrunoCesarAngst** [roger-melo-treinamentos/curso-de-js-roger-melo#1536]
# “For loop”
 — for (
	— **contador** — **executa uma vez** só um **valor inicial** de ponto de partida;
	— **condicional** — **se for true** o código dentro bloco **será executado**;
	— **incrementador** — no final de **cada rodada** o incrementador **é executo**
)

```js
const names = ['linus', 'Ada', 'Bill']

for (let i = 0; i < names.length; i++) {
  const HTMLTemplate = `<p>${names[i]}</p>`
  console.log(HTMLTemplate)
}

// names.length === 3
// 1º - <p>linus</p>
// 2º - <p>Ada</p>
// 3º - <p>Bill</p>
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @BrunoCesarAngst, rumo à fluência! 🚀
