### ISSUE TITLE
Resumo da Aulas 01, 02, 03, 04, 05 da etapa 01

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1537]
01 - Sou aspirante
02 - Comunicação com o browser através do JS. aprender os primeiros passos. básico html e css,
não vai ser fácil e jamais desista.
03 - configuração concluída
04 - Adicionando o script na página web, em qualquer lugar da tag head e body. observação para executar o js em um arquivo separado. igualmente como os arquivos css.
05 - A utilização do DevTools e o console.log() para a utilização na pagina, utilizar sempre enquanto estiver em desenvolvimento.
js e executado de cima para baixo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @carlosebs, rumo à fluência! 🚀
