### ISSUE TITLE
Resumo da Aula Um overview sobre tipos de dados - Aula 02-02  da etapa 01

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1538]
# Tipos de dados

### Dados de uma variável

Em JS existem 8 tipos de dados

1. Number: todos os tipos de números
2. Strings: cadeia de caracteres, textos (sempre dentro de aspas simples ou duplas)
3. Boolean: valores "verdadeiro (true)" ou "falso (false)" - usado para determinar se certas condições são verdadeiras ou falsas
4. Null: é uma forma de dizer que uma variável não tem valor
5. Undefined: parecido com o Null, mas o undefined é inserido automaticamente pelo JS e o Null é colocado pela pessoa que está programando
6. Object: são estruturas mais complexas de dados
7. Symbol: relacionado a objetos (será abordado mais a frente)
8. Bigint: usando para representar números inteiros muito grandes

Observe que as variáveis podem armazenar valores com diferentes tipos de dados e em JS não é necessário dizer de forma explícita qual tipo de dados a variável está armazenando porque o JS é uma linguagem de tipagem dinâmica :

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @JuFML, rumo à fluência! 🚀
