### ISSUE TITLE
Resumo da Aula 03 da etapa 01

### ISSUE THREAD

**Issue by emanuelcontinib** [roger-melo-treinamentos/curso-de-js-roger-melo#154]
**-----Arrays-----**
-São um tipo de dado que se enquadram como objeto;

`push()`
Para **adicionar** itens pra um array pode ser usado 
`array.push("argumentos", "itens")`

`array[]`
Para **atribuir** um novo valor na posição do array 
`array[X] = novo-valor `
Ou para **acessar** um item na posição do array. Dentro dos arrays pode-se passar qualquer expressão, por ex: `array[array.lenght - 1]`, irá mostrar o último item de qualquer array 
`array[X]`

`concat()`
Para **concatenar**  dois array 
`array1.concat(array2)`

`join()`
Para **retornar os arrays em um string** 
`array1.join(',')` retorna utilizando uma vírgula como sepador

`pop()`
Para **remover** itens do array. o retorno é o último item removido do array
`array.pop()`

`push()`
Para **adicionar** um item no array 
`array,push('adicione isso ao array')`

`slice()`
Para **obter parte** do array, primeira posição e última ou a partir de
`array.slice(0,1)` ou ainda `array[0][0]` 

`replace()`
Para **substituir** um item do array ou da string, passa-se o valor a ser substituido seguido do subtituto
`array.replace('mediano','fluente')`

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @emanuelcontinib! 🚀
