### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#1541]
# A palavra-chave this

A palavra-chave this é um objeto de contexto, ele representa o contexto no qual o código atual ta sendo executado. Dependendo de onde ou como o this foi usado, o valor dele pode mudar.

Se ele for usado na raíz do projeto, ele irá referenciar o contexto global, que é o window object.

No exemplo abaixo, a palavra-chave this irá referenciar o objeto user. Como o this está referenciando o objeto user, é possível acessar suas propriedades e métodos.

```js
let user = {
  name: 'João',
  age: 31,
  email: 'joaobernardo@gmail.com',
  login: function () {
    console.log('Usuário logado');
  },
  logout: function () {
    console.log('Usuário deslogado');
  },
  logName: function () {
    console.log(this.name); // João
  }
}
```

---

### O this tem comportamento diferente na arrow function

Quando o this é usado dentro de uma arrow function o valor do this sempre será o objeto window.

```js
let user = {
  name: 'João',
  logName: () => {
    console.log(this);
  }
}
```

Ou seja, quando o this for usado dentro de um método, se a gente quiser que o this referencie o objeto no qual o método está, a gente precisa usar uma function declaration ao invés de uma arrow function.

---

### Método com function declarations reduzido

```js
let user = {
  name: 'João',
  age: 31,
  logout: function() { ... },
  logout() { ... } // modo reduzido
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @rohyer. Rumo à fluência! 🙌🏻
