### ISSUE TITLE
Etapa 06, nome do vídeo: Eventos do teclado - Aula 02-03

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#1553]
Oi Roger! Espero que esteja tudo certo contigo =)

Minha dúvida de hoje é sobre como você referencia o elemento `input` dentro da callback do `eventListener` que monitora o teclado.  Quando você declara a variável que recebe o resultado do teste da regex, você referencia o `input` usando `event.target`. Logo abaixo isso muda: nas partes do código que atribuem as novas classes ao `input` você referencia o mesmo usando ` form.username`. 

Eu queria saber se essa mudança tem alguma razão de ser que eu acabei não entendendo, você pode me dar uma mão com isso, por favor?

Segue código pra facilitar o entendimento da dúvida:

```javascript
// pq usar:

form.username.addEventListener('keyup', event => {
    const isAValidUsername = testUsername(event.target.value)  // event.target aqui

    if (isAValidUsername) {
        form.username.setAttribute('class', 'success')  // mas form.username aqui
        return
    }
    form.username.setAttribute('class', 'error')  // e aqui também?
})
```

Segue também o código todo caso seja útil:

```javascript
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

const testUsername = username => /^[a-zA-Z]{6,12}$/.test(username) 


form.addEventListener('submit', event => {
    event.preventDefault()

    const isAValidUsername = testUsername( event.target.username.value)

    if (isAValidUsername) {
        feedback.textContent = 'Username valido =)'
        return
    }

    feedback.textContent = 'O username deve conter enter 6 a 12 caracteres e deve conter apenas letras'

})

form.username.addEventListener('keyup', event => {
    const isAValidUsername = testUsername(event.target.value)

    if (isAValidUsername) {
        form.username.setAttribute('class', 'success')
        return
    }
    form.username.setAttribute('class', 'error')
})
```

Muito obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende!

De fato, para referenciar o input, neste caso você pode usar apenas `event.target` ou apenas `form.username`. Os resultados são os mesmos:

```javascript
// apenas form.username usado
form.username.addEventListener('keyup', () => {
  const isAValidUsername = testUsername(form.username.value)

  if (isAValidUsername) {
    form.username.setAttribute('class', 'success')
    return
  }
  
  form.username.setAttribute('class', 'error')
})

// apenas event.target usado
form.username.addEventListener('keyup', event => {
  const isAValidUsername = testUsername(event.target.value)

  if (isAValidUsername) {
    event.target.setAttribute('class', 'success')
    return
  }
  
  event.target.setAttribute('class', 'error')
})
```

Na aula, eu mostrei com o `event.target` e `form.username` por dois motivos:

1. Por que eu quero que vc se acostume com o `event.target`. Quando vc começar a codar com um framework ou uma lib tipo o React, além de não selecionar elementos do DOM, quando vc trabalhar com forms, ao invés de usar o `querySelector` para obter o valor de um input, por exemplo, vc irá usar `event.target.value`. 

Você pode comprovar que não existe seleção de elementos do DOM com React [nessa pág.](https://reactjs.org/docs/forms.html) da doc. oficial.

Se abrir a página e pesquisar por querySelector nessa página, ou pesquisar no site todo, não existem ocorrências desse termo.

Então, quanto mais cedo você se acostumar a trabalhar com o `event.target`, mais rápido você vai se adaptar quando começar a trabalhar com uma lib como o react.

Esse é o primeiro motivo.

O segundo motivo é o seguinte...

2. Legibilidade

Eu acredito que no código abaixo,

```javascript
// apenas event.target usado
form.username.addEventListener('keyup', event => {
  const isAValidUsername = testUsername(event.target.value)

  if (isAValidUsername) {
    event.target.setAttribute('class', 'success')
    return
  }
  
  event.target.setAttribute('class', 'error')
})
```

demora um pouco mais compreender qual elemento `event.target` está referenciado se compararmos ao uso de `form.username` antes do `setAttribute`. 

Por isso eu escolhi fazer assim:

```javascript
form.username.addEventListener('keyup', event.target => {
  const isAValidUsername = testUsername(event.target.value)

  if (isAValidUsername) {
    form.username.setAttribute('class', 'success')
    return
  }
  
  form.username.setAttribute('class', 'error')
})
```

Dito isso, vc pode escolher se irá realmente padronizar com `event.target` ou `form.username` ou se prefere usar os dois nesse caso =)

Ficou mais claro?

**Comment by francisko-rezende** [comment]
Oi! Ficou claro sim, muito obrigado! :)

Aproveito o comentário pra te perguntar mais um coisinha: posso eu mesmo fechar eventuais issues de dúvida (clicando em 'Close with comment') quando a sua resposta já resolver a questão?

Obrigado mais uma vez e boa tarde!

**Comment by Roger-Melo** [comment]
Show @francisko-rezende. 

> #### Aproveito o comentário pra te perguntar mais um coisinha: posso eu mesmo fechar eventuais issues de dúvida (clicando em 'Close with comment') quando a sua resposta já resolver a questão?

Não precisa se preocupar com isso não. Quando eu fecho tenho que fazer umas paradas com as tags da issue. Fique tranquilo xD

E no que precisar, é só abrir uma nova issue =)
