### ISSUE TITLE
Etapa 5, nome do vídeo: Aula 01-06 O que é DOM

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#1554]
### Boa noite, professor!!

Na aula foi dito algo tipo "Uma vez que o documento é carregado na página no browser, este cria um objeto  (chamado
**_document_**) que modela  esse documento.

Gostaria de saber a diferença entre DOM e **_document_**, porque não ficou muito claro pra mim a diferença entre eles
 mesmo depois de ler os artigos relacionados no MDN.

Obrigada!!
Elaine

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

O `document` representa qualquer página web carregada no navegador e serve como um ponto de entrada para a árvore do DOM.

Isso significa que quando vc executa `document` no console do navegador e vê `> #document`, quando vc clica na setinha, o que vc está vendo é uma representação visual (em HTML) do DOM. 

Porém, quando você executa `console.dir(document)` no console do navegador, o que você vê agora é o objeto `document` por baixo dos panos. Ou seja, o `document` é o objeto que o browser cria, que chamamos de DOM, que nada mais é do que um objeto que representa o documento da página que foi carregada no navegador =)

Ficou mais claro?

Existe uma explicação um pouco mais técnica e complexa para isso (como vc viu [na doc](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction)), pq na verdade o DOM é uma API. Você verá o que é uma API na etapa 11, então por enquanto, recomendo que não se preocupe tanto em entender isso à fundo agora. Não vai te ajudar muito. A definição de DOM que eu disse acima é uma abstração para que vc tenha uma boa ideia do que se trata e continue a jornada se preocupando apenas com o que faz sentido para o seu momento =)

**Comment by ElaineDelgado** [comment]
ok, professor, Obrigada!!! 
Vou aguardar as próximas etapas para um maior entendimento geral!

**Comment by Roger-Melo** [comment]
Show @ElaineDelgado. No que precisar, pode abrir uma nova issue que te ajudo, combinado? =)

**Comment by ElaineDelgado** [comment]
Combinado!!
Muito obrigada!!
