### ISSUE TITLE
Resumo da Aula 02- 05 da etapa etapa 01

### ISSUE THREAD

**Issue by AleCarraDev** [roger-melo-treinamentos/curso-de-js-roger-melo#1555]
![WhatsApp Image 2021-08-17 at 20 34 17 (2)](https://user-images.githubusercontent.com/88162484/129816043-5449e79e-5592-4cf6-acef-d85ae26afd54.jpeg)
![WhatsApp Image 2021-08-17 at 20 34 17 (1)](https://user-images.githubusercontent.com/88162484/129816050-db511c34-deb5-4b0b-9738-32fd778f883c.jpeg)
![WhatsApp Image 2021-08-17 at 20 34 17](https://user-images.githubusercontent.com/88162484/129816052-b5b5273f-4dc5-4c64-88b1-e57e2a228313.jpeg)
![aula 02-05 etapa1](https://user-images.githubusercontent.com/88162484/129816137-f659b313-f712-4aff-94b0-3d00af692ca1.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @AleCarraDev. Rumo à fluência! 🙌🏻
