### ISSUE TITLE
Resumo da Aula Removendo to-dos - Aula 02-02 da etapa 09

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1558]
Para remover itens de uma lista, onde podem ser adicionados mais itens dinamicamente, utilizamos a abordagem *event delegation*, onde ao invés de atribuir eventos aos itens, atribuímos a `<ul>`, e identificamos o item clicado através do `event.target`.  Primeiro obtemos a referência da `<ul>`. Em seguida adicionamos um escutador de eventos de *click*. Como na lista há um ícone de lixeira e o item é removido apenas se for clicado neste ícone, devemos identificar o ícone através de uma classe, que no caso é a classe *delete*. Após criar uma condicional onde faremos algo apenas se o item clicado tiver a classe *delete* em sua `classList`, bastaria utilizar o `parentElement` para identificar o elemento pai do clicado, para aí sim removê-lo através do método `remove()`. No exemplo abaixo não irei me atentar a nomes de constantes, apenas na implementação do que o código deve fazer. Vamos ver na prática como ficaria:

```jsx
const ul = document.querySelector('ul');

ul.addEventListener('click', event => {
	const clickedElement = event.target;

	if (Array.from(clickedElement.classList).includes('delete')) {
		clickedElement.parentElement.remove();
	}
});
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Rumo à fluência! 🙌🏻
