### ISSUE TITLE
Etapa 2, nome do vídeo: 1-03/1-04

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#1561]
Olá professor, em relação a matéria em si não tenho duvidas, acontece que durante os exercícios de for/while loop eu fui fazer algumas pesquisas e em alguns sites aparecia a palavra **"println"** e queria saber o significado pois não encontrei uma resposta.
vi essa palavra por esse [link](https://www.clubedohardware.com.br/topic/1262418-array-com-sa%C3%ADda-em-caixa-alta-utilizando-touppercase/
![Captura de tela 2021-08-18 121212](https://user-images.githubusercontent.com/85198581/129924075-5bb8ae82-f5ed-4997-9976-1eecf6136f6d.png)
)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

`println` é um método do Java.

Java e JavaScript são linguagens diferentes, embora tenham nomes parecidos.

Além de ficar atento à diferença nos nomes, recomendo que pesquise no [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript). Ele é a sua fonte da verdade quando o assunto é JavaScript.

Eu falei sobre isso [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Sugiro que veja novamente, mas desta vez, com muita atenção pois lá eu falo o passo a passo do caminho que você precisa seguir no CJRM.

Se rolar dúvida, digite no google o assunto que vc precisa pesquisar e, em seguida, a palavra MDN. Exemplo: "for MDN". Sempre prefira a versão em inglês, você pode mudar a linguagem em um link que geralmente fica no canto superior direito da página:

![link-mdn](https://user-images.githubusercontent.com/29297788/129932905-140b3da6-9c2a-42dc-a40c-6ff8b492da1d.jpg)

Consumir o MDN em inglês evita que vc perca informações que não foram traduzidas para pt-BR. Se tiver dificuldades, use o google tradutor. 

E no que precisar, pode abrir issues aqui que te ajudo =)

Mais uma observação: os exercícios que vc precisa fazer estão no CJRM. Não sei se foi o caso, mas não procure exercícios fora. Eles não vão te ajudar, pelo contrário, a probabilidade é que eles te confundam e atrapalhem sua jornada pra chegar na fluência. [Vários alunos estão tendo resultados](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo#depoimentos-de-alunos) seguindo o mesmo treinamento que vc tem acesso.

Confia no processo e foca no CJRM. Ele é o seu GPS para a fluência =)

**Comment by Roger-Melo** [comment]
@CarlosHenrique2208, vou fechar a issue mas no que precisar, é só abrir uma nova =)
