### ISSUE TITLE
Resumo da Aula Xxxxxxxxx da etapa XX

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#1563]
[Ex03 Etapa01.docx](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7009326/Ex03.Etapa01.docx)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @shazenn. 

Não esquece de colocar o título na issue =)

Rumo à fluência! 🙌🏻
