### ISSUE TITLE
Etapa 2, Correção dos Exercícios - Aula 03-04

### ISSUE THREAD

**Issue by djailtim** [roger-melo-treinamentos/curso-de-js-roger-melo#157]
Roger, bom dia.

Não são dúvidas relacionadas diretamente aos exercícios, mas estou precisando de ajuda.

Leio a atividade, interpleto, porém quando vou resolver travo:

1 - Fico pensando em que nome colocar em variáveis (acredito ser TOC), não consigo aceitar qualquer nome e maioria das vezes não chego a uma conclusão, mudo várias vezes até chegar em algo... ainda assim não fico tão satisfeito, acabo tendo que ir ver a solução de exercício pra ver o que você colocou... poderia me dar sugestões de como tentar solucionar isso?

2 - Maioria das vezes não consigo pensar em uma lógica de solução de cada exercício, como posso melhorar minha lógica... assim como o problema citado assim, penso em várias soluções, faço de uma forma, não fico satisfeito, refaço de outro jeito... No fim quando vejo a sua solução, fica tudo mais simples, vejo que psicologicamente não fico bem com isso rsrs... o que fazer?

PS: sei que não são dúvidas ligadas diretamente aos exercícios, mas eu quero melhorar nisso... também sou muito ansioso, tenho tentado melhorar nisso...

Desde já muito obrigado Roger.

Suas aulas são um espetáculo, muito obrigado por compartilhar todo esse conhecimento conosco.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ailton.

> 1 - Fico pensando em que nome colocar em variáveis (acredito ser TOC), não consigo aceitar qualquer nome e maioria das vezes não chego a uma conclusão, mudo várias vezes até chegar em algo... ainda assim não fico tão satisfeito, acabo tendo que ir ver a solução de exercício pra ver o que você colocou... poderia me dar sugestões de como tentar solucionar isso?

Verifiquei que você acabou de entrar na etapa 3. Suas variáveis devem ter bons nomes, mas essa não é a prioridade agora. Por enquanto, apenas saiba que nomes de variáveis devem ser substantivos e nomes de funções devem ser verbos. Mas não foque muito em ir além disso agora. Você ainda está no começo do treinamento, nomear bem vem com a prática e o tempo.

> 2 - Maioria das vezes não consigo pensar em uma lógica de solução de cada exercício, como posso melhorar minha lógica... assim como o problema citado assim, penso em várias soluções, faço de uma forma, não fico satisfeito, refaço de outro jeito... No fim quando vejo a sua solução, fica tudo mais simples, vejo que psicologicamente não fico bem com isso rsrs... o que fazer?

No começo, eu recomendo que as resoluções dos seus exercícios sejam idênticas às minhas. Geralmente, a forma que resolvo os exercícios contém princípios que serão potencializados nas aulas seguintes.

Para que as resoluções dos seus exercícios sejam idênticas às minhas, vou deixar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/78#issuecomment-721458855) o passo a passo de uma revisão que recomendo que você faça. Ela te deixará mais afiado para o que está por vir.

Se algo que eu disse não ficou claro ou não fez sentido, é só dar o toque =)

@djailtim

**Comment by wsn-nunes** [comment]
Fala Ailton , tudo bem cara? 
a sua segunda situação , é praticamente a minha . tenho as mesmas dúvidas . mas mesmo assim eu ainda sou um cara bem persistente até ver a resposta final do professor ...
e a sua dúvida veio na mesma aula em que eu também estou , mas como o roger sabe muito ele tem sempre uma solução pra gente .... um grande abraço . e não desista . essa é a parte mais difícil o resto é moleza , espero kkkkk.

**Comment by djailtim** [comment]
> Fala Ailton , tudo bem cara?
> a sua segunda situação , é praticamente a minha . tenho as mesmas dúvidas . mas mesmo assim eu ainda sou um cara bem persistente até ver a resposta final do professor ...
> e a sua dúvida veio na mesma aula em que eu também estou , mas como o roger sabe muito ele tem sempre uma solução pra gente .... um grande abraço . e não desista . essa é a parte mais difícil o resto é moleza , espero kkkkk.

Pois é, desistir não está entre as opções meu amigo hehe... Vamos que vamos...

**Comment by djailtim** [comment]
> Oi Ailton.
> 
> > 1 - Fico pensando em que nome colocar em variáveis (acredito ser TOC), não consigo aceitar qualquer nome e maioria das vezes não chego a uma conclusão, mudo várias vezes até chegar em algo... ainda assim não fico tão satisfeito, acabo tendo que ir ver a solução de exercício pra ver o que você colocou... poderia me dar sugestões de como tentar solucionar isso?
> 
> Verifiquei que você acabou de entrar na etapa 3. Suas variáveis devem ter bons nomes, mas essa não é a prioridade agora. Por enquanto, apenas saiba que nomes de variáveis devem ser substantivos e nomes de funções devem ser verbos. Mas não foque muito em ir além disso agora. Você ainda está no começo do treinamento, nomear bem vem com a prática e o tempo.
> 
> > 2 - Maioria das vezes não consigo pensar em uma lógica de solução de cada exercício, como posso melhorar minha lógica... assim como o problema citado assim, penso em várias soluções, faço de uma forma, não fico satisfeito, refaço de outro jeito... No fim quando vejo a sua solução, fica tudo mais simples, vejo que psicologicamente não fico bem com isso rsrs... o que fazer?
> 
> No começo, eu recomendo que as resoluções dos seus exercícios sejam idênticas às minhas. Geralmente, a forma que resolvo os exercícios contém princípios que serão potencializados nas aulas seguintes.
> 
> Para que as resoluções dos seus exercícios sejam idênticas às minhas, vou deixar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/78#issuecomment-721458855) o passo a passo de uma revisão que recomendo que você faça. Ela te deixará mais afiado para o que está por vir.
> 
> Se algo que eu disse não ficou claro ou não fez sentido, é só dar o toque =)
> 
> @djailtim

Obrigado Roger,
Vou tentar não me preocupar com nomes agora rsrsrs...

Muito obrigado pelo apoio, vou seguir o passo a passo que você deixou o link...

**Comment by Roger-Melo** [comment]
Excelente @djailtim. Já que ficou mais claro, vou fechar a issue. Mas no que precisar, é só abrir uma nova =)
