### ISSUE TITLE
Etapa 4, Correção dos exercícios da aula 01 - Aula 02-01: 07

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1572]
Olá Roger,

Não entendi tecnicamente por que mesmo se não passar os **objetos** como parâmetros da função ```getAgeMenssage()``` e apenas interpolando ```${cat.name}``` e ```${dog.name}``` tem o mesmo comportamento. Isso ocorre por que estamos trabalhando no mesmo aquivo que os objetos cat e dog foram criados?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @paulovieiradasilva.

Poste todo o código na issue. Assim eu consigo entender o que está acontecendo no seu código e ajudar com mais precisão =)

**Comment by ElaineDelgado** [comment]
Fiquei curiosa sobre esse tópico, espero que seja permitido comentá-lo.
Acho que entendi a dúvida do @paulovieiradasilva .
Modifiquei meu código e vou mostrar como foi corrigido e a modificação que fiz para teste.

### Igual à correção:

```js
const cat = {
  name: 'Grampo',
  age: 6,
  color: 'preto',
  bestFriends: ['salsicha', 'bica'],
  sound: function() {
    return 'meooowww'
  }
}
const dog = {
  name: 'Milk',
  age: 8,
  color: 'white, light brown',
  bestFriends: 'Preta, Rebeca',
  sound: () => 'woof'
}
const getAgeMessage = (cat, dog) => `A soma das idades de  ${cat.name} e ${dog.name} é ${cat.age + dog.age}`
console.log(getAgeMessage(cat, dog))
```
Acima, os nomes dados aos  argumentos da função getAgeMessage são os mesmo nomes dos objetos, e por isso 
se retirarmos os argumentos e parmetros da função e da invocação dela, o código continua funcionando, pois 
cat.name está referenciando a propriedade name do objeto cat. 
Ou seja, a função abaixo também funciona:
```js
const getAgeMessage = () => `A soma das idades de  ${cat.name} e ${dog.name} é ${cat.age + dog.age}`
//não passando parâmetro na função
```

### Modificação que fiz mudando os nomes dos argumentos.
A seguinte função já não funcionaria sem passar os argumentos, pois obj1 e obj2 não existem como objetos, são apenas 
parâmetros.

const getAgeMessage = (obj1, obj2) => `A soma das idades de  ${obj1.name} e ${obj2.name} é ${obj1.age + obj2.age}`
console.log(getAgeMessage())
```

Não sei se deu para entender, mas acho que a dúvida do Paulo foi essa, estou acompanhando a thread pra saber se é isso emsmo
e poder ver a explicação do professor.

**Comment by Roger-Melo** [comment]
Boa @ElaineDelgado!

Se a dúvida do @paulovieiradasilva for essa, é como vc descreveu mesmo =)

Então, respondendo a pergunta...

> ### Isso ocorre por que estamos trabalhando no mesmo aquivo que os objetos cat e dog foram criados?

Sim. Mas tem mais um detalhe que faz com que as consts `cat` e `dog` possam ser acessadas na função `getAgeMessage`. E esse detalhe se chama **escopo**.

Os dois objetos foram criados em escopo global e, mesmo que estivessem em outro arquivo, seriam acessados na função. Olha só:

```html
<script src="./app.js"></script>
<script src="./app2.js"></script>
```

```javascript
// app.js
const cat = {
  name: 'Grampo',
  age: 6,
  color: 'preto',
  bestFriends: ['salsicha', 'bica'],
  sound: function() {
    return 'meooowww'
  }
}

const dog = {
  name: 'Milk',
  age: 8,
  color: 'white, light brown',
  bestFriends: 'Preta, Rebeca',
  sound: () => 'woof'
}

// app2.js
console.log(cat, dog)
// {name: "Grampo", ... }
// {name: "Milk", ... }
```

Ou seja, app2.js tem acesso às variáveis que foram declaradas em app.js.

Então se eu declarar a função em app2.js, ela irá acessar os objetos:

```javascript
const getAgeMessage = () => 
  `A soma das idades de ${cat.name} e ${dog.name} é ${cat.age + dog.age}`

console.log(getAgeMessage()) // A soma das idades de Grampo e Milk é 14
```

Porém, eu sinto que vc não deve se preocupar com escopos agora, por que você verá com detalhes o que são eles na **aula 01-03 da etapa 05**. Você está quase chegando lá =)

---

Já no exemplo abaixo, parecido com o que a Elaine deu:

```js
const getAgeMessage = (obj1, obj2) => `Olá, ${obj1.name} e ${obj2.name}`

console.log(getAgeMessage()) // Uncaught TypeError: Cannot read property 'name' of undefined
```

Os parâmetros `obj1` e `obj2` receberam `undefined` automaticamente, pois a invocação da função não recebeu os objetos como argumentos. 

Como `obj1` e `obj2` estão armazenando `undefined`, "Uncaught TypeError: Cannot read property 'name' of undefined" é exibido por que `undefined` não contém uma propriedade `name`.

Nesse caso, é possível evitar que os parâmetros recebam `undefined` declarando default parameters, como mostrado na aula 01-04 da etapa 03:

```javascript
const getAgeMessage = (obj1 = { name: 'Zé' }, obj2 = { name: 'João' }) => 
  `Olá, ${obj1.name} e ${obj2.name}`

console.log(getAgeMessage()) // Olá, Zé e João
```

Agora, como os parâmetros receberam por padrão objetos que contém uma propriedade `name`, se a função é invocada sem argumentos, `obj1.name` e `obj2.name` resultam em 'Zé' e 'João'.

Se a função recebe os objetos como argumentos, os default parameters são sobrescritos pelos objetos inseridos na invocação da função:

```javascript
const getAgeMessage = (obj1 = { name: 'Zé' }, obj2 = { name: 'João' }) => 
  `Olá, ${obj1.name} e ${obj2.name}`

// apenas obj1 recebe o objeto
getAgeMessage({ name: 'Joaquim' }) // Olá, Joaquim e João

// obj1 e obj2 recebem os objetos
getAgeMessage({ name: 'Joaquim' }, { name: 'David' }) // Olá, Joaquim e David
```

Se não tiver ficado claro é só dar o toque que explico de outra forma =)

**Comment by paulovieiradasilva** [comment]
Muito obrigado pela explicação @Roger-Melo e @ElaineDelgado!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
