### ISSUE TITLE
Resumo da Aula 02-06 (Template strings) da etapa 01

### ISSUE THREAD

**Issue by brunofarias** [roger-melo-treinamentos/curso-de-js-roger-melo#1574]
3 maneiras para incluir aspas dentro de uma string, 
- Incluir as aspas simples em uma string que tem abertura com aspas duplas
- Incluir aspas duplas em uma string que tem abertura e fechamento com aspas simples
- Escapar as aspas usando \

Template strings: Utilizado para injetar variáveis dentro da string

```js
const postTitle = 'Título'
const postAuthor = 'Bruno'
const postComments = 15
```
```js
const postMessage = `O post ${postTitle} do ${postAuthor} tem ${postComments} comentários `
console.log(postMessage)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @brunofarias. Rumo à fluência! 🙌🏻
