### ISSUE TITLE
Resumo 

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#158]
Boa noite! Esse é o link do repositório da calculadora que comentei na live. Poder da uma opinião agradeço! 

https://github.com/azulinho10/Calculadora 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rodrigo.

Parabéns pela aplicação =)

Antes de qualquer observação, saiba que o mais importante você já fez, que é fazer funcionar. Com a prática e o tempo no decorrer do treinamento, você terrá insights que farão você voltar nessa aplicação e lapidá-la aos poucos.

Com a prática e o tempo, você encontrará, por exemplo, formas de abstrair a repetição e código. Essas abstrações lhe ajudarão a declarar um pedaço de código uma vez e reusá-lo.

Vou dar um exemplo, de forma resumida.

No decorrer do treinamento, você conhecerá um o objeto event. Ele é um objeto que o browser disponibiliza nas funções de listeners de eventos. Por convenção, ele é declarado como `e`:

```javascript
function showNumberOnInput (e) {
  const clickedNumber = e.target.textContent

  inputNumeros += clickedNumber;
  guardarValor += clickedNumber;
  mostrarValor.value = inputNumeros;
}

btnUm.addEventListener("click", showNumberOnInput);
```

No código acima, a propriedade `target` armazena a referência do elemento no qual o evento aconteceu e a propriedade `textContent` armazena o conteúdo da tag HTML. Isso significa que quando `btnUm` é clicado, a expressão `e.target.textContent` resulta no número do botão que foi clicado e `clickedNumber` armazena esse valor.

Com isso, ao invés de repetir as declarações das funções para cada número, como abaixo,

```javascript
function numeroNove() {
  // ...
}

function numeroOito() {
  // ...
}
```

você pode eliminar todas as declarações das 9 funções dos números e apenas referenciar a `showNumberOnInput` nos listeners de eventos dos botões com os números.

```javascript
btnUm.addEventListener("click", showNumberOnInput);
btnDois.addEventListener("click", showNumberOnInput);
// ...
```

Essa é só uma das formas de abstrair repetições que você aprenderá no decorrer do treinamento. E claro, você conhecerá com muito mais detalhes nas aulas o event e essas propriedades que eu mencionei. Só dei um spoiler =)

Há um princípio para nomear bem variáveis e funções. Não fique preocupado em segui-lo à risca à qualquer custo agora, por que ele será intensificado conforme você avança. Mas é bom saber: nomes de funções devem ser verbos e nomes de variáveis/constantes devem ser substantivos. Seguindo esse princípio, você começa a ter uma direção mais clara de como deve preferir nomear.

Fique atento também a pedaços de códigos esquecidos na aplicação. Lembre-se de remover os debuggers e console.log (após usá-los). Há também duas declarações idênticas de funções de multiplicação, uma delas pode ser removida.

Lembrando: o mais importante você já fez (fazer funcionar). Conforme você for avançando no treinamento, você terá mais insights para melhorar o código. 

Se quiser mostrar as melhoras que fez no decorrer do tempo, vai ser massa ver essa evolução. Parabéns, novamente =)

@azulinho10

**Comment by azulinho10** [comment]
Obrigado pelo feedback, faço questão sim de mandar, conforme for evoluindo
no curso eu vou lapidar esse projeto, criando outros e os dos cursos também.


Em sex., 12 de fev. de 2021 às 23:15, Roger Melo <notifications@github.com>
escreveu:

**Comment by azulinho10** [comment]
Obrigado pelo feedback, faço questão sim de mandar, conforme for evoluindo
no curso eu vou lapidar esse projeto, criar outros também. Um Abraço, tem
bom final de semana. =)


Em sex., 12 de fev. de 2021 às 23:35, Rodrigo Morais <
rodrigosantosmath@gmail.com> escreveu:

**Comment by Roger-Melo** [comment]
Legal @azulinho10! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
