### ISSUE TITLE
Etapa 05, Correção dos exercícios da aula passada + destructuring em parâmetros de funções - Aula 04-01

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1584]
- 07
  - Se um clique no h1 acontecer, faça com que todos os elementos dentro do body 
    sejam removidos.

Minha resolução
```js
const body = document.body

h1.addEventListener('click', () => {
  const allElementsIntoBody = Array.from(body.children)
  
  allElementsIntoBody.forEach(element => {
    element.remove(element)
  })
})
```

A sua resolução
```js
const body = document.body

h1.addEventListener('click', () => {
  body.innerHTML = ''
  })
```

Minha dúvida é, eu deveria ter esses insights ou to estudando de forma errada?

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Minha dúvida é, eu deveria ter esses insights ou to estudando de forma errada?

Fique tranquilo, @dracoalv. Como eu já havia mencionado o `document.body` na aula 03-01 da etapa 05, esse exercício foi pra ver se vc de fato se lembrava dele. Sua solução ficou mais complexa apenas pq vc não se lembrou. Agora vc não esquece mais xD

Ps: tente não esquecer de colocar o nome do vídeo no título da issue =)

**Comment by dracoalv** [comment]
tudo bem, acho que preciso dar uma pausa nas aulas e revisar todos os meus resumos com calma para continuar seguindo o flow, suas aulas são ótimas!

sobre o título da issue, eu coloquei errado?

**Comment by Roger-Melo** [comment]
Se vc sentir que precisa, revise sim. E no que eu puder ajudar, pode contar comigo para tirar as dúvidas, ok? =)

O título da aula ficou como "x", mas relaxa, já consertei xD
