### ISSUE TITLE
Resumo da Aula Buscando e filtrando to-dos 02-03 da etapa 08

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1593]
@Roger-Melo
![Buscando](https://user-images.githubusercontent.com/35525950/130160879-373637bd-0415-41b2-8249-166eba27a750.jpeg)

**Comment by Roger-Melo** [comment]
Excelente @AnaCosta29. Rumo à fluência! 🙌🏻
