### ISSUE TITLE
Etapa 08, nome do vídeo: refatoração do to-do list

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#1594]
olá profesor,tudo bem? aqui a implementação dataset nao estou conseguindo fazer,mas a refatoração fez.posso colocar o codigo dessa forma ? obrigada!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Pode sim, @AnaCosta29. 

Só abrir uma issue do tipo "🔥Aplicação" e mandar ver =)

**Comment by Roger-Melo** [comment]
@AnaCosta29, vou fechar a issue mas no que precisar, é só abrir uma nova =)
