### ISSUE TITLE
Aplicação: Consumação da primeira API

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1598]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/jhow221318/Consumindo-API..git

### Maiores dificuldades durante a implementação

Foi tranquilo , só não consegui ver mais jeito de refatorar  sei que tem mas não consegui.

### Menores dificuldades durante a implementação

O  resto foi tranquilo.

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

No CJRM não existe uma aplicação que usa a API do Giphy.

As aplicações que podem ser analisadas são aquelas que eu listei [no email que você recebeu](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1311), ok? =)

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
