### ISSUE TITLE
Quiz interativo (resultado)

### ISSUE THREAD

**Issue by Dani-jardim** [roger-melo-treinamentos/curso-de-js-roger-melo#16]
Fiz uma versão com quiz com perguntas aleatórias, cada uma com 4 opções de resposta.

Quando li o exercicío achei que a parte mais fácil seria mostrar o resultado, mas me enganei, essa foi justamente a parte que tive maior dificuldade. Também fiquei confusa com o forEach por conta dos parâmetros passados 

Mas no geral fiquei bem feliz de ter conseguido e ver meu progresso.
Obrigada :)

Link do resultado: https://github.com/Dani-jardim/curso-de-js-roger-melo/tree/master/exercicio-19

**Comment by Roger-Melo** [comment]
Parabéns pelo projeto @Dani-jardim! 🎉

Duas pequenas observações:

**1. Tome cuidado com o excesso de linhas em branco.**

Linhas em branco delimitam a separação de responsabilidades do código, apenas uma é o suficiente.

Então no lugar de

```javascript
const resultQuiz = document.querySelector("div.result-quiz")


form.addEventListener('submit', event => {
    event.preventDefault()
    // ...
})
```

prefira assim:

```javascript
const resultQuiz = document.querySelector("div.result-quiz")

form.addEventListener('submit', event => {
    event.preventDefault()
    // ...
})
```

**2. Cuide da indentação**

Indentar uma linha de código evidencia a posição hierárquica dela.

Ao invés de fazer assim,

```javascript
form.addEventListener('submit', event => {
    event.preventDefault()
  
let score = 0
const userResponses = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,   
]
      
  userResponses.forEach ((userResponse, index) => {
    // ...
  })

  // ...
})
```

prefira indentar dessa forma:

```javascript
form.addEventListener('submit', event => {
    event.preventDefault()
  
    let score = 0
    const userResponses = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value,   
    ]
      
    userResponses.forEach ((userResponse, index) => {
        // ...
    })

    // ...
})
```

Novamente, parabéns pela aplicação =)

Nas próximas aulas você verá que iremos melhorar o código desse projeto.

Se você sentir que consegue construí-lo sozinha, inclusive com as refatorações que mostrarei, não hesite em fazer dele uma peça de seu portfólio.

Conte comigo para chegar à fluência. No que precisar, é só chamar aqui =)

**Comment by Dani-jardim** [comment]
Obrigada pelas dicas  =)

**Comment by Roger-Melo** [comment]
@Dani-jardim vou fechar a issue mas no que precisar é só dar o toque =)
