### ISSUE TITLE
Etapa 3, Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by wsn-nunes** [roger-melo-treinamentos/curso-de-js-roger-melo#160]
Boa noite, Professor Roger . tudo bem? 
Estou com uma dúvida .
Sim é uma dúvida , mas talvez seja um pouco pior que isso ... rsrs :D .

Vamos lá .

o Meu problema está na lógica na hora do desenvolvimento. As vezes a solução é tão óbvia que eu não consigo enxergar, fico procurando soluções difíceis e quando na verdade a solução parece ser bem simples . não sei se este é um problema comigo apenas ou se é com todos kkkkk.

abaixo segue um exercício passado com uma tentativa de solução sem ver as respostas.

```js
/*
 04

  - Concatene as strings do array abaixo, formando uma frase;
  - Se durante a concatenação a palavra "certeza" existir, ela não deve ser  
    concatenada;
  - Exiba a frase no console.
*/

const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']
let frase = " ";

for(let i = 0; i< sentence.length; i++){  
  
   if(sentence[i].includes("certeza")){
    frase += sentence[i];

      sentence.splice(1,1).pop();  

      console.log(frase)


    }
}


```

e o exercício 05 , eu não fiz , porém farei depois de ver a o resultado . 

quando você estava fazendo , as coisas foram ficando claras , porém quando eu tentei fazer , a lógica não veio na minha cabeça de forma simples . sempre busco soluções mais complexas ... 

é normal isso ???

Obrigado pela atenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi William!

Tudo em paz, e tu?

Proteja o processo e seja gentil com seus resultados. 

É natural sentir uma certa dificuldade quando estamos aprendendo algo novo. Por isso a recomendação é que você seja gentil com os resultados, mas proteja o processo. E o processo é: executar o método.

Vi que você leu o [passo a passo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/78#issuecomment-721458855) que recomendei em uma issue passada. Ele é a forma mais eficiente que eu conheço de fazer coisas difíceis para o cerebro ficarem automáticas.

E claro, quando surgirem dúvidas, pode abrir uma issue que te ajudo.

@wsn-nunes 

PS: sobre implementar soluções complexas, pode acontecer até com os mais treinados. Hoje mesmo aconteceu comigo =)

**Comment by wsn-nunes** [comment]
Esse processo de executar o método ele é de fato muito importante , tanto é que fiz isso revisando algumas aulas , depois que li o passo a passo .

Muito obrigado Professor ...

**Comment by Roger-Melo** [comment]
Isso mesmo @wsn-nunes. E em qualquer dificuldade na jornada rumo à fluência, conte comigo =)

Vou fechar a issue mas quando surgirem dúvidas, é só abrir uma nova =)
