### ISSUE TITLE
Resumo da Aula Controle de fluxo 01 da etapa 02

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1600]
O que é  controle de fluxo?

Conforme vamos avançando e começamos a criar códigos mais complexos,
vai existir momentos que teremos que decidir qual vai ser a parte do código
 a ser executada, também vai ter momentos que precisaremos executar uma 
parte do código varias vezes, o loop é uma das formas de controlar esse fluxo.
Loop é condicional fazem parte do conceito de  controle de fluxo em javaScript.

// Loop for

```js
for (let i = 0; i < 5; i++ ){

console.log(`Dentro do loop: ${i}`)

}

console.log('loop concluido!!')

```
// Loop com Array
```js
const names = ['Linus', 'Ada' , 'Bill']

for (let i = 0; i < names.length; i++) {

    const htmlTemplate = `<P>${names[i]}</P>`
    //console.log(names[i])

    console.log(htmlTemplate)
    
}
```
// Loop While

```js

let i = 0;

while ( i < 5){
   
    console.log(`Dentro do loop: ${i}`)
    i++

    }
    
    console.log('loop concluido!!')
 ```
// While com Array

```js

const names = ['Jobs', 'Hopper', 'Turing']

let i = 0

while (i < names.length) {

    console.log(names[i])

    i++
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @AdrianoRepet. Rumo à fluência! 🙌🏻
