### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1603]
# Operadores lógicos && e ||

Veremos agora quando executar um bloco de código quando há combinações de condições diferentes.

### Operador lógico && (operador e)

Usado quando as duas condições dentro do parêntese precisam ser verdadeiras ao mesmo tempo para executar determinado bloco de código.

**let password = 'oi123'**

**if** **(password > = 12 && password.includes ('1')) {**

**console.log ( 'senha muito forte' )**

**} else if (password > = 8)  {**

**console.log ( 'A senha tem 8 ou mais caracteres' )**

**} else {**

**console.log ( 'A senha deve conter 8 ou mais caracteres' )**

**}**

O bloco de código dentro da primeira chaves só vai ser executado se as duas condições que estiverem dentro do parêntese forem verdadeiras porque neste caso estamos usando o operador lógico && (e).

### Operador lógico || (operador ou)

Usado quando uma das duas condições dentro do parêntese precisam ser verdadeiras  para executar determinado bloco de código (não necessariamente as duas precisam ser verdadeiras ao mesmo tempo).

**let password = 'oi123'**

**if** **(password > = 12 && password.includes ('1')) {**

**console.log ( 'senha muito forte' )**

**} else if (password > = 8 || password.includes ('1'))  {**

**console.log ( 'A senha forte' )**

**} else {**

**console.log ( 'A senha deve conter 8 ou mais caracteres' )**

**}**

O bloco de código dentro da segunda chaves vai ser executado se pelo menos uma das duas condições que estiverem dentro do parêntese for verdadeira porque neste caso estamos usando o operador lógico || (ou).

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @JuFML. Rumo à fluência! 🙌🏻
