### ISSUE TITLE
Resumo da Aula 01-02 a 01-04 da etapa 03

### ISSUE THREAD

**Issue by lathne** [roger-melo-treinamentos/curso-de-js-roger-melo#1607]
### Functions

Fazem parte do tipo object. O papel principal é permitir que a gente crie um bloco de codigo que a gente pode invocar e executar quando a gente quiser. Uma forma possivel de interpretar uma função é pensar nela como uma caixa que contem um código dentro dela que faz uma coisa em particular.

**Function declaration**
As declarações de função são carregadas antes de qualquer código ser executado. São içadas para o topo do código. (hoisting)

**Function expression**
É a forma de criar uma função atribuindo ela a uma variavel.

As expressões de função são carregadas apenas quando o interpretador atinge essa linha de código.

##

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @lathne. Rumo à fluência! 🙌🏻
