### ISSUE TITLE
Resumo da Aula Arrayda etapa 1

### ISSUE THREAD

**Issue by kaiansamuel** [roger-melo-treinamentos/curso-de-js-roger-melo#161]
Array

Array é um objeto que serve para armazenar valores que se relacionam entre si. Desta forma é possível armazenar vários valores sem a necessidade de criar uma variável para cada. Para que isso seja possível é necessário usar colchetes e separar cada valor por vírgula.
Exemplo:

const arr = [10, 20, 30]

Ou podemos armazenar strings também:

const str = [‘Maria’, ‘Joana’, ‘Maura’]

Ou você pode criar com os dois tipos:

const crazyarr = [10, ‘Joana’, 20, ‘Maria]

Para acessarmos um item do array é necessário usarmos colchetes.
Exemplo:

console.log(crazyarr[0])
//10

Encontrar o comprimento de um array

Para encontrarmos o comprimento de um array é necessário usarmos o length.
Então:

console.log(crazyarr.length)
//4

Colocar um separador para cada item

Para colocarmos um separador com vírgula ou barra invertida entre os itens do array, temos que usar o método “join”.
Exemplo:
console.log(crazyarr.join(‘  ,   ‘))
//10 , Joana , 20 , Maria

O método “join” converte um array em uma string.

Outro método que retorna uma string é o toString().
Exemplo:
console.log(crazyarr.toString( ))
//10, Joana, 20, Maria

Procurar ocorrência
Para que possamos ter a última ocorrência de um valor dentro de uma string, temos que usar o método “indexOf”
Exemplo:

console.log(crazyarr.indexOf(10 ))
//0

Neste caso acima acessamos a última ocorrrência do valor 10 no array, e ele retornou que a ultima ocorrência do valor 10 foi na posição 0. Se não passarmos nenhum valor nos argumentos, ele vai retornar -1.
Exemplo:
console.log(crazyarr.indexOf( ))
//-1

Concatenar mais itens

Para concatenarmos mais itens dentro do array, precisamos usar o método concat.
console.log(crazyarr.concat(‘Aurora’)
//[10, ‘Joana’, 20, ‘Maria’, ‘Aurora’]

O método “push” adiciona itens no fim do array e retorna a quantidade dos itens.
Exemplo:

console.log(crazyarr.push(‘Augusto’))
//6

Já o método “pop” retorna sempre o último item de um array.
Exemplo:
console.log(crazyarr.pop())
//Augusto

Null e undefined

Basicamente o “null’’ somos nós que definimos, já o ‘undefined’ quem define é o JavaScript.
Exemplo:

let nothing
console.log(nothing)
//undefined

Ou seja a variável “nothing” está indefinida.

Só usamos o “null” para indicarmos intencionalmente que não existe um valor na variável.
Exemplo:

let metallica = null
console.log(metallica)
//null

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @kaiansamuel! Rumo à fluência 👊🏻
