### ISSUE TITLE
Etapa 5, nome do vídeo: Event bubbling e event delegation - Aula 04-02

### ISSUE THREAD

**Issue by josemalexandre** [roger-melo-treinamentos/curso-de-js-roger-melo#1612]
Olá Roger!!!

É possível aplicar o método **event.stopPropagation( )** nos **event delegation** de forma semelhante ao **event bubbling**?

Uma outra pergunta:

Seus exercícios são excelentes e bem desafiadores. Queria saber onde posse encontrar mais exercícios semelhantes aos seus, principalmente em relação ao DOM? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @josemalexandre.

> Queria saber onde posse encontrar mais exercícios semelhantes aos seus

Não procure isso. O que você precisa saber inicialmente sobre o DOM é o que foi passado na etapa 05 e no decorrer das próximas aulas, você verá mais sobre manipulação dele. 

Foque no CJRM. Ele é o seu GPS para a fluência =)

---

> É possível aplicar o método event.stopPropagation( ) nos event delegation de forma semelhante ao event bubbling?

Não entendi a dúvida, pode explicar com mais detalhes?

**Comment by josemalexandre** [comment]
No exemplo que você deu o evento é propagado da **ul** para as **lis**. Tentei prevenir isso usando o **stopPropagation( )** mas não deu certo. Queria se usei errado ou possui outro método para prevenir?

**Comment by Roger-Melo** [comment]
Ah, tô começando a sacar xD

Vc pode mandar o código para eu dar uma olhada?

Se possível, mande o HTML e JS, assim te digo com mais precisão o que está rolando =)

**Comment by josemalexandre** [comment]
```html

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <h1>Todos</h1>

    <ul>
        <li>Comprar frango</li>
        <li>Ler livros</li>
        <li>Tocar violão</li>
        <li>Pagar as contas</li>
    </ul>

    <button>Clique aqui</button>

    <script src="app.js"></script>
</body>

</html>


```

```js

const button = document.querySelector("button");

const ul = document.querySelector("ul");

const lis = document.querySelectorAll("li");

ul.addEventListener("click", (event) => {
  const checkTag = event.target.nodeName.toLowerCase();

  if (checkTag === "li") {
    event.target.remove();
  }
  event.stopPropagation();
});

button.addEventListener("click", () => {
  const li = document.createElement("li");
  li.textContent = "Novo item";
  ul.append(li);
});

```

**Comment by Roger-Melo** [comment]
> ### No exemplo que você deu o evento é propagado da ul para as lis. Tentei prevenir isso usando o stopPropagation( ) mas não deu certo. Queria se usei errado ou possui outro método para prevenir?

Na verdade é o oposto: o clique em qualquer li é propagado para a ul.

O `stopPropagation` deve ser usado quando algum ancestral do elemento no qual o evento foi encadeado tem o mesmo tipo de evento e vc não quer que esse evento do ancestral seja disparado também.

No código que vc postou, se uma section é adicionada como ancestral da ul, por exemplo, mesmo que a section tenha atrelado à ela um evento do mesmo tipo da ul (que nesse caso é um clique), como existe um stopPropagation dentro do callback da ul, o clique na ul não irá executar o callback da section:

```html
  <section>
    <ul>
      <li>Comprar frango</li>
      <li>Ler livros</li>
      <li>Tocar violão</li>
      <li>Pagar as contas</li>
    </ul>
  </section>
```

```javascript
const mySection = document.querySelector('section')

mySection.addEventListener('click', () => {
  console.log('Evento da section disparado')
})
```

Se você clicar em qualquer li, verá que `'Evento da section disparado'` não é exibido no console por causa do stopPropagation do callback da ul.

Agora, se o stopPropagation for removido do callback da ul, o clique em qualquer li também executa o callback do listener da section, por que agora o evento de clique na ul (e nas lis dela) está se propagando até a section.

Sacou a ideia?

Só um toque: prefira deixar a invocação do `event.stopPropagation` logo na primeira linha do bloco do callback, assim fica mais rápido entender por que o evento não está propagando (se necessário).

@josemalexandre

**Comment by josemalexandre** [comment]
> > ### No exemplo que você deu o evento é propagado da ul para as lis. Tentei prevenir isso usando o stopPropagation( ) mas não deu certo. Queria se usei errado ou possui outro método para prevenir?
> 
> Na verdade é o oposto: o clique em qualquer li é propagado para a ul.
> 
> O `stopPropagation` deve ser usado quando algum ancestral do elemento no qual o evento foi encadeado tem o mesmo tipo de evento e vc não quer que esse evento do ancestral seja disparado também.
> 
> No código que vc postou, se uma section é adicionada como ancestral da ul, por exemplo, mesmo que a section tenha atrelado à ela um evento do mesmo tipo da ul (que nesse caso é um clique), como existe um stopPropagation dentro do callback da ul, o clique na ul não irá executar o callback da section:
> 
> ```
>   <section>
>     <ul>
>       <li>Comprar frango</li>
>       <li>Ler livros</li>
>       <li>Tocar violão</li>
>       <li>Pagar as contas</li>
>     </ul>
>   </section>
> ```
> 
> ```js
> const mySection = document.querySelector('section')
> 
> mySection.addEventListener('click', () => {
>   console.log('Evento da section disparado')
> })
> ```
> 
> Se você clicar em qualquer li, verá que `'Evento da section disparado'` não é exibido no console por causa do stopPropagation do callback da ul.
> 
> Agora, se o stopPropagation for removido do callback da ul, o clique em qualquer li também executa o callback do listener da section, por que agora o evento de clique na ul (e nas lis dela) está se propagando até a section.
> 
> Sacou a ideia?
> 
> Só um toque: prefira deixar a invocação do `event.stopPropagation` logo na primeira linha do bloco do callback, assim fica mais rápido entender por que o evento não está propagando (se necessário).
> 
> @josemalexandre

**Comment by josemalexandre** [comment]
Eu saquei sim a propagação dos filhos para os ancestrais. A minha dúvida ficou apenas no movimento inverso, dos ancestrais para os filhos.

Eu acho que fechei a issue sem querer :)

**Comment by Roger-Melo** [comment]
Raramente você vai usar o comportamento inverso. Eu nunca usei.

Mas apenas para eu não pecar pela falta, copie e cole o código abaixo e me acompanhe:

```html
<div>
  <a href="#">link <span>span</span></a>
</div>
```

```javascript
const div = document.querySelector('div')
const a = document.querySelector('a')
const span = document.querySelector('span')

div.addEventListener('click', () => console.log('Clicou na div'))
a.addEventListener('click', () => console.log('Clicou no a'))
span.addEventListener('click', () => console.log('Clicou no span'))
```

Como vimos antes, esse é o comportamento padrão de propagação de eventos. 

Se o clique acontece no `span`, o callback do `span`, do `a` e da `div` são executados.

Se o clique acontece no `a`, o callback do `a` e da `div` são executados.

E se o clique acontece na `div`, o callback da `div` é executado.

Nada de novo até aqui, certo?

Porém, o `addEventListener` pode receber um terceiro argumento opcional. Esse argumento pode ser um boolean indicando como vai ser a captura de eventos. Quando omitido, esse 3º argumento recebe `false` por padrão.

Se esse parâmetro receber `true`, os callbacks são executados à partir do ancestral até chegar no elemento clicado (filho).

Olha só:

```javascript
const div = document.querySelector('div')
const a = document.querySelector('a')
const span = document.querySelector('span')

div.addEventListener('click', () => console.log('Clicou na div'), true)
a.addEventListener('click', () => console.log('Clicou no a'), true)
span.addEventListener('click', () => console.log('Clicou no span'), true)
```

Agora, se o clique acontece no `span`, primeiro o callback da `div` é executado, depois o callback do `a` e só então, o callback do `span`.

Se o clique acontece no `a`, primeiro o callback da `div` é executado e só então o callback do `a`.

E claro, se o clique acontece na `div`, só o callback da `div` é executado.

É basicamente isso.

Para abstrair a repetição, você pode criar um helper `on`:

```javascript
const on = (element, eventType, callback) => {
  document.querySelector(element)
    .addEventListener(eventType, callback, true)
}

on('div', 'click', () => console.log('Clicou na div'))
on('a', 'click', () => console.log('Clicou no a'))
on('span', 'click', () => console.log('Clicou no span'))
```

Se quiser ir à fundo nisso, [aqui](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) e o tópico "Bubbling and capturing explained" [dessa página](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#other_event_concepts) são fontes confiáveis.

Porém, novamente: raramente você usará isso. Eu não investiria muita energia, não vai fazer tanta diferença e não vai te ajudar muito. Por isso não expliquei isso à fundo nas aulas, não é necessário nesse estágio de seu aprendizado, você será apresentado a outros conceitos que devem ser priorizados.

@josemalexandre

**Comment by josemalexandre** [comment]
Perfeito. Obrigado pelo esclarecimento.

**Comment by Roger-Melo** [comment]
Show @josemalexandre. No que precisar, é só abrir uma nova issue =)
