### ISSUE TITLE
Etapa 5, 3 escopos em JavaScript que você deve conhecer: Aula 01-03

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1613]
Olá Roger,
No exemplo desta aula, gostaria de saber até que nível o escopo léxico procura até o escopo global?

```js
const external = () => {
  const book = 'Sapiens'

  const internal = () => {
    console.log(book.toUpperCase())
  }

  internal()
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @paulovieiradasilva.

Independe do nível. O escopo léxico acessa qualquer variável que seja externo à declaração da função. Olha só:

```javascript
const myConst = 'value'

const externalFunc = () => {
  const book = 'Sapiens'

  const internalFunc = () => {
    const internalFunc2 = () => {
      const internalFunc3 = () => {
        console.log(myConst)
      }

      internalFunc3()
    }

    internalFunc2()
  }

  internalFunc()
}

externalFunc() // value
```

No código acima, `internalFunc3` tem acesso à `myConst`, independente do nível de aninhamento em que ela esteja =)

Sacou a ideia?

Ps: esse exemplo foi um extremo para ilustrar um ponto, esse tipo de código nunca deve para produção.

**Comment by paulovieiradasilva** [comment]
Obrigado pela explicação!

**Comment by Roger-Melo** [comment]
Show @paulovieiradasilva. No que precisar, é só abrir uma nova issue =)
