### ISSUE TITLE
Etapa 04, nome do vídeo: Variáveis e escopo de bloco - Aula 02-02

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1617]
Boa-tarde ROGER.

Na explicação sobre o escopo de variáveis vi você usar nos seus exemplos o teste lógico ```if(true)```. Isso criou um pouco de confusão na minha mente. Por Exemplo:
```js

let currentTime=12

if(true){
  console.log(`Agora são ${currentTime} horas.`) // Agora são 12 horas.
}
```
Porque é que o teste resultou em ```true```, se não estou passando explicitamente a ```currentTime``` no meu teste?

O contrário também funciona:
```js
let currentTime=12

if(false){
  console.log(`Agora são ${currentTime} horas.`) // Vazio
}
``` 

**O que o JS está testando aqui?**

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### O que o JS está testando aqui?

[if e else if](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else) checam se a expressão passada entre os parênteses resulta em um valor [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) ou [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy).

Isso significa que no código abaixo, como `true` é um valor truthy, o bloco do `if` é executado:

```javascript
let currentTime = 12

if (true) {
  console.log(`Agora são ${currentTime} horas.`) // Agora são 12 horas.
}
```

Porém, quando o valor/expressão dentro dos parênteses é/resulta em um valor falsy, o bloco do `if` não é executado:

```javascript
let currentTime = 12

if (false) {
  console.log(`Agora são ${currentTime} horas.`)
}
```

Ficou mais claro?

@gerafim

**Comment by gerafim** [comment]
NÃO, ROGER, ainda não percebi:

Eu esperava o retorno  ```true``` ou  ```false``` se eu tivesse passado entre parênteses a ```currentTime``` no meu teste lógico. Por exemplo:
```js
let currentTime=12

if(currentTime){
  console.log(`Agora SÃO ${currentTime} horas.`) // Agora SÃO 12 horas.
}else{
  console.log(`Agora NÃO SÃO ${currentTime} horas.`) // Agora NÃO SÃO 12 horas.
}

```
Mas nos exemplos que eu **NÃO PERCEBI**,  foi passado  entre parênteses ```if(true)```. Então o que  o ```true``` entre parênteses está testando?  Eu esperava ```if(currentTime===12)```,  por exemplo.

Mas quando diz ```if(true)```, está testando oquê? Ou seja, está dizendo ```se uquê for truthy```?

Não sei se fiz perceber a minha dúvida =)

**Comment by Roger-Melo** [comment]
`if (true)` está testando se `true` é um valor truthy. 

Você se lembra quais são os valores truhty e falsy?

Caso não se lembre, eu mostrei o que são e quais são esses valores [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751263), mas você também pode ver isso sempre que precisar [aqui no MDN](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

---

Se qualquer valor `truthy` for inserido nos parênteses do `if`, o bloco do `if` é executado. Você pode comprovar isso se executar o código abaixo:

```javascript
if (1) {
  console.log(`Executou o bloco do if por que ${1} é um valor truthy`)
}

if ('olá') {
  console.log(`Executou o bloco do if por que '${'olá'}' é um valor truthy`)
}

if (true) {
  console.log(`Executou o bloco do if por que ${true} é um valor truthy`)
}
```

No código acima, os blocos de todos os ifs são executados por que o valor que está dentro dos parênteses em `if ()` é um valor truthy.

Porém, se qualquer valor `falsy` for inserido nos parênteses do `if`, o bloco do `if` **não é executado**:

```javascript
if ('') {
  console.log(`Não executou o bloco do if por que '' é um valor falsy`)
}

if (0) {
  console.log(`Não executou o bloco do if por que ${0} é um valor falsy`)
}

if (false) {
  console.log(`Não executou o bloco do if por que ${false} é um valor falsy`)
}
```

Se você executar o código acima, nenhum dos blocos será executado por que o valor que está dentro dos parênteses em `if ()` é um valor falsy.

Então voltando ao exemplo que você postou... 

```javascript
let currentTime = 12

if (currentTime) {
  console.log(`Agora SÃO ${currentTime} horas.`)
} else {
  console.log(`Agora NÃO SÃO ${currentTime} horas.`)
}
```

como `currentTime` recebeu `12`, na verdade `if (currentTime)` está testando `if (12)`.

Como `12` é um valor truthy, o bloco do `if` é executado e 'Agora SÃO 12 horas.' é exibida no console.

Se você modificar o valor da `currentTime` para `0`, 

```javascript
let currentTime = 0

if (currentTime) {
  console.log(`Agora SÃO ${currentTime} horas.`)
} else {
  console.log(`Agora NÃO SÃO ${currentTime} horas.`)
}
```

como `0` é um valor falsy, o bloco do `if` não é executado e como existe um `else`, o bloco do `else` é executado. Nesse caso, isso está sendo testado: `if (0)`. Por isso, "Agora NÃO SÃO 0 horas." é exibida no console.

Mas fica ligado no seguinte...

O fato do `if` testar `if (currentTime)` **não modifica o valor de currentTime**.

Ou seja, não faz sentido inserir uma mensagem dizendo que agora não são "X" horas, pois o valor de `currentTime` continua sendo o mesmo, independente se ela foi inserida como condição do `if`.

> ### Eu esperava o retorno true ou false se eu tivesse passado entre parênteses a currentTime no meu teste lógico.

Talvez eu esteja equivocado, mas penso que você esteja confundindo `if` com funções.

`if` não é função. 

`if` não retorna valor.

Se você inserir um return dentro de um bloco de um `if`:

```javascript
if (true) {
  return 'Olá'
}
```

fazer isso não retorna a string 'Olá'.

Nem mesmo se você inserir esse `if` como argumento de um `console.log()`:

```javascript
console.log(
  if (true) {
    return 'Olá'
  }
)
```

Se você tentar executar o código acima, "SyntaxError: Unexpected token 'if'" será lançado por que o if não é uma estrutura condicional e não uma expressão. Por isso, ele não retorna valor.

Agora, pode ser que você viu algo assim por aí:

```javascript
const myFunc = () => {
  if (true) {
    return 'Olá'
  }
}

console.log(myFunc()) // 'Olá'
```

Ou assim:

```javascript
function myFunc () {
  if (true) {
    return 'Olá'
  }
}

console.log(myFunc()) // 'Olá'
```

Se esse é o caso, não é o `if` que está retornando a string. O `return` ali só funciona por que ele está dentro de uma função.

Ficou mais claro?

@gerafim

**Comment by gerafim** [comment]
Sim ROGER =) =) =) =)

Desculpe-me por dar-te tanto trabalho ao tentar explicar-me, mas agora percebi. Na verdade não tinha fixado a aula de ```truthy``` e ```falsy```. Revisei de novo a aula e conferi também a documentação MDN. Faz todo o sentido agora. Percebi que o ```true``` é um valor ```truthy``` assim como qualquer valor que não é ```falsy```. 

Demorou tanto para eu perceber, mas sinto que valeu a pena a minha insistência, porque senão teria passado despercebido =).
Muito obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Não tem que pedir desculpas, tô aqui para te ajudar =)

No que precisar, é só abrir uma nova issue =)

@gerafim
