### ISSUE TITLE
Etapa 07, Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#162]
Olá, Roger. 

Nessa correção para atribuir um identifcador único em um dos paragrafos de feedback você usou um atributo data. Como mostra o exemplo: 

```js
const paragraphSubmitFeedback = document.createElement('P')

paragraphSubmitFeedback.setAttribute('data-feedback', 'submit-feedback')
```
Por que usar um atributo data ao invés do atributo id, que por definição deve ser um atributo único no HTML? 

Há alguma vantagem em usar os atributos data?

Uma outra dúvida: Por que as linhas de código não devem conter mais do que 80 caracteres? Por que esse número específico de 80? É algum tipo de convenção?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

> Por que usar um atributo data ao invés do atributo id, que por definição deve ser um atributo único no HTML? 

Na etapa 12 eu explico por que recomendo você usar esse atributo para selecionar elementos do DOM ao invés de usar id ou class.

Mas resumindo, usar `class` para estilizar e `data-*` para manipulação de DOM é uma convenção de organização de código.

Se você comparar, lado a lado, duas versões do mesmo arquivo .html, uma com data-js e class e outra apenas com class, verá que ao bater o olho no arquivo com data-js e class, você distingue rapidamente quais elementos estão sendo manipulados pelo JavaScript. Isso não é possível ao bater o olho na versão do arquivo que usa apenas class.

Isso também vai ser mostrado em aulas que você ainda chegará, mas quanto menos id, melhor. Id's penduram uma propriedade no objeto global (window). Essa é uma das razões pelas quais ids devem ser únicos em um documento HTML.

Se na marcação HTML for declarado um atributo `id` com o valor `x`, se você inserir `window.x` (ou simplesmente `x`) como argumento de um `console.log()`, o retorno será a referência do elemento.

```html
<p id="x">Olá</p>
```

```javascript
console.log(window.x) // <p id="x">Olá</p>
console.log(x) // <p id="x">Olá</p>
```

Se você retirar o id="x", as execuções dos `console.log()` acima resultarão em undefined.

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e podem minar a modularidade do código.

> Uma outra dúvida: Por que as linhas de código não devem conter mais do que 80 caracteres? Por que esse número específico de 80? É algum tipo de convenção?

Sim, é uma convenção. Linhas com mais de 80 caracteres tornam a leitura do código mais cansativa e menos legível, devido à extensão da linha. Isso é pesquisado há anos no Design (veja o item 2 [deste post](https://medium.com/ui-lab-school/voc%C3%AA-sabe-usar-tipografia-em-ui-design-9ce4ccdbab43), incluindo as imagens). O número de caracteres pode variar entre times. Eu prefiro 80.

Está ficando mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Está sim, Roger. 

Muito interessante o artigo linkado sobre design. 

Já configurei meu VScode para controlar os 80 caracteres das linhas. 

Obrigado pela resposta.

**Comment by Roger-Melo** [comment]
Olá, Hamilton.

`on*` é uma forma mais antiga de se adicionar eventos em elementos.

O `addEventListener` tem uma função oposta: `removeEventListener`, que como o nome já diz, remove um listener de evento adicionado anteriormente. Após o clique no `p`, o evento é removido:

```javascript
const p = document.querySelector('[data-js="p"]')

const myFunc = () => {
  console.log('myFunc executada')
  p.removeEventListener('click', myFunc)
}

p.addEventListener('click', myFunc)
```

Essa técnica pode ser útil em casos onde é necessário remover um evento de um elemento após uma certa ação ter sido concluída.

Com o `addEventListener`, você pode adicionar funções diferentes a serem executadas para o mesmo tipo de evento:

```javascript
const myFunc = () => {
  console.log('myFunc executada')
}

const myFunc2 = () => {
  console.log('myFunc2 executada')
}

p.addEventListener('click', myFunc)
p.addEventListener('click', myFunc2)

// Ao clicar no p, as mensagens abaixo são exibidas no console
// myFunc executada
// myFunc2 executada
```

Ao tentar fazer isso usando o `onclick`, a segunda ocorrência do `onclick` sobrescreve a primeira:

```javascript
const myFunc = () => {
  console.log('myFunc executada')
}

const myFunc2 = () => {
  console.log('myFunc2 executada')
}

p.onclick = myFunc
p.onclick = myFunc2

// Ao clicar no p, apenas "myFunc2 executada" é exibida no console
```

Não são diferenças gritantes, mas só uso o `onclick` em casos onde é necessário dar suporte a versões muito antigas de navegadores. Para todos os outros casos, sempre uso o `addEventListener`.

Ficou mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Ficou sim, Roger. 

Muito obrigado!

**Comment by Roger-Melo** [comment]
Legal @Hamiltonspjunior! Vou fechar a issue mas ao surgirem dúvidas, é só abrir uma nova =)
