### ISSUE TITLE
Etapa 01, O console do browser - Aula 01-05

### ISSUE THREAD

**Issue by Roger-Melo** [roger-melo-treinamentos/curso-de-js-roger-melo#1622]
Olá Rodrigo. Sempre prefira postar as dúvidas aqui no repositório. O help center do treinamento é aqui, ok? =)

Vou colar abaixo a dúvida que vc postou e vou deixar um vídeo rápido que gravei para respondê-la. 

Se não solucionar o problema, é só comentar nessa issue que te ajudo =)

> ### Como posicionar o console do browser em baixo? o meu está na lateral. Dei uma fuçada aqui e não consegui colocar, se alguém puder ajudar eu só agradeço.

https://user-images.githubusercontent.com/29297788/130363995-bacd1a45-07e8-4a35-a69b-123994a9d4c5.mp4

> Rodrigo Lima

**Comment by Rodrigo986** [comment]
Saquei. Obrigado!

**Comment by Roger-Melo** [comment]
Show @Rodrigo986. No que precisar, é só abrir uma nova issue =)
