### ISSUE TITLE
Resumo da Aula Booleans e comparações 04 da etapa 02

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1626]
Quando vamos utilizar o Boolean ?

Quando precisamos verificar alguma condição no código, 
vai ter momento que vamos precisar checar se um trecho de 
código é verdadeiro ou falso. Podemos utilizar alguns 
métodos que retornam um boolean (true ou false).

 Booleans e comparações
```js
console.log(true, false)
```
Métodos podem retornar Booleans
 
Método includes determina se contém  um determinado
elemento e retorna um boolean verdadeiro ou falso, 
o método includes tanto pode ser usado para String como para Array
A posição de busca por padrão iniciara pelo índice 0.

Utilização de includes com String
```js
const email = 'brucewany@rogermelo.com.br'

const includes = email.includes('@')

console.log(includes)
```
Utilização de includes com Array
```js
const names = ['dio', 'roger', 'robert']

const arrayIncludes = names.includes('roger')

console.log(arrayIncludes)
```
Operadores de comparação
```js
const age = 31

console.log(age == 31)
console.log(age == 35)
console.log(age != 31)
console.log(age > 31)
console.log(age <= 31)
console.log(age >= 31)
```
Comparando String

O javaScript entende que as letras minúsculas são maiores que 
as maiúsculas, também entende que as ultimas letras do alfabeto 
são maiores que as primeiras letras do alfabeto, essa é a ordem 
que o javaScript interpreta estes caracteres.
```js

const name = 'roger'
console.log(name == 'roger')
console.log(name == 'Roger')
console.log(name > 'belinha')
console.log(name > 'Roger')
console.log(name > 'Belinha')
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @AdrianoRepet, rumo à fluência! 🔥
