### ISSUE TITLE
Resumo da Aula: Tipos de refêrencia vs Tipos primitivos - da etapa 04

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1627]
**RESUMO**

Os tipos Primitivos são armazenados na STACK e os tipos de Referência são armazenados no HEAP.

Ao declarar uma variável ou uma constante e atribuir a ela um valor primitivo, esse valor é armazenado na STACK e ao criar uma cópia deste valor e armazenar numa outra variável, estes valores encontrar-se-ão em posições diferentes, pelo que mesmo que uma das variáveis receba um novo valor, o valor da outra variável não é alterado.

Ao contrário com o que acontece com os tipos de referência, quando declaramos uma variável e atribuimos a ela um objecto, é criado na STACK um ponteiro que aponta para a referência na HEAP. Assim, mesmo que seja feita cópia do ponteiro, qualquer alteração numa das variáveis ou constates, modificam directamente o objecto referido, fazendo com que todos os ponteiros que apontam ao objecto recebam o valor actualizado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @gerafim, rumo à fluência! 🔥
