### ISSUE TITLE
Etapa 12, nome do vídeo: Obtendo informações da cidade 01-06

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1631]
Boa tarde Roger  fiz as etapas que você pediu na aula mas o request não veio como no vídeo , na verdade nem veio .
Meu código esta assim :
```js
const apiKey = 'EXFVlL4b75HAL5LFJ30kMB8MJP9m3Kv3'
const cityUrl = `http://dataservice.accuweather.com/locations/v1/cities/search?apiKey=${apiKey}&q=coritiba`

const getCityData = async ()=>{
    try{
      const response = await  fetch(cityUrl)

      if(!response.ok){
        throw new Error('Não foi possível obter os dados')
      }
        console.log(await response.json())
    }catch({name, message}) {

    }
}
getCityData()
```

Mas no console do browser esta com este erro:
```js
index.html:1 Access to fetch at 'http://dataservice.accuweather.com/locations/v1/cities/search?apiKey=EXFVlL4b75HAL5LFJ30kMB8MJP9m3Kv3&q=coritiba' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
weather.js:6 GET http://dataservice.accuweather.com/locations/v1/cities/search?apiKey=EXFVlL4b75HAL5LFJ30kMB8MJP9m3Kv3&q=coritiba net::ERR_FAILED
getCityData @ weather.js:6
(anonymous) @ weather.js:16
```
Meu código está igual ao seu sem nenhuma modificação.
Aguardo sua resposta para seguir com os estudos .
obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

Primeiro, faça as seguintes modificações na template string `apiKey=${apiKey}&q=coritiba`: 

- substitua o "K" maiúsculo por um "k" minúsculo em `apiKey=` (apenas na palavra key antes do sinal de `=`);
- substitua o coritiba por curitiba.

Se depois de fazer os passos acima o problema não for resolvido, delete a app no site da accuweather API, crie uma nova e use a nova chave. 

Se for preciso, [essa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1402115) é a aula em que eu mostro como fazer isso.

Me avisa aqui se deu certo =)

**Comment by jhow221318** [comment]
Realmente os erros de sintaxe observados por vc existiam mas infelizmente Roger ainda sim não funcionou , se eu pegar a url da API do pokemon de aulas anteriores eu consigo fazer o request numa boa . 
Obrigado ... Bom dia ....

**Comment by Roger-Melo** [comment]
Sobe os arquivos em um respositório e manda o link aqui. Assim eu testo e ajudo com mais precisão =)

**Comment by jhow221318** [comment]
Roger eu fiz os reparos que você me pediu e uma vez eu consegui obter os dados , mas tenho um outro problema vou abrir uma nova issue para discutirmos ela .
Obrigado.
Boa tarde!
