### ISSUE TITLE
Etapa 01, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1633]
exercício nr 08, onde devemos exibir a ultima letra de qualquer palavra adicionada em
```js
let randomWord = 'Araponga'

console.log(randomWord[randomWord.length -1]
```
podemos utilizar as variáveis diretamente no index? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosebs.

Se eu entendi direito, a dúvida é se é possível usar variáveis dentro dos colchetes, certo?

Sim, dentro dos colchetes você pode usar: 

- uma variável que armazene um número;
- qualquer expressão que resulte em um número.

No código abaixo, a const `index` foi inserida entre os colchetes e, como ela armazena `0`, a expressão `randomWord[index]` resulta no caractere da string que está no index `0`, que é o "A".

```javascript
const randomWord = 'Araponga'
const index = 0

console.log(randomWord[index]) // 'A'
```

Já nesse código abaixo, como `2 - 1` resulta em 1, a expressão `randomWord[2 - 1]` resulta no caractere da string que está no index `1`, que é o "r".

```javascript
const randomWord = 'Araponga'

console.log(randomWord[2 - 1]) // 'r'
```

Era essa a dúvida?

**Comment by carlosebs** [comment]
@Roger, sim era está duvida, vou memorizar estes conceitos.
Obrigado pelo feedback

Em ter, 24 de ago de 2021 08:25, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @carlosebs. Vou fechar essa issue mas sempre que tiver dúvidas, abra issues aqui que te ajudo =)
