### ISSUE TITLE
Etapa 3, nome do vídeo: Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#1640]
Professor na questão 2 do exercício sobre if, else e else if aconteceu algo estranho. Eu montei toda a estrutura(inclusive tanto da forma que o senhor fez, assim como outras que deveriam dar no mesmo resultado), porém quando salvei o console não conseguiu executar e deixou uma mensagem
![Captura de tela 2021-08-24 123413](https://user-images.githubusercontent.com/85198581/130646197-6adcb874-0f6a-4019-bdb3-694314b735ee.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208. 

Esse erro foi lançado por que dentro do `else if`, foi inserido `consoles` ao invés de `console`. Consertando isso, o código deve funcionar normalmente =D

Dica: quando um erro for lançado, procure observar a mensagem que ele exibe. Nesse caso, foi um ReferenceError dizendo que `consoles` is not defined. Não tem problema se tiver dificuldades com o inglês, vc pode usar o google tradutor se sentir que precisa =)

Deixe-me saber se o problema foi resolvido =)

**Comment by CarlosHenrique2208** [comment]
que gafe🤦‍♂️🤦‍♂️🤦‍♂️...
obrigado professor!

**Comment by Roger-Melo** [comment]
Relaxa @CarlosHenrique2208, isso é natural =)

No que precisar, é só abrir uma nova issue 🔥
