### ISSUE TITLE
Etapa 05, nome do vídeo: Correção dos exercícios da aula passada + destructuring em parâmetros de funções - Aula 04-01

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1641]
Boa-noite ROGER
No exercício 07, tentei acessar a propriedade ```children``` do elemento ```body``` e depois usei o método ```remove()```, assim: 
```js
h1.addEventListener('click', ()=>{
  document.body.children.remove()
})

```
Não funcionou. PORQUÊ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim!

A expressão `document.body.children` retorna um `HTMLCollection`:

```html
<div>Div 1</div>
<div>Div 2</div>
```

```javascript
console.log(document.body.children) // HTMLCollection(3) [div, div]
```

Lembrando: um [HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection) representa uma lista genérica de elementos.

Só que um HTMLCollection não contém uma propriedade/método `remove`. Por isso, quando a invocação do `remove` é encadeada no HTMLCollection, um erro com a mensagem "Uncaught TypeError: document.body.children.remove is not a function" é lançado.

Quem tem a propriedade [remove](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove) é o **elemento do DOM**. Ou seja, se eu tiver apenas uma `<div>` e encadear a invocação do `remove` na referência dela, ela é removida do DOM:

```html
<div>Div</div>
```

```javascript
const myDiv = document.querySelector('div')

myDiv.remove() // remove o elemento do DOM
```

Então voltando em seu exemplo, como o `HTMLCollection` contém elementos do DOM, se você executar a expressão abaixo, o primeiro elemento filho do `<body>` é removido:

```javascript
document.body.children[0].remove()
```

Sacou a ideia?

**Comment by gerafim** [comment]
Sim ROGER, obrigado. Percebí!

Com a sua explicação, para treinar um pouco mais, usei a função construtora ```Array.from()``` para trasnformar cada ```child``` do elemento ```body```, num iten de array.  De seguida iterei o ```array```  e usei o método ```remove()``` para remover cada iten. Assim:

```js
const bodyChildren=document.body.children
const arrayOfBodyChildren=Array.from(bodyChildren)

arrayOfBodyChildren.forEach(bodyChild=>bodyChild.remove()) // FUNCIONOU!!!
``` 
Acredito que fiquei esclarecido!

**Comment by Roger-Melo** [comment]
Ótimo @gerafim =)

Já que ficou mais claro vou fechar a issue, mas no que precisar, é só abrir uma nova =)
