### ISSUE TITLE
Etapa 12, nome do vídeo: Obtendo Informações da cidade -Aula 01-07

### ISSUE THREAD

**Issue by jhow221318** [roger-melo-treinamentos/curso-de-js-roger-melo#1642]
Roger boa tarde!
Eu copiei o seu código feito no inicio desta aula  mas tem uma coisa que me deixando encabulado você declarou a função ```getCityUrl()``` , no meu código esta dando que a função ("is not defined") quando dentro  try do try / catch ela é referenciada em uma constante não estou entendendo  o porque ...

Código:
```js
const apiKey = 'hgOmHDRXNiBeUxQQS7LY9FdSqyA1gadP'

const getCityUrL = cityName =>
`http://dataservice.accuweather.com/locations/v1/cities/search?apikey=${apiKey}&q=${cityName}`

const getCityData = async cityName => {
  try {
    const cityUrl = getCityUrl(cityName)
    const response = await fetch(cityUrl)

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }
    const [cityData] = await response.json()
    return cityData
  } catch ({ name, message }) {
    alert(`${name}: ${message}`)
  }
}
getCityData('São Paulo') 
```
Pode ser um erro primário mas de verdade eu não intendi pois ela foi declarada em escopo global mas aparentemente não estou conseguindo acessa-la dentro do bloco do ```try()```

```js
const apiKey = 'hgOmHDRXNiBeUxQQS7LY9FdSqyA1gadP'
const cityUrl = `http://dataservice.accuweather.com/locations/v1/cities/search?apikey=${apiKey}&q=curitiba`

const getCityData = async ()=>{
    try{
      const response = await  fetch(cityUrl)

      if(!response.ok){
        throw new Error('Não foi possível obter os dados')
      }
        console.log(await response.json())
    }catch({name, message}) {

    }
}
getCityData()
```
Este código acima  depois das alterações pedidas por vc na ultima issue  esta rodando normal.

Obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @jhow221318.

A declaração da `getCityUrL` está com o "L" maiúsculo, enquanto a invocação dela está com o "l" minúsculo.

Basta substituir o "L" por "l" na declaração dela =)

O JavaScript é case-sensitive, então fica ligado se ao referenciar a função ela está com exatamente o mesmo nome da declaração dela. Eu mesmo gosto de copiar e colar o nome para não errar =)

**Comment by jhow221318** [comment]
Há tá , estranho porque quando seleciono ele no visual Studio  ele selecionava tbm a palavra , deve ser que o visual só leva em conta as letras . Mas obrigado ...

**Comment by Roger-Melo** [comment]
Saquei. Mas com essa modificação resolveu o problema? =)

**Comment by jhow221318** [comment]
Sim obrigado irmão , vlw

**Comment by Roger-Melo** [comment]
Show @jhow221318! No que precisar, é só abrir uma nova issue =)
