### ISSUE TITLE
Duvida, não referente a qualquer aula do curso.

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#1649]
### Olá Roger Melo

**Hoje venho aqui com uma duvida, mais essa não tem algum relacionamento com qualquer aula do curso.**

**No inicio do curso, para ser mais especifico na etapa 00 de Boas Vindas, você fala sobre se candidatar para vagas de Desenvolvedor Jr. é você fala sobre estudar algum framework exemplo `react js`, sobre o estudo do mesmo, me surgiu uma duvida.**

> ***Devo estudar primeiro `Nodejs` antes de `reactjs`❓*** 

**Pois visto que para criar aplicações com `react js` é usado o `Node js`.**

 **Grato Mateus** 👍

@Roger-Melo

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
