### ISSUE TITLE
Títulos das aulas

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1658]
Roger, estou com dúvida nos títulos das suas aulas.
"Correção dos exercícios da aula 02 - Aula 03-01"
Estou assistindo a aula que possui o título acima e nao consigo entender a logica dos títulos kkk, não lembro se voce explicou a nomeclatura em algum vídeo.
A lista de exercícios está  nomeado com outro padão de título e nao consegui meio que relacionar com as aulas.

**Comment by Rodrigo986** [comment]
Obrigado, ficou mais claro sim. Já era claro, eu que fiz confusão

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
