### ISSUE TITLE
Resumo da Aula O objeto Math - Aula 03-03 da etapa 04

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#1662]
# O objeto Math

É um objeto próprio do Javascript. Para visualizar suas propriedades e métodos:

```js
// Lista as propriedades e métodos
console.log(Math);

// Exemplo com a propriedade PI
console.log(Math.PI);
```

### Método round

O método round converte número decimal em inteiro na forma padrão, ou seja, se o valor for igual a 1,4 ou menos, ele será arredondado para baixo, se for 1,5 ou mais ele será arredondado para cima:

```js
const area = 7.7;

console.log(Math.round(area)); // 7
```

### Método floor

Esse método sempre irá arredondar o valor em decimal para baixo:

```js
const area = 7.9;

console.log(Math.floor(area)); // 7
```

### Método ceil

O método ceil irá fazer o oposto do floor, arredondando sempre para cima:

```js
const area = 7.1;

console.log(Math.ceil(area)); // 8
```

### Método trunc

Esse método remove o decimal do número, apresentando somente o número inteiro:

```js
const area = 7.4;

console.log(Math.trunc(area)); // 7
```

### Método random

Este método gera um número decimal aleatório entre 0 e 1:

```js
const randomNumber = Math.random();
console.log(randomNumber);
```

Abaixo um exemplo caso queira gerar um número aleatório de 0 a 100:

```js
console.log(Math.round(randomNumber * 100));
```

**Comment by Roger-Melo** [comment]
Boa @rohyer, rumo à fluência! 🔥
