### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#1665]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/francisko-rezende/curso-de-js-roger-melo-quiz-interativo

### Maiores dificuldades durante a implementação

Tive dificuldades com escopo e com a refatoração do código. 

Eu gostaria de declarar as variáveis "score" e "maxScore" dentro da função "gradeQuizAndShowResult" mas acabei não conseguindo, usei uma alternative que não me deixou satisfeito mas que resolveu o problema. 

Além disso, tive problemas em deicidir como refatorar o código, ficava me perguntando se não estava exagerando na refatoração (eg, dividindo o código demais).

### Menores dificuldades durante a implementação

A manipulação dos elementos do DOM foi bem tranquila.

**Comment by Roger-Melo** [comment]
Excelente @francisko-rezende. No que precisar, é só dar o toque =)
