### ISSUE TITLE
Resumo da Aula Booleans e Comparações - 04-02 da etapa 01

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1666]
- ### Booleans
- Verifica alguma condição no código(utilizando métodos) se é verdadeiro ou falso, retornando "true" ou "false".
- True e false são valores especiais em JS.
```js
let name = carlos@carlos.com
const includesFalsy = name.includes('dudu') //false

const includesTrue = name.includes('@carlos') //true
```
- ** includes** é um método que verifica se a string existe dentro da string
- ### Operadores de comparação
```js
==   => 'igual'
!=    => 'não igual'
>     =>'maior que'
<     => 'menor que'
<=   => 'menor ou igual que'
>=   => 'maior ou igual que'

```
- **Obs.**
 Os caracteres minúsculos são maiores que os caracteres maiúsculos.

**Comment by Roger-Melo** [comment]
Boa @carlosebs, rumo à fluência! 🔥
