### ISSUE TITLE
Resumo da Aula Palavra chave "this" - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1686]
# Palavra chave "this"

### This

This ⇒ é um objeto de contexto, ele representa o contexto no qual o código atual está sendo executado. O valor do this vai mudar de acordo com o contexto que ele estiver inserido.

O JS faz com que o valor do 'this' seja o objeto no qual ele está sendo usado. Mas isso só acontece quando a gente usa o 'this' com a function declaration, se a gente usar o 'this' com a arrow function o 'this' vai se referenciar ao objeto 'window'.

```
let user = {

  name: 'João',

  age: 31,

  email: 'joaocardoso@gmail.com',

  city: 'São Paulo',

  blogPosts: [ 'Empadão de frango', '4 receitas de purê de batata' ],

  login: function ( ) {

    console.log ( 'Usuário logado' )

  }

  logBlogPosts: function ( ) {

    console.log ( this.blogPosts ) → este 'this' referencia o objeto 'user', pois não é possível usar o nome do 
objeto dentro dele   mesmo (console.log ( user.blogPosts ))

  }

user.logBlogPosts ( )

console.log(this )  → já este 'this' referencia o 'window' como objeto pois ele está no escopo global e não dentro 
de um objeto
```

Uma forma mais reduzida de fazer uma function declaration como método dentro de um objeto é tirando os "dois pontos" depois do nome do método e tirando a palavra "function".

→ Forma normal de declarar um método dentro de um objeto ←

```
logBlogPosts: function ( ) {

  console.log ( this.blogPosts ) 

}
```

→ Forma REDUZIDA de declarar um método dentro de um objeto ←

Nesta forma reduzida o 'this' tbm funciona para referenciar o objeto do escopo.

```
logBlogPosts ( ) {

  console.log ( this.blogPosts ) 

}

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuFML, rumo à fluência! 🔥
