### ISSUE TITLE
Etapa 2, Exercícios 05 -  Aula 03-01

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#169]
```js
const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false]
let numberAmount = 0
let booleanAmount = 0
let stringAmount = 0

for(let i = 0; i < crazyArray.length; i++){
  const typeOFItem = typeof crazyArray[i]
  const isItemANumber = typeOFItem === 'number'
  const isItemABoolean = typeOFItem === 'boolean'
  if (isItemANumber){
    numberAmount += 1
  } else if(isItemABoolean){
    booleanAmount += 1
  } else {
    stringAmount += 1
  }
}
console.log(`"O crazyArray tem ${booleanAmount} booleans, ${numberAmount} números e ${stringAmount} strings."`)
```

 const isItemANumber = typeOFItem === 'number'
  const isItemABoolean = typeOFItem === 'boolean'

Nessa parte fiquei em dúvida na resolução

Ex: typeof 869 === 'number'
          ' number' === 'number'

        Quando eu converto o typeof de um valor numérico vai aparecer dessa maneira  -> 'number' , escrito dentro de uma aspa?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rodrigo.

O `typeof` não faz conversão. Ele é um operador que retorna uma string que indica o tipo do operando.

Se você executar `console.log(typeof 1)`, a expressão `typeof 1` resulta em uma string 'number'. No console do chrome a string não será exibida com aspas, mas é uma string.

Tanto é que se `console.log(typeof (typeof 1))` é executado, `string` é exibido no console. Ou seja, primeiro `(typeof 1)` foi executada (devido aos parênteses) e resultou em 'number', e como 'number' é uma string, o que foi executado como argumento do `console.log()` foi essa expressão: `typeof 'number'`.

E sim. Na expressão `typeof 869 === 'number'`, `typeof 869` resulta na string 'number' e a comparação que acontece é `'number' === 'number'`.

Pegou a ideia?

@azulinho10

**Comment by azulinho10** [comment]
Pegue sim, ficou claro para min. Até fiz no node para ter essa percepção.
![Capturar](https://user-images.githubusercontent.com/49795140/107848454-4bf77380-6dd2-11eb-85d9-e11a35f8ace3.PNG)

**Comment by Roger-Melo** [comment]
Isso mesmo @azulinho10, o Node facilita algumas visualizações desses tipos de nuances. Inclusive, devo introduzi-lo em etapas futuras =)

Já que ficou mais claro, vou fechar a issue. Mas quando houverem dúvidas, é só abrir uma nova =)
