### ISSUE TITLE
Aplicação: [To-do list]

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#1695]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/WebDevCampos/ToDoCJRM

### Maiores dificuldades durante a implementação

Olá Roger, tudo certinho? Espero que sim, lá vai: 

As maiores dificuldades estão na refatoração e na iteração sobre os elementos. Procurei resolver à minha maneira, mesmo que tenha assistido às aulas e feito na primeira vez, junto com você. Nessas outras vezes eu sempre esbarrava na aplicação correta de um método de array ou na iteração em HTML collections. Assistir às aulas me fez relembrar o método `.from()` que eu havia esquecido, e consequentemente isso me fez relembrar de rever sempre os conteúdos. 

### Menores dificuldades durante a implementação

Após as primeiras dificuldades eu comecei a pensar direito, passo a passo e fui fazendo como você sempre fala: 'Primeiro de tudo a gente tem que pegar a referência desse elemento HTML' e assim foi até que a iteração pode ter sido aplicada. Fiquei muito satisfeito de ter conseguido, embora eu quis ter conseguido através do mesmo modo que você. Fui revendo o conteúdo, relembrando para que cada coisa serve, por exemplo o objeto `event`.
As menores dificuldades foram na iteração em si do que na 'captura' dos elementos.

**Comment by Roger-Melo** [comment]
Olá @WebDevCampos. Você precisa enviar o link do repositório da aplicação, e não o link dela em produção =)

**Comment by WebDevCampos** [comment]
Opa Roger, desculpe, pensei que havia enviado corretamente. Vou verificar.

Em dom, 29 de ago de 2021 09:05, Roger Melo ***@***.***>
escreveu:

**Comment by WebDevCampos** [comment]
> Olá @WebDevCampos. Você precisa enviar o link do repositório da aplicação, e não o link dela em produção =)

Atualizei camarada.

**Comment by Roger-Melo** [comment]
@WebDevCampos, visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @WebDevCampos!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### As maiores dificuldades estão na refatoração e na iteração sobre os elementos. Procurei resolver à minha maneira, mesmo que tenha assistido às aulas e feito na primeira vez, junto com você. Nessas outras vezes eu sempre esbarrava na aplicação correta de um método de array ou na iteração em HTML collections. Assistir às aulas me fez relembrar o método .from() que eu havia esquecido, e consequentemente isso me fez relembrar de rever sempre os conteúdos.

Isso mesmo, revisar é fundamental para sacar o que talvez tenha passado despercebido antes. 

Refatoração vem com a prática e o tempo.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Após a adição de um to-do, você fez com que o input fosse limpo e voltou o foco para ele, isso é bom para a experiência do usuário em adicionar to-dos.

No geral, as cores da aplicação tiveram um bom contraste entre si.

## Lógica

A lógica da `searchTask` ficou complicada de entender, pelo seguinte...

A expressão abaixo retorna um boolean indicando se há um match entre a string inserida no input e a string de algum to-do:

```javascript
item.textContent
  .toLowerCase()
  .includes(event.target.value.trim().toLowerCase())
```

Ou seja, se 'x' é inserido no input, como existe um to-do com a palavra 'exercícios', a expressão acima resulta em `true`, certo?

Só que foi inserido um `!` como prefixo da expressão acima. Isso faz com que o boolean no qual a expressão resultou seja invertido. Se é `false`, é invertido pra `true`. Se é `true`, é invertido pra `false`.

Isso significa que no código abaixo, mesmo que haja um match entre a string inserida no input e a string de algum to-do, `true` está sendo convertido pra `false`:

```javascript
const thereIsAMatch = !item.textContent
  .toLowerCase()
  .includes(event.target.value.trim().toLowerCase())
```

Então o not não faz sentido ali.

Observe também essa `const`:

```javascript
const thereIsNotAValue = !event.target.length
```

Essa const sempre armazenará `true`, pois `event.target` resulta na referência do `input` e, como não existe uma propriedade `length` no input, `event.target.length` sempre resultará em `undefined`. Como `undefined` é um valor falsy mas existe um not ali, `!event.target.length` sempre resultará em true.

Ou seja, no `if/else if` abaixo, se considerarmos o mesmo exemplo do 'x' inserido no input (em que há um match), `thereIsAMatch` armazena `false`, o bloco do `if` não é executado, e o que está fazendo de fato o to-do "Fazer exercícios físicos" ser exibido na ul é um `else if` que verifica uma const que sempre armazena `true` mas se chama `thereIsNotAValue`:

```javascript
if (thereIsAMatch) {
  classList.remove('d-flex')
  classList.add('d-none')
} else if (thereIsNotAValue) {
  classList.remove('d-none')
  classList.add('d-flex')
}
```

Sacou o quanto isso é confuso?

Pra resolver, eu faria o seguinte...

1. Removeria o not da expressão que `thereIsAMatch` armazena;
2. Eliminaria `thereIsNotAValue`;
3. Eliminaria o `else if` (inserindo um `return` no `if`);
4. Inverteria a ordem de adição e remoção das classes.

```javascript
// antes
const searchTask = (event) => {
  Array.from(taskContainer.children).forEach((item) => {
    const thereIsAMatch = !item.textContent
      .toLowerCase()
      .includes(event.target.value.trim().toLowerCase())
    
    const thereIsNotAValue = !event.target.length
    const classList = item.classList

    if (thereIsAMatch) {
      classList.remove('d-flex')
      classList.add('d-none')
    } else if (thereIsNotAValue) {
      classList.remove('d-none')
      classList.add('d-flex')
    }
  })
}

// depois
const searchTask = (event) => {
  Array.from(taskContainer.children).forEach((item) => {
    const thereIsAMatch = item.textContent
      .toLowerCase()
      .includes(event.target.value.trim().toLowerCase())

    const classList = item.classList

    if (thereIsAMatch) {
      classList.remove('d-none')
      classList.add('d-flex')
      return
    }
    
    classList.remove('d-flex')
    classList.add('d-none')
  })
}
```

Na `removeTask`, não é necessário usar `forEach` para remover um to-do da lista. Eu mostrei na aula 02-03 da etapa 09 como fazer essa remoção sem usar o `forEach`.

Sempre use comparações com igualdade estrita (`===`) ao invés de `==`, pelos motivos que expliquei na aula 04-03 da etapa 01.

## Organização de código

### Nomes de variáveis e funções

Como `sendTask` está adicionando uma "task", acredito que `addTask` seja um nome mais descritivo.

### Linhas em branco

Para separar mais os conceitos, eu adicionaria linhas em branco nas linhas 17, 19 e 32.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by WebDevCampos** [comment]
Opa, obrigado pela revisão! Claro que fez sentido!  Vou estudar bem está aplicação antes de mudar para a próxima lição, na verdade é por isso que eu usei o `.forEach()` ao invés do `.filter()`, porque eu não queria fazer lembrando das aulas, na decoreba mecânica. Esquentei a cuca pensando em como fazer sem lembrar das aulas, e por isso mesmo que fiquei muito satisfeito de ter conseguido. Claro que suas correções são muito bem vindas e as aplicarei com calma até que eu assimile de verdade. Quanto ao sinal de igualdade com apenas *==* ao invés de *===*, sinceramente deve ter sido um _typo_. XD
Muito obrigado mesmo Roger, vou rever com todo cuidado. Abraço, camarada!

**Comment by Roger-Melo** [comment]
Show. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
