### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1696]
Me perdi um pouco na explicação da correção do quiz da aula 01 - Aula 02-01, etapa 08

busquei ver duas vezes pra entender se poderia fazer algo a mais pra melhorar o meu código e nao encontrei
o meu código pode ser melhorado?
```js
const form = document.querySelector('.quiz-form')

const correctAnswers = ['C', 'C', 'D', 'A']
const renderMessage = document.querySelector('.result')

const renderScore = event => {
  event.preventDefault()

  let score = 0

  const userAnswers = correctAnswers.map((_, index) =>
  form[`inputQuestion${index + 1}`].value)

  const checkAnswers = (userAnswer, index) => {
    const isAValidAnswer = userAnswer === correctAnswers[index]

    if(isAValidAnswer) {
      score += 25
    }
  }

  userAnswers.forEach(checkAnswers)
  renderMessage.classList.remove('d-none')

  let counter = 0

  setTimeout(() => {
    scrollTo(0, 0)
    
    const timer = setInterval(() => {
      if (counter === score) {
        clearInterval(timer)
      }
  
      renderMessage.querySelector('span').textContent = `${counter}%`
      counter++
    }, 15)
  }, 1000)  
}

form.addEventListener('submit', renderScore)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Sempre há como melhorar =)

As vezes você saca padrões de melhoria rápido. As vezes leva mais tempo, e tá tudo bem. 

Observe que na aula que vc mencionou (02-01 da etapa 08), o código é quebrado em funções menores. Isso já é uma das diferenças em relação ao código que vc postou acima. Então uma forma de melhorar o código é a que mostrei nas aulas (e vc ainda vai ver mais melhorias no quiz, não acabou).

Uma outra forma, é deixando a aplicação mais funcional, trabalhando com imutabilidade e sem variáveis globais, como mostrei [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1665#issuecomment-907331566).

Então a pergunta não é se tem como melhorar, mas sim, o quê melhorar.

> #### Me perdi um pouco na explicação da correção do quiz

No quê exatamente vc se perdeu?
