### ISSUE TITLE
Etapa 07, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1698]
Boa-tarde ROGER

Percebi que posso adicionar qualquer atributo a um elemento HTML, usando por exemplo:
 ```js
element.setAttribute('class', 'elementClassName')
```
Neste caso eu sei que estou adicionando uma ```class``` ao elemento. Mas e no código abaixo por exemplo:
```js
element.setAttribute('data-feedback', 'elementDataFeedback')
```
O que segnifica o prefixo ```data``` no nome do atributo ```data-feedback```?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim.

`data-*` é um atributo HTML como outro qualquer, mas vamos usá-lo para manipular elementos do DOM. 

Se é a primeira vez que vc teve contato com esse tipo de atributo, não se preocupe, vc ainda verá muitos casos de uso dele no treinamento e na aula 01-01 da etapa 12 eu falo por que vc deve usar atributos `data-*` ao invés de ids ou classes para manipular DOM.

[Aqui](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) você também encontra informações detalhadas sobre esse atributo.

Se ainda tiver alguma dúvida, é só dar o toque =)

**Comment by gerafim** [comment]
Muito obrigado!
