### ISSUE TITLE
Exercício 20 - Erro no contador 

### ISSUE THREAD

**Issue by Dani-jardim** [roger-melo-treinamentos/curso-de-js-roger-melo#17]
Oi Roger,
Estou com problemas.

Tenho três botões: 

- Iniciar contador;
- Parar contador;
- Zerar contador

Eles estão funcionando, mas, se eu clicar mais de uma vez no "Iniciar contador" a numeração começa a ir mais rápido e o botão "Parar contador" para de funcionar.

Quero saber se existe uma forma que o botão de início não pudesse ser clicado mais de uma vez. 

link exercício : https://github.com/Dani-jardim/curso-de-js-roger-melo/blob/master/exercicio-20/app.js

video com erro: https://drive.google.com/file/d/1A4Hbp3AssiGMAJQw7h360aJVDI4biNHh/view?usp=sharing

Obrigada :)

**Comment by Roger-Melo** [comment]
Oi @Dani-jardim!

Vou te dar pistas de uma das formas de se fazer isso. Se você não conseguir implementar as pistas, é só me chamar que explico com mais detalhes, combinado? =D

Você pode declarar, no topo do código, uma let `quantityOfInitButtonClicks`, por exemplo, que é iniciada em 0.

Essa let irá contabilizar quantos cliques o botão recebeu.

Quando a função do evento de clique no botão "Iniciar contador" é executada, isso significa que o botão foi clicado e `quantityOfInitButtonClicks` deve receber o valor que ela já tem + 1.

Se o botão for clicado pela 2º vez, `quantityOfInitButtonClicks` receberá 2 e dentro da função, você pode ter um if que verifica se a quantidade de cliques no botão é 2.

Se for, você encadeará no botão um método `removeEventListener()`.

O `removeEventListener()` faz o oposto do `addEventListener()`. Você encadeia a invocação dele na referência do elemento no qual o evento deve ser removido, especifica no 1º argumento uma string dizendo qual evento deve ser removido, e como 2º argumento você especificará a referência da função que deve ser removida do elemento.

Ou seja, para especificar este 2º argumento, você terá que armazenar em uma const a função do evento de clique do botão para usá-la como 2º argumento.

Logo após o `removeEventListener` ser executado, ainda dentro do if, insira um return para que o código abaixo do if seja ignorado e nenhuma modificação no timer aconteça.

Pronto. Com isso, você perceberá que no 2º clique no botão "Iniciar contador", o evento de clique nele terá sido removido e esse "descompasso" no timer não irá mais acontecer.

Tente fazer com essas informações e, se ainda estiver com dificuldades, é só chamar aqui que explico de outra forma =)

**Comment by Dani-jardim** [comment]
@Roger-Melo, deu certo!

Fiz o que você me orientou e está funcionando

link: https://github.com/Dani-jardim/curso-de-js-roger-melo/tree/master/exercicio-20

No meu btn zerar eu adicionei um <code>document.location.reload(true)</code> que você não passou ainda, né? Teria uma outra forma de fazer isso?

Eu reparei tbm que o btn **"parar contador"** dependendo da quantidade de clicks nele o btn **"iniciar contador"** ( que é para continuar a contagem de onde parou) para de funcionar.

Obrigada por enquanto =)

**Comment by Roger-Melo** [comment]
Oi @Dani-jardim.

Não tem por que usar `document.location.reload(true)`. Observe que se você simplesmente comentar a invocação desse método e salvar, quando o callback do clique do "buttonReset" for executado, o `clearInterval(timer)` já vai cancelar a repetição do setInterval e `counterDisplay.innerText = 0` vai fazer o timer exibir 0. Então não tem por que recarregar a página com o `document.location.reload(true)`.

Observe que essa expressão `quantityOfInitiButtonClicks ++` não funciona como o esperado. O operador de pós incremento deve ser encadeado sem espaço em branco na let que ele deve incrementar, ficando assim: `quantityOfInitiButtonClicks++`.

Observe também que no código abaixo, 

```javascript
buttonInit.addEventListener('click', function counterClickButtonInit (event) {
  // ...
})
```

o parâmetro `event` não está sendo usado dentro da função. Então ele não precisa ser declarado.

O "Iniciar contador" não irá funcionar a partir do 2º clique por que a função do evento de clique dele foi removida com o `removeEventListener`.

Pelo que entendi, você não quer que o botão "Iniciar contador" perca sua funcionalidade, mas quer que o erro no andamento do timer do counter não aconteça **caso o botão "Iniciar contador" seja clicado 2x seguidas**, não é isso?

Se for, há uma outra lógica que pode ser implementada.

Você pode declarar no topo do código uma let `clickedButtons` por exemplo. Essa let irá armazenar um array vazio e, a cada vez que um dos 3 botões for clicado, uma string é adicionada como item no array `clickedButtons`.

Se o botão "iniciar contador" foi clicado, uma string 'init button' é adicionada no array, se o botão "parar contador" foi clicado, uma string 'stop button' é adicionada no array, etc.

Feito isso, na função de listener de clique do buttonInit, implemente um if que checa se os 2 últimos itens do array correspondem à string 'init button'. Se corresponderem, apenas execute um return dentro do bloco do if para que a função pare imediatamente de ser executada e nenhuma manipulação no contador seja feita.

Sacou a ideia?

Qualquer dúvida na implementação desse algoritmo, ou se a ideia não é essa, é só chamar =)

**Comment by Dani-jardim** [comment]
Olá @Roger-Melo 
Você entendeu certo, muito obrigada pelas dicas!

Tentei fazer o que você falou e me enrolei um pouco no array, logo em seguida pensei em uma outra solução que resolveu 🎉

Segue o link: https://github.com/Dani-jardim/curso-de-js-roger-melo/commit/f9b1ef1a07d62e320179aef0a9b4cbcb2dbc6761

Está bom? em que posso melhorar?

Obrigada

**Comment by Roger-Melo** [comment]
Oi @Dani-jardim.

É isso aí, parabéns pela alternativa proposta =)

Apenas tome cuidado para não se esquecer de setar `isCounting` como `false` também no clique do botão de zerar o contador.

Caso contrário, ao clicar em "Zerar contador" e "Iniciar contador" em seguida, como `isCounting` estará setado como `true`, o `return` dentro do bloco do `if` será executado e o timer abaixo do `if` não será manipulado e o contador continuará exibindo 0.

Tome cuidado também com a formatação do código.

Ao invés de deixar linhas em branco no início e no fim da função,

```javascript
buttonInit.addEventListener('click', function counterClickButtonInit () {
  
  if(isCounting) { 
    return
  }

  isCounting = true
  timer = setInterval(() => {
    counterDisplay.textContent = Number(counterDisplay.textContent) + 1
  }, 1000);

})
```

prefira deixá-las apenas separando responsabilidades:

```javascript
buttonInit.addEventListener('click', function counterClickButtonInit () {
  if(isCounting) { 
    return
  }

  isCounting = true
  timer = setInterval(() => {
    counterDisplay.textContent = Number(counterDisplay.textContent) + 1
  }, 1000);
})
```

Declarações de lets podem ser agrupadas, assim como as de const:

```javascript
// evite
const buttonInit = document.querySelector('.button-init-counter')
const buttonStop = document.querySelector('.button-stop-counter')
const buttonReset = document.querySelector('.button-stop-reset')
const counterDisplay = document.querySelector('.counter-container')

let timer = null

let isCounting = false

buttonInit.addEventListener('click', function counterClickButtonInit () {
  // ...
}

// prefira
const buttonInit = document.querySelector('.button-init-counter')
const buttonStop = document.querySelector('.button-stop-counter')
const buttonReset = document.querySelector('.button-stop-reset')
const counterDisplay = document.querySelector('.counter-container')

let timer = null
let isCounting = false

buttonInit.addEventListener('click', function counterClickButtonInit () {
  // ...
}
```

Tente padronizar o uso das arrow functions no código.

```javascript
// evite
buttonInit.addEventListener('click', function counterClickButtonInit () {
  // ...
})

buttonStop.addEventListener('click', () => {   
  // ...
})

buttonReset.addEventListener('click', () => {
  // ...
})

// prefira
buttonInit.addEventListener('click', () => {
  // ...
})

buttonStop.addEventListener('click', () => {
  // ...
})

buttonReset.addEventListener('click', () => {
  // ...
})
```

No mais, acho que é isso. Parabéns novamente pela solução =)

**Comment by Dani-jardim** [comment]
Oi @Roger-Melo obrigada pelas dicas.
Estou adorando =)

**Comment by Roger-Melo** [comment]
Show, @Dani-jardim!

No que precisar é só abrir uma issue =)
