### ISSUE TITLE
Etapa 07, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by josemalexandre** [roger-melo-treinamentos/curso-de-js-roger-melo#1703]
Olá Roger!!!

Você poderia disponibilizar o código completo desse exercício?

Grato

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @josemalexandre.

Você se refere a algum exercício corrigido [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/943413), certo?

Se o que vc precisa é o app.js com a bateria de exercícios, você pode encontrá-lo [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-18/app.js).

Mas se o que vc quer é o código pronto de algum exercício, eu não disponibilizo, justamente para que o aluno resolva o exercício por conta própria e veja a correção depois =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só dar o toque =)
