### ISSUE TITLE
Etapa 07, Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by baronibr** [roger-melo-treinamentos/curso-de-js-roger-melo#1706]
Roger, bom dia!
Estou com muita dificuldade ao criar os nomes das variáveis, coloco os nomes das variáveis no início, quando vou refaturar o código, sinto dificuldade, o que posso para facilitar na criação dos nomes?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @baronibr.

Isso é natural, nomear coisas em um código exige prática e tempo.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Sacou a ideia?

Se quiser, pode postar o código que tem as variáveis em que vc está com dificuldade que te ajudo =)

**Comment by baronibr** [comment]
Esses códigos eu sempre volto para revisar.
Pode me dá um exemplo mais específico Roger ?

Eu me atrapalho todo na hora de colocar nomes, tenho que seguir um padrão,
para não me atraplhar depois.

```js

  const inputUsername = document.querySelector('#username')
  const formSubmit = document.querySelector('form')
  const button = document.querySelector('.button')

  const paragraphInputFeedback = document.createElement('p')
  const paragraphSubmitFeedback = document.createElement('p')
  paragraphSubmitFeedback.setAttribute('data-submit','data-feedback')

  const validFields = paragraphinfo => {
    const {paragraph,text,className,position} = paragraphinfo
    paragraph.textContent = text
    paragraph.setAttribute('class',className)
    position.insertAdjacentElement('afterend', paragraph)
  }

  invalidateSubmit = {
    paragraph: paragraphSubmitFeedback,
    text: `Por favor, insira um username válido`,
    className: 'submit-help-feedback',
    position: button,
  }

  validateSubmit = {
    paragraph: paragraphSubmitFeedback,
    text: `Dados enviados =)`,
    className: 'submit-success-feedback',
    position: button,
  }

  const invalidateInput = {
    paragraph: paragraphInputFeedback,
    text: `O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas`,
    className: 'username-help-feedback',
    position: inputUsername,
  }

  const validateInput = {
    paragraph: paragraphInputFeedback,
    text: `O Username válido =)`,
    className: 'username-success-feedback',
    position: inputUsername,
  }

  const removeSubmit = () => {
    const removeparagraphSubmitFeedback = document.querySelector('[data-submit="data-feedback"]')

    if(removeparagraphSubmitFeedback){
      paragraphSubmitFeedback.remove()
    }
  }

  const checkInput = check => /^[a-zA-Z]{6,}$/.test(check)

  showInputUsername = event =>{

    const inputValue = checkInput(event.target.value)

    removeSubmit()

    if(!inputValue){
      validFields(invalidateInput)
      return
    }

    validFields(validateInput)

  }


  const showFormSubmit = event => {
    event.preventDefault()

    const inputValue = checkInput(inputUsername.value)

    if(!inputValue){
      validFields(invalidateSubmit)
      return
    }

      validFields(validateSubmit)

  }

  inputUsername.addEventListener('input', showInputUsername)
  formSubmit.addEventListener('submit', showFormSubmit)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Pelo que entendi, sua dificuldade está no exercício da aula 01-01 da etapa 07, então modifiquei o título da issue. 

---

O princípio de nomeação que mostro na aula é o mesmo que mostrei acima. Então não é que vc está com dificuldade em nomear, vc está com dificuldade em seguir o que está sendo mostrado nas aulas. 

E tá tudo bem, a vontade de improvisar é positiva. Mas não nesse momento. Vc está em um estágio inicial, improvisar antes mesmo de aprender o básico vai te trazer frustração.

Se esforce para fazer exatamente o que é mostrado nas aulas. 

Depois que vc estiver conseguindo fazer exatamente o que é mostrado nas aulas, aí talvez seja o momento de pensar em improvisar.

---

Observe que na aula, eu nomeei um objeto como `invalidSubmitInfo` e, no código que vc postou, o mesmo objeto foi nomeado como `invalidateSubmit`.

Como descrevi no comentário acima, `invalidateSubmit` é verbo. Verbo é usado em nome de função, não de objeto. Por isso eu usei `invalidSubmitInfo` (substantivo).

E o mesmo vale para as outras consts que foram nomeadas de forma diferente do que foi mostrado na aula.

---

Uma outra coisa que vc precisa ficar ligado é esse tipo de código:

```javascript
nomeDoObjeto = {
  prop1: 'valor'
}
```

Tem dois objetos em seu código que foram declarados dessa forma.

Nunca declare consts ou lets sem as palavras-chave `const` ou `let`, pois isso pendura uma variável global no objeto `window`:

```javascript
console.log(window.invalidateSubmit) // {text: "Por favor, insira um username válido", ...}
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

Ficou mais claro?

@baronibr

**Comment by baronibr** [comment]
Perfeito Roger! ficou claro sim!
vou colocar em prática! obrigado.

@Roger-Melo

**Comment by baronibr** [comment]
Sobre as nomenclaturas das variáveis de funções entendi a lógica.
Sobre o desenvolvimento das marcações no html, você segue a mesma lógica para escrever o nome das classes ?

**Comment by baronibr** [comment]
Sobre as nomenclaturas das variáveis de funções entendi a lógica.
Sobre o desenvolvimento das marcações no html, você segue a mesma lógica para escrever o nome das classes ?

**Comment by baronibr** [comment]
Sobre as nomenclaturas das classes e das funções no javaScript eu entendi a lógica.
Sobre o desenvolvimento da marcação em html, você usa a mesma lógica para criar o nome das classes?

@Roger-Melo

**Comment by Roger-Melo** [comment]
@baronibr depois que uma issue é fechada, eu não sou notificado. Por isso só vi a pergunta agora.

Existem várias convenções de nomenclatura, uma das mais famosas é o [BEM](http://getbem.com/). Eu não abordo isso no treinamento pq não é o foco e, geralmente, libs como o [React](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet) usam [CSS modules](https://github.com/css-modules/css-modules) o que faz a preocupação com nomenclatura desnecessária.

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
