### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by LuizTokuhara** [roger-melo-treinamentos/curso-de-js-roger-melo#1707]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/LuizTokuhara/quiz-cjrm

### Maiores dificuldades durante a implementação

Lembrar de todos os conceitos, mas após o início da construção as ideias vão fluindo... alguma coisa ou outra em relação a manipulação do DOM é necessário rever alguns capítulos anteriores para refrescar a memória.

### Menores dificuldades durante a implementação

A menor dificuldade foi em relação a lógica do sistema montado

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> #### Lembrar de todos os conceitos, mas após o início da construção as ideias vão fluindo... alguma coisa ou outra em relação a manipulação do DOM é necessário rever alguns capítulos anteriores para refrescar a memória.

Total =)

Antes de qualquer coisa, eu quero que vc saiba que o mais importante no primeiro momento vc já fez, que é fazer funcionar. O que vou mostrar abaixo são melhorias, considerando que a aplicação já funciona, ok?

A versão do `app.js` que vou analisar é a [do primeiro commit](https://github.com/LuizTokuhara/quiz-cjrm/commit/4c36d6e0cb6b7281c7d715579400ebdc0488a189#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28f), feita antes de vc assistir a aula 02-01 da etapa 07.

---

## Boas decisões

Você deixou claro o total de perguntas que o quiz tem na mensagem "Você acertou 3 de 5 perguntas". Isso é bom para a usabilidade, pq traz clareza do progresso do usuário no quiz.

No geral, vc escolheu bons nomes de variáveis.

Vc também fez bom uso do callback do `forEach`, pq não inseriu manipulação de DOM à cada execução =)

## Usabilidade

### Inputs e labels

Ao clicar em uma alternativa, o usuário precisa posicionar o mouse e clicar exatamente no input type radio. Isso pode causar desconforto, pois o input é muito pequeno.

Por isso, eu preferi mostrar na aula como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

## Organização de código

### Comentários

Não é uma regra, mas evite comentários na hora de subir a aplicação para produção ou no código em geral.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

### Seleção de elementos

As consts `modal` e `modalWrapper` estão selecionando o mesmo elemento. Uma delas pode ser eliminada do código.

### Local de declaração de variáveis

Prefira declarar `openModal` antes de sua invocação. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`correct` pode ser uma const mais descritiva se for renomeada como `correctAnswersCounter`. 

Seguindo esse mesmo raciocínio, os parâmetros `correct` e `answer` podem ser renomeados como `correctAnswersCounter` e `correctAnswer`.

Como `formResult` na verdade é uma função que desencadeia algumas ações distintas, vc pode nomeá-la com um nome mais genérico, como `handleFormSubmit`.

## Lógica

O `stopPropagation` deve ser usado quando algum ancestral do elemento no qual o evento foi encadeado tem o mesmo tipo de evento e vc não quer que esse evento do ancestral seja disparado também.

O único ancestral de `<div class="modal-bg">` é o `<body>` e não existe um evento de clique nele, então o `stopPropagation` é desnecessário.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by LuizTokuhara** [comment]
Oi Roger, obrigado pela avaliação.
Ainda preciso melhorar legibilidade do código (ordem e nome de variáveis, funções etc), mas aos poucos estou pegando o ritmo =)

**Comment by Roger-Melo** [comment]
Isso aí! Com a prática e o tempo, aos poucos vc vai melhorando o código =)

Se precisar de algo, é só abrir uma nova issue =)
