### ISSUE TITLE
Aplicação: Construção do QUIZ - Exercício 19 da Etapa 07

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1708]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/gerafim/Exercicio19-Quiz-iterativo

### Maiores dificuldades durante a implementação

1. Não consegui de forma segura capturar valores de ```radiobutton``` e colocar no Array, para comparar com as respostas fornecidas pelo usuário;
2. Quando o usuário escolhe uma RESPOSTA CORRECTA e logo depois escolhe uma RESPSTA INCORRECTA, não conseguí substituir no Array a RESPOSTA CORRECTA pela INCORRECTA. Assim, uma RESPOSTA CORRECTA permanece no Array mesmo que o usuário mude de opinião;

### Menores dificuldades durante a implementação

1. Aplicar o método ```some``` para capturar elementos que fecham o popup;
2. Refactoração do código (embora ainda precise melhorar)

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Dá uma olhada no email que te enviei. Vou fechar a issue, mas no email, explico porquê =)
