### ISSUE TITLE
Resumo da Aula Aula 03-02 da etapa 1

### ISSUE THREAD

**Issue by brunofarias** [roger-melo-treinamentos/curso-de-js-roger-melo#1709]
Array são usados para armazenar uma lista de valores que geralmente tem uma relação entre si

```js
let heroes = ['Superman', 'Batman', 'Flash']
const ages = [31, 15, 19, 39, 31]
```

Para obter o valor passar o index do array
```js
console.log([0])
```

Sobrescrever array
```js
heroes[2] = 'Mulher Maravilha'
```
Métodos do array

Length: Retorna o tamanho do array
```js
console.log(heroes.length)
```

Join: Retorna uma nova string do array com todos os itens concatenados e separados por virgula. Um argumento opcional pode ser passado para substituir a vírgula pelo separador escolhido
```js
console.log(heroes.join())
console.log(heroes.join('-'))
```
indexOf: Retorna o index da primeira ocorrência do valor passado no argumento
```js
console.log(ages.indexOf(31))
```
concat: Retorna a junção de dois arrays
```js
const moreHeroes = heroes.concat([Aquaman, Lanterna Verde])
console.log(moreHeroes())
```
push: Empurra, adiciona valores ao array. Esse método altera o valor original do array
```js
console.log(heroes.push('Asa Noturna',  'Cyborgue'))
```
pop: Remove o último item do array e retorna esse array. Esse método altera o valor original do array
```js
console.log(heroes.pop())
```

**Comment by Roger-Melo** [comment]
Boa @brunofarias! Rumo à fluência 🔥
