### ISSUE TITLE
Etapa 5, nome do vídeo: 04-01 Exercícios

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#1712]
Boa noite, professor!
No exercício 01 do vídeo 4-1 da Etapa 5, você pediu um console.log( )  e fez o seguinte:

```js
const ul = document.querySelector('ul') 
const lis = Array.from(ul.children)

Array.from(li).forEach(item => {
  item.classList.add('video')
})
console.log({ ul,  lis })
}
```
Eu não entendi porque ul e lis foi passado como propriedades de objeto. Por que não passar apenas 
console.log( ul, li ) ?

Obrigada!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado. 

Nos primeiros minutos da correção desse exercício, eu usei shorthand property names apenas para visualizar os elementos de forma mais organizada no console. Às vezes fica mais organizado visualizar um objeto que contém propriedades que armazenam os valores, ao invés de simplesmente exibí-los no console separando-os por vírgula. 

O uso de shorthand property names foi apenas para propósitos visuais =)

Respondi a dúvida?

**Comment by ElaineDelgado** [comment]
Bom dia!!
Sim, resolveu! Entendi que foi para visualizar de forma mais organizada! 
Obrigada.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
