### ISSUE TITLE
Etapa 1, nome do vídeo:  Comparações com igualdade estrita - Aula 04-03

### ISSUE THREAD

**Issue by caiobgs** [roger-melo-treinamentos/curso-de-js-roger-melo#1723]
Opa Roger, tudo bem?

Nessa aula ficou bem claro que a utilização de comparações estritas são sem duvida mais confiáveis na hora de comparar dados, entretanto me surgiu uma duvida, existe algum contexto real que levaria a utilização de uma comparação simples ser mais interessante do que a estrita?

desde já agradeço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @caiobgs.

> #### existe algum contexto real que levaria a utilização de uma comparação simples ser mais interessante do que a estrita?

Não existe.

Uma comparação que envolve conversão de tipos não é confiável. E vc sempre irá querer que as comparações em suas aplicações sejam confiáveis. Portanto, não faz sentido usar `==` e `!=`. Esse é um princípio que vc levará para o resto da sua carreira como JS Dev, assim como outros que ainda aprenderá no treinamento =)

**Comment by caiobgs** [comment]
Muito Obrigado pelo esclarecimento, Roger!
