### ISSUE TITLE
Resumo da Aula 01-04da etapa 03

### ISSUE THREAD

**Issue by daniel-lopes-98435** [roger-melo-treinamentos/curso-de-js-roger-melo#1728]
Retornando valores de uma função, uma função pode executar um conjunto de tarefas e devolver um retorno, supondo que precisamos realizar um outro conjunto de tarefas com o resultado da função. exemplo:

//A função abaixo retorna o dobro de um valor
const double = (number) =>{
 return number * 2;
}
//Agora vamos armazenar o resulta da da funcão:
const result(double(10));

//Vamos criar uma função que que vai devolver uma string com o valor armazenado
const showMessage = (valor) =>{
return (`O resultado da função é  ${valor}`;
}
console.log(showMessage(result));

**Comment by Roger-Melo** [comment]
Boa @daniel-lopes-98435! Rumo à fluência 🔥
