### ISSUE TITLE
Resumo da Aula 01-05da etapa 06

### ISSUE THREAD

**Issue by eduardophilip** [roger-melo-treinamentos/curso-de-js-roger-melo#1733]
## Use Regular expression in javascript

* Uma regular expression é usada com os métodos de RegExp e com métodos de string.

* Um exemplo de RegExp method seria o ``` patternOfRegex.test('string') ``` ele testa se a sting passada como argumento faz mathing com a regular expression o o resultado da saída é TRUE ou FALSE.

```js
const username = 'eduardo';
const pattern = /^[a-z]{6,}$/;
const result = pattern.test(username);

console.log(result) // true
```
* Já quando é usada com string methods  podemos usar o method ``` string.search(patternRegex) ``` e este método retorna -1 ou 0, como mostra no exemplo abaixo:
```js
const username = 'eduardo';
const pattern = /^[a-z]{6,}$/;
const result = username.search(pattern);

console.log(result); //  0
```

* O retorno 0 indica o index da string

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @eduardophilip! Rumo à fluência 🔥
