### ISSUE TITLE
Etapa 08,Correção dos exercícios da aula 02 da etapa 08 - Aula 01-01: min 40:01

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#1737]
Roger  fui ler no MDN a respeito do innerHTML e lá informa que devemos evitar ao maximo o uso do innerHTML minha duvida é o seguinte tem que ser evitado em produção ou apenas depende de como  vamos utilizar ?
O codigo a seguir foi a forma que utilizei no exercicio.
```
const ul = document.querySelector('.list-group')
const movieNames = topBrazilMovies.reduce((acc, movie) => 
  acc + `<li>${movie.title}</li>`, '')

  ul.insertAdjacentHTML('beforeend', movieNames)
```

### Texto retirado do site mdn
**Considerações de segurança**
Não é incomum ver a propriedade innerHTML usada para inserir texto em uma página web. Isso vem com um risco de segurança.
```
var name = "John";

// presumindo que el é um elemento DOM HTML
el.innerHTML = name; // inofensivo, nesse caso

// ...

name = "<script>alert('I am John in an annoying alert!')</script>";
el.innerHTML = name; // inofensivo, nesse caso
```

Embora isso talvez se pareça como um ataque  cross-site scripting, o resultado é inofensivo. O HTML5 especifica que uma tag <script>, inserida via innerHTML, não deve ser executada.

No entanto, há formas de se executar JavaScript sem usar elementos <script>, por isso ainda há um risco de segurança sempre que você usa innerHTML para definir uma string sobre a qual você não tem controle. Por exemplo:
```
const name = "<img src='x' onerror='alert(1)'>";
el.innerHTML = name; // exibe uma caixa de alerta
```

Por essa razão, recomenda-se que você não use o innerHTML quando estiver inserindo texto puro; como alternativa, utilize node.textContent. Isso não interpreta o conteúdo passado como HTML, mas em vez disso, insere-o como texto puro.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mlluiz39.

> #### lá informa que devemos evitar ao maximo o uso do innerHTML minha duvida é o seguinte tem que ser evitado em produção ou apenas depende de como vamos utilizar?

Depende se você controla o valor que o `innerHTML` recebe.

Se o valor é totalmente controlado por você, não há grandes problemas em usar o `innerHTML`.

Se o valor vem de um input que o usuário inseriu, por exemplo, por motivos de segurança, ao invés de usar `innerHTML`, vc pode usar o `createElement` e manipular esse elemento como objeto do DOM, como mostrado na etapa 05. Mas ainda falarei mais à fundo sobre segurança em etapas futuras.

Também irá depender da stack que a aplicação está utilizando. Normalmente, aplicações que vão para produção usam algum framework/lib JS e essas ferramentas possuem formas específicas de lidar com a segurança no front-end. 

Quais tecnologias JS vc usa em seu dia a dia?

---

Ps: Use o MDN em inglês, mesmo que pra isso vc precise copiar partes do texto e colar no google tradutor para entender. Páginas em pt-BR do MDN perdem informações originais da página em inglês.

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só dar o toque =)
