### ISSUE TITLE
Aplicação: QUIZ Interativo

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1738]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/gerafim/Exercicio19-QUIZ-interativo

### Maiores dificuldades durante a implementação

Sem maiores dificuldades!

### Menores dificuldades durante a implementação

Não tive dificuldade até ao nível do QUIZ, mas fiquei com algumas dúvidas sobre como ficaria caso eu quizesse torná-lo dinámico? Por exemplo, posso querer acrescentar uma Questão e, neste caso teria que voltar ao arquivo JS para alterar o Array que armazena as Respostas correctas.

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @gerafim!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você também evitou if/else no final do do callback do `forEach`, através do return. Ótimo.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Mensagem da pontuação

A mensagem da pontuação pode ser mais clara, pois apenas o número "100" não é descritivo. Afinal, o usuário pode pensar "100%?, "100 pontos?, 100 pontos de quantos?"

Por isso, o ideal é que a mensagem deixe clara o progresso do usuário em relação à pontuação.

## Organização de código

Prefira que o nome do arquivo HTML na raiz da aplicação seja nomeado como `index.html`. 

Mesmo que atualmente exista a possibilidade de servidores possuírem configurações que suportem servir arquivos com outro nome, é uma boa prática a página de entrada da aplicação ser nomeada como `index.html`.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Mas na real, o que notei que pode ser melhorado em relação à nomes na aplicação são, em grande parte, erros ortográficos:

- `correctUnswers` => `correctAnswers`
- `givenUnswers` => `givenAnswers`
- `givenUnswer` => `givenAnswer`

Se `givenAnswers` é nomeada como `userAnswers`, além de `userAnswers` ser mais descritiva em relação ao valor que ela armazena (respostas do usuário), a expressão abaixo fica mais clara: 

```javascript
// antes
givenUnswer === correctUnswers[index]

// depois
userAnswer === correctAnswers[index]
```

Como há apenas uma pontuação na aplicação, `scores` pode ser nomeada como `score` (no singular).

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode inserir uma linha em branco antes da declaração da let `score` e remover a linha em branco do início do arquivo. É uma convenção que a primeira linha de um aquivo seja preenchida com código.

## Lógica

Se quando `score` armazena zero, zero é inserido na tela, o `if` que verifica se `score` é igual à `0` é desnecessário. 

Basta usar a própria `score` ao invés de `0`:

```javascript
// antes
if (score === 0) {
  quizResult.textContent = 0
  return
}

quizResult.textContent = `${score}`

// depois
quizResult.textContent = `${score}`
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
