### ISSUE TITLE
Etapa 2, nome do vídeo: Exercício 1 - Aula 02-01

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1745]
Olá, Roger eu errei todos os exercício do 04 a 07, isso é algo ruim, ou eu não estou entendendo a lógica?
Fiquei meio frustrado, vou repetir diversas vezes até internalizar as lógicas. Estou escrevendo para desabafar um pouco. abraços

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosebs.

Se sentir que precisa, faça uma [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x).

Não tenha pressa. Vá no seu tempo. No jogo da fluência, consistência é mais importante que velocidade.

E sempre que surgir uma dúvida, não hesite em abrir uma issue aqui no repositório =)
