### ISSUE TITLE
Etapa 9, Correção dos exercícios da aula 01: Aula 02-01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1750]
Durante a correção do 5º exercício, fiz uma anotação, e gostaria de saber se o meu entendimento do assunto faz sentido.
Obrigado pela atenção.

```js
Esse é o meu código, a forma como resolvi o exercício...
/*05

  - Através do encadeamento de 2 métodos, gere um novo array com apenas os nomes  
    dos amigos que moram perto (que contém a propriedade "nearMe" armazenando 
    true).
*/

const friends = [
  { id: 1, name: 'João', nearMe: true },
  { id: 2, name: 'Matheus', nearMe: true },
  { id: 3, name: 'Luana', nearMe: false },
  { id: 4, name: 'Nilson', nearMe: true },
  { id: 5, name: 'Solange', nearMe: false }
]
const friendsNearMe = friends
  .filter(friend => friend.nearMe === true )
  .map(({name}) => name)

  console.log(friends , friendsNearMe)
  // debugger

```
   A anotação foi a seguinte: "...Se filter() está baseado numa condicional que verifica se 'TRUE' (o elemento é adicionado)
ou FALSE (o elemento é ignorado); Na questão onde a property  do objeto, usada como referência, contém o valor TRUE, 
o simples apontamento de 'obj.property' dentro do bloco da função, deixa implícito , ao meu ver, que o objeto onde o 
valor da property for TRUE será selecionado."
PS-1: Essa anotação foi feita no meio da correção de ex.05..me veio a idéia de criar a 'issue';
PS-2: ...sim, eu uso 'property' pela preguiça de escrever 'pro-pri-e-da-de' ; Essa e outras palavras que troco pra agilizar, mas
eu faço no meu material pessoal.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy!

> #### Se filter() está baseado numa condicional que verifica se 'TRUE' (o elemento é adicionado)

É por aí =D

Se a expressão que o callback do `filter` retorna resulta em um valor truthy, o item é adicionado ao array que o `filter` está criando. 

No código abaixo, todos os itens do array são valores truthy, por isso todos eles foram adicionados no novo array que o filter gerou:

```javascript
const filteredItems = [1, true, 'olá'].filter(item => item)

console.log(filteredItems) // [ 1, true, 'olá' ]
```

Porém, se a expressão que o callback do filter retorna resulta em um valor falsy, o item não é inserido no novo array:

```javascript
const filteredItems = ['', 0, false].filter(item => item)

console.log(filteredItems) // []
```

No código acima, como todos os itens do array original são valores falsy, nenhum item é inserido no novo array que o filter gerou.

No código que vc deu como exemplo, como `friend.nearMe` vai resultar em um boolean (lembrando que `true` é um valor truthy e `false` é um valor falsy), você pode simplesmente referenciar a propriedade:

```javascript
filter(friend => friend.nearMe)
```

Observe que `=== true` não é necessário pois se `friend.nearMe` armazena `true`, o item será adicionado no novo array.

Faz sentido?

**Comment by marcosyoggy** [comment]
A primeira coisa que veio à mente durante a correção desse exercício foi "...quando uma property é referenciada , implicitamente, o que é analisado é o valor atribuído a ela... " , anteriormente quando usei '...=> friend.nearMe === true' , não imaginava  como a lógica funcionava neste contexto....Obrigado pela atenção.

**Comment by Roger-Melo** [comment]
Show! No que precisar, fico à disposição =)
