### ISSUE TITLE
Etapa 4, nome do vídeo:Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by KauaiStaingel** [roger-melo-treinamentos/curso-de-js-roger-melo#1755]
Fiquei em duvida apenas nessa parte, procurei nos meus resumos e nao encontrei, no return, para retornar o type, pq utlizamos o []???

```
let types = type => {
  let tipos = {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }
  return tipos[type]
}

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @KauaiStaingel!

Na aula 01-03 da etapa 04, a notação de colchetes em objetos foi apresentada.

Ela é uma alternativa a notação de ponto. Com ela, vc tb acessa ou modifica o valor de uma propriedade, porém, pode fazer isso de forma dinâmica. 

Observe que no código abaixo, a notação de ponto é usada, pois eu sei que existe uma `prop1` no objeto `props`:

```javascript
const props = {
  prop1: 'value 1'
}

console.log(props.prop1) // 'value 1'
```

Mas agora imagine que eu precise usar uma variável ou uma expressão que resulta no nome da propriedade que eu preciso obter.

Se eu usar a notação de ponto nesse caso, olha o que acontece:

```javascript
const props = {
  prop1: 'value 1'
}

const propName = 'prop1'

console.log(props.propName) // undefined
```

`props.propName` resultou em `undefined` por que não existe uma propriedade `propName` no objeto `props`.

Esse é um caso típico em que é necessário usar a sintaxe de colchetes: =)

```javascript
const props = {
  prop1: 'value 1'
}

const propName = 'prop1'
const anotherPropName = 'prop'

console.log(props[propName]) // 'value 1'
console.log(props[anotherPropName + 1]) // 'value 1'
```

Ou seja, quando vc precisa obter o valor de uma propriedade de forma dinâmica, basta inserir a expressão dinâmica dentro dos colchetes, usando a notação `obj[nomeDaProp]`.

O mesmo vale para quando é necessário criar uma propriedade de forma dinâmica:

```javascript
const props = {
  prop1: 'value 1'
}

const newPropName = 'prop2'
props[newPropName] = 'value 2'

console.log(props) // { prop1: 'value 1', prop2: 'value 2' }
```

---

Então no exemplo que vc mencionou, a expressão `return tipos[type]` está retornando o resultado de `tipos[type]` (forma dinâmica de obter uma propriedade do objeto `tipos`).

Ficou mais claro?

**Comment by KauaiStaingel** [comment]
Agora entendi, muito obrigado

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
