### ISSUE TITLE
Aplicação: Quiz interativo

### ISSUE THREAD

**Issue by higoroficial-city** [roger-melo-treinamentos/curso-de-js-roger-melo#1762]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/higoroficial-city/Quiz_interativo

### Maiores dificuldades durante a implementação

A minha maior dificuldade foi e vem sendo a mesma do curso até aqui: resolver os problemas recorrendo à minha mente aquilo que eu aprendi de fato no curso, e não relembrar "exatamente" como você resolveu o problema proposto, até porque muitas vezes existem mais de uma forma de se resolver um exercício - estou ciente disso - então, preciso acessar minha mente para pensar no que aprendi, não buscar uma "xerox" do que já foi feito.
No escopo particular da aplicação, fiquei na dúvida achando que poderia implementar a parte da pontuação com um for loop ou com o some, mas esse não foi o caso. 
E sobre a exibição da pontuação na tela, não consegui resetar a pontuação ao clicar no enviar novamente, mas como não olhei no quiz feito durante a aula, não sei se o mesmo também reseta, até porque o comportamento em uma aplicação real seria de enviar os dados ao servidor e recarregar a página, certo?

### Menores dificuldades durante a implementação

A implementação do HTML com as mudanças pedidas, o evento de escuta e a criação e manipulação de uma div para exibir a pontuação do usuário na tela.

**Comment by Roger-Melo** [comment]
Olá @higoroficial-city!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> #### A minha maior dificuldade foi e vem sendo a mesma do curso até aqui: resolver os problemas recorrendo à minha mente aquilo que eu aprendi de fato no curso, e não relembrar "exatamente" como você resolveu o problema proposto, até porque muitas vezes existem mais de uma forma de se resolver um exercício - estou ciente disso - então, preciso acessar minha mente para pensar no que aprendi, não buscar uma "xerox" do que já foi feito.

No início, o que eu recomendo é que a resolução seja a mais próxima possível do que eu mostro, [seguindo esses passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661), exatamente para não cair na armadilha de "existem mais de uma forma de se resolver um exercício". Sim, existem e você não precisa necessariamente saber delas. Você precisa saber de uma única forma e fazer funcionar. Num primeiro momento, fazer funcionar é o mais importante. Depois, vc melhora o código e, se necessário, implementa outra forma de resolver.

> #### No escopo particular da aplicação, fiquei na dúvida achando que poderia implementar a parte da pontuação com um for loop ou com o some, mas esse não foi o caso.

Na real, daqui pra frente dificilmente vc usará o `for` loop.

O `for` pode ser usado em casos onde ainda não existe um array a ser percorrido. 

Se o array existe e vc precisa executar um efeito colateral (vc verá o significado disso em breve), o `forEach` é o mais adequado. Por isso ele foi usado no quiz.

Já o `some` é adequado quando vc precisa que pelo-menos 1 item do array atenda à uma condição. 

Se pelo-menos 1 item atende à condição especificada no callback dele, o callback retorna true e o some para de ser executado. Caso contrário, `false` é retornado.

> #### E sobre a exibição da pontuação na tela, não consegui resetar a pontuação ao clicar no enviar novamente, mas como não olhei no quiz feito durante a aula, não sei se o mesmo também reseta...

Em breve vc verá uma aula mostrando como resetar a pontuação à partir do segundo envio =)

> #### até porque o comportamento em uma aplicação real seria de enviar os dados ao servidor e recarregar a página, certo?

Não. Na maioria das vezes a página não vai ser recarregada.

Vc só vai enviar os dados pro servidor/banco de dados se precisar desses dados depois. Geralmente isso não é necessário em aplicações de quiz. Aqui tem um exemplo de "[aplicação real](https://buzzfeed.com.br/quiz/voce-consegue-adivinhar-que-animais-sao-esses-que-a-gente-desenhou)". Não tem recarregamento de página e dados enviados pro servidor e não faria muito sentido se tivesse.

Vc aprenderá sobre bancos de dados na etapa 15 =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

## Usabilidade

Acredito que seria interessante especificar o total de pontos do quiz na mensagem "Você marcou XX pontos!".

Para quem desenvolveu, pode parecer óbvio que o total é 100, mas para o usuário pode não ser.

Então algumas alternativas para resolver isso seriam:

- "Você marcou 50 de 100 pontos"
- "Você acertou 50% das questões"

Sacou a ideia?

## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso, `showingScore` pode ser nomeada como um substantivo, como `scoreContainer` ou `scoreEl` (El é uma abreviação de element).

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by higoroficial-city** [comment]
>No início, o que eu recomendo é que a resolução seja a mais próxima possível do que eu mostro, [seguindo esses passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661), exatamente para não cair na armadilha de "existem mais de uma forma de se resolver um exercício". Sim, existem e você não precisa necessariamente saber delas. Você precisa saber de uma única forma e fazer funcionar. Num primeiro momento, fazer funcionar é o mais importante. Depois, vc melhora o código e, se necessário, implementa outra forma de resolver.

Entendi, não vou me ater a outras formas de resolução neste momento.
   
> Vc só vai enviar os dados pro servidor/banco de dados se precisar desses dados depois. Geralmente isso não é necessário em aplicações de quiz. Aqui tem um exemplo de "[aplicação real](https://buzzfeed.com.br/quiz/voce-consegue-adivinhar-que-animais-sao-esses-que-a-gente-desenhou)". Não tem recarregamento de página e dados enviados pro servidor e não faria muito sentido se tivesse.

Ah sim, faz sentido.

> Sacou a ideia?

Saquei, deixar claro para o usuário.
 
> Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.
 
Muito bom, anotei estes princípios que seguirei também.

> Mais uma vez, parabéns pelo esforço =)

Obrigado Roger, rumo à fluência!
 
> As observações fizeram sentido?

Muito, como sempre!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
