### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1766]
# Outras maneiras de fazer queries no DOM

### getElementById

→ Com este método é possível obter a referência de um elemento pelo ID dele. Como o método já vai buscar o elemtno pelo ID dele não é necessário colocar "#" na string dentro do parêntese.

```
const title = document.getElementById ( 'title' )

console.log ( title )
```

### getElementByClassName

→ Com este método é possível obter a referência de todos os elementos pelo nome da CLASSE deles. Como o método já vai buscar os elementos pela CLASSE deles não é necessário colocar "." na string dentro do parêntese. Se tiver mais de um elemento com a mesma classe o console vai nos retornar um HTML collection (que é similar ao nodelist mas não é igual). No HTML collection é possível usar a notação de colchetes para pegar apenas um dos elementos mas não é possível usar um forEach no HTML collection.

```
const errors = document.getElementsByClassName ( 'error' )

console.log ( errors )
```

Link com métodos e propriedades que um HTML collection tem:

https://developer.mozilla,org/en-US/docs/Web/API/HTMLCollection

### getElementByTagName

→ Com este método é possível obter a referência de todos os elementos pelo nome da TAG deles.  Se tiver mais de um elemento com a mesma tag o console vai nos retornar um HTML collection (que é similar ao nodelist mas não é igual). No HTML collection é possível usar a notação de colchetes para pegar apenas um dos elementos mas não é possível usar um forEach no HTML collection.

```
const paragraphs = document.getElementsByClassName ( 'p' )

console.log ( paragraphs )
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuFML! Rumo à fluência 🔥
