### ISSUE TITLE
Etapa 2, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1768]
Olá @Roger-Melo 

meu 1º exercício fiz de forma diferente, no caso utilizei o indexof em vez do includes(não lembrei na hora)  veja se está correto também.
```js
const fruits = ['morango', 'banana', 'mamão']

if (fruits.indexOf('abacaxi') !== -1){
  console.log('A string "abacaxi" existe no array fruits.')
} else if (fruits.indexOf('pera') !== -1) {
  console.log('A string "pera" existe no array fruits.')
} else {
  console.log('Nem pera nem abacaxi existem no array "fruits".')
}
```
meu 2º

```js

const age = 2
const free = age <= 7 || age >= 65

if (free) {
  let charge = 'Para você, a entrada é grátis!'
  console.log(charge)
}else {
  charge = 'A entrada e R$ 30,00.'
  console.log(charge)
}

```
5º me corrija não quero ver ainda a solução

```js
const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false]

let crazyString = 0
let crazyNumber = 0
let crazyBoolean = 0

for (let i = 0; i < crazyArray.length; i++) {
  if (typeof crazyArray[i] === Number()) {
    crazyNumber += 1
  }else if (typeof crazyArray[i] === String()) {
    crazyString += 1 
  }else if (typeof crazyArray[i] === Boolean()) {
    crazyBoolean += 1
  }
}
console.log(`O crazyArray tem ${crazyBoolean} booleans, ${crazyNumber} números e ${crazyString} strings.`)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosebs!

> ### meu 1º exercício fiz de forma diferente, no caso utilizei o indexof em vez do includes(não lembrei na hora) veja se está correto também.

Num primeiro momento, o mais importante é fazer funcionar. 

O código que vc fez no 1º exercício funciona. 

Apenas note que com o includes, não é necessário verificar se o retorno de `array.indexOf(item)` é `-1`, e isso deixa a expressão mais legível =)

```javascript
// com indexOf
if (fruits.indexOf('abacaxi') !== -1) {}

// com includes
if (fruits.includes('abacaxi')) {}
```

> ### meu 2º

Neste caso, é importante que a let charge seja declarada fora dos blocos if/else e, só então, um valor seja atribuído para ela dentro dos blocos (como mostrado na correção).

Você não precisa entender isso agora, por que escopos serão mostrados na etapa 5. Mas o fato é que no código abaixo, 

```javascript
const age = 2
const free = age <= 7 || age >= 65

if (free) {
  let charge = 'Para você, a entrada é grátis!'
  console.log(charge)
} else {
  charge = 'A entrada e R$ 30,00.'
  console.log(charge)
}
```

a `charge` usada dentro do `else` não é a mesma `charge` declarada dentro do bloco do `if`. Isso por que o bloco do `else` não tem acesso às variáveis declaradas dentro do bloco do `if`. E não faria sentido se tivesse, pois lembre-se: apenas um dos dois blocos será executado.

Se o bloco do `else` é executado, isso significa que o bloco do if não foi executado e, portanto, a let charge não foi declarada.

Uma prova disso é que quando executo o else e tento usar a `charge` dentro de um console.log dentro do `else`, um ReferenceError é lançado dizendo que "charge is not defined":

```javascript
const age = 10
const free = age <= 7 || age >= 65

if (free) {
  let charge = 'Para você, a entrada é grátis!'
  console.log(charge)
} else {
  console.log(charge) // ReferenceError: charge is not defined
  charge = 'A entrada e R$ 30,00.'
}
```

Ali em cima eu disse que a `charge` usada dentro do `else` não é a mesma `charge` declarada dentro do bloco do `if` pelo seguinte...

A expressão `charge = 'A entrada e R$ 30,00.'` dentro do else na verdade está criando uma var global.

Quando o console.log é inserido após essa expressão, a var global foi criada e então, ela é exibida no console:

```javascript
const age = 10
const free = age <= 7 || age >= 65

if (free) {
  let charge = 'Para você, a entrada é grátis!'
  console.log(charge)
} else {
  charge = 'A entrada e R$ 30,00.'
  console.log(charge) // A entrada e R$ 30,00.
}
```

Porém, vc irá entender isso melhor quando entrar na etapa 5, onde vc verá escopos com detalhes. Não se preocupe com isso agora.

> ### 5º me corrija não quero ver ainda a solução

Não recomendo que faça isso. Eu tento responder o mais rápido possível, mas nem sempre consigo.

Não há problemas em ver a resolução se vc seguir [esses passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661).

---

Se vc executar o código que postou, verá "O crazyArray tem 0 booleans, 0 números e 0 strings." exibido no console. O que não é verdade, pois o array contém booleans, números e strings.

Você sempre pode (e deve) visualizar os valores usando o console, ele é seu amigo. Use e abuse dele.

Observe que nas comparações, os construtores `Number()`, `String()` e `Boolean()` foram usados. Se vc executar o código abaixo, verá os valores que essas invocações retornam:

```javascript
console.log(Number()) // 0
console.log(String()) // ''
console.log(Boolean()) // false
```

Então em seu exemplo, as comparações que estão sendo executadas são as seguintes:

- `typeof crazyArray[i] === 0`
- `typeof crazyArray[i] === ''`
- `typeof crazyArray[i] === false`

E isso não faz muito sentido por que `typeof algumaExpressão` sempre retorna uma string. Isso pode ser verificado (novamente) ao exibir no console o resultado de `typeof algumaExpressão`:

```javascript
for (let i = 0; i < crazyArray.length; i++) {
  console.log(typeof crazyArray[i]) 
  // 'boolean' 
  // 'number'
  // 'string'...
}
```

Ou seja, você precisa comparar se `typeof crazyArray[i]` é igual à string do tipo que vc quer verificar. No exemplo abaixo, agora `crazyNumber` foi incrementada à cada execução do `if`:

```javascript
const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false]

let crazyString = 0
let crazyNumber = 0
let crazyBoolean = 0

for (let i = 0; i < crazyArray.length; i++) {
  if (typeof crazyArray[i] === 'number') {
    crazyNumber += 1
  }
}

console.log(`O crazyArray tem ${crazyBoolean} booleans, ${crazyNumber} números e ${crazyString} strings.`)
// O crazyArray tem 0 booleans, 4 números e 0 strings.
```

Ficou mais claro?

**Comment by carlosebs** [comment]
@ Roger, obrigado pelo retorno, garanto que não ficarei enchendo o seu
tempo com coisas que ainda não aprendi,
agora entendi o que está ocorrendo, vou estudar mais e realizar novamente a
revisão raio x.

Abraços e fique com Deus.

Em sáb., 4 de set. de 2021 às 22:51, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
@carlosebs estou aqui para ajudar você a chegar na fluência, pode perguntar sempre que tiver dúvidas =)
