### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by vitorsmessias** [roger-melo-treinamentos/curso-de-js-roger-melo#1771]
[Resumo da Aula 01-06 da etapa 01.docx](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7112509/Resumo.da.Aula.01-06.da.etapa.01.docx)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @vitorsmessias, rumo à fluência! 🙌🏻
