### ISSUE TITLE
Etapa 02 - Controle de fluxo - Duvida em utilizar FOR e WHILE 

### ISSUE THREAD

**Issue by viniciusnunhez27** [roger-melo-treinamentos/curso-de-js-roger-melo#1772]
Bom dia Roger  , 

Estou com uma duvida sobre o controle de fluxo , você mencionou no video que no dia a dia usaremos pouco o WHILE. pois o FOR  e mais utilizado . Minha duvida é o seguinte 

Existe algum caso especifico onde teremos que utilizar o WHILE ao invés do FOR ?  Ou conseguimos resolver qualquer problema utilizando o FOR ?. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
> #### Existe algum caso especifico onde teremos que utilizar o WHILE ao invés do FOR ?

Não conheço um caso onde o while deveria ser usado no lugar do `for`.

Quando se trata de loop, o `for` é muito popular. Mas na real, conforme avançar no treinamento, vc conhecerá formas mais elegantes de percorrer um array =)

@viniciusnunhez27
