### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by LuizTokuhara** [roger-melo-treinamentos/curso-de-js-roger-melo#1773]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/LuizTokuhara/todo-cjrm

### Maiores dificuldades durante a implementação

A refatoração do código ainda é o maior desafio, acredito que ainda dê para refatorar um pouco mais...

### Menores dificuldades durante a implementação

Selecionar os elementos HTML pelo javascript está cada vez mais automático, sem necessidade de pensar muito.

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
@LuizTokuhara, eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Fico no aguardo.

**Comment by LuizTokuhara** [comment]
@Roger-Melo  Ops, falha nossa... subi um commit com mudanças no layout.

**Comment by Roger-Melo** [comment]
Show, em breve posto a análise =)

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### A refatoração do código ainda é o maior desafio, acredito que ainda dê para refatorar um pouco mais...

Sempre dá pra melhorar um código. Porém, o mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Assim como no quiz, no geral, você escolheu nomes descritivos para suas variáveis e funções. 

Você não cometeu a maioria dos pontos de atenção mencionados na análise passada, isso demonstra que vc recebe bem feedbacks.

## Organização de código

### Nomeação

`showTodo` e `hideTodo` são funções que lidam com mais de um to-do, então eu as nomearia como `showTodos` e `hideTodos` (no plural).

### Formatação

Não sei se rolou alguma formatação automática em seu editor, mas o ideal é que formatações em encadeamentos de métodos deixem explícitos os métodos que estão sendo encadeados:

```javascript
// antes
const isDeleteClicked = Array.from(clickedElement.classList).includes(
  "delete"
);

// depois
const isDeleteClicked = Array
  .from(clickedElement.classList)
  .includes("delete");
```

Percebe como fica mais claro onde termina uma invocação e onde começa outra?

## Lógica

### `HTMLCollection`

Se dentro da `addTodo` vc executar um `console.log(todosContainer.children)`, adicionar um todo e investigar o `HTMLCollection`, verá que ele contém a propriedade `length`. 

Então, não é necessário converter em array apenas para usar a propriedade `length` de array:

```javascript
// antes
const todoIndex = Array.from(todosContainer.children).length + 1;

// depois
const todoIndex = todosContainer.children.length + 1;
```

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, eu evitaria expressões como `todoElements.length !== 0 ? hideTodo(todoElements) : showTodo(todosArray);`.

### Complexidade

A lógica da `searchTodos` pode ser mais simples se não forem usadas duas referências (todosArray e todoElements) para esconder e exibir to-dos. 

É possível também eliminar a condição, desde que fique claro no nome das consts se os to-dos que elas armazenam devem ou não serem exibidos:

```javascript
const searchTodos = (inputValue) => {
  const todosArray = Array.from(todosContainer.children)

  const machedTodos = todosArray
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
  
  const notMachedTodos = todosArray
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))

  showTodos(machedTodos)
  hideTodos(notMachedTodos)
};
```

Se não quiser repetir o `filter`, vc pode mudar um pouco da lógica. 

É possível, por exemplo, gerar um array de objetos em que uma propriedade indique se o to-do deve ficar visível e, baseado nessa propriedade, manipular as classes que exibem ou escondem o to-do:

```javascript
const showOrHideTodos = (todos => {
  todos.forEach(({ todoEl, shoudBeVisible }) => {
    todoEl.classList.add(shoudBeVisible ? "d-flex" : "hidden")
    todoEl.classList.remove(shoudBeVisible ? "hidden" : "d-flex")
  })
})

const searchTodos = (inputValue) => {
  const todos = Array
    .from(todosContainer.children)
    .map(todoEl => ({
      todoEl,
      shoudBeVisible: todoEl.textContent.toLowerCase().includes(inputValue)
    }))
    
  showOrHideTodos(todos)
}
```

Essa é uma das formas de fazer.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by LuizTokuhara** [comment]
Obrigado pela avaliação.
Em relação aos nomes da variáveis/funções eu estou tomando mais cuidado para escolher um nome que faça sentido.
Ainda peco um pouco na refatoração, muitas vezes vejo o código mas não vejo que ele ainda pode ser simplificado.
Estou com a formatação ligada no VSCode, sempre esqueço de desligar...

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
