### ISSUE TITLE
Resumo da Aula Obtendo e setando atributos - Aula 02-03 da etapa 05

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1774]
### Obtendo e setando atributos

→ Para obter o conteúdo de um atributo de determinada tag do HTML basta usarmos o método "getAttribute( )" e passar como argumento uma string com o nome do atributo em questão.

```
const link = document.querySelector ( 'a' )

console.log ( link.getAttribute( 'href' )) -> o console vai exibir o link declarado no atributo href da tag a em questão.
```

→ Para modificar o conteúdo de um atributo de determinada tag do HTML basta usarmos o método "setAttribute( )" e passar dois argumentos, o primeiro é uma string com o nome do atributo em questão e o segundo é o novo conteudo deste atributo.

```
const link = document.querySelector ( 'a' )

console.log ( link.setAttribute( 'href', 'https://rogermelo.com.br' )) -> o console vai exibir o link declarado no atributo href da tag
 em questão.
```

→ O exemplo acima pode ser utilizado para criar atributo. Então quando não existe o atributo em questão ele cria o referido atributo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuFML, rumo à fluência! 🙌🏻
