### ISSUE TITLE
Resumo da Aula  02-03 e 02-04 da etapa 03

### ISSUE THREAD

**Issue by lathne** [roger-melo-treinamentos/curso-de-js-roger-melo#1775]
**MÉTODOS**

São funções que estão associadas a objetos ou tipos de dados como strings. 

**CALLBACKS**

Quando inserimos uma função como argumento de outra função

```
// forEach e callbacks
const myFunc = callback => {
  const value = 77

  callback(value) 
}
```

- A função myFunc recebe o parametro callback.
- O parâmetro callback é _invocado_ passando value como argumento.
- Esse parametro é invocado pois o valor que ele vai receber é a declaração de uma função.
- Então quando invocarmos a função myFunc, é necessário inserir como argumento da invocação a declaração de uma função.

```
myFunc(number => {
  console.log(number)       <==== essa função foi atribuída para o parâmetro callback
})
```
Como o parametro callback ta armazenando essa função. E como ela recebe um number por parâmentro, estamos passando o _value_ como argumento da invocação da função.

**forEach**

- Esse método vai iterar um array. 
- Para cada item do array, executamos uma ação. 
- Funciona como o for de forma mais funcional.
- Ele requer uma função callback
- Pode receber dois parametros adicionai: o index do item atual e o array que está sendo iterado.
- A outra vantagem em relação ao for é que a função pode ser desacoplada. Isso torna o código mais legivel e organizado, alem de poder reutilizar a função em outro lugar se necessário.

```
//  função do for Each desacoplada
const socialNetworks = ['youtube', 'twitter', 'facebook', 'instagram']
const logArrayInfo = (socialNetwork, index, array) => {
  console.log(index, socialNetwork, array)
}
socialNetworks.forEach(logArrayInfo)
```

**Comment by Roger-Melo** [comment]
Boa @lathne, rumo à fluência! 🙌🏻
