### ISSUE TITLE
Resumo da Aula 01 a 05 Funções e métodos da etapa 03

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1777]
FUNÇÕES  E MÉTODOS

Funções fazem parte do tipo object,  são um dos principais conceitos fundamentais  em qualquer tipo linguagem de programação. 
A função principal dela é permitir que se criei um bloco de código que se pode invocar ou executar quando agente quiser.
Uma forma possível de interpretar uma função,  e pensar nela como ela fosse uma caixa que contem um código dentro dela 
que faz alguma  coisa em particular, quando a gente que executar o código que tem dentro dela é só invocar a função  desta forma:

Exemplo: 

```JS

 myFunction() 

```

Essa função pode ser invocada varias vezes no código, esse comportamento é muito útil porque só vai ser declarado o  código uma única vez é essa função poderá ser invocada múltiplas vezes sempre que for necessário  é  onde quiser  e   quantas  vezes quiser. 
Ou seja escrevemos o código uma única vez é ele pode ser executado futuramente quantas vezes forem necessária, uma outra coisa que podemos fazer com funções e passar valores dentro dessa função e essa função vai pegar esses valores vai fazer uma coisa  com eles e vai devolver estes valores no output (saída) desses valores transformado de alguma forma. Para criar a função utilizamos a palavra reservada "functio" e em seguida o nome da função. Da mesma forma que renomeamos variáveis e constantes a gente  nomeia as funções, depois do nome da função vamos abrir e fechar parênteses e vamos abrir e fechar o bloco de código da função, todo código da função vai ser inserido dentro desse bloco entre chaves, futuramente quando a 
função for invocada esse bloco de código será executado. A diferença entre function declaretion e a function  expression é praticamente nem uma, mais existe um detalhe que devemos saber o hoisting que traduzindo significa içamento - puxar para cima, levantar ou elevar. 
Quando você cria uma function declaration  se essa função estiver em qualquer lugar do seu código, que não seja no topo do arquivo por baixo dos panos  o javascript puxa a criação da função lá pro topo do arquivo. Já quando function expression é criada isso não acontece. Ou seja o hoisting funciona para function declaration mais não funciona para function expression.

Function declaration

```JS

function sayHi() {

    console.log('oi')
}

sayHi()
sayHi()
sayHi()

```

Funcition expression

```JS

const showFood = function () {

   console.log('Pizza') 
}

showFood()
showFood()
showFood()

```

Argumentos , parâmetros e defult parameters

```JS
const myFunc = function (name, lastName) { 

    console.log(`Oi, ${name} ${lastName}!`)
}

myFunc('Roger', 'Melo')

```

Muitas vezes vamos querer passar valores em nossas funções, para que elas façam alguma coisa com esses valores.
Quando a gente passa um valor entre os parênteses da invocação de função, esse valor é chamado de argumento. 
Já a variável criada entre os parênteses da declaração  da função é chamada de parâmetros. A ordem dos argumentos
devem corresponde coma ordem dos parâmetros. O primeiro parâmetro sempre vai receber o primeiro argumento,
o segundo parâmetro sempre vai receber o segundo argumento,  é assim sucessivamente. Agora a ordem do uso desses 
parâmetros dentro da função não importa. Agora se tivermos  parâmetros na declaração da função e não passamos valores 
para os argumentos na invocação da função, o valor undefined será atribuído aos parâmetros.
Para prevenir o recebimento de undefined quando nem um valor  for passado por argumento, a gente deve inicializar as 
variáveis da função com valores defult, ou seja atribuir  um valor inicial nas declarações dos parâmetros.

 Retornando valores
```JS

const double = function (number) {
  
    return  number * 2
    
}

const result = double(3)

const showResult = function (value) {

    return `O resultado é: ${value}`
}

console.log(showResult(result))
```

**Comment by Roger-Melo** [comment]
Boa @AdrianoRepet, rumo à fluência! 🙌🏻
