### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1778]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ricardopontesdantas/to-do-list

### Maiores dificuldades durante a implementação

Tomar decisões sobre o layout é uma dificuldade ainda, e a princípio a refatoração é algo que eu devo trabalhar mais, assim como nomear variáveis e funções. Mas acredito que seja uma questão de prática mesmo. Não senti dificuldade em algo específico do JavaScript.

### Menores dificuldades durante a implementação

Obter referências, adicionar escutadores de eventos, aplicar estilos, criar funções, transformar node list em array, loop em array, remover nó, obter elemento pai e elemento filho.

**Comment by ricardopontesdantas** [comment]
Fala @Roger-Melo , obrigado pelo feedback!

As observações fizeram bastante sentido sim. Entendi o motivo da sugestão de troca de nome da função, e valeu pela dica de boa prática de utilização do ternário, isso me ajudou bastante. Com relação a variável global que eu criei, já é a segunda vez que acontece enquanto estou refatorando o código. Ficarei mais atento na próxima oportunidade.

Do restante, obrigado pela força!

Vamos em frente, rumo a fluência. Abraço!

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova. 

Conte comigo para chegar na fluência =)
