### ISSUE TITLE
Aplicação: TO-DO List

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#1780]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/marcosyoggy/TO-DO-List

### Maiores dificuldades durante a implementação

   Não consegui desenvolver a lógica da aplicação, como estava perdendo muito tempo sem progresso, consultei o código de outro aluno, entendi a idéia, mesmo assim não fluiu; Percorrer o D.O.M obtendo referências não é o maior problema, a frustração maior é não desenvolver a lógica pedida, fazer funcionar da forma que for; Então pra não perder o prazo fiz o básico.

### Menores dificuldades durante a implementação

   Trabalhar as funcões, fazer a refatoração básica, nomear e trabalhar com variáveis, imagino não ter dificuldades.

**Comment by Roger-Melo** [comment]
@marcosyoggy, eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Fico no aguardo.

**Comment by marcosyoggy** [comment]
...fiz um update, veja se está certo.

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Não consegui desenvolver a lógica da aplicação, como estava perdendo muito tempo sem progresso, consultei o código de outro aluno, entendi a idéia, mesmo assim não fluiu; Percorrer o D.O.M obtendo referências não é o maior problema, a frustração maior é não desenvolver a lógica pedida, fazer funcionar da forma que for; Então pra não perder o prazo fiz o básico.

Se sentir que precisa, faça uma revisão [raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x). 

É importante que o que foi visto até aqui esteja consolidado pra vc, pois o conteúdo fica cada vez mais denso à medida em que vc vai avançando.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você manteve o foco no input após a adição de um to-do. Isso é bom por que evita que o usuário tenha que clicar/tocar novamente no input para adicionar outro to-do.

## Usabilidade

O placeholder "buscar to-do" está sem contraste com o fundo. Uma possível solução é deixá-lo na cor branca.

O estilo da lista está quebrando ao filtrar ou remover to-dos. Siga a marcação HTML e estilo CSS mostradas na aula que é sucesso.

## Organização de código

### `<!DOCTYPE html>`

Sempre declare um `<!DOCTYPE html>` no início da marcação HTML, isso vai evitar o [Quirks Mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode) do browser.

### Comentários

Não é uma regra, mas evite comentários, pelas razões que [mencionei aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1404).

### Declaração de variáveis

A `toDoContent` foi declarada mas não está sendo usada, então ela pode ser removida do código.

### Formatação

Não sei se rolou alguma formatação automática em seu editor, mas o ideal é que formatações em encadeamentos de métodos deixem explícitos os métodos que estão sendo encadeados:

```javascript
// antes
  todos.filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })

// depois
  todos
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
```

Percebe como fica mais claro onde termina uma invocação e onde começa outra?

### Consistência de code styling

O código está usando aspas simples e aspas duplas. Escolha uma delas e seja consistente nessa escolha.

Funções com a palavra-chave `function` e arrow functions com `const` estão sendo usadas. Novamente, escolha uma delas e seja consistente. Como não há necessidade de usar `this`, sugiro que use arrow functions, pois são mais simples e concisas.

### Nomes de variáveis e funções

Seguindo o princípio de nomeação que mencionei na análise passada, acredito que as renomeações abaixo deixam o código mais descritivo e simples de entender:

- `form` => `formAddTodo`
- `input` => `inputFilterTodos`
- `ul` => `todosContainer`
- `compareEvent` => `filterTodos`
- `inputCompareValue` => `inputValue`
- `hideToDo` => `hideToDos` (plural)
- `showToDo` => `showToDos` (plural)
- `toDoContent` => `todos`
- parâmetros `itemToDo` => `todo`

### Ordem de declarações e invocações de funções

Prefira declarar `hideToDos` e `showToDos` antes de suas invocações. 

Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

## Lógica

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para remover o to-do (em que o valor no qual essa expressão resulta não está sendo aproveitado), apenas um `if` pode ser usado:

```javascript
// antes
arrayElementClasslist.includes('delete') ? clickedElement.parentElement.remove() : ''

// depois
if (arrayElementClasslist.includes('delete')) {
  clickedElement.parentElement.remove()
}
```

## Análises passadas

Alguns pontos acima foram mencionados na [análise do quiz](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1404): comentários e nomes de variáveis e funções.

Como são pontos que se repetiram, recomendo que dê uma atenção maior à eles.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by marcosyoggy** [comment]
As observações descrevem como deveria ter sido feito a aplicação.....sobre o sentido....."disparou o meu  sentido de "aranha-manca" dizendo pra refazer a aplicação...Obrigado pelo FeedBack.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
