### ISSUE TITLE
Resumo da Aula  Funções VS Métodos 02-03  da etapa 03

### ISSUE THREAD

**Issue by AdrianoRepet** [roger-melo-treinamentos/curso-de-js-roger-melo#1781]
FUNÇÕES VS MÉTODOS

Funções e métodos são sinônimos em essência eles fazem a mesma coisa,  podem ser invocados para executar um pedaço de código que faz alguma coisa para gente, então  método e função são a mesma coisa, o que diferencia um método de uma função e a forma como ele é invocado e onde ele é declarado.
Para declarar uma função simplesmente inserimos o nome dela e a abertura e fechamento de parênteses, agora quando vamos invocar um método invés de simplesmente invocar o nome do método e a abertura e fechamento dos parênteses utilizamos a notação de ponto. Métodos são funções que estão associados a objetos ou tipo de dados como strings, os métodos são criados no objeto ou tipo de dados, já as funções são criadas sozinha. Os métodos são funções que fazem alguma ação, e que métodos e funções em essência são a mesma coisa, mais com nomes diferentes e forma diferente de ser criados e invocados.

FUNÇÕES

```js

const name = 'Roger'

const sayHi = () => 'oi'

const greet = sayHi()

console.log(greet)

```

MÉTODOS

```js

const nameInToUppCase = name.toUpperCase()

console.log(nameInToUppCase)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @AdrianoRepet! Rumo à fluência 🔥
