### ISSUE TITLE
Resumo da Aula Template Strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by vitorsmessias** [roger-melo-treinamentos/curso-de-js-roger-melo#1786]
[Resumo da Aula 02-06 da etapa 01.docx](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7123031/Resumo.da.Aula.02-06.da.etapa.01.docx)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @vitorsmessias! Rumo à fluência 🔥
