### ISSUE TITLE
Resumo da Aula Correção dos exercícios da aula 02 - Aula 03-01 da etapa Etapa 02

### ISSUE THREAD

**Issue by jose-rocha** [roger-melo-treinamentos/curso-de-js-roger-melo#1789]
Bem, de longe os exercícios 05 e 06 foram os mais difíceis que achei até agora, mas oque achei mais legal foi os encadeamentos de métodos, o método push  tenho que treinar mais e o lembrar de usar também o join, já o replace estou um pouco familiarizado.

![Summary_Question_06](https://user-images.githubusercontent.com/61214334/132394061-55f6870b-7ff0-4c80-8030-edf72dbd16a3.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @jose-rocha! Rumo à fluência 🔥
