### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1794]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/raphaelprsilva/weather-app

### Maiores dificuldades durante a implementação

As minhas maiores dificuldades são, na maioria das vezes, as mesmas. São elas:

- refatoração do código;
- definição de nomes de variáveis e funções;

E, acredito que se você não tivesse fornecido o Boilerplate HTML + CSS, talvez eu tivesse alguma dificuldade na estilização.

### Menores dificuldades durante a implementação

Por incrível que pareça, desenvolver as funções para fazer as requisições foi tranquilo (graças ao conteúdo).

Dei o máximo de mim e tentei deixar o código bem legível.

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

> #### As minhas maiores dificuldades são, na maioria das vezes, as mesmas. São elas: refatoração do código; definição de nomes de variáveis e funções;

Vc citou o maior desafio de todo desenvolvedor xD

Considerando que nomeação ou renomeação geralmente são parte de um refactoring, refactoring sempre será o seu maior desafio. Mas com o tempo, vai ficando mais fácil (o que não quer dizer que seja fácil).

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Você também resetou o input do form para que o usuário não tivesse que clicá-lo/tocá-lo novamente antes de inserir uma nova cidade.

## Organização de código

### Nomes de variáveis e funções

Na `setWeatherImageSrc`, `param` pode ser mais descritivo se for nomeado deixando claro o tipo de boolean que ele armazena. 

Nesse caso, eu o renomearia com o mesmo nome do argumento que foi recebido, `IsDayTime`. `IsDayTime` tende a deixar a expressão do ternário mais compreensível:

```javascript
// antes
param ? weatherImage.src = './src/day.svg' : weatherImage.src = './src/night.svg';

// depois
IsDayTime ? weatherImage.src = './src/day.svg' : weatherImage.src = './src/night.svg';
```

---

Não é uma regra mas, geralmente, nomear o parâmetro da função com o mesmo nome do argumento que ela recebeu deixa o código mais coerente. 

No caso da `setAllInnerHtml`, mesmo que os argumentos que ela recebeu comecem com a primeira letra maiúscula, eu nomearia os parâmetros da mesma forma:

```javascript
const setAllInnerHtml = (LocalizedName, WeatherText, Temperature) => {};
```

## Lógica

### Ternário

Geralmente, ternários não são usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para de fato executar a atribuição para do src de `weatherImage` (em que o valor no qual essa expressão resulta não está sendo aproveitado), é possível usar o ternário apenas para obter a string, se baseando no valor da `IsDayTime`:

```javascript
// antes
const setWeatherImageSrc = (IsDayTime) => {
  IsDayTime ? weatherImage.src = './src/day.svg' : weatherImage.src = './src/night.svg';
};

// depois
const setWeatherImageSrc = (IsDayTime) => {
  weatherImage.src = IsDayTime ? './src/day.svg' : './src/night.svg';
};
```

## Refatoração

Se vc quiser, é possível deixar o código mais conciso, eliminando as consts `cityWeatherInfos` e `weatherData`:

```javascript
// antes
const cityWeatherInfos = await fetchData(getCityUrl(cityInput));
const [{ Key, LocalizedName }] = cityWeatherInfos;

const weatherData = await fetchData(getCityWeatherUrl(Key));
const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = weatherData;

// depois
const [{ Key, LocalizedName }] = await fetchData(getCityUrl(cityInput));
const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = 
  await fetchData(getCityWeatherUrl(Key));
```

Outra abordagem possível é a separação de dados e view (renderização dos elementos). 

Olha só...

Num primeiro momento, eu vou voltar pra dentro da `renderWeatherData` todo o código que irá renderizar as informações na tela:

```javascript
const renderWeatherData = async (event) => {
  event.preventDefault();

  const cityInput = event.target.city.value;

  const [{ Key, LocalizedName }] = await fetchData(getCityUrl(cityInput));
  const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = 
    await fetchData(getCityWeatherUrl(Key));

  cityName.innerHTML = LocalizedName;
  weatherText.innerHTML = WeatherText;
  temperatureValue.innerHTML = Temperature.Metric.Value;
  weatherImage.src = IsDayTime ? './src/day.svg' : './src/night.svg';
  weatherIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />`;
  weatherContainer.classList.remove('d-none');
  weatherForm.reset();
}
```

Observe que essa função basicamente faz duas coisas:

1. Obtém os dados;
2. Renderiza os dados.

É possível fazer com que a obtenção dos dados fique isolada em uma função. Como essa função irá **obter** os dados, ela pode ser nomeada como `getWeatherData`:

```javascript
const getWeatherData = () => {
  const cityInput = event.target.city.value;
  const [{ Key, LocalizedName }] = await fetchData(getCityUrl(cityInput));
  const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = 
    await fetchData(getCityWeatherUrl(Key));
}

const renderWeatherData = async (event) => {
  event.preventDefault();

  cityName.innerHTML = LocalizedName;
  weatherText.innerHTML = WeatherText;
  temperatureValue.innerHTML = Temperature.Metric.Value;
  weatherImage.src = IsDayTime ? './src/day.svg' : './src/night.svg';
  weatherIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />`;
  weatherContainer.classList.remove('d-none');
  weatherForm.reset();
}
```

No código acima, dados e renderização estão separados, certo?

Porém, como a `renderWeatherData` precisa desses dados para renderizar o conteúdo, é possível fazer a `getWeatherData` retornar os dados quando for invocada. 

Observe também que `async` precisa ser inserido na declaração da `getWeatherData` (pois essa função executa um request) e `event` precisa ser inserido como argumento da invocação dela, por que ele está sendo usado dentro dela:

```javascript
const getWeatherData = async (event) => {
  const cityInput = event.target.city.value;
  const [{ Key, LocalizedName }] = await fetchData(getCityUrl(cityInput));
  const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = 
    await fetchData(getCityWeatherUrl(Key));
  
  return { LocalizedName, IsDayTime, Temperature, WeatherIcon, WeatherText }
}

const renderWeatherData = async (event) => {
  event.preventDefault();

  const { LocalizedName, IsDayTime, Temperature, WeatherIcon, WeatherText } = 
    await getWeatherData(event)

  cityName.innerHTML = LocalizedName;
  weatherText.innerHTML = WeatherText;
  temperatureValue.innerHTML = Temperature.Metric.Value;
  weatherImage.src = IsDayTime ? './src/day.svg' : './src/night.svg';
  weatherIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />`;
  weatherContainer.classList.remove('d-none');
  weatherForm.reset();
}
```

Só essa ideia de separar dados da view já ajuda a separar melhor as responsabilidades. 

Se vc quiser ir além, vc pode melhorar a legibilidade de algumas expressões dentro da `renderWeatherData`. Olha só:

```javascript
// antes
weatherImage.src = IsDayTime ? './src/day.svg' : './src/night.svg';
weatherIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />`;

// depois
weatherImage.src = getWeatherImgSrc(IsDayTime);
weatherIcon.innerHTML = getWeatherIconImg(WeatherIcon);
```

`getWeatherImgSrc` é uma função que apenas retorna uma string:

```javascript
const getWeatherImgSrc = (IsDayTime) => 
  IsDayTime ? './src/day.svg' : './src/night.svg';
```

O mesmo vale para a `getWeatherIconImg`:

```javascript
const getWeatherIconImg = (WeatherIcon) => 
  `<img src="./src/icons/${WeatherIcon}.svg" />`;
```

Ambas são funções puras. Ou seja:

- Dado o mesmo input, sempre retornam o mesmo output;
- Não executam efeito colateral.

Em JavaScript, não é possível ter um código 100% puro, devido à natureza da linguagem. Porém, quanto mais funções puras a sua aplicação tiver, ela vai tender a ter menos bugs e ser mais fácil de testar e manter.

Funções puras são um assunto que vou abordar quando falar sobre programação funcional de forma mais profunda =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by raphaelprsilva** [comment]
Olá Roger!

As observações fizeram total sentido. Ainda preciso melhorar em vários aspectos. Mas é um caminho.

Vou tentar separar o código em funções com responsabilidade única. Mas acredito que só com a prática e tempo, para melhorar os pontos mencionados por você.

Vou buscar não gerar algum efeito colateral com o ternário. 😂

Além disso, muito obrigado pelo review e pelos detalhes abordados.

Um abração!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
