### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1796]
# Obtendo, adicionando, removendo e alternando classes CSS

### Obtendo as classes de um elemento

→ Quando precisamos listar as classes de um elemento basta usarmos a propriedade "classList" junto ao elemento

```
const paragraph = document.querySelector ( 'p' )

console.log(paragraph.classList) -> vai aparecer no console a lista de classes que este elemento possui.
```

### Adicionando classe a um elemento

→ Para adicionar classes a um elemento usamos a mesma propriedade "classList" seguida do método "add( )" e como argumento deste método a gente informa uma string com a classe que vamos adicionar neste elemento.

```
const paragraph = document.querySelector ( 'p' )

paragraph.classList.add( 'error' ) -> vai adicionar a classe "erro" ao elemento "paragraph".
```

### Removendo classe de um elemento

→ Para remover classes de um elemento usamos a mesma propriedade "classList" seguida do método "remove( )" e como argumento deste método a gente informa uma string com a classe que vamos remover deste elemento.

```
const paragraph = document.querySelector ( 'p' )

paragraph.classList.remove( 'error' ) -> vai remover a classe "erro" do elemento "paragraph".
```

⇒ Diferença entre as propriedades "innerText" e "textContent":

1 - a "innerText" exibe o texto visível de um elemento.

2 - a "textContent" exibe todo o texto de um elemento independente de estar visível ou não.

### Removendo ou adicionando classe a um elemento dependendo do status atual

⇒ Método "toggle( )"

Para adicionarmos uma classe a um elemento quando o mesmo não possui a referida a classe ou removermos a classe quando o mesmo possuí-la usamos o método "toggle( )" da propriedade "classList" passando como argumento a string com o nome da classe a ser verificada/adicionada/removida.

```
const title = document.querySelector ( 'h1' )

title.classList.toggle( 'test' ) -> se a classe "test" estiver no elemento "title" ela será removida e se a classe ""test não estiver no elemento "title" ela será adicionada.
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @JuFML! Rumo à fluência 🔥
