### ISSUE TITLE
Quiz Interativo (Primeira Versão)

### ISSUE THREAD

**Issue by BrunoDElias** [roger-melo-treinamentos/curso-de-js-roger-melo#18]
Realizei uma versão com um quiz brasileiro, com uma quantidade diferente de respostas para cada pergunta. De início não tive muita dificuldade para implementar um quiz igual o mostrado em aula, porém tentei fazer o quiz marcar as respostas corretas (caso o usuário acertar marcava com bg-success) e as erradas (caso errar marcava a resposta dele com bg-danger) só que foi um fracasso pois não consegui fazer a marcação das respostas do usuário para assim poder usar o classList.add() =/

No geral, fiquei alegre com o resultado e principalmente com a evolução que  tive em tão pouco tempo!!! Estou adorando o curso e gostaria de saber se o professor teria alguma dica de livro ou site para eu ler sobre design pattern do javascript =)

Obrigado desde já por todo esse aprendizado!!!

link do repositório: https://github.com/BrunoDElias/QuizInterativo

**Comment by Roger-Melo** [comment]
Parabéns pelo projeto @BrunoDElias!🎉

Nas próximas aulas você verá que iremos melhorar o código desse projeto.

Se você sentir que consegue construí-lo sozinho, inclusive com as refatorações que mostrarei, não hesite em fazer dele uma peça de seu portfólio.

Sobre design patterns, recomendo que não foque nisso agora. O design pattern mais importante, poderoso e manutenível que você continuará aprendendo é o que estou mostrando no CJRM: simples funções. Se for importante falar sobre design patterns, acrescentarei esse conteúdo posteriormente, em etapas futuras.

Continue investindo seu tempo e energia apenas no CJRM e na documentação do MDN. Após finalizar o curso, aí eu recomendo você partir para outras fontes de estudo, que vão te ajudar a entender melhor o que você já aprendeu, ou ainda te ensinar coisas novas.

Coloque foco total em apenas uma fonte de estudos por vez, e você vai ver que vai conseguir evoluir muito mais rápido.

Parabéns pelo projeto e conte comigo para chegar à fluência.

No que precisar, é só chamar aqui =)

**Comment by Roger-Melo** [comment]
@BrunoDElias [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/19#issuecomment-663207986) eu falo uma forma de colorir as respostas erradas e corretas do quiz.
