### ISSUE TITLE
Resumo da Aula Break e Continue 03-03 da etapa 02

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1800]
**BREAK**
- Este comando encerra o loop atual ou o loop que foi informado, transferindo o controle da execução do programa para o comando seguinte.

**CONTINUE**
- Termina a atual iteração em que se encontra e continua a execução deste laço com a próxima iteração.
_Diferente_ do **BREAK** ele não termina a execução do laço completamente, em vez disso:
-No laço **while** ele volta à condição.
-No laço **for,** ele volta a expressão, atualizando-a.

**Comment by Roger-Melo** [comment]
Excelente @carlosebs! Rumo à fluência 🔥
