### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by josemalexandre** [roger-melo-treinamentos/curso-de-js-roger-melo#1801]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/josemalexandre/app-quiz-cjrm.git

### Maiores dificuldades durante a implementação

Minha maior dificuldade foi criar o template em Boostrap. Preciso estudar mais :(

### Menores dificuldades durante a implementação

O desenvolvimento do app foi tranquilo :)

**Comment by Roger-Melo** [comment]
Olá @josemalexandre.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @josemalexandre!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Minha maior dificuldade foi criar o template em Boostrap. Preciso estudar mais :(

O uso Bootstrap (ou qualquer outra lib CSS) é opcional. Eu uso para poupar tempo na hora de pensar no design da interface da aplicação. Veja o que fica mais confortável para vc =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Você entendeu como evitar `else if` e `else`.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Total de perguntas

É possível deixar mais claro o total de perguntas que o quiz tem. Pode ser algo como "Você acertou 3 de 5 perguntas". Isso é bom para a usabilidade, pq traz clareza do progresso do usuário no quiz e ele não precisa conferir quantas perguntas o quiz tem.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Local da exibição dos pontos

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![image](https://user-images.githubusercontent.com/29297788/132676171-9e91fdf2-fefe-4f7c-b722-3882d856007d.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Resultado - Clique aqui".

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso, acredito que as renomeações abaixo deixam o código mais descritivo:

- `quizHistoryBrazil` => `showResult`
- `template` => `correctAnswers`
- `answers` => `userAnswers`
- `answer` => `userAnswer` (parâmetro do callback do `forEach`)
- `resultaMsg` => `renderResult`. Observe que  "resulta" está em pt-BR. Fique atento à consistência do idioma no qual o código é escrito.

### Refatoração

Na `renderResult` (antiga `resultaMsg`), os parênteses não são necessários. Uma alternativa aos parênteses é usar o bloco da função:

```javascript
// antes
const renderResult = () =>
  (result.textContent = `Você acertou ${score} pergunta(s).`);

// depois
const renderResult = () => {
  result.textContent = `Você acertou ${score} pergunta(s).`
}
```

## Lógica

### Legibilidade em expressões

Acredito que se `resulWarning` e `resultPrimary` usarem `||`, fica mais rápido entender a lógica delas:

```javascript
// antes
const resulWarning = score > 0 && score < 3;
const resultPrimary = score > 2 && score < 5;

// depois
const resulWarning = score === 1 || score === 2;
const resultPrimary = score === 3 || score === 4;
```

### Eliminando ifs

Eu não sei se vc chegou em aulas onde mostro essa técnica, mas é possível eliminar os ifs do código abaixo:

```javascript
  if (resultDanger) {
    result.classList.add("bg-danger");
    renderResult();
    return;
  }

  if (resulWarning) {
    result.classList.add("bg-warning");
    renderResult();
    return;
  }

  if (resultPrimary) {
    result.classList.add("bg-primary");
    renderResult();
    return;
  }

  result.classList.add("bg-success");
  renderResult();
```

O primeiro passo é criar uma função que apenas retorna o nome da classe baseada na pontuação do usuário. 

Como essa função irá ser invocada para que a classe CSS do resultado seja **obtida**, ela pode se chamar `getResultClassList`:

```javascript
const getResultClassList = score => {
  if (score === 0) {
    return "bg-danger"
  }

  if (score === 1 || score === 2) {
    return "bg-warning"
  }

  if (score === 3 || score === 4) {
    return "bg-primary"
  }

  return "bg-success"
}

const renderResult = () => {
  result.textContent = `Você acertou ${score} pergunta(s).`
}

result.classList.add(getResultClassList(score));
renderResult();
```

Observe que é apenas uma função que retorna uma string e essa string é inserida como argumento da invocação de `result.classList.add`. Veja também que agora, é necessária apenas uma invocação da função `renderResult`.

Feito isso, é possível eliminar os ifs dentro da `getResultClassList`.

Uma forma de fazer isso é usando um objeto no qual o nome das propriedades correspondem à pontuação do usuário, e os valores correspondem às classes CSS das pontuações:

```javascript
const getResultClassList = score => {
  const scores = {
    0: "bg-danger",
    1: "bg-warning",
    2: "bg-warning",
    3: "bg-primary",
    4: "bg-primary"
  }

  return scores[score] || "bg-success"
}
```

Observe também que no código acima, se `scores[score]` resulta em 5, `"bg-success"` é retornado.

É possível deixar essa função mais concisa, eliminando a const `scores`:

```javascript
const getResultClassList = score => {
  return {
    0: "bg-danger",
    1: "bg-warning",
    2: "bg-warning",
    3: "bg-primary",
    4: "bg-primary"
  }[score] || "bg-success"
}
```

Como a função apenas retorna o valor de uma propriedade, é possível deixá-la ainda mais concisa, usando o `return` implícito da arrow function:

```javascript
const getResultClassList = score => ({
  0: "bg-danger",
  1: "bg-warning",
  2: "bg-warning",
  3: "bg-primary",
  4: "bg-primary"
})[score] || "bg-success"
```

Como a `getResultClassList` recebe o `score` por parâmetro, ela não-necessariamente precisa ficar dentro do callback do envio do `form`:

```javascript
const getResultClassList = score => ({
  0: "bg-danger",
  1: "bg-warning",
  2: "bg-warning",
  3: "bg-primary",
  4: "bg-primary"
})[score] || "bg-success"

const showResult = (event) => {
  // ...
};
```

Como `renderResult` agora só está sendo invocada uma vez (e a expressão que ela executa é legível), essa expressão pode ser inserida diretamente após a manipulação da classe CSS:

```javascript
result.classList.add(getResultClassList(score));
result.textContent = `Você acertou ${score} pergunta(s).`
```

Após essas modificações, o resultado seria algo desse tipo:

```javascript
const form = document.querySelector(".form-quiz");
const result = document.querySelector(".result");

const getResultClassList = score => ({
  0: "bg-danger",
  1: "bg-warning",
  2: "bg-warning",
  3: "bg-primary",
  4: "bg-primary"
})[score] || "bg-success"

const showResult = (event) => {
  event.preventDefault();

  const correctAnswers = ["B", "A", "A", "B", "C"];

  let score = 0;

  const userAnswers = [
    form.question1.value,
    form.question2.value,
    form.question3.value,
    form.question4.value,
    form.question5.value,
  ];

  userAnswers.forEach((userAnswer, idx) => {
    if (userAnswer === correctAnswers[idx]) {
      score++;
    }
  });

  result.classList.add(getResultClassList(score));
  result.textContent = `Você acertou ${score} pergunta(s).`
};

form.addEventListener("submit", showResult);

```

Mas claro, nas aulas seguintes, você verá formas de refatorar ainda mais o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

PS: ao ser enviado pela 2ª vez com um resultado diferente, a cor do warning anterior permanece.

1. Por que vc acha que isso aconteceu?
2. Qual possível solução vc tem em mente para resolver este problema? Faça e mostre o código =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)

**Comment by josemalexandre** [comment]
As observações fizeram total sentido. Já refatorei o código conforme sua orientação. 
Estou quebrando a cabeça pra melhorar a exibição da pontuação. Acho que vou fazer um popup.

Desculpa não ter respondido mais cedo, mas só agora consegui revisar o código.

Muito obrigado!!!
