### ISSUE TITLE
Etapa 4, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by KauaiStaingel** [roger-melo-treinamentos/curso-de-js-roger-melo#1802]
na propriedade getColorsMassage() quando fora usar o replace, a ', ' continuou no array, como podemos tirar ela de la?
consta no video de correção. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
@KauaiStaingel essa é uma forma:

```javascript
const colors = ['Azul Atlantic', 'Vermelho Crimson', 'Preto Mystic']

console.log(colors.join(' e ').replace(' e ', ', '))
```

Conforme for avançando no treinamento, você descobrirá formas dinâmicas para resolver esse tipo de problema e que se adequam à arrays de qualquer comprimento =)

**Comment by KauaiStaingel** [comment]
tentei dessa maneira porem nao funcionou

```
getColorMassage(){
    return`${this.name} esta disponivel nas cores ${this.colors.join(', ').replace(`,  ${this.colors[this.colors.length - 1]}` , ` e ${this.colors[this.colors.length - 1]}`)}`
  }
```

**Comment by Roger-Melo** [comment]
Qual foi o erro?

**Comment by KauaiStaingel** [comment]
ele n da nenhum erro

no video de correcao ficou assim "o Passat esta disponível nas cores Azul Atantic, Vermelho Crimson**_, e_** Preto Mystic"

esse , e oq estou tentando arrumar
o resultado com o codigo q enviei foi esse:
HB20 esta disponivel nas cores Black, White, Blue

n tem mensagem de erro, porem tambem n aconteceu a troca da ',' pelo 'e'

**Comment by ElaineDelgado** [comment]
```js
${this.colors.join(', ').replace(`,  ${this.colors[this.colors.length - 1]}`,

```
No replace, há dois espaços entre o (`,  e o ${this.colors... 
Removi um espaço e funcionou aqui!

**Comment by Roger-Melo** [comment]
@KauaiStaingel nesse caso, basta substituir os dois espaços em branco da primeira string do `replace` por apenas um, como a @ElaineDelgado falou =)

E como eu disse ali em cima, conforme for avançando no treinamento, vc descobrirá formas mais elegantes e simples para resolver esse tipo de problema =)

**Comment by KauaiStaingel** [comment]
não cheguei a reparar no espaço a mais, obrigado pela atenção!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
