### ISSUE TITLE
Resumo da Aula Data e hora em JavaScript - Aula 01-02 da etapa 10

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1811]
Datas são um tipo de objeto, ou seja, são tipos de referência. Criamos uma data em JavaScript através de um construtor de datas, utilizando a palavra *new* antes do tipo. E quando uma data é criada, ela estará sempre com o momento atual. Por exemplo, vamos criar uma data com o construtor de datas e exibir no console:

```jsx
const present = new Date();

console.log(present);

// Fri Sep 10 2021 15:07:35 GMT-0300 (Horário Padrão de Brasília)
```

Apesar de o retorno parecer uma *string*, basta utilizarmos o `typeof` para verificamos que é de fato um objeto. Podemos também retornar partes dessa data, como dia, mês, ano, dia da semana, etc. Além das partes de uma data, temos também o *timestamp*, que são os milissegundos desde 01/01/1970 até o momento atual, e que nos permite comparar datas. Vamos ver cada função e o que cada uma retorna, utilizando a constante criada no código acima:

```jsx
console.log(typeof present); // object

console.log("getFullYear: ", present.getFullYear()); // getFullYear:  2021
console.log("getMonth: ", present.getMonth()); // getMonth:  8
console.log("getDate: ", present.getDate()); // getDate:  10
console.log("getDay: ", present.getDay()); // getDay:  5
console.log("getHours: ", present.getHours()); // getHours:  15
console.log("getMinutes: ", present.getMinutes()); // getMinutes:  10
console.log("getSeconds: ", present.getSeconds()); // getSeconds:  40

console.log("timestamp: ", present.getTime()); // timestamp:  1631297440963

console.log("toDateString: ", present.toDateString()); // toDateString:  Fri Sep 10 2021
console.log("toTimeString: ", present.toTimeString()); // toTimeString:  15:10:40 GMT-0300 (Horário Padrão de Brasília)
console.log("toLocaleString: ", present.toLocaleString()); // toLocaleString:  10/09/2021 15:10:40
```

Atenção: Os meses e os dias da semana tem contagem *zero based*, ou seja, janeiro é o mês zero, fevereiro é o mês 1, e assim sucessivamente, assim como domingo é o dia zero, segunda-feira é o dia 1 é assim sucessivamente.

---

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência 🚀
