### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1812]
# Criando e removendo elementos do DOM

## Removendo um elemento do DOM

→ Um elemento pode ser removido do DOM utilizando a método ".remove( )" no objeto a ser removido.

```
HTML

<h1>Todos</h1>

   <ul>
      <li>Comprar frango</li>
      <li>Ler livro</li>
      <li>Tocar violão</li>
      <li>Pagar as contas</li>
   </ul>

   <button>Clique aqui</button>

JS

const ul = document.querySelector('ul')
	
ul.remove() -> o elemento <ul> será removido do DOM e nnão aparecerá no browser
```

→ Para remover mais de um elemento é preciso selecionar todas as tags alvo, iterar por ela com o "forEach" para adicionar o "remove" em cada uma delas, e quando aquele elemento sobre o evento ele será removido do DOM.

```
HTML

<h1>Todos</h1>

   <ul>
      <li>Comprar frango</li>
      <li>Ler livro</li>
      <li>Tocar violão</li>
      <li>Pagar as contas</li>
   </ul>

   <button>Clique aqui</button>

JS

const lis = document.querySelectorAll('li')
	
lis.forEach( (li) => {
	 li.addEventListener('click', (event) =>
const clikedElement = event.target
			clikedElement.remove()
}) -> quando clicar na "li" a <li> clicada ira ser removida do DOM e não aparecerá mais no browser
```

## Adicionando um elemento do DOM

→ Um elemento pode ser adicionado ao DOM utilizando a propriedade ".innerHTML" no objeto pai.

```
HTML

<h1>Todos</h1>

   <ul>
      <li>Comprar frango</li>
      <li>Ler livro</li>
      <li>Tocar violão</li>
      <li>Pagar as contas</li>
   </ul>

   <button>Adicionar Item</button>

JS

const ul = document.querySelector('ul')

const button = document.querySelector('button')
	
button.addEventListener('click', ( ) => {
	ul.innerHTML += `<li>Novo item</li>`
}) -> quando clicar no botão a <li> dentro do método addEventListener será adicionada ao DOM e aparecerá no browser.
```

→ Uma outra forma de adicionar um elemento ao DOM é usando o método "createElement( )" passando como argumento o nome da tag que a gente quer criar. Este método vai criar a tag "li", mas o conteuda da tag deverá ser passado usando a propriedade "textContent". E depois de tudo criado é preciso adicionar este elemento novo ao DOM. Para isso podemos usar no elemento pai (neste caso a tag 'ul') o método ".append( )" passando como argumento o nome do elemento criado (o append colocará o novo elemento no final da lista) ou o método ".prepend( )" passando como argumento o nome do elemento criado (o prepend colocará o novo elemento no início da lista)

São três passos:

1. Cria o elemento com o método "createElement( )" passando como argumento o nome da tag que a gente quer criar.
2. Seta o conteúdo deste elemento que foi criado no primeiro passo com a propriedade "textContent"
3. Adiciona este elemento como primeiro filho usando o método ".prepend( )" no elemento pai e passando como argumento o nome do elemento criado ou como último filho usando o método ".prepend( )" no elemento pai passando como argumento o nome do elemento criado.

```
HTML

<h1>Todos</h1>

   <ul>
      <li>Comprar frango</li>
      <li>Ler livro</li>
      <li>Tocar violão</li>
      <li>Pagar as contas</li>
   </ul>

   <button>Adicionar Item</button>

JS

const ul = document.querySelector('ul')

const button = document.querySelector('button')
	
button.addEventListener('click', ( ) => {
	const li = document.createElement('li')
	li.textContent = 'Novo item'
}) -> quando clicar no botão a <li> dentro do método addEventListener será adicionada ao DOM e aparecerá no browser.
```

Event reference - MDN:

[https://developer.mozilla.org/en-US/docs/Web/Events](https://developer.mozilla.org/en-US/docs/Web/Events)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuFML, rumo à fluência 🚀
