### ISSUE TITLE
Etapa 08, O método sort - Aula 02-02

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1813]
Eu entendi a sua explicação do método sort, porém o que confundiu minha cabeça foi como o javascript por de baixo dos panos executa a comparação.

```js
const theBigFamily = [
  { name: 'Lineu', score: 20 },
  { name: 'Nenê', score: 10 },
  { name: 'Tuco', score: 50 },
  { name: 'Bebel', score: 30 },
  { name: 'Agostinho', score: 70 }
]
```

Nesta explicação eu entendi que se quiséssemos colocar em ordem crescente, o score do lineu iria comparar com o score do nenê, e como o score do nenê é menor, o score do nenê iria ser posicionado antes do score do lineu, após isso, a comparação seria entre o score do lineu e o score do tuco, como o score do lineu é menor que o score do tuco, o do lineu iria antes, e então a nova comparação seria entre o tuco e a bebel, como a bebel é menor, ela iria antes..

A dúvida é a seguinte:
E se o score do Agostinho fosse 5, a comparação iria fazer o agostinho vir antes da bebel e não ficaria ordenado, o array é percorrido mais de uma vez?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Dê uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/307#issuecomment-803723638) e se tiver alguma dúvida, pode comentar aqui =)
