### ISSUE TITLE
Resumo da Aula Funções da etapa 03

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1815]
### Funções
- Elas fazem parte do 'object', é são fundamentais para a estrutura de uma aplicação;
- Eu acho que quase tudo é uma função em JavaScript;
- Nela podemos passar argumentos e reutilizar quando quiser, passando valores para dentro e depois devolver (output);

### Function declaration
```js
// Possui o 'hoisting' (içamento, puxar para cima, levantar, alçar);
// Não é interessante fazer isso em um código, pode ficar confuso.

raiseUp()

function raiseUp(){
  console.log('oi')
}
```
###  Function expression
```js
// Não têm hosting;
// Ela e declarada em uma variável ou constante(dê preferência);
// Podemos debugar melhor;
// Na maioria dos casos vamos preferir as funções no topo do código.

const doNotRaise = function() {
console.log('não têm elevação, ótima para manter o código organizado e legível')
}
doNotRaise()
```
### Argumentos, Parâmetros e default
- Nas funções podemos passar múltiplos parâmetros;
- Parâmetros são separados por vírgulas
- Não esquecer de atribuir os valores a variável, para não dar undefined;

```js
const myFunc = function(name, lastName) {  // Parâmetros
console.log(`Oi, ${name} ${lastName}`
}
myFunc('Carlos', 'Silva') // Argumentos
   // Oi, Carlos Silva
```
**Observação:** A ordem dos argumentos devem seguir a ordem dos parâmetros.

- Podemos passar na inicialização dos parâmetros, valores definidos para evitar undefined, caso o valor não seja lançado no argumento na hora da invocação
```js
const myFunc = function(name = 'Garibald', lastName = 'Meneguel') {  // Parâmetros
console.log(`Oi, ${name} ${lastName}`
}
myFunc() // Sem Argumentos
   // Oi, Garibald Meneguel
```

**Comment by Roger-Melo** [comment]
Show @carlosebs, rumo à fluência! 🙌🏻
