### ISSUE TITLE
Aplicação: To-do List.

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#1816]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/dracoalv/Todo-List-Aplication

### Maiores dificuldades durante a implementação

Ficou claro que o uso do **event.target** seria vital para quem futuramente for estudar react (meu caso), e foi tranquilo para eu implementar os seus usos, porém tive que voltar e repetir algumas aulas para lembrar e entender que o que eu estava representando com o mesmo. Minhas maiores dificuldades foram criar funções isoladas e confrontar o uso do **event.target**, demorei, porém consegui. 

E neste caso também tive dificuldades pra tornar o código mais legível, talvez foi falta de criatividade ou cansaço.

Após estes incômodo eu li o MDN a respeito do **dataset** porém também ficou difícil para eu assimilar sem a sua didática, o que me deixou empolgado pra tentar solucionar sozinho, embora fiquei o domingo nisso, não consegui resolver a questão.

A lógica da aplicação embora simples, me senti inseguro para realizar uma aplicação sem seguir alguns passos.

### Menores dificuldades durante a implementação

Obter referências e acredito que entendi bem os listener de eventos e o uso do event como parâmetro,

**Comment by Roger-Melo** [comment]
Olá @dracoalv.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @dracoalv!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> #### Ficou claro que o uso do event.target seria vital para quem futuramente for estudar react (meu caso), e foi tranquilo para eu implementar os seus usos, porém tive que voltar e repetir algumas aulas para lembrar e entender que o que eu estava representando com o mesmo. 

Sempre use o `console.log` para checar se as expressões que vc está inserindo em seu código estão retornando os valores que vc espera.

> #### Minhas maiores dificuldades foram criar funções isoladas e confrontar o uso do event.target, demorei, porém consegui. E neste caso também tive dificuldades pra tornar o código mais legível, talvez foi falta de criatividade ou cansaço.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

> #### Após estes incômodo eu li o MDN a respeito do dataset porém também ficou difícil para eu assimilar sem a sua didática, o que me deixou empolgado pra tentar solucionar sozinho, embora fiquei o domingo nisso, não consegui resolver a questão.

Show. Eu adicionei [mais uma dica](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-24/app.js#L39) no enunciado do exercício pra ver se fica mais claro (sem "entregar o ouro") xD

Nas próximas aulas vc descobrirá do que se trata =)

> #### A lógica da aplicação embora simples, me senti inseguro para realizar uma aplicação sem seguir alguns passos.

Não sei o quão dependente vc ficou das aulas na hora de revisar, mas se sentir que precisa, faça uma revisão [raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x).

É importante que o que foi visto até aqui esteja consolidado pra vc, pois o conteúdo fica cada vez mais denso à medida em que vc vai avançando.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Vc se lembrou de usar o `.reset()` para que o usuário não precisasse clicar/tocar no input novamente.

## Organização de código

### Estrutura de diretórios e arquivos

Prefira seguir a estrutura de arquivos e diretórios mostrada nas aulas. 

A raiz do projeto precisa ter um `index.html`, caso contrário, observe o que é exibido se `/src` é removido da url:

![image](https://user-images.githubusercontent.com/29297788/133090223-0529dac6-5023-4acf-bc12-1aab18ca005d.png)

Quando o `index.html` está na raiz do projeto, vc não tem esse tipo de problema =)

### Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

### Nomes de variáveis e funções

Como a `searchTodo` irá manipular vários to-dos, eu a renomearia para `searchTodos` (no plural).

### Indentação

Indentação é um dos pilares de um código mais legível. No segundo encadeamento de métodos de arrays na `searchTodos`, prefira indentar as invocações de `filter` e `forEach`:

```javascript
// antes
  Array.from(todosContainer.children)
  .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
  .forEach(todo => {
    todo.classList.remove('hidden')
    todo.classList.add('d-flex')
  })

// depois
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
```

## Lógica

`addTodo`, `removeTodo` e `searchTodos` podem ser apenas referenciadas como callback dos listeners de eventos. 

O `preventDefault` pode ser invocado dentro da `addTodo` e tanto `addTodo` como `removeTodo` recebem `event` por parâmetro:

```javascript
const addTodo = event => {
  event.preventDefault()
  // ...
}

const removeTodo = event => {
  // ...
}

const searchTodos = () => {
  // ...
}

formAddTodo.addEventListener('submit', addTodo)
todosContainer.addEventListener('click', removeTodo)
searchInputTodo.addEventListener('input', searchTodos)
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by dracoalv** [comment]
Fizeram sentido sim senhor, acabei de corrigir todos os detalhes, antes de continuar vou tentar implementar do zero sem assistir nenhuma aula, obrigado pelo suporte.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
