### ISSUE TITLE
Resumo da Aula Timestamps e comparações - Aula 01-03 da etapa 10

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1818]
Para fazermos comparações entre datas precisamos obter o *timestamp* das duas datas em questão. Lembrando que o *timestamp* de uma data retorna a quantidade de milissegundos de 01/01/1970 até o momento atual, e obtemos através do método `getTime()`. Então vamos supor que queiramos saber quantos dias faltam para chegar o natal. Para isso precisamos retornar o *timestamp* da data atual e o *timestamp* da data do natal. Após isso precisamos subtrair o *timestamp* do natal pelo *timestamp* atual. O resultado será a diferença entre as duas datas em milissegundos. Com esses milissegundos em mãos, podemos fazer algumas conversões interessantes, e uma delas será a de quantos dias separam estas duas datas. Vamos ver no exemplo abaixo:

```jsx
const currentDate = new Date();
const christmasDate = new Date('Dec 25 2021 00:00:00');

const difference = christmasDate.getTime() - currentDate.getTime();

const differenceInSeconds = Math.round(difference / 1000);
console.log(differenceInSeconds);

const differenceInMinutes = Math.round(differenceInSeconds / 60);
console.log(differenceInMinutes);

const differenceInHours = Math.round(differenceInMinutes / 60);
console.log(differenceInHours);

const differenceInDays = Math.round(differenceInHours / 24);

console.log(`Faltam ${differenceInDays} dias para o Natal.`);
```

No exemplo acima exibimos no console quantos segundos, minutos, horas e dias faltam para a chegada do natal.

---

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas, rumo à fluência! 🙌🏻
