### ISSUE TITLE
Resumo da Aula 02-03 scrollTo da etapa 07

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#182]
É um método responsável por fazer um scroll na página para uma posição específica que será passada por parâmetro.

**Argumentos**

1. Coordenada do eixo X da esquerda pra direita.
2. Coordenada do eixo Y de cima pra baixo.

Mas há uma alternativa há essa forma apresentada acima para passagem de parâmetro, que é por meio de um objeto. Este objeto que pode ser passado como argumento do `Window.scrollTo()` contém algumas configurações na qual a página será scrollada, ele pode receber as seguintes propriedades: { top, left, behavior }. Top e left funcionam da mesma forma como foi apresentado acima, enquanto o `behavior` vai configurar a velocidade com que o scroll irá acontecer, podendo receber dois valores: `auto (default)` & `smoth (suave)`.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! Rumo à fluência 🚀
