### ISSUE TITLE
Etapa 3, nome do vídeo: Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### ISSUE THREAD

**Issue by DiegoSampaio80** [roger-melo-treinamentos/curso-de-js-roger-melo#1822]
Oi, Roger.

Referente ao exercício 09, uma dúvida, apesar de rever o vídeo algumas vezes não ficou claro para mim porque utilizou o parâmetro "...= callback =>..." como uma invocação da função dentro do bloco "callback( )".

``` 
const invokeCallback = callback => {
  callback()
}

const logName = () => {
  console.log("Diego")
}
invokeCallback(logName)
 ```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @DiegoSampaio80!

> #### Referente ao exercício 09, uma dúvida, apesar de rever o vídeo algumas vezes não ficou claro para mim porque utilizou o parâmetro "...= callback =>..." como uma invocação da função dentro do bloco "callback( )"

O parâmetro `callback` recebeu a referência da função que foi inserida como argumento da `invokeCallback`. Você pode visualizar isso no console se executar o código abaixo:

```javascript
const invokeCallback = callback => {
  console.log(callback)
  callback()
}

const logName = () => {
  console.log("Diego")
}

invokeCallback(logName)
```

Observe que se a expressão `callback()` é comentada, a `logName` (que foi recebida no parâmetro `callback`) não é executada =)

```javascript
const invokeCallback = callback => {
  console.log(callback)
  // callback()
}

const logName = () => {
  console.log("Diego")
}

invokeCallback(logName)
```

Ficou mais claro?

De qualquer forma, callbacks levam um certo tempo pra clicar na mente. Mas eu recomendo fortemente que após executar os códigos acima, você execute [esse passo a passo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574#issuecomment-828888990) **até o final**. 

Se restar qualquer dúvida, pode responder aqui =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
