### ISSUE TITLE
Etapa 9, Correção dos exercícios da aula 02: Aula 01-01

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1832]
Boa noite Roger,
Poderia me ajudar a entender quando devemos utilizar um objeto para os argumentos das funções?

Por exemplo:
```js
const filterTodos = (todos, inputValue, returnMatchedTodos) => todos
    .filter(todo => {
        const matchedTodos = todo.textContent.toLowerCase().includes(inputValue)
        return returnMatchedTodos ? matchedTodos : !matchedTodos
    })
```
```js
const todosToHide = filterTodos(todos, inputValue, false)
const todosToShow = filterTodos(todos, inputValue, true)
```
Tentei aplicar na função ```const manipulateClass()```, mas não sei se está correto.

```js
const manipulateClass = ({ array, classAdd, classRemove }) => {
    array.forEach(todo => {
        todo.classList.add(classAdd)
        todo.classList.remove(classRemove)
    })
}
```
```js
const hideTodos = (todos, inputValue) => {
    const todosToHide = filterTodos(todos, inputValue, false)
    manipulateClass({ array: todosToHide, classAdd: 'hidden', classRemove: 'd-flex' })
}

const showTodos = (todos, inputValue) => {
    const todosToShow = filterTodos(todos, inputValue, true)
    manipulateClass({ array: todosToShow, classAdd: 'd-flex', classRemove: 'hidden' })
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @paulovieiradasilva!

Antes de responder, deixa eu revisar alguns conceitos...

Primeiro, é importante diferenciarmos o que é parâmetro e o que é argumento.

### Parâmetro

Parâmetro é uma variável especificada **na declaração de uma função**.

Na função abaixo, `param1`, `param2` são variáveis que podem ser usadas apenas no escopo da função `sum`:

```javascript
const sum = (param1, param2) => param1 + param2
```

### Argumento

Argumento é o valor inserido **na invocação da função**.

No código abaixo, a invocação de `sum` recebeu os valores 1 e 2 como argumentos:

```javascript
sum(1, 2)
```

Isso significa que o parâmetro `param1` (na declaração da função) recebeu 1 e `param2` recebeu 2:

```javascript
const sum = (param1, param2) => {
  console.log(param1, param2) // 1 2
}

sum(1, 2)
```

Outra coisa importante é diferenciar objeto e destructuring.

### Objeto

Um objeto pode ser inserido como **argumento** da invocação de uma função.

No código abaixo, a invocação da função `logObj` recebeu um objeto como argumento:

```javascript
logObj({ prop1: 1, prop2: 2 })
```

Sendo assim, podemos imaginar que a função `logObj` contém um parâmetro para receber esse objeto, como abaixo:

```javascript
const logObj = obj => {
  console.log(obj)
}
```

Isso significa que quando a função `logObj` é executada, o parâmetro `obj` recebe o objeto que foi inserido como argumento na invocação dela e exibe esse objeto no console:

```javascript
const logObj = obj => {
  console.log(obj) // { prop1: 1, prop2: 2 }
}

logObj({ prop1: 1, prop2: 2 })
```

### Destructuring

Revisando: destructuring assignment é uma expressão que possibilita que sejam atribuidos, pra variáveis, valores de propriedades de um objeto.

Se considerarmos que um parâmetro é uma variável, podemos usar destructuring no local onde um parâmetro seria declarado.

Ou seja, a função `logObj` pode receber uma expressão de destructuring no lugar do parâmetro `obj`:

```javascript
const logObj = ({ prop1, prop2 }) => {
  // ...
}
```

No destructuring acima, o valor da propriedade `prop1` do objeto foi atribuído a uma const `prop1` e o valor da propriedade `prop2` foi atribuído a uma const `prop2`. Isso significa que a const `prop1` armazena `1` e a const `prop2` armazena `2`:

```javascript
const logObj = ({ prop1, prop2 }) => {
  console.log(prop1, prop2) // 1 2
}

logObj({ prop1: 1, prop2: 2 })
```

Agora que revisamos esses conceitos, vamos à pergunta...

### Poderia me ajudar a entender quando devemos utilizar um objeto para os argumentos das funções?

Você pode usar um objeto como argumento de uma função quando quiser:

- Diminuir o número de argumentos/parâmetros que uma função recebe;
- Deixar mais claro o que os valores inseridos como argumentos significam.

#### Diminuindo o número de argumentos/parâmetros que uma função recebe

Funções com vários argumentos são mais complexas de testar e manter, pois exigem que casos diferentes sejam testados com cada argumento individualmente.

Como o JS permite que objetos sejam criados à qualquer momento, sem a necessidade de usar classes, um objeto pode substituir vários argumentos espalhados na invocação de uma função.

Lembre-se também que objetos não precisam obedecer uma ordem de parâmetros.

Na função abaixo, é obrigatório que ao invocá-la, os to-dos sejam inseridos como primeiro argumento, o valor do input como segundo e o boolean como terceiro. Se essa ordem não for obedecida, a função quebra.

```javascript
const filterTodos = (todos, inputValue, returnMatchedTodos) => {
  // ...
}
```

#### Deixando mais claro o que os valores inseridos como argumentos significam

Se vc observar a invocação abaixo, não fica tão explícito o que os valores inseridos como argumentos significam:

```javascript
manipulateClasses(todosToHide, 'hidden', 'd-flex')
```

Porém, se um objeto for inserido como argumento, fica mais fácil entender por que 'hidden' e 'd-flex' (por exemplo) estão sendo usadas ali:

```javascript
manipulateClasses({ todos: todosToHide, classToAdd: 'hidden', classToRemove: 'd-flex' })
```

Ou seja, fica fácil saber que `hidden` é a classe a ser adicionada e `d-flex` é a classe a ser removida. Mas claro, isso só funciona se os nomes das propriedades deixarem isso explícito.

> #### Tentei aplicar na função ```const manipulateClass()```, mas não sei se está correto.

**Sempre** use `console.log` para checar se suas variáveis estão armazenando o valor que você espera que elas armazenem. Você precisa se acostumar a fazer isso, ou será pego de surpresa.

No caso dessa função, basta inserir um console.log na primeira linha do bloco e verificar os valores que vc precisa.

---

Respondi a dúvida?

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
