### ISSUE TITLE
Etapa 5, nome do vídeo: dúvida pessoal

### ISSUE THREAD

**Issue by paulozy** [roger-melo-treinamentos/curso-de-js-roger-melo#1833]
Boa noite, Roger.

Estou com dúvida durante a execução de um projeto pessoal, queria saber como posso usar o resultado de um fetch fora da função em que ele está inserido, segue código abaixo:

```js
const url = "https://api.github.com/users/paulozy"


const getUserData = () => {
  fetch(url)
    .then(response => response.json())
    .then(dataUser => dataUser)
}

console.log(getUserData())
```

Poderia me ajudar por gentileza? sei que não é a etapa que eu estou no curso atualmente, mas é uma coisa que está me deixando muito encucado e lelé da silva.

Grato desde já

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @paulozy!

> #### Estou com dúvida durante a execução de um projeto pessoal, queria saber como posso usar o resultado de um fetch fora da função em que ele está inserido, segue código abaixo

No segundo `then`, vc pode referenciar uma função que recebe o objeto como parâmetro e, dentro dessa função, fazer algo com esse objeto:

```javascript
const url = 'https://api.github.com/users/paulozy'

const doSomething = res => {
  // aqui vc faz alguma coisa com o valor
  console.log(res)
}

const getUserData = () => {
  fetch(url)
    .then(response => response.json())
    .then(doSomething)
}

getUserData()
```

Ficou mais claro?

Operações assíncronas, requests, fetch e async/await são mostrados com detalhes na etapa 11. 

Se vc quiser, vc pode ir para essa etapa e depois voltar e continuar seguindo de forma sequencial à partir da etapa em que está. O ruim é que isso vai zoar a sua barra de progresso no treinamento xD

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
