### ISSUE TITLE
Aplicação: [TO-DO-LIST]

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#1834]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuniorAlvesbr/to-do-list.git

### Maiores dificuldades durante a implementação

Comecei a fazer essa aplicação antes de ver as aulas do to-do.
Fiz a aplicação toda com array baseado nas aulas que tivemos.

Tive muitas dificuldades em fazer as interações pelo array, principalmente em relembras métodos que tínhamos visto nas primeiras aulas do curso.

Porem consegui chegar a um resultado satisfatório.

Depois de olhar as aulas do to-do, fiz algumas refatorações baseado no seu código, porem não mudei a estrutura visto que construí a aplicação de uma forma bem diferente.

Ainda tenho muita dificuldade com refactory e nomes de variáveis que quase sempre escolho nomes que não explica muito oque a função e a variável está fazendo ou guardando.

Tive dificuldade com bootStrap e por isso construí o css do zero, até para treinar.

### Menores dificuldades durante a implementação

foram poucas

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> #### Depois de olhar as aulas do to-do, fiz algumas refatorações baseado no seu código, porem não mudei a estrutura visto que construí a aplicação de uma forma bem diferente.

Show, agora vc conhece 2 formas diferentes de fazer =)

> #### Ainda tenho muita dificuldade com refactory e nomes de variáveis que quase sempre escolho nomes que não explica muito oque a função e a variável está fazendo ou guardando.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

No geral, você entendeu bem a lógica para construir a aplicação.

Você limpou o input de adicionar to-dos, isso é bom para a usabilidade, pois faz com que o usuário não tenha que clicar ou tocar no input quando quiser adicionar um outro to-do.

## Usabilidade

A cor do placeholder "Buscar to-do" pode ter mais contraste com o fundo. Talvez a cor branca dê mais contraste nesse caso.

## Organização de código

### Nomes de variáveis e funções

No geral, os nomes que vc deu estão descritivos. Se quiser, vc pode deixá-los mais simples renomeando-os da forma abaixo. É apenas uma sugestão, a intenção dos nomes continua a mesma:

- `addTodoListInHTML` => `showTodos`
- `addItemToTodoList` => `addTodo`
- `searchItemInTodoList` => `searchTodo`
- `removeItemToTodoList` => `removeTodo`
- `todoList` => `todos`
- `htmlList` => `todosAsArray`
- `searchWord` => `searchTerm`
- `listWordMatch` => `matchedTodos`
- `eventTarget` => `clickedElement`

### Coding style

Como não há uso do `this` no código, para padronizar as declarações das funções, eu escolheria declará-las ou apenas com a palavra-chave `function` ou apenas como arrow functions.

Eu escolheria arrow functions pq acho elas mais simples e concisas.

### Indentação

Indentação é fundamental para dar mais legibilidade ao código. A indentação da template string da `showTodos` pode ser ajustada:

```javascript
// antes
const todosAsArray = array.map(item => (
        `<li class="list-group-item">
            <span>${item}</span>
            <i class="far fa-trash-alt delete" data-trash="delete"></i>
        </li>`
    )
)

// depois
const todosAsArray = array.map(item => (
    `<li class="list-group-item">
        <span>${item}</span>
        <i class="far fa-trash-alt delete" data-trash="delete"></i>
    </li>`
))
```

Como o callback do `map` não está retornando JSX ou um objeto, a função pode ficar mais simples se os parênteses forem removidos:

```javascript
const todosAsArray = array.map(item =>
    `<li class="list-group-item">
        <span>${item}</span>
        <i class="far fa-trash-alt delete" data-trash="delete"></i>
    </li>`)
```

### Linhas em branco

Como a última linha do bloco da `searchTodo` está em branco, ela pode ser removida. O mesmo vale para a primeira linha do if da `removeTodo`.

### Refatoração

Na etapa 15, vc verá uma técnica para controlar a mutação de objetos em escopo global. Ou seja, deixar a mutação do array `todos` em um escopo menor ao invés do escopo global =)

## Lógica

Na `removeTodo`, como vc quer obter **o texto** de um to-do, vc pode usar `textContent` ao invés de `innerHTML`:

```javascript
// antes
const todo = clickedElement.previousElementSibling.innerHTML

// depois
const todo = clickedElement.previousElementSibling.textContent
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JuniorAlvesbr** [comment]
Obrigado pelo feedback professor, todas as dicas e observações foram anotados. Vlw👍

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
