### ISSUE TITLE
Resumo da Aula While Loop - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by vitorsmessias** [roger-melo-treinamentos/curso-de-js-roger-melo#1837]
[WHILE LOOP - AULA 01-04 DA ETAPA 02.docx](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7188873/WHILE.LOOP.-.AULA.01-04.DA.ETAPA.02.docx)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @vitorsmessias, rumo à fluência! 🔥
