### ISSUE TITLE
Resumo da Aula Conhecendo a date-fns - Aula 02-03 da etapa 10

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1840]
A *date-fns* é uma *lib* para trabalharmos com datas em JavaScript, facilitando a manipulação das mesmas. Como a versão atual do *date-fns* é obtida apenas instalando através de um gerenciador de pacotes, vamos pegar uma versão mais antiga que nos permita utilizar um CDN. Então na nossa página HTML inserimos o link:

```html
<script src="http://cdn.date-fns.org/v1.9.0/date_fns.min.js"></script>
```

Após isso, em nosso arquivo app.js vamos fazer alguns testes. Primeiro vamos criar uma constante com a data atual, para em seguida fazermos algumas manipulações. Vamos ver abaixo alguns exemplos de como obter partes desta data, formatação dessa data e comparação entre duas datas: 

```jsx
const present = new Date();

console.log(dateFns.format('MMMM')); // September
console.log(dateFns.format('YY')); // 21
console.log(dateFns.format('Do')); // Saturday
console.log(dateFns.format('DD/MM/YYYY')); // 18/09/2021

const past = new Date('September 17 2021 21:30:00');

console.log(dateFns.distanceInWords(present, past, { addSuffix: true })); // about 10 hours ago
```

Falando do método `distanceInWords()`, ele recebe dois argumentos obrigatórios e um opcional. Os dois argumentos obrigatórios são as duas datas que queremos comparar e o terceiro será um objeto no qual podemos passar algumas configurações. No exemplo acima passamos a propriedade `addSuffix` com valor `true` para que saibamos por exemplo se o tempo retornado é um tempo passado ou futuro.

Um outro ponto a ser falado é que os resultados são exibidos em inglês. Podemos utilizar as saídas em outros idiomas, mas para isso precisamos fazer um *require* de um outro arquivo do *date-fns*, porém  ainda não o faremos neste momento.

Observação: Os resultados acima são de acordo com o dia em que este post foi escrito: 18 de setembro de 2021, às 7h30.

---

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🔥
