### ISSUE TITLE
Resumo da Aula Testando padrões REGEX - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1841]
## Testando padrões REGEX

→ Uma das maneiras de testar se o conteúdo digitado no form dá match com a regex é o método ".test( )" usado diretamente na regex determinada para aquele input que recebe como argumento a string digitada no input. Este método retorna um boolean.

```jsx
const username = 'rogerm'
const pattern = /^[a-z]{6,}$/ -> esta regex determina que só será aceito o preenchimento 
do campo com uma única palavra que não tenha espaço nem caracteres antes e depois, que 
tenha apenas letras minúscula e que tenha pelo menos 6 caracteres.

const isMatch = pattern.test(username) -> retorna true

if (isMatch) {
	console.log("o teste da regex passou =)")
} else {
	console.log("o teste da regex não passou =(")
}
```

→ A outra maneiras de testar se o conteúdo digitado no form dá match com a regex é o método ".search( )" usado diretamente na string digitada naquele input que recebe como argumento a regex determinada para aquele input. Este método retorna é um número inteiro que corresponde ao index no qual o match aconteceu, se o match não acontecer retorna "-1" .

```jsx
const username = 'rogerm'
const pattern = /^[a-z]{6,}$/ -> esta regex determina que só será aceito o preenchimento 
do campo com uma única palavra que não tenha espaço nem caracteres antes e depois, que 
tenha apenas letras minúscula e que tenha pelo menos 6 caracteres.

const isMatch = username.test(pattern) -> 0

if (isMatch !== -1) {
	console.log("o teste da regex passou =)")
} else {
	console.log("o teste da regex não passou =(")
}
```

→ MAS PARA TESTE EM FORMULARIOS O MÉTODO MAIS USADO É O ".TEST" ←

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @JuFML, rumo à fluência! 🔥
