### ISSUE TITLE
Resumo da Aula 02-02 - Arrow functions da etapa 03

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1848]
1. Arrow functions, é uma forma mais curta de escrever funções.
```js
const test1 = (number) => {
   return number * 2
}
```

2. Quando tiver apenas um parâmetro pode retirar os parênteses:
```js
const test2 = number => {
   return number * 2
}
// Obs. Quando não tiver parâmetro, têm que deixar os parênteses vazio '()'.
```
3. Característica importante da arrow function, e que se o bloco de código dela estiver contendo apenas uma linha retornando um valor, podemos retirar o return e eliminar as chaves, assim realizando um retorno implícito
Esse valor deve ser um array, boolean, string um número. Não deve ser switch nem if, porque eles não retornam valores e sim bloco de código.

```js
const test3 = number =>  number * 2

```

**Comment by Roger-Melo** [comment]
Excelente @carlosebs, rumo à fluência! 🔥
