### ISSUE TITLE
geral

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1852]
Roger, não sei se vou saber explicar, no vídeo que você incluiu sobre escopo, que estava fora do curso, voce se referiu const como variável e eu estranhei.
Vamos supor que eu estou explicando para alguém e quero me referir a "const", "let" ou "var"  mas eu estou achando estranho chamar uma "const" de variável, entao eu nas minhas anotações escrevi da seguinte maneira:

"Quando se trata de escopo de função, não importa se o identificador é declarado como "let", "const" ou "var", ele não existirá fora da função onde foi declarada".

Eu usei a palavra "identificador", não sei se estou certo ou se fiz confusão nisso.

se haver algum erro de portugês me perdoe, meu corretor de ortografia está em inglês e estou mal acostumado em corrigir erros.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986!

> #### voce se referiu const como variável e eu estranhei

Perdão. Às vezes acontece rs.

Se é variável (`var` ou `let`), o valor pode variar. 

Se é `const`, não. Apenas lembre-se que embora uma const não possa mudar seu valor, se o valor é um objeto, ele pode ter propriedades alteradas (ou itens, no caso de arrays). Objetos são mutáveis por padrão.

> #### "Quando se trata de escopo de função, não importa se o identificador é declarado como "let", "const" ou "var", ele não existirá fora da função onde foi declarada".

Exatamente. Variáveis/constantes declaradas dentro de uma função são acessíveis apenas no escopo da função, não importa se é uma `var`, `let` ou `const`.

```javascript
const myFunc = () => {
  var myVar = 'olá'
  let myLet = 'oi'
  const myConst = 'hi'
}

console.log(myVar) // myVar is not defined
console.log(myLet) // myLet is not defined
console.log(myConst) // myConst is not defined
```

No código acima, qualquer tentativa de acesso às variáveis/const lançam um erro que avisa que elas não foram definidas (no escopo em questão).

> #### Eu usei a palavra "identificador", não sei se estou certo ou se fiz confusão nisso.

[Segundo o MDN](https://developer.mozilla.org/en-US/docs/Glossary/Identifier), um identificador é uma sequência de caracteres no código que identifica uma variável, função ou propriedade. Então pode usar o termo "identificador" à vontade =)

Ficou mais claro?

**Comment by Rodrigo986** [comment]
Muito obrigado!
