### ISSUE TITLE
Como trocar navegador padão

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1853]
Roger, sem querer eu defini o mozila firefox como navegador padrão.
Como eu definio o live server para abrir o google chrome como padrão?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Se vc quer apenas que o live-server reconheça o chrome como browser padrão, vc pode pressionar `ctrl + shift + P`, inserir "Preferences: Open Settings (JSON)" e inserir essa key:

```JSON
"liveServer.settings.CustomBrowser": "chrome",
```

[Aqui](https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md#settings) tem mais informações sobre configurações que vc pode fazer na live-server.

Agora, se vc quer fazer com que o sistema operacional reconheça o chrome como browser default, se estiver no Windows, pressione a tecla `windows`, insira `browser` (ou `navegador` se estiver em pt-BR) e a opção pra vc clicar e ir pra janela pra mudar o browser vai ser exibida.

Testa e me avisa se seu certo =)

@Rodrigo986

**Comment by Rodrigo986** [comment]
Perfeito cara, vc é foda, esclarece as dúvidas de forma detalhada e de quebra me informa de coisas além da dúvida.
