### ISSUE TITLE
Etapa 3 - exercício 09

### ISSUE THREAD

**Issue by carlosebs** [roger-melo-treinamentos/curso-de-js-roger-melo#1860]
@Roger-Melo ,

Boa noite, Roger caso as respostas dos exercícios cheguem na resposta final, mais a lógica esteja diferente da sua, podemos acertar com a sua lógica e seguir em frente?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosebs!

Essas diferenças podem acontecer sim. Nesses casos, eu recomendo que vc se certifique que entendeu a minha forma de resolver, pq provavelmente, por trás daquela resolução há um princípio que será intensificado nos próximos desafios =)

**Comment by carlosebs** [comment]
sim, Tmj rumo a fluência.

Em dom, 19 de set de 2021 20:21, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show! No que precisar, pode abrir uma issue e perguntar =)

Rumo à fluência 🔥
