### ISSUE TITLE
Retomando os estudos

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#1863]
Olá a todos! Estou no curso desde março e estudei de forma frequente até o mês de junho. Desde esse mês, por conta do início das aulas, não venho conseguindo estudar direito. Forcei até a chegar na etapa 13, na metade de julho e estagnei. Agora, quero voltar a estudar, mas eu não sei se vou conseguir prosseguir a partir do ponto que parei e aquele pessimismo "eu não vou conseguir" me dificulta também. O que recomendam que eu faça?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

Somos mais fortes do que imaginamos, só não chega na fluência quem desiste =)

Eu recomendo que vc faça [esse passo a passo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/78#user-content-faca-uma-revisao), começando pela primeira bateria de exercícios.

E lembre-se, qualquer dúvida que surgir, pode abrir uma issue que te ajudo =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
