### ISSUE TITLE
Etapa 05, nome do vídeo: Correção dos exercícios da aula passada - Aula 02-01

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1864]
![image](https://user-images.githubusercontent.com/45271247/134049367-d876d34c-d37c-400d-8013-521280e0351b.png)

Roger, o que significa quando uma variável ou de uma função fica riscado desse jeito?
Não é a primeira vez que isso acontece.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986!

[Nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/92#issuecomment-735000418) vc verá uma resposta a essa dúvida e, se ainda restar qualquer dúvida, pode responder aqui nessa issue que te ajudo =)

**Comment by Rodrigo986** [comment]
Opa, compreendi. Obrigado mais uma vez. Vou procurar se existem issues criadas com a mesma dúvida minha a partir de agora. Vlw demais.
