### ISSUE TITLE
Etapa 05, nome do vídeo: Adicionando e modificando conteúdo em uma página - Aula 02-02

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1866]
Roger, gostaria de saber pq quando eu fiz o "innerHTML" ele criou um <h2> vazio?
```html
<div class="content">
        <p>Conteúdo aqui</p>
    </div>


```

```js

const div = document.querySelector('.content')

div.innerHTML = `<h2>Novo h2<h2>`

}
```

![image](https://user-images.githubusercontent.com/45271247/134227115-f110e95c-4d2e-42b2-acaa-03dfe6ae63b6.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986!

O segundo `h2` foi criado por que a tag de fechamento na string `<h2>Novo h2<h2>` está sem a barra (/).

Nesse caso, o que aconteceu por baixo dos panos foi que o browser fechou as duas tags `<h2>` automaticamente xD

Para que o código funcione como vc espera, basta inserir a barra no fechamento da tag. Vai ficar assim: `<h2>Novo h2</h2>`.

Pegou a ideia?

**Comment by Rodrigo986** [comment]
Rapaz... é mesmo ein?
Esse é o tipo de erro que me joga lá pra baixo.

Obrigado pelo esclarecimento.
