### ISSUE TITLE
Etapa 15, Correção dos exercícios da aula 03 da etapa 14 - Aula 01-01

### ISSUE THREAD

**Issue by tuxpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#187]
Olá Roger, tudo bem?

Entendi que o prototype podem ser **getters** e **setters** e para adicionar um método ao prototype da função construtora,  eu tenho que atribuir o método para o prototype fora da função construtora. Eu não estou entendendo por que eu estou atribuindo um método ao prototype de um função e quando quando faço a comparação utilizando o '.isPrototype(obj)' está retornando **false**?

Veja, esse é o exercício 38 número 1:

```js

/*
  01

  - Crie um objeto com um método getColor. Este método deve retornar o valor da
    propriedade 'color' dos objetos descritos abaixo;
  - Crie 2 novos objetos que representem dois carros. Na criação dos objetos, 
    faça o objeto com o método getColor ser prototype desses dois carros;
  - Após criar os carros, crie neles as propriedades 'color'. Atribua valores 
    diferentes para a propriedade color de cada carro;
  - Teste o método getColor do prototype dos carros.
*/

// Object with getColor method
const protoPropertyColor = {
  getColor() {
    return this.color
  }
}

// construction function
function Car(color) {
  this.color = color
}

// defines protoPropertyColor as Car prototype
Car.prototype = protoPropertyColor

const ford = new Car('blue') // create object
const fiat = new Car('Grey') // create object


console.log(ford, fiat) // log objects
console.log(
  'is prototype of car ?',
  Car.isPrototypeOf(ford) || Car.isPrototypeOf(fiat) //false
)
console.log('Ford color: ', ford.getColor(), 'Fiat color:', fiat.getColor())

```
![image_chrome_console](https://user-images.githubusercontent.com/9454256/107883517-42533600-6ece-11eb-81b0-fb84f7185062.png)

**Muito obrigado pela atenção.**

**Comment by Roger-Melo** [comment]
Olá, Pedro.

```javascript
Car.prototype = protoPropertyColor
```

O código acima está setando o objeto `protoPropertyColor` como prototype **dos objetos que a função construtora Car cria**. 

Então o que faz sentido é testar se `protoPropertyColor` é prototype dos objetos ford e fiat:

```javascript
console.log(
  protoPropertyColor.isPrototypeOf(ford),
  protoPropertyColor.isPrototypeOf(fiat)
)
// true true
```

Ficou claro?

@tuxpedro 

PS: Observe também que na correção, o exercício foi resolvido usando `Object.create()` ao invés de funções construtoras. E isso foi intencional, pois é uma feature que eu mostrei na aula anterior. Ela é uma maneira alternativa de usar herança prototypal sem usar funções construtoras, então é importante que você a entenda.

**Comment by tuxpedro** [comment]
Olá Roger! Tudo bem?

Ficou super claro, muito obrigado.

**Comment by tuxpedro** [comment]
Olá Roger, 

Hum, então é correto afirma que ```protoPropertyColor```  é protótipo  dos objetos ford e fiat, compreendido. 

Muito obrigado pela atenção.
