### ISSUE TITLE
Resumo da Aula 01 - 02 da etapa 08

### ISSUE THREAD

**Issue by josemalexandre** [roger-melo-treinamentos/curso-de-js-roger-melo#1871]
**Método Map**

Esse método itera sobre todos os itens de um array, modificando eles por meio de uma função de callback passada por argumento. O método map retorna sempre um novo array com os itens modificados, preservando o array anterior.

```js
   const numbers = [1, 2, 3, 4, 5]

   const doubleNumbers = numbers.map( num => num * 2)
```

O map pode receber três argumentos, o item iterado, o índice do item e o próprio array. No map apenas o item iterado é obrigatório passar por argumento.

**Comment by Roger-Melo** [comment]
Ótimo, @josemalexandre. Rumo à fluência 🔥
