### ISSUE TITLE
Resumo da Aula Código assíncrono em JavaScript - Aula 01-02 da etapa 11

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#1874]
Por padrão o JavaScript é uma linguagem síncrona, ou seja, executa uma instrução por vez de cima para baixo. Se em algum momento da nossa aplicação precisarmos fazer uma consulta a uma API por exemplo, essa consulta leva um determinado tempo para dar uma resposta. Então se eu tenho três instruções a serem executadas e a segunda é uma consulta a uma API, a terceira instrução só será executada após a segunda ser finalizada. Essa é a fragilidade do código síncrono. Ou seja, a segunda instrução bloqueia a próxima instrução até que ela seja finalizada, para aí sim a terceira instrução ser executada.

Já o código assíncrono faz com que as instruções não sejam bloqueadas, executando-as em ordem, mas sem bloquear a próxima instrução. Geralmente uma função de *callback* é passada para o código que inicia uma operação assíncrona, sendo executada assim que os dados da requisição são obtidos.

Então vamos imaginar que temos as seguintes instruções: A primeira instrução retorna a data e hora atuais, a segunda faz uma requisição a uma API para trazer os dados de um usuário, e a terceira monta um formulário na tela. Num código síncrono, o formulário só seria mostrado após a requisição a API retornar algo, ou seja, a aplicação "travaria" esperando a reposta da requisição. Num código assíncrono a aplicação montaria o formulário sem esperar os dados do usuário, e assim que estes dados estivessem disponíveis, a função de *callback* seria executada e mostraria esses dados na tela, por exemplo.

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência! 🙌🏻
