### ISSUE TITLE
Aplicação: [Todo-List]

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#1875]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edcabralc/todo-app

### Maiores dificuldades durante a implementação

Tive dificuldades em refazer o refactoring da aplicação.

### Menores dificuldades durante a implementação

Consegui entender a lógica e manipulação do DOM

**Comment by Roger-Melo** [comment]
Olá @edcabralc.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @edcabralc!

Parabéns pelo esforço em construir a segunda aplicação do treinamento. Sua evolução em relação à análise da aplicação passada é perceptível =)

Além de demonstrar ter entendido bem a lógica até aqui, você escolheu nomes descritivos para suas variáveis e funções.

> #### Tive dificuldades em refazer o refactoring da aplicação.

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

---

O único ponto de atenção que percebi no momento é a formatação da template string com a marcação HTML. Acredito que se ela for indentada da forma abaixo, o código ganha mais legibidade:

```javascript
// antes
todosContainer.innerHTML += `<li class='visible'>
                <span>${inputValue}</span>
                <i class="far fa-trash-alt delete"></i>
                </li>`;

// depois
todosContainer.innerHTML += `<li class='visible'>
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>
    </li>`;

// ou assim
todosContainer.innerHTML += `
    <li class='visible'>
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>
    </li>`;
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só dar o toque =)
