### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1878]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuFML/cat-quiz

### Maiores dificuldades durante a implementação

- A capacidade de refatorar o código;
- Me adaptar ao Bootstrap. 

=> Mesmo sabendo que o uso do Bootstrap não era obrigatório me desafiei a usálo visto que não tenho muito intimidade com esta lib uma vez que prefiro CSS puro. <=

### Menores dificuldades durante a implementação

- Desenvolver a lógica da aplicação.

**Comment by Roger-Melo** [comment]
Olá @JuFML.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuFML!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### A capacidade de refatorar o código

O mais importante no primeiro momento vc já fez, que é fazer funcionar. Suas habilidades de refatoração evoluem com a prática e o tempo, ok?

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Outra demonstração de que vc pegou bem a lógica até aqui foi evitar `else if` e `else` para exibir a pontuação na tela.

Os olhos de gato em telas com largura menor foi uma boa sacada.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa.

## Organização de código

As lets e consts relacionadas às respostas podem ficar separadas de consts que armazenam elementos do DOM:

```javascript
// antes
const correctAnswers = ['B', 'A', 'A', 'B'];
const form = document.querySelector('.quiz-form');
let userAnswersScore = 0;
const button = document.querySelector('.btn');
const scoreParagraph = document.createElement('p');

// depois
const form = document.querySelector('.quiz-form');
const button = document.querySelector('.btn');
const scoreParagraph = document.createElement('p');

const correctAnswers = ['B', 'A', 'A', 'B'];
let userAnswersScore = 0;
```

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos.

Sabendo disso, você pode deixar uma linha em branco ao final de cada `if` da `printScoreMessage`:

```javascript
const printScoreMessage = () => {
  if (userAnswersScore >= 75) {
    // ...
  };

  if (userAnswersScore >= 50) {
    // ...
  };

  scoreParagraph.setAttribute('class', 'text-danger');
  // ...
};
```

### Refatoração

Se quiser, é possível fazer um pequeno refactoring na `printScoreMessage`, olha só...

Como a declaração dela não-necessariamente precisa estar dentro do callback de envio do `form`, é possível extraí-la para fora do callback:

```javascript
const printScoreMessage = () => {
  // ...
};

form.addEventListener('submit', event => {
  // ...

  printScoreMessage();
  userAnswersScore = 0;
});
```

Feito isso, é possível fazer uma pequena abstração para eliminar as repetições. 

Observe que independente do valor da `userAnswersScore`, essas 3 linhas vão se repetir:

```javascript
scoreParagraph.textContent = '...';
scoreParagraph.setAttribute('class', '...');
button.insertAdjacentElement('beforebegin', scoreParagraph);
```

No código acima, só os placeholders `'...'` precisam mudar. Ou seja, precisam ser dinâmicos.

Sendo assim, é possível criar uma função que executa esse código e recebe os valores dinâmicos por argumento/parâmetro:

```javascript
const print = ({ text, color }) => {
  scoreParagraph.textContent = text;
  scoreParagraph.setAttribute('class', color);
  button.insertAdjacentElement('beforebegin', scoreParagraph);
}

const printScoreMessage = () => {
  if (userAnswersScore >= 75) {
    print({ text: `PARABÉNS!! Pontuação: ${userAnswersScore}!`, color: 'text-success' });
    return;
  };

  if (userAnswersScore >= 50) {
    print({ text: `MUITO BOM!! Pontuação: ${userAnswersScore}!`, color: 'text-primary' });
    return;
  };

  print({ text: `TREINE MAIS!! Pontuação: ${userAnswersScore}!`, color: 'text-danger' });
};
```

Seria possível também inserir apenas as strings como argumentos da `print`... 

```javascript
print(`TREINE MAIS!! Pontuação: ${userAnswersScore}!`, 'text-danger');
```

Mas eu acredito que quando essas strings são valores de propriedades, os nomes das propriedades deixam mais claro qual é o significado das strings, e isso impacta na legibilidade do código.

---

Uma outra forma de refatorar é não criar uma função `print`, mas criar uma função que retorna objetos baseados na pontuação:

```javascript
const getScoreMessageInfo = () => ({
  50: { text: `MUITO BOM!! Pontuação: ${userAnswersScore}!`, color: 'text-primary' },
  75: { text: `PARABÉNS!! Pontuação: ${userAnswersScore}!`, color: 'text-success' },
  100: { text: `PARABÉNS!! Pontuação: ${userAnswersScore}!`, color: 'text-success' }
})[userAnswersScore] || { text: `TREINE MAIS!! Pontuação: ${userAnswersScore}!`, color: 'text-danger' }

const printScoreMessage = () => {
  const { text, color } = getScoreMessageInfo();
  scoreParagraph.textContent = text;
  scoreParagraph.setAttribute('class', color);
  button.insertAdjacentElement('beforebegin', scoreParagraph);
};
```

A vantagem dessa abordagem é que ela elimina os `if`s.

Se vc ainda não chegou na aula em que mostro essa técnica, em breve vc encontrará. E claro, se tiver alguma dúvida, fique a vontade para perguntar =)

A desvantagem é que essa abordagem pode deixar o código um pouquinho mais complexo. Observe também que os valores das propriedades 75 e 100 são os mesmos.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JuFML** [comment]
Roger, muito obrigada pelas observações. Quando eu crescer quero ser bichão igual a você!!
