### ISSUE TITLE
Etapa 05, nome do vídeo: Adicionando e modificando conteúdo em uma página - Aula 02-02

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1879]
A minha "querySelect" está saindo um resultado diferente mostrado na aula e não consigo identificar o erro.

![image](https://user-images.githubusercontent.com/45271247/134782648-ab7496a9-16f8-41d9-897f-bb84348cc26a.png)

```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Adicionando e modificando conteúdo em uma página</title>
</head>

<body>
    <h1>Adicionando e modificando conteúdo em uma página</h1>

    <div>
        <p>Hello World</p>
        <p>Oi</p>
        <p class="error">Essa é uma mensagem de erro</p>
    </div>

    <div class="content">
        <p>Conteúdo aqui</p>
    </div>
    
    <script src="./app.js"></script>
</body>

</html>

}
```

```js
const div = document.querySelector('.content')
console.log(div)

```

@Roger-Melo

**Comment by Rodrigo986** [comment]
Eu apertei f5 e apareceu as tags normalmente.  Eu fiquei umas meia hora procurando o erro e nao achei (pois não tinha).
Mas mesmo assim eu gostaria de saber pq apareceu desse jeito que está no print (a div seguida de um ponto + a o nome da classe). Se clicasse na "setinha" abria uma lista enorme nao li o suficiente para saber se era de metodos.

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986.

> ### A minha "querySelect" está saindo um resultado diferente mostrado na aula e não consigo identificar o erro.

Não há erro, talvez uma nova atualização do chrome modificou a forma como nós do DOM são visualizados no console. 

Para visualizar o nó como árvore HTML, no chrome vc pode clicar com o botão direito do mouse sobre o nó e selecionar "inspect": 

![image](https://user-images.githubusercontent.com/29297788/134810753-3271cbe9-0051-437f-9e92-be767d474780.png)

Ou clique com o botão direito sobre `>div.content` e selecione a opção "Reveal in Elements panel":

![image](https://user-images.githubusercontent.com/29297788/134810523-b9e8d77a-94df-4577-8120-eb313f4860cb.png)

---

> Se clicasse na "setinha" abria uma lista enorme nao li o suficiente para saber se era de metodos

Sim, são propriedades do nó do DOM em questão. 

Todo nó que está no DOM é um objeto que contém propriedades e métodos =)

**Comment by Rodrigo986** [comment]
Sim, Obrigado, sua resposta me esclareceu.
