### ISSUE TITLE
Etapa 03, Funções e Métodos - Aula 02-04

### ISSUE THREAD

**Issue by betomouse** [roger-melo-treinamentos/curso-de-js-roger-melo#188]
Sobre Callbacks, eu buguei! Mas depois de fazer o passo a passo como nos comentários, parece que tudo ficou claro.
Minhas afirmações abaixo estão corretas mesmo não sendo regras ? Começo a enxergar tudo de maneira tão simples que estou com medo de estar mais perdido que no início.

1º - Posso afirmar que se um parâmetro referencia uma função que retorna um valor, espera-se que o argumento seja uma função de callback que utilize/manipule esse valor?

```js

const myFunc = callback => { 
   callback('Olá Mundo!') 
}
myFunc((value) => {
   console.log(value)
})

```
2º - Caso o parâmetro referencie uma função que manipule um valor, espera-se que o argumento seja uma função de callback que retorne um valor ?

```js

const myFuncB = callback => { 
  console.log(callback())
myFuncB(() => 'Olá Mundo!')

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Alberto.

Callbacks tem esse impacto inicial mesmo =)

Primeiramente, é importante definir duas coisas:

1) Um callback é uma função inserida como argumento da invocação de outra função. Apenas isso.
2) O que são parâmetros e o que são argumentos (abaixo). É legal você se acostumar com essa terminologia, por que é a terminologia que a documentação usa.

Chame de parâmetro apenas o nome especificado na declaração da função. No código abaixo, `param` é um parâmetro:

```javascript
const myFunc = param => {
  // ...
}
```

Já os argumentos são apenas os valores inseridos na invocação de uma função ou método. No código abaixo, a string `'argument'` é um argumento:

```javascript
myFunc('argument')
```

Com isso ajustado, vamos às perguntas =)

> 1º - Posso afirmar que se um parâmetro referencia uma função que retorna um valor, espera-se que o argumento seja uma função de callback que utilize/manipule esse valor?

Se um parâmetro armazena a referência de uma função e essa função tem um parâmetro na declaração dela, quando a referência da função for invocada (através do parâmetro que armazena ela), essa invocação precisa receber um valor como argumento.

Isso significa que no código abaixo, quando `myFunc` é invocada, `callback` armazena `value => { console.log(value) }`:

```js
const myFunc = callback => { 
  callback('Olá Mundo!') 
}

// invocação da myFunc
myFunc(value => {
  console.log(value)
})
```

Como `value => { console.log(value) }` é uma função que tem um parâmetro `value`, quando essa função for invocada dentro da `myFunc` (através do parâmetro `callback`), ela precisa receber um argumento na invocação dela:

```js
const myFunc = callback => {
  // callback é invocada recebendo o argumento 'Olá Mundo!'
  callback('Olá Mundo!') 
}

myFunc(value => {
  console.log(value)
})
```

Com `callback` invocada dentro da `myFunc`, o parâmetro `value` na função `value => { console.log(value) }` recebeu `'Olá Mundo!'` e `console.log(value)` foi executado.

> 2º - Caso o parâmetro referencie uma função que manipule um valor, espera-se que o argumento seja uma função de callback que retorne um valor?

No código abaixo, quando `myFuncB` é invocada, o parâmetro callback recebe `() => 'Olá Mundo!'`:

```js
const myFuncB = callback => {
  console.log(callback())
}

myFuncB(() => 'Olá Mundo!')
// o parâmetro "callback" agora armazenou () => 'Olá Mundo!'
```

Quando `() => 'Olá Mundo!'` é invocada (através da expressão `callback()`), o retorno dessa invocação resulta na string `'Olá Mundo!'`. Isso significa que no código abaixo, quando `() => 'Olá Mundo!'` é invocada através do parâmetro `callback`, o resultado da expressão `callback()` é `'Olá Mundo!'`:

```js
const myFuncB = callback => {
  callback() // 'Olá Mundo!'
}

myFuncB(() => 'Olá Mundo!')
```

Para que o resultado da expressão `callback()` seja exibido no console, podemos invocar um `console.log()` que recebe `callback()`. 

```js
const myFuncB = callback => {
  console.log(callback()) // 'Olá Mundo!' é exibida no console
}

myFuncB(() => 'Olá Mundo!')
```

Ou, se você preferir, pode declarar uma `const` que armazena o resultado de `callback()` e apenas referenciar essa `const` como argumento da invocação do `console.log()`:

```js
const myFuncB = callback => {
  const helloWorld = callback()
  console.log(helloWorld) // 'Olá Mundo!'
}

myFuncB(() => 'Olá Mundo!')
```

Está ficando mais claro?

@betomouse

**Comment by betomouse** [comment]
Lógico!!! Muito claro! Obrigado mil vezes pela atenção Roger!

**Comment by Roger-Melo** [comment]
Excelente. Já que ficou mais claro vou fechar a issue, mas quando surgirem mais dúvidas é só abrir uma nova =)
