### ISSUE TITLE
Resumo da Aula setInterval( ) e animação da pontuação - Aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1881]
# setInterval( ) e animação da pontuação

## setInterval( )

→ É um método similar so setTimeout( ) mas nele a função é executada repetidamente e repitição da execução deta função vai acontecer no intervalo de tempo que a gente especificar. Ele recebe dois argumentos, o primeiro é uma função callback que a gente quer invocar repetidamente e o segundo é o tempo em milisegundo indicando de quanto em quanto tempo esta função que foi passada no primeiro argumento deve ser executada. 

```jsx
setInterval(() =>{
	console.log("1 segundo se passou")
}, 1000 ) -> depois que a página for carregada esta função será executada de um em um segundo
```

A diferença do setInterval para o setTimeout é que o setTimeout executa a função uma única vez e o setInterval executa a função repetidamente no intervalo de tempo que a gente especificou.

```jsx
let counter = 0

const timer = setInterval(() =>{
	console.log("1 segundo se passou")
counter++

if(counter === 5 {
	clearInterval(timer)
}
}, 1000 ) -> depois que a página for carregada esta função será executada de um em um segundo
```

No código acima criamos uma variável "counter" que vai auxiliar na ação de parar o setInterval. Esta variável começa com o valor zero e é incrementada a cada vez que a setInterval é executada. Quando o counter for igual a 5 a função "clearInterval" é executada e ela recebe como argumento o "Id" da setInterval que a gente quer parar (o Id neste caso fica armazenado na const "timer" cuja função foi atribuída).

## Animação da Pontução

```jsx
let counter = 0

const timer = setInterval(() =>{
	if(counter === score {
		clearInterval(timer)
	}
	finalResult.querySelector('span).textContent = `${counter}%`
	counter++
}, 10 ) 
```

No código acima criamos uma variável "counter" que vai auxiliar na ação de parar o setInterval e também que vai ser o contador dinâmico da pontuação. Esta variável começa com o valor zero e é incrementada a cada vez que a setInterval é executada. Quando o counter for igual a pontuação que a pessoa fez a função "clearInterval" é executada e ela recebe como argumento o "Id" da setInterval que a gente quer parar (o Id neste caso fica armazenado na const "timer" cuja função foi atribuída). Enquanto o counter não for igual à pontuação que a pessoa fez o resultado final (que é o  span que mostra na tela a pontuação que a pessoa fez) vai sendo incrementado em 1 a cada 10 milisegundos, ou seja, a pontuação vai aumentando a cada dez milisegundo até chegar na pontuação que a pessoa atingiu respondendo as perguntas do quiz.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @JuFML, rumo à fluência! 🙌🏻
