### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1882]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/claudiogmoreira/cjrm.git

### Maiores dificuldades durante a implementação

A primeira dificuldade foi entender a estrutura html e css. Embora tenho tenho noções sobre essas duas tecnologias mas como não trabalho na área diretamente, precisei ler várias vezes a estrutura html para entendê-la. 
Foi meu primeiro contato com o bootstrap, gostei muito da praticidade para não perder tempo com estilos nesses momento. Assisti a aula três vezes para entender a lógica do quiz, para mim que não sou programador, tenho dificuldade de entender a lógica por trás da aplicação. Também está sendo meu primeiro contato com github, espero ter aberto o repositório corretamente! Enfim, estou me dedicando a ter uma visão de como as tecnologias se completam, sobre como trabalham juntas na construção de uma aplicação.

### Menores dificuldades durante a implementação

Foi entender a lógica do quiz, assistindo a aula algumas vezes não pareceu ser complicado. Para mim o desafio é chegar na lógica.

**Comment by Roger-Melo** [comment]
Olá, @claudiogmoreira.

Passando rapidinho pra avisar que visualizei a issue e, se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> #### Assisti a aula três vezes para entender a lógica do quiz, para mim que não sou programador, tenho dificuldade de entender a lógica por trás da aplicação.

Pelo que vi, vc entendeu a lógica sim =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

Agora, antes de continuar a análise... eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. 

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações, ok?

---

## Usabilidade

### Exibição dos pontos

Ao exibir a pontuação, é interessante que o usuário tenha mais clareza do que significa aquele número na tela. Isso pode ser resolvido com uma mensagem "Você acertou 75% do quiz", por exemplo.

## Organização de código

### Consts no topo do código

Uma forma de organizar consts é agrupá-las pelo tipo de valor que elas armazenam. 

No topo do código, é possível fazer com que as consts que armazenam elementos do DOM fiquem agrupadas e a const relacionada às respostas corretas fique separada:

```javascript
const form = document.querySelector('.quiz-form')
const showScore = document.querySelector('.showScore')

const correctAnswers = ['B', 'B', 'B', 'B']
```

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Como `showScore` (verbo) não é uma função, ela pode ser nomeada como `scoreContainer` ou `scoreEl` (el é uma abreviação de element).

Observe também que `scores` não precisa estar no plural, afinal há apenas uma única pontuação no quiz, e `userAnswer` pode ser nomeada como `userAnswers`, pois ela armazena várias respostas.

### console.log esquecidos

O `console.log` é útil apenas no momento em que você está desenvolvendo. Sei que vc deve ter usado para visualizar algum valor e esquecido, mas sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também).

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Apenas uma linha é suficiente para separar conceitos.

Observe também que é uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código, então eu evitaria deixar em branco as linhas 46, 48, 50, 52, 53 e 60.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by claudiogmoreira** [comment]
Boa tarde Roger, sim claro que fizeram muito sentido!
esses dias vi num grupo de JS que acompanho no facebook,
que no repositório de uma aplicação, é fundamental a gente melhorar
constantemente a aplicação,
farei os ajustes no quiz interativo conforme suas observações.
Graças ao curso CJRM que estou tendo meu primeiro contato com o github.
Quero em breve fazer um treinamento específico dele.

Uma dúvida: Para cada aplicação devemos criar um repositório um apenas um
repositório para todas as aplicações?
pois criei o repositório com o nome do curso CJRM e não com o nome da
aplicação. Se o correto é com o nome
da aplicação, eu consigo renomear o repositório para o nome da aplicação?

Obrigado,

Claudio.


Em ter., 28 de set. de 2021 às 10:08, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira!

> #### esses dias vi num grupo de JS que acompanho no facebook, que no repositório de uma aplicação, é fundamental a gente melhorar constantemente a aplicação...

Isso mesmo. Você chegará em um momento do treinamento onde eu bato nessa tecla também, hahah.

> #### Graças ao curso CJRM que estou tendo meu primeiro contato com o github. Quero em breve fazer um treinamento específico dele.

Legal! Se quiser, posso te indicar um material de uma pessoa em quem confio =)

> #### Uma dúvida: Para cada aplicação devemos criar um repositório um apenas um repositório para todas as aplicações?

O ideal seria que cada aplicação tenha seu próprio repositório. Assim o gerenciamento delas fica mais organizado =)

> #### Se o correto é com o nome da aplicação, eu consigo renomear o repositório para o nome da aplicação?

Vc consegue renomear um repositório sim, basta acessar o respositório no GitHub e ir na aba "settings" =)

**Comment by claudiogmoreira** [comment]
boa tarde Roger,
sobre o treinamento github quero sim, pode me passar o material, obrigado!
e também, se puder me passar indicações de canais ou qq material sobre html
e css, agradeço também.

Claudio.

Em sex., 1 de out. de 2021 às 22:35, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @claudiogmoreira, vou deixar os links dos materiais aqui abaixo.

- [Treinamento de GitHub](https://www.udemy.com/course/git-e-github-ninja/?couponCode=SETEMBRO21)

HTML e CSS são relativamente simples, com pouco tempo de estudos vc pega a base deles =)

- [Codecademy](https://www.codecademy.com/catalog/language/html-css) (gosto bastante desse site)
- [CSS Tricks](https://css-tricks.com/guides/)

E claro, sempre consulte o MDN. Ele é a sua fonte da verdade quando o assunto é documentação =)
