### ISSUE TITLE
Etapa 05, nome do vídeo: Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1886]
Opa blza?
gostaria de uma explicação sobre CSS

![image](https://user-images.githubusercontent.com/45271247/134981371-41cc13ac-9935-4a0f-90e5-ec8448f00d71.png)

Essa forma de nomear classe para mim é novidade.
Se eu escrever várias palavras separadas por um espaço, uma classe vai possuir 3 nomes diferentes, sendo que eu poderei usar qualquer um desses 3 nomes q foi escrito no exemplo?

Qual seria a aplicaçao disso?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986.

Cada palavra é uma classe diferente. 

Ter um conhecimento básico em HTML e CSS é importante para prosseguir com o treinamento, vai te ajudar bastante.

HTML e CSS são relativamente simples, recomendo que vc tire um tempo e estude a base deles. Vc pode começar por algum dos materiais que vou deixar abaixo e ir com calma que vai dar tudo certo =)

- [HTML & CSS 101](https://youtube.com/playlist?list=PLV7VqBqvsd_0XDZab8VaQchHJBkWXtTBO)
- [Codecademy](https://www.codecademy.com/search?query=css)
- [CSS Tricks](https://css-tricks.com/guides/)

**Comment by Rodrigo986** [comment]
Muito obrigado.
