### ISSUE TITLE
Resumo das Aulas 04 da etapa 01

### ISSUE THREAD

**Issue by emanuelcontinib** [roger-melo-treinamentos/curso-de-js-roger-melo#189]
**Booleans e comparações**

`includes()`
**Verifica a existência e retorna** `true` ou `false`
`const email = emanuel@JSfluence.com`
`const includes = email.includes('JS') //true` 
ou
`const array = ['JS', 'emanuel', 'fluente']` 
`const arrayIncludes = array.includes('emanuel') //true`
`const arrayNotIncludes = array.includes('noel') //false` 
No caso de array, buscará um match, por exemplo.

`typeof`
**Operador que retorna uma string com o tipo do dado**
`const strings= 'JS Fluencer'`
`const type = typeof strings // 'string'`

`indexOf()`
**Retorna a posição caso** `true`
`const evenNumbers = [0, 2, 4, 6, 8, 10]`
`evenNumbers.indexOf(2) // 1`
`evenNumbers.indexOf(28) //-1` nesse caso não há 33 e o retorno então é -1

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @emanuelcontinib! Rumo à fluência 🙌🏻
