### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#1890]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/francisko-rezende/cjrm_to-do

### Maiores dificuldades durante a implementação

Utilizar `dataset` ao invés da propriedade `parentElement` para implementar a remoção de items da lista. Demorei um pouquinho para pensar numa forma de implementar essa funcionalidade mas acabei conseguindo =) Agora, se é uma forma bacana de usar esse recurso ou não é outra história hahahahaha

Também estou um pouco inseguro sobre como organizei o código. Fiquei dividido entre agrupar as funções por semelhança (e.g., colocar as funções que lidam com os eventListeners mais próximas entre si assim como as funções que executam tarefas menores, como remover as lis, e assim por diante) ou por "funcionalidade" (e.g., colocar a função que lida com um determinado eventListener logo após as funções mais pontuais que são invocadas dentro daquela função). Acabei optando pela segunda estratégia por preferência mesmo.

Por último, fiquei em dúvida sobre unir as funções `hideMismatchingTodos` e `showMismatchingTodos`. O código dessas funções é bem semelhante, acho que vem daí o impulso de ter uma função só que executa uma ou outra ação dependendo dos parâmetros recebidos. Apesar desse ímpeto, acabei optando por manter essas funções separadas por achar que essa sepação facilita a compreensão do código mas gostaria de saber o que você acha sobre essa opção de reafatoração, Roger.

No mais é isso, obrigado!

### Menores dificuldades durante a implementação

Implementar as funcionalidades da to-do list em si foi bem tranquilo, as aulas cobrem essa parte muito bem!

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> #### Utilizar `dataset` ao invés da propriedade `parentElement` para implementar a remoção de items da lista. Demorei um pouquinho para pensar numa forma de implementar essa funcionalidade mas acabei conseguindo =) Agora, se é uma forma bacana de usar esse recurso ou não é outra história hahahahaha

Na verdade o recomendado é que ao manipular elementos do DOM, vc selecione os elementos usando apenas o atributo `data-*`. Nas próximas aulas vc descobrirá por que e como fazer =)

> #### Também estou um pouco inseguro sobre como organizei o código. Fiquei dividido entre agrupar as funções por semelhança (e.g., colocar as funções que lidam com os eventListeners mais próximas entre si assim como as funções que executam tarefas menores, como remover as lis, e assim por diante) ou por "funcionalidade" (e.g., colocar a função que lida com um determinado eventListener logo após as funções mais pontuais que são invocadas dentro daquela função). Acabei optando pela segunda estratégia por preferência mesmo.

Show. Com a prática e o tempo vc vai encontrando a forma na qual vc gosta de organizar, não há regras quanto a isso (há não ser que vc trabalhe com um time que define isso no code-styling).

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Organização de código

### Comentários

Há algumas `<li>`s comentadas no index.html. Talvez vc tenha se esquecido de descomentar ou remover.

### Indentação

Na `generateTodoHTML`, acredito que a template string fique mais legível se ela for indentada de forma similar a abaixo:

```javascript
const generateTodoHTML = todoContent => `
  <li data-todo-content="${todoContent}" class="message has-background-warning has-text-dark my-1 p-3 is-flex is-justify-content-space-between is-align-items-center">
    <span>${todoContent}</span>
    <i class="fas fa-trash-alt is-clickable delete-item" data-todo-content="${todoContent}"></i>
  </li>`
```

### Nomes de parâmetros

Geralmente, quando o nome do parâmetro tem o mesmo nome do argumento, o código tende a ficar mais compreensível. 

Considerando isso, eu renomearia o parâmetro da `removeLi` para `clickedElement`:

```javascript
const removeLi = clickedElement => {
  document
    .querySelector(`[data-todo-content="${clickedElement.dataset.todoContent}"]`)
    .remove()
}
```

### Refatoração

> #### Por último, fiquei em dúvida sobre unir as funções `hideMismatchingTodos` e `showMismatchingTodos`. O código dessas funções é bem semelhante, acho que vem daí o impulso de ter uma função só que executa uma ou outra ação dependendo dos parâmetros recebidos. Apesar desse ímpeto, acabei optando por manter essas funções separadas por achar que essa sepação facilita a compreensão do código mas gostaria de saber o que você acha sobre essa opção de reafatoração, Roger.

Vc pode mudar um pouco da lógica.

É possível, por exemplo, gerar um array de objetos em que uma propriedade indique se o to-do deve ficar visível. 

Baseando-se nessa propriedade, vc pode manipular as classes que exibem ou escondem o to-do:

```javascript
const showOrHideTodos = todos => {
  todos.forEach(({ todoEl, shoudBeVisible }) => {
    todoEl.classList.add(shoudBeVisible ? 'd-flex' : 'is-hidden')
    todoEl.classList.remove(shoudBeVisible ? 'is-hidden' : 'd-flex')
  })
}

const handleTodoSearches = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array
    .from(todosContainer.children)
    .map(todoEl => ({
      todoEl,
      shoudBeVisible: todoEl.textContent.toLowerCase().includes(inputValue)
    }))

  showOrHideTodos(todos)
}
```

Essa é uma das formas de fazer.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by francisko-rezende** [comment]
Ei Roger!

Obrigado pelo feedback! As sugestões fizeram sentido sim, já as implementei =)

Gostaria de te fazer algumas perguntas:

Na sua implementação da `showOrHideTodos`, você usa dois ternários: um para adicionar  e outro para remover classes. Pelo que eu entendi das aulas, essa abordagem vem do fato da classe `d-flex`, impossibilitar o uso de `display: none` no Bootstrap. Daí, é necessário remover essa classe pra ser possível esconder os _todos_. Esse "problema" não rola com o framework CSS que eu usei na minha versão da aplicação então acabei usando só um ternário:
```javascript
const showOrHideTodo = ({ todo, shouldBeVisible }) => {
  shouldBeVisible 
    ? todo.classList.remove('is-hidden') 
    : todo.classList.add('is-hidden')
}
```
Considerando esses pontos. gostaria de te perguntar se esse meu entendimento de que a sua abordagem vem de uma peculiaridade do Bootstrap procede. Também gostaria de saber se ter duas classes afetando o display, como rola implementação que eu coloquei acima, é considerado uma má prática deve ser evitado.


> Na verdade o recomendado é que ao manipular elementos do DOM, vc selecione os elementos usando apenas o atributo data-*

Não é isso que função `removeLi` faz?
```javascript
const removeLi = clickedElement => {
  document
  .querySelector(`[data-todo-content="${clickedElement.dataset.todoContent}"]`) // Aqui ó
  .remove()
}
```

Obrigado de novo!

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende!

Geralmente, ternários não devem ser usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar a manipulação das classes (em que o valor no qual a expressão `todo.classList.add/remove` resulta não está sendo aproveitado), nesse caso, o ideal é usar `if`: 

```javascript
const showOrHideTodo = ({ todo, shouldBeVisible }) => {
  if (shouldBeVisible) {
    todo.classList.remove('is-hidden')
    return
  }

  todo.classList.add('is-hidden')
}
```

---

> #### Não é isso que função `removeLi` faz?

Sim, me equivoquei no que li e acabei não dando a resposta adequada. Perdão.

Na real, eu quis dizer que nas próximas aulas vc descobrirá por que e como não usar classes para identificar, selecionar e manipular elementos no DOM, como no caso abaixo.

```javascript
const handleTodoDeletion = event => {
  const clickedElement = event.target
  const isClickedElementTrashIcon = Array.from(clickedElement.classList)
    .includes('delete-item')
  
  if (isClickedElementTrashIcon) {
    removeLi(clickedElement)
  }
}
```

---

> #### Também gostaria de saber se ter duas classes afetando o display, como rola implementação que eu coloquei acima, é considerado uma má prática deve ser evitado.

Não é que seja má prática, mas se é possível chegar no mesmo resultado com menos lógica ou escrevendo menos, geralmente é preferível escolher essa opção.

Ou seja, se é possível manipular a visibilidade do elemento usando apenas uma classe CSS (como vc fez), é uma solução muito bem-vinda. Pelo que vi, para manipular a visibilidade de uma `<li>`, basta adicionar ou remover a classe `is-hidden`, certo?

**Comment by francisko-rezende** [comment]
Oi Roger!

> Geralmente, ternários não devem ser usados para executar efeitos colaterais.
>
>O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.
>
>Sabendo disso, ao invés de usar o ternário para executar a manipulação das classes (em que o valor no qual a expressão todo.classList.add/remove resulta não está sendo aproveitado), nesse caso, o ideal é usar if:

Show, tá implementado!

---

>Sim, me equivoquei no que li e acabei não dando a resposta adequada. Perdão.
>
>Na real, eu quis dizer que nas próximas aulas vc descobrirá por que e como não usar classes para identificar, selecionar e manipular elementos no DOM, como no caso abaixo.

OK! Vai ser muito legal aprendar mais sobre isso!

---

>Não é que seja má prática, mas se é possível chegar no mesmo resultado com menos lógica ou escrevendo menos, geralmente é preferível escolher essa opção.
>
>Ou seja, se é possível manipular a visibilidade do elemento usando apenas uma classe CSS (como vc fez), é uma solução muito bem-vinda. Pelo que vi, para manipular a visibilidade de uma <li>, basta adicionar ou remover a classe is-hidden, certo?

Isso mesmo! Obrigado!

---

Obrigado pelo feedback adicional, agora tá tudo certo! :)

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
