### ISSUE TITLE
Etapa 11, Correção dos exercícios da aula 01 da etapa 11 - Aula 02-01

### ISSUE THREAD

**Issue by baronibr** [roger-melo-treinamentos/curso-de-js-roger-melo#1892]
Róger, Boa tarde

Como eu faço para melhorar a minha lógica, fiz todos os exercícios passados sozinho pratiquei bastante entendi perfeitamente como funciona, mas quando vou aplicar em outros exercícios eu não consigo compreender o que a questão quer dizer, cheguei no último exercício da etapa '11' sentir muita dificuldade para compreender.

Como eu faço para conseguir dominar a lógica de uma vez por todas?
Eu tenho dificuldade em compreender sempre quando eu vou para uma nova questão, como eu melhoro isso? Sendo que a questão é lógica pura, é usado apenas o que eu já executei nas atividades anteriores e já faço tudo sozinho. 

```js
let booksBox = {
  spaces: 5,
  booksIn: 0
}

booksBox.addBooksBox = booksQuantity => {

  if(booksBox.booksIn === booksBox.spaces){
    return `A caixa já está cheia`
  }

  if(booksBox.booksIn + booksQuantity > booksBox.spaces){
    const availableSpaces = booksBox.spaces  - booksBox.booksIn
    const fitPluralOrSingular = availableSpaces === 1 ? 'cabe' : 'cabem'
    const pluralOrSingular =  availableSpaces === 1 ? 'livro':'livros'
    return `Só ${fitPluralOrSingular} mais ${availableSpaces} ${pluralOrSingular}`
  }

  booksBox.booksIn += booksQuantity
  const pluralOrSingular = booksBox.booksIn === 1 ? 'livro':'livros'
  return `"Já há '${booksBox.booksIn}' ${pluralOrSingular} na caixa"`
}

console.log(booksBox.addBooksBox(7))
console.log(booksBox.addBooksBox(3))
console.log(booksBox.addBooksBox(3))
console.log(booksBox.addBooksBox(1))
console.log(booksBox)

}
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Como eu faço para conseguir dominar a lógica de uma vez por todas?

@baronibr não existe domínio da lógica. Se vc realmente tem esse objetivo, ficará frustrado toda vez que um problema complexo aparecer em sua frente. 

Esse exercício é mais complexo mesmo, afinal, vc está em um treinamento pra chegar na fluência em JS.

---

O que eu recomendo nesse caso é fazer uma [**revisão raio-x**](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x) à partir da primeira bateria de exercícios, seguindo esse [**passo a passo**](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). 

Regra de ouro: rolou dúvida, no momento em que a dúvida surgiu, não hesite em abrir uma issue. Isso vai fazer com que a dúvida seja mais específica e, portanto, mais fácil de ser sanada.

Se a issue não for aberta no momento que a dúvida surgiu, essa dúvida vai escalar e se ela escalar, a issue no futuro que vc abrirá vai ser menos específica e, por consequência, será mais difícil ser ajudado com precisão.

Pelo que vi em seu histórico, você não enviou as aplicações para a análise. 

Além disso, abriu apenas uma issue pedindo ajuda. 

É pouco. 

Posso estar enganado, mas acho improvável que você teve apenas uma única dúvida durante todo esse tempo.

Essas são as minhas recomendações. Se ficou alguma dúvida, é só dar o toque =)

**Comment by baronibr** [comment]
Obrigado! vou colocar em prática e qualquer dúvida eu abro uma 'Issue'.

**Comment by baronibr** [comment]
Obrigado! vou colocar em prática e qualquer dúvida eu abro uma 'Issue'.
@Roger-Melo

**Comment by Roger-Melo** [comment]
Show, no que precisar, é só abrir uma nova issue =)
