### ISSUE TITLE
Etapa 8, nome do vídeo: O método sort - Aula 02-02

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1895]
Bom-dia ROGER, uma dúvida: 
Já percebi que no Array de objectos abaixo, posso ordenar os itens pela propriedade `score` assim:

```js
const theBigFamily = [
  { name: 'Lineu', score: 20 },
  { name: 'Nenê', score: 10 },
  { name: 'Tuco', score: 50 },
  { name: 'Bebel', score: 30 },
  { name: 'Agostinho', score: 70 }
]

theBigFamily.sort((currentItem, nextItem) => currentItem.score - nextItem.score)
console.log(theBigFamily)
```
Mas como posso ordenar os itens do Array abaixo pela propriedade `name`?
Tentei não deu certo

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafim!

Para usar o [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) nesse caso, vc precisará inserir a função de comparação fazendo com que ela compare a propriedade `name` de cada objeto:

```javascript
const objs = [ 
  { name: 'Bruno' },
  { name: 'Armando' },
  { name: 'Carlos' }
]

const compare = (a, b) => {
  const nameA = a.name.toUpperCase()
  const nameB = b.name.toUpperCase()

  if (nameA < nameB) {
    return -1
  }
  
  if (nameA > nameB) {
    return 1
  }

  return 0
}

console.log(objs.sort(compare))

/*
[
  {name: 'Armando'},
  {name: 'Bruno'},
  {name: 'Carlos'}
]
*/
```

Obsreve que é importante usar `toUpperCase` ou `toLowerCase` pq o `sort`, antes de tentar ordenar os valores, transforma cada valor em string e usa a [tabela Unicode](https://unicode-table.com/en/#control-character) para ordenar os valores. Se não houver uma padronização nas strings antes de fazer a comparação, as maiúsculas são colocadas antes das minúsculas.

Ficou mais claro? =)

**Comment by gerafim** [comment]
Obrigado ROGER,
Percebi, vou treinar com mais exemplos para ter mais domínio

**Comment by Roger-Melo** [comment]
Show, no que precisar, é só abrir uma nova issue =)
