### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by LuizTokuhara** [roger-melo-treinamentos/curso-de-js-roger-melo#1897]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/LuizTokuhara/weather-cjrm

### Maiores dificuldades durante a implementação

Refatoração ainda é um grande desafio, mas aos poucos está começando a ficar claro.

### Menores dificuldades durante a implementação

Comandos mais comuns como selecionar elementos do DOM, fetch para APIs e etc.

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @LuizTokuhara!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> #### Refatoração ainda é um grande desafio, mas aos poucos está começando a ficar claro.

Sempre será. Mas você está indo muito bem, sua evolução é perceptível em relação às análises passadas. E no que tiver dúvidas quanto a isso, estou à disposição para te ajudar =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você sacou a forma correta de usar ternários. Um equívoco comum que várias pessoas cometem é usar ternários para executar efeitos colaterais, sem o objetivo de aproveitar o valor que o ternário retorna. E isso passou longe das duas ocorrências de ternário na aplicação. Muito bom!

Os nomes das suas variáveis e funções estão bem descritivos, e isso facilitou a compreensão do código.

## Organização de código

### Comentários

No `weather.js`, rolou um comentário esquecido dentro da `getCityWeather`.

## Lógica

É mais interessante que o caminho do ícone seja absoluto, e não relativo. Assim, se o `app.js` mudar de lugar, a busca do ícone continua intacta e o código não quebra, pois a busca parte da raiz da aplicação.

```javascript
// antes (relativo)
`<img src="../src/icons/${WeatherIcon}.svg" />`

// depois (absoluto)
`<img src="./src/icons/${WeatherIcon}.svg" />`
```

---

Se preferir, `showWeatherCard` e `reset` do `cityForm` podem ser invocadas dentro de `addWeatherDataToDom`. Isso faz com que a manipulação de DOM fique concentrada em apenas uma parte da aplicação:

```javascript
const addWeatherDataToDom = (...) => {
  // ...
  cityTemperatureContainer.textContent = Temperature;
  showWeatherCard();
  cityForm.reset();
};
```

---

Outra modificação que pode ser feita na `addWeatherDataToDom` é que ela pode receber um objeto ao invés de vários argumentos/parâmetros.

Você pode usar um objeto como argumento de uma função quando quiser:

- Diminuir o número de argumentos/parâmetros que uma função recebe;
- Deixar mais claro o que os valores inseridos como argumentos significam.

Funções com vários argumentos são mais complexas de testar e manter, pois exigem que casos diferentes sejam testados com cada argumento individualmente.

Como o JS permite que objetos sejam criados à qualquer momento, sem a necessidade de usar classes, um objeto pode substituir vários argumentos espalhados na invocação de uma função.

Outra vantagem é que objetos não precisam obedecer uma ordem de parâmetros. Na função abaixo, é obrigatório que ao invocá-la, o ícone seja o 1º argumento, o boolean o segundo, etc. Se essa ordem não for obedecida, o código quebra.

```javascript
const addWeatherDataToDom = (
  WeatherIcon,
  IsDayTime,
  LocalizedName,
  WeatherText,
  Temperature
) => {
  // ..
};
```

Pegando um outro exemplo, se vc observar a invocação abaixo, não fica tão explícito o que os valores inseridos como argumentos significam:

```javascript
manipulateClasses(todosToHide, 'hidden', 'd-flex')
```

Porém, se um objeto for inserido como argumento, fica mais fácil entender por que 'hidden' e 'd-flex' (por exemplo) estão sendo usadas ali:

```javascript
manipulateClasses({ todos: todosToHide, classToAdd: 'hidden', classToRemove: 'd-flex' })
```

Ou seja, fica fácil saber que `hidden` é a classe a ser adicionada e `d-flex` é a classe a ser removida. Mas claro, isso só funciona se os nomes das propriedades deixarem isso explícito.

Voltando para o exemplo da `addWeatherDataToDom`, mesmo que os argumentos que ela recebe estejam legíveis, acho que vale a refatoração, devido às vantagens que mencionei acima.

Ficaria assim:

```javascript
const addWeatherDataToDom = data => {
  // ...
};

// ...

addWeatherDataToDom({
  WeatherIcon,
  IsDayTime,
  LocalizedName,
  WeatherText,
  Temperature
});
```

E claro, se vc quiser, pode fazer o destructuring do objeto que está sendo recebido como parâmetro:

```javascript
const addWeatherDataToDom = ({ 
  WeatherIcon,
  IsDayTime,
  LocalizedName,
  WeatherText,
  Temperature 
}) => {
  // ...
};
```

---

Nas aulas seguintes, você verá mais formas de refatorar o código dessa aplicação.

Novamente, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
