### ISSUE TITLE
QuizInterativo

### ISSUE THREAD

**Issue by TaynaraCM** [roger-melo-treinamentos/curso-de-js-roger-melo#19]
Bom dia/tarde/noite, 
    segue o link da minha versão do quiz: https://github.com/TaynaraCM/ProjetoQuizCRM.git
Durante o processo tive a mesma dificuldade do colega Bruno, queria retornar as respostas certas em verde e as erradas em vermelho, porém não sabia como referenciar cada uma dentro do forEach. 
Outra dúvida que surgiu: A primeira resposta de cada pergunta já vem marcada por padrão ao carregar a página. É possível alterar esta configuração, algum tipo de 'preventDefault()' só que para o input radio? Supondo que o jogador esquecesse de marcar alguma questão, ao invés de uma resposta que ele não marcou ser computada, o quiz poderia retornar algum feedback o avisando de que a resposta não foi dada.
Att.

**Comment by Roger-Melo** [comment]
Oi @TaynaraCM. Parabéns pelo projeto!

Para deixar inputs não selecionados por padrão ao carregar página, basta remover o atributo "checked" dos inputs. Mas não faz sentido fazer isso. Você estará induzindo visualmente o usuário a enviar um formulário sem resposta alguma. E você precisa das respostas.

No envio do form, se uma resposta não foi checada, o array playerAnswers irá conter um item com uma string vazia `''` para cada questão sem resposta.

Então abaixo da declaração desse array, na função do submit do form, você pode implementar um if que checa se existe alguma string vazia no array. Se houver, você pode exibir o feedback visual que você quiser e inserir um return no final do if, para que o código abaixo do if seja ignorado.

Para mudar as cores de background das alternativas certas e erradas, abaixo de cada `<p>` que contém as perguntas, há duas divs irmãs. Você pode inserir uma classe CSS `wrong-answer` na div que contém a resposta errada e inserir uma classe `correct-answer` na div que contém a resposta correta.

No topo do código, obtenha e armazene em uma const as referências de todas as divs com essas classes, erradas e corretas.

Nas últimas linhas da função de envio do form, percorra o array com cada referência das divs com respostas erradas e adicione um backgroundColor inline nelas. Faça o mesmo com as divs das respostas corretas.

Essa é uma forma de fazer. Ficou claro?

Se tiver dúvida em qualquer coisa que eu falei, é só dar o toque =)

**Comment by TaynaraCM** [comment]
Obrigada!
Com relação à adição de cores, consegui realizar, porém, não da forma que o sr. orientou. Não estava conseguindo acessar a propriedade checked de forma indireta através das divs.  Assim, tive que 'trapacear' atribuindo os inputs diretamente em uma const (allInputs). Além disso, como eu não sabia ao certo como indicar ao JS qual alternativa era a correta ou não, adicionei classes aos inputs (T para as verdadeiras e F para as falsas) e baseei as condicionais nelas. Sei que isto não é ideal, pois o jogador pode dar inspect na página e 'colar' as respostas. Segue o projeto atualizado   https://github.com/TaynaraCM/ProjetoQuizCRM.git

**Comment by Roger-Melo** [comment]
Oi @TaynaraCM.

Não se preocupe em deixar o projeto "perfeito e sem brechas de segurança" agora.

Com o passar do tempo você evoluirá na linguagem e verá oportunidades de melhorias nos projetos que desenvolveu. Isso é parte do processo. Ainda mais em JavaScript, que é uma linguagem que te dá a liberdade de fazer a mesma coisa de "N" formas diferentes.

Apenas lembre-se de ir removendo os console.log à medida em que for atualizando o projeto =)

Parabéns novamente, e no que precisar é só chamar aqui.
