### ISSUE TITLE
Etapa 14, Factory functions e composição de objetos - Aula 03-09

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#190]
Eu tô tendo que reassistir por completo as aulas de funções construtoras até factory functions pq começou a complicar (primeira vez no curso que sou obrigado a isso) rs

Na aula 03-09 eu senti falta de uma coisas:

1. Como fica a sintaxe de factory function retornando um objeto que tenha métodos de outro objeto? É só usar o spread dentro do `return`?
2. Se eu tiver uma propriedade, vou usar a `counter` do vídeo como exemplo,  que trabalha com um método `incrementCounter`, como eu faço para passar ambas para outro objeto? Também é com spread?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

A etapa 14 tem esse impacto inicial =)

> 1. Como fica a sintaxe de factory function retornando um objeto que tenha métodos de outro objeto? É só usar o spread dentro do `return`?

Isso mesmo. Você pode usar o spread para espalhar as propriedades de um objeto dentro de outro objeto. No código abaixo, o parâmetro `obj` da `myFactory` recebe o objeto `{ prop1: () => 'a', prop2: () => 'b' }`:

```javascript
const myFactory = obj => ({
  ...obj, // "espalhou" prop1 e prop2
  prop3: () => 'c'
})

const myConst = myFactory({ prop1: () => 'a', prop2: () => 'b' })

myConst // { prop1: () => 'a', prop2: () => 'b', prop3: () => 'c' }
```

Se ao invés de espalhar todos os métodos de `obj`, você quiser selecionar quais métodos o objeto que a factory retorna terá, pode usar a notação de ponto ou destructuring (mais conciso):

```javascript
const myFactory = obj => ({
  prop1: obj.prop1,
  prop3: () => 'c'
})

// ou

const myFactory = ({ prop1 }) => ({
  prop1,
  prop3: () => 'c'
})
```

E claro, se por qualquer motivo o objeto não puder ser recebido no parâmetro da factory, ele pode estar em um escopo externo à ela:

```javascript
const obj = { prop1: () => 'a', prop2: () => 'b' }

const myFactory = () => ({
  prop1: obj.prop1,
  prop3: () => 'c'
})

const myConst = myFactory()

myConst // { prop1: () => 'a', prop3: () => 'c' }
```

> 2. Se eu tiver uma propriedade, vou usar a `counter` do vídeo como exemplo,  que trabalha com um método `incrementCounter`, como eu faço para passar ambas para outro objeto? Também é com spread?

A sacada da `counter` é que ela é privada àquele escopo da factory. Ela só pode ser manipulada através dos métodos do objeto que a factory retorna. Neste momento, estou escrevendo uma aula que mostra a importância disso em uma aplicação real.

Mas resumindo, se você precisa que a counter continue privada, pode inserir no objeto que a factory retorna um método getter e um setter, para obter e setar valores da counter.

```javascript
const myFactory = () => {
  let counter = 0

  return {
    getCounter: () => counter,
    setCounter: value => {
      counter = value
    }
  }
}

const myConst = myFactory()

myConst.setCounter(9)
myConst.getCounter() // 9
myConst.setCounter(7)
myConst.getCounter() // 7
```

Observe que se eu declarar no objeto uma propriedade `counter` que armazena o valor que a `counter` armazena (através de shorthand property names), `myConst` armazena o objeto que a factory retornou no momento em que ela foi invoada.

```javascript
const myFactory = () => {
  let counter = 0

  return {
    counter,
    setCounter: value => {
      counter = value
    }
  }
}

const myConst = myFactory()

myConst.setCounter(9)
myConst.counter // 0
myConst.setCounter(7)
myConst.counter // 0
```

Isso significa que a propriedade `counter` armazenou o valor da `let counter` do momento em que `myFactory()` foi executada.

Ou seja, só é possível acessar o valor atual da `let counter` através do método `getCounter: () => counter` do exemplo anterior. Esse método consegue acessar o valor "vivo" da `let` na memória por que ele é uma closure. 

Ou seja, `getCounter: () => counter` é uma closure por que acessa variáveis que foram declaradas no escopo léxico. Sempre que `myConst.getCounter()` for invocado, ele irá buscar na memória o valor atual da `counter`.

Respondi as perguntas?

@lucasfads

**Comment by lucasfads** [comment]
Beleza, e se (continuando o primeiro exemplo que você deu para a segunda pergunta) eu quiser fazer uma segunda factory que herda tanto uma propriedade quanto um método da `myFactory`?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Dentro da segunda factory, você pode obter o objeto que a primeira factory retorna e usar um destructuring nele para selecionar as propriedades que o objeto que a segunda factory retorna deve conter:

```javascript
const myFactory = () => {
  let counter = 0

  return {
    getCounter: () => counter,
    setCounter: value => {
      counter = value
    },
    anotherProp: 'some value'
  }
}

const myFactory2 = () => {
  const { setCounter, anotherProp } = myFactory()

  return {
    setCounter,
    anotherProp,
    propFromMyFactory2: 'hello'
  }
}

const obj = myFactory2()

obj // { anotherProp: "some value", propFromMyFactory2: "hello", setCounter: ƒ }
```

Dependendo do objetivo da segunda factory, ela pode receber por parâmetro o objeto no qual ela vai fazer o destructuring.

Era essa a dúvida?

@lucasfads

**Comment by lucasfads** [comment]
Nessa situação o `obj` vai automaticamente ter uma `let counter`?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Não. Objetos tem apenas propriedades (e métodos). 

Porém, toda vez que `myFactory` é invocada, ela cria um `counter` na memória. No exemplo abaixo, 

```javascript
const myFactory = () => {
  let counter = 0

  return {
    getCounter: () => counter,
    setCounter: value => {
      counter = value
    },
    anotherProp: 'some value'
  }
}

const myFactory2 = () => ({
  ...myFactory(), // criou um counter na memória e espalhou as propriedades do objeto que myFunc retornou
  propFromMyFactory2: 'hello'
})

const obj = myFactory2() // {anotherProp: "some value", propFromMyFactory2: "hello", getCounter: ƒ, setCounter: ƒ}

obj.getCounter() // 0
obj.setCounter(7)
obj.getCounter() // 7
```

`obj` é um objeto que contém as propriedades do objeto que a `myFactory` retorna. Isso significa que o `obj` contém métodos que manipulam o `counter`. Tanto é que quando invoco `obj.getCounter`, o valor do counter é obtido e quando invoco `setCounter`, o counter sofre uma reatribuição de valor. E isso só é possível por que esses métodos são uma closure - eles usam e mantém a referência do `counter` que foi declarado.

Sacou a ideia?

@lucasfads

**Comment by lucasfads** [comment]
Aaaaah, perfeito.
Então eu não tinha entendido antes essa questão de quando/como/onde o `counter` é criado.
Muito obg!

@Roger-Melo
