### ISSUE TITLE
Etapa 11, Status de respostas HTTP - Aula 02-04

### ISSUE THREAD

**Issue by baronibr** [roger-melo-treinamentos/curso-de-js-roger-melo#1900]
![dúvida](https://user-images.githubusercontent.com/75046998/135609794-a98c40b7-8186-4690-a979-7bdfdd7f13fe.png)
Quando retorna o 'JSON' no console tá aparecendo todo bagunçado é normal ? 
Segue a foto...
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @baronibr!

Sim, normal. Mas se quiser que eu teste aqui em minha máquina para comprovar se é alguma configuração de exibição do browser, suba todos os arquivos em um repo do GitHub ou em uma pasta no google drive e envie o link =)

**Comment by Roger-Melo** [comment]
Issus respondida e fechada [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1905).
