### ISSUE TITLE
Etapa 7, revisão raio X

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#1901]
Bom dia Roger,

Nas revisões raio X podemos resolver os exercícios inicias aplicando os conhecimentos adquiridos nos exercícios mais avançados?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @paulovieiradasilva.

Por que não das duas formas?

Resolver o mesmo problema de formas diferentes é um bom exercício de aprendizado da linguagem =)

**Comment by paulovieiradasilva** [comment]
Legal!

Aproveito para dar parabéns pelo excelente treinamento.

**Comment by Roger-Melo** [comment]
Fico feliz que esteja curtindo.

Conte comigo para chegar na fluência em JavaScript. No que precisar, é só abrir uma issue =)
