### ISSUE TITLE
Etapa 5, nome do vídeo: 03-03

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#1902]
Professor, acontece que durante a aula sobre o evento 'click' o senhor mostra o objeto 'event' que ao ir pro 'console.log' é retornado um objeto de nome 'MouseEvent', porém quando eu fiz o mesmo procedimento,  o obeto mostrado era de nome 'PointerEvent'.
apesar disso consegui fazer todos os demais comandos, ainda sim vi algumas diferenças nos dois objetos. Veja os prints:

realização do código pelo professor Roger
![image](https://user-images.githubusercontent.com/85198581/135628885-6dcc8153-21f8-4786-9365-31d567d0436c.png)

realização do código por mim
![image](https://user-images.githubusercontent.com/85198581/135629136-2a756e87-b68f-4b92-b770-4f9dec11753a.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208!

Posta todo o código (HTML, CSS e JS) para eu testar aqui =)

**Comment by CarlosHenrique2208** [comment]
perdão a demora, a luz onde moro foi embora.
não consegui colocar  uma pasta o documento pro VScode, então copiei e coloquei no word(tentei só comentar tudo aqui pelo github, mas não tava 100% correto algumas coisas escritas.

[carlos.henrique.docx](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7268925/carlos.henrique.docx)

**Comment by Roger-Melo** [comment]
Saquei, @CarlosHenrique2208.

O que está sendo exibido ao clicar realmente é o `PointerEvent`, talvez alguma implementação no browser atualizou a forma como esse evento é exibido. Mas, em regras gerais, tanto faz, por que o `PointerEvent` herda propriedades de `MouseEvent` e `Event`. Você entenderá o que significa "herdar propriedades" na etapa 14 =)

Independente disso, observe que a expressão `event.target` resulta no elemento clicado da mesma forma (que é o que nos interessa nesse momento). Então por agora, pode usar a propriedade `target` como mostrado nas aulas e seguir os estudos =)

Ficou mais claro?

**Comment by CarlosHenrique2208** [comment]
Sim, percebi que ambos os -event tem proximidade e não interferiu na aula,
mas achei bem estranho na hora. Enfim, obrigado professor

Em sáb, 2 de out de 2021 00:07, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
