### ISSUE TITLE
Etapa 11, Trabalhando com JSON (JavaScript Object Notation) - Aula 03-04

### ISSUE THREAD

**Issue by baronibr** [roger-melo-treinamentos/curso-de-js-roger-melo#1905]
```js
const request = new XMLHttpRequest()

const getTodos = (url, callback) => {
    
    request.addEventListener('readystatechange', () => {
        const isRequestOk = request.readyState === 4 && request.status === 200
        const isRequestNotOk = request.readyState === 4
        if(isRequestOk){
            //Objeto embutido do Javascript
            const data = JSON.parse(request.responseText) // parse = converter 
            callback(null, data)
            return
        }
    
        if(isRequestNotOk){ 
            callback('não foi possível obter os dados', null) 
        }
    })
    
    request.open('GET', url)
    request.send()

}


getTodos('./json/todos-02.json',(error, data) => {
    console.log(data)
    getTodos('./json/todos-02.json', (error, data) => {
        console.log(data)
    })
})

}
```

![error](https://user-images.githubusercontent.com/75046998/135718335-10d55911-d471-4558-a802-bbd738b925d9.png)

Estou com essa (dúvida) professor na hora estou executando o segundo 'callback' fica dando um loop infinito, porque isso acontece?
![error](https://user-images.githubusercontent.com/75046998/135718453-a32ab697-970e-48b3-80c4-94e6f8893e5e.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @baronibr. Você pode postar todo o código? 

Escolha a opção que preferir:

- subir todos os arquivos em um repositório do GitHub;
- subir todos os arquivos no Google Drive;
- postar o código de todos os arquivos aqui na issue.

Assim eu testo aqui em minha máquina e te ajudo com mais precisão =)

**Comment by baronibr** [comment]
Certo! vou fazer isso aqui agora. Já já te mando!
@Roger-Melo

**Comment by baronibr** [comment]
Segue abaixo o link
https://drive.google.com/drive/folders/1Z1296SrT7ChXfSb8NG102AqS_SE3nXty?usp=sharing
@Roger-Melo

**Comment by Roger-Melo** [comment]
@baronibr o problema está na primeira linha do código. 

A declaração do objeto `XMLHttpRequest` precisa estar dentro da função `getTodos`, dessa forma: 

```javascript
const getTodos = (url, callback) => {
  const request = new XMLHttpRequest()

  // ...
}
```

Basta apenas modificar isso para solucionar o problema.

Se a criação do objeto de request estiver de fora do escopo da `getTodos`, o loop infinito acontece pq dentro da `getTodos` o mesmo objeto está sendo usado. Ou seja, é necessário que a cada invocação da `getTodos`, um novo objeto `XMLHttpRequest` seja criado em memória, e isso só acontece se o objeto está dentro da função.

**Comment by baronibr** [comment]
Entendi 'mestre', obrigado, resolvido!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
