### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#1907]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuFML/to-do-list

### Maiores dificuldades durante a implementação

Refatoração e coo acessar o event de um addEventListener fora dele.

### Menores dificuldades durante a implementação

Layout, iterar arrays e saber qual método usar.

**Comment by Roger-Melo** [comment]
Olá @JuFML.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuFML!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Refatoração e coo acessar o event de um addEventListener fora dele.

Conforme vc for praticando, verá que a Refatoração aos poucos vai se tornando mais natural =)

Para acessar o `event` fora da função em que ele foi declarado, você pode inserí-lo como argumento da invocação de outra função, olha só:

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()
  showEvent(event)
})
```

No código acima, quando o form é enviado a função `showEvent` é executada recebendo o `event` como argumento, certo?

A `showEvent` pode ser uma função que apenas exibe o `event` no console. A declaração dela ficaria mais ou menos assim:

```javascript
const showEvent = () => {
  console.log()
}

form.addEventListener('submit', event => {
  event.preventDefault()
  showEvent(event)
})
```

Porém, para que a `showEvent` receba o `event` que foi inserido como argumento da invocação dela, ela precisa ter um parâmetro. 

Lembra que parâmetros são variáveis locais de uma função?

A `showEvent` pode ter um parâmetro `x`, por exemplo. Esse parâmetro recebe o valor que foi inserido como argumento da invocação da `showEvent`:

```javascript
const showEvent = (x) => {
  console.log(x)
}

form.addEventListener('submit', event => {
  event.preventDefault()  
  showEvent(event)
})
```

Com o código acima, quando um to-do é adicionado, a `showEvent` é executada e nessa execução, como o parâmetro `x` recebe o valor que a invocação da função recebeu como argumento (`event`), o `console.log()` dentro da `showEvent` exibe `SubmitEvent` no console.

Então uma forma fácil de usar o `event` fora da função em que ele está é inserindo-o como argumento de uma outra função (e isso vale pra qualquer parâmetro, não apenas o event).

Geralmente, não é muito útil passar apenas o event para outra função. O mais comum é usar o `event` pra obter um valor que alguma propriedade/método dele retorna. 

Para obter o valor do input no momento em que o `<form>` foi enviado, por exemplo, ao invés de inserir o event como argumento, vc pode inserir a expressão `event.target.add.value`:

```javascript
const showInputValue = (x) => {
  console.log(x)
}

form.addEventListener('submit', event => {
  event.preventDefault()
  
  showInputValue(event.target.add.value)
})
```

Como o form tem um input com um atributo `name` que tem o valor `add`, a expressão `event.target.add` resulta na referência desse input e então, basta encadear a propriedade `value` nessa referência.

Está ficando mais claro?

Sobre a aplicação em si, vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

A imagem de fundo deu um visual bem legal para a aplicação.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

## Organização de código

### Nomes de variáveis e funções

Como há dois `<form>` no mesmo código, acredito que se `form` for nomeada como `formAddTodo` ou algo do tipo, o nome dela fica mais específico e com isso fica mais fácil distinguir qual dos dois forms a `const` armazena.

---

Dentro do callback do addEventListener do `todosContainer`, se a expressão `Array.from(clickedElement.classList).includes('delete')` for atribuída à uma `const`, acredito que o `if` fica mais legível. Ela pode se chamar `isTrash` ou algo do tipo. 

```javascript
todosContainer.addEventListener('click', event => {
  const clickedElement = event.target
  const isTrash = Array.from(clickedElement.classList).includes('delete')

  if (isTrash) {
    clickedElement.parentElement.remove()
  }
})
```

## Lógica

`showTodoSearched` e `hideTodoNotSearched` são consts que estão armazenando `undefined`, vc pode comprovar isso ao exibí-las no console no momento da filtragem dos to-dos:

```javascript
inputSearchTodo.addEventListener('input', event => {
  // ...

  console.log(hideTodoNotSearched, showTodoSearched) // undefined undefined
})
```

Elas armazenam `undefined` por que há um `forEach` encadeado no final das expressões que elas armazenam, e o `forEach` nunca retorna valor. O `forEach` apenas executa efeitos colaterais. Então se as consts forem removidas do código, a filtragem continuará funcionando da mesma forma:

```javascript
inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()

  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
    })

  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
})
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JuFML** [comment]
Obrigada Roger, você é sempre cirúrgico em suas pontuações.
