### ISSUE TITLE
Aplicação: Todo - List

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1911]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/gerafim/Exercicio24-Todo-List

### Maiores dificuldades durante a implementação

1. Uso de `data-*` em substituição do `parentElement`. Não consegui utilizar. Pesquisei no MDN mas não percebi como usar.
2. Refactoração: principalmente na função de Pesquisa do TODO, queria evitar a repetição do `!todo.textContent.toLowerCase().includes(inputValue)` ao filtrar os TODO's, mas não consegui.

### Menores dificuldades durante a implementação

1. Isolar as funções que realizam tarefas únicas. Tentei, mas não tenho tanta certeza de que fiz correcto =)

**Comment by Roger-Melo** [comment]
@gerafim , eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Fico no aguardo.

**Comment by gerafim** [comment]
Obrigado Roger pela observação e recomendação. 
Já fiz as devidas alterações e estarei abrindo uma nova Issue
