### ISSUE TITLE
Etapa 05, nome do vídeo: Event bubbling e event delegation - Aula 04-02 

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1912]
Roger, eu li alguns resumos e nao esclareceu de forma clara minha dúvida. 

Pelo que eu entendi e fiz uns testes aqui, só confirma se é isso mesmo.

Mesmo que um elemento filho nao tenha um evento, tipo uma li que é filha de uma ul, mas o elemento pai possui um evento, o efeito de propagação irá acontecer?

Eu entendi que:
Se eu tiver uma div filha sem nehum evento, e se eu tiver um article como pai dessa div com um evento "click", se eu clicar nessa div filha irá disparar o evento do article pai da div.

Resumindo, event delegation é quando a interação em um elemento filho dispara um ou mais  evento(s) pertecente(s) ao(s) elementos  pai mesmo que esse elemento filho não possua nehum evento atrelado a ele.

Confere? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodrigo986.

> Mesmo que um elemento filho nao tenha um evento, tipo uma li que é filha de uma ul, mas o elemento pai possui um evento, o efeito de propagação irá acontecer?

Sim. Você pode testar isso facilmente se executar o código abaixo:

```html
<ul>
  <li>Conteúdo aqui</li>
</ul>
```

```css
ul {
  background-color: aqua;
  width: 200px;
  height: 200px;
}
```

```javascript
const ul = document.querySelector('ul')

ul.addEventListener('click', () => {
  console.log('callback executado')
})
```

Ao clicar em "Conteúdo aqui", o callback é executado.

> #### Resumindo, event delegation é quando a interação em um elemento filho dispara um ou mais  evento(s) pertecente(s) ao(s) elementos  pai mesmo que esse elemento filho não possua nehum evento atrelado a ele.

Event delegation é um conceito que se baseia no fato de que se vc quer que um código seja executado em qualquer um de vários elementos, é possível setar o event listener no pai desses elementos.

Vou deixar um [artigo do MDN](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events) que fala com detalhes sobre isso. Caso algo não tenha ficado claro, é só dar o toque =)

**Comment by Rodrigo986** [comment]
ficou claro! Obrigado.
