### ISSUE TITLE
Aplicação: Todo-List

### ISSUE THREAD

**Issue by gerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#1913]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/gerafim/Exercicio24-Todo-List

### Maiores dificuldades durante a implementação

1. Uso de `data-*` em substituição do `parentElement`. Não consegui utilizar. Pesquisei no MDN mas não percebi como usar.
2. Refactoração: principalmente na função de Pesquisa do TODO, queria evitar a repetição do `todo.textContent.toLowerCase().includes(inputValue)` ao filtrar os TODO's, mas não consegui.

### Menores dificuldades durante a implementação

1. Isolar as funções que realizam tarefas únicas. Tentei, mas não tenho tanta certeza de que fiz correcto =)

**Comment by Roger-Melo** [comment]
Olá @gerafim.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui.

As novas cores ficaram bacanas =)

**Comment by Roger-Melo** [comment]
Olá @gerafim!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### 1. Uso de `data-*` em substituição do `parentElement`. Não consegui utilizar. Pesquisei no MDN mas não percebi como usar.

Não tem problema. Nas próximas aulas você verá como e por que implementar remoção de elementos do DOM sem usar estratégias como a do `parentElement` =)

> ### 2. Refactoração: principalmente na função de Pesquisa do TODO, queria evitar a repetição do `todo.textContent.toLowerCase().includes(inputValue)` ao filtrar os TODO's, mas não consegui.

Eu mostro uma forma de fazer isso nas próximas aulas.

Mas vou deixar aqui uma outra forma interessante também (além da que mostro nas aulas seguintes), olha só...

Se não quiser repetir o `filter`, vc pode mudar um pouco da lógica. 

É possível, por exemplo, gerar um array de objetos em que uma propriedade indique se o to-do deve ficar visível e, baseado nessa propriedade, manipular as classes que exibem ou escondem o to-do:

```javascript
const showOrHideTodos = todos => {
  todos.forEach(({ todoEl, shoudBeVisible }) => {
    todoEl.classList.add(shoudBeVisible ? 'd-flex' : 'hidden')
    todoEl.classList.remove(shoudBeVisible ? 'hidden' : 'd-flex')
  })
}

const findTodo = event => {
  const todos = Array
    .from(todosContainer.children)
    .map(todoEl => ({
      todoEl,
      shoudBeVisible: todoEl.textContent.toLowerCase().includes(event.target.value.toLowerCase())
    }))

  showOrHideTodos(todos)
}
```

Essa é uma das formas de fazer =)

Se a repetição do `toLowerCase` estiver incomodando, vc pode abstrair, criando uma função como essa:

```javascript
const getLowerCase = str => str.toLowerCase()
```

Mas nesse caso específico, acho que não vale a pena o esforço.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outro ponto positivo foi que vc usou bem os `reset`. Isso faz com que o usuário poupe o esforço de tocar ou levar o mouse até o input novamente.

## Organização de código

### Consts não usadas

A const `noMatch` pode ser removida do código, pois não está sendo usada.

### Nomes de variáveis e funções

`todosForm` é um nome que pode confundir, afinal, a aplicação contém dois forms e ambos estão relacionados aos to-dos. O ideal é especificar que esse é o form que adiciona o to-do, então vc pode nomear como `formAddTodo`, por exemplo.

### Indentação

A indentação da marcação HTML do to-do pode ser reorganizada para que fique mais legível:

```javascript
const todoElement = `
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete"></i>
  </li>`
```

A indentação do encadeamento dos métodos `filter` e `forEach` pode ser reorganizada de modo que fique mais claro onde é o começo da invocação de cada método:

```javascript
// antes
todosList.filter(todo =>
  !todo.textContent.toLowerCase().includes(inputValue))
  .forEach(addCSSClassOnTodo)

// depois
todosList
  .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))
  .forEach(addCSSClassOnTodo)
```

### O método `preventDefault`

Prefira deixar comentários na issue ao invés de comentar no código. Sei que vc fez isso pq sabia que eu iria olhar, mas o ideal é que vc se acostume a não comentar no código. Não é uma regra, mas na maioria das vezes, um código legível faz com que comentários sejam desnecessários.

Mas respondendo a pergunta, sim. É útil usar o `preventDefault`. Sempre suponha que o usuário não irá fazer a coisa certa. Vou falar mais disso em aulas futuras sobre TDD =)

Porém, para evitar que a página seja recarregada quando o form é enviado, é necessário atrelar um evento `submit` **no form** ao invés do input:

```javascript
const formSearchTodo = document.querySelector('.form-search')

// ...

const preventFormSend = e => e.preventDefault()

// ...

formSearchTodo.addEventListener('submit', preventFormSend)
```

### Legibilidade

A expressão `Array.from(...)` pode ser atribuída à uma const para que o `if` fique mais legível. A const pode se chamar `isTrash` ou algo do tipo:

```javascript
// antes
if (Array.from(clickedElement.classList).includes('delete')) {}

// depois
if (isTrash) {}
```

Prefira declarar `addCSSClassOnTodo` e `removeClassOnTodo` antes de suas invocações. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

---

Como eu mencionei anteriomente, nas aulas seguintes você verá outra forma de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by gerafim** [comment]
Obrigado ROGER

Vou mais 1 vez, antes de prosseguir, refazer o todo para ganhar mais prática ( considerando todas as suas recomendações). Quanto a não repetição do `filter`, a técnica de gerar objecto que demostrou ficou meio complexa, o que acabou me atrapalhando. Mas vou olhar com calma e verei também a técnica de refactoração na correção do Exercício, nas aulas seguintes.

Muito obrigado, tudo fez sentido!
