### ISSUE TITLE
Resumo da Aula 02-02 e 02-03 da etapa 2

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#192]
/*-------------------------------------------------------------------------------------------------
Etapa 2 - Aula 02-02
-------------------------------------------------------------------------------------------------*/

/*

Condicional If

*/

const simpsons = ['MArge', 'Homer', 'Lisa', 'Bart']

if (simpsons.length >= 3) {
    console.log('o array tem bastate personagens')
}

/* Neste exemplo, utilizamos a condicional If para verificar quantos itens existem no array simpsons. Quando a afirmação 
resulta em true, a iteração é executada.*/

const password1 = 'oi123'
if (password1.length >= 8) {
    console.log('essa senha tem 8 ou mias caracteres')
}

/* Aqui fizemos a mesma coisa, entretanto, este exemplo abre magem para uma função complementar do If.*/

//-------------------------------------------------------------------------------------------------

/*-------------------------------------------------------------------------------------------------
Etapa 2 - Aula 02-03
-------------------------------------------------------------------------------------------------*/

/*

Else

*/

const password2 = 'oi123'
if (password2.length >= 8) {
    console.log('essa senha tem 8 ou mias caracteres')
}

else {
    console.log('a senha deve ter 8 ou maais caracteres')
}

/* Desta vez, nosso código ficou completo, pois agora temos uma resposta para ambos os casos, utilizando o Else. */

const password3 = 'oi123'
if (password3.length >= 12) {
    console.log('senha muito forte =)')
} else if (password3.length >= 8) {
    console.log('essa seha tem 8 ou mais caracteres')
} else {
    console.log('A senha deve ter 8 ou mais caracteres')
}

/* Com a finalidade de possibilitar múltiplas verificações, o comando else if nos foi apresentado. Ele funciona como
uma alternativa, que permite que o código se estenda até onde desejarmos.*/

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa YureK. Rumo à fluência 💪🏻
