### ISSUE TITLE
etapa:06 vídeo:Correção dos exercícios da aula passada - Aula 02-01

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1931]
Roger, eu particularmente prefiro usar o "else" sempre.
Tem alguma desvantagem em usar o "else" ao invés de "return"  quando um 'if" está dentro de uma função?

Na correção dos exercícios eu notei a vantagem pelomenos de usar um "else" pois eu nao tive que atribuir a string vazia 2 vezes.

Outra coisa que eu notei nessa correção,  é que a regex  feita no exercicio faltou o "^" na abertura e "$" no feichamento, pois quando eu coloquei sem  uma string que possuia mais de 11 caracteres, foi dada como válida mesmo eu estipulando o limite de 11 caracteres.
 

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Roger, eu particularmente prefiro usar o "else" sempre. Tem alguma desvantagem em usar o "else" ao invés de "return"  quando um 'if" está dentro de uma função?

@Rodrigo986 "sempre" é um extremo. 

Desvantagem: seu código ficará mais verboso e menos elegante =)

---

> ### Na correção dos exercícios eu notei a vantagem pelomenos de usar um "else" pois eu nao tive que atribuir a string vazia 2 vezes.

O código final da aula não tem duas atribuições de string vazia. Pode postar seu código para eu entender melhor? Sobe o projeto com todos os arquivos no github ou drive e manda o link.

---

> ### Outra coisa que eu notei nessa correção,  é que a regex  feita no exercicio faltou o "^" na abertura e "$" no feichamento, pois quando eu coloquei sem  uma string que possuia mais de 11 caracteres, foi dada como válida mesmo eu estipulando o limite de 11 caracteres.

Show, vou deixar essa observação anotada para uma futura regravação da aula. Valeu =D

**Comment by Rodrigo986** [comment]
Quando eu falei das duas strings vazias, foi porque eu nao terminei de assistir tudo e você modificou o código.
No mais eu entendi o motivo de usar o return ao invés do else.
obrigado!
