### ISSUE TITLE
Etapa 05, nome do vídeo: Exercícios 02 - Aula - 03-01

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#1945]
@Roger-Melo  no exercício nr 01 eu utilizei a propriedade innerHTML, para inserir o texto em letras maiúsculas, teria algum problema?
```js
const title = document.querySelector('h1')

title.innerHTML = title.textContent.toUpperCase()
```
exercício 02

na referência da ul, eu utilizei a tag ('ul') o restante foi igual.

No Ex. 03
```js
const liColor = document.querySelectorAll('.number')

liColor.forEach(number => {
  if (Number(number.textContent) % 2 === 0) {
    liColor.textContent = `${number.style.color = 'lightblue'}`
  } else {
    liColor.textContent = `${number.style.color = 'pink'}`
  }
})
```
- Duvida porque não podemos utilizar o Else? não lembrei o porque.
- dessa forma consegui, contudo a sua lógica o código ficou bem mais legível.

Ex 04

Eu fiz desta maneira

não sabia sobre document.body

```js
const body = document.querySelector('body')

body.setAttribute('class', 'body-background')
```

@Roger-Melo

**Comment by carlosebs** [comment]
ficou sim, obrigado Roger

Em ter, 12 de out de 2021 22:24, Roger Melo ***@***.***>
escreveu:
