### ISSUE TITLE
Etapa 07, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by Rodrigo986** [roger-melo-treinamentos/curso-de-js-roger-melo#1951]
Roger, não terminei de assistir a aula e pode ser que essa dúvida minha seja esclarecida no final, mas como eu irei dormir antes de terminar de assistir é o seguinte.
por volta dos 4:30 do vídeo, você identifica que a verificação falsy teria que prevalecer pois enquanto a condição nao fosse aceita, o paragrafo não seria criado.
Mas no meu código isso não aconteceu.
Eu tentei aqui entender a lógica do meu próprio código e não entendi pq desde quando vc já digita a primeira tecla, o paragrafo  com a classe de ajuda já é criado logo de cara.

Outra coisa é que eu tenho na minha cabeça, que o preferível é criar as variáveis fora de eventos ou de blocos de repetiçao igual escrevi no código abaixo. Acho q vamos supor, se for uma estrutura de repetição, toda vez que for repetir o loop, a variável será criada, ou em um caso de evento a mesma coisa. Só crio variaveis dentro de um bloco quando realmente percebo que é preciso usar uma lógica de escopo.
Faz sentido isso? Gostaria de saber se faz algum diferença.

```js
const input = document.querySelector(`input`)
const regex = /^[a-zA-Z]{6,}$/
const p = document.createElement(`p`)

input.addEventListener(`keyup`, event => {
  
  const username = event.target.value
  const isAValidUsername = regex.test(username)

  if (isAValidUsername) {

    p.setAttribute(`class`, `submit-success-feedback`)
    
    p.textContent = `Username válido =)`

    event.target.insertAdjacentElement(`afterend`, p)
    return
  }

  p.setAttribute(`class`, `submit-help-feedback`)
  p.textContent = `O valor deve conter no mínimo 6 caracteres,  
  com apenas letras maiúsculas e/ou minúsculas`
  event.target.insertAdjacentElement(`afterend`, p)
})

```

@Roger-Melo

**Comment by Rodrigo986** [comment]
Roger, tem algum vídeo seu que explica como q sobe arquivos pro git? 

Vou procurar aqui no google, mas se tiver algum seu em especifico pro seu curso, eu gostaria de  ver.
Segue o link dos arquivos. (imagino qeu eu fiz certo)

https://github.com/Rodrigo986/rodrigolmoRepositories/blob/main/index.html

https://github.com/Rodrigo986/rodrigolmoRepositories/blob/main/style.css

**Comment by Roger-Melo** [comment]
Show @Rodrigo986. Seu código está funcionando como o esperado.

> ### por volta dos 4:30 do vídeo, você identifica que a verificação falsy teria que prevalecer pois enquanto a condição nao fosse aceita, o paragrafo não seria criado.

Não encontrei o momento da aula em que falo que o parágrafo não seria criado.

Na real, o parágrafo de feedback do username vai ser exibido na tela tanto nos momentos em que o username for válido quanto nos momentos em que for inválido. O que vai mudar são as características dele (cor, texto, etc).

Se vc inserir um console.log dentro e fora do if, como no código abaixo,

```javascript
inputUsername.addEventListener(`input`, event => {
  // ...
  const isAValidUsername = usernameRegex.test(username)

  // ...

  if (!isAValidUsername) {
    console.log('dentro do if')
    // ...
    return
  }

  console.log('fora do if')
  // ...
})
```

ao testar esse código, à cada mudança no input, enquanto o username for inválido, o código dentro do if será executado ('dentro do if' é exibido no console). 

A partir do momento em que o username é válido, só o código fora do if é executado.

Em ambos os casos, o parágrafo deve ser exibido na tela.

Sacou a ideia?
