### ISSUE TITLE
Dúvida sobre a revisão 'RAIO X'

### ISSUE THREAD

**Issue by baronibr** [roger-melo-treinamentos/curso-de-js-roger-melo#1954]
Bom dia Roger
Estou com uma dúvida sobre a revisão 'raio x'.

Estou hoje, por exemplo, na etapa 11, atividade 15, quando você se refere `Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios` tenho que fazer todos os exercícios do começo?

Tipo estou na etapa 11, tenho que voltar refazendo todos os exercícios ou só aplicação? Porquê sempre estou voltando e começando do começo, sendo que passo praticamente o dia todo nesses exercícios, pode me explicar por favor, se está correto a forma que tô aplicando a revisão ou não, se é dessa forma em quanto tempo eu refaço os exercícios. Porque assim estou no exercício 29, imagine voltar para o número 1, olha que eu já gastei tempo voltando para 1 e refazendo tudo novamente.

1.
Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios. Como você está na primeira aplicação, comece à partir da primeira bateria. Quando você chegar na segunda aplicação, faça a revisão raio-x partindo da primeira bateria de exercício após a aplicação passada (primeira), e assim por diante.

exemplo terminei a etapa 11, volto a fazer todos os exercícios da etapa1 até o 11, chegando no 11 passa para a etapa 12?

Aguardo o contato

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @baronibr.

> ### Estou hoje, por exemplo, na etapa 11, atividade 15, quando você se refere `Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios` tenho que fazer todos os exercícios do começo?

Não necessariamente. 

Na etapa 12, vc vai chegar na 3ª aplicação do treinamento, a Weather Application. 

Antes de fazer ela, refaça apenas as baterias de exercícios da 2ª aplicação em diante. 

Quando vc chegar na 4ª aplicação, refaça as baterias de exercícios da 3ª aplicação em diante. 

Sacou a ideia?

---

É importante considerar o quão confortável vc está. Se vc perceber que está travando nos exercícios da 2ª aplicação em diante, vc precisa sentir se o problema é específicamente de um assunto que foi abordado naquele ponto do treinamento, ou se é algo que vc teve dúvidas lá atrás e essas dúvidas escalaram a ponto de vc não entender o conceito do exercício atual. É bem uma auto-avaliação mesmo. 

---

> ### sendo que passo praticamente o dia todo nesses exercícios

Essa é a ideia xD

---

E não se esqueça, sempre que tiver alguma dúvida, abra uma issue que te ajudo =)

Ficou mais claro?
