### ISSUE TITLE
Etapa 07, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#1957]
Roger, quando eu subo um arquivo para o repositorio, altero ele, salvo e tento subir ele alterado para o repositório, ele substitui o arquivo anterior. Como eu nao sei ainda esse negócio de subir arquivo para o repositório eu vou mandar o código por aqui mesmo (sinto muito)

Até os 42 mim estava tudo bem e funcionando normal conforme o código abaixo:
```js
const inputUsername = document.querySelector(`#username`)
const form = document.querySelector(`form`)
const button = document.querySelector(`.button`)
const paragraphUsernameFeedback = document.createElement(`p`)
const paragraphSubmitFeedback = document.createElement(`p`)

const usernameRegex = /^[a-zA-Z]{6,}$/


inputUsername.addEventListener(`input`, event => {

  const username = event.target.value
  const isAValidUsername = usernameRegex.test(username)

  const paragraphSubmitFeedbackExists = document.querySelector(`[data-feedback="submit-feedback"]`)

  if (paragraphSubmitFeedbackExists) {
    paragraphSubmitFeedback.remove()
  }

  if (!isAValidUsername) {

    paragraphUsernameFeedback.textContent = `O valor deve conter no mínimo 6 caracteres,  
    com apenas letras maiúsculas e/ou minúsculas`
    paragraphUsernameFeedback.setAttribute(`class`, `username-help-feedback`)
    paragraphSubmitFeedback.setAttribute(`data-feedback`, `submit-feedback`)

    event.target.insertAdjacentElement(`afterend`, paragraphUsernameFeedback)

    return
  }

  paragraphUsernameFeedback.textContent = `Username válido =)`
  paragraphUsernameFeedback.setAttribute(`class`, `username-success-feedback`)

  event.target.insertAdjacentElement(`afterend`, paragraphUsernameFeedback)

})

const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {

  previousSibiling.insertAdjacentElement(`afterend`, paragraph)

  paragraph.setAttribute(`class`, className)

  paragraph.textContent = text
}

form.addEventListener(`submit`, event => {
  event.preventDefault()

  const username = inputUsername.value
  const isAValidUsername = usernameRegex.test(username)

  if (isAValidUsername) {

    insertParagraphIntoDOM(paragraphSubmitFeedback, `Dados enviados =)`, `submit-success-feedback`, button)

    return
  }
  insertParagraphIntoDOM(paragraphSubmitFeedback, `Por favor, insira um username válido`, `submit-help-feedback`, button)

})
```

Quando eu crio o objeto para adicionar como parametro, começa a dar erro, segue o código e imagem abaixo:

```js
const inputUsername = document.querySelector(`#username`)
const form = document.querySelector(`form`)
const button = document.querySelector(`.button`)
const paragraphUsernameFeedback = document.createElement(`p`)
const paragraphSubmitFeedback = document.createElement(`p`)

const usernameRegex = /^[a-zA-Z]{6,}$/


inputUsername.addEventListener(`input`, event => {

  const username = event.target.value
  const isAValidUsername = usernameRegex.test(username)

  const paragraphSubmitFeedbackExists = document.querySelector(`[data-feedback="submit-feedback"]`)

  if (paragraphSubmitFeedbackExists) {
    paragraphSubmitFeedback.remove()
  }

  if (!isAValidUsername) {

    paragraphUsernameFeedback.textContent = `O valor deve conter no mínimo 6 caracteres,  
    com apenas letras maiúsculas e/ou minúsculas`
    paragraphUsernameFeedback.setAttribute(`class`, `username-help-feedback`)
    paragraphSubmitFeedback.setAttribute(`data-feedback`, `submit-feedback`)

    event.target.insertAdjacentElement(`afterend`, paragraphUsernameFeedback)

    return
  }

  paragraphUsernameFeedback.textContent = `Username válido =)`
  paragraphUsernameFeedback.setAttribute(`class`, `username-success-feedback`)

  event.target.insertAdjacentElement(`afterend`, paragraphUsernameFeedback)

})

const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {

  previousSibiling.insertAdjacentElement(`afterend`, paragraph)

  paragraph.setAttribute(`class`, className)

  paragraph.textContent = text
}

form.addEventListener(`submit`, event => {
  event.preventDefault()

  const username = inputUsername.value
  const isAValidUsername = usernameRegex.test(username)

  const validSubmitInfo = {
    paragraph: paragraphSubmitFeedback,
    text: `Dados enviados =)`,
    className: `submit-success-feedback`,
    previousSibiling: button
  }
  

  if (isAValidUsername) {

    insertParagraphIntoDOM(validSubmitInfo)

    return
  }

  insertParagraphIntoDOM(paragraphSubmitFeedback, `Por favor, insira um username válido`, `submit-help-feedback`, button)

})
```
Fala que o insertAdjacentElement é undefined e tem um problema na linha 65(que é a parte da funçao que insere o paragrafo no DOM) e um erro na 88 que é a invocação da funçao.
![image](https://user-images.githubusercontent.com/45271247/137453856-b9d1acdd-a566-4bc0-b87b-c174c2d4d366.png)
![image](https://user-images.githubusercontent.com/45271247/137454069-43cda735-b917-40cf-8f8f-a7e1fded0ae4.png)

Reparei que na funçao "insertParagraphIntoDOM()" está com uma ordem diferente da sua entao resolvi inverter a posição das ações dentro da função que está assim:
```js
const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {

  previousSibiling.insertAdjacentElement(`afterend`, paragraph)

  paragraph.setAttribute(`class`, className)

  paragraph.textContent = text
}
```
E mudei para ficar assim(igual no vídeo):
```js
const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {
  
  paragraph.textContent = text

  paragraph.setAttribute(`class`, className)

  previousSibiling.insertAdjacentElement(`afterend`, paragraph)

}
```
Ai o erro mudou pra linha 17 falando que "setAttribute()" não é uma função, como mostra na imagem abaixo:
![image](https://user-images.githubusercontent.com/45271247/137455143-6bc99824-ecf4-4b1a-9461-46861f405078.png)
![image](https://user-images.githubusercontent.com/45271247/137455195-1a109cb3-a608-4db7-83ba-7d07c9bd1dd4.png)

Pode ser que tenha algum erro de digitação q eu nao consegui enxergar, mas eu travei já faz um tempo nessa parte.

Segue o index e o css nos links abaixo
https://github.com/Rodrigo986/rodrigolmoRepositories/blob/main/index.html

https://github.com/Rodrigo986/rodrigolmoRepositories/blob/main/style.css

Espero que tenha entendido minha dúvida, infelizmente nao sei mostrar essas alteraçoes pelo repositório.

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Espero que tenha entendido minha dúvida, infelizmente nao sei mostrar essas alteraçoes pelo repositório.

Entendi. Como vc tb enviou os arquivos HTML e CSS na outra issue, é mais fácil testar em minha máquina e ajudar com precisão.

[Aqui](https://youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A) é um bom material para aprender github. Mas até entender git e github, vc pode subir as pastas com os arquivos pro google drive e enviar o link aqui, quando precisar =)

---

> ### Fala que o insertAdjacentElement é undefined e tem um problema na linha 65(que é a parte da funçao que insere o paragrafo no DOM) e um erro na 88 que é a invocação da funçao.

Observe que se vc exibir `previousSibiling` no console antes de executar o `insertAdjacentElement` nele, `undefined` é exibido:

```javascript
const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {
  console.log(previousSibiling) // undefined
  previousSibiling.insertAdjacentElement(`afterend`, paragraph)
  // ...
}
```

`previousSibiling` armazenar undefined é o ponto chave do problema. 

Como não existe um método `insertAdjacentElement` em `undefined`, o erro é lançado.

`previousSibiling` é o 4º parâmetro da função. Ou seja, quando a função `insertParagraphIntoDOM` é invocada, ela precisa receber um elemento do DOM como 4º argumento, certo?

Observe que se vc inserir um username inválido e enviar o form, o erro não é lançado.

Por que isso aconteceu?

Isso aconteceu pq no momento em que o form é enviado com um username inválido, a invocação da função `insertParagraphIntoDOM` recebe os 4 argumentos que ela precisa receber:

```javascript
form.addEventListener(`submit`, event => {
  event.preventDefault()

  // ...

  if (isAValidUsername) {
    // ...
  }

  // ✅ aqui a função está recebendo os 4 argumentos que ela precisa receber
  insertParagraphIntoDOM(paragraphSubmitFeedback, `Por favor, insira um username válido`, `submit-help-feedback`, button)
})
```

Só que tem tb uma invocação da função `insertParagraphIntoDOM` pra quando o username é válido. E ela está dentro do if que verifica `isAValidUsername`. E a invocação dela, ao invés de receber os 4 argumentos que ela espera, está recebendo só 1:

```javascript
form.addEventListener(`submit`, event => {
  event.preventDefault()

  // ...

  if (isAValidUsername) {
    // ❌ a função está recebendo apenas 1 argumento, quando na real, ela precisa receber 4
    insertParagraphIntoDOM(validSubmitInfo)
    return
  }

  // ...
})
```

Quando um parâmetro de uma função não recebe um valor, por baixo dos panos ele recebe `undefined`. Isso significa que (considerando a invocação do código acima), na declaração da `insertParagraphIntoDOM`, o parâmetro `paragraph` recebeu o objeto e os outros 3 parâmetros receberam `undefined`:

```javascript
const insertParagraphIntoDOM = (paragraph, text, className, previousSibiling) => {
  console.log(paragraph, text, className, previousSibiling)
  previousSibiling.insertAdjacentElement(`afterend`, paragraph)
  paragraph.setAttribute(`class`, className)
  paragraph.textContent = text
}
```

Se vc testar o código acima ao tentar enviar um username inválido, verá os seguintes valores exibidos no console:

```javascript
<p data-feedback="submit-feedback"></p> undefined undefined undefined
```

Bom, essa é a razão do problema ter acontecido. Com essas informações em mãos, vc sabe como resolvê-lo?

@Rodrigo986

**Comment by Rodrigo986** [comment]
Roger, obrigado pelo link do tutorial de github, vou começar hj mesmo.
Olha o negócio é o seguinte. Eu refiz tudo denovo e como teimoso eu coloqueia verificaçao de usuário válido como prioridade achando que o problema estava nisso, mas depois eu fui perceber(depois que vi sua resposta aqui) que como eu passei um objeto como argumento, eu teria que ter um objeto como parametro lá na criação da função (eu imaginei que voce tinha feito isso apenas para refatorar o código), mas agora oq está dando erro é a mensagem de de feedback do usuário e não do submit kkkk.
Se puder me dar umas dicas igual vc fez, sem passar a solução, pra mim seria melhor, mas se nao tiver jeito tudo bem em me passar a solução. Vou tentar fazer novamente quado eu acordar.
Segue o código com o parametro de objeto.(estou cansado e pode ser que nao vi o erro por causa disso)
```js
const form = document.querySelector(`form`)
const inputUsername = document.querySelector(`#username`)
const button = document.querySelector(`button`)

const paragraphSubmitFeedback = document.createElement(`p`)
const paragraphUsernameFeedback = document.createElement(`p`)

const regexUsername = /^[a-zA-Z]{6,}$/

paragraphSubmitFeedback.setAttribute(`data-feedback`, `submit-feedback`)


const insertParagraphIntoDOM = paragraphInfo => {
  const{paragraph, text, className, previousSibiling} = paragraphInfo
  paragraph.textContent = text
  paragraph.setAttribute(`class`, className)
  previousSibiling.insertAdjacentElement(`afterend`, paragraph)

}

inputUsername.addEventListener(`input`, event => {
  const username = inputUsername.value

  const paragraphSubmitExist = document.querySelector(`[data-feedback`, `submit-feedback]`)

  if (paragraphSubmitExist) {
    paragraphSubmitFeedback.remove()
  }

  if (regexUsername.test(username)) {

    insertParagraphIntoDOM(paragraphUsernameFeedback, `Username válido =)`, `username-success-feedback`, event.target)

    return
  }

  insertParagraphIntoDOM(paragraphUsernameFeedback, `O valor deve conter no mínimo 6 caracteres,  
  com apenas letras maiúsculas e/ou minúsculas`, `username-help-feedback`, event.target)

})

form.addEventListener(`submit`, event => {

  event.preventDefault()

  const username = inputUsername.value

  const validSubmitInfo = {

    paragraph: paragraphSubmitFeedback,
    text: `Dados enviados =)`,
    className: `submit-success-feedback`,
    previousSibiling: button

  }

  const invalidSubmitInfo = {

    paragraph: paragraphSubmitFeedback,
    text: `Por favor, insira um username válido`,
    className: `submit-help-feedback`,
    previousSibiling: button

  }

  if (regexUsername.test(username)) {

    insertParagraphIntoDOM(validSubmitInfo)

    return

  }
  insertParagraphIntoDOM(invalidSubmitInfo)

})
```

**Comment by Roger-Melo** [comment]
> ### ao inves de usar o "=" eu usei a vírgula e coloquei as aspas de forma bem maluca, e o código funcionou. kkkk

Depende do que vc quer dizer com "funcionou" xD

Observe que se vc exibir a const no console, verá que ela armazena `null`:

```javascript
  const paragraphSubmitFeedbackExists = document.querySelector(`[data-feedback`, `submit-feedback]`)
  console.log(paragraphSubmitFeedbackExists) // null
```

Quando o `querySelector` não encontra o elemento no DOM, ele retorna `null`. E nesse caso ele não encontrou o elemento pq não existe um elemento no DOM que corresponda ao seletor CSS `[data-feedback`.

Por isso é importante sempre exibir suas consts e variáveis no console para checar se elas realmente estão armazenando o valor que vc espera =)

@Rodrigo986
