### ISSUE TITLE
Etapa 7, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#1958]
professor, eu estava corrigindo a atividade passada de uma maneira não muito inteligente que foi anotar tudo passo a passo no Word e depois tentar fazer o código sozinho.
nisso eu fiz o código conforme minha anotações, porém por algum motivo meu código possui bem menos linhas e tem a mesma funcionalidade que o do senhor. 

estou revendo a aula e escrevendo o código da maneira que foi apresentada.

QUESTÃO-01
```JS
const inputUsername = document.querySelector('#username')

const p = document.createElement('p')

const usernameRegex = /^[a-zA-Z]{6,}$/

inputUsername.addEventListener('input', event => {
  const username = event.target.value
  const isAvalidUsername = usernameRegex.test(username)

  if (!isAvalidUsername) {
    p.textContent = 'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas'
    p.setAttribute('class', 'username-help-feedback')
    event.target.insertAdjacentElement('afterend', p)
    return
  }

  p.textContent = 'Username válido =)'
  p.setAttribute('class', 'username-success-feedback')
  event.target.insertAdjacentElement('afterend', p)
})
```

QUESTÃO-02
```
const form = document.querySelector('form')

const button = document.querySelector('button')

form.addEventListener('submit', event => {
  event.preventDefault()

  const inputValue = inputUsername.value

  if (usernameRegex.test(inputValue)) {
    p.textContent =  'Dados enviados =)'
    p.setAttribute('class', 'submit-success-feedback')
    button.insertAdjacentElement('afterend', p)
    return
  }

  p.textContent = 'Por favor, insira um username válido'
  p.setAttribute('class', 'submit-help-feedback')
  button.insertAdjacentElement('afterend', p)
})
```

outro problema que tive:
na questão 3 eu coloquei o mesmo código que o senhor porém nada aparece no console 
![image](https://user-images.githubusercontent.com/85198581/137552294-ca5e1de7-ad6c-4378-a721-379d4cc4aa0b.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

> ### nisso eu fiz o código conforme minha anotações, porém por algum motivo meu código possui bem menos linhas e tem a mesma funcionalidade que o do senhor. 

O código postado acima corresponde até por volta de 31 minutos da aula. A partir desse momento, eu mostro, por exemplo, como criar uma condição que remove o parágrafo abaixo do botão se ele já existir na tela. Veja a aula novamente, com calma =)

> ### na questão 3 eu coloquei o mesmo código que o senhor porém nada aparece no console 

Pode ter sido algum problema de conexão com o live server. Dentro do `index.html`, clique com o botão direito do mouse, selecione "stop live server" e depois, clique em "open with live server".

Aparentemente seu código está correto, mas poste ele por escrito na issue ao invés de print. Assim eu testo aqui em minha máquina e ajudo com mais precisão =)
