### ISSUE TITLE
Resumo da Aula 01-04 O método reduce da etapa 08

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#196]
## O método ```reduce```

- Reduz um array a um único valor, podendo ser qualquer tipo de valor.
- Pode receber 2 argumentos: callback, valorInicial
- A callback pode ter 4 parâmetros:
    - accumulator: armazena cada valor retornado pela função em cada iteração
    - item: representa o item atual que está sendo iterado
    - index: do item atual que está sendo iterado
    - array: o próprio array que está sendo iterado
- O parâmetro accumulator recebe o valorInicial na primeira iteração, enquanto que o parâmetro item recebe o segundo item do array. Caso o valorInicial seja omitido o accumulator vai armazenar o primeiro item do array, enquanto que o parâmetro item vai receber o segundo item do array.
- É uma boa prática passar o segundo argumento do reduce, pos ele indica o tipo de valor que a gente quer gerar com a redução do array.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! Continue seguindo o método. Rumo à fluência! 💪🏻
