### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#1976]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/CarlosHenrique2208/TentativaDaQuest-o19

### Maiores dificuldades durante a implementação

com certeza a maior dificuldade é a logica por detrás do JS e bem, até dois meses atrás eu mal sabia usar o "inspecionar" ou mesmo que dava para selecionar texto segurando shift e usando as setas. 
de forma direta:
  - Lembrar das funcionalidades mostradas em aula
  - Não saber aplicar corretamente certos componentes do Bootstrap no HTML, assim como ter pouca experiência com o HTML em si
  - Ter dificuldade em interpretar os textos e comandos
  -  não saber mexer direito com funções, sempre esqueço coisas básicas como parâmetro e como implementar um call-back  

### Menores dificuldades durante a implementação

  - Olhar o quiz sem ver o código e já entender a estrutura básica de divs e do form.

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

Enviei um email pra vc =)
