### ISSUE TITLE
Problema com o index da lista 13

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#1977]
![image](https://user-images.githubusercontent.com/78214862/137952107-eb2e6b24-a7c0-4191-a065-933964db3aa3.png)

Estava refazendo os exercícios e vi que falta o código deste index.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a.

Isso é intencional.

Se vc observar o exercício 01 até o 03, verá que eles começam mais ou menos assim:

```javascript
/*
01 - No index.html deste diretório (exercicio-03):
- Declare uma marcação HTML básica;
- Linke este arquivo, app.js;
- Inicie o seu servidor local e abra o console do browser.
*/
```

Ou seja, há um lembrete pra que vc suba o ambiente inicial.

A partir do 4º exercício, o esperado é que vc tenha o hábito de fazer isso sem ter que ser pedido =)

Já da bateria 14 em diante, há uma marcação HTML inicial onde é preciso ter uma marcação específica para responder os exercícios da bateria =)

Sacou a ideia?

**Comment by YureK-a** [comment]
Entendi, tinha me esquecido desse detalhe =)
