### ISSUE TITLE
Resumo da Aula While da etapa 2

### ISSUE THREAD

**Issue by kaiansamuel** [roger-melo-treinamentos/curso-de-js-roger-melo#198]
While

A expressão While cria uma rotina para verificar se o resultado da expressão é true. Se for true ele prossegue, senão ele para o a verificação do código.

while (condição) {
rotina
}

A condição verifica se a passagem pelo laço é true, se for ele prossegue , senão ele interrompe o fluxo. Depois uma rotina é executada quando a condição é verdadeira.
Exemplo:

let i = 0

while (i <= 5) {
console.log(i)
i++
}

// 0
1
2
3
4
5

É preciso notar que se não iterarmos o índice ( i ) vai gerar um loop infinito porque sempre que o loop verificar se o índice é menor do que 5 ele sempre vai mostrar no console o “i”, só que se “i” não for iterado, ele nunca será maior do que 5 , porque sempre será 0, criando assim um loop infinito.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @kaiansamuel! Rumo à fluência 🏆
