### ISSUE TITLE
Aplicação: to-do list

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#1980]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/claudiogmoreira/to-do-list.git

### Maiores dificuldades durante a implementação

Entender a lógica para construir a aplicação e manipular classes com javascript, preciso treinar mais.

### Menores dificuldades durante a implementação

Entendimento em qual método de array usar. 
obter e armazenar em uma const elementos do DOM

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
