### ISSUE TITLE
Number vs ParseInt

### ISSUE THREAD

**Issue by todd7** [roger-melo-treinamentos/curso-de-js-roger-melo#2]
Na aula 04 foi apresentado a função number, existe alguma diferença entra a conversão com parseInt ?

**Comment by Roger-Melo** [comment]
@todd7 

Oi Edson!

A função Number() tenta converter toda a string em um número.

Se tentarmos converter a string '123num', por exemplo, o valor retornado será um NaN:

```javascript
console.log(Number('123num')) // NaN
```

Mas se usarmos o parseInt() nessa mesma string, ele parseará (transformará) essa string até o 1º caractere não-dígito e retornará o valor parseado.

```javascript
console.log(parseInt('123num')) // 123
```

Só que ao usar o parseInt(), tenha em mente que ele transformará o número sempre em um inteiro, de algum tipo. E que ele pode receber um 2º argumento opcional: uma base matemática que será usada para fazer a conversão.

Por exemplo:

```javascript
console.log(parseInt('113', 10)) // 113
// Usando a base 10, o número é convertido em decimal.

console.log(parseInt('113', 8)) // 75
// Usando a base 8, o número é convertido para octal.

console.log(parseInt('113', 16)) // 275
// Usando a base 16, o número é convertido para hexadecimal.
```

Se esse 2º argumento ([base ou radix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)) não for usado, o valor passado como 1º argumento é convertido de forma implícita.

Se a string começa com 0x ou 0X, por exemplo, ela vai ser convertida para hexadecimal, e não para decimal como o esperado:

```javascript
console.log(parseInt('19')) // 19
console.log(parseInt('0x19')) // 25
```

Sobre o parseInt() sempre transformar o número em um inteiro, se inserirmos '3.35' como argumento, 3 é retornado.

```javascript
console.log(parseInt('3.35')) // 3
```

Mas se utilizarmos a função Number(), esse valor será convertido para número decimal normalmente. 

```javascript
console.log(Number('3.35')) // 3.35
```

Por que? Por que em JavaScript, todos os números são tratados como ponto flutuante (números quebrados/decimais).

Então o Number() apenas converte a string para um número, enquanto o parseInt() faz essa conversão utilizando uma base matemática (decimal, octal ou hexadecimal).

Ficou claro?

**Comment by todd7** [comment]
Opa, compreendi!!!

**Comment by Roger-Melo** [comment]
Show! Qualquer coisa é só chamar =)
