### ISSUE TITLE
exercício 2 (resultado igual com código diferente)

### ISSUE THREAD

**Issue by Bobsp2018** [roger-melo-treinamentos/curso-de-js-roger-melo#20]
Bom dia professor!

Separei alguns exercícios que meu resultado esta correto, mas a forma que escrevi o código esta um pouco diferente!
Gostaria de saber de se tem alguma coisa "errada" de como escrevi.
Obrigado!

exercício 5 -   const programmingLanguage = 'JavaScript'
                       const js = programmingLanguage
                        console.log(programmingLanguage[0],programmingLanguage[4])

exercício 6 - const mozilla = 'Mozilla Developer Network'
                     const mdn = console.log(mozilla[0],mozilla[8],mozilla[18])

no exercicio 20 eu usei backticks e funcionou

**Comment by Roger-Melo** [comment]
Oi @Bobsp2018.

Não encontrei os exercícios que você especificou.

Por exemplo, o exercício 05 corresponde a [essa](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-05/app.js) bateria de exercícios e em nenhum desses exerccícios consegui identificar similaridades com o exercício que você descreveu na issue como sendo o exercício 05.

Preciso saber exatamente de quais exercícios você está falando, para que eu compare as respostas =)

**Comment by Bobsp2018** [comment]
São os exercícios da aula 2. 
e cara... to feliz demais com esse curso! 
Muito bacana a abordagem dos exercícios!

**Comment by Roger-Melo** [comment]
Oi @Bobsp2018. Agora sim entendi.

Vi que você realmente foi um dos primeiros a se matricular nesta turma recente, parabéns pelo engajamento =D

Vamos lá.

No exercício 5, observe que com o código descrito acima, o resultado exibido no console é a string 'J S' enquanto o exercício pede que seja exibido no console a junção das letras "J" e "S". Sem o espaço em branco entre o "J" e o "S".

O espaço entre as letras exibidas no console aconteceu por que quando exibimos 2 valores como argumentos do `console.log()`, o browser renderiza um espaço em branco entre os dois valores exibidos.

Observe também que os exercícios 5 e 6 pedem que as constantes `js` e `mdn` **armazenem a junção das letras das palavras**. Lembrando que junção é sinônimo de concatenação. O propósito destes 2 exercícios é treinar suas habilidades de concatenação e acesso aos caracteres das strings =)

Observe que o exercío 20 pede para não usar template strings (backticks) e para que as aspas da string não sejam modificadas manualmente, justamente para você treinar o escape de caracteres =)

Sugiro que reveja a resolução dos exercícios e refaça-os até que esteja conseguindo fazê-los sozinho, para ter certeza de que realmente entendeu as soluções.

Vai chegar um momento em que você irá evoluir na linguagem e conseguirá propor soluções alternativas às que eu mostrar nas revisões, após entendê-las =)

No que precisar, é só chamar aqui!

**Comment by Roger-Melo** [comment]
@Bobsp2018 vou fechar a issue, mas no que precisar é só dar o toque =)
