### ISSUE TITLE
Resumo da Aula 04_02 da etapa 01

### ISSUE THREAD

**Issue by allanpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#200]
Booleans e Comparações 

Boolean representa dois valores em js (true ou false), utilizado para verificar uma condição no código 

O método includes verifica se existe ou não string ou number armazenada em uma variável ou dentro de um array. 

Operadores de Comparação

Alguns operadores são utilizados por exemplo: 
== (igual a)
!= (diferente de)

A forma ideal a ser utilizado é o operador de estritamente igual ===, pois os demais operadores (== e !==) podem variar dependendo da expressão do código fazendo a conversão de tipos. 

Para converter um tipo de dado utilizar a palavra boolean, string, number e passar o parâmetro, para visualizar qual o tipo de dado utilizar o indexof.

 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @allanpedro! Rumo à fluência! 🚀
