### ISSUE TITLE
Etapa 7 Quiz Interativo

### ISSUE THREAD

**Issue by rialic** [roger-melo-treinamentos/curso-de-js-roger-melo#201]
Fala Roger,

Segue meu projeto quiz abaixo. Nele eu dei uma apimentada e coloquei mais 2 questões ficando num total de 6 perguntas.

### Maiores dúvidas e dificuldades

- Realizar uma nova busca no DOM pelo name do input radio a partir da tag form. Eu tentava buscar todos os inputs radios com o mesmo name para pegar de forma dinâmica a resposta do usuário, tive que rever os exercícios e então lembrei que poderia selecionar da seguinte maneira **form['inputQuestion1']**
- Calcular de forma dinâmica o score de acordo com quantidade de exercícios que o formulário possui.  (Aquela apimentada no exercício)  =)
- Compreender a lógica de animação do score, pois o score era apresentado de forma repentina e o ideal é que o score cresça o contador até chegar ao resultado final do usuário.
- Utilizar de forma correta a função **Math.round** para arredondar os valores, acabei confundindo com o **Math.floor**

### Menores dificuldades

- Criação do HTML
- Utilização do forEach
- Separação do código e refatoração, mas acredito que tenha melhorias a serem feitas, porém, não identifiquei
- Utilização de array de objetos
- Selecionar elementos no DOM

[Link do  repositório quiz](https://github.com/rialic/quiz)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rhiali!

Parabéns pelo esforço em implementar a aplicação =)

A exibição dos pontos ficou legal e deu pra perceber que você entendeu bem a lógica até aqui.

A maioria das oportunidades de melhoria que vou listar abaixo não está relacionada à lógica em si, mas à organização do código. Vamos lá:

### Inputs marcados por padrão assim que a aplicação é carregada

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser exibido por padrão como "marcado". Isso é mais uma preferência pessoal.

### Nomeação de variáveis e funções

Há um princípio para nomear bem variáveis e funções. Não fique preocupado em segui-lo à risca à qualquer custo agora, por que ele será intensificado conforme você avança. Mas é bom saber: nomes de funções devem ser verbos e nomes de variáveis/constantes devem ser substantivos. Seguindo esse princípio, você começa a ter uma direção mais clara de como nomear.

Vou dar alguns exemplos práticos.

A função `quizFormEvent`, ao invés de ser nomeada como um substantivo, pode ter um nome que expressa a ação que ela executa. Como dentro dela as funções `showUserScore`, `animateScore` e `caculateScore` são invocadas, isso significa que ela desencadeia algumas ações distintas, então o nome dela, ainda que seja um verbo, poderia ser um nome mais genérico. Eu a nomearia como `handleFormSubmit` ou algo parecido.

Já a função `quizCountUserScore` pode ser chamada de `increaseUserScore` ou `setUserScore`, já que ela manipula a pontuação do usuário.

Também não há a necessidade de inserir `quiz` como prefixo dos nomes, pois essa aplicação não tem um escopo grande e tem apenas um arquivo, então é implícito que as variáveis e funções declaradas nela são do quiz.

A const `resultVal` pode ter um nome mais descritivo sobre valor que ela armazena. Eu a nomearia como `correctAnswer`. E também já aproveitaria o gancho para nomear o array com as respostas corretas como `correctAnswers` (no plural), ao invés de `quizCorrectResultList`.

### Linhas em branco

Use linhas em branco para indicar, visualmente, a separação entre conceitos, mas tome cuidado com o excesso. No código abaixo, você pode usar apenas uma linha em branco para separar a invocação do método que evita que a página seja recarregada dos demais métodos relacionados a execução de particularidades da aplicação:

```javascript
// antes
const quizFormEvent = event => {
  event.preventDefault()

  caculateScore()

  animateScore()

  showUserScore()
}

// depois
const quizFormEvent = event => {
  event.preventDefault()

  caculateScore()
  animateScore()
  showUserScore()
}
```

Seguindo esse princípio, eu removeria também as linhas em branco 17 e 28.

### `return`

```javascript
const animateScore = () => {
  // ...
  if (isZeroScore) {
      return userScore.textContent = counter;
  }
  // ...
```

No código acima, o `return` está retornando o valor no qual `userScore.textContent = counter` resulta. Se o `return` foi inserido apenas para que a função pare de ser lida naquele ponto, prefira inserí-lo na linha abaixo da atribuição. Isso deixa mais claro o motivo pelo qual ele está sendo usado.

O mesmo vale para o `return` do código abaixo.

```javascript
const timer = setInterval(() => {
  if(counter === Math.round(score)){
      return clearInterval(timer);
  }
  // ...
}, 10);
```

Ficaram claras as observações?

@rialic

**Comment by rialic** [comment]
Oi Roger,

Compreendi perfeitamente suas observações. A respeito do "return", a ideia é essa mesmo, parar a execução da função. Eu só coloquei na mesma linha das atribuições para diminuir 2 linhas do código, porém, o código não fica tão claro mesmo.

Valeu!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal @rialic! Fico no aguardo das próximas aplicações. No que precisar, é só dar o toque =)
