### ISSUE TITLE
Etapa 02, Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### ISSUE THREAD

**Issue by DanThug** [roger-melo-treinamentos/curso-de-js-roger-melo#202]
Olá Roger, a minha solução do **Exercício 01**, foi diferente e fiquei com dúvida se estaria correta também, poderia verificar por gentileza. Obrigado.
```js
const my3FavoriteTVShows = ['The Walking Dead', 'Atypical', 'Kingdom'];
const sentence = `Minhas 3 séries favoritas são: ${my3FavoriteTVShows.slice(0, 1)}, ${my3FavoriteTVShows.slice(1, 2)} e ${my3FavoriteTVShows.slice(2)}.`;
console.log(sentence);
```
No **Exercício 05**, inicialmente eu havia resolvido usando o replace('t', 'T'), porém eu me questionei se a frase tivesse menos de 39 caracteres, o Boolean resultaria em False e o replace não iria funcionar, sendo assim acabei resolvendo com esse monstrinho de código abaixo. haveria uma melhor forma de resolver? 

```js
const number = 39;
console.log(`A string que a "typeSentence" armazena tem mais de ${number} caracteres? ${String(typeSentence.length > number).slice(0, 1).toUpperCase()}${String(typeSentence.length > number).slice(1)}.`);
```

@DanThug

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Daniel.

É legal você ter me enviado as resoluções por que assim eu realmente posso saber se você entendeu o princípio por traz da resolução mostrada.

Ficou claro que você entendeu como resolver o exercício 01, mas o desafio é você usar apenas o que viu no treinamento, até aquela bateria de exercícios. Nessa bateria de exercícios, se não me engano, eu ainda não havia mostrado o método slice de array, apenas o de string =)

> No **Exercício 05**, inicialmente eu havia resolvido usando o replace('t', 'T'), porém eu me questionei se a frase tivesse menos de 39 caracteres, o Boolean resultaria em False e o replace não iria funcionar, sendo assim acabei resolvendo com esse monstrinho de código abaixo. haveria uma melhor forma de resolver?

Tentar soluções diferentes das que foram mostradas é uma forma de aprendizado super válida.

Apenas certifique-se de que você entendeu como implementar a solução da forma que mostrei (e por entender, quero dizer conseguir implementar sozinho).

Você está no começo do treinamento, ainda não é o momento de pensar na melhor forma de resolver. 

Aos poucos os exercícios vão ficando mais complexos. Vai chegar o momento em que eles vão exigir mais de você e você precisará executar o que recomendei [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) para que seu cérebro entenda de fato a forma de resolução mostrada.

Nos casos específicos que você apresentou, deu pra perceber que você entendeu a lógica por trás da forma que resolvi, então tá tudo certo =)

Respondi suas dúvidas?

@DanThug

**Comment by DanThug** [comment]
Achei que o método slice era um só rs, dúvida sanada :) . Gostaria de fazer
um pedido, poderia informar qual tema você usa no vscode. Obrigado.

Em qui., 18 de fev. de 2021 00:41, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Oi @DanThug.

Nas primeiras aulas estava usando o One Dark+ (Sublime) com o background em #15202B. Ele é instalado através de uma extensão com o nome do tema, mas acho que tiraram ela do ar. 

Por isso, você verá em aulas mais avançadas que hoje, uso o Dark+ (default dark), que é um tema padrão do VSCode =)

**Comment by DanThug** [comment]
Obrigado! Consegui instalar.

Em ter., 23 de fev. de 2021 15:00, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal @DanThug. Vou fechar a issue mas quando surgirem dúvidas, é só abrir uma nova =)

**Comment by Landowski** [comment]
@Roger-Melo

Fiz praticamente igual ao Dan, pensando no "t" e "T".

Tem horas que não sei se to saindo do "previsto" dentro do escopo das aulas ou se é a lógica de resolução que tá começando a fluir, rs.

```
const number39 = 39

console.log(`A string que a "typeSentence" armazena tem mais de ${number39}  
caracteres? ${String(typeSentence.length > number39)[0].toUpperCase()}${String(typeSentence.length > number39).slice(1)}.`)
```
