### ISSUE TITLE
Etapa 04, Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### ISSUE THREAD

**Issue by BernardoOficial** [roger-melo-treinamentos/curso-de-js-roger-melo#203]
Olá, Roger. fiz os exercícios dessa aula e queria saber se minha resolução da questão 14 está boa e no que posso melhorar?
```js
const quantidadePessoasQueCurtiram = array => {

  let pessoasQueCurtiram = array.length;

  if(pessoasQueCurtiram >= 4) pessoasQueCurtiram = 4;

  switch(pessoasQueCurtiram) {
    case 0:
      return "Ninguém curtiu isso =(";
    case 1:
      return `${array[0]} curtiu isso`;
    case 2:
      return `${array[0]} e ${array[1]} curtiram isso`;
    case 3:
      return `${array[0]}, ${array[1]} e ${array[2]} curtiram isso`;
    case 4:
      const restanteDasPessoas = array.length - 2;
      return `${array[0]}, ${array[1]} e mais ${restanteDasPessoas} pessoas curtiram isso`;
    default:
      return `Insira um valor válido como argumento`
  }
}

const pessoasQueCurtiram = quantidadePessoasQueCurtiram([
  "Ana",
  "Julia",
  "Bernardo",
]);

console.log(pessoasQueCurtiram);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Bernardo.

Você está no começo do treinamento, não se preocupe agora em pensar na melhor forma de resolver. Preocupe-se em resolver (sozinho) da forma que mostrei na resolução, seguindo [este](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) passo a passo.

A forma que eu mostro de resolver um exercício geralmente envolve princípios que serão intensificados nas próximas etapas.

O princípio da legibilidade é um deles.

Por isso, na resolução deste exercício eu substituí as ocorrências de `names[*]` por constantes.

Fique atento também ao estilo de código demonstrado nas aulas. Eu não uso `if` em linha única, muito menos com a omissão das chaves. E isso é intencional. `if` sem chaves pode causar bugs. Foi o motivo pelo qual [esse bug](https://youtu.be/arNtoWxBuXc?t=1389) crítico no SSL da Apple aconteceu há alguns anos atrás e colocou a segurança de dados em xeque. 

Tentar soluções diferentes das que foram mostradas é uma forma de aprendizado super válida.

Apenas certifique-se de que você entendeu como implementar a solução da forma que mostrei (e por entender, quero dizer conseguir implementar sozinho).

Respondi sua dúvida?

@BernardoOficial

**Comment by BernardoOficial** [comment]
Oi Roger!

Entendi sim. Muito obrigado.

**Comment by Roger-Melo** [comment]
Legal, no que precisar, é só abrir uma nova issue =)
