### ISSUE TITLE
Duvida a cerca de valores truthy e falsy

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2040]
### Etapa da aula

1

### Nome da aula

Conversão de tipos e 3 avisos - Aula 04-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751263

### Descreva a dúvida

então, durante a aula o professor disse que strings e NaN são valores falsy, quando fui testar ambos deram true. Não entendi.

![Captura de tela 2021-10-29 183642](https://user-images.githubusercontent.com/85198581/139504590-47c3d14e-f7ec-4c43-a02f-1b14d9ac4a8e.jpg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

> ### então, durante a aula o professor disse que strings e NaN são valores falsy, quando fui testar ambos deram true. Não entendi.

String ➡**vazia**⬅ é um valor falsy.

O que você testou nas linhas `6` e `9` no seu código é uma string que contém um espaço em branco. 

Observe a diferença:

```javascript
// testando uma string vazia
const isEmptyStringTruthy = Boolean('')
console.log(isEmptyStringTruthy) // false
```

```javascript
// testando uma string que contém um espaço em branco
const isSpaceTruthy = Boolean(' ')
console.log(isSpaceTruthy) // true
```

String vazia e espaço em branco são valores diferentes, ok? Cuidado com isso.

Já na linha `9`, o valor no qual a expressão `' ' + 20` resulta não é `NaN`, você pode comprovar isso exibindo o resultado da expressão no console:

```javascript
console.log(' ' + 20) // ' 20'
```

Lembra que na aula [Numbers - Aula 02-05](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/742277) eu mostrei que quando uma `string` é concatenada com `número`, por baixo dos panos, o JavaScript converte automaticamente esse número em string? 

Foi isso o que aconteceu no código acima: uma concatenação entre espaço em branco e uma string 20.

Como string ' 20' é um valor truthy, essa string convertida em boolean resulta em `true`:

```javascript
const twenthyString = ' ' + 20
console.log(twenthyString) // ' 20'

const isTwenthyStringTruthy = Boolean(twenthyString)
console.log(isTwenthyStringTruthy) // true
```

Observe que no código abaixo, agora o resultado da expressão é de fato `NaN`:

```javascript
console.log(undefined + 9) // NaN
```

Como `NaN` é um valor falsy, se vc convertê-lo em boolean, `false` é retornado:

```javascript
const aNaN = undefined + 9
console.log(aNaN) // NaN

const isNaNTruthy = Boolean(undefined + 9)
console.log(isNaNTruthy) // false
```

Sacou a ideia?

---

Ps: prefira postar o código por escrito na issue, como mostrei aos 13:22 [dessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928) =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
