### ISSUE TITLE
Aplicação: Quiz Interativo - Etapa 07

### ISSUE THREAD

**Issue by LordMan0** [roger-melo-treinamentos/curso-de-js-roger-melo#205]
Olá, Roger!
Este é o link para o quiz interativo que fiz proposto pela etapa 07:
https://github.com/LordMan0/programa-o-js/tree/main/music-quiz-main

**Maiores dificuldade**
A principal dificuldade foi recordar detalhes de como funciona e deve ser escrito funções específicas, ou resolver problemas que envolvem termos específicos (igual a situação do form['inputQuestion']). Além de ser um pouco confuso para mim como a questão da legibilidade, pois tentei modificar algumas partes do código (principalmente os códigos de condição if) usando constantes mas acabava tendo comportamentos diferentes do esperado.

**Menores dificuldades**
As menores dificuldades estavam na questão básica de programação. Apesar do HTML ter utilizado a base do quiz das aulas e o CSS ser bem simples (nessa minha versão). Na parte de programação JavaScript, ao seguir o raciocínio do que se pede e lembrando os conceitos das aulas, foi só uma questão de passo a passo para conseguir finalizar.

Obs.: Ainda tenho uma certa insegurança em relação a começar um código do zero sem orientação, pois o quiz teve, de certa forma, orientação por meio das aulas que deixaram o passo a passo mais nítido na cabeça, mas não tenho certeza de que isso possa acontecer da mesma forma por mim mesmo.

Obs. 2: Ainda sou muito novo na área de programação e existem muitos termos que ainda não sei o que significam na prática e acho que seria legal, se não for muito incômodo, se pudesse explicar em um e-mail ou se tiver algum vídeo que você já fez e puder me enviar para aprender melhor, ficaria bem agradecido. Alguns exemplos são: desenvolvedor front-end e back-end (já foi comentado no curso em alguns vídeos do seu canal no YT sobre isso, mas não entendi direito ainda), portifólio (foi recomendado criar um portifólio na Netlify, com a aplicação do quiz, mas não sei o que seria isso '^^) e outros termos que não me recordo.

Obrigado pela atenção,
Gabriel.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @LordMan0.

Passando para avisar que sua issue foi visualizada, e que a verificação dos requisitos para a análise da aplicação será feita em breve. Se estiver tudo ok, a análise será publicada aqui =)

**Comment by LordMan0** [comment]
Ok 👍

**Comment by Roger-Melo** [comment]
Olá, @LordMan0. 

O link do repositório está quebrado. Status 404, page not found.

Entrei em seu perfil e não vi repositórios. Certifique-se de que o repositório da aplicação esteja público, e não privado.

Se tiver qualquer dúvida, é só avisar =)

**Comment by LordMan0** [comment]
Pronto, acho que consegui mudar.
https://github.com/LordMan0/programa-js/tree/main/music-quiz-main
Se ainda não der para visualizar aí vou precisar de ajuda.
Meu sobrenome é Domingues Manoel. =)

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Parabéns pelo esforço em implementar a aplicação =)

Vou deixar abaixo algumas observações:

## Inputs marcados por padrão assim que a aplicação é carregada

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser exibido por padrão como "marcado". Isso é mais uma preferência pessoal.

## Organização do código

Prefira não deixar o bloco de um `if` na mesma linha da declaração dele. Mesmo que o bloco tenha apenas uma linha dentro dele, é uma convenção abrir e fechar o bloco em linhas diferentes:

```javascript
// evite
if (counter === score) { clearInterval(interval) }

// prefira
if (counter === score) {
  clearInterval(interval)
}
```

Tome cuidado com a ortografia na hora de nomear. "Ansewr" é uma palavra que não existe. Então no código abaixo, o correto seria "Answer":

```javascript
// antes
const isTheAnsewrCorrect = // ...

// depois
const isTheAnswerCorrect = // ...
```

Procure ser consistente na implementação de expressões. No código abaixo, há uma inconsistência ao inserir os operadores. 

```javascript
const inputQuestion = `inputQuestion${index+1}`

// ...

score += 25
```

Prefira inserir os espaços antes e depois dos operadores ou não inserir. Mas seja consistente nessa decisão. 

Recomendo que os operadores tenham espaço antes e depois, para que a expressão fique mais legível:

```javascript
const inputQuestion = `inputQuestion${index + 1}`

// ...

score += 25
```

`span` é um nome vago para uma const. Não é possível entender do que se trata sem antes investigar de forma mais aprofundada. Então prefira um nome mais descritivo. Como ela representa o elemento que irá conter a pontuação final, pode ser nomeada como `finalScoreContainer`, `finalScoreElement` ou algo do tipo.

Nomes de funções devem ser verbos e nomes de variáveis/constantes devem ser substantivos. Seguindo esse princípio, você começa a ter uma direção mais clara de como nomear.

`animatedFinalResult` é um substantivo. Prefira `animateFinalResult` (verbo).

Sobre as maiores dificuldades, recomendo que siga o passo a passo que recomendei na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Incluindo a revisão raio-x. Assista toda a aula para entender os marcos da jornada =)

> Obs.: Ainda tenho uma certa insegurança em relação a começar um código do zero sem orientação, pois o quiz teve, de certa forma, orientação por meio das aulas que deixaram o passo a passo mais nítido na cabeça, mas não tenho certeza de que isso possa acontecer da mesma forma por mim mesmo.

Isso é natural, mas faça a revisão raio-x. Ela vai te deixar mais afiado para as próximas etapas.

> Existem muitos termos que ainda não sei o que significam na prática...

Front-end é a parte visual de uma aplicação web, ou seja, quem trabalha com Front End é responsável por construir, por meio do código, a parte visual da aplicação web, que é o código executado no navegador.

Back-end é o que vem por trás de uma aplicação web. Quem trabalha com back-end é responsável por fazer, por meio do código, a ponte entre os dados que vão do navegador pro servidor, e do servidor pro navegador.

Isso ficará mais claro quando você chegar na etapa 15.

Sobre o Netlify, é exatamente por que você não o conhece que você precisa seguir o tutorial que deixei [neste exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-20/app.js#L68).

Se restar alguma dúvida, pode perguntar.

Conforme você for avançando no treinamento, vai perceber que uma das soft-skills importantes de um fluente em JavaScript é pesquisar primeiro e, se não entender, pedir ajuda.

Qualquer dúvida que surgir, é só abrir uma nova issue =)

Ficou claro?

@LordMan0

**Comment by LordMan0** [comment]
Ficou bastante claro tudo, professor!
Obrigado pelas correções, usarei das dicas e recomendações na próxima aplicação e ficarei mais atento aos códigos futuros.
E obrigado por responder dúvidas pessoais também. Acho que aproveitarei mais do plantão da fluência para retirar outras dúvidas desse tipo.
Rumo à fluência! 🚀

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal @LordMan0. 

No que precisar, pode contar comigo. Rumo à fluência! 👊🏻
