### ISSUE TITLE
Resumo da Aula Um overview sobre tipos de dados da etapa 01 aula 02-02

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2053]
- No JS, atualmente existem 8 tipos de dados:
	- Number – números;
	- String – cadeia de caracteres;
	- Boolean – lógica de verificação de valores verdadeiros ou falsos;
	- Null – modo de dizer que uma variável não tem valor;
	- Undefined – valor não “setado”, inserido automaticamente pelo JS;
	- Object – estrutura de dados que pode armazenar propriedades diferentes;
	- Symbol – nova edição do JS, relacionada a objetos;
	- BigInt – usado para manipular números muito grandes.

- Em JS, não é necessário informar o tipo da variável, pois a linguagem possui tipagem dinâmica.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery! Rumo à fluência 🙌🏻
