### ISSUE TITLE
Resumo de um overview sobre tipos de dados na Aula 02-02 da etapa 01

### ISSUE THREAD

**Issue by apoklpz** [roger-melo-treinamentos/curso-de-js-roger-melo#2054]
Number: 1, 2, 3, 100, 3.4
String:  'Hello, world' "oi@rogermelo.com.br" 
Boolean: true / false
Null: Uma variável que não tem valor.
Undefined: representa um valor não-setado.
Object: São estruturas de dados complexas (Array, Datas, Literais, etc.)
Symbol: Utilizado com objetos.
BigInt: Utilizado para manipular números muitos grandes.

Pontos Importantes em tipos de dados em JAVASCRIPT:
1-Uma variável pode armazenar qualquer tipo de dados.
2-Em Javascript não é necessário dizer de forma explicita qual o tipo de dado que uma variável esta armazenando, porque JAVASCRIPT é uma linguagem de tipagem DINÂMICA.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @apoklpz! Rumo à fluência 🙌🏻
