### ISSUE TITLE
Aplicação: Quiz Interativo - Etapa 7

### ISSUE THREAD

**Issue by CaioFFerreira** [roger-melo-treinamentos/curso-de-js-roger-melo#206]
Link do repositório:  https://github.com/CaioFFerreira/quiz-roger-melo .
Link Site: https://quizrogermelo.netlify.app/ .

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
   Acredito que minha maior dificuldade foi na parte de refatorar o código, ainda sinto que poderia ter melhorado mais. 
- Quais foram as suas menores dificuldades durante a execução desse exercício.
  Minhas menores dificuldades são com HTML e CSS ( Bootstrap ) durante a aplicação que  foi bem tranquila.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @CaioFFerreira.

Passando para avisar que sua issue foi visualizada, e que a verificação dos requisitos para a análise da aplicação será feita em breve. Se estiver tudo ok, a análise será publicada aqui =)

**Comment by Roger-Melo** [comment]
Oi Caio!

Parabéns pelo esforço em implementar a aplicação =)

Vi que você implementou uma funcionalidade à mais, o countdown. Isso é bom, mas tome cuidado para não improvisar antes de consolidar o básico.

Foi na implementação do countdown que identifiquei pontos de atenção que você precisará ajustar em relação à lógica vista até aqui.

`location.reload()` não foi mostrado no treinamento, então qualquer ação desse método na aplicação não será avaliada. O desafio é construir as aplicações usando o que foi mostrado no CJRM.

Vou deixar abaixo os ajustes que eu recomendo que você priorize.

## Organização do código

### Nomeação de variáveis, parâmetros e funções

Algumas variáveis estão com nomes vagos. Não é possível entender do que se trata `quiz` e `time` sem antes investigar de forma mais aprofundada. Esses nomes precisam ser mais descritivos. 

Como `quiz` é um elemento que contém o quiz, pode ser renomeada como `quizContainer`. 

Como `time` armazena o span que exibe o countdown, pode ser renomeado como `countdownContainer`.

Tome cuidado com a ortografia na hora de nomear. "Anwes", "Anwers" e "Anwer" são palavras que não existem.

Nomes de funções devem ser verbos e nomes de variáveis/constantes devem ser substantivos. Seguindo esse princípio, você começa a ter uma direção mais clara de como nomear. 

`answersMatch` é um substantivo. Prefira `matchAnswers` (verbo).

`lastScore` é uma função que exibe os pontos, então pode se chamar `showScore` ou `showUserScore`.

`timerAnwes` é um nome vago para uma função que exibe algo na tela. Prefira `showAlertWhenTimeIsOver` ou um nome similar.

Não faz sentido declarar uma função que tem um parâmetro com o mesmo nome dela.

```javascript
const lastScore = (classAlert, lastScore) => {
  // ...
}
```

Até por que `score` é uma `let` global (assunto mostrado [nessa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/842111) aula). Isso significa que ela pode ser acessada dentro da `lastScore` e o parâmetro `lastScore` pode ser eliminado.

## Lógica

`answersMatch` é executada para cada item do array userAnwers.

A cada execução dela, `lastScore` e `clearInterval` estão sendo executadas(os). 

Não faz sentido `lastScore` ser invocada à cada iteração do forEach. Se eu acertar as 3 primeiras alternativas e errar a última, a classe alert-danger é inserida na div do alert, por que à cada iteração, um innerHTML desnecessário está sendo executado.

`lastScore` só precisa ser executada uma vez para exibir os pontos depois que o cálculo deles foi feito.

O `clearInterval` não precisa ser invocado à cada iteração do forEach. Ele pode ser executado uma única vez após o form ser enviado.

A única ação que precisa acontecer no callback do forEach é aumentar a pontuação a cada resposta certa. 

Não insira atribuições onde (do ponto de vista de legibilidade e estilo de código) elas não são esperadas. 

```javascript
lastScore('alert-success', score += 25)

let timer = time.textContent = countdown--
```

Os trechos de código acima não lançam um erro, pois atribuições resultam em um valor. Porém, são um anti-pattern. 

O que faz sentido no primeiro trecho é apenas referenciar a `score` como argumento após modificar o valor dela e no segundo trecho, executar primeiro a atribuição do decremento do countdown pro h6 e depois usar o if para checar o countdown. Se necessário, use pré-incremento ao invés de pós.

Como eu disse anteriormente, priorize estes ajustes. 

Você listou refatoração como a maior dificuldade durante a execução do exercício, mas não é o que percebi ao analisar o código. Primeiro, consolide a base. Refatoração vem depois. 

É a primeira issue que você abre no repositório do treinamento. Recomendo que pergunte mais, que abra mais issues (não acredito que até aqui você não teve dúvidas). Quanto mais rápido você tirar dúvidas, menos elas irão escalar.

Lembre-se também dos marcos da Jornada à fluência que mencionei na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Um deles é executar a revisão raio-x antes de começar a construir qualquer aplicação do treinamento.

Ficaram claros os ajustes acima?

@CaioFFerreira

**Comment by CaioFFerreira** [comment]
Boa noite Professor, Obrigado pelo FeedBack vou corrigir esses pontos colocados . @Roger-Melo

**Comment by Roger-Melo** [comment]
Legal Caio. Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova =)
