### ISSUE TITLE
Resumo da Aula Tratando erros com try/catch - Aula 06-04 da etapa 11

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2064]
Quando um erro é lançado em uma aplicação JavaScript, todo o código abaixo desse erro não é executado. Quando houver uma possibilidade, dentro do código, de que um erro seja lançado, esse trecho de código poderá ser tratado com o uso da cláusula try/catch. Esse recurso faz com que a aplicação não trave, tratando o erro lançado e podendo fazer algo com esse erro, como criar um log por exemplo. Dentro do bloco try inserimos o código que é passível de ter um erro lançado. Dentro do bloco catch inserimos o código que queremos que seja executado caso um erro seja lançado. O catch recebe um parâmetro, que é um objeto error, em que temos as propriedades name e message, que podem ser utilizadas. Vamos ver na prática uma simples utilização do try/catch com algum código depois deste bloco, para comprovar que a aplicação continuou até o fim do código independente do erro ter sido lançado.

```jsx
try {
	console.log(hello); // tentando logar uma variável não inicializada
} catch (error) {
	console.log(error.name, error.message)
}

console.log('finalizando a aplicação');
```

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas! Rumo à fluência 🙌🏻
