### ISSUE TITLE
Resumo sobre String da Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by apoklpz** [roger-melo-treinamentos/curso-de-js-roger-melo#2078]
// strings: é um encadeamento de caracteres envolvidos entre aspas seja letras ou números.
---
console.log('hello, world')

const email = 'leon@rogermelo.com.br'

console.log(email)
---

// concatenação de strings
---
const firstName = 'Nathan'
const lastName = 'Drake'
const fullName = firstName + ' ' + lastName

console.log(fullName) //Mostra a concatenação das strings
---

// acessando caracteres
---
console.log(fullName[2]) //Mostra o caracter na posição
---
// comprimento de uma string
---
console.log(fullName.length) //Mostra o tamanho da string
---
// métodos de strings
---
console.log(fullName.toUpperCase()) //Mostrar toda a string Maiúscula

const result = fullName.toLowerCase() //Mostrar toda a string Minúscula

console.log(result, fullName) //Método não modifica a string original.

const index = email.indexOf('@') //Mostrar numero da posição do caracter na string
console.log(index)
---
@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @apoklpz! Rumo à fluência 🔥
