### ISSUE TITLE
Aplicação: Quiz 1º Upload

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2079]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/carlosdevjs/uploadQuiz.git

### Maiores dificuldades durante a implementação

- Começar foi o grande problema em relação ao array das respostas certas;
- HTML e CSS ainda aprendendo;
- Na hora de utilizar o forEach dentro do evento;
- Duvida de como mostrar o resultado; tentei criar um popup (não consegui)

### Menores dificuldades durante a implementação

- Criar os eventos;
- Jogar a respostas na página; Utilizei duas formas (uma está comentada).
- Utilizar o Bootstrap;

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Duvida de como mostrar o resultado; tentei criar um popup (não consegui)

É basicamente a mesma pegada do que foi mostrado [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890854).

Vc tem o código da tentativa do popup? Se tiver, manda que te ajudo =)

Mesmo com as outras dificuldades que você listou, pelo que vi, vc fez a aplicação funcionar como o esperado.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou alternativas marcadas por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

O fato de você ter conseguido fazer duas formas de exibição da pontuação é um indício que entendeu bem como inserir elementos no DOM.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

De um ponto de vista de usabilidade, seria interessante deixar claro o total de perguntas que o quiz tem. 

Pode ser uma mensagem tipo "Você acertou 3 de 5 perguntas". Isso é bom para o usuário, pq traz clareza do progresso dele no quiz.

## Organização de código

### Nomes de variáveis e funções

Como eu disse ali em cima, no geral, você nomeou bem suas variáveis. 

O que vou mostrar à seguir tem o intuito de te deixar mais ligado à uma parada nas próximas aplicações.

Nessa aplicação (quiz), como há apenas um `button` e um `h1`, é ok as variáveis serem nomeadas como `button` e `h1`.

Porém, nas próximas aplicações, pode haver dois elementos importantes na aplicação que possuem a mesma tag. 

Então no caso de haver 2 `button`s, por exemplo, você teria que ser mais específico ao nomear cada um. 

Se na mesma aplicação há um button que ao ser clicado executa uma pesquisa de palavras e um outro button que ao ser clicado executa a adição de uma palavra, o ideal é que eles sejam nomeados como `buttonSearchWords` e `buttonAddWord`, ou algo do tipo. 

Sacou a ideia?

Além disso, um princípio que gosto de seguir ao nomear e que acredito que pode te ajudar no futuro é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by carlosdevjs** [comment]
Boa noite Roger, meu grande professor, gosto da sua atenção plena em nosso crescimento como aluno.
Por isso devo ser sincero com vc, eu na verdade eu só consegui fazer o quiz, depois que vi vc começar, então foi clareando as ideias, mais eu errei mais do que acertei, depois de várias tentativas consegui fazer desta forma, ainda estou tentando refatorar o código, para melhorar a legibilidade, todavia eu também demoro a ter ideias com os nomes, mesmo sabendo da regra de ouro, funções são verbos relacionados a ações e as variáveis substantivos. A sacada do html, peguei todo da aula, eu ainda sou uma negação em colocar as tag em seu devidos lugares. Rumo a fluência eu vou chegar se Deus quiser e se eu continuar me esforçando. Todos estes conselhos seguirei a risca.

**Comment by Roger-Melo** [comment]
Obrigado pela sinceridade, @carlosdevjs 🙏🏻.

Neste caso, não recomendo que vc se preocupe com refatoração. Refatoração vem depois.

A minha recomendação é que vc revise como fazer e faça totalmente sozinho. Mesmo que para isso acontecer, vc precise repetir muitas vezes.

Se sentir que é necessário, faça uma [Revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1985).

Eu poderia deixar isso passar, mas se eu fizesse essa recomendação agora, você ficaria com dificuldades para progredir nos próximos desafios (a dificuldade vai aumentando aos poucos), e isso poderia te deixar desmotivado.

**Comment by carlosdevjs** [comment]
@Roger-Melo, estou realizando a criação do quiz já sozinho, de tempos em tempos vou revisando, vou começar uma revisão raio-x, para dar mais umas clarezas.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)

**Comment by carlosdevjs** [comment]
Olá @Roger-Melo, terminei a revisão raio-x, e consegui implementar o quiz sem olhar, inclusive consegui rodar o popup com o resultado, quando puder veja se tem algo a melhorar, acredito que seja a refatoração eu carreguei os arquivos antes de realizar. Rumo a fluência. =) minha dopamina está no auge hj. kkkk

**Comment by Roger-Melo** [comment]
Legal @carlosdevjs =)

Prefira comentar em issues abertas. Ao postar comentários em issues fechadas, vc corre um grande risco do seu comentário não ser visualizado e ficar sem resposta, ok?

Sua aplicação foi recebida lá na outra issue e, em breve, vc receberá análise dela.

**Comment by carlosdevjs** [comment]
Foi descuido meu, na verdade eu pensei que não podia postar novamente a
mesma aplicação abrindo outra issues.
Agora uma pergunta fora do rumo, meu caro mentor onde vc fez o seu inglês,
estou tentando colocar em prática junto com a leitura em savoring.
Estou em uma fase bem (digamos que seja uma provação), trabalhei
corretamente na Segov do RJ, durante 11 anos em um projeto com cargo
comissionado, peguei um PM fazendo mutreta e tive que relatar para o meu
coordenador. Aí fui exonerado, sendo que já tinha relatado ao pessoal do
alto escalão do Palácio Guanabara. Conclusão (corrupção tomando conta de
tudo), nem me pagaram esses anos que eu fiquei,  ainda estou procurando
trabalho, ninguém chama, mulher pressionando, mãe preocupada. Sinistro meu
mentor, estou apenas desabafando, pois eles não compreendem que eu estou
estudando para mudar as coisas. Pensam que é um hobby meu. Pedindo força a
Deus para continuar.
Estou pensando até em estudar para concurso.

Me desculpe amigo

Abraços @Roger Melo ***@***.***>

Em sáb., 20 de nov. de 2021 às 09:22, Roger Melo ***@***.***>
escreveu:
