### ISSUE TITLE
Mentoria

### ISSUE THREAD

**Issue by developerJSJ** [roger-melo-treinamentos/curso-de-js-roger-melo#2084]
### Etapa da aula

5

### Nome da aula

DOM

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928

### Descreva a dúvida

Oi, tudo bem? Por favor, sou deficiente visual e estou com muitas dúvidas.
E algumas complicações sobre acessibilidade.

Segue as dúvidas:

1- Como faço para ter a mentoria indivual(se é isso) pelo instagram?

2- Por que não respondem aos e-mails?

3-Estou com dúvida em relação ao DOM.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @developerJSJ!

> ### 1- Como faço para ter a mentoria indivual(se é isso) pelo instagram?

A mentoria que tenho hoje é o plantão da fluência. 

Você chegou a assistir a aula inaugural? Nela, eu falei sobre o plantão =)

> ### 2- Por que não respondem aos e-mails?

Eu enviei um email pra vc há 45 minutos atrás =)

Sempre estou atento aos pedidos de ajudas dos alunos, não se preocupe.

> ### 3-Estou com dúvida em relação ao DOM.

Preciso de mais informações. 

Qual é a sus dúvida?

Quanto mais específico você for, mais fácil será ajudá-lo =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
