### ISSUE TITLE
Erro de CORS

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2085]
### Etapa da aula

12

### Nome da aula

Obtendo informações da cidade - Aula 01-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1408269

### Descreva a dúvida

Roger, boa tarde! 

Não consigo fazer a requisição para a API do Weather porque dá erro de CORS conforme print abaixo. Já tentei baixar uma extensãp do chrome mas não resolveu. Não consigo progredir por conta deste erro. Consegue me instruir o que fazer para corrigir este erro e conseguir prosseguir?!

![image](https://user-images.githubusercontent.com/80974656/139700914-1f0db9e5-a64d-4931-8d1d-1975f5c5cc00.png)

@Roger-Melo

**Comment by JuFML** [comment]
Pode desconisderar Roger, Consegui resolver excluindo a key e criando outra.

Obrigada!

**Comment by Roger-Melo** [comment]
Isso aí. No que precisar, é só abrir uma nova issue =)
