### ISSUE TITLE
Resumo da Aula Try/catch em requests e erros personalizados - Aula 06-05 da etapa 11

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2088]
Podemos tratar erros em funções assíncronas com o uso do *try/catch*, podendo utilizar respostas personalizadas para o erro. Como sabemos, quando utilizamos o `fetch()` para buscar dados em um *endpoint*, mesmo que este *endpoint* esteja incorreto, a *promise* é resolvida e tratada no método `then()`, com o `catch()` sendo utilizado apenas quando não há conexão. Então caso tenhamos um *endpoint* incorreto, podemos tratar esse erro verificando seu `status` que será 404 ou se a propriedade `ok` será false. Então podemos primeiro verificar a falha, e caso a mesma exista lançamos um erro, e este erro será tratado no `catch()`. Vamos ver na prática como ficaria:

```jsx
const getUsers = async () => {
	try {
		const response = await fetch('https://jsonplaceholder.typicode.com/userss');
	
		if (!response.ok) {
			throw new Error('Não foi possível obter os dados da API');
		}
	
		return response.json();
	} catch(error) {
		console.log(error.name, error.message);
	}
}

const logUsers = async () => {
	const users = await getUsers();
	console.log(users);
}

logUsers();
```

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência 🔥
