### ISSUE TITLE
Resumo da Aula 01- 02, 01-03, 01-04, 01-05  da etapa 03

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#209]
![WhatsApp Image 2021-02-18 at 19 36 49](https://user-images.githubusercontent.com/49795140/108431196-54600c00-7221-11eb-9a2a-e1814a9c8c61.jpeg)
![WhatsApp Image 2021-02-18 at 19 37 09](https://user-images.githubusercontent.com/49795140/108431202-57f39300-7221-11eb-93a2-a8313cc1406b.jpeg)
![WhatsApp Image 2021-02-18 at 19 39 13](https://user-images.githubusercontent.com/49795140/108431220-59bd5680-7221-11eb-96cd-2814b3280e97.jpeg)
![WhatsApp Image 2021-02-18 at 19 40 44](https://user-images.githubusercontent.com/49795140/108431239-5b871a00-7221-11eb-8bba-0f17f99e2f54.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @azulinho10! Rumo à fluência 👊🏻
