### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2093]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuFML/weather-aplication

### Maiores dificuldades durante a implementação

- Sincronizar a lógica de duas requisições.

Obs.: Depois que eu subi o código para o Netlify o fetch começou a dar erro. A aplicação funciona fora do Netlify. Outro ponto é que o IsDayTime está sempre vindo como false então a imagem não está mudando para dia.

### Menores dificuldades durante a implementação

- Manipulação do DOM;
- Fazer o Fetch
- Colocar cada função com uma única responsabilidade

**Comment by Roger-Melo** [comment]
Olá @JuFML.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuFML!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ### Sincronizar a lógica de duas requisições.

Mesmo com as dificuldades, vc conseguiu =)

Tem só um pequeno ajuste que vou comentar ali em baixo.

> ### Obs.: Depois que eu subi o código para o Netlify o fetch começou a dar erro. A aplicação funciona fora do Netlify. 

Pode mandar um print para eu ver o que a mensagem de erro está dizendo?

> ### Outro ponto é que o IsDayTime está sempre vindo como false então a imagem não está mudando para dia.

Mais cedo quando testei, rolou isso mesmo. Agora, parece ter normalizado. Talvez tenha sido algo com a API.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Organização de código

### Nomes de variáveis e funções

Não é recomendável ter `temperature` e `Temperature` (com "T" maiúsculo) no código.

São variáveis com praticamente o mesmo nome e não fica explícito qual é a diferença entre as duas.

Além disso, o objeto que a API retorna tem propriedades com letra inicial maiúscula (Pascal case). Então pra manter o padrão, eu eliminaria a `temperature` com "t" minúsculo.

Ficaria assim:

```javascript
const getCityAndWeatherData = async event => {
  // ...
  const { WeatherText, Temperature, IsDayTime } = await getCityWeather(Key)

  showCityAndWeatherData(LocalizedName, WeatherText, Temperature, IsDayTime)
}
```

E dentro da `showCityAndWeatherData` vc pode fazer a `textContent` receber o valor da propriedade:

```javascript
const showCityAndWeatherData = (LocalizedName, WeatherText, Temperature, IsDayTime) => {
  // ...
  cityTemperature.textContent = Temperature.Metric.UnitType
  // ...
}
```

---

17 graus está sendo exibido para todas as cidades. Isso está acontecendo pq `Temperature.Metric.UnitType` foi usada, quando na verdade o valor dos graus está armazenado na propriedade `.Value`. 

Então ficaria `Temperature.Metric.Value`:

```javascript
cityTemperature.textContent = Temperature.Metric.Value
```

## Lógica

No código abaixo, `getCityData` está sendo invocada 2x:

```javascript
const getCityAndWeatherData = async event => {
  // ...
  // invocação 1️⃣
  const { Key, LocalizedName } = await getCityData(inputValue)
  const { WeatherText, Temperature, IsDayTime } = await getCityWeather(Key)
  // a invocação de getCityWeather acima executa getCityData novamente, como mostrado no código abaixo 👇🏻
}
```

```javascript
const getCityWeather = async (cityKey) => {
  try {
    // invocação 2️⃣
    const { Key, LocalizedName } = await getCityData(cityKey)
    // ...
  }
  // ...
}
```

Fazendo algumas pequenas mudanças, é possível fazer com que `getCityData` seja invocada apenas uma vez. Olha só...

Vc pode eliminar a invocação da `getCityData` dentro da `getCityAndWeatherData` e inserir o nome da cidade (`inputValue`) como argumento da invocação de `getCityWeather`:

```javascript
const getCityAndWeatherData = async event => {
  const inputValue = event.target.city.value
  const { LocalizedName, WeatherText, Temperature, IsDayTime } = await getCityWeather(inputValue)

  showCityAndWeatherData(LocalizedName, WeatherText, Temperature, IsDayTime)
}
```

Feito isso, dentro da `getCityWeather`, ao invés de retornar o objeto `cityWeather`, vc pode fazer um destructuring e retornar um novo objeto com apenas as propriedades que vc precisa (incluindo `LocalizedName`):

```javascript
const getCityWeather = async (city) => {
  try {
    const { Key, LocalizedName } = await getCityData(city)
    const urlCityWeather = `http://dataservice.accuweather.com/currentconditions/v1/${Key}?apikey=${APIKey}&language=pt-br`
    const response = await fetch(urlCityWeather)
    // 🧱 destructuring
    const [{ WeatherText, Temperature, IsDayTime }] = await response.json()

    // ↪ novo objeto retornado
    return { LocalizedName, WeatherText, Temperature, IsDayTime }
  }
  // ...
}
```

Assim, vc tem o mesmo resultado e economiza uma requisição pra API =)

---

Geralmente, ternários não são usados para executar efeitos colaterais.

Relembrando: um efeito colateral é qualquer mudança de estado, que pode ser percebida do lado de fora da função, e que não é um valor retornado pela função.

Exemplos:

- Modificar alguma variável ou propriedade de objeto que tá do lado de fora da função;
- Logar no console;
- Manipular o DOM;
- Desencadear qualquer processo do lado de fora da função;
- Invocar outra função que produz efeito colateral.

O ideal é usar ternários para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar a atribuição de `src` da `weatherImg` (em que o valor no qual a expressão `weatherImg.src = '...'` resulta não está sendo aproveitado), vc pode usar o ternário apenas para setar a string que `src` irá receber:

```javascript
// antes
IsDayTime ? weatherImg.src = './src/img/day.svg' : weatherImg.src = './src/img/night.svg'
```

```javascript
// depois
weatherImg.src = IsDayTime ? './src/img/day.svg' : './src/img/night.svg'
```

---

Assim como o ternário, o ideal é que expressões que envolvam `&&` ou `||` também não executem efeitos colaterais.

```javascript
const hideWeatherInfoContainer = () => {
  return weatherInfoContainer.classList.contains('d-none') && weatherInfoContainer.classList.remove('d-none')
}
```

No código acima, o resultado da expressão após o `return` não está sendo usado em outro lugar da aplicação.

Então nesse caso, eu preferiria executar a manipulação do DOM usando um `if`:

```javascript
const hideWeatherInfoContainer = () => {
  if (weatherInfoContainer.classList.contains('d-none')) {
    weatherInfoContainer.classList.remove('d-none')
  }
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
