### ISSUE TITLE
Challenge 16.

### ISSUE THREAD

**Issue by lucas-giraldelli** [roger-melo-treinamentos/curso-de-js-roger-melo#21]
Bom dia, notei que o desafio 16 já vem com uma resposta, no caso a primeira questão, é intencional?

**Comment by lucas-giraldelli** [comment]
Entendi agora, é para que não seja exibida, obrigado!

**Comment by Roger-Melo** [comment]
@lucas-giraldelli isso mesmo.

Qualquer dúvida é só chamar =)
