### ISSUE TITLE
Resumo da Aula 03-02, 03-03, 03-04 da etapa 2

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#210]
/*-------------------------------------------------------------------------------------------------
Aula 03-02
-------------------------------------------------------------------------------------------------*/

/*

Operador Not (!)

*/

//-------------------------------------------------------------------------------------------------

/*let isUSerLeggedIn = false 

if (!isUSerLeggedIn) {
    console.log('Você precisa fazer login para continuar!')
}

console.log(!true)
console.log(!false)*/

/* Quando utilizamos o operador !, temos o intuito de inverter a resposta dada pelo console à afirmação.
Por exemplo, ao invés do console exibir "true" no primeio console.log, ele exibiu false, pois lemos esta
expressão como "not true", se é "not true". é false.*/

//-------------------------------------------------------------------------------------------------

/*-------------------------------------------------------------------------------------------------
Aula 03-03
-------------------------------------------------------------------------------------------------*/

/* 

Break e COntinue.

*/

//-------------------------------------------------------------------------------------------------

/*
const scores = [50, 25, 0, 30, 100, 20, 10]

for (let i = 0; i < scores.length; i++) {
    const worstPoint = scores[i] === 0
    if (worstPoint) {
        continue
    }

    console.log(`sua pontuação: ${scores[i]}`)
    const bestPoint = scores[i] === 100
    

    if (bestPoint) {
        console.log('parabés você atingiu a pontuação máxima')

        break
}
}
*/

/* Quando usamos o continue, o console entendeu que queríamos que ele não exibisse o resultado "0"
no nosso loop. No caso do break, ele entendeu que queríamos parar o loop alí mesmo, na pontuação
máxima.*/

//-------------------------------------------------------------------------------------------------

/*-------------------------------------------------------------------------------------------------
Aula 03-04
-------------------------------------------------------------------------------------------------*/

/*

Condicional switch 

*/

/*const grade = 'B'

switch (grade) {
    case 'A' :
        console.log('Você tirou um A')
    case 'B':
        console.log('você tirou um B')
        break
    case 'C':
        console.log('você tirou um C')
        break
    case 'D':
        console.log('você tirou um D')
        break
    case 'E':
        console.log('você tirou um E')
        break
    default:
        console.log('nota inválida')

}*/

/* Anteriormente, usamos IF e ELSE IF para verificar várias condições.
Entretanto, por conta do alto esforço mental e visual gerado, o comando switch foi empregado.
Ele nada mais é do que uma simplicação dos if e else if, verificando cada condição e exibindo apenas
a condição que é atendida, desde que façamos uso do continue e do break.*/

@Roger-Melo

**Comment by Roger-Melo** [comment]
Parte pra cima @YureK-a! Rumo à fluência 🥇
