### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#2100]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/claudiogmoreira/to-do-list.git

### Maiores dificuldades durante a implementação

Entender a lógica para construir a aplicação e manipular 
classes com javascript, preciso treinar mais.

### Menores dificuldades durante a implementação

Entendimento em qual método de array usar.
obter e armazenar em uma const elementos do DOM

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Entender a lógica para construir a aplicação e manipular classes com javascript, preciso treinar mais.

Vc ainda treinará bastante manipulação de classes CSS durante o treinamento =)

Em quais partes vc teve mais dificuldade com a lógica?

---

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Na filtragem dos to-dos, é importante indentar os encadeamentos dos métodos `filter` e `forEach`, para que fique claro onde começa a invocação de um e de outro. Vc fez isso muito bem.

No geral, os nomes que vc deu às suas variáveis estão específicos e claros.

## Lógica

Cuidado ao omitir blocos de ifs. 

[Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos e colocou a segurança de dados em xeque por causa desse tipo de decisão.

## Organização de código

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco 4 a 7.

### Legibilidade

Indente bem template strings com marcação HTML. 

Boa indentação é um dos critérios para um código legível. 

```javascript
// antes
`<li class="list-group-item d-flex justify-content-between align-items-center">
<span>${inputValue}</span>
<i class="far fa-trash-alt delete"></i>
</li>`
```

```javascript
// depois
`<li class="list-group-item d-flex justify-content-between align-items-center">
  <span>${inputValue}</span>
  <i class="far fa-trash-alt delete"></i>
</li>`
```

---

Ao usar uma expressão extensa como condição de um `if`, prefira armazenar a expressão em uma variável que descreva o valor armazenado ou o que o valor significa naquele momento.

Isso dá mais legibilidade e velocidade de leitura ao código.

```javascript
// antes
if (Array.from(clickedElement.classList).includes('delete')) {
  clickedElement.parentElement.remove()
}
```

```javascript
// depois
if (shouldRemoveTodo) {
  clickedElement.parentElement.remove()
}
```

### Nomes de funções

Experimente treinar um dos maiores desafios em programação: nomear bem. 

Nomeie as funções de callback dos event listeners.

Se sentir achar necessário, relembre [o princípio de nomeação](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1882#issuecomment-929192918) que mencionei na análise passada.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
