### ISSUE TITLE
Funções com responsabilidade única

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2104]
### Etapa da aula

11

### Nome da aula

Exercícios da aula 06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1378497

### Descreva a dúvida

Roger, hoje tive uma dúvida com relação a responsabilidade única por função ao concluir o exercício "**Testando a API do GIPHY**". Neste exercício eu criei duas funções, onde uma faz o fetch na API pelo termo pesquisado, e uma outra que renderiza o GIF na tela. 
Só para contextualizar, a `fetchGiphy()` faz o fetch e retorna uma resposta. Já a `renderGif()` invoca a `fetchGiphy()` e com o seu resultado, renderiza algo na tela. Só que antes de, de fato renderizar o GIF na tela, eu crio um elemento de iframe e ao final eu limpo o input. Isso me trouxe uma sensação de que a minha função está fazendo mais do que deveria. Essa criação do iframe e reset do input me pareceram "sobrar" na minha função, apesar de necessárias.
Nesse caso eu deveria criar uma função externa que criasse um iframe de acordo com os argumentos passados, e eu apenas invocaria essa função dentro da minha `renderGif()`? E sobre a limpeza do input, eu deveria criar uma função externa e apenas invocá-lo? Ou por se tratarem de passos necessários não há problema em permanecerem na minha função `renderGif()`?

Seguem abaixo as duas funções:

**fetchGiphy()**
```js
const fetchGiphy = async (gif) => {
  try {
    const urlAPI = `https://api.giphy.com/v1/gifs/search?api_key=${apiKey}&limit=1&q=${gif}`;

    const response = await fetch(urlAPI);

    const { data } = await response.json();

    if (data.length === 0) {
      throw new Error("Não foi possível obter um GIF com o termo pesquisado");
    }

    const { embed_url, images: { original: { height, width }, }, } = data[0];

    return { embed_url, height, width };
  } catch (error) {
    console.log(error.name, error.message);

    return gifNotFound; // é uma constante que criei fora dessa função que retorna um objeto com um gif 404
  }
};
```

**renderGif()**

```js
const renderGif = async (event) => {
  event.preventDefault();

  const searchedTerm = event.target.search.value.trim();

  const { embed_url, height, width } = await fetchGiphy(searchedTerm);

  const createGifIframe = (url, height, width) => {
    const iframe = document.createElement("iframe");
    iframe.src = url;
    iframe.height = height;
    iframe.width = width;
    iframe.setAttribute("frameborder", "no");

    return iframe;
  };

  const gifIframe = createGifIframe(embed_url, height, width);

  outDiv.insertAdjacentElement("afterbegin", gifIframe);

  giphyForm.reset();
};
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas.

> ### Essa criação do iframe e reset do input me pareceram "sobrar" na minha função, apesar de necessárias.

A criação do iframe não necessariamente precisa estar na `renderGif`. 

Neste caso, eu deixaria a função que cria o iframe em uma função isolada sim:

```javascript
const createGifIframe = (url, height, width) => {
  const iframe = document.createElement("iframe");
  iframe.src = url;
  iframe.height = height;
  iframe.width = width;
  iframe.setAttribute("frameborder", "no");

  return iframe;
};
```

```js
const renderGif = async (event) => {
  event.preventDefault();
  const searchedTerm = event.target.search.value.trim();
  const { embed_url, height, width } = await fetchGiphy(searchedTerm);
  const gifIframe = createGifIframe(embed_url, height, width);

  outDiv.insertAdjacentElement("afterbegin", gifIframe);
  giphyForm.reset();
};
```

Quanto ao reset do form, é meio que inevitável que ele não seja invocado ali. E não tem problema. 98% do código dentro da `renderGif` faz o que o nome dela diz =)

Eu não criaria uma função apenas para encapsular a invocação `giphyForm.reset();`, seria desnecessário pois há apenas uma ocorrência dessa invocação no código e essa ocorrência é suficientemente legível.

Faz sentido?

**Comment by ricardopontesdantas** [comment]
Valeu @Roger-Melo , fez sentido sim. Obrigado pela explicação, abraço!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
