### ISSUE TITLE
Resumo da Aula Null e undefined 03-03 da etapa 01

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2107]
- **Null** e **undefined** representam a falta de um valor. No entanto, **null** é intencionalmente atribuído, enquanto **undefined** é automaticamente atribuído pelo JS.
- Exemplo de **undefined**: quando declaramos uma variável sem termos atribuído valor a ela, ao solicitamos ao console que seja exibido, veremos a mensagem _undefined_. Em operações matemáticas, ele regará um _NaN_.
- Exemplo de **null**: quando indicamos intencionalmente que não há valor em uma variável. Em operações matemáticas, ele tem efeito de zero, e ao exibirmos no console, aparece como “_null_”.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery! Rumo à fluência 🔥
