### ISSUE TITLE
Resumo da Aula Arrays - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by fabioCastroSardinha** [roger-melo-treinamentos/curso-de-js-roger-melo#2112]
![array 1](https://user-images.githubusercontent.com/54049289/139963556-8b586fd5-e200-44b1-8e87-b4038e699a74.PNG)
![arra 2](https://user-images.githubusercontent.com/54049289/139963561-629d7329-a545-4da9-b900-1c4f94756e84.PNG)
![array 3](https://user-images.githubusercontent.com/54049289/139963570-e242176d-b12f-4bd2-b35a-5cb54f719eb8.PNG)

**Comment by Roger-Melo** [comment]
Boa @fabioCastroSardinha! Rumo à fluência 🔥
