### ISSUE TITLE
Resumo da Aula 02 da etapa 02

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2114]
**Tipos de dados**

**number ->**  _armazena números, seja letras ou números _
**strings ->**  _armazena uma cadeia de caracteres. Pode estar entre aspas simples '     ' ou aspas duplas "     "_
**boolean ->** _valores lógicos - true, false_ 
**object ->** _estruturas de dados complexas - arrays, datas, literais, etc_
**null ->** _representa valores vazios - definido pelo programador_
**undefined ->** _valores vazios - definido pelo javascript_
**BigInt ->** _para armazenar números muito grandes_
**symbol ->** _utilizados com objetos_

**Comment by Roger-Melo** [comment]
Boa @Jansen-Muniz! Rumo à fluência 🔥
