### ISSUE TITLE
exercício 3 da aula, é muito errado fazer desse jeito?

### ISSUE THREAD

**Issue by shinkitsune** [roger-melo-treinamentos/curso-de-js-roger-melo#2118]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284

### Descreva a dúvida

É muito errado fazer desse jeito que eu fiz, já que coloquei o for dentro da function, e quando invocar a function só passar a quantidade.

```js
const multString = function(number = 'Você deve passar um valor como argumento') {
    for (let i = 0; i < number;  i++) {
        let countString = i + 1
        console.log(`Está e a ${countString}ª vez que essa string é exibida`);
    }
}
multString(7)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @shinkitsune.

Não é errado, vc chegou no resultado de uma forma diferente.

Apenas fique atento ao que o enunciado do exercício diz. 

Observe que o primeiro item é `Implemente uma função que apenas exibe no console o valor recebido por parâmetro;`. 

Criar funções com responsabilidades únicas é um princípio que será intensificado à medida em que vc avançar no treinamento =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
