### ISSUE TITLE
Etapa 03, Exercício 08- Aula 01

### ISSUE THREAD

**Issue by djailtim** [roger-melo-treinamentos/curso-de-js-roger-melo#212]
Professor, no exercício que pede o resultado da divisão entre dois números foi colocado por default o valor 0 (para prevenir undefined), quando invocado a função sem nenhum argumento está retornando _NaN_... Gostaria de entender, tentei inserir a operação em uma _const_ e num console pedi o '_typeof_', retornou '_number_'; porém após o _return_, ainda assim retorna NaN.

```js
const divide = function (a = 0, b = 0){
  return a / b
}

console.log(divide())
// NaN

console.log(typeof divide())
// number
```

Estou questionando certo professor?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ailton.

Se você executar um console.log que recebe `0 / 0` (que é o que a invocação `divide()` retorna), o retorno será `NaN`.

Se você abrir a calculadora do windows e tentar executar 0 / 0, eis o resultado:

![image](https://user-images.githubusercontent.com/29297788/108580993-d9741f80-730c-11eb-82ac-7c51becbfa36.png)

Então sim, `divide()` retorna o resultado de `a / b`, que por baixo dos panos é `0 / 0` e como essa não é uma operação matemática válida, `NaN` é retornado.

Pegou a ideia?

@djailtim

**Comment by djailtim** [comment]
Oi Roger,

Entendi.

Muito obrigado!

@Roger-Melo
