### ISSUE TITLE
Resumo da Aula Conversão e tipos aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by kennedyDev454** [roger-melo-treinamentos/curso-de-js-roger-melo#2122]
// Conversão de  tipos

// Conversão de string para number
// Para a conversão usamos o método Number()

const score = '200' // aqui score é uma string

const newNumber = Number(score) // usando o método para conversão

// console.log(newNumber) // retorna um number 

// console.log(typeof newNumber)//retorna o tipo de newNumber que é um numero

// Conversão de String para Number
//Para a conversão usamos o método String()

const number = 2000 // aqui number é um número

const otherNumber = String(number) // usando o método para conversão

// console.log(number) // number

// console.log(otherNumber) // string

const str = 'Maça'

// console.log(Number(str)) // retorna NaN pois é uma operação que não faz sentido

// console.log(typeof Boolean(10))

/* Valores falsy
    - false
    -0
    -'' ou ""
    -null
    -undefined
    -NaN
*/

// Valores trhuty 

// - Qualquer valor que não é falsy

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @kennedyDev454! Rumo à fluência 🔥
