### ISSUE TITLE
Exercícios da Aula 01

### ISSUE THREAD

**Issue by Williammedeiros** [roger-melo-treinamentos/curso-de-js-roger-melo#2129]
### Etapa da aula

1

### Nome da aula

Exercícios da Aula 01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/733512

### Descreva a dúvida

Boa tarde. 

Minha dúvida vem da Aula 01 dos Itens 08, 09 e 10

Fiquei com dúvidas no enunciado e fiz dessa maneira nos itens 08 e 09 para verificar se estão corretos ou não

Já no item 10 entendi que tem que entrar na URL que foi informado e colocar em modo desenvolvedor em "Devtools""
e incluir a const myBirthYear e atribuir o ano de seu nascimento, fiz de acordo e retornou undefined e não passei para outra etapa, ficou travado.
```js
// Aula 01 - item 08

const myAge = currentYear - myBirthYear 

// Aula 01 - item 09

const ten = 10
console.log(`Em ${currentYear}, estarei com ${ten} anos.`)

// Aula 01 - item 09

const ten = 10
console.log(`Em ${currentYear}, estarei com ${ten} anos.`)

//Aula 01. - item 10
const myBirthYear = 1977
undefined
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Williammedeiros.

Aos 6:25 [dessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/742273) eu mostro como resolver o exercício 09. 

Se vc observar seu código do exercício 09, ele está diferente do que foi mostrado na aula. Falta fazer as operações de soma, ok?

Esse é um primeiro ajuste que vc precisa fazer em seu código.

---

> ### ...fiz de acordo e retornou undefined e não passei para outra etapa, ficou travado.

Vai retornar undefined. 

Observe que aos 7:17 da aula que linkei no parágrafo acima, `undefined` é retornado após eu declarar a `const` no console. Isso é normal e será explicado em aulas futuras.

Sobre estar "travado", talvez dê a impressão de que travou devido ao cursor de texto não estar piscando no console do devtools. 

Dê um clique abaixo de `undefined` e vc verá o cursor piscando.

![cursor](https://user-images.githubusercontent.com/29297788/140247533-c9d489ff-9111-419b-8339-5463552e5332.jpg)

---

Seguindo o passo acima, o problema foi resolvido?

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
