### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by paulozy** [roger-melo-treinamentos/curso-de-js-roger-melo#2135]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/paulozy/quizCJRM

### Maiores dificuldades durante a implementação

Não tive muitas dificuldades porque assisti a aula do quiz dos filmes antes de realizar a aplicação, portanto fiquei confuso nas formas que usei para obter as referencias dos elementos do DOM, não sei se foi a melhor forma de fazer.

### Menores dificuldades durante a implementação

Em relação o bootstrap, eu já conhecia a ferramenta e como usa-la, tanto que cheguei a usar o componente de modal para realizar a visualização do resultado.

**Comment by Roger-Melo** [comment]
Olá @paulozy.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @paulozy!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Não tive muitas dificuldades porque assisti a aula do quiz dos filmes antes de realizar a aplicação, portanto fiquei confuso nas formas que usei para obter as referencias dos elementos do DOM, não sei se foi a melhor forma de fazer.

Se você enviou a aplicação [nesse ponto](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2829070) (sem ver as aulas após o aviso) e chegou nesse ponto do treinamento seguindo [estes passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661), tá tudo certo =)

Não se preocupe com a melhor forma de fazer. O mais importante num primeiro momento é resolver o problema, como você fez. 

Depois, com a prática vc vai conhecendo novas formas de resolver o mesmo problema e vai melhorando o código (se julgar que a nova forma é mais eficiente).

Tem apenas uma observação que vou fazer sobre o armazenamento dos elementos do DOM ali em baixo.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

A solução de exibição dos pontos ficou bem posicionada na tela.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

### Pontuação máxima

Ao invés de apenas exibir a pontuação que o usuário fez, o ideal é que esteja claro o quão bem ele foi no quiz. 

Isso pode ser feito com uma mensagem do tipo "Você acertou 3 de 5 perguntas", ou "Você acertou 50%", por exemplo. 

## Organização de código

### Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

### Nomes de variáveis e funções

Primeiro, deixa eu te mostrar uma parada...

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Isso vc pegou bem. No geral os nomes que vc deu estão bem resolvidos.

Porém, eu acho que é possível deixar mais explícito que certas variáveis estão armazenando elementos do DOM.

Uma forma de testar se o nome que vc deu para uma variável está fazendo sentido é lendo as linhas de código onde a variável é usada.

No caso das variáveis abaixo, vc pode avaliar o que faz mais sentido quando a variável e uma propriedade ou método encadeado nela são lidos.

```javascript
// antes
quizResults.style = 'display: block'
```

```javascript
// depois
modalUserScore.style = 'display: block'
```

```javascript
// antes
userScoreResult.textContent = `...`
```

```javascript
// depois
scoreMessage.textContent = `...`
```

```javascript
// antes
closeResults.addEventListener('click', () => {})
```

```javascript
// depois
buttonCloseModal.addEventListener('click', () => {})
```

Essas são algumas sugestões.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
