### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#214]
Olá, @Roger-Melo .
Segue o exercício 19 sobre a aplicação do quiz;

Link: https://github.com/gcarniel/curso-JS-roger-melo/tree/main/etapa-07/aula-01/exercicio-19

**Maiores dificuldades.**
    

- Para mim a maior dificuldade foi entender como mudar as cores do bootstrap, após ir fuçando e alterando eu entendi como fazia para alterar, pelo menos, o background e textos.
    

- Comecei a assistir as aulas da etapa 07 então vi a implementação do quiz, por isso não tive dificuldades para verificar as respostas certas, senão fosse por isso acredito que essa seria a maior dificuldade.
    

- Outra dificuldade que tenho, não foi caso desse exercício, mas é tanto o HTML e mais ainda CSS. Criar o básico eu sei, maior dificuldade mesmo é organizar na página todas as tags com CSS. 

- Não entendi bem como era para exibir a pontuação na tela, então criei um paragrafo dentro de uma div para mostrar.

**Menores dificuldades.**

- Obter elemento através do querySelector foi a menor dificuldade, pois já ficou bastante claro pra mim.

- O forEach também é outro ponto que não tenho tido dificuldades.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @gcarniel.

Passando para avisar que sua issue foi visualizada, e que a verificação dos requisitos para a análise da aplicação será feita em breve. Se estiver tudo ok, a análise será publicada aqui =)

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Parabéns pelo esforço em implementar a aplicação =)

A exibição dos pontos ficou legal, o objetivo era apenas implementar, não importa como. E deu pra perceber que você entendeu bem a lógica até aqui.

Tenho apenas duas observações em relação à organização do código:

### Linhas em branco

Use linhas em branco para indicar, visualmente, a separação entre conceitos.

```javascript
// antes
form.addEventListener('submit', event => {
    event.preventDefault()
    let score = 0
    const userAnswers = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value,
    ]
    userAnswers.forEach((answer, index) => {
        if(answer === correctAnswers[index]){
            console.log(form.inputQuestion1)
            score += 25
        }
    })
    p.textContent = `Você fez ${score}/100 pontos.`
})

// depois
form.addEventListener('submit', event => {
    event.preventDefault()

    let score = 0

    const userAnswers = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value,
    ]

    userAnswers.forEach((answer, index) => {
        if(answer === correctAnswers[index]){
            console.log(form.inputQuestion1)
            score += 25
        }
    })

    p.textContent = `Você fez ${score}/100 pontos.`
})
```

Seguindo este princípio, as linhas em branco do código do "depois" (acima) separa os seguintes conceitos:

- Prevenção da página ser carregada após o envio do form;
- Uma let que sofrerá mutação de valor;
- Um array com as respostas do usuário;
- O cálculo da pontuação;
- A inserção da pontuação na tela.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

### console.log()

Ao subir uma aplicação para a produção (nas aulas seguintes você irá fazer isso), sempre verifique se não há valores sendo exibidos no console. Há não ser que a intenção seja realmente mostrar esses valores para um outro dev.

Novamente, parabéns pelo esforço. Nas aulas seguintes, você verá como refatorar o código dessa aplicação =)

> Outra dificuldade que tenho, não foi caso desse exercício, mas é tanto o HTML e mais ainda CSS. Criar o básico eu sei, maior dificuldade mesmo é organizar na página todas as tags com CSS.

Vou deixar abaixo bons conteúdos (gratuitos e pagos) para você revisar. Mas lembre-se, não se preocupe excessivamente com isso. Você não precisa ser o "bichão" em HTML e CSS para chegar na fluência em JavaScript, basta apenas saber o básico.

- https://youtube.com/playlist?list=PLwXQLZ3FdTVGKl3iPEyEWpFoYkMUxWW5O
- https://youtube.com/playlist?list=PLwXQLZ3FdTVGf7GUtiOFLc_9AXO25iIzG
- https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n
- https://www.udemy.com/share/101JsQAkcccltaTX4=/

Ficou alguma dúvida sobre as observações?

@gcarniel

**Comment by gcarniel** [comment]
Oi, @Roger-Melo 
Saquei a separação do código por conceito. Geralmente eu separava quando ficava muito junto, mas não tinha um padrão, por conceito fica muito melhor de ler e dar manutenção, vlw.

O console log foi vacilo meu mesmo. Tanto que nas aulas seguintes eu removi, mas ainda não comitei.
Valeu pelas dicas, Roger. Já salvei as playlists para quando terminar o curso eu começar a ver. 
Tenho um controle financeiro desenvolvido em VBA e Excel e futuramente quero migrar para web. Já até salvei um vídeo seu de um controle financeiro também!

Obrigado, Roger.

**Comment by Roger-Melo** [comment]
Legal! Já que ficou mais claro vou fechar a issue, mas no que precisar, é só abrir uma nova =)

@gcarniel
