### ISSUE TITLE
Aplicação de Conversor de moeda

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2147]
### Etapa da aula

14

### Nome da aula

Aviso importante

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2829261

### Descreva a dúvida

Roger, boa tare! Na ultima aula da etapa 14 tem um aviso de não esquecer de enviar a aplicação de conversor de moeda, mas eu nao vi nada sobre esta aplicação até então. Fiquei sem entender. Onde está a explicação sobre esta aplicação de conversor de moeda?

Desde ja agradeço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @JuFML!

> ### Onde está a explicação sobre esta aplicação de conversor de moeda?

Está no [***exercício 07***](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-38/app.js#L186) da 38ª bateria de exercícios.

A forma de fazer essa aplicação é um pouquinho diferente das anteriores.

A intenção é que, desta vez, a aplicação seja implementada seguindo o passo a passo descrito no exercício 07 e, após implementada, enviada para a análise. 

Nos vídeos seguintes, eu mostro a forma que implementei essa aplicação =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
