### ISSUE TITLE
Exercicio da aula 3 da etapa 14

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2149]
### Etapa da aula

14

### Nome da aula

Exercicio da aula 3 da etapa 14

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1958774

### Descreva a dúvida

Roger boa tarde!

Estou fazendo os exercícios da aula 3 da etapa 14 e, diferente dos demais exeercicios ja feitos durante o curso, sinto que falta algum conteúdo antes. Não sei te explicar mas a sensação que eu tenho é de quando a gente deixa de assistir alguma aula e ja vai fazer o exercício. Faz sentido o que eu estou te falando?

Vou dar exemplos:
- No primeiro exercicio fala para criar prototype que seja um objeto com o método getColor e depois para fazer este objeto ser prototype deste dois outros carros (que são objetos). Dai na resolução do exercicio vc usa o Object.create( carproto) e atribui a estes dois objetos de carro. Eu não vi esta explicação em nenhum das suas aulas da etapa 14. A aula que menciona este Object.create é a de herança prototipal que fala como passar um protype de uma classe para outra ou de uma função construtora para outra mas a sintaxe é totalmente diferente.
- 
- No segundo exercício pede para fazer com que os undefined's não apareçam mais e sim as string correspondentes. Daí na resolução do exercício vc usa do .call(movie) encadeado após a função getSummary, resolução esta que tbm não vi explicação  em nenhuma aula anterior. A única aula que fala sobre o call tbm é de Herança prototipal que usa o .call( ) para invocar o constructor, o this e as propriedades da função pai.

Este foi o primeiro exercicio de todo o curso que não consegui nem começar sozinha.

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### No primeiro exercicio fala para criar prototype que seja um objeto com o método getColor e depois para fazer este objeto ser prototype deste dois outros carros (que são objetos). Dai na resolução do exercicio vc usa o Object.create( carproto) e atribui a estes dois objetos de carro. Eu não vi esta explicação em nenhum das suas aulas da etapa 14. A aula que menciona este Object.create é a de herança prototipal que fala como passar um protype de uma classe para outra ou de uma função construtora para outra mas a sintaxe é totalmente diferente.

Entre 8:33 e 9:41 [dessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1904025) é mostrado um exemplo idêntico ao exercício 01, em que um objeto é setado como prototype de outro objeto através do `Object.create` =)

---

> ### No segundo exercício pede para fazer com que os undefined's não apareçam mais e sim as string correspondentes. Daí na resolução do exercício vc usa do .call(movie) encadeado após a função getSummary, resolução esta que tbm não vi explicação  em nenhuma aula anterior. A única aula que fala sobre o call tbm é de Herança prototipal que usa o .call( ) para invocar o constructor, o this e as propriedades da função pai.

[Aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1904025), aos 4:22, é enfatizado que o `call` deve ser usado para invocar uma determinada função e forçar que o `this` dessa função armazene o valor que vc quer que ele armazene. E é exatamente isso que o exercício 02 pede. Olha só...

```javascript
function getSummary () {
  return `${this.title} foi dirigido por ${this.director} e tem ${this.starringRole} no papel principal.`
}
```

No código acima, é necessário forçar o `this` dentro da função a armazenar um outro valor que não é o que ele está armazenando no momento. 

---

> ### Este foi o primeiro exercicio de todo o curso que não consegui nem começar sozinha.

Eu não vejo isso como algo negativo.

Muito pelo contrário, é um sinal de que vc está saindo da zona de conforto.

Ninguém gosta da sensação de frustração, mas infelizmente, nem sempre vamos conseguir resolver tudo. Ou acertar de primeira. 

> ### sinto que falta algum conteúdo antes

Nesse caso, não penso que tenha faltado. 

Há certos exercícios em que eu pego o princípio e aplico ele de forma diferente do mostrado em aula sim. 

Se todas as respostas fossem escancaradas em aula, não haveria o desafio e estímulo de tentar encontrar a pequena peça que falta do quebra cabeça. Seria apenas mais uma aula `Ctrl + C` + `Ctrl + V`, o que não faz sentido em um treinamento que se propõe a treinar o aluno(a) a ser fluente. 

Mas no treinamento, provavelmente a peça já está no campo de visão, basta olhar com cuidado...

Por outro lado, vc pode procurar ajuda aqui sempre que tiver dúvidas. Estou aqui para ajudar =)

@JuFML
