### ISSUE TITLE
Etapa 07, Aula 03

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#215]
Minha dúvida não é especificamente sobre essa aula, mas sobre a revisão raio-x.

Enviei o exercício 19 para correção, atualmente foi o último que fiz até o momento. Na revisão raio-x eu teria que começar a refazer os exercícios a partir do 01 até chegar no 19?
E só então continuar a assistir as aulas após terminar a revisão dos exercícios? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @gcarniel. 

O ideal é começar a resolver novamente as baterias de exercícios, começando da primeira. 

Se você sente que está muito confortável com ela, comece à partir da primeira bateria de exercícios que você sentiu que começou a ter um certo nível de complexidade.

Regra de ouro: rolou dúvida, não hesite em abrir uma issue.

Sacou a ideia?

@gcarniel

**Comment by gcarniel** [comment]
Saquei sim, @Roger-Melo 
Vlw. abraço.
