### ISSUE TITLE
Resumo da Aula 02 E 03 da etapa 01

### ISSUE THREAD

**Issue by jarana-2020** [roger-melo-treinamentos/curso-de-js-roger-melo#2150]
[44581165920-IRPF-D-2021-2020-0211-06.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7479646/44581165920-IRPF-D-2021-2020-0211-06.pdf)
![IMG_2972](https://user-images.githubusercontent.com/65747305/140438750-359a8f61-b847-44b3-859e-db2c7d91f314.jpg)
![IMG_2973](https://user-images.githubusercontent.com/65747305/140438754-fae191b0-1c83-4ca4-a2f7-1c7cad5f7606.jpg)
![IMG_2974](https://user-images.githubusercontent.com/65747305/140438758-bdb6f4d9-d953-4399-a2a0-de374b52d62d.jpg)
![IMG_2975](https://user-images.githubusercontent.com/65747305/140438759-f28d5c74-e338-42bf-a46c-fdeaae2d3b42.jpg)
![IMG_2976](https://user-images.githubusercontent.com/65747305/140438760-42cc7901-2252-48b2-86e0-c99f5e65edb7.jpg)
![IMG_2977](https://user-images.githubusercontent.com/65747305/140438762-49eeb7cc-69ed-48ae-ae4e-0be6b2352acb.jpg)
![IMG_2978](https://user-images.githubusercontent.com/65747305/140438764-7afa383a-92d2-40d6-a8bf-32a10019403d.jpg)

**Comment by Roger-Melo** [comment]
Excelente @jarana-2020! Foco na fluência ⚡
