### ISSUE TITLE
Resumo da Aula Forloop e While loop aula 01-03 e 01-04 da etapa 02

### ISSUE THREAD

**Issue by kennedyDev454** [roger-melo-treinamentos/curso-de-js-roger-melo#2151]
// Os loops oferecem uma maneira rápida e fácil de fazer
// algo repetidamente.

//Um forloop se repete até que uma condição 
//especificada seja avaliada como false.

// SINTAXE

// for (inicial; condiction; increment) {
//     // código aqui
    
// }

/*

for (let i = 0; i < 5 ; i++){
   // codigo aqui
}

inicializa com a declaraçao de i = 0

depois ele verifica se i é menor que 5 se for ele incrementa 1 ao i 
apos isso ele não declara a i denovo volta para a condição ate que i seja 5 
apos isso ele encerra o loop
*/

for(let i = 0; i < 5; i++){
  console.log(`Contando ate ${i}`) // retorna de 0 a 4 pois o 5 não é incluido
}

console.log('Acabou o loop')

// for(let i = 0; i <= 10; i++){
//     console.log(i) // conta ate que i seja 10 ao atingir o loop se encerra
// }

const names = ['John','T-Pol']

let template = ''

for(let i = 0; i < names.length; i++){
 template += `<h1>Nome: ${names[i]}</h1>\n`
}

// console.log(template)

// LOOP WHILE
// Executa suas instruções 
//contanto que uma condição especificada seja avaliada como true

// let i = 0

// while(i <=10){
//   // dentro do parêntese avalia a condição
//     console.log(i)
//     i++ // incrementa i até que a condição seja verdadeira
// }

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @kennedyDev454! Foco na fluência ⚡
