### ISSUE TITLE
Resumo da Aula 02-03 da etapa 01 - Strings

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2153]
- Strings são encadeamentos de caracteres e servem para armazenar nomes ou números dentro de aspas simples ou aspas duplas
- É possivel armazenar uma string dentro de uma variável. Exemplo: const email = 'jansen.muniz1@gmail.com'
- concatenação de strings: juntar duas strings. 
Exemplo: 
 const firstname = 'Jansen'
 const lastname = 'Muniz'
 const fullname = firstname + '     '(para separar as strings) + lastname
- para acessar caracteres de uma string - exemplo: console.log(fullname[0]) - aparecerá no console o primeiro caractere da string
- uma string também possui método e propriedade, o length é uma propriedade que mostra o tamanho de uma string, quantos caracteres a string possui. Exemplo: console.log(fullname.length) - irá ser mostrado no console a quantidade de caracteres(incluindo o espaço em branco - '    ')
- método de string toUpperCase serve para deixar os caracteres da string todos maiúsculos. exemplo: console.log(fullname.toUpperCase( )) - os parenteses caracterizam um método.
- método de string toLowerCase serve para deixar os caracteres da string todos minúsculos.
- os métodos toUpperCase e toLowerCase não alteram a string original. Exemplo: console.log(fullname) - no caso aparecerá no console Jansen Muniz.
- o método indexOf exibe a posição de um caractere especificado de uma string, isso é feito sendo passado como argumento -dentro dos paranteses método(argumento) - do método o caractere desejado. 
Exemplo: 
const index = firstname.indexOf('J')
console.log(index)
será mostrado no console o número da posição do caractere, no caso o 1

**Comment by Roger-Melo** [comment]
Excelente @Jansen-Muniz! Foco na fluência ⚡
