### ISSUE TITLE
Resumo da Aula Condicional switch 03-04 da etapa 02

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2156]
A condicional **_switch_** permite trabalhar com uma série de condições que um determinado elemento pode apresentar e as ações a serem tomadas para cada caso, eliminando a necessidade de encadearmos diversos _if_ e _else_, o que poderia ser muito trabalhoso diante de inúmeras condições.
Exemplo:

```js
switch (variavel){
    case 'A': // se o valor de variavel for A, executa a respectiva instrução (exibe A no console)
        console.log('A') 
        break
    case 'B': // se o valor de variavel for B, executa a respectiva instrução (exibe B no console)
        console.log('B')
        break
    case 'C': // se o valor de variavel for C, executa a respectiva instrução (exibe C no console)
        console.log('C')
        break
    case 'D': // se o valor de variavel for D, executa a respectiva instrução (exibe D no console)
        console.log('D')
        break
    case 'E': // se o valor de variavel for E, executa a respectiva instrução (exibe E no console)
        console.log('E')
        break
    default: // o default é opcional, neste caso é usado para exibir 'outros' no console, caso variavel tenha outro valor qualquer
        console.log('outros')
}
```
 É necessário inserir um **_break_** em cada _**_case_**_, do contrário,  _**switch**_ continuará rodando, executando os demais blocos, independente das condições que apresentem. No bloco de **_default_**, por ser o último, não há necessidade.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery! Foco na fluência ⚡
