### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by lpf-developer** [roger-melo-treinamentos/curso-de-js-roger-melo#2158]
1 - Uma string representa uma cadeia de caracteres delimitada por aspas simples ou duplas;

2 - Esta string pode ser exibida diretamente no browser através da função console.log('string');
```javascript
console.log('myString')
````
3 - Uma string pode ser armazenada em uma variável e exibida no browser através da função console.log('myvar');
```javascript
let myStrig = "This is my string"
console.log(myString)
````
4 - Podemos unir duas ou mais strings em uma única cadeia de caracteres através de um processo denominado concatenação;
```javascript
const firstName = "Luis Paulo"
const lastName = "França"
const fullName = firstName + ' ' + lastName
console.log(fullname)
````
5 - Podemos exibir um caractere específico dentro de uma string. No exemplo, será exibido o primeiro caractere da string, pois a contagem de caracteres começa na posição 0;
```javascript
const god = "God bless you"
console.log(god[0]) // G
````
6 - Podemos obter o número total de caracteres (tamanho) de uma string através do método `length` do objeto string. Espaços em branco dentro da string, também são contados como caracteres.
```javascript
const god = "God bless you"
console.log(god.length) // 13
````
7 - Outro método importante é o `toUpperCase()` que converte a string em uma string cujas letras são maiúsculas;
```javascript
const god = "God bless you"
console.log(god.toUpperCase()) // GOD BLESS YOU
````
8 - Veja outros métodos:

a) toLowerCase(): converte letras maiúsculas em minúsculas: `god.toLowerCase()`;
b)indexOf(): retorna a posição do caractere, informado entre parênteses, dentro da string: `god.indexOf('b') // 4 (posição 4)` . O valor contido nos parênteses é chamado de argumento.

**Comment by Roger-Melo** [comment]
Excelente @lpf-developer! Foco na fluência ⚡
