### ISSUE TITLE
Etapa 07, Aula 03

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#216]
Olá, @Roger-Melo. Minha dúvida não é dessa aula, mas me ocorreu nos momentos em que estou vendo ela.
É sobre invocação de função. Não sei se meu código será o melhor exemplo, mas vamos lá.

Sei que para invocar uma função eu preciso passar a função e parênteses 'func()'.

Mas no caso do forEach abaixo eu passo só a referência da função, como ela é invocada? 
Nesse caso ela vai percorrer o array 3 vezes e nas 3 invocando a func para ir somando, mas não entendi essa questão 
da invocação, pode me esclarecer isso?

Obrigado.

```
let total = 0
const array = [1,2,3]
const func = a => total += a

array.forEach(func)

console.log(total)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

> Mas no caso do forEach abaixo eu passo só a referência da função, como ela é invocada? 

O `forEach` irá invocar a função automaticamente para cada item do array. Então não é necesário você invocar a função. Isso por que a invocação do `forEach` espera receber como argumento a declaração ou a referência de uma função para que ele a invoque:

```javascript
let total = 0
const array = [1,2,3]
// Opção 1: a declaração da função é inserida como argumento
array.forEach(a => total += a)

// ou

// Opção 2: func é referenciada como argumento

const func = a => total += a

array.forEach(a => total += a)
```

Ou seja, no código acima, em qualquer uma das duas opções, a função é invocada para cada item do array.

Vou colocar isso em uma tabela para você ter uma panorama geral do que está acontecendo:

Execuções da `func` | valor do parâmetro `a` | valor que `total` recebeu
------------ | ------------- | -------------
1ª execução | 1 | 1
2ª execução | 2 | 3
3ª execução | 3 | 6

Sacou a ideia?

Se não tiver sacado, é só dar o toque e explico de outra forma.

Se tiver sacado, tenho uma outra observação a fazer sobre o exemplo que você deu. Mas só farei ela depois de certificar que você entendeu o que escrevi acima =)

@gcarniel

**Comment by gcarniel** [comment]
Olá, @Roger-Melo 
Ainda não ficou tão claro para mim, mas o meu exemplo não foi dos melhores, o forEach eu saquei.
Minha dificuldade mesmo está em entender a invocação da função, independente do forEach.

```
const digaOla = () => console.log('Olá')

// se eu só deixar assim 'Olá' nunca vai aparecer no console, então preciso invocar ela.

digaOla()
// e agora no console vai aparecer 'Olá', pois a invoquei.

```
E agora vem a dúvida de fato, por que ao passar digaOla para uma outra função sem os parênteses ela vai ser invocada do mesmo jeito e aparecer 'Olá' no console. Não sei se consegui passar a explicação da minha dúvida.

Mas basicamente quando quero invocar a função eu chamo ela com parênteses digaOla() e quando a função é um argumento de outra função eu não passo os parênteses, isso que não entendi.

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Antes de responder, deixa só eu dar uma dica. 

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, é só inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const digaOla = () => console.log('Olá')

// se eu só deixar assim 'Olá' nunca vai aparecer no console, então preciso invocar ela.

digaOla()
// e agora no console vai aparecer 'Olá', pois a invoquei.
```

Ele ficará assim =)

```javascript
const digaOla = () => console.log('Olá')

// se eu só deixar assim 'Olá' nunca vai aparecer no console, então preciso invocar ela.

digaOla()
// e agora no console vai aparecer 'Olá', pois a invoquei.
```

---

> E agora vem a dúvida de fato, por que ao passar digaOla para uma outra função sem os parênteses ela vai ser invocada do mesmo jeito e aparecer 'Olá' no console. Não sei se consegui passar a explicação da minha dúvida.

`digaOla` só será executada quando for inserida como argumento da invocação de outra função caso essa outra função receba a referência da `digaOla` por parâmetro e execute a referência que o parâmetro recebeu.

Exemplo, se eu inserir `digaOla` como argumento da invocação da `func`, nada acontece:

```javascript
const digaOla = () => console.log('Olá')

const func = () => {
  // nenhum código aqui
}

func(digaOla) // nada acontece
```

Nada aconteceu por que a `func` sequer tem um parâmetro.

Se eu inserir um parâmetro nela, nada acontece mas desta vez, por que `param` não foi usado dentro da `func` para invocar a referência da função que ele armazena (que é a `digaOla`):

```javascript
const digaOla = () => console.log('Olá')

const func = param => {
  // nenhum código aqui
}

func(digaOla) // nada acontece
```

Agora, se `param` (que armazena a referência da `digaOla`) é invocado, 'Olá' é exibido no console:

```javascript
const digaOla = () => console.log('Olá')

const func = param => {
  param() // Olá
}

func(digaOla)
```

Essa era a dúvida?

Se for, o código acima funciona por que `digaOla` foi usada como uma função de callback. Caso precise reforçar o conceito de callbacks, dê uma olhada [nessa](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/188) issue e se alguma dúvida permanecer ou eu não tiver respondido a que já existia, é só dar o toque =)

@gcarniel

**Comment by gcarniel** [comment]
Saquei, Roger. Eu estava colocando o código entre as crases, mas não colocava javascript, e no preview achei que não mostrava formatado. Faltou só especificar javascript.

Acho que agora ficou claro sim, Roger. Vou começar a refazer os exercícios e se ainda restar dúvida eu te chamo.
Obrigado pela atenção.

**Comment by gcarniel** [comment]
Voltei com um exemplo melhor para minha dúvida, @Roger-Melo 

```javascript
 const counterContainer = document.querySelector('.counter-container')
  const buttonInit = document.querySelector('.button-init-counter') 
  const buttonStop = document.querySelector('.button-stop-counter') 
  
  
  let timer = null

  const incrementCounter = () => {
    timer = setInterval(() => {
      const incrementedCounter = Number(counterContainer.textContent) + 1
      counterContainer.textContent = incrementedCounter
    }, 1000)
  }
  
  const stopCounter = () => {
    clearInterval(timer)
    counterContainer.textContent = 0
  }
  

  buttonInit.addEventListener('click', incrementCounter)

//aqui no addEventListener eu estou passando a função stopCounter por referência, eu não entendi como ela é invocada.
  buttonStop.addEventListener('click', stopCounter)
```

stopCounter é uma função sem parâmetro que vai executar duas ações, eu entendo que se eu quiser invocar ela eu preciso
passar seu nome com os parênteses stopCounter(). Mas no caso do addEventListener eu só passei a referência, não entendi como ela é invocada.

**Comment by gcarniel** [comment]
Não tenho certeza, mas pelos testes que fiz, e me corrija se eu estiver falando bobagem, é como se quando eu passar a referência de uma função como argumento para outra função ela será invocada, é isso?

**Como se fosse uma regra para executar:**

- Como argumento de uma função passa outra como referência.

- No corpo de uma função passa outra função como invocação;

```javascript

  const stopCounter = () => {
    clearInterval(timer)
    counterContainer.textContent = 0
  }

//stopCounter como invocação executa a função.
 buttonStop.addEventListener('click', () => {
    stopCounter()
  })

//stopCounter como referência executa a função.
 buttonStop.addEventListener('click',  stopCounter) 
```

**Comment by Roger-Melo** [comment]
A `stopCounter` vai ser invocada automaticamente, por baixo dos panos, quando o 'click' acontecer no `buttonStop`.

Você irá inserir a referência da função como argumento da invocação de um método quando o método esperar isso.

No código abaixo,

```javascript
buttonStop.addEventListener('click', stopCounter)
```

como a referência de `stopCounter` foi inserida como segundo argumento da invocação do método `addEventListener`, ela vai ser invocada automaticamente, por baixo dos panos, quando o 'click' acontecer no `buttonStop`.

Já nesse outro código,

```javascript
array.forEach(func)
```

como a referência da `func` foi inserida como argumento da invocação do método `forEach`, ela vai ser invocada automaticamente, por baixo dos panos, para cada item do array `array`.

Tanto a função `stopCounter` quanto a `func` são invocadas sem os `()` por que elas foram inseridas como argumentos de métodos que vão invocar elas por baixo dos panos no momento certo.

---

Observe que no código abaixo, 

```javascript
buttonStop.addEventListener('click', () => {
  stopCounter()
})
```

`addEventListener` precisa receber a declaração ou a referência de uma função. Como ele recebeu a declaração da `() => { stopCounter() }`, no momento em que o evento 'click' aconteceu no `buttonStop`, `() => { stopCounter() }` será invocada e como ela contém a invocação da `stopCounter`, `stopCounter` é invocada.

---

Está ficando mais claro?

Se não estiver, continue perguntando. É legal quando as dúvidas vão ficando cada vez mais específicas =)

@gcarniel

**Comment by gcarniel** [comment]
O ponto chave para minha dúvida é essa sua frase, @Roger-Melo.

> _Você irá inserir a referência da função como argumento da invocação de um método quando o método esperar isso._

Como vou saber o que o método espera?
Por que a minha dúvida é saber quando vou passar a invocação ou a referência. Mas eu acho que ficou claro pra mim.

Essa dúvida é antiga, há algum tempo eu fiz um curso de react native, mas sabendo o básico do básico de JS, e isso de passar refência é de lá, pois em alguns componentes tinha a função declarada lá em cima do código e na renderização do componente era passado só a referência da função.

Ontem eu testei dando um console.log em uma função como referência e vi que era mostrado toda a declaração da função, então "entendi" que quando passo a referência é como se a função estivesse declarada ali. Se for isso eu entendi kkk.

**Comment by Roger-Melo** [comment]
> Ontem eu testei dando um console.log em uma função como referência e vi que era mostrado toda a declaração da função, então "entendi" que quando passo a referência é como se a função estivesse declarada ali. Se for isso eu entendi kkk.

Isso mesmo =)

"Referência" é um termo técnico para "um pedaço de código que permite a obtenção de outro pedaço de código". Então quando uma `const` armazena uma função, o nome da `const` se torna a referência para aquela função.

> Como vou saber o que o método espera?

Geralmente eu falo, quando apresento novos métodos.

Uma outra forma bem legal de você saber é checando a documentação (MDN).

A doc. do [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), por exemplo, especifica o que a invocação do método precisa receber como argumento e qual é o retorno dele:

![image](https://user-images.githubusercontent.com/29297788/109087437-39dbd600-76ec-11eb-98df-86fedbe43177.png)

E isso vale para qualquer dúvida que você tiver sobre a linguagem. Sempre consulte a documentação. 

E claro, se a dúvida permanecer, abra uma issue para que eu possa te ajudar =)

@gcarniel

**Comment by gcarniel** [comment]
Saquei, @Roger-Melo 
Obrigado pela atenção.

**Comment by Roger-Melo** [comment]
Legal @gcarniel. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
