### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by lpf-developer** [roger-melo-treinamentos/curso-de-js-roger-melo#2160]
Continuando nosso estudo sobre os métodos relacionados a strings no Javascript:

1. O método `lastIndexOf( )` retorna a posição da última ocorrência de um determinado caractere dentro da string:

```javascript
const email = 'laracroft@rogermelo.com.br'
const lastIndexOf = email.lastIndexOf('a') // posição do último caractere a = 3
```
2. O método `slice( )` retorna uma porção da sequência de caracteres de uma string, baseada em dois argumentos: posição inicial e posição final. No exemplo são utilizados os métodos `lastIndexOf( )` e `slice ( )` para obter a primeira parte da `const email` "laracroft':

```javascript
const lastIndexOfB = email.lastIndexOf('@')
const emailSlice = email.slice(0, lastIndexOfB)
console.log(emailSlice, email) // laracroft
```
Note que o método `slice ( )` não altera o conteúdo da const email, mas, apenas copia o conteúdo delimitado pelos argumentos passados por parênteses.

3. O método `replace( )` substitui um determinado trecho da string por outro valor:

```javascript
const emailReplace = email.replace('laracroft','batman')
console.log(emailReplace) // batman@rogermelo.com.br 
```

**Comment by Roger-Melo** [comment]
Show, @lpf-developer! Lembre-se: o faixa preta é o faixa branca que não desistiu. Rumo à fluência! 🔥
