### ISSUE TITLE
Resumo da Aula Retornando valores 01-05 da etapa 03

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2165]
Quando desejamos obter de uma função algum valor por ela processado, utilizamos o **_return_**. Sem ele, tudo o que podemos fazer é exibir o valor no console, pois não é possível manipulá-lo fora da função, uma vez que está preso a ela devido ao escopo. 
O **_return_** possibilita obtermos o valor processado dentro da function, e assim manipularmos este valor fora dela quando quisermos. Para isto, armazenamos o valor retornado em uma variável.

```js
const produto= function (num){
    const n = num *2
    return n // irá retornar o produto de num*2 para fora da função
}

const resultado = produto(3) // irá armazenar o resultado retornado pela função
console.log(resultado) // exibe o valor retornado da função, que foi armazenado na constante 'resultado'
```

Também podemos retornar o valor desta função sem a necessidade de armazená-lo em uma variável local, bastando para isto colocar `return num*2`.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show, @Kmkery! Lembre-se: o faixa preta é o faixa branca que não desistiu. Rumo à fluência! 🔥
