### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by brunaribeiro89** [roger-melo-treinamentos/curso-de-js-roger-melo#2166]
<p> 
inteiros e decimais const radius = 10  const pi = 3.14   console.log(radius, pi)

     se atentar a precedência de operações
     const area = pi * radius ** 2
     console.log(area) 

  
        let postlikes = 10
        postilikes = postilikes + 1 
        postilikes++
        console.log(postlikes)

       operações que não resultam em um número me retornam NaN.
       concatenação de strings com números, sempre me resulta uma string:
       const likeMessage = 'o poste tem' +  postilike  + 'acessos'.
</p>

**Comment by Roger-Melo** [comment]
Show, @brunaribeiro89! Lembre-se: o faixa preta é o faixa branca que não desistiu. Rumo à fluência! 🔥
