### ISSUE TITLE
Resumo da Aula 02-04 da etapa 01 métodos comuns de string

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2167]
**Métodos** são funções que pertecem a um objeto ou tipo de dado específico.
 
**LastIndexOf -** vai **_obter o index da última ocorrência do caractere_** passado como argumento.

Exemplo:
const email = 'laracroft@rogermelo.com.br'
const indexOfA = email.indexOf('a')
console.log(indexOfA)

Será mostrado no console o index do caractere, no caso 3.

**Slice - _obtém uma parte da string_**, passando **dois argumentos, primeiro, o número do index do caractere a partir do qual a string vai ser pega; segundo argumento, até onde desejamos cortar a string**    

Exemplo:
const emailSlice = email.slice(0, 9)
console.log(indexOfA)

Ou seja, do @ em diante a string será cortada, sendo mostrado no console apenas laracroft.
Este método não modifica a string original.

**Replace - _substitui um caractere de uma string por outro e também uma parte da string por outra._ São passados dois argumentos, o primeiro é o caractere a ser subsitiuído, o segundo é o caracetere substituto.**
 
Exemplo:
const emailReplace = email.replace('l', 'y')
console.log(emailReplace)
Será mostrado no console: yaracroft@rogermelo.com.br

Substituição de uma string por outra.
Exemplo:
const emailReplace = email.replace('laracroft', 'chun-li')
console.log(emailReplace)
Será mostrado no console: chun-li@rogermelo.com.br
Este método não modifica a string original.

**Comment by Roger-Melo** [comment]
Show, @Jansen-Muniz! Lembre-se: o faixa preta é o faixa branca que não desistiu. Rumo à fluência! 🔥
