### ISSUE TITLE
método replace dentro ou fora da template string.

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2168]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 03 - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/748311

### Descreva a dúvida

Boa noite professor, é só uma duvida sobre um trecho do código que foi corrigido. 
Vamos lá. No exercício 11, foi pedido varias coisas, entre elas tinha que substituir uma string por outra, então foi usado o método REPLACE. Eu resolvi de uma forma ligeiramente diferente da sua.

Irei mostrar primeiro como você solucionou. 
```js
const dessert = `${dogNames[0].slice(3)}${dogNames[1].slice(2)}${dogNames[3].slice(2)}`.replace('n', 'd')
```
Esse foi o jeito que fiz:
```js
const dessert = `${dogNames[0].slice(3)}${dogNames[1].slice(2)}${dogNames[3].slice(2).replace('n', 'd')}`
```
Como disse a diferença é bem pequena. Você adicionou o método REPLACE após a template String. Já eu coloquei logo após o método SLICE. 

Gostaria de saber se tem algo de errado? , ou se é apenas uma forma diferente para o mesmo resultado? , ou se a forma que eu fiz poderia gerar algum problema para o código.

Como disse, a dúvida é simples.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103!

Neste caso, qualquer uma das duas formas é válida =)

O que vc precisa ficar ligado ao usar o método `replace` é se a expressão no qual a invocação dele foi encadeada resulta em uma string. 

Como nos dois exemplos acima, as expressões que vem antes de `.replace('n', 'd')` resultam em strings, as duas formas são válidas =)

Sacou a ideia?

**Comment by Jonatan1103** [comment]
Entendi sim. Muito obrigado.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
