### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by brunaribeiro89** [roger-melo-treinamentos/curso-de-js-roger-melo#2172]
declarando const:
const postTitle = 'é bolacha ou biscoito'
const postAuthor = 'Matheus Pereira'
const postComments = 15

Usando Concatenação:
const postMessage = ' O post ' + postTitle + ' do ' + postAuthor + ' teve ' + postComments + ' comentários '

Usando Template Strings:
const postMessage = ` O  post ${postTitle}, do ${postAuthor}, teve ${postComments} comentários.`

Usando Template HTML:

const html = `<h2>${postTitle}`</h2>
                     <p>Autor : ${postAuthor}</p>
                     <p>Comentários : ${postComments}</p>

**Comment by Roger-Melo** [comment]
Excelente, @brunaribeiro89! Só não chega lá quem desiste. Rumo à fluência! 🔥
