### ISSUE TITLE
Resumo da Aula Método forEach e callbacks 02-04 da etapa 03

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2175]
**Funções de callbacks** ou simplesmente **calbacks** – são funções passadas como argumento em outras funções.

Exemplo:
```js
const myFunc = callback => { // parâmetro aqui chamado 'callback' é uma function
    const value == 77
    callback(value)
}
myFunc(number => {
console.log(number)
})
```

Porque receberá uma função, o parâmetro **callback** é invocado dentro de **myFunc**.

Ao invocarmos o **myFunc**, precisamos especificar um parâmetro, pois **callback** possui um argumento. A função dentro de **myFunc** foi atribuída ao parâmetro **callback**, que está sendo invocado dentro da própria **myFunc**.

**.forEach()** -  é um método que requer uma _função callback_ e permite realizar uma dada ação iterando com cada item de um array, para isto, necessita de uma função como argumento. Pode receber 3 parâmetros: o que representa o item atual que está sendo iterado, o que representa o index do item atual e o array que está sendo iterado. Todos estes parâmetros devem ir dentro dos parênteses da _callback_.

```js
nome_do_array.forEach( (item_atual, indice_atual, array) =>{
	bloco de instruções
})
```

A função declarada e passada como argumento pode ser alocada em uma variável, para então ser referenciada dentro de `.forEach()`. Ex:

```js

const func = (item_atual, indice_atual, array) =>{
	bloco de instruções
}
nome_do_array.forEach(func)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente, @Kmkery! Só não chega lá quem desiste. Rumo à fluência! 🔥
