### ISSUE TITLE
Aplicação: [Currency Convert]

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2183]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuFML/currency-converter

### Maiores dificuldades durante a implementação

Quando tem muitos campos para manipular e mostrar diferentes valores as vezes me confundo.

### Menores dificuldades durante a implementação

- Referenciar/Manipular Elementos através do DOM
- Fetch
- Condicional

**Comment by Roger-Melo** [comment]
Olá @JuFML.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuFML!

Parabéns pelo esforço em construir mais essa aplicação do treinamento =)

> ### Quando tem muitos campos para manipular e mostrar diferentes valores as vezes me confundo.

Essa aplicação tem várias atualizações de interface que devem ser desencadeadas à partir de modificações em inputs. Eu considero que focar em um input por vez é algo importante para implementá-la de forma mais tranquila.

Você conseguiu implementar e parece ter entendido bastante da lógica dela. 

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Organização de código

### Nomes de variáveis e funções

Acho que na `valuePrecionEl` vc quiz que ela se chamasse `valuePrecisionEl`. 

```javascript
// antes
const valuePrecionEl = document.querySelector('...')
```

```javascript
// depois
const valuePrecisionEl = document.querySelector('...')
```

Pra ficar mais fácil renomear, na declaração da const, com o cursor de texto no nome, pressione `F2` e renomeie. Todas as ocorrências da variável na aplicação serão renomeadas automaticamente.

Para deixar o parâmetro `getURL` mais simples, eu o nomearia apenas como `currency`.

```javascript
// antes
const getURL = (currencyOneSelected) => `...`
```

```javascript
// depois
const getURL = (currency) => `...`
```

### Consistência de code styling

Algumas arrow functions com apenas 1 parâmetro estão com o parâmetro entre parênteses e outras não.

Exemplo:

```javascript
// essas estão com o parâmetro sem parênteses
const getErrormessage = errorType => ({})
const getOptions = selectedCurrency => {}

currency => `<option ${currency === selectedCurrency ? 'selected' : ''}>${currency}</option>`)
```

```javascript
// essas estão com o parâmetro com parênteses
currencyOneEl.addEventListener('input', async (e) => {})
const fetchExchangeRate = async (url) => {}
```

Isso causa uma inconsistência no estilo de código adotado. Escolha uma das duas formas e seja consistente nessa escolha no decorrer da aplicação.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu eliminaria as seguintes linhas:

- 90 e 91
- 87
- 72
- 58
- 52

### Variáveis não utilizadas

A const `APIKey` pode ser usada ao invés da inserção da chave de forma estática:

```javascript
// antes
const getURL = (currency) => `https://v6.exchangerate-api.com/v6/daf56443438702dca1f50f2f/...`
```

```javascript
// depois
const getURL = (currency) => `https://v6.exchangerate-api.com/v6/${APIKey}/...`
```

A const `currencyOneValue` dentro do callback de evento da `currencyOneEl` não está sendo usada, então vc pode remover ela ou ver se ela será usada.

## Lógica

Nos códigos abaixo,

```javascript
const init = async () => {
  // ...
  internalExchangeRate = { ... exchangeRateData}
  // ...
}
```

```javascript
currencyOneEl.addEventListener('input', async (e) => {
  // ...
  internalExchangeRate = {...(await fetchExchangeRate(getURL(currencyOneSelected)))}
  // ...
})
```

a criação de um novo objeto e o espalhamento das propriedades é desnecessário. Fiz pela força do hábito, mas se `exchangeRateData` já é um objeto, neste caso, era só fazer como abaixo: 

```javascript
const init = async () => {
  // ...
  internalExchangeRate = exchangeRateData
  // ...
}
```

```javascript
currencyOneEl.addEventListener('input', async (e) => {
  // ...
  internalExchangeRate = await fetchExchangeRate(getURL(currencyOneSelected))
  // ...
})
```

Ah, e cuidado com o espaço em branco entre o spread e `exchangeRateData`. Mesmo que tenha funcionado, o ideal é sempre manter o padrão (sem espaço em branco) para que a leitura do código fique mais fluida.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Inclusive, aprenderá por que e como diminuir variáveis globais desnecessárias.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JuFML** [comment]
Obrigada!
