### ISSUE TITLE
Dúvida sobre objeto modficado

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#2189]
### Etapa da aula

8

### Nome da aula

O método map( ) - Aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986668

### Descreva a dúvida

Boa tarde professor,

Para criar uma nova array cujos itens são objetos foi feito o seguinte (gerando novo objeto que será retornado):

```js
const saleProducts = products.map(( product) => {
  if(product.price >= 30) {
    return {
      name: product.name, 
      price: product.price / 2
    } 
  }
  return product 
})
```

O método map( ) não modificou a array original, mas não ficou muito claro pra mim porque  o objeto dentro da array original é modificada se fizermos assim:

```js
const saleProducts= products.map((product) => {
  if(product.price >= 30) {
    product.price = product.price / 2
  }
  return product
}) 
console.log(saleProducts)
// 0: {name: 'Mouse Sem Fio', price: 15}
// 1: {name: 'Pen Drive', price: 25}
// 2: {name: 'Cartucho de Tinta', price: 25}
// 3: {name: 'Suporte Ergonômico para Notebook', price: 23}
// 4: {name: 'Repetidor de Sinal Wi-Fi', price: 22}
console.log(products)
// 0: {name: 'Mouse Sem Fio', price: 15}
// 1: {name: 'Pen Drive', price: 25}
// 2: {name: 'Cartucho de Tinta', price: 25}
// 3: {name: 'Suporte Ergonômico para Notebook', price: 23}
// 4: {name: 'Repetidor de Sinal Wi-Fi', price: 22}

``` 
Enquanto uma array de números não é modifica se fizermos:
```js
const numbers = [1, 2, 3] 
const doubleNumbers = numbers.map((item) => {
return  item * 2
}) 
console.log(doubleNumbers)
// [2 ,4, 6]

console.log(numbers) 
//[1, 2, 3]
```
Tipo, o map de numbers retorna o próprio item * 2 e não modifica a array original, já na array de objetos é preciso gerar um novo objeto que será retornado.
 
Obrigada desde já!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

> ### O método map( ) não modificou a array original, mas não ficou muito claro pra mim porque  o objeto dentro da array original é modificada se fizermos assim

Isso acontece por que objetos são tipos de referência. 

Ou seja, o parâmetro `product` está apenas referenciando um objeto do array. 

```javascript
const products = [
  { name: 'Mouse sem fio', price: 30 }
]

const result = products.map(product => {
  // ...
})
```

No código acima, o parâmetro `product` não recebeu uma cópia do objeto. 

Na real, `product` apenas referencia o objeto que está dentro do array.

Você pode comprovar isso verificando se `product` e `products[0]` referenciam o mesmo objeto em memória:

```javascript
const result = products.map(product => {
  console.log(product === products[0]) // true
})
```

O resultado da comparação é `true`, então tanto `product` como `products[0]` apontam pro mesmo objeto.

Isso significa que esse mesmo objeto pode ser manipulado através de `product` ou de `products[0]`.

Uma coisa a se atentar é que `product` é um parâmetro e parâmetros são variáveis. 

Então por baixo dos panos, é como se isso estivesse acontecendo:

```javascript
const product = products[0]
```

No código acima, `product` não recebeu uma cópia do objeto do array. O que aconteceu é que agora, `products[0]` e `product` resultam no mesmo objeto em memória.

---

> ### Enquanto uma array de números não é modifica se fizermos:

Números são tipos primitivos.

Tipos primitivos são criados em posições diferentes na memória. Por isso, ao contrário de objetos, quando estiver lidando com um parâmetro que recebe um tipo primitivo, vc pode confiar que aquele valor é imutável.

Dá uma olhada novamente na aula em que esse conceito é apresentado e se restar qualquer dúvida, pode dar o toque aqui que te ajudo a entender =)

- [Tipos de refêrencia vs Tipos primitivos - Aula 03-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/831889).

**Comment by ElaineDelgado** [comment]
Eu tinha re-assistido essa aula Tipo de referência vs Tipo primitivos (intuição, talvez? alguma coisa na minha cabeça fez eu lembrar essa aula e quer ver de novo e ler as anotações q fiz!) antes da aula do map(), só que eu não tinha certeza que no map a resposta para minha dúvida era por causa do tipo de dado, cheguei a cogitar mas achei melhor perguntar para ter certeza!!
"Uma coisa a se atentar é que product é um parâmetro e parâmetros são variáveis." isso faz todo sentido agora.
Muito obrigada, agora ficou bem claro pra mim que o tipo de dado passado por parâmetro faz toda diferença.
Obrigada!!

**Comment by Roger-Melo** [comment]
Excelente 🎉

Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
