### ISSUE TITLE
Cadeia de funções

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2199]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986667

### Descreva a dúvida

Boa noite, Roger! Havia acabado de terminar o Quiz 2.0 que estava fazendo e tive uma pequena dúvida. Quando há várias funções a serem invocadas e todas elas possuem algo em comum, não seria mais prático criar uma cadeia de funções?

No caso, eu pensei em colocar as invocações das funções logUserScore() e logScoreColor() dentro da função showUserScore(). Assim:

```js
const showUserScore = () => {
  scrollTo({
    top: 0,
    left: 0,
    behavior: 'smooth'
  })

  resultScoreContainer.classList.remove('d-none')

 logUserScore()
 logScoreColor()
}

form.addEventListener('submit', event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  calculateUserScore(userAnswers)
  showUserScore()
})
```

Abaixo, disponibilizarei o link do Github que direciona à aplicação. =)

https://github.com/YureK-a/Meu-portfolio/tree/main/Quiz

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

> ### Quando há várias funções a serem invocadas e todas elas possuem algo em comum, não seria mais prático criar uma cadeia de funções?

Claro, é uma outra forma válida tb =)

---

Tem umas paradas que vc pode ajustar em seu código pra deixar ele mais elegante, olha só...

```javascript
const [badResultColor, medianResultColor, goodResultColor] = [
  '#FF0000',
  '#FFFF00',
  '#009900'
]
```

O código acima, tem dois pontos importantes para analisar. 

O primeiro é que como as consts criadas no destructuring estão sendo usadas apenas dentro da função `logScoreColor`, faria mais sentido que elas fossem criadas perto de onde são usadas, ao invés de estarem declaradas no escopo global.

O segundo ponto é que o "malabarismo" com destructuring pode ser substituído por um código mais funcional. 

Dá uma olhada na parte de refatoração [dessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1878#issuecomment-927120321) que fiz. Acho que o design de código que exemplifiquei pode te dar uma luz. 

---

Um outro ponto é que você deve evitar isso:

```javascript
score > 50
  ? insertColorIntoScore(goodResultColor)
  : insertColorIntoScore(badResultColor)
```

Ternários não devem ser usados para executar efeito colateral. Eu expliquei o por que disso no tópico `Ternário` [dessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1496#issuecomment-898931419) da sua versão da weather application. Então cuidado para não repetir os mesmos erros =)

E claro, se tiver alguma dúvida em qualquer coisa que eu disse ou referenciei acima, pode comentar aqui nessa issue =)

**Comment by YureK-a** [comment]
Olá! Tentei as duas formas:

```js

//Criando um objeto colors;

const colors = {
  badResult: '#FF0000',
  medianResult: '#FFFF00',
  goodResult: '#009900'
}

const logScoreColor = ({ badResult,medianResult, goodResult }) => {
  if (score === 50) {
    insertColorIntoScore(medianResult)

    return
  }

  if (score > 50) {
    insertColorIntoScore(goodResult)

    return
  }

  insertColorIntoScore(badResult)
}

//Fazendo conforme o exemplo(fiquei um pouco perdido);

const insertColorIntoScore = ({ scoreColor }) => scoreCounter.setAttribute('class', scoreColor)

const logScoreColor = () => {
  if (score === 50) {
    insertColorIntoScore({scoreColor: 'text-warning'})

    return
  }

  if (score > 50) {
    insertColorIntoScore({scoreColor: 'text-success'})

    return
  }

  insertColorIntoScore({scoreColor: 'text-danger'})
}

```

Eu não sei o por quê, mas o texto da div Result sai muito pequeno. No mais, acho que vou optar por criar um objeto colors, me parece um pouco melhor de ler =)

**Comment by Roger-Melo** [comment]
Na real, vc pode implementar uma função que, baseando-se na pontuação, retorna apenas a cor:

```javascript
const getScoreColor = score => ({
  50: 'color 2',
  75: 'color 3',
  100: 'color 4',
})[score] || 'color 1'

const possibleScores = [0, 25, 50, 75, 100]

possibleScores.forEach(score => console.log(getScoreColor(score)))
/*
'color 1'
'color 1'
'color 2'
'color 3'
'color 4'
*/
```

Sacou a ideia?

Outro ponto de atenção do código anterior é que `logScoreColor` está sendo invocada dentro de `logUserScore`, então não é necessário invocá-la também no callback do `addEventListener` do `form`:

```javascript
const logUserScore = () => {
  // ...

  // 👇🏻 essa invocação elimina a necessidade da invocação ali em baixo
  logScoreColor()
}

form.addEventListener('submit', event => {
  // ...

  logUserScore()
  // 👇🏻 essa invocação pode ser removida, pois a invocação da logUserScore já invoca logScoreColor
  logScoreColor()
// ...
})
```

Faz sentido?

> ### Eu não sei o por quê, mas o texto da div Result sai muito pequeno no segundo caso.

O `setAttribute` está removendo as classes CSS que setam o `span`. 

Você lembra como evitar isso?

@YureK-a

**Comment by YureK-a** [comment]
Para evitar a remoção de classes, eu pensei nisso: 

```js
const getScoreColor = score => ({
  50: '#FFFF00',
  75: '#00FF00',
  100: '#00FF00',
})[score] || '#FF0000'

const insertColorIntoScore = () => {
  const scoreColor = getScoreColor(score)

  scoreCounter.style.color = scoreColor
}
```

Eu não consegui pensar em algo melhor do que usar o style.color, considerando que usar .classList.add() não funcionaria corretamente se o usuário enviasse várias respostas com resultados diferentes. O toggle não funciona também, pelo que eu vi.

E uma pequena observação: caso resultados como 51 sejam adicionados no futuro, eu vou ter problemas para usar a getScoreColor, pois ela só funciona se todos os casos possíveis sejam adicionados. Portanto, talvez seja melhor usar os ifs mesmo. Obviamente posso estar enganado =)

**Comment by Roger-Melo** [comment]
> ### //A insertColorIntoScore elimina a necessidade de usar ifs

Na real, a função que contém a lógica semelhante à de usar ifs é a `getScoreColor`, pq ela verifica um valor e faz algo baseado nesse valor (retorno) =)

A `insertColorIntoScore` só insere a cor no elemento.

---

> ### E uma pequena observação: caso resultados como 51 sejam adicionados no futuro, eu vou ter problemas para usar a getScoreColor, pois ela só funciona se todos os casos possíveis sejam adicionados. Portanto, talvez seja melhor usar os ifs mesmo. Obviamente posso estar enganado =)

Basta adicionar uma propriedade `51` no objeto.

---

> ### Para evitar a remoção de classes, eu pensei nisso

Sim. Essa é uma forma de resolver.

Se quiser evitar adicionar estilo CSS inline, vc pode usar classes. Nesse caso, o `setAttribute` pode ser útil. 

Exemplo simples:

```css
.blue {
  color: blue;
}

.red {
  color: red;
}
```

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
  <link rel="stylesheet" href="./style.css">
</head>
<body>
  <p class="class1 class2">My paragraph</p>

  <button data-js="blue">Add blue</button>
  <button data-js="red">Add red</button>
  
  <script src="./app.js"></script>
</body>
</html>
```

```javascript
const p = document.querySelector('p')
const buttonAddBlue = document.querySelector('[data-js="blue"]')
const buttonAddRed = document.querySelector('[data-js="red"]')

const getScoreColor = score => ({
  50: 'blue',
  75: 'red'
})[score]

const pClasses = Array.from(p.classList).join(' ')

buttonAddBlue.addEventListener('click', () => {
  p.setAttribute('class', `${pClasses} ${getScoreColor(50)}`)
})

buttonAddRed.addEventListener('click', () => {
  p.setAttribute('class', `${pClasses} ${getScoreColor(75)}`)
})
```

**Comment by YureK-a** [comment]
Compreendi. Muito obrigado pela ajuda! =)
