### ISSUE TITLE
Rolagem do exercício Quiz

### ISSUE THREAD

**Issue by carlosweb** [roger-melo-treinamentos/curso-de-js-roger-melo#22]
Opa, boa noite professor! O curso esta sendo ótimo pois estou realmente aprendendo mais a fundo com tudo funciona.
Sobre o Exercício do Quiz na propriedade 

scrollTo({
        top: 0,
        left: 0,
        behavior: 'smooth'
    })

No firefox ele faz a rolagem smooth mas, no IE10 e no Chrome não rolou...
tem outros códigos que fazem da certo mais gostaria de saber nesse caso mais simples do quiz.

Abraço.

**Comment by Roger-Melo** [comment]
Oi @carlosweb.

A rolagem realmente não está suave. Abri uma issue no suporte do chrome e uma no repo do mdn avisando que talvez seja preciso mudar a compatibilidade entre os browsers que eles exibem.

Qual alternativa você encontrou?

**Comment by carlosweb** [comment]
Apliquei esse código em um projeto e depois utilizei com o "to" trecho do código abaixo:


function scrollToId(e) {
    const menu = document.querySelector('.menu')
    e.preventDefault()
    const to = getScrollTopByHref(e.target) - 80
    scrollToPosition(to)
    menu.classList.remove("change")
  }

  // get position
  function scrollToPosition(to) {
    // window.scroll( {
    //   top: to,
    //   behavior: "smooth",
    // })
    smoothScrollTo(0, to)
  }

  // get href
  function getScrollTopByHref(element) {
    const id = element.getAttribute('href')
    return document.querySelector(id).offsetTop
  }

  // support all old browsers 
  function smoothScrollTo(endX, endY, duration) {
    const startX = window.scrollX || window.pageXOffset;
    const startY = window.scrollY || window.pageYOffset;
    const distanceX = endX - startX;
    const distanceY = endY - startY;
    const startTime = new Date().getTime();
  
    duration = typeof duration !== 'undefined' ? duration : 400;
  
    // Easing function
    const easeInOutQuart = (time, from, distance, duration) => {
      if ((time /= duration / 2) < 1) return distance / 2 * time * time * time * time + from;
      return -distance / 2 * ((time -= 2) * time * time * time - 2) + from;
    };
  
    const timer = setInterval(() => {
      const time = new Date().getTime() - startTime;
      const newX = easeInOutQuart(time, startX, distanceX, duration);
      const newY = easeInOutQuart(time, startY, distanceY, duration);
      if (time >= duration) {
        clearInterval(timer);
      }
      window.scroll(newX, newY);
    }, 1000 / 60); // 60 fps
  };

**Comment by Roger-Melo** [comment]
Show. Por enquanto vou deixar a issue aberta, pelo-menos até obter uma resposta. 

Se surgir alguma novidade posto aqui =)
