### ISSUE TITLE
Resumo da Aula 03-03 da etapa 01 - null e undefined

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2201]
**Ambos representam a falta de um valor.**

_Diferenças_ 

**Null -**Intencionalmente atribuído.
**Undefined -**Definido pelo JavaScript 

Exemplo Undefined:
```
let emptiness
console.log(emptiness, emptiness + 3, `o valor é ${emptiness}`)
``` 
Será exibido: _undefined_(não foi atribuído um valor a variável), _NaN_(quando fazemos uma operação aritmética com undefined, por isso Not a Number), _"o valor é undefined"_ (empitness foi usado numa string).  

Exemplo Null:
```
let emptiness = null
console.log(emptiness, empitness + 3, `o valor é ${emptiness}`)
``` 
Será exibido: _null_, _3_(pois null é entendido como 0), _"o valor é null"_ (empitness foi usado numa string).

**Comment by Roger-Melo** [comment]
Excelente, @Jansen-Muniz! Só não chega lá quem desiste. Rumo à fluência! 🔥
