### ISSUE TITLE
Resumo da Aula O que é o DOM - Document Object Model 01-06 da etapa 05

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2217]
O **DOM** é a interface criada pelo browser que possibilita interagir com o documento HTML. Quando o HTML é carregado, o browser cria um objeto que o modela (objeto _**document**_). Este objeto possui uma série de propriedades e métodos que irão permitir a interação browser-HTML.

Utilizando o console do browser, podemos ver a estrutura do documento, que é a representação visual da página HTML.
Podemos visualizar as propriedades e métodos do objeto _document_, digitando no console `document.` e uma lista flutuante mostrará todos os recursos ligados a este objeto. E, por meio do script js linkado ao documento HTML, podemos fazer uso destes recursos.
O DOM possui uma estrutura hierárquica, que pode ser representada por uma árvore de _**nodes**_ (nós), com sua **_raiz_** e ramificações. Em uma página HTML, temos a tag _<html>_ como raiz e demais _tags_ formando as ramificações, que também podem possuir ramificações. Pela indentação, conseguimos visualizar a hierarquia.
```js
<html>
    <head>
        <meta>
        <title></title>
    </head>
        <body>
            <div>
                <h1></h1>
                <p></p>
            </div>
        </body>
</html>
```

Usando a referência dos nós, podemos acessar e manipular estes elementos, aplicando os métodos e propriedades disponíveis ao objeto _document_.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery! Rumo à fluência 🔥
