### ISSUE TITLE
Resumo da Aula Event Bubbling e Event Delegation Aula 04-02 da etapa 05

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2218]
https://github.com/marcosyoggy/Resumo-Event-Bubbling-e-Delegation-Aula-04-02-E05 

https://resumo-event-bubbling-e-delegation-aula-04-02-e05.netlify.app

**Comment by Roger-Melo** [comment]
Boa @marcosyoggy! Rumo à fluência 🔥
