### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by lpf-developer** [roger-melo-treinamentos/curso-de-js-roger-melo#2219]
NULL e UNDEFINED

`Null` e `undefined`, são dois tipos de valores que podem ser atribuídos à variáveis. 
`Undefined` é um valor atribuído automaticamente, quando uma variável é declarada sem uma atribuição de valor.
`Undefined` não é atribuído à constantes, pois constantes devem, obrigatoriamente, possuir um valor inicial.
`Null` é um valor que pode ser atribuído pelo usuário à variáveis e constantes quando declaradas.

```javascript
// Null e Undefined

let undefinedValue;
console.log(undefinedValue) // undefined

let nullValue = null
console.log(nullValue) // null

//const valorIndefinido;
const valorNulo = null;
console.log(valorNulo)
```

**Comment by Roger-Melo** [comment]
Boa @lpf-developer! Rumo à fluência 🔥
