### ISSUE TITLE
duvida acerca de um boolean que retorna se um objeto é um objeto

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2220]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

a questão pede:
  06

  - Crie uma função que retorna um boolean indicando se um valor recebido por  
    parâmetro é um objeto;
  - Utilize a função para exibir no console se "cat" é um objeto.

```js
const cat = {
    name: 'floquinho',
    age: 2,
    color: 'cinza',
    bestFriends: ['mãe de mika', 'almofada'],
    sound: function () {
        return '...'
    }
}
```

minha resolução foi:

```js
isObject = (object = Object) => typeof object === 'object'

console.log(isObject(cat))
```

funcionou, porém quando testei outros dados me deparo com isso:

![exercicio 6](https://user-images.githubusercontent.com/85198581/141842823-4aa4f31e-e04a-4516-b077-5ac8f91e0f9d.jpg)

queria entender porque quando passo um array por argumento, ele me retorna true

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

Em JavaScript, tecnicamente não existem arrays, apenas objetos. Isso será mostrado na etapa 14, não foque nisso agora.

Em etapas mais avançadas do treinamento, também vou mostrar formas mais seguras de testar se o valor é um objeto ou array =)

Pode me tirar duas dúvidas?

1) A função `isObject` foi declarada sem a palavra-chave const?

2) O que vc espera que aconteça atribuindo `Object` como default parameter?

**Comment by CarlosHenrique2208** [comment]
1- eu vivo esquecendo de colocar a palavra chave const, e como o console não mostra nenhum erro isso só impulsiona essa falta de atenção. 

2- eu achei que atribuindo a função construtora fizesse o JS ver que só pudesse executar o codigo se fosse um objeto. Coloquei pois achei que seria mais especifico pro JS ler e ver que eu somente queria um objeto("tentei ser redundante de proposito")

**Comment by Roger-Melo** [comment]
> ### 1- eu vivo esquecendo de colocar a palavra chave const, e como o console não mostra nenhum erro isso só impulsiona essa falta de atenção. 

Nunca declare consts ou lets sem as palavras-chave `const` ou `let`, pois isso pendura uma variável global no objeto `window`  (é como se `var` tivesse sendo usado):

```javascript
myFunc = () => 'abc'

console.log(window.myFunc) // () => 'abc'
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

Você vai ver sobre isso na etapa 5, mas é bom já ficar ligado.

---

> ### 2- eu achei que atribuindo a função construtora fizesse o JS ver que só pudesse executar o codigo se fosse um objeto. Coloquei pois achei que seria mais especifico pro JS ler e ver que eu somente queria um objeto("tentei ser redundante de proposito")

Não faz sentido atribuir um constructor com a intenção de que por baixo dos panos o JS faça coerção para objeto.

Se vc quer que o default parameter seja um objeto, atribua um objeto:

```javascript
const x = (obj = { a: 1, b: 2 }) => { ... }
```

Constructors são mostrados na etapa 14, então vc viu algo fora do treinamento e tentou encaixar. É o mesmo que seguir duas dietas ao mesmo tempo. Não dá muito resultado. 

Se vc realmente quer chegar na fluência, recomendo que foque no CJRM e siga à risca o passo a passo que falei [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928).

@CarlosHenrique2208

**Comment by CarlosHenrique2208** [comment]
tá certo...
obrigado professor.
