### ISSUE TITLE
Resumo das Aula 02 da etapa 03

### ISSUE THREAD

**Issue by HenriqueAnraki** [roger-melo-treinamentos/curso-de-js-roger-melo#2221]
## Aula 02-02 - Arrow Functions

- Forma mais curta e concisa de funções
- `() ⇒ {}`
    - Casos:
        - 1 Parâmetro ⇒ sem necessidade de ()
            - Não funciona com valor default
        - 1 única expressão de **return** ⇒ sem necessidade de {} e de return
- Diferença importante:
    - Binding do `this`
        - Veremos mais à frente no curso

## Aula 02-03 - Funções vs Métodos

- Funções
    - bloco de código que executam uma ação
    - podem ser invocadas em qualquer ponto no código
- Métodos
    - São funções
        - Associadas a um objeto ou tipos de dados
    - Diferenças:
        - método de invocação
            - **notação de ponto**
                - ex: name.toUpperCase()
        - lugar onde é declarado
            - São criadas no objeto ou em no tipo de dados em si

## Aula 02-04 - O método forEach e callbacks

- callback
    - Funções passadas como argumentos para outras funções/métodos
    
    ```jsx
    const myFun = callback = {
    	const value = 77
    
    	callback(value)
    }
    
    myFunc(number => {
    	console.log(number)
    })
    ```
    
    - Funções de callback recebem a declaração de uma função
- **.forEach()**
    - Método de iteração sobre um array
        - Executa a função de callback para cada elemento
    - Recebe uma função de callback como argumento
        - Essa função pode receber 3 argumentos opcionais:
            - o elemento atual
            - o índice do elemento atual
            - e o array sendo iterado
    - A declaração da função pode ser desacoplada

**Comment by Roger-Melo** [comment]
Boa @HenriqueAnraki! Rumo à fluência 🔥
