### ISSUE TITLE
duvida acerca do uso do this

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2222]
### Etapa da aula

4

### Nome da aula

  A palavra-chave this - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824589

### Descreva a dúvida

só queria entender no que interfere trocar o uso de referencia com o _**proprio nome do objt**_ para o uso de referencia com a palavra chave **_this_**

```js
let user = {
  name: 'João',
  age: 31,
  email: 'joãocardoso@gmail.com', 
  city: 'São Paulo', 
  blogPosts: ['Empadão de frango', '4 receitas de purê de batata'],
  login: function() {
    console.log('Usuário logado')
  },
  logout: function () {
    console.log('Usuário deslogado')
  },
  logBlogPosts: function () {
    console.log(`${user.name} escreveu os seguintes posts:`)

    user.blogPosts.forEach(post => {
      console.log(post)
    })
  }
}

user.logBlogPosts()
```

```js
let user = {
  name: 'João',
  age: 31,
  email: 'joãocardoso@gmail.com', 
  city: 'São Paulo', 
  blogPosts: ['Empadão de frango', '4 receitas de purê de batata'],
  login: function() {
    console.log('Usuário logado')
  },
  logout: function () {
    console.log('Usuário deslogado')
  },
  logBlogPosts: function () {
    console.log(`${this.name} escreveu os seguintes posts:`)

    this.blogPosts.forEach(post => {
      console.log(post)
    })
  }
}

user.logBlogPosts()
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
@CarlosHenrique2208 dá uma olhada [nessa resposta](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/730#issuecomment-849873259) e, se ainda restar qualquer dúvida, pode chamar aqui =)

**Comment by CarlosHenrique2208** [comment]
obrigado professor!!

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
