### ISSUE TITLE
Resumo da Aula Lendo dados do Firestore - Aula 01-13 da etapa 15

### ISSUE THREAD

**Issue by JuFML** [roger-melo-treinamentos/curso-de-js-roger-melo#2223]
# Lendo dados do Firestore

```jsx
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-app.js"
import { getFirestore, collection, getDocs } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-firestore.js"

const firebaseConfig = {
	apiKey: "Aojaoijaijiajoajijaijaiojaoijaiojiajikja",
	authDomain: "testing-firebase-87a03.fiurebaseapp.com",
	projectId: "testng-firebase-87a03",
	storageBucket: "testng-firebase-87a03.appspot.com",
	messageingSenderId: "654684416515646548648",
	appId: "1:65465468465:web:654648484654151465454",
	measurementId: "G-6YWERLYEBT"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)
const collectionGames = collection(db, 'games')
getDocs(collectionGames)
```

Para obter e ler os dados que o banco de dados está armazenando eu vou precisar lidar com a const db que armazena os dados do meu banco de dados.

A função para pegar as collections do meu firestore é a collection(db, 'games') passando como primeiro argumento o nome da variável que contém o meu banco de dados e como segundo argumento o nome da minha collection. Mas para usar esta função é necessário importá-la do Firestore.

Agora que eu obti a referência do collection "games" eu posso obter, adicionar e deletar documents no banco. 

Para obter os documents basta usarmos a função getDocs  (tbm importando ela do SDK do Firestore) passando como argumento a collection em que os documents estão. A invocação desta getDocs retorna uma promisse, para visualizar o valor que esta promisse está encapsulando a gente encadeia um then com uma função de callback dentro que so vai ser executada quando o request for completado com sucesso, vai receber como parâmetro um querySnapshot (que é uma fotografia de como o collection game está no momento em que o request foi executado) este querySnapshot é um objeto que dentro dele possui um parâmetro docs que é um array que contém todos os documents que aquele collection tem, e para mostrar cada um destes documents podemos usar os mètodos de array que temos disponíveis. Cada document possui um método data( ) onde ficam armazenadas as informações de cada document.

Agora se o request não for completado com sucesso logo abaixo a gente encadeia um catch que tbm terá um callback que recebe um objeto de erro como argumento e a gente dá um console.log para visualizar este erro.

```jsx
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-app.js"
import { getFirestore, collection, getDocs } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-firestore.js"

const firebaseConfig = {
	apiKey: "Aojaoijaijiajoajijaijaiojaoijaiojiajikja",
	authDomain: "testing-firebase-87a03.fiurebaseapp.com",
	projectId: "testng-firebase-87a03",
	storageBucket: "testng-firebase-87a03.appspot.com",
	messageingSenderId: "654684416515646548648",
	appId: "1:65465468465:web:654648484654151465454",
	measurementId: "G-6YWERLYEBT"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)
const collectionGames = collection(db, 'games')
getDocs(collectionGames)
	.then(querySnapshot => {
		querySnapshot.docs.forEach{doc => console.log (doc.data())}	
	})
	.catch(error => console.log(error))
```

Para mostrar estas informações no HTML por exemplo podemos usar o método reduce ao invés do forEach armazenar o retorno do acc na const gameLis e atribuir este gameLis ao innerHTML da tag HTML que vai conter estas informações que serãopuxadas do banco.

O valor da propriedade createdAt  não está em formato de data, desta forma encadeamo nesta propriedade o método toDate( ) para transformar esta informação em data (como nos queremos).

```jsx
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-app.js"
import { getFirestore, collection, getDocs } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-firestore.js"

const firebaseConfig = {
	apiKey: "Aojaoijaijiajoajijaijaiojaoijaiojiajikja",
	authDomain: "testing-firebase-87a03.fiurebaseapp.com",
	projectId: "testng-firebase-87a03",
	storageBucket: "testng-firebase-87a03.appspot.com",
	messageingSenderId: "654684416515646548648",
	appId: "1:65465468465:web:654648484654151465454",
	measurementId: "G-6YWERLYEBT"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)
const collectionGames = collection(db, 'games')

getDocs(collectionGames)
	.then(querySnapshot => {
		const gameLis = querySnapshot.docs.reduce((acc, doc) => {
			const { title, developedBy, createdAt } = docs.data()
			acc += `<li>
				<h5>${title}</h5>
				<ul>
					<li>Desenvolvido por ${developedBy}</li>
					<li>Adicionado no banco em ${createdAt.toDate()}</li>
				</ul>
			
			</li>`
			return acc
	}, '')

	const gameslist = document.querySelector('[data-js = "game-list"]')
	gameslist.innerHTML = gameLis
	.catch(error => console.log(error))
```

**Comment by Roger-Melo** [comment]
Boa @JuFML! Rumo à fluência 🔥
