### ISSUE TITLE
Curiosidade sobre o Javascript

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2224]
### Etapa da aula

1

### Nome da aula

Aula introdutória

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928?utm_source=ActiveCampaign&utm_medium=email&utm_content=%5BAlunos+CJRM%5D+Atualiza%C3%A7%C3%A3o+da+aula+inaugural+%F0%9F%91%80&utm_campaign=%5Blaunch-out-2021%5D+%5BAlunos+CJRM%5D+Atualiza%C3%A7%C3%A3o+da+aula+inaugural+%3F

### Descreva a dúvida

Por que no javascript no final de cada linha de código não precisa colocar o ponto e vírgula?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz!

Na real, é questão de gosto. 

Não há problema em não utilizar ponto e vírgula no JS, pois ele tem uma feature chamada [ASI - Automatic Semicolon Insertion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion) - ou inserção automática de ponto e vírgula. Ele faz isso em vários casos e, existem alguns poucos casos em que não usar ponto e vírgula pode ser um problema, que seria iniciar uma nova linha com (, [ ou `.

Prefiro não ensinar usando ponto e vírgula para não colocar mais problemas na cabeça do aluno. 

Quando ele está em um nível mais avançado, aí falo sobre e ele decide se vai usar ou não =)

**Comment by Jansen-Muniz** [comment]
Valeu @Roger-Melo ✌🏻😁

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
