### ISSUE TITLE
Resumo da Aula inaugural da etapa 00

### ISSUE THREAD

**Issue by Vent7** [roger-melo-treinamentos/curso-de-js-roger-melo#2238]
Ser consistente e focado para atingir os meus objetivos.

Focar no CJRM para atingir cada Marco e chegar na fluência.

![image](https://user-images.githubusercontent.com/89490149/142082567-b89bb054-9526-4a9d-9e47-e4410f8d0e35.png)

**Comment by Roger-Melo** [comment]
Boa @Vent7! Rumo à fluência 🔥
