### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by brunaribeiro89** [roger-melo-treinamentos/curso-de-js-roger-melo#2245]
'igual a ' e 'diferente de'

const age = 32
console.log(age == 32)
console.log(age == '32')
console.log(age != 32)
console.log(age != '32')

'igual a, e do mesmo tipo' e 'diferente de, e do mesmo tipo'

console.log( age === 32)
console.log(age === '32')
console.log(age !== 32)
console.log(age !== '32')

**Comment by Roger-Melo** [comment]
Boa @brunaribeiro89! Rumo à fluência 🔥
