### ISSUE TITLE
Etapa 05, nome do vídeo: Desenvolvendo um popup - Aula 04-04

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#225]
Olá, Roger. 

Sobre essa aula ensinando a desenvolver um popup achei muito interessante a implementação, mas fiquei com uma dúvida: 

Imaginando um cenário onde eu tivesse mais de um popup na página e eu tivesse elementos diferentes para abrir esses popups, como botões por exemplo. Nesse caso você acha que é válido recuperar a referência de todos os botões e usar um forEach para adcionar um evento em cada um deles, ou é melhor adicionar o evento no documento todo e então verificar se o clique foi no botão?

Pergunto isso por que já me deparei com diversas situações onde é necessário lidar com eventos em multiplos elementos para executar uma determinada função.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

É possível fazer com o loop mas eu prefiro usar o event bubling. 

Considerando que são popups diferentes para cada botão:

```javascript
document.body.addEventListener('click', e => {
  const clickedElement = e.target

  if (clickedElement === button1) {
    showPopup1()
  }

  if (clickedElement === button2) {
    showPopup2()
  }

  // ...
})
```

Eu começaria assim e, se o código crescer, pensaria em possibilidades de abstração. Lembrando que primeiro, o mais importante é fazer funcionar.

Ficou mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Ficou sim. 

Também penso que usar o event bubling é o mais viável, porém, fiquei me perguntando se isso de alguma forma não pode prejudicar a performance? 

Já que vai ter um evento sendo monitorado na página inteira e a cada vez que um clique for feito em qualquer lugar a função é disparada.

**Comment by Roger-Melo** [comment]
Não se preocupe com performance nesse primeiro momento, @Hamiltonspjunior. Ainda há muitas outras coisas que você vai conhecer e que são prioritárias. Performance vem depois =)

**Comment by Hamiltonspjunior** [comment]
Entendido. 

Muito obrigado Roger
