### ISSUE TITLE
Aplicação: [APP-QUIZ]

### ISSUE THREAD

**Issue by gustavoalmeida82** [roger-melo-treinamentos/curso-de-js-roger-melo#2252]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/gustavoalmeida82/app-quiz.git

### Maiores dificuldades durante a implementação

Buscar as referências dos inputs. Mas, depois de quebrar a cabeça consegui lembrar.

### Menores dificuldades durante a implementação

A lógica geral do algoritmo e os passos para implementá-lo.

**Comment by Roger-Melo** [comment]
Olá @gustavoalmeida82.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @gustavoalmeida82!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Buscar as referências dos inputs. Mas, depois de quebrar a cabeça consegui lembrar.

Show. Isso acontece mesmo, nem sempre lembramos de tudo no momento. Mas ficou claro que vc entendeu bem a lógica como um todo, até aqui =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

O ideal é que o nome da aplicação (ou algo do tipo) seja exibida na guia do navegador. Você pode ajustar isso modificando o conteúdo da tag `<title>`.

Você pode deixar claro o total de perguntas que o quiz tem, ajustando a mensagem para "A sua pontuação foi 25/100" ou "Você acertou 25%" ou algo parecido. Isso é bom para a usabilidade, pq traz mais clareza do progresso do usuário no quiz.

## Organização de código

### Nomes de variáveis e funções

`paragraph` é um nome um pouco vago. Você pode deixar essa const mais específica se nomeá-la como `scoreParagraph`, por exemplo.

O mesmo vale para a função `insertParagraphIntoDOM`, pois não fica claro do que se trata o parágrafo. Além disso, se no futuro não for mais um parágrafo, o nome perde o sentido. Vc pode renomear para algo como `showScore`.

Há uma mesma coisa sendo chamada de dois nomes diferentes no código: points e score. Para manter a consistência, use apenas um dos dois.

Exemplo:

```javascript
// antes
const getUserScore = answers => {
  let points = 0

  // ...
  
  if (isAnswerCorrect) {
    points += 25
  }
  
  // ...

  return points
}
```

```javascript
// depois
const getUserScore = answers => {
  let score = 0

  // ...

  if (isAnswerCorrect) {
    score += 25
  }
  
  // ...

  return score
}
```

Alguns ajustes que podem trazer mais coerência aos nomes de suas variáveis no decorrer do código:

- O parâmetro `answers` da `getUserScore` pode ter o mesmo nome do argumento que ela recebe ao ser invocada.
- O parâmetro do callback do `forEach` pode ser nomeado como singular de itens do array no qual o `forEach` foi encadeado. Exemplo: `userAnswers.forEach(userAnswer => {})`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by gustavoalmeida82** [comment]
Sim, fizeram muito sentido. Obrigado pelo feedback.

Em qui., 18 de nov. de 2021 às 16:05, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
