### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#2257]
```js
// Function expression
const showFood = function () {
   console.log('pizza')
}
// Na function expression o JavaScript **NÃO** vai puxar a função para o topo, no hoisting

sayHi() // a função está sendo invocada antes da sua criação, mas não vai causar erro pois ela foi içada (hoisting)
showFood()

// Function declaration
function sayHi() { 
   console.log ('oi') 
}
// o JavaScript vai puxar a função para o topo, no hoisting
```
Hoisting (içamento, em português) [Saiba mais](https://developer.mozilla.org/pt-BR/docs/Glossary/Hoisting)

Hoisting funciona para a function declaration, mas não para a function expression (usando variável)

Na maioria das vezes, prefira declarar as funções no topo do código para manter a previsibilidade e a compreensão.

### Argumentos, parâmetros e default parameters
```js
const myFunc = function (name = 'Francisco', lastName = 'Chagas') { // name e lastName são **parâmetros**
   console.log(`Oi, ${name} ${lastName}!`)
}

myFunc('Roger', 'Melo') // Oi, Roger! 
// 'Roger' e 'Melo' são **argumentos**
```
![image](https://user-images.githubusercontent.com/54438080/142413476-7d85296d-24be-4173-9b4c-dbea42b25c9e.png)

**Comment by Roger-Melo** [comment]
Excelente @ghostnetrn, rumo à fluência 🙌🏻
