### ISSUE TITLE
Resumo da Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by emanuelcontinib** [roger-melo-treinamentos/curso-de-js-roger-melo#226]
**Functions**
A principal diferença entre **declaração de função** e **expressão de função** é que a declaração de função é içada. Ou seja, a declaração da função é puxada para o topo do código e pode ser chamada em uma leitura anterior de sua instrução. No entanto, contar com esse comportamento não é recomendável.

**Function expression**
` const showFood = function () {`
 ` console.log('pizza')`
`}`

`sayHi()`o código será executado sem problemas, mesmo invocando a função antes de sua declaração;

`showFood() //pizza`

**Function declaration**
`function sayHi () {`
`   console.log('Say Hi')`
`}`

**Argumentos e Parâmetros**
Numa função são executados parâmetros que são passados através de argumentos na invocação da função;
Se uma função for invocada e não houver parâmetro algum, o retorno será `undifined`; A prevenção desse comportamento se dá passando parâmetros fixos, que são sobrescritos quando a função é invocada utilizando argumentos;

``
``
``
``

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @emanuelcontinib. Rumo à fluência! 👊🏻
