### ISSUE TITLE
O forEach está recebendo undefined e eu não sei por que.

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2260]
### Etapa da aula

10

### Nome da aula

Correção dos exercícios da aula 02 da etapa 09 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1105821

### Descreva a dúvida

Eu fiz o código corretamente, procurei onde poderia estar errado por um bom tempo, mas não encontrei nada. Eu não entendo o por quê de o console dizer "Cannot read properties of undefined (reading 'forEach')", sendo que nem a const todos e nem a const inputValue recebem undefined(conferi usando console.log). Realmente não sei o que está dando errado, peço desculpas desde já caso tenha sido falta de atenção minha.

![image](https://user-images.githubusercontent.com/78214862/142431654-f9ca5cad-c80d-43a9-8854-bfa277d35ff5.png)

link da aplicação: https://github.com/YureK-a/Meu-portfolio/tree/main/To-do

OBS: tanto a addTodo() quanto a removeTodo() estão funcionando plenamente.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, @YureK-a!

Não precisa pedir desculpas, estou aqui para te ajudar =)

Primeiro, vou te mostrar o caminho que percorri para encontrar o que não está funcionando como o esperado, ok?

Eu consegui reproduzir o erro que vc reportou quando modifiquei o valor do input de pesquisa do to-do.

Com isso, eu já sei que devo começar a debugar o código aqui nesse callback:

```javascript
inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  hideTodos(todos, inputValue)
  hideTodos(todos, inputValue)
})
```

Dentro dele, eu inseri um console.log pra checar se as consts `inputValue` e `todos` estão armazenando os valores que eu espero que elas armazenem:

```javascript
inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
  console.log({ inputValue, todos })
  hideTodos(todos, inputValue)
  hideTodos(todos, inputValue)
})
```

Quando inseri 'a' no input, o console exibiu o resultado abaixo:

![image](https://user-images.githubusercontent.com/29297788/142455365-85953412-52a6-46a7-a682-fea62c79dbd7.png)

Ou seja, tudo funcionando corretamente, certo?

Observação: a invocação da `hideTodos` está duplicada. Acredito que vc quiz invocar a `showTodos`, então modifiquei o código e ele ficou assim:

```javascript
inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  hideTodos(todos, inputValue)
  showTodos(todos, inputValue)
})
```

Meu próximo passo então foi testar a próxima linha (`hideTodos(todos, inputValue)`). Pra testar a invocação da `hideTodos`, eu preciso ver a declaração dela.

Lá na declaração dela, só pra conferir se os parâmetros estavam de fato recebendo o valor que eu esperava, eu inseri este console.log:

```javascript
const hideTodos = (todos, inputValue) => {
  console.log({ todos, inputValue })
  const todosToHide = filterTodos(todos, inputValue, false)
  manipulateClasses(todosToHide, 'hidden', 'd-flex')
}
```

Ao testar o input novamente, o array de to-dos e o valor do input foram exibidos normalmente.

Meu próximo passo então foi testar a próxima linha, que é a linha que contém a declaração de `todosToHide`, que armazena o retorno de `filterTodos(todos, inputValue, false)`:

```javascript
const hideTodos = (todos, inputValue) => {
  const todosToHide = filterTodos(todos, inputValue, false)
  console.log(todosToHide)
  manipulateClasses(todosToHide, 'hidden', 'd-flex')
}
```

Quando eu inseri um valor no input, adivinha o que aconteceu?

![image](https://user-images.githubusercontent.com/29297788/142456935-f7abd5e9-ad8b-4d8d-94e0-b533253d704b.png)

Ah! Ha!

Ou seja, `todosToHide` está armazenando `undefined`.

E isso significa que na linha abaixo, 

```javascript
manipulateClasses(todosToHide, 'hidden', 'd-flex')
```

`undefined` foi inserido como primeiro argumento da `manipulateClasses`, certo?

Lá na declaração de `manipulateClasses` existe um primeiro parâmetro `todos`:

```javascript
const manipulateClasses = (todos, classToAdd, classToRemove) => {
  // ...
}
```

Esse parâmetro `todos` recebeu o `undefined` que foi inserido como 1º argumento da invocação da `manipulateClasses`.

Dentro da `manipulateClasses`, tem uma invocação do `forEach` encadeada no `todos`:

```javascript
const manipulateClasses = (todos, classToAdd, classToRemove) => {
  todos.forEach(todo => {
    // ...
  })
}
```

Ou seja, `todos` está armazenando `undefined` e uma invocação do `forEach` foi encadeada nesse `undefined`.

Por baixo do panos, o que está acontecendo é isso:

```javascript
undefined.forEach()
```

Se vc executar essa expressão no console do browser, verá a exata mesma mensagem do erro que vc reportou:

![image](https://user-images.githubusercontent.com/29297788/142459029-9fec8747-4cbf-4639-8951-d0513da8e0c9.png)

A mensagem diz `Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')`.

Traduzindo para o português, ficaria: `TypeError não capturado: Não é possível ler propriedades de undefined (ao ler forEach)`.

E isso faz sentido, pq não existe uma propriedade/método `forEach` em `undefined`, certo?

Então agora que eu descobri o que está causando o erro, eu preciso descobrir por que (no código abaixo) `todosToHide` está armazenando `undefined`.

```javascript
const hideTodos = (todos, inputValue) => {
  const todosToHide = filterTodos(todos, inputValue, false)
  manipulateClasses(todosToHide, 'hidden', 'd-flex')
}
```

Se `todosToHide` está armazenando `undefined`, isso significa que alguma coisa está fazendo a invocação da `filterTodos` retornar `undefined`. Então fui observar a declaração da `filterTodos`:

```javascript
const filterTodos = (todos, inputValue, returnMatchedTodos) => {
  todos.filter(todo => {
    const matchedTodos = todo.textContent.toLowerCase().includes(inputValue)
    return returnMatchedTodos ? matchedTodos : !matchedTodos
  })
}
```

Batendo o olho na declaração, eu saquei o que estava acontecendo. Mas por enquanto, vamos continuar...

Como vc já deve ter imaginado, meu primeiro passo foi checar se os parâmetros dela estavam recebendo os valores esperados:

```javascript
const filterTodos = (todos, inputValue, returnMatchedTodos) => {
  // 👇🏻 verificando os parâmetros
  console.log({ todos, inputValue, returnMatchedTodos })

  todos.filter(todo => {
    const matchedTodos = todo.textContent.toLowerCase().includes(inputValue)
    return returnMatchedTodos ? matchedTodos : !matchedTodos
  })
}
```

Quando testei novamente o input, tudo funcionando normalmente:

![image](https://user-images.githubusercontent.com/29297788/142461370-caaf9918-a120-4a19-8c64-dc805ecd818c.png)

Então, fui verificar se a expressão `todos.filter(...)` estava armazenando os to-dos filtrados:

```javascript
const filterTodos = (todos, inputValue, returnMatchedTodos) => {
  console.log(
    todos.filter(todo => {
      const matchedTodos = todo.textContent.toLowerCase().includes(inputValue)
      return returnMatchedTodos ? matchedTodos : !matchedTodos
    })
  )
}
```

Ao testar o input inserindo 'a', a expressão resultou em um array vazio:

![image](https://user-images.githubusercontent.com/29297788/142462078-8973c4a1-2ac9-4b09-afbb-4400f2fa0cdf.png)

Só que todos os to-dos contém a letra 'a', então a expressão deveria resultar em um array com as 3 referências dos to-dos, certo?

Isso significa que alguma coisa não está fazendo a função de callback do `filter` funcionar como ela deveria. 

O que vc acha que é?

**Comment by YureK-a** [comment]
Entendi o que aconteceu.

![image](https://user-images.githubusercontent.com/78214862/142467581-f9aa4004-bfdf-40c6-b378-482512ceaf28.png)

A função está filtrando e retornando os arrays normalmente... Mas e depois? Ela não **retorna** os arrays! Tudo por causa das chaves que eu coloquei, que eliminaram o return automático da arrow function. Ao removê-las... Não funciona. Por que? Simples, eu esqueci de trocar o parâmetro false pelo true na showTodo. Ao consertar isso... Funciona! HA!

Confesso que tive que comparar linha por linha na parte da resolução que você mostra a filterTodos refatorada para perceber o problema do return, mas o problema do false duplicado foi sozinho mesmo.

Eu me estressei bastante antes de criar a issue e a frustração até prejudicou meus estudos no dia de hoje, mas vou levar como aprendizado. Obrigado pela ajuda! =)

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
