### ISSUE TITLE
Resumo da Aula Adicionando To Do Aula 01-03 da etapa 09

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2265]
https://github.com/marcosyoggy/Resumo-Add-To-Do-Aula-01-03-E09

https://resumo-add-to-do-aula-01-03-e09.netlify.app

**Comment by Roger-Melo** [comment]
Excelente @marcosyoggy, rumo à fluência 🙌🏻
