### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2267]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ricardopontesdantas/cjrm-weather-app

### Maiores dificuldades durante a implementação

Acredito que as minhas dificuldades foram: nomear da melhor forma os elementos tanto no HTML quando no JavaScript e fazer com que minhas funções tivessem apenas uma responsabilidade. A refatoração é algo que também me tira da zona de conforto, mas sei que em algum momento vai fluir, estou praticando para isso.

### Menores dificuldades durante a implementação

A menor dificuldade que tive foi de selecionar elementos no DOM e fazer requisições assíncronas.

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

---

> ### Acredito que as minhas dificuldades foram: nomear da melhor forma os elementos tanto no HTML quando no JavaScript e fazer com que minhas funções tivessem apenas uma responsabilidade. A refatoração é algo que também me tira da zona de conforto, mas sei que em algum momento vai fluir, estou praticando para isso.

Se está seguindo método e sente desconforto, é um indício de que vc está de fato no caminho pra chegar na fluência =)

E sim, refatoração vem com a prática e o tempo. Aos poucos, vai ficando cada vez mais natural.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Lógica

Não faz sentido retornar `false` se nada é feito com esse boolean caso ele seja atribuído à const `data`:

```javascript
// 👇🏻 catch retornando false
const fetchData = async (endpoint) => {
  try {
    // ...
  } catch ({ name, message }) {
    console.log(name, message);
    return false;
  }
};
```

```js
// 👇🏻 caso data armazene false, nada é feito com ele dentro dessa função
const getCityWeatherDetails = async (cityName) => {
  const data = await getCityData(cityName);

  if (data.length === 0) {
    // ...
  }

  const [{ Key, LocalizedName }] = data;
  const [{ ... }] = await getWeatherData(Key);

  return {...};
};
```

Observe tb que se `data` armazena `false`, a tentativa de destructuring nele ali em cima vai lançar um `Uncaught (in promise) TypeError: data is not iterable`, por que não existem propriedades `Key` e `LocalizedName` em `false`.

---

Não execute um `throw` fora de um `try/catch`:

```javascript
const renderMessageNotFound = (message) => {
  resetForm();
  throw new Error(message);
};
```

Quando lançar um erro em seu código, sempre tem que haver um `catch` que vai capturar esse erro, ok? Se precisar relembrar, eu falo sobre isso na aula [Try/catch em requests e erros personalizados - Aula 06-05](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1376383) da etapa 11.

Tem uma forma elegante de abstrair repetições de `try/catch` no decorrer da aplicação, mas isso vc vai ver na etapa 15 =)

Outra abordagem que vc pode executar nesse caso é simplesmente não lançar o erro e apenas continuar exibindo na tela que a cidade não foi localizada.

---

Como `LocalizedName` e `WeatherText` não são strings com marcação HTML, vc pode usar a propriedade `textContent` ao invés de `innerHTML`:

```javascript
// ❌
cityName.innerHTML = LocalizedName;
descriptionWeather.innerHTML = WeatherText;


// ✅
cityName.textContent = LocalizedName;
descriptionWeather.textContent = WeatherText;
```

## Organização de código

### Extensões de arquivos

Cuidado ao nomear extensões de arquivos com letras maiúsculas.

Não deve causar problemas nessa aplicação, mas pode ser perigoso caso vc trabalhe em uma aplicação que tem código que depende da extensão estar em lowercase.

### Seleções de elementos do DOM

Evite selecionar elementos do DOM através de classes. Deixe as classes apenas para o CSS e use bem atributos `data-*`.

### Refatoração

Vou deixar abaixo algumas sugestões de refatoração.

A lógica de obter a imagem de background do clima não precisa estar dentro da `renderInfoCity`:

```javascript
// antes
const renderInfoCity = (...) => {
  // ...

  const containerBackground = IsDayTime
    ? "url(./src/day.jpg)"
    : "url(./src/night.jpg)";

  containerMain.style.backgroundImage = containerBackground;
  // ...
};
```

```javascript
// depois
const getWeatherBackground = IsDayTime => IsDayTime
  ? "url(./src/day.jpg)"
  : "url(./src/night.jpg)";

const renderInfoCity = (...) => {
  // ...

  containerMain.style.backgroundImage = getWeatherBackground(IsDayTime);
  // ...
};
```

Se quiser reduzir a extensão ou quebra de linhas, vc pode usar um objeto como parâmetro/argumento da `renderInfoCity`:

```javascript
// antes
const renderInfoCity = (
LocalizedName,
IsDayTime,
Temperature,
WeatherIcon,
WeatherText
) => {
  // ...
};
```

```javascript
// depois
const renderInfoCity = (city) => {
  // ...
  containerMain.style.backgroundImage = getWeatherBackground(city.IsDayTime);
  cityName.textContent = city.LocalizedName;
  descriptionWeather.textContent = city.WeatherText;
  iconWeather.src = `./src/icons/${city.WeatherIcon}.svg`;
  temperature.innerHTML = `${city.Temperature.Metric.Value}&deg;`;
};

changeLocation.addEventListener("submit", async (event) => {
  event.preventDefault();
  const city = await getCityWeatherDetails(event.target.city.value);

  renderInfoCity(city);
  changeLocation.reset();
});
```

Uma outra modificação que vc pode fazer é realocar o código do callback do submit para a `renderInfoCity` e concentrar a manipulação de DOM apenas nela:

```javascript
const renderInfoCity = async (event) => {
  event.preventDefault();
  const city = await getCityWeatherDetails(event.target.city.value);

  if (containerCityWeahetInfo.classList.contains("d-none")) {
    containerCityWeahetInfo.classList.remove("d-none");
  }

  if (!cityNotFound.classList.contains("d-none")) {
    cityNotFound.classList.add("d-none");
  }

  containerMain.style.backgroundImage = getWeatherBackground(city.IsDayTime);
  cityName.textContent = city.LocalizedName;
  descriptionWeather.textContent = city.WeatherText;
  iconWeather.src = `./src/icons/${city.WeatherIcon}.svg`;
  temperature.innerHTML = `${city.Temperature.Metric.Value}&deg;`;
  changeLocation.reset();
};

changeLocation.addEventListener("submit", renderInfoCity);
```

É possível também reduzir o destructuring na `getCityWeatherDetails`:

```javascript
// antes
const getCityWeatherDetails = async (cityName) => {
  const data = await getCityData(cityName);
  console.log(data)

  if (data.length === 0) {
    renderMessageNotFound("Cidade não localizada");
  }

  const [{ Key, LocalizedName }] = data;

  const [
    {
      IsDayTime,
      LocalObservationDataTime,
      Temperature,
      WeatherIcon,
      WeatherText,
    },
  ] = await getWeatherData(Key);

  return {
    LocalizedName,
    IsDayTime,
    LocalObservationDataTime,
    Temperature,
    WeatherIcon,
    WeatherText,
  };
};
```

```javascript
// depois
const getCityWeatherDetails = async (cityName) => {
  const data = await getCityData(cityName);

  if (data.length === 0) {
    renderMessageNotFound("Cidade não localizada");
  }

  const [{ Key, LocalizedName }] = data;
  const [weatherData] = await getWeatherData(Key);
  return [weatherData, LocalizedName];
};

const renderInfoCity = async (event) => {
  event.preventDefault();
  const [city, LocalizedName] = await getCityWeatherDetails(event.target.city.value);

  // ...
};
```

Se quiser diminuir um pouco a quantidade de linhas da `renderInfoCity`, vc pode isolar os `ìf`s em uma função `renderCityCard`:

```javascript
const renderCityCard = () => {
  if (containerCityWeahetInfo.classList.contains("d-none")) {
    containerCityWeahetInfo.classList.remove("d-none");
  }

  if (!cityNotFound.classList.contains("d-none")) {
    cityNotFound.classList.add("d-none");
  }
}

const renderInfoCity = async (event) => {
  event.preventDefault();
  const [city, LocalizedName] = await getCityWeatherDetails(event.target.city.value);

  renderCityCard()
  // ...
};
```

### Nomes de variáveis e funções

Além do princípio que comentei sobre nomes de variáveis e funções [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1242#issuecomment-881806673), não existem regras para nomear.

É algo que vc tb vai ficando afiado e tendo mais feeling conforme for praticando. Um outro fator que pode contar na hora de nomear é ver se o time segue alguma convenção.

Dito isso, eu acredito que as modificações abaixo deixariam as consts mais descritivas:

- `containerMain` => `cityCard`
- `changeLocation` => `form`
- `cityName` => `nameContainer`
- `temperature` => `temperatureContainer`
- `descriptionWeather` => `weatherContainer`
- `containerCityWeahetInfo` => `infoContainer`
- `cityNotFound` => `notFoundContainer`

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by ricardopontesdantas** [comment]
Valeu pelos comentários Roger, as observações fizeram sentido sim. Com relação ao que falou sobre a lógica, tranquilo, foi fácil de entender os pontos. Na parte que fala sobre organização do código, especificamente sobre extensão de arquivo e seleção de elementos do DOM, foi tranquilo de entender também. Mas na sugestão de refatoração, apesar de ter entendido os pontos, ainda não foi natural pra mim, assim como nomear as consts. Acredito que seja porque sempre me atentei mais em entender a lógica e em como resolver um problema do que em nomear algo. Sei da importância disso no código e acredito que faltou uma atenção e um cuidado maior com isso.
Eu lembro dos princípios de nomeação que você passou e tenho tentado aplica-los, mas acredito que nessa aplicação eu tenha me enrolado no seguinte (apenas um exemplo): 
No meu HTML eu tenho um input que recebe o nome da cidade e um H2 que recebe o nome da cidade após a pesquisa. Nesse caso eu não poderia ter dois data-js="cityName", por exemplo. Então esse foi o início de uma certa confusão no meu raciocínio para nomear. Parece uma grande besteira lendo depois, mas na hora em que estou escrevendo o código, ás vezes esse tipo de coisa acontece.

Para finalizar, só fiquei com dúvida no seguinte: Nas sugestões de nomeação, você me sugeriu os nomes "form", "nameContainer", "infoContainer" e "notFoundContainer". Caso fosse uma aplicação que tivesse mais de um form, eu deveria ser mais específico sobre estes nomes, certo?

**Comment by ricardopontesdantas** [comment]
Show Roger, obrigado pelas explicações. Ficou mais claro sim.

**Comment by Roger-Melo** [comment]
Show!

Apenas corrigindo, `data-js="headingCityName"` seria um nome mais adequado (e não header).

No que precisar, é só abrir uma nova issue =)
