### ISSUE TITLE
Resumo da Aula 01-03 da etapa 02 - For loop

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2268]
- É o loop mais usado.

Exemplo:
```
for (let i = 0; i < 5; i++){
 console.log(`Dentro do loop: ${i}`)
}
console.log('Loop concluído')
```
`let i=0` => inicialização.
`i < 5 `=> condição, enquanto i for menor que 5 o loop será executado, será true, quando o i não for menor que 5 o loop não será mais executado, resultando em false.
`i++ `=> incremento, o i inicia com 0, toda vez que o loop for executado i receberá todo o valor que tem mais 1. 

Para percorrer um array com vários itens, sem saber quantos elementos contém.
```
const names = ['Linus', 'Ada', 'Bill']
for(let i = 0; i < names.length; i++){
    console.log(names[i])
}
```
`names.length` retorna o a quantidade de itens do array names que é 3, enquanto i for menor que 3, o loop será executado.
i = 0; 0 < 3(true); i é incremento em 1
será exibido: Linus
i = 1; 1 < 3(true); i é incrementado em 2
será exibido: Ada
i = 2; 2 < 3(true); i é incrementado em 3
será exibido: Bill
i = 3; 3 < 3(false); o loop será concluído, pois 3 não é menor que 3.

**Comment by Roger-Melo** [comment]
Excelente @Jansen-Muniz, rumo à fluência 🙌🏻
