### ISSUE TITLE
Dúvida sobre eficiência do método e sobre operador ternário

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#2270]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 02 da etapa 08 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1039812

### Descreva a dúvida

Bom dia, professor!

No exercício 7 dessa aula(Exercícios da aula 2 etapa 8) você usou o método filter() e depois o reduce().
Eu tinha feito usando usando somente o reduce(), seguindo a mesma lógica que você usou na aula 01-04 (Método reduce() ) da etapa 8:

```js
// Aula 01-04 (Método reduce() ) da etapa 8:
const phaseScores = [
  { name: 'Vinicius Costa', score: 337 },
  { name: 'Roger Melo', score: 43 },
  { name: 'Alfredo Braga', score: 234 },
  { name: 'Pedro H. Silva', score: 261 },
  { name: 'Ana Paula Rocha', score: 491 },
  { name: 'Vinicius Costa', score: 167 },
  { name: 'Roger Melo', score: 137 },
  { name: 'Alfredo Braga', score: 135 },
  { name: 'Ana Paula Rocha', score: 359 },
  { name: 'Pedro H. Silva', score: 133 },
]

const rogerScore = phaseScores.reduce((accumulator, phaseScore) => {
  if(phaseScore.name === 'Roger Melo') {
    accumulator += phaseScore.score
  }
  return accumulator 
}, 0)

console.log(rogerScore) // 180 
```

Tenho duas dúvidas:
1- Tem alguma diferença entre usar ou não o filter() em termos de eficiência e eficácia nos resultados ?
2- Usei um operador ternário, funcionou, mas fiz da forma correta ou funcionou por coincidência?

Como você resolveu o exercício:

```js

const topBrazilmovies = [
  {
    title: 'Vingadores: Ultimato',
    peopleAmount: 19686119,
    distributedBy: 'Disney',
  },
  {
    title: 'Titanic',
    peopleAmount: 17050000,
    distributedBy: 'Paramount / 20th Century',
  },
  { title: 'O Rei Leão', peopleAmount: 16267649, distributedBy: 'Disney' },
  {
    title: 'Vingadores: Guerra Infinita',
    peopleAmount: 14572181,
    distributedBy: 'Disney',
  },
  { title: 'Tubarão', peopleAmount: 13035000, distributedBy: 'Universal' },
  {
    title: 'Nada a Perder',
    peopleAmount: 11944985,
    distributedBy: 'Paris Filmes',
  },
  {
    title: 'Os Dez Mandamentos',
    peopleAmount: 11259536,
    distributedBy: 'Paris / Downtown Filmes',
  },
  { title: 'Tropa de Elite 2', peopleAmount: 11204815, distributedBy: 'Zazen' },
  { title: 'Os Vingadores', peopleAmount: 10968065, distributedBy: 'Disney' },
  {
    title: 'Dona Flor e Seus Dois Maridos',
    peopleAmount: 10735524,
    distributedBy: 'Embrafilme',
  },
]
const peopleAmount = topBrazilmovies
  .filter(({ distributedBy}) => distributedBy === 'Disney')
  .reduce((acc { peopleAmount}) => acc + peopleAmount, 0)

console.log(peopleAmount) //61494014
```
Minha suloção do exercício:

```js 
const peopleAmount = topBrazilmovies.reduce((acc, { distributedBy, peopleAmount }) => {    
    return distributedBy === 'Disney'? acc + peopleAmount : acc
  }, 0)

console.log(peopleAmount) //61494014
```
Obrigada desde já!
Elaine

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

> ### Minha suloção do exercício:

Você resolveu o desafio usando menos código do que eu mostrei. Parabéns =)

Se quiser deixar o código ainda mais conciso, vc pode eliminar `return` e o bloco e usar o return implícito da arrow function:

```javascript
const peopleAmount = topBrazilmovies
  .reduce((acc, { distributedBy, peopleAmount }) => 
    distributedBy === 'Disney' ? acc + peopleAmount : acc, 0)
```

---

> ### 1- Tem alguma diferença entre usar ou não o filter() em termos de eficiência e eficácia nos resultados ?

Depende do que vc quer dizer com "eficiência" e "eficácia" =)

Se estiver falando do ponto de vista de performance, não se preocupe com isso agora. Em etapas mais avançadas vc verá que falarei sobre isso.

Na verdade, a utilização do filter acabou adicionando um passo além do necessário. 

E sempre que possível, o ideal é escrever o mínimo possível de código para alcançar um resultado.

O motivo disso é simples: quanto menos código, menos bugs.

Cada linha de código que escrevemos pode criar toneladas de bugs.

> ### 2- Usei um operador ternário, funcionou, mas fiz da forma correta ou funcionou por coincidência?

Funcionou muito bem pq vc usou o ternário da forma certa.

Existem 2 regras que se vc seguir, estará usando ternário da melhor forma possível:

1. Não executar efeito colateral;
2. Fazer algo com o valor que o ternário retorna.

Exemplo de ternário usado de forma equivocada:

```javascript
IsDayTime ? weatherImg.src = './src/img/day.svg' : weatherImg.src = './src/img/night.svg'
```

Nesse código, o ternário está sendo usado para executar uma manipulação de DOM (efeito colateral) e nada está sendo com o valor que ele retorna. É um exemplo extremo, que viola as 2 regras.

Uma forma simples de usar o ternário nesse caso é fazê-lo retornar a string que `src` precisa armazenar:

```javascript
weatherImg.src = IsDayTime ? './src/img/day.svg' : './src/img/night.svg'
```

Quando você precisar de um valor baseado em uma expressão, use ternário. 

Se não é necessário fazer algo com o valor que a expressão retorna ou se o ternário está sendo usado pra executar efeito colateral, melhor usar `if`.

Ficou mais claro?

**Comment by ElaineDelgado** [comment]
Ficou bem claro sim, sobre usar o ternário ou if então foi bom saber quando usar um ou outro.
Muito obrigada!!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
