### ISSUE TITLE
Aplicação: [Quiz]

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2276]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/carlosdevjs/uploadQuiz.git

### Maiores dificuldades durante a implementação

achar nomes compatíveis, refatoração do recebimento das opções do usuário, realizar a inclusão do popup, recebendo o resultado final, bootstrap(praticar mais)

### Menores dificuldades durante a implementação

eventListene(),

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### achar nomes compatíveis, refatoração do recebimento das opções do usuário, realizar a inclusão do popup, recebendo o resultado final, bootstrap(praticar mais)

Não se preocupe com refatoração agora. Seu foco deve estar em evoluir sua lógica, como você verá mais abaixo.

Mas o mais importante, num primeiro momento, vc já fez, que é fazer funcionar.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez.

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

Seria interessante deixar a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

## Lógica

`button.addEventListener` é desnecessário, pois já existe um evento de `submit` do `form` no qual o button está dentro. 

Basta fazer a manipulação de classes CSS do popup dentro do callback de submit:

```javascript
// antes
form.addEventListener('submit', event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  calculateUserScore(userAnswers)
  scoreFinale()
  animateFinaleScore()
})

button.addEventListener('click', () => {
  popup.setAttribute('class', 'popup-wrapper d-block text-center')
})
```

```javascript
// depois
form.addEventListener('submit', event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  popup.setAttribute('class', 'popup-wrapper d-block text-center')
  calculateUserScore(userAnswers)
  scoreFinale()
  animateFinaleScore()
})
```

---

A `textContent` abaixo está inserindo texto em um elemento que não está sendo usado na aplicação:

```javascript
const animateFinaleScore = () => {
  // ...
  const timer = setInterval(() => {
    // ...

    scoreFinal.querySelector('span').textContent = `${counter++}%`
  }, 30)
}
```

Não faz sentido deixar esse código assim. Apenas faça o incremento que deve ser feito no `counter` e tire essa manipulação dali. E óbvio, remova código não-usado dos outros arquivos também.

```javascript
const animateFinaleScore = () => {
  // ...
  const timer = setInterval(() => {
    // ...

    counter++
  }, 30)
}
```

---

`counter` está sendo incrementado para 26 desnecessariamente. Você pode ver isso exibindo ela no console:

```javascript
const animateFinaleScore = () => {
  let counter = 0

  const timer = setInterval(() => {
    popup.querySelector('#result').textContent = `${counter}%`

    if (counter === score) {
      clearInterval(timer)
      score = 0
    }

    counter++
    console.log(counter) // 26
  }, 30)
}
```

Não há nada de grave em `counter` receber 26, mas é importante entender que o `clearInterval(timer)` não para a função exatamente na linha em que ele foi invocado. O código abaixo da invocação do `clearInterval` é executado pela última vez. Ou seja, `clearInterval` não faz o papel do return. Para que a função pare após `score = 0`, é necessário inserir `return` na última linha do `if`.

---

Não é necessário setar as classes do popup novamente com o `setAttribute` pra fazer o popup ser exibido ou ocultado. 

Vc pode usar `add` ou `remove` de `classList`:

```javascript
// antes
form.addEventListener('submit', event => {
  // ...

  popup.setAttribute('class', 'popup-wrapper d-block text-center')
  // ...
})
```

```javascript
// depois
form.addEventListener('submit', event => {
  // ...

  popup.classList.remove('d-none')
  // ...
})
```

```javascript
// antes
popup.addEventListener('click', event => {
  // ...

  if (isExistClassName) {
    popup.setAttribute('class', 'popup-wrapper d-none text-center')
    // ...
  }
})
```

```javascript
// depois
popup.addEventListener('click', event => {
  // ...

  if (isExistClassName) {
    popup.classList.add('d-none')
    // ...
  }
})
```

---

`popup.querySelector('#result').textContent = 0` pode ser removido, pois toda vez que o form é enviado, `animateFinaleScore` é executada e, dentro dela, `counter` já recebe `0`:

```javascript
const animateFinaleScore = () => {
  let counter = 0

  // ...
}

popup.addEventListener('click', event => {
  // ...

  if (isExistClassName) {
    // ...
    // 👇🏻 pode ser removido
    popup.querySelector('#result').textContent = 0
  }
})
```

## Organização de código

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você remover as linhas em branco 108, 96 e 78.

É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código.

### Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Código comentado também deve ser removido. Em nenhuma hipótese deixe código não-usado em sua aplicação.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`scoreFinale` é um nome que não descreve bem a ação que a função está executando:

```javascript
const scoreFinale = () => {
  scrollTo({
    top: 0,
    left: 0,
    behavior: 'smooth'
  })
}
```

Como o código dessa função basicamente faz um scroll pro topo, eu a nomearia como `scrollToTop`.

---

`classList` não armazena uma lista de classes. Um nome mais apropriado seria `CSSClass`, pois ela armazena uma única classe CSS.

---

`isExistClassName` pode ser mais descritiva se renomeada para algo como `shouldHidePopup`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by carlosdevjs** [comment]
Sim faz todos os sentidos. Vou refazer o código e estarei acrescentando suas observações e novamente obrigado pelas orientações.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)

**Comment by carlosdevjs** [comment]
Enviou novamente a aplicação do quiz, quando eu estiver realizando estes acertos sem olhar as aulas.
