### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#2279]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JuniorAlvesbr/weather

### Maiores dificuldades durante a implementação

Minha maior dificuldade é pensar na lógica de como buscar a informação na API e trata-la de forma adequada.

Tinha momentos que eu travava e não sabia o que fazer com a informação que pegava na API, principalmente quando tive que iterar por alguns arrays para montar objetos com a informação que precisava.

Também tive muita confusão nos destructuring.

### Menores dificuldades durante a implementação

As coisas básicas da liguagem como criar funções

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ### Minha maior dificuldade é pensar na lógica de como buscar a informação na API e trata-la de forma adequada. Tinha momentos que eu travava e não sabia o que fazer com a informação que pegava na API, principalmente quando tive que iterar por alguns arrays para montar objetos com a informação que precisava.

Essa aplicação é um pouquinho mais complexa e exige mais atenção nas requisições mesmo. Mas pelo que vi, vc soube executar os requests e exibir as informações =)

> ### Também tive muita confusão nos destructuring.

O que exatamente te confundiu nos destructurings?

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

### Foco no input

Quando a página é carregada, o `input` já pode ter foco. Isso evita que o usuário tenha que pegar o mouse e clicar no input, ou tocar no input para fazer uma busca. Para que o input tenha foco quando a aplicação é carregada, basta inserir um atributo `autofocus` nele.

---

### Ícones

Como os ícones tem uma cor escura, quando é noite em uma cidade, os ícones não contrastam com o background escuro. Para resolver isso, vc pode mudar a cor deles para uma cor que dê contraste com ambos backgrounds.

---

### Declarações e invocações de funções

Prefira declarar uma função antes de sua invocação. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

---

### O que acontece quando uma cidade inválida é pesquisada

Quando uma cidade inválida é pesquisada, o `catch` da `getInfoAPI` é executado normalmente:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    // ...
  } catch ({ name, message }) {
    alert(`${name}, ${message}`)
  }
}
```

![image](https://user-images.githubusercontent.com/29297788/143061858-37fb4496-465b-4446-9740-1dc9fa32acd6.png)

Porém, logo após o alert do catch, `app.js:27 Uncaught (in promise) TypeError: Cannot destructure property 'LocalizedName' of 'undefined' as it is undefined.` é exibido no console:

![image](https://user-images.githubusercontent.com/29297788/143062177-9c882430-f4fd-4d94-a297-83143d8c86db.png)

A mensagem do erro diz que não é possível executar um destructuring em `undefined`. 

Se vc investigar a linha 27 (linha em que o erro foi lançado), chegará a conclusão que `showDataInHTML` está recebendo undefined por parâmetro (ao invés de receber um objeto).

```javascript
const showDataInHTML = ({
  LocalizedName,
  WeatherText,
  WeatherIcon,
  IsDayTime,
  Temperature,
  RelativeHumidity,
  Wind,
  Pressure,
  dataForecastFiveDays
}) => {...}
```

E como há uma tentativa de destructuring em `undefined`, o erro é lançado, pois `undefined` não possui as propriedades especificadas no destructuring.

A única invocação de `showDataInHTML` na aplicação é dentro do callback do envio do `form`:

```javascript
$form.addEventListener('submit', async event => {
  event.preventDefault()

  const inputValue = event.target.inputCity.value
  const dataInfoApi = await getInfoAPI(inputValue)

  // 👇🏻 invocação de showDataInHTML
  showDataInHTML(dataInfoApi)
})
```

Isso significa que `dataInfoApi`, que é uma constante que armazena o retorno de `await getInfoAPI(inputValue)` está armazenando `undefined`.

Mas por que a invocação da `getInfoAPI` está retornando `undefined`?

Se vc observar a declaração da `getInfoAPI`, verá que ela retorna `dataWeather`:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    // ...

    const dataWeather = await getWeather(Key)
    // ...

    return dataWeather
  }
  // ...
}
```

Se vc exibir `dataWeather` no console e testar novamente uma cidade inválida, verá que o console.log não é executado:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    const [{ LocalizedName, Key }] = await getCity(inputValue)

    if (LocalizedName === "") {
      throw new Error('Não foi posssivel localizar a cidade')
    }

    const dataWeather = await getWeather(Key)
    const dataForecastFiveDays = await getForecastFiveDays(Key)

    dataWeather['LocalizedName'] = LocalizedName
    dataWeather['dataForecastFiveDays'] = dataForecastFiveDays

    // 👇🏻 exibindo o valor de dataWeather
    console.log(dataWeather)
    return dataWeather
  } catch ({ name, message }) {
    alert(`${name}, ${message}`)
  }
}
```

Se vc inserir um console.log na 1ª linha do try, verá que desta vez o console.log é executado:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    console.log('olá')
    const [{ LocalizedName, Key }] = await getCity(inputValue)

    if (LocalizedName === "") {
      throw new Error('Não foi posssivel localizar a cidade')
    }

    const dataWeather = await getWeather(Key)
    const dataForecastFiveDays = await getForecastFiveDays(Key)

    dataWeather['LocalizedName'] = LocalizedName
    dataWeather['dataForecastFiveDays'] = dataForecastFiveDays

    console.log(dataWeather)
    return dataWeather
  } catch ({ name, message }) {
    alert(`${name}, ${message}`)
  }
}
```

Se esse 1º console.log é executado e o 2º não é, tem algum código entre esses 2 console.log que está lançando um erro. Se está lançando um erro, esse erro está sendo pego pelo catch. 

Ou seja, ao invés de retornar `dataWeather`, a função `getInfoAPI` está lançando um erro. Se está lançando um erro, ela não retorna valor. E toda função que não retorna um valor, por baixo dos panos, retorna `undefined`. É por isso que a `dataInfoApi` lá dentro do callback do envio do `form` está armazenando `undefined`. Sacou?

Voltando à `getInfoAPI`, lembra que ali no início eu disse que o `catch` da `getInfoAPI` estava sendo executado normalmente?

Observe o que a mensagem desse erro está dizendo:

![image](https://user-images.githubusercontent.com/29297788/143068173-e095e208-f70b-48ab-8a52-751f3a449ee1.png)

`TypeError, Cannot read properties of undefined (reading 'LocalizedName')`.

Essa mensagem basicamente diz que não é possível ler propriedades de undefined (ao ler 'LocalizedName').

Observe que logo abaixo do 1º console.log há uma tentativa de destructuring em uma propriedade `LocalizedName` de um objeto que, teoricamente, `await getCity(inputValue)` retorna:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    console.log('olá')
    const [{ LocalizedName, Key }] = await getCity(inputValue)

    // ...
  } 
  // ...
}
```

Se vc investigar o valor que `getCity` retorna ao buscar uma cidade inválida, verá que `await response.json()` resulta em um array vazio:

```javascript
const getCity = async (inputValue) => {
  const cityURL = getCityURl(inputValue)
  
  try {
    const response = await fetch(cityURL)
    
    if (!response.ok) {
      throw new Error('Não foi possivel obter os dados')
    }

    console.log(await response.json())
    // return await response.json()
  }
  // ...
}
```

![image](https://user-images.githubusercontent.com/29297788/143069356-8122e2bf-8a10-484f-94ab-3aba90c2bc1f.png)

Se vc executar um destructuring de objeto em um array vazio, verá exatamente o mesmo erro dizendo que não é possível ler propriedades de undefined (ao ler 'oi').

```javascript
[{ oi, ola }] = []
```

![image](https://user-images.githubusercontent.com/29297788/143070089-4b1d3824-6474-4bf7-b333-d737bb7e4abb.png)

Isso significa que o que está lançando esse erro é o destructuring abaixo:

```javascript
const getInfoAPI = async (inputValue) => {
  try {
    console.log('olá')
    const [{ LocalizedName, Key }] = await getCity(inputValue)
    // ...
  }
  // ...
}
```

Para que esse erro não seja lançado, vc precisa impedir que `getCity` retorne um array vazio:

```javascript
// antes
const getCity = async (inputValue) => {
  const cityURL = getCityURl(inputValue)
  
  try {
    const response = await fetch(cityURL)
    
    if (!response.ok) {
      throw new Error('Não foi possivel obter os dados')
    }

    return await response.json()
  } catch ({ name, message }) {
    console.log('getCity')
    alert(`${name}, ${message}`)
  }
}
```

```javascript
// depois
const getCity = async (inputValue) => {
  const cityURL = getCityURl(inputValue)
  
  try {
    const response = await fetch(cityURL)

    if (!response.ok) {
      throw new Error('Não foi possivel obter os dados')
    }

    const data = await response.json()

    // 👇🏻 impedindo que um array vazio seja retornado
    if (data.length === 0) {
      throw new Error('Não foi posssivel localizar a cidade')
    }

    return data
  } catch ({ name, message }) {
    alert(`${name}, ${message}`)
  }
}
```

Feito isso, essa verificação dentro da `getInfoAPI` pode ser removida:

```javascript
if (LocalizedName === "") {
  throw new Error('Não foi posssivel localizar a cidade')
}
```

Só que se vc testar novamente, vai ver que o erro com a mensagem dizendo que não é possível localizar a cidade é exibido, porém, como ainda há um destructuring na `showDataInHTML` e a invocação dela está recebendo undefined, o erro dizendo que não é possível fazer o destructuring ainda é lançado.

```javascript
// Ainda vai lançar erro (app.js 27)... pq tem destructuring na `showDataInHTML`:
const showDataInHTML = ({
  LocalizedName,
  // ...
}) => {...}

// e a invocação dela está recebendo undefined
$form.addEventListener('submit', async event => {
  event.preventDefault()

  const inputValue = event.target.inputCity.value
  const dataInfoApi = await getInfoAPI(inputValue)
  console.log(dataInfoApi) // undefined
  showDataInHTML(dataInfoApi)
})
```

Para resolver esse erro, você precisa evitar que `showDataInHTML` receba `undefined`:

```javascript
$form.addEventListener('submit', async event => {
  event.preventDefault()

  const inputValue = event.target.inputCity.value
  const dataInfoApi = await getInfoAPI(inputValue)

  if (!dataInfoApi) {
    return
  }

  showDataInHTML(dataInfoApi)
})
```

Fazendo isso, vc captura os erros que podem ser lançados quando o usuário buscar uma cidade inválida.

E vc ainda pode evitar que um erro seja lançado caso haja a tentativa de destructuring em `undefined` dentro da `getInfoAPI`:

```javascript
// antes
const getInfoAPI = async (inputValue) => {
  try {
    const [{ LocalizedName, Key }] = await getCity(inputValue)

    // ...
  }
  // ...
}
```

```javascript
// depois
const getInfoAPI = async (inputValue) => {
  try {
    const data = await getCity(inputValue)

    if (!data) {
      return
    }

    const [{ LocalizedName, Key }] = data
    // ...
  }
  // ...
}
```

---

### Eliminando mutabilidade

Mutabilidade pode ocultar bugs. Sempre que possível, evite.

Ao invés de modificar um objeto, prefira criar um novo.

Dentro da `getInfoAPI`, ao invés de modificar o objeto, vc pode simplesmente retornar um novo array:

```javascript
// antes
const getInfoAPI = async (inputValue) => {
  try {
    // ...
    const dataWeather = await getWeather(Key)
    const dataForecastFiveDays = await getForecastFiveDays(Key)

    dataWeather['LocalizedName'] = LocalizedName
    dataWeather['dataForecastFiveDays'] = dataForecastFiveDays
    
    return dataWeather
  }
  // ...
}
```

```javascript
// depois
const getInfoAPI = async (inputValue) => {
  try {
    // ...
    const dataWeather = await getWeather(Key)
    const dataForecastFiveDays = await getForecastFiveDays(Key)

    return [dataWeather, LocalizedName, dataForecastFiveDays]
  }
  // ...
}
```

Feito isso, como o retorno da invocação da `getInfoAPI` está sendo inserido como argumento da ìnvocação da `showDataInHTML`, vc pode ajustar a declaração de parâmetros dela.

Se quiser diminuir algumas linhas, pode fazer destructuring apenas no array e usar a sintaxe `obj.`:

```js
const showDataInHTML = ([cityDetail, LocalizedName, dataForecastFiveDays]) => {
  $cityName.textContent = LocalizedName
  $icon.src = getIconURL(cityDetail.WeatherIcon)
  $weather.textContent = cityDetail.WeatherText
  $mainTemperature.textContent = cityDetail.Temperature.Metric.Value
  $pressure.textContent = cityDetail.Pressure.Metric.Value
  $relativeHumidity.textContent = cityDetail.RelativeHumidity
  $windSpeed.textContent = cityDetail.Wind.Speed.Metric.Value
  showFiveDaysinHTML(dataForecastFiveDays)

  cityDetail.IsDayTime ? $main.classList.remove('-dark') : $main.classList.add('-dark')
  $form.reset()
  $wrapper.classList.add('-active')
}
```

---

### Ternário

Geralmente, ternários não devem ser usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para manipular classes CSS (em que o valor no qual essa expressão resulta não está sendo aproveitado), eu usaria (por incrível que pareça) apenas um if/else:

```javascript
// antes
cityDetail.IsDayTime ? $main.classList.remove('-dark') : $main.classList.add('-dark')
```

```javascript
// depois
if (cityDetail.IsDayTime) {
  $main.classList.remove('-dark')
} else {
  $main.classList.add('-dark')
}
```

---

### Repetições

Se quiser não repetir a url, vc pode usar um ternário para obter a string do ícone de forma dinâmica:

```javascript
// antes
const getIconURL = icon =>
  icon < 10 ?
    `https://developer.accuweather.com/sites/default/files/0${icon}-s.png` :
    `https://developer.accuweather.com/sites/default/files/${icon}-s.png`
```

```javascript
// depois
const getIconURL = icon => 
  `https://developer.accuweather.com/sites/default/files/${icon < 10 ? `0${icon}` : icon}-s.png`
```

Ou, mais legível:

```javascript
const getIconURL = icon => {
  const withZero = icon < 10 ? `0${icon}` : icon
  return `https://developer.accuweather.com/sites/default/files/${withZero}-s.png` 
}
```

---

### Efeito colateral no map

Prefira não executar efeito colateral em métodos de array como `map`, `filter` e `reduce`.

Se precisar executar efeito colateral, use `forEach` ou `for`.

O `map` já gera um novo array, então não é necessário criar e adicionar itens em um novo array de forma manual.

Também não é necessário criar um novo objeto de data a cada execução do callback do map:

```javascript
// antes
const getForecastFiveDays = async Key => {
  const forecastFiveDays = []
  const forecastFiveDaysURL = getForecastFiveDaysURL(Key)
  const { DailyForecasts } = await (await fetch(forecastFiveDaysURL)).json()

  DailyForecasts.map(item => {
    const getWeekDay = new Date(item.Date).getDay()
    const weekDay = daysOFtheWeek[getWeekDay]

    forecastFiveDays.push({
      'weekDay': weekDay,
      'icon': item.Day.Icon,
      'temperature': Math.round(item.Temperature.Maximum.Value)
    })
  })

  return forecastFiveDays
}
```

```javascript
// depois
const getForecastFiveDays = async Key => {
  const daysOFtheWeek = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab']
  const forecastFiveDaysURL = getForecastFiveDaysURL(Key)
  const { DailyForecasts } = await (await fetch(forecastFiveDaysURL)).json()
  const get = date => new Date(date)

  return DailyForecasts.map(item => ({
    weekDay: daysOFtheWeek[get(item.Date).getDay()],
    icon: item.Day.Icon,
    temperature: Math.round(item.Temperature.Maximum.Value)
  }))
}
```

---

### Seleção de elementos do DOM

Prefira selecionar elementos do DOM usando o atributo `data-*`. 

Se amanhã uma class CSS mudar de nome, seu código quebra. 

Além disso, deixar as classes para o CSS torna o seu código mais organizado. 

```javascript
// evite
const $icon = document.querySelector('.main-weather > .icon')
```

```javascript
// prefira
const $icon = document.querySelector('[data-js="icon"]')
```

---

### Const não usada

A const `iconURL` não está sendo usada, então ela pode ser removida.

---

### Nomes de variáveis e funções

Vou deixar abaixo algumas sugestões de nomes que acho que sejam mais descritivos. Veja o que faz sentido pra vc =)

Se quiser substituir com menos trabalho, basta deixar o cursor no nome (na declaração da variável), pressionar `F2`, inserir o novo nome no input que aparecer e pressionar `enter`.

- `$wrapper` => `$wrapperWeatherInfo`
- `$weather` => `$weatherDescription`
- `$mainTemperature` => `$temperatureDegree`
- `$weekDay` => `$weekDays`
- `$fiveIcon` => `$weatherImgs`
- `$temperature` => `$weekDayDegrees`
- `showFiveDaysinHTML` => `showForecastForFiveDays`
- `showDataInHTML` => `showCityWeather`
- `getInfoAPI` => `getCityWeather`
- `dataInfoApi` => `cityWeather`
- `dataWeather` => `weather`
- `getForecastFiveDays` => `getForecastForFiveDays`
- `dataForecastFiveDays` => `forecastForFiveDays`
- `getCity` => `getCityInfo`
- `data` (dentro de getCityInfo e getCityWeather) => `cityInfo`
- `[cityDetail, LocalizedName, dataForecastFiveDays]` (destructuring no parâmetro da showCityWeather) => `[weather, LocalizedName, forecastForFiveDays]`

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JuniorAlvesbr** [comment]
Muito bom sua analise (acho que vou ter que rescrever o programa de novo kkkkk), concerteza vez muito sentido para mim. Já estou revisando todo o código levando em conta tudo oque vc falow.

Eu to tentando corrigir os erros. Eu entreguei o projeto com esses erros para não estourar o prazo final da entrega.

Porem não consigo fazer o programa parar no try - catch, como que eu faço para parar o programa assim que o erro do catch for lançado?. Tipo se a cidade não for localizada eu quero parar o programa, achei que o catch faria isso por mim.

Outra coisa, penso que nesse programa tem vários locais que podem dar erro, eu teria que implementar o try-catch em todas as funções que lida com as informações da API para não lançar um possivel undefined ? A utilização do try-catch para mim ta um pouco confusa, não a sua utilização em si, mas quando utiliza-la. Eu tenho a impressão que devo estar constantemente testando se as constantes são undefineds ou não para tratar os erros.

**Comment by Roger-Melo** [comment]
> ### Porem não consigo fazer o programa parar no try - catch, como que eu faço para parar o programa assim que o erro do catch for lançado?. Tipo se a cidade não for localizada eu quero parar o programa, achei que o catch faria isso por mim.

O `catch` faz exatamente o contrário. Ele captura o erro para que a aplicação não trave e continue rodando.

Os try/catch são as últimas execuções da aplicação (pq envolvem operações assíncronas). O que exatamente vc quer parar após a execução deles?

Lembre-se que seus try/catch estão dentro de funções. Funções sempre retornam um valor (mesmo que seja `undefined` por baixo dos panos) e no seu código, **vc definiu** que vai fazer algo com esse valor retornado.

```javascript
$form.addEventListener('submit', async event => {
  event.preventDefault()

  const inputValue = event.target.inputCity.value
  // 👇🏻 armazena o valor que a invocação de getCityWeather retorna
  const cityWeather = await getCityWeather(inputValue)

  if (!cityWeather) {
    return
  }

  showCityWeather(cityWeather)
})
```

Ou seja, no código acima, se o catch lá dentro da `getCityWeather` for executado, o retorno da invocação dela será `undefined`. Isso é inevitável. O `if` vai parar a execução do código dali pra baixo (`showCityWeather` não será executada).

Agora, se vc quiser, pode estruturar seu código para não depender do retorno da função. Vou demonstrar com um exemplo mais simples pra vc sacar:

```javascript
const button = document.querySelector('button')

const renderTodoTitle = todo => {
  document.body.innerHTML = `<h1>${todo.title}</h1>`
}

const handleClick = async () => {
  try {
    const data = await fetch('https://jsonplaceholder.typicode.com/todos/1')

    if (!data.ok) {
      throw new Error('Falha na conexão')
    }

    const todo = await data.json()
    renderTodoTitle(todo)
  } catch (e) {
    console.log(e)
  }
}

button.addEventListener('click', handleClick)
```

Agora vc não depende do retorno da função.

---

> ### Outra coisa, penso que nesse programa tem vários locais que podem dar erro, eu teria que implementar o try-catch em todas as funções que lida com as informações da API para não lançar um possivel undefined ?

Vc sempre terá que implementar happy path e sad path. Ou seja, casos onde as coisas vão bem e onde vão mal. Vc sempre terá que tratar os possíveis valores que vc está recebendo da API.

---

> ### A utilização do try-catch para mim ta um pouco confusa, não a sua utilização em si, mas quando utiliza-la. Eu tenho a impressão que devo estar constantemente testando se as constantes são undefineds ou não para tratar os erros. 

Catch, em inglês, significa capturar. 

Você precisa do try/catch para capturar e tratar possíveis erros que sua aplicação pode lançar. Se um erro é lançado na aplicação e não cai em um catch, sua aplicação trava. Se sua aplicação travar, o usuário não vai querer usá-la.

[Nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1372048) eu expliquei por que o try/catch é usado. Recomendo fortemente que veja outra vez e se tiver mais dúvidas sobre isso, pergunte. Esse conceito tem que estar bem claro pra vc. 

---

> ### Eu tenho a impressão que devo estar constantemente testando se as constantes são undefineds ou não para tratar os erros.

São coisas diferentes. 

`undefined` não lança erro. 

`undefined` não trava sua aplicação.

`undefined` não precisa de `catch` pra ser tratado.

O que trava a aplicação é um erro lançado, por exemplo, por tentar executar um método/propriedade ou um destructuring em `undefined`. Aí vc vai precisar de um `catch` pra tratar esse erro e impedir que a aplicação trave.

@JuniorAlvesbr

**Comment by Roger-Melo** [comment]
Ah, em etapas mais avançadas, eu mostro como vc pode abstrair repetições de try/catch na aplicação =D

**Comment by JuniorAlvesbr** [comment]
Entendi, de fato mesmo assistindo as aulas, na minha cabeça o eu estava tratando o try/catch como um if/else. No entanto para lidar com as variáveis eu sigo utilizando if/else não try/catch.
Eu estou fatorando o código com esse principio e já percebo os erros sendo corrigidos de forma até mais fácil do que imaginava.
Vlw Professor, seu curso está me fazendo crescer absurdamente.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
