### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#228]
Link do repositório com a implementação do quiz: https://github.com/Hamiltonspjunior/quiz-interativo-js-puro

#### Maiores dificuldades: 
- Refatoração do código
- Conseguir escolher quais funções desacoplar e quais nomes escolher
- Escolher qual a melhor fluxo do código durante a refatoração

#### Menores dificuldades:
- Implementação da lógica da aplicação
- Lidar com a manipulação do DOM

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @Hamiltonspjunior.

Passando para avisar que sua issue foi visualizada, e que a verificação dos requisitos para a análise da aplicação será feita em breve. Se estiver tudo ok, a análise será publicada aqui =)

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Parabéns pelo esforço em implementar a aplicação =)

Você exibiu os pontos e pelo que percebi, você entendeu bem a lógica até aqui.

Vou deixar abaixo algumas oportunidades de melhoria. Vamos lá:

### Usabilidade

Você conseguiu implementar a exibição dos pontos, isso é bom. 

Perceba que quando o form é enviado, os pontos são exibidos na parte inferior da aplicação. 

- Form enviado:
![image](https://user-images.githubusercontent.com/29297788/109372045-38deac00-7886-11eb-9e44-19a468373fd6.png)

Se não houver algo que faça o usuário intuir que os pontos estão abaixo da visualização da tela, o mais provável é que ele pense que nada aconteceu depois de clicar no botão. 

Uma possível solução seria modificar o lugar da exibição dos pontos para logo acima do botão. Nas aulas seguintes você verá como implementar a exibição dos pontos no topo da aplicação, de forma que o olhar do usuário seja conduzido à exibição da pontuação.

### Lógica

No código abaixo, `userAnswer.length` sempre resulta em `1`, pois `userAnswer` é uma string que contém apenas um caractere:

```javascript
const checkUserAnswer = (userAnswer, index) => {
  const isCorrectAnswer = userAnswer === correctAnswers[index]

  if (isCorrectAnswer) {
    score += 25 / userAnswer.length
  }
}
```

Sendo assim, `25 / 1` sempre resulta em `25`.

Por que `25` está sendo dividido por `userAnswer.length`?

### Organização do código

#### Local de invocação do `setAttribute`

Ao invés de setar a classe do `scoreMessage` no escopo global, em termos de organização de código, faz mais sentido fazer isso junto à manipulação do texto do elemento, dentro da função `insertScoreIntoScreen`:

```javascript
const insertScoreIntoScreen = () => {
  scoreMessage.setAttribute('class', 'my-3 text-dark')
  scoreMessage.textContent = `Você acertou ${score}% das questões`

  form.insertAdjacentElement('afterend', scoreMessage)
}
```

Isso evita deixar o `setAttribute` "solto" no escopo global da aplicação.

#### Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. 

Mas, evite o excesso. 

No código abaixo, você pode agrupar as invocações do `forEach` e da `insertScoreIntoScreen`, eliminando a linha em branco entre as invocações.

```javascript
// antes
const getQuizResult = event => {
  // ...
  const userAnswers = [
    // ...
  ]

  userAnswers.forEach(checkUserAnswer)
  
  insertScoreIntoScreen()
}
```

Seguindo este princípio, você está separando a declaração do array das invocações dos métodos. Ficaria assim:

```javascript
// depois
const getQuizResult = event => {
  // ...
  const userAnswers = [
    // ...
  ]

  userAnswers.forEach(checkUserAnswer)  
  insertScoreIntoScreen()
}
```

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código. Exemplo:

```javascript
// antes
const insertScoreIntoScreen = () => {
  scoreMessage.textContent = `Você acertou ${score}% das questões`

  form.insertAdjacentElement('afterend', scoreMessage)
}

// depois
const insertScoreIntoScreen = () => {
  scoreMessage.textContent = `Você acertou ${score}% das questões`
  form.insertAdjacentElement('afterend', scoreMessage)
}
```

#### Nomenclatura de funções

Você sacou bem que nomes de consts são substantivos e de funções são verbos. Seguindo esse princípio, fica mais fácil nomear variáveis e funções.

Uma função nomeada como `getQuizResult` está sendo referenciada como callback do submit do form. Geralmente, funções que começam com `get` retornam um valor ao serem invocadas. Get, em inglês, significa "obter". Ou seja, quando uma função `get*` é invocada, um valor é obtido.

Não é o caso dessa função.

Por isso, sugiro que ela seja renomeada `submitUserAnswers` ou algo parecido.

`checkUserAnswer` é usada como callback de um `forEach`. Isso significa que a função será executada para cada resposta do usuário. Então faz mais sentido que o nome da função seja `checkUserAnswers`, no plural.

`scoreMessage` é um nome vago para uma `const` que armazena um elemento do DOM. Eu a nomearia como `scoreMessageContainer` ou `scoreMessageEl` (el é uma abreviação de "element").

---

Sobre as maiores dificuldades que você listou:

> - Refatoração do código

Vem com a prática e o tempo. O mais importante você já fez, que é fazer funcionar.

> - Conseguir escolher quais funções desacoplar e quais nomes escolher

Desacoplar funções e saber nomear são duas habilidades diferentes que você adquire ao preticar refatoração seguindo a resposta do item acima.

> - Escolher qual a melhor fluxo do código durante a refatoração

Não se preocupe com o melhor agora. A prioridade é fazer funcionar. Depois você melhora.

Ficou claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Oi, Roger. 

Ficou mais claro sim. 

Implementei as melhorias seguindo suas sugestões e vejo que o código realmente ficou melhor e agora faz mais sentido. 

Link do repositório: https://github.com/Hamiltonspjunior/quiz-interativo-js-puro/blob/master/app.js

Sobre esse ponto: 

```js
const checkUserAnswer = (userAnswer, index) => {
  const isCorrectAnswer = userAnswer === correctAnswers[index]

  if (isCorrectAnswer) {
    score += 25 / userAnswer.length
  }
}
```

Na verdade foi um erro bobo que acabou me passando batido. 
A minha ideia aqui era fazer com que o score recebesse o resultado da operação: 100 (de 100%) / Total de questões. 
Para que dessa forma independente do total de questões a porcentagem sempre fosse correta, entende?

a ```userAnswer.length``` deveria ter sido ```userAnswers.length``` no plural, que é o array que armazena todas as respostas do usuário, mas depois da refatoração como descaoplei a função e usei o parametro do forEach ai acabou ficando desse jeito.

Refatorei o código e ficou assim:

```js
const checkUserAnswers = (userAnswer, index) => {
  const isCorrectAnswer = userAnswer === correctAnswers[index]

  if (isCorrectAnswer) {
    score += 100 / totalQuestions
  }
}
```
Muito obrigado pelo feedback, valeu muito a pena ter esse pente fino de alguém mais experiente para observar esses pontos de melhoria.

**Comment by Roger-Melo** [comment]
Excelente. 

Como ficou mais claro, vou fechar a issue por agora. Mas ao surgirem dúvidas, é só abrir uma nova =)
