### ISSUE TITLE
Fiz algo errado? ou apenas maneira diferente de resolver o problema?

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2283]
### Etapa da aula

3

### Nome da aula

  Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284

### Descreva a dúvida

Boa noite professor, minha dúvida é se a forma com que eu resolvi o exercício esta correta, mesmo estando diferente da forma que o senhor resolveu. 

essa foi a forma como resolvi:
```js

const functions = [
  function () { return 'Plymouth' },
  function () { return 'é' },
  function () { return 'uma' },
  function () { return 'cidade' },
  function () { return 'fantasma' },
  function () { return 'localizada' },
  function () { return 'na' },
  function () { return 'ilha' },
  function () { return 'de' },
  function () { return 'Montserrat,' },
  function () { return 'um' },
  function () { return 'território' },
  function () { return 'ultramarino' },
  function () { return 'do' },
  function () { return 'Reino' },
  function () { return 'Unido' },
  function () { return 'localizado' },
  function () { return 'na' },
  function () { return 'cadeia' },
  function () { return 'de' },
  function () { return 'Ilhas' },
  function () { return 'de' },
  function () { return 'Sotavento' },
  function () { return 'nas' },
  function () { return 'Pequenas' },
  function () { return 'Antilhas,' },
  function () { return 'Índias' },
  function () { return 'Ocidentais.' }
]


let newArray = []

for (let i = 0; i < functions.length; i++) {
  const phraseFunction = functions[i];
  newArray.push(phraseFunction())
}

const phraseArray = newArray.join(' ')

console.log(phraseArray)
```

Essa foi a forma que você resolveu:
```js
let sentence = ''

for (let i = 0; i < functions.length; i++) {
  const string = `${functions[i]()} ` 
  
  sentence += string
}

console.log(sentence);
```
Basicamente eu usei um array para armazenar o resultado da frase, para depois usar o método join(' '). 
Ou seja, essa lógica que usei da para aceitar?

muito obrigado, sei que não é o lugar, mas só relatar que graças as aulas estou conseguindo até o momento me virar muito bem nos exercícios, as vezes nem acredito que fiz certo. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103!

> ### Ou seja, essa lógica que usei da para aceitar?

Sim, é uma forma válida também =)

Apenas observe que na resolução mostrada na correção, não foi necessário criar um novo array para chegar ao resultado. Não fazer uma transformação de dados (array para string), neste caso, acaba resultando em um código mais simples. 

Mas novamente: sua resolução também chegou no resultado desejado =)

> ### muito obrigado, sei que não é o lugar, mas só relatar que graças as aulas estou conseguindo até o momento me virar muito bem nos exercícios, as vezes nem acredito que fiz certo. 

Fico muito feliz que esteja percebendo progresso. 

No que precisar, é só abrir uma issue. Conte comigo para chegar na fluência =)
