### ISSUE TITLE
Etapa 07, nome do vídeo: Exercícios da aula 01

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#229]
Olá novamente Roger. 

Bem, terminei de fazer o primeiro exercício da etapa 07 que é a primeira parte da implementação do quiz, porém ainda estou com algumas dúvidas sobre o fluxo da criação das aplicações durante o curso. 

A ideia é que nós mesmo consigamos implementar a aplicação sozinhos. 
Porém, depois de fazer essa primeira parte da aplicação eu vou seguir para a próxima aula onde você vai mostrar como exibir a pontuação na tela. 

Nesse ponto, se a forma como você fizer for diferente de como eu fiz eu devo refatorar o meu código para ficar igual ao seu? Assim como faziamos com os exercícios? 

Outra coisa: A ideia é que nós implementemos as aplicações da mesma forma como você mostra na aula ou podemos fazer de formas diferente? O código deve ficar igual ao seu?

Estou fazendo essas perguntas pois estou com medo de que no final eu esteja apenas copiando o seu código da aplicação, entende? E não de fato desenvolvendo sozinho.

Até por que como vou enviar o código para você fazer a análise da implementação fico me perguntando como você vai fazer essa análise se o código é igual ao seu, entende?

Poderia explicar qual a melhor forma de seguir nessas etapas das aplicações?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton. Estou passando para avisar que estou ciente dessa issue e que ela será respondida logo após você ver a [análise do quiz](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/228#issuecomment-786990440) que acabei de responder.

Primeiro, preciso me certificar que você entendeu os pontos que observei para então responder as perguntas acima =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Oi, Roger. 

Já verifiquei a análise que você fez e compreendi os pontos apresentados. 

Implementei as melhorias no código e te respondi naquela issue.

Muito obrigado.

**Comment by Roger-Melo** [comment]
Oi, Hamilton.

Legal. Os critérios geralmente são aqueles 3: usabilidade, lógica e organização do código. E esses critérios podem conter subcritérios.

O critério de organização de código, por exemplo, tem linhas em branco, nomenclatura e refatoração como subcritérios. E assim sucessivamente.

Mas claro, o peso desses critérios depende do código do aluno. Se a aplicação possui muitos ajustes de lógica, não faz sentido eu cobrar ajustes de refatoração. 

> Outra coisa: A ideia é que nós implementemos as aplicações da mesma forma como você mostra na aula ou podemos fazer de formas diferente? O código deve ficar igual ao seu?

Eu recomendo que sim. Pois a forma que eu mostro de resolver um exercício ou de construir uma aplicação geralmente envolve princípios que serão intensificados nas próximas etapas.

Se esses princípios não foram praticados antes, as chances de você não entender o que vou mostrar mais à frente é maior.

> depois de fazer essa primeira parte da aplicação eu vou seguir para a próxima aula onde você vai mostrar como exibir a pontuação na tela. 

No decorrer do treinamento você descobrirá que não existe software "pronto". Sempre há o que melhorar e/ou implementar. Então não considere que uma determinada aplicação está pronta. Você verá que alguns exercícios do treinamento envolvem justamente refatoração e manutenção das aplicações.

> Estou fazendo essas perguntas pois estou com medo de que no final eu esteja apenas copiando o seu código da aplicação, entende? E não de fato desenvolvendo sozinho.

Sim. É exatamente por isso que eu recomendo que você siga [este](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x) passo a passo antes de começar a implementar qualquer aplicação no treinamento e [este](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) passo a passo quando fizer a resolução de um exercício de forma diferente da que mostrei na correção.

Essa é a forma de repetição mais eficaz que conheço para fazer conceitos complexos se tornarem automáticos em seu cérebro.

Está ficando mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Está sim.

Vou seguir confirme você sugeriu, muito obrigado.

**Comment by Roger-Melo** [comment]
Legal @Hamiltonspjunior. No que tiver dúvida, é só perguntar =)
