### ISSUE TITLE
Resumo da Aula 01da etapa 04

### ISSUE THREAD

**Issue by HenriqueAnraki** [roger-melo-treinamentos/curso-de-js-roger-melo#2297]
## Aula 01-02 - O que são objetos

- Objetos
    - Um dos núcleos da linguagem
    - Estruturas de dados que representam elementos do código/aplicação
- Propiedades
    - Características
- Métodos
    - Ações
- Objetos acoplados
    - Date
    - Math
- Diversas formas de criação
    - Objetos literais

## Aula 01-03 - Criando um objeto literal

- Usamos `{}` para criar objetos literais
    - Propriedades definidas dentro
    - Pares `chave: valor`
        - Separados por vírgula
- Propriedades são acessadas com:
    - . (ponto)
        - user.name
    - []
        - user['name']
        - Possibilita acesso com variáveis
- Ler e sobrescrever

## Aula 01-04 - Adicionando métodos

- Métodos são funções criadas dentro de um objeto
- o valor é uma definição de função

```jsx
let user = {
	name: 'João',
	login: function () {
		console.log('Usuário logado')
	}
}
```

**Comment by Roger-Melo** [comment]
Boa @HenriqueAnraki, rumo à fluência! 🔥
