### ISSUE TITLE
Retorno das funções getCityData e getCityWeather

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2299]
### Etapa da aula

12

### Nome da aula

Obtendo as informações que serão exibidas na interface - Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1441038

### Descreva a dúvida

Bom dia @Roger-Melo.

Fiquei um tempo afastado do curso mas estou voltando agora. 
Estou construindo a aplicação Weather App e me surgiu uma dúvida a respeito do retorno das funções getCityData e getCityWeather. 

```js
const getCityData = cityName => fetchData(getCityUrl(cityName))
const getCityWeather = cityKey => fetchData(getWeatherUrl(cityKey))
```

Ambas retornam promisses com os Arrays de objetos contendo os dados necessários. Não seria melhor que esses arrays fossem tratados dentro dessas funções para ao invés de retornar uma promisse retornar diretamente os dados que vamos usar?

Dessa forma iriamos evitar fazer os destructurings nas propriedades que queremos e também evitariamos que a função do listener  de submit do form fosse async, não?

```js
const [{Key, LocalizedName}] = await getCityData(inputValue)
const [{Temperature, WeatherText}] = await getCityWeather(Key)
```

Por que, então, retornar promisses nessas funções ao invés apenas dos dados necessários ou pelo menos dos arrays já tratados com esses dados?

Obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, @Hamiltonspjunior.

Passando rapidinho pra avisar que vi sua issue e mais tarde respondo com calma.

Estou sem energia e indo pro médico daqui a pouco.

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior. Bem vindo de volta! =D

Vc pode testar desse jeito sim. 

De qualquer forma, em breve vc encontrará o aviso para enviar a aplicação para a análise. 

Se vc achar que faz mais sentido da forma que sugeriu, faça e envie que eu te dou um feedback sobre as vantagens e desvantagens dessa decisão na aplicação. Combinado? =)

**Comment by Hamiltonspjunior** [comment]
Perfeito, @Roger-Melo. 

Vou continuar assistindo as aulas e quando terminar vou construir a aplicação do zero e enviar para análise. 

Falando nisso, houve alguma mudança no processo para enviar as aplicações para análise? 
Tem algo de diferente que devemos fazer ou mudou algo nos critérios para que seja feito o envio?

Obrigado.

**Comment by Roger-Melo** [comment]
> ### Agora podemos incluir funcionalidades que não foram mostradas nas aulas, por exemplo?

Não. O novo template é pra checar se quem tá enviando tá ligado nos critérios =)

Enviei o email sobre análise de aplicações para vc. Dá uma olhada se chegou e me diz aqui =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
O e-mail chegou sim. 

Bem, então tudo certo. Vou implementar a aplicação e em breve te envio para análise. 

Muito obrigado.

**Comment by Roger-Melo** [comment]
Show. No que precisar é só abrir uma nova issue =)
