### ISSUE TITLE
Duvida sobre async\await

### ISSUE THREAD

**Issue by tuxpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#23]
Ola Roger, tudo bem?

Quando escrevo o seguinte código utilizado "async/await" um erro é lançado no console dizendo que ".json()" não é uma função

```javascript
const getUsers = async () => {
    const response = fetch('https://jsonplaceholder.typicode.com/users')
    const users = await response.json()
    console.log(users)
}

getUsers()
```
```
Uncaught (in promise) TypeError: response.json is not a function
        at getUsers (App.js:3)
        at App.js:7
        getUsers @ App.js:3
        (anonymous) @ App.js:7
```

Quando utilizado o "await" duas vezes no momento de armazenar a resposta em uma const as promises são resolvidas, observe o seguinte código:

```javascript
const getUsers = async () => {
    const response = fetch('https://jsonplaceholder.typicode.com/users')
    const users = await (await response).json()
    console.log(users)
}

getUsers()
```
```javascript
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
```

Fiz uma breve pesquisa mas não encontrei nenhum exemplo de código semelhante.

Agradeço pela atenção.

Um abraço.

**Comment by Roger-Melo** [comment]
Oi @tuxpedro!

Legal, vamos lá =D

> Quando escrevo o seguinte código utilizado "async/await" um erro é lançado no console dizendo que ".json()" não é uma função

```javascript
const getUsers = async () => {
    const response = fetch('https://jsonplaceholder.typicode.com/users')
    const users = await response.json()
    console.log(users)
}

getUsers()
```

Observe que na expressão que a `response` recebe, não há um `await` inserido antes da invocação do `fetch`. Isso faz com que a `response` receba uma promise (objeto).

Como o `json()` é um método do objeto response que a promise está armazenando, e como não existe um método `json()` no objeto promise, o TypeError é lançado.

Então nesse caso, basta inserir o `await` antes da invocação do fetch.

> Quando utilizado o "await" duas vezes no momento de armazenar a resposta em uma const as promises são resolvidas, observe o seguinte código:

```javascript
const getUsers = async () => {
    const response = fetch('https://jsonplaceholder.typicode.com/users')
    const users = await (await response).json()
    console.log(users)
}

getUsers()
```

Neste caso, observe que mesmo que não haja um `await` antes da invocação do `fetch`, essa expressão dos parênteses (que é executada antes de qualquer outro código da expressão),

```javascript
(await response)
```

resulta no valor da promise (que é o objeto `response`), e o encadeamento da invocação do `json()` faz a expressão abaixo,

```javascript
(await response).json()
```

resultar em uma promise que contém o array de objetos. Lembrando que o `json()` retorna uma promise.

Como a expressão acima resulta em uma promise e há um `await` inserido antes dela,

```javascript
const users = await (await response).json()
```

a `users` armazena o valor da promise resolvida, que é o array de objetos.

Ficou mais claro?

Se ainda houverem dúvidas pode perguntar =)

**Comment by tuxpedro** [comment]
Olá Roger, 

Muito obrigado pela ajuda super esclarecido :smiley: :+1:

**Comment by Roger-Melo** [comment]
Show @tuxpedro! No que precisar, é só perguntar =)
