### ISSUE TITLE
Resumo da Aula 01-03 e Aula 01-04 da etapa 3

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#230]
/*-------------------------------------------------------------------------------------------------
Etapa 3 - Aula 01-03
-------------------------------------------------------------------------------------------------*/

/*

Funções

*/

//Function Declaration

function sayHI () {
    console.log('oi')
}

// Functon Expression

//sayHI()

/*
Em function declaration, criamos um código simples para dizer "oi" sempre que a função sayhi
fosse invocada. No entanto, mesmo que semelhante ao For Loop, o console.log não é invocado na 
mesma declaração. Portanto, em Function Expression, utilizamos outra função e invocamos o sayHI.
*/

// Exemplo

function goodNight () {
    console.log('Boa noite!')
}

//goodNight()

//

const showFood = function () {
    console.log('Pizza')
}

//showFood()

/*
Funções podem ser criadas dentro de constantes. Por mais que pareça não fazer diferença, faz.
Isto acontece por causa do hoisting, que será explicado a//baixo.
*/

//sayHello()
//sayHello()
//sayHello()

function sayHello () {
    console.log('hello')
}

/*
Aqui está o hoisting. Mesmo que coloquemos a declaração da função abaixo da sua própria
invocação, o código é executado normamelmente. Quando o console lê esse código,
por baixo dos panos, ele leva a declaração para o topo, evitando um erro na executação.
Quando usamos constantes, isso não ocorre.*/

/*-------------------------------------------------------------------------------------------------
Etapa 3 - Aula 01-04
-------------------------------------------------------------------------------------------------*/

/* 

Argumentos, parâmetros e default parameters

*/

// Code Declaration

const myFunc = function (name, lastName) {
    console.log(`Oi, ${name} ${lastName}!`)
}

myFunc('Roger', 'Melo')

/*
Agora vemos que é possível mesclar diversos conceitos de JS apenas usando funções. Na declaração da
função, além de definir um código a ser executado após a invocação, criamos uma variável cujo valor 
ainda não foi definido. Na convocação da função, demos um valor para essa variável, que, mesmo
estando invertida, com o valor embaixo e a convocação em cima, funcionou.
*/

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal @YureK-a. Rumo à fluência! 🥇
