### ISSUE TITLE
Resumo da Aula 01-03 da etapa 03

### ISSUE THREAD

**Issue by ecabral-29** [roger-melo-treinamentos/curso-de-js-roger-melo#2302]
Maneiras de declarar uma função:

**//Function declaration**

function sayHi () {
    console.log('oi')
}

**//Function expression**

const showFood = function () {
    console.log('pizza')
}

Ao criar uma "function declaration", o JS puxa a função para o topo do arquivo. Esse conceito é chamado de "Hosting", sendo possível invocar a função antes da declaração.

Ao criar uma "function expression", a declaração da função deve ser feita antes da invocação, pois nesse caso o JS não  puxa a função para o topo.

Prefira usar "function expression", facilitando a análise e deixando o código mais simples.

**Comment by Roger-Melo** [comment]
Boa @ecabral-29, rumo à fluência! 🔥
