### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes css  02-05 da etapa 05

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2304]
Para obter uma lista de classes que um elemento possui, utilizamos a propriedade _**.classList**_.
```js
console.log(nome_do_elemento.classList) // exibe a lista de classes do elemento especificado
```
Utilizando esta propriedade com o método _**.add()**_, é possível adicionar uma classe ao elemento.
```js
nome_do_elemento.classList.add(nome_da_classe) // adiciona a classe (especificada dentro dos parênteses) no elemento
```
De forma análoga ao item anterior, para remover uma classe, utilizamos o .remove().
```js
nome_do_elemento.classList.remove(nome_da_classe) // remove do elemento a classe especificada
```
Podemos também adicionar uma classe que não existe em um determinado elemento ou remover uma classe já existente, utilizando para isto o método **_.toogle()_**.
```js
nome_do_elemento.toogle(nome_da_classe) // se o elemento não possuir a classe especificada, esta é adicionada a ele. Caso exista, ela será removida
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
