### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários -  Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#231]
## Constantes e variáveis

Variáveis são utilizadas para armazenar um valor que pode ser utilizado no decorrer da aplicação. Uma variável pode ter seu valor modificado, desde que ela seja declarada com a palavra-chave: `let` ou `var`. Mas, também é possível declarar uma variável na qual seu valor é imutável, ou seja, não pode ser alterado, para isso declaramos a variável com a palavra-chave `const`. Os valores que as variáveis armazenam são guardados na memória e o nome da variável é apenas um identificador para acessar estes valores armazenados na memória.

### Regras para criar uma variável

- Seu nome deve ser único;
- Utilizar sempre o padrão camelCase;
- Não pode nomear uma variável com o mesmo nome de palavras reservadas da linguagem.

## Comentários

```jsx
// comentário de uma linha
/*
	Comentário
	multilinha
*/
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel. Rumo à fluência 🚀
