### ISSUE TITLE
Retornar um boolean de um método, exemplo: form.addEventListener('keyup' event...

### ISSUE THREAD

**Issue by andersoncsiqueira** [roger-melo-treinamentos/curso-de-js-roger-melo#2316]
### Etapa da aula

6

### Nome da aula

Eventos de Teclado

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/927205

### Descreva a dúvida

```
  form.addEventListener('keyup', event => {
   return event.value == 'X' 
}


```

Gostaria de retornar um boolean usando o addEventListener, já tentei criar uma variável e atribuir o form com o método anteriormente citado, mas o resultado foi undefined quando tentei demonstrar tal variavél no console, talvez seja por conta do parâmetro 'keyup', gostaria de saber se existe alguma forma de retornar true ou false usando um evento de teclado. 

(Não é bem uma dúvida sobre a aula, é uma curiosidade que surgiu ao fazer alguns testes.)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @andersoncsiqueira!

> ### Gostaria de retornar um boolean usando o addEventListener

Essa é uma forma de fazer isso:

```javascript
const form = document.querySelector('form')

const handleKeyup = event => {
  console.log('keyup executado')
  return 'qualquer valor'
}

form.addEventListener('keyup', handleKeyup)

console.log(handleKeyup()) // 'qualquer valor'
```

Como o `addEventListener` precisa receber a declaração ou referência de uma função como segundo argumento, vc pode atribuir a função à uma const e apenas referenciar a função no segundo argumento.

Toda vez que essa função for executada (seja no disparar do evento ou não), ela vai retornar qualquer valor à direita do `return`.

Dito isso, eu nunca precisei ou vi alguém que precisou fazer isso. Não faz muito sentido retornar valor em um callback de evento.

---

> ### já tentei criar uma variável e atribuir o form com o método anteriormente citado, mas o resultado foi undefined quando tentei demonstrar tal variavél no console, talvez seja por conta do parâmetro 'keyup'

```javascript
const form = document.querySelector('form')

const addEventListenerReturn = form.addEventListener('keyup', () => {})
console.log(addEventListenerReturn) // undefined
```

Vc tentou fazer isso?

Se sim, observe que a const `addEventListenerReturn` está recebendo o valor retornado pela invocação de `addEventListener`.

A invocação de `addEventListener` não retorna valor e em JavaScript, um pedaço de código que não retorna valor, por baixo dos panos retorna `undefined`. Vc ainda verá isso em vários casos diferentes no treinamento.

Ficou mais claro?

---

Vc não perguntou, mas fica ligado no seguinte...

No código que vc postou, faltou o parênteses do final da invocação do `addEventListener`. O `addEventListener` é um método no qual a invocação recebe 2 argumentos. Vc precisa fechar o parênteses após o segundo argumento, caso contrário seu código irá lançar um `Uncaught SyntaxError: missing ) after argument list`. Antes de postar o código, teste ele em sua máquina para ver se ele está se comportando como vc espera. Aí é só dar um ctrl c + ctrl v =)

No código postado, foi usado `==` ao invés de `===`. O recomendado é que vc fuja de operadores de comparação não-estrita e eu expliquei por que [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751262).

Vc adicionou `keyup` diretamente no form, essa realmente era a intenção? Fique atento, se o form tiver 2 inputs por exemplo, o evento vai ser executado nesses 2 inputs =)

---

Ao inserir links das aulas nas issues, prefira postar o link da aula **na plataforma**, e não do vídeo do yt. O motivo é muito simples... Quando essa aula for regravada, o vídeo do link que vc postou na issue não existirá mais. Já ajustei o link na issue.

**Comment by andersoncsiqueira** [comment]
Olá, Roger-Melo =) 

Obrigado pela resposta rápida, 

> Vc tentou fazer isso?

Sim, tentei. 

> Vc não perguntou, mas fica ligado no seguinte...

Estou captando vossa mensagem, vou repostar o código completo que refiz depois de ler sua resposta: 


const form = document.querySelector('form')

const handleKeyup = event => {
    console.log('keyup executado')
    return event.value === 'x'
}

form.addEventListener('keyup', handleKeyup)

if(handleKeyup()) {
    console.log('Retournou true')
} else {
    console.log('Retornou false')
}

No console ainda aparece o seguinte erro 'Uncaught TypeError: Cannot read properties of undefined (reading 'value'')

Mesmo depois de apertar alguma tecla a mensagem de erro persiste e o if não é disparado. 

(O 'console.log('keyup executado')' aparece no console, uma vez antes do evento ser disparado e se repete depois do disparo. )


> Dito isso, eu nunca precisei ou vi alguém que precisou fazer isso. Não faz muito sentido retornar valor em um callback de evento.

> A invocação de addEventListener não retorna valor e em JavaScript, um pedaço de código que não retorna valor, por baixo dos panos retorna undefined. Vc ainda verá isso em vários casos diferentes no treinamento.

Estou compreendendo e visualizando melhor o que ocorreu nessa minha peripécia =D Obrigado!

**Comment by Roger-Melo** [comment]
> ### No console ainda aparece o seguinte erro 'Uncaught TypeError: Cannot read properties of undefined (reading 'value')

Preste muita atenção na mensagem do erro.

Observe que essa msg diz que não é possível ler propriedades de `undefined` e, entre parênteses, tem um `(reading 'value')`. Ou seja, o erro aconteceu ao ler a propriedade value.

No seu código, no que vc especificou a propriedade `value`?

No `event`. 

Isso significa que o `event` (que deveria conter o objeto com informações do evento) está armazenando `undefined`.

Você pode comprovar isso se exibir o valor dele no console:

```javascript
const handleKeyup = event => {
  console.log(event) // undefined
  return event.value === 'x'
}
```

Toda vez que um erro é lançado, **vc precisa checar se as variáveis/parâmetros em seu código estão armazenando os valores que você espera**. O nome disso é debugar, é uma habilidade que vc precisa treinar.

O motivo que levou `event` a armazenar `undefined` é simples: o objeto com informações sobre o evento só é atribuído para o parâmetro `event` quando o evento acontece =)

No código abaixo, 

```javascript
if (handleKeyup()) {
  console.log('Retournou true')
}
```

a função `handleKeyup` foi executada sem argumento e sem o evento de keyup ter acontecido no `form`.

Se não tem argumento na invocação, o parâmetro recebe `undefined`.

Se não tem evento, não tem objeto com informações do evento pra atribuir pro parâmetro. Sacou?

Se vc comentar a invocação da função, o erro desaparece.

Se após comentar, vc testar o input agora, 'keyup executado' é exibido no console pq o evento foi de fato executado.

Dica: agora que vc sabe que precisa debugar o código... será que a expressão `event.value` está resultando no valor que vc acha que ela está? 👀

@andersoncsiqueira

**Comment by andersoncsiqueira** [comment]
> Dica: agora que vc sabe que precisa debugar o código... será que a expressão event.value está resultando no valor que vc acha que ela está? 

`const form = document.querySelector('form')

const handleKeyup = event => {
    console.log(event.key)
    return event.key === 'x'
}

form.addEventListener('keyup', handleKeyup)`

Consegui acessar ao valor da tecla ao usar a propriedade key, bastou explorar o KeyboardEvent no console =D 

> Se não tem evento, não tem objeto com informações do evento pra atribuir pro parâmetro. Sacou?

Compreendi sim! 

> Toda vez que um erro é lançado, vc precisa checar se as variáveis/parâmetros em seu código estão armazenando os valores que você espera. O nome disso é debugar, é uma habilidade que vc precisa treinar.

Irei virar um debugante kkkk 

Obrigado!

**Comment by Roger-Melo** [comment]
> ### Irei virar um debugante kkkk 

Boa! =D

Só um complemento... Se a intenção era que a expressão `event.value` resultasse no valor do elemento no qual o evento foi atrelado, lembre-se de usar a propriedade `target`. 

Você lembra o que essa propriedade retorna?

Assista novamente [essa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871195) para relembrar e me diz aqui como vc pode usar essa propriedade nesse código. Só pra eu sacar que vc entendeu =)

@andersoncsiqueira

**Comment by andersoncsiqueira** [comment]
> ó um complemento... Se a intenção era que a expressão event.value resultasse no valor do elemento no qual o evento foi atrelado, lembre-se de usar a propriedade target.

Você lembra o que essa propriedade retorna?


Lembro que a proprieda target retorna o elemento alvo do evento, colocando (event.target.value) vai retornar o valor dentro do elemento, 'x' por exemplo, caso eu tenha apertado a tecla 'x'.  Correto? =D

**Comment by Roger-Melo** [comment]
Isso mesmo =)

Quando precisar obter o valor do elemento no qual o evento aconteceu, ao invés de usar `event.value`,  use `event.target`. 

Se `event.target` resulta na referência do elemento e o elemento é um `form` ou `input`, por exemplo, vc pode encadear `.value` na referência desse input. Ficando `event.target.value`.

Era só pra reforçar esse conceito mesmo xD

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
