### ISSUE TITLE
Aplicação: Quiz-Interativo

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2318]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/carlosdevjs/Quiz.git

### Maiores dificuldades durante a implementação

Refatoração dos inputs enviados do usuário, implementação do popup, 

### Menores dificuldades durante a implementação

implementação do evento.

**Comment by carlosdevjs** [comment]
@Roger-Melo , boa tarde se vc aprovar eu darei prosseguimento as aulas, estou pesquisando os assuntos, para preparar os neurônios.

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Análises de aplicações são publicadas em até 5 dias úteis e, não recomendo que vc espere esse tempo para prosseguir com as aulas. =)

Dê continuidade no treinamento normalmente e quando a análise estiver formulada, publico aqui.

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Muito bom =) 

Sentiu que o código ficou mais simples?

---

Agora que vc ajustou a lógica, eu olharia para aspectos de organização do código.

Vou dar alguns exemplos.

### Linhas em branco

Lembrando: linhas em branco indicam, visualmente, a separação entre conceitos e o ideal é que vc evite o excesso ou a falta delas no código.

Seguindo esse princípio, a linha 69 pode ser removida e uma linha em branco pode ser adicionada entre as declarações de `animationResultFinale` e `updateQuiz`.

---

### Nomes de variáveis/parâmetros

Como comentei [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2276#issuecomment-974875611), no tópico `Nomes de variáveis e funções`:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso, como `closedPopup` armazena um boolean, ela poderia se chamar `shouldClosePopup`, por exemplo.

Como `endClosedPopup` é uma função na qual a ação é fechar o popup, eu a nomearia como `closePopup`. Inclusive, vc pode observar os locais onde a função é usada e comparar quais nomes fazem mais sentido ao ler a linha:

```javascript
popup.addEventListener('click', endClosedPopup)
popup.addEventListener('click', closePopup)
```

Algumas outras pequenas mudanças que eu faria nos nomes:

- `isResultResponseUser` => `isAnswerCorrect`
- `listNames` => `CSSClasses`
- `listName` (parâmetro do some) => `CSSClass` (singular de item do array `CSSClasses`)

---

Mas como eu disse em oportunidades passadas, o mais importante num primeiro momento você já fez, que é fazer funcionar. Sua progressão em relação à análise passada já é perceptível.

Organização de código e refatoração são secundários. Primeiro fazemos funcionar. Depois, melhoramos, ok? =)

**Comment by carlosdevjs** [comment]
Obrigado pelo feedback, rumo a fluência.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)

Rumo à fluência 🔥
