### ISSUE TITLE
Acessando o valor de uma promisse

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2319]
### Etapa da aula

12

### Nome da aula

Aviso importante

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2829246

### Descreva a dúvida

 Olá, Roger. 

 Uma coisa que aparentemente não tinha ficado muito claro pra mim mas que agora, desenvolvendo a Weather App ficou, é que quando lidamos com promisses para acessar o resultado delas temos duas formas: Ou usar um then, ou então Async/Await. 

Porém em ambos os casos o retorno sempre será uma nova promisse, certo? Então não importa onde eu for usar esses valores eu sempre vou precisar desencapsular essa promisse usando um then ou async/await, certo?

Não há nenhum jeito de retornar ou armazenar o valor de uma promisse sem que ela seja encapsulada por outra promisse?

O que quero dizer é: 
```js
const [cityData] = await fetchData(getCityUrl(cityName))
const cityData = fetchData(getCityUrl(cityName)).then(response => response)
```

Em ambos os casos acima o valor que cityData vai armazenar sempre será uma nova promise e quando eu for usá-la, terei que desencapsular esse valor, certo? 

Não tem um jeito de passar pra ela o resultado da promise, ou seja os dados, já desencapsulados? 
Para que eu possa retornar os dados diretamente?

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Não há nenhum jeito de retornar ou armazenar o valor de uma promisse sem que ela seja encapsulada por outra promisse?

Se eu entendi bem a dúvida, a resposta é: tem, e vc já sabe como. Apenas não "caiu a ficha", ainda =)

Olha só, no código abaixo, a função executa um request e retorna os dados que obteve:

```javascript
const fetchData = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await response.json()

  return data 
}

fetchData()
/*
☝🏻 Retorna, encapsulado em uma promise, o objeto 
{userId: 1, id: 1, title: 'delectus aut autem', completed: false}

Afinal, toda função async retorna uma promise.
*/
```

Você quer eliminar a necessidade de ter que usar async/await para desencapsular o valor da promise que a invocação de `fetchData` retorna, certo?

Você pode inserir esse valor como argumento de uma função:

```javascript
const render = data => {
  document.body.innerHTML = `${data.title}`
}

const fetchData = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await response.json()

  // 👇🏻 "data" foi atribuído ao parâmetro "data" da função "render"
  render(data)
}

fetchData()
```

Dessa forma, no escopo de `render`, vc tem acesso ao objeto sem ter que depender do retorno da `fetchData`.

Respondi a dúvida?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Respondeu sim mas, na verdade, eu estava me referindo a uma forma de retornar os dados diretamente, usando o return. Mas nesse caso parece que não dá, já que uma função async sempre vai retornar uma promise e eu terei que lidar com ela. 

Mas se eu entendi bem a resposta, nesse caso a função que lida com os dados teria que sempre estar no escopo da fetchData para assim passar os dados diretamente pra ela, certo?

No exemplo você usou essa função render, mas eu poderia passar uma função como argumento da fetchData e executar ela no lugar da render. Dessa forma a fetchData ficaria mais genérica e eu conseguiria executar uma ação diferente pra cada request, correto?. 

Bem, vou testar essa implementação na weather app e ver como fica. Pelo menos vai ser bem didático. 

De novo, obrigado!

**Comment by Roger-Melo** [comment]
> ### No exemplo você usou essa função render, mas eu poderia passar uma função como argumento da fetchData e executar ela no lugar da render. Dessa forma a fetchData ficaria mais genérica e eu conseguiria executar uma ação diferente pra cada request, correto?. 

Com certeza =)

---

> ### Só mais uma dúvida. O que originou essa minha questão foi o fato da função do submit do form precisar ser uma função async, por que a primeira vista ela não me parecia que precisava ser, já que a função de submit deveria apenas lidar com o evento.

Lembra que requisições são operações assíncronas?

Se a função de callback de um evento submit tem uma requisição dentro dela, ela precisa ter uma forma de tratar o retorno dos dados quando eles forem obtidos. 

```javascript
const form = document.querySelector('form')

const render = data => {
  document.body.innerHTML = `${data.title}`
}

const fetchData = async e => {
  e.preventDefault()
  
  // 👇🏻 fetch executa uma operação assíncrona (requisição)
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await response.json()

  render(data)
}

form.addEventListener('submit', fetchData)
```

Se then e catch forem usados ao invés de async/await, a função não terá a palavra-chave `async` na declaração dela, mas continuará executando uma operação assíncrona de qualquer forma:

```javascript
const form = document.querySelector('form')

const render = data => {
  document.body.innerHTML = `${data.title}`
}

// 👇🏻 versão sem async
const fetchData = e => {
  e.preventDefault()

  // 👇🏻 mas o fetch continua executando uma operação assíncrona (requisição)
  fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => response.json())
    .then(render)
    .catch(console.log)
}

form.addEventListener('submit', fetchData)
```

Se dentro dessa função de callback não houvesse uma operação assíncrona, aí sim não teria sentido ela ser uma função que usa async/await (ou promises).

Ficou mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Ficou sim, deu pra entender bem melhor agora. 

Obrigado!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
