### ISSUE TITLE
Devo colocar "minha" chave para acessar a API do AccuWeather no código do Weather App?

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#2320]
### Etapa da aula

12

### Nome da aula

Inserindo na interface os ícones e imagens - Aula 02-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1448904

### Descreva a dúvida

Oi Roger, tudo bem?

Estou me preparando para submeter o Weather App e gostaria de saber se meu código deve incluir a chave pra API  que eu criei ou se você se você usa uma chave própria.

Obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende.

Isso mesmo, pode inserir a chave que vc gerou =)

**Comment by francisko-rezende** [comment]
Show, muito obrigado pela resposta!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
