### ISSUE TITLE
Aplicação: Todo List

### ISSUE THREAD

**Issue by paulozy** [roger-melo-treinamentos/curso-de-js-roger-melo#2322]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/paulozy/To-do

### Maiores dificuldades durante a implementação

No geral não tive muitas dificuldades, e com toda certeza a que me deixou mais chateado foi referente a refatoração do código e criar a filtragem dos todos, além disso, tentei implementar a sua dica de usar dataset para remover os elementos porém não entendi como funciona exatamente e então desisti de fazer dessa forma, usei a forma "padrão" usando as classes mesmo.

### Menores dificuldades durante a implementação

Um dos fatores que me surpreendeu foi conseguir adicionar algum elemento no DOM, antes tinha muita dificuldade quando assistia outros cursos, a mesma coisa com o event delegation para realizar a remoção dos elementos.

**Comment by Roger-Melo** [comment]
Olá @paulozy.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @paulozy!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### No geral não tive muitas dificuldades, e com toda certeza a que me deixou mais chateado foi referente a refatoração do código e criar a filtragem dos todos, além disso, tentei implementar a sua dica de usar dataset para remover os elementos porém não entendi como funciona exatamente e então desisti de fazer dessa forma, usei a forma "padrão" usando as classes mesmo.

Tudo bem, nas aulas seguintes vc verá formas de refatorar o código. 

Não fique chateado com refatoração. 

Refatoração é uma habilidade que é elevada com a prática e o tempo. Num primeiro momento, o mais importante é fazer funcionar. Depois, conforme for avançando, vc melhora o código que implementou =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

O input de adicionar to-do está focado ao carregar a aplicação, isso é bom para a usabilidade, pois o usuário não precisa pegar o mouse e tocar/clicar no input antes de adicionar um to-do.

No geral, vc nomeou bem suas variáveis.

---

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode eliminar (de baixo para cima) as linhas 66, 64, 37, 33 e 6.

Algumas dessas linhas em branco são a primeira ou última linha de um bloco. É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código =)

### Indentação

Boa indentação é um dos pilares de um código legível. 

Você pode indentar o template HTML para enfatizar, visualmente, que a string está em um nível de indentação mais profundo do que o bloco do if:

```javascript
// antes
  if(inputValue) {
    todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
      <span>${inputValue}</span>
      <i class="fas fa-times delete"></i>
    </li>
  `
  }
```

```javascript
// depois
  if(inputValue) {
    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
        <span>${inputValue}</span>
        <i class="fas fa-times delete"></i>
      </li>
    `
  }
```

### Refatoração

Para entender de fato essa forma de refatorar que vou mostrar, você precisa executar o passo a passo abaixo junto comigo, ok?

Primeiro, vamos voltar o código da `filterTodos` para a `searchTodo` e eliminar a `filterTodos` (por enquanto).

```javascript
const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.trim()
  const todos = Array.from(todosContainer.children)

  const filteredTodos = todos
    .filter(todo => !todo.textContent.includes(inputValue))

  const notFilteredTodos = todos
    .filter(todo => todo.textContent.includes(inputValue))

  filteredTodos.forEach(({ classList }) => {
    classList.add('hidden')
    classList.remove('d-flex')
  })

  notFilteredTodos.forEach(({ classList }) => {
    classList.add('d-flex')
    classList.remove('hidden')
  })
}
```

Agora, vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Vc pode, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ser exibido.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.trim()
  const todos = Array.from(todosContainer.children)

  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.includes(inputValue)
  }))

  console.log(newTodos)

  // const filteredTodos = todos
  //   .filter(todo => !todo.textContent.includes(inputValue))

  // const notFilteredTodos = todos
  //   .filter(todo => todo.textContent.includes(inputValue))

  // filteredTodos.forEach(({ classList }) => {
  //   classList.add('hidden')
  //   classList.remove('d-flex')
  // })

  // notFilteredTodos.forEach(({ classList }) => {
  //   classList.add('d-flex')
  //   classList.remove('hidden')
  // })
}
```

Agora que há um array de objeto que indicam se o to-do deve estar visível, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, dependendo da propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.trim()
  const todos = Array.from(todosContainer.children)

  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.includes(inputValue)
  }))

  filterTodos(newTodos)
}
```

Se vc quiser, pode deixar o código mais conciso, eliminando as consts `inputValue` e `todos`, e modificar o nome da `newTodos` para `todos`:

```javascript
const searchTodo = e => {
  e.preventDefault()

  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.includes(e.target.value.trim())
  }))

  filterTodos(todos)
}
```

Agora, observe o seguinte... 

Não faz sentido uma função chamada `validateInput` adicionar o to-do no DOM. 

Como não há uma validação complexa, vc pode eliminar a `validateInput` e concentrar o código de adição do to-do apenas na `addTodo`:

```javascript
const addTodo = e => {
  e.preventDefault()
  const inputValue = e.target.add.value.trim()
  
  if (inputValue) {
    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
        <span>${inputValue}</span>
        <i class="fas fa-times delete"></i>
      </li>
    `
  }

  e.target.reset()
}
```

### Lógica

Dito isso, vamos para algo mais importante (num primeiro momento) do que a refatoração.

Esse algo mais importante num primeiro momento é: fazer funcionar.

Antes de qualquer refatoração, assim que baixei e testei a aplicação (e não modifiquei isso), a filtragem não está funcionando dependendo se a string está maiúscula ou minúscula.

Por exemplo, existe um to-do `Assistir Breaking Bad` e, se `assistir` é inserido no input, esse to-do não é exibido:

![image](https://user-images.githubusercontent.com/29297788/143942377-3c06c1eb-4f81-4490-bde3-f3aaed4bee13.png)

Vc se lembra como resolver esse problema?

**Comment by paulozy** [comment]
Boa noite, Roger.

Li tudo o que foi dito acima e implementei as sugestões de código que você
deu, achei incrível a ideia de retornar um objeto com os todos e se ele
poder ser exibido ou não, pra falar a verdade não se conseguiria chegar a
essa conclusão. Gostaria de agradecer muito a sua pessoa, e ao seu curso
que tem me ensinado muito e eu estou me sentindo cada vez mais capacitado
de ter uma carreira como dev. Deixando de lado a melancolia, resolvi o
ultimo ponto citado por você referente a pesquisa com as letras minúsculas,
eu sabia que precisava usar o toLowerCase( ), só não sabia onde. Resolvi
deixar a preguiça de lado e fui testando em alguns lugares que faria
sentido, por exemplo na função searchTodo, e ficou dessa forma:

const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(newTodos)
}

Muito obrigado!!

Atte.

Paulo Ricardo de Abreu Santana

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
