### ISSUE TITLE
SOU DEFICIENTE VISUAL/AULA SEM NENHUMA ACESSIBILIDADE

### ISSUE THREAD

**Issue by developerJSJ** [roger-melo-treinamentos/curso-de-js-roger-melo#2325]
### Etapa da aula

11

### Nome da aula

Encadeando promises - Aula 04-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1309715

### Descreva a dúvida

Oi, tudo bem?

Sou deficiente visual, em todas as aulas da plataforma, como toda plataforma. Não tem acessibilidade. Um deficiente visual fica perdido.
Dou zoom na tela, mas tem tantosi incremento sna tela que dificulta 
a visualização(incrementos são as msgs, sei lá o que é aquilo).

O vídeo não se adequal a lupa do windows, fica horrível. O código é de difícil visualização, pois não pensaram nas pessoas com deficiência na hora de produzir a aula. Parece que o mundo não tem pessoas com deficiência visual. Não é assim.

Eu estou perdido nessa aula que coloquei o link, não tive como produzir todo o  código por conta da falta de acessibilidade e o professor não deixa o código produzido para se fazer dowload de forma simples e rápida. É preciso entrar e fazer uma issue para perdi.

Não tem como deixar um l ink para se baixar o código produzido? EU digo, o feito na aula para conferência do aluno? É preciso fazer uma viagem no git por todas as aulas e não achar?
Serio, desculpe as palavras. Mas iimageina você com 10% de visão procurando algo tão dificil de ser encontrado?

Por favor, pense nas pessoas com deficiência, facilidade, porque você deixa um link de pesquisa, mas não deixa um link para baixar o código feito em aula para conferência.

Eu peço esse favor de deixar. Estou com dúvida nessa aula acima. E para tirar dúvida tenho que viajar algumas horas pelo git hub e fazer uma issue...

No mais, eu não sei quando conseguirei entarr aqui e conferir a  resposta dessa issue(nem sei se acho). Então, por favor, me responda no e-mail, porque o senhor não responde pelo watssapp também.

Obrigado!!!!!!!!

**Comment by Roger-Melo** [comment]
@developerJSJ é a segunda issue que você abre dizendo que eu não respondo.

Eu acabei de olhar meu whatsapp e não tem mensagem lá.

Na issue passada, vc disse que eu não respondi seu email, sendo que não recebi email seu.

Inclusive, você pode me dizer qual é o seu nome e email? Assim fica mais fácil ajudar. 

Respondo todos os alunos do treinamento, sem excessão. Sei que deve ser complicado pra vc a questão da acessibilidade. Porém, não vou aceitar as afirmações de que não respondo sendo que nem sei quem é vc e não recebo mensagens/emails seus. 

Fico no aguardo de seu nome e email.
