### ISSUE TITLE
VS Code, Preferences, Color Theme: Seu Layout

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#2327]
### Etapa da aula

4

### Nome da aula

Dúvida de VSCode

### Link da aula

Dúvida de VSCode

### Descreva a dúvida

Professor Roger, tem algum template para as cores do meu VSCode ficarem as mais parecidas possíveis com as suas?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @shazenn!

Dá uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1435) e se ainda restar qualquer dúvida, pode responder aqui =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
