### ISSUE TITLE
A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#2329]
A palavra chave **this** é um objeto que representa o contexto atual no qual o código está sendo executado e mudará dependendo de como e onde é utilizado. A grosso modo, podemos pensar que **this** referenciará o que o contém, por exemplo, dentro de um método, ele representará o objeto no qual este método está sendo usado, desde que o método seja criado em uma **function declaration**.

Já em um método criado por Arrow function, this irá referenciar o objeto onde a invocação do método que o contém foi feita.

```js
let obj = {
    name: 'fulano',
    metodo: function(){
        console.log(`O nome é ${this.name}`)
    },
    metodo2: () =>{ // usando arrow function
        console.log(`O nome é ${this.name}`)
        console.log(this) // aqui é o método window
    }
}
console.log(this) // this aqui está referenciando window, então exibe as propriedades deste
obj.metodo() // this referencia o objeto que possui o método que o contém (no caso, obj), então exibe 'O nome é fulano'
obj.medoto2() // exibe apenas 'O nome é', pois this fez referência a window e este não possui método2 e nem a propriedade name, por isto, não há o que exibir além
```

Quando for usar o **this** dentro de um método, se a gente quiser que o **this** referencie o objeto no qual o método foi criado a gente precisa utilizar uma function declaration, ao invés de uma array function.

O método também pode ser declarado omitindo **: function** após o nome da propriedade. Exemplo:

```js
metodo (){ // JS entende que se trata de uma function declaration
    bloco de instruções
}
```

**Comment by Roger-Melo** [comment]
Excelente @ghostnetrn, rumo à fluência! 🎯
