### ISSUE TITLE
Resumo da Aula Destructuring em parâmetros de funções 04-01 da etapa 05

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2330]
Dado um objeto, podemos acessar as propriedades deste por meio do **_destructuring_**. O _destructuring_ consiste em declarar, entre chaves, os mesmo nomes das propriedades que desejamos acessar e atribuirmos o objeto a estes. Desta forma, conseguimos acessar de forma mais simples os valores das propriedades, sem a necessidade de utilizar a notação de ponto ou colchete.
Exemplo:

```js
const obj = {
    name: ‘fulano’,
    cidade: ‘São Paulo’
}

// forma convencional de acessar as propriedades do objeto
console.log(obj.nome, obj.cidade) // exibe fulano São Paulo

// usando o destructuring
const {nome, cidade} = obj
console.log(nome, cidade) // exibe fulano São Paulo
```
Em uma função, quando temos parâmetros relacionados a um objeto, substituímos a referência ao objeto pela expressão que contém, entre chaves, os nomes das propriedades do objeto e que serão usadas por ela.
Exemplo:
```js
function (item) {
    console.log(item.name)
}
// com destructuring
function ({name}) {
    console.log(name) // exibe fulano
}
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
