### ISSUE TITLE
Resumo da Aula 01-03 da etapa 08

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2332]
### Filter()
- Este método tem o **proposito** de criar um novo array com todos os elementos, que apenas **passam** no teste implementado;
- Se nenhum elemento passar no teste será retornado um **array[vazio];**
- Ele também não altera o array chamado(original);
- **Ponto chave é**: Somente o elemento que der true, será adicionado no novo array.
- A callback é invocada com até  três **Parâmetros**: (**_item, index, array_**) como no Map, o **item** é obrigatório;

```js
const users = [
    { name: 'Ada Lovelace', premium: true },
    { name: 'Grace Hopper', premium: false },
    { name: 'Alan Turing', premium: true },
    { name: 'Linus Torvalds', premium: false },
    { name: 'Margaret Hamilton', premium: true }
  ]

// Mostre apenas os clientes que são usuários premium

const premiumUsers = users.filter(user => user.premium)

console.log(premiumUsers) 
```

**Comment by Roger-Melo** [comment]
Excelente @carlosdevjs, rumo à fluência! 🎯
