### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2335]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Hamiltonspjunior/weather-app

### Maiores dificuldades durante a implementação

- Lidar com as requisições para a AccuWeather API
- Entender o acesso aos dados de uma promise retornada por uma função async
- Refatorar o código em funções de responsabilidade única
- Conseguir escolher bons nomes para const e funções
- identicar quais trechos deviam ser isolados em funções e quais não

### Menores dificuldades durante a implementação

- Manipulação do DOM
- Inserir os elementos na tela
- Sintaxe da linguagem
- Manipulação do evento de submit

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Excelente, Hamilton.

No que precisar, é só abrir uma nova issue. Conte comigo para chegar na fluência =)
