### ISSUE TITLE
Aplicação: My To-do List - Etapa 10

### ISSUE THREAD

**Issue by LordMan0** [roger-melo-treinamentos/curso-de-js-roger-melo#234]
### **Dúvida sobre a aplicação do To-do list**

Boa tarde, professor!

No último exercício do Exercício 25 do repositório, pede-se que produza a própria aplicação do _To-do List_ de acordo com o que foi aprendido em aula. Tentei construir minha versão, mas o código pensei em outros caminhos para realizar as mesmas ações, mas não sei se acaba sendo viável ou não, em questão de acabar gerando muitos bugs e erros, através desse método. Portanto queria te perguntar se o método utilizado acaba sendo funcional do mesmo jeito que o _To-do List_ aprendido em aula ou não? Além de também pedir uma opinião sua sobre como está o andamento da aplicação.

Este é o link para o acesso da aplicação:
https://github.com/LordMan0/programa-js/tree/main/my-todo-main

PS.: **a aplicação ainda não foi finalizada**, falta fazer os reajustes e o _refactoring_ final.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi gabriel.

Testei a aplicação em minha máquina e seu código funciona, isso é fato.

Porém, prefiro que a aplicação seja enviada já refatorada. Isso por que refatoração é um dos critérios que uso ao analisar uma aplicação. Eis os critérios:

- Usabilidade
- Lógica
- Organização de código

Esses critérios possuem subcritérios. `Refatoração` é um subcritério de `Organização de código`, assim como `nomenclatura de variáveis e funções`, `linhas em branco`, etc.

Sacou a ideia?

Quando tiver refatorado, é só dar o toque que analiso e te dou um feedback =)

@LordMan0

**Comment by LordMan0** [comment]
Entendido!
Acho que agora terminei de arrumar o que faltava no código e de finalizar a organização dele. 
Este é o link para a versão final da aplicação:
https://github.com/LordMan0/programa-js/tree/main/my-todo-main

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Excelente, estou escrevendo a análise da aplicação.

Mas antes de publicá-la aqui, preciso lembrar que ainda falta você executar um critério daqueles que enviei no e-mail após a aula inaugural, em que falo das análises. É o critério 5:

> - Critério 5: a issue deve conter quais foram as suas maiores e menores dificuldades durante a implementação da aplicação.

Observe também que ao abrir a issue, o template de "dúvida" foi usado e não o de "aplicação". Mas tudo bem, já mudei as tags da issue.

Fico no aguardo da resposta ao critério 5.

Abraço.

@LordMan0

**Comment by LordMan0** [comment]
Ah! Verdade, acabei me esquecendo, peço desculpas. E sobre a _tag_, no começo a intenção era de tirar essa dúvida de funcionalidade mesmo, mas na próxima vou colocar a _tag_ de aplicação.

### **Critério 5**

**Maiores dificuldades**
Em relação ao código JavaScript, a maior dificuldade foi em realizar a parte de busca dos to-dos através do _input_, pois não era fácil de visualizar e pensar na lógica da mudança de classes dos itens  na forma de array. E a outra dificuldade foi pensar em possíveis erros e bugs que a aplicação poderia apresentar e modificar o código para evitar que eles aconteçam. Mas mais difícil que o JavaScript, foi finalizar o HTML tendo que pesquisar como funciona cada classe do bootstrap e deixar no formato desejado kkkk.

**Menores dificuldades**
As menores dificuldades eram de realizar a lógica e sequência da thread (saber o que a aplicação deve fazer e como fazer) e programar de acordo com o que foi aprendido: localizar as referências do HTML com querySelector, estruturar os _event listeners_ e reorganizar o código de maneira mais legível (_refactoring_). Acabou se tornando um código diferente do modelo aprendido em aula, mas conseguiu realizar as ações que era previsto, além de aproveitar para explorar outros métodos presente na aplicação (como na parte de remover os to-dos que risca a palavra e depois de um pequeno tempo apaga).

Em suma é isso, peço desculpas novamente pela falta de atenção.
Abraço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel. 

Legal. Parabéns pelo esforço em implementar a aplicação =)

Vou deixar abaixo algumas observações:

## Usabilidade

Só é possível saber que um item do to-do pode ser removido se o item de "check" for clicado. Não faz sentido clicar em um ícone verde de "check" para exclur um to-do. Prefira inserir um ícone que indica que o to-do pode ser removido.

## Lógica

### Não-uso da função `manipulateItemClass`

A função `manipulateItemClass` pode ser invocada para substituir as duas linhas dentro da função abaixo:

```javascript
notNeededLisArray.forEach(notNeededLi => {
  notNeededLi.classList.remove('d-flex')
  notNeededLi.classList.add('d-none')
})
```

### Complexidade

É legal experimentar soluções diferentes das mostradas no treinamento. Mas prefira fazer isso após dominar o que foi mostrado. E por dominar, quero dizer construir sozinho.

O código da refatoração dessa aplicação (mostrado na aula) ficou com apenas uma execução do `filter` e uma do `forEach`. Também não houve necessidade de inserir `else`. Else tende a prejudicar a legibilidade.

Então eu recomendo que no início, enquanto você está aprendendo, você siga a receita à risca. Depois que dominar a receita, aí sim é hora de experimentar modificá-la.

## Organização do código

### Remoção de elementos baseado em suas identificações

Ao invés de remover um item do to-do baseado na tag, prefira remover baseado em uma identificação com o data-js.

Eu não sei se mostrei a técnica acima especificamente nessa aplicação, mas em um determinado momento no treinamento, você verá que eu vou recomendar fazer isso. Afinal, se no futuro o nome da tag mudar, provavelmente ela ficará com o data-js e a remoção do item do to-do continuará funcionando. Mas se a remoção for baseada no nome da tag, o código quebra.

### Nomenclatura de funções e variáveis

Cuidado ao nomear consts incluindo o nome da tag, como `divSearchTodo`. Div é uma tag genérica que pode facilmente ser trocada por uma `section`, por exemplo. Prefira um nome que descreva o que o elemento faz ainda que não use o nome da tag, exemplo: `todoSearchContainer`.

### Inconsistência no estilo de código

A chave de abertura do bloco do `if` da linha 6 está colada no parênteses de fechamento.

```javascript
if (inputValue){
  // ...
}
```

Já nos outros `ifs`, existe um espaço em branco entre o parênteses e a chave. 

Procure manter consistência na formatação do código. Escolha `){` ou `) {` e seja consistente no decorrer do código. Eu recomendo que mantenha a convenção (`) {`).

Esse ponto de atenção já havia sido observado na análise do quiz. Então tome cuidado para não cometer os mesmos erros.

Mais uma vez, parabéns pelo esforço. Fico no aguardo de suas próximas aplicações.

E claro, se surgir qualquer dúvida, é só abrir uma issue que te ajudo =)

@LordMan0

**Comment by LordMan0** [comment]
Okay!
Vou arrumar esses erros e preparar a aplicação no portfólio.
Muito obrigado pela ajuda, professor!

**Comment by Roger-Melo** [comment]
Tamo junto @LordMan0. Rumo à fluência! 🔥
