### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#2342]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/francisko-rezende/cjrm-weather_app

### Maiores dificuldades durante a implementação

- Decidir o que cada função deve fazer durante a refatoração
- Decidir o nome das funções que criei
- Fazer uma função async modifcar uma let declarada externamente a ela (essa eu acabei conseguindo resolver depois de muito bater cabeça hahaha)

### Menores dificuldades durante a implementação

- Manipular o DOM foi fácil de acompanhar

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

Eu vi as maiores dificuldades que vc listou e sinceramente, não vi problemas nos nomes das funções que vc criou. Estão compreensíveis.

Sobre as responsabilidades das funções e a função async para modificar a let, vou falar sobre isso nas próximas linhas =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Let

Por que `timeImg` é uma `let`?

Vc pode declará-la como `const`. Isso faz com que seja mais difícil uma atribuição acidental de outro tipo de valor à ela.

---

## A let `Key`

Se `Key` não tem outra utilidade dentro de `handleCityData` exceto ser reatribuída, pq não eliminar a declaração de `Key` no escopo global e a mutabilidade dela e fazer a invocação de `handleCityData` retornar `cityData.Key`?

```javascript
// antes
let Key = null

const handleCityData = async inputValue => {
  const [cityData] = await getCityData(inputValue)
  Key = cityData.Key
  insertContentIntoTag(localizedNameInfo, cityData.LocalizedName)
}

const displayCityWeather = async event => {
  event.preventDefault()

  const inputValue = event.target.city.value

  await handleCityData(inputValue)
  handleWeatherData(Key)
  event.target.reset()
}
```

```javascript
// depois
const handleCityData = async inputValue => {
  const [cityData] = await getCityData(inputValue)

  insertContentIntoTag(localizedNameInfo, cityData.LocalizedName)
  return cityData.Key
}

const displayCityWeather = async event => {
  event.preventDefault()

  const inputValue = event.target.city.value
  const Key = await handleCityData(inputValue)
  
  handleWeatherData(Key)
  event.target.reset()
}
```

Assim vc elimina uma `let` do escopo global e a mutação que ela estava sofrendo =)

---

## Refatoração

À partir daqui, vou documentar algumas modificações que eu faria no código e por que.

Não há nada de certo ou errado, estamos apenas especulando possibilidades, ok? =)

### Eliminação de `insertContentIntoTag`

Eu eliminaria a função `insertContentIntoTag` pq ao usá-la, é necessário criar 4 objetos. 

`ObjDoDOM.propriedade` é uma sintaxe repetitiva, mas neste caso, penso que o saldo ainda seja mais positivo ao não abstrair, pela familiaridade da sintaxe.

```javascript
// antes
const localizedNameInfo = { 
  tag: cityNameContainer, 
  propertyName: 'textContent' 
}

const insertContentIntoTag = ({ tag, propertyName }, content) => tag[propertyName] = content
insertContentIntoTag(localizedNameInfo, cityData.LocalizedName)
```

```javascript
// depois
localizedNameInfo.textContent = cityData.LocalizedName
```

---

### Uma abordagem possível

Num primeiro momento, vou eliminar todas as funções exceto a `displayCityWeather`, pq vou voltar pra dentro dela todo o código que irá renderizar as informações na tela.

Ignorando as consts que selecionam os elementos no DOM, o código no `app.js` irá ficar assim:

```javascript
const displayCityWeather = async event => {
  event.preventDefault()

  const inputValue = event.target.city.value
  const [cityData] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(cityData.Key)

  cityNameContainer.textContent = cityData.LocalizedName
  timeImg.src = IsDayTime ? '../src/day.svg' : '../src/night.svg'
  timeIconConContainer.innerHTML = `<img src="../src/icons/${WeatherIcon}.svg" />`
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value

  const isCityCardHidden = cityCard.classList.contains('d-none')
  const showCityCard = () => cityCard.classList.remove('d-none')

  if (isCityCardHidden) {
    showCityCard()
  }

  event.target.reset()
}

cityForm.addEventListener('submit', displayCityWeather)
```

Por que você refatoraria este código?

Por que quebraria ele em partes?

O saldo da refatoração será positivo casa haja um bom por que que responda às perguntas acima.

Tem que haver um bom motivo pra refatorar.

#### Por que **eu não refatoraria** este código:

- Ele é relativamente simples
- Ele é relativamente legível
- Ele é familiar

#### Por que **eu refatoraria** este código:

- A função faz duas coisas: obtenção dos dados e manipulação de DOM
- A função está começando a ter muitas linhas

Considerando estes por quês, será que no final o saldo dessa refatoração seria positivo?

A resposta é: depende de como será a refatoração.

Se a refatoração adicionar mais complexidade e fizer "os 3 por ques para não refatorar" listados acima se tornarem afirmações falsas, talvez seja melhor deixar o código como está. 

Se a refatoração fizer apenas "os 2 por ques para refatorar" listados acima se tornarem afirmações falsas (e o código continuar relativamente simples, legível e familiar), provavelmente o saldo da refatoração será positivo.

Dito isso, eu acho que uma abordagem de refatoração que pode fazer com que o código continue simples, legível e familiar é um princípio muito difundido no React: separação de dados e view. 

View é apenas o código responsável pela renderização dos elementos.

Olha só...

A grosso modo, a função `displayCityWeather` faz duas coisas:

1. Obtém os dados;
2. Renderiza os dados.

É possível fazer com que a obtenção dos dados fique isolada em uma função. 

Como essa função irá **obter** os dados, ela pode ser nomeada como `getWeatherData`:

```javascript
const getWeatherData = () => {
  const inputValue = event.target.city.value
  const [cityData] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(cityData.Key)
}

const displayCityWeather = async event => {
  event.preventDefault()

  cityNameContainer.textContent = cityData.LocalizedName
  timeImg.src = IsDayTime ? '../src/day.svg' : '../src/night.svg'
  timeIconConContainer.innerHTML = `<img src="../src/icons/${WeatherIcon}.svg" />`
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value

  const isCityCardHidden = cityCard.classList.contains('d-none')
  const showCityCard = () => cityCard.classList.remove('d-none')

  if (isCityCardHidden) {
    showCityCard()
  }

  event.target.reset()
}
```

No código acima, dados e renderização estão separados, certo?

Porém, como a `displayCityWeather` precisa desses dados para renderizar o conteúdo, é possível fazer a `getWeatherData` retornar os dados quando for invocada. 

Observe também que `async` precisa ser inserido na declaração da `getWeatherData` (pois essa função executa um request) e `event` precisa ser inserido como argumento da invocação dela, por que ele está sendo usado dentro dela:

```javascript
const getWeatherData = async event => {
  const inputValue = event.target.city.value
  const [cityData] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(cityData.Key)
  
  return { WeatherText, Temperature, IsDayTime, WeatherIcon, cityData }
}

const displayCityWeather = async event => {
  event.preventDefault()

  const { WeatherText, Temperature, IsDayTime, WeatherIcon, cityData } = await getWeatherData(event)
  
  cityNameContainer.textContent = cityData.LocalizedName
  timeImg.src = IsDayTime ? '../src/day.svg' : '../src/night.svg'
  timeIconConContainer.innerHTML = `<img src="../src/icons/${WeatherIcon}.svg" />`
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value

  const isCityCardHidden = cityCard.classList.contains('d-none')
  const showCityCard = () => cityCard.classList.remove('d-none')

  if (isCityCardHidden) {
    showCityCard()
  }

  event.target.reset()
}
```

Só esse conceito de separar o que é dado e o que é view já ajuda a separar melhor as responsabilidades =)

A partir disso, vc pode fazer alguns outros pequenos refactorings. Mas a ideia base é a separação de dados e view.

Alguns pequenos refactorings que vc pode fazer para deixar o código mais simples:

- Fazer um destructuring no objeto `cityData`. 

Isso faz com que o objeto que a `getWeatherData` retorna tenha só as propriedades que serão usadas na view:

```javascript
// antes do destructuring
const getWeatherData = async event => {
  // ...
  const [cityData] = await getCityData(inputValue)
  const [{ /* blablabla */ }] = await getCityWeather(cityData.Key)
  
  return { /* blablabla */, cityData }
}

const displayCityWeather = async event => {
  // ...
  const { /* blablabla */, cityData } = await getWeatherData(event)
  
  cityNameContainer.textContent = cityData.LocalizedName
  // ...
}
```

```javascript
// depois do destructuring
const getWeatherData = async event => {
  // ...
  const [{ Key, LocalizedName }] = await getCityData(inputValue)
  const [{ /* blablabla */ }] = await getCityWeather(Key)
  
  return { /* blablabla */, LocalizedName }
}

const displayCityWeather = async event => {
  // ...
  const { /* blablabla */, LocalizedName } = await getWeatherData(event)
  
  cityNameContainer.textContent = LocalizedName
  // ...
}
```

- E claro, pra não deixar o `if` e a lógica dele na parte inferior da `displayCityWeather`, vc pode criar a `displayCityCard` (como já havia feito):

```javascript
const displayCityCard = () => {
  const isCityCardHidden = cityCard.classList.contains('d-none')
  const showCityCard = () => cityCard.classList.remove('d-none')

  if (isCityCardHidden) {
    showCityCard()
  }
}

const getWeatherData = async event => {
  const inputValue = event.target.city.value
  const [{ Key, LocalizedName }] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] = await getCityWeather(Key)
  
  return { WeatherText, Temperature, IsDayTime, WeatherIcon, LocalizedName }
}

const displayCityWeather = async event => {
  event.preventDefault()

  const { WeatherText, Temperature, IsDayTime, WeatherIcon, LocalizedName } = await getWeatherData(event)
  
  cityNameContainer.textContent = LocalizedName
  timeImg.src = IsDayTime ? '../src/day.svg' : '../src/night.svg'
  timeIconConContainer.innerHTML = `<img src="../src/icons/${WeatherIcon}.svg" />`
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = Temperature.Metric.Value
  displayCityCard()
  event.target.reset()
}

cityForm.addEventListener('submit', displayCityWeather)
```

Hoje, com a aplicação dessa forma, eu não quebraria o código além disso. Talvez, esse seja um bom motivo para eu regravar as aulas em que essa aplicação é construída/refatorada, caso no treinamento eu tenha quebrado ela em mais partes.

---

### Nomes de variáveis

`timeIconConContainer` pode ser renomeada para `timeIconContainer`.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by francisko-rezende** [comment]
Ei @Roger-Melo 

As observações fizeram bastante sentido sim, achei as sugestões de refatoração especialmente interessantes!

Obrigado pelo feedback!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
