### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by brunaribeiro89** [roger-melo-treinamentos/curso-de-js-roger-melo#2345]
//switch statement

const grade = 'B'

switch (grade) {
 case 'A':
    console.log('você tirou um A') 
    break
 case 'B':
    console.log('você tirou um B') 
    break
 case 'C':
    console.log('você tirou um C') 
    break
 case 'D':
    console.log('você tirou um D') 
    break
 default:
    console.log('nota inválida')
}

**Comment by Roger-Melo** [comment]
Excelente @brunaribeiro89, rumo à fluência! 🎯
