### ISSUE TITLE
Resumo da Aula Adicionando o javascript a uma pagina web - Aula 01-04 da etapa 01

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#2346]
O processo para adicionar **javascript** numa página web pode ser feito das seguintes maneiras:

Onde adicionar o javascript? R: É possível adicioná-lo em qualquer lugar dentro da tag `head `ou em qualquer lugar dentro da tag `body`.

Método 1- Tudo o que é preciso fazer é especificar uma tag `script `que tenha abertura e fechamento e escrever o código javascript dentro dessa tag.

**Observação**: Em alguns casos de deixá-lo na head, isso vai acarretar em problemas de carregamento, em 99% das vezes, prefira inserir o javascript como última tag dentro do `body`.  A prática de escrever javascript inline, isto, é dentro do `body`. É ok quando há pouco código, mas em situações que haja uma quantidade considerável de código Javascript, o ideal é externalizar e isolar esse código num arquivo separado e depois usar a tag `link `para adicioná-lo, da mesma forma usada para o CSS com a tag `style`.

Método 2- Crie um arquivo app.js dentro da pasta aula01 e coloque o seu endereço na seguinte maneira <script src="./app.js"> na index.html. O que for escrito dentro de app.js, também aparecerá no browser da mesma forma que no primeiro método.

OBS: Ctrl + b recolhe a aba de arquivos e ctrl + shift + e abre a mesma aba.

**Comment by Roger-Melo** [comment]
Excelente @MivlaM , rumo à fluência! 🎯
