### ISSUE TITLE
Resumo da Aula Arrow functions - Aula 02-02 da etapa 03

### ISSUE THREAD

**Issue by brunaribeiro89** [roger-melo-treinamentos/curso-de-js-roger-melo#2358]
Arrow functions 

exemplo de uma função tradicional:

const double = function (number) {
 return number * 2
}

//arrow function:
obs: quando somente houver um único parametro é possivél a retirada deles.
quando não houver nenhum parametro é necessário colocar os () vazios.
exemplo1:
const double = (number) => {
  return number * 2
}
exemplo2:
const double = number => {
  return number * 2
}
exemplo3:
const double = number => number * 2

const result = double(3)
console.log(`o resultado é: ${result}`)

**Comment by Roger-Melo** [comment]
Boa @brunaribeiro89, rumo à fluência! 🔥
