### ISSUE TITLE
Aplicação: Quis interativo exercício 19

### ISSUE THREAD

**Issue by andersoncsiqueira** [roger-melo-treinamentos/curso-de-js-roger-melo#2362]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/andersoncsiqueira/exercicio-19

### Maiores dificuldades durante a implementação

Tive um pouco de diifculade com a const que armazenava as respostas corretas, por algum motivo por duas ou três vezes o console mostrava o gabarito de forma alternada (Não faço ideia de como isso aconteceu, como no console tinham muitos console.log's, talvez eu tenha me confundido), mas tirando esse evento, não tive muitas dificuldades, espero ter acertado. =D

### Menores dificuldades durante a implementação

Perdi um pouco de tempo com o bootstrap, mas logo deixei de lado para focar no JS.

**Comment by Roger-Melo** [comment]
Olá @andersoncsiqueira.

Para que a sua aplicação seja analisada, você precisa postar na issue o link do repositório dela, e não o link dela em produção.

Edita isso na issue e me avisa aqui =)

**Comment by andersoncsiqueira** [comment]
Editei! =D

**Comment by Roger-Melo** [comment]
Olá @andersoncsiqueira.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @andersoncsiqueira!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Tive um pouco de diifculade com a const que armazenava as respostas corretas, por algum motivo por duas ou três vezes o console mostrava o gabarito de forma alternada (Não faço ideia de como isso aconteceu, como no console tinham muitos console.log's, talvez eu tenha me confundido), mas tirando esse evento, não tive muitas dificuldades, espero ter acertado. =D

Apesar dessa dificuldade listada, pelo seu código dá pra perceber que vc entendeu bem a lógica até aqui. As observações que irei listar nesta análise não estão relacionadas à lógica em si =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou claro o total de perguntas que o quiz tem na mensagem `Você acertou ${score}% das questões sobre a Europa!`. Isso é bom para a usabilidade, pq traz mais clareza do progresso do usuário no quiz.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

## Usabilidade

### Local da exibição dos pontos

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![image](https://user-images.githubusercontent.com/29297788/144656411-b0e8fcde-4a94-478f-bb95-cf21f1482b29.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

### Cores

O contraste entre a cor da fonte de exibição dos pontos e a cor de fundo está baixo. Isso faz com que a exibição dos pontos não fique "destacada" do fundo.

![baixo-contraste](https://user-images.githubusercontent.com/29297788/144657114-38d57f80-201b-42a8-b7e4-4c5d25edafbc.jpg)

Uma possível solução seria mudar a cor da mensagem para alguma cor que a deixe mais destacada do fundo cinza:

![alto-contraste](https://user-images.githubusercontent.com/29297788/144657109-456bc28a-e184-4603-8f76-815493fe652e.jpg)

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

## Organização de código

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover, de baixo pra cima, as linhas 26 e 5 e, adicionar uma linha em branco acima e abaixo da declaração da `let score`.

### Refatoração

Ao invés de aplicar estilo CSS inline usando a propriedade `style`, vc pode criar uma classe CSS específica para o parágrafo que exibe os pontos:

```javascript
// antes
paragraph.style.fontSize = '40px'
paragraph.style.textAlign = 'center'
paragraph.style.color = 'red'
```

```javascript
// depois
paragraph.classList.add('score-message')
```

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`paragraph` pode ter um nome mais descritivo como `scoreMessage`, por exemplo.

`usersResponse` dá a entender que está relacionada à resposta de vários usuários. Talvez `userAnswers` seja mais alinhado com o valor que a const armazena. Nesse caso, ao invés de `response`, o ideal é que o parâmetro do callback do `forEach` seja nomeado como singular de itens do array no qual o `forEach` foi encadeado (`userAnswer`).

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by andersoncsiqueira** [comment]
Boa noite, mestre!! 

Todas as colocações fizeram sentido, sinto que tenho muita dificuldade em dar o nome certo as diversas variáveis e funções, mas vou seguir as dicas e continuar prestando atenção as aulas, também tenho que prestar bastante atenção as linhas, para deixar o código mais arrumado, assim como ir aprendendo a refatorar. Para finalizar, quero agradecer ao feedback e dizer que a vontade de aprender só aumenta! =D

**Comment by Roger-Melo** [comment]
> ### sinto que tenho muita dificuldade em dar o nome certo as diversas variáveis e funções

Com a prática e o tempo, isso vai se tornando natural =)

No que precisar, é só abrir uma nova issue =)
