### ISSUE TITLE
Dúvida sobre escrever o código diferente da resolução

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2364]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/790701

### Descreva a dúvida

```js
const drinkType = 'suco'
switch (drinkType) {
  case 'água':
    console.log('Substância química cujas moléculas são formadas por dois átomos de hidrogênio e um de oxigênio.')
    break;
  case 'refrigerante':
    console.log('Bebida não alcoólica e não fermentada, fabricada industrialmente, à base de água mineral e açúcar.')
    break
  case 'suco':
    console.log('Bebida produzida do líquido extraído de frutos.')
    break
  default:
    console.log('Bebida desconhecida.')
    break;
}
```

Na resolução tu criou uma const para armazenar a mensagem, eu fiz assim, tem algum problema?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

O resultado é o mesmo, porém, lembre-se que sua habilidade em interpretação de leitura também está sendo testada.

O enunciado do exercício pede que uma variável seja criada e menciona essa variável algumas vezes: 

> ... atribua à uma variável a mensagem "Substância química..."

> ... a mensagem "Bebida não alcoólica... deve ser armazenada..."

> ... atribua a mensagem "Bebida produzida..."

> ... a variável deve armazenar "Bebida desconhecida..."

Fique atento aos enunciados. Não é esse o caso, mas em alguns exercícios, uma vírgula pode mudar todo o contexto =)

**Comment by Jansen-Muniz** [comment]
Ta certo =)
