### ISSUE TITLE
Aplicação: [To-do list]

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#2374]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/zolive72/todo-list

### Maiores dificuldades durante a implementação

Tive mais dificuldades na refatoração no momento de filtrar os To-dos (todosFound & todosNotFound) e tive que pesquisar sobre o data attributes para entender como usá-lo. Além disso o scroll dificultou minha aplicação, mas assim o layout ficou um pouco mais personalizado. 

### Menores dificuldades durante a implementação

Tenho menos dificuldades para usar os métodos e os ternários. Na realidade, a implementação foi mais simples depois de ter visto as aulas, pois minha primeira implementação tinha ficado complicada.

**Comment by Roger-Melo** [comment]
Olá @zolive72.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @zolive72!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Tive mais dificuldades na refatoração no momento de filtrar os To-dos (todosFound & todosNotFound) e tive que pesquisar sobre o data attributes para entender como usá-lo. Além disso o scroll dificultou minha aplicação, mas assim o layout ficou um pouco mais personalizado.

Na real, o código ainda ficou mais complexo do que o mostrado nas aulas, mas vou te mostrar uma outra forma simples de refatorar esse código, ali no final da análise =)

---

Não faz muito sentido executar uma função `filterTodos` no momento de adicionar um to-do. 

Também não é necessário `showOrHideTudo` ser invocada e executar manipulação de classes CSS no DOM a cada adição de um to-do.

---

Para evitar usar `id` nas `<li>`s dos to-dos, observe como ficaria se o `id` é substituído por um `data-todo` e `data-id` é substituído por `data-delete`:

```javascript
// antes
const removeTodo = event => {
  const clickedElement = event.target;
  const isTrashCan = clickedElement.className.includes('delete');

  if (isTrashCan) {
    const todoId = clickedElement.dataset.id;
    const TodoOfTrashCan = document.getElementById(todoId);

    TodoOfTrashCan.remove();
  }
}
```

```javascript
// depois
const removeTodo = event => {
  const clickedElement = event.target;
  const isTrashCan = clickedElement.dataset.delete;

  if (isTrashCan) {
    const todo = document.querySelector(`[data-todo="${isTrashCan}"]`)
    todo.remove()
  }
}
```

Nas aulas seguintes, vc verá por que evitar ids e também verá sobre o dataset =)

### Possível abordagem de refatoração 

Para entender de fato essa forma de refatorar que vou mostrar, você precisa executar o passo a passo abaixo junto comigo, testando o resultado de cada linha de código para de fato entendê-las, ok?

Primeiro, vamos eliminar `showOrHideTudo` e `filterTodos` e inserir dentro de `searchTodo` o código mais simples possível para a filtragem dos to-dos:

```javascript
const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.toLowerCase().trim()
  const todos = Array.from(containerTodos.children)

  const filteredTodos = todos
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))

  const notFilteredTodos = todos
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))

  filteredTodos.forEach(({ classList }) => {
    classList.add('hidden')
    classList.remove('d-flex')
  })

  notFilteredTodos.forEach(({ classList }) => {
    classList.add('d-flex')
    classList.remove('hidden')
  })
}
```

Agora, vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Vc pode, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ser exibido.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.toLowerCase().trim()
  const todos = Array.from(containerTodos.children)
  
  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(newTodos)

  // const filteredTodos = todos
  //...
}
```

Agora que há um array de objetos que indicam se o to-do deve estar visível, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, dependendo da propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.toLowerCase().trim()
  const todos = Array.from(containerTodos.children)
  
  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(newTodos)
}
```

Se vc quiser, pode deixar o código mais conciso, modificando o nome da `newTodos` para `todos` (usando o `Array.from`):

```javascript
const searchTodo = e => {
  e.preventDefault()

  const inputValue = e.target.value.toLowerCase().trim()
  const todos = Array.from(containerTodos.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by zolive72** [comment]
*Boa noite Roger,*

*Muito obrigado *por todas as observações e explicações as quais, posso
dizer,* fazem muito sentido*. O uso do *Map* criando um novo array de
objetos
(to-dos) foi fantástico, pois nos mostra como manipular o DOM com esses
métodos, simplificando assim o código. Em relação ao dataset, preciso
aprimorar
o assunto; usei o dataset.id e o id, mesmo tendo dúvidas, pois o usuário
poderia ter id's com os mesmos valores, o que não é possível, pois o id's
devem ter valores únicos no documento. O uso do data-tudo e do data-trash
são, com certeza, mais adequados nesta situação.

*Em relação ao uso das funções filterTodos e showOrHideTudo no momento de
adicionar um to-do, gostaria de explicar porque escrevi o código  desta
maneira, isso no objetivo de melhorar meu código. Não sei se é válido ?! *
------------------------------

Não faz muito sentido executar uma função filterTodos no momento de
adicionar um to-do.

Também não é necessário showOrHideTudo ser invocada e executar manipulação
de classes CSS no DOM a cada adição de um to-do.
------------------------------

O filterTodos e o showOrHideTudo junto com o resetInput(inputSearchTodo)
tinham como objetivo em um primeiro tempo, *limpar o inputSearchTodo e, em
seguida, mostrar de novo todos os to-dos quando o usuário adicionar um novo
to-do*. Porque no caso contrário, pode acontecer a situação na qual* o
usuário começa a preencher o "Buscar to-do"* (exemplo : ass) e *em mesmo
tempo adiciona um to-do* (exemplo : ir ao cinema), porém na validação do
tu-do, *a lista completa dos to-dos não aparece por causa da classe
"hidden"* como mostrado nos prints abaixo.
Esta explicação seria correta?

De qualquer forma, agradeço muito a você por ajudar cada um de nós para
chegar a fluência no Javascript, e já estou inserindo o MAP na minha
aplicação que farei de novo.

Abraço.
Olivier.

[image: image.png]

[image: image.png]
[image: image.png]

**Comment by Roger-Melo** [comment]
> ### Esta explicação seria correta?

Entendi. A ideia faz sentido sim =)

Se achar mais legível, pode apenas criar uma função `showTodos` que exibe os to-dos nesse caso:

```javascript
const showTodos = () => {
  Array.from(containerTodos.children).forEach(todo => {
    if (todo.classList.contains('hidden')) {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    }
  })
}

const addTodo = event => {
  // ...

  if (inputValue) {
    // ...
  }

  if (inputSearchTodo.value) {
    inputSearchTodo.value = ''
    showTodos()
  }

  event.target.reset();
};
```

@zolive72

**Comment by zolive72** [comment]
Mais uma vez, muito obrigado, Roger.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
