### ISSUE TITLE
Aplicação: Todo list CJRM

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#2380]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Will-Andrade/todoListCJRM

### Maiores dificuldades durante a implementação

1. Entender os casos de uso de data- e dataset e aplicá-los nesse projeto.
2. Criar funções de propósito único e refactoring preciso de parâmetros nessas funções

### Menores dificuldades durante a implementação

1. Compreensão do uso de métodos de array
2. Não precisar voltar nas aulas ou código anterior para conseguir aplicar alguma lógica. Ps: dessa forma, eu sempre "quebro mais a cabeça" para conseguir criar a lógica no app e assim eu sinto que aprendo mais.
3. Ler documentação e usar o Google como ferramenta de estudo para sanar dúvidas. Ps: esse é o motivo de eu não ter aberto tantas issues até o momento... sofrendo, eu tenho conseguido me virar kkkk

**Comment by Roger-Melo** [comment]
Olá @Will-Andrade.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Will-Andrade!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

É perceptível sua evolução em relação à análise passada, isso mostra que você ouviu os pontos que abordei explorei na análise. No geral, vc nomeou suas variáveis de forma específica e demonstrou ter pegado bem a lógica até aqui =)

> ### 1. Entender os casos de uso de data- e dataset e aplicá-los nesse projeto.

Nas aulas seguintes, vc verá por que e como usar atributos `data-*`. Se restar alguma dúvida, pode perguntar xD

> ### 2. Criar funções de propósito único e refactoring preciso de parâmetros nessas funções

Sem stress.

Refactoring é uma habilidade que será elevada com a prática e o tempo. Vc está no caminho.

Inclusive, vou deixar um desafio de refactoring no final dessa análise =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Consistência ao nomear callbacks

Como vc nomeou as funções de callback dos eventos como `searchTodos` e `deleteTodo`, o código fica mais coerente se `validateInputValue` for renomeada como `addTodo`.

```javascript
// antes
formAddTodo.addEventListener('submit', validateInputValue);
todosContainer.addEventListener('click', deleteTodo);
formSearchTodo.addEventListener('input', searchTodos);
```

```javascript
// depois
formAddTodo.addEventListener('submit', addTodo);
todosContainer.addEventListener('click', deleteTodo);
formSearchTodo.addEventListener('input', searchTodos);
```

Se quiser apertar ainda mais o parafuso da coerência, pode deixar `searchTodos` no singular (como as outras duas funções). Não é uma regra mas é uma possibilidade neste caso.

---

## Retorno de funções

Observe no código abaixo que `createTodo` está retornando o valor no qual a expressão `todosContainer.innerHTML += ...` resulta. 

```javascript
const createTodo = inputValue => todosContainer.innerHTML += `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo-item="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete" data-todo-trash="${inputValue}"></i>
  </li>
`;
```

Se vc estava consciente disso no momento da implementação e omitiu intencionalmente o bloco da função, tudo bem =)

---

### Ternário

Geralmente, o ideal é que ternários não sejam usados para executar efeitos colaterais. 

O ideal é usá-los para fazer algo com o valor que eles retornam. Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para remover o to-do (em que `null` ou o valor no qual a expressão `document.querySelector(...).remove()` resulta não está sendo aproveitado), vc pode usar apenas um `if`:

```javascript
// antes
const deleteTodo = ({ target: { classList, dataset } }) => {
  const clickedOnTrash = Array.from(classList).includes('delete');

  clickedOnTrash ? document
    .querySelector(`[data-todo-item="${dataset.todoTrash}"]`).remove()
    : null;
};
```

```javascript
// depois
const deleteTodo = ({ target: { classList, dataset } }) => {
  const clickedOnTrash = Array.from(classList).includes('delete');

  if (clickedOnTrash) {
    document.querySelector(`[data-todo-item="${dataset.todoTrash}"]`).remove()
  }
};
```

---

## Destructuring aninhado

É legal usar o destructuring, ele é muito poderoso e dá mais concisão ao código.

Porém, cuidado ao implementar destructuring aninhado. 

Às vezes um destructuring de apenas um nível é o suficiente para deixar o código conciso sem tirar a simplicidade dele. 

Observe que se `target` é usado dentro da função, um ReferenceError é lançado, pois o parâmetro do destructuring no primeiro nível não pode ser aproveitado quando há um segundo nível:

```javascript
const deleteTodo = ({ target: { classList, dataset } }) => {
  console.log(target) // Uncaught ReferenceError: target is not defined...
  // ...
};
```

---

## Desafio de refactoring

```javascript
const hideTodos = ({ classList }) => {
  classList.remove('d-flex');
  classList.add('hidden');
}

const showTodos = ({ classList }) => {
  classList.remove('hidden');
  classList.add('d-flex');
}

const hideOrShowTodos = (searchQuery, todos) => {
  todos
    .filter(todo =>
      !todo.textContent.trim().toLowerCase().includes(searchQuery))
    .forEach(hideTodos)

  todos
    .filter(todo =>
      todo.textContent.trim().toLowerCase().includes(searchQuery))
    .forEach(showTodos)
}

const searchTodos = e => {
  const searchQuery = e.target.value.trim().toLowerCase();
  const todos = Array.from(document.querySelectorAll('[data-todo-item]'));
  hideOrShowTodos(searchQuery, todos);
};
```

Já imaginou como seria legal se houvesse uma forma de abstrair esse código?

Imagina como seria se, ao invés de passar esses dois argumentos para a `hideOrShowTodos`, fosse passado um array de objetos em que cada objeto contém a referência do to-do e uma propriedade `shouldBeVisible`...

Consegue imaginar como isso poderia deixar o código mais conciso? 🤔 

Dá uma pensada e me mostra o código =)

**Comment by Will-Andrade** [comment]
# Obrigado pela revisão do app, professor! Gostaria de respondê-lo de acordo com os pontos que o senhor abordou.

# 1° - Consistência ao nomear callbacks
No caso da função que o senhor mencionou, eu escolhi deixar o nome da callback do ```formAddTodo``` daquela forma pois analisei meu código e pensei: 
"Pô, essa função está impedindo um reload da página, pegando o valor do input no submit, verificando se esse valor não é nulo e só aí ela cria um novo todo e limpa o input. Vou nomeá-la como ```validateInputValue```". 
Mas devido ao que você me alertou no segundo ponto que vou até comentar, e até por essa minha análise, eu pensei novamente e nomeá-la ```addTodo```de fato trará mais coerência.

# 2° - Retorno de funções
Sobre o que você disse... na verdade não shuausuah Eu queria dizer com aquela função que o único propósito dela é criar e inserir um todo no DOM, nada mais. Tanto que eu não estou de fato usando o retorno dessa função e só a utilizo lá dentro da ```validateInputValue```. Eu não estava mesmo ligado que o que está sendo retornado era o resultado daquela expressão mas sim achei que estava retornando a expressão toda, e até nisso é meio que desnecessário pois não estaria utilizando esse retorno. Vou refatorar aquela função para fazer mais sentido.

# 3° - Ternário
Obrigado, eu não estava atento nisso! Entendi e vou refatorar aquela expressão de acordo.

# 4° - Destructuring aninhando
Sim, estou ligado. Nessa função eu achei que ficaria ok assim para reduzir a notação de ponto e como no momento eu estava apenas usando essas duas propriedades do ```target```, deixei daquela forma. Vou pensar em refatorar para melhorar a legibilidade e manutenção do código.

# Desafio
Hm, não havia pensado dessa forma. Vou aceitar o desafio e refatorar esse código! Muito obrigado, @Roger-Melo :grin:
Darei um retorno nessa issue assim que "finalizar" .

**Comment by Will-Andrade** [comment]
# Nova versão do To-do list
@Roger-Melo, neste link https://github.com/Will-Andrade/todoListCJRM o senhor encontrará a nova versão do projeto com as implementações sugeridas em seu comentário. Gostaria de uma nova análise e de seu feedback, se possível.
PS: Eu consegui criar uma lógica de mostrar ou esconder todos a partir de um único objeto como mencionou no desafio. Entretanto, só consegui fazê-lo implementando com ```computed property names``` e espero que não haja problema.

**Comment by Roger-Melo** [comment]
@Will-Andrade, o código abaixo tem ternário executando efeito colateral.

```javascript
const hideOrShowTodo = todos => {
  todos.forEach((todo, index) => todo.shouldBeVisible
    ? showTodo(todo[`todo${index}`]) : hideTodo(todo[`todo${index}`]));
};
```

Vamos relembrar o que é efeito colateral?

- Modificar alguma variável ou propriedade de objeto que tá do lado de fora da função;

- Logar no console;

- Manipular o DOM;

- Desencadear qualquer processo do lado de fora da função;

- Invocar outra função que produz efeito colateral.

Antes de ler as próximas linhas, pense: qual efeito colateral o código acima está executando?

Manipulação de DOM.

`showTodo`/`hideTodo` são funções que manipulam classes CSS de um elemento do DOM.

Então novamente: não é recomendado usar o ternário nesse caso, pois além de executar efeito colateral, nada está sendo feito com o valor que o ternário retorna. E o ternário vai retornar nada pq as invocações dessas funções não retornam valor. Prefira usar `if` neste tipo de caso.

---

> ### Entretanto, só consegui fazê-lo implementando com computed property names e espero que não haja problema.

Essa solução abstrai boa parte do código que ainda ficou repetido:

```javascript
const searchTodo = e => {
  const searchQuery = e.target.value.trim().toLowerCase();
  const todos = Array
    .from(document.querySelectorAll('[data-todo-item]'))
    .map(todo => ({
      todo,
      shouldBeVisible: todo.textContent.trim().toLowerCase().includes(searchQuery)
    }))

  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
};
```

Se quiser, vc pode encapsular o `forEach` em uma função `filterTodos`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = e => {
  // ...

  filterTodos(todos)
};
```

**Comment by Will-Andrade** [comment]
Olá professor. Li essa revisão e estarei fazendo melhorias no código daqui em diante.
# Sobre o ternário usado na verificação da ```shouldBeVisible```
Realmente não me lembrei de que a manipulação do DOM também é um efeito colateral, obrigado pela explicação.

# Sobre a sugestão de código que me deu
Poxa vida, eu não tinha pensado em fazer um destructuring da propriedade ```todo``` e ```shouldBeVisible``` do obj. Isso realmente elimina a necessidade do computed property names e fica um código mais conciso. Sem contar que colocar um ternário dentro da invocação dos métodos  ```add``` e ```remove``` é algo que não passou pela minha cabeça em nenhum momento! Entretanto, nesse pedaço de código: 

```js

{
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
}
```
 O ternário não está executando efeito colateral? Fica tudo bem usá-lo nesse caso por qual motivo?
 Estarei realizando as melhorias sugeridas. Obrigado!

**Comment by Roger-Melo** [comment]
> ### O ternário não está executando efeito colateral? Fica tudo bem usá-lo nesse caso por qual motivo?

Na verdade a pergunta é: por que estaria executando efeito colateral?

O ternário está sendo usado apenas para retornar uma string:

```js
shouldBeVisible ? 'd-flex' : 'hidden' // retorna 'd-flex' ou 'hidden'
```

O fato do ternário ser inserido como argumento de qualquer método não caracteriza efeito colateral. 

@Will-Andrade

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
