### ISSUE TITLE
Resumo da Aula Testando padrões regex 01-05 da etapa 06

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2384]
Exemplo: testando se a string contém pelo menos 6 caracteres e se possuem apenas letras minúsculas.
```js
const username = ‘rogerm’
const pattern = /[a-z]{6,}/
console.log(pattern.test()) // retorna false
```

O método **_.test()_** é destinado a regex e irá checar se o valor de _username_ possui o padrão especificado pela _regex_ armazenada em _pattern_, neste caso, o console irá retornar _true_, pois ‘rogerm’ contém ao menos 6 letras e são minúsculas.
A regex do exemplo não está restringindo _username_ no que diz respeito ao tipo de caractere, apenas está dizendo que, se a string tiver pelo menos 6 caracteres e todos estes forem letras minúsculas em sequência, mesmo que haja caracteres antes depois (independente do tipo), também retornará _true_.
Para restringir a quantidade de caracteres para 6 e apenas letras minúsculas na string, a regex deve ser` /^[a-z]{6,}$/`

Podemos fazer o mesmo teste da _regex_, mas agora usando o método **_.search()_** que é destinado a strings. Porém, diferente do método anterior, ele não retorna um boolean, mas sim um número inteiro que indica o índice da posição na qual o padrão especificado na _regex_ ocupa dentro da string. Caso não haja correspondência, retorna -1.
```js
const result = username.search(pattern) // retornará índice 0
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
