### ISSUE TITLE
Resumo da Aula Stringficando e parseando dados - Aula-01-06 da etapa 13

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2401]
Podemos armazenar e obter dados mais complexos, como *arrays* e objetos, na *localStorage* utilizando a serialização. Para isso vamos utilizar o método `JSON.stringfy()`, que receberá como argumento um *array* ou um objeto. Vamos ver na prática a criação de um *array* de objetos, a modificação de seu formato para ser salvo na *localStorage*, e a volta ao formato original para ser exibido no console.

```jsx
const users = [
	{name: "Joaquim", age: 38, email: "joaquim@mail.com"}, 
	{name: "José", age: 28, email: "jose@mail.com"}
];

localStorage.setItem('users', JSON.stringify(users));

const JSONUsers = localStorage.getItem('users');
console.log(JSONUsers);

const convertedUsers = JSON.parse(JSONUsers);
console.log(convertedUsers);
```

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. vamo que vamo, rumo à fluência! 🙌
