### ISSUE TITLE
Iniciar as aulas das aplicações

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2406]
### Etapa da aula

9

### Nome da aula

To-do list Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1047938

### Descreva a dúvida

@Roger-Melo , devemos tentar realizar os códigos sozinhos ou acompanhando as aulas?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Segue o que recomendei no email `[Alunos CJRM] Análises de aplicações` que é sucesso. 

Vc recebeu esse email no dia 14 de agosto =)

**Comment by carlosdevjs** [comment]
Obrigado por lembrar, não ocorrerá novamente. =)
