### ISSUE TITLE
Resumo da Aula Eventos de teclado 02-03 da etapa 06

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2408]
A validação de uma entrada pode ser feita no momento em que o usuário está digitando algo, para isto, utilizando os eventos de teclado.
O evento _**keyup**_ permite executar alguma ação toda vez que uma tecla é pressionada e solta. Utilizando o event listener no elemento _input_ e manipulando o objeto fornecido por ele, podemos “monitorar” em tempo real tudo o que está sendo inserido, antes do evento _submit_ do _form_ acontecer.

```js
form.id_do_input.addEventListener('keyup', event =>{
    console.log(event) // mostra a informação do objeto do evento keyboartEvent
    console.log(event.target) // mostra a tecla que foi pressionada e solta
})
```
Com este recurso, é possível implementar uma função de teste da entrada que será executada toda vez que o usuário pressionar e soltar uma tecla dentro do campo _input_ do formulário. Por exemplo, dentro do callback do event listener, dada a _expressão_regex_ contendo o padrão de teste do valor inserido no _input_:

```js
if(expressão_regex.test(form.id_do_input.value) { // testando padrão estabelecido na expressão_regex
console.log('entrada inválida') // se truth, exibe esta mensagem
return
}
console.log('entrada válida') // se false, exibe esta mensagem
})
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. vamo que vamo, rumo à fluência! 🙌
