### ISSUE TITLE
Resumo da Aula02-03 da etapa 02

### ISSUE THREAD

**Issue by ARNOBIOAIRES** [roger-melo-treinamentos/curso-de-js-roger-melo#2414]
**If, else if and else statements**
Significado:  **If (se),         else if(senão se),            else(se não)**

Estruturas condiçionais é um recurso muito importante para
o fluxo do programa. De acordo com a condição analisada
a resposta pode alternar para true ou false.
Sendo que true é a primeira análise a ser feita.

Pode usar o conceito de nested, ou seja alinhar uma condição abaixo de outra.
- Interessante notar que nessa estrutura, o retorno é um boolean, assim entendemos que dentro dos parênteses sempre vamos fazer comparações com os operadores lógicos.

Segue exemplo:

````JS
const password = '11oi14846123@'

if (password.length >= 12 && password.includes('@')) {
    console.log('Senha fortíssima :)')
} else if (password.length >=8) {
    console.log('Essa senha tem 8 ou mais caracteres')
} else {
    console.log('a senha deve conter 8 ou mais caracteres')
}
```

**Comment by Roger-Melo** [comment]
Show @ARNOBIOAIRES . vamo que vamo, rumo à fluência! 🙌
