### ISSUE TITLE
Aplicação: Quiz-Interativo

### ISSUE THREAD

**Issue by mcrodrigo** [roger-melo-treinamentos/curso-de-js-roger-melo#2416]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/mcrodrigo/quiz.git

### Maiores dificuldades durante a implementação

1 - Até consegui iterar os radios pelo forEach, porém percebi que obrigatoriamente todos tinham que ter um valor checado por padrão para não dar erro na hora de comparar

2 - usar o bootstrap

### Menores dificuldades durante a implementação

fazer esse exercício sem rever partes das aulas anteriores

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo.

Passando para dizer que visualizei a issue e, em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### 1 - Até consegui iterar os radios pelo forEach, porém percebi que obrigatoriamente todos tinham que ter um valor checado por padrão para não dar erro na hora de comparar

Sim. Acredito que isso acaba incentivando mais o usuário a de fato marcar qual alternativa ele acha que é a correta =)

> ### 2 - usar o bootstrap 

O uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou claro o progresso do usuário ao exibir a porcentagem de acertos. Isso é bom para a usabilidade, pois o usuário tem um indicativo mais claro do quanto acertou do quiz.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando esse princípio...

`p` é uma const pouco descritiva sobre o valor que ela armazena. `scoreMessage` pode ser uma alternativa que deixa isso mais claro:

```javascript
// antes
const p = document.createElement('p')
```

```javascript
// depois
const scoreMessage = document.createElement('p')
```

Como a ação que `userCorrectAnswer` executa é basicamente calcular a pontuação, ela pode ser chamada de  `calculateScore`.

Como o array que armazena as respostas corretas contém várias respostas, ele pode se chamar `correctAnswers` (no plural).

Para dar mais coerência ao parâmetro do callback do `forEach`, vc pode nomeá-lo como singular de itens do array no qual o `forEach` foi encadeado (`userAnswer`).

---

## Refactoring

Ao invés de e repetir a execução de `innerText` no decorrer dos blocos de um `switch`, vc pode criar uma função que recebe a pontuação como parâmetro e usa o valor da propriedade de um objeto como retorno:

```javascript
// antes
switch (score) {
  case 0:
    p.innerText = `Você não acertou nenhuma questão`
    break
  case 100:
    p.innerText = 'Você acertou tudo, parabéns!'
    break
  default:
    p.innerText = `Você acertou ${score}% das questões`
}
```

```javascript
// depois
const getScoreMessage = score => {
  const scoreMessages = {
    0: 'Você não acertou nenhuma questão',
    100: 'Você acertou tudo, parabéns!'
  }

  return scoreMessages[score] || `Você acertou ${score}% das questões`
}

scoreMessage.innerText = getScoreMessage(score)
```

Se quiser, vc pode deixar a função mais concisa, eliminando a `const` scoreMessages e fazendo a função retornar o objeto diretamente:

```javascript
  const getScoreMessage = score => {
    return {
      0: 'Você não acertou nenhuma questão',
      100: 'Você acertou tudo, parabéns!'
    }[score] || `Você acertou ${score}% das questões`
  }
```

É possível deixar a função ainda mais concisa, usando o retorno implícito da arrow function ao invés de usar um `return`:

```javascript
  const getScoreMessage = score => ({
    0: 'Você não acertou nenhuma questão',
    100: 'Você acertou tudo, parabéns!'
  })[score] || `Você acertou ${score}% das questões`
```

Para diminuir um pouco da quantidade de linhas do callback de submit do form, vc pode remover `getScoreMessage` do escopo desse callback:

```javascript
const getScoreMessage = score => ({
  0: 'Você não acertou nenhuma questão',
  100: 'Você acertou tudo, parabéns!'
})[score] || `Você acertou ${score}% das questões`

form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
})
```

Ao invés de ficar em escopo global, faz mais sentido que a manipulação de classe do parágrafo fique próxima de outras manipulações do parágrafo:

```javascript
// antes
scoreMessage.classList.add('text-center', 'text-success')

form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
  form.insertAdjacentElement('afterend', scoreMessage)
})
```

```javascript
// depois
form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
  scoreMessage.classList.add('text-center', 'text-success')
  form.insertAdjacentElement('afterend', scoreMessage)
})
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

PS: por curiosidade, pq vc escolheu implementar a aplicação dentro de uma tag `<script>` no `index.html`?

**Comment by mcrodrigo** [comment]
Boa noite
- Obrigado pelas considerações sobre o refactoring, são realmente excelentes.
- Sobre: “PS: por curiosidade, pq vc escolheu implementar a aplicação dentro de uma tag <script> no index.html?” , eu estava acompanhando os nomes das classes e dos elementos para poder implementar o que o exercício pedia e acabei esquecendo de migrar o código para um arquivo de script externo [app.js]. Vou tomar mais cuidado nos próximos


...

Em quinta-feira, dezembro 9, 2021, 3:44 PM, Roger Melo ***@***.***> escreveu:




Olá @mcrodrigo!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)


1 - Até consegui iterar os radios pelo forEach, porém percebi que obrigatoriamente todos tinham que ter um valor checado por padrão para não dar erro na hora de comparar


Sim. Acredito que isso acaba incentivando mais o usuário a de fato marcar qual alternativa ele acha que é a correta =)


2 - usar o bootstrap


O uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

Boas decisões

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou claro o progresso do usuário ao exibir a porcentagem de acertos. Isso é bom para a usabilidade, pois o usuário tem um indicativo mais claro do quanto acertou do quiz.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:
   
   - Funções são verbos que descrevem a ação que a função executa.      
      - Exemplos: getName, setName, incrementCounter;

   - Variáveis/consts são substantivos que descrevem o valor armazenado.      
      - Exemplos: user, score, color.
      - Quando o valor armazenado é um boolean, podem conter is, has ou should.         
         - Exemplos: isOdd, hasSevenItems, shouldUpdate.



Considerando esse princípio...

p é uma const pouco descritiva sobre o valor que ela armazena. scoreMessage pode ser uma alternativa que deixa isso mais claro:
// antes
const p = document.createElement('p')// depois
const scoreMessage = document.createElement('p')
Como a ação que userCorrectAnswer executa é basicamente calcular a pontuação, ela pode ser chamada de calculateScore.

Como o array que armazena as respostas corretas contém várias respostas, ele pode se chamar correctAnswers (no plural).

Para dar mais coerência ao parâmetro do callback do forEach, vc pode nomeá-lo como singular de itens do array no qual o forEach foi encadeado (userAnswer).

Refactoring

Ao invés de e repetir a execução de innerText no decorrer dos blocos de um switch, vc pode criar uma função que recebe a pontuação como parâmetro e usa o valor da propriedade de um objeto como retorno:
// antes
switch (score) {
  case 0:
    p.innerText = `Você não acertou nenhuma questão`
    break
  case 100:
    p.innerText = 'Você acertou tudo, parabéns!'
    break
  default:
    p.innerText = `Você acertou ${score}% das questões`
}// depois
const getScoreMessage = score => {
  const scoreMessages = {
    0: 'Você não acertou nenhuma questão',
    100: 'Você acertou tudo, parabéns!'
  }

  return scoreMessages[score] || `Você acertou ${score}% das questões`
}

scoreMessage.innerText = getScoreMessage(score)
Se quiser, vc pode deixar a função mais concisa, eliminando a const scoreMessages e fazendo a função retornar o objeto diretamente:
  const getScoreMessage = score => {
    return {
      0: 'Você não acertou nenhuma questão',
      100: 'Você acertou tudo, parabéns!'
    }[score] || `Você acertou ${score}% das questões`
  }
É possível deixar a função ainda mais concisa, usando o retorno implícito da arrow function ao invés de usar um return:
  const getScoreMessage = score => ({
    0: 'Você não acertou nenhuma questão',
    100: 'Você acertou tudo, parabéns!'
  })[score] || `Você acertou ${score}% das questões`
Para diminuir um pouco da quantidade de linhas do callback de submit do form, vc pode remover getScoreMessage do escopo desse callback:
const getScoreMessage = score => ({
  0: 'Você não acertou nenhuma questão',
  100: 'Você acertou tudo, parabéns!'
})[score] || `Você acertou ${score}% das questões`

form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
})
Ao invés de ficar em escopo global, faz mais sentido que a manipulação de classe do parágrafo fique próxima de outras manipulações do parágrafo:
// antes
scoreMessage.classList.add('text-center', 'text-success')

form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
  form.insertAdjacentElement('afterend', scoreMessage)
})// depois
form.addEventListener('submit', event => {
  // ...
  scoreMessage.innerText = getScoreMessage(score)
  scoreMessage.classList.add('text-center', 'text-success')
  form.insertAdjacentElement('afterend', scoreMessage)
})
Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

PS: por curiosidade, pq vc escolheu implementar a aplicação dentro de uma tag <script> no index.html?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Roger-Melo** [comment]
> ### eu estava acompanhando os nomes das classes e dos elementos para poder implementar o que o exercício pedia e acabei esquecendo de migrar o código para um arquivo de script externo [app.js]. Vou tomar mais cuidado nos próximos

Separar seu código js em um arquivo .js dá mais organização ao seu código, pois separa o que é HTML e o que é JS e deixa a aplicação mais manutenível. 

Essa é uma boa prática fundamental que vc precisa se habituar a seguir, ok?

No que precisar, é só abrir uma nova issue =)

@mcrodrigo
