### ISSUE TITLE
Dúvida sobre método

### ISSUE THREAD

**Issue by DaniloTeixeira** [roger-melo-treinamentos/curso-de-js-roger-melo#2417]
### Etapa da aula

4

### Nome da aula

Exercícios arrow functions

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/824585

### Descreva a dúvida

Tenho uma dúvida de um exercício que pensei, mas que não está na aula. Como seria fazer um método que retorna true se todos os números do array forem pares e retorna false se houver pelo menos um número negativo. Tentei resolver, porém não consegui, seria possível me dar uma luz de como fazer um exercício desse tipo? Obrigado!

Danilo R. Teixeira

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @DaniloTeixeira!

Se vc quer que essas duas verificações existam na mesma função, pode fazer algo do tipo:

```javascript
const validadeNumbers = numbers => {
  if (numbers.some(number => number < 0)) {
    return 'Encontrei um número menor que 0'
  }

  return numbers.every(number => number % 2 === 0)
}

console.log(validadeNumbers([2, 4, -3])) // 'Encontrei um número menor que 0'
console.log(validadeNumbers([2, 4, 3])) // false
console.log(validadeNumbers([2, 4, 6])) // true
```

Esse código tem métodos que vc ainda conhecerá no treinamento (`some` e `every`), então não se preocupe se não entender tudo nesse momento =)

**Comment by DaniloTeixeira** [comment]
Show de bola!!! muito obrigado!!!!
