### ISSUE TITLE
Podemos utilizar qualquer propriedade nessa refatoração do destructuring?

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2423]
### Etapa da aula

9

### Nome da aula

correção exercício aula 1 - 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1067811

### Descreva a dúvida

No código abaixo na refatoração do destructuring você utilizou a propriedade length, não poderia ser outro nome?

```js
/*
  03

  - Gere um novo array com apenas os animais que contém 3 letras no nome;

  Ps: Neste e nos demais exercícios, utilize o debugger para visualizar o valor 
      final que os exercícios pedem. Após resolver um exercício, remova o 
      debugger antes de partir para o próximo.
*/

const animals = ['cão', 'gato', 'boi', 'leão', 'gnu', 'alce', 'ema']

const threeLetterAnimals = animals.filter(({ length }) => length === 3)
debugger
 
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Você pode renomear a const/parâmetro no destructuring:

```javascript
const { prop1: newProp } = { prop1: 1, prop2: 2 }

console.log(newProp) // 1
```

Apenas veja se faz sentido renomear (na maior parte dos casos, não há necessidade).

Não se preocupe se o código acima é novidade no momento. Vc ainda verá muitos casos de uso do destructuring no decorrer do treinamento e chegará na parte onde eu falo sobre renomeação de variáveis no destructuring, ok? =)

---

PS: ao inserir links das aulas nas issues, prefira postar o link da aula na plataforma, e não do vídeo do yt. O motivo é muito simples... Quando essa aula for regravada, o vídeo do link que vc postou na issue não existirá mais. Já ajustei o link dessa issue.

**Comment by carlosdevjs** [comment]
obrigado @Roger Melo ***@***.***> . Rumo a fluência

Em ter., 7 de dez. de 2021 às 22:13, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
