### ISSUE TITLE
Aplicação: [Quiz-Interativo]

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#2428]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ThiagoDeMorais/Quiz.git

### Maiores dificuldades durante a implementação

1 - Nomear variáveis e funções;

### Menores dificuldades durante a implementação

1 - Cálculo da pontuação.

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### 1 - Nomear variáveis e funções;

Vou falar sobre isso no decorrer da análise.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Usabilidade

Talvez, ao exibir a pontuação, seria interessante deixar claro o total de perguntas que o quiz tem. 

Exemplo: "Pontuação: 50/100".

Acredito que isso possa dar mais clareza para o usuário da performance dele. Deixando o total de pontos do quiz explícito, fica mais perceptível se o usuário se saiu bem ou não.

---

A única forma de sair da mensagem de pontuação é recarregando a página. Isso pode ser problemático, pois pode acabar "encurralando" o usuário a recarregar a página se quiser jogar novamente.

Uma possível solução para isso seria um botão "voltar" ou "fechar", por exemplo.

---

## Lógica

É desnecessário declarar `responsesReceived` no escopo global e dar `push` no array que ela armazena. 

Ela pode ser declarada dentro do callback de submit do form, já armazenando o array com as respostas:

```javascript
function scoreCalculation (responsesReceived) {
  responsesReceived.forEach(/* ... */);
}

formulary.addEventListener("submit", (event) => {
  event.preventDefault();

  const responsesReceived = [
    event.target.inputQuestion1.value,
    event.target.inputQuestion2.value,
    event.target.inputQuestion3.value,
    event.target.inputQuestion4.value
  ];

  scoreCalculation(responsesReceived)
});
```

Feito isso, vc pode armazenar o valor que a invocação de `scoreCalculation` retorna em uma const e em seguida executar `showScore`:

```javascript
formulary.addEventListener("submit", (event) => {
  // ...

  const score = scoreCalculation(responsesReceived)
  showScore(score)
});
```

Ou pode fazer ainda melhor: eliminar a `score` do escopo global.

```javascript
formulary.addEventListener("submit", (event) => {
  // ...
  const responsesReceived = [/* ... */];

  let score = 0;

  responsesReceived.forEach((element, index) => {
    if (element === rightAnswers[index]) {
      score += 25;
    }
  });

  showScore(score)
});
```

Sempre que possível, o ideal é evitar variáveis globais pois elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e atrapalham a modularidade do código (assunto que será visto em etapas mais avançadas).

---

## Nomes de variáveis e funções

Como vc listou a nomeação de variáveis como principal dificuldade, vou fazer algumas sugestões de ajustes.

Mas antes de falar sobre os ajustes, deixa eu mostrar uma coisa...

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

A extinta `scoreCalculation` poderia soar mais como um verbo se fosse nomeada como `calculateScore`.

`form` é um padrão meio que adotado universalmente para se referir à um formulário. Então vc pode renomear `formulary` como `form`.

Se vc renomear `responsesReceived` como `userAnswers` e `element` (parâmetro do callback do `forEach`) como singular de itens do array no qual o `forEach` foi encadeado (`userAnswers`), acredito que a leitura do `forEach` e do `if` fique mais legível:

```javascript
// antes
responsesReceived.forEach((element, index) => {
  if (element === rightAnswers[index]) {
    // ...
  }
});
```

```javascript
// depois
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === rightAnswers[index]) {
    // ...
  }
});
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

PS: por curiosidade, pq as variáveis no escopo global foram declaradas como `let`?

**Comment by ThiagoDeMorais** [comment]
Bom dia, professor Roger. Em primeiro lugar, gostaria de agradecer pelo esmero na análise do código. 

Após ler análise, eu já estou melhorando a parte da usabilidade inserindo a possibilidade de reiniciar e mostrando a pontuação máxima possível. Vou modificar os nomes da variáveis tbm e salvar as dicas em pdf aqui para usar posteriormente também. Sobre o uso de *let* ao invés de *const*, foi um erro devido à um vício que adquiri antes do curso rsrs, vou prestar mais atenção nesse quesito na hora de projetar a solução e na hora de refatorar o código.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue.

Conte comigo para chegar na fluência =)
