### ISSUE TITLE
Quanto mais funções, melhor?

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2433]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 05 da etapa 11 - Aula 06-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1352386

### Descreva a dúvida

Olá, Roger! Estava corrigindo a 31° lista de exercícios e fiquei com uma pequena dúvida em relação ao refactoring da questão 2.
Você apenas encapsulou o código em uma função que recebia um array por parâmetro, enquanto eu separei o código em 3 funções, para deixá-lo o mais genérico possível.
```js
//Refactoring mostrado na aula
const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
const divisibleBy2Or3 = numbers => numbers
   .filter(number => number % 2 === 0 || number % 3 === 0
console.log(divisibleBy2Or3(numbers))


//Meu refactoring
const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
const divisibleNumbers = (number, divisor) => number % divisor === 0
const getDivisibleNumbersBy = (divisor1, divisor2) => numbers
  .filter(number => divisibleNumbers(number, divisor1) || divisibleNumbers(number, divisor2))
const filterNumbers = () => getDivisibleNumbersBy(2, 3)

console.log(filterNumbers())
```

Eu devo criar uma função para uma certa ação sempre que eu ver uma oportunidade, ou isso pode acabar atrapalhando a leitura do código?

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### enquanto eu separei o código em 3 funções, para deixá-lo o mais genérico possível

Haverá casos em que não faz sentido deixar o código o mais genérico possível.

Nesse caso não é, pois as funções criadas além de não serem usadas em outros lugares do código, deixaram ele mais complexo.

Vale como estudo, mas para o seu dia a dia como Dev, não há necessidade de quebrar **prematuramente** o código. 

Não abstraia muito cedo. Espere até ter copiado e colado um pedaço de código algumas vezes. Vc precisa de exemplos de casos de uso para criar boas abstrações.

Então a resposta para a pergunta "Quanto mais funções, melhor?" é: não necessariamente. 

Vc ainda verá outros casos de refactoring nas aulas seguintes e, através deles, terá a oportunidade de treinar sua percepção de necessidade refactoring.

Dá uma olhada também no tópico `Refatoração`, [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2342#issuecomment-985200744) =)

@YureK-a

**Comment by YureK-a** [comment]
Entendi, obrigado pela resposta =)
