### ISSUE TITLE
Armazenando e obtendo dados do localStorage

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2435]
### Etapa da aula

13

### Nome da aula

Armazenando e obtendo dados - Aula 01-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1525038

### Descreva a dúvida

Oi, @Roger-Melo 

Vi que na aula podemos setar um item na localStorage através do método setItem e obter dados através do getItem. 

Mas descobri que também é possível utilizar a notação de ponto tanto para inserir como obter dados da localStorage. EX: 
```js
localStorage.name = "Zé"
localStorage.name // 'Zé'
```

Há algum problema em usar essa forma ao invés dos métodos setItem e getItem?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior!

Ao manipular o localStorage, dê preferência ao uso dos métodos da Web Storage API (`setItem`, `getItem`, etc). Caso contrário, vc poderá cair em algumas "armadilhas" associadas à essa sintaxe. 

Vou deixar um material [aqui](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#basic_concepts) caso vc queira se aprofundar no assunto. Dê uma olhada em "Note" (tarja azul) e, se ainda restar alguma dúvida, é só dar o toque =)

**Comment by Hamiltonspjunior** [comment]
Oi, @Roger-Melo 

Entendi. Vou dar uma olhada com calma no artigo que você passou, posteriormente. 

Muito obrigado.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
