### ISSUE TITLE
Exercício 4 - Criar uma função e adicionar um amigo ao objecto cat

### ISSUE THREAD

**Issue by ARNOBIOAIRES** [roger-melo-treinamentos/curso-de-js-roger-melo#2444]
### Etapa da aula

4

### Nome da aula

Aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Roger, boa tarde. Rolou um dúvida.
Compreendi o exercício. Entretanto se em vez de adicionar 01 friend,
como faria para adicionar 2 ou mais friends.

Fiz um exercício, mas conforme abaixo ele inclui um array, mas como fazer sem o array :)
```JS
const addFriend = (friend, obj) => {

  obj.bestFriends.push(friend)
}

addFriend(['Manel, Carlos'], cat) 

console.log(cat.bestFriends)

``````

@Roger-Melo

**Comment by ARNOBIOAIRES** [comment]
ops. Já encontrei a solução.
```JS
addFriend(('Maneol, Carlos'),  cat)
````

**Comment by Roger-Melo** [comment]
Olá @ARNOBIOAIRES!

Observe que na solução que vc mostrou, apenas uma string 'Manoel, Carlos' foi adicionada ao array. 

Ou seja, o resultado foi `['Charles', 'Irene', 'Manoel, Carlos']`, mas acho que vc queria que o resultado fosse `['Charles', 'Irene', 'Manoel', 'Carlos']`. Certo?

Se eu estiver certo, uma forma de inserir 2 itens no array neste caso é invocando a função 2x (1x para cada item a ser inserido no array):

```javascript
let cat = {
  name: 'Milton',
  age: 4,
  color: 'Cinza',
  bestFriends: ['Charles', 'Irene'],
  sound: function () {
    return 'meoooowwwwww'
  }
}

const addFriend = (friend, obj) => {
  obj.bestFriends.push(friend)
}

addFriend('Manoel', cat)
addFriend('Carlos', cat)
console.log(cat.bestFriends) // ['Charles', 'Irene', 'Manoel', 'Carlos']
```

Essa é uma forma.

Uma outra forma seria pelo caminho que vc fez:

```javascript
const addFriends = (friends, obj) => {
  obj.bestFriends.push(friends)
}

addFriends(['Manoel', 'Carlos'], cat)
console.log(cat.bestFriends) // ['Charles', 'Irene', ['Manoel', 'Carlos']]
```

Porém, acredito que vc queira eliminar o array aninhado `['Manoel', 'Carlos']` dentro do array `bestFriends`, certo?

Uma alternativa, neste caso, seria invocar o `push` 2x:

```javascript
const addFriends = (friends, obj) => {
  obj.bestFriends.push(friends[0])
  obj.bestFriends.push(friends[1])
}

addFriends(['Manoel', 'Carlos'], cat)
console.log(cat.bestFriends) // ['Charles', 'Irene', 'Manoel', 'Carlos']
```

Porém, essa estratégia só funciona se a quantidade de itens do array inserido como argumento da `addFriends` for conhecida (e pequena).

Dito isso, nas etapas passadas vc viu formas de evitar repetições de cóigo desnecessárias (como a repetição da invocação do `push` ali em cima).

Vc se lembra quais são essas formas?
