### ISSUE TITLE
Resumo da Aula inaugural da etapa 00

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2450]
Alicerce 

Marco 01: Assistir a aula inaugural.
Marco 02: Postar o resumo de cada aula no repositório do treinamento.
Marco 03: Fazer uma revisão raio-x antes de implementar cada aplicação.
                
                Revisão raio-x
                Passo 01
                Sem assistir as aulas novamente, refaça os exercícios anteriores a partir da aplicação passada e assim por diante.
                Passo 02
                Quando travar em um exercício, assista a correção, apague o código e  implemente-o novamente, sozinho.
                Passo 03
                Executar o passo anterior até assimilar o padrão do exercício.
                Passo 04
                Abrir uma issue se continuar sem entender o padrão.

Marco 04 : Análise das aplicações.
Marco 05: Montar um portfólio com as 3 aplicações do treinamento.
Marco 06: Se candidatar para as vagas ao terminar a etapa 14.
Marco 07: Implementar o feedbacks dos recrutadores.
Marco 08: Ser contratado.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota, rumo à fluência! 🎯
