### ISSUE TITLE
Resumo da Aula Conversão de tipos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#246]
É possível converter de forma explícita o tipo de um valor utilizando funções construtoras. 

Para verificar o tipo de um valor podemos utilizar o *typeof*.

---

## Convertendo um valor para *string*

```jsx
console.log(String(10) , typeof String(10)) // '10', string
```

---

## Convertendo um valor para *number*

```jsx
console.log(Number('100'), typeof Number('100')) // 100, number
```

Porém quando tentamos converter um valor que não é um número que esteja em um outro formato o resultado será `NaN`.

```jsx
console.log(Number('Maçã')) // NaN
```

---

## Convertendo um valor para *boolean*

- Valores falsy
    - false;
    - 0;
    - null;
    - undefined;
    - '', "", ``;
    - NaN.
- Valores truthy
    - É qualquer valores que não é falsy.

```jsx
console.log(Boolean(10), typeof Boolean(10)) // true, "boolean"
console.log(Boolean(''), typeof Boolean('')) // false, "boolean"
```

🚀 Rumo à fluência

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso mesmo @sou-gabriel. Rumo à fluência! 🚀
