### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2460]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Kmkery/Quiz.git

### Maiores dificuldades durante a implementação

Referenciar a variável _score_ de forma adequada, dentro de uma função, para que ao ser executada retornasse o valor de forma correta (por vezes eu me confundia com a questão de escopos).

### Menores dificuldades durante a implementação

Adicionar o _eventListener_, referenciar os elementos da página html.

**Comment by Roger-Melo** [comment]
Olá @Kmkery.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Kmkery!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Referenciar a variável score de forma adequada, dentro de uma função, para que ao ser executada retornasse o valor de forma correta (por vezes eu me confundia com a questão de escopos).

Isso mesmo. Se `score` é declarada dentro do callback de envio do form, a cada envio do form, uma nova `score` será criada em memória.

Se `score` é declarada em escopo global e é usada dentro do callback, a cada envio do form, `score` será apenas reutilizada =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou claro o percentual de acerto no quiz. Isso é bom para a usabilidade, pq traz mais clareza do progresso do usuário no quiz em relação à pontuação total.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Usabilidade

Ao repousar o mouse sobre o botão de envio, o ideal é que o cursor do mouse mude para a "mãozinha", indicando um possível clique.

Um teste que vc pode fazer é inserir um botão "voltar" ao invés de incentivar o usuário a recarregar a página para tentar novamente. Após o clique nesse botão, vc pode manipular classes CSS que contém a propriedade display, pra deixar certos elementos visíveis ou invisíveis. Pegou a ideia? =)

---

## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`scoreProcessing` soa mais como substantivo do que verbo. Para deixar mais claro a ação que essa função executa, um nome possível e que denota que várias operações são feitas ao enviar o quiz seria `handleQuizSubmit`.

Se `userResponses` for nomeada como `userAnswers`, e leitura da condição do if fica ainda mais coerente, pois parâmetro e const usam "answer" para se referir à resposta(s):

```javascript
// antes
correctAnswer === userResponses[index]
```

```javascript
// depois
correctAnswer === userAnswers[index]
```

---

## Sugestão de refactoring

Antes de qualquer coisa, saiba que o mais importante num primeiro momento vc já fez, que é fazer funcionar =)

O que vou sugerir abaixo são apenas lapidações possíveis para algo que já funciona, ok?

Ao invés de apenas declarar um objeto com as mensagens de feedback, vc pode criar uma função `getFeedbackMessage` que retorna a mensagem de acordo com a pontuação:

```javascript
// antes
const showFeedback = score => {
  const feedbackMessages = {
    badScore: `${score}% de acerto, não foi desta vez. Mas não desista, tente de novo ;)`,
    weakScore: `${score}% de acerto... que tal tentar de novo? =)`,
    goodScore: `Você acertou ${score}%. Muito bom! =)`,
    excelentScore: `Uau, você acertou ${score}%. Parabéns! =D`
  }
  
  // ...
}
```

```javascript
// depois
const getFeedbackMessage = score => ({
  0: `${score}% de acerto, não foi desta vez. Mas não desista, tente de novo ;)`,
  25: `${score}% de acerto... que tal tentar de novo? =)`,
  50: `Você acertou ${score}%. Muito bom! =)`,
  75: `Você acertou ${score}%. Muito bom! =)`
})[score] || `Uau, você acertou ${score}%. Parabéns! =D`

const showFeedback = score => {
  const feedbackMessage = getFeedbackMessage(score)
  // ...
}
```

Se vc ainda não chegou na aula onde mostro essa técnica, não se preocupe, em breve vc a conhecerá.

A desvantagem da abordagem acima é que as msgs de 50 e 75 pontos acabaram ficando repetidas. Mas é uma oportunidade para vc criar uma mensagem diferente para cada pontuação =)

Feito isso, vc não precisa mais encadear vários `if/else`. 

Vc pode simplesmente especificar que `textContent` receberá a mensagem que a função retornou:

```javascript
// antes
const showFeedback = score => {
  const feedbackMessage = getFeedbackMessage(score)
  const { badScore, weakScore, goodScore, excelentScore } = feedbackMessages

  if (score === 0) {
    feedback.textContent = badScore
  } else if (score === 25) {
    feedback.textContent = weakScore
  } else if (score === 100) {
    feedback.textContent = excelentScore
  } else {
    feedback.textContent = goodScore
  }

  // ...
}
```

```javascript
// depois
const showFeedback = score => {
  const feedbackMessage = getFeedbackMessage(score)
  feedback.textContent = feedbackMessage
  // ...
}
```

Ou, uma versão mais concisa:

```javascript
const showFeedback = score => {
  feedback.textContent = getFeedbackMessage(score)
  // ...
}
```

Já que é necessário o usuário recarregar a página para enviar novamente, `feedback` e `helpMessage` (e suas manipulações CSS) ao invés de ficarem em escopo global, podem ficar dentro da `showFeedback`, perto de onde outras manipulações nesses elementos são feitas:

```javascript
// antes
const feedback = document.createElement('p')
feedback.classList.add('feedback')
const helpMessage = document.createElement('p')
helpMessage.classList.add('help-message')

// ...

const showFeedback = score => {
  feedback.textContent = getFeedbackMessage(score)

  formBox.remove()
  helpMessage.textContent = `Recarregue a página para tentar de novo`
  description.insertAdjacentElement('afterend', feedback)
  feedback.insertAdjacentElement('afterend', helpMessage)
}
```

```javascript
// depois
const showFeedback = score => {
  const feedback = document.createElement('p')
  const helpMessage = document.createElement('p')
  
  feedback.textContent = getFeedbackMessage(score)
  helpMessage.textContent = `Recarregue a página para tentar de novo`
  feedback.classList.add('feedback')
  helpMessage.classList.add('help-message')
  description.insertAdjacentElement('afterend', feedback)
  feedback.insertAdjacentElement('afterend', helpMessage)
  formBox.remove()
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Kmkery** [comment]
Oi @Roger-Melo, muito obrigada pelas análises! Fez todo sentido sim, muita coisa não havia pensado ou ainda nem imaginava que era possível (como no caso do objeto que armazena as mensagens do score, bem melhor do jeito que você disse). Também sobre como nomear variáveis e funções, achei muito mais lógico. Alterei os arquivos com as sugestões que deu e atualizei no repositório.

Sobre a parte de mostrar/ocultar o formulário, mensagem de feedback e o botão de "voltar", como você sugeriu manipular via CSS, aproveitei para alterar a forma como o parágrafo das mensagens de help e feedback são inseridos (ao invés de criar e inserir "dinamicamente" os parágrafos pelo JS, criei uma div com estes parágrafos diretamente no arquivo HTML e deixei esta div inicialmente oculta via CSS) e inseri uma função para alternar a visibilidade do formulário e da mensagem + botão (função _changeDisplay()_, que altera a classe _“hidden”_ dos elementos mencionados). Está correto assim?

**Comment by Roger-Melo** [comment]
Excelente solução @Kmkery! =)

Essa não é uma função fácil de nomear, pois manipula a visibilidade de dois elementos distintos. Mas para deixar o nome dela mais descritivo sobre a ação que ela executa, ela poderia ser chamada de `changeFeedbackDisplay`, ou algo do tipo. O que acha?

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue.

Conte comigo para chegar na fluência =)

**Comment by Kmkery** [comment]
Muito obrigada, @Roger-Melo 😄🙏
