### ISSUE TITLE
Aplicação: Todo List

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#2464]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ElaineDelgado/todo-list-cjrm

### Maiores dificuldades durante a implementação

- Refatorar o código que filtra os Todos  removendo os códigos repetidos;
- Implementar lógica usando o Dataset para remover os todos.

### Menores dificuldades durante a implementação

- Trocar a classe que é adicionada e removida adicionando uma classe exclusiva para essa funcionalidade e removendo a classe Bootstrap do HTML;

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Refatorar o código que filtra os Todos removendo os códigos repetidos;

Vou mostrar ali em baixo uma forma de abstrair as repetições, mas lembre-se: o mais importante num primeiro momento vc já fez, que é fazer funcionar =)

> ### Implementar lógica usando o Dataset para remover os todos.

Nas aulas seguintes vc será apresentada ao atributo `data-*` e ao `dataset`. Esse primeiro contato foi apenas um pequeno desafio para vc conhecê-los por conta própria.

Também vou dar um toque em relação à remoção dos to-dos com o dataset, ali abaixo =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar. Peço que execute com calma cada código que mostrarei abaixo, ok?

---

## Comentários

Não é uma regra, mas prefira não comentar o código.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Indentação

Indentação é um dos pilares de um código legível.

Para dar mais legibilidade à inserção do to-do no DOM, vc pode ajustar a indentação da `<li>`:

```javascript
// antes
todosContainer.innerHTML += `
<li class="list-group-item show" data-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete" data-delete="${inputValue}"></i>
    </li>
`
```

```javascript
// depois
todosContainer.innerHTML += `
  <li class="list-group-item show" data-todo="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete" data-delete="${inputValue}"></i>
  </li>
`
```

---

## Clique fora da lixeira

No momento de remover um to-do, se ao invés de clicar na lixeira o texto do to-do ou a li for clicado(a), um `app.js:22 Uncaught TypeError: Cannot read properties of null (reading 'remove')` é lançado.

O erro diz que não foi possível ler propriedades de `null` (ao ler 'remove').

Na função abaixo, `remove` é um método que está encadeado em `todo`:

```javascript
const removeTodo = (event) => {
  const dataDelete = event.target.dataset.delete
  const todo = document.querySelector(`[data-todo="${dataDelete}"]`)
  todo.remove()
}
```

Se `remove` foi encadeada em `todo` e a mensagem do erro diz que não é possível ler a propriedade `remove` de `null`, isso significa que quando um clique acontece em qualquer elemento de `todosContainer` (ul) que não seja a lixeira, `todo` está recebendo `null`.

Podemos comprovar isso se exibirmos `todo` no console:

```javascript
const removeTodo = (event) => {
  // ...
  console.log(todo) // null
  todo.remove()
}
```

`todo` está recebendo null pq `document.querySelector(...)` retorna `null` caso esse elemento não seja encontrado no DOM.

Se vc executar a expressão `null.remove()` no console do browser, verá que o mesmo erro é lançado:

```javascript
null.remove() // Uncaught TypeError: Cannot read properties of null (reading 'remove')
```

Ou seja, como não existe uma propriedade/método `remove` em `null`, o erro dizendo que não é possível ler `remove` em `null` é lançado.

Para que esse erro não aconteça, antes de executar o `remove` vc precisará verificar se o elemento clicado foi o ícone de remoção do to-do.

Se o elemento clicado contém o atributo `data-delete`, a expressão `event.target.dataset.delete` resultará no valor da propriedade `delete` do objeto dataset:

```javascript
const removeTodo = (event) => {
  console.log(event.target.dataset.delete) // "Assistir Breaking Bad"
}
```

Se o elemento clicado não contém o atributo `data-delete`, a expressão `event.target.dataset.delete` resultará em `undefined`, pois não existe uma propriedade `delete` no objeto dataset:

```javascript
const removeTodo = (event) => {
  console.log(event.target.dataset.delete) // undefined
}
```

Sendo assim, vc pode fazer isso attribuir essa expressão à uma const `deleteIconWasClicked` por exemplo, e usar essa const como condição do if que remove o to-do:

```javascript
const removeTodo = (event) => {
  const deleteIconWasClicked = event.target.dataset.delete
  
  if (deleteIconWasClicked) {
    const todo = document.querySelector(`[data-todo="${deleteIconWasClicked}"]`)
    todo.remove()
  }
}
```

Dessa forma, se `deleteIconWasClicked` armazena `undefined` a remoção do to-do não acontece e, se armazena uma string preenchida (string do to-do), a remoção é executada.

---

## Sugestões de refatoração

Para dar mais organização ao código, os `addEventListener`s podem ficar agrupados e o callback que adiciona um to-do pode se chamar `addTodo`:

```javascript
const addTodo = (event) => {
  // ...
}

formAddTodo.addEventListener('submit', addTodo)
```

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

Primeiro, observe que é possível eliminar a duplicação de `Array.from(todosContainer.children)` ao armazenar essa função em uma const `todos`:

```javascript
// antes
const searchTodo = (event) => {
  const inputValue = event.target.value.trim().toLowerCase()

  Array.from(todosContainer.children)
    .filter(/* ... */)
    // ...

  Array.from(todosContainer.children)
    .filter(/* ... */)
    // ...
}
```

```javascript
// depois
const searchTodo = (event) => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  todos
    .filter(/* ... */)
    // ...

  todos
    .filter(/* ... */)
    // ...
}
```

Agora, vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Vc pode, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = (event) => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(newTodos) // [{…}, {…}, {…}]

  // todos
  //   .filter((todo) => !todo.textContent.toLowerCase().includes(inputValue))
  //   .forEach((todo) => {
  //     todo.classList.remove('show')
  //     todo.classList.add('hidden')
  //   })

  // todos
  //   .filter((todo) => todo.textContent.toLowerCase().includes(inputValue))
  //   .forEach((todo) => {
  //     todo.classList.remove('hidden')
  //     todo.classList.add('show')
  //   })
}
```

Agora que há um array de objetos que indicam se o to-do deve estar visível, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = (todos) => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'show' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'show')
  })
}

const searchTodo = (event) => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  const newTodos = todos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(newTodos)
}
```

Se vc quiser, pode deixar o código mais conciso, eliminando as consts `inputValue` e `todos`, e modificando o nome da `newTodos` para `todos`:

```javascript
const filterTodos = (todos) => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'show' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'show')
  })
}

const searchTodo = (event) => {
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(event.target.value.trim().toLowerCase())
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas vou dizer novamente... lembre-se: o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funcionava =)

---

Nas aulas seguintes, você verá formas outras de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço Elaine =)

As observações fizeram sentido?

**Comment by ElaineDelgado** [comment]
Boa tarde, professor,

### Sim, as observações fizeram, muito sentido.

### Clique fora da lixeira:

1- Analisando o código após sua explicação me dei conta que o elemento li  é armazenado numa const 'todo' que é obtida com o querySelector através do valor 'delete' do tributo 'data' da lixeira, se eu clicar fora não tem como obter esse data-delete para armazenar o todo.

2- Verificação com 'if' : 
Foi sugerido verificar a existência do deleteIconWasClicked  (atributo data do ícone da lixeira), mas se verificarmos o próprio todo em vez disso também funciona sem erro. Só a nível de curiosidade, há alguma razão em não fazer assim (código abaixo) ou tanto faz verificar um ou outro?
```js
const removeTodo = (event) => {
  const deleteIconWasClicked = event.target.dataset.delete
  const todo = document.querySelector(`[data-todo="${deleteIconWasClicked}"]`)
  if (todo) {
    todo.remove()
  }
}
```
### Sugestões de refatoração
Criar um array de objetos que armazena o todo e um boolean foi uma sacada que eu nem cogitei, assim como esses objetos na filterTodos para filtrar os todos.
Me pergunto se esse tipo de pensamento de solução de problemas vem com o tempo...

```js 
const filterTodos = (todos) => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'show' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'show')
  })
}
```

De forma geral, entendi tudo que foi feito, e sim, faz todo sentido, mas é uma solução que não teria imaginado.
### Obrigada!!!

**Comment by Roger-Melo** [comment]
> ### Foi sugerido verificar a existência do deleteIconWasClicked  (atributo data do ícone da lixeira), mas se verificarmos o próprio todo em vez disso também funciona sem erro. Só a nível de curiosidade, há alguma razão em não fazer assim (código abaixo) ou tanto faz verificar um ou outro?

No código abaixo, se `deleteIconWasClicked` resulta em false, a busca do to-do no DOM vai acontecer da mesma forma. Não que isso tenha um grande impacto, mas não tem pq fazer essa busca no DOM. É desnecessário buscar um `data-todo="undefined"` (lembra que `event.target.dataset.delete` pode resultar em `undefined?)`.

```js
const removeTodo = (event) => {
  const deleteIconWasClicked = event.target.dataset.delete
  console.log(deleteIconWasClicked)
  const todo = document.querySelector(`[data-todo="${deleteIconWasClicked}"]`)

  if (todo) {
    todo.remove()
  }
}
```

Execute o console.log acima ao clicar fora da lixeira e vc verá que `deleteIconWasClicked` resulta em `undefined`. Isso quer dizer que logo em seguida, o querySelector buscou por um elemento que contém `data-todo` armazenando `undefined`.

Então faz mais sentido obter o to-do depois de ter a certeza que o elemento clicado foi a lixeira =)

Sacou a ideia?

---

> ### Me pergunto se esse tipo de pensamento de solução de problemas vem com o tempo...

Vem com a prática.

Conforme vc vai praticando transformar dados (e vc ainda praticará isso bastante no treinamento), mais insights vc vai ter de como usar isso ao seu favor =)

**Comment by Roger-Melo** [comment]
> ### Foi sugerido verificar a existência do deleteIconWasClicked  (atributo data do ícone da lixeira), mas se verificarmos o próprio todo em vez disso também funciona sem erro. Só a nível de curiosidade, há alguma razão em não fazer assim (código abaixo) ou tanto faz verificar um ou outro?

No código abaixo, se `deleteIconWasClicked` resulta em false, a busca do to-do no DOM vai acontecer da mesma forma. Não que isso tenha um grande impacto, mas não tem pq fazer essa busca no DOM. É desnecessário buscar um `data-todo="undefined"` (lembra que `event.target.dataset.delete` pode resultar em `undefined?)`.

```js
const removeTodo = (event) => {
  const deleteIconWasClicked = event.target.dataset.delete
  console.log(deleteIconWasClicked)
  const todo = document.querySelector(`[data-todo="${deleteIconWasClicked}"]`)

  if (todo) {
    todo.remove()
  }
}
```

Execute o console.log acima ao clicar fora da lixeira e vc verá que `deleteIconWasClicked` resulta em `undefined`. Isso quer dizer que logo em seguida, o querySelector buscou por um elemento que contém `data-todo` armazenando `undefined`.

Então faz mais sentido obter o to-do depois de ter a certeza que o elemento clicado foi a lixeira =)

Sacou a ideia?

---

> ### Me pergunto se esse tipo de pensamento de solução de problemas vem com o tempo...

Vem com a prática.

Conforme vc vai praticando transformar dados (e vc ainda praticará isso bastante no treinamento), mais insights vc vai ter de como usar isso ao seu favor =)

@ElaineDelgado

**Comment by ElaineDelgado** [comment]
Perfeito, agora ficou bem claro a verificação do deleteIconWasClicked  em vez de verificar o todo!!
Muito obrigada!!!
😄

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue.

Conte comigo para chegar na fluência =)
