### ISSUE TITLE
Resumo da Aula setTimeout() e o objeto window 02-02 da etapa 07

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2474]
O objeto **`window`** é o objeto que existe no escopo global de uma aplicação e varia de acordo com o ambiente em que a aplicação está sendo executada. No node.js (utilizado em backend), este objeto se chama _global_. 

O objeto **`window`** armazena todos os métodos que podem ser utilizados na aplicação. Um exemplo, o **`window.outerwidth`** exibe a largura total da tela onde o _html_ está sendo exibido.

Ao utilizar propriedades ou métodos do objeto **`window`**, podemos omitir a palavra _"window"_. A exemplos, costumamos usar o **`console.log()`** e o **`document.querySelector()`**, que é a mesma coisa que **`window.console.log()`** e **`window.document.querySelector()`**, pois ambos são métodos do objeto **`window`**.

O **`.setTimeout()`** é um método de **`window`** e executa uma função após um determinado tempo. Ele recebe dois argumentos, a função **_callback_** e o **_tempo_**, em milissegundos, no qual ele deve aguardar para então executar a _callback_.

Na aplicação Quiz desenvolvida nas aulas, a mensagem de pontuação retornada ao usuário foi inserida logo após o título da aplicação, trazendo um problema de rolagem de página (o usuário teria que rolar a página para cima para visualizar a pontuação). Para contornar este problema, foi utilizado um método armazenado em **`window`**, o **`scrollTo()`**, que recebe dois argumentos correspondentes à _coordenada x_ e _coordenada y_ da tela. A contagem de pixel começa no canto superior à esquerda, assim y cresce em direção do rodapé e x cresce em direção à direita. Este método necessitou ser inserido antes de a classe Bootstrap _“d-none”_ ser removida para a exibição da mensagem da pontuação, desta forma, quando o formulário era enviado, a template string com o **`score`** era inserida no textContent do parágrafo de mensagem e a página exibida na coordenada **`scrollTo(0,0)`**, correspondente ao início da tela.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. vamo que vamo, rumo à fluência! 🙌
