### ISSUE TITLE
Remover classe de um elemento

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2476]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 01 da etapa 14 - Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1643666

### Descreva a dúvida

Olá, @Roger-Melo 

Acabei de corrigir os exercícios 36 e achei bem interessante o exercício para implementar um carousel. 
Nesse exercício uma das coisas que precisamos fazer é remover a classe que deixa os slides vísiveis antes de adicioná-la no slide que deve ser exibido. 

Na aula você usa um forEach para percorrer todos os slides e remover essa classe. 

Não seria melhor selecionar diratamente o slide que possui a classe ao invés de percorrer todos os itens? Pq afinal sempre só vai existir um slide por vez com essa classe. Então percorer o todos os slides tentando remover uma classe não parece ser necessário. 

Tem algum motivo para ter sido feito dessa forma?
Teria algum problema em selecionar no DOM diretamente o elemento que está com a classe?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior!

Ótima observação. Na real, pode ser feito dessa forma tb =)

Vc pensou em algo desse tipo?

```javascript
const manipulateSlidesClasses = correctSlideIndex => {
  const CSSClass = 'carousel__item--visible'

  document.querySelector(`.${CSSClass}`).classList.remove(CSSClass)
  slides[correctSlideIndex].classList.add(CSSClass)
}
```

**Comment by Hamiltonspjunior** [comment]
Oi, @Roger-Melo 

Isso mesmo!

Já cheguei a usar esse padrão em outras situações desse tipo também, pra selecionar apenas o elemento necessário. 

Mas achei que talvez pudesse ter algum problema ou desvantagem envolvido ao fazer dessa forma. 

Legal saber que assim também funciona. 

Obrigado!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue.

Conte comigo pra chegar na fluência =)
