### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#2485]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ThiagoDeMorais/Aplica-o-To-do-list.git

### Maiores dificuldades durante a implementação

1 - Implementação da lógica para substituir a navegação pelo DOM pelo uso de *attributes data* (Na função de remoção);
2 - Implementação da função de busca de to-dos.

### Menores dificuldades durante a implementação

1 - Implementação da função de inserção de to-dos;
2 - Isolar as funções de acordo com suas responsabilidades.

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

Até aqui, seu código está legal. Deu pra perceber que vc entendeu bem a lógica e, no geral, os nomes de suas variáveis estão bem descritivas.

Sua evolução em relação à análise anterior tb é perceptível. Inclusive, não usou mais `let` hahah.

> ### 1 - Implementação da lógica para substituir a navegação pelo DOM pelo uso de attributes data (Na função de remoção);

Nas aulas seguintes isso será mostrado com mais calma, o desafio nese primeiro momento realmente era vc pesquisar e usar por conta própria. Pelo que vi, vc conseguiu =)

> ### 2 - Implementação da função de busca de to-dos.

Sim, essa funcionalidade pode ficar um pouquinho complexa. Mas ali em baixo, eu vou sugerir uma abordagem que pode simplificar esse código.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Uso de espaços em branco 

Nas ocorrências dos atributos `data-*`, há um espaço em branco antes do `=`.

É preferível que esse espaço em branco seja removido, pois `data-*` é um atributo HTML como outro qualquer. Da mesma forma que é uma convenção especificar `class="a"` ou `type="submit"`, vc pode especificar `data-js="x"` (sem espaço antes do sinal de igual).

---

## Lógica da função `removeToDo`

A lógica da `removeToDo` pode ser mais simples.

Vc pode aproveitar que a expressão `clickedElement.dataset.remove` irá resultar em `undefined` ou em uma string e usá-la diretamente como condição do `if` e valor de `data-to-do`:

```javascript
// antes
const removeToDo =  event => {
  const clickedElement = event.target;
  const dataRemove = clickedElement.dataset.remove
  const isUndefined = String(dataRemove) === 'undefined';

  if(!isUndefined){
    const toDo = document.querySelector(`[data-to-do ="${dataRemove}"]`)
    toDo.remove();
  }
}
```

```javascript
// depois
const removeToDo = event => {
  const clickedElement = event.target;
  const clickedElementWasTrash = clickedElement.dataset.remove

  if (clickedElementWasTrash) {
    const toDo = document.querySelector(`[data-to-do="${clickedElementWasTrash}"]`)
    toDo.remove();
  }
}
```

## Refactoring da função `searchToDos`

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Observe também que `toDoEnteredByUser` já pode receber o valor do input em caixa baixa.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchToDos = event => {
  const toDos = Array.from(toDosContainer.children);
  const toDoEnteredByUser = event.target.value.toLowerCase();

  const newTodos = toDos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(toDoEnteredByUser)
  }))

  console.log(newTodos) // [{…}, {…}, {…}]

  // const hiddenToDos = toDos.filter(
  //   (toDo) =>
  //     !toDo.textContent.toLowerCase().includes(toDoEnteredByUser.toLowerCase())
  // );

  // const visibleToDos = toDos.filter((toDo) =>
  //   toDo.textContent.toLowerCase().includes(toDoEnteredByUser.toLowerCase())
  // );

  // hiddenToDos.forEach((toDo) => {
  //   toDo.classList.remove("d-flex");
  //   toDo.classList.add("hidden");
  // });

  // visibleToDos.forEach((toDo) => {
  //   toDo.classList.remove("hidden");
  //   toDo.classList.add("d-flex");
  // });
}
```

Agora que há um array de objetos que indicam quais to-dos devem estar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? "d-flex" : "hidden")
    todo.classList.remove(shouldBeVisible ? "hidden" : "d-flex")
  })
}

const searchToDos = event => {
  const toDos = Array.from(toDosContainer.children);
  const toDoEnteredByUser = event.target.value.toLowerCase();

  const newTodos = toDos.map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(toDoEnteredByUser)
  }))

  filterTodos(newTodos)
}
```

Se quiser, vc pode deixar o código mais conciso, eliminando as consts `toDoEnteredByUser` e `toDos` e, modificando o nome da `newTodos` para `todos` (eu especifiquei "todos", com "d" minúsculo, mas escreva como fizer mais sentido pra vc):

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? "d-flex" : "hidden")
    todo.classList.remove(shouldBeVisible ? "hidden" : "d-flex")
  })
}

const searchToDos = event => {
  const todos = Array.from(toDosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo
      .textContent.toLowerCase().includes(event.target.value.toLowerCase())
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

---

Nas aulas seguintes, você verá formas outras de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço Thiago =)

As observações fizeram sentido?

**Comment by ThiagoDeMorais** [comment]
Boa tarde, professor Roger. As observações fizeram sentido, já refatorei tudo e já vou fazer um *commit* rsrs . Eu demorei um pouco para entender profundamente a refatoração da *searchToDos*, mas executando em partes, como foi orientado, deu pra entender bem. Gostei bastante dessa solução, a criação do array de objetos agrupa todas as informações necessárias para a função *filterTodos*, os *todos*  que vão sofrer inserção/remoção de classe e a *flag* que vai indicar o tipo de mudança . Muito obrigado por mais essa análise.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
