### ISSUE TITLE
Resumo da Aula 02-02, 02-03 da etapa 04

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#249]
@Roger-Melo
![WhatsApp Image 2021-03-04 at 09 42 37](https://user-images.githubusercontent.com/49795140/109970113-7357a700-7cd3-11eb-9cd2-48b82ca26c4b.jpeg)
![WhatsApp Image 2021-03-04 at 09 43 41](https://user-images.githubusercontent.com/49795140/109970133-78b4f180-7cd3-11eb-8ca7-779f5f89dfb0.jpeg)

**Comment by Roger-Melo** [comment]
Tamo junto @azulinho10. Rumo à fluência! 🔥
