### ISSUE TITLE
Resumo da Aula setInterval() e animação da pontuação 02-03 da etapa 07

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2498]
O método `setInterval()` é similar ao _setTimeout()_, no entanto, ele executa uma função repetidamente em um intervalo determinado.

Para pará-lo, utiliza-se o `clearInverval()`, porém é necessário que este receba o id do método _setInterval_, que é um número único obtido na execução deste método. Assim, o método deve ser armazenado dentro de uma constante e referenciado dentro de _clearInterval_.
```js
clearInterval(nome) // onde nome é o nome da constante que armazena o setInterval()
```
No exemplo do Quiz, o _setInterval_ foi adicionado dentro do _event listener_ de modo a animar a exibição da contagem de pontos. Foi inserido um contador (_counter_) inicialmente com o valor de 0, que deveria ser incrementado até o valor de _score_.

Armazenando o _setInterval_ dentro de uma constante (_timer_) e definindo a exibição de pontos com a variável _counter_, a cada 10 milissegundos o valor exibido seria incrementado, até chegar a `counter === score`, quando o _setInterval_ seria parado usando `clearInterval(timer)`.

```js
let counter = 0
const timer = setInterval( () =>{
     if(counter === score) {
        clearInterval(timer)
    }
    finalResult.querySelector(‘span’).textContent = `${counter}%`
}, 10)
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery , rumo à fluência! 🔥
