### ISSUE TITLE
Exercicio_16

### ISSUE THREAD

**Issue by DavidLSousa** [roger-melo-treinamentos/curso-de-js-roger-melo#25]
Bom dia @Roger-Melo ! 

Tive uma duvida na forma como vc fez a primeira questão do exercício 16. Você optou por add o event.stopPropagation() acima do console.log(), isso na pratica teria alguma diferença, ou nesse caso a ordem não tem tanta importância?

elementsInsideDiv.forEach(element => {
  element.addEventListener('click', event => {
    console.log('Clicou no filho da div.')
    event.stopPropagation()
  })
})

**Comment by Roger-Melo** [comment]
Oi @DavidLSousa!

O `stopPropagation()` é apenas um método que impede que o evento que aconteceu no elemento se propague em direção aos elementos pais. A invocação dele não faz as linhas abaixo da invocação serem ignoradas.

Então nesse caso tanto faz inserir o console.log() acima ou abaixo da invocação do `stopPropagation()`.

Respondi a dúvida? Se não tiver ficado claro é só avisar que respondo de outra forma =)

**Comment by DavidLSousa** [comment]
Respondeu sim! Obrg!

Poderia fazer uma perg que não tem haver com as questões ?

**Comment by Roger-Melo** [comment]
@DavidLSousa claro! Pode falar =)

**Comment by DavidLSousa** [comment]
Desculpe ter feito esse pedido, mas eu não tenho nenhum profissional que pudesse me dar uma ajuda com isso;

Eu tenho a oportunidade de iniciar agr um curso de tecnólogo em análise e desenvolvimento de sistemas, queria saber o que vc acha de iniciar esse curso e simultaneamente manter a rotina que ja tenho com seu curso de JS. 
Esse curso poderia me dar uma base para avançar como programador? Não sei se seguiria a carreira de analista de sistemas, acho que gosto mais da criação de novas aplicações.

Eu estou iniciando agr e estou gostando mt do curso, da sua metodologia e dos exercícios, que pra mim, foi o maior diferencial, não tenho intenção de parar com esse curso, quero ter uma forte base em JS. Mas sempre que pesquiso ou vejo videos, escuto nomes de tecnologias, APIs, SDKs, frameworks, bibliotecas e o Firebase, que aparentemente são rotina na implementação dos projetos e vejo que tudo que tenho estudado e nada parece levar a isso ate o momento. Então fico me perguntando se sem um curso algum dia chegaria a conseguir utilizar o JS para, por exemplo, criar um app desktop utilizando electron.

Obrg pela paciência!

**Comment by Roger-Melo** [comment]
Entendi. 

Você fez uma pergunta no início mas depois escreveu algumas coisas que foram para caminhos diferentes.

Então para eu ter mais contexto, eu preciso pegar 1 trecho do que você falou e perguntar sobre. Só que eu preciso que você seja mais objetivo em suas respostas.

Eu posso responder tudo o que você perguntou acima, mas prefiro ir passo-a-passo, para que de fato a gente consiga chegar em algum lugar.

> Eu tenho a oportunidade de iniciar agr um curso de tecnólogo em análise e desenvolvimento de sistemas, queria saber o que vc acha de iniciar esse curso e simultaneamente manter a rotina que ja tenho com seu curso de JS.
Esse curso poderia me dar uma base para avançar como programador? Não sei se seguiria a carreira de analista de sistemas, acho que gosto mais da criação de novas aplicações.

Em uma frase simples, quero que você responda a seguinte pergunta: onde você quer estar daqui há 1 ano?

Eu não posso decidir isso por você. É uma pergunta simples. Responda com uma frase simples.

@DavidLSousa

**Comment by DavidLSousa** [comment]
Acabou que ficou um pouco longo mesmo...

Resp: Quero poder me enxergar como um profissional. Não necessariamente contratado por uma empresa, mas confortável pra poder iniciar como um freelancer, com clientes na região onde moro.

**Comment by Roger-Melo** [comment]
Ótimo.

Nossas decisões devem (ou deveriam) ser baseadas em nossos objetivos. Um curso de tecnólogo em análise e desenvolvimento de sistemas (para mim) não faz sentido, nesse caso.

Esqueça o "conforto para iniciar" em algo. Você já fechou pelo-menos 1 projeto com algum cliente da região onde você mora?

@DavidLSousa

**Comment by DavidLSousa** [comment]
Não cheguei a procurar clientes ainda.
Eu comecei a ter uma liberdade maior com CSS junto com a chegada da pandemia, então não cheguei a procurar. @Roger-Melo

**Comment by Roger-Melo** [comment]
Faculdade não vai te "preparar" para o mercado. Seja ele qual for.

## A oportunidade está em baixo do seu nariz

mas você não está enxergando ela.

O CJRM, o treinamento que você pagou por ele, **FUNCIONA**. O método aplicado no curso **FUNCIONA**. Se quiser provas, veja esses vídeos:

https://www.youtube.com/playlist?list=PLpSJMw6H4PFNMTHMhRyHHME_JZA80vstu

Se você não se sente "preparado o suficiente" tecnicamente, é justamente por que está começando agora e não por que o curso ou método é ineficaz.

Vi seu progresso no curso, 45%. Entrou há 2 meses.

> Mas sempre que pesquiso ou vejo videos, escuto nomes de tecnologias, APIs, SDKs, frameworks, bibliotecas e o Firebase, que aparentemente são rotina na implementação dos projetos e vejo que tudo que tenho estudado e nada parece levar a isso ate o momento. Então fico me perguntando se sem um curso algum dia chegaria a conseguir utilizar o JS para, por exemplo, criar um app desktop utilizando electron.

Ninguém vai à academia e espera ficar sarado com 2 meses de treino.

Firebase, por exemplo, será abordado na etapa 15 do treinamento. Mas antes, você precisa ter base para aprendê-lo.

Se você não aprender a base antes que querer aprender todo o ferramental que mencionou acima, estatisticamente as chances de você dar com a cara na parede são gigantescas.

O que você escreveu só me faz pensar que você está ansioso. Ansiedade e qualquer outra coisa é difícil de ser conciliada e costuma gastar energia desnecessária. O ideal é você aprender a domar sua ansiedade. Se necessário, caso esteja te incomodando muito, procure ajuda profissional.

> e vejo que tudo que tenho estudado e nada parece levar a isso ate o momento

Se você não aprender a fazer a sua parte e ter paciência, não há curso no mundo que irá te satisfazer. Não terceirize o que é responsabilidade sua. 

Dá trabalho. Não é fácil. Cabe a você se comprometer e ser consistente. Ou desistir.

**Comment by Roger-Melo** [comment]
Faculdade não vai te "preparar" para o mercado. Seja ele qual for.

## A oportunidade está em baixo do seu nariz

mas você não está enxergando ela.

O CJRM, o treinamento que você pagou por ele, **FUNCIONA**. O método aplicado no curso **FUNCIONA**. Se quiser provas, veja esses vídeos:

https://www.youtube.com/playlist?list=PLpSJMw6H4PFNMTHMhRyHHME_JZA80vstu

Se você não se sente "preparado o suficiente" tecnicamente, é justamente por que está começando agora e não por que o curso ou método é ineficaz.

Vi seu progresso no curso, 45%. Entrou há 2 meses.

> Mas sempre que pesquiso ou vejo videos, escuto nomes de tecnologias, APIs, SDKs, frameworks, bibliotecas e o Firebase, que aparentemente são rotina na implementação dos projetos e vejo que tudo que tenho estudado e nada parece levar a isso ate o momento. Então fico me perguntando se sem um curso algum dia chegaria a conseguir utilizar o JS para, por exemplo, criar um app desktop utilizando electron.

Ninguém vai à academia e espera ficar sarado com 2 meses de treino.

Firebase, por exemplo, será abordado na etapa 15 do treinamento. Mas antes, você precisa ter base para aprendê-lo.

Se você não aprender a base antes que querer aprender todo o ferramental que mencionou acima, estatisticamente as chances de você dar com a cara na parede são gigantescas.

O que você escreveu só me faz pensar em uma palavra: ansiedade. Ansiedade e qualquer outra coisa é difícil de ser conciliada e costuma gastar energia desnecessária. O ideal é você aprender a domar sua ansiedade. Se necessário, caso esteja te incomodando muito, procure ajuda profissional.

> e vejo que tudo que tenho estudado e nada parece levar a isso ate o momento

Você precisa fazer a sua parte e ter paciência. Se não conseguir, não há curso no mundo que irá te satisfazer. Tome cuidado para não terceirizar o que é de sua responsabilidade. 

Dá trabalho. Não é fácil, mas vale a pena. Cabe a você se comprometer e ser consistente. Ou desistir.

**Comment by DavidLSousa** [comment]
Obrg Roger!

Vou continuar no desenvolvimento do curso, como tinha falado, realmente já vi bastante resultado ate aqui. Acho que no final acaba sendo mais curiosidade de saber como as coisas funcionam do que ansiedade em si, mas tem razão, vou prosseguir focado no curso e lendo a documentação.

Obrg por responder!

**Comment by Roger-Melo** [comment]
Bacana @DavidLSousa. 

Quando o curso estiver mais maduro, pretendo introduzir novos conteúdos sobre mercado, posicionamento, clientes, processos seletivos, etc.

Por enquanto, recomendo que apenas continue focado em se tornar fluente em JavaScript - construir aplicações com JS puro, sem grandes dificuldades. Isso já irá te destacar dos 80% que não tem a fluência.

Vou fechar a issue, por agora.

Mas no que precisar, é só chamar aqui =)
