### ISSUE TITLE
Resumo da Aula Buscando e Filtrando to-dos da etapa 09

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2509]
- Buscar referências do form de busca e seu input;
- Adicionar um  evento para escutar o valor digitado **(input)**;
- Realizar a conversão do HTMLCollection com **Array.from();**
- **Filtrar** as lis, para adicionarmos valores nas classes para remover ou adicionar o to-do na tela do usuário;
- Para isso utilizaremos o **forEach**;
- Não esquecer de comparar o valor digitado com o que estão na ul, com o método **includes**(serve para os array e também para as strings);

**Comment by Roger-Melo** [comment]
Boa @carlosdevjs , rumo à fluência! 🔥
