### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by betomouse** [roger-melo-treinamentos/curso-de-js-roger-melo#251]
Fala Roger, segue abaixo link do repositório com arquivos do exercício Quiz Interativo.
Acho que eu ia sofrer muito se não tivesse lembrado como você armazenou e comparou os valores dos campos.
Achei bem simples colocar na tela o score, sem dificuldades até aqui.

[Link do repositório](https://github.com/betomouse/quizinterativo)

Obs: Aplico o Ater em todas as aulas, mas meus rascunhos são horríveis, escrevo muita coisa relacionada a meu modo de pensar como se fossem pequenas dicas com base nas dificuldades que eu tive. Tenho até vergonha de publicar. ( Me esforçando pra melhorar isso. )

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @betomouse.

Passando para avisar que sua issue foi visualizada e que a análise da aplicação já está sendo feita e em breve =)

**Comment by Roger-Melo** [comment]
Oi Alberto.

Parabéns pelo esforço em implementar a aplicação!


Sobre os resumos, fico feliz em saber que está executando. Publique apenas quando se sentir à vontade =)

O repositório é [este](https://github.com/betomouse/quizinterativo), certo?

Para inserir a url de um repositório em issues do GitHub, basta colar o link desta forma: `[texto do link](url)`. Editei isso na issue que foi aberta acima.

As urls HTTPS, SSH e GitHub CLI disponibilizadas no botão verde `code` que fica na página do repositório são utilzadas apenas para clonar o repositório na máquina local =)

Você escolheu bem o local de exibição dos pontos e, pelo que percebi, entendeu bem a lógica até aqui.

Percebi também que você tentou fazer o mais próximo possível do que foi mostrado nas aulas, e isso é excelente. Antes de inovar a receita, é preciso dominá-la. 

Vou deixar abaixo, separadas por critérios, algumas oportunidades de melhoria que identifiquei na análise. Lembrando que na análise, estou considerando o código do momento em que a issue foi aberta.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo checked no input type radio a ser exibido por padrão como "marcado". 

Isso é mais uma preferência pessoal mas acredito que incentiva mais o usuário a marcar a resposta que ele acredita que seja a verdadeira.

## Organização de código

### Local de declaração de variáveis/consts

Agrupar consts por declaração é um bom começo para organizar o código.

Uma maneira de intensificar ainda mais esse tipo de organização é separar consts por "categorias" de valores que elas armazenam.

Então ao invés de agrupar todas as declarações de consts em um só "bloco", você pode separar as consts que armazenam referências dos elementos do DOM:

```javascript
// antes
const form = document.querySelector('form')
const aceptAnswers = ['D', 'B', 'B', 'E']
const button = document.querySelector('button')
const p = document.createElement('p')

// depois
const form = document.querySelector('form')
const button = document.querySelector('button')

const p = document.createElement('p')
const aceptAnswers = ['D', 'B', 'B', 'E']
```

Se você for muito conservador, pode separar ainda mais, isolando as duas últimas consts:

```javascript
const form = document.querySelector('form')
const button = document.querySelector('button')

const p = document.createElement('p')

const aceptAnswers = ['D', 'B', 'B', 'E']

// ...
```

### Nomes de variáveis e funções

`p` é um nome vago para uma const. É um nome ok para uma aplicação que tem só um p, mas no caso dessa aplicação, o ideal é que a const seja um substantivo que descreva o valor que ela está armazenando. O mesmo vale para a const `button`.

Como `p` armazena o elemento que irá conter a pontuação final, você pode nomeá-la enfatizando isso.

Já no caso do button, você pode descrever pra quê ele existe:

```javascript
// antes
const p = document.createElement('p')
const button = document.querySelector('button')

// depois
const finalScoreContainer = document.createElement('p')
const buttonSubmitAnswers = document.querySelector('button')
```

Para deixar mais claro que `aceptAnswers` armazena um array que contém as repostas corretas, ela pode ser renomeada como `correctAnswers`.

"aswer1" é um erro de digitação/ortográfico que escalou, tanto no html como no app.js. Para não ter que renomear uma por uma, você pode (no VSCode) selecionar `aswer` e pressionar `ctrl + shift + f`. Um painel lateral será exibido. Note que haverá um input com o valor `aswer` e do lado esquerdo haverá uma seta. Clique na seta e um segundo input com um placeholder "replace" será exibido. Insira a palavra correta nesse input e pressione `ctrl + alt + enter` para substituir todas as ocorrências das palavras em todo o projeto. Se não quiser usar esse último shortcut, ao lado direito do novo input haverá um ícone. Se você repousar o mouse sobre o ícone um tooltip escrito "Replace All" será exibido. Então é só clicar nele.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos.

Então procure evitar o excesso e/ou a falta delas no código.

Seguindo esse princípio, as linhas em branco 38, 45, 52 e 53 podem ser removidas e linhas em branco podem ser inseridas antes e depois das declarações das lets score, aceptAnswers e p, e também antes da linha 47.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código. Exemplo:

---

Mais uma vez, parabéns pelo esforço, Alberto.

As observações fizeram sentido?

@betomouse

**Comment by betomouse** [comment]
Que feedback foi esse!!! Mil vezes Obrigado @Roger-Melo !!!
Não imaginava esse tipo de retorno!!!
Anotei TUDO! Compreendi TUDO perfeitamente!
Vou fazer a melhora de Usabilidade na interface do usuário e
organizar meu código.

**Comment by Roger-Melo** [comment]
Legal @betomouse. No que precisar, é só abrir novas issues =)
