### ISSUE TITLE
Resumo da Aula Mais sobre o Spread Operator: Casos de uso em strings e funções - Aula 01-06 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2518]
Podemos utilizar o *spread operator* também com *strings*. Vamos refator um código já criado anteriormente, que é uma função que retorna uma *string* com a ordem invertida. Essa função faz um `split()`, depois o `revere()` e em seguida o `join()`. Na refatoração vamos utilizar o *spread* no lugar da invocação do `split()` junto a *string*.

```php
const getReversedString = string => [...string]
    .reverse()
    .join('')

console.log(getReversedString('123'));
```

O *spread* serve para espalhar os números. E podemos utilizar disso para obter o maior e o menor número de um *array*. O objeto `Math` tem os métodos `min()` e `max()`, que retornam respectivamente o menor número e o maior número de uma lista de números. Porém se tivermos essa lista de números em um *array*, se passarmos o *array* como argumento, `NaN` será retornado. Isso porque são métodos que esperam uma lista de números, e não um *array*. Então é aí que entra o *spread operator*. Vamos ver no exemplo abaixo como faríamos para obter o menor e o maior número de um array de números:

```php
numbers = [3, 6, 1, 14, 5];

console.log(Math.min(...numbers));
console.log(Math.max(...numbers));
```

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas , rumo à fluência! 🔥
