### ISSUE TITLE
Prioridade de comandos na hora da refatoração

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#2519]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Tenho uma dúvida em relação a refatoração de funções. Por exemplo, na penúltima questão dessa aula, o exercício manda refatorar a função abaixo:

```js
const isAnSUV = car => {
  if (car === 'Honda HR-V' || car === 'Jeep Renegade' || car === 'Ford EcoSport' || car === 'Hyundai iX35') {
    return true
  }

  return false
}
```
Eu resolvi da seguinte maneira:
```js
const funcaoteste = (param1) =>{
  switch (param1) {
    case 'Honda HR-V':
      return true
    case 'Jeep Renegade':
      return true
    case 'Ford EcoSport':
      return true
    case 'Hyundai iX35':
      return true
    default:
      return false
  }
}
```
Como pode ver, eu refatorei a função por meio de switch, o código funciona, mas está de uma forma bem diferente da mostrada na correção do exercício que usa uma combinação de arrays e include. A minha dúvida é, há alguma prioridade em relação aos comandos que devo usar quando estiver refatorando códigos, por exemplo, devo dar prioridade a utilizar do jeito que foi mostrado no vídeo? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MivlaM!

Eu recomendo que vc dê preferência a forma que foi mostrada na resolução, por um motivo simples: a forma com que eu resolvo um desafio contém princípios que serão intensificados nos desafios seguintes =)

Em JS, sempre que precisar lidar com um array, haverá um arsenal de métodos de array à sua disposição. Um deles certamente irá te deixar mais próximo da resolução do problema.

A desvantagem de resolver com o `switch` é que ele é mais verboso. Ou seja, muito código é escrito para fazer algo relativamente simples.

Quando gravei essa aula, eu dei a entender que a solução com o `includes` seria menos legível. Hoje, eu certamente não falaria o mesmo =)

Respondi a dúvida?

**Comment by MivlaM** [comment]
@Roger-Melo 

Entendi. Eu fiz a refatoração com o `switch `porque foi a primeira maneira que eu pensei para resolver o problema, mas também entendi a lógica que você usou para resolver no vídeo. Darei prioridade às correções então.

Agradeço pela explicação =)

**Comment by Roger-Melo** [comment]
Massa @MivlaM!

Num primeiro momento, o mais importante é fazer funcionar mesmo, assim como vc fez.

Depois de fazer funcionar, aí vc procura melhorar o código =)

No que precisar, é só abrir uma nova issue =)
