### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by vitorsmessias** [roger-melo-treinamentos/curso-de-js-roger-melo#2523]
[TESTANDO PADRÕES DE REGEX.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7727987/TESTANDO.PADROES.DE.REGEX.pdf)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @vitorsmessias, rumo à fluência! 🔥
