### ISSUE TITLE
Aplicação: [TO-DO LIST]

### ISSUE THREAD

**Issue by mcrodrigo** [roger-melo-treinamentos/curso-de-js-roger-melo#2524]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/mcrodrigo/to-do.git

### Maiores dificuldades durante a implementação

- Fazer o refactoring no Array para ocultar/exibir o todo
- Identificar o todo a ser removido. Em vez de usar a propriedade textContent do todo, utilizei o index que o todo tinha dentro do todos-container
- reduzir o código ao menor número de linhas possível mantendo a legibilidade

### Menores dificuldades durante a implementação

Capturar os valores passados nos inputs dos forms

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo! 

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Me avise quando fizer a mudança =)

Fico no aguardo.

**Comment by mcrodrigo** [comment]
Realmente não lembrava do e-mail. As alterações foram feitas
 

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações".
 
 
 
-----Original Message-----

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Fazer o refactoring no Array para ocultar/exibir o todo

Sim, essa funcionalidade pode ficar um pouquinho complexa. Mas ali em baixo, eu vou sugerir uma abordagem que pode simplificar esse código.

> ### Identificar o todo a ser removido. Em vez de usar a propriedade textContent do todo, utilizei o index que o todo tinha dentro do todos-container

É uma alternativa também. Conforme for avançando no treinamento, vc identificará outras possibilidades =)

> ### reduzir o código ao menor número de linhas possível mantendo a legibilidade

Na maioria das vezes, legibilidade e concisão são forças opostas. 

Nem sempre o código mais legível terá menos linhas e por vezes, um código muito conciso perderá legibilidade.

Com a prática, vai se tornando mais fácil fazer escolhas equilibradas, tanto em time como em projetos pessoais =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Sugestão de melhora de legibilidade

Um bom ponto para melhorar a legibilidade do código é nomear os callbacks dos eventos.

Olha só:

```javascript
// antes
inputSearchTodo.addEventListener('input', event => {
  // é preciso ler todo o código dentro da função para entender o que ela faz
})
```

```javascript
// depois

// ao ler o nome da função, o que ela faz fica explícito imediatamente
const searchTodo = event => {
  // ...
}

inputSearchTodo.addEventListener('input', searchTodo)
```

Percebe a diferença?

---

`removeTodo` e `addTodo` podem conter o código que está no callback anônimo do evento e, serem referenciadas como callback:

```javascript
// antes
const removeTodo = clickedElement => {
  // ...
}

todosContainer.addEventListener('click', event => {
  const clickedElement = event.target
  removeTodo(clickedElement)
})
```

```javascript
// depois
const removeTodo = event => {
  const clickedElement = event.target
  // ...
}

todosContainer.addEventListener('click', removeTodo)
```

```javascript
// antes
const addTodo = (value, index) => {
  value = value.slice(0, 25)
  // ...
}

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()
  const index = todosContainer.children.length

  addTodo(inputValue, index)
  event.target.reset()
})
```

```javascript
// depois
const addTodo = event => {
  event.preventDefault()
  const value = event.target.add.value.trim()
  const index = todosContainer.children.length

  // ...
}

formAddTodo.addEventListener('submit', addTodo)
```

Aí vc pode agrupar os listeners de eventos no final do código.

Isso vai organizar seu código, deixando declarações de consts/let agrupadas no topo, declarações de funções agrupadas no meio e, invocações de listeners de eventos agrupados no final:

```javascript
const addTodo = event => {
  // ...
}

const removeTodo = event => {
  // ...
}

const searchTodo = event => {
  // ...
}

formAddTodo.addEventListener('submit', addTodo)
todosContainer.addEventListener('click', removeTodo)
inputSearchTodo.addEventListener('input', searchTodo)
```

---

## Remoção de caracteres após envio do to-do

Quando os caracteres do to-do são removidos após o envio, isso pode dar ao usuário a sensação de que os dados que ele inseriu não foram computados corretamente pela sua aplicação.

Deixar o usuário escrever um parágrafo e, ao adicionar o parágrafo ele não ser totalmente exibido pode causar uma sensação de frustração, pois por alguns segundos, o usuário realmente acreditou que cada palavra que ele inseriu seria considerada como texto de um to-do.

Para evitar isso, vc pode apenas limitar a quantidade máxima de caracteres que podem ser inseridos no input:

```html
<input maxlength="25" />
```

Além do benefício do ponto de vista de usabilidade, vc remove uma mutação em seu código (`value = value.slice(0, 25)`) =)

---

## Momento de criação de uma const

Na `removeTodo`, a const `todoItemDataset` está sendo declarada em um momento que ainda não é certo que ela será usada. Isso impacta em praticamente nada na performance. 

Mas se quiser assegurar que a const só será criada quando realmente for usada, vc pode fazer algo assim:

```javascript
// antes
const removeTodo = event => {
  const clickedElement = event.target
  const todoItemDataset = `[data-todo-id="${clickedElement.dataset.deleteId}"]`

  if (clickedElement.dataset.deleteId) {
    todosContainer.querySelector(todoItemDataset).remove()
  }
}
```

```javascript
// depois
const removeTodo = event => {
  const trashWasClicked = event.target.dataset.deleteId

  if (trashWasClicked) {
    const todo = document.querySelector(`[data-todo-id="${trashWasClicked}"]`)
    todo.remove()
  }
}
```

---

## Refactoring da função `searchToDo`

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean 
  que indica se o to-do deve ficar visível */

  // const manipulateClass = (element, classToAdd, classToRemove) => {
  // ...
}
```

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação e ver o que faz mais sentido para você.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by mcrodrigo** [comment]
Sim. As observações fizeram todo sentido.


...

Em sábado, dezembro 18, 2021, 6:48 PM, Roger Melo ***@***.***> escreveu:




Olá @mcrodrigo!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)


Fazer o refactoring no Array para ocultar/exibir o todo


Sim, essa funcionalidade pode ficar um pouquinho complexa. Mas ali em baixo, eu vou sugerir uma abordagem que pode simplificar esse código.


Identificar o todo a ser removido. Em vez de usar a propriedade textContent do todo, utilizei o index que o todo tinha dentro do todos-container


É uma alternativa também. Conforme for avançando no treinamento, vc identificará outras possibilidades =)


reduzir o código ao menor número de linhas possível mantendo a legibilidade


Na maioria das vezes, legibilidade e concisão são forças opostas.

Nem sempre o código mais legível terá menos linhas e por vezes, um código muito conciso perderá legibilidade.

Com a prática, vai se tornando mais fácil fazer escolhas equilibradas, tanto em time como em projetos pessoais =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

Sugestão de melhora de legibilidade

Um bom ponto para melhorar a legibilidade do código é nomear os callbacks dos eventos.

Olha só:
// antes
inputSearchTodo.addEventListener('input', event => {
  // é preciso ler todo o código dentro da função para entender o que ela faz
})// depois

// ao ler o nome da função, o que ela faz fica explícito imediatamente
const searchTodo = event => {
  // ...
}

inputSearchTodo.addEventListener('input', searchTodo)
Percebe a diferença?

removeTodo e addTodo podem conter o código que está no callback anônimo do evento e, serem referenciadas como callback:
// antes
const removeTodo = clickedElement => {
  // ...
}

todosContainer.addEventListener('click', event => {
  const clickedElement = event.target
  removeTodo(clickedElement)
})// depois
const removeTodo = event => {
  const clickedElement = event.target
  // ...
}

todosContainer.addEventListener('click', removeTodo)// antes
const addTodo = (value, index) => {
  value = value.slice(0, 25)
  // ...
}

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()
  const index = todosContainer.children.length

  addTodo(inputValue, index)
  event.target.reset()
})// depois
const addTodo = event => {
  event.preventDefault()
  const value = event.target.add.value.trim()
  const index = todosContainer.children.length

  // ...
}

formAddTodo.addEventListener('submit', addTodo)
Aí vc pode agrupar os listeners de eventos no final do código.

Isso vai organizar seu código, deixando declarações de consts/let agrupadas no topo, declarações de funções agrupadas no meio e, invocações de listeners de eventos agrupados no final:
const addTodo = event => {
  // ...
}

const removeTodo = event => {
  // ...
}

const searchTodo = event => {
  // ...
}

formAddTodo.addEventListener('submit', addTodo)
todosContainer.addEventListener('click', removeTodo)
inputSearchTodo.addEventListener('input', searchTodo)
Remoção de caracteres após envio do to-do

Quando os caracteres do to-do são removidos após o envio, isso pode dar ao usuário a sensação de que os dados que ele inseriu não foram computados corretamente pela sua aplicação.

Deixar o usuário escrever um parágrafo e, ao adicionar o parágrafo ele não ser totalmente exibido pode causar uma sensação de frustração, pois por alguns segundos, o usuário realmente acreditou que cada palavra que ele inseriu seria considerada como texto de um to-do.

Para evitar isso, vc pode apenas limitar a quantidade máxima de caracteres que podem ser inseridos no input:
<input maxlength="25" />
Além do benefício do ponto de vista de usabilidade, vc remove uma mutação em seu código (value = value.slice(0, 25)) =)

Momento de criação de uma const

Na removeTodo, a const todoItemDataset está sendo declarada em um momento que ainda não é certo que ela será usada. Isso impacta em praticamente nada na performance.

Mas se quiser assegurar que a const só será criada quando realmente for usada, vc pode fazer algo assim:
// antes
const removeTodo = event => {
  const clickedElement = event.target
  const todoItemDataset = `[data-todo-id="${clickedElement.dataset.deleteId}"]`

  if (clickedElement.dataset.deleteId) {
    todosContainer.querySelector(todoItemDataset).remove()
  }
}// depois
const removeTodo = event => {
  const trashWasClicked = event.target.dataset.deleteId

  if (trashWasClicked) {
    const todo = document.querySelector(`[data-todo-id="${trashWasClicked}"]`)
    todo.remove()
  }
}
Refactoring da função searchToDo

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean 
  que indica se o to-do deve ficar visível */

  // const manipulateClass = (element, classToAdd, classToRemove) => {
  // ...
}
Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função filterTodos que manipula as classes dos to-dos, considerando a propriedade shouldBeVisible:
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
Sacou a ideia?

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação e ver o que faz mais sentido para você.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
