### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2529]
São operadores que faz combinações de condições diferentes para gerar valores “_false_” ou “_true_”

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-c2676314-7fff-f7e5-5c15-221b1c58f98a">

A | B | A\|\|B | A&&B
-- | -- | -- | --
true | true | true | true
true | false | true | false
false | false | false | false
false | true | true | false

</div>

**Comment by Roger-Melo** [comment]
Boa @RodrigoLimaMota , rumo à fluência! 🔥
