### ISSUE TITLE
Métodos em classes

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2530]
### Etapa da aula

14

### Nome da aula

Métodos em classes - Aula 02-07

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1666028

### Descreva a dúvida

Oi de novo @Roger-Melo 

Na aula sobre métodos em classes você ensina que os métodos são criados fora do construtor. Para testar eu vi que também é possível criá-los dentro do construtor: 

```js
class User {
  constructor (name, email) {
    this.name = name
    this.email = email
    this.points = 0
    this.test = () => {
      console.log(this)
    }
  }

  login () {
    console.log(`${this.name} logou na aplicação!`)
    return this
  }
}
```
Porém eu vi que dessa forma ele não fica junto com os outros método dentro do prototype: 
![image](https://user-images.githubusercontent.com/31637175/146543224-40673307-8c24-4a19-a0bf-7261f5dc71e3.png)

Por que isso acontece? E qual a diferença de se crar os métodos dentro e fora do constructor?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior.

> ### Por que isso acontece? E qual a diferença de se crar os métodos dentro e fora do constructor?

O por que disso acontecer não tem muita importância. É só a forma como a linguagem funciona. 

Da mesma forma que ao declarar uma função tradicional vc precisa especificar a palavra-chave `function`, para que um método que vc cria dentro da classe seja reaproveitado em todos os objetos que ela cria (através do prototype), vc precisa declarar esse método fora do `constructor`.

Então respondendo a segunda pergunta, a diferença é: métodos criados dentro do `constructor` vão ser criados em cada objeto que a classe criar.

Isso significa que esses métodos serão **CONSTRUÍDOS** e mantidos em memória, um para cada objeto.

Exemplo:

```javascript
class User {
  constructor (name, email) {
    this.name = name
    this.email = email
    this.points = 0
    this.test = () => {
      console.log(this)
    }
  }

  login () {
    console.log(`${this.name} logou na aplicação!`)
    return this
  }
}

const user1 = new User('Roger', 'oi@rogermelo.com.br')
const user2 = new User('Roger2', 'oi@rogermelo2.com.br')

console.log(user1.test === user2.test) // false
```

No código acima, foram criados 2 métodos `test`, um para cada objeto que a função criou. Portanto, ao verificar se as duas funções ocupam o mesmo espaço em memória (lembrando que funções são objetos), `false` é retornado.

Do ponto de vista de performance, essa abordagem não é recomendada. Não faz sentido que todo objeto que a classe crie tenha uma instância do método criado só pra esse objeto (considerando que todos os métodos estão fazendo a mesma coisa).

---

Já os métodos criados fora do `constructor` são reaproveitados. Cada objeto que a classe criar terá acesso ao mesmo método. Ou seja, ao invés de criar um método pra cada objeto, um único método é criado e esse método é, através do prototype, acessível à todos os objetos que a classe criou.

Exemplo:

```javascript
class User {
  constructor (name, email) {
    this.name = name
    // ...
  }

  login () {
    console.log(`${this.name} logou na aplicação!`)
    return this
  }
}

const user1 = new User('Roger', 'oi@rogermelo.com.br')
const user2 = new User('Roger2', 'oi@rogermelo2.com.br')

console.log(user1.login === user2.login) // true
```

Ao verificar se o método `login` do objeto `user1` está na mesma posição em memória que o método `login` de `user2`, `true` é retornado.

Isso significa que os dois objetos estão usando um único método em memória. Em outras palavras, o método foi "herdado" nos dois objetos.

Sacou a ideia?

---

Dito tudo isso, eu não sei se em seu trabalho classes ainda são usadas... 

Mas definitivamente, é algo que vc deve aprender e evitar.

Classes são o pior da orientação à objetos. Usá-las em aplicações JavaScript Front-end, na maioria dos casos, é desnecessário. E isso é ótimo, pois elas são desnecessariamente complicadas =)

**Comment by Hamiltonspjunior** [comment]
Oi, @Roger-Melo 

Muito boa a resposta, deu pra entender muito bem. Não fazia ideia dessa diferença de ser criado um método diferente na memória para cada objeto quando ele está dentro do contrutor. 

Só mais uma pergunta por que agora fiquei curioso. Você mencionou agora no final: "Classes são o pior da orientação à objetos."

Você diz isso em relação as classes da orientação à objetos aplicados ao JavaScript ou classe num conceito geral?

Pergunto isso por que existem diversas linguagens orientadas à objetos a muitos anos por ai e elas utilizam classes. Como Java ou C# por exemplo.

**Comment by Roger-Melo** [comment]
Classes podem te tentar a fazer herança e, herança é a receita para implementar código acoplado.

Vc ainda verá aulas sobre isso no treinamento, fica ligado =)

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Beleza, @Roger-Melo 

Obrigado pela resposta. Pode fechar.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
