### ISSUE TITLE
Resumo da Aula 01-05 da etapa 03 Funções e métodos

### ISSUE THREAD

**Issue by kennedyDev454** [roger-melo-treinamentos/curso-de-js-roger-melo#2533]
// RETORNANDO VALORES DA FUNÇÃO

const double = function (number) {
  return number * 4; // a palavra return retorna o valor da função
};

const result = double(3);

const showResult = function (value) {
  return `o valor é ${value}`;
};

// console.log(showResult(result)) // aqui foi passado o resultado de uma  funçao para outra função

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @kennedyDev454 , rumo à fluência! 🔥
