### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#2534]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edcabralc/edcabralc-weather-app-cjrm

### Maiores dificuldades durante a implementação

Tive bastante dificuldade em fazer o refactoring do código. Principalmente colocar as funções por responsabilidade de execução.
Nomear variáveis mais precisamente.

### Menores dificuldades durante a implementação

Manipulação do DOM.

**Comment by Roger-Melo** [comment]
Olá @edcabralc.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by edcabralc** [comment]
Valeu, Roger!

**Comment by Roger-Melo** [comment]
Olá @edcabralc!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ### Tive bastante dificuldade em fazer o refactoring do código. Principalmente colocar as funções por responsabilidade de execução. Nomear variáveis mais precisamente.

Pelo seu código, não percebi dificuldade na separação de responsabilidades das funções. 

Se vc der uma olhada no tópico `Uma abordagem possível` [dessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2342#issuecomment-985200744), verá que fez basicamente o conceito que explico nela =)

Sobre os nomes de variáveis, também vou dar algumas sugestões logo abaixo.

Ah, o visual da aplicação ficou bem legal =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Omissão do bloco de um `if`

Cuidado ao omitir blocos de ifs. 

[Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos e colocou a segurança de dados em xeque por causa desse tipo de decisão.

---

## Ternário

Geralmente, o ideal é que um ternário não seja usado para executar efeito colateral. 

O ideal é usr o ternário para fazer algo com o valor que ele retorna. 

Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para executar a atribuição do src da imagem (em que o valor no qual a expressão `weatherCardImage.src = "..."` resulta não está sendo aproveitado), vc pode usar o ternário apenas para retornar a string que será aproveitada:

```javascript
// antes
IsDayTime
  ? (weatherCardImage.src = "images/src/day.svg")
  : (weatherCardImage.src = "images/src/night.svg");
```

```javascript
// depois
weatherCardImage.src = IsDayTime ? "images/src/day.svg" : "images/src/night.svg"
```

## Nomeação de callbacks de listeners de eventos

Um ponto importante para melhorar a legibilidade de um código é nomear os callbacks dos eventos.

É possível nomear o callback de `submit` do `formSearchCity` para `showCityWeather`:

Olha só:

```javascript
// antes
formSearchCity.addEventListener("submit", async (event) => {
  // é preciso ler todo o código dentro da função para entender o que ela faz
})
```

```javascript
// depois

// ao ler o nome da função, o que ela faz fica explícito imediatamente
const showCityWeather = event => {
  // ...
}

inputSearchTodo.addEventListener('input', showCityWeather)
```

Percebe a diferença?

---

## Nomeação de função

Se `getWeatherInfoAPI` for renomeada apenas como `getWeatherInfo`, ela continuará com o mesmo significado. Talvez, não seja necessário informar no nome da função que os dados que ela obtém são da API.

---

## Concisão de funções

Se vc quiser, `formatDayName` e `formatMonthName` podem ficar mais concisas. 

Exemplo:

```javascript
// antes
const formatDayName = (dayName) => {
  const days = [
    "Domingo",
    "Segunda",
    "Terça",
    "Quarta",
    "Quinta",
    "Sexta",
    "Sábado",
  ];
  return days[dayName];
};
```

```javascript
// depois
const formatDayName = (dayName) => (
  ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"]
)[dayName];
```

Ou, com um curto-circuito:

```javascript
// depois
const formatDayName = (dayName) => (
  ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"]
)[dayName] || "Domingo";
```

De qualquer forma, em aulas mais à frente, você verá como criar essa formatação de data escrevendo bem menos, através da `Intl` API:

```javascript
new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(date)
```

Em breve vc descobrirá como esse código funciona =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

PS: pq `weatherIcon` é uma `let`?

**Comment by edcabralc** [comment]
Boa, **@Roger-Melo** (GRANDE MESTRE)

Suas observações fazem total sentido, fiz as devidas correções e já subi para o repositório. 
Foi muito desafiador e gratificante desenvolver essa aplicação. 

> Geralmente, o ideal é que um ternário não seja usado para executar efeito colateral.

O conceito de efeito colateral vai ficando cada vez mais claro depois de algumas aulas.

> PS: pq `weatherIcon `é uma `let`?

Na revisão do código não percebi que tinha colocado como `let`

### Uma dúvida:

Percebi uma certa lentidão ao fazer a busca da cidade, isso se deve ao código em si ou na resposta da API?

**Comment by Roger-Melo** [comment]
> ### Percebi uma certa lentidão ao fazer a busca da cidade, isso se deve ao código em si ou na resposta da API?

Quanto tempo? 2 segundos?

@edcabralc

**Comment by edcabralc** [comment]
Não sei te dizer exatamente, como poderia medir esse tempo?

**Comment by Roger-Melo** [comment]
O "como" não importa muito, pode ativar um cronômetro no celular quando apertar o botão, ou algo do tipo..

O que eu quis dizer é que geralmente, como requests são operações assíncronas, é natural que eles levem um certo tempo para serem concluídos. 

Em etapas mais avançadas, vc encontrará uma aula onde falo sobre performance percebida, que é o que realmente importa antes de tentar otimizar milisegundos no código.

Até lá, recomendo que foque no treinamento sem se preocupar com isso =)

@edcabralc

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
