### ISSUE TITLE
Aplicação: To-Do List

### ISSUE THREAD

**Issue by andersoncsiqueira** [roger-melo-treinamentos/curso-de-js-roger-melo#2535]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/andersoncsiqueira/ToDoBrazilianSelection

### Maiores dificuldades durante a implementação

Memorizar cada etapa apresentada na aula, acabei não conseguindo lembrar de primeira o que fazer, mas depois de reassistir as aulas e tentar outras vezes consegui montar toda a aplicação. 

Organizar o código para deixa-lo o mais limpo possível e rafatorar quando necessário. 

Tive um pouco de dificuldade para entender como usar o DATA. 

### Menores dificuldades durante a implementação

O uso do addEventListener está ficando cada vez mais fácil, assim como os métodos de Array. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @andersoncsiqueira.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
@andersoncsiqueira, seu código ficou muito complexo e tá bem diferente do que foi mostrado nas aulas.

Sobre o atributo `data-*`, vc verá como ele funciona nas aulas seguintes.

Preciso que vc foque no que vou descrever nas linhas abaixo, pois vou documentar o passo a passo que fiz para deixar o código mais simples.

Essa será a sua análise. 

---

## Ocorrências do exato mesmo evento repetidas vezes

Há 3 ocorrências de `insertPlayer.addEventListener('submit', () => {...})` na aplicação, o que não faz sentido e traz bastante desorganização pro código.

E não só isso...

Uma dessas ocorrências está aninhada:

```javascript
insertPlayer.addEventListener('submit', event => {
  // ...
})

insertPlayer.addEventListener('submit', event => {
  // ...

  insertPlayer.addEventListener('submit', event => {
    // ...
  })
})
```

Outra ocorrência está invocando uma função `addPlayer` e, na declaração da função, um `event` que não foi inserido como parâmetro dela está sendo usado:

```javascript
const addPlayer = (inputValue) => {
  // ...
  event.target.reset()
}

insertPlayer.addEventListener('submit', event => {
  // ...
  addPlayer(inputValue)
})
```

Por que declarar o mesmo evento 3x? 

Em que aula vc viu isso ser mostrado?

Vc poderia simplesmente declarar esse evento uma única vez:

```javascript
insertPlayer.addEventListener('submit', event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    todosContainer.innerHTML += `
    <li class="li" data-todo="${inputValue}">
        <span> ${inputValue}</span>
        <i class="delete" data-trash="${inputValue}">x</i>
    </li>`
  }

  const playerNames = Array.from(todosContainer.children)
    .map(names => names.children[0].innerText.toLowerCase())

  for (i = 0; i < bestPlayers.length; i++) {
    if (bestPlayers[i].includes(playerNames[playerNames.length - 1])) {
      counter += 3
    } else if (playerNames[playerNames.length - 1].toLowerCase().includes('ribamar')) {
      counter -= 5
    }
  }

  if (playerNames.includes('neymar')) {
    neymar.classList.remove('hidden')
    neymar.classList.toggle('neymar')
  }

  winnsOdds.setAttribute('value', `${counter}`)
  odd.innerText = `${counter}`
  event.target.reset()
})
```

Depois de concentrar todo o código em uma única função de callback e assegurar que ele funciona como deveria, talvez seja o momento de pensar em como melhorar o código.

---

## Melhorando a legibilidade de um callback

O primeiro passo é nomear o callback do evento, isso começará a dar mais legibilidade ao código:

```javascript
// antes

insertPlayer.addEventListener('submit', event => {
  // é preciso ler todo o código dentro da função para entender o que ela faz
})
```

```javascript
// depois

// ao ler o nome da função, o que ela faz fica explícito imediatamente
const addPlayer = event => {
  // ...
}

insertPlayer.addEventListener('submit', addPlayer)
```

---

## Removendo a complexidade

Não é necessário executar um `for` loop com `if` e `else/if` para manipular o `counter`:

```javascript
const addPlayer = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.toLowerCase().trim()

  if (!inputValue.length) {
    return
  }

  if (inputValue === 'ribamar') {
    counter -= 5
  }

  if (bestPlayers.includes(inputValue)) {
    counter += 3
  }

  if (inputValue === 'neymar') {
    neymar.classList.remove('hidden')
    neymar.classList.toggle('neymar')
  }
  
  todosContainer.innerHTML += `
    <li class="li" data-todo="${inputValue}">
      <span> ${inputValue}</span>
      <i class="delete" data-trash="${inputValue}">x</i>
    </li>`
  
  winnsOdds.setAttribute('value', `${counter}`)
  odd.innerText = `${counter}`
  event.target.reset()
}
```

Percebe como está ficando mais simples ler e entender o código?

## Quebrando em partes

Como a maior parte desse código está relacionado a manipular `counter`, vc pode criar uma função específica para isso e invocá-la dentro de `addPlayer`:

```javascript
const updateCounter = inputValue => {
  if (inputValue === 'ribamar') {
    counter -= 5
  }

  if (bestPlayers.includes(inputValue)) {
    counter += 3
  }
  
  winnsOdds.setAttribute('value', `${counter}`)
  odd.innerText = `${counter}`
}

const addPlayer = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.toLowerCase().trim()

  if (!inputValue.length) {
    return
  }  

  if (inputValue === 'neymar') {
    neymar.classList.remove('hidden')
    neymar.classList.toggle('neymar')
  }
  
  todosContainer.innerHTML += `
    <li class="li" data-todo="${inputValue}">
      <span> ${inputValue}</span>
      <i class="delete" data-trash="${inputValue}">x</i>
    </li>`

  updateCounter(inputValue)
  event.target.reset()
}
```

Ainda ficou um if meio nada haver dentro da função. 

O nome da função é `addPlayer` e tem um if dentro dela que manipula a visibilidade de um elemento que não é o player adicionado.

Uma função `showNeymarImg`, pode ser criada, a const neymar pode ser criada apenas quando o input foi o nome do jogador, o toggle com a classe do nome do jogador não é necessário, e `showNeymarImg` pode ser invocada dentro da `addPlayer` ou da `updateCounter`:

```javascript
const showNeymarImg = inputValue => {
  if (inputValue === 'neymar') {
    const neymar = document.querySelector('#neymar')
    neymar.classList.remove('hidden')
  }
}

const updateCounter = inputValue => {
  if (inputValue === 'ribamar') {
    counter -= 5
  }

  if (bestPlayers.includes(inputValue)) {
    counter += 3
  }
  
  winnsOdds.setAttribute('value', `${counter}`)
  odd.innerText = `${counter}`
  showNeymarImg(inputValue)
}

const addPlayer = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.toLowerCase().trim()

  if (!inputValue.length) {
    return
  }
  
  todosContainer.innerHTML += `
    <li class="li" data-todo="${inputValue}">
      <span> ${inputValue}</span>
      <i class="delete" data-trash="${inputValue}">x</i>
    </li>`

  updateCounter(inputValue)
  event.target.reset()
}
```

## Refatoração de remoção e busca dos to-dos

Agora que a parte do código que cuida da adição do jogador está mais legível, os princípios a serem seguidos nas outras partes é o mesmo.

> ### O primeiro passo é nomear o callback do evento, isso começará a dar mais legibilidade ao código:

```javascript
// antes (addEventListener espalhados no meio do código)

todosContainer.addEventListener('click', event => {
  // ...
})

search.addEventListener('input', event => {
  // ...
})
```

```javascript
// depois
const removeTodo = event => {
  // ...
}

const handleTodoSearch = event => {
  // ...
}

const addPlayer = event => {
  // ...
}

insertPlayer.addEventListener('submit', addPlayer)
todosContainer.addEventListener('click', removeTodo)
search.addEventListener('input', handleTodoSearch)
```

Na `removeTodo`, `todo` não precisa ser criada antes de saber se o elemento clicado realmente foi a lixeira. `todo` só será usada se isso acontecer.

```javascript
const removeTodo = event => {
  // ...
  
  if (trashDataValue) {
    const todo = document.querySelector(`[data-todo='${clikedElement.dataset.trash}']`)
    // ...
  }
}
```

Quanto à `handleTodoSearch`, dá uma olhada no tópico `Refactoring da função searchToDo` [dessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2524#issuecomment-997289284). Lá eu mostro uma abordagem menos complexa para filtrar os to-dos.

---

## Usabilidade

Posso estar enganado, mas acho que vc criou um jogo onde mesmo se todos os jogadores do array `bestPlayers` forem inseridos, a pontuação não chega à 100%.

Tome cuidado com isso, vc pode frustrar o usuário e ele pode se sentir enganado caso abra o inspetor e confirme o que eu disse no parágrafo acima.

---

Como eu disse no começo da análise, seu código ficou bastante complexo.

E além de estar complexa, a aplicação criada não é bem um to-do. E nada de certo ou errado nisso, mas o fato é que talvez, se vc tivesse mais focado em fazer o básico bem feito, o código não teria a complexidade com que foi entregue.

Recomendo que na próxima aplicação, foque em fazer apenas o que é pedido.

Provavelmente, isso te dará mais chance de realmente enxergar o que precisa ser melhorado.

Depois de aprender a fazer o básico bem feito, aí sim talvez seja o momento de improvisar.

---

Nas aulas seguintes, você também verá outras formas de refatorar o código dessa aplicação.

As observações fizeram sentido?

**Comment by andersoncsiqueira** [comment]
>  seu código ficou muito complexo e tá bem diferente do que foi mostrado nas aulas.

Opa, mestre! 

Realmente ficou bem ruim, na verdade meio que me empolguei e acabei colocando coisas desnecessárias,  não parei para refatorar ele, apenas acabei e vi que funcionava, então enviei para ser avaliado. Para as próximas aplicações vou focar estritamente no que é pedido. 

> Ocorrências do exato mesmo evento repetidas vezes

Como tinham diferentes ações para acontecer, fui fazendo cada uma de forma separada e testando, a medida que funcionavam não pensei em reuni-las em um só evento. 

> Em que aula vc viu isso ser mostrado?

Não vi, erro meu.


> Percebe como está ficando mais simples ler e entender o código?

Saquei!! 

> Agora que a parte do código que cuida da adição do jogador está mais legível, os princípios a serem seguidos nas outras partes é o mesmo.

Ok

> insertPlayer.addEventListener('submit', addPlayer)
todosContainer.addEventListener('click', removeTodo)
search.addEventListener('input', handleTodoSearch)

Realmente fica muito mais fácil a leitura desta forma, como estava antes é de doer a vista e a mente para compreender o que o código faz, ou tenta fazer. 

> Nas aulas seguintes, você também verá outras formas de refatorar o código dessa aplicação.

As observações fizeram sentido?

Sim, fizeram todo sentido. Vou começar a refatorar agora mesmo. Obrigado!!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
