### ISSUE TITLE
Resumo da Aula 02/02 da etapa 04 Variável e Escopo de bloco

### ISSUE THREAD

**Issue by shazenn** [roger-melo-treinamentos/curso-de-js-roger-melo#2543]
[Variável e Escopo de bloco_   Aula 02_02 Etapa 04 (1).pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/7741339/Variavel.e.Escopo.de.bloco_.Aula.02_02.Etapa.04.1.pdf)

**Comment by Roger-Melo** [comment]
Excelente @shazenn , rumo à fluência! 🎯
