### ISSUE TITLE
Resumo da Aula While loop - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#255]
Um *while loop* faz a mesma coisa que um *for loop*: executar um pedaço de código repetidas vezes. A única diferença entre ambos é na forma em que são escritos.

```jsx
let i = 0

while (i < 5) {
	console.log(i)
	i++
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel. Continue seguindo o método. Rumo à fluência! 👊🏻
