### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2551]
A palavra chave “_return_” possibilita que uma função tenha um mecanismo de saída de dados, para que esses dados possam ser usados fora do escopo da função.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota , rumo à fluência! 🎯
