### ISSUE TITLE
Dúvida sobre um 'TypeError' quando retiro o parâmetro 'item' de map()

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2553]
### Etapa da aula

11

### Nome da aula

Async/Await Aula 05-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1338555

### Descreva a dúvida

   Durante trabalho de reforço para fixar melhor o assunto tratado nas aulas 'Async/Await' e 'Exercício 06' da Etapa 11;
Me deparei com o  'TypeError' da imagem abaixo, quando retirei o parâmetro 'item' de 'map()'. Por que aconteceu isso???

![image](https://user-images.githubusercontent.com/44072541/146798012-a270abfd-a615-4783-8c0a-f9223cba0d60.png)

```js
/*

>>> Exibir no Browser uma lista de users do link abaixo:
> 'https://jsonplaceholder.typicode.com/users'
*/
const div = document.querySelector("div")

const urlUsers = 'https://jsonplaceholder.typicode.com/users'

const usersBank = async () => {
  const users = await fetch(urlUsers)
  const objectResolved = await users.json()

  return objectResolved
}

const showDataUsers = async () => {
  const objectParser = await usersBank()

  const myUserList = objectParser
    .map((item, index) => {
      const {[index]:{username}, [index]:{website}} = objectParser
      
      return div.innerHTML += `<li>${username} - ${website}</li>`
    })
    
  return myUserList
}
console.log(showDataUsers())
console.log(usersBank())

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Antes de responder, deixa eu dar uma dica.

Ao inserir links das aulas nas issues, prefira postar o link da aula na plataforma, e não do vídeo do YouTube. O motivo é muito simples... Se essa aula for regravada, o vídeo do link que vc postou na issue não existirá mais. 

Já ajustei o link dessa issue =)

---

> ### Me deparei com o  'TypeError' da imagem abaixo, quando retirei o parâmetro 'item' de 'map()'. Por que aconteceu isso???

O parâmetro `item` não foi retirado. 

Com a mudança que vc fez, o parâmetro `item` foi renomeado pra `index`.

O `map` (e demais métodos como filter, reduce, forEach, etc) sempre recebem o item como primeiro argumento, index como segundo e array como terceiro (sendo que index e array são parâmetros opcionais). 

Porém, vc pode renomear qualquer parâmetro como quiser. Nomear o primeiro parâmetro como `blablabla` não muda o fato de que esse parâmetro receberá o item:

```javascript
const arr = [1, 2, 3].map(blablabla => blablabla)

console.log(arr) // [1, 2, 3]
```

Considerando que declarar o primeiro parâmetro é obrigatório mas, no exemplo que vc deu, vc não irá usá-lo, vc pode substituí-lo por um underscore (`_`):

```javascript
objectParser.map((_, index) => { /* ... */})
```

O underscore é uma convenção usada pra indicar que esse parâmetro deve ser ignorado.

Ficou mais claro?

**Comment by marcosyoggy** [comment]
Imagine a cena....quando eu li as duas primeiras linhas da sua explicação..eu dei um tapa na testa e pensei "....PQP...eu tinha esquecido disso...", Parei a leitura, abri o Vscode e coloquei um 'underline' no lugar do 'item' e voltei a ler o e-mail. Obrigado por mais essa.
```js
const div = document.querySelector("div")

const urlUsers = 'https://jsonplaceholder.typicode.com/users'

const usersBank = async () => {
  const users = await fetch(urlUsers)
  const objectResolved = await users.json()

  return objectResolved
}

const showDataUsers = async () => {
  const objectParser = await usersBank()

  const myUserList = objectParser
    .map((_, index) => {
      const {[index]:{username}, [index]:{website}} = objectParser
      
      return div.innerHTML += `<li>${username} - ${website}</li>`
    })
    
  return myUserList
}
showDataUsers()


```

**Comment by Roger-Melo** [comment]
Isso mesmo =)

No que precisar, é só abrir uma nova issue =)
