### ISSUE TITLE
Aplicação: Quiz 

### ISSUE THREAD

**Issue by kennedyDev454** [roger-melo-treinamentos/curso-de-js-roger-melo#2554]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Maiores dificuldades durante a implementação

Foi um pouco de logica mas depois consegui entender e fazer de outra forma mas ultilizando os conceitos das aulas.

### Menores dificuldades durante a implementação

fazer a animção do score

**Comment by Roger-Melo** [comment]
Olá @kennedyDev454.

Faltou colocar na issue o link do repositório ou pasta do drive da a aplicação =)

**Comment by kennedyDev454** [comment]
Olá Roger estou tentando subir obséquio mas não estou conseguindo vou
estudar pra ver como faz e envio

Em seg., 20 de dez. de 2021 às 12:47, Roger Melo ***@***.***>
escreveu:

**Comment by kennedyDev454** [comment]
Desculpa foi uma palavra errada rsrsrs estou tentando subir mas não
consegui vou estudar para ver como faz. Desde já agradeço

Em seg., 20 de dez. de 2021 às 12:57, Kennedy Costa <
***@***.***> escreveu:

**Comment by Roger-Melo** [comment]
Vi que abriu outra issue e enviou, vou fechar essa =)
