### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by kennedyDev454** [roger-melo-treinamentos/curso-de-js-roger-melo#2558]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://1drv.ms/u/s!AtGn8-3ofI13i174GogaC_s6WhWq?e=tMX9fe

### Maiores dificuldades durante a implementação

Foi um pouco da lógica de comparar as respostas mas depois entendi mehor.

### Menores dificuldades durante a implementação

fazer o moda e animar os números

**Comment by Roger-Melo** [comment]
Olá @kennedyDev454.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @kennedyDev454!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Foi um pouco da lógica de comparar as respostas mas depois entendi mehor.

Vou falar sobre isso mais abaixo.

Mas antes da análise, preciso te dar uma dica.

A solução de exibição dos pontos que vc implementou está idêntica a que mostrei nas aulas posteriores ao [aviso pedindo para enviar o quiz](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2829070). 

A aplicação deve ser enviada no momento em que vc ler o aviso pedindo que ela seja enviada. 

O momento de enviar as aplicações também está descrito no email `[Alunos CJRM] Análise de aplicações` enviado em 30/10. Se um próximo envio de aplicação acontecer fora do momento orientado, infelizmente sua aplicação não poderá ser analisada devido a falta de cumprimento dos requisitos para o envio.

O código da sua aplicação contém muitos ajustes, então preciso que vc foque e realmente execute o código do passo a passo que vou descrever nas linhas abaixo.

Essa será a sua análise.

---

## Usabilidade

Ao clicar em uma alternativa, o usuário precisa posicionar o mouse e clicar exatamente no input type radio. Isso pode causar desconforto, pois o input é muito pequeno.

Por isso, eu preferi mostrar na aula como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

---

O botão é desativado aós o primeiro envio do quiz, isso impossibilita que o usuário mude as alternativas e tente novamente (exceto se recarregar a página). Por que vc tomou a decisão de desativar o botão?

---

## Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Código legível dispensa comentários.

---

## `modal.addEventListener(...)`

Não há motivo para `modal.addEventListener(...)` estar dentro da função `show`.

Retire todo esse listener de evento de dentro da `show` e vc verá que o código continua funcionando normalmente.

---

## Fluxo de declaração e invocação de funções

Prefira declarar uma função antes de sua invocação. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo).

`show` e `correctAnswers` podem ser reposicionadas no código com esse ajuste.

## Nomeação de callbacks de listeners de eventos

Um ponto importante para melhorar a legibilidade de um código é nomear os callbacks dos eventos.

Olha só:

```javascript
// antes
form.addEventListener("submit", (event) => {
  // é preciso ler todo o código dentro da função para entender o que ela faz
})
```

```javascript
// depois

// ao ler o nome da função, o que ela faz fica explícito imediatamente
const showScore = (event) => {
  // ...
}

form.addEventListener("submit", showScore)
```

Percebe a diferença?

Isso também abre a possibilidade de vc agrupar os `addEventListeners` na parte inferior do arquivo, o que traz mais organização ao código:

```javascript
const showScore = (event) => {
  // ...
}

const closeModal = (event) => {
  // ...
}

modal.addEventListener("click", closeModal)
form.addEventListener("submit", showScore)
```

No código acima, `show` foi nomeada como `showScore` para que o nome ficasse mais específico.

---

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Já que a função `correctAnswers` retorna o score, ela pode ser nomeada como `getScore` (verbo).

`respost`, `correctAnswers` e `correctQuestions` estão se referindo à mesma coisa com nomes diferentes. Os três se referem à respostas mas um chama de "respost", outro de "answers" e outro de "questions". Se isso for padronizado, o código fica mais coerente. 

`respost` tem várias respostas, então precisa estar no plural. `answers` é um nome mais adequado. `correctQuestions` pode ser renomeado para `correctAnswers`

```javascript
// antes
const correctQuestions = [/* ... */]

const respost = [/* ... */]

show(getScore(respost))
```

```javascript
// depois
const correctAnswers = [/* ... */]

const answers = [/* ... */]

show(getScore(answers))
```

Não faz sentido nomear uma const como `elements` se ela armazena classes CSS: 

```javascript
// antes
const elements = ["close", "content", "modal active"]
```

```javascript
// depois
const CSSClasses = ["close", "content", "modal active"]
```

`clicked` é um nome vago, é possível especificar que a const armazena o elemento que foi clicado:

```javascript
// antes
const clicked = event.target.className
```

```javascript
// depois
const clickedElement = event.target.className
```

O parâmetro do callback da invocação de um método de array fica mais coerente se for nomeado como singular de itens do array no qual o método foi encadeado:

```javascript
// antes
CSSClasses.some((item) => item == clickedElement)
```

```javascript
// depois
CSSClasses.some((CSSClass) => CSSClass == clickedElement)
```

---

## Comparação não-estrita

No código postado, foi usado `==` ao invés de `===`. 

O recomendado é que vc fuja de operadores de comparação não-estrita e eu expliquei por que [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751262).

---

## Outros ajustes de nomenclatura

`getScore` recebe um array de respostas por parâmetro. 

Faz mais sentido que esse parâmetro tenha o mesmo nome do argumento que a função recebeu (e isso também impacta no nome do parâmetro do callback do `forEach`):

```javascript
// antes
const getScore = (value) => {
  value.forEach((element, index) => {
    if (element == correctAnswers[index]) {
      score += 25
    }
  })

  return score
}
```

```javascript
// depois
const getScore = (answers) => {
  answers.forEach((answer, index) => {
    if (answer == correctAnswers[index]) {
      score += 25
    }
  })

  return score
}
```

---

## Condicionais mais legíveis

Uma condição extensa de um if pode deixar o código mais legível se for armazenada em uma const:

```javascript
// antes
if (CSSClasses.some((CSSClass) => CSSClass === clickedElement)) {
  modal.classList.remove("active")
}
```

```javascript
// depois
if (shouldHideModal) {
  modal.classList.remove("active")
}
```

---

## Testes de uso da aplicação

Vc testou o código da sua aplicação enviando nenhuma resposta correta?

Ao fazer isso, vc verá que a contagem de pontos não para.

Há formas mais simples de inserir o texto na textContent, animar a pontuação e, de quebra, consertar essa lógica:

```javascript
// antes
function show(value) {
  modal.classList.add("active");
  timer = setInterval(() => {
    counter++;
    if (value == counter) {
      clearInterval(timer);
    }
    if (value >= 50 && value <= 75) {
      h2.textContent = `Parabens você acertou ${counter}%`;
    } else if (value < 50) {
      h2.textContent = `Você precisa estudar mais você acertou ${counter}%`;
    } else {
      h2.textContent = `Excelente você gabaritou com ${counter}%`;
    }
  }, 50);

  // ...
}
```

```javascript
// depois
const getScoreMessage = score => ({
  50: `Parabens você acertou <span class="counter"></span>%`,
  75: `Parabens você acertou <span class="counter"></span>%`,
  100: `Excelente você gabaritou com <span class="counter"></span>%`
})[score] || `Você precisa estudar mais você acertou <span class="counter"></span>%`

const animateScore = score => {
  const counterSpan = document.querySelector('.counter')

  timer = setInterval(() => {
    if (score === counter) {
      clearInterval(timer)
    }
    
    counterSpan.textContent = counter++
  }, 50)
}

const showScore = (event) => {
  event.preventDefault() 
  modal.classList.add("active")
  h2.innerHTML = getScoreMessage(score)

  const answers = [
    form.question1.value,
    form.question2.value,
    form.question3.value,
    form.question4.value,
  ]

  animateScore(getScore(answers))
}
```

Perceba que agora, cada função tem uma responsabilidade única. 

Observe também que ao invés de inserir todo o texto do h2 a cada execução do callback do setInterval, apenas o span tem o valor modificado (animado). 

Se vc quiser, esse template string HTML pode ser substituído, por exemplo, por uma manipulação de visibilidade de elementos HTML que já estejam no index.html. Mas o código acima já te dá uma boa direção de como separar mais as responsabilidades e não deixar toda essa parte de animação e inserção de texto dentro de apenas uma função com vários if/else.

Para não deixar o CSS quebrar, vc precisará substituir  `.content span{...}` por `.content .close{...}`.

`h2` e `correctAnswers` também podem ser declarados apenas dentro das funções onde são usadas.

---

## Declarações de variáveis em escopo global

`timer` e `counter` são usadas apenas dentro de `animateScore`, então elas não precisam ser declaradas em escopo global:

```javascript
// antes
let timer
let counter = 0

// ...

const animateScore = score => {
  // ...
  timer = setInterval(() => {
    // ...
  }, 50)
}
```

```javascript
// depois

const animateScore = score => {
  let timer
  let counter = 0
  const counterSpan = document.querySelector('.counter')

  timer = setInterval(() => {
    if (score === counter) {
      clearInterval(timer)
    }
    // ...
  }, 50)
}
```

---

## Código refatorado

Com os ajustes acima, o código ficou assim:

```javascript
const form = document.querySelector("form")
const modal = document.querySelector(".modal")

let score = 0

const getScoreMessage = score => ({
  50: `Parabens você acertou <span class="counter"></span>%`,
  75: `Parabens você acertou <span class="counter"></span>%`,
  100: `Excelente você gabaritou com <span class="counter"></span>%`
})[score] || `Você precisa estudar mais você acertou <span class="counter"></span>%`

const animateScore = score => {
  let timer
  let counter = 0
  const counterSpan = document.querySelector('.counter')

  timer = setInterval(() => {
    if (score === counter) {
      clearInterval(timer)
    }
    
    counterSpan.textContent = counter++
  }, 50)
}

const getScore = (answers) => {
  const correctAnswers = ["A", "A", "C", "B"]
  
  answers.forEach((answer, index) => {
    if (answer === correctAnswers[index]) {
      score += 25
    }
  })

  return score
}

const showScore = (event) => {
  event.preventDefault() 
  modal.classList.add("active")
  
  const h2 = document.querySelector("h2")
  h2.innerHTML = getScoreMessage(score)

  const answers = [
    form.question1.value,
    form.question2.value,
    form.question3.value,
    form.question4.value,
  ]

  animateScore(getScore(answers))
}

const closeModal = (event) => {
  const clickedElement = event.target.className
  const CSSClasses = ["close", "content", "modal active"]
  const shouldHideModal = CSSClasses.some((CSSClass) => CSSClass === clickedElement)

  if (shouldHideModal) {
    modal.classList.remove("active")
  }

  form.lastElementChild.style.pointerEvents = "none"
  form.lastElementChild.style.opacity = 0.7
}

modal.addEventListener("click", closeModal)
form.addEventListener("submit", showScore)

```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço.

As observações fizeram sentido?

**Comment by kennedyDev454** [comment]
Obrigado Roger agora vi e clareou as ideias aqui , vou melhorar o código e
os nomes também ,desde já agradeço os conselhos.


Em qui., 23 de dez. de 2021 às 22:55, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
