### ISSUE TITLE
Duvida sobre a ultima refatoração

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2560]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula passada Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/924879

### Descreva a dúvida

Boa noite Professor. 
minha dúvida é sobre a função criada clearInput() que você fez no minuto 18:52 dessa aula.
```js
const form = document.querySelector('form')

const clearInput = () => {
  input.value = ''
  input.focus()
}

const logMessage = message => {
  console.log(message)
  clearInput()
}

const showValue = event => {
  event.preventDefault()
  // const formRegex = /.{7,}/
  const input = event.target.input
  const formRegex = /^[a-zA-Z0-9]{7,11}$/
  const formIsMatch = formRegex.test(input.value)

  if (formIsMatch) {
    logMessage('O valor inserido no input é válido =)')
    return
  } 
  logMessage('Valor inválido =(');
}


form.addEventListener('submit', showValue)
```
como o _input.value_ da função _clearInput()_ recebe algum valor se nada foi passado para ele por parâmetro? 
Antes de ver  a resolução, eu tinha feito desse jeito, olhe que aonde eu chamo a função eu passei como parâmetro a minha variável "enteredValue", assim funcionava certinho.
```js
const form = document.querySelector('form')

const clearInput = item => {
  item.value = ''
  item.focus()
}

const logMessage = message => {
  console.log(message)
}

const showValue = event => {
  event.preventDefault()
  // const formRegex = /.{7,}/
  const formRegex = /^[a-zA-Z0-9]{7,11}$/
  const enteredValue = event.target.input
  const formIsMatch = formRegex.test(enteredValue.value)

  if (formIsMatch) {
    logMessage('O valor inserido no input é válido =)')
    clearInput(enteredValue)
    return
  } 
  logMessage('Valor inválido =(');
  clearInput(enteredValue)
}


form.addEventListener('submit', showValue)
```
o nome da variável era diferente e se eu fizesse igual você, sem passar nada como argumento, desse modo aqui.
```js
const clearInput = () => {
  enteredValue.value = ''
  enteredValue.focus()
}
```
funcionava mas logo em seguida dava o erro da foto
![Captura de tela 2021-12-21 012136](https://user-images.githubusercontent.com/92007775/146870665-c711c2c6-b3ac-49c5-8e41-3578d483b5d2.png)

Eu percebi que só de usar a palavra input já resolveria meu problema, mas não entendi o porque de resolver.
```js
const clearInput = () => {
  input.value = ''
  input.focus()
}

const logMessage = message => {
  console.log(message)
  clearInput()
}

const showValue = event => {
  event.preventDefault()
  // const formRegex = /.{7,}/
  const formRegex = /^[a-zA-Z0-9]{7,11}$/
  const enteredValue = event.target.input
  const formIsMatch = formRegex.test(enteredValue.value)

  if (formIsMatch) {
    logMessage('O valor inserido no input é válido =)')
    return
  } 
  logMessage('Valor inválido =(');
}


form.addEventListener('submit', showValue)
```
Espero ter sido claro. Muito obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @Jonatan1103!

Respondi a essa dúvida [nesta issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/10).

Se depois de ver essa resposta ainda restar alguma dúvida, é só dar o toque que te ajudo a entender, combinado? =)

**Comment by Jonatan1103** [comment]
Perfeito professor, entendi tranquilo, na aula Validação básica de formulários - Aula 02-02 da etapa 06. 
coloquei em pratica para fixar. 
```js
const clear = () => {
  username.value = ''
  username.focus()
}

const messageFeedback = message => {
  feedback.textContent = message
  clear()
}


const validationInput = event => {
  event.preventDefault()

  const username = event.target.username.value
  const usernameRegex = /^[a-zA-Z]{6,12}$/
  const isAValidUsername = usernameRegex.test(username)

  if (isAValidUsername) {
    messageFeedback('Nome válido =)')
    return
  }
  messageFeedback('Username deve conter apenas letras e 6 a 12 caracteres')

}

form.addEventListener('submit', validationInput)
```
