### ISSUE TITLE
Dúvida sobre o entendimento de uma mensagem de erro

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2561]
### Etapa da aula

11

### Nome da aula

Async/Await Aula 05-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1338555

### Descreva a dúvida

     Na Issue #2553 me deparei com uma mensagem de erro, que o final se mostrou ser uma questão básica, ou seja, de um
assunto já tratado e que não deveria causar muitos problemas; Após a resolução da questão, percebi que uma simples orientação sobre o entendimento de mensagens de erro ajudaria na resolução do problema de forma mais rápida e simples. Não vou me lembrar da questão, mas no início do curso, alguns erros que aconteceram eu resolvi entendendo o que a mensagem de erro apontava. Uma abordagem mais específica sobre leitura e entendimento de mensagens de erro, num contexto geral, seria válido? Um abraço e obrigado pela ajuda. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### Na Issue #2553 me deparei com uma mensagem de erro, que o final se mostrou ser uma questão básica, ou seja, de um assunto já tratado e que não deveria causar muitos problemas;

Ninguém tropeça em montanhas =)

É natural tropeçar em pequenas pedras, pequenos detalhes.

No caso que vc citou, sua expectativa era que o primeiro parâmetro do map recebesse um valor, quando na verdade, ele recebeu outro.

Isso poderia ser evitado com um simples `console.log(meuParametro)` abaixo da declaração do parâmetro.

Não sei se chegou a perceber, mas principalmente nas etapas iniciais do treinamento, eu uso o console.log praticamente a cada linha que escrevo, para mostrar o valor que uma determinada expressão / parâmetro / variável está armazenando. 

Eu não faço isso só por motivos didáticos. 

Não assuma que suas variáveis estão recebendo os valores que vc espera. 

**Sempre use console.log para checar suas variáveis**.

Só essa prática já traz bastante clareza de como o código realmente está funcionando e evita que vc seja pego de surpresa.

[Aqui](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong) tem um guia com sugestões de como debugar um código JS.

Vou anotar a sugestão de criar uma aula voltada para debugging, mas no momento, meu foco está em terminar de entregar o que está previsto no plano de aulas.

E claro, se rolar alguma dúvida, pode abrir uma issue que te ajudo =)

@marcosyoggy

**Comment by marcosyoggy** [comment]
Obrigado pela atenção e dica... até a próxima.

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
