### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2571]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/carlosdevjs/To-do-List---CJRM.git

### Maiores dificuldades durante a implementação

Em implementar o atributo data, com muito custo eu cheguei a realizar a tarefa de deletar a 'li', mais depois q adicionava uma nova 'li', não funcionava mais. 
Varias tentativas e erros e não consegui =(, por isso estou enviando o uso do dataset incompleto.
Realizei a refatoração mais somente com o tempo ficarei mais apto a realizar com exatidão.
Evitar que incluísse uma lista sem valores.

### Menores dificuldades durante a implementação

realizar as manipulações do DOM, antes eu não conseguia.
refatoração dos eventos.

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Em implementar o atributo data, com muito custo eu cheguei a realizar a tarefa de deletar a 'li', mais depois q adicionava uma nova 'li', não funcionava mais. Varias tentativas e erros e não consegui =(, por isso estou enviando o uso do dataset incompleto.

Tranquilo. O desafio era realmente fazer quebrar a cabeça pesquisando sobre `data-*` e `dataset`. Nas próximas aulas você verá como eles funcionam

Tá indo no caminho certo com o `event.target.dataset.trash` =)

> ### Realizei a refatoração mais somente com o tempo ficarei mais apto a realizar com exatidão.

Com a prática e o tempo o feeling para refatoração vai ficando mais apurado.

E não existe exatidão em refactoring.

Existem algumas técnicas, alguns padrões, alguns princípios, alguns consensos, mas no fim das contas, uma forma de refatoração que faz sentido em um time pode não fazer em outro. 

Muito de um refactoring depende do ambiente e no que as pessoas daquele ambiente acreditam.

> ### Evitar que incluísse uma lista sem valores.

Vou falar sobre isso mais abaixo.

Mas sua evolução é perceptível. Suas aplicações têm cada vez menos ajustes complexos =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Nomes dos callbacks dos listeners de eventos

Os nomes dos callbacks que adicionam, deletam ou removem to-dos podem ficar mais simples e, mesmo assim continuarem descrevendo o que a função faz:

- `insertContentInTodoList` => `addTodo`
- `deleteLiTodoList` => `deleteTodo`
- `searchContentTodoList` => `searchTodo`

À partir daqui, no decorrer da análise vou considerar que esses nomes foram refatorados e me referir à essas funções através dos novos nomes, ok?

---

## Erro lançado ao adicionar to-do "vazio"

Ao pressionar `enter` sem inserir valor no input de adicionar to-dos, um `Uncaught TypeError: inputValue.reset is not a function` é lançado. 

Isso aconteceu pq `inputValue` está armazenando uma string e, string não tem método `reset` disponível para ser usado. Quem tem método `reset` é o `formAddTodo`. 

Lembre-se: reset é um método que restaura valores padrão dos elementos de um form.

E o valor padrão de elementos de form (inputs) é string vazia.

Como dentro da função `addTodo` existe uma invocação de `event.target.reset()` e como `event.target` resulta no form de adição de to-dos, a limpeza do input do form já está sendo feita:

```javascript
const addTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue === '') {
    inputValue.reset()
  }

  // ...
  // 👇🏻 limpa o form
  event.target.reset()
}
```

O que vc pode fazer dentro do if é inserir um return. 

Assim, se nada foi inserido no input no momento da adição do to-do, o código abaixo do return não é executado desnecessariamente:

```javascript
const addTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue === '') {
    return
  }

  todosContainer.innerHTML += `
   <li class="list-group-item d-flex justify-content-between align-items-center" data-list="delete">
     <span>${inputValue}</span>
     <i class="far fa-trash-alt delete" data-trash="off-line"></i>
   </li>`

  event.target.reset()
}
```

---

## `deleteTodo`

Dentro da `deleteTodo`, a const `clickedElement` pode ter um nome que indica se o elemento clicado foi a lixeira. 

Ela pode se chamar, por exemplo, `trashWasClicked`:

```javascript
const deleteTodo = event => {
  const trashWasClicked = event.target.dataset.trash

  if (trashWasClicked) {
    event.target.parentElement.remove()
  }
}
```

---

## Refactoring da função `searchToDo`

O código de filtragem dos to-dos tende a ficar complexo, mas há uma forma mais simples de fazer essa filtragem.

Essa forma ainda não foi mostrada nas aulas. 

Por enquanto, mostro apenas para quem envia a aplicação para a análise.

Mas o fato é o seguinte...

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean 
  que indica se o to-do deve ficar visível */

  // const showTodosList = (arr, met1, className1, className2) => {
  // ...
}
```

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. 

O que sugeri é apenas uma lapidação de um código que já funciona =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação e ver o que faz mais sentido para você.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by carlosdevjs** [comment]
Como fez sentido, essas mudanças vão melhorando a minha forma lógica de ver as chamadas das funções, essa de fazer com que seja criado um array de objeto foi muito legal. Obrigado pelo feedback.
