### ISSUE TITLE
Dúvida sobre verificar uma condição

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2572]
### Etapa da aula

12

### Nome da aula

Exercícios da aula 02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1451629

### Descreva a dúvida

Eu estava refatorando o if/else da aplicação e tentei criar uma função que verifica se a IsDayTime é true ou false e executa algo
a partir disso. Eu não estou entendendo o por quê da logTimeIcon não funcionar corretamente e a logTimeIcon2 funcionar.

A logTImeIcon executa apenas a condição correspondente ao false, sendo que a IsDayTime recebe true(caso o usuário procure por São Paulo, por exemplo). 

```js

const logTimeIcon = IsDayTime => ({
  true: timeImg.src = `./src/day.svg`,
  false: timeImg.src = `./src/night.svg`,
}) [IsDayTime] || 'Dados não encontrados'

const logTimeIcon2 = IsDayTime => {
  if (IsDayTime) {
    timeImg.src = `./src/day.svg`
    return
  }

  timeImg.src = `./src/night.svg`
}

cityForm.addEventListener('submit', async event => {
  event.preventDefault()
  
  const inputValue = event.target.city.value
  const [{ Key, LocalizedName }] = await getCityData(inputValue)
  const [{ WeatherText, Temperature, IsDayTime, WeatherIcon}] = 
    await getCityWeather(Key)
  const timeIcon = `<img src="./src/icons/${WeatherIcon}.svg"/>`
  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }

  logTimeIcon(IsDayTime)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Antes de responder, deixa eu dar uma dica: não insira espaço em branco antes de `[IsDayTime]`. Seria o equivalente a especificar `obj [prop]`. Fica mal formatado, prejudica a legibilidade e vai contra a convenção natural de escrever um acesso à propriedade de forma dinâmica.

---

Isolando o código de forma independente de valores externos, basicamente ficaria assim:

```javascript
const timeImg = document.createElement('img')

const x = IsDayTime => ({
  true: timeImg.src = `./src/day.svg`,
  false: timeImg.src = `./src/night.svg`,
})[IsDayTime] || 'Dados não encontrados'

x(true)
x(false)
```

Executa esse código e comenta aqui em baixo na issue: 

1. O que vc pode fazer para visualizar os valores que as duas invocações de `x` estão retornando?
2. Pq vc acha que elas retornaram esses valores?
3. O que vc espera que as propriedades `true` e `false` do objeto armazenem na primeira e segunda vez que a função foi invocada?

@YureK-a

**Comment by YureK-a** [comment]
1. Inspecionar o HTML e olhar a tag img, ou utilizar um console.log()
2. Porque o que é retornado é o valor do src da timeImg
3. Os valores atribuídos ao src da timeImg

Como esse tipo de função apenas retorna valores, ela não é adequada para executar ações, sendo melhor utilizar if mesmo. Correto?

**Comment by Roger-Melo** [comment]
> ### 1. Inspecionar o HTML e olhar a tag img, ou utilizar um console.log()

Inspecionar HTML não vai te ajudar tanto quanto console.log nesse caso.

Não sei se chegou a perceber, mas principalmente nas etapas iniciais do treinamento, eu uso o console.log praticamente a cada linha que escrevo, para mostrar o valor que uma determinada expressão / parâmetro / variável está armazenando.

Eu não faço isso só por motivos didáticos.

Não assuma que suas variáveis estão recebendo os valores que vc espera.

**Sempre use console.log para checar suas variáveis**.

Só essa prática já traz bastante clareza de como o código realmente está funcionando e evita que vc seja pego de surpresa.

> ### A logTImeIcon executa apenas a condição correspondente ao false, sendo que a IsDayTime recebe true(caso o usuário procure por São Paulo, por exemplo).

Se vc executar o código acima, verá que isso não é verdade. 

![image](https://user-images.githubusercontent.com/29297788/147352376-eac2e4a4-e8c6-49c8-a296-0386ce05db1b.png)

---

> ### 2. Porque o que é retornado é o valor do src da timeImg

Isso mesmo. 

Quando uma reatribuição é executada, a expressão de reatribuição resulta no valor que a variável/parâmetro/propriedade recebeu:

```javascript
let y = 1
console.log(y = 2) // 2
```

```javascript
const obj = {
  prop1: 1
}

console.log(obj.prop1 = 2) // 
```

---

> ### 3. Os valores atribuídos ao src da timeImg

Exatamente. O que vc fez de diferente no código que já mostrei que funciona que o levou a relatar o problema abaixo?

> Eu não estou entendendo o por quê da logTimeIcon não funcionar corretamente e a logTimeIcon2 funcionar. A logTImeIcon executa apenas a condição correspondente ao false, sendo que a IsDayTime recebe true(caso o usuário procure por São Paulo, por exemplo). 

---

> ### Como esse tipo de função apenas retorna valores, ela não é adequada para executar ações, sendo melhor utilizar if mesmo. Correto?

Primeiro, voltando ao seu exemplo, o nome da função não descreve o que ela faz...

```javascript
const logTimeIcon = IsDayTime => ({
  true: timeImg.src = `./src/day.svg`,
  false: timeImg.src = `./src/night.svg`,
}) [IsDayTime] || 'Dados não encontrados'

cityForm.addEventListener('submit', async event => {
  // ...
  logTimeIcon(IsDayTime)
}
```

Por que essa função se chama `logTimeIcon`? Não faz sentido.

Já que ela seta a imagem do ícone, um nome mais adequado seria `setTimeIcon`.

Segundo, não há necessidade de declarar a função retornando um valor, pq esse valor não está sendo aproveitado.

Olha a diferença entre as duas funções:

```javascript
const logTimeIcon = IsDayTime => ({
  true: timeImg.src = `./src/day.svg`,
  false: timeImg.src = `./src/night.svg`,
}) [IsDayTime] || 'Dados não encontrados'

const logTimeIcon2 = IsDayTime => {
  if (IsDayTime) {
    timeImg.src = `./src/day.svg`
    return
  }

  timeImg.src = `./src/night.svg`
}
```

A primeira, além de setar a imagem, retorna o valor que src recebeu.

A segunda apenas seta o src. 

São funções criadas com dois objetivos diferentes.

Se é só pra setar o src baseado em `IsDayTime`, pq não deixar isso o mais simples possível?

```javascript
timeImg.src = IsDayTime ? './src/day.svg' : './src/night.svg'
```

Observe tb que vc não precisa usar template string, pq nenhuma interpolação é necessária. 

Eu não me lembro se fiz algo diferente nesse código durante as aulas, mas olhando em retrospecto, eu não vejo sentido em criar uma função só pra fazer esse tipo de atribuição. Faria apenas isso.

@YureK-a

**Comment by YureK-a** [comment]
Compreendo. Eu não lembrava, mas na minha versão da weather application eu fiz exatamente isso, usei o ternário para setar o valor, haha. Muito obrigado por tirar minha dúvida, e feliz Natal =)

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
