### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by danielscastro** [roger-melo-treinamentos/curso-de-js-roger-melo#2576]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/danielscastro/quiz-cjrm/tree/master

### Maiores dificuldades durante a implementação

Honestamente, a maior dificuldade foi olhar a documentação do Bootstrap para criar a aplicação sem encostar no CSS. Foi um desafio que eu me mesmo coloquei na atividade, fiquei satisfeito com o resultado, apesar de simples. Algo que eu também não sabia é que, ao submeter um form, as opções do radio input seriam acessíveis pelo objeto event.

### Menores dificuldades durante a implementação

A implementação da comparação dos valores é bem simples e direta, achei relativamente fácil.

**Comment by Roger-Melo** [comment]
Olá @danielscastro.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @danielscastro!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Honestamente, a maior dificuldade foi olhar a documentação do Bootstrap para criar a aplicação sem encostar no CSS. Foi um desafio que eu me mesmo coloquei na atividade, fiquei satisfeito com o resultado, apesar de simples. Algo que eu também não sabia é que, ao submeter um form, as opções do radio input seriam acessíveis pelo objeto event.

Lembra que usando `event.target` vc tem acesso ao elemento no qual o evento foi disparado? 

Como vc usou `e.target` dentro do callback de listener de `submit` do `form`, `e.target` resulta na referência do próprio form. 

Com a referência do form, vc pode acessar qualquer elemento do form que tenha um atributo `id` ou `name` (`e.target.nomeDoAtributo`). 

Por isso `e.target.inputQuestion1` resulta na referência do input que contém `name="inputQuestion1"`.

Pelo seu código, é perceptível que vc pegou bem a lógica até aqui. Sua análise tem poucos ajustes =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que alguns cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou claro o progresso do usuário em relação ao total de pontos, inserindo "/100" no final da mensagem. Isso é bom para a usabilidade, pq traz mais clareza do progresso do usuário no quiz.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Local da exibição dos pontos

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![image](https://user-images.githubusercontent.com/29297788/147385025-d3188fd7-7f85-4997-9e38-070ae876ea57.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

---

## Alternativas desmarcadas por padrão

Talvez seja interessante deixar a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## Separação entre tipos de consts

Se quiser, vc pode separar as consts pelo tipo de valor que elas armazenam.

No código abaixo, as consts que armazenam referências de elementos do DOM e a const que armazena as respostas corretas estão "agrupadas":

```javascript
const rightAnswers = ['A', 'A', 'A', 'A']
const form = document.querySelector('form')
const score = document.querySelector('.score')
```

Para organizar as consts pelo tipo de valor que armazenam, vc pode inserir uma linha em branco entre elas:

```javascript
const rightAnswers = ['A', 'A', 'A', 'A']

const form = document.querySelector('form')
const score = document.querySelector('.score')
```

Ou assim:

```javascript
const form = document.querySelector('form')
const score = document.querySelector('.score')

const rightAnswers = ['A', 'A', 'A', 'A']
```

---

## Posicionamento da invocação do `preventDefault`

Ao observar outros códigos vc verá que geralmente, a invocação do `preventDefault` virá na primeira linha do callback.

É uma convenção.

Do ponto de vista de organização de código, isso faz sentido pq vc demonstra antes de qualquer coisa que a página não será carregada quando o form for enviado. Então eu sugiro que vc siga essa convenção.

```javascript
// antes
form.addEventListener('submit', e => {
  let scorePoints = 0
  e.preventDefault()

  // ...
})
```

```javascript
// depois
form.addEventListener('submit', e => {
  e.preventDefault()
  let scorePoints = 0

  // ...
})
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by danielscastro** [comment]
Olá, Roger! Sim, fizeram total sentido. Li com atenção e agradeço pelo feedback e críticas (positivas e negativas). Rumo à fluência e às próximas aplicações!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue.

Rumo à fluência 🔥
