### ISSUE TITLE
Aula 02-03, nome do vídeo: A palavra chave this.

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#258]
```js
let user = {
  name: 'Gabriel',
  age: 17,
  email: 'gabriel.merigo.dev@gmail.com',
  city: 'Porto Alegre',
  blogPosts: ['Super-man', 'Spider-man'],
  login: () => {
    return 'Usuário Logado'
  },
  logout: () => {
    return 'Usuário Deslogado'
  },
  logBlogPosts: () => {
    console.log(this.blogPosts)
  }
}

user.logBlogPosts() // return undefined

/*--------------------*/

let user = {
  name: 'Gabriel',
  age: 17,
  email: 'gabriel.merigo.dev@gmail.com',
  city: 'Porto Alegre',
  blogPosts: ['Super-man', 'Spider-man'],
  login: function() {
    return 'Usuário Logado'
  },
  logout: function() {
    return 'Usuário Deslogado'
  },
  logBlogPosts: function() {
    console.log(this.blogPosts)
  }
}

user.logBlogPosts() //return ["Super-man", "Spider-man"]
```

Olá, Roger, tudo bem? Essa dúvida não parte especificamente da aula mas foi ao longo de erros, pois eu estava utilizando arrow functions para criar metodos dentros dos objetos. Porém, eu queria entender por que no primeiro exemplo, utilizando arrow functions para criar métodos, está me retornando "undefined" e por que utilizando function declaration (function()) me retorna o correto, que é o array de blogPosts. Aguardo a resposta e um abraço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Vou te dar um panorama geral do por que isso acontece, mas você só vai entender o comportamento do this conforme for avançando no treinamento. Você ainda verá muito sobre ele =)

Isso acontece por que um `this` dentro de uma arrow function referencia um valor diferente de um `this` de uma função declarada com a palavra-chave `function`.

Basicamente, o `this` dentro de uma arrow function referencia o `this` do escopo léxico. Escopo léxico é o escopo que envolve a declaração da arrow function.

Se você exibir no console o `this` da arrow function, verá que ele referencia o objeto `window`, e não o objeto `user`:

```javascript
let user = {
  // ...
  logBlogPosts: () => {
    console.log(this)
  }
}

user.logBlogPosts() // Window {window: Window, self: Window, document: document, name: "", location: Location, …}
```

Como o objeto `window` não possui um método `logBlogPosts`, a expressão `this.blogPosts` resulta em `undefined`. Ou seja, por baixo dos panos, o que o `console.log` está exibindo no console é o resultado de `window.blogPosts`.

Sacou a ideia?

Dito isso, métodos/funcões declaradas com a palavra-chave `function` fazem o `this` referenciar o objeto no qual a invocação do método foi encadeada. 

Se você exibir no console o `this` da função tradicional, verá que ele referencia o objeto `user`, por que a invocação de `logBlogPosts()` foi encadeada no objeto `user`:

```javascript
let user = {
  myProp: 1,
  logBlogPosts: function () {
    console.log(this)
  }
}

user.logBlogPosts() // {myProp: 1, logBlogPosts: ƒ}
```

Como eu disse anteriormente, isso foi apenas um panorama geral. Você ainda conhecerá e treinará muito seu conhecimento sobre funções, this e escopos durante o treinamento. E claro, se as dúvidas persistirem conforme for avançando, é só abrir novas issues.

Respondi a dúvida de por que a invocação do `logBlogPosts` não estava retornando o resultado esperado?

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
- Agora ficou claro, Roger!! Obrigado sanar minha dúvida! 🤩
