### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2589]
É um objeto de contexto, representa o contexto no qual o código atual está sendo executado. O valor do “_this_” é o objeto no qual o método está sendo usado. Quando o “_this_” é usado para referenciar o objeto no qual o método foi criado, é necessário o uso de uma function declaration. Se o método for criado usando uma arrow function, o “_this_” irá referenciar o objeto de mesmo escopo onde o método foi invocado.
É possível criar um método usando function declaration com uma sintaxe reduzida, onde a palavra reservada “_function_” e  o sinal _“:”_ podem ser ocultados:

```JS
logout() {
       console.log('usuário deslogado')
   }

```

**Comment by Roger-Melo** [comment]
Show @RodrigoLimaMota. Vamo que vamo, rumo à fluência! 🙌
