### ISSUE TITLE
Resumo da Aula Introdução a Classes - Aula 02-06 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2590]
Criar objetos literais nem sempre é a melhor solução. Quando eu preciso criar um ou outro objeto, eu crio esses objetos de forma literal. Mas quando eu preciso criar vários objetos que contém as mesmas características, eu preciso buscar outras maneiras de criar estes objetos de uma maneira mais eficiente. Existem algumas maneiras de construir objetos semelhantes em JavaScript. Podem ser usadas funções construtoras, *factory functions*, classes... uma das formas usadas antigamente para criar objetos parecidos era usar *prototypes* diretamente. Com a chegada do ES6 se tornou possível utilizar a palavra chave `class` para construir objetos. Classes, em JavaScript, são só uma abstração, pois elas usam *prototypes* por baixo dos panos. Uma classe é a planta de um objeto. É um *template* que descreve quais serão as propriedades base de um objeto. Por exemplo, vamos imaginar como seria a planta de um objeto carro:

Propriedades (características)

- Cor
- Modelo
- Motor

Funcionalidades

- Andar
- Acender faróis
- Parar

Todos os carros criados a partir desse *blueprint* terão essas características e ações, mas isso não significa que todos os carros serão iguais, pois cada carro pode ter uma cor, modelo e motor diferentes, por exemplo. Em JavaScript uma classe é um construtor, e um construtor é uma função.

Por convenção, uma classe é declarada com o primeiro nome em maiúsculo para se diferenciar dos métodos, utilizando a palavra chave `class` antes. Em seguida declaramos o construtor através da palavra chave `constructor`, que é um método, então abrimos parênteses para recebimento de parâmetros e abrimos chaves para o bloco de código que será executado, onde utilizamos a palavra chave `this` que se referencia ao objeto que está sendo criado no momento. Vamos ver na prática a criação de uma classe *User* com duas propriedades e a criação de um objeto a partir dessa classe:

```jsx
class User {
	constructor (name, email) {
		this.name = name
		this.email = email
	}
}

const user = new User('Ricardo', 'ricardopontesdantas@gmail.com');
console.log(user);
```

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. Vamo que vamo, rumo à fluência! 🙌
