### ISSUE TITLE
Resumo da Aula Encadeando métodos 02-03 da etapa 08

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2592]
O **encadeamento de métodos** é um recurso muito prático para manipulação de dados em um _array_. Se tivermos, por exemplo, uma lista de diversos produtos com diversas marcas e preços e precisarmos alterar temporariamente alguns deles, podemos gerar uma nova lista com as informações alteradas, de “uma vez só”.

Assim, ao invés de primeiro filtrarmos o _array_ original com `filter()` para obtermos a informação desejada e depois aplicarmos o `map()` para transformar o novo _array_ gerado pelo método anterior, podemos encadear estes dois métodos, eliminando a necessidade de duas variáveis para armazenar cada novo array gerado.
Exemplo:

```js
// sem encadeamento (dois arrays gerados e armazenados separadamente)
const arrayFiltrado = arrayOriginal.filter(funçãoCondicional)
const arrayFiltradoeModificado = arrayFiltrado.map(funçãoParaModificação)

// encadeando (armazenando um único array)
const arrayFiltradoEModificado = arrayOriginal
    .filter(funçãoCondicional)
    .map(funçãoParaModificação)
```
Onde:

- _arrayOriginal_ é o array tomado como base
- _arrayFiltrado_ é a constante que recebeu o novo _array_ gerado pelo método f`ilter()` com base no _arrayOriginal_
- _arrayFiltradoEModificado_ é a constante que recebeu o novo _array_ gerado após uso do `filter()` e `map()`
- _funcãoCondicional_ é a função que deve conter a condição a ser verificada no método _filter()_
- _funçãoParaModificação_ é a função que deve conter a expressão para inserir as modificações desejadas no novo _array_, por meio do método _map()_

Por convenção, cada método é deixado em uma nova linha, indentando os conteúdos, para melhor visualização do que está sendo feito no _array_.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. Vamo que vamo, rumo à fluência! 🙌
