### ISSUE TITLE
Aplicação: [Weather Application]

### ISSUE THREAD

**Issue by mcrodrigo** [roger-melo-treinamentos/curso-de-js-roger-melo#2593]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/mcrodrigo/weather-app.git

### Maiores dificuldades durante a implementação

- refactoring da função que executa os requests

### Menores dificuldades durante a implementação

- inserir as informações da API na interface

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ### refactoring da função que executa os requests

Essa aplicação realmente exige um pouco mais de atenção aos requests.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Função com muitos parâmetros

`insertDataIntoDOM` pode receber um objeto ao invés de vários argumentos/parâmetros.

Você pode usar um objeto como argumento de uma função quando quiser:

- Diminuir o número de argumentos/parâmetros que ela recebe;
- Deixar mais claro o que os valores inseridos como argumentos significam.

Funções com vários argumentos são mais complexas de testar e manter, pois exigem que casos diferentes sejam testados com cada argumento individualmente.

Como em JS é possível que objetos sejam criados à qualquer momento, sem a necessidade de usar classes, um objeto pode substituir vários argumentos espalhados na invocação de uma função.

Outra vantagem é que objetos não precisam obedecer uma ordem de parâmetros. 

Por exemplo...

Na função abaixo, é obrigatório que ao invocá-la, `LocalizedName` seja o 1º argumento, `WeatherText` o segundo, etc. 

Se essa ordem não for obedecida, o código quebra.

```javascript
const insertDataIntoDOM = (LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature) => {
  // ...
}
```

Pegando um outro exemplo, se vc observar a invocação abaixo, não fica tão explícito o que os valores inseridos como argumentos significam:

```javascript
manipulateClasses(todosToHide, 'hidden', 'd-flex')
```

Porém, se um objeto for inserido como argumento, fica mais fácil entender por que 'hidden' e 'd-flex' (por exemplo) estão sendo usadas ali:

```javascript
manipulateClasses({ todos: todosToHide, classToAdd: 'hidden', classToRemove: 'd-flex' })
```

Ou seja, fica fácil saber que `hidden` é a classe a ser adicionada e `d-flex` é a classe a ser removida. Mas claro, isso só funciona se os nomes das propriedades deixarem isso explícito.

Voltando para o exemplo da `insertDataIntoDOM`, mesmo que os argumentos que ela recebe estejam legíveis, acho que vale a refatoração, devido às vantagens que mencionei acima.

Ficaria assim:

```javascript
const insertDataIntoDOM = data => { /* ... */ }

// ...

insertDataIntoDOM({ LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature })
```

E claro, se vc quiser, pode fazer o destructuring do objeto que está sendo recebido como parâmetro:

```javascript
const insertDataIntoDOM = ({ LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature }) => {
  // ...
}
```

---

## Várias queries no DOM

As linhas abaixo estão sendo executadas à cada envio do form:

```javascript
const [time, timeIcon, weatherDetails] = weatherContainer.children
const [localized, weather, temperature] = weatherDetails.children
```

Isso significa que a cada envio do `form`, duas novas buscas por esses elementos estão sendo feitas no DOM.

Ou seja, se o form é enviado 2x seguidas, 4 queries no DOM são executadas. 

É possível reduzir esse número para 2 queries, independente de quantas vezes seguidas o form é enviado. 

Para ter esse pequeno ganho em performance, basta executar as queries de cada elemento apenas 1x e armazenar essas referências em consts no topo do código, como vc já havia feito com `weatherContainer` e `cityForm`:

```javascript
const cityForm = document.querySelector('[data-js="change-location"]')
const weatherContainer = document.querySelector('[data-js="weather-container"]')
```

Feito isso, a cada execução do callback de envio do form, ao invés dos elementos serem buscados no DOM novamente, as referências deles serão apenas reaproveitadas.

Afinal, quando um callback de listener de evento é executado, ele não faz o código que está fora dele ser declarado novamente. Apenas o bloco do callback é executado novamente. Isso significa que as mesmas referências estão sendo usadas dentro do callback.

Faz sentido?

A desvantagem dessa abordagem é que o código fica mais extenso. Mas do ponto de vista de performance, o saldo é positivo.

Ao declarar os elementos no topo, como esses elementos estarão em escopo global, as invocações de `setTimeSrc` e `setTimeIcon` não precisarão receber esses elementos como primeiro argumento.

Inclusive, talvez faça mais sentido criar funções genéricas apenas quando o código demonstre que precisa disso.

Na `showWeatherContainer`, por exemplo, como `weatherContainer` é o único elemento da aplicação que irá ser manipulado da forma que está especificada na função, o parâmetro `element` pode ser eliminado e a referência de `weatherContainer` pode ser usada dentro da função:

```javascript
// antes
const showWeatherContainer = element => {
  if (element.classList.contains('d-none')) {
    element.classList.remove('d-none')
  }
}
```

```javascript
// depois
const showWeatherContainer = () => {
  if (weatherContainer.classList.contains('d-none')) {
    weatherContainer.classList.remove('d-none')
  }
}
```

---

## Nome do parâmetro diferente do nome do argumento

Geralmente, a leitura do código fica mais coerente quando o parâmetro tem o mesmo nome do argumento que a função recebeu (a não ser que o nome do argumento realmente atrapalhe). 

Além de que no código abaixo, `timeOfDay` está recebendo um boolean e, é uma convenção que variáveis/parâmetros que armazenem booleans contenham `is`, `has` ou `should`, como eu já havia lhe mostrado no tópico `Nomes de variáveis e funções` [dessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2416#issuecomment-990123495).

Observe a diferença e veja se faz sentido:

```javascript
// antes
const dayOrNight = (timeOfDay) ? 'day' : 'night'
```

```javascript
// depois
const dayOrNight = IsDayTime ? 'day' : 'night'
```

A sugestão de mudança também vale para `setTimeIcon`:

```javascript
// antes
`<img src="/src/icons/${icon}.svg">`
```

```javascript
// depois
`<img src="/src/icons/${WeatherIcon}.svg">`
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by mcrodrigo** [comment]
Obrigado pelas observações. Sim, elas fizeram sentido


...

Em domingo, dezembro 26, 2021, 3:17 PM, Roger Melo ***@***.***> escreveu:




Olá @mcrodrigo!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)


refactoring da função que executa os requests


Essa aplicação realmente exige um pouco mais de atenção aos requests.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

Função com muitos parâmetros

insertDataIntoDOM pode receber um objeto ao invés de vários argumentos/parâmetros.

Você pode usar um objeto como argumento de uma função quando quiser:
   
   - Diminuir o número de argumentos/parâmetros que ela recebe;
   - Deixar mais claro o que os valores inseridos como argumentos significam.

Funções com vários argumentos são mais complexas de testar e manter, pois exigem que casos diferentes sejam testados com cada argumento individualmente.

Como em JS é possível que objetos sejam criados à qualquer momento, sem a necessidade de usar classes, um objeto pode substituir vários argumentos espalhados na invocação de uma função.

Outra vantagem é que objetos não precisam obedecer uma ordem de parâmetros.

Por exemplo...

Na função abaixo, é obrigatório que ao invocá-la, LocalizedName seja o 1º argumento, WeatherText o segundo, etc.

Se essa ordem não for obedecida, o código quebra.
const insertDataIntoDOM = (LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature) => {
  // ...
}
Pegando um outro exemplo, se vc observar a invocação abaixo, não fica tão explícito o que os valores inseridos como argumentos significam:
manipulateClasses(todosToHide, 'hidden', 'd-flex')
Porém, se um objeto for inserido como argumento, fica mais fácil entender por que 'hidden' e 'd-flex' (por exemplo) estão sendo usadas ali:
manipulateClasses({ todos: todosToHide, classToAdd: 'hidden', classToRemove: 'd-flex' })
Ou seja, fica fácil saber que hidden é a classe a ser adicionada e d-flex é a classe a ser removida. Mas claro, isso só funciona se os nomes das propriedades deixarem isso explícito.

Voltando para o exemplo da insertDataIntoDOM, mesmo que os argumentos que ela recebe estejam legíveis, acho que vale a refatoração, devido às vantagens que mencionei acima.

Ficaria assim:
const insertDataIntoDOM = data => { /* ... */ }

// ...

insertDataIntoDOM({ LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature })
E claro, se vc quiser, pode fazer o destructuring do objeto que está sendo recebido como parâmetro:
const insertDataIntoDOM = ({ LocalizedName, WeatherText, WeatherIcon, IsDayTime, Temperature }) => {
  // ...
}
Várias queries no DOM

As linhas abaixo estão sendo executadas à cada envio do form:
const [time, timeIcon, weatherDetails] = weatherContainer.children
const [localized, weather, temperature] = weatherDetails.children
Isso significa que a cada envio do form, duas novas buscas por esses elementos estão sendo feitas no DOM.

Ou seja, se o form é enviado 2x seguidas, 4 queries no DOM são executadas.

É possível reduzir esse número para 2 queries, independente de quantas vezes seguidas o form é enviado.

Para ter esse pequeno ganho em performance, basta executar as queries de cada elemento apenas 1x e armazenar essas referências em consts no topo do código, como vc já havia feito com weatherContainer e cityForm:
const cityForm = document.querySelector('[data-js="change-location"]')
const weatherContainer = document.querySelector('[data-js="weather-container"]')
Feito isso, a cada execução do callback de envio do form, ao invés dos elementos serem buscados no DOM novamente, as referências deles serão apenas reaproveitadas.

Afinal, quando um callback de listener de evento é executado, ele não faz o código que está fora dele ser declarado novamente. Apenas o bloco do callback é executado novamente. Isso significa que as mesmas referências estão sendo usadas dentro do callback.

Faz sentido?

A desvantagem dessa abordagem é que o código fica mais extenso. Mas do ponto de vista de performance, o saldo é positivo.

Ao declarar os elementos no topo, como esses elementos estarão em escopo global, as invocações de setTimeSrc e setTimeIcon não precisarão receber esses elementos como primeiro argumento.

Inclusive, talvez faça mais sentido criar funções genéricas apenas quando o código demonstre que precisa disso.

Na showWeatherContainer, por exemplo, como weatherContainer é o único elemento da aplicação que irá ser manipulado da forma que está especificada na função, o parâmetro element pode ser eliminado e a referência de weatherContainer pode ser usada dentro da função:
// antes
const showWeatherContainer = element => {
  if (element.classList.contains('d-none')) {
    element.classList.remove('d-none')
  }
}// depois
const showWeatherContainer = () => {
  if (weatherContainer.classList.contains('d-none')) {
    weatherContainer.classList.remove('d-none')
  }
}
Nome do parâmetro diferente do nome do argumento

Geralmente, a leitura do código fica mais coerente quando o parâmetro tem o mesmo nome do argumento que a função recebeu (a não ser que o nome do argumento realmente atrapalhe).

Além de que no código abaixo, timeOfDay está recebendo um boolean e, é uma convenção que variáveis/parâmetros que armazenem booleans contenham is, has ou should, como eu já havia lhe mostrado no tópico Nomes de variáveis e funções dessa análise.

Observe a diferença e veja se faz sentido:
// antes
const dayOrNight = (timeOfDay) ? 'day' : 'night'// depois
const dayOrNight = IsDayTime ? 'day' : 'night'
A sugestão de mudança também vale para setTimeIcon:
// antes
`<img src="/src/icons/${icon}.svg">`// depois
`<img src="/src/icons/${WeatherIcon}.svg">`
Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
