### ISSUE TITLE
Resumo da Aula Métodos em classes - Aula 02-07 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2595]
Se eu precisar criar um método para todos os objetos criados a partir de uma classe, basta eu adicionar esse novo método dentro da classe. Esse novo método é criado fora do construtor, declarado como o próprio construtor, sem a palavra chave `function`. Caso seja necessário utilizar alguma propriedade da classe dentro do método, deverá ser utilizada a palavra chave `this`, encadeando em seguida o nome da propriedade. Lembrando que o construtor é usado somente para setar as propriedades que o objeto criado pela classe terá. Vamos ver na prática a criação de um método `login()` que apenas retorne uma *string*.

```jsx
class User {
	constructor(name, email) {
		this.name = name;
		this.email = email;
	}

	login() {
		return `${this.name} logou na aplicação`;
	}
}

const user = new User('Ricardo', 'ricardopontesdantas@gmail.com');
console.log(user.login()); // Ricardo logou na aplicação
```

Agora vamos adicionar uma nova propriedade a classe *User,* chamada points, que será inicializada com o valor zero. E vamos criar um novo método chamado `addPoint()`. E agora toda vez que invocarmos o método `login()`, vamos em seguida encadear o método `addPoint()`. O método `addPoint()` será assim:

```jsx
class User {
	constructor(name, email) {
		// código omitido
		this.points = 0;
	}

	// código omitido

	addPoint() {
		this.points++;
		return `${this.name} agora tem ${this.points} ${this.points > 1 ? 'pontos' : 'ponto'}.`;
	}
}

const user = new User('Ricardo', 'ricardopontesdantas@gmail.com');
console.log(user.login().addPoint()); // isso irá gerar um erro
```

No código acima, ao invocar os métodos `login()` e em seguida encadear o método `addPoint()`, será retornado um erro no console dizendo que *addPoint() is not a function*. Porém isso ocorre porque o método `addPoint()` está encadeado a um método que retorna uma *string*. Então para que funcione corretamente, o método `login()` deveria retornar o próprio objeto criado, para que `addPoint()` seja invocado com sucesso. Então devemos alterar o retorno do método `login()` para retornar o próprio objeto, utilizando `return this`. E aí não será mais exibido um erro no console. Vamos ver na prática a classe *User* completa e a criação do objeto seguida da invocação dos métodos.

```jsx
class User {
	constructor(name, email) {
		this.name = name;
		this.email = email;
		this.points = 0;
	}

	login() {
		console.log(`${this.name} logou na aplicação.`);
		return this;
	}

	addPoint() {
		this.points++;
		return `${this.name} agora tem ${this.points} ${this.points > 1 ? 'pontos' : 'ponto'}.`;
	}
}

const user = new User('Ricardo', 'ricardopontesdantas@gmail.com');
console.log(user.login().addPoint());
```

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência! 🔥
