### ISSUE TITLE
Diferença entre .__proto__ e .prototype

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2597]
### Etapa da aula

14

### Nome da aula

Prototypes - Aula 03-07

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1886432

### Descreva a dúvida

Olá, @Roger-Melo 

Antes de tudo, feliz natal!

Bem essa aula sobre prototypes foi de longe a mais desafiadora pra mim até aqui. Ela me gerou uma tonelada de dúvidas. 
Eu sai da aula na verdade mais confuso do que quando entrei. Então, já me antecipo e peço desculpas pelo texto grande a seguir.

Na verdade, eu entendi os conceitos. Eu entendi que um prototype nada mais é que um objeto que fornece propriedades e métodos para outros objetos através de herança. E que todo objeto criado possui um prototype de onde ele herda propriedades e métodos. 

O meu problema é do ponto de vista de código, onde as coisas começaram a ficar confusas. 

Eu vou colocar abaixo uma lista de dúvidas que me surgiram e tentar explicar ou pouco melhor sobre cada uma delas. 

  * Por que funções construtoras existem se podemos retornar um objeto literal diretamente de uma função comum?
      Pelo que eu entendi funções construtoras são usadas quando precisamos criar diversos objetos que tem as mesmas propriedades e métodos. 
      Mas por que isso é necessário se podemos fazer isso com uma função tradicional?. EX: 
      ```js
        function Person (name, email) {
          this.name = name
          this.email = email
        }
        
        function Person2 (name, email) {
          return {
            name: name,
            email: email
          }
        }
      ```
      A função Person2 também cria um novo objeto assim como a Person1
    

  * Qual a diferença entre uma função construtora e uma função comum?
      Essa está relacionada com a pergunta acima. Já que de fato existem funções construtoras qual a real diferença delas para uma função comum?
      

  * Qual a diferença entre ```__proto__``` e .prototype ?
      Bem, aqui as coisas ficaram realmente confusas, vou tentar explicar:
      Na aula, você explica que para criar um método no prototype do objeto que a função cria devemos fazer isso fora da função. Isso me pareceu estranho pois do ponto de vista de organização me parece melhor manter os métodos dentro do bloco da função, fora parece que fazem parte de outr coisa. Por isso eu fui testar e tentar criar os métodos dentro da função: 

      ```js
        function Studant (name, email) {
          this.name = name
          this.email = email
        
          // this.prototype.login = function () { // Uncaught TypeError: Cannot set properties of undefined (setting 'login')
          //   return `${this.name} fez login`
          // }
        
          this.__proto__.login1 = function () { // Funciona
            return `${this.name} fez login`
          }
        
          Studant.prototype.login2 = function () { // Funciona
            return `${this.name} logou!`
          }
        
          Studant.__proto__.login3 = function () { // NÃO Funciona
            return `${this.name} logou!`
          }
        }
      ```
      - Bem, na primeira tentativa tentei fazer ```this.prototype.login``` e isso gerou um erro. Descobri que isso acontece pois o objeto criado pela função não possui uma propriedade chamada prototype mas sim chamada ```__proto__```. Tanto é que no segundo exemplo eu consigo criar o método. 
      - Mas eu também consigo criar o método chamando diretamente a função Studant.prototype. Em ambos os casos o método fica no prototype do objeto criado.
      - Porém no caso 3: Studant.```__proto__``` não funciona. Investigando eu descobri que no caso de Studante ela possui duas propriedades distintas. Uma chamada prototype e outro chamada ```__proto__```. E no caso 3 o método foi criado dentro da ```__proto__```, conforme a imagem. 

![prototypes](https://user-images.githubusercontent.com/31637175/147366177-93619f6e-271e-4d7a-8412-665c7fa42dfc.jpg)

Isso realmente me confundiu muito. A ponto de eu não entender mais o que é prototype e ```__proto__```. 

Então qual a diferença nesse cenário maluco que eu tentei explicar? 
Por que algumas coisas possui uma propriedade prototype e outras não?
Por que algumas possuem apenas uma propriedade chamasa ```__proto__```?
  
  * ```arr1.prototype === arr2.prototype // true. ```
      Mas ```arr1.prototype // undefined. Ou seja, ela não possui uma propriedade chama prototype, mas apenas uma chamada __proto__.``` 
      Essa ainda é sobre a pergunta acima. Em determinado momento da aula você executa esse código pra mostrar que ambos arrays possuem o mesmo prototype. Mas na verdade ambos estão refornando undefined e por isso é igual a true. Por que nenhum deles tem uma propriedade chamada prototype. 

  * Se eu criar um método no prototype de uma função construtora isso não significa que outras funções construtoras também vão ter acesso a esse método, já que elas compartilham o mesmo prototype?
      Eu não vou correr o risco de vários objetos diferentes terem acesso aos mesmos métodos já que eles compartilham um prototype em comum?

  * Em determinado momento da aula você diz que para criar um método no prototype do OBJETO que a função construtora cria, você o declara fora da função. Mas na verdade você está criando esse método no prototype da própria função construtora e não do objeto que ela cria, certo?
      Vê? eu não consegui entender a relação e a diferença ainda entre o prototype de uma função construtora e do prototype do OBJETO que a função cria.

  * Observe o código abaixo, ainda relacionado com o cenário anterior: 
      ```js
        function Studant (name, email) {
          this.name = name
          this.email = email
        
          // this.prototype.login = function () { // Uncaught TypeError: Cannot set properties of undefined (setting 'login')
          //   return `${this.name} fez login`
          // }
        
          this.__proto__.login1 = function () { // Funciona
            return `${this.name} fez login`
          }
        
          Studant.prototype.login2 = function () { // Funciona
            return `${this.name} logou!`
          }
        
          Studant.__proto__.login3 = function () { // NÃO Funciona
            return `${this.name} logou!`
          }
        }
      
      joao.__proto__.login1 === Studant.prototype.login1 // true
      joao.__proto__.login1 === Studant.__proto__.login1 // false
      ```

  * Sobre métodos estáticos, eu entendi a diferença entre declarar um método estático na função e no prototype do objeto que a função cria. Mas do ponto de vista prático qual a diferença? Por que os dois podem ser usados da mesma forma, não? 
      Eu posso fazer isso: ```Studant.formatToDataBase('Olá mundo')```
      mas eu também posso fazer isso: ```joao.formatToDataBase('Olá mundo')```

Mais uma vez perdão por jogar tanta coisa assim de uma vez. Sei que são muitas perguntas, mas é que isso realmente ficou martelando na minha cabeça. E não queria seguir para as próximas aulas antes de sanar essas dúvidas. 

Não precisa ter pressa para responder, muito obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior.

Antes de responder, deixa eu te dar uma dica...

Durante seus estudos de JS, vc irá se deparar com coisas novas à todo momento.

E isso é bom, significa que vc está se colocando em situações desconfortáveis.

Mas por outro lado, isso pode te causar uma certa ansiedade.

E por vezes, essa ansiedade não faz sentido. 

Sabe pq não faz sentido?

Pq na minha opinião, vc deve aprender o que faz sentido para o seu momento na jornada à fluência.

O objetivo do treinamento é te ensinar a construir aplicações web front-end com JS puro.

E sabe onde está o necessário que vc precisa saber de orientação à objetos para construir aplicações web front-end com JS puro?

Na etapa 14.

Na etapa 14 (e no começo da 15, na correção dos exercícios da última aula da etapa 14) eu condensei o que você precisa saber para construir aplicações web front-end com JS puro.

Esse é o propósito do treinamento.

E quando eu digo que o que vc deve saber sobre esse assunto está na etapa 14, isso significa que eu deixei de fora um monte de coisas que não te levam ao objetivo do treinamento.

O que vc precisa saber de prototypes para construir aplicações web front-end com JS puro está lá.

Nem mais, nem menos.

Vc tem a liberdade de querer saber tudo o que não conheça linguagem.

E eu tenho a liberdade para te dizer o que irá acelerar ou desacelerar sua chegada na fluência, afinal, vc decidiu entrar nesse treinamento e acredito que esse seja seu objetivo.

Na minha opinião, querer saber à fundo coisas internas da linguagem, como `__proto__`, é um bom sinal, mas não faz sentido pro seu momento.

Querer descobrir o "porque" de tudo de novo que vc encontra na linguagem vai retardar vc chegar no objetivo do treinamento.

Sabe pq?

Pq matar essa curiosidade e descobrir esse "porque" vai fazer diferença zero no seu dia a dia como Dev. Front-end.

Vc não vai usar esse tipo de conhecimento em seu dia a dia.

Então só pra reforçar: o que vc precisa saber de orientação à objetos para construir aplicações web front-end com JS puro está na etapa 14 =)

Ao invés de tentar descobrir o porque de tudo, penso que seja mais sensato se perguntar:

"Será que isso é importante para o meu momento?"

Sacou a ideia?

E sim, é muito legal ver as pessoas dizendo "vc tem que ser curioso", "vc tem que descobrir o porque"...

Mas na minha opinião, descobrir o "porque" de coisas inúteis vão te fazer perder tempo.

Estude o que faz sentido pro seu momento.

E o que faz sentido pra esse momento da sua jornada para construir aplicações web front-end com js puro é o que está na etapa 14. Sem tirar, nem colocar.

---

> ### Por que funções construtoras existem se podemos retornar um objeto literal diretamente de uma função comum?

> ### Qual a diferença entre uma função construtora e uma função comum?

Vc ainda não terminou a etapa 14 =)

Essas duas perguntas serão respondidas na aula `Factory functions e composição de objetos - Aula 03-09
`. 

Além disso, no começo da etapa 15 vc vai encontrar a correção de exercícios que envolvem o que vc está estudando agora. 

Se depois de acompanhar a correção dos exercícios essas duas dúvidas ainda estiverem com vc, pode abrir uma issue.

Até lá, não tenha pressa em entender tudo de uma vez, caso contrário, vc irá se frustrar =)

---

> ### Qual a diferença entre ```__proto__``` e .prototype ?

Vc encontrará essa resposta quando chegar na aula 01 da etapa 15.

---

> ### E não queria seguir para as próximas aulas antes de sanar essas dúvidas.

Não recomendo. 

A etapa 14 não terminou pra vc =)

E digo mais, só pq prefiro pecar pelo excesso do que pela falta: certas coisas não vão clicar na hora na sua cabeça. 

Isso é natural.

E tá tudo bem.

Eu recomendo que vc refaça a etapa 14 + correção de exercícios no começo da etapa 15 mais 2x.

Faz e repete.

Faz e repete.

Vai ser como um filme.

Na segunda vez, vc vai sacar coisas que não sacou na primeira. 

E essas coisas já estavam lá.

Na terceira vez, vc vai sacar coisas que não sacou na segunda. 

E aí vc vai pensar "puts, como eu não vi isso antes?".

Acontece com todo mundo. Pq não aconteceria com vc?

E se vc estiver disposto a questionar se o que está te tirando o sono realmente importa para o seu momento na jornada para aprender a construir aplicações web front-end com js puro, estou aqui pra te ajudar =)

**Comment by Hamiltonspjunior** [comment]
Olá, @Roger-Melo 

Entendi o que você quis dizer, sobre não precisar entender tudo de uma vez e sobre coisas que não fazem sentido nesse momento. Obrigado pelo toque. 

É que na verdade eu não teria como saber se essas coisas fazem ou não sentido pra mim nesse momento, entende?

Eu assisti as aulas e essas dúvidas surgiram, então como todas as outras vezes eu abri uma issue atrás das respostas. 
Mas foi legal você mostrar que tem coisas que simplesmente não faz sentido entender agora. E eu compreendo isso por que já aconteceu no passado antes também. Eu querer aprender absolutamente tudo sobre um determinado assunto e isso acabar me atrasando. 

Nesse caso eu achei que não estava entendendo o conteúdo por que essas dúvidas surgiram. Como eu expliquei eu entendi os conceitos principais, eu acho pelo menos. Sobre funções construtoras, como elas funcionam e os prototypes. Mas essas tecnicalidades me pegaram.

Eu vou seguir seu conselho e tentar me focar naquilo que está na aula 14 para aprender o que é necessário para seguir em frente.

Vou terminar a etapa 14 e repetir ela como você sugeriu e tentar não ficar tão na "nóia" querendo entender absolutamente tudo. 

Mais uma vez muito obrigado.

**Comment by Roger-Melo** [comment]
> ### É que na verdade eu não teria como saber se essas coisas fazem ou não sentido pra mim nesse momento, entende?

Vc pode perguntar, estou aqui pra te ajudar =)

Há várias possíveis dúvidas que podem surgir na cabeça do aluno que eu já antecipo e respondo nas aulas, mas algumas são imprevisíveis. 

Então qualquer dúvida específica que surgir, pode perguntar e eu vou dar a resposta mais adequada ao seu momento =)

Inclusive quando a reposta mais adequada é "desencana disso e foca no CJRM", hahahah

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Beleza, Roger. Combinado. 

Obrigado, pode fechar a issue.
