### ISSUE TITLE
sobre metodos de STRINGS e ARRAYS.

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#26]
Olá Roger, estou fazendo seu curso, estou na aula sobre 'STRINGS', já estudei um pouco sobre js antes de me inscrever no seu curso. Eis que me surge uma duvida, os metodos que sao usados em 'STRINGS' são usados também em 'ARRAYS', ou para cada um existem seus metodos especificos? Pois usamos os metodos 'concat, indexOf, slice' tanto para strings quanto para arrays. Sabe me dizer se existe diferença entre eles na hora de usamos em arrays e strings?

**Comment by Roger-Melo** [comment]
Oi @Mateus20Barros. 

Apenas **alguns métodos** podem ser usados tanto por strings como por arrays. E existe uma razão técnica para isso. 

Só que mesmo você já conhecendo um pouco da linguagem, não vai fazer muito sentido você se aprofundar nisso sem antes progredir no curso, começar a construir as aplicações e conhecer a linguagem à fundo.

Então eu recomendo que você não se preocupe com isso agora.

Quando o momento chegar, você vai ter a explicação nas aulas e as partes mais avançadas vão fazer sentido.

Combinado?

Se rolar mais dúvidas é só chamar aqui =)

**Comment by Mateus20Barros** [comment]
obg.... vou continuar aqui então

**Comment by Roger-Melo** [comment]
@Mateus20Barros show. Vou fechar a issue mas no que você precisar, pode chamar =D
