### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2602]
Quando é armazenado um valor de tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt), esse valor é armazenado em uma estrutura stack(pilha). Quando é criado dados de tipo de referência, (Objetos literais, Arrays, Funções, Datas..), o valor é armazenado em estrutura heap. O heap dispõe de mais espaço na memória para armazenar dados complexos. 
Quando um valor primitivo é armazenado, esse valor é salvo em uma stack e é acessado através do nome dado a esse valor. Quando um tipo de referência é criado, um objeto é armazenado no heap e um “ponteiro” é armazenado na stack que irá apontar para o objeto.

**Comment by Roger-Melo** [comment]
Boa @RodrigoLimaMota , rumo à fluência! 🔥
