### ISSUE TITLE
Dúvidas com retorno implícito no método .reduce()

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#2604]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 01 da etapa 14 - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1632925

### Descreva a dúvida

Professor, fiquei com algumas dúvidas na resolução do exercício 05 que você deu na aula. A seguir:

```js
const newTimestamps = timestamps.reduce((acc, { date, value }) => {
   acc[date] = value
   return acc
, {});
```

Eu tentei refatorar essa solução e notei que caso eu deixe um retorno implícito de 1 linha na arrow function, o console.log() me mostra 17 ao invés de mostrar o objeto que eu esperava criar.
![image](https://user-images.githubusercontent.com/52185265/147392395-a1050373-df10-4459-89cf-5be997606ea7.png)

Minha dúvida é por que isso acontece? Eu então refiz o exercício do zero utilizando retorno implícito e spread operator e esse foi o resultado:
![image](https://user-images.githubusercontent.com/52185265/147392421-74e3b751-5014-44bd-9eb0-962e4df24a77.png)

E a segunda dúvida é: está tudo bem eu ter resolvido dessa segunda maneira? 

Feliz Natal e abraços, @Roger-Melo !

**Comment by Roger-Melo** [comment]
Olá @Will-Andrade, feliz natal =)

> ### Minha dúvida é por que isso acontece? Eu então refiz o exercício do zero utilizando retorno implícito e spread operator e esse foi o resultado. E a segunda dúvida é: está tudo bem eu ter resolvido dessa segunda maneira?

Sim, é uma excelente resolução. 

Do ponto de vista funcional, é a ideal pois ao invés de modificar um objeto, vc está criando um novo (imutabilidade).

Nas aulas seguintes, vc perceberá que cada vez mais eu vou falar sobre imutabilidade e incentivar que ela seja um hábito em suas aplicações JavaScript. 

Parabéns =)

---

> ### Eu tentei refatorar essa solução e notei que caso eu deixe um retorno implícito de 1 linha na arrow function, o console.log() me mostra 17 ao invés de mostrar o objeto que eu esperava criar.

Uma expressão de reatribuição resulta no valor atribuído.

Isso significa que uma expressão `myLet = 'myValue'` resulta em `'myValue'`:

```javascript
let myLet = 'initial value'

console.log(myLet = 'myValue') // myValue
```

Sabendo disso, vc já tem ideia de pq `17` foi retornado?

---

PS: quando postar exemplos do código que vc fez, prefira postar como código js ao invés de imagem. Assim, fica mais fácil eu testar e inserir no meu comentário de resposta da issue =)

**Comment by Will-Andrade** [comment]
Obrigado professor, agora sim consegui sacar kkkkk
O valor ```17``` foi retornado pela última iteração do reduce, que está atribuindo à última prop ```date``` esse valor
```js
.reduce((acc, {'8596646656666r488', 17}) => acc['8596646656666r488'] = 17)
```
E como o senhor bem disse na aula: toda EXPRESSÃO resulta num valor. Vou me lembrar disso sempre daqui pra frente!

Valeu @Roger-Melo!

**Comment by Roger-Melo** [comment]
Isso mesmo =)

Já que ficou claro, vou fechar a issue. Mas no que precisar, é só abrir uma nova =)
