### ISSUE TITLE
Event Delegation e qualidade de codigo

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#2605]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 01 da etapa 14 - Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1643666

### Descreva a dúvida

Professor, boa tarde. Tudo jóia? Durante a correção do carrossel, eu percebi que você não usou a técnica de Event Delegation para atribuir listeners de evento para os controles do carrossel. No treinamento, eu percebi que após a todo list que desenvolvemos, o senhor não reforçou o uso de event delegation para criação de listeners em situações semelhantes a essa. 

Minha pergunta é: há alguma razão para não usar a delegação de eventos para atribuir listeners à elementos nesses casos? E não sei se já é a hora para pensar nisso mas essa escolha tem haver com qualidade/rapidez no código?

Como exemplo, aqui está uma possível versão do carrossel só que aproveitando o borbulhamento de eventos:
```js
const slides = document.querySelectorAll('[data-js="carousel__item"]');
const carouselActions = document.querySelector('.carousel__actions');

const lastSlideIndex = slides.length - 1;
let currentSlide = 0;

carouselActions.addEventListener('click', ({ target }) => {
  const clickedOnPrevSlide = target.dataset.js === 'carousel__button--prev';
  const clickedOnNextSlide = target.dataset.js === 'carousel__button--next';

  if (clickedOnNextSlide) {
    const correctSlideIndex = currentSlide === lastSlideIndex 
      ? currentSlide = 0
      : ++currentSlide;
    
    manipulateSlidesClasses(correctSlideIndex);
    return;
  }

  if (clickedOnPrevSlide) {
    const correctSlideIndex = currentSlide === 0 
      ? currentSlide = lastSlideIndex 
      : --currentSlide;

    manipulateSlidesClasses(correctSlideIndex);
  }
});
```

Abraços e feliz Natal, @Roger-Melo !

**Comment by Roger-Melo** [comment]
> ### E não sei se já é a hora para pensar nisso mas essa escolha tem haver com qualidade/rapidez no código?

Como vou mostrar abaixo, é uma escolha que, pra mim, tem mais relação com o design do código do que com performance.

Mais pro final da etapa 14, vc encontrará uma aula onde falo sobre o que vc realmente precisa se preocupar quando o assunto é performance =)

---

> ### Minha pergunta é: há alguma razão para não usar a delegação de eventos para atribuir listeners à elementos nesses casos? 

É uma forma válida de implementar também =)

A desvantagem que vejo é que ao incluir a função `manipulateSlidesClasses` (que não está no código que vc enviou), a solução apresentada na aula tem menos linhas de código. 

Quanto menos código, menos risco de bugs =)

Um outro ponto a se observar é a flexibilidade do código nas duas abordagens.

Com event delegation neste caso, vc teria que acrescentar mais ifs conforme novos elementos fossem adicionados no carousel:

```javascript
carouselActions.addEventListener('click', ({ target }) => {
  // ...

  if (clickedOnNextSlide) {
    // ...
  }

  if (clickedOnPrevSlide) {
    // ...
  }

  if (clickedOnSomeElement) {
    // ...
  }

  if (clickedOnAnotherElement) {
    // ...
  }
})
```

Esse tipo de design de código é um pouco limitante, pois te "força" a adicionar mais ifs. 

Não que seja errado. Podem haver casos em que essa seja a melhor escolha =)

Já na abordagem de listerens de eventos em cada botão, o código acaba ficando menor e sem ifs:

```javascript
nextButton.addEventListener('click', () => {
  // ...
})

prevButton.addEventListener('click', () => {
  // ...
})
```

No exemplo acima, se novos elementos forem adicionados no carousel, cada elemento terá seu próprio callback que lida com o que deve acontecer quando o elemento for clicado. Então o código fica mais modularizável.

Ficou mais claro?

---

@Will-Andrade

**Comment by Will-Andrade** [comment]
Ahhh, agora sim eu consegui entender a ideia. Ficou claro sim, faz sentido!
Obrigado pelo esclarecimento, professor!

**Comment by Roger-Melo** [comment]
No que precisar, é só dar o toque =)
