### ISSUE TITLE
Aplicação: Currency Converter

### ISSUE THREAD

**Issue by francisko-rezende** [roger-melo-treinamentos/curso-de-js-roger-melo#2606]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/francisko-rezende/cjrm-currency_converter

### Maiores dificuldades durante a implementação

Evitar a reatribuição do conteúdo de uma let no escopo global para usar os dados obtidos da API em callbacks de event listeners diferentes. 

Eu achei a sugestão que você me deu no último feedback sobre como contornar reatribuição muito chique e escasquetei que não ia entregar esse app com reatribuição. A estratégia que levei mais longe foi uma tentativa de armazenar as taxas de conversão no dataset dos elementos "option" mas acabei não conseguindo implementar a atualização dos valores. A minha estratégia dependia da ordem das options bater com a ordem das props do objeto retornado pela API e aparentemente isso só rolava na primeira vez que . Pensei também que talvez rolasse de usar closure pra armazenar o objeto retornado pela API mas acabei não indo muito longe com essa estratégia. Acabei me dando por vencido e submetendo com a reatribuição apesar de não estar 100% satisfeito :sweat_smile:  Tendo rezado essa missa toda na sua orelha também queria dizer que fiquei também não fiquei triste, acho que o resultado final tá ok!

### Menores dificuldades durante a implementação

Manipular o DOM e consumir os dados da API foi tranquilo.

Além disso, eu finalmente estou ficando mais em paz com a minha capacidade de refatorar código! Tá rolando de maneira mais natural e a implementação tá saindo mais suave também, tô bem feliz com isso. Agora só espero que o produto final faça sentido pra outras pessoas kkkkkkk Se você puder me dizer se, de maneira geral, o código tá ok eu agradeço, Roger!

Obrigado e boas festas! :santa: :fireworks:

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @francisko-rezende!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

> ### Evitar a reatribuição do conteúdo de uma let no escopo global para usar os dados obtidos da API em callbacks de event listeners diferentes.

Imutabilidade é um caminho sem volta hahah. Nas aulas seguintes vc verá uma forma de evitar essa reatribuição.

Seu código ficou bom. Bons nomes e boa lógica. Tanto é que a análise tem poucos ajustes =)

---

## Tipo retornado pelo `toFixed`

O `toFixed` já retorna uma string, então dentro de `handleConversionQuantityChange` e `updateDisplayedInfo`, não é necessário inserir `formattedConversionResult` em interpolações de template string:

```javascript
// antes
const handleConversionQuantityChange = event => {
  // ...
  convertedValueParagraph.textContent = `${formattedConversionResult}`
}
```

```javascript
// depois
const handleConversionQuantityChange = event => {
  // ...
  convertedValueParagraph.textContent = formattedConversionResult
}
```

---

## Callback de input de `targetCurrencySelect`

Se `handleTargetCurrencyChange` apenas invoca `updateDisplayedInfo`, vc pode especificar `updateDisplayedInfo` como callback do evento:

```javascript
// antes
const handleTargetCurrencyChange = () => {
  updateDisplayedInfo()
}

// ...

targetCurrencySelect.addEventListener('input', handleTargetCurrencyChange)
```

```javascript
// depois
targetCurrencySelect.addEventListener('input', updateDisplayedInfo)
```

Talvez vc não tenha feito isso antes para manter o padrão de nomenclatura "handleAlgumaCoisa", mas `updateDisplayedInfo` é um nome que descreve melhor a ação que a função está executando. 

`handle...` pode ser usado em funções que executam várias ações, ou pode até mesmo ser evitado se a função de callback referenciada no evento tem um nome mais direto ao ponto e, no final dela, contém a invocação da função que faz a próxima ação, e assim por diante xD

---

## Indicando qual tipo de valor uma `let` deve receber

Ao invés da `let` conversionRateData receber `null` por padrão, inicialmente vc pode atribuir um objeto à ela:

```javascript
// antes
let conversionRateData = null
```

```javascript
// depois
let conversionRateData = {}
```

A vantagem disso é que vc já expressa no código qual valor a let deve receber no futuro.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by francisko-rezende** [comment]
Ei @Roger-Melo!

Show de bola, fiquei muito feliz com o feedback :)

As observações fizeram sentido como de costume.

Obrigado e boas festas!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)

Feliz 2022! 🎉
