### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#261]
Podemos utilizar estes operadores lógicos para combinar condições em uma única verificação.

- *"E"* *&&* verifica se **duas** condições resulta em *true;*
- *"OU" ||* verifica se apenas **uma** das condições resulta em *true*.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! 🔥
