### ISSUE TITLE
Resumo da Aula Herança entre classes - Aula 02-08 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2610]
O conceito de herança entre classes, nada mais é do que fazer com que uma subclasse herde propriedades e métodos de uma outra classe. A herança é indicada através da palavra chave `extends`. São herdadas propriedades e métodos da classe principal. Vamos ver na prática como fica a herança, mesmo que a classe que está herdando esteja vazia:

```jsx
class Mammal {
	constructor(species, name, age) {
		this.species = species;
		this.name = name;
		this.age = age;
		this.mammaryGland = true;
	}

	incrementAge() {
		this.age++;
	}
}

class Lion extends Mammal {}

const mufasa = new Lion('leão', 'Mufasa', 7);

console.log(mufasa);
```

O código acima funcionará corretamente, mesmo que na classe `Lion` não haja uma linha de código. Isso porque ela está herdando todas as propriedades e métodos da classe `Mammal`. Porém se for necessário adicionar uma propriedade que apenas a classe `Lion` tenha, e também adicionar um método que somente esta classe tenha, então precisamos indica-las dentro da nossa nova classe. No construtor precisamos invocar o `constructor` da classe principal mas utilizando a palavra chave `super`, e o método é declarado normalmente, como qualquer outro. Vamos ver na prática como ficaria:

```jsx
class Mammal {
	constructor(species, name, age) {
		this.species = species;
		this.name = name;
		this.age = age;
		this.mammaryGland = true;
	}

	incrementAge() {
		this.age++;
	}
}

class Lion extends Mammal {
	constructor(species, name, age, manEater) {
		super(species, name, age);
		this.manEater = manEater;
	}

	eatZebras(animals) {
		return animals.filter(animal => animal.species !== 'zebra');
	}
}

const mufasa = new Lion('leão', 'Mufasa', 7, false);

console.log(mufasa);
```

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🎯
