### ISSUE TITLE
Resumo da Aula 01-03 Timestamp e comparações da etapa 10

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2618]
- Podemos utilizar para realizar **comparações** entre datas distintas (passado, futuro);
- Para podermos encontrar algum dado referente a data ou dia devemos converter os milissegundos para (segundos, minutos, horas, dias);
- Podemos utilizar uma data especifica dentro de uma string, como argumento tem que estar com algum formato válido;
- O **timestamp** não é um objeto de data, devemos **converter** ele, para isto utilizaremos o (timestamp) como argumento na função construtura **new Date(timestamp);**
```js
const past = new Date('May 1 2020 7:47:00')
const presentDay = new Date()

const difference = presentDay.getTime() - past.getTime()
console.log(difference)

const seconds = Math.round(difference / 1000)
console.log({ seconds }) //{seconds: 52313398}

const minutes = Math.round(seconds / 60)
console.log({ minutes }) //{minutes: 871890}

const hours = Math.round(minutes / 60)
console.log({ hours }) //{hours: 14532}

const days = Math.round(hours / 24)
console.log({ days }) //{days: 606}

console.log(`Escrito há ${days} dias`) //Escrito há 606 dias

//descobrir a data 
const timestamp = 52310940117 /* não é um obj de data temos que converter utilizando 
ele como argumento do new date(timestamp)*/
console.log(new Date(timestamp)) //Sun Aug 29 1971 07:49:00 GMT-0300 (Horário Padrão de Brasília)
```

**Comment by Roger-Melo** [comment]
Excelente @carlosdevjs, rumo à fluência! 🎯
