### ISSUE TITLE
Aplicação: Weather App - Etapa 12

### ISSUE THREAD

**Issue by LordMan0** [roger-melo-treinamentos/curso-de-js-roger-melo#262]
### **Weather App**

**Maiores dificuldades**
As maiores dificuldades foram descobrir o motivo do erro causado pela requisição, no qual a maioria era por causa do url escrito de maneira errada ou por causa do nome da cidade ter sido escrito de maneira errada (ou até mesmo pelo fato de ter alcançado o limite de requisições por dia no API). Era bem confuso saber o porquê do aplicativo não funcionar quando o erro se tratava da requisição. Também tive um pouco de dificuldade ao usar os códigos de manipulação do DOM (devido mais por não recordar alguns métodos que podiam facilitar)

**Menores dificuldades**
As menores dificuldades foi do código em si: procurar e utilizar do site da API (Accu Weather), fazer a estrutura da requisição seguindo o modelo da aula, colocar o weather.js antes do app.js no index.html, referenciar constantes ligadas ao DOM, fazer a estrutura do event listener (inclusive com o preventDefault e reset), obter o valor do input, enviar para a requisição, obter a resposta da requisição parseada e utilizar dos dados obtidos para colocar na interface do app, de acordo com design determinado para cada condição ( se está de noite ou de dia).

O link abaixo apresenta o repositório em que o app está contido:
https://github.com/LordMan0/programa-js/tree/main/weather-app-main/Weather%20app

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Passando para avisar que sua issue foi visualizada e que a análise da aplicação já está sendo feita e em breve será publicada aqui =)

@LordMan0

**Comment by LordMan0** [comment]
Okay 👍 =)

**Comment by LordMan0** [comment]
Tive que arrumar um erro de declaração de const, mas acho que agora deu certo!
https://github.com/LordMan0/programa-js/tree/main/weather-app-main/Weather%20app

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal Gabriel.

Parabéns pelo esforço em construir mais uma aplicação =)

Considerando que você a construiu sozinho, é perceptível a sua evolução desde a primeira aplicação até aqui.

A interface ficou bacana e mesmo tendo que revisar mecanismos de seleção de elementos do DOM, desta vez você evitou usar ids e preferiu usar `data-*`.

No geral, a nomenclatura das variáveis e funções também estão mais descritivas.

Minhas duas únicas observações são as seguintes...

A const `weatherDetails` foi declarada mas não está sendo usada no decorrer da aplicação, então ela pode ser removida.

Ainda há a possibilidade de `changeTheColorByDayTime` ser mais descritiva. Como o tema de cores da aplicação está sendo modificado dependendo se é dia ou noite, `updateColorTheme` ou `updateColorThemeAccordingWithDaytime` (se não se importar com nomes extensos) podem ser escolhas mais descritivas.

---

Continue aplicando o método. Tenho certeza que em breve você alcançará os objetivos que deseja ao se tornar fluente em JavaScript.

E claro, no que eu puder ajudar, pode contar comigo =)

Ficaram claras as observações que fiz acima?

@LordMan0

**Comment by Roger-Melo** [comment]
Excelente @LordMan0. Recomendo que você veja a aula inaugural para identificar em que ponto da jornada você está. Inclusive, nela eu falo sobre o momento em que você deve começar a dar passos mais práticos rumo ao seu objetivo como Desenvolvedor =)

**Comment by LordMan0** [comment]
Beleza, farei isso! 
Vlw, professor (^_^)/
