### ISSUE TITLE
Como acessar objetos que não estão armazenados em uma variável

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#2633]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Olá, Roger!
Minhas dúvidas surgiram durante a correção do exercício 09.
Enunciado:
 09)
- Crie uma função que recebe um parâmetro 'type';

- Dentro da função, crie um objeto com as seguintes propriedades:

- null, que recebe a mensagem 'Seta, explicitamente, uma variável sem valor.'

- undefined, que recebe a mensagem 'Representa um valor não-setado.'

- object, que recebe a mensagem 'Arrays, Datas, Objetos literais, Funções, etc.'

- Se o valor que o parâmetro type receber corresponder à alguma das 3  

- propriedades, retorne a mensagem que a propriedade armazena;

- Teste a função, exibindo no console a mensagem de cada propriedade.

Nele você mostra uma segunda maneira de resolver o que foi proposto:
```js
const getTypeDefinition = type => {
  return {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }[type] 
}
```
Até o momento eu achava que para acessar alguma propriedade de um objeto eu precisava do nome da variável que o armazena, por exemplo ```variável.name``` acessa a propriedade name do objeto variável. Mas nessa questão ele não está armazenado em local nenhum correto? É possível/habitual criar objetos sem armazena-los em uma variável? Se sim, como faço para acessar suas propriedades?

Na primeira vez que fiz essa questão, tentei resolver desse modo:
```js
const whichIsType = type => {
  let types = {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }

  if(typeof type === 'null') {
    return types.null
  }else if(typeof type === 'undefined') {
    return types.undefined
  }else if(typeof type === 'object') {
    return types.object
  }
}
let valor = null
console.log(whichIsType(valor))
```
Por que quando faço a verificação do tipo ```null``` retorna a frase contida na propriedade object e não a que está na propriedade null? 
Achava que a única diferença entre os tipos ```undefined ``` e  ```null``` seria que o primeiro é setado automaticamente pelo JS enquanto que null era definido por quem está programando. Mas quando utilizo o typeof em ambos um me retorna object e o outro undefined.

Está um pouco confuso na minha cabeça o Tipo de Dado object  com objeto literais { }, poderia explicar a diferença entre eles?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira.

> ## Até o momento eu achava que para acessar alguma propriedade de um objeto eu precisava do nome da variável que o armazena, por exemplo ```variável.name``` acessa a propriedade name do objeto variável. Mas nessa questão ele não está armazenado em local nenhum correto?

Execute o código abaixo comigo:

```javascript
console.log({ prop1: 1 }.prop1) // 1
```

O objeto não precisou ser armazenado em uma variável. O que aconteceu é que imediatamente após a criação dele em memória, `.prop1` acessa a propriedade do objeto =)

O mesmo acontece na função `getTypeDefinition`. A diferença é que nesse caso, para acessar a propriedade do objeto, é necessário usar a notação de colchetes:

```javascript
const getTypeDefinition = type => {
  return {
    null: 'Seta, explicitamente, uma variável sem valor.'
  }[type]
}

console.log(getTypeDefinition('null')) // 'Seta, explicitamente, uma variável sem valor.'
```

Observe que se a notação de ponto for usada, uma propriedade `type` será buscada dentro do objeto e, como essa propriedade não existe nele, `undefined` é retornado:

```javascript
const getTypeDefinition = type => {
  return {
    null: 'Seta, explicitamente, uma variável sem valor.'
  }.type
}

console.log(getTypeDefinition('null')) // undefined
```

Sempre que vc precisar acessar uma propriedade usando um parâmetro/variável ou alguma expressão, precisará usar a notação de colchetes. 

Dá uma olhada [nessa resposta](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563#issuecomment-999110064) e se ainda restar alguma dúvida em relação a pq e quando usar essa notação, pode comentar aqui abaixo que te ajudo =)

---

> ### É possível/habitual criar objetos sem armazena-los em uma variável? Se sim, como faço para acessar suas propriedades?

Em etapas mais avançadas, vc irá entender formas mais concisas de escrever um código.

Então se é ou não habitual vai depender de como vc quer expressar seu código.

Observe que o código abaixo é perfeitamente válido e, não foi necessário o objeto ser armazenado em uma variável/parâmetro:

```javascript
const getObj = () => {
  return { getProp: 'my prop' }
}

console.log(getObj().prop) // my prop
```

Em JS, objetos são valores que podem ser passados de um lugar para outro em sua aplicação. 

Se vc vai ou não armazená-lo, é uma escolha sua. Não se preocupe  muito com isso agora, vc ainda será exposto à vários casos de uso no decorrer do treinamento.

É claro que `getObj().prop` não é lá a expressão mais legível, mas quis mostrar apenas para vc perceber que é perfeitamente possível fazer isso =)

---

> ### Por que quando faço a verificação do tipo ```null``` retorna a frase contida na propriedade object e não a que está na propriedade null? 

É seguro usar `typeof` apenas em funções e valores primitivos (exceto `null`).

Observe que nas aulas, eu só uso `typeof` para testar funções e valores primitivos, exceto `null`.

Testar `null` com o `typeof` retorna 'object' (mesmo `null` sendo um tipo primitivo). 

```javascript
console.log(typeof null) // 'object'
```

Isso é um erro de implementação na linguagem. Infelizmente, é um bug que não pode ser corrigido, pois quebraria códigos em produção.

Em aulas mais avançadas, vc descobrirá como ter um resultado mais apurado ao testar `null` e objetos. Não se preocupe com isso agora =)

Ficou mais claro?

**Comment by BrunodevOliveira** [comment]
Sim, Roger! Muito obrigado!
