### ISSUE TITLE
Problema com o Netlifly

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2634]
### Etapa da aula

13

### Nome da aula

Correção dos exercícios da aula 02 da etapa 12 - Aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1512295

### Descreva a dúvida

Olá Roger! Eu tentei upar a Weather Aplication no Netlifly, mas por algum motivo, nada funciona. No entanto, quando eu utilizo o vscode, funciona normalmente. 

Link da aplicação: https://github.com/YureK-a/CJRM/tree/main/Weather%20Aplication
Link do site do Netlifly: https://practical-nobel-96a08d.netlify.app

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

Pelo que vi, não é que nada funciona. 

Ao enviar o form, o erro abaixo é exibido, certo?

![image](https://user-images.githubusercontent.com/29297788/147687854-b16d2a65-90ae-4a0b-8ab5-13768716d130.png)

Sempre seja específico ao descrever o que não está funcionando, isso é importante para comunicar o problema não apenas aqui no treinamento, mas para seu time, ok? =)

Acrescente um "s" no final de `http` e suba o app para o Netlify novamente:

```javascript
// antes
const baseUrl = 'http://dataservice.accuweather.com/'
```

```javascript
// depois
const baseUrl = 'https://dataservice.accuweather.com/'
```

Me avise aqui se resolveu =)

**Comment by YureK-a** [comment]
Resolvido! Desculpe pelo inconveniente, serei mais claro das próximas vezes. Obrigado pela ajuda! =)
