### ISSUE TITLE
Variável criada com VAR fica disponível fora do escopo de bloco

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#2636]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/831886

### Descreva a dúvida

Olá, Roger!
Durante a aula "Variáveis e  Escopo de bloco - Aula 02-02" vc utilizou o exemplo a baixo para mostrar que uma variável criada com a palavra-chave ```var``` conseguiria ser acessada fora do bloco em que foi criada. 
```js
const age = 31

if(true) {
    const age = 41
    console.log(`dentro do 1° bloco de código: ${age}`)
    
    if(true) {
        const age = 51
        var test = 'oi'
        console.log(`dentro do 2° bloco de código: ${age}`)
    }
}
console.log(`fora do bloco de código: ${age} ${test}`) //Retorna "31 e oi"
```
Tentei replicar o exemplo a cima na questão 02, mas não consigo acessar a variável ```age``` que foi criada dentro da função ```displayAge```. Me retorna o seguinte erro: ReferenceError: age is not defined

```js
const displayAge = () => {
  var age = 29 
  console.log(age)
}
 console.log(age) 
```
Pesquisei um pouco sobre Escopos e encontrei algo relacionada a Escopo de Função.. Pelo que li, as funções tbm possuem seu escopo e as variáveis criadas dentro dessa função não são acessíveis fora dela. Achei bem semelhante ao Escopo de bloco, com a diferença de que variáveis criadas com var são acessíveis fora do bloco, enquanto que no escopo de função não. 
Isso está correto?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira!

O que vc viu nessa aula é apenas uma introdução. 

Ao chegar na etapa 05, vc encontrará a aula [3 escopos em JavaScript que você deve conhecer - Aula 01-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/842111) em que falo com mais detalhes sobre escopo. Inclusive o escopo de função =)

Se depois de acompanhar essa aula restar alguma dúvida sobre o assunto, pode abrir uma nova issue que te ajudo, combinado? =)

**Comment by BrunodevOliveira** [comment]
Beleza, Roger! Obrigado!
