### ISSUE TITLE
Dúvida sobre o método reduce

### ISSUE THREAD

**Issue by danielscastro** [roger-melo-treinamentos/curso-de-js-roger-melo#2641]
### Etapa da aula

8

### Nome da aula

Aula 01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/991052

### Descreva a dúvida

Minha dúvida é simples. Não sei se foi respondida em alguma das aulas, certamente não lembro. Quando estava resolvendo o exercício de somar a quantidade de pessoas que assistiu somente os filmes da Disney, me deparei com essa solução, que funciona:

```
const totalDisneyWatches = topBrazilMovies
.filter(movie => movie.distributedBy === 'Disney')
.reduce((acc, movie) => ++acc, 0)
```

Reparei que o acumulador só funciona se ficar com a acumulação antes da invocação dele mesmo (++acc), se ficar após (acc++), a função retorna 0. Por quê?

@Roger-Melo
![WhatsApp Image 2021-12-27 at 14 53 04](https://user-images.githubusercontent.com/62402373/147712393-319b86c5-a7cb-41df-ba7e-c8e28cf0d420.jpeg)

**Comment by Roger-Melo** [comment]
Olá @danielscastro!

Isso não tem relação com o `reduce`. 

Na real, isso acontece devido à uma diferença na forma que operadores de pós e pré-incremento funcionam.

Dá uma olhada [nessa resposta](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1867#issuecomment-924516881) que dei para um aluno que teve essa mesma dúvida.

Se restar alguma dúvida, pode comentar aqui abaixo que te ajudo =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
