### ISSUE TITLE
Aplicação: Quiz musical

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2642]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Jonatan1103/estudo-musical.git

### Maiores dificuldades durante a implementação

- refatoração: acho que poderia ter ficado melhor, não sei se é por falta de confiança.
- bootstrat: por nuca ter usado, na hora de mudar as cores bati a cabeça até lembrar que eu poderia usar o CSS normal para alterar algumas coisas. acredito que não foi o correto a ser feito, mas foi a alternativa que encontrei kkkkkk.
- git: por não saber usar o git, consegui apagar o código na primeira vez que fui enviar, tiver que refazer tudo de novo, o lado bom é que fixou algumas coisas...kkkkk

### Menores dificuldades durante a implementação

não que tenha sido fácil, longe disso. Mas foi a questão do código em si. acredito que tenha sido por causa que a aula estava fresca na memória.

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### refatoração: acho que poderia ter ficado melhor, não sei se é por falta de confiança.

Não se preocupe com refatoração agora.

Num primeiro momento, o mais importante é fazer funcionar. Como você fez =)

Refatoração é uma habilidade que é elevada com a prática. E vc ainda irá praticar bastante durante o treinamento.

> ### bootstrat: por nuca ter usado, na hora de mudar as cores bati a cabeça até lembrar que eu poderia usar o CSS normal para alterar algumas coisas. acredito que não foi o correto a ser feito, mas foi a alternativa que encontrei kkkkkk.

O uso do Bootstrap ou qualquer outra lib CSS é opcional. Use o que ficar mais confortável para vc. 

> ### git: por não saber usar o git, consegui apagar o código na primeira vez que fui enviar, tiver que refazer tudo de novo, o lado bom é que fixou algumas coisas...kkkkk

Então foi um presente =D

---

Pelo seu código, vc pegou bem a lógica até aqui. 

A principal habilidade que seu código evidencia que precisa ser trabalhada em vc é a de nomeação. 

Portanto, a maioria dos ajustes da análise serão focados neste aspecto =)

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Porém, ali em baixo vou fazer uma observação sobre o array `answers`.

Você deixou claro o quanto de progresso o usuário teve no quiz ao inserir a porcentagem de acertos. Isso é bom para a usabilidade.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`paragraph` pode ser renomeada para `scoreMessage`. Isso descreve de forma mais objetiva qual papel o elemento que essa const armazena tem na aplicação.

```javascript
// antes
const paragraph = document.querySelector('.result')

// ...

paragraph.textContent = `Você acertou ${score}% do quiz`
```

```javascript
// depois
const scoreMessage = document.querySelector('.result')

// ...

scoreMessage.textContent = `Você acertou ${score}% do quiz`
```

A partir do momento em que há 2 botões no arquivo, vc precisa deixar claro qual botão é qual. Isto é, vc precisa ser específico sobre qual botão a const está armazenando. 

Para especificar que `button` armazena a referência do botão de envio do quiz, vc pode renomeá-la como `buttonQuizSubmit`. 

Já para deixar claro que `buttonResult` na verdade armazena o botão que fecha o popup, vc pode nomeá-la como `buttonClosePopup`. Pegou o raciocínio? 

E eu tô ligado que o clique nesse último botão também recarrega a página, mas não é lá muito recomendável nomear um botão `buttonClosePopupAndReloadPage`. É necessário especificar apenas uma ação que o botão faz. Sendo assim, especifique a ação mais significativa.

```javascript
// antes
const button = document.querySelector('.btn')
const buttonResult = document.querySelector('.popup-button')

// ...

button.addEventListener(/* ... */)
buttonResult.addEventListener(/* ... */)
```

```javascript
// depois
const buttonQuizSubmit = document.querySelector('.btn')
const buttonClosePopup = document.querySelector('.popup-button')

// ...

buttonQuizSubmit.addEventListener(/* ... */)
buttonClosePopup.addEventListener(/* ... */)
```

`answers` também não é um nome específico o suficiente. 

Se a const armazena as **respostas corretas**, nomeie-a como `correctAnswers`. 

Observe que o parâmetro do callback do forEach também precisa ter um nome coerente em relação ao array no qual o forEach foi encadeado.

```javascript
// antes
const answers = ['A', 'B', 'A', 'B']

// ...

answers.forEach((answer, index) => {
  // ...
})
```

```javascript
// depois
const correctAnswers = ['A', 'B', 'A', 'B']

// ...

correctAnswers.forEach((correctAnswer, index) => {
  // ...
})
```

`answersUser` é um substantivo. O ideal é que o nome de uma função seja um verbo. 

Como essa função desencadeia várias ações e a função que exibe o score (ação mais significativa ao enviar o form) já está sendo invocada em um outro momento, essa função pode ter um nome que apenas especifica que ela lida com o envio do quiz. 

`handleQuizSubmit`, por exemplo.

```javascript
// antes
const answersUser = event => {
  // ...
}

// ...

form.addEventListener('submit', answersUser)
```

```javascript
// depois
const handleQuizSubmit = event => {
  // ...
}

// ...

form.addEventListener('submit', handleQuizSubmit)
```

`compareAnswers` já é um nome descritivo. `calculateScore` pode descrever de forma mais específica a ação que a função executa.

```javascript
// antes
const compareAnswers = (arrayUserAnswers) => {
  // ...
}

const handleQuizSubmit = event => {
  // ...
  compareAnswers(userAnswers)
}
```

```javascript
// depois
const calculateScore = (arrayUserAnswers) => {
  // ...
}

const handleQuizSubmit = event => {
  // ...
  calculateScore(userAnswers)
}
```

Observe que nomear o parâmetro da função como `arrayUserAnswers` é desnecessário, pois a invocação da função recebe um argumento `userAnswers`.

Quando o parâmetro de uma função tem o mesmo nome do argumento que foi inserido na invocação dela, isso intensifica a coerência na leitura do código.

```javascript
// antes
const calculateScore = (arrayUserAnswers) => {
  // ...
}

// ...

calculateScore(userAnswers)
```

```javascript
// depois
const calculateScore = (userAnswers) => {
  // ...
}

// ...

calculateScore(userAnswers)
```

`showMessage` pode ficar mais específica se for nomeada como `showScoreMessage`.

```javascript
// antes
const showMessage = score => {
  // ...
}

const calculateScore = (userAnswers) => {
  // ...

  showMessage(score)
}
```

```javascript
// depois
const showScoreMessage = score => {
  // ...
}

const calculateScore = (userAnswers) => {
  // ...

  showScoreMessage(score)
}
```

## Inconsistência de code-styling

Dá uma olhada nas declarações das funções abaixo e me diz se vc percebe alguma inconsistência:

```javascript
const showScoreMessage = score => {
  // ...
}

const calculateScore = (userAnswers) => {
  // ...
}
```

Se a arrow function tem apenas 1 parâmetro, ele não precisa estar entre parênteses. Isso eu sei que vc sacou.

Porém, vc precisa ser consistente nas escolhas que faz em seu código.

Ou vc declara arrow functions com apenas 1 parâmetro usando parênteses, ou as declara sem parênteses. 

Seja qual for a sua escolha, seja consistente com ela no decorrer do código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Jonatan1103** [comment]
Muito sentido. pequena troca de palavras já deram mais legibilidade ao código. Pretendo fazer um curso de inglês pois sei que será essencial para a área. obrigado pelas informações passadas.

**Comment by Roger-Melo** [comment]
Show Jonatan!

Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
