### ISSUE TITLE
Resumo da Aula Buscando e filtrando to-dos 02-03 da etapa 09

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2650]
Para realizar a busca por um determinado item da lista, inicialmente é adicionado um _event listener_ no _input_ que é usado para a entrada da pesquisa. Este _addEventListener_ irá acompanhar a entrada caractere por caractere (o tipo de evento é ‘input’).
```js
inputSearchToDo.addEventListener(‘input’, event =>{ instruções })
```
De modo a detectar a sentença que corresponda a um item da lista e somente este item seja exibido e os demais ocultados, dentro da função _callback_, usamos o elemento pai e referenciamos seus filhos (_lis_), armazenando-os em um _array_ para então aplicarmos o método _**filter()**_, que receberá a função responsável pela comparação entre o _textContent_ de cada _li_ e o valor do _input_. No _array_ gerado pelo _filter()_, encadeamos o _**forEach()**_ para iterar por cada item dele, manipulando as classes que desejamos inserir e remover, e assim alterarmos a visibilidade dos itens da lista.

Para que o código não leve em conta diferenças entre letras maiúsculas e minúsculas, convertemos em minúsculas tanto o valor inserido no _input_ quanto o _textContent_ dos elementos _lis_ da lista antes de efetuar as iterações, bem como inserir o _trim()_ no valor de _input_ para remover possíveis espaços vazios.
```js
const inputValue = event.target.value.trim().toLowerCase() // toma o valor de target como referência, removendo espaços em branco e convertendo tudo em minúscula
Array.from(todosContainer.children) // toma o container como referência para pegar os elementos filhos (lis) e converter em um array
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue)) // converte em minúscula e retorna os arrays que não contêm o valor do input
    .forEach(todo => {
      todo.classList.remove('d-flex') // necessário remover esta classe, pois ela se sobrescreve e atrapalha o correto funcionamento deste bloco de código
      todo.classList.add('hidden')
    }) // insere a classe hidden nos elementos que serão ocultados

    Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue)) // retorna os arrays que CONTÊM o valor do input, para que apareçam novamente quando damos alteramos o input
    // console.log(todo.textContent)
    .forEach(todo => {
      todo.classList.remove('hidden') // 
      todo.classList.add('d-flex')
    })
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. vamo que vamo, rumo à fluência! 🙌
