### ISSUE TITLE
Resumo da Aula Funções construtoras - Aula 03-06 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2653]
Em JavaScript, as classes são na verdade um *syntax sugar* de funções construtoras. Por baixo dos panos, as funções construtoras é que são utilizadas. Vamos ver um exemplo de uma classe e como ela é escrita no formato de função construtora:

```jsx
// classe
class Student {
	construct(name, email) {
		this.name = name
		this.email = email
	}
}

// função construtora
function Student(name, email) {
	this.name = name
	this.email = email
}
```

A função construtora utiliza a palavra-chave function na sua declaração e tem o nome declarado com a primeira letra em maiúscula por convenção, para que quando a olharmos, sabermos que se trata de uma função construtora.

Os métodos também tem um formato diferente dentro das funções construtoras. Fazemos o uso da palavra-chave `this` seguida de ponto e do nome do método, que recebe uma *function declaration*. Não que o uso de *arrow function* não funcione, mas como se trata de uma maneira mais antiga de ser escrita, o normal é encontrar funções construtoras utilizando *functions declarations*.

```jsx
// classe
class Student {
	construct(name, email) {
		this.name = name
		this.email = email
	}

	login() {
		return `${this.name} está logado`;
	}
}

// função construtora
function Student (name, email) {
	this.name = name
	this.email = email

	this.login = function () {
		return `${this.name} está logado`;
	}
}
```

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. vamo que vamo, rumo à fluência! 🙌
