### ISSUE TITLE
Aplicação: Quiz games preferidos

### ISSUE THREAD

**Issue by Edersongoncalves** [roger-melo-treinamentos/curso-de-js-roger-melo#2654]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Edersongoncalves/curso_roger_melo_quiz.git

### Maiores dificuldades durante a implementação

Uma das minhas maiores dificuldade é:
criar os nomes das variaveis em inglês: 
 Obs: 
não sei quase nada eu vou no google tradutor e vou me virando, o bom que ja vai forçando o aprendisado,  qual a sua dica disso ?.
na hora de refatorar o codigo:
Obs:
na hora de refatora o bicho pega porque quando fica pronto sem refatora eu tenho a impressão que pra mim eu consigo ler melhor, mais eu tambem penso que é porque foi eu quem escreveu kkkk e depois que refatoro o codigo eu preciso ficar relendo pra entender isso é normal?

### Menores dificuldades durante a implementação

tirando as dificuldades descrita a cima o resto foi normal, quando tenho dividas volto nas aulas  e anotações.

**Comment by Roger-Melo** [comment]
Olá @Edersongoncalves.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Edersongoncalves!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Muito legal o tema do Quiz. Horizon Zero Down parece ser um excelente jogo, quero jogá-lo.

---

> ### não sei quase nada eu vou no google tradutor e vou me virando, o bom que ja vai forçando o aprendisado, qual a sua dica disso ?.

A importância de estudar inglês na sua carreira como Dev deve estar alinhada com seus objetivos.

Se o seu objetivo de médio prazo é ganhar em moeda forte (dollar ou euro), planeje-se para fazer um bom curso de inglês.

E com bom curso de inglês eu quero dizer: método que tenha resultados comprovados.

[Este treinamento](http://www.mairovergara.com/curso-de-ingles-mairo-vergara/) tem uma tonelada de casos de sucesso.

Mas primeiro, eu recomendo que vc foque em chegar na fluência em JavaScript.

Em seguida, vc foca no inglês =)

---

> ### na hora de refatora o bicho pega porque quando fica pronto sem refatora eu tenho a impressão que pra mim eu consigo ler melhor, mais eu tambem penso que é porque foi eu quem escreveu kkkk e depois que refatoro o codigo eu preciso ficar relendo pra entender isso é normal?

Sim, isso é natural. Principalmente quando vc olha pro mesmo código durante horas. 

Por isso, é importante fazer uma pausa (ocupando a cabeça com outra coisa) e depois voltar e/ou ter outra pessoa para olhar o código.

Porém, num primeiro momento, o mais importante vc já fez, que é fazer funcionar =)

Não se preocupe muito com refatoração agora. Refatoração é uma habilidade que é elevada com a prática. 

Conforme vc praticar, vc vai percebendo aos poucos o que pode ser melhorado.

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Mais clareza para o usuário

Quando o usuário envia o quiz, seria legal exibir o total de pontos que o quiz tem. Assim vc deixa mais claro para o usuário o quão bem ele foi em relação à pontuação total. 

Exemplos: 

- "Você acertou 75% do quiz"
- "Você acertou 3/4 do quiz"

---

## Local da exibição dos pontos

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte superior (não-visível) da tela:

![image](https://user-images.githubusercontent.com/29297788/147928156-363283ab-eab4-40ff-a0fe-0dfd9c1df44c.png)

Uma possível solução para isso é exibir os pontos em um local em que o usuário está olhando no momento do envio. Pode ser, por exemplo, logo acima do botão "Enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

---

## Comentários

Não é uma regra, mas evite deixar comentários no código, como abaixo.

```javascript
// log(form);
// log(answers_of_user);
// log(button_send);
```

Talvez vc os tenha esquecido, mas vou aproveitar a oportunidade para deixar claro o seguinte...

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Um outro ponto a conseiderar é que, se o código e legível, ele dispensa comentários.

---

## Local de declarações de variáveis

No código abaixo, não há uma separação visual entre a const que armazena elemento do DOM, a que armazena array e a que armazena uma função.

```javascript
// antes
const log = value => console.log(value)
const form = document.querySelector('.quiz-form')
const answers_certanin = ['B', 'B', 'B', 'B']
```

Você pode organizar essas consts, separando-as pelo tipo de valor que elas armazenam.

```javascript
// depois
const form = document.querySelector('.quiz-form')

const answers_certanin = ['B', 'B', 'B', 'B']

const log = value => console.log(value)
```

Assim, o topo do código fica com a declarações de consts que armazenam elementos do DOM, mais abaixo vc deixa as consts que armazenam outro tipo de valor (array, neste caso), no meio do código vc deixa as declarações de funções e, por último, os listeners de evento. Essa é a forma mais simples de organizar um código de uma aplicação web com JS puro =)

---

## Escopo

Um princípio que gosto de seguir é: deixe as declarações de suas variáveis perto de onde elas são usadas.

Porém, nem sempre esse princípio deve ser aplicado. Por questões de escopo.

Um exemplo clássico é quando vc tem duas funções que precisam acessar a mesma variável.

No código abaixo, func1 e func2 acessam myConst normalmente:

```javascript
const myConst = 'my value'

const func1 = () => {
  console.log(myConst)
}

const func2 = () => {
  console.log(myConst)
}

func1() // 'my value'
func2() // 'my value'
```

Porém, se myConst é declarada dentro de func1, func2 não consegue acessar myConst por que myConst agora é acessível apenas dentro do escopo de func1:

```javascript
const func1 = () => {
  const myConst = 'my value'
  console.log(myConst)
}

const func2 = () => {
  console.log(myConst)
}

func1() // 'my value'
func2() // app.js:7 Uncaught ReferenceError: myConst is not defined
```

Esse é um caso onde myConst precisa estar em escopo global, para que ela seja acessada dentro das duas funções. 

Mais à frente, vc começará a ver por que variáveis globais não são uma boa ideia. Mas por enquanto, isso não é importante. 

Um outro caso que vc precisa considerar é o escopo de bloco...

Lembra que não há problema em duas consts de mesmo nome serem criadas em escopos diferentes?

No código abaixo, 

```javascript
const myFunc = () => {
  const myConst = 'my value'
  console.log(myConst)
}

myFunc()
myFunc()
```

a cada vez que `myFunc` é invocada, o bloco que contém a declaração da const e o console.log é executado, certo?

Blocos criam escopos. 

Isso significa que na primeira vez que myFunc foi invocada, um escopo com a const myConst foi criado. E na segunda vez em que ela foi invocada, um outro escopo com uma outra const myConst foi criado.

Ou seja, se `myFunc` é invocada 2x, duas consts `myConst` foram criadas em memória.

E isso é importante pelo seguinte...

Copie o código abaixo e execute ele:

```HTML
<div></div>
<button>Adicionar parágrafo</button>
```

```javascript
const div = document.querySelector('div')
const button = document.querySelector('button')

const paragraph = document.createElement('p')

button.addEventListener('click', () => {
  div.appendChild(paragraph)
})
```

Ao executar esse código e clicar no botão pela primeira vez, vc verá que um `<p>` fio adicionado dentro da `<div>`.

Porém, do segundo clique em diante, não são adicionados novos `<p>`.

Por que isso acontece?

Isso acontece por que a cada execução do callback de clique, o `paragraph` ao invés de ser criado novamente está apenas sendo reaproveitado.

Ou seja, como `paragraph` foi declarado fora do escopo do callback, a cada execução do bloco do callback, o mesmo parágrafo está sendo inserido dentro da div.

Lembre-se: quando um callback de listener de evento é executado, ele não faz o código que está fora dele ser declarado novamente. Apenas o bloco do callback é executado novamente. Isso significa que o mesmo `paragraph` está sendo usado dentro do callback.

Agora, se `paragraph` for declarado dentro do callback,

```javascript
button.addEventListener('click', () => {
  const paragraph = document.createElement('p')
  div.appendChild(paragraph)
})
```

toda vez que esse bloco do callback for executado, um novo `paragraph` será criado em memória e inserido como filho da div. Ou seja, o segundo clique no botão irá inserir um segundo `<p>` como filho da div, um terceiro clique irá inserir um terceiro `<p>` e assim por diante. Graças ao escopo de bloco =)

Ficou claro?

Considerando isso...

`h2_question` pode ser declarada no topo do código para que uma busca no DOM não seja feita à cada execução do callback de submit do form.

E `create_paragraph` pode ser declarada no topo do código para que outros parágrafos não sejam criados novamente à cada execução do callback de submit do form.

```javascript
// antes
form.addEventListener('submit', event => {
  // ...

  const h2_question = document.querySelector('#questions')
  const create_paragraph = document.createElement('p')

  // ...
})
```

```javascript
// depois
const form = document.querySelector('.quiz-form')
const h2_question = document.querySelector('#questions')
const create_paragraph = document.createElement('p')

// ...

form.addEventListener('submit', event => {
  // ...
  h2_question.insertAdjacentElement(/* ... */)
  create_paragraph.setAttribute(/* ... */)
  create_paragraph.textContent = /* ... */
})
```

---

## Formatação pode ser mais perigosa do que parece

Tenha atenção com a formatação que o texto precisa ter.

Parece algo bobo, mas observe abaixo que o primeiro caractere da template string é um espaço em branco. E isso significa que faltou atenção aos detalhes aqui.

```javascript
create_paragraph.textContent = ` Seu score: ${score}`
```

O diabo está nos detalhes. 

Se um recrutador mais exigente vê esse tipo de erro em um teste, ele pode assumir que vc não tem atenção a detalhes e isso pode te prejudicar no processo.

---

## Ordem importa

A ordem de cada manipulação do create_paragraph importa. 

Não importa muito em termos de performance, mas sim do ponto de vista de organização do código.

```javascript
// antes
form.addEventListener('submit', event => {
  // ...
  
  h2_question.insertAdjacentElement('afterend', create_paragraph)
  create_paragraph.setAttribute('class', 'bg-warning text-center display-4 lead font-weight-normal text-success')
  create_paragraph.textContent = `Seu score: ${score}`
})
```

Ao invés de inserir o elemento na página, setar as classes e depois o texto, faz mais sentido inserir o texto no elemento, setar as classes e só então, inserir ele na página.

```javascript
// depois
form.addEventListener('submit', event => {
  // ...
  
  create_paragraph.textContent = `Seu score: ${score}`
  create_paragraph.setAttribute('class', 'bg-warning text-center display-4 lead font-weight-normal text-success')
  h2_question.insertAdjacentElement('afterend', create_paragraph)
})
```

---

## `console.log`

O `console.log` é útil apenas no momento em que você está desenvolvendo. 

Sei que vc deve ter usado para visualizar algum valor e esquecido, mas sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

Não faz sentido executar uma exibição no console a cada execução do callback do forEach, como abaixo.

```javascript
  answers_of_user.forEach((user_answer, index) => {
    if (user_answer === answers_certanin[index]) {
      score += 25
      log(user_answer) // ❌ remova essa linha
    }
  })
```

---

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

`h2_question` pode ser nomeada como `quiz_title` por duas razões: 

1. h2 pode ser substituído por h1 (por exemplo) e aí o nome da const perde o sentido. 
2. question pode dar a entender que a const armazena uma pergunta do quiz.

```javascript
// antes
const h2_question = document.querySelector('#questions')

// ...

form.addEventListener('submit', event => {
  // ...

  h2_question.insertAdjacentElement('afterend', create_paragraph)
})
```

```javascript
// depois
const quiz_title = document.querySelector('#questions')

// ...

form.addEventListener('submit', event => {
  // ...

  quiz_title.insertAdjacentElement('afterend', create_paragraph)
})
```

Observe tb que `#questions` contém apenas um título, então não faz sentido o id ser nomeado no plural.

---

`create_paragraph` é verbo. `score_message` é um exemplo de nome mais descritivo.

```javascript
// antes
const create_paragraph = document.createElement('p')

form.addEventListener('submit', event => {
  // ...

  create_paragraph.textContent = /* ... */
  create_paragraph.setAttribute(/* ... */)
  quiz_title.insertAdjacentElement('afterend', create_paragraph)
})
```

```javascript
// depois
const score_message = document.createElement('p')

form.addEventListener('submit', event => {
  // ...

  score_message.textContent = /* ... */
  score_message.setAttribute(/* ... */)
  quiz_title.insertAdjacentElement('afterend', score_message)
})
```

---

Em inglês, [a ordem das palavras muda](https://www.inglesnapontadalingua.com.br/2012/02/por-que-em-ingles-algumas-palavras-sao.html). 

Para especificar que a const armazena as respostas do usuário, o correto seria renomear `answers_of_user` para `user_answers`.

```javascript
// antes
form.addEventListener('submit', event => {
  // ...

  const answers_of_user = [ /* ... */ ]

  answers_of_user.forEach(/* ... */)

  // ...
})
```

```javascript
// depois
form.addEventListener('submit', event => {
  // ...

  const user_answers = [ /* ... */ ]

  user_answers.forEach(/* ... */)

  // ...
})
```

---

`certanin` é uma palavra que não existe. 

Neste caso, o ideal seria mudar `answers_certanin` para algo como `correct_answers`.

```javascript
// antes
const answers_certanin = ['B', 'B', 'B', 'B']

form.addEventListener('submit', event => {
  // ...

  user_answers.forEach((user_answer, index) => {
    if (user_answer === answers_certanin[index]) {
      // ...
    }
  })

  // ...
})
```

```javascript
// depois
const correct_answers = ['B', 'B', 'B', 'B']

form.addEventListener('submit', event => {
  // ...

  user_answers.forEach((user_answer, index) => {
    if (user_answer === correct_answers[index]) {
      // ...
    }
  })

  // ...
})
```

Feito isso, a aplicação continuará funcionando mas desta vez, com um código mais legível e fácil de ser entendido =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Edersongoncalves** [comment]
As observações fizeram todo sentido.
o feedback assim faz toda diferença muito obrigado e vamos pra cima e vou ficar mais atendo aqui antes de dar os comits

**Comment by Edersongoncalves** [comment]
uma duvida :
a parte do HTML  era pra escrever do zero ou podia copiar e so fazer alterações ?

**Comment by Roger-Melo** [comment]
> ### a parte do HTML  era pra escrever do zero ou podia copiar e so fazer alterações ?.

Se o exercício não especifica isso, tanto faz.

Quando o assunto é HTML ou CSS, recomendo que faça o que for mais confortável pra vc construir a aplicação. Seu foco real deve estar no JavaScript =)

---

> ### o refatoramento do codigo nesses caso que vamos ir fazendo  os projetos  por partes, assim que acabar uma parte ja pode ir refatorando ou melhor deixa para o final do projeto ?.

Não existe final de projeto =)

Sempre haverá algo a ser melhorado conforme vc progride no treinamento. Por isso, vc ainda irá se deparar com exercícios que pedem pra vc refatorar as aplicações baseado em algo que acabou de conhecer. 

Essa é a graça.

E vc também não precisa esperar ter um exercício pedindo pra refatorar.

Conheceu algo novo? Vai lá e testa uma refatoração com o que conheceu. 

Se não ficar legal, vc volta a aplicação pro estado de antes. 

Sacou a ideia?

@Edersongoncalves

**Comment by Edersongoncalves** [comment]
blz, entendido obrigado.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)

**Comment by Edersongoncalves** [comment]
Boa noite Professor
 fiz as elterações e dei o comit para avaliação

**Comment by Edersongoncalves** [comment]
boa noite Roger
sobre a quiz que eu ja tinha dado o comit e vc me respondeu  eu fiz as alterações  e dei o comit, vc avalia de novo eu fiquei com duvida ?
________________________________
De: Roger Melo ***@***.***>
Enviado: quinta-feira, 6 de janeiro de 2022 22:53
Para: roger-melo-treinamentos/curso-de-js-roger-melo ***@***.***>
Cc: Edersongoncalves ***@***.***>; Mention ***@***.***>
Assunto: Re: [roger-melo-treinamentos/curso-de-js-roger-melo] Aplicação: Quiz games preferidos (Issue #2654)


Closed #2654<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froger-melo-treinamentos%2Fcurso-de-js-roger-melo%2Fissues%2F2654&data=04%7C01%7C%7Ccee14321c8aa4718f0e608d9d1807a61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771172023196167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F8tym%2BE7tYnX7HYeLNNHqoAqMzLS2yHJMywRvMoCBPA%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froger-melo-treinamentos%2Fcurso-de-js-roger-melo%2Fissues%2F2654%23event-5855517550&data=04%7C01%7C%7Ccee14321c8aa4718f0e608d9d1807a61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771172023196167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YjhMCncZuWq%2BRY53kop3Yd0xr2ZH1AXFgyc2jCIv8ME%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ7GRMSAX4J5S42QTXTYNQ3UUZBQ3ANCNFSM5LEK3ADQ&data=04%7C01%7C%7Ccee14321c8aa4718f0e608d9d1807a61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771172023196167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uiPq5sBso51AuI4gPh1C%2Bljw4byUxJt7BYGNHCRhUm0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ccee14321c8aa4718f0e608d9d1807a61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771172023196167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X9el7YBtaDGlZ5ZV%2FHrh0TBUuWR4%2FwcF3ydcNz5qvdE%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ccee14321c8aa4718f0e608d9d1807a61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771172023196167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xkqzel%2F2S8qq%2Fo6QNWgng8uqNjcjfyh2gjVKfsqpAnc%3D&reserved=0>.
