### ISSUE TITLE
Dúvida sobre HTML

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2660]
### Etapa da aula

5

### Nome da aula

Eventos de clique - Aula 03-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871195

### Descreva a dúvida

```
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <title>Eventos de clique</title>
  <link rel="stylesheet" href="style.css">
</head>
<h1>Todos</h1>

<body>
  <ul>
    <li>Comprar frango</li>
    <li>Ler livro</li>
    <li>Tocar violão</li>
    <li>Pagar contas</li>
  </ul>
  <button>Clique aqui</button>
  <script src="app.js"></script>
</body>

</html>
```

Porque o link do style.css fica na tag head e o app.js na tag body?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz!

`<link>` é uma tag metadata e tags desse tipo devem ficar dentro de `<head>`. Vou deixar abaixo materiais para vc saber mais sobre isso:

- [`<head>`: The Document Metadata (Header) element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head)
- [Metadata](https://developer.mozilla.org/en-US/docs/Glossary/Metadata)
- [`<link>`: The External Resource Link element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)

---

Sobre a tag `<script>`, é como falei na aula [Adicionando o javascript a uma pagina web - Aula 01-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/733504). Ela também pode ser inserida no `<head>`, porém, isso acarreta em problemas de performance, pois ao inserir a tag `<script>` no `<head>`, o conteúdo do `<body>` não será carregado enquanto o JavaScript não terminar de ser carregado. 

Ou seja, o browser vai ler todo o script primeiro e, só depois, irá carregar o conteúdo da página. Isso significa que se vc tiver muitos scrips no `<head>`, o conteúdo da página só será carregado depois de todos os scripts serem carregados.

Sacou a ideia?

**Comment by Jansen-Muniz** [comment]
Entendido ✌🏻😁

**Comment by Roger-Melo** [comment]
Show. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
