### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2662]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/marcosyoggy/WEATHER-APPLICATION

### Maiores dificuldades durante a implementação

   1- Perco muito tempo definido a estrutura base; Organizando os elementos; Comparado às primeiras aplicações, gasto menos tempo, pois o 'BootsTrap' ajuda muito;

    2- A leitura dos comandos digitados é uma dificuldade, talvez pela falta de organização, mas percebo que a prática de 'ler e reler' ajuda;

   3- A minha técnica de refatoração ainda está engatinhando, neste caso específico, não consegui refatorar o 'form';

    4- ....e também, no fim, após entender que poderia enviar a aplicação, pois já estava funcionado, perdi algum tempo procurando(usando CTRL + F) variáveis e comandos que não estavam sendo usados;

### Menores dificuldades durante a implementação

    1- Criar uma estrutura de código, grosseira, mas funcional;
    2- Nomear variáveis e funções;
    3- Num nível básico, fazer destructuring em arrays e objetos;
    4- Adicionar elementos e funcionalidades a mais no projeto original, fazer funcionar, mesmo que o código fique com 1Km de extensão;
    5- Diante de qualquer dificuldade, não pular o problema, procurando nas anotações e no 'MDN', independente do tempo gasto, até achar uma possível solução;
    6- Com relação à tradução dos docs em inglês, hoje a leitura já flui bem, são poucas palavras e alguns parágrafos onde o sentido fica confuso no meu entendimento, que recorro ao tradutor online;

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Não sei se vc chegou a testar a aplicação antes de enviar, mas logo ao abrir a aplicação, é exibido que `night.svg` não foi encontrado:

![image](https://user-images.githubusercontent.com/29297788/148685798-47ea9d5f-b93e-4a87-8dd5-e70dae36688d.png)

Esse erro vem daqui:

```html
<img data-app="time" src="./docs/weather-application-master/src/night.svg" class="img-fluid ">
```

Vc precisa especificar um caminho no src que faça sentido. O diretório `docs` não existe na raiz do seu projeto.

Considerando que `./` é o diretório raiz do projeto (que contém index.html, README.md, etc), qual caminho vc acha que precisa especificar no src?

O mesmo vale para todos os outros svgs, pois também estão apontando para o caminho errado.

---

No geral, seu código ficou complexo e tá bem diferente do que foi mostrado nas aulas.

Não faz sentido, por exemplo, ter a quantidade de requests que vc inseriu no app.js. E o motivo é muito simples: cada request consome do pacote de dados do usuário. Se alguém usar uma aplicação como essa que faz vários requests desnecessários, o 4G da pessoa é consumido mais rápido do que deveria.

E eu usei a palavra desnecessário pq nas aulas vc viu uma forma de fazer a mesma coisa com bem menos requests. Quanto menos requests, melhor.

---

Eu poderia estender essa análise por várias e várias linhas fazendo observações como a que fiz acima, mas vou fazer uma única recomendação.

Se vc conseguir seguir essa recomendação, será o 80/20 para que seu código fique mais simples e sua aplicação seja de fato analisada.

A recomendação é: primeiro, faça o básico. Depois vc pensa em improvisar.

Ali em cima vc marcou, por exemplo, que sua aplicação não contém funcionalidades que não foram mostradas nas aulas. E na real, tem um "Data Bank" (como vc mesmo nomeou). A quebra desse critério já impossibilita que sua aplicação seja analisada.

---

Se vc deseja que sua aplicação seja analisada, recomendo que faça um segundo envio mas desta vez, focando apenas no que viu nas aulas. Sem improvisar. 

Só assim eu terei a certeza que vc realmente entendeu o que viu até aqui e tem uma base para o que encontrará nas próximas aulas e desafios =)

**Comment by marcosyoggy** [comment]
...Grato pelo feedback...Já iniciei a revisão completa, espero reenviar a aplicação até 3º feira (10/01).
