### ISSUE TITLE
Aplicação: Currency Converter

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#2663]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Will-Andrade/CJRMCurrency-Converter

## Link da aplicação no Netlify
https://currencyconverterdev.netlify.app/

## Dificuldades
1. Dificuldades em acessar elementos ```option``` e devido a isso, ter criado um código "amarrado" (se mexer, quebra)
2. Dificuldades com refatoração devido a não conseguir bolar uma boa lógica de implementação dos requisitos
3.  Dificuldades com a lógica para essa aplicação
4. Por algum motivo, um número enorme de requisições está sendo feito pela aplicação e não consegui consertar até o momento

### Menores dificuldades durante a implementação

1. Realizar requisições
2. Nomeação de variáveis, constantes e funções
3. Destructuring

**Comment by Roger-Melo** [comment]
@Will-Andrade abri no browser e um erro impediu que o conteúdo da página fosse carregado.

![image](https://user-images.githubusercontent.com/29297788/148135086-50874a1b-2219-469b-ae0c-ec3774f09430.png)

Vc quer que a aplicação seja analisada assim ou quer fazer um novo envio?

Estou perguntando pq ainda nem abri o código, mas se eu abrir, ele será analizado uma única vez (como em uma entrevista técnica).

Aguardo.

**Comment by Will-Andrade** [comment]
Ah, tudo bem. Vou tentar enviar a aplicação em outro momento. Isso está acontecendo pois por algum motivo que não consigo ver no código, várias requisições estão sendo feitas e esgotando o limite da API.
![image](https://user-images.githubusercontent.com/52185265/148138119-07d54411-f657-49dd-b627-7ae9058a8866.png)

**Comment by Roger-Melo** [comment]
Isso não é normal.

Será que vc não está fazendo um request para cada moeda, por exemplo? Pode ser algum loop fazendo request à cada execução.

@Will-Andrade

**Comment by Will-Andrade** [comment]
Professor @Roger-Melo, pode fechar essa issue. Consegui resolver o problema do monte de requisições mas esbarrei em mais problemas que impossibilitaram a entrega da aplicação a tempo.

**Comment by Roger-Melo** [comment]
@Will-Andrade pode entregar.

Assim que eupuder olhar, dá o toque aqui =)

**Comment by Will-Andrade** [comment]
Tudo bem professor, eu não consegui finalizar o app da forma requisitada. O senhor pode abrir a versão que eu passei nos comentários acima, obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Tranquilo, em breve posto a análise aqui =)

**Comment by Will-Andrade** [comment]
Obrigado pelo review, professor. Francamente, me enrolei todo nessa aplicação, refiz do zero 3 vezes e ainda assim não consegui finalizar. Assistindo a correção dos exercícios da aula 3 da etapa 14, percebi que eu peguei o caminho mais difícil para implementar essa aplicação, vide ter feito requisições desnecessárias e escrito código redundante.
Meu problema com essa aplicação começou na aula onde você começa a introduzir Factory Functions. Apesar de ter assistido a aula várias vezes e procurado mais conteúdo na internet, não consegui entender isso e nem aplicar nos exercícios que pediam para usar esse método de criação de objetos. Quando comecei a lista, já tive dificuldades. Diferente de qualquer lista do curso, essa foi a que mais tive dificuldades e que menos tive êxito na resolução.
Sinceramente, fiquei decepcionado nessa etapa 14 porque parece que não entendi nada dessa aula 3 kkkk 
Estarei seguindo sua recomendação e também vou revisar toda a etapa 14 pois não me sinto seguro com todo esse conteúdo ainda.

**Comment by Roger-Melo** [comment]
> ### Quando comecei a lista, já tive dificuldades. Diferente de qualquer lista do curso, essa foi a que mais tive dificuldades e que menos tive êxito na resolução.

E por que isso seria ruim?

Pra mim, isso é um sinal que vc está saindo da sua zona de conforto, o que é ótimo.

Se vc teve dúvida com factory functions, pq não abriu uma issue explicando a dúvida e pedindo ajuda?

Se vc não pedir ajuda, suas dúvidas vão escalar.

E quando as dúvidas escalam, fica mais complicado encontrar o ponto onde a primeira dúvida começou.

É por isso que vc precisa pedir ajuda quando uma dúvida surgir, sacou?

@Will-Andrade

**Comment by Will-Andrade** [comment]
Pensando dessa forma, eu concordo professor. Vou abrir uma issue relacionada com os problemas que encontrei na compreensão das factory functions. Essa issue aqui o senhor pode fechar, @Roger-Melo .

**Comment by Roger-Melo** [comment]
No que precisar, estou à disposição =)
