### ISSUE TITLE
Resumo da Aula Prototypes - Aula 03-07 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2668]
Um método criado dentro de uma função construtora não é bom para a minha aplicação, pois a cada objeto criado a partir dessa construtora, terá um mesmo método ocupando um novo espaço na memória. É possível comprovar isso comparando os métodos de cada objeto criado, onde `false` é retornado. Existe uma forma de evitar isso. Em *JavaScript*, todo novo objeto criado herda propriedades e métodos de seu *prototype*, que é o objeto do qual o meu objeto irá herdar propriedades e métodos. Se no console do *browser* for criado um *array*, ao expandi-lo, ele terá uma propriedade `__proto__` (ou `Prototype`), que armazena todos os métodos que o *array* poderá usar. Porém não é necessário chamar o `includes()` de um array dessa forma: `[].__proto__.includes()`. Basta invocar `[].includes()`, pois a *engine* do *JavaScript* entende que, caso esse método não exista no próprio *array*, será procurado no *prototype* do *array*.

Então, ao criar um método dentro da função construtora, ao visualizarmos no console algum objeto criado a partir dessa função, veremos o método dentro do próprio objeto. Então a ideia é criar esse método fora da função construtora, armazenando em apenas um espaço na memória, e fazer com que todo objeto criado a partir dela, tenha acesso a esse método através da referência dele. Para isso deve-se armazenar o método dentro do *prototype* do objeto, e não do objeto em si.

Cada tipo de objeto em *JavaScript* tem um *prototype*. *Prototype* é um objeto nativo da linguagem que é apenas referenciado quando é criado um novo objeto. Vamos ver abaixo o exemplo de uma função construtora com um método adicionado a seu *prototype*:

```jsx
function Student(name, email) {
	this.name = name
	this.email = email
}

Student.prototype.login = function() {
	return `${this.name} fez login`
}
```

No exemplo acima, o método `login()` foi adicionado não ao objeto, mas sim ao *prototype* do objeto, fazendo com que independente de quantos objetos forem criados a partir dessa função construtora, todos irão apenas referenciar o método `login()`, e não recria-lo no objeto. Então sempre que for utilizada uma função construtora para criar novos objetos, seus métodos deverão ser criados fora da função.

Agora, quando falamos de classes, os métodos não precisam ser criados fora dela. Quando métodos são criados nas classes, automaticamente eles são atribuídos ao *prototype* do objeto, e não ao objeto em si. Vamos ver esse exemplo, utilizando a abordagem de classe:

```jsx
class Student {
	constructor(name, email) {
		this.name = name
		this.email = email
	}

	login() {
		return `${this.name} fez login`
	}
}
```

Agora falando sobre métodos estáticos. É um método que ao invés de ser declarado no *prototype* dos objetos, é declarado diretamente na função construtora, sendo invocado através da referência da função construtora. Ou seja, esse método não será utilizado em um objeto criado a partir dessa função construtora, mas sim da própria função construtora. Por exemplo, o `Array.from()` é um método estático da função construtora `Array`, que é invocado através dela. Os métodos estáticos serão úteis quando for necessário ter um método utilitário, que é um método que pode ser útil em situações frequentes na aplicação. Como um exemplo, vamos criar um método estático que irá formatar uma *string* para que seja armazenada no banco de dados, e que a regra de negócios define que essa *string* deverá estar em caixa alta e separada por *undescores* ao invés de espaços em branco. Na abordagem de funções construtoras, basta criarmos o método da mesma forma que criamos os métodos nos *prototypes*, porém sem o “*prototype*” na criação. Vamos ver na prática como ficaria:

```jsx
Student.formatToDatabase = function(aString) {
	return aString
		.toUpperCase()
		.replace(/ /g, '_')
}

console.dir(Student)
```

Esse método não existe no *prototype* e nem no objeto, por ser um método estático, então ele existe apenas na função construtora. Caso eu queira visualizar esse método estático no console, é necessário utilizar o método `dir()` do console, conforme exemplificado acima, onde serão mostrados as propriedades e os métodos da função construtora. O único “problema” existente nesse caso é que os métodos criados na forma como foram declarados, ficam sem nome, pois estão sendo criados a partir de funções anônimas. Isso não fará com que a aplicação deixe de funcionar, mas caso um erro ocorra em um dos métodos, e eu precisar renderizar o nome do método, ele virá vazio. Não existe justificativa para trabalhar com *function declaration* anônima, a não ser que essa *function declaration* seja atribuída a uma `const` ou `let`, onde automaticamente o nome das `const` ou `let` será atribuído a propriedade `name` da função. Então quando se trata de métodos, estáticos ou não, o ideal é que elas tenham um nome. Então vamos dar o nome a elas da seguinte forma:

```jsx
Student.formatToDatabase = function formatToDatabase(aString) {
	return aString
		.toUpperCase()
		.replace(/ /g, '_')
}
```

E para criar métodos estáticos em classes, basta adicionar a palavra chave `static` antes da criação do método, onde a própria abordagem de classe já nomeia automaticamente seus métodos, sendo eles estáticos ou não.

```jsx
class Student {
	// código omitido

	static formatToDatabase(aString) {
        return aString
            .toUpperCase()
            .replace(/ /g, '_')
    }
}
```

Agora, ao invés de declarar um método estático, eu não poderia apenas declarar uma função? E a resposta é sim. Podemos criar simples funções ao invés de métodos estáticos.

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🎯
