### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07 da etapa 05

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2673]
Para manipular um documento HTML através do JS, existem alguns passos envolvidos. O primeiro passo é decidir qual elemento da página será manipulado e depois disso, buscar a referência desse elemento no DOM. Essa ação de buscar e selecionar um elemento, é chamado de query.

`document`: É o objeto raiz que dispõe vários métodos e atributos necessários para acessar os elementos HTML.

`querySelector():` É um método do objeto `document`  que retorna o primeiro nó equivalente ao seletor, ou grupo de seletores passado através de uma String como argumento. Se não houver um elemento equivalente ao seletor passado como argumento, null será retornado. A busca será feita seguindo uma ordem de cascata pelo documento começando pela raiz da estrutura iterando pelos nós de forma sequencial pelo documento.

`querySelectorAll()`: Retorna um NodeList estático representando uma lista de elementos do document equivalente ao seletor passado como argumento. Um NodeList estático possui um elemento para cada seletor especificado, caso não haja uma combinação entre seletor e elemento o retorno será um NodeList vazio.

**NodeList objects:** São coleções de nós, normalmente retornado por propriedades como “_Node.childNodes_” ou métodos como _"documento.querySelectorAll()"_. No entanto, NodeList não é um Array, mas é possível iterar sobre ele usando um `forEach()`.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota, rumo à fluência! 🎯
