### ISSUE TITLE
duvida a cerca de Bootstrap 

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2679]
### Etapa da aula

7

### Nome da aula

Exibindo a pontuação - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/963054

### Descreva a dúvida

Olá professor, um pouco atrasado mas **feliz ano novo.** Então, no final do ano passado o senhor recomendou que eu refizesse todas as aulas para que eu melhorasse minha base em JS e assim eu fiz, reescrevi vários resumos, refiz todas as atividades varias vezes, principalmente as mais complexas com envio do form e eventos de teclado. Claro, ainda falta bastante para que eu conclua o treinamento(isso me deixa meio desanimado principalmente por conta dos meus maus hábitos no estudo, mas que aos poucos vou melhorando-seguindo bastante o metodo ATER).
Eu marquei essa aula, pois logo no começo o senhor utiliza vários elementos do Bootstrap que alteram uma única div e eu queria saber algumas coisas sobre:
1- Se mais a frente no treinamento estudaremos mais sobre Bootstrap
2- Eu não sei inglês muito bem, então queria saber se tem algum canal no youtube de programação que fala sobre  Bootstrap que o senhor recomenda
3- Se devo me preocupar em não saber muito sobre Bootstrap(eu sou o tipo de aluno extremamente agitado e quando vejo dificuldade em algo eu fico bem ansioso)

no mais é isso, não duvidas normais como ajuda para resolver algum problema, são mais para me ajudar a não enlouquecer de tanto pensar sobre. Obrigado pela atenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208, feliz 2022!

> ### isso me deixa meio desanimado principalmente por conta dos meus maus hábitos no estudo

Quais maus-hábitos?

---

> ### 1- Se mais a frente no treinamento estudaremos mais sobre Bootstrap

Não.

O treinamento é focado em construir aplicações web com **JavaScript puro** =)

O uso do Bootstrap é opcional. Use CSS puro se achar mais confortável.

---

> ### 2- Eu não sei inglês muito bem, então queria saber se tem algum canal no youtube de programação que fala sobre Bootstrap que o senhor recomenda

Qualquer tecnologia que vc quer aprender já fornece a fonte número 1 na qual vc deve pesquisar, que é a documentação.

Essa é a [documentação do Bootstrap](https://getbootstrap.com/).

Eu não acompanho canais Brasileiros sobre bootstrap, então infelizmente não posso recomendar.

Sobre o inglês, dá uma olhada no que falei [neste vídeo](https://youtu.be/HuspxEOaX50).

---

> ### 3- Se devo me preocupar em não saber muito sobre Bootstrap (eu sou o tipo de aluno extremamente agitado e quando vejo dificuldade em algo eu fico bem ansioso)

E o que vc está fazendo hoje para amenizar a ansiedade?

Eu entendi que vc sabe que tem um problema, mas o que vc está fazendo para resolvê-lo?

Estou perguntando isso porque em sua carreira como desenvolvedor, você encontrará muitas coisas novas pelo caminho. E tudo o que é novo, é desafiador.

Se vc não tomar a atitude de resolver esse problema, ele pode comprometer sua carreira.

---

Como eu disse ali em cima, o uso do Bootstrap no treinamento é opcional. Se vc vai precisar dele fora daqui vai depender do tipo de vaga que vc está de olho.

Porém, algo me diz que o fato de vc ter se assustado com o Bootstrap pode ser um sinal de falta de base em HTML e CSS. Essa minha interpretação faz sentido?

**Comment by CarlosHenrique2208** [comment]
1- meus maus hábitos são somente a falta de constância nas horas de estudos diário, as vezes estudo varias horas, as vezes estudo poucas, as vezes começo pela manhã, as vezes pela tarde quase a noite. É bem mais um problema de rotina.

3- em relação a minha ansiedade, eu tento não dar voz a ela, tento não ser pessimista e agravar mais as coisas. Outra coisa que comecei recentemente foi começar a praticar atividade física.

------------------------------------------------------------------------

e sobre sua interpretação, ela está sim. Eu tive pouco contato com CSS e HTML antes de entrar no seu treinamento. Sabia só a base de o que são, para que servem e como funciona a estrutura de cada uma, mas não sei mais que isso principalmente no que diz respeito a elementos e valores mais complexos e aprofundados.

**Comment by Roger-Melo** [comment]
> ### 1- meus maus hábitos são somente a falta de constância nas horas de estudos diário, as vezes estudo varias horas, as vezes estudo poucas, as vezes começo pela manhã, as vezes pela tarde quase a noite. É bem mais um problema de rotina.

0 é maior que 1.

Estudar sem rotina é melhor que não estudar.

Porém, se continuar assim vc precisa estar ciente de que provavelmente não terá resultados tão expressivos quanto os de alguém consistente.

O ideal é estudar no mínimo 1h por dia (todos os dias) e ir aumentando conforme conseguir, mas sem perder a constância. Sem pressa, mas sem pausa.

---

> ### 3- em relação a minha ansiedade, eu tento não dar voz a ela, tento não ser pessimista e agravar mais as coisas. Outra coisa que comecei recentemente foi começar a praticar atividade física.

Boa! Atividade física é essencial. Seu corpo deve ser a armadura das suas vitórias, e não o peso das suas derrotas.

Buscar informações de pessoas que realmente são qualificadas para falar do assunto também é fundamental:

- [Pedro Calabrez](https://youtu.be/ekLcu9RnXg0)
- [Geronimo Theml](https://youtu.be/HRJNUJUgH5U)

Porém, se sentir que é necessário, busque ajuda profissional. Há casos em que é preciso. Eu buscaria, se sentisse que não estou conseguindo gerenciar as emoções.

---

> ### e sobre sua interpretação, ela está sim. Eu tive pouco contato com CSS e HTML antes de entrar no seu treinamento.

[Nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1882#issuecomment-933805098) eu recomendei materiais de estudo para um aluno em uma situação parecida.

No Codecademy, os cursos que não tem a tag "PRO" são gratuitos.

@CarlosHenrique2208

**Comment by CarlosHenrique2208** [comment]
professor, de novo, desculpa pelo atraso e muitíssimo obrigado por responder e compartilhar bons métodos e materiais para me ajudarem, obrigado msm.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
