### ISSUE TITLE
Etapa 06, nome do vídeo: correção dos exercicios da aula 02 da etapa 06

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#268]
ola roger, qual a diferenca de usar "event.target.input" no submit do escutador de eventos, e usamos "event.target.username.value" no keyup do escutador de evento? poderia me explicar a diferenca de usar uma ou outra.

``  
 const form = document.querySelector('form')
  const input = document.querySelector('#username')
  const p = document.createElement('p')

  const testUserName = username => /^[a-zA-Z]{6,}$/.test(username)

  const isNotUsernameValid = 'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas'
  const usernameValid = 'Username válido =)' 

  const inputMessage = (text, classname) => {
    p.textContent = text
    p.setAttribute('class', classname)
    input.insertAdjacentElement('afterend', p)
  }

// ESCUTADOR DE EVENTO "KEYUP"

  form.username.addEventListener('keyup', event => {
    const isAValidUsername = testUserName(event.target.input)

    if(isAValidUsername) {
      inputMessage(usernameValid, 'username-success-feedback')
      return
    }
    
    inputMessage(isNotUsernameValid, 'username-help-feedback')
  })
``
 const div = document.querySelector('.container')

  const submitMessage = (text, classname) => {
    p.textContent = text
    p.setAttribute('class', classname)
    div.append(p)
  }

// ESCUTADOR DE EVENTO "SUBMIT"

  form.addEventListener('submit', event => {
    event.preventDefault()

    const userName = event.target.username.value
    const isValid = testUserName(userName)

    if(isValid) {
      submitMessage('Dados Enviados =)', 'submit-success-feedback')
      return
    }

    submitMessage('Por favor, insira um username válido', 'submit-help-feedback')
  })

``

``

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mateus20Barros. Você tirou sua dúvida?

**Comment by Mateus20Barros** [comment]
conseguir sana ela
