### ISSUE TITLE
Resumo O que são requests HTTP - Aula 01-04 da etapa 11

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2681]
### requests HTTP
- São algumas das operações que levam um tempo para serem finalizadas no nosso código;
- Pegar informações em uma API ou em Banco de Dados;
- É um pedido ou uma solicitação;
- Realizamos um request para um endpoint de um servidor recebendo um JSON;

**Comment by Roger-Melo** [comment]
Excelente @carlosdevjs, rumo à fluência! 🎯
