### ISSUE TITLE
Resumo da Aula Herança prototipal - Aula 03-08 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2682]
Quando eu quiser criar uma subclasse de uma classe existente, ou seja, herdar suas propriedades e métodos além de ter propriedades e métodos próprios, eu utilizo a palavra chave `extends` e a invocação do `super()`. Com funções construtoras é um pouco diferente. Eu inicio uma nova função construtora normalmente (que será como uma subclasse), e ao invés de ter um método `constructor()`, eu chamo a função construtora da qual quero herdar, e invoco nela o método `call()`, que invocará um construtor. O método `call()` receberá como primeiro argumento o objeto que está sendo criado, ou seja, ele receberá `this`. Após esse primeiro argumento, os demais serão os valores das propriedades existentes na função construtora que é como se fosse uma classe principal. Pode parecer um pouco confuso, mas vamos ver como ficaria na prática, porém ainda sem adicionar mais propriedades ou métodos.

```jsx
function Student(name, email) {
	this.name = name
	this.email = email
}

Student.prototype.login = function login() {
	return `${this.name} fez login`
}

function TeacherAssistant(name, email) {
	Student.call(this, name, email)
}

const monica = new Student('Monica', 'monica@friends.com')
const ross = new TeacherAssistant('Ross', 'ross@friends.com')

console.log(monica, ross)
```

Porém apenas isso não é suficiente para que os métodos também sejam herdados. Se observarmos no console, no objeto `__proto__` (ou Prototype), o método `login()` de *Student* não está presente em *TeacherAssistant*. Então para que *TeacherAssistant* herde também os métodos de *Student*, devemos fazer como se estivéssemos criando um método: adiciona-lo ao *prototype*. Mas adicionar o que? O *prototype* da função construtora `Student`. Para isso devemos então atribuir ao `TeacherStudent.prototype` o método `create()` do construtor `Object`, que recebe como argumento um objeto que eu quero que seja o *prototype*, passando para ele `Student.prototype`. Isso será o suficiente para que nossa função construtora *TeacherAssistant* tenha em seu *prototype* os métodos da função construtora *Student*. Vamos ver na prática:

```jsx
// código omitido

TeacherAssistant.prototype = Object.create(Student.prototype)

// código omitido
```

A função construtora *TeacherAssistant* também pode ter suas próprias propriedades e métodos, e isso é feito normalmente igual feito na função construtora *Student*. As propriedades são declaradas utilizando o `this` e os métodos deverão ser adicionados ao *prototype* da função construtora. Então vamos criar uma propriedade e adicionar um método a *TeacherAssitant*:

```jsx
// código omitido

function TeacherAssistant(name, email, scheduledWeekPost) {
	Student.call(this, name, email)	
	this.scheduledWeekPost = scheduledWeekPost
}

TeacherAssistant.prototype.giveBadge = function giveBadge(student) {
	return `${this.name} deu uma medalha ao estudante ${student.name}`
}

const ross = new TeacherAssistant('Ross', 'ross@friends.com', false)

// código omitido
```

Isso fará com que *TeacherAssistant* tenha propriedades e métodos próprios, além dos herdados da função construtora *Student*.

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. Vamo que vamo, rumo à fluência! 🙌
