### ISSUE TITLE
Resumo - Fazendo requests HTTP - Aula 02-03 da etapa 11

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#2683]
### Fazendo requests HTTP
- 1º Passo - Criar um objeto request com o contructor new [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/XMLHttpRequest);
- Abrir a requisição com o método [open()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open), com dois argumentos (método HTTP e o endpoint);
- Para enviar utilizar o método [send()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send);
- Para saber o estado atual da requisição, devemos trakear a request antes de ser enviada;
- EventListener com 'readystatechance';
- 2º Passo - Checar se o [state ](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState)do request é igual a 4, porque é só neste estado que podemos fazer alguma coisa com os dados;
- 3º Passo - checar o [status ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)do request, pois apenas o state não adianta;

```js
const request = new XMLHttpRequest

request.addEventListener('readystatechange', event => {
  if (request.readyState === 4 && request.status === 200) {
    console.log(request.responseText)
  }
}

request.open('GET', 'https://jsonplaceholder.typicode.com/todos')
request.send()
```

**Comment by Roger-Melo** [comment]
Show @carlosdevjs . Vamo que vamo, rumo à fluência! 🙌
