### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by almir05** [roger-melo-treinamentos/curso-de-js-roger-melo#2684]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/almir05/cjrm-quiz-interativo

### Maiores dificuldades durante a implementação

Tive dificuldade em tentar elaborar um jeito de evitar a repetição da invocação da função "insertResultMessage" no meu código, não sei se deste modo está correto ou se devo mesmo colocar a condicional em uma outra função.

### Menores dificuldades durante a implementação

Acompanhei a aula do quiz dos filmes e pude entender um pouco da lógica utilizada, então apenas troquei o tema das cores e o tema das perguntas como foi pedido no desafio. Quanto a mostrar a pontuação do usuário na tela, também não tive muita dificuldade, minhas maiores dúvidas são mesmo quanto a refatoração do código e como torná-lo mais legível.

**Comment by Roger-Melo** [comment]
Olá @almir05.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @almir05!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Tive dificuldade em tentar elaborar um jeito de evitar a repetição da invocação da função "insertResultMessage" no meu código, não sei se deste modo está correto ou se devo mesmo colocar a condicional em uma outra função.

O correto é fazer funcionar. Num primeiro momento, o mais importante é fazer funcionar, como você já fez. 

Depois de fazer funcionar, se fizer sentido, aí vc refatora.

Ali em baixo vou te mostrar uma forma de refatorar essa parte =)

Antes de qualquer coisa, seu código tá bem legal pq por ele eu percebi que vc está preocupado em aprender o básico antes de improvisar. Esse é um princípio fundamental que muitos atropelam.

Ao invés de tentar fazer firulas, vc fez o básico bem feito. Parabéns por isso 🎉

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que alguns cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Local de exibição da pontuação

Talvez, depois que você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. 

Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![image](https://user-images.githubusercontent.com/29297788/149051790-67fd4bc1-6b08-48c5-88c3-b325b9b62f48.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

---

## Alternativas desmarcadas por padrão

Acredito que deixar a primeira alternativa de cada pergunta marcada por padrão incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Porém, isso é apenas uma opinião pessoal =)

---

## Nomes de variáveis e funções

Aqui foi o ponto onde econtrei mais possibilidades de ajustes. Mas não se preocupe tanto com isso. 

Nomear é uma das tarefas mais complexas em programação, mas com a prática e seguindo o princípio que vou deixar abaixo, vai ficando cada vez mais natural.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

`userScore` é uma função que pode ser nomeada como `calculateUserScore` (verbo).

`scoreBiggerThanZero` pode ter `is` acrescentado. Ficaria `scoreIsBiggerThanZero`.

Uma possibilidade de nome mais descritivo para o que acontece quando o form é enviado é `showScore` (ao invés de checkResult).

Uma opção para padronizar a forma de se referir à pontuação no código é renomear `insertResultMessage` para `insertScoreMessage`.

`h1` é um nome que não descreve de fato sobre o que se trata o texto. Além disso, se futuramente a tag mudar pra h2 por exemplo, o nome da const perde o sentido. Você pode renomeá-la como `scoreMessage`.

---

## Refatoração

Só pra reforçar: o que vou sugerir aqui é apenas uma lapidação de um código que já funciona, ok?

O que muda entre as invocações da antiga insertResultMessage é apenas a string. Então dá pra eliminar o `if` (e a repetição de invocação) criando uma função que retorna a string baseado na pontuação:

```javascript
// antes
const checkResult = event => {
  // ...

  userAnswers.forEach(userScore)
  
  const scoreBiggerThanZero = score > 0
  
  if (scoreBiggerThanZero) {
    insertResultMessage(score, 'text-success')
    return
  }
  
  insertResultMessage(score, 'text-danger')
}
```

```javascript
// depois
const getTextColor = score => ({
  0: 'text-danger'
})[score] || 'text-success'

const showScore = event => {
  // ...

  userAnswers.forEach(userScore)
  
  const textColor = getTextColor(score)
  insertScoreMessage(score, textColor)
}
```

Se vc ainda não chegou na aula em que mostro essa técnica, vai chegar em breve e entender tim tim por tim tim.

E só pra dar um gostinho do que vem pela frente... dá pra eliminar forEach e if através de ternário e de um método chamado `reduce`:

```javascript
const getScore = userAnswers => correctAnswers.reduce((acc, correctAnswer, i) => 
  correctAnswer === userAnswers[i] ? acc + 20 : acc, 0)

const showScore = event => {
  // ...
  
  const userAnswers = [
    // ...
  ]

  const score = getScore(userAnswers)
  const textColor = getTextColor(score)
  
  insertScoreMessage(score, textColor)
}
```

Vc conhecerá essas duas features na próxima etapa, então guarde esse código e volte nele novamente no futuro =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by almir05** [comment]
Olá @Roger-Melo!

Muito obrigado pela sua análise, com certeza elas fizeram sentido, serão muito úteis na minha jornada até a fluência na linguagem.

> ## Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

Verdade, eu acabei me preocupando mais com a parte do JavaScript e não chequei totalmente a questão da interação do usuário com a aplicação. Irei ajeitar isso antes de hospedar no Netlify.

> ## Refatoração

Gostei demais em ver essas duas features para evitar a repetição da insertResultMessage, eu estava quebrando muita cabeça para tentar achar uma solução. Consegui compreender os dois códigos e pra mim faz muito sentido, estou ansioso para chegar na parte de reduce e também no momento em que utilizaremos o operador ternário.

> ## Nomear é uma das tarefas mais complexas em programação, mas com a prática e seguindo o princípio que vou deixar abaixo, vai ficando cada vez mais natural.

Obrigado pelas dicas e por repassar o princípio que você utiliza para nomear as variáveis e funções, já deixei tudo anotado aqui pra poder utilizar e melhorar nisso.

> ## Antes de qualquer coisa, seu código tá bem legal pq por ele eu percebi que vc está preocupado em aprender o básico antes de improvisar. Esse é um princípio fundamental que muitos atropelam.

Antes de fazer a aplicação, eu assisti aos vídeos anteriores várias vezes pra que pudesse chegar na aplicação já tendo essa base consolidada, fico feliz com isso!

Mais uma vez, obrigado @Roger-Melo. Agora é continuar a caminhada...até a próxima aplicação! :muscle::fire:

**Comment by Roger-Melo** [comment]
Legal! =)

Vou fechar essa issue, mas no que precisar, é só abrir uma nova =)
