### ISSUE TITLE
Etapa 05, nome do vídeo: Correção da aula 02

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#269]
```js
const changeColorsPinkOrBlue = number => {
  if(number % 2 === 0){
    ul.innerHTML += `<li style="color:lightblue;" class="number">${number}</li>`
  }else{
    ul.innerHTML += `<li style="color:pink;" class="number">${number}</li>`
  }
}

numbers.forEach(changeColorsPinkOrBlue) 
//por que abaixo me retorna undefined?
```

Olá Roger, tudo bem? Olha só, a minha dúvida é refente a você criar uma função e colocar a função como argumento do forEach. O que ocorre ali? por que você apenas referencia a função ao invés de chama-la no forEach?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

O `forEach` irá invocar a função automaticamente para cada item do array. Então não é necessário você invocar a função. Isso por que a invocação do forEach espera receber como argumento a declaração ou a referência de uma função para que ele a invoque.

Vou deixar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/216) uma issue em que o aluno estava com essa mesma dúvida e eu a respondi. Caso leia a issue e ainda permanecer alguma dúvida, é só me falar que explico de outra forma =)

Sobre o trecho de código abaixo, você o executou no console do navegador e ele retornou undefined?

```javascript
numbers.forEach(changeColorsPinkOrBlue) 
//por que abaixo me retorna undefined?
```

Se sim, isso acontece por que em JavaScript, um pedaço de código que não lança um erro ou não retorna um valor, retorna undefined. Então como essa expressão `numbers.forEach(changeColorsPinkOrBlue)` não está retornando um valor, quando ela é executada, ela retorna `undefined`.

Observe que se você executar `const hi = 'ola'` no console do navegador, como esse pedaço de código não retorna um valor (apenas armazena), `undefined` é retornado.

Você ainda verá muitos exemplos sobre esse comportamento da linguagem durante o treinamento, fique tranquilo =)

Mas ficou mais claro?

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
Agora ficou claro @Roger-Melo! Thanks My Friend.
