### ISSUE TITLE
Criação de métodos em uma factory function

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2693]
### Etapa da aula

14

### Nome da aula

Factory functions e composição de objetos - Aula 03-09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1926080

### Descreva a dúvida

Fala Roger! Ao começar a praticar a escrita de uma factory function após assistir a aula, acabaram batendo algumas dúvidas que talvez eu já as tivesse mas só percebi agora.

A primeira dúvida que tive foi: Para criar um método em uma factory function, eu não sei (ou não entendi) a diferença entre criar uma propriedade que retorna uma função ou criar de fato um método. Abaixo eu declarei um método login() e um método comment() de formas diferentes, mas não sei qual diferença entre eles na prática (além de que um eu usei arrow function e no outro function declaration).

A segunda dúvida que tive foi que, no formato de criação de método apresentado na aula, quando eu criar objetos a partir dela, os métodos serão criados dentro de cada objeto, ou seja, cada um ocupará um espaço diferente na memória. Nesse caso não cairíamos no mesmo problema de criar métodos dentro de funções construtoras, ou seja, fora dos prototypes?

```js
const createUser = (name, email) => ({ 
    name, 
    email,
    login: () => `${name} fez login`,
    comment() {
        return `${name} comentou`
    }
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas!

> ### Para criar um método em uma factory function, eu não sei (ou não entendi) a diferença entre criar uma propriedade que retorna uma função ou criar de fato um método.

Se vc voltar na aula [Funções vs Métodos - Aula 02-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803290) da etapa 03, verá que métodos e funções, em essência, são a mesma coisa. A diferença é que um método é uma função atribuída como valor de uma propriedade.

A notação da função que foi atribuída não importa. Se é uma função atribuída à uma propriedade, isso significa que essa função precisa ser invocada com a sintaxe `obj.prop()`, então é um método.

No exemplo que vc deu, as duas propriedades armazenam funções, isso significa que `login` e `comment` são métodos =)

Ficou mais claro?

---

> ### Nesse caso não cairíamos no mesmo problema de criar métodos dentro de funções construtoras, ou seja, fora dos prototypes?

É possível fazer herança usando factory functions ao invés de classes ou funções construtoras.

Eu mostrei como fazer isso na aula 02-03 da etapa 15. Inclusive, nessa aula eu mostrei como é possível selecionar prototypes diferentes pros objetos que a função cria. Se ao ver essa aula restar alguma dúvida, é só dar o toque =)

**Comment by ricardopontesdantas** [comment]
@Roger-Melo obrigado pelas respostas!

Sobre as funções e métodos, ficou claro sim. A dúvida era mais com relação a notação da função, que pela sua explicação acabei de entender que não importa, então show de bola!

E sobre a dúvida de método de factory function no prototype, vou aguardar chegar na etapa 15 para ver a aula que você mencionou.

Essas etapas finais disponíveis estão incrivelmente boas, obrigado mais uma vez, grande abraço!

**Comment by Roger-Melo** [comment]
> ### Sobre as funções e métodos, ficou claro sim. A dúvida era mais com relação a notação da função, que pela sua explicação acabei de entender que não importa, então show de bola!

É, não importa em relação à ser chamado de método. As implicações técnicas (`this`) da notação que vc escolhe vc verá (ou já está vendo) nas aulas =)

---

No que eu puder ajudar, estou à disposição =)

@ricardopontesdantas
