### ISSUE TITLE
Resumo da Aula 01-02 da etapa 06 - Eventos em formulários

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2695]
- Formulários existem para capturar algum tipo de informação do usuário
- Para capturar as informações, são utilizados eventos, principalmente, eventos de submit, eventos de envio do formulário, 
que acontece quando o usuário clica no botão enviar.
- Clicar no botão enviar, dispara não somente um evento de clique no botão, mas também um evento de submit do 
formulário, nesta caso pode ser setado um listener de evento que reage aos envios da informações do formulário, 
quando o formulário for enviado, as informações que o usuário preencheu podem ser capturadas.
-  Eventos do teclado - é possivel reagir quando o usuário pressiona ou solta uma tecla.

**Comment by Roger-Melo** [comment]
Show @Jansen-Muniz . Vamo que vamo, rumo à fluência! 🙌
