### ISSUE TITLE
Target não funcionando como o esperado

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#2699]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada + destructuring em parâmetros de funções - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890633

### Descreva a dúvida

Durante a execução do exercício 05, é preciso fazer com que a li clicada seja exibida no console. A resolução mostrada no vídeo, antes de ser refatorada, segue o código abaixo:

```js
lis.forEach(li => {
  li.addEventListener('click', event => {
    console.log(event.target)
  })
})
```
Esse código faria com que, por exemplo, ao clicar em certa li, ela apareça no console como:

```html
<li class = 'video'> Como gerar um template html com JavaScript</li>
```
Porém, ao clicar, ela aparece apenas como:

```html
<li class = 'video'>
```
Pesquisando um pouco, eu consegui fazer com que o texto da li apareça por completo usando .innerHTML depois do .target no código, mas não sei se essa seria a forma ideal de usá-la no código. Portanto, gostaria de entender o motivo ou se há alguma coisa a mais para fazer com que o target funcione como mostrado no vídeo?

@Roger-Melo

**Comment by MivlaM** [comment]
Abaixo estão os códigos que eu utilizei

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Correção dos exercícios da aula 03 da etapa 05</title>
</head>
<body>
  <h1>Correção dos exercícios da aula 03 da etapa 05</h1>

  <h2>Vídeos</h2>

  <ul class="videos">
    <li>Como desenvolver uma pokedex com JavaScript puro</li>
    <li>Como desenvolver uma aplicação que busca e exibe letras de músicas, com JavaScript puro</li>
    <li>Como gerar um template html com JavaScript</li>
    <li>Como refatorar uma função que tem mais de uma responsabilidade | JavaScript</li>
    <li>Como eliminar a sintaxe objeto.propriedade em seu código | JavaScript</li>
  </ul>

  <button>Adicionar vídeos</button>

  <script src="./app.js"></script>
</body>
</html>
```

```js
const ul = document.querySelector('.videos')

const lis = Array.from(ul.children)

const insertVideoClass = li =>{
   li.classList.add('video')
 }

lis.forEach(insertVideoClass)

console.log(lis)
```

```js
lis.forEach(li => {
  li.addEventListener('click', event => {
    console.log(event.target)
  })
})
```

Aqui deixo uma imagem de exemplo do que aparece no console ao clicar nas lis

![Sample01](https://user-images.githubusercontent.com/82729897/148792982-2c8c6993-836c-460d-bb9b-fb95fc7ad218.png)

**Comment by Roger-Melo** [comment]
Testei o código e no print abaixo, eu cliquei em uma `li`. Ela foi exibida normalmente:

![image](https://user-images.githubusercontent.com/29297788/148794012-80249799-77f2-44c4-83ed-202fb5fc99c1.png)

Aparentemente seu código está correto (`event.target` funcionando normalmente). Esse é o resultado que vc esperava?

---

Qual navegador vc está usando?

Lembre-se que nas primeiras aulas eu recomendei usar o chrome.

Há diversas diferenças entre navegadores e, uma delas é a forma como os elementos são visualizados no console.

Se vc usa um navegador diferente, a visualização dos elementos será diferente. É importante que vc siga à risca o que é recomendado nas aulas, ok? =)

@MivlaM

**Comment by MivlaM** [comment]
O resultado esperado era para ser como o mostrado no seu print, se você clicar nas reticências entre o sinal de fechamento e de abertura da li, o texto aparece por inteiro certo? Todavia, o meu console exibe um resultado um pouco diferente e quando clicado ele abre aquela lista de propriedades.

![sample02](https://user-images.githubusercontent.com/82729897/148795814-80a82f1c-3a1e-481b-9d32-8752de9e7df1.png)

O navegador que eu uso é o Firefox, e até então, não tinha tido nenhum problema com a maneira que os códigos são exibidos no meu console. Tudo o que testei nas aulas funcionou perfeitamente bem.

Sim, eu me lembro que você recomendou usar o Chrome, às vezes alterno entre ele e o Firefox, mas se for necessário posso utilizá-lo unicamente.

**Comment by MivlaM** [comment]
O resultado obtido no Google Chrome é como o que você mostrou.
![Sample03](https://user-images.githubusercontent.com/82729897/148798908-e995193c-3159-4ec8-ba9a-e4a07d0b6b36.png)

Acho que o problema era esse mesmo. Eu estive usando tanto o Chrome quanto e Firefox anteriormente, e, só agora que fui ter essa diferença na hora de exibir os códigos.

Eu agradeço encarecidamente pela ajuda. =)

**Comment by Roger-Melo** [comment]
Show!

Não use firefox.

Os usuários das suas aplicações provavelmente usarão chrome. 

Pq vc escolheria testar sua aplicação em um navegador diferente do que o seu usuário usa?

Atualmente, 6 em cada 10 pessoas usam o chrome. Fonte [aqui](https://www.oberlo.com/statistics/browser-market-share).

![image](https://user-images.githubusercontent.com/29297788/148799762-0d8b4ad1-5409-4407-bf00-c70ec64598c5.png)

---

Segue à risca o passo a passo recomendado nas aulas que é sucesso =)

@MivlaM
