### ISSUE TITLE
Caracteres especiais estão errados no VS Code

### ISSUE THREAD

**Issue by VictorAlvesBug** [roger-melo-treinamentos/curso-de-js-roger-melo#27]
Boa tarde, estou iniciando o curso hoje e ao clonar o diretório do git pra minha máquina e abrir no vs code, os caracteres especiais vieram com a codificação errada, como posso resolver isso?

Exemplo:
/*
01 - Neste diretÃ³rio (exercicio-01), hÃ¡ um index.html vazio.

FaÃ§a o seguinte:

- Declare uma marcaÃ§Ã£o HTML bÃ¡sica nele;
- Modifique a linguagem para portuguÃªs do Brasil;
- Remova as meta tags desnecessÃ¡rias;
- Modifique o title para "ExercÃ­cio 01";
- E linke este arquivo, app.js, antes do fechamento da tag body.
*/

**Comment by VictorAlvesBug** [comment]
Consegui.

Basta clicar aqui, caso esteja com outro texto:
![image](https://user-images.githubusercontent.com/27698497/92508000-40c66900-f1de-11ea-8e14-bee27491a14d.png)

Save with Encoding:
![image](https://user-images.githubusercontent.com/27698497/92508083-66ec0900-f1de-11ea-9845-456e0743f223.png)

Digitar "UTF-8" e selecionar esta opção:
![image](https://user-images.githubusercontent.com/27698497/92508172-8f740300-f1de-11ea-88e4-a2e82e4cc475.png)

**Comment by Roger-Melo** [comment]
Boa @VictorAlvesBug!

No que precisar é só chamar aqui =)
