### ISSUE TITLE
Dúvida geral

### ISSUE THREAD

**Issue by LordMan0** [roger-melo-treinamentos/curso-de-js-roger-melo#270]
Tudo certo, professor?

Talvez você possa reclamar do título da issue desta dúvida não seguir o template, mas é porque não encontrei um vídeo de uma etapa específica que fala sobre isso, então peço desculpas.

Gostaria de perguntar sobre a URL do local host que é usado em todas as aulas! Você poderia me dizer como que faço para alterá-la ou fazer com que ela se torne igual as URL's dos sites que pesquisamos direto no Google? Ou, melhor ainda, como que funciona essa situação dos links dos sites, como eles existem e são organizados? 

Tava pensando em criar um site, por hobby, que pudesse ser pesquisado no Google, mas acabei parando nessa interrogação e por isso gostaria de pedir por ajuda.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Não precisa se desculpar, estou aqui para ajudar você =)

O primeiro passo para você ter uma url personalizada "seunomeaqui.com.br", por exemplo, é registrar um domínio no [Registro BR](https://registro.br/).

Depois que fizer isso, você vai precisar hospedar os arquivos HTML, CSS e JS do seu site em um servidor. Aqui é onde entra [este](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-20/app.js#L68) tutorial do Netlify que deixei na primeira aplicação do treinamento. À partir do quinto vídeo dessa playlist, ele fala como fazer isso. Mas claro, para entender é necessário ter acompanhado a playlist desde o primeiro vídeo.

Sacou a ideia?

@LordMan0

**Comment by LordMan0** [comment]
Saquei, pelo visto toda a playlist é importante ('^^)
Vou ver ela por completo então. Obrigado pela ajuda!

**Comment by Roger-Melo** [comment]
O que precisar, é só dar o toque =)
