### ISSUE TITLE
Aplicação: To do list

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2703]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Kmkery/To-Do-List.git

### Maiores dificuldades durante a implementação

Me confundi um pouco ao fazer referência dos elementos input com base no event.target,  esqueci-me de atentar à questão do tipo de evento (submit, input). No eventListener atrelado ao **form de adicionar to do**, foi necessário inserir a propriedade `name` do respectivo input ao event.target, para então acessar seu valor por meio do `value`, e no eventListener atrelado ao **form de busca** não.

### Menores dificuldades durante a implementação

Referenciar os elementos da página e adicionar os listeners de eventos.

**Comment by Roger-Melo** [comment]
Olá @Kmkery.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Kmkery!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

Mesmo com as dificuldades que vc listou, é perceptível que vc pegou bem a lógica até aqui. 

Os nomes das suas variáveis também estão bem descritivos, e isso deixa o código mais legível.

Sua análise tem poucas observações =)

Olha só...

---

## Destructurings aninhados

Tome cuidado com destructurings aninhados como esse:

```javascript
const searchTodo = ({ target: { value: inputValue } }) => {
  // ...
}
```

Não é o caso aqui, mas vão ter momentos em que vc pode precisar usar uma das consts aninhadas, e isso não é possível:

```javascript
const searchTodo = ({ target: { value: inputValue } }) => {
  console.log(value) // Uncaught ReferenceError: value is not defined at HTMLUnknownElement.searchTodo
}
```

---

## Lógica de pesquisa dos to-dos

A lógica de pesquisa dos to-dos ficou bem simples, muito bom =)

Se achar que fica mais legível, é possível remover o else (e eliminar um bloco):

```javascript
const searchTodo = ({ target: { value: inputValue } }) => {
  const todosArray = Array.from(todos.children)

  todosArray.forEach(todo => {
    const inputIsNotInTodos = !todo.textContent.toLowerCase().includes(inputValue.toLowerCase())

    if (inputIsNotInTodos) {
      todo.classList.add('hide')
      return
    }
    
    todo.classList.remove('hide')
  })
}
```

Não pense no elefante rosa.

Por mais que a frase acima tenha pedido para vc não pensar no elefante rosa, as chances são que vc pensou no elefante rosa quando leu.

Isso acontece pq geralmente nosso cérebro tende a processar melhor uma afirmação do que uma negação. 

Considerando isso, um ajuste que vc pode fazer se achar mais legível é evitar usar uma negação como condição.

```javascript
const searchTodo = ({ target: { value: inputValue } }) => {
  const todosArray = Array.from(todos.children)

  todosArray.forEach(todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().includes(inputValue.toLowerCase())

    if (shouldBeVisible) {
      todo.classList.remove('hide')
      return
    }
    
    todo.classList.add('hide')
  })
}
```

---

## Concisão e legibilidade

Se vc preferir, a condição de remoção do to-do pode ficar mais concisa:

```javascript
// antes
const removeTodo = ({ target }) => {
  const classOfClickedElements = Array.from(target.classList)
  if (classOfClickedElements.includes('delete')) {
    target.parentNode.remove()
  }
}
```

```javascript
// depois
const removeTodo = ({ target }) => {
  const removeIconWasClicked = Array.from(target.classList).includes('delete')

  if (removeIconWasClicked) {
    target.parentNode.remove()
  }
}
```

A vantagem que vejo nessa refatoração é que além do código ficar mais conciso, a condição no if fica menos extensa e mais descritiva.

---

Como eu disse antes, seu código tem poucas observações a serem feitas. 

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Kmkery** [comment]
Oi Roger, obrigada pela análise, fizeram sentido sim.

Sobre o destructuring aninhado, resolvi fazer a fim de treino mesmo, pois é um recurso que certamente eu esqueceria com o tempo, bem como o de renomear a propriedade (para não ficar somente value, renomeei para inputValue para eu enxergar).

Sobre o if/ else, verdade, eu me esqueço que dá para utilizar return e remover o else.

A forma como vc sugeriu (de não usar a negação na condicional) também é melhor, pois certamente na distração e correria eu poderia não me atentar ao `!` e quebrar alguma coisa no código.

Vou alterar os arquivos com as sugestões que vc fez, a gente (sozinho) sempre olha e acha que não dá para otimizar mais a legibilidade, mas de fato não tinha me atentado, fica bem melhor da forma como vc disse =D

**Comment by Roger-Melo** [comment]
Sim, às vezes ficamos tão focados no código que possíveis soluções não vem. É sempre bom ter um segundo olho.

No que eu puder ajudar, é só abrir uma nova issue =)
