### ISSUE TITLE
Duvida sobre o funcionamento interno da computed property names

### ISSUE THREAD

**Issue by fabiaov** [roger-melo-treinamentos/curso-de-js-roger-melo#2704]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 03 da etapa 11 - Aula 04-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1296231

### Descreva a dúvida

Roger, tive duvidas no funcionamento da computed property names, no caso, eu entendi que quando vc usa o `acc[person.age]`

quando vc usa o `acc[person.age]` vc esta tentando acessar uma propriedade de acc que não existe, e se não existe essa propriedade ele cria correto?, a terceira duvida é se o `person.age` é um number ao fazer o `acc[person.age]` , ele converte esse `person.age` de number pra string por debaixo dos panos?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @fabiaov!

Quanto ao funcionamento das computed property names, [dá uma olhada nessa resposta](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563#issuecomment-999110064) que dei para a dúvida deste aluno.

Se ainda restar alguma dúvida sobre isso, pode perguntar aqui que te ajudo =)

---

> ### a terceira duvida é se o `person.age` é um number ao fazer o `acc[person.age]` , ele converte esse `person.age` de number pra string por debaixo dos panos?

As regras para nomear uma propriedade de objeto são as mesmas regras para a nomeação de variáveis:

- deve começar com uma letra, underscore (_) ou cifrão ($)
- caracteres subsequentes podem ser dígitos (0-9)

Porém, se uma variável/propriedade não deve começar com número, como vc explicaria isso?

```javascript
const obj = {
  1: 'olá'
}

console.log(obj[1]) // 'olá'
console.log(obj['1']) // 'olá'
```

Na real, por baixo dos panos, há uma coerção acontecendo ali. 

Propriedade e valor entre `[]` são transformados em um mesmo tipo de valor (string) e comparados. Nessa lógica, '1' é igual a '1', então o valor da propriedade é retornado.

Dito isso, é importante vc saber que isso existe (para tirar o máximo de proveito da linguagem), mas nesse momento, não recomendo ir além. 

Focar em entender mecanismos internos da linguagem vai te fazer enxergar coisas até legais, mas que não serão úteis no momento de construir suas aplicações.

O que vc precisa saber nesse momento de sua jornada pra chegar na fluência está no CJRM. Confia no processo =)

Ficou mais claro?

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
