### ISSUE TITLE
WEATHER APPLICATION - REENVIO

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#2710]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/marcosyoggy/WEATHER-APPLICATION---REENVIO

### Maiores dificuldades durante a implementação

 - seguir um padrão definido, criando features diversas a fim de 'estilizar' o código, dando uma identidade pessoal, crendo que isso  ajudaria na avaliação;

 - ler o meu próprio bloco de código, momentos depois de fazer funcionar, com sérias dificuldades na refatoração;

 

### Menores dificuldades durante a implementação

 - fazer uma idéia funcionar, mesmo com um amontoado de linhas de código;

 - buscar uma solução usando os meios disponíveis( MDN,  Bootstrap) ;

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy.

Parabéns pelo esforço em reconstruir a terceira aplicação do treinamento =)

> ### seguir um padrão definido, criando features diversas a fim de 'estilizar' o código, dando uma identidade pessoal, crendo que isso ajudaria na avaliação;

O que mais ajuda em uma análise de aplicação é comprovar que vc de fato aprendeu o que foi mostrado até aqui. 

Fica mais complicado avaliar isso quando o aluno quer inovar antes de aprender os fundamentos.

Parabéns por ter feito o simples que funciona =)

---

> ### ler o meu próprio bloco de código, momentos depois de fazer funcionar, com sérias dificuldades na refatoração;

Refatoração vem com a prática. O mais importante num primeiro momento é fazer funcionar mesmo, como vc fez.

---

## Value vs placeholder

Ter que limpar "Quintana" antes de inserir qualquer cidade é um ponto negativo no aspecto de usabilidade. 

Só um placeholder já é o suficiente para o usuário entender o nome da cidade como exemplo.

E olhando o HTML, vc colocou uma placeholder mas deixou o value, o que não faz sentido.

```html
<!-- antes -->
<input type="text" placeholder="city name" name="inputCity" value="Quintana" autofocus>
```

```html
<!-- depois -->
<input type="text" placeholder="Ex: Quintana" name="inputCity" autofocus>
```

---

## Comentários e linhas em branco

Não deixe comentários e linhas em branco desnecessárias no seu código. 

O weather.js tem 4 linhas em branco no final e app.js tem 17.

O index.html tem 55 linhas de código e 102 de comentários e linhas em branco.

Se vc não ficar atento, isso se torna um hábito. 

E quando se torna um hábito, é muito fácil vc enviar um teste técnico desse jeito e a pessoa que analisa o código ter a impressão que vc é desorganizado, o que prejudica vc num processo seletivo.

---

## Font awesome

Não encontrei uso do font awesome na aplicação.

Pq vc está carregando essa lib através do código abaixo sendo que ela não está sendo usada?

```javascript
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/018be57abf.js" crossorigin="anonymous"></script>
```

---

## Mais linhas em branco

O início dos seus arquivos .js contém linhas em branco. 

Por que?

É esperado que o início de um arquivo seja preenchido com linhas de código. 

Se não há algum motivo razoável para não seguir esse princípio, não vejo motivo para não segui-lo.

---

## Ternário

Princípio: use ternários para fazer algo com o valor que eles retornam.

Quando você precisar de um valor baseado em uma expressão, use ternário.

Sabendo disso, ao invés de usar o ternário para remover uma classe CSS (em que o valor que o ternário retorna não está sendo aproveitado), prefira apenas fazer um if:

```javascript
// antes
// O valor retornado pelo ternário não está sendo aproveitado
displayInfoCard.classList.contains('d-none') ? displayInfoCard.classList.remove('d-none') : null
```

```javascript
// depois
const displayCard = () => {
  if (displayInfoCard.classList.contains('d-none')) {
    displayInfoCard.classList.remove('d-none')
  }
}
```

Novamente, nada está sendo feito com o valor que o ternário abaixo retorna:

```javascript
// antes
IsDayTime ? day_Image.src = "./src/day.svg" : day_Image.src = "./src/night.svg"
```

Observe que se vc aplicar o princípio que mencionei ali em cima, além de usar o ternário de forma mais eficiente, vc elimina a repetição desnecessária da atribuição à `src`:

```javascript
// depois
day_Image.src = IsDayTime ? "./src/day.svg" : "./src/night.svg"
```

---

## Code styling

Seu código contém constantes declaradas em camel case e snake case.

```javascript
// ...
const localTemperature = document.querySelector('[data-app="temperature"]')
const day_Image = document.querySelector('[data-app="time"]')
// ...
```

Há algum motivo ou convenção para essa distinção?

Também há strings declaradas com aspas simples e duplas:


```javascript
const displayCard = () => {
  if (displayInfoCard.classList.contains('d-none')) {
    displayInfoCard.classList.remove('d-none')
  }
}

form.addEventListener("submit", event => { /* ... */ }
```

Qual é o motivo disso?

---

## Nomes

Lembra do princípio que mencionei [nessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1404#issuecomment-894733496), no tópico "Nomes de variáveis e funções"?

`urlCity` e `urlConditions` não devem ser nomes de funções, pq são substantivos. 

Nomes de funções precisam ser verbos que descrevem a ação que a função faz.

Se ao ser invocada, `urlCity` retorna a url da cidade, ela pode ser nomeada como `getUrlCity`.

Se ao ser invocada, `urlConditions` retorna a url das condições climáticas, ela pode ser nomeada como `getUrlConditions`.

A ordem das palavras em inglês nos nomes não está correta, mas fica mais legível e padronizado com o `Url` logo após o `get`.

---

## Consistência ao refatorar

No código abaixo, foi criada uma função `getInfoCityWeather` que apenas encapsula o request.

```javascript
const getInfoCityWeather = async inputData => {
  const response = await fetchURL(getUrlCity(inputData))
  return response
}

const infoCityData = async inputData => {
  const [{ Key, LocalizedName }] = await getInfoCityWeather(inputData)
  const [{ IsDayTime, WeatherText, WeatherIcon, Temperature }] = await fetchURL(getUrlConditions(Key))

  // ...
}
```

Pq vc fez essa refatoração?

A resposta da pergunta acima não serviria para encapsular em uma nova função o request executado na segunda linha da `infoCityData`?

Se o motivo da criação de `getInfoCityWeather` for legibilidade, por exemplo, pq não foi criada uma segunda função com o mesmo propósito que encapsule `await fetchURL(getUrlConditions(Key))`?

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação, não se preocupe muito com isso agora.

Mais uma vez, parabéns pelo esforço =)

**Comment by marcosyoggy** [comment]
...se esse código estava "meio" bagunçado...fico imaginando a análise do 1º que eu enviei....Grato pelo feedback!!!

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
