### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2713]
`Node.textContent`: É uma propriedade que irá acessar um node text e retornar seu texto independentemente de sua visibilidade.

`Node.classList`: É uma propriedade que obtém um objeto chamado DOMTokenList que similar a um array.

`Node.classList.add()`: É um método do objeto DOMTokenList usado para adicionar uma classe em uma tag HTML correspondente ao argumento recebido do tipo String.

`Node.classList.remove()`:É um método do objeto DOMTokenList usado para remover uma classe em uma tag HTML correspondente ao argumento recebido do tipo String.

`Node.classList.toggle()`: Se o elemento não possui uma classe correspondente ao argumento do tipo String passado como argumento, essa classe será adicionada. Se o elemento já obtém uma classe correspondente ao argumento, a classe será removida.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota, rumo à fluência! 🎯
