### ISSUE TITLE
Aplicação: [Conversor Moedas]

### ISSUE THREAD

**Issue by mcrodrigo** [roger-melo-treinamentos/curso-de-js-roger-melo#2714]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/mcrodrigo/conversor-moedas.git

### Maiores dificuldades durante a implementação

Atribuir um valor predefinido para o segundo select

### Menores dificuldades durante a implementação

atribuir os eventos para cada um dos elementos da pagina

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @mcrodrigo!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

Mesmo com a dificuldade que vc listou, é perceptível que vc pegou bem a lógica até aqui. Os nomes das suas variáveis também ficaram bem descritivos. Sua aplicação tem poucas observações, parabéns!

---

## Possível refactoring na `makeOptionElement`

Como `makeOptionElement` é uma função que apenas retorna os options, talvez faça sentido encapsular o próprio retorno do reduce nela e renomeá-la como `getOptions`, por exemplo:

```javascript
// antes
const makeOptionElement = (acc, [key, value]) => acc + `<option value=${value}>${key}</option>`

const fillCurrencyOptions = rates => {
  const currencyOptions = rates.reduce(makeOptionElement, '')

  currencyOne.innerHTML = currencyOptions
  currencyTwo.innerHTML = currencyOptions
}
```

```javascript
// depois
const getOptions = rates => rates.reduce((acc, [key, value]) => 
  acc + `<option value=${value}>${key}</option>`, '')

const fillCurrencyOptions = rates => {
  const options = getOptions(rates)

  currencyOne.innerHTML = options
  currencyTwo.innerHTML = options
}
```

Veja qual opção vc acha que fique mais legível e/ou faça mais sentido.

---

## Queries no DOM

A forma que vc fez de pegar os options que foram inseridos no DOM e só em seguida marcar um option como selecionado ficou organizada. 

O único ponto negativo nisso é que inserir esses elementos e depois fazer uma nova query no DOM para obtê-los exige mais processamento do browser. 

Nas aulas seguintes, vc verá uma forma de evitar isso e poderá avaliar o que faz mais sentido pra vc =)

---

## Possível refactoring em `logConversionResult`

Como `logConversionResult` na verdade está exibindo o resultado da conversão, ela pode ser renomeada para `showConversionResult`.

E na real, `makeConversion` é um nome que meio que camufla a ação mais relevante que está acontecendo (exibir a conversão na tela). 

Exemplo:

```javascript
currencyOneTimes.addEventListener('input', makeConversion)
```

Olhando por essa perspectiva, talvez faça mais sentido renomear `makeConversion` para `showConversionResult` e deixar o código da antiga `showConversionResult` dentro da nova `showConversionResult`:

```javascript
// antes
const showConversionResult = (times, conversionResult) => {
  const { text: currencyOneText } = currencyOne[currencyOne.selectedIndex]
  const { text: currencyTwoText } = currencyTwo[currencyTwo.selectedIndex]

  convertedValue.textContent = `${conversionResult.toFixed(2)}`
  conversionPrecision.textContent = `${times} ${currencyOneText} = ${conversionResult} ${currencyTwoText}`
}

const makeConversion = () => {
  const { value: times } = currencyOneTimes
  const { value } = currencyTwo[currencyTwo.selectedIndex]
  const conversionResult = value * times

  showConversionResult(times, conversionResult)
}
```

```javascript
// depois
const showConversionResult = () => {
  const { value: times } = currencyOneTimes
  const { value } = currencyTwo[currencyTwo.selectedIndex]
  const conversionResult = value * times
  const { text: currencyOneText } = currencyOne[currencyOne.selectedIndex]
  const { text: currencyTwoText } = currencyTwo[currencyTwo.selectedIndex]

  convertedValue.textContent = `${conversionResult.toFixed(2)}`
  conversionPrecision.textContent = `${times} ${currencyOneText} = ${conversionResult} ${currencyTwoText}`
}
```

Fazendo isso, na linha abaixo por exemplo, fica mais claro que quando há um input em `currencyOneTimes`, o resultado da conversão é exibido:

```javascript
currencyOneTimes.addEventListener('input', showConversionResult)
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

E mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by mcrodrigo** [comment]
Sim. As observações fizeram sentido.
 
 
 
-----Original Message-----

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
