### ISSUE TITLE
Resumo da Aula Factory functions e composição de objetos - Aula 03-09 da etapa 14

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2715]
A *factory function* é uma alternativa mais direta de se compor objetos em JavaScript. Uma *factory function* é qualquer função que não é uma classe, não é uma função construtora, não é um construtor mas retorna um novo objeto. Qualquer função pode retornar um objeto, e quando essa função faz isso sem te obrigar a utilizar a palavra chave *new*, ela é uma *factory function*. Com *factory functions* eu consigo criar e compor objetos de forma mais simples. Abaixo vamos ver a criação de um usuário utilizando classe e *factory function*:

```jsx
// utilizando classe
class User {
	constructor(name, email) {
		this.name = name
		this.email = email
	}
}

// utilizando factory function
const createUser = (name, email) => ({
	name,
	email
})

const user = new User('Monica', 'monica@friends.com');
const user2 = createUser('Phoebe', 'phoebe@friends.com')

console.log(user, user2)
```

Numa *factory function* também temos a possibilidade de ter propriedades privadas. Lembrando que criamos uma propriedade privada para que só o código da classe ou da função acesse diretamente esse dado privado. Numa classe eu uso o *private field* utilizando uma *hash* como prefixo do nome da propriedade. Numa *factory function* basta criar a informação dentro da função que automaticamente ela não poderá ser acessada por fora do escopo da função. Vamos relembrar como isso é feito numa classe e ver como ficaria numa *factory function*:

```jsx
// utilizando classe
class User {
	#counter = 0

	constructor(name, email) {
		this.name = name
		this.email = email
	}
}

// utilizando factory function
const createUser = (name,email) => {
	let counter = 0

	return {
		name,
		email
	}
}
```

No código mostrado acima, as duas propriedades contadores não podem ser acessadas do lado de fora de seus escopos, portanto é dessa forma que podemos ter uma propriedade privada dentro de uma *factory function*. Mas como fazemos para criar métodos dentro de uma *factory function*? Vamos ver como criar um método que incremente o contador que criamos, e retorna esse valor já incrementado.

```jsx
// utilizando classe
class User {
	#counter = 0

	constructor(name, email) {
		this.name = name
		this.email = email
	}

	incrementCounter() {
		return ++this.#counter
	}
}

// utilizando factory function
const createUser = (name, email) => {
	let counter = 0

	return {
		name,
		email,
		incrementCounter: () => ++counter
	}
}
```

No exemplo acima, utilizando *factory function*, para termos um método, apenas declaramos uma propriedade `incrementCounter` que retorna uma *arrow function* que incremente o contador. E independente de quantos objetos forem criados a partir de uma *factory function*, cada uma terá o seu próprio contador. E isso é possível por causa de um mecanismo da linguagem chamado *closures*. Uma *closure* é a combinação de uma função com seu escopo léxico. E escopo léxico, utilizando a *factory function* acima como exemplo, é todo o escopo que envolve a declaração da minha *arrow function* da `incrementCounter`. Como nessa *arrow function* eu uso uma `let` que foi declarada no escopo léxico, essa *arrow function* agora é uma *closure*. Porque ela é uma combinação de uma função com seu escopo léxico.

As duas abordagens tem vantagens e desvantagens. Porém vou citar uma vantagem da *factory function* sobre classes. Numa classe, se for necessário utilizar o conceito de herança, a subclasse obrigatoriamente herda todas as propriedades e métodos, e mesmo que você não queria um ou outro método ou propriedade, você é obrigado a herdar, não há opção para isso. Já numa *factory function*, eu consigo selecionar o que preciso através da composição. Veja um exemplo de composição abaixo:

```jsx
const a = {
	first() {
		return 1
	}
}

const b = {
	second() {
		return 'não'
	}
}

const c = {
	third() {
		return 3
	}
}

const obj = {
	...a,
	...c
}

console.log(obj)
```

No exemplo acima, criamos três `const` que armazenam cada uma, uma função diferente. Então podemos criar um novo objeto `obj` que retorna um novo objeto e que através do *spread operator* espalha o método `first()` da `const a` e o método `third()` da `const c`. Então eu posso usar essa técnica para criar objetos com as combinações de métodos que eu quiser, fazendo com meu código fique mais flexível.

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🎯
