### ISSUE TITLE
Constantes, variáveis e comentários - Aula 01-06

### ISSUE THREAD

**Issue by Cleyson** [roger-melo-treinamentos/curso-de-js-roger-melo#2718]
Variáveis-> São objetos que ficam armazenado na memória do computador.
OBS: o termo antigo era var.

- Já let e const são os termos atuais.
- JS sempre executa de cima para baixo o código.
  O sinal de = é de atribuição. 

let age = 43 -> //Deixa age armazenar 43
let currentYear = 1978
console.log(age, currentYear)

age = 18
console.log(age)

const points =100
console.log(points)

var score = 75
console.log(score)

**Comment by Roger-Melo** [comment]
Excelente @Cleyson, rumo à fluência! 🎯
