### ISSUE TITLE
Resumo da Aula Timestamp e comparações 01-036 da etapa 10

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2733]
Podemos comparar dois _timestamps_ para obtermos a diferença em milissegundos entre eles, por exemplo, comparar um timestamp baseado na data atual e um timestamp de uma data passada.

Para criarmos um objeto com uma data passada, usamos o mesmo construtor `Date()`, mas fornecendo-lhe um argumento contendo a data desejada (mês, dia, ano, horas:minutos:segundos), em _string_. Encadeando a ele o método `.getTime()`, obtemos os milissegundos passados desde 01/01/1970 até a data determinada. Assim, comparando este com o objeto com a data presente (também encadeado com `.getTime()`), podemos obter a diferença entre as duas datas e convertê-la para o formato de data.

```js
const past = new Date('May 1 2020 7:47:00')
const present = new Date()
const difference = present.getTime() – past.getTime()
const seconds = Math.round(difference/1000) // dividir por 1000 (pois está em milissegundos) e arredondar o valor considerando o digito significativo
const minutes = Math.round(seconds/60)
const hours = Math.round(minutes/60)
const days = Math.round(hours/24)
```
Para converter um _timestamp_ em um objeto de data, inserirmos seu valor como argumento de um novo `Date()`. 
Sintaxe:
```js
console.log(new Date(valor_do_timestamp) // exibe dia da semana, mês, dia, ano, horas:minutos:segundos e fuso horário a que o valor do timestamp corresponde
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery , rumo à fluência! 🎯
