### ISSUE TITLE
Aplicação: Quiz Iterativo

### ISSUE THREAD

**Issue by bindwkill** [roger-melo-treinamentos/curso-de-js-roger-melo#2737]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/bindwkill/Quiz-Iterativo

### Maiores dificuldades durante a implementação

* Pensar em um tema (sou muito indeciso com essas coisas)
* Alterar e centralizar as coisas com o bootstrap/css

### Menores dificuldades durante a implementação

* A lógica para avaliar as respostas era bem simples
* Exibir na tela o resultado foi mais fácil do que imaginei que seria

**Comment by Roger-Melo** [comment]
Olá @bindwkill.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @bindwkill!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

Faz sentido que suas maiores dificuldades tenham sido com CSS, pq deu pra perceber que vc pegou bem a lógica até aqui.

E mais do que isso, vc fez o simples que funciona. Muitas pessoas querem inovar na hora de construir uma aplicação e acabam se atrapalhando, pois algumas firulas acabam evidenciando que os fundamentos não foram realmente aprendidos. O que é o oposto do seu caso. 

Sua análise tem poucas observações =)

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Vc deixou mais claro o progresso do usuário em relação à pontuação total ao exibir a pontuação em porcentagem. Isso é bom para a usabilidade, pq traz clareza do progresso do usuário no quiz.

Outra sacada interessante que vc fez em relação à usabilidade foi a de posicionar a mensagem dos pontos no local onde o usuário está olhando ao enviar o quiz.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Linhas em branco

Talvez seja interessante vc começar a treinar deixar um pouco mais de linhas em branco no código.

Linhas em branco indicam, visualmente, a separação entre conceitos. 

Sabendo disso, você pode separar mais os conceitos no código abaixo, por exemplo:

```javascript
// antes
form.addEventListener("submit", event => {
  event.preventDefault()
  let total = 0
  const respostasDadas = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value
  ]

  // ...
})
```

```javascript
// depois
form.addEventListener("submit", event => {
  event.preventDefault()

  let total = 0

  const respostasDadas = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value
  ]
  
  // ...
})
```

---

## Nomeação de parâmetro do callback do `forEach`

O parâmetro do callback do `forEach` pode ser nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Observe a diferença na leitura:

```javascript
// antes
respostasDadas.forEach((resposta, index) => {
  if (resposta === respostasCertas[index]) {
    total += 25
  }
})
```

```javascript
// depois
respostasDadas.forEach((respostaDada, index) => {
  if (respostaDada === respostasCertas[index]) {
    total += 25
  }
})
```

---

Como eu disse, sua análise tem poucas observações, e isso é um bom sinal.

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Show! =D

No que precisar, é só abrir uma nova issue.

Conte comigo para acelerar sua chegada na fluência =)
