### ISSUE TITLE
Resumo da Aula Retornando valores - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#274]
As funções podem retornar um valor que pode ser utilizado no decorrer da aplicação. Para fazer a função retornar algo é necessário inserir a palavra-chave *return* antes do valor que desejamos retornar. Esse valor retornado pela função é obtido todas as vezes que a função é invocada.

```jsx
const double = function (number) {
	return number * 2
}

console.log(double(3)) // 6
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Vamo que vamo, rumo à fluência @sou-gabriel! 🚀
