### ISSUE TITLE
Resumo da Aula Conhecendo a date fns 02-03 da etapa 10

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#2742]
A **date fns** é uma biblioteca para manipular de forma mais fácil e rápida objetos do tipo date.
Para fazer uso da biblioteca, atualmente é necessário baixá-la via npm (gerenciador de pacotes do Node.js), mas nesta aula usamos a versão 1.9.0 que é a última na qual ainda há a disponibilização de uso via CDN. Na página do _date-fns.org_, selecionada a referida versão, copiamos e colamos no arquivo html a primeira tag script com o link da biblioteca, substituindo a palavra VERSION pela versão a ser utilizada.

Ao executar um `console.log(dateFns)`, o console exibe um objeto com todos os métodos e propriedades disponíveis na biblioteca.

A sintaxe de uso da biblioteca é:
**`dateFns.metodo(data)`**
 onde _método_ refere-se ao método fns e _data_ a constante que armazena o objeto date.

Exemplos de uso da biblioteca:
- Verificar se uma data corresponde a data atual, pelo uso do método **`.isToday()`** passando como argumento a data desejada.
- Formatação da data, utilizando o método **`.format()`**, que recebe três argumentos: a data que queremos formatar, o _token_ (formato, em string) e o um objeto que contém as opções de idioma da data (este último, opcional).
- Comparação entre datas, usando o método **`.distanceInWords()`**, que recebe três argumentos: as duas datas a serem comparadas, começando pela mais recente e depois a mais antiga (argumento 1 e argumento 2, respectivamente) e um objeto contendo opções da formatação disponibilizadas pelo dateFns (argumento opcional).

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
