### ISSUE TITLE
Aplicação: projeto To-do list

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2748]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Jonatan1103/projeto-Todo-List/blob/main/projeto-Todo-List/app.js

### Maiores dificuldades durante a implementação

 - Fazer o item ser excluído ao clicar na lixeira: A lógica na cabeça até estava certa, mas na hora de colocar no código ficava meio perdido.
 - refactoring: senti mais facilidade do que o da outra aplicação, porem não quer dizer que foi fácil...kkkk.

### Menores dificuldades durante a implementação

 - fazer as manipulações do DOM.
 - fazer os addEventListener.
 - usar o método filter.

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

Mesmo com as dificuldade em fazer o item ser excluído, vc conseguiu. Além disso, no geral os nomes que vc dau às variáveis ficaram descritivos e vc demonstrou ter pegado bem a lógica até aqui.

Sobre o refactoring, vou sugerir uma possibilidade bem legal ali em baixo =)

---

## Diretório do index.html

A raiz/diretório inicial do seu projeto deve ter um index.html, exatamente como é mostrado nas aulas. Caso contrário, ao invés da página inicial com o to-do list, a listagem de diretórios da aplicação é exibida, o que não é o desejado.

![image](https://user-images.githubusercontent.com/29297788/150049777-01ca54fa-0118-4af1-a2b8-891e7c449cfc.png)

---

## Linhas em branco em excesso

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco `67` e `5`.

---

## Indentação

Indentação é um dos pilares para um código mais legível.

Para deixar a marcação HTML de um template string mais legível, o ideal é que ela seja indentada.

Dá uma olhada no antes e depois.

```javascript
// antes
const createTodoLists = (event, inputValue) => {
  if (inputValue.length) {
    todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center" data-list="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt" data-delete="${inputValue}"></i>
    </li>
    `
    event.target.reset()
  }
}
```

```javascript
// depois
const createTodoLists = (event, inputValue) => {
  if (inputValue.length) {
    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center" data-list="${inputValue}">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt" data-delete="${inputValue}"></i>
      </li>
    `
    event.target.reset()
  }
}
```

---

## Possível refactoring em `removeTodo`

Vc sacou o `dataset`. Ótimo!

Um pequeno refactoring que vc pode fazer na `removeTodo` é buscar o to-do no DOM apenas se ele de fato tiver que ser removido. Assim vc elimina uma query desnecessária no DOM caso o elemento clicado não seja o de remoção do to-do =)

```javascript
// antes
const removeTodo = event => {
  const clickedElement = event.target
  const dataAttribute = clickedElement.dataset.delete
  const elementOfTodo = document.querySelector(`[data-list="${dataAttribute}"]`)

  if (dataAttribute) {
    elementOfTodo.remove()
  }
}
```

```javascript
// depois
const removeTodo = event => {
  const clickedElement = event.target
  const dataAttribute = clickedElement.dataset.delete

  if (dataAttribute) {
    const elementOfTodo = document.querySelector(`[data-list="${dataAttribute}"]`)
    elementOfTodo.remove()
  }
}
```

---

## Padrão de nomenclatura mais simples

Pra simplificar as coisas e manter um padrão, eu renomearia `elementOfTodo` para `todo`:

```javascript
// antes
if (dataAttribute) {
  const elementOfTodo = document.querySelector(`[data-list="${dataAttribute}"]`)
  elementOfTodo.remove()
}
```

```javascript
// depois
if (dataAttribute) {
  const todo = document.querySelector(`[data-list="${dataAttribute}"]`)
  todo.remove()
}
```

---

## Possível renomeação de funções

Como existe apenas uma lista de to-dos e o que é exibido ou ocultado são os itens dessa lista (to-dos), `hideLists` e `showLists` podem ser renomeadas como `hideTodos` e `showTodos`.

---

## Método que não foi mostrado nas aulas

`toLocaleLowerCase` não foi mostrada nas aulas e o desafio é vc construir as aplicações do treinamento apenas com o que foi visto nele.

Nesse caso, a opção `A aplicação contém features da linguagem que não foram mostradas nas aulas?` ali em cima deveria ser marcada com `Sim`.

Locale é um set de preferências de um idioma para uma interface de usuário. O que não é necessário nesse caso. 

`toLowerCase` é um método que, além de te dar o mesmo resultado neste caso, tem menos caracteres a serem digitados e lidos.

---

## Ortografia

`mateched` é uma palavra que não existe. Talvez vc queria ter nomeado a const como `matchedTodo`.

---

## Possível refactoring em `searchTodoInList`

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições e tantas quebras em funções (em alguns casos, isso pode aumentar a complexidade do código).

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodoInList = event => {
  const inputValue = event.target.value.toLowerCase().trim()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean 
  que indica se o to-do deve ficar visível */

  // hideTodos(todos, inputValue)
  // showTodos(todos, inputValue)
}
```

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodoInList = event => {
  const inputValue = event.target.value.toLowerCase().trim()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Jonatan1103** [comment]
Perdão pela demora de responder. Como sempre você foi pontual. irei anotar essas sugestões, e implementa-las no projeto. Muito obrigado e rumo a fluência
