### ISSUE TITLE
Aplicação: [Quiz-Interativo]

### ISSUE THREAD

**Issue by aisl1n** [roger-melo-treinamentos/curso-de-js-roger-melo#2749]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/aisl1n/Quiz-interativo

### Maiores dificuldades durante a implementação

Acredito terem sido referentes a refatoração em sí; de certa forma se torna  um pouco maçante as vezes.

### Menores dificuldades durante a implementação

Estilização e ideias.

**Comment by Roger-Melo** [comment]
Olá @aisl1n.

Passando para dizer que visualizei a issue e em até 5 dias úteis a análise será postada aqui =)
