### ISSUE TITLE
Aplicação: to-do list

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#275]
Segue link da aplicação do to-do list, @Roger-Melo 
https://github.com/gcarniel/to-do

**Dificuldades**
- Dar nome às variáveis.
- Refatorar código.
- Exclusão de itens, pois não saberia fazer por conta (não a parte de excluir por data).

**Facilidades**
- Pegar elementos HTML com o dom.
- Métodos de arrays já estão ficando mais claros.
- AddEventListener é simples também.
- Adicionar item ao to-do.

**Curiosidade**
Sei que aqui não é o espaço, mas eu desenvolvo no note da empresa e as vezes no meu, porém no meu muitos atalhos são diferentes, sabe me dizer como resolver?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel. 

Passando para dizer que sua issue foi visualizada e se estiver tudo ok com a aplicação, em breve a análise será postada aqui.

---

Sobre alternar os notes, isso depende do que você precisa configurar. Se for uma modificação de configuraçao de teclado pode ser um pouco mais complicado.

Agora, se você precisa manter as mesmas configurações do VSCode nos dois notebooks, [essa](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extensão ajuda bastante =)

@gcarniel

**Comment by gcarniel** [comment]
@Roger-Melo, obrigado. Vou instalar a extensão pra ver.

Fico no aguardo da análise.

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> - Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Fico no aguardo.

@gcarniel 

Ps: e a extensão, rolou?

**Comment by gcarniel** [comment]
Olá, @Roger-Melo 
Peço desculpas por isso, vou corrigir o quanto antes e te informo aqui.
O e-mail está salvo, porém não li ele antes, eu assisti ao vídeo. 

Sobre e extensão ontem eu estava fuçando e descobri que o VSCode consegue sincronizar através do GIT, agora ficou show. 
Sobre o atalho descobri o motivo, era uma extensão de keymap de outro editor de texto, removi e deu certo.

Obrigado.

**Comment by gcarniel** [comment]
Pronto, @Roger-Melo, as cores foram trocadas.

**Comment by Roger-Melo** [comment]
Legal @gcarniel. Em breve publico a análise aqui =)

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

Pelo que analisei, se você conseguiu implementar a aplicação sozinho, está no caminho certo. Mesmo com as dificuldades de refatoração que você relatou, deu pra perceber que você está atento à lógica e questões importantes de organização de código, como os locais das declarações das variáveis e as linhas em branco.

Outro ponto indício de progressão é que você não cometeu os mesmos "erros" observados na análise da aplicação anterior. 

Minhas únicas observações estão relacionadas aos nomes das variáveis. Vou deixar algumas oportunidades de melhoria abaixo. Mas que fique claro, não é nada grave. São apenas pequenos ajustes de refinamento. 

---

### Objetividade ao nomear variáveis

`eventSubmitAddItem`, `eventInputSearchItem` e `eventClickRemoveItem` podem ser mais objetivas. 

Traduzindo para o português, os nomes delas seriam parecidos com `eventoDeSubmitAdicionaItem`, `eventoDeInputBuscaItem` e `eventoDeClickRemoveItem`. Perceba que elas não expressam diretamente o a ação que executam.

Então uma possível solução é eliminar o prefixo `event` e o tipo de evento do qual a função é um callback, e especificar que o item que está sendo manipulado é um to-do:

- `addTodo`;
- `searchTodo`;
- `removeTodo`;

```javascript
inputTextAddTodo.addEventListener('submit', addTodo)
inputTextSearchTodo.addEventListener('input', searchTodo)
todosList.addEventListener('click', removeTodo)
```

Outro possível ajuste seriam `hideItemTodo` e `showItemTodo`. Seguindo o mesmo padrão acima, elas podem ser renomeadas como `hideTodos` e `showTodos`. Sugiro que seja no plural pois ao pesquisar um to-do, um ou mais to-dos podem ser exibidos e/ou escondidos.

### Ordem das palavras

Em inglês, as palavras são escritas em uma ordem diferente da língua portuguesa.

Os adjetivos geralmente são inseridos antes dos substantivos. Exemplo: "Casa bonita." fica "Beautiful house."

Isso significa que na verdade, `inputSearched` deve ser `searchedInput`.

Porém, para deixar mais explícito e direto, eu nomearia essa const apenas como `inputValue`. Ou no máximo `searchInputValue`.

### Camel case

Na const `classToremove`, faltou apenas inserir o `R` maiúsculo para que ela siga a convenção camel case.

---

Como eu disse acima, esses pontos de atenção em inglês não são graves. Teriam mais importância se você trabalhar com um time gringo que se comunica em inglês =)

Fez sentido o que eu falei acima?

@gcarniel

**Comment by gcarniel** [comment]
Bom dia, @Roger-Melo 
Opa, faz todo sentindo sim.

Obrigado pela análise e feedback. 

Eu sei que não é certo ficar repetindo nomes como caso do "event", mas optei por manter porque eu estava me perdendo bastante no código, então para ficar mais claro para mim eu deixei com essas nomeações.

E de fato uma das minhas dificuldades tem sido os nomes de variáveis e funções por questão do inglês, nunca fiz curso de inglês, por isso que os nomes acabam ficando assim meio sem nexo, mas já estou vendo algumas coisas de inglês para tentar refinar isso.

Já ajustei o código e subi novamente.

**Comment by Roger-Melo** [comment]
Vi lá, é isso aí garoto. 

Essas dificuldades são naturais. Continue aplicando o método e com a prática e o tempo você verá que as resoluções de vários desses obstáculos com os quais está lidando hoje ficarão automáticas =)

Novamente, parabéns pela aplicação e no que precisar, tô aqui. 

Vou fechar essa issue mas quando houverem dúvidas, abra novas issues =)
