### ISSUE TITLE
Dúvida sobre construtores

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2750]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 02 da etapa 14 - Aula 03-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1811152

### Descreva a dúvida

Olá, Roger! Fiquei com uma pequena dúvida sobre a questão 3 da lista 37. A questão pede para filtrar os itens truthy do array utilizando um construtor, sem declará-lo.

```js
//Meu código
const values = [
  0,
  {},
  '',
  [],
  NaN,
  () => {}
]

class TruthyValues {
  constructor (value) {
    this.value = value
  }

  get truthyValue () {
    return this.value ? this.value : false
  }
}

const truthyValues = values.filter(value => new TruthyValues(value).truthyValue)
console.log(truthyValues)

```

Este código é válido para resolver a questão? Eu não usei um construtor como o Boolean para filtrar, e sim um ternário, mas eu usei o constructor na hora de criar a class TruthyValues. Onde eu errei? Estou com um nó na cabeça.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

> ### Olá, Roger! Fiquei com uma pequena dúvida sobre a questão 3 da lista 37. A questão pede para filtrar os itens truthy do array utilizando um construtor, sem declará-lo.

#### Sem declará-lo não. Sem **invocá-lo**.

```javascript
/*
  03
  - A partir do array abaixo, gere um novo array com apenas os valores truthy;
  - Utilize um construtor para resolver este exercício;
  - Não invoque o construtor.
*/
```

---

> ### Este código é válido para resolver a questão?

Classes e construtores fazem basicamente a mesma coisa, mas o fato é que o enunciado pede que um construtor seja usado, e não uma classe =)

Não faz sentido criar uma classe que retorna o boolean de um valor sendo que a linguagem já tem um construtor nativo pra isso.

**Comment by YureK-a** [comment]
Entendi, valeu!
