### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2751]
### Etapa da aula

14

### Nome da aula

Prototypes - Aula 03-07

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1886432

### Descreva a dúvida

Olá, Roger! Acabei de ver a aula sobre os prototypes e estou com algumas dúvidas. É melhor usar classes ou funções construtoras? Você disse na aula que class foi criado para as pessoas de outras linguagens, de forma que diminuísse o desconforto. Eu não conheço outra linguagem, mas acho que prefiro class por ser mais fácil de bater o olho e saber o que está acontecendo. É comum ter essa impressão no começo?

Segunda dúvida: sobre inserir funções no prototype de uma função construtora, eu estou tentando entender como eu faria para uma função do prototype receber um parâmetro da função construtora. Exemplo:

```js
function User (name, age, time) {
  this.name = name
  this.age = age
}

User.prototype.login = function login (time) {
  return `${this.name} logou às ${time}`
}

const yure = new User('yure', 15, '10:59')

console.log(yure.login())
```

Terceira dúvida: o código não ficaria um pouco feio caso eu precisasse adicionar vários métodos no prototype da função construtora? Há uma forma de, por exemplo, armazenar essas adições ao prototype?

Desculpe se a causa das dúvidas for falta de atenção ;)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

> ### Segunda dúvida: sobre inserir funções no prototype de uma função construtora, eu estou tentando entender como eu faria para uma função do prototype receber um parâmetro da função construtora.

Não faria. 

Funções construtoras existem para construir um objeto.

Se os parâmetros que vc declara na função não serão usados como propriedades do objeto que a função vai criar, pq declarar esse parâmetro? Consegue me dizer um caso em que isso faria sentido?

---

> ### Terceira dúvida: o código não ficaria um pouco feio caso eu precisasse adicionar vários métodos no prototype da função construtora? Há uma forma de, por exemplo, armazenar essas adições ao prototype?

Tenha em mente que vc está adicionando métodos `ao prototype do objeto` que a função construtora cria.

```javascript
function Abc () {
  // ...
}

Abc.prototype.method1 = function def () {
  // ...
}

Abc.prototype.method2 = function ghi () {
  // ...
}

console.log(new Abc())
```

![prototype](https://user-images.githubusercontent.com/29297788/149678468-37a0257d-a7fd-4467-9589-282d473cd306.jpg)

Como eu disse na aula, prototype é apenas um objeto que armazena as propriedades e métodos que ficam disponíveis para o novo objeto que a função construtora criou.

Não entendi o que quis dizer com "armazenar essas adições ao prototype".

E sim, antigamente, quando era necessário fazer herança, a forma do código acima era a regra, a não ser que um framework fosse usado.

---

A primeira dúvida será respondida quando vc terminar a etapa 14 e a correção da última bateria de exercícios dela (etapa 15). Vc precisa assistir o filme até o final para que todas as pontas desse roteiro sejam amarradas =)

**Comment by YureK-a** [comment]
Compreendo. Sobre o código, faria sentido se o this referenciasse uma propriedade time, não sendo necessário passar time como argumento da login(), como neste código:

```js
function User (name, age, time) {
  this.name = name
  this.age = age
  this.time = time
}

User.prototype.login = function login () {
  return `${this.name} logou às ${this.time}`
}

const yure = new User('yure', 15, '10:59')

console.log(yure.login())
```

Está correto?

**Comment by YureK-a** [comment]
Vou fechar a issue aqui, suponho que está correto e não hajam adições a serem feitas.
