### ISSUE TITLE
Métodos de Factory Functions X Métodos de Classes

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2755]
### Etapa da aula

14

### Nome da aula

Factory functions e composição de objetos - Aula 03-09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1926080

### Descreva a dúvida

Oi, Roger. 

Acabei de assistir a aula sobre factory functions e elas realmente parecem ser mais simples de se trabalhar. Porém uma dúvida que me ocorreu enquanto estou fazendo os exercícios. 

Em Classes quando declaramos um método ele automaticamente é declarado no prototype dessa classe, correto? Pelo que eu entendi isso acontece para que um novo método não seja criado na memória toda vez que um novo objeto é criado. 

Com funções construtoras também é possível fazer a mesma coisa mas nós mesmos devemos explicitar que o método deve ser adcionado ao prototype da função. 

Porém na aula de factory functions você declarou métodos diretamente no objeto que a função retorna. 
Isso significa que esses métodos serão criados na memória sempre que um novo objeto for criado pela factory function, não?

Isso não causa um problema de performance? E se sim, existem maneiras de contorná-lo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior!

É possível fazer herança com factory functions de uma forma bem flexível, vc verá como fazer isso na aula 02-03 da etapa 15.

Se ao ver essa aula restar alguma dúvida, pode abrir uma nova issue que te ajudo =)

**Comment by Hamiltonspjunior** [comment]
Ok, Roger.
