### ISSUE TITLE
Aplicação: Currency Converter

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2757]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/YureK-a/Currency-Converter

### Maiores dificuldades durante a implementação

Quando o usuário trocava a(s) moeda(s), o valor a ser convertido era sempre 1 unidade. Ou seja. Mesmo que ele tivesse escrito 10 no input, quando estivesse convertendo, por exemplo, de real para dólar e trocasse a moeda para, por exemplo, euro, a conversão iria ser de 1 real para 1 euro.

Isso estava acontecendo por conta do valor default 1 da value do input. Fiquei travado nesse problema e a única solução que encontrei foi tornar a amount uma let, para que quando o input acontecesse, o valor default fosse alterado.

Como já deve ter percebido, eu não converti a fetchData em uma factory function. O motivo é que eu realmente não sei como fazer isso, não devo ter entendido o suficiente do assunto para poder aplicá-lo. Eu imagino que devesse fazer isso, pois há uma questão na lista de exercícios pedindo para fazer isso com uma outra função bem parecida.

Edit: Acabei de ver que eu esqueci de fazer o que foi pedido na data-js="conversion-precision" ;/

### Menores dificuldades durante a implementação

O código, no geral, deu muito pouco trabalho porque foi muito parecido com a weather application, que eu fiz e refiz até demais. 

O refactoring deu pouco trabalho para fazer, apesar de eu acreditar que a convertCurrency() poderia ser melhorada(só não sei como). O mesmo acontece com os listeners de evento, que são, praticamente, idênticos. Portanto, eu acho que existe algum jeito de eliminar essas repetições, só não sei como. 

Eu tive uma certa dificuldade com a escolha dos nomes das consts, por isso há nomes bem parecidos. Não achei um nome melhor do que "yourCurrency" para denominar a moeda a ser convertida.

**Comment by Roger-Melo** [comment]
Olá @YureK-a.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 8 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

---

> ### Quando o usuário trocava a(s) moeda(s), o valor a ser convertido era sempre 1 unidade. Ou seja. Mesmo que ele tivesse escrito 10 no input, quando estivesse convertendo, por exemplo, de real para dólar e trocasse a moeda para, por exemplo, euro, a conversão iria ser de 1 real para 1 euro.

Vou comentar sobre isso mais abaixo.

---

> ### Como já deve ter percebido, eu não converti a fetchData em uma factory function. O motivo é que eu realmente não sei como fazer isso, não devo ter entendido o suficiente do assunto para poder aplicá-lo. Eu imagino que devesse fazer isso, pois há uma questão na lista de exercícios pedindo para fazer isso com uma outra função bem parecida.

Factory function é apenas uma função que retorna um objeto literal. Não haveria como vc ter chegado até essa etapa do treinamento sem saber isso. 

E outra, `fetchData` retorna uma promise, pois ela é uma função async. E funções async sempre retornam uma promise. 

---

> ### Edit: Acabei de ver que eu esqueci de fazer o que foi pedido na data-js="conversion-precision" ;/

Observe também que o enunciado do exercício pede pra que os selects sejam populados com tags `<option>` [**quando a página for carregada**](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-38/app.js#L197). Isso é basicamente o oposto de deixar options estáticos no index.html.

Ler e executar o passo a passo é parte do desafio. Se vc comete esses tipos de erros aqui, provavelmente cometerá lá fora também. Fica ligado.

---

## Funções de callback

Se a única ação que as duas funções de callback abaixo fazem é invocar `changeValue`, pq não apenas referenciar `changeValue` como argumento do addEventListener?

```javascript
// antes
yourCurrency.addEventListener('input', () => {
  changeValue(amount)
})

targetedCurrency.addEventListener('input', () => {
  changeValue(amount)
})
```

Observe que `amount` é uma let global. Por isso a segunda linha dentro da changeValue já acessa amount naturalmente:

```javascript
// depois
const changeValue = async () => {
  const currencyValue = await convertCurrency()
  convertedValue.textContent = `${currencyValue * amount}`
}

yourCurrency.addEventListener('input', changeValue)
targetedCurrency.addEventListener('input', changeValue)
```

O mesmo vale pro callback de input no inputAmount, sendo que ter uma let amount não é necessário, pois é possível obter o valor atual do inputAmount apenas especificando `inputAmount.value`:

```javascript
// antes
inputAmount.addEventListener('input', event => {
  amount = event.target.value

  changeValue(event.target.value)
})
```

```javascript
// depois

// ❌ let removida
let amount = inputAmount.value

const changeValue = async () => {
  const currencyValue = await convertCurrency()
  convertedValue.textContent = `${currencyValue * inputAmount.value}` // 👈🏻 aqui vc pega o valor atual do input
}

yourCurrency.addEventListener('input', changeValue)
targetedCurrency.addEventListener('input', changeValue)
inputAmount.addEventListener('input', changeValue)

changeValue()
```

Só tem um problema...

```javascript
yourCurrency.addEventListener('input', changeValue)
targetedCurrency.addEventListener('input', changeValue)
inputAmount.addEventListener('input', changeValue)
```

No código acima, toda vez que há qualquer mudança nos inputs, changeValue é invocada, changeValue invoca convertCurrency, que invoca fetchData. Ou seja, toda vez que há qualquer mudança nos inputs, um novo request é executado.

Já parou pra pensar o quanto isso pode consumir dados do pacote de dados do usuário se ele não estiver usando sua aplicação no wi-fi?

Nas aulas seguintes, vc verá uma forma de diminuir a quantidade de requests.

---

## Nomes de variáveis e funções

`getConvertedCurrency` é só uma const que armazena valor mas foi nomeada como função (verbo). 

Const/let que não é função deve ser nomeada como substantivo. 

```javascript
// antes
const convertCurrency = async () => {
  const url = getUrl(yourCurrency.value)
  const getConvertedCurrency = await fetchData(url)
  const convertedCurrency = getConvertedCurrency.conversion_rates[targetedCurrency.value]

  return convertedCurrency
}
```

```javascript
// depois
const convertCurrency = async () => {
  const url = getUrl(yourCurrency.value)
  const convertedCurrency = await fetchData(url)

  return convertedCurrency.conversion_rates[targetedCurrency.value]
}
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by YureK-a** [comment]
Olá Roger! A resolução foi esclarecedora! Ontem eu (finalmente) terminei de ver a construção e refatoração da aplicação, então já tenho uma base para fazer outra versão no futuro. No mais, obrigado pela explicação!
