### ISSUE TITLE
Aplicação: [Quiz interativo. Atividade19]

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#2758]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação

https://github.com/CarlosHenrique2208/2-TentativaDaQuest-o19

### Maiores dificuldades durante a implementação

de longe a maior dificuldade foi montar o arquivo HTML e estiliza-lo com o CSS, mesmo usando o Bootstrap eu ainda tive dificuldades com definição de elementos como padding, margin, etc. Levei uns dias só estudando essas coisinhas e ainda sim tive dificuldade.

### Menores dificuldades durante a implementação

o JS é sempre a parte mais fácil nessas, pois estou acostumado com sua logica e estrutura.

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 8 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208!

Parabéns pelo esforço em reconstruir a primeira aplicação do treinamento =)

> ### de longe a maior dificuldade foi montar o arquivo HTML e estiliza-lo com o CSS, mesmo usando o Bootstrap eu ainda tive dificuldades com definição de elementos como padding, margin, etc. Levei uns dias só estudando essas coisinhas e ainda sim tive dificuldade.

Mesmo com as dificuldades, vc conseguiu. Num primeiro momento, o mais importante é fazer funcionar, como vc fez.

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Como vc exibiu a pontuação em forma de porcentagem, ficou bem claro o progresso do usuário no quiz, e isso é bom do ponto de vista de usabilidade.

No geral, você escolheu nomes descritivos para suas variáveis e demonstrou ter pegado bem a lógica até aqui. Sua análise tem poucos ajustes.

---

## Nomeação de arquivos

Não nomeie arquivos como `(feito)`, v1, versão final, nem nada parecido.

Se vc não ficar atento, isso se torna um hábito.

E quando se torna um hábito, é muito fácil vc enviar um teste técnico desse jeito e a pessoa que analisa o código ter a impressão que vc é desorganizado, o que prejudica vc num processo seletivo.

---

## Critérios para que a aplicação fosse analizada

Observe que o [enunciado do exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js#L6) pede pra que a aplicação não seja sobre filmes.

Isso é exatamente o oposto do que foi feito.

Ler o exercício é parte do desafio. Se vc comete esses tipos de erros aqui, provavelmente cometerá lá fora também. Fica ligado.

---

## Alternativas não marcadas por padrão

Acredito que deixar a primeira alternativa de cada pergunta marcada por padrão incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Mas é só uma opinião. Eu deixaria.

Para isso, basta usar o atributo `checked` no input.

---

## Clique no texto não marca o input

O ideal é que o usuário não precise posicionar o mouse e clicar exatamente no input type radio (que é pequeno).

Para que ao clicar no texto da alternativa o input seja marcado, é necessário que as labels tenham uma class ao invés de for, exatamente como é mostrado nas aulas.

```html
<!-- antes -->
<label for="form-check-label">
  <input type="radio" name="inputQuestion1" value="A">
  O magico de OZ
</label>
```

```html
<!-- depois -->
<label class="form-check-label">
  <input type="radio" name="inputQuestion1" value="A">
  O magico de OZ
</label>
```

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by CarlosHenrique2208** [comment]
tá certo, obrigado professor. Vou sim começar a ter mais cuidado ao ler os enunciados.

sobre a observação de como eu salvo o arquivo, o nome dele, o senhor tem alguma dica, alguma sugestão para que eu possa colocar no lugar e identificar qual arquivo é qual arquivo?

(eu tenho o costume de ter um arquivo com notas e observações e outro que o codigo foi refatorado em aula.)

**Comment by Roger-Melo** [comment]
Seus nomes de arquivos devem ser o mais simples possíveis, exatamente como os mostrados nas aulas (index.html, stile.css, app.js, etc).

Para versionar os arquivos, o ideal é que vc use uma ferramenta como o [git](https://youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A).

@CarlosHenrique2208
