### ISSUE TITLE
Aplicação: Currency Converter

### ISSUE THREAD

**Issue by danielscastro** [roger-melo-treinamentos/curso-de-js-roger-melo#2761]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/danielscastro/currency-converter-app

### Maiores dificuldades durante a implementação

Refactoring. Estou constantemente com a sensação de que a solução dada não é a melhor/ideal. O refactoring feito foi o melhor que pude na visão atual que tenho do app.

Também tentei manter o _event.target_ e não utilizar a referência direta dos objetos HTML, mas acabei não conseguindo de forma satisfatória e fiz a decisão de remover do aplicativo esse tipo de referência.

### Menores dificuldades durante a implementação

Por algumas vezes no app, precisei percorrer conjunto de dados dentro de outro conjunto de dados (como array dentro de array). Acredito que a lógica desse tipo de código está bem fixada na minha mente. 

As requisições HTTP usando async/await também estão cada vez mais fáceis de compreender e replicar. A desse código fiz totalmente sem pesquisa/olhar nos códigos anteriores.

**Comment by Roger-Melo** [comment]
Olá @danielscastro.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 8 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @danielscastro!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

---

> Refactoring. Estou constantemente com a sensação de que a solução dada não é a melhor/ideal. O refactoring feito foi o melhor que pude na visão atual que tenho do app.

Sempre haverá essa sensação, o que não é ruim =)

Porém, na minha opinião técnica, pelo que o seu código mostrou, não recomendo que refactoring seja prioridade.

A minha recomendação é que vc foque suas energias em duas coisas: 

1. Mais interpretação de texto;
2. Minimizar a complexidade do seu código. 

Nas aulas seguintes, vc verá que não é necessário, por exemplo, aninhar `forEach`es e `if`s e usar dois `||` na mesma expressão.

Sobre a interpretação de texto, observe que o enunciado do exercício cita também o parágrafo com `data-js="converted-value"`, que não foi usado.

---

## Variáveis globais

Observe que `response` foi declarada sem a palavra-chave `const`.

```javascript
const fetchData = async url => {
  try {
  response = await fetch(url)

  // ...
} // ...
```

As consequências disso já haviam sido foi observadas [nessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2700#issuecomment-1013572602), no tópico `Variáveis globais`.

Fica ligado pra não cometer os mesmos erros.

---

## Requests

Toda vez que há qualquer mudança nos inputs, um novo request é executado.

Já parou pra pensar o quanto isso pode consumir dados do pacote de dados do usuário se ele não estiver usando a aplicação no wi-fi?

Por isso, nas aulas seguintes, vc tb verá uma forma de diminuir a quantidade de requests da aplicação.

---

Essa análise teve poucos ajustes pq os 2 pontos que mencionei lá em cima serão explicados detalhadamente nas aulas seguintes. 

Se possível, após terminar de ver a sequência de aulas de construção dessa aplicação, o ideal é que vc execute [esse passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Fazendo isso, aumentam as chances de que vc realmente entenderá a abordagem que usei para construir essa aplicação. 

Faz sentido?

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
