### ISSUE TITLE
Aplicação: Currencies Conversion

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2765]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ricardopontesdantas/cjrm-currencies-conversion-app

### Maiores dificuldades durante a implementação

Tive que olhar a documentação do MDN para lembrar do `Object.entries()`, pois havia esquecido de como utiliza-lo.
Outra dúvida foi no momento de utilizar o try/catch, onde eu tive a oportunidade de utilizar as respostas de erro da API, mas fiquei em dúvida se eu deveria utilizar as respostas da API ou se verificava o `response.ok`, então preferi manter o que eu já fazia nas aulas, que é a verificação do `response.ok`.
Para refatorar eu tentei ver primeiro as responsabilidades das funções, depois verifiquei blocos com repetição de código, e em seguida criei consts para onde achei necessário, e apesar de ter ido por um caminho mais objetivo dessa vez, ainda tive minhas dúvidas, de saber se o que eu estava fazendo era o certo ou não, se eu precisava fazer mais ou não.

### Menores dificuldades durante a implementação

Seleção de elementos, trabalhar com eventos, fazer requisições HTTP, criar funções, ler a documentação da API e do MDN.

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 9 dias úteis a análise será postada aqui =)

**Comment by ricardopontesdantas** [comment]
Sem problema @Roger-Melo , abraço!

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

> ### e apesar de ter ido por um caminho mais objetivo dessa vez, ainda tive minhas dúvidas, de saber se o que eu estava fazendo era o certo ou não, se eu precisava fazer mais ou não.

Esse tipo de dúvida é natural.

Sempre há como refatorar, mas ao mesmo tempo, é necessário refletir se o saldo da refatoração realmente será significativo.

No caso desta aplicação, vc fez bem. Seus nomes de variáveis estão bons, as funções não estão extensas e é perceptível que vc entendeu bem a lógica para implementar essa aplicação.

Sua análise tem praticamete nenhum ajuste. A única observação que tenho é sobre a consistência no code-styling.

No código abaixo, o parâmetro único da primeira função não está envolvido em parênteses, enquanto o da segunda função, está.

```javascript
currencyToInput.addEventListener('input', event => {
  // ...
});

currencyTimes.addEventListener('input', (event) => {
  // ...
})
```

O ideal é que vc escolha uma das duas formas de declarar parâmetro único e seja consistente nessa escolha no decorrer do código.

Mas como eu disse, é apenas uma observação. Você implementou muito bem essa aplicação, parabéns =)

**Comment by ricardopontesdantas** [comment]
Valeu @Roger-Melo ! Obrigado pela observação, e pelo seu feedback. Fico feliz de estar trilhando um caminho bacana junto aos outros alunos e você.

_*Ao invés de apenas utilizar o botão Comment, quando for para encerrar, posso utilizar direto o Close with comment? Ou é você quem sempre deve encerrar as issues?_

**Comment by Roger-Melo** [comment]
Show! 

> ### *Ao invés de apenas utilizar o botão Comment, quando for para encerrar, posso utilizar direto o Close with comment? Ou é você quem sempre deve encerrar as issues?

Quando o aluno fecha a issue, elas vão automaticamente para a aba de issues fechadas e as chances são de que eu não verei o último comentário, então pode deixar que eu fecho.

No que precisar, é só abrir uma nova issue =)
