### ISSUE TITLE
Dúvida referente a atribição e sintaxe

### ISSUE THREAD

**Issue by ARNOBIOAIRES** [roger-melo-treinamentos/curso-de-js-roger-melo#2768]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/943413

### Descreva a dúvida

Boa Tarde Roger

Bateu uma dúvida cruel,.
passo 1 - Nas linhas abaixo, a tag/elemento p foi criado  e atribuído a  uma constante de nome  p, ok

passo 2 - o setAttribute está incluindo em p uma classe e um nome da classe ok

passo 3 - a dúvida -  a constante feedbackParagraph armazena a referência da tag p que foi criada ?

Trata-se da mesma constante p ?
essa sintaxe utilizada pelo querySelector ?  com '[data-feedback="username-feedback"]'
é porque o elemento p foi criado no js  ?

```js
const p = document.createElement('p')

p.setAttribute('data-feedback', 'username-feedback')

const feedbackParagraph = document.querySelector('[data-feedback="username-feedback"]')

'''


Se possível, uma explicação

Atenciosamene
Arnóbio Aires


<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ARNOBIOAIRES!

> ### passo 2 - o setAttribute está incluindo em p uma classe e um nome da classe ok

Não é nome de classe. 

Atributos `data-*` tem um propósito diferente de classes. 

Classes foram criadas manipular estilos, enquanto atributos data permitem que vc associe informações extras à um determinado elemento. 

Você pode conferir isso [*aqui*](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

---

> ### passo 3 - a dúvida -  a constante feedbackParagraph armazena a referência da tag p que foi criada ?

Sim, mas para o `querySelector` funcionar como vc deseja, primeiro vc precisa inserir a tag `p` no DOM.

Caso contrário, `feedbackParagraph` armazenará `null`, pois null é retornado quando `querySelector` não consegue obter o elemento que vc especificou como argumento.

Você pode visualizar o valor que `feedbackParagraph` armazena simplesmente inserindo ela como argumento de um console.log:

```javascript
const p = document.createElement('p')
p.setAttribute('data-feedback', 'username-feedback')

const feedbackParagraph = document.querySelector('[data-feedback="username-feedback"]')

console.log(feedbackParagraph) // null
```

Hack o restante da sua carreira de desenvolvedor: sempre use o console.log para conferir se uma variável, parâmetro, propriedade ou expressão está de fato armazenando ou resultando no valor que você espera. 

Eu uso o console.log nas aulas não apenas por motivos de didática, mas pq eu codo daquele jeito mesmo. A cada linha de código escrita, eu confiro usando console.log se os valores são o que eu esperava.

---

Lembre-se, como foi falado em [Query selector & query selector all - Aula 01-07](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/842118), o `querySelector` deve ser usado quando vc precisa fazer queries (consultas) no DOM.

Para o querySelector resultar no valor que vc deseja e `feedbackParagraph` de fato armazenar o `p`, basta inserir o `p` no DOM:

```html
<div></div>
```

```javascript
const div = document.querySelector('div')
const p = document.createElement('p')

p.setAttribute('data-feedback', 'username-feedback')
// 👇🏻 p foi inserido no DOM
div.append(p)

const feedbackParagraph = document.querySelector('[data-feedback="username-feedback"]')

// 👇🏻 e agora, p é exibida no console
console.log(feedbackParagraph) // <p data-feedback="username-feedback"></p>
```

---

> ### Trata-se da mesma constante p ?

Com certeza!

---

> ### essa sintaxe utilizada pelo querySelector ?  com '[data-feedback="username-feedback"]' é porque o elemento p foi criado no js  ?

Não. 

`querySelector` e `querySelectorAll` [recebem como argumento qualquer seletor CSS válido](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#parameters). Para selecionar esse elemento no CSS, vc usaria essa notação =)

[Aqui](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) vc encontra uma listagem de seletores CSS.

---

Ficou mais claro?

**Comment by ARNOBIOAIRES** [comment]
Ok, Roger.
Sim ficou mais claro, atributos data* servem para acrescentar informações adicionais a uma tag
e através dessas informações adicionais, fazer referência ao elemento.
ok valeu.

Em relação ao uso do console.log, valeu pela dica.
