### ISSUE TITLE
Resumo da Aula Arrow functions - Aula 02-02 da etapa 03

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#277]
É uma adição do JavaScript moderno que permite a declaração de uma função de forma mais curta e concisa.

Ex.:

```jsx
const multiply = () => {}
```

---

## Sintaxe para os parâmetros

Caso haja apenas um parâmetro, os parênteses que o envolvem podem ser removidos; mas, caso for passado um valor default para este parâmetro, os parênteses devem ser mantidos.

Ex.:

```jsx
const divide = number => {
	return number / 2
}
```

---

## Sintaxe para o retorno

Se o bloco de código da função tiver apenas uma linha retornando algum valor, podemos utilizar o *return* implícito, ou seja, podemos remover a palavra-chave  *return* e as chaves que definem o bloco dessa função.

Ex.:

```jsx
const divide = (number = 0) => number + 2
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Tamo junto @sou-gabriel! 🔥
