### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2782]
`Node.addEventListener()`: É um método que remove um elemento no DOM.

`document.createElement()`: É um método do Document que pode ser usado para criar um novo elemento HTML, como argumento, é passado através de uma String, o nome da tag que será criada.

`parent.append()`: É um método que quando encadeado com um elemento pai, é uma forma de criar um elemento dentro do DOM, passando como argumento a referência do elemento a ser criado. O método irá criar um elemento como o último filho do elemento pai.

`parent.prepend()`:  É outra forma de criar um elemento no DOM, mas como primeiro filho de um elemento pai.

Resumindo, para criar elementos no DOM o primeiro passo, é criar o elemento através do método `createElement()`, depois é setado o conteúdo e atributos deste elemento e então adicioná-lo como primeiro ou último filho de um nó no DOM.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota, rumo à fluência! 🎯
