### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by ARNOBIOAIRES** [roger-melo-treinamentos/curso-de-js-roger-melo#2785]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ARNOBIOAIRES/quiz

### Maiores dificuldades durante a implementação

- Sei que o método forEach é composto de 3 parâmetros, e um deles retorna a posicão no array, (o índice), mas nesse código, o parâmetro está atrelado a outra constante, que faz parte da lógica.

-  Entender porque o parâmetro [index] , está atrelado a constante correctAnwsers .

A pergunta é:  o parâmetro [index] está retornando um índice  de qual constante ?  

 if (userAnswer === correctAnwsers[index]) {
}

### Menores dificuldades durante a implementação

- fazer referencia ao form
- Entender o addEventListener atrelado ao form 
- usar o event.preventDefault()
- entender que a variável score tem que ser do tipo let - porque o valor altera
- entender que o Form acessa o id, ou name de um campo de input, facilitando a iteração

**Comment by Roger-Melo** [comment]
Olá @ARNOBIOAIRES ! 

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Me avise aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by Roger-Melo** [comment]
Olá Arnóbio. 

Devido à falta de resposta, essa issue será fechada.

No que precisar, é só abrir uma nova issue =)
