### ISSUE TITLE
Resumo da Aula 04-01 da etapa 05 Destructuring assignment

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#2786]
Este recurso permite extrair de um Array ou Object valores e transformar em uma variável ou constante.

É comum a necessidade de recuperar um item armazenado em um Array e atribuí-lo a uma variável. Nestes casos podemos fazer como no exemplo abaixo:

```js
const totais = [ 10, 20, 30 ]

  const [ valorA, valorB, valorC ] = totais

  console.log(valorA) // 10
  console.log(valorB) // 20
  console.log(valorC) // 30
```

É possível extrair items de um Array e armazenar o resto:

```js
const [ valorA, valorB, ...valorC ] = [ 10, 20, 30, 40, 50, 60 ]

  console.log(valorA) // 10
  console.log(valorB) // 20
  console.log(valorC) // [ 30, 40, 50, 60 ]
```

Podemos pré-definir valores quando não exista determinado elemento em um Array, para que quando seja feita a extração deste resultado para uma variável ele receba um valor padrão:
```js
const [ itemA = 5, itemB = 10 ] = [ 20 ]

  console.log(itemA) // 20
  console.log(itemB) // 10
```

Podemos extrair valores de objetos literais utilizando o nome de suas propriedades, como no exemplo abaixo:
```js
const usuario = { nome: 'Pedro', idade: 18 }

  const { nome, idade } = usuario

  console.log(nome) // Pedro
  console.log(idade) // 18
```

Podemos também utilizar os valores pré definidos em objetos assim como é feito nos Arrays:
```js
const usuario = { idade: 18, temFilhos: true }

  const { nome = 'Jonas', idade, temFilhos } = usuario

  console.log(nome) // Jonas
  console.log(idade) // 18
  console.log(temFilhos) // true
```

Podemos capturar os resultados que não tenham sido extraídos como variáveis:
```js
const usuario = { nome: 'Pedro', idade: 18, temFilhos: true }

  const { nome, ...outrosDados } = usuario

  console.log(nome) // Pedro
  console.log(outrosDados) // { idade: 18, temFilhos: true }
```
Perceba que ao colocar reticências precedendo a variável outrosDados todos os valores existentes no objeto, exceto o nome, que havia sido extraído, foram adicionados a ela como um novo objeto.

**Comment by Roger-Melo** [comment]
Excelente @ghostnetrn , rumo à fluência! 🎯
