### ISSUE TITLE
Exercício feito de forma diferente

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#2788]
### Etapa da aula

10

### Nome da aula

  Correção dos exercícios da aula 02 da etapa 10

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1154164

### Descreva a dúvida

Boa noite professor, a segunda questão do exercício 26 pedia o seguinte.

<p>- Crie uma função que recebe uma data por parâmetro e retorna o horário e a 
    data na formatação: "03:07 - domingo, 7 de junho de 2020";
  - Não utilize a date-fns.</p> 

<p>Eu comecei fazendo na logica de utilizar arrays, Porem fui olhar a documentação e vi o método toLocaleString(), que pode ser passado um parâmetro options que nele terá um array com as configurações padrão</p>

```js
const optionsDates = { 
  weekday: 'long', 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric'
}

const optionsHours = {
  hour: 'numeric', 
  minute: 'numeric'
}

const returnTimeAndDate = date => {
  const hours = date
    .toLocaleTimeString('pt-BR', optionsHours)

  const dates = date.toLocaleString('pt-BR', optionsDates)

  console.log(`${hours} - ${dates}`);
}

returnTimeAndDate(present)
```

<p>A pergunta é a seguinte, como foi muito diferente da sua resposta, ela também foi bem construída?</p>

@Roger-Melo

**Comment by Roger-Melo** [comment]
@Jonatan1103 o desafio é vc fazer os exercícios e aplicações apenas com o que viu no treinamento. 

Isso já foi falado [nessa sua análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2748#issuecomment-1016038043), no tópico `Método que não foi mostrado nas aulas`.

Não está errado fazer de outra forma, só não está dentro do que eu recomendo.

Na etapa 15 vc verá outras formas de formatar data.

Mas se quiser jogar 100% no método do treinamento, vc deve resolver usando só o que foi visto nele e seguindo [esse passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661).
