### ISSUE TITLE
Aplicação: [To-do List]

### ISSUE THREAD

**Issue by JoaoSald** [roger-melo-treinamentos/curso-de-js-roger-melo#2794]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/JoaoSald/ApplicationTo-doList

### Maiores dificuldades durante a implementação

Demorei para entender a lógica do evento que busca o todo, porém repeti várias vezes que acabei decorando a lógica. Estou com dificuldades de refatorar o código então resolvi deixar assim, bem parecido com a aplicação das aulas.  No listener de submit fiquei com dúvida no porque na hora de obter a referência do valor inserido usamos o **.add** no "evento.target.add.value.trim()", só aceitei que precisava estar ali, pois usaria apenas evento.target.value.trim().

### Menores dificuldades durante a implementação

Minhas menores dificuldades foram com o evento de adicionar os elementos na lista pelo meio do innerHTML, pois acredito que absorvi bem este conteúdo, e também o vento de click para remover o todo da tela.

**Comment by Roger-Melo** [comment]
Olá @JoaoSald.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 9 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @JoaoSald!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ### Demorei para entender a lógica do evento que busca o todo, porém repeti várias vezes que acabei decorando a lógica. Estou com dificuldades de refatorar o código então resolvi deixar assim, bem parecido com a aplicação das aulas.

Vou deixar ali em baixo uma possível abordagem de refatoração da parte do código que busca o to-do.

Porém, não faz sentido vc se preocupar com refatoração enquanto não se certificar que a aplicação funciona no que ela se propõe a fazer. 

Se eu inserir 'fa' no input de busca do to-do, o to-do 'Fazer exercícios físicos' não é exibido. 

![image](https://user-images.githubusercontent.com/29297788/151709016-63ebc36d-8f7b-4a2f-a03f-5103d89786df.png)

Vc sabe pq isso aconteceu?

Não vou te dar a resposta pronta, pois a solução desse problema já foi explicada nas aulas =)

---

> ### No listener de submit fiquei com dúvida no porque na hora de obter a referência do valor inserido usamos o .add no "evento.target.add.value.trim()", só aceitei que precisava estar ali, pois usaria apenas evento.target.value.trim().

`add` é o valor do atributo `name` do input:

```html
<input class="form-control m-auto" type="text" name="add" autofocus />
```

Se vc simplesmente exibir no console o resultado da expressão `evento.target.add`, verá que ela resulta na referência do input que contém o atributo name armazenando `add`:

```javascript
formAddTodo.addEventListener('submit', evento => {
  evento.preventDefault()
  console.log(evento.target.add) // <input name="add" ... >
}
```

Ou seja, `evento.target` resulta na referência do elemento no qual o evento foi disparado (formAddTodo) e ao encadear `.add` nessa referência, vc está especificando que quer obter um input que está dentro do formAddTodo, e esse input contém o atributo name armazenando add.

---

## Hack para o restante da sua carreira de Desenvolvedor

Não sei se chegou a perceber, mas principalmente nas etapas iniciais do treinamento, eu uso o console.log praticamente a cada linha que escrevo para mostrar o valor que uma determinada expressão / parâmetro / variável está armazenando. 

Eu não faço isso só por motivos didáticos. 

Não assuma que suas variáveis ou expressões estão resultando nos valores que vc espera. 

**Sempre use console.log para checar suas variáveis ou expressões**.

Só essa prática já traz bastante clareza de como o código realmente está funcionando e evita que vc seja pego de surpresa.

Nesse caso, vc poderia ir testando no console a expressão `evento.target`, depois `evento.target.add` e ver no que cada expressão estava resultando.

---

Vou deixar abaixo alguns pontos, segundo os critérios que usei para analisar sua aplicação.

---

## Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código. Não é "errado" não fazer, mas tenha em mente que vc está quebrando uma convenção universal ao não fazer e isso pode causar uma certa estranheza por parte de quem está lendo o código. 

Há não ser que vc tenha um motivo forte para não seguir essa convenção, recomendo que a siga. 

---

## `ulList`

`ulList` é redundante, pois `ul` já é uma abreviação de unordered **list**. Vc pode renomear essa const para `todoList`, por exemplo.

---

## Inconsistência ao nomear

Nomear variáveis/parâmetros em idiomas diferentes em uma aplicação denota inconsistência.

Não faz sentido ler um parâmetro `evento` e na linha seguinte, uma variável ser nomeada como `inputValue`.

Escolha um único idioma e seja consistente nessa escolha no decorrer do código.

---

## Legibilidade

A condição do `if` do callback de click na ul pode ser mais legível se for armazenada em uma const que descreve o valor que a expressão retorna.

```javascript
// antes
if (Array.from(clickedElement.classList).includes('delete')) {
  // ...
}
```

```javascript
// depois
if (trashWasClicked) {
  // ...
}
```

---

Uma outra abordagem que vc pode adotar para melhorar a legibilidade do código é nomear os callbacks de eventos. 

Assim, uma outra pessoa que ler o código não precisa ler todo o callback para descobrir o que ele faz, já que isso estará descrito no nome da função:

```javascript
// antes (é necessário ler o código dentro de cada função anônima para descobrir o que ela faz)
formAddTodo.addEventListener('submit', evento => {
  // ...
}

todoList.addEventListener('click', evento => {
  // ...
}

formSearchTodo.addEventListener('input', evento => {
  // ...
}
```

```javascript
// depois
const addTodo = evento => {
  // ...
}

const deleteTodo = evento => {
  // ...
}

const searchTodo = event => {
  // ...
}

formAddTodo.addEventListener('submit', addTodo)
todoList.addEventListener('click', deleteTodo)
formSearchTodo.addEventListener('input', searchTodo)
```

---

## Refatoração da busca de to-dos

Vc pode modificar um pouco da lógica para deixar o código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa executar cada código do passo a passo abaixo junto comigo, ok?

É possível, por exemplo, criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim()
  const todos = Array.from(todoList.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */

  // Array.from(todoList.children)
  //   .filter(todo => !todo.textContent.includes(inputValue))
  //   .forEach(todo => {
  //     todo.classList.remove('d-flex')
  //     todo.classList.add('hidden')
  //   })

  // Array.from(todoList.children)
  //   .filter(todo => todo.textContent.includes(inputValue))
  //   .forEach(todo => {
  //     todo.classList.remove('hidden')
  //     todo.classList.add('d-flex')
  //   })
}
```

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim()
  const todos = Array.from(todoList.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

Mas lembre-se: refatoração é algo secundário. 

O mais importante num primeiro momento é fazer funcionar, vc não pode deixar sua aplicação sem se certificar que a busca está funcionando como o usuário espera. 

E como eu disse lá em cima, a forma com que esse tipo de problema é resolvido já foi explicada nas aulas. É só revisar e vc vai entender como resolver. 

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by JoaoSald** [comment]
sim, todas as observações fizeram sentido. Obrigado pela ajuda, irei refazer o código e aplicar as dicas que foram dadas.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
