### ISSUE TITLE
Correção dos exercícios da aula 03 da etapa 14 - Aula 01-01

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#2796]
### Etapa da aula

15

### Nome da aula

Correção dos exercícios da aula 03 da etapa 14 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1952522

### Descreva a dúvida

Na correção do primeiro exercício ao falar sobre herança prototipal, você diz que podemos fazer isso através da palavra-chave extends, de funções construtoras e a forma que mostrou na correção. Diz que essas formas linkam objetos a outros objetos. A minha dúvida sobre a forma que mostrou é: Isso que é a composição de objetos? Ou composição não tem nada a ver com herança prototipal?

Valeu, obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ricardopontesdantas!

> A minha dúvida sobre a forma que mostrou é: Isso que é a composição de objetos? Ou composição não tem nada a ver com herança prototipal?

Composição é o ato de combinar partes ou elementos para formar um todo.

Toda vez que vc constrói um um tipo de dado não-primitivo, vc está fazendo algum tipo de composição.

Herança prototipal é uma forma de compor objetos. 

Usar spread operator é uma outra forma. 

Usar JSON.stringify e JSON.parse como vc viu na aula 01-03 da etapa 14 é uma outra forma...

No fim, isso são apenas mecanismos para um objetivo: reutilização de código.

Dica: em JS, sempre opte por mecanismos flexíveis de reutilização de código: funções =)

**Comment by ricardopontesdantas** [comment]
Show Roger, muito obrigado pelas explicações.
