### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#2798]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Hamiltonspjunior/currency-converter-app

### Maiores dificuldades durante a implementação

- Descobrir como a Exchange-Rate API funcionava
- Decidir a forma de popular os selects
- Decidir a melhor forma de deixar as opções selecionadas por padrão.
- Refatorar o código: Modularizar, encontrar bons nomes para funções a variáveis, saber quando uma função está com excesso de responsabilidade. 

### Menores dificuldades durante a implementação

- Fazer o request para a Exchange-rate API
- Obter os dados de conversão das moedas
- Manipular o DOM
- Lidar com o evento input

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 9 dias úteis a análise será postada aqui =)

**Comment by Hamiltonspjunior** [comment]
Sem problemas @Roger-Melo. 

Obrigado!

**Comment by Roger-Melo** [comment]
Olá @Hamiltonspjunior!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

Sobre descobrir como a Exchange-Rate API funciona, o desafio era pesquisar mesmo xD

Em geral, boas documentações tem um "Get started". Sempre comece por ele =)

O get started da exchange rate API é o "fast start", primeiro parágrafo listado na página de entrada da doc. Logo no início do parágrafo, há um link `Standard endpoint`.

![exchange-rate-api](https://user-images.githubusercontent.com/29297788/152078125-160b2988-fbd7-4dee-9b7b-fcee0da87554.jpg)

---

> ### Decidir a melhor forma de deixar as opções selecionadas por padrão.

Não sei se vc quis dizer que sabia pelo-menos duas formas e estava se decidindo ou se não imaginava como fazer. Mas o mais importante é decidir isso depois de ter uma primeira versão já funcionando. 

Primeiro faz funcionar, não importa se é a "melhor forma". Esse é um princípio fundamental que vc deve ter em mente.

---

> ### Refatorar o código: Modularizar, encontrar bons nomes para funções a variáveis, saber quando uma função está com excesso de responsabilidade.

Vou dar algumas sugestões ali abaixo, mas no geral, seu código está bom! Eu não faria refatorações significativas. Vc verá que a análise tem poucos ajustes =)

---

## `document.addEventListener('input', ...)`

Vc inseriu um listener de input no document para não ter que inserir em cada input individualmente?

Essa estratégia pode ser frágil em caso de um novo input ser adicionado na aplicação.

```html
<body>
  <input data-js="input2">
  <!-- ... -->
</body>
```

```javascript
const input2 = document.querySelector('[data-js="input2"]')

const updateResults = async () => {
  console.log('disparou')
  // ...
}

// ...

document.addEventListener('input', updateResults)
input2.addEventListener('input', () => console.log('vai disparar o callback dos outros inputs'))
```

![disparou](https://user-images.githubusercontent.com/29297788/152080253-f774663a-803e-4437-a1de-56bf9d9aea44.jpg)

Toda vez que há qualquer mudança nos inputs, um novo request é executado.

Já parou pra pensar o quanto isso pode consumir do pacote de dados do usuário se ele não estiver usando a aplicação no wi-fi?

Por isso, nas aulas seguintes vc verá uma forma de diminuir a quantidade de requests =)

---

## Uso de id

Pq foi declarado um `id="currency-one"`?

Lembre-se que ids penduram variáveis globais no window:

```javascript
console.log(window['currency-one']) // <select id="currency-one" ..."></select>
```

Sempre que possível, o ideal é evitar variáveis globais pois elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e atrapalham a modularidade do código.

---

## Objetos como argumentos

Olhando os argumentos da invocação da função, não fica claro para quê eles serão usados:

```javascript
await getPairExchangeData(currencyOneValue, currencyTwoValue, currencyOneTimesValue)
```

Para deixar mais claro o papel de cada argumento, você pode criar um objeto em que as propriedades descrevem para quê servem esses argumentos. As propriedades podem ter o mesmo nome dos parâmetros que vc havia declarado na função (eles são descritivos).

```javascript
// destructuring inserido no parâmetro
const getPairExchangeData = ({ baseCode, targetCode, amount }) => fetchExchangeRateData(getPairExchangeURL(baseCode, targetCode, amount))

const { conversion_result, conversion_rate } = await getPairExchangeData({
  baseCode: currencyOneValue,
  targetCode: currencyTwoValue,
  amount: currencyOneTimesValue
})
```

O código fica mais extenso, porém, mais legível.

O mesmo pode ser feito na `getPairExchangeURL`.

Nas aulas seguintes, vc verá outra forma de fazer esses requests. Mas a sacada aqui é vc usar esse princípio quando sentir que um objeto pode dar mais legibilidade ao argumento que a função recebe =)

---

## Nomes de variáveis

updateResults pode ser mais específica em relação ao quê ela está atualizando. Não está claro o que "results" de fato significa. Essa const pode se chamar `updateRates`, por exemplo.

Para simplificar, vc pode remover "Data" das consts `fetchExchangeRateData`, `getSupportedCodesData` e `getPairExchangeData`. Esse ajuste encurta mais os nomes e impacta em nada no entendimento do que as funções fazem.

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Hamiltonspjunior** [comment]
Oi, @Roger-Melo 

Obrigado pela análise, as recomendações foram muito boas e fizeram sentido sim. 

> ### Não sei se vc quis dizer que sabia pelo-menos duas formas e estava se decidindo ou se não imaginava como fazer. Mas o mais importante é decidir isso depois de ter uma primeira versão já funcionando.

Sim, eu encontrei mais de uma forma de fazer isso e não sabia qual delas era melhor para usar. Preciso me lembrar desse princípio de primeiro fazer funcionar para depois encontrar a melhor forma. 

> ### Vc inseriu um listener de input no document para não ter que inserir em cada input individualmente?

Sim, foi isso mesmo. Tentei aplicar a técnica de event delegation para evitar insetir em cada um dos inputs, mas não pensei na possibilidade de haver um input que faria algo diferente. Essa observação foi muito boa para pensar nisso nas próximas. 

> ### Já parou pra pensar o quanto isso pode consumir do pacote de dados do usuário se ele não estiver usando a aplicação no wi-fi?

Na verdade cheguei a pensar nisso sim enquanto estava desenvolvendo, porém não encontrei uma forma de contornar o problema. Vou assistir a correção para ver como você fez =)

> ### Pq foi declarado um ```id="currency-one"``` ?

Na verdade esse foi um descuido. Quando eu estava alterando o layout da aplicação havia inserido um label para os inputs e usado o atributo for. Por isso declarei um id para bater com o atributo for dos labels. Porém depois decidir remover os labels mas acabei esquecendo de remover o id.


De novo, obrigado pela análise. 
Agora vou continuar com a correção dos exercícios =)

**Comment by Roger-Melo** [comment]
Excelente meu caro.

No que precisar, estou à disposição =)
