### ISSUE TITLE
parseInt e parseFloat

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#28]
Olá roger,
tenho outra duvida em relação a 'parseInt' e 'parseFloat', na sua aula sobre conversao de tipos, nao vi esses dois metodos para converter strings em numeros inteiros ou flutuantes, esses metodos estão obsoletos ou existe outro metodos para fazer isso?

**Comment by Roger-Melo** [comment]
Oi @Mateus20Barros. Não estão obsoletos não, pode usar à vontade =)

Sobre o `parseInt()`, apenas fique atento às diferenças dele com o `Number()` na hora de fazer a conversão. Falei sobre essas diferenças [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2#issuecomment-573691308).

Respondi sua pergunta?

**Comment by Roger-Melo** [comment]
Oi @Mateus20Barros.

A resposta sanou sua dúvida?

Por agora vou fechar a issue, mas no que precisar, é só dar o toque =)
