### ISSUE TITLE
Dúvida na 1ª questão do exercício 14

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2800]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula 02 da etapa 05 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871191

### Descreva a dúvida

```js
/*
  01

  - Faça com que o texto do h1 do index.html seja exibido com todas as letras  
    maiúsculas.
*/
const title = document.querySelector('h1')
title.textContent = title.textContent.toUpperCase()

```
Roger, porque que é necessário o texto do title receber o próprio texto concatenado ao método `toUppercase()`?
`title.textContent = title.textContent.toUpperCase()` e não dá certo só assim `title.textContent.toUpperCase()`?

@Roger-Melo

**Comment by Roger-Melo** [comment]
@Jansen-Muniz lembre-se de postar código HTML ou CSS quando sua dúvida envolver marcação ou estilo, ok?

Se vc visualizar no console o valor que a expressão abaixo retorna, verá o título com letras maiúsculas:

```html
<h1>Olá</h1>
```

```javascript
const title = document.querySelector('h1')

console.log(title.textContent.toUpperCase()) // OLÁ
```

Ou seja, a expressão `title.textContent` resulta no conteúdo textual do h1:

```javascript
const title = document.querySelector('h1')

console.log(title.textContent) // Olá
console.log(title.textContent.toUpperCase()) // OLÁ
```

Tudo certo até aqui?

---

Só que a propriedade `textContent` pode ser usada como um getter ou setter.

Getter (obtedor) pq ela pode apenas obter o conteúdo textual do elemento, ou setter pq ela pode setar o conteúdo textual do elemento:

```javascript
const title = document.querySelector('h1')

// 👇🏻 usada como setter
title.textContent = 'oi'

// 👇🏻 usada como getter
console.log(title.textContent) // 'oi'
```

---

> ### porque que é necessário o texto do title receber o próprio texto concatenado ao método `toUppercase()`?

`toUpperCase()` é um método que não modifica a string original. Apenas retorna uma nova string, e vc pode ver isso [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase#return_value) (sempre veja a doc de qualquer feature da linguagem que vc tenha dúvidas).

Se `toUpperCase()` não modifica a string original, isso significa que na expressão abaixo, `title.textContent` resultou no conteúdo textual do title e como há uma invocação .toUpperCase() nessa string, `title.textContent.toUpperCase()` resultou na nova string com todos os caracteres maiúsculos.

```javascript
title.textContent.toUpperCase()
```

Só que como eu disse, `toUpperCase()` não modifica a string original. 

A nova string retornada não está sendo aproveitada.

Para a nova string ser de fato inserida no title, vc precisa usar `textContent` como setter. E o valor que a textContent recebe vai ser a nova string com todos os caracteres maiúsculos.

Por isso é necessário fazer com que o retorno de `title.textContent.toUpperCase()` seja atribuído à textContent:

```javascript
const title = document.querySelector('h1')

title.textContent = title.textContent.toUpperCase()
```

**Comment by Jansen-Muniz** [comment]
@Roger-Melo, esqueci de colocar o HTML e o CSS, foi mal. Entendido, valeu irmão ✌🏻
