### ISSUE TITLE
Aplicação: Etapa09: TodoList

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#281]
Quando eu faco uma pesquisa e pressiono Enter a tela atualiza e os li's criados somem.
Tem alguma forma de evitar esse refresh na tela utilizando algo do tipo "preventDefault()"?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Fabio.

Eu preciso testar o código aqui em minha máquina. Você pode subir a aplicação em um repositório do GitHub e enviar o link?

@fabioromagnoli99

**Comment by fabioromagnoli99** [comment]
Ola Roger,

Segue o link

https://github.com/fabioromagnoli99/todolist

**Comment by Roger-Melo** [comment]
Oi Fabio.

Agora sim, entendi sua situação =D

O método `preventDefault()` cancela o comportamento de eventos `cancelable`. E o evento `input` (que é o evento disparado ao modificar o valor do input) não é cancelable.

Tanto é que se dentro da função de callback do listener do input você invocar um `console.log()` que exibe o retorno de `event.cancelable`, `false` é exibido quando o valor do input é modificado:

```javascript
inputSearchTodo.addEventListener('input', event => {
  // ...
  console.log(event.cancelable) // exibe false quando o valor do input é modificado
```

Já o evento do tipo `submit` é um evento cancelable. Ou seja, é um tipo de evento que pode ser ignorado, como se ele nunca tivesse acontecido.

Já que o `preventDefault()` em um evento `submit` é cancelable, você pode apenas adicionar um listener de `submit` no `form` e invocar o `preventDefault()` dentro da função desse listener de evento:

```javascript
formSearchTodo.addEventListener('submit', e => {
  e.preventDefault()
})
```

Assim a página não vai mais ser recarregada quando o form de pesquisa for enviado =)

Ficou mais claro? 

@fabioromagnoli99

**Comment by fabioromagnoli99** [comment]
Valeu Professor!
