### ISSUE TITLE
Sobre confiança

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#2811]
### Etapa da aula

15

### Nome da aula

Exercícios da aula 01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/2532234

### Descreva a dúvida

Olá Roger! Eu acho que é comum pensar isso no começo, mas eu sinto que não estou preparado para o nível em que estou do curso.

Eu estou quase na metade da etapa 15 mas ainda há casos em que eu pulo uma ou duas questões das listas de exercícios, ou que eu não consiga resolver uma questão completamente.

E isso está acontecendo justamente em um período em que minha produtividade caiu bastante. Eu não sei devo dar um tempo para voltar com mais ânimo depois, se devo continuar do jeito que estou ou se devo dar um passo para trás e revisar as etapas anteriores para ver se adquiro mais confiança(apesar de que eu acho que aprendi bem os assuntos das etapas 13 e 14).

Se puder me ajudar, ficarei agradecido. =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a.

Esse sentimento nessa etapa do treinamento não é natural.

Estatisticamente, na etapa 15, [**quando o método foi seguido à risca**](https://youtu.be/Ex6tyWvK0Nc), as pessoas já constróem aplicações web sozinhas e se candidatam à vagas Jr. 

Se vc não está se sentindo confiante nesse estágio, eu sinto que algo possa ter atrapalhado vc no decorrer do treinamento.

Não sei exatamente o motivo, mas é algo que sinto (posso estar enganado).

Aconteceu ou está acontecendo algo que está atrapalhando o seu progresso no treinamento?

**Comment by YureK-a** [comment]
Eu só consigo pensar em 4 motivos: distração, preguiça, idade e escola.

Eu reconheço que sou preguiçoso, perco horas do meu dia com videogame e sou bem jovem(tenho 15 anos).

No entanto eu consigo fazer e refazer todas as aplicações(exceto a currency converter que eu ainda estou devendo) que mostradas no  curso com muita facilidade. A minha versão da currency eu fiz em 2 horas mais ou menos, e o código funcionou, apesar de pequeno e bem incompleto.

Também percebi que sou dezenas de vezes mais produtivo quando estou de férias da escola, tanto que saltei da etapa 13 para a 15 nas minhas duas semanas de férias.

Pretendo terminar o curso e focar em fazer versões das aplicações do curso com mais funcionalidades, além de fazer minhas próprias aplicações. Daqui 2 meses vou entrar de férias de novo, então acho que vou voltar a ser mais produtivo.

**Comment by Roger-Melo** [comment]
Com 15 anos eu já trampava pra ser mais independente financeiramente xD

Mas o fato é que esse desejo de ser financeiramente independente era mais forte do que as outras coisas nas quais eu poderia investir meu tempo. Mas eu estava focado.

Quando entrou no treinamento, vc respondeu que queria começar a trabalhar como programador...

E na real, vc já tem em mãos o mesmo passo a passo de [alunos que conquistaram esse objetivo](https://youtube.com/playlist?list=PLpSJMw6H4PFNMTHMhRyHHME_JZA80vstu).

Se vc estiver seguindo à risca o que eu recomendei [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928), já deve ter se candidatado e recebido feedbacks de recrutadores =)

**Comment by YureK-a** [comment]
Ou seja, não há desculpas. Muito obrigado pela resposta!
