### ISSUE TITLE
Dúvida sobre o método "some()"

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#2814]
### Etapa da aula

5

### Nome da aula

Desenvolvendo um popup - aula 04-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890854

### Descreva a dúvida

Boa tarde professor, tudo bem?

Tenho duas dúvidas:

1 - Em relação ao método some, ao invés de utilizar ele  eu usei o método includes e atingi o mesmo resultado. Gostaria de saber se está errado usar dessa forma.

2 - Eu sinto que perco muito tempo em algumas aulas, toda hora indo e voltando, devido a novos métodos e códigos que sempre vão surgindo. É obrigatório eu decorar todos eles?

Segue abaixo meu código referente à primeira dúvida.

Obrigado!

```js
const button = document.querySelector('button')
const popup = document.querySelector('.popup-wrapper')

button.addEventListener('click', () => {

    popup.style.display = 'block'
    
})

popup.addEventListener('click', event => {

    const classeElementoClicado = event.target.className

    const classNames = ['popup-close', 'popup-link', 'popup-wrapper']

    if (classNames.includes(classeElementoClicado)) {

        popup.style.display = 'none'
    }
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rafaelpradoj. 

> ### 1 - Em relação ao método some, ao invés de utilizar ele  eu usei o método includes e atingi o mesmo resultado. Gostaria de saber se está errado usar dessa forma.

Neste caso, eu apenas aproveitei a oportunidade para apresentar o `some`. Mas sim, o `includes` pode ser usado tranquilamente neste caso e isso deixaria o código mais conciso, afinal, a função de callback não seria necessária =)

A vantagem do `some` é que a função de callback dele te dá a oportunidade de especificar uma lógica mais refinada, saca? Mas nem sempre você precisará disso. 

Na aula 01-02 da etapa 14 eu mostro um exemplo em que é preferível usar o `some` ao invés do `includes` =)

---

> ### 2 - Eu sinto que perco muito tempo em algumas aulas, toda hora indo e voltando, devido a novos métodos e códigos que sempre vão surgindo. É obrigatório eu decorar todos eles?

Vc não precisa decorar, pois à medida em que vc vai usa mais um determinado método, naturalmente a sintaxe dele vai ficando mais familiar pra vc. E tb não há nada de mal em relembrar a sintaxe olhando seu resumo ou o MDN.

Porém, o que vc precisa, de fato, é sacar `quando` deve usar um método ou outro.

E vc consegue entender isso focando na **definição** que eu dou quando apresento um método ou feature da linguagem. 

Ao apresentar o `some`, por exemplo, eu disse que ele retorna um boolean indicando se `algum` (por isso o nome "some") item do array atende a uma condição.

Ou seja, vc deve usar o `some` quando precisar de um boolean que indica se pelo-menos 1 item do array atende a uma condição.

O mais importante é vc entender "porque" usar um determinado método.

Sacou a ideia?

---

E sobre voltar nas aulas, o meu conselho é que vc siga à risca o que recomendei [aqui](https://youtu.be/Ex6tyWvK0Nc), voltando e fazendo revisões nas anotações dos seus resumos =)

**Comment by rafaelpradoj** [comment]
Bom dia professor

Tudo anotado, sua explicação me esclareceu bastante coisa. As vezes fico ansioso e não sigo o ATER direito, vou me atentar mais nesse ponto, obrigado!

**Comment by Roger-Melo** [comment]
Show Rafael.

No que precisar, é só abrir uma nova issue =)
