### ISSUE TITLE
Weather App no Netlify

### ISSUE THREAD

**Issue by LordMan0** [roger-melo-treinamentos/curso-de-js-roger-melo#282]
Olá, professor!
Tudo bem?

Estava fazendo deploy dos apps no site do Netlify, mas ao testar o weather app deu esse erro por causa do request: 

![fetch error](https://user-images.githubusercontent.com/78428088/110856356-4e949e00-8296-11eb-95fa-81189202c131.jpg)

Quando testo pelo live server do VS code a aplicação funciona sem problemas, mas no deploy do Netlify ele dá erro, o que precisa ser feito para arrumar isso?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Gabriel.

Tente adicionar um `s` no final do `http` da url base. Ficaria asism: `https://dataservice.accuweather.com/`.

Se não resolver, grave a tela do seu código e do browser no momento da requisição, por favor.

@LordMan0

**Comment by LordMan0** [comment]
Deu certo, professor!
Muito obrigado!! E pensar que era só um 's' kkkk
Mas agora consegui colocar os três apps no netlify e estão funcionando.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal. Quando novas dúvidas surgirem, é só abrir novas issues =)
