### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by imrochamatheus** [roger-melo-treinamentos/curso-de-js-roger-melo#2821]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação

https://github.com/imrochamatheus/Quiz_Interativo_com_Vanilla_JS

### Maiores dificuldades durante a implementação

- Como adicionei uma nova pergunta no quiz, precisava que a página voltasse ao topo de uma maneira mais suave, porém não sabia como implementar

### Menores dificuldades durante a implementação

- Aplicação dos conceitos aprendidos nas aulas

**Comment by Roger-Melo** [comment]
Olá @imrochamatheus.

A solução de exibição dos pontos que vc implementou está idêntica a que mostrei em aulas **posteriores** ao [aviso solicitando para enviar o quiz](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2829070). 

Como vc explica isso?

**Comment by imrochamatheus** [comment]
Olá @Roger-Melo.

Enviei o link do repositório antes de assistir a aula de implementação do score, porém me descuidei e acabei atualizando o repositório após assistí-la. Pelo desculpas pelo descuido. Segue o link de outro repositório com a versão anterior.

https://github.com/imrochamatheus/Quiz_versao_anterior

**Comment by imrochamatheus** [comment]
> Olá @Roger-Melo.
> 
> Enviei o link do repositório antes de assistir a aula de implementação do score, porém, me descuidei e acabei atualizando o mesmo repositório após assistí-la. Peço desculpas pelo descuido. Segue o link de outro repositório com a versão anterior. Os códigos contidos neste novo repositório correspondem aos enviados junto com o primeiro commit do anterior, realizado ontem pouco antes da abertura dessa issue.
> 
> https://github.com/imrochamatheus/Quiz_versao_anterior

**Comment by Roger-Melo** [comment]
Show @imrochamatheus.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. 

Em até 9 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @imrochamatheus!

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Como adicionei uma nova pergunta no quiz, precisava que a página voltasse ao topo de uma maneira mais suave, porém não sabia como implementar

Vou falar sobre isso ali em baixo. Mas de qualquer forma, nas aulas seguintes, vc verá como implementar essa rolagem pro topo =)

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que alguns cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Local da exibição dos pontos

É importante ficar atento ao local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida em uma parte não-visível da tela:

![image](https://user-images.githubusercontent.com/29297788/152529683-97e649a0-a6e1-4e51-b2a0-9005644c1d69.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

De qualquer forma, nas aulas seguintes você verá uma forma de implementar os pontos =)

---

## Mensagem sobre a pontuação

Você pode dar mais clareza para o usuário sobre a pontuação que ele teve em relação à pontuação total do quiz.

Alguns exemplos de mensagens para trazer essa clareza ao usuário:

- "Você acertou 3 de 5 perguntas"
- "Você acertou 75% do quiz"

---

## 4 espaços vs 2

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

A partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Ternário

Até o ponto do aviso pedindo para que a aplicação seja enviada, ternário não foi apresentado no treinamento.

O desafio é vc resolver os exercícios e implementar suas aplicações usando apenas o que viu no treinamento até o ponto em que vc está.

Não faz sentido analisar ternário nessa aplicação sendo que é uma feature que só foi apresentada na aula 02-01 da etapa 8. E o pedido de envio do quiz está na etapa 7.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover a primeira linha da showScore, que está em branco.

É uma convenção que a primeira e última linha de um bloco sejam linhas preenchidas com código =)

```javascript
// antes
const showScore = score => {

  document.querySelector('.feedbackDiv') 
  ? document.querySelector('.feedbackDiv').remove()
  : ''

  // ...
}
```

```javascript
// depois
const showScore = score => {
  document.querySelector('.feedbackDiv')
    ? document.querySelector('.feedbackDiv').remove()
    : ''

  // ...
}
```

---

## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Você pode ser mais específico ao descrever no nome da const `feedbackMessage` o valor que ela armazena. Ela pode ser renomeada para `scoreMessage`, por exemplo.

```javascript
// antes
  const feedbackMessage = /* ... */

  // ...

  scoreContainer.textContent = feedbackMessage
```

```javascript
// depois
  const scoreMessage = /* ... */

  // ...

  scoreContainer.textContent = scoreMessage
```

`scoreDiv` é um nome que descreve bem o valor que a const armazena, porém, se no futuro vc quiser mudar esse elemento pra uma `section`, por exemplo, o nome perde o sentido e vc terá que renomear.

Neste caso, vc pode pensar de forma um pouco mais abstrata (como fez com a `quizContainer`) e nomear essa const como `scoreContainer`. "Container" é um termo adequado para descrever uma div, uma section, ou qualquer outro elemento usado para conter outros elementos.

```javascript
// antes
const scoreDiv = document.createElement('div')

scoreDiv.classList.add(/* ... */)
scoreDiv.textContent = /* ... */

quizContainer.prepend(scoreDiv)
```

```javascript
// depois
const scoreContainer = document.createElement('div')

scoreContainer.classList.add(/* ... */)
scoreContainer.textContent = /* ... */

quizContainer.prepend(scoreContainer)
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?
