### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#2826]
`regex.test()`: É um método que faz tentativas de mach entre a Regex e a String passada como argumento.

`String.search()`:É um método que recebe como argumento o padrão Regex e que retornará o index no qual o mach aconteceu.

**Comment by Roger-Melo** [comment]
Excelente @RodrigoLimaMota, rumo à fluência! 🎯
