### ISSUE TITLE
Por que o destructuring não funciona como imaginei?

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#2843]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 01 da etapa 11 - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1185989

### Descreva a dúvida

Boa tarde, professor a correção dos exercícios, eu estava implementando o destructuring como você mostrou e aí algo parou de funcionar: o objeto booksBox não estava mais sendo atualizado ao modificar o valor de booksIn na função booksBox.addBooks.
Então, no final da correção você mostrou o porquê de a booksBox.booksIn não estar mais armazenando os novos valores.
Eu entendi o porquê mas fiquei confusa com destructuring de objetos agora, eu acahava que quando mesmo declarando nova constante ou variável apontando para um objeto (tipo let {nome} = pessoa) essa let de alguma forma jogaria qualquer novo valor para objeto pessoa já que objetos são do tipo de referência.
Deu pra entender o que eu quis dizer? Nem eu tô entendendo direito!
Haverá aulas de destructuring em específico? Espero que sim, está bem confuso pra mim.  

```js
const getPluralOrSingular = (quantity, singular, plural) =>
  quantity === 1 ? singular : plural

booksBox.addBooks = (booksQuantity) => {
  let { booksIn, spaces } = booksBox
 // essa declaração não deveria bastar para alterar os valores da propriedade dentro de booksBox? 
 //Não entendo porque não altera.
  if (booksIn === spaces) {    
    return 'A caixa já está cheia'
  }

  if (booksIn + booksQuantity > spaces) {
    const avaliableSpaces = spaces - booksIn
    const fitPluralOrSingular = getPluralOrSingular(
      avaliableSpaces,
      'cabe',
      'cabem',
    )
    const bookPluralOrSingular = avaliableSpaces === 1 ? 'livro' : 'livros'
    
    return `Só ${fitPluralOrSingular} mais ${spaces - booksIn} ${bookPluralOrSingular} na caixa.`
  }

  booksIn += booksQuantity
  console.log(booksIn) // 4
  
  const bookPluralOrSingular = getPluralOrSingular(booksIn, 'livro', 'livros')
  return `Já há ${booksIn} ${bookPluralOrSingular} na caixa`
}

console.log(booksBox.addBooks(4)) // Já há 4 livros na caixa
console.log(booksBox) // {spaces: 5, booksIn: 0, addBooks: ƒ} , aqui booksIn possui 0 livros
```

#### Já se eu fizer:
```js

let people = {
  name: 'João',
  age: 20,
}

let olderPeople = people 
olderPeople.age = 89

console.log(people) 
// {name: 'João', age: 89}
// Também declarei nova avariável e quando reatribuí o valor de age em na olderPeople, a people foi alterada.
```
A minha dúvida é: por que a alteração no valor da booksIn dentro desse destructuring não afeta o valor dentro de booksBox?
Obrigada, professor!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

> ### Haverá aulas de destructuring em específico? Espero que sim, está bem confuso pra mim. 

Não há uma aula exclusiva de destructuring, mas vc ainda verá vários e vários casos de uso onde explico exatamente como o destructuring está funcionando em cada caso. O que vc viu foi apenas uma introdução, não se preocupe =)

---

> ### Eu entendi o porquê mas fiquei confusa com destructuring de objetos agora, eu acahava que quando mesmo declarando nova constante ou variável apontando para um objeto (tipo let {nome} = pessoa) essa let de alguma forma jogaria qualquer novo valor para objeto pessoa já que objetos são do tipo de referência.

Fica ligada nos exemplos que eu vou postar abaixo.

Recomendo que ao invés de apenas ler, vc digite linha a linha e teste cada linha junto comigo, combinado? =)

Na expressão `let {nome} = pessoa`, vc não está atribuindo `pessoa` para a variável `nome`. Então isso é diferente de uma atribuição comum. 

Olha só:

```javascript
const pessoa = { 
  nome: 'Elaine', 
  idade: 15 
}

// 👇🏻 atribui o valor da propriedade 'nome' do objeto pessoa para uma nova const 'nome' (nesse caso, tanto faz ser const ou let)
const { nome } = pessoa
console.log(nome) // 'Elaine'

// 👇🏻 faz 'pessoa2' e 'pessoa' armazenarem o mesmo objeto
const pessoa2 = pessoa
console.log(pessoa2 === pessoa) // true
```

Observe que no destructuring, eu enfatizei `nova` const.

Ou seja, no destructuring acima, foi declarada uma const `nome` que armazena uma cópia do mesmo valor que a propriedade `pessoa.nome` armazena.

Observe que no exemplo do exercício, uma nova let `booksIn` é criada:

```javascript
let booksBox = {
  spaces: 5,
  booksIn: 0
}

booksBox.addBooks = (booksQuantity) => {
  // 👇🏻 neste destructuring, uma let booksIn foi criada
  let { booksIn, spaces } = booksBox
  
  // ...
}
```

`booksBox.booksIn` armazena um tipo primitivo (number). Isso significa que a let `booksIn` criada no destructuring armazena uma cópia do valor de `booksBox.booksIn`.

Ou seja, no exemplo acima, `booksIn` é uma let que armazena zero e `booksBox.booksIn` é uma propriedade que armazena zero.

Se `booksIn` sofre uma reatribuição, ela é apenas uma let que foi declarada dentro da função e que não tem relação alguma com `booksBox.booksIn`. O único ponto em comum entre a let `booksIn` e a propriedade `booksBox.booksIn` é que elas armazenam zero.

```javascript
let booksBox = {
  spaces: 5,
  booksIn: 0
}

booksBox.addBooks = () => {
  let { booksIn } = booksBox

  booksIn = 1
  
  console.log('valor de booksIn:', booksIn, 'valor de booksBox.booksIn:', booksBox.booksIn)
  // valor de booksIn: 1 valor de booksBox.booksIn: 0
}

booksBox.addBooks()
```

let `booksIn` é uma coisa, propriedade `booksBox.booksIn` é outra =)

---

Agora, o que vc pode estar confundindo um pouquinho é o seguinte...

Se `booksBox.booksIn` armazenasse um objeto (tipo de referência), aí sim a let `booksIn` criada no destructuring e a propriedade `booksBox.booksIn` iriam armazenar o mesmo objeto, por que objetos são tipos de referência =)

Olha só:

```javascript
let booksBox = {
  spaces: 5,
  booksIn: { myProp: 1 }
}

booksBox.addBooks = () => {
  // 👇🏻 a let booksIn armazenou o mesmo objeto que booksBox.booksIn armazena
  let { booksIn } = booksBox
  
  console.log('valor de booksIn:', booksIn, 'valor de booksBox.booksIn:', booksBox.booksIn)
  // valor de booksIn: {myProp: 1} valor de booksBox.booksIn {myProp: 1}

  // 👇🏻 a prova que let e propriedade estão armazenando o mesmo objeto em memória
  console.log(booksIn === booksBox.booksIn) // true
}

booksBox.addBooks()
```

Está ficando mais claro?

**Comment by ElaineDelgado** [comment]
Bom dia, professor!
Sim, agora ficou claro!
Eu imaginei que ao fazer "let {nome} = pessoa" eu estava pegando a propriedade 'nome' do objeto pessoa, apontando para a mesma propriedade armazenada, e não criando uma variável nova que armazenava o mesmo valor que "nome" armazenava no objeto pessoa e que só aponta para o mesmo objeto armazenado quando declaro "pessoa2 = pessoa, que aí sim apontam para o mesmo objeto armazenado na memória.
Muito obrigada!!

**Comment by Roger-Melo** [comment]
Show Elaine.

No que precisar, é só abrir uma nova issue =)
