### ISSUE TITLE
Resumo da Aula  Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by EduSouza-programmer** [roger-melo-treinamentos/curso-de-js-roger-melo#2858]
### Constantes, variáveis e comentários.

Variáveis são como contêiner que armazena uma valor, elas podem ser "let", "const" ou "var".
"let" é um modelo de variável que podemos mudar seu valor quando necessário.
 "const" é um modelo de variável onde quando atribuímos um valor, este não pode ser modificado posteriormente.
"var" é um modelo de variável de uma feature antiga do javascript. 

Podemos também inserir comentários utilizando "//" ou "/* */" no código.

**Comment by Roger-Melo** [comment]
Show @EduSouza-programmer. Vamo que vamo, rumo à fluência! 🙌
