### ISSUE TITLE
Etapa 04, nome do vídeo: A palavra-chave this

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#286]
Professor uma dúvida sobre _function declaration_ e _function expression_ me surgiu ao assistir esta aula. Quando criamos um método e atribuímos ele como valor de uma propriedade, temos uma _function expression_, correto? Se sim, posso afirmar que o _this_ referencia o objeto na qual o método foi encadeado se este mesmo método for também uma _function expression_? Pois há um momento na aula em que você diz que ele vai referenciar o objeto literal apenas se o método for uma _function declaration_.

Desde já meus agradecimentos professor!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Passando para avisar que sua issue foi visualizada e será respondida em breve =)

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Eu errei. Quiz dizer "função tradicional" ao invés de dizer "function declaration".

Dentro de um método declarado na forma de uma função tradicional (que usa a palavra-chave `function`), o `this` referencia o objeto no qual a invocação do método foi encadeada:

```javascript
obj.doSomething()
// this dentro do doSomething referencia obj
```

Lembrando que no código acima, o valor do `this` vai permanecer o mesmo independente do método ser declarado com a palavra-chave `function` ou com a sintaxe abreviada.

```javascript
// método declarado com a palavra-chave "function"
const obj = {
  doSomething: function () {
    // ...
  }
}

// ou

// método declarado com abreviação de sintaxe
const obj = {
  doSomething () {
    // ...
  }
}
```

---

Já em arrow functions, o `this` referencia o valor que o `this` do escopo léxico armazena. 

No código abaixo, como `obj` foi declarado no escopo global e como o `this` do escopo global referencia o `window`, a expresão `this.prop1` resulta em `undefined`, por que não existe uma propriedade `prop1` no objeto `window`:

```javascript
console.log(this) // Window {window: Window, …}

const obj = {
  prop1: 'value',
  doSomething: () => this.prop1
}

console.log(obj.doSomething()) // undefined
```

Ficou mais claro?

@sou-gabriel

**Comment by sou-gabriel** [comment]
Ótima explicação professor, saquei a ideia! =)

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
