### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#2893]
====== Template Strings or Template Literals =========================

São strings que permitem expressões embutidas. Aceitam multilinhas e interpolação. São envolvidas por crases, chamadas de backticks. É mais legível devido a sua interpolação de expressões, deixando o código mais simples de ler e fazer manutenção.

```.js
const postMessage = `O post "${postTitle}", do ${postAuthor}, tem ${postComments} comentários.`
```

Ao utilizar concatenação ES5, caso não queira utilizar aspas dentro de aspas para os nomes, é possível utilizar o escape notation para "escapar" o caracter desejado. Ou seja, o javascript interpretará o elemento com escape notation como um caracter e não como um fechamento da string.

```.js
console.log('Você manja do filme \"As branquelas\"?')
```

Quando usar template strings ou concatenação de strings?

Quando não será interpolado variáveis na string ou não será usado aspas ou quebra de linhas, não será obrigado utilizar template strings. Mas se a string sendo criada precisa conter variáveis, aspas ou templates HTML, o uso de template strings facilitará a escrita do código e melhor leitura do mesmo.

**Comment by Roger-Melo** [comment]
Show @santos2408. Vamo que vamo, rumo à fluência! 🙌
