### ISSUE TITLE
Aplicação: WEATHER APLICATION

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#2897]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/zolive72/Weather-Aplication

### Maiores dificuldades durante a implementação

A vezes me atento a pequenos detalhes como por exemplo quand o usuário entre um valor bizarro como (++++++++++++) e acabo perdendo muito tempo. Tenho que praticar a parte das requisições com o fetch, para deixar o código mais conciso como foi mostrado nas aulas. 

### Menores dificuldades durante a implementação

Não tive problema para consumir os dados da API. Espero ter conseguido refatorar os códigos do app.js e deixado mais legível o código em geral.

**Comment by Roger-Melo** [comment]
Olá @zolive72.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta. Em até 10 dias úteis a análise será postada aqui =)

**Comment by zolive72** [comment]
Sem problema, professor.
Tenha uma noite abençoada.

Le mar. 1 févr. 2022 à 21:43, Roger Melo ***@***.***> a
écrit :

**Comment by Roger-Melo** [comment]
Olá @zolive72!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ## A vezes me atento a pequenos detalhes como por exemplo quand o usuário entre um valor bizarro como (++++++++++++) e acabo perdendo muito tempo. 

Isso realmente não deve ser sua preocupação. 

Pelo-menos, não agora.

Inclusive, sua aplicação ficou menos complexa que a da análise passada e parte disso é graças a vc ter se preocupado menos em tratar edge-cases =)

Mais adiante, quando vc estudar sobre testes automatizados e TDD, vc conhecerá o conceito de [happy path e unhappy path](https://youtu.be/e5wX3rs-P1s?t=1664).

Vc verá que o recomendado é testar primeiramente os casos esperados e, depois, os casos inesperados. Fazer essa organização tira um pouco do peso de tentar resolver todos os problemas de uma só vez.

---

> ## Tenho que praticar a parte das requisições com o fetch, para deixar o código mais conciso como foi mostrado nas aulas.

Pelo que seu código mostrou, vc sacou bem o fetch. Não vi nada a ser ajustado no uso dele em sua aplicação.

Seu ternário na atribuição de timeImg.src também foi bem implementado, pq o valor que o ternário retorna foi utilizado =)

---

## 4 espaços vs 2

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

A partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## `cityCardNotDisplay`

Uma forma alternativa de nomear essa função de forma mais descritiva é nomeá-la como `thereIsNoCityCard`.

Observe como fica o uso da const na leitura da condição do `if` e veja qual vc sente que fica mais legível.

```javascript
// antes
  if (cityCardNotDisplay) {
    cityCard.classList.remove('d-none');
  }
```

```javascript
// depois
  if (thereIsNoCityCard) {
    // ..
  }
```

---

## `insertImageAndIconInDOM`

Não é uma regra, mas uma função que contém `And` no nome pode estar fazendo mais do que deveria.

Sempre que possível, o ideal é que uma função tenha uma única responsabilidade.

Um outro problema dessa função (e consequentemente do nome) é a não-descrição do que se trata a imagem ou ícone.

Então, indo por este caminho que vc foi, talvez faça mais sentido criar uma função de responsabilidade única para cada manipulação (imagem e ícone). Vc pode nomeá-las como `showTimeImage` e `showTimeIcon` ou algo do tipo.

---

## Callback de envio do form

Uma abordagem que vc pode adotar para melhorar a legibilidade do seu código é nomear os callbacks de eventos.

Assim, uma outra pessoa que ler o código não precisa ler todo o callback para descobrir o que ele faz, já que isso estará descrito no nome da função:

```javascript
// antes (é necessário ler o código dentro da função anônima para descobrir o que ela faz)
cityForm.addEventListener('submit', async event => {
  // ...
}
```

```javascript
// depois
const showCityWeather = async event => {
  // ...
}

cityForm.addEventListener('submit', showCityWeather)
```

---

## Recomendação de refatoração

Como vc se esforçou para que seu código ficasse mais simples (e conseguiu), vou indicar que vc veja uma possível abordagem de refatoração dessa aplicação.

Não é uma sobreposição ao que vc já fez.

É apenas um ponto de vista para te mostrar possibilidades, através de uma outra abordagem =)

Para entender do que eu estou falando, dá uma olhada no tópico `Uma abordagem possível` [dessa análise](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2342#issuecomment-985200744).

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by zolive72** [comment]
Obrigado Prof. Roger pela coerência das suas observações que li com
atenção.

Já mudei,  no "Settings" do VS Code, a indentação para 2 espaços e segui as
demais recomendações  que deixaram o meu código mais legível (mudança do
nome da variável, nomeação da função de callback do evento, criação de duas
funções de responsabilidade única e refatoração com 2 funções principais :
a primeira obtendo os dados e a outra renderizando-os).
Irei fazer as mudanças no repositório também.

Agradeço mais uma vez pela sua atenção e por todo seu ensinamento dentro do
curso CJRM. Prática é tudo !!! :)
Olivier.

Le mer. 9 févr. 2022 à 22:52, Roger Melo ***@***.***> a
écrit :

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
