### ISSUE TITLE
Comparação estrita e abstrata

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#29]
Roger, lendo um pouco sobre a documentação de igualdade estrita e igualde abstrata me deparei com este caso
`1 != true` // false
`0 != false` // false
Citando este dois exemplos, o comportamento do JavaScript com apenas estes dois números é bem peculiar, por que deste comportamento Roger ? E neste caso, o boolean que é convertido em algum tipo number ou o operando numérico que é convertido em boolean ?
Obrigado desde já!

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Na [aula 04-03 da etapa 01](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/751262) eu mencionei que quando o `==` ou o `!=` são usados, ambos executam conversão de tipos.

Nos exemplos que você citou acima, como o operando à esquerda do `!=` é do tipo number e o da direita é um boolean, o `!=` tenta convertê-los para o mesmo tipo antes de executar a comparação.

Como nas expressões um dos operandos é um boolean, se o boolean é `true`, ele é convertido para `1`. Se o boolean é false, ele é convertido para `+0` (que é o mesmo que `0`).

Então, na expressão `1 != true`, por baixo dos panos, antes de executar a comparação, o `!=` faz isso:

```javascript
1 != 1 // false, por que 1 é igual a 1 (1 == 1 resulta em true)
```

E na expressão `0 != false`, antes de executar a comparação, o `!=` faz isso:

```javascript
0 != +0 // false, por que 0 é igual a 0 (0 == 0 resulta em true)
```

Para evitar dores de cabeça em suas aplicações, sempre certifique-se que os operandos são do mesmo tipo e valor. Ou seja, prefira usar "igualdade-estrita" (`===` e `!==`) ao comparar valores em JavaScript.

Ficou mais claro? Se ainda houver dúvidas é só perguntar =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Sanou completamente minha dúvida Roger, obrigado =)

**Comment by Roger-Melo** [comment]
Show! No que precisar tô à disposição =)
