### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários da etapa 01

### ISSUE THREAD

**Issue by holivei531** [roger-melo-treinamentos/curso-de-js-roger-melo#290]
### → O papel de uma variável é armazenar um determinado valor. Com isso podemos utilizar esse valor armazenado em qualquer lugar.

- Pode ser um nome,  número, email ...

### → Existem formas diferentes de declarar variáveis em JavaScript

- let - o valor pode ser reatribuido
- const - o valor não pode ser reatribuido
- var - o valor pode ser reatribuido ( não é muito utilizada nos dias de hoje )

### → Regras para nomear variáveis

- 01 - Se a variável for duas ou mais palavras, usamos a convenção  camelcase.
- 02 - Nome de variáveis devem conter apenas letras, números, undescores e cifão, o nome não pode começar com número.
- 03 - Nomes de palavras reservadas da linguagem não podem ser utilizadas ex.: let e const
- Dê nomes significativos para suas variáveis

### → Comentários

- Comentário de uma linha - //
- Comentário de múltiplas linhas - /**/

@Roger-Melo

**Comment by sou-gabriel** [comment]
Esse daí é brabo! 🚀 Rumo à fluência!
