### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by almir05** [roger-melo-treinamentos/curso-de-js-roger-melo#2908]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/almir05/cjrm-to-do-list

### Maiores dificuldades durante a implementação

Quebrei muita cabeça mas não consegui implementar os data attributes na aplicação, senti bastante dificuldade. 

### Menores dificuldades durante a implementação

Acho que compreendi um pouco a utilização do ` event.target ` e senti facilidade em desenvolver a aplicação sem precisar consultar os vídeos.

**Comment by Roger-Melo** [comment]
Olá @almir05.

Passando para dizer que visualizei a issue e vou pedir um pouquinho de paciência, pois nesse momento a demanda está muito alta.

Em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @almir05!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Quebrei muita cabeça mas não consegui implementar os data attributes na aplicação, senti bastante dificuldade.

Sem problemas. Na real, o desafio era fazer vc exercitar pesquisar o assunto.

Nas aulas seguintes vc verá por que e como usar atributos `data-*` em suas aplicações =)

---

No geral, seu código ficou muito bom e por isso, essa análise tem poucas observações.

Algumas boas decisões que elevaram o nível de qualidade do seu código foram as seguintes...

Vc se atentou à diferença entre caracteres maiúsculos e minúsculos na comparação de strings no momento da busca do to-do.

Vc limpou o input e deu foco nele novamente após a adição do to-do.

Seus nomes ficaram descritivos.

```javascript
formAddTodo.addEventListener('submit', addTodo)
todosContainer.addEventListener('click', deleteTodo)
inputSearchTodo.addEventListener('input', searchTodo)
```

O código acima ficou bem coerente, pois as funções de callback tem um nome semelhante às consts nas quais os eventos foram atrelados. Exemplo: `searchTodo` e `inputSearchTodo`. Esse padrão entre nomenclatura de const e função favorece o entendimento rápido do código.

---

## Verificação de valor do input ao adicionar um to-do

Se com a const `inputValueContainsContent` vc quer verificar apenas se há pelo-menos 1 caractere no valor do input, vc pode eliminar essa const e usar a `inputValue` como condição:

```javascript
// antes
const addTodo = event => {
  // ...

  const inputValue = event.target.add.value.trim()
  const inputValueContainsContent = inputValue.length

  if (inputValueContainsContent) {
    // ...
  }

  // ...
}
```

```javascript
// depois
const addTodo = event => {
  // ...

  const inputValue = event.target.add.value.trim()

  if (inputValue) {
    // ...
  }

  // ...
}
```

Se vc testar o código acima, verá que ao inserir nenhum caractere ou apenas espaços em branco no input de adição de to-dos e pressionar enter, o if não é executado.

Vc se lembra pq isso acontece? 🤔

---

## Possível abordagem de refatoração

Como vc demonstrou ter pegado bem a lógica até aqui, vou te mostrar uma possível abordagem de refatoração do código que busca os to-dos.

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

É possível criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */

  // hideTodo(inputValue)
  // showTodo(inputValue)
}
```

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode eliminar as funções `hideTodo` e `showTodo` e criar uma única função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação e avaliar o que faz mais sentido pra vc.

Novamente, parabéns pelo esforço =)

As observações ajudaram?

**Comment by almir05** [comment]
Olá, @Roger-Melo!

>### O código acima ficou bem coerente, pois as funções de callback tem um nome semelhante às consts nas quais os eventos foram atrelados. Exemplo: searchTodo e inputSearchTodo. Esse padrão entre nomenclatura de const e função favorece o entendimento rápido do código.

Fico feliz em ler isso, nomear as variáveis ainda está sendo um grande desafio para mim.

>### Se vc testar o código acima, verá que ao inserir nenhum caractere ou apenas espaços em branco no input de adição de to-dos e pressionar enter, o if não é executado.
>### Vc se lembra pq isso acontece? 🤔

Sim, acredito que seja porque quando não inserimos o valor no input, a constante `inputValue` não recebe um valor `truthy` e a condição não é executada.

Também saquei a ideia da criação do array de objetos, implementei e funcionou tudo corretamente. Vou tentar aprimorar mais essa técnica para melhorar o meu refactoring.

Obrigado pela análise e pela dicas, Roger. Até a próxima aplicação! :muscle::fire:

**Comment by Roger-Melo** [comment]
> Sim, acredito que seja porque quando não inserimos o valor no input, a constante inputValue não recebe um valor truthy e a condição não é executada.

Exatamente! `inputValue` nesse caso armazena string vazia (`''`), e string vazia é um valor falsy xD

---

No que precisar, é só abrir uma nova issue =)

Rumo à fluência 🔥
