### ISSUE TITLE
Ordem de execução do operador (%)

### ISSUE THREAD

**Issue by anderson-oliveira-git** [roger-melo-treinamentos/curso-de-js-roger-melo#2909]
### Etapa da aula

1

### Nome da aula

Numbers - Aula 02-05

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/742277

### Descreva a dúvida

Professor, na aula sobre Numbers, foi falado a ordem que javascript executa as operações, mas fiquei em dúvida com relação a operação de modúlo(%) em qual ordem ela se encaixa: 1ª, 2ª, 3ª ou 4ª? 

@Roger-Melo

**Comment by anderson-oliveira-git** [comment]
Entra como divisão?

**Comment by Roger-Melo** [comment]
Olá @anderson-oliveira-git.

> ### Operação de modúlo(%) em qual ordem ela se encaixa: 1ª, 2ª, 3ª ou 4ª?

O operador de `módulo (%)` está na mesma categoria que os operadores de `multiplicação (*)` e de `divisão (/)`. Portanto, numa expressão, o `módulo (%)` tem a ordem de prioridade dos operadores da 3ª categoria.


Você pode conferir mais sobre a ordem de prioridade dos operadores na documentação do MDN, vou deixar o link dessa parte para você dar uma olhada: [Precedência de operadores - MDN.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table/)

---

Faz sentido para você?

**Comment by anderson-oliveira-git** [comment]
Há sim, tinha imaginado que entraria na parte de multiplicação e divisão, mas achei que poderia ser um caso especial. Obrigado!

**Comment by Roger-Melo** [comment]
Show!

No que precisar, é só abrir uma nova issue =)
