### ISSUE TITLE
Resumo da aula Expressões regulares - aula 01-04 da etapa 06

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#2933]
EXPRESSÕES REGULARES

O que são `RegEx` (Regular Expressions)?
R: São padrões de combinações de caracteres usados para validar uma informação inserida pelo usuário.

Site para testar padrões `RegEx`
R: https://regex101.com/

Como declarar uma `RegEx`?
R: /REGEX/

Declarar `RegEx` para dar match em uma única palavra?
R: /^REGEX$/

Dar Match em `RegEx` de A-Z, a-z, 0-9 e no mínimo Y e máximo Z caracteres?
R:/^[a-zA-Z0-9]{min,max}$/

Dar Match em `RegEx` de qualquer caractere com o mínimo Y e máximo Z caracteres?
R: /^.{min,max}$/

Como as `RegEx` podem ser usadas?
- Para `buscas`, encontrando determinados padrões e sequências de caracteres. A busca por um e-mail dentro de um texto, por exemplo.

- Para `validações`, validando valores digitados pelo usuário. Validar campos como email, telefone, senha etc...

- Para `substituições`. Se você digitar seu número de telefone em um campo "telefone" e, automaticamente, ele é formatado com traços e parênteses, foram as `RegEx`.

**Comment by Roger-Melo** [comment]
Boa @rafaelpradoj, rumo à fluência! 🔥
