### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 1

### ISSUE THREAD

**Issue by VictorHugoDC1999** [roger-melo-treinamentos/curso-de-js-roger-melo#2937]
![aula0203](https://user-images.githubusercontent.com/47994068/152400559-3438f256-97e3-4b34-acd6-5856735a5eb6.jpg)

**Comment by Roger-Melo** [comment]
Boa @VictorHugoDC1999, rumo à fluência! 🔥
