### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07 da etapa 05

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#294]
Antes de fazer qualquer manipulação na página devemos buscar e selecionar a referência do elemento que queremos manipular. 

---

## document.querySelector()

Este método é responsável por buscar e selecionar a referência de um elemento por meio de um seletor CSS desse próprio elemento.

### Argumento

Um seletor CSS referente ao elemento que desejamos buscar.

### Retorno

Há dois valores possíveis que este método pode retornar:

- A referência do elemento buscado;
- null, indicando que não foi encontrada a referência do elemento.

---

## document.querySelectorAll()

É utilizado para buscar a referência de múltiplos elementos por meio de um seletor CSS, especificado como argumento.

### Argumento

Seletor CSS dos elementos que desejamos obter a referência.

### Retorno

Um *NodeList* que armazena a referência dos elementos.

---

## NodeList

Trata-se de um objeto semelhante a um array, mas não é um. Ele é uma lista de nós retornada por métodos como *document.querySelectorAll()*, e propriedades como *Node.childNodes*. Existem 2 tipos de *NodeList*, são eles:

- *NodeList ao vivo*: a coleção de nós é atualizada a cada mudança no DOM. Geralmente é retornada pela propriedade *Node.childNodes;*
- *NodeList estático*: a coleção permanece a intacta mesmo que novos elementos sejam adicionados no DOM, ou seja, ela não percebe alterações no DOM. É retornada pelo método *document.querySelector()*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel. Pra cima, rumo à fluência! 💪🏻
