### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#2943]
```.js
let score = '100'

score = Number(score)
// função construtora que converte para número

console.log(score + 1)
console.log(typeof score)

const crazyConvertion = Number('Maçã') // NaN, pois não faz sentido
const crazyConvertion = String(97) // 97 string
const booleanConvertion = Boolean(10) // true, tipo boolean

// Number(), Boolean(), String() converte explicitamente seus valores
```

Number(), Boolean(), String() converte explicitamente seus valores, são funções construtoras.

   - concatenação de string e número resultado em string
   - função construtura a princípio converte um valor para outro
   - typeof verifica o tipo de dado, em algumas situações não é a melhor escolha
   - tentar converter string em número ou vice-versa resulta em NaN

Valores Falsy:
      - false
      - 0
      - "", '', ``
      - null
      - undefined
      - NaN

Qualquer um desses valores convertidos para boolean resultam em false

   Valores Truthy:
      - Qualquer valor que não é Falsy

**Comment by Roger-Melo** [comment]
Boa @santos2408, rumo à fluência! 🔥
