### ISSUE TITLE
Resumo da Aula 02-04 Operadores lógicos da etapa 02

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#2948]
Resumo: Operadores lógicos

OperadoresLógicos( || , && ) -> 

-> O operador lógico || (ou) devolve um boolean verdadeiro se caso uma das condições passadas for verdadeiro. Por exemplo, Eu vou a padaria se eu tiver fome ou alguém me pedir. Então se tiver fome vou a padaria, se alguém me pedir, vou a padaria e se eu tiver fome e alguém me pedir vou a padaria. 

-> O operador lógico && (and) devolve um boolean verdadeiro quando as duas condições resultam em verdadeiras. Por exemplo, vou padaria somente em ultima necessidade, ou seja, quando tiver fome e quando me pedirem. Se caso me pedirem e eu não estiver com fome não vou.
					                                  ---------------------> Essa linha de código com	
OBS: quando temos uma expressao(código || código && código) o and, representa uma expressão e o || (ou) outra.

**Comment by Roger-Melo** [comment]
Boa @EneasFeynlinus, rumo à fluência! 🔥
