### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by holivei531** [roger-melo-treinamentos/curso-de-js-roger-melo#295]
# Métodos comuns de strings

### → Métodos são funções que pertencem a objetos ou tipo de dados específicos.

- lastIndexOf( );

    Obtém o index da ultima ocorrência do caractere que passarmos por argumento

- Ex.:

    const email = ' laracroft@gmail.com ';

    const lastIndexOfA = email.lastIndexOf( 'a' );

- slice( );

    Fatia, pega um pedaço da string

    Recebe dois argumentos o primeiro é a partir de qual indice vamos pegar o pedaço da string, o segundo representa a partir de onde a string deve ser cortada.

    Não altera a string original.

- Ex.:

    const emailSlice = email.slice(0, 9);

    console.log(emailSlice);

    // laracroft

- replace( );

    Substitui o caractere ou conjunto de caracteres de uma string por outro.

    Recebe dois argumentos o primeiro é o caractere que queremos substituir, o segundo argumento é o caractere que vai substituir o caractere que passamos no primeiro argumento.

    Não altera a string original

    - Ex.:

        const emailReplace = email.replace('l', 'y');

        const emailReplace = email.replace('laracroft', 'chun-li');

        console.log(emailReplace);

        // [chun-li@gmail.com](mailto:chun-li@gmail.com)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Parabéns por postar os primeiros resumos, @holivei531! Rumo à fluência 👊🏻
