### ISSUE TITLE
Dúvida na primeira questão do exercício 16

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#2951]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula 04 da etapa 05 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/907614

### Descreva a dúvida

```js
/*
  01

  - Faça com que ao clicar em um dos elementos dentro da div, a mensagem  
    'Clicou na div.' não seja exibida no console.
*/

const div = document.querySelector('div')
const elementsInsideDiv = Array.from(div.children)

elementsInsideDiv.forEach(element => {
  element.addEventListener('click', event => {
    event.stopPropagation()
    console.log('Clicou no filho da div.')
  })
})

div.addEventListener('click', () => {
  console.log('Clicou na div.')
})
```
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="./style.css">
  <title>Exercícios da aula 04 da etapa 05</title>
</head>
<body>
  <div>
    <h1>3 objetos que toda casa brasileira já teve</h1>
    
    <p>TV portátil</p>
    <p>Antena UHF</p>
    <p>Galinha da Maggi</p>
  </div>

  <div class="egg">Mova o mouse aqui dentro</div>
  <button>Mudar cor do ovo</button>

  <script src="./app.js"></script>
</body>
</html>

```
```css
.egg {
  width: 300px;
  height: 300px;
  background: lightblue;
  border-radius: 50%;
  margin: 30px auto;
  text-align: center;
  padding-top: 50px;
}

```
```js
elementsInsideDiv.forEach(element => {
  element.addEventListener('click', event => {
    event.stopPropagation()
    console.log('Clicou no filho da div.')
  })
})

```
Existe diferença entre colocar o `event.stopPropagation()` acima ou abaixo do `console.log`?
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

> ### Existe diferença entre colocar o `event.stopPropagation()` acima ou abaixo do `console.log`?

Para facilitar a leitura do código, é uma convenção e também uma boa prática deixar o método `event.stopPropagation()` como a primeira linha do bloco do callback do `element.addEventListener`. 

Assim, quem ler essa parte do código vai entender de imediato que o clique não vai propagar.

Ou seja, se o padrão é o clique propagar e você coloca no callback que esse clique não deve propagar, por ser uma quebra de padrão, você deve informar isso o mais rápido possível.

---

Faz sentido?

**Comment by Jansen-Muniz** [comment]
Entendido, valeu Mister Roger =)

**Comment by Roger-Melo** [comment]
Show!

No que precisar, é só abrir uma nova issue =)
