### ISSUE TITLE
Aplicação: Quiz interativo do Grêmio

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#296]
- https://github.com/GabrielMerigo/quiz-interativo-master;
- Sem muitas dificuldades;
- Desenvolver e pensar na lógica como um todo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Gabriel.

Passando para avisar que sua issue foi visualizada. A análise da aplicação começará a ser feita e em breve será publicada aqui.

Mas antes, deixa eu dar uma dica.

Sempre que abrir uma issue, seja o mais específico possível, pois assim a comunicação fica mais fluida e fica mais fácil receber ajuda se precisar.

"Sem muitas dificuldades" quer dizer que houveram algumas poucas dificuldades. Então especifique-as.

As issues são registros que fazem parte do seu histórico no treinamento. A comunicação nelas deve ser o mais eficiente possível =)

@GabrielMerigo

**Comment by Roger-Melo** [comment]
Olá Gabriel.

Parabéns pelo esforço em construir sua primeira aplicação no treinamento =)

Percebi que você entendeu bem a lógica até aqui e que soube nomear bem as variáveis e funções.

Tenho apenas duas pequenas observações.

### Usabilidade

Seria interessante exibir a pontuação com um pouco mais de destaque. Isso pode ser feito aumentando um pouco mais a fonte do parágrafo e modificando a cor da fonte ou do fundo da fonte. Você verá como fazer isso nas aulas seguintes.

### Linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo esse princípio, eu adicionaria uma linha em branco abaixo da declaração da let score:

```javascript
// antes
form.addEventListener('submit', event => {
  event.preventDefault()

  let score = 0
  const userAnswers = [
    // ...
  ]

  // ...
})

// depois
form.addEventListener('submit', event => {
  event.preventDefault()

  let score = 0

  const userAnswers = [
    // ...
  ]

  // ...
})
```

Essa linha em branco separa, visualmente, o conceito "declaração de let (que será modificada)" do conceito "armazenamento de respostas do usuário".

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

No final do `app.js` há duas linhas em branco. Deixe no máximo uma.

---

Novamente, parabéns pelo esforço =)

Fez sentido o que falei acima?

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
Sim, fez total sentido, Roger!!! Irei rever esse erros para eu atingir a fluência em javascript.
