### ISSUE TITLE
Etapa 15, Correção dos exercícios da aula 03 da etapa 14 - Aula 01-04

### ISSUE THREAD

**Issue by rialic** [roger-melo-treinamentos/curso-de-js-roger-melo#297]
Oi Roger,

Estou com 2 dúvidas em relação à correção do exercício 4 do vídeo

1º - Os métodos **render()**, **start()**, **stop()** não deveriam ser criados no objeto prototype para não consumir recursos da memória a cada criação do objeto? Se eu criar 2 objetos makeExtendClock em páginas diferentes isso não será ruim para o navegador do usuário? **Obs: Eu vi no vídeo no momento 15:15 que você fala a respeito disso, mas tive perguntar pra confirmar mesmo =)**

2º - Eu sei que não é algo que estudamos ainda mas já usei em alguns projetos passados e gostaria de saber sua opinião. É o seguinte, no método **start()** mais exclusivamente no trecho do **setInteval** se eu colocar o **this.render.bind(this)** sem o arrow function, o código funciona normalmente e o **this** continua referenciado o objeto Clock. Eu gostaria de saber se é aconselhável usar o **bind** para esses tipos de situações? Ou se devo evitar esse recurso do JS? Já usei muito esse recurso  e fico na dúvida se continuo utilizando em outros projetos...

```js
start() {
    const oneSecond = 1000

    this.render()
    this.timer = setInterval(this.render.bind(this), oneSecond)
  },
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rhiali.

Não existe aula na etapa 14 com o título que foi colocado na issue. A aula na qual você está com dúvidas é a Aula 01-04 da etapa 15, certo? Já ajustei o título da issue.

---

Classes fazem a atribuição ao prototype dos objetos automaticamente, então ao invés de declarar diretamente os métodos no prototype, você pode declará-los dentro da classe. Comentei sobre isso mais ou menos aos 11:03 da [Aula 03-07](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1886432) da etapa 14.

Na verdade não é recomendado declarar métodos dentro de uma **função construtora**, pois aí sim os métodos serão declarados diretamente nos objetos que a função construtora cria e não no prototype que eles compartilham. 

> Eu gostaria de saber se é aconselhável usar o **bind** para esses tipos de situações?

Eu evito ao máximo, principalmente em aplicações que desenvolvo em time e/ou não são antigas (suportam ES6 em diante). 

`this.render.bind(this)` é menos legível que `() => this.render()` (embora as duas expressões sejam redundantes).

Ps: se você observar bem, verá que no treinamento eu ensino `this`, `class`, `apply` e outros conceitos fortemente usados na orientação à objetos... mas evito usá-los exatamente por serem não-amigáveis a iniciantes. O JavaScript me dá a liberdade de obter o mesmo resultado com um código mais legível =)

Fez sentido?

@rialic

**Comment by rialic** [comment]
Oi Roger,

> Não existe aula na etapa 14 com o título que foi colocado na issue. A aula na qual você está com dúvidas é a Aula 01-04 da etapa 15, certo? Já ajustei o título da issue.

Era isso mesmo Roger, obrigado!

1º Resposta da primeira pergunta
> Classes fazem a atribuição ao prototype dos objetos automaticamente, então ao invés de declarar diretamente os métodos no prototype, você pode declará-los dentro da classe. Comentei sobre isso mais ou menos aos 11:03 da Aula 03-07 da etapa 14.

Eu vi essa aula e pra mim foi umas das melhores explicações que já vi sobre prototypes, pois eu utilizava prototypes mas não entendia como elas funcionavam, afinal eu usava o velho copia e cola de sempre!

Mas não era bem isso que eu queria saber, na verdade a minha dúvida é bem besta mesmo, e acredito que eu não passei ela direito pra você. Olha só você construiu o factory function dessa maneira certo ?! 👇🏽

```js
const makeClock = ({ template }) => ({
  template,
  render() {
    const formattedTime = getFormattedTime(this.template);

    console.log(formattedTime)
  },
  start() {
    const oneSecond = 1000

    this.render()
    this.timer = setInterval(this.render.bind(this), oneSecond)
  },
  stop() {
    clearInterval(this.timer);
  }
});
```
Não seria melhor colocar os métodos render(), start() e stop() no prototype dessa maneira para consumir menos memória?! 👇🏽
```js

function makeClock({ template }) {
  this.template = template;
}

Clock.prototype.render = function () {
  const formattedTime = getFormattedTime(this.template)
  console.log(formattedTime)
}

Clock.prototype.start = function () {
  const oneSecond = 1000

  this.render()
  this.timer = setInterval(() => this.render(), oneSecond)
}

Clock.prototype.stop = function () {
  clearInterval(this.timer)
}
```

Já que ambos são funções construtoras qual seria a diferença entre eles (além da sintaxe)? Eu sei que não existe a correta já que ambas fazem a mesma coisa, mas qual seria a diferença?

2º Resposta da segunda pergunta
> Eu evito ao máximo, principalmente em aplicações que desenvolvo em time e/ou não são antigas (suportam ES6 em diante).
this.render.bind(this) é menos legível que () => this.render() (embora as duas expressões sejam redundantes).
Ps: se você observar bem, verá que no treinamento eu ensino this, class, apply e outros conceitos fortemente usados na orientação à objetos... mas evito usá-los exatamente por serem não-amigáveis a iniciantes. O JavaScript me dá a liberdade de obter o mesmo resultado com um código mais legível =)

Então, o `this` o `call` e o `apply` são conceitos que eu entendia bem pouco e só aprendi o real significados deles assistindo suas aulas. No mais está tudo perfeitamente entendido - Roger That! =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rhiali.

> Não seria melhor colocar os métodos render(), start() e stop() no prototype dessa maneira para consumir menos memória?!

Dentro da factory, você pode criar o novo objeto, setar o prototype e em seguida, as propriedades dele:

```javascript
const objMaker = ({ firstValue, secondValue }) => {
  const newObj = Object.create(objProto)

  newObj.firstProp = firstValue
  newObj.secondProp = secondValue

  return newObj
}
```

Isso faz com que todos os objetos que essa factory function crie compartilhem o mesmo prototype. Tanto é que `true` é exibido ao checar se `obj` e `obj2` possuem o mesmo prototype:

```javascript
const objProto = {
  logFirstProp () {
    console.log(this.firstProp)
  },
  logSecondProp () {
    console.log(this.secondProp)
  }
}

const objMaker = ({ firstValue, secondValue }) => {
  const newObj = Object.create(objProto)

  newObj.firstProp = firstValue
  newObj.secondProp = secondValue

  return newObj
}

const obj = objMaker({ firstValue: 1, secondValue: 2 })
const obj2 = objMaker({ firstValue: 3, secondValue: 4 })

console.log(objProto.isPrototypeOf(obj) && objProto.isPrototypeOf(obj2)) // true

obj.logFirstProp()   // 1
obj.logSecondProp()  // 2
obj2.logFirstProp()  // 3
obj2.logSecondProp() // 4
```

Sacou a ideia?

Essa abordagem é flexível e, se necessário, permite você selecionar o prototype do objeto que a factory vai gerar:

```javascript
// prototypes disponíveis
const proto1 = {
  proto1Method () {
    console.log(this.firstProp, this.secondProp)
  }
}

const proto2 = {
  proto2Method () {
    console.log(this.firstProp, this.secondProp)
  }
}

// factory recebe o prototype selecionado como 2º parâmetro
const objMaker = ({ firstValue, secondValue }, selectedProto) => {
  const newObj = Object.create(selectedProto)

  newObj.firstProp = firstValue
  newObj.secondProp = secondValue

  return newObj
}

// objetos criados com prototypes diferentes
const obj = objMaker({ firstValue: 1, secondValue: 2 }, proto1)
const obj2 = objMaker({ firstValue: 3, secondValue: 4 }, proto1)
const obj3 = objMaker({ firstValue: 5, secondValue: 6 }, proto2)
const obj4 = objMaker({ firstValue: 7, secondValue: 8 }, proto2)

// comprovação que os objetos possuem o mesmo prototype
console.log(proto1.isPrototypeOf(obj) && proto1.isPrototypeOf(obj2))  // true
console.log(proto2.isPrototypeOf(obj3) && proto2.isPrototypeOf(obj4)) // true

// acesso aos métodos do prototype
obj.proto1Method()   // 1 2
obj2.proto1Method()  // 3 4
obj3.proto2Method()  // 5 6
obj4.proto2Method()  // 7 8
```

> Não seria melhor colocar os métodos render(), start() e stop() no prototype dessa maneira para consumir menos memória?! 👇🏽

Você se preocupará com memória caso esteja construindo uma lib que gera uma quantidade absurda de objetos por segundo. No front-end, na maioria dos casos, você não precisará fazer isso. Então não fique muito preocupado com performance ao criar objetos para aplicações que não são libs.

> Já que ambos são funções construtoras qual seria a diferença entre eles (além da sintaxe)? Eu sei que não existe a correta já que ambas fazem a mesma coisa, mas qual seria a diferença?

Tecnicamente, ambas não são funções construtoras. 

Uma factory function é qualquer função que não é uma classe, não é uma função construtora, mas retorna um novo objeto. 

Uma função construtora te obriga a usar a palavra-chave `new` ao invocá-la. Por convenção, funções construtoras também precisam ter a primeira letra maiúscula. Então a `makeClock` seria chamada de `MakeClock`.

Fez sentido o que eu disse acima?

@rialic

**Comment by rialic** [comment]
Com certeza Roger, obrigado pela explicação e pela ajuda!

@Roger-Melo
