### ISSUE TITLE
Aplicação: TODO-LIST

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#298]
Link do repositório da aplicação de TODO-List: https://github.com/Hamiltonspjunior/todo-list-js

### Menores dificuldades
- Selecionar os elementos do DOM
- Adcionar Listener de eventos
- Implementar a lógica de adicionar e remover os TODOS

### Maiores dificuldades
- Implementar a lógica de filtrar os TODOS
- Refatorar a aplicação
- Saber escolher quais funções isolar

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Hamilton.

Passando para avisar que sua issue foi visualizada. A análise da aplicação começará a ser feita e em breve será publicada aqui.

@Hamiltonspjunior

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Parabéns pelo esforço em desenvolver a segunda aplicação do treinamento =)

Só para eu confirmar aqui, a aula mais recente que você viu da construção dessa aplicação foi a [Buscando e filtrando to-dos - Aula 02-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1073158) da etapa 09, correto?

Percebi progresso em seu código, quando comparado com a aplicação passada (quiz). Você deu bons nomes às variáveis e funções e aplicou bem as linhas em branco. Isso mostra que você ficou atento às observações que fiz.

Sobre refatoração, você verá, nas aulas seguintes, formas de melhorar esse código, inclusive abstraindo a duplicação de `forEach` e `filter` ao filtrar os todos =)

Tenho apenas duas pequenas observações.

A primeira é sobre a ortografia da palavra hidde. O correto é "hide", com apenas um "d".

A segunda observação é sobre a função `resetAddTodoForm`. Observe que só existe uma ocorrência de `formAddTodo.reset()` em toda a aplicação. Então, teoricamente, não é tão importante isolá-la dentro de uma função. A não ser que a intenção tenha sido melhorar a legibilidade. Mas ainda assim, `formAddTodo.reset()` não é uma expressão tão ilegível. Então eu preferiria não criar uma função extra para conter uma expressão que, no fim das contas, não está duplicada na aplicação e não está ilegível. Sacou a ideia?

Como eu disse anteriormente, são pequenos ajustes. A prioridade você já está fazendo: funcionar.

Ficou claro o que eu disse acima?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Oi, Roger

> Só para eu confirmar aqui, a aula mais recente que você viu da construção dessa aplicação foi a [Buscando e filtrando to-dos - Aula 02-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1073158) da etapa 09, correto?

Isso mesmo. Eu achei melhor enviar a aplicação para análise antes de corrigir o exercício 24 para que você pudesse análisar como eu refatorei o código, ponto que eu ainda tenho mais dificuldade.

Obrigado pelas dicas, já as implementei no código e obrigado também pelo incentivo!

**Comment by Roger-Melo** [comment]
No que precisar, tô à disposição 👊
