### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#2981]
Nesta aula foi explicado o tipo de dados **String**, que é utilizado para armazena cadeias de caracteres ou um único caractere, e é adicionando entre ‘’ ou “”. Também podemos acessar um único caractere da String utilizando a anotação de` [] `e informando o index do caractere desejado, por exemplo, na palava `const str = “Resumo”` podemos acessar a primeira letra: `str[0]`. 
O tipo String possui métodos e propriedades que podem ser utilizadas para realizar ou obter um determinado resultado, como por exemplo a propriedade `length` que retorna o tamanho, uma observação é que os espaços em branco também são considerados. Um exemplo de método é o `toUpperCase()`.

**Comment by Roger-Melo** [comment]
Show @paulovieiradasilva. Vamo que vamo, rumo à fluência! 🙌
