### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by holivei531** [roger-melo-treinamentos/curso-de-js-roger-melo#299]
# Numbers

### → Inteiros e decimais

- const radius = 10
- const pi = 3.14  para representar números decimais utilizamos ponto e não virgula .

### → Operadores aritméticos

- + adição
- - subtração
- * multiplicação
- / divisão
- % resto da divisão

### → Ordem de operações

- 1º parênteses
- 2º expoentes ou raízes
- 3º multiplicação e divisão
- 4º adição e subtração

### → Operadores de incremento, decremento e addition assignment

- incremento ++
- decremento - -
- addition assigment +=

### → NaN - not a number

- É exibido quando uma operação não resulta em um número

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @holivei531! Rumo à fluência 🔥
