### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06  da etapa 01

### ISSUE THREAD

**Issue by jfjunior86** [roger-melo-treinamentos/curso-de-js-roger-melo#2995]
A variável tem o papel de armazenar um valor, pode ser um nome, e-mail, número, etc. O valor armazenado pode ser usado de diversas formas.

-Existem formas diferentes de declarar uma variável em javascript.
Forma 01: LET (o valor pode ser alterado)
Ex: let age = 01	
console.log(age) – mostra o que está armazenado na variável age no console do chrome.

O console pode receber mais de uma valor, basta separar por vírgula.
Let currentYear = 2019
console.log(age, currentYear) 

A variável pode ter seu valor alterado.
Ex: ege = 32 – a variável ege passa a ter um novo valor.
Obs.: não é necessário colocar o let, pois essa variável já foi criada antes.    

Forma 02: CONST (o valor não pode ser alterado)
Ex: const poins = 100
points = 101 – vai apresentar um erro, pois o const não permite alteração.

Tanto o const com o let é recente no javascript, antes se usava a palavra var, que assim como a let, aceita alteração do valor atribuído. 

-Regras para nome de variável
O nome de uma variável, se formado por uma única palavra, deve ser declarado inteiramente em minúsculo. No caso de palavras compostas, apenas a primeira letra de cada palavra, a partir da segunda palavra, deve estar em maiúsculo (camelCase).  
Ex: Let currentYear = 2019

Nomes de variáveis podem conter só letras, números, underscore "_" ou cifrão "$", mas o nome não pode começar com número. 

Existem certos nomes de variáveis que não podem ser usados, por já ser uma palavra reservada da linguagem. Ex: val, let, cons, etc.

-Comentários 
Parte do código que não aparece no momento da execução.
Para comentar apenas uma linha use: //
Quando o comentário tiver duas linhas ou mais use /* no início e */ no final.

**Comment by Roger-Melo** [comment]
Show @jfjunior86. Vamo que vamo, rumo à fluência! 🙌
