### ISSUE TITLE
Utilização do response fora do callback e async await

### ISSUE THREAD

**Issue by alphabraga** [roger-melo-treinamentos/curso-de-js-roger-melo#3]
Roger,

Sou aluno do curso de JS. Como posso utilizar os dados de uma response do axios fora do callback? (sei que isso ainda não foi visto no curso, mas vi esse conteudo nesse video seu https://www.youtube.com/watch?v=U_eGa7LEsDk)

Eu tenho uma função que pega dados via uma requisição http. Quero que essa função retorne os dados para uma variável e em seguida fazer um loop nessa variável como no codigo do link abaixo:

https://codepen.io/alphabraga-1477080019/pen/jOPWPbp

**Comment by Roger-Melo** [comment]
Oi Alfredo.

Isso mesmo, funções async sempre retornam uma promise =)

Para você fazer algo com essa promise, você pode utilizar o then.

O then é um método responsável por receber a resposta de sucesso da Promise. Exemplo:

```js
myPromise.then(value => console.log(value))
```

Em breve falarei sobre ele no curso, mas [nesse vídeo](https://youtu.be/wTGPhsGJ0sw), explico com detalhes como promises funcionam.

Uma opção que você tem é declarar uma função que encapsule o then.

Exemplo: 

```js
const logUsers = () => {
  invocacaoDaFuncaoQueRetornaAPromise()
    .then(users => {
      // execução do forEach aqui
    })
}
```

Veja se com essas informações você consegue chegar ao resultado que deseja. Se estiver batendo muito a cabeça, me avise novamente que te explicarei com mais detalhes! =)

@alphabraga

**Comment by alphabraga** [comment]
Olá Roger,

Obrigado pela informação. O que eu quero é utilizar de alguma forma a variável `users` fora do metodo then

	const logUsers = () => {
	  invocacaoDaFuncaoQueRetornaAPromise()
	    .then(users => {
	      // eu NÃO quero executar forEach aqui

	      // vou retornar a users
	      return users
	    })
	}

	let dadosDeUsuarios

	dadosDeUsuarios = logUsers()

	// executar o foreach aqui

**Comment by Roger-Melo** [comment]
Entendi.

Só que o retorno do `then` também é uma promise (por isso, é possível encadear múltiplos `then`). Então não há como você retornar apenas a resposta da requisição.

Se você executar o código abaixo, poderá comprovar isso.

```js
const url = 'https://jsonplaceholder.typicode.com/users'

const getUsers = async () => {
  return await axios.get(url)
}

const dadosDeUsuarios = getUsers().then(users => users.data)

console.log(dadosDeUsuarios) // Promise {<pending>}
```

A solução que eu havia comentado antes, seria algo nesse sentido:

```js
const logUsers = () => {
  getUsers()
    .then(users => {
      users.data.forEach(user => console.log(user))
    })
}

logUsers() // exibe os objetos do array de usuários
```

Há algum motivo específico para você querer utilizar a variável fora do `then`?
@alphabraga

**Comment by alphabraga** [comment]
Eu gostaria de passar ela para uma outra função responsável pela exibição desas informações

**Comment by Roger-Melo** [comment]
Entendo, mas para mim ainda não fez sentido o motivo para se fazer isso fora das funções.

Dentro dos `then`, você pode referenciar funções e fazer o que for necessário com a resposta da requisição.

Por exemplo, a função `filterUsers` abaixo, vai retornar apenas os usuários com o id igual ou menor que 3.

Abaixo da declaração da `filterUsers`, a função `showUsers` foi declarada e será a responsável pela exibição dos os usuários filtrados.

Abaixo das declarações das funções, dentro dos `then`, as funções foram referenciadas .

O motivo para utilizar algum valor fora dos `then` é por você achar a sintaxe estranha?

```js
const filterUsers = users => {
  let filteredUsers = []

  for (let i = 0; i < users.data.length; i++) {
    if (users.data[i].id <= 3 ) {
      filteredUsers.push(users.data[i])
    }
  }

  return filteredUsers
}

const showUsers = users => console.log(users)

getUsers()
  .then(filterUsers)
  .then(showUsers)

getUsers()
```

@alphabraga

**Comment by alphabraga** [comment]
Sim eu acho um pouco estranho. Mas tudo bem!
Obrigado pela atenção professor.

**Comment by Roger-Melo** [comment]
@alphabraga isso é normal, com a prática você se acostuma com o pattern =)

No que precisar, pode chamar aqui! =D
