### ISSUE TITLE
Aula 2 - Ex

### ISSUE THREAD

**Issue by joohnrodrigues23** [roger-melo-treinamentos/curso-de-js-roger-melo#30]
Oi Roger,

no oitavo exercício, eu solucionei de maneira diferente, gostaria de saber se posso utilizar dessa forma tbm, ou se impacta
em algo negativo.

Tbm percebi que em alguns exercícios eu chegava no resultado, mas de maneira diferente.

Exemplo:

let randomWord = 'Araponga'
let lastCharacter = randomWord.slice(randomWord.length-1);

console.log(lastCharacter);

Obrigado.

**Comment by Roger-Melo** [comment]
Oi John. Bem-vindo ao repositório do curso! =)

Você pode me passar o link da aula desse exercício que você mencionou acima?

Ou se preferir, apenas diga "Aula 02-01 da etapa 2", por exemplo.

Assim fica mais fácil eu encontrar a aula e responder sua dúvida.

@joohnrodrigues23

**Comment by joohnrodrigues23** [comment]
Oi Roger, foi mal rs.

Aula 02 da etapa 1, exercício 8

08 - Comente o console.log acima, e,

- Exiba no console a última letra da string que a "randomWord" (abaixo) armazena, mas com a condição a seguir;
- Ao invés de inserir manualmente a posição do último caractere, faça com que a obtenção da última letra funcione para qualquer palavra que a "randomWord" receber;
- Dica: utilize a propriedade ".length".
*/

**Comment by Roger-Melo** [comment]
Aula 03-01 da etapa 1. Vamos lá! =D

Em JavaScript há várias maneiras de se chegar ao mesmo resultado.

É excelente criarmos outras possibilidades na resolução de um problema, explorando o que conhecemos da linguagem.

Quando praticar outras possibilidades, apenas fique atento se a forma da resolução mostrada na aula foi compreendida.

É como tocar guitarra. Antes de começar a improvisar solos, os fundamentos devem estar solidificados.

Parabéns pelo esforço em pensar em uma resolução alternativa John =)

**Comment by joohnrodrigues23** [comment]
Show. Obrigado Roger.

**Comment by Roger-Melo** [comment]
No que precisar, é só dar o toque John =)
