### ISSUE TITLE
Resumo da Aula 02-05 Utilizando callbacks  da etapa 03

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3004]
forEach((inserindo templates HTML)=>{})

 -> Nesta aula vimos que com o uso do forEach é possível extrair informações de um array e organiza-las em um lista HTML. O forEach() itera em cada item do array adicionando os itens através da interpolação uma string que será passada para o HTML através do innerHTML.

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
