### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3007]
Sendo também um controle de fluxo, muitas vezes é utilizado como alternativa no lugar de if para evitar a repetição de condições. Usado para verificar múltiplos valores diferentes de uma variável ou constante, e para cada valor possível, ter a possibilidade de reagir de forma diferente.

Ao abrir o switch, o bloco pode receber um série de cases de possibilidades que a variável ou constante pode ter. Ao final do switch, o bloco recebe um valor default que será executado caso nenhum dos cases seja avaliado como true.
   
É necessário adicionar um comando break em cada case verificado para que caso o case seja true, o loop seja parado. Não é necessário adicionar break no default pois se nenhum for true, automaticamente o default será executado.

```.js
const grade = 'B'

switch (grade) {
   case 'A':
      console.log('você tirou nota A')
      break
   case 'B':
      console.log('você tirou nota B')
      break
   case 'C':
      console.log('você tirou nota C')
      break
   case 'D':
      console.log('você tirou nota D')
      break
   case 'E':
      console.log('você tirou nota E')
      break
   default:
      console.log('nota inválida')
}
```

**Comment by Roger-Melo** [comment]
Show @santos2408. Vamo que vamo, rumo à fluência! 🙌
