### ISSUE TITLE
Aplicação: Javascript Quiz

### ISSUE THREAD

**Issue by 0lucasferrari** [roger-melo-treinamentos/curso-de-js-roger-melo#3015]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/0lucasferrari/javascript-quiz

### Maiores dificuldades durante a implementação

Pensar na melhor forma de lidar com o elemento 'p' e seu estado, bem como refatorar o código (não refatorei, não consegui pensar em como fazer isso).

### Menores dificuldades durante a implementação

Trabalhar com métodos de array.

**Comment by Roger-Melo** [comment]
Olá @0lucasferrari.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @0lucasferrari.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Pensar na melhor forma de lidar com o elemento 'p' e seu estado

Você não precisa se preocupar com a melhor forma de lidar com o elemento 'p' agora. Num primeiro momento, o mais importante é fazer o código funcionar. Depois, você melhora.

---

> ## Refatorar o código (não refatorei, não consegui pensar em como fazer isso)

O mais importante vc já fez, que é fazer funcionar =)

Não se preocupe muito com refatoração agora. Refatoração é uma habilidade que é elevada com a prática.

Conforme vc praticar, vc vai percebendo aos poucos o que pode ser melhorado.

E você ainda irá praticar bastante no decorrer do treinamento =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem). A ideia do `forEach` ali naquele momento era apenas calcular os pontos ou a quantidade de respostas certas, exatamente como vc fez =)

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Localização dos pontos

Talvez, depois que você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular.

Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior da tela:

![image](https://user-images.githubusercontent.com/29297788/153233450-c213c90b-c492-4a71-bcde-acacac78bb0b.png)

Uma possível solução para isso seria exibir os pontos em um local em que o usuário está olhando no momento do envio. Poderia ser, por exemplo, logo acima do botão "Enviar".

Nas aulas seguintes você também verá uma outra forma de implementar os pontos =)

---

## Comentários 

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Indentação com quatro espaços ao invés de dois.

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Parâmetro do callback do forEach

Você pode renomear o parâmetro de callback do `forEach` como `correctAnswer` ao invés de `answer`. Acredito que como singular de itens do array no qual o forEach foi encadeado (correctAnswers), a leitura do forEach e do if fique mais legível:

```js
//antes
correctAnswers.forEach((answer, index) => {
  if (userAnswers[index] === answer) {
    numberOfRightAnswers++
  }
})
```

```js
//depois
correctAnswers.forEach((correctAnswer, index) => {
  if (userAnswers[index] === correctAnswer) {
    numberOfRightAnswers++
  }
})
```

---

## Uso dos métodos map e filter antes de serem apresentados no treinamento

No trecho de código abaixo, você usou dois métodos que não foram apresentados no treinamento no momento que a aplicação foi solicitada.

```js
const userAnswers = Array.from(document.querySelectorAll('form input'))
  .filter(({ checked }) => checked === true)
  .map(({ value }) => value)
```

O desafio é você resolver os exercícios e implementar suas aplicações usando apenas o que viu no treinamento até o ponto em que você está.

Não faz sentido analisar map e filter nessa aplicação sendo que são features apresentadas na etapa 8. E o pedido de envio do quiz está na etapa 7.

---

## Nome da const usada para criar o parágrafo

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

A const precisa descrever o valor que ela está armazenando. Nesse caso, p poderia ser nomeada de forma mais descritiva. Se o que ela faz é armazenar a mensagem de pontuação do usuário, você pode, por exemplo, nomeá-la como scoreText.

```js
//antes
const p = document.createElement('p')
```

```js
//depois
const scoreText = document.createElement('p')
```

Como existe uma outra `scoreText` que é usada para checar se esse parágrafo já existe no DOM, você pode nomeá-la como `scoreTextExists`.

Ficaria assim:

```js
form.addEventListener('submit', event => {
  // ...

  const scoreTextExists = document.querySelector('#scoreText')

  if (scoreTextExists) {
    scoreTextExists.remove()
  }

  // ...

  const scoreText = document.createElement('p')
  // ...
})
```

É perceptível que `scoreTextExists.remove()` não é lá a expressão mais clara do mundo... Mas ao mesmo tempo, não me vêm a mente outra alternativa neste caso. Vem à sua?

---

## Linhas em Branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Seguindo esse princípio, você pode remover a linha 40, pq é uma segunda linha em branco desnecessária.

Tem também a linha 37, que está em branco. Vc pode removê-la pq é uma convenção que a primeira e a última linha de um bloco sejam linhas preenchidas com código =)

---

## Ordem das consts que armazenam elementos do DOM

É uma convenção que consts que armazenam elementos do DOM venham acima das demais consts utilizadas na aplicação.

Então no caso do código da sua aplicação, o ideal é que a const `form` seja declarada antes de `correctAnswers`.

```js
// antes
const correctAnswers = ['C', 'A', 'D', 'B']

const form = document.querySelector('form')
```

```js
// depois
const form = document.querySelector('form')

const correctAnswers = ['C', 'A', 'D', 'B']
```

O princípio acima pode ser quebrado quando houverem importações de libs ou serviços back-end, por exemplo, como você verá na etapa 15. Então ficaria assim:

```js
// importações aqui

const form = document.querySelector('form')

const correctAnswers = ['C', 'A', 'D', 'B']
```

Sacou a ideia? =)

---

## Code styling

Ao analisar as linhas abaixo, você percebe que algo pode estar "desorganizado"?

```js
  if(scoreText) {
    scoreText.remove()
  }

  if (userAnswers[index] === answer) {
    numberOfRightAnswers++
  }
```

Há um espaço em branco antes do parênteses de abertura do primeiro if e o mesmo não acontece no segundo if.

Escolha uma forma de escrever e seja consistente com ela no decorrer do código.

Por convenção, recomendo que escolha deixar um espaço em branco antes da abertura dos parênteses.

Ficaria assim:

```js
  if (scoreText) {
    scoreText.remove()
  }
```

---

## Let ao invés de const

Prefira usar const no lugar de let, quando possível. 

`let` pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo. 

As let's `numberOfQuestions` e `score` podem ser const's, pois elas não irão sofrer reatribuição de valor.

```js
// antes
let numberOfQuestions = correctAnswers.length
let score = (numberOfRightAnswers / numberOfQuestions * 100)
```

```js
// depois
const numberOfQuestions = correctAnswers.length
const score = (numberOfRightAnswers / numberOfQuestions * 100)
```

---

## Os termos "rightAnswers" e "correctAnswers"

Há uma inconsistência em você usar dois termos diferentes pra descrever a mesma coisa na sua aplicação. Sendo assim, `numberOfRightAnswers` pode ser substituído por `numberOfCorrectAnswers`. O código fica mais corente quando vc se refere a uma única coisa usando o mesmo termo.

---

## Armazenar a referência do button numa const

Você pode armazenar a referência do button e atribuí-la a uma const no topo do código. Assim, a leitura da expressão fica mais legível, olha só:

```js
//antes
document.querySelector('button').insertAdjacentElement('afterend', p)
```

```js
//depois
const button = document.querySelector('button')

button.insertAdjacentElement('afterend', p)
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)

**Comment by 0lucasferrari** [comment]
Oi Roger, muito obrigado pelos feedbacks!
Sim, suas observações foram perfeitas! 

De fato, acabei utilizando array methods por pura força do hábito uma vez que já estou acostumado e utiliza-los! 

Vou manter em mente seus apontamentos para os próximos desafios!
