### ISSUE TITLE
Aplicação: quiz-interativo

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#3017]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/RodrigoLimaMota/Curso-JavaScript-puro/tree/main/quiz-interativo%20

### Maiores dificuldades durante a implementação

Refatorar o que eu fiz.
Eu não consegui alterar a cor para vermelho da resposta errada do usuário.

Quando eu busquei pela referencia do radio para capturar apenas a alternativa clicada pelo usuário, eu não consegui, pois aparece o radioNodeList se não me engano e sobre esse radio list acho que você não ensinou.

Pensei em colocar os vetores dentro de um objeto, mas achei q os vetores separados ficaram melhores.

### Menores dificuldades durante a implementação

Colocar cores nas letras das respostas corretas e erradas no CSS.
A lógica de somar a pontuação.

**Comment by Roger-Melo** [comment]
Olá @RodrigoLimaMota.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
