### ISSUE TITLE
Comparação entre Strings

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#3026]
### Etapa da aula

1

### Nome da aula

Booleans e comparacoes - Aula 04-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751260

### Descreva a dúvida

@Roger-Melo

Prof, olá!

Estendi certinho sua explicação sobre comparações entre números.
Mas surgiu uma dúvida quanto as comparações entre Strings, mais exatamente no exemplo abaixo:
```js
const myName = "Bruno"

console.log(myName > "Bruna");

```
No console retorna TRUE, mas gostaria de saber o porquê. Eu deduzo que é JS vai verificando letra por letra e quando chega na última letra: "o" é maior que a letra "a".. Ou estou equivocado?

**Comment by Roger-Melo** [comment]
Olá @Bruno-Luna.

> ## No console retorna TRUE, mas gostaria de saber o porquê. Eu deduzo que é JS vai verificando letra por letra e quando chega na última letra: "o" é maior que a letra "a".. Ou estou equivocado?

Na minha opinião técnica, não faz sentido vc investir tempo e energia buscando resposta para esse tipo de problema.

Vou te dizer pq nas linhas abaixo.

---

## 1) Não faz sentido para o seu momento

Vc está em um estágio de aprendizado inicial, onde ainda está estudando sobre booleans e comparações.

Se algum dia for necessário vc entender comparações entre strings envolvendo `>`, `<`, etc, definitivamente não é agora =)

---

## 2) Conhecimento interno sobre a linguagem

Esse tipo de operação envolve um conhecimento de mecanismos internos da linguagem.

Pode ser até legal saber algumas coisas sobre como a linguagem funciona internamente, mas é um conhecimento que não será usado em seu dia a dia como Dev. Front-end. 

Eu nunca vi algum caso em que esse tipo de comparação fosse necessária em uma aplicação web Front-end.

---

## 3) Não te ajuda a construir aplicações web com JavaScript puro

Se não está no CJRM, não te ajuda a chegar no objetivo de construir aplicações web com JS puro.

Se não te ajuda a chegar nesse objetivo, não há motivos pra estudar agora. Foca no CJRM =)

---

E tá tudo bem, vc não sabia dessas coisas que eu listei acima. 

Mas à partir de agora, a minha recomendação é que quando rolar esse tipo de dúvida, vc pergunte na issue se faz sentido aprender isso agora. E dessa forma, vc descobrirá a resposta =)

---

Dito isso, vou deixar alguns materiais para vc pesquisar por conta própria sobre esse assunto, caso tenha interesse em entrar nesse buraco, mesmo depois do que eu disse acima. 

- [String comparison - javascript.info](https://javascript.info/comparison#string-comparison)
- [Why is string "11" less than string "3"? - stackoverflow](https://stackoverflow.com/questions/10863092/why-is-string-11-less-than-string-3)
- [Why is one string greater than the other when comparing strings in JavaScript? - stackoverflow](https://stackoverflow.com/questions/7087811/why-is-one-string-greater-than-the-other-when-comparing-strings-in-javascript)
 - [javascript greater than operator with strings - resultados de pesquisa do google](https://www.google.com/search?q=javascript+greater+than+operator+with+strings&oq=javascript+greater+than+operator+with+strings&aqs=chrome..69i57j69i64.15952j0j4&sourceid=chrome&ie=UTF-8)

---

Deixe-me saber se minha resposta fez sentido pra vc =)

**Comment by Bruno-Luna** [comment]
Certinho. 
Obrigado pelas palavras, @Roger-Melo

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
