### ISSUE TITLE
Resumo da Aula Async/await da etapa 11

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#3033]
<h1>Async/await</h1>
<p>É um abstração da promise, async e await são duas palavras chaves usadas em javascript que irão usar promise por baixo do pano e irá permitir um código ainda mais legível, e é lido como se fosse síncrono</p>

<p>Quando começamos a encarar varias e varias promises (aquelas com o then() e catch() encadeado) o código fica ilegível, já quando usamos o async/await, podemos setar o código assíncrono em uma função e usar dentro dessa função a palavra chave await para lidar com promise de uma forma mais legível. Com async/await evitamos configurar explicitamente encadeamentos de promises</p>

<h2>sintaxe</h2>

```js
const getUsers = async () => { }
```

<p>Para fazer uma função assíncrona temos que colocar a palavra chave async antes da declaração da função. Então assim que invocarmos essa função ela irá retornar uma promise independente do eu conteúdo</p>

```js
const getUsers = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users')
  const user = await response.json()
  console.log(users)
}
getUsers()
```

```js
const response = await fetch('https://jsonplaceholder.typicode.com/users')
```
<p>iremos salvar o resultado da fetch() ema uma const, só que antes da invocação do fetch() iremos inserir a palavra await. O await só pode ser usado ema uma função async, quando usada, nenhuma linha abaixo dele é executado até que a resposta seja obtida</p>

```js
const user = await response.json()
```

<p>Colocamos o resultado da response encadeado do método json() salvas numa const users. Encadeado do await pois essa invocação retorna uma promise com o array de objeto.</br>
Quando essa promise for resolvida, o await vai atribuir o resultado para a const users </p>

<p>Só que sempre ao final nós retornamos o resultado e não exibimos ela dentro da própria função e para isso fazemos o seguinte</p>

```js
const getUsers = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users')
  return await response.json()
}
const logUsers = async () => {
  const users = await getUsers()

  console.log(users)
}

logUsers()
```
```js
return await response.json()
```
<p>Retornamos o resultado do request</p>

```js
const users = await getUsers()
```
<p>Salvamos o resultado em outra função e colocamos o await, pois o resultado é uma promise</p>

**Comment by Roger-Melo** [comment]
Boa @Jonatan1103, rumo à fluência! 🔥
