### ISSUE TITLE
Função Callback

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#3037]
### Etapa da aula

11

### Nome da aula

Funções de Callback - 03-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1251212

### Descreva a dúvida

Boa tarde, professor!
Estou com muita dificuldade em entender funções de callback, eu simplesmente não entendo a lógica delas.
Não sei nem dizer o que exatamente eu não entendo, só sei que não entendo porque se eu tiver que fazer uma do zero eu não consigo. 
Eu fico encarando o código da aula e entendo o que faz, mas por que faz? E se eu me esforçar em entender parece que eu passo a não mais entender o pouco que entendia antes, é confuso, chega a dar vertigem dependendo do tempo que eu ficar nisso.
O código feito em aula:
```js
const getTodos = (callback) => {
  const request = new XMLHttpRequest()
  request.addEventListener('readystatechange', () => {
    const requestOk = request.readyState === 4 && request.status === 200
    const requestNotOk = request.readyState === 4
    if (requestOk) {
      callback(null, request.responseText)
      return
    } else if (requestNotOk) {
      callback('Não foi possivel obter os dados', null)
    }
  })
  request.open('GET', 'https://jsonplaceholder.typicode.com/todos')
  request.send()
}

getTodos((error, data)=>{
  console.log('Callback executado')
  if(error) {
    console.log(error)
  }
  console.log(data)
})
```
Uma das coisas que me deixam confusa: Temos uma função, e normalmente numa função passamos um parâmetro. Na invocação passamos os argumentos, até aí ok. 
Aqui nessa aula temos a declaração da função (const getTodos...) e  passamos um parâmetro que receberá uma função que tem parâmetros mas essa função que passamos no parâmetro que será passada como argumento está na invocação da função (a getTodos) que tem uma função como argumento que tem dois valores como parâmetro...buguei.).

Parece a história do "quem veio primeiro, o ovo ou a galinha?", a do Tostines... 

Pode me ajudar, por favor?

Obrigada!!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Callbacks tem esse impacto inicial =)

Como sua dificuldade é sobre callback, eu recomendo que vc desfoque desse código de abstração de requests por agora e foque no passo a passo que eu vou te mostrar.

Porém, vc vai copiar e colar zero linhas do passo a passo.

Vc irá **digitar cada linha** ao invés de dar ctrl + c e ctrl + v, combinado?

- [Passo a passo para entender callbacks](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574)

Se ao final do passo a passo restar alguma dúvida, pode mandar aqui que te ajudo =)

**Comment by ElaineDelgado** [comment]
Bom dia, professor!
Fiz o passo a passo que você sugeriu, e foi bem tranquilo de entender, ficou bem claro, inclusive fiz outros exemplos parecidos sem olhar a solução.
O problema é quando não é tão simples, como no caso da getTodos do início da issue onde na invocação da getTodos além de receber uma função como argumento, a função que foi passada como argumento tem parâmetros, esses parâmetros  serão (foram) passados na declaração da getTodos como argumento, e isso me confunde. 
Analisando o código com calma eu consigo entender o que está sendo feito, mas não é o tipo de coisa que eu conseguiria fazer, por exemplo, se fosse pedido em um exercício. 
De qualquer forma estou refazendo esse código do getTodos e re-assistindo à aula até eu entender de vez.

**Comment by Roger-Melo** [comment]
> ## O problema é quando não é tão simples, como no caso da getTodos

Pq o de ter parâmetros torna o callback mais complexo?

Lembre-se que parâmetros são apenas variáveis que podem ser usadas localmente na função. 

> ## ...esses parâmetros serão (foram) passados na declaração da getTodos como argumento, e isso me confunde. 

Não existe argumento 👉🏻na declaração👈🏻 da `getTodos`.

A 👉🏻declaração👈🏻 de uma função pode receber **parâmetros**.

Distinguir o que é parâmetro e o que é argumento faz toda a diferença.

![parametro-argumento](https://user-images.githubusercontent.com/29297788/153782448-ae70bd46-f4d9-4cf3-aadc-34f6932c5048.jpg)

O primeiro passo é vc entender de fato o que é parâmetro e o que é argumento. 

Se vc sacar isso, fica mais fácil entender que o argumento inserido na invocação da `getTodos`, que poderia ser qualquer coisa mas nesse caso é uma função, foi atribuído para o parâmetro `callback`. 

Se a função que foi inserida como argumento tem ou não parâmetros, é outra história. 

Primeiro, vc precisa resolver e deixar bem definido o que é parâmetro e o que é argumento =)

---

Entendiso isso...

Se logo na primeira linha dentro da getTodos vc invocar um `console.log(callback)`, verá que o parâmetro `callback` armazena exatamente a função que foi inserida como argumento da invocação da `getTodos`:

```javascript
const getTodos = (callback) => {
  console.log(callback) // (error, data)=>{ blá blá blá... }
  // ...
}
```

Se `callback` está armazenando essa função, isso significa que vc pode invocar `callback()` pra que o código dessa função que callback armazena seja executado.

Só que não faz sentido invocar callback() sem argumentos pq a declaração da função que o parâmetro callback armazena tem dois parâmetros declarados (error e data).

Sendo assim, vc pode invocar callback(arg1, arg2) pra que arg1 e arg2 sejam atribuídos aos parâmetros `error e data` =)

@ElaineDelgado

**Comment by ElaineDelgado** [comment]
#### " Primeiro, vc precisa resolver e deixar bem definido o que é parâmetro e o que é argumento =)"

Sim, eu entendo a diferença entre parâmetro e argumento, eu me expressei mal quando disse "esses parâmetros serão (foram) passados na declaração da getTodos como argumento", eu quis dizer os parâmetros "error" e "data" da função de callback que é um argumento.   

Ontem passei o dia fazendo vários testes e pegando exemplos dados em aulas passadas. Está mais claro agora, e quando faço aos poucos, eu consigo chegar lá, fazer funcionar, só tenho problemas para olhar um código do tipo desse dos "todos" da aula 03-03 e entender com completa clareza o que está fazendo sem antes analisar por alguns (muitos) minutos.
Não me restou dúvidas de como o callback funciona.
Obrigada pela ajuda!!

**Comment by Roger-Melo** [comment]
Natural Elaine. 

Nem tudo o que estudamos "cai a ficha" na hora.

Mas quanto mais vc praticar, aos poucos o conceito vai clicando na mente =)

E claro, qualquer dúvida que surgir, pode abrir uma issue que te ajudo a entender, ok?

Conte comigo pra chegar na fluência.
