### ISSUE TITLE
Resumo da Aula O que são requests HTTP 01-04 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3041]
Existem situações onde há a necessidade de exibir informações que estão armazenadas em um outro lugar, como banco de dados ou APIs (interface de programação de aplicações, ferramenta de comunicação entre sistemas). Para obter estas informações, serão necessárias requisições solicitando-as. Entre as requisições, o _**protocolo HTTP**_ é o principal para efetuar a comunicação entre computadores.

A _requisição HTTP_ realizada a uma API ou servidor é feita a um _**end point**_, que é uma URL disponibilizada com as informações que a API ou servidor armazena. O _request_ é analisado pelo servidor que irá retornar ao requisitante alguma informação. Geralmente, o formato da resposta obtido é feito em _**JSON (Javascript Object Notation)**_.

Toda vez que inserimos um endereço na barra de busca do navegador, estamos fazendo uma request.

Para os estudos deste curso, será utilizada a _**API JSON Placeholder**_, que foi criada especificamente para treinamento de _requests_.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
