### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by acuglar** [roger-melo-treinamentos/curso-de-js-roger-melo#3048]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação

https://github.com/acuglar/quiz

### Maiores dificuldades durante a implementação

Demorei um pouco para me entender com  a  documentação do bootstrap e fazer aparecer o modal do score no app.

Depois de funcional o app, tive dificuldades de implementar uma lógica alternativa que marcasse a resposta em verde ou vermelho depois do submit

### Menores dificuldades durante a implementação

Começar

**Comment by Roger-Melo** [comment]
Olá @acuglar.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
Olá @acuglar.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Demorei um pouco para me entender com a documentação do bootstrap e fazer aparecer o modal do score no app.

Mesmo com as dificuldades, vc conseguiu. Num primeiro momento, o mais importante é fazer funcionar, como vc fez.

---

> ## Depois de funcional o app, tive dificuldades de implementar uma lógica alternativa que marcasse a resposta em verde ou vermelho depois do submit

Você não precisa se preocupar com isso por agora. Num primeiro momento, o mais importante é fazer o código funcionar. Depois, você melhora.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

O parâmetro do callback do forEach foi nomeado de forma coerente, como singular de itens do array no qual o forEach foi encadeado.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Uso do método filter antes de ser apresentado no treinamento

No trecho de código abaixo, você usou um método que não foi apresentado no treinamento no momento que a aplicação foi solicitada.

```js
const showScore = () => {
	const correctAnswerAmount = insertedAnswers.filter((answer) => answer === 'C').length;
```

---

## Uso de ferramentas (libs) que não foram apresentadas no treinamento

Nos trechos de código abaixo, você importou as libs jQuery, Popper e o javascript do Bootstrap.

```HTML
<!-- Import das libs jQuery e Popper-->
<script
	src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	crossorigin="anonymous"
></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
	integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	crossorigin="anonymous"
></script>
```

```js
// Uso indevido do método Modal
const modal = new bootstrap.Modal(document.querySelector('.modal'));
```

Em nenhum momento foi pedido para usar algo que não fosse JS puro na aplicação. Os critérios para análise do quiz devem ser seguidos, libs são ferramentas adicionais, e essas ferramentas não devem ser adicionadas agora. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, o que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

---

## Callback do forEach

Se o callback anônimo do `forEach` existe apenas para invocar a `checkAnswer`, por que criar um callback anônimo? Basta inserir `checkAnswer` (sem invocá-la) como argumento do `forEach`. Como mostrado no código abaixo:

```js
//antes
correctAnswers.forEach((correctAnswer, index) => {
	checkAnswer(correctAnswer, index);
});
```

```js
//depois
correctAnswers.forEach(checkAnswer)
```

---

Mais uma vez, parabéns pelo esforço.

As observações fizeram sentido?

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
