### ISSUE TITLE
Resumo Tratando erros com try/catch - Aula 06-04 - etapa 11

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3050]
- Ele deve ser usado para fazer tratamento de um erro especifico;
- Serve para tratar um erro, que esteja bloqueando a aplicação de carregar o restante dos códigos;
- Todo objeto de **Error** tem duas propriedades  (**name**, **message**);
- Quando um erro e lançado em JS, o código abaixo dele não é executado;

Exemplo 1
```js
console.log(oi)
console.log('oi')

// Uncaught ReferenceError: oi is not defined
```
### try/catch em ação =)
- Podemos usar o **try/catch**, uma clausura que vai tentar executar um código;
- Vai tentar executar um código caso o error for lançado, para não travar a aplicação;

Exemplo 2
```js
try {
  console.log(oi)
} catch (error) {
  if (error.name === 'ReferenceError' && error.message === 'oi is not defined') {
    const oi = 'const oi criada'
    console.log(oi)
  }
}
console.log('oi')

// const oi criada
// oi
```

**Comment by Roger-Melo** [comment]
Show @carlosdevjs. Vamo que vamo, rumo à fluência! 🙌
