### ISSUE TITLE
Resumo da Aula da 01-04 etapa 03

### ISSUE THREAD

**Issue by PatrickTav** [roger-melo-treinamentos/curso-de-js-roger-melo#3052]
Vamos sar valores para dentro da função para que elas retornem algo. 

Vemos no exemplo abaixo

**const myFunc = function (){**

**console.log(`Oi, Nome!`)**

**}**

**myFunc() ⇒ Oi, Nome!**

mais suponhamos que queremos colocar o nome verdadeiro nesta função então dentro de parênteses colocamos o valor name, assim estamos indicando que esta função vai receber um valor. “name” é uma variável local que apenas pode ser usada dentro do bloco de código da função

**const myFunc = function (name){**

**console.log(`Oi, ${name}!`)**

**}**

até então nem me não tem nenhum valor da variável então para dar valor a esta variável dentro dos parênteses da função myFunc colocamos o valor da variável

**myFunc(  “Patrick”)** 

Então fica assim. 

**const myFunc = function (name){**

**console.log(`Oi, ${name}!`)**

**}**

**myFunc(”Patrick”) ⇒ Oi, Patrick!**

Quando passamos um valor dentro da invocação de uma função esse valor é chamado de argumento. 

**myFunc(”Patrick”//argumento) ⇒ Oi, Patrick!**

Já a variável passada entre parênteses na declaração da função é chamada de parâmetro

**const myFunc = function (name// parâmetro){**

**console.log(`Oi, ${name}!`)**

**}**

dentro de uma função podemos colocar um ou mais parâmetros assim como na invocação podemos colocar um ou mais argumentos todos eles separados por “ , ”

**const myFunc = function (name, lastname){**

**console.log(`Oi, ${name} ${lastname}!`)**

**}**

**myFunc(”Patrick”, “Tavares”) ⇒ Oi, Patrick Tavares!**

Atenção para que as ordens dos argumentos tem que seguir as ordens do parâmetro.

O primeiro parâmetro sempre irá receber o primeiro argumento e o segundo parâmetro sempre irá usar o segundo argumento e assim sucessivamente. Mas o uso das variáveis dentro do bloco não tem ordem

se por algum acaso não passarmos os argumentos na invocação da função, o retorno irá ser undefined, podemos prevenir isso usando valores padrões dentro dos parâmetros exemplo:

const myFunc =  function(name = “Ridson”){

console.log(`Oi, ${name}!`)

}

myFunc() ⇒ Oi Ridson!

Desta forma iremos prevenir que não tenhamos valores indefinidos mas se dentro de nossa invocação passarmos como argumento “Patrick” este valor passado como argumento irá sobre escrever o “Ridson”

**Comment by Roger-Melo** [comment]
Show @PatrickTav. Vamo que vamo, rumo à fluência! 🙌
