### ISSUE TITLE
Aplicação: [Quiz interativo sobre JavaScript]

### ISSUE THREAD

**Issue by andrewherculano** [roger-melo-treinamentos/curso-de-js-roger-melo#306]
**Maiores dificuldades**

* Adicionar a pontuação do usuário sem que se acumule com a anterior a cada envio do botão.
* Refatoração do código

**Menores dificuldades**

* Adicionar os events
* Manipular o DOM

**Link do repositório da aplicação**

* Quiz: https://github.com/andrewherculano/Quiz

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Andrew.

Excelente, em breve a análise da aplicação será postada aqui.

Mas antes, preciso lembrar que ainda falta você executar um critério. A issue deve conter quais foram as suas maiores e menores dificuldades durante a implementação da aplicação. Ou seja, você precisa listar também quais foram as suas menores dificuldades.

Fico no aguardo.

@andrewherculano

**Comment by Roger-Melo** [comment]
Oi @andrewherculano.

Passando para avisar que, para ter sua aplicação analisada, você precisa preencher o critério que mencionei na issue acima.

Fico no aguardo. Se houver alguma dúvida, é só dar o toque =)

**Comment by Roger-Melo** [comment]
@andrewherculano vou fechar a issue mas quando ajustar confirme pedido acima, é só dar o toque =)
