### ISSUE TITLE
Resumo da Aula Tratando erros com try/catch 06-04 da etapa 11

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#3060]
<h1>Tratando erros com try/catch</h1>

<p>Quando um erro é lançado em uma aplicação, o código abaixo de onde veio o erro não é exectado</p>

<p>O try/catch é uma clausula que vai tentar executar um código, se o código que for executado lançar um erro, vamos poder executar algum outro código, e o código que lançou o erro não vai travar a aplicação</p>

```js
try {
  console.log(oi)
} catch (error) {
  if (error.name === 'ReferenceError' && error.message === 'oi is not defined') {
    const oi = 'A const "oi" foi declarada'
    console.log(oi)
  }
}

console.log('oi')
```

<p>No try será o código aonde pode vir o erro, o catch é aonde tratamos esse erro.</br>
O catch nos da um objeto de erro que nos fornece uma propriedade <strong>name</strong> e <strong>message</strong></p>

**Comment by Roger-Melo** [comment]
Show @Jonatan1103. Vamo que vamo, rumo à fluência! 🙌
