### ISSUE TITLE
Resumo da Aula Introdução ao Firebase - Aula 01-10 da etapa 15

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#3066]
## Banco de dados (database)

- É um sistema de armazenamento que coleta dados de forma organizada para que uma aplicação possa acessar esses dados depois.
- Qualquer tipo de dado pode ser armazenado num database: textos, imagens, números, objetos, arrays, etc.

## LocalStorage vs Banco de dados

- O localStorage persiste dados apenas no browser do usuário, ou seja, se a aplicação estiver sendo acessada e persistindo dados no browser do smartphone, apenas nele existirão os dados. Se a aplicação for acessada pelo browser de qualquer outro dispositivo, os dados não existirão ali.
- Quando os dados são persistidos num database (ou seja, no back-end), independente do dispositivo acessado, os dados persistidos sempre serão carregados e mostrados ao usuário.

### SQL

- SQL é a sigla para Structured Query Language (Linguagem de consulta estruturada).
- É uma linguagem de pesquisa para bancos de dados relacionais.
- Bancos de dados relacionais são baseados em schemas, com uma estrutura de tabelas, linhas e colunas.
- Costumam ser menos flexíveis na hora de se fazer uma modificação na estrutura das tabelas.
- É mais comum de ser utilizado em conjunto com linguagens de programação como PHP e Python, por exemplo.

### noSQL

- Utiliza a estrutura de collections, documents e properties (coleções, documentos e propriedades).
- Termo genérico para representar bancos de dados não relacionais.
- A ideia das documents é parecida com a forma que trabalhamos com objetos no JavaScript.
- Bancos noSQL surgiram da necessidade de flexibilizar as modificações que nos bancos clássicos eram menos flexíveis.
- É uma boa opção para iniciar uma aplicação, principalmente por possivelmente não sabermos tudo sobre a estrutura que o banco de dados precisará ter no futuro.
- Estrutura do banco de dados noSQL:
    - Instância do banco de dados: Container para todas as informações, onde podem haver várias collections
    - Collections: podem representar um tipo específico de informações, por exemplo, uma collection Users poderá armazenar múltiplos documents de usuários, uma collection Comments poderá armazenar múltiplos documents de comentários de posts.
    - Documents: estão dentro das collections. Cada um desses documents tem um ID único e uma estrutura muito parecida com a de objetos Javascript, ou seja, é uma estrutura com vários pares de chave e valor.

## Firebase

- Serviço de back-end que oferece o Firestore como banco de dados noSQL.
- É uma plataforma de serviços back-end.
- É um BAAS: Back-end As A Service.
- Além do banco de dados, tem diversos outros serviços de back-end
- É um serviço disponível apenas online.

### Vantagens do Firebase

- Oferece serviços de autenticação, segurança, infraestrutura, Rest API, upload, configuração de DNS, push notifications, alta disponibilidade, etc.
- Gratuito para aplicações pequenas e médias.
- Por estar na nuvem tem alta disponibilidade.

### Desvantagens do Firebase

- Para aplicações complexas que envolvem muitas regras de negócios possivelmente um BAAS não seja o ideal para utilizar em meu sistema.
- Não é o Firebase que se adequa ao sistema, é o sistema que deve se adequar ao Firebase.

## Front-end vs Back-end

- Front-end é a parte visual de uma aplicação, é todo o código executado no navegador.
- Back-end é o que vem por trás de uma aplicação, faz a ponte entre os dados que vão do browser para o servidor e do servidor para o browser.

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. Vamo que vamo, rumo à fluência! 🙌
