### ISSUE TITLE
Etapa 8, nome do vídeo: O método sort - Aula 02-02

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#307]
Olá Roger, tudo bem? Eu fiquei um pouco confuso sobre como funciona a iteração do método sort nos itens do array. Ele compara um com todos? E também fiquei na dúvida do motivo de retornar -1, 0 e 1. Como o método entende que um número é maior que o outro? E também por que como parâmetros do método sort() voce coloca Item1 e item2, sendo que o item1 é o segundo item do array e o item2 é o primeiro... Não seria mais fácil de entender assim:

```js
theBigFamily.sort((item2, item1) => {
  if(item2.score > item1.score){
    return -1
  }else if(item1.score > item2.score){
    return 1
  }
  return 0
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

> Ele compara um com todos?

Recomendo que você não se apegue a entender os algorítimos do sort. É um tópico complexo de algorítimos de estruturas de dados e cada browser usa um algorítmo diferente para ordenar. O V8 (motor que executa JS no chrome) por exemplo, usa [este](https://v8.dev/blog/array-sort) algorítimo. Investir muita energia nisso poderia te confundir, desfocar e ao mesmo tempo, ainda haverão assuntos mais importantes que este (para seu momento atual) no decorrer do treinamento. 

Essa primeira aula foi apenas uma introdução ao sort. Você ainda chegará [nesta](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1039812) aula onde falo mais sobre ele. Inclusive, mostro um exemplo nomeando o 1º parâmetro da função como `item2`. No fim das contas, não importa como a função vai retornar -1, 0 e 1 desde que você saiba como esse retorno vai impactar na ordenação dos dois itens em questão.

Se depois dessa aula permanecer alguma dúvida, é só dar o toque que explico de outra forma =)

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
hmmmm, beleza Roger!! Eu dei mais uma estuda, vi que é algo bem mais "Avançado". Só fiquei na dúvida pra saber como aquilo acontecia por baixo dos panos.
