### ISSUE TITLE
Propriedade definida como parâmetro de uma função retorna undefined, porque?

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3074]
### Etapa da aula

4

### Nome da aula

Correção dos exercicios 10 - 03-01 Etapa 04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Bom dia professor Roger Melo, tenho gostado muito das aulas, sua didática é incrivel.

Minha duvida é a seguinte. Estou refazendo o exercício n° 07 do grupo de exercícios 10. E ao refazer tentei colocar a propriedade (name) do objeto cat e dog como o parâmetro da função  que receberia os objetos e calcularia a idade, mostrando os nomes também. No entanto ao colocar a propriedade como parâmetro, e colocar a propriedade no argumento invocando a função, O JS retorna undefined nos nomes, ele apenas reconhece quando escrevo a propriedade diretamente na interpolação dentro da função. Estou com duvida nesta questão. Porque o JavaScript reconhece a propriedade do objeto diretamente na função, no entanto ao coloca-la como parâmetro de armazenamento ela retorna undefined ao colocar a propriedade de cada objeto como argumento.

```js
const cat = {
  name: 'Fluffy',
  age: 10,
  color: 'Green',
  bestFriends: ['Jerry', 'Lewis', 'Flurry'],
  sound: function () {
    return `${this.name} faz Miauuu!`
  }

}

const dog = {
  name: 'Jeremy',
  age: 10,
  color: 'Blue',
  bestFriends: ['Hunter', 'Pancho', 'Nixon'],
  sound: function () {
    return `${this.name} do Barks barks yo!`
  }
}

function agesObjectSum (objec1,object2,property) {
  return console.log(`A soma das idades de ${objec1.property} e ${object2.property} é ${objec1.age + object2.age}.`)
}

agesObjectSum(cat,dog,name)
```
      Retorno Console : A soma das idades de undefined e undefined é 22.

@Roger-Melo

**Comment by EneasFeynlinus** [comment]
Muito obrigado pelo modo que respondeu, realmente muito mais emocionante que receber a resposta pronta. 
    Ao ler os links realmente entendi onde estava errando na linguagem, estava colocando o argumento sem estar entre aspas para ser mandado ao parâmetro property que na verdade estava errado dentro do bloco da função, devido ao uso da notação de ponto, deveria ter usado a sintaxe de colchetes neste caso, como estava passando dinamicamente o nome da propriedade. 
    Havia lido anteriormente sobre o assunto, no entanto, estava perdido nos emaranhados de minha mente, realmente essa explicação refrescou e muito bem a memória e aprendi algo novo e reforcei algo desvanecido nos neurônios. 

Muito obrigado!! Maykell e a equipe Roger Melo.

**Comment by MivlaM** [comment]
Show. No que precisar, é só abrir uma nova issue =)
