### ISSUE TITLE
remover classes de todos os elementos de uma nodelist

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#3078]
### Etapa da aula

5

### Nome da aula

Query selector & query selector all 

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/842118

### Descreva a dúvida

Eu estava revisando a matéria e tentei criar um header com alguns links, a funcionalidade trata-se de que quando eu clicar em um elemento, ele adicione uma class active no elemento clicado e remove de todos os outros exceto o que foi clicado, eu consegui fazer funcionar, a dúvida é se teria um jeito mais conciso de chega no mesmo resultado.

```html
<nav class="nav-header">
<ul>
    <li class="active"><a href="#">Início</a></li>
    <li><a href="#">Arte</a></li>
    <li><a href="#">Shop</a></li>
    <li><a href="#">Blog</a></li>
    <li><a href="#">Sobre</a></li>
  </ul>
</nav>
```

```js
const headerLinks = document.querySelectorAll('.nav-header ul li')

headerLinks.forEach(link => {
  link.addEventListener('click', event => {
    if (!link.classList.contains('active')) {
      headerLinks.forEach(link => {
        link.classList.remove('active')
      })

      link.classList.add('active')
    }
  })
})
```

O problema que obtive ao remover as classes com esse método foi que eu não consigo usar efeitos de animações/transições

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, @dracoalv.

Antes de responder, deixa eu te dar algumas dicas...

Prefira postar o título da issue em pt-BR, pq provavelmente as pesquisas nas issues acontecem em português. Assim, se alguém pesquisar por uma palavra-chave que só existe no título da issue, por exemplo, a issue será exibida nos resultados da busca =)

Não precisa declarar o parâmetro `event` quando não for usá-lo.

---

> ## a dúvida é se teria um jeito mais conciso de chega no mesmo resultado

Sempre tem. 

Há uma forma de evitar o if e os forEach'es aninhados neste caso. 

Para chegar em uma solução mais elegante, recomendo que revise o material abaixo:

- [Event bubbling e event delegation - Aula 04-02](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890634)
- [O método filter - Aula 01-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/991048)

Pesquise nessas fontes, teste o seu código e poste aqui a solução na qual vc chegou. 

Vamos ver se ela é parecida com a minha =)

---

Feito isso, tem uma outra parada que vc deve questionar...

Será que é mesmo as `li`s que devem receber a class 'active'? Vc visualizou no console qual elemento está de fato recebendo o clique quando ele acontece?

---

> ## O problema que obtive ao remover as classes com esse método foi que eu não consigo usar efeitos de animações/transições

Geralmente, a animação ou transição estão especificadas na classe. 

Vou deixar abaixo um material que pode te ajudar com essa parte. Inclusive, esse site tem um conteúdo de CSS muito bom, vc pode deixar nos seus favoritos para futuras pesquisas.

- [Animation Techniques for Adding and Removing Items From a Stack](https://css-tricks.com/animation-techniques-for-adding-and-removing-items-from-a-stack/)

---

Fico no aguardo de sua solução =)

**Comment by dracoalv** [comment]
Muito bom dia, não entendi onde usar o filter, devo obter a referencia de todos os links com o querySelectorAll e transforma-lo em array através do Array.from() e depois passar o filter pra me retornar apenas o link que conter a classe active? (pois a saída deste filter esta me impossibilitando de usar o método remove() do classList

código atual:

```js
const menuBtn = document.querySelector('.header-menu')
const headerUL = document.querySelector('.header-ul')
const links = document.querySelectorAll('.header-ul li a')

const showMenu = () => {
  headerUL.classList.toggle('show')
}

const activeLink = Array.from(links)
  .filter(link => link.classList.contains('active'))

const headerTransition = event => {
  const clickedElement = event.target
  
  if (clickedElement.tagName === 'A') {
    activeLink.classList.remove('active')
  }

  clickedElement.classList.toggle('active')
}

menuBtn.addEventListener('click', showMenu)
headerUL.addEventListener('click', headerTransition)
```

**Comment by dracoalv** [comment]
eu consegui obter o resultado desejado através do forEach, mas agora estou tentando com filter

```js
const menuBtn = document.querySelector('.header-menu')
const headerUL = document.querySelector('.header-ul')
const links = document.querySelectorAll('.header-ul li a')

const showMenu = () => {
  headerUL.classList.toggle('show')
}

const headerTransition = event => {
  const clickedElement = event.target
  
  if (clickedElement.tagName === 'A') {
    links.forEach(link => {
      link.classList.remove('active')
    })
    clickedElement.classList.toggle('active')
  }
}

menuBtn.addEventListener('click', showMenu)
headerUL.addEventListener('click', headerTransition)
```

**Comment by Roger-Melo** [comment]
Isso mesmo, essa é uma forma de fazer =)

Esse é a marcação que usei nos testes que fiz. Procurei usar o `data-js` ao invés de classes, por questões de organização de código.

```html
<nav class="nav-header">
  <ul data-js="ul">
    <li><a data-js="a" href="#">Início</a></li>
    <li><a data-js="a" href="#">Arte</a></li>
    <li><a data-js="a" href="#">Shop</a></li>
    <li><a data-js="a" href="#">Blog</a></li>
    <li><a data-js="a" href="#">Sobre</a></li>
  </ul>
</nav>
```

Na forma que eu imaginei, o filter gera um array com as referências de todos os links, exceto o que foi clicado.

Feito isso, basta adicionar a classe `active` no link clicado e removê-la de todos os outros links.

```javascript
const ul = document.querySelector('[data-js="ul"]')
const links = document.querySelectorAll('[data-js="a"]')

ul.addEventListener('click', e => {
  const clickedLink = e.target  
  const otherLinks = Array.from(links).filter(link => link !== clickedLink)
  
  clickedLink.classList.add('active')
  otherLinks.forEach(link => link.classList.remove('active'))
})
```

É um tiro de bazuca pra matar uma formiga, eu sei. Mas isso é só uma ideia rápida que me veio à mente. Vc pode lapidá-la usando os princípios que mencionei acima =)

@dracoalv

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
