### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by RodrigoLimaMota** [roger-melo-treinamentos/curso-de-js-roger-melo#3085]
### Etapa da aula

7

### Nome da aula

Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/986667

### Descreva a dúvida

Roger, quando vc falou em refazer tudo sem consultar, vc incluiu a parte do HTML/BootStrap, ou somente o JS?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RodrigoLimaMota.

Vc tem essa resposta.

Só vc sabe a dificuldade que sentiu ou não sentiu com HTML e CSS da aplicação.

Se vc estiver com dificuldades nisso, é um indício que não seguiu o que foi recomendado [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1886#issuecomment-929202507).

E tá tudo bem se seguiu ou não. São escolhas.

Mas cada escolha traz suas consequências. 

A consequência de não ter base HTML e CSS é travar com marcação e estilo em qualquer aplicação/projeto que vc se propõe a construir. Seja com Bootstrap ou não.

Se tem dificuldades com bootstrap (ou qualquer outra lib HTML/CSS), o problema não é o bootstrap.

É a falta da base.

**Comment by RodrigoLimaMota** [comment]
Roger, eu segui sim, estudei conteúdo que você me indicou, e mais alguns por fora de CSS e HTML.

Compreendo que o que você quis me dizer, é que para entender qualquer biblioteca, é necessário estudar bem a linguagem nativa.


Sou iniciante ainda, não me aprofundei, mas em uma aula, você falou que para não perder tempo com CSS seria usado a lib BootStrap  e isso é um indício de que somente o JavaScript é necessário refazer até não agarrar mais nos códigos de uma aplicação e pelo mesmo motivo te fiz a pergunta.

Se eu tivesse a resposta eu não teria perguntado não é mesmo? kkk

Pelo que eu estudei, consigo compreender e reproduzir o HTML e CSS do popup e o HTML do formulário de boa. Já o BootStrap eu entendo mas não consigo reproduzir ainda.

Apenas depois da sua resposta deduzi que a resposta é sim.
Obrigado.

**Comment by RodrigoLimaMota** [comment]
Se eu tivesse a resposta, eu não criaria a issue. Peço por favor para ser
mais direto em esclarecer minha dúvida.
"indício que não seguiu o que foi recomendado aqui
<https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1886#issuecomment-929202507>
."
Quando você disse que usaria o bootstrap para focar no Javascript o indício
é que precisaria apenas garantir o JS mas pela sua resposta interpreto que
a resposta para minha pergunta é sim

"Vc tem essa resposta."
Se eu tivesse a resposta, eu não teria criado a issue.


Em qua, 16 de fev de 2022 22:42, Roger Melo ***@***.***>
escreveu:

**Comment by RodrigoLimaMota** [comment]
Para que você não interprete como um ressentimento da minha parte,

Estou refazendo o curso do 0 criando e postando as anotações da maneira que
você me indicou(eu tinha parado na aula do quiz-interativo).

O material que você me passou, é muita coisa, mas eu segui suas orientações
e estudei o material sim e minha pergunta não indicia nada disso que você
disse.
Não dá para eu aprofundar em tudo aquilo que você me passou. Se eu tivesse
feito isso não estaria nem na primeira aula do seu curso ainda. Estudei o
suficiente para entender o CSS do popup, por exemplo.
Sei da importância de ter uma base sólida em uma linguagem nativa para
aprender as libs e é exatamente por isso que comprei seu curso, para
futuramente aprender bibliotecas como React ou Angular por exemplo.

Até onde estudei o CSS, não dá pra sacar de BootStrap.
Sei que vou ganhar "patadas" de chefe no mercado de trabalho quando eu
fizer uma pergunta desse tipo, mas aqui estou na posição de aluno e você de
professor.
Pela sua resposta, vi que devo estudar o Bootstrap para refazer as
aplicações, mas o conceito do curso não é esse e no auge da minha
ignorância eu resolvi criar a issue.

Como sugestão, oriente os alunos até qual nível é necessário estudar outras
tecnologias para concluir seu curso ou fazer as aplicações, pois isso não
está claro para mim, mas aí já é com você, isso é apenas uma dica.
Seu curso é excelente, você tem uma ótima didática e não me arrependo de
nenhum centavo que paguei.

Não me interprete mal por favor.
Se um dia eu for bom em alguma coisa na minha vida, vai ser no front end e
pretendo usar seu conhecimento para me ajudar a chegar nesse objetivo.
Obrigado

Em qui., 17 de fev. de 2022 às 02:43, Rodrigo Lima ***@***.***>
escreveu:
