### ISSUE TITLE
Resumo da Aula Conhecendo o Firestore - Aula 01-11 da etapa 15

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#3086]
## O que é o Firestore?

- Firestore é um banco de dados noSQL oferecido pelo Google através de um serviços BAAS chamado Firebase.
- Para ter acesso, basta ter uma conta do gmail.
- Possui diversas features para resolver problemas comuns de aplicações web e aplicativos mobile.

## O que é um projeto no Firebase?

- Antes de criar nosso banco de dados, é preciso criar um projeto no Firebase.
- Um projeto no Firebase é um container para minhas aplicações web e é onde os serviços do Firebase para essas aplicações são organizados.
- É dentro de um projeto que eu registro quais serviços do Firebase serão utilizados

## Registrar um projeto no Firebase

- Após logar no firebase (https://firebase.google.com/) deve-se acessar Go to console
- Já no dashboard, clicar em Add project.
- A partir daí serão preenchidos alguns dados como:
    - Nome do projeto;
    - Habilitar ou não o Analytics do projeto;
    - Selecionar ou criar uma conta no Google Analytics;
    - Escolher a localização do Analytics (Brazil);
    - Nesse ponto o projeto foi criado.
- Com o projeto criado, já será dado acesso ao dashboard do projeto com todas ferramentas para gerenciar o back-end da aplicação

## Firestore Database vs Realtime Database

- O Firebase possui dois bancos de dados: Firestore e Realtime.
- O Realtime Database é o banco mais antigo do Firestore. É um banco menos organizado.
- O Firebase é o banco de dados mais recente do Firestore, parecido com o MongoDB, que é um banco de dados noSQL. É mais robusto que o Realtime.

## Criando um banco de dados no Firestore

- No painel principal, clicar no menu lateral na opção Firestore Database.
- Clicar no botão Create database.
- Selecionar a opção Start in test mode, por estarmos na fase de desenvolvimento e testes.
- O test mode permite que qualquer pessoa com uma referência do banco de dados possa interagir com ele.
- Após avançar, selecionar a localização do banco de dados, que deverá ser sempre a mais próxima de quem irá utilizara aplicação, pois isso tende a diminuir a latência.
- Latência é o atraso entre a causa e o efeito de alguma mudança em um software.
- Agora basta clicar no botão Enable, e o banco de dados é criado.

## Criando uma collection

- Podem ser criadas quantas collections forem necessárias desde que cada collection represente um tipo específico de informações.
- Para criar a collection, clicar no botão Start collection
- Deve-se nomear a collection. No exemplo vamos nomear como games e clicar no botão Next.
- Agora deverá ser adicionado o primeiro document a collection games. Document é um registro de game dentro da collection games.
- Cada document é uma estrutura muito parecido com objetos JavaScript, ou seja, é uma estrutura que contém pares de chave e valor.
- Devem ser preenchidas os fields (properties) e os values do document.
- No exemplo vamos usar: title: The Last Of Us (string); developedBy: Naughty Dog (string); createdAt: 02/16/2022 00:00:00 (timestamp). Clicar no botão Auto-Id para que o document tenha um Id único gerado automaticamente.
- Após o primeiro registro preenchido, clicar no botão Save.

## Documentação

- Tudo o que foi falado anteriormente se encontra na documentação do Firebase.
- Para acessar a documentação, clicar no botão que fica no canto superior direito Go to docs.
- Como no primeiro momento o interesse é como adicionar o Firebase na aplicação web, posicionar o mouse sobre a opção de menu Fundamentals e em seguida na opção Add Firebase - Web.

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🎯
