### ISSUE TITLE
Resumo da Aula 03-04 Tipos de referência vs Tipos primitivos da etapa 04

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3087]
**Tipos de Dados(primitivos, Tipos de referencia) {**

      primitivos (Numbers,strings,booleans,null,undefined,symbol,bigInt) {
      primitivo: Os dados do tipo primitivo, são um pouco mais simples que os tipos de referencial. São armazenados na memória na 
      forma de stack, ou seja, um em cima do outro. Como vantagem os tipos de dados do tipo primitivo são mais rápidos

      tiposDeReferencia: os dados do tipos de referencia, são separados para projetos mais complexos e maiores como Objetos e 
      arrays, 
      que carregam mais informação e precisam ser acessados randomicamente e não sequencialmente.
     }

**}**

**Armazenamento de Tipos de Dados (primitivos, Tipos de referencia) {**

     primitivos: O armazenamento do tipo de dado primitivo, é salvo em um stack(ou para o português, uma pilha, algo sequencial) e 
     armazena desde números strings, booleans e os nomes das variáveis.

     Tipos de Dados: O armazenamento do tipo de dados, são mais complexos e focados em um acesso randômico. No entanto ao 
     salvar uma array em uma variável, o nome atribuído a variável é salvo como um ponteiro na memoria stack como um dado 
     primitivo apontando para a array cujo a variável armazena.
	Caso uma cópia do objeto seja feita com um novo nome de variável, o JS vai apontar esse novo nome de variável com a cópia 
     para o mesmo objeto da variável original. Ou seja temos uma copia, mas na verdade a cópia seria uma parte da memória que 
     armazena um ponteiro para a memoria heap onde esta alocado a array. 
	Caso o valor da array seja modificado, essa modificação será valida para ambos os ponteiros.

**}**

**Comment by Roger-Melo** [comment]
Excelente @EneasFeynlinus, rumo à fluência! 🎯
