### ISSUE TITLE
Resumo da Aula Status de respostas HTTP 02-04 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3092]
A checagem pelo estado do _request_ não é suficiente porque se houver erros no _request_ (como um erro de escrita), a requisição passará por todos os estados da mesma forma. Para garantir que a checagem seja feita de forma apropriada, trabalhamos com a propriedade _status_ do objeto, pois quando ocorre algum erro (como por exemplo, _endpoint_ não encontrado), seu valor muda para `**404** `(que significa que os dados não foram encontrados), enquanto que, se tudo correr bem, o seu valor é _**200**_. No site MDN é possível ver vários tipos de status obtidos em uma requisição HTTP.

Podemos acessar o valor do status por **`request.status`**, assim, se a resposta do status for _200_, podemos pedir para que a informação seja exibida no console.

```js
if(request.readyState === 4 && request.status === 200){
    console.log(request.responseText) // exibe os dados no formato JSON se o estado for 4 (concluído) e se o request encontrou as informações requeridas (status 200)
}
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. Vamo que vamo, rumo à fluência! 🙌
