### ISSUE TITLE
Aplicação: Quiz interativo

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3093]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Jansen-Muniz/quiz-interativo.git

### Maiores dificuldades durante a implementação

Como fazer para comparar as respostas do usuário com as respostas corretas

### Menores dificuldades durante a implementação

Obter a referência do form e colocar o texto na tela.

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Jansen-Muniz** [comment]
ta certo, mestre =)

**Comment by MivlaM** [comment]
Olá, @Jansen-Muniz.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Como fazer para comparar as respostas do usuário com as respostas corretas

Mesmo com a dificuldade relatada, você conseguiu =)

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do `forEach` (um erro comum que algumas pessoas cometem).

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Uma sacada interessante que você fez em relação à usabilidade foi a de posicionar a mensagem dos pontos no local onde o usuário está olhando ao enviar o quiz.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Diretório do index.html

No diretório inicial do seu repositório, os arquivos da pasta exercício-19 devem ser colocados na raiz e essa pasta pode ser descartada.

![image](https://user-images.githubusercontent.com/29297788/154993235-5a1bc567-31b4-48a3-bc92-f333bd572813.png)

A pasta raiz da sua aplicação deve ter um index.html, exatamente como é mostrado nas aulas. Caso contrário, ao invés da página inicial com o quiz aparecer, a listagem de diretórios da aplicação é exibida, o que não é o desejado.

![image](https://user-images.githubusercontent.com/29297788/155000812-6f46a858-8cd9-4ff8-b98b-c5199bb0330d.png)

Mesmo que atualmente exista a possibilidade de servidores possuírem configurações que suportem servir arquivos com outro nome, é uma boa prática a página de entrada da aplicação ser nomeada como index.html.

---

## Posicionamento do estilo fontSize de `p`

Não faz muito sentido setar o estilo fontSize de `p` no escopo global, neste caso. 

Não é uma regra, mas ao manipular um elemento, se essa manipulação estiver concentrada em apenas um local, o codigo fica mais organizado.

Como já há uma manipulação do conteúdo textual desse parágrafo dentro do callback de envio do form, o ideal é deixar a manipulação de estilo e texto do elemento juntas. Veja no exemplo abaixo:

```js
//antes
const form = document.querySelector('.quiz-form')
const p = document.querySelector('.points')

p.style.fontSize = '25px'
// ...

```

```js
//depois
form.addEventListener('submit', event => {
  // ...
  if (score === 0) {
    p.textContent = 'ERROU TODAS, TENTE NOVAMENTE'
  }

  if (score === 100) {
    p.textContent = 'PARABÉNS! ACERTOU TODAS!'
  }

  p.style.fontSize = '25px'
  p.textContent = `SUA PONTUAÇÃO: ${score}`
})

```

---

## Const userAnswer

A const que você usou para armazenar as respostas que o usuário do quiz selecionar está no singular. Uma boa ideia seria você declará-la com um nome no plural, pois a const está armazenando várias respostas e por isso faz mais sentido que ela esteja no plural. Acredito também que dessa forma, a leitura do `forEach` ficaria mais legível:

```js
//antes
const userAnswer = [
  form.inputQuestion1.value,
  form.inputQuestion2.value,
  form.inputQuestion3.value,
  form.inputQuestion4.value
]
  // ...
  userAnswer.forEach((userAnswer, index) => {
// ...
}
```

```js
//depois
const userAnswers = [
  form.inputQuestion1.value,
  form.inputQuestion2.value,
  form.inputQuestion3.value,
  form.inputQuestion4.value
]
  // ...
  userAnswers.forEach((userAnswer, index) => {
// ...
}
```

---

## Linhas em Branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Seguindo esse princípio, você pode remover a linha 20 no if dentro do forEach. Por convenção, prefira que a primeira e última linha de um bloco sejam linhas preenchidas com código.

```js
//antes
userAnswer.forEach((userAnswer, index) => {

  if (userAnswer === correctAnswers[index]) {
    score += 25
  }
})
```

```js
//depois
userAnswer.forEach((userAnswer, index) => {
  if (userAnswer === correctAnswers[index]) {
    score += 25
  }
})
```

`let score = 0` também pode ter uma linha em branco abaixo de sua declaração.

---

## Nome da const usada para criar o parágrafo

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

A const precisa descrever o valor que ela está armazenando. Nesse caso, `p` poderia ser nomeada de forma mais descritiva. Se o que ela faz é armazenar a mensagem de pontuação do usuário, você pode, por exemplo, nomeá-la como `scoreMessage`.

```js
//antes
const p = document.querySelector('.points')
```

```js
//depois
const scoreMessage = document.querySelector('.points')
```

---

# Mensagem de pontuação

Quando você testou o código, viu que ele não estava funcionando como o esperado? Você percebeu que a string armazenada no `p.textContent`, quando a pontuação é 100 ou 0 não está aparecendo como resultado do quiz? Apenas o `p.textContent` fora dos blocos do if aparece como resultado.

Você pode ajustar o seu código armazenando o valor de `score` em duas consts, uma recebe o maior valor e a outra o menor valor. Depois, pode usá-las nos blocos de if e por meio do `return`, parar a execução da função após a respectiva mensagem.

Outra coisa, as mensagens podem ser armazenadas em template string podem ser mais descritivas. Você pode dar mais clareza para o usuário sobre a pontuação que ele teve em relação à pontuação total do quiz. 

Os ajustes ficariam assim, por exemplo:

```js
//antes
if (score === 0) {
  p.textContent = 'ERROU TODAS, TENTE NOVAMENTE'
}

if (score === 100) {
  p.textContent = 'PARABÉNS! ACERTOU TODAS!'
}

p.textContent = `SUA PONTUAÇÃO: ${score}`
```

```js
//depois
const highestScore = score === 100
const lowestScore = score === 0

p.style.fontSize = '25px'

if (highestScore){
  scoreMessage.textContent = `PARABÉNS! ACERTOU TODAS! SUA PONTUAÇÃO É DE: ${score}%`
  return
}

if (lowestScore){
  scoreMessage.textContent = `ERROU TODAS, TENTE NOVAMENTE. SUA PONTUAÇÃO É DE: ${score}%`
  return
}

scoreMessage.textContent = `SUA PONTUAÇÃO: ${score}`
```

Mas aqui tem um detalhe, se você inserir a posição da estilização do scoreMessage acima do primeiro if, como mostrado no exemplo acima, não precisa repetir essa estilização dentro dos ifs e abaixo deles.

A desvantagem disso é que quebra um pouquinho do que foi mostrado na observação sobre posicionamento e concentrar a manipulação do elemento em apenas um lugar. Como tudo, dessa maneira, há prós e contras, mas seria do jeito que eu faria.

---

## Refatoração do código

Há uma forma de eliminar a repetição de ifs para atribuir a string do parágrafo para a textContent.

Você pode criar uma função com o nome de `getScoreMessage` e dentro dela, criar um objeto `myScore` com propriedades que indicam a pontuação de 0 e 100 recebidas no parâmetro da função. Assim, você faz com que `scoreMessage.textContent` receba a invocação da função `getScoreMessage` com a pontuação `score` como argumento, a invocação da função retornará os valores das propriedades do objeto equivalentes a pontuação máxima e mínima, ou uma mensagem padrão para as pontuações entre 0 e 100.

As alterações ficariam assim, por exemplo:

```js
//antes
const highestScore = score === 100
const lowestScore = score === 0
// ...
if (highestScore){
  scoreMessage.textContent = `PARABÉNS! ACERTOU TODAS! ${score}`
  return
}

if (lowestScore){
  scoreMessage.textContent = `ERROU TODAS, TENTE NOVAMENTE ${score}`
  return
}
```

```js
//depois
const getScoreMessage = score => {
  const myScore = {
    0: `ERROU TODAS, TENTE NOVAMENTE ${score}`,
    100: `PARABÉNS! ACERTOU TODAS! ${score}`
  }

  return myScore[score] || `SUA PONTUAÇÃO: ${score}`
}
// ...
scoreMessage.style.fontSize = '25px'
scoreMessage.textContent = getScoreMessage(score)
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Jansen-Muniz** [comment]
Entendido, obrigado =)

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
