### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### ISSUE THREAD

**Issue by PatrickTav** [roger-melo-treinamentos/curso-de-js-roger-melo#3094]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/813573

### Descreva a dúvida

@Roger-Melo

Ola, Boa tarde . No  exericio de funções e callbacks tive a duvida de porque que quando passada a função de callback invocada da erro dizendo que callback não é uma função? 
# Sem invocação
```js
const invokeCallback = callback =>{
  callback
}
const logName = () =>{
  console.log('Patrick Tavares')
} 
invokeCallback(logName())
```
![image](https://user-images.githubusercontent.com/84410499/154364729-24699866-c647-4629-9c5f-9d006e75d80f.png)

# Com Invocação 
```js

const invokeCallback = callback =>{
  callback()
}
const logName = () =>{
  console.log('Patrick Tavares')
} 
invokeCallback(logName())
```
![image](https://user-images.githubusercontent.com/84410499/154364699-b84c52f2-db12-46f0-98d7-2175dc525288.png)

**Comment by MivlaM** [comment]
Olá, @PatrickTav. 

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Por que que quando passada a função de callback invocada da erro dizendo que callback não é uma função?

Não vou dar a resposta pronta, mas vou te mostrar o caminho para que você chegue nela. Por que estou fazendo isso? Se você entender a razão pela qual o código está apresentando essa mensagem de erro, você nunca mais terá esse tipo de problema.

Por agora, é importante que você entenda que existe um princípio que é essencial para que você saiba onde e o que está acontecendo à medida que você vai escrevendo seu código. Não sei se chegou a perceber, mas principalmente nas etapas iniciais do treinamento, o Roger usa o console.log praticamente a cada linha escrita, para mostrar o valor que uma determinada expressão / parâmetro / variável está armazenando. 

Isso não é feito apenas por motivos didáticos. 

Não assuma que suas variáveis estão recebendo os valores que você espera. 

**Sempre use console.log para checar suas variáveis**.

Faça o teste e responda em seguida: O que acontece se você exibir o valor do parâmetro callback da função `invokeCallback` no `console.log()`?

De acordo com a dica que o console.log lhe deu, o que você acha que pode resolver esse problema?

---

Fico no aguardo =)

**Comment by PatrickTav** [comment]
Pelo que eu vi, a invocação na verdade eu estava passando na invocação da invokeCallback, sendo assim fazendo que o callback dela seja reconhecido como uma função. Assim fazendo o erro que não temos função callback declarada

**Comment by Roger-Melo** [comment]
> ## Faça o teste e responda em seguida: O que acontece se você exibir o valor do parâmetro callback da função invokeCallback no console.log()?

@PatrickTav vc exibiu o parâmetro `callback` no console? O que ele estava armazenando?

Só pra ficar mais claro, qual valor é exibido no console se vc inserir como argumento de um console.log() a referência do parâmetro `callback` que está dentro da função abaixo?

```js
const invokeCallback = callback =>{
  callback // 👈🏻 referência do parâmetro
}
```

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
