### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by ecabral-29** [roger-melo-treinamentos/curso-de-js-roger-melo#3099]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ecabral-29/CJRM-Quiz

### Maiores dificuldades durante a implementação

- Deixar o código de uma forma clara após a refatoração;
- Decidir bons nomes para as variáveis;

### Menores dificuldades durante a implementação

- Manipulação do DOM;
- Lógica para calcular a pontuação do usuário.

**Comment by Roger-Melo** [comment]
Olá @ecabral-29.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
Olá, @ecabral-29.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Deixar o código de uma forma clara após a refatoração

O mais importante você já fez, que é fazer funcionar =)

Não se preocupe muito com refatoração agora. Refatoração é uma habilidade que é elevada com a prática.

Conforme você praticar, você vai percebendo aos poucos o que pode ser melhorado.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

O local de exibição dos pontos ficou bem posicionado na tela.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Seguindo esse princípio, você pode remover as linhas 28 e 32 na função `handleUserAnswer`. Por convenção, prefira que a primeira e última linha de um bloco sejam linhas preenchidas com código.

```js
//antes
// ...
  const checkUserAnswer = (userAnswer, index) => {
    const isAValidAnswer = userAnswer === correctAnswers[index]

    if (isAValidAnswer) {
      score += 25
      quizScore.textContent = score
      return
    }

    quizScore.textContent = score
    
  }

  userAnswers.forEach(checkUserAnswer)

}
```

```js
//depois
// ...
  const checkUserAnswer = (userAnswer, index) => {
    const isAValidAnswer = userAnswer === correctAnswers[index]

    if (isAValidAnswer) {
      score += 25
      quizScore.textContent = score
      return
    }

    quizScore.textContent = score
  }

  userAnswers.forEach(checkUserAnswer)
}
```

---

## forEach

A manipulação de DOM não precisa estar dentro do forEach. Independente se o if é executado ou não, o que precisa acontecer dentro do forEach, nesse caso, é apenas o cálculo dos pontos:

```js
//antes
const checkUserAnswer = (userAnswer, index) => {
  const isAValidAnswer = userAnswer === correctAnswers[index]

  if (isAValidAnswer) {
    score += 25
    quizScore.textContent = score
    return
  }

  quizScore.textContent = score
}

userAnswers.forEach(checkUserAnswer)
```

```js
//depois
const checkUserAnswer = (userAnswer, index) => {
  const isAValidAnswer = userAnswer === correctAnswers[index]

  if (isAValidAnswer) {
    score += 25
  }
    
}

userAnswers.forEach(checkUserAnswer)
quizScore.textContent = score
```

O forEach é um método síncrono. Isso significa que as linhas de código abaixo da invocação dele só serão executadas quando a execução dele for concluída, a mensagem de pontuação pode ser exibida na tela apenas depois que a pontuação foi calculada.

---

## Usabilidade

Um teste que você pode fazer é deixar o usuário mais consciente do progresso dele no quiz em relação à pontuação total. Por exemplo, você pode fazer isso inserindo uma porcentagem no `text.Content` que indica a pontuação final ("100%, 50%"...) ou inserindo uma barra e pontuação total do quiz após a quantidade de acertos, exemplo: "50/100".

---

## Variável isAValidAnswer

No geral, você escolheu bons nomes para suas variáveis.

Um princípio que gosto de seguir ao nomear (e que vi que você já sacou) é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Sendo assim, vou te mostrar um ajuste sutil no nome da variável `isAValidAnswer`.

Resposta correta é diferente de resposta válida. Uma resposta "inválida" seria, por exemplo, uma resposta que não está entre nas alternativas. 

Exemplo:

Se eu pergunto "Emerson, qual é o coletivo de cães, alcateia ou matilha?" e você responde "manada", vc deu uma resposta inválida, pois é uma resposta que não está entre as alternativas.

Se a resposta fosse alcateia ou matilha, ela seria válida.

Nem toda resposta válida é correta, mas toda resposta correta é válida. 

Sacou a ideia? =)

Considerando isso, `isAValidAnswer` pode ser renomeada para `isCorrectAnswer`."

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by ecabral-29** [comment]
Olá Maykell, boa noite!

Muito obrigado pela analise da aplicação, as observações fizeram muito sentido!

Fico feliz por ter conseguido implementar o Quiz Interativo, que venham os próximos.

Obrigado @Roger-Melo e @MivlaM!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
