### ISSUE TITLE
toLocaleUpperCase x toUpperCase  -  toLocaleLowerCase x ToLowerCase

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#31]
Olá Roger,
tenho uma duvida em relação ao 'toUpperCase' x 'ToLocaleUpperCase' e 'toLocaleLowerCase' x 'ToLowerCase', pois 'toUpperCase' e 'ToLowerCase' são métodos que transforma letras em maiúsculas e minusculas, já os outros 2 também fazem o mesmo, vc pode me dizer qual e a diferença entre ambos, pois uso o VSCode e quando uso esses metodos, ele sempre me dar ToLocaleUpperCase e ToLocaleLowerCase como primeira opção de uso.

**Comment by Roger-Melo** [comment]
Oi @Mateus20Barros.

"Locale" é um set de preferências de um idioma para uma interface de usuário.

Na maioria das vezes, `toLocaleLowerCase()` e `toLowerCase()` vão retornar o mesmo resultado.

Para alguns locales, como o Turkish, que não tem mapeamento de cases (minúsculos e maiúsculos) em Unicode, pode haver um output diferente. Mas, na maioria dos idiomas, `toLocaleLowerCase()` e `toLowerCase()` retornam o mesmo resultado. Isso também vale para `toLocaleUpperCase()` e `toUpperCase()`.

Quanto às sugestões do VSCode, recomendo que ignore. Ou melhor, remova.

Perceba que durante as aulas eu não uso sugestões, muito menos autocomplete. Isso me faz focar no que é importante naquele momento e, consequentemente, pelo exemplo, o ideal é o aluno fazer o mesmo.

Quando alguém está em fase de aprendizado da linguagem, essas parafernalhas mais atrapalham do que ajudam.

Para remover recomendações e autocomplete do VSCode, pressione "ctrl+shift+p" para que a command pallete seja exibida. Insira "settings", escolha a opção "Open Settings (JSON)" e deixe os valores das chaves abaixo como `false`:

```json
  "editor.suggestOnTriggerCharacters": false,
  "editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
  },
  "editor.parameterHints.enabled": false,
```

Respondi sua dúvida?

**Comment by Mateus20Barros** [comment]
obg.. respondeu sim vlw :)

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue mas no que precisar, é só dar o toque =)
