### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#3101]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ghostnetrn/quiz-interativo

### Maiores dificuldades durante a implementação

Não há.

Uma dúvida: como fazer para capturar a questão que foi respondida e inserir um texto explicativo abaixo de cada opção?

Exemplo:
![image](https://user-images.githubusercontent.com/54438080/154517609-f9d211f3-0841-4fbc-84bf-d0568d1af3fe.png)

### Menores dificuldades durante a implementação

Não há.

**Comment by Roger-Melo** [comment]
Olá @ghostnetrn. 

O link que vc postou na issue está levando para um repositório que não existe.

![image](https://user-images.githubusercontent.com/29297788/154600661-a53b93bc-699b-4a1d-96dc-18cb567457ac.png)

**Comment by ghostnetrn** [comment]
Oi Roger, o repo tava privado. Agora tá público, ok

**Comment by Roger-Melo** [comment]
Olá @ghostnetrn.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
Olá @ghostnetrn.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas Decisões

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Isso dá mais legibilidade ao ler a expressão `userAnswer === correctAnswers[index]`.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

No geral, você escolheu nomes descritivos para suas variáveis e funções.

---

## Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo checked no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## Exibição dos pontos

A solução de exibição dos pontos da sua aplicação está idêntica à solução que foi apresentada no curso nas aulas posteriores ao aviso pedindo para que a aplicação fosse enviada.

Por este motivo, a implementação do código da aplicação que exibe os pontos não será analisada. 

A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas até o momento que foi pedido o envio da aplicação. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

---

## Novas funcionalidades

Tanto limpar as alternativas escolhidas nas respostas, quanto capturar a questão que foi respondida e inserir um texto explicativo abaiso das alternativas, são novas funcionalidades, e novas funcionalidades não devem ser adicionadas agora. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

---

## Indentação com quatro espaços ao invés de dois.

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

- [Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode deixar uma linha em branco entre a const `userAnswers` e o `event.preventDefault()`.

```js
//antes
form.addEventListener('submit', event => {
  event.preventDefault()
  const userAnswers = [
    //...
  ]
```

```js
//depois
form.addEventListener('submit', event => {
  event.preventDefault()

  const userAnswers = [
    //...
  ]
```

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by ghostnetrn** [comment]
Sim, obrigado! Ajudou muito.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
