### ISSUE TITLE
Resumo da Aula 02-03 da etapa 07 - setInterval() e animação da pontuação

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3106]
Método setInterval

- Similar ao setTimeout
- No setInterval a função é executada repetidamente e a repetição da execução da função
acontecerá no intervalo de tempo especificado.

Ex: `setInterval(() => {}, 1000)`

**Comment by Roger-Melo** [comment]
Show @Jansen-Muniz. Vamo que vamo, rumo à fluência! 🙌
