### ISSUE TITLE
feedback de um código com fetch e try/catch

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#3108]
### Etapa da aula

11

### Nome da aula

Try/Catch Aula 06-05

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1376383

### Descreva a dúvida

Boa noite Roger. Estou treinando os requests e try/catch da etapa 11 e gostaria de saber se você pode dar uma olhada no meu código do repositório https://github.com/zolive72/insertUsersDataInTable e me dar um feedback. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @zolive72.

Não vi possibilidades de ajustes decisivos em seu código. Na real, vc parece ter pegado bem a lógica até aqui =)

Talvez o que vc pode testar é mudar alguns nomes de variáveis e ver se faz sentido ao ler o código.

Vc pode testar, por exemplo, mudar o nome das consts `data` para `users`. Apenas pelo benefício da especificidade.

```javascript
// antes
const data = await response.json();
return data;

// ...

const data = await getUsersData();

data.forEach(/* ... */)
```

```javascript
// depois
const users = await response.json();
return users;

// ...

const users = await getUsersData();

users.forEach(/* ... */)
```

---

Observe que o parâmetro `userData` está sendo usado dentro da função apenas para que o destructuring seja feito nele:

```javascript
const insertUsersDataInDOM = userData => {
  const [id, name, username, email, phone] = userData;

  // ...
}
```

Se quiser deixar o código mais conciso, vc pode executar o destructuring diretamente no parâmetro:

```javascript
const insertUsersDataInDOM = ([id, name, username, email, phone]) => {
  // ...
}
```

Já que uma função que não retorna valor retorna `undefined` e o retorno da invocação de `insertUsersDataInDOM` não vai ser aproveitado, vc pode eliminar o bloco:

```javascript
// antes
const insertUsersDataInDOM = ([id, name, username, email, phone]) => {
  tableBody.innerHTML += `
    <tr>
      <th scope="row">${id}</th>
      <td>${name}</td>
      <td>${username}</td>
      <td>${email}</td>
      <td>${phone}</td>
    </tr>
  `
}
```

```javascript
// depois
const insertUsersDataInDOM = ([id, name, username, email, phone]) => 
  tableBody.innerHTML += `
    <tr>
      <th scope="row">${id}</th>
      <td>${name}</td>
      <td>${username}</td>
      <td>${email}</td>
      <td>${phone}</td>
    </tr>
  `
```

Isso vai fazer com que o retorno implícito da arrow function retorne o retorno no qual a atribuição à innerHTML resulta. Mas tanto faz, pq esse retorno não está sendo usado.

---

Outra coisa que vc precisa observar é a consistência do seu estilo de código.

No `catch` abaixo, por exemplo, há uma linha com `;` e outras sem.

```javascript
catch (error) {
  document.body.innerText = error.message;
  document.body.style.color = 'red'
  document.body.style.fontSize = '25px'
}
```

Isso se repetiu em outras partes do código. 

O ideal é que vc faça uma escolha e seja consistente com essa escolha no decorrer do código.

---

Mas como eu disse no início, não são ajustes decisivos. 

São apenas testes que vc pode fazer e ver se fazem sentido pra vc ou para possíveis pessoas que venham a ler o código =)

**Comment by zolive72** [comment]
Obrigado Roger pelas observações que ajudam a melhorar o código. Deus
abençoe você e sua equipe.

Le ven. 18 févr. 2022 à 23:44, Roger Melo ***@***.***> a
écrit :

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
