### ISSUE TITLE
duvida a cerca do certificado de conclusão do curso

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#3110]
### Etapa da aula

1

### Nome da aula

Aula inaugural - Aula 0-0

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928

### Descreva a dúvida

Oi professor, bom dia. A duvida aqui é mais para saber sobre o certificado de conclusão do curso, se ele é aprovado pelo MEC ou algo relacionado.

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @CarlosHenrique2208.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## A duvida aqui é mais para saber sobre o certificado de conclusão do curso, se ele é aprovado pelo MEC ou algo relacionado.

Segundo a regulamentação do MEC, cursos livres como o CJRM não são reconhecidos pelo MEC, mas são atividades legais e amparadas por decreto.

Você pode procurar saber mais a respeito disso com uma rápida pesquisa no google.

- [Cursos livres são reconhecidos pelo mec?](https://www.google.com/search?q=cursos+livres+s%C3%A3o+reconhecidos+pelo+mec%3F&sxsrf=APq-WBvESZ9TuybLru743VB0gGvQ5e8h_g%3A1645201370668&ei=2scPYpGbKJvC5OUPuZqn8As&ved=0ahUKEwiR8KDa1In2AhUbIbkGHTnNCb4Q4dUDCA4&uact=5&oq=cursos+livres+s%C3%A3o+reconhecidos+pelo+mec%3F&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABKBAhGGABQyQdYyQdgjwloAXABeACAAQCIAQCSAQCYAQCgAQHIAQjAAQE&sclient=gws-wiz)

No momento que você precisar do certificado, pode enviar um email para oi@rogermelo.com.br =)
