### ISSUE TITLE
Aplicação: Todo-list

### ISSUE THREAD

**Issue by aisl1n** [roger-melo-treinamentos/curso-de-js-roger-melo#3124]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/aisl1n/todos-app

### Maiores dificuldades durante a implementação

Acredito ser ainda ser a refatoração do código final.

### Menores dificuldades durante a implementação

A parte de referenciar as classes através dos document.querySelector.

**Comment by Roger-Melo** [comment]
Olá @aisl1n.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @aisl1n!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Acredito ser ainda ser a refatoração do código final.

Feito é sempre melhor do que perfeito.

Uma vez que vc faz funcionar (que é o mais importante num primeiro momento), sempre poderá voltar no código e ver o que pode ser melhorado, a medida em que vai avançando no treinamento =)

---

## Contraste de cores 

As cores do h1 "Todos" e dos placeholders dos inputs não estão contrastando com o fundo.

Já que o fundo dos dois textos é escuro, vc pode testar se aplicar cores mais claras nesses textos faz com que eles contrastem mais com o fundo.

---

## Cursor pointer

Como o cursor pointer está setado em toda a li, dá a impressão que o clique em qualquer parte da li executará alguma ação, o que não é verdade. 

Já que apenas o clique no texto marca o to-do como completo, vc pode limitar o cursor pointer para que ele seja exibido apenas no hover do texto =)

---

## Comentários

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Indentação com quatro espaços ao invés de dois

Recomendo que ao invés de 4 espaços para indentação, use 2. Isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

A partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

- [Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

# `event` global 

Em `addTodo`, `event` foi usado na expressão `event.target.reset()`:

```javascript
const addTodo = inputValue => {
  if (inputValue.length) {
    // ...
    event.target.reset()
  }
}
```

Porém, o `event` declarado como parâmetro do callback do listener de envio do `formAddTodo` não foi inserido como argumento da invocação de `addTodo`:

```javascript
formAddTodo.addEventListener('submit', event => {
  // ...
  addTodo(inputValue)
})
```

Isso significa que a expressão `event.target.reset()` em `addTodo` está usando o `event` global. 

Mesmo que tenha funcionado, o ideal é que o parâmetro `event` seja usado na expressão. Isso por que o [event global](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) foi descontinuado. O VSCode geralmente insere um traço no meio de propriedades e métodos que foram descontinuados.

![image](https://user-images.githubusercontent.com/29297788/155909500-63ac3342-471f-4fa6-82c8-38966154cc95.png)

Quando você insere o event como parâmetro de um callback de listener de evento e usa ele, ao invés de usar o event global, você está usando o [Event interface](https://developer.mozilla.org/en-US/docs/Web/API/Event) =)

```javascript
// antes
const addTodo = inputValue => {
  if (inputValue.length) {
    // ...
    event.target.reset()
  }
}

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()
  addTodo(inputValue)
})
```

```javascript
// depois
const addTodo = event => {
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    // ...
    event.target.reset()
  }
}

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  addTodo(event)
})
```

Já que agora o callback anônimo do listener de envio do `formAddTodo` está apenas invocando `addTodo` e evitando que a página seja carregada, vc pode referenciar `addTodo` diretamente como callback do listener:

```javascript
const addTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    // ...
    event.target.reset()
  }
}

formAddTodo.addEventListener('submit', addTodo)
```

---

## Considerações finais

Seu progresso em relação à análise do quiz é perceptível. Vc demonstrou ter entendido bem a lógica até aqui.

Como vc foi bem na implementação dessa aplicação e listou refatoração como uma dificuldade, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

É possível criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Eu "desfiz" as funções relacionadas à busca de to-dos e o callback do listener de evento ficou da forma abaixo. 

Faça o teste:

```javascript
inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */
})
```

Tudo certo até aqui?

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma única função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

inputSearchTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
})
```

Feito isso, vc pode nomear o callback do listener de evento como `searchTodo`, por exemplo.

Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, pq ao bater o olho no nome da função, a ação que ela executa fica explícita:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}

inputSearchTodo.addEventListener('input', searchTodo)
```

Sacou a ideia?

**Comment by aisl1n** [comment]
Olá @Roger!
Obrigado pela avaliação, e de cara já deixo a imagem abaixo como questionamento, se é isso que chamamos de "Refactoring".
![refactor - todos-app](https://user-images.githubusercontent.com/36649051/156093859-4edb3da1-ca5f-477b-955e-36b077eccc24.png)

**Comment by Roger-Melo** [comment]
Isso aí, sempre tem como melhorar =)
