### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#3131]
Nesta aula foi exemplificado alguns métodos de String, como por exemplo: lastIndexOf(), slice(), replace(), que são podem ser utilizados em algumas situações. Obter o último índex de um determinado caractere, obter partes de uma string, ou substituir partes da string.

**Comment by Roger-Melo** [comment]
Excelente @paulovieiradasilva, rumo à fluência! 🎯
