### ISSUE TITLE
Problema com a chave da 3ª Aplicação

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3135]
### Etapa da aula

12

### Nome da aula

Obtendo informações da cidade - Aula 01-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1408269

### Descreva a dúvida

@Roger conforme orientado por vc, eu deletei a chave fiz outra e nada, depois de varias tentativas e erros, criei mais duas chaves com e-mails diferentes e deu o mesmo erro, acredito que possa ser lá no servidor. vou aguardar até amanhã para testar novamente. Ou se vc tiver outra forma de acessar e so me avisar.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Sobe a aplicação num repositório do github e linka o repo aqui.

Assim eu consigo testar na minha máquina e te ajudar com mais precisão =)

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Sobe a aplicação num repositório do github e linka o repo aqui.

Assim eu consigo testar na minha máquina e te ajudar com mais precisão =)
