### ISSUE TITLE
Resumo da Aula Lendo dados do Firestore - Aula 01-13 da etapa 15

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#3138]
## Como obter collections do Firestore?

- Na documentação (Go to docs > Build > Firestore) acessar a opção do menu lateral read data.
- Acessar a opção Get data once.
- No menu lateral direto acessar Get all documents in a collection.
- Obtemos a referência do collection games através da função collection(), passando a referência do banco de dados (db) e o nome do collection (games) e importando essa função do firestore.
- Com a collection obtida, eu posso adicionar, atualizar, remover e obter documents dessa collection.
- Para obter os documents, usar a função getDocs(), importando a mesma do firestore.
- O getDoces() faz uma consulta ao banco, então ele faz uma requisição assíncrona, e ele retorna uma querySnapshot.
- Podemos utilizar tanto o async await com try catch como podemos também obter através de um then catch.

### O que é um querySnapshot?

- É uma fotografia (representação) de como a collection games está no momento do request.

## Como obter os documents de um collection no Firestore?

- Vamos ver duas maneiras: a da documentação e uma maneira alternativa.
- A primeira maneira é através do método forEach() do prototype do objeto querySnapshot.
- No resultado do forEach(), ao verificar o prototype, temos o método data() que é utilizado para retornar de fato os dados dos documents da collection.

```jsx
querySnapshot.forEach(doc => console.log(doc.data()))
```

- A maneira alternativa é utilizar a propriedade docs de querySnapshot, onde esse docs é um array, e a partir desse array utilizamos o método forEach() para percorrer esse array.

```jsx
querySnapshot.docs.forEach(doc => console.log(doc.data()))
```

- A grande diferença entre as duas maneiras é que na primeira estamos condicionados ao método forEach() do objeto querySnapshot, e a segunda é que estamos utilizando o método forEach() nativo do JavaScript, encadeado em um array, onde se eu precisar fazer algo diferente com o resultado desse array, não estarei condicionado a um objeto querySnapshot.
- Como a ideia é inserir o resultado da query na página, então queremos percorrer um array para gerar um outro valor que não necessariamente é um array, posso substituir o forEach() por um reduce().
- Dentro dos valores que esperamos, temos o createdAt, que se exibido no console, vemos um timestamp. Esse objeto createdAt tem um método toDate() que converte um objeto timestamp do Firestore para um objeto do tipo data JavaScript, e retorna esse objeto data do JavaScript.
- O timestamp do Firebase usa nanosegundos para representar o tempo, por isso o Firebase tem um objeto diferente de data.

## Documentação

- Tudo o que foi feito nos passos acima estão na documentação do Firebase.
- A documentação do Firebase é dividida por categorias, então podemos acessar Fundamentasl > Add Firebase - Web
- O novo menu principal horizontal da documentação terá os mesmos nomes que temos no dashboard do Firebase, com os itens Build, Release and Monitor e Engage.
- Ao acessar Build > Firestore, no menu esquerdo podemos ver API reference.
- Na seção API reference > Web podemos ver toda a documentação da API do Firestore que está sendo usada no front-end da aplicação, inclusive vemos o que é um timestamp, e no menu a direita temos os methods, onde é possível vermos o método toDate(), que converte o timestamp em um objeto data JavaScript.

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas, rumo à fluência! 🎯
