### ISSUE TITLE
Refactoring dos exercícios da aula 1, etapa 9

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#3139]
### Etapa da aula

9

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1067811

### Descreva a dúvida

Para esses exercícios, utilizei o mesmo esquema de criar uma função nomeada **getArrayCopy** que faz uma copia do array utilizando o map.

```js
const getArrayCopy = array => array.map(item => item)
```

- Questão 02, queria saber quais os problemas da minha resolução, já que usei metade do codigo da versão já refatorado apresentada na correção.

```js
const people = [
  { firstName: 'Estevão', lastName: 'Rodriguez', score: 90 },
  { firstName: 'José', lastName: 'Antônio', score: 100 },
  { firstName: 'Felipe', lastName: 'Tavares', score: 71 },
  { firstName: 'Eric', lastName: 'Silva', score: 82 }
]

//RESOLUÇÃO_ALUNO
const people123 = getArrayCopy(people)
.sort((a, b) => a.score - b.score)

//RESOLUÇÃO_PROFESSOR
const people123 = people
.map(({ firstName, lastName, score }) => ({ firstName, lastName, score }))
.sort((a, b) => a.score - b.score)

console.log(people123)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208.

> ## Para esses exercícios, utilizei o mesmo esquema de criar uma função nomeada **getArrayCopy** que faz uma copia do array utilizando o map.

Aqui é importante entender a diferença entre cópia do array e cópia dos itens do array.

Se o item do array é um objeto, esse objeto não será copiado. Como objetos são tipos de referência, o objeto será apenas referenciado. 

Ou seja, o objeto do array original e o objeto do novo array é o mesmo objeto.

Talvez vc já saiba disso, mas achei importante mencionar.

> ## Questão 02, queria saber quais os problemas da minha resolução, já que usei metade do codigo da versão já refatorado apresentada na correção

Pelo que vi, na sua solução vc não encadeou a invocação do sort em um array com novos objetos. Ao invés disso, apenas retornou os objetos originais.

Se a intenção não é fazer mutação nos objetos originais, tá tudo bem trabalhar com eles. 

Agora, se a intenção é mudar o valor da propriedade de um objeto, por exemplo, o ideal é que um novo objeto seja criado ao invés de modificar a propriedade original. É o princípio da imutabilidade. Assim, vc tende a diminuir bugs em sua aplicação.

```javascript
// código mutável (modifica o objeto original)
const obj = { prop1: 1 }

obj.prop2 = 2

console.log(obj) // {prop1: 1, prop2: 2}
```

```javascript
// código imutável (cria um novo objeto ao invés de modificar o objeto original)
const obj = { prop1: 1 }

const obj2 = { // 👈🏻 novo objeto criado
  prop1: obj.prop1,
  prop2: 2
}

console.log(obj2) // {prop1: 1, prop2: 2}
```

O código acima é apenas uma das formas de não modificar o objeto original.

Não se preocupe se esse conceito aida é novo pra vc. Nas próximas aulas vc será exposto à ele com vários casos de uso =)

Ficou mais claro?

**Comment by CarlosHenrique2208** [comment]
tudo certo, no caso de arrays e objetos acho preferível fazer uma copia e não mexer no original, por precaução. Então usar de códigos que não modifiquem o original, ou que modifiquem somente uma copia do original é algo mais seguro que me dá mais liberdade de tentar várias opções durante a aplicação.

enfim, obrigado de novo por responder professor, perdão a falta de atenção em não responder as issues.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
