### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#314]
**Minha aplicação**
[TBBQ - The Big Brain Quiz](https://github.com/Will-Andrade/CJRMProjects/tree/master/interactiveQuiz)

**Minhas maiores dificuldades**
1. Empolgação
  * Quando cheguei na Etapa 7 e vi que a atividade era basicamente por conta, fiquei extremamente empolgado e cheio de ideias que no fim me custaram quase 1 mês e meio desenvolvendo a aplicação.
2. Vergonha / Medo
  * Vergonha de pedir ajuda para o Sr. quando tive dificuldade (exemplo: fiquei quase duas semanas travado mentalmente desenvolvendo uma lógica para randomizar as perguntas e respostas que apareceriam na tela.
3. Desconhecer pré requisitos
  * Como a empolgação tinha me levado às alturas, minhas ideias foram madurando aos poucos e quis desenvolver mais e mais funcionalidades na aplicação. Durante esse processo, fiquei incrívelmente frustado por tentar fazer certas coisas que depois descobri que não conseguia pois não as tinha estudado ainda na trajetória rumo à fluência.
4. Bootstrap
  * Demorei um certo tempo para compreender o uso do Bootstrap pois eu tenho certo domínio apenas no HTML5 e CSS3 vanilla

**Minhas menores dificuldades**
1. Pensar como a JavaScript
  * Ao criar o código, pensar em grande parte das funcionalidades, interagir com a DOM e finalizar requisitos, não foi tão complicado graças às suas aulas que me fizeram entender de fato o que eu estou escrevendo.
2. Manipulação da DOM
3. Todo o básico de JS até o momento (Etapa 7)
4. Utilizar a documentação, Google e outras ferramentas para sanar dúvidas e atacar dificuldades

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Willian.

Primeiramente, parabéns pelo esforço em desenvolver a primeira aplicação dentro do CJRM =)

Eu não sei se você chegou a assistir à [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928) e se recebeu o e-mail com os requisitos para ter sua aplicação analisada. De qualquer forma, enviei o e-mail para o willian.santos.andra@...

Mas basicamente, um dos requisitos é que a aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas.

Eu preciso que você faça isso para que eu entenda o que você realmente aprendeu até aqui apenas segundo os meus ensinamentos.

Não estou dizendo que essa versão da aplicação que você enviou não é válida. Pelo contrário, eu recomendo que você salve ela e, no decorrer do treinamento, você terá ideias de como melhorar essa versão do código.

Mas no momento, para que a sua aplicação seja analisada, eu preciso que você faça ela o mais próximo possível do que foi mostrado nas aulas. Antes de inovar a receita, é preciso dominá-la.

Então eu recomendo que no início, enquanto você está aprendendo, você siga a receita à risca. Depois que dominar a receita, aí sim é hora de experimentar modificá-la.

E para que eu possa analisar o código com mais precisão, eu preciso que você siga o que está descrito nos requisitos do e-mail sobre as análises das aplicações. Você consegue fazer isso e me enviar um link com a nova versão?

Se houver alguma dúvida, pode dar o toque. Estou aqui pra te ajudar a alcançar a fluência na linguagem =)

@Will-Andrade

**Comment by Will-Andrade** [comment]
Não, não tinha visto essa nova aula inaugural ainda. E recebi sim o e-mail, farei conforme pedido.
Tudo bem professor, vou lhe enviar o link aqui em breve! Mas como disse, fiquei empolgado com o projeto e como o requisito era "faça sua versão" achei que podíamos fazer funcionalidades diversas com todos os conhecimentos do curso até o momento kkkk

@Roger-Melo

**Comment by Will-Andrade** [comment]
Olá professor, boa noite. Eis o link da nova versão da aplicação conforme pedido
[Meu Quiz Interativo](https://github.com/Will-Andrade/CJRMProjects/tree/master/interactiveQuizCJRMVersion)

Ps: Assisti às aulas posteriores à atividade da lista em questão (desenvolver minha versão do quiz) e gostei de como o senhor criou aquela animação de contagem da pontuação. Adaptei para a minha versão do quiz e espero que não tenha problema.

Com essa versão do quiz, minha maior dificuldade foi:
1. Entender o Bootstrap;

As menores dificuldades:
1. Desenvolver a aplicação sozinho 
  * Após assistir às aulas não tive necessidade de voltar e revê-las para criar o código.
2. Manipulação da DOM
3. Entender JavaScript

Espero que tudo esteja ok agora professor, obrigado pelo toque! :+1: 
@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Willian.

Legal, vou dividir a análise baseada nos critérios que achei mais relevante, vamos lá =)

## Lógica

Veja se é possível eliminar as manipulações do `zIndex` no `app.js`, pois talvez ele seja desnecessário se `z-index: 1;` for inserido como regra da `.popup-wrapper` (no `styles.css`).

## Organização de código

### Local de declaração de variáveis

Prefira declarar `scoreAnimation` e `showUserScore` antes de suas invocações. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo). 

A const `closePopupClasses` pode ser declarada dentro da única função em que ela é usada (closeScoreFeedback), isso deixará a leitura do código da `closeScoreFeedback` mais fluida, pois não será necessário procurar pela `closePopupClasses` fora da função. 

### Nomes de variáveis

Em geral, as variáveis da aplicação receberam bons nomes.

Eu apenas deixaria a função `closeScoreFeedback` com um nome mais descritivo, como `closeScorePopup`. 

### Linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo esse princípio, eu adicionaria uma linha em branco abaixo da declaração da let `userScore`:

```javascript
// antes
const handleQuizSubmit = event => {
    event.preventDefault();

    let userScore = 0;
    let userAnswers = [
        // ...
    ];

    // ...
}

// depois
const handleQuizSubmit = event => {
    event.preventDefault();

    let userScore = 0;

    let userAnswers = [
        // ...
    ];

    // ...
}
```

Essa linha em branco separa, visualmente, o conceito "armazenamento de pontos do usuário" do conceito "armazenamento de respostas do usuário".

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

### Uso de `let` ou `const`

Como a let `userAnswers` não terá seu valor modificado, ela pode ser declarada como uma `const`. Isso sinalizará, visualmente, que o valor que o identificador `userAnswers` armazena será o mesmo no decorrer de toda a aplicação.

---

Sobre a dificuldade em entender o Bootstrap, é natural ter um pouco dessa dificuldade no início. Você usará bastante a documentação dele e ler documentações, aos poucos, tenderá a se tornar um hábito para você.

---

Novamente, parabéns pelo esforço Willian =)

Fez sentido o que falei acima?

@Will-Andrade

**Comment by Will-Andrade** [comment]
Sim, fez sentido e me ajudou bastante!
Obrigado pelo toque com linhas em branco entre variáveis e constantes e a questão de onde declarar variáveis. Isso é algo que ainda pretendo aperfeiçoar.
E sobre o Bootstrap: é um framework legal que facilita demais a criação de UI. Espero que nos próximos projetos o senhor explore bem mais seu uso e pessoalmente irei tentar criar mini projetos utilizando ele.

Obrigado pelo feedback!
@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal, @Will-Andrade. Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova =)
