### ISSUE TITLE
Resumo da Aula 02-03 Obtendo e setando Atributos da etapa 05

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3141]
(Obtendo e setando Atributos)

Obtendo e setando Atributos() -> Temos muitos atributos HTML como src, class, href e etc e nos podemos obter e setar também com o java script. Mas como fazer isso?

**Obtendo referencia do link () -> {**

=> Primeiro vamos salvar na variavel link através do método querySelector() nossa referencia para o link que queremos manipular que neste caso seria a tag ancora a com o atributo href onde é colocado o endereço da pagina web a ser linkado.

```JS
const link = document.querySelector('a')
```

=> Segundo, logo após salvar a tag a de ancora na variavel link, vamos utilizar o método getAttribute('href') que como sugestivamente é escrito ele pega o atributo e nos mostra se relmente foi pego.
**}**

**Como setar um atributo (sertAtribute) {**
=> utilizando da variável onde foi armazenado a referencia da tag a(ancora) que possui o atributo href. vamos chamar a variável e aplicar o método setAtribute('atributeNAme','mudanças no atributo')

```JS
link.setAttribute('href', 'https://rogermelo.com.br/')
```

**}**

**Modificando texto do link (innerText) {** 

=> através da variável link onde foi guardado a referencia da tag a (ancora), vamos chamar a variável seguida do método innerText para alterar o texto entre a tag a (ancora)
```JS
link.innerText = `WebMelo do site Roger`
```
**}**

**manipulando mais tags (p paragraf) {**

=> armazenando p com a class
e error na constante paragraph para poder manipula-lo

```JS
const paragraph = document.querySelector('p')
```

=> Agora através do método getAttribte('className') podemos pegar a classe de um elemento HTML

**setAttribute: (setAttibute) {**

=> Com o método setAttribute é possível referenciar uma tag em uma constante, chamar essa constante acompanhada do método setAttribute e com isso é possível mudar a classe do elemento

```JS
paragraph.setAttribute('class','successs')
```

OBS: Esse tipo de modificação é útil, quando o usuário preenche um formulário, nos mudamos a classe do form para success ou error caso o preenchimento ou envio não tenha sido correto.
   **}**

**(setando valores de um atributo que ainda não existe no elemento){**

setAttribute : (Podemos digitar o nome da classe e ela será atribuída ao elemento já referenciado){
Ex:
```JS
paragraph.setAttribute('style','color: green;')
```

  **}**

**Comment by Roger-Melo** [comment]
Excelente @EneasFeynlinus, rumo à fluência! 🎯
