### ISSUE TITLE
Aplicação: Conversor de moedas

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#3145]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/marcosyoggy/APP_Conversor_de_Moedas

### Maiores dificuldades durante a implementação

   - Como iterar através dos elementos html e concatenar com os valores de conversão obtidos com o request;
   - Tentei refatorar usando um Factory Function mas não consegui;
   - Ainda me 'enrosco' quando tento retornar o conteúdo de uma request, hoje consegui 'na sorte', exemplo: ...Pegar a Promise retornada do request e manipulá-la através de uma função assíncrona, fazendo destructuring, etc...' e assim consegui manipular os valores, demora mas sai.....;
   - No bloco do 'evento', bem no começo, quando ainda estava definindo a lógica do processo, os 'forEach' aninhados de repente 'aconteceram' ali......Eu fiz funcionar, mas não conseguiria explicar como eu fiz isso; No momento eu estava definido que teria que iterar pelo conteúdo dos elementos <option> e concatenar com os valores de conversão obtidos com o 'request';

### Menores dificuldades durante a implementação

- Fazer pesquisa
- Manipular o D.O.M...eu acho.

**Comment by Roger-Melo** [comment]
@marcosyoggy o valor convertido só é exibido após a mudança de valor do `input` type number.

Tem certeza que a aplicação deve ser analisada assim?

![image](https://user-images.githubusercontent.com/29297788/155245956-c9518423-84ce-4587-aae7-5b0edf26c753.png)

**Comment by marcosyoggy** [comment]
Grato pelo feedback.....farei a revisão da aplicação e em breve faço o reenvio.

**Comment by marcosyoggy** [comment]
Cheguei no meu limite..."SEJA O QUE DEUS QUISER...rsrsrs". Obrigado pelo feedback.

**Comment by Roger-Melo** [comment]
Show.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy!

Parabéns pelo esforço em construir a quarta aplicação do treinamento.

> ## Como iterar através dos elementos html e concatenar com os valores de conversão obtidos com o request;

O desafio era fazer quebrar a cabeça e pensar em uma estratégia mesmo. 

Vc usou uma estratégia diferente do que eu mostro nas próximas aulas, pq se baseou em dados estáticos (`<option>`'s no index.html).

Quando possível, prefira trabalhar com dados dinâmicos ao invés de dados estáticos. Nesse caso faz mais sentido popular os `<option>` dos selects com informações da API pq de qualquer forma esses dados vão precisar ser usados na aplicação, então vc não precisa ter o retrabalho de criar a informação estática pra depois substituir ela pela dinâmica.

> ## Tentei refatorar usando um Factory Function mas não consegui;

Não se preocupe com refatoração agora. Há alguns comportamentos no código da aplicação que podem indicar que vc ainda não consolidou alguns conceitos-base. Vou falar sobre isso mais abaixo.

> ## No bloco do 'evento', bem no começo, quando ainda estava definindo a lógica do processo, os 'forEach' aninhados de repente 'aconteceram' ali......Eu fiz funcionar, mas não conseguiria explicar como eu fiz isso; No momento eu estava definido que teria que iterar pelo conteúdo dos elementos e concatenar com os valores de conversão obtidos com o 'request';

Aninhamento de forEach tende a deixar o código mais complexo. E não é necessário nessa aplicação, como vc verá nas aulas seguintes =)

---

## Conceitos-base

Como eu disse antes, há alguns comportamentos no código da aplicação que podem indicar que vc ainda não consolidou alguns conceitos-base (e posso estar errado nessa hipótese).

```javascript
const display_Conversion_Precision = async ref_Coin => {
  // ...
  return show_Conversion.textContent = ` ${USD} ${get_Element_Value(select_One)} = ${BRL.toFixed(2)} ${get_Element_Value(select_Two)}`
}

// ...

display_Conversion_Precision(get_Element_Value(select_One))
```

No código acima, o return está retornando o valor no qual a atribuição resulta.

Só que isso não faz sentido pq em nenhum momento na aplicação vc usa esse valor retornado. Além disso, é incomum ter que retornar o resultado de uma atribuição.

---

## Interpretação textual

Além disso, eu sinto que houve dificuldade em interpretar o que foi pedido no enunciado do exercício.

O enunciado especifica que o parágrafo menor [deveria exibir a conversão exata](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-38/app.js#L209) (com vários decimais) e só o parágrafo em destaque (com `data-js="converted-value"`), [a conversão arredondada](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-38/app.js#L215), com apenas 2 decimais no máximo.

---

## Abreviações

Não abrevie a ponto de deixar o nome da variável ilegível para quem lê o código. 

É complicado ler `sel_Element`, `refCoin` e `s01` por exemplo e entender o que isso significa. 

---

## Nomes de funções

`conversions_Values` não deve ser nome de função. 

Função deve ser nomeada como verbo. 

Esse tipo de erro foi falado mais de uma vez em [análises passadas](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=is%3Aissue+author%3Amarcosyoggy+is%3Aclosed+label%3A%F0%9F%94%A5aplica%C3%A7%C3%A3o). 

Isso significa que vc está repetindo os mesmos erros.

---

## Conclusão

Peça mais ajuda quando tiver dúvidas, faça mais perguntas, abra mais issues.

Por exemplo... 

> ## Ainda me 'enrosco' quando tento retornar o conteúdo de uma request, hoje consegui 'na sorte', exemplo: ...Pegar a Promise retornada do request e manipulá-la através de uma função assíncrona, fazendo destructuring, etc...' e assim consegui manipular os valores, demora mas sai.....;

Vc listou essa dificuldade com requests, que é um assunto introduzido na etapa 11. 

Se vc está com dificuldades nesse assunto, não espere chegar na etapa 15 para pedir ajuda. Peça ajuda o quanto antes. 

Se vc não resolver suas dúvidas o quanto antes, elas viram uma bola de neve a medida em que vc avança no treinamento.

Direção é mais importante que velocidade. 

O problema não é demorar, o problema é não aprender. 

Obviamente vc evoluiu desde que entrou no CJRM. Porém, pelo que analiso em seu código, sinto que vc tem potencial para melhorar sua performance e resultados no caminho rumo à fluência.

Se houver algo que eu possa fazer para ajudar, é só dar o toque que ajudo =)

**Comment by marcosyoggy** [comment]
Grato pelo feddback.
