### ISSUE TITLE
Resumo da aula da Uma introdução ao Bootstrap - aula 01-02 da etapa 07

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#3146]
UMA INTRODUÇÃO AO BOOTSTRAP

O que é Bootstrap?
R: É uma biblioteca de componentes front-end, são elementos e partes da interface do usuário que podem ser reutilizadas, como classes CSS e JavaScript.

Por que usar Bootstrap?
R: Porque ele usa classes CSS próprias para aplicar o design na nossa página web. Assim sendo, podemos tirar o foco do CSS da página e focar mais no JS.

Como usar o Bootstrap?
R: Podemos usar através da Content Delivery Network (CDN) no site oficial.

**Comment by Roger-Melo** [comment]
Boa @rafaelpradoj, rumo à fluência! 🔥
