### ISSUE TITLE
Resumo da Aula 02-05 Obtendo, adicionando, removendo e alternando classes CSS da etapa 05

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3147]
{Obtendo, adicionando, removendo e alternando classes CSS}

**Mudando classes utilizando JS(javaScript) {**
-> Através do método add() do class list nos vamos adicionar um nova classe a tag armazenada na variável paragraph.
```JS
paragraph.classList.add('error')
```
**}**

**Recebendo uma DOM list através da propriedade (classList) {**
-> Neste exemplo estamos armazenando a tag P paragraph na variável paragraph e logo abaixo estamos mostrando na console o classLista da paragraph.
classList () => Gera uma DOMlist que seria um array com todas as classes da tag armazenada em paragraph.

```JS
const paragraph =  document.querySelector('p')
console.log(paragraph.classList)
```
**}**

**Removendo a classe de um elemento () {**
-> Através do método remove da propriedade classList que nos retorna um DOMtokenlist, podemos remover uma classe que esteja na tag HTML

```JS
paragraph.classList.remove('error')
```
**}**

**formas de obter o texto de um elemento HTML (innerText,textContent) {**

Ex-> No exemplo abaixo, estamos pegando a variável paragraphs que recebe um nodelist através do querySelectorAll referente a todos os elementos P do documento HTML. Logo após com a variável paragraphs armazenando o nodelist, utilizamos o método forEach em nossa variável e no forEach ele vai receber cada elemento trago pelo querySelectorAll e mostrar o texto através do innerText ou o textContent. Ambos entregam os textos no elemento.

Modo (1) A propriedade innerText obtem o texto visível apenas, caso tenha algum texto oculto nao será exibido nem na console.

```JS
const paragraphs = document.querySelectorAll('p')

paragraphs.forEach((paragraph)=>{
    console.log(paragraph.innerText)
})
```
---------------------------------------------------------------
Modo (2) Já a textContent vai mostrar todo o texto que o elemento contem, independente se o texto esta oculto ou não.

```JS
const paragraphs = document.querySelectorAll('p')

paragraphs.forEach((paragraph)=>{
    console.log(paragraph.textContent)
})

```
**}**

**Implementando uma mudança de classe caso um paragrafo contenha error () {**

=> Neste exemplo estamos pegando a variável paragraphs colocando o método for each com uma função callback qeu recebe os parágrafos tragos pelo querySelectorAll em uma nodelist, e através da propriedade textContent utilizando o método de array includes() para checar se a palavra referida existe nos textos tragos dos elementos. Toda tag P que tiver a palavra error, terá sua classe adicionada a classe error e vai pegar as qualidades dessa classe referida no documento CSS. E caso a primeira condição de ter error não seja verdadeira, temos uma outra condição semelhante, no entanto, dessa vez buscando com o includes a palavra success e adicionando a classe success com o método add da propriedade classList.

```JS
const paragraphs = document.querySelectorAll('p')

  if (paragraph.textContent.includes('error')) {
        paragraph.classList.add('error')
    }

    if (paragraph.textContent.includes('success')) {
        paragraph.classList.add('success')
    }
})
```
**}**

**Alternando uma classse em um elemento () {**

=> Neste exemplo estamos referenciando na variável title o elemento h1 do documento HTML e logo após vamos usar o método da classList chamado toggle. Agora nos pegamos nossa variável aplicamos a propriedade classList e utilizamos o método toggle como argumento 'test' que seria a nova classe. Caso não tenhamos essa classe no elemento essa classe será adicionada no elemento sem remover a classe que ja esta definida. E no entando caso passarmos uma classe que já existe como argumento to toggle, essa classe será removida.

```JS
const title = document.querySelector('h1')

title.classList.toggle('test') // Aqui adiciona a classe text a title que referencia h1
title.classList.toggle('test') // Com uma nova invocação de toggle a classe é removida
```
**}**

**Comment by Roger-Melo** [comment]
Boa @EneasFeynlinus, rumo à fluência! 🔥
