### ISSUE TITLE
Aplicação Quiz I App

### ISSUE THREAD

**Issue by wsn-nunes** [roger-melo-treinamentos/curso-de-js-roger-melo#315]
**Link da Aplicação :** 
https://github.com/wsn-nunes/CJRM

**MINHAS MAIORES DIFICULDADES:** 

- Interagir com as classes dos elementos.

- Refatorar o código, deixando-o menor e mais legível, nem sempre fica menor (rsrsrs)
No exercício não cheguei a refatorar.

- E talvez uma das maiores dificuldades é saber em que local da aplicação criar a variável.
Exemplo - ao criar um elemento via javascript.

**MINHAS MENORES DIFICULDADES:** 

- Criação dos eventos.
- Iteração com os elementos no forEach.
- Criar um elemento.

Consequentemente , aprendi muito até aqui , obrigado pela didática e por toda atenção nas aulas .

rumo à fluência. EU QUERO , EU POSSO , EU CONSIGO ...

**Comment by Roger-Melo** [comment]
Oi William.

Passando para dizer que sua issue foi visualizada e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Oi William.

Antes de tudo, parabéns pelo esforço em construir sua primeira aplicação no CJRM =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar a aplicação.

## Lógica

### Armazenamento das respostas

No código abaixo, perceba que a `const questions` não armazena as perguntas, mas sim **as respostas das perguntas**:

```javascript
const Questions = [
  form.inputQuestion1.value,
  form.inputQuestion2.value,
  form.inputQuestion3.value,
  form.inputQuestion4.value
]
```

Sendo assim, é mais adequado nomear essa const como `answers`.

### Manipulação de DOM e `else` (desnecessários) dentro do callback do `forEach`

O `else` e a manipulação de DOM dentro do callback do `forEach` são desnecessários.

Você pode deixar a manipulação de DOM fora do `forEach`, após ele terminar de ser executado (como foi mostrado [nessa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/943417) e [nessa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/963054) aula), pois não é necessário inserir o `h5` na tela a cada execução da função. Só é necessário inserir o resultado na tela **após** o cálculo, e não **durante**. Ao fazer isso, o uso do else também é eliminado.

## Usabilidade

### Local da exibição dos pontos

O print abaixo foi tirado logo após o envio do form:

![print-form-submit](https://user-images.githubusercontent.com/29297788/112741231-1fe71a80-8f5a-11eb-9f04-2209baf1885e.jpg)

Quando o form é enviado, os pontos são exibidos na parte inferior da tela (parte não visível). Se não houver algo que faça o usuário intuir que os pontos estão abaixo, o mais provável é que ele pense que nada aconteceu depois de clicar no botão. Uma alternativa seria exibir os pontos próximo do local para onde ele está olhando quando envia o form (botão). 

Nas aulas seguintes eu mostro uma forma de inserir os pontos na tela, mas fique atento à isso. Ao inserir um elemento na tela, certifique-se de que o usuário irá vê-lo.

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no `input` type radio a ser exibido por padrão como "marcado".

Isso é mais uma preferência pessoal mas acredito que incentiva mais o usuário a marcar a resposta que ele acredita que seja a verdadeira.

## Organização de código

### `console.log` esquecido

Lembre-se de eliminar invocações de `console.log` ao subir uma aplicação para produção ou enviar para alguém usá-la. Exibir informações no console é útil apenas para programadores. O usuário, na grande maioria das vezes, não abrirá o console do devtools.

### Inconsistência nos espaços em branco

Observe as duas aberturas de blocos abaixo:

```javascript
form.addEventListener("submit",event => {
  // ...
}

correctQuestions.forEach((correctQuestion, index) => {
  // ...
}
```

Houve uma inconsistência no uso do espaço em branco após a vírgula. Não há problema em escolher inserir um espaço após a vírgula ou não inserir, mas escolha um e seja consistente no decorrer do código.

O mesmo vale para os espaços em branco que antecedem a abertura de blocos:

```javascript
// espaço em branco inserido antes da abertura do bloco
correctQuestions.forEach((correctQuestion, index) => {
  // ...
}

// espaço em branco ausente antes das aberturas dos blocos
if(correctQuestion === Questions[index]){
  // ...
} else{
  // ...
}
```

### Nomes de variáveis e funções

A declaração da `Questions` tem outra inconsistência: falta de camelCase. Em todo o código, as variáveis estão declaradas em camelCase. Novamente, não há problema em escolher uma convenção de nomenclatura diferente (embora eu não recomende), mas essa escolha precisa se mostrar consistente ao longo do código.

Como `correctQuestions` é um array que armazena as respostas corretas, o mais adequado seria nomear essa const como `correctAnswers`.

`element` é um nome pouco descritivo para uma const. Não há como bater o olho no nome e entender rápido o que ela armazena. Prefira descrever qual elemento a const está armazenando. Como essa const contém a pontuação final, eu a nomearia como `scoreContainer`, `finalScoreContainer` ou trocaria o `Container` por `El` (que é uma abreviação de "element").

### Linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo esse princípio eu removeria as linhas em branco 6, 19, 21, 29, 33 e 36. É uma convenção que a primeira e a última linha de um bloco de código esteja preenchida. Isso deixa a leitura mais fluida, sem saltos desnecessários entre linhas.

Fez sentido os pontos que mencionei?

---

Sobre as maiores dificuldades que você listou, eu sugiro que não se preocupe com refatoração agora. Refatoração vem depois. Prefira priorizar melhorar os pontos que citei no critério `Lógica` (primeiro critério lá em cima).

E só uma observação sobre refatoração: existem formas e formas de se refatorar. Diminuir as linhas do código não é o mais importante em uma refatoração (não na minha filosofia). Mas isso você vai perceber ao longo do treinamento.

> E talvez uma das maiores dificuldades é saber em que local da aplicação criar a variável.
Exemplo - ao criar um elemento via javascript.

Se essa variável não precisar ser global (ser usada em duas funções diferentes, por exemplo), você pode declará-la próxima de onde ela será usada.

> - Interagir com as classes dos elementos.

Preciso de mais informações para entender. Pode dar um exemplo? 

@wsn-nunes

**Comment by wsn-nunes** [comment]
Boa noite, professor .

Muito obrigado pelo feedBack.

na parte do forEach( ), vamos ver se eu entendi .

quando iterar o array, eu não preciso manipulador o dom , quando o forEach() terminar o array já vai ter sido alterado e a partir daí eu faço as manipulações com as condições que for declarada por mim ... 

na parte em que eu falo sobre interagir com as classes dos elementos. digo em relação a criação dos estilos da pagina html, e a manipulação das classes no html , com o classList.add(), o style: , o setAttribute("class","bg-warning");


mas muito obrigado pelo conteúdo até aqui. como foi rico .

**Comment by Roger-Melo** [comment]
Oi @wsn-nunes.

Essa dúvida da última issue é a mesma da outra issue que vc abriu, certo? Respondi na outra issue, então vou fechar essa =)
