### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by developsouza** [roger-melo-treinamentos/curso-de-js-roger-melo#3152]
Aprendi sobre o uso do null e undefined e suas primeiras aplicações, quando queremos referenciar alguma variával que iremos utilizar posteriormente sem precisar atribuir um valor utilizamos o null, e o undefined é quando "esquecemos" de atribuir algum valor a alguma variável ou constante.

**Comment by Roger-Melo** [comment]
Boa @developsouza, rumo à fluência! 🔥
