### ISSUE TITLE
Resumo da Aula 01 da etapa 08

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#3153]
### Map:

O método map é usado quando queremos gerar um novo array com a mesma quantidade de elementos do array original, mas aplicando alguma transformação em cada elemento dele. Essa transformação é aplicada através de uma função passada como argumento ao map e será executada para cada elemento do array original.

O mpa é invocado encadeando com o array original e a função que fará a transformação pode receber três parâmetros:

item: é o item que está sendo iterado (obrigatório)
index: é a posição do item iterado no array original
array: é o próprio array original.
A função será executada para cada item do array e o valor retornado por ela será adicionado ao novo array que a função map irá retornar.

### Filter:

O método filter funciona de maneira similar ao map, ele recebe uma função como argumento e essa função será executada para cada item do array. Mas ele serve para obter um novo array apenas com alguns elementos do array original.

Assim como no map, a função recebida como argumento pode receber três parâmetros:

item: é o item que está sendo iterado (obrigatório)
index: é a posição do item iterado no array original
array: é o próprio array original.
O filter criará um novo array com os elementos do array que atenderem a uma condição especificada pela função recebida, por isso essa função deve sempre retornar um valor booleano: Sempre que ela retornar 'true' o item da iteração será adicionado ao novo array, sempre que retornar 'false' o item será ignorado. Se a função retornar 'false' em todas as iterações, o filter retornará um array vazio .

### Reduce:
O reduce também recebe uma função ppor argumento para ser executada para cada elemento do array, no entanto, ela serve para quando queremos reduzir o array original em algum outro tipo de dado, não necessariamente outro array.

O reduce recebe dois argumentos:

A função que será executada para cada item do array
Um valor inicial que será utilizada pela função na primeira iteração do reduce.
A função pode receber quatro argumentos:

accumulator: um acumulador que guardará o valor retornado pela função a cada iteração, para que possa ser usado na próxima.
item: é o item que está sendo iterado
index: é a posição do item iterado no array original
array: é o próprio array original.
Accumulator e item são argumentos obrigatórios.

A função precisa retornar um valor a cada execução pois esse valor será implicitamente atribuído ao acumulador para a próxima iteração.

Apesar de não ser obrigatório uma boa prática atribuir um valor inicial, para ter uma representação do tipo de dado que o reduce irá retornar. Esse valor será recebido pelo accumulator na primeira iteração do reduce. Caso esse valor não seja especificado, o accumulator irá receber o primeiro elemento do array como valor inicial e item começará com o segundo elemento.

### Exemplos
Vamos imaginar que a gente precisa obter desse array só os livros acima de 20 reais e a partir disso vamos gerar para todos os livros string informando o nome e o preço do livro em promoção.
Para fazer isso iremos utilizar primeiro o filter(), pois assim iremos obter só os livros acima de 20 reais. Como precisamos gerar também para todos os livros uma string informando o nome e o preço do livro em promoção, vamos utilizar o map().

```js
const books = [
  { name: 'Código Limpo', price: 30 },
  { name: 'O milagre da manhã', price: 5 },
  { name: 'Alice no País das Maravilhas', price: 10 },
  { name: 'Quem Pensa Enriquece', price: 50 },
  { name: 'O livro da ciência', price: 40 }
]

const booksOnSale = books
  .filter(({ price }) => price > 20)
  .map(({ name, price }) =>
    `O preço do livro "${name}" caiu para ${price} reais`)

console.log(booksOnSale)
// ['O preço do livro "Código Limpo" caiu para 30 reais', 
    'O preço do livro "Quem Pensa Enriquece" caiu para 50 reais',
    'O preço do livro "O livro da ciência" caiu para 40 reais']


Agora vamos receber um array com objetos com nome e preço, e iremos modificar apenas os preços que forem acima de 30, dando um desconto de 50%.

const products = [
  { name: 'Mouse Sem Fio', price: 30 },
  { name: 'Pen Drive', price: 25 },
  { name: 'Cartucho de Tinta', price: 50 },
  { name: 'Suporte Ergonômico para Notebook', price: 23 },
  { name: 'Repetidor de Sinal Wi-Fi', price: 44 }
]

const saleProducts = products.map( product => {
  if (product.price >= 30) {
    return { name: product.name, price: product.price / 2 }
  }

  return product
})


O encadeamento de métodos é um recurso muito prático para manipulação de dados em um array. Se tivermos, por exemplo, uma lista de diversos produtos com diversas marcas e preços e precisarmos alterar temporariamente alguns deles, podemos gerar uma nova lista com as informações alteradas, de “uma vez só”.

Assim, ao invés de primeiro filtrarmos o array original com filter() para obtermos a informação desejada e depois aplicarmos o map() para transformar o novo array gerado pelo método anterior, podemos encadear estes dois métodos, eliminando a necessidade de duas variáveis para armazenar cada novo array gerado.
Exemplo:

// sem encadeamento (dois arrays gerados e armazenados separadamente)
const arrayFiltrado = arrayOriginal.filter(funçãoCondicional)
const arrayFiltradoeModificado = arrayFiltrado.map(funçãoParaModificação)

// encadeando (armazenando um único array)
const arrayFiltradoEModificado = arrayOriginal
    .filter(funçãoCondicional)
    .map(funçãoParaModificação)
Onde:

arrayOriginal é o array tomado como base
arrayFiltrado é a constante que recebeu o novo array gerado pelo método filter() com base no arrayOriginal
arrayFiltradoEModificado é a constante que recebeu o novo array gerado após uso do filter() e map()
funcãoCondicional é a função que deve conter a condição a ser verificada no método filter()
funçãoParaModificação é a função que deve conter a expressão para inserir as modificações desejadas no novo array, por meio do método map()
Por convenção, cada método é deixado em uma nova linha, indentando os conteúdos, para melhor visualização do que está sendo feito no array.


```

MÉTODO MAP
array.map(item => {}): cria um novo array iterando os itens do array original e retornando um novo array, portanto, o método map precisa SEMPRE retornar um valor.

MÉTODO FILTER
array.filter(item => {}): semelhante ao método map, porém o retorno agora é somente true ou false. Se true (obedecendo à condição da função de callback), adiciona o item no novo array, se false, ignora.

METÓDO REDUCE
array.reduce((accumulator,item) => {}, 0): reduz um array inteiro em outro tipo de dado, utiliza o acumulador como ponto de partida e de soma/qualquer outra alteração. O número 0 no final é a indicação explícita de qual número o accumulator vai iniciar, de outra forma, ele recebe o primeiro item do array.

**Comment by Roger-Melo** [comment]
Boa @ghostnetrn, rumo à fluência! 🔥
