### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3159]
====== A PALAVRA-CHAVE THIS =========================

Estando dentro do objeto, para acessar uma propriedade deste mesmo objeto devemos inserir a palavra-chave this seguido da propriedade para podermos acessar o seu valor.

O this irá referenciar o objeto, mas não pense que o this é o mesmo que colocar o nome do objeto. Mesmo funcionando desta maneira o this na verdade é um objeto de contexto, ou seja, ele representa o contexto no qual o código atual está sendo executado. Dependendo de onde ou como se usa o this, o valor dele irá mudar.

Se utilizarmos o this na raiz do documento, ele irá referenciar o contexto global, ou seja, o windows object (Objeto window).

Quando invocamos um método, o javascript define o this como o objeto no qual o método está sendo usado. Por exemplo:

```.js
user.logBlogPost()
```

Nesse momento o javascript pegou o this, definiu ele como objeto user e está disponibilizando dentro do bloco essa referência para ser acessada. Apenas dentro do bloco do objeto user o this irá representar o user. Ou seja, dependerá do contexto, em outro objeto ele será diferente.

Como estamos referenciando o objeto através do this, é possível acessar suas propriedades normalmente com notação de ponto ou colchetes.

```.js
let user = {
   name: 'João',
   age: 31,
   email: 'joaocardoso@gmail.com',
   city: 'São Paulo',
   blogPosts: ['Empadão de Frango', '4 receitas de purê de batata'],
   login () {
      console.log('Usuário logado.')
   },
   logout () {
      console.log('Usuário deslogado.')
   },
   logBlogPosts () {
      console.log(`${this.name} escreveu os seguintes posts:`)

      this.blogPosts.forEach(post => {
         console.log(post)
      })
   }
}
```

```.js
// dentro do objeto user, o this está referenciando o próprio objeto user.

user.logBlogPosts()
```
Atenção:

Ao declarar um método que estará usando o this, atente-se ao uso das function declarations, pois apenas com elas o this se comprota desta maneira. Ou seja, referenciando o objeto do contexto.

Se utilizarmos arrow functions, o this irá referenciar o objeto referente ao local onde o método está sendo invocado. Ou seja, se invocarmos o método no escopo global, onde o javascript define o contexto do this, o this irá referenciar o objeto window, pois a invocação se encontra na raiz. Ele não irá visualizar o objeto literal desejado.

Utilize function declartions ao usar this

ENCURTANDO UM MÉTODO DENTRO DO OBJETO:

Podemos escrever a função do objeto com uma sintaxe mais curta, pois o javascript também entenderá que a função é uma function declaration, procure utilizar o shorcut por boas práticas. Exemplo:

```.js
let user = {
   // forma completa
   login: function () {
      console.log('Usuário logado.')
   }

   // forma mais curta (shortcut)
   login () {
      console.log('Usuário logado.')
   }
}
```

**Comment by Roger-Melo** [comment]
Boa @santos2408, rumo à fluência! 🔥
