### ISSUE TITLE
Método trim()

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#3161]
### Etapa da aula

9

### Nome da aula

Adicionando to-dos - Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1047938

### Descreva a dúvida

O que está impedindo o método trim de remover os espaços antes e depois dos caracteres?

![image](https://user-images.githubusercontent.com/70287096/155157485-1958bf8e-0b70-4370-850c-a5b4eba415ae.png)

@Roger-Melo

**Comment by dracoalv** [comment]
Perdão @Roger-Melo, eu acabei esquecendo e dei continuidade no código através de outras soluções com base no que aprendi, o repositório, segue o repositório: https://github.com/dracoalv/Todo-List

Não entendi o motivo do método trim não ter funcionado, então apliquei uma regex para verificar se existia mais do que um espaço entre os caracteres, o problema que isso gerou foi que ao inserir uma Todo com vários espaços, o Todo era adicionado com apenas um espaço, porém quando eu filtrava este Todo, ele continha os espaços a mais inseridos no input de adicionar Todos, também passei por cima deste problema, porém deu um trabalhinho a mais rs

**Comment by Roger-Melo** [comment]
@dracoalv o `trim` remove espaços em branco do início ou do final da string. Vc pode ver isso [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim).

A forma mais eficiente de lidar com essa manipulação de strings nesse caso é usando regex, como vc já fez =)

**Comment by dracoalv** [comment]
Eu não estava entendendo por que no meu código o trim não estava funcionado kkk, mas aí fiz com o regex, no caso se deixar com o método trim, na hora de fazer a busca pelo todo, se no input do Todo for inserido vários espaços, para filtrar seria necessário todos os espaços usados?

Esta é a última dúvida, agradeço desde já! ✨

**Comment by Roger-Melo** [comment]
Exatamente =)

O exemplo abaixo usa os mesmos métodos da aplicação. Execute e olhe os resultados:

```javascript
const withThreeSpaces = 'a   b'

console.log(withThreeSpaces.trim().toLowerCase().includes('a b')) // false
console.log(withThreeSpaces.trim().toLowerCase().includes('a   b')) // true
```

No primeiro console.log, false foi retornado pq há apenas 1 espaço em branco entre os caracteres e a string original tem 3.

Já no segundo console.log, como a string tem exatamente os mesmos caracteres da string original, true é retornado.

Então sim, no momento da filtragem, o conteúdo das duas strings precisa ser o mesmo =)

@dracoalv

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
