### ISSUE TITLE
problemas com o refactoring do todo-list

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#3162]
### Etapa da aula

9

### Nome da aula

Exercícios da aula 02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1073160

### Descreva a dúvida

**ainda não assisti a revisão da aula**

durante o refactoring eu pensei em fazer o mesmo que na atividade 18 em que trabalhamos com o envio de form, sendo uma atividade para validar nomes de usuário, no refactoring dessa atividade usamos duas funções que seus valores eram organizados em objetos a parte.

**link da atividade realizada por mim, a parte do codigo referida acima se encontra entre as linhas 20 e 60**
https://github.com/CarlosHenrique2208/atividade18_valida-oDeUsername

**eu utilizei dessa mesma base para fazer as funções que irão adicionar as classes '_.hidden_' e '_.d-flex_' nas**
```html
<li></li>
```

**const usadas**
```js
const formAddTodo = document.querySelector('.form-add-todo')
const todosContainer = document.querySelector('.todos-container')
const inputSearchTodo = document.querySelector('.form-search input')

const targElement = element => element.target
```

**funções e objetos para esconder e mostrar as lis**

```js
//PROCURA POR UM ITEM DA LISTA
//FUNÇÕES
const hiddenItemGroupList = (object, classElement) => {
  const { todosChildren, todosText } = object
  Array.from(todosChildren)
      .filter(todo => !todosText(todo, classElement))
      .forEach(todo => {
          todo.classList.remove('d-flex')
          todo.classList.add('hidden')
  })
}
const revealItemGroupList = (object, classElement) => {
  const { todosChildren, todosText } = object
  Array.from(todosChildren)
      .filter(todo => todosText(todo, classElement))
      .forEach(todo => {
          todo.classList.remove('hidden')
          todo.classList.add('d-flex')
  })
}

//OBJETOS
const hiddenInformations = {
  todosChildren: todosContainer.children, 
  todosText: (todo, classElement) => {todo.textContent
    .toLowerCase()
    .includes(classElement)}
}
const revealInformations = {
  todosChildren: todosContainer.children, 
  todosText: (todo, classElement) => {todo.textContent
    .toLowerCase()
    .includes(classElement)}
}
```

**eventListener**

````js
inputSearchTodo.addEventListener('input', event => {
    const inputValue = targElement(event).value.trim().toLowerCase()

    hiddenItemGroupList(hiddenInformations, inputValue)
    // revealItemGroupList(revealInformations, inputValue)
    
    Array.from(todosContainer.children)
        .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
        .forEach(todo => {
            todo.classList.remove('hidden')
            todo.classList.add('d-flex')
    })
})
```

**OBS: somente a 'hiddenItemGroupList' funciona**

<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208!

Preciso de mais clareza para te ajudar =)

Não ficou muito clara a dúvida que vc tem e ao mesmo tempo, vc postou pedaços de código sobre algo e o link do repositório não tem os pedaços de código que vc comentou (pelo pouco que vi aqui), então eu teria que modificar o código aos poucos e ir testando até descobrir o que vc quis dizer.

Peço que poste aqui abaixo uma descrição mais clara do problema, a dúvida, o que vc quer fazer e o código completo, testável e condizente com o problema que vc quer resolver, para que eu possa baixar aqui e testar. Assim eu consigo te ajudar com mais precisão. 

Se comunicar de forma clara ao pedir ajuda é um desafio que vc terá em qualquer equipe. Vá se acostumando =)

**Comment by CarlosHenrique2208** [comment]
eu queria entender qual o problema da função **revealItemGroupList** pois ela não funciona, ela deveria remover a classe "hidden" e adicionar a classe "d-flex" quando a pesquisa pelo todo acontecer.

```js
inputSearchTodo.addEventListener('input', event => {
    const inputValue = targElement(event).value.trim().toLowerCase()
    
    //funciona
    hiddenItemGroupList(hiddenInformations, inputValue)
    
    //não funciona
    revealItemGroupList(revealInformations, inputValue)
})
```

eu coloquei somente partes do codigo pois as demais funções do todo-list não interferem nessa e não tiveram problemas quanto ao refactoring, então pensei que seria mais rápido e eficiente só colocar pedaços do codigo.

aqui o link do repositório com todos os arquivos usados na atividade 24
https://github.com/CarlosHenrique2208/atividade24

**Comment by Roger-Melo** [comment]
@CarlosHenrique2208 agora ficou mais fácil entender o que vc quiz dizer =)

`revealItemGroupList` não está funcionando por um motivo simples. 

Não vou dar a resposta pronta pq quero que vc descubra por conta própria. Se isso acontecer, as chances são de que vc não errará mais isso. Vou apenas te direcionar.

Exibe no console o valor que a invocação `todosText(todo, classElement)` está retornando.

```javascript
const revealItemGroupList = (object, classElement) => {
  const { todosChildren, todosText } = object
  Array.from(todosChildren)
    .filter(todo => todosText(todo, classElement)) // 👈🏻 aqui
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
}
```

Esse era o valor que vc esperava?

Pq a invocação dessa função está retornando esse valor? 🤔

Testa e responde aqui em baixo =)

---

Depois que resolver isso, quero te falar uma outra coisa, mas resolve essa parada primeiro. Uma coisa de cada vez =)

**Comment by CarlosHenrique2208** [comment]
uma mensagem de error aparece dizendo que não consegue ler o "indefinido", ou seja, a função ```todosText``` não possui valor, mas não sei como resolver ou mesmo se era pra resolver algo, pois é uma função de callback que, ao menos deveria, retornar uma string com o conteúdo do todo, o filter retornaria false ou true e dependendo do boolean, as classes ```"hidden"``` e ```"d-flex"``` seriam adicionadas e removidas

![image](https://user-images.githubusercontent.com/85198581/155525788-97caeb91-1602-4d28-b298-ccd3b8871084.png)


depois de 20-25min batendo a cabeça vi que o problema mesmo é que eu tenho uma função que só não retorna nada e dá esse erro, porém sei que ela deveria ter o conteúdo do ```todo```, só não sei como fazer isso. 

pensando um pouco sobre, acredito que tenho todas as informações que preciso, mas a forma como organizei tá criando um problema no **call-back** 

enfim, mais um problema que fico dando voltas e voltas em círculos kkk

**Comment by Roger-Melo** [comment]
@CarlosHenrique2208 o problema é que a invocação da função `todosText(todo, classElement)` não está retornando valor, e toda função que não retorna um valor, retorna undefined por baixo dos panos.

```javascript
const revealItemGroupList = (object, classElement) => {
  const { todosChildren, todosText } = object
  
  Array.from(todosChildren)
    .filter(todo => {
      console.log(todosText(todo, classElement)) // 👈🏻 retorna undefined
      return todosText(todo, classElement)
    })
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
}
```

Isso significa que o filter está retornando undefined toda vez que é executado. `undefined` é um valor falsy. Ou seja, nenhum to-do vai ser inserido no novo array que o filter está criando.

E se o filter retorna um array vazio, o forEach não é executado, pq o array não tem itens.

Agora observa a declaração da `todosText`:

```javascript
const revealInformations = {
  todosChildren: todosContainer.children,
  todosText: (todo, classElement) => {
    todo.textContent
    .toLowerCase()
    .includes(classElement)
  }
}
```

Ela não contém um return. 

Não faz sentido elaborar uma expressão que resulta em um valor e esse valor ficar "preso" dentro da função. 

Vc precisa retornar o boolean no qual a expressão que checa se o to-do existe resulta:

```javascript
const revealInformations = {
  todosChildren: todosContainer.children,
  todosText: (todo, classElement) => {
    return todo.textContent.toLowerCase().includes(classElement)
  }
}
```

Testa e me diz se ficou mais claro =)

**Comment by CarlosHenrique2208** [comment]
olá professor, perdão a demora para responder.

testei a função utilizando o return, entendi qual o problema da minha aplicação e muito obrigado pelo suporte.
estava tão acostumado a usar os "shorthands" que as arrow functions proporcionam que não notei uma notação básica ao se colocar consts dentro de um bloco de codigo.

Ficou sim mais claro, vou me me vistoriar a ter mais cuidado quando for utilizar funções. Obrigado, mais uma vez =)
