### ISSUE TITLE
Aplicação: Quiz interativo

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#3163]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/rafaelpradoj/quiz-interativo

### Maiores dificuldades durante a implementação

Minha maior dificuldade foi com o Bootstrap em si, por ter muitas divs espalhadas pelo projeto.

Senti falta da nova semântica HTML5 com as tags header, main, nav etc... Mas como o objetivo era o resultado final, não me preocupei de mexer com isso no momento, talvez mais pra frente.

### Menores dificuldades durante a implementação

A criação do JS foi bem tranquila e as classes CSS do Bootstrap também são fáceis de entender vendo a documentação. 

Utilizei uma biblioteca JS chamada "Sweet Alert", ela tem o intuito de deixar o alert do JS mais elegante e com algumas funcionalidades a mais. 

Utilizei essa biblioteca com o intuito de quando o usuário clicar em enviar, um alert aparece com o resultado do quiz, acompanhado de uma mensagem amigável.

**Comment by Roger-Melo** [comment]
Olá @rafaelpradoj.

Parabéns pelo tema do Quiz, acertou na nostalgia 🎯

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
Olá, @rafaelpradoj.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Minha maior dificuldade foi com o Bootstrap em si, por ter muitas divs espalhadas pelo projeto.

O uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

No geral, você escolheu nomes descritivos para suas variáveis e funções.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Uso de ferramenta (lib) que não foi apresentada no treinamento

No trecho de código abaixo, você importou a biblioteca JS Sweet Alert.

```HTML
<!--Sweet Alert Library-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
```

Em nenhum momento do treinamento foi pedido para usar algo que não fosse JS puro na aplicação. Os critérios para análise do quiz devem ser seguidos, libs são ferramentas adicionais, e essas ferramentas não devem ser adicionadas agora. Foi pedido no [enunciado do exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js#L12)
e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação seja feita apenas com o que você viu nas aulas até aqui.

Com o que você viu até aqui, o que foi feito usando lib poderia ter sido feito com JS puro.

A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, o que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

---

## Indentação com quatro espaços ao invés de dois

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

- [Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Comentários no código

Não é uma regra, mas evite comentários.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código. Sabendo disso, você pode evitar de deixar linhas em branco no início e final do código. Por exemplo, você pode remover do início do código, as linhas 2 e 4 que estão em branco.

A primeira linha do callback do envio do envio do form também está em branco. Por convenção, prefira que a primeira e última linha de um bloco sejam linhas preenchidas com código. 

```js
//antes
form.addEventListener('submit', event => {

  event.preventDefault()
  // ...
})
```

```js
//depois
form.addEventListener('submit', event => {
  event.preventDefault()
  // ...
})
```

Há também uma linha em branco no if do forEach.

```js
//antes
if (isCorrectAnswer) {

  score += 25
}
```

```js
//depois
if (isCorrectAnswer) {
  score += 25
}
```

Na função usada para encontrar respostas corretas do quiz, há uma linha em branco abaixo da declaração da const `findCorrectAnswers`.

```js
//antes
const findCorrectAnswers = (answer, index) => {

  const isCorrectAnswer = answer === correctAnswers[index]
  // ...
}
```

```js
//depois
const findCorrectAnswers = (answer, index) => {
  const isCorrectAnswer = answer === correctAnswers[index]
  // ...
}
```

---

Mais uma vez, parabéns pelo esforço.

As observações fizeram sentido?

**Comment by rafaelpradoj** [comment]
Bom dia Maykell, tudo bem?

Realmente as explicações fizeram sentido e parando pra analisar, eu conseguiria fazer o alert já usando o evento submit, acabei pensando rápido demais.

E quanto as boas práticas eu nunca parei para ler, agradeço ter compartilhado. Essa coisa de espaços entre cada nome eu havia pego em outro curso e foi se tornando um hábito, sem nem ao menos saber se estava certo.

Obrigado pelo incentivo!!!

**Comment by MivlaM** [comment]
Show! No que precisar, é só abrir uma nova issue =)
