### ISSUE TITLE
Por que faz requisição infinitamente?

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#3166]
### Etapa da aula

11

### Nome da aula

Exercícios da Aula 03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1262485

### Descreva a dúvida

Bom dia, professor,

Fazendo o exercício 1 eu tinha começado bem simples e quando eu criei a função getRequest() eu esqueci de mover a const request para dentro dela, ficou dessa forma:

```js
const request = new XMLHttpRequest() 

const getRequest = (url, callback) => {
  request.addEventListener('readystatechange', () => {
    if(request.readyState === 4 && request.status === 200) {
      const data = JSON.parse(request.responseText)
      callback(`O nome do Pokemon obtido é: ${data.name}`)
      return    } 
  })
  request.open('GET', url)
  request.send()
}

getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', ( data) => {
  console.log(data)
  getRequest('https://pokeapi.co/api/v2/pokemon/charmander/', ( data) => {
    console.log( data)
    getRequest('https://pokeapi.co/api/v2/pokemon/squirtle/', ( data) => {
      console.log( data)
    })
  })
})
```
Quando eu invoquei a primeira getRequest foi de boa, no console apareceu os dados do Bulbasaur.
#### sem request infinito:
```js 
getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', ( data) => {
  console.log(data)
})
```
 Quando invoquei a segunda e a terceira  começou um número infinito de requisições, a primeira requisição, Bulbasaur, foi feita 1 vez,  charmander não terminava nunca, o número de requisições era eterno, tipo um loop infinito. E não chegava a fazer a requisição do squirtle.
#### com request infinito:
```js
getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', ( data) => {
  console.log(data)
  getRequest('https://pokeapi.co/api/v2/pokemon/charmander/', ( data) => {
    console.log( data)
    getRequest('https://pokeapi.co/api/v2/pokemon/squirtle/', ( data) => {
      console.log( data)
    })
  })
})
```
Quando me dei conta vi que a request foi declarada fora da getRequest e que poderia ser isso, e realmente era, e a joguei pra dentro da função.
A dúvida é: se a request declarada fora da função era o problema do request infinito, porque não havia request infinito quando eu fazia a requisição apenas para 1 pokemon, somente quando adicionei mais uma ou duas getRequest()?

Obrigada!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Há algum tempo, um aluno teve essa mesma dúvida. Vou deixar a issue que ele abriu aqui abaixo e, caso ainda reste alguma dúvida, pode comentar aqui abaixo que te ajudo, ok? =)

- [Requests infinitos](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1905)

**Comment by ElaineDelgado** [comment]
#### "Se a criação do objeto de request estiver de fora do escopo da getTodos, o loop infinito acontece pq dentro da getTodos o mesmo objeto está sendo usado. Ou seja, é necessário que a cada invocação da getTodos, um novo objeto XMLHttpRequest seja criado em memória, e isso só acontece se o objeto está dentro da função."

Mesmo lendo essa explicação ainda não está claro o porquê do request infinito com 2 ou mais pokemons e não acontece quando faço o request para apenas 1 pokemon:
```js 
getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', (error, data) => {
  console.log(error,data)
})
// sem request infinito
``` 
Eu não consigo visualizar o que está acontecendo quando ocorre o request infinito.

**Comment by Roger-Melo** [comment]
@ElaineDelgado vamos fazer um experimento para descobrirmos os valores que `request.readyState` e `request.status` resultam?

No código abaixo, o objeto `request` está fora da `getRequest` e, quando apenas 1 request é executado:

- antes do addEventListener ser executado, `request.readyState` resulta em `0` e `request.status` também resulta em `0`
- dentro do do addEventListener, `request.readyState` resulta em `1` a `4` e `request.status` resulta em `0` e `200`

Você pode comprovar isso executando o código abaixo e visualizando os resultados no console:

```javascript
const request = new XMLHttpRequest()

const getRequest = (url, callback) => {
  console.log(
    'Antes do addEventListener', 
    'request.readyState:', 
    request.readyState, 
    'request.status:', 
    request.status
  )

  request.addEventListener('readystatechange', () => {
    console.log(
      'Dentro do addEventListener', 
      'request.readyState:', 
      request.readyState, 
      'request.status:', 
      request.status
    )

    if (request.readyState === 4 && request.status === 200) {
      const data = JSON.parse(request.responseText)
      callback(`O nome do Pokemon obtido é: ${data.name}`)

      return
    }
  })

  request.open('GET', url)
  request.send()
}

getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', (data) => {
  console.log(data)
})
```

![Group 9](https://user-images.githubusercontent.com/29297788/155639847-ed616ccb-4947-4aa4-8d7f-8506d87f08e1.jpg)

Tudo conforme o esperado até aqui, certo?

Agora... se o objeto `request` é mantido fora de `getRequest` e há um segundo request, **à partir desse segundo request**, os resultados serão os seguintes:

- antes do addEventListener ser executado, `request.readyState` resulta em `4` e `request.status` resulta em `200`
- dentro do do addEventListener, `request.readyState` resulta em `1` a `4` e `request.status` resulta em `0` e `200`

☝🏻 lembrando: isso acontece **do segundo request em diante, com o objeto request fora da getRequest, ok?** =)

Olha só:

```javascript
const request = new XMLHttpRequest()

const getRequest = (url, callback) => {
  // nada aqui mudou
}

// aqui foi acrescentado um segundo request
getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', (data) => {
  console.log(data)
  getRequest('https://pokeapi.co/api/v2/pokemon/charmander/', ( data) => {
    console.log( data)
  })
})
```

![image 16](https://user-images.githubusercontent.com/29297788/155640191-aad3dc63-3f3c-4225-abb3-a95fc2f23fdc.jpg)

---

Com essas informações, vc consegue perceber pq o request infinito está acontecendo?

O que estamos fazendo aqui é um processo didático, ok? =)

Se eu te direcionar ao invés de dar a resposta pronta, dificilmente vc cairá nessa mesma situação caso entenda por conta própria o que está acontecendo =)

**Comment by ElaineDelgado** [comment]
#### "Se eu te direcionar ao invés de dar a resposta pronta, dificilmente vc cairá nessa mesma situação caso entenda por conta própria o que está acontecendo"
Eu agradeço, e normalmente com esse tipo de didática eu consigo entender o problema, mas não é o caso dessa vez.

#### "Com essas informações, vc consegue perceber pq o request infinito está acontecendo?" 
Ainda não. 
Tenho tentado, mas não consigo entender de onde sai esse loop.
Com o request fora da função, eu tinha achado que era por causa do "if" com a condição de request.readyState igual a 4 e o request.status igual a 200, e como antes do addEventListener essa condição já era true o loop acontecia, mas testei tirar o if e deu na mesma. 
Antes da primeira invocação da getRequest o objeto request já está criado e os valores das chaves desse objetos são null, false, string vazia... ao invocar a getRequest os valores mudam; na segunda invocação além de o objeto já estar criado algumas chaves (readyState, status, responseText) já  possuem valor por causa da primeira invocação, então com a segunda invocação esses valores são modificados. Mas aco que isso também não tem a ver, né?
Não consigo nem uma pista do porquê do looping.

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado.

Esse request infinito está acontecendo pelo seguinte...

Quando `getRequest` é invocada pela 1ª vez, um listener de evento do tipo `readystatechange` é atrelado ao objeto `request`. Isso faz com que toda vez que a propriedade `readyState` mude, o callback do listener de evento seja executado.

```javascript
const getRequest = (url, callback) => {
  // ...
  request.addEventListener('readystatechange', () => {
    /*
    todo o código dessa função de callback é executado quando readyState muda
    */
  })

  request.open('GET', url)
  request.send()
}
```

Só que quando `getRequest` é invocada pela segunda vez, tem um detalhe que aconteceu na primeira invocação que faz com que requests infinitos sejam executados: o método `open()`.

O método `open` inicializa um request novo 👉🏻ou reinicializa👈🏻 um request existente.

Reinicializar significa o seguinte: quando esse método é executado em um objeto `request` já ativo/iniciado, a propriedade `readyState` desse objeto recebe 0.

Como o listener de mudança da `readyState` está escutando essa mudança desde a invocação passada, a função de callback do listener é executada novamente. 

Como há um listener de evento de mudança do valor da `readyState` e o valor dela está sempre mudando (devido ao open atrelado em um `request` ativo), requests infinitos são executados.

Vc pode saber mais sobre esse comportamento do `open` aqui abaixo. Observe bem o parágrafo inicial e a nota que fala sobre a invocação desse método em um request ativo:

- [XMLHttpRequest.open()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open)

Dito isso, tudo o que vc precisa fazer para que requests infinitos não aconteçam nesse caso é não reutilizar um objeto `request` que já está ativo.

Isso pode ser feito criando um objeto `request` diferente a cada invocação de `getRequest`. Ou seja, declare `request` dentro do escopo de `getRequest`.

Ao executar o código abaixo, não haverão mais requests infinitos =)

```javascript
const getRequest = (url, callback) => {
  const request = new XMLHttpRequest()

  request.addEventListener('readystatechange', () => {
    if (request.readyState === 4 && request.status === 200) {
      const data = JSON.parse(request.responseText)
      callback(`O nome do Pokemon obtido é: ${data.name}`)

      return
    }
  })

  request.open('GET', url)
  request.send()
}

getRequest('https://pokeapi.co/api/v2/pokemon/bulbasaur/', (data) => {
  console.log(data)

  getRequest('https://pokeapi.co/api/v2/pokemon/charmander/', (data) => {
    console.log(data)
  })
})
```

**Comment by ElaineDelgado** [comment]
Muito obrigada pela explicação detalhada, professor, entendi que a criação do novo objeto deve ficar dentro da função para que um novo objeto seja criado a cada invocação, só não consigo ainda  ver exatamente o que está acontecendo para criar o loop, mas vou estudar essa issue até cair a ficha.
Muito obrigada!

**Comment by Roger-Melo** [comment]
O que está causando o request infinito é o objeto ser reutilizado com a `readyState` sempre recebendo 0 depois de receber 1, 2, 3 e 4. 

A função que é executada quando essa mudança (`readystatechange`) acontece sempre vai ser executada a cada ver que `readyState` receber um novo valor. Como `readyState` nunca para de receber um novo valor, os requests nunca param de acontecer.

**Comment by ElaineDelgado** [comment]
Entendido, obrigada, professor!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
