### ISSUE TITLE
Resumo da aula setTimeout() e o objeto window - aula 02-02 da etapa 07

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#3173]
SET TIME OUT( ) E O OBJETO WINDOW

O que é objeto `Window`?
R: É o objeto que existe no escopo global de uma aplicação JS.
No projeto front-end esse objeto é o `window`, quando mexemos com Node esse objeto se chama `global`.

Pra que serve o método `setTimeout()` e como ele é utilizado?
R: Ele executa uma função, após o tempo que especificarmos. Primeiro passamos como parâmetro a função e depois o tempo pra ela ser executada.

Pra que serve o método `scrollTo()` e como ele é utilizado?
R: Ele rola a página pras coodernadas passadas como parâmetro do método. O primeiro argumento é o eixo X, o segundo argumento é o eixo Y.

```js
/* MÉTODO setTimeout() */

setTimeout(() => {
    alert('Hello World')
}, 2000)
//Após a página carregar, depois de 2 milissegundos vai ser exibido um alert "Hello World".


/* MÉTODO `scrollTo()` */

scrollTo(0, 100)
// A página vai rolar pro eixo X | 0 e eixo Y | 100
```

**Comment by Roger-Melo** [comment]
Show @rafaelpradoj. Vamo que vamo, rumo à fluência! 🙌
