### ISSUE TITLE
Etapa 11, Exrcicio 27

### ISSUE THREAD

**Issue by gerafimjoaquim** [roger-melo-treinamentos/curso-de-js-roger-melo#3174]
### Etapa da aula

11

### Nome da aula

Exercicio 27- 06)

### Link da aula

https://youtu.be/OYUdbwWytFk

### Descreva a dúvida

Boa-noite ROGER
No exercício 27:
```
*
  06

  - Crie uma função que recebe 3 argumentos;
  - Se um dos 3 argumentos não for passado na invocação, a string 'A função 
    deve ser invocada com 3 argumentos' deve ser retornada;
  - Se todos os argumentos forem passados, retorne a string 'A função foi 
    invocada com 3 argumentos'.
*/
```
Eu resolvi assim:
```js

const myFunc = (param1, param2, param3) => {

  const parameters = [param1, param2, param3]
  const paramEmpty = param => param === undefined
  const someParamEmpty = parameters.some(paramEmpty)

  if(someParamEmpty){
    return 'A função deve ser invocada com 3 argumentos'
  }

  return 'A função foi invocada com 3 argumentos'
}
console.log(myFunc())//A função deve ser invocada com 3 argumentos
console.log(myFunc('Argumento 1', 'Argumento 2', 'Argumento 3'))//A função foi invocada com 3 argumentos
```
Mas o ROGER usou o método `includes` na correcção, assim:
```js

const myFunc = (param1, param2, param3) => {

  if([param1, param2, param3].includes(undefined)){
     return 'A função deve ser invocada com 3 argumentos'
  }

  return 'A função foi invocada com 3 argumentos'
    
}
```
NÃO PERCEBI o uso do ```includes```. Porque é que o ```includes``` funciona? Pois o array que está sendo testado pelo ```if``` não contem o item "undefined" para que seja possivel verificar a sua existência.

O que o JS faz por baixo dos panos? Como é que o array inclue o 'undefined' se não está de forma explicita no array?

---
``````

<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gerafimjoaquim!

> ## O que o JS faz por baixo dos panos? Como é que o array inclue o 'undefined' se não está de forma explicita no array?

Quando uma função que possui um parâmetro é invocada sem um valor recebido como argumento, `undefined` é automaticamente atribuído para o parâmetro:

```javascript
const myFunc = param1 => {
  console.log(param1)
}

myFunc()  // como nenhum valor foi inserido como argumento, param1 recebeu undefined automaticamente
```

Ou seja, no código acima, por baixo dos panos é como se isso estivesse acontecendo:

```javascript
const myFunc = param1 => {
  console.log(param1)
}

myFunc(undefined) // 👈🏻 undefined é inserido por baixo dos panos
```

Isso significa que, independente de quantos parâmetros a função tenha, se ela for invocada sem argumento, o primeiro parâmetro automaticamente receberá undefined:

```javascript
const myFunc = (param1, param2) => {
  console.log([param1, param2].includes(undefined)) // true
}

myFunc()
```

No código acima, como `param1` está armazenando undefined, toda a expressão do includes retorna `true`.

Se param1 receber um valor mas param2 não, true também será retornado pq param2 está armazenando undefined:

```javascript
const myFunc = (param1, param2) => {
  console.log([param1, param2].includes(undefined)) // true
}

myFunc(1)
```

Ficou mais claro? =)

**Comment by gerafimjoaquim** [comment]
Obrigado ROGER, ficou muitissimo claro, que até testei outra forma e clareou tudo:
```js
const myFunc = (param1, param2, param3) => {
  const paramsArray = [param1, param2, param3]

  return paramsArray
}

console.log(myFunc())//[undefined, undefined, undefined]
````

Muito obrigado!
