### ISSUE TITLE
Resumo da Aula03-04 Criando e removendo elementos do DOM da etapa 05

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3179]
**Criando elemento do DOM(createElement) {**

**=>** Primeiro com a a tag li referenciada em uma const li, vamos coloca-la dentro de uma função callback do addEventListener('evento',callBackFunction) assignada do método do DOM createElement este método do document é utilizado para criar um novo elemento HTML e passamos como argumento o nome do novo elemento que queremos criar, neste caso estamos checando na console através da variável li o novo elemento HTML li que foi criado.

```JS
button.addEventListener('click', () => {
    const li = document.createElement('li')
    console.log(li)
})
```
**}**

**(Agora que criamos a nova tag li, podemos adicionar um conteúdo) (textContent) {**

**=>** com nossa mesma variável dentro da callbak da adddEventListener vamos encadear em nossa variável li a propriedade textContent e assignar a nossa li a string novo item.

```JS
button.addEventListener('click', () => {
    const li = document.createElement('li')

    li.textContent = 'Novo item'
    console.log(li)
})
```
**=>** Olhando na console, podemos observar agora, que nossas tags li adicionadas foram preenchidas com o texto novo item.
	**}**
**}**

**(inserindo nossa tag li no DOM dentro da ul) {**

**=>** Primeira forma(método apend -> no elemento: pai) {
**=>** Dentro de nossa função callback do addEventListener que este encadeada no button com a const li referenciando o elemento li  e logo após colocando o texto através da testContent com a frase novo item em nossa li, vamos encadear na variável ul que seria pai das tags li e encadear nela o método apend que recebe como argumento a li já com o texto. 

```JS
button.addEventListener('click', () => {
    const li = document.createElement('li')

    li.textContent = 'Novo item'
    ul.append(li)
})
```
**OBS:** O método apend insere o elemento recebido como argumento como ultimo filho do elemento que ele foi encadeado
**}**

**=> Segunda forma (método prepend -> no elemento : pai) {**
**=>** Primeiro você cria os elementos referenciando-os em uma variável com o querySelector, depois você seta o conteúdo e os atributos desse elemento e então você adiciona esse elemento como primeiro ou ultimo filho de um elemento no DOM

**=>** Semelhante a forma anterior de encadear na li que são as tags filhas de ul, vamos usar o método prepend que neste caso adiciona as novas li como primeiro filho da ul.

```JS
button.addEventListener('click', () => {
    const li = document.createElement('li')

    li.textContent = 'Novo item'
    ul.prepend(li)
})
```
 **}**
**}**

**(inserindo um template HTML dentro de um elemento de uma maneira diferente) {**

**=>** Primeiro vamos obter a referencia do botão em uma variável button com o document.querySelector('button')

```Js
const button = document.querySelecto('button')
```

**=>** Logo após vamos encadear na variável button o método addEventListener() que receberá como argumento o evento a ser monitorado nesse caso o click e como função callback sera com parâmetro vazio e dentro da função callback, teremos nossa variável ul que guarda a parent da nossas childrens lis e ela será concatenada com uma nova tag li seguida da mensagem dentro das tags li

```JS
button.addEventListener('click', () => {
    ul.innerHTML += '<li>Novo item</li>'
})
```
**}**

**Removendo elemento do DOM() {**

**=>** Primeiro referenciamos a tag o o pai de algumas tags para remover varias de uma vez, como exemplo uma unordered ilst ul que tem varias li lists como children. E logo após com a variável onde referenciamos os elementos encadeamos o método remove()

```JS
const ul = document.querySelector('ul')

ul.remove()
```
**}**

**Removendo varios elemento do DOM() {**

**=>** Após referenciarmos as tags lis na variável de nome (li), vamos encadear um forEach e como função callback vai receber o parâmetro li, que seria cada li das li da unordered list (ul) essas li da callback do forEach vao ser encadeadas cada uma de um addEventListener recebendo como primeiro parâmetro o click que seria o evento a monitorar e segundo parâmetro a função callback que tem como parâmetro o event que seria o objeto que referencia o evento ocorrido com o event.target referenciado na clickElement vamos encadear nossa variável clickedElement e encadear com o método remove(). Com isso, a cada click vamos eliminar um li da lista de lis que temos dentro da ul.

```JS
const lis = document.querySelectorAll('li')

lis.forEach(li => {
    li.addEventListener('click', event => {
        const clickedElement =  event.target
        clickedElement.remove()
    })
})
```
**}**

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
