### ISSUE TITLE
Dúvida no exercício 5 da 3ª leva de exercícios da etapa 02

### ISSUE THREAD

**Issue by marovitch** [roger-melo-treinamentos/curso-de-js-roger-melo#3186]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/790701

### Descreva a dúvida

Boa noite, Roger. Estou com uma dúvida que na verdade é bastante simples. No exercício 5, devemos iterar sobre o array "randomValues" até a 4ª string dele e exibir um console contendo algumas informações a respeito da iteração.

Meu código parece correto e parece com o seu e tudo funciona, exceto pela variável que faz a soma de quantas iterações aconteceram até chegar na condição (iterar até a 4ª string).  No console, a "totalIterations" está retornando 0. 

Mando meu código abaixo. Pode me ajudar a encontrar o erro por favor?

```const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS', 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]

let stringAmount = 0;
let booleanAmount = 0;
let first4Strings = []
let totalIterations = 0;
let typeOfItem = typeof randomValues[i];

for(i=0; i<randomValues.length; i++){
  if(stringAmount = 4){
    break
  }else if(typeOfItem === 'string'){
    stringAmount++
    first4Strings.push(randomValues[i])
  }else if (typeOfItem === 'boolean'){
    booleanAmount++
  }
  
  totalIterations++
}


console.log(`3 informações sobre o array randomValues:
  - As primeiras 4 strings são ${first4Strings.join(', ')};
  - Até que as primeiras 4 strings fossem iteradas, ${booleanAmount} booleans foram iterados;
  - O array foi iterado por ${totalIterations} vezes.`);
  ```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @marovitch.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## No console, a "totalIterations" está retornando 0.

Não vou dar a resposta pronta, mas vou te mostrar o caminho para que você chegue nela. Por que estou fazendo isso? Se você entender a razão pela qual `totalIterations` está retornando 0, você nunca mais terá esse tipo de problema.

Primeiramente, recomendo que você olhe cuidadosamente as expressões que foram especificadas como condições do if e dos else if do seu código. 

Ao observar as condições, você consegue perceber o motivo de `totalIterations` retornar 0?

---

Fico no aguardo =)

**Comment by marovitch** [comment]
Oi, Maykell. Localizei o erro :D Agora o código está retornando a quantidade de iterações. Porém, agora estou com outros erros. Vou rever a resolução de exercícios com calma pra ver se entendo onde estou errando. Obrigada pela resposta rápida! :)

**Comment by Roger-Melo** [comment]
@marovitch conseguiu resolver?

Se precisar de ajuda pode comentar aqui em baixo =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
