### ISSUE TITLE
Erro de Request: Access to XMLHttpRequest

### ISSUE THREAD

**Issue by gerafimjoaquim** [roger-melo-treinamentos/curso-de-js-roger-melo#3188]
### Etapa da aula

11

### Nome da aula

Trabalhando com JSON aula 03-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1255410

### Descreva a dúvida

Boa-tarde ROGER

Quando segui o exemplo de Requisição de dados no formato JSON hospedados localmente no meu computador, tive o Erro: ``
Access to XMLHttpRequest at 'file:///C:/Users/Pathfinder%20TESTE/Desktop/JavaScript/CJRM/gerafim/todos.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.``

Como resolver?

@Roger-Melo

**Comment by Roger-Melo** [comment]
@gerafimjoaquim sobe o projeto no github e manda o link aqui. Assim eu consigo testar o mesmo código que vc está usando e te ajudar com mais precisão =)

**Comment by gerafimjoaquim** [comment]
Bom-dia ROGER
Segue o Link dos arquivos:  https://github.com/gerafimjoaquim/CJRM-Request

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
