### ISSUE TITLE
Opinião sobre a resolução do exercício

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#3193]
### Etapa da aula

1

### Nome da aula

Exercício 04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/761582

### Descreva a dúvida

Bom dia!

Na bateria de Exercícios 4 e especificamente o exercício  Nº10, eu cheguei a uma resolução e estou
mandando antes de ver o vídeo das correções dos exercícios .

 ```js
 /*
  10 - Comente o console.log() acima e:

  - Abaixo da constante "evenNumbers", exiba no console um boolean que indica se  
    o número 8 existe no array;
  - Não utilize o método includes desta vez.
*/

const evenNumbers = [0, 2, 4, 6, 8, 10];

// Primeiro eu vejo a posição do index que o Número 8 está.
console.log(evenNumbers.indexOf(8));

// Já que eu sei que o index do numero 8 é '4', então é so fazer a verificação.
console.log(evenNumbers[4] === 8); // true é retornado
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
@GoharaJunior nem sempre é preciso acertar de primeira. Quando isso acontecer, segue [esse passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) que é sucesso 🔥

E se algo não tiver ficado claro, pode abrir uma issue que te ajudo =)

**Comment by GoharaJunior** [comment]
@Roger-Melo 

Na hora que eu já coloco 
```js
evenNumbers.indexOf(8) // 4
```
Eu já consigo ver se ela existe ou não, pois me retorna o índice do elemento que pode ser encontrado no array

Essa verificação 'diferente ou igual a -1' é apenas pra retornar o boolean para se caso um dia eu precise
usar em alguma função eu ter esse boolean ?

```js
evenNumbers.indexOf(8) !== - 1
```

**Comment by Roger-Melo** [comment]
@GoharaJunior em suas aplicações JS, dificilmente vc precisará evitar o uso do `includes`, a não ser que a aplicação não dê suporte a versões mais atuais nos navegadores =)

O objetivo desse exercício é fazer vc pensar em uma solução alternativa para resolver o desafio e checar se vc sacou os possíveis valores retornados pelo `indexOf`.

---

Tecnicamente falando, o `!==` está comparando se o valor retornado pela expressão `evenNumbers.indexOf(8)` é diferente de `-1`.

O `indexOf()` retorna `-1` caso o valor que ele receba não seja um item do array.

Se o valor é um item do array, ele retorna o index do item:

```javascript
// indexOf invocado com um valor que existe no array
[1, 2, 3].indexOf(1) // 0

// indexOf invocado com um valor que não existe no array
[1, 2, 3].indexOf(5) // -1
```

Isso significa que ao acrescentar `!== -1` nessa expressão, ela resultará em um boolean que indica se o item existe ou não no array:

```javascript
// item existe no array
[1, 2, 3].indexOf(1) !== -1 // true

// item não existe no array
[1, 2, 3].indexOf(5) !== -1 // false
```

Com esse boolean vc pode fazer o que for preciso em uma operação que envolva checar se o item existe no array =)

Pegou a ideia?

**Comment by GoharaJunior** [comment]
@Roger-Melo Saquei, obrigado! 🚀

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
