### ISSUE TITLE
Resumo da Aula Etapa 01 - Controle de fluxo a Etapa 03 - Funções e Métodos

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#3197]
/*
RESUMO DAS AULAS 
 LOOP FOR , PERCORRER ARRAYS

 -
 let nomes = ['Leonel','Augusto','Rodolfo']

 for(let i =0 ; i < nomes.length; i++){

    console.log(`Os nomes existentes na lista são : ${nomes[i]}`)
 }
*/

/*LOOP WHILE*/

/* let i=0
const names = ['Rodolfo','Rondinely','Silva']
while (i < names.length ){
    console.log(names[i]);
    i++
} */

// TREINAR ARRAYS E TUAS FUNÇOES

/*ARRAYS FUNÇÕES */

/*
listar arrays usar laço for
*/
let algumArray =  ['Rodolfo','Rondinely','Web Developer']

console.log(algumArray.push('Enzo'));  // colocar itens no final do array
console.log(algumArray.pop());         // retirar o ultimo item do array
console.log(algumArray.shift());       // remove item do inicio do array 
console.log(algumArray.unshift('Rodolfo')); // adiona no inico do array
console.log(algumArray.slice(1,2));    // busca apartir do item 1 ate o item dois , resposta deve ser Rondinnely
console.log(algumArray.slice(1));      // se colocar somente um numero, busca todo o array apos o  numero indicado
console.log(algumArray.indexOf('Rodolfo'));  //vai retornar '0', pois é verdaderio , caso falso retorna -1 veja abaixo
console.log(algumArray.indexOf('Rodolf')); // faltou o 'O' no final do nome.
console.log(algumArray.join(' / '));    // lista o array separados com o que vc quiser

for(let i =0; i< algumArray.length ; i++){
console.log(`${algumArray[i]}`)}
console.log(algumArray.join(' ! '));
console.log(algumArray[0].toLowerCase);

//IF ELSE

const passoword  = '123a'
/* if( passoword.includes('a')){
console.log(`Senha deve conter mais que 5 digitos`);
}
else{console.log(`Conectado com sucesso`);}

 */

**Comment by Roger-Melo** [comment]
Excelente @RodolfoRondinely , rumo à fluência! 🎯
