### ISSUE TITLE
Dúvida - Template strings - Aula 02-06

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#32]
Roger, posso colocar um if ou fazer uma validação dentro de uma template string?

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Interpolações de template strings precisam receber uma expressão.

Expressão é tudo aquilo que resulta em um valor. Exemplo: 

```javascript
1 + 1 // 2

'Hello' + ' ' + 'World' // 'Hello World'
```

O if não é uma expressão mas sim um statement. Ou uma "instrução", se preferir. E instruções não resultam em valores.

Para interpolar uma condição em uma template string, você pode usar um ternário:

```javascript
const birthYear = 1988
const currentYear = 2020

const ageString = `Tenho ${(currentYear - birthYear) > 18 ? 'mais' : 'menos'} de 18 anos.`

ageString // 'Tenho mais de 18 anos.'
```

O ternário é apenas um if/else inline.

O 1º operando é `a condição seguida de um ponto de interrogação`. `(currentYear - birthYear) > 18` é uma condição que resulta em true.

Como essa expressão resultou em `true`, todo o ternário resulta na string `'mais'` e 'mais' é renderizado na string.

Se a expressão resultasse em `false`, toda a expressão do ternário resultaria em `'menos'` e 'menos' seria renderizada.

Respondi sua dúvida?

Se não tiver ficado claro é só dar o toque e respondo de outra forma =)

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
Esta claro, valeu.

**Comment by Roger-Melo** [comment]
Show. Vou fechar a issue mas qualquer coisa, é só chamar =)
