### ISSUE TITLE
Resumo da Aula O método de array some() da etapa 05

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#320]
O método *`some`* é responsável por executar uma *função de teste* para cada item presente no array na qual ele foi encadeado. Essa *função de teste* precisa retornar um valor *trurthy* que é convertido para *boolean* por de baixo dos panos. O item que satisfaz a *função de teste*, ou seja, que faz com que ela retorne *true* fará com que o *`some`* pare imediatamente sua iteração sobre o array e retorne *true*. Caso nenhum item satisfaça essa *função de teste* o *`some`* retornará *false*.

## Parâmetros

1° Função de teste que pode ser declarada com 3 parâmetros:

1. *item* atual que está sendo iterado;
2. *index* do item atual que está sendo iterado;
3. *array* que está sendo iterado.

## Retorno

Um valor booleano.

---

*MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#description)*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Tamo junto @sou-gabriel. Rumo à fluência! 🔥
