### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3212]
====== TIPO REFERÊNCIA E TIPO PRIMITIVO =========================

```.js
// ===== TIPOS PRIMITIVOS ===============

/*
   - Numbers
   - Strings
   - Booleans
   - Null
   - Undefined
   - Symbol
   - BigInt
*/

// ===== TIPOS DE REFERÊNCIA ===============

/*
   - Objetos literais
   - Arrays
   - Funções
   - Data
   - Todos os outros objetos
*/
```

A diferença entre eles está na forma de como são armazenados na memória. Ao  atribuirmos um valor de tipo primitivo a uma variável ou constante, esse valor será armazenado numa "stack" que é uma pilha de diferentes valores armazenados na memória que podem ser acessados rapidamente quando necessário.

Os espaços na "stack" são limitados, portanto não comportam "valores complexos" como são os objetos. Devido a isso os jetos são armazenados em outro local diferente da "stack", que são chamados de "heap" que é um amontoado de maior espaço disponível para armazenar objetos maiores e mais complexos.

O "heap" é mais lento que a "stack" que é mais rápida. Eles são duas partes na memória para duas coisas diferentes.

Valores primitivos são armazenados na "stack" e são acessados através do nome da variável, já valores mais complexos como objetos são armazenados no "heap" e um ponteiro é criado na "stack" e esse ponteiro "aponta" para o objeto localizado no "heap". Portanto quando chamamos um objeto que está no "heap", essa chamada entra na "stack" localiza o ponteiro e puxa o objeto da "heap".

Portanto, valores no "heap" são acessados através de ponteiros e valores na "stack" são acessados através do nome da variável.

```.js
// valores primitivos armazenados na "stack"
let scoreOne = 50
let scoreTwo = scoreOne // cópia do scoreOne

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`)

score = 100

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`) // 50 100

// valores de referência
let userOne = { name: 'Roger', age: 25 }
let userTwo = userOne // tentando criar uma cópia, mas como é um objeto,
// está sendo copiado o ponteiro da userOne, portanto estão apontando pro mesmo local.

console.log(userOne, userTwo) // userOne userOne

userOne.age = 30

console.log(userOne, userTwo) // userOne userOne
// as duas ages foram modificados pois apontam pro mesmo objeto.
```

**Comment by Roger-Melo** [comment]
Excelente @santos2408, rumo à fluência! 🎯
