### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07 da etapa 05

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3219]
=== QUERY SELECTOR E QUERY SELECTOR ALL =======================

A ação de buscar e selecionar um elemento do DOM é chamada de query do DOM, ou seja, é feita uma consulta do DOM em busca de um elemento.

============================================

"QuerySelector" é o método mais recomendado para realizar consultar no DOM. Dentro da invocação do método nós passamos como parâmetro uma string com o selector CSS do elemento que queremos obter.

O resultado dessa expressão resultará numa referência para o seletor inserido.

Utilizando o querySelector, o DOM é percorrido e ao encontrar o primeiro seletor passado como parâmetro, ele retorna esse elemento. Se tiverem outros seletores iguais ao passado no parâmetro, eles serão ignorados e só o primeiro encontrado será retornado.

É possível também copiarmos a referência do elemento diretamente na árvore do DOM e colar no parâmetro do método.

```.js
const h1 = document.querySelector('h1')
const paragraph = document.querySelector('p') // só a primeira ocorrência
const error = document.querySelector('.error')
const errorDiv = document.querySelector('div.error')

console.log(h1)
console.log(paragraph)
console.log(error)
console.log(errorDiv)
```

=============================================

"QuerySelectorAll" é utilizado para obtermos todas as ocorrência do seletor passado como argumento do método.

O retorno dessa busca será um "node list" que contém a referência do seletor inserido no parâmetro do método.

Esse node list se assemelha a um tipo Array mas não é um Array, é apenas parecido. Normalmente é conhecido como array-like. Nem todos os métodos de array são possíveis utilizar numa node list. Mas podemos utilizar algumas funcionalidades parecida com array como acessar index através de colchetes.

É possível também percorrer o nodelist através de um loop.

```.js
const paragraphs = document.querySelectorAll('p')
const errors = document.querySelectorAll('.error')

paragraphs.forEach(paragraph => {
   console.log(paragraph)
})

console.log(errors)
```

**Comment by Roger-Melo** [comment]
Boa @santos2408, rumo à fluência! 🔥
