### ISSUE TITLE
Resumo da Aula Expressões regulares - Aula 01-04 da etapa 06

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#322]
As *expressões regulares* ou também conhecidas como *regular expressions (regex)* são utilizadas para definir um padrão de caracteres que vai buscar dar match com uma *substring* presente na *string*. Em JavaScript as *expressões regulares* são um objeto.

### Forma literal

A forma literal para se criar uma *expressão regular* consiste na abertura e fechamento de uma barra, que por sua vez envolve o padrão dos caracteres.

```jsx
let myRegex = /myPattern/
```

Criar uma expressão dessa forma é bastante utilizada quando o padrão que definimos na *expressão regular* é constante.

### Por meio do construtor RegExp()

Também é possível criar a nossa expressão regular por meio de uma função construtora `*RegExp()*` que por sua vez recebe como argumento o padrão a ser adotado.

```jsx
let myRegex2 = new RegExp('abc')
```

Criar uma expressão com esse construtor é bastante usual quando o padrão não é conhecido pelo programador, ou seja quando ele vem de outra fonte; e também quando o padrão pode sofrer variações.

## Character set

- []: define os caracteres que podem haver na *substring* para que ela dê match com o padrão. Ex.: [a-bA-B0-9] - indica que pode haver caracteres minúsculos e maiúsculos de a e z, além de definir que pode ter números entre 0 e 9.

## Quantificadores

- {}: é um exemplo de quantificador que indica o número de caracteres que a *substring* a ser buscada pode ter para dar match com o padrão. Ex.: {3, 6} - deve haver entre 3 e 6 caracteres para que o match ocorra.

## Alguns caracteres especiais

- *^* indica que não pode haver nada antes da *substring*.
- $ indica que não pode ter nenhum caracter após a *substring* que estamos buscando.
- '*' indica que pode haver uma mais mais ocorrências do caracter que vem antes desse caracter especial.

---

*MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)*

*Regex101: [https://regex101.com/](https://regex101.com/)*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! 🚀
