### ISSUE TITLE
Aplicação: Etapa 12 - Weather Application

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3223]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

gh repo clone carlosdevjs/weather-cjrm

### Maiores dificuldades durante a implementação

- Realizar a busca da requisições na 2ª vez implentando a "getCityWeather() e a sua refatoração =(, 
- destructuring do Array, refatoração, 
- achar bons nomes para as funções de responsabilidade,
-  errava muito na hora de colocar o await antes para desencapsular a promise
-  o teste com .then(concole.log)
- esqueço de usar o debugger para testar.

### Menores dificuldades durante a implementação

- manipulação do DOM, 
- a utilização do try/catch, 
- async/await;

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

Ps: consegui acessar o repositório entrando em seu perfil, pq o link do repositório que vc deixou não está correto.

**Comment by carlosdevjs** [comment]
Bom dia Roger

Me desculpe por isso.



Em ter., 1 de mar. de 2022 às 22:12, Roger Melo ***@***.***>
escreveu:

**Comment by carlosdevjs** [comment]
eu preciso reenviar, @Roger-Melo ?

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs. Não precisa, a análise está sendo elaborada =)

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ## Realizar a busca da requisições na 2ª vez implentando a "getCityWeather() e a sua refatoração =(, - destructuring do Array, refatoração,

Pelo que vi, seu código demonstra que mesmo com as dificuldades (as duas acima e as outras), vc conseguiu fazer funcionar =)

Vou falar sobre refatoração mais abaixo.

> ## esqueço de usar o debugger para testar.

O `debugger` é uma opção, e não uma obrigatoriedade. 

Entre `debugger` e `console.log`, use o que é mais confortável para o seu momento.

Eu tendo a usar mais `console.log` pelo simples fato de que eu não preciso pressionar F5 para recarregar ou "destravar" a página (como ao usar `debugger`).

---

## Nomeação de callbacks

Nomear callbacks de listeners de eventos tende a deixar o código mais legível, afinal, é mais fácil bater o olho no nome da função e saber de cara o que ela faz, ao invés de ter que ler todo o código dela para entender o que está acontecendo ali.

Seguindo esse raciocínio, o callback de listener do envio do form poderia se chamar `displayCityWeather`, `showCityWeather` ou algo do tipo.

```javascript
// antes
cityForm.addEventListener('submit', async event => {
  // várias linhas de código aqui
})
```

```javascript
// depois
cityForm.addEventListener('submit', showCityWeather)
```

---

## Variáveis nomeadas com `is`

Em vias de regra, o que se espera de uma variável que contém `is`, `should`, `has` ou algo parecido no nome é que ela armazene um boolean, como mencionei no tópico `Nomes de variáveis e funções` [nesta análise de seu Quiz](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2276).

No código abaixo, ao enviar o form, `isDnone` armazena um `DOMTokenList`:

```javascript
const removeClassName = () => {
  const isDnone = cityCard.classList
  console.log(isDnone) // DOMTokenList(4)...
  if (isDnone.contains('d-none')) {
    isDnone.remove('d-none')
  }
}
```

Já que o propósito de `isDnone` é deixar a condição do if mais legível, vc pode testar renomeá-la para `cardIsHidden`, por exemplo, e encadear `contains` no `DOMTokenList`.

Além disso, ao invés de remover a classe do `DOMTokenList`, eu acredito que fica mais legível remover do elemento em si:

```javascript
// antes
const isDnone = cityCard.classList
if (isDnone.contains('d-none')) {
  isDnone.remove('d-none')
}
```

```javascript
// depois
const cardIsHidden = cityCard.classList.contains('d-none')

if (cardIsHidden) {
  cityCard.classList.remove('d-none')
}
```

## Nome da função `removeClassName`

Um outro aspecto a ser observado aqui é nome da função. 

`removeClassName` pode ter um nome focado no impacto mais significativo da ação que ela executa na aplicação. 

A grosso modo, o que ela faz é exibir o card da cidade. Então ela pode ser renomeada como `showCityCard`.

```javascript
// antes
const removeClassName = () => {
  const cardIsHidden = cityCard.classList.contains('d-none')

  if (cardIsHidden) {
    cityCard.classList.remove('d-none')
  }
}
```

```javascript
// depois
const showCityCard = () => {
  const cardIsHidden = cityCard.classList.contains('d-none')

  if (cardIsHidden) {
    cityCard.classList.remove('d-none')
  }
}
```

---

## Ternário

Dentro da `insertIconAndImage`, nada está sendo feito com o valor que o ternário IsDayTime retorna. 

No fim das contas, o ternário só foi inserido ali para executar manipulação de DOM. Se o propósito é não aproveitar o valor que o ternário retorna, vc pode ir na abordagem clássica e usar um if.

```javascript
// antes
const insertIconAndImage = (IsDayTime, WeatherIcon) => {
  IsDayTime ? insertIconDayOrNight(cityTime, 'day') : insertIconDayOrNight(cityTime, 'night')
  timeIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />`
}
```

```javascript
// depois
const insertIconAndImage = (IsDayTime, WeatherIcon) => {
  timeIcon.innerHTML = `<img src="./src/icons/${WeatherIcon}.svg" />` // importante posicionar essa linha acima da ramificação abaixo, pq essa atribuição precisa ser executada independente se é dia ou não

  if (IsDayTime) {
    insertIconDayOrNight(cityTime, 'day')
    return
  }

  insertIconDayOrNight(cityTime, 'night')
}
```

## Uma abordagem possível

O que eu vou dizer não invalida o interessante estudo de mexer no código e refatorar funções, mas, hj, eu não quebraria essa manipulação de DOM em muitas funções, pq ela ainda está relativamente simples de entender.

Dá uma olhada no tópico [Uma abordagem possível](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2342) dessa issue. Essa é a abordagem que eu consideraria hoje.

---

Seu código demonstra ser um código pé no chão, que não inventa moda antes de focar nos fundamentos. Sua evolução ao longo das análises é perceptível =)

Mais uma vez, parabéns pelo esforço.

As observações fizeram sentido?

**Comment by carlosdevjs** [comment]
Fizeram sim, e vou colocar em prática. Obrigado pelo feedback, vou melhorar na criação de bons nomes.

**Comment by Roger-Melo** [comment]
Show de bola! No que precisar, é só abrir uma nova issue =)
