### ISSUE TITLE
Problemas com Lógica

### ISSUE THREAD

**Issue by developsouza** [roger-melo-treinamentos/curso-de-js-roger-melo#3232]
### Etapa da aula

1

### Nome da aula

Exercícios da Aula 03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/745806

### Descreva a dúvida

Opa Roger, então, estou com problemas na parte lógica dos exercícios, estou seguindo o método, faço as revisões de raio x que você sugere para que tenhamos uma melhor compreensão, compreendo, porém, quando leio o enunciado dos exércícios, em especial os últimos de cada aula, onde tem algo mais elaborado a ser feito eu não consigo raciocinar da forma correta para resolver e compreender. O que me indica para essa parte lógica das atividades? Valeu!

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @developsouza.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## O que me indica para essa parte lógica das atividades?

Geralmente, os últimos 2 exercícios das baterias de exercício são mais complexos mesmo. Afinal, você está em um treinamento para chegar na fluência. E chegar na fluência não é fácil =)

Dito isso, você não precisa acertar tudo de primeira. Não é esse o objetivo. 

Porém, ao resolver o exercício de forma diferente, ou até mesmo travar para resolvê-lo, recomendo que siga [esses passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) à risca.

Além disso, tem um outro ponto que vc precisa sacar...

Na minha opinião técnica, no começo, vc não deve prosseguir se tiver dúvidas. Por isso, vc deve abrir uma issue assim que alguma dúvida surgir. 

Caso contrário, se vc não solucionar essa dúvida, ela vai voltar quando vc estiver praticando novos conceitos e isso vai virar uma bola de neve. Não deixe isso acontecer. Peça ajuda quando tiver dúvida, ok? =)

**Comment by developsouza** [comment]
Tranquilo, eu estou justamente seguindo essa metodologia, não avancei de etapa ainda porque tive esses problemas nessa primeira etapa, vou ver onde posso focar mais e tentar absorver melhor os conteúdos. Obg pela resposta.
