### ISSUE TITLE
Dúvida sobre app-todo-list.

### ISSUE THREAD

**Issue by hamiceis** [roger-melo-treinamentos/curso-de-js-roger-melo#3237]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://hamiceis.github.io/ListadeTarefas/

### Maiores dificuldades durante a implementação

// Boa tarde, tentei fazer de duas maneiras a lógica para buscar o todo ,  fiquei na duvida sobre  esses dois métodos, 
porque o primeiro funciona, e o segundo não funciona?

Segunda duvida : nessa primeiro método , porque não possui { }, logo após => , e funciona normal ? 
fico grato, se me tirar essa dúvida  
//-----------------------------------------------------------------------------------------------------------------------
//1 - método 

const filterTarefas = (tarefas, inputValue, CheckListas) => 
    tarefas.filter(tarefa =>{
        const CheckList = tarefa.textContent.toLowerCase().includes(inputValue)
        return CheckListas ? CheckList : !CheckList
    })

const ManipularClasses = (tarefas, ClasseAdd, ClasseRemove) => {
    tarefas.forEach(tarefa => {
        tarefa.classList.remove(ClasseRemove)
        tarefa.classList.add(ClasseAdd)
    })
}

function esconderTarefas(tarefas, inputValue){
    const Esconder = filterTarefas(tarefas, inputValue, false)
    ManipularClasses(Esconder,'hidden','d-flex')
}

function mostrarTarefas(tarefas, inputValue){
    const Mostrar = filterTarefas(tarefas, inputValue, true)
    ManipularClasses(Mostrar,'d-flex','hidden')

}

inputSearchLista.addEventListener('input', event =>{
    const inputValue = event.target.value.trim().toLowerCase()
    const tarefas = Array.from(lista.children)
    
    esconderTarefas(tarefas,inputValue)
    mostrarTarefas(tarefas,inputValue)

})

//--------------------------------------------------------------------------------------------------------------------------------//
//2 - método

function filterTarefas(tarefas, inputValue, checkList){
    tarefas.filter(tarefa =>{
      const check = tarefa.textContent.toLowerCase().trim().includes(inputValue)
      return checkList ? check : !check
    })
}

function ManipularClasses(tarefas, classAdd, classRemove){
    tarefas.forEach(tarefa => {
        tarefa.classList.remove(classRemove)
        tarefa.classList.add(classAdd)
    })
}

function mostrar(tarefas, inputValue) {
    const mostrarTarefas = filterTarefas(tarefas, inputValue, true)
    ManipularClasses(mostrarTarefas,'d-flex','hidden')
}

function esconder(tarefas, inputValue){
    const esconderTarefas = filterTarefas(tarefas, inputValue, false)
    ManipularClasses(esconderTarefas,'hidden','d-flex')
}

formSearch.addEventListener('input', event => {
    const inputValue = event.target.value.trim().toLowerCase()
    const tarefas = Array.from(lista.children)

    mostrar(tarefas, inputValue)
    esconder(tarefas, inputValue)
   
})

### Menores dificuldades durante a implementação

const formSearch = document.querySelector('.form-search input')
const lista = document.querySelector('.lista-container')
const formAddList = document.querySelector('.form-add-list')

const addtarefa = (inputValue) => {
    if(inputValue){
        lista.innerHTML += `<li class="list-group-item d-flex justify-content-between align-items-center" data-list="${inputValue}">
        <span data-span="${inputValue}">${inputValue}</span>
        <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
    </li>`
    }
    event.target.reset()
}

formAddList.addEventListener('submit', event => {
    event.preventDefault()
    const inputValue = event.target.add.value.trim()
    addtarefa(inputValue)
})

const removerTarefa = (elementClicked) => {
    const dataTrash = elementClicked.dataset.trash
    const data = document.querySelector(`[data-list="${dataTrash}"]`)

    if(dataTrash){
        data.remove()
    }
}

const finalizarTarefa = clickedElement => {
    const spanData = clickedElement.dataset.span
    const data = document.querySelector(`[data-list="${spanData}"]`)

    if(spanData){
        data.classList.toggle('completed')
    }
}

lista.addEventListener('click', event => {
    const ClickedElement = event.target
    removerTarefa(ClickedElement)
    finalizarTarefa(ClickedElement)
})

**Comment by hamiceis** [comment]
Já descobri onde eu estava errando, faltou eu colocar um return antes do tarefas.filter ()..

**Comment by Roger-Melo** [comment]
Olá @hamiceis.

Quando surgir dúvida técnica, prefira abrir uma issue de dúvida. Assim consigo organizar melhor do que se trata cada issue =)

As dúvidas que vc listou acima foram resolvidas?

**Comment by hamiceis** [comment]
sim, muito obrigado ! =)

**Comment by Roger-Melo** [comment]
Show @hamiceis! =)

Procurei pelo seu nome na lista de alunos mas não encontrei. Com qual email vc se cadastrou no CJRM? Se não quiser falar por aqui, pode mandar um email para oi@rogermelo.com.br
