### ISSUE TITLE
Resumo da Aula 04-02 Event Bubbling e event delegation da etapa 05

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3238]
**Event Bubbling(Borbulhamento de eventos) {** O evento é iniciado no target do evento que é o elemento onde o evento foi adicionado e este evento se propaga em direção aos pais desse target para que os calls backs de eventos dos pais, sejam disparados também.
**}**

**stopPropagation() {**
**=>** Este método serve para parar a propagação padrão de um evento como o addEventListener, neste caso ao clicar, por default o cheque de eventos se propaga ate o pai de onde o event.target ocorreu. Como exemplo se temos um addEventListener em uma li ele se propagará até a tag pai Ul. com o stopPropagation() essa propagação será inibida e as outras funções de callback de outros addEventListener das tags parent não serão executadas

```JS
const ul = document.querySelector('ul')
const lis = document.querySelectorAll('li')

lis.forEach(li => {
    li.addEventListener('click', event => {
        const clickedElement = event.target
        console.log('clicou na LI')
        event.stopPropagation()
        clickedElement.remove()
    })
})

ul.addEventListener('click', () => {
    console.log('cliclou na UL')
})
```
**}**

**Event Delegation() {**

 Muito util quando atrelamos eventos, em múltiplos elementos. Neste exemplos temos dois elementos HTML referenciados e encadeados com o addEventListener, no entanto para cada evento é delegado o que o ocorrerá e com o uso do stopPrpagation é possível controlar em qual estagio ocorrerá os eventos encadeados. Neste exemplo temos o evento que cria novas Li para a pagina, referenciando uma nova li com o createElement('li') que pertence ao DOM e ajuda a criar novos elementos html, e logo apos sua referenciarão é colocado um texto utilizando a li referenciada e encadeando do textContent e para finalizar, o uso agora encadeado na ul do prepend, que pegará essa nova li e a colocará no topo após criada.

```JS
button.addEventListener('click', () => {
    const li = document.createElement('li')

    li.textContent = 'Novo item'
    ul.prepend(li)
})
```

=> Logo após temos o outro addEventListener que está sendo encadeado em todas as lis do documento HTML que já foram referenciadas com o querySelectorAll('li') essas lis estão encadeadas em um forEach(()=>{}) para iterar em cada elemento das lis dentro de nosso forEach que estamos delegando o que será feito com o o nosso outro addEventListener onde será referenciado em uma constante chamada clickedElement o event.target que nessa caso pertence ao evento do addEventListener que gera um ponteiro para varias possibilidades, nesse caso o target que seria o elemento onde o evento foi adicionado e aconteceu. Com o elemento onde o evento ocorre referenciado, podemos encadear na variável clickedElement o método do DOM remove() que vai remover o elemento onde o evento ocorreu.
```JS
lis.forEach(li => {
    li.addEventListener('click', event => {
        const clickedElement = event.target
        clickedElement.remove()
    })
})
```
**}**

**Comment by Roger-Melo** [comment]
Excelente @EneasFeynlinus, rumo à fluência! 🎯
