### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3246]
=== OBTENDO, ADICIONANDO, REMOVENDO =======================

classList: essa propriedade que retorna um DOMTokenList, que lista todas as classes que o elemento possui. Esse objeto é similar a um array e possui algumas propriedades e métodos.

classList.add( ): método de classList que adiciona uma classe no elemento, recebe como argumento o nome da classe que se quer adicionar.

classList.toggle( ): método de classList que alterna os valores da classe dependendo se ela existe ou não.

```.js
const texto = document.querySelector('.erro')

// propriedade que visualiza todas as classes do elemento
texto.classList

// adiciona uma classe no elemento
texto.classList.add()

// remove uma classe do elemento
texto.classList.remove()

// alterna entre adicionar e remover a classe do elemento, se classe existir,
// ele remove, se não existir, ele adiciona.
texto.classList.toggle()

const textos = document.querySelectorAll('.textos p')

// adicionando classe no elemento
textos.forEach(texto => {
   if (texto.textContent.includes('erro')) {
      texto.classList.add('erro')
   }
   
   if (texto.textContent.includes('success')) {
      texto.classList.add('success')
   }
})
```

**Comment by Roger-Melo** [comment]
Show @santos2408. Vamo que vamo, rumo à fluência! 🙌
