### ISSUE TITLE
retornando um pointerEvent ao inves de mouseEvent

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3249]
### Etapa da aula

5

### Nome da aula

Eventos de clique - Aula 03-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871195

### Descreva a dúvida

```js
const lis = document.querySelectorAll('li')
lis.forEach(li => {
    li.addEventListener('click', event => {
        console.log(event)
    })
})
```
Roger, este codigo esta retonando pointerEven, consegue me ajudar ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos!

Não tem problema, pq `PointerEvent` herda propriedades de `MouseEvent`. Isso significa que o objeto `PointerEvent` também tem a propriedade `target` acessível. Tudo bem?

Não se preocupe se o termo "herdar" soar estranho agora, vc vai aprender sobre isso na etapa 14 =)

**Comment by Giansantos-carlos** [comment]
Roger, obrigado, tranquilo.
