### ISSUE TITLE
Etapa 7, Aplicação: Quiz Interativo : Template e Checando respostas.

### ISSUE THREAD

**Issue by wsn-nunes** [roger-melo-treinamentos/curso-de-js-roger-melo#325]
Boa noite Professor a aplicação do Quizz | App .
No arquivo app.js tem os comentários das minhas dúvidas.

```js
const form = document.querySelector(".quiz-form")
const correctQuestions = ["B","A","B","B"]
const element = document.createElement("h5")
const feedback = document.querySelector('[data-feedback="correct-feedback"]')

const formQuestion = document.querySelectorAll(".form-question")

form.addEventListener("click",() => {

// Professor, porque a variável (usersAnswer) abaixo não pode ser declarada fora do escopo do evento "click"?
// e quando é declarada, o evento click não consegue enxergar, eu acho que é o termo correto 

    const usersAnswer = [ 
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value
    ] 

// a cada evento de click no checkbox o forEach() faz a iteração em cada elemento verificando se o elemento clicado é o mesmo elemento da resposta, caso seja igual, adiciona a classe "bg-success" - bootstrap 
// Neste caso abaixo o uso das condições estão corretas ?

    correctQuestions.forEach((correctQuestion,index) => {
        if(correctQuestion === usersAnswer[index]){
        console.log(correctQuestion)
        formQuestion[index].classList.add("bg-success")
        }else{
        formQuestion[index].classList.remove("bg-success")
        }
    })

})

form.addEventListener("submit",event => {
    event.preventDefault()
    
    const Questions = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value
    ]     
    let score = 0
   
    const answerAndQuestions = (correctQuestion, index) => {
        const isCorrect = correctQuestion === Questions[index]
        if(isCorrect){
            score += 25
                }
            }

// este elemento abaixo eu entendi , o por que, que pode ser declarado fora do escopo do forEach()

            element.textContent = `Você acertou ${score}% das questões`
            element.setAttribute("class","bg-success mt-4 mb-4 p-3 text-center text-light shadow")
            form.insertAdjacentElement("beforebegin",element)  

    correctQuestions.forEach(answerAndQuestions)

let count = 0
    const timer = setInterval(() => {
        if(count === score){
            clearInterval(timer)
        }
            element.textContent = `Você acertou ${count}% das questões`
            element.setAttribute("class","bg-success mt-4 mb-4 p-3 text-center text-light shadow")

            form.insertAdjacentElement("beforebegin",element)  
count++
    }, 30);

    scrollTo(0,0,)
})

}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi William.

Vamos lá =D

> Porque a usersAnswer não pode ser declarada fora do escopo do evento "click"? E quando é declarada, o evento click não consegue enxergar, eu acho que é o termo correto 

Observe que os itens do array `usersAnswers` são expressões `form.inputQuestion1.value`. Cada uma dessas expressões resulta no valor do atributo `value` do input marcado. 

Ou seja, no momento em que o array é criado, se nenhum input da primeira pergunta estiver "checado", `form.inputQuestion1.value` resulta em uma string vazia (`''`). Você irá comprovar isso ao invocar um `console.log()` que exibe o valor dessa expressão:

```javascript
form.addEventListener('submit', event => {
  // ...
  console.log(form.inputQuestion1.value) // ''
}
```

A razão de declarar o array `usersAnswers` dentro desse callback de listener de evento é a seguinte: quando o array for criado, os itens dele devem ser os resultados de todas as expressões `form.inputQuestion*.value`. 

Como o bloco de código dentro desse callback do submit só é executado quando o form é enviado, quando `usersAnswers` é criada após o envio do form, o esperado é que ela seja um array que contém os valores dos atributos `value` marcados pelo usuário.

Se ela for declarada fora do callback, o array vai ser criado antes do envio do form acontecer e as expressões `form.inputQuestion*.value` vão resultar nos valores dos inputs marcados de quando a página é carregada.

Lembre-se: o callback do `submit` só vai ser executado quando o envio do form acontecer.

Se `usersAnswers` é criada antes do envio do form acontecer, ela será declarada assim que a página é carregada (e será um array que contém os valores dos inputs marcados por padrão quando a página é carregada).

Então ela pode ser declarada fora do escopo do callback sim, mas o problema é que os itens do array serão os valores dos inputs de quando a página é carregada, e não necessariamente dos inputs que o usuário marcou.

Sacou a ideia?

> A cada evento de click no checkbox o `forEach` faz a iteração em cada elemento verificando se o elemento clicado é o mesmo elemento da resposta, caso seja igual, adiciona a classe "bg-success" - bootstrap. Neste caso abaixo o uso das condições estão corretas ?

Por que um evento de clique foi adicionado no form?

Não faz sentido usar `click` como evento aqui. Se `click` for usado como listener de evento em um `form`, a função que você especificou como callback do `click` será executada quando o usuário clicar no formulário. 

O evento que faz sentido aqui é o envio do form (`submit`), por que é só quando ele acontecer que as respostas do usuário devem ser obtidas e a pontuação calculada. Exatamente como eu mostrei na aula da construção dessa aplicação.

À partir daqui, para responder essa dúvida, eu vou desconsiderar esse evento de clique do código acima e partir do código abaixo, que foi o código analisado, ok?

```javascript
const form = document.querySelector(".quiz-form")
const correctQuestions = ["A","A","B","B"]
const element = document.createElement("h5")

form.addEventListener("submit",event => {

    event.preventDefault()

    const Questions = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value
    ]

    let score = 0

    correctQuestions.forEach((correctQuestion, index) => {
    
        if(correctQuestion === Questions[index]){
            
            score += 25
            console.log(score)
            element.innerHTML = `Você acertou ${score}%`
            element.setAttribute("class","bg-success mt-4 mb-4 p-3")
            form.insertAdjacentElement("afterend",element)

        }else{

            element.innerHTML = `Você acertou ${score}%`
            element.setAttribute("class","bg-danger mt-4 mb-4 p-3")
            form.insertAdjacentElement("afterend",element)

        }
    })
    
})

```

Tudo o que é necessário fazer dentro do callback do forEach é: 

- calcular a pontuação do usuário.

Apenas isso. O forEach deve ser usado aqui apenas para percorrer o array de respostas e calcular a pontuação.

Depois de calcular a pontuação (depois que a execução do forEach terminar), você irá fazer o que precisa fazer no DOM.

Observe que você irá inserir na tela as informações de pontuação baseado na pontuação do usuário. Então faz mais sentido setar e as classes e inserir a pontuação na tela depois que o forEach terminar de calcular a pontuação do usuário. Não tem necessidade de remover e adicionar classes à cada execução do forEach.

É basicamente isso:

```javascript
// antes
correctQuestions.forEach((correctQuestion, index) => {
  if (correctQuestion === Questions[index]) {
    score += 25
    
    element.innerHTML = `Você acertou ${score}%`
    element.setAttribute("class", "bg-success mt-4 mb-4 p-3")
    form.insertAdjacentElement("afterend", element)

  } else {

    element.innerHTML = `Você acertou ${score}%`
    element.setAttribute("class", "bg-danger mt-4 mb-4 p-3")
    form.insertAdjacentElement("afterend", element)

  }
})

// depois 
correctQuestions.forEach((correctQuestion, index) => {
  if (correctQuestion === Questions[index]) {
    score += 25
  }
})

// fora do forEach, você manipula o DOM de acordo com a pontuação do usuário. Exemplo:
element.innerHTML = `Você acertou ${score}%`

if (score >= 50) {
  element.setAttribute("class", "x")
} else {
  element.setAttribute("class", "y")
}

form.insertAdjacentElement("afterend", element)
```

Entendeu a ideia?

O `if/else` do exemplo acima pode ser substituído por um ternário, mas acho que você ainda não chegou nas aulas em que mostro ternários. Quando chegar, vc pode refatorar o `if/else`.

@wsn-nunes

**Comment by Roger-Melo** [comment]
@wsn-nunes vou fechar a issue mas quando surgirem dúvidas, é só abrir uma nova issue =)
