### ISSUE TITLE
: : marker dentro da miha li 

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3250]
### Etapa da aula

5

### Nome da aula

Eventos de clique - Aula 03-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871195

### Descreva a dúvida

Roger, dentro do meu elemento li aparece uma : : marker, isso faz com que uma marcação em numeros sequenciais  apareca sempre que eu seto um novo elemento li, como faço pra removelo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos.

Antes de responder, deixa eu dar uma dica...

Quando tiver dúvidas técnicas, poste o código (JS, e HTML + CSS - se houver).

Mesmo que vc já tenha postado o código em outra issue paralela que abriu (estou supondo que vc está testando o mesmo código de lá), é importante postar o código pq se alguém pesquisar e ler sua issue, essa pessoa vai saber exatamente do que vc está falando e vai poder comparar com um possível problema dela, ok? =)

`::marker` é um pseudo-elemento CSS. 

Como o foco do treinamento é JavaScript Puro, vou deixar algumas fontes confiáveis sobre CSS abaixo:

- [::marker - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker)
- [::marker - CSS Tricks](https://css-tricks.com/almanac/selectors/m/marker/)

**Comment by Giansantos-carlos** [comment]
Roger, primeiramente obrigado pela a dica é problema ou melhor dizendo equívoco resolvido.

Grato pelas referências. =)

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
