### ISSUE TITLE
Etapa 5, Event bubbling e event delegation - Aula 04-02

### ISSUE THREAD

**Issue by higoroficial-city** [roger-melo-treinamentos/curso-de-js-roger-melo#326]
Olá professor, na parte do event delegation, quando é feita a consulta no console do target da 'li', o meu não exibe a 'tagName' do elemento, e sim um 'nodeName', que possui o mesmo conteúdo, e aplicado no código, obtém o mesmo resultado. Mesmo sem aparecer a tagName do elemento, consegui usá-la normalmente.
 Qual a diferença entre os dois?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @higoroficial-city.

Pode postar o código aqui?

**Comment by higoroficial-city** [comment]
```js
const paragraph = document.querySelector('.copy-me')

paragraph.addEventListener('copy', () => {
    console.log('Texto copiado!')
})

const div = document.querySelector('.box')

div.addEventListener('mousemove', event => {
    div.textContent = `X ${event.offsetX} | Y ${event.offsetY}`
})

document.addEventListener('wheel', event => {
    console.log(event.pageX, event.pageY)
})
```

Este e o outros arquivos (index.html e app.js) estão iguais aos que você escreveu na aula. Uso o live preview no Chrome.

**Comment by Roger-Melo** [comment]
Oi Higor.

O código que você postou na issue acima não é da [aula 04-02](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890634). Sua dúvida é sobre evento em uma `li` e o código postado não contém `li`.

Por favor, sempre verifique se a issue realmente está correta, caso contrário fica complicado te ajudar mais rápido. Combinado?

Eu preciso ver o código correto pra te ajudar. Pode postar o HTML e CSS também, sem problemas.

Fico no aguardo.

**Comment by higoroficial-city** [comment]
Boa noite Roger. Mil desculpas, realmente não sei o que aconteceu pra eu ter colocado esse código de outra aula. Sempre reviso antes de postar.
Mas enfim, segue o código correto:
App.js:
```js
const button = document.querySelector('button')
const ul = document.querySelector('ul')


button.addEventListener('click', () => {
    const li = document.createElement('li')

    li.textContent = 'Novo item'
    ul.prepend(li)
})


ul.addEventListener('click', event => {
    const clickedElement = event.target
    
    if (clickedElement.nodeName === 'LI') {
        clickedElement.remove()
    }
})
```
Index.html:
```
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Eventos de clique</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <h1>Todos</h1>

    <ul>
        <li>Comprar frango</li>
        <li>Ler livro</li>
        <li>Tocar violão</li>
        <li>Pagar as contas</li>
    </ul>

    <button>Adicionar item</button>

    <script src="./app.js"></script>
</body>
</html>
```
E o style.css:
```
ul {
    padding: 0;
}

li {
    list-style-type: none;
    max-width: 200px;
    padding: 8px;
    margin: 8px 0;
    background: #eee;
    border: 1px dotted #ddd;
}
```

![Sem título](https://user-images.githubusercontent.com/61762293/113212548-4b655000-924d-11eb-9cbd-1726989e73ad.png)

**Comment by Roger-Melo** [comment]
Olá Higor.

Talvez a propriedade `tagName` não esteja sendo exibida em seu browser pelo seguinte... ao executar o código abaixo,

```javascript
ul.addEventListener('click', event => {
  console.log(event)
})
```

ao clicar em uma `li`, o objeto `MouseEvent` é exibido, certo?

Esse objeto possui a propriedade `target` que armazena um objeto que possui as propriedades `tagName` e `nodeName`. Só que para visualizar a `tagName`, é necessário descer até achar os `3 pontinhos` abaixo. Clique neles para que a listagem completa das propriedades seja exibida:

![img-01](https://user-images.githubusercontent.com/29297788/113239923-0f001700-9282-11eb-8c8e-e74187ae3302.jpg)

Teste e me avise se funcionou =)

---

A diferença entre `tagName` e `nodeName` é que `tagName` existe apenas para nós do tipo [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) e `nodeName` existe em qualquer [nó](https://developer.mozilla.org/en-US/docs/Web/API/Node). 

Quando `tagName` e `nodeName` são usados em elementos, ambos fazem a mesma coisa.

Já para outros tipos de nós, como um nó de comentário por exemplo, `tagName` retorna `undefined` por que comentário não é um nó do tipo [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element), mas sim do tipo [Comment](https://developer.mozilla.org/en-US/docs/Web/API/Comment):

```html
<body><!-- um comentário -->
</body>
```

```javascript
console.log(document.body.firstChild.tagName) // undefined
console.log(document.body.firstChild.nodeName) // #comment
```

Mas como eu disse, para elementos, tanto faz usar `tagName` e `nodeName`. 

Você pode ir a fundo no assunto pesquisando nos links acima, mas não recomendo investir energia (agora) nesse tipo de detalhe. Há conceitos mais importantes que você verá no treinamento daqui em diante.

@higoroficial-city

**Comment by higoroficial-city** [comment]
Sim, o MouseEvent exibe normalmente.
Funcionou sim, nos três pontinhos fica a tagName.
Obrigado pela explicação Roger.
