### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by VictorHugoDC1999** [roger-melo-treinamentos/curso-de-js-roger-melo#3267]
![IMG_20220306_182155498](https://user-images.githubusercontent.com/47994068/156943118-93cd8c2f-3881-4a8b-a4a5-c6a6bf08d9d7.jpg)

**Comment by Roger-Melo** [comment]
Show @VictorHugoDC1999. Vamo que vamo, rumo à fluência! 🙌
