### ISSUE TITLE
Resumo da Aula 01-05 Testando padrões de regex da etapa 06

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3269]
**=======================Testando padrôes de regex===========================**

**Criando REGEX para checar se a string user name (6 caracteres letras minúsculas) {**

**=>**Criamos uma const userName que vai armazenar a string a ser checada com o REGEX
**=>**Logo após na variável pattern nos vamos colocar nossa regular expression., assim
como uma string que vem entre aspas, a REGEX tem que vir entre /barras/
**=>** Vamos criar nosso caracter set com colchetes com letras minúsculas de a -a [a-z]
**=>** Vamos logo após nossos caracter set, vamos inserir abertura e fechamento de chaves
para quantificar a quantidade de caracteres que queremos dar match. {6,10}caso queiramos
manter apenas que seja maior que 6 caracteres sem um limite, removemos o 10 {6,}. Por enquanto
nossa REGEX fica assim /[a-z]{6,10}/
**=>** Logo após, nos vamos testar nossa RGEX, e para isso toda REGEX por ser um objeto tem dispo
nível o método test() esse método vai ser encadeado em nossa REGEX e receber como argumento
a string a ser testado o match, o método test() nos retorna um boolean true ou false.

**OBS:** Lembrando que encapsulando com o circunflexo e o cifrão podemos definir especificamente
a palavra

```JS
const pattern = /^[a-z]{6,}$/
```
}
```JS
const result = pattern.test(username)
```

**}**

==================================================
```JS
const form = document.querySelector('.signup-form')
const usernameInput = document.querySelector('#username')

form.addEventListener('submit', event => {
    event.preventDefault() // Evita o carregamento padrão do form

    console.log(event.target.username.value)// Caso esteja utilizando o react, seria deste modo
    // para capturar o valor armazenado no input do form.
})

const username = '45554enelas'
const pattern = /^[a-z]{6,}$/
/*
const isAMatch = pattern.test(username)

if (isAMatch){
console.log('O teste passasts!') // Utilizando o teste com uma condicional, para manipular o resultado de
} else { // um REGEX que teve sucesso ou não.
    console.log('O testda regex não passou =(')
}
*/

const result = username.search(pattern) // Search é um metodo de string que recebe a REGEX que quermos
// testar, ele vai dar o index de onde o match ocorreu, quando nao acontecer um match o -1 sera
// retornado

console.log(result) // Quando der match nesse caso será 0 pois neste padrão especificamos o match
// No inicio da regex. Caso seja removido de nosso REGEX o circunflexo (^) ai neste caso, se 
// colocarmos alguns numeros antes das letras o indice vai aumentar ja que tiramos a condição
// de dar match apartir do inicio.

```

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
