### ISSUE TITLE
Exercício 01

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#327]
Eu fiz o exercíco atribuindo o calculo aos valores, valor1 e valor2, estou errado? tem algum impedimento para esse uso? 

Obrigado.

```js

const ten = 10 

valor1 = currentYear + ten
valor2 = myAge + ten

console.log(`Em ${valor1}, estarei com ${valor2} anos.`)

```

@Roger-Melo

**Comment by wsn-nunes** [comment]
@renarfreitas  tudo bem? 
se me permite , vou tentar te ajudar.

caso eu esteja errado o professor roger nos ajuda .

os atribuídos valor1 e valor 2 você colocou em uma const ou let ?
se puder coloca os valores atribuídos a currentYear e myAge.

mas o console.log() me parece que está bem elabora.

**Comment by renarfreitas** [comment]
> @renarfreitas tudo bem?
> se me permite , vou tentar te ajudar.
> 
> caso eu esteja errado o professor roger nos ajuda .
> 
> os atribuídos valor1 e valor 2 você colocou em uma const ou let ?
> se puder coloca os valores atribuídos a currentYear e myAge.
> 
> mas o console.log() me parece que está bem elabora.

Nunes, não coloquei nem const nem let para valor1 e valor2... rsrs agora percebi que ambas não eram variaveis declaradas.
Muito obrigado pela ajuda, me abriu os olhos!

**Comment by renarfreitas** [comment]
Nunes, Muito obrigado.

**Comment by Roger-Melo** [comment]
Oi Renar.

Como o @wsn-nunes  colocou, ao declarar uma variável (ou constante), sempre especifique se ela é uma `let` ou uma `const`. 

Pelo que entendi, rolou apenas uma interpretação equivocada. O objetivo deste exercício é fazer você perceber que na string `Em ${valor1}, estarei com ${valor2} anos.`, as palavras `valor1` e `valor2` podem ser substituídas por expressões que envolvem variáveis =)

@renarfreitas

**Comment by renarfreitas** [comment]
Valeu Roger e Nunes!! entendi a proposta do exercicio, e já corrigi!! muito obrigado!
Muito feliz com o curso.
Obrigado.
