### ISSUE TITLE
Resumo da Aula Trabalhando com JSON (Javascript Object Notation) 03-04 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3272]
_**JSON (Javascript Object Notation)**_ significa Notação de Objeto Javascript e é um formato para troca de dados. Seu aspecto é semelhante a um _array_ contendo objetos, mas em realidade trata-se de _string_ formatada de forma a se assemelhar a este, pois assim os dados podem ser transmitidos e posteriormente tratados. Para isto, ele deve ser transformado em um objeto Javascript, o que pode ser feito por meio do objeto embutido (JSON) e o método `.parse()`, que irá converter a informação.
```js
const data = JSON.parse(request.responseTxt)
```
Podemos criar arquivos JSON, usando a extensão _**.json**_. Dentro dele, não é necessário inserir strings, pois fica implícito que ele contém uma string JSON. Assim, iniciamos com a notação de array, dentro do qual colocamos par de chaves. Todas as propriedades e strings contidas dentro de chaves devem estar envoltas em aspas duplas (nos valores de chaves, obedecemos às mesmas regras de objetos javascript).
Todos os objetos JSON devem ser separados por vírgula dentro do arquivo.
```js
[
    {
        "myKey": "My key value",
        "mykey2": 7
    },

    {
        "myKey": "Other value",
        "myKey2": true
    },

    {
        "myKey": "Other value",
        "myKey2": null
    }
]
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. Vamo que vamo, rumo à fluência! 🙌
