### ISSUE TITLE
Resumo da Aula Callback Hell ou Pyramid of Doom 03-05 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3273]
Fazer uma request esperar outra request ser feita é algo comum quando há duas APIs envolvidas, por exemplo, quando se usa os dados obtidos de uma API para fazer requisição a outra API.

Criamos 3 arquivos _.json_ em uma pasta de nome _json_. A idéia é obter os dados destes arquivos, um de cada vez (isto é, terminada a obtenção e exibição de um, obter e exibir o seguinte a ele). Como cada arquivo representa um _endpoint_ diferente, inserimos um parâmetro `url` na função `getTodos()`, substituindo também por este parâmetro o _endpoint_ inserido na abertura da _request_, desta forma, basta apenas informarmos a _url_ no momento da invocação da função `getTodos()`.
```js
getTodos(url, callback) => {  // parâmetro url para troca das endpoints

    bloco de instruções  

    request.open(‘GET’, url) // substituindo a endpoint específica por url

    bloco de instruções
}
```
Precisamos “pegar” o momento no qual sabemos que a _request_ é feita com sucesso (isto é, quando os dados são obtidos) e inserir as novas _requests_. Este momento ocorre quando o valor de resposta da _request_ é verificado (_true_ na condição do `isRequestOk`) e a função _callback_ executada (especificamente na linha `console.log(data)`). Assim, as invocações ficam:

```js
getTodos(‘./json/todos.json’, (error, data) => { 
   bloco de instruções 
   getTodos(‘./json/todos02.json’, (error, data) => {
      bloco de instruções
      getTodos(‘./json/todos03.json’, (error, data) => { 
         bloco de instruções 
      }) 
   })
}) 
```

A indentação gerada por este aninhamento de callbacks é o que leva o nome de Callback Hell ou Pyramid of Doom (inferno de callback ou pirâmide do pesadelo), devido ao fato de este tipo ser de difícil leitura e, consequentemente, difícil manutenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
