### ISSUE TITLE
Aplicação: [Conversor de moedas]

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#3284]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/zolive72/currency-converter

### Maiores dificuldades durante a implementação

Minha dificuldade está mais na escolha dos nomes das funções de Callback do AddEventListener e na refatoração do código. Neste desafio, fiz funcionar a aplicação uma primeira vez sem usar as propriedades dos objetos 'select' que estavam disponível desde o início,  mas quando examinei os objetos 'baseCurrencyContainer' e 'targetCurrencyContainer', vi que tinha propriedades que podiam ser usadas e que deixariam o código mais simples.

### Menores dificuldades durante a implementação

Manipular o DOM, Obter os dados da API e usar o localStorage

**Comment by Roger-Melo** [comment]
Olá @zolive72.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @zolive72!

Parabéns pelo esforço em construir a quarta aplicação do treinamento =)

> ## Minha dificuldade está mais na escolha dos nomes das funções de Callback do AddEventListener e na refatoração do código. Neste desafio, fiz funcionar a aplicação uma primeira vez sem usar as propriedades dos objetos 'select' que estavam disponível desde o início, mas quando examinei os objetos 'baseCurrencyContainer' e 'targetCurrencyContainer', vi que tinha propriedades que podiam ser usadas e que deixariam o código mais simples.

Seus nomes estão específicos, não vi necessidade de grandes ajustes desse tipo. O único cuidado que eu tomaria é deixar apenas camelCase ao invés de inserir snake_case. Isso deixaria o código mais padronizado.

Vc também demonstrou que pegou bem a lógica até aqui, inclusive usou bem o ternário.

Sobre refatoração, nas aulas seguintes vc verá que eu escolhi uma abordagem diferente de armazenamento das moedas. Veja o que vc sente que faz mais sentido para vc.

---

## jQuery

Dentro do `<head>` há uma importação do jQuery. 

Não use jQuery nas aplicações do treinamento. O propósito é treinar suas habilidades com JS puro =)

---

## Local de invocação da getRates

`getRates('USD')` pode ser invocada próximo a outras invocações no final do código. Isso deixa o código mais organizado, pois as invocações de funções/métodos ficam concentradas em apenas um lugar.

```javascript
// antes
getRates('USD');

// ...

baseCurrencyContainer.addEventListener('change', changeBaseCurrency);
targetCurrencyContainer.addEventListener('change', changeTargetCurrency);
amountToConvertContainer.addEventListener('input', calculateConvertedAmount);
```

```javascript
// depois
baseCurrencyContainer.addEventListener('change', changeBaseCurrency);
targetCurrencyContainer.addEventListener('change', changeTargetCurrency);
amountToConvertContainer.addEventListener('input', calculateConvertedAmount);

getRates('USD');
```

---

## Propriedades em objetos do DOM

No código abaixo, `baseCurrencyContainer` é um objeto do DOM em que foi adicionado uma nova propriedade `.rates` que armazenou dados da API.

```javascript
baseCurrencyContainer.rates = localStorageRates
  ? JSON.parse(localStorageRates)
  : await getFetchData(baseCurrency)
```

Para fazer um Biscoito de Água e Sal, vc precisará de 1 pitada de açúcar e 1 pitada de sal. Mas se na hora de pegar esses ingredientes, vc pegar um pacote que contém sal e açúcar misturados e colocar na massa, o biscoito vai tender a ficar com um sabor diferente do esperado, pq no modo de preparo, sal e açúcar deveriam ser adicionados em momentos diferentes, por isso era necessário que eles não estivessem misturados.

O que quero dizer é: prefira organizar certos ingredientes de forma separada. 

O propósito do DOM é ser uma representação estrutural do documento (página). 

Adicionar dados em uma estrutura que não foi planejada para conter outros tipos de dados é uma quebra de princípio. E essa quebra não traz benefícios, pq vc está desorganizando seu código ao tentar combinar tipos de informações que deveriam estar separadas, pois são usadas para propósitos distintos. Não conheço um caso onde essa combinação seria benéfica.

Não sei se pra fazer Biscoito de Água e Sal caseiro é necessário adicionar sal e açúcar em momentos diferentes, foi só um exemplo.

---

## let currencies

A `let currencies` não sofre reatribuição de valor no decorrer do código, então ela pode ser uma `const`.

```javascript
// antes
if (!baseCurrencyContainer.childElementCount) {
  let currencies = Object.keys(baseCurrencyContainer.rates);
  createOptions(baseCurrencyContainer, baseCurrency, currencies);
  createOptions(targetCurrencyContainer, 'BRL', currencies);
}
```

```javascript
// depois
if (!baseCurrencyContainer.childElementCount) {
  const currencies = Object.keys(baseCurrencyContainer.rates);
  createOptions(baseCurrencyContainer, baseCurrency, currencies);
  createOptions(targetCurrencyContainer, 'BRL', currencies);
}
```

---

Como mencionei acima, nas aulas seguintes você verá formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by zolive72** [comment]
Obrigado Roger pelas observações e explicações que me ajudam sempre bastante a melhorar o código.
Em relação ao tópico  **Propriedades em objetos do DOM**, depois de ter enviado para você a issue inicial da aplicação, continuei tentando melhorar o código inclusivo para não usar a **baseCurrencyContainer.rates** e sim a **rates** .

Usei também **o construtor Option** para criar as opções.  Creio que é uma outra possibilidade para criar as opções.

Antes:
```
const createOptions = (currencyContainer, currencySelected, currencies) =>
  currencies.forEach(currency =>
    currencyContainer.innerHTML += currency === currencySelected
      ? `<option value = ${currency} selected>${currency}</option>`
      : `<option value = ${currency}>${currency}</option>`
  );
```

Depois:
```
const createOptions = (currencyContainer, currencySelected, rates) => 
  Object.entries(rates).forEach(([currency, rate], index) =>
    currencyContainer[index] = currency === currencySelected
      ? new Option(currency, rate, false, true)
      : new Option(currency, rate)
  );
```

Mais uma vez obrigado, Roger pela observações. Estou ancioso por ver a correção dos exercícios. 👍 

Atenciosamente
Olivier

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí, legal explorar outras possibilidades, hahah.

No que precisar, é só abrir uma nova issue =)
