### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by developsouza** [roger-melo-treinamentos/curso-de-js-roger-melo#3293]
Também já tinha noção de operadores estritos, porém, não sabia que é uma boa prática utilizá-los prioritariamente, pois não tinha essa mentalidade antes. Aula excepcional.

**Comment by Roger-Melo** [comment]
Boa @developsouza, rumo à fluência! 🔥
