### ISSUE TITLE
Duvida Aula 02-03 | Funções Vs Método

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#33]
Bom dia Roger!
Acompanhando a aula percebi uma leva diferença, poderia me explicar mais sobre ?
Pois fazendo isso o valor não é mostrado no console do navegador igual na aula.

![image](https://user-images.githubusercontent.com/57417305/93208583-2ab32e00-f733-11ea-853b-b7ad5ce4f687.png)

**Comment by Roger-Melo** [comment]
Oi Gohara.

Pode subir o código no github e me mandar o link para eu dar uma olhada?

@GoharaJunior

**Comment by GoharaJunior** [comment]
### Modulo Funções e Métodos - Aula 02-03-Funções Vs Método

O trecho do código é esse e fica conforme a print que enviei.

```javascript
const name = 'Roger'

// Funções
const sayHi = () => 'Oi'

const greet = sayHi()
console.log(greet)

// Métodos
const nameInUpperCase = name.toUpperCase()
console.log(nameInUpperCase)
```

[aula-02-03-funcoes-vs-metodos.zip](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/5228678/aula-02-03-funcoes-vs-metodos.zip)

**Comment by Roger-Melo** [comment]
Oi Gohara!

Acho que entendi a dúvida, vamos lá =D

> Pois fazendo isso o valor não é mostrado no console do navegador igual na aula.

Observe que no `index.html`, o `src` do `<script>` está buscando um diretório `03-funcoes-e-metodos`, depois um diretório `aula-02-03-funcoes-vs-metodos`, e dentro desse último diretório, está buscando o `app.js`.

```html
<script src="/03-funcoes-e-metodos/aula-02-03-funcoes-vs-metodos/app.js"></script>
```

Então quando baixei os arquivos, apenas ajustei o valor do src para buscar, no mesmo diretório do `index.html`, o `app.js`:

```html
<script src="./app.js"></script>
```

O que o `./app.js` está dizendo é, basicamente: "à partir de onde este arquivo (index.html) está localizado, procure por um arquivo app.js".

Como o `index.html` e o `app.js` estão localizados no mesmo nível, não foi preciso eu especificar diretórios no valor do `src`.

Feito isso, o erro `GET http://127.0.0.1:5500/03-funcoes-e-metodos/aula-02-03-funcoes-vs-metodos/app.js net::ERR_ABORTED 404 (Not Found)` não foi mais exibido no console.

Esse erro estava sendo exibido para você?

> Acompanhando a aula percebi uma leva diferença, poderia me explicar mais sobre ?

Funções e métodos são blocos de código que podem ser invocados para executar um pedaço de código.

O que diferencia um método de uma função, é a forma como os invocamos e onde (ou como) eles são declarados.

Para declarar uma função, eu uso a notação `const [nome_da_funcao] recebe uma função`, como abaixo:

```javascript
const sayHi = () => 'Oi'
```

Nas aulas seguintes, você verá como declarar um método. Basicamente, a forma de declaração é a maior diferença entre métodos e funções.

Um método é uma função que pertence a um objeto:

```javascript
const myObj = {
  myMethod: () => {}
}
```

Se você não ainda não entendeu a sintaxe acima, não se preocupe. Nas aulas seguintes eu explico o que são objetos =)

Uma outra diferença de sintaxe é que para invocar uma função, eu insiro o nome dela seguido de um par de parênteses,

```javascript
sayHi() // 'Oi'
```

e para invocar um método, como um método é uma função que pertence a um objeto, é preciso inserir o nome do objeto, ponto, e a invocação do método:

```javascript
myObj.myMethod()
```

Mas como eu disse, nas aulas posteriores eu mostro o que são objetos. Não se preocupe se não entendeu a sintaxe deles por agora =)

Ficou mais claro?

@GoharaJunior

**Comment by GoharaJunior** [comment]
Entendi perfeitamente, muito obrigado!

**Comment by GoharaJunior** [comment]
Roger aproveitando essa issues, queria uma dica sobre estudo.

Eu como é muita coisa nova você acha que compensa voltar os módulos até fixar bem ? 

Pois eu estou tendo muita dificuldade em montar a lógica, mais por outro lado a leitura está bem melhor.

**Comment by Roger-Melo** [comment]
As revisões são necessárias para você não esquecer o que estudou. A intensidade das revisões depende dos seus resultados nos exercícios.

Durante as correções dos exercícios, tem tido uma taxa de acertos de mais de 80%?

@GoharaJunior

**Comment by GoharaJunior** [comment]
Está sendo menos em algumas etapas

**Comment by Roger-Melo** [comment]
Em quais exercícios teve mais dificuldades?

Pode colar o código deles aqui e falar as dúvidas que te ajudo =)

@GoharaJunior

**Comment by GoharaJunior** [comment]
Eu vou postando em novas issues pra ficar melhor. 

Obrigado até aqui

**Comment by Roger-Melo** [comment]
Show. Vou fechar essa issue mas, no que precisar, estou à disposição =)
