### ISSUE TITLE
Revisão raio-x

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#330]
Roger tenho uma dúvida na revisão raio-x. Cheguei na aplicação quiz-interativo. O recomendado é realizar com você a aplicação (assistir toda etapa), e depois ir refazendo todos os exercícios desde a primeira etapa do treinamento pra então ai refalizá-la sozinho?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi gabriel.

Como você já está a mais tempo no treinamento, recomendo a revisão raio-x apenas se tiver dificuldades em [construir o quiz sozinho](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js).

Se não é o caso, construa a aplicação e envie ela para a análise =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Entendido professor, obrigado mais uma vez!
