### ISSUE TITLE
Resumo da Aula O evento submit - Aula 01-03 da etapa 06

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3302]
========== O EVENTO SUBMIT ==========

Na etapa passando, quando queriamos adicionar um evento de clique no elemento, nós atrelavamos um listener de evento diretamente que seria clicado. Só que quando queremos escurar o envio de um formulário, ao invés de atrelarmos o listener de evento no botão de formulário, nós atrelamos ao <form> em geral. Porque no fim das constas o que está sendo enviado é o form e não o botão.

Nesse caso o que queremos é o submit desse form, o envio dele. Para isso vamos referenciar o formulário e passar um listener de evento nele.

O listener de evento espefícifo para formulários é o evento 'submit'. Esse evento será disparado quando o botão do form for clicado, ou se o input estiver selecionado o usuário presisonar a tecla 'enter'.

Um comportamento padrão do evento 'submit' é que sempre que o formulário é enviado, o evento 'submit' recarrega toda a página HTML. Em muitos casos esse comportamento não será desejado e portanto podemos impedir esse reload através do método 'preventDefault()' do objeto event.

Para obtermos a informação passada no input do formulário, primeiro devemos referenciar esse input, para podermos obter informações de elemento. 
   
1ª FORMA DE OBTER O VALOR DO INPUT: O input contém uma propriedade chamada 'value', essa propriedade recebe o valor que o usuário digiou no input, portanto, através dela conseguimos visualizar o que foi inserido.

2ª FORMA DE OBTER O VALOR DO INPUT: Quando um input dentro de um formulário contém um ID/NAME, nós podemos obter a referência desse input através da referência do form e do ID/NAME do input. Se passarmos um ID/NAME como uma propriedade do elemento form, o JS irá obter o elemento que contém esse ID/name dentro do form. E para obtermos o valor basta encadermos a propriedade value.

3ª FORMA DE OBTER O VALOR DO INPUT: Esse última forma pode ser útil caso esteja trabalhando com formulários dentro da biblioteca ReactJS

```.js
const form = document.querySelector('.signup-form')
const usernameInput = document.querySelector('#username')

form.addEventListener('submit', event => {
   event.preventDefault() // prevenindo reload da página

   usernameInput.value // valor de input através de value
   form.username.value // procurando input com ID/NAME username dentro do form e obtendo valor
   event.target.username.value // obtendo valor do input com ID/NAME, ajuda no ReactJS
})
```

**Comment by Roger-Melo** [comment]
Boa @santos2408, rumo à fluência! 🔥
