### ISSUE TITLE
sou da turma de maio de 2021 e estou com duvida sobre oque acontece após 1 ano de treinamento 

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#3303]
### Etapa da aula

1

### Nome da aula

Aula inaugural - Aula 0-0

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/733512

### Descreva a dúvida

sou da turma de maio de 2021, tive problemas pra começar a estudar bem e por volta de setembro-outubro o professor Roger recomendou que eu refizesse o treinamento pois minha base JS estava muito insuficiente praquelas etapas(parei na aplicação do quiz).

refiz o treinamento, focando bastante em revisões e consegui sem muita dificuldade fazer as duas primeiras aplicações grandes(quiz e todo list), porém comecei a estudar para concurso público em fevereiro e meus estudos com JS pararam de novo. estou com 46% concluído, mas sei que não chego nem nos 70% com o pouco de tempo que me falta pra completar um ano que comprei o treinamento. Então queria saber se depois de maio ainda terei acesso a alguma ajuda ou a plataforma com as aulas.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208!

O acesso e suporte ao treinamento são válidos durante o tempo que vc precisar =)

O importante pra mim é que vc conte comigo pra chegar na fluência em JavaScript, independente de quanto tempo isso leve.

Se restar alguma dúvida, é só dar o toque =)

**Comment by CarlosHenrique2208** [comment]
professor, muito obrigado mesmo, foi através do seu treinamento que estou sempre com prazer em estudar sobre programação. Espero muito conseguir meu primeiro emprego como programador esse ano e poder fazer minhas próprias aplicações com JS. Enfim, muito obrigado mesmo por todo o suporte!!
