### ISSUE TITLE
Vídeo ATER não abre

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#3304]
### Etapa da aula

1

### Nome da aula

Vídeo ATER

### Link da aula

Vídeo ATER

### Descreva a dúvida

Boa noite Roger, estou tentando ver o vídeo do método ATER e diz que ele é privado, não consigo acessar. Houve algum informe de email a respeito ou foi um erro mesmo?

Obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rafaelpradoj.

O treinamento passa por constantes atualizações e, com isso, vídeos são substituídos.

Uma possível solução para não ter esse tipo de problema é acessar o conteúdo através da plataforma, e não diretamente no youtube.

No caso do vídeo do ATER, vc pode acessar [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) o post na plataforma que contém o vídeo =)

Sacou a ideia?

**Comment by rafaelpradoj** [comment]
Bom dia!

Agora foi, eu estava com o vídeo antigo salvo, por isso não estava indo. Obrigado!!!

**Comment by Roger-Melo** [comment]
Isso mesmo =)

Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
