### ISSUE TITLE
Uso de callback no exercício 6 da Etapa 11

### ISSUE THREAD

**Issue by zolive72** [roger-melo-treinamentos/curso-de-js-roger-melo#3309]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios (exercício 6) - Aula 02-01 

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1181723

### Descreva a dúvida

Boa tarde Roger, tudo bom ?
Fazendo uma revisão, percebi que na correção do exercício 6, foi invocado a **myFunc** com uma função de callback em argumento. Em um primeiro momento, fiz a invocação só com os argumentos : myFunc( 'Hello', [], {}). Teria algum motivo para invocar com uma função de callback neste exercício?

```
const myFunc = (param1, param2, param3) => {
  const isSomeParameterUndefined = [param1, param2, param3].includes(undefined);
  return isSomeParameterUndefined
    ? 'A função deve ser invocada com 3 argumentos'
    : 'A função foi invocada com 3 argumentos'
}

console.log(myFunc(() => 'Hello', [], {}));
```
Minha invocação:
```
console.log(myFunc( 'Hello', [], {}))
```

Agradeço desde já sua atenção. 
Olivier

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @zolive72!

> ## Teria algum motivo para invocar com uma função de callback neste exercício?

Não. A declaração da função foi inserida como argumento da invocação de `myFunc` apenas para que `param1` recebesse um valor aleatório. 

Todos os argumentos que `myFunc` recebeu foram valores aleatórios =)

**Comment by zolive72** [comment]
Bom dia Roger,
Obrigado pelo retorno. Revendo o código hoje de manhã, compreendi que eu estava fazendo confusão e que na invocação da função **myFunc** tem 3 argumentos que são respectivamente:

1. () => 'Hello'
2. []
3. {}

Obrigado Roger. 
Tenha um bom fim de semana.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso mesmo =)

No que precisar, estou à disposição 🙏🏻
