### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by rodrigoljpereira** [roger-melo-treinamentos/curso-de-js-roger-melo#331]
Olá professor, não é que eu tenha errado o exercicio, mas tenho reparado que em alguns deles, eu tenho conseguido resolver usando tudo que foi passado até aqui, porem, vejo que você resolve de outra forma e chega no mesmo resultado. 

Quanto ao exercicio 05 que é a minha duvida, eu resolvi da seguinte forma:
```
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

let positiveNumber = 0
let negativeNumber = 0
let numbers = 0

const checkingPositiveNumbers = function (numbers, positiveNumber, negativeNumber) {
  
  let messenger = `O array "randomNumbers" possui ${numbers} números, sendo ${positiveNumber} positivos e ${negativeNumber} negativos.`

  return messenger
      
}

for(let i = 0; i < randomNumbers.length; i++){
    if(randomNumbers[i] > 0){
      positiveNumber++
    }

    if(randomNumbers[i] < 0){
      negativeNumber++
    }

    numbers++
}

console.log(checkingPositiveNumbers(numbers, positiveNumber, negativeNumber))

```
Gostaria de lhe perguntar, qual o impacto negativo que esse meu código pode gerar na aplicação, uma vez que sua resolução é completamente diferente da minha mesmo eu tendo usado os mesmos recursos que o senhor utilizou, como For, função com parametros etc. E se até aqui existe algo que eu deva me atentar?

Desde já agradeço a atenção!!

Obs: Mesmo com a duvida, já corrigi meu código para o mostrado na correção!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rodrigo.

Antes de responder, deixa eu dar algumas dicas.

Quando abrir uma issue, copie e cole o nome exato da aula no título da issue. Isso faz com que eu localize a aula certa e te ajude mais rápido. Já consertei o título dessa issue.

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, basta inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

let positiveNumber = 0
let negativeNumber = 0
let numbers = 0
```

Ele ficará assim:

```javascript
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

let positiveNumber = 0
let negativeNumber = 0
let numbers = 0
```

---

Não há problema em resolver de outra forma, desde que a forma que você resolveu aplique os mesmos princípios da resolução mostrada.

A resolução mostrada na correção contém alguns princípios de lógica e qualidade de código.

- Para obter o número de itens de um array, não é necessário declarar uma `let` e incrementar ela à cada vez que o for é executado, já que arrays contém a propriedade `length`.

- Não é necessário declarar duas verificações para checar se o número é positivo ou negativo (se ele não é positivo, só pode ser negativo - considerando, claro, que o array do exemplo não contém 0).

- Outro ponto de atenção é que geralmente, não é uma boa ideia uma função ter muitos parâmetros, por que isso torna ela mais difícil de testar. Por isso eu evito ao máximo declarar funções com 3 parâmetros. Em etapas mais avançadas, eu falarei sobre testes. Mas é bom que você já fique ligado nisso. 

---

Tome cuidado também com as linhas em branco em excesso.

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo esse princípio eu removeria a primeira a e última linhas em branco da `checkingPositiveNumbers`. É uma convenção que a primeira e a última linha de um bloco de código estejam preenchidas. Isso deixa a leitura mais fluida, sem saltos desnecessários entre linhas.

E um último ponto de atenção é que `checkingPositiveNumbers` tem um nome que não condiz com o que ela faz. O que ela está fazendo: retornando uma mensagem. O que o nome diz que ela está fazendo: checando números positivos.

Por isso eu indico que, no começo, você seja espartano com o método e tente absorver o que está por trás do que eu estou mostrando.

Fez sentido os pontos que observei acima?

@rodrigoljpereira

**Comment by rodrigoljpereira** [comment]
Bom dia professor. Sim, os pontos fazem sentido. 

Agora vou reassistir as correções e aplicá-las. Com essas novas informações posso ve-las com outros olhos, deixando de lado alguns vícios que trago de outros cursos. Agradeço imensamente a atenção.

Talvez esses pontos que você comentou sobre convenções da linguagem como por exemplo as linhas em branco, o fato de não ser uma boa usar mais que um ou dois parâmetros em funções, etc, pudessem ser abordados nos vídeos. Por enquanto Obrigado por seu tempo. Seguirei com as correções!! Grande abraço.

**Comment by Roger-Melo** [comment]
Vão ser abordados em etapas mais avançadas.

Não faz sentido falar sobre isso para alguém que está começando a aprender o que são funções. Uma coisa de cada vez.

Mencionei os pontos acima justamente por que você já tem conhecimento na linguagem. Geralmente quem não tem, segue à risca o que mostro na correção.

@rodrigoljpereira

**Comment by rodrigoljpereira** [comment]
Ok Roger. Obrigado!! Como mensionei estou estudando agora seguindo as dicas e apontamentos em sua resposta, o que está me ajudando bastante. Obrigado!! Duvidas completamente esclarecidas rsrs!!

**Comment by Roger-Melo** [comment]
Legal @rodrigoljpereira.

Já que ficou mais claro, vou fechar a issue. No que eu puder ajudar em sua jornada rumo à fuência, é só dar o toque =)
