### ISSUE TITLE
Resumo da Aula 01-03 Template HTML e checando as respostas da etapa 07

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3317]
Como estamos focados no java script, vamos pegar no repositório esse template já estilizado
com algumas classes bootStrap.

**(Template HTML checando as respostas) {**
**=>** Em nosso quiz, vamos checar as respostas dada e devolver uma nota, para isso..

**=>** Primeiro vamos referenciar o form através de sua classe .quiz-form

```JS
const form = document.querySelector('.quiz-form')
```

**=>** Vamos também criar um array com o mesmo numero de perguntas, e este array vai conter todas
as respostas corretas.

```JS
const correctAnswers = ['B','B','B','B']
```

**=>** se nos formos inspecionar por exemplo a primeira pergunta, podemos notar que a pergunta e
as 2 opções de resposta, estão dentro de um container div com a class = "my-5" esse container,
contem outros 2 containers div com a class = "form-check my-2 text-white-50" cada uma dessas
divs contem um label com a class="form-check-label" e dentro dssa label, nos temos em cada um
o input do tipo radio redondo e o principal aqui para nosso exemplo, o name do input que esta
dentro do label ele tem o name="inputQuestion1". Com isso nos temos uma referencia de como aces
sar o valor armazenado do questionário em cada ratio para comparar com a nossa array corr
ectAnswers.

**=>** Com o nosso form referenciado vamos adicionar um listener de eventos que vai monitorar o even
to 'submit' e recebera como parâmetro de sua função callback o event, vamos com o event encadear
o preventDefault() para evitar o carregamento padrão do form.

```JS
form.addEventListener('submit', event => {
    event.preventDefault()
}
```

**=>** Ainda dentro do bloco de nosso listener de eventos, vamos criar uma variável do tipo let
porque como ela vai armazenar o resultado das respostas corretas, sofrerá mudança o que ocasi
onaria um erro caso declarássemos uma const.

```JS
form.addEventListener('submit', event => {
    event.preventDefault()

    let score = 0
}

```

**=>** Vamos ainda dentro do bloco de nosso listener de eventos e logo após criar nossa variável
que armazena o resultado. Criar uma const userAnswers, que será nossa array que vai armazenar
a entrada das respostas para comparar com a array correctAnswers. Como já mencionado, esses
 valores das respostas virão do name="inputQuestion1" do input através do form referenciado, encadeado no nome
 do input o inputQuestion1 e finalizando encadeando com o value pra nos retornar o valor ar-
 mazenado nesses input.

```JS
form.addEventListener('submit', event => {
    event.preventDefault()

    let score = 0
    const userAnswers = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value,
    ]
```
 **=>** Vamos agora checar as respostas encadeando as respostas do usuário que foram armazenadas
 no userAnswers e encadear de um forEach que receberá como argumento o userAnswer e o index, 
 para ser aplicados em uma condicional onde caso o item iterado e entregue como argumento do
 userAnswer for igual ao elemento do correctAnswer referenciado a através do índice entregue
 pelo forEach por cada elemento iterado. Pode-se comparar e caso esteja correto adiciona 25
 pontos, tomando por base um total de 100 pontos dividido por quatro perguntas.

```JS
userAnswers.forEach((userAnswer, index) => {
        if (userAnswer === correctAnswers[index]) {
            score += 25
            
        }
        
    })
```
**}**

(Codigo final) {
```JS
const form = document.querySelector('.quiz-form')

const correctAnswers = ['B','B','B','B']

form.addEventListener('submit', event => {
    event.preventDefault()

    let score = 0
    const userAnswers = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value,
    ]
    userAnswers.forEach((userAnswer, index) => {
        if (userAnswer === correctAnswers[index]) {
            score += 25
            
        }
        
    })
    console.log(score)
})
```
}

**Comment by Roger-Melo** [comment]
Excelente @EneasFeynlinus, rumo à fluência! 🎯
