### ISSUE TITLE
Aplicação: [Quiz-Interativo]

### ISSUE THREAD

**Issue by homeromeirelesjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#332]
- O link da sua versão do quiz;
[Link para o quiz](https://github.com/homeromeirelesjunior/quiz-interativo-homero-meireles)

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
Bom, tive dificuldades em algumas partes na criação de elementos no DOM. Um pouco por falta de prática. Tentei aplicar diretamente class através do classList.add() e não deu certo.

- Quais foram as suas menores dificuldades durante a execução desse exercício.
Quanto a lógica como um todo, pensei até em implementar uma mensagem de acordo com a pontuação mas achei que ficaria poluído demais. No mais é isso, valeu!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @homeromeirelesjunior.

Passando para dizer que sua issue foi visualizada e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Homero.

Parabéns pelo esforço em construir a primeira aplicação dentro do CJRM =)

Antes da análise, deixa só eu dar uma dica.

O repositório é [este](https://github.com/homeromeirelesjunior/quiz-interativo-homero-meireles), certo?

Para inserir a url de um repositório em issues do GitHub, basta colar o link desta forma: `[texto do link](url)`. A `url` entre os parênteses deve ser a da página do respositório (https://github.com/homeromeirelesjunior/quiz-interativo-homero-meireles). Editei essa parte na issue que foi aberta acima.

Vou deixar abaixo a análise da aplicação, segundo alguns critérios:

## Usabilidade

### Local da exibição dos pontos

O print abaixo foi tirado logo após o envio do form:

![image](https://user-images.githubusercontent.com/29297788/113496029-f84d0080-94cb-11eb-9de7-eed5dc11ebbb.png)

Quando o form é enviado, os pontos são exibidos na parte inferior da tela e boa parte do feedback visual fica comprometida. Uma alternativa seria exibir os pontos próximo do local para onde o usuário está olhando quando envia o form (botão).

Nas aulas seguintes eu mostro uma forma de inserir os pontos na tela, mas fique atento à isso. Ao inserir um elemento na tela, certifique-se de que ele está bem posicionado em relação ao olhar do usuário.

## Lógica

### Prefira usar `===` ao executar comparações

Na [aula 04-03 da etapa 01](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/751262) eu mencionei que quando o `==` é usado, ele executa conversão de tipos.

Então, para não ter imprevisibilidade no momento de executar uma comparação, prefira usar o operador de comparação estrita (`===`).

## Organização de código

### Evite pendurar variáveis globais no `window`

No código abaixo, observe que `correctAnswers` foi declarada sem o uso da palavra-chave `const`:

```javascript
correctAnswers = ['C', 'B', 'A', 'C', 'A']

const form = document.querySelector('.quiz-form')
const paragraph = document.createElement('p')
```

Se logo abaixo da `correctAnswers` um `console.log(window.correctAnswers)` for executado, `["C", "B", "A", "C", "A"]` é exibido.

Isso acontece por que quando uma variável/let/const é declarada sem uma dessas palavras-chave, ela é automaticamente pendurada no objeto global (`window`, nesse caso). E isso pode trazer problemas, já que valores em escopo global podem ser alterados em qualquer parte da aplicação, incluindo por scripts de terceiros. Há aulas sobre isso em etapas mais avançadas do treinamento, mas é bom que você já fique ligado.

### Cuidado para não esquecer `console.log`'s

O `console.log` é útil apenas no momento em que você está desenvolvendo a aplicação. Sempre que enviar código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele `console.log` também) xD

### Local de declaração/manipulação de variáveis

Faz mais sentido deixar as manipulações de `paragraph` concentradas em um só lugar no código. Assim você evita ter que procurar em partes diferentes um código que poderia estar "agrupado" e mais facilmente acessível.

Então ao invés de estilizar o `paragraph` no topo do código, você pode estilizá-lo próximo à manipulação de texto e inserção dele na tela:

```javascript
form.addEventListener('submit', event => {
  // ...

  paragraph.innerText = `A pontuação final foi de: ${score} pontos!`
  paragraph.style.color = "#FFA937";
  paragraph.style.textAlign = "center";
  paragraph.style.fontSize = "20pt";
  
  form.appendChild(paragraph)
})
```

É uma convenção posicionar o armazenamento de elementos do DOM no topo do código. Então `correctAnswers` pode ser declarada logo após `form` e `paragraph`:

```javascript
const form = document.querySelector('.quiz-form')
const paragraph = document.createElement('p')

const correctAnswers = ['C', 'B', 'A', 'C', 'A']
```

### Nomes de variáveis e funções

`paragraph` é um nome pouco descritivo. Prefira descrever o que o elemento contém. 

Como essa const contém a pontuação final, eu a nomearia como scoreContainer, finalScoreContainer ou trocaria o Container por El (que é uma abreviação de "element").

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos. 

É uma convenção que a primeira e a última linha de um bloco de código esteja preenchida. Isso deixa a leitura mais fluida, sem saltos desnecessários entre linhas. Por isso, eu removeria a primeira e última linha em branco do bloco do callback do envio do form e também removeria a última linha em branco do bloco do callback do forEach.

---

Novamente, parabéns por chegar até aqui @homeromeirelesjunior =)

Sobre a dificuldade com o `classList.add()`, eu teria que ver o código para te ajudar a descobrir o que está acontecendo.

Enquanto isso, fez sentido os pontos que mencionei?

**Comment by homeromeirelesjunior** [comment]
Olá, Roger! Respondo pelo email ou pelo issue? Se estiver errado, me aponte
que dá próxima vez tentarei fazer da forma correta.

Obrigado pelo feedback, fico perplexo como uma pessoa mais experiente
consegue detectar tantos pontos em um código relativamente pequeno,
obrigado mesmo pelo feedback.

Minha ideia era usar o createElement e inserir uma class nesse através do
classList.add(). Porém não tava dando certo.

Vou me atentar aos pontos que você citou, novamente obrigado pelo feedback.

Em sáb, 3 de abr de 2021 23:12, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
@homeromeirelesjunior pode responder as issues pelo GitHub ou por e-mail (eu acho mais fácil responder pelo github mesmo) =)

Já que ficou mais claro, vou fechar essa issue. Mas no que precisar, é só abrir uma nova. Conte comigo para chegar na fluência! 👊🏻
