### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by almir05** [roger-melo-treinamentos/curso-de-js-roger-melo#3321]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/almir05/cjrm-weather-app

### Maiores dificuldades durante a implementação

Tive um pouco mais de dificuldade para entender os retornos das funções async/await e como obter os dados encapsulados da promise em outra função.

### Menores dificuldades durante a implementação

Inserir os dados no DOM, nomear variáveis, destructuring, trocar o if/else por um operador ternário.

**Comment by Roger-Melo** [comment]
Olá @almir05!

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ## Tive um pouco mais de dificuldade para entender os retornos das funções async/await e como obter os dados encapsulados da promise em outra função.

Nessa aplicação, um dos pontos importantes era treinar async/await mesmo. Apesar da dificuldade listada, vc demonstrou ter se saído bem =)

Para aproveitar um valor que está dentro de uma função `async`, vc pode:

1) fazer essa função async retornar o valor e invocar essa função dentro de uma outra função async;
2) invocar uma função dentro da função async e inserir o valor como argumento. Neste caso, se a operação assíncrona acontece antes da invocação da função, a função invocada não precisa ser async.

Exemplo do caso 1:

```javascript
const getTodos = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos')
  return res.json()
}

const logTodos = async () => {
  const todos = await getTodos() // 👈🏻 getTodos invocada dentro de outra função async
  console.log(todos)
}

logTodos()
```

Exemplo do caso 2:

```javascript
const logTodos = todos => console.log(todos)

const getTodos = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos')
  const todos = await res.json()
  logTodos(todos) // 👈🏻 todos foi atribuído para o parâmetro "todos" da declaração de logTodos
}

getTodos()
```

Sacou a ideia?

---

## Alternativa a `cityCardIsNotDisplaying`

Se vc quiser, pode deixar o nome dessa const um pouco mais curto mas transmitindo a mesma ideia:

```javascript
// antes
if (cityCardIsNotDisplaying) {
  cityCard.classList.remove('d-none')
}
```

```javascript
// depois
if (thereIsNoCityCard) {
  cityCard.classList.remove('d-none')
}
```

---

## `handleCityCard`

Lidar com o card da cidade é apenas uma das ações que a função `handleCityCard` desencadeia.

Considerando isso, vc pode nomeá-la como `handleFormSubmit` ou `handleCityFormSubmit` (se sentir a necessidade de ser mais específico).

```javascript
// antes
cityForm.addEventListener('submit', handleCityCard)
```

```javascript
// depois
cityForm.addEventListener('submit', handleFormSubmit)
```

Uma outra abordagem possível é remover `handleFormSubmit` e deixar `showCityCard` referenciada diretamente como callback do submit do form. 

Nessa abordagem, ao invés de deixar várias invocações de funções dentro de `handleCityCard`, as invocações ficariam distribuídas pela aplicação (dentro das funções).

Olha só:

```javascript
// antes
const handleFormSubmit = async event => {
  event.preventDefault()

  showCityCard()
  setCityCardData()
  scrollPage()

  cityForm.reset()
}

cityForm.addEventListener('submit', handleFormSubmit)
```

```javascript
// depois
const scrollPage = () => {
  // ...
}

const setCityCardData = async () => {
  // ...
  
  scrollPage()
  cityForm.reset()
}

const showCityCard = event => {
  event.preventDefault()
  
  // ...

  setCityCardData()
}

cityForm.addEventListener('submit', showCityCard)
```

Essas funções executam efeito colateral (manipulação de DOM), então, do ponto de vista funcional, não há problemas em invocá-las entre si, e vc elimina uma função (handleFormSubmit). 

Mas vai do seu feeling. Veja se essa forma de organizar as invocações faz sentido pra vc =)

---

## Destructuring

O destructuring do objeto retornado da API pode ser mais conciso.

```javascript
// antes
const setCityCardData = async () => {
  const cityCardData = await getCityCardData()

  const {
    timeIcon,
    LocalizedName,
    WeatherText,
    Temperature,
    IsDayTime } = cityCardData

  // ...
}
```

```javascript
// depois
const setCityCardData = async () => {
  const { timeIcon, LocalizedName, WeatherText, Temperature, IsDayTime } = 
    await getCityCardData()

  // ...
}
```

Essa modificação também não é decisiva. Apenas economiza algumas linhas, então veja se em termos de legibilidade o saldo pra vc é mais negativo ou positivo.

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço. Sua aplicação tem poucas observações e nenhum ajuste decisivo =)

As observações fizeram sentido?

**Comment by almir05** [comment]
Olá @Roger-Melo 

As observações fizeram sentido sim, curti a parte de referenciar a `showCityCard` como callback do submit do form e de evitar criar uma const `cityCardData` pra fazer o destructuring, eu estava mesmo achando que minha aplicação estava com linhas demais.

Obrigado por mais uma análise e até a próxima! :raised_hands:

**Comment by Roger-Melo** [comment]
Massa! =D

No que precisar, é só abrir uma nova issue, ok? =)
