### ISSUE TITLE
Aplicação: [Quiz_Interativo]

### ISSUE THREAD

**Issue by PatrickTav** [roger-melo-treinamentos/curso-de-js-roger-melo#3327]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/PatrickTav/Quiz-cjrm

### Maiores dificuldades durante a implementação

Tendo ainda como dificuldade fazer com que não apareça dublicada se apertar duas vezes em enviar e tambem que se o usuário não escolher nem uma resposta, o submit não ser enviado porem, a pontuação conta e isso que quero evitar 

### Menores dificuldades durante a implementação

O desenvolvimento como html e com o css, o js tive duvidas porem consegui sanar porem apenas as dificuldades acima tive diiculdades à mais

**Comment by MivlaM** [comment]
Olá @PatrickTav.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by MivlaM** [comment]
Olá, @PatrickTav.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Fazer com que não apareça dublicada se apertar duas vezes em enviar e tambem que se o usuário não escolher nem uma resposta, o submit não ser enviado porem, a pontuação conta

Vou comentar mais abaixo sobre essas dificuldades, mas o mais importante para a aplicação você já fez, que é fazer funcionar =)

---

## Boas decisões

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Isso dá mais legibilidade ao ler a expressão `answer === correctAnswers[index]`.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Comentários no código

Não é uma regra, mas evite comentários.

```js
if (answer === "") {
  alert(`Marque uma opção da pergunta antes de prosseguir`); //Implementar feature para impedir de continuar se não marcar a pergunta certa
}
```

No trecho acima, você usou um comentário para indicar uma ideia. Mas, comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Usabilidade

Ao repousar o mouse sobre o botão de envio, o ideal é que o cursor do mouse mude para a "mãozinha", indicando para o usuário um possível clique. Você pode fazer isso adicionando `cursor: pointer` no css do button.

Uma coisa que vc pode fazer para melhorar a usabilidade é deixar o total de perguntas mais explícito e o usuário mais consciente do progresso dele no quiz em relação à pontuação total. Você pode fazer isso com uma mensagem indicando a pontuação com porcentagem ("você acertou 50%") ou inserindo uma barra e pontuação total do quiz em sua mensagem após a quantidade de acertos, exemplo: "Você acertou 2 perguntas, sua pontuação é 50/100 pontos".

---

## Inputs desmarcados por padrão

Não é necessário usar alert na aplicação, o alert pode irritar o usuário. Ao invés de exibir quatro alerts, prefira esperar o usuário marcar as opções que ele acredita serem as corretas e exibir apenas uma única mensagem de pontuação final, porque assim você torna a experiência do usuário mais agradável. 

Para evitar o uso do alert, sugiro que antes do usuário selecionar as alternativas, é bom deixar a primeira alternativa de cada pergunta marcada por padrão. Para fazer isso, basta inserir o atributo checked no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## forEach

Uma outra sugestão é manter dentro do forEach apenas a lógica de calculo de pontos e relacionadas, assim o entendimento do `forEach` fica mais claro. Veja o exemplo abaixo: 

```js
//antes
answers.forEach((answer, index) => {
  if (answer === "") {
  alert(`Marque uma opção da pergunta antes de prosseguir`); //Implementar feature para impedir de continuar se não marcar a pergunta certa
  }
  if (answer === correctAnswers[index]) {
    pontuation += 25;
    questions += 1;
  }
});
```

```js
//depois
answers.forEach((answer, index) => {
  if (answer === correctAnswers[index]) {
    pontuation += 25;
    questions += 1;
  }
});
```

---

## Nomenclatura das variáveis

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

A const precisa descrever o valor que ela está armazenando. Nesse caso, `h2` poderia ser nomeada de forma mais descritiva. Se o que ela faz é armazenar a mensagem de pontuação do usuário, você pode, por exemplo, nomeá-la como `scoreMessage`.

```js
//antes
const h2 = document.createElement('h2')
```

```js
//depois
const scoreMessage = document.createElement('h2')
```

A palavra pontuation é gramaticamente incorreta na língua inglesa, prefira substituir o nome da varíavel pela palavra `score` para indicar a pontuação do usuário.

```js
//antes
let pontuation = 0;
```

```js
//depois
let score = 0;
```

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode deixar uma linha em branco entre a declaração do form e o listener e mais uma após o `event.preventDefault()`.

Antes de `let score = 0` e depois de `let questions = 0` pode ter uma linha em branco também.

```js
//antes
const form = document.querySelector(".quiz-form");
form.addEventListener("submit", (event) => {
  event.preventDefault();
  let score = 0;
  let questions = 0;
  //...
});
```

```js
//depois
const form = document.querySelector(".quiz-form");

form.addEventListener("submit", (event) => {
  event.preventDefault();

  let score = 0;
  let questions = 0;

  //...
});
```

Por convenção, prefira que a primeira e última linha de um bloco sejam linhas preenchidas com código, por isso, você pode remover a linha 52 e deixar uma linha em branco entre a 49 e 50.

```js
//antes
form.addEventListener("submit", event => {
  //...
  answers.forEach((answer, index) => {
    //...
  });
  h2.textContent = `Você acertou ${questions} perguntas, sua pontuação é ${score} pontos`
  form.insertAdjacentElement('afterend', h2)

});
```

```js
//depois
form.addEventListener("submit", event => {
  //...
  answers.forEach((answer, index) => {
    //...
  });

  h2.textContent = `Você acertou ${questions} perguntas, sua pontuação é ${score} pontos`
  form.insertAdjacentElement('afterend', h2)
});
```

---

## Code styling

Ao longo do código, há algumas inconsistências em relação ao uso das aspas e do ponto e vírgula:

```js
// Uso de aspas simples e sem ponto e vírgula
const h2 = document.createElement('h2')
```

```js
// Uso de aspas duplas e ponto e vírgula
const form = document.querySelector(".quiz-form");
```

É uma boa prática manter um padrão na maneira que você escreve o código. Uma sugestão é que você escolha uma das formas e seja consistente com essa escolha no decorrer do código.

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que vc formate manualmente. 

Isso vai "forçar" vc a adotar um estilo de escrita de código e ser consistente com esse estilo ao implementar suas aplicações.

---

## Mensagem de pontuação aparecendo repetidamente ao clicar no botão

A cada envio do quiz (sem recarregar a página), uma nova mensagem de pontuação está sendo criada.

![image](https://user-images.githubusercontent.com/82729897/158990466-4a80a78a-edc2-4515-a712-91183b8ac9ee.png)

Você se lembra o motivo disso acontecer?

Olha só...

Um princípio que gosto de seguir é: deixe as declarações de suas variáveis perto de onde elas são usadas.

Porém, nem sempre esse princípio deve ser aplicado. Por questões de escopo.

Um exemplo clássico é quando vc tem duas funções que precisam acessar a mesma variável.

No código abaixo, func1 e func2 acessam myConst normalmente:

```javascript
const myConst = 'my value'

const func1 = () => {
  console.log(myConst)
}

const func2 = () => {
  console.log(myConst)
}

func1() // 'my value'
func2() // 'my value'
```

Porém, se myConst é declarada dentro de func1, func2 não consegue acessar myConst por que myConst agora é acessível apenas dentro do escopo de func1:

```javascript
const func1 = () => {
  const myConst = 'my value'
  console.log(myConst)
}

const func2 = () => {
  console.log(myConst)
}

func1() // 'my value'
func2() // app.js:7 Uncaught ReferenceError: myConst is not defined
```

Esse é um caso onde myConst precisa estar em escopo global, para que ela seja acessada dentro das duas funções. 

Mais à frente, vc começará a ver por que variáveis globais não são uma boa ideia. Mas por enquanto, isso não é importante. 

Um outro caso que vc precisa considerar é o escopo de bloco...

Lembra que não há problema em duas consts de mesmo nome serem criadas em escopos diferentes?

No código abaixo, 

```javascript
const myFunc = () => {
  const myConst = 'my value'
  console.log(myConst)
}

myFunc()
myFunc()
```

a cada vez que `myFunc` é invocada, o bloco que contém a declaração da const e o console.log é executado, certo?

Blocos criam escopos. 

Isso significa que na primeira vez que myFunc foi invocada, um escopo com a const myConst foi criado. E na segunda vez em que ela foi invocada, um outro escopo com uma outra const myConst foi criado.

Ou seja, se `myFunc` é invocada 2x, duas consts `myConst` foram criadas em memória.

E isso é importante pelo seguinte...

Escreva o código abaixo e execute ele:

```HTML
<div></div>
<button>Adicionar parágrafo</button>
```

```javascript
const div = document.querySelector('div')
const button = document.querySelector('button')

const paragraph = document.createElement('p')

button.addEventListener('click', () => {
  div.appendChild(paragraph)
})
```

Ao executar esse código e clicar no botão pela primeira vez, vc verá que um `<p>` foi adicionado dentro da `<div>`.

Porém, do segundo clique em diante, não são adicionados novos `<p>`.

Por que isso acontece?

Isso acontece por que a cada execução do callback de clique, o `paragraph` ao invés de ser criado novamente está apenas sendo reaproveitado.

Ou seja, como `paragraph` foi declarado fora do escopo do callback, a cada execução do bloco do callback, o mesmo parágrafo está sendo inserido dentro da div.

Lembre-se: quando um callback de listener de evento é executado, ele não faz o código que está fora dele ser declarado novamente. Apenas o bloco do callback é executado novamente. Isso significa que o mesmo `paragraph` está sendo usado dentro do callback.

Agora, se `paragraph` for declarado dentro do callback,

```javascript
button.addEventListener('click', () => {
  const paragraph = document.createElement('p')
  div.appendChild(paragraph)
})
```

toda vez que esse bloco do callback for executado, um novo `paragraph` será criado em memória e inserido como filho da div. Ou seja, o segundo clique no botão irá inserir um segundo `<p>` como filho da div, um terceiro clique irá inserir um terceiro `<p>` e assim por diante. Graças ao escopo de bloco =)

Sacou a ideia?

Considerando isso...

`scoreMessage` pode ser declarada no topo do código para que outros parágrafos não sejam criados novamente à cada execução do callback de submit do form.

```js
//antes
form.addEventListener("submit", (event) => {
  //...
  const scoreMessage = document.createElement('h2')
  //...
});
```

```js
//depois
const correctAnswers = ["B", "B", "B", "B"];

const form = document.querySelector(".quiz-form");
const scoreMessage = document.createElement('h2')

form.addEventListener("submit", event => {
  //...
}); 
```

No print abaixo, o botão foi clicado várias vezes e apenas um único parágrafo é exibido.

![image](https://user-images.githubusercontent.com/82729897/158400590-3d414791-07c4-4285-b2f0-2019eb8da190.png)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by PatrickTav** [comment]
Eu realmente não tenho palavras para poder expressar o quanto me ajudou. eu esperava sim um feedBack mas não assim kasjds
Isso me ajudou demais, consegui assimilar de maneira coesa. Muito obrigado mesmo. Me surpreendeu demais, diferente de vários cursos que tem por ai !

Eu teria feito modificações porem quis mandar assim, ja irei fazer as devidas manutenções !

**Comment by MivlaM** [comment]
Show! No que precisar, é só abrir uma nova issue =)
