### ISSUE TITLE
Aplicação: Todo list

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3329]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Jansen-Muniz/todo-list.git

### Maiores dificuldades durante a implementação

Lógica para buscar e remover os todos.

### Menores dificuldades durante a implementação

Adicionar todos.

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz!

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Lógica para buscar e remover os todos.

Vou falar sobre isso ali em baixo.

Mas o mais importante no primeiro momento vc já fez, que é fazer funcionar.

Inclusive, pelo que vi vc ajustou parafusos em relação à análise passada. Seu código está bacana, não encontrei nenhum ajuste decisivo =)

---

## A const `existingValue`

Talvez, `existingValue` poderia ser renomeada para `inputValueIsValid` para transmitir mais a ideia que vc quis passar.

Porém, `inputValue.length` não é uma expressão extensa/ilegível, então talvez seja válido apenas inserir essa expressão como condição do `if`:

```javascript
// antes
const addTodo = event => {
  // ...
  
  const inputValue = event.target.add.value.trim()
  const existingValue = inputValue.length
  // ...

  if (existingValue) {
    // ...
  }
}
```

```javascript
// depois
const addTodo = event => {
  // ...
  
  const inputValue = event.target.add.value.trim()
  // ...

  if (inputValue.length) {
    // ...
  }
}
```

---

## O momento da criação de um novo to-do

`newTodo` não precisa ser criado antes de se certificar que o valor do input é válido. 

Criar o to-do antes de ter a certeza de que ele será usado ocupa espaço desnecessário na memória (nada que impacte de forma significativa, claro).

O ideal é criar o to-do quando vc tem a certeza de que ele deve ser inserido no DOM.

```javascript
// antes
const addTodo = event => {
  // ...

  const newTodo = `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo = "${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt" data-trash = "${inputValue}"></i>
  </li>`

  if (inputValue.length) {
    todosContainer.innerHTML += newTodo
    // ...
  }
}
```

```javascript
// depois
const addTodo = event => {
  // ...
  
  if (inputValue.length) {
    const newTodo = `
    <li class="list-group-item d-flex justify-content-between align-items-center" data-todo = "${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt" data-trash = "${inputValue}"></i>
    </li>`

    todosContainer.innerHTML += newTodo
    // ...
  }
}
```

---

## Indentação

Indentação é um dos pilares de um código mais legível.

A indentação da template string da marcação do to-do deve indicar que a template string é um valor da const `newTodo`, e vc pode indicar isso através da adição de um nível a mais de indentação:

```javascript
// antes
if (inputValue.length) {
  const newTodo = `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo = "${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt" data-trash = "${inputValue}"></i>
  </li>`

  // ...
}
```

```javascript
// depois
if (inputValue.length) {
  const newTodo = `
    <li class="list-group-item d-flex justify-content-between align-items-center" data-todo = "$  {inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt" data-trash = "${inputValue}"></i>
    </li>`

  // ...
}
```

Sacou a ideia?

---

## Atributos HTML

No código abaixo, os atributos na template string funcionam normalmente, mesmo com o espaço antes e depois do `=`:

```javascript
`data-trash = "${inputValue}"`
`data-todo = "${inputValue}"`
```

Porém, não há motivo para inserir esses espaços em branco, pois vc está declarando um atributo HTML e não uma const.

É uma convenção e boa prática que não haja espaços em branco ali. A não ser que vc tenha algum motivo muito significativo para não seguir essa convenção, prefira que a declaração de atributos fique assim:

```javascript
`data-trash="${inputValue}"`
`data-todo="${inputValue}"`
```

---

## Reset do `form`

O reset do form pode acontecer fora do if, pq se o valor do input forem vários espaços em branco por exemplo, após enviar o form, se o usuário quiser mudar o valor do input, ele precisa remover os espaços em branco primeiro (para o cursor voltar para o início do input). 

Considerando isso, o ideal é resetar o form independentemente se o valor do input é válido.

```javascript
// antes
if (inputValue.length) {
  // ...
  event.target.reset()
}
```

```javascript
// depois
if (inputValue.length) {
  // ...
}

event.target.reset()
```

---

## O momento de fazer uma busca no DOM

A const `todoItem` pode armazenar o elemento do DOM apenas quando há a certeza de que ela será usada:

```javascript
// antes
const removeTodo = event => {
  const clickedElementIsTrash = event.target.dataset.trash
  const todoItem = document.querySelector(`[data-todo = "${clickedElementIsTrash}"]`)

  if (clickedElementIsTrash) {
    todoItem.remove()
  }
}
```

```javascript
// depois
const removeTodo = event => {
  const clickedElementIsTrash = event.target.dataset.trash

  if (clickedElementIsTrash) {
    const todoItem = document.querySelector(`[data-todo = "${clickedElementIsTrash}"]`)
    todoItem.remove()
  }
}
```

👆🏻 Ou seja, antes de obter a referência do to-do no DOM, faz mais sentido verificar se essa referência realmente será usada.

---

## Considerações finais

Seu progresso em relação à análise do quiz é perceptível. Vc demonstrou ter entendido bem a lógica até aqui.

Como vc foi bem na implementação dessa aplicação e listou a lógica para buscar e remover os todos como uma dificuldade, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

É possível criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Comentei o restante do código, apenas para você focar nessa parte e testar no console:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */

  // ...
}
```

Tudo certo até aqui?

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```javascript
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible }) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  filterTodos(todos)
}
```

Sacou a ideia?

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação e avaliar o que faz mais sentido pra vc.

Novamente, parabéns pelo esforço =)

As observações ajudaram?

**Comment by Jansen-Muniz** [comment]
```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))

  console.log(todos) 
}

searchTodo()
```
Roger, quando eu chamei a função para testar, deu esse erro:  

unCaught typeError: cannot read properties of undefined(reading 'target')

**Comment by Roger-Melo** [comment]
Pq vc invocaria `searchTodo` no fim do código? 

O `event` é um objeto recebido como parâmetro em uma função de callback de listeners de eventos, lembra?

`searchTodo`  deve continuar referenciada como callback do listener do input de busca do to-do.

Conserta isso, testa, e me avisa aqui.

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Deu certo, acho que é porque tava com sono kkkkk

Roger, nessa parte:
```js
todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
```
`shouldBeVisible ? 'd-flex' : 'hidden'` - se for visível irá adicionar a classe `d-flex`, se não for visível, a classe `'hidden'`
`shouldBeVisible ? 'hidden' : 'd-flex'` - se for visível irá remover a classe `'hidden'`, se não for visível, a classe `'d-flex'`

é isso? 

Sobre o restante, acho que entendi. Tô pegando gosto por código assim, desde que não seja de difícil compreensão, 
como falou em uma aula.

**Comment by Roger-Melo** [comment]
Não é "se for visível".

A tradução de `shouldBeVisible` seria algo como "deve estar visivel".

Se o to-do **deve estar visivel**, na primeira linha abaixo a classe CSS após o `?` será adicionada no elemento e na segunda linha, a classe após o `:` será removida do elemento:

```js
todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
```

Se o to-do **não deve estar visivel**, na primeira linha a classe após o `:` será adicionada e na segunda linha, a classe após o `?` será removida.

Em outras palavras: 

Se `shouldBeVisible` armazena `true`, a classe que deixa o elemento visível é adicionada e a classe que deixa o elemento invisível é removida.

Se `shouldBeVisible` armazena `false`, a classe que deixa o elemento invisível é adicionada e a classe que deixa o elemento visível é removida.

Ficou mais claro?

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Ficou sim. Às vezes tenho dificuldade para criar nome para as variáveis e funções. 

Roger, só mais uma pergunta, sobre mandar a aplicação no netlify, não mandei essa ainda, até sei fazer, mandei a do quiz mas irei ainda praticar a forma como tu fez a refatoração. 
Pq penso que preciso aprender como fazer tuas refatorações, é o professor, minha base são teus ensinamentos, então quero fazer e entender tua forma de refatorar e com o tempo vou criando a minha.
O que diz sobre isso?

**Comment by Roger-Melo** [comment]
O que eu disse antes: Mas o mais importante no primeiro momento vc já fez, que é fazer funcionar.

Refatoração vem com o tempo. Desencana de querer sacar tudo de uma vez. É o mesmo que achar que engravidar 9 mulheres faz o filho nascer em 1 mês.

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Ta certo mano Roger, valeu!

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
