### ISSUE TITLE
Resumo da Aula 02.04 da etapa 01

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#333]
// metodos comuns de strings
// const cria uma constante (valor que não pode ser simplesmente alterado).

const email = 'laracroft@rogermelo.com'

/* O metodo lasIndexOf() é uma função, e como todo função precisa ser precedida de '()', estes metodo,
mostra a ultima ocorrência do argumento informado dentro dos '()'.*/

const lastIndexofA = email.lastIndexOf('a')

// Fatiamento e remanejamento de strings, com os metodos '.slice e .replace'.
const emailSlice = email.slice(4, 9)
const emailReplace = email.replace('laracroft', 'chun-li')

console.log(emailReplace)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @renarfreitas! Rumo à fluência! 🔥
