### ISSUE TITLE
Aplicação: [Quiz_Interativo]

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3333]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/EneasFeynlinus/quizInterativo-cjrm.git

### Maiores dificuldades durante a implementação

Maiores dificuldades, estão sendo em entender os frame works de bootStrap e utilizalos de uma maneira eficiente com JavaScript, como ensinado no curso.

Também tive dificuldades em arrumar um problema que surgiu com o highlight que fiz ao escolher a resposta, caso o usuário, decida mudar a resposta clicada, a alternativa selecionada anteriormente continua selecionada. Tentei fazer algo para tirar a seleção e passar para a outra mas não consegui. Tentei referenciar pelos parents e previus elements mas não obtive sucesso.

### Menores dificuldades durante a implementação

Com o template HTML pois já tinha toda uma estrutura pronta para trabalhar em cima.

**Comment by MivlaM** [comment]
Olá @EneasFeynlinus.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by EneasFeynlinus** [comment]
Bom dia @MivlaM tá ok fico no aguardo =)

Desde já grato,

@EneasFeynlinus

**Comment by MivlaM** [comment]
Olá, @EneasFeynlinus.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Entender os frame works de bootStrap e utilizalos de uma maneira eficiente com JavaScript, como ensinado no curso.

O uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

> ## Highlight que fiz ao escolher a resposta, caso o usuário, decida mudar a resposta clicada, a alternativa selecionada anteriormente continua selecionada

Vou comentar sobre isso mais abaixo.

---

## Boas decisões

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado.

Uma sacada interessante que você fez em relação à usabilidade foi a de posicionar a mensagem dos pontos no local onde o usuário está olhando ao enviar o quiz.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

---

## Diretório do index.html

No diretório inicial do seu repositório, os arquivos da pasta exercício-19 devem ser colocados na raiz e essa pasta pode ser descartada.

![image](https://user-images.githubusercontent.com/82729897/158424428-98a5c4c4-5bca-4442-a863-bc0b9a62316a.png)

A pasta raiz da sua aplicação deve ter um index.html, exatamente como é mostrado nas aulas. Caso contrário, ao invés da página inicial com o quiz aparecer, a listagem de diretórios da aplicação é exibida, o que não é o desejado.

![image](https://user-images.githubusercontent.com/82729897/158424078-097ae597-71f8-483c-978c-fcb4d68dae62.png)

Mesmo que atualmente exista a possibilidade de servidores possuírem configurações que suportem servir arquivos com outro nome, é uma boa prática a página de entrada da aplicação ser nomeada como index.html.

---

## Highlight ao escolher as respostas.

Adicionar um highlight para as alternativas é uma nova funcionalidade, e novas funcionalidades não devem ser adicionadas agora. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, novas features não serão analisadas. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e implementar mais features.

---

## Comentários no código

Não é uma regra, mas evite comentários.

Junto ao código da aplicação, você colocou o enunciado do exercício em comentário, mas futuramente você pode querer implementar novas modificações ou features que não necessariamente estariam relacionadas com aquela descrição do enunciado. Uma sugestão seria você remover esse comentário, pois se ele não for reescrito com frequência, ele perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Indentação com quatro espaços ao invés de dois

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

- [Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Na sua aplicação, apenas a primeira pergunta tem a primeira alternativa marcada como padrão. Para fazer com que as outras alternativas também tenham, basta inserir o atributo checked no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## Nomenclatura das variáveis

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Uma const precisa descrever o valor que ela está armazenando. Nesse caso, h1 poderia ser nomeada de forma mais descritiva. Se o que ela faz é armazenar a mensagem de pontuação do usuário, você pode, por exemplo, nomeá-la como scoreMessage.

```js
//antes
const h1 = document.querySelector('.result')
```

```js
//depois
const scoreMessage = document.querySelector('.result')
```

---

## Linhas em branco
  
Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco 68, 60 e 58. Por convenção, prefira que a primeira e última linha de um bloco sejam linhas preenchidas com código.

`let score = 0` pode ter uma linha em branco depois de sua declaração.

---

## Else if

Não é necessário usar else if no código abaixo.

A desvantagens do `else` e do `else if` é que eles adicionam um bloco desnecessário no código.

```js
//antes
if (score > 50) {
  h1.classList.toggle('text-warning')
  h1.classList.add('text-success')
  h1.textContent = `Result: ${score}`
  return
} else if (score < 70) {
    h1.classList.toggle('text-warning')
    h1.classList.add('text-danger')
    h1.textContent = `Result: ${score}`
}
```

```js
//depois
if (score > 50) {
  h1.classList.toggle('text-warning')
  h1.classList.add('text-success')
  h1.textContent = `Result: ${score}`
  return
}

h1.classList.toggle('text-warning')
h1.classList.add('text-danger')
h1.textContent = `Result: ${score}`
```

---

## console.log

O `console.log` é útil apenas no momento em que você está desenvolvendo.

Sei que vc deve ter usado para visualizar algum valor e esquecido, mas sempre que subir a aplicação para produção ou enviar o código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

Para o funcionamento da sua aplicação, não faz sentido exibir os array de inputs no console, como abaixo.

```js
console.log(Array.from(answer))
```

---

## Usabilidade

Algo que vc pode fazer para melhorar a usabilidade é deixar o usuário mais consciente do progresso dele no quiz em relação à pontuação total. Vc pode fazer isso com uma mensagem indicando a pontuação com porcentagem ("você acertou 50%") ou inserindo uma barra e pontuação total do quiz após a quantidade de acertos, exemplo: "100/100".

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by EneasFeynlinus** [comment]
Boa noite @MivlaM, espero que esteja tudo certo por ai.

Muito obrigado pelos feedbacks, adorei todos.

Não tinha muita noção e não pensava muito ainda sobre a questão de um padrão de espaçamento durante um endentação no código. Achei muito maneiro a sua indicação com o link do MDN com o padrão para escrever um cleanCode, não conhecia essa documentação e fiquei muito animado de vc ter dividido o link, vai ajudar muito aprender o padrão de codar, tanto no entendimento durante a leitura e na hora do flow para refatorar e melhorar assim como no campo profissional.

Muito obrigado do toque com relação a fazer upload apenas dos arquivos html, style.css e o .js não tinha noção que isto poderia afetar durante a exibição do conteúdo, agradeço muito =).

Adorei também, você dividir o link para a documentação do visualCode, nunca tinha acessado ela, até já coloquei no favoritos para começar a entender melhor, por enquanto o que sei são as dicas dada pelo Roger Melo durante o curso e que vou copiando e são muito uteis.

Top demais a dica sobre a nomenclatura de funções como verbo getSomething setSomething useSomething não tinha pego essa lógica ainda mesmo assistindo a aula e a correção dos exercícios, também a nomenclatura dos constantes como substantivos e booleans com o adendo do is, has ou should muito rica essa informação para facilitar no raciocínio na hora de criar um nome para o que esta acontecendo ou armazenando. Fiquei muito animado, já havia lido sobre essa questão dos verbos representarem a ação o substantivo os objetos que vão interagir o adverbio a intensidade que vai ocorrer a ação, no entanto tinha visto isso em um livro estudando inglês e aplicado a gramática,  não pensava assim na hora de nomear as funções e constantes e isso meio que foi uma informação nova que ajudará e muito a partir de agora.

Muito obrigado pelo toque de prestar atenção quanto a necessidade do else if ou não, ajudou bastante tb para aumentar as conexões neurais do aprendizado, também, pode deixar vou me atentar para apenas fazer aquilo que é pedido no exercício para fins de didática, muito obrigado pelo feedback.

Muito obrigado por tudo, desde já grato,

@EneasFeynlinus

**Comment by MivlaM** [comment]
Show! No que precisar, é só abrir uma nova issue =)
