### ISSUE TITLE
Resumo da Aula inaugural da etapa 00

### ISSUE THREAD

**Issue by thiagotcs** [roger-melo-treinamentos/curso-de-js-roger-melo#3334]
Criando um Issue Resumo seguindo as orientações da aula inaugural do curso CJRM.

Criando um Issue Dúvida seguindo as orientações da aula inaugural do curso CJRM.
Etapa da aula => sempre o titulo da barra lateral da plataforma CJRM.
nome da aula => CTRL + C & CTRL + V
link da aula => CTRL + L para selecionar a URL + CTRL + C & CTRL + V
Ler as instruções antes de criar Issue de Dúvida.
 
inteligência coletiva do Github
rolou dúvida pesquisa nas Issues

Fazer Revisão raio-x: 
https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1985

**Comment by Roger-Melo** [comment]
Show @thiagotcs. Vamo que vamo, rumo à fluência! 🙌
