### ISSUE TITLE
Resumo da Aula For loop - Aula 01-03 da etapa 02

### ISSUE THREAD

**Issue by developsouza** [roger-melo-treinamentos/curso-de-js-roger-melo#3339]
Através das iterações do for loop, podemos percorrer itens de array, inserí-los em templates HTML, e utilizado sempre quando queremos percorrer ou fazer uma determinada ação por N vezes até que a condição seja falsa onde encerra a iteração do loop.

**Comment by Roger-Melo** [comment]
Show @developsouza. Vamo que vamo, rumo à fluência! 🙌
