### ISSUE TITLE
Resumo da Final da etapa 02 (aulas01-04, aulas02-04, aulas03-03):

### ISSUE THREAD

**Issue by mrp99** [roger-melo-treinamentos/curso-de-js-roger-melo#3340]
=========================================================
Controle de fluxo (loop) - Aula 01 a 04 - Etapa 2:
For: é uma iteração cada vez que o for percorre o loop.
exemplo cada iteração seria se i tivesse valor de 0 a 2
cada iteração seria i = 0, depois i = 1 e i =2.

while: O que muda de um para outro que no while precisa declarar
uma variável de iteração seja ela qual for exemplo i e inicializar
ela com valor de 0 ou outros valores, e dentro do parentes colocar
condição e não esquecer de colocar o incremento dentro do scopo da 
função.
=========================================================
Controle de fluxo (if-else) - Aula 02 a 03:
if condição e ação dentro do bloco {}. se expressão for true ou false
dependendo de como for codificada a condição. Else caso seja contraria 
a condição adota!
=========================================================
Controle de fluxo (&& e ||) Aula 02 a 04:
&& =  and as condições tem que ser estritamente verdadeiras  e || = or
=========================================================
O operador lógico not (!) - Aula 03 a 02:
esse operadorador vai negar a condição do if!
=========================================================
Break e continue - Aula 03-03:
É auto explicativo.
=========================================================
A condicional switch e exercícios - Aula 03-04:
É auto explicativo.
=========================================================

**Comment by Roger-Melo** [comment]
Excelente @mrp99, rumo à fluência! 🎯
