### ISSUE TITLE
Resumo das Aulas 1 e 2 da etapa 01

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#3342]
[Aula1 e 2 - CJRM.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/8288007/Aula1.e.2.-.CJRM.pdf)

Segue PDF em anexo.

**Comment by George-Luis-Costa** [comment]
> [Aula1 e 2 - CJRM.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/8288007/Aula1.e.2.-.CJRM.pdf)
> 
> Segue PDF em anexo.

![Parametros_Argumentos](https://user-images.githubusercontent.com/79100329/158900259-476c67c0-f37f-4111-a1c6-57c96bf43144.png)

**Comment by George-Luis-Costa** [comment]
> [Aula1 e 2 - CJRM.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/8288007/Aula1.e.2.-.CJRM.pdf)
> 
> Segue PDF em anexo.

![Parametros_Argumentos](https://user-images.githubusercontent.com/79100329/158900343-18ae7a7a-5a52-4da9-9953-3cb81489ab02.png)

**Comment by Roger-Melo** [comment]
Excelente @George-Luis-Costa, rumo à fluência! 🎯
