### ISSUE TITLE
Dúvida sobre issues

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#3343]
### Etapa da aula

1

### Nome da aula

Aula inaugural

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/2186928

### Salve Roger! Devo postar os códigos dos exercícios? Ou apenas o resumo?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @George-Luis-Costa.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Devo postar os códigos dos exercícios? Ou apenas o resumo?

Se você estiver se referindo ao código que você escreveu para os exercícios ao longo das etapas, não é necessário. Caso você tenha alguma dúvida em relação a algum exercício durante o treinamento, você pode abrir uma issue de dúvida no repositório do curso. O mais importante para os exercícios é que você aplique os conceitos mostrados nas aulas e pratique resolvê-los com o que você aprendeu durante o curso. Os resumos das aulas servirão como uma ferramenta de consulta para auxiliar você a lembrar alguns aspectos da linguagem e assim chegar na fluência em Javascript =) 

Essa foi apenas uma sugestão, mas você pode fazer da maneira que achar mais confortável. 

---

Na etapa 01 você também vai encontrar um post com orientações sobre os exercícios.

Se houver qualquer dúvida, pode abrir uma issue que te ajudo =)

**Comment by MivlaM** [comment]
Vou fechar a issue. Se tiver alguma dúvida, no que precisar, é só abrir uma nova issue =)
