### ISSUE TITLE
Resumo da Aulas 01-01 ate 01-05 da etapa 01

### ISSUE THREAD

**Issue by thiagotcs** [roger-melo-treinamentos/curso-de-js-roger-melo#3344]
Criando um Issue Resumo seguindo as orientações da aula do curso CJRM.
Sequencia dos videos aula 01 ate 05.

Objetivo do curso, linguagem javascript, configuração minima do ambiente, adicionando o javascript na pagina web. Usando servidor local (localhost:) e mostrando O console do browser

- Qual é o meu objetivo com o CJRM - Aula 01-01
- A importância de você ter escolhido o JavaScript - Aula 01-02
- Configurando o ambiente - Aula 01-03
- Adicionando o javascript a uma pagina web - Aula 01-04
- O console do browser - Aula 01-05

Boa praticar inserir a tag <script> sempre como o ultimo código antes do fechamento do < /body> ou isolar todo o código javascript em um arquivo separado.

**Comment by Roger-Melo** [comment]
Excelente @thiagotcs, rumo à fluência! 🎯
