### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3347]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/santos2408/quiz-interativo

### Maiores dificuldades durante a implementação

- Achei o bootstrap bem chatinho, por não ser obrigatório a utilização dele, deixei o básico inserido e não mexi mais.

- Deixar as variáveis bem descritivas e refatorar o código quando estava extenso me fez dedicar um tempo considerável, pois eu acabava me perdendo na hora de organizar e não ter muita certeza se a variável estava bem informativa.

- Acredito que o código tenha ficado extenso, pois tentei separar em funções e implementar funcionalidades que foram assimiladas em aulas anteriores.

### Menores dificuldades durante a implementação

- Manipular o DOM
- Criar as funções para cada tipo de ação
- Trabalhar com os eventos

**Comment by Roger-Melo** [comment]
Olá @santos2408.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Roger. 

Em breve envio a gravação da call que fizemos ontem =)
