### ISSUE TITLE
Etapa 01, nome do vídeo: em todos os vídeos.

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#335]
Roger, bom dia!

Eu queria commitar no meu git, os exercícios e os resumos de aulas conforme vou executando, tal qual está no diretório aqui do curso.
Porem ao tentar fazer, o upload dos arquivos no meu github, "não é via command line", o git só pega os arquivos, ele não tá pegando a extrutura de diretórios e pastas.
Como faço?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Renar.

Neste caso, é mais fácil criar um novo repositório aqui no github, clonar ele para a sua máquina, inserir os aquivos e diretórios nele e então comitar (upload). 

Vou deixar [aqui](https://youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A) um tutorial rápido de git e github. No vídeo 13 da playlist tem o passo-a-passo de como fazer o que mencionei acima. Mas já que a playlist é curta, recomendo que veja ela inteira para entender melhor como funciona.

Caso ainda tenha dúvidas, é só dar o toque =)

@renarfreitas

**Comment by renarfreitas** [comment]
Ok Roger! entendi... Obrigado pelo retorno.
Vou fazer exatamente como tu falou.
Duvida sanada com sucesso. :)

**Comment by renarfreitas** [comment]
Obrigado.
