### ISSUE TITLE
Resumo da Aula Encadeando promises 04-04 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3350]
Para encadearmos as requests da aula anterior, precisamos novamente identificar o momento no qual a primeira request é finalizada. A nova requisição entrará exatamente após a exibição dos dados, dentro de `then()`, e conterá o novo endpoint. A diferença, neste caso, é que todas as próximas requisições terão seus respectivos métodos `then()` encadeados “por fora”, isto é, não serão aninhados, além de que todos terão o mesmo `catch()` para tratamento de erro.

```js
getPokemon('https://pokeapi.co/api/v2/pokemon/1')
    .then(bulbasaur => {
        console.log(bulbasaur)
        return getPokemon('https://pokeapi.co/api/v2/pokemon/4') 
    })
    .then(charmander => {
        console.log(charmander)
        return getPokemon('https://pokeapi.co/api/v2/pokemon/7')
    })
    .then(console.log) // último elemento, já está implícito que se trata do squirtle
    .catch(error => console.log(error))
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
