### ISSUE TITLE
Resumo da Aula tipos de variáveis ate correção dos exercícios da etapa 01

### ISSUE THREAD

**Issue by thiagotcs** [roger-melo-treinamentos/curso-de-js-roger-melo#3352]
Criando um Issue Resumo seguindo as orientações da aula do curso CJRM.
Sequencia dos videos aula tipos de variáveis ate Correção dos exercícios da aula 01.

variáveis é um espaço na memoria aonde armazenam os dados, hoje  Existem três tipos de declarações em JavaScript.
 - var
   - Declara uma variável, opcionalmente, inicializando-a com um valor.
 - let
   - Declara uma variável local de escopo do bloco, opcionalmente, inicializando-a com um valor. 
 - const
   - Declara uma constante de escopo de bloco, apenas de leitura.
 - comentários
   - Os comentários são, essencialmente, pequenos trechos de texto que podem ser adicionados entre os códigos e são ignorados
   
 - Exercícios da Aula 01
   - criar conta no github
   - instalar o git
   - instalar o Hyper
   - clone do projeto
   - Aviso sobre a correção dos exercícios
   - Correção dos exercícios da aula 01 - Aula 02-01

**Comment by Roger-Melo** [comment]
Excelente @thiagotcs, rumo à fluência! 🎯
