### ISSUE TITLE
Resumo da Aula 02-03 setInterval() e animação da pontuação da etapa 07

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3354]
**(setInterval()) {**
=> setInterval, é similar a setTimeout() no entanto enquanto o setTimeout() executa uma vez
após o tempo determinado o método setInterval a função será executada intermi
tentemente no intervalo de tempo também definido em milissegundos especificado no segundo 
argumento do método. Vamos aprender a utilizar o setInterval() para criar uma animação
nos pontos do usuário.

```JS
setInterval(()=>{
    console.log('1 segundo se passou')
}, 1000)
```
**}**

**=>(parando o setInterval) {**
**=>** nos precisamos espcificar um limite de execuções do setInterval, portanto vamos criar
uma variavel para incrementala e setar um limite.
**=>** Então nos vamos setar o valor inicial do nosso counter
**=>** E logo abaixo nos vamos executar o setInterval(()=>{},milisegundos) e armazenar o retorno
do ID da setInterval dento da variavel timer. E portanto a função será executada a cada 1
segundo e p valor da counter será incrementado, como cada execução da setInterval gera o
incremento do ID vamos com uma condicional comparar o valor da counter incrementrada a cada
execução da função e quando o numero da counter for igual o do ID ele vai executar  o méto
do clearInterval()

```JS
let counter = 0

const timer = setInterval(()=>{
    console.log('1 segundo se passou')
    counter++

    if(counter === 5) {
        clearInterval(timer)
    }
}, 1000)
```
**=>** Será deste modo que vamos animar a exibição da pontuação do user no quiz.
**}**

**(animando a pontuação){**
**=>** Vamos primeiro declarar nossa variável timer que recebe o método setInterval com um inter
valo de 10 milésimos. E dentro de sua função callback nos vamos colocar o nosso finalResult
onde assignamos os pontos em porcentagem. No entanto logo após precisaremos modificar nossa
interpolação porque senão ela vi mostrar o valor total do score a cada 10 milissegundos.

```Js
const timer = setInterval(()=>{
        finalResult.querySelector('span').textContent = `${score}%`
    },10)
```
**=>** No lugar do score, nos vamos colocar o counter a cada execução dessa função, o valor
que o counter armazena de 1 em 1, será exibido a cada 10 millisegundos. Então vamos criar uma let counter que vai receber
0 vamos invocar a setInterval e vamos armazenar o ID que ele retorna na const timer
e como o setInterval foi invocado, a função callback será executada a cada 10 milesundos
Dentro dessa função, nossa logica através de uma condicional, verifica se o counter, atingiu
o valor da variável score e caso seja true ele vai executar a clearInterval(timer), que vai
parar a execução da setInterval. Caso seja falso será mostrado em nossa tag Span através
da referencia pelo form a adição do texto pelo textContent uma interpolação contendo a variável
counter que será incrementada após sua exibição a cada 10 milissegundos.

```JS
let counter = 0

const timer = setInterval(() => {
        if(counter === score) {
            clearInterval(timer)
        }
        finalResult.querySelector('span').textContent = `${counter}%`
        counter++
    }, 10)
```
**}**

**(Resultado final com adição da animação) {**
```JS
const form = document.querySelector('.quiz-form')
const finalResult = document.querySelector('.result')

const correctAnswers = ['A', 'B', 'A', 'B']

form.addEventListener('submit', event => {
    event.preventDefault()

    let score = 0
    const userAnswers = [
        form.inputQuestion1.value,
        form.inputQuestion2.value,
        form.inputQuestion3.value,
        form.inputQuestion4.value
    ]

    userAnswers.forEach((userAnswer, index) => {
        if (userAnswer === correctAnswers[index]) {
            score += 25
        }
    })

    scrollTo(0, 0)

    finalResult.classList.remove('d-none')

    let counter = 0

    const timer = setInterval(() => {
        if(counter === score) {
            clearInterval(timer)
        }
        finalResult.querySelector('span').textContent = `${counter}%`
        counter++
    }, 10)
})
```
**}**

**Comment by Roger-Melo** [comment]
Excelente @EneasFeynlinus, rumo à fluência! 🎯
