### ISSUE TITLE
Aplicação: Currency Exchange

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#3356]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edcabralc/currency-exchange

### Maiores dificuldades durante a implementação

Não consegui refatorar partes do código para aplicar Factory Function. (Vou rever essas aulas)

### Menores dificuldades durante a implementação

Manipular o DOM
Sinto mais tranquilidade em criar funções por responsabilidade e em nomear variáveis e funções. Claro, acredito que tenho muito para melhorar.

**Comment by Roger-Melo** [comment]
Olá @edcabralc.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)
