### ISSUE TITLE
Aplicação: Todo- list

### ISSUE THREAD

**Issue by PatrickTav** [roger-melo-treinamentos/curso-de-js-roger-melo#3367]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/PatrickTav/list-todo

### Maiores dificuldades durante a implementação

Tive dificuldade em refatorar o código em funções exclusivas!

### Menores dificuldades durante a implementação

em sí o código foi bem simples porem das menores foia implementação de remover o item da tela

**Comment by Roger-Melo** [comment]
Olá @PatrickTav! 

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Me avise aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by PatrickTav** [comment]
Ja foi modificado
