### ISSUE TITLE
Resumo da Aula Xxxxxxxxx da etapa XX

### ISSUE THREAD

**Issue by gh-carneiro** [roger-melo-treinamentos/curso-de-js-roger-melo#3371]
# Constantes, variáveis e comentários - Aula 01-06

- `console.log()` é um método que pode ser utilizado para exibir mensagem no console do navegador. Pode ser atribuído mais de um valor entre os parênteses adicionando a virgula entre os valores.

## Variáveis

- Variável é uma forma de armazenar um valor na memória;
- Para declarar uma variável utilizamos:
    - `let nomeDaVariavel = valor`
    - `var nomeDaVariavel = valor` **forma antiga de se declarar**
- Ao declarar uma variável o nome dela se torna um container para o valor atribuído.
- Como o nome já diz pode variar durante a execução da aplicação, como JavaScript é executado de forma sequencial ao digitar novamente o nome da variável pode-se atribuir um novo valor.

## Constantes

- Para adicionar um valor na memória que não é permitido alterar durante a aplicação deve-se adicionar uma constante.
- Para declarar uma constante utilizamos:
    - `const nomeDaVariavel = valor`

## Regras para declarar variáveis

- Deve ser uma única palavra;
    - Caso escrever mais de uma palavra utilizar o CamelCase;
- Somente letras, números, underscores ou cifrão;
    - Não pode começar com um número;
- Não pode ser utilizado palavras-chave em nome de variáveis;
- Dê nomes significativos a variáveis;

## Comentários

- `//Comentário de uma linha`
- `/* Comentário de várias linhas */`

## Atalhos

- Ctrl + ; - torna uma linha de código em comentário.

**Comment by Roger-Melo** [comment]
Boa @gh-carneiro, rumo à fluência! 🔥
