### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by FelipeD4ntas** [roger-melo-treinamentos/curso-de-js-roger-melo#3372]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/FelipeD4ntas/projeto-quiz-interativo

### Maiores dificuldades durante a implementação

Achei bem tranquilo de se implementar o que foi estudado até aqui nessa aplicação.

### Menores dificuldades durante a implementação

Buscar os elementos do documento HTML, com o que aprendi até aqui no curso, já está se tornando automático.

**Comment by Roger-Melo** [comment]
Olá @FelipeD4ntas.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by FelipeD4ntas** [comment]
Muito obrigado, coloquei pra mostrar na tela os pontos do quiz, através de um popup como vc tinha ensinado antes, espero que tenha feito certo. Fico no aguardo de seu feedback. =)
