### ISSUE TITLE
Resumo da Aula 01-04 da etapa 11 - O que são requests HTTP

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3376]
- Dentro das nossas aplicações, informações que estão armazenadas em outro lugar precisarão ser exibidas, que pode ser um
banco de dados ou um API. Essas informações podem estar armazenadas em outro servidor ou no nosso próprio banco de dados.
- Para obter as informações fazemos requisições HTTP para se conectar a API ou banco de dados.
- Requisição ou request é uma solicitação de informações que o banco de dados ou API armazena.
- HTTP - HiperText transfer Protocol - protocolo principal de comunicação entre computadores utilizados na internet.
- Quando fazemos requests HTTP para uma API ou servidor, esses requests são feitos para uma endpoint, que é uma URL
que a API ou servidor disponibiliza para usar ou obter informações que uma API ou servidor armazenam

![image](https://user-images.githubusercontent.com/92958989/160218241-babd4049-c92a-4be9-a80d-2c58ca7dd7af.png)

**Comment by Roger-Melo** [comment]
Boa @Jansen-Muniz, rumo à fluência! 🔥
