### ISSUE TITLE
QuizInterativo

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3380]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação

https://github.com/Giansantos-carlos/QuizInterativo.git

### Maiores dificuldades durante a implementação

Muitas dificuldades em  usar o  Boostrap, muita dificuldade em usar cores novas e adicionar novas tags.

### Menores dificuldades durante a implementação

Primeiramente agradecer e parabenizar pelo Curso, Não me arrependo de forma alguma da a aquisição do curso. 

As menores dificuldades foi no JS puro, como apliquei o ATER desde do inicio do curso , e não tive dificuldades.
Dei uma incrementada no quiz, deixando em vermelho os text das peguntos que usuário errou,  e verde os acertos, como ja tiva visto isto em alguns sites estudantis antes quis aplicar isso nesse quiz, usei o insertAdjacentElement para inserir um parágrafo na pagina, e tambem usei o JS para estilizar o parágrafo Criado, testei usar o máximo de JS nesse exercicio.

Obs : Codigo não refatorado.

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Agora que a análise via chamada de vídeo foi feita, vou fechar a issue. No que precisar, é só abrir uma nova =)
