### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by Nathan-013** [roger-melo-treinamentos/curso-de-js-roger-melo#3387]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Nathan-013/Weather-Application---CJRM

### Maiores dificuldades durante a implementação

- Dar nome as funções de responsabilidade única;
- Refatorar o código.

### Menores dificuldades durante a implementação

-Fazer o destructing de arrays e objetos
-Obter os dados atráves dos requests
-Manipular o DOM

**Comment by Roger-Melo** [comment]
Olá @Nathan-013.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Te enviei uma mensagem no whatsapp, dá uma olhada quando puder =)

@Nathan-013

**Comment by Roger-Melo** [comment]
Agora que a análise via chamada de vídeo foi feita, vou fechar a issue. No que precisar, é só abrir uma nova =)
