### ISSUE TITLE
Resumo da Aula setInterval() e animação da pontuação- Aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#339]
## `setInterval()`

É um método pendurado pelo objeto global Window responsável por executar uma ação repetidas vezes dentro de um intervalo de tempo que especificamos em millissegundos. 

### Argumentos

1. **Função de callback** que será executada repetidas vezes dentro de um intervalo de tempo
2. **Intervalo de tempo** em millissegundos que a função de callback especificada como primeiro argumento será executada
3. **Argumentos** que são valores que serão passados como argumento dos parâmetros da função de callback especificada no primeiro argumento

### Retorno

Um identificador único para o método, sendo um número inteiro diferente de 0. Esse identificador poderá ser utilizado para paralisar a execução do `setInterval()`.

---

## `clearInterval()`

É um método que quando executado paralisa a execução do método `setInterval()`. 

### Argumentos

O identificador do `setInterval()` que deseja-se parar.

### Retorno

*undefined*

---

*MDN:*

- [*https://developer.mozilla.org/pt-BR/docs/Web/API/WindowOrWorkerGlobalScope/setInterval*](https://developer.mozilla.org/pt-BR/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)
- [*https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval*](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Muito bom @sou-gabriel. Tamo junto, rumo à fluência! 🔥
