### ISSUE TITLE
O que mais faz a execução do código demorar?

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3395]
### Etapa da aula

11

### Nome da aula

Código assíncrono em JavaScript - Aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1154166

### Descreva a dúvida

Além da requisição de uma instrução a um banco de dados, por exemplo, o que mais faz a execução do código
ser demorada?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

Na etapa 14 você verá a aula em que falo sobre performance. Já adianto que não é algo que vc deva se preocupar nesse momento.

E claro, se ao ver a aula ainda restar alguma dúvida, pode abrir uma issue que te ajudo =)

**Comment by Jansen-Muniz** [comment]
Tá certo mister Roger =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
