### ISSUE TITLE
Aplicação: [To-Do-List]

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#3396]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/MivlaM/Minha-To-Do-List

### Maiores dificuldades durante a implementação

-A refatoração ainda é bem complicada para mim, eu cheguei a refatorar uma parte do código, mas acredito que ainda haja possibilidade de refatorar mais.

-Usar data e dataset, eu cheguei a adicioná-los no html, mas não consegui fazer uma lógica para fazê-los funcionar na aplicação.

### Menores dificuldades durante a implementação

Dessa vez consegui organizar melhor o código da aplicação. A lógica de adicionar e remover to-dos também não me foi muito difícil.

**Comment by Roger-Melo** [comment]
Olá @MivlaM, hahah!

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)
