### ISSUE TITLE
Resumo da Aula Requests paralelos vs sequenciais 06-03 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3399]
As requisições via fetch feitas com o `await` são seqüenciais, pois este “pausa” a execução das linhas seguintes até que a promise atual seja resolvida ou rejeitada.

Sintaxe da requisição fetch seqüencial:
```js
const getData = async () => {
    const data1 = await fetch(endpoint 1) // usa-se await
    const data2 = await fetch(endpoit 2) // usa-se await

    console.log(await data1.json()) // obtendo dados desencapsulados
    console.log(await data2.json() // obtendo dados desencapsulados
}
```

- Ao invés do console.log() direto, podemos usar o `Promise.all()` dentro da função `getData()`:
```js
    const result = await Promise.all([data1.json(), data2.json()])
    result.forEach( response => console.log(response) ) // se as promises no argumento estiverem com .json()
```

Se as promises passadas como argumentos não estiverem com o método `.json()` aplicado, a callback do método .`forEach()` deve ser assíncrona, pois deve conter `await` para conseguir desencapsular os objetos:
```js
    const result = await Promise.all([data1, data2])
    result.forEach( async response => console.log(await response.json()))
```

Se as requisições não dependem dos dados umas das outras, podemos torná-las paralelas, removendo os awaits contidos nas aberturas dos fetchs. No entanto, como os awaits são responsáveis por esperar a resolução das promises criadas, a resposta somente poderá ser obtida se usarmos o método `Promises.all()`, que recebe um array de promises como argumento que, ao estarem todas resolvidas, permite gerar uma única `promise` com as respostas, e somente então podemos usar o método `json()`. Se alguma das promises for rejeitada, será retornada uma mensagem de rejeição.

A promise gerada pelo `Promise.all()` é um array com 3 objetos response. Para desencapsularmos e exibirmos um a um, usamos o método `forEach()`.

Sintaxe da requisição fetch paralela:
```js
const getData = async () => {
    const data1 = fetch(endpoint 1)
    const data2 = fetch(endpoit 2)

 bloco de instruções

}

    const result = await Promise.all([data1, data2])
    result.forEach( async response => console.log(await response.json())) // callback assíncrona para desencapsular os dados
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
