### ISSUE TITLE
Destructuring Assignment

### ISSUE THREAD

**Issue by brenoSSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#34]
Oi Roger, a minha dúvida é em relação a essa expressão. Após a correção dos exercícios dessa aula eu abri o mdn pra poder entender melhor sobre ela. Entendi que é uma expressão que usamos pra poder desempacotar valores de arrays e propriedades de objetos. O ponto que me gerou a dúvida é o seguinte: Temos sempre que declarar as variáveis do lado esquerdo da atribuição com o mesmo nome das propriedades do objeto a ser desestruturado?

**Comment by Roger-Melo** [comment]
Oi Breno!

Para ficar mais fácil eu identificar qual aula você está se referindo, prefira mencionar o nome da aula na plataforma. Exemplo: etapa 1, vídeo "Correção dos exercícios da aula 03 - Aula 04-01".

Aí fica mais fácil para eu encontrar e entender a sua dúvida =)

Mas, suponho que esteja se referindo à aula onde apresentei o destructuring.

> Temos sempre que declarar as variáveis do lado esquerdo da atribuição com o mesmo nome das propriedades do objeto a ser desestruturado?

Isso. Em uma expressão de destructuring, as variáveis sempre são declaradas do lado esquerdo do sinal de atribuição.

No começo é meio estranho. Afinal, estamos acostumados a ver a sintaxe de objetos `{}` sempre após o sinal de atribuição.

Mas as variáveis não necessariamente precisam ser declaradas com o mesmo nome da propriedade do objeto.

Porém, se você está na aula em que eu apresentei o destructuring, não se preocupe com esse aspecto agora.

Nas aulas seguintes, aos poucos eu mostro mais casos de uso dele em diversos contextos =)

A aula que você se referiu é a aula de apresentação do destructuring?

@brenoSSilva

**Comment by brenoSSilva** [comment]
Foi na correção dos exercícios 13, no primeiro exercício você usou o
destructuring

>

**Comment by Roger-Melo** [comment]
Conferi aqui, é isso mesmo. Nesse vídeo eu apenas apresento a feature =)

> Temos sempre que declarar as variáveis do lado esquerdo da atribuição com o mesmo nome das propriedades do objeto a ser desestruturado?

Sim. Mas como eu disse no comentário acima, com a prática você se acostumará com a sintaxe. Essa feature ainda será muito explorada nas aulas posteriores, então você ainda a treinará bastante =)

Esclareci sua dúvida?

@brenoSSilva

**Comment by brenoSSilva** [comment]
Muito obrigado Roger, esclareceu sim, eu andei treinando a feature
separadamente e consegui entender =)

>
