### ISSUE TITLE
Resumo da todas as aulas da etapa 3

### ISSUE THREAD

**Issue by mrp99** [roger-melo-treinamentos/curso-de-js-roger-melo#3410]
O que são funções - Aula 01-02 - Etapa-3:
Permitir criar um bloco de código, e executar esse bloco de
código quando quiser.
=========================================================
Function declaration, function expression e hoisting 
- Aula 01-03:
hosting - evocação somente para function declaration (function ()...) 
vai para topo do arquivo independente de onde for invocar. Para as
function expression (const msg = function ()...) NÃOOOOOOO!!Erro 
esperado para expression - Cannot access 'showFood' 
before initialization. Declarar as funções no topo do código.
=========================================================
Argumentos, parâmetros e default parameters - Aula 01-04:
Argumentos = myFunc('valor'), ao inserir um valor entre aspas torna-se argumento.
Parâmetros = (name), aqui o name é um parametro.
parametro dentro do escopo da função nao tem ordem de precedência, mas os argumentos
tem ordem SIM!
Default parameters dentro da função qdo os parametros estao especificados exemplo
(name = 'Estrôncio', lastName = 'Almeida') e ao invocar a função myFunc(), não
for passado nenhum argumento, irá assumir o valor default.
=========================================================
Retornando valores e exercícios - Aula 01-05:
variáveis locais que só existem dentro do escopo da função, não possível fora do escopo
utiliza-las. a menos que se utilize o return e variável ai possível usar ela fora do escopo.
armazenando ela numa variável e podendo chamar ao qualquer uso que quiser.
=========================================================
Arrow functions - Aula 02-02:
forma mais consija de implementar funções de forma simples é basicamente uma simplificação com alguns adicionais.
1 forma) const double = (number) =>{ return number * 2 ;}
Quando somente existe uma unica expressão possivel tirar os parêntese, mas somente para um parâmetro.
1 forma) const double = number =>{ return number * 2 ;}
parâmetro default tem que vir em parêntes, valor de expressão exemplo abaixo:
const double = number => number * 2; não necessita do return e nem {}. o valor implícito retornável.
=======================================================
Funções vs Métodos - Aula 02-03:
Método é uma função, o que diferencia ambos é invocação da função ou do método onde ele for declarado.
método é invocado através do ponto o qual da possibilidade de referencia ao determinado fim, mas são 
funções associadas objetos ou aos tipos de dados.
=======================================================
Utilizando callbacks e exercícios - Aula 02-05:
Uma função callback é uma função passada a outra função como argumento, que é então invocado dentro 
da função externa para completar algum tipo de rotina ou ação.
forEach é para cada iteração. ou cada item do array.

**Comment by Roger-Melo** [comment]
Show @mrp99. Vamo que vamo, rumo à fluência! 🙌
