### ISSUE TITLE
Minha modificação foi eficaz?

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#3412]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 06 da etapa 11 - Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1393459

### Descreva a dúvida

/*
  Neste exercício, vamos praticar um pouco do que vimos até aqui, através da 
  API do GIPHY, que é um website de GIFs (https://giphy.com/).

  - Seu desafio é implementar uma funcionalidade de busca dos GIFs. Quando o 
    usuário digitar o termo de busca no input e pressionar enter, um GIF deve 
    ser exibido na tela. Como neste exemplo: https://youtu.be/RHe-uCJGCeA
  - Observe que o GIF mais recente é inserido acima dos GIFs anteriores;
  - Para fazer requests para a API do GIPHY, você precisará de uma API key. 
    Para obtê-la, siga os seguintes passos:
    - Acesse https://developers.giphy.com/dashboard/ e faça o login;
    - No Dashboard, clique em "Create an App", clique em "API Selected" e em 
      "Next Step";
    - Dê um nome e descrição para o app e crie-o;
    - Clique no código da API key para copiá-la;
  - O submit do form deve ser feito para o endpoint abaixo. Atente-se para os 2
    [PLACEHOLDERS] que devem ser substituídos:
    - https://api.giphy.com/v1/gifs/search?api_key=[SUA_CHAVE_DA_API_AQUI]&limit=1&q=[VALOR_INSERIDO_NO_INPUT]
    - Se quiser testar outras possibilidades, os endpoints da API estão 
      listados na documentação: https://developers.giphy.com/docs/api/endpoint#search
  - Ignore os avisos no console. Para limpá-lo, pressione "ctrl + L".
*/

#### Bom dia, professor, durante a correção desse exercício você inseriu um "if" para evitar um erro caso o endpoint estivesse incorreto o que fazia com o objeto data retornasse vazio.
Eu segui as instruções mas eu continuava recebendo um erro quando o endpoint estava incorreto, ou se, mesmo com o endpoint correto eu buscava por um gif que não existe.
Tentei a solução abaixo e parece que resolveu meu problema, seja endpoint incorreto ou busca sem resultado, eu vou ter retorno e não receberei um erro como reposta. 
Gostaria de saber se o que fiz também foi uma boa ideia ou se há algum algum problema em fazer desse jeito.

#### Não alterei esse trecho:
```js
const form = document.querySelector('form') 
const GIFSContainer = document.querySelector('div')


const APIKey = 'g69TzPDs0QH0Dvz1cAx3YmDpY3glHWB0'

const getGiphyApiUrl = (GIFName) => 
  `https://api.giphy.com/v1/gifs/search?api_key=${APIKey}&limit=1&q=${GIFName}`

const generateGiphyApiUrl = (downsizedGifUrl, GIFData) => {
  const img = document.createElement('img')
  img.setAttribute('src', downsizedGifUrl)
  img.setAttribute('alt', GIFData.data[0].title)
  return img
}

const fetchGif = async (inputValue) => {
  try {
    const gifApiUrl = getGiphyApiUrl(inputValue)
    const response = await fetch(gifApiUrl)

    if(!response.ok) {
      throw new Error('Não foi possível obter os dados da pesquisa')
    }
    return response.json()
    } catch(error) {
    console.log(`Erro: ${error.message}`)
}
}
```
### Trecho do código que modifiquei:

```js
const insertGifIntoDOM = async (inputValue) => {
  const GIFData = await fetchGif(inputValue)

  //Com o if abaixo ao buscar por um gif que não existe recebo data vazio e nenhum erro é exibido no console :
{data: Array(0), pagination: {…}, meta: {…}}

  if (!GIFData ||!GIFData.data.length > 0) {
    alert('Não há gif para essa pesquisa')
    return
  }

  // Sem o if acima, ou com o if igual ao mostrado em aula, ao pesquisar por gif que não existe, resulta em erro:
  //app.js:66 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'images') at insertGifIntoDOM (app.js:69:43)

  // if mostrado na aula: 
     
  // if(GIFData) {
  //       const downsizedGifUrl = GIFData.data[0].images.downsized.url
   
  //    const img = generateGiphyApiUrl(downsizedGifUrl, GIFData)
    
  //    GIFSContainer.insertAdjacentElement('afterbegin', img)
    // }

      const downsizedGifUrl = GIFData.data[0].images.downsized.url
    
      const img = generateGiphyApiUrl(downsizedGifUrl, GIFData)
    
      GIFSContainer.insertAdjacentElement('afterbegin', img)
  
    }
    // com esse if mostrado em aula continuo recebo erro mesmo se o problema for só uma busca que não encontrou 
correspondência:
    //app.js:73 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'images') at insertGifIntoDOM 
    ```

#### Por fim, deixei o form.reset() dentro eventListener porque em caso de erro ou busca não encontrada o form não limpava.
  ```js  
    form.addEventListener('submit', event => { 
      event.preventDefault()
      
      const inputValue = event.target.search.value  
      
      insertGifIntoDOM(inputValue)
      
      form.reset()  
})
```

Obrigada desde já!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ElaineDelgado!

É uma excelente forma de evitar que o erro seja lançado =)

Se vc preferir, pode deixar a condição à direita do `or` mais concisa. Basta remover `> 0`.

Ficaria assim:

```javascript
if (!GIFData || !GIFData.data.length) {
  // ...
}
```

Dessa forma, se o array `data` contém algum objeto dentro dele, o `if` não será executado (pq `!GIFData.data.length` resulta em false). 

Se `data` contém nenhum objeto, `GIFData.data.length` resultará em zero e como zero é um valor falsy, `!` fará com que `!GIFData.data.length` resulte em `true` e então, o `if` será executado.

Sacou a ideia?

**Comment by ElaineDelgado** [comment]
Sim, saquei a ideia! 
Muito obrigada, professor!

**Comment by Roger-Melo** [comment]
Show. No que precisar, pode abrir uma nova issue =)
