### ISSUE TITLE
Resumo Mais sobre o Spread Operator: Unindo objetos e arrays - Aula 01-05 Etapa -14

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3413]
###  Unindo Objetos e arrays 

 **[spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) operator em array** 
        - Clonar objetos e array;
        - Serve para junta os itens de um array e objetos também;
        - Técnica de mutabilidade (_pilar da programação funcional_);
        - Legibilidade;
        - Evitar bugs;
        - Cria-se um novo obj ou um novo array.
 ```js
// concat => criar uma cópia rasa.
const arr1 = [1, 2, 3]
const arr2 = [4, 5, 6]

const newArr1 = [0, ...arr1, 1.5, ...arr2, 7, 8]

 **spread operator em objeto** 
const obj1 = {prop1: 1, prop2: 2}
const obj2 = {prop3: 3, prop4: 4}

// feature antiga (Object.assign()) também faz cópia rasa
const obj3 = Object.assign({}, obj1, obj2)

// com spread operator (...) estamos criando um novo objeto
const obj4 = { ...obj1, ...obj2 } // técnica de mutabilidade
```

**Comment by Roger-Melo** [comment]
Excelente @carlosdevjs, rumo à fluência! 🎯
