### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by gh-carneiro** [roger-melo-treinamentos/curso-de-js-roger-melo#3417]
## Função da String

- Armazenar textos, links, caracteres e qualquer outra forma de texto.
    - Sempre deve estar entre aspas simples ‘ ‘ ou aspas duplas “ “

---

## Concatenação de strings

- Para unir (concatenar) duas strings utiliza-se o sinal de “+”

```js
const firstName = 'Nathan'
const lastName = 'Drake'
const fullName = firstname + lastname

//Para adicionar um espaço entre as duas strings, deverá adicionar uma terceira string com um espaço em branco

const fullName = firstName + ' ' + lastName
```

---

## Acessando caracteres

- Para acessar um caractere específico de uma string, utiliza-se o número referente a posição do caractere dentro de colchetes
- String em JavaScript é zero-based, ou seja, a contagem começa a partir do 0

```js
console.log(fullName[0])
//Valor exibido no console é 'N'
```

---

## Comprimento de uma string

- Para saber o tamanho de uma string basta utilizar a propriedade .length

```js
console.log(fullName.length)
//Valor retornado no console é 12
```

---

## Métodos de string

- Para utilizar métodos preciso invocá-los com os paracenteses ( )
- Não alteram o valor da string original:
    - .toUpperCase() - Faz com que todos os caracteres da string fiquem maiúsculos.
    - .toLowerCase() - Faz com que todos os caracteres da string fiquem minúsculos.
- .indexOf() - Retorna a posição do caractere passado como **argumento** dentro da string.

**Comment by Roger-Melo** [comment]
Excelente @gh-carneiro, rumo à fluência! 🎯
