### ISSUE TITLE
Resumo - O que é orientação a objetos - Aula 02-05 da etapa 14

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3420]
### Orientação a objetos
 - É uma abordagem, paradigma, forma de programar;
 - É uma forma de programar;
 - JavaScript é fortemente tipada a objetos (Baseada em Prototypes);
 - JavaScript é uma linguagem multiparadigma (OO, Iperativo, funcional), combinando o melhor de cada, você extrai o melhor dos mundos;
 - Existem dois tipo de dados os [Primitivos ](https://developer.mozilla.org/en-US/docs/Glossary/Reference)e os de [Referência](https://developer.mozilla.org/en-US/docs/Glossary/Primitive);
 ___
### Diferença entre criar um Objeto com operador new e um Objeto Literal
Contructor => Quando houver necessidade de converter um  valor do dado.
```js
const obj1 = new Object()
```
Literal =>Sempre preferir criar desta formar,  mais rápida de criar um objeto.
```js
const obj2 = { }
```
___
### O que são construtores e quando usar eles.

Construtores embutidos na linguagem, eles são objetos ou funções para criam um novo objeto
```js
const numbers2 = new Array(1, 2, 3)
const obj = new Object()
```
___
### O que é um Wrapper (envolver) Objeto
Significa que os construtores estão convertendo por baixo dos panos os valores do dado.
Depois que a propriedade ou o método for usado pelo javascript, ele remove da memoria e este valor primitivo volta a ser o valor primitivo novamente.
```js
const name = 'Carlos'
name.length //6

typeof name // 'string'

const name2 = new String('Carlos')  //  Wrapper Object na memória
```
### Null e Undefined
- Não têm nenhuma propriedade ou método;

**Comment by Roger-Melo** [comment]
Excelente @carlosdevjs, rumo à fluência! 🎯
