### ISSUE TITLE
Aplicação: [To-do List]

### ISSUE THREAD

**Issue by ecabral-29** [roger-melo-treinamentos/curso-de-js-roger-melo#3428]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/ecabral-29/CJRM-To-do-List

### Maiores dificuldades durante a implementação

Usar o dataset e o atributo data para ter a referência do item a ser deletado.

### Menores dificuldades durante a implementação

- Refatorar o código
- Isolar as funções

**Comment by Roger-Melo** [comment]
Olá @ecabral-29.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Agora que a análise foi feita via call, vou fechar a issue. 

No que precisar, é só abrir uma nova =)
