### ISSUE TITLE
Duvida sobre o projeto do conversor de moeda

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#3443]
### Etapa da aula

14

### Nome da aula

Exercícios da aula 03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1946514

### Descreva a dúvida

Estou com dificuldade na lógica para pegar os dois valores que os options estão selecionado, estou usando o seguinte para pegar os valores que retorna ao mudar a seleção do options

```js
const valueConverted = document.querySelector('[data-js="currency-one-times"]')
const convertedValueText = document.querySelector('[data-js="converted-value"]')
const selectCurrencyOne = document.querySelector('[data-js="currency-one"]')
const selectCurrencyTwo = document.querySelector('[data-js="currency-two"]')

valueConverted.addEventListener('input', async event => {
  console.log(event.target.value)
  let currencyValue = await getAPIValue()
  let convertedValue = event.target.value * currencyValue
  convertedValueText.textContent = convertedValue.toFixed(2)
})

const getAPIValue = async () => {
  const  {conversion_rate : valueOfCoin } = await 
    fetchData(createUrlAPI('USD', 'BRL')) //passar de forma dinamica
  return valueOfCoin
}

// let optionsValueOne = selectCurrencyOne.options[selectCurrencyOne.selectedIndex].text

// let optionsValueTwo = selectCurrencyTwo.options[selectCurrencyOne.selectedIndex].text

selectCurrencyOne.addEventListener('input', event => {
  let getOptionsValueOne = event.target.value
  console.log(getOptionsValueOne)
})

selectCurrencyTwo.addEventListener('input', event => {
  let getOptionsValueTwo = event.target.value
  console.log(getOptionsValueTwo)
})


// deixei em outra pasta a parte que faz a requisição 
const APIKey = 'f5ec23c1b4f520691c1ed458'

const createUrlAPI = (valueCurrencyOne, valueCurrencyTwo) => 
  `https://v6.exchangerate-api.com/v6/${APIKey}/pair/${valueCurrencyOne}/${valueCurrencyTwo}`

const fetchData = async url => {
  try {
    const response = await fetch(url)
    
    if (!response.ok) {
      throw new Error('Não foi possível acessar os dados')
    }
    return response.json()

  } catch ({ name, message }) {
    alert(`${name} : ${message}`)
  }
}
```
como faço para pegar esses dois valores e passar eles para a função que vai gerar o link para a minha requisição.
Lógico que não quero a resposta, mas apenas aquele empurrão para pensar. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103!

Se o problema que vc está buscando solucionar é marcar um option como selecionado, pesquisa pelo elemento `options` no MDN, mais especificamente na parte de atributos que podem ser setados nesse elemento =)

Vc chegou a popular os selects com os options assim que a página é carregada?

**Comment by Jonatan1103** [comment]
sim, na parte que eu deixei comentado, usei uma propriedade selectedIndex.
```js
let optionsValueTwo = selectCurrencyTwo.options[selectCurrencyOne.selectedIndex].text
```
se jogar no console, irá aparecer a options que já esta selecionada como padrão.

**Comment by Jonatan1103** [comment]
o problema que estou tentando resolver, é pegar os valores desses dois options diferentes e manda-los para o link de requisição. eu consigo pega-los, mas só consigo pegar com o addEventListener, mas como são dois options diferentes, então eu crio 2 addEventListener, e então não sei como passar esses resultados para o link. por que se eu chamasse a função que cria o link em cada addEventListener não daria certo. acredito que estou usando a logica errada de usar eventos para pegar o valor dos options

**Comment by Roger-Melo** [comment]
@Jonatan1103 sobe seu projeto em um repositório no github e me envia o link. Assim eu testo aqui e consigo ajudar com mais precisão =)

**Comment by Jonatan1103** [comment]
meio que entendi oque estava fazendo de errado, na documentação da API, clicando na parte dos endpoints e indo na pair conversion, lá eu peguei o link que da para mandar a moeda que quero ter como referencia e a que quero converter. 

// https://v6.exchangerate-api.com/v6/YOUR-API-KEY/pair/EUR/GBP

eu estava fazendo a requisição por aqui, e ao invés de popular meu select através do javascript, eu populei ele pelo HTML mesmo, então não estava conseguindo.

Porém me veio outro problema kkkkk. mas estou tendo progresso

Obrigado pela atenção professor.

**Comment by Roger-Melo** [comment]
Hahah, massa @Jonatan1103. 

Já que por enquanto o caso está sob controle, vou fechar essa issue. Mas, caso apareça outra dúvida, pode abrir uma nova issue que te ajudo, ok? =)
