### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#3444]
Nesta aula foi explicado o tipo Number e algumas operações que podem ser realizadas.
Também foi apresentado os "atalhos" `+=`; `-=`; `*=`; `/=`; que utilizamos para reatribuir valores a variáveis, e concatenação de números com strings. E a precedências utilizadas na execução dos cálculos .

**Comment by Roger-Melo** [comment]
Show @paulovieiradasilva. Vamo que vamo, rumo à fluência! 🙌
