### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3446]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/santos2408/todo-app

### Maiores dificuldades durante a implementação

- Demorei um pouco para entender como utilizar os dataset dentro do Javascript.
- Tentei utilizar objetos na aplicação, mas não consegui desenvolver uma lógica.

### Menores dificuldades durante a implementação

- Separar as funções.
- Trabalhar com os eventos
- Utilizar métodos de array

**Comment by Roger-Melo** [comment]
Olá @santos2408.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Agora que a análise foi feita via call, vou fechar a issue. 

No que precisar, é só abrir uma nova =)
