### ISSUE TITLE
Resumo da Aula Try/catch em requests e erros personalizados 06-05 da etapa 11

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3448]
Até então, havíamos tratado erros com `catch()`, mas como utilizamos o async/await (que “simula” uma execução de forma síncrona), torna-se mais conveniente utilizarmos o try/catch.

O código construído na aula 05-04 foi refatorado e utilizado para realizarmos um exemplo de tratamento de erros com try/catch. Nesta aula, vimos inicialmente que a requisição via fetch pode ser simplificada usando `then()`, no qual inserimos a função responsável por retornar os dados parseados da promise response. 
```js
const getUsers = async () => {
    const users = await fetch(endpoint).then(response => response.json())
    return users
}
// ou
const getUsers = async () => await
    fetch(endpoint)
    .then(response => response.json())
```
Outra forma foi utilizar a procedência de execução por meio de parênteses, que nos permitiu encadearmos o método `json()` diretamente no bloco no qual se encontra a abertura do fetch. O primeiro `await` espera a resolução do `fetch()`, resultando em um objeto response, e por isso conseguimos encadear diretamente o `json()`, obtendo os valores parseados. Como este método retorna uma promise com array de valores dos objetos parseados, necessitamos de mais um await para desencapsular esta promise.
```js
const getUsers = async () => await (await fetch(endpoint)).json()
```
Para inserirmos o try/catch dentro da função `getUsers()`, desmembramos o código acima, armazenando a primeira promise ( `await fetch(endpoint)` ) em uma constante chamada `response`, dentro do bloco de instruções de try e retornamos o valor deste parseado por `json()`.

Como requisições fetch somente rejeitam promises por erro de conexão de rede, necessitamos de uma condição para que, se acaso ocorresse um erro no endereço da endpoint, este também seja considerado em notificação ao usuário. Desta forma, inserimos um `if` utilizando a propriedade do objeto response (`response.ok`). Esta propriedade resulta em true em status 200 a 299, desta forma, invertemos este resultado para que se resultar em false (qualquer outro valor), obtenhamos true e o bloco de instruções de `if` seja executado.

No bloco de `if`, inserimos `throw new Error()`, que lança um objeto de erro, que será utilizado pelo catch. `Error()` é um objeto de erro genérico, mas existem tipos mais específicos, como **ReferenceError** (variável inexistente referenciada) e **TypeError** (valor passado discrepante do tipo especificado). Usamos o `Error()` e, dentro dele, inserimos a mensagem desejada. Quando há execução desta linha, tudo abaixo dela é ignorado e o objeto gerado é recebido por catch.
```js
try {
    const response = await fetch(endpoint)
    if(!response.ok) {
         throw new Error(‘Não foi possível obter os dados’)
    }
    return response.json()
}
```
A seguir, inserimos o catch, que deve receber o objeto de erro em seus parênteses. Dentro de seu bloco de instruções, simplesmente pedimos para que a mensagem de erro seja exibida no console, para isto, referenciamos sua propriedade message. Se não especificarmos error.message, a mensagem exibida pelo console será _“Error: Não foi possível obter os dados at getUsers (app:js: linha) at async logUsers (app.js: linha)_.
```js
catch (error) {
    console.log(error.message)
}
```
Se houver algum erro na requisição, este não impedirá a execução das linhas de código posteriores à estrutura try/catch.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
