### ISSUE TITLE
Aplicação: [Todo-List]

### ISSUE THREAD

**Issue by MaxOliverrr** [roger-melo-treinamentos/curso-de-js-roger-melo#3451]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/MaxOliverrr/todolist-cjrm

### Maiores dificuldades durante a implementação

Utilizar o dataset e organizar o código 

### Menores dificuldades durante a implementação

A logica em geral

**Comment by Roger-Melo** [comment]
Olá @MaxOliverrr.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
@MaxOliverrr enviei uma mensagem em seu whatsapp. Fico o aguardo da resposta para darmos prosseguimento à análise =)

**Comment by Roger-Melo** [comment]
@MaxOliverrr, vc pode acessar a gravação da sua análise **[aqui](https://drive.google.com/file/d/1yvYagwbwSY1ntDmOGQUGfN3ZxhjDxg8t/view?usp=sharing)** =)
