### ISSUE TITLE
Refatoração de código e funcionamento da função clearInput()

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3458]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/924879

### Descreva a dúvida

Olá, Roger, espero que esteja bem!

Surgiu uma dúvida a partir do minuto 18 da aula citada.

Poderia explicar como funciona a função `clearInput()`?
Pelo que entendi ela irá apagar o conteúdo e chamar o método .focus() da variável `input` , mas essa var não pertence ao seu escopo nem foi declarada no escopo global.. Olhando o código eu consigo inferir que, ao executar a função, ela irá retornar a propriedade .value e o método .focus () que, por possuírem o mesmo nome da var declarada em ` handleSubmit() `  foram executados.

Dessa forma, caso alguém altere o nome da var `input` declarada na função `handleSubmit()`, teria que modificar a função `clearInput()` tbm.
Para evitar que uma alteração em uma função quebre a outra, pensei em fazer dessa maneira:

```js
const clearInput = () => {
  const input = document.querySelector('#input')
  input.value = ''
  input.focus()
}
```
Aí surgiu uma outra dúvida, por que não podemos utilizar a propriedade `.innerText/.textContent` ao invés de `.value `para apagar o conteúdo digitado no input?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira!

> ## Poderia explicar como funciona a função clearInput()?

Respondi a essa dúvida [nesta issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/10).

Se depois de ver essa resposta ainda restar alguma dúvida, é só dar o toque que te ajudo a entender =)

---

> ## Por que não podemos utilizar a propriedade .innerText/.textContent ao invés de .value para apagar o conteúdo digitado no input?

De um ponto de vista de leitura de código, `value` é mais curto e faz mais sentido por deixar explícito que o elemento manipulado é um input.

Além disso, input é um tipo de objeto `HTMLInputElement` (vc verá mais sobre esses tipos de objetos e de onde eles vem na etapa 14), e esse tipo de objeto não possui innerText/textContent como propriedade, como vc pode ver aqui: [HTMLInputElement - MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#properties). E quando isso acontece, a propriedade é buscada na cadeia de objetos prototypes (assunto que vc verá na etapa 14, não se preocupe em entender agora).

`textContent` só irá retornar string preenchida caso o nó do DOM no qual ela foi encadada contenha nós-filhos. Se o nó não tem filhos, `textContent` retorna string vazia. Fonte: [Value - textContent, MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#value).

Já o "inner", de `innerText`, faz referência ao conteúdo que está entre a tag de abertura e a tag de fechamento do elemento.

```html
<p>O que está aqui corresponde a "innerText"</p>
```

`<input>` não tem tag de fechamento, por isso a propriedade `innerText` não funciona nesse elemento.

Faz sentido?

**Comment by BrunodevOliveira** [comment]
Total sentido, Roger! Obrigado!!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
