### ISSUE TITLE
Aplicação: [NOME_DA_APLICAÇÃO]

### ISSUE THREAD

**Issue by Jonatan1103** [roger-melo-treinamentos/curso-de-js-roger-melo#3459]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Jonatan1103/conversor-moedas

### Maiores dificuldades durante a implementação

- Bati muito a cabeça até conseguir usar o end-point certo da aplicação
- A lógica de comparar uma moeda do options com a outra moeda.
-  fatoração também.
- Até pensar em criar um objeto e passar o resultado da requisição para ele, eu estava fazendo muitas requisições. 
- nomear as variáveis e funções, por mais que eu entenda que variáveis são substantivos  e funções são verbos, e não sei porque erro tanto. 

### Menores dificuldades durante a implementação

- consumir  a API, pegar o resultado da API não é tão difícil, pegar o resultado certo que foi. 
- mexer com o DOM.

**Comment by Roger-Melo** [comment]
Olá @Jonatan1103.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
@Jonatan1103, vc pode acessar a análise de sua aplicação [aqui](https://drive.google.com/file/d/1qIx3ijo031dvR5CYQOvbTqNmBzzmx5tq/view?usp=sharing) =)
