### ISSUE TITLE
Aplicação: [ToDoList]

### ISSUE THREAD

**Issue by CamiloMeassiMacoris** [roger-melo-treinamentos/curso-de-js-roger-melo#3462]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/CamiloMeassiMacoris/toDoList

### Maiores dificuldades durante a implementação

A maior dificuldade que eu tive foi refatorar a parte de remove do código usando o dataset e o data, tive que olhar um pedaço da aula de coreção para fazer o refatoramento do código, pois não estava conseguindo fazer funcionar.

### Menores dificuldades durante a implementação

Tanto a refatoranção do código quanto a lógica  das funções implementadas foi tranquilo tirando a parte do remove com o dataset e o atributo data.

**Comment by Roger-Melo** [comment]
Olá @CamiloMeassiMacoris.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Agora que a análise foi feita via call, vou fechar a issue. No que precisar, é só abrir uma nova =)
