### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3467]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Giansantos-carlos/To-DoList.git

### Maiores dificuldades durante a implementação

Utilizar o dataset  e seus atributos,  organizar  o codigo  e dar nome a novas funções e fazer a refatoração do codigo .

### Menores dificuldades durante a implementação

Adicionar novas cores.

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Agora que a análise foi feita via call, vou fechar a issue. No que precisar, é só abrir uma nova =)
