### ISSUE TITLE
Dúvida em relação ao escopo de bloco

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#3475]
### Etapa da aula

4

### Nome da aula

Variáveis e escopo de bloco - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824588

### Descreva a dúvida

Muito boa tarde;

Tenho uma dúvida, há algum comando (ou talvez alguma forma) de acessar uma `const` ou `let` declarada dentro de um escopo de bloco, por exemplo:

```js
const n1 = 10;
const n3 = 34;

if (n1 === 10) {
  const n2 = 45;
  let n4 = 44;
}

console.log(n1, n3); // resulta em 10 e 34
console.log(n2, n4); // resulta em erro
```
Entendo que, se n2 ou n4 fossem declarados como `var`, eu poderia acessá-los. No entanto, sendo `const` e `let`, há alguma forma de eu acessar os valores de n2 e n4 fora do escopo de bloco que eles foram declarados?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MivlaM! =D

No exemplo que vc deu, não há como acessar `n2` e `n4` pois elas estão "presas" dentro do bloco do `if` e só podem ser acessadas lá dentro.

Agora, se o `if` estiver dentro de uma função, os valores dentro do bloco desse `if` podem ser acessados fora da função. Basta que esses valores sejam retornados. Lembrando que `return` é uma palavra-chave que pode ser usada apenas em funções.

```javascript
const getValue = () => {
  if (true) {
    const a = 1;
    let b = 2;
    return [a, b]
  }
}

console.log(getValue()) // [1, 2]
```

No código acima, ao ser invocada, a função retorna um array com os valores de `a` e `b`.

Respondi a dúvida?

**Comment by Roger-Melo** [comment]
@MivlaM cliquei no botão errado e fechei sem querer. Comentando aqui, caso vc não tenha rcebido a notificação =)

**Comment by MivlaM** [comment]
Olá @Roger-Melo!

Entendi! Agradeço pela explicação =)
