### ISSUE TITLE
Aplicação: Quiz interativo

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3477]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/BrunodevOliveira/Quiz-interativo

### Maiores dificuldades durante a implementação

- Refatoração do código

### Menores dificuldades durante a implementação

- Manipulação do DOM

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Você pode acessar a análise do seu quiz **[aqui](https://drive.google.com/file/d/1UshcXs4enBmGiQhSCHB7uExG7rZ-ja3b/view?usp=sharing)** =)

**Comment by BrunodevOliveira** [comment]
Fala, Roger! Torço para que se recupere logo =)

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira!

Vc verá curto-circuito na etapa 11 e a técnica de retorno do objeto será mostrada na etapa 09 =)

Mas apenas para não te deixar sem resposta, vc precisa envolver o objeto em um [grouping operator (parênteses)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping) basicamente para que a engine do javascript não interprete a abertura do objeto (`{`) como a abertura de um bloco da função =)

Começou a fazer sentido?

**Comment by BrunodevOliveira** [comment]
Sim, Roger! Valeu!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
