### ISSUE TITLE
Aplicação: To Do List

### ISSUE THREAD

**Issue by bindwkill** [roger-melo-treinamentos/curso-de-js-roger-melo#3478]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/bindwkill/todolist

### Maiores dificuldades durante a implementação

Refatoração: Eu sempre tenho dificuldades em pensar a partir de onde vale a pena isolar uma parte do código e até onde algo pode compor a mesma função sem perda de legibilidade.

dataset: Nesse ponto eu até cheguei numa solução mas fiquei na duvida se era isso mesmo que o exercício pontuava. Modifiquei a função de deletar to-dos com base nas informações do site da MDN. Acabei tendo que fazer umas alterações no html também para funcionar com os itens que vinham do template.

Estilo: não ficou claro pra mim se tinha que modificar a aparência do template, igual foi no quiz, então apenas troquei para cores azulada, porque eu gosto. Foquei só na programação praticamente.

### Menores dificuldades durante a implementação

As funcionalidades que estamos usando desde antes do quiz foram bem tranquilas, localizar elementos no DOM, adicionar, alterar, remover. Transformar os conjuntos do DOM em arrays para poder iterar neles também foi ok.

**Comment by Roger-Melo** [comment]
Olá @bindwkill.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Você pode acessar a análise do seu to-do [aqui](https://drive.google.com/file/d/11QB9VnMhFunCYa0ZQwi5jMY-z4Zcurt-/view?usp=sharing) =)

**Comment by Roger-Melo** [comment]
Olá @bindwkill! Você pode acessar a análise do seu to-do [aqui](https://drive.google.com/file/d/11QB9VnMhFunCYa0ZQwi5jMY-z4Zcurt-/view?usp=sharing) =)

**Comment by bindwkill** [comment]
Muito obrigado, professor. Fiz varias anotações das coisas que você pontuou. A parte de filtrar os todos explodiu minha cabeça, achei muito legal. haha. Gratidão e rumo a fluência.

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)

Rumo à fluência 🔥
