### ISSUE TITLE
Dúvida - Callback

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#3487]
### Etapa da aula

3

### Nome da aula

O método forEach e callbacks -  Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803293

### Descreva a dúvida

@Roger-Melo, poderia explicar o fluxo do exemplo abaixo feito em aula. Pois não ficou claro para mim, por favor. 
Além de sua explicação, irei pontuar algumas dúvidas.

 * Uma callback  é uma função como argumento? Se sim, isso se aplica a `callback_` e `num` ?
 * Uma callback ora posso invocar como função, ora posso passa-lá como argumento em outra função? (Não havendo obrigatoriedade nas ações que se quer utilizar) 
 Grato!

```js
//Callback

const myFunc = callback_ => {
    const value = 77

    callback_(value)
}

myFunc(num => {
    console.log(num);
})
```

**Comment by Roger-Melo** [comment]
Olá @Bruno-Luna!

> ## * Uma callback  é uma função como argumento? Se sim, isso se aplica a `callback_` e `num` ?

Callback é uma função inserida como argumento da invocação de outra função.

No seu exemplo, `callback_` e `num` são apenas parâmetros. Mas claro, o parâmetro `callback_` recebeu a função que vc inseriu como argumento na invocação de `myFunc`.

A função de callback é a que vc inseriu como argumento de `myFunc`:

```javascript
num => {
  console.log(num);
}
```

---

> ## * Uma callback ora posso invocar como função, ora posso passa-lá como argumento em outra função? (Não havendo obrigatoriedade nas ações que se quer utilizar)

Geralmente, vc invoca um callback. Inclusive, se vc traduzir, a palavra "call" significa "chamar", que por sua vez, é sinônimo de "invocar".

---

Eu fiz um passo a passo que acredito que pode clarear as dúvidas sobre callback. Vou deixar ele aqui:

- [Passo a passo para entender callbacks](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574)

Se após seguir o passo a passo até o final, codando e executando o código, restarem dúvidas, pode perguntar aqui abaixo que te ajudo, combinado? =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
