### ISSUE TITLE
Resumo da Aula Status de respostas HTTP - Aula 02-04 da etapa 11

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3492]
===== STATUS DE REQUEST =====

Ao verificarmos se a resposta foi obtida através do readyState === 4 ficamos sabendo se tudo ocorreu bem. No entanto, só isso não é o suficiente, porque mesmo que a requisição venha a ocorrer algum tipo de erro, por exemplo um endpoist inválido, mesmo assim o request passará por todos os status de resposta chegando no último que é o 4.

Quando o request é feito sem gerar nenhum erro, o status do request terá '200' como valor. Caso o request ocorra algum erro, o estatus retornará '404'.  Portanto, para assegurarmos que a verificação do request foi obtida com sucesso e assim podermos fazer algo com ela, nós podemos verificar o status da requisição.

```.js
request.addEventListener('readystatechange', () => {
   if (request.readyState === 4 && request.status === 200) { // checking status
      console.log(request, request.responseText)
   }
})
```

**Comment by Roger-Melo** [comment]
Show @santos2408. Vamo que vamo, rumo à fluência! 🙌
