### ISSUE TITLE
Duvida - Exercicio 21 - utilização do filter e reduce na mesma função

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3493]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1012887

### Descreva a dúvida

Boa noite. Durante a correção dos exercicios 21 da etapa 08 o ultimo exercício, pede para analisarmos os loopings em nossa aplicação quiz.interativo e deduzir se pode ser substituído por um dos métodos de array ensinados na aula. Eu utilizei uma função para substituir a que pegava as respostas e a que fazia os  cálculos.

Minha duvida seria se utilizarmos 2 métodos dentro de uma função, isso pode atrapalhar a performance da aplicação quando fica mais extensa?

Exemplo do código:
```JS
const proccessUserAnswers = () => {

    const userAnswers = correctAnswers.filter((answer, index) => quizForm[`inputQuestion${index + 1}`].value === answer)
    console.log(userAnswers)
    score = userAnswers.reduce((accumulator, _) => accumulator += 25, 0)
    console.log(score)
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus!

> ## Minha duvida seria se utilizarmos 2 métodos dentro de uma função, isso pode atrapalhar a performance da aplicação quando fica mais extensa?

Não necessariamente. Inclusive, vão haver casos em que isso será preciso =)

Porém, eu vou pedir que vc não se preocupe com performance nesse momento, pois esse é um assunto que vc verá sobre na etapa 14.

Nesse momento, foque em fazer funcionar, sem se importar tanto se o código está "feio" ou "não performático", combinado? =)

**Comment by EneasFeynlinus** [comment]
Ta ok Professor, vou seguir sua dica e focar em fazer o código funcionar e assim melhorar minha fluência em javaScript com o tempo.

Muito obrigado pelo feedback. Tudo de bom!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
