### ISSUE TITLE
Resumo da Aula Encadeando métodos  da etapa 08

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3495]
**Como quando e porque nos encadeamos métodos de array.**
```JS
const books = [
    { name: 'Código Limpo', price: 30 },
    { name: 'O milagra da manhã', price: 5 },
    { name: 'Alice no País das Maravilhas', price: 10 },
    { name: 'Quem pensa Enriquece', price: 50 },
    { name: 'O livro da ciência', price: 30 },
]
```

/*
**Encadeando array books=>**
**- Primeiro** com o método filter buscando a propriedade price maior que 20
**-Segundo** o método map sendo encadeado no resultado de filter. O map agora vai pegar o novo
array com os itens filtrados e adicionar através da interpolação as propriedades name e price
do array filtrado em nossa nova frase `O livro x estaa no valor de y`
*/

```JS
const booksOnSale = books
    .filter(({ price }) => price > 20)
    .map(({ name, price }) =>
        `O livro "${name}" esta no valor de ${price}`)
        console.log(booksOnSale)
/*
const booksOnSale = books
    .filter(({ price }) => price > 20)
    .map(({ name, price }) =>
        `O preço do livro "${name}" caiu para ${price}`)


console.log(booksOnSale)
debugger
*/

```

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
