### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by edu-mendes** [roger-melo-treinamentos/curso-de-js-roger-melo#3496]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/edu-mendes/quiz-interativo

### Maiores dificuldades durante a implementação

Foi criar a exibição de pontos e enviar a implementação para o Github. Pelo terminal, estava apresentado o com erro de origem remota já existente. Só consegui enviar pelo GitHub Desktop. 

### Menores dificuldades durante a implementação

Na explicação da aplicação ficou bastante claro, conseguir progredir até chegar na parte de implementar a pontuação na tela. Consultei o material de aulas anteriores e consegui terminar.

**Comment by edu-mendes** [comment]
@Roger-Melo o repositório está publico agora.

**Comment by Roger-Melo** [comment]
Show @edu-mendes!

Em até 10 dias úteis a análise do seu quiz será feita =)

**Comment by Roger-Melo** [comment]
Olá @edu-mendes! Parabéns pelo esforço 🔥

Vou deixar a análise de seu Quiz [aqui](https://drive.google.com/file/d/1VZEJh-sqm1CwKJBNHcq8s2l-3QZX6sTU/view?usp=sharing) e se houver qualquer dúvida, é só dar o toque =)
