### ISSUE TITLE
Dúvida sobre Array (Exercício #22 da aula 02 - 03-01 e exercício #9 da aula 03 04-01)

### ISSUE THREAD

**Issue by higoroficial-city** [roger-melo-treinamentos/curso-de-js-roger-melo#35]
No exercício #22 você conseguiu acessar apenas uma letra do elemento do array sem usar o segundo colchetes, tendo que usá-lo no exercício #9 da aula 03. Como deu certo? 
PS.: Não lembro de você comentar sobre isso nas aulas anteriores (só por slice() mesmo) e não consegui achar na documentação exemplos do mesmo. Será 'slice()' o jeito mais comum de solucionar esse problema? O que você recomenda Roger?

**Comment by Roger-Melo** [comment]
Oi Higor.

Você se refere à [esse momento](https://youtu.be/e1TG_oQRh9U?t=1579) e [esse momento](https://youtu.be/csd_mOSyCIs?t=760), certo?

No código abaixo,

```javascript
const name = 'walter white'

name[0] // 'w'
```

a expressão `name[0]` contém apenas 1 par de colchetes com o index do caractere da string que eu quero acessar.

Neste outro código,

```javascript
const dogNames = ['Chico', 'Zeca', 'Lilica', 'Nina']

dogNames[0] // 'Chico'
dogNames[0][0] // 'C'
```

com a expressão `dogNames[0]`, o item que está no index 0 do array é acessado.

Se essa expressão `dogNames[0]` resulta no item 'Chico' (que é uma string), eu posso encadear `[0]` nessa string para acessar apenas o 1º caractere dela.

Por isso foi necessário usar os 2 pares de colchetes.

Você usará o `slice()` quando precisar obter uma parte de uma string. Essa "parte" pode conter mais de 1 caractere.

Se precisar obter apenas 1 caractere específico da string, a notação `string[index]` economizará seu tempo de escrita do código.

Respondi sua dúvida Higor?

@higoroficial-city

**Comment by higoroficial-city** [comment]
Respondeu sim Roger.
Eu na verdade viajei aqui, porque no exercício #22 tem apenas uma string, então, naturalmente o index do colchete vai acessar o caractere. Tem duas uma mais strings, será necessário o segundo colchetes como você disse.
Obrigado pela explicação!

**Comment by Roger-Melo** [comment]
Exatamente Higor.

Já que a dúvida foi esclarecida, vou fechar a issue. Mas no que precisar, é só dar o toque =)
