### ISSUE TITLE
Response não retorna array

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#3501]
### Etapa da aula

12

### Nome da aula

Obtendo informações da cidade - Aula 01-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1408269

### Descreva a dúvida

// API Utilizada:  A WEATHERSTACK (meu AccuWeather dá erro 401)
//weatherstack key: ca78332203beacfbb671738c978b759f
//https://weatherstack.com/documentation 

```js
const APIKey = 'ca78332203beacfbb671738c978b759f'

const getCityUrl = cityName => `http://api.weatherstack.com/current?access_key=${APIKey}&query=${cityName}`

const getCityData = async (cityName) => {
  try {
    const cityUrl = getCityUrl(cityName)
    const response = await fetch(cityUrl)

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }

    console.log(await response.json())

  } catch ({name, message}) {
    alert(`${name}: ${message}`)
  }
}
getCityData('rio de janeiro')

 //{request: {…}, location: {…}, current: {…}}
// retorna esse objeto de objetos em vez de uma array com "objetos"  igual ao da aula
```
Por que não retorna array, mas sim objeto?
Já fiz algumas pesquisas mas não encontrei nada sobre retornar um array de objetos, e a documentação dessa API não tem muitos detalhes.

Obrigada

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Nem sempre APIs retornarão um JSON formatado como array de objetos. 

A única certeza que vc tem é que o retorno será um JSON, pois é o formato padrão de dados que trafegam entre client e server side. 

Como mencionado [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1556791), um valor JSON pode ser uma string, número, boolean, null, objeto ou array. São essas estruturas que um JSON pode conter e/ou aninhar =)

Na aula [O que são requests HTTP - Aula 01-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1157208), por exemplo, o request para a [JSON placeholder](https://jsonplaceholder.typicode.com/) retornou um JSON em formato de objeto =)

Ficou mais claro?

**Comment by ElaineDelgado** [comment]
Bom dia, professor!

"Na aula [O que são requests HTTP - Aula 01-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1157208), por exemplo, o request para a [JSON placeholder](https://jsonplaceholder.typicode.com/) retornou um JSON em formato de objeto =)"

Nessa aula mencionada acima, o endpoint restado foi do todo com id 1, ele retorna esse objeto:
```js
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```
Se testarmos o endpoint para todos os "todos" (https://jsonplaceholder.typicode.com/todos) ele retorna uma array com todos aqueles objetos dentro:

```js
`[
  {
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  },
  {
    "userId": 1,
    "id": 2,
    "title": "quis ut nam facilis et officia qui",
    "completed": false
  },
 ...
]
```

Apesar do meu json retornar um pouco diferente, só achei curioso e fiquei em dúvida se era alguma conversão que deixei de fazer.
```js
{
  "request": {
    "type": "City",
    "query": "Recife, Brazil",
    "language": "en",
    "unit": "m"
  },
  "location": {
    "name": "Recife",
    "country": "Brazil",
    "region": "Pernambuco",
    "lat": "-8.050",
    "lon": "-34.900",
    "timezone_id": "America/Noronha",
    "localtime": "2022-04-28 10:32",
    "localtime_epoch": 1651141920,
    "utc_offset": "-2.0"
  },
...
}
```
De qualquer forma só vai mudar a maneira como vou pegar esses dados!
Muito obrigada pelo esclarecimento!

**Comment by Roger-Melo** [comment]
Isso mesmo. Só vai mudar a forma de vc tratar os dados na aplicação, nada que vc já não tenha visto até aqui =)

Mas se rolar qualquer dúvida, pode abrir uma nova issue que te ajudo =D
