### ISSUE TITLE
Aplicação: Quiz Interativo 

### ISSUE THREAD

**Issue by Cs75ceh** [roger-melo-treinamentos/curso-de-js-roger-melo#3504]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/Cs75ceh/Quiz-interativo

### Maiores dificuldades durante a implementação

Github

### Menores dificuldades durante a implementação

mudei os tipos de respostas de A,B,C,D para 1,2,3,4...
demorei 10mns para entender porque a condição de teste não funcionava até usar o typeof e ver que estava comparando strings com numéros. Usei a Number() e deu certo

**Comment by MivlaM** [comment]
Olá @Cs75ceh! 

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua aplicação =)

Eu abri a aplicação, mas identifiquei que a parte que diz respeito sobre a exibição dos pontos na descrição do exercício está em falta.

O enunciado do exercício 19 é o seguinte:

![image](https://user-images.githubusercontent.com/29297788/165510075-7743072e-3075-491a-98ac-3a1cba15d88f.png)

A exibição de pontos será mais trabalhada nas etapas seguintes do treinamento. Porém, por agora é fundamental que você desenvolva em sua versão da aplicação uma exibição de pontos na tela após o botão de envio ser clicado. Você pode conferir as aulas das etapas anteriores do treinamento, pode ser que você tenha alguma ideia de como implementar a exibição de pontos ao revê-las =)

Me avise aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by Cs75ceh** [comment]
Ola Maykell,

Agora mudei o código para que apareçam os pontos na tela.]
Obrigado

**Comment by MivlaM** [comment]
Ok!

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Cs75ceh! Parabéns pelo esforço 🔥

Vou deixar a análise de seu Quiz [aqui](https://drive.google.com/file/d/1Z017rXS857FujiIvbsoxFgVZei989SwH/view?usp=sharing) e se houver qualquer dúvida, é só dar o toque =)

**Comment by Cs75ceh** [comment]
muito obrigado pela analise do Quiz !
Ajustes entendidos (formatação do codigo, declaração explicita da tabela userAnswers, extração da função de callback, toFixed() para remover as decimais do score).

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
