### ISSUE TITLE
console.log com interpolação e apenas separando items retorna output diferente no console.

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3506]
### Etapa da aula

9

### Nome da aula

Exercicio 22 - etapa 09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1039812

### Descreva a dúvida

Boa noite, espero que esteja tudo bem.
Estava refazendo o exercício 22 e ao refazer o exercício 02, imitei como na correção para ver o comportamento do método sort() utilizando o console.log(). No entanto, ao refazer fiz um pouco diferente utilizando a interpolação, porém a interpolação, diferente de separar a string e as variáveis no console, está me retornando essa resposta: 

item1: [object Object] item2: [object Object]

Minha duvida seria, porque ao utilizar, deste modo o console.log(item,item,item) separando os itens por virgula tenho o resultado correto: 

```JS
const charactersOrderedById = characters.map(item => item)
charactersOrderedById.sort((item2, item1) => {
  console.log('item1: ',item1, 'item2: ',item2)
  return item2.id - item1.id
})
```
resultado:

item1:  {id: 3, name: 'Simba'} item2:  {id: 2, name: 'Nala'}
item1:  {id: 2, name: 'Nala'} item2:  {id: 1, name: 'Scar'}
item1:  {id: 1, name: 'Scar'} item2:  {id: 4, name: 'Mufasa'}
item1:  {id: 2, name: 'Nala'} item2:  {id: 4, name: 'Mufasa'}
item1:  {id: 3, name: 'Simba'} item2:  {id: 4, name: 'Mufasa'}

E quando utilizo o console.lo(`item ${interpolação} item ${interpolação]`) tenho o resultado escrito apenas object objetct

```JS
const charactersOrderedById = characters.map(item => item)
charactersOrderedById.sort((item2, item1) => {
  console.log(`item1: ${item1} item2: ${item2}`)
  return item2.id - item1.id
})
```
resultado:

item1: [object Object] item2: [object Object]

Desde já muito obrigado, tudo de bom!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus!

Na aula 01-01 da etapa 14, vc vai ver um caso idêntico, hahah.

Mas basicamente é o seguinte, se o valor que a interpolação receber não for uma string, o JS vai converter esse valor em string.

E ele faz isso, por baixo dos panos, através de um método chamado `toString`.

Olha só, se vc testar o código abaixo,

```javascript
const myNumber = 7

myNumber.toString()
```

uma string '7' é retornada, por que é isso que o `toString` faz. Ele converte um valor em string.

Agora, se vc testar uma const `o` que recebe um objeto com uma propriedade `prop1` que armazena `1`,

ao invocar `o.toString()`, uma string "[object Object]" é retornada:

```javascript
const o = { prop1: 1 }

o.toString()
```

Ou seja, o valor que a interpolação vai renderizar é o resultado de uma execução do `toString` tentando converter um objeto em string =)

Ficou mais claro?

**Comment by EneasFeynlinus** [comment]
Bom dia @Roger-Melo

Poxa agora com sua explicação, tudo ficou mais claro. Como estava colocando a variável item2 na interpolação estava entregando o objeto com 2 propriedades id e name para a interpolação então o toString transformava o objeto em string mas sem separar cada propriedade do objeto. Essa explicação sobre o toString() que não tinha ideia, me lembrou de um método que você ensinou umas aulas passadas, o Number para transformar um texto de um elemento HTML em numero e incrementá-lo. 

Ficou super claro, muito obrigado professor!

Tudo de bom e um ótimo dia!

**Comment by Roger-Melo** [comment]
Legal! Qualquer nova dúvida que surgir, é só abrir uma nova issue =)
