### ISSUE TITLE
map() X forEach()

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3507]
### Etapa da aula

8

### Nome da aula

O método map - Aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986668

### Descreva a dúvida

Olá, Roger!

Estou com algumas dificuldades em saber a diferença entre esses dois métodos e quando utilizar um ou outro, principalmente se é "errado" utilizar um no lugar do outro.

Eu refiz o último exemplo que vc utilizou para ilustrar o uso do map() usando o forEach() e, apesar de gerar mais código, aparentemente funcionou:

``` js 
const products = [
  { name: 'Mouse Sem Fio', price: 30 },
  { name: 'Pen Drive', price: 25 },
  { name: 'Cartucho de Tinta', price: 50 },
  { name: 'Suporte Ergonômico para Notebook', price: 23 },
  { name: 'Repetidor de Sinal Wi-Fi', price: 44 }
]
const saleProductsForEach = []

products.forEach(product => {
  if(product.price >= 30) {
    return saleProductsForEach.push({ name: product.name, price: product.price / 2 }) 
  }
  return saleProductsForEach.push(product)
})
``` 
Eu anotei que umas das principais diferenças entre eles é que o forEach não retorna um valor, mas no exemplo acima estou retornando, não?

Uma segunda dúvida é o motivo de não poder reatribuir o valor de uma propriedade sem que esse valor seja reatribuído ao array "original". Como o map() gera um novo array, pq esse erro ocorre?
``` js 
const saleProducts = products.map(product => {
  if(product.price >= 30) {
     product.price = product.price / 2 
     return product
  }

  return product
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira!

> ## Estou com algumas dificuldades em saber a diferença entre esses dois métodos e quando utilizar um ou outro, principalmente se é "errado" utilizar um no lugar do outro.

Vc deve usar `map` quando precisar obter um array com a mesma quantidade de itens do array original. Geralmente, vc vai desejar que os itens desse array sejam uma versão "transformada" dos itens do array original.

Já o `forEach` deve ser usado quando vc precisa executar efeito colateral. Na aula 02-01 da etapa 8, vc verá o que "efeito colateral" significa, e no decorrer do treinamento, verá (do ponto de vista funcional) pq vc deve buscar ter sempre o mínimo possível de efeito colateral em suas aplicações.

Saber quando usar um método ou outro é um assunto que vc ainda verá diversas vezes no treinamento. A aula 01-02 da etapa 8 é apenas uma introdução à map, filter e reduce. Mas claro, se dúvidas quanto a isso forem surgindo, é só perguntar =)

---

> ## Eu anotei que umas das principais diferenças entre eles é que o forEach não retorna um valor, mas no exemplo acima estou retornando, não?

`forEach` [sempre retorna undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#return_value). 

```javascript
// versão com return implícito da arrow function
console.log(
  [1, 2, 3].forEach(item => item)
) // undefined

// versão com return tradicional
console.log(
  [1, 2, 3].forEach(item => {
    return item
  })
) // undefined
```

No código acima, `undefined` é retornado, independente do valor que vc tente retornar no callback do `forEach`.

Quando vc usa o map, `return` é usado para inserir o item no array e o map retorna o array:

```javascript
// versão com return implícito da arrow function
console.log(
  [1, 2, 3].map(item => item * 2)
) // [2, 4, 6]

// versão com return tradicional
console.log(
  [1, 2, 3].map(item => {
    return item  * 2
  })
) // [2, 4, 6]
```

---

## Return x push

No primeiro exemplo de código que vc deu, o `return` ali não faz sentido...

```javascript
products.forEach(product => {
  if (product.price >= 30) {
    return saleProductsForEach.push(/* ... */) 
  }
  return saleProductsForEach.push(/* ... */)
})
```

Pq vc usaria o return à esquerda do `push`, sendo que em nenhum lugar da aplicação há a necessidade de usar o valor que a invocação do `push` retorna?

Em vias de regra, vc deve usar return para fazer algo com o valor que esse return está retornando. 

---

> ## Uma segunda dúvida é o motivo de não poder reatribuir o valor de uma propriedade sem que esse valor seja reatribuído ao array "original". Como o map() gera um novo array, pq esse erro ocorre?

O map gera um novo array, mas isso não significa que os objetos dentro desse novo array são cópias dos objetos originais. 

No seu exemplo, o parâmetro `product` é apenas uma referência para objeto em memória, e não uma cópia.

Lembre-se que parâmetros **são variáveis** locais de uma função e veja novamente a aula [Tipos de refêrencia vs Tipos primitivos - Aula 03-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/831889). Ela irá te ajudar a clarear esse assunto =)

Quando vc usa sinal de atribuição em um lugar que não seja a declaração da propriedade ou variável, vc está reatribuindo valor. E como `product` armazena o objeto original, a operação abaixo mudou o valor do objeto original.

```javascript
product.price = product.price / 2
```

Ficou mais claro?

**Comment by BrunodevOliveira** [comment]
Entendi agr, Roger! Muito obrigado pela explicação!

**Comment by Roger-Melo** [comment]
Show! Qualquer dúvida que surgir, é só abrir uma nova issue =)
