### ISSUE TITLE
Resumo da Aula Adicionando to-dos - Aula 01-03 da etapa 09

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3513]
Quando escrevemos algo na janela do form, a pagina recarrega. No entanto, o que queremos
de verdade seria adicionar mais itens a nossa lista de to-do e não carregar a pagina.
E para isso, primeiro vamos referenciar nosso form para trabalhar com o input.
Para remover espaços em branco antes e depois da string estamos utilizando o método
trim()

Logo após através do event, vamos pegar o name do elemento input do form, que tem o mesmo
nome que o ID geralmente, vamos encadear o nome do name que seria add no target que foi
encadeado o eventListener e finalizar encadeando com o value que nos entregará o valor
do input.

Vamos armazenar o event.target.add.value em uma variável pra utilizar na hora de adicionar
os itens da todoList que no caso serão as Lis adicionadas no elemento UL

como queremos que a li adicionada seja igual as anteriores e siga um padrão vamos copiar
as classes de bootStrap e do fontAwesome para dar o mesmo estilo as novas lis de nossa
lista.

Para evitar que um item sem nada seja enviado vamos criar uma condicional que recebe o 
valor booleano do comprimento do input, caso nao seja escrito nada o valor de length
será 0 e 0 é um valor falsy enquanto os demais números são truthy.

No final em nosso listener de eventos vamos utilizar o método reset no nosso event.target
pois e legal acostumar a utilizar o objeto event para utilizar em frameworks mais avançados
como react.

```JS
const formAddToDo = document.querySelector('.form-add-todo')
const unorderedList = document.querySelector('.todos-container')

formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()
    if (inputValue.length) {
        unorderedList.innerHTML += `
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>${inputValue}</span>
            <i class="far fa-trash-alt delete"></i>
          </li>
        `

        event.target.reset()
    }
})
```

**Comment by Roger-Melo** [comment]
Boa @EneasFeynlinus, rumo à fluência! 🔥
