### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by vitorsmessias** [roger-melo-treinamentos/curso-de-js-roger-melo#3514]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação

https://github.com/vitorsmessias/quiz-interativo

### Maiores dificuldades durante a implementação

Minha maior dificuldade foi na utilização do método insertAdjacentElement, além de alguns problemas que tive com a estilização utilizando o método classList.add e o setAttribute.

### Menores dificuldades durante a implementação

Minha menor dificuldade foi realizar a mudança de cores da aplicação

**Comment by Roger-Melo** [comment]
Olá @vitorsmessias.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @vitorsmessias! Parabéns pelo esforço 🔥

Vou deixar a análise de seu Quiz [aqui](https://drive.google.com/file/d/1JnJpHBV7IbIyaFJcEmtRjZ78jZUJhzhe/view?usp=sharing) e a issue que mencionei na análise [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563). 

Se houver qualquer dúvida, é só dar o toque =)
