### ISSUE TITLE
quando o classList é encadeado diretamente no event.target dentro de uma variável da erro, diferente de encadear na variável que guarda o event.target

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3523]
### Etapa da aula

9

### Nome da aula

Removendo to-dos - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1067824

### Descreva a dúvida

Boa noite professor @Roger-Melo espero que esteja tudo ok!

Um feliz dia do trabalhador, por ser programador e um ótimo professor e mentor.

Minha duvida seria a seguinte. Depois de adicionar o listener de eventos no elemento UL referenciado no todoContainerlist e pegar o objeto event para trabalhar dentro o addEventListener. Esta acontecendo algo que não entendi na hora de praticar.
Quando eu encadeio o classList no event.target dentro da variável clickedElement, na hora que ele é executado na condicional como um boolean eu recebo esse erro: -> Cannot read properties of undefined (reading 'remove')
    at HTMLUListElement.<anonymous>
    
```JS
    todoContainerList.addEventListener('click', event => {
    const clickedElement = event.target.classList
    if (Array.from(clickedElement).includes('delete')) {
        clickedElement.parentElement.remove()
    }
})
```

Diferente de quando faço como depois vi que você fez em sua explicação encadeando o classList na variável que guarda o event.target dentro da condicional, que acaba dando certo.

```JS
todoContainerList.addEventListener('click', event => {
    const clickedElement = event.target
    if (Array.from(clickedElement.classList).includes('delete')) {
        clickedElement.parentElement.remove()
    }
})
```

Minha duvida seria a seguinte, não seria a mesma coisa encadear o classList diretamente no event.target ou no event.target dentro de uma variável?

Dede já, muito obrigado por tudo.

@Roger-Melo

**Comment by bindwkill** [comment]
Posso tentar ajudar?

O problema não está na logica do if, e sim o que está acontecendo dentro dele.

Esse erro acontece quando invoca o método remove(), certo? Isso acontece porque, no primeiro código, clickedElement não é um elemento do html, só a lista de classes css. Por isso ele não possui a propriedade 'parentElement' e consequentemente 'remove()' não existe.

O problema não está na logica do if, e sim o que está acontecendo dentro dele. Se trocar a const 'clickedElement' pelo que ela representa, vai reparar que no primeiro código você está encadeando ``event.target.classList.parentElement.remove()``

**Comment by EneasFeynlinus** [comment]
Boa noite @bindwkill e @MivlaM . Espero que tudo esteja bem por ai !

Poxa fez todo sentido sim =D, depois de ler algumas vezes as respostas de vocês olhar, no MDN e o código entendi aonde estava errando.

Muito obrigado mesmo pela ajuda de vocês, fiquei  muito feliz de entender. Realmente não tinha percebido que estava encadeando o método remove() que deve ser utilizado para remover  um elemento do DOM. Estava utilizando o método remove para remover uma classe do classList que na verdade é uma propriedade de leitura com um DOMToken list das classes CSS para trabalhar encima do elemento capturado no event.target. Como explicado por vocês. 

Por isso estava recebendo undefined, o remove esperava receber um elemento como argumento, no entanto estava entregando um DOMtoken list com as classes do elemento. Coisas pequenas, mas que pegam de surpresa um iniciante.

Muito obrigado pela ajuda no entendimento. @bindwkill @MivlaM 

@EneasFeynlinus 
Best regards.

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, se tiver mais alguma dúvida, não hesite em abrir uma nova issue!
