### ISSUE TITLE
Metodologia ATER

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3528]
### Etapa da aula

1

### Nome da aula

Não se refere a uma aula específica

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf

### Descreva a dúvida

Existe algum vídeo na plataforma explicando a metodologia ATER? Se não, como faço para ter maior detalhamento sobre o método.

OBS: A etapa e o link da aula no formulário acima apenas foi preenchido por ser obrigado, mas não se refere a dúvida. 

@Roger-Melo

**Comment by lucian-bonifacio** [comment]
Por exemplo:
Estou confuso com o "T", pois não lembro a parte da leitura (uma forma especial de leitura) e também o resumo, este é feito no "R", revisão?

Pois bem, preciso aprender melhor sobre o método ATER para ir firme no projeto CJRM.

**Comment by Roger-Melo** [comment]
Olá @lucian-bonifacio!

Na primeira etapa, logo após os exercícios da aula 01, você encontrará um post que contém um vídeo sobre o ATER. 

Se após ver o vídeo restar alguma dúvida, pode abrir uma issue que te ajudo, combinado? =)

**Comment by lucian-bonifacio** [comment]
Olá @Roger-Melo 

Acabei de assistir o vídeo que você citou, por duas vezes.

Esse link demonstra algumas anotações: https://docs.google.com/document/d/1x_HqZ9KpniFQ3tqAj_95XzlFCwbmAxNd9jfZICjE6OQ/edit?usp=sharing

Minhas dúvidas:
- A única hora que eu vejo se falar em resumo é na etapa de TEORIA, correto? Nesta etapa, explica-se que a teoria é realizada principalmente no MDN. A dúvida então: Na REVISÃO, eu consulto os resumos realizados no MDN?
- Ainda em TEORIA, o professor cita visualição/ imagens, e ainda dá exemplo de um livro com desenhos. Na prática, como isso se aplica no ATER?
- Na explicação da etapa de TEORIA o professor não cita sobre anotações durante a aula, contudo, na etapa de revisão ele cita. É recomendado fazer anotações durante a aula, portanto?
- Na etapa de EXERCÍCIOS, o professor disponibiliza ele no SDG e exercícios modelo? Pergunto pois no vídeo proposto o professor cita para resolver os "exercícios resolvidos do MDN" para depois "os propostos pelo professor".
- Na etapa de REVISÃO, é citado que eu é importante resolver exercicíos modelo toda vez que revisado o conteúdo, contudo, onde eu encontro "exercícios modelo"?
- Por último, qual a periodicidade que você indicar praticar a REVISÃO?

Desculpe a quantidade de perguntas, porém eu quero aprender bem sobre essa metodologia pois já comprei vários cursos e tenho o sentimento de nunca evoluir. Quero praticar bem esta metodologia para entender se o problema está em mim, pois já estou começando a me achar burro rsrs!

**Comment by EneasFeynlinus** [comment]
@lucian-bonifacio Bom dia tudo bem. Sou anluno do professor Roger Melo, também estou no cominho de aprender a programar em javaScript e obter a fluência na linguagem e vi sua pergunta, gostaria de te ajudar com o que entendi.

O método ATER foi uma forma do professor Roger Melo criar uma siglas para ser mais fácil você lembrar de um algoritmo que neste caso você vai encaminhar seu cérebro. Como nossa genética não vem com a razão pronta, devemos construí-las com esforço quase que semelhante a exercício físico, é desgastante necessita esforço, mas no longo prazo te traz um retorno.

O método ATER, ele encaminha você para focar:

A -aula : Em cada aula que o professor Roger Melo te dará ao longo do curso, será muito importante você tomar suas notas, de  sua maneira, aquela que você se sente mais confortável, o importante aqui é você ter um mapa para o passado daquilo que você viu de novo com a aula, pontos importantes, tópicos e subtopicos desses pontos. Você tem vários tipos de anotações a mais fácil para nós seria titulo e paragrafo explicando o que entendi, isso porque, foi assim que a escola disciplinou seu cérebro e não tem problema nisso, lembrando que o foco é aquilo que te deixa confortável. Porém, você tem alguns tipos de anotações que pode pesquisar a fundo se quiser adotar ou não, como mapas mentais, linhas gerais e o famoso Cornell. Lembrando que o ponto aqui é você aprender com a aula e tomar nota para consultas futuras, pois você vai precisar.

T-teoria: A teoria, vem com você agora lendo o MDN que seria o Mozila Developer Network ele é a bíblia o livro oficial de quem trabalha com front e back end. Ele te dará a documentação, ou uma explicação oficial de tudo aquilo que pode ser possível e explorado no javaScript. Como ele é muito extenso, o ideal como o professor indica caso você esteja iniciando seria ler sobre aquilo que você viu na aula assistida e se necessário complementar suas anotações sobre a aula, isso ajuda no ciclo do método ATER o no seu aprendizado, pois seu cérebro precisa de repetição e rever aquilo que você quer armazenar no seu HD auhuauhu senão, caso você não reveja, a informação será tratada como a memoria RAM e descartada ao desligar, no nosso caso dormir.

E -exercício: Não se preocupe, o professor Roger Melo selecionou os melhores exercícios, para respeitar aquilo que ele explica no método sobre ir aumentando gradativamente a dificuldade,  tem que ser algo cadenciado que te desafie mas também não seja algo muito além daquilo que você está aprendendo. E acredite os exercícios do professor são ótimos, antes pegava exercícios na internet, no entanto, copiava os exercícios e muitas vezes não entendia o que estava fazendo, diferente do modo que professor faz para você atingir a fluência em javaScript.

R-revisão: Este é o ponto que você assistiu a aula, tomou suas notas, revisou suas notas, foi ler a teoria oficial no MDN relacionado a aula assistida, melhorou suas notas, fez o exercício, quebrou a cabeça, talvez tenha falhado ou mesmo não conseguido fazer o exercício após um tempo de tentativa, no entanto, viu a correção e aprendeu com a correção uma maneira nova de pensar e resolver problemas relacionados a programação com javaScript. Você vai revisar tudo novamente, suas notas a leitura refazer os exercícios, para avançar para a próxima aula que utilizará como base aquilo que você viu nas aulas anteriores aplicando o método ATER, e pelo que entendi, a parte da revisão ela entra em todo o processo, na aula, na teoria, e no exercício. 

E um comentário final relacionando o método ATER, teve uma cientista Marian Diamond uma neuroanatomista da Universidade da Califórnia que na década de 1980 obteve para pesquisa cortes do cérebro de Alber Einstein, sim quando ele morreu, o mundo pensava que ele tinha um super cérebro um cérebro alienígena de gênio e retirou para pesquisa, cedido por ele lógico. Mas é ai que Diamond nos elucidou algo escondido, que na época desanimou as pessoas durante a morte de Einstein o cérebro dele era do mesmo tamanho senão menor do que a média dos cérebros da humanidade. No entanto, Diamon olhando cautelosamente e com seu conhecimento, observou que o cérebro de Einstein continha um numero anormal de células Gliais, mas que bulufas são células gliais? Essas células são responsáveis por nutrir e ajudar na transferência dos sinais eletroquímicos entre os neurônios e quanto mais células gliais você tem no seu cérebro mais conexões neurais você fez em vida, sim esses foram os músculos que albert Einstein construiu ao longo da vida, como ele criou muitas conexões neurais estudando, lendo, pensando e se desafiando ele criou muitas regiões onde um neurônio( células de nosso cérebro)
se comunicam e trocam informação com outro e assim o seu corpo teve de produzir mais células gliais para manter as vias de conexões entre eles saudáveis. Então o esforço e a repetição individual de cada um que faz toda a diferença, o método é o caminho que vai te facilitar nessa musculação da mente e da razão.

Desculpa a resposta extensa, espero ter ajudado com algo.

Tudo de bom!

**Comment by Roger-Melo** [comment]
Olá @lucian-bonifacio.

Apenas complementando o que o @EneasFeynlinus disse...

> ## A única hora que eu vejo se falar em resumo é na etapa de TEORIA, correto? Nesta etapa, explica-se que a teoria é realizada principalmente no MDN. A dúvida então: Na REVISÃO, eu consulto os resumos realizados no MDN?

Vc pode fazer resumos das aulas também.

O resumo é apenas uma ferramenta de consulta. Basicamente, ao ter dificuldades em algum assunto que vc já viu, provavelmente vc precisará consultar algum material. Esse material pode ser seu resumo da aula ou do MDN.

---

> ## Ainda em TEORIA, o professor cita visualição/ imagens, e ainda dá exemplo de um livro com desenhos. Na prática, como isso se aplica no ATER?

Eu disse que ter esse tipo de apoio pode ajudar. Mas nem sempre vc vai encontrar isso. Nas aulas do CJRM, por exemplo, sempre que possível, principalmente em assuntos um pouco mais complexos (como prototypes e operações assíncronas, por exemplo), eu mostro o conceito em imagens antes de mostrar na prática. Assim, primeiro vc entende visualmente. Alguns conceitos fixam mais na mente quando vc os estuda assim.

---

> ## Na explicação da etapa de TEORIA o professor não cita sobre anotações durante a aula, contudo, na etapa de revisão ele cita. É recomendado fazer anotações durante a aula, portanto?

Sim. Como mencionei acima, resumo é ferramenta de revisão. Se seu resumo te traz clareza no momento de dúvida, ele cumpriu seu papel.

---

> ## Na etapa de EXERCÍCIOS, o professor disponibiliza ele no SDG e exercícios modelo? Pergunto pois no vídeo proposto o professor cita para resolver os "exercícios resolvidos do MDN" para depois "os propostos pelo professor".

Sim, sempre que possível refaça os exercícios do MDN, digitando caractere por caractere, mesmo que num primeiro momento isso pareça ser apenas "copy/paste". Essa prática pode te ajudar a criar memória muscular de sintaxe da linguagem.

---

> ## Na etapa de REVISÃO, é citado que eu é importante resolver exercicíos modelo toda vez que revisado o conteúdo, contudo, onde eu encontro "exercícios modelo"?

Os exercícios das baterias de exercícios do CJRM seguem uma SDG. Geralmente, os últimos 2 exercícios de cada bateria são mais complexos, pois são exercícios-modelo.

---

> ## Por último, qual a periodicidade que você indicar praticar a REVISÃO?

Se vc estudar todos os dias, já estará praticando revisão periodicamente.

Vc vai revisar sob demanda.

Todo exercício vai demandar um conhecimento que vc viu no treinamento. Se vc seguir o que recomendei no post [Aviso sobre a correção dos exercícios](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661), estará revisando o conteúdo sob demanda =)

Além da revisão sob demanda, tem também a [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1985) que vc pode fazer antes de implementar cada aplicação do treinamento, como recomendei na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928).

Está ficando mais claro?

---

Não precisa pedir desculpas, estou aqui para ajudar. Pode perguntar sempre que quiser =)

**Comment by lucian-bonifacio** [comment]
Muito obrigado @EneasFeynlinus e @Roger-Melo .

Ficou bem mais claro agora. Já fiz duas páginas de '"resumo" somente sobre a metodologia ATER =)

Agora vou dar seguimento a aula.

Valeu
