### ISSUE TITLE
Resumo da Aula Template strings 02-06  da etapa 01

### ISSUE THREAD

**Issue by tonymatheus** [roger-melo-treinamentos/curso-de-js-roger-melo#3537]
**Template Strings**

Usaremos sempre que a string precisa conter variáveis ou precisa conter aspas ou é um template html . Essa feature nos dá a opção de inserir variáves dentro de uma string sem precisar fechar string declarar um mais e etc, ou seja facilita bastante o trabalho com strings e variáveis .

Templates HTML

podemos usar template string para fazer isso tbm 

ex:

```jsx
const postTitle = "É bolacha ou biscoito";
const postAuthor = "tony Matheus";
const postComments = 16;

// const postMessage =
//   " Opost " +
//   postTitle +
//   " Do " +
//   postAuthor +
//   " tem " +
//   postComments +
//   " Comentários";

const postMessage = `Ò Post ${postTitle} do ${postAuthor} tem ${postComments} comentários`;
console.log(postMessage);

const html = `

    <h2>${postAuthor}</h2>
    <p>${postAuthor}</p>
    <span>${postComments}</span>

`;

console.log(html);
```<!-- Escreva/insira as imagens após essa linha -->

**Comment by Roger-Melo** [comment]
Excelente @tonymatheus, rumo à fluência! 🎯
