### ISSUE TITLE
Resumo da Aula A importância de você ter escolhido o Javascript (Aula 01-02) da etapa 01

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3538]
# A importância de você ter escolhido o JavaScript - Aula 01-02 - Resumo

## Por que escolher o JS?
O Javascript é uma linguagem universal que permite criar:
- Aplicativos e páginas ***web***
- Aplicativos para dispositivos móveis
- Servidores
- etc.

## E o que vamos fazer nesse curso?
Vamos nos concentrar no uso do Javascript no navegador, voltado para o ***front-end***.

## Quais são as vantagens do Javascript no navegador?
- Experiência do usuário melhor
- Páginas mais interativas
- Busca de dados
- etc.

## Quais serão os conceitos básicos que vamos aprender nesse curso?
Vamos aprender conceitos básicos como variáveis, funcões, ***loops***, etc.

## E quais serão os conceitos avancados que vamos aprender nesse curso?
Aprenderemos código assíncrono, programacão funcional, programacão orientada a objetos, etc.

## Quais serão os meios que vamos usar para aprender esses conceitos?
- Prática
- Exercícios
- Criar aplicativos do zero

## Qual é o pré-requisito básico?
Saber HTML e CSS.

**Comment by Roger-Melo** [comment]
Excelente @ananopaisdojavascript, rumo à fluência! 🎯
