### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by hugofficial** [roger-melo-treinamentos/curso-de-js-roger-melo#3539]
**Constantes, variáveis e comentários**

Uma variável tem a função de armazenar um valor na memória. No Javascript temos esta formas de declarar variável: let, const e var.

> **let:** A let podemos atribuir e alterar o valor já atribuído a variável.

> **const:** A const será usada quando não queremos que outro valor seja reatribuído para ela. A const armazenará um valor único.

> **var:** Forma antiga de criar uma variável de armazenamento, não se utiliza mais desta forma.

Para fazer comentários no código usamos: **//** para comentar em linha, ****/* */**** para multi-linha.

**Comment by Roger-Melo** [comment]
Excelente @hugofficial, rumo à fluência! 🎯
