### ISSUE TITLE
Resumo da Aula 05-04 da etapa 11 - Async/await

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3540]
Async/await
- Palavras-chave no JS
- Usam promises por baixo dos panos
- Permitem que seja escrito um código ainda mais legível que é lido como
se fosse síncrono.

```js
fetch('https://jsonplaceholder.typicode.com/users')
   .then(response => {
     console.log('response', response)
     return response.json()
   })
   .then(users => console.log(users))
   .catch(error => console.log(error))
```
Quando várias promises são encadeadas, este código fica de difícil
compreensão e manutenção.

Quando o async/await é utilizado, é possível setar o código assíncrono em 
uma função e usar dentro da função a palavra await para que seja possível 
utilizar promises de forma mais legível.
Com o async/await a configuração explícita de encadeamento de promises 
pode ser evitada.

```js
const getUsers = async () => {
  /*
    Quando a palavra-chave async é declarada antes da função, faz com que 
    a função seja assíncrona.
    Se esta função fosse uma function declaration a palavra-chave async poderia ser 
    declarada depois da palavra-chave function.
    Quando função for invocada, retornará uma promise independente do 
    conteúdo dentro dela.
  */
  const response = await fetch('https://jsonplaceholder.typicode.com/users')
  /*
  await(aguardar) só pode ser usada dentro de uma função async.
  A invocação do fetch vai ser executada, a requisição vai acontecer
  enquanto a resposta da requisição não chegar, nenhum código abaixo
  da linha do await será executado.
  Quando a promise que o fetch retorna for resolvida, o await vai atribuir para
  a const response o valor resolvido dessa promise que é o objeto response, 
  após isso, as linhas abaixo serão executadas.  
  */
}
getUsers()
```
![image](https://user-images.githubusercontent.com/92958989/166588490-ea7b150a-c0eb-4bfc-b5cb-e7a598393fa0.png)

O objeto `response` é o valor resolvido que a `promise` retornou.

Para obter os dados da resposta do request, o método `json`(pega a resposta que o `response `
está armazenado, parseia a resposta para um array de objetos JS e retorna uma `promise `que contem a resposta parseada) será encadeado na `const response.`

```js
const getUsers = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users')
    const users = await response.json()
    /*
      O await precisa ser declarado antes da const response porque a invocação do response.json()
      retorna uma promise com um array de objetos, quando essa promise que encapsula o array de objetos
      for resolvida, o await vai atribuir para a const users o valor resolvido da promise que é 
      o array de objetos. 
   */
   console.log(users)
}
getUsers()
```
![image](https://user-images.githubusercontent.com/92958989/166590815-3b3eb2d3-d442-4b50-8df6-cf9577f0ad5d.png)

Retornando os usuários. 
    - Duas formas:

1ª) retornando a `const users`
```js
const getUsers = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users')
    const users = await response.json()
    return users
}
getUsers()
```    
2ª) `return` antes da palavra-chave `await`
  ```js 
  const getUsers = async() => {
   const response = await fetch('https://jsonplaceholder.typicode.com/users')
   return await response.json()
   /*
  Este return só vai ser executado, depois que o await desencapsular o 
  valor da promise resolvida que o response.json() retorna.
  */
}
console.log(getUsers())
```
![image](https://user-images.githubusercontent.com/92958989/166602267-45603ede-6cc7-4964-9069-1f3190f90a6a.png)
A `promise` armazena o array de usuários.

Uma função `async` sempre retorna uma `promise` que encapsula o valor a que função ta retornando.
Toda função `async` implicitamente retorna uma `promise`.

Para fazer alguma coisa com array de usuários.

```js
const getUsers = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users')
    return await response.json()
}
const logUsers = async () => {
  //Para obter os usuários
  const users = await getUsers()
  console.log(users)
}
console.log(1)
console.log(2)

logUsers() //função assíncrona, é executa e finalizada posteriormente.

console.log(3)
console.log(4)
```
![image](https://user-images.githubusercontent.com/92958989/166605177-d47900cb-3d76-4282-9490-bd262123c691.png)

**Comment by Jansen-Muniz** [comment]
Esse resumo ficou muito bom, mas eu trabalho pra fazer kkkk
Assisti essa aula semana passada e escrevi no vs code, mas queria todas as telas do console, tava acompanhando 
e executava, tirei o print, só que tava com sono e não lembrava mais de onde era cada tela, como tá agora.

**Comment by Roger-Melo** [comment]
Excelente @Jansen-Muniz, rumo à fluência! 🎯
