### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários da etapa 01

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3543]
<h2 style="color: 'blue'">Resumo sobre constantes, variáveis e comentários</h2>
<h3><span>Variáveis</span></h3>
<ul>
<li>No ES5 o var não faz tanto sentido, logo para atribuição de valores é melhor utilizado <strong><i>let</i></strong> para reatribuir um valor para essa variável, ou <strong><i>const</i></strong> para deixar o dado imutável. </li>
<li>A convenção de nomeclatura é camelcase, ou seja, inicia com letra minúscula e a transição de uma palavra para outra difere da primeira letra da próxima palavra maiúscula</li>
<li>Nomes de variáveis não podem começar com número</li>
<li>Nomes de variáveis não podem ser nomes reservados</li>
</ul>
<h3><span>Comentários</span></h3>
<ul>
<li>Comentários de uma única linha pode ser utilizado //  na frente da linha</li>
<li>Comentários de múltiplas linhas pode ser utilizado com /*comentário*/  na frente da linha</li>
<li>Selecionando as linhas que deseja comentar e apertando o atalho <strong><i>ctrl+;</i></strong> irá comentar todas as linhas</li>
</ul>

**Comment by Roger-Melo** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯

**Comment by Beninigmal** [comment]
Roger uma dúvida, tô me esforçando pra manter esse ritmo, mas deixa eu te
passar meu contexto pra me dar um conselho, eu entrei numa empresa como
trainee e por motivo de grande quantidade de evasão da empresa eu fui
colocado como Jr em react, porém eu mal sabia JS e isso me trava ainda
hoje, então eu comecei a estudar JS e aprendi bastante coisa, o que sinto
hoje é que meu raciocínio não é fluído, mas esse básico eu entendi bem. No
caso essas aulas que eu já souber eu fazendo o exercício e batendo com o
seu eu devo fazer o resumo? Ou eu posso avançar? Não tô querendo ser
coelho, mas eu iniciei curso de JS por várias vezes e é meio massante e meu
tempo é meio curto.

Att

Lucas Araujo

Em qua., 4 de mai. de 2022 08:09, Roger Melo ***@***.***>
escreveu:
