### ISSUE TITLE
Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by muritadb** [roger-melo-treinamentos/curso-de-js-roger-melo#3547]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/745800

### Descreva a dúvida

Boa noite, no exercicio 22 sobre Strings eu resolvi o exercicio de outra forma que o Professor, usando o replaceAll(), segue o codigo: 
```js
newName = `${name.replaceAll('w', 'W')}`
```

Nesse caso, devo refazer com a solução do professor ? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @muritadb.

`replaceAll` é apresentado em etapas posteriores. O desafio é vc resolver o exercício com o que viu no treinamento até o momento, ok? =)

E sobre a resolução de um exercício ser diferente da minha, eu respondi essa dúvida na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Recomendo fortemente que pare e veja até o final (caso ainda não o tenha feito), pois ela é a aula mais importante do CJRM. Se vc aspira chegar na fluência, vc precisa assistir essa aula.

E claro, se ainda restar alguma dúvida, é só dar o toque =)

**Comment by muritadb** [comment]
blz professor, vou revisitar o conteudo. Obrigado!!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
