### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários (Aula 01-06) da etapa 01

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3549]
# Constantes, variáveis e comentários - Aula 01-06 - Resumo

## Qual é a responsabilidade de uma variável?

A responsabilidade de uma variável é armazenar um valor. Pode ser números, nomes, valores lógicos, etc.

## Quais são as formas de declarar uma variável no Javascript?

Declaramos variáveis no JS com as palavras reservadas `var`, `let` e `const`.

## O que significa `=` em uma variável?

`=` não é um operador de igualdade. É um operador de atribuição de um valor.

## Como podemos interpretar a variável `let age = 31`?

Podemos interpretá-la da seguinte forma: trata-se de uma variável chamada `age` que recebe um valor (31).

## Como podemos colocar mais de um valor no `console.log()`?

Podemos colocar os valores separados por vírgulas no `console.log()`.

```javascript
console.log(age, currentYear)
```

## Como atribuir outro valor à mesma variável?
É só “chamar” essa variável (sem a palavra `let`) e atribuí-la um novo valor.

```javascript
age = 32
```

## Qual é a forma de declarar uma variável cujo valor não deve ser alterado?
Basta declarar uma variável com a palavra `const`.

```javascript
const points = 100
```

## É possível atribuir um novo valor a uma constante?
Não. Se tentarmos atribuir um novo valor a uma constante, aparecerá a seguinte mensagem de erro no console do JS:

```
Uncaught TypeError: Assignment to constant variable
```

## `const` e `let` são formas recentes de declaração de variáveis. Qual era a forma mais frequente de declaração de variáveis anterior a `let` e `const`?

Antes existia uma forma de declaração de variáveis chamada `var`. 

```javascript
var score = 75
```

Essa forma caiu em desuso com o advento do ES5(ES6)

## Quais são as regras para criação de variáveis?

- Uma variável deve ser uma única palavra. Para criar uma variável com mais de uma palavra, é importante usar uma convenção chamada **CamelCase**, na qual a primeira letra da primeira palavra é minúscula e a primeira letra das palavras posteriores é maiúscula.

```javascript
const currentYear = 2022
```

- Nomes de variáveis devem conter apenas letras, números, `_` (sublinhado) e `$` (cifrão), porém o nome da variável não deve começar com um número.

- Palavras reservadas da linguagem JS (`const`, `var`, `let`) não devem ser usadas como nomes de variáveis.

- As variáveis devem ter nomes significativos, que revelam exatamente o que a variável está fazendo.

## Quais são os tipos de comentários usados no JS?

Podemos usar comentários de uma única linha

```javascript
// Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
```  

Ou podemos usar comentários de mais de uma linha

```javascript
/*
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium 
doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore 
veritatis et quasi architecto beatae vitae dicta sunt explicabo.
*/
```

**Comment by Roger-Melo** [comment]
Boa @ananopaisdojavascript, rumo à fluência! 🔥
