### ISSUE TITLE
Duvida com relação ao definir o input do form para referencia do DOM

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3554]
### Etapa da aula

9

### Nome da aula

Buscando e filtrando to-dos - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1073158

### Descreva a dúvida

Boa noite! E que tudo esteja bem por ai.

Estava estudando a aula sobre filtrar os To Dos . Durante os estudos, tentei tirar o input escrito separado logo após o .form-search passado como argumento ao querySelector.
```JS
const formSearch = document.querySelector('.form-search input')

const formSearch = document.querySelector('.form-search')
```
 No intuito de ver se teria como acessar formSeach dentro do listener de evento que contem o type Event = 'input' e durante execução do evento  com o objeto event conseguir acessar o elemento input pelo name que neste caso seria = "search". 
```JS
formSearch.addEventListener('input', event => {
    const inputValue = event.target
    console.log(inputValue.search)
})
```
Porém, quando tento fazer isso sem o input separado na referencia, tentando chamar ele diretamente na propriedade target do event encadeando com o "search" que seria o valor de name -> event.target.search eu recebo undefined no console.

```JS
const formSearch = document.querySelector('.form-search')

formSearch.addEventListener('input', event => {
    const inputValue = event.target
   console.log(inputValue.search)

})
```

 Diferente de quando está referenciado com o '.form-search input'. 
 
 ```JS
 const formSearch = document.querySelector('.form-search input')
 
 formSearch.addEventListener('input', event => {
    const inputValue = event.target
   console.log(inputValue)

})
 ```
 
 Não entendi o porque ainda de não funcionar, pois no passado, teve exercícios que era possível pegar o input pelo ID, por exemplo com o #username no exercício 18.
 
 ```JS
const inputUsername = document.querySelector('#username')
```

 E mesmo o listener de evento da aplicação todo que tem o event type = 'submit' estamos pegando o input pelo add.value em que add seria o name do formulário referenciado no formAddTodo.

```JS
const formAddToDo = document.querySelector('.form-add-todo')

const inputValue = event.target.add.value
````

Desde já grato,

All the best!

Enéas da Silva Junior.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus!

Vc pode postar todo o código (HTML, CSS e JS)? Assim fica mais fácil eu reproduzir aqui em minha máquina e ajudar com mais precisão =)

Vc pode subir os arquivos no google drive, um repositório público e mandar o link ou postar o código dos arquivos aqui na issue mesmo. Sempre que a dúvida envolver DOM, pode postar o código todo =)

**Comment by EneasFeynlinus** [comment]
Boa tarde professor, vou colar o HTML,CSS e javaScript e no codigo javaScript, vou deixar comentários nas partes que estou com a duvida. Desde já muito obrigado. =)

```HTML
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel="stylesheet" href="./style.css">
  <title>To-do List | CJRM</title>
</head>
<body class="bg-dark">
  <div class="container">

    <header class="text-center text-light my-4">
      <h1 class="mb-4">To-do List</h1>
      <form class="form-search">
        <input class="form-control m-auto" type="text" name="search" placeholder="Buscar to-do" />
      </form>
    </header>

    <ul class="todos-container list-group mx-auto text-light">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>Assistir Breaking Bad</span>
        <i class="far fa-trash-alt delete"></i>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>Planejar aulas</span>
        <i class="far fa-trash-alt delete"></i>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>Fazer exercícios físicos</span>
        <i class="far fa-trash-alt delete"></i>
      </li>
    </ul>

    <form class="form-add-todo text-center my-4">
      <label class="text-light">Adicionar to-do</label>
      <input class="form-control m-auto" type="text" name="add" autofocus />
    </form>
  </div>

  <script src="./app.js"></script>
</body>
</html>
```
CSS

```CSS
.container {
  max-width: 400px;
}

input[type=text],
input[type=text]:focus {
  color: #fff;
  border: none;
  background: rgba(0,0,0,0.2);
  max-width: 400px;
}

.todos-container li {
  background: #484E53;
}

.delete {
  cursor: pointer;
}
```
javaScript (Modo que está retornando undefined.)

```JS
const formAddToDo = document.querySelector('.form-add-todo')
const todoContainerList = document.querySelector('.todos-container')
const formSearch = document.querySelector('.form-search') // Antes era (.form-search input) quando 
// retiro o input e tento acessar o valor pelo name="search" obtenho undefined.

formAddToDo.addEventListener('submit', event => {

event.preventDefault()

const inputValue = event.target.add.value

if (inputValue.length) {
 todoContainerList.innerHTML += `
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>
      </li>
        `
event.target.reset()
    }
})

todoContainerList.addEventListener('click', event => {

const clickedElement = event.target

if (Array.from(clickedElement.classList).includes('delete')) {

clickedElement.parentElement.remove()
    }
})

formSearch.addEventListener('input', event => {

    const inputValue = event.target.search// Tentando acessar o valor do input através do va-
    // lor de name = "search" 
    console.log(inputValue)// Porém esta me retornando undefined, no entanto nao entendi
// o porque de nao conseguir utilizar o name="search" sendo que no listener de evento do
// submit, foi possivel pegar o input pelo name="add"
})
```
javaScript (Modo que está dando certo)

```JS
const formAddToDo = document.querySelector('.form-add-todo')
const todoContainerList = document.querySelector('.todos-container')
const formSearch = document.querySelector('.form-search input') // Quando mantenho o 
// input logo apos o form-search, consigo acessar o valor do input no console.log().

formAddToDo.addEventListener('submit', event => {

event.preventDefault()

const inputValue = event.target.add.value// Obtendo o valor do elemento input, através do
//  valor de name="add" dando errado com o name="search"

if (inputValue.length) {
 todoContainerList.innerHTML += `
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>
      </li>
        `
event.target.reset()
    }
})

todoContainerList.addEventListener('click', event => {

const clickedElement = event.target

if (Array.from(clickedElement.classList).includes('delete')) {

clickedElement.parentElement.remove()
    }
})

formSearch.addEventListener('input', event => {

    const inputValue = event.target// Quando acesso o o elemento que encadeou o evento, pelo
// target sem o valor de name, recebo normalmente o elemento. minha duvida esta em entender
// Porque no listener de eventos do submit acima, foi possivel acessar o elemento input com o valor
// do name="add" e no caso quando uso search, recebo undefined.
    console.log(inputValue)// Porém esta me retornando undefined
})
```

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus!

No código abaixo, vc está obtendo a referência do seguinte form:

```javascript
const formSearch = document.querySelector('.form-search')
/*
<form class="form-search">
  <input class="form-control m-auto" type="text" name="search" placeholder="Buscar to-do" />
</form>
*/
```

Porém, observe que mesmo encadeando o addEventListener no form, `event.target` resulta no elemento no qual o evento de input aconteceu (o próprio input). Sendo assim, vc pode pegar o value encadeando diretamente a propriedade `value`:

```javascript
formSearch.addEventListener('input', event => {
  console.log(event.target) // <input class="form-control m-auto" ...>
  console.log(event.target.value) // valor inserido no input
})
```

---

> ## E mesmo o listener de evento da aplicação todo que tem o event type = 'submit' estamos pegando o input pelo add.value em que add seria o name do formulário referenciado no formAddTodo.

`submit` e `input` são eventos diferentes. Apenas eventos `submit` (nos quais `event.target` resulte no form) vão possibilitar que vc obtenha a referência do elemento através de `.target`. 

O que vc quer fazer irá funcionar caso o evento de input seja substituído por `submit`, somado ao fato de que `event.target` agora resulta no form, e não no input:

```javascript
formSearch.addEventListener('submit', event => {
  event.preventDefault()

  console.log(event.target) // <form class="form-search">...</form>
  console.log(event.target.search.value) // valor inserido no input
})
```

Agora, o porquê disso, sinceramente eu acho que não vale se aprofundar, pois vc investiria tempo em descobrir respostas que não vão fazer diferença no seu dia a dia. DOM é uma API meio "zoada", algumas coisas nela são imprevisíveis e tentar descobrir o pq de certas coisas internas dela demandaria um tempo de estudo que não vai te trazer retorno significativo.

Ficou mais claro? =)

**Comment by EneasFeynlinus** [comment]
Bom dia professor @Roger-Melo

Nossa!! Ficou muito claro, estava apenas focado no event.target sem pensar no elemento que o evento estaria ocorrendo e as diferenças para obter os valores do objeto event retornado, não tinha pensado por esse ponto, realmente se for olhar pelo retorno do comportamento de um submit, um input, mousedown e etc... cada um terá um tipo de comportamento, não tinha isso em mente. 

Deu mais uma iluminada no horizonte do oceano da programação em javaScript. 

Muito obrigado professor, tenha um ótimo dia!

All the best!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
