### ISSUE TITLE
Resumo da Aula Template Strings da etapa 01 Aula 02-06

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3556]
<h1 align="center">Template Strings</h1>
<ul align="center">
<li align="justify">Template strings ou template literals é a forma mais atual de escrever strings a partir do ES6, é interessante utiliza-la quando é necessário fazer interpolação de dados em uma string e ao invés de aspas simples ou duplas, utilizamos a crase. Ex:
<code>
const  autor = 'André Vianco';<br />
const livro = 'O Bento' <br />
const mensagem = `${autor}, é um escritor brasileiro de ficção e um dos seus best sellers é ${livro}`
</code>
</li>
</ul>

**Comment by Roger-Melo** [comment]
Show @Beninigmal. Vamo que vamo, rumo à fluência! 🙌
