### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by ricardostarosa** [roger-melo-treinamentos/curso-de-js-roger-melo#3559]
O tipo de dado **Number** é muito utilizado para realizar operações matemáticas dentro do JS.

Um exemplo bem comum é o de calcular a media de um aluno.

let notaMatematica = 8;
let notaPortugues = 6;
let notaBiologia = 7;

const media = notaMatematica  +  notaPortugues  +  notaBiologia  /  3 ;

media -> 17 

Note que o valor está com um erro por não seguir a regra de precedência de operações, que é a mesma da matemática. 

1.  ( ) - Os parênteses tem precedência nas operações.
2.  **  e  Math. sqrt(numero)  - Os operadores de potencia e raiz são os segundos na ordem de precedência.
3.  * e /  -  Os operadores de multiplicação e divisão os terceiros.
4.  - e +  - São os últimos .

**Obs:** _É importante considerar que a ordem também é um fator de precedência . Assim como em uma fila de pessoas com prioridades a que chegou antes tem a precedência no atendimento, então tendo operadores equivalentes , o que será calculado primeiro é o que está à esquerda._

Voltando para o calculo da média e sabendo como funciona a precedência, vamos aplicá-la!

let notaMatematica = 8;
let notaPortugues = 6;
let notaBiologia = 7;

const media = ( notaMatematica  +  notaPortugues  +  notaBiologia )  /  3 ;

media -> 7

**Comment by Roger-Melo** [comment]
Show @ricardostarosa. Vamo que vamo, rumo à fluência! 🙌
