### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by Lkoshoji** [roger-melo-treinamentos/curso-de-js-roger-melo#356]
Fiz de uma forma diferente, alçando o mesmo resultado. Porem, vendo a resolução do exercício, me pareceu muito mais correto a forma que o professor fez. 

Segue a forma que fiz. Tem algum problema dessa forma?
```JS
const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS', 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]
let stringValues = []
let booleansAmount = 0
let iterationAmount = 0
for(let i =0; i < randomValues.length; i ++) {
  iterationAmount += 1

  if (typeof randomValues[i] === 'boolean') {
    booleansAmount += 1
  }

  if (typeof randomValues[i] === 'string') {  
  stringValues.push(randomValues[i])
  if (stringValues.indexOf(randomValues[i]) >= 3){
    break
  }
} 
```

@Roger-Melo

**Comment by YureK-a** [comment]
Bom, não sou o roger mas resolvi responder. Eu passei seu código a limpo e havia só um erro(faltou uma "}" do if de stringValues). Fora isso, só foi necessário adicionar as consts que colocam um 'e' antes do último item, além de melhorar a legibilidade do seu código.
```javascript

const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS', 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]
let stringValues = []
let booleansAmount = 0
let iterationAmount = 0
for(let i = 0; i < randomValues.length; i++) {
    let item = randomValues[i]
    const booleanType = typeof item === 'boolean'
    const stringType = typeof item === 'string'
    iterationAmount++
    
    if (booleanType) {
      booleansAmount += 1
    }   

    if (stringType) {  
    stringValues.push(item)
    }

    if (stringValues.length === 4){
      break
    }
} 
const lastItem = stringValues[stringValues.length - 1]
const showStrings = stringValues.join(', ').replace(`, ${lastItem}`,  ` e ${lastItem}`)

console.log(`- As primeiras 4 strings são ${showStrings};
- Até que as primeiras 4 strings fossem iteradas, ${booleansAmount} booleans foram iterados;
- O array foi iterado por ${iterationAmount} vezes.`)

```

**Comment by Roger-Melo** [comment]
Obrigado pela contribuição, @YureK-a.

---

Olá @Lkoshoji.

Quando abrir uma issue, copie e cole o nome exato da aula no título. Isso faz com que eu localize a aula certa e te ajude mais rápido. Já consertei o título dessa issue, não existe Correção de exercícios da aula 03 na etapa 02.

Também preciso saber seu nome para tagear a issue. Não há como saber como você se chama, mesmo olhando o perfil.

---

Não há problema em resolver de outra forma, desde que a forma que você resolveu aplique os mesmos princípios da resolução mostrada.

A resolução mostrada na correção contém alguns princípios de design e qualidade de código.

- Quando o bloco tem alguma condição que deve parar de executá-lo, prefira deixar essa condição explícita nas primeiras linhas do bloco. Isso é uma convenção chamada [fail-fast](https://martinfowler.com/ieeeSoftware/failFast.pdf);

- Sempre que possível, prefira não aninhar ifs. O aninhamento deles deixa o código menos legível e, para resolver este exercício, é desnecessário (como mostrado na correção). É tão ilegível que você acabou esquecendo de fechar o bloco do `if` que contém o segundo `if`;

- Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos. Seguindo esse princípio, eu adicionaria linhas em branco antes do bloco de declarações das let `stringValues`, `booleansAmount` e `iterationAmount`:

```javascript
const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS', 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]

let stringValues = []
let booleansAmount = 0
let iterationAmount = 0

for(let i =0; i < randomValues.length; i ++) {
  // ...
}
```

Isso delimita o conceito "declarações de variáveis que sofrerão reatribuição" do restante dos outros conceitos do código.

Outra oportunidade de melhoria é sempre deixar uma linha em branco antes de blocos `if`:

```javascript
if (typeof randomValues[i] === 'string') {
  stringValues.push(randomValues[i])
  
  if (stringValues.indexOf(randomValues[i]) >= 3) {
    break
  }
}
```

Prefira sempre deixar uma linha em branco antes de `if`s, exceto quando o `if` é a primeira linha dentro de um bloco (de função, por exemplo).

- Como o @YureK-a mencionou, legibilidade é importante. Eu não sei se a versão que você postou é a refatorada, mas há bastante oportunidades de melhoria.

---

Por essas razões, no início, prefira reescrever o código o mais parecido possível com a resolução mostrada. Isso vai assegurar que você assimile os princípios por tras do que estou fazendo.

Fizeram sentido as observações acima?

@Lkoshoji

**Comment by Lkoshoji** [comment]
Perfeito professor, vou me atentar as suas observações e refazer o exercício colocando em pratica os conceitos que me passou!

Muito obrigado!
