### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3563]
# Template strings - Aula 02-06 - Resumo

## O que são ***template strings***?

São uma funcionalidade do ES6 que facilita a concatenação de cadeias de caracteres.

```javascript
// usando concatenação
const postMessage = 'O post "' + postTitle + '", de ' + postAuthor + ', tem ' + postComments + ' comentários'
```

```javascript
// usando template strings
const postMessage = `O post "${postTitle}", de ${postAuthor}, tem ${postComments} comentários.`
```

## Como podemos resolver os conflitos de aspas dentro de uma ***string***?

Podemos resolver esses conflitos de três formas:

- Colocando aspas simples no começo e no fim da ***string*** e dentro usa aspas duplas.

```javascript
console.log('Você já viu o filme "As Branquelas"?')
```

- Colocando aspas duplas no começo e no fim da ***string*** e dentro usa aspas simples.

```javascript
console.log("Você já viu o filme 'As Branquelas?'")
```

- Colocando aspas simples no começo e no fim da ***string*** e dentro usa aspas simples com comandos de escape `\`

```javascript
console.log('Você já viu o filme \'As Branquelas\'?')
```

## Como renderizar uma variável dentro de uma ***template string***?

É só colocar a variável da seguinte forma:

```javascript
console.log(`${nome-da-variavel}`)
```

## Como criar um ***template*** HTML dentro de uma ***template string***?

```javascript
const html = `
    <h2>${postTitle}</h2>
    <p>Autor: ${postAuthor}</p>
    <span>Esse post tem ${postComments} comentários.</span>
`
console.log(html)
```

**Comment by Roger-Melo** [comment]
Show @ananopaisdojavascript. Vamo que vamo, rumo à fluência! 🙌
