### ISSUE TITLE
Aplicação: To-Do list

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3565]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/BrunodevOliveira/to-do-lis-js

### Maiores dificuldades durante a implementação

Nessa aplicação resolvi me desafiar e desenvolvi algumas funcionalidades que achei legal ter, que foram uma mensagem caso o filtro de To-do não retorne nenhuma tarefa e uma validação para que o usuário não insira um To-do duplicado na lista.

Minha principal dificuldade durante a implementação foi identificar o local correto para chamar as funções responsáveis por essas duas funcionalidades e a lógica em si de cada uma. Tive a impressão de que quanto mais mexia no código mais bugs apareciam em cada funcionalidade.  Daí pude perceber a importância de cada função ter uma responsabilidade única. Fica mais fácil saber onde pode estar o erro dessa forma.

Ainda não me habituei a essa nova forma de fazer querys no DOM, então a parte da aplicação que desenvolvi assistindo às aulas deixei como já vínhamos fazendo durante o curso.

Outra coisa que pude notar tentando criar algo sozinho é que meu raciocínio ainda é muito caótico na hora de desenvolver algo. Às vezes me perdia no que estava fazendo por não saber se daquele jeito chegaria no resultado que gostaria, essa insegurança fazia com que eu perdesse bastante tempo pensando em uma alternativa para algo que ainda não confirmei se de fato vai dar errado🤡. 

Também continuo com dificuldade em entender a documentação, alguns exemplos que ela possui são meio vagos ou complexos para alguém do meu nível de conhecimento ainda, aí recorro ao YouTube ou algum artigo que alguém explique melhor e entendo. Mas tenho certeza que é importante ler a documentação para criar autonomia, só acho que estou lendo de forma errada rs.

Uma outra funcionalidade que tentei implementar era a de editar To-dos, mesmo tentando de diversas formas não consegui desenvolver um código que fizesse isso.

Desculpe o texto enorme! Vou listar aqui em baixo um resumo do que fiz a mais nessa aplicação:

- Caso o usuário busque por algum to-do que não esteja na lista, uma mensagem de to-do não encontrado será exibida.
- Caso o usuário insira algum to-do que já existe na lista, uma mensagem de alerta será exibida ao usuário informando que o to-do já existe.
- Caso o usuário adicione ou remova uma LI as cores delas serão modificadas

### Menores dificuldades durante a implementação

A menor dificuldade que tive foi em replicar o que eu desenvolvi junto com vc durante a aula, sua didática é excelente! 
Também não tive dificuldades em utilizar arrow functions, criar eventos e manipular o DOM, claro que não lembrei a sintaxe de tudo de cabeça, mas sabia que determinado método existia e como utilizar, assim só pesquisava a forma correta de se escrever mesmo.

### Conselho sobre estudos
Então professor gostaria de uma orientação do senhor e como essa dúvida não é sobre o curso e não existe uma label para isso, decidi postar aqui mesmo. Mas caso vc prefira que utilize outro canal, me avise pfv.
Assim que me matriculei no CJRM(final de outubro) tive uma aprovação em um bootcamp onde aprendi a utilizar Angular + Node Js, mas como a proposta de bootcamp não é ensinar do 0 ainda tenho várias lacunas de conhecimento que estão sendo preenchidas com o seu curso. O problema é que esse bootcamp irá me indicar para vagas e não necessariamente será em Angular, pois perderam um parceiro que utilizava esse framework e agora estão indicando os alunos que eles acham mais capacitados para empresas que utilizam react. Agora me vejo na situação de ter que aprender React(o que sempre foi meu plano inicial) o mais breve possível e gostaria que me indicasse algum curso que tenha uma didática tão incrível quanto a sua.

**Comment by MivlaM** [comment]
Olá, @BrunodevOliveira.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua aplicação =)

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by MivlaM** [comment]
Ok!

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Parabéns pelo esforço 🔥

Vou deixar a análise de seu To-do [aqui](https://drive.google.com/file/d/1okXGQYdFueLMtX-1LDaHQL7J_TFvkfHB/view?usp=sharing). 

Se houver qualquer dúvida, é só dar o toque =)

**Comment by BrunodevOliveira** [comment]
Oi, Roger! 
Muito obrigado pela orientação e pelas dicas de como refatorar o código! =D

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
