### ISSUE TITLE
Correção dos exercícios da aula 03 da etapa 11 - Aula 04-01

### ISSUE THREAD

**Issue by rodrigoljpereira** [roger-melo-treinamentos/curso-de-js-roger-melo#3566]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 03 da etapa 11 - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1289060

### Descreva a dúvida

Olá Professor. Na correção dos exercicios, no primeiro exercicio sobre request, nós criamos uma função chamanda logPokemonData para exibir os console.log('error'), e o console.log(`pokemon obtido: ${data}`). E como estamos usando data e error precisamos passar data e error como argumentos quando chamarmos a função logPokemonData(error, data).

Porem, no aninhamento das funções para exibir os três pokemons do exercicio, a ultima chamada da função logPokemonData não precisou ser passada error e data como argumento.

Eu não consegui entender por que de usar apenas a referência da função se a mesma a ser criada está solicitando parâmetros.

Poderia por favor me ajudar com essa duvida?

```js
getTodos(getTodosUrl(1), (error, data) => {
  logPokemonData(error, data)

  getTodos(getTodosUrl(4), (error, data) => {
    logPokemonData(error, data)
  })
    getTodos(getTodosUrl(7), logPokemonData)
})
```

Desde já agradeço!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
@rodrigoljpereira dá uma olhada [nesse vídeo](https://drive.google.com/file/d/15ftfaggtLICFqO00k6M1wIZJe3qDhlMl/view?usp=sharing) também =)

**Comment by rodrigoljpereira** [comment]
Olá professor. Assisti seu vídeo. Então, minha duvida não está na função de callback(conceitos ou usabilidade). Até aqui, entendi bem como funciona uma função de callback, entendi mesmo, e também sei utilziar função com parametros, passar argumentos e a diferença entre eles, e quando usar uma função como referencia. 

Acho que não me fiz entender na questão da minha duvida. Minha duvida era mais na questão estrutural do código que foi montado. Função de callback foi um dos seus conteúdos que eu mais estudei rsrs, 

Por que nas duas primeiras chamadas da logPokemonData, nós passamos os argumentos e na ultima invocação dela não passamos.  Mas eu assisti o vídeo da correção novamente com mais calma e consegui compreender o que foi feito. 

Agora está tudo claro pra mim. 

Muito obrigado por seu tempo e disponibilidade.

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
