### ISSUE TITLE
Utilização do MDN

### ISSUE THREAD

**Issue by gh-carneiro** [roger-melo-treinamentos/curso-de-js-roger-melo#3570]
### Etapa da aula

1

### Nome da aula

Arrays - Aula 03-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/745801

### Descreva a dúvida

Professor, estou na etapa 01 e quando estava aprendendo o método A.T.E.R. tu falou sobre a utilização do MDN. Vai ter um momento em que tu vai introduzir a utilização do mdn ou desde o começo já posso ir utilizando? (Não tenho experiência nenhuma com programação)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gh-carneiro.

Desde já, vc precisa pesquisar no MDN por conta própria. Não tem segredo. Apenas vá no google e insira o nome do assunto/conceito que vc está estudando e em seguida, "MDN". Exemplo: `array mdn`.

Provavelmente, essa página irá ser uma das primeiras a ser exibida pra vc.

![image](https://user-images.githubusercontent.com/29297788/167525738-99c31db7-63a4-4537-9803-52aeae9db363.png)

Leia ela, sem clicar em links e sem a intenção de entender tudo de primeira. Se entender 5%, tá ótimo!

A medida em que vc for praticando, vc vai perceber que começará a entender + 5% do que está escrito. Ou seja, agora vc entende 10%. Essa é a lógica. É como ler um livro pela 1ª vez... Quando lê pela 1ª vez, vc só teve um panorama geral do livro. Quando lê pela 2ª, começa a sacar coisas que pareciam não estar ali.

Já adianto que na parte do treinamento em que vc está, as partes mais iportantes dessa pág. serão `Description` e `Examples`.

E sim, no treinamento, em breve vc verá aulas em que eu falo mais sobre o MDN, mas vc pode pesquisar desde já, apenas lembrando-se de não criar expectativas de entender tudo de primeira. 

Ficou mais claro? =)

**Comment by gh-carneiro** [comment]
Perfeito professor!
Resolvi perguntar porque as outras vezes que tentei estudar programação utilizava de muitas fontes e acabava morrendo na praia kk
Obrigado!

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
