### ISSUE TITLE
Resumo da Aula Conversão de tipos da etapa 01 Aula 04-04

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3582]
<h1 align="center">Conversão de tipos</h1>
<ul align="center">
<li align="justify">Por muitas vezes um dado imputado pelo usuário será uma string com um número, e precisaremos fazer uma operação numérica, portanto é necessário um tratamento desses dados antes da operação. Existe um método chamado <code>Number()</code> que serve para efetuar essas conversões, lembrando que esse método é uma operação e operações que não fazem sentidos podem retornar NaN. Uma outra forma de fazer essa conversão (apesar de mais nova é menos popular) é adicionando o operador <strong>+</strong> na frente do número, ex: <br />
<code>const numero = '10'</code> <br />
<code>console.log(Number(numero)) // resultado: 10</code><br />
<code>console.log(+numero) // resultado: 10</code>
</li>
<li align="justify">Os valores booleans sempre retornaram false quando recebe valores <strong><i>falsy</i></strong>, os valores <strong><i>falsy</i></strong> são: <ol type="1">
<li><strong><i><code>false</code></i></strong></li>
<li><strong><i><code>0</code></i></strong></li>
<li><strong><i><code>"", ''. ``</code></i></strong></li>
<li><strong><i><code>null</code></i></strong></li>
<li><strong><i><code>undefined</code></i></strong></li>
<li><strong><i><code>NaN</code></i></strong></li>
</ol></li>
<li align="justify">Todos os valores que não são falsy são truthy</li>

</ul>

**Comment by Roger-Melo** [comment]
Boa @Beninigmal, rumo à fluência! 🔥
