### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3596]
# Constantes, variáveis e comentários - 01-06  

**Variáveis**  

O objetivo de utilizamos variáveis é armazenar um valor para ser usado posteriormente em outra parte da aplicação. 

O conteúdo armazenado pode ser um e-mail, número, palavra, etc.  
 

Através da palavra reservada LET, declaramos tipos de variáveis que poderão ter o seu valor alterado. 
 

Let idade = 60 -> Nesse exemplo atribuímos para idade o valor 60. A palavra idade vai funcionar como uma caixa que armazena o valor dentro dela, e quando precisarmos utilizar este valor, chamaremos a variável idade digitando o seu nome. 

Após a declaração, se digitarmos no console a palavra idade, será mostrado o valor 60. Quando declaramos uma variável com LET, podemos atribuir um novo valor  

_Console_ 

1> Let idade = 60 

2> idade -> No console aparecerá o valor 60 

3> Idade = 120 -> Será mostrado o valor 120 

 

Note que na linha 3 não utilizamos a palavra reservada LET quando atribuímos um novo valor para a variável. Isso porque só precisamos colocá-la no momento que iniciamos a variável, nas próximas vezes que formos usar, não precisaremos mais declarar.  
 

**Constantes** 

Utilizamos variáveis do tipo constante quando não queremos que um novo valor seja atribuído a ela. Para declararmos uma constate usamos a palavra reservada CONST. 

_console:_ 

1> const ano = 2022 

2> ano -> No console aparecerá o valor 2022 

3> ano = 2023 -> Se tentarmos alterar o valor, o console irá mostrar uma mensagem de erro por tentarmos alterar o valor de uma constante 

 

**Var** 

Outra forma de se inicializar uma variável é através do VAR. Ela também permite que novos valores sejam atribuídos a variável. Mas, com a modernização da linguagem essa forma caiu em desuso. 

 

**Regras para nomear variáveis** 

Por convenção elas devem seguir as seguintes regras: 

1º Deve ser uma única palavra 

2º Para usar mais de uma palavra adota-se a convenção camelCase: 

- O primeiro nome deve iniciar com letra minúscula e os demais iniciam com maiúscula.   

3º Nomes de variáveis podem conter somente letras, números, undescore ou cifrão, mas a nome não pode começar com um número. 

4ª Palavras reservadas pela linguagem não podem ser utilizadas como nome de variáveis 

 

_Obs._ Escolha nome de variáveis que revelem a intenção do que ela realiza. Isso vai facilitar que outros desenvolvedores saibam o tipo de informação que está sendo guardada 

 

**Comentários** 

Como o próprio nome sugere, é uma forma que os programadores utilizam para escrever um comentário sobre o que o código faz. A linha que estiver com o comentário não será executada pelo Javascript, ou seja, será ignorada. 

 

Comentário de uma linha que é feito colocando //. 

// Este comentário é de uma linha  

Comentário em bloco, feito com /* */ 

/* Este bloco diz respeito  

Comentário em bloco*/

**Comment by Roger-Melo** [comment]
Excelente @MarioFilho1, rumo à fluência! 🎯
