### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3597]
### Constantes ou ```const```:
Na MDN temos um resumo que diz:
"```A  declaração const cria uma **variável** cujo o **valor é fixo**...```"
Bem contraditório, né?!?! rs...

Mas sua aplicação é fundamental!!!!

Pensei bastante sobre sua necessidade e imaginei a seguinte situação.
Imagine um sistema de um Posto de Gasolina que contenha umas mil linhas. Dentro dessas mil linhas, utilizamos o preço da gasolina para vários cálculos que vão além da bomba de gasolina. Podemos imaginar usarmos seu valor umas 53 vezes em locais diferentes das mil linhas do código.
Daí declaramos: ```const gasPrice = 7,89``` (Olha o "camel case" aí!)
Usando uma ```const```, de cara isso garante que vamos inserir uma única vez e será alterado em todas os demais 53 lugares que é utilizada.

### Variáveis
Mas poderíamos perguntar, por quê então não usar o ```let```?
A resposta é simples, a ```const``` não permite ser alterada, ao passo que o ```let``` permite. Imagine se alguém atribui um valor diferente bem no meio do código? Se for uma ```const``` o sistema dá erro, enquanto se fosse com o ```let``` o sistema roda e os cálculos dariam errado. O que é bem mais grave a luz do cliente! :-/

Como o ```var``` está sendo cada vez menos utilizado, não faz sentido aprofundar. Apesar de que, na minha opinião, o ```var``` (var_iável) é mais intuitivo que ```let``` (deixar, permitir) sei lá...!

### Comentários
É uma mão na roda poder comentar o código, principalmente no início do curso. Mas imagino que na vida profissional é melhor fazer um código mais legível do que com muitos comentários.

ATER NA VÉIA!!!
Aula e teoria já foram, faltam exercício e revisão!!!

Obrigado Professor!

**Comment by Roger-Melo** [comment]
Excelente @andersonpereiragithub, rumo à fluência! 🎯
