### ISSUE TITLE
Resumo da Aula 01 da etapa 02

### ISSUE THREAD

**Issue by tiagodavanzo** [roger-melo-treinamentos/curso-de-js-roger-melo#3598]
- Javascript é uma linguagem universal, desde a criação de sites e aplicações web, aplicativos mobile, servidores, programação de robôs, dentre outros;
- O foco do treinamento será no navegador (frontend), onde foi projetado originalmente;
- Inicialmente será abordado a base (variáveis, funções, loops, objetos), antes de entrar em tópicos avançados como orientação a objetos e programação funcional, sempre foi muita prática;
- O javascript pode ser usado no backend, através do Node.js.

**Comment by Roger-Melo** [comment]
Excelente @tiagodavanzo, rumo à fluência! 🎯
