### ISSUE TITLE
Quiz interativo - CJRM.

### ISSUE THREAD

**Issue by lucas-giraldelli** [roger-melo-treinamentos/curso-de-js-roger-melo#36]
https://github.com/lucas-giraldelli/quiz-interativo-cjrm

Mudei a temática para jogos (e a paleta de cores), mantive a quantidade de perguntas e lógica que foi aplicada na aula anterior.

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
A minha maior dificuldade é realmente em relação ao bootstrap apenas, tive que consultar a documentação para alterar algumas coisas a meu gosto.
- Quais foram as suas menores dificuldades durante a execução desse exercício.
Quanto a recuperar elementos do DOM, conseguir entender que a referencia do form capturada com querySelector já traz os inputs (com name ou id) isso é tudo muito genial, inclusive para inserir o texto do placar final eu apenas utilizei um h2 vazio e capturei por referencia e inseri na mesma utilizando o textContent (lembro-me bem que a diferença dele pro innerText é a quantidade de texto capturada).

**Comment by Roger-Melo** [comment]
Oi Lucas!

Nostalgia pura quando li a 1ª pergunta do quiz =D

> A minha maior dificuldade é realmente em relação ao bootstrap apenas, tive que consultar a documentação para alterar algumas coisas a meu gosto.

Se as maiores dificuldades foram com o bootstrap, pode ser um bom sinal hahah.

> Quanto a recuperar elementos do DOM, conseguir entender que a referencia do form capturada com querySelector já traz os inputs (com name ou id) isso é tudo muito genial, inclusive para inserir o texto do placar final eu apenas utilizei um h2 vazio e capturei por referencia e inseri na mesma utilizando o textContent (lembro-me bem que a diferença dele pro innerText é a quantidade de texto capturada).

Isso mesmo, o `innerText` retorna o texto visível de um nó do DOM, e o `textContent` retorna todo o texto do nó, independente se o texto está visível ou não.

Nas aulas seguintes, mostro sugestões de refatoração do código dessa aplicação.

Parabéns pelo esforço em concluir mais essa etapa do treinamento! No que precisar, é só dar o toque =D

@lucas-giraldelli

**Comment by Roger-Melo** [comment]
Lucas, vou fechar a issue mas no que precisar é só dar o toque =)

**Comment by lucas-giraldelli** [comment]
Muito obrigado! :D :-1:
