### ISSUE TITLE
Resumo da Aula Switch case da etapa 02

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3603]
<h1 align="center">Switch case</h1>
 <p align="justify">O switch case ou switch statement, é um condicional que faz uma checagem por casos. Após a declaração do switch, observe que a constante é verificada para saber qual o valor dará match e terá um retorno de um código. <br /> É importante saber também que após cada case é necessário que o código pare, senão os outros cases vão ser verificados, e por esse motivo utilizamos o break após os consoles, no exemplo da imagem abaixo.<br />Caso nenhuma das opções dê um match o default será executado</p>
<img src="https://user-images.githubusercontent.com/53193423/168098745-90f93968-fd89-4abc-9c5d-48bf7ef45ad1.png" />

**Comment by Roger-Melo** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯
