### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3606]
STRINGS

- String é um encadeamento de caracteres. 
- Uma string pode ser armazenada com ‘’ ou “”. O importante é que se abrir com uma, necessariamente tem que fechar com a mesma.
- Uma string pode ser armazenada em uma variável.
- Uma string pode ser concatenada com outra, ou seja, juntá-las em uma só através do sinal de +.
- É possível acessar um caractere específico dentro de uma string, neste caso, utilizando os [ ] colchetes para tal. O número dentro do colchete representa o índice do caractere que será demonstrado.
- As strings possuem propriedades e métodos. A diferença na representação das mesmas é basicamente a utilização dos ( ) parênteses nos métodos, pois esta ação que indica que o método está sendo invocado.
- Dentre os métodos, existem aquele que precisam de argumentos para serem executados.

Abaixo códigos da aula

```javascript
// strings
// Armazena com '' ou "".
console.log('Hello, world')
 
const email = 'leon@rogermelo.com.br'
console.log(email)
 
// concatenação de strings
// ação de juntar duas strings, ou coisas
// Utiliza-se o sinal de +
 
const firstName = 'Nathan'
const lastName = 'Drake'
const fullName = firstName + ' ' + lastName
 
console.log(fullName)
 
// acessando caracteres
// Utiliza-se colchetes para acessar caracteres específicos de acordo
// com sua posição
console.log(fullName[2])
 
//comprimento de uma string
// length
// Para acessar propriedade utiliza-se a notação ponto.
console.log(fullName.length)
 
// métodos de string
// Possui-se muitos métodos
// Por ser um método, ele precisa ser invocado com um parênteses
console.log(fullName.toUpperCase())
 
const result = fullName.toLowerCase()
 
console.log(result, fullName)
 
// Dentro dos parênteses nós chamamos de argumentos
// Este método busca o index, posição, dentro do email
const index = email.indexOf('@')
console.log(index)
 
// Mesmo que coloque números entre aspas, estes serão entendidos
// como textos. Tudo dentro das aspas são caracteres.

```

**Comment by Roger-Melo** [comment]
Excelente @lucian-bonifacio, rumo à fluência! 🎯
