### ISSUE TITLE
Resumo da Aula Async/await - Aula 05-04 da etapa 11

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#3607]
================= ASYNC / AWAIT =================

Async/Await são sintax sugar, abstrações de promises que usam promises por baixo dos panos que nos permite escrever código ainda mais legível que é lido como se fosse um código síncrono.

Repare que no código anterior, estamos executando a FETCH API, encadeando várias promises que tratam do passo a passo para nos podermos manipular os dados retornados.

Esse código é melhor do que funções de callback com objetos XMLHttpRequest, só que, quando o número de promises passa a aumentar, o código começa a ficar ilegível e imanutenível. Para isso surgiu as palavras chave 'async/await' para melhorar a legibilidade e manutenabilidade do código, fora as boas práticas.

Quando usamos 'async/await' podemos setar o código assíncrono (async) em uma função e usar dentro dessa função a palavra (await) para lidarmos com promises de uma forma mais legível, evitando assim configurar explicitamente encadeamento de promsises.

* Toda função assíncrona retorna uma Promise, independente do conteúdo que está dentro dela.

* Sabemos que o FETCH retorna uma promise e para obter os dados retornado nós encadeávamos o método THEN para tratar os dados. Agora não precisaremos  disso, nós vamos inserir o 'await' antes da chamada do FETCh.

* Esse await irá 'aguardar' a resposta da requisição, enquando essa resposta não chegar, o await não deixa o código abaixo dele ser executado. Ou seja,  ele vai se comparar a um código síncrono.

* Caso ocorra tudo bem com a requisição, o await irá retornar o valor resolvido da promise, que é o objeto Response. Após isso as linhas abaixo dele serão executadas.

Para obtermos os dados da resposta do request, precisaremos encadear no objeto response o método json() que irá obter esse objeto response, irá parsear para um array de objetos javascript e retorna-rá uma promise que contém esse resposta parseada.

  Veja abaixo:

```.js
const getUsers = async () => { // tornando a função assíncrona / também aceita function declaration
  const response = await fetch('https://anapioficeandfire.com/api/houses') // retorna objeto response da promise
  const users = await response.json() // retorna valor resolvido da promise
  return users
}

const logUsers = async () => {
  const users = await getUsers()
  console.log(users)
}

logUsers()
```

**Comment by Roger-Melo** [comment]
Excelente @santos2408, rumo à fluência! 🎯
