### ISSUE TITLE
Resumo da Aula Inserindo na interface os ícones e imagens 02-06 da etapa 12

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3613]
Referenciamos os elementos da página que devem receber a imagem do card e do ícone que corresponde ao clima.
```js
let timeImg = document.querySelector('[data-js = "time"]')
let timeIconContainer = document.querySelector('[data-js = "time-icon"]
```
Na chamada da função `getCityWeather()`, inserimos a propriedade `IsDayTime` no destructuring do objeto retornado pela função, pois baseada nela alteramos a imagem do card.

Logo após a condicional que inserimos no código, inserimos um outro `if` que verifica o valor de `IsDayTime` e altera a imagem exibida, por meio da manipulação do atributo `src` do elemento `img`, indicando o diretório que contém as imagens a serem utilizadas.
```js
if (IsDayTime) {
    timeImg .src = ‘./src/day.svg’
} else {
    timeImg.src = ‘./src/night.svg’
}
```
Ainda na função `getCityWeather()`, inserimos a propriedade `WeatherIcon` no destructuring do objeto retornado, pois com base nela alteramos os ícones de clima. O valor dela compreende 1 a 44, de acordo com as condições do clima. 

Após a chamada da função `getCityWeather()`, criamos o elemento `img` que deve receber o ícone e adicionamos ele dentro do respectivo container. De forma similar ao anterior, direcionamos seu `scr` ao diretório que contém os ícones a serem utilizados.
```js
const timeIcon = `<img src="./src/icons/${WeatherIcon}.svg />`
```
E, logo após as condicionais, inserimos a constante com o elemento criado dentro da respectiva `div`, usando o `.innerHTML`.
```js
timeIconContainer.innerHTML = timeIcon
```
No arquivo css, especificamos alguns estilos para ajustar a disposição do ícone e atribuímos estes a uma classe, que adicionamos na `div` do ícone.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
