### ISSUE TITLE
Encadeamento de Promises

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3615]
### Etapa da aula

11

### Nome da aula

Encadeando promises - Aula 04-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1309715

### Descreva a dúvida

Olá, Roger!
Gostaria de saber qual a diferença entre encadear promises e fazer uma requisição em cada linha.

Exemplo:
```js
const getPokemon = url => new Promise((resolve, reject) => {
  const request = new XMLHttpRequest()

  request.addEventListener('readystatechange', () => {
    const isRequestOK = request.readyState === 4 && request.status === 200
    const isRequesyNotOk = request.readyState === 4

    if(isRequestOK) {
      const data = JSON.parse(request.responseText)

      resolve(data)
    }

    if(isRequesyNotOk) {
      reject('Não foi possível obter os dados')
    }
  })

  request.open('GET', url)
  request.send()

})

//Porquê fazer requisições assim:

getPokemon('https://pokeapi.co/api/v2/pokemon/pikachu')
  .then(pikachu => {
    console.log(pikachu)
    return getPokemon('https://pokeapi.co/api/v2/pokemon/4')
  })
  .then(charmander =>{
    console.log(charmander)
    return getPokemon('https://pokeapi.co/api/v2/pokemon/7')
  })
  .then(console.log) //Exibe os dados do squirtle
  .catch(error => console.log(error)) 

// E não assim:
getPokemon('https://pokeapi.co/api/v2/pokemon/30').then(console.log).catch(error => console.log(error)) 
getPokemon('https://pokeapi.co/api/v2/pokemon/4').then(console.log).catch(error => console.log(error)) 
getPokemon('https://pokeapi.co/api/v2/pokemon/7').then(console.log).catch(error => console.log(error)) 

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Dá uma olhada [nessa resposta](https://drive.google.com/file/d/1quOv0YfjEYdSZwYKGen_8ITEH9vMpmhB/view?usp=sharing) e se restar alguma dúvida, é só dar o toque =)

**Comment by BrunodevOliveira** [comment]
Entendi, professor! 
Uma outra dúvida que surgiu agr é que utilizando apenas um catch() para todas requisições se modificar o endPoint para algum errado na primeira requisição, por exemplo, todas as requisições posteriores não são efetuadas. Independente se os outros endPoints estão corretos ou não, o código pula para o catch() e finaliza.

Utilizando o mesmo código da primeira dúvida, se eu passar um endPoint errado na primeira requisição, o catch() é executado e todas as demais requisições encadeadas deixam de ser executadas. Existe uma forma para evitar que isso aconteça?
``` js
 getPokemon('https://pokeapi.co/api/v2/pokemon/EndPointErrado')
  .then(pikachu => {
    console.log(pikachu)
    return getPokemon('https://pokeapi.co/api/v2/pokemon/4') //Request não executado
  })
  .then(charmander =>{
    console.log(charmander)
    return getPokemon('https://pokeapi.co/api/v2/pokemon/7') //Request não executado
  })
  .then(console.log) 
  .catch(error => console.log(error)) //Executa o catch por conta do erro da primeira requisição
```

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Dá uma olhada [nessa resposta](https://drive.google.com/file/d/1Ywk_csinT8NqZM9k3yzl61froTtrYyDm/view?usp=sharing) =)

**Comment by Roger-Melo** [comment]
Ficou mais claro? Vou fechar a issue, mas no que precisar, é só abrir uma nova =)

**Comment by Roger-Melo** [comment]
@BrunodevOliveira veja também o método allSettled, [clicando neste link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled).
