### ISSUE TITLE
Resumo da Aula 06-04 da etapa 11 - Tratando erros com try/catch

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3616]
- Quando um erro é lançado numa aplicação JS, o código abaixo do 
código que disparou o erro não é executado.

```js
console.log(oi)
console.log('oi')
```
![image](https://user-images.githubusercontent.com/92958989/168403393-c892b085-21fd-4435-8fb1-cd54b670188f.png)
Não existe a declaração de uma variável oi no código e depois desse erro nada é exibido no console.

Para resolver esse problema será utilizado um `try/catch` que é uma cláusula que vai tentar executar um código.
Se o código que ela tentar executar lançar algum erro, será possível executar algum outro código e o erro 
lançado não vai travar o restante do código da aplicação.

```js
try {
  /*
    código que quero tentar executar.
    se o código dentro deste bloco do try lançar algum erro, esse erro é 
    recebido dentro dos parênteses do catch.
  */
  console.log(oi)
} catch (error) {
  /*
    dentro deste bloco do catch, será possível fazer alguma coisa com o erro
    ou executar outra ação, já que o erro é conhecido.
  */

  //para visualizar o erro.
  console.log(error)
}
console.log('oi')
```
![image](https://user-images.githubusercontent.com/92958989/168404375-7bfd3f6f-49f0-4fa7-a1a5-85d8ae95ae69.png)
Como não está sendo exibido como um erro o código abaixo do `try/catch` foi executado
e a string oi foi exibida no console, a aplicação não travou por causa do erro.

```js
try {
  console.log(oi)
} catch (error) {
  console.log(error.name, error.message)
  /*
    Agora que o erro está dentro do catch, é possível usar informações desse erro 
    para executar alguma ação.
    Em JS todo objeto de erro tem as propriedades name e message que armazenam o 
    nome e a mensagem do erro
  */
}
console.log('oi')
```
![image](https://user-images.githubusercontent.com/92958989/168404769-1203b2d1-2b1d-4d11-84eb-425929143d74.png)

A `error.name` retornou que o `error` é um `ReferenceError`
A `error.message` retornou que a mensagem é `oi is not defined`
  
A partir dessas informações de objeto de erro, é possível fazer alguma coisa, por exemplo.

```js
try {
  console.log(oi)
} catch (error) {
  if (error.name === 'ReferenceError' && error.name === 'oi is not defined') {
    const oi = 'const oi criada'
    console.log(oi)
  }
}
console.log(oi)
```
```js
try {
  console.log(oi)
} catch (error) {
  if (error.name === 'ReferenceError' && error.message === 'oi is not defined') {
    const oi = 'const oi foi criada'
    console.log(oi)
  }
}
console.log(oi)

```
![image](https://user-images.githubusercontent.com/92958989/168405689-d5981b42-2085-41a4-9ee3-33ce170264f9.png)
A `const oi` foi criada e o código abaixo do `try/catch` foi executado. 

O `try/catch` é utilizado quando quando for feito alguma coisa em relação ao objeto de erro que o `catch` recebe 
Existe para tratar um erro que o código pode lançar, se esse não é o caso, um `if` pode ser utilizado.
O `try/catch` exige mais poder de processamento do que condicionais como o `if`, usar o `try/catch` muitas vezes 
como alternativa do `if` deixará a aplicação mais lenta.

**Comment by Roger-Melo** [comment]
Excelente @Jansen-Muniz, rumo à fluência! 🎯
