### ISSUE TITLE
Erro no código da aula 

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3617]
### Etapa da aula

11

### Nome da aula

Tratando erros com try/catch - Aula 06-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1372048

### Descreva a dúvida

Roger, eu escrevi o código igual ao da aula, mas no console não apresentou a mesma mensagem.
O código é esse:
```js
try {
  console.log(oi)
} catch (error) {
  if (error.name === 'ReferenceError' && error.message === 'oi is not defined') {
    const oi = 'const oi foi criada'
    console.log(oi)
  }
}
console.log(oi)
```
```html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script src="./app.js"></script>
</body>

</html>
```
A mensagem que apareceu no meu console:
![image](https://user-images.githubusercontent.com/92958989/168406408-30572d8f-c28f-4b6f-9ff2-649beac43917.png)

A mensagem do console na aula:
![image](https://user-images.githubusercontent.com/92958989/168406380-1f513f30-d43f-4fd4-a2b1-b6782abfee80.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz! Dá uma olhada [aqui](https://drive.google.com/file/d/15cadSk8_NsZh9PtIek9LqdVLu6rrB9-m/view?usp=sharing) e se restar alguma dúvida, é só avisar =)

**Comment by Jansen-Muniz** [comment]
Que vacilo =(
Entendido. Valeu mano Roger.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
