### ISSUE TITLE
Resolução diferente de exercícios

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3618]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1324088

### Descreva a dúvida

Opa, Roger!
Durante a resolução dos exercícios acabei resolvendo alguns de forma diferente e gostaria de saber se amaneira que fiz está correta também ou se não é adequado para o caso: 

## Questão 03) 
Crie um novo array chamado `newSul`, que recebe somente os estados do sul, pegando do array `brasil`. Não remova esses itens de `brasil`.

Resolução do vídeo: 
``` js
 const newSul = brasil.slice(2,5) 
 // ['Paraná', 'Santa Catarina', 'Rio Grande do Sul']
```
Forma que eu fiz:
``` js
 const newSul = brasil.filter(estado => sul.includes(estado)) 
 // ['Paraná', 'Santa Catarina', 'Rio Grande do Sul']
```
## Questão 04) 
Adicione os estados do `nordeste` ao array `brasil`. Esses estados devem ficar no mesmo nível que os estados já existentes, não em um array separado

Resolução do vídeo: 
``` js
//Modificando a var brasil de const para let
 brasil = brasil.concat(nordeste)
 // ['Amapá', 'Amazonas', 'Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Bahia', 'Ceará', 'Maranhão', 'Paraíba', 'Piauí', 'Rio Grande do Norte', 'Pernambuco', 'Alagoas', 'Sergipe']
```
Forma que eu fiz:
``` js
 nordeste.forEach(estado => brasil.push(estado))
 // ['Amapá', 'Amazonas', 'Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Bahia', 'Ceará', 'Maranhão', 'Paraíba', 'Piauí', 'Rio Grande do Norte', 'Pernambuco', 'Alagoas', 'Sergipe']
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Dá uma olhada [aqui](https://drive.google.com/file/d/1eBttVz0mlZj63rehup7lmhPkgEkJg0Ix/view?usp=sharing) e se restar alguma dúvida, é só avisar =)

**Comment by BrunodevOliveira** [comment]
Obrigado, Roger!
É que treinamos tanto os métodos map, filter, reduce e forEach que nos de exercícios sempre me vem algum deles em mente para resolver o que foi proposto. Mas como não utilizamos, achei que teria algum motivo específico.

**Comment by Roger-Melo** [comment]
Show. 

Talvez eu não tenha usado para enfatizar o uso de algum método que mostrei recentemente, nas aulas anteriores. Mas a forma que vc resolveu também é válida.

No que precisar, é só abrir uma nova issue =)
