### ISSUE TITLE
Resumo da Aula Callbacks da etapa 03

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3619]
<h1 align="center">Callbacks</h1>

Como sabemos uma função pode receber como parâmetro, vários tipos de dados, strings, numbers, booleans e além de todos esses que já vimos, podemos passar também uma função pra ser executada dentro do bloco de código, e essas funções se chamam callbacks.

```js
const testandoCallbacks = callback => {
  console.log(callback())
}

testandoCallbacks(() => oi)
//resultado Oi
```

Basicamente criamos uma função que recebe uma função como parâmetro e a invocamos no console.log, a chamada da função testandoCallbacks recebe como argumento a execução de uma função passando algum valor, esse valor será a referência do parâmetro 'callback' que criamos na função.

## ForEach
Algumas funções funcionam dessa maneira e são muito poderosas como o _forEach_, primeiro vamos ver a sua estrutura e em seguida vamos comenta-las:

```js
const dias = [segunda,  terça, quarta, quinta, sexta, sábado, domingo]

dias.forEach( dia => {
  console.log(`${dia}-feira`)
})

// resultado: segunda-feira ...
```

**Comment by Roger-Melo** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯
