### ISSUE TITLE
Retorno de uma função async

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3621]
### Etapa da aula

11

### Nome da aula

Async/await - Aula 05-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1338555

### Descreva a dúvida

Olá, Roger, acho que bati meu recorde de dúvidas em um só dia rs
Dessa vez tenho duas dúvidas sobre o funcionamento do async/await e vou colocar aqui o código utilizado na aula como exemplo:

``` js
const getUsers = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users')

  const users = await response.json() 
  console.log( typeof users)  //object
  return users   //Promise {<pending>}
}
```

Não consegui entender como esse código é considerado assíncrono sendo que ele espera (await) a resposta da requisição chegar para executar as demais linhas de código. Nesse caso ele não seria um código bloqueante?

Se response.json() retorna as informações que eu estou buscando no request como um objeto, pq ao retornar  essa var em uma função async ela vira uma promise novamente e não o obj resultante do método json()? Não seria mais lógico retornar o valor que buscamos na requisição de uma vez ao invés de uma nova Promise?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira! Pode perguntar sempre que tiver dúvida =)

Respondi as dúvidas [neste vídeo](https://drive.google.com/file/d/1jntg0kJKObL5YkA_vQW4_lbVdkc4uF6L/view?usp=sharing) =)

**Comment by BrunodevOliveira** [comment]
Obrigado, Roger! Com essa explicação consegui entender o funcionamento do async/await

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
