### ISSUE TITLE
Resumo da Aula For loop - Aula 01-03 da etapa 02

### ISSUE THREAD

**Issue by ricardoGiThUb84** [roger-melo-treinamentos/curso-de-js-roger-melo#3623]
## O for é um statment de loop e faz parte dos controladores de fluxo em um código.

```js
for(let i = 1; i <= 10; i = i+1){

  console.log("numero", i)
}
```
:bulb: **Hint:**  O **for( )** é responsável por repetir uma execução de um bloco de código **n vezes** até que a condição de quebra, **_no caso do for uma condição conhecida_**, seja atingida e interrompa o loop de execução.

- Parâmetros do for
- let i = 1; // É uma declaração de variável para inicialização.
- i <= 10; // <= é um operador lógico que vai checar se a condição do loop é verdadeira ou falsa.
- i++ // operador de incremento que é um atalho para o += ou o i = i+1;

**Comment by Roger-Melo** [comment]
Excelente @ricardoGiThUb84, rumo à fluência! 🎯
