### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3624]
Nesta aula, primeiro observa-se que métodos são funções que pertencem a um objeto.

Dito isto, vamos ao primeiro método aprendido:
`string.lastIndexOf( )`
- Este método pega a última ocorrência do caracter especificado como argumento

`string.slice( )`
- Utilizo quando quer buscar uma parte de uma string
- Utiliza-se dois argumentos:
  - No primeiro refere-se ao index que inicia-se a parte do caracter que busco.
  - No segundo refere-se que a partir dele que o método ignora.
- Este método não altera a string original

`string.replace( )`
- Este método vai substituir o caracter de uma string, por outro.
- Passa-se dois argumentos:
  - O primeiro é a string que a gente quer substituir
  - O segundo é o caracter que vai substituir o caracter que foi passado no primeiro argumento
- Só a primeira ocorrência do caracter a ser substituído, é substituída
- Posso substituir palavras inteiras
- Este método não modifica a string original

Códigos da Aula
``` javascript
const email = '[laracroft@rogermelo.com.br](mailto:laracroft@rogermelo.com.br)'
const lastIndexOfA = email.lastIndexOf('a')
const emailSlice = email.slice(4, 9)
const emailReplace = email.replace('laracroft', 'chun-li')
```

**Comment by Roger-Melo** [comment]
Excelente @lucian-bonifacio , rumo à fluência! 🎯
