### ISSUE TITLE
Resumo da Aula Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by danielleoliveira-dev** [roger-melo-treinamentos/curso-de-js-roger-melo#3629]
# A condicional switch

Obs: 
- Ctrl +Shift + alt, pressiona a seta para cima para posicionar o cursor em multiplas linhas, pressiona enter e todas as linhas irão aparecer com espaços simultaneamente e a digitação posterior tbm aconetcerá em todas essas linhas :)

- Ctrl + D, end e vai para o final

	## //switch statement
	
	    const grade = 'A'
	    switch (grade){
		   case 'A':
			  console.log('Você tirou uma A')
			  break
		    case 'B':
			   console.log('Você tirou uma B')
			    break
		     case 'C':
			    console.log('Você tirou uma C')
			    break
		     case 'D':
			     console.log('Você tirou uma D')
			     break
		     case 'E':
			     console.log('Você tirou uma E')
			     break
		      default:
			     console.log('Nota inválida')
	     }

*Inserir o break fará dar match com o que está sendo solicitado e somente o case 'A' como no exemplo acima seja executado.* 

	##//usando if statements

	const grade = 'B'
	if (grade === 'A') {
	} else if (grade === 'B') {
	} else if (grade === 'C') {
	} else if (grade === 'D') {
	} else if (grade === 'E') {
	}else {
	}

**Comment by Roger-Melo** [comment]
Excelente @danielleoliveira-dev, rumo à fluência! 🎯
