### ISSUE TITLE
Resumo da Aula Variáveis e escopo de bloco da etapa 04

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3631]
<h1 align="center">Variáveis e escopo</h1>

Escopo global é uma área de acesso no código para todas as outras áreas e escopo local é uma área de acesso restrita a um bloco, isso faz com que por exemplo, uma variável declarada no inicio do código, possa ser acessada de qualquer escopo ou bloco de código, já uma variável criada dentro de um determinado bloco só poderá ser vista nesse escopo. Um exemplo de que esses escopos são independentes é se uma variável for declarada com o nome obj como global, e declarada novamente com o mesmo nome dentro de um if, os dois funcionaram de forma independente, pois o do if só será usada no if, e o do global será usada em todo o resto com exceção do if, porém se no if ao invés de declarar você apenas acessar o obj sem o let na frente, ai essa variável estará fazendo referência à variável global.

**Comment by Roger-Melo** [comment]
Show @Beninigmal. Vamo que vamo, rumo à fluência! 🙌
