### ISSUE TITLE
Resumo da Aula Conversão de tipos (Aula 04-04) da etapa 01

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3637]
# Conversão de tipos - Aula 04-04 - Resumo

## O que faz a função construtora `Number()`?

Essa função converte um número dentro de uma ***string*** em um número inteiro ou decimal.

```javascript
let score = '100'
score = Number(score)

console.log(score + 1)
// returns 101
``` 

## O que faz o operador `typeof`?

Esse operador retorna tipos de valores.

```javascript
console.log(typeof score)
// returns "number"
```

## O que acontece quando tentamos converter um nome dentro de uma ***string*** em um número?

O valor retornado será `NaN` (***not a number***) porque se trata de uma expressão sem sentido.

```javascript
const crazyConversion = Number('Maçã')
console.log(crazyConversion)
// returns NaN
```

O que faz a função `String()`?

Essa função converte um número em uma ***string***.

```javascript
const convertedNumber = String(97)
console.log(convertedNumber)
// returns "97"
```

## O que faz a função `Boolean()`?

Essa função converte um valor qualquer em um valor lógico.

```javascript
const booleanConversion = Boolean(10)
console.log(booleanConversion)
// returns true
```

## O que são valores ***falsy***?

São valores que, quando convertidos em valores lógicos, retornam `false` como resultado.

## Quais são os valores ***falsy***?

Os valores ***falsy*** são:

```javascript
/*
- false
- " ", ' ', ` `
- 0
- null
- undefined
- NaN
*/
```

## O que são valores ***truthy***?

São todos os valores que, quando são convertidos em valores lógicos e não estão no grupo dos valores ***falsy***, retornam `true`.

```javascript
console.log(Boolean('Oi'))
// returns true
```

**Comment by Roger-Melo** [comment]
Show @ananopaisdojavascript. Vamo que vamo, rumo à fluência! 🙌
