### ISSUE TITLE
Resumo da Aula numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3644]
# Tipos de dados Numbers. 

**Inteiros e decimais** 

Podem ser declarados da seguinte forma: 
```js
Const radius = 10 

Const pi = 3.14 

Console.log (3.14, 10) 
```
Declaramos o número inteiro 10 para a variável radius, o decimal 3,14 para pi e exibimos os dois no console. Apenas com a utilização do ponto (.) indicamos que o valor é um número decimal. Ambos os valores fazem parte do mesmo tipo de dado em javascript. 

 
**Operadores Aritméticos** 

Em javascript podemos realizar praticamente todos os cálculos matemáticos. 
```js
Console.log (10/2) -> será exibido o valor 5. 
```
 
Em javascript podemos obter o resto de uma divisão através do operador módulo representado pelo % 
```js
Const modulo = 10 % 3 

Console.log (modulo) -> será exibido o valor 1, que é o resto da divisão entre os operandos 10 e 3. 
```
 
Assim como na matemática básica, em javascript também existe a precedência  na resolução das expressões que contenham mais de uma operação. 
```js
Const area = pi * radius ** 2 

Console.log(area) 
```
O cálculo acima foi utilizado para obter o raio de uma determinada área.  

Primeiro é executado a operação de radius elevado a ² potência, o resultado é multiplicado com pi e depois armazenado na variável area. Essa operação só pode ser realizada devido a precedência que dita a ordem em que as operações serão executadas. 

Ordem da precedência: 

1º parênteses 

2º expoentes ou raízes 

3º multiplicação e divisão 

4º adição e subtração 

 ```js
console.log(3+(20+4)/4*2) -> nesse exemplo a precedência ocorre da seguinte forma 
```
1º Será realizado a soma entre os parênteses 

2º A divisão entre o resultado e o operando 4 

3º O resultado da divisão e a multiplicação 

4º O resultado da multiplicação é somado ao operando 3 

O resultado da operação é 15. 

 
**Incremento e decremento** 
```js
`Let contador = 10 
```
Quando queremos incrementar em 1 o valor de uma variável podemos fazer das seguintes formas: 
```js
Contador = contador + 1 
```
A variável recebe o valor 10 + 1, e passa a valer 11. Também podemos utilizar a forma abreviada com o operador de incremeto ++ 
```js
Let valor = 20 

Valor++ -> desse modo haverá o incremento é uma unidade. 
```
Existe também a forma abreviada para o decremento utilizando o operador ``--`` 
```js
Valor--   -> o resultado será 19 
```
  

**Operadores assignment** 

São formas abreviadas de incremento, decremento, multiplicação e divisão com valores maiores que 1. 

 ```js
Let operador = 5 

operador += 10 -> a variável recebe o seu valor (5) e soma 10, resultado é 15.  

Operador -= 5 -> a variável recebe o seu valor (15) e diminui 5, a variável passa a conter 10. 

Operador *= 3 -> a variável recebe o seu valor (10) multiplicando por 3, o novo valor é 30. 

Operador/= 5 -> a variável recebe o seu valor (30) e divide por 5 o resultado é 6 
```
 

**NaN – not a number** 

Esse operador é exibido quando uma operação não faz sentido. 
```js
Console.log(operador / ‘oi’) 
```
Como não existe divisão entre o número e uma strig, o console irá exibir a mensagem NaN 

 

**Concatenação entre número e string** 
```js
Const postLikes = 30 

Let message = ‘O post tem’ + postLikes + ‘likes.’ 

Console.log(menssage) -> o post tem 30 likes 
```
Quando concatenamos string com número, o javascript converter o número em string. 

O resultado de uma concatenação de string e número, será sempre uma string .

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
