### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3646]
**STRING**
Na [Wikipédia](https://pt.wikipedia.org/wiki/Cadeia_de_caracteres) **String** é "(...)uma **cadeia de caracteres** ou é uma **sequência de caracteres**, geralmente utilizada para representar palavras, frases ou textos de um programa." 

Sendo assim, toda vez que uma variável armazena uma string ela passa ater **atributos** e **métodos** que podem ajudar na sua manipulação dentro do sistema.

Como uma string é uma cadeia de caractere, é mais fácil de entender que nela existe um "comprimento" ou tamanho que de forma geral é um TRIBUTO. E o seu comprimento é a soma de todos os seus caracteres, incluindo os espaços se houverem. 
Onde cada caractere que a compõe é determinado por um índice, iniciando por 0 (zero) da esquerda para direita.
Ou seja, na palavra **Brasil** tem um comprimento (length) que é igual a 6, onde:
![string](https://user-images.githubusercontent.com/58309283/168944217-a07f747a-503b-4375-afd4-f91e1dba6025.png)

O que possibilita acessar cada caractere de forma individual.
Exemplo individual ```const country =  "Brasil"``` - ```country[3]``` resultado é o caractere ```s```;

Tanto seus atributos quanto os métodos podem ser acessados logo após a inclusão de um (.) ponto.
Exemplos: 
```country.length``` o resultado dessa expressão é que a variável ```country``` tem o cumprimente 6;
```country.toUpperCase()``` temos um **método** onde o resultado é transformar todos os caracteres em maiúsculas.
```country.indexOf('r')``` temos um método onde o resultado é o índice da posição do caractere enviado como parâmetro.

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
