### ISSUE TITLE
Etapa 01, nome do vídeo: EXercicios da Aula -01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#365]
Erro na instalação do Hyper, meu pc usa W7-32bits
[SquirrelSetup-Log_Hyper.txt](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/6261152/SquirrelSetup-Log_Hyper.txt)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Marcos.

O uso do terminal é opcional. Você pode abrir o terminal do windows pressionando "windows" e pesquisando por "terminal" e seguir os mesmos passos mostrados com o hyper.

Caso não queira usar o terminal, pode seguir [este tutorial](https://youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA).

@marcosyoggy

**Comment by Roger-Melo** [comment]
@marcosyoggy vou fechar a issue mas quando surgirem dúvidas, é só abrir uma nova =)
