### ISSUE TITLE
Aplicação: QUIZ

### ISSUE THREAD

**Issue by hayttle** [roger-melo-treinamentos/curso-de-js-roger-melo#3653]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Sim

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/hayttle/curso-javascript-roger-melo/tree/main/exercicio-quiz

### Maiores dificuldades durante a implementação

Não houve

### Menores dificuldades durante a implementação

Não houve

**Comment by Roger-Melo** [comment]
Olá @hayttle!

Vou deixar a análise de seu Weather App [aqui](https://drive.google.com/file/d/1GrEQXbQH8Y6C8dUYHva2wJ6jp6UKLNjY/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by hayttle** [comment]
Oi @Roger-Melo 

Sobre subir em repositório separado até entendo para um portfólio, que até já tenho um rascunho, mas não cheguei a pensar neste caso específico subir agora.
Link: https://hayttle.github.io/
Repo: https://github.com/hayttle/hayttle.github.io)
Não tratei a responsividade, UI/UX, apenas a funcionalidade do quiz, mas me atentarei para os próximos
A ideia das questões estarem no JS é preparando para buscar de uma API, com isso realmente gerou forEachs aninhados
As aspas simples e duplas foi a autoformatação do VSCode

Obrigado pela análise. =)
