### ISSUE TITLE
Resumo da Aula inaugural 

### ISSUE THREAD

**Issue by CarlosHenrique2** [roger-melo-treinamentos/curso-de-js-roger-melo#3654]
#### Resumo Da Aula Inaugural do Treinamento CJRM <h4>
* Aula para tirar dúvidas
* Aula para aprender como prosseguir no treinamento 
* Aula para aprender como fazer uma Issue para tirar duvidas de codigo e resumo de aulas e aplicações do treinamento 
* E dicas para ter o Feedback em caso de processo seletivo

**Comment by Roger-Melo** [comment]
Boa @CarlosHenrique2 , rumo à fluência! 🔥
