### ISSUE TITLE
Aplicação: WeatherApp

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3662]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Kmkery/WeatherApp.git

### Maiores dificuldades durante a implementação

Com relação ao código JS, acredito que desta vez não tive maiores dificuldades dentro do que eu tinha em mente a fazer, mas ainda me enrolo um pouco ao nomear funções e constantes de forma a deixar bem claro o que cada uma faz.
A dificuldade maior foi mais com a parte CSS, no que diz respeito a ajustes de alinhamento.

### Menores dificuldades durante a implementação

Fazer as requests e manipular os dados obtidos.

**Comment by Roger-Melo** [comment]
Olá @Kmkery.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Kmkery!

Vou deixar a análise de sua Weather App [aqui](https://drive.google.com/file/d/1x7HwvZgJ9ILj5dY4P11Nr6hitCY__cCh/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by Roger-Melo** [comment]
Legal @Kmkery! 

Fiz algumas considerações adicionais [neste vídeo](https://drive.google.com/file/d/1AbY-0gmC-bo46FRkgQ7lwfvM51nncT8y/view?usp=sharing). 

Desculpe por responder por vídeo ao invés de texto, é que estou com um pouquinho de tendinite no antebraço direito, então quando respondo em vídeo, sinto que digito menos =)

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)
