### ISSUE TITLE
Resumo da aula setInterval() e animação da pontuação - aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#3663]
Pra que serve o método `setInterval()` e como ele é utilizado ?
R: Ele executa uma função repetidas vezes, de acordo com o intervalo de tempo que passarmos como parâmetro.

Como parar o método `setInterval()` ?
R: Utilizando o método `clearInterval(ID SET-INTERVAL)`

O que é esse tal de `ID SET-INTERVAL` ?
R: Quando o método `setInterval()` é criado, ele também cria um ID único pra esse método, podendo ser manipulado para outros fins.

Diferença entre `setInverval()` e `setTimeout()` ?
R: Interval executa repetidas vezes, com intervalo de tempo. Timeout executa apenas uma vez, após o tempo passado como parâmetro.

```js
// Exemplo do uso setInverval() e clearInterval()

let counter = 0

const timer = setInterval(() => {
  console.log(counter)
  counter++

  if (counter === 3) {
    console.log('TEMPO ESGOTADO!')
    clearInterval(timer)
  }
}, 1000)

// "timer" vai ser executado até o "counter" ser igual a 3. Quando "counter" for igual a 3, o método clearInterval(timer) vai ser executado e parar a constante "timer".
```

**Comment by Roger-Melo** [comment]
Boa @rafaelpradoj, rumo à fluência! 🔥
