### ISSUE TITLE
Aplicação: [WeatherApp]

### ISSUE THREAD

**Issue by MaxOliverrr** [roger-melo-treinamentos/curso-de-js-roger-melo#3668]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/MaxOliverrr/weather-app

### Maiores dificuldades durante a implementação

Nomear variáveis e funções, renomeei algumas vezes até a versão final e refatorar o código para ficar da mais legível e conciso. 

### Menores dificuldades durante a implementação

Consegui fazer o código funcionar sem grandes dificuldades.

**Comment by Roger-Melo** [comment]
Olá @MaxOliverrr.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @MaxOliverrr!

Vou deixar a análise de sua Weather App [aqui](https://drive.google.com/file/d/1yy3fOXpO4BnNU7bLK1DJVvDuwqMgWHCH/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by MaxOliverrr** [comment]
Obrigado Roger! boa análise, esclareceu bastante coisa.

**Comment by Roger-Melo** [comment]
Show Max. No que precisar, é só abrir uma nova issue =)
