### ISSUE TITLE
Resumo da Aula Modificando estilos css (inline) da etapa 05

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3673]
<h1 align="center">Modificando estilos css (inline)</h1>

Como vimos no resumo anterior, o setAttribute, pode criar uma propriedade style com um determinado valor, porém caso queira adicionar um outro estilo css o novo vai sobrescrever o antigo, então ao invés de utilizar o setAttribute vamos utilizar o objeto style que terá todas as chaves com as propriedade css podendo assim atribuir propriedades diretamente a ela.

```html
<body>
  <h1>Texto qualquer</h1>
</body>
```

```js
const h1 = document.querySelector('div')

h1.style.color = 'tomato'

console.log(h1) // <h1 style="color: 'tomato';>Texto qualquer</h1>
```

Observação se você usar o getSelectorAll lembre-se de iterar pra fazer a mudança em todos senão retornará undefined.
Para excluir um atributo do estilo basta seta-lo como ''
```js
h1.style.color = ''
console.log(h1)// <h1>Texto qualquer</h1>
```

**Comment by Roger-Melo** [comment]
Boa @Beninigmal, rumo à fluência! 🔥
