### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3676]
**Conversão de tipos**
```js
let score = '100'
console.log(score + 1) //O resultado é 1001
/*Isso ocorre porque "score" armazena uma string, assim ele executa uma concatenação e não uma adição de valores*/
```
Para que possamos ter uma adição ao invés de uma concatenação, teremos que converter a variável ```score``` para Number. 
Para isso usamos a expressão ```Number()``` como no exemplo a seguir:
```js
score = Number(score)
console.log(score + 1) //O resultado agora é 101
console.log(typeof score) //O resulta é Number
```
```typeof``` pode ser usado para verificar o tipo da variável, contudo, nem sempre ele será a melhor escolha (será visto mais a frente)

**Conversões variadas**
```js 
/*String para Number*/
const crazyConversion = Number('Maçã')
console.log(crazyConversion) //O resultado é um NaN (não é um número)

/*Number para String*/
const convertedNumber = String(97)
console.log(convertedNumber, typeof convertedNumber) //O resultado é 97, mas é um tipo string.

/*Number para Boolean*/
const booleanConversion = Boolean(10)
console.log(booleanConversion, typeof booleanConversion) //O resultado é true e o tipo é boolean.
```
Mas daí a pergunta, por que 10 convertido para Boolean é true?
É porque em JavaScript temos os **Valores falsy**, que são:
- false
- 0
- "", '', ``
- null
- undefined
- NaN

Assim, todos os outros que não são **Valores falsy** são **Valores truthy**.

**Comment by Roger-Melo** [comment]
Boa @andersonpereiragithub, rumo à fluência! 🔥
