### ISSUE TITLE
Resumo da Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by ricardoribeir** [roger-melo-treinamentos/curso-de-js-roger-melo#368]
template strings // declarar mais de uma variaveis em uma unica string (' ')
" `Fulana tem + ${idade} + anos` " // envolvida com crases (` `)

templates strings ou templates literals

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardoribeir! Rumo à fluência! 👊🏻
