### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM da etapa 05

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3686]
<h1 align="center">Criando e removendo elementos do DOM</h1>

## Removendo elementos da tela
Para remover um elemento da tela, após ser feito a query para obter a referência do elemento pode ser encadeado a essa referência o método remove:

```js
const ul = documento.querySelector('ul')
ul.remove()
```

Então sabendo disso, se por exemplo for obtido um nodelist de __*lis*__ e dentro de cada função do callback do evento de click nós adicionarmos o __*remove()*__ o item será removido da tela. Obviamente após um refresh esse item retornará a tela, porque eles não estão sendo criados dinamicamente esses dados vindo de um array, poderemos além de remover da tela, usar um método __*pop*__ ou __*shift*__ para remover esse item do array e usando alguns modos de persistência para assegurar que mesmo o um refresh da página esse dado não volte.

## Criando elementos da tela

Para criar um novo elemento podemos utilizar o método __*createElement('elemento')*__  e atribuindo a uma constante e para inserir podemos usar o __*textContent*__ recebendo o novo valor e fazendo um __*append()*__ ao pai daquele elemento passando como argumento a constante que criamos com o elemento:

```js
const ul = document.querySelector('ul')
const btn = document.querySelecto('button')

btn.addEventListener('click', (e) => {
  const li = document.createElement('li')
  li.textContent = 'nome do item'
  ul.append(li)
})

```
O código acima fará com que através de um evento de click uma nova __*li*__ seja inserida ao final de uma __*ul*__

Além do __*append*__ podemos usar o __*prepend*__ que funciona muito semelhante, porém o __*li*__ será inserido no inicio da *__ul__*

**Comment by Roger-Melo** [comment]
Boa @Beninigmal, rumo à fluência! 🔥
