### ISSUE TITLE
Resumo da Aula While Loop (Aula 01-04) da etapa 02

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3688]
## O que é o laço ***while***?

É um laço condicionado no qual não conhecemos a quantidade execuções.

## Qual é a estrutura do laço ***while***?

```javascript
let i = 0
while(i < 5) {
   console.log(i)
   i++
}
```

## Por que devemos incluir o incremento (ou decremento) dentro do laço ***while***?

Para evitar o chamado ***loop*** infinito.

**Comment by Roger-Melo** [comment]
Boa @ananopaisdojavascript, rumo à fluência! 🔥
