### ISSUE TITLE
Resumo da Aula Booleans e comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#369]
Boolean representa dois valores em JavaScript: true e false. Se exibirmos no console estes valores, e logo em seguida passarmos os mesmos valores, porém como strings, ou seja, entre aspas, veremos que o navegador pega os argumentos passados como strings e os coloca entre aspas, para que possamos diferenciar o tipo de dado que foi retornado. Enquanto os dois primeiros são retornados como true e false, ou seja, booleans, os dois últimos são retornados como "true" e "false", ou seja, strings.

```jsx
console.log(true, false, 'true', 'false'); // true, false, "true", "false"
```

Quando iremos utilizar booleans? Quando precisarmos verificar alguma condição no código. Haverá momentos em que teremos que verificar se um trecho de código é verdadeiro ou false. Existem alguns métodos que nos retornam um boolean como resultado. Vamos ver isso na prática, declarando uma const email que recebe a string 'jakeperalta@ricardodantas.dev'. Agora vamos declarar uma const includes que recebe a const email com o método includes(), que receberá como argumento '@'. O que esse método includes() faz? Ele verifica se a string passada como argumento existe na string a qual o método se referencia. E retorna true caso encontre, ou false caso não encontre.

```jsx
const email = 'jakeperalta@ricardodantas.dev';

const includes = email.includes('@');

console.log(includes); // true
```

E como uma string é uma sequencia de caracteres, podemos passar palavras ao invés de apenas um caractere como argumento de includes().
Este mesmo método pode ser utilizado também em arrays. Ele verifica se a string passada como argumento existe como um elemento do array, ou seja, ele tenta fazer um match entre o argumento passado com algum elemento do array. Então vamos declarar uma const names que receberá o array ['jake', 'amy', 'ricardo'], e vamos declarar uma outra const arrayIncludes que receberá a const names com o método includes(), que receberá como argumento 'ricardo'. Nesse caso, como 'ricardo' é um elemento do array, será retornado true. Caso não houvesse um elemento com o argumento passado, seria retornado false.

```jsx
const names = ['jake', 'amy', 'ricardo'];

const arrayIncludes = names.includes('ricardo');

console.log(arrayIncludes); // true
```

Agora vamos ver alguns operadores de comparação. Comparações irão retornar booleans como resultado. Então vamos criar uma const age que recebe o valor 37. E em seguida, vamos utilizar o console.log() com a comparação age == 37. Os dois sinais de igual (==) representam igualdade, ou seja, estamos comparando se o valor de age é igual ao number 37. E logo abaixo, vamos utilizar novamente console.log() mas dessa vez passando como argumento number == 39. Agora vamos ver o que é retornado no console. Na primeira comparação é retornado true, pois age tem como valor 37, e na segunda é retornado false, pois 39 não é igual a 37. Agora em mais um console.log(), vamos passar age != 39. O sinal != significa que o primeiro número não é igual ao segundo. Essa comparação nos retorna true. Agora se passarmos como argumento de console.log() age != 37, recebemos false como retorno, pois age na verdade é igual a 37.
Temos ainda os operadores > (maior que), < (menor que). ≥ (maior ou igual que), ≤ (menor ou igual que)

```jsx
const age = 37;

console.log(age == 37); // true
console.log(age == 39); // false
console.log(age != 39); // true
console.log(age != 37); // false
console.log(age > 37);  // false
console.log(age < 39);  // true
console.log(age <= 37); // true
console.log(age >= 37); // true
```

Agora vamos ver comparações de strings. Vamos declarar uma const que recebe o valor 'ricardo'. E vamos passar como argumento do console.log(name == 'ricardo'), ou seja, estamos comparando se a const name é igual a string 'ricardo' e isso nos retornará true. Se compararmos name == 'Ricardo', onde temos o primeiro caractere maiúsculo, o retorno será false, pois para o JavaScript 'ricardo' e 'Ricardo' são strings diferentes. E se utilizarmos os operadores de comparação > e <? Como o JavaScript trata isso? O que é comparado é onde se encontra a letra no alfabeto. As últimas letras do alfabeto são maiores que as primeiras. E o JavaScript também considera que as letras minúsculas tem valor maior que as letras maiúsculas. Então se compararmos name < 'julia', recebemos um true como retorno, pois o 'r' de 'ricardo' é maior que 'j' de 'julia'. E se compararmos 'ricardo' < 'Ricardo' também recebemos true como retorno pois 'r' de 'ricardo' é maior do que 'R' de "Ricardo'.

```jsx
const name = 'ricardo';

console.log(name == 'ricardo');  // true
console.log(name == 'Ricardo');  // false
console.log(name > 'julia'); // true
console.log(name > 'Ricardo');   // true
```

Todos estes tipos de comparações serão úteis todas as vezes que precisarmos verificar se certas condições são true ou false, para que com essa informação nós possamos executar algum código. Por exemplo, o usuário está logado? Se isso for true, executamos um código que exibe um dashboard por exemplo. Se for false, não exibimos.
Até agora vimos as comparações utilizando sinais duplos: 'igual a' (==), e o 'não é igual a' ou 'diferente de' (!=). Mas estes operadores com sinais duplos testam apenas os valores que estão sendo comparados, e não os tipos deles. Esta comparação de tipos veremos em um próximo resumo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas. Rumo à fluência! 👊🏻
