### ISSUE TITLE
Resumo da Aula sobre a Tag Script - Aula 01-04 da etapa 01

### ISSUE THREAD

**Issue by felipegueller** [roger-melo-treinamentos/curso-de-js-roger-melo#3694]
## No Head 👨:

> A tag `<script>` pode ser inserida no *HEAD* da sua aplicação, com código inline ou chamando um arquivo JS externo por meio do atributo `src="path"`. Porém está pratica pode gerar erros se não for executada de forma correta e consciente, pois o Javascript pode ser totalmente carregado antes da DOM Tree e com isso ele não será executado de forma correta, gerando erros.

```HTML
<head>
     <script>
          const name = 'Felipe'
     <script>
     <script src="./app.js" defer></script>
</head>
``` 

## No Body 🤺 : 

> No *BODY*, a tag `<script>` deve ser sempre inserida ao fim do documento, para que o código seja lido e executado após o carregamento total da DOM Tree.

```HTML
<body>
    <h1>Learning Javascript!</h1>
    <script>
        const name = 'Felipe'
     <script>
     <script src="./app.js" defer></script>
</body>
```

## `<script>`: O elemento script `HTMLScriptElement` :scroll:

> O  elemento HTML `<script>` é usado para incorporar códigos executáveis ou dados a sua aplicação Web, geralmente Javascript ou JSON. 

### Atributo `defer` 🕐:

> É um atributo boleano que indica ao navegador que o script deve ser executado após o documento ser analisado, mas antes de ser disparado o evento `DOMContentLoaded`.

**Comment by Roger-Melo** [comment]
Boa @felipegueller, rumo à fluência! 🔥
