### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03 da etapa 03

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3698]
**Function Declaration, Function Expression e Hoisting**

**Function Declaration** é quando usamos a palavra reservada ```function``` antes do nome da função.
```js
function nomeFuncao (){
 código a ser executado
}

nomeFuncao() // Invocação
```
Function Expression por sua vez é uma função atribuída a uma variável e a palavra reservada ```function``` vem depois do sinal de atribuição ( = ).
```js
const nomeVariavelQueRecebeAFuncao = function () {
 código a ser excutado
}

nomeVariavelQueRecebeAFuncao() //Invocação
```
Ambas podem ser invocadas da mesma forma com seus respectivos nomes com ( ) parênteses na frente. 

Mas ATENÇÃO, a diferença entre as duas funções se encontra no **HOISTING**.
**Hoisting** nada mais é que, içar, levar algo que está embaixo para o topo do código. 
Mas isso só ocorre na **Function Declaration**.

Ou seja, se você invocar uma **Function Declaration** antes dela ser criada, ela vai rodar, porque ela será içada para o topo.
Ao passo que, a **Function Expression** isso não ocorre, o que irá gerar um erro na execução.

**Comment by Roger-Melo** [comment]
Boa @andersonpereiragithub, rumo à fluência! 🔥
