### ISSUE TITLE
Api Weather - Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by carlosweb** [roger-melo-treinamentos/curso-de-js-roger-melo#37]
Olá professor estou tendo problema com o Access-'Control-Allow-Origin' na execução do Projeto Weather.
Dei uma pesquisada sobre e tem algumas soluções com express.
Pode me ajudar com outras soluções?

**Comment by Roger-Melo** [comment]
Oi Carlos!

Chegou a tentar remover o app criado no site da Accuweather e criar um novo app para que uma nova chave seja gerada?

Tente fazer isso e usar a nova chave.

Se não funcionar, printe a tela e anexe em um novo comentário da issue, para eu entender o que o erro está dizendo.

Para anexar um arquivo, e só clicar na parte inferior de seu novo comentário, onde está escrito "Attach files by dragging & dropping, selecting or pasting them."

Fico no aguardo =)

@carlosweb

**Comment by carlosweb** [comment]
Bom dia professor!
Crie outro App continua dando mesma mensagem.
![page-1](https://user-images.githubusercontent.com/4267779/93405535-a57b6680-f863-11ea-86ac-da8c5b0b7e39.png)
![vscode](https://user-images.githubusercontent.com/4267779/93405546-a9a78400-f863-11ea-97cf-a0b0997d4ee5.png)

**Comment by Roger-Melo** [comment]
Oi Carlos.

Pode subir seu projeto num repositório no github e me enviar o link para eu testar aqui?

@carlosweb

**Comment by carlosweb** [comment]
Sim professor, segue o link https://github.com/carlosweb/curso_Fluencia_JavaScript/tree/master/appWeatherApp

**Comment by Roger-Melo** [comment]
Oi Carlos. 

Baixei seus arquivos e também testei os meus, o mesmo erro aconteceu.

Acho que mudaram alguma coisa no servidor da API. Enviei um email para eles. Assim que responderem, te chamo aqui para falar com mais detalhes o que está acontecendo. A issue ficará aberta.

Enquanto isso, parta para as próximas aulas =D

@carlosweb

**Comment by Roger-Melo** [comment]
Oi Carlos.

Observe que no endpoint abaixo,

```js
const getCityUrl = cityName => 
`http://dataservice.accuweather.com/locations/v1/cities/search?apiKey=${apiKey}&q=${cityName}`
```

o query parameter `apiKey` está em camel case. Experimente deixar o `K` minúsculo e executar o código novamente.

Ficaria assim:

```js
const getCityUrl = cityName => 
`http://dataservice.accuweather.com/locations/v1/cities/search?apikey=${apiKey}&q=${cityName}`
```

Teste e me diga se funcionou =D

@carlosweb

**Comment by carlosweb** [comment]
Olá professor, bom dia!
Funcionou sim, rsrs não me atentei a esse detalhe.
Obrigado Roger!

**Comment by Roger-Melo** [comment]
Legal Carlos!

Já que o problema foi resolvido, por agora vou fechar a issue. Mas se surgir alguma nova dúvida é só abrir uma nova issue e perguntar =D
