### ISSUE TITLE
Etapa 3, nome do vídeo: O método forEach e callbacks - Aula 02-04

### ISSUE THREAD

**Issue by EricSampaio-Js** [roger-melo-treinamentos/curso-de-js-roger-melo#370]
Em um callback eu envio uma função como argumento e chamo ela depois. Ate aii tudo certo.

A minha dúvida é: Onde fica o ambiente de execução da função (callback)?, na criação da função quando ela é passada, ou na invocação desse callback, dentro da função que recebe esse argumento?

```js
const myfunc = callback =>{ // momento em que o parâmetro callback recebe a função;
    const value = 77
    callback(value); // invocando a função;
}

myFunc(number =>{
    console.log(number)
}) // enviando a função como argumento;

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Eric.

Depende do que você quer dizer com ambiente de execução.

Em JavaScript, funções são valores e, por tanto, podem ser atribuídas a um parâmetro.

Isso significa que o parâmetro `callback` armazenou a referência da função em memória. Tanto é que se dentro da `myFunc` você exibir `callback` (sem invocar) no console, verá que ele armazena a referência da função:

```javascript
const myFunc = callback => {
  const value = 77

  console.log(callback) // number => { console.log(number) }
  callback(value)
}

myFunc(number => {
  console.log(number)
})
```

Como a função `number => { console.log(number) }` que foi inserida como argumento é uma função anônima que apenas foi recebida no parâmetro `callback`, assim que `myFunc` termina de ser executada, o que está dentro dela é removido da memória (pois não será mais usado).

Para não perder a referência da função `number => { console.log(number) }`, você pode armazená-la em uma `const` e apenas referenciar a const como argumento da invocação de `myFunc`:

```javascript
const myFunc = callback => {
  const value = 77
  callback(value)
}

const logNumber = number => {
  console.log(number)
}

myFunc(logNumber) // referência da função inserida como argumento
```

Assim você guarda a referência da função e pode reutilizá-la em outros pontos da sua aplicação.

Essa era a dúvida?

---

Off-topic: observe também que, em seu exemplo, apenas a invocação da `myFunc` está em camelCase. Ou seja, `myFunc` não foi declarada e quando é invocada, lança um erro no console. Afinal, a declaração de `myfunc` está com o `f` minúsculo.

@EricSampaio-Js

**Comment by EricSampaio-Js** [comment]
Sim... Entendi.. Obrigado pela atenção.. :D

**Comment by Roger-Melo** [comment]
Legal @EricSampaio-Js. Vou fechar a issue mas quando surgirem dúvida, é só abrir uma nova =)
