### ISSUE TITLE
Resumo da Aula Arrays - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3701]
ARRAYS

`let heroes = ['Batman', 'Catwoman', 'Iron Man']`
Esta ☝ é a sintaxe de um array com 3 elementos. O array é representado pelos colchetes e cada um deles é separado por vírgula.

Um array aceita diversos tipos de dados.

Para acessar um elemento específico de um Array é suficiente utilizar da notação colchetes para tal: `heroes[2]`, neste caso, será retornado o valor `'Iron Man'`.
Desta forma, a partir disso, é possível fazer alterações no Array, como por exemplo: `heroes[2] = 'Spider-Man'` modificando o elemento de index 2 para a string ‘Spider-Man’.

MÉTODOS ARRAY

**Array.join( )** -> Retorna todos os elementos do Array concatenados e separados por vírgula. Ele aceita um argumento que serve como separador. O retorno é uma string.
Sintaxe `array.join([separador = ‘,’])`
```javascript
const elements = ['Fire', 'Air', 'Water'];

console.log(elements.join());
// expected output: "Fire,Air,Water"

console.log(elements.join(''));
// expected output: "FireAirWater"

console.log(elements.join('-'));
// expected output: "Fire-Air-Water"
```

**Array.indexOf( )** -> Retorna o primeiro índice em que o elemento pode ser encontrado no array. Retorna -1 caso o mesmo não esteja presente.
Sintaxe `array.indexOf(elementoDePesquisa, [pontoInicial = 0])`
```javascript
var array = [2, 5, 9];
array.indexOf(2);     // 0
array.indexOf(7);     // -1
array.indexOf(9, 2);  // 2
array.indexOf(2, -1); // -1
array.indexOf(2, -3); // 0
```

**Array.concat( )** -> Retorna um novo array contendo todos os arrays ou valores passados como parâmetro.
Sintaxe `array.concat(valor1, valor2, …, valorN)`
```javascript
var alpha = ["a", "b", "c"];
var numeric = [1, 2, 3];

var alphaNumeric = alpha.concat(numeric);
// creates array ["a", "b", "c", 1, 2, 3]; alpha and numeric are unchanged
```

**Array.push( )** -> Adiciona um ou mais elementos ao final de um array e retorna o novo comprimento desse array. 
Sintaxe `array.push(elemento1, …, elementoN)`
```javascript
var numeros = [1, 2, 3];
numeros.push(4);

console.log(numeros); // [1, 2, 3, 4]

numeros.push(5, 6, 7);

console.log(numeros); // [1, 2, 3, 4, 5, 6, 7]
```

**Array.pop( )** -> Remove o último elemento de um array e retorna aquele elemento.
Sintaxe `array.pop()`
```javascript
var meuPeixe = ['acara-bandeira', 'palhaco', 'mandarim', 'esturjao'];

console.log(meuPeixe); // ['acara-bandeira', 'palhaco', 'mandarim', 'esturjao']

var meuPeixePop = meuPeixe.pop();

console.log(meuPeixe); // ['acara-bandeira', 'palhaco', 'mandarim' ]

console.log(meuPeixePop); // 'esturjao'
```

**Comment by Roger-Melo** [comment]
Excelente @lucian-bonifacio, rumo à fluência! 🎯
