### ISSUE TITLE
Dúvida no exercício 32

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#3702]
### Etapa da aula

12

### Nome da aula

Correção dos exercícios da aula 06 da etapa 11 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1381625

### Descreva a dúvida

const form = document.querySelector('form')

```js
form.addEventListener('submit', async event => {
  event.preventDefault()

  const inputValue = event.target.search.value
  const APIkey = 'tSlaMQB4BJPL6g84dacHm74VNtnNW3mQ'
  const url = `https://api.giphy.com/v1/gifs/search?api_key=${APIkey}&limit=1&q=${inputValue}`

  try {
    const response = await fetch(url)

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }

    const GIFdata = await response.json()
    console.log(GIFdata)
  } catch (error) {
    alert(`Erro: ${error.message}`)
  }
})

```
```html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="./style.css">
  <title>Testando a API do GIPHY</title>
</head>

<body>
  <h1>Testando a API do GIPHY</h1>

  <main>
    <form>
      <input name="search" type="search" autofocus />
      <button>Buscar</button>
    </form>

    <div class="out"></div>
  </main>

  <script src="./app.js"></script>
</body>

</html>
```
Quando fui testar no console, nessa linha apaguei o underline
```js
...
const url = `https://api.giphy.com/v1/gifs/search?apikey=${APIkey}&limit=1&q=${inputValue}`
...

```
Coloquei um valor qualquer e no foi exibido o array:

![image](https://user-images.githubusercontent.com/92958989/169892136-0eb9edef-b526-4f38-80fa-b4dc168fdcec.png)

Escrevi e reescrevi o código e continua assim, é bom que pratica mais kkkk
Tentei descobrir o que pode ser mas não consegui.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz. Dá uma olhada [aqui](https://drive.google.com/file/d/1o0U7vmCq145vBJH2cdsGAv3qVaKluNyK/view?usp=sharing) =)

**Comment by Jansen-Muniz** [comment]
Corrigindo: Coloquei um valor qualquer, no console foi exibido o array -> Aqui tudo bem.

Desculpa, Roger não expliquei direito. 
Minha dúvida é quando o endpoint está assim:
```js
...
const url = `https://api.giphy.com/v1/gifs/search?apikey=${APIkey}&limit=1&q=${inputValue}`
...
```
Quando testa o `catch`, que tira o underline, no meu não está exbindo o erro, como na aula:

![image](https://user-images.githubusercontent.com/92958989/169909604-e85bf5cb-299f-4404-b65b-6c477ca63297.png)

**Comment by Roger-Melo** [comment]
Ahh sim, agora saquei. Dá uma olhada [aqui](https://drive.google.com/file/d/1TdGXeYgZa9WiVyTplJBqAGZUKasfxo94/view?usp=sharing) =)

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Entendido, Roger =).
Tenho outra dúvida. Nesse trecho aqui, não entendi direito.
```js
if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
}
```
Porque tem que ter o `not`?

Gostei desse formato que tu responde as dúvidas =)
Fica melhor o entendimento, acho melhor por vídeo.

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz!

Dá uma olhada [aqui](https://drive.google.com/file/d/126eP_zhf1-Gv7vmEeJhNUkUBn3d2lhOX/view?usp=sharing) =)

Vou deixar abaixo os links que mencionei no vídeo:

- [O operador lógico not (!) - Aula 03-02](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/781550)
- [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)
- [Logical NOT (!)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_NOT)

**Comment by Jansen-Muniz** [comment]
Roger, sobre o operador `not`, sei que ele inverte um valor `true `para `false`, por exemplo.
Na verdade minha dúvida é qual `boolean`, o `response.ok` neste trecho do `if` retorna.
Se o `response.ok` é `false` e é invertido para `true`, ou se é `true` e  é  invertido para `false`.

**Comment by Roger-Melo** [comment]
> ## Na verdade minha dúvida é qual `boolean`, o `response.ok` neste trecho do `if` retorna

`response.ok` contém um boolean que indica se a resposta do request foi bem sucedida (status HTTP de 200 a 299) ou não.

Se foi bem sucedida, `response.ok` resulta em `true`. Caso contrário, resulta em `false`.

Se acima do if, vc inserir um console.log() que recebe `response.ok` e fizer a requisição, vc irá visualizar o boolean =)

---

> ## Se o `response.ok` é `false` e é invertido para `true`, ou se é `true` e  é  invertido para `false`

Vc acabou de descrever o comportamento do not (`!`). Independente do boolean em que `response.ok` resulte, o not irá inverter esse boolean.

Ficou mais claro?

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Entendi agora. Essa rendeu kkkkk
Valeu mano Roger. 
Antes da aplicação da etapa 12, vou refazer uns exercícios. Quero fazer o code review, se possível, vai me ajudar bastante =)

**Comment by Roger-Melo** [comment]
Boa! Siga o recomendado na aula inaugural: [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1985) antes de cada aplicação =)

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Certo, mister Roger =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
