### ISSUE TITLE
Chaves em cores diferentes

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#3704]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1324088

### Descreva a dúvida

Roger, boa tarde!

Recentemente estava fazendo a segunda questão do exercício 30 e percebi que as cores das chaves e colchetes mudaram quando fui criar uma nova função para retornar a mensagem e valores que o exercício pediu. O que me deixou em dúvida foi o seguinte: Por que essas chaves estão em cores diferentes uma da outra? Alguma das duas está fazendo algo que a outra não está e por isso a mudança de cor?

![Duvida cor chaves](https://user-images.githubusercontent.com/82729897/170085460-0521c23a-4c4b-400e-8056-e2a656e3b839.png)

Eu tenho a suposição que possa ser por causa de uma extensão que tenho adicionada, mas se esse for o caso, por que a extensão diferenciou as cores de uma da outra nesse momento específico?

Aguardo resposta, atenciosamente =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MivlaM. Dá uma olhada [aqui](https://drive.google.com/file/d/1BwwgnyJIOgsXcEHCyh54zjUgYQ0l5s72/view?usp=sharing) =)

**Comment by MivlaM** [comment]
Entendi. Peço desculpas por não ter colocado o código escrito, por ser algo mais visual, pensei que apenas o print fosse necessário.

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
