### ISSUE TITLE
Herança com factory functions

### ISSUE THREAD

**Issue by BrunodevOliveira** [roger-melo-treinamentos/curso-de-js-roger-melo#3714]
### Etapa da aula

14

### Nome da aula

Factory functions e composição de objetos - Aula 03-09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1926080

### Descreva a dúvida

Opa, Roger!
fiquei com uma dúvida sobre herança entre objetos criados com uma factory function.
No exemplo abaixo crio dois objetos com e verifico no console.log se os dois compartilham a mesma função. Nesse caso tenho ``false`` como retorno, isso significa que para cada instância criada será armazenado em memória um método incrementCounter() diferente? 
Nesse caso, não seria melhor utilizar o prototype para que essas instâncias compartilhassem esse métodos?

``` js
const createUser = (name, email) => {
  let counter = 0 

  return {
    name,
    email,
    incrementCounter: () => ++counter
  }
}
const user2 = createUser('Bruno', 'bruno@gmail.com')
const user3 = createUser('Bruno 2', 'bruno2@gmail.com')

console.log(user3.incrementCounter() === user2.incrementCounter()) //false
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BrunodevOliveira!

Na aula 02-03 da etapa 15 vc verá uma forma de fazer herança em factory function sem que haja essa duplicação de método entre objetos. 

Mas se depois de ver essa aula ainda restarem dúvidas, pode postar aqui que te ajudo, combinado? =)

**Comment by BrunodevOliveira** [comment]
Beleza, Roger!

**Comment by Roger-Melo** [comment]
Vou fechar essa issue mas no que precisar, é só abrir uma nova =)
