### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3719]
## Null e Undefined 
 

Esses dois tipos de dados são similares, eles representam a falta de valor. A diferença é que o valor null é atribuído pelo desenvolvedor, enquanto undefined é colocado automaticamente pelo javascript 

 

Undefined 

```js
Let emptiness 
Conslole.log(emptiness, emptiness + 3, `O valor é ${emptiness}` 
undefined NaN ' o valor é undefined' 
```
 

Como não atribuímos um valor à variável emptiness, ao tentarmos usá-la, o javascript coloca automaticamente o valor undefined, foi o que aconteceu com o resultado da primeira variável. Na segunda declaração, ao tentar usar undefined com uma expressão numérica, é atribuído um NaN, não é um número. Já a declaração com templete string também foi atribuída undefined, e a variável foi transformada numa string.  

**Null** 

É utilizado quando queremos de forma intencional indicar que uma variável não tem valor. 

```js
let emptiness = null 
console.log(emptiness, emptiness + 3, ` o valor é ${emptiness}`) 
null 3 ' o valor é null' 
```

A primeira variável tem o valor null conforme declarado. A segunda tem o valor 3, pois em cálculos matemáticos null assume o valor 0. A terceira varialvel também foi transformada em string.

**Comment by Roger-Melo** [comment]
Excelente @MarioFilho1, rumo à fluência! 🎯
