### ISSUE TITLE
Resumo da Aula 01-01 Objetivo CJRM da etapa 01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#372]
Durante muito tempo, sempre tive uma certa fixação por linguagem de programação; Interesse bem amador, daquele de comprar um livro só porque na capa estava escrito 'programação'; Depois com o envolvimento com eletronica, programei alguns  chips e descobri, de forma bem rasa, linguagens como o C e ASSEMBLY; Então este ano conheci a linguagem JAVA e em seguida veio a 'Semana Java Script'.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @marcosyoggy! Rumo à fluência! 🔥
