### ISSUE TITLE
Resumo da Aula Expressões regulares da etapa 06

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3724]
<h1 align="center">Expressões regulares</h1>

Expressões regulares ou **_REGEX_** são expressões usadas para garantir o match (ou não) de expressões, é difícil de entender assim, mas vamos lá. Para nível de aprendizado podemos simular as expressões no webapp [regex101.com](regex101.com), a primeira coisa que devemos fazer é selecionar no sabor ou **flavor** a esquerda o **ECMAScript** que é o **Javascript** 👇 

![image](https://user-images.githubusercontent.com/53193423/170151267-3caf84ad-8084-45b3-a79e-b95d0b1a53ea.png)

No primeiro campo escrito **REGULAR EXPRESSION** será o campo da expressão que iremos fazer e no **test string** a saída de testes. bom, de inicio devemos saber que uma expressão sempre vai começar e terminar com **/**, e isso quer dizer que se por exemplo eu colocar ```/ Lucas /``` e no campo de teste ```asalçkjdaLucaslkajsd``` um match será feito por que foi encontrado a expressão Lucas entre aquele emaranhado de letras.

![image](https://user-images.githubusercontent.com/53193423/170151581-b495c798-cbfb-4d6c-b584-148f08894f65.png)

Porém se caso quisermos encontrar Lucas de forma isolada, sem estar emaranhado com outras palavras, como podemos fazer? Bom usaremos uma combinações de sinais ao redor da expressão para isolar ela, ou seja, o match só vai acontecer se Lucas for o começo da expressão do input e o final da expressão desse mesmo input e essa combinação é ```\ ^Lucas$ \```, então se Houver ```Lucas Lima``` a expressão não dará **_match_** por que a expressão teria que terminar no Lucas.

Caso quisermos uma expressão mais flexível que pegue todos os caracteres de **_A a Z,_** podemos usar o **_character set_**, que é uma lista que dá match com qualquer caractere  que for inserido dentro dele. ```/ ^[a-z]$ / ``` essa **_regex_** vai dar match com qualquer letra minúscula entre **_a e z_**, porém apenas uma única letra, e caso também queiramos incluir as letras maiúsculas vamos incluir nessa mesma **_regex_** ```/ ^[a-zA-Z]$ /``` assim o range aumentou ainda mais.
Caso a **_regex_** que queremos seja de no mínimo 6 e no máximo 10 caracteres, ao lado do colchetes adicionaremos chaves fazendo essa indicação ```/ ^[a-zA-Z]{6, 10}$ /```.
Se quisermos adicionar números podemos adicionar os números  ```/ ^[a-zA-Z0-9]{6, 10}$ /```
Uma outra coisa que podemos fazer é checar se antes de ter alguma restrição de quantidade de valor, qualquer caractere possa ser aceito, e para isso adicionaremos o . antes dessa restrição para formar o match que precisamos. ```/ ^.{6,10}$ /``` 

## Testando padrões de regex

Agora no nosso código JS podemos fazer a expressão e testar e o que iremos fazer aqui é o nome do usuário terá apenas letras minúsculas e no mínimo 6 caracteres, e para fazer isso podemos fazer: 

```js 
const username = 'Lucas'
const pattern = /^[a-z]{6,}$/
const result = pattern.test(username)

console.log(result) // false
```
No código acima, a expressão resultou em **_false_**, ou seja o valor do **username** não deu **_match_** com a especificação do **pattern**, isso por que existe uma letra maiúscula e apenas 5 caracteres,

Uma outra coisa importante é que além do método **_test()_**,  podemos usar o método **search()**, diferente do test, ele vai indicar o índice do primeiro caractere que deu **_match_**, se se não houver match o retorno será -1

```js
const username = 'lucaslima'
const pattern = /^[a-z]{6,}$/
const result = pattern.search(username)

console.log(result) // 0, que é a posição do 'l' que é a primeira letra que deu match do username

```

**Comment by Roger-Melo** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯
