### ISSUE TITLE
Resumo da aplicação da etapa 09

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#3726]
### **Marcação HTML**

```html
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel="stylesheet" href="./style.css">
  <title>To-do List</title>
</head>
<body>
  <div class="container">

    <header class="text-center text-light my-4">
      <h1 class="mb-4">To-do List</h1>
      <form class="form-search">
        <input class="form-control m-auto" type="text" name="search" placeholder="Buscar to-do" autofocus />
      </form>
    </header>

    <ul class="todos-container list-group mx-auto text-light">
      <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="Assistir Breaking Bad">
        <span>Assistir Breaking Bad</span>
        <i class="far fa-trash-alt" data-trash="Assistir Breaking Bad"></i>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="Planejar aulas">
        <span>Planejar aulas</span>
        <i class="far fa-trash-alt" data-trash="Planejar aulas"></i>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="Fazer exercícios físicos">
        <span>Fazer exercícios físicos</span>
        <i class="far fa-trash-alt" data-trash="Fazer exercícios físicos"></i>
      </li>
    </ul>

    <form class="form-add-todo text-center my-4">
      <label class="text-light">Adicionar to-do</label>
      <input class="form-control m-auto" type="text" name="add" />
    </form>
  </div>

  <script src="./app.js"></script>
</body>
</html>
```

---

### 01 - Adicionando Todos

Para começar, podemos iniciar a aplicação obtendo e armazenando as referências do formulário e da **ul** que conterá as **lista** com cada **Todo**, então para isso podemos olhar no documento **HTML** e verificar o **atributo** para servir de referência. 

Após isso, podemos adicionar um **evento de escuta** no **formulário** e como primeiro argumento, passaremos o **tipo de evento** que neste caso será **submit** e como segundo argumento, uma **função** com o parâmetro **event**, para que possamos trabalhar a partir dele. 

A primeira coisa a se fazer dentro da função é **impedir o comportamento padrão do navegador**, ou seja, quando enviarmos o formulário, a página **não será recarregada**.

Agora para armazenar o **valor do input**, podemos utilizar uma const inputValue que vai receber o **event** que vai encadear o **target**, o **atributo do input** e depois o **atributo value**

Para prevenir que um Todo seja adicionado com o caractere de espaço uma ou múltiplas vezes, podemos encadear o **método trim().** O método **trim** irá remover quaisquer caractere de espaço duplicado.

E agora para impedirmos que um Todo seja adicionado **sem nenhum caractere**, utilizaremos uma **expressão de verificação**, passando uma **condição** coerente para isso e se a condição resultar em **true**, então encadearemos na ul a propriedade **innerHTML** que receberá uma **li** com o valor do input vale.

OBS: Como estamos usando o **bootstrap** que usa classes para a estilização, não podemos deixar de acrescenta-los na marcação.

```jsx
const formAddTodo = document.querySelector('.form-add-todo')
const todosContainer = document.querySelector('.todos-container')

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  if (inputValue.length) {
    todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
    </li>
  `
  }
})
```

---

### 02 - Removendo Todos

Para remover um item da lista de **Todos** quando houver um **click na lixeira**, podemos adicionar um **evento de escuta na ul** e através da **ul**, criar uma **condição** para que se o click acontecer em um elemento **filho da ul** que contenha a classe **delete**, que neste caso é o ícone da lixeira, a **respectiva li** **seja removida**. Ou seja, iremos aproveitar o **event delegation**. 

Para que possamos obter e armazenar a referência do elemento clicado, podemos usar o objeto event e através do objeto event, usaremos a propriedade target.

Além disso, para que possamos excluir a respectiva li que contem a lixeira que foi clicada, precisamos usar o método includes, que retorna um **Boolean**, indicando se a condição é **verdadeira** ou **falsa**. Como o **includes** é um método de **array**, precisamos invocar o método from da função construtora **Array** e como argumento do método **from**, passar a **condição** que checa se o elemento clicado contem a classe **delete.**

```jsx
todosContainer.addEventListener('click', event => {
	const clickedElement = event.target

	if (Array.from(clickedElement.classList).includes('delete')) {
    clickedElement.parentElement.remove()
  }
})
```

---

### 03 - Filtrando Todos

A feature que vamos implementar, vai fazer com que o **input de search** filtre e exiba somente os todos que derem **match** com o **valor passado no input de busca**. E para isso podemos adicionar um **evento de escuta no input**, do tipo **input**, ou seja, a cada vez que o input escutar uma alteração, ele vai executar a **função** que será passada como **segundo argumento** deste evento de escuta.

Esta função, precisará manipular classes **CSS** de acordo com uma condição que vai identificar se a string digitada no input de busca da match com o texto do Todo já adicionado, se der match, ele deve ser exibido na tela, enquanto os todos que não derem match devem ficar **invisíveis**.

Então para isso, dentro da função vamos armazenar o valor do input do qual está atrelado o evento de escuta através do objeto event da função, e podemos obter e armazenar o valor do input através do **event.target.value** e ainda encadearmos o método **trim** e o **toLowerCase** para que não haja espaços duplicados no começo ou no final de uma string e para que também não haja diferenças entre caracteres maiúsculos e minúsculos no input de busca. Para isso podemos armazenar a referência do input em uma const **inputValue**.

Agora, para que possamos obter as referências dos Todos, podemos utilizar a **const** que obtém e armazena a referência da **ul** na qual os **Todos** estão inseridos como **filho**, e então podemos encadear na **ul**, a propriedade **children** para obter as referências de todos os filhos da ul em uma **HTML Collection.**

Como o nosso próximo passo é filtrar as Todos que dão match com o input de busca, e consequentemente precisaremos usar o método **filter,** e como este método, é um método de array, precisaremos utilizar o método **from** da função construtora **Array**, para assim converter este **HTML Collection** em um **array**. 

****Agora sim, podemos encadear o método **filter**, e através da condição deste método, devemos obter as lis que derem match com o input de busca, e esta condição pode ser gerada através do método **includes** que recebe como argumento o **inputValue**. Se digitarmos o texto de uma das **todos** no input de busca, obtemos a referência da Todo específica, mas para que possamos obter apenas as Todos que **não** derem match com a busca, podemos utilizar o not (!), para inverter a condição e obter todos as Todos, que não deram match com o texto inserido no input de busca.

Como agora, obtemos um array com os Todos que não deram match com o input de busca, para percorrer por todos esses itens e aplicar uma classe neles que fará com que eles fiquem invisíveis, podemos utilizar o método forEach e pra cada item dele, removeremos a classe **d-flex,** e adicionaremos a classe **hidden**, onde está aplicado um estilo css com a propriedade display: none, que faz com que o elemento não seja visível na tela.

Devemos repetir este processo de filtro, para fazer o processo retrógado e inserir a classe **d-none** e remover a classe **hidden**, quando o match acontecer as lis sejam inseridas novamente na tela.

E para concluir, devemos separar o código em funções de responsabilidades únicas, para uma maior legibilidade e manutenabilidade do nosso código.

**Conclusão:**

```jsx
const formAddTodo = document.querySelector('.form-add-todo')
const todosContainer = document.querySelector('.todos-container')
const inputSearchTodo = document.querySelector('.form-search input')

const addTodo = inputValue => {
  if (inputValue.length) {
    todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
    </li>
  `
  }
}

const removeTodo = clickedElement => {  
  if (Array.from(clickedElement.classList).includes('delete')) {
    clickedElement.parentElement.remove()
  }
}

const hiddenTodo = inputValue => {
  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
  })
}

const showTodo = inputValue => {
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
  })
}

const filterTodos = inputValue => {
  hiddenTodo(inputValue)
  showTodo(inputValue)
}

const handleAddTodo = event => {
  event.preventDefault()
  const inputValue = event.target.add.value.trim()

  addTodo(inputValue)  
  event.target.reset()
}

const handleRemoveTodo = event => {
  const clickedElement = event.target
  removeTodo(clickedElement)
}

const handleFilterTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  filterTodos(inputValue)
}

formAddTodo.addEventListener('submit', handleAddTodo)
todosContainer.addEventListener('click', handleRemoveTodo)
inputSearchTodo.addEventListener('input', handleFilterTod
```

#rumoafluencia
---

**Comment by Roger-Melo** [comment]
Excelente @dracoalv, rumo à fluência! 🎯
