### ISSUE TITLE
Resumo da Aula A condicional switch (Aula 03-04) da etapa 02

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3736]
# A condicional ***switch*** - Aula 03-04 - Resumo

## O que é a condicional ***switch case*** ?

É uma estrutura condicional que registra múltiplas condições e que utiliza um valor padrão quando nenhuma das condições anteriores é satisfeita.

```javascript
switch(expressão) {
	case <valor 1>:
  // código
  	break
  case <valor 2>:
  // código
  	break
  case <valor 3>:
  // código
  	break
  default:
  // código
  	break
}
```

**Comment by Roger-Melo** [comment]
Show @ananopaisdojavascript. Vamo que vamo, rumo à fluência! 🙌
