### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3740]
## Comparações com igualdade estrita 

Os operadores ‘===’ e ‘!==’ são utilizados nas comparações de igualdade e diferença levando em conta se os valores comparados são do mesmo tipo. 
```js
Console.log(31 === 31) -> true //  
```
```js
Console.log(31 === ‘31’) -> false 
```
// Ao comparar um valor númerico com uma string o resultado é falso. Diferentemente da comparação com o operador ‘==’ que retorna um ‘true’.Isso acontece porque nas operações com os operadores ‘==’ ou ‘!=’ o javascript antes de efetuar a comparação faz uma conversão de tipo. No caso, de string para numbers. Devido a isso, é mais indicado o uso dos comparadores de igualdade estrita. 

Os operadores igual a ‘==’ e diferente de ‘!=’.  

Quando utilizamos o duplo sinal de igual na comparação de expressão que envolve tipos diferentes, o resultado pode ser um true (verdadeiro). 

 
```js
 Console.log( 31 == ‘31’) -> true
```
 // O javascript faz uma conversão implícita do tipo string para number antes de realizar a comparação.

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
