### ISSUE TITLE
Aplicação: [Weather Application]

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#3745]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/ThiagoDeMorais/weather-app

### Maiores dificuldades durante a implementação

* Nomear funções.
* Lidar com *promises*. Tive dificuldade em tratar e utilizar os dados encapsulados por *promises*. Ao digitar o nome de uma cidade inexistente, ou de maneira errada, eu obtive um erro o qual não resolvi. Caso a *API* não encontre o nome da cidade, ao executar a função *getCityData* e por conseguinte a *fetchData*, obtém-se uma *promise* com um *array* vazio, na função *getAllData* eu fiz dois *destructing* para pegar as propriedades *Key* e *LocalizedName* da primeira posição do array encapsulado pela *promisse*, mas como o *array* está vazio, ele não tem propriedade e isso gerou um erro. Pensei em ao invés de *fazer* um *destructing*, receber a reposta da *getCityData* e verificar o conteúdo dela antes de atribuir às novas constantes, mas não o fiz pois fiquei em dúvida em qual das funções eu deveria tratá-lo, na *getAllData* no arquivo  *app.js* ou na *fetchData* do arquivo *weather.js*.

### Menores dificuldades durante a implementação

* Usar *Query Parameters*.
* Utillização da API.

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @ThiagoDeMorais!

Vou deixar a análise de seu Weather App [aqui](https://drive.google.com/file/d/1g6Bj4fP3bVXka-MjL-TkVSbobmDbLmbR/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by ThiagoDeMorais** [comment]
Muito obrigado pela excelente e criteriosa análise, professor Roger.  Eu refatorei o código com as correções feitas e com as mudanças sugeridas:

* Limpei o *input* após o usuário enviar *form*;
* Renomeei as funções e constantes;
* Corrigi o excesso de requisições( era por isso que eu tive que trocar a APIKey diversas vezes durante os testes rsrs);
* Eliminei as funções que estavam sendo mais preciosismo do que necessárias;
* Compreendi bem a função do ternário. Mesmo com código funcionando, eu estava utilizando ele de maneira confusa; 
* Tratei os erros com o *if* e vou pesquisar mais sobre *Optional chaining*.

Mais uma vez, obrigado, professor, as análises são feitas com muito esmero.
