### ISSUE TITLE
Dúvida no exercício 38

### ISSUE THREAD

**Issue by FelipeD4ntas** [roger-melo-treinamentos/curso-de-js-roger-melo#3747]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 03 da etapa 14 - Aula 01-05

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1984848

### Descreva a dúvida

Minha duvida está no exercicío 05, na aplicação de exportar uma tabela HTML para um arquivo CSV, para ser aberto no EXCELL, vi a aula algumas vezes, fiz tudo mas quando abro a planilha no excell fica toda a string CSV em uma coluna só no EXCELL, como resolvo isso? ja tentei até copiar o código da resolução do exercicío pra saber se eu tava fazendo algo errado, mas continou com esse problema no EXCELL.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @FelipeD4ntas!

Vc chegou a testar o .csv no Google Planilhas, como mostrado na aula?

Se sim, funcionou como o esperado? Se não funcionou como o esperado tanto no gg planilhas quanto no excel, pode ser algo no código. Caso contrário, pode ser algum tipo de "feature" do excel hahah.

Mas de qualquer forma, preciso ver o código para ajudar com mais precisão. 

Sobe todos os arquivos (HTML, CSS, JS + CSV) para um repositório no github, ou pasta do drive, ou cole HTML, CSS e JS no corpo da issue e anexe o CSV =)

**Comment by Roger-Melo** [comment]
Conseguiu resolver? Vou fechar a issue mas no que precisar, é só abrir uma nova =)
