### ISSUE TITLE
Resumo da Aula Stringficando e parseando dados 01-06 da etapa 13

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3751]
Podemos armazenar dados um pouco mais complexos como arrays, para isto, precisamos converter em string. Para obter estes dados, precisamos converter novamente para o formato original; este processo todo se assemelha ao que vemos em objetos JSON.

Usamos o método global `.stringfy()` para converter as informações para o formato JSON. Como argumento, ele recebe um objeto ou array. Dado um array `myArray`:

```js
JSON.stringfy(myArray)
```
Para armazenar na Local Storage o array transformado em string, fazemos:

```js
localStorage.setItem("myArray", JSON.stringify(myArray))
Para obter o dado da Local Storage e convertê-lo ao formato original:
const JSONFromLocalStorage = localStorage.getItem(“myArray”)
const myConvertedArray = JSON.parse(JSONFromLocalStorage)
```
@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
