### ISSUE TITLE
Não conseguira achar a propriedade "tagName" na propriedades do evento

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3761]
### Etapa da aula

5

### Nome da aula

Event bubbling e event delegation - Aula 04-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/890634

### Descreva a dúvida

```js
const ul = document.querySelector('ul')
ul.addEventListener('click' , event => {
    console.log(event)
})
```
Esse pedaço  de código é  para checar  se o elemento clicado foi realmente uma LI. Investigando no browser nas propriedades eu não conseguir achar a propriedade "tagName" , mesmo usando f5 para auxiliar na busca. Dei uma lida na documentação para ver se tinha sido descontinuada, mas não foi. Na lista de propriedade que achei com o nome da tag foi : localName e nodeName. 

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @Sansanoski.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Não conseguira achar a propriedade "tagName" na propriedades do evento

Esse mesmo problema foi relatado em uma outra issue, dê uma olhada: [Propriedade tagName não aparece](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/326#issuecomment-811613488).

Acredito que nessa issue você encontrará mais contexto do que pode estar acontecendo.

Se restar alguma dúvida, pode comentar por aqui.

**Comment by Sansanoski** [comment]
Sim, ajudou bastante. Resolvido. Valeu

**Comment by MivlaM** [comment]
Show. No que precisar, é só abrir uma nova issue =)
