### ISSUE TITLE
Aplicação: TODO

### ISSUE THREAD

**Issue by hayttle** [roger-melo-treinamentos/curso-de-js-roger-melo#3763]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/hayttle/curso-javascript-todo

### Maiores dificuldades durante a implementação

Refatoração para separar em métodos com funções específicas

### Menores dificuldades durante a implementação

Manipulação do DOM

**Comment by Roger-Melo** [comment]
Olá @hayttle.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @hayttle!

Vou deixar a análise de seu Todo-list [aqui](https://drive.google.com/file/d/1EiFF0PUi1E0BeERO0p_CChMflOOxWGLR/view?usp=sharing).

Após a análise em vídeo, eu continuei observando o código para ver como seria possível simplificar a lógica do "check" e reorganização dos to-dos na ul. Resumidamente, fiz o seguinte...

Como `removeTodo` não continha uma lógica apenas de remoção de to-dos, renomeei a função para `handleTodoClick`.

```javascript
// antes
const removeTodo = (event) => {/*...*/}
```

```javascript
// depois
const handleTodoClick = (event) => {/*...*/}
```

---

Em seguida, para facilitar a identificação dos to-dos, adicionei neles (tanto nos estáticos no HTML quanto nos inseridos via js) atributos `data-*`. Em breve vc chegará nas aulas em que falo sobre esses atributos.

```html
<li data-todo="Fazer investimento">
  <span>Fazer investimento</span>

  <span>
    <i class="fas fa-check-circle" data-check="Fazer investimento"></i>
    <i class="fas fa-trash" data-trash="Fazer investimento"></i>
  </span>
</li>
```

```javascript
const addTodo = (event) => {
  // ...
  const todo = inputAddTodo.value.trim()
  // ...
  
  todosContainer.innerHTML += `
    <li data-todo="${todo}">
      <span>${todo}</span>

      <span>
        <i class="fas fa-check-circle" data-check="${todo}"></i>
        <i class="fas fa-trash" data-trash="${todo}"></i>
      </span>
    </li>`;
};
```

Feito isso, ficou mais simples elaborar a lógica de remoção dos to-dos dentro da `handleTodoClick`:

```javascript
const handleTodoClick = (event) => {
  const clickedElement = event.target
  const trashWasClicked = clickedElement.dataset.trash

  if (trashWasClicked) {
    const todo = document.querySelector(`[data-todo="${trashWasClicked}"]`)
    todo.remove()
  }
}
```

A lógica para verificar se o check foi marcado também ficou similar:

```javascript
const handleTodoClick = (event) => {
  const clickedElement = event.target
  const trashWasClicked = clickedElement.dataset.trash
  const checkWasClicked = clickedElement.dataset.check

  if (trashWasClicked) {
    const todo = document.querySelector(`[data-todo="${trashWasClicked}"]`)
    todo.remove()
    return
  }

  if (checkWasClicked) {
    // lógica para reorganizar os to-dos
  }
}
```

Aqui vem a sacada: para reorganizar os to-dos, não é necessário usar `push`, `splice`, `indexOf`, `forEach` para inserir to-dos novamente no DOM, etc.

Vc pode obter e reposicionar os to-dos para a parte superior ou inferior da ul usando apenas os métodos `append` e `prepend`:

```javascript
const handleTodoClick = (event) => {
  // ...

  if (checkWasClicked) {
    const todo = document.querySelector(`[data-todo="${checkWasClicked}"]`)
    const todoWasMarkedAsDone = todo.classList.contains('done')
    
    todo.classList.toggle('done')

    if (todoWasMarkedAsDone) {
      todosContainer.prepend(todo)
      return
    }
    
    todosContainer.append(todo)
  }
}
```

Obviamente, pra não ficar com if aninhado e extenso, vc pode isolar o código em uma função:

```javascript
const reorganizeTodos = checkWasClicked => {
  // ...
}

const handleTodoClick = (event) => {
  // ...

  if (checkWasClicked) {
    reorganizeTodos(checkWasClicked)
  }
}
```

Sacou a ideia?

Deu pra simplificar bastante. Pelo que vi, o app.js original tinha 105 linhas e o refatorado ficou com 77.

Adicionei vc como colaborador no repositório privado que contém o código refatorado para vc conferir se os ajustes fizeram sentido. Veja se a notificação chegou pra vc.

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by hayttle** [comment]
Olá @Roger-Melo, vou verificar a sua refatoração e retorno

Obrigado pela atenção.

**Comment by hayttle** [comment]
Olá, @Roger-Melo 

De fato o código ficou muito mais enxuto. Uma boa sacada o uso do prepend() e append(). Eu tive que fazer um teste paralelo com esse dois métodos em outra aplicação para assimilar que o prepend() e o append() trocam de lugar o elemento em questão. Gostei.

OBS: 
- você falou a pronúncia certa do meu nome de segunda (Raitle) =)
- usei InsertAdjacentHTML('afterbegin',element) para inserir o novo TODO no início da lista
- estava pensando em nova feature como sendo algum método ou função que ainda não tinha sido apresentado no curso, mas o "check" do TODO realmente é uma nova feature.
- o uso do ";" é o autoformat do VSCode

Obrigado pela análise.

**Comment by Roger-Melo** [comment]
Massa! Que bom que acertei o nome hahah.

Já que vc viu a análise, vou fechar a issue. Mas no que precisar, é só abrir uma nova, ok? =)
