### ISSUE TITLE
Resumo da Aulas 3 e 4 da etapa 01

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#3769]
#Resumos: 

[Aula 4.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/8807312/Aula.4.pdf)
[Aula 3.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/8807313/Aula.3.pdf)

**Comment by Roger-Melo** [comment]
Excelente @George-Luis-Costa, rumo à fluência! 🎯
