### ISSUE TITLE
Duvida exercício da aula 03 da etapa 05

### ISSUE THREAD

**Issue by muritadb** [roger-melo-treinamentos/curso-de-js-roger-melo#3781]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada + destructuring em parâmetros de funções - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890633

### Descreva a dúvida

Bom dia, tarde ou noite, Roger tudo bem.
No exercicio 07, a questão pede para adicionar um evento de click no H1 e em seguida apagar os filhos de Body, eu estava tentando usar a propriedade children do Body e utilizando o metodo remove para apagar, segue o codigo abaixo: 
```js
const body = document.body

h1.addEventListener('click', () => {
  body.children.remove()
})
```
obviamente não consegui, na resolução você utiliza o innerHTML recebendo uma string vazia, dai eu entendi que sobreescreve o html, mas não entendi porque o body.children.remove(), não funciona.

O remove() só funciona no elemento pai e no filho não ?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá, @muritadb.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Não entendi porque o body.children.remove(), não funciona.

De início, vou te dar uma dica: Sempre use o console.log a cada linha escrita. Assim você consegue saber o valor que uma determinada expressão/parâmetro/variável está armazenando.

Não assuma que suas expressões estão recebendo os valores que você espera, é essencial usar o console.log para checar suas expressões conforme você vai escrevendo o código. Por exemplo:

```js
console.log(body.children) // Faça assim para ver qual valor o body.children está retornando
```

`body.children` resulta em um [HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection) que contém os filhos do body, o método `remove() `não é um método de um HTMLCollection, mas sim de um elemento do DOM. 

Você pode saber mais sobre eles nos links abaixo:

[Elemento.children](https://developer.mozilla.org/en-US/docs/Web/API/Element/children)
[Metodo Remove](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove)

Nesse caso, uma solução seria usar o remove nos elementos do HTMLCollection. Por exemplo:

```js
  body.children[0].remove() // Remove o primeiro elemento da HTMLCollection
``` 

> ## O remove() só funciona no elemento pai e no filho não?

O método `remove()` remove do DOM o elemento no qual a invocação dele foi encadeada. No código que você mostrou, não faz sentido usar `body.children.remove()`, você poderia deixar apenas `body.remove()` e o código funcionaria perfeitamente para a proposta do exercício.

```js
const body = document.body

h1.addEventListener('click', () => {
  body.remove()
})
```

Ficou mais claro?

**Comment by muritadb** [comment]
Boa Noite, @MivlaM entendi o HTMLCollection ficou mais claro agora obrigado, e valeu pela dica do console.log(), ficarei mais atento nos proximos exercicios :)
