### ISSUE TITLE
Resumo da Aula Retornando valores (Aula 01-05) da etapa 03

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3790]
# Retornando valores - Aula 01-05 - Resumo

## O que é `return`?

É uma palavra reservada que retorna o parâmetro (valor) da função.

```javascript
const double = function(number) {
	return number * 2
}
```

## Existe um outro modo de retornar um valor dentro de uma função?

Podemos usar, dentro da função, uma variável cujo valor é o parâmetro, retornando essa variável.

```javascript
const double = function(number) {
	const numberResult = number * 2
	return numberResult
}
```

## De que modo é possível imprimir o valor da função?

É possível imprimir o valor da função de algumas formas:
* Chamando a função com argumentos no console
* Colocando o valor da função em uma variável

```javascript
const double = function(number) {
	return number * 2
}

console.log(double(3))

const result = 3
console.log(double(result))
```

**Comment by Roger-Melo** [comment]
Show @ananopaisdojavascript. Vamo que vamo, rumo à fluência! 🙌
