### ISSUE TITLE
Resumo da Aula 02 -06 da etapa 12

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3791]
Referenciamos os elementos da página que devem receber a imagem do card e do ícone que corresponde ao clima.
Na chamada da função getCityWeather(), inserimos a propriedade IsDayTime no destructuring do objeto retornado pela função, pois baseada nela alteramos a imagem do card.
Logo após a condicional que inserimos no código, inserimos um outro if que verifica o valor de IsDayTime e altera a imagem exibida, por meio da manipulação do atributo src do elemento img, indicando o diretório que contém as imagens a serem utilizadas.
Ainda na função getCityWeather(), inserimos a propriedade WeatherIcon no destructuring do objeto retornado, pois com base nela alteramos os ícones de clima. O valor dela compreende 1 a 44, de acordo com as condições do clima.
Após a chamada da função getCityWeather(), criamos o elemento img que deve receber o ícone e adicionamos ele dentro do respectivo container. De forma similar ao anterior, direcionamos seu scr ao diretório que contém os ícones a serem utilizados.
E, logo após as condicionais, inserimos a constante com o elemento criado dentro da respectiva div, usando o .innerHTML.
No arquivo css, especificamos alguns estilos para ajustar a disposição do ícone e atribuímos estes a uma classe, que adicionamos na div do ícone.

```
const cityForm =  document.querySelector('[data-js="change-location"]')
const cityNameContanier =  document.querySelector('[data-js="city-name"]')
const cityWeatherContanier =  document.querySelector('[data-js="city-weather"]')
const cityTemperatureContanier = document.querySelector('[data-js="city-temperature"]')
const cityCard =  document.querySelector('[data-js="city-card"]')
let timeImg = document.querySelector('[data-js="time"]')
const timeIconContanier  = document.querySelector('[data-js="time-icon"]')

cityForm.addEventListener('submit', async event => {
    event.preventDefault()

    const inputValue = event.target.city.value 
    const [{ Key, LocalizedName }] =  await getCityData(inputValue)
    const [{ WeatherText, Temperature, IsDayTime, WeatherIcon }] =  await getCityWeather(Key)
    const timeIcon = `<img src="./src/icons/${WeatherIcon}.svg" />`

    if(cityCard.classList.contains('d-none')){
        cityCard.classList.remove('d-none')
    }

    if(IsDayTime){
        timeImg.src = './src/day.svg'
    } else {
        timeImg.src = './src/night.svg'
    }

    timeIconContanier.innerHTML = timeIcon
    cityNameContanier.textContent = LocalizedName
    cityWeatherContanier.textContent = WeatherText
    cityTemperatureContanier.textContent = Temperature.Metric.Value
})

```

**Comment by Roger-Melo** [comment]
Show @Giansantos-carlos. Vamo que vamo, rumo à fluência! 🙌
