### ISSUE TITLE
Resumo da Aula 3 escopos em JavaScript que você deve conhecer - Aula 01-03 da etapa 05

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3794]
**ESCOPO**
```Escopo``` pode ser definido como a visibilidade de uma ```Variável```. Ou seja, é o limite de até onde ela poderá ser acessada. E os seus principais limites são: FUNÇÕES, BLOCOS E O LÉXICO.

**Os 3 principais ESCOPOS em JavaScript**
- Escopo de FUNÇÕES
- Escopo de BLOCOS
- Escopo LÉXICO

```Escopo de FUNÇÕES``` -> é quando a variável é declarada dentro de uma função. Quando isso é feito, ela só poderá ser acessada dentro da própria função.
```js
function myFunc () {
  let cat = 'Zeca'
  const age = 3
  var color = 'cinza'
}  // As 3 variáveis acima só podem ser acessadas dentro do escopo da myFunc()
```

```Escopo de BLOCOS``` -> um bloco é definido por abertura e fechamento de chaves { }, tais como, ```if```, ```for```, ```while```, ```for of```, todos são blocos.
 Mas **ATENÇÃO**, em blocos os limitadores são apenas para ```const``` e ```let```!!!
 Quando a variável é declarada com ```var```, ela PODE ser acessada fora do bloco.

```Escopo de LÉXICO``` -> o escopo LÉXICO ele é definido quando tempos funções dentro de outras funções. Quando isso ocorre as variáveis declaradas na FUNÇÃO de base, pode ser acessadas por todas as outras funções criadas dentro da função inicial.
Veja o exemplo abaixo:
```js
const external = () => {
  const book = 'Sapiens'

  const internal = () => {
    console.log( book )  // Como a ```internal()``` não tem a declaração da variável book, ela irá procurar dentro da função a qual pertence, no caso a ```external``` e vai exibir seu valor.
  }
internal()
}
// Isso irá ocorrer independente do número de funções estiverem aninhadas.
```
Mas **ATENÇÃO**, as variáveis só podem ser acessada da base para as próximas funções. Quando uma variável é declarada dentro de uma função mais interna, NÃO PODERÁ SER ACESSA pela função a qual ela também pertence.

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
