### ISSUE TITLE
Entrevista emprego - Teste Técnico

### ISSUE THREAD

**Issue by kadiado** [roger-melo-treinamentos/curso-de-js-roger-melo#3797]
### Etapa da aula

8

### Nome da aula

Reduce

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/991052

### Descreva a dúvida

Olá bom dia, estou fazendo um teste tecnico para uma entrevista de emprego e estou com dificldade em um retorno do metodo reduce.

Vou colocar abaixo o desafio, o link para o snippet e a resolução que apliquei.

-------------------------------------------------------------------------------------

**Explicação do desafio**

Olá, boa tarde!
Precisamos criar uma variável nova que tenha o valor total dos produtos do carrinho e se
o frete é grátis (compras acima de 300 reais). Essa variável será chamada
‘cartPricesInfo’.

Além disso, nossa página de carrinho atualmente a variável ‘totalPrice’ se encontra com o
valor ‘undefined’ independente da situação. Precisamos que vocês atualizem ela com o
valor total dos produtos do carrinho.
E também precisamos que a variável ‘freeShipping’ tenha valor ‘true’ caso o frete seja
gratuito.

Um colega te alertou de que por padronizações internas do time de tags nesse tipo de
situação utilizamos normalmente o método Javascript reduce().
Além disso, disse que você deve fazer uma função que retorna os dois valores (‘totalPrice’ e
‘freeShipping’) para depois atribuí-los para as variáveis.

-------------------------------------------------------------------------------------

**o Link do Snippet** - https://gitlab.com/-/snippets/1881791

var cart_products = [{
    'product_id': 'IN2350',
    'product_name': 'Teclado Mecânico Rozar K600',
    'product_price': '650.00',
    'product_quantity': '1',
    'product_url': 'http://www.foo.com/p/IN2350',
    'product_category': 'peripherals',
    'product_brand': 'Rozar'
}, {
    'product_id': 'IN4566',
    'product_name': 'Monitor Gamer LED GL UltraWide 25"',
    'product_price': '1399.99',
    'product_quantity': '1',
    'product_url': 'http://www.foo.com/p/IN4566',
    'product_category': 'monitor',
    'product_brand': 'GL'
}, {
    'product_id': 'ES7112',
    'product_name': 'Pacote de Post-it Fenix 50 unidades',
    'product_price': '14.95',
    'product_quantity': '5',
    'product_url': 'http://www.foo.com/p/ES7112',
    'product_category': 'office',
    'product_brand': 'Fenix'
}, {
    'product_id': 'BR8810',
    'product_name': 'Miniatura Yoshi Haras',
    'product_price': '6.50',
    'product_quantity': '2',
    'product_url': 'http://www.foo.com/p/BR8810',
    'product_category': 'others',
    'product_brand': 'Haras'
}];

-------------------------------------------------------

**Minha solução até agora** 

```js
let freeShipping = false;
let totalPrice = 0;

const cartPricesInfo = cart_products
  .map(product => ({
    product_id: product.product_id,
    product_name: product.product_name,
    product_price: parseFloat(product.product_price),
    product_quantity: parseFloat(product.product_quantity),
    product_url: product.product_url,
    product_category: product.product_category,
    product_brand: product.product_brand,
  }))
  .reduce((acc, product) => {
    let total = (acc += product.product_price);
   
    if (total > 300) {
      freeShipping = true;
    }

    return { acc };
  }, {});

console.log(cartPricesInfo, freeShipping);
```

Quando retorno apenas a let 'total' ela me da o valor dos produtos somados, mas qndo retorno um objeto ele nao entrega os os valores somados e a variavel freeShipping retorna falso

```js
{ acc: '[object Object]6.5' } false
```

----------------------------------------------------------------------------------------

**Saída esperada da resolução**

```js
cartPricesInfo = { totalPrice: 2137.74, freeShipping: true };
totalPrice = 2137.74;
freeShipping = true;
```

@Roger-Melo

**Comment by dracoalv** [comment]
isto está acontecendo pois você está somando um objeto com números, o retorno do seu reduce precisaria ser um número e não um objeto. Além disso, você está retornando um objeto contendo uma propriedade acc, enquanto deveria retornar a let que recebe a operação acumulativa.

A minha resolução para o seu problema foi obter e armazenar uma copia dos produtos em uma const, utilizar o objeto construtor Number no valor do product_price e depois criar o reduce, contendo como primeiro parâmetro o acc e como segundo parâmetro o item a ser iterado, que no caso seriam os produtos, a função então retornaria a let totalPrice recebendo o accumulator + cada preço de cada produto. Após isso criei um if pra checar se a let totalPrice é maior ou igual a 300, se sim, eu altero o freeShipping para true, e por final retorno a let totalprice.

```js
let freeShipping = false;
let totalPrice = 0;

const cartProductsCopy = cart_products.map(product => ({
  'product_id': product.product_id,
  'product_name': product.product_name,
  'product_price': Number(product.product_price),
  'product_quantity': product.product_quantity,
  'product_url': product.product_url,
  'product_category': product.product_category,
  'product_brand': product.product_brand,
}))

const cartProductsIsFreeShipping = cartProductsCopy.reduce((acc, item) => {
  totalPrice = acc + item.product_price

  if (totalPrice >= 300) {
    freeShipping = true
  }

  return totalPrice
}, 0)

console.log(cartProductsIsFreeShipping, freeShipping)
```

**Comment by kadiado** [comment]
isso foi minha dúvida, eu retornei o objeto pois a saída pedida é:

```js
cartPricesInfo = { totalPrice: 2137.74, freeShipping: true };
totalPrice = 2137.74;
freeShipping = true;
 ```
 
 esse retorno de dois objetos que eu não entendi se é possível fazer por dentro do reduce?

**Comment by dracoalv** [comment]
ahhh sim, desculpe, acabei não fazendo o que você queria não é mesmo?

neste caso, você usaria o reduce apenas para obter o totalPrices, e após isso você pode criar uma função pra verificar se o preço é maior que 300 e então retornar um objeto contendo as propriedades totalprice e freeShipping.

algo mais ou menos assim

```js
let freeShipping = false;
let totalPrice = 0;

const cartProductsCopy = cart_products.map(product => {
  product = {
    'product_id': product.product_id,
    'product_name': product.product_name,
    'product_price': Number(product.product_price),
    'product_quantity': product.product_quantity,
    'product_url': product.product_url,
    'product_category': product.product_category,
    'product_brand': product.product_brand,
  }

  return product
})

const totalProductPrice = cartProductsCopy.reduce((acc, item) => 
  totalPrice = Math.round(acc + item.product_price), 0)

const isFreeShipping = products => {
  if (totalPrice > 300) {
    freeShipping = true
  }

  return totalCartProducts = {
    totalPrice: totalProductPrice,
    freeShipping
  }
}

isFreeShipping(totalProductPrice)

console.log(isFreeShipping())
```

**Comment by Roger-Melo** [comment]
Olá @kadiado. Dá uma olhada [nessa resposta](https://drive.google.com/file/d/1jkl8cvQwxUgq50vWcLsimJfsJ2SdgzI-/view?usp=sharing). Acabei de subir o vídeo, baixe ele pra sua máquina para ver em alta resolução.

Só depois vi que usei `Number()` para converter o preço, mas pode usar `parseFloat` como vc fez =)

**Comment by Roger-Melo** [comment]
Obrigado pela contribuição @dracoalv ☺🙏🏻

**Comment by kadiado** [comment]
@dracoalv aah, o problema acredito que foi na interpretação, eu estava tentando fazer o reduce retornar os dois valores, vlw demaaais <3

**Comment by kadiado** [comment]
@Roger-Melo meu caro, excelente como sempre seu feedback!!

Sobre o enunciado do exercício que me confundiu, fazendo separado eu consegui entender e aplicar, como eu disse ao Marcelo em cima, duvida era como retornava dois valores em uma função, mas sobre como usar os métodos eu consegui entender legal sem duvidas, realmente senti que estava fazendo sentido como e o que usar.

Muuito obrigado pela atenção, de coração !!
