### ISSUE TITLE
O método forEach e callbacks - aula 02-04

### ISSUE THREAD

**Issue by luisotacilio** [roger-melo-treinamentos/curso-de-js-roger-melo#38]
Professor Roger,  a partir do segundo 0:44 da aula é dito que trata-se de uma Arrow Function que tem um so parametro, entao pode ser eliminado os parentesis.  Eliminado o parentesis e escrito o termo "callback" e dito que assim vai ser denominado o parametro.

Fiquei confuso porque "parametro e  nome de função se fundem", meu entendimento é que ela deixou de ser anônima para ser posteriormente invocada: o termo callback esta denominando a função que antes não tinha nome.  Essa invocação ocorre na linha 5:
'callback(value)

Acho que entendi:  a função é o parametro passado, mas vou precisar de mais tempo pra compreender melhor, imagino, rs.

**Comment by Roger-Melo** [comment]
Oi Luis.

> Fiquei confuso porque "parametro e nome de função se fundem",

Uma regra que pode ajudar a diferenciar é que, o nome da função sempre vem antes do sinal de atribuição,

```javascript
const myFunc = // ...
// "myFunc" é o nome da função
```

e parâmetros vem após o sinal de atribuição:

```javascript
const myFunc = param => {}
// "param" é o nome do parâmetro da função
```

> meu entendimento é que ela deixou de ser anônima para ser posteriormente invocada

Observe que quando declaramos uma `const` e atribuímos uma função a ela, o nome da const é o nome da função, então a função não é anônima:

```javascript
const myFunc = param => {}
// "myFunc" é o nome da função
```

Mais à frente, eu vou falar sobre objetos em JavaScript. E funções são objetos.

Tanto é que se eu declarar uma função e encadear na referência dela uma propriedade `.name`, o nome da `const` é retornado:

```javascript
const myFunc = () => {}

myFunc.name // 'myFunc'
```

> o termo callback esta denominando a função que antes não tinha nome. Essa invocação ocorre na linha 5: 'callback(value)

`callback` é apenas o nome do parâmetro que recebe a referência da função.

Como a referência da função foi recebida no parâmetro `callback`, eu posso invocar essa função recebida, usando a sintaxe de par de parênteses:

```javascript
const myFunc = callback => {
  callback() // invocação da referência da função que o parâmetro callback recebeu
}
```

> Acho que entendi: a função é o parametro passado, mas vou precisar de mais tempo pra compreender melhor, imagino, rs.

O primeiro contato com callbacks não costuma ser muito amigável.

Mas esse conceito ainda será bastante explorado durante o treinamento e exercícios. Com a prática e com o tempo, ele se consolidará aos poucos em sua mente =)

Ficou mais claro?

@luisotacilio

**Comment by luisotacilio** [comment]
Professor Roger,  dúvida esclarecida, muito obrigado. Além do mais: repeti
o exemplo da aula 7 vezes,  fazendo comentários do que acontecia em cada
linha de código,
agora o assunto está dominado, pois acertei  os exercícios propostos sobre
callbacks. Pode encerrar a questão!

Em sex., 18 de set. de 2020 às 22:41, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal Luis, que bom que esclareceu =D

Por agora vou fechar a issue, mas no que precisar, é só dar o toque =)
