### ISSUE TITLE
Resumo da Aula O método map - Aula 01-02 da etapa 08

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#380]
O método *map* é responsável por gerar um novo *array* com a mesma quantidade de itens do array original, porém com cada item transformado. Ele executa uma *callback* para cada item do *array* na qual ele foi encadeado e, o valor retornado por essa *callback* é adicionado no *array* que o próprio *map* está gerando. Este método não é destrutivo, ou seja, não modifica o *array* original, mas a *função de callback* é capaz de modificá-lo.

## Argumentos

1. ***Função de callback*** que será executada para cada item do *array* original. O valor retornado por esta *callback* é adicionado no *array* que está sendo gerado pelo *map*. Essa *callback* pode receber 3 parâmetros, são eles:
    1. ***item*** que recebe o item atual que está sendo iterado;
    2. ***index*** que recebe o index do item atual que está sendo iterado; *(opcional)*
    3. ***array*** que recebe *array* que está sendo iterado. *(opcional)*
2. ***thisArg*** que é o valor do this a ser utilizado na invocação da função de callback. *(opcional)*

## Retorno

Um novo *array* com a mesma quantidade de itens do *array* original em que o *map* está encadeado.

## Quando não devo utilizar o map?

- Quando não vou utilizar o *array* que ele retorna;
- Quando a *função de callback* passada no argumento do *map* não está retornando valor algum.

---

*MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Muito bom @sou-gabriel! Pra cima, rumo à fluência! 🔥
