### ISSUE TITLE
WeatherApp

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3802]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Giansantos-carlos/weather-application-master.git

### Maiores dificuldades durante a implementação

Boa noite !
A dificuldade que tive foi depois de fazer o deploy da aplicação no netlify. Pois quando enviava o form recebia um alert de erro no fecth, então fiz algumas algumas pesquisas e consegui resolver, colocando um 's' depois do http, essa foi  a maior dificuldade.
e também tive um pouco de dificuldade em fazer alguns destructuring.

### Menores dificuldades durante a implementação

usar o *boostrap

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos! 

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Me avise aqui quando fizer a mudança =)

Fico no aguardo.
