### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by marcoferreiradev** [roger-melo-treinamentos/curso-de-js-roger-melo#381]
###  Existe três formas de armazenar variaveis hoje em dia:
**const** - Recebe um valor e o mantém fixo, não podendo ser reatribuido um valor;
**let** - Valor pode ser reatribuido;
**var** - Valor pode ser reatribuido

### Boas práticas de nomeação de variáveis

1. Dar nomes significativos as variáveis;
2. Caso a variável seja composta de mais de duas palavrar usar a conveção camelcase;
3. O nome das variáveis podem conter  letras, números, undescores e cifrão PS: nome não pode começar com número.
3. Não se utilizar de palavras reservadas da linguagem, pois dará erro;
 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @marcoferreiradev! Rumo à fluência! 🔥
