### ISSUE TITLE
Resumo da Aula Funções vs Métodos (Aula 02-03) da etapa 03

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3810]
# Funções vs Métodos - Aula 02-03 - Resumo

## O que são funções?

Funções são blocos de código que podem ser reutilizados sempre que for necessário.

```javascript
const sum = (numberOne, numberTwo) => numberOne + numberTwo
```

## O que são métodos?

Métodos são propriedades associadas a objetos ou outros tipos de dados (como as ***strings***) que armazenam uma função.

```javascript
// Método que deixa os caracteres de uma string em maiúsculas

someString.toUpperCase()
```

## Qual é a diferença entre funções e métodos?

A diferença entre funções e métodos está na forma de invocação.
* Funções podem ser chamadas de modo independente em qualquer parte do código (lembrando que, no caso de expressões de função, essas devem ser chamadas DEPOIS de sua declaração)

```javascript
const sum = (numberOne, numberTwo) => numberOne + numberTwo
console.log(sum(4, 5))
```

* Métodos são chamados com notação de ponto.

```javascript
const name = "Ana"
const allCapitalLetters = name.toUpperCase()
console.log(allCapitalLetters)
```

**Comment by Roger-Melo** [comment]
Boa @ananopaisdojavascript, rumo à fluência! 🔥
