### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07 da etapa 05

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3814]
**Query selector & query selector all**

```Query selector``` -> Considerando que "query" em português significa consulta, podemos afirmar que ```querySelector()``` é um método do objeto ```document``` com o qual consultamos a referência de uma tag dentro do arquivo html. 
Para tanto, inserimos o argumento daquilo que queremos consultar.
Veja:
```js
const example = document.querySelector('argumento')

/* Exemplos de argumentos */
const example = document.querySelector('p') // retorna o primeiro parágrafo encontrado de cima para baixo

const example = document.querySelector('.error') // retorna qualquer elemento que tenha uma CLASSE com o nome ```error```.

/* Vários elementos com a MESMA CLASSE */
const example = document.querySelector('div.error') // retorna somente a primeira div que pertence a CLASSE "error".
```
Buscando direto na página a descrição do argumento:
![querySelector](https://user-images.githubusercontent.com/58309283/172077323-e3329ff8-2cb0-4bfa-a6f9-81851f206c97.png)

```Query selector all``` -> esse método percorre por toda estrutura do DOM e cria um ```NodeList``` (lista de nós) que contém todas as referências das tags que foi atribuída como argumento.

```js
const example = document.querySelectorAll('argumento')
```

O que é um [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)?
Ele é similar a um array, contudo não tem todos os métodos que um array possui. 
Mas ele contém índice e pode ser percorrido por um ```forEach```.

[Seletores CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)

**Comment by Roger-Melo** [comment]
Boa @andersonpereiragithub, rumo à fluência! 🔥
