### ISSUE TITLE
Resumo da Aula Mais sobre o Spread Operator 01-06 da etapa 14

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3816]
Também é possível usar o _spread operator_ em strings. Com ele, é possível transformar uma cadeia de caracteres em itens de um array que pode ser utilizado em casos que necessitamos comparar caracteres ou transformar a cadeia. Tomando o exemplo da função que inverte uma string, podemos substituir o método `string.split(‘’)` (que separa os caracteres e coloca em um array) por `[...string]`:
```js
const getReversedString = string => [...string].reverse().join(‘’)
```
O _spread operator_ também facilita a comparação de uma sequência de números que podem ser armazenados em um array. O espalhamento” dos itens do array permite usar os métodos `.min()` e `.max()`, que só aceitam tipos number como argumento.
```js
const numbers = [7, 3, 5, 3.1, 9]
console.log(Math.min(numbers)) // retorna NaN pois argumento é um array
console.log(Math.max(numbers)) //retorna NaN pois argumento é um array

console.log(Math.min(...numbers)) // funciona, pois desencapsulou os itens do array numbers
console.log(Math.max(...numbers)) // funciona, pois desencapsulou os itens do array numbers
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
