### ISSUE TITLE
Resumo da Aula Retornando valores e exercício - 01 - 05 da etapa 03

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#3826]
Essa ainda tem sido uma das minhas dificuldades, então vamos lá:
Eu posso realizar todo o processo com variáveis, argumentos, métodos e todo o mais dentro do bloco de uma função.
Uma vez que tenha montado minha lógica e chegado ao resultado esperado, esse resultado pode ser "exportado" da 
função ao fazer uso da palavra chave "return". 
É necessário lembrar que, no final das contas, uma função sempre deve retornar um valor, seja uma string, um boolean,
number, array, objeto e todo o mais possível. Esse valor pode ser manipulado, desde que seja retornado pela função. 

E por aí, Roger?

**Comment by Roger-Melo** [comment]
Excelente @VitorPeixotoDev, rumo à fluência! 🎯
