### ISSUE TITLE
Tive dois problemas na correção desses exercícios [feedback]

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#3828]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1324088

### Descreva a dúvida

No exercício 4, como a minha solução era concatenar o array brasil com o array nordeste, mas por ser uma const não era possível, subi até o exercício 3 para confirmar se o exercício tinha me pedido para criar uma const e não uma let, como estava escrito que o brasil deveria ser uma const, entendi que não era para modifica-lo.

Já na parte onde precisamos percorrer o array brasil para verificar se todos os estados continham 7 letras, eu fiz um ternário e não entendia o por quê de retornar apenas true ou false e não o que estava no ternário.

```js
const hasMoreThan7Letters = brasil.every(item => item.length > 7 
  ? 'Sim, todos os estados tem mais de 7 letras.'
  : 'Nem todos os estados tem mais de 7 letras.')
```

sua solução foi receber o retorno do every em uma const e então criar o ternário, o que eu fiquei confuso também.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv!

> ## ...como estava escrito que o brasil deveria ser uma const, entendi que não era para modifica-lo.

`const` não garante imutabilidade. `const` impede que um valor seja reatribuído, mas quando se trata de objetos, como objetos são mutáveis por padrão, é perfeitamente possível modificar o valor de um objeto que uma const armazena. Olha só:

```javascript
const obj = {}
obj.prop = 1

console.log(obj) // {prop: 1}

const arr = []
arr[0] = 1

console.log(arr) // [1]sole.log(obj) // {prop: 1}
```

Observe também que o enunciado dos exercícios pede explicitamente que o array `brasil` seja modificado:

```javascript
/*
  03
  // ...
  - Adicione 3 novos estados da região Norte no início do array e mostre no 
    console. Pesquise pelo método "unshift" no MDN;
  - Remova o primeiro estado do array `brasil` e mostre-o no console;
  // ...
*/

/*
  04
  // ...
  - Remova de `brasil` os estados do `sudeste`, colocando-os em uma constante
    chamada `newSudeste`. Pesquise pelo método "splice";
  - Adicione os estados do `nordeste` ao array `brasil`. Esses estados devem
    ficar no mesmo nível que os estados já existentes, não em um array separado;
  // ...
*/
```

O método `unshift` adiciona elementos no array original, então era mais uma pista de que o array original deveria ser mutado.

`splice` também modifica o array original.

Mutação geralmente deve ser evitada, mas no caso destes exercícios, a ideia era incentivar a conhecer os métodos =)

---

> ## Já na parte onde precisamos percorrer o array brasil para verificar se todos os estados continham 7 letras, eu fiz um ternário e não entendia o por quê de retornar apenas true ou false e não o que estava no ternário.

Cuidado com o "agir pela intuição" em relação ao tipo de valor que vc espera que um método retorne.

Sempre consulte a documentação no MDN para entender qual tipo de valor o método que vc está usando retorna, e como ele retorna.

Como vc pode ver na [doc do every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every), ele executa a função de callback para cada item do array, e sempre retorna um boolean indicando se a condição que foi especificada na função foi atendida para todos os itens do array. 

Se a função retorna um valor truthy para todos os itens do array, o `every` retorna `true`. Qualquer coisa diferente disso, o `every` retorna `false`.

No exemplo que vc deu, o `every` sempre vai retornar `true`, pois independente do boolean no qual `item.length > 7` resulta, a função sempre está retornando a string preenchida que o ternário retornou. E string preenchida é um valor truthy.

O código abaixo exemplifica a mesma situação. 

Mesmo que nenhum item do array tenha mais de 7 letras, devido à função retornar `'olá'` para todos os itens do array (e 'olá' é string preenchida - valor truhty), `hasMoreThan7Letters` armazena o boolean (true) que o `every` retornou:

```javascript
const arr = ['a', 'b', 'c']

const hasMoreThan7Letters = arr.every(item => {
  const value = item.length > 7 ? 'oi' : 'olá'
  
  console.log(value) // 3x olá
  return value
})

console.log(hasMoreThan7Letters) // true
```

Está ficando mais claro?

**Comment by dracoalv** [comment]
O problema da const ocorreu devido a minha fraqueza em interpretação de texto, de fato foi muita falta de atenção..

Quanto ao método every, agora tudo faz sentido, pelo fato do método sobre retornar um boolean.

Isso significa que se eu tivesse fechado o parênteses da invocação do método antes do ternário teria funcionado.

```js
const arr = [1, 2, 3]

const hasMoreThan7Letters = arr.every(number => number.length > 7)
  ? 'oi' : 'ola'

```

Isso faria sentido?

desde já quero agradecer por esclarecer as dúvidas com tanto empenho e dedicação!👏🏽👏🏽

**Comment by Roger-Melo** [comment]
@dracoalv dá uma olhada [neste vídeo](https://drive.google.com/file/d/1Zrztpw5iopbW--frS14aJ5tlWiMnj-H2/view?usp=sharing).

Precisei fazer um pequeno corte nele para atender o interfone, mas veja se está ficando mais claro e qualquer dúvida, pode perguntar =)

**Comment by dracoalv** [comment]
nossa, verdade, ali no exemplo do array eu acabei passando números para simplificar e nem me dei conta do uso indevido da propriedade length, porém quando você arrumou o array e ele passou a ter 2 itens como strings, e essas strings eram maior que 7 caracteres, a expressão de retorno do método every retornou true, neste caso o ternário após esse retorno funcionaria ?

**Comment by Roger-Melo** [comment]
Na real, eu não vejo sentido em usar ternário nesse caso. [Aqui](https://drive.google.com/file/d/1Tt8IhB4uwFbME7r3J0i7Aqq-dN8PbVvm/view?usp=sharing) eu explico pq =)

@dracoalv

**Comment by dracoalv** [comment]
entendi como funciona o método every, já que ele precisa retornar true ou false e consequentemente a const que armazena a invocação do every vai retornar true ou false, isso seria valido?

```js
const everyRerurn = ['um', 'dois', 'tres']
  .every(item => item.lenght > 3)
    ? 'x'
    : 'y'
```

**Comment by Roger-Melo** [comment]
Válido é, mas não faz sentido de acordo com o que vc quer.

Se o nome da const é `everyReturn`, fica subentendido que ela irá armazenar o retorno do `every` (um boolean), mas não é o que está acontecendo. 

Ela está armazenando o retorno do ternário. 

O `every` ali é apenas parte da expressão da condição do ternário, saca?

```javascript
const ternaryCondition = ['um', 'dois', 'tres'].every(item => item.lenght > 3)

const everyReturn = ternaryCondition ? 'x' : 'y'

console.log(everyReturn) // 'y'
```

@dracoalv

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
