### ISSUE TITLE
Etapa 11, Correção dos Exercícios da aula 01 - Aula 02 - 02

### ISSUE THREAD

**Issue by Will-Andrade** [roger-melo-treinamentos/curso-de-js-roger-melo#383]
Olá professor, boa noite.
Durante a correção dos exercícios fiquei em dúvida em sua correção do último exercício da lista sobre o que significou para o código eu não conseguir fazer um destructuring dentro do método, de uma propriedade do mesmo obj no qual tô inserindo esse método. A seguir:

```
let booksBox = {
  spaces: 5,
  booksIn: 0
};

booksBox.addBooks = amountOfBooks => {
  const { spaces } = booksBox;
  const isTheBoxFull = booksBox.booksIn === spaces;
  const theresNoSpaceLeft = booksBox.booksIn + amountOfBooks > spaces;

  if (isTheBoxFull) return "A caixa já está cheia"

  if (theresNoSpaceLeft) {
    return getAvailableSpacesMessage(spaces, booksBox.booksIn)
  }

  booksBox.booksIn += amountOfBooks;
  
  const bookPluralOrSingular = 
    getPluralOrSingular(booksBox.booksIn, 'livros', 'livro');
  return `Já há ${booksBox.booksIn} ${bookPluralOrSingular} na caixa`
}

```
Na linha onde declaro a ``` const { spaces } = booksBox ``` não é possível realizar o destructuring da chave "booksIn" por eu não estar usando a palavra chave "this" ou o motivo é simples e exclusivamente a noção de tipos de dado de referência e valor? Se, no caso de criar um método com uma função anônima e ao invés de utilizar "obj.chave" eu utilizasse "this.chaveDoObj", eu podia me esquivar de usar "booksBox.booksIn" ?

Espero ter me feito entender. Muito obrigado pela correção!
@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Willian.

Antes de responder, deixa eu dar uma dica.

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, basta inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

Ele ficará assim:

```javascript
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

---

O `this` de uma arrow function referencia o `this` do escopo em que ela foi declarada (escopo léxico). Se Isso ainda é estranho para você, não se preocupe, em breve você chegara nas aulas em que explico isso. 

Para usar o this neste caso, a função (método) teria que ser refatorada para uma função tradicional `function () {...}`. Mas resumindo, eu não acho que usar o `this` seja a melhor saída. Eu ensino o this, mas evito usá-lo ao máximo justamente por que é muito fácil ele mudar de valor.

Então não é que não é possível fazer um destructuring na `booksIn`, mas é que a let que esse destructuring cria é apenas uma let que contém o valor que `booksBox.booksIn` armazenava naquele momento.

Como eu precisava modificar o valor da propriedade do objeto, não fazia sentido fazer um destructuring e modificar a let.

O código abaixo mostra a mesma situação (com menos código). Observe que quando o destructuring de `obj` acontece, dentro do escopo da `myFunc` agora eu posso acessar tanto a let `myProp` como a propriedade `myProp` do objeto (através da expressão obj.myProp):

```javascript
const obj = {
  myProp: 1
}

const myFunc = () => {
  let { myProp } = obj

  myProp = 999 // modificou a let myProp

  console.log('myProp:', myProp, 'obj.myProp:', obj.myProp) // myProp: 999 obj.myProp: 1
}

myFunc()
```

Ou seja, quem sofreu uma reatribuição de valor foi a let `myProp` e não a propriedade `myProp` do objeto `obj`.

---

E sim, você está correto em relação a passagem de valores de tipos primitivos e tipos de referência.

Usando o mesmo exemplo acima, se `myProp` armazena um objeto, a let `myProp` criada no destructuring apenas referencia o objeto que `obj.myProp` armazena. Ou seja, `obj.myProp` e a let `myProp` estão armazenando o mesmo objeto em memória:

```javascript
const obj = {
  myProp: { 
    nestedProp: 1 
  }
}

const myFunc = () => {
  const { myProp } = obj

  console.log(myProp, obj.myProp) // {nestedProp: 1} {nestedProp: 1}
  
  myProp.nestedProp = 7 // mudou o valor de obj.myProp.nestedProp através da let myProp
  
  console.log(myProp, obj.myProp) // {nestedProp: 7} {nestedProp: 7}
  console.log(myProp === obj.myProp) // prova que a myProp e obj.myProp referenciam o mesmo objeto
}

myFunc()
```

---

Off-topic: prefira ser consistente no estilo de código. Se escolher inserir blocos em ifs de uma linha (recomendado), seja consistente nessa decisão e aplique ela no decorrer do código.

Evite inconsistências como nos `if`s abaixo.

```javascript
if (isTheBoxFull) return "A caixa já está cheia"

if (theresNoSpaceLeft) {
  return getAvailableSpacesMessage(spaces, booksBox.booksIn)
}
```

---

Respondi a dúvida?

@Will-Andrade

**Comment by Will-Andrade** [comment]
Respondeu perfeitamente professor, muito obrigado!
Sobre o toque com ifs, também agradeço. Evitarei esse tipo de coisa pois pensando bem agora, é estranho ler um código em que numa parte alguma intrução é escrita de uma forma e logo abaixo, uma outra semelhante é escrita de forma diferente.

**Comment by Roger-Melo** [comment]
Legal @Will-Andrade. Já que ficou mais claro vou fechar a issue, mas quando surgirem dúvidas, é só abrir uma nova =)
