### ISSUE TITLE
Resumo da Aula Booleans e comparacoes - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3830]
BOOLEANS

Apesar da aula ser sobre booleans, muito se foi discutido sobre o método `String.includes()` ou `Array.includes()`

`true` ou `false` é utilizado todas as vezes que precisamos utilizar deste resultado para as nossas operações. 

Muito utilizado com os operadores de comparação: == , != , > , < , <= , >= 

Estes operadores podem ser utilizados com `numbers` e `strings`
```javascript
const name = 'roger'

console.log(name == 'roger') // true
console.log(name == 'Roger') //  false
console.log(name > 'belinha') // true
console.log(name > 'Roger') // true
console.log(name > 'Belinha') // true
```
Observações:
- Letras do final do alfabeto são maiores que do início.
- Letra minúscula é maior que letra maiúscula

```javascript
const email = 'brucewayne@rogermelo.com.br'
const includes = email.includes('@') // true

const names = ['dio', 'roger', 'robert']
const arrayIncludes = names.includes('roger') // true
```

Conclusão interessante: No MDN eu achei apenas o objeto `Boolean` e não os tipos primitivos `true` ou `false`

**Comment by Roger-Melo** [comment]
Excelente @lucian-bonifacio, rumo à fluência! 🎯
