### ISSUE TITLE
AppWeather

### ISSUE THREAD

**Issue by Giansantos-carlos** [roger-melo-treinamentos/curso-de-js-roger-melo#3832]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Giansantos-carlos/weather-application-master.git

### Maiores dificuldades durante a implementação

A maior  dificuldade foi depois do depploy da aplicação no netlify. quando enviar o form um alert com erro  de fecth era exibido, então fiz algumas pesquisas e descobri que devia adicionar um 's' no final do 'http', e assim o problema foi resolvido.

### Menores dificuldades durante a implementação

usar o boostrap.

**Comment by Roger-Melo** [comment]
Olá @Giansantos-carlos!

Vou deixar a análise de seu Weather App [aqui](https://drive.google.com/file/d/1A2LXXxLfkU-F8sYL3LgUbi4phhxDRZEu/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by Giansantos-carlos** [comment]
Ola, Roger passando pra dizer que já vi a análise e gostei bastante, saquei as ideias e melhorias propostas.
Muito Obrigado !

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)
