### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3834]
**Modificando estilos CSS (inline)**

Primeiro vamos buscar um elemento que gostaríamos de modificar seu estilo
```js
const title = document.querySelector('h1')

console.log(title) // retorna <h1 style="color: blue;">Modificando estilos CSS</h1>
```
Não podemos usar o ```.setAttribute()``` para modificar um estilo, pois ele sobrescreve o estilo que houver no elemento. 
```js
title.setAttribute('style', 'margin: 50px;') // ele sobrescreve todos os estilos que houver.
````
Para INSERIR um novo estilo e ou modificar o estilo, usaremos a propriedade ```.style``` do elemento.
```js
title.style.margin = '50px' // quando usamos a PROPRIEDADE style ele adiciona um novo estilo sem sobrescrever o existente.

title.style.color = 'green' // alteramos só a cor, sem afetar outros estilos.
```
/* Particularidades */

Se quisermos mudar a fonte, por exemplo, em css usaríamos o ```font-size```. 
Contudo o JavaScript lê o termo fonte-size como um operação matemática. Sendo assim, temos que deletar o sinal de subtração e inserir o "camel case". 
```js
title.style.font-size = '50px' // Error!
title.style.fontSize = '50px' // Correto!
```
Quando precisarmos modificar uma propriedade style e não conhecemos sua nomenclatura, basta seguir os seguintes passos:
1) console.log(title.style)
2) Clica na seta para expandir suas propriedades
3) Ctrl + F e pesquise o estilo que gostaria de escrever

/* Deletando um estilo */

Veja que acima atribuímos uma "margin: 50px", então para retirar, basta atribuir uma string vazia.
```js
title.style.margin = ''
```

**Comment by Roger-Melo** [comment]
Excelente @andersonpereiragithub, rumo à fluência! 🎯
