### ISSUE TITLE
Resumo da Aula a condicional switch e exercícios - Aula 03-04da etapa 02

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3843]
## switch

Utilizamos para verificar múltiplos valores possíveis de uma constante ou variável e pra cada possível valor, a possibilidade de reagirmos de forma diferente. 	  

```js
const grade = 'C' 

switch(grade) { 

    case 'A': 

        console.log('você tirou um A') 

        break 

    case 'B':     

        console.log('você tirou um B') 

        break 

    case 'C': 

        console.log('você tirou um C') 

        break 

        default: 

        console.log('Nota inválida') 

} 
```
Se o break for esquecido, será executado o case correspondido e os demais cases, independentemente de ter ou não sido correspondido.

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
