### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3845]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Sansanoski/Quiz-Interativo/tree/master

### Maiores dificuldades durante a implementação

Conseguir dar nomes significativos para as variáveis. Também tive dificuldade em lembrar que usar o setAttribute() e melhor que simplesmente o event.classList() , pelo fato de sobre escrever o CSSin line.

### Menores dificuldades durante a implementação

Em realizar os eventos em geral , como o de 'click' . Usar os eventos de classes.

**Comment by Roger-Melo** [comment]
Olá @Sansanoski.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Sansanoski!

Vou deixar a análise de seu Quiz [aqui](https://drive.google.com/file/d/1PFiRLokAuOdo40zgWCgqAHe7j9CexKKX/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by Sansanoski** [comment]
Obrigado.

**Comment by Roger-Melo** [comment]
@Sansanoski como vc acessou a issue por email, não sei se chegou a ver, mas tem um link na palavra "aqui". 

Não sei se o link é exibido via email, por isso sempre que for visualizar uma issue, o ideal é visualizar através do GitHub mesmo =)

**Comment by Sansanoski** [comment]
Boa noite professor. Alto gabarito essa sua análise, agradeço muito pelo feedback.  Fez sentido sim esses pequenos detalhes que deveria haver no código. Vou refazer o código colocando em pratica os pontos anotados de melhoria.
Com relação  ao dos dois botões  fora do formulário, foi a solução que achei. Não lembro exatamente porque eu coloquei fora, mas acredito que estava dando errado na hora do click, mesmo usando event.stopPropagtion(), acho que os dois estavam sendo disparados ou não estava conseguindo manipular corretamente. Teria alguma dica nessa ocasião  ??
Gostei demais dessa analise, sem duvida vai me ajudar a atingir um nível melhor no meu  código.

**Comment by Roger-Melo** [comment]
@Sansanoski o `stopPropagation` deve ser usado quando algum ancestral do elemento no qual o evento foi encadeado tem o mesmo tipo de evento e vc não quer que esse evento do ancestral seja disparado também.

Os ancestrais dos buttons são div e form, e não existe evento de clique neles, então o `stopPropagation` é desnecessário.

Vc pode inserir a div com os buttons dentro do form e, dentro da `backToStart`, inserir a invocação do `preventDefault` (da mesma forma que na `showResult`).

Isso vai fazer com que qualquer clique nos botões impeça que a página seja recarregada, mesmo que os botões estejam dentro do form.

Sacou a ideia?

Implementa e se tiver alguma dúvida, pode chamar aqui =)

**Comment by Sansanoski** [comment]
Perfeito , obrigado.
