### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3848]
**Obtendo, adicionando, removendo e alternando classes CSS**
```js
const paragraph = document.querySelector('p')
````
**Obtendo** -> ```paragraph.classList```
**Adicionando** -> ```.classList.add()```
**Removendo** -> ```.classList.remove()```
**Alternando** -> ```.classList.toggle()```

console.log(paragraph.classList) // retorna todas as classes da tag <p>

```classList``` -> retorna uma lista de classes
```DOMTokenList``` -> similar a um array

/* ADICIONANDO CLASSE */
Existe o método ```.add()``` dentro da ```.classList``` que permite adicionar uma Classe.
```js
paragraph.classList.add()
```

/* REMOVENDO CLASSE */
Existe o método ```.remove()``` dentro da ```.classList``` que permite remover uma Classe.
```js
paragraph.classList.remove()
```
Adicionando classe através de condições preexistente
```js
const paragraphs = document.querySelectorAll('p')

paragraphs.forEach( paragraph => {
    if(paragraph.innerText.includes('error')) { // traz o conteúdo da tag
        paragraph.classList.add( 'error' )
    }else if(paragraph.textContent.includes('success')) { // traz o conteúdo da tag
        paragraph.classList.add( 'success' )
    }
})
```

**DIFERÊNCA** entre ```.innerText``` para ```textContent``` é que o primeiro traz todo o texto visível, enquando ```.textContent``` traz todo texto, mesmo que ele tenham um ```display: none;``` ocultando ele.

/* ALTERNANDO CLASSE */
```JS
const title = document.querySelector( 'h1' )

title.classList.toggle( 'test' ) // Adicionado se não existir a Classe.
title.classList.toggle( 'test' ) // Remove se a Classe existir.
```

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
