### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3849]
COMPARAÇÕES COM IGUALDADE ESTRITA

- O operador `==` e `!=`
Significa “igual a” e “diferente de”
Neste operador é possível fazer comparações com tipos de dados diferentes e, mesmo assim, o resultado ser `true`, pois este faz uma conversão de tipos.
```javascript
const age = 31

console.log(age == 31) // true
console.log(age == ‘31’) // true

console.log(age != 31) // false
console.log(age != ‘31’) // false
```

- O operador `===` e `!==`
Significa “igual a, do mesmo tipo” e “diferente de, e do mesmo tipo”
Chama-se de **comparação estrita**
É o operador aconselhado a usar quando queremos fazer comparações, pois este considera o tipo de dado.
```javascript
const age = 31

console.log(age === 31) // true
console.log(age === '31') // false

console.log(age !== 31) // false
console.log(age !== '31') // true
```
Abaixo explicações nas palavras do MDN

`igual(==)` -> Retorna verdadeiro caso os operandos sejam iguais.
`Estritamente igual (===)` -> Retorna verdadeiro casos os operandos sejam iguais e do mesmo tipo.

**Comment by Roger-Melo** [comment]
Show @lucian-bonifacio. Vamo que vamo, rumo à fluência! 🙌
