### ISSUE TITLE
Etapa 01, nome do vídeo: exercicio-02, correção: 21- newName

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#385]
Boa Noite !
Roger no meu vscode a const name quando atribuido a let newName ela fica com um risco em todas as chamadas é normal ficar desta forma, fiquei na duvida se fiz algo de errado ?

```
const name = 'walter white'
let newName = name[0].toUpperCase() + name.slice(1,6) + ' ' + name[7].toUpperCase() + name.slice(8) 
 
console.log(newName)
```
![etapa 01 exercio-02- ex-21](https://user-images.githubusercontent.com/65474069/113803137-4e22e200-9732-11eb-8b31-4bd689c2968e.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcelo.

Antes de responder, deixa eu dar uma dica.

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, basta inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

Ele ficará assim:

```javascript
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

---

Você não fez algo errado, não se preocupe. O VSCode inseriu um traço na palavra `name` apenas por que existe uma propriedade no escopo global chamada `name`. 

Resumidamente, seu código está em escopo global e sobrescreveu uma variável `name` que já existe no objeto window. Se você ainda não chegou na parte do treinamento em que explico o que são escopos e variáveis globais, fique tranquilo, logo logo você entenderá isso =)

Para resolver isso por agora, você pode escolher uma das duas opções:

1. Modificar o nome da const. Ela poderia se chamar `characterName`, por exemplo;
2. Desabilitar esse tipo de verificação no VSCode.

Se escolher a segunda opção, segure `ctrl+shift` e pressione `P` para que a command pallete seja exibida e então, insira "settings" para que a opção "Preferences: Open Settings (JSON)" seja exibida.

Ao clicar nessa opção, um JSON de configurações do VSCode será aberto. Insira a chave "editor.showDeprecated" e atribua `false` a ela.

Perceba que essa segunda opção desabilita o aviso do VSCode para todas as outras propriedades e métodos que possam ter o mesmo "problema".

Recomendo que escolha a primeira opção. Listei a segunda apenas para que você ficasse ciente de que é possível fazer isso.

Me avise se resolveu? =)

@Mlluiz39

**Comment by Mlluiz39** [comment]
Obrigado pelo feedback, e pode deixar que a respeito da issue vou me atentar,  pois eu coloquei entre as três crases mas acredito que foi por falta do nome javasScript que eu não coloquei.

**Comment by Mlluiz39** [comment]
Obrigado pela força.
