### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by jfjunior86** [roger-melo-treinamentos/curso-de-js-roger-melo#3850]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/jfjunior86/quiz-Info

### Maiores dificuldades durante a implementação

Não tive dificuldade de elaborar, pois já tinha feito o quiz de filmes.

### Menores dificuldades durante a implementação

01 Confesso que esqueci de colocar o link do arquivo .js no index.html (rsrsrs), mas consegui identificar o erro com facilidade;
02 Não senti segurança criar um reduce e solucionar o problema da linha com mais de 80 caracteres.

**Comment by Roger-Melo** [comment]
Olá @jfjunior86.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @jfjunior86!

Você pode baixar a análise de seu Quiz [neste link](https://drive.google.com/file/d/16Fb8cEhxOqZgSUCrEGuRv22U2yMfK-Yw/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by jfjunior86** [comment]
Roger, foi muito gratificante ver você corrigindo meu quiz. 
01 - Quanto as respostas do questionário para enviar o quiz, realmente faltou atenção da minha parte no momento de responder.
02 - Reduce - não assisti à aula desse assunto ainda. Na verdade queria ter falado do destructuring, mas a palavra reduce estava impregnada na minha cabeça, pois ouvi uma pessoa falando sobre ele. 
03 - Na questão do idioma, obrigado pela dica, vou escolher um e usar apenas ele em cada aplicação.
04 - Notei todas as observações que você fez, agora vou seguir cada uma das dicar e fazer as melhorias sugeridas.

**Comment by Roger-Melo** [comment]
Massa! No que precisar, é só abrir uma nova issue =)
