### ISSUE TITLE
setInterval() e animação da pontuação - Aula 02-03

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3852]
Sobre o setInterval(). E uma função que recebe dois parâmetros . O primeiro e uma função de call-back  , e o segundo parâmetro será um number, esse referente ao tempo em milissegundos para a call-back ser invocada cada vez . Para que o setInterval() não fique em um loop infinito, usamos o clearInterval() para pausar a sequencia de invocações da função de call-back como paramento

**Comment by Roger-Melo** [comment]
Show @Sansanoski. Vamo que vamo, rumo à fluência! 🙌
