### ISSUE TITLE
dificuldade de refatorar a class para factory function no exercício 37 - etapa 14

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#3860]
### Etapa da aula

14

### Nome da aula

factory function

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1946514

### Descreva a dúvida

Uma das dúvidas  eu consegui tirar procurando nas Issues,
Não sei se estou fazendo a correta atribuições da {precision e do próprio template)
Agora está dando um erro que eu não consigo ver, por falta de conhecimento aprofundado;

```js
const createClock = (template) => ({
  template,
  render: () => {
    const formattedTime = getFormattedTime(template)
    console.log(formattedTime)
  },
  start: () => {
    const oneSecond = 1000
    render()
    timer = setInterval(() => render(), oneSecond)
  },
  stop: () => {
    clearInterval(timer)
  }

})

console.log(createClock())

const createExtendedClock = (options) => ({
  ...createClock(),
  precision: options,
  precision: 1000
})

const clock = createExtendedClock({ template: 'h:m:s', precision: 1000 })

clock.start()



o erro é esse:
app.js:116 Uncaught ReferenceError: render is not defined
    at Object.start (app.js:116:5)
    at app.js:148:7
start @ app.js:116
(anonymous) @ app.js:148

```

Eu não estou avançando devido a este exercício, estou realizando algumas revisões raio-x

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs!

Antes de responder, deixa eu dar uma dica...

Quando postar um código, se assegure que o código que vc está disponibilizando é executável, ou seja, contém tudo o que é preciso para ser executado por outra pessoa. 

No exemplo que vc postou, faltam trechos essenciais para a execução fora do contexto da sua máquina (`getFormattedTime`, por exemplo). Quando for assim, pode postar o código todo na issue (incluindo CDD e HTML, se necessário) ou subir os arquivos em uma pasta no drive ou github, o que for melhor pra vc =)

---

Dentro do método `start`, vc está tentando acessar o método `render` como se ele estivesse em um escopo externo, o que não é o caso. `render` é apenas um método que está no mesmo o objeto.

Para que vc consiga acessar um outro método do mesmo objeto, vc vai precisar usar o `this`. E além disso, terá que fazer com que o `this` referencie, de fato, o objeto.

Lembra que o `this` "muda" em arrow functions?

Neste caso, vc teria que usar função tradicional (declarada com a palavra-chave `function`) ou a abreviação, como abaixo.

```javascript
const getObj = () => ({
  x () {
    return 'x() executado'
  },
  y () {
    console.log(this)     // {x: ƒ, y: ƒ}
    console.log(this.x()) // x() executado
  }
})

getObj().y()
```

De qualquer forma, não se cobre tanto em acertar de primeira. O objetivo não é esse. Se estiver se batendo muito, veja a correção, execute [esse passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) e se tiver qulquer dúvida, pode chamar aqui =)

**Comment by carlosdevjs** [comment]
Dei mancada ao enviar o código pela metade, não acontecerá novamente.
Vou revisar suas anotações. obrigado pelo feedback.
