### ISSUE TITLE
Resumo da Aula setTimeout() e o objeto window da etapa 07

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#3866]
<h1 align="center">setTimeout() e o objeto window </h1>

Relembrando o método window é um objeto que existe no escopo global do Javascript isso no caso do frontend, no caso do uso do NodeJS no backend o objeto global seria o _**global**_ , muitos dos métodos que utilizamos até agora, são pendurados ao window, porém a engine do browser consegue entender que você quis chamar aquele método sem precisar invocar o windows, e exemplos é o **_console.log()_** que se não fosse omitido seria **_document.console.log()_** ou até mesmo o **_document.querySelector()_**, que seria **_window.document.querySelector()_**.

## setTimeout

O setTimeout executa uma função após uma certa quantidade de tempo que você especificar, ele faz isso recebendo 2 argumentos, a primeira uma função, e o segundo o tempo em ms que será executado a função do primeiro argumento após o termino dessa contagem.

```js
  setTimeout(() => {
   alert('Executou após 2 segundos')
}, 2000)
```

## Escrolando a tela para o topo

No caso de precisar escrolar automaticamente a tela para o topo podemos usar o método scrollTo(), onde esse método receberá 2 argumentos, o primeiro o eixo X e o segundo o eixo Y.

```js
  scrollTo(0,0)
```

## setInterval

O **_setInterval_** é bem similar ao **_setTimeout_**, com a diferença que o segundo argumento ao invés de ser o tempo que será executado o primeiro argumento, cada vez que esse tempo se esgotar ele irá executar o primeiro argumento de novo e de novo, esse seria o método ideal para criar um relógio por exemplo.

```js
  let counter = 0

  const timer = setInterval(() => {
    counter++
    console.log(`${counter}s`)
    if(counter === 5){
      clearInterval(timer)
    }
   }, 1000)
```

Uma coisa importante de saber é que o método **_clearInterval()_**serve para limpar o intervalo no exemplo acima, demos a condição que se o contador chegar a 5 que o interval pare de executar, só que o argumento utilizado no clearInterval é o id do setInterval que no caso se for dado um log em timer ele vai retornar um id único.

**Comment by Roger-Melo** [comment]
Boa @Beninigmal, rumo à fluência! 🔥
