### ISSUE TITLE
Dúvida sobre retorno do fetch

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#3869]
### Etapa da aula

12

### Nome da aula

Aula 01-07 - Obtendo Informações do Clima da Cidade

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1410863

#### Bom dia, professor!
Preciso de uma luz aqui, e gostaria de solicitar sua ajuda novamente com essa aplicação.
Eu já havia terminado e a análise já foi feita, inclusive, porém a API que eu estava utilizando não tinha suporte a 'HTTPS' e eu não pude fazer deploy no Netlify, pois dava erro.
Troquei de API, essa que encontrei é bem parecida coma  que eu estava utilizando, e fui modificando no código alguns detalhes que variavam.
Então a segunda função, a getCityWeatherData , não funcionou mais. Creio que estou deixando passar algum detalhe, mas não consigo descobrir o que é. Poderia me auxiliar, por favor?
Abaixo está o código com comentários mostrando a resposta que podemos visualizar no devtools, na aba Network, na primeira função os dados vem corretamente, na segunda, não importa qual cidade eu utilize como argumento, vem sempre a mesma resposta.

```js
const APIKey = '585fd43ab04b431dbc7114516221406'

const getCityUrl = (cityName) =>
`https://api.weatherapi.com/v1/current.json?key=585fd43ab04b431dbc7114516221406&q=${cityName}&aqi=yes`

const fetchData = async (url) => {
  try {
    const response = await fetch(getCityUrl(url))

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }   
    // console.log(response.json())
    return response.json()
  } catch ({ name, message }) {
    console.log({ name, message })
  }
}

fetchData ('london')
// resposta do fetchData('london') na aba Network do devtools:
/*
location: {name: "London", region: "City of London, Greater London", country: "United Kingdom", lat: 51.52,…}
country: "United Kingdom"
lat: 51.52
localtime: "2022-06-14 14:39"
localtime_epoch: 1655213944
lon: -0.11
name: "London"
region: "City of London, Greater London"
tz_id: "Europe/London"
*/

const getCityWeatherData = async (cityName) => {
  const cityURL = getCityUrl(cityName)
  const data = await fetchData(cityURL)

  console.log(data)
}
getCityWeatherData ('london')
// getCityWeatherData ('london') na aba Network do devtools:
/*
location: {name: "Key Key", region: "Semnan", country: "Iran", lat: 36.07, lon: 55.67, tz_id: "Asia/Tehran",…}
country: "Iran"
lat: 36.07
localtime: "2022-06-14 18:09"
localtime_epoch: 1655213944
lon: 55.67
name: "Key Key"
region: "Semnan"
tz_id: "Asia/Tehran"
*/
```
Repositório da versão original com API antiga que funciona:
https://github.com/ElaineDelgado/weather-application

Obrigada desde já!

@Roger-Melo

**Comment by ElaineDelgado** [comment]
Analisando os códigos e tentando achar onde estou errando, acabei chegando em uma solução, a fetchData receber uma cidade,e  não uma URL como argumento. O que na minha cabeça faz sentido visto que no código que postei antes testei invocar a fetchData passando 'london' como argumento. Modifiquei a getCityWeatherData:
```js
const getCityWeatherData = async (cityName) => {
  const getCityData = await fetchData(cityName)
  const cityData = await getCityData
  console.log(cityData)
}
getCityWeatherData ('london')
// as informações sobre o clima em Londres foram recebidas
```

Mas aí, olhando o código antigo algo não fez sentido, por que eu passei uma URL como argumento da fetchData (e funcionou)?

```js
const getCityUrl = (cityName) =>
  `http://api.weatherstack.com/current?access_key=${APIKey}&query=${cityName}`

const fetchData = async (url) => {
  try {
    const response = await fetch(getCityUrl(url))

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }

    return response.json()
  } catch ({ name, message }) {
    console.log({ name, message })
  }
}

const getCityData = async (cityName) => {
  const cityURL = getCityUrl(cityName)
  const {
    location: { name: city },
    current: weatherInfo,
  } = await fetchData(cityURL)

  return [city, weatherInfo]
}
```
Vou tentar achar a aula onde esse código foi refatorado, porque deu um nó no meu cérebro aqui!

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Você pode baixar a resposta à sua dúvida [neste link](https://drive.google.com/file/d/1tMe87t8WzbwjyRhvTaxkmxu2y4tZBLoI/view?usp=sharing).

Se restar qualquer dúvida, é só dar o toque =)

**Comment by ElaineDelgado** [comment]
Obrigada pela explicação, professor, mas agora a dúvida é outra! Ficou muito claro que a fetchData deveria receber a cidade como argumento, não a url, tudo certo. Mas aí no meu código antigo, da aplicação que o senhor avaliou, está desse jeito, a fetchData recebe a URL e está funcionando, que é o caso que expliquei nesse segundo comentário.
Antes eu não entendia porque não funcionava, quando vi o porquê de não funcionar, me toquei o antigo código da aplicação está do mesmo jeito, e funciona! 
Aqui nesse código ainda é a API antiga que não suporta https, mas localmente funciona:
(código completo aqui: https://github.com/ElaineDelgado/weather-application)

```js
const APIKey = '422499b6dd8c9fb1e08d38bd081f4c1e'

const getCityUrl = (cityName) =>
  `http://api.weatherstack.com/current?access_key=${APIKey}&query=${cityName}`

const fetchData = async (url) => {
  try {
    const response = await fetch(getCityUrl(url))

    if (!response.ok) {
      throw new Error('Não foi possível obter os dados')
    }

    return response.json()
  } catch ({ name, message }) {
    console.log({ name, message })
  }
}

const getCityData = async (cityName) => {
  const cityURL = getCityUrl(cityName)
  const {
    location: { name: city },
    current: weatherInfo,
  } = await fetchData(cityURL)
// olha ele aqui, o fetchData recebendo a  URL o.O

  return [city, weatherInfo]
}
```
A dúvida agora é: Por que funciona?

**Comment by ElaineDelgado** [comment]
Professor, consegui fazer funcionar com a nova API, e fiz o deploy na Netlify! 
https://appweathercjrm.netlify.app

Ainda falta alterar alguns detalhes, inclusive o idioma, mas estou satisfeita que está funcionando, embora esteja bolada do porquê a função fetchData() dentro da getCityData() aceitar url ou cidade como argumento e funcionar (eu testei, e funcionou! hahah)

**Comment by Roger-Melo** [comment]
> ### Ficou muito claro que a fetchData deveria receber a cidade como argumento, não a url, tudo certo.

Não. Na verdade a fetchData deve receber a url mesmo. Quem deve receber o nome da cidade é a getCityWeatherData:

```javascript
const fetchData = async (url) => { // 👈🏻 URL recebida por parâmetro
  try {
    const response = await fetch(url) // 👈🏻 URL inserida como argumento

    // ...
  }
  // ...
}

const getCityWeatherData = async (cityName) => {
  // ...
  const data = await fetchData(cityURL) // 👈🏻 URL inserida como argumento

  // ...
}

getCityWeatherData('curitiba') // 👈🏻 nome da cidade inserida como argumento
```

---

Nesse último exemplo que vc enviou, vc de fato está inserindo a URL como argumento da fetchData,

```javascript
const getCityData = async (cityName) => {
  const cityURL = getCityUrl(cityName)
  const { 
    location: { name: city }, 
    current: weatherInfo 
  } = await fetchData(cityURL) // 👍🏻 URL inserida como argumento

  // ...
}
```

isso faz com que na fetchData, a URL seja recebida no parâmetro url,

```javascript
const fetchData = async (url) => { // 👍🏻 URL recebida no parâmetro
  // ...
}
```

porém, na hora de invocar o fetch, ao invés de inserir a url como argumento, uma nova invocação de `getCityUrl` foi inserida como argumento do fetch,

```javascript
const fetchData = async (url) => {
  try {
    const response = await fetch(getCityUrl(url)) // 

    // ...
  }
  // ...
}
```

isso faz com que a url que a fetch recebe seja essa:

```javascript
const fetchData = async (url) => {
  try {
    console.log(getCityUrl(url))
    // http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=Curitiba

    // ...
  }
  // ...
```

Ou seja, o valor que a primeira `&query` após access_key recebeu foi `http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=Curitiba`.

E a dúvida é pq funcionou, certo?

Bom, nesse caso, o servidor que devolveu a resposta provavelmente tem alguma configuração que suporta esse tipo de caso de url inserida como valor de um query parameter.

Observe que teoricamente, a URL maior deveria ter 2x `&query=Curitiba` no final, mas não tem. 

Inclusive, se vc inserir qualquer uma das urls abaixo na barra de busca do navegador e pressionar enter, as duas irão trazer os dados.

```
http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=Curitiba

http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=http://api.weatherstack.com/current?access_key=422499b6dd8c9fb1e08d38bd081f4c1e&query=Curitiba
```

Mas como isso é controlado pelo lado do servidor, não tem como afirmar ao certo como esse fallback é feito sem ver o código. Pq [na doc](https://weatherstack.com/documentation#query_parameter) eles não vão muito à fundo nisso xD

@ElaineDelgado

**Comment by ElaineDelgado** [comment]
Acho que olhei tanto pra esse código ontem que no final já não fazia mais sentido!
Muito obrigada pela ajuda!!!

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
