### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - 02-04 da etapa 03

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#3871]
Ao meu ver, é aqui que a coisa começa a decolar... Funções passadas como parâmetros de outras funções!
Comecei a programar porque me apaixonei pela dinâmica das funções algébricas, mas a ideia de uma função,
que retorna um valor que é passado para o interior de outra função... Isso é um sonho! Em JS esse sonho se chama
função de callback. Nessa aula, também me foi apresentado o método forEach. Uma forma ainda mais elegante 
de fazer parte substancial do trabalho do loop for. O método forEach pode receber três parâmetros, a saber: 
o item iterado a partir do array, o índice do mesmo e o array ao qual ele pertence originalmente.

**Comment by Roger-Melo** [comment]
Boa @VitorPeixotoDev, rumo à fluência! 🔥
