### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by CamiloMeassiMacoris** [roger-melo-treinamentos/curso-de-js-roger-melo#3872]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/CamiloMeassiMacoris/conversorDeMoedas

### Maiores dificuldades durante a implementação

Maior dificuldade foi quando tinha que trocar a moeda no select pois necessitava de um novo fatch para a api e isso tomou um bom tempo até eu conseguir fazer.

### Menores dificuldades durante a implementação

Manipular os elementos DOM e refratorar a aplicação.

**Comment by Roger-Melo** [comment]
Olá @CamiloMeassiMacoris.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by CamiloMeassiMacoris** [comment]
Combinado Roger, muito obrigado pela análise , vou rever esse erros e conceitos que você apontou para refazer a aplicação!

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
