### ISSUE TITLE
Resumo da Aula O objeto Math (Aula 03-03) da etapa 04

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#3878]
# O objeto Math - Aula 03-03 - Resumo

## O que faz o objeto `Math.PI`?
    
Mostra o valor completo do pi (razão entre a circunferência de um círculo e seu diâmetro)

```javascript
const showPI = Math.PI
console.log(showPI) // 3.141592653589793
```

## O que faz o objeto `Math.E`?
    
Mostra a base dos logaritmos naturais.

```javascript
const showLog = Math.E
console.log(showLog) // 2.718281828459045
```

## O que faz o método `Math.round( )`?
    
Converte um número decimal em inteiro de duas formas:
    
 - Se o decimal é menor que 5, o número é arredondado para baixo

```javascript
const area = 7.1

console.log(Math.round(area)) // 7
```

- Se o decimal é maior ou igual a 5, o número é arredondado para cima

```javascript
const area = 7.6

console.log(Math.round(area)) // 8
```

## O que faz o método `Math.floor( )`?
    
Converte um número decimal em inteiro, arredondando-o para baixo.

```javascript
const area = 7.1

console.log(Math.floor(area)) // 7
```

```javascript
const area = 7.8

console.log(Math.floor(area)) // 7
```

## O que faz o método `Math.ceil( )`?
    
Converte um número decimal em inteiro, arredondando-o para cima.

```javascript
const area = 7.8

console.log(Math.ceil(area)) // 8
```

```javascript
const area = 7.1

console.log(Math.ceil(area)) // 8
```

## O que faz o método `Math.trunc( )`?
    
Remove a parte decimal de um número, deixando o número inteiro.

```javascript
const area = 7.1

console.log(Math.trunc(area)) // 7
```

```javascript
const area = 7.8

console.log(Math.trunc(area)) // 7
```

## O que faz o método `Math.random( )`?
    
Gera números decimais aleatórios entre 0 e 1.

```javascript
const showRandomNumber = Math.random()

console.log(showRandomNumber) // 0.5745295464138217
```

```javascript
const showRandomNumber = Math.random()

console.log(showRandomNumber) // 0.17126109130034628
```

## Como mostrar números inteiros, aleatórios e maiores que 0 e 1?
    
Para mostrar números inteiros, aleatórios e maiores que 0 e 1, é só fazer o seguinte:

```javascript
const showRandomNumber = Math.round(Math.random() * 100)

console.log(showRandomNumber) // 48
```

**Comment by Roger-Melo** [comment]
Boa @ananopaisdojavascript, rumo à fluência! 🔥
