### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by donato-ba** [roger-melo-treinamentos/curso-de-js-roger-melo#388]
Variável = Armazenar valor. São 3 tipos:

1. var = Pode redeclarar ou reatribuir valores. É antigo
2. let = Não pode redeclarar, mas pode reatribuir valores. Utilizado atualmente
3. const = Não pode redeclarar e nem reatribuir valores. Utilizado atualmente

Regras para nomear variáveis:

- Camel case: letras maiúsculas a partir da segunda palavra na variável
- Pode conter somente letras, números, "_" (underscore) e $
- Não pode começar por número no inicio da variável
- Não pode usar palavras reservadas. Ex: let, const...

Comentários

- // comentário. (uma única linha)
    - tecla de atalha (shortcut): ctrl+;
- /* comentário */ (multilinhas)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @donato-ba! Rumo à fluência! 🔥
