### ISSUE TITLE
Aplicação: Weather-aplication 

### ISSUE THREAD

**Issue by CamiloMeassiMacoris** [roger-melo-treinamentos/curso-de-js-roger-melo#3897]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/CamiloMeassiMacoris/weatherApp

### Maiores dificuldades durante a implementação

refatoração do código em funções de responsabilidade Única.

### Menores dificuldades durante a implementação

Manipulação do DOM

**Comment by Roger-Melo** [comment]
Olá Camilo. 

Devido ao que conversamos no whatsapp, irei desconsiderar essa issue e fechá-la =)
