### ISSUE TITLE
Aplicação:Todo list

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#3898]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/EneasFeynlinus/toDo-Application.git

### Maiores dificuldades durante a implementação

processo de mudança da manipulação do elemento i<icon> do DOM para deletar os toDos utilizando os datasets para ter o mesmo controle atraves das classes personalizadas. 

Processo de refatoraçao da filtragem dos toDos.

### Menores dificuldades durante a implementação

referenciando os elementos do DOM.

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @EneasFeynlinus!

Você pode baixar a análise de seu Todo [neste link](https://drive.google.com/file/d/1RcYanvIfNRxYTFXWFU6wEjNpvoBp45ds/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by EneasFeynlinus** [comment]
Bom dia Mestre @Roger-Melo  primeiramente, desculpe a demora para responder. Que aula excelente assisti duas vezes sua explicação e algumas partes 5 vezes pra pegar o conteúdo kkk. Que aula excelente!!

Sim professor, realmente eu assisti a aula sobre  o relógio e realmente elas são depois do todo-list. Realmente não tinha me atentado a esse e-mail com relação as datas das aplicações, vou procurar e ler para acompanhar corretamente o curso, peço desculpas pelo mal entendido professor.

Muito obrigado pelo adendo em utilizar mais os atributos dataset, não tinha isso em mente.

Sobre a toLocalLowerCase, eu não conhecia esse método, acredito que não tenha visto quando o Visual code auto completou, falha minha em ver esse erro, realmente neste caso minha intenção era o uso do toLowerCase(). Muito obrigado pelos feedbacks, foram magníficos e muito engrandecedores e realmente o toLocaleLowerCase() que o visualStudio autocolocou e eu não percebi, causou grandes problemas na filtragem que não percebi durante a programação e re-fatoração do código, percebi que preciso melhorar os testes também hehehe.

Muito obrigado pela ajuda na fatoração do removeTodo com o trashWasClicked ficou show seu método como sempre. Muito legal seu comentário com relação a colocar a manipulação do DOM na hora de referenciar o todo com o mesmo valor de classe dentro do bloco do IF, realmente é algo muito importante a atentar, já que economiza memoria e processamento, fascinante.

Eu achando que dividir os filtro dos todos em 4 funções de responsabilidade individual seria bacana e estava ok, então vem o Mestre e da uma aula magnifica sobre transformação de dados utilizando destructuring e sinergia entre os métodos de array. Não tinha lido sobre transformação de dados ainda, me lembrou um pouco as suas aulas de destructuring sobre pegar valores de um objeto e armazenar em variáveis. Que aula magnifica, aprendi muito, mudei a visão com relação a transformar dados mais conhecimento para a base da construção da fluência em java script, eliminou varias linhas do código que havia escrito, e abordou de uma maneira bem intuitiva e didática os conceitos de destructuring os métodos map e for each utilizados em sinergia.

Muito obrigado pela ótima aula e pelos feedbacks para evoluir Mestre .

Desde já grato,

Best regards.
