### ISSUE TITLE
Etapa 3, Exercícios- Aula 03

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#39]
Roger, estou vendo as aulas e lendo a documentação da MDN, que é como você pediu
no CJRM.

Mais percebi que no primeiro modulo você explica sobre string, e logo abaixo do vídeo
tem o link sobre string para a documentação do JavaScript na MDN.

Mais na etapa 2 em diante, já não tem mais os links da MDN, é para agente procurar ou você poderia colocar?
Isso ia me ajudar nos estudos. Por exemplo eu trabalho com jquery sempre olho a documentação lá quanto tenho tempo,
mais vou no mais rápido google e stackOverflow, aí peguei um vício de copiar código pronto.

Na aula de array fui procurar sobre array no MDN e li do começo ao fim antes de iniciar o exercício 03, e me ajudou bastante a compreender mais.

Por exemplo o link: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Arrays
 
Acho que mais uma sugestão que dúvida :)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Valeu pela sugestão =)

De fato, nas primeiras aulas eu não coloquei os links da documentação abaixo dos vídeos.

É um cuidado com os que estão no estágio baby na linguagem.

Geralmente, quem está neste estágio pode se desfocar muito facilmente ao ler a documentação e ver vários links nos parágrafos, que levam à assuntos mais avançados.

À medida em que os conteúdos do treinamento vão ficando mais densos, você notará, gradativamente, mais links abaixo dos vídeos.

Esse cuidado de não deixar os links nos vídeos iniciais é apenas uma coisa que eu acho que pode acontecer. Não é nada baseado em estudos científicos ou algo do tipo. É só um receio que tenho de, acidentalmente, desfocar o aluno com conteúdos que não necessariamente vão ajudá-lo nos momentos iniciais.

Sacou mais ou menos a ideia? =)

**Comment by Roger-Melo** [comment]
Ednaldo, vou fechar a issue por agora, mas se tiver qualquer dúvida, é só abrir uma nova issue =)
