### ISSUE TITLE
Resumo da Aula Exercício 01/01 da etapa 01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#390]
Comecei digitando as constantes no app.js, mas deixava como comentário, então ao abrir o console no browser,e repetindo o processo de digitação das constantes, ocorria um erro de definição de variável. Então a partir do momento que 'descomentarizei' as 'const' o console imprimiu os resultados corretos.  No site http://whathappenedinmybirthyear.com/ mostrou muita coisa interessante:
--> 'Degradê Dinâmio' ao iniciar a contagem regressiva a tela vai escurecendo;
-->  Texto inserido letra por letra, junto com imagens, no sentido da leitura;
-->  Várias palavras grifadas usadas com link;
   O interessante é imaginar o tamanho do repositório para criar um arquivo completo com as informações de cada ano; A 
mesma base textual com diferenças pontuais para cada ano:
-->  Premiação do Oscar
-->  Prêmio Nobel
-->  Geopolítica
-->  Invenções mais importantes
-->  Música e Entretenimento

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @marcosyoggy! 🚀
