### ISSUE TITLE
Resumo da Aula While loop e exercicios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#3902]
WHILE LOOP

**while**

A declaração `while` cria um laço que executa uma rotina específica enquanto a condição de teste for avaliada como verdadeira. A condição é avaliada antes da execução da rotina.

É muito parecida com o `for`, contudo, muda somente a sintaxe.

**Sintaxe**
```javascript
while (condição){
	rotina
}
```

```javascript
// Códigos da aula
// while loop

for (let i = 0; i < 5; i++) {
    console.log(`Dentro do loop: ${i}`)

}

// let i = 0
// while (i < 5) {
//     console.log(`Dentro do loop: ${i}`)
//     i++
// }

const names = ['Jobs', 'Hopper', 'Turing']
let i = 0

while (i < names.length){
    console.log(names[i])
    i++
}
```

**Comment by Roger-Melo** [comment]
Show @lucian-bonifacio. Vamo que vamo, rumo à fluência! 🙌
