### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03 da etapa 

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3907]
**Mais eventos do DOM**
```Event copy``` -> capturamos a referência do parágrafo que contém a "class="copy-me"" e adicionamos um evento de cópia. Ou seja, toda vez que o texto é copiado na página, ele imprime que o texto foi copiado.

```js
const paragraph = document.querySelector('.copy-me')

paragraph.addEventListener( 'copy', () => {
    console.log('Texto copiado!')
})
```

```Event mousemove``` -> capturamos a referência da <div> que contém a "class=".box"" e adicionamos este evento que, quando o mouse se movimenta dentro do box,. Ou seja, toda vez que o texto é copiado na página, ele imprime no console as coordenadas do mouse.
```js
const div = document.querySelector('.box')

div.addEventListener( 'mousemove', event => {
    console.log(event.offsetX, event.offsety)
})
```
Observe que as propriedades ```.offsetX``` e ```.offsetY``` retornam as coordenadas verticais e horizontais.
Para mostrar as informações na página, basta pegar a referência do texto da <div> e atribuir o ```.offsetX``` e ```.offsetY``` para ele.
Veja:
```js
const div = document.querySelector('.box')

div.addEventListener( 'mousemove', event => {
    div.textContent = `X ${event.offsetX} | Y ${event.offsetY}`
})
```

```Event wheel``` -> Podemos atribuir este evento na página toda. Sua função é informar o quanto a página foi rolada para cima ou para baixo através do scroll do mouse.
```js
document.addEventListener('wheel', event => {
    console.log(event.pageX, event.pageY)
})
```

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
