### ISSUE TITLE
Aplicação: [Quiz app]

### ISSUE THREAD

**Issue by muritadb** [roger-melo-treinamentos/curso-de-js-roger-melo#3908]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém features da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/muritadb/quiz-app

### Maiores dificuldades durante a implementação

Ola, eu tive dificuldades na logica da pontuação, setInterval() e com o bootstrap.
 - com a logica não estava entendendo a condição para poder pontuar.
 - com o setInterval(), não conseguia entender como parar, usar o clearInterval()  revendo a aula e lendo a documentação, entendi como usar.
 - com o bootstrap era questão da pontuação, não sabia como apresentar, revendo a aula entendi como usar o remove() para remover a classe 'd-none'.

### Menores dificuldades durante a implementação

* trocar a paleta de cores de site.
* usar o flex box com bootstrap.
* usar componentes do bootstrap.
* usar evento de submit no botão .

**Comment by Roger-Melo** [comment]
Olá @muritadb!

Apenas quem se matriculou até às 8:15h tem o bônus de análise de aplicações, e pelo que vi, sua matrícula foi feita às 08:36h.

O que vc pode fazer neste caso é dar uma olhada nas [análises que fiz dessa aplicação](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=label%3A%F0%9F%94%A5aplica%C3%A7%C3%A3o+quiz+is%3Aclosed). Elas são públicas =)

E claro, qualquer dúvida que tiver, é só dar o toque =)
