### ISSUE TITLE
Resumo da Aula o que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3909]
## Funções   

 Um dos principais conceitos em uma linguagem de programação. Faz parte do tipo de dado _object_. A principal função é permitir a criação de um bloco de código que podemos executar quando e quantas vezes quisermos. 

Utilizamos uma função para evitar a repetição de código. Se tivermos um fato que é recorrente na nossa aplicação, exemplo, a impressão de determinada mensagem quando o usuário aperta um botão, podemos colocar essa mensagem dentro de uma função e chamá-la quando for necessário, assim evita-se a repetição de código. 

As funções podem receber valores, processá-los e retornar um resultado.

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
