### ISSUE TITLE
Resumo da Aula O método reduce - Aula 01-04

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3926]
O método reduce() ele e bem mais versátil que os outros métodos, pois baseado no array original conseguimos reduzir o array em algum outro tipo de dado , number , string , objeto literal , ou em um novo array , sendo do mesmo tamanho ou não . Sempre lembrando que o reduce precisa retornar um valor.

const phaseScores = [
  { name: 'Vinicius Costa', score: 337 },
  { name: 'Roger Melo', score: 43 },
  { name: 'Alfredo Braga', score: 234 },
  { name: 'Pedro H. Silva', score: 261 },
  { name: 'Ana Paula Rocha', score: 491 },
  { name: 'Vinicius Costa', score: 167 },
  { name: 'Roger Melo', score: 137 },
  { name: 'Alfredo Braga', score: 135 },
  { name: 'Ana Paula Rocha', score: 359 },
  { name: 'Pedro H. Silva', score: 133 }
]

const scoreOfVinicius = phaseScore.reduce((acc , score ) => {
      if(score.name === 'Vinicius Costa'){
           acc + score.score 
     }
return acc 
} , [])
console.log(scoreOfVinicius)

**Comment by Roger-Melo** [comment]
Excelente @Sansanoski, rumo à fluência! 🎯
