### ISSUE TITLE
Duvida sobre Reduce()

### ISSUE THREAD

**Issue by muritadb** [roger-melo-treinamentos/curso-de-js-roger-melo#3928]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1012887

### Descreva a dúvida

Ola boa tarde, na correção dos exercicios desta aula, no exercicio 04 onde pede pra exibir o nome dos jogos no console, Você resolve o exercicio com o reduce, mas eu tinha resolvido o mesmo usando o map(), segue codigo:

```js
const showGamesIntoTemplate = ({ name }) => {
  console.log(` - ${name}\n`)
}
const showGameNames = cart.map(showGamesIntoTemplate)
```
Eu entendi que o reduce reduziu a estrutura de array de objetos a uma string mas para mim ainda tenho uma ideia de que o reduce é para manipulação de numeros e na hora de resolver só lembrei do map. Tipo pra mim não ficou claro o porque de usar o reduce ao invés do map.  Talvez seja uma duvida boba, mas poderia explicar o reduce?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @muritadb.

> ### mas eu tinha resolvido o mesmo usando o map(), segue codigo

A função de callback de `map`, `filter` ou `reduce` sempre deve retornar um valor. Isso foi falado nas aulas em que esses métodos foram apresentados =)

Na forma que vc fez, ao invés de retornar valor o console.log foi executado. Se a função do map não retornar valor, a expressão `array.map(nomeDaFuncao)` retorna um array de undefined. Vc pode comprovar isso se logo abaixo da declaração da `showGameNames` inserir um console.log que exibe o valor dela =)

Lembre-se: o map deve ser usado quando, baseado em um array, vc precisa retornar um novo array com a mesma quantidade de itens do array original. `showGameNames` está armazenando um array, e não uma string.

---

> ### Eu entendi que o reduce reduziu a estrutura de array de objetos a uma string

No exemplo que vc deu, o array não foi "reduzido" à uma string. Pelos motivos que falei acima.

---

> ### para mim ainda tenho uma ideia de que o reduce é para manipulação de numeros 

Não faria sentido mostrar muitos casos de uso do reduce de uma só vez. Iria mais confundir do que ajudar. Vc está nas aulas em que o reduce está apenas sendo introduzido. 

Vc ainda verá muitos casos de uso dele no treinamento, à medida em que for progredindo, e não de uma só vez =)

Na própria correção do exercício 04, vc viu um exemplo de que o reduce pode ser usado para "reduzir" o array original a qualquer valor (string, no caso do exercício 04).

---

> ### e na hora de resolver só lembrei do map

Vc deve lembrar do map na situação que mencionei acima e na aula: quando, baseado em um array, vc precisa retornar um novo array com a mesma quantidade de itens do array original.

---

> ### Talvez seja uma duvida boba, mas poderia explicar o reduce?

Recomendo que veja novamente a aula em que o reduce foi introduzido. 

"Explicar o reduce" é muito vago. Preciso que vc faça uma pergunta específica sobre ele, pq explicar o método seria basicamente repetir o que foi mostrado na aula. Seria mais eficiente vc revisar e depois disso, se houver alguma dúvida específica, pode perguntar que te ajudo, ok? =)

**Comment by muritadb** [comment]
Ola Roger, boa noite, irei revisar a aula novamente como você sugere, obrigado :)

**Comment by Roger-Melo** [comment]
Show! Vou fechar essa issue, mas no que precisar, é só abrir uma nova =)
