### ISSUE TITLE
Resumo da Aula retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3931]
## Retornando valores

 

Vimos que podemos passar um valor para função para que esse valor seja processado e exibido. Mas haverá momentos que precisaremos que esse valor  retorne para passar por um novo processo e só aí então, ser exibido na tela. 

```js
const double = function(number) { 

    const doubleResult = number * 2 

    return doubleResult 

} 

let result = double(8) 

Console.log(result) // -> resultado 16 
```
 

Neste exemplo passamos o valor 8 como argumento para o parâmetro number da função double. Dentro da função o valor de number é multiplicado por 2 e guardado na variável doubleResult. Como doubleresult é uma variável local, se tentarmos utilizá-la fora da função, será exibido um erro. Para usarmos o seu valor fora da função é necessário retornar o seu valor através da palavra-chave return. Ao utilizarmos o return o valor que está em doubleresult é retornado para quem invocou, double(). Para podermos utilizar o valor que retornou, precisamos guardar em outra variável, que neste caso foi a result. 

 ```js
const showResult = function(value) { 

    console.log (`O resultado é ${result}`) // resultado -> 6
} 

const double = function(number) { 

    const doubleResult = number * 2 

    return doubleResult 

} 

let result = double(8) 

result -= 10 

showResult(result) 
```
 
No exemplo acima, o valor que retornou passou por mais um processo antes de ser exibido. Utilizamos uma função para exibir o resultado final. Assim, destinamos um local para quando quisermos exibir algo, tirando a necessidade de repetir código quando precisamos exibir algo.

**Comment by Roger-Melo** [comment]
Excelente @MarioFilho1, rumo à fluência! 🎯
