### ISSUE TITLE
Resumo da Aula O que são objetos? - 01 - 02 da etapa 04

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#3936]
Em programação, o conceito de objeto pode ser definido como o grupo de propriedades e ações que definem 
as caracteristicas e possibilidades de algo. Para evitar que fique muito vago, vou me apoiar no exemplo que o Roger
usou: o objeto "Usuário". Esse tem como propriedades um nome, um email, uma senha. Cada uma dessas 
propriedades serão únicas e estarão realcionadas apenas ao usuário que as detém. Já as ações (métodos)
que este mesmo usuário pode realizar dentro de uma aplicação, uma vez validada sua legitimidade através 
da confiramção da exclusividade de suas propriedades, são mais abrangentes e totalmente controladas pelo
desenvolvedor da aplicação. Aí o desenvolvedor age como um demiurgo, atribuindo asas e penas 
a alguns, o que lhes possibilita que voem, ou, para utros, tolhendo-lhes as pernas, impondo que rastegem 
(foi mal Roger, mas não resisti...). 
E analisando com mais atenção o exemplo do usuário, acabo percebendo que propriedades quase invariavelmente
são substantivos, enquanto métodos são verbos. Um truque semântico que, aparentemente, também serve para
a linguagem Javascript.

**Comment by Roger-Melo** [comment]
Excelente @VitorPeixotoDev, rumo à fluência! 🎯
