### ISSUE TITLE
Aplicação: Quiz Iterativo

### ISSUE THREAD

**Issue by tonymatheus** [roger-melo-treinamentos/curso-de-js-roger-melo#3940]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/tonymatheus/NaruQuiz

### Maiores dificuldades durante a implementação

- Refatorar o código de forma a deixar mais conciso , fiquei com a sensação de que talvez minha separação por funções tenha deixado meu código mais verboso.
- Em um certo momento quando fui implementar a lógica da animação entrei em loop infinito no counter da tela , após observar bem percebi que não estava atribuindo valor ao counter .

### Menores dificuldades durante a implementação

- Aplicar estilos simples com bootstrap 
- Entender o objetivo da aplicação

**Comment by Roger-Melo** [comment]
Olá @tonymatheus.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by tonymatheus** [comment]
Ok Roger, obrigado!!

**Comment by Roger-Melo** [comment]
Olá @tonymatheus!

Você pode baixar a análise de seu Quiz [neste link](https://drive.google.com/file/d/1vpUlGcjOO462S98WT742F__Cp824-VHw/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by tonymatheus** [comment]
Salve Roger muito obrigado pela análise e dicas, eu  realmente deixei passar o time ali do envio da  aplicação foi por descuido mesmo, quando voltei ao email novamente percebi que mandei num momento errado e já tinha visto a aula, vou me atentar quanto a isso pra que não acontecer nos próximos desafios. Apesar dos fogos de São joão kkk sua explicação ficou bastante clara, mais uma vez muito obrigado , qualquer dúvida eu entro em contato.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
