### ISSUE TITLE
Resumo da Aula Tipos de referência vs Tipos primirivos - 03-04 da etapa 04

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#3944]
O conceito parece complexo num primeiro momento, mas com atenção é fácil de pegar, ao menos seus
princípios básicos. Stack é o nome do tipo de memória que armazena os tipos primitivos. É um memória 
de mais fácil acesso ao compilador - estou arriscando aqui, espero não estar falando bobagem. - embora
seja uma memória menor e, digamos, mais simplificada. Uma metáfora seria nossa memória de curto prazo
que nos permite armazenar um senha numérica de seis dígitos pos 30 segundos até que tenhamos, por 
exemplo, utilizado os seis dígitos para validar um email. Porém, 30 minutos depois, já não temos a menor ideia da 
sequência numérica exigida.  Já a memória do tipo heap é maior, mais complexa e, consequentemente, mais lenta.
Para mais uma metáfora, diria que a memória heap poderia se assemelhar ao certo método A.T.E.R, que "talvez"
o único leitor certo desse resumo conheça... Exige mais tempo, espaço e atenção, porém tem a capacidade de se
manter viva e ativa por muito mais tempo. 

 - Do pointer:
   Ele vai apontar para o tipo não primitivo no heap. Portanto, ao tentar criar uma cópia de um tipo não
   primitivo, o que se está fazendo, na verdade, é reendereçar uma requisição para um mesmo valor.
   Apenas os tipo primitivos são capazer de ser realmente "clonados", digamos; uma entidade que, num 
   primeiro momento será absolutamente identica a sua matriz, porém, capaz de ser alterada de forma 
   individual e ilimitada sem que essas alterações interfiram em sua matriz.

**Comment by Roger-Melo** [comment]
Boa @VitorPeixotoDev, rumo à fluência! 🔥
