### ISSUE TITLE
Dúvida sobre requisições json internamente

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#3946]
### Etapa da aula

11

### Nome da aula

Fetch API

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1332937

### Descreva a dúvida

@Roger-Melo

Se eu tenho um arquivo JSON contendo os objetos da aplicação, pra eu usar os dados eu preciso criar uma requisição e parsear os dados para objetos javascript, certo?

depois disso, eu preciso tratar a requisição ou por o arquivo estar internamente na aplicação a requisição nunca vai falhar ?

**Comment by dracoalv** [comment]
Wow, como sempre, resposta mais que satisfatória, muitíssimo obrigado Roger!

**Comment by Roger-Melo** [comment]
Legal =D

No que precisar, é só abrir uma nova issue =)
