### ISSUE TITLE
Resumo da Aula funções vs Métodos - Aula 02-03da etapa 03

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3947]
## Funções vs Métodos   

Funções -> Bloco de códigos que executam alguma ação e podem ser invocadas em qualquer ponto do código. 

Métodos -> Em essência é uma função, o que diferencia é a forma como invocamos e onde ele é declarado. Os métodos são funções que estão associadas à objetos ou tipos de dados como strings. Os métodos são criados num objeto ou em um tipo de dado em si, já as funções são criadas sozinhas. 

Quando queremos chamar uma função colocamos o nome dela e os parênteses para invocá-la.  

```js
Const sayHi = ( ) => ‘oi’ 

Const greet  = **sayHi( )** 

Console.log(greet) 
``` 

Já para invocar um método é necessário referenciar um valor e utilizar a notação do ‘. ’ e logo após inserir o nome do método e os parênteses para que ele possa ser invocado. 

```js
 Const name = ‘mario’ 

name.toUpperCase( ) 
```
Para transformar o valor da variável _name_ em maiúscula foi necessário utilizar a notação do ‘.’ e invocar o método através dos parênteses.

**Comment by Roger-Melo** [comment]
Boa @MarioFilho1, rumo à fluência! 🔥
