### ISSUE TITLE
Resumo da Aula setInterval() e animação da pontuação - Aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#3956]
https://github.com/marcosyoggy/slide-resume
https://marcosyoggy.github.io/slide-resume/
https://slide-resume.netlify.app/

**Comment by Roger-Melo** [comment]
Show @marcosyoggy. Vamo que vamo, rumo à fluência! 🙌
