### ISSUE TITLE
Uso da propriedade 'IsDayTime' não está funcionando bem

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#3957]
### Etapa da aula

12

### Nome da aula

Inserindo na interface os ícones e imagens - Aula 02-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1443475

### Descreva a dúvida

Bom dia!

Então, estava seguindo a aula e em certo momento, você indica para utilizarmos a propriedade 'IsDayTime' da API para podermos saber se está de dia ou de noite na cidade pesquisada. Assim, inseririamos a imagem .svg correspondente.

Porém, quando fui implementar essa função na aplicação, a propriedade não funciona como o mostrado no vídeo. Por exemplo, ela indica apenas noite, sem variação nas cidades que de fato estão de dia. Tentei contornar esse problema por meio do operador lógico !, mas não resolveu, ela indica apenas dia e não troca para noite nunca.

![Print1S](https://user-images.githubusercontent.com/82729897/175324167-9ccb58ac-a292-4b75-9012-9aa9d5bc5d10.png)
![Print2S](https://user-images.githubusercontent.com/82729897/175324184-0aef7078-5192-435f-8e1b-0fd87d3269f0.png)

Peço por gentileza que me ajude a descobrir o que está causando esse problema, se é algum erro de código meu ou algo que deixei passar.

Link do repositório da aplicação: https://github.com/MivlaM/Meu-WeatherApp

É isso, agradeço desde já.

@Roger-Melo

**Comment by MivlaM** [comment]
Oi @Roger-Melo,

Entendido, esse repositório que disponibilizei não é o definitivo, vou me certificar de que o index.html esteja na raiz do repositório da análise.

---

Bem, `isDayTime` está armazenando `undefined` porque ele não tem o que armazenar. Isso está acontecendo porque eu não coloquei o nome correto para a propriedade. O nome correto é `IsDayTime` que é diferente da minha versão em camel case. Depois que percebi isso e fiz alguns ajustes no código, a implementação da funcionalidade está funcionando como o necessário.

No mais era isso mesmo, agradeço pela ajuda =)

**Comment by Roger-Melo** [comment]
Isso mesmo. Como JS é case sensitive, `IsDayTime` com "I" maiúsculo é diferente de `isDayTime` com "i" minúsculo. Como não existe propriedade `isDayTime` com "i" minúsculo no objeto, a const com esse nome que foi declarada no destructuring armazenou `undefined` =)

@MivlaM
