### ISSUE TITLE
Adicionando to-dos - Aula 01-03

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3958]
Nessa aula aprendemos sobre o método reset() . Esse método ele e usado para restaurar os valores dos elementos de um formulário. E lembrado que o valor de um input de um form, e uma string vazia

**Comment by Roger-Melo** [comment]
Show @Sansanoski. Vamo que vamo, rumo à fluência! 🙌
