### ISSUE TITLE
Resumo da Aula o método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3965]
## Callbacks e ForEach 

Callbacks são funções que são passadas como argumento da invocação de outras funções ou métodos. 

 ```js
const myFunc = (callback) => { 

  const value = 77 
 

  callback(value) 

} 
 
myFunc((number)=> { 

  console.log(number) 

}) 
```

Neste exemplo invocamos a função _myFunc_ passando como argumento uma função. Essa função tem a finalidade de imprimir um valor que será enviado como argumento para o parâmetro  _number_ 

 O parâmetro _callback_ armazena a função. Dentro do bloco de código foi declarada uma variável _value_ que recebe o valor 77. A variável _value_  funciona como argumento na invocação _callback(value)_, que passará seu valor para o parâmetro _number_ da função depositada em _callback_. 

 

O ForEach é um método que permite que façamos interações sobre um array utilizando uma função de callback na invocação do método. 

```js
Const socitalNetwork = [‘youtube’, ’facebook’, ’instagram’,  ‘twitter’] 

socialNetwork.forEach(( ) = > { 

Console.log( ‘Minhas mídias sociais’) 

}) 
```
Neste exemplo o conteúdo do console.log será exibido 4 vezes, uma para cada item do array.  A fução de callback dentro do forEach pode receber três parâmetros: 

- 1º O item atual do array que está sendo iterado; 

- 2º O index do item atual; 

- 3º O array que está sendo iterado . 

 
```js
Const netWork = [‘youtube’, ’facebook’, ’instagram’,  ‘twitter’] 

SocialNetwork.forEach((socitalNetwork, index, array ) = > { 

Console.log(socitalNetwork, index, array) 

}) 
```

Os nomes utilizados nos argumentos são opcionais. 

Uma outra vantagem de usar o forEach em relação ao for, é a possibilidade de desacoplar a declaração da função. Isso permite uma escrita de código mais legível e a possibilidade de reutilização da função, se necessário, em outro lugar do código. 

 
```js
Const netWork = [‘youtube’, ’facebook’, ’instagram’,  ‘twitter’] 
 

Const logArrayInfo = (socitalNetwork, index, array ) => { 

Console.log(socitalNetwork, index, array) 

} 

SocialNetwork.forEach(logArrayInfo) 
```

**Comment by Roger-Melo** [comment]
Boa @MarioFilho1, rumo à fluência! 🔥
