### ISSUE TITLE
Resumo da Aula Factory functions e composição de objetos - 03-09 da etapa 14

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#3969]
Factory function é qualquer função que não seja uma classe, construtor, função construtora, mas que retorne um novo objeto. Em Js, qualquer função pode retornar um objeto e, quando ela não obriga o uso de new em sua declaração, ela é uma factory function.
Sua vantagem é permitir compor/criar objetos de forma mais simples, enxuta. 
Para criar métodos e propriedades privadas em uma factory function, basta apenas criar tais métodos/propriedades dentro do objeto dela, desta forma, não estarão disponíveis fora dela por causa do escopo.
```js
const createUser = (name, email) => {
    let counter = 0 // variável privada, pois foi declarada dentro do escopo da função
    return {  // cria um objeto com propriedades de nome name e email usando o shorthand property names
        name,
        email,
        incrementCounter: () => ++ counter
    }
}
```
Para cada objeto criado, o método nele contido se transforma em uma closure, isto é, por causa do escopo léxico (escopo que envolve a declaração do método), o contador de cada objeto irá “obedecer seu respectivo escopo, não interferindo uns nos outros, pois a cada invocação do método, para não haver conflito, são criados contadores diferentes que ocupam espaços diferentes na memória.
A maioria dos códigos atuais muito provavelmente irão utilizar classes para a implementação de objetos, no entanto, isto cria uma série de dependências e trabalho para uma possível necessidade de refatoração. Outra desvantagem do uso de classes é que não temos opção de escolha sobre quais propriedades e métodos desejamos que um objeto herde de outro.
Para contornar este problema, precisaríamos criar um objeto não por herança, mas sim por composição, criando objetos diferentes que armazenam métodos diferentes e, na criação de um novo objeto, atribuímos a ele os métodos desejados.
```js
const a = {metodo1}
const b = {metodo2}
const c = {metodo3}
const obj = {... a, ... c} // objeto recebeu apenas os métodos a e c
```
Factory functions evitam que “caiamos na tentação” de usarmos e abusarmos de níveis de heranças, possibilita uma refatoração mais simples apenas usando funções e diminui a necessidade de uso do `this`, tornando o código mais previsível. Uma desvantagem seria a micro performance (é um pouco mais lenta que classes e funções construtoras), mas nada que impacte demasiadamente (performance percebida), a não ser que nos preocupemos com micro-otimização da aplicação.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
