### ISSUE TITLE
Etapa 11, nome do vídeo: Correção dos exercícios da aula 02 da etapa 11 - Aula 03-01

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#397]
Oi, Roger. 

Nessa correção de exercício você utilizou uma let para criar o objeto person, já que ele teria alterações. 

Quando eu fiz os exercícios acabei usando const, acho que por força do hábito. 

Por que objetos podem ser alterados mesmo quando declarados como consts?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Hamilton.

Consts não garantem imutabilidade. Um objeto atribuído a uma const pode ter suas propriedades modificadas. O mesmo vale para itens de arrays (por que arrays são objetos).

Uma const apenas impede que um novo valor seja reatribuído para o identificador `const`.

Ou seja, objetos são mutáveis por padrão e `const` não define imutabilidade, apenas evita reatribuição.

O uso de const é uma convenção para indicar, visualmente, que eu não vou mudar aquele valor. O valor que aquela const armazenar vai permanecer o mesmo em todo o decorrer da aplicação. Já quando quero indicar que o valor vai ser modificado, uso `let`.

Devo falar especificamente sobre imutabilidade mais à frente no treinamento, quando mostrar programação funcional =)

Ficou mais claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Ficou sim, obrigado!

**Comment by Roger-Melo** [comment]
Legal @Hamiltonspjunior. Já que ficou mais claro vou fechar a issue, mas quando surgirem dúvidas, é só abrir uma nova =)
