### ISSUE TITLE
Aplicação: [Weather-App]

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#3970]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/MivlaM/Meu-WeatherApp

### Maiores dificuldades durante a implementação

-> Enquanto eu testava a aplicação, tive um problema com a API, acho que cheguei no limite de usos que era permitido diariamente, mas achei a solução por meio de umas issues passadas aqui no repositório.

-> Consegui fazer umas refatorações nas funções, mas acredito que ainda teria espaço para fazer mais (com o if da const IsDayTime, por exemplo).

### Menores dificuldades durante a implementação

-> Nomenclatura das variáveis

-> Manipulação do DOM

**Comment by Roger-Melo** [comment]
Olá @MivlaM.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @MivlaM!

Você pode baixar a análise de sua Weather Application [neste link](https://drive.google.com/file/d/1-9G685BY_qehhcyCISuaG0WMDytp11-O/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
