### ISSUE TITLE
Duvidas sobre o Firebase

### ISSUE THREAD

**Issue by Roger-Melo** [roger-melo-treinamentos/curso-de-js-roger-melo#3975]
### Etapa da aula

15

### Nome da aula

Observando o estado de autenticação do usuário - Aula 03-20

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/4941199

### Descreva a dúvida

Olá @FelipeD4ntas e @andersoncsiqueira. 

Só agora, acidentalmente vi a discussion. Estou trazendo a discussion aqui para as issues, pois discussions serão desativadas.

O local para tirar dúvidas é aqui nas issues, como recomendei na aula [A aula mais importante do CJRM](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/2186928), ok? =)

Print da pergunta e transcrição abaixo (para indexação da ferramenta de busca).

Vou deixar minha resposta no próximo comentário abaixo.

![duvidas-sobre-o-firebase](https://user-images.githubusercontent.com/29297788/176045745-2c7d676c-e675-42e9-9e42-59d822f8accb.jpg)

> Boa noite. Cheguei na etapa 15 do treinamento, e me bateu uma dúvida sobre o firebase, é possível fazer uma collection no firestore pra cada usuário? Pois mesmo logando com um usuário diferente na aplicação os mesmos dados adicionados enquanto tinha outro usuário logado, são retornados do firestore.

> @Roger-Melo Compartilho a mesma dúvida que o colega @FelipeD4ntas =D

**Comment by Roger-Melo** [comment]
Sim, vc pode criar um collection em que cada document desse collection contém informações específicas de um usuário. Essas informações vc já tem quando o usuário loga na aplicação =)

Se ainda não tiver chegado nas aulas sobre autenticação, logo logo vc chega.

Uma das informações que vc pode inserir como ID do próprio document do usuário é o ID de usuário (`uid`).

Com o `uid`, vc consegue setar nas regras de segurança do firestore quem pode ler ou escrever no banco =)

Provavelmente, isso ainda será mostrado nas próximas aulas, mas enquanto isso, vou deixar aqui a referência da doc onde vc encontrará como fazer isso através das regras de segurança do firestore.

Se surgir qualquer dúvida, pode perguntar =)

- [Fix insecure rules - Firebase Docs](https://firebase.google.com/docs/firestore/security/insecure-rules)

@FelipeD4ntas e @andersoncsiqueira

**Comment by andersoncsiqueira** [comment]
> Uma das informações que vc pode inserir como ID do próprio document do usuário é o ID de usuário (uid).
>Com o uid, vc consegue setar nas regras de segurança do firestore quem pode ler ou escrever no banco =).

Perfeito, vou tentar implementar =D

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
