### ISSUE TITLE
Resumo da Aula Uma introdução ao Bootstrap - Aula 01-02 da etapa 07

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3977]
**Bootstrap** -> É uma biblioteca **CSS/JAVASCRIPT** de componentes Front-end.

Como funciona?
1º Passo -> Acessar o site [getbootstrap.com](getbootstrap.com)
2º Passo -> Copiar a tag link abaixo:
```html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
```
3º Passo -> **Colar** dentro do ```<head>``` do arquivo 'html'
Ter a tag ```link``` dentro do html significa que podemos usar as classes 'CSS' disponíveis no Bootstrap.

E como utilizamos essas classes?
4º Passo -> Se no Site clicarmos em 'DOCs':
![Bootstrap_01](https://user-images.githubusercontent.com/58309283/176057328-1e6c0b45-a369-4cff-8ec6-99c604a2a252.PNG)

5º Passo -> Depois em 'UTILITIES'
![Bootstrap_02](https://user-images.githubusercontent.com/58309283/176058885-a0d48ee7-7401-4efc-81ff-638d725120d1.PNG)

6º Passo -> E em 'COLORS'
![Bootstrap_03](https://user-images.githubusercontent.com/58309283/176058959-d8f03e05-4d30-451e-a8bd-2810cb309a36.PNG)

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
