### ISSUE TITLE
Aplicação: [TO DO LIST]

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#3986]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Sansanoski/toDoList/tree/master

### Maiores dificuldades durante a implementação

Fatoração , dar nomes as variáveis. 

### Menores dificuldades durante a implementação

manipulação do DOM , uso de condicionais , uso de métodos e funções

**Comment by Roger-Melo** [comment]
Olá @Sansanoski.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Sansanoski** [comment]
perfeito, obrigado

**Comment by Sansanoski** [comment]
Professor boa noite, só um detalhe que notei foi : a aplicação em um aparelho mobile não consegue adicionar o to-do na lista de to-dos , porque não existe um botão para fazer isso. Claro que isso seria um feature futura para possível melhorias.

**Comment by Roger-Melo** [comment]
Excelente observação @Sansanoski! Anotei aqui para possíveis ajustes =)

**Comment by Roger-Melo** [comment]
Fechei a issue sem querer, abri novamente 😅

**Comment by Roger-Melo** [comment]
Olá @Sansanoski!

Você pode baixar a análise de seu Quiz [neste link](https://drive.google.com/file/d/19MAK9PGWfP2abKYDWlQ_kioX36qXlHgx/view?usp=sharing).

Se houver qualquer dúvida, é só dar o toque =)

**Comment by Sansanoski** [comment]
Boa tarde professor!! Excelente revisão  do meu código. É incrível como consegue deixar o código mais legível e enxuto. Obrigado por me mostrar a transformação de dados e como eu posso usar a meu favor. Uma coisa que eu fico em duvida é por exemplo, ate que ponto a estratégia que eu vou usar no código vai funcionar. O exemplo do Event.parent , se mudasse a semântica do HTML o código iria quebrar certo, ai no caso foi usado a transformação de dados , ate que ponto da aplicação essa estratégia funcionaria. Claro essa minha duvida e para aplicações maiores . Espero que tenha entendido minha duvida. No mais muito obrigado

**Comment by Roger-Melo** [comment]
> ### ate que ponto a estratégia que eu vou usar no código vai funcionar

Primeiro vc faz, depois vc melhora. 

Esse é um princípio que vc deve carregar durante sua carreira de desenvolvedor. 

Primeiro vc faz funcionar. 

Depois, conforme for praticando e adquirindo mais proeficiência na linguagem, vc pode voltar e ver o que pode ser melhorado no código. 

---

> ### O exemplo do Event.parent , se mudasse a semântica do HTML o código iria quebrar certo, ai no caso foi usado a transformação de dados , ate que ponto da aplicação essa estratégia funcionaria

São dois problemas diferentes. 

Evitar `parentElement` deixa a aplicação menos frágil contra mudanças de marcação HTML.

Já a técnica de transformação de dados foi usada para simplificar o código. Eu demorei a chegar nessa técnica. Hoje parece natural, mas foi um processo =)

Sempre vai haver o que pode ser melhorado, mas isso não deve ser um incômodo. Vc deve fazer o melhor que pode com o conhecimento que tem hoje, e conforme for avançando, terá insights de possibilidades de melhooria do código. É um processo.

---

> ### Claro essa minha duvida e para aplicações maiores

Em aplicações maiores, vc usará a linguagem com uma lib como o React. Mas não recomendo que se preocupe com isso agora. 

Segue os marcos que eu falei na [aula mais importante do CJRM](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/2186928). Sua preocupação deve ser: "qual é o próximo marco?".

Vc tem na mão o mesmo método que [eles](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo#depoimentos-de-alunos). 

Depois que completar os marcos e chegar na fluência, aí talvez seja o momento de vc se preocupar com "aplicações maiores".

@Sansanoski

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
