### ISSUE TITLE
Dúvida a cerca da necessidade de passagem dos objetos como argumentos 

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3992]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Dúvida na questão nº 07 

Boa tarde Roger,

Fique em dúvida se realmente é necessário nesse exercício passar como argumentos os objetos cat e dog para função, pois implementei sem a passagem dos argumentos e deu certo. No exercício você resolveu passando os objetos como argumento. 

 - Crie um objeto "dog" que possui as mesmas propriedades do objeto "cat";
  - Crie uma função que retorna a mensagem abaixo, com as informações corretas;
  - Exiba a mensagem no console.
  "A soma das idades de NOME_DO_GATO e NOME_DO_CACHORRO é RESULTADO_DA_SOMA."

```js
let dog = {
  name: 'vini',
    age: 3,
    color: 'black',
    bestFriends: ['foster','glover'],
    sound: function () {
          return 'Auuuuuuu'
    }
  }
   
  const sumOfAges = () => {
    return `A soma das idades de ${cat.name} e ${dog.name} é ${cat.age + dog.age}.`

    }
 console.log(sumOfAges())
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MarioFilho1.

Neste caso, o resultado será o mesmo sim, pq os objetos estão em escopo global (vc saberá o que é isso na etapa 5).

Então respondendo a pergunta, não é necessário. A forma com que vc fez também é válida, ok? =)

**Comment by MarioFilho1** [comment]
Obrigado!
