### ISSUE TITLE
Resumo da Aula variáveis e escopo de bloco - Aula 02-02da etapa 04

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#3994]
## Variáveis e escopo de bloco  

Escopo é o local onde o valor da variável pode ser acessado. Existe dois tipos de escopo, global e local. 

Escopo global é aquele que a variável pode ser acessada tanto na raiz do código, quanto pelos blocos de código, seja funções, loops, etc. 

Escopo local é aquele que a variável só pode ser acessada localmente por ter sido declarada dentro de um bloco de código. 

O javascript só permite a criação de uma variável de mesmo nome por escopo, seja do tipo let ou const.  

Quando um bloco de código é declarado dentro de outro bloco de código, há o que chamamos de aninhamento de blocos de código. Quando uma variável declarada no bloco mais externo do aninhamento tem o mesmo nome de variável declarada na raiz do código, se o bloco mais interno do aninhamento utilizar a mesma variável, o valor dela terá o mesmo valor da variável declarada do bloco mais próximo. 

```js
let age = 20 
 

if(true) { 

  let age = 40 

  console.log('valor no bloco externo',age) // 40  

if(true) { 

  age = 50   

  console.log('valor no bloco interno',age) // 50 

  } 

} 

console.log('Valor na raiz',age) //20 
```

**Comment by Roger-Melo** [comment]
Boa @MarioFilho1, rumo à fluência! 🔥
