### ISSUE TITLE
id do setInterval()

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#3996]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986667

### Descreva a dúvida

@Roger-Melo

Sei bem que o Contador da questão 03 tem uma função didática gigante e um uso prático pequeno, então minha dúvida neste exercício é apenas busca de um algo a mais.
Veja se pode ajudar!

Resolução do Professor não REFATORADA (modifiquei apenas os nomes das variárias) :
```JS 
 const btnInit = document.querySelector('.button-init-counter')
 const btnStop = document.querySelector('.button-stop-counter')
 const marker = document.querySelector('.counter-container')
 
 let timer = null

 btnInit.addEventListener( 'click', () => {
    timer = setInterval(() => {
     marker.textContent = Number(marker.textContent) + 1
    }, 1000)
  })
  
  btnStop.addEventListener( 'click', () => {
    clearInterval(timer)
    marker.textContent = 0
  })
```
A aplicação funciona.
Contudo, se clicarmos no botão ```Inciar Contador``` 2 ou mais vezes antes de clicarmos no botão ```Parar Contador```, veremos que ele aumenta a velocidade do Contador e o botão "Parar Contador **NÃO FUNCIONA**.

Então temos 2 problemas:
1) aumento de velocidade do contador;
2) o botão Parar Contador zera, mas não para o contador.

Pergunto:
1) Por que a velocidade aumenta?

2) Por que o contador não para mais?
Nesta segunda questão fiz alguns testes e acredito que, toda vez que o ```setInterval()``` é disparado ele cria o id (como dito em aula).

Mas se ele é disparado algumas vezes seguidas, antes de ser interrompido, ele gera um id NOVO. Assim, o ```clearInterval(timer)``` limpa o último id gerado, mas não pode limpar os anteriores.

Seria isso mesmo?
E como lidar com esse comportamento?

Infelizmente não posso estudar tanto quanto gostaria, mas fazer seu curso foi um dos melhores investimentos que fiz na minha vida.
Seu curso é muito bom, PARABÉNS!!!

**Comment by Roger-Melo** [comment]
Olá @andersonpereiragithub!

> ### 1) Por que a velocidade aumenta?

A sensação que a velocidade "aumenta" acontece pq, na verdade, no segundo clique no `btnInit`, um segundo callback do `setInterval` foi criado em memória (como o abaixo). Ou seja, agora existem 2 callbacks "brigando" para atribuir o conteúdo textual para `marker`. Cada um no seu tempo.

```javascript
() => {
  marker.textContent = Number(marker.textContent) + 1
}
```

---

> ### 2) Por que o contador não para mais?

Pq no momento em que o segundo clique no botão acontece, a referência do primeiro callback do setInterval foi perdida. Neste caso, `timer` armazena apenas o ID da referência atual (mais recente).

> o ```clearInterval(timer)``` limpa o último id gerado, mas não pode limpar os anteriores.

👆🏻 é basicamente isso que vc descreveu mesmo =)

---

> ### E como lidar com esse comportamento?

Existem algumas formas. 

Uma forma é declarando uma "flag", como listei [nesta issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/900). 

Uma outra forma é manipular o atributo [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) dos botões:

```javascript
btnInit.addEventListener('click', e => {
  timer = setInterval(() => {
    marker.textContent = Number(marker.textContent) + 1
  }, 1000)

  e.target.setAttribute('disabled', true)
  btnStop.removeAttribute('disabled')
})

btnStop.addEventListener('click', e => {
  clearInterval(timer)
  marker.textContent = 0
  
  btnInit.removeAttribute('disabled')
  e.target.setAttribute('disabled', true)
})

btnStop.setAttribute('disabled', true)
```

Sacou a ideia?

Se tiver ficado qualquer dúvida, pode comentar aqui abaixo que explico de outra forma =)

**Comment by andersonpereiragithub** [comment]
Obrigado Professor!

Ficou tudo muito claro agora.
Lamento que não tenha encontrado a dúvida semelhante do colega.

**Comment by Roger-Melo** [comment]
Tranquilo, meu caro. No que precisar, é só abrir uma nova issue =)
