### ISSUE TITLE
Exercícios - Aula 01-04 - Game Master Quiz

### ISSUE THREAD

**Issue by alphabraga** [roger-melo-treinamentos/curso-de-js-roger-melo#4]
- O do quiz: https://github.com/alphabraga/moviemaster

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício:

- Ainda sinto dificuldade no sync/await
- Listar as respostas de forma randominca
- Eu tentei adicionar classe css quando o li da resposta fosse clicado e tambem deixar selecionado o input radio mas não consegui
- Refatorar o código

- Quais foram as suas menores dificuldades durante a execução desse exercício.

debug
manipular o dom

**Comment by Roger-Melo** [comment]
Boa @alphabraga !

Havia esquecido de inserir na descrição do exercício que apenas o que vimos até aqui no curso deveria ser usado, hahah.

> Ainda sinto dificuldade no sync/await

Ainda vamos falar sobre promises e async await no curso, mas no quê exatamente você está dificuldades?

> Listar as respostas de forma randominca

Não entendi por quê, mas... https://codepen.io/rogermelodev/pen/ZEbyBeK?editors=0011

> Eu tentei adicionar classe css quando o li da resposta fosse clicado e tambem deixar selecionado o input radio mas não consegui

Uma solução é fazer com que o elemento clicado e o container do elemento (que deve receber a classe) contenham atributos com o mesmo valor (e de preferência com o mesmo nome). Exemplo: clicou no p dentro de uma li, se a li contém um atributo com o mesmo valor de um atributo do p, adiciona a classe na li. Usei essa técnica [aqui](https://youtu.be/OY21UokkEYk?t=3805).

> Refatorar o código

Refactoring vem com a prática. 

O que costumo fazer é: 

1. Fazer funcionar;
2. Me perguntar: "O que essa função extensa está fazendo?". Essa pergunta me leva a "agrupar mentalmente" linhas do código que existem para executar uma ação específica;
3. Depois de fazer esse agrupamento mental, fica mais fácil isolar esses grupos de código em funções de responsabilidade única.

Tente não deixar tantas linhas em branco no código. Linhas em branco fazem sentido quando separam responsabilidades.

**Comment by Roger-Melo** [comment]
Oi @alphabraga.

Estou fechando a issue, mas no que precisar é só dar o toque!
