### ISSUE TITLE
Etapa 06, Eventos de formulário - Aula 01-02

### ISSUE THREAD

**Issue by brenoSSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#40]
Oi Roger, minha dúvida em relação a essa aula é em como o input é disponível dentro do form usando a notação de objeto.
Na aula foi acessado o input pelo seu name e pelo seu Id:
```js
form.username.value
```
A outra forma que você disse que seria útil mais pra frente dentro do React também me gerou dúvidas
```js
event.target.username.value
```

Em resumo a minha dúvida é entender como que o id e o name se tornaram objetos acessíveis dentro do form. e dentro do target. Muito obrigado pela paciência.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Breno.

> como o input é disponível dentro do form usando a notação de objeto.

Na etapa 5, eu mostrei que quando um HTML é carregado no browser, o browser cria o Document Object Model (DOM) pra que seja possível a gente interagir com esse documento html, através do nosso código javascript.

Foi mostrado também que cada elemento da página se torna uma referência no DOM. Essas referências se chamam "nós". E cada nó é um objeto.

Se quiser visualizar as propriedades que cada elemento (nó) tem, você pode fazer o seguinte:

Selecione algum elemento da página e execute um `console.dir()`:

```javascript
const h1 = document.querySelector('h1')

console.dir(h1)
```

Você verá o nó desse elemento do DOM representado em sua forma natural: um objeto.

Como cada nó é um objeto, o form é apenas um nó (objeto) que contém propriedades e valores.

Recomendo que assista novamente a [Etapa 5, O que é o DOM - Document Object Model - Aula 01-06](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/842114) onde explico isso com mais detalhes.

Se mesmo após assistir ainda houverem dúvidas, é só dar o toque que explico de outra forma =)

@brenoSSilva

**Comment by brenoSSilva** [comment]
Obrigado por esclarecer, eu irei ver novamente a aula

Em sex., 18 de set. de 2020 às 23:31, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal Breno. Por agora vou fechar a issue, mas se surgir qualquer dúvida, é só abrir uma nova issue =)
