### ISSUE TITLE
Resumo da Aula O método sort - Aula 02-02 da etapa 08

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#402]
Este método é responsável por realizar uma ordenação dos itens de um *array*. Por padrão, o *sort* já ordena me ordem alfabética, caso os itens não forem uma *string* eles serão convertidos para que a ordenação alfabética ocorra. Se desejamos efetuar uma ordenação de números devemos especificar uma *função de comparação*. 

Vale ressaltar que este método é destrutivo, ou seja, ele modifica o *array* original.

## Argumentos

1. ***Função de comparação (opcional):*** é responsável por comparar dois itens consecutivos do *array*. Essa função deve retornar um valor numérico para que a ordenação ocorra. Além disso, essa função recebe dois parâmetros:
    1. **b →** representa o segundo item do *aray;*
    2. **a →** recebe o primeiro item do *array.*

## Retorno

O *array* na qual o *sort* foi invocado, porém com os itens ordenados.

## Como ocorre a ordenação

A ordenação do *array* ocorre de acordo com o valor retornado pela *função de comparação,* e, a referência do item que será ordenado é o item recebido no parâmetro ***b***. No entanto temos a seguinte regra para a ordenação seguindo o valor retornado pela *função de comparação*:

- Se um número negativo for retornado ***b*** virá antes de ***a*;**
- Se 0 for retornado ***b*** e ***a*** permanecem em suas respectivas posições;
- Se um número positivo for retornado ***b*** virá depois de ***a.***

---

*MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @sou-gabriel! Continue aplicando o método e a fluência será apenas uma questão de tempo! 🔥
