### ISSUE TITLE
Resumo da aula O método reduce - aula 01-04 da etapa 08

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#4059]
O MÉTODO REDUCE( )

O método `reduce()` executa a função de callback fornecida uma vez para cada elemento presente no array, excluindo valores indefinidos, recebendo quatro argumentos:

- acumulador - valor inicial (ou o valor do callback anterior)
- valorAtual - o valor do elemento atual
- index - o índice atual
- array - o array onde a iteração está ocorrendo.

Obs: Como boa prática, no segundo argumento do método `reduce()`, sempre coloque o valor inicial do acumulador.

```js
/* MÉTODO Array.prototype.reduce() */

const numbers = [1, 2, 3]

const sumNumbers = numbers.reduce((accumulator, item) => accumulator + item, 0)
// O segundo argumento do método reduce() indica o valor que 'accumulator' iniciou ao ter usado o método. A cada execução 'accumulator' recebe implicitamente ('accumulator' + 'item'). Ao fim do método, 'sumNumbers' irá valer 6, pois está retornando o valor final de 'accumulator'.

console.log(sumNumbers) // 6
```

**Comment by Roger-Melo** [comment]
Excelente @rafaelpradoj, rumo à fluência! 🎯
