### ISSUE TITLE
Criei método reduce de forma diferente do exercício corrigido

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#4061]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 01 da etapa 08 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1012887

### Descreva a dúvida

Bom dia professor, tudo bem?

Percebi que no exercício 4, antes de refatorar o código, dentro da função callback você fez um "return" direto usando apenas uma linha. Porém do seu jeito, quando eu bato o olho no código fico em dúvida, não compreendi muito bem o que o parâmetro accumulator está armazenando a cada execução.

Gostaria de saber se da forma que eu fiz pode impactar meu aprendizado em etapas futuras. Segue abaixo meu código, obrigado!

```js
const cart = [
  { name: 'Dark Souls III', price: 95.03 },
  { name: 'Shadow of the Tomb Raider', price: 101.19 },
  { name: 'Sekiro: Shadows Die Twice', price: 179.99 },
  { name: 'Resident Evil 2', price: 119.90 },
  { name: 'Death Stranding', price: 149.99 }
]

const onlyCartNames = cart.reduce((list, item) => {
  list += `- ${item.name}\n`

  return list
}, '')

console.log(onlyCartNames)
```

@Roger-Melo

**Comment by MivlaM** [comment]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 01 da etapa 08 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1012887

### Descreva a dúvida


Bom dia professor, tudo bem?

Percebi que no exercício 4, antes de refatorar o código, dentro da função callback você fez um "return" direto usando apenas uma linha. Porém do seu jeito, quando eu bato o olho no código fico em dúvida, não compreendi muito bem o que o parâmetro accumulator está armazenando a cada execução.

Gostaria de saber se da forma que eu fiz pode impactar meu aprendizado em etapas futuras. Segue abaixo meu código, obrigado!

```js
const cart = [
  { name: 'Dark Souls III', price: 95.03 },
  { name: 'Shadow of the Tomb Raider', price: 101.19 },
  { name: 'Sekiro: Shadows Die Twice', price: 179.99 },
  { name: 'Resident Evil 2', price: 119.90 },
  { name: 'Death Stranding', price: 149.99 }
]

const onlyCartNames = cart.reduce((list, item) => {
  list += `- ${item.name}\n`

  return list
}, '')

console.log(onlyCartNames)
```



@Roger-Melo

---

Olá @rafaelpradoj!

> ## Não compreendi muito bem o que o parâmetro accumulator está armazenando a cada execução.

Algo essencial para entender como está funcionando o parâmetro accumulator no seu código é acrescentar um `console.log` antes das atribuições de valor da `list`. Ficaria assim: 

```js
const onlyCartNames = cart.reduce((list, item) => {
  console.log('list:', list)
  list += `- ${item.name}\n`
      
  return list
}, '')
```

Nunca se esqueça de usar console.log para assegurar que a const está armazenando o valor que se espera. Não assuma que suas consts/parâmetros/expressões estão resultando no valor que você acha que estão. Você não deve ter essa certeza antes de comprovar isso.

Sabendo disso, observe o exemplo abaixo:

```js
const numbers = [1, 2, 3, 4]

const sumResult = numbers.reduce((accumulator, item) => accumulator + item, 0)

console.log(sumResult) // retorna 10
```

Imagine que temos um array com 4 números, [1, 2, 3, 4], ao invocarmos o `reduce` com uma função como primeiro argumento e um tipo de dado como segundo, na primeira execução da função, o `accumulator` recebe o segundo argumento do `reduce`, que é 0. O item atual recebe o primeiro item do array, ou seja, 0 + 1 = 1;

Essa função vai retornar o resultado de accumulator + item (no caso 1) e na segunda execução dessa função, o `accumulator` armazena o retorno da invocação passada da função, pois recebe o resultado do cálculo que é 1. Depois, o `accumulator` é somado ao próximo item do array que é o 2, 1 + 2 = 3;

O `accumulator` novamente armazena o resultado do cálculo e soma ao próximo item do array que é 3, 3 + 3 = 6; e por fim 4, 4 + 6 = 10. A expressão retorna 10 e todo o `reduce` retorna o valor total de 10.

Tendo como exemplo a função mostrada na aula:

```JS
const productList = cart.reduce((accumulator, product) => {
  return `${accumulator}- ${product.name}\n`
}, '')
```

Visto que o exercício pede para obter uma lista de strings, uma string vazia é passada como segundo argumento do `reduce`, ela é necessária para a primeira execução, o parâmetro `accumulator` armazena essa string vazia e o parâmetro product armazena o primeiro item da lista. Depois da primeira execução, o parâmetro `accumulator` que antes armazenava uma string vazia, passa a armazenar o retorno da execução passada da função, ou seja, o nome do primeiro item da productList; a string 'Dark Souls III', enquanto o o product passa a armazenar o segundo item da lista 'Shadow of the Tomb Raider', a sequência continuará dessa forma até todos os itens serem retornados.


> ## Gostaria de saber se da forma que eu fiz pode impactar meu aprendizado em etapas futuras.

Quando o sinal de atribuiçao `=` é utilizado fora da declaração do identificador (const, let, parâmetro) é um indício que está acontecendo uma mutação de valor. No caso do seu código, list está recebendo todo o valor que ele tem concatenado a string.

```js
const onlyCartNames = cart.reduce((list, item) => {
  list += `- ${item.name}\n`
  // ...
}, '')
```

Existe um princípio chamado princípio da imutabilidade. Uma mutação tende a causar bugs na aplicação, a aplicação se torna menos previsível e é mais difícil de manter. Por isso que é recomendado evitar mutações.

Eu recomendo que você dê preferência a forma que foi mostrada na resolução, nela não será mais necessário usar o sinal de igual e por consequência, não haverá mutações =)

--- 

Ficou claro?

**Comment by rafaelpradoj** [comment]
Olhando para o seu exemplo e tentando fazer o exercício novamente, consegui compreender. 

Por eu ter usado o nome "list" e não "accumulator", acabei esquecendo o que esse primeiro argumento fazia. Compreendi que nesse exercício, na primeira execução, ele é uma string vazia, e após a segunda execução ele já armazena o segundo argumento como valor.

Muito obrigado pela ajuda, principalmente o uso do console.log() antes das execuções.
