### ISSUE TITLE
Aplicação: Conversor de Moeda

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4065]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Kmkery/Conversor-de-Moeda.git

### Maiores dificuldades durante a implementação

Acho que não tive maiores dificuldades, apenas de início me atrapalhei um pouco na lógica de criar as opções na página.

### Menores dificuldades durante a implementação

Fazer a requisição dos dados da API, obter os valores convertidos e renderizá-los na página.

**Comment by Roger-Melo** [comment]
Olá @Kmkery.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Kmkery!

Você pode baixar a análise de seu Conversor de Moedas [neste link](https://drive.google.com/file/d/17wLRE4R9UPteaKNw8JEPm6qDwmsj5Ql7/view?usp=sharing).

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by Kmkery** [comment]
Oi @Roger-Melo, muito obrigada pela análise!

Na verdade, ainda não cheguei a olhar a aula da resolução deste exercício, mas fiquei feliz que o código que fiz tenha ficado um pouquinho próximo à solução que vc comentou... Vi a necessidade de encapsular os dados em um objeto para não deixá-los expostos e poder acessar onde precisasse, de modo privado, senão eu teria que deixar os valores expostos em uma const global. 

Fiquei um pouco insegura em usar objetos e inserir tantos métodos quanto pudesse dentro dele, se estava fazendo um uso correto deste recurso... inclusive, realmente tive dúvida de como nomeá-lo (por isso acabou ficando como currencyObj e "currencys" mesmo)... falando em nomes, perdão meu inglês, ele é "embromation", nem me liguei no plural equivocado de currency 🙈😅

Muuuuito legal a explicação do recurso do fragment, vou tentar usar e alterar os arquivos com as sugestões e dicas que deu (mais uma vez, me sinto como no meme da mente expandindo rsrs). Obrigada de coração, Roger! ❤️🙏

**Comment by Roger-Melo** [comment]
Legal! Fico feliz que tenha ajudado. 

No que precisar, é só abrir uma nova issue =)
