### ISSUE TITLE
Resumo da Aula 03 - 03 da etapa 01

### ISSUE THREAD

**Issue by ricardoribeir** [roger-melo-treinamentos/curso-de-js-roger-melo#407]
_**valor undefined**_
valor primitivo utilizado quando uma variável não teve valor atribuído

_**valor null**_
valor primitivo que representa a ausência intencional de um valor de objeto

**Ex: 01**
_let x;_

x == null            // true        --(verdadeiro pois não houve atribuição de valor na variável intencionalmente)
x == undefined       // true   --(verdadeiro pois não há atribuição de valor para a variável)
x === null           // false      --(falso, pois não foi atribuído o valor null, apenas valor não declarado)
x === undefined      // true  --(verdadeiro pois variável não possui valor atribuído)

**Ex: 02**
_let y = null;_

y == null            // true        --(verdadeiro pois variável foi declarada como "null")
y == undefined       // true   --(verdadeiro pois a variavel (y = null) é uma variavel undefined)
y === null           // true       --(verdadeiro pois variável foi declarada como "null")
y === undefined      // false   --(a variavel foi atribuida como "null" por isso não é undefined)

@Roger-Melo

**Comment by YureK-a** [comment]
Olá! Que tal escrever os códigos do seu app.js na sua issue? Para fazer isso, basta colocar isso: "```javascript" no começo do resumo e mais outras três crases no final dele.

exemplo:

const example = 'a'

```javascript
const example = 'a'
```

Isso vai ser bem útil no futuro, porque acaba ficando cansativo rever as aulas só para lembrar de um comando, logo, anotá-los em seu resumo vai ser de grande ajuda!
