### ISSUE TITLE
Captura de elementos 

### ISSUE THREAD

**Issue by anderson-oliveira-git** [roger-melo-treinamentos/curso-de-js-roger-melo#4078]
### Etapa da aula

7

### Nome da aula

Template HTML e checando as respostas - Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/943417

### Descreva a dúvida

Vi que existem muitas formas de capturar elementos no javascript, por exemplo: getElementById(), getElementByClassName(), querySelector() e capturando um form e usando form.idDoCampo para ter acesso ao elemento. Existe alguma diferença com relação ao desempenho entre essas 3 formas de obtenção de elementos? E qual a forma mais recomendada utilizar em projetos maiores que tem formulários com muitos campos? vou armazenando todos os campos em uma const utilizando os metodos de captura? ou apenas capturo o form e vou utilizando o fomato elementoForm.idElementoDesejado? 

@Roger-Melo

**Comment by anderson-oliveira-git** [comment]
Obrigado, professor, ficou claro sim. :)

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
