### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - 03 - 04 - da etapa 05

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#4079]
Muita coisa nova e interessante nessa aula! A que mais me chamou a atenção foi a forma mais elaborada
de adicionar um elemento e conteúdo ao DOM. O método createElement me gerou uma certa estranheza 
num primeiro momento. É mais prático acrescentar elementos e conteúdo ao DOM fazendo uso do innerHTML,
porém, a maior complexidade do createElement, com criação e reatribuição, após um olhar mais atento (e 
principalmente após o exercício 06 da lista de exercícios 15) me permitiu compreender melhor as possibilidades
dos métodos createElement, append e prepend trabalhando em conjunto. Mais uma grande aula!

**Comment by Roger-Melo** [comment]
Boa @VitorPeixotoDev, rumo à fluência! 🔥
