### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by carlosdevjs** [roger-melo-treinamentos/curso-de-js-roger-melo#4081]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/carlosdevjs/Conversor-de-Moedas.git

### Maiores dificuldades durante a implementação

- Inserir a seleção das moedas com o "select";
- Realizar a requisição fora do eventListener;
-  Refatoração;
-  Tive muita dificuldade de pegar os valores dos objeto para poder calcular a multiplicação;
-  criar bons nomes de funções;
-  Dividir o problema em partes menores;
-  A utilização do join() para transformar os dados em strings, estava tentando manipular só o array gerado pelo map(), ai sempre dava errado, levei muito tempo para lembrar que precisava dele do join().

### Menores dificuldades durante a implementação

- Criar a função asyncrona para pegar os dados no servidor;
- Manipular o DOM;
- try/catch;
- criar os eventos;

**Comment by Roger-Melo** [comment]
Olá @carlosdevjs.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Boa meu caro! Rumo à Fluência 🔥

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
