### ISSUE TITLE
Resumo da Aula O método map da etapa 08

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#4083]
<h1 align="center">O método map</h1>

O map é um método de array que tem seu uso quando é necessário retornar a mesma quantidade de itens do array original, porém com os valores transformados:

```js
const numeros = [1, 2, 3];

const double = numeros.map(numero => {
return  numero * 2
})

console.log(double) // resultado [2, 4, 6]
```
Vimos no exemplo acima que o _**map**_ retornou 3 itens assim como o **_array_** original, porém ainda assim retorna um **_array_** com valores modificados.
Diferente do **_forEach_** que não é obrigado a retornar nada, o **_map_** é necessário, senão **_undefined_** será retornado.

## Casos de uso
Imagine que uma loja está com uma promoção em que todos os itens da loja está pela metade do preço:
```js
const prices = [20, 10, 30, 25, 15, 40, 80, 5]

const salePrices = prices.map(price => price / 2)

console.log(salePrices) //10, 5, 15, 12.5, 7.5, 20, 40, 2.5
```

Imagine que na mesma loja itens que forem acima de 30 reais receberam 50% de desconto:

```js
const prices = [20, 10, 30, 25, 15, 40, 80, 5]

const salePricesMoreThan30 = prices.map(price => {
  if (price >= 30){
    return price /2
  }
return price
})
```

**Comment by Roger-Melo** [comment]
Boa @Beninigmal, rumo à fluência! 🔥
