### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07 da etapa 05

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#409]
Linha de raciocínio...

## Como pegar a referência desse elemento no DOM?

- Primeira opção: Investigar os seletores CSS(tags, divs, classes) em que ele está.
- Segunda Opção: Utilizar o inspect do navegador, clicar com o botão direito no elemento que você quer e escolher copy > selector.

## Como guardar essa refêrencia para ser utilizada?

**---> MÉTODO 1:**
Query Selector

_SINTAXE:_
`querySelector(" ")`

_EXEMPLO:_ 
`const Paragraph = document.querySelector("p")`

_RESULTADO:_ 
Ele devolve a primeira TAG p encontrada no HTML e guarda na variável Paragraph.

--------------------------
**---> MÉTODO 2:**
Query Selector All

_SINTAXE:_
`querySelectorAll(" ")`

_EXEMPLO:_ 
`const Paragraph = document.querySelectorAll("p")`

_RESULTADO:_
Ele devolve um NodeList(não é um array) com todas as referências das TAGs p encontradas no HTML e guarda na variável Paragraph.

![image](https://user-images.githubusercontent.com/42559009/114103740-08842780-98a0-11eb-81c6-bbaf359d2b03.png)

Nesse NodeList podem ser utilizados alguns métodos de array, como forEach, notação de colchetes, etc...

## Outras maneiras de selecionar elementos

**---> MÉTODO 3:**
Get Element

_SINTAXE:_
`getElementByID(" ")`

_EXEMPLO:_ 
`const title = document.getElementById("title")`

_RESULTADO:_ 
Ele devolve o primeiro elemento com o ID especificado encontrado no HTML e guarda na variável Title.

**---> MÉTODO 4:**
Get Elements

_SINTAXE:_
`getElementsByClassName(" ")`

_EXEMPLO:_ 
`const errors = document.getElementsByClassName("errors")`

_RESULTADO:_ 
Ele devolve uma HTML Collection com as referências de todos os elementos que tem a a Classe "errors", e armazena na variável "errors".

**HTML Collection** = uma espécie de NodeList porém com recursos limitados, não dá pra fazer um forEach porém dá pra usar uma marcação de colchetes pra acessar os elementos pela sua posição.

**---> MÉTODO 5:**
Get Elements

_SINTAXE:_
`getElementsByTagName(" ")`

_EXEMPLO:_ 
`const paragraphs = document.getElementsByTagName("paragraphs")`

_RESULTADO:_ 
Ele devolve uma HTML Collection com as referências de todos os elementos que tem a Tag "paragraphs", e armazena na variável "paragraphs".

**HTML Collection** = uma espécie de NodeList porém com recursos limitados, não dá pra fazer um forEach porém dá pra usar uma marcação de colchetes pra acessar os elementos pela sua posição.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @davidtheblane! Rumo à fluência! 🔥
