### ISSUE TITLE
Resumo da Aula Herança entre classes - Aula 02-08 da etapa 14

### ISSUE THREAD

**Issue by santos2408** [roger-melo-treinamentos/curso-de-js-roger-melo#4092]
=============== HERANÇA ENTRE CLASSES ===============

Herença entre classes significa fazer com que uma subclasse herde propriedades e métodos de uma outra classe, mas mesmo assim podendo ter as suas próprias propriedades e métodos.

Isso será usado quando quisermos ter um novo objeto que herda as características de outro mas que tenha características únicas. E para não repetirmos código desnecessariamente, utilizamos a herença de classes para obter as características que irão se repetir nos objetos.

Para herdarmos propriedades e métodos de uma classe, na declaração da classe devemos inserir 'extends' e o nome da classe que queremos herdar as características.

Quando uma subclasse não contém um constructor declarado, essa subclasse irá usar o constructor da classe que ela está herdando e consequentemente irá obter as propriedades da classe pai. Mas quando criamos um novo constructor na subclasse, a subclasse não irá conseguir mais obter as propriedades da classe pai, isso porque, existindo dois constructor, eles entram em conflito.

O constructor da classe pai só é executado quando não existe um constructor na classe filho, se passar a existir, o constructor da classe pai não será mais executado. A classe pai é conhecida também como superclass, por isso o nome do método que a invoca é chamado de 'super'.

Podemos 'sobrescrever' métodos da subclasse que já existem na superclasse, pois como estão em objetos diferentes, declarar com o mesmo nome não causará problema, mesmo tendo o mesmo nome cada método terá seu comportamente único.

Para resolver isso e recebermos as propriedades da classe pai e ainda inserir propriedades exlusivas da subclasse precisaremos receber todos os argumentos da classe pai na invocação da subclasse e em seguida, dentro do constructor da subclasse iremos invocar o constructor da classe pai, só que para o JS entender que estamos invocando o constructor da classe pai e não do filho, precisaremos trocar o nome 'constructor' por 'super'. Assim nós teremos dois constructors um para a subclasse e outro para obter as propriedades da classe pai sem evitar um conflito entre elas. Veja o exemplo abaixo:

```.js
class Mammal { // classe pai
  constructor (species, name, age) {
    this.species = species
    this.name = name
    this.age = age
    this.mammaryGland = true
  }

  incrementAge () {
    this.age++
  }
}

class Lion extends Mammal{ // Lion (subclasse) herdando propriedades e métodos de Mammal (classe pai)
  constructor (species, name, age, manEater) { // constructor da subclasse
    super(species, name, age) // invocando constructor da classe pai e obtendo propriedades
    this.manEater = manEater // propriedade única da subclasse Lion
  }

  eatZebras (animals) { // método único da subclasse Lion
    return animals.filter(animal => animal.species !== 'zebra')
  }
}

const zeca = new Mammal('zebra', 'Zeca', 6)
const pompeu = new Mammal('gnu', 'Pompeu', 5)
const cesar = new Mammal('macaco', 'Cesar', 8)
const mufasa = new Lion('leão', 'mufasa', 4, false)
const scar = new Lion('leão', 'scar', 10, true)

const animals = [zeca, pompeu, cesar]

scar.eatZebras(animals)
console.log(mufasa, scar)
```

=============== MÉTODOS GETTER AND SETTER ===============

Métodos get e set são outras features de classes. 
  
Quando temos um método numa classe que está claramente obtendo um determinado valor, nós reconhecemos esse método como um método 'getter', ou seja, esse método existe para que um valor seja obtido quando ele for invocado.

Portanto, quando um método é um 'getter' nós podemos usar uma sintaxe de abreviação inserindo a palavra chave 'get' a esquerda do nome do método. Essa palavra chave nos permitirá obter o valor da propriedade usando a sintaxe de propriedade. Também devemos colocar o nome do método em letras minúsculas.

Com isso, mesmo sendo um método, no momento da invocação desse método podemos remover a sintaxe de invocação de método e invocá-lo como se estivessemos chamando uma propriedade, ou seja, sem precisar inserir parênteses.

Vale lembrar que não podemos ter métodos e propriedades com o mesmo nome, então se isso estiver ocorrendo, troque os nomes para evitar conflito.

Da mesma forma que existem métodos que obtém um valor 'getter', existem também métodos que setam um valor 'setter', ou seja, que atribuem um valor a uma propriedade. Para isso usamos a mesma sintaxe de abreviação mas passamos a palavra chave 'set' a esquerda do método.

Pode parecer estranho invocar métodos como se fossem propriedades, e é sim. Mas quando nos depararmos com um código semelhante em um projeto real, deveremos saber o que está acontecendo. Então, saber que isso é possível é uma maneira de evitar consequências no futuro e se for viável poderemos refatorar o código.

=============== ENCAPSULAMENTO ===============

É um mecanismo de restringir o acesso direto a certas informações de um objeto. Isso é muito importante e existem no mínimo 3 formas de encapsularmos dados em javascript: com classes, factory functions ou funções construtoras.

Agora veremos a forma utilizando classes, as outras duas formas veremos em aulas posteriores.

Repare que, no código abaixo, mesmo tendo métodos próprios para modificar o valor da propriedade count, nada impede que, fora da classe, depois que instanciamos o objeto, modifiquemos e acessemos a propriedade count dentro da classe. Ou seja, códigos externos à classe podem acessar e modificar propriedades dentro dela.

```.js
class Counter {
  count = 0 // propriedade pública

  get value () { // método get usando sintaxe de abreviação
    return this.count
  }

  increment () {
    this.count++
  }

  set newValue (aNumber) { // método set usando sintaxe de abreviação
    this.count = aNumber
  }
}

const counter = new Counter()

counter.count = 'Olá' // atribuindo string à count
console.log(counter.count) // acessando diretamente o valor da count
```

Veja que, o código que escrevemos fora da classe consegue acessar e modificar o valor da propriedade count dentro da classe. Isso pode parecer normal, mas é um problema de segurança.

Isso acontece porque a propriedade count é uma propriedade pública. Normalmente a propriedade já é pública, mas podemos explicitar isso removendo o 'constructor', removendo o 'this' e deixando apenas a declaração do nome da propriedade. Esse tipo de feature que nos permite declarar uma propriedade pública sem precisar declarar o método constructor é chamada de 'public class fields'.

Fields é um termo alternativo para 'propriedades dentro de uma classe'. Propriedade e fieldes significam a mesma coisa nesse contexto.

Mas se desejarmos que apenas os códigos internos da classe possam acessar e modificar as propriedades dela, para isso devemos declarar a propriedade como privada, com isso, qualquer código fora da classe será impedido de acessar ou modificar propriedades da classe.

Chamamos a declaração de propriedades privadas de 'class private fields', declarando uma '#' antes do nome da propriedade a tornará privada e apenas os métodos internos da classe poderão acessar ou modificar seu valor, códigos externos não terão acesso.

Caso deseje inserir um valor dentro da propriedade privada que está sendo recebido por parâmetro ou o objeto precisa de outras propriedades que são únicas, você pode, abaixo da propriedade privada, criar o método constructor e reatribuir o valor 
da propriedade recebendo o valor do parâmetro e trabalhar normalmente com o constructor

```.js
class Counter {
  #count = 0 // propriedade privada, precisar usar '#'

  constructor (value) { // atribuindo valor na propriedade privada, pode usar o constructor normalmente
    this.#count = value
  }

  get value () { // método get usando sintaxe de abreviação
    return this.#count
  }

  increment () {
    this.#count++
  }

  set newValue (aNumber) { // método set usando sintaxe de abreviação
    this.#count = aNumber
  }
}

const counter = new Counter()

counter.#count = 'Olá' // não tem permissão para modificar a propriedade
console.log(counter.count) // não tem permissão para acessar a propriedade

counter.newValue = 5 // modificando propriedades através do método que existe na classe 
counter.value // acessandro propriedade através do método que existe na classe
```

Em classes que herdam propriedades de outras classes, se as propriedades dessa subclasse forem públicas, nós não precisamos inserir o método constructor, invocar o método super para obter as propriedades da classe pai e em seguida criar as propriedades próprias da subclasse.

Basta utilizar a sintaxe de propriedade pública removendo o contructor, o this e deixando apenas a declaração da propriedade. Naturalmente a subclasse está obtendo as propriedades da classe pai e inserindo propriedades únicas no seu bloco.

Vale lembrar que esse tipo de ação só funciona em subclasses, na classe pai ainda precisaremos do método constructor para criar as propriedades. E perceba também que se quisermos obter os dados através dos parâmetros deveremos ter de fato o método constructor.

**Comment by Roger-Melo** [comment]
Excelente @santos2408, rumo à fluência! 🎯
