### ISSUE TITLE
Resumo da Aula O método reduce da etapa 08

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#4094]
<h1 align="center">O método reduce</h1>

O **_reduce_** é um método usado quando você precisa transformar um dado em outro tipo de dado como uma **_string_**, um objeto ou até mesmo um numero.

```js
const numbers = [1, 2, 3]

const sumResult = numbers.reduce((acc, item) => {
  return acc + item
}, 0)

console.log(sumResult) // 6
```

Interessante salientar que o valor passado após as chaves é o valor inicial do accumulador e isso também demonstra qual o tipo de dado inicial, no exemplo acima é um número.

**Comment by Roger-Melo** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯
