### ISSUE TITLE
Etapa 4, Tipos de refêrencia vs Tipos primitivos - Aula 03-04

### ISSUE THREAD

**Issue by brenoSSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#41]
Depois de absorver o conteúdo da aula, eu tentei praticar procurando exercícios na internet e encontrei esse exemplo, depois de vários minutos tentando entender a saída dele eu cheguei a conclusão:
```js
var x = 0;

function foo() {
    var x = 10;
    return function() {
        return x;
    }
}
var bar = foo();

function baz() {
    var x = 20;
    return bar();
}
```
Pelo que entendi bar sempre vai referenciar apontando para a função definida dentro de foo() e não criando uma cópia da função retornada, por isso, independente de onde bar() for invocada seu valor sempre vai ser 10. Se minha conclusão estiver errada por favor me corrija.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Breno.

Na verdade o objetivo desse exercício que você encontrou não está relacionado a Tipos de refêrencia e Tipos primitivos. Mas sim a closures.

Eu não recomendo que você procure exercícios na internet não. Todos os exercícios que você precisa para treinar os conceitos passados no treinamento já estão **dentro do treinamento**.

Quanto mais você focar em uma coisa só, mais resultados terá.

Imagina se eu seguir duas receitas diferentes de dieta pensando que elas se complementam e que vou emagrecer mais rápido? Cada receita vai me levar para uma direção e no final das contas, eu vou executar nenhuma das duas direito.

O exercício acima é sobre closures. Closures é algo que eu ainda não falei no treinamento. Por uma razão: há o momento certo de falar.

A minha sugestão é que você foque e siga o que está no curso, para realmente chegar na fluência na linguagem =)

@brenoSSilva

**Comment by brenoSSilva** [comment]
Beleza Roger, muito obrigado pelo direcionamento :D

Em sex., 18 de set. de 2020 às 23:48, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Show Breno. Por agora irei fechar a issue, mas se surgirem mais dúvidas é só dar o toque =)
