### ISSUE TITLE
Resumo da Aula 01-04 requests HTTP da etapa 11

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#4117]
**Aula 01-04 - RequesteHTTP**

**requests HTTP() {**
-> As vezes precisamos exibir informações em banco de dados ou API(Application Programming
    Interface)
API = Seria uma interface de programação de programações. Da mesma forma que uma interface
gráfica de uma aplicação é criada para que o usuário use essa aplicação uma api é desenvolvida
para que uma aplicação use as funcionalidades de outro sistema. E uma ferramenta para que u 
sistema se comunique com outro sistema

-> requisições HTTP é um pedido uma solicitação a api ou banco de daddos

-> HTTP = hypertext Transfer Protocol -> Esse protocolo é o protocolo principal
entre a comunicação de computadores na internet, fazemos esse request para um endpoint
que seria uma URL disponível pela API ou servidor.

-> Apartir do código rodando no browser fazemos um request para um endpoint de um servidor
que envia as respostas e com isso nos obtemos as informações do servidor e podemos fazer
alguma coisas com elas. Tem varias api que podemos consumir para obter dados. Twitter
spotify, e cada aPI tera seu próprio conjunto de endpoints disponível para que os requests
sejam feitos. Nos podemos fazer uma api utilizando uma API com que pode ser javaScript conm
node ou python com ruby.

-> resposta obtida do servidos será no formato JASON

-> JASOM = JavaScript Object Notation -> Ele é um formato que se parece muito com um objeto
javaScript. Este é um padrão utilizado para a troca e armazenamento de informação entre 
sistemas.

-> Na pratica dos requests iremos utilizar a JASONPlaceholder(esta api foi feita especificam
    ente para desenvolvedores treinar requests para endpoints específicos que voa retornar
    um JSON com informações especificas)
}

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
