### ISSUE TITLE
Resumo da Aula Adicionando to-dos - Aula 01-03 da etapa 09

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#412]
## O método HTMLFormElement.reset() 
É responsável por restaurar todos os campos presentes dentro de um formulário para seus respectivos valores iniciais.

## Curiosidade

É possível criar um botão dentro de um formulário que tenha um atributo id/name armazenando *"reset"*, e, quando esse botão for clicado os campos do formulário serão limpos sem inserir nenhum código Js.

---

*MDN: [https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset)*

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @sou-gabriel! 🔥
