### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03 da etapa 05

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#4122]
Nesta aula, foram abordados alguns tipos de eventos, como por exemplo: `copy`, `mousemove` e o `wheel`

**Comment by Roger-Melo** [comment]
Show @paulovieiradasilva. Vamo que vamo, rumo à fluência! 🙌
