### ISSUE TITLE
Resumo da Aula o método sort da etapa 08

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#4123]
<h1 align="center">O  método sort</h1>

O método **_sort_** é utilizado para ordenar um array  seja em ordem alfabética, crescente, decrescente, etc.
Por padrão o sort já ordena em ordem alfabética, vamos ver isso no exemplo abaixo:

```js
const names = ["banana", "abelha", "cacau", "dragão" ]
names.sort()
console.log(names) // ["abelha", "banana", "cacau", "dragão"]
```

Já para ordenação crescente de numéricos, o sort sozinho irá ordenar apenas os primeiros dígitos de cada número, e isso é complicado por que se houver:

```js
const number = [10, 5, 55, 30, 45, 24, 77]

number.sort()

console.log(number) // 10, 24, 30, 45, 5, 55, 77

```
Observe que o número 5 ficou após o 45 isso por que se olharmos o primeiro digito, de 10 é 1, de 24 é 2  e assim o 5 é tratado da mesma maneira, o que não funciona para o propósito da ordenação.
Para resolver essa questão o sort pode receber em seu argumento uma função que ao retornar -1, 1 ou 0 uma ordenação vai ser feita ou finalizada:

```js
const number = [10, 5, 55, 30, 45, 24, 77]
//crescente
number.sort((num1, num2) => {
  if(num1 > num 2){
    return 1
  }
  else if (num2 >num1){
    return -1
  }

return 0
})

//decrescente
number.sort((num1, num2) => {
if(num1 < num2){
  return 1
}
else if (num2 < num1){
  return -1
}

return 0
})

```
Em resumo, o sort vai comparar de 2 em 2 itens, e se o primeiro desses 2 for maior que o segundo, retornando 1 o numero maior vai ser colocado após o menor, e esse maior vai ser o primeiro numero da próxima iteração fazendo a comparação com o próximo, se a condição anterior for falsa, a próxima condição é testada se o num2 é maior que o num 1, e isso vai resultar verdadeiro, e retornará -1 isso vai fazer com que o numero menor permaneça onde está e o maior seja comparado na próxima iteração ao invés dele e se o número for igual ao outro nada acontece  pulando para a próxima comparação.

Apesar de funcionar bem existe uma forma mais concisa de fazer esse mesmo código que é:

```js
const number = [10, 5, 55, 30, 45, 24, 77]

number.sort((num1, num2) => num1 - num2)

console.log("crescente" ,number) // [5, 10, 24, 30, 45, 55, 77]

number.sort((num1, num2) => num2 - num1)

console.log("decrescente", number) // [77, 55, 45, 30, 24, 10, 5]
```

**Comment by Roger-Melo** [comment]
Show @Beninigmal. Vamo que vamo, rumo à fluência! 🙌
