### ISSUE TITLE
Resumo da Aula Testando padrões de regex - 01 - 05 da etapa 06

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#4134]
Nessa aula são apresentados dois métodos: test() e search(). Aquele é um método específico das regex,
cujo retorno é um boolean; este um método de strings que retornará o índice equivalante à posição ocupada
pelo primeiro caracter que inicia o match com o padrão preestabelecido. 
 Outro ponto muito simples porém importante é como é feita a declaração de uma regex dentro do código:
se para uma string basta fazer uso das aspas, para uma regex basta o uso das barras.

**Comment by Roger-Melo** [comment]
Boa @VitorPeixotoDev, rumo à fluência! 🔥
