### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by henriquesouzadev** [roger-melo-treinamentos/curso-de-js-roger-melo#4138]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/henriquesouzadev/english-quiz

### Maiores dificuldades durante a implementação

Tive um pouco de dificuldade em pensar na lógica para fazer a funcionalidade de pontuação do usuário, antes de assistir a aula. 

### Menores dificuldades durante a implementação

Inserir o elemento de pontuação no HTML.

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev!

Você pode baixar a análise de sua aplicação [neste link](https://drive.google.com/file/d/1jikgY7E9s9eDJT7GghuirMg5v_XH5ZD8/view?usp=sharing).

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by henriquesouzadev** [comment]
Oi @Roger-Melo!

Obrigado pela análise e pelas dicas!

Já consigo perceber uma evolução muito grande na minha compreensão de como funciona o JavaScript. 

Parabéns pela sua didática e obrigado mais uma vez pelos ensinamentos passados, estou muito satisfeito com o curso.

Obs.: Acho que perdi o prazo para ver a análise da aplicação do Todo-list, por conta da correria do dia a dia. =\

**Comment by Roger-Melo** [comment]
Boa!

> ### Acho que perdi o prazo para ver a análise da aplicação do Todo-list, por conta da correria do dia a dia. =\

**Comment by Roger-Melo** [comment]
> ### Acho que perdi o prazo para ver a análise da aplicação do Todo-list, por conta da correria do dia a dia. =\

Cara, geralmente nas análises de todo-list dá pra tirar umas sacadas bem interessantes. 

As análises são públicas, então se vc quiser ver, basta acessar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=is%3Aissue+label%3A%F0%9F%94%A5aplica%C3%A7%C3%A3o+is%3Aclosed).

E fica ligado pra não perder o prazo da próxima =)

@henriquesouzadev

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
