### ISSUE TITLE
Aplicação: Weather application

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#4139]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Jansen-Muniz/weather-application

### Maiores dificuldades durante a implementação

Criar as funções dos dois requests.

### Menores dificuldades durante a implementação

Manipulação do DOM para inserir os ícones e os textos.

**Comment by Jansen-Muniz** [comment]
Tá aí mano Roger Waters =)

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz! A análise foi enviada para seu email.

No que precisar, é só abrir uma nova issue =)
