### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by allanpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#414]
Olá Profº Roger, segue o link do repositório do QUIZ: https://github.com/allanpedro/quiz.git

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;

Tive dúvidas no uso do forEach, porém revisando o código consegui ter um entendimento esperado, também não consegui colocar a pontuação, vou dar seguimento nas aulas para aprender. 

- Quais foram as suas menores dificuldades durante a execução desse exercício.

Conseguir entender bem os métodos para execução do exercício, o querySelector, o preventDefault, estou gostando muito do treinamento.

Eu como vim do HelpDesk focado em Infra, estou tendo bastante dificuldade de memorizar mesmo refazendo exercícios, anotações, sempre tenho que dar uma consultada noss códigos do exercícios anteriores para relembrar, creio que faz parte do processo. 

Um abraço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Allan.

Parabéns pelo esforço em construir a primeira aplicação dentro do CJRM =)

Antes da análise, deixa só eu dar uma dica.

Não é necessário inserir ´´´js e ´´´ no início e fechamento do código no arquivo .js. Você só usará essa sintaxe quando for postar algum código js diretamente no corpo da issue. Então pode remover ´´´js e ´´´ do código, beleza?

Sobre o código da aplicação em si, tenho dois pontos de atenção:

### 1. Consistência no uso do idioma no código

Não há problemas em implementar as aplicações em PT-BR. Porém, você precisa ser consistente com essa decisão no decorrer do código.

Se as variáveis estão sendo nomeadas em português do Brasil, prefira nomear a variável que armazena as respostas do usuário como `respostasDoUsuario` ao invés de `userRespostas`.

### 2. Cuidado para não esquecer `console.log`'s

O `console.log` é útil apenas no momento em que você está desenvolvendo a aplicação. Sempre que enviar código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele `console.log` também) =)

---

Você conseguiu implementar a aplicação sem grandes problemas, exceto pela pontuação.

Nesse ponto do treinamento, o esperado é que não haja dificuldades para implementar essa feature, pois é algo que usa ferramentas que já foram mostradas no treinamento. A inserção da pontução era um requisito.

Você disse que está com dificuldades em memorizar. Mas a sacada não é memorizar, é entender.

Pelo que você relatou como maiores dificuldades, meu sentido aranha diz que algo pode estar faltando. E pode estar relacionado à sua rotina de estudos. Se estuda todos os dias, pelo-menos 1h por dia, se está seguindo o passo a passo como recomendei [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928), inclusive executando a revisão raio-x, etc. Esses fatores influenciam diretamente nos seus resutados. 

Recomendo também que se inscreva no plantão da fluência para conversarmos sobre rotina de estudos. Eu considero perda de tempo falar sobre isso através de issues, a comunicação por texto não se compara a uma chamada de vídeo.

Estou recomendando os passos acima porque pelo que observo, os alunos que chegam nesse ponto do treinamento geralmente estão "afiados" para construir a aplicação e a implementação da exibição dos pontos por conta própria. 

Assista a aula inaugural que linkei acima e veja se o que eu falei faz sentido para você =)

@allanpedro

**Comment by Roger-Melo** [comment]
@allanpedro vou fechar a issue mas no que precisar, é só abrir uma nova =)
