### ISSUE TITLE
Resumo da Aula Eventos do teclado - 02 - 03 - da etapa 06

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#4143]
Nessa aula me foi apresentado o evento keyup. Esse evento possibilita a chamada de uma função de callbak
a cada pressionar/liberar de tecla do teclado. Iterando pelo elemento 'event', também é possível obter várias 
informações sobre o evento, como tecla acionada, possíveis teclas acionadas como complemento da ação e
mais... Esse tipo de evento possibilita uma interação dinâmica com o usuário.

**Comment by Roger-Melo** [comment]
Excelente @VitorPeixotoDev, rumo à fluência! 🎯
