### ISSUE TITLE
Resumo da Aula tipos de referência vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#4147]
## Tipos de dados vs Tipos de referência 

 

**Tipos primitivos**					 

- Numbers
- Strings 
- Booleans 
- Null 
- Undefined 
- Symbol 
- BigInt 

**Tipos de referência** 

- Todos os tipos de objeto 
 -Objeto literais 
 -Arrays 
 -Funções 
 -Datas 
 -Todos os outros objetos 

A diferença entre os tipos primitivos e os de referência está na forma como são armazenados na memória. 

Os tipos primitivos são armazenados na stack e os tipos de referência são armazenados na heap. A memória stack tem um acesso mais rápido que a heap, mas possui uma capacidade de armazenamento menor. A heap tem um espaço maior, por isso que ela fica encarregada de armazenar os tipos de dados de referência que são dados mais complexos e maiores.  

Quando atribuímos um tipo de dado primitivo à uma variável, esse dado é armazenado na stack e acessado pelo nome da variável. Quando armazenamos um tipo referência, exemplo um array armazenado numa variável fruits. O conteúdo do array é guardado na memória heap, mas a variável fruits guarda na memória stack um ponteiro que a ponta para o conteúdo que está na heap. Assim quando queremos acessar o conteúdo do array, estamos acessando a partir do apontamento que está na armazenado na stack a partir da variável fruits.

**Comment by Roger-Melo** [comment]
Excelente @MarioFilho1, rumo à fluência! 🎯
