### ISSUE TITLE
Resumo das Aulas 1,2,3 da etapa 03

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#4148]
[Aulas 1, 2, 3 - Etapa 03.zip](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/9115040/Aulas.1.2.3.-.Etapa.03.zip)

**Comment by Roger-Melo** [comment]
Excelente @George-Luis-Costa, rumo à fluência! 🎯
