### ISSUE TITLE
Resumo da Aula 03-04 - Trabalhando com JSON da etapa 11

### ISSUE THREAD

**Issue by EneasFeynlinus** [roger-melo-treinamentos/curso-de-js-roger-melo#4152]
**JSON = () => {**

    => JASON: Seria um formato de texto que o servidore retornam uma 
    informação requisitada, ele se parece com um array de objetos, no
    entanto é uma string JSON. O JASON é uma string que se parece
    com um array de objetos java script

    => Ele precisa ser uma string, pois quando o browser troca informaçao
    com o servidor elas precisam ser strings.

**}**

**transformandoJASONemOBJETO () => {**

      => Objeto imbutido no java script o JSON nos vamos encadear no 
    JSON o método parse() que significa transformar. Então vamos
    transformar a string JASON em objetos que podemos interagir com 
    as propriedades.

```Js
const data = JSON.parse(XMLHttpRequest.responseText)
````

    => Para criar seu proprio arquivo JSON crie outro file no seu diretorio
    de files com a extensão .json. Enão pode-se criar um array de objetos com
    as propriedades enre aspas seus valores strings em aspas tambem. Valores, 
    Booleans e valores falsy ou truthy podem ser escrito sem aspas

    => se trocarmos o endpoint do nosso método open() para o destino de nosso
    arquivo .json, então o request sera feito para o nosso arquivo JSON. E assim
    pode se utilizar o metodo parse() para manipular as propriedades e valores
    do objeto.

**}**

```JS
const getTodo = callback => {
    const request = new XMLHttpRequest

    request.addEventListener('readystatechange', () => {
        const isRequestOk =
            request.readyState === 4 && request.status === 200
        const isRequestNotOk =
            request.readyState === 4

        if (isRequestOk) {
            const data = JSON.parse(request.responseText)
            callback(null, data)
            return
        }

        if (isRequestNotOk) {
            callback("Unable to get endPoint", null)
        }
    })

    request.open('GET', './todos.json')
    request.send()
}

getTodo((error, data) => {
    if (error) {
        console.log(error)
        return
    }
    console.log(data)

})
```

**Comment by Roger-Melo** [comment]
Show @EneasFeynlinus. Vamo que vamo, rumo à fluência! 🙌
