### ISSUE TITLE
Resumo da Aula outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#4157]
**Outras maneiras de fazer queries no DOM**  
 
Obter elemento através do Id: 

`const $title = document.getElementById(‘title’)` -> Esse método pega a referência do elemento que tem o id title e coloca na variável _$title_. Como esse método busca o elemento pelo id, não é necessário fazer uso do hash ‘#’ no início da string para especificar o id.  

 
Obter elementos através do nome da classe: 

`const $erros = document.getElementesByClassName` -> A variável erros guarda uma referência do conteúdo das classes erros. O conteúdo guardado é um HTMLcollection. É similar a um nodeList, mas mais limitado. É possível acessar cada item com a notação de colchetes, mas não é possível interar pelas posições através do forEach como acontece com o nodeList. 

Obter elementos através do nome da tag: 

`const paragraphs = document.getElementsByTagNames(‘p’)` -> Também guarda em formado de um HTMLcollection o conteúdo das tags ‘p’

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
