### ISSUE TITLE
Etapa 4, nome do vídeo: Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by rodrigoljpereira** [roger-melo-treinamentos/curso-de-js-roger-melo#416]
Olá Professor Roger, tudo bem? 

Poderia me explicar de uma outra forma, o que acontece nesse código?

```js
const getTypeDefinition = type => { //aqui estamos recebendo  como parâmetro o tipo de dado
  const obj = {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }

  return obj[type] //aqui estamos passando a variável que está com o valor passado por argumento no console.log
}

console.log(getTypeDefinition('null'))
console.log(getTypeDefinition('undefined'))
console.log(getTypeDefinition('object'))

```

O que não consegui entender, é como que o **[type]**, faz referencia a propriedade do objeto dentro da função, pra poder retornar o valor. Pois o valor passado por argumento no console é uma string, mas a propriedade(a chave) do objeto não é. Apenas os valores dessas propriedades são strings. Então, não consegui entender essa parte. Poderia me explicar? 

Espero ter conseguido passar a minha duvida!

Desde já agradeço.

@Roger-Melo

**Comment by YureK-a** [comment]
Quando você dá o valor do argumento da função getTypeDefinition, null por exemplo, o javascript vai procurar uma propriedade com o mesmo nome do valor. Experimente colocar um console.log(getTypeDefinition('NULL'); resultará em undefined. Mesmo que o nome da propriedade não seja uma string, o javascript reconhece ele e faz a comparação.

**Comment by rodrigoljpereira** [comment]
Hum, agora eu entendi. Obrigado pela ajuda!!

**Comment by Roger-Melo** [comment]
Oi Rodrigo.

Independente do valor que uma propriedade armazena (ou se ela é ou não é uma string), para ela ser acessada com a sintaxe de colchetes, o que é colocado dentro dos colchetes precisa ser uma string:

```javascript
const obj = { prop1: 1 }

obj['prop1'] // 1
```

Você pode inserir qualquer expressão dentro dos colchetes, mas por baixo dos panos, para acessar a propriedade, o resultado dessa expressão será convertido para string:

```javascript
const obj = { prop1: 1 }
const obj2 = { 1234: 'olá' }

obj['prop' + 1] // 1
obj2[1234] // 'olá'
```

Além disso, objetos javascript podem ter strings como propriedades:

```javascript
const obj3 = { 'prop1': 1 }

obj3['prop1'] // 1
obj3.prop1 // 1

obj3['prop2'] = 2

obj3['prop2'] // 2
obj3.prop2 // 2
```

Por isso, é possível acessar as propriedades de um objeto através da invocação de `getTypeDefinition('null')`, por exemplo. Então sim, por questões de mecanismos da implementação da linguagem (que não vem ao caso agora), é possível acessar propriedades de objetos através de strings sem que essas propriedade sejam (necessariamente) strings.

Ficou mais claro?

@rodrigoljpereira

**Comment by rodrigoljpereira** [comment]
Sim Roger, ficou mais claro sim. Obrigado pela atenção!!

**Comment by Roger-Melo** [comment]
Legal @rodrigoljpereira. Já que ficou mais claro vou fechar a issue, mas quando surgirem dúvidas, é só abrir uma nova =)
