### ISSUE TITLE
Resumo da Aula A aula mais importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4187]
Etapa 00 - Boas Vindas
A aula mais importante do CJRM

Vamos ao final do curso construir 4 aplicações completas com JavaScript puro.
São 15 etapas no curso. Nas 7 primeiras vamos aprender os fundamentos e vamos construir a primeira aplicação.
A partir da etapa 8 vamos aprender conceitos e features em pouco mais avançadas.

As 4 aplicações que faremos durante o curso serão um Quizz Interativo, um To-Do-List, um Conversor de Moedas, e
uma aplicação de previsão do tempo.

8 Marcos da Jornada da Fluencia

Alicerce -> 
1) Assistir a aula inaugural ate o final
2) Postar o resumo de cada aula no repositório
3) fazer uma revisão Raio-X antes de implementar cada aplicação

Validação ->
4) Montar um portifólio com as 4 aplicaçoes
5) Se candidatar para as vagas ao terminar a etapa 15

Evolução ->
6) Implementar o feedback dos recrutadores.
7) Ser contratado

Comemoração ->
8) Comunicar a sua contratação

Passo a passo do marco

Marco 1) Assistir a aula inaugural ate o final
CONCUÍDO

Marco 2) Postar o resumo de cada aula 

Para postar os resumos no repositorio do curso, vá ao GitHub, 
clique em Issues, depois clique no botão New Issues, e clique no tipo de Issue que quer postar,
no caso a Issue Resumo. Coloque o nome da aula no lugar do Xxxxx e a etapa.
podemos postar arquivos de fotos caso tenhamos escrito o resumo a mão, no caderno.

Na plataforma do curso nao há campo para tirar dúvidas abaixo de cada vídeo.
Devemos tirar dúvidas pelo repositório do curso que esta no link abaixo de cada aula.

Postar as duvidas no repositório é melhor por 3 principais motivos.

PRIMEIRO MOTIVO
Porque na area de input da plataforma o codigo postado seria renderizado como texto
E nao teria sintaxe highlight (que é o texto colorido conforme o codigo).

Para acessar o repositório de duvidas vamos em Issues, New Issues, Duvidas.
E siga as instruções

Para inserir um codigo JavaScript basta inserir 3 crases ,  o tipo de codigo, 
e fechar com 3 crases
```JS 
console.log("area para código JavaScript)
``` 

Para inserir um código HTML
```HTML (tudo maiúsculo)
<h1>(Area de codigo HTML)</h1>
```

SEGUNDO MOTIVO
Se o curso trocar de plataforma as informações, duvidas, resumos e outras coisas não serão perdidos

TERCEIRO MOTIVO
Inteligência coletiva.
Na plataforma não dá para pesquisar comentários
E a pesquisa no Git Hub é muito mais eficiente.
Por exemplo se pesquisarmos sobre CallBack
Pode ser que a maioria das respostas a pesquisa sejam resumo das aulas.
Para resolver esse problema, clique em Labels, veja qual label tirar da pesquisa
segure a tecla ALT e clique na label Resumo e o texto -Label>Resumo foi adicionado ao Input
Se clicarmos em alguma Issue aberta e darmos o comando CTRL + F e pesquisar CALLBACK nessa Issue.
Se por acaso houver mais de uma ocorrência da palavra CALLBACK na Issue, podemos navegar pelas
por cada ocorrência pressionando F3 para avançar e Shift F# para voltar.
Caso as Issues abertas nao solucionem a duvida. Abra uma nova Issue
Atenção para postar as Issues com as informações corretas. coloque Etapa, nome e URL (CTRL + L - seleciona a URL)
 

Marco 3) Revisão Raio-X

Caso a solução dada tenha ficado diferente da do professor. Não podemos pensar q só porque entendemos a correção,
agora sabemos como resolver o problema.
Se o professor resolveu daquele jeito, nos próximos exercícios vai ser potencializado os princípios
daquela fora de resolução.
O intuitivo é ver a correção, corrigir junto e achar que a solução ficou óbvia.
Entender a correção do exercício não é o suficiente.
Porque entender é muito diferente do fazer.
O correto é >>
1)Depois de resolver o exercício na correção junto ao professor, Apagar o código e refazer sozinho.
Porque entender é diferente de fazer. Porque executar junto com o professor , vai ser só replicar o que ele esta fazendo.

2) Implementar sozinho o código que o professor mostrou na correção do exercício, sem olhar a correção.
É nesse passo que vamos de fato executar sozinhos o raciocínio que foi mostrado na correção.

3)Se o momento que estamos implementando a resolução sozinho, e não conseguirmos, podemos consultar as anotações que foram feitas
durante a aula ou as anotações feitas durante a etapa da teoria ou consultar o MDN ou procurar
o ponto da aula que esclareça a duvida. 
Quando esclarecer a duvida, é importante que apague todo o código e implemente ele novamente sozinho, do zero.
Para não usar anotações como muleta e não deixar o cérebro fixar bem as sequências de resolução do exercício.

A REVISÃO RAIO-X É
Um tipo de revisão usando engenharia reversa. explicada em um link abaixo do vídeo

Marco 4) Montar um portifólio com as 4 aplicações
Ao montar u  portifólio com as 4 aplicações feitas no CJRM
Essas aplicações precisam estar no GitHub e tambem hospedadas em um domínio de fácil acesso e que
qualquer pessoa possa acessar

Marco 5) Se candidatar para as vagas ao terminar a etapa 15

Marco 6) Implementar o feedback dos recrutadores

Marco 7) ser contratado

Marco 8 Comunicar a contratação

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr, rumo à fluência! 🔥
