### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4189]
### Etapa da aula

1

### Nome da aula

Exercícios da Aula 01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/733512

### Descreva a dúvida

Boa noite Roger, estou com problemas, minha maquina é de 32 bits e o hyper requer 64 bits, 
Com isso não consigo fazer o download das atividades conforme explicação na aula.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @EdsonAjjunior!

Veja se vc consegue instalar o [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install).

Se não conseguir, vc pode usar o [Power Shell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.2).

Teste e me avise =)

**Comment by EdsonAjjunior** [comment]
Professor,

Eu fiz o seguinte, baixei o arquivo zipado, tirei o zip em uma pasta e abrir pelo VS CODE na parte FOLDER, localizei a pasta que estava a lista de Exercícios 01 e consegui abrir perfeitamente.

Inclusive conclui os exercícios agora mesmo.
Muito bom por sinal 👏🏾

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Roger-Melo** [comment]
Boa! É uma alternativa tb =)

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
