### ISSUE TITLE
Resumo da Aula mais importante  da etapa 00

### ISSUE THREAD

**Issue by Dan0668079** [roger-melo-treinamentos/curso-de-js-roger-melo#4194]
CJRM 
Caminho para postar o resumo
issues -> new issues -> resumo

Caminho para postar o duvida
issues -> new issues -> duvida

Caminho para postar o resumo
issues ->  lupa para pesquisar  + enter para excluir aperte alt + e clica o que quer excluir 
clicar na lista e da um ctrl F
f3 para navegar para a próxima ocorrência ou shift + f para a ocorrência anterior

Postar dúvida 3 clic copiar o nome da aula ctrl para selecionar a barra do browser ctr c ctrl v
Revisão raio x 
Resolver os exercícios junto
Apagar o exercício e fazer sozinho
Consultar o meu resumo, MDN, ater a minha duvida, apagar o código novamente e fazer sozinho.

**Comment by Roger-Melo** [comment]
Boa @Dan0668079, rumo à fluência! 🔥
