### ISSUE TITLE
Etapa 4, Exercícos - Aula 03

### ISSUE THREAD

**Issue by Henrique-SPinheiro** [roger-melo-treinamentos/curso-de-js-roger-melo#42]
Roger, tudo bem?

Não tenho dúvidas, mas tenho um pouco de dificuldade em pensar na lógica para resolver o exercício. Quando você resolve eu vejo que na verdade é super simples. Esta semana eu pretendo refazer alguns exercícios de funções, pois ainda não entrou muito na minha cabeça quando devo alterar ou utilizar os "()" (vazios) no final da função,  saber iterar e etc... Acho que mudando um pouco o enunciado já me ajuda, pois vejo que se trata de falta de prática. Tem alguma sugestão pra melhorar isso?

Obrigado.

@Roger-Melo

**Comment by GoharaJunior** [comment]
@Henrique-SPinheiro Eu também estou na mesma, revendo conteúdo para poder fixar mais. Creio que isso seja mal de iniciante e acho que com o tempo vamos desenvolvendo isso e geralmente eu eu paro após finalizar algum modulo e volto apenas nos exercícios e tento refazer, a meta é acerta todos, mas caso meu índice de acerto seja baixo, eu revejo o modulo.

**Comment by Roger-Melo** [comment]
Oi Henrique.

Essa dificuldade inicial é normal. No início, qualquer coisa é mais difícil. Mas vou te dar sugestões do que fazer.

> pois ainda não entrou muito na minha cabeça quando devo alterar ou utilizar os "()" (vazios) no final da função

Eu não sei em que aula específica você está, pois não está escrito no título da issue, mas basicamente, você irá utilizar os `()` no final do nome da função quando quiser executar o código dentro dos blocos da função.

```javascript
const myFunc = () => {
  console.log('oi')
}
```

No código acima, uma função `myFunc` foi declarada.

Quando eu quiser executar o `console.log('oi')` dentro do bloco da função, eu invoco a função especificando o nome dela e em seguida os `()`:

```javascript
myFunc() // 'oi' é exibido no console
```

Se precisar rever as aulas de introdução a funções, é só clicar [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/790702).

> saber iterar e etc...

No quê, especificamente, você tem dúvidas em relação à iterações?

Quando a dúvida é específica, fica mais fácil eu entender ela e ajudar =)

> Acho que mudando um pouco o enunciado já me ajuda, pois vejo que se trata de falta de prática.

Alguns enunciados dos exercícios realmente não entregarão uma descrição do que deve ser feito. Mas se houver alguma dúvida sobre o enunciado, pode abrir uma issue que te ajudo a entender.

---

Sobre dificuldades no aprendizado, nenhum bloqueio resiste a um bom método.

Se você quer melhorar seus resultados nos estudos, avalie os 6 indicadores-chave de performance:

1. Quanto => Sua meta diária. Quantas horas diárias você estuda;
1. Quando => Os dias que você estuda. De preferência, todos os dias;
1. Onde => O ambiente te influencia pro bem ou pro mal;
1. Por onde => É o material que você usa para estudar (aula, anotações, exercícios, etc);
1. O quê => É o quê você estuda. No CJRM, isso já é filtrado. É o conteúdo que vai te levar à fluência;
1. Como => É o método de estudos que você aplica.

---

Verifique se o ATER está sendo seguido.

No começo, o "T" não precisa ser seguido à risca. Os parágrafos da documentação no MDN contém vários links que levam assuntos mais avançados que podem confundir, no começo. À medida em que você avança no treinamento, notará que eu vou começar a deixar links para a documentação abaixo dos vídeos.

Mas, definitivamente, no "A", de aula, fazer resumos das aulas é essencial.

A escrita exige que o cérebro foque na aula e, posteriormente, suas anotações serão materiais de consulta nos exercícios e revisão.

Em quais pontos que mencionei acima você precisa melhorar?

@Henrique-SPinheiro

**Comment by GoharaJunior** [comment]
Ótimas dicas Roger!

**Comment by Henrique-SPinheiro** [comment]
Perfeito, Roger.

Já ficou mais claro com sua explicação sobre os parenteses no final.

Vou me reorganiza com as dicas.

Obrigado pelo retorno.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Roger-Melo** [comment]
Legal Henrique! Vou fechar a issue por agora, mas se tiver qualquer dúvida é só abrir uma nova issue =)

**Comment by MarcusViniciusTavaresRangel** [comment]
Olá amigo, sei que perguntou ao Roger, mas se eu puder ajudar, acredito que estejam faltando as crases para formar um template string. console.log(` Em ${currentYear + ten }. ..`). Vê, logo após o primeiro parênteses?

**Comment by clsouza** [comment]
Olá Marcus

  Não sei o motivo mas as crases estão lá: 
console.log(`Em ${currentYear + ten}, estarei com ${myBirthYear + ten} anos.`)

**Comment by MarcusViniciusTavaresRangel** [comment]
Pois é meu amigo, eu havia esquecido que o GitHub usa Markdown e por isso as crases são incorporadas e não exibem, por isso pensei que você tivesse esquecido. Enfim, neste caso, acredito que seja melhor postar o código do exercício todo com as declarações das variáveis currentYear e myBirthYear para vermos onde está no erro. Abraço!

Enviado do Yahoo Mail no Android 
 
  Em qua, 31 31e mar 31e 2021 às 11:35, ***@***.***> escreveu:   


Olá Marcus

Não sei o motivo mas as crases estão lá:
console.log(Em ${currentYear + ten}, estarei com ${myBirthYear + ten} anos.)

**Comment by Roger-Melo** [comment]
Olá Cleber.

Quando estiver com dúvidas, prefira abrir uma nova issue. 

Preciso ver o código completo para ajudar. 

### Para abrir uma nova issue, basta acessar o painel `issues`,

![01](https://user-images.githubusercontent.com/29297788/113204974-1acce880-9244-11eb-8824-f5ff533f453f.jpg)

### e clicar no botão para abrir uma issue de dúvida:

![02](https://user-images.githubusercontent.com/29297788/113205094-44860f80-9244-11eb-9e64-7aced6019600.jpg)

Fazendo isso, você vai ver as instruções de como a issue deve ser aberta =)

@clsouza 

Ps: Obrigado pela contibuição, @MarcusViniciusTavaresRangel =)
