### ISSUE TITLE
Resumo da Aula While loop e exercícios da etapa 02

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#420]
Vamos falar agora do *loop while*, que faz exatamente a mesma coisa que o *loop for*: executa um bloco de código um determinado número de vezes. A única diferença entre os dois é a sintaxe. O *loop while* tem como argumento apenas a condição. Por exemplo, ```while (i < 7) { console.log(`Dentro do loop: ${i}`) }``` ou seja, enquanto i for menor do que 7, faça alguma coisa (nesse exemplo, exibimos algo no console). Porém se executarmos o código apenas da forma como está, teremos alguns problemas. O primeiro é que a variável i não foi inicializada. Então antes do *loop while*, precisamos declarar uma ```let i = 0```, para iniciarmos o i com o valor zero. Mas ainda assim se salvarmos e executarmos, teremos o problema de *loop* infinito, que fatalmente irá travar o browser de tanto console.log() que será executado, pois a condição do *while* nunca retornará *false*. Então dentro do bloco de código que será repetido, a última instrução será o incremento da variável i. Vamos ver na prática:

```jsx
let i = 0;

while (i < 7) {
	console.log(`Dentro do loop: ${i}`);
	i++;
}

// Dentro do loop: 0
// Dentro do loop: 1
// Dentro do loop: 2
// Dentro do loop: 3
// Dentro do loop: 4
// Dentro do loop: 5
// Dentro do loop: 6
```

Agora vamos ver um exemplo da utilização do *loop while* iterando sobre um *array* de nomes e os exibindo no console:

```js
const names = ['Phil', 'Claire', 'Haley', 'Alex', 'Luke'];

let i = 0;

while (i < names.length) {
	console.log(names[i]);
	i++;
}

// Phil
// Claire
// Haley
// Alex
// Luke
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! 🔥
