### ISSUE TITLE
Resumo da Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4205]
Constantes, variáveis e comentários

As variáveis armazenam um valor que pode ser um nome, um email, um numero, ela armazena esse valor para que possamos usar ela mais tarde aonde quisermos, existem formas diferentes de se declarar uma variável no JavaScript

Regras das Variáveis no Geral
Uma variável é definida por uma única palavra ela pode ser mundoNovo mas não poderia ser mundo Novo, para usar duas ou mais palavras para se nomear uma variável é preciso empregar as regras da CamelCase, sendo assim a primeira palavra em a letra minúscula e as demais palavras possuem sua primeira letra maiúscula.
Nomes de variáveis não podem começar com números.
Não é possível declarar variáveis que são palavras chaves reservadas. Ex: let, cost...

= é um símbolo de atribuição, ele e outros símbolos podem ter significados distintos no JavaScript.

let é uma variável que pode ter seu valor reatribuído conforme o código for escrito, será uma das variáveis mais usadas no curso junto com const.
const é uma constante, ela faz com que o valor que lhe é atribuído não possa ser mais mudado ao longo do código.
var é uma variavel similar a let que era usada nas versões antigas do JavaScript.

E por fim comentários no código podem ser feitos com // para uma linha ou     /* e */ para blocos de linhas inteiros.

**Comment by Roger-Melo** [comment]
Boa @Hugones45, rumo à fluência! 🔥
