### ISSUE TITLE
Resumo da Aula 02-04 da etapa 01 | Métodos comuns de strings

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4207]
### lastIndexOf
O método lastIndexOf retorna a ultima ocorrência do valor especificado encontrado na String
```js
const email = diego@gmail.com

const lastIndexOfA = email.lastIndexOf('e')
```
Neste caso o valor retornado será 2, já que o indice do valor especificado se encontra na posição 2

### slice
Temos tambem o método slice() que serve para extrair parte de uma string.

O primeiro argumento do método slice é o elemento a partir do qual faremos a extração, o segundo argumento é onde especificamos a parte que será cortada da string
```js
const emailSlice = email.slice(2, 4)
```
### replace
O método replace serve para substituir uma string por outra.

O primeiro argumento do método é o que queremos substituir, o segundo argumento é pelo que queremos substituir.
```js
const emailReplace = email.replace('D',  'T')
```
Aqui o haverá uma substituição da string D por T ficando o valor da variável emailReplace sendo Tiego@gmail.com

**Comment by Roger-Melo** [comment]
Boa @Diegodkid, rumo à fluência! 🔥
