### ISSUE TITLE
Etapa 01, nome do vídeo: Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#421]
Olá, tudo bem? Eu vou refazer como você mostrou, só queria te mostrar como eu cheguei ao resultado do exercício 21. 

Há muita diferença entre a sua resolução e a minha? Você acessou o índice de um caractere por colchetes e invocou o método .toUpperCase e eu fatiei as strings nas partes desejadas através dos índices também. Há alguma diferença além do modo de resolução, como desempenho por exemplo? 
```js

const name = 'walter white'

let newName = `${name.slice(0, 6).replace('w','W')} ${name.slice(7).replace('w','W')}`

console.log(newName)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcus Vinicius.

No momento, não se preocupe com desempenho ou performance de código, isso será visto em etapas mais avançadas. Foque-se apenas em absorver o que está sendo passado nas aulas.

Quando houver diferentes formas de resolução, tente captar os princípios que usei para resolver daquela forma. Observe que um dos critérios da resolução do exercício é não digitar a nova string manualmente (e claro, apenas os 'w's foram inseridos de forma manual).

Pela sua forma de resolver, percebi que você não teria grandes dificuldades em aplicar o padrão de resolução demonstrado na correção em exercícios futuros. Então, tá tudo certo =)

@WebDevCampos

**Comment by Roger-Melo** [comment]
@WebDevCampos vou fechar a issue mas quando surgir alguma dúvida, é só abrir uma nova =)
