### ISSUE TITLE
Resumo da Aula 02 - 02 da etapa 01 | Um overview sobre tipos de dados

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4211]
Nesta aula aprendemos sobre tipos de dados que contem no javascript, existem pelo menos oito tipos:
**Númber, String, Boolean, Null, Undefined, Object, Bigint e Simbol**;

Cada um desses tem suas tipagens e locais que podem ser aplicados, podendo mudar por características, símbolos e etc.

O javascript é uma plataforma de tipagem dinâmica então não necessitamos descrever qual destes estaremos usando, que a propria plataforma consegue compreender cada elemento sem precisar fazer distinção deles, diferente de outras plataformas que precisam ser definidos como o python por exemplo.

**Comment by Roger-Melo** [comment]
Boa @EdsonAjjunior, rumo à fluência! 🔥
