### ISSUE TITLE
colocar múltiplos argumentos no parâmetro de uma função

### ISSUE THREAD

**Issue by CarlosHenrique2208** [roger-melo-treinamentos/curso-de-js-roger-melo#4228]
### Etapa da aula

3

### Nome da aula

Arrow functions - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803287

### Descreva a dúvida

queria saber como faz para que eu possa colocar diversos argumentos em um parametro da função sem ter que ficar "ditando uma quantidade fixa".

Estava refazendo as atividades do curso e uma delas pedia para eu transformar uma function normal em arrow function:

```js
/*
  01

  - Converta a função abaixo em uma arrow function e utilize-a para exibir um  
    valor no console.
*/

function convertToString (value) {
  return String(value)
}
```

quando transformei em arrow function, para testar eu coloquei dois argumentos booleanos no console, um na função e outro não:

```js
const convertToString = value => {
    return String(value)
}

console.log(`${convertToString(true)}`, true)
```
fiz isso pois a cor de um valor string e um valor booleano no console do navegador mudam, então fica:
![image](https://user-images.githubusercontent.com/85198581/180056556-20bb0ec5-e4d4-4592-a509-a017eb33bfc2.png)

depois que fiz a questão pensei em substituir o '_console.log_' por uma function '_log_':
```js
const log = (itemInConsole = 'insira algo') => console.log(itemInConsole)

log(`${convertToString(true)}`, true)
```

resultado: não apareceu o segundo argumento(o valor booleano)
![image](https://user-images.githubusercontent.com/85198581/180057665-18001c67-fb6b-4879-b7de-e99093294b2f.png)

@Roger-Melo

**Comment by iurisilvag** [comment]
Boa tarde, acredito que não esteja retornado o segundo argumento pois você não o passo como parâmetro, logo ele só tem como trabalhar com o primeiro

EX:
const log = (item1 = true, item2 = false)=>{
console.log(String(item1), String(item2), item1, item2)
}

se você não passar o primeiro tudo bem, pois deixou uma opção de autocomplete ('intemImConsole ='insira algo''), porem o segundo argumento não esta sendo chamado após o return (=>)

respondendo a sua duvida: para utilizar mais de um parametro, é só utilizar a virgula 

ex: const log2 = (para1, para2)=>console.log(para1 , para2)

**Comment by CarlosHenrique2208** [comment]
sim, oq estou dizendo é exatamente isso, não quero ficar colocando um valor possível de parâmetro(item1, item2, item3...) o que eu queria era saber se eu posso escrever o codigo de maneira que **independentemente de quantos argumentos eu coloque, todos irão aparecer sem erro e sem eu precisar ter colocado uma predefinição**

**Comment by Roger-Melo** [comment]
Olá @CarlosHenrique2208!

Existe uma forma sim de vc inserir uma quantidade indefinida de argumentos e a função receber todos esses argumentos através de um "parâmetro especial". Quando uma função possui essa característica, ela é chamada de função variádica. 

Essa forma de compactar os argumentos em um só parâmetro é chamada de rest parameters e será mostrada em aulas mais avançadas no CJRM. 

Só que até lá, vc ainda verá alguns conceitos que são pré-requisitos para aprender rest parameters. Então nesse caso, talvez faça mais sentido não buscar esse conceito agora...

Faz sentido para vc? =)

---

PS: valeu pela contribuição, @iurisilvag =)

**Comment by CarlosHenrique2208** [comment]
faz total sentido, obrigado.
