### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4234]
# let

Declara uma variável local no escopo do bloco atual, opcionalmente iniciando-a com um valor.

Basicamente let permite que você declare variáveis limitando seu escopo no bloco, instrução, ou em uma expressão na qual ela é usada. 

Isso é inverso da keyword var, que define uma variável globalmente ou no escopo inteiro de uma função, independentemente do escopo de bloco
 
Nota1: Tipo de variável que pode reatribuir valor limitando o contexto do bloco, com exceção para funções.
 
Nota2: Redefinição da variável no mesmo escopo do bloco causa typeError. Exemplo:

```js
 if (x) {
     let foo;
     let foo; // Emite um TypeError.
 }
```
	
Nota3: Redefinição da variavel let no mesmo escopo de uma função, não causa problemas. Exemplo:

```js
 function do_something() {
     let foo = 1;
     let foo = 2; // Isso funciona.
 }
```
	
## const
Constantes possuem escopo de bloco, semelhantes às variáveis declaradas usando o palavra-chave let.

Nota: Uma vez atribuido um valor a uma constante, seu valor não pode ser alterado. Exemplo:

```js
const number = 42;

try {
  number = 99;
} catch (err) {
  console.log(err);
  // expected output: TypeError: invalid assignment to const `number'
  // Note - error messages will vary depending on browser
}

console.log(number);
// expected output: 42
```

## comentários

Eles podem ser adicionados para uma única linha através do // ou em bloco através do /* */.  Exemplo:

```js
 // Linha

 /*
   Bloco
   Bloco
   Bloco
 */
```

**Comment by Roger-Melo** [comment]
Show @silvasouzaadriano. Vamo que vamo, rumo à fluência! 🙌
