### ISSUE TITLE
Resumo da Aula obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#4243]
## Obtendo, adicionando, removendo e alternando classes CSS 

Primeiro criamos um arquivo css separado onde foram inseridos os seletores com os estilos das classes. 

Podemos exibir uma lista com as classes que o elemento possui com a propriedade classList. Console.log(‘paragraphs.classList’). Obtemos um DOMTokenList, um objeto similar a um array com as classes do elemento. 
```js
paragraphs.classList.add(‘error’) -> adiciona uma classe no elemento ‘p’ 

paragraphs.classList.remove(‘error’) -> remove a classe do elemento ‘p’ 
```

_TextContent_ -> Assim como o innerText, essa propriedade também é utilizada para obtermos um texto que o elemento contém. A diferença o innerText obtém o texto visível que o elemento contém, já a textContent obtém o texto ainda que ele não esteja visível. Ex. A propriedade display none é utilizado para ocultar um elemento página. Se utilizarmos a propriedade textContent, ainda que o texto esteja oculto, esta propriedade irá obter o texto.  

_ClassList.toggle( )_ -> Esse método adiciona e remove uma classe passada entre parênteses. Se a classe existe, da próxima vez que o método for invocado a classe é removida, e quando o método for invocado novamente a classe será adicionada e assim sucessivamente.

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
