### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4245]
Uma das maiores praticidades dos templates strings é injetar variáveis dentro de strings sem ter que fechar a strings declarar um , +, depois abrir outra string, etc.

OBS: Termo Template Literals e Template String são a mesma cosia.

USANDO CONCATENAÇÃO
Para colocar aspas dentro de uma string é preciso ficar atento, se string estiver envolvida com aspas duplas " " as aspas dentro de alguma palavra dentro dessa string precisam ser aspas simples ' ', já se a string estiver envolvida com aspas simples, as aspas dentro dessa string precisam ser aspas duplas.
Outra solução é escapar as aspas que estão dentro da string envolvida utilizando barras invertidas ( \ )
Ex: "O canal do youtube do ( \ )"senhor( \ )" Hugo tem muitos inscritos."     <--- Repare como nessa string todas as aspas são aspas duplas. Detalhe, esses parênteses nas barras invertidas foram colocados apenas para que as barras invertidas aparecessem.  Caso haja duvida teste um console.log("O canal do youtube do ( \ )"senhor( \ )" Hugo tem muitos inscritos." ) sem os parênteses. 

USANDO TEMPLATE STRINGS
Strings envolvidas em crase podem usar um recurso chamado de interpolar ${ } para que elas sejam renderizadas, o que facilita o entendimento da string escrita no JS.

TEMPLATE HTML
Com o template strings é possível também criar um template HTML e injetar nele conteúdo dinâmico. Mais sobre esse uso do template strings em templates html será abordado ao longo do curso.

**Comment by Roger-Melo** [comment]
Show @Hugones45. Vamo que vamo, rumo à fluência! 🙌
