### ISSUE TITLE
Resumo da Aula 02-06 da etapa 01 | Template strings

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4251]
Nesta aula aprendemos a fazer template strings são essas abinhas invertidas **``**, vimos também que não é necessário usar esta ferramenta, no melhor dos casos é quando os códigos pedem dígitos, ai utilizamos template pra deixar o código mais limpo e mais compreensivo.

**Comment by Roger-Melo** [comment]
Show @EdsonAjjunior. Vamo que vamo, rumo à fluência! 🙌
