### ISSUE TITLE
Resumo da aula O método sort - aula 02-02 da etapa 08

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#4255]
O MÉTODO SORT()

O método `sort()` ordena os elementos do próprio array e retorna o   array. 

A ordenação NÃO é necessariamente estável. A ordenação padrão é de acordo com a PONTUAÇÃO DE CÓDIGO UNICODE. 
  
Exemplo: Em um array de números com mix de unidades e dezenas, pode ser que o método `sort()` não organize os números de forma crescente/decrescente, pelo fato deles terem um valor unicode por baixo dos panos, que não é o mesmo valor de uma sequência númerica normal.

Resultado uso do `sort()` em arrays de strings?
R: Os itens serão organizados em ordem alfabética unicode, de acordo com o primeiro index da string, caso não usar função de comparação.

Resultado uso do `sort()` em arrays numéricos?
R: Caso usado função de comparação, podemos organizar esse array em ordem crescente, descrescente e ordem unicode.

O que é função de comparação?
R: É uma função que vai dentro do método `sort()`, ela decide a ordem em que o array será retornado.

OBS: Método `sort()` modifica o array original, mesmo que seja uma `const`.

```js
/* EXEMPLO 1 */

const things = ['word', 'Word', '1 Word', '2 Words']

things.sort()
console.log(things) // ['1 Word', '2 Words', 'Word', 'word'] (ordem unicode)

/* EXEMPLO 2 */

const numbers = [2, 1, 10, 4, 6]

/* ORDEM CRESCENTE */
numbers.sort((a, b) => a - b)
console.log(numbers) // [1, 2, 4, 6, 10]

/* ORDEM DECRESCENTE */
numbers.sort((a, b) => b - a)
console.log(numbers) // [10, 6, 4, 2, 1]

/* ORDEM UNICODE*/
numbers.sort()
console.log(numbers) // [1, 10, 2, 4, 6]
```

**Comment by Roger-Melo** [comment]
Show @rafaelpradoj. Vamo que vamo, rumo à fluência! 🙌
