### ISSUE TITLE
Resumo da Aula 01-02 da etapa 01-02 

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#4256]
código asincrônico é  um código que inicia um processo agora e finaliza o processo posteriormente. Quando existe a requisição, o  browser lida com essa requisição em outra thread, e com isso o javascript pode tratar suas tarefas na sua thread de forma continua. Esse código não é um bloking code.

A natureza do Java script e executar o código síncrono , ou seja executar uma tarefa de cada vez de cima para baixo ( ou seja, single thread). Porem esse código tem um ponto baixo, que é exatamente o fato de ser executado uma instrução de cada vez ,caso haja no código uma requisição para um banco de dados e essa requisição por sua vez demore alguns segundos, a instrução seguinte vai ter que esperar ate que essa que esta sendo executada seja terminada, podemos chamar esse código de código blocante (bloking code).

**Comment by Roger-Melo** [comment]
Show @Sansanoski . Vamo que vamo, rumo à fluência! 🙌
