### ISSUE TITLE
Aplicação: [Quiz interativo ]

### ISSUE THREAD

**Issue by Felipe-HVSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#426]
[Link](https://github.com/Felipe-HVSilva/quiz-interativo) do repositório.

Minha maior dificuldade foi nos events, estou me confundindo na hora de 'pegar' eles, mas já vou dar uma revisada, para mostrar os pontos, usei a ideia do popup, mas de resto foi bem tranquilo

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @Felipe-HVSilva.

Passando para dizer que sua issue foi visualizada e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Felipe.

Parabéns pelo esforço em construir a primeira aplicação dentro do CJRM =)

Antes da análise, deixa só eu dar uma dica.

O repositório é [este](https://github.com/Felipe-HVSilva/quiz-interativo), certo?

Para inserir a url de um repositório em issues do GitHub, basta colar o link desta forma: `[texto do link](url)`. A `url` entre os parênteses deve ser a da página do respositório (https://github.com/Felipe-HVSilva/quiz-interativo). Editei essa parte na issue que foi aberta acima.

Vou deixar abaixo alguns pontos de atenção sobre os critérios que vejo que podem ser melhorados

## Lógica

O código abaixo não é necessário.

```javascript
button.addEventListener('click', () => {
  popupWrapper.style.display = 'block'
})
```

A inserção do display block no popup pode ser inserida na última linha do callback do listener de evento de envio do form.

## Organização de código.

### Inconsistência no idioma

Consts `popupContent` e `respostasCorretas` não devem coexistir. Escolha um idioma e seja consistente nessa escolha.

### Nomes de variáveis e funções

Nomes de funções devem ser verbos. Devem descrever uma ação.

`pontos` é um substantivo. 

Prefira usar substantivos apenas para nomear variáveis.

---

Prefira nomear variáveis que armazenam booleans com `is` ou `should`. Seguindo esse raciocínio, `close` pode ser nomeada como `shouldClose` ou `shouldClosePopup`.

Recomendo que veja novamente [a aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890854) de implementação do popup, mas esta vez, focando nos nomes dados as variáveis.

### Inconsistência na formatação do código

Nos trechos de código abaixo,

```javascript
button.addEventListener('click', () => {
  popupWrapper.style.display = 'block'
})

respostasMarcadas.forEach((resp, index) =>{
  // ...
})
```

há uma inconsistência na declaração da abertura dos blocos. Um deixa espaço em branco antes da abertura do bloco e outro não. Escolha uma das duas formas e seja consistente no decorrer do código.

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos. 

Seguindo esse princípio, eu adicionaria uma linha em branco nas seguintes linhas: 

- 11
- 16
- 20
- 26
- 32

Também removeria a última linha em branco do bloco da `closePopup` e do início do bloco do callback do `forEach`. É uma convenção iniciar e terminar um bloco com linhas de código. Caso contrário, o olho precisa pular linhas em branco desnecessárias e a leitura do código perde fluidez.

### Fechamento de tags

O `<h1>` da linha 32 está sem fechamento.

---

Novamente, parabéns Felipe =)

As observações acima fizeram sentido?

@Felipe-HVSilva

**Comment by Felipe-HVSilva** [comment]
Opa Roger, muito obrigado pelo feedback, vou prestar mais atenção nessas coisas, e sim, fazem muito sentido

**Comment by Roger-Melo** [comment]
Legal @Felipe-HVSilva. Já que fez sentido, vou fechar a issue por agora. Quando surgir uma nova dúvida, é só abrir uma issue =)
