### ISSUE TITLE
Resumo da Aula Numbers da etapa 01

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4262]
Numbers.
Podem ser números inteiros ou decimais

podemos fazer qualquer tipo de operação matemática
 
ordem de operação
1 parênteses
2 expoentes ou raízes
3 multiplicação ou divisão
4 adição ou subtração

operadores de incremento
variável++ soma 1 do valor dela mesmo
variável-- subtrai 1 do valor dela mesma
variável += soma números maiores que 1 ao valor dela
variável -= subtrai números maiores que 1 ao valor dela
variável *= multiplica o valor dela a qualquer numero
variável /= divide o valor dela a qualquer numero

NaN
Not a Number
resposta quando uma operação não resulta em um numero

Concatenação de string com numero
const likeMenssage = 'O post em ' + postLikes+ ' likes'
quando números são concatenados com strings eles são automaticamente convertidos em strings

**Comment by Roger-Melo** [comment]
Show @josejuniorvr. Vamo que vamo, rumo à fluência! 🙌
