### ISSUE TITLE
Resumo da Aula: While loop e exercícios, Aula 01-04 etapa 02

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4267]
Ele faz o mesmo que o for, mas sua sintaxe é diferente, ele precisa de uma atribuição fora dele através de uma variável, e atenção a essa atribuição, pois se vc atribuir um valor por exemplo zero ou 1, sem que vc tenha colocado a condição de parada que é o incremento, seu 
código vai entrar em loop infinito: 
let i = 0;
while (i < 5) {
    console.log(`Dentro do loop ${"valor de i"}`)
} 
e a quantidade de outputs que vai gerar no browser, vai fazer seu pc travar. 
O valor do incremento vem dentro do bloco: i++ 
let i = 0;
while (i < names.length) {
   console.log(names[i])
   i++
}

**Comment by Roger-Melo** [comment]
Show @Morais465. Vamo que vamo, rumo à fluência! 🙌

**Comment by Morais465** [comment]
Obrigado professor Roger, é isso que busco. Vamos sim🙏🏿
