### ISSUE TITLE
Resumo da Aula 03-02 da etapa 01 Arrays

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4271]
### Arrays 
Os arrays são uteis para armazenarmos tipos de dados que tem uma relação entre si em uma única variável
```js
const name = ['Diego', 'João', 'Maria']
```
Nós podemos acessar os elementos do array através do indice:
```js
console.log(name[0]) // Diego
```
como o js é zero base, começando a contagem a partir de 0 ele retornara o primeiro elemento do array

É possível reatribruirmos um elemento do array da seguinte maneira:
```js
name[2] ='Ana'
```
### Métodos
Os arrays tambem possuem métodos
```js
console.log(name.length) // 3
```
Da mesma forma que  o método length retorna a quantidade de caracteres em uma string ele também retorna a quantidade de itens em um array
```js
console.log(name.join()) // Diego, João, Maria
```
o método join concatena elementos do array com virgula e espaços
```js
console.log(name.join('-')) // Diego-João-Maria
```
o método join também pode receber um argumento, o argumento inserido entre os parênteses são um separador.
```js
const moreNames = name.concat(['Ana', 'Pedro']) 
```
o método concat ira concatenar um array com outro:
```js
console.log(moreNames) // ['Diego', 'João', 'Maria', 'Ana', 'Pedro']
```
```js
const pushNames = name.push('Marcos') // 4
```
O método push serve para empurrarmos um elemento para o final do array e tambem retorna a quantidade de elementos que o array possui.
```js
console.log(name) // ['Diego', 'João', 'Maria', 'Marcos']
```
```js
console.log(name.pop()) // ['Diego', 'João', 'Maria']
```
O método pop remove o ultimo elemento do array

**Comment by Roger-Melo** [comment]
Boa @Diegodkid, rumo à fluência! 🔥
