### ISSUE TITLE
Etapa 5, Eventos do clique: 03-03

### ISSUE THREAD

**Issue by Felipe-HVSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#428]
Fique numa dúvida, quando eu coloco pra ver o ''event'' no console não aparece MouseEvent e sim o PointEvent, muda muita coisa?
 Estava vendo não aparece o tagName no PointEvent e tals

@Roger-Melo

**Comment by YureK-a** [comment]
Para facilitar para o Roger, coloca os códigos que você tá falando. Muitas vezes a gente não presta atenção e fica em dúvida haha.

**Comment by Roger-Melo** [comment]
Oi @Felipe-HVSilva.

Para verificar o que está acontecendo com precisão, preciso baixar o código (.html, .css e .js) para testar em minha máquina. Você pode subir o código em um repositório e me enviar o link ou postar o código aqui na issue, o que for mais fácil para você.

Se postar o código na issue, pode postar o HTML e CSS também, sem problemas.

Fico no aguardo =)

**Comment by Felipe-HVSilva** [comment]
Eu acabei procurando nas perguntas e achei justamente o que estava procurando e esqueci de fechar, mesmo assim agradeço

**Comment by Roger-Melo** [comment]
Tamo junto @Felipe-HVSilva  👊🏻
