### ISSUE TITLE
Etapa 7, Quiz Interativo - Exercício Quiz

### ISSUE THREAD

**Issue by mateusgh** [roger-melo-treinamentos/curso-de-js-roger-melo#43]
Boa noite Prof.

Segue o link do meu Quiz até então.
https://github.com/mateusgh/Quiz-CJRM

Identificar erros (esqueci o parenteses do event.defautPrevent()) , dificuldade em saber se o código está "clean" ou não e qual a forma mais correta de acessar o DOM (sei que é possível de várias maneira e estou acostumado com objeto.propriedades.

Tenho facilidade com a lógica.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Mateus. Parabéns pelo esforço! =D

No início, não se preocupe tanto em deixar o código clean. Isso vem com a prática e com o tempo. E você também verá que ainda vamos falar muito desse assunto no treinamento =)

Sempre que rolar alguma dúvida, é só abrir uma issue aqui que te ajudo.

Parabéns pela aplicação!

Por agora, vou fechar a issue, mas no que precisar, é só abrir uma nova. Conte comigo para chegar à fluência em JavaScript.

@mateusgh
