### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4302]
O tipo de dado Number abrange numeros inteiros(10) e decimais(3.14).

Alguns operadores aritmeticos:
- operador de adicao  +
- operador de subtracao  -
- operador de mutiplicacao *
- operador de divisao  /
- operador modulo  %  (Lembrando que modulo nao e porcentagem, modulo retorna o resto do calculo.)

O JavaScript segue uma ordem de operacao que tem por prioridade:
1 parenteses
2 expoentes ou raizes
3 multiplicacao e divisao
4 adicao e subtracao

exemplo: const crazyOperation = 5 * (10 - 3) ** 2
nesta equacao a ordem de resolucao sera: 
10 - 3 (7)        //parenteses
7 ** 2 (49)      //expoentes ou raizes
5 * 49 (245)    //multiplicacao e divisao

Operadores de incremento:
++ e -- //servem apenas para somar ou subtrair o numero 1.
para numeros maiores que 1 e utilizado o ASSIGNMENT.
Exemplo:
postLike += 42
postLike -= 42
postLike *= 42
postLike /= 42

NaN (Not A Number) e o erro ou resultado de uma equacao que nao resulta em um numero.

Em concatenacoes entre strings e numeros o resultado sempre sera convertido em STRING.

**Comment by Roger-Melo** [comment]
Excelente @YukOnRails, rumo à fluência! 🎯
