### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4311]
É possível converter um tipo de dado para outro, por exemplo: converter um número que é string ‘1’ para o tipo número 1. Exemplos:

```js
const convertedNumber = String(97) → Resultado ‘97’
const convertedNumber = Number(‘97’) → Resultado 97
```
Também é possível converter valores em tipo boolean.
```js
const booleanConvertion = Boolean(10) → Resultado true
```
Porém há alguns valores que sempre retornaram como False, são eles:
```js
false
0
“ “
‘ ‘
null
undefined
NaN
```
Qualquer outro valor diferente dos mencionados acima, o retorno é true.

Quando a conversão não for válida, o resultado no console sera NaN. Exemplo:
```js
const num = Number(‘maracuja’) → Retorno NaN
```

**Comment by Roger-Melo** [comment]
Excelente @AlessandroAscanio, rumo à fluência! 🎯
