### ISSUE TITLE
Resumo da Aula 04-02 da etapa 01 Booleans e comparacoes

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4312]
Os booleans são um tipo de dado lógico que pode retornar apenas um de dois valores possíveis: true(verdadeiro) ou false(false)

existe um método onde nós podemos verificar se um conjunto de caracteres fazem parte de uma string
```js
const email = 'diego@gmail.com'
const includes = email.includes('@') // true
```
o método includes ira verificar se o argumento especificado existe na string e retornara true ou false
```js
const name = ['Ana', 'Lucas', 'Luan']
const nameIncludes = name.includes('Luan') // true
```
Da mesma forma que o método includes serve para identificar se um caractere está presente em uma string ele também serve para verificar se um elemento está em um array

### Operações de comparações
```js
const age = 25
console.log(age == 25) // true
```
verifica se a variável age é igual a 25
```js
const age = 25
console.log(age != 25) // false
```
a forma de lermos essa declaração age é diferente de 25
```js
const age = 25
console.log(age > 25) // false
```
verifica se a variável age é maior que 25
```js
const age = 25
console.log(age >= 25) // true
```
verifica se a variável age é maior ou igual 25

**Comment by Roger-Melo** [comment]
Excelente @Diegodkid, rumo à fluência! 🎯
