### ISSUE TITLE
Etapa 06, Correção dos exercícios da aula 04 da etapa 05 - Aula 01-01

### ISSUE THREAD

**Issue by diegobaena89** [roger-melo-treinamentos/curso-de-js-roger-melo#432]
Boa tarde, professor!
Estava resolvendo o exercício 3, que pede para adicionarmos as mensagens - que antes estavam no console.log - dentro de uma h2 criada no index.html.
Cheguei à seguinte resolução:

```js

const h2 = document.querySelector('h2')
const div = document.querySelector('div')
const elementsInsideDiv = Array.from(div.children)

elementsInsideDiv.forEach(element => {
  element.addEventListener('click', event => {
    event.stopPropagation();
    h2.innterHTML += `Clicou no ${event.target.tagName.toLowerCase() } filho da div.`
  })
})

div.addEventListener('click', () => {
  h2.innetHTML += 'Clicou na div.'
})

```

Contudo, em sua resolução, o senhor usa o textContent ao invés do innetHTML - tirando o fato que eu também concatenei o valor que existia antes, fazendo com que, a cada clique, as mensagems fossem se somando dentro do h2.
Ambos os exercícios chegaram à mesma conclusão. Mas existe algum problema, neste caso, em usar o innerHTML ao invés do textContent?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Diego.

Antes de responder, deixa eu dar uma dica. 

Sempre que abrir uma issue de dúvidas, o título precisa conter a etapa e o título exatos da aula em que você viu o assunto sobre o qual tem dúvidas. Caso contrário, fica mais complicado eu encontrar a aula e te ajudar mais rápido.

Para dar uma resposta mais precisa, eu levo em consideração o ponto em que você está no treinamento. Esse é um outro ponto pelo qual é importante que o título tenha essas informações corretas.

Esse exercício não existe na aula do título que foi colocado na issue. Já consertei o título com a aula e etapa correta.

---

A `textContent` deve ser usada quando você precisa obter ou setar uma string. Por isso o nome `text`.

Já a `innerHTML` é ideal quando você precisa obter ou setar uma marcação `HTML`.

---

Sobre a concatenação, não vejo muito sentido nesse caso. Mas se você usou consciente de que a concatenação iria acontecer, saberia resolver sem a concatenação também. Então tá tudo certo.

Ficou mais claro?

@diegobaena89

**Comment by diegobaena89** [comment]
Olá, professor.
Eu acabei me confundindo na hora de me explicar rs....na verdade queria saber a diferença de se usar o innerText ao invés do textContent, não o innerHTML.

Me desculpe e mto obrigado.

**Comment by Roger-Melo** [comment]
Olá @diegobaena89.

Eu mostrei as diferenças entre `innerText` e `textContent` na aula 02-05 da etapa 05. Mas é basicamente o seguinte...

A `innerText` obtém **o texto visível** que o elemento contém.

Já a `textContent` obtém todo o texto que o elemento contém, independente se o texto está visível ou não.

Ou seja, no parágrafo abaixo,

```html
<p>Olá <span style="display: none">texto invisível</span> oi.</p>
```

a `innerText` retorna `Olá oi.` e a `textContent` retorna `Olá texto invisível oi.`:

```javascript
const p = document.querySelector('p')

p.innerText       // Olá oi.
p.textContent  // Olá texto invisível oi.
```

Ficou mais claro?

@diegobaena89

**Comment by diegobaena89** [comment]
Ficou sim professor. Acho que essa informação acabou passando e não me atentei. 

Mto obrigado

**Comment by Roger-Melo** [comment]
Tranquilo @diegobaena89. No que precisar, é só abrir uma nova issue =)
