### ISSUE TITLE
Resumo da Aula 01-03 da etapa Etapa 02

### ISSUE THREAD

**Issue by Zevid-Lucas** [roger-melo-treinamentos/curso-de-js-roger-melo#4322]
- A expressão inicial é iniciada, normalmente com a declaração de uma variável que servirá como um contador
- A ***Condição é avaliada***. Caso a condição seja true, o bloco de código que contém a ***declaração é executado***
- Ao final da declaração é feito o incremento. Após o incremento é verificado a condição, se true, a declaração é executada.
- O ciclo é repetido até que a condição seja false. Quando a condição for false, a declaração não executa e esse bloco de código é encerrado.
```js 
for ([ExpressaoInicial]; [Condicao]; [Incremento]) {
	declaracao
}
```

- Iteração é o processo de percorrer os valores dentro de um array.
```js
const names = ['Linus', 'Ada', 'Bill']
for (let i = 0; i < names.length; i++) {
	const HTMLTemplate = `<p>${names[i]}</p>`
	console.log(HTMLTemplate) // <p>Linus</p>
				 // <p>Ada</p>
				// <p>Bill</p>
}
```

**Comment by Roger-Melo** [comment]
Excelente @Zevid-Lucas, rumo à fluência! 🎯
