### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4329]
A conversão como o nome sugere transforma um tipo de dado em outro tipo de dado, como transformar uma string "31" em um number 31.
Foram ouvidas palavras que arremetem a coisas ainda não vistas, como Função Construtora e outras, esses e outros fatores serão estudados ao longo do curso, tudo o que é preciso saber sobre essa aula é o efeito das conversões em si.

Number ( ) por exemplo é uma função construtora que converte dados em números.

typeof verifica o tipo de dado, retornando string, number, boolean, mas existem situações em que ele não vai ser a melhor escolha para se verificar um valor, mais detalhes sobre isso serão esclarecidos ao longo do curso.

String ( ) similar a number converte numero (e dados) em strings.

---

É possivel também converter valores em booleans, porém dados convertidos em booleans são comparados com "Falsy" e "Truthy", para os valores booleans qualquer valor que não é falsy será considerado true.

falsy
- false
- 0
- " ", ' ' , ``
- null
- undefined
-  NaN

truthy
- qualquer valor que não for falsy

EX: console.log (Boolean ( 0 ) ) = seria considerado falso, pois 0 é um valor falsy

já 

     console.log (Boolean ( "0" ) ) = Seria verdadeiro pois aqui 0 é uma string, e qualquer valor não falsy é truthy

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
