### ISSUE TITLE
Resumo da Aula: Arrow functions, Aula 02-02 etapa 03

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4332]
ao uma das adições do JS moderno, deixando nosso código mais conciso e limpo. Quando existe apenas um parâmetro na função, podemos
retirar os parênteses. Mas dessa forma não é possível colocar um valor como default pra essa função:
= number = 0 => {
Pois dará erro, nesse caso precisa, estar entre (): = (number = 0) => { !!!
E no caso dessa função ter só uma linha de código, podemos
retirar o return, as chaves que ela retornará implicitamente
o resultado: = number => number * 2; !
Isto é, se fosse um boolean, array, string ou qualquer outra expressão(é qualquer pedaço de código que resulta num valor) já o if e switch não são expressões e sim blocos de código.

**Comment by Roger-Melo** [comment]
Excelente @Morais465, rumo à fluência! 🎯
