### ISSUE TITLE
Resumo da Aula Conversão de tipos da etapa 01

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4340]
Conversão de tipos
Etapa 01
Aula 04 - 04

É possível converter tipos de dados, haverá momentos em que vamos precisar fazer isso
para obtermos determinado resultado
```JS
let score = '100'
console.log (score + 1)
1001
```
O resultado é 1001 por que faria a concatenação entre uma string e um number , resultando em uma string
Para somarmos corretamente teriamos que converter a string em um number.
para converter uma string em um number invocamos uma Função Construtora Number()
Passando a string como argumento dessa invocação e essa sttring é convertida em número
```JS
let score = '100'
score = number(score)
console.log (score + 1)
101
```

Podemos verificar o tipo de uma dado, usando o operador typeof

```JS
console.log (typeof score)
Number
```

```JS
const crazyConversion = 'maçã'
console.log (crazyConversion = Number('maçã')
NaN
```

Converter Number para String
```JS
const convertedNumber = String(97)
console.log (convertedNumber , typeof convertedNumber)
97 string
```

Converter valores em Boolean
```JS
const booleanConversion = Boolean(10)
console.log (booleanConversion, typeof booleanConversion)
true "boolean"
```
Valores que retornam False numa conversão para boolean
[false, 0, " ", ' ', ` `, null, undefined, NaN]

Valores que retornam True
[Qualquer outro valor que nao é False]

Isso são conversões explicitas. Conversões implicitas são as que o proprio JS faz por baixo dos panos antes de comparar

**Comment by Roger-Melo** [comment]
Excelente @josejuniorvr, rumo à fluência! 🎯
