### ISSUE TITLE
A condicional switch  - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4347]
![js](https://user-images.githubusercontent.com/55354801/180683043-e3081e38-91ed-4f3b-ac07-1019e10c27c5.jpg)

# A condicional switch - Aula 03-04 da etapa 02

**Condicional switch**

O **switch case** é uma estrutura condicional do **Javascript**
 como o if, e serve para analisar os valores e executar um bloco de código condicionalmente. Normalmente é utilizado, quando se deseja analisar diversos valores diferentes para a mesma variável.

O **switch** vai tratar os casos de uma única entrada. Veja que cada case se refere diretamente ao num. O **if** não te restringe a quantas entradas serão avaliadas. Você pode comparar diretamente duas **ou** mais condições dentro de um único **if.**

```jsx
const grade = 'B' 

// if statements
if (grade === 'A') {

} else if (grade === 'B') {
	console.log('Voce tirou um B')
} else if (grade === 'C') {
	console.log('Voce tirou um C')
} else if (grade === 'D') {
	console.log('Voce tirou um D')
} else {
	console.log('Nota invalida')
}

// switch
switch (grade) {
	case 'A':
		console.log('Voce tirou um A')
		break
	case 'B':
		console.log('Voce tirou um B')
		break
	case 'C':
		console.log('Voce tirou um C')
		break
	case 'D'
		console.log('Voce tirou um D')
		break
	default:
		console.log('Nota invalida')
}
```

**Comment by Roger-Melo** [comment]
Excelente @RodrigoRedivo, rumo à fluência! 🎯
