### ISSUE TITLE
O que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4362]
![js](https://user-images.githubusercontent.com/55354801/180898267-613795a2-5584-4ddb-b4e2-e93abb459dca.jpg)

# O que são funções - Aula 01-02 da etapa 03

**Functions**

- Funções são **blocos de construção fundamentais em JavaScript.**
- Uma função é um procedimento de JavaScript - um conjunto de instruções que executa uma tarefa ou calcula um valor.
- Para usar uma função, você deve defini-la em algum lugar no escopo do qual você quiser chamá-la

**Comment by Roger-Melo** [comment]
Excelente @RodrigoRedivo  rumo à fluência! 🎯
