### ISSUE TITLE
Resumo da Aula: O  método forEach e callbacks - Aula 02-04 etapa 03

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4364]
Se quisermos inserir uma função de ARGUMENTO, então chamamos essa função de callback ou só callback. Estamos invocando callback como argumento, pois ele vai receber o valor da declaração de uma função.
Ao invés de inserir um número, um array para a função, vamos inserir uma outra func: myFunc(() => {}) essa func está sendo atribuída para esse parâmetro: callback => , e abaixo estou invocando essa func mas com o value como argumento: callback (value), então a declaração dessa func dentro de myFunc precisa ter um parâmetro, que vai ser number e como só existe um parâmetro vamos simplificar: myFunc(number => {
Então qual foi o fluxo? Declaramos a myFunc, abaixo invocamos ela e colocamos como parâmetro recebendo a func number como argumento, ou seja, func number foi atribuída para o parâmetro callback, e já que ele armazena essa func number, podemos invocá-la no callback da primeira: callback (value) e como ela recebe um number como parâmetro, a gente ta pegando o value que declaramos acima e passando como argumento da invocação da função, o valor foi pego no parâmetro number e exibido no console.log !
Foreach(significa: Para Cada) é um método que vai iterar sobre um array, isto é, para cada item desse array vou fazer algo!
Nesse caso o foreach vai iterar por cada item desse array e vai executar essa func, aparecendo olá 4 vezes. Essa func de callback pode receber 3 parâmetros, o primeiro é o item atual sendo iterado, como é individual, podemos colocar no singular, isso vai fazer executar cada item no console. Como 2 parâmetro o index e o 3 o próprio array, colocando index, o item e o array, recebemos uma lista bem completa. E ela pode ser desacoplada.

**Comment by Roger-Melo** [comment]
Excelente @Morais465, rumo à fluência! 🎯
