### ISSUE TITLE
Resumo da Aula sobre Arrays - Aula 03-02 etapa 01

### ISSUE THREAD

**Issue by felipegueller** [roger-melo-treinamentos/curso-de-js-roger-melo#4375]
# Aprendendo sobre arrays

## Atribuição 

```JS
const array = [1, 2, 3]
array[3] = 4
```

## propriedade `length`

A propriedade length retorna a quantidade de itens dentro do array.

```JS
console.log(array.length) // 4
```

## Push( )

O método push adiciona um ou mais elementos ao um array, e retorna a quantidades de items após a inserção.

```JS
array.push(5) // -> 4
```

## Pop( )

O método push remove o último elemento do array e retorna o elemento removido.

```JS
array.push(5) // -> retorna o elemento 5, o último item do array
```

## Join( )

O método join cria uma string a partir da concatenação dos elementos do array. Por padrão, os elementos são separados por virgula `,`, mas pode-se passar um delimitador opcional por parâmetro.

```JS
array.join(' | ') // -> 1 | 2 | 3 | 4
```

## Concat()

O método concat junta um ou mais arrays.
```JS
const otherArray = [5, 6]
array.concat(otherArray)

console.log(array) -> [1, 2, 3, 4, 5, 6]
```

## indexOf()

Retorna o índice da primeira ocorrência do elemento passado por parâmetro se o mesmo existir no array, caso não exista, retorna -1.
```JS
array.indexOf(3) // -> 2
```

## indexOf()

Retorna o índice da última ocorrência do elemento passado por parâmetro se o mesmo existir no array, caso não exista, retorna -1.
```JS
array.push(3)
array.lastIndexOf(3) // -> 6
```

**Comment by Roger-Melo** [comment]
Excelente @felipegueller, rumo à fluência! 🎯
