### ISSUE TITLE
Resumo da Aula Booleans e comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4376]
Booleans sao os valores true e false que sao utilizados para verificacao de codigos, retornando um deles, verdadeiro ou falso.
// lembrando que o metodos .includes( ) como o nome sujere serve para verificar se o argumento se inclui naquele container; e serve para strings e booleans.

Alguns operadores de condicionais que geralmente sao utilizados com booleans:
- // == (igual)
- // !=   (diferente de)
- // >    (maior que)
- // <    (menor que)
- // <=  (menor ou igual)
- // >=   (maior ou igual)
- // === (igual absoluto)

**Comment by Roger-Melo** [comment]
Excelente @YukOnRails, rumo à fluência! 🎯
