### ISSUE TITLE
Resumo da Aula O que é controle de fluxo - Aula 01-02 da etapa 02

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4377]
Em certos momentos na construção do código iremos precisar decidir qual será a próxima ação a ser tomada, e haverá também certos momentos em que será preciso executar um pedaço de códigos muitas vezes,  e para isso precisamos controlar o fluxo do código.

Ex: Imagine que há um array com três nomes, agora nos queremos percorrer esse array e executar o código uma vez para cada nome dentro do array. Nesse caso usaríamos o Loop, que é um tipo de controle de fluxo do JavaScript.
Da mesma forma iremos querer verificar se uma condição é verdadeira, por exemplo se a um usuário logado ou se o valor de uma variável é o esperado, e só quando essa condição for verdadeira iremos executar o código, isso é chamado de estrutura condicional.
Loop e condicional fazem parte do conceito de controle de fluxo no JS. Nessa etapa iremos falar desse conceitos e estudar tipos diferentes de loops e estruturas condicionais.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
