### ISSUE TITLE
Resumo das Aulas 1, 2, 3 da etapa 04

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#4385]
# Resumo em formato OneNote.

[Aulas 1, 2, 3 - Etapa 04.zip](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/9202830/Aulas.1.2.3.-.Etapa.04.zip)

**Comment by Roger-Melo** [comment]
Excelente @George-Luis-Costa, rumo à fluência! 🎯
