### ISSUE TITLE
Resumo da Aula O método reduce - 01 - 04 - da etapa 08

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#4390]
Esse é sem dúvidas o mais versátil dos métodos apresentados até agora. O método reduce() tem a capacidade
de retornar como saída um valor que seja distinto de um array, podendo ser um único número ou string, por exemplo.
Também pode receber até quatro parâmetros, mais uma particularidade sua. Desses, obrigatórios são o acumulador 
e o item a ser iterado (os outros, a saber, são: index e array)
É um método que também sempre deve retornar um valor.

**Comment by Roger-Melo** [comment]
Excelente @VitorPeixotoDev, rumo à fluência! 🎯
