### ISSUE TITLE
Resumo da Aula While loop e exercicios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4391]
O For e o While fazem exatamente a mesma coisa, a unica diferença é a sintaxe a forma como eles são escritos.

O while loop possui apenas a expressão de condição em seu (  ). Portanto ao contrario do For a i não é declarada entre (  ), ela precisa ser declarada em uma let i acima do while.

Sobre LOOPS INFINITOS
O que é?
Ex:

Let i = 0

While ( i < 5 ) {
          console.log( `Dentro do loop: ${  (  i  )  } `
          
{

O valor de incremento no while que normalmente fica abaixo do console.log não foi colocado, 

Atribuímos um valor para i na let i que é 0, mais abaixo a expressão de condição diz que enquanto i for < que 5 o código dentro do bloco continuara rodando. E como o valor de i não esta sendo incrementado a cada conferida, o valor de i continua a ser 0 e o programa volta mais uma vez para conferir o valor de i que novamente será 0, e novamente, e novamente. Um loop infinito, portanto para que isso não aconteça precisamos incrementar a i. Da seguinte maneira:

Let i = 0

While ( i < 5 ) {
          console.log( `Dentro do loop: ${  (  i  )  } `
          i++
{

Com o valor do incremento, no momento em que a i armazenar 5 o loop será encerrado. Lembrando que o while não é tão usado como o for, mas ainda é possível se deparar com ele de vez em quando.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
