### ISSUE TITLE
Duvida referente ao valor do valor que a propriedade do objeto armazena. 

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#4394]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 03 da etapa 11 - Aula 04-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1296231

### Descreva a dúvida

Boa noite professor tudo certo ? 
Minha duvida é  no exercício  07. 

```js
const people = [
  { id: 5 , name: 'Angelica', age: 18, federativeUnit: 'Pernambuco' },
  { id: 81, name: 'Aline', age: 19, federativeUnit: 'São Paulo' },
  { id: 47, name: 'Gabriel', age: 18, federativeUnit: 'Alagoas' },
  { id: 87, name: 'Aline', age: 18, federativeUnit: 'Minas Gerais' },
  { id: 9 , name: 'Gabriel', age: 20, federativeUnit: 'São Paulo' },
  { id: 73, name: 'Aline', age: 19, federativeUnit: 'Brasília' }
]
const getFrequencyOfAge = (accumulator , {age}) => { 
  accumulator[age] =  accumulator[age] + 1 || 1
   return accumulator
}

const newObj = people.reduce(getFrequencyOfAge , {})
console.log(newObj)
```

Minha duvida é  a seguinte :  porque a expressão "  accumulator[age]  "  do lado direito, ou seja, depois da atribuição é undefined . A primeira expressão antes da atribuição " accumulator[age] "  armazenou 18. Porque a mesma expressão depois da atribuição ( lado direito não armazenou 18 também, e em vez disso undefined). Eu fiz os testes no console do browser, e entendi que undefined + qualquer numero resulta em NaN. Eu só não entendi porque a mesma expressão armazena diferente resultado. 
Desde já grato.

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Sansanoski!

>## Minha duvida é a seguinte: porque a expressão "accumulator[age]" do lado direito, ou seja, depois da atribuição é undefined

Vamos lá! Nestes trechos de código abaixo, na primeira execução do callback, observe que o parâmetro `accumulator` está armazenando o valor que foi inserido como segundo argumento do reduce:

```js
const getFrequencyOfAge = (accumulator , {age}) => { 
  accumulator[age] =  accumulator[age] + 1 || 1
  return accumulator
}
```

```js
const newObj = people.reduce(getFrequencyOfAge , {})
```

Percebe-se que é um objeto vazio, certo?

Note também, que o `accumulator`, na primeira linha de código da função, está buscando uma propriedade `age`: 

```js
accumulator[age]
```

Ao executar o trecho de código abaixo, antes de fazer a atribuição na lógica, você verá como resultado `undefined`.

```js
const getFrequencyOfAge = (accumulator , {age}) => { 
  console.log(accumulator[age]) // Resulta em undefined
  return accumulator
}

const newObj = people.reduce(getFrequencyOfAge , {})

```

Sabendo que o `accumulator` vai armazenar um objeto vazio durante sua primeira execução, sugiro que você acompanhe comigo codando no editor de código o exemplo similar abaixo:

```js
const objeto1 = {}
```

Uma const `objeto1` que recebe um objeto vazio foi criada.

Agora, quando se busca uma propriedade 18, por exemplo, em um objeto vazio, veja o que acontece.

```js
console.log(objeto1[18]) // undefined
```

Conseguiu visualizar? Quando se busca num objeto uma propriedade que não existe, ela retorna `undefined`!

Voltando ao seu código.

```js
const getFrequencyOfAge = (accumulator , {age}) => { 
  accumulator[age] =  accumulator[age] + 1 || 1
   return accumulator
}
```

```js
const newObj = people.reduce(getFrequencyOfAge , {})
console.log(newObj)
```

Na primeira execução, o `[age]` está armazenando 18. Entretanto, essa propriedade não existe no `accumulator` pois na primeira execução `accumulator` ainda está armazenando um objeto vazio. E foi por isso que `undefined` é retornado!

Ficou mais claro? =)

---

>## A primeira expressão antes da atribuição "accumulator[age]" armazenou 18. Porque a mesma expressão depois da atribuição ( lado direito não armazenou 18 também, e em vez disso undefined).

Não vou dar a resposta pronta, mas vou te mostrar o caminho para que você chegue nela. Por que estou fazendo isso? Se você entender a razão pela qual está com essa duvida, você não terá dificuldade em entender conceitos relacionados numa eventual ocasião depois.

Sabendo disso, procure no Google: "mdn operator precedence" e depois procure pelo "(assignment operator)" na tabela. Lá você vai encontrar mais informações sobre o que está acontecendo nessa parte do código em questão.

Depois, comente aqui na issue o que você achou, se precisa de mais ajuda ou o que conseguiu concluir com essas informações acima.

---

Faz sentido?

**Comment by Sansanoski** [comment]
Ficou claro sim . O que estava faltando entender era que o assignment  operator   ele é right-to-left  , então ele vai resolver  primeiro  accumulator[age] + 1 || 1  , que esse curto circuito resulta em 1 , e depois ele cria a propriedade  accumulator[age] que da  18.  No final da primeira execução o objeto não retorna  mais vazio e sim { 18 : 1} .

**Comment by MivlaM** [comment]
Show! No que precisar, é só abrir uma nova issue =)
