### ISSUE TITLE
Resumo da Aula 01-04 da etapa 02 | While loop e exercicios 

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4398]
O while loop é bem similar ao for loop, ambos são laços, porém o que muda no while é a escrita da função condicional, diferente do for loop(que todas as funções são no mesmo local), o while é de maneira diferente, porém ambos tem a mesma funcionalidade, fazendo assim eles varrem um array e iteram entre os itens. Caso o incremento não seja colocando dentro da aba de aplicação isso pode gerar um laço infinito fazendo assim gerar códigos até travar a pagina do console. o incremento desta vez fica após a função que sera aplicada caso a sentença de true.  

Ex: 

let i = 0
while ( i < 10) { 
      console.log(" .... ")
      i++
}

**Comment by Roger-Melo** [comment]
Excelente @EdsonAjjunior, rumo à fluência! 🎯
