### ISSUE TITLE
Resumo da Aula Aula mais importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by EnricoTomaz** [roger-melo-treinamentos/curso-de-js-roger-melo#4399]
Fala de tipos de estudantes (coelhos e tartarugas);
O curso tem 15 etapas para chegar a fluência
    --> Nas 7 primeiras etapas veremos os fundamentos do Javascript;
    -->A partir da 8ª etapa haverá conceitos mais complexos
    -->Nas etapas finais será possível construir aplicações web com javascript puro

   Fala dos 8 marcos para percorrer até a fluencia
    -->São divididos em 4 etapas: alicerce, validação, evolução, comemoração.
Explica como abrir uma issue para perguntas e resumo;
Explica como revisar aulas
Fala da revisão raio-x

**Comment by Roger-Melo** [comment]
Excelente @EnricoTomaz, rumo à fluência! 🎯
