### ISSUE TITLE
Etapa 02 - Controle de fluxo - exercicio-07

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#44]
Roger, sobre a etapa 2 controle de fluxo.

Tenho uma dificuldade com loops, quando vou fazer revejo as aulas anteriores,
e leio na documentão do mdn, e as vezes procuro no google, "trocar text array loop posição js"

Faço essas buscas para vê como é feito não sei se é bom para quem esta aprendendo essa do google,
por q muitas das vezes já tem a lógica pronta.

Como você falou, não pode ficar preço em uma peça do quebra cabeça por muito, sendo que tem outras peças.

Por exemplo esse exercício abaixo, quando vejo já bate aquele frio e desespero e tristeza, coisa de iniciante né, ter medo
de algo novo em que você vai ser desafiado. 
Sempre que olho um problema assim, vejo o que eu sei fazer fazer e vou fazendo por etapa.

Por exemplo:
- fazer um loop
- exibi o loop

Aí depois não se fazer, vou testando, e leio o mdn, procuro no google e tem coisa que resolver mais 
não tem na aulas anteriores. 
Não gosto de ir já para a solução sem tentar, e quebrar a cabeça, para tentar resolver. 
E nesse hora penso vale a pena perguntar aqui, mesmo eu vendo o solução e entendendo?

/*
  05

  - Itere sobre o array "randomValues" apenas até a 4ª string dele;
  - Exiba a string abaixo no console, mantendo a formatação de lista e inserindo  
    as informações corretas:

  "
    3 informações sobre o array randomValues:
      - As primeiras 4 strings são XX, XX, XX e XX;
      - Até que as primeiras 4 strings fossem iteradas, XX booleans foram iterados;
      - O array foi iterado por XX vezes.
  "
*/ 

 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo! 

> Como você falou, não pode ficar preço em uma peça do quebra cabeça por muito, sendo que tem outras peças.

Exato. Você pode tentar resolver, mas não deixe que o "travamento" para fazer um exercício estrague seu dia.

> Por exemplo esse exercício abaixo, quando vejo já bate aquele frio e desespero e tristeza, coisa de iniciante né, ter medo

Compreendo. É desconfortável no começo. Mas nenhum bloqueio resiste a um bom método.

Verifique se o ATER está sendo seguido.

No começo, o "T" não precisa ser seguido à risca. Os parágrafos da documentação no MDN contém vários links que levam assuntos mais avançados que podem confundir, no começo. À medida em que você avança no treinamento, notará que eu vou começar a deixar links para a documentação abaixo dos vídeos.

Mas, definitivamente, no "A", de aula, fazer resumos das aulas é essencial.

A escrita exige que o cérebro foque na aula e, posteriormente, suas anotações serão materiais de consulta nos exercícios e revisão.

> Tenho uma dificuldade com loops, quando vou fazer revejo as aulas anteriores,
e leio na documentão do mdn, e as vezes procuro no google, "trocar text array loop posição js"

No momento da dúvida em meio ao exercício, o ideal é consultar o conteúdo do treinamento. Seja através das aulas ou das suas anotações.

Se não for o suficiente, pode perguntar aqui.

No quê você tem dúvida? A dúvida está em entender como um loop funciona?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
>No quê você tem dúvida? A dúvida está em entender como um loop funciona?
Isso saber como funciona e quando usar nos casos.

Pelo que eu vi o loop faz um ciclo, e nesse ciclo ele altera algum elemento, ou faz uma consulta.
E hoje dia o loop é usado de mais. 
Mais eu aprendi no curso a ter uma boa base com o loop funciona, por causa da boa base dos índices do array. 

Vou procurar fazer mais o ATER, e fazer o A

**Comment by Roger-Melo** [comment]
> Isso saber como funciona e quando usar nos casos.

O "como" funciona está detalhado nas aulas, mas caso reveja e não consiga entender alguma parte específica do que expliquei, pode perguntar.

Talvez ainda mais importante que o "como", que pode ser aprendido vendo as aulas, é o "quando".

### Você irá usar loops quando precisar executar um pedaço de código várias vezes

Esse é o princípio fundamental para o caso de uso de um loop.

Imagine que, por alguma razão, eu precise exibir 'x' no console, por 5x.

Eu tenho a opção de fazer isso de forma manual, executando o `console.log` 5x,

```javascript
console.log('x')
console.log('x')
console.log('x')
console.log('x')
console.log('x')
```

ou eu posso escrever o `console.log` apenas 1x e inseri-lo dentro de um loop que executa o que está dentro do bloco de código 5x:

```javascript
for (let i = 1; i <= 5; i++) {
  console.log('x')
}
```

Sobre o "como funciona", eu preciso saber o que você tem dificuldade em entender. Se são as expressões dentro dos parênteses...

```javascript
(let i = 1; i <= 5; i++)
```

se é a palavra-chave em si...

```javascript
for
```

se são os blocos...

```javascript
{

}
```

quebre o problema em partes e pergunte. É mais eficaz eu responder "não entendo a ordem das mudanças dos valores dentro dos parênteses", por exemplo. Tente formular perguntas específicas =)

> Roger tem uma questão da pressa, 

Paciência é a habilidade dos campeões.

> eu trabalho com front-end, e vejo o pessoal que trabalha comigo dominando o javascript

Cada um tem seu ritmo de aprendizado. Pare de olhar o ritmo dos outros e foque no seu. 

Se comparar com os outros tem 2 caminhos:

1. Se você se julga melhor, tenderá a se acomodar.
2. Se você se julga pior, tenderá a se sabotar.

Nenhum dos dois caminhos vai te fazer bem.

Se você se comparar apenas com você mesmo, verá o quanto está evoluindo.

A meta é ser 1% melhor a cada dia. 1% melhor do que **você** era ontem.

**Comment by naldowebdeveloper** [comment]
ok, ciente meu amigo!

**Comment by Roger-Melo** [comment]
Edinaldo, vou fechar a issue mas no que precisar é so abrir uma nova =)
