### ISSUE TITLE
Dúvida - Exercício 9 - Aula -01-02 - Etapa 4

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#4400]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

```js

const typesInfo = function(type) {
    let tipos = {
        null: 'Seta, explicitamente, uma variável sem valor.',
        undefined: 'Representa um valor não-setado.',
        object: 'Arrays, Datas, Objetos literais, Funções, etc.'
    }
   return tipos[type]
}

console.log(typesInfo(null));
console.log(typesInfo(undefined));
console.log(typesInfo('object')); // assim funciona 
console.log(typesInfo(object)); // assim não funciona. 

```

Consegui resolver o exercício utilizando os valores null, undefined e object entre aspas simples. Mas vi que null e undefined também retornam o valor correspondente sem aspas. No entanto, object sem aspas apresenta um erro. Por que isso ocorre? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @aecio-neto!

Dê uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563), acredito que ela contém a resposta a essa dúvida.

Se ainda restar alguma dúvida, pode mandar aqui abaixo nessa issue que te ajudo =)

**Comment by aecio-neto** [comment]
Show, dúvida esclarecida.

**Comment by Roger-Melo** [comment]
Massa! Já que essa dúvida está esclarecida, vou fechar a issue. Mas ao surgir alguma dúvida, é só abrir uma nova issue =)
