### ISSUE TITLE
Resumo da Aula Arrow functions - Aula 02-02 da etapa 03

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4405]
É uma das adições do Javascript moderno

Qual o motivo da criação da Arrow Function?
Para se ter uma forma mais curta e concisa de se implementar funções. Se tem o nome de arrow function porque é utilizado => 
A estrutura da arrow function ficaria: ( ) => { }
Exemplo: 
```js
const double = (number) => {
  return number * 2
}

```
Caso a arrow function receba apenas 1 valor por parâmetro, os parênteses se tornam opcionais e também se o retorno desta função estiver apenas uma linha, pode se remover as {}. Ao refatorar o código acima ele ficaria:
```js
const double = number => number * 2
```

**Comment by Roger-Melo** [comment]
Excelente @AlessandroAscanio, rumo à fluência! 🎯
