### ISSUE TITLE
Etapa 11, nome do vídeo: Encadeando promises - Aula 04-04

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#441]
Oi, @Roger-Melo

Acabei de assistir as primeiras aulas sobre promises e gostei muito. Elas parecem ser uma forma muito mais simples e legível de escrever código. 

A minha dúvida é: Em que situações devemos usar promises, apenas quando estamos trabalhando com operações assíncronas?

Pergunto isso pois fazendo alguns testes para fixar o conteúdo, o código feito com promise me pareceu muito mais limpo e legível. Ex: 

```js 
getPokemon('https://pokeapi.co/api/v2/pokemon/1')
  .then(getPokemonName, logError)
  .then(showPokemonName)
```

O código acima me parece melhor do que escrever algo assim: 

```js 
const bulbasaur = getPokemon('https://pokeapi.co/api/v2/pokemon/1')
const pokemonName = getPokemonName(bulbasaur)
showPokemonName(pokemonName)
```

Porém só devemos usar essa sintaxe de promise quando vamos trabalhar com assíncronismo? Fazendo requests para uma API por exemplo? 

É uma má prática trocar uma função tradicional por uma promise?

Vou aproveitar essa issue para fazer outra pergunta de uma dúvida que me surgiu. 

Lendo a documentação na mdn sobre promise vi que o método then(), além da função de callback para tratarmos do retorno de uma promise, também pode receber uma outra função para lidar com a falha no resultado da promise. Algo assim: 

```js
myPromise()
  .then(logData, logError)
```

Quando devemos usar essa segunda função atrelada ao then() e quando devemos usar o catch()?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Hamilton.

> Em que situações devemos usar promises, apenas quando estamos trabalhando com operações assíncronas?

Exatamente. Não faz sentido usar promises para deixar o código assíncrono em momentos em que ele deveria ser síncrono.

> É uma má prática trocar uma função tradicional por uma promise?

Sim. Não faça isso 😅

> Quando devemos usar essa segunda função atrelada ao then() e quando devemos usar o catch()?

Dificilmente você verá alguém usando o segundo argumento do `then` pelo seguinte motivo...

No código abaixo, se um erro acontece em `f1`, ele é tratado pelo `catch`,

```javascript
promise
  .then(f1)
  .catch(f2)
```

mas isso não acontece aqui:

```javascript
promise
  .then(f1, f2)
```

O código acima não está tratando o erro por que um erro quando um erro acontece em f1, ele é passado para o encadeamento inferior. E não há encadeamento abaixo de `f1`.

Ou seja, um `then` passa o resultado/erro para o próximo `then` ou `catch`. Isso significa que se não houver um `catch` abaixo do `then`, o erro não é tratado.

Você pode comprovar isso observando a diferença ao executar o código abaixo:

```javascript
const getData = () => new Promise(resolve => {
  resolve('blá blá blá')
})

getData()
  .then(v => { throw new Error('Error message 1') }, err => console.log(err.message))

getData()
  .then(v => { throw new Error('Error message 2') })
  .catch(err => console.log(err.message))
```

Por isso, sempre prefira usar o `catch` para tratar erros.

Ficou mas claro?

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Ficou sim, muito obrigado!

**Comment by Roger-Melo** [comment]
Show @Hamiltonspjunior. No que precisar, é só abrir uma nova issue =)
