### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4416]
Tipos 			Primitivos | Tipos 			de Referência
-- | --
Numbers | Todos 			os tipos de objetos
String | Objetos 			Literais
Booleans | Arrays
Null | Funções
Undefined | Datas
Symbol | Todos 			os outros tipos
BigInt |  

Qual a diferença entre um tipo primitivo e um tipo referência?

A forma com que são armazenados na memória. Os primitivos são armazenados na parte chamada stack(pilha) e o seu acesso é mais rápido, porém o seu tamanho de armazenamento é limitado. O tipo referência é armazenado na parte heap (Amontoado) que tem uma capacidade maior de armazenamento porém seu acesso é um pouco mais lento.

Como esse processo funciona na memória?

No caso dos primitivos eles são acessados diretamente pelas variáveis. No caso do tipo referência é armazenado um pointer(ponteiro) na memória stack que faz a referência ao objeto/array..etc que está armazenado no heap da memória.

Quando se faz uma cópia de uma variável primitiva é criado um novo valor na parte stack da memória, ou seja se você deletar ou substituir o valor original, ao cópia mantém o valor original. No caso do tipo referência é criado um novo pointer porém ele referencia o mesmo objeto. O que isso significa? Se algum valor for alterado no objeto como ambos ponteiros apontam para o mesmo objeto/array o valor de ambos é alterado.

**Comment by Roger-Melo** [comment]
Boa @AlessandroAscanio, rumo à fluência! 🔥
