### ISSUE TITLE
Resumo da Aula While loop e exercicios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4417]
Lacos de repeticao:
FOR
for (i =0; i < let; i++) {
 codigo
}

// neste laco de repeticao o contador, condicional e incrementador ficam dentro do parenteses.

WHILE
let exemplo = 0
while (exemplo < a) {
 codigo
 exemplo += 1
}
// neste laco de repeticao somente a condicional fica dentro do parenteses e a variavel em questao ja deve existir fora do laco.

obs: lacos de repeticao podem ser aninhados.

**Comment by Roger-Melo** [comment]
Boa @YukOnRails, rumo à fluência! 🔥
