### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by EnricoTomaz** [roger-melo-treinamentos/curso-de-js-roger-melo#4420]
##### Resumo geral: Começa a aula falando de um conceito fundamental em linguagem de programação: Variáveis. Após, fala das convenções para se criar nomes para variáveis e finaliza a aula falando brevemente sobre o suporte dos navegadores e como comentar um código.

  Variáveis armazenam valores (nomes, email, número ... etc). Podem ser chamadas usando as palavras reservadas **let**, **const** ou **var**.
  Usando a palavra reservada **let** criamos uma variável que podemos, em outro lugar do código, alterar o seu valor. Para mudar esse valor, ou, em outras palavras, fazer uma **reatribuição** é necessário apenas digitar o nome da variável seguida do simbolo de atribuição (=) e digitar o novo valor. 

   Exemplo: 
Atribuindo um valor para a variável age:
```js
let age = 26
```
Reatribuindo um valor para a variável age:
```js
age = 36
```

Usando a palavra reservada  **const** atribuimos um valor a uma variável que não poderá ser mudado em momento algum do código. Se definimos:
```js
const number = 100
```
Isso significa que a variável number sempre terá o valor 100.

Usando a palavra reservada **var** atribuimos uma valor a uma variável que, ao modo de let, poderá ter seu valor mudado. Esta forma de criar uma variável, segundo pude entender da aula, caiu em desuso.

Convenções para nomes de variáveis:

1) Deve ser uma unica palavra, não deve ter espaços. Fala da convenção camelCase.
2) Não pode começar com número.
3) O nome das variáveis não deve ser igual a palavra reservada da linguagem usada.
Nota: As variáveis devem ter nomes significativos, nomes que revelam uma intenção. As variáveis devem ter nomes claros o suficientes para que outro desenvolvedor, batendo o olho, possa entender o que essa variável faz, armazena..etc.

Fala, brevemente, sobre o suporte dos navegadores

É possível que features mais atuais(como as palavras reservadas let e const) não funcionem mais em navegadores mais antigos como o Explorer.

Fala sobre Comentário de codigos
1) Comentarios de 1 linha usa //
2) Comentarios multilinhas /* */

**Comment by Roger-Melo** [comment]
Boa @EnricoTomaz, rumo à fluência! 🔥
