### ISSUE TITLE
Duvida no exercício 04  - Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by FerreiraIommi** [roger-melo-treinamentos/curso-de-js-roger-melo#4425]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284

### Descreva a dúvida

Roger, fiquei com uma duvida em um exercício, mesmo eu vendo a a resposta dele, eu não consegui compreender.

```js
/*
  04

  - Comente o código acima, de forma que a string não seja mais exibida no  
    console;
  - Implemente uma função que retorna um novo array com as strings do array  
    "millennialWords" em letras maiúsculas;
  - Exiba o novo array no console, sem inserir um console.log() dentro da  
    função.
*/

const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']


const transformToUpperCase = function (array = [] ) {
  let newArray = []

  for (let i = 0; i < array.length; i++) {
    newArray.push(array[i].toUpperCase())
  }
  return newArray

}

console.log(transformToUpperCase(millennialWords))

```

Minha dúvida seria na hora do For loop, como o array.length consegue captar quantos numeros ele tem, se você declarou ele como vazio, eu não consigo compreender como ele consegue fazer esse loop, já que em nenhum momento durante a função, voce  menciona por exemplo a "millennialWords.length"

Obrigado

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @FerreiraIommi!

> ## como o array.length consegue captar quantos numeros ele tem

O fato é que o array que em que a propriedade `.length` está encadada não é o array vazio (`newArray`), a propriedade `.length` está encadeada na referência do parâmetro `array` =)

Lembra que parâmetros são variáveis que só existem dentro de uma função?

Se `array` é um parâmetro (e parâmetros são variáveis), isso significa que o parâmetro `array` recebeu `millennialWords`, pois o `millennialWords` foi inserido como argumento da invocação da função:

```javascript
const transformToUpperCase = function (array = [] ) { // 👈🏻 array recebeu o valor que foi inserido como argumento
  let newArray = []

  for (let i = 0; i < array.length; i++) { // 👈🏻 como array está armazenando o array millennialWords, array.length resulta na quantidade de itens de millennialWords
    newArray.push(array[i].toUpperCase())
  }
  // ...
}

// 👇🏻 a função recebeu como argumento o array millennialWords
console.log(transformToUpperCase(millennialWords))
```

Ou seja, o parâmetro `array` é uma variável (que funciona apenas na função) que armazenou `millennialWords` =)

Vc pode comprovar isso inserindo um `console.log` para checar o valor que `array` armazena:

```javascript
const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']

const transformToUpperCase = function (array = [] ) {
  console.log('array:', array) // ['lol', 'yolo', 'troll', ...]
  // ...
}

console.log(transformToUpperCase(millennialWords))
```

Lembre-se: argumento é o valor que é inserido na invocação da função. Parâmetro é a variável que recebe o valor que foi inserido como argumento.

Se na expressão do `for` houvesse `newArray.length` ao invés de `array.length`, aí sim o retorno seria um array vazio, pq `newArray.length` resultaria em zero pq `newArray` é um array vazio =)

Está ficando mais claro?

**Comment by FerreiraIommi** [comment]
Perfeito Professor! 

Ficou muito bem explicado!

Muito Obrigado!!!
