### ISSUE TITLE
Resumo da Aula 01-03 da etapa 03 - Function declaration, function expression e hoisting 

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4431]
### Funções 
São um bloco de código que podemos reaproveitar diversas vezes e quando quisermos, existem duas formas de criarmos uma função.

### Function declaration
```js
function myAge () {
console.log(25)
}

myAge() // 25 será exibido
```
nos invocamos uma função chamando o seu nome e abrindo e fechando parênteses no final dela, assim o bloco de código dentro dela será executado

### Function expression
```js
const myColor = function () {
console.log('green')
}

myColor() // green será exibido
```
Em uma function expression  nos atribuímos a função a uma variável e a invocamos da mesma maneira, com seu nome abertura e fechamento de parênteses

Existe uma diferença entre function declaretion e expression, na function declaration acontece o (hoisting) que é a elevação da função caso a invocação seja feita antes da declaração 
```js
myAge() // 25 será exibido

function myAge () {
console.log(25)
}
```
O javascript por debaixo dos panos faz a elevação da função mesmo que ela ainda não tenha sido declarada.

Na function expression não acontece o hoisting, sendo necessário que a invocação seja feita após a declaração da função

**Comment by Roger-Melo** [comment]
Boa @Diegodkid , rumo à fluência! 🔥
