### ISSUE TITLE
Resumo da Aula: Criando um objeto literal, Aula 01-03 etapa 04

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4435]
Para criar um objeto literal criamos variável com um nome e atribuímos a ele  chaves,  dentro das chaves colocamos suas propriedades(ou chave) e valores, por exemplo: criar um Usuário: let user {} - Criamos uma let user e atribuímos a ela propriedades como o nome, idade, email, cidade, etc… dentro das chaves! 
Para acessar um valor usamos atribuição de ponto: user.name. Pra modificar qualquer valor podemos fazê-lo manualmente direto na chave, ou fazer de qualquer ponto do código: user.name = 40; e com o console vemos que name foi alterado. Podemos acessar a propriedade através da notação de colchetes, nesse caso devemos usar uma variável: let key = 'name'- user[key]. E para saber o seu tipo: console.log(typeof user), veremos que é um objeto.

**Comment by Roger-Melo** [comment]
Boa @Morais465, rumo à fluência! 🔥
