### ISSUE TITLE
Discord para alunos do CJRM

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4438]
### Etapa da aula

1

### Nome da aula

Discord para alunos do CJRM

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/2186928

### Descreva a dúvida

Roger apenas uma dica, nao seria legal montar um discord para todos alunos do CJRM para um grupo de estudo?

Grato, 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @fabioromagnoli99!

Essa é uma ideia pro futuro. No momento, é inviável devido à necessidade de moderação. Mas no futuro deve rolar sim.

De qualquer forma, sempre que tiver dúvidas, pode abrir issues aqui que te ajudo no que for preciso, ok? =)
