### ISSUE TITLE
Dúvida na questão 04 do exerc. 36

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#4439]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 01 da etapa 14 - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1615431

### Descreva a dúvida

```js
/*
  04

  - Descubra o que o código abaixo está fazendo e refatore-o para que o objeto 
    criado permaneça intacto.
*/

const third = obj => ({
  ...obj,
  d: 3
})

const second = obj => third(obj)
const first = obj => second(obj)

const object = { k: 't' }

const object2 = first(object)
console.log(object, object2)

```

Roger, porque a primeira função invocada é essa `const first = obj => second(obj)`? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Jansen-Muniz!

> ### Roger, porque a primeira função invocada é essa `const first = obj => second(obj)`? 

Vc diz nesse pedaço de código abaixo?

```javascript
const object2 = first(object)
```

Basicamente pq a invocação dela desencadeia as invocações das funções `second` e `third` =)

E agora eu pergunto a vc: consegue explicar o quê as funções `first`, `second` e `third` fazem?

**Comment by Jansen-Muniz** [comment]
Basicamente pq a invocação dela desencadeia as invocações das funções second e third =) -> Entendi.

A`first`retorna a`second`, a`second`retorna a`third`, e a`third`cria um novo objeto. É isso?

**Comment by Roger-Melo** [comment]
Não é que uma retorna a outra. 

É que uma retorna o valor que a outra retorna ao ser invocada.

Ao ser invocada, `first` retorna o valor que a invocação de `second(obj)` retorna, e `second(obj)` ao ser invocada, retorna o valor que a invocação de `third(obj)` retorna.

`third`, ao ser invocada, retorna um novo objeto que contém todas as propriedades de `obj`, mais a propriedade `d` armazenando `3`.

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Esqueci de dizer que retorna o valor =/.
Valeu, mano.

**Comment by Roger-Melo** [comment]
Boa! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
