### ISSUE TITLE
Resumo da Aula Timestamps e comparações - Aula 01-03 da etapa 10

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#444]
O *timestamps* representa a quantidade de milissegundos passados desde 1° de janeiro de 1970, às 00:00:00, até o momento no tempo que o *objeto* de data representa. 

Utiliza-se bastante o *timestamps* para obter o intervalo entre duas datas, e, com isso podemos obter:

- A quantidade de ***milissegundos*** passados entre uma data e outra;
- A quantidade de ***segundos*** passados entre uma data e outra;
- A quantidade de ***minutos*** passados entre uma data e outra;
- A quantidade de ***horas*** passadas entre uma data e outra;
- A quantidade de ***dias*** passadas entre uma data e outra;
- A quantidade de ***anos*** entre uma data e outra;
- ...

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! 🔥
