### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4442]
Null e Undefined - São semelhantes e ambos representam a falta de uma valor.
A principal diferença entre eles é que o Null deve ser intencionalmente atribuído.
  
Exemplos:
  
1)

```js
	let emptiness
	console.log(emptiness, emptiness + 3, `o valor é ${emptiness`);
	// undefined NaN "o valor é undefined"
```

Nota1: Quando é usado undefined numa expressão númerica, resulta NaN
Nota2: Quando o valor undefined é usado em uma string, ele automaticamente é convertido para string.
	

2) Usamos o null quando quisermos indicar intencionalmente que não existe valor para ela.

```js
	let emptiness = null
	console.log(emptiness, emptiness + 3, `o valor é ${emptiness`);
	// null 3 "o valor é null"
```
Nota1: Quando se usa um valor null em uma operação matemática, ele automaticamente é interpretado como zero

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano, rumo à fluência! 🔥
