### ISSUE TITLE
Resumo da Aula: Adicionando métodos, Aula 01-04 etapa 04

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4444]
Métodos são funções criadas dentro de objetos, por exemplo add um login pro 
usuário, vamos colocar uma vírgula no fim de blogPosts, e colocar o login e dentro dele adicionar uma função. Como a propriedade login armazena uma função 
ela é um método, e pra invocá-la basta fazer notação de ponto com objeto e login: user.login(), para add mais métodos basta colocar uma vírgula, dar o nome e aplicar a função.

let user = {
    name: 'João',
    age: 31,
    email: 'Ogen4p@yahoo.com.br',
    city: 'São Paulo',
    blogPosts: [' Flango', 'batata doce'],
    login: function () {
        console.log('usuário logado')
    },
    logout: function () {
        console.log('usuário deslogado')
    }
}

user.login()
user.logout()

**Comment by Roger-Melo** [comment]
Boa @Morais465, rumo à fluência! 🔥
