### ISSUE TITLE
Duvida no exercicio 02 - Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### ISSUE THREAD

**Issue by muritadb** [roger-melo-treinamentos/curso-de-js-roger-melo#4446]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1324088

### Descreva a dúvida

Olá Roger, boa noite tudo bem, no desafio 02 do exercicio 30 você pede para que uma função calculator receba outra função para realizar operações matematicas. A minha duvida é se a minha resolução esta correta ou não. Eu consegui chegar no resultado que o exercicio pediu porem é diferente da sua resolução. segue o codigo: 
````js
const operators =
  [
    `+`,
    `-`,
    `*`,
    `/`,
    `%`
  ]

const calculateOperation = (number1, number2, operador) => {
  let result = 0

  if (operators.includes(operador)) {
    if (operador === '+') {
      result = number1 + number2
    } else if (operador === '-') {
      result = number1 - number2
    } else if (operador === '*') {
      result = number1 * number2
    } else if (operador === '/') {
      result = number1 / number2
    } else {
      result = number1 % number2
    }

    return `Resultado da operação: ${number1} ${operador} ${number2} = ${result}.`
  }

  return "Operação inválida."
}

const calculator = operador => calculateOperation(10, 5, operador)

console.log(calculator('+'))
```


<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by MivlaM** [comment]
Olá @muritadb!


> ### A minha duvida é se a minha resolução esta correta ou não. Eu consegui chegar no resultado que o exercicio pediu porem é diferente da sua resolução.

Eu testei o seu código aqui na minha máquina e para todas as situações descritas no exercício, o seu código funciona corretamente. Num primeiro momento, o mais importante é fazer funcionar mesmo, assim como você fez =)

Uma observação que posso fazer é a seguinte: O seu código possui muitos blocos de `if` e `else if` em sua função `calculateOperation` e elas estão dentro de um `if` aninhado.

```js
const calculateOperation = (number1, number2, operador) => {
  /// ...

  if (operators.includes(operador)) {
    if (operador === '+') {
      result = number1 + number2
    } else if (operador === '-') {
      result = number1 - number2
    } else if (operador === '*') {
      result = number1 * number2
    } else if (operador === '/') {
      result = number1 / number2
    } else {
      result = number1 % number2
    }
    /// ...
  }
  /// ...
}
```

Em aplicações maiores, o design de código que usa `if` aninhado torna o entendimento muito mais difícil, é complicado entender e fazer manutenção nesse tipo de código. Outra coisa, muitos blocos de `if` e `else if` tornam o código mais verboso, ou seja, é muito código escrito para fazer algo relativamente simples. Eu recomendo que você dê preferência a forma que foi mostrada na resolução, nessa especificamente, para resolver esse exercício sem o que foi observado acima, há conceitos importantes sobre propriedades dos objetos e curto circuito que você precisa entender.


Uma outra observação, quando o sinal de atribuiçao `=` é utilizado fora da declaração do identificador (const, let, parâmetro) é um indício que está acontecendo uma mutação de valor. No caso do seu código, `result` recebe 0 e depois está recebendo todo o valor das variáveis de acordo com o operador escolhido.

```js
const calculateOperation = (number1, number2, operador) => {
  let result = 0 // result recebe 0

  if (operators.includes(operador)) {
    if (operador === '+') {
      result = number1 + number2 // mutações
    } else if (operador === '-') {
      result = number1 - number2 // mutações
    } else if (operador === '*') {
      result = number1 * number2 // mutações
    } else if (operador === '/') {
      result = number1 / number2 // mutações
    } else {
      result = number1 % number2 // mutações
    }
    // ...
  }
  // ...
}

```

Existe um princípio chamado princípio da imutabilidade. Uma mutação tende a causar bugs na aplicação, a aplicação se torna menos previsível e é mais difícil de manter. Por isso que é recomendado evitar mutações.

---

Ficou claro?

**Comment by muritadb** [comment]
Entendi, ficou claro sim, ainda estou tentando pegar a questão imutabilidade e do curto circuito, aonde usar, quando usar.

**Comment by Roger-Melo** [comment]
Imutabilidade: vc deve usar sempre que possível. É um princípio que vai fazer suas aplicações tenderem a ter menos bugs e serem mais fáceis de manter =)

---

Curto circuito:

```javascript
const value = 'x' || 'y'

console.log(value) // 'x'
```

No código acima, a variável `value` armazenou a string `'x'`, pq na expressão `'x' || 'y'`, o valor à esquerda do `||` (string preenchida) é um valor truthy. Sendo assim, a expressão de curto-circuito retornou `'x'`.

Agora, se o valor à esquerda do `||` não é truthy, a expressão de curto-circuito retorna o valor à direita de `||`, independente se esse valor é truthy ou não:

```javascript
const value = '' || 'y'

console.log(value) // 'y'
```

Ou seja, vc pode usar o curto-circuito quando quer retornar um valor caso ele seja truthy, e se esse valor não é truthy, vc precisa retornar um outro valor =)

Está ficando mais claro?

@muritadb

**Comment by muritadb** [comment]
Entendi, ficou mais claro sim. Obrigado
