### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4460]
SWITCH statment e um mecanismo de controle fluxo que serve para verificar multiplos valores possiveis de uma variavel ou constante.
Estrutura do Switch:

         switch(variavel1) {
      case 'valor1':
      bloco de codigo ex: console.log()
      break
      case 'valor2':
      bloco de codigo ex: console.log()
      break
      case 'valor3':
      bloco de codigo ex: console.log()
      break
      default:
      bloco de codigo ex: console.log()
      }
Neste exemplo o BREAK e usado para parar a iteracao de acordo com a condicional, senao ela sera executada ate o final automaticamente.

DEFAULT e similar o ELSE,  e utilizado no final da estrutura e executado caso nenhum match anterior aconteca.

**Comment by Roger-Melo** [comment]
Boa @YukOnRails, rumo à fluência! 🔥
