### ISSUE TITLE
Resumo da Aula Encadeando métodos - 02 - 03 da etapa 08

### ISSUE THREAD

**Issue by VitorPeixotoDev** [roger-melo-treinamentos/curso-de-js-roger-melo#4461]
O tema abordado nessa aula me pareceu muito mais uma facilidade naturalmente desenvolvida pela 
linguagem que um novo tópico ou "matéria nova do curso". Faz total sentido o encadeamento de métodos
quando a linguagem é cheia de _shortenings_ em passagens de argumentos e iterações. Pessoalmente,
também acredito que o encadeamento de métodos dá um ar de maior elegância e dinamismo ao código.

**Comment by Roger-Melo** [comment]
Boa @VitorPeixotoDev, rumo à fluência! 🔥
