### ISSUE TITLE
Resumo da Aula Break e continue - Aula 03-03 da etapa 02

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4471]

**Comment by EdsonAjjunior** [comment]
O break ou continue podem ser utilizado no loop com o intuito de dar uma pausa quando chegar em determinado ponto solicitado ou dar uma continuação quando chegar em determinada sentença.

**Comment by Roger-Melo** [comment]
Boa @EdsonAjjunior, rumo à fluência! 🔥
