### ISSUE TITLE
Aplicação: [Todo List]

### ISSUE THREAD

**Issue by tonymatheus** [roger-melo-treinamentos/curso-de-js-roger-melo#4472]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/tonymatheus/todoListApplication

### Maiores dificuldades durante a implementação

- Entender como utilizar o  dataSet para fazer a remoção do todo foi um pouco complicado mas acredito que tenha conseguido aplicar da forma certa.
-  A implementação do método de search também não tinha ficado muito claro pra mim tive que refazer duas vezes pra entender 100%.
- Tentei refatorar o método de search mas, infelizmente não consegui fazer com que o código ficasse mais legível nesse refactory  então optei por deixar como já estava e seguir com as aulas para ver uma melhor implementação.

### Menores dificuldades durante a implementação

- Entender oque devia ser feito 
-  Utilizar o bootstrap

**Comment by Roger-Melo** [comment]
Olá @tonymatheus.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by tonymatheus** [comment]
Tá ok!

**Comment by Roger-Melo** [comment]
Olá @tonymatheus!

Você pode baixar a análise de sua aplicação [neste link](https://drive.google.com/file/d/1IgMjyKgJ4vcm93Hr7am88yIngy2hDBD_/view?usp=sharing).

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
