### ISSUE TITLE
Resumo da Aula Switch da etapa 02

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4476]
A condicional Switch

Imagine que queremos verificar o valor de uma variável e executar uma ação dependendo de qual valor essa variável armazena
Poderíamos usar um encadeamento de if e elses onde verificaríamos possíveis valores dessa variável
Mas ficaria muito repetitivo escrever uma série de condições após a outra
Uma alternativa para verificar múltiplos valores possíveis de uma variável ou constante é
o SWITCH statements.
O Switch serve para chegar todos os possíveis valores de uma variável ou constante
```JS
const grade = 'B"

switch (grade) {
case A :
console.log ('Você tirou um "A")
break

case B :
console.log ('Você tirou um "B")
break

case C :
console.log ('Você tirou um "C")
break

case D :
console.log ('Você tirou um "D")
break

case E :
console.log ('Você tirou um "E")
break

default
console.log ('Nota inválida')
```

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr, rumo à fluência! 🔥
