### ISSUE TITLE
Resumo da Aula Else e else if statements da etapa Aula 02-03

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4478]
Caso a condição resultar em false no código, uma condição diferente precisa ser colocada no controle de fluxo, é ai que entra o 

    "else"     em português seria "se não", e também o    "else if"   que em português seria  "se não, si ".

Exemplo abaixo:

const password = 'oi12aaaaaa'

if (password.length > 12) {
    console.log('senha forte')
}
else if (password.length > 8) {
    console.log('senha valida') 
} 
else {
    console.log('senha invalida')    
    }

Que neste caso resultaria em     "else if"

IMPOPTANTE      "if"   ,   "else if"   e   "else"     são separados pelos blocos. É sempre, sempre, apenas um dos blocos de código será executado.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
