### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || da etapa 02

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#448]
OPERADORES LÓGICOS && E ||
Vamos ver agora como executamos um bloco de código se a combinação de condições diferentes resultarem em *true*. Para isso, utilizamos os operadores lógicos. Os dois principais são o || (ou) e o && (e). Então vamos imaginar a seguinte situação: Estamos validando uma senha (const password), e para que ela seja considerada muito forte de acordo com a nossa regra de negócio, ela deve conter 12 ou mais caracteres e conter o # como parte da password. Então nesse caso utilizaremos o operador lógico &&, ou seja, as duas condições devem retornar *true*. A validação nesse caso será `if (password.length >= 12 && password.includes('#')) { // do something }`. Neste exemplo, o bloco de código só será executado se as duas condições retornarem *true*. Se uma não retornar *true*, o bloco de código não será executado. Então o uso do operador lógico && (e) é para verificar se duas (ou mais) condições são verdadeiras.

```jsx
const password = '#thisIsMyNewPassword123';

if (password.length >= 12 && password.includes('#')) {
	console.log('Senha muito forte =D');
} else if (password.length >= 8) {
	console.log('Senha forte =)');
} else {
	console.log('Senha fraca. A senha deve conter 8 ou mais caracteres =/');
}

// Senha muito forte =D
```

Agora vamos falar do operador lógico || (ou). Utilizando o código do exemplo acima, vamos modificar as condições do *else if*, incluindo o operador lógico || (ou) com uma nova condição, que será a verificação da existência do caractere @ na const password. Nesse caso, basta uma das condições retornar *true* para que seu bloco de código seja executado, ou seja, se a password for igual ou maior a 8 caracteres "ou" tiver o caractere @. Vamos ver na prática:

```jsx
const password = 'p@ss';

if (password.length >= 12 && password.includes('#')) {
	console.log('Senha muito forte =D');
} else if (password.length >= 8 || password.includes('@')) {
	console.log('Senha forte =)');
} else {
	console.log('Senha fraca. A senha deve conter 8 ou mais caracteres =/');
}

// Senha forte =)
```

Então no exemplo acima, apesar de a password ter menos de 8 caracteres, ela tem o caractere @ em seu conteúdo. A primeira condição retornou *false*, mas a segunda condição retornou true, logo, seu bloco de código será executado. O problema da nossa regra de negócio é que mesmo que a password tenha 1 caractere e esse seu único caractere seja o @, ela será considerada uma senha forte, mesmo estando claro que não é. Então vamos ajustar essa verificação fazendo uma combinação dos operadores lógicos. A nossa regra então será: é considerada uma senha forte se a quantidade de caracteres for maior ou igual a 8 "ou" a password conter o caractere @ "e" tiver 6 ou mais caracteres. Isso servirá para prevenirmos que uma password com menos de 6 caracteres seja considerada forte simplesmente por conter o @. Nós podemos fazer esse tipo de verificação, onde o separador das condições que devem retornar *true* será o || (ou). Então nosso código ficaria da seguinte forma:

```jsx
const password = 'myP@ss';

if (password.length >= 12 && password.includes('#')) {
	console.log('Senha muito forte =D');
} else if (password.length >= 8 || password.includes('@') && password.length >= 6) {
	console.log('Senha forte =)');
} else {
	console.log('Senha fraca. A senha deve conter 8 ou mais caracteres =/');
}

// Senha forte =)
```

Então para que a senha seja considerada forte, ela deve atender a pelo menos uma das condições separadas por ||: Ou ela deverá ter 8 ou mais caracteres, ou ela deverá conter o @ e ter 6 caracteres ou mais.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Rumo à fluência! 🔥
