### ISSUE TITLE
Resumo da Aula Introdução ao Firebase 01-10 da etapa 15

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4480]
Banco de dados (ou database) é um local onde podemos armazenar informações de nossa aplicação de forma organizada. Qualquer tipo de dado pode ser armazenado em um banco de dados. Um exemplo do uso dele é em um perfil do GitHub. Toda vez que inserimos informações nele e salvamos, ao ser acessado, o banco de dados irá buscar as informações atreladas a ele e exibir no perfil.

Diferente do localStorage (que armazena informações no próprio navegador), as informações contidas no banco de dados não ficam limitadas ao computador do usuário. Eles poderão ser acessados de qualquer dispositivo. 
Existem dois tipo de banco de dados que podemos utilizar em aplicações: SQL e noSQL.

Structured Query Language - linguagem de consulta estruturada, de pesquisa de banco de dados relacionais (baseados em esquemas, fazendo uso de tabelas, linhas e colunas, sendo muito popular com quem trabalha com Python ou PHP).

No Structured Query Language - linguagem de consulta não estruturada, de banco de dados não relacionais, utiliza collections, documents e properties.
Uma vantagem do noSQL em comparação ao SQL é que o primeiro é mais flexível na hora de realizar alterações nos dados do banco de dados, sendo portanto ideal quando iniciamos a construção de uma aplicação que ainda não temos noção completa da estrutura este irá necessitar ao longo de seu desenvolvimento.

O Firebase é um serviço de backend que possui o Firestore (banco de dados noSQL, cujo modo de trabalho pode-se dizer semelhante ao que tratamos objetos em Javascript. Existem outras opções, mas pela quantidade de serviços oferecidos no plano grátis, este se torna uma opção bastante atrativa, pois não é apenas um banco de dados, é uma plataforma do Google (sendo popularmente chamado de Backend As A Service), e permite ao desenvolvedor poder focar no frontend uma vez que não precisa se preocupar em construir o backend do zero.

Para usar o Firebase não há necessidade de instalar nada, ele é utilizado de forma online, o que se traduz em alta disponibilidade. Quanto às desvantagens, o Firebase torna-se inviável para aplicações muito complexas e muito limitada por regras de negócios. Dependendo da aplicação, pode tomar muito tempo para implementação e adequação.
Um banco de dados noSQL possui a seguinte estrutura:
instância do banco de dados (container das informações) >> collections (que podem representar um tipo específico de informações) >> documents (que possui estrutura parecida com um objeto JS, e cada um possui um id próprio).

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Kmkery, rumo à fluência! 🔥
