### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by henriquesouzadev** [roger-melo-treinamentos/curso-de-js-roger-melo#4482]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/henriquesouzadev/weather-application/

### Maiores dificuldades durante a implementação

Fazer as funções para obter os dados da API.

### Menores dificuldades durante a implementação

Inserir os dados na aplicação

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev!

Você pode baixar a análise de sua aplicação [neste link](https://drive.google.com/file/d/1CEJn7Odr42vRBc2ceBVKV6pVl69lbH72/view?usp=sharing).

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by henriquesouzadev** [comment]
Obrigado @Roger-Melo! Vou assistir

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
