### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - 02-04 da etapa 01

### ISSUE THREAD

**Issue by gustavo-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#4490]
## lastIndexOf

Esse método recebe um parâmetro e retorna em qual posição da ``` string ``` a ultima ocorrência dele se encontra.

#### EX:
```js
const a = "gustavo.viana@rogermelo.com"
console.log(a.lastIndexOf("m"))
//será exibido 26 que é o numero da posição

```
## Slice

O ``` slice ``` é um método que recebe parâmetros, cada um desses parâmetros tem uma função o primeiro parâmetro corresponde ao índice a partir de onde você quer começar a capturar da``` string ```e o segundo parâmetro é o  numero do índice onde dali pra frente vai ser ignorado, esse método não altera a ``` string ```original.

#### Ex: 
```js
const a = "gustavo.viana@rogermelo.com"
console.log(a.slice(0, 1))
//será exibido apenas a letra G
```	
## Replace
O método ```replace``` , também recebe dois parâmetros, e também não altera a ``` string ```original, esse método recebe dois parâmetros sendo o primeiro uma ``` string ``` que você que encontrar na ``` string ``` original e o segundo parâmetro é o valo a ser colocado no lugar, ou seja, o substituto.

#### EX:
```js
const a = "gustavo.viana@rogermelo.com"
console.log(a.replace("gustavo", "Roger"))
//será exibido: Roger.viana@rogermelo.com
```

**Comment by Roger-Melo** [comment]
Excelente @gustavo-viana, rumo à fluência! 🎯
