### ISSUE TITLE
Uso do spread operator

### ISSUE THREAD

**Issue by ghostnetrn** [roger-melo-treinamentos/curso-de-js-roger-melo#4492]
### Etapa da aula

15

### Nome da aula

Correção dos exercícios da aula 01 da etapa 15 - Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2599647

### Descreva a dúvida

Professor, bom dia. 

Fique com dúvida na parte do retorno da função usando o spread operator.

```js
const aString = 'O Curso de JavaScript Roger Melo funciona com turmas fechadas, abertas poucas vezes e é focado em quem ainda não é fluente em JS. Ou seja, quem não consegue construir aplicações web com JavaScript puro.'

const getIndexesOfCharacter = (string, caractere) => [...string]
  .reduce((acc, item, index) => item.toLowerCase() === caractere.toLowerCase() ? [...acc, index] : acc, [])

console.log(getIndexesOfCharacter(aString, 'c'))
```

A cada execução do código, o que está acontecendo com [...acc, index]?

Eu não entendi bem o uso do spread operator e do index no array de retorno da condicional. Se eu deixar só o [...acc], percebi que o código não retorna nada. E se inserir apenas index, ele retorna o último index do caractere.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ghostnetrn!

Você pode baixar a resposta à sua dúvida [neste link](https://drive.google.com/file/d/1pAX4aVeSZZ3PDPP1DdszBlsbvheCgKFm/view?usp=sharing).

Se restar qualquer dúvida, é só dar o toque =)

**Comment by ghostnetrn** [comment]
Obrigado Professor! Excelente explicação. Como sempre muito atencioso e prestativo.

Tudo entendido. ;)
