### ISSUE TITLE
Etapa 2, Controle de fluxo - Exercício-06 (Questão 3)

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#45]
### Bom dia Roger, eu resolvi a lógica dessa maneira

  03
  - Armazene sua idade em uma constante;
  - Escreva uma estrutura condicional em que, se a idade é 7 anos ou menos, ou se a idade é 65 anos ou mais, a frase "Para você, a entrada é grátis!" é armazenada em uma variável;
  - Se a idade não atende às condições acima, a variável deve armazenar a mensagem "A entrada é R$ 30,00.";
  - Exiba a mensagem no console;
  - Agora, teste diferentes idades para se certificar que a condição do `if` também está funcionando.

```js
const age = 26

if (age <= 7 || age >= 65) {
  console.log('Para você, a entrada é grátis!')
} else {
  console.log('A entrada é R$ 30,00.')
}
```

### Mas vi que na correção teve algumas coisas diferentes 

```js
const age = 26
let priceMessage = null

if (age <= 7 || age >= 65) {
  priceMessage = 'Para você, a entrada é grátis!'
} else {
  priceMessage = 'A entrada é R$ 30,00.'
}

console.log(priceMessage)
```

### Como a criação da 

```js
let priceMessage = null
```

### O resultado é o mesmo mais queria saber qual a diferença entre elas e sorry se a pergunta soa um pouco beginner hehe

OBS: Não sei se eu coloquei o nome certo. "Etapa" você se refere ao módulos do curso ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gohara.

Não precisa ter vergonha de perguntar. Não fique com dúvidas.

> OBS: Não sei se eu coloquei o nome certo. "Etapa" você se refere ao módulos do curso ?

Isso mesmo. Etapa e módulo querem dizer a mesma coisa =)

---

> Mas vi que na correção teve algumas coisas diferentes

Um dos objetivos desse exercício é fazer reatribuições de strings dependendo de qual bloco da estrutura condicional foi executado.

Então nesse exercício, declarar uma let, fazer reatribuições de strings a ela e exibir no console o valor da let apenas depois da estrutura condicional é um requisito.

Vai chegar o momento em que eu não vou detalhar tanto o passo a passo do que precisa ser feito. Mas até lá, tente resolver os exercícios seguindo os requisitos que ele pede =)

**Comment by GoharaJunior** [comment]
Ah sim, então beleza

**Comment by Roger-Melo** [comment]
Legal então, Gohara. Vou fechar a issue, mas no que precisar, estou à disposição =)
