### ISSUE TITLE
Resumo da Aula02-02 - Um overview sobre tipos de dados da etapa 01

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4509]
## Tipo de Dados em JS

- **Number**
    
    1,2,3,100, 3.14
    
- **String**
    
    'Hello, world' "[oi@fabio.com](mailto:oi@fabio.com)"
    
- **Boolean**
    
    True / False
    
- **Null**
    
    Seta, explicitamente, uma variável sem valor
    
- **Undefined**
    
    Representa um valor não-setado
    
- **Object**
    
    Estruturas de dados complexas - Arrays, Datas, Literais, etc
    
- **Symbol**
    
    Utilizado com objetos
    
- **BigInt**
    
    Utilizado para manipular números muito grandes

**Comment by Roger-Melo** [comment]
Excelente @fabioromagnoli99, rumo à fluência! 🎯
