### ISSUE TITLE
Resumo da Aula Eventos do teclado - Aula 02-03 da etapa 06

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4515]
keyup → captura qual tecla foi utilizada após o usuário solta-lá.
```js
const form = document.querySelector(‘form’)
const textUserName = value => /^[a-zA-Z]{6,12}$/.test(value)
form.username.addEventListener(‘keyup’, event => {
  const isValidUsername = testUserName(event.target.value)
    if(isValidUsername){
      form.username.setAttribute(‘class’, ‘success’)
      return
   }
    form.username.setAttribute(‘class’,’error’)
})
```
No código acima na linha 1 está sendo pega a referência do form, na linha 2 está sendo criada uma função que retorna o teste de uma regex(true/false), na linha 3 está sendo criado um evento no form de keyup, na linha 4 uma const está recebendo o resultado do teste da regex e armazenando-o, na linha 5 um if esta recebendo a const isValidUsername com o resultado da regex caso for true será inserido uma class=’success’ no elemento com id ou name chamado username, caso contrário receberá a class=’error’.
Neste caso está sendo utilizado o método setAttribute justamente pelo fato dele subscrever o atributo já existente, porque elemento poderá receber uma class success ou uma class error.

**Comment by Roger-Melo** [comment]
Excelente @AlessandroAscanio, rumo à fluência! 🎯
