### ISSUE TITLE
Resumo da Aula Conectando o Front-end ao Firebase 01-12 da etapa 15

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4516]
Para conectar o frontend ao ao backend do Firebase, primeiro temos que adicionar algumas linhas de código ao html. Se clicarmos em "acessar documentação" >> "noções básicas" >> "adicionar Firebase Web", veremos o passo a passo de como isto pode ser feito. O primeiro passo é registrar a aplicação dentro do projeto no Firebase, para isto, acessando as configurações do projeto clicando no ícone de engrenagem no canto superior esquerdo da página. Aqui, temos as configurações gerais do projeto e a opção para registrar a aplicação, que pode ser um app iOS, Android, Web e/ou Game Unity. Clicamos em aplicações Web (ícone com representação de tags html), que exibe uma página onde inserimos o nome da aplicação, que pode ser o mesmo nome do projeto. Deixamos o checkbox de hoisting Firebase desmarcado e clicamos em "registrar app".

Na página seguinte, temos duas opções para "linkagem" do app ao projeto, que pode ser via npm (gerenciador de pacotes do node) ou tag script. Marcamos a segunda opção para linkar via tag.

Devemos atentar para o versionamento do Firebase, indicado nas linhas de código exibidas na página, pois uma versão diferente ao que a aula utiliza pode gerar quebra de código, por isto, utilizamos o trecho de código indicado no vídeo da presente aula. O link em questão importa features do Firebase e fornece um objeto de configuração, que é o que o conecta ao frontend. A tag `script` tem um atributo `module` que indica que o código no arquivo se trata de um módulo JS, que o código está encapsulado em escopo próprio e pode ser importado entre arquivos JS. 

Indicamos na tag `script` inserida no html que esta é `type="module"` e copiamos dentro dela o script fornecido pelo Firebase (alterando o versionamento), desta forma importamos o SDK para a aplicação. A primeira linha (que contém `import`) está importando o `initializeApp` do SDK Firebase-app.js, o core do Firebase, que é o mínimo necessário para que o Firebase funcione na aplicação e por isso sempre deve ser inicializado antes de qualquer outro serviço do Firebase. A segunda linha importa a função `getAnalytics` e as linhas seguintes comentadas informam ou link onde encontramos os SDKs para as ferramentas que podemos usar.

O objeto que encontramos no código refere-se às configurações do Firebase para a aplicação e, no fim do código, temos as linhas de invocação das funções importadas, para inicialização do Firebase na aplicação.

Para usar o Firestore, acessamos o link indicado no comentário do código, na página deste link temos os serviços disponíveis, entre eles, o Cloud Firestore para Web. Nele, é mostrado como importar o Firestore. No arquivo js, então inserimos:
```js
import { getFirestore } from "https://www.gstatic.com/firebasejs/9.0.1/firebase-firestore.js"
```
Para deixar o código mais limpo, removemos os comentários e também o `import` e invocação do Analytics (não usamos este).

Inserimos uma referência ao banco de dados, armazenando em uma const. O argumento passado na invocação da função é opcional, porém, para ficar mais claro, inserimos. 
```js
const db = getFirestore(app)
```
Toda vez que necessitarmos fazer alguma alteração ou leitura no banco de dados, devemos utilizar esta constante.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery, rumo à fluência! 🎯
