### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4520]
O return serve para retornar um valor e guardar esse valor para um uso posterior mais a frente, o return para ter validade ele precisa estar na ultima linha da function, podemos atribuir um valor no return que estará sendo invocado junto com o que foi solicitado e dando o resultado conforme foi solicitado. Utilizamos o return para obter o valor dentro da função para podermos utilizar este valor do lado de fora dela.

**Comment by Roger-Melo** [comment]
Excelente @EdsonAjjunior, rumo à fluência! 🎯
