### ISSUE TITLE
Resumo da Aula O que são funções - Aula 01-02 da etapa 02

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4521]
Funcoes fazem parte do tipo de dado Object, e sua funcao eh permitir criar um bloco de codigo dentro dela e executa-lo todas as vezes que ela for invocada, podendo ser invocada inumeras vezes.

Para invocar uma funcao e utilizado o comando: nomeDaFuncao( )

Funcoes tambem podem receber, transformar e retornar valores.
A definição da função (também chamada de declaração de função) consiste no uso da palavra chave (function), seguida por:

- Nome da Função.
- Lista de argumentos para a função, entre parênteses e separados por vírgulas.
- Bloco de codigos que  definem a função, entre chaves { }.

Ex:
       function showMessage( ) {
  alert('algum dado')
  }

showMessage( )

**Comment by Roger-Melo** [comment]
Excelente @YukOnRails, rumo à fluência! 🎯
