### ISSUE TITLE
Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by RodrigoRedivo** [roger-melo-treinamentos/curso-de-js-roger-melo#4530]
![js](https://user-images.githubusercontent.com/55354801/182985174-e6aff498-87c9-49a2-87de-b51f230ef0ba.jpg)

# Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

**setAttribute vai sobrescrever os estilos e nao adicionar um novo e isso não é legal.**

portanto podemos usar o style tanto pra remover e adicionar.

Usando style logo abaixo:

```jsx
const title = document.querySelector('h1');

console.log(title.style);
console.log(title.style.color);

title.style.margin = "50px"; // adicionando
title.style.color = "red";
title.style.fontSize = "32px";
title.style.margin = ""; // removendo
```

**Comment by Roger-Melo** [comment]
Excelente @RodrigoRedivo, rumo à fluência! 🎯
