### ISSUE TITLE
Resumo da Aula: Tipos de refêrencia vs Tipos primitivos, Aula 03-04 etapa 04

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4535]
Tipos primitivos são numbers, strings, booleans, null, undefined, bigInt e Symbol,
os referência são todos os objetos, arrays, funções, datas, a diferença está na
forma que se armazena, as variáveis vão pra stack e os objetos pro heap, maior 
espaço e mais lenta. O primitivo armazenado e sua busca é pelo nome da variável, o objeto armazenado, fica no heap, mas um ponteiro que aponta pra esse objeto fica na stack, isso quer dizer que criamos um array por exemplo, com o nome Balas, o array fica no heap e um ponteiro de Balas fica na stack apontando
pra esse objeto. 
Por isso, quando fazemos uma cópia de um valor primitivo, ele cria dois espaços distintos, um não vai afetar o outro. 
Já os referência, vão criar um ponteiro que aponta, quando for copiado, só o ponteiro vai ser duplicado, logo a base será a mesma, se vc modificar qualquer uma das variáveis, vai mudar no heap, mas os ponteiros apontam pro mesmo lugar, portanto os dois serão modificados.

**Comment by Roger-Melo** [comment]
Excelente @Morais465, rumo à fluência! 🎯
