### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by EnricoTomaz** [roger-melo-treinamentos/curso-de-js-roger-melo#4536]
Na aula fala de:

1. Concatenação de strings
   1.2. Como acessar os caracteres de uma string dentro de uma variável (usando colchetes)
2. Fala sobre o comprimento de uma string ( propriedade .length ) 
3. Fala sobre métodos de string
   3.1. Explica a diferença entre método e função: **Uma função** é um pedaço de código que executa alguma ação específica, **já um método** é uma função que está assocciada a um objeto ou tipo de dado em particular. Sempre que eu usar um metodo devo usar parênteses no fim da palavra reservada. Ex.: 
```js
const firstName = "Nathan";
const lastName = "Drake";
const fullName = firstName + " " + lastName;
const result = fullName.toLowerCase();
```
Nota: O que coloca-se dentro do parênteses do método é chamado argumento, e não parâmetro.

**Comment by Roger-Melo** [comment]
Excelente @EnricoTomaz, rumo à fluência! 🎯
