### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by jfjunior86** [roger-melo-treinamentos/curso-de-js-roger-melo#4541]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/jfjunior86/to-do-List-1

### Maiores dificuldades durante a implementação

Travei um pouco na remoção dos itens, nesse momento fiz uma revisão das anotações e consegui resolver o problema.
Não fiquei satisfeito com a refatoração que fiz no código, tenho que revisar melhor essa parte.

### Menores dificuldades durante a implementação

Na busca pelas to-do tive um pouco de dificuldades, mas resolvi não revisar, depois de alguns testes consegui resolver o problema.

**Comment by Roger-Melo** [comment]
Olá @jfjunior86.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @jfjunior86.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ##  Não fiquei satisfeito com a refatoração que fiz no código, tenho que revisar melhor essa parte.

Tenha consciência que refatoração é uma habilidade que vai sendo elevada conforme vc pratica. E vc ainda praticará bastante durante o treinamento e será exposto há vários casos de uso.

Mas o mais importante num primeiro momento vc já fez, que é fazer funcionar. Refatoração vem depois =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

> ## 4 espaços vs 2

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

> ## Code styling

Observando o trecho do código abaixo, percebe que o espaçamento antes do nome da const `VerificaSeExisteAClasseDelete` entre os parênteses do bloco do if está um pouco "desorganizado"?

```js
// antes
const excluiItemClicado = event => {
  const itemClicado = event.target
  const VerificaSeExisteAClasseDelete = Array.from(itemClicado.classList).includes('delete')

  if( VerificaSeExisteAClasseDelete){
    itemClicado.parentElement.remove()
  }    
}
```

Por convenção, recomendo que evite deixar um espaço em branco após os parênteses, ficaria assim:

```js
// depois
const excluiItemClicado = event => {
  const itemClicado = event.target
  const VerificaSeExisteAClasseDelete = Array.from(itemClicado.classList).includes('delete')

  if(VerificaSeExisteAClasseDelete) {
    itemClicado.parentElement.remove()
  }    
}
```

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que você formate manualmente.

Isso vai fazer com que você adote um estilo de escrita de código e seja consistente com esse estilo ao implementar suas aplicações.

---

> ## Indentação

Indentação é um dos pilares de um código mais legível.

Sabendo disso, você pode deixar o código mais fácil de entender ao indentar também a marcação html dentro da template string dentro do bloco do if. Ficaria assim:

```js
// antes
if (InformacoesInseridas) {
containerComItensCadastrados.innerHTML += `
  <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-primary">
  <span>${InformacoesInseridas}</span>
  <i class="far fa-trash-alt delete"></i>
  </li>`
}
```

```js
// depois
if (InformacoesInseridas) {
  containerComItensCadastrados.innerHTML += `
    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-primary">
      <span>${InformacoesInseridas}</span>
      <i class="far fa-trash-alt delete"></i>
    </li>`
}
```

---

> ## A convenção CamelCase

Os nomes das consts `InformacoesInseridas` e `VerificaSeExisteAClasseDelete` não estão na convenção de nomenclatura camel case. A primeira letra da palavra deve ser sempre minúscula e apenas da segunda palavra para a frente é maiúscula. É importante que o código que você escrever em Javascript siga essa convenção para deixar o código mais legível, tanto para você, quanto para outros desenvolvedores que eventualmente poderão ler seus códigos. Veja as duas ocorrências abaixo:

```js
// antes
const InformacoesInseridas = event.target.add.value
    
if (InformacoesInseridas) {
  // ...
}
```

```js
// depois
const informacoesInseridas = event.target.add.value
    
if (informacoesInseridas) {
  // ...
}
```

```js
// antes
const VerificaSeExisteAClasseDelete = Array.from(itemClicado.classList).includes('delete')

if (VerificaSeExisteAClasseDelete) {
  // ...
}    
```

```js
// depois
const verificaSeExisteAClasseDelete = Array.from(itemClicado.classList).includes('delete')

if (verificaSeExisteAClasseDelete) {
  // ...
}    
```

---

> ## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a palavra "formulário" que você usou no código pode ser substituída por "form", assim o código diminui de comprimento e facilita a leitura e escrita.

```js
// antes

const formularioAdicionaTodo = document.querySelector('.form-add-todo')

const formularioDePesquisa = document.querySelector('.form-search')`
```

Você também pode remover o "De" da const `formDePesquisa` pelo mesmos motivos citados acima, o novo nome ficaria como `formPesquisa`.

```js
// depois

const formAdicionaTodo = document.querySelector('.form-add-todo')

const formPesquisa = document.querySelector('.form-search')`
```

Uma outra observação, se fizer sentido para você, talvez seja interessante não usar a palavra item ou sua versão no plural quando se referir aos todos, pois isso pode gerar ambiguidade para quem está lendo. Sabendo disso, na const `containerComItensCadastrados`, prefira nomeá-la por algo como `containerTodosCadastrados`. Ficaria assim:

```js
// antes
const containerComItensCadastrados = document.querySelector('.todos-container')
```

```js
// depois
const containerTodosCadastrados = document.querySelector('.todos-container')
```

A const `verificaSeExisteAClasseDelete` pode ter um nome mais curto e conciso como `classeDeleteExiste`.

Os nomes que você escolheu para as funções também podem ser reduzidos de forma que continuem começando com um verbo e não percam o sentido. Elas podem ser nomeadas da seguinte forma:

- `adicionaItemTodo` pode ser substituída por `adicionaTodo`
- `excluiItemClicado`pode ser substituída por `excluiTodo`
- `filtraItensTodo` pode ser substituída por `pesquisaTodo`
- `adicionaExcluiClasses` pode ser substituída por `mudaVisibilidadeTodos`

Um detalhe adicional para os parâmetros `adicionaClasse` e `excluiClasse` da função `mudaVisibilidadeTodos`. Não faz muito sentido nomear parâmetros com verbos no início sendo que eles não são funções. Prefira substantivos que descrevam o valor armazenado. Por exemplo, ficaria assim:

```js
// antes
const mudaVisibilidadeTodos = (array, adicionaClasse, excluiClasse) => {
  array.forEach(item => {
    item.classList.add(adicionaClasse)
    item.classList.remove(excluiClasse)
  })
}
```

```js
// depois
const mudaVisibilidadeTodos = (array, classeAAdicionar, classeAExcluir) => {
  array.forEach(item => {
    item.classList.add(classeAAdicionar)
    item.classList.remove(classeAExcluir)
  })
}
```

Por fim, algumas observações podem ser feitas para facilitar o entedimento do código e deixá-lo mais exato nos nomes da const `informacoesInseridas` e `itemClicado`. Dentro da função `adicionaTodo`, a const `informacoesInseridas` está recebendo o valor do input digitado, sendo assim, você pode renomeá-la como `valorInput`. Algo semelhante acontece com a const `itemClicado`, ela está recebendo `event.target`, isto é, o elemento que foi clicado, portanto, faz mais sentido que ela receba algo como `elementoClicado`.

```js
// antes
const informacoesInseridas = event.target.add.value

const itemClicado = event.target

```

```js
// depois
const valorInput = event.target.add.value

const elementoClicado = event.target

```

---

## Refatoração

Se você quiser que o código fique mais conciso, uma sugestão é usar `contains` ao invés de `includes` na const `classeDeleteExiste`. Por meio desse método, você não precisa transformar classList em array. Ficaria assim:

```js
// antes
const classeDeleteExiste = Array.from(elementoClicado.classList).includes('delete')
```

```js
// depois
const classeDeleteExiste = elementoClicado.classList.contains('delete')
```

Uma outra sugestão seria, se você achar que faz sentido, usar um `early return` dentro da função `adicionaTodo`. A vantagem do early return é parar a execução da função naquele ponto caso a condição seja falsa, assim não se torna necessário ler a parte do código que vem em seguida. Além disso, usando um `early return`, você não precisa inserir o código da marcação html dentro do bloco do if, reduzindo então o número de indentações para essa marcação e tornando o código mais legível. Veja abaixo: 

```js
const adicionaTodo = event => {
  event.preventDefault()

  const valorInput = event.target.add.value

  if (!valorInput) {
    return
  }
    
  containerTodosCadastrados.innerHTML += `
    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-primary">
      <span>${valorInput}</span>
      <i class="far fa-trash-alt delete"></i>
    </li>`
      
  event.target.reset() 
}
```

Dentro desse if do early return, qualquer coisa pode ser feita, como por exemplo, exibir a mensagem na tela que o texto inserido é invalido. Sempre que possível e sempre que fizer sentido, é preferível usar um early return do que executar uma leitura de código que não necessariamente precisa ser lida =)

Você também pode fazer uma refatoração na função `adicionaTodo` e na `excluiTodo` por meio dos atributos data, em breve você chegará nas aulas sobre esses atributos. Mas para você ter uma ideia, você pode inserir o atributo data-todo na li do todo e colocar seu valor como o mesmo conteúdo da tag de `span`, depois adicionar um outro atributo data-trash no elemento html `i` da lixeira com novamente o mesmo conteúdo de `span`:


```html

<li class="..." data-todo="Fazer exercícios de JS">
  <span>Fazer exercícios de JS</span>
  <i class="..." data-trash="Fazer exercícios de JS"></i>
</li>
            
<li class="..." data-todo="Planejar site">
  <span>Planejar site</span>
  <i class="..." data-trash="Planejar site"></i>
</li>
            
<li class="..." data-todo="Pagar contas">
  <span>Pagar contas</span>
  <i class="..." data-trash="Pagar contas"></i>
</li>
```

Depois, na função `adicionaTodo`, você pode adicionar, dentro da template string, a nova marcação html atualizada com os atributos data. data-trash vai receber o conteúdo textual do todo, que no caso é o `valorInput`. Na li, o data-todo vai receber uma interpolação com o texto do todo do `valorInput`:

```js
const adicionaTodo = event => {
  // ...
  if(valorInput) {
    containerTodosCadastrados.innerHTML += `
      <li class="..." data-todo="${valorInput}">
        <span>${valorInput}</span>
        <i class="..." data-trash="${valorInput}"></i>
      </li>`
  }
  // ... 
}
```

Após inserir os atributos data acima na marcação html, na função `excluiTodo`, vamos usá-los também para fazer uma refatoração no lugar do `parentElement`. Não é bom usar `parentElement`, pois é um design de código que tende a ser frágil. Se futuramente a marcação html dessa aplicação mudar e o `parentElement` não for mais o elemento que você tinha em mente quando escreveu o código, o seu código quebra. O que não acontece quando você usa os atributos data. Por isso, você pode fazer o seguinte:

Você pode criar uma const `lixeiraFoiClicada` que vai receber o valor retornado pelo dataset que contém uma propriedade trash. Ou seja, quando a lixeira for clicada, o valor do atributo data-trash vai ser atribuida para a const `lixeiraFoiClicada`. Ficaria assim:

```js
const excluiTodo = event => {
  const lixeiraFoiClicada = event.target.dataset.trash  

  if (lixeiraFoiClicada) {
    const todo = document.querySelector(`[data-todo="${lixeiraFoiClicada}"]`)
    todo.remove()
  }    
}
```

Ao clicar fora da lixeira, essa const vai armazenar `undefined`, que por ser um valor `falsy`, o if não vai ser executado. Quando a lixeira for clicada, `lixeiraFoiClicada` vai estar armazenando uma string preenchida, e uma string preenchida é um valor `truthy`, assim o if vai ser executado.

Quando o if for executado, você pode criar uma const `todo` que vai conter o todo, ou seja, a li que deve ser removida. Para selecionar essa li, você pode usar os atributos data. O data-todo tem o mesmo valor que data-trash, assim, você vai selecionar a li que contém o texto que `lixeiraFoiClicada` está armazenando, pois tanto data-todo quanto data-trash contém essa string que `lixeiraFoiClicada` está armazenando. Após a const `todo` receber a li que deve ser removida, você pode invocar o método `todo.remove()` para excluir a li escolhida do DOM.

Você irá aprender mais sobre os atributos data e suas particularidades nas próximas aulas do treinamento =)

Vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

É possível criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Eu "desfiz" as funções relacionadas à busca de to-dos e vamos ir codando passo a passo. Você pode declarar uma const `todos` que contenha as lis que representam os todos:

```js
formPesquisa.addEventListener('input', event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children)
})
```

Agora, você pode invocar console.log(todos) e buscar por eles, vai aparecer no console as lis de cada todo.

```js
formPesquisa.addEventListener('input', event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children)

  console.log(todos)
})
```

Agora, sabendo que `todos` precisa armazenar um array de objetos e cada objeto precisa conter uma propriedade `todo` que vai armazenar a li e uma propriedade que vai receber um boolean indicando se esse todo vai ficar vísivel ou não. Se para cada li do array você precisa gerar um objeto e o array gerado vai ter a mesma quantidade de itens que o original, você pode usar o método map. Já que cada item do array ao qual o map está sendo encadeado representa um todo, você pode inserir um parametro `todo` e fazer a função retornar um objeto. A cada execução do callback do map, um objeto vai ser inserido no novo array que o map está gerando. Ênfase que você não pode remover os parênteses após ter declarado uma propriedade, pois caso contrário o Javascript vai interpretar a abertura de chave como bloco da função. Para que o Javascript considere essa abertura e fechamento de chave como um objeto, você vai precisar dsses parênteses conhecidos como grouping operator, eles que fazem com que a precedência dessa expressão seja o objeto literal.

```js
formPesquisa.addEventListener('input', event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children).map(todo => ({
    todo
  }))

  console.log(todos)
})
```

Em seguida, acrescentamos uma propriedade `deveEstarVisivel` que armazena um boolean indicando se o `todo` deve ficar visível ou não. Você pode fazer isso pela expressão `todo.textContent.toLowerCase().includes(valorInput)` em que `todo.textContent.toLowerCase()` retorna o texto do todo em letras minúsculas e nessa string, você está verificando por meio do método `includes()` se ela contém a string da `valorInput`.

```js
formPesquisa.addEventListener('input', event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children).map(todo => ({
    todo,
    deveEstarVisivel: todo.textContent.toLowerCase().includes(valorInput)
  }))
      
  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */
})
```

Tudo certo até aqui?

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma única função `filtraTodos` que manipula as classes dos to-dos, considerando a propriedade `deveEstarVisivel`:

```js
const filtraTodos = todos => {
  todos.forEach(({ todo, deveEstarVisivel }) => {
    todo.classList.add(deveEstarVisivel ? 'd-flex' : 'oculta')
    todo.classList.remove(deveEstarVisivel ? 'oculta' : 'd-flex')
  })
}

formPesquisa.addEventListener('input', event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children).map(todo => ({
    todo,
    deveEstarVisivel: todo.textContent.toLowerCase().includes(valorInput)
  }))
      
  filtraTodos(todos)
})
```

Feito isso, vc pode nomear o callback do listener de evento como `pesquisaTodo`, por exemplo.

Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, pq ao bater o olho no nome da função, a ação que ela executa fica explícita:

```js
const pesquisaTodo = event => {
  const valorInput = event.target.value.trim().toLowerCase()
  const todos = Array.from(containerTodosCadastrados.children).map(todo => ({
    todo,
    deveEstarVisivel: todo.textContent.toLowerCase().includes(valorInput) 
  }))
    
  filterTodos(todos)
}
```

Sacou a ideia?

---

## Considerações finais

Você demonstrou ter entendido bem a lógica até aqui, porém eu notei uma dificuldade em escolher nomes no código da sua aplicação. Eu sugiro que você volte na área que mostrei sobre o princípio de escolher nomes e leia novamente, se possível anote, para que escolher nomes segundo o princípio se torne cada vez mais natural para você, é muito importante que uma aplicação tenha nomes que descrevam bem o que cada parte do código está fazendo =)

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by jfjunior86** [comment]
@MivlaM , obrigado pela analise.

1) 4 espaços vs 2
Já estava pensando em mudar isso mesmo, o Roger até falou sobre isso na correção da outra aplicação.

2) Mudei o nome dessa constante usando o **F2**, para alterar de uma só vez em todos os locais e acabei colocando um espaço sem necessidade.

03) Indentação
Vou ficar mais atendo, realmente faz muita diferença um código bem indentado.

04) A convenção CamelCase
Mudei algumas vezes o nome das variáveis mencionadas, acabei descuidando e não respeitando a convenção `CamelCase`. Quando comecei a ler sua analise, já percebi de cara o erro nessa parte.

05) Nomes de variáveis e funções
Gastei muito tempo tentando melhorar esse ponto. Seguindo o principio que você mencionou, vai ficar bem mais fácil nomear.

06) Refatoração
Vou seguir todas as dicas.

07) Considerações finais
Vou seguir sua sugestão.

**Comment by MivlaM** [comment]
Show! No que precisar, é só abrir uma nova issue =)
