### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4543]
Os parenteses de uma function servem para armazenar parametros, que sao variaveis exclusivas da function em questao e devem ser separados por virgula e espaco.
Esses parametros nao sao obrigatorios e tambem podem ser do tipo "default" [(paramentro1 = "name", parametro2 = "last name")].
Ex:
   const fullName = function (paramentro1 = "name", parametro2 = "last name") {
console.log(`Oi ${parametro1} ${parametro2}`)
}

Na invocacao da funcao os argumentos sao inseridos dentro dos parenteses e devem obrigatoriamente serguir a sequencia os parametros, porem apenas na insercao dos mesmos; dentro da funcao a ordem nao importa.
Ex:
   fullName ('Joao', 'Almeida')

**Comment by Roger-Melo** [comment]
Show @YukOnRails. Vamo que vamo, rumo à fluência! 🙌
