### ISSUE TITLE
Resumo da Aula Lendo dados do Firestore 01-13 da etapa 15

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4557]
Para ler e obter os dados armazenados no Firebase, utilizamos a referência feita a ele por meio da constante `db` e as funções importadas do Firestore. Como em um banco de dados podemos ter vários _collections_, precisamos especificar qual queremos acessar. Na sessão do Firestore, encontramos um tópico da documentação que trata da leitura de dados (Read Data) e nele o tópico "Get data once". Acessando este, veremos no menu lateral direito "Get all documents in a collection", que apresenta o código a ser utilizado para acesso de todos os _documents_ de um _collection_. Este código utiliza funções assíncronas (async/await), que podem ser transformadas para then/catch.

Obtemos a referência de todos os `collections` do banco de dados invocando a função `collection()`. Nela, inserimos dois valores como argumentos, sendo o primeiro a referência ao banco de dados do Firestore (`db`), e o segundo é o nome do `collection` que desejamos consultar, em string. 
```js
collection(db, 'games')
```
No entanto, primeiro devemos importar esta função do SDK do Firestore. Isto pode ser feito alterando a linha na qual importamos o Firestore, adicionando `collection` dentro das chaves. Para importar os `collections`, adicionamos também o `getDocs`, que irá fazer uma consulta no banco e retornar uma _promise_.
```js
import { getFirestore, collection, getDocs } from 'https://www.gstatic.com/firebasejs/9.0.1/firebase-firestore.js'

```
Se inserirmos a invocação de `collection()` como argumento de `getDocs()`, obtemos uma promise, na qual podemos acessar os dados por meio de async/await ou then/catch. O `querySnapshot` é um objeto que faz representação de como o _collection_ está no momento em que o request foi executado. 
```js
getDocs(collection(db, 'games'))
      .then(querySnapshot => {
           console.log(querySnapshot)
})
      .catch(console.log)
```
Para exibir os _documents_, podemos usar o `forEach()`. No entanto, precisamos invocar nele o método `data()` que então irá retornar os `documents`.
```js
getDocs(collection(db, 'games'))
      .then(querySnapshot => {
            querySnapshot.forEach(doc => console.log(doc.data()))
             console.log(querySnapshot)
})
      .catch(console.log)
```
Apesar de o objeto `querySnapshot` possuir um método `forEach()` próprio, uma outra alternativa para obtenção dos _documents_ se faz mais vantajosa, que é acessar a propriedade `docs` diretamente no `querySnapshot` para aí então aplicar o método `forEach()`. Este modo dá mais contexto ao que está sendo feito, pois estamos trabalhando o método `forEach()` (que é um método de array) no array `docs` e não mais diretamente no objeto querySnapshot. Ademais, neste modo também podemos usar qualquer método de array.
```js
querySnapshot.docs.forEach(doc => console.log(doc.data())
```
Para implantar os dados dentro da página HTML, podemos substituir o `forEach()` pelo método `reduce()` e por meio do atributo `acc`, inserir uma template string com as tags que queremos adicionar ao innerHTML do elemento pai, interpoladas com as propriedades que o document contém.
```js
const gamesLis = querySnapshot.docs.reduce((acc, doc) => {
      acc += `<li>${doc.data().title}</li>`
      return acc
    }, '') 
    const gamesList = document.querySelector('[data-js="games-list"]')
    gamesList.innerHTML = gamesLis
    console.log(gamesLis)
```
Propriedades que armazenam tipo data contêm um objeto `Timestamp` que utiliza unidade de nanossegundos para representar o tempo, desta forma, para exibirmos o formato correto, precisamos transformá-lo utilizando um método contido nele, o `toDate()`.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. Vamo que vamo, rumo à fluência! 🙌
