### ISSUE TITLE
Resumo da Aula: Query selector & query selector all, Aula 01-07 etapa 05

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4570]
Usado para buscar um elemento, ou por nome, ou tag, ou id, ou classe, é um novo método perante o getElementBy ! E para buscar um elemento direto na fonte, botão direito em cima do elemento no browser, ir em copy selector e assim é possível uma tag única para ele.

const h1 = document.querySelector('body > h1') console.log(h1).

Com selectorAll pegamos todos os elementos e assim obtemos uma Node List, que é a árvore desses elementos todos. Os métodos de
array como notação de colchetes e forEach funcionam com ele,  e podemos percorrer e iterar sobre eles.

**Comment by Roger-Melo** [comment]
Show @Morais465. Vamo que vamo, rumo à fluência! 🙌
