### ISSUE TITLE
Resumo da Aula 02-02 da etapa 04 - Variáveis e escopo de bloco

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4574]
### Escopo
Quando declaramos uma variável fora de algum bloco de código, essa se torna uma variável global, isso significa que essa variável pode ser acessada em qualquer parte do nosso código e dentro de qualquer bloco de código
```js
let name = 'Diego'

if(name === 'string') {
 console.log(name) // Diego
}

console.log(name) // Diego
```
Se tentarmos declarar uma variavel de escopo global com nome de uma variável já existente e tentarmos reatribuir seu valor um erro será retornado.
```js
let name = 'Diego'

let name = 'Lucas'

if(name === 'string') {
 console.log(name)
}

console.log(name)
```
Mas dentro de um bloco de código podemos criar uma variável com mesmo nome e modificar o seu valor, essa variável apenas poderá  ser acessada dentro do bloco onde foi criada, se tornando assim uma variável de escopo local.
```js
let name = 'Diego'

if(name === 'string') {
 let name = 'Lucas'
 console.log(name) // Lucas
}

console.log(name) // Diego
```

**Comment by Roger-Melo** [comment]
Show @Diegodkid. Vamo que vamo, rumo à fluência! 🙌
