### ISSUE TITLE
Resumo da Aula Arrays - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#458]
**Utilizamos arrays para armazenar listas de objetos.**

* Declaração de variáveis:

```js
let variable_1 = "Valor 1";
let variable_2 = "Valor 2";
let variable_3 = "Valor 3";
let variables = [variable_1,variable_2,variable_3];
``` 

* Podemos acessar qualquer um dos elementos de um array utilizando a notação array[position], para acessar o primeiro elemento no caso do exemplo:

```js
let printVariable = variables[0]// atribuindo à printVariable o valor do primeiro elemento do array variables
console.log(printVariable);// Mostrando o valor de printVariable: Valor 1
``` 

* Arrays possuem propriedades e métodos, alguns dos métodos são:
	* join: Retorna uma string com os elementos do array(que invocou o metodo) separados por vírgula ou por um argumento escolhido.
	```js
		// Método join sem argumento: array.join()
		console.log(variables.join());//Valor 1,Valor 2,Valor 3
	```

	```js
		// Método join com argumento: array.join(argumento)
		console.log(variables.join("|"));//Valor 1|Valor 2|Valor 3
	```
 	* indexOf: Retorna o índice da primeira ocorrência do argumento em questão. Caso o argumento não esteja contido no array, -1 é retornado.

	```js
		// Método indexOf: array.indexOf(argumento)
		console.log(variables.indexOf("Valor 2"));// 1
	```
 	* concat: Retorna um array com os elementos dos dois arrays concatenados.
	```js
		// Método concat: array.concat(otherArray)
		let newVariables = ["Valor 4", "Valor 5"];
		console.log(variables.concat(newVariables));// ["Valor 1", "Valor 2", "Valor 3", "Valor 4", "Valor 5"]
	```
 	* push: Insere o argumento(ou vários se parados por vírgula) como um novo elemento do array ORIGINAL e retorna o novo número de itens desse array| MUTAÇÃO DE VALORES.

	```js
		// Método push : array.push(argumento)
		variables.push("valor 6");
		console.log(variables);// ["Valor 1", "Valor 2", "Valor 3", "valor 6"]
	```

	* pop: Remove o último item do array original(array que invocou o método) e retorna o valor retirado| MUTAÇÃO DE VALORES.
	
	```js
		// Método pop : array.pop()
		variables.pop();
		console.log(variables);// ["Valor 1", "Valor 2", "Valor 3"]
	```
	
	* includes: Retorna *true* ou *false* de acordo com a presença do argumento no array.
	```js
		// Método includes: array.includes(argumento)
		console.log(variables.includes("Valor 1"));// true
		console.log(variables.includes("Valor 19"));// false
	```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ThiagoDeMorais! Rumo à fluência! 🔥
