### ISSUE TITLE
Resumo da Aula Break e continue - Aula 03-03 da etapa 02

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4580]
BREAK
Quando a condição do break é atingida o loop se encerra, isso significa que mesmo havendo mais itens para serem iterados, quando o break é colocado o loop se encerra ali mesmo. Veja o exemplo:

const scores = [50, 25, 0, 30, 100, 20, 10]

for (let i = 0; i < scores.length; i++) {
      console.log(`Sua pontuação foi: ${scores[i]}`)
    
    if (scores[i] === 100){
      console.log('Parabens, você atingiu a pontuação foi maxima!')
    
      break
    }   
  }

Desse modo, nem 20 e nem 10 seriam mostrados no console.

CONTINUE

A continue pula uma iteração em particular e depois continua dando procedência a execução do loop. Veja o exemplo:

const scores = [50, 25, 0, 30, 100, 20, 10]

for (let i = 0; i < scores.length; i++) {
    if (scores[i] === 0) {
      continue
    }
      console.log(`Sua pontuação foi: ${scores[i]}`)
    
    if (scores[i] === 100){
      console.log('Parabens, você atingiu a pontuação foi maxima!')
    
      break
    }
    
  }

No primeiro if, continue fez com que 0 fosse tirado da exceção do loop e os outros números foram iterados normalmente.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
