### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4587]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/AlessandroAscanio/quiz/tree/master

### Maiores dificuldades durante a implementação

Eu precisei rever a aula desenvolvendo um popup porque não estava conseguindo implementar a lógica correta para fazer com que o ele fosse fechado ao clicar no x ou na tela de fundo do popup.

### Menores dificuldades durante a implementação

A captura dos elementos do DOM e a criação do event listener

**Comment by Roger-Melo** [comment]
Olá @AlessandroAscanio.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @AlessandroAscanio.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Eu precisei rever a aula desenvolvendo um popup porque não estava conseguindo implementar a lógica correta para fazer com que o ele fosse fechado ao clicar no x ou na tela de fundo do popup.

Mesmo com a dificuldade relatada, você conseguiu =)

---

## Boas decisões

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que alguns cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Você inseriu uma porcentagem no resultado final, excelente!


Vou deixar abaixo algumas observações sobre sua aplicação.

---

> ## Ortografia

A palavra ''inicio '', usada na terceira pergunta do quiz está ortograficamente incorreta, início seria a versão correta. Além disso, uma sugestão seria usar o ponto de interrogação (?) ao invés do dos dois pontos (:) no final de cada pergunta e antes das alternativas para a resposta. É muito importante que a parte visível do texto das aplicações seja escrita de acordo com a norma ortográfica das palavras. Uma aplicação pode perder integridade, além de talvez causar desconfiança em seus usuários se o que for escrito estiver muito distante do padrão utilizado na língua portuguesa.

---

> ## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Para que sua aplicação tenha uma definição clara onde começa e onde termina cada conceito, procure evitar o excesso ou a falta de linhas em branco no código.

Sabendo disso, você pode adicionar uma linha em branco antes do bloco do if dentro da função `checkAnswers`. Ficaria assim:

```js
// antes
const checkAnswers = (answer,index) => {
  const isAnswerCorrect = answer === correctAnswers[index]
  if(isAnswerCorrect){
    score += 25
  }
}
```

```js
// depois
const checkAnswers = (answer,index) => {
  const isAnswerCorrect = answer === correctAnswers[index]

  if(isAnswerCorrect){
    score += 25
  }
}
```

> ## Parâmetro do callback do forEach

Você pode renomear o parâmetro de callback do `forEach` como `userAnswer` ao invés de `answer`. Acredito que como singular de itens do array no qual o forEach foi encadeado (userAnswers), a leitura do forEach e do if fique mais legível:

```js
//antes
const checkAnswers = (answer,index) => {
  const isAnswerCorrect = answer === correctAnswers[index]

  if(isAnswerCorrect){
    score += 25
  }
}
userAnswers.forEach(checkAnswers)
```

```js
//depois
const checkAnswers = (userAnswer,index) => {
  const isAnswerCorrect = userAnswer === correctAnswers[index]

  if(isAnswerCorrect){
    score += 25
  }
}
userAnswers.forEach(checkAnswers)
```

> ## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, o a const `isAnElementClicked` que você usou no código pode ser substituída por `shouldClosePopup`, pois ela está sendo usada na lógica justamente para a situação em que o popup deve ser fechado. Dessa forma, a leitura e escrita do código se torna mais fácil. Ficaria assim:

```js
// antes
const isAnElementClicked = classNames.some(className =>
  className === classNameClickedElement)
  
  if(isAnElementClicked){
    popup.style.display ='none'
  }
```

```js
// depois
const shouldClosePopup = classNames.some(className =>
  className === classNameClickedElement)
  
  if(shouldClosePopup){
    popup.style.display ='none'
  }
```

Você também pode trocar o nome da const `p` para algo mais exato e descritivo. Se essa const está sendo usada para armazenar o id answer do html, você pode renomea-lá para `answer`. Veja abaixo: 

```js
// antes
const p = document.querySelector('#answer')
```

```js
// depois
const answer = document.querySelector('#answer')
```

Por fim, uma possibilidade de nome mais descritivo para o que acontece quando o form é enviado é `showScore` (ao invés de `handleQuizAnswer`). `showScore` é um nome que deixa mais explícito a ação principal que vai acontecer na aplicação quando a função do addEventListener for executada, isto é, manipular o DOM para mostrar a pontuação. Ficaria assim:

```js
// antes
const handleQuizAnswer = event => {
  // ...
}
form.addEventListener('submit', handleQuizAnswer)
```

```js
// depois
const showScore = event => {
  // ...
}
form.addEventListener('submit', showScore)
```

---

> ## Div do popup

Você percebeu que após enviar o form e depois de aparecer o popup indicando a pontuação que o usuário fez, dependendo de onde é clicado na tela, o popup não necessariamente fecha no primeiro clique? Quando o clique é ao lado de algum dos `<input type="radio"`, ou seja, no mesmo alinhamento, o popup não fecha, o fundo mais escuro não cobre os inputs de alternativa. Porém, quando o clique ocorre fora do alinhamento de qualquer um dos `<input type="radio"`, o popup fecha corretamente. Sabendo disso, existe uma solução para resolver essa inconsistência do local do clique. Ao mover a div do popup para abaixo da div com a classe quiz no código html, essa inconsistência é resolvida e você pode clicar em qualquer lugar da tela que o popup fechará normalmente, faça o teste em sua máquina:

```html
<!-- Antes -->
<div class="intro py-3 bg-warning text-center">
  ...
</div>

<div class="popup-wrapper">
  ...
</div>

<div class="quiz py-4 bg-light">
  ...
</div>
```

```html
<!-- Depois -->
<div class="intro py-3 bg-warning text-center">
  ...
</div>

<div class="quiz py-4 bg-light">
  ...
</div>

<div class="popup-wrapper">
  ...
</div>
```

---

> ## A let score

Não é necessário uma `let score = 0` nem `score = 0` se a `let score` for declarada dentro da função `showScore`.

Observe o seguinte, quando uma `let score = 0` é declarada dentro de uma função, toda vez que a função for invocada, essa let será declarada recebendo 0. Quando essa função termina de ser invocada, o Javascript através de um mecanismo chamado Garbage collection, vai remover da memória todas as lets e consts que ele não for usar mais. No caso da aplicação, observa-se que a `score` só está sendo usada no callback do forEach e na const `answer.textContent`, ambos também dentro da função `showScore`. Sabendo disso, você pode declarar a let `score` dentro da função sem problemas, pois como ela só é usada nesse escopo, o Garbage collection vai remover da memória o valor armazenado por ela quando a função terminar de ser invocada. Numa eventual segunda ou terceira vez que a função `showScore` for invocada, essa `let score = 0` vai funcionar, pois na execução anterior, o valor dela já foi removido da memória, eliminando qualquer possibilidade de colisão com a `let score = 0` declarada na execução anterior, pois esta já vai ter sido removida pelo Garbage collection =). Veja como ficaria o código abaixo:

```js
// antes
let score = 0

const showScore = event => {
  // ... 
  const checkAnswers = (userAnswer,index) => {
    // ...

    if(isAnswerCorrect){
      score += 25
    }
  }
  answer.textContent = `Você acertou ${score}%`  

  score = 0
}
```

```js
// depois
const showScore = event => {
  // ...
  let score = 0
  
  const checkAnswers = (userAnswer,index) => {
    // ...

    if(isAnswerCorrect){
      score += 25
    }
  }
  answer.textContent = `Você acertou ${score}%`  
}
```

---

> ## Refactoring

Se você quiser que o código fique mais simples e usar menos linhas de código, uma sugestão é usar `includes` ao invés de `some` na const `shouldClosePopup`. Por meio desse método, você pode verificar se as classes armazenadas pelo array `classNames` estão incluídas na const `classNameClickedElement`. Ficaria assim:

```js
// antes
const shouldClosePopup = classNames.some(className => className === classNameClickedElement)
```

```js
// depois
const shouldClosePopup = classNames.includes(classNameClickedElement)
```

Uma outra sugestão seria, se você achar que faz sentido, fazer um destructuring ao invés de usar a sintaxe de colchetes na const `classNameClickedElement`. Você pode tornar o código mais legível ao usar uma abordagem envolvendo o destructuring. Na const `classNameClickedElement`, a sintaxe de colchetes está sendo usada para pegar o primeiro elemento do array ao clicar em qualquer lugar na tela. Isso também pode ser feito por meio do destructuring. Ao envolver por colchetes a const `classNameClickedElement`, você está colocando-a na primeira posição no destructuring de array, ou seja, o primeiro item do array vai para a essa const, pois ela se torna o primeiro item do destructuring. Ficaria assim: 

```js
// antes
const classNameClickedElement = event.target.classList[0]

```

```js
// depois
const [classNameClickedElement] = event.target.classList

```

Feito esses ajustes, vou te mostrar duas abordagens de refactoring usando métodos que você vai encontrar em breve nas aulas seguintes, ambos serão explicados com detalhes futuramente. O que quero que você entenda, nesse primeiro momento, é o conceito por trás deles. Sabendo disso, observe o código abaixo:

```js
const checkAnswers = (userAnswer,index) => {
  const isAnswerCorrect = userAnswer === correctAnswers[index]

  if(isAnswerCorrect){
    score += 25
  }
}
userAnswers.forEach(checkAnswers)
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, `userAnswers` servirá como um default parameter que vai receber um array vazio de `userAnswers`. Por esse momento, vamos manter a lógica que você usou na const `checkAnswers` dentro dessa nova função:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
    score += 25
    }
  })
}
```

Depois, a let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 25 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
      return accumulator + 25
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 25, que na primeira execução será (0 + 25). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 25, na segunda execução o parâmetro `accumulator` estará armazenando 25 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 25 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator, 0)
```

Por fim, você pode invocar a função `getScore()` dentro da função `showScore` recebendo o array armazenado por `userAnswers` como argumento.

```js
const showScore = event => {
  // ...
  const finalScore = getScore(userAnswers)
 // ...
}
```

Legibilidade em funcionalidades que a gente ainda não conhece na linguagem pode ser algo um pouco complicado no começo, porém quanto mais você praticar, mais você vai se acostumar com esse tipo de código declarativo. Percebe-se que a função foi resumida em apenas duas linhas =)

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. userAnswers vai receber um array vazio que será preenchido após percorrermos cada item dentro do array correctAnswers por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Lembre-se da ideia de que quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. A cada execução desse callback, o valor que a função está retornando vai ser inserido nesse novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, você pode invocar a função dentro da função `showScore` que o código funcionará normalmente =)

```js
const showScore = event => {
  event.preventDefault()
  
  const userAnswers = getUserAnswers()
  const finalScore = getScore(userAnswers)
  
  popup.style.display = 'block'
  answer.textContent = `Você acertou ${finalScore}%`  
}
```

Por meio de um código declarativo, como foi mostrado nas duas últimas abordagens, sua aplicação vai tender a ter menos bugs, e com menos bugs ela será mais fácil de manter. Entendeu a ideia?

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

**Comment by AlessandroAscanio** [comment]
Olá @MivlaM muito obrigado pelo retorno com a análise detalhada do código! Todas as observações fizeram total sentido eu acompanhei passo a passo com o meu código efetuando as devidas alterações, e com certeza irão me ajudar a ficar mais atento aos pontos que foram observados para que eu possa criar códigos de forma declarativa e mais legíveis.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
