### ISSUE TITLE
Resumo da Aula mais eventos do DOM - Aula 04-03 da etapa 05

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#4593]
## Mais eventos do DOM 

Copy -> Acontece quando selecionamos um texto e copiamos.  
```js
Const paragraph = document.querySelector(‘.copy-me’) 

paragraph.addEventListener('copy', (event)=> { 
    console.log(event) 
}) 
```
Mousemove -> O evento é disparado quando o mouse é movido sobre a área determinada. Nesse exemplo a div é a área do disparo do evento. 
```js
const div = document.querySelector('.box') 

div.addEventListener('mousemove', (event)=> { 
    box.innerHTML = `${event.offsetX} | ${event.offsetY}` 
}) 
```
As propriedades do objeto event, offsetX e offsetY, representam os valores em pixel de onde o mouse se encontra, no plano horizontal e vertical respectivamente. Essa contagem é feita a partir do canto superior esquerdo do container. 

Wheel-> O evento é disparado quando é feito a rolagem da página através do botão scroll do mouse. O evento é colocado no document. 
```js
document.addEventListener('wheel', (event)=> { 
    console.log(event.pageX, event.pageY) 
})  
```
As propriedades pageX e pageY são similares as propriedades offsetX e offsetY,  mas os valores são relativos a toda página.

**Comment by Roger-Melo** [comment]
Boa @MarioFilho1, rumo à fluência! 🔥
