### ISSUE TITLE
Etapa 03 - Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by Mateus20Barros** [roger-melo-treinamentos/curso-de-js-roger-melo#46]
Olá Roger, 

em relação a este exercicio onde vc coloca arr = [], poderia ser qualquer outro metodo como 'a', 'b' e etc. ou em temos que especificar o tipo de metodo?

const millennialWords = [
'lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail'
]

const def = function(arr = []) {
  let newArr = []

  for (let x = 0; x < arr.length; x++) {
    let wordUpper = arr[x].toUpperCase()

    newArr.push(wordUpper)
  }

  return newArr
}
log(def(millennialWords))

**Comment by Roger-Melo** [comment]
Oi Mateus.

Só uma dica rápida - quando abrir a issue, coloque o nome da aula e da etapa (como está pedindo no título da issue).

É só copiar o nome da aula que está na plataforma ou no título do vídeo e . Exemplo: **Etapa 3, Correção dos exercícios da aula 01 - Aula 02-01**

Assim fica mais fácil eu encontrar a aula aqui, ver o que expliquei e entender sua dúvida de acordo com o momento em que você está no curso, beleza?

---

Você não perguntou, mas evite esse tipo de nomenclatura ao escrever código JavaScript.

```javascript
const def
```

Esqueça a forma com que outras linguagens definem funções. Não faz sentido nomear uma função como `def`. Durante as aulas, fique atento à forma como nomeio as funções. A maioria será nomeada com verbos que deixam explícitos uma intenção.

---

> em relação a este exercicio onde vc coloca arr = [], poderia ser qualquer outro metodo como 'a', 'b' e etc. ou em temos que especificar o tipo de metodo?

Não entendi a pergunta.

Na expressão `arr = []`, um parâmetro `arr` armazena um array vazio como valor padrão.

O valor que `arr` armazena pode ser qualquer tipo. String, boolean, objeto...

O que você quis dizer com "método"?

**Comment by Mateus20Barros** [comment]
escrevi errado e 'argumento', pois o argumento arr = [], poderia ser qualquer outro argumento por exemplo: a, b, c etc, sempre e preciso passar os colchetes [] para definir um argumento como um array? ou simplesmente colocar o arr como argumento da função sem os colchetes?

**Comment by Roger-Melo** [comment]
Oi Mateus.

Passando rapidinho apenas para dizer que li a issue.

Estou sem meu computador hoje. Tive que enviá-lo para a assistência técnica para limparem a poeira interna da CPU e gabinete. Havia um certo tempo que não fazia isso.

Amanhã devo pegá-lo de volta e lhe responderei com calma, combinado? =)

**Comment by Mateus20Barros** [comment]
blz... =)

**Comment by Roger-Melo** [comment]
Oi Mateus.

Um imprevisto aconteceu e ainda não peguei o computador hoje.

Amanhã, assim que eu pegá-lo, responderei a sua dúvida. Tentei começar a respondê-la pelo celular mas não dá. É inviável. Amanhã respondo da forma ideal, combinado?

**Comment by Roger-Melo** [comment]
Oi Mateus. Vamos lá! =D

> sempre e preciso passar os colchetes [] para definir um argumento como um array?

Você **_não precisa_** sempre passar os colchetes para definir um argumento como um array.

Diferente de linguagens como o Java, o JavaScript é uma linguagem de tipagem dinâmica. Isso significa que quando você declara um parâmetro, não precisa "definir" qual tipo de valor o parâmetro receberá.

Quando declaramos uma função, da forma abaixo:

```javascript
const myFunc = function (param) {
  // ...
}
```

`myFunc` é uma função que tem um parâmetro `param` que recebe qualquer valor que a invocação da função receber como argumento:

```javascript
myFunc('string') // param recebeu 'string'
```

No código acima, o parâmetro "param" recebeu 'string', mas a invocação da função poderia ter recebido qualquer outro valor por argumento (boolean, objeto, array, etc).

---

É importante diferenciar o que é **parâmetro** e o que é **argumento**. Parâmetro é a variável especificada **na declaração da função**. Argumento é o valor inserido **na invocação da função**.

Para evitar que o parâmetro da função receba `undefined` (se a função for invocada sem um valor como argumento), logo após o nome do parâmetro eu especifico um valor padrão para o parâmetro:

```javascript
const myFunc = function (param = 'qualquer valor') {
  // ...
}
```

O que eu fiz acima não tem a ver com definir o tipo de dado que o parâmetro vai receber. Eu só estou fazendo o parâmetro `param` receber um valor padrão. **_Isso não significa_** que se eu invocar `myFunc([1, 2, 3])` um erro será lançado. `param` pode receber qualquer valor:

```javascript
const myFunc = function (param = 'qualquer valor') {
  console.log(param)
}

myFunc([1, 2, 3]) // [1, 2, 3]
```

[Nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/745804), eu disse que todas as vezes que um valor não é atribuído para uma variável e usamos ela, o JavaScript automaticamente atribui `undefined` pra essa variável. Lembrando que parâmetros são variáveis.

Quando eu especifico `param = 'qualquer valor'`, eu estou dizendo que caso a função seja invocada sem argumento, ao invés do `param` receber `undefined`, ele receberá a string `'qualquer valor'`:

```javascript
const myFunc = function (param = 'qualquer valor') {
  console.log(param)
}

myFunc() // 'qualquer valor'
```

Se eu remover o default parameter `'qualquer valor'` e invocar a função sem passar argumento, `param` recebe `undefined`:

```javascript
const myFunc = function (param) {
  console.log(param)
}

myFunc() // undefined
```

Ficou mais claro?

**Comment by Roger-Melo** [comment]
Oi Mateus. Espero que a dúvida tenha sido esclarecida. Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
