### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#460]
Nesta aula foi visto mais afundo sobre o tipo de dados **String**. 

String é uma sequência de caracteres. Para apresentar uma string ou atribuir a uma variável, ela deve estar entre ' ' ou " ".

```js
console.log('Hello, World');

const email = 'leon@rogermelo.com';
console.log(email);
```

**Concatenação de Strings**

Para concatenar basta usar o **+**:
```js
const firstName = 'Nathan';
const lastName = 'Drake';
const fullName = firstName + ' ' + lastName;
```

**Acessando o comprimento de uma string**

Basta usar a propriedade length precedidade por ponto ( . ):
```js
console.log('fullName.length');
```

**Métodos de String**

Servem para desempenhar determinada função (lembrando que método é diferente de função), porém diferentemente da propriedade, o método terá () no final, podendo ou não ser preciso inserir algum argumento entre os parênteses:
```js
console.log(fullName.toUpperCase());

const result = fullName.toLowerCase();
console.log(result);
```
Os métodos acima não alteram a string.

Outro método é o **indexOf()**, este busca em qual posição da string está o caracter que foi passado como argumento. Lembre-se que como o método irá procurar uma string então ela deve estar entre aspas simples ou duplas:
```js
const index = email.indexOf('@');
console.log(index);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @rohyer. Rumo à fluência! 👊🏻
