### ISSUE TITLE
Resumo da Aula While loop e exercicios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by felipegueller** [roger-melo-treinamentos/curso-de-js-roger-melo#4606]
# While loop ➿ 

> Executa um bloco de código enquanto sua condição é `true`, na primeira vez que a condição for `false`, o looping é imediatamente interrompido.

## Condição 

É avaliada antes de cada execução do loop, se for verdadeira, o loop é executado, caso seja falsa, o loop é interrompido.

## Bloco de código 

Executado sempre que o loop for `true`.

## Estrutura do While

``` js 
  let contador = true

while (contador) {
  contador = false // na próxima verificação da expressão, o loop é interrompido
}
```

## Exemplo: 

```js
// Show the names using the while loop

const names = ['João', 'Maria', 'José']
let index = 0

while (index < names.length) {
  console.log(names[index])
  index++
}
```

![image](https://user-images.githubusercontent.com/35064154/183731870-4ca36a5a-b28b-4cbd-957a-07693096652c.png)

**Comment by Roger-Melo** [comment]
Boa @felipegueller, rumo à fluência! 🔥
