### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4612]
CALLBACK e uma funcao passada para outra funcao como argumento e invocada dentro da funcao externa para executar uma rotina ou acao.
Ex:

function greetings (name) {
   alert('Ola ' + name)
}

function processUserInput (callback) {
   var name = prompt('por favor insira seu nome')
   callback(name)
}

processUserInput(greetings)
...................................................................................

forEach( )   e um metodo semelhante ao  FOR LOOP que pode ter seu argumento desacoplado para uma melhor sintaxe.
Ele tambem pode receber TRES paramentros sendo eles: (o primeiro item da iteracao, o index e o array) nesta ordem; sendo apenas um argumento obrigatorio, o primeiro item da iteracao.

**Comment by Roger-Melo** [comment]
Boa @YukOnRails, rumo à fluência! 🔥
