### ISSUE TITLE
Resumo da Aula Operadores lógicos && e | | - Aula 02-04

### ISSUE THREAD

**Issue by LeandroAzevedo-1** [roger-melo-treinamentos/curso-de-js-roger-melo#4620]
*   Operadores lógicos - "OU" || e "E" &&
    Operador && quando comprado uma condição verdadeira. 
    Operador | | quando so 1 e verdadeira a condição e executada.

const password = 'oi1dr'

if(password.length >= 12 && password.includes('1')) {
    console.log(`Senha muito forte `)
} else if (password.length >= 8 || password.includes('1') && password.length >= 5 ) {
    console.log(`Essa senha tem 8 ou mais caracteres`)
}else {
    console.log(`A senha deve conter 8 ou mais caracteres`)
}

**Comment by Roger-Melo** [comment]
Boa @LeandroAzevedo-1, rumo à fluência! 🔥
