### ISSUE TITLE
Resumo da Aula 03-02 da etapa 04 - Objetos em arrays

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4622]
### Objetos em arrays
É possivel trabalhar com objetos dentro de arrays:
```js
let person = [
 { name: 'Diego', age: 25},
 { name: 'Lucas', age: 23}
]
```
se precisarmos iteirar sobre os itens do array, cada iteração nos retornara um objeto, onde podemos acessar as propriedades e valores associados a elas.

**Comment by Roger-Melo** [comment]
Boa @Diegodkid , rumo à fluência! 🔥
