### ISSUE TITLE
Resumo da Aula Booleans e comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4623]
Qualquer objeto cujo o valor não é undefined ou null, incluindo um objeto Boolean que o valor seja false, 
é avaliado para true quando passa por uma declaração condicional. 
Por exemplo, a condição a seguir if a declaração é avaliada como true:

```js
const convertToBoolean = new Boolean(false);
if (convertToBoolean) {
  console.log(convertToBoolean)
}

```

Esse comportamento não se aplica aos primitivos Boolean. Por exemplo, a condição a seguir if a declaração é avaliada como false:

```js
const isTrue = false;
if (isTrue) {
  console.log(isTrue)
}
```

Não use um objeto Boolean para converter um valor não-boleano para um valor boleano. Ao invés disso use Boolean como uma função para executar essa tarefa:

```js
let x = Boolean(expression);     // preferido
x = new Boolean(expression); // não use

```

Se você especificar qualquer objeto, incluindo um objeto Boolean cujo valor é false, como valor inicial de um objeto Boolean,
o novo objeto Boolean terá o valor de true.

```js
const myFalse = new Boolean(false);   // valor inicial false
const g = new Boolean(myFalse);       // valor inicial true
const myString = new String('Hello'); // objeto String
const s = new Boolean(myString);      // valo
```

Obs: Não use um objeto Boolean no lugar de um primitivo Boolean.

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano  rumo à fluência! 🔥
