### ISSUE TITLE
queria entender melhor

### ISSUE THREAD

**Issue by joshuapalucci** [roger-melo-treinamentos/curso-de-js-roger-melo#4631]
### Etapa da aula

2

### Nome da aula

aula 2-1

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/771837

### Descreva a dúvida

Se você precisar adicionar trechos de código, coloque-os entre 3 crases, assim:

```
const  números  =  [ '91' ,  '5' ,  '30' ,  '97' ,  '83' ,  '31' ]

let number = 0

for (let i = 0; i < números.length; i++) {
 number += Number(números[i])
    
}
console.log(number === 337)
```

Colocando 3 crases antes e 3 crases depois, o código bloco de código será 
formatado corretamente. O "js" ali em cima é para que o código seja 
colorizado com base em JavaScript. 

Se precisar usar HTML ou CSS, basta substituir "js" pelo nome da 
linguagem. 

Antes de publicar a issue, lembre-se de clicar na aba "Preview", para visualizar se a formatação está correta.

Quanto mais específico você for, mais fácil será ajudá-lo(a) =)

Eu nao consegui entender muito bem como o loop esta funcionando ai sendo que nao esta tendo nenhuma operação matematica, eu vejo da seguinte forma, ele esta percorrendo o array e somando os numeros de acordo com a let i

@Roger-Melo

**Comment by MivlaM** [comment]
Show @joshuapalucci! =)

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

Mas antes disso, eu procurei pelo seu nome na lista de alunos mas não encontrei. Com qual email vc se cadastrou no CJRM? Se não quiser falar por aqui, pode mandar um email para [oi@rogermelo.com.br](mailto:oi@rogermelo.com.br)
