### ISSUE TITLE
Resumo da Aula desenvolvendo um popup - Aula 04-04 da etapa 05

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#4636]
## Método de array some 

Itera pelo array e verifica se pelo menos um item do array atende a condição especificada dentro do método 
```js
Const classNameOfClickedElement = event.target.classList[0] 

Const classNames = [‘popup-close’, ‘popup-link’, popup-wrapper]  

Const shouldClosePopup = classNames.some(className=> className === classNameOfClickedElement 
```
Como argumento do some é inserido uma função, dentro dela é colocado o item className que representa cada item do array iterado. Além disso a função irá a comparação entre o item do array e o conteúdo da variável  classNameOfClickedElement. 

Se pelo menos um item atender a condição o some retorna true, senão retorna false.

**Comment by Roger-Melo** [comment]
Show @MarioFilho1. Vamo que vamo, rumo à fluência! 🙌
