### ISSUE TITLE
Resumo da Aula 03-03 da etapa 04 - O objeto Math

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4638]
### O objeto Math
Ao trabalharmos com o objeto Math temos acesso a diversos métodos e propriedades, aqui deixarei alguns métodos de arredondamento, mais existem muitos outros que são uteis para outros objetivos.

Se precisarmos arredondar um numero podemos utilizar o Math.round
```js
let number = 5.5

console.log(Math.round(number)) // 6
```
aqui ele arredonda para cima pois leva em consideração o valor do decimal, se for entre .5 ou maior, se fosse .4 ou menor seria arredondado para baixo.

Temos o Math.floor
```js
let number = 5.5

console.log(Math.floor(number)) // 5
```
Independente do valor do decimal será arredondado para baixo

Math.ceil
```js
let number = 5.3

console.log(Math.ceil(number)) // 6
```
Independente do valor do decimal será arredondado para cima

Math.trunc
```js
let number = 5.3

console.log(Math.trunc(number)) // 5
```
Utilizado para remover as casas decimais

**Comment by Roger-Melo** [comment]
Show @Diegodkid. Vamo que vamo, rumo à fluência! 🙌
