### ISSUE TITLE
Etapa 02, Correção do exercício da aula 01 Aula 02-01

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#464]
No exercício 05 eu fiz da forma do código inserido aqui.
Eu vendo a resolução entendi que tem que criar a variável fora do bloco do for devido ao escopo só que minha dúvida é que o código até funcionou como pedido no enunciado, até mesmo usando document.write.
Só que colocando o console.log fora do bloco somente retornou o último elemento do array por que isso aconteceu ?
```js
const names = ['João Grilo', 'Chicó', 'Rosinha']


for (let i = 0; i < names.length; i++) {
  HTMLTemplate = `<li>${names[i]}</li>`  
 
console.log(HTMLTemplate)
}
```

@Roger-Melo

**Comment by davidtheblane** [comment]
Fala @Mlluiz39 não sou o professor mas gostaria de ajudar, nessa meu amigo você tem que iniciar a variável HTMLTemplate  declarando ela fora do bloco, abaixo do array names...  assim:
```
let HTMLTemplate = "";
```

e dentro do bloco você tem que usar o sinal "+=" para concatenar conforme o "for" iterar o array, assim:
```
HTMLTemplate += `<li>${names[i]}</li>`
```

ai você receberá esse resultado:
![image](https://user-images.githubusercontent.com/42559009/114788519-fc90dd80-9d57-11eb-8599-b331f9ab14d4.png)

**Comment by Mlluiz39** [comment]
Boa noite ! Davidtheblane
A respeito da declaração da variável eu até entendi e fiz desta forma depois de ver a resolução, o que eu queria entender é que dá forma que eu tinha feito no início só retornava o último item do elemento.

**Comment by Roger-Melo** [comment]
Olá Marcelo.

Você está em dúvida do motivo da `HTMLTemplate` receber `<li>Rosinha</li>` no código abaixo?

```javascript
const names = ['João Grilo', 'Chicó', 'Rosinha']

for (let i = 0; i < names.length; i++) {
  let HTMLTemplate = `<li>${names[i]}</li>`
  console.log(HTMLTemplate)
}
```

Isso aconteceu por que o sinal de atribuição (`=`) está sendo usado. Neste caso, tanto faz declarar a let dentro ou fora do for.

Isso significa que a cada execução do for, a let está sofrendo uma **reatribuição de valor**.

Vou colocar isso em uma tabela para você ter uma panorama geral do que está acontecendo ao usar o sinal de atribuição:

Execuções do for | valor no qual names[i] resultou | valor da HTMLTemplate
:-- | :-: | :-:
1ª execução | João Grilo | `<li>João Grilo</li>`
2ª execução | Chicó | `<li>Chicó</li>`
3ª execução | Rosinha | `<li>Rosinha</li>`

Ou seja, à cada execução do for, o valor que `HTMLTemplate` recebe é **sobrescrito** várias vezes até chegar em `<li>Rosinha</li>` (por que 'Rosinha ' é o último item do array).

Isso é o mesmo que declarar uma `let` e depois reatribuir novos valores à ela:

```javascript
let myLet = 'value'

// myLet recebe 'new value'
myLet = 'new value'

console.log(myLet) // 'new value'

// myLet recebe 'new value 2'
myLet = 'new value 2'

console.log(myLet) // 'new value 2'

// myLet recebe 'new value 3'
myLet = 'new value 3'

console.log(myLet) // 'new value 3'

// ☝️ isso é o que está acontecendo à cada execução do for
```

Agora, observe que se eu trocar o operador de atribuição pelo addition assignment (`+=`), ao invés de sobrescrever o valor de `myLet`, como estamos lidando com strings, a string que `myLet` armazena é concatenada à nova string que ela está recebendo:

```javascript
let myLet = 'value'

// concatena 'value' com 'new value'
myLet += 'new value'

console.log(myLet) // 'valuenew value'

// concatena 'valuenew value' com 'new value 2'
myLet += 'new value 2'

console.log(myLet) // 'valuenew valuenew value 2'

// concatena 'valuenew valuenew value 2' com 'new value 3'
myLet += 'new value 3'

console.log(myLet) // 'valuenew valuenew value 2new value 3'
```

Uma dica: sempre inicie suas variáveis/constantes usando os identificadores `const` ou `let`. Você irá descobrir o motivo disso nas etapas seguintes =)

Respondi a dúvida?

@Mlluiz39

---

Ps: obrigado pela contribuição, @davidtheblane 🙏

**Comment by Mlluiz39** [comment]
Roger Melo muito obrigado consegui entender pq só retornava o último elemento, já tinha visto o addition assignment (+=) porém neste exercício e sua explicação ficou muito nítido o uso do mesmo.
PS' estou extremamente satisfeito com a aquisição do treinamento, tem alguns exercícios que não estou conseguindo fazer igual ao seu mas 70% está garantido, vou me esforçar para chegar pelo menos nós 90% obrigado.

**Comment by Roger-Melo** [comment]
Legal @Mlluiz39. 

[Esses passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) são a forma mais eficiente que conheço de aprender com os erros e fazer seu cérebro se acostumar com soluções mais complexas. É o que eu faço e funciona muito bem.

E claro, quando surgir alguma dúvida, é só abrir uma issue que te ajudo =)
