### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4641]
Para adicionar metodos dentro de objetos basta atribuir uma funcao a uma propriedade e para invoca-la e necessario referenciar o objeto e acessar o metodo atraves da notacao de ponto, e como se trata de uma funcao parenteses no final.
Ex:
const umObjeto = {
   login: function ( ) {
      console.log('usuario logado.')
   }
}

umObjeto.login( )

**Comment by Roger-Melo** [comment]
Show @YukOnRails. Vamo que vamo, rumo à fluência! 🙌
