### ISSUE TITLE
Resumo da Aula Null e Undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by gustavo-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#4643]
### Null e Undefined
``` undefined ``` é um valor atribuído automaticamente pelo JS quando uma variável ainda n tem valor
#### Ex:
```js
let nome
// caso for feito um cosole.log() dessa variável o valor exibido será  undefined 
```

O ```null``` por outro lado é aconselhado ser atribuído manualmente

#### Ex:
```js
let nome = null

// nesse caso a variável contem um valor porem o mesmo é nulo
```

**Comment by Roger-Melo** [comment]
Show @gustavo-viana. Vamo que vamo, rumo à fluência! 🙌
