### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4656]
O forEach significa para cada, é um método que itera sobre o array, sobre cada item executando uma função, tem a mesma essência do for, porem deixa os códigos mais organizados. Normalmente sempre acompanhado com uma função de callback(função de callback são funções que utilizamos como argumentos de outra função) e iterar sobre o array. Lembrando que esse método itera sobre cada item, item por item, e tem uma vantagem a função pode ser desacoplada e armazenada em outro local para deixar o código mais legível e organizado para melhor compreensão.

**Comment by Roger-Melo** [comment]
Show @EdsonAjjunior. Vamo que vamo, rumo à fluência! 🙌
