### ISSUE TITLE
Resumo da Aula Encadeando métodos - Aula 02-03 da etapa 08

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4670]
É possível encadear métodos se o resultado do primeiro for aceito pelo próximo, exemplo: ao utilizar o método filter o retorno dele é um array, logo o próximo método precisa ser um compatível com array como por exemplo map().

```js
const books =[
{name: ‘O código limpo’, price: 30},
{name: ‘O milagre do amanhã’, price: 5},
{name: ‘Alice no país das maravilhas’, price: 10},
{name: ‘Quem pensa enriquece’, price: 50},
{name: ‘O livro da ciência’, price: 40},
]

const booksOnSale = books
  .filter(({price}) => price > 20)
  .map(({name, price}) =>`o preço do livro ”${name}” caiu para ${price} reais`)
```

No exemplo acima o filter esta gerando um novo array com os livros contendo preço superior a 20 reais, em seguida o map está pegando este array filtrado e criando um novo array de string com a informação do nome do livro e o preço em promoção.

**Comment by Roger-Melo** [comment]
Show @AlessandroAscanio Vamo que vamo, rumo à fluência! 🙌
