### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4674]
Em alguns casos será necessário que a função retorne um valor sem que esse valor seja exibido no console, esse resultado ou variável poderá ser armazenado e usado para algum outro momento.

const double = function (number) {
        return  number * 2        
}

double(3)

Até aqui, escrever toda essa função ou apenas escrever 6 pouco tem diferença, nada irá aparecer no console, contudo podemos colocar essa função double dentro de uma const para que possamos vê-la como no exemplo abaixo:

const doubleResult = double(3)

console.log(doubleResult)

Colocando a função dentro de uma const e aplicando um console com essa const, possibilita ver o valor da função fora de seu bloco.

Depois disso é possível usar uma função em outras funções, exemplo:

const showResult = function (value) {
    return `O resultado é: ${value}`
}

showResult()

const grandeResult = showResult( )

console.log (showResult (double (3) ) )

**Comment by Roger-Melo** [comment]
Show @Hugones45. Vamo que vamo, rumo à fluência! 🙌
