### ISSUE TITLE
Resumo da Aula Break e continue - Aula 03-03

### ISSUE THREAD

**Issue by LeandroAzevedo-1** [roger-melo-treinamentos/curso-de-js-roger-melo#4676]
- break 
- continue 

const scores = [ 50, 25, 0, 30, 100, 20, 10]

for( let i = 0; i < scores.length; i++) {
   
       *  continue ...  Quando o jogador fizer zero pontos, a iteiração vai continuar, mas não mostra o 0. 
       
 
   if (scores[i] === 0) {
    // console.log(`Você não marou nenhum ponto. `)
    continue
   }

    console.log(`sua pontuação: ${scores[i]}`)

    if (scores[i] === 100) {
        console.log(`Parabéns você atinjiu a pontuação máxima`)
        
        break 
     
           *  A inteiração vai para quando encontar o valor (100). Para a execução do loop.
            
     
    }
}

**Comment by Roger-Melo** [comment]
Show @LeandroAzevedo-1. Vamo que vamo, rumo à fluência! 🙌
