### ISSUE TITLE
Resumo da Aula 03-03 da etapa 05 - Eventos de clique

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4686]
Através do método addEventListener podemos adicionar interações em nossa pagina quando um determinado evento acontecer.
```js
const button = document.querySelector('button')

button.addEventListener('click', () => {
 console.log('ola');
}
```
O método addEventListener fica ouvindo esperando que um evento aconteça para executar uma ação, como primeiro parâmetro especificamos o tipo de evento que queremos ouvir, neste caso é um evento de click, o segundo parametro é uma função de callback que será executada quando o evento acontecer.
```js
button.addEventListener('click', event => {
 console.log(event);
}
```
Essa função de callback nos da acesso ao parâmetro event que ao ser investigado no console nos fornece varias informações sobre o evento que esta acontecendo

**Comment by Roger-Melo** [comment]
Show @Diegodkid. Vamo que vamo, rumo à fluência! 🙌
