### ISSUE TITLE
Resumo da Aula 03-04 da etapa 05 - Criando e removendo elementos do DOM

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4694]
Podemos criar elementos no DOM com o método createElement
```js
const ul = document.querySelector('ul')

const li = document.createElement('li')
```
e como parâmetro desse método passamos a tag que queremos criar no html
```js
ul.append(li)
```
apos a criação do elemento que desejemos podemos inserir essa li dentro de uma ul, com o método append adicionamos a li criada como ultimo elemento.
```js
ul.innerHTML = ''
```
caso seja necessário remover um elemento podemos utilizar o innerHTML e atribuirmos uma string vazia, assim tudo o que existe dentro dessa ul terá o seu valor atualizado para essa string vazia

**Comment by Roger-Melo** [comment]
Show @Diegodkid. Vamo que vamo, rumo à fluência! 🙌
