### ISSUE TITLE
Etapa 7, Exercícios da aula 01 - Quiz interativo

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#47]
- **O link da sua versão do quiz:** https://github.com/sou-gabriel/quiz-interativo;
- **Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício:** 
  - Escolha de nomes para variáveis/constantes;
  - Lidar com as diversas gamas de componentes que o Bootstrap fornece (foi meu primeiro contato com o framework), porém nada que me atrapalhasse;

- Quais foram as suas menores dificuldades durante a execução desse exercício: 
  - Implementação do código JavaScript e a lógica por detrás da aplicação;
  - Refatoração.

**Comment by Roger-Melo** [comment]
Oi Gabriel!

Que bom que está conseguindo implementar e entender a lógica =D

Vou deixar algumas dicas abaixo, ok?

No título do quiz, você pode trocar o "a" de `a qual linguagem` por "em".

Observe que na declaração da função abaixo,

```javascript
const removeParagraphScore = event => {
  const paragraphShowScoreExists = document
    .querySelector('[data-questions="input-change"]')

  if (paragraphShowScoreExists) {
    paragraphShowScore.remove()
  }
}
```

o parâmetro `event` não está sendo usado dentro da função, então ele pode ser removido.

---

Nas aulas seguintes, você verá que aos poucos iremos refatorar o código essa aplicação =)

> Lidar com as diversas gamas de componentes que o Bootstrap fornece (foi meu primeiro contato com o framework), porém nada que me atrapalhasse

Legal! O intuito em usar o Bootstrap é apenas focarmos na lógica da aplicação. A marcação HTML fica um pouco verbosa com ele mesmo. Mas no fim das contas, o saldo é positivo.

> Escolha de nomes para variáveis/constantes

No decorrer do treinamento, você irá notar alguns padrões qeue uso para nomear. Aos poucos, através da observação e da prática, você conseguirá lapidar este aspecto em seu código =)

Mas é isso cara, parabéns pelo esforço!

E qualquer dúvida, conte comigo =D

**Comment by sou-gabriel** [comment]
Obrigado pelas observações Roger, ao finalizar a aplicação estava tão realizado que passou despercebido estes detalhes mencionados por ti. Rumo à fluência! =)
