### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#470]
# Obter ou Remover a listagem de classes de um elemento

**Exemplo:  TAG "p"**

``` javascript
//Selecionando o elemento:
const paragraph = document.querySelector("p")

//Adiciona a classe "error" ao elemento "p"
paragraph.classList.add("error")

//Remove a classe "error" do elemento "p"
paragraph.classList.remove("error")
```

# Adicionar classes em elementos HTML dependendo do seu conteúdo.

**Exemplo:** Temos uma lista com vários "p", dentro de alguns temos a palavra "error", em outros a palavra "success".

**Missão:** onde estiver escrito "error" adicionar a tag "p"  à classe "error" e onde estiver escrito "success" adicionar a tag "p"  à classe "success".

![image](https://user-images.githubusercontent.com/42559009/114786678-e9c8d980-9d54-11eb-9f6e-dfb0b6c7a39e.png)

**1ª Parte:**
Obter as referências de todas as tags "p"
``` javascript
const paragraphs = document.querySelectorAll("p")
```

**2ª Parte:**
A opção acima nos devolve um NodeList, utilizando isso podemos fazer um "forEach" e iterar sobre a paragraphs procurando dentro de cada linha as palavras "error" e "success", utilizando o método "innerText" e "includes".

``` javascript
paragraphs.forEach( paragraph => {
if (paragraph.innerText.includes("error")) {
paragraph.classList.add("error");
} else if (paragraph.innerText.includes("success")) {
paragraph.classList.add("success");
}
});
```

**Resultado:** 
![image](https://user-images.githubusercontent.com/42559009/114786742-09f89880-9d55-11eb-906c-3832446d32ef.png)

### **innerText**  
- obtém o texto visível que o elemento tem
### **textContent** 
- obtém todo o texto que o elemento tem, mesmo os que estão sob a propriedade CSS "display: none" que consequentemente estão invisíveis na tela para o usuário.

# Alternando as classes com a propriedade "Toogle"

A propriedade "toggle" adiciona uma classe a um elemento, porém se este elemento já possuir essa classe, ela remove a classe do elemento.

Exemplo da tag h1 e seu conteúdo sem classe.
![image](https://user-images.githubusercontent.com/42559009/114786797-2268b300-9d55-11eb-8d4a-a44dbff9d5f2.png)

ao selecionarmos e aplicarmos a propriedade "toogle"
``` javascript
const title = document.querySelector("h1")
title.classList.toggle("test")
```
![image](https://user-images.githubusercontent.com/42559009/114786834-2f85a200-9d55-11eb-86e0-b975e6ce8f1f.png)

e assim por diante... é como um botão de liga e desliga.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @davidtheblane! Rumo à fluência! 🔥
