### ISSUE TITLE
Resumo da Aula Deletando informações no Firestore 02-09 da etapa 15

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4700]
Adicionamos um botão de remover (com um `data-remove`), e um `data-id` em cada li na marcação HTML dinâmica para testarmos a remoção de informações do banco de dados. 

Cada conjunto de `button`/`li` deve receber os mesmos valores de `dataset`, e isto pode ser feito utilizando o parâmetro `index` do `reduce` do `gameLis` e interpolando na marcação dinâmica `li data-id=${index}` e `button data-remove=${index}`. Isto permite tomar a referência de qual `li` deve ser removida quando seu respectivo botão for clicado.

Movemos a declaração da `const` que faz referência à lista (elemento `ul`) de forma a torná-la global e acessível às funções nas quais precisamos usá-la. 

Logo após o event listener do formulário, inserimos o event listener da lista. 
```js
gamesList.addEventListener('click', event => {})
```
 Se dentro dele inserirmos um `console.log(event.target.dataset)`, ao clicarmos no botão, veremos no console um `DOMStringMap` com o valor da propriedade `remove` atribuído a ele. Clicando em qualquer `li`, vemos um objeto vazio. Desta forma, com o valor da propriedade `remove` do `dataset` de `button`, conseguimos manipular a `li` respectiva. O valor armazenado na propriedade é uma `string` (portanto, caso seja zero não é `falsy`), por isso podemos usá-lo dentro de um `if` e impedir que as instruções sejam executadas caso o elemento clicado seja uma `li` e não um botão:
```js
if(event.target.dataset.remove) {
    const game = document.querySelector(`[data-id="${event.target.dataset.remove}"]`)
game.remove()
}
```
Estas linhas de código apagam o item na página, mas se ela for recarregada, um novo request será feito ao banco de dados e nele ainda constará a informação referente ao item. Antes de efetivamente deletarmos o `document`, precisamos obter a referência a este, assim devemos importar uma outra função do SDK, o `doc()` (inseringo `doc` na dentro das chaves da linha do `import` do Firestone) e invocá-la dentro do bloco do `if` passando três argumentos: a referência do banco, a `collection` a que o `document` pertence e o `id` do `document`, porém este último precisa ser inserido dinamicamente, pois do contrário estaremos referenciando sempre o mesmo `document`.

Podemos obter o `id` utilizando o item do callback do `reduce` de `gamesLis`, pois ele é um objeto que contém uma propriedade com o `id` do `document`. Desta forma, ao invés de usarmos o `index` deste callback para atribuírmos o valor de data a cada `button` e `li`, podemos usar diretamente esta propriedade.  Neste caso, podemos remover o parâmetro `index` no `reduce` e na marcação dinâmica alteramos para `li data-id=${doc.id}` e `button data-remove=${doc.id}`.

Para deletar, importamos mais uma função do SDK, `deleteDoc()` (inserindo `deleteDoc` dentro das chaves na linha do `import` do Firestone), que recebe como argumento a `doc()` com seus argumentos. Esta invocação também retorna uma `promise`, por meio da qual podemos verificar se a remoção do `document` ocorreu com sucesso. Uma vez removido o `document`, não há como recuperá-lo. Para remover o item do DOM, uma alternativa é movermos a instrução que anteriormente inserimos dentro do if do event listener de gamesList para dentro do `then()` encadeado nesta `promise` :
```js
deleteDoc(doc(db, 'games', event.target.dataset.remove))
    .then(() => {
        const game = document.querySelector(`[data-id="${event.target.dataset.remove}"]`)
        game.remove()
        console.log('Game removido com sucesso')
      })
      .catch(console.log)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Kmkery. Vamo que vamo, rumo à fluência! 🙌
