### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters da etapa 03

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4702]
Muitas vezes a gente vai querer passar valores para dentro das nossas funções para que elas façam alguma coisa com esses valores.

```JS
const myFunc = function() {
console.log(`oi, nome!`)
}
```
Imagine que queremos substituir o _"nome"_ dentro do console por um nome de verdade.
A gente deve passar o valor pra dentro da função _**myFunc**_ e a função vai pegar esse nome e exibir no console.
Para fazer isso devemos especificar que queremos usar um nome dentro dessa função.
Então dentro dos parênteses inserimos _**name**_.
Indicando que essa função vai receber um valor que é o nome de de alguém.
Esse name é uma variável local que só pode ser usada dentro do bloco de código da função.
Se é uma variável e a gente pode usar ela dentro do bloco da função a gente pode substituir o **_nome_** no console por uma interpolação e passar _**name**_
Só que ainda não passamos um valor pra essa variável _**name**_. Se salvarmos assim _**oi, undefined**_ é exibido no console

Para atribuirmos um valor para _**name**_ temos que passar  entre os parênteses da invocação da função
```JS
const myFunc = function (name) {
console.log (`oi, ${name}!`)
}
myFunc('Roger')
```
**_Oi, Roger!_** é exibido no console porque estamos invocando a função e passando o valor **'Roger'**  para **name**.
Como a **name** agora está recebendo a string **'Roger'** o valor da variável dentro da interpolação é substituído por essa string.

Quando passamos um valor entre os parênteses da invocação de uma função, o valor é chamado de **argumento.**
Já a variável criada entre os parênteses da declaração da função é chamado de **parâmetro**

Podemos passar mais de um valor para dentro de uma função e uma função pode ter múltiplos parâmetros e argumentos.
Para adicionar mais um parâmetro na função, inserimos uma virgula e o outro nome do parâmetro
```JS
const myFunc = function (name, lastName) {
console.log(`Oi, ${name} ${lastName}`)
}
myFunc('Roger', 'Melo')
```
_**Oi, Roger Melo**_ é exibido no console.
A ordem dos argumentos deve corresponder a ordem dos parâmetros.
O primeiro parâmetro sempre vai receber o primeiro argumento, o segundo parâmetro sempre vai receber o segundo argumento e assim sucessivamente. Mas a ordem do uso desses parâmetros dentro da função não importa.
_**console.log(`Oi, ${lastName} ${name}!`)**_ nenhum erro vai acontecer, os parâmetros são renderizados normalmente na ordem em que a gente inserir dentro da função

Se tivermos parâmetros na declaração da função, mas não passarmos valores para esses parâmetros na invocação da função?
```JS
const myFunc = function (name, lastName) {
console.log (`Oi, ${name} ${lastName}!`)
}
myFunc()
```
_**Oi, Undefined undefined**_ é exibido no console
Para prevenir isso e não deixar um parâmetro receber **undefined** quando nenhum valor for passado para ele, podemos inicializar esse parâmetro com algum valor inicial que a gente definir
```JS
cons myFunc = function (name = 'José' , lastName = 'Oliveira') {
console.log(`Oi, ${name} ${lastName}`)
}
myFunc()
```
**Oi, José Oliveira** é exibido no console porque nao passamos nenhum valor na invocação da função, mas invés de receber undefined, recebeu os valores passados na criação da função.

Mas se duplicarmos a invocação da função e inserindo valores aos parâmetros, os valores passados substituem os valores passados na criação da função.
myFunc('Roger' , 'Melo')
**Oi, Roger Melo!** é exibido no console 
Mas se passarmos só um valor na invocação da função, só um valor será substituído, osegundo valor receberá o valor que foi recebido na criação da função.

myFunc('Roger')
**Oi, Roger Oliveira!** será exibido no console.

**Comment by Roger-Melo** [comment]
Show @josejuniorvr. Vamo que vamo, rumo à fluência! 🙌
