### ISSUE TITLE
Resumo da Aula O console do browser - Aula 01-05 da etapa 01

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#4707]
**COMO UTILIZAR O _DEVTOOLS_**

Abra o console do Browser clicando com o botão direito do mouse e em seguida _inspecionar_.

Outra forma de imprimir alguma informação no console é usando com comando ```console.log('alguma coisa')``` que ele irá imprimir o que estiver dentro dos parênteses.
O ```console.log()``` é um método para imprimir valores no console do browser.

**Comment by Roger-Melo** [comment]
Show @andersonpereiragithub. Vamo que vamo, rumo à fluência! 🙌
