### ISSUE TITLE
Resumo da Aula 04 da etapa 11 - Introdução a Promises

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#471]
## Introdução a Promises
- Promise é um objeto que representa o sucesso ou a falha de uma operação assíncrona
- Para criar uma nova promise usamos a função construtora Promise() junto com o new: new Promise()
- Uma promise sempre vai ter dois resultados possíveis:
  - resolved: Quando a promise teve sucesso e os dados foram obtidos
  - rejected: Quando ocorre um erro e a promise é rejeitada
- A função construtora Promise() recebe como argumento uma função com dois parametros: resolve e reject(Convenção universal)
- Esses parametros são funções embutidas da API de promise que vão ser responsáveis por lidar com o resultado da promise. Um quando ela teve sucesso e o outro quando ocorrer algum erro
- As funções resolve() e reject() possuem um return implicitado, portanto quando são invocadas todo o código abaixo delas é ignorado
- Quando uma promise tem sucesso ela fica com o estado: fulfilled. 
- As promises também possuem 2 outros estados: 
  - pending: Que é o estado inicial de uma promise, não teve nem sucesso e nem foi rejeitada
  - rejected: A operação falhou e a promise foi rejeitada
- Para acessarmos a resposta de uma promise utilizamos o método then()
- O método then() é o responsavel por receber a resposta da promise e pode receber como argumento 2 funções:
  - Uma função de callback com um parametro que representa a resposta positiva da promise, com os dados obtidos
  - Uma função de callback com um parametro que representa a resposta negativa da promise, quando houve um erro
- Uma das vatangens em se usar promises é que passamos a adcionar callbacks conforme for necessário, através do método then(), ao invés de passar esses calsbacks para dentro da nossa função que lida com a operação assíncrona.
- Dessa forma as promises eliminam o problema de callback hell
- Para lidarmos com um erro em uma promise usamos o método catch()
- O método catch() é o responsável por receber o erro que uma promise retorna quando ela falha
- O método catch() recebe como argumento uma função com uma parametro que representa o erro gerado pela promise

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @Hamiltonspjunior! Rumo à fluência! 🔥
