### ISSUE TITLE
Resumo da Aula: Modificando estilos CSS (inline), Aula 02-04 etapa 05

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4710]
Utilizando o Set já vimos que ele altera por completo os atributos que o elemento já possui, para não fazer isso podemos então usar a propriedade style atrelado ao que queremos mudar, não interferindo no restante.
Para modificar uma propriedade que é do CSS com duas ou  mais palavras no JS, é necessário usar o CamelCase, e se tiver dúvida, no console com ctrl+f você pode buscar a forma correta de escrita, colocando o começo do nome da propriedade. Para remover um atributo podemos fazer com estyle e deixar uma string vazia no lugar.

**Comment by Roger-Melo** [comment]
Show @Morais465. Vamo que vamo, rumo à fluência! 🙌
