### ISSUE TITLE
Resumo das Aulas 1, 2, 3 e 4 da etapa 05

### ISSUE THREAD

**Issue by George-Luis-Costa** [roger-melo-treinamentos/curso-de-js-roger-melo#4711]
# Resumo no formato OneNote
[Aulas - Etapa 05.zip](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/9356238/Aulas.-.Etapa.05.zip)

**Comment by Roger-Melo** [comment]
Show @George-Luis-Costa. Vamo que vamo, rumo à fluência! 🙌
