### ISSUE TITLE
Pq a soma veio fora do IF?

### ISSUE THREAD

**Issue by NathanCastro** [roger-melo-treinamentos/curso-de-js-roger-melo#4712]
### Etapa da aula

2

### Nome da aula

Exercícios - Aula 12 - módulo 2

### Link da aula

www

### Descreva a dúvida

Olá professor.
Fazendo o exercício do Módulo 2 - Controle de fluxo, gostaria de entender pq a soma fica fora do IF e não dentro.
"sum += randomNumbers[i]" Esta parte não entendi.
```js
const randomNumbers = [59, 61, 73, 57, 35, 73, 21, 87, 43]
let sum = 0;
const numberMax = 400
for (let i = 0; i < randomNumbers.length; i++) {
  if(sum > numberMax) {
    console.log(`"A soma ultrapassou ${numberMax}. Até aqui, o valor atual é ${sum}."`);
    break
  }  
  sum += randomNumbers[i]; 
}
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @NathanCastro! =)

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

Mas antes disso, eu procurei pelo seu nome na lista de alunos mas não encontrei. Com qual email vc se cadastrou no CJRM? Se não quiser falar por aqui, pode mandar um email para [oi@rogermelo.com.br](mailto:oi@rogermelo.com.br)

**Comment by NathanCastro** [comment]
Olá!
Na vdd não sou aluno não, eu só faço os exercícios do GitHub e como vi que
podia abrir issue ali, fiz a pergunta.

Em qua., 17 de ago. de 2022 às 08:37, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Olá @NathanCastro!

Então, esse benefício de abrir issues requisitando explicações de eventuais dúvidas ao longo do treinamento é de uso exclusivo para os alunos que compraram o curso =)
