### ISSUE TITLE
Resumo da Aula O que é controle de fluxo - Aula 01-02 da etapa 02

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4713]
## Controle de fluxo

	1. Looping
	2. All conditionals statement

##  Looping

	"O propósito de todo loop é executar um trecho de código repetidas vezes"

	// for loop
	
          Sintaxe:
```js		
	    for ([inicialização]; [condição]; [expressão final]) {
		    //bloco de código ou declaração
	    }
```			
	            1. Utilizando var na inicialização, a variável criada ficará no contexto global
	            2. Utilizando let na inicialização, a variável criada ficará no contexto do for
	            3. A execução do trecho de código poderá ser feito em uma única linha ou em bloco utilizando {}
	

```js	
            for (let i = 0; i < 5; i++) {
	            //  Bloco de código
	            console.log(`Dentro do loop: ${i}`)
            }
            console.log('Loop concluído')
```
		
          Fluxo:
          
	          1. Primeira execução
		          a. Inicialmente variável i com valor 0 foi criada
		          b. Expressão i < 5 é lida
			          i. Como é i é menor que 0, então o resultado da expressão é true
				           ii. Código dentro do loop é executado
		          c. Quando item b termina, a expressão i++ é executada
			          i. Nesse caso é somando +1 à variável i que atualmente é 0
	          
	          2. Execução até i for < 5
		          a. Expressão que cria a variável não é mais executada
			          i. Foi o ponto de partida para a criação da variável
		          b. Expressão i < 5 é lida
			          i. Como é i é menor que 0, então o resultado da expressão é true
				           ii. Código dentro do loop é executado
		          c. Quando item b termina, a expressão i++ é executada
			          i. Nesse caso é somando  + 1 à variável i
          
              "Nem sempre saberemos a quantidade de vezes a ser percorrida no loop, pois seu valor pode ser um array
               ou objeto de banco de dados"
		
```js		
		const names = ['Linus', 'Ada', 'Bill']
		
		for (let i = 0; i < names.length; i++) {
			//console.log(names[i])
			const htmlTemplate = `<p>${names[i]}</p>`
			console.log(htmlTemplate)
		}
```
          Terminologia:
          
              1. Percorrer um array
                  a. Iteração
	                  i. Corresponde a cada vez que o trecho de código é executado.
			

					
		
	// while loop
	
          "For e while fazem exatamente a mesma coisa, ou seja, executam um código um número determinado de vezes"
          "Porém, a única diferença entre eles é a sintaxe (a forma como eles são escritos)"
          "Loop infinito acontece quando a condição do loop não tem incremento"
```js			
      let i = 0
      while (i < 5) {
	      console.log(`Dentro do loop: %{i}`)
	      i++
      }
      
      const names = ['Jobs', 'Hopper', 'Turing']
      let i = 0
      
      while (i < names.length) {
	      console.log(names[i])
	      i++
      }
```

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano rumo à fluência! 🔥
