### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4720]
Controle de fluxo
## Estruturas condicionais
      // Operadores lógicos - "OU" || e "E" &&
		
          "Combina condições diferentes dentro uma mesma verificação"
          "Operador && verifica se duas condições são verdadeiras"
          "Operador || verifica se uma das condições é verdadeira"
			
```js
        const password = 'oi1'
		
        if (password.length >= 12 && password.includes('1')) {
	        console.log('Senha muito forte =)')
        } else if (password.length >= 8 || password.includes('1') && password.length >= 5) {
	        console.log('Senha forte')
        } else {
	        console.log('A senha deve conter 8 ou mais caracteres')
        }	
```

**Comment by Roger-Melo** [comment]
Excelente @silvasouzaadriano, rumo à fluência! 🎯
