### ISSUE TITLE
Resumo da Aula Retornando valores da etapa 03

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4721]
Ao invés de queremos exibir uma função no console, cão ter vezes que vamos querer que a função retorne um valor pra gente.
por exemplo: Se quisermos obter o dobro de um número.
Podemos passar esse número a uma função que vai fazer esse cálculo.
```JS
const double = function(number) {
const doubleResult = number * 2
console.log(doubleResult)
}
double(3)
```
6 é exibido no console.
O valor é exibido no console e não podemos fazer nada com ele, porque esse valor da multiplicação só está armazenado dentro da função na const **doubleResult** e como essa const foi declarada dentro da função, ela é local, só funciona dentro da função

Existe uma forma de a gente obter o valor dessa const fora do bloco da função para fazermos alguma coisa com esse valor,
essa forma é: Fazer a função **retornar** esse valor.
Ao invés de exibir a variável no console, a gente vai inserir a palavra-chave **return** _doubleResult_

```JS
const double = function(number) {
const doubleResult =  number * 2
return doubleResult
}
double(3)
```
Quando a função **double** é invocada, recebendo _3_ por argumento, esse _3_ foi atribuído pro parâmetro **number** e o código dentro do bloco é executado.
O cósdigo está criando uma _const_ **doubleResult** que recebe o resultado de _number * 2_ que resulta em _6_.
Logo após o condigo está fazendo a função retornar a _doubleResult_.
A expressão _double(3)_ resulta no valor que a função retornou.
Se a expressão resulta em _6_ a gente pode , por exemplo, armazenar esse valor numa constante.
```JS
const double = function(number) {
const doubleResult =  number * 2
return doubleResult
}
double(3)
const result = double(3)
console.log(result)
```
A const **result** armazena o valor que a função retornou que é _6_
E _6_ é exibido no console
Então é assim que a gente faz uma função retornar um valor.

Já que só queremos fazer a função retornar o resultado de _number * 2_ podemos fazer mais simplificado
```JS
const double = function(number) {
return number * 2
}
```
Ou seja a gente não precisa necessariamente armazenar o resultado dessa expressão em uma constante primeiro, a gente pode fazer esse retorno diretamente. A expressão _number * 2_ vai ser calculado e p resultado vai ser retornado.
devemos fazer como for mais legível e compreensível
```JS
const double = function(number) {
return number * 2
}
const result = double(3)
```
Agora que a gente tem o valor armazenado fora do escopo na **result** podemos usar ele normalmente

```JS
const showResult = function(value) {
return `O resultado é: ${value}`
console.log(showResult(result))
```
invocamos a função **showResult** passando a const **result** como argumento e o resultado é a _string_ que a função está retornando. 
no console a saída é : _**O resultado é: 6**_

**Comment by Roger-Melo** [comment]
Excelente @josejuniorvr, rumo à fluência! 🎯
