### ISSUE TITLE
Dúvida com métodos

### ISSUE THREAD

**Issue by john-maicon** [roger-melo-treinamentos/curso-de-js-roger-melo#4723]
### Etapa da aula

7

### Nome da aula

setTimeout() e o objeto window - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/963056

### Descreva a dúvida

Sei que scrollTo é um método no objeto global window.. dúvida é como saber usar, digo, como sei que precisava passar 2 argumentos, que um era pro eixo x outro y.. Veja no print abaixo, quando eu paro o mouse sobre o método ele me informa algo, porém não me fica claro que posso passar 2 valores.

Então, quando eu olhar o windon como faço, descubro de como usar aquele tal método? Pergunto para saber lidar com qualquer um tipo quando precisar..

![image](https://user-images.githubusercontent.com/68080301/185400447-d9402a6d-9a88-44fa-89b3-113d4656ab93.png)

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @john-maicon!

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Quando eu olhar o windon como faço, descubro de como usar aquele tal método? Pergunto para saber lidar com qualquer um tipo quando precisar.

Sempre que houver alguma dúvida em relação a como é escrita a sintaxe, como usar certo método ou quando você quiser saber algo um pouco mais específico de alguma particularidade do Javascript, eu recomendo que você consulte a documentação [MDN](https://developer.mozilla.org/en-US/).

É importante para um desenvolvedor saber pesquisar no MDN. Não tem segredo. Apenas vá no google e insira o nome do assunto/conceito que vc está estudando e em seguida, "MDN". Se você fizer isso com o método `scrollTo`, você verá logo no início da página a resposta para a sua pergunta sobre os argumentos do eixo X e Y =)

![Elemento](https://user-images.githubusercontent.com/82729897/185414512-77409890-091a-4a3a-910a-1be60d6ab41a.png)

Se você quiser refrescar a memória de como usar a documentação, recomendo que você assista novamente a aula da Etapa 05: MDN - Mozilla Developer Network - Aula 01-04 

---

Respondi a sua pergunta? Se restar qualquer dúvida é só avisar =)

**Comment by MivlaM** [comment]
Estou fechando a issue. No que precisar, é só abrir uma nova issue =)
