### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4725]
Funções e métodos são sinônimos, pois em essência eles fazem a mesma coisa, eles podem ser invocados para invocar um pedaço de código que faz alguma coisa para o programador. O que diferencia um método de uma função e a forma como invocamos eles.

Para invocarmos uma função, nos simplesmente inserimos ela e a abertura e fechamento de parênteses.

Já para invocarmos o método, ao invés de  simplesmente inserimos o nome e a abertura e fechamento de parênteses usamos na verdade a notação de ponto. Por exemplo:

const name = 'Hugo'

const nameMaiusculo = name.toUpperCase( ), depois se criamos um console.log com nome " nameMaiusculo " o nome Hugo vai estar todo em caixa alta aparecendo no console.

Em ambos os casos usamos os parênteses para fazer a invocação e esses parênteses  podem receber argumentos, a única diferença na forma como invocamos as funções e que na parte de traz da invocação do método agente referencia um valor inserindo um ponto. 

Métodos são funções, mas são funções que estão associadas a objetos ou tipos de dados como strings, os métodos são criados em um objeto ou em tipo de dado em si, já as funções são criadas sozinhas.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
