### ISSUE TITLE
Aplicação: Todo-List

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4726]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/AlessandroAscanio/todo-list

### Maiores dificuldades durante a implementação

A implementação da pesquisa, encontrar uma maneira de utilizar da forma correta o data attribute para deletar um todo sem utilizar o parentElement e com toda certeza a refatoração do código que tem sido um grande desafio pra mim.

### Menores dificuldades durante a implementação

Capturar os elementos do DOM, implementar a função de adicionar um todo, adicionar e adicionar os eventsListeners

**Comment by Roger-Melo** [comment]
Olá @AlessandroAscanio.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @AlessandroAscanio.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## A implementação da pesquisa, encontrar uma maneira de utilizar da forma correta o data attribute para deletar um todo sem utilizar o parentElement e com toda certeza a refatoração do código que tem sido um grande desafio pra mim.

Mesmo com a dificuldade relatada, você conseguiu =)

Tenha consciência que refatoração é uma habilidade que vai sendo elevada conforme vc pratica. E vc ainda praticará bastante durante o treinamento e será exposto há vários casos de uso.

Mas o mais importante num primeiro momento vc já fez, que é fazer funcionar. Refatoração vem depois =)

Vou deixar abaixo algumas observações sobre sua aplicação.

## Boas decisões

No geral, os nomes que você deu para as variáveis e funções deixaram bem claro o que elas armazenam/executam =)

---

## Indentação

Indentação é um dos pilares de um código mais legível.

Sabendo disso, você pode deixar o código mais fácil de entender ao indentar a marcação html dentro da template string dentro do bloco do if. No código atual, ela está na mesma linha que o `todosContainer`, talvez isso passe a impressão que elas são independentes, o que não é verdade. Portanto, faz mais sentido que a marcação esteja um pouco mais à direita. Ficaria assim:

```js
// antes
if(todo.length) {
    todosContainer.innerHTML += `
    <li data-id="${++id}" class="list-group-item d-flex justify-content-between align-items-center">
      <span>${todo}</span>
      <i data-remove="${id}" class="far fa-trash-alt delete"></i>
    </li>`
}
```

```js
// depois
if(todo.length) {
    todosContainer.innerHTML += `
      <li data-id="${++id}" class="list-group-item d-flex justify-content-between align-items-center">
        <span>${todo}</span>
        <i data-remove="${id}" class="far fa-trash-alt delete"></i>
      </li>`
}
```

---

## event.preventDefault() 

Prefira invocar event.preventDefault() na primeira linha da função.

Isso é uma convenção e faz mais sentido que um callback de submit informe na primeira linha que a página não será recarregada.

```js
// antes
const addTodo = event => {
  const todo = event.target.add.value
  
  event.preventDefault()
  // ...
}
```

```js
// depois
const addTodo = event => {
  event.preventDefault()

  const todo = event.target.add.value
  // ...
}
```

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Para que sua aplicação tenha uma definição clara onde começa e onde termina cada conceito, procure evitar o excesso ou a falta de linhas em branco no código.

Sabendo disso, você pode remover a linha 62, a função pode ser fechada sem necessidade de uma linha em branco antes do colchete. Ficaria assim:

```js
// antes
const searchTodo = event => {
  // ...
 
  hideTodos(getTodosList, inputValue)
  showAllTodos(getTodosList, inputValue)
  
}
```

```js
// depois
const searchTodo = event => {
  // ...
 
  hideTodos(getTodosList, inputValue)
  showAllTodos(getTodosList, inputValue)
}
```

---

## Nomenclatura

Uma observação seria, se fizer sentido para você, renomear a const `idRemove` para algo como `trashWasClicked` para indicar que o ícone da lixeira foi clicado no todo. Assim fica mais claro para quem está lendo ou trabalhando com o código, até mesmo pela primeira vez, que o ícone da lixeira foi clicado.

```js
// antes
const idRemove = event.target.dataset.remove
```

```js
// depois
const trashWasClicked = event.target.dataset.remove
```

Você também pode, se achar que faz sentido, trocar o nome do dataset de remove para trash. Isso traria mais coerência para o código, visto que a const `trashWasClicked` estaria recebendo uma expressão com o dataset mais similar a seu nome.

```html
<!-- Antes no código html -->
<i data-remove="1">...</i>
```

```js
// antes Javascript
const trashWasClicked = event.target.dataset.remove

todosContainer.innerHTML += `
  <li data-id="...">
    ...
    <i data-remove="${id}">...</i>
  </li>`
```

```html
<!-- Depois no código html -->
<i data-trash="...">...</i>
```

```js
// depois Javascript
const trashWasClicked = event.target.dataset.trash

todosContainer.innerHTML += `
  <li data-id="...">
    ...
    <i data-trash="${id}">...</i>
  </li>`
```

---

## Refatoração

Uma sugestão seria, se você achar que faz sentido, usar um `early return` dentro da função `createTodo`. A vantagem do early return é parar a execução da função naquele ponto caso a condição seja falsa, assim não se torna necessário ler a parte do código que vem em seguida. Além disso, usando um `early return`, você não precisa inserir o código da marcação html dentro do bloco do if, reduzindo então o número de indentações para essa marcação e tornando o código mais legível. Veja abaixo: 

```js
const createTodo = todo => {
  if(!todo.length) {
    return 
  }

  todosContainer.innerHTML += `
    <li data-id="${++id}" class="list-group-item d-flex justify-content-between align-items-center">
      <span>${todo}</span>
      <i data-trash="${id}" class="far fa-trash-alt delete"></i>
    </li>`
}
```

Dentro desse if do early return, qualquer coisa pode ser feita, como por exemplo, exibir a mensagem na tela que o texto inserido é invalido. Sempre que possível e sempre que fizer sentido, é preferível usar um early return do que executar uma leitura de código que não necessariamente precisa ser lida =)

Você também pode, se for interessante para você, mover o código de `createTodo` para a função `addTodo`. Um indicativo de que essa mudança pode fazer sentido é a similaridade dos nomes das funções, isso poderia ser simplificado numa única função dessa forma:

```js
const addTodo = event => {
  event.preventDefault()
  const todo = event.target.add.value
  
  if(!todo.length) {
    return
  }

  todosContainer.innerHTML += `
    <li data-id="${++id}" class="...">
      <span>${todo}</span>
      <i data-trash="${id}" class="..."></i>
    </li>`

  event.target.reset()
}
```

Um pequeno refactoring que você pode fazer na `removeTodo` é buscar o to-do no DOM apenas se ele de fato tiver que ser removido. Assim você elimina uma query desnecessária no DOM caso o elemento clicado não seja o de remoção do to-do =)

```js
// antes
const removeTodo = event => { 
  const trashWasClicked = event.target.dataset.trash
  const todo = document.querySelector(`[data-id="${trashWasClicked}"]`)
   
  if(trashWasClicked) {
    todo.remove()
  }
}
```

```js
// depois
const removeTodo = event => { 
  const trashWasClicked = event.target.dataset.trash
  
  if(trashWasClicked) {
    const todo = document.querySelector(`[data-id="${trashWasClicked}"]`)
    todo.remove()
  }
}
```

Você também pode, se achar que faz sentido, parar a execução dessa função no mesmo instante que a condição do if for falsa. Você pode fazer isso por meio de outro `early return`, a principal vantagem dele aqui é que o código que essa função se propõe a executar não está mais dentro de um bloco e consequentemente não é mais necessário que ele esteja indentado à direita. 

```js
const removeTodo = event => { 
  const trashWasClicked = event.target.dataset.trash
  
  if(!trashWasClicked) {
    return 
  }

  const todo = document.querySelector(`[data-id="${trashWasClicked}"]`)
  todo.remove()
}
```

Vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

É possível criar um array de objetos em que cada objeto, além de conter a referência do to-do no DOM, contém um boolean indicando se esse to-do deve ficar visível.

Eu "desfiz" as funções relacionadas à busca de to-dos e vamos ir codando passo a passo. Você pode declarar uma const `todos` que contenha as lis que representam os todos:

```js
inputSearch.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
})
```

Agora, você pode invocar console.log(todos) e buscar por eles, vai aparecer no console as lis de cada todo.

```js
inputSearch.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  console.log(todos)
})
```

Agora, sabendo que `todos` precisa armazenar um array de objetos e cada objeto precisa conter uma propriedade `todo` que vai armazenar a li e uma propriedade que vai receber um boolean indicando se esse todo vai ficar vísivel ou não, se para cada li do array você precisa gerar um objeto e o array gerado vai ter a mesma quantidade de itens que o original, você pode usar o método `map`. Já que cada item do array ao qual o map está sendo encadeado representa um todo, você pode inserir um parametro `todo` e fazer a função retornar um objeto. A cada execução do callback do map, um objeto vai ser inserido no novo array que o map está gerando. Ênfase que você não pode remover os parênteses após ter declarado uma propriedade, pois caso contrário o Javascript vai interpretar a abertura de chave como bloco da função. Para que o Javascript considere essa abertura e fechamento de chave como um objeto, você vai precisar desses parênteses conhecidos como grouping operator, eles que fazem com que a precedência dessa expressão seja o objeto literal.

```js
inputSearch.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo
  }))

  console.log(todos)
})
```

Em seguida, acrescentamos uma propriedade `shouldBeVisible` que armazena um boolean indicando se o `todo` deve ficar visível ou não. Você pode fazer isso pela expressão `todo.textContent.toLowerCase().includes(inputValue)` em que `todo.textContent.toLowerCase()` retorna o texto do todo em letras minúsculas e nessa string, você está verificando por meio do método `includes()` se ela contém a string da `inputValue`.

```js
inputSearch.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))
      
  console.log(todos) /* [{…}, {…}, {…}] 👈🏻 cada objeto contém um boolean que indica se o to-do deve ficar visível */
})
```

Tudo certo até aqui?

Agora que há um array de objetos que indicam quais to-dos devem ficar visíveis, vc pode criar uma única função `filterTodos` que manipula as classes dos to-dos, considerando a propriedade `shouldBeVisible`:

```js
const filterTodos = todos => {
  todos.forEach(({ todo, shouldBeVisible}) => {
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'hidden')
    todo.classList.remove(shouldBeVisible ? 'hidden' : 'd-flex')
  })
}

inputSearch.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))
      
  filterTodos(todos)
})
```

Por fim, podemos nomear o callback do listener de evento como `searchTodo`, por exemplo. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, porque ao bater o olho no nome da função, a ação que ela executa fica explícita:

```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children).map(todo => ({
    todo,
    shouldBeVisible: todo.textContent.toLowerCase().includes(inputValue)
  }))
 
  filterTodos(todos)
}
```

Entendeu a ideia? 

Mas o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

---

**Comment by AlessandroAscanio** [comment]
Olá @MivlaM !
