### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4728]
A palavra-chave THIS e utilizada para referenciar o objeto dentro de seu escopo sem ter que ficar reescrevendo o nome do mesmo, ou seja, utilizando THIS fora de um bloco de codigo ele fara referencia ao WINDOW que e a janela geral, e provavelmente nao e isso que queremos. 
Por outro lado utilizando THIS dentro de um bloco de codigo ele referenciara o mesmo. Basicamente como escopo local e global, porem caso seja utilizado dentro de uma ARROW FUNCTION o THIS perdera a referencia ao 'escopo local' e novamente referenciara o WINDOW. Entao para sua correta utilizacao o THIS deve ser utilizado dentro de um FUNCTION DECLARATION, entretanto, para nao ter que digitar muito mais que um arrow function existe um SHORTCUT para a function declaration dentro de um objeto e sua sintaxe e eliminando o dois pontos ( : ) na hora da atribuicao e a palavra "function", deixando somente os parenteses ( ) e chaves { }.
Ex:

        logBlogPosts: function ( ) {
            console.log('padrao')
        }

X

        logBlogPosts ( ) {
            console.log('shortcut')
        }

**Comment by Roger-Melo** [comment]
Excelente @YukOnRails, rumo à fluência! 🎯
