### ISSUE TITLE
Dúvida sobre aplicações do curso

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#4730]
### Etapa da aula

14

### Nome da aula

Exercícios da aula 03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1946514

### Descreva a dúvida

Bom dia, professor,

Uma dúvida sobre as aplicações: o "Conversor de moedas" que foi dado como exercício na aula "Exercícios da aula 03" também deve ser enviado para análise?

Eu dei uma desacelerada no curso porque as coisas saíram um pouco do controle, e não consegui administrar meu tempo para conciliar os estudos (curso, faculdade, treinamento de trabalho...) mas estou tentando me reorganizar e lembrei dessa aplicação que foi a última que fiz.

PS.: Lembro de ter lido uma certa vez (mas pode ser coisa da minha cabeça) algum documento que parecia listar as aplicações e a forma como era feita a análise, tipo um manual de instruções. Se esse documento existe, onde posso encontrá-lo?

Obrigada,
Elaine

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Dá uma olhada no email `[Alunos CJRM] Análises de aplicações` enviado dia 30 de maio do ano passado. Lá tem a listagem das aplicações, as instruções e critérios para uma aplicação ser analisada =)

**Comment by ElaineDelgado** [comment]
Boa tarde, Professor,!
Encontrei, não tinha lembrado de procurar no e-mail!! 
Obrigada.

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
