### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4734]
Podemos adicionar métodos dentro dos objetos, métodos são funções que são criadas dentro de objetos, elas são criadas para executar alguma ação, este método pode ser acessado através da notação de ponto. Lembrando que método é uma função, porem dentro de um objeto ela tem outro nome. As funções e os métodos tem a mesma usabilidade.

**Comment by Roger-Melo** [comment]
Show @EdsonAjjunior. Vamo que vamo, rumo à fluência! 🙌
