### ISSUE TITLE
Etapa 11, nome do vídeo: A fetch API - Aula 05-03

### ISSUE THREAD

**Issue by Hamiltonspjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#474]
Roger, lendo a documentação da Fetch API na mdn me deparei várias vezes com o termo headers, porém não entendi muito bem o que é isso. 

É algo importante com o que eu deveria me preocupar/estudar?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Hamilton. Eu falo sobre headers na aula [02-03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1189622) da etapa 11 =)

O que eu recomendo você saber sobre headers no momento é o que comentei nessa aula. 

Você se aprofundará em saber mais sobre eles se for construir uma API, ou seja, se trabalhar no server-side (back-end) de uma aplicação.

@Hamiltonspjunior

**Comment by Hamiltonspjunior** [comment]
Oi, Roger. 

Vou reasistir a aula, obrigado pelo esclarecimento.

**Comment by sou-gabriel** [comment]
@Roger-Melo aproveitando o gancho da dúvida do amigo, outros o método HTTP GET é o mais comumente utilizado no front-end de uma aplicação? Pois fiquei um pouco em dúvida sobre qual momento certo de também estudar os demais, e, se há realmente a necessidade de me preocupar com isso agora, já que minha energia está toda no front.
- Desculpas se não é permitido postar este tipo de dúvida por aqui numa outra issue, é que realmente quis aproveitar o gancho do assunto pra não perder o fio da manada.

**Comment by Roger-Melo** [comment]
Oi Gabriel.

O `GET` é o método HTTP que mais vamos usar nesse momento do treinamento, ao construir nossas aplicações. 

Vou falar sobre os [outros métodos](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) em etapas futuras, quando eu apresentar o NodeJS =)

@sou-gabriel

**Comment by Roger-Melo** [comment]
@Hamiltonspjunior e @sou-gabriel vou fechar a issue mas quando surgir alguma dúvida, é só abrir uma nova =)
