### ISSUE TITLE
weather applicationAplicação

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#4742]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Sansanoski/Weather-Forecast

### Maiores dificuldades durante a implementação

Uma dificuldade que tive foi de entender se somente consigo usar o retorno de uma PROMISE somente dentro de funções ASYNC. Eu sei que funções ASYNC retornam uma promises. Eu gostaria de entender se consigo armazenar o valor do retorno da PROMISES em uma variável para usar em outro lugar , ou somente consigo manipular o retorno da promises dentro de funções async?

### Menores dificuldades durante a implementação

Refatoração , dividir funções maiores para funções  menores com apenas uma  responsabilidade , fazer o consumo da API.

**Comment by Sansanoski** [comment]
feita a mudança

Em seg., 22 de ago. de 2022 às 08:47, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Olá @Sansanoski.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @Sansanoski.

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. Se você não está seguindo o que o email de análise de aplicações pede, talvez você deixe passar, por exemplo, o que pede o enunciado de algum desafio técnico para concorrer a uma vaga de desenvolvedor. Uma cor diferente da aplicação mostrada nas aulas é fundamental para que a sua versão da aplicação tenha uma aparência própria. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Novamente, os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

---

## Indentação

Indentação é um dos pilares de um código mais legível.

Sabendo disso, você pode deixar o código mais fácil de entender ao indentar `containerCity.textContent` dentro da função `getCurrentWeatherIntoDOM`. No código atual, ela está numa indentação diferente das outras duas consts usadas para pegar a referência de um atributo data, talvez isso passe uma impressão diferente sobre ela, o que não é verdade. Portanto, faz mais sentido que a marcação esteja como as outras.

```js
// antes
const getCurrentWeatherIntoDOM = ... => {
  containerCity.textContent = ...
    containerTemperture.textContent = ...
    containerWeather.textContent = ...
}
```

```js
// depois
const getCurrentWeatherIntoDOM = ... => {
    containerCity.textContent = ...
    containerTemperture.textContent = ...
    containerWeather.textContent = ...
}
```

---

## 4 espaços vs 2

Recomendo que ao invés de 4 ou 3 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4 ou 3.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Card sem informações

Em termos de usabilidade, para o usuário, não acredito que haja muito sentido exibir na tela inicial de sua aplicação um card sem imagem e sem informações relevantes sobre o nome e clima da cidade.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Para que sua aplicação tenha uma definição clara de onde começa e onde termina cada conceito, procure evitar o excesso ou a falta de linhas em branco no código.

Sabendo disso, no weather-app.js, você pode remover a linha 21. Ficaria assim:

```js
// antes weather-app.js
const fetchData = async url => {
  // ...
}

const getCityInfo = city => fetchData(getCityInfoURL(city))

const logConditionWeather = Key => fetchData(getCityConditionWeatherURL(Key))
``` 

```js
// depois weather-app.js
const fetchData = async url => {
  // ...
}

const getCityInfo = city => fetchData(getCityInfoURL(city))
const logConditionWeather = Key => fetchData(getCityConditionWeatherURL(Key))
``` 

---

## Code Styling

Observando os trechos de código abaixo, percebe que o espaçamento antes do nome da const `fetchInfoForecastWeather` está um pouco "desorganizado"? Algo similar acontece com os espaçamentos das vírgulas de outros trechos de código:

```js
// Espaço antes do nome da const
const  fetchInfoForecastWeather = ... => {
  // ...
}

// O espaçamento entre as vírgulas é diferente em cada trecho abaixo:
const getCurrentWeatherIntoDOM = (LocalizedName,IsDayTime , WeatherText , WeatherIcon , Temperature) => {
  // ...
}

getCurrentWeatherIntoDOM(LocalizedName,IsDayTime,WeatherText,WeatherIcon,Temperature)

const [{Key , LocalizedName}] = ...
const [{IsDayTime , WeatherText , WeatherIcon , Temperature}] = ...
```

Por convenção, recomendo que evite deixar esse espaço em branco antes do nome da const e seguir apenas um padrão de espaçamento entre as vírgulas por todo o código, ficaria assim:

```js
// Espaço antes do nome da const
const fetchInfoForecastWeather = ... => {
  // ...
}

// Ajustes no espaçamento entre as vírgulas
const getCurrentWeatherIntoDOM = (LocalizedName, IsDayTime, WeatherText, WeatherIcon, Temperature) => {
  // ...
}

getCurrentWeatherIntoDOM(LocalizedName, IsDayTime, WeatherText, WeatherIcon, Temperature)

const [{Key, LocalizedName}] = ...
const [{IsDayTime, WeatherText, WeatherIcon, Temperature}] = ...
```

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que você formate manualmente.

Isso vai fazer com que você adote um estilo de escrita de código e seja consistente com esse estilo ao implementar suas aplicações.

---

## Let ao invés de const

Prefira usar const no lugar de let, quando possível. 

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo. No entanto, vale a pena relembrar que as propriedades do objeto que a const armazena ainda podem sofrer mutação, então mesmo que o objeto seja atribuído a uma const, isso não garante que o objeto seja imutável. 

A let `imgIconContainer` pode ser uma const, pois ela não irá sofrer reatribuição de valor, porém as propriedades de seu objeto ainda estarão sujeitas à mutação. 

```js
// antes
let imgIconContainer = document.createElement('img')
```

```js
// depois
const imgIconContainer = document.createElement('img')
```

---

## Nomenclatura

Uma observação seria, se fizer sentido para você, renomear a const `getCityConditionWeatherURL` para algo como `getCityWeatherURL`. A palavra condition não necessariamente torna mais específico o que essa função está fazendo além de deixá-la mais longa sem necessidade, portanto `getCityWeatherURL` já fornece uma boa noção de que a função está retornando a url com as informações do clima da cidade escolhida para quem está lendo o código.

```js
// antes
const getCityConditionWeatherURL = Key => `...`
```

```js
// depois
const getCityWeatherURL = Key => `...`
```

Você também pode, se achar que faz sentido, trocar o nome da função `logConditionWeather` para algo similar à `getCityWeather`. A palavra log pode causar um entendimento errôneo do que a função está fazendo por exemplo, que algo vai ser exibido no console.log. Portanto, eu sugiro que você prefira uma abordagem mais direta e que traga coerência para o código. Como a função em questão está sendo usada para receber a invocação de `fetchData` e de `getCityWeatherURL`, ela já está recebendo os dados que podemos usar para exibir as informações na tela, portanto o nome `getCityWeather`, nessa situação, pode fazer mais sentido.

```js
// antes
const logConditionWeather = Key => fetchData(getCityWeatherURL(Key))  
```

```js
// depois
const getCityWeather = Key => fetchData(getCityWeatherURL(Key))  
```

---

## Ternário

No operador ternário, você pode abstrair as repetições de `imgTime.src` e de benefício deixá-lo mais simples escrevendo menos código. Uma implementação ideal do ternário poderia ser feita ao fazer `imgTime.src` receber a condição de `IsDayTime` da seguinte forma:

```js
// antes
IsDayTime ? imgTime.src = './src/day.svg' : imgTime.src = './src/night.svg'
```

```js
// depois
imgTime.src = IsDayTime ? './src/day.svg' : './src/night.svg'
```

Uma outra observação e também um gosto pessoal meu, seria você deixar o código que usa ternário na primeira linha entre as linhas da função que manipulam o DOM. O sentido aqui é que fique claro para quem está lendo o código da função que manipula o DOM que um ternário está sendo usado logo de início. 

```js
// antes
const getCurrentWeatherIntoDOM = (LocalizedName, IsDayTime, WeatherText, WeatherIcon, Temperature) => {
  containerCity.textContent = LocalizedName
  containerTemperture.textContent = Temperature.Metric.Value
  containerWeather.textContent = WeatherText
    
  IsDayTime ? imgTime.src = './src/day.svg' : imgTime.src = './src/night.svg'

  // ...
}
```

```js
// depois
const getCurrentWeatherIntoDOM = (LocalizedName, IsDayTime, WeatherText, WeatherIcon, Temperature) => {
  imgTime.src = IsDayTime ? './src/day.svg' : './src/night.svg'

  containerCity.textContent = LocalizedName
  containerTemperture.textContent = Temperature.Metric.Value
  containerWeather.textContent = WeatherText
    
  // ...
}
```

---

## Validação

Na função `fetchInfoForecastWeather`, algo que você pode adicionar e que seria interessante como funcionalidade para o usuário é inserir uma validação no `inputValue`. Esse `inputValue` pode ter uma verificação para caso uma string vazia ou string com menos de três caracteres for enviada como input. Numa situação assim, você pode, se achar que faz sentido, exibir uma mensagem na tela por meio do `alert` comunicando que é necessário inserir o nome de uma cidade. Ficaria assim:

```js
const fetchInfoForecastWeather = async event => {
  // ...
  const inputValue = event.target.city.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira o nome da cidade")  
    return
  }
  // ...
}
```

---

## Refatoração

Uma opção de refatoração que você pode fazer é eliminar a função `getCurrentWeatherIntoDOM` e mover código dela para dentro de `fetchInfoForecastWeather`. Nessa nova função, você também pode renomeá-la para um nome mais conciso e coerente em relação ao papel que ela está desempenhando no código, algo como `showCityWeather`. Ficaria assim:

```js
const showCityWeather = async event => {
  event.preventDefault()
  
  const inputValue = event.target.city.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira o nome da cidade")  
    return
  }

  const [{Key , LocalizedName}] = await getCityInfo(inputValue)
  const [{IsDayTime , WeatherText , WeatherIcon , Temperature}] = await getCityWeather(Key)

  imgTime.src = IsDayTime ? './src/day.svg' : './src/night.svg'

  containerCity.textContent = LocalizedName
  containerTemperture.textContent = Temperature.Metric.Value
  containerWeather.textContent = WeatherText

  imgIconContainer.setAttribute('src',`./src/icons/${WeatherIcon}.svg`)
  imgIconContainer.classList.add('iconImage')
  icon.appendChild(imgIconContainer)
   
  form.reset()
}
```

Um indicativo de que essa mudança pode fazer sentido é a similaridade dos nomes das funções, isso poderia ser simplificado numa única função. Assim, por meio dessa refatoração, você concentra grande parte da manipulação do DOM em apenas uma função e deixa ela com um nome mais específico.

Uma outra possibilidade de refatoração seria, por meio de uma abstração, você não precisar mais usar a invocação de `getCityInfo`. Segundo o raciocínio, ao invés de termos essa função, nós vamos ter apenas a função `getCityWeather` que vai fazer o que a `getCityInfo` está fazendo. A ideia dessa refatoração é ao invés de invocarmos duas funções, simplificar as coisas e precisarmos apenas invocar uma função que irá fazer o papel das duas =)

Dito isso, para entender de fato essa abstração que vou mostrar, eu sugiro que você escreva e execute cada código do passo a passo abaixo junto comigo, ok?

Vamos lá, vou criar uma função chamada `getCityWeather` que ao invés de receber a key, vai receber o nome da cidade. Antes de buscarmos o clima da cidade, precisamos obter as informações da cidade para obtermos a key, pois só por meio dela poderemos fazer o segundo request, no caso do seu código, o usado na função `fetchData`. Para desaninharmos as funções invocadas dentro da `fetchData`, vamos criar uma const `cityInfoUrl` que vai receber a `getCityInfoUrl` e vamos exibí-la no console para confirmarmos se os resultados que esperamos estão sendo obtidos.

```js
const getCityWeather = city => {
  const cityInfoURL = getCityInfoURL(city)
  console.log(cityInfoURL) // Url com o nome da cidade no query parameter aparece...
} 
``` 

Não se preocupe se aparecer algum erro no console, o intuito aqui é, ao executarmos um console.log, ver a url com o nome da cidade no query parameter, ou seja, a cidade buscada. Feito isso, já que essa url está sendo obtida, podemos criar uma const `cityInfo` que vai armazenar o retorno da função `fetchData`. Seguindo o raciocínio, `cityInfo` vai ser uma função async, portanto terá um await que espera a resolução dessa promise que contém `cityInfoUrl` como argumento. Ficaria assim:

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const cityInfo = await fetchData(cityInfoURL)
  console.log(cityInfo) // Array de objetos aparece...
} 
```

Ao visualizarmos isso no console, veremos que o resultado é um array de objetos em que o primeiro objeto vai corresponder, na maioria das vezes, a cidade escolhida no input.

No código que usamos para manipular o DOM, estamos usando, além da propriedade Key, a propriedade LocalizedName. Então, também vamos precisar da propriedade localizedName, e essa função `getCityWeather` vai ter que retornar ela para quando for invocada ela ser usada no destructuring e e então servir como argumento dessa invocação. 

Para fazermos o destructuring no array de objetos e pegarmos do primeiro objeto, as propriedades LocalizedName e Key, vamos fazer um destructuring nesse primeiro objeto, na propriedade Key e na LocalizedName. Feito isso, se exibirmos no console, aparece a Key e o nome da cidade como LocalizedName. 

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  console.log(Key, LocalizedName) // Key e LocalizedName aparecem no console...
} 
```

Após isso, vamos fazer o segundo request para obtermos a informação do clima dessa cidade, para isso, vamos usar a Key. Para isso, vamos obter a url, vou criar uma const `cityWeatherURL` recebe a invocação de `cityWeatherURL()` que recebe a Key como argumento. Dessa forma, a url com a Key vai ser retornada corretamente.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getCityWeatherURL(Key)
  console.log(cityWeatherURL) // Url com a Key vai ser retornada...
} 
```

Feito isso, agora que temos a url, falta fazer o último request, que é o request que vai buscar os dados do clima da cidade. Para fazer isso, vamos criar uma const `cityWeather` que recebe `fetchData` com await antes porque é uma função assincrona, e esse `fetchData` vai receber `cityWeatherURL` como argumento.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getCityWeatherURL(Key)
  const cityWeather = await fetchData(cityWeatherURL)
  console.log(cityWeather) // Array com um objeto que contém os dados do clima da cidade.
} 
```

Agora, podemos retornar cityWeather e para que essa função não retorne um array num objeto, podemos fazer com que ela retorne apenas um objeto por meio de um destructuring.

```js

const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getCityWeatherURL(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return cityWeather
} 
```

Você se lembra que esse objeto que está sendo retornado por essa função também precisa ter LocalizedName? Então, ao invés de retornar um objeto, você pode retornar um novo objeto que contém as propriedades do objeto cityWeather e também contém LocalizedName. Aqui foi criado um novo objeto que contém as propriedades do objeto cityWeather espalhados pelo spread operator e que também contém a LocalizedName.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityInfoURL(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getCityWeatherURL(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return { ...cityWeather, LocalizedName }
} 
```

Por fim, resta inserir LocalizedName como um dos destructurings da função `getCityWeather`. Nessa função, o destructing do array, ou seja, os colchetes, podem ser removidos.

```js
const {IsDayTime , WeatherText , WeatherIcon , Temperature, LocalizedName} = await getCityWeather(inputValue)
```

Após isso, você não vai precisar mais da função `getCityInfo` e o código estará funcionando perfeitamente bem =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Olá @Sansanoski.

> ## Não seria feita pelo professor Roger por um vídeo explicativo ?

Não necessariamente. 

Porém, o Maykell é uma pessoa da equipe treinada por mim. Toda análise de alguém da equipe passa pela minha direção e supervisão =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
