### ISSUE TITLE
Resumo da Aula O operador lógico not (!) - Aula 03-02 da etapa 02

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4744]
// Operador lógico not (!)

	"Quando um ponto de exclamação é adicionado a frente de um boolean. O valor do boolean é invertido"
	"Quando usado com valores não booleanos, ele retornará false se seu único operando  puder ser convertido em true;
     caso contrário, retorna true."

```js

	let isUserLoginIn = false
	
	if (!isUserLoginIn) {
		console.log('Você precisa fazer login para continuar')
	}
	
	console.log(!true)
	console.log(!false)

```

**Comment by Roger-Melo** [comment]
Show @silvasouzaadriano. Vamo que vamo, rumo à fluência! 🙌
