### ISSUE TITLE
Resumo da Aula Utilizando callbacks e exercícios - Aula 02-05 da etapa 03

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4752]
Nesta aula vimos um exemplo avançado de forEach combinado com uma função de callback pra gera um template HTML através de dados.  Este exemplo utiliza de recursos ainda não vistos no curso como a interação com o browser, porém ele ilustra bem uma das possibilidades de forEach e callback no JS.

**Comment by Roger-Melo** [comment]
Show @Hugones45 Vamo que vamo, rumo à fluência! 🙌
