### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04

### ISSUE THREAD

**Issue by LeandroAzevedo-1** [roger-melo-treinamentos/curso-de-js-roger-melo#4758]
* Argumentos, parâmetros e default parameters

    * Passando valores para a function

    * (name) esse valor entre parentese é chamado de parâmetro 

    * Pode ser passado mais de um parâmetro (name, lastName), quando for chamar a function tenho que passar dois argumento. myFunc('Leandro', 'Azevedo') 

    * Mas tenho que passar na expressão também para buscar os dois valores
    console.log(`Oi, ${name} ${lastName}`)

const myFunc = function (name, lastName) {
    console.log(`Oi, ${name} ${lastName}!`)
}

   *  Esse valor vai ficar na name. Esse valor é chamado de argumento. 

   *  Se não colocar nenhum valor como argumento, o valor é undefined. Para previnir posso passar como o valor no parâmetro como no exemplo 
    (name = "Estrôncio", lastName = "Almeida").

    * myFunc ( ) * se chamar a function é não passar argumento, o valor fica o que está sendo passado como parâmetro.
     
    * Passando valores como argumento, ele vai sobrescrever os valores passado como parâmetro. 

myFunc('Leandro', 'Azevedo')

**Comment by Roger-Melo** [comment]
Show @LeandroAzevedo-1. Vamo que vamo, rumo à fluência! 🙌
