### ISSUE TITLE
Resumo da Aula Conversão de tipos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#476]
# Conversão de Tipos

* typeof variavel  : Retorna o tipo da variável de interesse.
```js
let word = "casa";
console.log(typeof word);// string
```

* Number(argumento): Retorna o valor do argumento convertido em number.

```js
let height = "1.78";
console.log(height + 0.02);//1.780.02

let newHeight = Number(height) + 0.02;
console.log(newHeight);//1.8

let crazyConverted = Number("maça");
console.log(crazyConverted);//NaN
``` 

Como pôde ser visto, Number(argumento) não consegue converter o tipo se o argumento não for composto de algarismos arabicos

* String(argumento): Retorna o valor do argumento convertido em string.

```js
//String(argumento)
let numberToString = String(97);
console.log(numberToString, typeof numberToString);//97 string
``` 

* Boolean(argumento): Retorna o valor do argumento convertido em boolean. Essa conversão é feita sob os critérios do javaScript sobre quais valores são falsy e quais são truthy:
	* Valores falsy: false, 0, "", '', null, undefined e NaN.
	* Valores Truthy: Todos valores que não são falsy.

```js
//Boolean(argumento)
console.log(Boolean(0));//false
console.log(Boolean(""));//false
console.log(Boolean(-99));//true
console.log(Boolean("/"));//true
``` 

	

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ThiagoDeMorais! Rumo à fluência! 👊🏻
