### ISSUE TITLE
Resumo da Aula 3 escopos em JavaScript que você deve conhecer - Aula 01-03 da etapa 05

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4761]
ESCOPO DE FUNCAO
E o alcanse de acessibilidade de uma variavel/constante, ou seja, se forem declaradas dentro de um funcao elas existirao apenas la, sendo impossivel seu accesso externamente exceto por retorno.

ESCOPO DE BLOCO
E praticamente a mesma coisa que o escopo de funcao, a unica diferenca e que variaveis VAR nao se limitam ao escopo do bloco o qual foram declaradas e poderao ser acessadas externamente, ainda assim a regra anterior de escopo se mantem para LET e CONST.

ESCOPO LEXICO
Em blocos de codigos e ou funcoes aninhadas o escopo de dentro para fora e possivel no bloco aninhado, ou seja, o bloco filho pode acessar o bloco pai mas nao o contrario. Esta regra nao se aplica ao inverso onde o bloco pai nao pode acessar o escopo do bloco aninhado (filho).

**Comment by Roger-Melo** [comment]
Show @YukOnRails. Vamo que vamo, rumo à fluência! 🙌
