### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4766]
// Retornando valores

	As vezes não queremos exibir o valor processado de uma função.
	Em muitos casos, podemos querer processar esse valor e retorná-lo para posteriormente usá-lo.
	Na última linha da função usamos a palavra chave return e depois o valor processado.

```js
	const double = function (number) {
		//const doubleResult = number * 2
		//return doubleResult
		
		return number * 2
	}
	
	const result = double(3)
	
	const showResult = function (value) {
		return `O resultado é: ${value}`
	}
	console.log(showResult(result))
	
```

**Comment by Roger-Melo** [comment]
Show @silvasouzaadriano. Vamo que vamo, rumo à fluência! 🙌
