### ISSUE TITLE
Resumo da Aula 01-04 da etapa 06 - Expressões regulares

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4770]
Quando trabalhamos com formulários, na maioria das vezes vamos querer validar os dados que estão sendo inseridos dentro do input, então criamos certos padrões que precisam ser satisfeitos para validar o formulário, para estas validações podemos utilizar o Regex que são Regular Expression, então criamos padrões com o Regex que ao derem match com as strings dentro dos inputs são validadas

**Comment by Roger-Melo** [comment]
Show @Diegodkid. Vamo que vamo, rumo à fluência! 🙌
