### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#478]
# Template String

Template string serve para fazer interpolação. Quando for necessário interpolar variáveis e strings, apresentar esses dados com aspas ou quebrar linhas, então o recomendável é usar template string.

## Concatenação Normal

Aqui é usado o **+** para concatenar:

```js
const postMessage = 'O post "' + postTitlte + '" do ' + postAuthor + ', tem ' + postComments + ' comentários.'
console.log(postMessage);
```

Neste console.log seria apresentado: "O post "É bolacha ou biscoito?" do Matheus Saad, tem 15 comentários."

## Interporlação com Template String

A Template String usa crase ( ` ) em volta de todo o texto e as variáveis/constantes devem ficar dentro de **${ ... }**:

```js
const postMessage = `O post "${postTitle}", do ${postAuthor}, tem ${postComments} comentários`;
```

Também podemos utilizar template string para criar templates HTML:

```js
const HTML = `
    <h2> ${postTitle} </h2>
    <p> Autor: ${postAuthor} </p>
    <span> Este post tem ${postComments} comentários </span>
`;

console.log(HTML);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer! Rumo à fluência! 🔥
