### ISSUE TITLE
Resumo da Aula Conhecendo a date-fns - Aula 02-03 da etapa 10

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4783]
date-fns é uma biblioteca de data para se trabalhar com Javascript.

Como obter a date-fns ?

Acesse o site date-fns.org e vá em getting installation. As versões acima de 1.9 são instaladas utilizando o npm. Caso queira fazer a instalação por CDN é preciso selecionar a versão 1.9 e inserir o link do CDN no index.html com a tag script src.
No link do CDN onde aparece /VERSION/ substitua por v1.9.0.
Após a instalação para verificar se esta funcionando pode usar um console.log(dateFns), aparecerá uma lista de métodos que podem ser utilizados.

Como formatar datas com o date-fns ?

Primeiro crie um objeto date com a data atual.

```js
const present = new Date()
dateFns.isToday //Retorna um boolean se a data é hoje, retorna true senão false

//método dateFns.format() recebe 3 argumentos(date, token, objeto com opções de idioma), os tokens devem ser consultados na documentação

console.log(dateFns.format(present,’MMMM’))// August
console.log(dateFns.format(present,’YY’))// 22 (ano com 2 digitos)
console.log(dateFns.format(present,’dddd’))// Saturday
console.log(dateFns.format(present,’Do’))// 20th

```
É possível combinar tokens e desta maneira personalizar a data, exemplo:

```js
console.log(dateFns.format(present,’DD/MM/YYYY’)) // 20/08/2022
```

como comparar as datas com o dataFns ?

```js
const past = new Date(‘April 7 2019 17:00:00’)
const present = new Date()
console.log(dateFns.distanceInWords(present, past)) // Retorna uma string que representa a distância entre as data que ele recebeu como argumento.

**Comment by Roger-Melo** [comment]
Boa @AlessandroAscanio, rumo à fluência! 🔥
