### ISSUE TITLE
Resumo da Aula Aula Adicionando o JavaScript a uma página web da etapa 01

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#4788]
Para adicionar o JavaScript a uma página Web usa-se a tag _<script></script>_. Pode se colocar a tag <script> dentro da tag '_head_'.

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aula 1</title>
    <script>
        alert('hello,')
    </script>
</head>
<body>
    <h1>Learning JavaScript</h1>
</body>
</html>
```

Mas carregar o JavaScript dentro da tag '_head_' pode gerar problemas no carregamento da página. Uma melhor prática é colocar a tag _<script></script>_ dentro da tag '_body_'.

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aula 1</title>
</head>
<body>
    <h1>Learning JavaScript</h1>
    <script>
        alert('hello, world')
    </script>
</body>
</html>
```

Caso o JavaScript tenha uma quantidade considerável de linhas do código é aconselhável colocar o script em um arquivo externo e inserir o arquivo pelo atributo _src_ na tag _<script>_.

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aula 1</title>
</head>
<body>
    <h1>Learning JavaScript</h1>
    <script src="./app.js"></script>
</body>
</html>
```

**Comment by Roger-Melo** [comment]
Boa @Geisonszo rumo à fluência! 🔥
