### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#479]
```js
Eu não entendi o "log(transformToUpperCase(millennialWords))" por que só, "log()"? ao invés de console.log(), aqui no comigo somente o log() dá erro.
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Renar. 

No título da issue você precisa postar a etapa da aula, se não fica mais complicado eu encontrar a aula aqui.

A dúvida é sobre a aula [02-01 da etapa 03](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284)?

Se sim, consertei o título da issue.

---

`log` é a função que foi criada no exercício 3 dessa bateria de exercícios. Na aula eu usei `log` por que foi o nome que dei para a função que criei =)

Ficou mais claro?

@renarfreitas

**Comment by renarfreitas** [comment]
Ficou super Claro Roger!! Obrigado!
Eu revi a correção do exercício, passo a passo, e percebi a minha falta de atenção.
Obrigado pela resposta.

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
