### ISSUE TITLE
Resumo da Aula Adicionando e modificando conteúdo em uma página - Aula 02-02 da etapa 05

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4794]
- innerText
E uma propriedade que representa o conteudo textual 'renderizado' de um no (tag) e seus descendentes. Usada com um GETTER retorna de maneira aproximada o texto que o usuario obteria caso tivesse selecionado o conteudo e copiado para a area de transferencia.

- innerHTML
A propriedade innerHTML defino ou obtem a sintaxe HTML ou XML descrevendo os elementos descendentes. Sendo um GETTER e SETTER, esta propriedade fornece uma forma simples de trocar o conteudo de um elemento.

**Comment by Roger-Melo** [comment]
Boa @YukOnRails rumo à fluência! 🔥
