### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4795]
// a palavra-chave this

	O this é um objeto de contexto.
	Ele representa o contexto no qual o código está sendo executado.
	Dependendo de como e onde o utilizamos, seu valor mudará.
	Se o referenciarmos na raíz do código, ele utilizará o context global que é o window object.
	Ao criarmos um atributo do tipo function

      a) Utilizando function declaration
          i) Ao utilizarmos o this dentro da function, o this referenciará o objeto sendo usado.
	
      Nota: ao removermos a palavra-chave function e os dois pontos (:), o JS também reconhece
      que o atributo sendo criado é de uma function declaration.
	
      b) Utilizando arrow function
          i) Ao utilizarmos o this dentro da function, o this referenciará o objeto global window

```js
let user = {
    name: 'João',
    age: 31,
    email: 'joaocardoso@gmail.com',
    city: 'São Paulo',
    blogPosts: ['Empadão de frango', '4 receitas de purê de batata'],
    login () {
	    console.log('Usuário logado')
    },
    logout () {
	    console.log('Usuário deslogado')
    },
    logBlogPosts: function () { // function declaration
      //console.log(this.blogPosts))
      //console.log(this) referencia o contexto do object user
      
      console.log(`${this.name} escreveu os seguintes posts:`)
      
      this.blogPosts.forEach(post => {
      console.log(post)
      })
    },
    logBlogPosts2 () { // function declaration (outra forma de criar o atributo)
	this.blogPosts.forEach(post => {
		console.log(post)
	})
    }
}

user.login()
user.logout()
user.logBlogPosts()

console.log(this) // referencia o contexto do object window
```

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano rumo à fluência! 🔥
