### ISSUE TITLE
Resumo da Aula exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by LeandroAzevedo-1** [roger-melo-treinamentos/curso-de-js-roger-melo#4797]
const { is } = require("express/lib/request")

/*
  01

  - Utilizando function declaration, implemente uma função que recebe 2 números  
    por parâmetro e retorna o resultado da multiplicação entre esses 2 números;
  - Previna que esses parâmetros recebam undefined;
  - Exiba o resultado no console, sem inserir um console.log() dentro da função.
*/
  function multitwoNumbers (firstNumber = 0, secondNumber = 0) {
    return firstNumber * secondNumber
  }

  // console.log(multitwoNumbers(5, 10))
/*
  02

  - Faça o mesmo que o exercício acima pede, mas desta vez, implemente uma  **function expression** que retorne o resultado da **divisão** entre esses 2 números.
*/
  const divideTwoNumbers = function ( firstNumber = 0 , secondNumber = 0) {
    return firstNumber / secondNumber
  }
  // console.log(divideTwoNumbers(20, 2))
/*
  03

  - Implemente uma função que apenas exibe no console o valor recebido por parâmetro;
  - Previna que o parâmetro dessa função receba undefined;
  - Faça a string abaixo ser exibida 7x no console;
  - A cada exibição, substitua o "X" pela informação correta;
  - Não repita (manualmente) a invocação da função ou do console.log().

  "Esta é a Xª vez que essa string é exibida."
*/

function log (value = `Você deve passar um valor como argumento.`) {
  for (let i = 1; i <= value; i++) {
    console.log(`Esta é a ${i}ª vez que essa string é exibida.`)
  }
}
// log(7)

/*
  04

  - Comente o código acima, de forma que a string não seja mais exibida no console;
  - Implemente uma função que retorna um novo array com as strings do array  
    "millennialWords" em letras maiúsculas;
  - Exiba o novo array no console, sem inserir um console.log() dentro da  
    função.
*/

const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']

const trasformToupperCase = function( array = []) {
  let newArray = []
  
  for(let i = 0; i < array.length; i++) {
    // Refatorando o código 
    const arrayUpperCase = array[i].toUpperCase()

    newArray.push(arrayUpperCase)
  }

  return newArray
}

// console.log(trasformToupperCase(millennialWords))

/*
  05

  - Implemente uma função que retorna se um número é positivo;
  - Use essa função para descobrir quantos números positivos o array 
    "randomNumbers" possui;
  - Exiba a frase abaixo no console, inserindo as informações corretas.

  "O array "randomNumbers" possui XX números, sendo XX positivos e XX negativos."
*/

const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

let positiveNumberCounter = 0
let negativeNumberCounter =0

const isPositive = function (number = 0) {
  return number  >= 1
}

for (let i =0; i < randomNumbers.length; i++) {
  // Refatorando 
  const express = isPositive(randomNumbers[i])

  if(express) {
    positiveNumberCounter++
  }else {
    negativeNumberCounter++
  }
}

const messageResult = `O array "randomNumbers" possui ${randomNumbers.length} números, sendo ${positiveNumberCounter} positivos e ${negativeNumberCounter} negativos.`

// console.log(messageResult)

/*
  06

  - Descomente a invocação da função abaixo e implemente-a;
  - Ela deve retornar um novo array com apenas os números ímpares do array 
    passado por argumento;
  - Exiba o novo array no console, sem inserir um console.log() dentro da  
    função.
*/
const getOddNumbers = function (number = []) {

  const newArray = []

  for (let i = 0; i < number.length; i++) {
    // Refatoração
    const numbers =  number[i]
    const isOddNumber = numbers % 2 !== 0 

    if(isOddNumber) {
      newArray.push(numbers)
    }
  }
  return newArray
}

const oddNumbers = getOddNumbers([83, 52, 31, 73, 98, 37, 61, 56, 12, 24, 35, 3, 34, 80, 42])

// console.log(oddNumbers)

/* 
    resultado 
    [
      83, 31, 73, 37,
      61, 35,  3
    ] 
*/

/*
  07

  - Forme uma frase com o array abaixo e exiba-a no console.
*/

const functions = [
  function () { return 'Plymouth' },
  function () { return 'é' },
  function () { return 'uma' },
  function () { return 'cidade' },
  function () { return 'fantasma' },
  function () { return 'localizada' },
  function () { return 'na' },
  function () { return 'ilha' },
  function () { return 'de' },
  function () { return 'Montserrat,' },
  function () { return 'um' },
  function () { return 'território' },
  function () { return 'ultramarino' },
  function () { return 'do' },
  function () { return 'Reino' },
  function () { return 'Unido' },
  function () { return 'localizado' },
  function () { return 'na' },
  function () { return 'cadeia' },
  function () { return 'de' },
  function () { return 'Ilhas' },
  function () { return 'de' },
  function () { return 'Sotavento' },
  function () { return 'nas' },
  function () { return 'Pequenas' },
  function () { return 'Antilhas,' },
  function () { return 'Índias' },
  function () { return 'Ocidentais.' }
]

let sentece = ''

for (let i = 0; i < functions.length; i++) {
  // Refatoração
  const string = `${functions[i]()} `
  
  sentece += string
}

console.log(sentece)

**Comment by Roger-Melo** [comment]
Boa @LeandroAzevedo-1 rumo à fluência! 🔥
