### ISSUE TITLE
Resumo da Aula Construindo um Relógio Digital - Aula 02-02 da etapa 10

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#4798]
const clockContainer = document.querySelector('.clock-container')

const updateClock = () => {
  const present = new Date()
  const hours = present.getHours()
  const minutes = present.getMinutes()
  const seconds = present.getSeconds()

  const clockHTML = `
      <span>${String(hours).length === 1 ? `0${hours}`: hours}:</span>
      <span>${String(minutes).length === 1 ? `0${minutes}` : minutes}:</span>
      <span>${String(seconds).length === 1 ? `0${seconds}` : seconds}</span>
  `
  clockContainer.innerHTML = clockHTML
}

setInterval(updateClock, 1000)

**Comment by Roger-Melo** [comment]
Boa @renarfreitas rumo à fluência! 🔥
