### ISSUE TITLE
Etapa 07, Aplicação: Quiz Interativo - Exercício-01 

### ISSUE THREAD

**Issue by brenoSSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#48]
Oi, roger nesse exercício vc pediu pra implementar tudo que foi aprendido pra desenvolver um quiz interativo e subir ele no git e deixar o link do repositório na issue. Aqui está o meu:

https://github.com/brenoSSilva/quiz_interativo

**- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;**
  R: Ter paciência com o Boostrap

**- Quais foram as suas menores dificuldades durante a execução desse exercício.**
   R: Tirando o Boostrap toda implementação foi tranquila, sem dificuldades.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Breno.

Passando rapidinho apenas para dizer que li a issue.

Estou sem meu computador hoje. Tive que enviá-lo para a assistência técnica para limparem a poeira interna da CPU e gabinete. Havia um certo tempo que não fazia isso.

Amanhã devo pegá-lo de volta e olharei o código e lhe responderei com calma, combinado? =)

**Comment by brenoSSilva** [comment]
Combinado teacher

Em qui, 24 de set de 2020 22:27, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Oi Breno.

Um imprevisto aconteceu e ainda não peguei o computador hoje.

Amanhã, assim que eu pegá-lo, olharei p código com calma, combinado?

**Comment by Roger-Melo** [comment]
Oi Breno! Legal que está pegando bem a implementação.

O visual do quiz ficou da hora =)

Tome cuidado com a [quantidade de linhas em branco](https://github.com/brenoSSilva/quiz_interativo/blob/a2793d2467daa92ca245819e0e07c1a93a628264/assets/js/app.js#L29-L32). O propósito delas é separar, visualmente, partes do código que fazem ações semelhantes. Apenas uma linha é necessária para separar uma parte da outra.

Um problema que tive foi não perceber o input no topo antes de marcar as respostas do quiz. E depois que enviei o form, vi o input, preenchi e enviei novamente, mas nada aconteceu. Então seria legal deixar explícito que a inserção do username é obrigatória. Talvez um "Insira seu username" acima do input pra começar... tem que testar xD

Em etapas mais avançadas do curso, iremos falar sobre estratégias de como a aplicação deve responder quando o usuário faz coisas inesperadas. Como não preencher um input, por exemplo.

Observe também que, no código abaixo, o parâmetro `array` não está sendo usado dentro da função:

```javascript
playerAnswers.forEach((answer, index, array) => {
  if(answer === correctAnswers[index]){
    player.score += 10
  }
})
```

Então nesse caso, não é necessário declará-lo =)

No mais, é isso aí cara! Parabéns pelo esforço e por implementar uma feature à mais na aplicação (input)! =D

@brenoSSilva

**Comment by brenoSSilva** [comment]
Obrigado pelo feedback Roger, e por toda atenção à atividade, eu irei tomar
cuidado com as linhas em branco e vou ficar atento as próximas aulas
relacionadas a atitudes inesperadas dos usuários, com relação ao parâmetro
array que não tá sendo usado é porque eu sempre coloco esses três
parâmetros no forEach pra não esquecer deles, como eu não usei eu deveria
mesmo tira-los. Mais uma vez muito obrigado

Em sáb, 26 de set de 2020 16:58, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal Breno! Essa evolução do código é natural. Primeiro implementamos o código, depois melhoramos a qualidade dele =)

Por agora vou fechar a issue, mas no que precisar é só abrir uma nova =D
