### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4805]
Tipos primitivos               Tipos de referência

    - Numbers                      - Todos os tipos de objetos
    - Strings                         - Objetos literais
    - Booleans                        - Arrays
    - Null                            - Funções
    - Undefined                       - Datas
    - Symbol                          - Todos os outros objetos
    - BigInt

A diferença entre eles está na forma como são armazenados na memória.

Tipos primitivos

	Quando um tipo primitivo é criado (string ou número por exemplo) e recebe uma atribuição de valor.
	O valor atribuido é armazenado numa parte da memória chamado stack (pilha).
	A stack é uma pilha de diferentes valores na memória e esses valores podem ser acessados rapidamente quando necessário.
	Contudo, o espaço na stack é limitado.
	
Tipos de referência

	Quando um tipo de referência é criado, ele é armazenado em outra parte da memória chamado heap (amontoado).
	O heap tem mais espaço disponível para armazenar objetos maiores.
	Contudo, é um pouco mais lento.
	Quando um objeto é criado, ele é adicionado na heap. Ao atribuií-lo a uma variável, é criado um ponteiro que referencia o objeto que está na heap.
	Quando um outro objeto é criado, mas como base no anterior (veja exemplo abaixo), ele não é criado na heap.
	Isso significa que ele terá o mesmo ponteiro de referencia do objeto anterior.
	Então qualquer valor que for alterado tanto no objeto anterior quanto no novo, afetará ambos. 
	Por isso é preciso ter cuidado evitando ao máximo esse tipo de criação. Utilizando-o em casos muito específicos onde não tenha problema essa 
	reatribuição de valores mutua.

```js		
// valores primitivos
	let scoreOne = 50
	let scoreTwo = scoreOne
	
	console.log(`scoreOne: ${scoreTwo} | scoreTwo: ${scoreTwo}`)
	
	scoreOne = 100
	
	console.log(`scoreOne: ${scoreTwo} | scoreTwo: ${scoreTwo}`)
	
// valores de referência
	let userOne = { name: 'Adriano', age: 46 }
	let userTwo = userOne
	
	console.log(`userOne: ${userTwo} | userTwo: ${userTwo}`)
	
	userOne.age = 36
	
	console.log(`userOne: ${userTwo} | userTwo: ${userTwo}`)
```

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano rumo à fluência! 🔥
