### ISSUE TITLE
Resumo da Aula - 03-07 da etapa 14 (2) - prototypes

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#4806]
```js
function Student(name, email){
     this.name = name
     this.email = email
}

Student.prototype.login = function(){
      return `${this.name}` 
}

const jansen = new Student('Jansen', 'jansen@email.com')
console.log(jansen)
```
Quando uma função construtora é utilizada, para declarar os métodos no `prototype` do objeto que ela cria, 
é preciso declarar os métodos fora da função construtora.

Quando classes são utitlizadas, o métodos não são declarados fora da classe.

```js
class Student{
    constructor(name, email){
        this.name = name
        this.email = email
    }

    comment(){ 
        return `${this.name} comentou`
    }
}

const jansen = new Student('Jansen', 'jansen@email.com')
console.log(jansen.comment()) 
console.log(jansen) 
```
![image](https://user-images.githubusercontent.com/92958989/186997262-865acf6a-394f-4c72-9f08-313cab03a747.png)

O método comment está inserido no `prototype`, ou seja, classes fazem a atribuição ao 
`prototype` dos objetos automaticamente, então não é preciso declarar diretamente os métodos
no `prototype` dos objetos como quando são as funções construtoras são utilizadas.

Se esquecer da propriedade `prototype` na hora de declarar um método no `prototype`?

Se uma propriedade for declarada numa função construtora e atribuir uma função
diretamente para essa propriedade, estará sendo declarado um método estático. 
Método estático é um método que ao invés de ser declarado no `prototype` dos objetos
que a função construtora cria é declarado diretamente na função construtora e obviamente
é invocado através da referência da função construtora.

Quando vai ser útil fazer a declaração de um método estático ao invés de declarar
  um método no prototype dos objetos?
    - Vai ser útil quando for preciso declarar um método utilitário.
    - Método utilitário é um método que pode ser útil em situações frequentes na aplicação.
 
Exemplo: 
Declarando um método estático na função construtora `Student` e esse método vai formatar a `string`
para que seja armazenada num banco de dados e por algum motivo essa string deve ser armazenada 
com todos os caracteres maiúsculos e com underscores ao invés de espaços em branco.

```js
function Student(name, email){
     this.name = name
     this.email = email
}

Student.formatToDataBase = function(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}
/*
 Como esse método é estático ao invés de ser declarado no prototype dos objetos que a função construtora
 cria, como a função construtora Student também é um objeto, se abaixo inserir um console.log()... 
*/

const jansen = new Student('Jansen', 'jansen@email.com')
console.log(Student.formatToDataBase('string para banco de dados')) //STRING_PARA_BANCO_DE_DADOS
```
E se investigar um dos objetos criados pela função construtora, esse método não existe no `prototype`,
muito menos no próprio objeto, pois é um método estático, ele só existe na função construtora.

![image](https://user-images.githubusercontent.com/92958989/187000180-04d4eb37-0d89-4b64-910f-5c39987bcff1.png)

Para visualizar o método `Student` como objeto, pode ser usado o método `dir` do `console` 

`console.dir(Student)`

![image](https://user-images.githubusercontent.com/92958989/187000544-2c8ece48-02e9-4ac0-b0f4-ac2f0a47515f.png)

Será exibido as propriedades e métodos que essa função construtora tem e uma dessas propriedades é o método
`formatToDataBase`.

```js
class Student{
     constructor(name, email){
         this.name = name
         this.email = email
     }

     comment(){ 
         return `${this.name} comentou`
     }
    
   //Declarando um método estático na classe
    static formatToDataBase(aString){
     return aString.toUpperCase().replaceAll(' ', '_')
    }
}

const jansen = new Student('Jansen', 'jansen@email.com')
console.log(Student.formatToDataBase('string para banco de dados'))
console.dir(Student)
```
![image](https://user-images.githubusercontent.com/92958989/187001130-b43bfd9a-0428-478d-b528-9e0e41bcfcdc.png)

O `formatToDataBase` está declarado no objeto ao invés de ser declarado nos objetos que a classe cria.

![image](https://user-images.githubusercontent.com/92958989/187005770-d7a71fdd-0f91-4154-a946-d23b1f2d5b9b.png)

O `formatToDataBase` tem uma propriedade `name` que armazena o nome do método, ou se for executado no `console.log()`
a propriedade `formatToDataBase.name`, a string com o nome do método é retornada:

`console.log(Student.formatToDataBase.name) //formatToDataBase`.

Porém, o mesmo não acontece numa função construtora.

```js
function Student(name, email){
     this.name = name
     this.email = email
}

Student.formatToDataBase = function(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}

const jansen = new Student('Jansen', 'jansen@email.com')
console.log(Student.formatToDataBase.name) 
```
A propriedade do método armazena uma `string` vazia, ou seja, quando um método é declarado a sintaxe
de abreviação de function declaration:  

```js
static formatToDataBase(aString){
     return aString.toUpperCase().replaceAll(' ', '_')
}
```
o nome do método - `formatToDataBase` - é automaticamente atribuído a propriedade `name` dele. 

Mas quando o método com essa sintaxe de function declaration:
```js
Student.prototype.login = function(){
    return `${this.name} fez login`
}
```
Está sendo declarado explicitamente que a função não tem nome, é anônima. Se executar `Student.formatToDataBase` no `console.dir()`:
`console.dir(Student.formatToDataBase)`

![image](https://user-images.githubusercontent.com/92958989/187006909-b0bff261-b7aa-4ae5-99b3-b88727fdc153.png)

A propriedade `name` da função recebeu uma `string` vazia.

```js
Student.formatToDataBase = function formatToDataBase(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}
```

![image](https://user-images.githubusercontent.com/92958989/187007320-16ca0e44-e52d-4860-8158-77d3e64ac914.png)

A propriedade `name` agora armazena o nome de função.

Não é recomendado em métodos que usam function declarations sejam anônimos.

Métodos estáticos:
 ```js
Student.formatToDataBase = function formatToDataBase(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}
```

Podem ser substituídos por simples funções:
```js
function formatToDataBase(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}
```

**Comment by Jansen-Muniz** [comment]
é quase uma documentação do MDN kkkkk

**Comment by Roger-Melo** [comment]
Boa @Jansen-Muniz rumo à fluência! 🔥
