### ISSUE TITLE
Resumo da Aula O que são objetos - Aula 01-02 da etapa 04

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4810]
Para explicar o que é um objeto em JS podemos traçar um paralelo com objetos do mundo real, no mundo real objetos tem algumas características que podemos chamar de propriedades, e eles tem alguma ação disponível para ser executada neles.

Ex de propriedade e ação usando celular.

Propriedades 
Tamanho, cor, modelo.

Ações
Fazer ligações, tocar musicas, tirar fotos.

Em JS um objeto também tem características que vamos chamar de propriedades e ações que vamos chamar de métodos. Ex:

Um usuário de uma aplicação web por exemplo pode ser um objeto user que possui como propriedades: E-mail, nome do usuário, e ele também pode executar algumas ações os métodos, um método de login ou logout.

Objetos em JS vão possibilitar que criemos estruturas de dados que representam certos elementos de nossos códigos e das nossas aplicações web, o JS também possui alguns objetos acoplados nele que iremos usar como math e o date. Mas também iremos usar os nossos próprios objetos que iremos criar, existem inúmeras maneiras de se criar um objeto em JS e nessa etapa iremos estudar como criar objetos individuais também conhecidos como objetos literais.

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
