### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#4811]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/ElaineDelgado/exchange-rate-app

### Maiores dificuldades durante a implementação

Maior dificuldade foi conseguir obter os resultados com a mudança de valor do primeiro select, 
precisei assistir à correção algumas vezes pra conseguir fazer depois. 
Isolar código em funções de responsabilidade  única.

### Menores dificuldades durante a implementação

Obter os resultados do primeiro request (quando a  aplicação inicia);
Mostrar os resultados para o usuário;
Manipular os resultados com evento disparado no segundo select (currency-one);
Html e CSS da aplicação.

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado. 

Seu código está bom, tenho poucas observações a fazer. Acho que essa é uma das análises em que tive menos trabalho hahah.

Há algumas pequenas sugestões de ajustes que vc pode implementar se fizer sentido pra vc.

Dentro da função `init`, a expressão do `await` foi envolvida entre parênteses, mas eles não são necessários. Vc colocou pq acha que fica mais legível?

---

### Return early

Se achar que faz sentido não invocar `showInitialInfo` dentro do bloco de um if, o if pode ser um return early:

```javascript
// antes
const init = async () => {
  // ...
  if (exchangeRate && exchangeRate.conversion_rates) {
    showInitialInfo(exchangeRate)
  }
}
```

```javascript
// depois
const init = async () => {
  // ...
  if (!exchangeRate || !exchangeRate.conversion_rates) {
    return
  }

  showInitialInfo(exchangeRate)
}
```

O interessante disso, na minha opinião técnica, é que vc coloca menos código dentro de bloco. E devido à invocação de `showInitialInfo` não estar mais dentro de um bloco, o seu código fica com menos níveis de indentação, o que pode ser um indicativo de um código menos complexo e com menos ramificações.

---

### Currying

Observe que as invocações de `getOptions` estão repetindo o argumento `conversion_rates`:

```javascript
currencyOneEl.innerHTML = getOptions('USD', conversion_rates)
currencyTwoEl.innerHTML = getOptions('BRL', conversion_rates)
```

Isso pode ser evitado se vc usar uma técnica de programação funcional chamada `currying`.

Essa técnica funciona da seguinte forma...

Em linguagens puramente funcionais, como o Haskell por exemplo, funções podem receber apenas um único argumento/parâmetro. Se a função precisa receber mais de um parâmetro, ao invés de receber 2 parâmetros de uma só vez, ela recebe um parâmetro e retorna uma nova função que recebe o segundo parâmetro.

Um dos benefícios disso é que o valor armazenado do segundo parâmetro ficará "enclausurado" (closure) e será usado na função que foi retornada. 

Traduzindo isso para o seu caso, ao invés de receber os parâmetros `selectedCurrency` e `conversion_rates`, a `getOptions` irá receber apenas o parâmetro que vc quer abstrair, que no caso é o `conversion_rates`:

```javascript
// antes
const getOptions = (selectedCurrency, conversion_rates) => {
  // ...
}
```

```javascript
// depois
const getOptions = (conversion_rates) => {
  // ...
}
```

Feito isso, ao invés de ser invocada 1x, `getOptions` será invocada apenas 1x, recebendo `conversion_rates` como argumento:

```javascript
const x = getOptions(conversion_rates)
```

Nomeei a const como `x` apenas para não pensarmos em nomes agora. Daqui a pouco vai fazer sentido.

Nesse ponto, o importante agora é fazer com que a invocação de `getOptions` retorne uma nova função. O corpo dessa função é exatamente o mesmo que a `getOptions` tinha:

```javascript
const getOptions = (conversion_rates) => () => {
  // aqui dentro, tudo continua a mesma coisa
}
```

Só que agora, vc pode fazer que essa função que getOptions está retornando tenha um parâmetro `selectedCurrency`:

```javascript
const getOptions = (conversion_rates) => (selectedCurrency) => {
  // ...
}
```

Lembra que dentro da `showInitialInfo`, o retorno da invocação de `getOptions` está sendo armazenando na const `x`?

Se vc olhar essa const no console, verá que ela está armazenando a função que `getOptions` retornou:

```javascript
const showInitialInfo = ({ conversion_rates }) => {
  const x = getOptions(conversion_rates)
  console.log(x) // (selectedCurrency) => { ... }
  // ...
}
```

Se `x` armazena essa função, vc pode invocar `x` inserindo o código da moeda como argumento:

```javascript
console.log(x('USD')) // <option selected>USD</option><option >AED</option>...
```

Isso significa que agora, `x` pode ser invocada e retornar para as `.innerHTML` os valores que elas precisam:

```javascript
const x = getOptions(conversion_rates)

currencyOneEl.innerHTML = x('USD')
currencyTwoEl.innerHTML = x('BRL')
```

Nomear uma curried function como a `getOptions` não é intuitivo. Talvez esse seja um dos pontos fracos dessa técnica. Mas eu renomearia `getOptions` como `getOptionsFn` (Fn é uma abreviação de "Function") e `x` como `getOptions`:

```javascript
const getOptionsFn = (conversion_rates) => (selectedCurrency) => {
  // ...
}

const showInitialInfo = ({ conversion_rates }) => {
  const getOptions = getOptionsFn(conversion_rates)

  currencyOneEl.innerHTML = getOptions('USD')
  currencyTwoEl.innerHTML = getOptions('BRL')
  // ...
}
```

Se quiser, vc também pode deixar mais claro o que a string que está sendo inserida como argumento de `getOptions` significa. Basta usar uma propriedade de objeto que descreve o valor:

```javascript
const getOptionsFn = (conversion_rates) => ({ selectedCurrency }) => {
  // ...
}

currencyOneEl.innerHTML = getOptions({ selectedCurrency: 'USD' })
currencyTwoEl.innerHTML = getOptions({ selectedCurrency: 'BRL' })
```

Sacou a ideia?

Se quiser ver uma aplicação dessa técnica em vídeo, vc pode baixar [esse vídeo](https://drive.google.com/file/d/1QThTnf08dWk0wACqiQC35FiB4xVllAxb/view?usp=sharing) onde mostro a técnica mais ou menos aos 16:38.

---

Entendi que foi preciso assistir a correção para conseguir fazer depois. Mas se certifique-se de que vc consegue construir a aplicação sozinha, ok?

As observações fizeram sentido?

**Comment by ElaineDelgado** [comment]
Bom dia, professor, espero que esteja bem!!

As observações fizeram sentido sim.

Os parênteses no await dentro da init( ) não foram intencionais, provavelmente esqueci de remover! -.-' Mas já acertei aqui.

A dica do Return early foi legal porque eu não gosto de deixar retorno de função dentro de if, mas eu tinha esquecido esquecido desse detalhe e acabou fazendo do outro jeito. Já consertei aqui.

Bacana também a ideia da Curried function, acho que já tínhamos visto durante o curso mas não foi citado que tinha esse nome.
Li a explicação, vi o vídeo, e depois de vários console.log's entendi como funciona e implementei na aplicação.

Obrigada pela avaliação e pelas dicas!!

**Comment by Roger-Melo** [comment]
> ### A dica do Return early foi legal porque eu não gosto de deixar retorno de função dentro de if, mas eu tinha esquecido esquecido desse detalhe e acabou fazendo do outro jeito. Já consertei aqui.

Não é retorno de função.

A `showInitialInfo` não retorna valor, independente se for invocada dentro ou fora do `if` =)

@ElaineDelgado

**Comment by Roger-Melo** [comment]
Boa! 

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
