### ISSUE TITLE
Resumo da Aula 3 escopos em JavaScript que você deve conhecer - Aula 01-03 da etapa 05

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4814]
Escopo é a visibilidade de uma variável, 03 tipos importantes de escopos:
- Escopo de Funções;
- Escopo de Blocos;
- Escopo léxico. 

Lembrando que existem escopos globais e escopos locais, se uma const for declarada dentro de um escopo local, ao tentar acessar a const fora do escopo local vai dar erro pois a mesma foi criada dentro de um escopo local, para ser acessado apenas dentro daquele escopo. Já a declaração em escopo global, pode ser acessada dentro de um ambiente local ou em um ambiente externo e a mesma resultara no resultado da const.

**Comment by Roger-Melo** [comment]
Boa @EdsonAjjunior rumo à fluência! 🔥
