### ISSUE TITLE
Resumo da Aula 01 - 04 - Adicionando Métodos da etapa 04

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4818]
### Adicionando métodos

```jsx
let user = {
    name: 'João',
    age: 31,
    email: 'joaocardoso@gmail.com',
    city: 'Sao Paulo',
    blogPosts: ['Empadao de frango', '4 receitas de pure de batata'],
    login: function () {
        console.log('Usuário logado!')
    },
    logout: function () {
        console.log('Usuário deslogado!')
    }
}

user.login()

user.logout()
```

Podemos adicionar métodos dentro dos objetos, métodos são funções que são criadas dentro de objetos, elas são criadas para executar alguma ação, este método pode ser acessado através da notação de ponto. Lembrando que método é uma função, porem dentro de um objeto ela tem outro nome. As funções e os métodos tem a mesma usabilidade.

**Comment by Roger-Melo** [comment]
Boa @fabioromagnoli99 rumo à fluência! 🔥
