### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4823]
Existem outras maneiras para selecionar alguns itens de maneira semelhante ao query selector, a primeira é através da identificação do id que queremos localizar, a segunda é através da identificação do nome da classe e a terceira é através do nome da tag da classe. Esses são três maneiras diferentes de selecionar e fazer queries no DOM.

**Comment by Roger-Melo** [comment]
Boa @EdsonAjjunior rumo à fluência! 🔥
