### ISSUE TITLE
Resumo da Aula 03-08 da etapa 14 - Herança prototipal

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#4824]
```js
/*
  Quando a palavra-chave class é usada e quero criar uma subclasse, ou seja, quero criar uma
  classe que herda métodos e da classe pai mas que também tem propriedades e métodos únicos
  dela, uso a palavra-chave extends e a invocação do super.
*/

//Herança com uma função construtora

function Student (name, email){
  this.name = name
  this.email = email
}

Student.prototype.comment = function comment(){
  return `${this.name} comentou`
}

function TeacherAssistent(name, email){
  /*
    Usando funções construtoras, para fazer com que TeacherAssistent herde proprieades e 
    métodos da função construtora Student, será invocado o método call() - para invocar uma 
    determinada função e forçar que o this desta função armazene o valor desejado, que nesse caso
    foi o this da TeacherAssistent.
    Para fazer com que os parâmetros da Student - name, email - receber os valores que os parâmetros 
    da TeacherAssistent - name, email - receberam, serão declarados no método call() 
    do segundo argumento em diante os valores que a função Student deve receber como parâmetros - name, email. 
  */
 Student.call(this, name, email)
}

```
![image](https://user-images.githubusercontent.com/92958989/187297520-e9e41df7-0dd0-42ae-9ed4-f3e0a612a580.png)

Agora as propriedades do objeto que a `TeacherAssistent` criou, contém os valores inseridos na invocação do `call()`

```js
function Student (name, email){
  this.name = name
  this.email = email
}

Student.prototype.comment = function comment(){
  return `${this.name} comentou`
}

function TeacherAssistent(name, email, scheduledWeekPost){
 Student.call(this, name, email)

 /*
  Se eu quiser que o objeto que a TeacherAssistent criou tenha propriedades e métodos únicos. 
  Para criar uma propriedade única desse objeto que representa que o monitor agendou os posts
  da semana, por exemplo:   
*/
 this.scheduledWeekPost = scheduledWeekPost 
}
const jansen = new Student('Jansen', 'jansen@email.com')
const roger = new TeacherAssistent('Roger', 'rogermelo@email.com', false)
console.log(jansen, roger)
```  
![image](https://user-images.githubusercontent.com/92958989/187299754-5f435b8f-2889-4312-88ca-4119c7c96aab.png)

O objeto criado pela Student não tem uma propriedade `scheduledWeekPost`, porque essa propriedade é única
dos objetos criados pela `TeacherAssistent` 

```js
function Student (name, email){
  this.name = name
  this.email = email
}

Student.prototype.comment = function comment(){
  return `${this.name} comentou`
}

function TeacherAssistent(name, email, scheduledWeekPost){  
 Student.call(this, name, email)

 this.scheduledWeekPost = scheduledWeekPost 
}

/*
  Se eu quiser que os objetos cria tenham métodos únicos, esses métodos serão declarados 
  no prototype da função construtora:
*/
  TeacherAssistent.prototype.giveBadge = function giveBadge({ name }){
    return `${this.name} deu uma medalha para ${name}`
  }

const jansen = new Student('Jansen', 'jansen@email.com')
const roger = new TeacherAssistent('Roger', 'rogermelo@email.com', false)
console.log(roger.giveBadge(jansen))
```
![image](https://user-images.githubusercontent.com/92958989/187305658-c1463efb-0898-4ea7-a899-96501c8c2262.png)

A `string` que a invocação do método retornou e no `prototype` do objeto que `TeacherAssistent` criou 
tem o método `giveBadge()` no `prototype`.  

![image](https://user-images.githubusercontent.com/92958989/187306922-0eb6018d-d911-42cf-862c-9fdd0aa50944.png)

Mesmo que a `TeacherAssistent` tenha herdado as propriedades da `Student`, o `prototype` 
que desse objeto que a `TeacherAssistent` criou não tem os métodos `comment` e `login`, ou seja, 
no `prototype` do objeto que a `TeacherAssistent` criou não existem propriedades que apontam para os métodos 
`comment` e `login`.

Como serão criadas essas propriedades e fazer elas apontarem para os métodos que estão no `prototype` dos
objetos que a função `Student` cria? Ao invés de criar essas propriedades novamente, posso fazer com que o `prototype`
dos objetos da função `Student` seja também o `prototype` dos objetos que a `TeacherAssistent` cria. Isso será feito usando
um método chamado object.create().

```js
function Student (name, email){
  this.name = name
  this.email = email
}

Student.prototype.login = function login(){
    return `${this.name} fez login`
}

Student.prototype.comment = function comment(){
  return `${this.name} comentou`
}

function TeacherAssistent(name, email, scheduledWeekPost){  
 Student.call(this, name, email)
 this.scheduledWeekPost = scheduledWeekPost  
}

TeacherAssistent.prototype = Object.create(Student.prototype)
/* 
 Object.create(Student.prototype) - essa invocação vai criar um novo objeto, que contém as propriedades
 do prototype dos objetos que a Student cria, esse objeto está sendo recebido como prototype dos objetos
 que a TeacherAssistent cria 
*/

TeacherAssistent.prototype.giveBadge = function giveBadge({ name }){
  return `${this.name} deu uma medalha para ${name}`
}

const jansen = new Student('Jansen', 'jansen@email.com')
const roger = new TeacherAssistent('Roger', 'rogermelo@email.com', false)

console.log(jansen, roger)
console.log(roger.giveBadge(jansen))
```
![image](https://user-images.githubusercontent.com/92958989/187316170-93af94d6-5265-476b-b55e-f682474fb7bf.png)

Se olhar o prototype desse objeto criado pela `TeacherAssistent` - `[[Prototype]]: Student` - ele contém o método
já adicionado antes e se investigar o segundo nível da cadeia de prototypes - `[[Prototype]]: Object` - encontro os métodos
que queria que estivessem disponíveis - `comment` e `login` nos objetos que a `TeacherAssistent` criar.

![image](https://user-images.githubusercontent.com/92958989/187317303-a4245330-b0df-478d-bd1f-0da087688245.png)

Quando invoco `arthurSouza.login()`(objeto1) se o método `login` não existe no próprio objeto, o método vai ser buscado no 
`prototype`(objeto2) do objeto, se o `prototype` do objeto não contém esse método, o método vai ser buscado no `prototype`
do `prototype`(objeto 3) do objeto e como o método foi encontrado no `prototype`(objeto 3), o método é executado no 
objeto(objeto 1), ou seja, através dessa cadeia de protótipos, o objeto arthurSouza, pode acessar e executar métodos que 
foram declarados no último `prototype` da cadeia, que é o `prototype` de `object` e esse `prototype` de `object` é o objeto
o qual, qualquer objeto em JS vai herdar propriedades, esse `prototype` sempre vai ser o útimo `prototype` na cadeia de 
`prototypes`.

Quando vai ser necessário usar classes ou funções construtoras? 
Quando precisar criar objetos específicos que compartilham um método, usar classes nesse caso,
vai ajudar a economizar memória e classes são mais simples que funções construtoras.
As funções constrututoras eram a norma antes da palavra-chave `class` na linguagem.

Vai ser preciso usar classes quando for necessário fazer herança, quando uma biblioteca estiver
sendo desenvolvida, em que os objetos precisam ter métodos compartilhados e quando precisar 
economizar uma quantidade quase insignificativa de memória.

**Comment by Roger-Melo** [comment]
Boa @Jansen-Muniz rumo à fluência! 🔥
