### ISSUE TITLE
Issues GitHub

### ISSUE THREAD

**Issue by LeandroAzevedo-1** [roger-melo-treinamentos/curso-de-js-roger-melo#4826]
### Etapa da aula

1

### Nome da aula

01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928

### Descreva a dúvida

@Roger-Melo
Boa noite Roger tudo bem ? 
Minha dúvida é sobre as Issues do github. 
Onde consigo acessar todos os meus resumos, desde do primeiro ?

**Comment by Roger-Melo** [comment]
Olá @LeandroAzevedo-1. 

Na [página de issues](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues), clica no item "author" e selecione seu nome. Ao fazer isso, vc estará filtrando por todas as issues que vc abriu. Aí é só vc clicar em "closed" para ver suas issues fechadas. Provavelmente seus resumos estarão nessa aba de issues fechadas =)

**Comment by LeandroAzevedo-1** [comment]
Onde encontro item "author" ? Não estou encontrando.

**Comment by LeandroAzevedo-1** [comment]
Opa, encontrei. 
Obrigado.

**Comment by Roger-Melo** [comment]
Show. No que tiver dúvidas, é só abrir uma nova issue =)
