### ISSUE TITLE
Resumo da Aula: Template HTML e checando as respostas, Aula 01-03 etapa 07

### ISSUE THREAD

**Issue by Morais465** [roger-melo-treinamentos/curso-de-js-roger-melo#4836]
No nosso Quiz todas as respostas corretas estão com o B maiúsculo, e como são 4 perguntas, faremos um array com 4 respostas. Colocarei os 4 'As'no array e se acaso quiser mudar a ordem terei que modificar o array tmbm, obteremos o form com o query, usaremos um escutador com event, para evitar que a página seja recarregada no envio do from, crio uma let 0 que será a parte para soma, faço um array obtendo os valores das valores 'B' e verifico com console.log e envio o form, vejo que obtenho todos os B's.
Fazer o array ser iterado e verificar qual item atual corresponde ao item que esta na mesma posição que está no array de respostas,  crio um if que compara se o item e o index é igual ao que esta sendo iterado, e coloco index como segundo parâmetro do forEach, e adiciono ao score a cada resposta certa, 25 Pt.

**Comment by Roger-Melo** [comment]
Boa @Morais465 rumo à fluência! 🔥
