### ISSUE TITLE
Aplicação: [Quiz]: Como refatorar um if dentro do evento de submit?

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#4840]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/aecio-neto/portfolio/tree/main/Projetos%20Javascript/06%20-%20Quiz

### Maiores dificuldades durante a implementação

Minha maior dificuldade foi checar se todas as respostas foram respondidas antes do envio (o que é bem simples, mas demorei para entender). 

Refatorar o código é algo que tenho dificuldade também. 

Minha dúvida: há uma forma de refatorar um if dentro do submit? Isso seria transformado em uma função? 

```js
   const questionsNotAnswered = userAnswers.includes('')
   if(questionsNotAnswered) {
    userSubmitAlert.classList.remove('d-none')
    return
  }
```

A ideia dessa parte do código é avisar ao usuário que ele precisa responder todo o questionário antes de visualizar o resultado. 

### Menores dificuldades durante a implementação

Calcular e apresentar o score.

**Comment by MivlaM** [comment]
Olá @aecio-neto!

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te informar sobre as aplicações.

Apenas quem se matriculou até às 8:15h tem o bônus de análise de aplicações, e pelo que vi, sua matrícula foi feita às 08:38h.

O que vc pode fazer neste caso é dar uma olhada nas [análises que fiz dessa aplicação](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=is%3Aissue+quiz+label%3A%F0%9F%94%A5aplica%C3%A7%C3%A3o+is%3AclosedI). Elas são públicas =)

E claro, qualquer dúvida que tiver, é só dar o toque =)

**Comment by Roger-Melo** [comment]
Olá @aecio-neto. 

Se a issue for aberta com a label `🔥aplicação`, a equipe irá entender que vc está solicitando uma análise de aplicação (como as do link que o Maykell disponibilizou no comentário acima).

Quando precisar tirar dúvidas, abra uma issue com a label `❓ dúvida`, da forma que foi mostrada aqui na [Aula Mais Importante do CJRM](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/2186928). Isso facilita o nosso gerenciamento de issues por aqui =)
