### ISSUE TITLE
Resumo da Aula 02 - 03 - A palavra chave this da etapa 04

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4842]
### A palavra chave this

```jsx
let user = {
    name: 'Joao',
    age: 31,
    email: 'joaocardoso@gmail.com',
    city: 'Sao Paulo',
    blogPosts: ['Empadao de frango', '4 receitas de pure de batata'],
    login: function () {
        console.log('Usuario logado!')
    },
    logout: function () {
        console.log('Usuario deslogado!')
    },
    logBlogPosts () {
	console.log(`${this.name} escreveu os seguintes posts:`)

    this.blogPosts.forEach(post => {
    console.log(post)
})

user.logBlogPosts()

```

quando for usar o this para declarar uma função nunca usar arrow function => ( ) sempre usar function ( ) {}

A palavra this é um objeto de contexto, ele representa o contexto de código atual que está sendo executado, e dependendo de onde e como usamos o this, ele pode mudar de valor. Ao ser acessado sem notação de ponto e direcionamento no escopo global, ele vai usar todo o escopo global e vai reproduzir window. O this não tem utilidade chamando ele junto com uma arrow function, normalmente utilizamos function declaration para utilizarmos o this.

**Comment by Roger-Melo** [comment]
Boa @fabioromagnoli99 rumo à fluência! 🔥
