### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4844]
Estilos podem ser modificados atraves do JS utilizando setAttribute( ), porem este ira sobrescrever tudo caso haja mais de um estilo.
Para adicionar e ou modificar um estilo sem afetar os demais uma opcao melhor e utilizar a propriedade (.style), e nele deve ser encadeado a propriedade em questao.
Ex:
     title.style.margin = '50px'

OBS: Em caso de propriedades cujo nome possui duas ou mais palavras deve-se escrever em camelCase.
Ex:
      font-size: 10px;
       title.style.fontSize = '50px'

**Comment by Roger-Melo** [comment]
Boa @YukOnRails rumo à fluência! 🔥
