### ISSUE TITLE
Resumo da Aula utras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4849]
HTMLCollection representa uma lista genérica de elementos
Ao contrário de um NodeList, não podemos utilizar um forEach em um HTMLCollection

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano rumo à fluência! 🔥
