### ISSUE TITLE
Como refatorar um if dentro de um evento de submit? 

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#4852]
### Etapa da aula

7

### Nome da aula

Exercícios da Aula 2

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/967841

### Descreva a dúvida

O código abaixo avalia se há questões não respondidas no Quiz. Se true, um aviso é mostrado ao usuário. Se false, o form é enviado normalmente. 

```js
   const questionsNotAnswered = userAnswers.includes('')
   if(questionsNotAnswered) {
    userSubmitAlert.classList.remove('d-none')
    return
  }
```

Link do código completo: 
https://github.com/aecio-neto/portfolio/tree/main/Projetos%20Javascript/06%20-%20Quiz

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @aecio-neto!

> ## Como refatorar um if dentro de um evento de submit?

Antes de explicar sobre a refatoração nesse caso específico, quero que você se atente e entenda os seguintes comportamentos do código.

Sendo `userAnswers` um array de respostas, ou seja um array de strings, você pode perceber que ele age de formas diferentes de acordo com a quantidade de itens no array. Quando o array tem apenas um item e você usa o método includes com uma string vazia, `false` é retornado. Mas, quando o array tem mais de um item e um deles é uma string vazia, `true` é retornado. Observe o seguinte, por exemplo:

```js
// Quando o array tem apenas um item, false é retornado

const a = ['oi']

console.log(a.includes('')) // False aparecerá no console
```

```js
// Quando o array tem mais de um item, true é retornado

const b = ['oi', '']

console.log(b.includes('')) // True aparecerá no console
```

Dito isso, algo que é recomendado ao longo do treinamento, quando estamos fazendo a aplicação do quiz, é para que o desenvolvedor deixe as alternativas do quiz marcadas por padrão. Pois tanto por uma questão de usabilidade, quanto como um incentivo para o usuário marcar a resposta que ele acredita que seja a verdadeira. Isso facilita o desenvolvimento dessa aplicação.

Agora, se tratando da refatoração, sua dúvida original, não existe uma relação entre o if estar no callback de um submit. Independente disso, se o if está ou não num callback de submit do form, vão haver situações em que não há uma alternativa "melhor" que usar um if. Por quê? Vejamos as opções para refatorar o if do código, a primeira delas seria por meio de um ternário.

Você também irá aprender mais sobre o ternário nas etapas posteriores do treinamento, mas para você ter uma ideia, se a condição do ternário for verdadeira, o que está após o sinal de ? será retornado, se a condição for falsa, o que está após o sinal de : que será retornada. Qual a diferença de usar um if e um ternário? A primeira delas é a palavra chave `return`, como esse if está sendo usado dentro de uma função, se a condição dentro do if for verdadeira, você quer executar apenas o que está dentro do if e não ler as outras linhas de código fora dele. Com o ternário, isso não seria possível, o ideal seria usar o ternário quando baseado numa condição, você quer executar ações, uma se for `true` e a outra se for `false`. No caso do seu código, se o if for true, o código dentro dele será executado e o `return` impedirá o restante do código da função de ser executado. Se o if for falso, o if não vai ser lido e o restante do código fora do bloco que irá ser lido. Para você adaptar esse trecho de código para ternário, ficaria de forma semelhante a isso:


```js
questionsNotAnswered ? userSubmitAlert.classList.remove('d-none') : null
```

No código acima, o ternário não está em bom uso, ele está retornando `null` para não fazer nada. Lembre-se que seu uso ideal é quando baseado em uma condição, você quer executar a expressão depois de ? se for verdadeira e a depois de : se for falsa. Mas ao mesmo tempo que o ternário precisa desse `null`, vem a questão do `return`. Se você quiser eliminar esse if por um ternário, você não vai ter um `return`. Não tem como você usar o `return` após o ternário, pois ele retornaria o seu valor junto com a invocação das outras funções do resto do código. Ou seja, não é possível usar o operador ternário nesse caso.

Mas então, uma outra ideia seria usar o ternário como argumento do remove.

Nessa composição, se `questionsNotAnswered` for true, o ternário poderia retornar d-none e para a `questionsNotAnswered` retornar um valor falsy, o ternário poderia retornar uma string vazia. Ficaria assim:

```js
userSubmitAlert.classList.remove(questionsNotAnswered ? 'd-none' : '')
```

Porém, nota-se que quando testamos o que o remove retorna quando uma string vazia é inserida como argumento, isso acontece:

```js
userSubmitAlert.classList.remove('') // Um erro é exibido. uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
```

A DOMTokenList retornada pela classList apresenta um erro. Nesse caso, também não é possível usar o ternário como argumento do remove.

Então, por fim, independentemente se o if está ou não dentro de um callback submit, a melhor solução para o seu código seria permanecer usando esse if mesmo. O seu if não está extenso e não tem muitas linhas de código, então eu não vejo uma outra condicional aqui, com uma menor quantidade de linhas e que possa fazer o que o if está fazendo nesse código.

---

Respondi a sua pergunta? Se restar qualquer dúvida é só avisar que te ajudarei =)

**Comment by aecio-neto** [comment]
Questão respondida. Me pareceu a melhor opção mesmo. Já usei o ternário em
outros exercícios, mas não me pareceu uma boa opção aqui.

O mesmo vale para manter todas as alternativas como checked. Penso que a
experiência do usuário ficaria comprometida.

Obrigado pelo esclarecimento.

Em qua., 31 de ago. de 2022 às 12:26, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Show! Vou fechar essa issue e a anterior, se precisar, sinta-se livre para abrir uma nova issue =)
