### ISSUE TITLE
Dúvida relacionada a um projeto real para uma Associação

### ISSUE THREAD

**Issue by dracoalv** [roger-melo-treinamentos/curso-de-js-roger-melo#4853]
### Etapa da aula

15

### Nome da aula

Salvando informações no Firestore - Aula 02-08

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2865381

### Descreva a dúvida

Olá Roger, muito bom dia.

Aceitei um trabalho voluntário para uma associação de crianças carentes onde o projeto consiste em um site informativo contendo um Blog e estou tendo algumas dificuldades relacionadas ao id do documento criado no banco de dados.

A minha intenção é criar um ID sequencial para todo documento, ou então até mesmo o ID gerado automaticamente pelo Firebase, o problema é que eu não consigo usar a referencia do documento e consequentemente seu ID, pois o objeto é inserido antes da declaração da variável que armazena a função de adicionar o doc.

Outro problema é na criação de um slug, pois como se trata de um blog, eu gostaria que o caminho de cada post fosse o seu título, porém formatado para funcionar em uma url.

```js
Exemplo: {
  title: 'Um título',
  slug: 'um-titulo'
}
```

Segue abaixo o código que estou utilizando para capturar a imagem do input de seleção de arquivos no formulário e também o código para adicionar o doc.
```js
const router = useRouter()
 
const handleUpload = async (event: any) => {
  event.preventDefault()
  const file = event.target.image.files[0]
    
  const postImagesRef = ref(storage, `images/${v4()}`)
  const uploadTask = uploadBytesResumable(postImagesRef, file)

  const uploadState = (snapshot: any) => {
    const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100
    console.log(`Upload is ${progress}% done`)

    switch (snapshot.state) {
      case 'paused':
        console.log('Upload is paused')
        break
      case 'running':
        console.log('Upload is running')
        break
    }
  }

  const uploadError = (error: any) => alert(error)
    
  const getUrl = async () => {
    const collectionPosts = collection(db, 'posts')      
    const url = await getDownloadURL(uploadTask.snapshot.ref)

    const postData = {
      id: '',
      image: url,
      title: event.target.title.value,
      slug: '',
      description: event.target.description.value,
      author: 'Luis Guedes',
      date: serverTimestamp()
    }

    const docRef: any = await addDoc(collectionPosts, postData)
    router.push('/dashboard')
  }
    
  uploadTask.on('state_changed', uploadState, uploadError, getUrl)  
}
  ```
  
  ```jsx
  {posts.map(({ item, index }: any) => (
    <li key={index} className='list-none'>
      <Link href={`/relatorios/posts/${item.id}`}>
        <a>
          <BlogCard 
            image={item.image}
            title={item.title}
            description={item.description}
            authorImage={item.authorImage}
            author={item.author}
            date={item.date}
          />
        </a>
      </Link>
    </li>
  ))}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dracoalv! Hj foi um dia atípico por aqui e por isso, ainda não consegui elaborar a resposta. Mas ela já está à caminho, ok? =)

**Comment by dracoalv** [comment]
> Olá @dracoalv! Hj foi um dia atípico por aqui e por isso, ainda não consegui elaborar a resposta. Mas ela já está à caminho, ok? =)

Meu querido, não esquenta, sem pressa alguma, obrigado pelo retorno

**Comment by Roger-Melo** [comment]
Olá @dracoalv!

Não é uma boa ideia usar IDs sequanciais pq vc pode ter problemas de race condition em algum momento. O ideal é usar algo como um UUID. Hoje vc não precisa de lib para gerar IDs aleatórios. No browser, vc pode usar, por exemplo, o método `randomUUID` da propriedade global `crypto`:

- [randomUUID() - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)

```javascript
crypto.randomUUID() // '487db2ac-9fb3-4f98-bb56-0e7da452f7ec' ou algo do tipo
```

☝🏻 retorna UUID na versão 4, que é a mais segura atualmente.

---

Sobre o slug, fazer na mão não é boa ideia pq há várias regras que vc precisa considerar. 

Neste caso, vc pode usar a lib [slugify](https://github.com/simov/slugify) =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
