### ISSUE TITLE
Melhoria no Replace

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4854]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01 - Etapa 04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284

### Descreva a dúvida

Professor poderia verificar minha sugestão para resolução do método replace pois na correção a virgula sempre ficara junto na penúltima posição do array color e quando usamos “e” para separar duas palavras não precisamos da virgula.

```jsx
let car = {
  name: 'Polo',
  brand: 'VW',
  color: ['black', 'red', 'gray'],
  isRunning: false,
  run () {
    this.isRunning = true
    return `"O ${this.name} está em movimento";`
  },
  stop () {
    this.isRunning = false
    return `"O ${this.name} está parado";`
  },
  getColorsMessage () {
    const lastItem = this.color[this.color.length - 1]
    const colors =  this.color.join(', ').replace(`, ${lastItem}`,` e ${lastItem}`)
    return `"O ${this.name} está disponível nas cores: ${colors}.` 
  }
}

// "O Polo está disponível nas cores: black, red e gray."
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @fabioromagnoli99! Podem haver vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento já foi feito, que é fazer funcionar =)

Só fica ligado que geralmente, a forma que eu resolvo os exercícios usa princípios que serão intensificados conforme vc avança no CJRM. Por isso, para se sertificar que vc realmente absorveu também a forma que eu resolvi, recomendo que siga esse [passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/1801661) =)

**Comment by fabioromagnoli99** [comment]
Maravilha, obrigado Roger!
