### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4859]
Para acessar o valor da propriedade no método, usamos a palavra chave this, para que ela faça uma referencia ao objeto user. E como this está referenciando o objeto user, podemos acessar a propriedade blogPosts desse objeto inserindo ponto.blogPosts como no exemplo abaixo. E se salvarmos iremos ver o valor da propriedade blogPosts exibido.

let user = {
    name: 'João',
    age: 31,
    email: 'joaocardoso@gmail.com',
    city: 'São Paulo',
    blogPosts: ['Empadão de Frango', '4 Receitas de Pure de Batata'],
    login: function () {
        console.log('Usuario Logado')
    },
    logout: function () {
        console.log('Usuario Deslogado')    
    },
    logBlogPosts: function () {
        console.log(this.blogPosts)
    }
}

user.logBlogPosts()

Mas o que é essa palavra this? O this é um objeto de contexto, ele representa o contexto no qual o código atual esta sendo executado. E dependendo de onde e como nos usamos o this, seu valor irá mudar. Se usarmos ele por exemplo na raiz do documento, ele ira referenciar o contexto global que é chamado de "window object". Teste o console.log(this) para ver.

Quando invocamos um método da forma no exemplo acima o JS faz com que o valor do this seja o objeto no qual o método esta sendo usado que no caso é o objeto user, então dentro desse método logBlogPosts o this representa o objeto user, e por isso que podemos acessar as propriedades desse objeto. E já que podemos acessar os logBlogPosts podemos iterar sobre eles e exibir eles no console, exemplo abaixo:

    logBlogPosts () {
        
        console.log(`${this.name} escreveu os seguintes posts:`)

        this.blogPosts.forEach((post) => {
            console.log(post)
        })
    }

user.logBlogPosts()

Aqui estamos usando function declaration ao invés de arrow function pois quando usamos uma function declaration como método e invocamos esse metodo o valor que JS atribui ao this é o objeto no qual o método está sendo usado. Que neste caso é o user, se transformarmos essa function em uma arrow function o valor do this irá referenciar window, e um erro será exibido no console por conta dos conflitos de propriedades.
OBSERVAÇÃO, repare como no exemplo acima do forEach a sinxtaxe do método está mais enxuta pois no logBlogPosts os dois pontos e a palavra function foram retirados, essa alteração não muda o código e ajuda a deixa-lo mais legível.

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
