### ISSUE TITLE
Etapa 02, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by Denilson-S-Garcia** [roger-melo-treinamentos/curso-de-js-roger-melo#486]
Professor, no exercício 4 ocorre algo estranho quando coloco o console .log dentro do escopo  do for veja como fica no console:

```
 ["SÃO PAULO"]
 (2) ["SÃO PAULO", "RIO DE JANEIRO"]
 (3) ["SÃO PAULO", "RIO DE JANEIRO", "MINAS GERAIS"]

```
Queria saber, porque ocorre isso, como sei quando colocar dentro ou fora do escopo o console.log?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Denilson.

Na verdade esse é o comportamento esperado.

```javascript
const cities = ['São Paulo', 'Rio de Janeiro', 'Minas Gerais']

let upperCaseCities = []

for (let i = 0; i < cities.length; i++) {
  upperCaseCities.push(cities[i].toUpperCase())
  console.log(upperCaseCities)
}

console.log(upperCaseCities)
```

No código acima, a cada execução do for a expressão `upperCaseCities.push(cities[i].toUpperCase())` está adicionando no array a string na qual a expressão `cities[i]` resulta (o toUpperCase apenas faz essa string ter todos os caracteres maiúsculos). 

Como abaixo dessa primeira linha (que adicionou o item no array) existe a invocação do `console.log(upperCaseCities)`, o valor de `upperCaseCities` é exibido no console a cada execução do `for`.

> Como sei quando colocar dentro ou fora do escopo o console.log

Você irá inserir um `console.log()` dentro do bloco do `for` quando quiser exibir algum valor a cada vez que o `for` é executado.

Se você quiser esperar o for terminar de ser executado para só então exibir algum valor no console, aí sim você invoca o `console.log()` abaixo do `for` (as linhas de código abaixo do `for` só são executadas quando o `for` termina de ser executado).

Apenas para eu não pecar por falta de clareza, vou colocar em uma tabela um panorama geral do que está acontecendo no código acima:

Execuções do for | valor no qual cities[i] resultou | valor de upperCaseCities
:-- | :-: | :-:
1ª execução | 'SÃO PAULO' | ['SÃO PAULO']
2ª execução | 'RIO DE JANEIRO' | ['SÃO PAULO', 'RIO DE JANEIRO']
3ª execução | 'MINAS GERAIS' | ['SÃO PAULO', 'RIO DE JANEIRO', MINAS GERAIS]

Ou seja, no fim das contas, o que as duas linhas dentro do `for` estão fazendo à cada execução é isso:

```javascript
const cities = ['São Paulo', 'Rio de Janeiro', 'Minas Gerais']

let upperCaseCities = []

// adiciona 'SÃO PAULO' no array
upperCaseCities.push(cities[0].toUpperCase())

console.log(upperCaseCities) // ['SÃO PAULO']

// adiciona 'RIO DE JANEIRO' no array
upperCaseCities.push(cities[1].toUpperCase())

console.log(upperCaseCities) // ['SÃO PAULO', 'RIO DE JANEIRO']

// adiciona 'MINAS GERAIS' no array
upperCaseCities.push(cities[2].toUpperCase())

console.log(upperCaseCities) // ['SÃO PAULO', 'RIO DE JANEIRO', 'MINAS GERAIS']

// ☝️ isso é o que está acontecendo à cada execução do for
```

Respondi a dúvida @Denilson-fullstack?

**Comment by Denilson-fullstack** [comment]
Agradeço! professor Roger, agora ficou claro; mais uma coisa, eu não recebi o email com explicação sobre revisão raio x, vi isso em outro comentário queria saber do que se trata, até porque meus acertos ainda ficam em torno 40% nos exercícios feitos pela primeira vez?

**Comment by Roger-Melo** [comment]
Olá Denilson. 

Não enviei e-mail sobre a revisão raio-x, mas sim sobre a aula inaugural (em que falo sobre a revisão raio-x) e análise das aplicações. O título do e-mail é "[Alunos CJRM] Aula inaugural e análises de aplicações".

Você recebeu este e-mail?

@Denilson-fullstack

**Comment by Denilson-fullstack** [comment]
Não recebi esse email.

**Comment by Roger-Melo** [comment]
Seu e-mail é o denilsonsg2017@gmail.com, certo? Enviei novamente.

Me adicione como contato em seu gmail para não correr o risco de perder avisos importantes =)

@Denilson-fullstack

**Comment by Roger-Melo** [comment]
@Denilson-S-Garcia vou fechar a issue mas no que precisar, é só dar o toque =)
