### ISSUE TITLE
Método getAttribute: Dúvida sobre Non-existing attributes e Retrieving nonce values

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4865]
### Etapa da aula

5

### Nome da aula

Obtendo e setando atributos - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/853299

### Descreva a dúvida

Pesquisando sobre getAttribute no MDN, me reparei com essas duas questões abaixo. 

1) [Non-existing attributes](https://developer.mozilla.org/en-US/docs/Web/API/element/getAttribute#non-existing_attributes)

Devo sempre utilizar o hasAttribute() antes do getAttribute para evitar problemas com possíveis valores null or ""?

2) [Retrieving nonce values](https://developer.mozilla.org/en-US/docs/Web/API/element/getAttribute#retrieving_nonce_values)

For security reasons, [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) nonces from non-script sources, such as CSS selectors, and .getAttribute("nonce") calls are hidden.

```js
let nonce =  script.getAttribute('nonce');
// returns empty string
```
Confesso que não entendi muito bem essa explicação. Poderia me ajudar com ela por favor?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @silvasouzaadriano!

> ### Devo sempre utilizar o hasAttribute() antes do getAttribute para evitar problemas com possíveis valores null or ""?

Sempre não.

Vc pode usar o `hasAttribute` antes de invocar `getAttribute` **se** for possível que o atributo não exista no elemento. 

Quando se trata de JavaScript, é meio que um caminho natural vc precisar fazer certas validações em seu código. Vc ainda verá casos desse tipo conforme for avançando no treinamento =)

Quanto ao CSP, na etapa 15 vc encontrará o que vc deve fazer para deixar o Front-end da sua aplicação mais seguro. Caso ainda não saiba o que é Front-end, sem problemas também. Lá vc encontrará uma explicação do que isso significa.

Então até lá, não se preocupe muito com verificações de valores e segurança, pois isso é um conteúdo um pouquinho mais avançado que vc ainda encontrará. Tudo bem? =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
