### ISSUE TITLE
Resumo da Aula 03-09 da etapa 14 - Factory functions e composição de objetos

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#4867]
Factory function 
- Alternativa mais direta de se compor objetos em aplicações web com JS puro.
- É qualquer função que não é uma classe, não é um construtor, não é uma função construtora, mas retorna um novo objeto. 
- Em JS qualquer função pode retornar um objeto e quando a função faz isso sem obrigar a usar a palavra-chave new
antes da invocação dela, ela é uma factory function.

Comparação de um objeto através de uma classe com a criação de um objeto com uma factory function.

Classe

```js
class User {
  constructor(name, email) {
    this.name = name
    this.email = email
  }
}

const user = new User('Roger', 'oi@rogermelo.com.br')

console.log(user) //User {name: 'Roger', email: 'oi@rogermelo.com.br'}
```
```js
const createUser = (name, email) => ({
  name,
  email
})

const user2 = createUser('Roger', 'oi@rogermelo.com.br')

console.log(user2) //{name: 'Roger', email: 'oi@rogermelo.com.br'}
```
Usando factory function, não precisei invocar ela com `new`, não precisei me precupar em inserir a primeira 
letra maiúscula, nem com `constructor`, nem com `this`. 

Utilizando propriedades e métodos privados

Classe

```js
class User {
  #counter = 0

  constructor(name, email) {
    this.name = name
    this.email = email
  }

  incrementCounter() {
    return ++this.#counter
    /*
      Essa expressão - ++this.#counter - vai ser executada antes do return
      a counter vai ser incrementada, essa expressão - ++this.#counter - já vai
      resultar no valor incrementado da counter e esse valor vai ser retornado 
    */
  }
}

const user = new User('Roger', 'oi@rogermelo.com.br')

console.log(user.incrementCounter())//1
console.log(user.incrementCounter())//2
```
Factory function
```js
const createUser = (name, email) => {
  let counter = 0

  return {
    name,
    email,
    incrementCounter: () => ++counter
  }
}

const user2 = createUser('Roger', 'oi@rogermelo.com.br')

console.log(user2.incrementCounter())//1
console.log(user2.incrementCounter())//2
const user3 = createUser('Roger 2', 'oi2@rogermelo.com.br')//1
const user3 = createUser('Roger 2', 'oi2@rogermelo.com.br')//2
```
Um novo `counter` foi criado e incrementado duas vezes. Isso é possível por causa de um mecanismo 
da linguagem chamado closures - combinação de uma função com seu escopo léxico.
Escopo léxico é todo o escopo que envolve a declaração dessa arrow function - `() => ++counter`. Como nessa 
arrow function, estou usando uma `let` que foi declarada no escopo léxico, a arrow function agora é uma 
closure. E para que não houvesse uma colisão entre a `let counter` do `user2` e a `let counter` do `user3`, como
a `createUser` foi invocada duas vezes, duas `let counter` foram declaradas em espaços diferentes na memória, então a 
`let counter` da segunda invocação não é a mesma `let counter` da primeira e é isso que garante que cada `user`
tenha seu próprio `counter`.

Composição 

```js
class a {
  first() {
    return 1
  }

  second() {
    return 'nããoooo!'
  }
}

class b extends a {
  third() {
    return 3
  }
}

const obj = new b()
console.log(obj.second()) //nããoooo!  
```
Herança clássica é um tipo de herança inflexível por natureza, não tenho a flexibilidade de escolher qual
método eu quero que meu objeto tenha. Ao invés de criar o objeto usando herança, eu uso composição:

```js
const a = {
  first() {
    return 1
  }
}

const b = {
  second() {
    return 'nããoooo!'
  }
}

const c = {
  third() {
    return 3
  }
}
```

Ao invés de criar um objeto em que eu não posso selecionar muito bem os métodos que ele vai ter, posso criar uma 
`const obj` que recebe um objeto e dentro desse objeto posso criar as combinações de métodos que eu quiser:

```js
const obj = {
  ...a,
  ...c
}

console.log(obj)//{first: ƒ, third: ƒ}
```

O objeto tem os métodos `third` e `first` e não tem o método `second`.

Vantagens de usar factory functions ao invés de classes ou funções construtoras:

1ª) factory functions não me deixam tentado a fazer níveis de herança na aplicação 
2ª) a aplicação tende a ter menos problema de refatoração, porque não vai ser preciso converter
factory functions para classes 
3ª) não vai ser necessário utilizar o `new` para invocar uma factory function, será invocada como qualquer 
outra função, porque em JS qualquer função pode retornar um objeto.
4ª) o comportamento do `this` vai voltar a ser o padrão, ou seja, o `this` ao invés de referenciar o objeto que 
está sendo criado, vai referenciar quem ele tiver que referenciar e terá uma tendência a escrever menos `this`. 
E quanto menos `this` melhor, pois o `this` é imprevisível, ele pode mudar quem ele referencia, quanto mais
previsível for o código da aplicação, melhor.

Desvantagens em usar factory functions

Uma factory function é microotimizadamente um pouco mais lenta que uma classe ou função construtora,
mas mesmo assim uma factory function ainda é muito rápida, ela faz milhões de operações por segundo
num computador velho, ao invés de se preocupar com microotimização em uma aplicação, a preocupação 
será quando uma lib ou framework estiver sendo desenvolvida, em uma aplicação a prioridade, o que tem 
que ser feito antes de escovar bit, é trabalhar em cima da performance percebida.

**Comment by Roger-Melo** [comment]
Boa @Jansen-Muniz rumo à fluência! 🔥
