### ISSUE TITLE
Resumo da Aula 02-02 da etapa 07 - setTimeout() e o objeto window

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4869]
### Objeto window
Quando se trata do front-end existe um objeto global onde todas as propriedades e métodos estão penduradas esse objeto global é o window a janela do browser, tudo que fazemos no js, todas os objetos, propriedades e métodos estão armazenadas no objeto window, todas as vezes que precisarmos utilizar uma propriedade do objeto window não é preciso especificar a palavra window antes do nome da propriedade, pois a engine do browser infere que a propriedade esta armazenada no objeto window.

### setTimeout
O setTimeout é uma função que esta armazenada no objeto window, não sendo necessário especificar a palavra window antes da função.
```js
setTimeout(() =>{
    console.log('Ola');
}, 2000)
```
O setTimeout executa uma ação após uma quantidade de tempo após o browser carregar a pagina, ela recebe dois parâmetros, o primeiro parâmetro é a função que será executada, o segundo é a quantidade de tempo em milissegundos que vai levar para a ação ser executada.

**Comment by Roger-Melo** [comment]
Boa @Diegodkid rumo à fluência! 🔥
