### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#487]
O último tipo de controle de fluxo que veremos é o *switch statement*. Ele é utilizado quando precisamos checar uma variável ou constante que possa ter múltiplos valores diferentes, e que para cada um desses valores  possamos reagir de uma determinada forma. Um pequeno exemplo seria imaginar uma lista de notas de 1 a 5, que servem para monitorar a qualidade do atendimento de uma equipe de suporte, onde cada nota deve retornar uma mensagem específica falando sobre o atendimento. E sim, poderíamos resolver com *ifs* encadeados, porém o código ficaria repetitivo e talvez um pouco mais difícil de entender de maneira rápida num primeiro momento. Já com o *switch statement*, temos uma facilidade maior de implementação e entendimento. Vamos ao código:

```js
const grade = 4;

switch (grade) {
	case 1:
		console.log('O atendimento foi péssimo.');
		break;
	case 2:
		console.log('O atendimento foi ruim.');
		break;
	case 3:
		console.log('O atendimento foi normal.');
		break;
	case 4:
		console.log('O atendimento foi bom.');
		break;
	case 5:
		console.log('O atendimento foi excelente.');
		break;
	default:
		console.log('Não foi possível identificar a avaliação do atendimento.');
}

// O atendimento foi bom.
```

Após cada ação (no exemplo foi apenas uma mensagem no console), é necessária a utilização do *break* para que neste ponto o *switch statement* seja interrompido, caso contrário ele será executado até o comando do *default*. E caso o valor atribuído a constante *grade* não seja encontrado em nenhum *case* do *switch*, o bloco de código que estiver no *default* será executado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas! Rumo à fluência! 👊🏻
