### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4877]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/AlessandroAscanio/weatherAPP

### Maiores dificuldades durante a implementação

Refatorar o código, tentar criar pequenas funções de única responsabilidade e saber exatamente quando eu preciso utilizar o await em uma função async, por exemplo: na função do fetch o return é um response.json( ) ao invés de await response.json( ), eu dei uma travada nessa parte mas revisei as aulas e refiz todo o código do zero então eu pude compreender melhor.

### Menores dificuldades durante a implementação

Capturar os elementos do DOM, fazer o destructuring apenas das informações que serão utilizadas, inserir as informações na página.

**Comment by Roger-Melo** [comment]
Olá @AlessandroAscanio.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @AlessandroAscanio.

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ### Na função do fetch o return é um response.json( ) ao invés de await response.json( ), eu dei uma travada nessa parte mas revisei as aulas e refiz todo o código do zero então eu pude compreender melhor.

Boa! Embora você tenha revisado, vou apenas reforçar alguns conceitos aqui para eu não pecar pela falta...

> ### Saber exatamente quando eu preciso utilizar o await em uma função async

Você precisa usar o `await` quando precisa aguardar o resolver de uma promise. 

> ### Por exemplo: na função do fetch o return é um response.json()

Lembre-se de que um request (operação assíncrona) feito com o `fetch` retorna uma promise, e não um response ou response.json(). 

Você pode comprovar isso testando no seu código:

```javascript
// weather.js
const x = fetch(url)
console.log(x) // Promise {<pending>}
```

☝🏻 sem o await, você não aguarda o resolver da promise e o retorno é a prória promise. 

`response` só é desencapsulado da promise se você aguarda ela resolver usando o `await`:

```javascript
const x = await fetch(url)
console.log(x) // Response { ... }
```

`response.json()` também retorna uma promise. Por isso você precisa do `await` na frente dele.

Recomendo que revise toda a etapa 11 buscando preencher esses gaps. Ela é muito importante para que você entenda os conceitos de assincronismo que você levará pelo restante de sua carreira de desenvolvedor.

Além disso, recomendo que leia a documentação de introdução à JavaScript assíncrono no MDN:

[Asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous)

Não vai ser rápido, mas entender assincronismo é crucial para um Desenvolvedor JS, caso contrário certamente a carreira será prejudicada. E eu não quero isso para você.

Se tiver alguma dúvida, pode abrir outras issues que te ajudo =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Let ao invés de const

Prefira usar const no lugar de let, quando possível. 

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo. No entanto, vale a pena relembrar que as propriedades do objeto que a const armazena ainda podem sofrer mutação, então mesmo que o objeto seja atribuído a uma const, isso não garante que o objeto seja imutável. 

A let `timeImg` pode ser uma const, pois ela não irá sofrer reatribuição de valor, porém as propriedades de seu objeto ainda estarão sujeitas à mutação. 

```js
// antes
let timeImg = document.querySelector('[data-js="time"]')
```

```js
// depois
const timeImg = document.querySelector('[data-js="time"]')
```

---

## Callback de formSearch.addEventListener

Uma sugestão seria nomear o callback do listener de evento como `showCityWeather`, por exemplo. Por meio desse nome, fica claro a ação mais importante que vai acontecer quando o envio do form for executado, que é a exibição do clima da cidade. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, porque ao bater o olho no nome da função, a ação que ela executa fica explícita:

```js
// antes
formSearch.addEventListener('submit', async event => {
  // ...
})
```

```js
// depois
const showCityWeather =  async event => {
  // ...
}

formSearch.addEventListener('submit', showCityWeather)
```

---

## inputValue

Algo que pode ser útil, seria usar o método trim para remover os espaços em branco de uma eventual busca ao inserir o nome da cidade. Sabendo que o método trim remove os espaços em branco do início e fim de um texto, ele pode ser usado para evitar com que um espaço em branco inserido acidentalmente, por exemplo, prejudique a busca de um nome. Ficaria assim:

```js
inputValue = event.target.city.value.trim()
```

Nunca declare consts ou lets sem as palavras-chave const ou let, pois isso pendura uma variável global no objeto window (é como se var tivesse sido usado).

No código abaixo inputValue foi pendurado no window:

```js
inputValue = event.target.city.value.trim()

console.log(window.inputValue) // california
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

Como regra geral, sempre declare uma variável com const, a menos que você saiba que o valor mudará futuramente. Dito isso, você pode declarar o `inputValue` com a palavra chave const.

```js
const inputValue = event.target.city.value.trim()
```

---

## Validação

Na função `showCityWeather`, algo que você pode adicionar e que seria interessante como funcionalidade para o desenvolvedor da aplicação é inserir uma validação no `inputValue`. Esse `inputValue` pode ter uma verificação para caso uma string vazia ou string com menos de três caracteres for enviada como input. Numa situação assim, você pode, se achar que faz sentido, exibir uma mensagem na tela por meio do `alert` comunicando que é necessário inserir o nome de uma cidade. Haver esse tipo de validação aqui é apenas uma ideia inicial, existem várias possibilidades diferentes de fazer uma validação, mas não vamos focar nisso nessa análise, essa sugestão é apenas um começo, uma ideia em relação ao que pode ser feito nesse trecho de código. Dito isso, ficaria assim:

```js
const showCityWeather =  async event => {
  // ...
  inputValue = event.target.city.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira o nome da cidade")  
    return
  }
}
  
```

---

## Nomenclatura

Se fizer sentido para você, a palavra "search" que você usou na const `formSearch` pode ser removida e o nome da const ser encurtada em apenas `form`. Assim já é o suficiente para quem está lendo entender que a const `form` está armazenando a referência do form.

```js
// antes
const formSearch = document.querySelector('[data-js="change-location"]')
```

```js
// depois
const form = document.querySelector('[data-js="change-location"]')
```

Um outro ajuste que você pode fazer para facilitar o entendimento é renomear a função `insertTemperatureIntoPage` para `insertCityTemperatureIntoPage`. Dessa forma, essa função seguirá o mesmo padrão de nome, "insertCity" que as funções usadas para inserir o nome, ícone e clima respectivamente. 

```js
// antes
const insertTemperatureIntoPage = ...
```

```js
// depois
const insertCityTemperatureIntoPage = ...
```

A const `isDnoneClassExistis` pode ter um nome mais simples, mais curto e que ao mesmo tempo seja referente a um sentido similar. Se for interessante para você, você pode renomeá-la como `hasDnone`, esse nome já fornece uma boa noção de que a const está armazenando algo que contém a classe 'd-none'. Ficaria assim:

```js
// antes
const isDnoneClassExistis = cardContainer.classList.contains('d-none')
```

```js
// depois
const hasDnone = cardContainer.classList.contains('d-none')
```

Também pode ser interessante trocar o nome da função `createTemplateImg` por algo como `getImgIcon`, visto que essa função tem um uso mais similar ao de colocar um ícone de dia ou noite na aplicação do que o de criar. Acredito que dessa forma a ideia do que essa função está fazendo se torne mais clara. Ficaria assim:

```js
// antes
const createTemplateImg = WeatherIcon => `<img src="./src/icons/${WeatherIcon}.svg">`
```

```js
// depois
const getImgIcon = WeatherIcon => `<img src="./src/icons/${WeatherIcon}.svg">`
```

Por fim, a função `removeClassDnone` pode ter um nome mais conciso em relação ao seu papel no código. Ao analisar o código, percebe-se que essa função é responsável por exibir na tela o cartão com as informações da cidade pesquisada no input, nesse caso, se fizer sentido para você, acredito que essa função possa receber um nome que torne mais fácil o entedimento dessa parte do código. Uma sugestão seria trocar `removeClassDnone` por algo como `showCityCard`. Ficaria assim:

```js
// antes
const removeClassDnone = () => {
  // ...
}
```

```js
// depois
const showCityCard = () => {
  // ...
}
```

---

## Organização do código

Alguns detalhes em relação à ordem das linhas de código nas funções da sua aplicação podem deixar o código mais organizado. Por exemplo, uma delas é na função `showCityWeather`, o reset do event poderia estar melhor posicionado se ficasse na última linha da função, pois faz mais sentido que os inputs desse form sejam resetados por último, após todas as outras funções e informações adicionais já terem sido lidas. Ficaria assim:

```js
const showCityWeather =  async event => {
  // ...
  // ...
  event.target.reset()
}
```

Uma outra ideia seria, se fizer sentido para você, posicionar a invocação da função `showCityCard` antes do método reset. A vantagem disso é relativa à organização de forma bem similar à sugestão anterior, você pode deixar para invocar a função que exibe o card com as informações da cidade na tela após todas as outras informações e funções já terem sido lidas, e por fim, invocá-la antes do método de reset. Ficaria assim:

```js
const showCityWeather =  async event => {
  // ...
  // ...
  showCityCard()
  event.target.reset()
}
```

---

## Refatoração

No operador ternário dentro de `insertTimeBackgroundImg`, você pode abstrair as repetições de `timeImg.src` e de benefício deixá-lo mais simples escrevendo menos código. Uma implementação ideal do ternário poderia ser feita ao fazer `timeImg.src` receber a condição de `IsDayTime` da seguinte forma:

```js
// antes
const insertTimeBackgroundImg = IsDayTime => {
  return IsDayTime
    ? timeImg.src = './src/day.svg'
    : timeImg.src = './src/night.svg'
}
```

```js
// depois
const insertTimeBackgroundImg = IsDayTime => timeImg.src = IsDayTime ? './src/day.svg' : './src/night.svg'
```

Uma opção de refatoração com o intuito de encurtar o código e deixá-lo mais conciso, seria remover o if e a const `hasDnone` dentro da função `showCityCard`. A const `hasDnone` está retornando um boolean que será true ao escrever o nome da cidade no input e então esse valor passa por um bloco if para depois remover a classe `d-none`. Entretanto, você pode fazer o mesmo apenas com `cardContainer.classList.remove('d-none')` dentro da função `showCityCard` sem a necessidade de uma const armazenando um valor boolean ou de um bloco de if. Após essa refatoração de código, caso a classe `d-none` não existir no elemento, o método remove também será executado mas nenhum erro será lançado e o seu código continuará funcionando normalmente. Ficaria assim:

```js
// antes
const showCityCard = () => {
  const hasDnone = cardContainer.classList.contains('d-none')

  if (hasDnone) {
    cardContainer.classList.remove('d-none')
  }
}
```

```js
// depois
const showCityCard = () => {
  cardContainer.classList.remove('d-none') 
}
```

No código acima, não há problemas caso a classe `d-none` exista ou não, o método remove será executado, mas na situação onde ela não existir, o código continuará funcionando normalmente sem erros.

Você também pode, se achar que faz sentido, mover os códigos das funções `getImgIcon`, `showCityCard` e `insertCityWeatherInfosIntoPage` (e também todas as funções invocadas dentro dela) para `showCityWeather`:

```js
const showCityWeather = async event => {
  event.preventDefault()
  
  const inputValue = event.target.city.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira o nome da cidade")  
    return
  }
      
  const [{ Key, LocalizedName }] = await getCityData(inputValue)
  const [{ IsDayTime, Temperature, WeatherIcon, WeatherText }] = await
    getCityWeather(Key)

  const imgIcon = `<img src="./src/icons/${WeatherIcon}.svg">`
    
  timeImg.src = IsDayTime ? './src/day.svg' : './src/night.svg'

  timeIcon.innerHTML = imgIcon
  cityNameContainer.textContent = LocalizedName
  cityWeatherContainer.textContent = WeatherText
  cityTemperatureContainer.textContent = (Temperature.Metric.Value)
 
  cardContainer.classList.remove('d-none')

  event.target.reset()
}

```

Um indicativo de que essa mudança pode fazer sentido é a complementariedade que esses trechos de códigos fornecem à `showCityWeather`, e por isso, acredito que esses trechos de código poderiam ser simplificados numa única função. Por essa função já se chamar `showCityWeather`, portanto, presume-se que o código dentro dela esteja relacionado a isso. Assim, por meio dessa refatoração, você concentra grande parte da manipulação do DOM em apenas uma função e evita usar mais linhas de código para declarar mais funções que executariam apenas uma linha simples para no final serem invocadas na função principal.

Uma outra possibilidade de refatoração seria, por meio de uma abstração, você não precisar mais usar a invocação de `getCityData`. Segundo o raciocínio, ao invés de termos essa função, nós vamos ter apenas a função `getCityWeather` que vai fazer o que a `getCityData` está fazendo. A ideia dessa refatoração é ao invés de invocarmos duas funções, simplificar as coisas e precisarmos apenas invocar uma função que irá fazer o papel das duas =)

Dito isso, para entender de fato essa abstração que vou mostrar, eu sugiro que você escreva e execute cada código do passo a passo abaixo junto comigo, ok?

Vamos lá, vou criar uma função chamada `getCityWeather` que ao invés de receber a key, vai receber o nome da cidade. Antes de buscarmos o clima da cidade, precisamos obter as informações da cidade para obtermos a key, pois só por meio dela poderemos fazer o segundo request, no caso do seu código, o usado na função `fetchData`. Para desaninharmos as funções invocadas dentro da `fetchData`, vamos criar uma const `cityInfoUrl` que vai receber a `getCityUrl` e vamos exibí-la no console para confirmarmos se os resultados que esperamos estão sendo obtidos.

```js
const getCityWeather = city => {
  const cityInfoURL = getCityUrl(city)
  console.log(cityInfoURL) // Url com o nome da cidade no query parameter aparece...
} 
``` 

Não se preocupe se aparecer algum erro no console, o intuito aqui é, ao executarmos um console.log, ver a url com o nome da cidade no query parameter, ou seja, a cidade buscada. Feito isso, já que essa url está sendo obtida, podemos criar uma const `cityInfo` que vai armazenar o retorno da função `fetchData`. Seguindo o raciocínio, `cityInfo` vai ser uma função async, portanto terá um await que espera a resolução dessa promise que contém `cityInfoUrl` como argumento. Ficaria assim:

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const cityInfo = await fetchData(cityInfoURL)
  console.log(cityInfo) // Array de objetos aparece...
} 
```

Ao visualizarmos isso no console, veremos que o resultado é um array de objetos em que o primeiro objeto vai corresponder, na maioria das vezes, a cidade escolhida no input.

No código que usamos para manipular o DOM, estamos usando, além da propriedade Key, a propriedade LocalizedName. Então, também vamos precisar da propriedade localizedName, e essa função `getCityWeather` vai ter que retornar ela para quando for invocada ela ser usada no destructuring e e então servir como argumento dessa invocação. 

Para fazermos o destructuring no array de objetos e pegarmos do primeiro objeto, as propriedades LocalizedName e Key, vamos fazer um destructuring nesse primeiro objeto, na propriedade Key e na LocalizedName. Feito isso, se exibirmos no console, aparece a Key e o nome da cidade como LocalizedName. 

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  console.log(Key, LocalizedName) // Key e LocalizedName aparecem no console...
} 
```

Após isso, vamos fazer o segundo request para obtermos a informação do clima dessa cidade, para isso, vamos usar a Key. Para isso, vamos obter a url, vou criar uma const `cityWeatherURL` recebe a invocação de `getWeatherUrl()` que recebe a Key como argumento. Dessa forma, a url com a Key vai ser retornada corretamente.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getWeatherUrl(Key)
  console.log(cityWeatherURL) // Url com a Key vai ser retornada...
} 
```

Feito isso, agora que temos a url, falta fazer o último request, que é o request que vai buscar os dados do clima da cidade. Para fazer isso, vamos criar uma const `cityWeather` que recebe `fetchData` com await antes porque é uma função assincrona, e esse `fetchData` vai receber `cityWeatherURL` como argumento.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getWeatherUrl(Key)
  const cityWeather = await fetchData(cityWeatherURL)
  console.log(cityWeather) // Array com um objeto que contém os dados do clima da cidade.
} 
```

Agora, podemos retornar cityWeather e para que essa função não retorne um array num objeto, podemos fazer com que ela retorne apenas um objeto por meio de um destructuring.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getWeatherUrl(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return cityWeather
} 
```

Você se lembra que esse objeto que está sendo retornado por essa função também precisa ter LocalizedName? Então, ao invés de retornar um objeto, você pode retornar um novo objeto que contém as propriedades do objeto cityWeather e também contém LocalizedName. Aqui foi criado um novo objeto que contém as propriedades do objeto cityWeather espalhados pelo spread operator e que também contém a LocalizedName.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getWeatherUrl(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return { ...cityWeather, LocalizedName }
} 
```

Por fim, resta inserir LocalizedName como um dos destructurings da função `getCityWeather`. Nessa função, o destructuring do array, ou seja, os colchetes, podem ser removidos pois agora a `getCityWeather` não está mais retornando um array, mas um objeto. Por isso não é mais necessário os colchetes do destructuring.

```js
const {IsDayTime , WeatherText , WeatherIcon , Temperature, LocalizedName} = await getCityWeather(inputValue)
```

Após isso, você não vai precisar mais da função `getCityData` e o código estará funcionando perfeitamente bem =)

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by AlessandroAscanio** [comment]
Olá @MivlaM as observações fizeram total sentido para mim e tem me ajudado bastante a perceber onde eu preciso melhorar e também a me atentar mais em detalhes que já foram ensinados por exemplo: validação do campo input, utilizar .trim() que não implementei na minha versão. Valeu!  Obrigado pela análise minuciosa.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
