### ISSUE TITLE
Resumo da Aula Try/catch em requests e erros personalizados - Aula 06-05 da etapa 11

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4892]
```js
const getUsers = async () ={
  try{
    const response = await fetch(‘https://jsonplaceholder.typicode.com/users’)
    
    if(!response.ok) {
      throw new Error(‘Não foi possível obter os dados’)
    }
    
    return response.json()
  } catch (error) {
     console.log(error.message)
 }
}

logUsers()
```

No código acima está sendo feita uma solicitação para uma API porém o request está sendo envolvido em um try que tem como objetivo tentar executar o trecho do código, se ele não conseguir obter os dados ele lança um throw de Error que será repassado para o catch criando assim um erro personalizado. Caso o resultado da requisição seja positivo, será retornado o response.json()

**Comment by Roger-Melo** [comment]
Show @AlessandroAscanio . Vamo que vamo, rumo à fluência! 🙌
