### ISSUE TITLE
02 - Controle de fluxo, Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#49]
Roger,
Levei uma surra nesse exercício, travei tela azul.
Eu fui olhar a resolução, via uma parte sendo feita e fazia sem olhar, e fui assim
até o final do exercício.
Esse modo que eu fiz tbm serve como aprendizado?

Por que logo nesse item >> "Itere sobre o array "randomValues" apenas até a 4ª string dele;"
Já travei!

Cheguei a criar o loop, verificar a string.
Acho que o medo de fazer um código zoado, esta me bloqueando
Vi você  fazendo e não imaginei que poderia usar vários ifs dentro do loop.

O que eu estou no curso são códigos muitos tops, e bem explicados.
Mais pra eu montar igual a você,  nesse alto nível de lógica esta sendo um pouco 
difícil pra mim. 

Estou fazendo do curso uma missão pra mim, mesmo com uma vida turbulenta que vivemos.
Se eu focasse só no curso o dia todo, pó eu acho que evoluiria bem mais rápido. 

/*
  05

  - Itere sobre o array "randomValues" apenas até a 4ª string dele;
  - Exiba a string abaixo no console, mantendo a formatação de lista e inserindo  
    as informações corretas:

  "
    3 informações sobre o array randomValues:
      - As primeiras 4 strings são XX, XX, XX e XX;
      - Até que as primeiras 4 strings fossem iteradas, XX booleans foram iterados;
      - O array foi iterado por XX vezes.
  "
*/ 

``` const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS', 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]

let stringsAmount = 0
let stringsItens = []
let booleansItens = 0
let totalInterations = 0

for(let i = 0; i < randomValues.length; i++){
    const item = randomValues[i]
    const typeofItem = typeof item
    const isItemAString = typeofItem === 'string'
    const isItemABoolean = typeofItem === 'boolean'

    if(stringsAmount === 4){
      break
    }

    if(isItemAString){
      stringsAmount++
      stringsItens.push(item)
    }

    if(isItemABoolean){
       booleansItens++
    }

    totalInterations++
}

const lasItem = stringsItens[stringsItens.length - 1]
const itemString = stringsItens.join(', ').replace(`, ${lasItem}`, ` e ${lasItem}`)

console.log(`3 informações sobre o array randomValues:
  - As primeiras 4 strings são ${itemString};
  - Até que as primeiras 4 strings fossem iteradas, ${booleansItens} booleans foram iterados;
  - O array foi iterado por ${totalInterations} vezes.`) ```


<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Passando rapidinho apenas para dizer que li a issue.

Estou sem meu computador hoje. Tive que enviá-lo para a assistência técnica para limparem a poeira interna da CPU e gabinete. Havia um certo tempo que não fazia isso.

Amanhã devo pegá-lo de volta e lhe responderei com calma, combinado? =)

**Comment by Roger-Melo** [comment]
Oi Edinaldo.

Um imprevisto aconteceu e ainda não peguei o computador hoje.

Amanhã, assim que eu pegá-lo, responderei a sua dúvida. Tentei começar a responder as issues pelo celular mas não dá. É inviável. Amanhã respondo da forma ideal, combinado?

**Comment by naldowebdeveloper** [comment]
Tranquilo Professor

**Comment by Roger-Melo** [comment]
Oi Ednaldo! Vamos lá =D

> Eu fui olhar a resolução, via uma parte sendo feita e fazia sem olhar, e fui assim
até o final do exercício. Esse modo que eu fiz tbm serve como aprendizado?

Você via até a parte em que "travava" e depois tentava fazer só?

Pode ser uma estratégia também.

Sempre se assegure que você entendeu a resolução mostrada na revisão. É legal fazer sozinho depois de assistir. Assim seu cérebro é forçado a se lembrar dos conceitos explicados. Se não lembrar, assista novamente e depois tente fazer só, outra vez.

Se sentir que tá muito complicado, esse exercício pode ser um exercício-modelo do seu resumo. Lembra dessa etapa do ATER?

---

> Cheguei a criar o loop, verificar a string. Acho que o medo de fazer um código zoado, esta me bloqueando. Vi você fazendo e não imaginei que poderia usar vários ifs dentro do loop.

Ifs podem ser usados em qualquer momento em que uma verificação é necessária =)

Não precisa ter esse medo. Todo começo de implementação é imperfeito. Aos poucos você vai incrementando e melhorando o código. Primeiro faça, depois melhore.

Não é um grande problema chegar em uma solução diferente da que foi mostrada na revisão. Essa "dor" de ver o exercício sendo resolvido de uma maneira mais concisa (se for o caso) também é um aprendizado.

Apenas fique atento ao ponto que falei acima, sobre entender a resolução e fazê-la sozinho.

---

> Se eu focasse só no curso o dia todo, pó eu acho que evoluiria bem mais rápido.

É um caminho, mas não é o único. Nenhum bloqueio resiste a um bom método.

Se você quer melhorar seus resultados nos estudos, avalie os 6 indicadores-chave de performance:

1. Quanto => Sua meta diária. Quantas horas diárias você estuda;
1. Quando => Os dias que você estuda. De preferência, todos os dias;
1. Onde => O ambiente te influencia pro bem ou pro mal;
1. Por onde => É o material que você usa para estudar (aula, anotações, exercícios, etc);
1. O quê => É o quê você estuda. No CJRM, isso já é filtrado. É o conteúdo que vai te levar à fluência;
1. Como => É o método de estudos que você aplica.

Definitivamente, no "A" de aula, do ATER, fazer resumos das aulas é essencial.

A escrita exige que o cérebro foque na aula e, posteriormente, suas anotações serão materiais de consulta nos exercícios e revisão.

---

Sobre o código do exercício, tem alguma dúvida específica em que posso ajudar?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo Valeu pela explicação vou focar mais no ATER,  ter mais calma e focar mais consistência.

Sobre o código é uma questão de familiaridade, eu tinha pensado em outras formas de resolver, mais tranquilo.

**Comment by Roger-Melo** [comment]
Show. Já que a dúvida foi sanada, vou fechar essa issue. Mas no que precisar é só abrir uma nova =)
