### ISSUE TITLE
Resumo da Aula O que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#490]
Funções são um dos principais conceitos em linguagem de programação. No JavaScript, uma função faz parte do tipo Object (lembrando que do tipo Object nós temos também arrays, datas, objetos literais, etc), e ela permite que criemos um bloco de código que pode ser invocado e consequentemente executado quantas vezes forem necessárias.

A sintaxe de invocação de uma função é utilizar o nome da função seguido de abertura e fechamento de parênteses, por exemplo `exibeMensagem()`, podendo ter valores ou não entre os parênteses, e isso dependerá do que a função irá fazer. Imagine que dentro de uma aplicação existe um botão que ao ser clicado deverá exibir uma determinada mensagem ao usuário. Aqui poderíamos ter uma função, onde sua invocação estaria atrelada ao clique do botão, logo, toda vez que o botão fosse clicado, a função seria executada e a mensagem seria exibida. Uma outra ideia seria ter uma função que receba um valor como argumento, como por exemplo, o ano de nascimento de alguém, e essa função devolveria a idade que essa pessoa tem no ano atual, e ela poderia ser invocada da seguinte maneira: `calculaIdade(1983);`.

Estes são apenas alguns simples exemplos de como se utilizar funções em JavaScript.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas. Bora rumo à fluência! 🔥
