### ISSUE TITLE
Resumo da Aula Ométodo forEach e CallBacks da etapa XX

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#4907]
### Callback
Vimos que podemos passar argumentos para uma função e usar dentro da função esses valores passados como argumento
Podemos também inserir uma função como argumento e quando fazemos isso  a gente chama essa função que passamos por argumento de **função de callback** ou simplesmente de **callback**

```JS
const myFunc =(callBack => {
const value = 77

callBack(value)
}
myFunc((number) => {
console.log(number)
})
```
## forEach

forEach é um método que itera sob um array e para cada item desse array ele executa alguma ação.
Esse método funciona como o _for_ mas de uma forma mais elegante e funcional.
Na invocação do _forEach_ a gente precisa inserir uma função de callback.

```JS
const socialNetworks = ['youtube', 'twitter', 'instagram', 'facebook']
socialNetworks.forEach(() => {
console.log('Olá')
}
```
O **forEach** itera pelo array e para cada item desse array ele vai executar a função de callback que passamos como argumento dele. então devemos ver a string _olá_ exibida no console 4 vezes(uma para cada item do array)

A funçao de callbac que passamos como parametro pode receber 3 parametros.
O primeiro é o item atual que está sendo iterado.
podemos nomear esse parâmetro como _socialNetwork_ (no singular) porque cada item do array é uma rede social.

```JS
socialNetworks.forEach((socialNetwork) => {
console.log(socialNetWork)
})
```
Então todas as vezes que a função é executada o item atual que está sendo iterado é recebido no parâmetro _socialNetworks_.
Na primeira vez que a função for executada o primeiro item('youtube') vai ser exibido no console, na segunda vez  o segundo item item ('twitter') vai ser exibido no console.

Essa função pode ainda receber mais dois parâmetros opcionais, o index do item atual e o array que está sendo iterado.
```JS
socialNetworks.forEach((socialNetwork, index, array) => {
console.log( index, socialNetwork, array)
})
```
Então na primeira vez que a função for executada ela vai exibir o index do primeiro item do array que é 0
O item em sí que é 'youtube' e o array completo.
Na segunda vez o index 1, o item 'twitter' e o array completo e assim sucessivamente.

Outra vantagem do **forEach** em relação ao **for** é a declaração dessa função_**(socialNetwork, index, array) => {
console.log( index, socialNetwork, array)**_ pode ser desacoplada 

```JS
const socialNetworks = ['youtube', 'twitter', 'instagram', 'facebook']

const logArrayInfo = socialNetwork, index, array) => {
console.log( index, socialNetwork, array)

socialNetworks.forEach(logArrayInfo)

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr rumo à fluência! 🔥
