### ISSUE TITLE
Resumo da Aula 01-04 da etapa 08 - O método reduce

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4910]
### Reduce
O método reduce é utilizado quando queremos obter um único valor de um array, este valor será obtido por uma função de callback fornecida por nos, esse callback é conhecido como reducer
```js
const number = [1, 2, 3]

number.reduce((accumulator, item) => {}, 0)
```
o método reduce recebe dois parâmetros iniciais, que são o acumulador e o item atual, como segundo parâmetro a função de callback que será executada e um terceiro parâmetro opcional que representa o valor inicial que o acumulador terá quando o reduce for executado pela primeira vez
```js
const result = number.reduce((accumulator, item) => accumulator + item, 0)
```
a função de callback sempre retornará um valor, que será armazenado no acumulador, na primeira vez que o reduce for executado o acumulador recebe 0, que foi passado como argumento inicial no terceiro parâmetro e será somado ao item atual do array
```js
const result = number.reduce((accumulator, item) => accumulator + item, 0)

const result = number.reduce((accumulator, item) => 0 + 1, 0)
```
na segunda vez que o reduce for executado o acumulador agora possui o valor que obteve da função de callback guardado, onde é somado ao item atual, assim consecutivamente até que todos os itens do array tenham sido iterados.
```js
const result = number.reduce((accumulator, item) => 1 + 2, 0)
```
Se não passarmos o valor inicial que o acumulador terá quando o reduce for executado pela primeira vez como argumento do terceiro  parâmetro do reduce, então o acumulador será o valor do primeiro item do array e o item será o segundo elemento do array, e a cada  nova iteração isso será executado no index seguinte do array até que todo array tenha sido percorrido
```js
const result = number.reduce((accumulator, item) => accumulator + item)
```

**Comment by Roger-Melo** [comment]
Boa @Diegodkid rumo à fluência! 🔥
