### ISSUE TITLE
Resumo da Aula 02-02 da etapa 08 - O método sort

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#4919]
### O método sort
Quando quisermos ordenar um array podemos utilizar o método sort
```js 
const letters = ['c', 'b', 'a']

letters.sort()

console.log(letters) // a, b, c
```
ao encadearmos a invocação do método sort no array letters ele ordena automaticamente as strings em ordem alfabética
```js 
const number = [15, 10, 30, 20, 5]

number.sort()

console.log(number); // 10, 15, 20, 30, 5
```
ao encadearmos o método sort no array number o esperado era que também fosse ordenado de forma crescente, mas o resultado foi outro, isso acontece porque quando tentamos ordenar um array de números dessa maneira, o método sort considera apenas o primeiro numero quando faz a ordenação, sabendo disso a ordenação da forma como foi especificada está correta.
```js 
const number = [15, 10, 30, 20, 5]

number.sort((number1, number2) => {})
```
O método sort pode receber dois parâmetros opcionais, que representam dois itens do array consecutivamente, uma função de callback que é uma função de comparação que será executada para os parâmetros 1 e 2 consecutivamente.
```js 
number.sort((number1, number2) => {
    if (number1 > number2) {
        return -1
    } else if (number2 > number1) {
        return 1
    }

    return 0
})
```
se quisermos retornar o item 1 antes do item 2 dentro da condicional do if vamos dizer que se o item 1 for maior do que o item 2 então o valor retornado será um numero menor que 0, isto é -1, se quisermos que o item 2 seja exibido primeiro, o retorno dessa função deve ser um numero positivo, se não for necessário haver ordenação o retorno deve ser 0
```js 
number.sort((number1, number2) => number2 - number1)
```
essa é uma forma de obtermos o mesmo valor do código anterior, porem com uma sintaxe mais reduzida

**Comment by Roger-Melo** [comment]
Boa @Diegodkid rumo à fluência! 🔥
