### ISSUE TITLE
Resumo da Aula Código assíncrono em JavaScript - Aula 01-02  da etapa 11

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#4920]
`
Código assíncrono em JavaScript - Aula 01-02  

O que é uma operação assíncrona? 

Basicamente, são operações que levam um certo tempo para sempre concluídas. 

É um código que inicia um processo agora! e finaliza esse processo posteriormente. 

Ex.: Consultar uma API; 
     Consulta a um BD. 

A natureza do JavaScript é ele ser síncrono ou seja, uma instrução por vez, em cascata, de cima para baixo. 
Uma linguagem Single thread (thread = "fio"), uma instrução atras da outra. 

_________________________________________________________________________________________________________________________________________

Código síncrono:

       |
console.log(L 1) 
       | 
console.log(L 2) 
       | 
console.log(L 3) - consulta BD (Código Blocante ou Block Code = Bloqueia a próxima execução até que as informações do BD sejam obtidas.) 
       | 
console.log(L 4) 

_________________________________________________________________________________________________________________________________________ 

Código assíncrono: 

       | 
console.log(L 1) 
       | 
console.log(L 2) - consulta BD (Neste ponto o Browser, lida com esse request fora da thread) 
       |                | 
console.log(L 3)        | 
       |                | = Enquanto isso o JS, lida com o restante da thread 
console.log(L 4)        | 
                        | 
callback _______________| = e quando os dados da requisição na L 2, forem obtidos, e as execuções da thread  

terminarem de ser executadas, a função de call-back e a operação assíncrona é executada! não bloqueia o bloco.
![image](https://user-images.githubusercontent.com/38799859/189073542-5d9d31e6-cd21-45c6-bd67-391f7723d7f9.png)

`

**Comment by Roger-Melo** [comment]
Boa @renarfreitas rumo à fluência! 🔥
