### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4924]
// Utilizando classList

	1. Método add adiciona uma classe ao elemento
	2. Método remove, remove uma classe do elemento
	3. Método toggle, 
		a. Adiciona uma classe ao elemento, quando ele não existe
		b. Remove uma class do elemento, quando ele existe
	
// Diferença entre innerText e textContent

	innerText obtém o texto visível que o elemento contém
	textContent obtém todo o texto que o elemento contém mesmo visível ou não.
	
	
```js
	const paragraph = document.querySelector('p')
	
	paragraph.classList.add('error')
	
	paragraph.classList.remove('error')
	
	paragraph.classList.toggle('error')
```

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano rumo à fluência! 🔥
