### ISSUE TITLE
Resumo da Aula Stringficando e parseando dados - Aula-01-06 da etapa 13

### ISSUE THREAD

**Issue by AlessandroAscanio** [roger-melo-treinamentos/curso-de-js-roger-melo#4929]
Para armazenar dados mais complexos com um array de objetos ele precisa converter o array de objetos em string e quando obter o array do localStorage ele será uma string que será necessário conveter(parsear) a string de volta em array, exemplo:

```js
const myArray = [
  {a:1, b:2},
  {c:3, d:4},
  {e:5, f:6},
]

// Convertendo o Array em String
JSON.stringify(‘myArray’, myArray)

// Convertendo a String em Array novamente
JSON.parse(localStorage.getItem(‘myArray’))

```

**Comment by Roger-Melo** [comment]
Boa @AlessandroAscanio rumo à fluência! 🔥
