### ISSUE TITLE
Aplicação: Quiz-app

### ISSUE THREAD

**Issue by diegobaena89** [roger-melo-treinamentos/curso-de-js-roger-melo#493]
Bom dia, professor!
Terminei a primeira aplicação do seu treinamento.
O link do meu repositório onde está o quiz é este: https://github.com/diegobaena89/quiz-app
O deploy do projeto está aqui: https://nifty-khorana-900f65.netlify.app/

**Maiores dificuldades**

* Primeiramente, não tinha pensado em colocar as respostas certas em um array, mas cada resposta em uma variável diferente para, só depois, fazer a verificação com o input do usuário, um a um, o que dificultaria muito a codificação, podendo comprometer sua legibilidade. Quando me deparei com o tamanho do problema que eu mesmo tinha causado e não sabia mais o que fazer, resolvi assistir ao começo do seu desenvolvimento e aí consegui entender de uma maneira mais lógica o porquê do uso do array e não de variáveis separadas.
* Não tinha pensado no scrollTo(x,y), mesmo porque quando eu implementei os pontos a serem aparecidos na página, tinha criado uma div abaixo do botão de 'enviar' e não acima - evitando a necessidade de ter que subir a página. Mas achei a solução do scrollTo bem elegante e funcional e acabei adotando-a.
* setInterval demorou pra entrar na minha cabeça. No começo tinha colocado o setInterval como segundo parametro do addEventListener e não estava funcionando, só depois fui perceber o erro. Não tinha nem cogitado a possibilidade de fazer o contador ir do 0 à pontuação do usuário e eu nem sabia como começar a fazer isso, pra ser sincero (só´sabia que era com o setInterval). Como disse, de início mostrava unicamente a pontuação, foi a maneira q eu tinha achado. Depois que vi sua explicação, as coisas ficaram um pouco mais clarar, mas preciso estudar /aplicar mais esta função para poder asimilar melhor.

**Menores dificuldades**

* Manipulação do DOM. Fazer queries  e obter valores dos inputs.
* Manipular classes de elementos HTML com o javascript.
* Aplicar addEventListener.
* Lógica inicial da aplicação até o momento de mostrar o resultado. Depois, no caso do score ir mudando conforme pontuação do usuário, tive um pouco mais de dificuldade.
* Comparação entre respostas do usuário e respostas corretas
* Manipulação do HTML e do Bootstrap.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Diego. 

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

@diegobaena89

**Comment by Roger-Melo** [comment]
Oi Diego.

Parabéns pelo esforço em implementar a primeira aplicação =)

Antes de postar a análise, deixa eu dar uma dica...

No e-mail sobre a análise de aplicações, foi especificado que a aplicação deve ser enviada antes de assistir a aula "Exibindo a pontuação - Aula 02-01", da etapa 07.

Ou seja, o esperado era que a aplicação fosse enviada com a implementação de pontos que você conseguisse fazer e não com a implementação que mostrei na aula 02-01.

Vou deixar passar por que não tem como voltar atrás, pois você viu a aula. Mas fique atento a isso. No e-mail tem a listagem do momento em que cada aplicação do treinamento deve ser enviada para a análise. Sugiro que salve esse e-mail, você precisará voltar nele. Para localizá-lo em sua caixa de entrada, basta pesquisar por "[Alunos CJRM] Análises de Aplicações".

---

## Organização de código

### Comentários

Evite comentários na hora de subir a aplicação para produção.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Se você realmente faz questão de usar comentários como objeto de estudos, mantenha duas versões do código; a de produção (sem comentários) e a de desenvolvimento/estudos.

Uma prova que comentários mentem:

```javascript
//mostra o resultado acima do form
// spanResult.textContent = `${counterScore}%`
```

### Indentação

Indentar corretamente é fundamental. 

A indentação da declaração da `checkingAnswers` precisa evidenciar que `checkingAnswers` está dentro do bloco da função `comparingQuestions`, caso contrário a leitura do código fica confusa.

### Nomes de variáveis e funções

Evite nomear certas variáveis usando o nome do elemento que elas armazenam.

Uma const nomeada como `form` é aceitável em uma aplicação de escopo reduzido (como essa) que tem apenas 1 formulário. E geralmente, um formulário sempre será uma tag `<form>`.

Porém, uma const `spanResult` pode precisar ser renomeada caso o elemento que ela armazene seja modificado para qualquer outra tag. Neste caso, prefira omitir o nome do elemento. Você pode nomear como `resultContainer` ou `resultEl` ("El" é uma abreviação de "element").

`sameNumbers` é um nome que não descreve muito bem o valor que a const armazena. 

`displayCounter === counterScore` não é uma expressão ilegível, então neste caso, eu deixaria ela como condição do `if`.

Quando uma variável armazena um boolean, prefira nomeá-la com `is`, `has` ou `should`. É uma convenção que facilita identificar booleans no código.

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo este princípio, eu adicionaria uma linha em branco nas linhas 6 e 44.

## Lógica

### `let spanResult`

`spanResult` não precisa ser uma let.

Um objeto atribuído a uma const pode ter suas propriedades modificadas. O mesmo vale para itens de arrays (por que arrays são objetos). Consts não garantem imutabilidade. 

Uma const apenas impede que um novo valor seja reatribuído para o identificador da `const` (nome da const).

Ou seja, objetos são mutáveis por padrão e `const` não define imutabilidade, apenas evita reatribuição.

O uso de const é uma convenção para indicar, visualmente, que eu não vou mudar aquele valor. O valor que aquela const armazenar vai permanecer o mesmo em todo o decorrer da aplicação. Já quando quero indicar que o valor vai ser modificado, uso `let`.

Devo falar especificamente sobre imutabilidade mais à frente no treinamento, quando mostrar programação funcional. 

Então já que `spanResult` modifica o valor da propriedade `textContent` do objeto que ela armazena (e não o valor de spanResult), eu declararia `spanResult` como const.

---

Parabéns novamente pelo esforço, Diego =)

Os pontos que observei acima fizeram sentido?

@diegobaena89

**Comment by diegobaena89** [comment]
Bom dia, professor.
Sim, todos seus apontamentos fazem sentido. Vou me atentar a isso e refatorar este meu projeto.
Sobre o e-mail de análise de aplicações, eu acredito que eu o tenha perdido pois eu tive um problema no gmail e eu não o achei. Acredito que por isto não estava lembrado desta recomendação e acabei fazendo todo o projeto.

Existe a possibilidade de o senhor me reenviar este e-mail?


Quanto aos outros tópicos, já estão anotado e eu vou tentar aplicá-los nos próximos projetos.
Muito obrigado!

**Comment by Roger-Melo** [comment]
Enviei =)

@diegobaena89

**Comment by diegobaena89** [comment]
Muito obrigado, professor! Tudo certinho agora haha

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
