### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by EdsonAjjunior** [roger-melo-treinamentos/curso-de-js-roger-melo#4933]
Quando queremos colocar um estilo css em algo pontual, é mais preferível utilizarmos o style dentro do javascript, ao invés de utilizarmos o setAttribute. O style nos dar todas as formas que podemos alterar ou adicionar algo, seja cor, borda, margem, letra e etc. 

Sempre utilizamos ele através da notação de ponto e conseguimos adicionar ou alterar o que for necessário.

**Comment by Roger-Melo** [comment]
Boa @EdsonAjjunior rumo à fluência! 🔥
