### ISSUE TITLE
Aplicação: Conversor de Moedas

### ISSUE THREAD

**Issue by henriquesouzadev** [roger-melo-treinamentos/curso-de-js-roger-melo#4941]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/henriquesouzadev/currency-converter-app

### Maiores dificuldades durante a implementação

Nenhuma dificuldade muito grande. Apenas algumas dúvidas na hora de criar funções genéricas que pudessem ser usadas nos diferentes EventListeners.

Obs.: Eu vi uma das aulas da correção e vi que tinha faltado uma funcionalidade no primeiro select, onde troca a moeda que deve ser a base do cálculo. Então essa foi a minha maior dificuldade, não tinha entendido esse ponto.

### Menores dificuldades durante a implementação

Preencher as options dos selects com as informações da API.

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by henriquesouzadev** [comment]
Obrigado @Roger-Melo !

**Comment by Roger-Melo** [comment]
Olá @henriquesouzadev!

Parabéns pelo esforço em implementar a aplicação =)

> ### Nenhuma dificuldade muito grande. Apenas algumas dúvidas na hora de criar funções genéricas que pudessem ser usadas nos diferentes EventListeners.

Vou falar sobre isso mais abaixo, ok?

> ### Eu vi uma das aulas da correção...

Entendi que foi preciso assistir parte da correção para conseguir fazer depois. Mas se certifique-se de que você consegue construir a aplicação sozinho, combinado?

---

Sobre a `fetchCurrencyData`... Não faz sentido fazer requests sem validar e tratar possíveis erros com try/catch e if. 

Sem essas validações sua aplicação pode quebrar facilmente. 

Recomendo que faça a etapa 11 novamente para relembrar o quanto é importante tratar erros com try/catch ou then/catch e validar se o objeto que você está obtendo no request realmente é o que você espera. 

Se você apresentar o código dessa forma para um recrutador, ele pode assumir que você não tem consciência de que ter cautela ao fazer requests é fundamental, e isso definitivamente pode jogar contra você em um processo seletivo. 

☝🏻 essa observação é a mais significativa para você nesse momento e a mais importante dessa análise, por isso coloquei ela aqui no topo.

---

A invocação de `init()` pode ser a última linha do código. Isso pode ser uma precaução para não dar a impressão de que essa invocação está "perdida" ou "jogada" no meio do código.

---

Nas duas ocorrências da atribuição `internalConversionRates = { ...conversion_rates }`, não há necessidade de criar um novo objeto e espalhar as propriedades do objeto `conversion_rates` nesse novo objeto. 

Basta apenas atribuir o objeto `conversion_rates` para a let `internalConversionRates`:

```javascript
// antes
internalConversionRates = { ...conversion_rates }
```

```javascript
// depois
internalConversionRates = conversion_rates
```

---

No código abaixo, `forEach` e repetição de ternário e options podem ser eliminados.

```javascript
  Object.keys(internalConversionRates).forEach((currency) => {
    currencyOneContainer.innerHTML += currency === 'USD'
      ? `<option selected>${currency}</option>`
      : `<option>${currency}</option>`

    currencyTwoContainer.innerHTML += currency === 'BRL'
      ? `<option selected>${currency}</option>`
      : `<option>${currency}</option>`
  })
```

Saca só...

Pra deixar mais clara a separação de responsabilidades, você pode ter uma função que ao ser invocada, retorna uma string com os options.

Bora criar essa implementação por partes?

Primeiro, vamos apenas retornar o resultado de `Object.keys(internalConversionRates)`, que é um array com o código das moedas:

```javascript
const getOptions = () => Object.keys(internalConversionRates)

const init = async () => {
  const { conversion_rates } = await fetchCurrencyData('USD')
  internalConversionRates = conversion_rates

  console.log(getOptions()) // ['USD', 'AED', 'AFN', ...]
}
```

Agora, pode ser gerado um novo array que contém um option para cada item do array que `Object.keys(internalConversionRates)` retornou.

Observe que esse novo array irá conter a mesma quantidade de itens do array original. Clássico caso de uso pro `map`:

```javascript
const getOptions = () => Object
  .keys(internalConversionRates)
  .map(currency => `<option>${currency}</option>`)

const init = async () => {
  // ...

  console.log(getOptions()) // ['<option>USD</option>', '<option>AED</option>', ...]
}
```

Agora que a expressão `Object.keys(...).map(...)` está retornando o array que o map gerou, vc pode encadear o `join` nesse array pra que ele retorne uma nova string de options:

```javascript
const getOptions = () => Object
  .keys(internalConversionRates)
  .map(currency => `<option>${currency}</option>`)
  .join('')

const init = async () => {
  // ...

  console.log(getOptions()) // <option>USD</option><option>AED</option>...
}
```

Para inserir um atributo `selected` no option de uma moeda específica, vc pode inserir o código da moeda como argumento/parâmetro da função e usar um ternário para que o atributo seja inserido ou não no option:

```javascript
const getOptions = (selected) => Object
  .keys(internalConversionRates)
  .map(currency => `<option ${currency === selected ? 'selected' : ''}>${currency}</option>`)
  .join('')

const init = async () => {
  // ...

  console.log(getOptions('USD')) // <option selected>USD</option><option >AED</option>...
}
```

Observe que os options não-selecionados tem um espaço em branco antes do `>` (abertura da tag). Daqui a pouco falo mais sobre isso.

Observe também que na invocação `getOptions('USD')` não fica explícito que `'USD'` é a moeda do option que deve ser selecionado. 

Então neste caso, é interessante inserir um objeto como argumento em que o nome da propriedade deixe claro que o option com a string `'USD'` deve ter o atributo `selected`.

Ao fazer isso, o parâmetro de `getOptions` agora deve estar preparado para receber um objeto, e para não ter que inserir a sintaxe `obj.property` dentro da função, um destructuring pode ser feito no objeto recebido por parâmetro:

```javascript
const getOptions = ({ selected }) => Object
  .keys(internalConversionRates)
  .map(currency => `<option ${currency === selected ? 'selected' : ''}>${currency}</option>`)
  .join('')

const init = async () => {
  // ...

  console.log(getOptions({ selected: 'USD' })) // <option selected>USD</option><option >AED</option>...
}
```

Agora, basta atribuir o retorno de `getOptions` para `innerHTML`:

```javascript
currencyOneContainer.innerHTML = getOptions({ selected: 'USD' })
currencyTwoContainer.innerHTML = getOptions({ selected: 'BRL' })
```

Ao inserir os options no DOM, o browser remove automaticamente o espaço em branco antes de `>`. 

Compare o antes e depois:

```javascript
// antes
Object.keys(internalConversionRates).forEach((currency) => {
  currencyOneContainer.innerHTML += currency === 'USD'
    ? `<option selected>${currency}</option>`
    : `<option>${currency}</option>`

  currencyTwoContainer.innerHTML += currency === 'BRL'
    ? `<option selected>${currency}</option>`
    : `<option>${currency}</option>`
})
```

```javascript
// depois
const getOptions = ({ selected }) => Object
  .keys(internalConversionRates)
  .map(currency => `<option ${currency === selected ? 'selected' : ''}>${currency}</option>`)
  .join('')

// ...

currencyOneContainer.innerHTML = getOptions({ selected: 'USD' })
currencyTwoContainer.innerHTML = getOptions({ selected: 'BRL' })
```

A segunda versão é mais interessante por que não precisou de `forEach` e eliminou as repetições de option e ternários.

Poderia ser feito com `reduce` também, mas o código iria ficar mais complexo.

---

As invocações de `showConvertedValue` em todo o código estão recebendo argumentos, mas a declaração da função não tem parâmetros. 

Neste caso, já que os argumentos que estão sendo inseridos nas invocações dela são consts globais, eles podem ser removidos:

```javascript
// antes
showConvertedValue(currencyOneContainer, currencyTwoContainer)
```

```javascript
// depois
showConvertedValue()
```

Algo similar acontece com a `showConversionPrecision`. 

No caso dela, talvez faça sentido remover parâmetros e argumentos, já que os argumentos dela são consts globais (as mesmas de foram removidas de `showConvertedValue`):

```javascript
// antes
const showConversionPrecision = (currencyOne, currencyTwo) => {
  const currencyOneName = currencyOne.selectedOptions[0].textContent
  const currencyTwoName = currencyTwo.selectedOptions[0].textContent
  // ...
}

// ...

showConversionPrecision(currencyOneContainer, currencyTwoContainer)
```

```javascript
// depois
const showConversionPrecision = () => {
  const currencyOneName = currencyOneContainer.selectedOptions[0].textContent
  const currencyTwoName = currencyTwoContainer.selectedOptions[0].textContent
  // ...
}

// ...

showConversionPrecision()
```

`calculateConvertedValue` também pode ter parâmetros e argumentos removidos:

```javascript
// antes
const calculateConvertedValue = (currencyOne, currencyTwo) => {
  // ...
}

// ...

calculateConvertedValue(currencyOneContainer, currencyTwoContainer)
```

```javascript
// depois
const calculateConvertedValue = () => {
  // ...
}

// ...

calculateConvertedValue()
```

---

Alguns ajustes podem ser feitos na `calculateConvertedValue`, saca só...

Existem duas invocações de `calculateConvertedValue` na aplicação, elas retornam valor, mas as consts que armazenam esse valor possuem nomes diferentes. Talvez faça sentido padronizar os nomes dessas consts. As duas poderiam se chamar, por exemplo, `convertedValue`:

```javascript
// antes
const result = calculateConvertedValue()
const convertedValue = calculateConvertedValue()
```

```javascript
// depois
const convertedValue = calculateConvertedValue()
```

Quem invocar `calculateConvertedValue` irá obter um valor. Geralmente, faz sentido que funções que retornam um valor tenham um nome como `getAlgumaCoisa`. 

No caso da `calculateConvertedValue`, ela poderia se chamar `getConvertedValue`, por exemplo.

```javascript
// antes
const calculateConvertedValue = () => {
  // ...
}

// ...

const convertedValue = calculateConvertedValue()
```

```javascript
// depois
const getConvertedValue = () => {
  // ...
}

// ...

const convertedValue = getConvertedValue()
```

---

Na `showConversionPrecision`, a expressão `.selectedOptions[0].textContent` pode ser substituída por `.value`. É mais curto e continua funcionando da mesma forma.

```javascript
// antes
const currencyOneName = currencyOneContainer.selectedOptions[0].textContent
const currencyTwoName = currencyTwoContainer.selectedOptions[0].textContent
```

```javascript
// depois
const currencyOneName = currencyOneContainer.value
const currencyTwoName = currencyTwoContainer.value
```

Na template string dentro dessa função, lembre-se de substituir `internalConversionRates[currencyTwoName.value]` por `internalConversionRates[currencyTwoName]`.

Se achar que faz sentido, pode remover "Name" das duas consts.

```javascript
// depois
const currencyOneName
const currencyTwoName
```

```javascript
// depois
const currencyOne
const currencyTwo
```

---

Na maioria das vezes, é interessante nomear callbacks de addEventListeners, nem que seja um nome genérico como handleAlgumaCoisa. 

Mesmo que seja genérico, o nome ajuda a esclarecer **mais rápido** a ação mais importante que aquele callback está executando no código.

Você pode nomear os callbacks como ``, `` e ``, por exemplo.

```javascript
// antes
currencyOneContainer.addEventListener('input', async () => {
  // ...
})

currencyTwoContainer.addEventListener('input', () => {
  // ...
})

currencyOneTimesContainer.addEventListener('input', () => {
  // ...
})
```

```javascript
// depois
const handleCurrencyOneChange = async () => {
  // ...
}

const handleCurrencyTwoChange = () => {
  // ...
}

const handleTimesChange = () => {
  // ...
}

currencyOneContainer.addEventListener('input', handleCurrencyOneChange)
currencyTwoContainer.addEventListener('input', handleCurrencyTwoChange)
currencyOneTimesContainer.addEventListener('input', handleTimesChange)
```

Isso irá acrescentar um pouquinho de linhas em seu código, mas com o benefício da legibilidade o saldo é maior.

---

Lembre-se de remover o comentário no início do app.js se for subir a aplicação pra produção e colocar no portfólio, ok? =)

---

Nas próximas aulas vc verá mais possíveis abordagens de refactoring. 

O mais importante no primeiro momento você fez, que é fazer a aplicação funcionar =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
