### ISSUE TITLE
Dúvida retorno do map()

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#4945]
### Etapa da aula

15

### Nome da aula

Correção dos exercícios da aula 02 da etapa 15 - Aula 03-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/3029058

### Descreva a dúvida

Boa tarde, professor,

Na aula 03-02 da etapa 12, exercício 02, foi feito o seguinte:

```js
const removeProp = (propToRemove, objs) => {
  return objs.map(({ [propToRemove]: _, ...obj }) => obj)
}
```
Não ficou claro por que propToRemove é excluída só por ter sido atribuída para um parâmetro  " _ "  ( underscore).
É porque a propriedade "_" não existe no objeto original diferentemente de  "a" e "b"?

Na minha cabeça o resultado da removeProp(objs) seria :
```js 
[
 {a: 213, _: 965, c: 522}
 {c: 2333, a: 1321, _: 545}
 {_: 993, c: 345, a: 781}
]
```

Obrigada desde já!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

> ### Não ficou claro por que propToRemove é excluída só por ter sido atribuída para um parâmetro  " _ "  ( underscore).

Não é que ela é excluída. Ela só não é usada.

A expressão `[propToRemove]: _` dentro do destructuring está atribuindo o valor de `propToRemove` (propriedade b) para o underscore. 

Vc pode visualizar isso executando um console.log no underscore:

```javascript
const removeProp = (propToRemove, objs) => {
  return objs.map(({ [propToRemove]: _, ...obj }) => {
    console.log('_:', _)
    /*
      ☝🏻
      1ª execução: _: 965
      2ª execução: _: 545
      3ª execução: _: 993
    */
    return obj
  })
}
```

Esses valores que o underscore armazena não estão sendo aproveitados. O underscore não está sendo usado no retorno do callback do map.

Porém, se vc visualizar o valor de `obj`, verá que por ele ser um rest parameter dentro de um destructuring de objeto (`...obj`), ele é um objeto que contém o restante das propriedades do objeto pro qual a função está sendo executada. 

Ou seja, ele é um objeto que contém todas as propriedades do objeto em questão, exceto a propriedade `b`:

```javascript
const removeProp = (propToRemove, objs) => {
  return objs.map(({ [propToRemove]: _, ...obj }) => {
    console.log(obj)
    /*
      ☝🏻
      1ª execução: {a: 213, c: 522}
      2ª execução: {c: 2333, a: 1321}
      3ª execução: {c: 345, a: 781}
    */
    return obj
  })
}
```

E o callback do map está retornando apenas `obj`. Por isso o array retornado pelo map contém os objetos sem a propriedade `b`. O valor de `b` está armazenado em underscore, e underscore não está sendo usado após o destructuring.

Está ficando mais claro?

**Comment by ElaineDelgado** [comment]
Bom dia, professor!!

_"(...obj), ele é um objeto que contém o restante das propriedades "_

Nossa, eu tinha me esquecido completamente desse detalhe de que (...obj) é o **restante**  das propriedades, por isso não estava fazendo sentido pra mim. 

Obrigada, professor!

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)
