### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03 da etapa 05

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4949]
1. copy

	Com ele é posssível capturar os conteúdos que foram copiados da página usando Crl-C ou o Copy com o botão direito do mouse

2. mousemove

	Com ele é possível capturar a posição do mouse na tela
	
		offsetX = Corresponde a posição horizontal
		offsetY = Corresponde a posição vertical

3. wheel

	As propriedades pageX e pageY são similares a offsetX e offsetY, que mostram a posição do mouse.
	Contudo, esses valores são relativos a toda página.
	
		pageX = Corresponde a posição horizontal da esquerda para direita
		pageY = Corresponde a posição vertical do topo para baixo.

**Comment by Roger-Melo** [comment]
Excelente @silvasouzaadriano, rumo à fluência! 🎯
