### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4950]
A diferença entre esses dois tipos está na forma como eles são armazenados na memoria.

Tipos Primitivos
Numbers
Strings
Null
Undefined
Booleans
Symbol
BigInt

Quando atribuímos a esse tipo uma variável ou constante esse valor é armazenado em uma stack (pilha), a stack é uma pilha de diferentes valores que na memoria que podem ser acessados rapidamente quando precisamos usa-los. Mas o espaço nessa stack é limitado. 
Se criamos uma variável valores que armazena 50, e depois armazenamos essa variável a uma outra variável, uma copia do numero de valores é criada e armazenada na stack e o nome valores2 será o identificador que permitira o acesso ao a esse valor 50 que embora seja o mesmo numero estarão armazenados em posições diferentes no stack da memoria. Sendo assim caso a let valores seja alterada a let valores2 não será modificada pois o valor que ela armazena está armazenado em outra parte da memoria.

let valores = 50

let valores2 = valores

valores= 30
console.log(`valores: ${valores} e valores2: ${valores2}`)

-----------------------------------------------------------------------

Tipos de Referencia
Objetos Literais
Arrays
Funções
Datas
Todos os Outros Objetos

Quando criamos um tipo de referência, esse tipo ao invés de ser armazenado na stack será armazenado no heap (amontoado), o heap tem mais espaço disponível para que sejam armazenado objetos maiores e mais complexos, como objetos literais e arrays, contudo o heap é um pouco mais lento que o stack. Quando armazenamos um tipo de referência, esse objeto é armazenado no heap e um ponteiro que aponta para o objeto é adicionado na stack. Se armazenarmos uma variável dentro de outra como fizemos no exemplo passado e modificarmos alguma de suas propriedades, nesse caso as duas Let terão seu valor modificado, pois como um objeto é um tipo de Referencia  uma heap será criada, ligando as variáveis a um mesmo valor.

let userOne = {name: 'Hugo', score: 50}
let userTwo = userOne

userOne.name = 'Felipe'

console.log(`Usuario um: ${userOne.name} Usuario dois: ${userTwo.name}`)

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
