### ISSUE TITLE
Resumo da Aula O que são requests HTTP - Aula 01-04 da etapa 11

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#4953]
`/*
    API: Application Programming Interface, ferramenta de comunicação entre sistemas;

Requests HTTP:

    Requisição ou request: Pedido ou solicitação de informações que a API ou BD armazena;

    HTTP: Hypertext Transfer Protocol; (Principal protocolo de comunicação entre computadores na internet)

    Endpoint: URL que a API ou o servidor, disponibilizam para utilizarmos, e obtermos informações que ambos armazenam.

    Ex. de endpoint HTTP:
        http://apidemusicas.com/artista/iron-maiden

        http://meusite.com.br  ->      request HTTP      -> http://outroservidor.com
                               <- response (informações) <-
        Geralmente o formato da resposta será um JSON.
            JSON: JavaScript Object Notation

*/`

**Comment by Roger-Melo** [comment]
Excelente @renarfreitas , rumo à fluência! 🎯
