### ISSUE TITLE
Resumo da Aula 04-03 - Mais eventos do DOM da etapa 05

### ISSUE THREAD

**Issue by fabioromagnoli99** [roger-melo-treinamentos/curso-de-js-roger-melo#4956]
### Mais eventos do DOM

```jsx
const paragraph = document.querySelector('.copy-me');

// Evento que diz se o texto dentro da tag <p> foi copiado.
paragraph.addEventListener('copy', () => {
  console.log('texto copiado');
});

const div = document.querySelector('.box');

// Evento para saber a localização do mouse no eixo X e Y.
div.addEventListener('mousemove', (event) => {
  div.textContent = `X ${event.offsetX} | Y${event.offsetY} `;
});

//Evento para ver a localização da rolagem na pagina.
document.addEventListener('wheel', (event) => {
  console.log(event.pageX, event.pageY);
});
```

Copy -> Acontece quando selecionamos um texto e copiamos.

Mousemove -> O evento é disparado quando o mouse é movido sobre a área determinada. Nesse exemplo a div é a área do disparo do evento.

As propriedades do objeto event, offsetX e offsetY, representam os valores em pixel de onde o mouse se encontra, no plano horizontal e vertical respectivamente. Essa contagem é feita a partir do canto superior esquerdo do container.

Wheel-> O evento é disparado quando é feito a rolagem da página através do botão scroll do mouse. O evento é colocado no document.

As propriedades pageX e pageY são similares as propriedades offsetX e offsetY, mas os valores são relativos a toda página.

**Comment by Roger-Melo** [comment]
Excelente @fabioromagnoli99 , rumo à fluência! 🎯
