### ISSUE TITLE
Em relação ao acesso da propriedade privada de uma classe

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#4963]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 02 da etapa 14 - Aula 03-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1808746

### Descreva a dúvida

Olá Roger, bom dia!

Nessa aula em específico, você explica que podemos colocar um # antes do nome da propriedade para torná-la privada. O intuito disso é de evitar que essa propriedade seja modificada ou acessada fora da classe na qual ela foi criada.

```js
class Counter {
#count = 0

 get value (){
   return this.#count
 }

 set newValue (aNumber) {
  this.#counter = aNumber
 }
}
```
No exemplo acima, não conseguimos modificar nem acessar a propriedade count. 

```js
counter.#count = 'oi' // Não funciona, aparece um erro.
console.log(counter.#count) // Também não funciona, aparece outro erro.
```

Porém, mais para o final do vídeo, mostra-se possível modificar e acessar o valor da propriedade privada através de um método que existe dentro da classe. 

```js
console.log(counter.value) // É possível acessar o valor da propriedade privada
counter.newValue = 7 // É possível alterar o valor da propriedade privada
```

Mas aí eu fiquei em dúvida em duas coisas, se ainda é possível acessar ou modificar o valor da propriedade privada por métodos que existem dentro da classe, o valor dela não vai ser 100% imutável como o de uma const que não pode ser feito re-assignment? Se for o caso, qual o intuito de torná-la privada se ela ainda pode ser modificada em certas circunstâncias? Existe alguma forma de garantir que o valor da propriedade privada não seja acessada ou modificada em nenhuma hipótese?

É isso, agradeço desde já =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MivlaM!

Antes de responder deixa eu dar uma dica...

Se vc testar o primeiro código que postou, verá que ele está lançando um erro. 

A razão desse erro é que a expressão `this.#counter = aNumber` contém uma propriedade/field que não foi declarada. Não existe propriedade `counter` na classe. 

Por isso, é sempre fundamental testar o código e checar se ele está funcionando como vc espera, ok?

Então à partir daqui, vou pressupor que o correto é `this.#count = aNumber`.

---

> ### se ainda é possível acessar ou modificar o valor da propriedade privada por métodos que existem dentro da classe, o valor dela não vai ser 100% imutável como o de uma const que não pode ser feito re-assignment?

Ao contrário da Programação funcional, orientação à objetos é um paradigma que não dá muita importância a imutabilidade (esse é um dos problemas dele). Então nem sempre a propriedade privada será criada com o objetivo de ser imutável, saca?

---

> ### Se for o caso, qual o intuito de torná-la privada se ela ainda pode ser modificada em certas circunstâncias? 

O propósito de uma propriedade privada é não ser modificada diretamente por qualquer código fora da classe. 

Se a propriedade pode ser modificada apenas por um método que você definiu, vc pode estabelecer regras para essa mudança. Ou seja, vc tem mais controle de como a propriedade pode ser modificada, pq só os métodos que vc criou podem modificá-la.

Se alguém quer modificar o valor encapsulado, ao invés de modificar diretamente, esse alguém terá que usar os métodos que vc criou. Isso dá mais previsibilidade para a sua aplicação (além do fator risco, que eu falei sobre à partir dos 14:55 na aula que vc linkou acima). No fim das contas, encapsulamento é uma das abordagens possíveis para deixar a aplicação mais determinística (previsível).

Está ficando mais claro?

---

> ### Existe alguma forma de garantir que o valor da propriedade privada não seja acessada ou modificada em nenhuma hipótese?

Existe, mas não vejo um cenário em que isso faria sentido.

```javascript
class Counter {
  #count = 0
}

const myCounter = new Counter()

myCounter.#count // 👈🏻 erro é exibido no editor
```

No código acima, a propriedade não pode ser acessada. 

Mas se ela não pode sequer ser acessada/lida, qual é o sentido dela existir?

Já no código abaixo,

```javascript
class Counter {
  #count = 0

  get value () {
    return this.#count
  }
}

const myCounter = new Counter()

myCounter.value // 0
```

não há como modificar a propriedade, mas ela pode ser lida/usada, o que pode fazer sentido quando a propriedade deve ser privada mas não deve ter seu valor modificado.

---

Está começando a fazer sentido?

**Comment by MivlaM** [comment]
Oi Roger,

Eu estava achando que o propósito da propriedade privada era evitar com que ela fosse modificada em qualquer situação, mas agora que você me explicou, eu entendi melhor cada situação.

Agradeço =)

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
