### ISSUE TITLE
Resumo da Aula 3 escopos em JavaScript que você deve conhecer - Aula 01-03 da etapa 05

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4967]
O que é um escopo? Escopo é a visibilidade de uma variável, dependendo de onde se declara uma variável ela pode ou não ser acessada por outras partes de seu código. Existem 3 tipos de escopo, Escopo de Funções, Escopo de Blocos, Escopo de Léxico:

Escopo de Funções
Variáveis declaradas dentro do corpo de funções não podem ser acessadas fora dos limites de sua função, mesmo se invocarmos elas, essas variáveis continuaram existindo apenas dentro do escopo da função. Isso significa que podemos ter múltiplas funções que tem variáveis e constantes com os mesmos nomes dentro delas.

function dog () {
      let name = 'Zeca'
      const age = 3
      var color = 'cinza'
      console.log(age)
}

function dog2 () {
  let name = 'Sapeca'
  const age = 5
  var color = 'marrom'
  console.log(age)
}

dog ()
dog2 ()

---------------------------------------------------

Escopo de Blocos
Let e Const não podem ser acessadas fora dos blocos aonde elas são declaradas, como em um if ou em um while por exemplo, contudo a variável Var consegue sobressair do escopo dos blocos de códigos, antigamente ela só poderia ser prendida em um bloco de função.

if (true) {
   var dragon = 'Balerian'
  console.log(dragon)
}
console.log(dragon)

Nesse if, dragon pode ser acessado tanto fora como dentro do bloco de codigo por conta da regra especial de var, se ali estivesse uma let dragon ou uma const dragon, um erro iria aparecer no console dizendo que dragon não está definido.

--------------------------------------------------

Escopo de Léxico
No aninhamento de funções é possivel acessar variaveis de acordo com o seguimento de criação de escopos. Exemplo:

const external = () => {
    const greet = 'Oi'

  const internal = () => {
        const message = ` ${greet}. Seu pai tem boi?`
        console.log(message)
  }
internal ()
}

external ()

Nesse aninhamento de funções a const internal consegue acessar as variáveis de external,  mas não o contrario. External não pode acessar a const message por exemplo, e conforme houvesse mais aninhamento de funções, as funções "de baixo" conseguem acessar as variaveis das funções "de cima", mas as funções de cima não conseguem acessar as variáveis das funções de baixo.

**Comment by Roger-Melo** [comment]
Show @Hugones45 . Vamo que vamo, rumo à fluência! 🙌
