### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#4970]
- document.createElement( )
Como o nome sujere, este propriedade cria um elemento do DOM.
E pare remover um elemento, como ja visto, e utilizado .remove( )

- append( ) e prepend( )
E para inserir o elemento criado utiliza-se append( ) que adiciona no final da lista e prepend( ) que adiciona no inicio da lista.

**Comment by Roger-Melo** [comment]
Show @YukOnRails . Vamo que vamo, rumo à fluência! 🙌
