### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#4984]
Três maneiras alternativas de fazermos queries no DOM e obter referencia dos elementos.

OBTER ELEMENTO ATRAVÉS DO ID

No código HTML o h1 um estará com um id nomeado de title.

<   h1 id="title">Outras maneiras de fazer queries no DOM<   /h1 >

const title = document.getElementById('title')

console.log(title)

Essa expressão vai resultar na referencia do elemento que tem esse id title.

------------------------------
OBTER ELEMENTOS ATRAVÉS DO NOME DA CLASSE

Olhando para a estrutura do HTML dessa aula, temos um p com a classe erro e uma div também com essa classe.

const erros = document.getElementsByClassName('erro')

Dentro da invocação desse método passamos como argumento o nome da classe dos elementos que queremos obter, no caso, erro. E novamente como esse método já e especifico pro nome da classe não precisamos inserir um ponto no inicio do nome da classe, pois isso já esta implícito nesse método.

console.log(erros)
ou
console.log(erros[1])
Assim como em um NODE LIST, podemos inserir a notação de colchetes para selecionar um item em particular.

Quando inserimos o console obtemos um HTML colection com dois itens que são as referencias dos elementos da pág que tem a classe erro. Um HTML colection representa uma lista genérica de elementos, NODE LIST e HTML colection são similares mas não idênticos. No geral existem menos métodos e opções para se trabalhar com HTML colection.

----------------------------------------------------------------

OBTER ELEMENTOS ATRAVÉS DO NOME DA TAG

const paragraph = document.getElementsByTagName('p')

console.log(paragraph)
ou
console.log(paragraph[2])

Obter elementos através da tag também aceita a notação de colchetes.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45 , rumo à fluência! 🎯
