### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 10 - Aula 01-01

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#4986]
### Etapa da aula

10

### Nome da aula

Correção dos exercícios da aula 02 da etapa 10

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1154164

### Descreva a dúvida

O código abaixo, a depender da validação do ternário, irá retornar 2 valores distintos (string e number). Isso é igualado por debaixo dos panos? Se não, haveria algum problema?

````
const formatTimeUnit = unit => String(unit).length == 1 ? `0${unit}` : unit

const num = 8
const num2 = 12
console.log(formatTimeUnit(num), formatTimeUnit(num2));
// output 08 (string) e 12 (number)
``

<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @aecio-neto!

Antes de responder, deixa eu dar uma dica...

Ao fazer comparações, prefira usar o comparador de igualdade estrita (`===`). Ao usá-lo, você evita que coisas desse tipo aconteçam na sua aplicação:

```javascript
console.log(2 == '2') // true
```

Quando o duplo sinal de igual é usado (operador `==`), uma comparação que envolve tipos diferentes pode resultar em `true`. 

Recomendo que veja novamente a aula [Comparações com igualdade estrita](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/751262). Nela eu explico com detalhes pq vc deve dar preferência ao `===` ao invés de `==`, ok? =)

---

> ### Isso é igualado por debaixo dos panos?

Não.

O ternário apenas retorna o valor, sem fazer conversão de tipo.

Você pode comprovar isso ao visualizar o valor no console e/ou visualizar o tipo do valor com o`typeof`: 

```javascript
const formatTimeUnit = unit => String(unit).length === 1 ? `0${unit}` : unit

console.log(formatTimeUnit(1)) // '01'
console.log(formatTimeUnit(10)) // 10

console.log(typeof formatTimeUnit(1)) // string
console.log(typeof formatTimeUnit(10)) // number
```

> ### Se não, haveria algum problema?

Depende se o ponto onde esse valor será usado está esperando apenas um tipo específico de valor. 

Nos casos mostrados no vídeo, o valor que `formatTimeUnit` retornou é usado onde o esperado é que o retorno seja uma string. E como nesses casos há uma conversão automática de tipos (número para string), não há grandes preocupações nesse sentido. 

Mas vc também tem a opção de fazer com que o tipo que o ternário retorne seja apenas string, se quiser deixar isso explícito no código =)

Respondi a dúvida?

**Comment by aecio-neto** [comment]
Ótimo, respondido.

**Comment by Roger-Melo** [comment]
Massa! Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
