### ISSUE TITLE
Resumo da Aula Refatorando a limpeza da ul dos games 03-12 da etapa 15

### ISSUE THREAD

**Issue by Kmkery** [roger-melo-treinamentos/curso-de-js-roger-melo#4990]
Quando a página da aplicação de games é carregada ou quando o `collection` é alterado, o `snapshot` (antes nomeado como `querySnapshot`) recebe todos os `documents` do `collection`. Se inserirmos um `console.log(snapshot.docs)` na primeira linha após o `if` da `renderGamesList`, ao recarregarmos a página, vemos no console todos os `documents` do `collection`. E, quando adicionamos um novo item, vemos estes `documents` acrescidos de um, evidenciando que o `snapshot` foi alterado. Porque o banco de dados foi alterado, a função que renderiza é chamada novamente, criando novamente os itens, fazendo assim duplicatas. 

Na aula anterior, para resolver o problema de duplicatas na renderização da página, inserimos um `gamesList.innerHTML = ' '` antes da execução da renderização, isto para garantir que o conteúdo fosse renderizado apenas uma vez, evitando assim as repetições indesejadas. No entanto, esta não é a melhor prática para evitar este tipo de problema. 

Podemos usar o método `.docChanges()` para selecionar os documents que queremos trabalhar, desta forma conseguimos determinar quais e quando devem ser renderizados. 

Se substituimos o `console.log(snapshot.docs)` por `console.log(snapshot.docChanges())`, quando a página é recarregada vemos um array de objetos os quais representam cada `document` adicionado no banco de dados, cada um com uma propriedade `type: 'added'`. Quando adicionamos um novo item, a `docChanges()` resulta em um array de um único item, com a propriedade `type: 'modified'`, indicando que o `collection` foi modificado. Ao recarregar a página, `docChanges()` resulta em outro array, agora com todos os itens existentes da `collection` e propriedades `type: 'added'`. Se acaso um `document` for deletado do banco, `docChanges()` irá resultar em um array de único item, com propriedade `type: 'removed'`, indicando um `document` removido. 
Tomando como base as três propriedades `type` possíveis, conseguimos então determinar quando um determinado item deve ser adicionado na renderização. Usando `snapshot.docChanges().forEach(docChange => {})`, dentro dele inserimos a condicional que testa cada caso de `type`, desta forma, podemos permitir que as lis sejam criadas de acordo com o que desejamos. 

Para que as lis sejam criadas, `type` deve ser `'added'` ou `'modified'`. Dentro desta condição, colocamos o código anteriormente usado (escopo do `snapshot.doc.map()`) com algumas alterações. No lugar de `doc`, agora usamos o `docChange.doc`, eliminamos a constante `game` e inserimos `gamesList.append(liGame)` no fim do bloco. 

Para remover a `li` quando clicamos no botão remover, quando `type` for `'removed'`, referenciamos o `id` do elemento clicado e executamos o método `.remove()` nele. 

Encapsulamos todo o código responsável pela renderização em uma função `renderGames(docChange)` e alteramos a condicional `if (snapshot.metadata.hasPendingWrites)`, removendo de dentro dele todo o código e colocando no lugar um `return` (técnica **return early**), para remover ifs aninhados e assim melhorar a legibilidade.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Kmkery , rumo à fluência! 🎯
