### ISSUE TITLE
Resumo da Aula Eventos do teclado - Aula 02-03 da etapa 06

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#4993]
### insertAdjacentElement - Insere um elemento em relação ao elento pai passado como parâmetro (primeiro argumento)

Nota: forEach() - Não existe uma maneira de parar ou interromper um forEach(), a não ser lançando uma exception.
Caso seja necessário executar esse comportamento, recomenda-se usar: 
	
	1. A simple for loop
	2. A for...of / for...in loops
	3. Array.prototype.every()
	4. Array.prototype.some()
	5. Array.prototype.find()

**Comment by Roger-Melo** [comment]
Excelente @silvasouzaadriano, rumo à fluência! 🎯
