### ISSUE TITLE
Há diferenças ?

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#4998]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/824585

### Descreva a dúvida

Olá, pessoal.

Na correção do exercicio 07, fiz da forma abaixo:

```js
let dog = {
  name:'bindy',
  age: 8,
  color: 'branca',
  bestFriends: ['maia','billy','pitty'],
  sound: function (){
    return 'au, au!'
  }
 }

 const somaAge = (message) =>  {
  const result = cat.age + dog.age

  console.log(`${message}${result}`);
}
 somaAge(`A soma das idades de ${cat.name} e ${dog.name} é `)
 ```

Prof Roger fez da seguinte forma:

```js
 let dog_ = {
  name:'Charles',
  age: 3,
  color: 'Marron',
  bestFriends: ['Milton','Joaquim'],
  sound: function (){
    return 'wooooof'
  }
 }

 const getAgeMessage = (cat, dog) => `A soma das idades de ${cat.name} e ${dog.name} é ${cat.age + dog_.age} `

 const ageMessage = getAgeMessage(cat, dog_)

 console.log(ageMessage);
 ```
Minha dúvida é se existe algo de equivocado em minha resolução, em questão de performace, semântica ou lógica em comparação  com a resolução do prof. Roger. Pois, ainda que o resultado sejam os mesmos, gostaria de saber, por gentileza, para não criar "vicios".

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Bruno-Luna!

É normal ter essas preocupações no início, é um indicativo de que vc quer fazer com excelência.

Há um princípio que pode te ajudar quando essas preocupações vierem, que é o seguinte: **Feito é melhor que perfeito**.

Isso por que podem haver vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar =)

---

> ### em questão de performace, semântica ou lógica em comparação

Não se preocupe com performance nesse momento. Esse é um assunto que será abordado apenas na etapa 14 pq eu sinto que é nesse ponto da sua jornada à Fluência que você deve começar a pensar sobre isso. 

Sobre semântica e lógica, essas são habilidades que você irá melhorar conforme for praticando. E vc ainda praticará bastante no CJRM, então também recomendo que não foque nisso em excesso agora. Seguindo o princípio que mencionei ali no primeiro parágrafo dessa resposta, vc estará caminhando o passo a passo que te deixa cada vez mais próximo da Fluência =)

**Comment by Bruno-Luna** [comment]
Olá, @Roger-Melo. Bom dia!
Agradeço as suas palavras, que por sinal são de quem já passou por esse processo! 
Muitíssimo obrigado.
