### ISSUE TITLE
Quiz Super Heroes Marvel

### ISSUE THREAD

**Issue by tuxpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#5]
**Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;**
-> Refatorar o código
-> Demorei bastante para compreender que input radio não tem evento checked kkkkk
-> Acredito que ficaria melhor se tivesse feito usando um checkbox

**Link:**
https://github.com/tuxpedro/quiz-super-heroes

Gostei do exercício nesse formato ;-)

Vlw um abraço.

**Comment by Roger-Melo** [comment]
Boa @tuxpedro ! Legal o quiz =)

Observe que a div que exibe o resultado final do quiz contém a classe `scoreboard`, com "b" minúsculo e na const que obtém a referência dessa div, o nome da classe foi passado como `scoreBoard`, com "b" maiúsculo. Isso faz com que na linha 24, `scoreBoard` seja null e não receba o 'inline-block' como display, lançando um erro no console ao invés de exibir o resultado do quiz.

Eu havia esquecido de inserir na descrição do exercício que apenas o que vimos até aqui no curso deveria ser usado, hahah (ainda vamos falar sobre ternário).

> -> Acredito que ficaria melhor se tivesse feito usando um checkbox

É uma alternativa também =)

Sobre o refactoring do código, isso vem com a prática. Ainda vamos praticar muito refactoring no curso.

Mas o importante é primeiro fazer funcionar, como você fez! A partir disso, com o conhecimento que você for adquirindo, você pode voltar e melhorar o que você já fez nessa aplicação.
