### ISSUE TITLE
Etapa 03 - Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#50]
Roger fiquei na duvida para fazer essa questão.
Ela retorna um função inteira.
Nessas horas eu nunca vi algo parecido travo, aí vou pesquisar
no google e mdn, aí fico tentando o máximo possível até sair fumaça da cabeça rs.
quando vejo que não jeito vou para a correção.

Quero muito ser fluente js, mais estou vendo que não é do dia para noite que
que vou ficar fluente, preciso ter base, praticar e ter teoria.

Parece que não entra na cabeça, se vc não ficar ali em cima direto. 

/*
  07

  - Forme uma frase com o array abaixo e exiba-a no console.
*/

````const functions = [
  function () { return 'Plymouth' },
  function () { return 'é' },
  function () { return 'uma' },
  function () { return 'cidade' },
  function () { return 'fantasma' },
  function () { return 'localizada' },
  function () { return 'na' },
  function () { return 'ilha' },
  function () { return 'de' },
  function () { return 'Montserrat,' },
  function () { return 'um' },
  function () { return 'território' },
  function () { return 'ultramarino' },
  function () { return 'do' },
  function () { return 'Reino' },
  function () { return 'Unido' },
  function () { return 'localizado' },
  function () { return 'na' },
  function () { return 'cadeia' },
  function () { return 'de' },
  function () { return 'Ilhas' },
  function () { return 'de' },
  function () { return 'Sotavento' },
  function () { return 'nas' },
  function () { return 'Pequenas' },
  function () { return 'Antilhas,' },
  function () { return 'Índias' },
  function () { return 'Ocidentais.' }
]

let frase = []

for(let i = 0; i < functions.length; i++){
  frase.push(functions[i])
}

console.log(`${frase}`) 

```




@Roger-Melo

**Comment by naldowebdeveloper** [comment]
@Roger-Melo acabei resolvendo assim, fiquei tentando de várias formas
e pesquisando.

As vezes fico com medo medo de fazer gambiarra e não acabo nem fazendo,
coloquei na minha cabeça que que começar nem que seja fraco e ir melhorando. 

```let frase = []

for(let i = 0; i < functions.length; i++){
  frase.push(functions[i]())
}

console.log(`${frase.join(' ')}`) ```

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Apenas uma dica: quando for abrir uma issue, coloque o nome do vídeo no título da issue. Assim fica mais fácil eu encontrar a aula. Editei o título dessa issue =)

---

> Ela retorna um função inteira.

Na verdade, o código que você deixou acima retorna uma string de funções separadas por vírgula. E existe uma razão para isso que não é importante agora, vai ser falada mais à frente.

Observe que se você invocar um `console.log()` para visualizar o valor que está sendo adicionado no array à cada execução do `for`, verá que o que está sendo adicionado no array são as referências das funções:

```javascript
let frase = []

for(let i = 0; i < functions.length; i++){
  console.log(functions[i]) // exibe o valor que está sendo adicionado no array à cada iteração
  frase.push(functions[i])
}

console.log(`${frase}`)
```

Ou seja, se na invocação do `console.log()` eu substituir a template string apenas pelo array `frase`,

```javascript
console.log(frase)
```

o console exibe o array preenchido com as funções do array `functions`.

Se a expressão `functions[i]` resulta na referência de uma função, o que você pode mudar nessa expressão para que ela resulte no valor que a função retorna?

---

Recomendo fortemente que a cada passo que você der no código, verifique se os valores com os quais você está trabalhando são os que você espera. O segredo está em fazer um pouco e checar, a cada passo. Faça um passo de cada vez, sem pressa e sempre verificando os valores no console. 

Ao abrir os blocos de um `for`, exiba no console os valores que estão dentro do bloco dele. Faça o mesmo para funções, ifs, switch's ou qualquer outro tipo de instrução que esteja lidando com valores.

**Use e abuse do `console.log()`**, ele é seu amigo =)

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo valeu pela explicação vou ficar mais atendo.

**Comment by Roger-Melo** [comment]
Show que está ficando mais claro Ednaldo! No início é complicado mesmo, crescer dói. Mas no que precisar para chegar na fluência em JavaScript, pode contar comigo.

Vou fechar a issue mas quando surgirem mais dúvidas, é só abrir uma nova =)
