### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by LWagg** [roger-melo-treinamentos/curso-de-js-roger-melo#5008]
Diferenças entre LET E CONST.

LET - Pode-se atribuir outro valor quando a variável é declarada com LET.
CONST - Não se pode atribuir outro valor quando é declarado com CONST.

Regras e boas práticas para declarar variáveis.
Instruções sobre como comentar em código. Sempre comentar com o intuito de ajudar futuras manutenções.

**Comment by Roger-Melo** [comment]
Boa @LWagg  rumo à fluência! 🔥
