### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01 

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5012]
**O pepel de um variável e armazenar um valor assim podemos usar em outro parte do código 
 var 
let
const** 

### LET
```
let age = 25;

// age agora possuí 31 armazenado
// o = é operador de atribuição, ler ser "atribua 31 a variável age"
```

o console.log ele pode recebe mais de um valor separando por virgula
`console.log('Ola mundo', age);`

### VAR
var e forma antiga q usava para da nome a variáveis.
`var myAge = 25`

### CONST
const: utilize quando você precisar declarar constantes, ou seja, você não quer haja uma nova atribuição de valor para uma variável durante a execução do bloco
`const myName = 'Everton Mattos'`

### Regras para nome da variáveis:
- Não pode ter espaço entre elas, use camelCase.
- Não podemos utilizar palavras reservada da linguagem.
- Não pode começar por números 

### Comentarios
```
Comentarios de uma linha iniciam com // meu comentário de linha
Comentário com multiplas linhas /* Comentário em bloco */
```

**Comment by Roger-Melo** [comment]
Boa @EvertonMattos  rumo à fluência! 🔥
