### ISSUE TITLE
Resumo da Aula 02-03 Strings da etapa 01

### ISSUE THREAD

**Issue by Diegokraus** [roger-melo-treinamentos/curso-de-js-roger-melo#5017]
//strings
console.log('hello, world');

const email = 'leon@rogermelo.com.br'
console.log(email);

//concatenação de strings
const firstName = 'Nathan'
const lastName = 'Drake'
const fullName = firstName + ' ' + lastName
console.log(fullName);

//acessando caracteres
console.log(fullName[2]);

//comprimento de uma string
console.log(fullName.length);

//metodos de string
console.log(fullName.toUpperCase()); //deixa as letras maiusculas

const result = fullName.toLowerCase()); //deixa as letras minusculas
console.log(result, fullName);

const index = email.indexOf('@')  //O que está dentro do parêntese é um argumento.
console.log(index);

//qualquer caractere entre '' é uma string, podendo ser letra ou numero.(encadeamento de caracteres envolvidos por aspas)
//strings tem propriedades como a length, usamos a notaçao de .nome da propriedade
//strings podem ser concatenadas por sinal de +
//strings tem métodos ou funções, pedaços de códigos embutidos do javascript que executam uma ação com ();

**Comment by Roger-Melo** [comment]
Boa @Diegokraus rumo à fluência! 🔥
