### ISSUE TITLE
Resumo da Aula Adicionando o JavaScript a uma página web - Aula 01-04 da etapa 00

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5024]
Com mesmo html da aula anterior foi removido o script da tag body e no diretório raiz do projeto na pasta Aula-01 foi criado um arquivo App.js e no html inserido a tag script novamente que não tem conteúdo e foi declarado um atributo src que vai receber o caminho do arquivo App.js <script src="./App.js"></script> e os códigos escritos nesse arquivo App.js vão ser apresentados junto com o html no browser.

**Comment by Roger-Melo** [comment]
Boa @Dieison37  rumo à fluência! 🔥
