### ISSUE TITLE
Correção dos exercícios da aula 01 da etapa 11 - Aula 02-01

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#5025]
### Etapa da aula

11

### Nome da aula

exercícios da aula 01 da etapa 11 

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1181723

### Descreva a dúvida

Não é uma dúvida, é uma sugestão. 

A forma como o exercício 5 está escrita pode ser melhorada. Sugiro adicionar a exceção de mudança do nome através de bracket notation também. 

```JS
/*
- Abaixo da declaração do objeto "car", modifique a cor do carro para 'azul';
- Não insira `car.color = azul`.
- Não insira `car[ 'color'] = azul`.
*/
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @aecio-neto!

> ## Sugiro adicionar a exceção de mudança do nome através de bracket notation também.

É algo que pode ser adicionado também, visto que o intuito do exercício é modificar a cor do objeto `car` sem usar a notação de pontos e a de colchetes. Boa observação!

O enunciado do exercício já foi atualizado para uma versão mais completa, mais uma vez, agradeço pela observação =)

**Comment by aecio-neto** [comment]
👍🏻

**Comment by MivlaM** [comment]
Massa! Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
