### ISSUE TITLE
Exercício 7 | Aula 01 da Etapa 11

### ISSUE THREAD

**Issue by aecio-neto** [roger-melo-treinamentos/curso-de-js-roger-melo#5026]
### Etapa da aula

11

### Nome da aula

Exercícios da aula 01 da etapa 11

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1181723

### Descreva a dúvida

Minha solução ficou um pouco diferente. Dúvidas: 
Quais os prós e contras de fazer assim? 
O que pode ser refatorado? (ainda tenho bastante dificuldade com refatoração, não entendo quais são os princípios para se levar em conta na hora de fazer.)

```JS
booksBox.addBooks = (books => {
  if (booksBox.spaces === 0) {
    return 'A caixa já está cheia.'
  }
  else if (books > booksBox.spaces) {
    return booksBox.spaces === 1 
    ? 'Só cabe mais um livro na caixa' 
    : `Cabem apenas ${booksBox.spaces} livros na caixa.`
  }
  else if (books <= booksBox.spaces ) {
    booksBox.booksIn += books
    booksBox.spaces -= books
    return booksBox.booksIn === 1 
    ? `Já há ${booksBox.booksIn} livro na caixa.`
    : `Já há ${booksBox.booksIn} livros na caixa`
  }
})

// debugging
console.log(booksBox.addBooks(1));
console.log(booksBox.addBooks(2));
console.log(booksBox.addBooks(3));
console.log(booksBox.addBooks(2));
console.log(booksBox.addBooks(2), booksBox);
// output spaces = 0, booksIn = 5
```

@Roger-Melo

**Comment by aecio-neto** [comment]
Versão refatorada: 

```JS
booksBox.addBooks = (books => {
  const boxFull = booksBox.spaces === 0
  const boxHasNotEnoughSpace = books > booksBox.spaces
  const boxHasSpace = books <= booksBox.spaces

  if (boxFull) {
    return 'A caixa está cheia.'
  }
  else if (boxHasNotEnoughSpace) {
    return booksBox.spaces === 1 
    ? 'Só cabe mais um livro na caixa' 
    : `Cabem apenas ${booksBox.spaces} livros na caixa.`
  }
  else if (boxHasSpace) {
    booksBox.booksIn += books
    booksBox.spaces -= books
    return booksBox.booksIn === 1 
    ? `Há ${booksBox.booksIn} livro na caixa.`
    : `Já há ${booksBox.booksIn} livros na caixa`
  }
})
```
Ps - Trabalhei modificando ambas as propriedades (space e booksIn).

**Comment by MivlaM** [comment]
Olá @aecio-neto!

É normal ter essas preocupações quando se está aprendendo no início, é um indicativo de que vc quer fazer com excelência.

Há um princípio que pode te ajudar quando essas preocupações vierem, que é o seguinte: Feito é melhor que perfeito.

Isso por que podem haver vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Com a prática, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, saca? =)

Vi que você refatorou uma parte, boa! Se você quiser uma refatoração mais precisa do exercício, sugiro que siga como foi feito na correção, lá tem uma refatoração apropriada para esse caso. Mas sobre a dificuldade em refatoração, essa é uma habilidades que você irá melhorar conforme for praticando. E vc ainda praticará bastante no CJRM, então também recomendo que não foque nisso em excesso agora. Seguindo o princípio que mencionei ali no primeiro parágrafo dessa resposta, vc estará caminhando o passo a passo que te deixa cada vez mais próximo da Fluência =)

---

Respondi a dúvida? Se ficou com dificuldade em algo mais específico me avisa por aqui que eu te ajudo =)

**Comment by aecio-neto** [comment]
Ok. 

Obrigado
