### ISSUE TITLE
Etapa 02, nome do vídeo: Correção dos exercícios da aula 04 da etapa 01

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#503]
Olá Roger, tudo bem? Por que, no exercício 09, para verificar se a randomTVShow era uma string, foi preciso usar aspas e  a letra s minúscula e não declarar o tipo de dado como fazemos normalmente como String? Essa eu não acertava por conta disso, eu inventei um workaround sem pé nem cabeça que funcionou e só pra você não ficar curioso e dar boas risadas, taí:
```js
const isNotAString = Number(randomTVShow) === String

console.log(isNotAString) // false
```
Enfim, refiz  **todo**  o exercício, demorei mais algum tempo e encontrei a mesma solução sua, mas, porquê ?
```js
const isNotAString = typeof randomTVShow !== 'string'
  
console.log(isNotAString ) // false and true answer
```

@Roger-Melo

**Comment by WebDevCampos** [comment]
Entendi, agora ficou claro.

Em seg, 19 de abr de 2021 16:08, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Legal @WebDevCampos. Já que ficou mais claro vou fechar a issue, mas no que precisar, é só abrir uma nova =)
