### ISSUE TITLE
Resumo da Aula Conversão de tipos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by acdona** [roger-melo-treinamentos/curso-de-js-roger-melo#5030]
# Conversão de tipos
### Exemplo:
```
let score ='100'
console.log(score + 1) // out 1001

score = Number(score)
console.log(score + 1) // out 101
```
### para verificar o tipo de um dado utiliza-se o operador typeof

```
console.log(typeof score) // out string
```
#### 
    - false
    - 0
    - "", '', `` 
    - null
    - undefined
    - Na
#### Valores truthy:
    - Qualquer valor não falsy
#### Exemplo:
```
console.log(Bolean('0')) // out true
```

**Comment by Roger-Melo** [comment]
Show @acdona . Vamo que vamo, rumo à fluência! 🙌
