### ISSUE TITLE
Resumo da Aula Event bubbling e event delegation - Aula 04-02 da etapa 05

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5037]
- Event bubbling
E a propagacao de um evento que foi acionado e que pode acionar outros eventos como um efeito em cadeia, em um elemento pai (parent) por exemplo, caso nele haja um event listener esperando por este gatilho.

- Event delegation
E uma funcionalidade atraves do Event bubbling que visa a interacao direta com um objeto do DOM atraves de um evento por exemplo. Usando o event.target obtemos o elemento em questao que utilizando o event bubbling e possivel automatizar de certa forma alguns comandos ao inves de coloca-los diretamente la, podendo ser gerados de forma interativa.

**Comment by Roger-Melo** [comment]
Show @YukOnRails . Vamo que vamo, rumo à fluência! 🙌
