### ISSUE TITLE
Aplicação: Quiz App

### ISSUE THREAD

**Issue by Lkoshoji** [roger-melo-treinamentos/curso-de-js-roger-melo#504]
Olá Roger, 
Segue o [link](https://github.com/Lkoshoji/quizApp) do repositório da aplicação do quiz que fiz. 

Maiores dificuldades:

Eu ainda tenho dificuldades na parte de refatoração do código e dar nomes relevantes para  as variáveis.

Tentei fazer a refatoração do código que insere o score do usuário na DOM de forma semelhante ao que você mostrou na aula onde você nos apresenta o 'insertAdjacentElement', porém, não tive muito sucesso.

Eu fiz um 2 objetos, _userSuccessInfo_ e _userFailsInfo_, as quais armazenavam 2 propriedades: text e className.  Após isso, fiz uma função com o parâmetro _userInfo_ e depois declarei uma const com o destructuring do parametro passado na funçao e os invoquei nos lugares corretos.
Porém, a função só funcionava quando eu deixava a declaração desses 2 objetos dentro no listener do 'Submit', após o forEach.

Menores dificuldades:

Lógica do quiz.
Manipulação de objetos no dom.

Estou gostando muito do curso e sinto realmente uma evolução. 

Muito Obrigado!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Leandro. 

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

@Lkoshoji

**Comment by Roger-Melo** [comment]
Olá Leandro.

Primeiramente, parabéns pelo esforço. Deu pra perceber que você pegou bem a lógica para implementar a aplicação =)

Vou deixar abaixo pontos de atenção, seguindo alguns critérios.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no `input` type radio a ser exibido por padrão como "marcado".

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele acredita que seja a verdadeira.

### Local da exibição dos pontos

O print abaixo foi tirado logo após o envio do form:

![print-envio-form-quiz-leandro](https://user-images.githubusercontent.com/29297788/115566670-d657ca00-a290-11eb-9a9f-b40e0203ca21.jpg)

Quando o form é enviado, os pontos são exibidos na parte inferior da tela e boa parte do feedback visual fica comprometida. Uma alternativa seria exibir os pontos próximo do local para onde o usuário está olhando quando envia o form (botão).

Nas aulas seguintes eu mostro uma forma de inserir os pontos na tela, mas é bom ficar atento à isso. Ao inserir um elemento na tela, certifique-se de que ele está bem posicionado em relação ao olhar do usuário.

## Lógica

Nas invocações da `addUserScoreIntoDOM`, não é necessário aninhar template strings e interpolações. Basta inserir abertura, conteúdo e fechamento da tag e as interpolações das variáveis. Olha só:

```javascript
// antes
`<p>${`String ${const1} outra string ${const2} última string`}<p/>`

// depois
`<p>String ${const1} outra string ${const2} última string<p/>`
```

## Organização de código

### Local de declaração de variáveis

Ao declarar variáveis que contém elementos do DOM, prefira deixá-las no topo do código. Isso é uma convenção que facilita encontrar esse tipo de variável.

Então eu organizaria as variáveis no topo do código dessa forma:

```javascript
const form = document.querySelector('form')
const userResultDiv = document.createElement('div')

const corretAnswers = ['D', 'A', 'B', 'B', 'C', 'D', 'C', 'A']

let score = 0
let userCorrectAnswersAmount = 0
```

Variáveis que armazenam elementos criados no js podem ser separadas (visualmente) das demais. Mas como só há uma variável que armazena um elemento do DOM, para não deixar "buracos" no código, é preferível manter juntas as duas variáveis relacionadas a elementos. 

Vou falar mais sobre essa separação visual no tópico `Linhas em branco`, lá em baixo.

### Nomes de variáveis e funções

Cuidado ao nomear certas variáveis usando o nome do elemento que elas armazenam.

Uma const nomeada como `form` é ok em uma aplicação de escopo reduzido (como essa) que tem apenas 1 formulário. E geralmente, um formulário sempre será uma tag `<form>`.

Porém, uma const `userResultDiv` pode precisar ser renomeada caso o elemento que ela armazene seja modificado para qualquer outra tag. Neste caso, prefira omitir o nome do elemento. Você pode nomear como `userResultContainer` ou `userResultEl` ("El" é uma abreviação de "element").

`corretAnswers` pode ser renomeada para `correctAnswers`.

### Indentação

Ao quebrar em linhas diferentes os argumentos da invocação de uma função, prefira indentá-los para que fique mais rápido identificar que eles são argumentos:

```javascript
// antes
addUserScoreIntoDOM(
`<p>Olá<p/>`, 
'result-div-success')

// depois
addUserScoreIntoDOM(
  `<p>Olá<p/>`, 
  'result-div-success')
```

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos. 

Seguindo esse princípio, eu adicionaria uma linha em branco na linha 44 e deixaria apenas uma linha em branco entre as linhas 8 a 10 e 53 a 55.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

---

Novamente, parabéns pela aplicação. Curti muito o tema, a nostalgia bateu. Eu colecionava álbuns de figurinhas da copa quando criança, tive uma certa familiaridade com os uniformes =)

![album-copa-98](https://user-images.githubusercontent.com/29297788/115592123-3d817880-a2a9-11eb-8fc8-6d13bcd692ce.jpg)

---

As observações acima fizeram sentido?

@Lkoshoji

**Comment by Lkoshoji** [comment]
Boa tarde Professor,

Muito obrigado pela revisão e apontamentos.

Fizeram muito sentido sim!

Eu já vi os vídeos seguintes a essa aula e inclusive fiz o exercício 2. 

Além de aplicar o que aprendi nas aulas seguintes, vou colocar em prática os pontos levantados aqui!


Mais uma vez, muito obrigado!!
