### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5040]
As variáveis let, const e var são para armazenar valores. no caso da let pode-se atribuir mais valores sendo que a partir do segundo não precisa inserir a variavél let novamente. Na const não pode ser atribuido outros valores, use-se somente para atribuir um valor.  A forma antiga de se declarar variavéis é pela palavra var. As regras para se declarar variáveis onde só se usa uma palavra é em forma de camelCase pela convenção na primeira regra, na segunda regra os nomes das variáveis podem conter somente  letras, números, anderscors ou sifão mas o nome não pode começar com números. Terceira regra, em certos nomes são palavras reservadas, exemplo let e const não se pode declarar uma variável dessa forma "let const" pois vai dar erro no código. Os comentários por linha são começados com // e em várias linhas /* código */.

**Comment by Roger-Melo** [comment]
Show @Dieison37 . Vamo que vamo, rumo à fluência! 🙌
