### ISSUE TITLE
Resumo da Aula 01 da etapa 06

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5043]
![1 1](https://user-images.githubusercontent.com/71138743/191637228-ae4fbae1-8015-4c22-98dd-7f7c9f20ad83.png)
![1 2](https://user-images.githubusercontent.com/71138743/191637226-4b81a020-f412-43c5-95c0-defe68994844.png)
![1 3](https://user-images.githubusercontent.com/71138743/191637225-70309029-7945-4636-a267-9bc65b84e5e7.png)
![1 4](https://user-images.githubusercontent.com/71138743/191637224-d31acb7f-b454-4d9c-9ede-87706993a0be.png)

**Comment by Roger-Melo** [comment]
Show @Ale557333 . Vamo que vamo, rumo à fluência! 🙌
