### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5046]
### VARIÁVEL

A função de uma variável é armazenar um valor para você, pode ser um nome, email ou um número.
Você pode usar esse valor mais tarde se quiser.

### FORMAS DE DECLARAR UMA VÁRIAVEL

Existem várias formas de declarar uma váriavel no javascript, umas delas é com o LET.

O símbulo **"="** no javascript significa RECEBE.

**LET** = Cria uma váriavel que pode ter o valor alterado.

**CONST** = Cria uma váriavel que o valor não pode ser alterado.

Se você quiser reatribuir o valor de uma variável, só precisa escrever o nome da variável e o novo valor. Exemplo: 

```
let age = 31
age = 32

console.log(age)
```
### FORMA ANTIGA DE CRIAR UMA VARIÁVEL

Antigamente o "VAR" era usado para criar uma variável no javascript.

### Regras para criar uma variável

1- Se você quiser usar mais de 1 palavra como nome de uma variável, use a convenção "CAMEL CASE" (é uma convenção de nomenclatura na qual cada palavra em uma palavra composta é colocada em maiúscula, exceto a primeira palavra)
2- Nomes de variável não pode começar com número.
3- Não é possível criar variáveis com palavras reservadas da linguagem

### Comentários

```
// para criar um comentário

/*
Para criar um comentário multiLinha
*/
```

**Comment by Roger-Melo** [comment]
Show @lucamacedos . Vamo que vamo, rumo à fluência! 🙌
