### ISSUE TITLE
Resumo da Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by romulofrontend** [roger-melo-treinamentos/curso-de-js-roger-melo#5047]
# Métodos Comuns de Strings

## Métodos
São funções que pertencem a um objeto ou tipo de dado específico

**Dada uma variável declarada com o seguinte valor de string**
`const email = 'romulorosa@front.com'`

## Método .lastIndexOf()
- Para acessar a última ocorrência de um caractere específico
`const lastIndexOfR = email.lastIndexOf('r');`
`console.log(lastIndexOfR);`
**Exibição no Console:** romulorosa

## Método slice()
- Para acessar uma fatia de uma string
- 1º argumento é o nº do índice do caractere de ínício
- 2º argumento é o nº do índice do caractere final

`const emailSliceFirstName = email.slice(0,10);`
`console.log(emailSliceFirstName)`;
**Exibição no Console:** romulorosa

`const emailSliceLastName = email.slice(6,10);`
`console.log(emailSliceLastName);`
**Exibição no Console:** rosa

## Método replace()
-Para substituir um caractere ou trecho específico da string

**Substituindo Um Caractere**
`const replaceLetter = email.replace('a', 'o');`
`console.log(replaceLetter);`
**Exibição no Console:** romuloroso@front.com

**Substituindo Um Trecho**
`const replacePart = email.replace('romulorosa', 'rogermelo');`
`console.log(replacePart);`
**Exibição no Console:** rogermelo@front.com

**Comment by Roger-Melo** [comment]
Show @romulofrontend . Vamo que vamo, rumo à fluência! 🙌
