### ISSUE TITLE
Métodos de string, number e arrays

### ISSUE THREAD

**Issue by igor-chaves** [roger-melo-treinamentos/curso-de-js-roger-melo#5049]
### Etapa da aula

1

### Nome da aula

Strings - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/742275

### Descreva a dúvida

@Roger-Melo

Estou revisando as aulas de strings, numbers e arrays. Comecei a escrever no caderno o que cada método faz mas estou achando meio exaustivo. São TANTOS métodos de cada, será mesmo que eu deveria decorar? Fico pensando se não seria melhor eu apenas procurar como funcionam QUANDO eu precisar. Sinto que estou gastando um tempão desnecessário.

**Comment by MivlaM** [comment]
Olá @igor-chaves!

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

O mais importante nessa etapa inicial do treinamento, é que você siga o método, procure usar o que você aprendeu durante o curso e os conceitos mostrados nas aulas para resolver os exercícios de cada assunto. Não é necessário decorar todos os métodos, porém recomendo você pelo menos se acostumar a usá-los e ter uma ideia de como esses métodos mostrados nas aulas funcionam, assim futuramente você pode acessar os detalhes e particularidades de cada um deles na documentação sem quaisquer dificuldades. Os resumos que você escrever servirão como uma ferramenta de consulta para auxiliar você a lembrar alguns aspectos da linguagem e assim chegar na fluência em Javascript =)

Essa foi apenas uma sugestão, mas você pode fazer da maneira que achar mais confortável.

**Comment by igor-chaves** [comment]
Ok, obrigado!
