### ISSUE TITLE
Resumo da Aula Adicionando e modificando conteúdo em uma página - Aula 02-02 da etapa 05

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5050]
Nessa parte da aula aprendemos como modificar o texto dentro dos elementos que selecionarmos e também como fazemos para modificar o HTML dentro desses elementos.

innterText é uma propriedade utilizada para obter apenas o texto do elemento referenciado:

const paragraph = document.querySelector( ' p  ')

console.log(paragraph.innerText)

---------------------------------------

Como também pode ser utilizado para mudar o texto do elemento referenciado.

const paragraph = document.querySelector( ' p  ')

paragraph.innerText = ' Texto Inserido'  ATRIBUINDO UM NOVO VALOR

paragraph.innerText += ' Texto Inserido'  OU ACRESCENTANDO UM NOVO VALOR

console.log(paragraph.innerText)

------------------------------------------

Também podemos iterar ou modificar vários parágrafos de uma vez com o forEach ( ):

paragrafos.forEach((paragrafo, index) => {
       paragrafo.innerText += ` Novo Texto ${index + 1}`
})

-----------------------------------
-----------------------------------

Também podemos adicionar ou modificar HTML que esse elemento contém, neste exemplo usamos a referencia da modificação de uma DIV que contém um paragrafo dentro dela.

const div = document.querySelector('.content')

div.innerHTML = '< h2 >Novo H2< /h2 >'

Esse novo H2 foi inserido dentro da DIV com o conteúdo content. E mesmo se essa div estivesse vazia, não houvesse um h2 ou um p, esse h2 seria inserido de qualquer forma. Quando usamos o sinal de atribuição e já houver algum HTML dentro da DIV, o HTML que estivermos escrevendo sobre escreve o elemento que esse HTML já havia dentro da DIV.
Da mesma maneira também podemos usar o addition assingment para adicionar um innterHTML

const div = document.querySelector('.content')

div.innerHTML += '< h2 >Novo H2< /h2 >'

Outras maneiras de adicionar templates HTML seria usando um forEach( )

people.forEach((person) =>{
    div.innerHTML += `<p>${person}</p>`

})

Mais a frente iremos ver como as propriedades innertTex e innerHTML vão ser muito uteis no desenvolvimento das aplicações quando precisarmos atualizar o valor de um texto u de algum HTML da pág. Essas duas propriedades também são classificadas como getter e setter. Pesquisar sobre elas no MDN.

**Comment by Roger-Melo** [comment]
Show @Hugones45 . Vamo que vamo, rumo à fluência! 🙌
