### ISSUE TITLE
Resumo da Aula 01-04 (adicionando o java script a uma pagina web)

### ISSUE THREAD

**Issue by Valdemar-Junior** [roger-melo-treinamentos/curso-de-js-roger-melo#5051]
![Captura de tela de 2022-09-22 15-06-35](https://user-images.githubusercontent.com/99037582/191820155-923e0227-e1ac-4059-aa19-e17f7cfc8b31.png)

**Comment by Roger-Melo** [comment]
Show @Valdemar-Junior . Vamo que vamo, rumo à fluência! 🙌
