### ISSUE TITLE
Resumo da Aula 01-02 da etapa 11 - Código assíncrono em JavaScript

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#5054]
### Código assíncrono 
Para compreender o que é um código assíncrono antes é preciso entender o que é código síncrono, por padrão o JS é um código síncrono, isto quer dizer que uma instrução é lida após a outra de cima para baixo.
```js
console.log('instrução 1')
console.log('instrução 2')
console.log('instrução 3')
``` 
Em um código síncrono a tarefa seguinte só será lida quando a anterior tiver sido finalizada, isto quer dizer que se na segunda instrução houvesse uma requisição para algum servidor, e essa requisição levasse alguns segundos para ser concluída o código abaixo da segunda instrução ficaria travado esperando a segunda instrução ser finalizada, isto acontece porque o código síncrono é executado em uma única thread, o código assíncrono resolve essa questão de travamento, porque se a segunda instrução for assíncrona ela será colocada em uma thread separada pelo browser e as instruções seguintes serão lidas normalmente sem que tenham que esperar a instrução anterior ser finalizada, após as instruções serem finalizadas a função de callback da segunda instrução que ficou em uma thread separada é chamada.

**Comment by Roger-Melo** [comment]
Show @Diegodkid . Vamo que vamo, rumo à fluência! 🙌
