### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5055]
### Boleano
**O tipo primitivo boolean no JavaScript
O JavaScript fornece um tipo primitivo boolean que tem dois valores true e false.**

### Includes poder ser utilizado tanto string ou array ele retorna true ou false
Exemplo
```
let name = 'Everton'
console.log(name.includes('E') )
// out true
console.log(name.includes('x')
out false
```

### Operadores de comparação 
```
 == igual
!= maior igual
> maior que
<  menor que
<= menor igual
>= maior igual
```

### OBSERVAÇÃO 
**As ultimas letras do alfabeto e maior que as primeiras letra do alfabeto caractere minúsculo e maior do que maiúsculo**

**Comment by Roger-Melo** [comment]
Show @EvertonMattos . Vamo que vamo, rumo à fluência! 🙌
