### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5062]
Para obter uma listagem das classes que um elemento possui podemos fazer o seguinte console.

const title = document.querySelector( 'h1' )

console.log(title.classList)

A propriedade .classList exibe um DOMTokenList (uma lista similar a um array), que possui todas as classes do elemento.

-------------------------------------------------------

Para adicionar uma classe a um elemento usamos um método chamado add. Usando como base o código acima fazemos:

title.classList.add('error')

Podemos adicionar classes a elementos mesmo que o h1 não tenha sido criado com uma classe CSS, através do JS podemos adicionar uma classe a esse elemento.

----------------------------------------

Para remover uma classe de um elemento podemos usar o método remove:

title.classList.remove('error')

E essas são algumas formas de adicionar ou remover classes em elementos HTML.

--------------------------------------
--------------------------------------

INNERTEXT e TEXTCONTENT
Para obter o texto que um elemento possui podemos além de usar innerText usar o textContent. A diferença entre os dois é que o innerText obtém apenas os textos visíveis que o elemento possui, já a textContent exibe todos os textos que o elemento contem, independente de ser um texto visível ou não.

-----------------------------------

ALTERNANDO CLASSES DOS ELEMENTOS

Se o elemento tiver uma classe iremos remover ela, e se ele não possuir determinada classe iremos adiciona-la com o método toggle( )

const title = document.querySelector('h1')    < = = =    Esse h1 representa um elemento que possui 'title' como class, usando o método toggle abaixo e passando 'title' no argumento do toggle nos removemos o title como class. Caso o title não existisse o toggle iria adiciona-lo como class ao elemento h1.

title.classList.toggle('title')

**Comment by Roger-Melo** [comment]
Show @Hugones45. Vamo que vamo, rumo à fluência! 🙌
