### ISSUE TITLE
Resumo da Aula For loop - Aula 01-03 da etapa 02

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5065]
### For Loop
**O proposito de todo loop é executar a parte do código  repetidas vezes:**
```
for(let i= 0; i<5; i++){
   console.log(o for executou ${i} vezes)
}
out:
o loop executou 0
o loop executou 1
o loop executou 2
o loop executou 3
o loop executou 4
```
### Primeira expressão do for e inicialização do loop:
`let i = 0;
`
### Segunda expressão  ea condição e ela verificar si é true ou false, caso for true ela vai executar a expressão dentro do bloco caso for false ela vai sair do bloco de execução 
```
i<5;
//podemos usar o length 
```
### Terceira expressão tem o valor incrementado ou decrementado 
```
i++
i--
```

**Comment by Roger-Melo** [comment]
Show @EvertonMattos. Vamo que vamo, rumo à fluência! 🙌
