### ISSUE TITLE
Classe hidden para esconder to-do da aplicacao

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#5079]
### Etapa da aula

9

### Nome da aula

Buscando e filtrando to-dos - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1073158

### Descreva a dúvida

Bom dia professor, tudo bem?

Eu quero tirar uma dúvida em relação à classe "hidden", que criamos para esconder o todo na hora de buscá-lo na lista.

Eu percebi que o Bootstrap já tem uma função chamada "d-none" que garante o mesmo efeito. Minha dúvida é se essa classe do Bootstrap é usada para outro fim, ao invés do que estávamos buscando na aplicação.

Obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rafaelpradoj! 

O que a classe `d-none` faz é aplicar um `display: none;` no elemento, então pode usar ela sim =)
