### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5083]
### Template Strings

- Uma das coisas mais legais que uma template strings permite que a gente faça é injetar conteúdo de uma variável em uma string sem precisar concatenar.

**Dica: Em alguns matérias de estudo pode ser que encontre o termo "template literals", mas são a mesma coisa.**

- Exemplo: 

```
const postTittle = 'É bolacha ou biscoito?'
const postAutor = 'Matheus Saad'
const postComment = 15
```

```
// usando concatenação
const postMessage = 'O post "' + postTittle + '", do ' + postAutor + ', tem ' + postComments + ' comentários'
console.log(postMessage)
```

**No javascript você não pode usar a mesma aspa para concatenar e para criar uma string ao mesmo tempo.
Exemplo:**

`const postMessage = 'O post '' + postTittle + '' é legal' // isso vai dar erro
`

- **Alternativas para resolver esse problema:**

1. Se colocar aspas simples em uma string, use aspas duplas nas outras ocasiões.
3. Escapar as aspas que um string contém usando barra invertida '\'. `const postMessage = 'Você manja do filme \'As braquelas\''`
4. Usar template strings

**Template Strings**

```
// Usando template strings
const postMessage = `O post "${postTittle}", do ${postAutor}, tem ${postComment} comentários.`
console.log(postMessage)
```

**Criando templates em HTML**

```
const html = `
    <h2>${postTittle}</h2>
    <p>Autor: ${postAutor}</p>
    <span>Este post tem ${postComment} comentários</span>
`
console.log(html)
```

**Comment by Roger-Melo** [comment]
Show @lucamacedos. Vamo que vamo, rumo à fluência! 🙌
