### ISSUE TITLE
Código executado mais de uma vez

### ISSUE THREAD

**Issue by yrpcfcp** [roger-melo-treinamentos/curso-de-js-roger-melo#5084]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/781540

### Descreva a dúvida

Por que meu console.log foi executado diversas vezes e não apenas uma vez?

```js

let numberAmount = 0
let booleanAmount = 0
let stringsAmount = 0

 for (let i = 0; i < crazyArray.length; i ++){
   if(typeof crazyArray[i] === 'number'){
     numberAmount = numberAmount + 1
   }
  else if ((typeof crazyArray[i] === 'boolean')){
   booleanAmount = booleanAmount + 1
  } else
  {
  stringsAmount = stringsAmount + 1
}

console.log(`O crazyArray tem ${booleanAmount} booleans, ${numberAmount} números e ${stringsAmount} strings.`)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @yrpcfcp! Adiciona o `}` de fechamento do bloco do `for` =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
