### ISSUE TITLE
Dúvida sobre a forma de resolução do exercício 09

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5087]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/742273

### Descreva a dúvida

Oi Roger, fiquei com uma dúvida nesse exercício era para declarar a const mas sem digitar os números e inseri no console.log 
a subtração que imprime o mesmo resultado no console, gostaria de saber se dessa forma também funcionaria ou se é coerente ?

```js
const myAge = 1984
const currentYear = 2022
console.log((currentYear) - (myAge))
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Dieison37!

É normal ter esse tipo de preocupação no início, é um indicativo de que vc quer fazer com excelência =)

Há um princípio que pode te ajudar quando essas preocupações vierem, que é o seguinte: Feito é melhor que perfeito.

Isso por que podem haver vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Com a prática, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, saca? =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
