### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04 da etapa 03

### ISSUE THREAD

**Issue by lucian-bonifacio** [roger-melo-treinamentos/curso-de-js-roger-melo#5088]
**ARGUMENTOS, PAR METROS E DEFAULT PARAMETERS**

Para invocar uma função eu coloco o seu nome seguido de parênteses `myFunc ( )`. Durante a criação da função eu posso definir parâmetros a serem utilizados no momento da sua invocação. Parâmetros, portanto, são as variáveis que são definidas no momento da criação de uma função, podendo ter um valor padrão ou não. Quando já possuírem valores padrões, então se chamam de `DEFAULT PARAMETERS`.

Já os argumentos são utilizados no momento da invocação da função e estes, por sua vez, são as representações dos parâmetros anteriormente criados na função.

Exemplos da Aula:

```javascript
// Argumentos, parâmetros e default parameters
const myFunc = function (name = 'Estrôncio', lastName = 'Almeida') {
    console.log(`Oi, ${name} ${lastName}`)
}

myFunc()
myFunc('Lucian')
myFunc('Lucian', 'Bonifácio')

// output:
// “Oi, Estrôncio Almeida”
// “Oi, Lucian Almeida”
// “Oi, Lucian Bonifácio”
```

**Comment by Roger-Melo** [comment]
Show @lucian-bonifacio . Vamo que vamo, rumo à fluência! 🙌
