### ISSUE TITLE
Resumo da Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by RicardoMell** [roger-melo-treinamentos/curso-de-js-roger-melo#5097]
**STRINGS E MÉTODO:**
Todas às vezes que vejo um nome + ponto + outro nome + parêntese - significa que é um método e vai fazer alguma ação. Também chamado de função que é um pedaço de código com poder de executar ações específicas.

Uma **função** sempre aparece associada a um **método** em particular.

Pode aguardar por alguma ação quando tiver **Método ou Função** que aparecem nas Strings.

Nem sempre os métodos aplicados modificam os valores originais das variáveis.

Os **"métodos"** evocam valores que estão dentro de seus parênteses que são chamados de **"Argumentos"** que NÃO pode ser confundidos com **"Parâmetros"**

**Strings: Quem são, como vivem e o que comem?**
As **"Strings"** são todo o conjunto de caracteres envoltas em aspas duplas ou simples; podem ser concatenadas, possuem propriedades; elas são chiques por possuir métodos conhecidos também como funções.

Esses **"Métodos"** são pedaços de códigos do JS para provocar alguma ação e são visivelmente reconhecíveis por possuírem parênteses.
![CleanShot 2022-09-26 at 17 22 48](https://user-images.githubusercontent.com/24791549/192372804-d7b1bf5f-12ad-44c9-91d2-3e3bea390be5.jpg)

**Comment by Roger-Melo** [comment]
Boa @RicardoMell rumo à fluência! 🔥
