### ISSUE TITLE
Resumo da Aula 01-04 da etapa 11 - O que são requests HTTP

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#5100]
### Requests HTTP
Vão ter momentos em que será necessário buscar informações que estão em outro lugar, em um servidor, um banco de dados ou alguma API, e para obter essas informações será necessário fazer requisições HTTP para se conectar a API ou Banco de dados.

### O que são requisições (request) ?
São solicitações de informações que estão armazenadas em uma API ou Banco de dados, HTTP (Hypertext Transfer Protocol) - protocolo de transferência de hipertexto, que é o principal protocolo de comunicações entre computadores na internet.

### Endpoint
Quando fazemos essas requisições para um servidor ou API nós estamos acessando um Endpoint, Endpoint é uma URL que um servidor ou API disponibiliza para obter informações armazenadas neles, quando fazemos uma requisição para algum Endpoint o formato da resposta que obtemos geralmente é um JSON que é um padrão para troca e armazenamento de informações entre sistemas.

### Json (JavaScript Objetc Notation)
O json é um formato que se parece muito com um objeto javascript. 

### O que são API
Application Programming Interface (interface de programação de aplicações) uma API é criada para que uma aplicação use as funcionalidades de um outro sistema, sendo um ferramenta para que um sistema se comunique com outro sistema.

**Comment by Roger-Melo** [comment]
Boa @Diegodkid rumo à fluência! 🔥
