### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by silasgq** [roger-melo-treinamentos/curso-de-js-roger-melo#5111]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://drive.google.com/drive/folders/1OVrpLkYO7auYag1meMISeK5oiwY0BuRg?usp=sharing

### Maiores dificuldades durante a implementação

- Nomeação de variáveis e funções;
- Refatoração do código.

### Menores dificuldades durante a implementação

- Implementação da lógica da aplicação;

**Comment by MivlaM** [comment]
Olá @silasgq.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Mas antes disso, eu abri a aplicação e identifiquei que o segundo critério para que a análise seja feita está em falta.

O critério é o seguinte:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas anteriores.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações".

Novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação, solicito que por favor, remova as funcionalidades adicionais para que possamos prosseguir com o processo de análise de aplicação.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by MivlaM** [comment]
Não, a que me refiro é apenas a parte de lógica do código que é usada para mostrar todas as respostas corretas para tirar 100% no final. O resto está ok, não se preocupe =)

**Comment by silasgq** [comment]
Entendi @MivlaM, fiz as alterações conforme solicitou, confira se está tudo certo, por gentileza.
Alterei o link no corpo da Issue, mas por via das dúvidas, segue o link: https://drive.google.com/drive/folders/1OVrpLkYO7auYag1meMISeK5oiwY0BuRg?usp=sharing

**Comment by MivlaM** [comment]
Olá @silasgq.

Está tudo ok! Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by silasgq** [comment]
Ok!

**Comment by MivlaM** [comment]
Olá, @silasgq.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Nomeação de variáveis e funções

Vou falar sobre isso mais abaixo.

> ## Refatorar o código

O mais importante vc já fez, que é fazer funcionar =)

Não se preocupe muito com refatoração agora. Refatoração é uma habilidade que é elevada com a prática.

Conforme vc praticar, vc vai percebendo aos poucos o que pode ser melhorado.

E você ainda irá praticar bastante no decorrer do treinamento =)

---

## Boas decisões

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Uma sacada interessante que você fez em relação à usabilidade foi a de posicionar a mensagem dos pontos de forma que ela preenchesse toda a tela após clicar no botão.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Indentação com quatro espaços ao invés de dois

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

- [Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco em excesso 28 e 29.

```js
// antes
const hiddenForm = (form, header, subtitle) => {
  // ...
}



const showResultQuiz = (scoreNumber, scoreSentence, textSentence) => {
  // ...
}
```

```js
// depois
const hiddenForm = (form, header, subtitle) => {
  // ...
}

const showResultQuiz = (scoreNumber, scoreSentence, textSentence) => {
  // ...
}
```

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

A função `hiddenForm` pode ser renomeada de forma com que o nome dado a ela comece com um verbo, `hideForm` pode ser uma sugestão válida.

```js
// antes
const hiddenForm = (form, header, subtitle) => {
  // ...
}
```

```js
// depois
const hideForm = (form, header, subtitle) => {
  // ...
}
```

A função `formSubtmit` pode ter um nome mais descritivo em relação a seu funcionamento. Se o que ela está fazendo ao ser invocada é recomeçar o quiz novamente, pode ser interessante renomeá-la para algo como `restartQuiz`.

```js
// antes
const formSubtmit = () => form.submit()
```

```js
// depois
const restartQuiz = () => form.submit()
```

A palavra `quiz` aparece de forma repetitiva em algumas consts cujo código que elas recebem é indubitavelmente sobre o quiz, se você achar que faz sentido, com o objetivo de encurtar o nome, as consts `quizForm`, `quizHeader` e `quizColorsScore` podem ser renomeadas como apenas `form`, `header` e `scoreColors` respectivamente. A primeira, tanto pelo motivo que já foi citado, quanto porque é o único form da aplicação. A const `quizSubtitle` pode ser renomeada como `title`, esse nome faz mais sentido porque está armazenando justamente o título do quiz.

```js
// antes
const quizForm = document.querySelector('form')
const quizHeader = document.querySelector('.header')
const quizSubtitle = document.querySelector('.quiz-subtitle')

const quizColorsScore = [
  // ...
]
```

```js
// depois
const form = document.querySelector('form')
const header = document.querySelector('.header')
const title = document.querySelector('.quiz-subtitle')

const scoreColors = [
  // ...
]
```

Algo similar acontece aqui, se fizer sentido, você pode remover a palavra "quiz" das consts `quizScoreSentence` e `quizScoreNumber`, você também pode trocar o nome de `quizRestartButton` para algo mais curto e que tenha o mesmo sentido, nessa recomendo que a palavra "Button" seja abreviada e que a palavra "quiz" ainda apareça para que se torne claro para quem está lendo o que está sendo resetado. Essas consts, por exemplo, poderiam ser renomeadas como `scoreMessage`, `scorePercentage` e `btnRestartQuiz` respectivamente. Veja abaixo:

```js
// antes
const quizScoreSentence = document.querySelector('.quiz-score-text')
const quizScoreNumber = document.querySelector('.quiz-result-number')
const quizRestartButton = document.querySelector('.quiz-restart')
```

```js
// depois
const scoreMessage = document.querySelector('.quiz-score-text')
const scorePercentage = document.querySelector('.quiz-result-number')
const btnRestartQuiz = document.querySelector('.quiz-restart')
```

Na função `calculateScore`, o parâmetro pode se chamar `correctAnswer` ao invés de `answer`. Acredito que de forma similar ao nome do array no qual o forEach foi encadeado (`correctAnswer`), a leitura do forEach e do if fique mais legível.

```js
// antes
const calculateScore = (answer, index) => {

  // ...
}
```

```js
// depois
const calculateScore = (correctAnswer, index) => {

  // ...
}
```

No intuito de melhorar a legibilidade do código, você também pode renomear a função `handleSubmitForm` para algo como `showScore`. Dessa forma, ao bater o olho no nome da função, a ação que ela executa fica explícita. A let `counterRightAnswers` também pode ser renomeada como `counterCorrectAnswers`, visto que o termo "correct" já é utilizado em outras partes da aplicação, tornando-o mais habituado para quem está lendo o código.

```js
// antes
let counterRightAnswers = 0

const handleSubmitForm = event => {
  // ...
}
```

```js
// depois
let counterCorrectAnswers = 0

const showScore = event => {
  // ...
}
```

Você também pode, se achar que faz sentido, renomear a função `setColorScore` para `setScoreColor`, dessa forma o nome seria mais similar a norma ortográfica da língua inglesa, o que pode facilitar o entendimento para quem está lendo o código sobre como a função funciona. Dentro dessa função, há uma detalhe na lógica que vale a pena ser notado: `allWrongAnswers` e `allAnswersAreCorrect` estão armazenando um boolean para a verificação de uma única resposta para item do forEach, e não todas as respostas, portanto, pode fazer mais sentido que essas consts sejam renomeadas para `answerIsWrong` e `answerIsCorrect` respectivamente, ficaria assim:

```js
// antes
const setColorScore = ({ id, className, color }) => {
  const allWrongAnswers = counterCorrectAnswers === 0
  const allRigthAnswers = counterCorrectAnswers === 4
  // ...
}
```

```js
// depois
const setScoreColor = ({ id, className, color }) => {
  const answerIsWrong = counterCorrectAnswers === 0
  const answerIsCorrect = counterCorrectAnswers === 4
  // ...
}
```

---

## Refatoração de funções

Há uma forma de fazer uma refatoração de como a pontuação é obtida, mas para entender de fato essa forma de refatorar o código que vou mostrar, sugiro que você preste bastante atenção nesse passo a passo abaixo junto comigo, ok?

Vamos lá!

De início, vamos eliminar essa função `setScoreColor` e mover todo o código dentro dela para a função `showScore`. 

```js
const showScore = event => {
  // ...

  const answerIsWrong = counterCorrectAnswers === 0
  const answerIsCorrect = counterCorrectAnswers === 4
  const isIdColor = counterCorrectAnswers === id

  const allWrongAnswersSentence = 'Ops! Você errou todas as perguntas.'
  const allRigthAnswersSentence = 'Parabéns! Você acertou todas as perguntas.'
  const patternAnswersSentence = `Você acertou ${counterCorrectAnswers} de 4 perguntas.`

  if (isIdColor) {
    scorePercentage.classList.add('class', className)
    headerResult.style.background = color
  }

  if (answerIsWrong) {
    showResultQuiz(scorePercentage, quizScoreSentence, answerIsWrong)
    return
  }

  if (answerIsCorrect) {
    showResultQuiz(scorePercentage, quizScoreSentence, answerIsCorrect)
    return
  }

  showResultQuiz(scorePercentage, quizScoreSentence, patternAnswersSentence)
  // ...

  scoreColors.forEach(setScoreColor)
  // ...
}
```

Aqui, há alguns detalhes que valem a pena ser mencionados. Nessa parte do código logo abaixo, há algumas coisas que não são tão necessárias para executar o que o seu código está fazendo, por exemplo, para cada item do array `scoreColors`, o forEach está fazendo com que aconteça uma manipulação do DOM e a cada manipulação está sendo setada no DOM as cores, a mensagem e a pontuação.

```js
const scoreColors = [
  { id: 0, className: 'none-question', color: '#5c5c5c' }, // Itens do array scoreColors.
  { id: 1, className: 'one-question', color: '#FF0000' },
  { id: 2, className: 'two-question', color: '#97b828' },
  { id: 3, className: 'three-question', color: '#48B700' },
  { id: 4, className: 'all-question', color: '#00FF00' }
]
  
scoreColors.forEach(setScoreColor) // forEach manipulando o DOM para setar as cores, mensagem e pontuação
```

Segundo o funcionamento do código acima, se a pessoa acertou 75%, na primeira vez que esse callback do forEach for executado, uma manipulação de DOM vai acontecer que colocará cor, pontuação e mensagem específicas para essa pontuação no DOM, na segunda execução do callback, se a pessoa acertou 50%, por exemplo, uma nova manipulação de DOM acontecerá de novo para colocar outra cor, outra porcentagem e outra pontuação. Na terceira execução do callback, uma nova substituição de algo que já existe no dom acontecerá de novo... então você percebe que não é preciso manipular o DOM toda vez que esse callback `setScoreColor` for executado?

Certo, como próximo passo, vamos descrever os casos para cada pontuação. Após isso, poderemos remover a const `scoreColors` e também sua manipulação pelo forEach `scoreColors.forEach(setScoreColor)`.

Como que seria um código com if repetindo tudo que foi abstraído pelo código acima aqui? Seria mais ou menos o seguinte:

```js
const showScore = event => {
  // ...

  if (counterCorrectAnswers === 0) { // Caso nenhuma resposta certa seja selecionada
    scorePercentage.classList.add('class', 'none-question')
    headerResult.style.background = '#5c5c5c'
    scorePercentage.textContent = `${score}%`
    scoreMessage.textContent = 'Ops! Você errou todas as perguntas.'
    return
  }

  if (counterCorrectAnswers === 1) { // Caso apenas uma resposta certa seja selecionada
    scorePercentage.classList.add('class', 'one-question')
    headerResult.style.background = '#FF0000'
    scorePercentage.textContent = `${score}%`
    scoreMessage.textContent = `Você acertou ${counterRightAnswers} de 4 perguntas.`
    return
  }

  if (counterCorrectAnswers === 2) { // Caso duas respostas certas sejam selecionadas
    scorePercentage.classList.add('class', 'two-question')
    headerResult.style.background = '#97b828'
    scorePercentage.textContent = `${score}%`
    scoreMessage.textContent = `Você acertou ${counterRightAnswers} de 4 perguntas.`
    return
  }

  if (counterCorrectAnswers === 3) { // Caso três respostas certas sejam selecionadas
    scorePercentage.classList.add('class', 'three-question')
    headerResult.style.background = '#48B700'
    scorePercentage.textContent = `${score}%`
    scoreMessage.textContent = `Você acertou ${counterRightAnswers} de 4 perguntas.`
    return
  }

  if (counterCorrectAnswers === 4) { // Caso todas as respostas certas sejam selecionadas
    scorePercentage.classList.add('class', 'all-question')
    headerResult.style.background = '#00FF00'
    scorePercentage.textContent = `${score}%`
    scoreMessage.textContent = 'Parabéns! Você acertou todas as perguntas.'
    return
  }

  // ...
}

``` 

Agora, você percebe um padrão se repetindo para cada if e que apenas alguns dados específicos estão mudando? Sabendo disso, podemos criar uma função para fazer o papel de todos esses ifs, vamos criar uma função para retornar um objeto que vai conter todas as informações para cada um dos casos retratados no if. Se cada dado dentro do if está relacionado a mensagem de pontuação, podemos criar uma função chamada `getScoreMessage` que irá receber a pontuação que o usuário fez por meio de um parâmetro score que fará o mesmo papel de definir a mensagem, cor e classe que o usuário receberá e que retornará esse objeto personalizado para cada caso. Visto que a mensagem se repete caso a pontuação esteja entre 25 e 75, podemos armazená-la exclusivamente numa const `message` dentro dessa função. Uma situação especial é o de caso `score` receba 100, não precisa inserir essa opção no objeto, podemos fazer com que essas informações sejam retornadas por meio de um || caso todas as outras situações sejam invalidas.   Ficaria assim:

```js
const getScoreMessage = score => {
  const message = `Você acertou ${score/25} de 4 perguntas.`

  return {
    0: { className: 'none-question', color: '#5c5c5c', message: 'Ops! Você errou todas as perguntas.' },
    25: { className: 'one-question', color: '#FF0000', message },
    50: { className: 'two-question', color: '#97b828', message },
    75: { className: 'three-question', color: '#48B700', message }
  }[score] || { className: 'all-question', color: '#00FF00', message: 'Parabéns! Você acertou todas as perguntas.' }
}
```

Agora, podemos fazer um destructuring na invocação dessa função `getScoreMessage`. Sabendo que a função vai receber a pontuação do usuário armazenada em `score` e que sua invocação sempre vai retornar um objeto pois o valor de uma das propriedades dentro dela sempre será um objeto, podemos fazer um destructuring em `className`, `color` e `message`. Feito isso, todos os blocos de if mostrados anteriormente podem ser excluídos junto com a let `counterRightAnswers`. Apenas o trecho de código necessário para essa funcionalidade dentro de `showScore` será o de inserção das propriedades da função no DOM, assim conseguimos fazer com que o código faça a mesma coisa que o anterior antes de começar a refatoração e eliminamos muitas linhas desnecessárias.Ficaria assim:

```js
const showScore = event => {
  event.preventDefault()

  // ...
  const { className, color, message } = getScoreMessage(score)

  scorePercentage.classList.add('class', className)
  headerResult.style.background = color
  scorePercentage.textContent = `${score}%`
  scoreMessage.textContent = message
  quizContainer.style.display = 'flex'
  // ...
}
```

Feito esses ajustes, vou te mostrar duas abordagens de refactoring usando métodos que você vai encontrar em breve nas aulas seguintes, ambos serão explicados com detalhes futuramente. O que quero que você entenda, nesse primeiro momento, é o conceito por trás deles. Sabendo disso, observe o código abaixo:

```js
const calculateScore = (correctAnswers, index) => {
  const isAnswerCorrect = correctAnswers === userAnswers[index]

  if (isAnswerCorrect) {
    score += 25
    counterRightAnswers += 1
  }
}
correctAnswers.forEach(calculateScore)
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, vamos declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Por esse momento, vamos manter uma lógica similar a que você usou dentro dessa nova função:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
    score += 25
    }
  })
}
```

Depois, a let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 25 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
      return accumulator + 25
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 25, que na primeira execução será (0 + 25). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 25, na segunda execução o parâmetro `accumulator` estará armazenando 25 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 25 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator, 0)
```

Por fim, você pode invocar a função `getScore()` dentro da função `showScore` recebendo o array armazenado por `userAnswers` como argumento.

```js
const showScore = event => {
  // ...
  const score = getScore(userAnswers)
  const { className, color, message } = getScoreMessage(score)
 // ...
}
```

Legibilidade em funcionalidades que a gente ainda não conhece na linguagem pode ser algo um pouco complicado no começo, porém quanto mais você praticar, mais você vai se acostumar com esse tipo de código declarativo. Percebe-se que a função foi resumida em apenas duas linhas =)

## Refatoração getUserAnswers

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter as respostas do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. userAnswers vai receber um array vazio que será preenchido após percorrermos cada item dentro do array correctAnswers por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, você pode invocar a função dentro da função `showScore` que o código funcionará normalmente =)

Se você achar que faz sentido, você também pode fazer algumas refatorações na função `hideForm` para deixá-la com menos código e mais concisa. Por exemplo, essa função não precisa receber argumentos e parâmetros, pois as variáveis que ela está usando são variaveis globais. Além disso, você pode criar um array com os três elementos `form`, `header` e `title` e armazená-los numa const `elements`. Depois, percorrer cada um dos elementos dessa const `elements` por meio de um forEach que servirá para executar `element.classList.add('d-none')` para cada um dos elementos do array. Vale ressaltar que, o que essa classe d-none faz é aplicar um display: none; no elemento. Essa classe é uma classe específica do bootstrap, então podemos usá-la tranquilamente para deixar o código mais curto e com o mesmo efeito =) 

```js
// antes
const hideForm = (form, header, subtitle) => {
  form.style.display = 'none'
  header.style.display = 'none'
  subtitle.style.display = 'none'
}
```

```js
// depois
const hideForm = () => {
  const elements = [form, header, title]
  elements.forEach(element => element.classList.add('d-none'))
}
```

Na barra de URL do navegador, há um detalhe sutil na composição da URL da aplicação quando o form é enviado. Cada vez que o form é enviado, a URL muda de acordo com as alternativas marcadas no quiz. Você pode, se achar interessante, evitar esse comportamento da URL, deixando-a apenas de uma forma padrão. Para fazer isso, se a intenção é apenas recarregar a página quando o botão é clicado, ao invés de usar o método `submit()`, você pode optar pelo método [location.reload()](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload).  

```js
// antes
const restartQuiz = () => form.submit()
```

```js
// depois
const restartQuiz = () => location.reload()
```

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by silasgq** [comment]
Obrigado @MivlaM, faz sentindo sim, fiz as alterações conforme sugeriu na análise.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
