### ISSUE TITLE
Resumo da Aula Eventos de clique - Aula 03-03 da etapa 05

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5116]
Na maior parte das vezes as manipulações e modificações que fazemos são reações a ações do usuário na pagina, por exemplo se o usuário clicar em um botão podemos exibir um menu ou um pop-up, se o usuário clicar em um ícone de lixeira, o usuário pode deletar alguma coisa. Esses são os eventos e começaremos a falar sobre os eventos de clique para posteriormente cobrir outros tipos de eventos .

Existem 3 passos para construir a interação de um clique:

1-  Precisamos fazer uma query no DOM para obter a referencia do elemento no qual agente quer que  evento aconteça, no caso o botão.
2 - Adicionar nesse elemento um eventListening, tradução seria "escutador de evento", ele escuta um evento em um elemento especifico.
3 - Implementar uma função de callback que vai ser executada quando esse evento acontecer, ou seja quando o clique no botão acontecer.

EX:
const button = document.querySelector('button')

button.addEventListener('click', ()=> {
            console.log('Clicou no Botão')
})

O método addEventListener tem dois argumentos, no primeiro argumento especificamos uma string com o nome do tipo de evento que queremos escutar, neste caso o clique, mas existem vários outros eventos também. O segundo argumento é uma função de callback que só será executada quando o evento no elemento especificado acontecer.

--------------------------------------------

Agora se quiséssemos adicionar eventListener em cada uma das tags li, para que ao clicar em uma das li, ela seja removida da ul e consequentemente da tela. Para fazer isso executaremos os mesmos três passos de antes.

const lis = document.querySelectorAll('li')

lis.forEach((li) => {
        li.addEventListener('click', event => {
            console.log(event.target)
        })
})

Mas para saber qual elemento será removido ou modificado precisamos saber de sua localização. No browser quando um evento acontece dentro da função de callback o browser disponibiliza um objeto no parâmetro da função, e esse objeto será chamado de event, esse objeto possui informações sobre o evento que aconteceu.
Para obtermos em qual elemento o evento aconteceu, usamos a propriedade target, pois a target armazena a referencia do elemento em que o evento ocorreu.
Outra forma de obter o elemento que foi clicado é usar o parametro li da função de callback do forEach

lis.forEach((li) => {
        li.addEventListener('click', event => {
           console.log(li)
        })
})

Se clicarmos nas lis, veremos a referencia da li que foi clicada. Porém na maioria das vezes daremos preferencia do event.target, pois ele ira nos ajudar com o event.delegation que será visto mais a frente.
 Agora então que sabemos qual elemento foi clicado podemos remover esse elemento da pág, mas por agora apenas modificaremos o estilo da li que foi clicada, para que ela fique com um traço em seu meio como se estivesse riscada.

const lis = document.querySelectorAll('li')

lis.forEach((li) => {
        li.addEventListener('click', event => {
            const clickedElemet = event.target
            clickedElemet.style.textDecoration = 'line-through'
        })
})

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
