### ISSUE TITLE
Switch e seu escopo

### ISSUE THREAD

**Issue by fernandomk6** [roger-melo-treinamentos/curso-de-js-roger-melo#5117]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/813573

### Descreva a dúvida

Essa foi minha resolução da questão 14 do exercício 9

```js
const getLikesInfo = peoplesWhoLiked => {
  const peopleAmount = peoplesWhoLiked.length

  switch (peopleAmount) {
    case 0: 
      return 'Ninguém curtiu isso.'
    case 1:
      return `${peoplesWhoLiked[0]} curtiu isso.`
    case 2:
      return `${peoplesWhoLiked[0]} e ${peoplesWhoLiked[1]} curtiam isso.`
    case 3:
      return `${peoplesWhoLiked[0]}, ${peoplesWhoLiked[1]} e ${peoplesWhoLiked[2]} curtiam isso.`
    default:
      return `${peoplesWhoLiked[0]}, ${peoplesWhoLiked[1]} e mais ${peopleAmount - 2} pessoas curtiam isso.`
  }
}

// console.log(getLikesInfo(['fernando', 'jessica', 'rodrigo', 'jonathan', 'muriel']))
```
Em muitos locais eu estou usando a `peoplesWhoLiked[0]`, eu gostaria de atribuir ela a uma
variável, para cada um dos casos, como no exemplo a baixo:

```js
switch (peopleAmount) {
  case 0: 
    return 'Ninguém curtiu isso.'
  case 1:
    const firstPeople = peoplesWhoLiked[0]
    
    return `${firstPeople} curtiu isso.`
  case 2:
    const firstPeople = peoplesWhoLiked[0]
    const secondPeople = peoplesWhoLiked[1]

    return `${peoplesWhoLiked[0]} e ${secondPeople} curtiam isso.`
  case 3:
    const firstPeople = peoplesWhoLiked[0]
    const secondPeople = peoplesWhoLiked[1]
    const thirdPeople = peoplesWhoLiked[2]

    return `${firstPeople}, ${secondPeople} e ${thirdPeople} curtiam isso.`
  default:
    const firstPeople = peoplesWhoLiked[0]
    const secondPeople = peoplesWhoLiked[1]

    return `${firstPeople}, ${secondPeople} e mais ${peopleAmount - 2} pessoas curtiam isso.`
}
```

Porém um erro ocorre dizendo que a constante X já foi declarada. Pelo que parece eu não
posso declarar variável com mesmo nome, mesmo em cases diferentes. É isso mesmo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @fernandomk6!

Isso mesmo, `case` e `default` não possuem escopo. Isso quer dizer que o único escopo no switch que vc declarou é o que está dentro do bloco de abertura e fechamento do switch (`switch (peopleAmount) { ... }`).

Isto é, qualquer variável dentro desse escopo que tenha o mesmo nome, irá colidir.

Vc pode ver um caso idêntico neste exemplo da doc:

- [Switch Lexical scoping - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#lexical_scoping)

Porém, vc pode adicionar blocos em `case` e/ou `default` em seu switch. Ficaria mais ou menos assim:

```javascript
const aValue = 7

switch (aValue) {
  case 8: {
    console.log('"aValue" é 8')
  }

  default: {
    console.log('"aValue" não é 8') // "aValue" não é 8
  }
}

```

Dentro desses blocos, vc pode adicionar suas variáveis e elas não irão colidir:

```javascript
const aValue = 7

switch (aValue) {
  case 8: {
    const x = 'case 8'
    console.log(x)
  }

  default: {
    const x = 'default'
    console.log(x) // default
  }
}
```

Mas talvez faça sentido não se preocupar muito em entender à fundo o switch nese momento. Primeiro pq, como você viu, vc sempre pode consultar a doc para tirar esse tipo de dúvida mais específica.

E segundo pq conforme vc avançar no treinamento, vc verá maneiras mais elegantes e interessantes de checar valores do que o `switch` =)

Respondi a dúvida?

**Comment by fernandomk6** [comment]
Respondeu sim roger valeu, muito legal isso do bloco no switch não conhecia. Valeu.

**Comment by Roger-Melo** [comment]
Boa! No que precisar, é só abrir uma nova issue =)
