### ISSUE TITLE
Correção dos exercícios da aula 02 - Aula 03-01 (exercício 21)

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5118]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/745800

### Descreva a dúvida

Gostaria de saber o motivo da constante **name** estar riscada ao meio. Pesquisei e diz que foi indeferida, mas não entendi.

![21](https://user-images.githubusercontent.com/71138743/192641590-083e35ab-2d4c-48cc-95d0-47e85ce7ea1b.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Dê uma olhada [nessa resposta](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/385) e se ainda restar alguma dúvida, pode perguntar aqui =)

**Comment by Ale557333** [comment]
Obrigado Roger! Entendi sim!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
