### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5120]
O método lastIndexOf busca o index da última ocorrência do caractere passado como argumento.
O método slice ele vai fatiar, pegar um pedaço de uma string.
O método replace vai substituir um caractere de uma string por outro.

**Comment by Roger-Melo** [comment]
Boa @Dieison37 rumo à fluência! 🔥
