### ISSUE TITLE
Resumo da aula Data e hora em JavaScript da etapa 10

### ISSUE THREAD

**Issue by rafaelpradoj** [roger-melo-treinamentos/curso-de-js-roger-melo#5121]
DATA E HORA EM JAVASCRIPT

Como funciona o objeto Date()?
R: É um objeto que representa o tempo, conseguimos identificar calendarios e horarios, entre coisas relacionadas a datas. A data pode ser representada desde 1 de janeiro de 1970.

Observação?
R: A representação de alguns valores são em zero base, ou seja, mês 0 é igual a janeiro, por exemplo.

Como declarar um objeto Date()?
R: const varName = new Date()

Métodos famosos para o objeto Date()?
  - Date.prototype.getFullYear()
  - Date.prototype.getMonth()
  - Date.prototype.getDate()
  - Date.prototype.getDay()
  - Date.prototype.getHours()
  - Date.prototype.getMinutes()
  - Date.prototype.getSeconds()
  - Date.prototype.getTime()
  - Date.prototype.toDateString()
  - Date.prototype.toTimeString()
  - Date.prototype.toLocaleString

Link no MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

```js

// EXEMPLOS DE USO

const present = new Date()

console.log('Ano:', present.getFullYear()) // ano (4 digitos)

console.log('Mês:', present.getMonth()) // numeroMes (zero base)

console.log('Data:', present.getDate()) // DiaMes

console.log('Dia:', present.getDay()) // numeroSemana (zero base)

console.log('Hora:', present.getHours()) // Hora

console.log('Minutos:', present.getMinutes()) // Minutos

console.log('Segundos:', present.getSeconds()) // Segundos

console.log('Timestamp:', present.getTime()) // Tempo que se passou desde 1970

console.log('toDateString:', present.toDateString()) // diaSemana, mes, diaMes, ano em tipo de string

console.log('toTimeString', present.toTimeString()) // Horario e fuso horário em tipo string

console.log('toLocaleString', present.toLocaleString()) // dia, mes, ano, hora, minutos e segundos em tipo string (padrao americano)
```

**Comment by Roger-Melo** [comment]
Boa @rafaelpradoj rumo à fluência! 🔥
