### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5122]
### **Null e undefined**

**Null e undefined são similares e ambos apresentam a falta de uma valor.**

### NULL 

- **A principal diferença é que o NULL diferente do undefined deve ser intencionalmente definido.**
- Exemplo: 

`let emptiness = null
`
Com isso a variável "emptiness" não tem um valor definido
- Quando você envolve alguma operação matemática envolvendo o NULL ele é interpretado como 0. Exemplo:

```
let emptiness = null
console.log(emptiness + 3)
```

**Resultado no console = 3**

- O NULL também pode ser convertido para uma string. Exemplo: 

```
let emptiness = null
console.log(`issos é uma ${emptiness}`)
```

**RESUMINDO: VOCÊ ADICIONA O NULL QUANDO QUER QUE SUA VARIÁVEL INTECIONAMENTE NÃO TENHA VALOR.**

### UNDEFINED

**Todas as vezes que não é atribuído um valor para uma variável o javascript automaticamente atribui undefined para essa variável.**
Exemplo: 

```
let emptiness
console.log(emptiness, emptiness + 3, `issos é uma ${emptiness}`)
```
- **Quando undefined toda operação matemática resultará em "NaN"**
- **Assim como NULL o undefined também pode ser convertido para uma string.**

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
