### ISSUE TITLE
Resumo da Aula O evento submit - Aula 01-03 da etapa 06

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5137]
- Evento submit  | form.addEventListener('submit', ( ) => { })  |
E utilizado para capturar as informacoes de um formulario; Quando o botao de envio e acionado a pagina por padrao e recarregada e para evitar esse comportamento utiliza-se o comando | event.preventDefault( ) |.

E para obter o valor inserido no input existem algumas formas:
- console.log(usernameInput.value) - caso o valor seja armazenado em uma const (usernameInput)
- console.log(form.username.value) - referenciando form e o id ou name (nao precisa armazenar o valor em const)
- console.log(event.target.username.value) referenciando o id ou name atraves do event.target (nao precisa armazenar o valor em const).

**Comment by Roger-Melo** [comment]
Boa @YukOnRails rumo à fluência! 🔥
