### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5141]
Number
Inteiros e decimais são números em sequências normais e para representar os números decimais usa-se ponto. O símbolo de % (módulo) esse operador calcula o resto de uma divisão entre dois operandos. Na ordem das operações a sequência correta de procedência que são os 1º-parênteses, 2º-expoentes ou raízes, 3º-multiplicação e divisão e 4º-adição e subtração. Operadores de incremento são a soma de uma variável + um outro valor e decremento e a subtração de um valor por outro. Nos operadores assignment, usa-se os shorthands que são mais práticos, ex: += addition, -= subtraction, *= multiplication e /= division. NaN – not a number se refere a uma operação que não resulta em um número. Em concatenação de string com número funciona da seguinte forma no JS que converte automaticamente esse número em string e o resultado entre número e string, sempre será uma string.

**Comment by Roger-Melo** [comment]
Boa @Dieison37 rumo à fluência! 🔥
