### ISSUE TITLE
Resumo da Aula 02-03 da etapa 11 - Fazendo requests HTTP

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#5148]
A primeira coisa a se fazer em uma requisição HTTP é criar um objeto de request
```js
const request = new XMLHttpRequest()
```
Através deste objeto temos acesso a vários métodos e propriedades, agora precisamos abrir essa requisição
```js
request.open()
```
O método open, disponível no objeto que acabamos de criar precisa de dois argumentos:
```js
request.open('GET', 'https://jsonplaceholder.typicode.com/todos')
```
O primeiro argumento é o método de requisição HTTP que será utilizado, o segundo argumento é o endpoint para onde será enviado o request para obter os dados
```js
request.send()
```
Depois de configurar o request precisamos enviar a solicitação para o servidor, e fazemos isso através do método send(), podendo passar como argumento null, como estamos utilizando o GET não é preciso passar um argumento.

Depois disso, para começar acessar os dados da resposta é possível traquear o processo da requisição através de um eventListener,
para obtermos informações sobre a mudança de estado da requisição
```js
request.addEventListener('readystatechange', () => {
 console.log(request.readyState)
})
```
Esta propriedade irá retornar o estado da nossa requisição: 
```js
 console.log(request.readyState) // 1, 2, 3, 4
```
E o que são estes estados 1, 2, 3 e 4? Abaixo segue uma lista com o significado de cada estado.
<html>
<body>
<h1 style="box-sizing: border-box; margin: 0px 0px 2rem; letter-spacing: var(--heading-letter-spacing); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-weight: ; font-stretch: ; font-size: ; line-height: ; font-family: Inter, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; word-break: break-word; color: rgb(255, 255, 255); orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(27, 27, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">XMLHttpRequest.readyState</h1><div class="section-content" style="box-sizing: border-box; color: rgb(255, 255, 255); font-family: Inter, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(27, 27, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 1rem 0px 2rem; font: var(--type-article-p);">The<span> </span><strong style="box-sizing: border-box; font-weight: var(--font-body-strong-weight); letter-spacing: 0.02rem;">XMLHttpRequest.readyState</strong><span> </span>property returns the state an XMLHttpRequest client is in. An XHR client exists in one of the following states:</p><div class="table-scroll" style="box-sizing: border-box; margin: 0px; overflow: auto; width: 765.719px;">

Value | State | Description
-- | -- | --
0 | UNSENT | Client has been created. open() not called yet.
1 | OPENED | open() has been called.
2 | HEADERS_RECEIVED | send() has been called, and headers and status are available.
3 | LOADING | Downloading; responseText holds partial data.
4 | DONE | The operation is complete.

</div></div>
</body>
</html>

Agora podemos checar se o estado da nossa requisição é igual a 4, porque quando o estado for igual a 4 é que podemos fazer algo com as informações
```js
request.addEventListener('readystatechange', () => {
    if (request.readyState === 4) {
        console.log(request.responseText);
    }
})
```

**Comment by Roger-Melo** [comment]
Boa @Diegodkid rumo à fluência! 🔥
