### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by Thesamuel01** [roger-melo-treinamentos/curso-de-js-roger-melo#516]
Olá Roger, segue o link para minha aplicação do Quiz Interativo.
- [Quiz Interativo](https://github.com/Thesamuel01/Interactive-Quiz)

**Maiores Dificuldades:**
- Tive dificuldades na hora da refatoração do código, pois normalmente tenho a tendêcia a já ir pensando na refatoração enquanto ainda estou desenvolvendo o código.
- Definir nome de algumas funções e algumas variáveis.

**Menores Dificuldades:**
- Manipulação dos elementos do DOM.
- Utilizar o forEach.
- Lógica de Programação, realizei a revisão todos os dias antes de iniciar um novo conteúdo, e isso me auxiliou em poder relembrar todos os conceitos aprendidos enquanto estava fazendo a aplicação.

A aplicação tem alguns aditivos, mas tudo utilizando os conceitos aprendidos em aula sem nada fora do escopo ou de pego de fontes externas.

O curso está atendendo muito bem as minhas expectativas e estou gostando da forma que é ministrada.
Consigo visualizar o meu progresso a cada bateria de exercícios.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Samuel.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

@Thesamuel01

**Comment by Roger-Melo** [comment]
Olá Samuel.

Parabéns pelo esforço em implementar a aplicação =)

Em relação ao que foi adicionado na aplicação, no e-mail que enviei explicando os critérios para que a aplicação fosse analisada, o critério 2 especifica que a aplicação deve conter nenhuma funcionalidade a mais do que as que foram mostradas nas aulas anteriores. 

Então na análise eu vou me focar nas features e princípios que eram essenciais que a aplicação tivesse e as features adicionais (cor de background nas respostas erradas, recarregar página, etc) vão ficar por sua conta. A medida em que você for avançando no treinamento, terá várias ideias de como melhorar o código das features à mais que implementou.

---

### Nomes de variáveis e funções

Prefira nomear variáveis que armazenam booleans começando com `is`, `has` ou `should`. Isso é uma convenção que padroniza e facilita identificar esse tipo de variável mais rápido no código.

Então `verifyCheckedWrongAnswer`, por exemplo, ficaria como `isWrongAnswer`.

`button` pode descrever melhor o valor que ela armazena. Eu a renomearia como `buttonForm`, para ser mais específico.

### Padronização da escrita do código

Não há problemas em envolver um parâmetro único de uma arrow function em parênteses. Porém, é necessário ser consistente com essa decisão ao longo do código. Então evite a inconsistência abaixo.

```javascript
const highlightWrongUserAnswer = input => {}
const showPopup = (scoreFeedback) => {}
```

### Refatoração

Como eu disse, ao longo do treinamento você terá insights para melhorar o código das features adicionais. Inclusive reduzindo a quantidade de `forEach`.

---

As observações acima fizeram sentido, @Thesamuel01?

**Comment by Thesamuel01** [comment]
Olá Roger.

Realmente havia esquecido sobre o fato da aplicação que quando for submetida a análise, não deve haver features que não foram apresentadas nas aulas, irei me atentar nas próximas para entregar conforme o acordado.

Referente aos comentários realizados:

Fizeram sentido sim, ainda mais a questão das variáveis que armazenam um valor boolean e como elas ficam mais claras quando iniciam com `is`, `has` ou `should`. Irei realizar as devidas correções e adicionar as novas funcionalidades que foram ministradas nas aulas seguintes. 

Muito obrigado pelo feedback!

E rumo a fluência!

@Roger-Melo
