### ISSUE TITLE
Dúvida no exercício 11

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5160]
### Etapa da aula

1

### Nome da aula

Exercícios da Aula 02 - Como baixá-los

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/742279

### Descreva a dúvida

Roger fiquei com uma dúvida no exercício 11 da aula-02, pede para exibir o caractere "v" da string  "winterMessage", nesse caso para que o exercício está pedindo vai dar um erro no console ? ou no caso o "v" vai representar o "w" ?.

```js 
const message = 'winterMesssage'
console.log(message[0])
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Dieison37! 

Como você pode ver [neste link](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-02/app.js#L92), na linha 92, `winterMessage` é uma `const` que armazena uma string. O exercício pede que você exiba no console o `index` do caractere "v" da "winterMessage". Isto é, o index do caractere "v" da string que a const winterMessage armazena.

Sacou a ideia? =)

**Comment by Dieison37** [comment]
Boa tarde Roger!

Saquei, foi falta de atenção mesmo, obrigado.






Att.
DIEISON L. VIEIRA.


Em dom., 2 de out. de 2022 às 22:19, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
