### ISSUE TITLE
Resumo da Aula O que é controle de fluxo - Aula 01-02

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5161]
### O que é controle de fluxo
- Vai existir momentos na criação de projetos que vão necessitar da execução de um pedaço de código **múltiplas vezes**, ou decidir qual vai ser a próxima ação a ser executada. Então vamos precisar de alguma forma `controlar o fluxo ` do nosso código.

**Exemplo:**

- Imagine que temos um array e precisaríamos executar cada item desse array, nesse caso usaríamos o `LOOP`, que é um tipo de controle de fluxo.

- Da mesma forma haverá casos em que precisaríamos verificar se uma condição é verdadeira, e só se essa condição for verdadeira o código seria executado. Nessa caso usaríamos o `IF`.

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
