### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#5209]
### Strings 
- Pode-se utilizar aspas simples ou aspas duplas para definir uma String
  - Exemplo: 
```js
const firstName = 'Geison'
const lastName = "Oliveira"
```

- Concatenação de strings
  - Exemplo: 
```js
const firstName = 'Geison'
const lastName = 'Oliveira'
const fullName = firstName + ' ' + lastName

console.log(fullName) // Geison Oliveira
```

- Acessando caracteres
  - String é um vetor de caracteres
  - JS é uma linguagem _zero based_, ou seja, a contagem começa no zero
    -  Exemplo:
```js
const fullName = 'Geison Oliveira'
const firstLetter = fullName[0] // Acessando o primeiro caractere da String
console.log(firstLetter ) // G
```

- Comprimento de uma String
  - Para se obter o comprimento da uma String podemos usar a propriedade _length_
  - Exemplo:
```js
const fullName = 'Geison Oliveira'
console.log(fullName.length) // 15
```

- Métodos de String
  - Os métodos de String não modificam a String original
  - Exemplo:
```js
const fullName = 'Geison Oliveira'
console.log(fullName.toUpperCase()) // GEISON OLIVEIRA
console.log(fullName.toLocaleLowerCase()) // geison oliveira
console.log(fullName.indexOf('G')) // 0
 ```

**Comment by Roger-Melo** [comment]
Boa @Geisonszo rumo à fluência! 🔥
