### ISSUE TITLE
Resumo da Aula O evento submit - Aula 01-03 da etapa 06

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5212]
Quando queremos escutar o envio de um formulário, ao invés de atrelar o listener de evento no botão, atrelamos esse listener de evento no form, pois no final das contas é o form que está sendo enviado, pois o que importa é o SUBMIT o envio desse form.

Os próximos passo são:
Obter a referencia do form e depois adicionar um eventListener nele.

const form = document.querySelector('.singup-form')

form.addEventListener('submit', event=> {
    
})

Neste eventlistener usamos o event no parâmetro da função, pois o comportamento padrão do evento submit é o de carregar a pág toda vez que clicarmos no botão, através do método preventDefault podemos evitar o carregamento padrão da pág.

form.addEventListener('submit', event=> {
event.preventDefault()

})

-------------------------------------------------

Agora que impedimos que a pág fosse recarregada podemos no momento em que o form for enviado obter os dados que o usuário inseriu no form.

const form = document.querySelector('.singup-form')
const usernameInput = document.querySelector('#username')

form.addEventListener('submit', event=> {
event.preventDefault()
console.log(usernameInput.value)
 }) 

Dentro da função quando o evento submit acontecer, usaremos essa propriedade value para obter o valor que foi inserido nesse input. Essa é uma das formas de obter o valor que foi inserido no input no momento do envio do form, mas também existem outras maneiras.

----------------------------------------------------

const form = document.querySelector('.singup-form')

form.addEventListener('submit', event=> {
event.preventDefault()
console.log(form.username.value)
})                

Observe que temos um form e que já obtivemos a referencia e dentro desse form temos um input com ID=USERNAME, quando um input dentro de um formulário tem um id, podemos  obter a referencia desse imput através da referencia do form e do id do input.            
Se salvarmos e enviarmos o form, obtemos a referencia desse input com id=username, e se no momento do envio do form quisermos obter o valor desse input, podemos encadear a .value na referencia desse input.
Quando salvamos qualquer coisa desse input e enviamos o form, vemos o valor do form exibido no console.

----------------------------------------------------

Também podemos obter esse valor atraves do name do input. Se substituirmos o ID do FORM no html por name e digitarmos qualquer cosia no input dessa aula e enviarmos, também veremos o valor do form exibido no console.

--------------------------------------------------

E também existe uma outra forma de obter a referencia do input que pode ser útil mais a frente quando estivermos trabalhando com forms no react.             

const form = document.querySelector('.singup-form')

form.addEventListener('submit', event=> {
event.preventDefault()
console.log(event.target.username.value)

})

event.target.username essa expressão no console resulta no input do ID que tem username, e para obter o valor desse input usamos a .value.

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
