### ISSUE TITLE
Resumo da aula: Constantes, Variáveis e Comentários, da Etapa 01-06.

### ISSUE THREAD

**Issue by depizzolx** [roger-melo-treinamentos/curso-de-js-roger-melo#5215]
###  - Constantes;
Uma constante é como se fosse uma variável _(armazena um valor, seja ele um nome, um email, ou um número)_, mas com o valor imutável; ou seja, ela não pode variar, tem um valor fixo.
É usada quando não queremos que outro valor seja atribuído a esse elemento.

```js
const age = 31
```

### - Variáveis; 
Uma variável armazena um valor, seja ele um nome, um email, ou um número.
A variável só pode ser nomeada com uma única palavra, para nomearmos com duas ou mais palavras, usamos a convenção CanalCase, onde a primeira letra da palavra é minúscula, e a primeira das demais palavras são maiúsculas. Por exemplo: "euSouLindo";
O nome de uma variável não pode começar com um número; 
Sempre dar nomes claros para uma variável, para sabermos o que significa apenas pelo nome atribuído a ela;
Você pode declarar uma variável com o "let", da seguinte forma:

_NT: Se é uma variável, o valor pode variar._

```js
let age = 31
```
No código acima, você está declarando uma "let", com o nome "age", que a esse nome é atribuído(=) o número, o "31". Sendo assim, a palavra "age" é um container do valor "31". Lê-se: "age" recebe "31". 
Se logo abaixo da declaração da variável eu definisse o "age" como "40", por exemplo, à partir daquele ponto o valor atribuído deixaria de ser o "31" e retornaria o número "40".
```js
let age = 31
age = 40
```

### - Comentários:
É possível adicionar comentários dentro do Editor de Código, que não são executados pelo JS, usando "//" antes do que se quer comentar, ou usar "/*" "*/", para comentar quebrando linhas, como por exemplo:
```js
//comentário aleatório.

/*
ai
AI
*/
```

**Comment by Roger-Melo** [comment]
Boa @depizzolx rumo à fluência! 🔥
