### ISSUE TITLE
Resumo da Aula Adicionando métodos da etapa 04

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#5216]
Um **método** dentro de um objeto tambem é composto por de uma par formado pelo nome da propriedade e pelo seu valor.
Por exemplo para adicionarmos um método **login** inserimos a propriedade **login** que recebe uma função e dentro da função inserimos o comando que vai ser executado ao invocarmos esse método.

como a propriedade **login** armazena uma função, ela é chamada de método e esse faz parte do objeto **user**
Então invocamos esse método através de **user.login()**

Métodos são funçoes criadas dentro de um objeto. inclusive métodos ja aclopados no javascript como **.toUpperCase()**

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr rumo à fluência! 🔥
