### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by marcoferreiradev** [roger-melo-treinamentos/curso-de-js-roger-melo#522]
# Resumo da Aula Strings 

Strings são sequências de caracteres, normalmente dentro de '' aspas simples ou "" aspas duplas;

````js
const email = 'mw.marcowilliam@gmail.com.br'

console.log(email)
````

### Para concatenar strings
````js
const firstName = 'Marco'
const lastName = 'Ferreira'
const fullName = firstName + ' ' + lastName

console.log(fullName)
````

### Para acessar posições dentro da string
````js
console.log(fullName[2])
````

### Para ver o comprimento de uma string
Usa-se a propriedade length:
````js
console.log(fullName.length)
````

### toUpperCase - Tornar em maiúsculo o conteúdo da string sem alterar o valor original
````js
console.log(fullName.toUpperCase())
````

### toLowerCase - Tornar em minúsculo o conteúdo da string
````js
const result = fullName.toLowerCase();
console.log(result)
````

### indexOf - retorna o índice do **argumento** passado para o método
````js
const index = email.indexOf('@')
console.log(index)
````

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @marcoferreiradev! 👊🏻
