### ISSUE TITLE
Resumo da Aula Array - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#523]
# Array

Array serve para armazenar uma lista de valores que geralmente tem uma relação entre si.

```js
let heros = ['Batman', 'Catwoman', 'Iron Man'];
cons ages = [31, 25, 39, 40];
```

Também é possível criar um array de diferentes tipos de dados, mesmo que isso não faça muito sentido.

```js
const randomArray = ['Parker', 'Diana', 19, 28];
```

## Substituir o valor de um índice do array

Basta usar [] com o número que representa o índice onde há determinado valor que se deseja sobrescrever e atribuir um novo valor:

```js
heros[2] = 'Spider-Man';
```

## Métodos de array

Métodos são funções que são de determinado objeto ou tipo de dado.

1. join
2. indexOf
3. concat
4. push
5. pop

### join

Retorna uma nova string, concatena os itens e os separa por vírgula ou pelo caractere que for passado por argumento. O argumento é opcional.

```js
const joinHeros = heros.join();
const joinHerosTwo = heros.join('-');
```
**join não altera o array original.**

### indexOf

É usado no array para retomar o índice de determinado valor que foi passado por argumento. Caso esse valor não exista, é retornado -1.

```js
const age = [31, 25, 39, 40];

const indexOf31 = age.indexOf(31); // indexOf31 possui o valor 0
const indexOf20 = age.indexOf(20) // indexOf20 possui o valor -1
```

**Não altera o array original**

### concat

É usado para concatenar 2 arrays.

```js
const newHeros = heros.concat(['Superman', 'Wolverine']);
```

**Não altera o array original**

### push

Adiciona itens no fim do array

```js
const pushToHeros = heros.push('Cyclops', 'Hulk');

// pushToHeros retorna a nova quantindade de itens no array
// heros retorna o novo array
````

**Altera o array original (mutação de valores)**

### pop

Remove o último item do array e retorna esse item

```js
const popHeros = heros.pop();

// popHeros retorna o item removido
// heros retorna o novo array
```

**Altera o array original (mutação de valores)**

### length (propriedade)

É uma **propriedade** que também pode ser usada em array.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @rohyer! 🔥
