### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5230]
### _THIS EM JAVASCRIPT_

-  O this é um objeto de contexto.
-  O this dentro de uma function declaration tem como escopo o objeto ao qual o contém.
-  O this dentro de uma arrow function tem como base o ponto onde a invocação do método foi realizado. Nesse caso o this também fara referêcia ao objeto window.

```
const user = {
  name:"Everton",
  age:25,
  email:'devsukita@gmail.com',
  city:'Espirito Santos',
  blogPost:['Café','Pão','Biscoito'],
  login: function(){
    console.log('USUARIO LOGADO')
  },
  logout:function(){
    console.log('usuario deslogado')
  },
  logBlog(){
    console.log(`O ${this.name} fez uma cafe da manhã `)
    this.blogPost.forEach((post)=>{
      console.log(post)
    })
  }
}
console.log(user.logBlog())
```

**Comment by Roger-Melo** [comment]
Excelente @EvertonMattos , rumo à fluência! 🎯
