### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01, exercício 02

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#525]
Boa tarde!
Roger

Roger teria algum problema eu resolver desta forma vi que na correção ficou muito mais simples porém fiquei na duvida, sei que tenho que revisar e tentar resolver da mesma forma que vc mas ficou essa duvida se atrasa a execução do codigo ou tem algum problemas diferente.
PS: estou fazendo da seguinte forma o resumo apos uma semana estou refazendo os exercicios sem consulta alguma ai quando travo em algo sigo suas orientações vejo minhas anotações ou no maximo o codigo implementado naquele trecho esrá correto ?
```js
const animals = ['macaco', 'tucano', 'elefante', 'pavão', 'hipopótamo']
let isLionInAnimals = [];

for (let i = 0; i < animals.length; i++) {
  isLionInAnimals = animals.includes("leão");

  if (!isLionInAnimals) {
    console.log("Leão não existe no array animals.");
    break;
  } else {
    console.log("Existe um leão no array animals.");
    break;
  }
}
}
```
Desde já agradeço...

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcelo.

Não se preocupe em escrever código performático. Não no início.

O problema da solução na qual você exemplificou é que o `for` realmente não é necessário, pois o `includes` já percorre todos os itens do array. 

A grande sacada em executar [esse](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) passo-a-passo é fazer seu cérebro internalizar princípios que serão intensificados nas aulas e exercícios seguintes.

À medida em que você for avançando no treinamento, verá que o `for` vai ser utilizado cada vez menos, pois existem outras maneiras de percorrer arrays de forma mais objetiva e específica (o `includes` é uma delas).

Pegou a ideia?

@Mlluiz39

**Comment by Mlluiz39** [comment]
Entendi sim obrigado !
Desculpas eu acabei colocando o nome do video errado.

**Comment by Roger-Melo** [comment]
Tranquilo. Já que ficou mais claro vou fechar a issue, mas quando surgirem dúvidas é só abrir uma nova =)

@Mlluiz39
