### ISSUE TITLE
Resumo da Aula Conhecendo a date-fns 02-03 da etapa 10

### ISSUE THREAD

**Issue by EussouShAd** [roger-melo-treinamentos/curso-de-js-roger-melo#5251]
# DATE-FNS

### Como obter a date-fns ?
Acesse o site date-fns.org e vá em getting installation. As versões acima de 1.9 são instaladas utilizando o npm. Caso queira fazer a instalação por CDN é preciso selecionar a versão 1.9 e inserir o link do CDN no index.html com a tag script src.
No link do CDN onde aparece /VERSION/ substitua por v1.9.0. Após a instalação para verificar se esta funcionando pode usar um console.log(dateFns), aparecerá uma lista de métodos que podem ser utilizados. Para podermos utilizar os métodos e propriedades que a date-fns disponibiliza e vemos declarar o objeto 'dateFns' e invocar o método e propriedade desejado.
Consulte a documentação da biblioteca para verificar como funciona os métodos, propriedades, parâmetros e argumentos.

Data Atual
```js
const present = new Date()
```
Checando se a data informada como argumento é a data de hoje
Retorna um boolean
```js
const today = dateFns.isToday(present)
```
Formatando datas passando um parâmetro obrigatório e dois opcionais o primeiro é a data que queremos formatar o segundo é uma string com os tokens que que definirão como será a formatação o terceiro é um objeto que contém opções extras de configuração, 
```js
const day = dateFns.format(present, 'DD')
const month = dateFns.format(present, 'MM')
const year = dateFns.format(present, 'YYYY')
const fullDate = dateFns.format(present, 'DD/MM/YYYY')
```
Comparando duas datas recebe 3 argumentos, o último é opcional os dois primeiros serão as datas a serem comparadas
o último será um objeto com algumas configurações extras
```js
const past = new Date('Aug 24 1996 00:00:00')
dateFns.distanceInWords(present, past) // about 25 years
dateFns.distanceInWords(present, past, { addSuffix:true }) // about 25 years ago

**Comment by Roger-Melo** [comment]
Excelente @EussouShAd, rumo à fluência! 🎯
