### ISSUE TITLE
Resumo da Aula Arrays - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5252]
Arrays são para armazenar uma lista de valores que geralmente tem uma relação entre si, ex: lista de números ou lista de strings.
 Para encontrar uma posição de um array no console.log(valor[]) passamos colchetes. Para subescrever um array e atribuir e passado dessa seguinte forma ex: heroes[2] = 'Spider-Man'.
Métodos de arrays básicos são o join() que retorna uma nova string com todos os itens do array concatenados e separados por vírgula, pode receber um argumento opcional que pode ser um separador. O indexOf() vai obter o index da primeira ocorrência do número do array passado. O concat([])concatenar, juntar 02 arrays. O push() valores que podem ser empurrados e adicionados no fim do array e retorna um novo número de array que tem agora e esse método já altera o array original. Método pop() remove o último item de um array e retorna esse mesmo item, se torna um container e esse também modifica o array original.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
