### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by viniciusnunhez27** [roger-melo-treinamentos/curso-de-js-roger-melo#5261]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/viniciusnunhez27/Quiz

### Maiores dificuldades durante a implementação

Mostrar a pontuação sem alterar o HTML , foi necessário cololcar uma classe  " score " , para que eu possa inserir o texto do score.

### Menores dificuldades durante a implementação

Mapear os elementos e os valores do Quiz.

**Comment by MivlaM** [comment]
Olá @viniciusnunhez27.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Mas antes disso, eu abri a aplicação e fiz alguns testes, depois de escolher as alternativas do quiz, cliquei no botão para enviar, porém esse botão não está funcionando corretamente.  Você deseja que a análise seja feita sem essa funcionalidade funcionando, ou você deseja enviar novamente?

Avise por aqui para que possamos prosseguir com o processo de análise de aplicação =)

Fico no aguardo.

**Comment by viniciusnunhez27** [comment]
Boa tarde , vou verifica de já lhe retorno

Em sex., 7 de out. de 2022 às 13:16, MivlaM ***@***.***>
escreveu:

**Comment by viniciusnunhez27** [comment]
Maykell

Realizei o ajuste , caso tenha algum problema a mais por favor me informar .
Desde já agradeço a sua atenção.

@MivlaM

**Comment by Roger-Melo** [comment]
Olá @viniciusnunhez27.

Passando para dizer que visualizei a issue e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @viniciusnunhez27.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Mostrar a pontuação sem alterar o HTML , foi necessário cololcar uma classe " score " , para que eu possa inserir o texto do score.

Sem problemas, não há certo ou errado na forma de exibir os pontos, o mais importante num primeiro momento você já fez, que é implementar a lógica de exibição =)

Antes de qualquer coisa, seu código tá bem legal porque por ele eu percebi que vc está preocupado em aprender o básico antes de improvisar. Esse é um princípio fundamental que muitos atropelam.

Ao invés de tentar fazer outras coisas, vc fez o básico simples e funcional bem feito. Parabéns por isso. 

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisóes

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Isso dá mais legibilidade ao ler a expressão `userAnswer === anserwsCorrect[index]`.

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco em excesso: 27, 26 e 8

```js
// antes
form.addEventListener('submit', event => {
    event.preventDefault()


let score = 0

 const userAnswers =  [
   form.inputQuestion1.value,
   form.inputQuestion2.value,
   form.inputQuestion3.value,
   form.inputQuestion4.value,
 ]

 userAnswers.forEach((userAnswer, index) => {
    if(userAnswer === anserwsCorrect[index]){
      score += 25
    }
 })

  textScore.innerHTML = `<h3>Seu score é: ${score}</h3`  


})
```

```js
// depois
form.addEventListener('submit', event => {
    event.preventDefault()

let score = 0

 const userAnswers =  [
   form.inputQuestion1.value,
   form.inputQuestion2.value,
   form.inputQuestion3.value,
   form.inputQuestion4.value,
 ]

 userAnswers.forEach((userAnswer, index) => {
    if(userAnswer === anserwsCorrect[index]){
      score += 25
    }
 })

  textScore.innerHTML = `<h3>Seu score é: ${score}</h3`  
})
```

---

## Indentação

Indentação é um dos pilares de um código mais legível.

Sabendo disso, você pode deixar o código mais fácil de entender ao indentar também a let `score` e remover um espaço antes de `event.preventDefault()` dentro do listener de evento. Ficaria assim:

```js
// antes
form.addEventListener('submit', event => {
    event.preventDefault()

let score = 0

  // ...

})
```

```js
// depois
form.addEventListener('submit', event => {
  event.preventDefault()

  let score = 0

  // ...
 
})
```

---

## Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Uma observação seria em relação a const `textScore`, essa const pode ter seu nome reorganizado de forma que soe mais natural segundo as normas ortográficas da língua inglesa. O que você pode fazer aqui, se achar que é coerente, é trocar o nome de `textScore` para `scoreText`.

```js
// antes
const textScore = document.querySelector('.score')
```

```js
// depois
const scoreText = document.querySelector('.score')
```

Um pequeno ajuste ortográfico pode ser feito na const `anserwsCorrect` e ela também pode ter o nome reorganizado de forma semelhante ao caso mostrado acima, portanto podemos reescrevê-la de forma que ela seja entendida de forma mais clara e exata para quem estiver lendo o código. Uma sugestão seria, renomeá-la para `correctAnswers`.

```js
// antes
const anserwsCorrect = ['C', 'A', 'B', 'C']
```

```js
// depois
const correctAnswers = ['C', 'A', 'B', 'C']
```

---

## Callback do listener de envio do form

Podemos nomear o callback do listener de evento como `showScore`, por exemplo. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, o intuito aqui é nomeá-lo descrevendo a ação mais significativa que essa função irá executar na aplicação quando o form for enviado, assim ao bater o olho no nome da função, a ação que ela executa fica explícita:


```js
// antes
form.addEventListener('submit', event => {
  // ...
})
```


```js
// depois
const showScore = event => {
  // ...
}
form.addEventListener('submit', showScore)
```

---

## Refatoração das funções

Feito esses ajustes, vou te mostrar duas abordagens de refactoring usando métodos que você vai encontrar em breve nas aulas seguintes, ambos serão explicados com detalhes futuramente. O que quero que você entenda, nesse primeiro momento, é o conceito por trás deles. Sabendo disso, observe o código abaixo:

```js
userAnswers.forEach((userAnswer, index) => {
  if(userAnswer === correctAnswers[index]){
    score += 25
  }
})
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, vamos declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Por esse momento, vamos manter uma lógica similar a que você usou dentro dessa nova função:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
    score += 25
    }
  })
}
```

Depois, a let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 25 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
      return accumulator + 25
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 25, que na primeira execução será (0 + 25). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 25, na segunda execução o parâmetro `accumulator` estará armazenando 25 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 25 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator, 0)
```

Por fim, você pode invocar a função `getScore()` dentro da função `showScore` recebendo o array armazenado por `userAnswers` como argumento.

```js
const showScore = event => {
  // ...
  const score = getScore(userAnswers)
 // ...
}
```

Legibilidade em funcionalidades que a gente ainda não conhece na linguagem pode ser algo um pouco complicado no começo, porém quanto mais você praticar, mais você vai se acostumar com esse tipo de código declarativo. Percebe-se que a função foi resumida em apenas duas linhas =)

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. `userAnswers` vai receber um array vazio que será preenchido após percorrermos cada item dentro do array `correctAnswers` por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Lembre-se da ideia de que quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. A cada execução desse callback, o valor que a função está retornando vai ser inserido nesse novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, você pode invocar a função dentro da função `showScore` que o código funcionará normalmente =)

```js
const showScore = event => {
  event.preventDefault()
  
  const userAnswers = getUserAnswers()
  const score = getScore(userAnswers)
  
  textScore.innerHTML = `<h3>Seu score é: ${score}</h3`   
}
```

Por meio de um código declarativo, como foi mostrado nas duas últimas abordagens, sua aplicação vai tender a ter menos bugs, e com menos bugs ela será mais fácil de manter. Entendeu a ideia?

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by viniciusnunhez27** [comment]
Boa tarde, 

Obrigado pela explicação , anotei alguns pontos para melhoria nos próximos projetos que serão realizados.

Desde já agradeço  a sua atenção @MivlaM .

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
