### ISSUE TITLE
Resumo da Aula 02-05 da etapa 01 (Numbers)

### ISSUE THREAD

**Issue by romulofrontend** [roger-melo-treinamentos/curso-de-js-roger-melo#5265]
### INTEIROS E DECIMAIS
- Valores podem ser inteiros ou decimais
- Valores decimais são expressos com . em vez de ,

```javascript
const radius = 10;
const pi = 3.14;
console.log (radius,pi);
```
**Resultado Exibido pelo Console**
```javascript
10 3.14
```
---

### OPERADORES ARITMÉTICOS
Com numbers podemos fazer todos os tipos de operações matemáticas
Soma,  Subtração, Multiplicação, Divisão, Resto e Exponenciação

---

### ORDEM DE OPERAÇÕES
**1º -** Parênteses
**2º -** Expoentes ou Raízes
**3º -** Multiplicações e divisões
**4º -** Adições e Subtrações

```javascript
const area = pi * radius ** 2;
console.log(area);
```
**1)** Resolve a exponenciação `(radius ** 2)`
**2)** Resolve a multiplicação `pi *`

```javascript
const crazyOperation = 5 * (10 - 3) ** 2;
console.log(crazyOperation);
```
**1)** Resolve os parenteses `(10 - 3)`
**2)** Resolve a exponenciação `** 2`
**3)** Resolve a multiplicação `5 *`

---

## OPERADORES DE INCREMENTO E DECREMENTO
Pra atrubuição de valores precisar ser let
```javascript
let postLikes = 10;
```
**INCREMENTO: nomevariavel + 1 ou nomevariavel++**
```javascript
postLikes++
console.log(postLikes);
```
Resultado exibido pelo console
```javascript
11
```

**DECREMENTO: nomevariavel + 1 ou nomevariavel++**
```javascript
postLikes--
console.log(postLikes);
```

Resultado exibido pelo console
```javascript
10
```
---

## ADDITION, SUBTRACTION, MULTIPLICATION E DIVISION ASSIGMENT
**ADDITION ASSIGMENT (+=)**
```javascript
postLikes += 10;
console.log(postLikes);
```
Resultado exibido pelo console
```javascript
20
```

**SUBTRACTION ASSIGMENT (-=)**
```javascript
postLikes -= 5;
console.log(postLikes);
```
Resultado exibido pelo console
```javascript
15
```

**MULTIPLICATION ASSIGMENT (*=)**
```javascript
postLikes *= 5;
console.log(postLikes);
```
Resultado exibido pelo console:
```javascript
75
```

**DIVISION ASSIGMENT (/=)**
```javascript
postLikes /= 5;
console.log(postLikes);
```
Resultado exibido pelo console:
```javascript
15
```
---

## NaN - NOT A NUMBER
Exibido quando a operação não faz sentido. Quando não resulta num número.
```javascript
console.log(7/'oi');
```
Resultado exibido pelo console:
```javascript
NaN
```
---

## CONCATENAÇÃO DE NÚMEROS E STRINGS
É possivel concatenar strings e numbers
"Por trás do código", ao concatenar o js converte o number em string, exibindo ao todo uma string.
```javascript
const likesMessage = 'O post tem ' + postLikes + ' likes.';
console.log(likesMessage);
```
Resultado exibido pelo console:
```
O post tem 15 likes.
```

**Comment by Roger-Melo** [comment]
Excelente @romulofrontend, rumo à fluência! 🎯
