### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5270]
Null representa um valor nulo ou vazio e deve ser atribuído de forma proposital e quando for indicar intencionalmente que não existe um valor em uma variável.
Undefined  representa um valor indefinido, acontece quando não se atribui a uma variável.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37 , rumo à fluência! 🎯
