### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5273]
**Quando utilizamos setattribute para adicionar estilos em um elemento, ele pode sobreescrever o estilo que o elemento já tinha.
Neste caso podemos utilizar a propriedade styles para adicionar, obter e remover estilos de um elemento.**

```
const title = document.querySelector('h1')

// setAttribute ele sobreesqueve o que o style ja tem no html

title.setAttribute('style', 'margin: 50px;')

// Adicionando stilos sem apagar os estilos anteriores css inline

title.style.margin = '50px'
title.style.color = 'pink'
title.style.fontSize = '50px'

// Removendo o style

title.style.margin = ''
```
**OBS: Quando escrever propriedades CSS no JS ao invés do “ - “ é utilizado CamelCase.

EX:

Font-size = Maneira errada

FontSize = Maneira correta.**

**Comment by Roger-Melo** [comment]
Excelente @EvertonMattos , rumo à fluência! 🎯
