### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5274]
### **Operador "OU" que é representado por "`||`"**

- O operador "OU" é executado quando ambas condições são verdadeiras
 
**Exemplo:**

```
const password = 'oi123oi'

if (password.length >= 12 || password.includes('1')) {
    console.log('senha muito forte =)')
}
```
> No exemplo acima o `console.log` será executado se a variável password for maior que 12 e se ao mesmo tempo a variável possuir o caractere "1"

- O operador lógico `OU` pode ser usado mais de uma vez.

**Exemplo:**
```
const password = 'oi123oi'

if (password.length >= 12 || password.includes('1') || password.length >= 6) {
    console.log('senha muito forte =)')
}
```

### **Operador "E" que é representado por "`&&`"**

- O operador "E" é executado quando uma das condições forem verdadeiras.

**Exemplo:**
```
const password = 'oi123oi'

if (password.length >= 12 && password.includes('1')) {
    console.log('senha muito forte =)')
} 
```
> No exemplo acima o `console.log` será executado se a variável password for maior que 12 ou se ela possuir o caractere "1"

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos , rumo à fluência! 🎯
