### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#528]
# Removendo um elemento do DOM

### Temos como exemplo:
![image](https://user-images.githubusercontent.com/42559009/115598664-07e08d80-a2b1-11eb-9a23-c4223b014dbd.png)

```javascript
//pegamos a referencia do elemento
const lis = document.querySelectorAll("li");

//utilizamos o método remove
lis.forEach((li) => {
  li.addEventListener("click", (event) => {
    const clickedElement = event.target;

    clickedElement.remove();
  });
});
```
### Saída
![image](https://user-images.githubusercontent.com/42559009/115603022-08c7ee00-a2b6-11eb-9b78-624a0e98c158.png)

Agora toda vez que clicarmos em um dos elementos "li" na tela, ele é removido do DOM.

<hr/>

# Adicionando um elemento no DOM

### Temos como exemplo:
![image](https://user-images.githubusercontent.com/42559009/115603515-9efc1400-a2b6-11eb-8ca6-48f33296588d.png)

### 1º Método - innerHTML
Vamos fazer um novo item ser inserido na tela...
```javascript
//pegamos a referencia do botão
const button = document.querySelector("button");

//adicionamos um eventListener, um evento de "click" e utilizamos innerHTML para mostrar na tela.
button.addEventListener("click", () => {
  button.innerHTML += "<li>Novo item</li>"
});
```
### Saída
![image](https://user-images.githubusercontent.com/42559009/115603364-7247fc80-a2b6-11eb-8336-ec32d8ab1364.png)
Ao clicar no botão um novo elemento será adicionado ao final da "ul"

<hr/>

### 2º Método - createElement("")
Vamos criar um novo item com base na referencia do anterior para ser apresentado no console.

```javascript 
//pegamos a referencia do botão
const button = document.querySelector("button");

//adicionamos um eventListener e um evento de "click"
//porém desta vez iremos criar um novo elemento utilizando o método createElement("")
button.addEventListener("click", () => {
  const li = document.createElement("li");
  console.log("Novo item");
});
```
### Saída
![image](https://user-images.githubusercontent.com/42559009/115603925-22b60080-a2b7-11eb-8022-f7d84a3433bc.png)
Toda vez que clicarmos no botão, um novo item aparecerá no console

<hr/>

### 3º Método - append e prepend
Vamos criar um novo item com base na referencia do anterior e inseri-lo na tela, utilizando:
append = utilizando um elemento pai, o método append apresenta um elemento filho como seu último item.
prepend = utilizando um elemento pai, o método prepend apresenta um elemento filho como seu primeiro item.

```javascript 
//pegamos a referencia do botão
const button = document.querySelector("button");

//adicionamos um eventListener e um evento de "click"
//iremos criar um novo elemento utilizando o método createElement("")

button.addEventListener("click", () => {
  const li = document.createElement("li");

//apontamos com o textContent o conteúdo que aparecerá na tela.
  li.textContent = "Novo item";
//e posicionamos ele como primeiro item da ul com o prepend
  ul.prepend(li);
});

//para adicionar o item no final da ul é só utilizar o append... ex: ul.append(li)
```
### Saída
![image](https://user-images.githubusercontent.com/42559009/115606720-7118ce80-a2ba-11eb-99a3-0c0276883c7e.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @davidtheblane! 🔥
