### ISSUE TITLE
Resumo da Aula A palavra chave THIS da etapa 04

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#5286]
Ao criarmos um método no objeto que precise ter o próprio objeto referenciado, nao usamos o nome do objeto e sim a palavra chave **this**. Entãp nesse caso a this refere-se ao objeto em que este método está sendo criado.
Mas o this é um objeto de contexto, ele representa o contexto no qual o código atual está sendo executado, então dependendo de onde ou como o this está sendo usado, o valor dele vai mudar.
Se o this estiver no escopo global, o valor dele será o **window**

Usamos **function declaration** para criar o método com o **this**. As arrow functions funcionam de forma diferente com o this.

Quando usamos function declaration com o método e invocamos esse método, o valos que o javaScript atribui ao this é o objeto no qual o método está sendo usado.

Quando usamos uma arrow function o this refere-se ao window.

Então quando formos usar o this em um método, se quisermos que o this referencie o o objeto no qual o método foi criado usamos function declaration ao invés de arrow function.

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr rumo à fluência! 🔥
