### ISSUE TITLE
Resumo da Aula Objeto Math da etapa 04

### ISSUE THREAD

**Issue by josejuniorvr** [roger-melo-treinamentos/curso-de-js-roger-melo#5288]
O Math é um dos objetos já embutidos no javaScript. Esse objeto tem muitas propriedades e métodos ja criados dentro dele.
Para vermos esse objeto usamos console.log(Math). Veremos no console um objeto Math que tem varias propriedades e varios métodos que podemos usar.

Math.PI : Obtemos o valor de PI
Math.E: obtemos o valor de E

**podemos arredondar numeros decimais:** 
**let area = 7.7**
Math.round(area): arredonda para o numero inteiro mais proximo

Math.floor(area): arredonda para o numero inteiro anterior

Math.ceil(area): arredonda para o numero inteiro posterior

Math.trunc(area): retira o numero decimal e deixa apenas o numero inteiro.

**Números aleatórios:**
const randomNumber = Math.random()
console.log(randomNumber): esse método random() gera um numero decimal aleatório entre 0 e 1.

console.log(Math.round(randomNumber)): 0 ou 1 são exibidos no console

Math.round(randomNumber * 100): um numero aleatório entre 0 e 100 será exibido a cada atualização do console(incluindo 0 e 100)

**Comment by Roger-Melo** [comment]
Boa @josejuniorvr rumo à fluência! 🔥
