### ISSUE TITLE
Dúvida exercício 06 for loop pasta exercícios 05

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5297]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/771837

### Descreva a dúvida

@Roger-Melo

Exercício 06
Após a const numbers, utilize um for loop para somar todos os números do array;
Exiba no console um boolean indicando se o total dessa soma é 337;
O console deve exibir true.

```javascript
const numbers = ['91', '5', '30', '97', '83', '31']

let sum = 0

for (let i = 0; i < numbers.length; i++) {
 sum += Number(numbers[i])
}
console.log(sum === 337)
```

Não consegui entender a lógico sobre o motivo de ter que declarar a let sum = 0

Obrigado.

**Comment by Roger-Melo** [comment]
Oi @Ale557333!

Essa é a mesma dúvida que vc postou no grupo do Telegram?

Ela foi resolvida ou precisa de mais ajuda?

**Comment by Ale557333** [comment]
> Oi @Ale557333!
> 
> Essa é uma das dúvidas que vc postou no grupo do Telegram?
> 
> Ela foi resolvida ou precisa de mais ajuda?

Foi resolvida sim no Telegram Roger. Muito obrigado.

**Comment by Roger-Melo** [comment]
Show. Vou fechar as issues, mas no que precisar, é só abrir uma nova =)
