### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by fernandomk6** [roger-melo-treinamentos/curso-de-js-roger-melo#5302]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Sim

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/fernandomk6/Quiz-Interativo

### Maiores dificuldades durante a implementação

# Maiores dificuldades durante a implementação

1. Manipular componentes (modal) do bootstrap, pois nunca tinha usado antes. Precisei pesquisar um pouco.
2. Configurar uma mensagem de feedback dependendo da pontuação obtida no quiz.

### Menores dificuldades durante a implementação

# Menores dificuldades durante a implementação

1. Implementar logica de pontuação

**Comment by fernandomk6** [comment]
# Correções Efetuadas

- Removido ferramentas adicionais
- Feito as modificações necessárias

**Comment by MivlaM** [comment]
Olá @fernandomk6

Tudo certo agora! Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá, @fernandomk6.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Manipular componentes (modal) do bootstrap, pois nunca tinha usado antes. Precisei pesquisar um pouco.

O uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

> ## Configurar uma mensagem de feedback dependendo da pontuação obtida no quiz.

Pelo que eu vi no seu código, o mais importante vc já fez, que é fazer funcionar. Mesmo com a dificuldade relatada, você conseguiu =)

Vou mostrar durante a análise uma forma de refatoração de obtenção da mensagem em que será baseada na pontuação.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

## Boas decisões

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

No geral, você escolheu nomes descritivos para suas variáveis e funções =)

O tema do seu quiz foi surpreendente e divertido =)

---

## Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo checked no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, pode ser interessante separar as consts que armazenam os elementos do DOM das consts relacionadas à pontuação por uma linha em branco. Dessa forma, a leitura do código se torna mais fácil.

```js
// antes
const form = document.querySelector('.quiz-form')
const modalResult = document.querySelector('.modal')
const correctAnswers = ['A', 'B', 'A', 'B', 'B']
const scoreParagraph = document.querySelector('#score')
const scoreFeedbackElement = document.querySelector('#result-feedback')
const closeModalResultButton = document.querySelector('#close-quiz')
const dangerScore = 40
const warningScore = 60
const sucessScore = 80
const maxScore = 100
let score = 0
```

```js
// depois
const form = document.querySelector('.quiz-form')
const modalResult = document.querySelector('.modal')
const correctAnswers = ['A', 'B', 'A', 'B', 'B']
const scoreParagraph = document.querySelector('#score')
const scoreFeedbackElement = document.querySelector('#result-feedback')
const closeModalResultButton = document.querySelector('#close-quiz')

const dangerScore = 40
const warningScore = 60
const sucessScore = 80
const maxScore = 100
let score = 0
```

Se fizer sentido para você, por a const `correctAnswers` estar desempenhando um papel diferente das demais, uma sugestão seria mover essa const para fora do meio das consts que armazenam os elementos do DOM. O intuito aqui, é facilitar ainda mais a organização do código tendo a separação de conceitos em mente.

```js
// antes
const form = document.querySelector('.quiz-form')
// ...
const correctAnswers = ['A', 'B', 'A', 'B', 'B']
// ...
const closeModalResultButton = document.querySelector('#close-quiz')
```

```js
// depois
const closeModalResultButton = document.querySelector('#close-quiz')

// ...
let score = 0

const correctAnswers = ['A', 'B', 'A', 'B', 'B']
```

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a const `closeModalResultButton` e a função `closeModalResult` que você usou no código podem ter seus nomes substituidos por `buttonCloseModal` e `closeModal` respectivamente. O intuito aqui é fazer com que os nomes diminuam de comprimento e ao mesmo tempo mantenham o sentido original.

```js
// antes
const closeModalResultButton = document.querySelector('#close-quiz')

const closeModalResult = () => modalResult.style.display = 'none'
```

```js
// depois
const buttonCloseModal = document.querySelector('#close-quiz')

const closeModal = () => modalResult.style.display = 'none'
```

Uma outra observação seria, se estiver de acordo, trocar o nome de `modalResult` para `modalScore`. Nesse contexto, result e score querem dizer basicamente a mesma coisa. É interessante usar apenas uma única palavra que já esteja familiarizada para definir esse nome no decorrer da aplicação. Por você já ter usado a palavra `score` anteriormente, optei por essa versão. 

```js
// antes
const modalResult = document.querySelector('.modal')
```

```js
// depois
const modalScore = document.querySelector('.modal')
```

Por fim, você também pode renomear a const `scoreParagraph` para `scoreMessage`, a ideia aqui é caso futuramente o elemento mudar para h3, por exemplo, a const não precisará ser renomeada, pois a nomenclatura da const estará escrita de forma mais abrangente.

```js
// antes
const scoreParagraph = document.querySelector('#score')
```

```js
// depois
const scoreMessage = document.querySelector('#score')
```

---

## Omissão de blocos em `if`s

Cuidado ao omitir blocos em ifs, como você fez nos trechos abaixo:

```js
const checkAnswer = (userAnswer, index) => {
  // ...
  if(!isRightAnswer) return
  // ...
}
```

```js
const showScore = event => {
  // ...

  if (score <= dangerScore) renderFeedback(dangerFeedbackInfo)
  if (score === warningScore) renderFeedback(warningFeedbackInfo)
  if (score === sucessScore) renderFeedback(successFeedbackInfo)
  if (score === maxScore) renderFeedback(maxFeedbackInfo)

  // ...
}
```

[Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos e colocou a segurança de dados em xeque por causa desse tipo de decisão.

---

## Refatorações nas funções

Feito esses ajustes, logo em seguida vou te mostrar duas abordagens de refactoring usando métodos que você vai encontrar em breve nas aulas seguintes, ambos serão explicados com detalhes futuramente. O que quero que você entenda, nesse primeiro momento, é o conceito por trás deles. Sabendo disso, observe o código abaixo:

```js
const checkAnswer = (userAnswer, index) => {
  const questionScore = maxScore / correctAnswers.length
  const isRightAnswer = userAnswer === correctAnswers[index]

  if(!isRightAnswer) return

  addToScore(questionScore)
}

const addToScore = questionScore => score += questionScore
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, vamos declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Por esse momento, vamos manter uma lógica similar à seguinte:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
      score += 20
    }
  })
}
```

Na lógica acima, o array que armazena as respostas do usuário está sendo percorrido por um forEach e para cada resposta verdadeira segundo a lógica armazenada pela const `isAnswerCorrect`, uma pontuação de 20 pontos está sendo adicionada a let `score`. Agora, quero que atente-se às modificações que vamos fazer nessa lógica. A let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 20 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const isAnswerCorrect = userAnswer === correctAnswers[index]

    if(isAnswerCorrect){
      return accumulator + 20
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 20, que na primeira execução será (0 + 20). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 20, na segunda execução o parâmetro `accumulator` estará armazenando 20 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 20 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 20 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 20 : accumulator, 0)
```

Por fim, você pode remover as funções `addToScore` e `checkAnswers` e invocar a função `getScore()` dentro da função `showScore` recebendo o array armazenado por `userAnswers` como argumento.

```js
const showScore = event => {
  // ...
  const score = getScore(userAnswers)
 // ...
}
```

Legibilidade em funcionalidades que a gente ainda não conhece na linguagem pode ser algo um pouco complicado no começo, porém quanto mais você praticar, mais você vai se acostumar com esse tipo de código declarativo. Percebe-se que a função foi resumida em apenas duas linhas =)

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter as respostas do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. userAnswers vai receber um array vazio que será preenchido após percorrermos cada item dentro do array correctAnswers por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, você pode invocar a função dentro da função `showScore` que o código funcionará normalmente =)

Há mais uma abordagem de refactoring que podemos fazer envolvendo a parte do código responsável para indicar qual mensagem será selecionada de acordo com a pontuação do usuário. Estou me referindo a esses trechos de código em específico. Há uma maneira de refatorar essa parte do código e deixá-la muito mais concisa e enxuta. Preparado? Vamos lá então!  

```js
const dangerScore = 40
const warningScore = 60
const sucessScore = 80
const maxScore = 100

const dangerFeedbackInfo = {
  className: 'text-danger',
  textContent: `Hmm... você errou a maioria das questões, 
    mas não desanime, você pode rever as aulas de etapa 1, e tentar novamente.`
}

const warningFeedbackInfo = {
  className: 'text-warning',
  textContent: `Você tirou uma nota razoável, mas é bom rever novamentes as aulas da etapa 1`
}

const successFeedbackInfo = {
  className: 'text-info',
  textContent: `Você acertou quase tudo, errou apenas uma questão. Você foi muito bem. =)`
}

const maxFeedbackInfo = {
  className: 'text-success',
  textContent: `Parabéns, Você acertou todas as questões. Você está pronto para a etapa 2`
}

const showScore = event => {
  // ...
  if (score <= dangerScore) renderFeedback(dangerFeedbackInfo)
  if (score === warningScore) renderFeedback(warningFeedbackInfo)
  if (score === sucessScore) renderFeedback(successFeedbackInfo)
  if (score === maxScore) renderFeedback(maxFeedbackInfo)
  // ...
}
```

Você percebe um padrão se repetindo e que apenas alguns dados específicos estão mudando? Sabendo disso, podemos criar uma função para fazer o papel de todos esses ifs, vamos criar uma função para retornar um objeto que vai conter todas as informações para cada um dos casos retratados no if. Se cada dado dentro do if está relacionado a mensagem de pontuação, podemos criar uma função chamada `getScoreMessage` que irá receber a pontuação que o usuário fez por meio de um parâmetro `score` que fará o mesmo papel de definir a mensagem e classe que o usuário receberá e que retornará esse objeto personalizado para cada caso. Visto que a mensagem se repete caso a pontuação seja 0, 20 e 40, podemos armazenar essa mensagem exclusivamente numa const `message` que substituirá o texto anteriormente armazenado em `textContent` dentro dessa função. Uma situação especial é o de caso `score` receba 0, não precisa inserir essa opção no objeto, podemos fazer com que essas informações sejam retornadas por meio de um || caso todas as outras situações sejam invalidas. Ficaria assim:

```js
const getScoreMessage = score => {
  const message = `Hmm... você errou a maioria das questões, 
  mas não desanime, você pode rever as aulas de etapa 1, e tentar novamente.`
  
  return {
    20: { className: 'text-danger', message},
    40: { className: 'text-danger', message},
    60: { className: 'text-warning', message: `Você tirou uma nota razoável, mas é bom rever novamentes as aulas da etapa 1`},
    80: { className: 'text-info', message: `Você acertou quase tudo, errou apenas uma questão. Você foi muito bem. =)` },
    100:{ className: 'text-success', message: `Parabéns, Você acertou todas as questões. Você está pronto para a etapa 2` }
  }[score] || { className: 'text-danger', message: `Hmm... você errou a maioria das questões, 
  mas não desanime, você pode rever as aulas de etapa 1, e tentar novamente.` }
}
```

Agora, podemos fazer um destructuring na invocação dessa função `getScoreMessage`. Sabendo que a função vai receber a pontuação do usuário armazenada em `score` e que sua invocação sempre vai retornar um objeto pois o valor de uma das propriedades dentro dela sempre será um objeto, podemos fazer um destructuring em `className` e `message`. Feito isso, todo aquele trecho de código mostrado no início dessa refatoração pode ser excluído. Apenas o trecho de código necessário para essa funcionalidade dentro de `showScore` será o de inserção das propriedades da função no DOM, assim conseguimos fazer com que o código faça a mesma coisa que o anterior antes de começar a refatoração e eliminamos muitas linhas desnecessárias. Por fim, o código de `renderScore`, `resetScore` e `showModalResult` podem ficar dentro de `showScore`, já que agora ela está muito menos extensa e o código que ela contém fara sentido com o nome dela:

```js
// Todas as funções abaixo podem ser removidas e seus respectivos códigos inseridos na showScore
const resetScore = () => score = 0
const renderScore = score => scoreMessage.textContent = `${score}%`
const showModalResult = () => modalScore.style.display = 'block'
```

```js
// Função showScore com os códigos das funções acima inseridos.
const showScore = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  const {className, message} = getScoreMessage(score)

  scoreFeedbackElement.setAttribute('class', className)
  scoreMessage.textContent = `${score}%`
  scoreFeedbackElement.textContent = message
  modalScore.style.display = 'block'
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by fernandomk6** [comment]
> As observações fizeram sentido?

Fizeram bastante sentido sim, vou retatorar todo o código com base nesse feedback.
Realmente todas as sugestões fizeram bastante sentido.

Obrigado pelo feedback.

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, se tiver alguma nova dúvida, sinta-se livre para abrir uma nova issue =)
