### ISSUE TITLE
Filter vs Valor passado por referência

### ISSUE THREAD

**Issue by fernandomk6** [roger-melo-treinamentos/curso-de-js-roger-melo#5307]
### Etapa da aula

8

### Nome da aula

Método filter aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/991048

### Descreva a dúvida

```js
const users = [
  { name: 'Ada Lovelace', premium: true },
  { name: 'Grace Hopper', premium: false },
  { name: 'Alan Turing', premium: true },
  { name: 'Linus Torvalds', premium: false },
  { name: 'Margaret Hamilton', premium: true }
]

const premiumUsers = users.filter(user => user.premium)

users[0].name = 'ticaracatica'
console.log({ users, premiumUsers })

// Dados exibidos no console
// array users 

[
    {
        "name": "ticaracatica",
        "premium": true
    },
    {
        "name": "Grace Hopper",
        "premium": false
    },
    {
        "name": "Alan Turing",
        "premium": true
    },
    {
        "name": "Linus Torvalds",
        "premium": false
    },
    {
        "name": "Margaret Hamilton",
        "premium": true
    }
]

// array premiumUsers

[
    {
        "name": "ticaracatica",
        "premium": true
    },
    {
        "name": "Alan Turing",
        "premium": true
    },
    {
        "name": "Margaret Hamilton",
        "premium": true
    }
]
```

Perceba que, ao alterar o primeiro elemento do array users, essa alteração foi
refletida no array preminumUsers.

Percebi que é por que o filter retornou o exato mesmo dado do array original, e não uma cópia.
Como objetos são passados por referência, uma referencia ao objeto original foi retornada.

A duvida é:

o filter quando encadeado em um array de objetos, é possível
fazer com que seja retornado um **novo** objeto (ou novo dado), 
ao invés de uma **referência** (dado original) ao objeto original?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @fernandomk6!

Excelente dúvida =)

Isso ainda será explorado conforme vc for avançando, mas é importante sacar que o filter sempre retorna um novo array. Porém, se os itens desse array são objetos (e como objetos são tipos de referência), o primeiro parâmetro do callback do filter é apenas uma referência para o item original.

Ou seja, no código abaixo, `true` é retornado por que o parâmetro `item` e a expressão `arr[index]` apontam para o exato mesmo objeto em memória:

```javascript
const arr = [
  { prop1: 'x', prop2: 'y' }
]

const x = arr.filter((item, index) => {
  console.log(item === arr[index]) // true
})

// ☝🏻 não implemente o callback sem return, o exemplo acima é apenas didático
```

Lembra que parâmetros são variáveis que podem ser usadas apenas no escopo da função? É por isso que o parâmetro `item` armazena o exato mesmo objeto que `arr[index]`. `item` é apenas uma segunda forma de obter o objeto do array.

Por isso o exemplo com variáveis mostrado na aula [Tipos de refêrencia vs Tipos primitivos - Aula 03-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/831889) se traduz também para o exemplo com o parâmetro `item`, já que parâmetros são variáveis. 

```javascript
// exemplo semelhante ao mostrado na aula
const x = { prop1: 1 }
const y = x

console.log(x === y) // true
```

No código acima, `y` recebeu o mesmo objeto que `x` armazena. Em outras palavras, `y` se tornou uma referência para o objeto `{ prop1: 1 }`.

---

> ## O filter quando encadeado em um array de objetos, é possível fazer com que seja retornado um **novo** objeto (ou novo dado), ao invés de uma **referência** (dado original) ao objeto original?

É possível sim, basta você criar um novo objeto.

Porém você deve fazer isso apenas se sentir que precisa modificar o objeto original. E na real vc não deve modificar o original, mas sim criar um novo objeto com as propriedades que você precisa.

No código abaixo, o callback está retornando um novo objeto. Esse novo objeto contém todas as propriedades do objeto recebido no parâmetro `obj`. Mas é um novo objeto. Por isso a comparação resulta em `false`:

```javascript
const arr = [
  { x: 1, y: 2 }
]

const w = arr.map(obj => ({
  ...obj
}))

console.log(arr[0] === w[0]) // false
```

No exemplo acima, não há necessidade de retornar um novo objeto, por que não existe a intenção de modificar o objeto.

Já no código abaixo, a const `doubledY` armazena um array com a propriedade `y` do objeto armazenando o dobro do valor original dessa propriedade. Então nesse caso, ao invés de modificar o objeto original (fazendo algo como `obj.y = obj.y * 2`), o ideal é deixar o objeto original intacto e criar um novo objeto com os valores que você precisa:

```javascript
const doubledY = arr.map(obj => ({
  ...obj,
  y: obj.y * 2
}))
```

E isso vale para qualquer parte do código que precise de mutação. 

Ao invés de usar mutação no objeto original, sempre que possível, prefira usar imutabilidade. Isso é, não modificar os valores no decorrer da aplicação. Se uma variável/propriedade/parâmetro foi declarado com um valor, ele deve ter esse valor até o fim da execução do programa. 

Está ficando mais claro? =)

**Comment by fernandomk6** [comment]
Com relação ao método map está bem claro.

A dúvida é com relação ao método filter

> O filter quando encadeado em um array de objetos, é possível fazer com que seja retornado um novo objeto (ou novo dado), ao invés de uma referência (dado original) ao objeto original?

> É possível sim, basta você criar um novo objeto.

No método filter, o callback deve retornar um boolean. Se for true, o item da iteração atual será
adicionado ao novo array. Até ai está claro. Porém quando o item atual é um objeto e o retorno 
da iteração atual é true, um **refêrencia** ao objeto atual é adicionado ao novo array, e não uma cópia. 

```js
const users = [{name: 'fernando'}]

const newUsers = users.filter(user => true)

console.log(users[0] === newUsers[0]) // true, pois é a mesma referencia

const a = {a: 'a'}
const b = {a: 'a'}

console.log(a === b) // false pois são referencias diferentes
```

A dúvida era para saber se tem como fazer item retornado pelo filter, ser uma copia do
item do array original.

**Comment by Roger-Melo** [comment]
Ahh, entendi!

O `filter` retorna o item original sim, não há como modificar esse comportamento.

Se vc precisar fazer uma cópia dos objetos do array que o filter gerou, isso deve ser feito encadeando um `map` no array que o `filter` gerou =)

@fernandomk6

**Comment by fernandomk6** [comment]
Boa, Roger, encadear o método map no retorno do filter é uma solução muito boa, valeu.

**Comment by Roger-Melo** [comment]
Boa! Vc sempre pode encadear algum método de array se o retorno da expressão resultar em um array =)
