### ISSUE TITLE
Resumo da Aula 02-06 da etapa 01 (Template Strings)

### ISSUE THREAD

**Issue by romulofrontend** [roger-melo-treinamentos/curso-de-js-roger-melo#5311]
## STRINGS  - CONCATENAÇÕES
Forma mais atual, organizada e limpa de injetar variáveis numa string.

#### Dadas as Variáveis:
```javascript
const postTitleEx1 = 'É bolacha ou biscoito?';
const postAuthorEx1 = 'Romulo Guilherme Rosa';
const postCommentsEx1 = 15;
```
#### Concatenando
- A ordem de fechamento de aspas influencia no funcionamento e exibição da string
- O sinal de + fazendo a concatenação da string junto as variáveis que são injetadas
```javascript
const postMessageEx1 = 'O post "' + postTitleEx1 + '", de ' + postAuthorEx1 + ' , tem ' + postCommentsEx1 + ' comentários.'
```

#### Para Exibir no Console
```javascript
console.log(postMessageEx1);
```

#### Resultado no Console
```
O post "É bolacha ou biscoito?", de Romulo Guilherme Rosa , tem 15 comentários.
```
---

#### Dadas as Variáveis:
```javascript
const postTitleEx2 = 'É feijão ou arroz?';
const postAuthorEx2 = 'Romulo Guilherme';
const postCommentsEx2 = 42;
```
#### Concatenando com Template Strings
- Forma muito mais simples, organizada e limpa de injetar varáaveis em strings
- Uso de sinal de crase no início e fim da string
- Uso de ${nomeVariavel} para injetar a variável na string
```javascript
const postMessageEx2 = `O post "${postTitleEx2}" de ${postAuthorEx2} tem ${postCommentsEx2} comentários.`
```

#### Para Exibir no Console
```javascript
console.log(postMessageEx2);
```

#### Resultado no Console
```
O post "É feijão ou arroz?" de Romulo Guilherme tem 42 comentários.
```
---

#### Dadas as Variáveis:
```javascript
const postTitleEx3 = 'É lazanha ou pizza?';
const postAuthorEx3 = 'Romulo Rosa';
const postCommentsEx3 = 22;
```
#### Criando Templates HTML
- Uso de sinal de crase no início e fim do template
- Uso de tags HTML 
- Uso de ${nomeVariavel} para injetar a variável nos templates

```javascript
const html = `
  <h2>Título: ${postTitleEx3}</h2>
  <p>Autor: ${postAuthorEx3}</p>
  <span>Este post tem ${postCommentsEx3} comentários</span>
`
```

#### Para Exibir no Console
```javascript
console.log(html);
```

#### Resultado no Console
```
<h2>Título: É lazanha ou pizza?</h2>
<p>Autor: Romulo Rosa</p>
<span>Este post tem 22 comentários</span>
```

**Comment by Roger-Melo** [comment]
Boa @romulofrontend rumo à fluência! 🔥
