### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5312]
Testando Regex

const username = 'hugos'

const pattern = /^[a-z]{5,}$/

const isAMatch = pattern.test(username)
console.log(isAMatch)

Pattern é a regex do exemplo, e para testar ela contamos com o método test e dentro dessa método passamos o username para conferir se há um match. Esse método sempre irá retornar um boolean.

-----------------------------------

Outra maneira é usar o método search, exemplo:

const result = username.search(pattern)
console.log(result)

Toda vez que o match entre a string e a regex não acontece o search retorna - 1, quando há um match o search retorna a posição do inicio da string aonde ouve match. O search é mais usado quando precisamos por exemplo descobrir em um paragrafo o idex no qual um padrão de regex da match nesse paragrafo, mas para testar inputs de formulários, na maioria das vezes usaremos o test( ).

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
