### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5314]
### **Function declaration**

- Essa forma de criar uma função se chama **Function Declaration**

```
function sayHi () { // Todo o código da função tem que ser inserido dentro desse bloco.
    console.log('Oi')
}
```
- **Agora em qualquer momento futuro podemos invocar essa função.**
- **Da mesma forma que nomeamos variáveis temos que nomear funções.**

### **Aqui estamos invocando a função "sayHi:"**

`sayHi( ) // Para acionar uma função tem que ser usado um ( )`

> **Essa invocação vai executar o código dentro da função "sayHi"**

- **Podemos invocar essa função várias vezes. Exemplo:**

```
sayHi()
sayHi()
sayHi()
```

### **Function expression**

- Essa forma de criar uma função se chama **Function expression**

```
const showFood = function () {
    console.log('pizza')
}

showFood() // Invocando a function "showFood"
showFood() 
showFood()
```

- **Podemos invocar funções quantas vezes forem necessarias**

### **Qual a diferença entre Function declaration e Function expression?**
**Praticamente nenhuma, mas tem um detalhe que você tem que saber.
`Hoisting `= Quando você cria uma função usando function declaration o javascript puxa a criação da função para o topo do arquivo. Então a function declaration pode ser coloca em qualquer lugar do código e não terá nenhum erro.**

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
