### ISSUE TITLE
Dúvida sobre const

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#5315]
### Etapa da aula

5

### Nome da aula

Adicionando e modificando conteúdo em uma página - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/853297

### Descreva a dúvida

Bom dia!

Surgiu a seguinte dúvida:
Levando em consideração que `const` não pode ter seu valor modificado, não entendi como foi possível alterar o valor nos 2 exemplos. Ademais, quando capturamos a tag, capturamos igualmente o `value` que está contida na respectiva tag, ou não?

```js
const paragrafo = document.querySelector('p')

//1°
paragrafo.innerText = ' Texto alternativo!'

//2°
paragrafo.innerText += ' Texto alternativo!'
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Bruno-Luna.

Uma const não garante imutabilidade. const apenas impede que um valor seja reatribuído =)

A const `paragrafo` que você deu como exemplo está armazenando um elemento do DOM, e por sua vez, um elemento do DOM é um objeto. Um objeto pode ter o valor de suas propriedades modificadas, ou seja, const não garante imutabilidade em objeto porque em Javascript objetos são mutáveis por padrão. É por isso que você pode mudar as propriedades desse objeto =)

Sabendo disso, a const `paragrafo` tem uma propriedade `innerText` que é possível mudar o valor dela assim como outras propriedades, porque esse elemento paragrafo do DOM é um objeto e objetos por padrão não são imutáveis em Javascript, mesmo que estejam armazenados por uma const.

Entendeu a ideia? =)

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova issue.
