### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#5317]
Comparações estrita

-  '_igual a_' e '_diferente de_' o JavaScript faz a conversão de valores

```js
console.log(age == 31) // true
console.log(age == '31') // true
console.log(age != 31) // false
console.log(age != '31') // false
```

- '_igual a, e do mesmo tipo_' e '_diferente de, e do mesmo tipo_' - O JavaScript não  faz a conversão de valores e leva em consideração o tipo da variável na comparação 

```js
console.log(age === 31) // true
console.log(age === '31') // false
console.log(age !== 31) // false
console.log(age !== '31') // true
```

**Comment by Roger-Melo** [comment]
Boa @Geisonszo rumo à fluência! 🔥
