### ISSUE TITLE
Resumo da Aula Event bubbling e event delegation - Aula 04-02 da etapa 05

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5319]
### Event bubbling:
**Quando um evento “bubbling” é realizado sobre um determinado elemento, todos os ancestrais dele também serão acionados em ordem crescente de aninhamento até chegar ao último elemento:**
![1 G_7x4sH8IB_wFIcWAju41g](https://user-images.githubusercontent.com/79621118/195928473-3c6a7970-d0fb-4f66-b5c5-c5a7b5ad2f83.png)
```
const pai     = document.getElementById('pai');
const filho   = document.getElementById('filho');
const neto    = document.getElementById("neto");

pai.addEventListener('click', x=>console.log("pai foi clicado"));
filho.addEventListener('click', x=>console.log("filho foi clicado"));
neto.addEventListener('click', x=>console.log("neto foi clicado"))
```
### Event delegation
**E uma funcionalidade atraves do Event bubbling que visa a interacao direta com um objeto do DOM atraves de um evento por exemplo. Usando o event.target obtemos o elemento em questao que utilizando o event bubbling e possivel automatizar de certa forma alguns comandos ao inves de coloca-los diretamente la, podendo ser gerados de forma interativa.**

**Comment by Roger-Melo** [comment]
Boa @EvertonMattos rumo à fluência! 🔥
