### ISSUE TITLE
Aplicação: to-do list

### ISSUE THREAD

**Issue by fernandomk6** [roger-melo-treinamentos/curso-de-js-roger-melo#5324]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/fernandomk6/To-do-List

### Maiores dificuldades durante a implementação

Mensagem de lista de resultados vazia conforme os resultados da pesquisa

### Menores dificuldades durante a implementação

Adicionar li (to-do) na ul (lista de todas os to-dos)

**Comment by Roger-Melo** [comment]
Olá @fernandomk6.

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @fernandomk6.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Mensagem de lista de resultados vazia conforme os resultados da pesquisa

O assunto listado será abordado no decorrer da análise. O que é importante é que mesmo com a dificuldade relatada, você conseguiu fazer funcionar =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

No geral, você escolheu nomes descritivos para suas funções de callback de listeners de evento. Parabéns!

Um erro comum que alguns alunos fazem é inserir a função com `preventDefault` no input, mas você inseriu a função com `preventDefault` corretamente no form, boa!

---

## Nomenclatura

Nas consts declaradas no topo do código, se achar que faz sentido, atente-se às seguintes observações. No intuito de melhorar a legibilidade do código, você pode renomear as costs `emptyListElement` e `feedbackElement` para algo como `emptyListMessage` e `feedbackMessage` Dessa forma, ao bater o olho no nome nessas consts, é mais específico e o que elas estão armazenando fica explícito.

```js
// antes
const feedbackElement = document.querySelector('.feedback')
const emptyListElement = document.querySelector('.empty-list-message')
```

```js
// depois
const feedbackMessage = document.querySelector('.feedback')
const emptyListMessage = document.querySelector('.empty-list-message')
```

Uma outra observação, a const `isEmptyTodoList` declarada dentro de `addTodo` pode ter seu nome reorganizado de forma que soe mais natural segundo as normas ortográficas da língua inglesa. O que você pode fazer aqui, se achar que é coerente, é trocar o nome de `isEmptyTodoList` para `todoListIsEmpty`.

```js
// antes
const isEmptyTodoList = todoList.children.length === 0
```

```js
// depois
const todoListIsEmpty = todoList.children.length === 0
```

Por `addForm` ser uma const e não uma função, pode considerar renomear o nome dessa const para algo como `formAddTodo`. Nomes que começam com verbos são recomendados apenas para funções, lembre-se disso, pode facilitar a escolha de nomes específicos para cada caso.

```js
// antes
const addForm = document.querySelector('.form-add-todo')
```

```js
// depois
const formAddTodo = document.querySelector('.form-add-todo')
```

Uma outra observação seria, se você achar que faz sentido, renomear o parâmetro `feedback` por `message` dentro da função `showFeedback`. A ideia aqui é fazer com que esse parâmetro seja mais específico no que está fazendo dentro do código.

```Js
// antes
const showFeedback = (feedback, type) => {
  // ...
}
```

```Js
// depois
const showFeedback = (message, type) => {
  // ...
}
```

Se você quiser deixar a função `preventDefault` com um nome mais específico no que está fazendo, você pode renomeá-la para algo como `preventSubmit`.

```js
// antes
const preventDefault = event => event.preventDefault()
```

```js
// depois
const preventSubmit = event => event.preventDefault()
```

Por fim, houve um erro de digitação na palavra "tarefa" dentro da invocação de `showFeedback` na função `deleteTodo`. Certifique-se de corrigí-lo posteriormente.

---

## Refatorações nas funções

Na função `addTodo`, como a const `input` está sendo usada apenas para obter o valor do input, ela pode ser eliminada e seu código colocado em `value`. Após isso, para que a const fique mais específica, vale a sugestão de renomeá-la para `inputValue`.

Uma outra observação é em `isValidTodo`, ela existe apenas para encapsular a expressão `todo.length >= 4`. Nesse contexto, talvez faça sentido eliminar a função e inserir a expressão diretamente como condição do if, já que não é uma expressão difícil de entender. Você pode deixar essa expressão mais simples, por exemplo, não é necessário usar o not (!) se invertermos o sinal, e se a mensagem indica que "a tarefa deve conter pelo menos 4 letras", também não é necessário um sinal de menor igual, pois se já houver quatro caracteres, o input já se torna válido de acordo com a mensagem.

Um pequeno refactoring que você pode fazer é na expressão `todoList.children.length === 0` que a const `todoListIsEmpty` armazena o resultado, ela pode ser executada apenas no momento em que é necessário executá-la. Assim você elimina um cálculo desnecessário caso a condição do primeiro if seja a executada. 

A função completamente refatorada ficaria assim:

```js
const addTodo = event => {
  event.preventDefault()

  const inputValue = event.target.add.value.trim()
  
  if (inputValue.length < 4) {
    showFeedback('A tarefa deve conter pelo menos 4 letras', 'error')
    return
  }

  const todoListIsEmpty = todoList.children.length === 0

  if (todoListIsEmpty) {
    toggleEmptyListMessage('hide')
  } 

  todoList.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete"></i>
    </li>
  `

  addForm.reset()
  showFeedback('Tarefa adicionada', 'success')
}
```

Se na sua percepção, a função `addTodo` estiver muito extensa, você pode optar por declarar uma função fora do escopo de `addTodo` para retornar o template HTML do to-do ao ser invocada. Isso seria feito dessa forma:

```js
const getTodoTemplate = inputValue => `
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete"></i>
  </li>`
```

```js
const addTodo = event => {
  event.preventDefault()

  // ...

  todoList.innerHTML += getTodoTemplate(inputValue)

  // ...
}
```

Na função `deleteTodo`, a condição do if que verifica se a lista de to-dos está vazia `todoList.children.length === 0` pode ser armazenada em uma const, da mesma forma que foi armazenada dentro da função `addTodo`. Esse processo se chama padronização, e pode ser bastante útil para facilitar o entendimento de conceitos iguais em partes diferentes do código. 

```js
const todoListIsEmpty = todoList.children.length === 0

if (todoListIsEmpty) {
  toggleEmptyListMessage('show')
}
```

Apesar de o trecho de código acima ter um padrão repetido, como são apenas duas ocorrências no mesmo código, acho que o custo de uma refatoração não compensaria o retorno.

Algo que pode fazer sentido, se você achar interessante, na invocação de `showFeedback`, se o usuário teve a intenção de deletar um item do to-do e a deleção aconteceu, a mensagem de confirmação pode ser do tipo 'success' ao invés de 'error'. Afinal de contas, o usuário conseguiu executar a ação que queria com sucesso.

```js
// antes
showFeedback('Tarefa removida', 'error')
```

```js
// depois
showFeedback('Tarefa removida', 'success')
```

Você também pode fazer uma refatoração na função `addTodo` e na `deleteTodo` por meio dos atributos data, em breve você chegará nas aulas sobre esses atributos. Mas para você ter uma ideia, você pode inserir o atributo data-todo na li do todo e colocar seu valor como o mesmo conteúdo da tag de `span`, depois adicionar um outro atributo data-trash no elemento html `i` da lixeira com novamente o mesmo conteúdo de `span`:

```html

<li class="..." data-todo="Fazer o jantar">
  <span>Fazer o jantar</span>
  <i class="..." data-trash="Fazer o jantar"></i>
</li>

<li class="..." data-todo="Estudar javascript">
  <span>Estudar javascript</span>
  <i class="..." data-trash="Estudar javascript"></i>
</li>

<li class="..." data-todo="Ler o homem que calculava">
  <span>Ler o homem que calculava</span>
  <i class="..." data-trash="Ler o homem que calculava"></i>
</li>

```

Depois, na função `getTodoTemplate`, você pode adicionar, dentro da template string, a nova marcação html atualizada com os atributos data. data-trash vai receber o conteúdo textual do todo, que no caso é o `inputValue`. Na li, o data-todo vai receber uma interpolação com o texto do todo do `inputValue`:

```js
const getTodoTemplate = inputValue => `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
  </li>`
```

Após inserir os atributos data acima na marcação html, na função `deleteTodo`, vamos usá-los também para fazer uma refatoração no lugar do `parentElement`. Não é bom usar `parentElement`, pois é um design de código que tende a ser frágil. Se futuramente a marcação html dessa aplicação mudar e o `parentElement` não for mais o elemento que você tinha em mente quando escreveu o código, o seu código quebra. O que não acontece quando você usa os atributos data. Por isso, você pode fazer o seguinte:

Você pode criar uma const `trashWasClicked` que vai receber o valor retornado pelo dataset que contém uma propriedade trash. Ou seja, quando a lixeira for clicada, o valor do atributo data-trash vai ser atribuida para a const `trashWasClicked`. Ficaria assim:

```js
const deleteTodo = event => {
  const trashWasClicked = event.target.dataset.trash

  if (!trashWasClicked) {
    return
  }

  const todo = document.querySelector(`[data-todo="${trashWasClicked}"]`)
  todo.remove()
  // ...
}
```

Ao clicar fora da lixeira, essa const vai armazenar `undefined`, que por ser um valor `falsy`, o if do early return vai ser executado. Quando a lixeira for clicada, `trashWasClicked` vai estar armazenando uma string preenchida, e uma string preenchida é um valor `truthy`, o if não será executado.

Você pode criar uma const `todo` que vai conter o todo, ou seja, a li que deve ser removida. Para selecionar essa li, você pode usar os atributos data. O data-todo tem o mesmo valor que data-trash, assim, você vai selecionar a li que contém o texto que `trashWasClicked` está armazenando, pois tanto data-todo quanto data-trash contém essa string que `trashWasClicked` está armazenando. Após a const `todo` receber a li que deve ser removida, você pode invocar o método `todo.remove()` para excluir a li escolhida do DOM.

Você irá aprender mais sobre os atributos data e suas particularidades nas próximas aulas do treinamento, mas deixei aqui também uma versão em escrito da explicação =)

Para a função `showFeedback`, ao ler o segundo argumento não fica tão claro o que ele significa. Você pode, se for de seu interesse, inserir um objeto em que as propriedades tenham o mesmo nome dos parâmetros nas invocações. O intuito aqui é ajudar na legibilidade, para isso, você também pode, na declaração da função, utilizar a abordagem de destructuring na declaração de parâmetro. Ficaria assim:

```Js
const showFeedback = ({ message, type }) => {
  // ...
}

// Invocações da função showFeedback com objetos sendo usados na invocação
showFeedback({ message: 'A tarefa deve conter pelo menos 4 letras', type: 'error' })
showFeedback({ message: 'Tarefa adicionada', type: 'success' })
showFeedback({ message: 'Tarefa removida', type: 'error' })
```

Partindo do princípio de, enquanto existirem apenas dois tipos de mensagem (error e success), uma alternativa seria substituir a propriedade `type` por uma propriedade que armazene um boolean. Essa propriedade poderia se chamar `isErrorMessage`, por exemplo. Feito esse ajuste, as consts `isSuccessFeedback` e `isErrorFeedback` podem ser removidas da função `showFeedback`, um if pode ser removido e os valores de `remove`, `add` e `innerHTML` podem ser inseridos dinamicamente através de um ternário como argumento para cada caso. Seria feito dessa forma:

```js
// antes
const showFeedback = ({ message, type }) => {
  const isSuccessFeedback = type === 'success'
  const isErrorFeedback = type === 'error'

  if (isErrorFeedback) {
    feedbackMessage.classList.remove('text-success')
    feedbackMessage.classList.add('text-danger')
    feedbackMessage.innerHTML = `${message} <i class="fas fa-times"></i>`
  }

  if (isSuccessFeedback) {
    feedbackMessage.classList.remove('text-danger')
    feedbackMessage.classList.add('text-success')
    feedbackMessage.innerHTML = `${message} <i class="fas fa-check"></i>`
  }

  clearFeedback()
}
```

```js
// depois
const showFeedback = ({ message, isErrorMessage }) => {

  feedbackMessage.classList.remove(isErrorMessage ? 'text-success' : 'text-danger')
  feedbackMessage.classList.add(isErrorMessage ? 'text-danger' : 'text-success')
  feedbackMessage.innerHTML = `${message} <i class="fas ${isErrorMessage ? "fa-times" : "fa-check"}"></i>`
  
  clearFeedback()
}
```

Na função `toggleEmptyListMessage`, a mesma lógica da refatoração de `showFeedback` pode ser aplicada aqui. Um objeto com uma propriedade `shouldShow` pode ser inserido como argumento. Ao invés de ternário, pode ser feito com apenas um if. Ficaria assim:

```js
// antes
const toggleEmptyListMessage = action => {
  const show = action === 'show'
  const hide = action === 'hide'

  if (show) emptyListMessage.classList.remove('d-none')
  if (hide) emptyListMessage.classList.add('d-none')
}
```

```js
// depois
const toggleEmptyListMessage = ({ shouldShow }) => {
  if (shouldShow) {
    emptyListMessage.classList.remove('d-none')
    return
  }

  emptyListMessage.classList.add('d-none')
}

toggleEmptyListMessage({ shouldShow: true})
```

Na função `clearFeedback`, você pode fazer algumas refatorações. Veja bem, quando uma função usa um argumento global, ela não precisa ter argumento/parâmetro. O código de `clearTextContent` pode ser colocado dentro de `clearFeedback` e esse código pode ser refatorado de forma que fique com apenas uma linha, ficaria assim:

```js
const clearFeedback = () => setTimeout(() => feedbackMessage.textContent = '', 1500)
```

Aqui vale uma observação, tenha como uma boa prática, declarar uma função antes de sua invocação. Assim, quem lê o código não precisa alterar o fluxo da leitura (de cima para baixo). Ou se você preferir, você pode mover o código inteiro de `clearFeedback` para `showFeedback`. 

```js
// Opção 1: Posicionada antes de showFeedback
const clearFeedback = () => setTimeout(() => feedbackMessage.textContent = '', 1500) 

const showFeedback = ({ message, isErrorMessage }) => {
  // ...

  clearFeedback()
}
```

```js
// Opção 2: Código de clearFeedback dentro de showFeedback
const showFeedback = ({ message, isErrorMessage }) => { 
  // ...

  setTimeout(() => feedbackMessage.textContent = '', 1500)
}
```

Para a função `searchTodo`, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

Vamos aproveitar parte do código que você escreveu e vamos inserir essa parte numa função `searchToDo`. Até o momento, temos uma const `todos` que contem as lis que representam os todos e a const `value` será renomeada para `inputValue`, um nome mais específico para a variável que recebe o valor escrito pelo usuário. Aqui, vale a sugestão de adicionar o método `trim()`, caso o usuário insira, acidentalmente, um espaço em branco no final, por exemplo.

```js
const searchToDo = event => {
  const inputValue = (event.target.value).toLowerCase().trim()
  const todos = Array.from(toDoList.children)
}
```

Feito isso, podemos percorrer cada um dos todos por meio do forEach, e após isso, podemos criar uma const `shouldBeVisible` que irá armazenar um boolean indicando se a li do todo deve ficar vísivel ou não dependendo do que o usuário escrever, depois disso, podemos manipular as classes dos to-dos considerando `shouldBeVisible`. Ficaria assim:

```js
const searchToDo = event => {
  const inputValue = (event.target.value).toLowerCase().trim()
  const todos = Array.from(toDoList.children)

  todos.forEach(todo => {
    const shouldBeVisible = (todo.textContent).toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  })

  // ...
}
```

Por fim, para dar mais legibilidade ao código e também deixar sua execução de forma explícita, podemos armazenar essa parte do código numa função própria chamada `filterTodos` e depois executá-la para cada um dos `todos` por meio de um forEach. Ficaria assim:

```js
const searchToDo = event => {
  const inputValue = event.target.value.toLowerCase().trim()
  const todos = Array.from(todoList.children)

  const filterTodos = todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  }
  
  todos.forEach(filterTodos)

  const isEmptyResult = validResults.length === 0

  if (isEmptyResult) {
    toggleEmptyListMessage('show')
    return
  }

  toggleEmptyListMessage('hide')
}
```

De forma adicional, `isEmptyResult` pode ser eliminada e ao invés de if, `some` e `contains` podem ser usados para definir o boolean que a propriedade `shouldShow` irá armazenar. Para isso, a ideia é declararmos uma const `searchHasResults` responsável para armazenar um boolean. O parâmetro `todo` do `some` pode ser usado para verificar se existe a classe `'d-flex'` no to-do. Essa verificação pode ser feita por meio do método `contains`. Caso `searchHasResults` seja false, a invocação de `toggleEmptyListMessage` será executada, e a mensagem de nenhuma tarefa encontrada será exibida na tela.

```js
const searchTodo = event => {
  const inputValue = event.target.value.toLowerCase().trim()
  const todos = Array.from(todoList.children)

  const filterTodos = todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  }
  
  todos.forEach(filterTodos)

  const searchHasResults = todos.some(todo => todo.classList.contains('d-flex'))

  toggleEmptyListMessage({ shouldShow: !searchHasResults })
}
```

---

## Omissão de blocos em `if`s

Ao longo do seu código houveram ifs com blocos omissos, foi uma observação que também ocorreu na análise passada, acredito que já a tenha visto, mas estou passando novamente apenas para que você relembre, pois é um assunto que merece atenção.

---

## Performance

Não sei se aconteceu em sua máquina, mas na primeira vez em que as mensagens que usam ícones do fontawesome eram exibidas, o ícone demorava a ser carregado. Existem algumas estratégias que a própria documentação do fontawesome fornece para melhorar a performance ao usar os ícones. Sugiro que você dê uma olhada nela: https://fontawesome.com/docs/web/dig-deeper/performance
 
Se tiver qualquer dúvida, é só perguntar =) 

---

O mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by fernandomk6** [comment]
Fizeram sim, bastante sentido. Irei prosseguir até o final do curso e quando concluir
voltarei em cada aplicação refatorando com base nos feedback e vou fazer um mini portfólio com
elas, muito obrigado.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
