### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5325]
### **Retornando valores e exercícios**

- **Até agora criamos `funções` que exibem algum valor no browser, mas nem sempre vamos querer fazer isso, existirá casos que vamos querer que a função retorne um valor para a gente.**

**Exemplo:**

```
const double = function (number) {
    const doubleResult = number * 2 // variáveis declaradas dentro da função só funcionam dentro da função.
    console.log(doubleResult)
}

double(3)

console.log(result) // resultado será 6 no console
```
- No código acima criamos uma função que multiplica um número e mostra o resultado no console do browser.
- Mas quando tentamos usar o a variável criada dentro da função do lado de fora do bloco da função isso retorna um erro.

> ### **Motivo: variáveis declaradas dentro da função só funcionam dentro da função.**

---------------------------------------------------------------------------------------------------------------------------------------------

### **Mas Existe uma forma de obtermos o valor fora do bloco da função?**
**Sim, existe uma forma de obtermos o valor fora do bloco da função. Fazendo a função retornar o valor, usando o `RETURN`**

**Exemplo**: 

```
const double = function (number) {
    const doubleResult = number * 2 // variáveis declaradas dentro da função só funcionam dentro da função.
    return doubleResult // Isso vai retornar o valor da váriavél "doubleResult"
}

const result = double(3) // Armazenando o chamado da função que armazena o resultado do RETURN

// console.log(result) // resultado será 6 no console
```
- **Isso vai retornar o valor da váriavél "doubleResult"**
- **E logo em seguida armazenar o chamado da função que armazena o resultado do RETURN**

### **Forma de retornar sem precisar de uma variável**

```
const double = function (number) {
    return doubleResult = number * 2 // Usa o return sem precisar de armazenar na vaviável
}

const result = double(3) // Armazenando o chamado da função que armazena o resultado do RETURN

const showResult = function (value) {
    return `O resultado é: ${value}`
}

console.log(showResult(result))
```

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
