### ISSUE TITLE
Exercício 5 pasta exercícios 06

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5330]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/781540

### Descreva a dúvida

 O array "crazyArray" (abaixo) possui 3 tipos de dados: numbers, booleans  e strings;
  - Considerando este array, substitua os "X" da frase abaixo pelas informações corretas;
  - Gere essas informações à partir de um for loop;
  - Exiba a frase no console.

  "O crazyArray tem X booleans, X números e X strings."

```javascript
const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false]

let amountBoolean = 0
let amountNumber = 0
let amountString = 0

for (let i = 0; i < crazyArray.length; i++) {
  const typeOfItem = typeof crazyArray[i]
  const isItemABoolean = typeOfItem === 'boolean'
  const isItemANumber = typeOfItem === 'number' 

  if ( isItemABoolean ) {
    amountBoolean ++
  } else if ( isItemANumber ) {
    amountNumber ++
  } else {
    amountString ++
  }
}

console.log(`O crazyArray tem ${amountBoolean} booleans, ${amountNumber} números e ${amountString} strings.`)
```

Minha dúvida está no final onde fica o else:
Eu gostaria de entender o motivo de não precisar declarar no else a mesma coisa que foi declarado em if e else if. Como que o JS conseguiu deduzir que amountString tem x strings? Afinal nem declaramos outra const como feito com isItemANumber e isItemABoolean.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

> ### Eu gostaria de entender o motivo de não precisar declarar no else a mesma coisa que foi declarado em if e else if

`if`, `else if` e `else` são excludentes. Ou seja, apenas um dos 3 é executado.

Isso significa que, se na primeira execução do loop por exemplo, as condições de `if` e `else if` resultam em false, o else será executado. O `else` é a última opção. Se nenhum `if` ou `else if` acima dele é executado, ele executa o código dentro do bloco dele =)

O `else` do exemplo que vc postou contém apenas o incremento da let `amountString`. Observe que o array `crazyArray` contém apenas 3 tipos de dado: string, boolean e number.

Como o array contém apenas string, boolean e number, se o item que está sendo verificado não é um number e não é um boolean, ele só pode ser uma string =)

Por isso não é preciso declarar uma let `isItemAString`. O `else` é executado quando o item não é boolean ou number. E já que string é o terceiro e último tipo de dado do array, basta incrementar `amountString`

Sacou a ideia? =)

**Comment by Ale557333** [comment]
> Olá @Ale557333!
> 
> > ### Eu gostaria de entender o motivo de não precisar declarar no else a mesma coisa que foi declarado em if e else if
> 
> `if`, `else if` e `else` são excludentes. Ou seja, apenas um dos 3 é executado.
> 
> Isso significa que, se na primeira execução do loop por exemplo, as condições de `if` e `else if` resultam em false, o else será executado. O `else` é a última opção. Se nenhum `if` ou `else if` acima dele é executado, ele executa o código dentro do bloco dele =)
> 
> O `else` do exemplo que vc postou contém apenas o incremento da let `amountString`. Observe que o array `crazyArray` contém apenas 3 tipos de dado: string, boolean e number.
> 
> Como o array contém apenas string, boolean e number, se o item que está sendo verificado não é um number e não é um boolean, ele só pode ser uma string =)
> 
> Por isso não é preciso declarar uma let `isItemAString`. O `else` é executado quando o item não é boolean ou number. E já que string é o terceiro e último tipo de dado do array, basta incrementar `amountString`
> 
> Sacou a ideia? =)

Saqui sim Roger! Muito legal mesmo!! Obrigado!

**Comment by Ale557333** [comment]
> Saquei sim Roger! Muito legal mesmo!! Obrigado!

**Comment by Roger-Melo** [comment]
Massa! Se surgir alguma dúvida, é só abrir uma nova issue =)
