### ISSUE TITLE
Etapa 02, nome do vídeo: Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by MarcusViniciusTavaresRangel** [roger-melo-treinamentos/curso-de-js-roger-melo#534]
Olá professor! Fiz um teste aqui e o resultado true do exercício 6 é apenas na última iteração do loop. Se pusermos o console.log() dentro do for(), haverá iterações na mesma quantidade de elementos do array numbers. Porque não há maneira de somar imediatamente os itens do array com o loop for(), é isso mesmo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcus Vinicius.

Vou mostrar um exemplo com os mesmos princípios mas com um escopo menor. 

No código abaixo,

```javascript
const numbers = [1, 2, 3]

let sum = 0

for (let i = 0; i < numbers.length; i++) {
  sum += numbers[i]
  console.log(sum === 6)
}
```

`console.log(sum === 6)` exibe `true` apenas na última execução (3ª) por que é apenas na última execução que `sum` armazena `6`.

Apenas para eu não pecar por falta de clareza, observe a tabela abaixo. Ela contém um panorama geral do que está acontecendo no código acima:

Execuções do for | valor que `sum` recebeu | boolean exibido no console
:-- | :-: | :-:
1ª execução | 1 | `false` (por que 1 não é igual a 6)
2ª execução | 3 | `false` (por que 3 não é igual a 6)
3ª execução | 6 | `true` (por que 6 é igual a 6)

Sacou por que é só na última execução do `for` que `true` é exibido?

---

> Porque não há maneira de somar imediatamente os itens do array com o loop for(), é isso mesmo?

Não há. Por isso a cada execução do loop é necessário armazenar o valor acumulado das somas em uma variável externa (`sum`).

A medida em que você for avançando no treinamento, verá ferramentas mais eficientes e específicas que o `for`. Inclusive um método que irá possibilitar a soma dos números de um array sem precisar declarar variáveis externas =)

Ficou mais claro @MarcusViniciusTavaresRangel?

**Comment by MarcusViniciusTavaresRangel** [comment]
Beleza! Era o que eu pensava, mas você elaborou melhor. Muito obrigado pelos esclarecimentos.

**Comment by Roger-Melo** [comment]
Show @MarcusViniciusTavaresRangel! No que precisar, é só abrir uma nova issue =)
