### ISSUE TITLE
Resumo da Aula setInterval() e animação da pontuação - Aula 02-03 da etapa 07

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5345]
- setTimeout( )
E um metodo utilizado para executar uma unica vez uma funcao de callback apos um determinado tempo em milessegundo estabelecido por parametro.
Ex: 
      setTimeout(( )=>{ }, 1000)

- setInterval( )
E um metedo semelhante ao setTimeout, porem ao inves de executar o callback uma unica vez ele executara repetidamente com o intervalo estabelecido em milissegundo por parametro.
Ex:
     setInterval(( )=>{ }, 1000)

E para ENCERRAR o metodo setInterval( ) e utilizado outro metodo chamado clearInterval( ) que deve receber por parametro a referencia do setInterval( ) desejado.

**Comment by Roger-Melo** [comment]
Excelente @YukOnRails, rumo à fluência! 🎯
