### ISSUE TITLE
Resumo da Aula Arrow functions - Aula 02-02 da etapa 03

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#535]
*Arrow Functions* foram implementadas em versões mais recentes do JavaScript, e elas são uma forma mais curta e concisa de escrever uma função. A sintaxe de uma *arrow function* utilizando um exemplo de uma *function expression*, é declarar uma constante que receberá um parênteses com ou sem parâmetros, seguido de um sinal de igual com um sinal de maior que (=>), seguido de abertura e fechamento do bloco de código utilizado chaves. Caso essa *arrow function* receba apenas um parâmetro e não tenha um valor *default*, podemos omitir o uso dos parênteses. E caso essa função tenha apenas uma linha em seu bloco de código retornando um valor, podemos eliminar a palavra *return* e as chaves, pois o valor será retornado implicitamente. Vamos ver na prática um exemplo de uma *function expression* com uma função tradicional e em seguida a mesma função utilizando *arrow function*.

```jsx
const double = function (number) {
	return number * 2;
}

const result = double(7);

console.log(`O resultado é ${result}`);
// O resultado é 14
```

Agora utilizando a *arrow function*:

```jsx
const double = number => number * 2;

const result = double(7);

console.log(`O resultado é ${result}`);
// O resultado é 14
```

O retorno de uma arrow function poderia ser uma string, um number, um array, ou até uma expressão. Uma expressão em JavaScript é qualquer pedaço de código que resulta em um valor, como por exemplo `number * 2;`. O que não é possível de se retornar por não ser um valor seria um bloco *if* ou um bloco *switch*, pois eles são blocos de códigos condicionais, eles não resultam valor, logo não poderiam ser retornados em funções.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas! 👊🏻
