### ISSUE TITLE
Dúvida sobre etapa final

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#5351]
### Etapa da aula

15

### Nome da aula

Ajustando a função onSnapshot

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/5447356

### Descreva a dúvida

Bom dia, professor!!!

Ontem estava assistindo à última aula (03-31 Etapa 15), e quando ela terminou eu fiquei com uma sensação de que não tinha terminado. 
Na aula 03-13 é lançado um desafio (implementar uma feature nesta aplicação: a autenticação do Firebase) e nas aulas seguintes você mostra como implementar.
Um dos requisitos do desafio era mostrar as informações da conta do usuário no card "Detalhes da Conta", e essa implementação não foi mostrada como fazer (eu consegui fazer, mas não sei se foi da melhor maneira!).
Não houve uma aula mostrando como refatorar o código como você sempre mostra após os desafios/projetos.
No final da aula não há um "O curso termina aqui, adeus!" ou coisa assim, dando a impressão de que haverá uma próxima aula.

A aula 03-31 é realmente o final da jornada ou você ainda está atualizando o conteúdo dessa etapa?

Abç!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado. 

As aulas finais dessa etapa ainda estão sendo produzidas =)
