### ISSUE TITLE
Resumo da Aula Operadores lógicos (e e ou) - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by gustavo-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#5356]
### Operadores logicos ( &&, ||)

Esses operadores são usados desde as portas lógicas para comparação de mais
de uma condição ao mesmo tempo, retornando apenas uma resposta booleana para
essa condição, cada operador serve para uma coisa, o && só retorna ``` true ``` quando
as duas condições são verdadeiras, já o operador || (ou) se qualquer umas das condições
forem verdadeiras o resultado será ``` true ``` fazendo assim a execução do código acontecer
Os operadores podem ser usados em conjunto também

#### ex:

```js
let age = 30
let minhaNamorada = 31

let soma = age + minhaNamorada

if(soma > 50 && age < 15 ){
	console.log('sua namorada é velha demais pra vc')
}

if(soma < 50 || minhaNamorada > 19) {
	console.log('esse namoro ta ok')
}

if((soma < 60 && minhaNamorada > 19) || (age > 20  || minhaNamorada > 19) {
	cosole.log('usando dois operadores logicos')
}

```

**Comment by Roger-Melo** [comment]
Excelente @gustavo-viana, rumo à fluência! 🎯
