### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5357]
### **callbacks**
- **São funções que a gente passa como argumento de invocações de outras funções ou métodos.**
- **Podemos inserir uma função no argumento de outra função, isso se chama função de callbacks ou callbacks.**

```
const myFunc = callback => {
    const value = 77

    callback(value)
}

myFunc(number => {
    console.log(number)
})
```

### **forEach**

- **O forEach vai iterar por todo o array do mesmo jeito que um for, mas de um forma elegante.**

- **ForEach pode receber 3 parâmetros:**
1. `Variável Qualquer` = Vai receber a valor do item atual.
2. `index `= Vai receber o index do item atual.
3.  `Array `= Vai receber o array.

```
const socialNetworks = ['youtube', 'instagram', 'twitter', 'facebook']

socialNetworks.forEach((index, socialNetwork, array) => {
    console.log(index, socialNetwork, array)
})
```

### **Outra forma de executar o forEach**

```
const logArrayInfo = (socialNetwork, index, array) => {
    console.log(index, socialNetwork, array)
}

socialNetworks.forEach(logArrayInfo)
```

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos , rumo à fluência! 🎯
