### ISSUE TITLE
Resumo da Aula Uma introdução ao Bootstrap - Aula 01-02 da etapa 07

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5359]
O Boostrap é uma biblioteca de componentes front-end, componentes no bootstrap são resumidamente elementos e partes da interface do usuário que podem ser reutilizadas, eles nos ajudam com o desing dos nossos projetos.
Quando usamos bootstrap não precisamos nos preocupar em escrever vários estilos CSS, permitindo um foco maior no JS. O bootstrap é uma biblioteca CSS e JS mas por hora usaremos apenas a parte de CSS dele.
Uma das formas mais rápidas para se usar o bootstrap é a através da CDN dele, CDN significa content delivery network, ou rede de distribuição de conteúdo em português, em que um grupo de servidores próximos a nossa localização disponibilizam um certo conteúdo para baixarmos em nosso browser.
O conteúdo que iremos baixar no carregamento de nossa aplicação e o CSS do bootstrap, para usarmos ele precisamos apenas copiar uma tag especifica para dentro do head, então agora poderemos usar na nossa marcação HTML as classes de CSS disponíveis no bootstrap.

```html
<!DOCTYPE html>
<html lang="pt=br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Aplicacao Quiz, Etapa 7</title>
</head>
<body>
    
    <div class="card" style="width: 18rem;">
        
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>

    <script src="./app.js"></script>
</body>
</html>
```

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
