### ISSUE TITLE
Resumo da Aula Trabalhando com JSON (JavaScript Object Notation) - Aula 03-04 da etapa 11

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#537]
JSON é um formato utilizado durante a troca de dados entre o browser e um servidor. 

Um JSON é uma *string* que se parece com um *objeto* JavaScript. Ele é uma *string* porque os dados trocados entre o browser e o servidor devem estar em formato de *string*.

Para acessarmos os dados que um JSON armazena devemos converter este JSON em um *objeto* JavaScript por meio do método **`*JSON.parse()*`**- o `***JSON***` é um objeto embutido na linguagem.

O que diferencia um objeto JSON de um objeto JavaScript é que o nome das propriedades devem estar envolvidos por aspas duplas, o mesmo serve para valores de propriedades que são *strings*.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! 👊🏻
