### ISSUE TITLE
Resumo da Aula Tratando erros com try/catch - Aula 06-04 da etapa 11

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#5371]
# Tratando erros com try/catch - Aula 06-04 - Resumo

## O que é ***try/catch***?

É uma cláusula que tenta executar um código. É um bloco que tem uma tentativa. Se essa tentativa não der certo, uma mensagem de erro é lançada.

Exemplo do uso do ***try/catch:***

![imagem 1](https://res.cloudinary.com/ananopaisdojavascript/image/upload/v1665008153/aula-6-etapa-11/Screen_Shot_2022-10-05_at_18.55.41_utf4jq.png)

Exemplo de uso personalizado do ***try/catch***:

![imagem 2](https://res.cloudinary.com/ananopaisdojavascript/image/upload/v1665008153/aula-6-etapa-11/Screen_Shot_2022-10-05_at_19.08.34_nxkdka.png)

**Comment by Roger-Melo** [comment]
Excelente @ananopaisdojavascript, rumo à fluência! 🎯
