### ISSUE TITLE
Resumo da AAula 01-03 da etapa 03

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5376]
**Function declaration, function expression e hoisting** 

Funções são blocos que podem ser invocadas. Ela vai executar uma tarefa seguindo um conjunto de instruções.

Essa forma  de se criar uma função  é a Function declaration:

![1](https://user-images.githubusercontent.com/71138743/197294084-3c5d2154-83a1-4f4a-a5ed-a9af44e013c1.png)

Ela pode ser invocada várias vezes:

![2](https://user-images.githubusercontent.com/71138743/197294102-26686dc3-374d-42ae-a8f0-6721e1adc4d9.png)

Function expression:

Atribuir a função a uma variável.
Para invocar é a mesma coisa:

![3](https://user-images.githubusercontent.com/71138743/197294179-fade91c5-3a2d-47a2-82f2-66b89f863977.png)

E também pode ser invocada várias vezes:

![4](https://user-images.githubusercontent.com/71138743/197294239-e822eeef-949c-497d-a9be-92765704017d.png)

Não existe diferença entre as duas, mas possui um detalhe:

Hoisting:  Pode ser traduzido como içamento (puxar pra cima).
Se a Function declaration estiver em qualquer lugar do código que não seja no topo do arquivo, por baixo dos panos o JS puxará a criação para o topo do arquivo, coisa que não acotencerá com a Function Expression:

Mesmo alterando a posição da function declaration para baixo, até mesmo ela ficando após suas declarações sayHi( ), ela irá continuar sendo invocada normalmente:

![5](https://user-images.githubusercontent.com/71138743/197294270-7318a967-ae9f-4a84-b756-f37445bbfb16.png)

Seria normal pensar que aconteceria um erro, pois sabemos que o JS lê o código de cima para baixo, mas nesse caso não acontecerá o erro, pois ele agirá por debaixo dos panos.

Isso não funcionará para Function Expressions, pois se fizermos a mesma coisa, a função não irá ser içada nem menos invocada.
Na linha 9 irá acusar o erro no console.

![6](https://user-images.githubusercontent.com/71138743/197294303-0841c383-ec80-4cb4-8aad-7d531a8f625c.png)

Para evitar erros a melhor coisa é declarar as funções no topo do código.

**Comment by Roger-Melo** [comment]
Show @Ale557333 . Vamo que vamo, rumo à fluência! 🙌
