### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5380]
Operadores lógicos - "OU" || e "E" && são utilizados nas verificações com "if" para verificar combinações com condições diferentes. Obs: não é só porque pode utilizar esses operadores lógicos que devemos utiliza-los pois o código ficará muito complicado de ser ler.

**Comment by Roger-Melo** [comment]
Show @Dieison37 . Vamo que vamo, rumo à fluência! 🙌
