### ISSUE TITLE
Resumo da Aula O método reduce - Aula 01-04 da etapa 08

### ISSUE THREAD

**Issue by silvasouzaadriano** [roger-melo-treinamentos/curso-de-js-roger-melo#5390]
De forma similar ao map e ao filter, ele também recebe uma função como argumento e executa essa função para cada item do array.
	Você o utiliza quando baseado no array original, for necessário reduzir o array a algum outro tipo de dado.
	E esse tipo de dado por ser: um objeto literal, uma string, um número ou até mesmo um novo array
	Ao contrário dos métodos map e filter, o reduce tem poder e versatilidade para gerar um output que não necessáriamente será um array.
	
	Nota1: O segundo argumento do reduce é opcional e é usado somente na primeira vez que a função é executada.
	Contudo, é uma boa prática declará-lo pois ele será uma representação explicíta e visual do tipo de dado que o reduce retornará.
	
	Nota2: A função sempre precisa retornar um valor
	
	Nota3: O parâmetro accumulator sempre receberá esse valor, pois ele serve para acumular o valor a cada execução da função
	e lembrar desse valor a cada execução
	
	Note4: Quando uma arrow function somente está retornando uma expressão, podemos usar a sintasse "concise body" que tem um retorno implícito
	
	Nota5: O ternário é o único operador do JS que recebe três operandos: 
	
		1) Condição a ser testada
		2) Resultado se condição verdadeira
		3) Resultado se condição falsa
		
			O ternário também é conhecido como um atalho para um IF

    IMPORTANTE1: Ele não deve ser usado para gerar efeitos colaterais (side effect).
	Um efeito colateral é qualquer mudança de estado em uma aplicação que pode ser percebida do lado de fora da função,
	e que não é um valor retornado pela função.
	
	IMPORTANTE2: Estado numa aplicação é tudo que armazena um valor. Existem vários subtipos de estado, como por exemplo o
	estado compartilhado.
	
	IMPORTANTE3: Um estado compartilhado é qualquer variável, objeto ou espaço na memória que existe em um escopo compartilhado, 
	ou existe como propriedade de um objeto que é passada entre escopos
	
	
	Tipos de efeitos colaterais:
	
		1. Modificar uma variável ou propriedade que está do lado de fora da função
		2. Logar no console
		3. Manipular o DOM
		4. Desencadear qualquer processo do lado de fora da função
		5. Invocar outra função que produza outro efeito colateral

```js
	// Primeiro exemplo - Retornar a soma de todos os números do array original

	const numbers = [1, 2, 3]

	const sumResult = numbers.reduce((accumulator, item) => accumulator + item, 0)

	console.log(sumResult, numbers)



	// Segundo exemplo - Imagine um array de objetos que contenha a pontuanção de cada gamer numa determinada fase do jogo
	

	const phaseScores = [
	  { name: 'Vinicius Costa', score: 337 },
	  { name: 'Adriano Souza', score: 43 },
	  { name: 'Alfredo Braga', score: 234 },
	  { name: 'Pedro H. Silva', score: 261 },
	  { name: 'Ana Paula Rocha', score: 491 },
	  { name: 'Vinicius Costa', score: 167 },
	  { name: 'Adriano Souza', score: 137 },
	  { name: 'Alfredo Braga', score: 135 },
	  { name: 'Ana Paula Rocha', score: 359 },
	  { name: 'Pedro H. Silva', score: 133 }
	]

	// O objetivo aqui será retornar a pontuação total do gamer Adriano Souza

	const adrianoSouzaScore = phaseScores.reduce((accumulator, phaseScore) => {
	  if (phaseScore.name === 'Ariano Souza') {
		accumulator += phaseScore.score
	  }

	  return accumulator
	}, 0)

	console.log(adrianoSouzaScore)
```

**Comment by Roger-Melo** [comment]
Boa @silvasouzaadriano! Rumo a fluência!
