### ISSUE TITLE
Etapa 07 - Aplicação: Quiz Interativo - Aula 01 - Exercício 19

### ISSUE THREAD

**Issue by DavidLSousa** [roger-melo-treinamentos/curso-de-js-roger-melo#54]
https://github.com/DavidLSousa/Exercicio19-Quiz.git

Duvidas e dificuldades:
Levei um certo tempo para entender como usar o bootstrap, a primeira vista imaginei que seria somente copiar e colar trechos de HTML inteiros e editar, mas vi que é possivel ir apenas add novas classes nos elementos, mas ainda n sei estruturar muito bem, mas já é um processo muito mais simples que o CSS no zero;

Tive problemas com o add os inputs do usuário, tentei fazer de uma maneira mais geral, que permitisse add um numero indeterminado de perguntas e o código ainda funcionasse sem precisar reescrever partes, mas não consegui nada muito prático

Em escolher os nomes das variáveis;

Saber se seria ou não bom refatorar o código e add algumas funções, mas as vezes acho que acaba ficando mais dificil de enxergar do que antes de refatorar, quando o código é pequeno assim;

Menores dificuldades:
Com a linha lógica a seguir;

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi David. Parabéns pela aplicação =D

> Levei um certo tempo para entender como usar o bootstrap, a primeira vista imaginei que seria somente copiar e colar trechos de HTML inteiros e editar, mas vi que é possivel ir apenas add novas classes nos elementos, mas ainda n sei estruturar muito bem, mas já é um processo muito mais simples que o CSS no zero;

Exatamente. No começo exige mais investimento de tempo na documentação, mas depois que você pega o jeito, estilizar as aplicações fica mais simples.

> Tive problemas com o add os inputs do usuário, tentei fazer de uma maneira mais geral, que permitisse add um numero indeterminado de perguntas e o código ainda funcionasse sem precisar reescrever partes, mas não consegui nada muito prático

Cuidado ao tentar expandir o escopo de features da aplicação. Isso pode isso pode gerar frustração, caso não consiga implementá-las.

Mais à frente, quando você estiver em partes mais avançadas no treinamento, estará mais confiante na linguagem e pode lapidar as aplicações que construirmos.

> Em escolher os nomes das variáveis;

Mesmo programadores mais experientes podem ter dificuldades em nomear bem uma variável. Não se preocupe tanto com isso agora. Com a prática, você começará a perceber padrões de nomes que fazem sentido.

> Saber se seria ou não bom refatorar o código e add algumas funções, mas as vezes acho que acaba ficando mais dificil de enxergar do que antes de refatorar, quando o código é pequeno assim;

Exatamente. O ideal é primeiro fazer funcionar e depois, se necessário, refatorar.

Nas aulas seguintes, mostrarei alguns refactorings possíveis no código desta aplicação.

---

Evite selecionar elementos "navegando pelo DOM" como no código abaixo.

```javascript
const scoreDisplay = outputScore.parentElement.parentElement
```

Essa é uma forma frágil de selecionar um elemento. Se amanhã o elemento mudar de posição, seu código JS quebrará. Prefira apenas identificar o elemento a ser selecionado (com uma classe, por exemplo) e armazenar a referência dele na `const`.

No mais, é isso meu caro. Parabéns pelo esforço! 👏👏👏

**Comment by DavidLSousa** [comment]
```
const scoreDisplay = outputScore.parentElement.parentElement
```

Eu tava fazendo um teste, ate substitui isso depois, não lembrei de atualizar no github

Obrg Prof @Roger-Melo

**Comment by Roger-Melo** [comment]
Tranquilo David. No que precisar, pode contar comigo para te ajudar a chegar na fluência.

Vou fechar a issue mas quando surgirem dúvidas, é só abrir uma nova =)
