### ISSUE TITLE
Javascript assíncrono: Await

### ISSUE THREAD

**Issue by fernandomk6** [roger-melo-treinamentos/curso-de-js-roger-melo#5407]
### Etapa da aula

11

### Nome da aula

aula-05-04-async-await

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1338555

### Descreva a dúvida

Bom dia, gostaria de saber como funciona a ordem de execução do
seguinte código abaixo. 

Mais especificamente, como o javascript lida com o código abaixo do await.

Esse é o código que eu gostaria de saber como funciona a ordem de execução.

```js
const asyncFunction = async () => {
  const URL = `https://api.github.com/users/fernandomk6`

  const response = await fetch(URL)
  console.log('Apos o primeiro await')
  
  const user = await response.json()
  console.log('Apos o segundo await')

  return user
}

console.log('inicio')
console.log(
  asyncFunction().then(console.log)
)
console.log('fim')
```

O resultado no console é o seguinte:

```
inicio
Promise {<pending>}
fim
Apos o primeiro await
 Apos o segundo await
{login: 'fernandomk6', id: 80510651, node_id: …}
```

Só para alinhar os conhecimentos eu sei que uma função async ela 
tem o seu retorno sincrono, ou seja, é por isso que ela retorna a promise pending.

Então eu acredito que ocorre o seguinte, 

Para ser mais claro com relação a duvida, é o seguinte, a function async é executada e retorna uma promise pending,
isso de forma sincrona. Porém o console.log('apos o await') não é. Isso significa que, todo código abaixo de
um await, será executado somente depois? É um pouco estranho para mim pois, códigos assincronos
geralmente recebem um callback (listeners, setTimes...), já o código abaixo do await não é um callback. 

Faz sentido pensar que, todo o código abaixo de um await, "equivale" a um callback passado como argumento
de um then?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @fernandomk6.

> ## Como funciona a ordem de execução do seguinte código abaixo, mais especificamente, como o javascript lida com o código abaixo do await

Antes de começar a responder, só vou confirmar que você está no caminho certo! Vou te explicar de uma maneira mais detalhada o que está acontecendo.

Quando o await está aguardando uma promise, a expressão que é composta pelo await e pelo método que vai aguardar a promise, resulta no valor desencapsulado da promise.

Numa função assíncrona, assim como no código que você postou, todo o código abaixo do await será executado assim que a promise que o fetch retorna for resolvida. Quando o await está aguardando uma promise, a expressão que é composta pelo await e pelo método que vai aguardar a promise, resulta no valor desencapsulado da promise. Isto é, enquanto essa promise não for resolvida, nenhum código abaixo da linha na qual o await foi utilizado será executado. Esse comportamento é observado na linha comentada abaixo:

```js
const asyncFunction = async () => {
  const URL = `https://api.github.com/users/fernandomk6`

  const response = await fetch(URL) // O código abaixo dessa linha ficará "pausado" até a promise ser resolvida
  console.log('Apos o primeiro await')
  
  const user = await response.json()
  console.log('Apos o segundo await')

  return user
}
```

> ## Só para alinhar os conhecimentos eu sei que uma função async ela tem o seu retorno sincrono, ou seja, é por isso que ela retorna a promise pending.

O resultado das operações assíncronas só vão ser obtidos após todas as operações síncronas do código serem executadas. No exemplo abaixo, os dois códigos síncronos, os console.log, são executados primeiro, mesmo quando o tempo de um código assíncrono é setado como 0.

```Js
console.log(1)

setTimeout(() => console.log('setTimeout'), 0)

console.log(2)
```

> ##  Isso significa que, todo código abaixo de um await, será executado somente depois?

Sim!! Tendo como exemplo o que foi apresentado no console, ambos os console.log são executados somente depois que a Promise que o fetch retorna é resolvida, e eles aparecem primeiro no console pois `user` é retornado apenas na última linha da função. `asyncFunction`.

> ## Faz sentido pensar que, todo o código abaixo de um await, "equivale" a um callback passado como argumento de um then?

É um raciocínio similar mesmo, no caso do await junto do fetch, por exemplo, o fetch vai retornar uma promise e a expresão com o await vai resultar na promise resolvida. O await serve para indicar que ele está aguardando que a promise seja resolvida. Já o then será executado quando a promise for resulvida. Então meio que é possível estabelecer um sentido semelhante em relação ao resultado final.

---

Respondi a dúvida?

**Comment by fernandomk6** [comment]
Mais ou menos, é um conceito complexo, vou ter que estudar um pouco mais.

No exemplo do setTimeout, ele recebe um callback que é executado quando algo estiver pronto,
isso é tranquilo. Já o async function, é como se mesma função fosse chamada (ou continuasse) 2 ou mais vezes. Uma vez
para cada await.

Por exemplo.

```js
const asyncFunction = async () => {
  const URL = `https://api.github.com/users/fernandomk6`

  const response = await fetch(URL) // O código abaixo dessa linha ficará "pausado" até a promise ser resolvida
  console.log('Apos o primeiro await')
  
  const user = await response.json()
  console.log('Apos o segundo await')

  return user
}

console.log(asyncFunction()) // primeira chamada, imprime promise pending. Até aqui tranquilo.

Porém depois disso a função volta a ser executada novamente. Ela continua de onde parou.
Ela continua a partir da resolução da expressão do await. Isso para mim ainda é difícil de visualizar na call stack.

Eu consigo visualizar um callback sendo armazenado em algum lugal para ser 
executado depois.  Mas continuar de onde parou é difícil visualizar.

Eu sei que o await usa um yield por baixo dos panos.
É como se o async function fosse um generator, e cada await, fosse uma pausa do yield,
Porém sem precisar chamar a função novamente.

Tá correto essa linha de raciocinio?

Na verdade o que eu estaria precisando mesmo seria apenas visualizar a ordem de 
execução (simular a callstack com o nome das funções). 

Promises foi tranquilo, mas o await deu um nó na cabeça.

Eu sei que é um assunto mais complicado, eu consigo lidar com await bem, mas me incomoda
por que não sei exatamente como funciona.

Eu conheço um pouco de event loop e callstack e tento visualizar o await nesses meios.

```

**Comment by Roger-Melo** [comment]
Olá @fernandomk6!

Não tem muito mistério, se vc entende promises, async/await não é complicado =D

> ### Já o async function, é como se mesma função fosse chamada (ou continuasse) 2 ou mais vezes

Isso não existe =)

`asyncFunction` é executada uma única vez.

O fato de a invocação dela retornar uma promise pendente **não significa** que a função é executada mais de uma vez.

Se vc executar qualquer função async, independente do conteúdo que ela tenha, ela irá retornar uma promise:

```javascript
const asyncFunction = async () => {}

console.log(asyncFunction()) // Promise {<fulfilled>: undefined}
```

Sobre `Promise {<pending>}` ser exibida no console no seu exemplo, isso não significa que o retorno da função é síncrono. Significa apenas que o state da promise foi exibido. Uma promise é um objeto que representa o sucesso ou a falha de uma operação assíncrona.

A função `asyncFunction` no exemplo que vc postou contém 2 operações assíncronas, por isso [o state da promise é pending](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#description).

---

> ### Eu sei que o await usa um yield por baixo dos panos

Não faz sentido se preocupar com isso. 

Se vc buscar saber cada engrenagem interna da linguagem nesse momento, ficará desnecessariamente confuso.

Nem mesmo a página do `await` na documentação fala sobre yield: 

- [await - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)

---

> ### Eu conheço um pouco de event loop e callstack e tento visualizar o await nesses meios.

Dá uma olhada no link abaixo =)

- [⭐️🎀 JavaScript Visualized: Promises & Async/Await](https://dev.to/lydiahallie/javascript-visualized-promises-async-await-5gke#asyncawait)

**Comment by fernandomk6** [comment]
Obrigado pelas resposta vou devorar essa página e fazer mais testes para 
fixar bem o conteúdo. Obrigado.
