### ISSUE TITLE
Dúvidas sobre legibilidade.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5409]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/781540

### Descreva a dúvida

Oi Roger tudo bem ?
Rolou uma dúvida quando estava acompanhado a correção dos exercícios, da forma que fiz deu o mesmo resultado, mas bem diferente da forma que você realizou a correção, mas quando você foi legitimar o código para facilitar a leitura e entendimento e com certeza fica bem melhor mesmo, não entendi a forma de como interpretar os detalhes de cada parte do código que você modificou, creio que é porque ainda não tenho uma familiaridade com a linguagem em geral, mas não tem uma forma mais fácil de começar a entender em como inserir a legibilidade como no meu caso que ainda não tenho um conhecimento mais aprofundado na linguagem ?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Dieison37

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## mas não tem uma forma mais fácil de começar a entender em como inserir a legibilidade como no meu caso que ainda não tenho um conhecimento mais aprofundado na linguagem

É normal ter essas preocupações quando se está aprendendo no início, é um indicativo de que vc quer fazer com excelência.

Há um princípio que pode te ajudar quando essas preocupações vierem, que é o seguinte: Feito é melhor que perfeito.

Isso por que podem haver vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Certifique-se também de entender como é feita a lógica do código mostrado na correção, isso é importante. Com a prática, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, entende? =)

Sobre entender onde o código pode ficar mais legível e aprimorá-lo, essa é uma das habilidades que você irá melhorar conforme for praticando. E vc ainda praticará bastante no CJRM, então também recomendo que não foque nisso em excesso agora. Seguindo o princípio que mencionei ali no primeiro parágrafo dessa resposta, vc estará caminhando o passo a passo que te deixa cada vez mais próximo da Fluência =)

**Comment by Dieison37** [comment]
Bom dia Maykell,

Certinho, obrigado pelo retorno ficou mais claro pra mim essa questão.


Att.
DIEISON L. VIEIRA.


Em qua., 26 de out. de 2022 às 12:17, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Excelente! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
