### ISSUE TITLE
Resumo da Aula O método map - Aula 01-02 da etapa 08

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5414]
- Metodo map( )
Este metodo e usado para criar um novo array a partir de outro ja existente , transformando-o sem modificar o original.
Lembrando que para nao alterar o array original nao deve ser feito nenhuma atribuicao e sim retornar as modificacoes.
Este pode receber ate 3 (item, index, array) parametros sendo apenas (item) obrigatorio.

Ex:
     const element = [1, 2, 3]
    const transformedArray =  element.map((item) => {item * 2})

**Comment by Roger-Melo** [comment]
Boa @YukOnRails rumo à fluência! 🔥
