### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5420]
# **Tipos de refêrencia vs Tipos primitivos**

## Tipos primitivos
- Todos os tipos de primitivos
1- Numbers 
2- Strings 
3- Booleans 
4- Null 
5- Undefined 
6- Symbol 
7- Biglnt 

``` js
let scoreOne = 50;
let scoreTwo = scoreOne; // O stack está criando uma copia do número 50 na variável scoreTwo.

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);

scoreOne = 100; // scoreOne vai ter 100, mas o scoreTwo vai continuar com 50.

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);
```

## Tipos de referência
- Todos os tipos de objetos
1- Objetos literais
2- Arrays
3- Funções
4- Datas
5- Todos os outros objetos

``` js
let userOne = { name: "Roger", age: 31 };
let userTwo = userOne; // As duas variáveis vão apontar para o mesmo objeto no HEAP

console.log(userOne, userTwo);

userOne.age = 32; // As duas váriaveis vão mudar, porque elas estão apontando para o mesmo valor.

console.log(userOne, userTwo);
```

## **Qual a diferença entre eles?**

> A diferença entre eles está na forma que são armazenados na memoria, quando criamos um tipo primitivo e atribuibos a esse tipo uma variável ou uma constante, esse valor é armazenado em uma STACK. Já os tipos de refêrencia são armazenados no HEAP.

- **HEAP = "Amontoado" tem mais espaço disponivél, mas é um pouco mais lento.**
- **STACK = "pilha" de diferentes válores na memoria, e esses valores podem ser acessados rápidamente quando precisamos usar ele, mas esse espaço é limitido.**

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
