### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5423]
Switch statement é usado para verificar uma variável ou constante que pode ter multiplos valores diferentes e para cada valor possível tem a possibilidade de reagir de forma diferente. É usado uma case que é como se fosse uma const e no final de cada bloco de código e inserido a palavra break para que seja realizada a leitura individual do cada bloco.

**Comment by Roger-Melo** [comment]
Boa @Dieison37  rumo à fluência! 🔥
