### ISSUE TITLE
Exercício 06 

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5424]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/803284

### Descreva a dúvida

@Roger-Melo

Roger, eu estranhei essa nova maneira de declarar um array com ([ ]) :

![Captura de tela 2022-10-28 174640](https://user-images.githubusercontent.com/71138743/198738377-3234ee1a-2e69-4681-a273-ddb1132bbea6.png)

Me confundiu mais ainda o fato dele terminar sendo inserido dentro do console.log:

![image](https://user-images.githubusercontent.com/71138743/198738645-afd532f4-c638-4e6c-aea9-41da56ab3074.png)

Eu fiquei com tanta dúvida nessa resolução que não sei nem como formular a pergunta da dúvida, mas estou com bastante dificuldade desde que cheguei aqui nesse exercício.

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Em JavaScript, arrays são valores (como strings, numbers, booleans, objetos, etc) e nem toda vez vc precisa atribuir um valor para uma const =)

Porém, de certa forma, vc está atribuindo o array para uma variável.

Pq pensa comigo, se ao especificar `[qualquerValorAqui]` vc está criando um array e está inserindo este array como argumento de uma função, isso significa que este array será atribuído ao parâmetro da função. E parâmetro é uma variável =)

A única diferença é que parâmetros são variáveis que podem ser usadas apenas dentro da função =)

Sacou a ideia?

**Comment by Ale557333** [comment]
Saquei sim Roger, muito obrigado!

**Comment by Roger-Melo** [comment]
Boa! No que precisar, é só abror uma nova issue =)
