### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#544]
Funções são blocos de código que executam alguma ação e que podem ser invocadas em qualquer ponto do nosso código. Os métodos são funções, mas são funções associadas a algum objeto ou algum tipo de dado. As funções são criadas e invocadas sozinhas, já os métodos são criados e invocados a partir de um objeto, utilizando primeiro o nome do objeto, seguido de um ponto (.) e em seguida o nome do método. Ambas podem ou não receber parâmetros e também podem atribuir seus retornos a variáveis para fazermos algo em seguida. No exemplo abaixo, vamos criar e invocar uma função que dará boas-vindas a alguém.

```jsx
const welcome = () => 'Seja bem-vindo!';

const greet = welcome();

console.log(greet);
// Seja bem-vindo
```

Agora vamos invocar um método que irá transformar uma *string* em caixa alta:

```jsx
const name = 'Jonas Kahnwald';

const nameInUpperCase = name.toUpperCase();

console.log(nameInUpperCase);
// JONAS KAHNWALD
```

Resumindo, funções e métodos fazem a mesma coisa, porém além de nomes diferente, as formas de criação e invocação também são diferentes.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência! 🔥
