### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5442]
# Modificando estilos CSS (inline)

### Podemos alterar um setar / alterar um valor de um atributo usando `setAttribute`. Exemplo:
``` js
title.setAttribute('style', 'color: yellow')
```
- **Mas essa forma não é eficiente porque o atributo anterior é substituído.**

-----------------------

## Mas podemos adicionar um estilo inline de outra forma. Exemplo: 

``` js
// CSS
 <h1 style="color: blue">Modificando estilos CSS (inline)</h1>

// JS
const title = document.querySelector('h1')
title.style.color = 'red'
title.style.margin = '50px'
title.style.fontSize = '50px'
```

**Para remover o style é só deixa-lo com uma string vazia.**
``` js
title.style.margin = ''
```

**Comment by Roger-Melo** [comment]
Boa @lucamacedos rumo à fluência! 🔥
