### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5443]
# Obtendo, adicionando, removendo e alternando classes CSS

## Element.classList
O `Element.classList` é um propriedade de somente leitura que retorna um `DOMTokenList` contendo todos os atributos da classe de **um** elemento. Exemplo:
### `DOMTokenList` é similar a um array

``` js
// CSS
<p class="arroz feijao">lorem error lorem</p>

// JS
const paragraph = document.querySelector('p')
console.log(paragraph.classList)
```

---------------------

### Pegando os "P" do documento e adicionando classes

``` js
const paragraphs = document.querySelectorAll('p')
paragraphs.forEach(paragraph => {
  if (paragraph.innerText.includes('error')) {
    paragraph.classList.add('error')
  }

  if (paragraph.innerText.includes('success')) {
    paragraph.classList.add('success')
  }
})
```

-----------------

### Adionando classes ao elemento

``` js
const title = document.querySelector('h1')

title.classList.toggle('test')
title.classList.toggle('test')
```

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos , rumo à fluência! 🎯
