### ISSUE TITLE
Resumo da Aula O  método reduce - Aula 01-04 da etapa 08

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5452]
Usamos o reduce quando baseados no array original precisamos reduzir o array a um outro tipo de dado, um objeto literal, uma string, um numero, ou até mesmo um novo array. O reduce tem o poder e versatilidade para gerar um output que não necessariamente é um array.

```js
const numbers = [1,2,3]

const calculo = numbers.reduce((accumulator, number) => accumulator += number, 0)

console.log(calculo)
```

Esse segundo argumento (o 0 depois da virgula) serve apenas para ser o valor do accumulator na primeira vez que a função foi executada, depois da primeira execução da função ele não precisa ser lembrado, pois ele foi apenas um ponto de partida, contudo é uma boa pratica especificar esse valor inicial para que tenhamos uma representação visual e explicita do tipo de dado que o reduce vai retornar, que na ocasião é um numero. 

Neste exemplo nos pegamos um array e reduzimos ele há um único numero

--------------------------------

Ex 2:

```js
const phaseScores = [
    { name: 'Vinicius Costa', score: 337 },
    { name: 'Roger Melo', score: 43 },
    { name: 'Alfredo Braga', score: 234 },
    { name: 'Pedro H. Silva', score: 261 },
    { name: 'Ana Paula Rocha', score: 491 },
    { name: 'Vinicius Costa', score: 167 },
    { name: 'Roger Melo', score: 137 },
    { name: 'Alfredo Braga', score: 135 },
    { name: 'Ana Paula Rocha', score: 359 },
    { name: 'Pedro H. Silva', score: 133 }
  ]

  const rogerScore = phaseScores.reduce((accumulator, phaseScore) => {
                if(phaseScore.name === 'Roger Melo') {
                    accumulator += phaseScore.score
                }
return accumulator
  },0)

  console.log(rogerScore)
```

Neste outro exemplo nós pegamos apenas o valor do score, somamos e apresentamos ele com o método reduce.

**Comment by Roger-Melo** [comment]
Excelente @Hugones45 , rumo à fluência! 🎯
