### ISSUE TITLE
Resumo da Aula Mais sobre o Spread Operator: Casos de uso em strings e funções - Aula 01-06 da etapa 14 

### ISSUE THREAD

**Issue by EussouShAd** [roger-melo-treinamentos/curso-de-js-roger-melo#5454]
# Mais sobre o Spread Operator

### Unindo objetos e array
Com o spread operator conseguimos espalhar caracteres de uma string dentro de um array.

```js
const str = 'Eussoushad'
console.log( ...str) // "E" "u" "s" "s" "o" "u" "s" "h" "a" "d"
const arr = [...str]  
console.log( arr)  // ["E","u","s","s","o","u","s","h","a","d"]
``` 

E também consegue usar variáveis que armazenam arrays em funções que só aceitam por exemplo números como argumentos porque por baixo dos panos os itens deste array vão ser espalhados como argumentos desta função.
```js
const numbers = [1, 2, 3, 4]

console.log(Math.max(...numbers))
console.log(Math.min(...numbers))

**Comment by Roger-Melo** [comment]
Excelente @EussouShAd , rumo à fluência! 🎯
