### ISSUE TITLE
Aplicação própria: traffic_light

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#5458]
### Etapa da aula

5

### Nome da aula

Modificando estilos CSS (inline) - Aula 02-04 

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/853300

### Descreva a dúvida

@Roger-Melo,  fiz este projeto colocando em prática o que até então foi ensinado em seu treinamento e paralelamente juntei com a busca na documentação(MDN) e saiu este projeto...

-  Repositório: https://github.com/Bruno-Luna/traffic_light_js

-  Deploy: https://bruno-luna.github.io/traffic_light_js/

A aplicação consiste em: ao clicar em 'play' é exibido dinamicamente um contador em ordem crescente que vai até o número 60 e dentro deste tempo, há a troca das cores do semáforo.

Consegui colocar em prática alguns conceitos/metodos como: o setAtributte, a estilização inline, querySelector, template literals, DOM etc.
Ficou algo simples. Gostaria se possível de um feedback e dicas para meu aprimoramento.
Desde já, agradeço muitissimo.

**Comment by MivlaM** [comment]
Olá @Bruno-Luna.

Recebemos a solicitação para a análise da aplicação que você fez. O prazo estimado para uma análise completa é de 10 dias úteis, pois também temos as aplicações desenvolvidas no treinamento para análise e elas são prioritárias. Mas não se preocupe, você irá receber um feedback sobre o código e as dicas para seu aprimoramento como demandado, apenas lhe solicito um pouco de paciência até lá.

**Comment by Bruno-Luna** [comment]
Olá, caro @MivlaM .

Certo, agradeço muitíssimo.

**Comment by MivlaM** [comment]
Olá, @Bruno-Luna.

Parabéns pelo esforço em construir a aplicação =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Code styling

Ao longo do código, há algumas inconsistências em relação ao uso das aspas, do ponto e vírgula e do idioma:

```js
// Uso de aspas simples, sem ponto e vírgula e trechos em português e em inglês juntos
const btnRefresh = document.querySelector('.refresh_btn')

alterarImg(sinalVermelho, sinalVerde, attributeSrc)
```

```js
// Uso de aspas duplas e ponto e vírgula
const elementH4 = document.getElementById("demo");
const card = document.querySelector(".card-panel");
```

É uma boa prática manter um padrão na maneira que você escreve o código. Uma sugestão é que você escolha uma das formas e seja consistente com essa escolha no decorrer do código.

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que vc formate manualmente. 

Isso vai "forçar" vc a adotar um estilo de escrita de código e ser consistente com esse estilo ao implementar suas aplicações.

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a const `card` e a let `cont` que você usou no código podem ter seus nomes substituidos por `containerCounterText` e `counter` respectivamente. O intuito aqui é fazer com que os nomes se tornem mais explicativos, para que a pessoa, quando bater o olho no código já entender de cara o que as linhas de código em questão estão armazenando.

```js
// antes
const card = document.querySelector(".card-panel")

let cont = 0
```

```js
// depois
const containerCounterText = document.querySelector(".card-panel")

let counter = 0
```

Com o objetivo de padronizar um único idioma nas linhas de código da aplicação, a sugestão aqui é trocar o nome de `imgSemaforo` para algo como `imgTrafficLight`, penso que assim a leitura do código se torne mais fluída e de compreensão mais simples do que quando há duas línguas distintas.

```Js
// antes
const imgSemaforo = document.querySelector("img")
```

```js
// depois
const imgTrafficLight = document.querySelector("img")
```

Por fim, você também pode renomear a const `elementH4` para `counterText`, a ideia aqui é caso futuramente o elemento mudar para h3, por exemplo, a const não precisará ser renomeada, pois a nomenclatura da const estará escrita de forma mais abrangente.

```js
// antes
const elementH4 = document.getElementById("demo")
```

```js
// depois
const counterText = document.getElementById("demo")
```

A função `contador`, para melhorar na legibilidade do código e seguir o princípio mostrado logo acima, pode ser renomeada para algo como `startCounter`, visto que a palavra contador é um substantivo e não verbo. Uma outra recomendação seria mover o trecho de código na qual a função é declarada para acima de onde ela é usada, para também deixar a leitura do código mais fluída.

```js
// antes
btnStart.onclick = () => {
  contador()
  btnStart.setAttribute("disabled", true)
}

const contador = () => {
  // ...
}
```

```js
// depois

const startCounter = () => {
  // ...
}

btnStart.onclick = () => {
  startCounter()
  btnStart.setAttribute("disabled", true)
}
```

Algo semelhante acontece com a função `condicaoTrocaDeImagem`, uma função, preferencialmente deve ser nomeada por um verbo, não por um substantivo. Mas aqui vou propor uma outra modificação, se você achar interessante, esse trecho de código armazenado por essa função pode ser movido para `alterarImg`, visto que não é tão necessário criar uma outra função para uma funcionalidade que pode ser abrangida pela `alterarImg`, os códigos de ambas são tão complementares que acredito que apenas uma função seja necessária aqui, e de benefício, você ainda economiza algumas linhas de código. Ficaria assim:

```js
// antes
const condicaoTrocaDeImagem = () => {
  const sinalVermelho = counter >= 0 && counter <= 20
  const sinalVerde = counter >= 20 && counter <= 52
  const attributeSrc = "src"
  
  alterarImg(sinalVermelho, sinalVerde, attributeSrc)
}

const alterarImg = (sinalVermelho, sinalVerde, attributeSrc) => {

  if (sinalVermelho) {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/vermelho.png")
    containerCounterText.style.backgroundColor = '#e53935'
  }
  else if (sinalVerde) {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/verde.png")
    containerCounterText.style.backgroundColor = '#4caf50'
  }
  else {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/amarelo.png")
    containerCounterText.style.backgroundColor = '#f9a825'
  }
}
```

```js
//depois
const alterarImg = () => {

  const sinalVermelho = counter >= 0 && counter <= 20
  const sinalVerde = counter >= 20 && counter <= 52
  const attributeSrc = "src"

  if (sinalVermelho) {
    // ...
  }
  else if (sinalVerde) {
    // ...
  }
  else {
    // ...
  }
}
```

---

## Refatorações nas funções

Na função `startCounter`, há algumas coisas que podemos refatorar. De início, if (counter === 60) está sem bloco, o que além de estar irregular em relação aos outros ifs da aplicação, [Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos e colocou a segurança de dados em xeque por causa desse tipo de decisão. A recomendação é que você sempre use os blocos de chaves quando for usar um if.

```js
// antes
if (counter === 60)
  counter = 0
```

```js
// depois
if (counter === 60){
  counter = 0
}
```

Depois disso, podemos fazer a seguinte refatoração, para facilitar a lógica dessa função e deixá-la mais simples, a condição de if (counter === 60) pode ser movida para o início do `setInterval`. Após ter feito isso, a condicional do if de (counter <= 60) não vai mais precisar existir, você economiza um if deixando o código dentro de seu bloco logo abaixo do if anterior. Por fim,  também vamos mover a let `counter` para dentro dessa função, visto que não há mais necessidade dela ser global após termos colocado o código de `condicaoTrocaDeImagem` dentro de `alterarImg`. `counter` pode ficar na primeira linha de `startCounter` e `alterarImg` pode ter o valor de `counter` passado como parâmetro. A função após todas as refatorações ficaria assim:

```js
// antes
const startCounter = () => {
  setInterval(() => {
    if (counter <= 60) {
      counterText.innerHTML = counter
      counter = counter + 1;
      alterarImg()
    }
    if (counter === 60){
      counter = 0
    }
  }, 1000);
}
```

```js
// depois
const startCounter = () => {
  let counter = 0

  setInterval(() => {
    if (counter === 60){
      counter = 0
    }
    counterText.innerHTML = counter
    counter = counter + 1;
    alterarImg(counter)
  }, 1000);
}
```

Na função alterarImg, seguindo a ideia de manter os nomes de função em apenas um padrão de idioma, podemos renomeá-la ocmo `getTrafficLightStyle`. A ideia de refatoração aqui é, para cada if dentro da função, vamos fazer retornar um objeto que contém o caminho da img e o hexadecimal da cor do background como propriedade. Seria mais ou menos assim:

```js
return {
  imgSrc: "", bckColor: "" // Entre as aspas, em imgSrc fica o endereço de cada imagem e em bckColor o hexadecimal da cor 
}
```

Além disso, `sinalVermelho` e `sinalVerde` não precisam existir, pois armazenam expressões curtas e simples de entender que podem ser usadas diretamente entre os parênteses do if. A const `attributeSrc` também pode ser eliminada. Agora, um pequeno detalhe na expressão `counter >= 20 && counter <= 52`, o `=` da expressão ao lado esquerdo do && não precisa existir, porque a expressão do sinal vermelho já cobre o caso de quando o counter é igual a 20. Por fim, essa função totalmente refatorada ficaria assim:

```js
// antes
const alterarImg = (counter) => {

  const sinalVermelho = counter >= 0 && counter <= 20
  const sinalVerde = counter >= 20 && counter <= 52
  const attributeSrc = "src"

  if (sinalVermelho) {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/vermelho.png")
    containerCounterText.style.backgroundColor = '#e53935'
  }
  else if (sinalVerde) {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/verde.png")
    containerCounterText.style.backgroundColor = '#4caf50'
  }
  else {
    imgTrafficLight.setAttribute(`${attributeSrc}`, "assets/img/amarelo.png")
    containerCounterText.style.backgroundColor = '#f9a825'
  }

}
```

```js
// depois
const getTrafficLightStyle = (counter) => {

  if (counter >= 0 && counter <= 20) {
    return {
      imgSrc: "assets/img/vermelho.png", bckColor: "#e53935"
    }
  }
  else if (counter > 20 && counter <= 52) {
    return {
      imgSrc: "assets/img/verde.png", bckColor: "#4caf50"
    }
  }
  return {
    imgSrc: "assets/img/amarelo.png", bckColor: "#f9a825"
  }
}
```

Entretanto, o funcionamento dessa função ainda não está completo. Agora, tendo em vista o que foi mostrado anteriormente, na função `startCounter`, uma única ocorrência de `setAttribute` e `style.backgroundColor` podem ser inseridos dentro dessa função. A ideia aqui é fazer com que os valores sejam inseridos de forma dinâmica, aproveitando o objeto retornado pela invocação de `getTrafficLightStyle`:

```js
const startCounter = () => {
  let counter = 0

  setInterval(() => {
    // ...
    const {imgSrc, bckColor} = getTrafficLightStyle(counter)

    imgTrafficLight.setAttribute('src', imgSrc)
    containerCounterText.style.backgroundColor = bckColor

    // ...
  }, 1000);
}
```

Após isso, observando a ordem dos acontecimentos, faz mais sentido que o `counter` seja incrementado na última linha da função, após toda a manipulação de DOM. Também vale ressaltar que, em questão de legibilidade, `startCounter` pode ser apenas referenciada como função de callback de `btnStart.onclick`. Para isso, basta inserir o btnStart.setAttribute como última linha de `startCounter`.

No final, a função `startCounter` completamente refatorada ficará assim:

```js
btnStart.onclick = "startCounter()"

btnRefresh.onclick = () => {
  window.location.reload()
}

// ...

const startCounter = () => {
  let counter = 0

  setInterval(() => {
    if (counter === 60){
      counter = 0
    }
    counterText.innerHTML = counter
    const {imgSrc, bckColor} = getTrafficLightStyle(counter)

    imgTrafficLight.setAttribute('src', imgSrc)
    containerCounterText.style.backgroundColor = bckColor

    counter = counter + 1
  }, 1000);
  btnStart.setAttribute('disabled', true)
}
```

## Uso de onclick antes de ser apresentado no treinamento

Em nenhum momento até o ponto onde você está no CJRM onclick foi recomendado. A forma recomendada de adicionar eventos em elementos do DOM é addEventListener. Na etapa 15 é mostrado quando onclick deve ser usado, mas até lá, recomendo que você siga o que foi apresentado no treinamento, não faz muito sentido usar onclick nesse caso. Prefira substituí-los por addEventListener e aqui, podemos criar uma função `reloadPage` que irá conter o mesmo código atual, mas que será usado como callback do listener de `btnRefresh`. Ficaria assim:

```js
// antes
btnStart.onclick = "startCounter()"

btnRefresh.onclick = () => {
  // ...
}
```

```js
// depois

const reloadPage = () => window.location.reload()

btnRefresh.addEventListener('click', reloadPage)
btnStart.addEventListener('click', startCounter)
```

Por questões de organização, addEventListeners devem ficar agrupados no final do código. Assim, o código fica "subdividido" em 3 grandes grupos: referências de elementos do DOM, declarações de funções e invocações de listeners de eventos.

```js
// depois
const imgTrafficLight = document.querySelector('img')
const btnStart = document.querySelector('.start_btn')

//...

const startCounter = () => {
  // ...
}

const getTrafficLightStyle = (counter) => {
  // ...
}

// ...

btnRefresh.addEventListener('click', reloadPage)
btnStart.addEventListener('click', startCounter)
```

Por fim, seu app.js no total continha 55 linhas, e após as refatorações, agora contém 44. Cerca de 11 linhas a menos de código =)

A análise acaba aqui, mas mais uma vez, parabéns pelo esforço =)

**Comment by Bruno-Luna** [comment]
Olá, caro @MivlaM.

Agradeço a generosa atenção e feedback minucioso. Irei me debruçar em cada ponto mencionado. 
Caso haja dúvidas, abro uma nova issue.

**Comment by Bruno-Luna** [comment]
Na função startCounter, há algumas coisas que podemos refatorar. De início, if (counter === 60) está sem bloco, o que além de estar irregular em relação aos outros ifs da aplicação, [Esse](https://youtu.be/arNtoWxBuXc?t=1389) bug crítico no SSL da Apple aconteceu há alguns anos e colocou a segurança de dados em xeque por causa desse tipo de decisão. A recomendação é que você sempre use os blocos de chaves quando for usar um if.
```js
// antes
if (counter === 60)
  counter = 0
```
```js
// depois
if (counter === 60){
  counter = 0
}
```
Nessa sua orientação, pelo que entendi é: sempre usar a abertura e fechamento do bloco IF, ainda que seja opcional quando se trata de uma linha de código?

**Comment by MivlaM** [comment]
Olá @Bruno-Luna

## 1) Nessa sua orientação abaixo, pelo que entendi é: sempre e em quaisquer circunstâncias usar a abertura e fechamento do bloco IF/ELSE, ainda que seja opcional quando se trata de uma linha de código, devido essa falha de SSL da Apple?

É uma recomendação usar a abertura e fechamento de bloco do if, essa é a forma recomendada ao longo do treinamento e um dos motivos para isso é essa questão da falha de SSL na Apple, pode ocorrer algo similar em outro momento devido a falta das chaves. Portanto, é o recomendado usar abertura e fechamento no bloco do if.

## 2) Desculpe-me, mas não consegui entender ao certo essa const com { }. Não cheguei nessa parte do treinamento, ainda. Se puder me ajudar na compreensão, por gentileza.

Essa const com { } é referente a algo chamado Destructuring Assignment. Você ainda vai ver mais a respeito disso mais adiante no treinamento, não te preocupe, pois quando você chegar lá, você vai poder voltar nessa análise e entender melhor o que foi feito. Até lá, eu sugiro que você faça a refatoração nessa parte por meio da sintaxe de objeto.propriedade. Por meio dela, você acessa as propriedades do objeto que é retornado pela função `getTrafficLightStyle`. Seria assim:

```js
// antes
const {imgSrc, bckColor} = getTrafficLightStyle(counter)

imgTrafficLight.setAttribute("src", imgSrc)
containerCounterText.style.backgroundColor = bckColor
```

```Js
// depois
imgTrafficLight.setAttribute("src", getTrafficLightStyle(counter).imgSrc)
containerCounterText.style.backgroundColor = getTrafficLightStyle(counter).bckColor
```

## 3) Qual sua orientação de quando colocar uma expressão em uma variavel para facilitar a legibilidade?

Não é necessária ter essa obrigatoriedade de colocar toda expressão numa variável, a ideia que gosto de seguir é a de colocar uma expressão em uma variável quando ela for mais difícil de entender, claro que essa dificuldade é subjetiva, mas nessas situações, acredito que armazená-la numa const de nome adequado para seu papel no código seja uma opção interessante. Entretanto, as expressões de `sinalVermelho` e `sinalVerde` não necessariamente precisam ser armazenadas nessas consts, pois além dos critérios que citei anteriormente, elas são muito mais simples e acaba que você tem a vantagem de economizar mais linhas de código quando a lógica delas é colocada diretamente no condiconal.

---

Está conseguindo entender melhor? Se restou alguma dúvida, pode me chamar aqui novamente que irei te ajudar =)

**Comment by Bruno-Luna** [comment]
Caro @MivlaM, muito obrigado. Todos os seus esclarecimentos foram de bom proveito e me fizeram aprender e reforçar vários conceitos.
Agradeço-te.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
