### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03 da etapa 03.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5460]
A diferença entre function declaration e function expression e praticamente nenhuma, mas tem um detalhe chamado "hoisting" (içamento), puxar pra cima, levantar ou elevar na function declaration a função pode estar em qualquer lugar do código que não seja no topo do arquivo, vai funcionar já a function expression vai dar erro no código.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37 , rumo à fluência! 🎯
