### ISSUE TITLE
Foto não aparece algumas vezes

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#5463]
### Etapa da aula

15

### Nome da aula

Você consegue implementar este ajuste? Desafio no desafio - Aula 03-33

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/5895058

### Descreva a dúvida

Repositório do exercício em andamento:
https://github.com/ElaineDelgado/cjrm-etapa15-add-remove-event-listeners

Boa tarde, professor!!

Eu tinha começado a implementar os detalhes da conta, e na minha cabeça pedia a foto também, e hoje ao assistir a aula de correção e voltar no Readme-md vi que não foi pedido para mostrar a foto. Só que eu tive um problema que me deixou com uma pulga atrás da orelha: quando com a conta dejiko.leekspin a foto aparece no "Detalhes da Conta", quando logo com  delgado.elaine03 a foto não carrega na aplicação.

A URL da foto está correta, pois se eu  copiar a URL e colar no browser ela carrega:

https://lh3.googleusercontent.com/a/ALm5wu1FVS3PnbQ3fCyaMy0RMAr-PJcZHrAyZtLZZhCq=s96-c

Coloquei o código da aula no Github para facilitar, poderia me ajudar a descobrir o que pode estar acontecendo, por favor?

Edit: Esse texto da Issue eu escrevi anteontem mas não enviei, e ontem ao mexer na aplicação vi que o problema não estava acontecendo. Hoje, ao assistir a aula para correção da implementação da autenticação com Redirect, o problema continuava mas inverteu: a foto que não aparecia antes, agora aparece, e a outra não.

Abçs! 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @ElaineDelgado!

Acho que o repositório que vc linkou está privado, pois exibiu um status code 404.

Dá uma olhada se é isso mesmo e me avisa aqui =)

**Comment by ElaineDelgado** [comment]
Verdade, estava privado, desculpe!!
Mudei a visibilidade para público.

**Comment by Roger-Melo** [comment]
@ElaineDelgado, usando o `setAttribute`, insere um atributo `referrerpolicy` e insira `no-referrer` como valor do atributo. Fazendo isso, provavelmente irá funcionar como o esperado =)

O "por que" disso é um assunto com um viés de conhecimentos detalhados sobre HTTP. 

Vou deixar aqui abaixo um post que pode deixar isso mais claro e qualquer dúvida que tiver, é só perguntar =)

- [Referer and Referrer-Policy best practices](https://web.dev/i18n/en/referrer-best-practices/)

**Comment by ElaineDelgado** [comment]
Vou ver agora mesmo, muito obrigada, professor!!

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
