### ISSUE TITLE
Resumo da Aula phaseScores da etapa 08

### ISSUE THREAD

**Issue by EvertonMattos** [roger-melo-treinamentos/curso-de-js-roger-melo#5469]
**Reduce=> Você precisa reduzir um array orignal algum tipo de dado pode ser um objeto literal algum number ou ate mesmo um novo array 
ele sempre precisa retorna um valor 
Esse segundo argumento (o 0 depois da virgula) serve apenas para ser o valor do accumulator na primeira vez que a função foi executada, depois da primeira execução da função ele não precisa ser lembrado, pois ele foi apenas um ponto de partida, contudo é uma boa pratica especificar esse valor inicial para que tenhamos uma representação visual e explicita do tipo de dado que o reduce vai retornar, que na ocasião é um numero.**
Parâmetros

callback: função que e executada em cada valor no array.

Acumulador => é o valor inicial ou valor do callback anterior , este valor inicia com o valor inicial será retornado na ultima interação
 
valorAtual=> Opcional. O índice do elemento atual que está sendo processado no array. Começa a partir do index 0 se um valorInicial for fornecido. Do contrário, começa do index.

valorInicial=>Opcional. Valor a ser usado como o primeiro argumento da primeira chamada da função callback. Se nenhum valorInicial é fornecido, o primeiro elemento do array será usado como o valor inicial do acumulador e o valorAtual não será lido. Chamar reduce() em uma array vazia sem valor inicial retornará um erro.

```
const phaseScores = [
  { name: 'Vinicius Costa', score: 337 },
  { name: 'Roger Melo', score: 43 },
  { name: 'Alfredo Braga', score: 234 },
  { name: 'Pedro H. Silva', score: 261 },
  { name: 'Ana Paula Rocha', score: 491 },
  { name: 'Vinicius Costa', score: 167 },
  { name: 'Roger Melo', score: 137 },
  { name: 'Alfredo Braga', score: 135 },
  { name: 'Ana Paula Rocha', score: 359 },
  { name: 'Pedro H. Silva', score: 133 },
  {name:'Roger Melo', score:150}
]

const rogerScore = phaseScores.reduce((accumulator,phaseScore)=>{
  if(phaseScore.name === 'Roger Melo'){
    accumulator+= phaseScore.score
  }
  return accumulator
},0)
console.log(rogerScore)
```

**Comment by Roger-Melo** [comment]
Excelente @EvertonMattos, rumo à fluência! 🎯
