### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5478]
Retornando valores, a declaração return finaliza a execução de uma função e especifíca o valor que deve ser retornado para onde a função foi invocada. Quando uma declaração return é inserida no bloco de código de uma função, a mesma é parada. Se não for especifícado um valor não retornará nada.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37 , rumo à fluência! 🎯
