### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5481]
# Mais eventos do DOM

### O evento copy se ativa quando o usuário faz a ação de copiar no browser 
**Exemplo**: 

``` js
const paragraph = document.querySelector('.copy-me')

paragraph.addEventListener('copy', () => {
  console.log('Texto copiado!')
})
```

--------------

### O mousemove evento inicia em um elemento quando o ponteiro do computador é movimentado dentro do elemento.
**Exemplo**: 

``` js
const div = document.querySelector('.box')

div.addEventListener('mousemove', event => {
  div.textContent = `X = ${event.offsetX} | Y = ${event.offsetY}`
})
```

---------------------------

### O evento wheel inicia quando o bola de rolagem do mouse é rodada.
**Exemplo**: 

``` js
const div = document.querySelector('.box')

document.addEventListener('wheel', event => {
console.log(event.pageX, event.pageY)
})
```

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos,rumo à fluência! 🎯
