### ISSUE TITLE
Resumo da Aula O método sort - Aula 02-02 da etapa 08

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5483]
- Metodo sort( )
E utilizado para ordenar elementos como strings, numeros e objetos.
Este e encadeado a um array e pode receber um callback de comparacao com ate dois parametros.

Ex:
                const theBigFamily = [
          { name: 'Lineu', score: 20 },
          { name: 'Nenê', score: 10 },
          { name: 'Tuco', score: 50 },
          { name: 'Bebel', score: 30 },
          { name: 'Agostinho', score: 70 }
        ]

Exemplos de comparacao e ordenacao DECRESCETE:

        theBigFamily.sort((item1, item2) => item2.score - item1.score)

Exemplos de comparacao e ordenacao CRESCENTE:

        theBigFamily.sort((item1, item2) => item1.score - item2.score)

OBS: O metodo sort( ) quando encadeado, altera o elemento original.

**Comment by Roger-Melo** [comment]
Show @YukOnRails. Vamo que vamo, rumo à fluência! 🙌
