### ISSUE TITLE
Resumo da Aula Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5486]
**Funções vs Métodos**

Funções são blocos de código que executa alguma ação e que podem ser invocadas a qualquer ponto do nosso código.

Funções e Métodos são sinônimos, pois podem ser invocados para ser executar um pedaço de código que faz alguma coisa, ou seja, o método é uma função, o que diferencia o método é a forma como o invocamos e onde é declarado.

Função:

![11](https://user-images.githubusercontent.com/71138743/200697923-a4cd2d8f-7a8a-4c49-9526-5e1f552e4708.png)

Observe que para invocar uma função é necessário inserir o nome, abertura e fechamento de parênteses. Quando invocamos um método, usamos a notação de ponto:
Método:
![22](https://user-images.githubusercontent.com/71138743/200697973-42d4b9d8-4717-424d-af85-51b4a90710f5.png)

Em ambos os casos, está sendo usado os parênteses para fazer a invocação e eles podem receber argumentos, a única diferença é que na parte de trás  da invocação do método, está referenciando um valor e inserindo um ponto.
![33](https://user-images.githubusercontent.com/71138743/200698030-cf9462bf-4286-4ee7-ab26-10df1c840d6c.png)

Se quiser armazenar o resultado dessa expressão, pode ser inserido uma constante.
Ou seja, métodos são funções, mas que estão associadas a objetos ou tipos de dados como strings, os métodos são criados num objeto ou no tipo de dado em si.  Já as funções são criadas sozinhas.

**Comment by Roger-Melo** [comment]
Show @Ale557333. Vamo que vamo, rumo à fluência! 🙌
