### ISSUE TITLE
Exercícios da Aula 01

### ISSUE THREAD

**Issue by Polianeh** [roger-melo-treinamentos/curso-de-js-roger-melo#5488]
### Etapa da aula

1

### Nome da aula

Aula 01-06

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/733512

### Descreva a dúvida

Olá, boa noite Roger.

Eu já tenho o git instalado. Utilizo o Windows e instalei o Hyper. Quando eu dei o comando cd + espaço + 2x o Tab ele não listou meus diretórios, apareceu "cd .ms-ad". Gostaria de entender o motivo.
Embora eu já tenha ido ao VSC, abri o terminal e baixei todos os exercícios.

Obrigada

@Roger-Melo

**Comment by Polianeh** [comment]
Obrigada

**Comment by Roger-Melo** [comment]
No que precisar, fique à vontade para abrir uma nova issue, ok? =)

Não sei se você já entrou, mas eu enviei por email um link para o novo grupo de alunos do CJRM no Telegram. Dá uma olhada se recebeu =)

@Polianeh
