### ISSUE TITLE
Resumo da Aula Eventos do teclado - Aula 02-03

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5493]
# Eventos do teclado

## KeyUp
**Os `keydown` e `Keyup`  fornecem umas indicação de qual key está sendo pressionada, e podemos fazer uma ação quando a key for pressionada ou solta.**

``` js
form.username.addEventListener('keyup', event => {
  const isAValidUsername = testUsername(event.target.value)
  console.log(event)
  if (isAValidUsername) {
    form.username.setAttribute('class', 'sucess')
    console.log('É valido')
    return
  }

  form.username.setAttribute('class', 'error')
})
```
> Quando uma key for solta o código vai verificar se o username é válido ou não.

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos, rumo à fluência! 🎯
