### ISSUE TITLE
Resumo da Aula Mais importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by JhonatanSerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#5496]
# Iniciando curso

*Entendendo o processo do curso e descobrindo uma nova forma de estudo e aprendizagem;
* Como criar uma Issue e documentar meu aprendizado por meio de um __resumo__
* A importancia de tirar dúvidas pelo github: Cria uma sintaxy highLight assim dando enfase para códigos. (Mais elegante);
* Revisão Raio-X: Tipo de revisão usando engenharia reversa;
* Desenvolvimento do portifólio;
* Se candidatar para vagas mesmo com medo.

**Comment by Roger-Melo** [comment]
Excelente @JhonatanSerafim, rumo à fluência! 🎯
