### ISSUE TITLE
Resumo da Aula Adicionando to-dos - Aula 01-03 da etapa 09

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5497]
Começaremos nessa etapa a criação de um To-do List, também vamos ver métodos novos e revisar alguns conceitos já vistos durante o curso nesta aula.

A primeira funcionalidade que iremos implementar é adicionar um item no to-do list, quando o form for enviado. 

-------------------------------------

```js
formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()
    console.log(inputValue)
})
```

Aqui vamos lembrar de no evento submit colocar o event.preventDefault() para impedirmos a pagina de recarregar como o submit faz por padrão. O inputValue está fazendo o console de tudo que passarmos no inpu, pois ele está recebendo o event com todas as propriedades necessárias.
OBS: O event.target. + o que for necessário para se obter informação do form costuma variar de acordo com a aplicação, nesta por exemplo ele pega o "add" da propriedade name, em um exercício passado ele já foi o username.value, ficar atento em quanto a isso.

Por fim nesta primeira parte o trim é um novo método que nos permite remover espaços em branco no inicio e no fim da string digitada.

------------------------------

Nosso próximo passo é inserir na ul uma nova li que contem o valor do input, para isso precisamos da referencia da ul, que aqui será pega pela classe.

```js
const todosContainer = document.querySelector('.todos-container')
```

Agora quando o form for enviado podemos obter o valor do input como uma li dessa ul, fazendo um innterHTML.

```js
formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()
   
   todosContainer.innerHTML += `<li>${inputValue}</li>`
})
```

Porém se apenas fizermos dessa maneira a nova li não irá conter as propriedades de estilização que o resto das lis do to-do possue, para isso copiamos a marcação da li e formatamos ela para colocar a interpolação da nossa input.value, ficando assim:

```js
formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()
   
   todosContainer.innerHTML += `<li class="list-group-item d-flex justify-content-between align-items-center">
   <span>${inputValue}</span>
   <i class="far fa-trash-alt delete"></i>`
})
```

-------------------------------

Agora precisamos fazer o input não obter o envio de strings vazias:

```js
formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()

    if (inputValue.length) {
        todosContainer.innerHTML += `<li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>`
    }

})

```
Fazemos um if com a condição que de inputValue.length, se o comprimento da string digitada conter pelo menos um caractere, o bloco de codigo que agora contem o innerHTML recebendo as lis é executado, caso contrario o form não recebe nada.

-----------------------

Por fim para não termos que limpar o input após o envio do form, nos invocamos o método reset().
O reset() é um método que restaura os valores default de um form, e o valor padrão de um input é uma string vazia.

```js
formAddToDo.addEventListener('submit', event => {
    event.preventDefault()

    const inputValue = event.target.add.value.trim()

    if (inputValue.length) {
        todosContainer.innerHTML += `<li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete"></i>`
    }
    event.target.reset()
})
```

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
