### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5499]
Funções e métodos são sinônimos pois em excência eles fazem a mesma coisa, podem ser invocados para executar um pedaço de código que faz alguma coisa, método é uma função e o que diferencia um método de uma função é a forma de invocação dele e onde ele é declarado. Para uma invocação de um método é usado a notação de ponto(.), Ex: name.toUpperCase(), então métodos são funções que estão associadas a objetos ou tipos de dados como strings, são criados no objeto ou tipo de dado em si.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
