### ISSUE TITLE
etapa 07 - Quiz interativo

### ISSUE THREAD

**Issue by RennerMedeiros** [roger-melo-treinamentos/curso-de-js-roger-melo#55]
https://github.com/RennerMedeiros/exercicio-19

eu não fiz uso do bootstrap nesse exercício porque eu também queria treinar um pouco de css que eu sei

não tenho duvidas sobre o exercicio em si, minha duvida até agora está mais sobre a questão de callback functions  e funções que recebem outras funções como argumento, eu ainda não entendi 100% sobre esse conceito

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Renner. Parabéns pela aplicação =)

> eu não fiz uso do bootstrap nesse exercício porque eu também queria treinar um pouco de css que eu sei

Show de bola. O Bootstrap pode ser útil em casos onde não queremos focar tanto em CSS. Como você também queria treinar CSS, implementá-lo manualmente fez sentido =)

---

Dê uma olhada em [qual largura](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_width_and_screen_width) você quer inserir no `content` da `<meta>` de viewport, pois `src` não é um valor válido.

---

Algumas palavras em inglês são meio chatinhas de se escrever e podemos esquecer de inserir uma letra. Você pode substituir os nomes das const `ansers` e `userAnsers` para `answers` e `userAnswers`.

---

Tome cuidado com as linhas em branco. No código abaixo,

```javascript
const result = event => {
    event.preventDefault()
    let score = 0
    const userAnsers = [form.inputQuestion1.value,
                        form.inputQuestion2.value,
                        form.inputQuestion3.value,
                        form.inputQuestion4.value]
                        
    userAnsers.forEach((anser, index) => {
        if(anser === ansers[index]){
            score+=25
        }
    });
    document.querySelector('.result').style.display = 'block'
    userResult.textContent = `${score}%` 
}
```

perceba que a primeira linha da função invoca um método e a segunda e terceira linha declaram consts.

Prefira deixar linhas em branco entre linhas de código que executam ações diferentes. No caso, você pode deixar uma linha em branco entre a invocação do `event.preventDefault()` e da `let` e `const` e entre o final do bloco do `forEach` e as atribuições de valores no final da função. Então ficaria assim:

```javascript
const result = event => {
    event.preventDefault()

    let score = 0
    const userAnsers = [form.inputQuestion1.value,
                        form.inputQuestion2.value,
                        form.inputQuestion3.value,
                        form.inputQuestion4.value]
                        
    userAnsers.forEach((anser, index) => {
        if(anser === ansers[index]){
            score+=25
        }
    });

    document.querySelector('.result').style.display = 'block'
    userResult.textContent = `${score}%` 
}
```

---

Mesmo que a `<div class="result">` seja usada no `app.js` apenas uma vez, prefira armazenar a referência dela em uma `const`. Isso deixa o código mais legível, por que ao invés de ler

```javascript
document.querySelector('.result').style.display = 'block'
```

quem ler o código, irá ler (por exemplo)

```javascript
resultContainer.style.display = 'block'
```

sacou a ideia?

---

Ao nomear funções, prefira que elas expressem uma ação. O ideal é que os nomes sejam verbos. Então ao invés de nomear uma função como `result`, prefira nomeá-la como `showResult`, por exemplo.

Você também verá que nas aulas seguintes, vamos melhorar o código dessa aplicação.

---

É isso aí, meu caro. Mais uma vez, parabéns pelo esforço! =D

No que precisar, pode contar comigo para te ajudar na jornada para chegar na fluência na linguagem.

@RennerMedeiros

**Comment by RennerMedeiros** [comment]
certo, obrigado
