### ISSUE TITLE
Resumo da Aula A importância de você ter escolhido o JavaScript - Aula 01-02 da etapa 01

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5500]
> Javascript é uma linguagem universal que pode ser usada em múltiplos propósitos e diversas plataforma, desde criação de web sites, aplicativos para celulares, programas de desktop com Node.js. Neste treinamento o foco vai ser a utilização no browser, onde é o ambiente que a linguagem foi projetada inicialmente. 

> No browser o javascript, melhora a experiencia do usuário, adicionar interatividade as paginas, buscar e exibir dados, e muito mais.

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
