### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5505]
ForEach e callbacks, podemos inserir uma função como argumento e essa função e chamada de callback, que é simplesmente funções que são passadas como argumento de outras funções ou métodos. Já o método forEach e que vai iterar sobre um array (forEach = "para cada"), funciona como método for mas de uma forma mais funcional e uma outra vantagem do forEach em relação ao for é que a declaração de uma função pode ser desacoplada.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
