### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5511]
- Strings serve para armazenar qualquer tipo de caractere em formato de texto.

- Deve- se armazenar strings com aspas simples ou duplas.

- As strings pode ser concatenadas através do sinal de +, ou seja pode unir uma ou mais strings.
- Os caracteres de uma strings pode ser acessadas pelo seu index, usando no final colchetes e o numero do index. Como no exemplo da aula fullName[0].
- Strings possuem métodos e propriedades.
- Uma propriedade das strings é a propriedade 'length', que retorna a quantidade total que caracteres de uma strings, deve- se se utilizada no final da strings com um ponto. Exemplo: fullName.length - retorna o valor total de caractere armazenada na variável.
- Um método é uma função que esta associada a algum objeto ou tipo de dado particular. Os metodos diferentes das propriedades executa ações, por exemplo o método 'toUpperCase( )' que retorna todos os caracteres em maiúsculo - fullName.toUpperCase( ), ficaria assim.
- Existem métodos que esperam argumentos por padrão, por exemplo o 'indexOf( )' - que localizar o caractere que é passado como argumento dentro da string. Exemplo: email.indexOf( '@' ).

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
