### ISSUE TITLE
Resumo da Aula Removendo to-dos - Aula 02-02 da etapa 09

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5514]
Uma boa maneira de remover to-dos é aproveitar o event delegation que vimos na aula 4 da etapa 5, onde falamos de DOM, então podemos adicionar um event listener em toda a ul, e quando um elemento da ul for clicado a função de callback do listener de evento vai ser executada e dentro dessa função verificamos se o evento clicado foi o ícone da lixeira. Então quando usamos o event delegatin para fazer esse tipo de operação isso faz o JS trabalhar menos o que otimiza sua performance.

```js
greatUl.addEventListener('click', event => {
    const closeElements = event.target
    
if(Array.from(closeElements.classList).includes('delete')) {
    closeElements.parentElement.remove()
}
})
```

**Comment by Roger-Melo** [comment]
Excelente @Hugones45, rumo à fluência! 🎯
