### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5515]
- Método lastIndexOf( ) - obtém o index do ultimo caractere passado como argumento no método.

- Método slice( ) - Esse método fatia ou recorta a string, recebendo 2 argumentos, o primeiro argumento recebe o index do inicio onde deve ser cortado e o segundo recebe o index do final do corte.

- Método replace( ) - Esse método vai substituir um caractere ou um conjunto de caractere por outro. Ele recebe 2 argumentos também, o primeiro e o caractere que quer substituir, e o segundo argumento e o caractere que vai entrar no lugar, ou seja, o novo caractere.

**Comment by Roger-Melo** [comment]
Show @LeonardoMoreiraDaSilva. Vamo que vamo, rumo à fluência! 🙌
