### ISSUE TITLE
Resumo da Aula 1,2 e 3 da etapa 01

### ISSUE THREAD

**Issue by GabrielSouza2** [roger-melo-treinamentos/curso-de-js-roger-melo#5518]
Resumo da aula 1
O objetivo do curso é:
Treinar desenvolvedore(a)s com pouca ou nenhuma experiência em JavaScript.
Treinar aspirantes a desenvolvedore(a)s que não conhecem nenhuma linguagem de programação e escolheram o JS.
Ambos tem o objetivo de atingir a fluência.

Resumo aula 2
O JS é uma linguagem universal que podemos usar em inúmeras aplicações na web, criação de websites, criação de robôs, servidores e muito mais.
Vamos focar no Front-End para melhorar a experiência do usuário, adicionar interatividade e etc.
Focará do zero até ao avançado.
Requisitos: o básico de HTML5 e CSS3.
Quando a fluência em JS chegar, você estará preparado para outras ferramentas.
Você vai se sentir desafiado e a síndrome do impostor pode aparecer.
Não será fácil mas valerá a pena.
Peça ajuda quando precisar.

Resumo aula 3
Baixar o vs code
Instalar as extensões: live server
Utilizar um local server para exibir suas aplicações no browser que você está utilizando.
Após as modificaões no vs code, você leventará um servidor local através do live server. Assim não precisará atualizar a página para cada alteração que fizer.
Com tudo configurado, você vai escrever seus primeiros códigos.
Instalar o f.lux para inibir a luz a azul.

**Comment by Roger-Melo** [comment]
Show @GabrielSouza2. Vamo que vamo, rumo à fluência! 🙌
