### ISSUE TITLE
Resumo da Aula Buscando e filtrando to-dos - Aula 02-03 da etapa 09

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5519]
Nesta aula vamos fazer o input de busca pelos To-dos filtrar os To-dos aparentes conforme digitamos as letras no buscador de To-dos.
Primeiro vamos pegar o input no DOOM. Como o input está dentro de um form com a classe form-search e temos que passar um seletor css como argumento do query.selector, fazemos:

```js
const inputSearch = document.querySelector('.form-search input')
```
Agora que obtmos a referencia do input vamos colocar nele um addEventListener.

```js
inputSearch.addEventListener('input', event => {
console.log(event.target.value.trim())
})
```

Se salvarmos dessa maneira e inserirmos um valor no imput, a cada caractere inserido a função do addEventListener é executada.

------------------------------------------------

Segundo passo, tentaremos filtrar os To-dos através do valor do input e adicionar classes nos To-dos que não correspondem ao valor do input. Mas antes de tentar filtrar os To-dos precisamos obter as referencias dos To-dos.

```js
inputSearch.addEventListener('input', event => {
      
      console.log(event.target.value.trim())

      console.log(todosContainer.children)

})
```
Se salvarmos e inserirmos um valor no input, vamos obter um HTML collection com todas as referencias de todos os elementos filhos da UL. E agora que obtemos a referencia desses elementos, a cada vez que o valor desse input for modificado queremos obter um array so com as strings dos To-dos que conrresongem ao valor do input, para isso podemos usar o metodo filter, apesar de não podermos usar ele nesse momento nessa expressão todosContainer.children, pois ela nos retorna um HTML collection e o metodo filter é um metodo de array, para dar certo então vamos transformar o HTML collection em um array com o metodo Array.from.

```js
inputSearch.addEventListener('input', event => {

      //console.log(event.target.value.trim())

     Array.from(todosContainer.children).filter(todo => {
      console.log(todo.textContent)
     })

})
```

Comentamos o console.log com o valor do evento e por motivos didaticos colocamos um outro console.log( ) dentro do todosContainer contendo o todo.textContent, que apesar de nas LIS o texto estar dentro de um span, como o texto do span ainda sim está dentro da LI, ele será obtido pela text.content.

-----------------------------

Nosso terceiro passo é exibir no console um boolean que indica se o valor inserido no input existe em alguma das lis. Para fazer isso vamos usar o método includes, ele funciona tanto para arrays como para strings.
Agora então vamos encadear na text.Content um includes e vamos passar como argumento o valor do input, vamos obter um boolean indicando se string do To-do contem o valor inserido no input.

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim()

     Array.from(todosContainer.children).filter(todo => {
      console.log(todo.textContent.includes(valorInput))
     })

})
```

--------------------------

Nosso quarto passo então será ao inves de inserir um boolean no console, vamos exibir as lis que contem o valor que foi inserido no input.
Vamos então substituir o console.log ( ) por um return, ou seja agora a invocacao do filter vai retornar um array só das LIS nas quais o texto contem um valor do input, e para vizualizar esse array, vamos armazenar a expressão em um a const const filteredLis, e abaixo vamos colocar um console.log(filteredLis)

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim()

   const filteredLis = Array.from(todosContainer.children).filter(todo => {
      return todo.textContent.includes(valorInput)
     })
     console.log(filteredLis)

})
```

Se salvarmos e inserirmos um w no input, vemos um array vazio por que nenhuma dessas LIS padrão contem uma LI que contem um w. Agora se colcoarmos um B, vamos no console um array que contem uma LI que contem o B maisculo, a LI do Assistir Breaking Bad.

----------------------------------

O quinto passo, como queremos adicionar uma classe CSS nas LIS que não contem o valor que foi inserido no input, ao inves de obter um array das LIS que contem um valor que foi inserido no input, queremos obter um array das LIS que não contem um valor que foi inserido no input. Para isso vamos inverter o boolean que a expressão está gerando, assim ele retorna um array só das LIS nas quais o texto não contém um valor do input. Usamos o operador NOT ( ! ) para isso.

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim()

   const filteredLis = Array.from(todosContainer.children).filter(todo => {
      return !todo.textContent.includes(valorInput)
     })
     console.log(filteredLis)
})
```

Se inserirmos agora um B maisculo no input, o array que o filter gerou não contem a LI que contem o B maisculo, e retornou para nos no console.log essas LIS. Agora para adicionarmos uma classe nessas Lis que queremos deixar momentaneamente invisivel, iremos usar um forEach, pois aqui precisamos executar um efeito colateral que neste caso é uma manipulação do DOM.

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim()

   Array.from(todosContainer.children)
   .filter(todo => !todo.textContent.includes(valorInput))
   .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
   })
})
```

Se salvarmos agora vemos como apenas a LI contendo Breaking Bad aparece na lista de To-dos.
E para fazermos as LIS que receberam a classe hidden voltem a aparecer nos implementamos um outros Array.from, mas com o incremento dos todos do forEach trocados.

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim()

   Array.from(todosContainer.children)
   .filter(todo => !todo.textContent.includes(valorInput))
   .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
   })

   Array.from(todosContainer.children)
   .filter(todo => todo.textContent.includes(valorInput))
   .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
   })
})
```

----------------------------------

Para finalizar e podemos obter tanto as LIS com strings minusculas ou maisculas no buscador de To-dos, nos fazemos as seguintes operações

```js
inputSearch.addEventListener('input', event => {

      valorInput = event.target.value.trim().toLowerCase()

   Array.from(todosContainer.children)
   .filter(todo => !todo.textContent.toLowerCase().includes(valorInput))
   .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
   })

   Array.from(todosContainer.children)
   .filter(todo => todo.textContent.toLowerCase().includes(valorInput))
   .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
   })
})
```

FINALIZAR CORRECAO E ERROS DE ORTOGRAFIA

**Comment by Roger-Melo** [comment]
Boa @Hugones45! Rumo a fluência!
