### ISSUE TITLE
Resumo da Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#552]
Bom dia ! 
Sei que não posto aqui meus resumos mais estou fazendo de uma forma diferente, tenho uma conta no notion e estou colocando tudo lá para ficar junto com outras anotações e resumos da área.
Segue a foto do resumo de function.
Tudo para praticar o ATER !
![IMG_20210424_114918](https://user-images.githubusercontent.com/65474069/115962922-e4595500-a4f3-11eb-8ea2-783207dce607.jpg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @Mlluiz39! ATER na veia! Rumo à fluência 🔥
