### ISSUE TITLE
Dúvida na forma de interpretação do exercício-09 nº 14.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5524]
### Etapa da aula

3

### Nome da aula

Utilizando callbacks e exercícios - Aula 02-05

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/803297

### Descreva a dúvida

Boa noite Roger, tudo bem com você ?
Nessa etapa surgiram alguma dúvidas mas com revisão seguindo o ATER, consegui resolver os exercícios até o nº 13 da forma que achei que fazia sentido pra mim, claro que com muito estudo ainda terei que melhorar bastante. Mas no exercício nº 14 eu travei!, pois li várias vezes voltei nas aulas mas não consegui interpretar como seria uma forma melhor de se resolver esse exercício, e a minha dúvida e exatamente em cima dessa questão, em qual seria a uma forma mais fácil de interpretar o que se pede em exercícios mais complicados como esse ? (pelo menos pra mim),  como esse é de funções a minha dificuldade e de assimilar uma coisa com outra e colocar no código, talvez isso possa ser uma questão um pouco simples ou boba, mas até no momento não consigo. Fico no aguardo para poder sanar essa dúvida que está me travando no decorrer do treinamento e desde já agradeço a atenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Dieison37!

A forma mais eficiente que eu conheço para interpretar a descrição de um desafio/exercício é ler toda a descrição e só então, dar um primeiro passo para resolver.

**Um problema de cada vez**.

Esse exercício, por exemplo, tem 7 itens na descrição (cada `-` é um item). Qual deles foi o primeiro em que vc travou?

Depois de identificar isso, eu focaria em resolver apenas esse item e esqueceria dos outros por enquanto. 

Vc também pode assistir a correção quando travar. Vc tem a opção de ver toda a correção do exercício ou apenas até o ponto em que travou. 

Não há problemas em precisar ver a correção, desde que vc siga o passo a passo que escrevi [neste post](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1801661) =)

**Comment by Dieison37** [comment]
Boa tarde Roger!

Certo vou seguir essa orientação mais a fundo, revisar mais vezes antes de
começar os exercícios.
Obrigado pelo retorno.


Att.
DIEISON L. VIEIRA.


Em qua., 16 de nov. de 2022 às 22:34, Roger Melo ***@***.***>
escreveu:

**Comment by Dieison37** [comment]
Roger!

Acabei de assistir a resolução dos exercícios e neste último (Exercício nº
14) onde surgiu a dúvida vc utilizou o switch para resolver e um detalhe
que notei
foi que eu tinha pensado nele, mas não tinha a menor idéia de como
utilizá-lo com uma função mas da forma que você inseriu juntamente com a
função
ficou um pouco mais claro, preciso revisar mais.

Só queria compartilhar esse detalhe.

Att.
DIEISON L. VIEIRA.


Em qui., 17 de nov. de 2022 às 14:47, Dieison Lemes Vieira <
***@***.***> escreveu:

**Comment by Roger-Melo** [comment]
Saquei. Tudo o que vc ver de novo pode ser combinado com o que foi visto antes =)

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
