### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5525]
- Para representar decimais em javascript colocamos ponto no lugar de virgula.

> Operadores aritméticos;

-  Divisão - operador: /

- Modulo (resto da divisão) - operador: %

- Multiplicação - operador: *

- Potenciação - operador: **

- Adição - operador: +

- Subtração - operador: -

> Ordem de precedência das operações:

1. parenteses;
2. expoentes ou raízes;
3. multiplicação e divisão;
4. adição e subtração;

> Operadores de incremento e decremento:

let postLikes = 10
postLikes = postLikes + 1
postLikes = postLikes - 1
postLikes = postLikes + 10

> shortrende

postLikes++
postLikes--
postLikes += 10

> NaN - not a number:

Acontecer quando tentamos fazer algum calculo que não faz sentindo.
Exemplo: 7 / "oi"

> Concatenação de string com números:

const likesMessege = 'O post tem ' + postLikes + ' likes.'
por baixo dos panos quando tentamos concatenar string com números o javascript converter o números em string.

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
