### ISSUE TITLE
Função de callback

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5527]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/813573

### Descreva a dúvida

@Roger-Melo

Boa tarde Roger, estou com muita dúvida no entendimento desse exercício, não consigo nem formular a pergunta.

  - Crie uma função que invoca uma função de callback recebida por parâmetro.  
    A invocação da função recebida por parâmetro deve receber um valor como  
    argumento;
  - Crie uma função que retorna o triplo de um número recebido por parâmetro;
  - Faça com que a invocação da função descrita no 1º item deste exercício (10)  
    resulte no triplo de 33.

```javascript

const callCallback = (value, callback) => {
  return callback(value)
}

const triple = number => number * 3

console.log(callCallback(33, triple))

```

Eu não entendi por que também o parâmetro callback invocou value no return e depois como no console.log ela conseguiu efetuar a multiplicação apenas invocando 33 e triple. Desculpe não saber formular  a pergunta da dúvida direito, mas ficou confuso pra mim.

Obrigado

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Callback costuma ter esse impacto inicial na mente, isso é comum.

Siga o passo a passo da issue abaixo e, quando terminar, me avisa aqui se está ficando mais claro =)

- [Passo a passo para entender callbacks](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574)

**Comment by Ale557333** [comment]
Então Roger, eu super entendi o exemplo, fiz o passo a passo, mas de fato esse exercício do triplo não entra na minha mente, não consigo entender o por que de retornar o callback invocando o value e também não entendo como ele faz a conta triple por debaixo dos panos no argumento do console.log.

**Comment by Roger-Melo** [comment]
> ### Não consigo entender o por que de retornar o callback invocando o value

Talvez nesse caso faça sentido vc visualizar no console o valor que o parâmetro `callback` está recebendo (sem invocá-lo) =)

Como vc visualizaria esse valor?

Testa e manda aqui o código que vc testou =)

@Ale557333

**Comment by Ale557333** [comment]
```javascript
const callCallback = (value, callback) => {
  return callback
}

const triple = number => number * 3

console.log(callCallback(33, triple))
```

Ele retornou assim no console.log:

number => number * 3

**Comment by Roger-Melo** [comment]
> ### Eu acho que o que não estou compreendendo é como que ele está associando o triple na função, sendo que nela o parâmetro é outro (number), e não está sendo colocado number no console.

![flow](https://user-images.githubusercontent.com/29297788/202747573-0fba7f0b-f730-43e6-bba1-04806a95e97f.jpg)

Vamos fazer um passo a passo do fluxo, como mostrado na imagem =D

1. A const `triple` é declarada, recebendo a função `number => number * 3`;

2. A const `triple` é inserida como 2º argumento da invocação da função `callCallback`;

3. Devido ao que aconteceu no passo 2, o parâmetro `callback` agora também armazena a função que `triple` armazena. 

Isto é, o parâmetro `callback` e a const `triple` agora armazenam a mesma referência da função em memória (`number => number * 3`);

4. Por isso, ao exibir o parâmetro `callback` no console, a referência da função `number => number * 3` é exibida.

Ou seja, se `callback` está armazenando uma referência de uma função, isso significa que a função pode ser invocada através de `callback`. Por isso `callback(value)` é o mesmo que `triple(value)`.

**Importante**

Parâmetro é a variável especificada na **declaração da função**: `(param) => {}`.

Argumento é o valor inserido na **invocação da função**: `func(5)` (5 é um argumento).

Não importa o nome do parâmetro da função. Ele é só uma variável e pode ter qualquer nome. O importante é entender que o valor que é inserido na invocação da função é armazenado no parâmetro declarado na função. Não importa o nome do parâmetro.

5. `callback(value)` é a mesma coisa que `triple(value)`. 

```javascript
const triple = number => number * 3
```

☝🏻 observe que ao ser invocada, a função `triple` irá retornar o resultado de `number` multiplicado por 3. 

Por isso, `return callback(value)` retorna o resultado de `33` (value) * 3.

Está ficando mais claro?

@Ale557333

**Comment by Ale557333** [comment]
Agora tudo fez mais sentido Roger. Acredito que essa parte salvou o entendimento pra mim: **_Devido ao que aconteceu no passo 2, o parâmetro callback agora também armazena a função que triple armazena._**

E nessa parte também fez desbloquear: **_callback(value) é a mesma coisa que triple(value)._**

Muito obrigado

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
