### ISSUE TITLE
Resumo da Aula Criando um objeto literal - Aula 01-03 da etapa 04

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5529]
Criando um objeto literal, um objeto e a junção de propriedades e uma propriedade e uma associação entre um nome e um valor. A maneira simples de criar um objeto literal e composto por um par de chaves "{}" que envolve uma ou mais propriedades. Cada propriedade segue o formato "nome: valor" e deve ser separado por vírgula.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
