### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5535]
Métodos são ações que são inseridos no objeto(coisas que ele pode fazer), método também é formado por um par(propriedade: valor). Métodos são funções que são criados dentro de um objeto.
=> funções criadas fora de um objeto são chamadas de funções;
=> funções criadas dentro de um objeto são métodos;
que em exência são a mesma coisa com nomes diferentes.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
