### ISSUE TITLE
Forma do implementação do exercício da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#5547]
### Etapa da aula

7

### Nome da aula

Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986667

### Descreva a dúvida

Olá Roger,

Originalmente escrevi o código dessa maneira conforme inserido abaixo e apliquei as formatações aprendidas na aula. Utilizei apenas um addEventListener e um if para tomar analisar o botão clicado. Gostaria de saber se escrever o código dessa forma pode ser considerada uma boa prática. Uma coisa que percebi é que tanto nesse código, quanto no que você implementou, ao se clicar duas vezes no botão de iniciar contagem, o contador começa a incrementar de maneira errada. Ele começa a somar de dois em dois números e três em três a medida de cliques que são efetuados. Gostaria de saber se há algum método que desabilita o evento de click para não permitir cliques sucessivos.

```js
const div = document.querySelector(".container");
const counterStarButton = div.querySelector("button").className;

let timer = null;

const incrementCounter = () => {
  const incrementedCounter = Number(div.firstElementChild.textContent) + 1;
  div.firstElementChild.textContent = incrementedCounter;
};

starAndEndCounter = (event) => {
  const buttonClicked = event.target.className;

  if (buttonClicked === counterStarButton) {
    timer = setInterval(incrementCounter, 1000);
    return;
  }
  clearInterval(timer);
  div.firstElementChild.textContent = "0";
};

div.addEventListener("click", starAndEndCounter);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MarioFilho1!

> ### Gostaria de saber se escrever o código dessa forma pode ser considerada uma boa prática.

Nesse primeiro momento, na minha opinião técnica, se preocupar muito com boas práticas não deve ser a prioridade. 

O mais importante num primeiro momento você ja fez, que é fazer funcionar. Conforme você for avançando no CJRM, vc pode voltar no código e melhorar o que fez =)

Mas apenas para não deixar sem resposta, a forma que vc fez é valida, porém tem uma desvantagem...

Se alguma classe for inserida no elemento `counterStarButton`, a validação não irá funcionar, por que as strings serão diferentes. 

A forma mais confiável de se identificar elementos e manipulá-los em JavaScript puro que eu conheço é usar o atributo `data-*`. Você verá no CJRM como usar esse atributo =)

---

> ### ...ao se clicar duas vezes no botão de iniciar contagem, o contador começa a incrementar de maneira errada.

Existem algumas formas de lidar com esse comportamento. Dá uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/3996#issuecomment-1172813573) e me diga aqui nessa issue se ficou mais claro =)

**Comment by MarioFilho1** [comment]
Olá Roger, 

Obrigado pelos esclarecimentos. 👍

**Comment by Roger-Melo** [comment]
Show, no que precisar é só abrir uma nova issue =)

Não sei se já entrou, mas enviei por email o link do Telegram do novo grupo de alunos do CJRM. Dá uma olhada em sua caixa de entrada =)

**Comment by MarioFilho1** [comment]
Olá Roger, não consegui entrar no novo grupo do telegram. O link enviado não está redirecionando
