### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5552]
- É possível converter um tipo de dado em outro usando uma função construtora e passando como argumento a string que precisa ser convertida. Por exemplo: score = Number(score).
- Existem também uma maneira de verificar o tipo de dado usando o operador typeof. Exemplo: typeof score. (obs.: existem situação que o typeof não vai ser a melhor maneira de verificar os tipos. aulas futuras)
- Existem outras funções construtoras que converter dados, por exemplo string(97) - que converter para string e boolean(10) - que converter valores para boolean, ou seja "true e false".

> Valores que retorna false no boolean:

1.  false;
2. 0;
3. "", '', ``;
4. null;
5. undefined;
6. NaN;

> Valores que retorna true no boolean:

1. Qualquer valor que não é false;

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
