### ISSUE TITLE
Dúvida no Exercício - 10 nº 02.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5554]
### Etapa da aula

4

### Nome da aula

Sobre os exercícios desta aula

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/819188

### Descreva a dúvida

```js
Bom dia Roger, tudo bem ?

Minha dúvida e no exercício 02 estou fazendo de uma forma (mas não sei se é a melhor) que vai imprimir no console o que o exercício está pedindo, mas na última parte que é para "sound", que recebeu uma função que retorna "X", não consegui encontrar uma forma que retorna essa função no console. As primeiras partes inseri interpolações, mas na parte da função travei aí fiz de uma forma mais manual, mas gostaria de saber uma forma mais legal de se fazer. 
 

02
  - Exiba a mensagem abaixo no console, substituindo os "X" pelas informações  
    corretas.
  Até aqui, o objeto "cat" possui as seguintes propriedades e valores: "name", que recebeu "X", "age", que recebeu "X", "color", que recebeu "X", "bestFriends", que recebeu um array com os itens "X" e "X", e "sound", que recebeu uma função que retorna "X".
*/


console.log(
  `Até aqui, o objeto "cat" possui as seguintes propriedades e valores: "name", que recebeu ${
    cat.name
  }, "age", que recebeu ${cat.age}, "color", que recebeu ${
    cat.color
  }, "bestFriends", que recebeu um array com os itens ${cat.bestFriends[0]} e ${
    cat.bestFriends[1]
  } e "sound", que recebeu uma função que retorna ${'Miauuuuuu'}.`
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Dieison37

> ## As primeiras partes inseri interpolações, mas na parte da função travei aí fiz de uma forma mais manual, mas gostaria de saber uma forma mais legal de se fazer

A forma que você fez na primeira parte das questões foi através de uma sintaxe chamada objeto.propriedade, por meio dela você pode acessar as propriedades dos objetos ao selecionar o nome do objeto e colocar o nome de sua propriedade após um ponto. Ex: `cat.name`. Essa forma é a recomendada para os alunos que chegaram nesse ponto do treinamento, então você está indo bem, boa! =)

Em relação a função, você pode fazer de forma bastante semelhante às propriedades anteriores, a ideia é a mesma, a diferença aqui é que para acessar o que uma função declarada dentro de um objeto retorna, você terá que invocá-la. Para visualizar isso, você pode invocar essa função dentro de um console.log. Nesse sentido, especificamente nessa questão, para obter o valor que o método sound está retornando, você vai inserir o nome do objeto "cat" e o nome do método que recebe uma função "sound", após isso, você vai invocar a função armazenada por "sound", ambos dentro de uma interpolação. Na sintaxe objeto.propriedade ficariam dessa forma: `cat.sound()`. Assim, você pode ver que no console.log, vai aparecer a frase que esse método retorna como o exercício pede =)

```js
// Trecho final do exercício usando o que foi explicado acima
console.log(`... "sound", que recebeu uma função que retorna "${cat.sound()}".`)
```

Está conseguindo entender melhor? Se restou alguma dúvida, pode chamar aqui novamente que iremos te ajudar =)

**Comment by Dieison37** [comment]
Boa tarde!

Esclarecido minha dúvida, mas faltou um detalhe que eu tinha esquecido era
um return para essa função pois até no momento antes de inserir essa
alteração estava retornando undefined, mas agora está certo imprimindo no
console o que o exercício pede.

Obrigado pelo suporte.

Att.
DIEISON L. VIEIRA.


Em seg., 21 de nov. de 2022 às 10:45, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
