### ISSUE TITLE
Exercício 04 Objetos 

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5556]
### Etapa da aula

4

### Nome da aula

Adicionando métodos - Aula 01-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/819188

### Descreva a dúvida

Boa tarde Roger!

Estou com dúvidas em como fazer mais uma função dentro desse objeto.  O exercício é a continuação do exercício 01 do objeto cat, onde agora irá pedir para fazer uma função que adicione mais amigos para  bestfriends.

  04

  - Crie uma função que adiciona um amigo(a) no array de amigos do gato;
  - Exiba o array de amigos no console para verificar se o novo amigo(a) foi  
    adicionado.

Meu objeto está assim desde o exercício 01:

```javascript
let cat = {
  name: 'Julio',
  age: 2,
  color: 'rajado',
  bestfriends: ['Maria Efigênia', 'raio laser'],
  sound: function (meow = 'miau') {
    return meow
  },
  addBestfriend: function (friend) {
    bestfriends.push(friend)
  }
}

console.log(cat.bestfriends(['pelúcia']))
```

Desde já agradeço,

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Essa é a mesma dúvida que vc podtou no grupo do Telegram?

Ela foi sanada?

**Comment by Ale557333** [comment]
Foi sim Roger! Muito obrigado.

**Comment by Roger-Melo** [comment]
Show! Vou fechar a issue então, mas no que precisar, é só abrir uma nova =)
