### ISSUE TITLE
Aplicação própria: simple_piano_js

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#5558]
### Etapa da aula

5

### Nome da aula

Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/853346

### Descreva a dúvida

@Roger-Melo

Olá, fiz essa pequena aplicação de um teclado visando por em prática o que aprendi até o momento no treinamento. 
Gostaria assim que possivel de dicas/feedback para meu aprimoramento. 

- Repositório: https://github.com/Bruno-Luna/simple_piano_js

- Deploy: https://bruno-luna.github.io/simple_piano_js/

Como foi-me orientado no feedback anterior deixei o nome das variáveis/funções em inglês, utilizei aspas simples para todo o conteúdo do código, bem como o addEventListener para escutar as interações em tela. 
Descobri que é possivel por meio da tag dialog, criar uma caixa de mensagem e manipula-lá via JS. Da mesma forma fiz uso do localStorage para armazenar nome do usuário. Ambas as funcionalidades acredito que verei no decorrer do treinamento, mas me esforcei para implementar por conta própria.

Agradeço desde já a atenção e retorno sobre a aplicação.

**Comment by MivlaM** [comment]
Olá @Bruno-Luna,

Recebemos a solicitação para a análise da aplicação que você fez, porém tem alguns pontos que gostaria de destacar. Olhamos seu cadastro na lista de alunos e vimos que você tem o bônus de análise de aplicações referentes às apresentadas no treinamento, a ideia que temos ao longo do treinamento, é que o foco para a análise está apenas nas quatro aplicações apresentadas. Essas aplicações são escolhidas minuciosamente para você aprender o que viu nas aulas anteriores e colocar em prática os conceitos das aulas. Portanto, partindo desse princípio, apesar de ter aberto uma exceção na sua issue anterior e analisado uma aplicação que não estava no treinamento, não poderei fazer o mesmo dessa vez, pois há conceitos que ainda não foram apresentados no ponto que você está no curso, nós ajudamos o aluno de acordo com o que ele vai aprendendo em sequência. 

Em contrapartida, se aceita uma sugestão, recomendo você seguir o treinamento conforme os conceitos são apresentados ao longo do mesmo, quando você estiver nas etapas mais avançadas, você vai ver que o tudo o que aprendeu servirá como base para construir as mais diversas aplicações JavaScript =)

**Comment by Bruno-Luna** [comment]
Compreendi, caro @MivlaM.

Desculpe-me. Agradeço pontualmente o esclarecimento.
