### ISSUE TITLE
Resumo da Aula Prototypes - Aula 03-07 da etapa 14

### ISSUE THREAD

**Issue by EussouShAd** [roger-melo-treinamentos/curso-de-js-roger-melo#5567]
# Prototypes
```js
function Student(name, email){
     this.name = name
     this.email = email

     this.login = function(){
         return `${this.name} fez login`
     }
```
O método login está declarado dentro da função construtora, isso não é bom para a aplicação, porque esse método vai ser declarado em cada objeto que essa função construtora criar. Dessa forma o método é inserido diretamente no próprio objeto, ou seja dois métodos que fazem exatamente a mesma coisa foram criados em espaços diferentes na memória. 
Para isso não acontecer, o método login pode ser criado uma vez, armazenar em apenas um espaço na memória e fazer com que todos os objetos criados pela função construtora tenham acesso a esse método através da referência, armazenando no ```prototype``` do objeto.
    Em JS todo novo objeto criado herda propriedades e métodos do seu prototype ou protótipo.
 ### Prototype 
É o objeto que armazena as propriedades e métodos que vão ser herdadas pelo novo objeto criado.
 - Todo tipo de objeto em JS tem um prototype, esse prototype do objeto armazena os métodos que o objeto pode acessar.
 - Quando um array é criado, a instância do array - [] - tem uma propriedade length, mas todos os métodos que podem ser executados no array estão armazenados no prototype e não no próprio array. 
 - Prototype é um objeto único, nativo da linguagem que é só referenciado quando um novo objeto é criado.
 - A propriedade prototype é tanto um getter como um setter.
 
Foram criados dois objetos que ocupam espaços diferentes na memória, os dois tem uma propriedade __proto__ e essa propriedade só referencia o prototype do array criado. O prototype do array criado é esse objeto array - Array(0) que a propriedade proto está referenciando, ou seja, a propriedade __proto__ de cada array - Array(0) - estão apontando para o mesmo prototype.

```js
arr1.prototype === arr2.prototype // true

arr1.__proto__ === arr2.__proto__   // true    
```
Isso significa que as duas propriedades proto dos dois arrays estão referenciando o mesmo prototype e quando um método é executado em um desses arrays, se o método não existir no próprio array o método vai ser buscado no prototype desse array.

A propriedade prototype é tanto um getter como um setter, ou seja, se no console, for inserido Array - porque quero
investigar o prototype do construtor de arrays da linguagem e inserir prototype, se investigar esse prototype, é
possível ver todos os métodos possíveis de ser usado em array.
```js
Array.prototype
```
Então nesse caso a propriedade prototype foi usada como um getter, foi obtido o prototype de arrays e isso pode ser
feito para qualquer tipo de objeto.

O método login será adicionado no prototype dos objetos que a função vai criar, usando a propriedade prototype
será usada como um setter, ou seja, será atribuído para prototype fora da função construtora, um método que será
adicionado no prototype dos objetos que a função construtora criar.
```js
function Student(name, email){
    this.name = name
    this.email = email
}

//Declarando um método no `prototype` dos objetos que a função construtora vai criar:
Student.prototype.login = function(){
     return `${this.name}` 
//  o this representa o objeto no qual esse método login vai ser executado, que é o objeto que a função construtora criar.
}
const eussoushad = new Student('Eussoushad', 'eussoushad@gmail.com')
console.log(eussoushad)
````
Quando classes são utitlizadas, os métodos não são declarados fora da classe.
```js
class Student{
    constructor(name, email){
        this.name = name
        this.email = email
    }

    comment(){ 
        return `${this.name} comentou`
    }
}

const eussoushad = new Student('Eussoushad', 'eussoushad@gmail.com')
console.log(eussoushad .comment()) 
console.log(eussoushad)
```
O método comment está inserido no prototype, ou seja, classes fazem a atribuição ao prototype dos objetos automaticamente, então não é preciso declarar diretamente os métodos no prototype dos objetos como quando são as funções construtoras são utilizadas.

Se esquecer da propriedade prototype na hora de declarar um método no prototype?

Se uma propriedade for declarada numa função construtora e atribuir uma função diretamente para essa propriedade, estará sendo declarado um método estático. Método estático é um método que ao invés de ser declarado no prototype dos objetos que a função construtora cria é declarado diretamente na função construtora e obviamente é invocado através da referência da função construtora.

Quando vai ser útil fazer a declaração de um método estático ao invés de declarar um método no prototype dos objetos?
- Vai ser útil quando for preciso declarar um método utilitário. 
- Método utilitário é um método que pode ser útil em situações frequentes na aplicação.

Exemplo:
Declarando um método estático na função construtora Student e esse método vai formatar a string
para que seja armazenada num banco de dados e por algum motivo essa string deve ser armazenada
com todos os caracteres maiúsculos e com underscores ao invés de espaços em branco.

```js
function Student(name, email){
     this.name = name
     this.email = email
}

Student.formatToDataBase = function(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}
/*
 Como esse método é estático ao invés de ser declarado no prototype dos objetos que a função construtora
 cria, como a função construtora Student também é um objeto, se abaixo inserir um console.log()... 
*/

const eussoushad = new Student('Eussoushad', 'eussoushad@gmail.com')
console.log(Student.formatToDataBase('string para banco de dados')) //STRING_PARA_BANCO_DE_DADOS
```
E se investigar um dos objetos criados pela função construtora, esse método não existe no prototype, muito menos no próprio objeto, pois é um método estático, ele só existe na função construtora.

Para visualizar o método Student como objeto, pode ser usado o método dir do console
```js
 console.dir(Student)
```
Será exibido as propriedades e métodos que essa função construtora tem e uma dessas propriedades é o método formatToDataBase.
```js
class Student{
     constructor(name, email){
         this.name = name
         this.email = email
     }

     comment(){ 
         return `${this.name} comentou`
     }
    
   //Declarando um método estático na classe
    static formatToDataBase(aString){
     return aString.toUpperCase().replaceAll(' ', '_')
    }
}

const eussoushad = new Student('Eussoushad', 'eussoushad@gmail.com')
console.log(Student.formatToDataBase('string para banco de dados'))
console.dir(Student)
```
O formatToDataBase está declarado no objeto ao invés de ser declarado nos objetos que a classe cria.

O formatToDataBase tem uma propriedade name que armazena o nome do método, se for executado no console.log() a propriedade formatToDataBase.name, a string com o nome do método é retornada:
```js
console.log(Student.formatToDataBase.name) //formatToDataBase.
```
Porém, o mesmo não acontece numa função construtora.
```js
function Student(name, email){
     this.name = name
     this.email = email
}

Student.formatToDataBase = function(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}

const eussoushad = new Student('Eussoushad', 'eussoushad@gmail.com')
console.log(Student.formatToDataBase.name) 
```
A propriedade do método armazena uma string vazia, ou seja, quando um método é declarado a sintaxe
de abreviação de function declaration:
```js
static formatToDataBase(aString){
     return aString.toUpperCase().replaceAll(' ', '_')
}
```
o nome do método - formatToDataBase - é automaticamente atribuído a propriedade name dele.

Mas quando o método com essa sintaxe de function declaration:
```js
Student.prototype.login = function(){
    return `${this.name} fez login`
}
```
Está sendo declarado explicitamente que a função não tem nome, é anônima. Se executar Student.formatToDataBase no console.dir():
```js
console.dir(Student.formatToDataBase)
```
A propriedade name da função recebeu uma string vazia.

A propriedade name agora armazena o nome de função.

Não é recomendado em métodos que usam function declarations sejam anônimos.

### Métodos estáticos:
```js
Student.formatToDataBase = function formatToDataBase(aString){
   return aString.toUpperCase().replaceAll(' ', '_')
}
```
Podem ser substituídos por simples funções:
```js
function formatToDataBase(aString){
    return aString.toUpperCase().replaceAll(' ', '_')
}

**Comment by Roger-Melo** [comment]
Excelente @EussouShAd rumo à fluência! 🎯
