### ISSUE TITLE
Sintaxe do exercício de objetos

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5568]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/824585

### Descreva a dúvida

@Roger-Melo

Boa tarde Roger.
Eu fiquei com dúvida sobre a sintaxe do exercício 09, não entendo por que foi colocado esse return obj[type]. O que me confundiu na verdade foi esse [type] em colchetes.

  09

  - Crie uma função que recebe um parâmetro 'type';
  - Dentro da função, crie um objeto com as seguintes propriedades:
    - null, que recebe a mensagem 'Seta, explicitamente, uma variável sem valor.'
    - undefined, que recebe a mensagem 'Representa um valor não-setado.'
    - object, que recebe a mensagem 'Arrays, Datas, Objetos literais, Funções, etc.'
  - Se o valor que o parâmetro type receber corresponder à alguma das 3  
    propriedades, retorne a mensagem que a propriedade armazena;
  - Teste a função, exibindo no console a mensagem de cada propriedade.
  
```javascript
const whatTypeIs = (type) => {
  let obj = {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }
  
  return obj[type]
}

console.log(whatTypeIs('null'))
```

Uma outra dúvida boba que tenho é quando eu devo colocar o return das funções, percebo que alguns vão antes de fechar as chaves, umas vão depois.

Agradeço desde já!.

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

> ### Eu fiquei com dúvida sobre a sintaxe do exercício 09, não entendo por que foi colocado esse return obj[type]. O que me confundiu na verdade foi esse [type] em colchetes.

Dá uma olhada [nessa](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2633#issuecomment-1002353936) e [nessa](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563#issuecomment-999110064) resposta e se restar alguma dúvida, pode comentar aqui abaixo =)

---

> ### Uma outra dúvida boba que tenho é quando eu devo colocar o return das funções, percebo que alguns vão antes de fechar as chaves, umas vão depois.

Não existe dúvida boba =)

Eu não sei se entendi bem a sua dúvida...

Vc usa o return sempre que precisa retornar um valor e parar a execução da função naquele ponto. 

No exemplo que vc postou acima, o return está dentro do bloco da função. A `}` que está acima dele é o fechamento da chave do objeto. 

O fechamento do bloco da função está abaixo do `return`.

Explica mais pra eu entender melhor a sua dúvida e te ajudar =)

**Comment by Ale557333** [comment]
Oi Roger tudo bom? Muito obrigado, eu entendi perfeitamente agora tudo!!! Sobre o return, agora entendi quando você falou sobre o bloco, eu tinha me confundido.

Um abraço.

**Comment by Roger-Melo** [comment]
Nesse último exemplo que vc postou não existe return (explicitamente). 

Dentro da função, `cat.bestfriends.push(friend)` será executado e a função não vai retornar valor.

Por baixo dos panos ela vai retornar `undefined`, pq toda função que não retorna valor, retorna `undefined`. Mas nesse caso, isso não importa.

A função `addFriends` iria retornar valor se você usasse a palavra-chave `return` ou usasse o retorno implícito da arrow function:

```javascript
const addFriends = (friend, cat) => {
  return cat.bestfriends.push(friend)
}

// ou

const addFriends = (friend, cat) => cat.bestfriends.push(friend)
```

Nos dois exemplos acima, ao ser invocada, a função `addFriends` irá executar `cat.bestfriends.push(friend)` e em seguida, irá retornar o valor que o `push` retornou =)

@Ale557333

**Comment by Ale557333** [comment]
Obrigado Roger!
