### ISSUE TITLE
Dúvida sobre como usar o this e quando ele é necessário.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5569]
### Etapa da aula

4

### Nome da aula

A palavra-chave this - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/824589

### Descreva a dúvida

Boa noite Roger!
```js
Acabei de assistir a aula novamente sobre o this e não consegui entender como ele é contextualizado no código referente ao objeto declarado, ele é somente  usado no console.log(`${}`) utilizando interpolação ? ou existe uma forma mais simples de utilizar ? sempre é também utilizado em function declaration ?. Vi e revi a aula mais ainda não consegui assimilar como ele é utilizado, ainda não está claro pra mim.

let user = { 
  name: 'Joao',
  age: 31,
  email: 'joaocardoso@gmail.com',
  city: 'São Paulo',
  blogPosts: ['Empadão de frango', '4 receitas de purê de batata'],
  login () {
    console.log('Usuário logado')
  }, 
  logout () {
    console.log('Usuário deslogado')
  },
  logBlogPosts () {
    console.log(`${this.name} escreveu os seguintes posts:`)

    this.blogPosts.forEach(post => {
      console.log(post)
    })
  }
}

user.logBlogPosts()
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Dieison37

Essa aula foi apenas uma introdução ao this, você vai entender melhor o comportamento do `this` conforme for avançando no treinamento, até lá, não se preocupe em querer entender todo tipo de particularidade do `this`, é algo que você vai entendendo com o tempo. Por enquanto, nesse momento, é necessário que você entenda apenas o básico, que é o que eu vou te mostrar aqui.

Vou te mostrar um mini-exemplo com um passo a passo de como um método pode adicionar um item em um array [1,2,3] do objeto através do this. Esse exemplo é fundamental para você entender como que funciona o this, ok? Certo, então vamos lá!

Primeiramente, vamos criar uma const `obj` que vai armazenar um objeto.

```js
const obj = {
 
}
```

Agora, vamos criar uma propriedade chamada `numberSequence` para esse objeto, essa propriedade armazenará um array com três números: 1, 2 e 3.

```js
const obj = {
  numberSequence: [1, 2, 3]
}
```

Feito isso, agora vamos adicionar um método para esse objeto, nas aulas, você viu como é criado um método dentro de um objeto, certo? Pois então, o comportamento do `this` varia da function declaration para os outros diferentes tipos de funções. Mas não se preocupe com isso agora, isso será abordado em aulas futuras. Por enquanto, vamos seguir como foi mostrado nesse ponto do treinamento, vamos criar um método `addToArr` por meio da function declaration:

```Js
const obj = {
  numberSequence: [1,2,3],
  addToArr: function (){
    
  }
}
```

Tudo ok até aqui? Se sim, vamos prosseguir! =)

A lógica que quero que esse método tenha é a seguinte, vamos adicionar um novo número para esse array armazenado pela propriedade `numberSequence`. Para isso, precisamos acessá-la. Lembra da sintaxe objeto.propriedade? Então, é possível usar o próprio objeto `obj` para acessar essa propriedade, poderiamos usar `obj.numberSequence` mas isso não é o recomendado, o motivo disso é assunto para um outro momento. Portanto, até lá, peço que você evite fazer isso e use a abordagem do `this`.

Dentro de um método declarado na forma de uma função tradicional (que foi a que nós usamos e que usa a palavra-chave `function`), o `this` referencia o objeto no qual a invocação do método foi encadeado. No exemplo da aula, o this referenciou o objeto `user`. Nesse caso, o `this` vai referenciar o `obj`.

```js
const obj = {
  numberSequence: [1,2,3],
  addToArr: function(){
    this.numberSequence // O this referencia obj
  }
}
```

Feito isso, vamos continuar com a nossa lógica aqui. Para adicionar um novo número em `numberSequence`. O método vai receber num como parâmetro e vamos colocar esse número recebido como parâmetro na `numberSequence` ao encadear o método push na expressão. O método push vai receber num como parâmetro que é o numero que iremos passar como argumento na hora que formos invocar esse método.

```js
const obj = {
  numberSequence: [1,2,3],
  addToArr: function(num){
    this.numberSequence.push(num)
  }
}
```

Por fim, vamos invocar esse método. Ele vai receber como argumento o número 4

```js
obj.addToArr(4)
```

Agora, você pode visualizar o objeto no console.log. O console.log é usado nas aulas apenas para você conseguir visualizar os valores. Respondendo a um de seus questionamentos acima, você pode fazer o que quiser com o `this` dentro de uma função, ele não necessariamente precisa aparecer num console.log.

Se você quiser visualizar o objeto com mais um número adicionado no array armazenado por `numberSequence`. O código completo ficaria assim:

```js
const obj = {
  numberSequence: [1,2,3],
  addToArr: function(num){
    this.numberSequence.push(num)
  }
}

obj.addToArr(4)

console.log(obj)
console.log(obj.numberSequence)
```

O this é um assunto que vai ser mais aprofundado mais adiante no treinamento. Por enquanto, você está conseguindo compreender melhor o que mostrei? Se restou alguma dúvida, pode escrever por aqui que eu te ajudo =)

**Comment by Dieison37** [comment]
Boa tarde Mivla!

Ficou mais claro um pouco agora. Só me tira outra dúvida o this é melhor
ser usado com o método push por padrão ou é somente em alguns casos ?





Att.
DIEISON L. VIEIRA.


Em qui., 24 de nov. de 2022 às 11:18, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Eu usei o método push junto com o `this` por motivos didáticos nesse exemplo. Você pode usar outro método junto com o `this` também, vai depender do que você quer fazer, o método só precisa ser condizente com a lógica que você quer elaborar.

**Comment by Dieison37** [comment]
Boa noite!

Entendido, obrigado pelo suporte.


Att.
DIEISON L. VIEIRA.


Em qui., 24 de nov. de 2022 às 14:04, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
