### ISSUE TITLE
Resumo da Aula Tipos de referência vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5583]
Tipos de referência vs tipos primitivos, a diferença entre eles está na forma que são armazenados na memória. Quando se atribui a esse tipo uma variável ou constante esse valor primitivo é armazenado na stack (tradução: pilha) é uma pilha de diferentes valores na memória. E quando se cria um tipo de referência como um objeto literal ou um array, vai ser armazenado no heap ( tradução: amontoado) que tem mais espaço para armazenar objetos maiores e mais complexos.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
