### ISSUE TITLE
Dúvida em qual método utilizar no Exercício - 12 nº 02.

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5589]
### Etapa da aula

4

### Nome da aula

Tipos de referência vs Tipos primitivos - Aula 03-04

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/831889

### Descreva a dúvida

```js
Boa noite Roger tudo bem ?

Estou tentando resolver o exercício - 12 nº 02 mas não estou conseguindo, tentei usar o método forEach para iterar sobre cada item do array mas não dá certo, tentei várias vezes e nada e agora deu um branco total.

/*
  02
  - No objeto abaixo, implemente um método que exibe a seguinte mensagem no 
    console:

    Vídeos recentes de Roger Melo:
    Introdução ao TDD - Parte 02 | JavaScript | Jest
    Introdução ao TDD | JavaScript | Jest
    Higher-order Functions | JavaScript
  
  - As 4 linhas da mensagem, podem ser exibidas separadamente.
*/

const youtubeUser = {
  name: 'Roger Melo',
  chanelUrl: 'https://www.youtube.com/channel/UCmjDevp9Y8r-qi-xueD3Izg',
  videos: {
    total: 111,
    recentVideos: [
      { title: 'Introdução ao TDD - Parte 02 | JavaScript | Jest', length: '28:28' },
      { title: 'Introdução ao TDD | JavaScript | Jest', length: '19:29' },
      { title: 'Higher-order Functions | JavaScript', length: '47:38' }
    ]
  },
  about: {
    description: '🔥 Ensino as pessoas a alcançarem a fluência em JavaScript! 🔥',
    socialNetworks: {
      twitter: 'https://twitter.com/rogermelodev',
      gitHub: 'https://github.com/Roger-Melo'
    },
    country: 'Brasil'
  }
}


```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Dieison37

Você pode postar o código das suas tentativas aqui? Isso faz com que eu entenda em qual ponto você está tendo problemas e assim possa te ajudar com mais precisão =)

**Comment by Dieison37** [comment]
Oi, bom dia!

const youtubeUser = {
  name: 'Roger Melo',
  chanelUrl: 'https://www.youtube.com/channel/UCmjDevp9Y8r-qi-xueD3Izg',
  videos: {
    total: 111,
    recentVideos: [
      { title: 'Introdução ao TDD - Parte 02 | JavaScript | Jest', length: '
28:28' },
      { title: 'Introdução ao TDD | JavaScript | Jest', length: '19:29' },
      { title: 'Higher-order Functions | JavaScript', length: '47:38' }
    ]
  },
  about: {
    description: '🔥 Ensino as pessoas a alcançarem a fluência em
JavaScript! 🔥',
    socialNetworks: {
      twitter: 'https://twitter.com/rogermelodev',
      gitHub: 'https://github.com/Roger-Melo'
    },
    country: 'Brasil'
  }
}
this.youtubeUser.forEach( video => {
  console.log(`${video.title}`)
})


Tentei fazer dessa forma, contextualizando com o this e iterando com o
forEach, mas retorna um erro;

[image: Capturar.PNG]


Att.
DIEISON L. VIEIRA.


Em qui., 1 de dez. de 2022 às 08:34, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Olá @Dieison37

## Estou tentando resolver o exercício - 12 nº 02 mas não estou conseguindo, tentei usar o método forEach para iterar sobre cada item do array mas não dá certo, tentei várias vezes e nada e agora deu um branco total.

O `forEach` de fato é usado nesse exercício, porém você o usa na lógica após acessar as propriedades do objeto por meio do this. Nesse exercício em questão, a ideia é que antes de tudo isso, você vai criar um método dentro do objeto `youtubeUser`, e dentro desse método, vai inserir um código responsável para exibir a mensagem solicitada no texto do exercício. Para que fique mais claro para você, sugiro que siga o raciocínio acompanhando as instruções e escrevendo as linhas de código que eu mostrar aqui na sua máquina. O primeiro passo é criar um método `getRecentVideos` dentro desse objeto, esse método terá um console.log com a frase escrita no enunciado.


```js
getRecentVideos (){
  console.log(`Videos recentes de ${this.name}`)
}
```

No código acima, como esse método `getRecentVideos` é uma function declaration, quando usamos o `this` dentro desse método, o `this` vai referenciar o próprio objeto `youtubeUser`, lembra? Por agora, tenha esse princípio em mente. Então, por meio dessa característica, podemos exibir o frase do enunciado de forma mais dinâmica. 

Feito isso, se a ideia é a de exibir um vídeo recente em cada linha do console, podemos iterar pelo array que a propriedade `recentVideos` está armazenando. Então, sabendo disso, para ter acesso a essas propriedades, vamos usar a sintaxe objeto.propriedade. A ideia aqui, é acessar a propriedade `videos` por meio de this.videos (que é a propriedade videos do objeto) e depois, vamos usar a mesma estratégia novamente para acessar a propriedade `recentVideos`. Se você exibir `this.videos.recentVideos` no console.log, você obtem o array que a propriedade `recentVideos` está armazenando. Agora, com esse array obtido, vamos iterar por ele. Para isso, usaremos o método `forEach` que recebe uma função com um parâmetro vídeo que representará cada objeto do array, e dentro dessa função, vamos exibir o título de cada vídeo no console. Por fim, basta invocar a função. O código seria mais ou menos assim: 

```js
const youtubeUser = {
  name: 'Roger Melo',
  chanelUrl: 'https://www.youtube.com/channel/UCmjDevp9Y8r-qi-xueD3Izg',
  videos: {
    total: 111,
    recentVideos: [
      { title: 'Introdução ao TDD - Parte 02 | JavaScript | Jest', length: '28:28' },
      { title: 'Introdução ao TDD | JavaScript | Jest', length: '19:29' },
      { title: 'Higher-order Functions | JavaScript', length: '47:38' }
    ]
  },
  about: {
    description: '🔥 Ensino as pessoas a alcançarem a fluência em JavaScript! 🔥',
    socialNetworks: {
      twitter: 'https://twitter.com/rogermelodev',
      gitHub: 'https://github.com/Roger-Melo'
    },
    country: 'Brasil'
  },
  getRecentVideos (){
    console.log(`Videos recentes de ${this.name}`)

    this.videos.recentVideos.forEach(video => console.log(video.title))
  }
}

youtubeUser.getRecentVideos()
```

Ficou mais claro? Se você estiver com dificuldade nesse conteúdo referente ao this e às propriedades do objeto, sugiro que revise a etapa 04 por completo. Qualquer coisa, se tiver restado alguma dúvida, comente abaixo que eu te ajudo =)

**Comment by Dieison37** [comment]
Sim, estou com um pouco de dificuldade onde inserir o this e forEach, mas
depois desse conceito explicado aqui ficou melhor pra entender e irei fazer
como você orientou vou revisar o conteúdo.

Obrigado pelo suporte.


Att.
DIEISON L. VIEIRA.


Em qui., 1 de dez. de 2022 às 13:11, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Ok! Quando você travar assim, você pode assistir a correção, desde que você siga o passo a passo que está no post da etapa 01. Não tem problema você ter que ver a aula de correção, mas quando isso for necessário, solicito que você siga o que está escrito neste [post](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1801661)

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
