### ISSUE TITLE
Resumo da Aula A condicional if - Aula 02-02 da etapa 02

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5592]
- If - são estruturas condicionais que executa um bloco de código caso a condição seja verdadeira, entretanto executa apenas uma vez, se a condição for falsa o código não será executado. Sintaxe:

- if (Aqui vai a condição){
aqui vai o bloco de código para ser executado.
}

**Comment by Roger-Melo** [comment]
Boa @LeonardoMoreiraDaSilva rumo à fluência! 🔥
