### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06 (exercício 17)

### ISSUE THREAD

**Issue by andersonpereiragithub** [roger-melo-treinamentos/curso-de-js-roger-melo#5599]
/*
  01

  - No envio do form, faça com que a página não seja recarregada.

```js
const form = document.querySelector('form')

form.addEventListener( 'submit', e => {
  e.preventDefault()
})
```
  02

  - No envio do form obtenha, através do objeto event, o texto inserido no input e exiba-o no console.
```js
const form = document.querySelector('form')

form.addEventListener( 'submit', e => {
  e.preventDefault()

 console.log(e.target.input.value)
})
```
  03

  - Teste uma regex que dá match com a palavra documentation" do parágrafo do index.html;
  - Exiba no console o boolean no qual este teste resulta.
```js
const p = document.querySelector('p')
const regexTest = /documentation/ ou /[a-z]{13,}/

const match = regexTest.test(p.textContent)
console.log('O resultado do REGEX foi: ' + match)
```
  04

  - Escreva uma regex que dê match com a palavra "B99" da string abaixo;
  - A regex não deve conter (literalmente) os caracteres B99;
  - Teste se o match aconteceu e exiba o resultado no console.
```js
const B99message = 'E o Terry Crews faz tudo, inclusive tocar a abertura de B99 na flauta'

const pattern = /[A-Z0-9]{3}/
const result = pattern.test(B99message)
console.log('O resultado do REGEX foi: ' + result)
```
  05

  - Modifique (manualmente) o valor que a const word armazena para que o  
    resultado do teste entre a regex e a string exibido no console seja true.
```js
const word = 'NASA'

const NASARegex = /^[A-Z]{4,}$/
const NASAResult = NASARegex.test(word)

console.log(NASAResult)
```
  06

  - No envio do form, se o valor inserido no input conter, no mínimo, 7  
    caracteres, que podem ser quaisquer caracteres, exiba no console a mensagem
    "O valor inserido no input é válido =)";
  - Caso contrário, exiba "Valor inválido =(" no console.
  
  Exemplos:
    - "a[b@X7c" é um valor válido, pois contém 7 caracteres;
    - "jozeti" não é um valor válido, pois contém 6 caracteres.
```js
const text = /.{7,}/

form.addEventListener( 'submit', e => {
  e.preventDefault()
 
const isValid = text.test(e.target.input.value)

if (isValid) {
    console.log("O valor inserido no input é válido =)")
} else {
     console.log("Valor inválido =(")
   }
})
```
  07

  - Agora, no envio do form, faça com que o valor permitido contenha de 7 a 11 caracteres mas não contenha caracteres especiais. Apenas letras maiúsculas ou minúsculas e números serão permitidos.

  Exemplos:
    - "0xY79aYx54e" é um valor válido, pois contém 11 letras e números;
    - "eich_1961" não é um valor válido, pois contém um caractere especial.
```js
const text = /[a-zA-Z0-9]{7,11}/

form.addEventListener( 'submit', e => {
  e.preventDefault()
const isValid = text.test(e.target.input.value)
  if (isValid) {
    console.log("O valor inserido no input é válido =)")
  } else {
    console.log("Valor inválido =(")
  }
})
```
**==== CÓDIGO REFATORADO ===**
```js
const clearInput = () => {
  input.value = ''
  input.focus()    
}

const logMessage = message => {
  console.log(message)
  clearInput()
}

const hundleSubmit = e => {
    e.preventDefault()
    
    const regexText = /[a-zA-Z0-9]{7,11}/
    const input = e.target.input
    const isAValid = regexText.test(input.value)
  
    if (isAValid) {
      logMessage("O valor inserido no input é válido =)")
      return
    } 
    
    logMessage("Valor inválido =(")
  }
form.addEventListener( 'submit', hundleSubmit)
```

**Comment by Roger-Melo** [comment]
Excelente @andersonpereiragithub, rumo à fluência! 🎯
