### ISSUE TITLE
Etapa 09, Aplicação: To-do list - Aula 02-03

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#56]
Roger minha dúvida surgiu após a segunda etapa da filtragem, que era filtrar a referência de todos os to-dos que continham o mesmo valor do input. Por que a engine do JavaScript retorna ```true``` quando eu verifico se uma string vazia está inclusa em uma string que tem seus devidos caracteres ? Como no exemplo abaixo:

```js
'Gabriel'.includes('') // True
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

Uma string vazia sempre estará inclusa em qualquer string, independente de quantos caracteres ela tenha.

```javascript
''.includes('') // true
'a'.includes('') // true
```

Isso acontece por que o `includes`, por razões de consistência da linguagem, por baixo dos panos, tem a mesma funcionalidade do `indexOf`. E o `indexOf` sempre dá match entre uma string vazia e outra string.

Se quiser realmente se aprofundar nessas razões, dê uma olhada [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf#Syntax), a partir de "Return value".

É um aspecto estranho da linguagem, mas não me recordo de ter problemas com esse tipo de caso. Acho que nunca precisei verificar se uma string vazia existe em uma string. Se é necessário testar se um valor é uma string vazia, posso usar o `strict equality operator`:

```javascript
'' === '' // true
'a' === '' // false
```

Você teve problemas com esse comportamento do includes?

@sou-gabriel

**Comment by sou-gabriel** [comment]
_Você teve problemas com esse comportamento do includes?_ Roger não obtive nenhum problema com esse comportamento, foi apenas algo curioso da linguagem que me despertou este questionamento. Mas, com tua resposta já foi sanado completamente esta questão. Obrigado =)
