### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5602]
- Uma alternativa para verificar múltiplos valores de uma variável ou constante e o (Switch).

- Sintaxe:
switch (variável para verificar) {
     case 'A':
         console.log('Voce tirou um A')
         break
default:
console.log('Nota invalida')
}
Obs.: Pode ser inserido vários case para verificação.

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
