### ISSUE TITLE
Resumo da Aula O que é o DOM - Document Object Model - Aula 01-06 da etapa 05

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5603]
O que é DOM - Document Object Model ? 
O DOM é criado pelo browser e não faz parte da linguagem em si, quando um documento html e carregado no browser o mesmo cria o DOM para que seja possível interagir com esse documento html através do código JS e através do DOM é possível fazer coisas adicionar ou remover conteúdo de uma página. Uma vez criado esse documento, um objeto que modela esse documento. Esse objeto document contém  várias propriedades e métodos que dizem respeito ao documento html e que podem ser usados para interagir com esse documento que foi carregado no browser.

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
