### ISSUE TITLE
setTimeout() e o objeto window - Aula 02-02

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5604]
# setTimeout() e o objeto window - Aula 02-02

* **Esse resumo vai se basear em uma maneira de rolar a pagina para cima quando o usuário apertar no botão do formulário.**

## Oque é o `window`?
**Window é o objeto que existe no escopo global de uma aplicação. No javaScript sempre existe um objeto global em que todos os métodos e propriedades que você usa estão pendurados ( Exemplo: window.algumMetodoOuPropriedade )**

**No frontEnd o objeto global é o "`window`". Que representa a janela do browser.**

**Todos os métodos é propriedades estão armazenados no objeto `window`.**

## Forma de usar o window
Exemplo: 

```  js
Window.console.log('Console é um metodo do window')
```
> **Quando usamos um método ou propriedade do `window` nós não precisamos especificar o "`window`" antes da propriedade ou método.**

Exemplo:
``` js
console.log("Não preciso especificar o window")
```

### Console.log
**`console.log` é uma propriedade pendurada no "window".**

### Document.querySelector
**O `document.querySelector` também é um método pendurado no window.**

----------------------------------------
### SetTimeOut
**O `setTimeOut` executa uma função após uma certa quantidade de tempo especificada.**
``` js
setTimeOut(function => { }, 300)
```
**setTimeOut(`FUNÇÃO, MILISSEGUNDOS`)**

## ScrollTo
ScrollTo vai rolar a pagina para um determinado local.
`ScrollTo (X, Y)`

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos, rumo à fluência! 🎯
