### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by marcoferreiradev** [roger-melo-treinamentos/curso-de-js-roger-melo#561]
# Métodos de strings
````js
const email = 'mw.marcowilliam@gmail.com'
````

### lastIndexOf - Retorna a ultíma ocorrência do caractere passado como argumento no método 
````js
const lastIndexOfA = email.lastIndexOf('o')
````

### slice - Recorta uma string onde o primeiro argumento recebe a posição inicial e o segundo a posição final do recorte
````js
const emailSlice = email.slice(0, 15)
````

### replace - Substitui um caractere ou uma sequencia de caracteres, onde o primeiro argumento é o que vai ser encontrado na string para ser substituido pelo segundo argumento
````js
const emailReplace = email.replace('gmail', 'hotmail')
````

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa Marco William! Rumo à fluência! 🔥 

@marcoferreiradev
