### ISSUE TITLE
Quando utilizar o for loop dentro ou fora do bloco da função

### ISSUE THREAD

**Issue by Marcio-Ribeiro-44** [roger-melo-treinamentos/curso-de-js-roger-melo#5612]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803284

### Descreva a dúvida

Professor Roger, boa noite!
Verifiquei que na questão 04 o for loop foi usado dentro do bloco da função e na 05, fora.
Sempre que for gerar um novo array, o for loop ficará dentro do bloco da função?
Quando houver contagem, ele ficará fora?
Qual o critério/lógica que deve ser utilizado?
Agradeço a atenção!

04
  - Comente o código acima, de forma que a string não seja mais exibida no  
    console;
  - Implemente uma função que retorna um novo array com as strings do array  
    "millennialWords" em letras maiúsculas;
  - Exiba o novo array no console, sem inserir um console.log() dentro da  
    função. 
```js
const millennialWords = [
  "lol",
  "yolo",
  "troll",
  "stalkear",
  "selfie",
  "influencer",
  "crush",
  "fitness",
  "hater",
  "bae",
  "random",
  "kawaii",
  "outfit",
  "mood",
  "fail",
];
const stringsMaiusculas = function (array = []) {
  let novoArray = []
  for (let i = 0; i < array.length; i++){
    const palavrasMaiusculas = array[i].toUpperCase()
    novoArray.push(palavrasMaiusculas)
  }
  return novoArray
}
const millennialWordsEmMaiusculas = stringsMaiusculas(millennialWords)
repeticao(millennialWordsEmMaiusculas)
```
05
  - Implemente uma função que retorna se um número é positivo;
  - Use essa função para descobrir quantos números positivos o array 
    "randomNumbers" possui;
  - Exiba a frase abaixo no console, inserindo as informações corretas.
  "O array "randomNumbers" possui XX números, sendo XX positivos e XX negativos."

```js
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3];
let contadorPositivo = 0
let contadorNegativo = 0
const numerosPositivos = function(numero = 0){
  return numero >= 1
}
for (let i = 0; i < randomNumbers.length; i++){
  let numeroPositivo = numerosPositivos(randomNumbers[i]) 
  if (numeroPositivo){
    contadorPositivo++
  }else {
    contadorNegativo++
  }
}
const array = `O array "randomNumbers" possui ${randomNumbers.length} números, sendo ${contadorPositivo} positivos e ${contadorNegativo} negativos."`
console.log(array)
```

@Roger-Melo
``

**Comment by Roger-Melo** [comment]
Olá @Marcio-Ribeiro-44!

> ### Sempre que for gerar um novo array, o for loop ficará dentro do bloco da função?

Não existe essa relação direta. Vai depender do que você quer/precisa fazer. 

No exercício 4, a ideia foi fazer com que o código responsável por criar e retornar o novo array ficasse contido dentro de uma função que ao ser invocada, retorna o novo array com as strings em letras maiúsculas.

Tem também um outro detalhe importante chamado escopo, que vai ser apresentado em breve à vc. 

Mas só pra não te deixar sem resposta, vou mostrar um exemplo mais simples envolvendo o local da declaração do array pra vc sacar a ideia.

```javascript
let numbers = []

function addTo () {
  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }
}

addTo()
console.log(numbers) // [1, 2]
```

Se vc testar o código acima, verá que após a invocação da função, ao invocar `console.log(numbers)`, é exibido que o array `numbers` contém 1 e 2. Certo?

Só que se antes do console.log você invocar a função mais uma vez, verá que ao invés de 1 e 2, o array contém 1, 2, 1 e 2.

```javascript
addTo()
addTo()
console.log(numbers) // [1, 2, 1, 2]
```

Isso acontece por que dentro da função `addTo`, você está reaproveitando a referência do array que foi declarado fora da função. 

Porém, se você declarar o array `numbers` dentro da função, vai ficar assim:

```javascript
function addTo () {
  let numbers = []

  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }
}

console.log(numbers) // Uncaught ReferenceError: numbers is not defined
```

Agora, vc não irá conseguir acessar `numbers` fora da função `addTo` (isso vai ser mostrado mais à frente, quando vc chegar na parte de escopos).

Então pra ter acesso à `numbers` fora da função, vc precisa retorná-lo:

```javascript
function addTo () {
  let numbers = []

  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }

  return numbers
}

console.log(addTo()) // [1, 2]
```

Observe que ao executar a função 1x, `numbers` armazenou `[1, 2]`. E mesmo que você execute a função 2x, `numbers` armazena `[1, 2]` 👇🏻

```javascript
console.log(addTo()) // [1, 2]
console.log(addTo()) // [1, 2]
```

Isso acontece por que após a primeira execução da função, o console.log é executado mostrando o retorno da função e o JS pensa "já que `numbers` não está mais sendo usado em outro lugar do código, posso eliminá-la da memória".

Então após a primeira execução da função, `numbers` que estava armazenando `[1, 2]` é eliminada da memória.

Em seguida, quando a função é invocada pela 2ª vez, a mesma coisa acontece. Uma let `numbers` é declarada na memória e depois que a função termina de ser executada, `numbers` é limpa da memória. Por isso, quando o array é declarado dentro da função, não importa quantas vezes ela for invocada, não vai haver reaproveitamento do array mas sim, uma nova declaração e depois remoção da memória.

Está ficando mais clara a diferença entre criar um novo array dentro de uma função e reaproveitar a referência de um array dentro da função?

---

Observe também que no exercício 5, ao contrário do exercício 4, vc não está criando um novo array (nem na função nem no loop). 

No loop, vc está apenas obtendo o número do array através da expressão `randomNumbers[i]`.

---

Não tem relação com sua dúvida, mas evite nomear funções como substantivos.

Ao nomear uma função como substantivo, não fica claro qual ação aquela função está executando.

O ideal é nomear suas funções como verbos =)

**Comment by Roger-Melo** [comment]
@Marcio-Ribeiro-44 marcando aqui para me certificar que vc será notificado, pois tinha fechado a issue sem querer ao comentar acima.

**Comment by Roger-Melo** [comment]
Olá @Marcio-Ribeiro-44!

> ### Sempre que for gerar um novo array, o for loop ficará dentro do bloco da função?

Não existe essa relação direta. Vai depender do que você quer/precisa fazer. 

No exercício 4, a ideia foi fazer com que o código responsável por criar e retornar o novo array ficasse contido dentro de uma função que ao ser invocada, retorna o novo array com as strings em letras maiúsculas.

Tem também um outro detalhe importante chamado escopo, que vai ser apresentado em breve à vc. 

Mas só pra não te deixar sem resposta, vou mostrar um exemplo mais simples envolvendo o local da declaração do array pra vc sacar a ideia.

```javascript
let numbers = []

function addTo () {
  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }
}

addTo()
console.log(numbers) // [1, 2]
```

Se vc testar o código acima, verá que após a invocação da função, ao invocar `console.log(numbers)`, é exibido que o array `numbers` contém 1 e 2. Certo?

Só que se antes do console.log você invocar a função mais uma vez, verá que ao invés de 1 e 2, o array contém 1, 2, 1 e 2.

```javascript
addTo()
addTo()
console.log(numbers) // [1, 2, 1, 2]
```

Isso acontece por que dentro da função `addTo`, você está reaproveitando a referência do array que foi declarado fora da função. 

Porém, se você declarar o array `numbers` dentro da função, vai ficar assim:

```javascript
function addTo () {
  let numbers = []

  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }
}

console.log(numbers) // Uncaught ReferenceError: numbers is not defined
```

Agora, vc não irá conseguir acessar `numbers` fora da função `addTo` (isso vai ser mostrado mais à frente, quando vc chegar na parte de escopos).

Então pra ter acesso à `numbers` fora da função, vc precisa retorná-lo:

```javascript
function addTo () {
  let numbers = []

  for (let i = 1; i <= 2; i++) {
    numbers.push(i)
  }

  return numbers
}

console.log(addTo()) // [1, 2]
```

Observe que ao executar a função 1x, `numbers` armazenou `[1, 2]`. E mesmo que você execute a função 2x, `numbers` armazena `[1, 2]` 👇🏻

```javascript
console.log(addTo()) // [1, 2]
console.log(addTo()) // [1, 2]
```

Isso acontece por que após a primeira execução da função, o console.log é executado mostrando o retorno da função e o JS pensa "já que `numbers` não está mais sendo usado em outro lugar do código, posso eliminá-la da memória".

Então após a primeira execução da função, `numbers` que estava armazenando `[1, 2]` é eliminada da memória.

Em seguida, quando a função é invocada pela 2ª vez, a mesma coisa acontece. Uma let `numbers` é declarada na memória e depois que a função termina de ser executada, `numbers` é limpa da memória. Por isso, quando o array é declarado dentro da função, não importa quantas vezes ela for invocada, não vai haver reaproveitamento do array mas sim, uma nova declaração e depois remoção da memória.

Está ficando mais clara a diferença entre criar um novo array dentro de uma função e reaproveitar a referência de um array dentro da função?

---

> ### Verifiquei que na questão 04 o for loop foi usado dentro do bloco da função e na 05, fora.

No exercício 5, vc não precisa invocar a função para que o loop seja executado. Por isso o loop foi posicionado fora da função.

Se colocar o loop dentro da função, o loop só vai ser executado se a função for executada. Código dentro de função só é executado se a função for executada (assim `doSomething()`).

---

Não tem relação com sua dúvida, mas evite nomear funções como substantivos.

Ao nomear uma função como substantivo, não fica claro qual ação aquela função está executando.

O ideal é nomear suas funções como verbos =)

**Comment by Roger-Melo** [comment]
> ### Ao declarar um variável FORA da função e quiser exibi-la no console, devo referenciá-la dentro da função, invocar a função e o console.log podendo REAPROVEITAR a variável.

Não. 

Pra exibir uma variável no console basta apenas invocar console.log. 

console.log não tem relação com reaproveitamento de variável. Ele serve apenas para você visualizar um valor no console.

Não sei se foi isso que chegou a confundí-lo, mas no exemplo `console.log(addTo())`, o console.log simplesmente está exibindo no console o valor que a invocação `addTo()` retornou. 

Como a invocação `addTo()` está retornando um array, o console exibe esse array no console. 

---

> ### Quando a variável for declarada DENTRO da função, é necessário retorná-la (RETURN) e invocar a função dentro do console.log sendo que a cada invocação, ocorrerá uma NOVA DECLARAÇÃO.

Uma variável declarada dentro de uma função deve ser retornada apenas se vc precisa fazer alguma com essa variável foca do bloco da função. 

No código abaixo, a `const` myConst foi declarada dentro do bloco da função `addTo`. Por isso, o console.log abaixo da função não consegue acessar myConst:

```javascript
function addTo () {
  const myConst = 'olá' // 👈🏻 declarada dentro do bloco ({}) da função
}

// 👇🏻 não há como acessar essa const fora do bloco
console.log(myConst) // Uncaught ReferenceError: myConst is not defined at app.js:5:13
```

Pra acessar myConst fora do bloco da função, vc precisa dar um jeito de fazer com que ela fique disponível fora do bloco. E uma forma de fazer isso é retornando myConst:

```javascript
function addTo () {
  const myConst = 'olá'
  return myConst
}
```

Esse `return` está dizendo que ao ser invocada (com os `()`), a função `addTo` irá retornar `myConst`. Ficaria assim:

```javascript
function addTo () {
  const myConst = 'olá'
  return myConst
}

addTo()
```

Pra visualizar o valor que a invocação `addTo()` retornou, aí vc pode usar o console.log:

```javascript
console.log(addTo()) // exibe 'olá' no console
```

> ### sendo que a cada invocação, ocorrerá uma NOVA DECLARAÇÃO

Sim. Se a declaração da const foi feita dentro da função, no término da execução da função, o JS limpa da memória o que está dentro da função que não será mais usado.

Está ficando mais claro?

@Marcio-Ribeiro-44

**Comment by Marcio-Ribeiro-44** [comment]
Muito obrigado, por enquanto!
Vou aproveitar para revisar desde o primeiro exercício até agora.
Antes de avançar para cada etapa, faço a revisão raio-x.
Quando eu travo em algum exercício, refaço quando vezes forem necessárias para massificar isso.
E sempre que possível, postarei minhas dúvidas, por mais simples que sejam.
Abraço!

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)
