### ISSUE TITLE
Resumo da Aula O que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5615]
- Funções são os principais conceitos de uma linguagem de programação, elas fazem parte do tipo object, cujo papel principal é permitir criar um bloco de código, que pode ser invocado posteriormente quantas vezes quiser. Sintaxe invocação: nomeFunção(  ).

- Podemos também passar valores para dentro da função e retornar um resultado ou fazer alguma coisa.

**Comment by Roger-Melo** [comment]
Excelente @LeonardoMoreiraDaSilva, rumo à fluência! 🎯
