### ISSUE TITLE
Resumo da Aula O método map - Aula 01-02

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5623]
# O método map - Aula 01-02

- `MAP` um método de array que pode usado quando você quiser gerar um `novo array` com a mesma quantidade de itens do array original só que com cada item transformado.
- O método vai percorrer por cada item do array e executar alguma transformação em cada um desses itens através da função que a gente passar como argumento pra ele, e ele vai retornar um novo array com esses itens transformados, ou seja, `ele não vai modificar o array original no qual ele foi encadeado`.

### Exemplo: 

``` js
const numbers = [1, 2, 3];

numbers.map((item, index, array) => {}) // Somente o item é obrigatório, o resto é opcional
numbers.map(item => {});
```
- A função que for passada no `MAP` vai ser executada para cada item do array(numbers).
- Todo o item que a função retornar vai ser adicionado como item desse novo array que o `MAP` vai gerar.`

-------------------------

### Exemplo:  Obtendo um novo array com cada numero do array(numbers) multiplicado por 2.
``` js
numbers.map((item) => item * 2); 
// Adicionamos o método MAP no array(Numbers) e criamos uma função que retorna item multiplicado por 2

const doubleNumbers = numbers.map((item) => item * 2); 
// Agora adicionamos a uma variável chamada doubleNumbers
// A variável vai receber o array criado pelo MAP que está recebendo os item da função.

console.log(doubleNumbers, numbers); // Mostrando no console o resultado.
console.log(numbers); // O array numbers permaneceu intacto, porque o MAP não altera o array original.
```
- A principal diferença entre `FOREACH` e o `MAP` é que o `MAP` retorna um valor.

-------------------------

### Exemplo: Colocando todos os produtos da loja com 50% de desconto
``` js
const prices = [20, 10, 30, 25, 15, 40, 80, 5] // Criando um array de produtos

const salePrices = prices.map(price => price / 2) 
// Criando uma função que vai dividir cada item do array por 2
// O método MAP vai retornar cada item dentro de um novo array que vai ser armazenado na variável "salePrices".

console.log(salePrices); // Mostrando o array no console.
```

------------------------

### Exemplo: Colocando todos os produtos com 50% de desconto
``` js
const products = [
  { name: "Mouse Sem Fio", price: 30 },
  { name: "Pen Drive", price: 25 },
  { name: "Cartucho de Tinta", price: 50 },
  { name: "Suporte Ergonômico para Notebook", price: 23 },
  { name: "Repetidor de Sinal Wi-Fi", price: 44 },
];

const saleProducts = products.map(product => { 
// Observe que o "product" não é uma copia do objeto, ele é o objeto em si, então qualquer alteração que for feita nele vai alterar o objeto do array original.
  if (product.price >= 30) {
    return { name: product.name, price: product.price / 2 };
  }

  return product;
})
```

**Comment by Roger-Melo** [comment]
Excelente @lucamacedos, rumo à fluência! 🎯
