### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5626]
Obtendo, adicionando, removendo e alterando classes CSS, depois de obter a referencia do elemento pelo document.querySelector('p'), para obter uma lista que esse elemento contem e pela propriedade classList e para adicionar uma classe em um elemento e usado a propriedade classList.add('error') e para remover uma classe e usado a classList.remove('error'). Para adicionar uma classe e usado classList.add('success').

**Comment by Roger-Melo** [comment]
Excelente @Dieison37, rumo à fluência! 🎯
