### ISSUE TITLE
Resumo da Aula A Aula Mais Importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by salvedojuliao** [roger-melo-treinamentos/curso-de-js-roger-melo#5627]
_Qual decisão importante eu tomei na minha via que não me deu um frio na barriga?_
------------------------------------------------------------------------------------------------------------------------------------

### 📌O que eu sou? Coelhinho 🐰ou Tartaruga 🐢?  
 🐰 Coelhinho de certa forma chega mais rápido, mas pode perder o foco. 
 🐢 Já a tartaruga vai bem devagar...mas pode virar pedra (parar). O lance é entender quem eu sou, saber meus pontos fracos e identificar quando esse ponto fraco me impede de ir para frente. Em resumo: começou NÃO PARA MAIS!
> Quando eu não aprendo, eu perco mais tempo no processo! 
- O curso não é uma corrida, é uma **Jornada!**

O conceito primordial para eu chegar na fluência do JS é **SEM PRESSA / SEM PAUSA**.  Começou? Então não pare mais!

 ## O curso é divido e **8 marcos:**

![marcos_jornada](https://user-images.githubusercontent.com/44206400/206937543-ce6ed25e-1041-4fb6-8b6f-78170ade5d88.jpg)

**MAS** Eu irei fazer o resumo tanto para dentro do treinamento, quanto para meu próprio **Github**

--------------------------------------------------------------------------------------------------------------------------------------------

- A ideia é focar no **CJRM** e usar o **MDN** (A fonte da verdade). Isso inclui fazer os exercícios das aulas primeiro e somete depois de um tempo (quando eu estiver criando minhas aplicações em JS sozinho) procurar exercícios de outros locais.

 ### Sobre os marcos:
- O **Alicerce** é a parte mais importante dos marcos!

 ### ⚡Revisão Raio-x:
> Se eu errar em algum exercício, preciso ver a correção e entender os princípios que estão envolvidos ali.

**ENTENDER** a resolução do exercício **NÃO É SUFICIENTE**
- Pois entender é **diferente** de **fazer**

1️⃣ **Passo 1**
**Depois** que eu resolver o exercício com o professor, eu vou apagar o código que eu implementei com ele durante a correção.

2️⃣ **Passo 2**
Implementar sozinho o código que ele mostrou sem olhar na correção. É aqui que eu irei executar de fato sozinho o raciocínio que ele mostrou na hora de corrigir.

3️⃣ **Passo 3**
Se eu **travar** na hora de fazer sozinho, eu devo executar um ou todos os seguintes passos:
1) Consultar as anotações que eu fiz durante a aula ou as anotações que eu fiz na etapa de teoria
2) Consultar o MDN
3) Procurar o ponto da aula que esclarece minha dúvida. 

**NOTE:** Assim que eu tirar a dúvida, é importante que eu apague todo o código e implemente sozinho do tudo **DO ZERO**. 
- Se eu não apagar e fizer de novo, a tendência é que eu estarei usando as anotações como muleta e quando eu faço isso, eu não dou chance para meu cérebro absorver direito aquela sequência de resolução de exercício.

**Raio-x explicado pelo professor:** [https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1985](url)

-----------------------------------------------------------------------------------------------------------------------------------------------

## 📌Sobre o portfólio e Javascript:
- SEMPRE deixe aplicações o mais fácil possível de serem acessadas!

Ter uma base sólida em JS gera MUITA OPORTUNIDADES! (quanto mais fluente eu for com JS, mais chances eu terei) 

> _"As torres mais altas são aquela que possuem as maiores fundações_"

> _"Libs vem, Libs vão. A linguagem pura permanece / Frameworks vem, Frameworks vão. A linguagem pura permanece."_

- O que o **browser entende é JS e não framework,** ou seja, a linguagem pura é a BASE!

## 📌Sobre Se candidatar no marco 5:
- Medo e desejo estão relacionados. O desejo do que tenho tem que ser maior do que o medo de lutar com isso. Eu só entrarei no mercado no dia que meu desejo for maior do que o erro de errar! 
- A única coisa que **cura** o medo é a **AÇÃO**!

NÃO IMPORTA A DESCRIÇÃO DA VAGA! APLIQUE MESMO ASSIM! 80% das descrições das vagas estão mentindo para mim e eu não posso me dar ao luxo candidatar a vagas que pedem coisas que eu já sei!! Minha vontade de correr atrás de algo que eu ainda não sei é um dos critérios mais avaliados por recrutadores:

**- Locais para buscar vagas:**
📍 Vagas anunciadas no Front-end BR:
https://github.com/frontendbr/vagas/issues

📍 Vagas anunciadas no LinkedIn:
https://www.linkedin.com/jobs/search/?keywords=javascript

**📌ATÉ A ETAPA 15:** 
Separar pelo menos 15 vagas que me interessam e mandar email / whatsapp se candidatando!!

### O QUE CURA O MEDO É A AÇÃO!! A dor passa e a fluência fica!
- A fluência em JS puro é o meu maior ativo durante minha carreira de DEV

**Obs**: Se candidatar para 15 vagas é só o começo, é por isso eu tenho que fazer 50 e não 15. Eu irei receber feedbacks do recrutadores das empresas e devo portanto, implementar esses feedbacks, pois são eles que me darão uma direção do que preciso entrar nas empresas que quero entrar! 
- Se empresa não de feedback, tudo bem, fique atento a cultura da empresa...se ela não dá feedback para um candidato, muito provavelmente não é uma empresa muito boa.
- Eu posso pedir feedbacks em grupos o telegram, discord...e em outros locais. **O lance é focar em problemas que eu tenho controle e desfocar de problemas que eu não tenho controle.**

--------------------------------------------------------------------------------------------------------------------------------------------

## ❓A pergunta que devo fazer agora é:
> Em qual marco eu estou agora e qual é meu próximo marco?

**Comment by Roger-Melo** [comment]
Excelente @salvedojuliao, rumo à fluência! 🎯

**Comment by salvedojuliao** [comment]
No meu repositório eu criei minahs próprias issues, eu adiciono lá e aqui. Tem problema?
