### ISSUE TITLE
Etapa 7, nome do vídeo: Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#563]
Escrevi esse código em cerca de uma hora, e fiquei mais outra hora tentando resolver o problema de a segunda mensagem de help, criada após o envio do formulário, não aparecer na tela, então deixo aqui o código que eu fiz.

```javascript

const usernameInput = document.querySelector('#username')
const usernameSubmit = document.querySelector('form')
const buttonSubmit = document.querySelector('button')

usernameInput.addEventListener('keyup', event => {
  event.preventDefault()

  const p = document.createElement('p')
  p.setAttribute('data-feedback', 'username-feedback')
  const feedbackParagraph = document.querySelector('[data-feedback="username-feedback"]')
  
  const Target = event.target
  const validUSername = /[A-Za-z]{6,}/.test(Target.value)

  const helpFeedbackFunction = () => {
    Target.insertAdjacentElement('afterend', p)
    const helpFeedbackMessage = `O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas`
    p.classList.add('username-help-feedback')
    p.textContent = helpFeedbackMessage
  }

  const successFeedbackFunction = () => {
    Target.insertAdjacentElement('afterend', p)
    const successFeedbackMessage = 'Username válido =)'
    p.classList.add('username-success-feedback')
    p.textContent = successFeedbackMessage
  }

  if (feedbackParagraph) {
    feedbackParagraph.remove()
  }

  if (validUSername) {
    successFeedbackFunction()
    return
  }
  
  helpFeedbackFunction()
})

  usernameSubmit.addEventListener('submit', event => {
    event.preventDefault()
  
    const Target = event.target
    const validUsername = /[A-Za-z]{6,}/.test(Target.value)
    const p1 = document.createElement('p')
    p1.setAttribute('data-submit', 'username-submit')
    const feedbackParagraph = document.querySelector('[data-submit="username-submit"]')
  
    const successSubmitFunction = () => {
      usernameSubmit.insertAdjacentElement('beforeend', p1)
      const successSubmitMessage = `Dados enviados =)`
      p1.setAttribute('submit-success-feedback')
      p1.textContent = successSubmitMessage
    }
  
    const helpSubmitMessage = () => {
      buttonSubmit.insertAdjacentElement('afterend', p1)
      const helpSubmitMessage = `Por favor, insira um username válido`
      p1.classList.add('submit-help-feedback')
      p1.textContent = helpSubmitMessage
    }
    if (feedbackParagraph) {
      feedbackParagraph.remove()
    }
  
    if (validUsername) {
      successSubmitFunction()
      return
    }
  
    helpSubmitMessage()
  })

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @YureK-a. Você pode postar também o código HTML e CSS?

Assim fica mais fácil eu testar aqui em minha máquina e ajudar com mais precisão =)

**Comment by YureK-a** [comment]
> Oi @YureK-a. Você pode postar também o código HTML e CSS?
> 
> Assim fica mais fácil eu testar aqui em minha máquina e ajudar com mais precisão =)

HTML:

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">
  <link rel="stylesheet" href="./styleExercicios18.css">
  <title>Exercício 18</title>
</head>
<body>
  <div class="container">
    <h1>Exercício 18</h1>

    <form>
      <fieldset>
        <label for="username">Nome de usuário</label>
        <input
          type="text"
          placeholder="Cadastre seu nome de usuário"
          id="username"
          autofocus
          autocomplete="off"
        >

        <button class="button">Enviar</button>
        
      </fieldset>
    </form>
  </div>

  <script src="./Exercicios18.js"></script>
</body>
</html>

CSS:

.container {
    max-width: 80rem;
    padding-top: 7.5rem;
  }
  
  .username-help-feedback {
    margin-bottom: 2.5rem;
    color: orange;
  }
  
  .username-success-feedback {
    margin-bottom: 2.5rem;
    color: green;
  }
  
  .submit-help-feedback {
    margin-bottom: 2.5rem;
    color: red;
  }
  
  .submit-success-feedback {
    margin-bottom: 2.5rem;
    color: green;
  }

**Comment by Roger-Melo** [comment]
Olá Yure.

Ao enviar o form, `Dados enviados =)` não é exibido abaixo do botão e um erro `Uncaught TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present.` é exibido no console, certo?

Isso aconteceu por que na linha `53`, há uma invocação do `setAttribute` com apenas 1 argumento: 

```javascript
p1.setAttribute('submit-success-feedback')
```

É só inserir o primeiro argumento que falta (nome do attributo). Ficará assim:

```javascript
p1.setAttribute('nome_do_atributo', 'submit-success-feedback')
```

Faça isso e o código irá funcionar normalmente =)

@YureK-a

**Comment by YureK-a** [comment]
Ahhhhhh! Muito obrigado, professor! Vou prestar mais atenção da próxima vez!
