### ISSUE TITLE
Resumo da Aula Aviso sobre a Correção dos Exercícios da etapa 01

### ISSUE THREAD

**Issue by salvedojuliao** [roger-melo-treinamentos/curso-de-js-roger-melo#5630]
# ATER: Aula, Teoria, Exercício e Revisão
_____

![2022-12-12_13h55_46](https://user-images.githubusercontent.com/44206400/207106054-c10d6790-6f39-4735-8103-a1dae737d521.png)

## 📖 (A) Assistir Aula:
Serve somente para **ENTENDER**, Eu preciso do pós-aula (O processo de estudo individual). MAS, antes de eu partir para o 'TER' do método ATER.  Eu preciso tomar cuidado com o **anacronismo**. 
  - Anacronismo: É tudo aquilo que não segue uma sequência. 
____________________________________________________________________________________________________________________________________________

## 📚 (T) Teoria:
Eu preciso consolidar a teoria que eu acabei de ver na aula. 
- Onde eu consolido isso? Na documentação! No **MDN**! MAS como eu leio? Eu devo executar a **LEITURA EM SAVORING** (técnica mais poderosa que serve para me tirar do automático).

**Leitura do Savoring:** 
Ela funciona assim: Quando eu estiver lendo a documentação, assim que eu terminar de ler um parágrafo, eu devo me perguntar "O que eu entendi desse parágrafo que eu acabei de ler?" logo em seguida eu devo escrever resumidamente uma pequena frase acima do parágrafo (que resuma o que eutendi do parágrafo), eu devo partir para o próximo e fazer o mesmo. Em resumo:
1) Ler a documentação sobre aaula
2) A cada parágrafo da documentação, escrever resumidamente o que eu entendi do parágrafo em uma pequena frase
3) Fazer isso para os demais parágrafos
Obs: Fazendo isso eu aumento o estado de presença no meu cérebro e concentração e evito RETRABALHO.
IMPORTANTE: No final de cada leitura, eu devo ter pelo menos dois exercícios modelo.

![2022-12-12_14h05_04](https://user-images.githubusercontent.com/44206400/207114142-cc94d1cc-90d9-4cec-b9fb-9b292bad0047.png)

**- Sobre o MDN:** El tem muitos termos e links, de priemria eu devo não clicar neles, eu devo primeiro ler a descrição e definição do assunto e depois de um tempo (quanto eu estiver masi fonciente na linguagem e revisando aquele assunto) eu irei perceber que terei um pouco mais de conehcimento e os termos ficarão masi familiares.

O ato de ter que escrever aumenta a minah atenção na leitura. 
Visualização ajuda! Se eu consegir vizualizar o que o parágrafo diz, então eu terei mais facilidade dentender (livros com iamgens ajudam demais!)
____________________________________________________________________________________________________________________________________________

## 💪🏿 (E) Exercícios
A maneira mais rápida de descobrir o que eu não sei: **EXERCÍCIOS!** 
- Existem três pontos que uma **resolução de exercícios** efetiva deve seguir:
**1)** É importante que eu faça os **resolvidos do MDN** e depois os propostos pelo professor

**2)** Eles devem seguir uma **SDG (Sequência de dificuldade gradativa).** 
> No mundo das exatas, sequência é mais importante que quantidade
>_É melhor uma sequência gratativa do que uma aletaória_

**3)** Exercícios modelo! Pelo menos 1.
_(Exercício modelo é aquele exercício complexo que se eu conseguir resolver, eu consigo resolver qualquer outro exercício envolvendo o conteúdo)_
____________________________________________________________________________________________________________________________________________

## ⭐ (R) Revisão:
- Se eu não reviso, eu esqueço! E um ingrediente fundamental da revisão é a correção dos exercícios que eu fiz.
- Essa correção deixa saber se eu evolui ou não na lingaugem. Se eu tiver uma taxa de acerto de 80% ou mais, é um indício de que estou na direção certa da fluência.
- A revisão tem que ser periódica, senão o conteúdo irá virar pó

**Como revisar?**
Meu caderno ou escritas da leitura em savoring são o conteúdo que eu devo utilizar para revisar!
Lembrando: Para cada escrita/resumo que fiz com a leitura savoring, eu devo ter dosi edercícios modelos! Toda a vez que eu revisar algo, eu devo fazer a resolução do exercício modelo! 

** Depois que eu decorar tudo (que viraram paisagem), eu devo colocar meu cérebro em uma situação desafiadora, devo escolher exercícios inéditos e executar! Fazer exercícios inéditos durante a revisão é fudnamental!

_______

## E SE EU TRAVAR NUM EXERCÍCIO? 🤔

1️⃣ **Passo 1:** 
Depois de corrigir o exercício comigo, você apagará o código que implementou comigo na correção;

 2️⃣ **Passo 2:** 
Você implementará o código da resolução sozinho, como foi feito na aula, sem olhar a correção;

3️⃣ **Passo 3:** 
Se você travar em algum ponto do exercício e não conseguir resolvê-lo, você pode consultar as anotações que fez durante a aula, ou consultar as anotações que fez durante a etapa da teoria **(que é o "T", do ATER),** ou procurar o ponto da aula ou correção que esclarece a sua dúvida. Feito isso, apague o código e implemente-o novamente, sozinho.

**PS2:** não use autocomplete do editor. Vai chegar o momento em que eu vou recomendar ele no treinamento. Mas, por enquanto, evite. Assim, você ganhará memória muscular ao inserir os comandos =)

_______

⚠️ **É MUITO IMPORTANTE** que eu encontre um tempo e encaixae a revisão no meu dia! 
Não tem muito tempo? Faça a teoria do prego:
1) Antes de partir para a próxiam aula, revisa as aulas através do material mais enxuto que eu montei (caderno, flashcard, mapa mental...) escolher uma e revisar. Essa é a teoria do prego clássica.

**MAS....**

📍Agora tem um elemento na teoria de aprendizagem que ajuda a reter conteúdo: **EMOÇÃO**
  - **[Na TEORIA**] 
        Quando o conteúdo tem imagem, ele gera uma emoção maior do que se não tivesse imagem.

  - **[NOS EXERCÍCIOS]**
        No processo de exercício (quando erro a emoção vem na hora!)

  - **[Na Revisão]**:
        Eu posso ensinar alguém, criar música, mnemônicos etc.

**Comment by Roger-Melo** [comment]
Boa @salvedojuliao rumo à fluência! 🔥
