### ISSUE TITLE
Console.log dentro ou fora da arrow function

### ISSUE THREAD

**Issue by Marcio-Ribeiro-44** [roger-melo-treinamentos/curso-de-js-roger-melo#5631]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/813573

### Descreva a dúvida

Professor Roger, boa noite!
Na questão abaixo, se ao invés de retornar o callback (valor), fosse inserido o console.log(numero * 3) na função calcularTriplo estaria errado e/ou incompleto?

10

  - Crie uma função que invoca uma função de callback recebida por parâmetro.  
    A invocação da função recebida por parâmetro deve receber um valor como  
    argumento;
  - Crie uma função que retorna o triplo de um número recebido por parâmetro;
  - Faça com que a invocação da função descrita no 1º item deste exercício (10)  
    resulte no triplo de 33.
*/
```js
const chamarCallback = (valor, callback) => {
callback(valor);
};

const calcularTriplo = numero => {
console.log(numero * 3);
};

chamarCallback(33, calcularTriplo)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Marcio-Ribeiro-44!

No item 2 do exercício (abaixo), é pedido explicitamente que a função retorne o triplo do número.

> - Crie uma função que retorna o triplo de um número recebido por parâmetro;

`console.log` não substitui `return`, não retorna valor. 

`console.log` é só uma forma de você visualizar um valor no console.

Se vc invocar `calcularTriplo` sem retornar o valor, a função vai retornar `undefined`. Você pode comprovar isso visualizando o valor dessa invocação no console:

```javascript
const calcularTriplo = numero => {
  console.log(numero * 3)
}

// 👇🏻 visualizando o retorno da função
console.log(calcularTriplo(3)) // undefined
```

Em JavaScript, toda função que não retorna valor retorna `undefined`.

Obviamente, a linha `console.log(numero * 3)` vai exibir `9` no console, mas quando a função é invocada, o que vc precisa é fazer a função retornar esse valor, e não exibí-lo no console =)

**Comment by Roger-Melo** [comment]
Ah, se vc quiser postar dúvidas no grupo dos alunos no Telegram, fique à vontade. 

Acho que lá vc pode ter mais pessoas respondendo e ter respostas mais rápidas. Pela própria natureza da plataforma =)

@Marcio-Ribeiro-44

**Comment by Marcio-Ribeiro-44** [comment]
Obrigado!
