### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by LeonardoMoreiraDaSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#5637]
- Além de números, valores, string e array, podemos também passar como parâmetro de funções outras funções, chamamos essa função que passamos como parâmetros de callbacks.
```js
const myFunc = callback =>{
   const value = 77

  callback(value)
}

myFunc (number => {
  console.log(number)
})
```

> forEach

- forEach é um método de array que vai iterar, esse método significa: `para cada`. Esse método recebe uma função de callback, que por sua vez pode receber 3 parâmetros: o primeiro é o item do array, o segundo é o index e o terceiro é o próprio array.

```js
const socialNetworks = ['youtube', 'twiter', 'instagran', 'facebook']

socialNetworks.forEarch((socialNetworks, index, array) =>{
   console.log(index, socialNetworks, array)
})
```

**Comment by Roger-Melo** [comment]
Boa @LeonardoMoreiraDaSilva rumo à fluência! 🔥
