### ISSUE TITLE
Resumo da Aula Data e hora em JavaScript - Aula 01-02

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5638]
Em JS datas são um tipo de objeto, ou seja são um tipo de referencia e não um tipo primitivo. Com esses dados podemos setar datas em posts de blogs ou em uma aplicação. Para setar uma data usamos Date Constructor, um construtor é utilizado para construir um tipo de objeto, existem vários tipos de construtores em JS, e nesse caso nos utilizaremos o construtor de data.
Quando uma data é criada em JS automaticamente o tempo representado nela é o presente o agora, o tempo em que o arquivo foi excetuado.

const present = new Date
console.log(present)

Passando o console log acima iremos obter um objeto que se parece com uma string, mas que de fato é um objeto, e podemos conferir isso com um typeof. No console acima também vemos que dele iremos obter:

`Tue Dec 13 2022 23:54:38 GMT-0300 (Horário Padrão de Brasília) `
Dia da semana, o mês, dia do mês, o ano e hora atual em que o arquivo foi salvo. Agora caso quisermos obter apenas partes desta data entre outras referencias temporais, precisamos usar alguns dos vários métodos disponíveis para o objeto date.

```js
const present = new Date

console.log('getFullYear', present.getFullYear())

console.log('getFullMonh', present.getMonth())

console.log('getFullDay', present.getSeconds())

```

Quando obtemos a contagem do mês obtemos uma contagem zero based, janeiro é mês 0, fevereiro é o mês 1 e assim por diante.
Para o dia do mês

```js
console.log(present.getDate())

console.log(present.getDay())
```

O getDate( ) retorna o dia do mês e o getDay( ) o dia da semana que assim como o Month é zero based, ou seja 0 representa domingo, 1 representa segunda e assim por diante.
Podemos também obter as horas do dia com seus minutos e segundos:

```js
console.log(present.getHours())
console.log(present.getMinutes())
console.log(present.getSeconds())
```
Por fim nessa aula temos o time stamp, um time stamp é representado pelo numero de mili segundos de primeiro de janeiro de 1970 até o momento presente, o que nos permite comparar duas datas.

```js
console.log(present.getTime())
````

Se salvarmos iremos ver os mili segundos passados de primeiro de janeiro de 1970 até hoje. E para obtermos parte da data em formato de string. 

console.log(present.toDateString())
console.log(present.toTimeString())

Com essa propriedade podemos obter uma string do valor das das, lembrando que aqui estamos lidando com datas no formato de padrão américa.

**Comment by Roger-Melo** [comment]
Boa @Hugones45 rumo à fluência! 🔥
