### ISSUE TITLE
Etapa 11, Introdução a promises - Aula 04-03

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#564]
Oi professor, bom dia!
Estou com dúvida a respeito do método then. Bom, é o seguinte vi na documentação que ele também pode receber como argumento uma segunda função de callback que é executada quando a promise for rejeitada. É uma boa pratica evitar este segundo argumento e realizar o tratamento de uma promise rejeitada apenas com o catch?
Este questionamento me veio porque na maioria dos códigos que vejo a galera não utiliza este segundo argumento.

Agradeço desde já professor!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel.

Vou referenciar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/441) uma issue em que respondi essa dúvida. Se mesmo assim ainda restarem dúvidas, é só dar o toque aqui nessa issue =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
É exatamente a mesma dúvida 😂... Desculpas qualquer coisa professor, não há mais dúvidas há respeito.
Obrigado ;)
