### ISSUE TITLE
Aplicação: [To-Do_List]

### ISSUE THREAD

**Issue by Hugones45** [roger-melo-treinamentos/curso-de-js-roger-melo#5640]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### A aplicação contém funcionalidades que não foram mostradas nas aulas?

Não

### A aplicação contém funcionalidades da linguagem que não foram mostradas nas aulas?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Hugones45/To-Do_List

### Maiores dificuldades durante a implementação

Refatoração do Codigo.
Trabalhar com data-trash.
Excluir Todos com data-trash.

### Menores dificuldades durante a implementação

Adicionar Todos

**Comment by MivlaM** [comment]
Olá @Hugones45.

Eu abri a aplicação e identifiquei que o segundo critério para que a análise seja feita está em falta.

O critério é o seguinte:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas anteriores.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações".

Novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

É interessante que você tenha desenvolvido uma outra funcionalidade na aplicação, mas no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação. Solicito que, por favor, remova a funcionalidade de riscar os itens da lista para podermos prosseguir com o processo de análise de aplicação.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by Hugones45** [comment]
Mas o riscar dos itens eu aprendi no curso, Etapa 5, Eventos de clique - Aula 03-03

**Comment by MivlaM** [comment]
O que você argumentou faz sentido, talvez as labels do form do template da issue de envio de aplicações tenham causado ambiguidade e vamos corrigi-la para não deixá-las ambíguas em breve. O que o critério acima também quis dizer é: "Não usar nenhuma funcionalidade que não foi usada na aplicação modelo". Tudo bem que essa funcionalidade do traço foi mostrada nas aulas anteriores e valorizamos a sua criatividade para empregar mais funcionalidades na aplicação, porém, na hora da análise, o importante para gente é analisar o essencial que foi mostrado para a aplicação. Porque se a pessoa consegue construir a aplicação sozinha, fica meio que implícito que provavelmente, ela consegue fazer adições de funcionalidades (afinal, ela já fez o mais difícil).

Assim, eu valorizo o fato de você fazer outras funcionalidades, mas no momento que for colocar a aplicação para análise, o foco deve ser no essencial que foi mostrado nas aulas da aplicação. Você pode inserir as novas funcionalidades após termos feito a análise e ainda assim, aproveitar o que você aprendeu no feedback da análise para também implementar nas novas funcionalidades =)

Dito isso, solicito que remova a funcionalidade de riscar os itens da lista para podermos prosseguir com o processo de análise de aplicação.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by Hugones45** [comment]
Funcionalidade de riscar retirada.

**Comment by MivlaM** [comment]
Olá @Hugones45.

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @Hugones45!

Você pode fazer o download de sua análise [aqui](https://drive.google.com/drive/folders/1Ahemk4A1jCe4ny5mYGi5AJyeoHbJWmn5?usp=sharing) =)

**Comment by Hugones45** [comment]
Roger boa noite! Desculpa a demora para responder, só agora consegui ver a analise, muito obrigado pelas dicas.
Sobre o JS inline, ele possivelmente é algo que esqueci de deletar enquanto eu fazia experimentos na aplicação, procuro seguir o método e sei que não é legal ficar misturando as coisas.
Com os nomes da aplicação realmente, tenho dificuldade também em dar nomes simples e objetivos, eu esqueci de colocar isso nas dificuldades enfrentadas. Já o objeto em si que passava suas propriedades eu fiz com base no exercício 18 da etapa 6, eventos em formulários. 
Obrigado pela analise e vamos rumo a fluência!!
