### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5644]
Criando e removendo elementos do DOM, para remover um elemento dom, primeiro tem que obter a referência dele e depois utilizar o método remove(). E para inserir um novo item no elemento usa o addEventListener(). Para criar um novo item em uma tag html é usado o addEventListener(). Para criar um novo item em uma tag html é usado o document.createElement() e inserir um texto nessa tag e pelo textContent, para inserir no DOM é pelo método append(), que vai receber como argumento o elemento que vai ser inserirdo na tag em questão e tem também o método prepend() que é a mesma coisa do append() só que o item vai ser inserido como primeiro elemento e não o último como no append().

**Comment by Roger-Melo** [comment]
Boa @Dieison37 rumo à fluência! 🔥
