### ISSUE TITLE
Resumo da Aula Event bubbling e event delegation - Aula 04-02 da etapa 05

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5648]
Event bubbling (borbulhamento) propagação de de eventos, funciona assim; temos uma li como exemplo e clicamos nessa li e o evento foi disparado e esse evento é propagado dessa li onde que o evento aconteceu para o elemento pai dessa li e a partir desse ponto o JS vai procurar se existe um Listener de evento nesse elemento pai e se existir um evento adicionado nesse elemento pai a função de callback desse elemento pai e assim por diante.  O event delegation é um padrão de manipulação de eventos que permite manipular eventos em um nível superior na árvore DOM diferente do nível em que o evento foi recebido pela primeira vez.

**Comment by Roger-Melo** [comment]
Show @Dieison37. Vamo que vamo, rumo à fluência! 🙌
