### ISSUE TITLE
Resumo da Aula Código assíncrono em JavaScript - Aula 01-02 da etapa 11

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5651]
Código Assíncrono
- E um código onde um processo inicia agora e termina posteriormente. Diferente de um código síncrono onde os processos são executados passo a passo de forma ordenada de cima para baixo tornando-o "blockante", em outras palavras, travando o código pois o processo seguinte só poderá ser executado quando o anterior for iniciado e finalizado.

**Comment by Roger-Melo** [comment]
Boa @YukOnRails, rumo à fluência! 🔥
