### ISSUE TITLE
Resumo da Aula Encadeando métodos - Aula 02-03

### ISSUE THREAD

**Issue by lucamacedos** [roger-melo-treinamentos/curso-de-js-roger-melo#5654]
# Encadeando métodos - Aula 02-03
- No JavaScript, você pode encadear métodos chamando um método após o outro no mesmo objeto. O encadeamento de métodos permite escrever código conciso e expressivo ao aplicar várias transformações em um objeto em uma única instrução.

**Exemplo:**
```js
const str = '   Hello World!   ';
const transformedStr = str.trim().toLowerCase().split(' ').join('-');
console.log(transformedStr); // Saída: 'hello-world!'
```
- O código acima primeiro chama o método `trim()` para remover os espaços em branco no início e no final da string.
- Em seguida, ele chama o método `toLowerCase()` para converter a string para minúsculas. 
- Finalmente, ele chama os métodos `split()` e `join()` para dividir a string em um array de palavras e juntá-las novamente com um hífen (-) como separador.

---------------------------------------------

## Exemplo 1: Precisamos obter desses livros apenas os itens que estiverem acima de 20 reais. 
```js
const books = [
  { name: "Código Limpo", price: 30 },
  { name: "O milagre da manhã", price: 5 },
  { name: "Alice no País das Maravilhas", price: 10 },
  { name: "Quem Pensa Enriquece", price: 50 },
  { name: "O livro da ciência", price: 40 },
]

;const promoBooks = books.filter((book) => book.price > 20); // Pegando os livros com preço maior que 20 reais

const bookString = promoBooks.map(
  (book) => `O preço do livro "${book.name}" caiu para ${book.price} reais.`
); // criando outro array que vai receber a string acima.

console.log(bookString);
```

------------------------------------------------------
## Encadeando o código acima
```js
const booksOnSale = books
  .filter(({ price }) => price > 20)
  .map(
    ({ name, price }) => `O preço do livro "${name}" caiu para ${price} reais.`
  );
```

**Comment by Roger-Melo** [comment]
Show @lucamacedos. Vamo que vamo, rumo à fluência! 🙌
