### ISSUE TITLE
Resolução do exercício

### ISSUE THREAD

**Issue by Marcio-Ribeiro-44** [roger-melo-treinamentos/curso-de-js-roger-melo#5655]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Professor Roger, boa tarde!
A resolução que fiz abaixo está incorreta ou incompleta?
Devo seguir fielmente a sua resolução?
Obrigado!

07

  - Crie um objeto "dog" que possui as mesmas propriedades do objeto "cat";
  - Crie uma função que retorna a mensagem abaixo, com as informações corretas;
  - Exiba a mensagem no console.

  "A soma das idades de NOME_DO_GATO e NOME_DO_CACHORRO é RESULTADO_DA_SOMA."
*/

```js
let dog = {
  name: "Simba",
  age: 11,
  color: "Preta",
  bestFriends: ["Márcio", "Lau"],
  sound: () => "auau",
};

let soma = 0;

const somarIdades = () => {
  soma = cat.age + dog.age;
  return `A soma das idades de ${cat.name} e ${dog.name} é ${soma}.`;
};

console.log(somarIdades());
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Marcio-Ribeiro-44!

Desde que vc chegue no resultado que o exercício está pedindo, não há problemas em sua solução ser diferente da minha =)

Dito isso, após ver a correção, recomendo que vc busque também reproduzir a forma com que eu resolvi. Isso pq geralmente, os princípios por trás da forma com que resolvo um exercício serão intensificados à medida em que vc avança no treinamento =)

**Comment by Marcio-Ribeiro-44** [comment]
Obrigado!
