### ISSUE TITLE
Resolução do exercício II

### ISSUE THREAD

**Issue by Marcio-Ribeiro-44** [roger-melo-treinamentos/curso-de-js-roger-melo#5656]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/824585

### Descreva a dúvida

Roger, continuando com a resolução dos exercícios, pensei na criação do array, porém usando um objeto e método. Isso estaria correto ou fugiria das corretas resoluções que você implementou?
Obrigado!

08
  - Se você descomentar os 2 console.log abaixo, verá que a função "isAnSUV" está funcionando corretamente. Mas ela pode ser melhorada;
  - Como você refatoraria esta função?

```js
const isAnSUV = car => {
   if (
     car === "Honda HR-V" ||
     car === "Jeep Renegade" ||
     car === "Ford EcoSport" ||
     car === "Hyundai iX35"
   ) {
     return true;
   }

   return false;
 };

console.log(modelosCarros.isAnSUV("Honda Civic"));
console.log(modelosCarros.isAnSUV("Ford EcoSport"));
```
A forma que pensei...
```js
let modelosCarros = {
  modelo: ["Honda HR-V", "Jeep Renegade", "Ford EcoSport", "Hyundai ix35"],
  isAnSUV: () => {
    if (modelosCarros["modelo"]) {
      return true;
    }
    return false;
  },
};
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Marcio-Ribeiro-44. 

A resposta à essa dúvida é a que respondi na issue mais recente que foi aberta, pois são perguntas muito parecidas. Vou deixar o link [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/5655#issuecomment-1363526786) e se tiver qualquer dúvida sobre isso, é só dar o toque =)

**Comment by Marcio-Ribeiro-44** [comment]
Roger, vou seguir a sua recomendação.
Obrigado!

**Comment by Roger-Melo** [comment]
Show! =)
