### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 05 - Aula 03-01

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#5663]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula 02 da etapa 05 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/871191

### Descreva a dúvida

Neste exercício é pedido 'SE' o link da pagina possuir o a classe 'link'.
O professor resolve já acionado o método toggle, porém pelo o que entendi do método , se não tiver a classe ele vai inserir na pagina e as vezes sem necessidade , podendo gerar um BUG, pois o link poderá conter uma classe que não existia nele.

Concluo que teríamos que usar o IF para verificar se tem ou não com o  toggle dentro do IF com fiz abaixo.
está errado esta linha de raciocínio ?

minha solução
```

if(linkReferencc.classList.contains('link')){
  
  linkReferencc.classList.toggle('link')

}

```
solução do professor
![image](https://user-images.githubusercontent.com/69883048/209444533-69d95515-538f-4f65-b2cf-d13685abbc5d.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RodolfoRondinely!

Não há nada de errado em inserir um `if` não. 

Eu não fiz essa verificação pq era certo que a marcação HTML do link teria a classe.

O objetivo do exercício era apenas checar se vc entendeu como usar o método `toggle` =)
