### ISSUE TITLE
Pasta 15 exercícios - Resolução exercício 07 

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5669]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada + destructuring

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/890633

### Descreva a dúvida

@Roger-Melo

Boa tarde Roger!

Eu gostaria de saber se a minha resolução desse exercício também é correta:

07
- Se um clique no h1 acontecer, faça com que todos os elementos dentro do body 
    sejam removidos.

```javascript
const body = document.querySelector('body')

  h1.addEventListener('click', () => {
    
    body.remove()
  })
```
Na sua resolução você usou innerHTML declarando strings vazias.

Desde já agradeço.

**Comment by Roger-Melo** [comment]
Olá @Ale557333.

O método `remove` remove o elemento no qual ele foi encadeado. Ou seja, `body.remove()` removeu a tag `<body>`, e o exercício pede para que apenas o conteúdo dentro do body seja removido. 

Sacou a ideia? =)

**Comment by Ale557333** [comment]
Ah entendi sim Roger, muito obrigado!

**Comment by Roger-Melo** [comment]
Boa! No que precisar, é só dar o toque =

**Comment by Ale557333** [comment]
Obrigado Roger!
