### ISSUE TITLE
Resumo da Aula 02-02da etapa 08

### ISSUE THREAD

**Issue by diegobaena89** [roger-melo-treinamentos/curso-de-js-roger-melo#567]
**Método Sort()**

"_O método sort() ordena os elementos do próprio array e retorna o array. A ordenação não é necessariamente estável. A ordenação padrão é de acordo com a  pontuação de código unicode_." (MDN)

Ou seja, o método sorte ordena os itens de um array, sendo útil quando precisarmos ordenar os itens de um array de strings em ordem alfabética, ou um array de números em ordem crescente, etc.

sintaxe:

arr.sort([funcaoDeComparacao])

Ao contrário dos métodos map(), filter() e reduce(), o sort() modifica o array original.

Exemplo 1 - ordenando strings
```js
const names = ['Christian', 'Alfredo', 'Edson']
names.sort()
//por padrão, o sort() já ordena strings em ordem alfabética
console.log(names)
```

Exemplo 2 - ordenando números
Quando se trata da ordenação de arrays numéricos, o sort ordena os números baseado somente no primeiro número de cada item do array.

```js
const scores = [10, 50, 20, 5, 35, 70, 45]
scores.sort((score1, score2) => score2 - score1)
console.log(scores)
```

Exemplo 3 - ordenando objetos

```js
const theBigFamily = [
  { name: 'Lineu', score: 20 },
  { name: 'Nenê', score: 10 },
  { name: 'Tuco', score: 50 },
  { name: 'Bebel', score: 30 },
  { name: 'Agostinho', score: 70 }
]
```

Para orgenar objetos, o sort pode receber um argumento opcional, que é uma função de comparação.
A função recebe 2 parâmetros, representando dois itens consecutivos do array e, dentro da função,  compararemos os dois itens e decidir qual dos dois deve vir primeiro no array.

Se quisermos que o primeiro item retorne primeiro que o segundo item, a função deve retornar um número negativo, ou seja, abaixo de 0. Se quisermos que o segundo item retorne primeiro que o primeiro item, a função deve retornar um número positivo, Ou seja, maior que 0. Agora, se os dois itens forem iguais e não precisarmos reordenar os itens, a função deve retornar 0.

```js

theBigFamily.sort((item1, item2) => {
  if (item1.score > item2.score ){
    return -1
  } else if ( item2.score > item1.score) {
    return 1
  } 

  return 0
})

theBigFamily.sort((item1, item2) => item2.score - item1.score)
console.log(theBigFamily)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @diegobaena89! ATER na veia, rumo à fluência! 🔥
