### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by MarioFilho1** [roger-melo-treinamentos/curso-de-js-roger-melo#5680]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/MarioFilho1/aplications/tree/main/quiz

### Maiores dificuldades durante a implementação

As dificuldades foram as seguintes:

Como resolvi inserir ícones ao lado da pergunta para que o usuário também pudesse identificar as respostas certas e erradas. Então essa parte foi difícil e não sei se utilizei a melhor maneira de implementar, mas foi a única que consegui. 

Ainda tenho dificuldade em escolher nomes das variáveis.

Também implementei uma popup para aparecer quando o usuário deixasse de responder alguma questão. Essa foi outra que tive que pesquisar, pois quando a popup aparecia, o fluxo do programa continuava. Então mudei o local da chamada de algumas funções.   

Obs. Não usei o bootstrap para nessa aplicação, pois achei melhor utilizar  CSS puro para um melhor aprendizado. 

### Menores dificuldades durante a implementação

Não posso dizer que tiveram menores dificuldades. :)

**Comment by Roger-Melo** [comment]
Olá @MarioFilho1!

Vc abriu uma issue com o template `🔥aplicação`, mas apenas quem se inscreveu até às 8:15h tem o bônus de análise de aplicações. E pelo que vi, sua inscrição foi feita às 18:25h. 

O que vc pode fazer neste caso é dar uma olhada nas [análises feitas dessa aplicação](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues?q=is%3Aissue+quiz+label%3A%F0%9F%94%A5aplica%C3%A7%C3%A3o+is%3Aclosed). Elas são públicas =)

E claro, qualquer dúvida que tiver, é só dar o toque =)

**Comment by MarioFilho1** [comment]
Olá Roger, foi mal, não atentei para o detalhe. 
Mais uma coisa, recebi o e-mail informando sobre o novo grupo do telegram, mas não consigo acessar. Poderia enviar novamente o link?

**Comment by Roger-Melo** [comment]
@MarioFilho1 para conseguir acessar, vc precisa ter o telegram instalado no dispositivo que está clicando no link. Vc instalou o app do telegram?

**Comment by MarioFilho1** [comment]
Sim Roger, tenho o telegram instalado no meu dispositivo, mas não consigo acessar.

**Comment by Roger-Melo** [comment]
Show, aprovei lá! =D
