### ISSUE TITLE
Etapa 14, nome do vídeo: Correção dos exercícios da aula 03 da etapa 14 - Aula 01-09

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#569]
Olá, @Roger-Melo.

Queria entender o por baixo dos panos do código abaixo, o porquê.
Eu entendi que a função tem um objeto que recebe um argumento e que o objeto está envolvido entre parênteses para executar a expressão primeiro e com isso através de **[typeError]** retornar o valor da propriedade passada. 
Como tudo isso funciona?

```js
const getErrorMessage = typeError => ({
  "unsupported-code": "Sigla de moeda fornecida não é valida ou não há suporte.",
  "malformed-request": "Algo de errado com o endpoint, contate o dev.",
  "invalid-key": "Chave da API tem problemas.",
  "inactive-account": "Conta do responsável não está ativa.",
  "quota-reached": "Este plano é free e atingiu o limite de buscas.",
})[typeError] || 'Não foi possível acessar as informações!'
```

Aproveitando o gancho, o código acima seria algo parecido com a IIFE?
Porque eles se assemelham bastante, são envolvidos por parênteses, no caso do objeto retorna a propriedade passada nos colchetes e não IIFE é feita a invocação.

```js
const state = (() => {
  let exchangeRate = {}
  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate) {
        showError( {message: 'Objeto deve ter uma propriedade "conversion_rates" ' } )
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
})()
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Gabriel.

> Eu entendi que a função tem um objeto que recebe um argumento e que o objeto está envolvido entre parênteses para executar a expressão primeiro e com isso através de **[typeError]** retornar o valor da propriedade passada. 

A função apenas retorna o resultado da expressão `({ 'x': 'y' })['x'] || 'z'`.

Os parênteses nesse caso são um [grouping operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping) que apenas fazem o objeto literal ser criado antes da função executar o retorno dela. Por consequência, eles evitam que `{}` seja interpretado como abertura e fechamento do bloco da função.

Então no código abaixo, antes de qualquer coisa, o objeto é criado e só então o return implícito é executado, retornando o objeto:

```javascript
const myFunc = param => ({
  'a': `Valor de 'a'`,
})

console.log(myFunc('a')) // {a: "Valor de 'a'"}
```

Nada de novo até aqui, certo?

Porém, quando eu encadeio os colchetes e o nome de uma propriedade do objeto no final dessa expressão, por baixo dos panos é como se eu estivesse usando a sintaxe `obj['nomeDaProp']`:

```javascript
const myFunc = param => ({
  'a': `Valor de 'a'`,
})[param]

console.log(myFunc('a')) // Valor de 'a'
```

Ou seja, no fim das contas, `({ 'x': 'y' })['x']`, é o mesmo que `obj['nomeDaProp']` (exceto que o objeto não está armazenado em uma variável `obj`.

O último detalhe a ser analizado é o curto-circuito. Por que se o parâmetro referênciado dentro dos colchetes não receber uma propriedade que existe no objeto, o resultado da expressão que a função vai retornar é undefined:

```javascript
const myFunc = param => ({
  'a': `Valor de 'a'`,
})[param]

console.log(myFunc('b')) // undefined
```

Por isso é necessário inserir essa expressão ao lado esquerdo do `or` para que se ela resulte em undefined (valor falsy), todo o curto circuito resulte no valor à direita do `or`:

```javascript
const myFunc = param => ({
  'a': `Valor de 'a'`,
})[param] || 'Valor à direita do or'

console.log(myFunc('b')) // Valor à direita do or
```

Ps: se possível, execute o código do passo à passo acima em seu editor, mas digitando-o. Acredito que isso pode fazer o cérebro ir se acostumando aos poucos com o padrão.

> Aproveitando o gancho, o código acima seria algo parecido com a IIFE?
Porque eles se assemelham bastante, são envolvidos por parênteses, no caso do objeto retorna a propriedade passada nos colchetes e não IIFE é feita a invocação.

Não necessariamente.

Se uma variável armazena uma IIFE, essa variável receberá o valor que a auto-execução da função retorna:

```javascript
const myConst = (function (param) {
  return { prop: param }
})('olá')

console.log(myConst) // { prop: "olá" }
```

Já no código abaixo, ao invés de armazenar o valor que a função retorna, `myFunc` continua sendo uma função que precisa ser invocada com a notação `myFunc(x)` e essa invocação resultará no valor no qual o curto-circuito resultou:

```javascript
const myFunc = param => ({
  'a': `Valor de 'a'`,
})[param] || 'Valor à direita do or'

console.log(myFunc('b')) // myFunc('b') resulta no valor em que o curto-circuito resultou
```

Na etapa 15 você encontrará conteúdo sobre IIFE =)

Ficou mais claro?

@gcarniel

**Comment by gcarniel** [comment]
Ficou mais claro sim, Roger.

Quando bati o olho nessa expressão `({ 'x': 'y' })['x'] || 'z'` tudo fez sentido.

Obrigado.

**Comment by Roger-Melo** [comment]
Legal @gcarniel! No que precisar, estamos às ordens =)
