### ISSUE TITLE
Resumo da Aula Exercicios 02-01 da etapa 02

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#570]
@Roger-Melo
![pg001](https://user-images.githubusercontent.com/44072541/116277113-8dee4f80-a75b-11eb-9b7c-c173d275cacf.jpg)
![pg002](https://user-images.githubusercontent.com/44072541/116277189-9ba3d500-a75b-11eb-8ed7-12640a8448e3.jpg)
![pg003](https://user-images.githubusercontent.com/44072541/116277229-a5c5d380-a75b-11eb-865b-dbc53ce0bb52.jpg)
![pg004](https://user-images.githubusercontent.com/44072541/116277273-afe7d200-a75b-11eb-8a1a-9f1993ff8614.jpg)
![pg005](https://user-images.githubusercontent.com/44072541/116277315-b9713a00-a75b-11eb-9412-2ee25c4c84bd.jpg)
![pg006](https://user-images.githubusercontent.com/44072541/116277346-c3933880-a75b-11eb-8d91-fcca26f94efc.jpg)
![pg007](https://user-images.githubusercontent.com/44072541/116277380-cdb53700-a75b-11eb-88b7-9b565d8f05c1.jpg)

**Comment by Roger-Melo** [comment]
Excelente @marcosyoggy! COntinue seguindo o método, rumo à fluência! 🔥
