### ISSUE TITLE
Quiz Interativo

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#5700]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/RodolfoRondinely/quizinterativo

### Maiores dificuldades durante a implementação

Tentei colocar uma variável para caso o valor do score for 1, a palavra apareceria no singular , porém não consegui  e deixei sem esta palavra e somente com o score como esta no GIT. abaixo como tentei fazer

```js
let word ='questões'


const showResult = event=>{
    event.preventDefault()

input.forEach(checado =>{

const condiction = checado.checked & checado.value ==='B'

if (condiction) {
        score ++
        totalScore =score * 25

if( score ===1 ){
    word = 'questão'
return
}

        result.textContent = `
        Você acertou ${score} ${word}!!!
        O rendimento foi de  ${totalScore}%
        `
    }

    if(score === 0 )
    result.textContent =`
    VOCÊ NAO ACERTOU NADA TENTE NOVAMENTE :(
    `

})

score  = 0 

}

form.addEventListener('submit' , showResult )


```

### Menores dificuldades durante a implementação

Tentei achar os valores do input radio pelo console. 
Não fiz pelo array pois achei o mesmo resultado .

**Comment by Roger-Melo** [comment]
@RodolfoRondinely no seu código tem um operador `&`. 

É um operador válido em JavaScript, você pode ver isso aqui: 

- [Bitwise AND (&)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND)

Como vc acabou de ver, ele está fazendo algo no seu código que eu acho que vc não queria fazer. Talvez vc tenha usado esse operador querendo usar outro, não?

Dica: se vc inserir um `console.log(input.checked & input.value === 'B')`, verá os valores que essa expressão está retornando. É esse valor que está sendo armazenado na const `condition`.

Quer ajustar essa lógica antes que a aplicação seja analisada?

**Comment by RodolfoRondinely** [comment]
Oi tudo bem , e obrigado pelo curso está sendo ótimo !!!

Eu analisei aqui, conferi , reconferi, e não achei outro resultado senão o
que eu estava querendo .

Procurei no MDN também e o operador & retorna true se ambas as opções forem
válidas.

Coloquei no console e antes do IF a variável me retorna 0 ou 1. O quando
for false e 1 quando for true.
Dentro do IF a variável me retorna somente o 1 que é a condiction == true ,
ou seja verdadeira e executa o código..

Pensei se checado.ckecked e checado.value forem true, eu executaria o
código .
Pois em todos os inputs após o envio do formulário , temos checked e value,
se ambos quando o forEach rodar forem true variável (condiction for true) o
IF será executado .

Vou enviar este e-mail com a pulga atrás da orelha porque vocês com certeza
sabem mais do que eu e viram o que eu não vi , porém dei tudo aqui para
tentar achar outra solução ou outro operador e não consegui .
Fiz conforme a dica em cima e estava me retornando no IF  no console o
valor do value e cheked  quando for true.
A variável condiction se for verdadeira cairá dentro do IF e executará o
código. que é adicionar o que a score tem +1  e a scoreTotal receberá =
valor da score*25.

Tentei ajustar aqui, podem me dar mais uma dica neste código ou pode
avaliar também sem problemas.
O bom de analisar este código seria de mais alguém ter a dúvida e não saber
resolver como eu.

Obrigado !!!




const condiction =  checado.checked & checado.value ==='B'
if ( condiction ) {
    console.log('valor cheked ' + checado.checked + ' valor value '+
checado.value
);

        score ++
        totalScore =score * 25

        result.textContent = `
        Você acertou ${score} !!!
        O rendimento foi de  ${totalScore}%
        `
        return
    }

    if(score === 0 ){
    result.textContent =`
    VOCÊ NAO ACERTOU NADA TENTE NOVAMENTE :(
    `
}

})
score  = 0








*Rodolfo Rondinely da Silva*
*(31) 9 95704103    ZAP*


Em qui., 5 de jan. de 2023 às 18:34, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
@RodolfoRondinely isso mesmo, não retorna true mas sim `1` ou `0`. 

Provavelmente, o operador que vc queria usar é o `&&` (com dois "&"), não?

- [Página no MDN do operador &&](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND)

Para analisar as aplicações, pedimos que vc use o que foi mostrado no CJRM. Isso já é material suficiente para analisar o seu desempenho e o que entendeu até aqui. O operador `&` não foi mostrado nas aulas =)

**Comment by RodolfoRondinely** [comment]
Bom dia,

Após esta dica do operador && , notei que realmente estava usando apenas um
&, este me retornava apenas 0 ou 1 e com dois && me retorna true ou false.
Retornei aos meus rascunhos da Etapa 2 e lá estavam 2 operadores e não um
como estava usando .
Alterei para os 2 &&, e considero que já podem analisá-lo .



Obrigado pela atenção !!

https://www.instagram.com/rondrondinely/


*Rodolfo Rondinely da Silva*
*(31) 9 95704103    ZAP*


Em sex., 6 de jan. de 2023 às 23:32, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @RodolfoRondinely!

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by RodolfoRondinely** [comment]
ok

**Comment by Roger-Melo** [comment]
Olá, @RodolfoRondinely.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ### Tentei achar os valores do input radio pelo console.

Não sei se entendi o que vc quis dizer, mas o usuário da sua aplicação não vai usar ela com o console do navegador aberto. Vc tem que deixar tudo pronto para ele chegar e usar =)

---

> ### Não fiz pelo array pois achei o mesmo resultado

Sim, da forma que vc fez também funciona. Apenas fique atento que dessa forma, é obrigatório que a alternativa certa sempre seja a que tem o value 'B'. Isso pode deixar a aplicação mais limitada, por que se daqui a um tempo vc quiser adicionar mais perguntas, sempre terá que se lembrar dessa "regra".

---

### Nomenclatura

A const `input` armazena referências de vários inputs, então pode fazer mais sentido nomear ela como plural ao invés de singular:

```javascript
// antes
const input = // ...

// depois
const inputs = // ...
```

Isso faz com que uma pessoa que está vendo o código pela primeira vez, ao bater o olho no nome da const, entenda mais rápido que ela armazena vários elementos e não apenas um. 

No callback do `forEach` tem um parâmetro "checado", enquanto o restante da aplicação usa o inglês como idioma. Ter apenas um único idioma na aplicação tende a fazer com que ela fique mais consistente. Por isso, eu vejo que faz mais sentido nomear esse parâmetro como `input`. Isso pq além da consistência no idioma, `input` é singular do array no qual o `forEach` foi encadeado (`inputs`). Esse conceito de nomear parâmetro do callback como singular do array funciona bem em grande parte das vezes. 

```javascript
// antes
inputs.forEach(checado => { /* ... */ }

// depois
inputs.forEach(input => { /* ... */ }
```

Fazer dessa forma também dá ao código mais legibilidade. Dá uma olhada no antes e depois dos locais onde esse parâmetro é usado:

```javascript
// antes
checado.checked && checado.value === 'B'

// depois
input.checked && input.value === 'B'
```

A palavra "condiction" não existe. Acho que vc quis dizer "condition".

```javascript
// antes
const condiction = // ...

// depois
const condition = // ...
```

Como a const condition armazena um boolean que indica se a resposta marcada é a resposta correta, talvez `isCorrectAnswer` seja um nome mais descritivo:

```javascript
// antes
const condition = input.checked && input.value === 'B'

// depois
const isCorrectAnswer = input.checked && input.value === 'B'
```

---

### Manipulação de DOM dentro do `forEach`

A cada execução da função do `forEach`, um texto está sendo inserido dentro da div `result`:

```javascript
inputs.forEach(input => {
  // ...

  if (isCorrectAnswer) {
    // ...
    result.textContent = /* inseriu texto na div... */
  }

  if (score === 0)
    result.textContent = /* inseriu texto na div... */
})
```

A inserção do texto na tela não precisa acontecer a cada execução da função. Ela pode acontecer apenas após a pontuação ser calculada. Dentro do forEach, vc precisa apenas calcular a pontuação =)

A princípio, ficaria assim:

```javascript
// antes
const showResult = event => {
  event.preventDefault()

  inputs.forEach(input => {
    const isCorrectAnswer = input.checked && input.value === 'B'

    if (isCorrectAnswer) {
      score++
      totalScore = score * 25

      result.textContent = `Você acertou ${score} !!! O rendimento foi de  ${totalScore}%`
    }

    if (score === 0)
      result.textContent = `VOCÊ NAO ACERTOU NADA TENTE NOVAMENTE :(`
  })

  score = 0
}
```

```javascript
// depois
const showResult = event => {
  event.preventDefault()

  inputs.forEach(input => {
    const isCorrectAnswer = input.checked && input.value === 'B'

    if (isCorrectAnswer) {
      score++
      totalScore = score * 25
    }
  })

  if (score === 0) {
    result.textContent = 'VOCÊ NAO ACERTOU NADA TENTE NOVAMENTE :('
    return
  }

  result.textContent = `Você acertou ${score} !!! O rendimento foi de  ${totalScore}%`
}
```

No código acima, não é necessário quebrar linha nas template strings, por isso removi. 

A mensagem dentro do if (score === 0) não está usando interpolação, então ela pode ser uma string tradicional.

Observe também que se o score for `0`, não é mais necessário reatribuir `0` abaixo do forEach. 

Porém, se vc testar esse código, no segundo envio seguido do form, `score` irá acumular com a pontuação do primeiro envio. 

Porém, se a declaração de score for movida para dentro da função `showResult`, quando `showResult` terminar de ser executada, `score` será limpa da memória e uma nova score será declarada recebendo 0 se a função for executada novamente, e assim sucessivamente. E o mesmo vale para `totalScore`.

Deve ficar assim:

```javascript
const showResult = event => {
  event.preventDefault()
  let score = 0
  let totalScore = 0

  inputs.forEach(input => {
    const isCorrectAnswer = input.checked && input.value === 'B'

    if (isCorrectAnswer) {
      score++
      totalScore = score * 25
    }
  })

  if (score === 0) {
    result.textContent = 'VOCÊ NAO ACERTOU NADA TENTE NOVAMENTE :('
    return
  }

  result.textContent = `Você acertou ${score} !!! O rendimento foi de  ${totalScore}%`
}
```

Ao testar, tudo deve funcionar normalmente.

Há formas mais sofisticadas de refatorar esse código, mas isso vc verá nas próximas aulas do treinamento =)

Fez sentido pra vc o que foi mostrado aqui?

**Comment by RodolfoRondinely** [comment]
Boa tarde !

Ao testar, tudo deve funcionar normalmente.

Há formas mais sofisticadas de refatorar esse código, mas isso vc verá nas próximas aulas do treinamento =)

Fez sentido pra vc o que foi mostrado aqui?

Sim, fiquei satisfeito pela avaliação porque foram coisas bem pontuais mesmo, já refiz este exercicio com os arrays como armazenamento e ficou bom,tambem, 

Estou super satisfeito com o curso e dedicado somente a ele.
Não tenho a intenção de trabalhar de clt , talvez em um curto periode de tempo para sentir a rotina de um dev, porem meu objetivo é empreender com os conhecimentos adquiridos por aqui.

muito obrigado
