### ISSUE TITLE
Pasta exercício REGEX

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5712]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/924879

### Descreva a dúvida

@Roger-Melo

Boa tarde Roger! 

Segue abaixo o exercício e minha dúvida:

  03

  - Teste uma regex que dá match com a palavra "documentation" do parágrafo do  
    index.html;
  - Exiba no console o boolean no qual este teste resulta.

```javascript

const p = document.querySelector('p')

const regex = /documentation/
const result = regex.test(p.textContent)

console.log(result)
```

Eu não entendi o por que do textContent

Muito obrigado.

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Quando `textContent` é usado sem o sinal de atribuição (`=`), ele retorna o texto que ele contém. 

Você pode visualizar isso se antes de declarar a const `result`, invocar um `console.log()` que recebe como argumento a expressão com `textContent` que vc inseriu na invocação do test =)

**Comment by Ale557333** [comment]
Entendido, muito obrigado Roger!
