### ISSUE TITLE
Correção dos exercícios - Aula 02-01

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#5719]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/924879

### Descreva a dúvida

@Roger-Melo
Boa tarde Roger tudo bem?

Eu não entendi por que você inseriu no value aquela string para teste no html
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/71138743/211388390-a8ac1b95-b765-4589-84b0-e40f9ed34a8b.png">

**Comment by Roger-Melo** [comment]
Olá @Ale557333!

Quando um atributo `value` é inserido numa tag input, a string que vc insere como valor desse atributo será inserida no input quando a página carregar. 

Isso significa que o input `<input value="abc">` estará preenchido com a string `abc` assim que o navegador carregar o index.html. 

Eu fiz isso para não ter que inserir um valor no input manualmente toda vez que eu quisesse testar ele xD

**Comment by Ale557333** [comment]
Entendido Roger! 
Muito obrigado

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só dar o toque =)
