### ISSUE TITLE
Etapa 08, Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by DeivideSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#572]
Professor,depois que o código foi refatorado a variavel que contém o score foi passado para o scopo global,mesmo se for escolhido uma resposta errada o contador incrementa e vai incrementando até passar de 100 pontos.
Ao retirar a variavel que contém o score e retornado ela para dentro do form  tudo volta a funcionar normalmente,no caso sem refatorar fiz um teste no codigo antes de ser refatorado,colocando a variavel que  armazena o score no scopo global e o erro persiste,mas quando a score volta para dentro do evento do form volta a funcionar,já assisti mais de 3x a video aula mas não consegui encontrar o porque pois no seu código após a refatoração funciona normalmente.
Segue o codigo refatorado conforme a video aula:

```
const form = document.querySelector('.quiz-form')
const finalScoreContainer = document.querySelector('.final-score-container')

const correctAnswers = ['B' , 'D', 'C', 'A']

let points = 0

const getUserAnswers = () => {
    let userAnswers =  []
    correctAnswers.forEach((_, index) => {
        const userAnswer = form[`inputQuestion${index + 1}`].value
        userAnswers.push(userAnswer)
    })
    
    return userAnswers
}

const calculateUserScore = userAnswers => {
    userAnswers.forEach((userAnswer,index) => {
        const isCorrectAnswers = userAnswer === correctAnswers[index]
        if(isCorrectAnswers){
            points += 25
        }
    })
}

const showFinalScore = () => {
    scrollTo({
        top: 0,
        left: 0,
        behavior: 'smooth'
    })
    finalScoreContainer.classList.remove('d-none')
}

const animateFinalResult = () => {
    let counter = 0
  
    const timer = setInterval(() => {
        if(counter === points) {
            clearInterval(timer)
        }

        finalScoreContainer.querySelector('span').textContent = `${counter++}%`
    },10)
}

form.addEventListener('submit', event => {
    event.preventDefault()

    const userAnswers = getUserAnswers()

    calculateUserScore(userAnswers)
    showFinalScore()
    animateFinalResult()
})


```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Deivide.

Antes de responder, deixa eu dar uma dica.

Sempre que inserir um bloco de código, prefira usar syntax highlight. Isso deixa o código mais legível e elegante. Ao abrir a issue, você verá nos comentários a instrução de como fazer isso, mas para resumir, basta inserir `javascript` após as três crases de abertura do bloco (```javascript).

Fazendo isso, ao invés do código ficar assim:

```
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

Ele ficará assim:

```javascript
const firstConst = 1
const secondConst = 2
const thirdConst = 3
```

---

Sobre o limite da pontuação do usuário, você verá como resolver isso na aula 01-02 da etapa 09 e também pode ver [nessa](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/9) issue.

E claro, se ainda restar alguma dúvida, é só dar o toque aqui nessa issue =)

@DeivideSilva

**Comment by DeivideSilva** [comment]
Bom dia,Roger obrigado pela resposta rápida consegui resolver o problema seguindo o exemplo da issue citada acima.E sobre a syntax highlight vou seguir conforme mencionado novamente obrigado pelas dicas o curso esta otimo!

**Comment by Roger-Melo** [comment]
Boa @DeivideSilva! Já que ficou mais claro vou fechar a issue. Mas no que precisar, é só abrir uma nova =)
