### ISSUE TITLE
Dúvida em como inserir o método "insertAdjacentElement".

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#5731]
### Etapa da aula

6

### Nome da aula

Exercícios da aula 02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/2821553

### Descreva a dúvida

Boa tarde Roger tudo bem ?
Fiz o 1º exercício e está funcionando, mas não consigo inserir esse método "insertAdjacentElement" como pede no exercício, já pesquisei no MDN mas não compreendi a forma que se procede. Segue o exercício como fiz até então.

```js
  01
  - Valide o valor do input "username" à medida em que ele é digitado;
  - Ele deve conter: 
    - No mínimo 6 caracteres;
    - Apenas letras maiúsculas e/ou minúsculas;
  - Se o valor inserido não é válido, exiba um parágrafo laranja abaixo do  
    input com a seguinte mensagem: "O valor deve conter no mínimo 6 caracteres,  
    com apenas letras maiúsculas e/ou minúsculas";
  - Se o valor é válido, o parágrafo deve ser verde e exibir a mensagem  
    "Username válido =)";
  - Use as classes disponíveis no arquivo style.css para colorir o parágrafo;
  - Não insira o parágrafo manualmente no index.html.
  
  Dica: pesquise pelo método "insertAdjacentElement", no MDN;
*/
const form = document.querySelector('form')
const feedback = document.querySelector('.feedback')
const testUsername = username => /^[a-zA-Z]{6,}$/.test(username)
form.addEventListener('submit', event => {
  event.preventDefault()

  const isAvalidUsername = testUsername(event.target.username.value)

  if (isAvalidUsername) {
    feedback.textContent = 'Username válido'
    return
  }
   feedback.textContent =
    'O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas'

})

form.username.addEventListener('keyup', event => {
  const isAValidUsername = testUsername(event.target.value)
  console.log(event)
  if(isAValidUsername) {
    form.username.setAttribute('class', 'submit-success-feedback')
    return
  }
  form.username.setAttribute('class', 'submit-help-feedback', )
  
})

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Dieison37!

O `insertAdjacentElement` é um método que deve ser usado quando vc precisa inserir um elemento em uma posição relativa ao elemento no qual o método foi invocado. 

Por exemplo:

```html
<h1>Olá</h1>
```

Se esse `<h1>` está em meu HTML e eu preciso inserir um `<p>` antes do `<h1>`, eu posso criar esse parágrafo no JavaScript e usar o `insertAdjacentElement` para posicionar o parágrafo logo acima do `<h1>`:

```javascript
const title = document.querySelector('h1')
const message = document.createElement('p')

message.textContent = 'mensagem'
title.insertAdjacentElement('beforebegin', message)
```

No código acima, eu especifiquei que antes do começo do `<h1>` (beforebegin), o parágrafo (message) deve ser inserido.

Na correção do exercício eu mostro como o `insertAdjacentElement`. Não há problemas em ver a correção se tiver travado no exercício, desde que vc realmente aprenda o que foi mostrado nela xD

Se depois de ver a correção restar alguma dúvida, é só dar o toque =)

**Comment by Dieison37** [comment]
Certo, vou tentar fazer aqui e depois vou ver a correção pra ver se
consegui fazer corretamente.

Grato pela ajuda.




Att.
DIEISON L. VIEIRA.


Em qua., 11 de jan. de 2023 às 22:15, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Boa! No que precisar, é só dar o toque =)
