### ISSUE TITLE
Etapa 03, nome do vídeo: o método forEach e callbacks-Aula 02-04

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#574]
Bom dia Roger fiquei um pouco confuso no uso de callbacks teria outros exemplos ou video explicando um pouco mais a fundo esses callbacks, eu até refiz com uma function declaration para ver se entendia um pouco mais ´so que sem sucesso; desde já agradeço.
```js
function myFunc2 (callback) {
  const value = 41
  callback(value)
}

myFunc2 (function(number) {
  console.log(number)
})

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcelo. No começo é normal termos um pouco de dificuldade para entendermos callbacks.

Vamos fazer um passo a passo?

Preciso que você acompanhe cada passo codando comigo em seu editor, vamos lá:

- 1º passo: vou declarar a função normalmente, sem parâmetro algum:

```javascript
const myFunc = () => {}
```

Se salvarmos o arquivo e invocarmos essa função, nada acontece pois invocamos uma função vazia:

```javascript
const myFunc = () => {}

myFunc()
```

- 2º passo: para que futuramente essa função exiba algum valor no console, vou especificar que ela receberá uma string por um parâmetro nomeado como `string`,

```javascript
const myFunc = string => {}

myFunc()
```

e agora que eu especifiquei esse parâmetro, eu posso passar uma string como argumento da invocação da função:

```javascript
const myFunc = string => {}

myFunc('Minha string')
```

Então agora temos uma função que recebe 'Minha string' no parâmetro `string`.

Só que a invocação dessa função ainda não causará efeito algum, pois eu estou fazendo nada com a 'Minha string' que recebi no parâmetro string.

Então para exibir no console o valor que o parâmetro `string` recebeu, dentro da função eu vou executar um `console.log()` que recebe o valor que o parâmetro `string` recebeu:

```javascript
const myFunc = string => {
  console.log(string)
}

myFunc('Minha string')
```

Se você olhar o console, verá que 'Minha string' foi exibida.

Até nesse ponto do treinamento, os valores que foram passados como argumentos para as funções foram strings (como essa que codamos agora), números, arrays e etc.

Só que em JavaScript, assim como números e strings são valores que podem ser recebidos por parâmetro, uma função também é um valor (que pode ser recebido por parâmetro).

Sabendo disso, vamos ao próximo passo.

- 3º passo: para que a `myFunc` receba uma função como parâmetro, eu vou substituir o parâmetro `string` por um parâmetro `aFunction`,

```javascript
const myFunc = aFunction => {
  console.log(string)
}
```

e para que a função recebida no parâmetro `aFunction` da myFunc seja exibida no console, no argumento do `console.log()`, vou substituir `string` por aFunction:

```javascript
const myFunc = aFunction => {
  console.log(aFunction)
}
```

Então agora, se eu inserir a declaração de uma função como argumento da invocação da myFunc,

```javascript
const myFunc = aFunction => {
  console.log(aFunction)
}

myFunc(() => {}) // função declarada como argumento
```

como em JavaScript uma função também é um valor que pode ser recebido por parâmetro (como qualquer outro valor), se salvarmos o arquivo e olharmos o console, a função que declaramos como argumento da invocação da myFunc é exibida.

- 4º passo: agora que sabemos que o argumento `aFunction` do console.log() é uma função, eu posso invocar essa função inserindo os parênteses:

```javascript
const myFunc = aFunction => {
  console.log(aFunction()) // função invocada
}

myFunc(() => {})
```

Se salvarmos o arquivo, o console exibe undefined. 

Por que?

Por que a função que inserimos como argumento da invocação da myFunc não está retornando um valor.

Se eu fizer a função retornar um 'Oi',

```javascript
const myFunc = aFunction => {
  console.log(aFunction())
}

myFunc(() => 'Oi') // fiz a função retornar 'Oi'
```

como a invocação da `() => 'Oi'` retorna uma string, a invocação dela no argumento do console.log() dentro da myFunc resultará na string 'Oi'.

Se salvarmos o arquivo, agora sim o console exibe a string.

A diferença entre o exemplo mostrado na aula e esse é que a função de callback invocada dentro da myFunc recebe um argumento. Se você entender esse exemplo acima, será mais fácil entender o exemplo do vídeo.

Ficou claro?

Se não ficou, é só dizer qual dos passos teve mais dificuldade em entender que explico de outra forma =)

@Mlluiz39

**Comment by Mlluiz39** [comment]
Roger no 4° passo você invocou a função dentro da myFunc é ela quem está recebendo o argumento oi ?

**Comment by Roger-Melo** [comment]
Na verdade a string `'Oi'` não é um argumento. Essa string é apenas o valor que a função retorna quando é invocada.

Argumento é o valor inserido dentro dos parênteses da **invocação** de uma função:

![parametro-argumento](https://user-images.githubusercontent.com/29297788/116639147-33611900-a93e-11eb-9a6f-7d6c457e8466.jpg)

Ou seja, `() => 'Oi'` foi inserida como argumento da invocação de `myFunc()`.

Como o parâmetro `aFunction` recebeu a referência da função `() => 'Oi'`, a invocação `aFunction()` retorna o valor que `() => 'Oi'` retorna (string 'Oi'):

![retorno-oi](https://user-images.githubusercontent.com/29297788/116639538-242e9b00-a93f-11eb-9295-86fa24fd8b0d.jpg)

Sacou a ideia?

@Mlluiz39

**Comment by Mlluiz39** [comment]
Com esse exemplo eu até entendi, mas no exemplo do vídeo quando tem a const aí deu uma brigada no cérebro !

**Comment by Mlluiz39** [comment]
Bom dia Roger !
maravilha entendi obrigado mesmo pela mentoria extremamente feliz em finalmente começar a entender um pouco mais sobre a linguagem.

**Comment by Roger-Melo** [comment]
Excelente @Mlluiz39. Já que ficou mais claro vou fechar a issue mas no que precisar, estamos às ordens =)
