### ISSUE TITLE
Duvida map, porque usar return em um e em outro não

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#5740]
### Etapa da aula

8

### Nome da aula

O método map - Aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/986668

### Descreva a dúvida

Bom dia, não entendi porque no array number não é preciso retornar um objeto usando return
como foi foi no array products.

Estou vendo pela primeira vez e estou com esta duvida. 

```js
const number =[1,2,3]

const doublenumber = number.map( item => item *2)



const products = [
    { name: 'Mouse Sem Fio', price: 30 },
    { name: 'Pen Drive', price: 25 },
    { name: 'Cartucho de Tinta', price: 50 },
    { name: 'Suporte Ergonômico para Notebook', price: 23 },
    { name: 'Repetidor de Sinal Wi-Fi', price: 44 }
  ]

  const metadeofProducts  = products.map(item => {
    if( item.price >= 30){
        return {name: item.name,  price: item.price / 2}
    }
    return item
  })
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
@RodolfoRondinely na expressão `item => item * 2`, vc está usando o `return` implícito da arrow function para retornar o resultado do número multiplicado por 2.

O valor que vc irá especificar como retorno na função do map só deve ser um objeto se vc quiser que o map gere um array de objetos. 

A função do map pode retornar qualquer tipo de dado que vc especificar. No caso do array `numbers`, provavelmente o objetivo ao usar o map era obter um array de números, por isso não tem objeto sendo retornado =)

Entendeu a ideia?

**Comment by RodolfoRondinely** [comment]
Entendido .obrigado!!
