### ISSUE TITLE
Como posso rever meus resumos?

### ISSUE THREAD

**Issue by JhonatanSerafim** [roger-melo-treinamentos/curso-de-js-roger-melo#5742]
### Etapa da aula

1

### Nome da aula

A Aula Mais Importante do CJRM

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928

### Descreva a dúvida

Roger, me veio uma dúvida com relação a organizão dos estudos sendo 'Como rever meus resumos feitos no seu repositório'?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @JhonatanSerafim!

Para ver issues passadas que vc postou, basta vi aqui na [aba de issues](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues), clicar em "Filters" e selecionar "Your issues". 

À partir daí, basta clicar em "Open" para ver as issues que vc tem abertas ou "Closed" para ver as issues que foram marcadas como fechadas =)
