### ISSUE TITLE
Aplicação: [Conversor de Moedas]

### ISSUE THREAD

**Issue by MivlaM** [roger-melo-treinamentos/curso-de-js-roger-melo#5743]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/MivlaM/ConversorDeMoedas

### Maiores dificuldades durante a implementação

-Refatoração
-Tive que revisar as aulas, os passos várias vezes e passei algum tempo consultando a internet para achar uma forma de fazer o código funcionar
 

### Menores dificuldades durante a implementação

-Request da API
-Dessa vez, como já havia escrito o que era necessário fazer, pude me organizar melhor em cada parte.

**Comment by Roger-Melo** [comment]
Olá @MivlaM!

Boa! Em breve visualizo aqui e te dou um feedback =)

Desde já, parabéns por ter enviado a aplicação 🎉

**Comment by Roger-Melo** [comment]
Olá @MivlaM!

Mesmo com as dificuldades de refatoração e revisões que vc listou, vc conseguiu implementar a aplicação. Está de parabéns =D

Vou deixar abaixo a análise com alguns pontos de melhoria que encontrei e qualquer dúvida, pode comentar aqui abaixo que te ajudo, ok? =)

---

## Carregamento da aplicação

De uma perspectiva do usuário, ao invés de não exibir valor na tela, acredito que seria interessante exibir de cara a conversão do dólar pra real. Mas eu vou falar mais sobre isso daqui à pouco, ali em baixo. 

---

## Contraste entre logo e background

A cor do logo (lilás escuro) não está contrastando com a cor de fundo (azul escuro). Pra destacar mais o logo, você pode testar uma cor mais clara. Acredito que isso irá resolver o problema da falta de contraste =)

---

## Erro ao carregar a aplicação

Quando abri a aplicação, um erro foi exibido no console com a seguinte mensagem: `Uncaught (in promise) TypeError: getCurrency is not a function at fetchCurrency - app.js:38`.

Ou seja, a mensagem diz que `getCurrency` não é uma função. 

O erro vem da linha da invocação de `getCurrency` no código abaixo:

```javascript
const fetchCurrency = async mainCurrency => {
  // ...
  const getCurrency = Array.from(secondCurrency)
    .find(({ text }) => text === currencyTwo)
    .selected = true

  getCurrency() // 👈🏻 o erro foi lançado devido à essa invocação
  startConversion()
}
```

Antes de continuar lendo, você consegue imaginar o que aconteceu?

O que você pode fazer para descobrir?

Dica: console.log().

Bom, se acima da invocação de `getCurrency` você visualizar ela console, verá que ela não está armazenando uma função, mas sim um boolean (`true`).

Isso aconteceu por que a expressão `Array.from(...).find(...)` está retornando a referência do `<option>` que contém uma propriedade `text` (que foi criada em um outro lugar do código) que corresponde à string do segundo select. 

É má prática atribuir propriedades à elementos do DOM, e também não é necessário fazer isso. Vou mostrar como daqui a pouco. Mas é importante entender que DOM foi feito para um propósito: representar o que está sendo renderizado. Não faz sentido inserir propriedades nesse tipo de elemento. Não nesse caso e em nenhum outro que eu já tenha visto.

Depois que o `find()` retorna o `<option>` em questão, `.selected = true` está atribuindo `true` para a propriedade `selected`. 

Quando há reatribuição, toda a expressão da reatribuição retorna o valor que foi atribuído. 

Exemplo:

```javascript
const obj = { prop: 'value 1' }

// 👇🏻 console.log só pra vc visualizar o valor que a reatribuição retornou
console.log(obj.prop = 'value 2') // value 2
```

Ou seja, no seu código, a expressão `Array.from(...).find(...).selected = true` retornou `true`, e esse `true` foi armazenado na const `getCurrency`. 

Isso significa que `getCurrency` não é uma função. 

Como `getCurrency` está armazenando `true`, a invocação `getCurrency()` é o mesmo que fazer `true()`. 

`true` não é função, então o erro dizendo "...getCurrency is not a function..." foi lançado.

O lançamento desse erro está impedindo `startConversion` de ser executada, pois o erro está sendo lançado na linha acima da invocação de `startConversion`. E por isso, nenhum valor é exibido na tela quando a aplicação é carregada. 

Para resolver isso, é necessário remover a invocação de `getCurrency`:

```javascript
// antes
const fetchCurrency = async mainCurrency => {
  // ...
  getCurrency()
  startConversion()
}
```

```javascript
// depois
const fetchCurrency = async mainCurrency => {
  // ...
  startConversion()
}
```

Teste o código antes de continuar.

Nesse ponto, provavelmente os valores zerados foram exibidos na tela. 

O ideal é que seja exibida uma conversão quando o usuário acessa a aplicação, no caso 1 USD = "X" BRL.  forma mais simples de fazer isso nesse caso é mudando o atributo `value` do input de zero para 1 (`value="1"`).

```html
<input ... value="1">
```

Obviamente, o ajuste acima vai fazer o nome da const `getCurrency` ficar esmaecido no VSCode, pq essa const não está mais sendo usada. Porém, o que vem à direita do sinal de atribuição (=) é executado primeiro e só depois a atribuição acontece para a const. Isso significa que a expressão `Array.from(...).find(...).selected = true` foi executada normalmente. Mas claro, se a const não está sendo usada, ela não precisa existir. Basta deixar apenas a execução da expressão:

```javascript
const fetchCurrency = async mainCurrency => {
  // ...
  Array.from(secondCurrency)
    .find(({ text }) => text === currencyTwo)
    .selected = true

  startConversion()
}
```

Teste o código novamente.

Antes de continuar, vale lembrar que `fetchCurrency` pode ser invocada no final do código. Isso dá mais organização para o seu código, pq agora, todas as invocações de função estarão concentradas em um único lugar:

```javascript
amountToConvertContainer.addEventListener('input', startConversion)
firstCurrency.addEventListener('change', convertFrom)
secondCurrency.addEventListener('change', convertTo)
fetchCurrency('USD') // 👈🏻 invocação posicionada junta a outras invocações
```

`fetchCurrency` é um nome que dá a entender que a função está buscando as moedas, o que não é verdade. Existe uma invocação de `getCurrencyData` dentro dela, e essa sim está obtendo as moedas. O que maior parte do código de `fetchCurrency` faz de verdade é deixar os `<select>` preparados. Por isso, acho que renomeá-la como `setCurrencySelects`, por exemplo, pode deixar mais claro o que essa função faz.

Com a renomeação, faz sentido deixar mais descritivo também do que se trata o argumento que essa função recebe ao ser invocada. E isso você consegue fazer inserindo um objeto com uma propriedade que descreve o valor que está sendo inserido. Uma dica é nomear a propriedade do objeto com o mesmo nome do parâmetro que vc declarou na função (que está com um nome descritivo). 

Vai ficar assim:

```javascript
const setCurrencySelects = async ({ mainCurrency }) => {/*...*/}

// ...

// invocações da função
setCurrencySelects({ mainCurrency: 'USD' })
setCurrencySelects({ mainCurrency })
```

☝🏻 perceba que um destructuring foi feito no parâmetro da função. 

---

## `getConversionResult`

Dentro da `startConversion`, tem uma invocação de uma função que só é usada ali dentro, a `getConversionResult`. 

Acho que pode fazer sentido manter o código de `getConversionResult` dentro da `startConversion`, por que elas praticamente fazem a mesma coisa (manipulam os valores exibidos na tela): 

```javascript
const startConversion = () => {
  const { value: times } = amountToConvertContainer
  const { value } = secondCurrency[secondCurrency.selectedIndex]
  const { text: currencyOneText } = firstCurrency[firstCurrency.selectedIndex]
  const { text: currencyTwoText } = secondCurrency[secondCurrency.selectedIndex]
  const result = value * times

  convertedValue.textContent = `${result.toFixed(2)}`
  conversionPrecision.textContent = `${times} ${currencyOneText} = ${result} ${currencyTwoText}`
}
```

O nome `startConversion` pode dar a impressão que essa função inicia um processo de conversão da moeda, o que não é verdade. Essa função é responsável por exibir na tela a conversão, então acho que um nome que pode fazer mais sentido é `showConversion`.

---

## Erro ao mudar o valor do primeiro select

Ao mudar o valor do primeiro select, um erro está sendo lançado com a seguinte mensagem: `Cannot destructure property 'conversion_rates' of '(intermediate value)' as it is undefined. - app.js:20`.

Ou seja, por algum motivo, `conversion_rates` está armazenando undefined e um destructuring está sendo feito em undefined. Esse erro vem dessa linha: 

```javascript
const { conversion_rates } = await getCurrencyData(mainCurrency)
```

Primeira coisa a fazer: console.log acima da linha, para ver o que `mainCurrency` está armazenando. 

Ao modificar o valor do select, vc verá que é ela que está armazenando undefined. 

`mainCurrency` é parâmetro da função `setCurrencySelects`, então fui investigar as invocações dessa função.

Ao investigar, encontrei uma invocação dela na função abaixo, que é executada quando o valor do primeiro select é modificado:

```javascript
const convertFrom = event => {
  const mainCurrency = event.target.selectedIndex.text
  setCurrencySelects({ mainCurrency })
}
```

Coloquei um console.log pra ver o que `mainCurrency` estava armazenando e ao modificar o valor do select, bingo:

```javascript
const convertFrom = event => {
  const mainCurrency = event.target.selectedIndex.text
  console.log(mainCurrency) // undefined
  // ...
}
```

Para investigar pq ela está armazenando undefined, coloquei um console.log em para cada encadeamento de propriedade do objeto event e ao modificar o select, o resultado foi:

```javascript
const convertFrom = event => {
  console.log('event.target:', event.target)
  console.log('event.target.selectedIndex:', event.target.selectedIndex)
  console.log('event.target.selectedIndex.text:', event.target.selectedIndex.text)
  // ...
}
```

Antes de continuar lendo, teste o código acima e busque descobrir por que o erro está sendo lançado.

Acontece que `event.target.selectedIndex` resulta em `1` (ou qualquer outro número correspondente ao index da moeda selecionada).

E no final da expressão `event.target.selectedIndex` (que retorna um número), foi encadeado `.text`.

É o mesmo que fazer `1.text`. O JS até foi prestativo e tentou fazer `Number(1).text` por baixo dos panos, mas não rolou pq não existe propriedade `.text` em `1`. 

E aqui fica a pergunta... como você irá resolver isso?

O que vc pode fazer antes de ver a resolução abaixo?

Pra obter a string que foi selecionada no primeiro select, você irá precisar ir passo a passo, buscando resolver um problema de cada vez. Olha só...

Vc pode começar obtendo as referências dos `<options>` que o select contém. Teste cada passo que vou mostrar abaixo.

Essa função é callback de `firstCurrency.addEventListener`, isso significa que `event.target` retorna a prrópria referência do select no qual o escutador de evento foi encadeado:

```javascript
const convertFrom = event => {
  console.log(event.target) // <select>...</select>
  // ...
}
```

A partir dessa referência, vc pode obter os options:

```javascript
const convertFrom = event => {
  console.log(event.target.options) // [option, option, option...]
  // ...
}
```

Agora que vc obteve os options, vc precisa obter a referência do option selecionado. 

E pra fazer isso, basta usar a notação de colchetes: `event.target.options[?]`. Só que claro, vc precisa inserir dentro dos colchetes o index do option selecionado. 

E pra pegar esse index, vc pode usar, na referência dos options, a propriedade `selectedIndex`:

```javascript
const convertFrom = event => {
  console.log(event.target.options[event.target.options.selectedIndex]) // <option value="3.6725">AED</option>
  // ...
}
```

Agora que vc obteve a referência do option selecionado, pra obter o conteúdo desse option (código da moeda), vc pode encadear na referência do option a propriedade `textContent`:

```javascript
const convertFrom = event => {
  console.log(event.target.options[event.target.options.selectedIndex].textContent) // AED
  // ...
}
```

Obviamente vc não precisa deixar o código assim. Vc pode quebrar essa expressão em partes para deixar o código mais legível:

```javascript
const convertFrom = event => {
  const options = event.target.options
  const mainCurrency = options[options.selectedIndex].textContent
  setCurrencySelects({ mainCurrency })
}
```

Com o código acima, ao testar a mudança de valor no primeiro select, tudo deve funcionar normalmente.

---

## Erro ao recarregar a página

Ao recarregar a página, um erro com a seguinte mensagem é lançado: `Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'selected') - app.js:30`.

O erro corresponde a essa linha:

```javascript
.selected = true
```

Observando a mensagem do erro, você consegue entender o que está acontecendo?

A mensagem diz que "não é possível setar propriedades em undefined (setando 'selected')". 

Isso significa que `.selected` foi encadeada em undefined. Ou seja, `  Array.from(...).find((...)` está retornando undefined.

Com o que foi mostrado até aqui na análise, você consegue descobrir por que isso está acontecendo e solucionar o problema?

Fico no aguardo =)

**Comment by MivlaM** [comment]
Estava revendo as refatorações aqui, até tinha notado esses erros no console, mas não encontrei uma solução para eles não aparecerem sem prejudicar o que já estava funcionando antes na aplicação. Imagino que `Array.from(...).find((...)` está retornando undefined de forma parecida com o erro que o `mainCurrency` estava tendo que você mostrou na análise, porém, não encontrei uma solução para ele ainda :/

**Comment by Roger-Melo** [comment]
Depois de seguir o passo a passo na análise, se vc derrubar e levantar o live server, modificar o valor do 2º select e recarregar a página, o erro é exibido no console?

Se sim, quando vc vai na aba "application" do devtools e seleciona seu endereço localhost dentro de session storage (como a imagem abaixo), qual é o valor que está sendo armazenado em "currency-two"? E mais importante, qual é o tipo desse valor?
 
![Group 9](https://user-images.githubusercontent.com/29297788/215132604-2a42650c-516a-4657-b992-37ab6b5da05c.jpg)

@MivlaM

**Comment by Roger-Melo** [comment]
@MivlaM dá uma olhada [nesse vídeo](https://drive.google.com/file/d/1DlzCLc1g64T0k1oHP4iv3TTQABlFdAK9/view?usp=sharing) =)

**Comment by MivlaM** [comment]
Reproduzi o erro mencionado no vídeo aqui no computador, o tipo do valor que está sendo armazenado em currency-two é undefined

**Comment by Roger-Melo** [comment]
Aí está o erro. 

O tipo armazenado não é undefined, session storage não armazena código JavaScript, apenas string JSON.

O tipo de dado é uma string que armazena a palavra `undefined`. 

@MivlaM

**Comment by MivlaM** [comment]
Compreendi, mas esse tipo de dado vem desde o que o `Array.from(...).find((...)` está retornando?

**Comment by Roger-Melo** [comment]
Não.

Em qual parte do seu código vc está obtendo dados de session storage? É dali que vem.

@MivlaM

**Comment by MivlaM** [comment]
Roger, estava analisando o código aqui. A parte do código que uso para obter os dados de session storage é a quando uso o getItem e passo uma string 'currency-two' para ele, porém, como que eu faço a modificação nessa parte sem prejudicar o funcionamento total?

**Comment by Roger-Melo** [comment]
Essa não é a pergunta certa. 

As perguntas certas são:

1. Qual parte do meu código está inserindo undefined no session storage?
2. Como eu impeço que isso aconteça?

---

Dica: A solução pra esse tipo de coisa não acontecer já foi mostrada na análise acima, em um ajuste dentro da função `convertFrom`.

É necessário limpar o sessionStorage ou derrubar e levantar o servidor pra que ela volte a funcionar normalmente, após o ajuste acima.

@MivlaM

**Comment by MivlaM** [comment]
Parece-me que consegui arrumar esse erro que estava aparecendo ao fazer uma modificação semelhante a mostrada na análise na função `convertTo` 

```js
const convertTo = event => {
  const options = event.target.options
  const targetCurrency = options[options.selectedIndex].textContent
  sessionStorage.setItem('currency-two', targetCurrency)
  showConversion()
}
```

Seria isso?

**Comment by Roger-Melo** [comment]
Isso mesmo. Com esse ajuste, o erro que mostrei no vídeo acima não deve mais ser lançado (teste para confirmar).

Da forma com que foi feito em seu código, um request está sendo feito a cada mudança de valor nos selects. Vc verá nas aulas que eu mostro uma forma de fazer no máximo 2 requests. 

É isso. Parabéns pelo esforço =)

As observações fizeram sentido?

@MivlaM

**Comment by MivlaM** [comment]
Compreendi! Sim, as observações foram de grande ajuda para que eu pudesse entender o que pode ser aperfeiçoado no código, agradeço imensamente pela ajuda. =)

**Comment by Roger-Melo** [comment]
Legal. No que tiver dúvidas, é só abrir uma issue =)
