### ISSUE TITLE
Exercícios 

### ISSUE THREAD

**Issue by Polianeh** [roger-melo-treinamentos/curso-de-js-roger-melo#5749]
### Etapa da aula

1

### Nome da aula

Exercícios 06

### Link da aula

Exercício 06: https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/tree/master/exercicio-06

### Descreva a dúvida

Devo fazer o commit de todos os exercícios? Porque ficam aparecendo as “changes” em meu VSC e eu queria tirar sem perder as alterações nos exercícios.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Polianeh!

Não precisa comitar os exercícios no repositório do CJRM. 

Para não ver mais as mudanças, o que vc pode fazer, se quiser, é um [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) do repositório do CJRM e clonar esse fork. 

Assim, à medida em que vc for fazendo os exercícios, vc faz os commits com as mudanças pra esse fork que estará em sua conta. 

Pegou a ideia? =)

**Comment by Polianeh** [comment]
> Olá @Polianeh!
> 
> 
> 
> Não precisa comitar os exercícios no repositório do CJRM. 
> 
> 
> 
> Para não ver mais as mudanças, o que vc pode fazer, se quiser, é um [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) do repositório do CJRM e clonar esse fork para sua máquina. 
> 
> 
> 
> Assim, à medida em que vc for fazendo os exercícios, vc faz os commits com as mudanças pra esse fork que estará em sua conta. 
> 
> 
> 
> Pegou a ideia? =)

Sim, obrigada

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)
