### ISSUE TITLE
Aplicação: Quiz interativo

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#575]
Link da aplicação:

https://github.com/YureK-a/Quiz-Interativo---CJRM

Minhas maiores dúvidas foram:

- Colors:
            Eu realmente não entendi como poderia modificar as cores. Eu até consegui colocar cores novas, o problema foi que sempre que eu fazia isso, o site inteiro mudava de cor e (ou) o texto "Quiz" perdia a centralização, e depois de algumas tentativas, acabei desistindo e continuei o código.

- Simplificação do código:
            Não foi exatamente uma dificuldade, mas eu fiquei em dúvida se haviam mais possibilidades de melhorias, como por exemplo, o if que verifica as respostas corretas. Eu acho que ele deixou o código mais feio, ou pelo menos ficou difícil de se ler e entender rapidamente.

Minhas menores dificuldades foram:

- A construção do código:
            Eu cerca de 2 horas para construir o esqueleto do código. Provavelmente demorei mais 30-60 minutos no máximo para simplificar tudo. Fora as cores, minha maior dificuldade foi entender a simplificação dos ifs por meio de objetos e replicá-la, com base no exercício 18, na aplicação.

Pretendo melhorar minhas aplicações, inclusive hoje eu tripliquei o tempo que estudo normalmente, indo de 1 hora para 3 horas, e pretendo manter um ritmo semelhante a esse. Obrigado pelas aulas, professor! =)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Yure.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

@YureK-a

**Comment by Roger-Melo** [comment]
Oi Yure.

Parabéns pelo esforço em construir a aplicação =)

> Colors

Para modificar a cor de um elemento HTML com o Bootstrap, basta modificar [o nome da classe](https://getbootstrap.com/docs/5.0/utilities/background/) que aplica a cor no elemento.

A `<div>` abaixo, por exemplo, contém a classe `bg-primary` que aplica o azul padrão do Bootstrap.

```html
<div class="intro py-3 bg-primary text-center">
```

Então para deixá-la com um fundo vermelho, basta inserir a classe `bg-danger`:

```html
<div class="intro py-3 bg-danger text-center">
```

> Simplificação do código

Na real, `ifs` de uma ou duas linhas são mais legíveis que `if/else` (minha opinião). É o que recomendo usar.

Vou deixar abaixo alguns pontos de atenção baseados em critérios da análise.

## Organização de código

### Nomes dos arquivos

Sempre nomeie os arquivos da forma mais concisa possível. Não existe uma convenção oficial para nomear arquivos mas geralmente você verá essas variações:

- scriptName.js
- script-name.js
- script_name.js

Esse tipo de cuidado é importante para que a leitura aos arquivos funcione em qualquer sistema operacional (além de padronizar a nomeação de arquivos da aplicação). Escolha um e seja consistente.

## Usabilidade

### Comunicação

Tome cuidado com afirmações como "Você tem mal gosto!...". Eu não me importo, mas um recrutador pode considerar esse tipo de comunicação com o usuário um pouco grossa, e isso pode te prejudicar em um processo seletivo.

## Lógica

### Variáveis globais

`p` é uma variável global, ou seja, pode ser acessada em qualquer lugar da aplicação, então não é necessário inseri-la como valor das propriedades `p` dos objetos.

### Grouping operator na declaração da `insertResultIntoQuiz`

A declaração da função `insertResultIntoQuiz` está entre parênteses ([grouping operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping)).

Já que é apenas a declaração de uma função, os parênteses podem ser removidos.

### Nomes de variáveis e funções

Funções devem ser nomeadas como verbos que representam a ação que a função faz.

`ResultsOfQuiz` é um substantivo. Então prefira algo como `calculateQuizResult`.

A aplicação contém variáveis nomeadas em camelCase e PascalCase (primeira letra maiúscula). Escolha uma das duas convenções e seja consistente com essa escolha.

`nextSimbling` pode ser renomeada para `nextSibling` (sem o "m").

`p` é um nome vago para uma const. Para descrever bem o que ela está armazenando, prefira nomeá-la como `resultContainer`, `resultEl` ou algo do tipo ("el" é uma abreviação de "element").

### Linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

Mas, seguindo o princípio, eu adicionaria linhas em branco entre objetos e ifs e na linha 27 para separar o destructuring da manipulação do DOM. 

Também removeria a linha 19 em branco, pois é uma convenção iniciar e terminar um bloco com linhas de código. Caso contrário, o olho precisa pular linhas em branco desnecessárias e a fluidez da leitura do código é prejudicada.

Ainda seguindo o princípio de separar conceitos, eu separaria as declarações de consts por tipo:

```javascript
// antes
const form = document.querySelector('.quiz-form')
const correctAnswers = ['B', 'A', 'B', 'A']
const p = document.createElement('p')
const button = document.querySelector('button')

// depois (separação entre elementos do DOM e respostas corretas)
const form = document.querySelector('.quiz-form')
const button = document.querySelector('button')
const p = document.createElement('p')

const correctAnswers = ['B', 'A', 'B', 'A']
```

---

Novamente, parabéns pelo esforço e continue seguindo o método. Só não chega na fluência quem desiste =)

As observações acima fizeram sentido?

@YureK-a

**Comment by YureK-a** [comment]
Gostei bastante da análise, professor! Foi muito explicativa e com certeza terei ela em mente da próxima vez!

**Comment by Roger-Melo** [comment]
Show @YureK-a. Já que fez sentido vou fechar a issue, mas no que precisar, é só abrir uma nova =)
