### ISSUE TITLE
Por que usar no exercício callback(error, data), dois parametros, e não callback(data) só com um parametro, se o resultado é igual?

### ISSUE THREAD

**Issue by rezendenetto** [roger-melo-treinamentos/curso-de-js-roger-melo#5752]
### Etapa da aula

11

### Nome da aula

Correção dos exercícios da aula 03 da etapa 11 - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1289060

### Descreva a dúvida

Olá Roger,
Tudo bom?

Por que no exercícios de fazer request pra API de Pokemons você teve que invocar e declarar a função de callback com dois parametros: error e data? e ainda precisou escrever um if dentro da invocação da getPokemon pra que null não fosse rederizado no console, não bastaria ter uma função de callback que recebe apenas um parametro, por exemplo: data, que na invocação da getPokemon não seria mais necessário fazer o if pra eliminar a renderização do null no console e ainda não seria necessário criar a função logPokemonData pra evitar que no caso de um request sequencial não for bem sucedido travar a aplicação

VERSÃO MAIS COMPLETA:
```js
const getPokemon = (url, callback) => {
  const request = new XMLHttpRequest()

  request.addEventListener('readystatechange', () => {
    if (request.readyState === 4 && request.status === 200) {
      callback(null, request.response)
      return
    }

    if (request.readyState === 4) {
      callback('Não foi possível obter os dados da API', null)
    }
  })

  request.open('GET', url)
  request.send()
}

const logPokemonData = (error, data) => {
  if (error) {
    console.log(error)
    return
  }
  console.log(data)
}

getPokemon('https://pokeapi.co/api/v2/pokemon/1', (error, data) => {
  if (error) {
    console.log(error)
    return
  }
  console.log(data)

  getPokemon('https://pokeapi.co/api/v2/pokemon/2', (error, data) => {
    logPokemonData(error, data)
  })
})
```
VERSÃO SIMPLIFICADA:
```js
const getPokemon = (url, callback) => {
  const request = new XMLHttpRequest()

  request.addEventListener('readystatechange', () => {
    if (request.readyState === 4 && request.status === 200) {
      callback(request.response)
      return
    }

    if (request.readyState === 4) {
      callback('Não foi possível obter os dados da API')
    }
  })

  request.open('GET', url)
  request.send()
}

getPokemon('https://pokeapi.co/api/v2/pokemon/1', (data) => {
  console.log(data)

  getPokemon('https://pokeapi.co/api/v2/pokemon/2', (data) => {
    console.log(data)
  })
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rezendenetto!

Os 2 argumentos na função de callback foram inseridos para treinar uma possível variação entre os resultados desses argumentos (erro e sucesso). Mas pode fazer como você fez também, sem problemas =)
