### ISSUE TITLE
Métodos includes() vs Métodos contains()

### ISSUE THREAD

**Issue by RodolfoRondinely** [roger-melo-treinamentos/curso-de-js-roger-melo#5756]
### Etapa da aula

9

### Nome da aula

Removendo to-dos - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1067824

### Descreva a dúvida

Blz Pessoal,
aos 05:45 min da aula, o professor usa o método includes, e logo se vê o erro pois item é um HTML collection.

Eu estava fazendo antes do professor justamente para treinar, e é incrível como esta quase tudo igual , inclusive o nome das variavéis.

Nesta parte do codigo, para verificar se existe a classe 'delete', eu usei o método contains do classList.
Não houve erro, no meu codigo , então gostaria de saber se há algum problema em usá-lo ?

codigo abaixo 👍 
```js
const ulTodo =document.querySelector('.todos-container')

ulTodo.addEventListener('click', event =>{
    const clickedElement  =event.target
    
    if(clickedElement.classList.contains('delete')){
        clickedElement.parentElement.remove()
    }
})
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RodolfoRondinely.

Eu usei o `includes`, mas o `contains` pode ser usado tranquilamente neste caso, ele até deixa o código mais conciso =)

**Comment by RodolfoRondinely** [comment]
Obrigado Roger, abandonei todos os outros cursos, e fora meu trabalho, estou focado no CJRM. 
Parabéns pela didática !!!
