### ISSUE TITLE
Resumo da Aula-02-02 da Etapa-02 Conditiona If

### ISSUE THREAD

**Issue by romulofrontend** [roger-melo-treinamentos/curso-de-js-roger-melo#5763]
# ETAPA-02 | AULA-02-02 | CONDITIONAL IF

## IF
- Estrutura condicional
- Verifica SE uma determinada condição é verdadeira
- Caso seja, o bloco de código é executado uma vez

---

## SINTAXE - EXPLICAÇÃO
```javascript
if (condição){
  bloco de código
}
```

---

## FLUXO DO CÓDIGO
1) if | tipo de condicional. Vai verificar se a condição é true
2) (condição) | Caso seja verdadeira pode executar o bloco de código
3) { bloco de código } | Trecho de código a ser executado
4) Caso haja alguma linha de código após bloco de código essa será executada

---

## EXEMPLO PRÁTICO 01 - TESTE DE VARIÁVEL
```javascript
// variável para armazenar um determinado valor. 
const idade = 18;

// tipo de condicional (condição)
// se a condição for verdadeira o bloco de código será executado
if (idade >= 18){

  //bloco de código
  console.log("Igual ou Maior de 18 anos")
}
```

**EXIBIÇÃO NO CONSOLE**
```
Igual ou Maior de 18 anos
```
---

## EXEMPLO PRÁTICO 02 - TESTE DE ARRAY
```javascript
// variável para armazenar um determinado valor / array.
const simpsons = ["Bart", "Home", "Marge", "Lisa", "Maggie"]

// tipo de condicional (condição)
// se a condição for verdadeira o bloco de código será executado
if (simpsons.length > 3){

  //bloco de código
  console.log("Os Simpsons possuem mais de 3 personagens principais")
}
```

**EXIBIÇÃO NO CONSOLE**
```
Os Simpsons possuem mais de 3 personagens principais
```
---

## EXEMPLO PRÁTICO 03 - TESTE DE STRING
```javascript
// variável para armazenar um determinado valor / array.
const senha= "oi123456"

// tipo de condicional (condição)
// se a condição for verdadeira o bloco de código será executado
if (senha.length >= 8){

  //bloco de código
  console.log("Senha possui 8 caracteres ou mais")
}
```

**EXIBIÇÃO NO CONSOLE**
```
Senha possui 8 caracteres ou mais
```

**Comment by MivlaM** [comment]
Boa @romulofrontend rumo à fluência! 🔥
