### ISSUE TITLE
Resumo da Aula 02-04 da etapa 03 - O método forEach e callbacks

### ISSUE THREAD

**Issue by gerafimjoaquim** [roger-melo-treinamentos/curso-de-js-roger-melo#5765]
## forEach
É um método que invoca uma funcção de callback 1 vez em cada elemento iterado de um determinado array.
A função que o ```forEach``` invoca retorna ```undefined ```. O valor que a ```callback``` retorna é descartado
A função de ```callback``` é invocada com pelo menos 4 argumentos, sendo que apenas 1 é obrigatório:

1. item actual que está sendo iterado (este é obrigatório)
2. index do item actual que está sendo iterado
3. array no qual o método ```forEach``` foi encadaeado
4. o valor a usar com ```this```  ao invocar a ```calback```

o método ```forEach não é encadeável e não modifica o array ao qual o método foi encadeado

Não tem como parar o ```forEach``` enquanto excuta a ```callback``` e sempre invoca uma funçao síncrona

**Comment by MivlaM** [comment]
Boa @gerafimjoaquim rumo à fluência! 🔥
