### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by maxgabrieldev** [roger-melo-treinamentos/curso-de-js-roger-melo#5769]
console.log // pode receber mais de um valor
ex  : consolte.log(a, b)

variável '**let**' pode ter um novo valor atribuído
variável '**const**' não pode ter o valor alterado

**Comment by MivlaM** [comment]
Boa @maxgabrieldev rumo à fluência! 🔥
