### ISSUE TITLE
Constantes, variáveis e comentários - Aula 01-06

### ISSUE THREAD

**Issue by PauloRDev** [roger-melo-treinamentos/curso-de-js-roger-melo#5776]
Papel de uma variável é armazenar um valor (nome, email, número...)

    Meios de declarações de variaveis:
  
    - let
    - var 
    - const    

sinal de igualdade ' = ' representa atribuição.

Exemplo de uso de let:

```js
let age = 24
let currentYear = 2023

console.log(age, currentYear)
```

 console.log, mostra os valores recebidos das variáveis no console do navegador.
 o valor recebido por let pode ser alterado mais tarde.

```js
age = 25

console.log(age)
```

Apartir desse ponto o valor de age é alterado
Podemos alterar o valor mesmo sem utilizar o let na frente de age.

Exemplo do uso de const:

```js 
const points = 100
 points = 101
console.log(points)
```

 Nesse caso o console irá retornar erro
 Pois const (é uma constante) e valor dela não pode ser alterado
 Desse modo points = 101, não é possível de ser atribuido como novo valor

```js 
var score = 75
console.log(score)
```

 Var é uma maneira mais antiga de declarar uma variável
 tem o mesmo propósito de let.

   Regras para nomear variáveis:
   - CamelCase
   - não podemos iniciar ela com números
   - algumas palavras não são permitidas, pois já são reservadas da linguagem.
   - ter sempre nomes claros e suficientes

**Comment by MivlaM** [comment]
Boa @PauloRDev rumo à fluência! 🔥
