### ISSUE TITLE
Resumo da Aula Adicionando o JavaScript a uma página web - Aula 01-04 da etapa 1

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5779]
![image](https://user-images.githubusercontent.com/106329803/214393338-6b28cf8b-5f4a-48d7-9f2f-0fffa2434f6d.png)

**Comment by MivlaM** [comment]
Boa @rafael-rodrigues01 rumo à fluência! 🔥
