### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 00

### ISSUE THREAD

**Issue by Francimildo** [roger-melo-treinamentos/curso-de-js-roger-melo#5782]
Vimos os métodos: lastIndexOf(), slice() e replace()
lastIndexOf() : retorna o índice da última ocorrência do argumento informado entre os parênteses do método.
slice() : retorna uma "fatia" da string em questão de acordo os os argumentos informados. Índice inicial e índice final sendo este segundo o início do pedaço da string que não se quer mais capturar.
replace() :  substitui o caractere informado como primeiro argumento pelo que foi informado como segundo argumento.

**Comment by MivlaM** [comment]
Boa @Francimildo rumo à fluência! 🔥
