### ISSUE TITLE
Resumo da Aula Factory functions e composição de objetos - Aula 03-09 da etapa 14

### ISSUE THREAD

**Issue by ananopaisdojavascript** [roger-melo-treinamentos/curso-de-js-roger-melo#5788]
# Factory functions e composição de objetos - Aula 03-09 - Resumo

## O que são funções de fábrica?

São funções que não são classes, nem objetos, nem funções construtoras, mas que permitem a criação de novos objetos sem a palavra-chave `new`.

 ```jsx
const createStudent = (name, email) => {
  return {
    name,
    email
  }
 }

const ana = new Student('Ana', 'ana@email.com')
const pedro = new Student('Pedro', 'pedro@email.com')
 ```

## Como criar um valor acessado apenas dentro de uma função de fábrica?

É só criar uma variável dentro dessa função. Ao tentar acessar esse valor fora da função, o resultado é `undefined`.

 ```jsx
const createStudent = (name, email) => {
  let counter = 0 // Valor que só pode ser acessado dentro da função
  return {
    name,
    email
  }
 }

 ```

## Como fazer para que o objeto acesse um valor privado?

Nesse caso, é só criar um método que retorne esse valor 

 ```jsx
const createStudent = (name, email) => {
  let counter = 0 // Valor que só pode ser acessado dentro da função
  return {
    name,
    email,
    increment() {
      return counter++ // Método que vai permitir o acesso do objeto e a atualização do valor
    }
  }
 }

const ana = new Student('Ana', 'ana@email.com')
console.log(ana.increment())
 ```

**Comment by MivlaM** [comment]
Boa @ananopaisdojavascript rumo à fluência! 🔥
