### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 03 da etapa 02 - Aula 01-01

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#579]
Olá Roger, boa tarde, tudo certo? Na questão 04, eu resolvi da seguinte forma:
```js
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']

let newSentence = ''

for(let i = 0; i < sentence.length; i++ ){
if(!(sentence[i] === 'certeza')){
  newSentence += `${sentence[i]} ` 
}
}
console.log(newSentence)
```
Eu realmente esqueci do `continue` e por isso utilizei o operador lógico `!(NOT)`. Não sei, mas parece mais conciso, pouca coisa.

Agora, a questão 05, confesso que eu fiz uma grande bagunça, embora tenha resolvido. Vou refazer da forma que você sugeriu lá no começo do curso, apenas queria mostrar minha resolução:
```js

const randomValues = [57, false, 'JS', [], true, 'HTML', 31, null, false, 'CSS',
 97, true, 'Git', 11, 'sticker', false, 'GitHub', true, null]

let stringValues = [] /*Nessa parte acredito que além dos 
nomes das variáveis estarem diferentes, eu atribuí imediatamente 
um array para os valores de string, ao invés de declarar uma 
variável contadora como nos outros casos, assim, quando foi
 preciso substituir a vírgula pelo 'e', apenas invoquei o método
 .replace(), lá no final. Mesmo assim, eu sei que está com 
baixa legibilidade.*/

let amountOfBooleans = 0

let numberOfIterations = 0

for(let i = 0; i < randomValues.length; i++){

  numberOfIterations += 1 // Aqui eu quis saber de imediato a quantidade de iterações

  if (typeof randomValues[i] === 'string' ) {
    stringValues.push(randomValues[i])
    
 }  
if(stringValues.length === 4){
    break /* Neste caso como eu já havia declarado 
um array, achei que o método .length 
era o mais correto a se fazer*/
  } 
  if(typeof randomValues[i] === 'boolean'){
    amountOfBooleans += 1 /* Aqui eu apenas contei o número 
de Booleans, acredito que tenha sido o mesmo na sua resolução*/
  }

}

let stringValuesReplacement = String(stringValues).replace(',G', ' e G')
 // O .replace() que eu mencionei

console.log(`3 informações sobre o array randomValues:
  - As primeiras 4 strings são ${stringValuesReplacement};
  - Até que as primeiras 4 strings fossem iteradas, ${amountOfBooleans} booleans 
  foram iterados;
  - O array foi iterado por ${numberOfIterations} vezes.`)
 ``` 

Por diversas vezes nesse exercício acreditei que estava fazendo tudo errado e por isso fui me concentrando em executar cada parte do proposto. Quando você foi corrigindo e acrescentando 'if's, vi que eu não estava errado, pelo menos não nisso. Quando finalmente o resultado era o que o exercício pedia, eu não notei a necessidade de refatorar algumas partes, como os 'typeof', porque são palavras em inglês que indicam exatamente que 'se tal índice do array x for do tipo string e etc...', mas entendi a necessidade e refarei. Eu refiz os exercícios desde o primeiro até o anterior  a esse, vou refazer do primeiro até esse. 

A dúvida é realmente no exercício 04 e se puder apontar se aparentemente estou evoluindo ou não, fico agradecido! Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcus Vinicius.

O `continue` foi usado no exercício 04 apenas para revisão. A forma com que você resolveu é válida sim. Apenas certifique-se de que entendeu o `continue`.

Sobre o exercício 05, a pegada é essa mesmo. Fazer funcionar primeiro e ir melhorando aos poucos =)

E sim, só de você estar exercitando sua habilidade com a linguagem nos desafios com certeza você está evoluindo (mesmo que não perceba ou perceba pouco). Quando alguém constrói uma casa, a construção da base é a parte mais demorada e menos sexy. Quem passa em frente a construção vê nada acontecer. Ninguém tira foto da base da casa e posta no instagram. Só é legal mostrar a casa pronta. Porém, o que sustenta a casa é a solidez da base. Quanto mais alta a torre, maior a fundação.

Você está nos trilhos rumo à fluência. Continue seguindo o método e atingir os resultados que deseja será só uma questão de tempo.

@WebDevCampos

**Comment by Roger-Melo** [comment]
Excelente, @WebDevCampos. Só não chega na fluência quem desiste. No que precisar, estamos às ordens =)
