### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5792]
const postTitle = 'E bolacha ou biscoito'
const posrtAuthor = 'Matheus Saad'
const postComments = 15

#### Usando template strings

const postMessage =  `O post ${postTitle}, do ${posrtAuthor }, tem ${postComments }  comentarios` 

// Resultado: O post E bolacha ou biscoito, do Matheus Saad, tem 15 comentarios

---------

#### Quando usar ?

 Se voce nao vai interpolar variaveis na string, usar aspas ou quebrar linhas, NAO PRECISA USAR Template Strings,

Se a string que voce esta usando precisa conter variaveis, aspas ou e um templace html, E RECOMENDAVEL USAR   Template Strings,

**Comment by MivlaM** [comment]
Boa @dzpoke rumo à fluência! 🔥
