### ISSUE TITLE
Resumo da Aula Adicionando o JavaScript a uma página web - Aula 01 da etapa 04

### ISSUE THREAD

**Issue by hugolealtech** [roger-melo-treinamentos/curso-de-js-roger-melo#5793]
Primeiro, cria-se uma pasta e dentro da pasta cria-se um arquivo index.html
após, aperta ! + tab para que uma instrura de HTML seja exibida.

Em head, altera-se o título da página e depois abre-se um <script> em body.
na mesma pasta cria-se um arquivo chamado app.js
Em body cria-se a src='./app.js'

Já em app.js, basta criar um alert('Helo World') e a imagem será exibida no browser.

Para que funcione no browser é preciso instalar o aplicativo Opem Live Server.

Após isso basta adicionar à página ao aplicativo.

**Comment by MivlaM** [comment]
Boa @hugolealtech rumo à fluência! 🔥
