### ISSUE TITLE
Resumo da Else e else if statements - Aula 02-03 da etapa 02

### ISSUE THREAD

**Issue by salviotonon** [roger-melo-treinamentos/curso-de-js-roger-melo#5794]
# A condicional if e else

- o comando `if` e `else`  é utilizado para executar ações diferentes dependendo de condições específicas, Ex:

```js
if (condição) {
  // código a ser executado se a condição for verdadeira
} else {
  // código a ser executado se a condição for falsa
}
```

- o comando `else if` pode ser utilizado para aumentar o número de condições a serem exigidas, Ex:
```js
if (condição1) {
  // código a ser executado se a condição 1 for verdadeira
} else if (condição2) {
  // código a ser executado se a condição 1 for falsa e a condição 2 for verdadeira
} else {
  // código a ser executado se nenhuma das condições for verdadeira
}
```

## Pontos Importantes e que necessitam de atenção 🔴

- é possível utilizar operador de comparação e operadores lógicos para criar condições complexas
- é importante entender que quando um bloco if se torna verdadeiro, ele será executado e o restante das condicionais não serão verificados
- É possível usar o comando `if` sem `else`, porém somente para verificar uma condição específica.

## Prestar atenção nesses ERROS ❌

1. Esquecer de usar parênteses para delimitar a condição: é importante lembrar de usar parênteses para delimitar a condição, caso contrário o código pode dar erro.
```
if x > 0 // Incorreto
if (x > 0) // Correto
```
2. Esquecer de usar chaves para delimitar o bloco de código: é importante lembrar de usar chaves para delimitar o bloco de código, caso contrário o código pode dar erro ou somente a primeira linha será executada. 
```
if (x > 0)
  console.log("x é maior que 0");
  console.log("isto também será executado"); // Incorreto, este código não está dentro do if

```
3. Esquecer de usar o sinal de igualdade: é importante lembrar de usar o sinal de igualdade (== ou ===) para comparar valores, caso contrário o código pode dar erro.
```
if (x = 0) // Incorreto
if (x == 0) // Correto

```
4. Esquecer de usar o else: é importante lembrar de usar o else para tratar as condições caso contrário, caso contrário o código pode dar erro ou não tratar todas as possibilidades.

```
if (x > 0) {
  console.log("x é maior que 0");
}
console.log("não se sabe se x é maior ou menor que 0"); // Incorreto


```

**Comment by MivlaM** [comment]
Boa @salviotonon rumo à fluência! 🔥
