### ISSUE TITLE
Resumo da Aula A Aula Mais Importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by dev-pedro** [roger-melo-treinamentos/curso-de-js-roger-melo#5795]
# A Aula mais Importante do CJRM

### Resumo

> **Fluência em JavaScript:**

> Fluência em javascript é construir Apps Web com javascript puro.

#### Coelho ou Tartaruga

Não importa a velocidade que você faz as aulas, mas sim seguir o passo a passo e ter constância, observar os pontos fracos e corrigir, não perder o foco.

> Rápido é devagar para chegar na fluência, o objetivo é não parar.

CJRM **NÃO** é competição e sim uma jornada, mais uma vez o importante é começar e não parar.

##### Marcos da Jornada à Fluência

![](file:///home/pedro/Dropbox/CJRM/Documentos/marcos_da_Jornada_a_fluencia.jpg?msec=1674646411890)

1. Assistir a aula inalgural
  
      -- Fazer as anotações importantes dessa aula que é para estar contida nesse resumo.
  
      -- A importância de saber javascript puro é que libs e frameworks vem e vão e o linguagem javascript permanece.
  
2. Postar resumo de cada aula
  
  Ao postar os resumos das aulas utilizar os templates conforme a necessidade e de acordo com as opções disponíveis nas issues do repositório no github [curso-de-js-roger-melo]([[Issues · roger-melo-treinamentos/curso-de-js-roger-melo · GitHub](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues)](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues)) (Resumo | Aplicação | Dúvida)
  
  As vantagens de postar os resumo, dúvidas, e informações são várias:
  

    -- Sintax Highlighting

    -- Pesquisas são indexadas

É possivel pesquisar e filtrar as issues por label, conteúdo...

Ao postar um issue de dúvida se atentar para a forma correta de preencher os dados.

- ETAPA -> NOME DA AULA -> LINK DA AULA -> DESCREVER A DÚVIDA

Seguir a sequência e cronologia do curso, usar o [[MDN](https://developer.mozilla.org/en-US/)](https://developer.mozilla.org/en-US/) (versão inglês) como consulta das libs javascript.

3. Revisão Raio-X

Se o código que eu estiver fazendo nos exercícios ficar diferente da resolução do professor, devo apagar meu código refazer o exercício do zero sem ver a **aula de correção**, caso eu trave e não consiga fazer o exercício posso consultar as minhas anotações e o resumo da aula e até o [[MDN](https://developer.mozilla.org/en-US/)](https://developer.mozilla.org/en-US/), quando esclarecer a minha dúvida apagar todo o exercício e implementar novamente sozinho do zero.

Isso vai fazer o cerebro fixar na resolução do problema.

    -- Revisão Raio-X é a forma de revisar usnago engenharia reversa, abaixo as etapas desse método:

##### Passo 1

Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios. Se você estiver na primeira aplicação, comece à partir da primeira bateria.

Se você estiver na segunda aplicação, faça a revisão raio-x partindo da primeira bateria de exercícios após a aplicação passada (primeira), e assim por diante.

##### Passo 2

Quando travar em um exercício, assista a correção, apague o código e implemente-o novamente, sozinho.

Se não conseguir implementar sem olhar a correção do exercício, veja a correção. Nessa fase, você notará que provavelmente suas dúvidas sobre o exercício vão ficar mais específicas.

Após sanar a dúvida, apague o código e implemente-o, sozinho.

##### Passo 3

Execute o item acima quantas vezes forem necessárias para que seu cérebro entenda o padrão de resolução do exercício.

##### Passo 4

Após executar os 3 passos acima, parta para o próximo exercício.

##### Passo 5

Faça isso até chegar no ponto do treinamento em que você está agora. As chances são de que você estará mais afiado para fazer os exercícios atuais e construir a próxima aplicação sozinho(a).

E claro, se mesmo executando essa Revisão Raio-x a dúvida permanecer, não hesite em abrir uma issue.

Ficar afiado para construir aplicações sozinho(a) não vai ser fácil, não vai ser prazeroso.

Mas a longo prazo, esse hábito da Revisão Raio-x vai te ajudar a fundar o seu alicerce para construir aplicações com JavaScript puro =)

4. Monte seu portifólio

    -- Ao montar seu portifólio não exagerar em quantidade de projetos e sim na qualidade, melhor ter 5 projetos acabados e bem feitos do que ter vários e com péssima qualidade.

    -- Não deixar seus Projetos apenas no github, hospedalos em outra plataforma, **garantir que seu projeto rode para pessoas leigas**, afinal o entrevistador pode não conhece de código.

5. Se candidatar as vagas

    -- *Se preparar para que o medo seja menor pois a segurança no que se faz diminui o medo de agir.*

6. Implementar Feedbacks dos recrutadores

    -- Identificar onde pode melhorar nas entrevistas e aplicar nas próximas.

    -- Pedir feedbacks das pessoas da área que passaram pelos mesmos desafios.

7. Ser contratado
  
8. Comunicar sua contratação
  

    -- Inspira outras pessoas que estão trilhando o caminho que você trilhou, reconhecer que se voce chegou ate a fase 8 foi porque houve muito empenho e ajuda de pessoas ao seu lado e nada mais justo de compartilhar esse momento tão importante e feliz.

**Comment by MivlaM** [comment]
Boa @dev-pedro rumo à fluência! 🔥
