### ISSUE TITLE
Dúvida sobre uso de let ou const ao criar um array vazio que receberá novos itens

### ISSUE THREAD

**Issue by salviotonon** [roger-melo-treinamentos/curso-de-js-roger-melo#5796]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370901

### Descreva a dúvida

# Dúvida sobre arrays vazios.

Eu estou criando um novo array vazio no meu código e gostaria de saber se devo declará-lo como let ou const. Sabendo que este array vazio vai receber novos itens no decorrer do código, qual é a melhor opção?

```
const isOdd = [];
let isEven = [];
```

das duas formas é possível, e mesmo que eu declare como const eu consigo fazer um push para dentro do array, em um primeiro momento eu acreditava que ocorreria um erro declarando como uma const, pois o array esta sendo alterado, existe uma boa prática nesse ponto? ou no fim das contas é preciso analisar o codigo como um todo?

Desde já, agradeço pela ajuda.

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @salviotonon

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

## Eu estou criando um novo array vazio no meu código e gostaria de saber se devo declará-lo como let ou const. Sabendo que este array vazio vai receber novos itens no decorrer do código, qual é a melhor opção?

Sim, existe uma boa prática, e usualmente, prefira usar const no lugar de let, quando possível.

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt). Veja como funciona na prática no exemplo abaixo.

```js
// Declarando um array com let
let randomArray = ["1", "2", "3", "4"]

randomArray = 2 // reatribuímos o valor desse array para 2

console.log(randomArray) // 2 é exibido no console
``` 

No exemplo acima, o array `randomArray` foi declarado com uma let, e por causa disso, é possível fazer uma reatribuição de valor e após isso, se verificarmos o valor desse array no console, você vai ver que 2 aparecerá. Isso acontece pois a let permite que você faça reatribuições de valor.

```js
// Declarando um array com const
const randomArray = ["1", "2", "3", "4"]

randomArray = 2 // Tentativa de reatribuir o valor desse array para 2

console.log(randomArray) // Um erro é exibido no console
```

Agora, o array `randomArray` foi declarado com uma const, e por causa disso, não é mais possível fazer uma reatribuição de valor pois a const impossibilita esse tipo de operação, no lugar do resultado, aparece um erro "Uncaught TypeError: Assignment to constant variable", que basicamente diz que não é possível fazer reatribuição de valor com uma const.

Você aprenderá mais sobre let e const conforme for avançando no treinamento =)

Respondi a sua dúvida? Sinta-se livre para deixar um comentário logo abaixo, caso ficou com alguma outra dúvida, te ajudarei =)

**Comment by salviotonon** [comment]
massa! Então declarando com const eu adiciono uma camada a mais de "segurança" caso ao longo do código tente reatribuir um valor para essa variavel. entendi e faz total sentido escolher const na maioria das vezes. valeuu ✍

**Comment by MivlaM** [comment]
No que precisar, é só abrir uma nova issue =)
