### ISSUE TITLE
Etapa 10, Correção dos exercícios da aula 02 da etapa 09 - Aula 01-01

### ISSUE THREAD

**Issue by brenoSSilva** [roger-melo-treinamentos/curso-de-js-roger-melo#58]
Tenho duas dúvidas em relação a essa correção de exercícios:
1º - Na primeira parte foi feito a refatoração da função de remoção dos to-dos: 
```js 
const removeTodo = clickedElement => {
     const trashDataValue = clickedElement.dataset.trash
     const todo = document.querySelector(`[data-todo="${trashDataValue}"]`)
     
     if(trashDataValue){
          todo.remove()
     }
}
```
Dúvida: Sabendo que o ```document.querySelector()``` obtém a referência do primeiro elemento que atenda ao seletor css. Se na lista de to-dos inserirmos vários todos com o mesmo ``` textContent ``` que por consequência terão o mesmo valor em ``` data-todo ``` e em ```data-trash```, porque ao clicarmos no ícone da lixeira para remover um to-do apenas aquele to-do expecífico é removido ?

2º - Em relação a refatoração da função de adicionar to-dos:
```js 
const addTodo = inputValue => {
     if(inputValue.length){
          todosContainer.innerHTML += `
          <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
               <span>${inputValue}</span>
               <i class="far fa-trash-alt" data-trash="${inputValue}"></i>
          </li>`
          event.target.reset()
     }
}
```
Dúvida: Porque o ```event.target.reset()``` é acessível dentro da função ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Breno.

> Dúvida: Sabendo que o ```document.querySelector()``` obtém a referência do primeiro elemento que atenda ao seletor css. Se na lista de to-dos inserirmos vários todos com o mesmo ``` textContent ``` que por consequência terão o mesmo valor em ``` data-todo ``` e em ```data-trash```, porque ao clicarmos no ícone da lixeira para remover um to-do apenas aquele to-do expecífico é removido ?

Se há vários to-dos com os mesmos `textContent` e `data-todo`, como o `querySelector()` obtém a referência do 1º elemento que ele encontrar, esse elemento não será, necessariamente, exatamente o mesmo da lixeira que você clicou.

Se quiser comprovar, declare uma `let counter` iniciando em `0` no topo do código e, dentro da `addTodo`, adicione um atributo `data-counter` na `<li>` e um incremento da counter antes do fim da função.

Crie os dois to-dos idênticos e os inspecione. Você verá que ao clicar na lixeira do `data-test="1"`, o `data-test="0"` será removido.

No final das contas, não faz sentido ter vários to-dos com o mesmo texto e `data-todo`. Se isso acontecer, tanto faz qual deles será removido, pois são todos iguais.

---

> Porque o `event.target.reset()` é acessível dentro da função ?

Eu deveria ter deixado ele lá dentro do callback do submit do `formAddTodo`. Só vi ele depois que gravei o vídeo. Falha minha.

Como não existe um objeto `event` dentro da `addTodo`, esse `event` está referenciando a variável global [window.event](https://developer.mozilla.org/en-US/docs/Web/API/Window/event). Quando um evento é disparado no DOM, essa variável também recebe o objeto `SubmitEvent` que recebido no parâmetro `event` do callback do submit do `formAddTodo`.

Mas, mesmo que recebam o mesmo objeto, não é recomendado usar o `event` global. Um dos motivos é que é uma variável não suportada em todos os browsers.

Então é melhor mover a invocação do `event.target.reset()` para dentro do callback do submit do `formAddTodo`. Ficaria assim:

```javascript
formAddTodo.addEventListener('submit', event => {
  event.preventDefault()
  
  const inputValue = event.target.add.value.trim()
  
  addTodo(inputValue)
  event.target.reset()
})
```

Ficou mais claro?

@brenoSSilva

**Comment by brenoSSilva** [comment]
Oi Roger. Ficou mais claro em relação à segunda dúvida, que existe uma variável global ```window.event``` que recebe o evento de submit. 

Mas em relação à primeira dúvida eu ainda não entendi. Não consegui aplicar bem o que você sugeriu.

**Comment by Roger-Melo** [comment]
> Edição: Roger, desculpe, eu acabei de realizar um teste aqui e verifiquei, adicionei elementos com valores iguais, cliquei pra remover o elemento do fim da lista e acabou removendo o elemento do inicio da lista. o ```querySelector()``` encontrou o primeiro elemento e este foi removido. Muito obrigado pela paciência e pela sua atenção, pode fechar a issue.

Isso mesmo O `querySelector()` sempre remove o 1º elemento (de cima para baixo) no DOM que corresponde ao seletor CSS que você especificou =)

Já que ficou mais claro, vou fechar a issue. Mas no que precisar, pode abrir outra. Tô aqui para te ajudar =)
