### ISSUE TITLE
Resumo da Aula Else e else if statements - Aula 02-03 da etapa 02

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#580]
# else

Todo *else* tem um *if* ao qual ele é associado. Caso a condição do *if* associado seja falsa, o bloco "interno" do *else* é executado.
 
Senão(condição "anterior" é falsa), faça!.

* else{//Código que será executado se a condição do if associado for falsa} 
	
```js
let variable_1 = 8;
let variable_2 = 9;

if(variable_1 > variable_2){
    console.log("A primeira variável é maior que a segunda");
}else{
    console.log("A segunda variável é maior que a primeira");//A segunda variável é maior que a primeira
} 
```

Podemos usar *else if* (senão se) para verificar múltiplas condições. Se um *if*, encadeado e anterior à um *else if*, possui condição falsa, o *else if* é executado  e, se sua condição for verdadeira, o código entre suas chaves é executado.

* else if(condição){//Código que será executado se a condição for verdadeira}

```js
let variable_1 = 8;
let variable_2 = 8;

if(variable_1 > variable_2){
    console.log("A primeira variável é maior que a segunda");
}else if(variable_1 < variable_2 ){
    console.log("A primeira variável é menor que a segunda");
}else if(variable_1 === variable_2 ){
    console.log("A primeira variável é igual a segunda");//A primeira variável é igual a segunda
} 
```
Apenas um dos blocos de código encadeados será executado, pois,  mesmo que mais de *else if* tenha condições verdadeiras, assim que uma condição
for verdadeira, o "senão" de todos os outros *else if* não serão satisfeitos:

```js
let variable_1 = 8;
let variable_2 = 8;

if(variable_1 > variable_2){
    console.log("A primeira variável é maior que a segunda");
}else if(variable_1 <= variable_2 ){
    console.log("A primeira variável é menor ou igual a segunda");//A primeira variável é menor ou igual a segunda
}else if(variable_1 === variable_2 ){
    console.log("A primeira variável é igual a segunda");
} 
```
	

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ThiagoDeMorais! Rumo à fluência! 🔥
