### ISSUE TITLE
ETAPA 01 - AULA 6 Constantes, variáveis e comentários 

### ISSUE THREAD

**Issue by Phlopes90** [roger-melo-treinamentos/curso-de-js-roger-melo#5805]
Constantes, variáveis e comentários 
Let Age = 38
O igual é interpretado com atribuição, ou seja, Age recebe 38.
As varíáveis podem sofrem modificação, ou seja, o valor pode variar, retribuindo outro valor;

let age = 32
let currentYear = 2023

console.log(age,currentYear)   Console( 32  2023)

age = 34
console.log(age) 
Console
32 2023
34

A CONST é ultilizado para que não haja essa variação do LET

Antigamente usava se o VAR

Codigo da Aula

let age = 32
let currentYear = 2023

console.log(age,currentYear)

age = 34
console.log(age)

const points = 100
console.log(points)

var score = 75
console.log(score)

score = 65
console.log(score)

Para fazer comentarios de uma linha usa se ( //)
Para fazer comentarios de mais linhas (/*let name*/)

**Comment by MivlaM** [comment]
Boa @Phlopes90 rumo à fluência! 🔥
