### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5806]
![image](https://user-images.githubusercontent.com/106329803/214658717-fb662f51-0f1c-4921-bd89-3d36e6bcf101.png)
![image](https://user-images.githubusercontent.com/106329803/214658918-7d6db867-a5c0-4145-aa41-222e13a36a09.png)
![image](https://user-images.githubusercontent.com/106329803/214658996-82d5bcd0-6675-449f-bc09-3db802992cdf.png)

**Comment by MivlaM** [comment]
Boa @rafael-rodrigues01 rumo à fluência! 🔥
