### ISSUE TITLE
Etapa 09, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by diegobaena89** [roger-melo-treinamentos/curso-de-js-roger-melo#582]
Boa noite, professor. Tudo bem? :)
Estou fazendo os exercícios dessa etapa 09 e, quando fui ver as correções depois de eu tê-los feito, percebi que no exercício de número 06 o senhor invoca os métodos filnter() e depois o map() para a resolução do exercício.
Contudo, eu fiz o contrário, da seguinte forma:

```js

const friends = [
  { id: 1, name: 'João', nearMe: true },
  { id: 2, name: 'Matheus', nearMe: true },
  { id: 3, name: 'Luana', nearMe: false },
  { id: 4, name: 'Nilson', nearMe: true },
  { id: 5, name: 'Solange', nearMe: false }
]

const newArrayOfFriends = friends.map(friend => {
  return {
    id: friend.id,
    name: friend.name,
    nearMe: friend.nearMe,
  }
}).filter(nearFriend => nearFriend.nearMe)
console.log(newArrayOfFriends)

```

Além disso, como o senhor deve ter notado, ao invocar o método map(), fiz a cópia do array 'friends'  como tínhamos feito no exercício 02.
Está errado fazer desse jeito?

Muito obrigado e tenha um ótimo dia!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Diego.

Legal. O interessante é que cópias de objetos sejam criadas quando é necessário modificar o objeto. Nesse caso, ao invés de modificar o objeto original, é melhor criar uma cópia do objeto original e modificar a cópia. Assim, a referência do objeto original não é perdida. Isso é um conceito de programação funcional chamado imutabilidade. Você ainda chegará em aulas em que falo sobre isso.

A forma com que você fez não está errada não. Apenas não é tão necessária por que nesse caso, os objetos não serão modificados, apenas ordenados no novo array que o map criou.

No exercício 02 eu só quis reforçar que objetos são tipos de referência e se uma cópia de cada objeto não fosse criada de forma explícita, o map iria referenciar exatamente os mesmos objetos, ao invés de copiá-los (cópias são executadas apenas com tipos primitivos).

Sacou a ideia?

@diegobaena89

**Comment by diegobaena89** [comment]
Entendi perfeitamente, professor.
Muito obrigado pela explicação!

**Comment by Roger-Melo** [comment]
Legal @diegobaena89. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
