### ISSUE TITLE
Resumo da Aula Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5822]
**Qual é a função da variável no JS?**
R: Armazenar um tipo de dados para o dev. Pode ser do tipo: *String ou Number.*

O símbolo( = ) é lido como atribuição e não como símbolo de igual. O ``` console.log() ``` pode receber mais de um valor, basta separa-los com uma vírgula. 

Quando não quiser que o valor de sua variável seja alterado usar a atribuição ```const``` Nome de variáveis não podem começar com números.

**Comment by MivlaM** [comment]
Boa @Luis-avellar rumo à fluência! 🔥
