### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5829]
const age = 31

#### "==" igual a' e 'diferente de'

* Operador "==" comparacao de tipos diferentes podem resultar em uma conversao interna que esta sendo comparado para  string, por isso algumas comparacoes podem resultar em true

console.log(age  == 31) // true
console.log(age  == '31') // true

console.log(age  !=  31) // true
console.log(age  !=  '31') // true

#### "===" 'igual a, e do mesmo tipo ' e 'diferente de, e do mesmo tipo'

console.log(age === 31)  //true
console.log(age === '31') //false

console.log(age !== 31)  /// true 
console.log(age !== '31')  //false

**Comment by MivlaM** [comment]
Boa @dzpoke rumo à fluência! 🔥
