### ISSUE TITLE
Resumo de uma overview sobre tipos de dados - Aula 02-02 da etapa 02

### ISSUE THREAD

**Issue by hugolealtech** [roger-melo-treinamentos/curso-de-js-roger-melo#5830]
São 08 tipos de variáveis que serião expilcadas melhor a diante.

--> Number, que pode ser 1,2,3, 100, 3.456
-->String, que é texto e precisa estar entre aspas simples.
--> Boolean, que é verdadeiro ou falso
-->Null que é uma variável sem valor. O programador declara a variável null e o JS declara a mesma coisa mas com Undefined automaticamente.
-->object são estruturas mais complexas, como arrays, datas, literais e etc.
--> Simble utilizado por objetos
-->Bigint utilizados para manipular números muito grandes.

O JS é uma linguagem de tipagem dinâmica;

**Comment by MivlaM** [comment]
Boa @hugolealtech rumo à fluência! 🔥
