### ISSUE TITLE
Resumo da Aula Arrays - Aula 03-02 da etapa 01

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5836]
![image](https://user-images.githubusercontent.com/106329803/215187836-27c7e928-2193-44f9-a80b-0a4ae7f89f75.png)
![image](https://user-images.githubusercontent.com/106329803/215187966-f03100ae-58a6-4e87-901e-b6d815bb6e69.png)
![image](https://user-images.githubusercontent.com/106329803/215188068-9a353538-e69b-44c1-865c-f3635088060e.png)

**Comment by MivlaM** [comment]
Excelente @rafael-rodrigues01, rumo à fluência! 🎯
