### ISSUE TITLE
Resumo da Aula Strings - Aula 02 da etapa 03

### ISSUE THREAD

**Issue by hugolealtech** [roger-melo-treinamentos/curso-de-js-roger-melo#5842]
Strings podem armazenar textos e caracteres

Elas também podem guardar informações se transformadas em variáveis

Elas podem ser concatenadas e tratadas.

Abaixo o conteúdo da aula.

//strings
console.log('Hello, World')

const email = 'hugoleal@gmail.com'

console.log (email)

// concatenação de strings
 const firstName = 'Hugo'
 const lastName = 'Leal'
 const fullName = firstName + ' ' + lastName

 console.log(fullName)

//acessando caracteres
 console.log(fullName [0])

 //comprimento de ums string

 console.log(fullName.length)

//métodos de strings

console.log(fullName.toUpperCase())

const result = fullName.toLowerCase()

console.log(result)

const index = email.indexOf('@')
console.log (index)

**Comment by MivlaM** [comment]
Excelente @hugolealtech, rumo à fluência! 🎯
