### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by Francimildo** [roger-melo-treinamentos/curso-de-js-roger-melo#5843]
null e undefined representam a falta de um valor.
**No contexto da linguagem JavaScript:**
- **null** quando o programador atribui intencionalmente esse valor a uma variável.
- **undefined** é o valor que a própria linguagem atribui à variável quando esta é declarada e não atribuída ainda nenhum valor.
- **NaN** **(Not a Number)** quando uma operação matemática acontece entre um número e uma variável que está com '**undefined**', ou seja, não tem nenhum valor ainda. O mesmo não acontece quando a variável está com 'null' pois o JavaScript, por baixo dos panos trata o 'null' como 'zero' e efetua a operação normalmente.

**Comment by MivlaM** [comment]
Excelente @Francimildo, rumo à fluência! 🎯
