### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by bindwkill** [roger-melo-treinamentos/curso-de-js-roger-melo#5850]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/bindwkill/weather-application

### Maiores dificuldades durante a implementação

* entender/lembrar os passos para fazer uma requisição à API e tratar a resposta. Algumas vezes fiquei na duvida se uma função precisava ser declarada `async` ou então se precisava de `await` na hora de retornar valor.

### Menores dificuldades durante a implementação

* Exibir as informações no navegador, o template ajuda muito nisso
* Refatorar o código. As tarefas que cada parte do código faziam parecia bem clara na hora de separar elas e o fato da parte de requests estar num arquivo próprio ajudou bastante.

**Comment by MivlaM** [comment]
Olá @bindwkill

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Tudo certo! Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @bindwkill.

Parabéns pelo esforço em construir a terceira aplicação do treinamento =)

> ## entender/lembrar os passos para fazer uma requisição à API e tratar a resposta. Algumas vezes fiquei na duvida se uma função precisava ser declarada async ou então se precisava de await na hora de retornar valor.

Lembre-se de que uma requisição (operação assíncrona) feito com o `fetch` retorna uma promise.

Você pode comprovar isso testando no seu código:

```javascript
// weather.js
const x = fetch(url)
console.log(x) // Promise {<pending>}
```

☝🏻 sem o await, você não aguarda o resolver da promise e o retorno é a prória promise. 

`response` só é desencapsulado da promise se você aguarda ela resolver usando o `await`:

```javascript
const x = await fetch(url)
console.log(x) // Response { ... }
```

`response.json()` também retorna uma promise. Por isso você precisa do `await` na frente dele.

Recomendo que revise toda a etapa 11 buscando preencher esses gaps. Ela é muito importante para que você entenda os conceitos de assincronismo que você levará pelo restante de sua carreira de desenvolvedor.

Além disso, recomendo que leia a documentação de introdução à JavaScript assíncrono no MDN:

[Asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous)

Não vai ser rápido, mas entender assincronismo é crucial para um Desenvolvedor JS, caso contrário certamente a carreira será prejudicada. E eu não quero isso para você.

Se tiver alguma dúvida, pode abrir outras issues que te ajudo =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Const ao invés de let

Prefira usar const no lugar de let, quando possível.

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt. Sabendo disso, prefira seguir essa boa prática e fazer com que `timeImg` e `timeIconContainer` sejam consts. 

```js
// antes
let timeImg = document.querySelector('[data-js="time"')
let timeIconContainer = document.querySelector('[data-js="time-icon"')
```

```js
// depois
const timeImg = document.querySelector('[data-js="time"')
const timeIconContainer = document.querySelector('[data-js="time-icon"')
```

---

## Callback do listener de envio do form

Podemos nomear o callback do listener de evento como `showCityWeather`, por exemplo. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, o intuito aqui é nomeá-lo descrevendo a ação mais significativa que essa função irá executar na aplicação quando o form for enviado, assim ao bater o olho no nome da função, a ação que ela executa fica explícita:


```js
// antes
cityForm.addEventListener('submit', async event => {
  // ...
})
```


```js
// depois
const showCityWeather = async (event) => {
  // ...
}

cityForm.addEventListener('submit', showCityWeather)
```

---

## updateWeatherCard

Nessa função, o condicional if não é necessário, porque o d-none só vai estar presente antes de o usuário fazer a primeira busca, portanto, o código pode funcionar da mesma forma apenas com o remove. Você também pode deixar o código mais curto e mais simples de entender ao remover o método contains. Para facilitar o fluxo da leitura, uma sugestão seria fazer com que a remoção do d-none seja a última manipulação de DOM a ser feita na função, por isso, a ideia aqui é deixar esse trecho de código como última linha da função. Veja abaixo como ficaria a refatoração dessa função por completo:

```js
// antes
const updateWeatherCard = (cityName, weatherText, temperatureValue, isDayTime, weatherIcon) => {
  if (cityCard.classList.contains('d-none')) {
    cityCard.classList.remove('d-none')
  }

  // ...
}
```

```js
// depois
const updateWeatherCard = (cityName, weatherText, temperatureValue, isDayTime, weatherIcon) => {
  cityNameContainer.textContent = cityName
  cityWeatherContainer.textContent = weatherText
  cityTemperatureContainer.textContent = temperatureValue
  timeImg.src = isDayTime ? './src/day.svg' : './src/night.svg'
  timeIconContainer.innerHTML = `<img src="./src/icons/${weatherIcon}.svg"></img>`
  cityCard.classList.remove('d-none')
}
```

---

## função showCityWeather

Uma outra possibilidade de refatoração seria, por meio de uma abstração, você não precisar mais usar a invocação de `getCityData`. Segundo o raciocínio, ao invés de termos essa função, nós vamos ter apenas a função `getCityWeather` que vai fazer o que a `getCityData` está fazendo. A ideia dessa refatoração é ao invés de invocarmos duas funções, simplificar as coisas e precisarmos apenas invocar uma função que irá fazer o papel das duas =)

Dito isso, para entender de fato essa abstração que vou mostrar, eu sugiro que você acompanhe o passo a passo abaixo junto comigo, ok?

Vamos lá, vou criar uma função chamada `getCityWeather` que ao invés de receber a key, vai receber o nome da cidade. Antes de buscarmos o clima da cidade, precisamos obter as informações da cidade para obtermos a key, pois só por meio dela poderemos fazer o segundo request, no caso do seu código, o usado na função `fetchData`. Para desaninharmos as funções invocadas dentro da `fetchData`, vamos criar uma const `cityInfoUrl` que vai receber a `getCityUrl` e vamos exibí-la no console para confirmarmos se os resultados que esperamos estão sendo obtidos.

```js
const getCityWeather = city => {
  const cityInfoURL = getCityUrl(city)
  console.log(cityInfoURL) // Url com o nome da cidade no query parameter aparece...
} 
``` 

Não se preocupe se aparecer algum erro no console, o intuito aqui é, ao executarmos um console.log, ver a url com o nome da cidade no query parameter, ou seja, a cidade buscada. Feito isso, já que essa url está sendo obtida, podemos criar uma const `cityInfo` que vai armazenar o retorno da função `fetchData`. Seguindo o raciocínio, `cityInfo` vai ser uma função async, portanto terá um await que espera a resolução dessa promise que contém `cityInfoUrl` como argumento. Ficaria assim:

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const cityInfo = await fetchData(cityInfoURL)
  console.log(cityInfo) // Array de objetos aparece...
} 
```

Ao visualizarmos isso no console, veremos que o resultado é um array de objetos em que o primeiro objeto vai corresponder, na maioria das vezes, a cidade escolhida no input.

No código que usamos para manipular o DOM, estamos usando, além da propriedade Key, a propriedade LocalizedName. Então, também vamos precisar da propriedade localizedName, e essa função `getCityWeather` vai ter que retornar ela para quando for invocada ela ser usada no destructuring e e então servir como argumento dessa invocação. 

Para fazermos o destructuring no array de objetos e pegarmos do primeiro objeto, as propriedades LocalizedName e Key, vamos fazer um destructuring nesse primeiro objeto, na propriedade Key e na LocalizedName. Feito isso, se exibirmos no console, aparece a Key e o nome da cidade como LocalizedName. 

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  console.log(Key, LocalizedName) // Key e LocalizedName aparecem no console...
} 
```

Após isso, vamos fazer o segundo request para obtermos a informação do clima dessa cidade, para isso, vamos usar a Key. Para isso, vamos obter a url, vou criar uma const `cityWeatherURL` recebe a invocação de `getConditionsURL()` que recebe a Key como argumento. Dessa forma, a url com a Key vai ser retornada corretamente.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getConditionsURL(Key)
  console.log(cityWeatherURL) // Url com a Key vai ser retornada...
} 
```

Feito isso, agora que temos a url, falta fazer o último request, que é o request que vai buscar os dados do clima da cidade. Para fazer isso, vamos criar uma const `cityWeather` que recebe `fetchData` com await antes porque é uma função assincrona, e esse `fetchData` vai receber `cityWeatherURL` como argumento.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getConditionsURL(Key)
  const cityWeather = await fetchData(cityWeatherURL)
  console.log(cityWeather) // Array com um objeto que contém os dados do clima da cidade.
} 
```

Agora, podemos retornar cityWeather e para que essa função não retorne um array num objeto, podemos fazer com que ela retorne apenas um objeto por meio de um destructuring.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getConditionsURL(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return cityWeather
} 
```

Você se lembra que esse objeto que está sendo retornado por essa função também precisa ter LocalizedName? Então, ao invés de retornar um objeto, você pode retornar um novo objeto que contém as propriedades do objeto cityWeather e também contém LocalizedName. Aqui foi criado um novo objeto que contém as propriedades do objeto cityWeather espalhados pelo spread operator e que também contém a LocalizedName.

```js
const getCityWeather = async city => {
  const cityInfoURL = getCityUrl(city)
  const [{ Key, LocalizedName }] = await fetchData(cityInfoURL)
  const cityWeatherURL = getConditionsURL(Key)
  const [cityWeather] = await fetchData(cityWeatherURL)

  return { ...cityWeather, LocalizedName }
} 
```

Por fim, resta inserir LocalizedName como um dos destructurings da função `getCityWeather`. Nessa função, o destructuring do array, ou seja, os colchetes, podem ser removidos pois agora a `getCityWeather` não está mais retornando um array, mas um objeto. Por isso não é mais necessário os colchetes do destructuring.

```js
const {IsDayTime , WeatherText , WeatherIcon , Temperature, LocalizedName} = await getCityWeather(inputValue)
```

Após isso, você não vai precisar mais da função `getCityData` e o código estará funcionando perfeitamente bem =)

---

## inputValue

Algo que pode ser útil, seria usar o método trim para remover os espaços em branco de uma eventual busca ao inserir o nome da cidade. Sabendo que o método trim remove os espaços em branco do início e fim de um texto, ele pode ser usado para evitar com que um espaço em branco inserido acidentalmente, por exemplo, prejudique a busca de um nome. Ficaria assim:

```js
// antes
const inputValue = event.target.city.value
```

```js
// depois
const inputValue = event.target.city.value.trim()
```

---

## Validação

Na função `showCityWeather`, algo que você pode adicionar e que seria interessante como funcionalidade para o usuário é inserir uma validação no `inputValue`. Esse `inputValue` pode ter uma verificação para caso uma string vazia ou string com menos de três caracteres for enviada como input. Numa situação assim, você pode, se achar que faz sentido, exibir uma mensagem na tela por meio do `alert` comunicando que é necessário inserir o nome de uma cidade. Ficaria assim:

```js
const showCityWeather = async (event) => {
  event.preventDefault()
  
  const inputValue = event.target.city.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira o nome da cidade")  
    return
  }

  // ...
}
```

---

## Argumentos de updateWeatherCard

A função `updateWeatherCard` tem muitos argumentos e funções com vários argumentos são mais complexas de testar e manter, pois exigem que casos diferentes sejam testados com cada argumento individualmente. A sugestão aqui, é fazer com que essa função receba apenas um argumento para facilitar na hora de testar e manter. Para isso, vamos declarar uma const `cityWeather` que vai armazenar o objeto retornado pela `getCityWeather`, depois disso, essa `cityWeather` será o argumento da `updateWeatherCard`. Ficaria assim:  

```js
// antes
const {IsDayTime , WeatherText , WeatherIcon , Temperature, LocalizedName} = await getCityWeather(inputValue)
```

```js
// depois
const cityWeather = await getCityWeather(inputValue)

updateWeatherCard(cityWeather)
```

Agora, para o código funcionar por completo, vamos fazer com que a `updateWeatherCard` tenha apenas um parâmetro, você pode fazer uma refatoração tanto pela sintaxe objeto.propriedade quanto por destructuring, no exemplo abaixo mostro uma das opções, caso tenha alguma duvida na segunda, pode comentar logo abaixo na issue. Veja abaixo como ficaria:

```js
// antes
const updateWeatherCard = (cityName, weatherText, temperatureValue, isDayTime, weatherIcon) => {
  cityNameContainer.textContent = cityName
  cityWeatherContainer.textContent = weatherText
  cityTemperatureContainer.textContent = temperatureValue
  timeImg.src = isDayTime ? './src/day.svg' : './src/night.svg'
  timeIconContainer.innerHTML = `<img src="./src/icons/${weatherIcon}.svg"></img>`
  cityCard.classList.remove('d-none')
}
```

```js
// depois
const updateWeatherCard = cityWeather => {
  cityNameContainer.textContent = cityWeather.cityName
  cityWeatherContainer.textContent = cityWeather.weatherText
  cityTemperatureContainer.textContent = cityWeather.temperatureValue
  timeImg.src = cityWeather.isDayTime ? './src/day.svg' : './src/night.svg'
  timeIconContainer.innerHTML = `<img src="./src/icons/${cityWeather.weatherIcon}.svg"></img>`
  cityCard.classList.remove('d-none')
}
```

---

## Fechamento da tag img

Há um pequeno detalhe no HTML que `timeIconContainer.innerHTML` está recebendo, lá, a tag img não necessariamente deve ter o fechamento `</img>`.

```js
// antes
timeIconContainer.innerHTML = `<img src="./src/icons/${cityWeather.weatherIcon}.svg"></img>`
```

```js
// depois
timeIconContainer.innerHTML = `<img src="./src/icons/${cityWeather.WeatherIcon}.svg">`
```

Você pode ver mais detalhes sobre essa particularidade na documentação [Images in HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#how_do_we_put_an_image_on_a_webpage)

---


Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by bindwkill** [comment]
@MivlaM Muito obrigado pelas observações! Levei um tempinho para ler e compreender tudo.

Apenas umas justificativa que eu gostaria de dar, eu não cheguei a pensar em juntar a getCityData com a getCityWeather porque eu estava imaginando (posteriormente) fazer o usuário escolher entre as cidades do array que a primeira request retorna.

Mas eu gostei demais das mudanças que você apontou, principalmente com relação aos argumentos da 'updateWeatherCard', realmente aquele pedaço dá um pouco de caos e colocar eles num objeto melhorou muito!

As verificações no input também foram coisas que não passaram pela minha cabeça.

Eu fiquei um tempo sem estudar por uns problemas pessoais e acho que isso prejudicou na atenção a umas coisas. Se eu tivesse consultado mais a documentação das coisas penso que teria ajudado bastante.

Vou revisar a etapa 11 como orientou antes de seguir em frente.

Mais uma vez muito obrigado!

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
