### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by acdona** [roger-melo-treinamentos/curso-de-js-roger-melo#5853]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/acdona/to-do-list

### Maiores dificuldades durante a implementação

Implementação do editar com modal.
Não consigo resultado que altera corretamente o campo clicado.
Altera mais de um campo.
Se utilizar o prompt, consigo alterar corretamente.

### Menores dificuldades durante a implementação

Implementação do editar com prompt.

**Comment by acdona** [comment]
#### Roger consegui resolver.
Eu estava submetendo o formulário mais de uma vez.
Utilizei o **_.removeAddListener_** (ainda não cheguei nessa aula)

**Comment by MivlaM** [comment]
Olá @acdona.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Mas antes disso, verifiquei a sua aplicação e identifiquei que alguns critérios para que a análise seja feita estão em falta.

O critério é o seguinte:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas da construção da aplicação.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações", também é necessário que você se atente ao que foi escrito nos campos de texto na hora de abrir uma issue de aplicação.

Novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. Foi pedido no enunciado do exercício e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que não foram mostradas nas aulas.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Na sua aplicação, você usou funcionalidades da linguagem que ainda não foram apresentadas no CJRM no momento em que a aplicação deve ser enviada.

É interessante que você tenha feito funcionar por uma abordagem diferente usando outras funcionalidades, mas no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by MivlaM** [comment]
Olá @acdona 

Para ser mais preciso no que está sendo demandado, o que há no código da sua aplicação e que está entrando em conflito com o critério, é a feature de popup que apesar de ser mostrada em aulas passadas, não é utilizada nas aulas de construção da aplicação To-do List. Há também mais uma ocorrência que é a do uso de uma nova feature, o `removeEventListener` que pelo que pude analisar aqui, é usado exclusivamente no trecho do código referente ao popup. 

Esse trecho de código especificamente não é necessário para o que se dispõe o foco de analisar nesta parte do treinamento, o importante para a gente é analisar o essencial que foi mostrado para a aplicação, porque se a pessoa consegue construir a aplicação sozinha, fica meio que implícito que provavelmente, ela consegue fazer adições de funcionalidades (afinal, ela já fez o mais difícil).

Novamente, é interessante que você tenha adicionado uma nova funcionalidade e tenha feito a aplicação funcionar com ela, porém, no momento da análise, consideramos o ideal manter no código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação, portanto, você tem mérito por ter desenvolvido uma nova funcionalidade e você ainda vai poder aplicá-la futuramente, mas, neste momento, para a análise, solicito-lhe que ela seja removida para analisarmos o foco principal do conteúdo ensinado na etapa =)

**Comment by acdona** [comment]
Obrigado pela atenção.

**Comment by acdona** [comment]
Aplicação com implementações ainda não estudadas. 
Issue fechada
