### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03

### ISSUE THREAD

**Issue by PauloRDev** [roger-melo-treinamentos/curso-de-js-roger-melo#5858]
Null and Undefined.

 São similares e representam a falta de um valor.
 A diferença de null para undefined, é que null precisa de valor atribuido.
 Toda vez que declaramos uma váriavel e não atribuimos valor
 Ao chamar ela, recebemos Undefined.
 Se essa varíavel receber algo relacionado á números, recebemos NaN (Not A Number)

```js
let emptiness = null

/*

 Se null é declarado como atribuição, ele é retornado no lugar de undefined.
Utilizamos null quando propositalmente queremos declarar que não tem valor.

*/
console.log(emptiness, emptiness + 3, `O valor é ${emptiness}`)
```

**Comment by MivlaM** [comment]
Boa @PauloRDev rumo à fluência! 🔥
