### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5861]
* Argumentos:  E que passamos no escopo das funcoes | function( name, lastName )

* Parametros: E o que passamos para invocar as funcoes | myFunc('Diego')

* Default parameters: Utilizamos como valor padrao na ausencia de informacao |  function(name = 'Estronciio', lastName ='Alves')

Quando invocamos uma funcao e nao passamos nenhum parametro a ela os valores default declarados sao retornados,
caso todos ou alguns parametros tenham sido declados o valor  dafault e subescrito.

---------------
// Argumentos, parametros e default parameters

const myFunc  = function(name = 'Estroncio', lastName ='Alves') {
  console.log(`Oi ${name}  ${lastName}!`)
}
myFunc()       // Retorna : OI Estroncio Alves
myFunc('Diego','Braga')       // Retorna : OI Diego Braga
myFunc('Diego','')     // Retorna : OI Diego Alves
myFunc('','Braga')    // Retorna : OI Estroncio Braga

**Comment by MivlaM** [comment]
Boa @dzpoke rumo à fluência! 🔥
