### ISSUE TITLE
Resumo da Aula Conversao de tipos Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by leandrokespers** [roger-melo-treinamentos/curso-de-js-roger-melo#5867]
<p style='margin:0in;font-family:"IBM Plex Mono";font-size:20.0pt'>Conversão de
tipos</p>

<p style='margin:0in;font-family:Calibri;font-size:10.0pt;color:#767676'>terça-feira,
31 de janeiro de 2023</p>

<p style='margin:0in;font-family:Calibri;font-size:10.0pt;color:#767676'>00:48</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>Uma das
formas de conveter variaveis em um tipo diferente do atribuído é utilizando a
função construtora <span style='font-weight:bold;color:#3B5E26'>Number(). </span>Com
ela é possível comverter strings em números.</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'><span
style='font-weight:bold;color:#0070C0'>Typeof</span><span style='font-weight:
bold'> - </span>verifica qual é o tipo de dado.</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>Converter
uma string que não seja de ordem numerica resultará em NaN. Ex:</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;line-height:18pt;font-family:"IBM Plex Mono";font-size:
12.0pt'>&nbsp;</p>

<div style='direction:ltr'>

1        2 | const crazyNumber = Number("Maçã")   console.log(crazyNumber);
-- | --

</div>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'><span
style='font-weight:bold'>String() - a função construtora converte números em
strings.</span></p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'><span
style='font-weight:bold'>Boolean() - converte valores para true ou false.</span></p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:"IBM Plex Mono";font-size:12.0pt'>Valores como
null, undefined, &quot;&quot;, NaN e 0 serão convertidos para false.</p>

</body>

</html>

**Comment by MivlaM** [comment]
Boa @leandrokespers rumo à fluência! 🔥
