### ISSUE TITLE
Resumo da Aula Booleans e Comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#587]
# Booleans e Comparações

Booleans representa dois valores em JavaScript, true ou false. Ele é usado para verificar alguma condição no código, ou seja, checar se um pedaço de código retorna true ou false.

## Método Includes

Esse método verifica se uma string passada no argumento existe em determinada **string** ou **array**. Caso sim, esse método irá retornar true, se não, false.

```js
const email = 'brucewayne@rogermelo.com.br';
const includes = emai.includes('wayne');
// includes valerá true

const names = ['dio', 'roger', 'robert'];
arrayIncludes = names.includes('roger');
// includes valerá true
```

## Operadores de Comparação

Desconsidere as aspas entre os operadores.

1. '==' igual a
2. '!=' não é igual a / diferente de
3.  '>' maior que
4. '<' menor que
5. '>=' maior ou igual a
6. '<=' menor ou igual a

### Comparando Numbers

```js
const age = 31;
const name = 'roger';

console.log(age == 31); // true
console.log(age == 35); // false
console.log(age != 31); // false
console.log(age > 31);  // false
console.log(age < 32); // true
console.log(age <= 31);  // true
console.log(age >= 31); // true
```

### Comparando Strings

Como JS é **case sensitive** ele compara verificando se as letras são exatamente iguais, ou seja, compara também se são maiúsculas ou minúsculas.

Quando a comparação entre strings for usado com os operadores: >, >=, <, <=, será comparado a primeira letra de cada string.

* A 1ª letra minúscula é considerada maior que uma maiúscula.
* Quanto mais para o fim do alfabeto a 1ª letra estiver, maior ela será em comparação com uma letra que está mais no início.

```js
const name = 'roger';

console.log(name > 'Belinha'); // true
console.log(name > 'Roger'); // true
console.log(name > 'belinha'); // true
```

As comparações vistas até aqui são chamadas de **comparação sem igualdade estrita** ou seja, elas não comparam se os tipos das variáveis são iguais.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer. Rumo à fluência! 🔥
