### ISSUE TITLE
Resumo da Aula Booleans e comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5873]
Booleans são valores especiais e servem para verificar se uma parte do código é verdadeiro. 

Método includes verifica se um caracter ou uma cadeia de caracter existe dentro de uma variável, e retorna um valor do tipo boolean. O includes pode ser usado tanto em Strings quanto em Arrays.

**Comment by MivlaM** [comment]
Excelente @Luis-avellar rumo à fluência! 🔥
