### ISSUE TITLE
Resumo da Aula Comparações com igualdade estrita - Aula 04-03 da etapa 01

### ISSUE THREAD

**Issue by Francimildo** [roger-melo-treinamentos/curso-de-js-roger-melo#5874]
A comparação estrita ou **_"strict equality"_** utiliza dos símbolo de igualdade a mais "?==" para marcar graficamente que a comparação que está sendo realizada é não só dos valores mas também dos tipos envolvidos.

**Comment by MivlaM** [comment]
Boa @Francimildo rumo à fluência! 🔥
