### ISSUE TITLE
Resumo da Aula 02 da etapa 05

### ISSUE THREAD

**Issue by hugolealtech** [roger-melo-treinamentos/curso-de-js-roger-melo#5876]
console.log(crazyOperation) //retorna 245
//-------------------------------------------

let postLike = 10

postLike++// console.log(postLikes)  retorna - 11
//postLike-- //console.log(postLikes)  retorna 9

console.log(postLike)

//---------------------------------------------
//operadores addition, subtraction, multiplication and division assigment

let postlikes = 10

//postlikes = postlikes + 10

//postlikes += 10

console.log(postlikes)

// Pega o valor que já tem em postLikes e adiciona 10
// postLikes -= 5 --> pega o valor que já tem e subtraia 10
// postLikes *= 2 --> pega o valor que já tem e multiplique por 2
// postLikes /= 2 --> pega o valor que já tem e divida por 2

//------------------------------------------------------------------//
//Concatenação números com strings

const likesMessage = 'O post tem '  + postlikes + ' likes'
console.log (likesMessage)

**Comment by MivlaM** [comment]
Boa @hugolealtech rumo à fluência! 🔥
