### ISSUE TITLE
Dúvida sobre o método de preenchimento do array

### ISSUE THREAD

**Issue by leandrokespers** [roger-melo-treinamentos/curso-de-js-roger-melo#5885]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370896

### Descreva a dúvida

A forma como eu preenchi o array sem usar o push(), também está correto?

```js
const cities = ['São Paulo', 'Rio de Janeiro', 'Minas Gerais']
let upperCaseCities = []
for(let i = 0; i < cities.length; i++){
  upperCaseCities[i] = cities[i].toUpperCase()
}

console.log(upperCaseCities)


```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @leandrokespers

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

## A forma como eu preenchi o array sem usar o push(), também está correto?


Eu testei aqui e vi que o seu código funciona também. É possível que haja vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Com a prática, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, entende? =)

Compreenda também que é importante que você entenda a lógica da forma que os exercícios são resolvidos na correção, pois nela há princípios que serão intensificados conforme você avança no CJRM. Eu sugeriria para você também aprender a chegar na solução com o método push, pois é um método importante que com certeza você verá uso durante sua jornada como programador.

Respondi a sua pergunta? Se restar qualquer dúvida é só avisar que te ajudarei =)

**Comment by leandrokespers** [comment]
Bom dia. Eu refiz os exercícios de acordo com a correção. E deixei comentado a forma com a qual eu resolvi. Com o push() a resolução foi mais eficiente. Obrigado.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
