### ISSUE TITLE
Dúvida sobre o exercicio 7

### ISSUE THREAD

**Issue by leandrokespers** [roger-melo-treinamentos/curso-de-js-roger-melo#5886]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370896

### Descreva a dúvida

Roger eu não compreendi muito bem a lógica pra somar esse conjunto de arrays. Aliás isso seria uma matriz? Alguma dica para compreender melhor?

```js
const arrays = [
  [4, 32, 8],
  [64, 8, 32],
  [8, 32, 16],
  [2, 8, 4]
]
let arraysSum = 0
for(let i = 0; i < arrays.length; i++){
  for(let j = 0; j < arrays[i].length; j++){
    arraysSum += arrays[i][j]
  }
}
console.log(arraysSum);


```

@Roger-Melo

**Comment by leandrokespers** [comment]
Revendo a resolução hoje, creio que eu tenha entendido. Obrigado pelo retorno.

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
