### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by Francimildo** [roger-melo-treinamentos/curso-de-js-roger-melo#5890]
Quando se tem um número na forma de uma string por exemplo: '100' e se tenta realizar uma operação matemática de adição, **_exclusivamente de adição_**, com este número o resultado é uma concatenação da string com o valor em questão. As outras operações são realizadas.

Para converter uma string que representa um número Ex.: "150" Usa-se a função construtora Number() passando a string de número como argumento. Ex abaixo:
```js
const numero = "150";
numero = Number(numero);
console.log(numero + 1); // output: 151
```
Caso a função construtora Number("maçã") seja invocada com um argumento que não represente um número o resultado no console será 'NaN' "Not a Number".
Existe também a função construtora String() que recebe um número tipo 'number' mesmo e converte para tipo string.
Existe uma forma de verificar o tipo de um dado usando o operador 'typeof'
```js
const valor = 205;
console.log(valor, typeof valor); // output: 205 number
```
Existe também a função construtora Boolean() que converte um valor para boolean seguindo a premissa de quando não for  um valor da lista '**_falsy_**' será true.
Lista falsy = 0, "", false, '', ``, null, undefined, NaN.

**Comment by MivlaM** [comment]
Excelente @Francimildo, rumo à fluência! 🎯
