### ISSUE TITLE
Resumo da Aula Funções construtoras da etapa 14

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#5891]
### Funções construtoras
Da mesma forma que uma classe é um molde para um objeto que estamos criando, uma função construtora tambem é.
```js
function Student (name, email) {
  this.name = name
  this.email = email
}

const gabrielFialho = new Student('Gabriel Fialho', 'gabriel@gmail.com')
```
Por que devemos usar function declaration para criar uma função construtora?
Porque se criarmos com function expression obteremos um erro, pois o this dentro de uma arrow function representa o this do escopo em que a arrow function foi declarada
```js
const Student (name, email) => {
  this.name = name
  this.email = email
}
```
No caso acima o this faz referencia o objeto window, que é o objeto global de uma aplicação e não ao objeto que esta sendo criado pela função construtora.

**Comment by MivlaM** [comment]
Excelente @Diegodkid, rumo à fluência! 🎯
