### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5897]
Operadores lógicos nos permitem criar uma combinação condicional para nossas estruturas de validação. Onde && significa (E), ou seja, ambas as condições tem que ser verdadeiras para a estrutura condicional seja válida e || representa (Ou) que apenas basta que UMA das condições sejam verdadeira para executar nosso bloco de código.

**Comment by MivlaM** [comment]
Excelente @Luis-avellar, rumo à fluência! 🎯
