### ISSUE TITLE
Resumo da Aula Else e else if statements - Aula 02-03 da etapa 02

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5904]
![image](https://user-images.githubusercontent.com/106329803/216438753-ebbebcc4-15a5-405d-b781-0c29917ee628.png)
![image](https://user-images.githubusercontent.com/106329803/216438807-183f2d44-2057-4f36-b5da-07b53e0c84e4.png)

**Comment by MivlaM** [comment]
Excelente @rafael-rodrigues01, rumo à fluência! 🎯
