### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5905]
#### forEach e callbacks

* callback: sao funcoes que passamos como argumentos da invocao de outras funcoes

const myFunc = callback => {
 const value = 77 

callback(value)
}

myFunc( number => {  // Aqui estamos passando como parametro de *callback* outra funcao que vai retornar o valor da const 
console.log(number)  //  value
})

* forEach

const socialNetworks =['youtube',''twitter','instagram','facebook']

socialNetworks.forEach((socialNetwork, index, array) =>{
console.log(index, socialNetwork, Array)
})

/// forEach refatorado

const socialNetworks =['youtube',''twitter','instagram','facebook']

const logArrayInfo = (socialNetwork, index, array)=>{
console.log(index, socialNetwork, Array)
}

**Comment by MivlaM** [comment]
Excelente @dzpoke, rumo à fluência! 🎯
