### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by salviotonon** [roger-melo-treinamentos/curso-de-js-roger-melo#5906]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/salviotonon/VanillaJS-Quiz

### Maiores dificuldades durante a implementação

1. Tive dificuldades em criar a lógica para percorrer por todos os inputs selecionados pelo usuário.
2. Na primeira tentativa para finalizar o projeto, esqueci de fazer a aplicação mostrar o gabarito das questões. quando fui criar essa funcionalidade tive dificuldades em acessar um Elemento no DOM específico
3. Pela dificuldade relatada no item 2, gastei um bom tempo na documentação até entender de fato os seletores CSS para o comando document.querySelector conseguir referenciar o ponto específico em que eu precisava.
4. Apos finalizar o projeto, gastei aproximadamente 80% do tempo refatorando o código, tive uma certa dificuldade para entender qual função estava fazendo mais tarefas do que o ideal.

obs: Se o usuário acessar a aplicação com o modo noturno ativado no navegador, pode quebrar o layout, optei por não adicionar a funcionalidade que resolve isso, mas sei que existe esse bug na aplicação.

dentro do código existe um swtich case, que ao tentar refatora-lo acabei percebendo que fugiria do escopo visto até essa etapa no curso, entao decidi manter ele, até chegar em uma etapa mais avançada do curso.

### Menores dificuldades durante a implementação

1. Injetar estilos CSS nos elementos pelo Javascript
2. adicionar eventos de click nos elementos do DOM
3. realizar iterações utilizando o método forEach
4. utilizar a template string para incorporar variaveis na string.

Atividades extras:

Criei um ReadME sobre o projeto no github https://github.com/salviotonon/VanillaJS-Quiz/blob/main/README.md
Coloquei o repositório no github Pages para testar a aplicação : https://salviotonon.github.io/VanillaJS-Quiz/

**Comment by MivlaM** [comment]
Olá @salviotonon

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá, @salviotonon.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)


## Pela dificuldade relatada no item 2, gastei um bom tempo na documentação até entender de fato os seletores CSS para o comando document.querySelector conseguir referenciar o ponto específico em que eu precisava.

Mesmo com as dificuldades relatadas no item 1 ao 3, você conseguiu!! =)

## Apos finalizar o projeto, gastei aproximadamente 80% do tempo refatorando o código, tive uma certa dificuldade para entender qual função estava fazendo mais tarefas do que o ideal.

O mais importante vc já fez, que é fazer funcionar =)

Não se preocupe muito com refatoração agora. Refatoração é uma habilidade que é elevada com a prática.

Conforme vc praticar, vc vai percebendo aos poucos o que pode ser melhorado.

E você ainda irá praticar bastante no decorrer do treinamento =)

---

## Boas decisões

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Uma ideia interessante que você teve em relação à usabilidade foi a de posicionar a mensagem dos pontos de forma que ela preenchesse boa parte do centro da tela após clicar no botão. Isso é bom pois a pontuação aparece justamente onde o usuário estará olhando após enviar as respostas.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

A estilização do seu quiz ficou muito legal! =)

Vou deixar abaixo algumas observações sobre sua aplicação.

---

Antes de começar a mostrar os pontos, gostaria de ratificar que houve um erro na hora que fui validar alguns critérios, são os seguintes:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas de construção da aplicação.

No trecho de código abaixo, você usou o javascript do bootstrap.

```HTML
<script>
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
  crossorigin="anonymous"
</script>
```

Em nenhum momento do treinamento foi pedido para usar algo que não fosse JS puro na aplicação. Os critérios para análise do quiz devem ser seguidos, libs são ferramentas adicionais, e essas ferramentas não devem ser adicionadas agora. Foi pedido no [enunciado do exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js#L12)
e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação seja feita apenas com o que você viu nas aulas até aqui.

Ao longo do seu código, também houveram algumas funcionalidades adicionais, como a de mostrar o gabarito, o highlight com ícone nas opções certas e erradas, os botões de reset, tudo isso é muito interessante que você tenha feito, mas novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, o que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

É interessante que você tenha desenvolvido outras funcionalidade na aplicação, mas no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação. Solicito que, por favor, nas futuras aplicações, siga o recomendado estritamente.

---

## Usabilidade

Em termos de usabilidade, para o usuário, não acredito que seja uma boa experiência ter que clicar em dois botões para refazer o quiz. Uma boa ideia aqui seria fazer o botão de refazer quiz levar diretamente às perguntas novamente, sem precisar passar pela tela inicial de novo.

---

## Declaração e invocação de funções

Nas funções `transformTitleButton` e `calculateResult` podemos fazer algumas modificações em relação ao momento no código que elas são declaradas e invocadas. Primeiramente, ambas estão sendo declaradas depois de já terem sido invocadas em outras partes do código, para facilitar o fluxo da leitura, uma sugestão seria declará-las antes de elas serem usadas.

```js
// antes
const handleSubmitForm = (event) => {
  event.preventDefault();

  const [score, scorePercentage] = calculateResult(event);

  handleQuizPerformanceFeedback(scorePercentage, score, answerInputs);

  transformTitleButton(scorePercentage, score);
};

const calculateResult = (event) => {
  // ...
};

const transformTitleButton = (scorePercentage, score) => {
  // ...
};

```

```js
// depois
const calculateResult = (event) => {
  // ...
}

const transformTitleButton = (scorePercentage, score) => {
  // ...
}

const handleSubmitForm = (event) => {
  event.preventDefault()

  const [score, scorePercentage] = calculateResult(event)

  handleQuizPerformanceFeedback(scorePercentage, score, answerInputs)

  transformTitleButton(scorePercentage, score)
}

```

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a função `calculateResult` pode ter seu nome substituido por `getScore`. O intuito aqui é fazer com que os nomes diminuam de comprimento e ao mesmo tempo mantenham o sentido original.

```js
// antes
const calculateResult = (event) => {
  // ...
};
```

```js
// depois
const getScore = (event) => {
  // ...
}
```

---

## Refatoração de answerInputs

Podemos fazer uma abordagem interessante aqui, Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. `userAnswers` vai receber um array vazio que será preenchido após percorrermos cada item dentro do array `correctAnswers` por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = quizFormElement[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Lembre-se da ideia de que quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = quizFormElement[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. A cada execução desse callback, o valor que a função está retornando vai ser inserido nesse novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, `answerInputs` poderá ser removida do código, mas sugiro que não a remova ainda, pois ela foi usada em muitas partes do código e ao longo das próximas refatorações você verá que vamos ir substitundo seus papéis antigamente por outros trechos. Por agora, a `getUserAnswers` já vai estar funcionando normalmente e você pode declarar uma const `userAnswers` para armazenar a invocação dessa função em `getScore`.

```js
const getScore = () => {
  let score = 0
  const userAnswers = getUserAnswers()

  // ...
}
```

## Função getScore

Nessa função, podemos fazer algumas refatorações, primeiramente após ter declarado `userAnswers` para armazenar o retorno da função `getUserAnswers`, vamos refatorar a lógica usada dentro do callback do forEach. Antes, o código estava utilizando uma const `answer` para armazenar uma expressão que será utilizada como argumento de uma outra função `isAnswerCorrect` para calcular a pontuação. Agora, para não ser mais necessário usar essa função `isAnswerCorrect`, você pode, se fizer sentido para você, ao invés de usar `answerInputs`, vamos percorrer cada item de `correctAnswers`, para isso, vamos encadeá-lo no forEach. Feito isso, vamos declarar uma const com um nome mais preciso para armazenar a resposta do usuário por pergunta, essa const pode se chamar `isCorrectAnswer` e ela vai armazenar uma lógica semelhante a utilizada na função `getUserAnswers`, por fim, vamos manter essa const num condicional if, e caso esse if seja true, o `score` será aumentado. Ficaria assim:

```js
// antes
const getScore = (event) => {
  
  // ...
  answerInputs.forEach((answerInput, index) => {
    const answer = event.target[answerInput].value;

    if (isAnswerCorrect(answer, correctAnswers[index])) {
      score++;
    }
  });

  let scorePercentage = (score / answerInputs.length) * 100;
  return [score, scorePercentage];
};
```

```js
// depois
const getScore = (event) => {
  
  // ...
  correctAnswers.forEach((correctAnswer, index) => {
    const isCorrectAnswer = correctAnswer === userAnswers[index]
      if (isCorrectAnswer) {
        score++
      }
  })

  let scorePercentage = (score / answerInputs.length) * 100
  return [score, scorePercentage]
};
```

Feita observação, você pode perceber que `event` se tornou desnecessário como parâmetro dessa função, portanto, esse `event` pode ser removido inteiramente e a função pode ser invocada em `handleSubmitForm` da mesma forma que anteriormente, mas sem nenhum parâmetro agora. A função `isAnswerCorrect` que estava sendo usada unicamente nesse trecho de código, também pode ser eliminada da aplicação e antes de finalizarmos a refatoração dessa função, há um pequeno detalhe na let `scorePercentage`.

Prefira usar const no lugar de let, quando possível.

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt. Sabendo disso, prefira seguir essa boa prática e fazer com que `scorePercentage` seja const. Além disso, a expressão de `scorePercentage` pode usar `correctAnswers` ao invés de `userAnswers`, visto que essa última está para ser removida do código.

```js
// antes
let scorePercentage = (score / answerInputs.length) * 100;
```

```js
// depois
const scorePercentage = (score / correctAnswers.length) * 100
```

Por fim, a função completa ficaria assim:

```js
const getScore = () => {
  let score = 0
  const userAnswers = getUserAnswers()

  correctAnswers.forEach((correctAnswer, i) => {
    const isCorrectAnswer = correctAnswer === userAnswers[i]
    if (isCorrectAnswer) {
      score++
    }
  })

  const scorePercentage = (score / correctAnswers.length) * 100
  return [score, scorePercentage]
}
``` 

---

## Funções de mensagem

Há mais uma abordagem de refactoring que podemos fazer envolvendo a parte do código responsável para indicar qual mensagem será selecionada de acordo com a pontuação do usuário. Estou me referindo a esses trechos de código em específico. Há uma maneira de refatorar essa parte do código e deixá-la muito mais concisa e enxuta. Preparado? Vamos lá então!  

```js
const transformTitleButton = (scorePercentage, score) => {
  titleButton.style.display = "block";
  titleButton.textContent = `Você obteve ${scorePercentage}%, acertando ${score} de ${answerInputs.length} questões.`;
  titleButton.disabled = true;
  titleButton.style.cursor = "not-allowed";
};

const handleQuizPerformanceFeedback = (scorePercentage, score) => {
  switch (scorePercentage) {
    case 100:
      paragraph.textContent = `Você alcançou um desempenho incrível com ${scorePercentage}% de acertos, 
      acertando ${score} de ${answerInputs.length} questões. Você é um verdadeiro campeão! Continue assim!`;
      break;
    case 80:
      paragraph.textContent = `Você alcançou um desempenho muito bom com ${scorePercentage}% de acertos, 
      acertando ${score} de ${answerInputs.length} questões. Continue assim!`;
      break;
    case 60:
      paragraph.textContent = `Você obteve um bom resultado com ${scorePercentage}% de acertos, 
      acertando ${score} de ${answerInputs.length} questões. Mantenha o bom trabalho e você alcançará resultados ainda melhores em breve!`;
      break;
    case 40:
      paragraph.textContent = `Parabéns por se esforçar! Você obteve ${scorePercentage}% de acertos, 
      acertando ${score} de ${answerInputs.length} questões. Não se preocupe, continue praticando e você verá seu desempenho melhorar a cada dia.`;
      break;
    default:
      paragraph.textContent = `Ops! Você não obteve um resultado satisfatório.Não se preocupe, c
      ontinue praticando e você verá seu desempenho melhorar a cada dia.`;
  }

  paragraph.style.textAlign = "center";
  titlePopupScore.insertAdjacentElement("afterend", paragraph);
};

```

Você percebe um padrão se repetindo e que apenas alguns dados específicos estão mudando no switch da função `handleQuizPerformanceFeedback`? Sabendo disso, podemos criar uma função para fazer o papel de todos esses casos do switch case, vamos criar uma função para retornar um objeto que vai conter todas as informações para cada um dos casos retratados dentro do bloco do switch. Se cada dado dentro do switch está relacionado a mensagem de pontuação, podemos criar uma função chamada `getScoreMessage` que irá receber a pontuação que o usuário fez por meio de um parâmetro `score` que fará o mesmo papel de definir a mensagem de acordo com a pontuação que o usuário receberá e que retornará esse objeto personalizado para cada caso. No lugar de `answersInput.length`, é possível colocarmos simplesmente a quantidade de perguntas que há no quiz, por ser algo estático, a quantidade de perguntas é fixa, portanto você pode economizar linhas de código, fazer com que a invocação da função tenha dois argumentos ao invés de três (pois passar answerInputs não será mais necessário) e deixá-lo mais simples se optar por essa abordagem. Também teremos um parâmetro `scorePercentage`, que exibirá a porcentagem na mensagem de acordo com cada caso. Uma situação especial é o de caso `score` receba 0, não precisa inserir essa opção no objeto, podemos fazer com que essas informações sejam retornadas por meio de um || caso todas as outras situações sejam invalidas. Ficaria assim:

```js
const getScoreMessage = (scorePercentage, score) => {

  return {
    100: `Você alcançou um desempenho incrível com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Você é um verdadeiro campeão! Continue assim!`,
    80: `Você alcançou um desempenho muito bom com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Continue assim!`,
    60: `Você obteve um bom resultado com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Mantenha o bom trabalho e você alcançará resultados ainda melhores em breve!`,
    40: `Parabéns por se esforçar! Você obteve ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Não se preocupe, continue praticando e você verá seu desempenho melhorar a cada dia.`
  }[scorePercentage] || `Ops! Você não obteve um resultado satisfatório. Não se preocupe, continue praticando e você verá seu desempenho melhorar a cada dia.`
}
```

Agora, podemos armazenar o retorno dessa função `getScoreMessage` numa const `scoreMessage` que será declarada dentro da função `handleSubmitForm`, assim como `handleQuizPerformanceFeedback` estava anteriormente. 

```js
const scoreMessage = getScoreMessage(scorePercentage, score)
```

A ideia de fazer isso é para redirecionarmos toda a manipulação de DOM que estava sendo feita anteriormente na função `getScoreMessage` para uma outra função que pode ser responsável apenas para isso. Tendo esse objetivo em mente, a função `transformTitleButton` pode desempenhar esse papel, e para que ela faça isso, a sugestão aqui, além de renomeá-la para algo como `showScore` para deixar mais específico o que ela está fazendo no código e também encurtar sua nomenclatura, é fazer com que ela receba um novo parâmetro além dos outros dois que já estavam anteriormente, ela terá três parâmetros: `scoreMessage`, `scorePercentage` e `score` que serão envolvidos em colchetes pois queremos fazer um destructuring nesse caso. Feito isso, basta mover toda a manipulação de DOM para dentro dela e adicionar uma nova linha de código lá para receber a scoreMessage de forma dinâmica. A linha sugerida é `paragraph.textContent = scoreMessage`. A função finalizada ficaria assim:

```js
// antes
const transformTitleButton = (scorePercentage, score) => {
  titleButton.style.display = "block";
  titleButton.textContent = `Você obteve ${scorePercentage}%, acertando ${score} de ${answerInputs.length} questões.`;
  titleButton.disabled = true;
  titleButton.style.cursor = "not-allowed";
};
```

```js
// depois
const showScore = ({ scoreMessage, scorePercentage, score }) => {
  titleButton.style.display = "block"
  titleButton.textContent = `Você obteve ${scorePercentage}%, acertando ${score} de 5 questões.`
  titleButton.disabled = true
  titleButton.style.cursor = "not-allowed"
  paragraph.textContent = scoreMessage
  paragraph.style.textAlign = "center"
  titlePopupScore.insertAdjacentElement("afterend", paragraph)
}
```

Por fim, basta invocá-la na função `handleSubmitForm` e passar os argumentos necessários para a manipulação de DOM funcionar que o código vai estar funcionando normalmente =). Ficaria assim:

```js
const handleSubmitForm = (event) => {
  event.preventDefault()

  const [score, scorePercentage] = getScore()
  const scoreMessage = getScoreMessage(scorePercentage, score)

  showScore({ scoreMessage, scorePercentage, score })
}
```  

---

## markCorrectAnswers, highlightCorrectAnswer e markAnswer

Há algumas refatorações que podemos fazer nessas funções de forma que a lógica entre as três se torne complementar. Primeiramente, na função `markCorrectAnswers`, podemos declarar uma const `userAnswers` que irá armazenar o resultado da invocação de `getUserAnswers` e que será usado para encadear o callback no lugar de `answerInputs`, o intuito aqui é justamente substituir a última ocorrência de `answerInputs` no código, vale notar aqui, que vamos também renomear o novo parâmetro do callback do forEach como singular de itens do array no qual o forEach foi encadeado, a ideia é facilitar na legibilidade e deixar o código mais simples.

```js
// antes
answerInputs.forEach((answerInput, index) => {
  // ...
});
```

```js
// depois
const userAnswers = getUserAnswers()

userAnswers.forEach((userAnswer, index) => {
  // ...
});
```

Você também pode, se achar que faz sentido, remover a const `answer` e readaptar o código de `selectorInputChecked` para fazer tanto a função que `answer` fazia, quanto a de ratificar as respostas escolhidas pelo usuário. Para isso, a sugestão aqui é renomeá-la para algo mais preciso em relação a seu novo papel no código, algo como `checkedElement` serviria bem. `isAnswerCorrect` também teria uma parte do código adaptada para usar o parâmetro `userAnswer` ao invés de `answer` na lógica desse trecho de código. Ambas as refatorações efetuadas seriam mais ou menos assim: 

```js
// antes
const markCorrectAnswers = () => {
  handleVisibleElement(popupEndQuiz);
  handleVisibleElement(refreshButton);
  handleVisibleElement(sendAnswersButton);
  window.scrollTo(0, 0);

  const userAnswers = getUserAnswers()

  userAnswers.forEach((userAnswer, index) => {
    let selectorInputChecked = `input[name='${userAnswer}']:checked`;
    const answer = document.querySelector(selectorInputChecked);
    const isAnswerCorrect = answer.value === correctAnswers[index];
    const label = answer.closest("label");

    // ...
  });
};
```

```js
// depois
const markCorrectAnswers = () => {
  handleVisibleElement(popupEndQuiz)
  handleVisibleElement(refreshButton)
  handleVisibleElement(sendAnswersButton)
  window.scrollTo(0, 0)
  
  const userAnswers = getUserAnswers()

  userAnswers.forEach((userAnswer, index) => {
    const checkedElement = document.querySelector(`input[name='inputQuestion${index + 1}']:checked`)
    const isAnswerCorrect = userAnswer === correctAnswers[index]
    const label = checkedElement.closest("label")

    // ...
  })
}
```

Na função `highlightCorrectAnswer`, se você achar que faz sentido, a const `selectorIdentifyCorrectOption` não é necessária para essa função, o código fica muito mais conciso se você usar a própria `correctAnswerElement` diretamente para obter a referência do DOM, optando por essa abordagem, você consegue economizar uma linha de código e simplificar o código. Você também pode, se achar interessante, fazer com que a função receba apenas `index` como parâmetro se você optar por fazer algumas modificações na hora de pegar a referência no DOM, por exemplo, na template string, usar o `index` como ponto de partida e ir incrementando em um por um até concluir todo o número de alternativas. Ficaria assim:

```js
// antes
const highlightCorrectAnswer = (answerInput, correctAnswers, index) => {
  const selectorIdentifyCorrectOption = `input[name='${answerInput}'][value='${correctAnswers[index]}']`;
  const correctAnswerElement = document.querySelector(
    selectorIdentifyCorrectOption
  );
  if (correctAnswerElement) {
    const correctLabel = correctAnswerElement.closest("label");
    correctLabel.classList.add("feedback");
  }
};
``` 

```js
// depois
const highlightCorrectAnswer = index => {
  const correctAnswerElement = document.querySelector(`input[name='inputQuestion${index + 1}'][value='${correctAnswers[index]}']`)

  if (correctAnswerElement) {
    const correctLabel = correctAnswerElement.closest("label")
    correctLabel.classList.add("feedback")
  }
}
```

Por fim, ao invés de duas funções com funcionalidades parecidas, seja para marcar a alternativa como correta ou incorreta, é possível fazer uma refatoração aqui e condensá-las numa única função responsável para marcar as respostas. Se você achar que faz sentido, a vantagem aqui é encurtar o código e eliminar trechos desnecessários para manter um mesmo funcionamento que o anterior. Para isso, vamos declarar uma função `markAnswer` que irá receber `label`, `classToAdd` e `icon` como parâmetros, dentro da função, vamos fazer a manipulação de DOM e fazer com que label adicione a classe recebida por parâmetro por meio de `label.classList.add()` e que adicione o ícone por `label.textContent +=`:

```js
// antes
const markAnswerAsCorrect = (label) => {
  label.classList.add("success");
  label.textContent += `✔`;
};

const markAnswerAsIncorrect = (label) => {
  label.classList.add("failed");
  label.textContent += `❌`;
};
```

```js
// depois
const markAnswer = ({ label, classToAdd, icon }) => {
  label.classList.add(classToAdd)
  label.textContent += icon
}
```

Agora, ao invés de invocar duas funções como estava sendo feito anteriormente, podemos fazer com que essa função seja invocada com um objeto com as propriedades similares àquelas que estavam nas duas funções anteriores, ou seja, com os trechos de código responsáveis por definir se o ícone e classe para cada alternativa será o de correto ou incorreto. Para isso, faremos um destructuring, vamos envolver entre colchetes os parâmetros e os argumentos.

```js
// Declaração da função markAnswer
const markAnswer = ({ label, classToAdd, icon }) => {
  // ...
}
```

```js
// invocação para situação de alternativa correta
markAnswer({ label, classToAdd: "success", icon: '✔' })
```

```js
// invocação para situação de alternativa incorreta
markAnswer({ label, classToAdd: "failed", icon: '❌' })
```

Depois disso, para cada situação apropriada, você pode substituir os trechos de código que usavam as duas funções `markAnswerAsCorrect` e `markAnswerAsIncorrect` pelas invocações de `markAnswer` mostradas acima. A refatoração completa dessas três funções ficaria assim:

```js
const markAnswer = ({ label, classToAdd, icon }) => {
  label.classList.add(classToAdd)
  label.textContent += icon
}

const highlightCorrectAnswer = index => {
  const correctAnswerElement = document.querySelector(`input[name='inputQuestion${index + 1}'][value='${correctAnswers[index]}']`)

  if (correctAnswerElement) {
    const correctLabel = correctAnswerElement.closest("label")
    correctLabel.classList.add("feedback")
  }
}

const markCorrectAnswers = () => {
  handleVisibleElement(popupEndQuiz)
  handleVisibleElement(refreshButton)
  handleVisibleElement(sendAnswersButton)
  window.scrollTo(0, 0)
  
  const userAnswers = getUserAnswers()

  userAnswers.forEach((userAnswer, index) => {
    const checkedElement = document.querySelector(`input[name='inputQuestion${index + 1}']:checked`)
    const isAnswerCorrect = userAnswer === correctAnswers[index]
    const label = checkedElement.closest("label")

    if (isAnswerCorrect) {
      markAnswer({ label, classToAdd: "success", icon: '✔' })
      return
    }
    
    markAnswer({ label, classToAdd: "failed", icon: '❌' })
    highlightCorrectAnswer(index)
  })
}
```

Por fim, o código completo com todas as refatorações descritas ao longo da análise ficará assim:

```js
const quizFormElement = document.querySelector(".quiz-form")
const startQuizButton = document.querySelector("#startedQuiz")
const popupEndQuiz = document.querySelector(".popup-end-quiz")
const closeScoreQuizButton = document.querySelector(".btn-close-popup-score")
const checkAnswersButton = document.querySelector(".btn-check-answers")
const titlePopupScore = document.querySelector(".title-popup-score")
const sendAnswersButton = document.querySelector("#btnEndQuiz")
const refreshButton = document.querySelector("#refreshButton")
const titleButton = document.querySelector("#titleButton")

const correctAnswers = ["A", "A", "A", "B", "A"]

const showQuiz = () => {
  quizFormElement.style.display = "block"
  titleButton.style.display = "none"
}

const getUserAnswers = () => correctAnswers.map((_, index) => quizFormElement[`inputQuestion${index + 1}`].value)

const getScore = () => {
  let score = 0
  const userAnswers = getUserAnswers()

  correctAnswers.forEach((correctAnswer, i) => {
    const isCorrectAnswer = correctAnswer === userAnswers[i]
    if (isCorrectAnswer) {
      score++
    }
  })

  const scorePercentage = (score / correctAnswers.length) * 100
  return [score, scorePercentage]
}

const getScoreMessage = (scorePercentage, score) => {

  return {
    100: `Você alcançou um desempenho incrível com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Você é um verdadeiro campeão! Continue assim!`,
    80: `Você alcançou um desempenho muito bom com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Continue assim!`,
    60: `Você obteve um bom resultado com ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Mantenha o bom trabalho e você alcançará resultados ainda melhores em breve!`,
    40: `Parabéns por se esforçar! Você obteve ${scorePercentage}% de acertos, acertando ${score} de 5 questões. Não se preocupe, continue praticando e você verá seu desempenho melhorar a cada dia.`
  }[scorePercentage] || `Ops! Você não obteve um resultado satisfatório. Não se preocupe, continue praticando e você verá seu desempenho melhorar a cada dia.`
}

const showScore = ({ scoreMessage, scorePercentage, score }) => {
  titleButton.style.display = "block"
  titleButton.textContent = `Você obteve ${scorePercentage}%, acertando ${score} de ${correctAnswers.length} questões.`
  titleButton.disabled = true
  titleButton.style.cursor = "not-allowed"
  paragraph.textContent = scoreMessage
  paragraph.style.textAlign = "center"
  titlePopupScore.insertAdjacentElement("afterend", paragraph)
}

const handleSubmitForm = (event) => {
  event.preventDefault()

  const [score, scorePercentage] = getScore()
  const scoreMessage = getScoreMessage(scorePercentage, score)

  showScore({ scoreMessage, scorePercentage, score })
}

const paragraph = document.createElement("p")

const handleVisibleElement = (element) => element.classList.toggle("hidden")

const markAnswer = ({ label, classToAdd, icon }) => {
  label.classList.add(classToAdd)
  label.textContent += icon
}

const highlightCorrectAnswer = index => {
  const correctAnswerElement = document.querySelector(`input[name='inputQuestion${index + 1}'][value='${correctAnswers[index]}']`)

  if (correctAnswerElement) {
    const correctLabel = correctAnswerElement.closest("label")
    correctLabel.classList.add("feedback")
  }
}

const markCorrectAnswers = () => {
  handleVisibleElement(popupEndQuiz)
  handleVisibleElement(refreshButton)
  handleVisibleElement(sendAnswersButton)
  window.scrollTo(0, 0)
  
  const userAnswers = getUserAnswers()

  userAnswers.forEach((userAnswer, index) => {
    const checkedElement = document.querySelector(`input[name='inputQuestion${index + 1}']:checked`)
    const isAnswerCorrect = userAnswer === correctAnswers[index]
    const label = checkedElement.closest("label")

    if (isAnswerCorrect) {
      markAnswer({ label, classToAdd: "success", icon: '✔' })
      return
    }
    
    markAnswer({ label, classToAdd: "failed", icon: '❌' })
    highlightCorrectAnswer(index)
  })
}

startQuizButton.addEventListener("click", showQuiz)
quizFormElement.addEventListener("submit", handleSubmitForm)
sendAnswersButton.addEventListener("click", () => handleVisibleElement(popupEndQuiz))
checkAnswersButton.addEventListener("click", markCorrectAnswers)
closeScoreQuizButton.addEventListener("click", () => window.location.reload())
refreshButton.addEventListener("click", () => window.location.reload())
```

---

Após todas essas refatorações, você vai poder ver que o seu código continua funcionando normalmente e com a vantagem que as refatorações diminuiram algumas linhas de comprimento do código =)

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by salviotonon** [comment]
Obrigado pela análise, um dos pontos que eu não tinha gostado do meu código era aquele switch case, esse refactoring utilizando um objeto melhorou 10x a legibilidade do código, muito boa essa abordagem. Valeu até o próximo projeto

**Comment by MivlaM** [comment]
Show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
