### ISSUE TITLE
Resumo da Aula Prototypes da etapa 14

### ISSUE THREAD

**Issue by Diegodkid** [roger-melo-treinamentos/curso-de-js-roger-melo#5907]
### Protottypes
Em uma função construtora também podemos criar métodos:
```js
function Student (name, email) {
  this.name = name
  this.email = email

  this.login = function() {
    return `${this.name} logou`
  }
}

const gabrielFialho = new Student('Gabriel Fialho', 'gabriel@gmail.com')
const jorgeAugusto = new Student('Jorge Augusto', 'jorge@gmail.com')
```
Para criar métodos em uma função construtora não devemos criar os métodos dentro da função, pois cada objeto que é criado a partir da função construtora esta criando um método igual, isso faz com que o mesmo método seja criado em vários espaços de memória desnecessariamente.

Em JS todo novo objeto que criamos herda propriedades e métodos do seu prototype.

O que é um prototype? É o objeto do qual o novo objeto que criamos vai herdar propriedades e métodos

Então a maneira correta de criarmos métodos em uma função construtora é a seguinte:
```js
function Student (name, email) {
  this.name = name
  this.email = email
}

Student.prototype.login = function() {
  return `${this.name} fez login`
}

```
Fora da função construtora usamos o prototype como seter para criarmos o método, assim todo novo objeto que criarmos a partir da função construtora Student vai possuir armazenada em seu proto as propriedades criadas, além disso o método foi criado uma vez e ocupa apenas um espaço na memória.

**Comment by MivlaM** [comment]
Boa @Diegodkid rumo à fluência! 🔥
