### ISSUE TITLE
Resumo da Aula Operadores lógicos && e || - Aula 02-04 da etapa 02

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5911]
![image](https://user-images.githubusercontent.com/106329803/216699300-d5bb4e17-7a73-4445-a792-ebe1264c06ea.png)

**Comment by MivlaM** [comment]
Boa @rafael-rodrigues01 rumo à fluência! 🔥
