### ISSUE TITLE
Resumo da Aula Conversão de Tipos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#593]
# Conversão de Tipos de Dados

É a transformação de uma variável que é de um tipo de dado em outro

Sabemos que uma concatenação de uma string e um number resulta em uma string como está abaixo, isso ocorre porque o JS converte o number por baixo dos panos para string:

```js
let score = "100";
console.log(score + 1); // 1001
```
## Conversão de String para Number

É possível converter primeiro e só depois fazer essa expressão, nesse caso, para converter de string para number basta utilizar o método Number():

```js
let score = "100";
score = Number(score);
console.log(score + 1); // 101
```

## Verificação de Tipo de Dado

Para verificar o tipo de dado basta inserir o operador **typeof**:

```js
console.log(typeof score); // Number
```

É importante dizer que em algumas situações o typeof não será a melhor escolha para verificar o tipo de dado. Isso será abordado mais adiante.

Uma conversão que não faça muito sentido pode resultar em NaN

```js
const crazyConversion = Number('Maça'); // NaN
```

## Conversão de Number para String

Basta usar o método String():

```js
const convertedNumber = String(97);
```

## Conversão de Number para Boolean

Basta utilizar o método Boolean():

```js
const booleanConversion = Boolean(10); // true
```

O código acima resultará em true, pois o JS considera alguns números como true e outros como false

### Valores falsy

Estes são valores que o JavaScript considera como falsos

1. false
2. 0
3. "", '', ``
4. null
5. undefined
6. NaN

### Valores truthy

São qualquer valor que não é falsy

**Até aqui foi visto tipos de conversões explícitas de tipos de dados, que são as que o próprio programador realiza.**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer! Rumo à fluência! 🔥
