### ISSUE TITLE
Resumo da Aula Retornando valores e exercícios - Aula 01-05 da etapa 03

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5936]
Variáveis declaradas dentro do escopo das funções só poderão ser utilizadas dentro deste escopo. Mas existe uma forma de obter um valor de dentro dessa função que é através do Return. Não precisamos necessariamente armazenar o valor em uma variável para poder retorna ela.

**Comment by MivlaM** [comment]
Boa @Luis-avellar rumo à fluência! 🔥
