### ISSUE TITLE
Resumo da Aula O operador lógico not (!) - Aula 03-02 da etapa 02

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5952]
![image](https://user-images.githubusercontent.com/106329803/217059991-676fa95c-a38f-4aaa-a127-50e95b8662a1.png)

**Comment by MivlaM** [comment]
Boa @rafael-rodrigues01 rumo à fluência! 🔥
