### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5963]
This é uma palavra chave usada para referência um objeto.
This é um objeto de contexto, ele representa o contexto do código atual que esta sendo executado. E dependendo de onde e como usar o This e o valor dele vai mudar.  Quando formos usar o This dentro de um método de um objeto temos de usar o uma function declaration para referência o objeto, se por acaso usarmos uma arrow function ele vai referenciar o objeto windows.

**Comment by MivlaM** [comment]
Boa @Luis-avellar rumo à fluência! 🔥
