### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#5972]
**Tipos Primitivos:**

- Number,
- Strings,
- null,
- undefenied,
- boolean,
- bigInt,
- symbol

**Tipos de Referências:** 

- Todos os tipos de objetos;
- Objetos literais;
- Arrays;
- Funções;
- Data

Tipos Primitivos quando tem seus valores copiados eles criam uma novo espaço na memória para salvar esse valor. Já os Tipos de referências não, o que eles tem copiados caso, seus valores sejam copiados, é seus ponteiros que indicam onde na memória o objeto estar salvo. 

Ou seja se tivermos duas variáveis armazenando o mesmo objeto, e alterarmos alguma propriedade de qualquer objeto, ele irá alterar de ambas "variáveis" pois ambas referenciam o mesmo objeto,

**Comment by MivlaM** [comment]
Show @Luis-avellar. Vamo que vamo, rumo à fluência! 🙌
