### ISSUE TITLE
Resumo da Aula Introdução a promises da etapa 11

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#5974]
Promisse e um objeto que representa o sucesso ou falha de uma operação assíncrona, e sempre terá apenas dois resultados possíveis:
- Resolved,  quando a operação foi bem sucedida.
- Rejected, quando houve falha na operação e a promisse foi rejeitada. 

Como argumento da invocação desse construtor (promisse) e passado uma função com os parâmetros "resolve" e "reject" que são uma convenção universal.

              getData = () => {
                  return new Promisse((resolve, reject) => {
                     resolve('dados aqui')
                     //reject('erro aqui')
                  })
              }

Para consumir uma promisse e receber o resultado de sucesso da mesma e utilizado o "then( )".
Para tratar erros usando promisses e utilizado o "catch( )" que pode ser encadeado ao then( ), e este e usado em duas situações: na invocação do reject ou quando o then( ) lança o um erro.

              getData = () => {
                  return new Promisse((resolve, reject) => {
                     //resolve('dados aqui')
                     reject('erro aqui')
                  })
              }

             getData()
                .then(value => console.log(value))
                .catch(error => console.log(error))

**Comment by MivlaM** [comment]
Show @YukOnRails. Vamo que vamo, rumo à fluência! 🙌
