### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#5976]
<h2>Variáveis</h2>

A função de uma variável é armazenar um valor para mim, podendo ser um Number, String, Boolean, Array, Objeto. Isso me possibilita usar esse valor em qualquer lugar no meu código.

Existem maneiras diferentes de declarar variáveis em JavaScript, posso declarar como **let**, **const** e **var**.

**Let** limita seu escopo no bloco onde foi declarada, podendo ser em uma função ou expressão etc... Em outras palavras a variável **let** não é visível globalmente no código assim como uma **var** que independente de onde for declarada ela pode ser visível no código inteiro.

**Const** pode ter seu escopo global ou local dependendo de onde ela for declarada. É necessário atribuir um valor para inicializar  uma constante logo ao declarar ela. Uma **const** cria uma referência de somente leitura, seu valor não é imutável, porem seu identificador não pode ser reatribuido.

<h2>Comentários</h2>

Posso usar comentários no meu código  para que outro desenvolvedor leia. Eu posso criar um comentário de uma linha usando " // " antes da declaração do código ou um comentário de várias linhas declarando o código entre " /*    */ "

**Comment by MivlaM** [comment]
Show @MateusCavalheiro-prog. Vamo que vamo, rumo à fluência! 🙌
