### ISSUE TITLE
return obj [type]

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5978]
### Etapa da aula

4

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370920

### Descreva a dúvida

Oi Roger, 

Creio que minha dúvida seja bem simples mas não sei o nome especifico do que você utilizou para fazer 

Queria entender porque vc "[ ]" (return obj[type]) no minuto 16:07 dessa aula de correção, de toda a lista isso foi a única coisa que não entendi como usa

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dzpoke. Obrigado por detalhar o momento da dúvida no vídeo =)

Vou deixar [aqui](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/2563#issuecomment-999110064) uma issue que acredito que tenha a resposta à essa dúvida. 

Se após ler a issue ainda restar alguma dúvida, pode deixar um comentário aqui abaixo que te ajudo =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
