### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04 da etapa 03

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#5982]
![image](https://user-images.githubusercontent.com/106329803/217919899-93a9eebb-d0a5-49d0-b9ef-7e17d1ed4e07.png)
![image](https://user-images.githubusercontent.com/106329803/217919964-4bf14bfd-ca09-4112-ba31-81c0538e1b6f.png)

**Comment by MivlaM** [comment]
Show @rafael-rodrigues01. Vamo que vamo, rumo à fluência! 🙌
