### ISSUE TITLE
Uso do return em condicionais

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#5983]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula 02 da etapa 05 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/871191

### Descreva a dúvida

Gostaria de saber mais como é o fluxo, o uso e quando usar o `return` num `if`. Percebi apenas que ele foi usado em detrimento do uso do `else`
```js
  /*
  03
  - Modifique as cores dos números dentro da ul da seguinte forma:
    - Se o número é par, ele deve ser exibido na cor "lightblue";
    - Se o número é ímpar, exiba-o na cor "pink".
  */

    const lis = document.querySelectorAll('.number') 
    lis.forEach(li => {
      const ehPar = Number(li.textContent) % 2 === 0
      if(ehPar){
        li.style.color = 'lightblue'
        return
      }

      li.style.color = 'pink'
    })
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Bruno-Luna

## Gostaria de saber mais como é o fluxo, o uso e quando usar o `return` num `if`

O return é usado dentro de funções e sempre quando você precisa retornar um valor e parar a execução da função naquele ponto, ou seja, o código abaixo do return não vai ser executado.

Além de retornar um valor, o `return` finaliza a execução de uma função.

Observe que no código abaixo, `console.log('olá')` não é executado por que logo na primeira linha dentro do bloco da função, o `return` retornou um valor e finalizou a execução da função.

```javascript
const myFunc = function () {
  return 'oi'
  console.log('olá')
}

console.log(myFunc()) // 'oi'
```

No código que você postou, o if está dentro de uma função e o uso do return nesse código é parar a execução dessa função, ou seja, a função só vai ser executada até esse bloco do if. A única particularidade a mais que há nesse código é que o return foi posicionado dentro de um if, mas o princípio é o mesmo. Você mencionou que o uso do else também seria possível nesse caso, e isso é verdade, mas ao usar else if e else, há uma desvantagem que eles adicionam um bloco adicional e que nem sempre é necessário. Por isso, o return é uma alternativa mais enxuta para o funcionamento da função.

Então, lembre-se, o fluxo funciona dessa forma, ao inserir um return dentro do bloco de uma função, ele vai retornar um valor e a função vai parar de ser executada.

Pegou a ideia?

Consegui ajudar com a dúvida? Se ainda tiver ficado confuso em alguma parte, pode comentar logo abaixo que eu irei te ajudar! =)

**Comment by Bruno-Luna** [comment]
Legal, muito obrigado @MivlaM!

**Comment by MivlaM** [comment]
Olá @Bruno-Luna 

Não sei se você já percebeu, mas na plataforma na Etapa 00 - Boas Vindas, há um convite com um link para você entrar no novo grupo de alunos do CJRM no Telegram. Por lá, você pode encontrar respostas mais rapidamente para as eventuais dúvidas e também você vai poder interagir com os outros alunos do treinamento. Se for de seu interesse, dá uma olhada lá =)

**Comment by MivlaM** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
