### ISSUE TITLE
Dúvida na aplicação do conversor de moedas

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#5984]
### Etapa da aula

15

### Nome da aula

Correção dos exercícios da aula 03 da etapa 14 - Aula 01-07

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2004309

### Descreva a dúvida

```js
const url = 'https://v6.exchangerate-api.com/v6/4031ca976d54d32a4b267277/latest/USD'

const getErrorMessage = errorType => ({
  'invalid-key': 'Sua chave de API não é válida.',
  'inactive-account': 'Seu endereço de e-mail não foi confirmado.',
  'quota-reached': 'Sua conta atingiu o número de solicitações permitidas pelo seu plano.',
  'malformed-request': 'O endpoint do seu request precisa seguir a seguinte estrutura: https://v6.exchangerate-api.com/v6/API-KEY/latest/currency',
  'unsupported-code': 'Não oferecemos suporte ao código de moeda fornecido'
})[errorType] || 'Não foi possível obter as informações'

const fetchExchangeRate = async () => {
  try{
    const response = await fetch(url)
    const exchangeRateData = await response.json()

    if(!response.ok){
      throw new Error('Sua conexão falhou. Não foi possível obter os dados')
    }

    if(exchangeRateData.result === 'error'){
      throw new Error(getErrorMessage(exchangeRateData['error-type']))
    }
  } catch(err){
    alert(err.message)
   }
}
```
```html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href="./style.css" rel="stylesheet">
  <title>Exercício 38</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
      <img class="col-sm-6 col-md-5 col-lg-4 col-lg-3 col-xl-3 col-xxl-3" src="./src/img/logo.svg" alt="Logo ">
    </div>

    <div class="row justify-content-center mb-4 mt-4">
      <div class="col-sm-3 col-lg-2">
        <select data-js="currency-one" class="form-select"></select>
      </div>

      <div class="col-sm-3 col-lg-2">
        <select data-js="currency-two" class="form-select"></select>
      </div>
    </div>

    <div class="row justify-content-center align-items-center mb-4 mt-4">
      <div class="col-sm-3 col-md-2">
        <input data-js="currency-one-times" type="number" min="1" class="form-control form-control-lg" value="1">
      </div>
      
      <div class="col-sm-3 col-md-2">
        <p data-js="converted-value" class="converted-value fs-1 text-center mb-0"></p>
      </div>

      <p data-js="conversion-precision" class="conversion-precision text-center m-4"></p>
    </div>
  </div>

  <script src="./app.js"></script>
</body>
</html>
```
```css
body {
  background-color: #F9FAFC;
}

.container {
  padding-top: 7.5rem;
}

.converted-value {
  color: #452B4E;
}

.conversion-precision {
  color: #452B4E;
}
```

Quando vou testar as mensagens de erro, só cai no primeiro `if`

```js
if(!response.ok){
   throw new Error('Sua conexão falhou. Não foi possível obter os dados')
}
```
Mas quando esse `if`:
```js
if(exchangeRateData.result === 'error'){
      throw new Error(getErrorMessage(exchangeRateData['error-type']))
}
```
é colocado primeiro, a mensagem de erro dele aparece.

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Jansen-Muniz 

Você poderia me passar mais informações em relação a sua dúvida? Para ser preciso na resposta, poderia me informar um passo a passo da forma que você está testando as mensagens de erro e como ele está acontecendo? Dessa forma, eu vou poder reproduzir o problema aqui no meu computador e poderei te ajudar de forma certeira.

**Comment by Jansen-Muniz** [comment]
Quando testo colocando uma moeda que não existe:
`const url = 'https://v6.exchangerate-api.com/v6/4031ca976d54d32a4b267277/latest/cents'`

Em vez de aparecer no `alert` a mensagem do segundo `if`, 
que é essa: 'Não oferecemos suporte ao código de moeda fornecido'

Aparece a mensagem do primeiro `if`: 'Sua conexão falhou. Não foi possível obter os dados'
 
```js
if(!response.ok){
      throw new Error('Sua conexão falhou. Não foi possível obter os dados')
}
if(exchangeRateData.result === 'error'){
      throw new Error(getErrorMessage(exchangeRateData['error-type']))
}
```

Porém, quando o código está assim:
```js
if(exchangeRateData.result === 'error'){
      throw new Error(getErrorMessage(exchangeRateData['error-type']))
}
if(!response.ok){
      throw new Error('Sua conexão falhou. Não foi possível obter os dados')
}
```
E faço o mesmo teste: `const url = 'https://v6.exchangerate-api.com/v6/4031ca976d54d32a4b267277/latest/cents'`
Aparace no alert a mensagem de erro correspondente: 'Não oferecemos suporte ao código de moeda fornecido'

Ficou mais claro?

**Comment by Roger-Melo** [comment]
@Jansen-Muniz antes de qualquer coisa, o if que testa `response.ok` deve ser declarado logo abaixo da declaração de `response`. Não faz sentido invocar `.json()` se vc não sabe se `response` realmente está armazenando o objeto que vc espera. 

A forma certa é:

1. declaração de `response`
2. if que testa `response`
3. restante do código

Então no caso que vc disse acima, `response.ok` retorna false ao testar uma moeda que não existe, por isso o primeiro if que testa exatamente `response.ok` é executado.

Essa API retorna um objeto mesmo quando a moeda não existe, por isso o caso 2 que vc mencionou funciona. Mas é só fazer como descrevi no passo a passo acima e vai dar tudo certo =)

**Comment by Jansen-Muniz** [comment]
```js
const url = 'https://v6.exchangerate-api.com/v6/4031ca976d54d32a4b267277/latest/kkk'

const getErrorMessage = errorType => ({
  'invalid-key': 'Sua chave de API não é válida.',
  'inactive-account': 'Seu endereço de e-mail não foi confirmado.',
  'quota-reached': 'Sua conta atingiu o número de solicitações permitidas pelo seu plano.',
  'malformed-request': 'O endpoint do seu request precisa seguir a seguinte estrutura: https://v6.exchangerate-api.com/v6/API-KEY/latest/currency',
  'unsupported-code': 'Não oferecemos suporte ao código de moeda fornecido'
})[errorType] || 'Não foi possível obter as informações.'

const fetchExchangeRate = async () => {
  try {
    const response = await fetch(url)

    if(!response.ok){
      throw new Error('Sua conexão falhou. Não foi possível obter as informações.')
    }

    const exchangeRateData = await response.json()

    if(exchangeRateData.result === 'error'){
      throw new Error(getErrorMessage(exchangeRateData['error-type']))
    }
  } catch(err){
    alert(err.message)
  }
}

fetchExchangeRate()
```

Roger, fiz igual a aula: [https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2004309](url), minuto: 25:13, mas sem olhar, tá dando o mesmo resultado que falei, já fiz até em outra pasta. 
Não sei que bruxaria é essa =(

**Comment by Roger-Melo** [comment]
@Jansen-Muniz dá uma olhada [aqui](https://drive.google.com/file/d/1Qo2qeGVpct5rCXbM4BqsQdNysaqhiRWu/view?usp=sharing).

**Comment by Jansen-Muniz** [comment]
É pq na aula que mandei o link aí, quando faz o teste com o endpoint trocando USD por kkk:
`const url = 'https://v6.exchangerate-api.com/v6/4031ca976d54d32a4b267277/latest/kkk'`
como é uma moeda que não existe aparece a mensagem do segundo `if`, que é: 'Não oferecemos suporte ao código de moeda fornecido'.
Nesse momento, depois que tu implementou a mensagem de erro no DOM, a mensagem de erro que aparece 
é essa que falei: 'Não oferecemos suporte ao código de moeda fornecido'.

![image](https://user-images.githubusercontent.com/92958989/218828197-01bafd90-7f8c-4c3f-8ec1-e2ba68f68de8.png)

**Comment by Jansen-Muniz** [comment]
Tá certo. Obrigado, Roger. Desculpa a insistência kkkk

**Comment by Roger-Melo** [comment]
Nada, o importante é vc entender o que está acontecendo no código. 

Ficou mais claro?

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Entendi o que o mano mandou aí e testei aqui, mas, considerando que tem os dois if's, quando é que cai no `if` que 
testa `exchangeRateData.result === 'error'`? =)

**Comment by Roger-Melo** [comment]
Dá uma olhada na tabela "Response Error Details" dessa [página](https://developer.accuweather.com/accuweather-locations-api/apis/get/locations/v1/%7BlocationKey%7D). 

`response.ok` só vai resultar em `true` se o HTTP status code estiver em 200 a 299. Nenhum dos códigos da tabela acima está entre esse limite.

@Jansen-Muniz

**Comment by Roger-Melo** [comment]
Boa pergunta. 

Se sempre que uma moeda inválida for enviada para a API ela responder com esse objeto com `.ok` resultando em false, o segundo if pode não ser necessário.

@Jansen-Muniz

**Comment by Jansen-Muniz** [comment]
Obrigado, mano Roger, pode encerrar essa issue =)
