### ISSUE TITLE
Resumo da Aula Try/catch em requests e erros personalizados - Aula 06-05 da etapa 11

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#599]
Podemos utilizar um try/catch em uma função assíncrona para tentar verificar se uma requisição foi bem-sucedida e se não for lançamos um erro e o tratamos. Quando utilizamos o encadeamento de promises temos a possibilidade de tratar erros por meio do método `Promise.prototype.catch()`, mas como funções assíncronas possui instruções assíncronas que se comportam como síncronas podemos utilizar o try/catch para lidar com um possível erro durante a requisição.

Para lançarmos erros utilizamos a palavra-chave `throw` que ao ser declarada lança imediatamente um erro e faz com que as linhas abaixo dela (no bloco) sejam ignoradas. 

Em JavaScript erros são objetos e há diferentes construtores diferentes que representam um tipo de erro que podemos lançar. Para visualizar uma lista com todos os erros possíveis que posso lançar é só conferir na documentação a seguir: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel! Rumo à fluência! 🔥
