### ISSUE TITLE
Resumo da Aula 3 escopos em JavaScript que você deve

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#5996]
### 3 tipos de escopo em JS que precisamos conhecer

*ESCOPO:  visibilidade de variavel

* Escopo de FUNCOES:  Variaveis e Constantes declaradas dentro de funcoes so podem ser acessadas somente na funcao em que foram criadas. 

![image](https://user-images.githubusercontent.com/60947491/218284467-e8fa3799-1252-4354-8fb3-ec0d057261c1.png)

* Escopo de  BLOCOS: Em JS um bloco tem abertura e fechamento de chaves "{ }" for/for on/ if, etc. Tem um codigo dentro deles.
* VAR nao e mais utilizado dentro desses blocos pq podem ser acessadas fora dos blocos de execucao esperados causando erro na aplicacao. CONST e LET  foram criadas para evitar esses tipo de erro

![image](https://user-images.githubusercontent.com/60947491/218284529-47b06913-1fbf-476d-a84c-c7691b73b761.png)

* Escopo LEXICO: Nada mais e do que funcoes alinhadas estarem sujeitas a buscarem variaveis em um escopo acima delas  so que essa relacao so tem so um fluxo que e de fora para dentro.

* Quando usamos uma variavel e ela nao foi declarada dentro da funcao ela vai ser buscada no escopo acima, no nosso caso a funcao EXTERNAL.

![image](https://user-images.githubusercontent.com/60947491/218284711-834d67b8-ff9f-41f4-9435-3359c3b8176d.png)

* Como dito antes esse fluxo so funciona de fora para dentro. No exemplo abaixo declaramos um let x =10 dentro da funcao INTERNAL porem se tentar acessar essa variavel na funcao EXTERNAL vai ser retornando um erro

 
![image](https://user-images.githubusercontent.com/60947491/218319918-c22783b9-2750-4aed-9d2c-650f9354944d.png)

**Comment by MivlaM** [comment]
Show @dzpoke. Vamo que vamo, rumo à fluência! 🙌
