### ISSUE TITLE
Checkpoint - Quiz

### ISSUE THREAD

**Issue by apdsrocha** [roger-melo-treinamentos/curso-de-js-roger-melo#6]
- Link da minha versão: https://github.com/apdsrocha/quiz-exercise
- Maiores dúvidas ou dificuldades: refatorar é sempre minha maior dificuldade =/
- Menores dificuldades: estou achando tranquilo chegar no raciocínio para construir as soluções. As explicações e os exercícios estão bem didáticos.

**Comment by Roger-Melo** [comment]
Que legal @apdsrocha! Fico muito feliz em saber que está conseguindo evoluir!

Parabéns pelo projeto! =D

Sobre o refactoring, com a prática e o tempo, você vai sentir que essa habilidade vai ficando mais natural. E ainda vamos praticar muito refactoring durante o curso.

Esses problemas que você está tendo, e as dúvidas que estão surgindo são normais, ok? =)

O importante é praticar, e perguntar sempre que tiver dúvidas!

**Comment by Roger-Melo** [comment]
@apdsrocha estou fechando a issue, mas qualquer dúvida que surgir é só chamar!
