### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6004]
![image](https://user-images.githubusercontent.com/106329803/218533909-a464d2ab-d483-4545-8bea-b02fe491c3a9.png)

**Comment by MivlaM** [comment]
Show @rafael-rodrigues01. Vamo que vamo, rumo à fluência! 🙌
