### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#6008]
Obter um elemento pela ID utilizando o getElementById não necessita a utilização da # devido já esta implícito no método. 

Obter um elemento pela nome da classe utilizando o getElementsByClassName segue o mesmo princípio do getElementById de não precisar a utilização de sua referência CSS, pois esta implícito no método. 

HTML Colections representa uma lista genérica de elementos. Node list são similares porém não idênticos. Também é possível acessar seu conteudo através de CONCHETES. Porém o ForEach não esta disponível para ele. 

Obter um elemento pelo nome da TAG utilizando getElementsByTagName faz com que você selecione todas as Tag do seu HTML gerando um HTML Colections

**Comment by MivlaM** [comment]
Show @Luis-avellar. Vamo que vamo, rumo à fluência! 🙌
