### ISSUE TITLE
Aplicação Quiz

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#6011]
### Etapa da aula

7

### Nome da aula

Template HTML e checando as respostas - Aula 01-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/943417

### Descreva a dúvida

Boa tarde Roger.

Eu não entendi muito bem como prosseguir daqui pra frente. Eu acabei de terminar a minha primeira revisão raio-x e fiz a aula de introdução ao Bootstrap, quando percebi que em seguida já caí na aula que você ensina a fazer a primeira aplicação.
Como eu devo proceder? Eu vejo essa aula Template HTML e checando as respostas - Aula 01-03 para em seguida eu fazer a aplicação com o acompanhamento da aula ou não devo ver a aula e tentar fazer a aplicação sozinho? Estou um pouco apreensivo, pois eu de fato não consigo ainda fazer sozinho.
Desculpe pela pergunta estranha, talvez eu tenha me perdido em alguma explicação.

Muito obrigado!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Ale557333. Dá uma olhada no email "[Alunos CJRM] Análise de aplicações" que foi enviado em 19/09/2022. 

Lá tem as informações que você precisa seguir para enviar suas aplicações. Inclusive, quais aulas vc deve ver antes de tentar fazer sozinho =)

**Comment by Ale557333** [comment]
Obrigado Roger!
Eu não tinha visto o seu e-mail. Vou seguir a risca como está detalhado.

**Comment by Roger-Melo** [comment]
Legal. 

Vou fechar a issue mas no que precisar, basta abrir uma nova =)
