### ISSUE TITLE
Resumo da Aula Criando um objeto literal - Aula 01-03 da etapa 04

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6027]
![image](https://user-images.githubusercontent.com/106329803/219402468-f6df9aa3-433a-4645-93e8-2ea325b94d26.png)
![image](https://user-images.githubusercontent.com/106329803/219402610-905df1f3-9b7f-4dd1-817a-bb774f8b001b.png)
![image](https://user-images.githubusercontent.com/106329803/219402973-a568161a-43cb-497b-94a4-9943a7125ae8.png)

**Comment by MivlaM** [comment]
Show @rafael-rodrigues01. Vamo que vamo, rumo à fluência! 🙌
