### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#6030]
remove() este método permite remover um elemento HTML do meu código. 
createElement() me permite assim como innerHTML criar um novo Elemento HTML no meu código.

**Comment by MivlaM** [comment]
Show @Luis-avellar. Vamo que vamo, rumo à fluência! 🙌
