### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by Luis-avellar** [roger-melo-treinamentos/curso-de-js-roger-melo#6051]
Para criar uma expressão regular ou RegEx é necessário fazer a declaração dela entre barras. As chaves {} tem o papel de quantificar o numero de caracteres que poderão ser inseridos no formulário, porém, existe mais outras formas de quantificar, as chaves é uma delas. 

Em JavaScript as RegEx tem um método disponível chamado test(). Este método tentará dar um match, ou seja, encontrar um valor igual  ao passado por argumento no método. E sempre retornará um Boolean. 

Existe um método para string que também pode nos auxiliar a verificar se uma string  se encaixa na expressão regular que é o método search(), porém o valor passado pelo argumento deste método é a nossa Expressão Regular. E o valor retornado por ela é um numero que corresponde ao index onde o match aconteceu.

**Comment by MivlaM** [comment]
Show @Luis-avellar . Vamo que vamo, rumo à fluência! 🙌
