### ISSUE TITLE
Aplicação: [Quiz]

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#6052]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Ale557333/interactive-quiz

### Maiores dificuldades durante a implementação

Como pessoa autista eu tive dificuldade maior no prazo estipulado no e-mail.

Minha maior dificuldade foi para entender o bootstrap, e estilizar e posicionar melhor o paragrafo do score.

### Menores dificuldades durante a implementação

Encontrar uma imagem com link do ícone JS, pois tive que baixar a imagem e anexar numa pasta. Acredito que se fosse pelo link ficaria melhor, mas ainda não aprendi muito bem como que faz isso, e pelo prazo preferi deixar assim por enquanto e focar no JS.

**Comment by MivlaM** [comment]
Olá @Ale557333

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @Ale557333.

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Minha maior dificuldade foi para entender o bootstrap, e estilizar e posicionar melhor o paragrafo do score.

Sem problemas, não há certo ou errado na forma de exibir os pontos, o mais importante num primeiro momento você já fez, que é implementar a lógica de exibição. De qualquer forma, uma maneira de implementar os pontos será mostrada nas aulas seguintes.

Quanto à estilização, o uso do Bootstrap (ou qualquer lib CSS) é opcional.

Veja o que fica mais confortável pra você.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisóes

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Isso dá mais legibilidade ao ler a expressão `userAnswer === correctAnswers[index]`.

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

---

## Callback do listener de envio do form

Podemos nomear o callback do listener de evento como `showScore`, por exemplo. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, o intuito aqui é nomeá-lo descrevendo a ação mais significativa que essa função irá executar na aplicação quando o form for enviado, assim ao bater o olho no nome da função, a ação que ela executa fica explícita:

```js
// antes
form.addEventListener("submit", (event) => {
  // ...
})
```

```js
// depois
const showScore = (event) => {
  // ...
}
form.addEventListener("submit", showScore)
```

---

## Code Styling

Ao longo do código, há uma única inconsistência em relação ao uso do ponto e vírgula:

```js
// Uso do ponto e vírgula
const userAnswers = [
  // ...
];
```

Todo o resto do código não há o uso do ponto e vírgula, a ideia aqui é considerar que é uma boa prática manter um padrão na maneira que você escreve o código. Uma sugestão é que você escolha uma das formas e seja consistente com essa escolha no decorrer do código.

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que vc formate manualmente.

Isso vai "forçar" vc a adotar um estilo de escrita de código e ser consistente com esse estilo ao implementar suas aplicações.

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, `let score = 0` pode ter uma linha em branco abaixo de sua declaração.

```js
// antes
const showScore = (event) => {
  event.preventDefault()
  
  let score = 0
  const userAnswers = [
    // ...
  ]
  
  // ...
}
```

```js
// depois
const showScore = (event) => {
  event.preventDefault()
  
  let score = 0

  const userAnswers = [
    // ...
  ]
  
  // ...
}
```

---

## forEach

Há um pequeno erro de funcionamento na sua aplicação caso o usuário não acerte nenhuma questão e obtenha 0 como pontuação. Essa pontuação de 0 nunca é mostrada, e o motivo disso é o exatamente o que vai ser mostrado abaixo:

Esse erro de funcionamento acontece por causa da condição apresentada dentro do bloco if, se ela resultar em `false`, o incremento da pontuação nunca acontece e a manipulação de DOM também não vai ser exibida na tela, isto é, se o usuário marcar todas as opções incorretas, a mensagem de pontuação não aparece na tela. Você pode aprimorar o funcionamento do código ao manter as duas linhas de manipulação de DOM fora do if, porém, é uma boa prática manter a manipulação de DOM fora do `forEach`. Independente se o if é executado ou não, o que precisa acontecer dentro do `forEach`, nesse caso, é apenas o cálculo dos pontos:

```js
// antes
const showScore = (event) => {
  // ...
  
  userAnswers.forEach((userAnswer, index) => {
    if (userAnswer === correctAnswers[index]) {
      score += 25

      scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
      form.append(scoreParagraph)
    }
  })
}
```

```js
// depois
const showScore = (event) => {
  // ...
  
  userAnswers.forEach((userAnswer, index) => {
    if (userAnswer === correctAnswers[index]) {
      score += 25
    }
  })

  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
}
```

O forEach é um método síncrono. Isso significa que as linhas de código abaixo da invocação dele só serão executadas quando a execução dele for concluída, a mensagem de pontuação pode ser exibida na tela apenas depois que a pontuação foi calculada. Ao fazer essa alteração, você vai ver que o quiz estará funcionando 100% como o esperado e ainda num código mais conciso para cada parte da função.

---

## Refatoração das funções

Feito esses ajustes, vou te mostrar duas abordagens de refactoring envolvendo a criação de duas funções para deixarmos o código mais conciso em relação a cada trecho de seu funcionamento. O que quero que você entenda, nesse primeiro momento, é o conceito por trás delas. Sabendo disso, observe o código abaixo:

```js
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === correctAnswers[index]) {
    score += 25
  }
})
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. A ideia aqui é, por meio do forEach, percorrer cada uma das respostas escolhidas do usuário e aumentar a pontuação se a resposta dele estiver correta, e por fim, retornar esse número que será a pontuação. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, vamos mover a `let score = 0` para dentro dessa função e declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Vamos manter uma lógica similar a que você usou dentro dessa nova função:

```js
const getScore = (userAnswers = []) => {
  let score = 0

  userAnswers.forEach((userAnswer,index) => {
    if (userAnswer === correctAnswers[index]){
      score += 25
    }
  })

  return score
}
```

Por fim, você pode invocar a função `getScore()` dentro da função `showScore` recebendo o array armazenado por `userAnswers` como argumento.

```js
const showScore = event => {
  // ...
  const score = getScore(userAnswers)
 // ...
}
```

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputQuestion` do form. `userAnswers` vai receber um array vazio que será preenchido após percorrermos cada item dentro do array `correctAnswers` por meio do método `forEach`, e por fim, esse valor que contém as respostas do usuário e que foi armazenado em `userAnswers` vai ser retornado. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}
```

Por fim, você pode invocar a função dentro da função `showScore` que o código funcionará normalmente =)

```js
const showScore = (event) => {
  event.preventDefault()
  
  const userAnswers = getUserAnswers()
  const score = getScore(userAnswers)

  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Ale557333** [comment]
Boa tarde @MivlaM tudo bem?

Eu tentei fazer a parte Refatoração das funções mas sem sucesso. O restante 'anterior a essa parte eu entendi', então  vou colocar meu código aqui com algumas alterações pra você dar uma olhada até aonde eu entendi um pouco para fazer, mas o código está dando erro:

```javascript
const form = document.querySelector(".quiz-form")
const finalResult = document.querySelector('.result')

const correctAnswers = ["B", "B", "B", "B"]

const showScore = (event) => {
  event.preventDefault()

  const score = getScore(userAnswers)

  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ]
  
  const getScore = (userAnswers = []) => {
    let score = 0
    
    userAnswers.forEach((userAnswer, index) => {
      if (userAnswer === correctAnswers[index]) {
        score += 25
      }
    })
    
    return score
  }

  scrollTo(0, 0)
  
  finalResult.querySelector('span').textContent = `${score}%`
  finalResult.classList.remove('d-none')
}

form.addEventListener("submit", showScore)
```

mensagem de erro: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71138743/220736044-c735d6e5-d912-4d64-9d7b-7883ebcd5470.png">

**Comment by MivlaM** [comment]
Olá @Ale557333

Então, antes de começar a responder o problema, eu sugiro que você faça primeiro as refatorações mostradas aqui na análise, para depois prosseguir para as alterações mostradas a partir da aula `Exibindo a pontuação - Aula 02-01", da etapa 07`, assim fica mais simples para você entender o passo a passo daqui e compreender os conceitos até o momento que você fez o quiz, para depois você partir para uma outra funcionalidade na aplicação, mais adiante, serão mostradas refatorações até mesmo para às que eu estou mostrando aqui na análise e caso você as faça primeiro, pode ser que haja um lapso no seu entendimento e as refatorações que eu mostrei aqui ficariam obsoletas. Dito isso, você pode comentar a função `scrollTo` e vamos usar as consts `form` e `scoreParagraph`, da mesma forma que estavam quando você enviou o quiz para a análise.

```js
const form = document.querySelector(".quiz-form")
const scoreParagraph = document.createElement("p")

const showScore = (event) => {
  // ...
  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
}
```

Ok, agora, vamos observar o erro exibido no console, quero que se atente a essa parte `Cannot access 'getScore' before initialization`. O que o erro está querendo dizer, é que ele não está conseguindo acessar a getScore antes dela ser inicializada, ou seja, ela está sendo invocada antes de o javascript conseguir acessá-la. Para corrigir esse erro, você pode mover a função `getScore` para fora de `showScore`, o ideal é que ela seja declarada antes de `showScore`:

```js
const form = document.querySelector(".quiz-form")
const scoreParagraph = document.createElement("p")

const correctAnswers = ["B", "B", "B", "B"]

const getScore = (userAnswers = []) => {
    
  let score = 0
  
  userAnswers.forEach((userAnswer, index) => {
    if (userAnswer === correctAnswers[index]) {
      score += 25
    }
  })
  
  return score
}

const showScore = (event) => {
  event.preventDefault()

  const score = getScore(userAnswers)

  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ]

  // scrollTo(0, 0)
  
  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
}

form.addEventListener("submit", showScore)
```

Porém, se você executar o código assim, verá um erro similar acontecer, mas dessa vez irá aparecer `Cannot access 'userAnswers' before initialization`, o princípio é bem parecido com o anterior, ele está tentando acessar `userAnswers` antes do mesmo ser declarado, e para resolver, você pode mover a linha de declaração de userAnswers para antes de `score`, idealmente, a invocação de `score` será efetuada depois de `userAnswers` já ter sida declarada.

```Js
//antes
const showScore = (event) => {
  event.preventDefault()

  const score = getScore(userAnswers)

  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ]
  // ...
}
```

```js
//depois
const showScore = (event) => {
  event.preventDefault()

  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ]

  const score = getScore(userAnswers)
  // ...
}
```

Após o que eu expliquei aqui, ficou mais claro o entedimento? Se sim, deixo para você a tarefa de implementar a função `getUserAnswers` que foi mencionada na análise, se você não tiver entendido bem ou se tiver alguma dificuldade nessa explicação ou para implementar a outra função, sinta-se livre para comentar logo abaixo aqui na issue que estarei disposto a te ajudar! =)

**Comment by Ale557333** [comment]
Obrigado @MivlaM Fiz exatamente como vc falou e consegui entender sim, mas já em relação a outra função confesso que estou com bastante dificuldade...

```js

const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}

```

eu não entendi o primeiro argumento de dentro do forEach. Basicamente não consegui pegar o que está acontecendo em todo esse trecho de código .

Obrigado

**Comment by MivlaM** [comment]
Olá @Ale557333

Certo, vamos detalhar o que está acontecendo nessa função passo por passo então. Primeiramente a ideia é criar uma função para obter as respostas marcadas pelo usuário do quiz, dessa forma, você não vai mais precisar da const `userAnswers` armazenando cada resposta de forma enumerada, pois a função fará o papel dele e de forma dinâmica. Observe abaixo como é obtido o valor de cada input do usuário:

```js
const userAnswers = [
  form.inputQuestion1.value,  // <-- Cada valor é obtido por meio da notação de ponto, e ela segue um padrão 1...2...3...4
  form.inputQuestion2.value,
  form.inputQuestion3.value,
  form.inputQuestion4.value,
]
```

Sabendo disso, criaremos uma função `getUserAnswers` que não precisa receber nenhum parâmetro, pois o que ela vai usar ou está dentro de seu escopo, ou vai estar num escopo global, como `correctAnswers`, por exemplo. Depois, podemos criar uma const `userAnswers` que vai armazenar um array vazio, de início, a função seria concebida da seguinte forma. 

```js
const getUserAnswers = () => {
  const userAnswers = []

}
```

Agora, vamos pegar a const `correctAnswers` que armazena as respostas corretas para cada pergunta, essa const foi declarada no início do código, ou seja, no escopo global, e com ela, nós vamos encadeá-la num `forEach`, você já viu anteriormente que o forEach pode receber três parametros sendo eles o primeiro, o item atual da iteração, o segundo, o index que corresponde ao item e o ultimo o array inteiro que está sendo iterado, mas nessa situação em específico, nós queremos apenas o segundo parâmetro, o index. Tendo em vista que não vamos usar o primeiro parâmetro, basta colocar um `_` na posição que estaria o primeiro parâmetro e colocar o `index` (que é o segundo parâmetro) logo em seguida, ficaria assim:

```js
correctAnswers.forEach((_, index) => {
  // ...
  })
```

Dessa forma, vamos declarar uma const `userAnswers` que vai pegar cada resposta do usuário de forma dinâmica, lembra que eu mostrei logo no início aqui desse comentário que cada alternativa estava sendo selecionada por meio da notação de ponto? Então, se você observar o trecho abaixo, verá que o que estava acontecendo nas quatro linhas de cada input, também está acontecendo dinamicamente em uma única linha de código. A ideia aqui, é que `userAnswer` vai armazenar um form que na notação de colchetes vai pegar o `inputQuestion`, passar pelo seu `index` e pegar o valor (que é a resposta marcada pelo usuário para aquele input), logo, por estar num método forEach, o javascript vai fazer a mesma coisa para cada um dos inputs, mas dessa vez, será o segundo input devido ao incremento de index + 1 para cada vez. E assim por diante, na terceira vez, ele pegará o valor do terceiro input e por fim, o último.  

```js
const userAnswer = form[`inputQuestion${index + 1}`].value // Nesse trecho, o valor de cada resposta do usuário do quiz é armazenada em userAnswer
```

Após isso, por meio do método push, a const `userAnswers` que foi declarada vazia, terá seu array preenchido com os inputs obtidos no trecho de código acima, e por fim, esse valor que contém as respostas do usuário e que foi armazenado em `userAnswers` vai ser retornado. Se você quiser observar isso sendo feito na prática, você pode executar um `console.log(userAnswers)` da seguinte forma:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  console.log(userAnswers) // Respostas marcadas no quiz aparecerão no console
  return userAnswers
}
```

Após as modificações acima, resta apenas invocar a função `getUserAnswers` na função `showScore` que o código funcionará normalmente:

```js
const showScore = (event) => {
  event.preventDefault()
  
  const userAnswers = getUserAnswers()
  const score = getScore(userAnswers)

  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
}
```

Consegui esclarecer a sua dúvida? Se ainda assim não tiver entendido, sinta-se livre para comentar logo abaixo aqui na issue que estarei disposto a te ajudar!

**Comment by Ale557333** [comment]
Boa tarde @MivlaM  tudo bem?
Consegui entender bem sim a sua última explicação , inclusive eu não sabia que basta colocar um _ na posição que estaria o primeiro parâmetro dentro do forEach quando não quer usar esse primeiro parâmetro.
Eu estou com bastante dificuldade nessa primeira aplicação , tenho um déficit maior do que as outras pessoas para entender algumas coisas, mas eu não consigo avançar sem conseguir de fato entender totalmente e treinar bem para fixar. 
Eu quero terminar esse primeiro passo contigo, refazer tudo sem refatorar e depois refatorar. Mas antes preciso que você me ajude a ver aonde estou errando novamente, pois estou com esse erro agora: Uncaught ReferenceError: Cannot access 'getUserAnswers' before initialization at HTMLFormElement.showScore (app.js:22:23). Acredito que seja erro de escopo novamente, eu ainda não consegui 'pegar' certas coisas, pois me confundo demais quando o código é refatorado.
Obrigado pela sua ajuda e atenção .

```js

const form = document.querySelector(".quiz-form")
const scoreParagraph = document.createElement("p")

const correctAnswers = ["B", "B", "B", "B"]

const getScore = (userAnswers = []) => {
    
  let score = 0
  
  userAnswers.forEach((userAnswer, index) => {
    if (userAnswer === correctAnswers[index]) {
      score += 25
    }
  })
  
  return score
}

const showScore = (event) => {
  event.preventDefault()

  const userAnswers = getUserAnswers()
  const score = getScore(userAnswers)
  
  scoreParagraph.textContent = `Sua pontuação foi de ${score}%`
  form.append(scoreParagraph)
  
  const getUserAnswers = () => {
    const userAnswers = []
  
    correctAnswers.forEach((_, index) => {
      const userAnswer = form[`inputQuestion${index + 1}`].value
      userAnswers.push(userAnswer)
    })
  
    return userAnswers
  }
  
}

form.addEventListener("submit", showScore)

```

**Comment by Roger-Melo** [comment]
Olá @Ale557333. 

A mensagem do erro diz que não e possível acessar `getUserAnswers` antes que ela seja inicializada. Se vc observar a linha que a mensagem do erro menciona, verá que ela contém a invocação da `getUserAnswers`.

Só que não existe nenhuma declaração de `getUserAnswers` acima da invocação dela. Faz sentido agora o que a mensagem do erro quis dizer?

A declaração de `getUserAnswers` precisa vir antes da invocação dela. Ficaria assim:

```javascript
const getUserAnswers = () => {
  // ...
}

const showScore = (event) => {
  // ...
  const score = getScore(userAnswers)
  // ...
}
```

**Comment by Roger-Melo** [comment]
Legal. No que precisar, é só abrir uma nova issue =)
