### ISSUE TITLE
Etapa 15, nome do vídeo: Introdução a regras de segurança no Firestore - Aula 02-07

### ISSUE THREAD

**Issue by gcarniel** [roger-melo-treinamentos/curso-de-js-roger-melo#606]
Olá, @Roger-Melo 

Eu cheguei na aula **Introdução a regras de segurança no Firestore - Aula 02-07**, que é a última lançada. O que devo fazer agora? O que me sugere?
Como será o lançamento das próximas aulas e etapas?

Bom fim de semana.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gcarniel. Qual é o seu objetivo com o treinamento?

**Comment by gcarniel** [comment]
Eu atualmente trabalho com suporte, mas quero ser dev.
Meu objetivo é poder construir aplicação web, quero trabalhar com isso e que isso me traga retorno financeiro melhor do que estou no momento.

Eu tenho um sistema de controle financeiro em VBA, usando Excel como aplicação e Access como banco, quero desenvolver meu sistema todo para web.

**Comment by Roger-Melo** [comment]
Com o que vimos até aqui, você pode aplicar para vagas Jr.

Na verdade, os alunos que já relataram conseguir entrar no mercado ou serem promovidos não tinham 100% de progresso no treinamento.

O [Caio Fábio](https://drive.google.com/file/d/1gNQtRjsa3UHTxZp7-w3W6LM8x1q5q30J/view?usp=sharing), por exemplo, entrou no mercado com 65% do treinamento concluído.

O [Arthur](https://youtu.be/IvG47ce4kz0) foi de estagiário à Front-end Developer em um mês e meio após entrar no treinamento e aplicar o método (28% de progresso atualmente).

O [Alisson](https://youtu.be/8nwGTNKa6gM) foi contratado pelo maior e-commerce de tecnologia da América Latina com apenas 4 meses de estudos (49% de progresso atualmente).

Então se o objetivo é conquistar uma vaga (na empresa atual ou em outra), eu recomendo seguir o marco 6 em diante da [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928).

---

Sobre o sistema de controle financeiro, seria interessante implementá-lo usando uma lib ou framework que vai te proporcionar mais produtividade e escala. Pode ser feito com JS puro, mas não é o mais adequado, pois você terá que implementar na mão algumas coisas que um framwework já faz.

Com o conhecimento que você tem até aqui, será mais fácil aprender um framework.

Se fizer sentido para você, posso recomendar um curso de React de uma pessoa em quem confio.

---

> Como será o lançamento das próximas aulas e etapas?

Da mesma forma que atualmente. Aula por aula, de forma gradativa.

Desde a criação do treinamento, o escopo aumentou bastante. Então é normal o ritmo das entregas ter diminuído um pouco. Mas elas estão sendo feitas =)

---

E lembrando, por ter entrado no treinamento em construção, você tem acesso às aulas e ao suporte do CJRM por quanto tempo precisar. O tempo de acesso vai mudar para quem entrar depois que eu terminar de entregar as aulas. Quem entrou antes, sempre será honrado =)

@gcarniel

**Comment by gcarniel** [comment]
Olá, @Roger-Melo 

Ontem eu me inscrevi para uma vaga de JR. Infelizmente eu sou bastante inseguro, tenho medo de não atender as expectativas de uma empresa e muitas vezes a depender do que a vaga pede eu nem me candidato, por mais que você tenha dito que 80% do que pedem é só pra preencher. Mas aos poucos estou ganhando confiança.

Vou ver os vídeos que mencionou do pessoal para ter uma noção maior.

Sobre o react pode recomendar o curso sim, pretendo fazer, mas por enquanto quero revisar as etapas do curso que tive mais dificuldades e quero entender melhor HTML e CSS também e o projeto de controle financeiro fica pro futuro, preciso pegar uma bagagem melhor.

Perguntei como será o lançamento das próximas aulas para eu me organizar, porque daí quero estudar HTML e CSS e intercalando com as aulas do CJRM. Apenas pra poder deixar cada dia da semana com assuntos fixos.

vlw, Roger.

**Comment by Roger-Melo** [comment]
Essa insegurança é natural. O importante é se candidatar até passar. Só não chega lá quem desiste.

O curso de React que recomendo é [este](https://www.udemy.com/course/curso-reactjs-ninja/?couponCode=CODECON21).

> Perguntei como será o lançamento das próximas aulas para eu me organizar

Dei uma pausa temporária na produção das próximas aulas, por que estou preparando a Semana do JavaScript, que começa dia 18. Em breve vou fixar um aviso sobre isso na plataforma do curso. Após a Semana do JS e a semana de abertura das matrículas, a produção volta ao normal, com vídeos mais ou menos à cada 3 dias =)

@gcarniel

**Comment by gcarniel** [comment]
É isso aí, vamos a luta!

Vou refinar mais meu conhecimento em JS, refazer aulas e exercícios e então vou partir pro react.

Obrigado, Roger.

**Comment by Roger-Melo** [comment]
Excelente @gcarniel. No que precisar, estamos às ordens =D
