### ISSUE TITLE
setInterval()

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#6065]
### Etapa da aula

7

### Nome da aula

setInterval() e animação da pontuação - Aula 02-03

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/963183

### Descreva a dúvida

_**Boa tarde Roger.

Estou com dificuldade para entender a linha 35 onde foi incrementado o counter.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/71138743/220740455-59901dcf-c246-43f9-ace2-55db97f10cd2.png">**_

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Ale557333. A linha 35 apenas faz o counter receber todo o valor que ele já tem somado à 1. 

Se por exemplo, counter estiver armazenando 1, com a expressão `counter++` a let counter irá armazenar o valor que ela tem somado à 1. Nesse caso, a let armazena 1 (valor que ela já tem) + 1. 

Se não tiver ficado claro, descreva a dúvida de forma mais detalhada =)

**Comment by Ale557333** [comment]
Talvez eu não tenha conseguido explicar direito minha dúvida. 
No caso foi gerado um counter para ele tentar se igualar ao score e fazer a animação acontecer? Seria isso?

**Comment by Roger-Melo** [comment]
> ### No caso foi gerado um counter...

Não foi gerado um counter. 

A `let` counter é **incrementada**. Apenas isso. Não há criação ou geração de variáveis na linha 35. Apenas incremento.

> ### ...para ele tentar se igualar ao score e fazer a animação acontecer?

Isso. 

A função de callback do `setInterval` será executada a cada 10 milisegundos até que a condição do `if` resulte em true. Enquanto não resultar em `true`, o que está fora do if será executado:

```javascript
// 👇🏻 isso será executado a cada execução da função em que a condição do if resultar em false
finalresult.querySelector('span').textContent = ...
counter++
```

Quando counter for igual a score, o if será executado. 

Está ficando mais claro?

@Ale557333
