### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by gerafimjoaquim** [roger-melo-treinamentos/curso-de-js-roger-melo#6077]
### Etapa da aula

8

### Nome da aula

Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/986667

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Bom-dia ROGER
Percebi perfeitamente a resolução do exercício sobre o contador e resolvi sozinho até ao fim, como mostra o código abaixo:
```js

const btnInitCounter = document.querySelector('.button-init-counter')
const btnStopCounter = document.querySelector('.button-stop-counter')
const counterContainer = document.querySelector('.counter-container')

let timer = null

const startCounter = () => {
  const incrementedCounter = Number(counterContainer.textContent) + 1
  counterContainer.textContent = incrementedCounter
}

const stopCounter = () => {
  clearInterval(timer)
  counterContainer.textContent  = 0
}

btnInitCounter.addEventListener('click', () => {
  timer = setInterval(startCounter, 1000)
})

btnStopCounter.addEventListener('click', stopCounter)
```
Minha dúvida é a seguinte:
Quando eu clico no botão **Iniciar contador**, o contador inicia, mas se por alguma razão eu volto a clicar no mesmo botão sem primeiro parar o contador, a velocidade da contagem aumenta, como se tivesse reduzidopara metade o tempo. Se eu clico pela terceira vez, a velocidade aumenta ainda mais, como se tivesse dividido o tempo por 3.

Tem como anular o efeito do segundo, terceiro...cliques para que não seja apresentado um comportamento inesperado?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @gerafimjoaquim

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Tem como anular o efeito do segundo, terceiro...cliques para que não seja apresentado um comportamento inesperado?

Existem algumas formas de lidar com esse comportamento. Uma dúvida similar a essa já foi respondida numa issue passada, dê uma olhada [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/3996#issuecomment-1172813573) e depois comenta aqui se ficou mais claro =)

**Comment by gerafimjoaquim** [comment]
Olá @MivlaM 

Ficou muito clara a explicação. Vi as 2 alternativas, a de setar Atributo ```disabled``` e usar ```flag```

Muito obrigado pelo suporte!

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
