### ISSUE TITLE
Etapa 03, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by MarcusViniciusTavaresRangel** [roger-melo-treinamentos/curso-de-js-roger-melo#608]
Olá Roger, bom dia, tudo bem? 

No exercício 03, você resoleveu da seguinte maneira :

```js

const justShow = function (times = 0){
console.log(times)
 }
 		
 for(let i = 1; i < 8; i++){
 justShow(`Esta é a ${i}ª vez que essa string é exibida.`)
 }
 		
 ```		
E eu resolvi dessa maneira:

```js
 function showMe(numberOfTimes){
for(let i = 1; i < 8; i++ ){
 console.log (`Esta é a ${numberOfTimes++}ª vez que essa string é exibida.`)
 }
 }
showMe(1)

```
Por que, na sua resolução, você não precisou declarar `console.log()` para a função? Ela está dentro do `for loop` e não deveria ser invocada, deveria ser armazenada em uma variável e assim então ser chamada, certo? 

E também, não somente nesse exercício mas em outros, quando eu coloco o `return` dentro do `for loop`, na hora de executar, ele me retorna uma vez só, por quê?

ex.:

```js
const iteraction = function (times){
for (let i = 1; i < 5; i++){
return `Esta é a ${times++}ª iteração`
}
}

console.log(iteraction()) //Esta é a NaN iteração

console.log(iteraction(1)) // Esta é a 1ª...
```

Agradeço de antemão pelas explicações!!

P.S.: Estou indo muito bem, sinto que estou evoluindo, comprovando na verdade, porque eu fiz outras atividades de outros sites e consegui, passei por desafios que antes eu não conseguia. Estou refazendo os exercícios do começo até onde eu errei.
Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcus Vinicius. 

Tudo certinho, e contigo?

Fico feliz em saber que está percebendo progresso =)

---

Tanto faz uma função ser uma `function` nomeada ou armazenada em uma contante. Quando ela for invocada, o código dentro do bloco dela é executado:

```javascript
const myFunc = function () {
  console.log('myFunc executada')
}

function myFunc2 () {
  console.log('myFunc2 executada') 
}

myFunc()  // myFunc executada
myFunc2() // myFunc2 executada
```

No exercício 3, não foi necessário invocar o console.log por que a função que é invocada a cada execução do loop tem uma invocação do console.log dentro do bloco dela.

Então se a declaração de uma função contém uma invocação do console.log() e essa função é invocada dentro de um loop, toda vez que o loop for executado, a invocação da função irá ser executada e, consequentemente, o código dentro do bloco dela:

```javascript
const myFunc = function () {
  console.log('myFunc executada')
}

for (let i = 0; i < 2; i++) {
  myFunc()
}

// 'myFunc executada'
// 'myFunc executada'
// 'myFunc executada'
```

Ou seja, no fim das contas, dentro do loop, o que está acontecendo é isso:

```javascript
const myFunc = function () {
  console.log('myFunc executada')
}

myFunc() // 'myFunc executada'
myFunc() // 'myFunc executada'
myFunc() // 'myFunc executada'
```

Ficou mais claro?

---

> quando eu coloco o `return` dentro do `for loop`, na hora de executar, ele me retorna uma vez só

`return` deve ser usado dentro de funções. `for` não retorna valor, apenas funções retornam.

Além de retornar um valor, o `return` finaliza a execução de uma função. Por isso o `for` é executado apenas uma vez.

Observe que no código abaixo, `console.log('olá')` não é executado por que logo na primeira linha dentro do bloco da função, o `return` retornou um valor e finalizou a execução da função.

```javascript
const myFunc = function () {
  return 'oi'
  console.log('olá')
}

console.log(myFunc()) // 'oi'
```

Então lembre-se, ao inserir um return dentro do bloco de uma função, ele vai retornar um valor e a função vai parar de ser executada.

Pegou a ideia?

---

E uma dica... cuidado com a indentação do código.

Um código não-indentado tem a legibilidade prejudicada. Sempre indente o código como mostrado nas aulas para facilitar a leitura de quem o lê =)

@MarcusViniciusTavaresRangel

**Comment by MarcusViniciusTavaresRangel** [comment]
Opa Roger, bom dia! Tudo certo por aqui, espero que aí também!

Muito obrigado pelas respostas, analisei novamente os exercícios e realmente compreendi que a função seria executada dentro do `for loop` por seu bloco de código conter a invocação de um console.log(), portanto a cada iteração, logicamente ela seria chamada no console.
Realmente precisava dessa explicação sobre o `return`, é muito importante porque nós humanos pensamos semanticamente aí podemos associar o `retornar` com qualquer operação no JavaScript. 

Desculpe a demora em responder, eu fiquei até agora 'pegado' com essa parte, até eu entender de verdade, sempre foi uma de minhas maiores dificuldades no JavaScript, implementar as funções. É quase o mesmo que dizer que sabe jogar futebol, mas não sabe passar a bola direito, é um fundamento básico, mas eu me confundo por vezes. 

Sem querer ser enxerido, mas já sendo, pedagogicamente o exercício cinco pode estar um pouco confuso para os(as) alunos(as). Porque você pede que implementemos uma função para determinar se um número é positivo e a utilizemos para descobrir quantos números positivos um array possui. Bom, a 'confusão pedagógica' está no fato de que não é preciso uma função para saber isso, basta um `for loop` com uma estrutura condicional, um método `.push()` e pronto. Depois é só invocar os um console.log() com a frase e substituir os valores sem precisar de uma função. 

e.x:

```js
const myArray = [1, -2, 3, -4]

let counter = 0

for (let i = 0; i < myArray.length; i++){
			
 if(myArray[i] >= 1){
                 
        counter += 1
				
       }
}

console.log(`O array "myArray" possui ${myArray.length} números, sendo ${counter} positivos e ${myArray.length - counter} negativos.`) 
//...4 números...2 positivos  e 2 negativos
```

Por isso, eu acredito que o enunciado deveria trazer 'implemente uma função que retorne os números positivos de um array. Use como referência o array '[X, Y, Z]', porque assim é demonstrado que a função possui utilidade ao retornar valores positivos de qualquer array.

Eis a minha resolução do exercício cinco:

```js
const randomNumbers = [-2, 93, 34, -1, 1, 93, 11, -7, 47, -3]

const isAPositive = function(array){

 		let positives = 0
 
for(let i = 0; i < array.length; i++){

		let thisIsAPositiveIndex = array[i] > 0
		
				if (thisIsAPositiveIndex ){
						 positives += 1
				}
}

return positives

}

const totalNumbers = randomNumbers.length

const positiveNumbers = isAPositive(randomNumbers)

const negativeNumbers = randomNumbers.length - isAPositive(randomNumbers) 
console.log(`O array "randomNumbers" possui ${totalNumbers} números, sendo ${positiveNumbers} positivos e ${negativeNumbers} negativos.`)

//...10 números...6 positivos e 4 negativos

```

É só uma sugestão, a sua resolução é  obviamente cirúrgica, eu compreendo que 'uma função para determinar se um número é positivo', pode parecer mais 'suave' para o aluno, mas o propósito de aplicar essa função pode se perder, não ser significativo.

De qualquer forma, estou sim sentindo melhora e evolução, por causa das suas aulas. Tenho certeza de que está sendo um excelente investimento o curso contigo. Sei que tenho ainda um longo caminho a percorrer.

Abraço!

**Comment by Roger-Melo** [comment]
Oi Marcus Vinicius. 

Na verdade feedbacks são muito bem-vindos, fique à vontade =D

Nesse caso, meso que o resultado possa ser alcançado sem uma função, a intenção é "forçar" o aluno a usá-la mesmo. Isso por que à partir desse ponto do treinamento, será cada vez menos frequente deixarmos código "solto", que não esteja encapsulado em uma função de única responsabilidade. Você irá perceber isso conforme avança no treinamento e irá perceber como seu código ficará mais conciso e legível ao adotar esse tipo de design de código =)

@MarcusViniciusTavaresRangel

**Comment by Roger-Melo** [comment]
@MarcusViniciusTavaresRangel vou fechar a issue mas no que precisar, é só abrir uma nova =)
