### ISSUE TITLE
Resumo da Aula Variáveis e escopo de bloco - Aula 02-02 da etapa 04

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6080]
![image](https://user-images.githubusercontent.com/106329803/221003460-6d76c307-eebe-402b-95f8-229f7f291b85.png)
![image](https://user-images.githubusercontent.com/106329803/221003513-66442dc2-38e3-4b05-8165-93bd7581bdb4.png)

**Comment by MivlaM** [comment]
Excelente @rafael-rodrigues01, rumo à fluência! 🎯
