### ISSUE TITLE
Aplicação: conversor de moedas

### ISSUE THREAD

**Issue by Jansen-Muniz** [roger-melo-treinamentos/curso-de-js-roger-melo#6082]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Jansen-Muniz/conversor-de-moedas

### Maiores dificuldades durante a implementação

Implementar as mudanças a cada alteração nos inputs.

### Menores dificuldades durante a implementação

Fazer o request para a API

**Comment by MivlaM** [comment]
Olá @Jansen-Muniz

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @Jansen-Muniz!

> ## Implementar as mudanças a cada alteração nos inputs.

Mesmo com as dificuldades relatadas, vc conseguiu implementar a aplicação. Está de parabéns =D

Vou deixar abaixo a análise com alguns pontos de melhoria que encontrei e qualquer dúvida, pode comentar aqui abaixo que te ajudo, ok?

---

## Usabilidade

Em termos de usabilidade, para o usuário, não acredito que seja uma boa experiência a falta de contraste da logo com a cor de fundo. Dependendo da quantidade de brilho, ou se o usuário usa algum filtro, pode se tornar bem complicada a situação de visualização da tela. Uma boa ideia aqui, seria fazer com que as cores da logo tivessem um certo contraste com a cor de fundo, para assim evitar a situação mencionada anteriormente

---

## init

Aqui vale uma observação, partindo do princípio que `getCurrency` já retorna um objeto, `internalExchange` não precisa receber um novo objeto + destructuring, porque a expressão `await getCurrency('USD')` já resulta num objeto e você pode fazer com que `internalExchange` aproveite esse mesmo objeto que `getCurrency` retorna. Não é necessário criar um novo objeto e nem usar o spreading operator aqui, você pode deixar esse trecho de código com um entendimento muito mais simples e muito mais fácil ao fazer com que `internalExchange` receba diretamente o objeto que `getCurrency` retorna. Ficaria assim:

```js
// antes
const init = async () => {
  internalExchange = {...(await getCurrency('USD'))}

  // ...
}
```

```js
// depois
const init = async () => {
  internalExchange = await getCurrency('USD')

  // ...
}
```

---

## showInitialConverted

Se fizer sentido para você, a função `showInitialConverted` pode ter seu nome substituido por `showInitialExchange`. Acredito que dessa forma o nome tenha um sentido um pouco mais próximo do que a função está fazendo, é uma opinião pessoal, mas se você achar interessante, sinta-se livre para escolher da forma que lhe agradar mais.

```js
// antes
const showInitialConverted = () => {
  // ...
}
```

```js
// depois
const showInitialExchange = () => {
  // ...
}
```

---

## showInitialExchange

Há algumas observações que podem ser consideradas nessa função. De início, a função `getOption`, ao ser invocada está retornando mais de uma opção, ou seja, por estar trabalhando com mais de um option, a ideia aqui é que ela seja preferencialmente nomeada no plural, como `getOptions`, por exemplo, para que assim o entendimento de seu papel no código se torne mais efetivo:

```js
// antes
const getOption = selectedCurrency => Object.keys(internalExchange.conversion_rates)
  .map(currency => optionTemplate(selectedCurrency, currency))
```

```js
// depois
const getOptions = selectedCurrency => Object.keys(internalExchange.conversion_rates)
    .map(currency => optionTemplate(selectedCurrency, currency))
```  

Se for interessante para você, a invocação de getOptions não precisa estar dentro do escopo de `showInitialExchange`, o motivo por trás disso é mantê-la fazendo o que ela já faz do mesmo jeito e fazer com que a função `showInitialExchange` se tornar mais responsável por uma única coisa. Ao declarar a função `getOptions` no mesmo escopo de `showInitialExchange`, você está facilitando o entendimento do código, deixando mais claro que elas fazem coisas diferentes e tem responsabilidades diferentes. Então, a ideia aqui é que `getOptions` seja movida preferencialmente para cima da `showInitialExchange`:

```js
// antes
const showInitialExchange = () => {
  // ...
  const getOptions = selectedCurrency => Object.keys(internalExchange.conversion_rates)
    .map(currency => optionTemplate(selectedCurrency, currency))
  // ...
}
```

```js
// depois
const getOptions = selectedCurrency => Object.keys(internalExchange.conversion_rates)
  .map(currency => optionTemplate(selectedCurrency, currency))

const showInitialExchange = () => {
  // ...
}
```

Uma outra possibilidade de refatoração seria, se for interessante para você, você não precisar mais da função `optionTemplate`. Segundo o raciocínio, ao invés de termos essa função, nós vamos ter apenas a marcação HTML dessa função passada como retorno do callback do map da função `getOptions`. A ideia dessa refatoração é ao invés de invocarmos duas funções que estão em locais distantes uma da outra, você pode facilitar a leitura ao deixar logo de cara o que o retorno do map está fazendo, dessa forma, você pode economizar algumas linhas e simplificar as coisas, optando por apenas invocar uma única função que irá fazer o papel das duas:

```js
// antes
const optionTemplate = (selectedCurrency, currency) => 
  `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`

const getOptions = selectedCurrency => Object.keys(internalExchange.conversion_rates)
  .map(currency => optionTemplate(selectedCurrency, currency))
```

```js
// depois
const getOptions = selectedCurrency  => Object.keys(internalExchange.conversion_rates)
  .map(currency => `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`)
```

Para quem está lendo apenas as invocações da função `getOptions`, ao ler seus argumentos não fica tão claro o que eles significam no contexto por ao todo. Você pode, se for de seu interesse, inserir um objeto em que haja uma propriedade que facilite no entendimento, por exemplo, `selectedCurrency` e especificar a string da sigla da moeda escolhida. O intuito aqui é ajudar na legibilidade, para isso, você também pode, na declaração da função, utilizar a abordagem de destructuring na declaração de parâmetro. Ficaria assim:

```js
// antes
const getOptions = selectedCurrency  => Object.keys(internalExchange.conversion_rates)
  .map(currency => `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`)

const showInitialExchange = () => {
  // ...

  currencyOneEl.innerHTML = getOptions('USD')
  currencyTwoEl.innerHTML = getOptions('BRL')

  // ...
}
```

```js
// depois
const getOptions = ({ selectedCurrency }) => Object.keys(internalExchange.conversion_rates)
  .map(currency => `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`)

const showInitialExchange = () => {
  // ...

  currencyOneEl.innerHTML = getOptions({selectedCurrency: 'USD'})
  currencyTwoEl.innerHTML = getOptions({selectedCurrency: 'BRL'})

  // ...
}
```

Agora, quero que preste bastante atenção na refatoração a seguir:

Se você executar a aplicação, abrir o dev tools no navegador, inspecionar qualquer um dos selects e abrir suas opções, verá algo similar ao mostrado na imagem abaixo:

![Select](https://user-images.githubusercontent.com/82729897/222978504-3edd77bf-1f07-4342-8b31-6f5a4b7ff940.png)

A função `getOptions` está gerando vírgulas na marcação HTML...

Mas por que isso está acontecendo?

Bem, os options estão sendo separados pela vírgula, essa vírgula é colocada para separar cada item, quando é inserido um array renderizado como conteúdo da tag option, mas, para esse array ser renderizado como conteúdo, ele é transformado por baixo dos panos pelo javascript em string, e quando um array é transformado em string, as chaves são removidas e as vírgulas ficam.

Você pode ver esse comportamento funcionando na prática da seguinte forma:

Se você acessar o dev tools e declarar um array [1,2,3] e invocar o método `toString()` nele, verá que o seguinte acontece:

```js
[1,2,3].toString() // método toString() é invocado...

// Resultado: '1,2,3'
```

Uma string `1,2,3`! É isso que está acontecendo por baixo dos panos, quando um array é colocado para ser renderizado como string, o toString vai ser executado, os colchetes do array vão ser removidos e ele vai virar uma string com as vírgulas entre cada item do array.

Agora, retornando ao seu código. Por que o `getOptions` está retornando aquelas vírgulas? A resposta é que `getOptions` retorna um array, e um array quando convertido em string ele vai ter o método .toString() invocado por baixo dos panos e é o que está resultando em todas aquelas vírgulas juntas dos options.

Para resolver esse comportamento indesejado, a idéia é encadear no map, a invocação do método join. O join é um método de array que vai juntar todos os itens do array em uma string e como seu argumento, você pode usar um separador entre esses itens, o separador seria uma string em branco, pois você não quer separar os itens e sim, apenas evitar com que as vírgulas sejam retornadas:

```js
// antes
const getOptions = ({ selectedCurrency }) => Object.keys(internalExchange.conversion_rates)
  .map(currency => `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`)
```

```js
// depois
const getOptions = ({ selectedCurrency }) => Object.keys(internalExchange.conversion_rates)
  .map(currency => `<option ${selectedCurrency === currency ? 'selected' : ''}>${currency}</option>`).join('')
```

![Select2](https://user-images.githubusercontent.com/82729897/222979105-813bb780-9514-41d4-b82e-adaa9dec51d1.png)

---

Por fim, há uma inconsistência de code styling em relação aos parênteses de `BRLCurrency` antes da invocação de `toFixed`. Uma sugestão é que você escolha uma das formas e seja consistente com essa escolha no decorrer do código e ao implementar suas aplicações, um código com uma abordagem consistente sempre vai ter uma visualização mais simples e fácil para quem o estiver lendo.

```js
// antes
convertedValueEl.textContent = (BRLCurrency).toFixed(2)
```

```js
// depois
convertedValueEl.textContent = BRLCurrency.toFixed(2)
```

---

## showTimesCurrency

Aqui, se fizer sentido para você, você pode fazer com que essa função seja mais precisa em relação a seu nome, nesse contexto, a função `showTimesCurrency` pode ter seu nome substituido por `showMultipliedExchange`. O intuito aqui é fazer com que ao bater o olho no nome da função, quem estiver lendo já saiba diretamente o que a função está fazendo e qual seu papel no código.

```js
// antes
const showTimesCurrency = () => {
  // ...
}
```

```js
// depois
const showMultipliedExchange = () => {
  // ...
}
```

---

## currencyOneEl.addEventListener

Podemos nomear o callback do listener de evento como `handleCurrencyOneChange`, por exemplo. Nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, o intuito aqui é manter o padrão que já foi estabelecido no código de nomear os callbacks descrevendo a ação mais significativa que essa função irá executar na aplicação. A vantagem aqui, é que mesmo se optar por um nome relativamente mais genérico, ainda será melhor para o entendimento do todo ao todo, assim ao bater o olho no nome da função, a ação que ela executa fica explícita. Há também uma outra ocorrência de `internalExchange` recebendo um objeto + destructuring sem haver necessidade, aqui, vale a mesma abordagem que já foi mostrada no início da análise, apenas fazer com que internalExchange receba o objeto que `getCurrency` retorna:

```js
// antes
currencyOneEl.addEventListener('input', async e => {
  internalExchange = {...(await getCurrency(e.target.value))}
  showUpdatedRates()
})
```

```js
// depois
const handleCurrencyOneChange = async e => {
  internalExchange = await getCurrency(e.target.value)
  showUpdatedRates()
}

currencyOneEl.addEventListener('input', handleCurrencyOneChange)
```

---

## buttonCloseEl.addEventListener

Há um detalhe importante no listener de evento em relação à função `closeErrorMessage`, você não precisa invocar essa função para que ela execute a linha `errorMessageContainerEl.classList.add('hidden')` quando ela está sendo passada como callback do listener de evento. Lembre-se que quando uma função não está retornando algo, ela retorna undefined e é isso que ela está retornando. Como não é esse o comportamento desejado, nesse trecho de código, não é necessário invocar a função no listener. Ficaria assim:

```js
// antes
const closeErrorMessage = () => {
  errorMessageContainerEl.classList.add('hidden')
}

buttonCloseEl.addEventListener('click', closeErrorMessage())
```

```js
// depois
const closeErrorMessage = () => {
  errorMessageContainerEl.classList.add('hidden')
}

buttonCloseEl.addEventListener('click', closeErrorMessage)
```

---

É isso. Mais uma vez, parabéns pelo esforço! 

As observações fizeram sentido?

**Comment by Jansen-Muniz** [comment]
Sim. Obrigado =)
