### ISSUE TITLE
Etapa 11, Exercícios da aula 04

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#609]
Olá professor! Estou com dúvidas a respeito do que está ocorrendo no seguinte código:
```js
const calculator = operator => {
  return (num1, num2) => {
    const operations = {
      '+': `Resultado da operação: ${num1} ${operator} ${num2} = ${num1 + num2}.`
    }

    return operations[operator] || 'Operação inválida.'
  }
}

const sum = calculator('+')
console.log(sum(1, 1))
```
Essa função externa e essa função interna estão ocupando posições diferentes na memória ou ambas ocupam a mesma posição na memória já que temos um aninhamento?
Minha outra dúvida é a respeito na invocação da ```calculator('+')```, esse valor que está sendo atribuído para o parâmetro ```operator``` sempre ficará armazenado na stack ou ele fica armazenado lá só enquanto a função ainda não termina sua execução?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel.

> Essa função externa e essa função interna estão ocupando posições diferentes na memória ou ambas ocupam a mesma posição na memória já que temos um aninhamento?

Funções são objetos, então quando declaramos uma função estamos declarando um objeto. 

Da mesma forma que um aninhamento de objetos cria 2 objetos diferentes na memória, o mesmo acontece com aninhamento de funções =)

```javascript
const externalObj = {
  internalObj: {}
}

console.log(externalObj === externalObj.internalObj) // false

const externalFunc = () => {
  const nestedFunc = () => {}
  console.log(externalFunc === nestedFunc)
}

externalFunc() // false
```

Sacou a ideia?

Sobre o parâmetro `operator`, ele só é mantido na stack até a última execução da função que usa ele. A pós todas as invocações das funções que o utilizam, o frame da stack que contém a função é destruído da memória, como qualquer outra função.

Aqui tem algumas informações mais detalhadas sobre call-stack e event loop:

- [What the heck is the event loop anyway?](https://youtu.be/8aGhZQkoFbQ)
- [In The Loop](https://youtu.be/cCOL7MC4Pl0)

Se ainda tiver alguma dúvida, ou problemas pra entender os vídeos em inglês, é só avisar =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
No que diz respeito aos objetos e ocuparem posições diferentes na memória não há mais dúvidas professor, mas ainda queria tirar uma outra dúvida...

> Sobre o parâmetro operator, ele só é mantido na stack até a última execução da função que usa ele. 

Professor seguindo o mesmo exemplo do exercício... Quando a função externa é invocada o parâmetro ```operator``` é criado em memória também, logo como estamos utilizando-o dentro de uma função aninhada o valor que o ```operator``` armazena em memória só será apagado quando a execução dessa função aninhada for finalmente concluída e consequentemente excluída da stack?

**Comment by Roger-Melo** [comment]
> o valor que o operator armazena em memória só será apagado quando a execução dessa função aninhada for finalmente concluída e consequentemente excluída da stack?

Isso mesmo. `operator` é um parâmetro e parâmetros são variáveis (variáveis locais da função). Uma variável só é mantida na memória enquanto ela é usada. Logo após o último uso dela, ela é descartada. Eu ainda pretendo falar sobre [garbage collection](https://developer.mozilla.org/en-US/docs/Glossary/Garbage_collection) no treinamento, em etapas mais avançadas. 

> o operator, por exemplo, é criado na memória durante uma invocação depois removido e em invocações posteriores é criado novamente porém armazenando novos valores (passados por parâmetro), exato?!

Isso mesmo =)

Não precisa pedir desculas não, tô aqui pra ajudar! No que eu puder contribuir, pode contar comigo =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Dúvidas sanadas da melhor forma, padrão do treinamento. Obrigado professor, agora partiu estudar rs 😜😜😜
