### ISSUE TITLE
Resumo da Aula O que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#6092]
<h1>O que são funções</h1>

Funções são blocos de códigos reutilizáveis que eu posso invocar e usar em qualquer parte do código. Usar funções é muito útil porque eu vou declarar o código apenas uma vez e depois posso invocar ela multiplas vezes chamando o nome da função e abrindo e fechando parênteses.

```js

// declarando a função
function test () {
  //bloco de código
}

// invocando a função
test()
```

**Comment by MivlaM** [comment]
Excelente @MateusCavalheiro-prog, rumo à fluência! 🎯
