### ISSUE TITLE
Etapa 03 - Aula 02-04 e Etapa 04 - Aula 01-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#61]
Roger, tenho umas duvidas 

/*
  12

  - Converta o for loop abaixo em um forEach;
  - Após a conversão, verifique se a cópia do array lettersCopy realmente foi  
    criada.
*/

* A questão 12 (Etapa 03 - Funções e Métodos)

- Sobre o forEach ele é usado somente para arrays?
Se eu tiver um json, com objetos e arrays misturados posso usar ele.

* E também a finalidade do callback é sempre retorna alguma coisa?

- A questão 14 (Etapa 03 - Funções e Métodos)

Quando penso em array já penso em loop.
Quando fui resolver já fui usando.
Eu posso usar um loop aí para gerar esses index dinamicos?

/*
  14

  - Implemente uma função que retorna uma string com a quantidade de pessoas que  
    curtiram um post, conforme descrito a seguir;
  - A função deve receber por parâmetro um array com os nomes das pessoas que  
    curtiram o post/vídeo/foto;  
  - Se o array recebido estiver vazio, a mensagem que a função deve retornar é  
    "Ninguém curtiu isso";  
  - Se o array conter apenas um nome, como "Rafael", por exemplo, a mensagem  
    retornada deve ser "Rafael curtiu isso";  
  - Se o array conter 2 nomes, a mensagem retornada deve ser  
    "NOME_1 e NOME_2 curtiram isso";  
  - Se o array conter 3 nomes, a mensagem retornada deve ser  
    "NOME_1, NOME_2 e NOME_3 curtiram isso";  
  - Se o array conter 4 ou mais nomes, a mensagem retornada deve ser  
    "NOME_1, NOME_2 e mais X pessoas curtiram isso". O "X" deve ser substituído  
    pelo restante da quantidade de pessoas que curtiram o post (além das duas  
    pessoas já mencionadas no início da mensagem).
*/

```

const nomes = (nomes = []) => {
    const primeiro = nomes[0]
    const segundo = nomes[1]
    const terceiro = nomes[2]
    const total = nomes.length - 2
  
    switch(nomes.length){
      case 0:
        return "Ninguém curtiu isso"
      case 1:
        return `${primeiro} curtiu isso`
      case 2:
        return `${primeiro} e ${segundo} curtiram isso`
      case 3:
        return `${primeiro}, ${segundo} e ${terceiro} curtiram isso`
      default:
        return `${primeiro}, ${segundo} e mais ${total} pessoas curtiram isso.`
    }
}
console.log(nomes(['ed', 'ze', 'ana']))

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Legal, vamos lá =D

---

> - Sobre o forEach ele é usado somente para arrays? Se eu tiver um json, com objetos e arrays misturados posso usar ele.

Isso. O `forEach` é um dos métodos usados **apenas em arrays**. Então não, o `forEach` não pode ser usado em JSON.

Existem métodos específicos para strings JSON também. Mostro isso em etapas mais avançadas do treinamento.

---

> * E também a finalidade do callback é sempre retorna alguma coisa?

Não. Callbacks são apenas funções inseridas como argumentos em invocações de outras funções.

A invocação do `forEach`, por exemplo, recebe uma função de callback como argumento. Essa função **não retorna** um valor. O motivo disso é explicado em etapas seguintes.

---

> Quando penso em array já penso em loop.

Não é tão simples. Seria o mesmo que pensar em uma furadeira como a ferramenta ideal para resolver todos os problemas relacionados à marcenaria. Uma furadeira não é eficiente para afundar um prego na madeira.

Mas, se além da furadeira você conhece outras ferramentas, como o martelo, saberá qual delas resolve o problema de forma mais eficiente.

---

> Eu posso usar um loop aí para gerar esses index dinamicos?

É possível obter os itens de forma dinâmica de várias formas. Neste caso, loops não são a forma mais eficiente.

Só que eu vou mostrar como fazer isso em etapas mais avançadas. Então não fique tão focado em escrever o código perfeito agora. Aos poucos, eu vou mostrando como você refina suas implementações. 

Apenas tenha certeza de que entendeu as ferramentas e conceitos mostrados nas aulas. E se surgirem dúvidas, é só perguntar =)

Respondi suas perguntas?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
Roger você é o cara!
Valeu pela excelente explicação 
E o conteúdo do curso já esta me ajudando
no meu trabalho com front-end!
abs

**Comment by Roger-Melo** [comment]
Legal! Fico feliz que o treinamento esteja ajudando em sua jornada rumo à fluência. É só o começo!

Vou fechar issue mas se surgirem dúvidas, já sabe, é só abrir uma nova issue =)
