### ISSUE TITLE
Resumo da Aula 03-04 - Exercicios(05) da etapa 02

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#610]
Estudo For - If - Break
  ```JS  
          const randomV = [57 , false , 'JS' , true , 'HTML' , 31]
          let item = []
          for(let x = 0; x< randomV.length; x++){
          item = randomV[x]
```
  &gt; 'item' recebe os elementos do array; A cada iteração exibida pelo 'console.log' dentro do bloco 'For'; 'item' recebe mas não 'acumula', compravado pelo 'console.log' fora do bloco, que exibe o último elemento do array(31);

  &gt; Mudando para esta instrução:
````JS
         item += randomV[x]
````
  &gt; Agora a cada iteração, 'item' recebe e concatena cada elemento, os mesmos são agrupados sem espaço:

        57falseJStrueHTML31

  &gt; Vamos inserir o If - Break:
````JS
        for(let x = 0; x< randomV.length; x++){
        item += randomV[x]
        if(randomV[x] <= randomV[4]){
        console.log('Ponto de Break')
        break}
````
 &gt; As iterações progrediram até o item[3] do array(true), a iteração seguinte não mostra o item [4] e sim a mensagem 'Ponto de Break'; **....MAAAAS... o console.log fora do bloco do 'For' exibe o item [4] - 'HTML' , excluindo apenas o último item(31);

  &gt; Lembrando do 'Processamento em Linha' , a instrução ' item += randomV[x]' estando antes do 'If - Break' garante que o elemento [4] da iteração, entre na concatenação de 'item +=' então só depois  é analisada pela condicional de 'If' e bloqueada por 'Break';

  &gt; Alterando a posição da linha ' item += randomV[x]' :
````JS
        for(let x = 0; x< randomV.length; x++){
        if(randomV[x] <= randomV[4]){
        console.log('Ponto de Break')
        break}
        item += randomV[x]
````
  &gt; Nesta configuração 'item' recebe os 4 primeiros elementos do array;

  &gt; Agora, analisando os tipos dos 4 primeiros elementos do array com o mesmo código acima , apenas mudando para a instrução ' item = randomV[x]' para vermos as iterações do 'For', e logo abaixo incluir 'console.log(typeof item)';

  &gt; Nesta situação não ocorre a concatenação de itens, apenas a observação dos tipos dos elementos na ordem das iterações:

                              &gt;  number
                              &gt;  boolean
                              &gt;  string
                              &gt;  boolean
                              &gt;  * Ponto de Break

  &gt; Após analisar os tipos, façamos a quantificação do tipo 'Boolean' encontrado nesta partição do array:
````JS
         let item = []
         let booleanTypes = 0
         
         for(let x = 0; x< randomV.length; x++){ 

         if(randomV[x] <= randomV[4]){
         console.log('Ponto de Break')
         break}

         item = randomV[x]

         if(typeof randomV[x] === 'boolean'){
         booleanTypes += 1}
````

  &gt; Por escolha pessoal, sempre coloco um 'console.log' dentro do bloco 'For' e outro fora; Assim eu posso analisar  o processamento de cada iteração e o resultado final;

 &gt; Eu tenho dois tipos de informação no console do 'Browser', a análise dos tipos com 'typeof item' e a contagem de quantos elementos do tipo 'Boolean' tem nesta parte do array;

&gt; As iterações mostraram o seguinte: 0 - 1 - 1 - 2

&gt; Como usei 'booleanTypes += 1' houve a soma dos tipos;

&gt; Finalizando com o último console.log:  'console.log(`Nesta amostra temos: ${booleanTypes} booleanos.`)'

Espero que ajude...Obrigado Roger!

![image](https://user-images.githubusercontent.com/44072541/116819729-aa1d3280-ab47-11eb-819a-135dafd50f67.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @marcosyoggy! Rumo à fluência! 🔥
