### ISSUE TITLE
Destructuring assignment

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6109]
### Etapa da aula

6

### Nome da aula

Correção dos exercícios da aula 04 da etapa 05 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370948

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Oi mestre,

Eu preciso de uma ajuda com o destructuring, não entendi por que é possível utiliza ló nesse caso. (minuto: 16:30)

Você tem algum vídeo ou issue que explique com mais detalhes a utilização do destructuring  ?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @dzpoke

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

## Você tem algum vídeo ou issue que explique com mais detalhes a utilização do destructuring ?

Destructuring em JavaScript é uma técnica que permite extrair dados de arrays ou objetos em variáveis individuais de forma mais simples e concisa.

Por exemplo, suponha que você tenha o seguinte objeto:

```javascript
const pessoa = {
  nome: 'João',
  idade: 30,
  cidade: 'São Paulo'
};
```

Para extrair os valores das propriedades `nome` e `idade` do objeto `pessoa` e armazená-los em variáveis separadas, você pode utilizar a sintaxe de destructuring da seguinte maneira:

```javascript
const { nome, idade } = pessoa;
```

Agora, as variáveis `nome` e `idade` contêm, respectivamente, os valores `'João'` e `30`.

Você também pode usar destructuring em arrays. Por exemplo, suponha que você tenha o seguinte array:

```javascript
const numeros = [1, 2, 3];
```

Para extrair os valores dos elementos do array e armazená-los em variáveis separadas, você pode usar a seguinte sintaxe de destructuring:

```javascript
const [primeiroNumero, segundoNumero, terceiroNumero] = numeros;
```

Agora, as variáveis `primeiroNumero`, `segundoNumero` e `terceiroNumero` contêm, respectivamente, os valores `1`, `2` e `3`.

A sintaxe geral do destructuring é a seguinte:

```javascript
// Para objetos
const { propriedade1, propriedade2 } = objeto;

// Para arrays
const [ elemento1, elemento2 ] = array;
```

Aqui, `propriedade1`, `propriedade2` e `elemento1`, `elemento2` são as variáveis que receberão os valores extraídos do objeto ou array, respectivamente. 

O destructuring também pode ser utilizado em funções para receber argumentos nomeados ou para definir valores padrão. Por exemplo:

```javascript
// Recebendo argumentos nomeados
function imprimeDados({ nome, idade }) {
  console.log(`Nome: ${nome}, Idade: ${idade}`);
}

imprimeDados({ nome: 'João', idade: 30 }); // Imprime "Nome: João, Idade: 30"

```

## Eu preciso de uma ajuda com o destructuring, não entendi por que é possível utiliza ló nesse caso. (minuto: 16:30)

Após a explicação acima, quero que se atente a essa parte específica do código mostrado no vídeo:

```js
egg.addEventListener('mousemove', event =>{
  console.log(event)
})
```

Ao executar o código acima e percorrer a área com o cursor do mouse, você verá as propriedades que `MouseEvent` possui, se você clicar na setinha à esquerda, esse conjunto de propriedades irá se expandir, e dentre elas, você verá que há as propriedades `offsetX` e `offsetY`. O que estava sendo feito anteriormente para acessar essas propriedades, era a sintaxe objeto.propriedade, respectivamente `event.offsetX` e `event.offsetY`. Mas agora, sabendo que o `MouseEvent` tem essas propriedades, você também pode acessá-las por meio do destructuring, e para isso, é necessário envolver entre colchetes os nomes das propriedades, esses colchetes com os nomes vão estar envolvidos em parênteses por se tratar de uma função. O código refatorado por completo, ficaria assim:

```Js
const showCoordinates = ({ offsetX, offsetY }) => {
  egg.textContent = `Eixo X: ${offsetX} | Eixo Y: ${offsetY}`
}
egg.addEventListener('mousemove', showCoordinates)
```

Dessa forma, a técnica de destructuring pode ser usada em JavaScript para simplificar o código, evitar a repetição que a sintaxe do objeto.propriedade causava e torná-lo bem mais legível! =)

Está ficando mais claro? Sinta-se livre para perguntar de novo caso não tenha entendido.

**Comment by MivlaM** [comment]
@dzpoke 

Complementando o que comentei anteriormente, o destructuring apresentado nessas aulas é só uma introdução à técnica, você ainda verá muito suas particularidades em relação ao destructuring conforme você for avançando no treinamento e ainda terá a oportunidade de praticar e aperfeiçoar muito o que foi mostrado =)

**Comment by dzpoke** [comment]
Salve @MivlaM, de boas ?

Pow mano, era isso que queria entender, li a DOC algumas vezes e entendi +/- como eu poderia aplicar.

Acho que agora com sua explicação ficou mais claro.

Eu consigo usar o destructuring aqui porque o que é retornado para mim no console é um objeto, e pelo fato de ser um objeto eu poderia pegar qualquer propriedade que ele tem abaixo, certo ?

![image](https://user-images.githubusercontent.com/60947491/221628660-bf621164-bc3d-434f-b13d-bbb0d5a600ad.png)

Se for isso mesmo, me tira mais uma dúvida, como eu consigo acessar as propriedades de MouseEvent sem eu fazer isso 

Se fosse dessa maneira aqui eu iria entender  porque ia ser igual ao exemplo que você deu

```
`
const { propriedade1, propriedade2 } = MouseEvent ;

`
```

Mas aqui em que momento eu sei que tenho a oportunidade de usar destructuring ?

```
const showCoordinates = ({ offsetX, offsetY }) => {
  egg.textContent = `Eixo X: ${offsetX} | Eixo Y: ${offsetY}`
}
egg.addEventListener('mousemove', showCoordinates)

```

**Comment by dzpoke** [comment]
@MivlaM 

Estou refazendo os exercícios  desse modulo e estou tentando entender como posso aplicar o destructuring.

Vou escrever aqui o que entendi me baseando na DOC blz, ae você vê se meu pensamento esta correto.

  - Faça com que o movimento do mouse dentro da div com a classe "egg" substitua
    o texto que ela tem por 
    "Eixo X: COORDENADA_EIXO_X | Eixo Y: COORDENADA_EIXO_Y".

Essa é minha resposta

```
egg.addEventListener('mousemove', ({offsetX, offsetY}) => {
    //console.log(event)
    egg.innerText = `Eixo X: ${offsetX} | Eixo Y: ${offsetY}`
})
```

Para chegar nesse resultado fui na DOC da MDN onde mostra a sintaxe e alguns exemplos, pelo que entendi é esse aqui que Roger usa.

DOC: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#try_it


```
Linha de exemplo da DOC

({ a, b } = obj);
```

Usando o exemplo acima pelo que entendi e como se eu estivesse fazendo isso aqui

`({offsetX, offsetY} =  mousemove)`

mousemove = objeto Mousemove (MouseEvent)

a, e =  São as propriedades desse objeto que estou acessando

-----------------------------------------------------------------------------------------------------------------------------------------

Pelo que eu entendi a pesar de não ter passado o objeto o JS faz isso internamente então no final é como se estivesse escrito dessa maneira.

```
egg.addEventListener('mousemove', ({offsetX, offsetY} = mousemove) => {
    //console.log(event)
    egg.innerText = `Eixo X: ${offsetX} | Eixo Y: ${offsetY}`
})

```
A omissão do objeto é como se eu estivesse utilizando o objeto do bloco de código  atual que nesse caso o único disponível é o mousemove.

Depois disso tudo, estou certo ou errado ?

**Comment by MivlaM** [comment]
Olá @dzpoke

É bem parecido mesmo com o que você demonstrou, o javascript faz esse processo por baixo dos panos quando está dentro de um listener de eventos, então não é bem necessário fazer da mesma forma da sintaxe como você mostrou (dentro de um listener), mas ela serve como uma didática. Isso não ocorre somente para o `mousemove`, você pode ver as propriedades dependendo do que for passado para o listener de eventos, veja abaixo com o `click`, por exemplo:

```js
button.addEventListener(('click', event) =>{
  egg.style.backgroundColor = 'yellow'
  console.log(event) // propriedades do click serão exibidas no console
})
```

> ## Mas aqui em que momento eu sei que tenho a oportunidade de usar destructuring ?

Diversas abordagens de quando você pode usar o destructuring serão apresentadas conforme você avança no treinamento, não se preocupe muito com isso agora, o que eu recomendaria para você agora, nesse ponto do treinamento, é entender a lógica da refatoração e também que é possível usar a abordagem do destructuring ao invés da sintaxe.objeto nessa situação. Mais para frente você verá mais situações em que o destructuring será empregado =)

Respondi a sua pergunta? Se restar qualquer dúvida é só avisar que te ajudarei =)

**Comment by dzpoke** [comment]
Obrigado! Vou seguir seu conselho e continuar o curso sem quebrar tanto a cabeça com isso.
