### ISSUE TITLE
Quiz-Interativo

### ISSUE THREAD

**Issue by Jonasjps** [roger-melo-treinamentos/curso-de-js-roger-melo#6114]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://jonasjps.github.io/Quiz-Interativo/

### Maiores dificuldades durante a implementação

1-Tive dificuldades em como seria a logica em usar os popups para mostra tanto o resultado como o gabarito e também com os botões dos popups.
2 - Também tive um pouco mais de dificuldade em refatorar o código, sem consultar as aulas anteriores como ajuda. 
3- Foi um pouco difícil utilizar  as class do bootstrap, por isso fiz uma mesclagem,  tanto do bootstrap com CSS.
4- Obter a resposta do usuário pelos inputs.

### Menores dificuldades durante a implementação

1- Não tive dificuldades em usar addEventListener, tanto eventos de click como de envio-(submit).
2 - Utilizando o querySelector(), para referenciar as tags HTML e class css.
3- Usar o método setInternal() para animar a pontuação do meu Quiz.
4- usar o Método setAttribute() para alternar os feedbacks para o usuário.

**Comment by MivlaM** [comment]
Olá @Jonasjps! =)

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos.

Eu procurei pelo seu nome na lista de alunos mas não encontrei. Com qual email vc se cadastrou no CJRM? Se não quiser falar por aqui, pode mandar um email para [oi@rogermelo.com.br](mailto:oi@rogermelo.com.br)

**Comment by Jonasjps** [comment]
Na verdade, estou fazendo o curso pelo link de colega meu que peguei emprestado!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
