### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#6119]
<h1>Callbacks</h1>

Callback é uma função passada a outra função como argumento, que é então invocada dentro da função externa para executar alguma ação ou rotina.
Exemplo:
```js
// declarando a função callback
const greeting = () => console.log('Olá')

// usando arrow function e passando uma função callback no parâmetro da myFunc
const myFunc = callback => callback()

myFunc(greeting)
```

<h1>forEach</h1>

forEach é um método que vai iterar por um array, ele recebe uma função callback como parâmetro e vai executar essa callback para todos os itens do array. O método forEach não retorna nada e também não pode ser parado, ele SEMPRE VAI ITERAR POR TODOS OS ITENS.

Essa função callback do forEach pode receber 3 parâmetros o item atual, o index e o array.

Irão ter casos que para manter a organização do código eu posso desacoplar a função callback do forEach e depois só referênciar ela dentro dos parênteses do forEach.

**Comment by MivlaM** [comment]
Excelente @MateusCavalheiro-prog, rumo à fluência! 🎯
