### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6124]
![image](https://user-images.githubusercontent.com/106329803/221894196-8d5cf0d5-4ab1-4dba-8d14-0b1c2376554d.png)
![image](https://user-images.githubusercontent.com/106329803/221895035-44430076-e930-4a82-84eb-d51e1087d568.png)
![image](https://user-images.githubusercontent.com/106329803/221895131-0f0bc44b-849a-4e4f-bdc9-8362beb7b6b1.png)
![image](https://user-images.githubusercontent.com/106329803/221895258-d8394396-e799-4f60-8874-e77012436daf.png)
![image](https://user-images.githubusercontent.com/106329803/221895349-d9498fdf-2ccb-4fac-b43b-f50b91e9ab51.png)

**Comment by MivlaM** [comment]
Excelente @rafael-rodrigues01, rumo à fluência! 🎯
