### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6136]
![image](https://user-images.githubusercontent.com/106329803/222469260-9b60a783-b506-4034-ada9-e9f2969566bb.png)
![image](https://user-images.githubusercontent.com/106329803/222469374-e36bf4a6-4931-4dff-9d7f-ce6cc6e6d21d.png)
![image](https://user-images.githubusercontent.com/106329803/222469428-b09645b3-f678-4b7a-87f3-f2ea3c353679.png)
![image](https://user-images.githubusercontent.com/106329803/222469470-af713cf7-d2b2-4c84-87a9-696ff5c9cec9.png)

**Comment by MivlaM** [comment]
Excelente @rafael-rodrigues01  , rumo à fluência! 🎯
