### ISSUE TITLE
Instalação npm netlify

### ISSUE THREAD

**Issue by Ale557333** [roger-melo-treinamentos/curso-de-js-roger-melo#6150]
### Etapa da aula

8

### Nome da aula

Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/986667

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa tarde Roger!

Estou tentando instalar o npm netfily para hospedar a primeira aplicação , porém estou com dificuldades. Já vi o tutorial que é passado na aula e procurei por outras soluções mas sem sucesso. Você consegue me ajudar? Essa é a mensagem que está aparecendo no meu terminal:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/71138743/223281428-7985813f-8a9e-491c-b134-108da874a4d2.png">

Muito obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
@Ale557333 Netlify está escrito errado. 

Está escrito "netfily", mas o correto é "netlify".

**Comment by Ale557333** [comment]
Oi Roger, desculpe pelo erro. Mas tentei novamente e mesmo assim sem sucesso. 
Eu não aprendi a mexer muito bem ainda no terminal, estou tentando ler e ver alguns videos sobre

<img width="762" alt="image" src="https://user-images.githubusercontent.com/71138743/223496657-8b9c9980-1f32-46e6-9f7a-9a5c321b2bcc.png">

**Comment by Roger-Melo** [comment]
@Ale557333 Podem ser várias coisas em relação ao seu sistema operacional e o CLI do Netlify. Vc pode dar uma olhada [aqui](https://github.com/netlify/cli/issues/3870#issuecomment-1018483719) para ver se resolve. 

Porém, não é necessário usar a CLI do Netlify pra fazer o deploy. Nos próximos vídeos da playlist é mostrado como fazer o deploy via arrasta e solta e via Git =)

**Comment by Ale557333** [comment]
Opa deu certinho Roger! Segue para você visualizar:
https://rad-alpaca-58f33c.netlify.app/

Fiz também um Readme no meu perfil, se você puder dar uma olhadinha quando puder:
https://github.com/Ale557333/interactive-quiz

Obrigado por tudo!

**Comment by Roger-Melo** [comment]
@Ale557333 ficou bem legal, parabéns =)

No que precisar, pode contar comigo para te apoiar na jornada =D

**Comment by Ale557333** [comment]
Muito obrigado mais uma vez Roger! Pode deixar!!
