### ISSUE TITLE
Resumo da Aula Variáveis e escopo de bloco - Aula 02-02 da etapa 04

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#616]
O que é escopo? É a área em que o valor de uma variável está disponível para utilizarmos. Quando criamos uma variável na raiz do documento, ou seja, fora de um bloco de código, essa variável terá escopo global, logo ela poderá ser acessada em qualquer lugar desse arquivo, dentro ou fora de qualquer bloco de código. E já que podemos acessá-la de qualquer parte do documento, significa que podemos acessá-la para exibir seu valor ou até reatribuir este valor dentro de um bloco de código. Então se criamos uma variável no escopo global e quisermos alterar seu valor em um bloco de código, isto será possível. Por exemplo:

```jsx
let age = 38;

if (true) {
	age = 48;

	console.log(`Dentro do 1º bloco de código: ${age}`);
	// 48
}

console.log(`Escopo global: ${age}`);
// 48
```

Se tentarmos recriar uma variável dentro do mesmo escopo, será retornada uma mensagem de erro, dizendo que a variável já foi declarada. Mas se criarmos novamente a variável, porém dentro de um escopo diferente, ou seja, dentro de um bloco de código por exemplo, veremos que ela irá existir como se fosse uma outra variável. Então as duas variáveis de mesmo nome poderão existir no mesmo código, porém cada uma em seu escopo. E assim como foram declaradas em escopos diferentes, ao serem chamadas, cada uma terá o valor que foi definido no escopo em que se encontram. Então se eu tenho uma variável no escopo global com um valor, e uma outra variável criada de mesmo nome em um outro escopo, num bloco de código por exemplo, o valor que será retornado será de acordo com o escopo em que foi chamada. Se chamada no escopo global, será retornado o valor declarado no escopo global. Se chamada no bloco de código, será retornado o valor declarado no bloco de código. Lembrando que se a variável tiver sido declarada somente em escopo global, se chamada dentro de um bloco de código, será retornado o valor declarado no escopo global.

```jsx
let age = 38;

if (true) {
	let age = 48;

	console.log(`Dentro do 1º bloco de código: ${age}`);
	// 48
}

console.log(`Escopo global: ${age}`);
// 38
```

Quando uma variável é criada dentro de um bloco de código, ela só estará acessível dentro deste bloco de código. E isso faz com que ela seja uma variável de escopo local, ou seja, está disponível para ser utilizada somente deste bloco, e caso seja chamada em escopo global, nada será retornado.

E se tivermos blocos de código aninhados? E se tivermos um bloco de código *if* dentro do nosso primeiro bloco de código? Caso utilizemos uma variável já declarada anteriormente, será utilizado o valor da mais próxima, no caso da primeira acima de onde foi chamada. Caso a variável seja recriada, este será o valor utilizado.

```jsx
let age = 38;

if (true) {
	let age = 48;
	
	let name = 'Ricardo';

	console.log(`Dentro do 1º bloco de código: ${age} ${name}`);
	// Dentro do 1º bloco de código: 48 Ricardo

	if (true) {
		let age = 58;
		
		console.log(`Dentro do 2º bloco de código: ${age} ${name}`);
		// Dentro do 2º bloco de código: 58 Ricardo
	}
}

console.log(`Escopo global: ${age}`);
// Escopo global: 38
```

Ao utilizar *let* e *const* para criar variáveis, os escopos são respeitados. Mas se utilizarmos a forma antiga, com o *var*, os escopos não são respeitados, e mesmo que uma variável tenha sido criada dentro de um bloco de código, ela poderá ser chamada num escopo global. E uma das vantagens de *let* e *const* é exatamente o escopo de bloco.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência! 🔥
