### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-06

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6170]
* var: Não é mais utilizando
 
* let:  Permite que você declare variáveis limitando seu escopo no bloco, instrução, ou em uma expressão na qual ela é usada. Isto quer dizer que se variáveis declaradas dentro de blocos internos de função, são vinculadas no escopo da função, não no bloco no qual elas são declaradas.(fora do bloco de função)

```
let age =31
let currentYear = 2019

console.log(agem currentYear)
```

* const: O valor de uma constante não pode ser alterado por uma atribuição, e ela não pode ser redeclarada.

```
const points =100
points =101  // Erro ao redeclarar o valor 

console.log(points)
```

**Comment by MivlaM** [comment]
Excelente @dzpoke rumo à fluência! 🎯
