### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by dev-pedro** [roger-melo-treinamentos/curso-de-js-roger-melo#6175]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Sim

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/dev-pedro/quiz-interativo

### Maiores dificuldades durante a implementação

Tive dificulade em manipular os eventos de formulários, manipular funções de callback e também na hora de manipular os elementos html

### Menores dificuldades durante a implementação

Utilizar os metodos forEach ficaram mais fáceis depois de algumas aulas

**Comment by MivlaM** [comment]
Olá @dev-pedro.

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Mas antes disso, verifiquei a sua aplicação e identifiquei que alguns critérios para que a análise seja feita estão em falta.

O critério é o seguinte:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas da construção da aplicação.

No trecho de código abaixo, você usou o javascript do bootstrap.

```HTML
<script>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
    />
</script>
```

Em nenhum momento do treinamento foi pedido para usar algo que não fosse JS puro na aplicação. Os critérios para análise do quiz devem ser seguidos, libs são ferramentas adicionais, e essas ferramentas não devem ser adicionadas agora. Foi pedido no [enunciado do exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js#L12) e também descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação seja feita apenas com o que você viu nas aulas até aqui.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Há um outro critério em falta:

## Critério 3: A aplicação só deve conter funcionalidades da linguagem que você viu no CJRM até o ponto que você está no treinamento;

Na sua aplicação, você usou funcionalidades da linguagem que ainda não foram apresentadas no CJRM no momento em que a aplicação deve ser enviada.

Ao longo do seu código, houveram algumas funcionalidades adicionais, como os trechos de código envolvendo JSON, a funcionalidade de mostrar a mensagem conforme a pontuação, a animação da pontuação final e a funcionalidade de subir a tela são apresentadas após a aula que foi solicitada para você enviar o quiz, ou seja, na teoria, esses trechos de código serão adicionados na sua aplicação após você ter passado pela análise aqui, não antes. Para o `Quiz interativo`, o ideal é que você envie a aplicação antes de assistir a aula "Exibindo a pontuação - Aula 02-01", da etapa 07. Contudo, tudo isso é muito interessante que você tenha feito, mas novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, notavelmente até a última aula de construção do quiz antes da demanda para enviar a sua aplicação para análise. O que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

Novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui.

Novamente, acredito que é muito interessante que você tenha feito funcionar por uma abordagem diferente usando outras funcionalidades, mas no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação. Nada mais ou menos que isso =)

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by dev-pedro** [comment]
Olá Maykell, obrigado pelas dicas vou rever e refazer o código e reenvio pra você, valeu.

**Comment by dev-pedro** [comment]
Só em relação ao bootstrap não entendo por que não pode usar pois o que vai ser analizado é so o javascript mesmo?

**Comment by dev-pedro** [comment]
Eu mudei o código javascript se puder me dar um feedback eu agradeço. Bom dia.
https://github.com/dev-pedro/quiz-interativo

**Comment by MivlaM** [comment]
Olá @dev-pedro

Boa tarde,

Em relação à estilização, o uso do Bootstrap (ou qualquer lib CSS) é opcional. O que o Roger mostra nas aulas é o Bootstrap utilizado unicamente para estilizar o CSS das aplicações, esse você tem a liberdade de escolher como usar, portanto, não é nenhum problema se você usou o CSS do Bootstrap na sua aplicação. Porém, nunca é usado o Javascript do Bootstrap (ou de alguma outra lib) em nenhum momento. Em todas as aulas, o que é mostrado é apenas o Javascript puro. O motivo desse critério é que todo o código Javascript da aplicação deve ser escrito pelo aluno, não se tem acesso ao código da lib, então não tem como analisar e refatorar um código que não se tem acesso. 

Eu dei uma olhada no seu código aqui, em relação ao critério 2, você precisa remover essas linhas referentes ao uso da lib da sua aplicação:
```HTML
<script>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
    />
</script>
```

Para o critério 3, estão irregulares três funções: `showFinalScore`, `animateFinalScore` e `showBruxoOuTrouxa`. Compreendo que algumas dessas funcionalidades são acrescentadas nas aulas seguintes após a demanda para enviar o quiz, mas de acordo com o critério, a aplicação deve conter apenas as funcionalidades exibidas da primeira aula que começa o desenvolvimento do quiz  até a aula `"Exibindo a pontuação - Aula 02-01", da etapa 07`. Eu recomendo que você revise essa etapa para conseguir visualizar melhor o que está sendo demandado.

Sinta-se livre para comentar caso tenha restado alguma dúvida.

Fico no aguardo =)

**Comment by dev-pedro** [comment]
Olá @MivlaM, fiz algumas mudanças ficaria grato se você revisasse, meu cabeçalho html esta desta forma sem o script.
Também removi as funcões `showFinalScore`, `animateFinalScore` e `showBruxoOuTrouxa`

```html
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
    />
    <link rel="stylesheet" href="style.css" />
    <title>Quiz</title>
  </head>
```
https://github.com/dev-pedro/quiz-interativo

Fico no aguardo da sua avaliação.

**Comment by MivlaM** [comment]
Olá @dev-pedro

Boa tarde,

O cabeçalho HTML está ok. E o código, no geral, está 95% aprovado. Só tem mais um último detalhezinho antes de poder aprovar em 100% a sua aplicação. Na última função do seu código, em `onsubmitAnswers`, o `finalScoreContainer` que você usou como solução de exibição dos pontos que vc implementou está como a mostrada em aulas posteriores ao aviso solicitando para enviar o quiz (em relação a posição, a animação, as características estéticas no geral). Estou lhe passando essa observação, para que possa fazer uma análise precisa posteriormente, pois uma solução como a mostrada em aulas, você pode assistir as aulas que terá uma explicação ainda mais aprofundada sobre cada função que for introduzida lá. Se você quiser mesmo assim manter a ideia, você pode fazer com que o local de exibição da pontuação apareça no centro da aplicação, em baixo, por popup, ou em algum outro lugar. Apenas mais esse detalhe e poderei aprovar a sua aplicação para análise =)

**Comment by dev-pedro** [comment]
@MivlaM valeu pelas dicas e desculpe todo o encomodo, uma pergunta eu posso usar um `alert`para exibir a pontuação ?

**Comment by MivlaM** [comment]
Olá @dev-pedro

Sim você pode usar um alert. Estou passando para dizer que a issue foi visualizada e aprovada e em até 10 dias úteis a análise será feita =)

**Comment by dev-pedro** [comment]
Muito obrigado 👍🏽

**Comment by MivlaM** [comment]
Olá @dev-pedro

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Tive dificulade em manipular os eventos de formulários, manipular funções de callback e também na hora de manipular os elementos html

Mesmo essas dificuldades relatadas, você conseguiu!

Vou fazer algumas observações e falar mais sobre elas ao decorrer da análise.

---

## Boas decisóes

Uma boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

Você inseriu porcentagem na mensagem dos pontos. Isso é bom pq traz mais clareza do progresso do usuário no quiz em relação a pontuação máxima.

A estilização do seu quiz ficou muito legal! =)

---

Vou deixar abaixo algumas observações sobre sua aplicação

---

## Ponto exato do envio de cada aplicação

Entendo que já foi mencionado nas mensagens que trocamos antes de aprovar a sua aplicação, porém vou reforçar aqui novamente para que não ocorra de novo na próxima vez. É muito importante que você siga à risca o que está escrito no email enviado para a análise de aplicações, esse email é que vai te orientar como tudo deve ser feito para que você tenha o melhor aproveitamento possível na hora de escrever o código, enviar a sua aplicação para a análise e receber o feedback. Alguns trechos de código que vou apresentar aqui, não serão tão eficazes como o planejado, pois a aplicação foi enviada depois de você já ter assistido algumas aulas depois da aula que foi recomendada o envio da aplicação.

Segue abaixo uma captura de tela de um trecho da mensagem do email:

![imgg](https://user-images.githubusercontent.com/82729897/226719656-f593c881-d81b-41a3-94ef-90fc553a2b5c.png)

Por favor, atente-se para cumprir todos os critérios para que possamos ter o melhor tipo de análise na próxima aplicação =)

---

## Comentários no código

No index.html e no script.js há alguns trechos de código comentados, não é uma regra, mas evite comentários.

Comentários podem mentir se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Alternativas desmarcadas por padrão

Antes do usuário selecionar as alternativas, uma sugestão é a de deixar a primeira alternativa de cada pergunta marcada por padrão. Para fazer isso, basta inserir o atributo checked no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal, mas acho que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

---

## Nomenclatura das variáveis

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a const `scoreScript` que você usou no código pode ter seu nome substituido por apenas `score`. O intuito aqui é fazer com que os nomes diminuam de comprimento e ao mesmo tempo mantenham o sentido original.

```js
// antes
let scoreScript = 0
```

```js
// depois
let score = 0
```

Por fim, você também pode renomear a const `divQuestion` para `questionsContainer`, a ideia aqui é caso futuramente o elemento mudar para algo que não seja uma div, por exemplo, a const não precisará ser renomeada, pois a nomenclatura da const estará escrita de forma mais abrangente.

```js
// antes
const divQuestion = document.querySelector('.questions')
```

```js
// depois
const questionsContainer = document.querySelector('.questions')
```

---

## Const ao invés de let

Prefira usar const no lugar de let, quando possível.

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt). Sabendo disso, prefira seguir essa boa prática e fazer com que `correctAnswers`, `percentualAsked` e `wasAnswered` sejam consts. 

```js
// antes
let correctAnswers = ['2', '1', '0', '2', '0', '2', '1', '1', '3', '1']
let percentualAsked = Math.round(100 / correctAnswers.length)
let wasAnswered = false
```

```js
// depois
const correctAnswers = ['2', '1', '0', '2', '0', '2', '1', '1', '3', '1']
const percentualAsked = Math.round(100 / correctAnswers.length)
const wasAnswered = false
```

---

## Posicionamento

Ao longo do seu código, é possível observar que algumas consts que foram declaradas no escopo global são utilizadas apenas em algumas funções e em trechos específicos que não necessariamente necessitam que essas consts estejam num escopo tão amplo. A sugestão aqui, é que você mova esses trechos de código para as funções que os utilizam, a vantagem disso, é manter um código mais conciso e focado em deixar cada função mais organizada e específica. Sabendo disso, você pode mover `percentualAsked`, `wasAnswered` para dentro da função `calculateUserScore` e `templateHTML` para dentro da função `insertAsketsOnIndexHTML`. Ficaria assim:

```js
// antes
const percentualAsked = Math.round(100 / correctAnswers.length)
const wasAnswered = false
let templateHTML = ''
```

```js
// depois
function insertAsketsOnIndexHTML (questions = {}) {
  let asksLabel = ''
  let templateHTML = ''
  // ...
}

const calculateUserScore = userAnswers => {
  const percentualAsked = Math.round(100 / correctAnswers.length)
  const wasAnswered = false
  // ...
}
```

Também vale mencionar que a invocação de `insertAsketsOnIndexHTML` pode ser posicionada junto das outras invocações no final do código, estabelecendo assim uma padronização de declarar as funções e só depois de todas já terem sido declaradas, começar as invocações. Isso faz com que o seu código se torne mais legível e mais fácil de compreender.

```js
// antes
function insertAsketsOnIndexHTML (questions = {}) {
  // ...
}
insertAsketsOnIndexHTML(questions)
```

```js
// depois
form.addEventListener('submit', onsubmitAnswers)
insertAsketsOnIndexHTML(questions)
```

---

## getUserAswers

Feito esses ajustes, há algumas coisas que podemos refatorar nessa função também. Primeiramente, o nome que você escolheu é eficiente em descrever o que a função está fazendo, porém, há um pequeno erro ortográfico na palavra `answers`, nada muito prejudicial, mas acredito que vale a pena mencionar. O nome após a correção será `getUserAnswers`:

```js
//antes
const getUserAswers = () => {
  // ...
}
```

```js
//depois
const getUserAnswers = () => {
  // ...
}
```

Sabendo disso, podemos fazer uma abordagem interessante aqui:

```js
const getUserAnswers = () => {
  let userAnswers = []
  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })
  return userAnswers
}
```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Lembre-se da ideia de que quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputQuestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. A cada execução desse callback, o valor que a função está retornando vai ser inserido nesse novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, a `getUserAnswers` já vai estar funcionando normalmente e você pode manter a const `userAnswers` armazenando sua invocação:

```js
const onsubmitAnswers = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  alert(`Você acertou ${score}% do Quiz.`)
}
```

---

## calculateUserScore

Para essa função, há alguns detalhes que podemos mencionar:

```js
const calculateUserScore = userAnswers => {
  const percentualAsked = Math.round(100 / correctAnswers.length)
  const wasAnswered = false

  if (!wasAnswered) {
    userAnswers.forEach((userAnswer, index) => {
      const isUserAnswerCorrect = userAnswer === correctAnswers[index]
      if (isUserAnswerCorrect) {
        score += percentualAsked
      }
    })
  }
}
```

Primeiramente, a const `wasAnswered` está recebendo false, porém, dentro do condicional if, ela está sendo usada quando seu valor for true. Nesse caso, como o valor sempre vai ser true quando o usuário já ter escolhido as alternativas, não é necessário que essa const `wasAnswered` exista. O código pode continuar funcionando normalmente ao removê-la do código:

```js
// antes
const calculateUserScore = userAnswers => {
  const percentualAsked = Math.round(100 / correctAnswers.length)
  const wasAnswered = false

  if (!wasAnswered) {
    userAnswers.forEach((userAnswer, index) => {
      const isUserAnswerCorrect = userAnswer === correctAnswers[index]
      if (isUserAnswerCorrect) {
        score += percentualAsked
      }
    })
  }
}
```

```js
// depois
const calculateUserScore = userAnswers => {
  const percentualAsked = Math.round(100 / correctAnswers.length)

  userAnswers.forEach((userAnswer, index) => {
    const isUserAnswerCorrect = userAnswer === correctAnswers[index]
      if (isUserAnswerCorrect) {
        score += percentualAsked
      }
  })
}
```

Agora, há um outro detalhe, está acontecendo uma adição desnecessária na pontuação ao enviar a aplicação. Não sei se você percebeu e os detalhes específicos desse tipo de problema serão mostrados em uma aula adiante, porém, vou fazer uma síntese aqui do que está acontecendo. Não é necessário que score receba o valor de `percentualAsked` somado com o que já tinha, basta fazer com que `score` receba o valor determinado para cada pergunta, no caso da sua aplicação seria 10. Mas, há uma outra refatoração que podemos fazer nessa função, e dessa forma `percentualAsked` também não é necessária para o funcionamento da sua aplicação.

E como isso é feito? Bem, toda a ideia da função `calculateUserScore`é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Você pode criar uma função própria para obter a pontuação, essa função se chamará `getScore`, vamos declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Por esse momento, vamos manter uma lógica similar a que você usou dentro dessa nova função:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer, index) => {
    const correctAnswer = userAnswer === correctAnswers[index]

    if (correctAnswer){
      score += 10
    }
  })
}
```

Depois, a let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 10 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const correctAnswer = userAnswer === correctAnswers[index]

    if (correctAnswer){
      return accumulator + 10
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 25, que na primeira execução será (0 + 10). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 10, na segunda execução o parâmetro `accumulator` estará armazenando 10 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 10 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 10 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 10 : accumulator, 0)
```

Por fim, você pode invocar a função `getScore()` dentro da função `onsubmitAnswers` recebendo o array armazenado por `userAnswers` como argumento. A função atualizada ficaria assim:

```js
const onsubmitAnswers = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  alert(`Você acertou ${score}% do Quiz.`)
}
```

---

## insertAsketsOnIndexHTML

Nessa função, para que ela esteja padronizada como as demais, é interessante que ela também seja uma arrow function. Um código que segue um padrão e permanece nele por toda a aplicação, é um código muito mais fácil de entender, além de ser muito mais limpo e organizado. Além disso, para aprimorar ainda mais os benefícios recém mencionados, o nome dessa função pode causar uma certa confusão ao lê-lo, se fizer sentido para você, se essa função é responsável por inserir as questões que vão ser utilizadas no quiz, essa função pode ter seu nome pode ser simplificado para `insertQuestions`. Ficaria assim:

```Js
// antes
function insertAsketsOnIndexHTML (questions = {}) {
  // ...
}
```

```js
// depois
const insertQuestions = (questions = {}) => {
  // ...
}
```

Um outro detalhe que vale a pena mencionar é em relação a nomenclatura de `templateHTML`, acredito que `HTMLtemplate` seja mais ortograficamente preciso, claro que isso é apenas uma opinião pessoal, mas se você achar interessante, sinta-se livre para optar por essa possibilidade também:

```Js
// antes
const insertQuestions = (questions = {}) => {
  let templateHTML = ''
  // ...
}
```

```js
// depois
const insertQuestions = (questions = {}) => {
  let HTMLtemplate = ''
  // ...
}
```

Uma outra observação, é que você pode deixar o código mais fácil de entender ao indentar também a marcação html dentro da template string que `asksLabel` está armazenando. Ficaria assim:

```js
// antes
options.forEach((option, index) => {
  asksLabel += `<div class="form-check my-2 text-black-50">
                    <label class="form-check-label">
                    <input class="pergunta" type="radio" name="inputQuestion${number}" value="${index}" />
                    ${option}
                    </label>
                    </div>`
})
```

```js
// depois
options.forEach((option, index) => {
  asksLabel += `<div class="form-check my-2 text-black-50">
                    <label class="form-check-label">
                      <input class="pergunta" type="radio" name="inputQuestion${number}" value="${index}" />
                      ${option}
                    </label>
                </div>`
})
```

Por fim, há uma refatoração completa que é possível ser feita nessa função para não precisar mais do forEach aninhado e das reatribuição em lets. Para isso, a ideia é que haja duas funções separadas, uma para obter o markup das opções e uma outra para inserir as perguntas. De início, vamos começar pela função para obter o markup. Vamos declarar uma função chamada `getOptionsMarkup` que irá receber number e options como parâmetro, ambos virão do objeto que será usado em sua invocação. Após isso, vamos encadear em options o método reduce com os parâmetros `acc`, `option` e `index`. De início, ficaria mais ou menos assim: 


```js
const getOptionsMarkup = ({ number, options }) => options.reduce((acc, option, index) =>
  // ...
```

Tudo certo até aqui? Se sim, vamos prosseguir!

Feito isso, agora vamos inserir o template HTML de forma bem semelhante a anterior, a única diferença é que vamos colocar o `acc` do reduce antes da abertura da primeira div, assim, cada pergunta terá o seu markup específico de acordo com o valor do `acc`. O segundo argumento será uma string vazia, pois o `acc` vai começar a valer a partir dela. A função completa ficaria assim: 

```js
const getOptionsMarkup = ({ number, options }) => options.reduce((acc, option, index) => `
  ${acc}<div class="form-check my-2 text-black-50">
    <label class="form-check-label">
      <input class="pergunta" type="radio" name="inputQuestion${number}" value="${index}" />
      ${option}
    </label>
  </div>`, '')
```

Agora, passando para a segunda função, vamos declarar uma função com o nome de `insertQuestions`, essa função vai ser responsável por inserir na aplicação, as questões armazenadas no array de objeto `questions`. Podemos reaproveitar boa parte do código anterior também, então essa função vai receber um parâmetro questions que vai armazenar, inicialmente, um objeto vazio.

```js
const insertQuestions = (questions = {}) => {
  // ...
}
```

Após isso, dentro dessa função, vamos criar uma const `markup` que será responsável para armazenar o array modificado de cada pergunta, para isso, vamos encadear o método map no `questions` que vai ser recebido como parâmetro, os valores do array que vão ser modificados são `number`, `title` e `options` e por isso, esses três serão passados como parâmetros do map e estarão entre chaves por se tratarem de propriedades de um objeto. Depois disso, o template será inserido de forma bem similar ao anterior, a diferença aqui, é que ao invés de utilizarmos a `asksLabel` para evitar a duplicação de alternativas, vamos invocar a função `getOptionsMarkup` com o número da questão e suas opções. Ficaria assim:

```Js
const insertQuestions = (questions = {}) => {
  const markup = questions.map(({ number, title, options }) => `
    <div class="my-5">
      <p class="lead font-weight-normal">${number}. ${title}</p>
      ${getOptionsMarkup({ number, options })}
    </div>`)

  questionsContainer.innerHTML = markup
  form.insertAdjacentElement('afterbegin', questionsContainer)
}
```

Maaaas, se você executar o código assim, vai ver que a função está gerando vírgulas na marcação HTML, elas estão aparecendo após as alternativas de cada pergunta. Para resolver esse problema, vou te dar um pequeno spoiler de um método que será melhor apresentado nas próximas etapas do treinamento, se trata do método join. Para resolver esse comportamento indesejado, a idéia é encadear no map, a invocação do método join. O join é um método de array que vai juntar todos os itens do array em uma string e como seu argumento, você pode usar um separador entre esses itens, o separador seria uma string em branco, pois você não quer separar os itens e sim, apenas evitar com que as vírgulas sejam retornadas:

```js
const insertQuestions = (questions = {}) => {
  const markup = questions.map(({ number, title, options }) => `
    <div class="my-5">
      <p class="lead font-weight-normal">${number}. ${title}</p>
      ${getOptionsMarkup({ number, options })}
    </div>`).join('')

  questionsContainer.innerHTML = markup
  form.insertAdjacentElement('afterbegin', questionsContainer)
}
```

Feito isso, ambas funções estarão funcionando perfeitamente bem agora =). Segue abaixo uma comparação de antes e depois com as funções juntas e completamente refatoradas:

```js
// antes
const insertQuestions = (questions = {}) => {
  let HTMLtemplate = ''
  let asksLabel = ''
  
  questions.forEach(({ number, title, options }) => {
    options.forEach((option, index) => {
      asksLabel += `<div class="form-check my-2 text-black-50">
                        <label class="form-check-label">
                          <input class="pergunta" type="radio" name="inputQuestion${number}" value="${index}" />
                          ${option}
                        </label>
                    </div>`
    })
    HTMLtemplate += `<div class="my-5">
                      <p class="lead font-weight-normal">
                      ${number}. ${title}
                      </p>
                      ${asksLabel}
                    </div>`
    asksLabel = ''
  })

  questionsContainer.innerHTML = HTMLtemplate
  form.insertAdjacentElement('afterbegin', questionsContainer)
}
```

```js
// depois
const getOptionsMarkup = ({ number, options }) => options.reduce((acc, option, index) => `
  ${acc}<div class="form-check my-2 text-black-50">
    <label class="form-check-label">
      <input class="pergunta" type="radio" name="inputQuestion${number}" value="${index}" />
      ${option}
    </label>
  </div>`, '')

const insertQuestions = (questions = {}) => {
  const markup = questions.map(({ number, title, options }) => `
    <div class="my-5">
      <p class="lead font-weight-normal">${number}. ${title}</p>
      ${getOptionsMarkup({ number, options })}
    </div>`).join('')

  questionsContainer.innerHTML = markup
  form.insertAdjacentElement('afterbegin', questionsContainer)
}
```

---

## onsubmitAnswers

A sugestão aqui é criarmos uma nova função responsável unicamente pela manipulação de DOM e invocarmos ela nessa função também. Atualmente, a função `onsubmitAnswers` também é responsável por executar o alert, e para deixar mais claro o papel de apenas passar informações para a frente, podemos criar uma função `showScore` que vai ser unicamente responsável para executar esse alert e invocar essa função em `onsubmitAnswers`. Assim, além de facilitar o fluxo de leitura, você separa mais as responsabilidades, agora que não tem manipulação de DOM em `onsubmitAnswers`, essa função agora é apenas responsável por passar informações para frente, para que outras partes da aplicação executem o que precisa ser executado, como por exemplo, exibir o score. Ficaria assim:

```js
// antes
const onsubmitAnswers = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  alert(`Você acertou ${score}% do Quiz.`)
}
```

```js
// depois
const showScore = score => alert(`Você acertou ${score}% do Quiz.`)

const onsubmitAnswers = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  showScore(score)
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by dev-pedro** [comment]
Desculpe a demora esta muito corrido esses dias, muito obrigado pelas dicas irei aplica-las. Muito obrigado.
