### ISSUE TITLE
Dúvida com relação aos primeiros exercícios envolvendo Funções.

### ISSUE THREAD

**Issue by PauloRDev** [roger-melo-treinamentos/curso-de-js-roger-melo#6187]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370910

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Estou com dificuldade de entender a resolução abaixo,
por exemplo temos 2 arrays vazios.
Um como parâmetro da função e outro para receber os itens de millennialWords.

mas como padrão eles estão vazios, então como é 'pego' o valor de millennialWords, para o newArray?
O que mais causa confusão é o fato de o [i] ser em array[i] e porque não millennialWords[i] ?

ou, o array como parâmetro está declarado como tipo de dado, fazendo referência direta a millennialWords, e conforme o for loop percorre ele está por baixo dos panos percorrendo o millennialWords?

```js
const millennialWords = ['lol', 'yolo', 'troll', 'stalkear', 'selfie', 'influencer', 'crush', 'fitness', 'hater', 'bae', 'random', 'kawaii', 'outfit', 'mood', 'fail']

const transformToUpperCase = function (array = []) {
  let newArray = []
  
  for (let i = 0; i < array.length; i++) {
    const wordInUpperCase = array[i].toUpperCase()

    newArray.push(wordInUpperCase)
  }

  return newArray
}

const millennialWordsInUpperCase = transformToUpperCase(millennialWords)

log (millennialWordsInUpperCase)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
> ### por exemplo temos 2 arrays vazios

@PauloRDev seu exemplo não tem 2 arrays vazios. 

O parâmetro `array` só iria receber aquele array vazio se a função `transformToUpperCase` fosse invocada sem receber argumento (assim: `transformToUpperCase()`). Não é o caso. 

Você invocou `transformToUpperCase(millennialWords)`, então o parâmetro `array` recebeu o array `millennialWords`.

---

> ### O que mais causa confusão é o fato de o [i] ser em array[i] e porque não millennialWords[i]?

Você pode fazer `millennialWords[i]`, mas aí a sua função só vai funcionar para o array `millennialWords`.

Quando vc faz a função receber um array de strings como argumento/parâmetro, a função vai funcionar pra qualquer array de strings. 

Se vc tiver 2 arrays diferentes, ela funciona pros dois:

```javascript
const millennialWords = ['lol', 'yolo', 'troll']
const arr2 = ['a', 'b', 'c']

const transformToUpperCase = function (array = []) {
  let newArray = []

  for (let i = 0; i < array.length; i++) {
    const wordInUpperCase = array[i].toUpperCase()

    newArray.push(wordInUpperCase)
  }

  return newArray
}

// 👇🏻 funciona para qualquer array de string que vc passe como argumento
const millennialWordsInUpperCase = transformToUpperCase(millennialWords)
const arr2WordsInUpperCase = transformToUpperCase(arr2)
```

A função acima pode ser reutilizada pra qualquer array de string. 

Já a função abaixo, só vai funcionar para o array `millennialWords`, pq ao invés de usar o array que foi recebido no parâmetro, `millennialWords[i]` está sendo usado. 

```javascript
const millennialWords = ['lol', 'yolo', 'troll']
const arr2 = ['a', 'b', 'c']

const transformToUpperCase = function (array = []) {
  let newArray = []

  for (let i = 0; i < array.length; i++) {
    const wordInUpperCase = millennialWords[i].toUpperCase()

    newArray.push(wordInUpperCase)
  }

  return newArray
}

const millennialWordsInUpperCase = transformToUpperCase(millennialWords)
const arr2WordsInUpperCase = transformToUpperCase(arr2)
```

**Comment by Roger-Melo** [comment]
@PauloRDev cola o código no seu editor e exiba as últimas duas consts no console.

**Comment by PauloRDev** [comment]
Explicação excelente, agora só realizar os exercícios novamente até não precisar acompanhar a revisão.

**Comment by Roger-Melo** [comment]
Boa! =)
