### ISSUE TITLE
Funcao de callback

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6191]
### Etapa da aula

3

### Nome da aula

Utilizando callbacks e exercícios - Aula 02-05

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370914

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Minuto da aula 10:45

Oi,

Preciso de uma ajuda para entender melhor a estrutura de uma função de callback

* Não entendi pq nessa parte dentro do bloco da função tenho que executar  "callback()"

```
const funcExterna = callback => {
  callback()
}

```
* Não entendi pq nessa parte tenho que digitar meu nome de maneira manual, o certo não seria invocar a função e digitar o nome que eu quero apareça ?

```
const funcMyName = name => {
  return console.log('Diego')
}

```
* Na minha cabeça a resolução para esse exercício seria essa aqui, quando executo o código da erro mas espero que entendam 
a minha ideia 

```
const funcExterna = callback => {

  const funcMyName = name => {
    return console.log(name)
  }
callback(funcMyName())
}

funcExterna(funcMyName('Diego'))
```
A resolução tendo como base a resolução dessa aula foi isso aqui

```
const funcExterna = callback => {

     const funcMyName = name => {
       return console.log(name)
   }
callback()
}


funcExterna(funcMyName('Diego'))
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @dzpoke

Callback costuma ter esse impacto inicial na mente, isso é comum até compreender como funciona.

Na issue abaixo tem um passo a passo completo, acredito que ao fazê-lo, ficará mais claro a compreensão da estrutura dos callbacks. Recomendo que você o faça e quando terminar, me avisa por aqui se compreendeu e se permanece com dúvida.

- [Passo a passo para entender callbacks](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574)

**Comment by dzpoke** [comment]
@MivlaM 

Vou dar uma olhada hoje.  Depois que eu deu uma lida e testar volto a atualizar esse comentário.

**Comment by MivlaM** [comment]
Bem, vou fechar essa issue aqui, mas se precisar de mais ajuda em relação a esse ou a outros assuntos, sinta-se livre para abrir uma nova =)
