### ISSUE TITLE
Resumo da Aula  Numbers - Aula 02-05, etapa 01.

### ISSUE THREAD

**Issue by olucasbrum** [roger-melo-treinamentos/curso-de-js-roger-melo#6196]
# <p align="center">Numbers</p>

Number é um tipo de dado usado para representar valores numéricos. Eles podem ser escritos como números inteiros ou decimais.

```js
let integer = 42; // an integer
let decimal = 3.14; // a decimal
let negative = -10; // a negative number
```

### Exemplo de ordem de precedência:

1.  Parênteses;
2.  Expoentes ou radiciação;
3.  Multiplicação e divisão;
4.  Adição e subtração;

```js
let operation = 10 * (20 - 10) ** 6;

console.log(operation); // return 10000000
```

### Operadores de incremento e decremento: 

```js 
let studyingDays = 10;

studyingDays++     // incremento (  + 1 )
studyingDays--     // decremento (  - 1 )
studyingDays += 1; // adição de atribuição
studyingDays -= 1; // subtração de atribuição
studyingDays *= 2; // multiplicação de atribuição
studyingDays /= 5; // divisão de atribuição
```

**Comment by MivlaM** [comment]
Excelente @olucasbrum rumo à fluência! 🎯
