### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6197]
Template string

As strings podem ser escritas com aspas simples, aspas duplas ou crases, ficando a critério do programador escolher a melhor opção. No entanto, para evitar conflitos de aspas, se desejarmos incluir aspas duplas no nosso texto, devemos escolher na abertura e fechamento da string aspas simples, crases ou barra invertida "escapada", a fim de evitar erros. Caso a frase contenha aspas simples, então a abertura e fechamento da string terá que ser feita com aspas duplas, crases ou escapada.

Exemplo:
- console.log('Você manja do filme "As Branquelas"?') 
Aqui, "As Branquelas" está entre aspas duplas e não gera erro

- console.log('Você manja do filme \'As Branquelas\'?') 
Aqui, foi escolhido usar aspas simples, o escape com barra invertida foi usado para não gerar erros.

- Existe também a possibilidade de usar uma template string:
const movie = 'As Branquelas'
console.log( ` Você manja do filme "${movie}" ? ` ) 

É recomendado usar template string: 
Quando precisar usar variáveis dentro do texto. 
Quando o texto contém aspas duplas ou simples.
Quando o texto comtém HTML.
Quando o texto for complexo.

**Comment by MivlaM** [comment]
Excelente @dev-jefferson-lopes rumo à fluência! 🎯
