### ISSUE TITLE
Etapa 08, Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by DavidLSousa** [roger-melo-treinamentos/curso-de-js-roger-melo#62]
Boa tarde prof!
Quando estava fazendo o contador no Exercício 20, enquanto testava o que estava fazendo tive problema com mais de um click no botão de iniciar o contador. Quando clicado repetidas vezes o contador começava a aumentar sua velocidade e o botão de parar não tinha mais efeito, ele ate chegava a diminuir a velocidade, mas o contador não parava mais.

Eu pensei na solução de add uma:
```js
let condition = true
```
Dentro do addEventListener do botão de iniciar, colocar o código dentro de um if pra só acontecer ao ser clicado pela primeira vez, por que antes de sair do bloco eu atribuo a let contition o valor false, assim mais de um click no botão de iniciar não teria nenhum efeito pra acelerar o contador e o botão de parar tbm continuou funcionando normalmente independente do numero de cliques. 

Dentro do adddEventListener do botão de parar, eu atribuo a let condition o valor true, que caso o usuário quera utilizar novamente o contador, ele volte funcionando normalmente

OBS: O código ja esta refatorado, pois assistir a correção para ver se seria resolvido, mas msm depois da correção o meu continuou com o mesmo problema, não sei se deixei passar algo da correção.

O código ficou assim:

```js
const counterContainer = document.querySelector('.counter-container')
const buttonInitCounter = document.querySelector('.button-init-counter')
const buttonStopCounter = document.querySelector('.button-stop-counter')

let timer = null
let condition = true

const incrementCounter = () => {
  const counter = Number(counterContainer.textContent)
  const incrementedCounter = counter + 0.1
  counterContainer.textContent = incrementedCounter.toFixed(1)
}

const stopCounter = () => {
  clearInterval(timer)
  counterContainer.textContent = 0
  condition = true
}

buttonInitCounter.addEventListener('click', () => {
  if (condition) {
    timer = setInterval(incrementCounter, 100)
  }

  condition = false
})

buttonStopCounter.addEventListener('click', stopCounter)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi David. 

Pode subir o projeto no GitHub e me enviar o link para eu testar aqui em minha máquina?

@DavidLSousa

**Comment by DavidLSousa** [comment]
https://github.com/DavidLSousa/Exerc-cio20_Contador.git

**Comment by Roger-Melo** [comment]
Oi David!

O contador está frenético assim porque no código abaixo,

```javascript
buttonInitCounter.addEventListener('click', () => {
  if (condition) {
    timer = setInterval(incrementCounter, 100)
  }
  condition = false
})
```

o 2º argumento da invocação do `setInterval` recebeu `100` milisegundos. Para executar a `incrementCounter` a cada segundo, é só inserir `1000` milisegundos, que equivalem à 1 segundo. Sacou a ideia?

Ah, não sei se foi intencional, mas você pode modificar o valor da `incrementedCounter` para um número inteiro, tirando o `0.`. Assim você exibe na tela apenas os segundos do contador.

Ficaria assim:

```javascript
const incrementedCounter = counter + 1
```

---

Sobre a declaração da `let condition = true`, "condition" é um nome que não expressa a intenção da variável existir.

Se quiser deixar o nome e valor da variável mais explícitos, você pode seguir os passos que recomendei [nessa issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/17). É uma orientação para resolver basicamente o mesmo problema que você descreveu. 

Depois de fazer os passos acima, me diga se o código funciona como o esperado =)

@DavidLSousa

**Comment by DavidLSousa** [comment]
Oi Roger!

Então, acho que eu não conseguir ser mt claro na minha duvida, eu vou atualizar o repositório do github e mando pra o sr dar uma olhada dnv.

@Roger-Melo

**Comment by DavidLSousa** [comment]
https://github.com/DavidLSousa/Exercicio20_Contador.git

Nesse link além da forma que eu resolvi o exercício tem mais outras 2 formas pra o sr olhar, eu deixei no uma delas descomentada, o sr pode testar um e descomentar o de cima para testar o outro.

O que eu tinha feito a principio foi intencional o intervalo de 100 milissegundos, eu tinha feito funcionar com o contador mudando a cada 1 segundo mas fiquei achando que ficou meio parado dps, as vzs dava a impressão que não estava funcionando, ai eu fiz ele atualizar a cada segundo e add um .toFixed(1), para não mostrar digitos demais na tela
```js
const incrementCounter = () => {
  const counter = Number(counterContainer.textContent)
  const incrementedCounter = counter + 0.1
  counterContainer.textContent = incrementedCounter.toFixed(1)
}
```
Assim só foi outra forma de fazer o contador aparecer na tela, mas não era em cima disso que eu vi um problema.

Eu editei o repositorio e add 2 trechos de codigo que atualizam a cada 1 segundo, porem um deles tem a condicional que eu mencionei na primeira mensagem e o outro não tem a condicional. No que não tem a condicional eu peço que o sr teste clicar umas 10 vzs segudas no botão de iniciar, o contador fica cada vez mais rapido e msm clicando varias vezes no botão de parar o contador não zera mais.
Já no que tem a condicional, mesmo clicando varias vezes no botão de iniciar o contador, ele permanece contando a cada 1 segundo normalmente, sem acelerar, e ao clicar no botão de parar, ele para e zera normalmente tbm.

Eu entendi que o nome da variavel "condition" não quer dizer mt pra o que ele serve, mas eu não tive mt tempo pra ler ainda a issue que o sr indicou, assim que possivel eu vou ler e ver como ela poderia melhorar pra ficar mais legível.

Essa foi a solução que eu achei pra esse problema, caso um usuário clicasse mais de uma vez em iniciar e não dessse esse bug no programa.

Queria saber se teria outra forma de resolver esse problema, usando o if se outra forma ou outra recurso no JS que não conheço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi David.

A solução que você apresentou é válida sim. Parabéns pelo esforço =)

Seguindo essa linha de verificar com um boolean, para deixar a intenção mais clara, você pode declarar uma `let isCounterRunning` que é inicializada com `false`.

Quando o botão de iniciar o contador é clicado, se `isCounterRunning` não é `true`, o `setInterval()` é executado e `isCounterRunning` recebe true.

Quando o botão de parar o contador é clicado, `isCounterRunning` recebe `false`.

Sacou a ideia?

Essa é uma forma de resolver. Uma outra forma é a que expliquei na outra issue que comentei e referenciei ali em acima. 

> Queria saber se teria outra forma de resolver esse problema, usando o if se outra forma ou outra recurso no JS que não conheço.

As duas formas de resolver (com boolean ou a que comentei na outra issue) são simples e fáceis de entender. Podem haver outras formas, mas elas poderiam complicar o entendimento e legibilidade do código.

Qualquer uma das duas que você escolher vai ser satisfatória =)

Respondi sua dúvida?

@DavidLSousa

**Comment by DavidLSousa** [comment]
Poderia explicar mais uma vez a forma que o sr resolveu esse problema na outra issue? 
Acho que não entendi bem como foi resolvido na primeira vez essa questão dos clicks múltiplos nos botões.

Obrg pela dica do nome pra colocar na let, fica bem mais claro msm o significado dela.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi David.

> Poderia explicar mais uma vez a forma que o sr resolveu esse problema na outra issue?

Claro! Antes disso, apenas para documentar o passo-a-passo da solução com o boolean, ficaria assim:

1. Uma `let` isCounterRunning é inicializada com `false`, no topo do código.

```javascript
let isCounterRunning = false
```

2. Quando o botão de iniciar o contador é clicado, se `isCounterRunning` não é `true`, o `setInterval()` é executado e `isCounterRunning` recebe true.

```javascript
buttonInitCounter.addEventListener('click', () => {
  if (!isCounterRunning) {
    timer = setInterval(incrementCounter, 1000)
  }

  isCounterRunning = true
})
```

3. Quando o botão de parar o contador é clicado, `isCounterRunning` recebe false.

```javascript
buttonStopCounter.addEventListener('click', () => {
  clearInterval(timer)
  
  counterContainer.textContent = 0
  isCounterRunning = false
})
```

Essa é uma forma de resolver, usando um boolean.

---

A forma que comentei na outra issue utiliza um array que contém os botões clicados. Vou deixar o passo-a-passo dela também, para facilitar o entendimento. Mas a forma acima é mais simples, dê preferência a ela.

1. Uma `let` clickedButtons é iniciada com um array vazio, no topo do código. A cada vez que um dos 2 botões for clicado, uma string é adicionada como item desse array.

```javascript
let clickedButtons = []
```

2. Se o botão "iniciar contador" foi clicado, uma string 'init button' é adicionada no array. Se o botão "parar contador" foi clicado, uma string 'stop button' é adicionada no array.

```javascript
buttonInitCounter.addEventListener('click', () => {
  clickedButtons.push('init button')
  timer = setInterval(incrementCounter, 1000)
})

buttonStopCounter.addEventListener('click', () => {
  clickedButtons.push('stop button')
  clearInterval(timer)

  counterContainer.textContent = 0
})
```

3. Na função de listener de clique do `buttonInit`, um if checa se o array contém 2 ou mais itens e se os 2 últimos itens do array correspondem à string 'init button'.

Se corresponderem, um return dentro do bloco do if é executado para que a função pare imediatamente de ser executada e nenhuma manipulação no contador seja feita.

```javascript
buttonInitCounter.addEventListener('click', () => {
  clickedButtons.push('init button')

  const wasInitCounterClickedTwice = clickedButtons.length >= 2 
    && clickedButtons
      .slice(-2)
      .every(item => item === 'init button')
  
  if (wasInitCounterClickedTwice) {
    return
  }

  timer = setInterval(incrementCounter, 1000)
})
```

Sacou a ideia? =)

@DavidLSousa

**Comment by Roger-Melo** [comment]
Oi David. Vou fechar a issue mas se não tiver ficado claro, eu reabro ela, ok? =)
