### ISSUE TITLE
Resumo da Aula Métodos comuns de strings - Aula 02-04 da etapa 01

### ISSUE THREAD

**Issue by CodeVitor** [roger-melo-treinamentos/curso-de-js-roger-melo#6201]
<h1> Metodos comuns de strings</h1>

+ Métodos são funções que pertecem a um objeto ou um tipo de dado especifico

+ Os metodos no Js são funcões que são implatadas no JS que pode ser invocada para alterar algo.

`lastIndexOf( )` = esse método vai obter a ultima ocorrencia do caractere na string e retornar o seu index.

`slice()` = adicionando dois argumentos, esse metodo 'corta' uma parte da string e retorna essa parte. O primeiro argumento pega o index de onde começa a cortar e o segundo argumento de onde termina de cortar.

`replace()` = vai substituir um caractere da string por outro, recebe dois argumentos, o primeiro argumento é o caractere que voce quer substituir, o segundo argumento é o caractere que sera substituido no lugar. 

+ Nenhum desses métodos citados vão mudar o conteudo da variavel, eles apenas retornaram uma 'cópia' com o valor modificado.

<h2> Exemplos </h2>

```js

let email = 'laracroft@rogermelo.com.br'
let emailLastIndex = email.lastIndexOf('a')
console.log(emailLastIndex)  //return 3 

let emailSlice = email.slice(0 , 4)
console.log(emailSlice) //return 'lara'

let emailReplace = email.replace('lara' , 'tom')
console.log(emailReplace) // return 'tomcroft@rogermelo.com.br'

**Comment by MivlaM** [comment]
Excelente @CodeVitor rumo à fluência! 🎯
