### ISSUE TITLE
Resumo da Aula Criando um objeto literal - Aula 01-03

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6204]
// Criando um objeto literal

* Objetos literais podem contém propriedades e métodos, no caso abaixo somente propriedades
* 
```
let user = {
nmae: 'Joao',
age: 31,
email: 'joao@gmail.com',
city: 'São Paulo',
blogPosts: ['Empadao de frango', ,'Pure de batata']
}

```
* Para acessar as propriedades podemos utilizar anotação de ponto ou colchete

// Anotação de ponto

user.name
user.age
user.city

// Anotação de colchete

```
user['name']
user['age']
user['city']

```
Se retribuimos um valor  conforme abaixo devemos utilizar a anotação de colchetes para acessar a alteração

```
const newUser = 'Diego'

user[newUser]

```

**Comment by MivlaM** [comment]
Excelente @dzpoke rumo à fluência! 🎯
