### ISSUE TITLE
Resumo da Aula 00 da etapa 00

### ISSUE THREAD

**Issue by giovannirp** [roger-melo-treinamentos/curso-de-js-roger-melo#6206]
Quando vc achar que não resolveu de forma certa, um exercício resolvido de forma diferente:
Passo 1 
Apagar seu código

Passo 2
Implementar sem olhar a correção

Passo 3
se travar, consultar as anotação durante a aula e tentar fazer novamente

![caneca](https://user-images.githubusercontent.com/10762886/225192135-a3b4888c-aa13-4def-b17a-c93c44d3daae.png)

**Comment by MivlaM** [comment]
Excelente @giovannirp rumo à fluência! 🎯
