### ISSUE TITLE
Resumo da Aula Template strings - Aula 02-06 da etapa 01

### ISSUE THREAD

**Issue by andlcode** [roger-melo-treinamentos/curso-de-js-roger-melo#6209]
- Strings podem ser escritas utilizando aspas simples ou aspas duplas. Para o browser não confundir o local de fechamento da string quando utilizamos mais de uma aspa, Fica a gosto do desenvolvedor a escolha das aspas.

- Para declarar variaveis Javascript dentro de uma template string, envolvemos a variavel com $ e { }. Vide exemplo.

```js
const postTitle = 'É bolacha ou biscoito ?'
const postAuthor = 'Matheus Saad'
const postComments = 15

// usando concatenação

// const postMessage =  'O post "' postTitle '", do ' postAuthor + ', tem ', postComments 

// usando template strings


const postMessage = `O post "${postTitle}", do ${postAuthor}, tem ${postComments} comentarios`

// criando template html

const html = `
 <h2>${postTitle}</h2>
   <p>Author: ${postAuthor}</p>
   <span>Este post tem ${postComments} comentarios</span>
   `

console.log(html)

```
Quando devemos usar template String:
- Quando é um template HTML
- Quando o texto contém aspas duplas ou simples.
- Quando precisa conter aspas dentro do texto

**Comment by MivlaM** [comment]
Excelente @andlcode rumo à fluência! 🎯
