### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04  da etapa 03

### ISSUE THREAD

**Issue by ThiagoDeMorais** [roger-melo-treinamentos/curso-de-js-roger-melo#621]
# Callbacks e o método forEach

* Funções de callback: São funções passadas em forma de argumento para outras funções.
```js
//Callback
function hi(name, height){
    console.log(`Olá, ${name}, você tem ${height} cm de altura.` );
}

const showData= callback =>{
    const name = prompt('Insira seu nome: ');
    const height = prompt('Insira sua altura em cm: ');
    callback(name,height )
}
showData(hi);
```

No código acima, a função *hi* foi passada como argumento para a função *showData* e armazenada no parâmetro *callback*. A função *hi* foi invocada dentro da função *showData* através do parâmetro *callback* e constantes criadas internamente na função *showData* foram passadas como argumento para a função *hi*.

* forEach: O forEach recebe uma função de callback e aplica essa função em cada elemento do array. 

```js
//forEach
const socialNetworks = ['Telegram', 'Status', 'COS.TV ', 'Voice'];
socialNetworks.forEach(()=>{
    console.log('Olá');//A função será executada 4 vezes 
                       //pois esse é o número
                       // de elementos do array.
});
```

O callback que será passado como argumento para o forEach pode ser invocado com três argumentos: o valor do elemento, o índice do elemento e o array que está sendo percorrido.

```js
//forEach
const socialNetworks = ['Telegram', 'Status', 'COS.TV ', 'Voice'];
socialNetworks.forEach((socialNetwork,index,array)=>{
    console.log(index, socialNetwork, array);

});
```
No código acima, a cada iteração do forEach, o índice do elemento, o elemento referente ao índice,  e o array  serão mostrados no console.

A declaração da função pode ser desacoplada:

```js
//forEach
const socialNetworks = ['Telegram', 'Status', 'COS.TV ', 'Voice'];
const logArrayInfo = (socialNetwork,index,array) =>{
console.log(index, socialNetwork, array);
}
socialNetworks.forEach(logArrayInfo);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ThiagoDeMorais! Rumo à fluência! 🔥
