### ISSUE TITLE
Aplicação: QUIZ

### ISSUE THREAD

**Issue by CleitonRReis** [roger-melo-treinamentos/curso-de-js-roger-melo#622]
https://github.com/CleitonRReis/quiz

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Cleiton.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

@CleitonRReis

**Comment by CleitonRReis** [comment]
Fala, Roger! Blz?

Na verdade não percebi que havia mais informações no exercício. Estou terminando a aplicação. Em breve postarei o restante do código.

Abs!

@Roger-Melo
