### ISSUE TITLE
Resumo da Aula Configurando o ambiente - Aula 01da etapa 01

### ISSUE THREAD

**Issue by elimadev** [roger-melo-treinamentos/curso-de-js-roger-melo#6229]
A aula inicialmente explica como baixar e instalar o editor VSCode. Após a instalação do mesmo, é necessário adicionar algumas extensões para facilitar a vida do desenvolvedor: 
   - LiveServer : Tem a função de criar um servidor local (localhost) para rodar as aplicações web em desenvolvimento em sua própria máquina no browser;
   - Emmet(instalada por default): Tem a função de agilizar a codificação através de uma linguagem resumida, gerando código html muito mais rápido.

É apresentada a ferramenta "f.lux" que tem a funcionalidade de reduzir a emissão de radiação dos monitores, forçando menos a visão e consequentemente gerando um menor estresse ao programador, este recurso já é disponível nativamente nos S.O.s como Windows 10 e Linux Ubuntu 22.04, não sendo necessária a instalação de ferramentas de terceiros.

**Comment by MivlaM** [comment]
Excelente @elimadev rumo à fluência! 🎯
