### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-04 da etapa 01

### ISSUE THREAD

**Issue by EduardoXavier16** [roger-melo-treinamentos/curso-de-js-roger-melo#6237]
Variável é um container para guardar um valor! Ela recebe um nome, pra quando necessário, você a chama, somente pelo nome!
Elas se dividem em dois grupos: Variáveis, cujo seu valor pode ser modificado depois de sua declaração, e Constantes, cujo valor não pode ser modificado! 
Existem algumas regras quanto a sua nomeação!
O que não pode: 
Seu nome não pode ser palavra reservada, começar por número, e não podem ser mais de uma palavra, a não ser que juntas no formato camelCase  ou snake_case!

Comentários:
Comentários de uma linha!   // antes do código ou testo
Comentários de bloco!   /* código aqui */

**Comment by MivlaM** [comment]
Excelente @EduardoXavier16 à fluência! 🎯
