### ISSUE TITLE
Resumo da Aula A fetch API - Aula 05-03 da etapa 11

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#6238]
A fetch API e uma maneira mais pratica de fazer requisições usando três passos:

1 - Buscar as informações através da invocação do método fetch.
Ex: 
fetch(url)

2 - Obter a resposta e retornar uma promisse com response.json( ).

3 - Encadear um segundo then( ) na promisse que o primeiro then( ) esta retornando, para dentro desta função fazer algo com os dados obtidos.

**Comment by MivlaM** [comment]
Excelente @YukOnRails rumo à fluência! 🎯
