### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#624]
O `this` é um objeto de contexto. Ele representa um objeto no contexto o qual o código atual está sendo executado. Se chamarmos o `this` em um `console.log()` na raiz do documento, veremos que ele se referencia ao objeto *window*. Porém se ele for chamado dentro de um método, ele irá referenciar o objeto no qual ele está sendo chamado. Vamos supor que temos um objeto `user`, que possui algumas propriedades, onde uma dessas propriedades é uma lista de títulos de post que foram escritos por este `user`, que será chamada de `blogPosts`. A ideia é criar um método que retorne essa lista de posts. Dentro do método criado, se apenas declararmos um `console.log(blogPosts)`, um erro será retornado dizendo que `blogPosts` não foi definida. Para isso, precisamos utilizar a palavra-chave `this` antes do nome da propriedade. Se apenas utilizamos o `this` no console, veremos que o que será exibido será o objeto `user` com todas as suas propriedades e métodos. Então, criando um método logBlogPosts, onde serão exibidos os posts, nosso código ficará da seguinte forma:

```jsx
let user = {
	name: 'Ricardo',
  age: 38,
  email: 'ricardopontesdantas@gmail.com',
  city: 'Rio de Janeiro',
  blogPosts: [
		'Criando objetos literais em JavaScript',
		'Adicionando métodos a objetos literais em JavaScript',
		'Utilizando a palavra-chave this'
	],
  login () {
		console.log('Usuário logado');
  },
  logout () {
		console.log('Usuário deslogado');
  },
  logBlogPosts () {
    console.log(`${this.name} escreveu os seguintes posts:`);
    
    this.blogPosts.forEach(post => console.log(post));
  }
}

user.logBlogPosts();

// Ricardo escreveu os seguintes posts:
// Criando objetos literais em JavaScript
// Adicionando métodos a objetos literais em JavaScript
// Utilizando a palavra-chave this
```

Agora uma observação importante: Se utilizamos *arrow functions* na criação dos métodos, o `this` irá referenciar o objeto *window*, e não o objeto que o chamou. Para que ele se referencie ao próprio objeto, devemos criar o método como uma *function declaration*. Porém para simplificar o código, o JavaScript nos permite eliminar os dois pontos e a palavra *function*, ficando apenas o nome do método seguido dos parênteses e do bloco de código entre chaves, como mostrado no código acima.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência, meu caro! 👊🏻
