### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-04 da etapa 01

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6241]
## O que é uma variável

Uma das coisas mais importantes são as variáveis.

A sua função é armazenar um valor

E temos alguns tipos :

```js
let a = 0 // Pode ter o seu valor trocado a qualquer momento
const b = 1 // O valor atribuído para ela virá um valor constante
```

## Regras para nomear variáveis:  

Tem que ser uma unica palavra, mas vc pode usar mais palavras usando convenções como camelCase 
Nao se pode usar palavras reservadas como "let", "const", "and"...

## Comentarios

```js
// Podemos comentar com duas "/"
```

**Comment by MivlaM** [comment]
Excelente @gvao rumo à fluência! 🎯

**Comment by gvao** [comment]
Vlw @MivlaM !!!
