### ISSUE TITLE
Resumo da Aula Strings - Aula 02-03 da etapa 01

### ISSUE THREAD

**Issue by Latorreander** [roger-melo-treinamentos/curso-de-js-roger-melo#6242]
**Strings:**
 String é um encadeamento de caracteres envolvidos por aspas, sejam eles letras, números.
```js
const firstName = 'Nathan'
const lastName = 'Drake'
let number = '342';
const email = 'fulano@detal.com.br'
```
Obs: Qualquer caracter dentro das aspas é uma string!

Armazenamos uma string utilizando aspas simples ou duplas.
Podemos armazenar uma string dentro de uma variável.

**Concatenação de strings:**

Podemos concatenar duas strings usando o sinal de +, ou seja juntar uma string a outra.

```js
const fullName = firstName + lastname
console.log(fullName) // NathanDrake
```
Para espaçar duas strings, colocamos uma string vazia entre os sinais de +:
```js

const fullName = firstName + ' ' +lastname
console.log(fullName) // Nathan Drake
```

**Acessando caracteres:**

Para cessar um único caracter de uma string que foi armazenada podemos usar a notação de colchete que seria

 tratar a string como um objeto array-like onde os caracteres individuais correspondem a um índice numérico:
```js
console.log(fullName[0]) // N
```
obs. dentro dos colchetes informamos o índice da posição da letra a ser acessada, lembrando que o Js é uma linguagem zero based, significa que ele começa a contar  a partir do número zero e não do número 1.

outra  forma é utilizando o método charAt( ):

```js
console.log(lastName.charAt(0))// D
```

**Comprimento de uma string:**

Uma string possui métodos e propriedades, uma delas é o length. o length é uma propriedade que informa o comprimento de uma string(quantos caracteres ela tem), para digitar uma propriedade separamos ela do objeto com um ' . ' :

```js
console.log(fullName) // Nathan Drake
console.log(fullName.length) // 12
```
Note que o 12 não é o número certo de caracteres do valor da variável fullName, porque espaços vazios são considerados caracteres pela propriedade length.

**Métodos de string**

strings tem funções associadas a elas que se chamam métodos, existe uma diferença entre função e método:

Uma função é um pedaço de código que executa uma ação específica.

Um método é uma função associada a um objeto ou tipo de dado em particular.

```js
console.log(fullName.toUpperCase( ) ) // NATHAN DRAKE

const result = fullName.toLowerCase( )
console.log( result) // nathan drake
```
Notação de ponto especifica uma propriedade = .propriedade
Especifica método = .metodo( )

O método precisa ter essa abertura e fechamento de parênteses, pois é uma função e por se tratar de uma função ela precisa ser invocada para ser executada.

Obs: esses dois métodos  que vimos acima não alteram o valor original  no qual eles estão executando a ação:

```js
const result = fullName.toLowerCase( )
console.log( result, fullName) // nathan drake, Nathan Drake
```

Existem métodos que esperam receber algum valor dentro dos parênteses de execução esse valor dentro dos parênteses se chama
 ARGUMENTO

```js
const email = 'ander@gmail.com'
const index = email.typeOf( '@')
console.log(index) // 5
```
Link exercícios Modelo MDN: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Useful_string_methods

**Comment by MivlaM** [comment]
Excelente @Latorreander rumo à fluência! 🎯
