### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-04 01

### ISSUE THREAD

**Issue by CidMaia** [roger-melo-treinamentos/curso-de-js-roger-melo#6244]
Conceito de 
1. Variáveis, como declarar uma variável (let)
2. Constante, como declarar uma constante (const)
3. Como atribuir valor tanto nas variáveis como nas constantes  (=)
4. Como escrever o nome de uma variável/constante, usar a boa pratica de programação chamada camelcase(camelo), a primeira letra e minuscula seguida da segunda que e maiúscula, simbolizando assim as costas de um camelo, exemplo : let = myAge, const = currentYear etc;
5. passado as formas de comentar o código; existe duas formas 01. /* comentários em bloco*/  ; // comentários em linha
6. regras de como declarar variável; so pode conter letras, números, underscore e cifrão, mais o nome não pode começar com numero.
7. Não usar mais a palavra ( var = ) para declarar uma variável, substituir por (let = ) , pois browsers modernos não reconhecem mais o comando ( var = )
8. palavras com variáveis reservadas; existe uma lista no final da aula que tem algumas variáveis de palavras reservadas.

**Comment by MivlaM** [comment]
Excelente @CidMaia rumo à fluência! 🎯
