### ISSUE TITLE
Aplicação: QUIZ

### ISSUE THREAD

**Issue by CleitonRReis** [roger-melo-treinamentos/curso-de-js-roger-melo#626]
Fala, Roger! Blz?

Segue novo link da aplicação proposta - quiz.

Minha maior dificuldade foi animar a porcentagem. Eu estava colocando no 'textContent' do span, a própria variável 'timer' que guardava o valor do setInterval. Quando, na verdade, deveria criar uma variável contadora a parte. 

Fora isso, não tive grandes dificuldades.

Segue link:

https://github.com/CleitonRReis/quiz-interativo-CJRM

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show. Em breve posto a análise aqui =)

**Comment by Roger-Melo** [comment]
Olá Cleiton!

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo as oportunidades de melhoria que observei.

## Usabilidade

No popup exibindo os pontos, eu deixaria o usuário ter mais controle do momento em que a aplicação deve parar de exibir a pontuação. Ou seja, ao invés da pontuação desaparecer após 2 segundos e meio, eu preferiria deixar um botão de fechar o popup. Apenas para que o usuário sinta que ele tem o controle de exibição dessa informação. 

Porém, isso é apenas uma opinião pessoal. O mais importante você fez, que era implementar a exibição dos pontos. Nas aulas seguintes você verá a forma que implementei =)

## Organização de código

### Nomes de variáveis e funções

Evite nomear elementos do DOM com nome de tags. Essa aplicação tem um escopo pequeno, mas em aplicações maiores, é possível que a tag da marcação HTML mude. Neste caso, uma const nomeada como `span`, por exemplo, precisaria ser renomeada. Por isso, prefira dar um nome que descreva o que o elemento do DOM irá conter. 

Seguindo esse princípio, eu renomearia a const span para `scoreContainer` ou `scoreEl` ("El" é uma abreviação de "element").

A const `modal` também pode ser mais descritiva. Acredito que se ela fosse nomeada como `scoreModal`, seria mais fácil entender do que se trata o modal. 

`corectOptions` pode ser renomeada para `correctOptions`, com dois "r".

Acredito também que no contexto do quiz, `answers` pode ser mais específico que `options`.

O nome de uma função é mais compreensível quando é um verbo que descreve a ação que a função está executando. Seguindo este raciocínio, eu renomearia `timerOut` (substantivo) para algo como `removeScoreModal`.

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo este princípio, eu apenas adicionaria uma linha em branco entre as consts que armazenam referências de elementos do DOM e a const que armazena as respostas corretas:

```javascript
const form = document.querySelector('.quiz-form');
const span = document.querySelector('span');
const modal = document.querySelector('.quiz-modal');

const corectOptions = ['B', 'B', 'B', 'B'];
```

Novamente, parabéns pelo esforço em aplicar o método e construir a aplicação =)

As observações acima fizeram sentido?

@CleitonRReis

**Comment by CleitonRReis** [comment]
Boa noite, Roger! Tudo bem?

Fazem sentido, sim. Muito obrigado pela análise.

😎👌🏻

Sent from my iPhone

On 5 May 2021, at 22:54, Roger Melo ***@***.***> wrote:

﻿

Olá Cleiton!

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo as oportunidades de melhoria que observei.

Usabilidade

No popup exibindo os pontos, eu deixaria o usuário ter mais controle do momento em que a aplicação deve parar de exibir a pontuação. Ou seja, ao invés da pontuação desaparecer após 2 segundos e meio, eu preferiria deixar um botão de fechar o popup. Apenas para que o usuário sinta que ele tem o controle de exibição dessa informação.

Porém, isso é apenas uma opinião pessoal. O mais importante você fez, que era implementar a exibição dos pontos. Nas aulas seguintes você verá a forma que implementei =)

Organização de código
Nomes de variáveis e funções

Evite nomear elementos do DOM com nome de tags. Essa aplicação tem um escopo pequeno, mas em aplicações maiores, é possível que a tag da marcação HTML mude. Neste caso, uma const nomeada como span, por exemplo, precisaria ser renomeada. Por isso, prefira dar um nome que descreva o que o elemento do DOM irá conter.

Seguindo esse princípio, eu renomearia a const span para scoreContainer ou scoreEl ("El" é uma abreviação de "element").

A const modal também pode ser mais descritiva. Acredito que se ela fosse nomeada como scoreModal, seria mais fácil entender do que se trata o modal.

corectOptions pode ser renomeada para correctOptions, com dois "r".

Acredito também que no contexto do quiz, answers pode ser mais específico que options.

O nome de uma função é mais compreensível quando é um verbo que descreve a ação que a função está executando. Seguindo este raciocínio, eu renomearia timerOut (substantivo) para algo como removeScoreModal.

Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo este princípio, eu apenas adicionaria uma linha em branco entre as consts que armazenam referências de elementos do DOM e a const que armazena as respostas corretas:

const form = document.querySelector('.quiz-form');
const span = document.querySelector('span');
const modal = document.querySelector('.quiz-modal');

const corectOptions = ['B', 'B', 'B', 'B'];

Novamente, parabéns pelo esforço em aplicar o método e construir a aplicação =)

As observações acima fizeram sentido?

@CleitonRReis<https://github.com/CleitonRReis>
