### ISSUE TITLE
Exercícios Aula 01

### ISSUE THREAD

**Issue by Keydorah** [roger-melo-treinamentos/curso-de-js-roger-melo#6270]
### Etapa da aula

1

### Nome da aula

Exercícios da Aula 01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706656

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa noite, desculpe, sou novo, fiquei meio confuso, nesta aula 01 eu baixei 40 exercícios, devo resolver todos os 40 para avançar para a próxima aula?  

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Keydorah! 

Essa é a mesma dúvida que vc postou no grupo fechado dos alunos no Telegram? 

Ela foi respondida?

**Comment by Keydorah** [comment]
> Olá @Keydorah! 
> 
> Essa é a mesma dúvida que vc postou no grupo fechado dos alunos no Telegram? 
> 
> Ela foi respondida?

Foi sim, obrigado
