### ISSUE TITLE
Duvida sobre Exercicio 03 - numero 8 da lista

### ISSUE THREAD

**Issue by matheusmoraesn** [roger-melo-treinamentos/curso-de-js-roger-melo#6275]
### Etapa da aula

1

### Nome da aula

Exercicios 3 

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706668

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

```
- Exiba no console o último item do array "dogNames", mas de  
forma que caso a quantidade de itens do array aumente ou diminua,  
o último item continue sendo exibido;
- Para testar essa lógica, na linha acima do console.log que  
você acabou de escrever, remova o último item do array "dogNames"  
utilizando o método adequado para isso;
- O console deve continuar exibindo o último item do array, que  
agora é "Lilica".
*/

const lastDogName = dogNames
lastDogName.pop()
console.log(lastDogName[lastDogName.length - 1])
```

A duvida é , apesar de ter resolvido ( usei o exemplo do exercicio 2 que tem uma questão parecida para resolver esse)
não entendo esse console.log, o porque tem esses colchetes em " lastDogName[lastDogName.length - 1]"
eu entendi a logica do -1 , mas isso que fazemos com esses colchetes seria um metodo ? pois achava que geralmente usava-se ponto ou parenteses

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @matheusmoraesn! 

O console.log está ali apenas pra que você consiga visualizar o resultado da expressão `lastDogName[lastDogName.length - 1]`. Se vc remover o console.log e deixar apenas a expressão, não irá conseguir visualizar o resultado que a expressão gera!

Na [Aula 03-02](https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706666) desta etapa eu mostrei que os colchetes são uma forma de acessar itens de um array. 

Recomendo que reveja a aula (só clicar no link do parágrafo acima) pq isso pode ter passado despercebido mas é um conceito fundamental para você trabalhar com arrays em JS.

Se após ver a aula restarem mais dúvidas, é só comentar aqui abaixo =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova.
