### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by CodeVitor** [roger-melo-treinamentos/curso-de-js-roger-melo#6279]
<h1> Conversão de tipos </h1>

+ Significa que é possivel a gente transformar um tipo de dado em outro tipo de dado.

Number() -> transforma string em number

```js

let score = '100'
score = Number(score)
console.log(score + 1) //return 101

```

typeof -> retorna o tipo de dado

```js
let score = '100'
console.log(typeof score) //return string
```

+ Qualquer operação matematica que nao faça sentido como por exemplo coverter um valor pra number e que nao faz sentido
vai retornar NaN

```js

const crazyConversion = Number('Maça')
console.log(crazyConversion) //return NaN

const convertedNumber = String(97)
console.log(convertedNumber) // return 97 -- > (string)
console.log(convertedNumber, typeof convertedNumber) // return 97 string

```

+ Convertendo Valores em  Booleans ( true / false)

``` js

const booleanConversion = Boolean(10)
console.log(booleanConversion, typeof booleanConversion) // return true "boolean"

```

<h4> Por que resultou em true ? </h4>

+ em JS alguns valores retornan true e outros false.

Valores falsy: todos esses valores convertido em boolean retornaria false

+ false
+ 0
+ "" , ' ' , ` `
+ null
+ undefined
+ NaN

Valores Truthy: todos esses valores convertidos em boolean retornaria true

+ Qualquer valor que nao é falsy

**Comment by MivlaM** [comment]
Excelente @CodeVitor, rumo à fluência! 🎯
