### ISSUE TITLE
Resumo da Aula Expressões regulares - Aula 01-04 da etapa 6

### ISSUE THREAD

**Issue by paulovieiradasilva** [roger-melo-treinamentos/curso-de-js-roger-melo#6286]
Nesta aulo foi mostrado alguns exemplos de utilização de regax para validar strings.

Documentação: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by MivlaM** [comment]
Excelente @paulovieiradasilva, rumo à fluência! 🎯
