### ISSUE TITLE
Resumo da Aula 05-03da etapa 11

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#6288]
<h1 align="center">Fetch</h1>

Fetch é um método nativo do Javascript muito mais moderno do que o XHTTPRequest que vimos antes, esse método é menos verboso, e trás um resultado muito semelhando ao que já vimos.

O fetch tem 3 etapas essenciais:

1- O fetch que recebe como argumento o endereço.
2- um then que recebe um parametro resolve (convenção de nomeclatura das promises) e um resolve.json() que vai trazer os dados, semelhante ao parse, porém ainda não vai trazer a resposta pois isso retorna uma promessa.
3- um encadeamento do then que recebe o retorno do argumento

```js
fetch("https://pokeapi.co/api/v2/pokemon/gengar")
  .then(resolve => resolve.json())
  .then(pokemon => console.log(pokemon))
  .catch(error => console.log(error))
```

Para tratar erros, podemos encadear um catch assim como no XHTTPRequest, como no exemplo acima.

**Comment by MivlaM** [comment]
Excelente @Beninigmal, rumo à fluência! 🎯
