### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by EduardoXavier16** [roger-melo-treinamentos/curso-de-js-roger-melo#6289]
Nessa aula vimos como JavaScript trata os números!

Inteiros e decimais

Os inteiros são aqueles que ao serrem divididos, não retornam resto! Assim como na matemática básica mesmo!
```
Ex: let radius = 10
```
Já os decimais possuem uma pequena diferença, eles usam o ponto, ao invés da vírgula para separar a parte quebrada!
```
Ex: const pi = 3.14
```
Operadores aritiméticos (reminder)
Remindeer é o operador aritimético que retorna o resto de uma divisão!
```
Ex: const reminder = 10 % 3 => 1 
```
JavaScript segue a mesma precedencia da matemática básica!
Ou seja segue uma ordem para realizar diferentes operações!

1- ( ) // JS resolve primeiro tudo o que estiver entre parenteses!
2- ** //expoêntes e raizes!
3- * ou / //Multiplicações e divisões
4- + - //Adições e subtrações
```
Ex: const area = pi * radius ** 2 => 314
```
Operadores de incremento e decremento!
```
radius = radius +1 => 11;  Pode ser simplesmente:  radius++; =>11 //Incremento
ou
radius--; =>9 //Decremento
```
Operadores assignment:
São operadores unidos que tornam a escrita do código mais simples!
Por exemplo, você poderia escre assim:
```
let postLikes = 10
postLikes = postLikes + 10 => 20
ou simplesmente:
postLikes += 10 => 20 //Operador assignment:
```
NaN:
Esse é o valor que é mostrado pelo JS, quando você realiza uma operação, cujo o valor é nulo!
```
const crazyNumbers = 10 + 'hi'
console.log(crazyNumbers) => NaN
```
Também podemos concatenar strings com números!
```
const age = 37
const message = 'My age is'
const IAmAOldMan = message + age => My age is 37
```

**Comment by MivlaM** [comment]
Excelente @EduardoXavier16 , rumo à fluência! 🎯
