### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6292]
Outro tipo de controle de fluxo é o switch. O switch é usado para verificar uma variável ou expressão que pode ter múltiplos valores e para cada valor possível, há uma possibilidade de agir de forma diferente. O switch funciona da seguinte forma: caso a condição seja atendida, o case será executado e, em seguida, o break será usado para sair do switch. Se as condições não forem atendidas, o default será executado. 
É útil para verificar variáveis ou constantes com múltiplos valores e agir de forma diferente para cada valor possível.

**Comment by MivlaM** [comment]
Excelente @dev-jefferson-lopes, rumo à fluência! 🎯
