### ISSUE TITLE
Etapa 02 - Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#63]
```js
/*
  08 - Comente o console.log() acima e:

  - Armazene em uma constante "ages" um array com os números 31, 82, 61 e 11;
  - Armazene em uma constante "agesSum" a soma entre 1º e 3º itens do array  
    "ages";
  - Exiba a frase abaixo no console, substituindo "BOOLEAN" pela informação  
    correta.

  "A soma entre o 1º e o 3º item de "ages" é menor ou igual a 92. Essa afirmação  
  é: BOOLEAN."
*/
```
Neste você diz pra somar 1º item do array que é 31 e o terceiro item do array que é 11

Na correção você colocou 
```js 
const agesSum = ages[0] + ages[2]
```

o certo não é eu pegar a 
```js
ages[3]  // 11 
```
Pois a contagem não é zero-based. ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gohara.

Observe que no enunciado,

```
- Armazene em uma constante "ages" um array com os números 31, 82, 61 e 11;
```

o terceiro item do array é o 61. Ele vem antes do quarto item, que é o 11.

Então para acessar o 3º item, que é o 61, a notação fica assim `ages[2]`.

Sacou a ideia?

@GoharaJunior

**Comment by GoharaJunior** [comment]
Ah sim, obrigado!

**Comment by Roger-Melo** [comment]
Legal! No que precisar, é só abrir uma nova issue =)
