### ISSUE TITLE
Resumo da Aula Criando um objeto literal - Aula 01-03 da etapa 04

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#6301]
<h1>Criando objetos</h1>

Objetos literais são formados por um par de chaves e dentro dessas chaves eu seto suas propriedades e métodos, propriedades são formados por chave e valor separados por notação de dois pontos, se eu quiser adicionar outras propriedades eu separado elas por virgulas.

Uma boa prática é seguir a convenção usando cada propriedade em uma nova linha.

Exemplo:
```js
const user = {
  name: 'Mateus',
  age: 31,
  email: 'mateus@gmail',
}
```

Para acessar as propriedades de um objeto eu posso usar tanto a notação de ponto quanto a notação de colchetes, sendo que a notação de colchetes aceita tanto uma string quanto uma variável.

```js
console.log( user.name, user['name'] ) // vão ter o mesmo resultado
```

Reatribuindo o valor de uma propriedade.
Exemplo;
```js
const person = {
  name: 'Julio',
  age: 45
}

//reatribuindo
person.name = 'Mateus'
person['age'] = 32

console.log( person ) // { name: 'Mateus', age: 32}
```

**Comment by MivlaM** [comment]
Excelente @MateusCavalheiro-prog, rumo à fluência! 🎯
