### ISSUE TITLE
Etapa 3, nome do vídeo: Exercício nº 3

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#631]
Trabalhando na resolução do Exercício 3 digitei assim:
```JS
function repeatString (manyRepeat = 7){
  return 
}
  console.log(repeatString)
```
  Por que a resposta foi essa, não deveria ser uma mensagem de erro? 

ƒ repeatString (manyRepeat = 7){
  return 
}

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Marcos.

Antes de responder, deixa eu dar uma dica...

Ao abrir uma issue, prefira copiar e colar o nome da aula que aparece logo abaixo do vídeo:

![nome-da-aula](https://user-images.githubusercontent.com/29297788/115944908-29976b80-a48f-11eb-9530-ef0d5e646269.jpg)

E para copiar o número da etapa, olhe a listagem à esquerda do vídeo:

![numero-da-etapa](https://user-images.githubusercontent.com/29297788/115944945-66636280-a48f-11eb-8d94-31292a547957.jpg)

Aí é só colar o número da etapa e o nome da aula no título da issue:

![titulo-da-issue](https://user-images.githubusercontent.com/29297788/115945023-e7225e80-a48f-11eb-9ac5-87149b80b432.jpg)

Isso facilita na hora de eu encontrar a aula exata e ajudar com mais precisão =)

---

Repondendo a dúvida, uma mensagem de erro não é lançada por que na verdade, `repeatString` é um [identificador](https://developer.mozilla.org/en-US/docs/Glossary/Identifier) para a função. É como se ele fosse uma variável que armazena a função.

Ou seja, `repeatString` é uma referência para a função. Em ciência da computação, uma referência é um pedaço de código que contém um outro pedaço de código.

Em breve você vai encontrar as aulas sobre callbacks, onde eu mostro como referências de funções serão úteis =)

Ficou mais claro?

@marcosyoggy

**Comment by Roger-Melo** [comment]
@marcosyoggy vou fechar a issue mas se não tiver ficado claro, é só dar o toque que reabro ou abrimos outra, ok?
