### ISSUE TITLE
Resumo da Aula Async/await - Aula 05-04 da etapa 11

### ISSUE THREAD

**Issue by YukOnRails** [roger-melo-treinamentos/curso-de-js-roger-melo#6325]
- Async

Usada para tornar uma função comum (bloqueante/síncrona) em assíncrona.
A palavra chave ASYNC e utilizada antes da declaração da função e logo após seu nome.
Ex: 
const getUsers = async ( ) => { }
 
--------------------------------------------------------------------------
- Await

Palavra chave que so pode ser utilizada dentro de uma função ASYNC e tem como função pausar a execução do restante do código abaixo de si ate o momento em que a resposta da invocação seja obtida.
Ex:
const getUsers = async ( ) => {
 const response = await fetch(url)
 const users = await response.json( )
 console.log(users)
}
getUsers( )

------------------------------------------------
A proposta das funções async/await é de simplificar o uso de forma síncrona das Promises e executar alguns procedimentos em um grupo de Promises. Assim como Promises são similares a callbacks estruturados, funções async/await são similares à junção de generators com Promises.

* Uma função async sempre retorna uma promisse que encapsula o valor que a função esta retornando.

**Comment by MivlaM** [comment]
Excelente @YukOnRails , rumo à fluência! 🎯
