### ISSUE TITLE
Duvida no operador =+

### ISSUE THREAD

**Issue by Thalles17** [roger-melo-treinamentos/curso-de-js-roger-melo#6338]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 03 - Aula 04-01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706669

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Fala professor Roger, minha duvida é quando  você fala no exercício 12 que a const oddNumbers " recebe o que ela já tem + 4" o que entendi é que recebendo o que já tem que é 125 + 4.... não entendo como chega aos 729...

esse calculo que não to conseguindo calcular.

@Roger-Melo

**Comment by pgstudies22** [comment]
@Thalles17 No código abaixo, o segundo item do array foi substituído pelo resultado de 5 + 4, que é 9: 

```javascript
let oddNumbers = [3, 5, 7]

oddNumbers[1] += 4
// ☝🏻 isso é o mesmo que fazer oddNumbers[1] = oddNumbers[1] + 4

console.log(oddNumbers[1]) // 9
```

Basicamente, o resultado mostrado na aula vem da expressão`9 ** 3`:

```javascript
let oddNumbers = [3, 5, 7]

oddNumbers[1] += 4

// 👇🏻 essa expressão está exibindo no console o resultado de 9 ** 3, que é 729
console.log(oddNumbers[1] ** 3)
```

**Comment by Roger-Melo** [comment]
@Thalles17 No código abaixo, o segundo item do array foi substituído pelo resultado de 5 + 4, que é 9: 

```javascript
let oddNumbers = [3, 5, 7]

oddNumbers[1] += 4
// ☝🏻 isso é o mesmo que fazer oddNumbers[1] = oddNumbers[1] + 4

console.log(oddNumbers[1]) // 9
```

Basicamente, o resultado mostrado na aula vem da expressão`9 ** 3`:

```javascript
let oddNumbers = [3, 5, 7]

oddNumbers[1] += 4

// 👇🏻 essa expressão está exibindo no console o resultado de 9 ** 3, que é 729
console.log(oddNumbers[1] ** 3)
```

**Comment by Roger-Melo** [comment]
@Thalles17 o operador que vc postou no título da issue não existe. O operador correto é `+=`

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova.
