### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#634]
Olá professor! Eu mais uma vez rs 🤓
Dessa vez venho publicar minha aplicação Weather-App para análise.

### Maiores dificuldades
- Acredito que a refatoração principalmente na nomeação das minhas funções de responsabilidade única. Mas acredito que ainda não tenho confiança suficiente nessa nomeação e por com isso a balança tende a me levar que essas nomeações não estão legais, mas aguardo a avaliação

### Menores dificuldades
- Solicitar e consumir dados das APIs fornecidas pelas AccuWeather
- Tratamento de promises e erros
- Entender com exatidão o que cada instrução da minha aplicação está fazendo

### Links:
- Repositório: https://github.com/sou-gabriel/weather-cjrm
- Aplicação: https://heuristic-hawking-a962f2.netlify.app/

Professor uma dúvida que tenho é a seguinte é que consigo fazer a aplicação sozinho, por conta própria, mas no final das contas sempre acho o código da minha aplicação muito parecido com o teu, embora eu consiga fazer tudo sozinho sem dificuldades, isso é algo que devo me preocupar?

Abração professor!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

> sempre acho o código da minha aplicação muito parecido com o teu

Isso é natural. Muitas variáveis influenciam na sua forma de se expressar no código. Bagagem, referências, cursos, time, etc. Com a prática, você vai moldando o seu estilo de código. O meu estilo tem uma pegada mais funcional, inclusive eu deixo isso claro na etapa de orientação a objetos. Ensino como classes funcionam mas também mostro que para mim elas não fazem muito sentido na maioria dos casos. 

Essa pegada mais funcional vai facilitar para você na hora de trabalhar com o React, por exemplo.

Mas se acaso você começar a trabalhar em um time que curte muito orientação a objetos e só quer programar assim (mesmo que não faça muito sentido em JavaScript), provavelmente precisará revisar alguns conceitos da etapa 14. Mas nada muito complicado, pois você já tem uma base da linguagem =)

@sou-gabriel

**Comment by Roger-Melo** [comment]
Essa análise foi bem rápida rs. 

Deu pra perceber que você está bem afiado e compreendeu bem a lógica até aqui. Também nomeou bem as variáveis e quebrou o código em funções de única responsabilidade.

Minhas poucas observações são as seguintes...

## Organização de código

### Nomes de variáveis e funções

Como em inglês as palavras possuem uma ordem diferente do português brasileiro, eu renomearia `handleSubmitCity` como `handleCitySubmit`.

### Linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo este princípio, eu separaria o `return` das invocações das funções:

```javascript
if (isAValidCity) {
  insertCityInfoIntoDOM(inputCityName)
  showCityCard()

  return
}
```

E separaria a declaração da `inputCityName` das invocações de método/função:

```javascript
const handleSubmitCity = event => {
  event.preventDefault()

  const inputCityName = event.target.city.value.trim()  
  
  showCityInfo(inputCityName)
  event.target.reset()
}
```

Quando um bloco de código contém apenas duas linhas, eu quebro este princípio. Afinal, não faz sentido deixar um "buraco" entre apenas duas linhas de código.

☝️ o princípio das linhas em branco é mais uma forma pessoal de como gosto de visualizar o código =)

As observações acima fizeram sentido?

@sou-gabriel

**Comment by sou-gabriel** [comment]
> As observações acima fizeram sentido?

Total Roger, essa questão das linhas em branco e da nomeação de variáveis eram um dos pontos que me deixavam um pouco com um pé atrás na refatoração, mas pegando as observações captei bem o que você quis passar e vou aplicar daqui pra frente.

Professor só gratidão. Obrigado =)
