### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6344]
Podemos passar argumentos para uma função e usá-los dentro da própria função. Além disso, é possível passar uma função como argumento, chamada de callback. O callback é uma função que será executada dentro de outra função.

O forEach é um método que itera sobre um array. A tradução literal é "para cada", o que significa que para cada item do array, uma ação será executada. Ele funciona como um loop for, mas de maneira mais elegante e funcional. O forEach recebe uma função de callback. Dentro dos parênteses, podemos passar três argumentos, mas só o primeiro é obrigatório: O primeiro é o valor do elemento, o segundo é o índice do elemento e o terceiro é o próprio array. O forEach não retorna nenhum valor, ele apenas itera sobre os elementos do array.

Outra vantagem do forEach em comparação com o for é que a declaração da função pode ser desacoplada. deixando o código mais organizado e modular.

**Comment by MivlaM** [comment]
Boa @dev-jefferson-lopes rumo à fluência! 🔥
