### ISSUE TITLE
Aplicação: QUIZ

### ISSUE THREAD

**Issue by Nathan-013** [roger-melo-treinamentos/curso-de-js-roger-melo#635]
Boa tarde Roger, segue a minha aplicação do quiz (como pedido no exercicio 01 da etapa 07).
Nessa primeira parte, senti dificuldades apenas na hora de dar nome as variaveis,. Quanto a manipulação
do DOM, me sinto bem confortável por enquanto.

segue o link do repositório da minha aplicação:
https://github.com/BlackS-heep/Aplicacao-QUIZ.git

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @BlackS-heep.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Nathan.

Parabéns pelo esforço em implementar a primeira aplicação. Deu pra perceber que você de fato está confortável com a lógica até aqui =)

Vou deixar abaixo alguns pontos de melhoria que observei durante a análise.

## Usabilidade

### Local da exibição dos pontos

O print abaixo foi tirado logo após o envio do form:

![image](https://user-images.githubusercontent.com/29297788/117388780-b267cb80-aec1-11eb-8f96-c518d3033e5d.png)

Quando o form é enviado, os pontos são exibidos na parte inferior da tela e boa parte do feedback visual fica comprometida. Uma alternativa seria exibir os pontos acima do botão, por exemplo. 

Nas aulas seguintes eu mostro uma forma de inserir os pontos na tela. Mas ao inserir um elemento na interface, certifique-se de que ele está bem posicionado em relação ao olhar do usuário, de preferência sem a necessidade de ele ter que rolar a tela =)

## Organização de código

### Local de declaração ou uso de variáveis

Quando possível, prefira deixar as manipulações de DOM de um elemento "agrupadas" em um só local.

No caso da manipulação da classe no `h1`, por exemplo, você pode deixar ela próxima à outra manipulação do h1 (textContent) ao invés de deixá-la no topo:

```javascript
const quizMessage =  event => {
  // ...
  const message = `Você acertou ${score}% do quiz`
  
  h1.textContent = message
  h1.classList.add('mx-5') // manipulação da classe junto à manipulação do texto
  div.appendChild(h1)
}
```

Isso facilita na hora de localizar as linhas de código que envolvem o elemento do DOM, pois elas estão em apenas um lugar.

### Nomes de variáveis e funções

Um princípio que pode ajudar na hora de nomear suas variáveis e funções é: funções são verbos, variáveis são substantivos.

Com isso em mente, eu renomearia `quizMessage` deixando mais explícito a alçao que ela faz ao ser invocada. Como vc fez na `addPointsInScore` =)

Como `quizMessage` é uma função que executa várias ações, eu a renomearia ela descrevendo que ela lida com o envio do form: `handleFormSubmit` ou `handleAnswersSubmit`.

Outra const que pode ser mais descritiva sobre o que ela armazena é a `message`. Como se trata de uma mensagem que informa a pontuação do usuário, eu a nomearia como `scoreMessage`, `userScoreMessage` ou algo do tipo.

Ao desenvolver uma aplicação, evite também nomear variáveis descrevendo o nome do elemento que elas armazenam, como `div` ou `h1`. Isso por que se depois a `<div>` mudar para `section`, por exemplo, você terá que renomear a const `div`. Para isso não acontecer, você pode nomear essas variáveis descrevendo o que elas armazenam, sem especificar o nome da tag. `div` pode ser renomeada para `quizContainer` e `h1` para `finalScoreContainer`, `scoreContainer` ou `scoreEl` ("El é uma abreviação de "element").

### Linhas em branco

Linhas em branco, quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Seguindo este princípio, eu adicionaria linhas em branco nas linhas 12 e 28.

Quando um bloco de código contém apenas duas linhas, eu quebro este princípio. Afinal, não faz sentido deixar um "buraco" entre apenas duas linhas de código.

☝️ o princípio das linhas em branco é mais uma forma pessoal de como gosto de organizar o código, não uma regra.

---

Novamente, parabéns pelo esforço Nathan =)

As observações acima fizeram sentido?

@BlackS-heep

**Comment by BlackS-heep** [comment]
Ok, muito obrigado pelas dicas Roger, irei aplica-las ao código. Seu curso
é realmente diferenciado, sinto que estou evoluindo constantemente  e o
método ATER tem me ajudado bastante!

Em qui, 6 de mai de 2021 22:51, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Fico muito feliz que esteja percebendo evolução, Nathan. No que eu puder ajudar em sua jornada rumo à fluência, pode contar comigo. 

Vou fechar a issue mas no que precisar, é só abrir uma nova =)

@Nathan-013
