### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6356]
# Modificando estilos CSS (inline)

Vimos anteriormente que quando precisamos alterar uma atributo usamos o `setAttribute`.

Porém esse método substitui o valor anterior.

E para alterarmos o estilo CSS é mais adequado usar o método `.style`.

```js
const title = document.querySelector('h1')

console.log(title.style) // objeto style
console.log(title.style.color) // black
```
E com ele podemos mudar qualquer propriedade de CSS do elemento.
```js
console.log(title.style.color) // black

title.style.color = 'red'
title.style.padding = '10px'

console.log(title.style.color) // red
```

> Todos as propriedades de CSS estão disponíveis para usarmos, porem não podemos usar a mesmo anotação usada no CSS.

```js
console.log(title.style.margin-top) // Error!
```

A maneira certa é escrever em `camelCase`.
```js
console.log(title.style.marginTop) // 10px

title.style.marginTop = '16px'

console.log(title.style.marginTop) // 16px
```

> Porém é mais indicador criarmos uma classe CSS e adicionarmos ou retirarmos do elemento.

**Comment by MivlaM** [comment]
Boa @gvao rumo à fluência! 🔥
