### ISSUE TITLE
Resumo da Aula Código assíncrono em JavaScript - Aula 01-02 da etapa 11

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#6357]
O JavaScript é sincrono ou seja executa uma instrução por vez de cima p/ baixo. E uma linguagem Single Thread = 'fio' ou linguagem de um único fio. Código assíncrono em JS, entende-se como o JavaScript executa operações que levam um certo tempo para serem concluídas, tipo buscar dados em uma API ou em um banco de dados. Resumidamente, operação assíncrona é um código que inicia um processo agora e finaliza esse processo posteriormente.

**Comment by MivlaM** [comment]
Boa @Dieison37 rumo à fluência! 🔥
