### ISSUE TITLE
Dúvida com relação ao que foi pedido no exercício

### ISSUE THREAD

**Issue by PauloRDev** [roger-melo-treinamentos/curso-de-js-roger-melo#6366]
### Etapa da aula

3

### Nome da aula

Utilizando callbacks e exercícios - Aula 02-05

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6370914

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Não consegui compreender de forma clara o que foi pedido, é o index de 1 parâmetro em outro
ou o index de cada um dos parâmetros?

/*
  04

  - Crie uma função que recebe 2 parâmetros: um caractere e uma string;
  - Ao ser invocada, a função deve retornar o index do caractere na string.
*/

@Roger-Melo

**Comment by Roger-Melo** [comment]
@PauloRDev a função deve retornar o index do caractere na string. 

Se a assinatura da função é `getIndex('a', 'abc')`, ela deve retornar `0`, pq 'a' está no index zero da string 'abc'.
