### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by CodeVitor** [roger-melo-treinamentos/curso-de-js-roger-melo#6368]
<h1> Condicional switch </h1>

+ Quando uma condição pode haver muitos possiveis valores, fica repetitivo usar else if, então para isso pode se usar o switch statement

+ switch é uma maneira de verificar possiveis valores de uma var ou const

<h2> No exemplo abaixo o switch vai verificar os possivel valores dessa const, e cada possivel valor vai em uma case, o break serve para interromper, se nao colocasse o case iria aparecer no console.log todas os valores no caso iria aparecer do B ate o default. O default é o ultimo e serve pra no caso nao tiver nenhum valor definido.

```js

const grade = 'B'

switch (grade) {
   case 'A':
      console.log('Você tirou um A') 
      break
    case 'B':
      console.log('Você tirou um B') 
      break
    case 'C':
      console.log('Você tirou um C') 
      break
    case 'D':
      console.log('Você tirou um D') 
      break
    case 'E':
      console.log('Você tirou um E') 
      break
     default:
       console.log('nota invalida')
}
```

**Comment by MivlaM** [comment]
Show @CodeVitor. Vamo que vamo, rumo à fluência! 🙌
