### ISSUE TITLE
Aplicação: To-do list

### ISSUE THREAD

**Issue by dev-pedro** [roger-melo-treinamentos/curso-de-js-roger-melo#6375]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Não

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/dev-pedro/todo-list

### Maiores dificuldades durante a implementação

#
Tentei fazer a implementação proposta com dataset e atributos data porem tive dificuldades mesmo pesquisando na internet e vendo algumas aplicações não entendi muito bem.

### Menores dificuldades durante a implementação

#
Já estou me acostumando com eventos de formularios e com métodos como o `filter`, `forEach`, `map`, `reduce`.
:) muito obrigado pelo meu avanço. S2

**Comment by MivlaM** [comment]
Olá, @dev-pedro.

Eu abri a aplicação mas identifiquei que o primeiro dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

> ### Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula.

Isso é fundamental para que a sua versão da aplicação tenha uma aparência própria. Uma sugestão aqui, para deixar sua aplicação ainda mais única, é que você também troque os to-dos, eles não necessariamente precisam ser: "Assistir Breaking Bad, planejar aulas e fazer exercícios físicos", mas nesse caso, é apenas uma sugestão mesmo, para as cores, é um critério. Se quiser, você pode usar o bootstrap para evitar investir muita energia no design da interface.

Os critérios e regras para que a análise seja feita foram enviados no email "[Alunos CJRM] Análises de Aplicações". 

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by MivlaM** [comment]
Olá @dev-pedro

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá, @dev-pedro.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Tentei fazer a implementação proposta com dataset e atributos data porem tive dificuldades mesmo pesquisando na internet e vendo algumas aplicações não entendi muito bem.

Sem problemas. Parte do desafio era fazer você exercitar e pesquisar o assunto.

Você ainda vai aprender mais sobre os atributos data nas próximas aulas, mas em resumo, não é bom usar `parentElement`, pois é um design de código que tende a ser frágil. Se futuramente a marcação html dessa aplicação mudar e o `parentElement` não for mais o elemento que você tinha em mente quando escreveu o código, o seu código quebra. O que não acontece quando você usa os atributos data. Mas de certa forma, não há problema em usá-lo nesse momento do treinamento, mas nas próximas aulas você também vai poder aprender mais sobre o porquê e como usar atributos data-* em suas aplicações =)

Antes de começar a análise, gostaria de te parabenizar por ter focado em escrever um código mais simples que a aplicação anterior. Dessa vez, você realmente mandou bem com essa aplicação baseando-se no que viu no CJRM =)

---

## Nome das funções

Ao longo do seu código, percebe-se um padrão de nomeação em algumas funções, essas que estão iniciando com "event": `eventsSubmit`, `eventTodosContainer` e `eventInputSearchTodo`. Na verdade, um bom princípio é fazer com que essas funções também comecem com verbos. Por exemplo: `addTodo`, `removeTodo` e `searchTodo` respectivamente. Você já deve ter visto esse princípio:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Dito isso, nesse caso em específico, essas três funções não são necessárias para o funcionamento do código, você pode simplesmente reaproveitar as funções que você já declarou anteriormente, o código não vai perder em legibilidade e você poderá economizar algumas linhas ao reaproveitar e referenciar as funções existentes. Ficaria assim:

```js
// antes
const eventsSubmit = event => {
  // ...
}

const eventTodosContainer = event => {
  // ...
}

const eventInputSearchTodo = event => {
  // ...
}

formAddTodo.addEventListener('submit', eventsSubmit)
todosContainer.addEventListener('click', eventTodosContainer)
inputSearchTodo.addEventListener('input', eventInputSearchTodo)
```  

```js
// depois
formAddTodo.addEventListener('submit', addTodo)
todosContainer.addEventListener('click', removeTodo)
inputSearchTodo.addEventListener('input', searchTodo)
```

---

## toLocaleLowerCase e toLowerCase

No seu código, você usou o `toLocaleLowerCase`, a respeito disso, vale a seguinte observação:

"Locale" é um set de preferências de um idioma para uma interface de usuário.

Na maioria das vezes, `toLocaleLowerCase()` e `toLowerCase()` vão retornar o mesmo resultado.

Para alguns locales, como o Turkish, que não tem mapeamento de cases (minúsculos e maiúsculos) em Unicode, pode haver um output diferente. Mas, na maioria dos idiomas, `toLocaleLowerCase()` e `toLowerCase()` retornam o mesmo resultado. Isso também vale para `toLocaleUpperCase()` e `toUpperCase()`.

Não sei se você pegou esse método pela sugestão do VSCode ou pela documentação, pois ele não é ensinado no CJRM. Você pode fazer a mesma coisa que ele faz por meio do `toLowerCase` e ainda vai escrever menos, pois é um nome mais curto. Quanto às sugestões do VSCode, recomendo que ignore. Ou melhor, remova.

Perceba que durante as aulas, as sugestões não são usadas muito menos autocomplete. O ideal é o aluno fazer o mesmo.

Quando alguém está em fase de aprendizado da linguagem, essas parafernalhas mais atrapalham do que ajudam.

Para remover recomendações e autocomplete do VSCode, pressione "ctrl+shift+p" para que a command pallete seja exibida. Insira "settings", escolha a opção "Open Settings (JSON)" e deixe os valores das chaves abaixo como `false`:

```json
  "editor.suggestOnTriggerCharacters": false,
  "editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
  },
  "editor.parameterHints.enabled": false,
```

Feito isso, a sugestão aqui é que você pode substitua o `toLocaleLowerCase` pelo `toLowerCase`:

```js
// antes
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLocaleLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
    })
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLocaleLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
}
```

```js
// depois
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('d-flex')
      todo.classList.add('hidden')
    })
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    .forEach(todo => {
      todo.classList.remove('hidden')
      todo.classList.add('d-flex')
    })
}
```

---

## Método trim na busca para buscar o to-do

Algo que pode ser útil, seria usar o método trim para remover os espaços em branco de uma eventual busca do todo. Sabendo que o método trim remove os espaços em branco do início e fim de um texto, ele pode ser usado para evitar com que um espaço em branco inserido acidentalmente, por exemplo, prejudique a busca de um nome. Ficaria assim:

```js
// antes
const searchTodo = event => {
  // ...
  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLowerCase().includes(inputValue))
    // ...
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().includes(inputValue))
    // ...
}
```

```js
// depois
const searchTodo = event => {
  // ...
  Array.from(todosContainer.children)
    .filter(todo => !todo.textContent.toLowerCase().trim().includes(inputValue))
    // ...
  Array.from(todosContainer.children)
    .filter(todo => todo.textContent.toLowerCase().trim().includes(inputValue))
    // ...
}
```

---

## searchTodo

Para a função `searchTodo`, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

Vamos aproveitar parte do código que você escreveu e vamos inserir essa parte numa função `searchTodo`. Até o momento, temos uma const `todos` que contem as lis que representam os todos e a const `value` será renomeada para `inputValue`, um nome mais específico para a variável que recebe o valor escrito pelo usuário. Aqui, vale a sugestão de adicionar o método `trim()`, caso o usuário insira, acidentalmente, um espaço em branco no final, por exemplo.

```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
}
```

Feito isso, podemos percorrer cada um dos todos por meio do forEach, e após isso, podemos criar uma const `shouldBeVisible` que irá armazenar um boolean indicando se a li do todo deve ficar vísivel ou não dependendo do que o usuário escrever, depois disso, podemos manipular as classes dos to-dos considerando `shouldBeVisible`. Ficaria assim:

```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  todos.forEach(todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  })
}
```

---

Mas, tenha em mente que o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação de um código que já funciona =)

Após todas essas refatorações, o código reduziu de 60 linhas para 45, uma redução de 15 linhas! =)

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by dev-pedro** [comment]
Olá @MivlaM, cara muito obrigado pelas dicas e pela atenção dedicada, eu li todas a sua análise e coloquei em prática todas as dicas que você me deu, gostei bastante das dicas de nomear as funções, é difícil conciliar muita coisa ao mesmo tempo pois já estou com 44 e muitas responsabilidades em paralelo com a família e o trabalho que inclusive éoutra área, mas estou me esforçando o rítimo de estudo as vezes diminui mas sempre que sobra um tempo volto aos estudos.
Mais uma vez muito obrigado, tenho aprendido muito com vocês, sou grato a Deus, pelo Roger, por você e toda a equipe do CJRM.
Da minha parte você pode fechar essa issue. Muito obrigado.

**Comment by MivlaM** [comment]
Ok! Vou fechar essa issue aqui, mas qualquer coisa, sinta-se livre para abrir uma nova caso tenha alguma outra dúvida ou dificuldade em entender algum outro assunto, estarei aqui para te ajudar =)
