### ISSUE TITLE
Resumo da Aula Criando um objeto literal - Aula 01-03 da etapa 04

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6382]
Os objetos literais permitem a criação de objetos simples de maneira fácil, dispensando a necessidade de se definir uma classe ou função construtora.

Para criar um objeto literal, é necessário, declarar uma variável para armazenar o objeto. Em seguida, utilizamos as chaves {} para criar o objeto literal. Dentro das chaves, especificamos as propriedades do objeto e seus respectivos valores, separados por dois pontos ":". Com essa notação de atribuição, definimos a estrutura do objeto e podemos utilizá-lo em nosso código.

```
let user = { 
	name: 'joão',
	age: 31,
	email: 'joaocardoso@gmail.com'
	city: 'São Paulo',
	blogPosts: ['empadão de frango', '4 receitas de purê de batata'
}
```
Cada propriedade e separada por virgula. 

---
 - Acessando o objeto com a notação de ponto.
Notação de ponto é uma forma de acessar as propridedade de nosso objeto. Usamos o nome do objeto seguido de ponto "."  e o nome da propriedade.
`user.name`

- Modificando o valor da propriedade do objeto.
Para modificar o valor de uma propriedade dentro de um objeto, acessamos a propriedade usando a notação de ponto.  Isso significa que escreveremos o nome do objeto seguido de um ponto "." e o nome da propriedade que desejamos alterar. Em seguida, atribuímos o novo valor a propriedade. Por exemplo:
`user.age = 35`
Neste exemplo, a propriedade "age" do objeto "user" foi alterada de 31 para 35, usando a notação de ponto para acessá-la.

- Notação de couchetes []
A notação de colchetes '[]' é uma forma alternativa de acessar as propriedades do objeto. Ao invés da notação de ponto, escrevemos o nome do objeto seguido de colchetes e dentro dos colchetes escrevemos o nome da propriedade desejada, escrito com aspas. Por exemplo:
`user['name']`

- Para modificar um valor utilizando a notação de [], é necessário acessar o elemento desejado do objeto e, em seguida, atribuir o novo valor ao mesmo. 
`user['name'] = 'José'`

 - Se inserirmos no `console.log(typeof user)`, obteremos o tipo do objeto, que no caso é 'object'.

**Comment by MivlaM** [comment]
Show @dev-jefferson-lopes. Vamo que vamo, rumo à fluência! 🙌
