### ISSUE TITLE
Resumo da Aula Testando padrões de regex - Aula 01-05 da etapa 06

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6386]
# Testando padrões de regex

Agora para testarmos esses padrões de `regex`, podemos declarar em uma variável.

## .test
usando o método `.test`, que retorna um `boolean`.
```js
const string = 'Yuri'
const pattern = /ˆ[a-z]{6,}$/

pattern.test(string) // false
```

## .search
E podemos testar também pela string:
```js
const string = 'doiyurigal'
const pattern = /[a-z]{6,}$/

string.search(pattern) // 3
```
neste método recebemos o índice da expressão que deu match com o regex

caso não de match retorna `-1`.

**Comment by MivlaM** [comment]
Show @gvao. Vamo que vamo, rumo à fluência! 🙌
