### ISSUE TITLE
Aplicação: QUIZ DR HOUSE

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6389]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

Repositório: https://github.com/dzpoke/Projeto-Quiz.git

### Maiores dificuldades durante a implementação

Olá!

Minha maior dificuldade foi fazer o maldito poup-pop, não consegui fazer igual o que foi apresentado na etapa 5 do curso e era o que  mais queria fazer para aplicar o  stop propagation queria ter a mesma interação quando um click acontecesse fora do poup-pop o mesmo fosse fechado. Creio que eu seu tivesse revisto a aula para tentar fazer talvez eu conseguisse mas como eu queria fazer tudo só puxando a memória ou consultando a MDN acabei utilizando o setTimeout de 5 segundos para fazer ele sumir, não era o que eu queria mas pelo menos consegui entregar a interação

O Bootstrap foi chatinho de fazer, não consegui deixar os checks alinhados da maneira que eu queria eles acabaram ficando desalinhados puxados um pouco para a direita.

### Menores dificuldades durante a implementação

HTML não encontrei problemas

CSS acabei utilizando um pouco na hora de fazer o poup-pop porque não sabia como fazer no bootstrap

**Comment by MivlaM** [comment]
Olá @dzpoke.

Antes de começar o processo de análise da sua aplicação, verifiquei a sua aplicação e identifiquei que um dos critérios para que a análise seja feita está em falta.

O critério é o seguinte:

## Critério 3: A aplicação só deve conter funcionalidades da linguagem que você viu no CJRM até o ponto que você está no treinamento;

Na sua aplicação, você usou o `setTimeout` que ainda não foi apresentado no CJRM no momento em que a aplicação deve ser enviada. 

Contudo, acho muito interessante que você tenha procurado na documentação uma solução para fazer o que estava sendo demandado no quiz, porém, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. Foi descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que ainda não foram mostradas nas aulas. A prioridade é fazer funcionar com o que foi mostrado nas aulas, notavelmente até a última aula de construção do quiz antes da demanda para enviar a sua aplicação para análise. 

O que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

Novamente, acredito que é muito interessante que você tenha feito funcionar usando outras funcionalidades, mas no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação. Você pode, por exemplo, se achar necessário, assistir novamente as aulas relativas ao pop-up, se essa for a abordagem que você deseja utilizar para exibir a pontuação, não há um certo ou errado nesse quesito.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by dzpoke** [comment]
@MivlaM 

Quando li o critério 03 entendi que só podia usar o que foi ensinado da etapa 01 a 05  do CJRM, então realmente só posso usar o que foi ensinado na usa de construção do quiz ?

**Comment by MivlaM** [comment]
Olá @dzpoke

Você pode usar qualquer ideia ou abordagem que foi apresentada desde a primeira aula do treinamento até a aula "Exibindo a pontuação - Aula 02-01", da etapa 07, pois é ideal que você envie a aplicação antes de assistir essa aula. Há também um outro critério que indica que a aplicação não tenha nenhuma outra funcionalidade a mais do que aquelas já estabelecidas nas aulas de construção da aplicação, mas a sua aplicação não tem irregularidade nesse critério, é apenas na questão do `setTimeout`. Você ainda vai poder reaproveitar essa sua ideia com o `setTimeout` futuramente, mas, para agora, solicito que o código seja modificado para podermos prosseguir para o processo de análise =)

**Comment by dzpoke** [comment]
@MivlaM

**Comment by MivlaM** [comment]
Olá @dzpoke

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by dzpoke** [comment]
@MivlaM obrigado pelo feedback!

Tudo ficou bem claro. 

Agora me tira uma dúvida, devo aplicar essas melhorias ou continuar assistindo as aulas das próximas etapas e volta futuramente refazendo esse projeto ?

**Comment by MivlaM** [comment]
Olá @dzpoke

Bem a decisão final é segundo o seu próprio critério, a sugestão que eu posso lhe dar é a seguinte, eu recomendo que você faça as alterações da análise na aplicação antes de assistir as próximas aulas, principalmente aquelas observações que que você achar mais pertinente para o seu código. Pois logo, você verá outras abordagens e ideias mostradas em vídeo para usar no código dessa aplicação e de certa forma elas complementarão o que você viu aqui na análise. Você também pode, a qualquer momento, refazer a aplicação novamente com os novos conceitos que você for aprendendo ao longo do treinamento, e posso lhe adiantar que, há muito conteúdo legal que pode ser usado nessa aplicação que você ainda vai ver nas aulas futuras.

**Comment by MivlaM** [comment]
Vou fechar a issue aqui, mas qualquer coisa, sinta-se livre para abrir uma nova.
