### ISSUE TITLE
Resumo da Aula Booleans e comparações - Aula 04-02 da etapa 01

### ISSUE THREAD

**Issue by Latorreander** [roger-melo-treinamentos/curso-de-js-roger-melo#6391]
**BOOLEANS***

```js
console.log(true, false, 'true', 'false');
```

 Usamos booleans quando presisamos verificar ou obter alguma condição true ou false  no código, em algum momento presisamos chegar se um pedaço de código é verdadeiro ou falso

 Métodos podem retornar booleans
```js
const email = 'brucewayne@rogermelo.com.br'
const includes = email.includes('wayne')
const names = ['dio', 'roger', 'robert']
const arrayIncludes = names.includes('roger')
const numbers = [1, 2, 4, 5]
const includesNumbers = numbers.includes(7)
console.log(includesNumbers)

console.log(includes)
```

O Método includes pode ser usado tanto em string, numbers como em arrays, ele verifica se existe a ocorrência de um determinado caractere ou elemento

Quando é usado em arrays ele irá tentar dar um match entre o valor passado por argumento e algum elemento do array

**Operadores de comparação**

```js
const age = 31
const name = 'roger'
 console.log(age == 31);
 console.log(age == 35);
 console.log(age != 31);
 console.log(age > 31);
 console.log(age < 32);]
 console.log(age <= 31);
 console.log(age >= 31);

console.log(name == 'roger');
console.log(name == 'Roger');
```

Quando comparamos se duas strings são maiores ou menores, o JS se baseia na primeira letra de cada elemento sendo que a primeira letra do alfabeto tem um peso menor que as subsequentes, ou seja 'A' é menor que 'B' e por sua vez é menor que 'C' e assim por diante. Pode parecer contra intuitivo mas uma letra minúscula é maior que uma maiúscula no JS
```js
console.log(name > 'belinha');
console.log(name > 'Roger');
console.log(name > 'Belinha');
```
**COMPARADORES COM IGUALDADE ESTRITOS**
```js
console.log(age == 31);
 console.log(age == '31');

 console.log(age != 31);
 console.log(age != '31');
```
 Nesse caso o js está dizendo que o number 31 é igual a string '31', porque duplo sinal de igual só está comparando o valor e não o tipo, é feito uma conversão dessa string pra number e resulta em true, essa conversão é feita por debaixo dos panos

 Executar comparações com os operadores 'igual a' e 'diferente de' não são a forma mais confiável de comparar valores, o ideal é usar 3 sinais de igual ou um sinal de exclamação e dois sinais de igual ambos sinais comparam valor e tipo: !== , ===('não idêntico a' e 'idêntico a') tmabém chamado de strict comparation ou comparação estrita
```js
console.log(age === 31);
console.log(age === '31');
console.log(age !== 31);
console.log(age !== '31');
```

**Comment by MivlaM** [comment]
Show @Latorreander. Vamo que vamo, rumo à fluência! 🙌
