### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6392]
Os objetos são conjuntos de dados e funcionalidades relacionadas. Os objetos também podem ter métodos, que são como funções que manipulam e executam ações no objeto.
Para criar um método, declaramos o nome da propriedade que recebe uma função que executa alguma ação, como no exemplo a seguir:
`login: function() {}`
Podemos criar quantos métodos forem necessários para a aplicação, separando-os por vírgulas.

As funções que são criadas dentro do objeto recebem o nome de métodos e são invocadas usando a notação de ponto, como no exemplo a seguir:
`user.login()`
Já estamos familiarizados com a invocação de métodos. Um exemplo de método é o toUpperCase, que é um método criado dentro do objeto string e converte a string em letras maiúsculas.

**Comment by MivlaM** [comment]
Show @dev-jefferson-lopes. Vamo que vamo, rumo à fluência! 🙌
