### ISSUE TITLE
Resumo da Aula 09-03da etapa 11

### ISSUE THREAD

**Issue by Beninigmal** [roger-melo-treinamentos/curso-de-js-roger-melo#6394]
<h1 align="center">Requests Paralelos Vs Sequenciais</h1>

Observe o código abaixo:

```js
const getPokemons = async () => {
  const bulbasaur = await fetch(https://pokeapi.co/api/v2/pokemon/1)
  const charmander = await fetch(https://pokeapi.co/api/v2/pokemon/4)
  const squirtle = await fetch(https://pokeapi.co/api/v2/pokemon/7)

  console.log(await bulbasaur.json())
  console.log(await charmander.json())
  console.log(await squirtle.json())
}

getPokemons()
```

Esse código irá mostrar sequencialmente os 3 pokemons no console, porém essas chamadas não são dependentes uma da outra, ou deixando mais claro, charmander não deveria depender da resposta do bulbasaur para poder ser executado, e sim, em muitas aplicações vai surgir a necessidade de a depender do resultado de uma api seja invocado outra que depende da resposta da primeira e isso é um request sequencial. No caso acima, como existe um await no bulbasaur, somente após sua resolução é que a linha abaixo será liberada e para resolver isso podemos transformar essa request em paralela da seguinte maneira:

```js
const getPokemons = async () => {
  const bulbasaur =  fetch(https://pokeapi.co/api/v2/pokemon/1)
  const charmander = fetch(https://pokeapi.co/api/v2/pokemon/4)
  const squirtle =  fetch(https://pokeapi.co/api/v2/pokemon/7)

  const result = await Promise.all([bulbasaur, charmander, squirtle])

  result.forEach(async response => console.log( await response.json()))
}

getPokemons()
```

Trocando em miúdos, todos os fetchs efetuados, serão executados quase que instantâneo e utilizaremos o método Promise.all. esse método irá receber um array com todas as requisições e cada posição irá receber seu resultado seja de response ou error, e como esses resultados ainda são uma promessa, podemos resolver adicionando um await  antes do Promise.all.
como result agora é um array podemos usar um forEach para usando o async e await trazendo o método json() desse resultado. Assim o resultado virá paralelo e um não dependerá do outro.

**Comment by MivlaM** [comment]
Show @Beninigmal. Vamo que vamo, rumo à fluência! 🙌
