### ISSUE TITLE
Retorno de NaN invés de undefined 

### ISSUE THREAD

**Issue by giovannirp** [roger-melo-treinamentos/curso-de-js-roger-melo#6396]
### Etapa da aula

1

### Nome da aula

02-01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/aula/6706689

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

```js
  const multNumbers = function(numberOne, numberTwo) {
    const numbers = numberOne * numberTwo;
    return numbers;
  }
  
  const resultNumbers = multNumbers(3, 3);
  
  console.log(resultNumbers);

```

Olá tudo bem, estou com uma duvida, durante o exercício, fiz os retornos e percebi que nesse caso se eu não passar nada nos argumentos, é retornado um NaN e não um undefined, não entendi muito o por que nesse caso acontece isso.

Obrigado! 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @giovannirp! 

Isso mesmo, se uma função tem um parâmetro e nada é inserido como argumento na invocação dela, o parâmetro recebe `undefined`.

```javascript
function myFunc (param) {
  console.log(param) // undefined
}

myFunc()
```

Porém, no exemplo que você deu, além de receber `undefined`, o parâmetro está sendo usado em uma operação matemática. 

Quando `undefined` é usado em uma operação matemática, o retorno dessa operação será NaN (not a number), por que por baixo dos panos o JavaScript entende que `undefined` não é um valor que deve ser usado em uma operação matemática.

```javascript
function myFunc (param) {
  console.log(param) // undefined
  console.log(param * 5) // NaN
}

myFunc()
```

Tem uma aula em que eu falo sobre isso. Você ainda chegará nela =)

**Comment by giovannirp** [comment]
Oi @Roger-Melo, 

Obrigado, ficou muito claro.
