### ISSUE TITLE
Etapa 03 - Funções e Métodos

### ISSUE THREAD

**Issue by rodrigocavalcantef** [roger-melo-treinamentos/curso-de-js-roger-melo#6397]
### Etapa da aula

1

### Nome da aula

Retornando valores e exercícios - Aula 01-05

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706691

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

@Roger-Melo tive dificuldade em 4 dos 7 exercícios da etapa. Pelo pouco que foi explicado na aula de retorno de valores anterior à bateria de exercícios, me senti um pouco perdido. Estou assistindo ao módulo novamente e refazendo os exercícios. Mas como foram muitos, fiquei um pouco preocupado e não quero deixar isso virar uma bola de neve para das demais etapas. Você me aconselha dar uma lida na documentação? O que posso fazer pra compreender essa parte melhor? Obrigado!

**Comment by Roger-Melo** [comment]
@rodrigocavalcantef não fique muito preocupado em acertar tudo de primeira. 

Quando surgir alguma dúvida ou dificuldade, abra uma issue ou ainda melhor, peça ajuda no grupo dos alunos no Telegram. O link está na Etapa 00 =)

**Comment by Roger-Melo** [comment]
Vou fechar a issue, mas no que precisar, é só abrir uma nova
