### ISSUE TITLE
Etapa 14, nome do vídeo: Correção exercicios aula 02 etapa 14.

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#640]
Olá Roger, tudo bem? a dúvida em sí é não sobre a aula, mas sim, algo que citou constantemente na correção dos exx. Por que é tão importante evitar mutação de variaveis? Ficou essa dúvida 😄 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel!

Tudo certo, e contigo? 

Imutabilidade é um fundamento da programação funcional e um código mais funcional é mais fácil de testar, debugar e manter. Atualmente, várias libs JS populares são inspiradas nessa abordagem.

Ainda irei separar um momento para falar apenas sobre programação funcional em etapas mais avançadas do treinamento. Mas se você tiver estiver sacando bem a minha forma de desenvolver até aqui, não vai ter grandes dificuldades quando entrarmos no assunto =)

Enquanto isso, vou deixar abaixo algumas fontes que inclusive vão responder sua dúvida e dar um bom panorama de FP:

- [Master the JavaScript Interview: What is Functional Programming?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0)
- [Why is immutability so important (or needed) in JavaScript?](https://stackoverflow.com/questions/34385243/why-is-immutability-so-important-or-needed-in-javascript)
- [The problems of shared mutable state and how to avoid them](https://2ality.com/2019/10/shared-mutable-state.html)

Se ainda tiver alguma dúvida, ou problemas pra entender os posts em inglês, é só avisar =)

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
Valeu Roger!!!!
