### ISSUE TITLE
Por que eu não consigo usar o join(' ') para esse caso?

### ISSUE THREAD

**Issue by giovannirp** [roger-melo-treinamentos/curso-de-js-roger-melo#6410]
### Etapa da aula

3

### Nome da aula

Retornando valores e exercícios 

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/aula/6706690

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa tarde, tudo bem?

Estou com uma duvida em uma resolução de um exercício, para separar o caracteres estou usando templates string, gostaria de saber por que nesse caso, não consigo usar join(' ') pra separar.

```js
let textPrase = '';

for (let i = 0; i < functions.length; i++) {
  textPrase += `${functions[i]()} `;
}

console.log(textPrase);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @giovannirp. E qual parte do código vc está usando `join`? Não encontrei no código que você postou acima. 

De qualquer forma, o `join` tem esse nome (juntar) por que ele une itens de um array. É isso o que você quer fazer?

**Comment by Roger-Melo** [comment]
@giovannirp `join` é método de array. Por isso a mensagem do erro diz "join is not a function".

`functions[i]()` retorna uma string, não um array. Você pode visualizar isso com um console.log e olhando no console do devtools:

```javascript
for (let i = 0; i < functions.length; i++) {
  console.log(functions[i]()) // Plymouth...
}
```

![image](https://user-images.githubusercontent.com/29297788/228843712-3f7cee54-d7c5-47f1-aafa-a9b7bfeb484f.png)

Use e abuse do `console.log`, vai te ajudar muito a visualizar valores em seu código.

**Comment by Roger-Melo** [comment]
Boa. No que precisar, é só abrir uma nova issue.
