### ISSUE TITLE
Dúvida em como fazer o exercício - 07

### ISSUE THREAD

**Issue by Dieison37** [roger-melo-treinamentos/curso-de-js-roger-melo#6412]
### Etapa da aula

1

### Nome da aula

Exercícios da aula 01

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/1157211

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa tarde Roger!

Estou com uma dúvida em como fazer o exercício-07 pois lá diz que é para criar um método que adiciona livros em uma caixa, mas não estou compreendendo como deve criar esse método. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Dieison37. 

Existem várias maneiras de criar um método em um objeto

Acredito que nesse pondo do CJRM, vc verá eu fazer na correção do exercício algo desse tipo:

```javascript
const obj = {
  prop: 'abc'
}

// 👇🏻 propriedade myMethod recebe uma função. Função atribuída à propriedade de objeto é um método
obj.myMethod = () => {} 

// 👇🏻 myMethod está disponível para ser usado
console.log(obj) // { prop: 'abc', myMethod: () => {} }
```

**Comment by Roger-Melo** [comment]
@Dieison37 o método deve ser adicionado no objeto `booksBox`. Dá uma olhada como foi feito na resolução =)

**Comment by Dieison37** [comment]
Bom dia Roger!

Certo, vou conferir na resolução.
Obrigado.






Att.
DIEISON L. VIEIRA.


Em qui., 30 de mar. de 2023 às 22:32, Roger Melo ***@***.***>
escreveu:
