### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03 da etapa 03

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#6415]
## Function declaration, function expression e hoisting

> Function declaration: Uma function declaration deve ter um nome. As function 
> 
> Function expression: O nome da função pode ser omitido, neste caso a função será anônima. A função é atribuída a uma variável ou constante. 
> 
> Hoisting: Significa “içamento”, ou “elevação”.  O Hoisting permite que você execute funções antes das suas declarações, pois é disponiobilizada  ​​“no topo” do seu código.

### Sintaxe básica: Function declaration

```js
function soma(a, b) {
    return a + b
};
```

### Sintaxe básica: Function expression

```js
const soma = function(a, b) {
    return a + b
};
```

### Sintaxe básica: Hoisting

```js
console.log(soma(2, 5))

function soma(a, b) {
    return a + b
}
```

<!-- ### Exemplo:

> Descrição do exemplo

```js

```

> console

```js

``` -->

<!-- Escreva/insira as imagens após essa linha -->

**Comment by MivlaM** [comment]
Boa @Geisonszo rumo à fluência! 🔥
