### ISSUE TITLE
Resumo da Aula Objetos em arrays - Aula 03-02 da etapa 04

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6420]
Dentro de um array, podemos criar vários objetos. Para isso, basta declarar um array vazio [] e adicionar objetos usando chaves {}. Cada objeto deve ser separado por vírgula e contém suas próprias propriedades, valores e métodos. É possível acessar esses objetos normalmente usando a notação de ponto.

**Comment by MivlaM** [comment]
Boa @dev-jefferson-lopes  rumo à fluência! 🔥
