### ISSUE TITLE
Resumo da Aula While loop e exercícios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by tiagojunio** [roger-melo-treinamentos/curso-de-js-roger-melo#6426]
Resumo aula  While loop e exercícios - Aula 01-04

A instrução while cria um loop que executa uma instrução específica desde que a condição de teste seja avaliada como verdadeira. A condição é avaliada como verdadeira. A condição é avaliada antes de executar a instrução.

Sintaxe
```js
while (condition){
statement
}
```
condition - uma expressão avaliada antes de cada passagem pelo loop. Se esta condição for avaliada como verdadeira, a instrução será executada. Quando a condição é avaliada como falsa, a execução continua com a instrução após o loop while.

statement - Uma instrução opcional que é executada desde que a condição seja avaliada como verdadeira. Para executar várias instruções dentro do loop, use uma instrução de bloco para agrupar essas instruções.
```js
while (n < 3){
statement
//bloco de instrução
n++;
}
```

```js
const names = [‘Jobs’, ‘Hopper’, ‘Turing’,];
let i = 0;
while (i < names.length){
i++
console.log(names[i]);
}
```

**Comment by MivlaM** [comment]
Boa @tiagojunio rumo à fluência! 🔥
