### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6429]
Os tipos primitivos são Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt. Já os tipos de referência são qualquer tipo de objeto, como objetos literais, arrays, funções, datas e todos os outros objetos.
	
A principal diferença entre eles é a forma como são armazenados na memória. Os valores primitivos são armazenados diretamente na stack, que é mais rápida, mas tem um espaço limitado. Por outro lado, os tipos de referência, como arrays e objetos, são armazenados na heap, que tem mais espaço disponível, mas é mais lenta.
	
Quando atribuímos um valor primitivo, como uma string, número ou booleano, a uma variável, o valor é armazenado diretamente na memória da pilha (stack) e pode ser acessado pelo nome da variável. Porém, quando atribuímos um objeto, um array ou outro tipo de referência a uma variável, ele é armazenado na memória heap, enquanto um ponteiro para o objeto é criado na stack. Então, essa variável conterá uma referência para o objeto em vez do objeto em si. Dessa forma, quando acessamos a variável, ela segue o ponteiro até o objeto na memória do heap e recupera seus valores. 
	
- Comportamento do tipos de refêrencia e tipos primitivos ao tentarmos atribuí-las:

Se criarmos uma variável com um valor primitivo e atribuirmos essa variável a outra variável, teremos duas stacks independentes na memória e com possição diferente. Isso significa que podemos alterar o valor de uma variável sem afetar o valor da outra.
```
let scoreOne = 50
let scoreTwo = scoreOne
scoreOne = 100
```

Se atribuirmos um objeto a uma variável e, em seguida, atribuirmos essa variável a outra, as duas variáveis ​​estarão apontando para o mesmo objeto na memória. Portanto, qualquer alteração feita em um objeto afetará todos os outros que apontam para ele. 
```
let userOne = {nome: 'Jefferson', score: 100}
let userTwo  = userOne
userOne.score = 50
```
Devemos tomar cuidado ao trabalhar com tipos de referência, pois o comportamento pode não ser o desejado.

**Comment by MivlaM** [comment]
Boa @dev-jefferson-lopes rumo à fluência! 🔥
