### ISSUE TITLE
Resumo da Aula Stringficando e parseando dados - Aula-01-06 da etapa 13

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#645]
## `JSON.stringify()`

Este método é responsável por converter um objeto JavaScript em uma string JSON.

### Argumento

1. Objeto a ser convertido para JSON.
2. Função responsável por alterar o comportamento padrão do processo de conversão. (opcional)
3. Um valor do tipo number ou string que será utilizado para a indentação do JSON a ser gerado. (opcional)

### Retorno

Uma cópia do objeto original em formato JSON.

---

## `JSON.parse()`

É um método responsável por parsear, ou seja, por converter um JSON em um objeto JavaScript.

### Argumento

1. JSON que será parseado.
2. Função responsável por manipular o JSON antes que o objeto seja retornado. (opcional)

### Retorno

Um objeto JavaScript obtido através do parseamento de um JSON.

---

MDN: 

- [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)
- [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)

@Roger-Melo

**Comment by Roger-Melo** [comment]
excelente @sou-gabriel! Rumo à fluência meu caro! 👊🏻
