### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04 da etapa 03

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#6456]
## Argumentos, Parâmetros e Default parameters

> Parâmetros: São as variaveis que irão receber um valor em uma função ou método.
> 
> Argumentos: São os valores que são passados para a função ou método.
> 
> Default parameters: Em JavaScript, um parâmetro tem um valor padrão indefinido. Mas valores podem ser definidos nos paramtros da função

### Sintaxe básica: Parâmetros

```js
function soma(x, y) { // x e y são parametros
    return x + y;
}
```

### Sintaxe básica: Argumentos

```js
soma(4, 5) // 4 e 5 são argumentos
```

### Sintaxe básica: Default parameters

```js
function soma(x=0, y=0) { // x e y recebem o valor 0 caso não seja passado argumentos
    return x + y;
}

soma() // Retorna 0
```

**Comment by MivlaM** [comment]
Excelente @Geisonszo, rumo à fluência! 🎯
