### ISSUE TITLE
Aula 04 da etapa 01 - Aula 01-01 etapa 02 correção

### ISSUE THREAD

**Issue by rfalfieri** [roger-melo-treinamentos/curso-de-js-roger-melo#6459]
A forma de correção aplicada ao exercício da aula 4, para este caso creio não ter ficado funcional, pois prende a solução ao último item do array, ao qual se alterado não irá mais funcinar.

const my3FavoriteTVShows = ['GOT', 'Rick and Morty', 'TWD']

/*Solução da aula

const sentence = `Minhas 3 séries favoritas são: ${my3FavoriteTVShows.join(', ')}`.replace(', T', ' e T')
*/
/*Minha solução, que pode incluir/alterar itens do array e somente alterando os valor do slice(posições)

const sentence = `Minhas 3 séries favoritas são: ${my3FavoriteTVShows.slice(0,2).join(', ')} e ${my3FavoriteTVShows.slice(2, 3)}`
*/
/*
O que acham sobre para soluções até esta etapa?
Teremos tratativas mais fáceis para estes casos?
*/

**Comment by MivlaM** [comment]
Excelente @rfalfieri, rumo à fluência! 🎯
