### ISSUE TITLE
Aplicação: Quiz planetário

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6462]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Sim

### Link do repositório da aplicação (ou pasta pública no Google Drive)

gvao.github.io/quiz-planetario/

### Maiores dificuldades durante a implementação

 1. E tive muita dificuldade com o `Bootstrap`, pois ainda não entendi muito bem sobre as classes.

 2. Minhas maior dificuldade foi validar as respostas erradas do usuário.

### Menores dificuldades durante a implementação

Foi inserir a pontuação

**Comment by MivlaM** [comment]
Olá @gvao

Vc abriu uma issue com o template `🔥aplicação`, mas apenas quem se inscreveu entre às 7:45h e 8:45 do primeiro dia de abertura tem o bônus de análise de aplicações. E pelo que vi, sua inscrição foi feita no segundo dia.

O que vc pode fazer neste caso é dar uma olhada nas análises feitas dessa aplicação. Elas são públicas =)

E claro, qualquer dúvida que tiver, é só dar o toque =)

OBS: Agora que vi que você fez um comentário sobre uma dúvida numa issue fechada, por favor, sempre que estiver com alguma dúvida, abra uma issue de dúvida, estou falando isso porque nós não somos notificados quando o comentário é feito em uma issue fechada. Portanto, prefira sempre usar o recurso das issues de dúvidas, ok? =)

**Comment by gvao** [comment]
> Olá @gvao
> 
> Vc abriu uma issue com o template `🔥aplicação`, mas apenas quem se inscreveu entre às 7:45h e 8:45 do primeiro dia de abertura tem o bônus de análise de aplicações. E pelo que vi, sua inscrição foi feita no segundo dia.
> 
> O que vc pode fazer neste caso é dar uma olhada nas análises feitas dessa aplicação. Elas são públicas =)
> 
> E claro, qualquer dúvida que tiver, é só dar o toque =)
> 
> OBS: Agora que vi que você fez um comentário sobre uma dúvida numa issue fechada, por favor, sempre que estiver com alguma dúvida, abra uma issue de dúvida, estou falando isso porque nós não somos notificados quando o comentário é feito em uma issue fechada. Portanto, prefira sempre usar o recurso das issues de dúvidas, ok? =)

@MivlaM Obrigado pelo retorno, sua explicação ficou muito clara, pode deixando que quando surgir próximas dúvidas crio um issue de duvida.

**Comment by MivlaM** [comment]
Ok! Bem, vou fechar essa issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
