### ISSUE TITLE
Resumo da Aula O método sort - Aula 02-02 da etapa 08

### ISSUE THREAD

**Issue by gvao** [roger-melo-treinamentos/curso-de-js-roger-melo#6466]
# O método sort

Usamos este método para ordenarmos um array.

> Ao executar esse método o array original é alterado.

## Ordenando strings

```js
const names = ['Cristian', 'Alfredo', 'Edson']
names.sort() 

console.log(names) //output: ['Alfredo', 'Cristian', 'Edson']
```

## Ordenando Numbers
Porém em quando usamos o `sort()` para ordenar números precisamos usar os parâmetros opcionais.

Pois quando não passamos argumentos ele vai analisar o primeiro caracter.

```js
const scores = [10, 50, 20, 5, 35, 70, 45]
score.sort() 

console.log(scores) //output: [10, 20, 35, 45, 5, 50, 70]
```

Para conseguirmos ordenar conforme queremos usamos os parâmetros da função de callback do método.

```js
scores.sort((score1, score2) => score2 - score1) // ordem decrescente
console.log(scores) //output: [70, 50, 45, 35, 20, 10, 5]
```

## Escolhendo ordem
O callback do método `sort()` precisa retornar um valor `maior`, `menor` ou `igual` a 0.

Quando o retorno for:
1. Maior que zero - coloca o 1 argumento após do 2 argumento 
2. Menor que zero - coloca o 1 argumento antes do 2 argumento 
3. igual a zero - permanecem iguais na ordem 

### Exemplo prático:

Em um array com objetos podemos acessar seus métodos e propriedades.

Definimos o array:
```js
const theBigFamily = [
    { name: 'Lineu', score: 20 },
    { name: 'Nenê', score: 10 },
    { name: 'Tuco', score: 50 },
    { name: 'Bebel', score: 30 },
    { name: 'Agostinho', score: 70 }
]
```

Agora vamos ordena-los de acordo com suas propriedades `score`.
```js
theBigFamily
.sort((item1, item2) => item2.score - item1.score)

console.log(theBigFamily) 
/**
output: [
    { "name": "Agostinho", "score": 70 },
    { "name": "Tuco", "score": 50 },
    { "name": "Bebel", "score": 30 },
    { "name": "Lineu", "score": 20 },
    { "name": "Nenê", "score": 10 }
]
*/
```

**Comment by MivlaM** [comment]
Excelente @gvao, rumo à fluência! 🎯
