### ISSUE TITLE
Resumo da Aula O que são funções - Aula 01-02 da etapa 03

### ISSUE THREAD

**Issue by Thalles17** [roger-melo-treinamentos/curso-de-js-roger-melo#6469]
Funções são parte do tipo de dado object
e o papel principal delas é permitir que criamos um bloco de código podemos declarar e invocar quando quisermos. A forma de interpretamos uma função é de uma caixa que contem um código dentro dela que faz alguma coisa em particular

funções são executadas onde e quando quisermos

escrevemos o código uma vez e esse código se repete quantas vezes quisermos.

**Comment by MivlaM** [comment]
Excelente @Thalles17, rumo à fluência! 🎯
