### ISSUE TITLE
Exercício 04 Etapa 01

### ISSUE THREAD

**Issue by Keydorah** [roger-melo-treinamentos/curso-de-js-roger-melo#6471]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 04 da etapa 01 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/6b300556444e6ff43f4a78991d84996d17c050a9/aula/6706673

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
@Keydorah vc colocou o primeiro bloco em um comentário, por isso não foi renderizado. 

Recomendo que veja novamente a Aula Mais Importante do CJRM, primeira aula na plataforma. Lá eu mostro tim-tim por tim-tim como você deve postar seu código aqui no GitHub. 

---

As suas séries não são as mesmas que eu mostrei na aula, então vc precisa adaptar a resolução pro seu caso. Se for preciso, reveja a aula em que é explicado como o método `replace` funciona. 

A última série do seu array começa com "U" e não com "T", e não há nenhuma série em seu array que comece com "T" maiúsculo. 

Com essas informações, você consegue ajustar o que está errado?

**Comment by Keydorah** [comment]
nossa, era algo tão simples kkk, obrigado. consegui

**Comment by Roger-Melo** [comment]
@Keydorah boa! Vc está no grupo dos alunos do CJRM no Telegram?

**Comment by Keydorah** [comment]
estou sim

**Comment by Roger-Melo** [comment]
Boa! Se quiser mandar as dúvidas por lá, fique à vontade. 

Geralmente lá a resposta vem mais rápido. Mas é só uma dica =)

@Keydorah
