### ISSUE TITLE
Resumo da Aula Null e undefined - Aula 03-03 da etapa 01

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6472]
# Undefined e Null

### Undefined
Quando declaramos uma variável e não atribuímos uma valor para ela, automaticamente JavaScript dá o valor de undefined á variável.

```js
let emptiness;
console.log(emptiness, emptiness + 3, `o valor é ${emptiness}`);            //undefined NaN o valor é undefined
```
Notas: 
- O valor de uma variável que não foi inicializada é endefined. 
- Ao intentar usar undefined numa expressão numérica, o resultado que obteremos será NaN (Not A Number). 
- Quando inserimos uma variável não inicializada dentro de um string, JavaScript converte o valor undefined para uma string (neste caso para a paravra undefined)

### Null

Null é usado quando queremos indicar intencionalmente que uma variável não tem valor

```js
let emptiness = null;
console.log(emptiness, emptiness + 3, `o valor é ${emptiness}`);            //null 3 o valor é null
```
Notas:
- O valor de uma variável que foi inicializada com o valor null é null. 
- Ao intentar usar null numa expressão numérica, o valor null é convertido para 0. 
- Quando inserimos dentro de uma string uma variável com el valor de null, automaticamente JavaScript converte o valor null para uma string (neste caso para a paravra null)

**Comment by MivlaM** [comment]
Excelente @OnielStgo, rumo à fluência! 🎯
