### ISSUE TITLE
Resumo da Aula Palavra this da etapa 04

### ISSUE THREAD

**Issue by giovannirp** [roger-melo-treinamentos/curso-de-js-roger-melo#6476]
Palavra chave this.

Quando a gente usa um this, essa palavra chave vai referenciar um objeto

<img width="521" alt="bloco-codigo" src="https://user-images.githubusercontent.com/10762886/230096151-f24dedba-a65b-4d9a-bf35-450fc51b2b9e.png">

Nesse caso esta referenciando o objeto **user**:

<img width="566" alt="codigo" src="https://user-images.githubusercontent.com/10762886/230096536-63ba02de-e153-4ad8-aa65-587ccb8cb438.png">

O que é a palavra chave this?

O this é um objeto de contexto, ele representa o contexto no qual o código atual esta sendo executado.

E dependendo de onde e como a gente usa o **this**, o valor dele vai mudar

Dessa forma aqui, o this referencia o objeto Window.

<img width="461" alt="bloco-codigo" src="https://user-images.githubusercontent.com/10762886/230100361-7e489aab-3b51-4b4a-8ad0-d5f4c01e576d.png">

<img width="581" alt="codigo" src="https://user-images.githubusercontent.com/10762886/230100558-13984355-25a5-45c8-aba6-7068f81ec76f.png">

Desta forma aqui, o this está referenciando o objeto this:

<img width="443" alt="bloco-codigo" src="https://user-images.githubusercontent.com/10762886/230103466-f612398d-3fd2-4733-a3c2-4305152db2c3.png">

**Comment by MivlaM** [comment]
Boa @giovannirp  rumo à fluência! 🔥
