### ISSUE TITLE
Resumo da Aula O método reduce - Aula 01-04 da etapa 08

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6477]
![image](https://user-images.githubusercontent.com/106329803/230100819-babf9dca-b53a-4243-bb49-cee618a13bb3.png)
![image](https://user-images.githubusercontent.com/106329803/230100903-b2dab854-79b3-4f29-8b2f-7e701756fb43.png)

**Comment by MivlaM** [comment]
Boa @rafael-rodrigues01 rumo à fluência! 🔥
