### ISSUE TITLE
Etapa 12, nome do vídeo: Correção Refatoramento Weather Aplication

### ISSUE THREAD

**Issue by allanpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#648]
Olá Professor. 

Estou com um problema no meu código, após realizado a correção fiz o mesmo refatoramento dos videos de correção, pois ainda assim aparece um erro no fech(url)

```js
const baseUrl = 'http://dataservice.accuweather.com/'
const APIKey = 'pIxhE1xHyIR0ZVZvAOi86bAR2MMbrdUG'

const getCityURL= cityName => `${baseUrl}locations/v1/cities/search?apikey=${APIKey}&q=${cityName}`

const getWeatherUrl= cityKey => `${baseUrl}currentconditions/v1/${cityKey}?apikey=${APIKey}&language=pt-br`

const fetchData = async url => {
    try {
        const response = await fetch(url)

        if (!response.ok) {
            throw new Error('Não foi possível obter os dados!')
        }

        return response.json()
    } catch ({ name, message}) {
        alert(`${name}: ${message}`)
    }
}

const getCityName = cityName => {
    const cityUrl = getCityURL(cityName)
    return fetchData(cityUrl)
}

const getCityWeather = key => {
    const weatherUrl = getWeatherUrl(key)
    return fetchData(weatherUrl)
}

getCityWeather('Curitiba')
```
Segue o erro do console: 

![image](https://user-images.githubusercontent.com/62186548/117539057-21871200-afdf-11eb-8604-15c2e8aa60c4.png)

![image](https://user-images.githubusercontent.com/62186548/117539089-5c894580-afdf-11eb-950a-0c2643ff651c.png)

Se puder me auxiliar, 

Desde já agradeço, bom fds.
Abraços.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Allan. 

Insira um "s" após o "p" do http. Deverá ficar assim: 

```javascript
const baseUrl = 'https://dataservice.accuweather.com/'
```

Se após isso os dados não forem obtidos, suba todos os arquivos em um repositório do github e mande o link, ou poste o código de todos os arquivos aqui (veja o que fica melhor para você). Assim é mais fácil eu reproduzir o erro na minha máquina e ajudar com mais precisão =)

@allanpedro

**Comment by allanpedro** [comment]
Ok professor

segue o link do repositório: https://github.com/allanpedro/weatherAplication.git

Desde já agradeço

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Allan.

O que está causando o erro é a segunda linha do código abaixo:

```javascript
const getCityWeather = key => {
  const weatherUrl = getWeatherUrl(key)
  return fetchData(weatherUrl)
}
```

A url que precisa ser usada nesse request é a que a invocação da `getCityURL` retorna. Se você substituir a invocação da `getWeatherUrl(key)` por `getCityURL(key)`, verá que o erro não é mais lançado:

```javascript
const getCityWeather = key => {
  const weatherUrl = getCityURL(key)
  return fetchData(weatherUrl)
}
```

Se antes do `return` o valor da promise que o request trouxe for exibido no console (e a função for transformada em assíncrona), você verá o array com o objeto com os dados da cidade =)

```javascript
const getCityWeather = async key => {
  const weatherUrl = getCityURL(key)
  console.log(await fetchData(weatherUrl))
  return fetchData(weatherUrl)
}

getCityWeather('Curitiba')
// [{…}, {…}]
```

Pelo que observei, talvez houve um pouco de imprecisão no momento de criação das funções `getCityName` e `getCityWeather`, então seria legal você rever a aula para identificar em qual ponto o equívoco começou a acontecer. E claro, se houver alguma dúvida é só dar o toque =)

Ficou mais claro?

@allanpedro

**Comment by allanpedro** [comment]
Bom dia!

Ficou claro sim, já fiz essas alterações e funcionou, vou rever as aulas. 

Muito obrigado! 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal @allanpedro. No que precisar, é só dar o toque =)
