### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6487]
# Conversão de tipos

Para saber o tipo de uma valor podemos usar typeof:
```js
const valor1= 30;
const valor2= '30';
typeof valor1;      // number
typeof valor2;      // sting
```

Funções construtoras de tipo:
- **Number()**      // converte um valor a tipo numérico
- **String()**      // converte um valor a tipo string
- **Boolean()**      // converte um valor a tipo boolean

Exemplo onde usamos a função construtora Number():
```js
const score = '100';
console.log(score + 1);              //"1001" // aqui se concatenou uma string com um número e o resultado foi uma string
console.log(Number(score) + 1);      // 101

// Se intento converter um valor (que não faz sentido, por ejemplo: "hola") para tipo numérico, vamos a obtener como respuesta un: NaN

const crazyConversao = Number('hola');
console.log(crazyConversao)            // NaN

```

Exemplo onde usamos a função construtora String():
```js
const score = String(100);
console.log(score);               // '100'
console.log(typeof score);          // string
```

Exemplo onde usamos a função construtora Boolean():
```js
const score = 100;
console.log(Boolean(score));           // true
```

### Em JavaScript alguns valores são considerados como falsy (false) ou truthy (true):

Valores falsy:

- false
- 0
- "", '', ``
- null
- undefined
- NaN

Valores truthy:
- Qualquer valor que não é falsy

**Comment by MivlaM** [comment]
Boa @OnielStgo rumo à fluência! 🔥
