### ISSUE TITLE
Resumo da Aula Objeto Math da etapa 04

### ISSUE THREAD

**Issue by giovannirp** [roger-melo-treinamentos/curso-de-js-roger-melo#6489]
Método Math

```js
// o objeto Math
console.log(Math)
console.log(Math.PI)
console.log(Math.E)
```

<img width="386" alt="bloco-codigo" src="https://user-images.githubusercontent.com/10762886/230414117-d3c7f270-b17e-45b6-991d-85bfdb0d43b5.png">

Math round vai fazer , ele converter um numero decimal em um numero inteiro.

```js
const area = 7.7

console.log(Math.round(area))  
// 8
```

Floor sempre vai arredondar um numero para baixo:

```js
const area = 7.7

console.log(Math.floor(area))
// 7
```

Ceil vai arredondar numero para cima:

```js
const area = 7.7

console.log(Math.ceil(area))
// 8
```

Trunc vai remover um decimal de um numero

```js
const area = 7.7

console.log(Math.trunc(area));
// 7
```

Gerando um numero aleatório:
```js
const randomNumber = Math.random();

console.log(randomNumber);

// aqui um numero aleatório de 0 a 100 vai ser exibido no console
console.log(Math.round(randomNumber * 100))
```
 **Exemplos de diferentes abordagem de cada mehodos:**

<img width="282" alt="bloco-codigo" src="https://user-images.githubusercontent.com/10762886/230418520-75484c81-00ba-4adf-8381-f1bb75092a7c.png">

**Comment by MivlaM** [comment]
Boa @giovannirp rumo à fluência! 🔥

**Comment by giovannirp** [comment]
Obrigado @MivlaM, Vamos que vamos.
