### ISSUE TITLE
Resumo da Aula A condicional switch  - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by Latorreander** [roger-melo-treinamentos/curso-de-js-roger-melo#6496]
**A condicional switch **

Para verificar a nota de um aluno poderiamos utilizar um encadeamento de else ifs, note que dessa forma o código fica muito repetitivo

```js

const grade = 'C'

 if (grade === 'A' ){

 }else if(grade === 'B'){

 }
 else if(grade === 'C'){

 }
 else if(grade === 'D'){

 }
 else if(grade === 'E'){

 }

```

 Um a alternativa que podemos usar é o uso do swtich statement, com ele usamos a palavra chave case com as possíveis notas a serem verificadas, quando verificado e se o resultado for true o bloco da expressão é executado cai no break o restante do bloco para, se nenhuma das notas forem iguais, ou seja se não der match o valor da constante com a case de cada expressão, ele cai no default e executa o bloco dele. Usamos o swtich para verificar uma variável que pode ter multiplos valores diferentes e para cada valor possível temos a possibilidade de reagir de forma diferente.

```js
switch(grade){

    case 'A':
    console.log('tirou A')
    break

    case 'B':
    console.log('tirou B')
    break

    case 'C':
         console.log('tirou C')
    break

    case 'D':
    console.log('tirou D')
    break

    case 'E':
    console.log('tirou E')
    break

    default:
        console.log('nota inválida')

}
```

**Comment by MivlaM** [comment]
Boa @Latorreander rumo à fluência! 🔥
