### ISSUE TITLE
Aplicação: [Quiz Interativo]

### ISSUE THREAD

**Issue by DiegoFrancoGiusti** [roger-melo-treinamentos/curso-de-js-roger-melo#6498]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Sim

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/DiegoFrancoGiusti/quiz-interativo

### Maiores dificuldades durante a implementação

Minha maior dificuldade durante o desenvolvimento da aplicação foi nomear as variáveis e as funções. A dificuldade é ainda maior quando o dado ou a função é mais abstrata. Queria saber se tem algum(a) guia/dica para me ajudar nesse quesito?

------
Essa foi a funcionalidade que utilizei e que ainda não foi ensinada no curso.
~~~
location.reload()
~~~
Utilizei essa funcionalidade para quando o usuário apertar o botão de **Reiniciar quiz** a página atualize e limpe o formulário.

### Menores dificuldades durante a implementação

A parte lógica da aplicação foi a que senti menos dificuldade. Consegui memorizar bem todas as etapas feitas durante a aula, assisti ela apenas uma vez. Desenvolvi a aplicação duas vezes, uma no dia que assisti à aula e outra dois dias depois. Fiz isso para testar se memorizei mesmo o passo a passo.

---

Não utilizei o **Bootstrap**, pois também estou estudando **CSS** e quero dominar ele puro. Nada de atalhos :satisfied: :satisfied: :wink:

**Comment by MivlaM** [comment]
Olá @DiegoFrancoGiusti

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @DiegoFrancoGiusti

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## Minha maior dificuldade durante o desenvolvimento da aplicação foi nomear as variáveis e as funções. A dificuldade é ainda maior quando o dado ou a função é mais abstrata. Queria saber se tem algum(a) guia/dica para me ajudar nesse quesito?.

No geral você escolheu bons nomes para as funções e variáveis, mas de qualquer forma, vou falar mais sobre a questão da nomenclatura mais adiante na análise =)

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Boas decisões

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

O parâmetro do callback do `forEach` foi nomeado de forma coerente, como singular de itens do array no qual o `forEach` foi encadeado. Isso dá mais legibilidade ao ler a expressão `userAnswer === correctAnswers[index]`.

---

## Funcionalidade Adicional

Antes de começar a análise, gostaria de salientar que na sua aplicação há uma funcionalidade adicional, o botão de resetar o quiz com o location.reload. Normalmente, isso seria uma ocorrência que demandaria que você a removesse para fazer a análise, mas como é uma funcionalidade muito simples que usou apenas uma única, optei por aprovar a sua aplicação. Essa mensagem é mais um aviso, de que é muito interessante que você tenha procurado novos métodos, mas novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. A prioridade é fazer funcionar com o que foi mostrado nas aulas, o que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

É interessante que você tenha desenvolvido outras funcionalidade na aplicação, mas entenda essa mensagem como um aviso para a próxima aplicação não sair muito dos eixos, no momento da análise, considere manter em seu código apenas os trechos relativos às funcionalidades mostradas nas aulas da aplicação. Solicito que, por favor, nas futuras aplicações, siga o recomendado estritamente.

---

## Comentários no código

No index.html, há uma linha de código comentados, não é uma regra, mas evite comentários.

Comentários podem mentir se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## 4 espaços vs 2

Recomendo que ao invés de 4 espaços para indentação, use 2. E isso vale para qualquer linguagem (HTML, CSS, JS, etc).

Se um dia vc quiser enviar alguma sugestão ou modificação de artigo pro MDN, por exemplo, seu código terá que seguir o code-guideline deles:

- [Indentation, spacing, size - MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#indentation_spacing_size)

E não só o MDN, mas muitas outras fontes recomendam que o código tenha 2 espaços ao invés de 4.

Seu olho irá cansar menos, pq suas linhas de código serão menos extensas, o que impacta na legibilidade e carga cognitiva na leitura.

À partir daqui, os exemplos do seu código que postarei abaixo já estarão formatados com 2 espaços, ao invés de 4.

Para configurar espaços no VSCode, dá uma olhada aqui:

[Indentation - VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation)

Vc verá que nesse parágrafo, há um link para o get started de Settings do VSCode. Recomendo dar uma lida, mas não invista muito tempo nisso =)

---

## Usabilidade

Uma outra coisa que vc pode fazer para melhorar a usabilidade é deixar o usuário mais consciente do progresso dele no quiz em relação à pontuação total. Vc pode fazer isso com uma mensagem indicando a pontuação com porcentagem ("você acertou 50%") ou inserindo uma barra e pontuação total do quiz após a quantidade de acertos, exemplo: "Sua nota final é de 50/100".

```js
// antes
userScore.textContent = score
```

```Js
// depois
userScore.textContent = `Sua nota final é de ${score}%`
```

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, a função `validatingAnswers` pode ter seu nome substituido por `getScore`. O intuito aqui é fazer com que o nome diminua de comprimento e ao mesmo tempo mantenha um sentido mais preciso para o que a função está fazendo. De forma similar, a função `showPunctuation` pode ser renomeada para `handleFormSubmit`, o intuito aqui é tornar essa função como uma função genérica cujo intuito é passar as informações que ela recebe das outras funções, mais a frente na análise, você vai entender que isso irá fazer mais sentido. Por agora, ficaria assim:

```js
// antes
const validatingAnswers = (userAnswer,index) => {
  // ...
}

const showPunctuation = event => {
  // ...
}
```

```js
// depois
const getScore = (userAnswer,index) => {
  // ...
}

const handleFormSubmit = event => {
  // ...
}
```

---

## Função getScore

Nessa função, há um detalhe, se fizer sentido para você, não é necessário usar `userAnswer.value` se a propriedade value for acessada para cada inputQuestion na const `userAnswers`. Há uma maneira de deixá-las padronizadas e não precisar acessar essa propriedade value dessa forma, ficaria assim:

```js
// antes
const getScore = (userAnswer,index) => {
  const isCorrectAnswer = userAnswer.value === correctAnswers[index]
}

const userAnswers = [
  event.target.inputquestion1,
  event.target.inputquestion2,
  event.target.inputquestion3,
  event.target.inputquestion4
]
```

```js
// depois
const getScore = (userAnswer,index) => {
  const isCorrectAnswer = userAnswer === correctAnswers[index]
}

const userAnswers = [
  event.target.inputquestion1.value,
  event.target.inputquestion2.value,
  event.target.inputquestion3.value,
  event.target.inputquestion4.value
]
```

Feito esses ajustes, vou te mostrar duas abordagens de refactoring usando métodos que você vai encontrar em breve nas aulas seguintes, ambos serão explicados com detalhes futuramente. O que quero que você entenda, nesse primeiro momento, é o conceito por trás deles. Sabendo disso, observe o código abaixo:

```js
userAnswers.forEach((userAnswer, index) => {
  if(userAnswer === correctAnswers[index]){
    score += 25
  }
})
```

Toda a ideia do código acima é a seguinte: baseado em um array, você quer gerar um número, isto é, um número que seja a pontuação. E quando baseado num array você quer gerar um número, você pode fazer isso de forma funcional, sem efeito colateral e sem reatribuições e ainda pode diminuir algumas linhas do código. A forma que você pode fazer isso é, por exemplo, por meio do método `reduce()`. Mas como isso pode ser feito? Vamos lá, acompanhe comigo codando passo a passo. Vamos fazer essas modificações na função `getScore`, vamos declarar um parâmetro que também se chamará `userAnswers` e esse parâmetro também tera um default parameter de array vazio. Por esse momento, vamos manter uma lógica similar a que você usou dentro dessa função:

```js
const getScore = (userAnswers = []) => {
  userAnswers.forEach((userAnswer,index) => {
    const isCorrectAnswer = userAnswer === correctAnswers[index]

    if(isCorrectAnswer){
      score += 25
    }
  })
}
```

Depois, a let `score` que antigamente recebia o valor 0, agora vai ser uma const `score` e irá receber o retorno da expressão que antes era do `forEach`, mas agora contém o método `reduce`. O reduce vai receber um parâmetro chamado `accumulator` e como segundo argumento, ele irá receber um valor inicial 0. Por quê 0? Porque 0 é o ponto de partida do valor que você deseja obter na pontuação e porque é uma boa prática usar o segundo argumento do `reduce` para indicar visualmente o tipo de valor que o reduce deve retornar. Feito isso, se a resposta estiver correta, o valor de `accumulator` somado com 25 será retornado, se a condição do if não for verdadeira, apenas o valor de `accumulator` vai ser retornado, ficaria assim:

```js
const getScore = (userAnswers = []) => {
  const score = userAnswers.reduce((accumulator,userAnswer,index) => {
    const isCorrectAnswer = userAnswer === correctAnswers[index]

    if(isCorrectAnswer){
      return accumulator + 25
    }

    return accumulator
  }, 0)

  return score
}
```

Na primeira execução dessa função, `accumulator` vai receber o segundo argumento do `reduce`, `userAnswer` vai receber o primeiro item do array e o `index` é o mesmo index do item do array. Se a resposta estiver correta, a função vai retornar accumulator + 25, que na primeira execução será (0 + 25). Por outro lado, se a resposta não estiver correta, `accumulator` será retornado (na primeira execução, o `accumulator` estará armazenando 0). Quando a função for executada pela segunda vez, o parâmetro `accumulator` estará armazenando o valor que foi retornado na execução passada da função, então se na primeira execução for retornado accumulator + 25, na segunda execução o parâmetro `accumulator` estará armazenando 25 ao invés de 0 como na primeira execução. Assim, a operação será feita novamente. E isso vai se repetir para cada item do array `userAnswers`. A const `score` está recebendo o resultado dessa expressão e por fim, esse valor é retornado.

Há mais algumas refatorações que você pode fazer para o código se tornar ainda mais conciso, você pode eliminar os returns para aproveitar o return implícito da arrow function e ao invés de usar o bloco de if, você pode usar um ternário, você também ira aprender mais sobre o ternário posteriormente, mas para você ter uma ideia, se o que está a esquerda do sinal de ? for um valor `truthy`, accumulator + 25 é retornado, caso contrário, apenas `accumulator` será retornado. O score pode ser retornado diretamente:

```js
// Usando o operador ternário no lugar do bloco do if
const getScore = (userAnswers = []) => { 
  return userAnswers.reduce((accumulator, userAnswer, index) => {
    return userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator
  }, 0)
}
```

```js
// Usando o return implícito das arrow functions
const getScore = (userAnswers = []) => userAnswers
  .reduce((accumulator, userAnswer, index) => userAnswer === correctAnswers[index] ? accumulator + 25 : accumulator, 0)
```

Por fim, você pode invocar a função `getScore()` dentro da função `handleFormSubmit` recebendo o array armazenado por `userAnswers` como argumento.

```js
const handleFormSubmit = event => {
  // ...
  const score = getScore(userAnswers)
 // ...
}
```

---

## Função getUserAnswers

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada `inputquestion` do form. `userAnswers` vai receber um array vazio que será preenchido após percorrermos cada item dentro do array `correctAnswers` por meio do método `forEach`. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []

  correctAnswers.forEach((_, index) => {
    const userAnswer = form[`inputquestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })

  return userAnswers
}

```

Tudo certo até aqui? Se sim, vamos prosseguir! A ideia do código acima é a seguinte, baseado em um array, você quer obter um novo array que contém a mesma quantidade de itens do array original. Por quê? `correctAnswers` tem quatro itens e `userAnswers` quando está sendo retornado também vai ter quatro itens. Lembre-se da ideia de que quando baseado em um array, você precisa obter um novo array com a mesma quantidade de itens do array original, você pode usar um método chamado `map`. Sabendo disso, ao invés de `userAnswers` ser declarada como um array vazio, o `userAnswers` pode receber o retorno dessa expressão. Feito isso, ao invés de executar o método `push`, é necessário apenas retornar `userAnswers`. Veja abaixo:

```js
const getUserAnswers = () => {
  const userAnswers = correctAnswers.map((_, index) => {
    const userAnswer = form[`inputquestion${index + 1}`].value
    return userAnswer
  })

  return userAnswers
}
```

Feito isso, você pode refatorar a função ainda mais ao usar os retornos implícitos das arrow functions, removendo os blocos e retornos:

```js
const getUserAnswers = () => correctAnswers.map((_, index) => form[`inputquestion${index + 1}`].value)
```

Fazendo isso, o `map` vai ser executado para cada item de `correctAnswers`, o callback está retornando o valor da resposta do usuário, esse valor que o callback está retornando vai ser inserido num novo array que o `map` está gerando por baixo dos panos. A cada execução desse callback, o valor que a função está retornando vai ser inserido nesse novo array que o `map` está gerando por baixo dos panos. Quando esse callback for executado para todos os itens, o `map` vai retornar esse novo array que ele gerou e toda a expressão vai resultar no array que o `map` retornou.

Por fim, você pode invocar a função dentro da função `handleFormSubmit` que o código funcionará normalmente =)

```js
const handleFormSubmit = event => {
  // ...

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  // ...
}
```

Por meio de um código declarativo, como foi mostrado nas duas últimas abordagens, sua aplicação vai tender a ter menos bugs, e com menos bugs ela será mais fácil de manter. Entendeu a ideia?

---

## Função handleFormSubmit

Como tinha dado uma pequena pista anteriormente, a sugestão aqui é criarmos uma nova função responsável unicamente pela manipulação de DOM e invocarmos ela nessa função também. Atualmente, a função handleFormSubmit também é responsável por uma linha de manipulação de DOM e da invocação da função `showModal`, e para deixar mais claro o papel de apenas passar informações para a frente, vamos reaproveitar a função `showModal` e fazer com que ela se torne a função que vai ser unicamente responsável pela manipulação de DOM. Assim, além de facilitar o fluxo de leitura, você separa mais as responsabilidades, agora que não tem manipulação de DOM em `handleFormSubmit`, essa função agora é apenas responsável por passar informações para frente, para que outras partes da aplicação executem o que precisa ser executado, como por exemplo, exibir o score. Ambas as refatorações nas duas funções ficariam assim:

```js
// antes
const showModal = () => {
  modal.classList.toggle('is-close')
}

const handleFormSubmit = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)

  userScore.textContent = score
  showModal(score)
}
```

```js
// depois
const showScore = (score) => {
  modal.classList.toggle('is-close')
  userScore.textContent = `Sua nota final é de ${score}%`
}

const handleFormSubmit = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getScore(userAnswers)
  showScore(score)
}
```

---

## Função closeModal

Para essa função, se você quiser que o código fique mais simples, uma sugestão é usar o método `includes` ao invés do operador de comparação na const `isCloseButton`. Dessa forma, você também pode remover a notação de colchetes e passar a classe diretamente como um argumento do includes. Ficaria assim:

```js
// antes
const closeModal = event => {
  const isCloseButton = event.target.classList[1] === 'btn--close'
  if(isCloseButton){
    modal.classList.toggle('is-close')
    location.reload()
  }
}
```

```js
// depois
const closeModal = event => {
  const isCloseButton = Array.from(event.target.classList).includes('btn--close')
  if(isCloseButton){
    modal.classList.toggle('is-close')
    location.reload()
  }
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by DiegoFrancoGiusti** [comment]
Muito obrigado pela análise.

Vou refazer a aplicação implementando as observações feitas e o que foi ensinado na etapa 8.

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, mas qualquer coisa, sinta-se livre para abrir uma nova.
