### ISSUE TITLE
Etapa 04, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#65]
Roger, fiquei com uma duvida nesse exercício.

/*
  04

  - Crie uma função que adiciona um amigo(a) no array de amigos do gato;
  - Exiba o array de amigos no console para verificar se o novo amigo(a) foi  
    adicionado.
*/

```
const addGato = (friend, object) => {
  console.log(object)
  object.bestFriends.push(friend)
}
addGato('bruninho', cat)
console.log(cat.bestFriends)

 ```

- **A duvida** 

  Vi que você passou um objeto por parâmetro, nunca tinha visto alguém fazer isso
é uma novidade para mim.
  Achei muito interessante, quero saber mais sobre essa forma de passar objeto, é uma
boa pratica ?
  

- **Outras duvidas que eu acumulei**

1.   Quando estou desenvolvendo uma função.

```
const fazAlgumaCoisa = () => {

} 
```
  Sempre eu tenho que chamar ela pelo parêntese **console.log( fazAlgumaCoisa() )**,
ou posso chamar pela expressão **console.log( fazAlgumaCoisa )**   
  Aí fico na duvida as vezes para saber qual é o melhor método. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo! =)

Só uma dica. Se quiser que o código da issue fique colorido (sintax highlight), é só inserir `js` depois dos 3 pontinhos da abertura do bloco de código.

---

> Vi que você passou um objeto por parâmetro, nunca tinha visto alguém fazer isso
é uma novidade para mim. Achei muito interessante, quero saber mais sobre essa forma de passar objeto, é uma boa pratica ?

É uma prática comum. No decorrer do treinamento você verá vários exemplos de objetos inseridos como argumentos de funções =)

---

> Sempre eu tenho que chamar ela pelo parêntese **console.log( fazAlgumaCoisa() )**,
ou posso chamar pela expressão **console.log( fazAlgumaCoisa )**. Aí fico na duvida as vezes para saber qual é o melhor método. 

Você irá inserir o par de parênteses após o nome da função quando quiser **executá-la**. Ou seja, executar o código que está dentro dos blocos dela.

No código abaixo, 

```javascript
const logMessage = message => {
  console.log(message)
}
```

`logMessage` é uma função que, ao ser invocada, exibe no console a string que recebeu no parâmetro `message`:

```javascript
const logMessage = message => {
  console.log(message)
}

logMessage('olá') // o parâmetro 'message' recebeu 'olá', e 'olá' é exibida no console
```

Você **não irá** inserir os parênteses após o nome da função quando quiser apenas **referenciá-la**. 

No código abaixo, 

```javascript
const numbers = [1, 2, 3]

numbers.forEach(number => {
  console.log(number)
})
```

um número do array numbers é exibido no console a cada execução da função do `forEach`.

Para deixar o código mais legível eu posso, por exemplo, armazenar em uma const a função que o forEach recebe como argumento e apenas referenciar essa função como argumento:

```javascript
const numbers = [1, 2, 3]

const logNumber = number => {
  console.log(number)
}

numbers.forEach(logNumber) // apenas referenciei a função
```

Nesse caso, eu referenciei a função e, para cada número do array, o `forEach` vai executar a função `logNumber`.

Se ao invés de apenas referenciar a função, eu executasse ela,

```javascript
const numbers = [1, 2, 3]

const logNumber = number => {
  console.log(number)
}

numbers.forEach(logNumber()) // executei a função ao invés de referenciá-la
```

essa invocação `logNumber()` faz duas coisas: 

1. Executa o bloco da função. Como um número não foi inserido como argumento na invocação da função, a execução do `console.log(number)` exibe `undefined` no console;
2. Resulta em `undefined` porque em JavaScript, toda função que não retorna um valor, por baixo dos panos, retorna `undefined`.

Se eu olhar o console após executar o código acima, eu vejo o `undefined` que o `console.log(number)` exibiu, e vejo um `TypeError: undefined is not a function`. Ou seja, como a invocação de `logNumber()` resulta em `undefined`, e a invocação do `forEach()` precisa receber uma função como argumento, o erro diz que `undefined` não é uma função.

Ficou mais clara a diferença entre invocar e referenciar?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo, perfeito! 

Não sei se esta mais nos exercícios mais para frente 

Se eu criasse uma função que recebe outra função dentro dela,
já trazer e modificando um valor.

Aí por exemplo, só armazenaria o valor que ela trouxe de outra função que, tratou e deu o
resultado final.

Uma função trazendo o resultado dentro de outra

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

Acho que não entendi qual é a sua dúvida. Você está com dúvida se é possível invocar uma função dentro da outra?

Se sim, observe o código abaixo:

```javascript
const sum = (num1, num2) => num1 + num2
const double = number => number * 2

double(sum(1, 2)) // 6
```

A invocação da `double` precisa receber um número como argumento.

Como `sum(1, 2)` retorna `3`, a invocação da `double` recebeu o `3` e retornou o dobro, que é `6`.

Era essa a dúvida?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo 
Estou mais ciente.
São novidades pra mim, agora estou aprendendo de forma 
mais clara e direto.
Estou ciente da explicação

**Comment by Roger-Melo** [comment]
Show Edinaldo. Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova =)
