### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by RafaelM10** [roger-melo-treinamentos/curso-de-js-roger-melo#6518]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/RafaelM10/Quiz-interativo-js

### Maiores dificuldades durante a implementação

Não tive tanta dificuldade devido eu ter assistido até aqui (Template HTML e checando as respostas - Aula 01-03) 

mas não consegui refatorar tão bem como eu gostaria!

 mas surgiu uma dificuldade em lembrar como agruparia todos os eventos de clique da resposta do usuario em um array, então pensei e puxei na memoria como seria feito e consegui chegar ao resultado 
 
refiz lembrando conforme foi feito na aula e usei somente o conhecimento adquirido até aqui!

### Menores dificuldades durante a implementação

utilizar forEach, prevenir evento de clique, selecionar a classe ou ID

**Comment by MivlaM** [comment]
Olá @RafaelM10

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
