### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by marcoferreiradev** [roger-melo-treinamentos/curso-de-js-roger-melo#652]
# Conversão de tipos

````js
let score = '100'
score = Number(score) //Função construtora para conversão para números

console.log(typeof score) // Função para verificar o tipo do valor

const convertedNUmber = String(97) //Função construtora para conversão para String
````

# Valores

## falsy:
  - false
  - 0
  - "" , '', ``
  - null
  - NaN

## truthy:
  - Qualquer valor que não é falsy

# Observações
- Conversões implicitas de dados são as que o proprio javascript faz por baixo dos panos     

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @marcoferreiradev, rumo à fluência! 🔥
