### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by DevNeves** [roger-melo-treinamentos/curso-de-js-roger-melo#6526]
<h1> Tipos de refêrencia vs Tipos primitivos - Aula 03-04 </h1>

<h2> TIPOS PRIMITIVOS SÃO: </h2>

<p> Numbers </p> 
<p> Strings </p>
<p> Booleans </p>
<p> Null </p>
<p> Undefined </p>
<p> Symbol </p>
<p> BigInt </p>

<h2> TIPOS DE REFERENCIA SÃO: </h2>

<p> Todos os tipos de objeto </p> 
<p> Objetos literais </p>
<p> Arrays </p>
<p> Funções </p>
<p> Datas </p>
<p> Todos os outros objetos </p>

<h3> A diferença deles, é como eles estão armazenados na memoria </h3>

+ Tipos primitivos são armazenados na stack (pilha) que é mais rápida

+ Tipos de refenrencia são armazenados na heap (amontoado) que é mais lenta, mas armazena mais coisas

+ Na stack, fica armazendas os valores primitivos em variaveis e são acessados atraves do nome da variavel 

+ Quando armazena um tipo de referencia como um objeto em uma variavel, esse objeto é armazenado no heap e um PONTEIRO que aponta para o objeto é adicionado na stack 

![stack heap](https://user-images.githubusercontent.com/102633306/231015304-00cbedf9-8e2f-435e-b8e8-5a8fa3399502.png)

<h3> Porque saber disso é importante ? </h3>

+ valores primitivos mesmo sendo os mesmos valores eles são armazenados em posições diferentes na stack. Se o valor for modificado
só o primeiro valor será modificado

![stack](https://user-images.githubusercontent.com/102633306/231016033-96efff86-73fc-44b8-9b31-4641a52c313b.png)

+ com os tipos de referencia por exemplo um objeto ele é armazenado no heap e na stack fica o ponteiro que acessa o objeto q esta no heap, se criar uma variavel e adicionar o mesmo valor , o objeto NAO sera 'copiado' apenas o ponteiro e os dois iram apontar para o mesmo objeto. Ou seja se modificar um deles o outro também será modificado.

![heap](https://user-images.githubusercontent.com/102633306/231016484-98b7112f-20de-4205-9830-3dbc9b8f7046.png)

```js

//valores primitivos

let scoreOne = 50
let scoteTwo = scoreOne

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`) // return scoreOne: 50 | scoreTwo: 50

scoreOne = 100

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`) // return scoreOne: 100 | scoreTwo: 50

//valores de referencia

let userOne = { name: 'Roger' , age: 31}
let userTwo = userOne 

console.log(userOne , userTwo) // return { name: 'Roger' , age: 31} , { name: 'Roger' , age: 31}

userOne.age = 32

console.log(userOne , userTwo) // return { name: 'Roger' , age: 32} , { name: 'Roger' , age: 32}

// isso acontece pq a userOne e a userTwo apontam para o mesmo objeto, o objeto ainda é o mesmo no heap a userTwo 
// nao faz uma cópia dele, apenas criar outro ponteiro entao se modificar uma a outra vai modificar também

**Comment by MivlaM** [comment]
Excelente @DevNeves rumo à fluência! 🎯
