### ISSUE TITLE
data atribute; quando e por que devo utilizar ?

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6540]
### Etapa da aula

10

### Nome da aula

Correção dos exercícios da aula 02 da etapa 09 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6370989

Olá 

Preciso de uma ajuda para entender melhor o conceito de utilizar um dataset. 

Não compreendi muito bem porque devo utiliza ló e muito menos em que momento eu posso ser me beneficiar desse recurso. :(

@Roger-Melo

**Comment by Roger-Melo** [comment]
@dzpoke o que você está vendo agora é apenas uma introdução a esse conceito. Vc ainda verá muitos casos dele conforme for avançando no CJRM e aos poucos isso ficará mais claro. Não espere entender tudo de primeira, algumas coisas começam a fazer mais sentido apenas depois que criamos o hábito de usá-las =)

Mas só pra não te deixar sem resposta...

Selecionar pelo nome da tag é problemático pq se houver duas ocorrências do mesmo elemento no HTML (duas uls, por exemplo), seu código quebra.

Classes CSS foram criadas para manipular estilos. Seu código fica mais organizado quando vc não seleciona pelo atributo class e deixa as classes apenas para o CSS.

`id` tem o efeito colateral nos browsers de gerar uma variável global que aponta para o elemento que tem aquele ID.

Se na marcação HTML for declarado um atributo id com o valor x, se você inserir window.x (ou simplesmente x) como argumento de um console.log(), o retorno será a referência do elemento.

```html
<p id="x">Olá</p>
```

```javascript
console.log(window.x) // <p id="x">Olá</p>
console.log(x) // <p id="x">Olá</p>
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e isso pode minar a modularidade do código.

Se você retirar o id="x", as execuções dos console.log() acima resultarão em undefined.

Então, para não gerar variáveis globais desnecessárias, o ideal é usar data-* (o asterisco representa qualquer nome que vc queira inserir após o `-`) para manipulação de DOM via JS, e usar IDs somente para inputs, por conta da acessibilidade do atributo for das labels ou quando você quiser fazer âncoras na sua página, aí você também precisa do ID. Para todos os outros casos, evite =)

Outra questão de organização é que se você comparar, lado a lado, duas versões do mesmo arquivo .html, uma com data-* e class e outra apenas com class, verá que ao bater o olho no arquivo com data-js e class, você distingue rapidamente quais elementos estão sendo manipulados pelo JavaScript. Isso não é possível ao bater o olho na versão do arquivo que usa apenas class.

A forma mais confiável de identificar elementos e manipulá-los em JavaScript (puro) é usar o atributo data-*.

---

Dito isso, lembre-se do que eu disse acima. O que vc está vendo agora é apenas uma introdução, então não precisa se preocupar em entender agora esse conceito completamente =)

**Comment by dzpoke** [comment]
Obrigado Roger!
