### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6541]
# Função callback e o método forEach

Quando uma função é passada como argumento de uma outra função, essa função que passamos como argumento é chamada de **callback**.

### Segue um exemplo que explica o uso de um callback:
```js

//primeiro declaramos uma função que recebe uma outra função (ou seja, um callback, e neste caso terá o nome "callbackFunction") como argumento
const myFunc = callbackFunction => {
  const value = 'Peter';
  callbackFunction(value);    //aqui invocamos o callback passando-lhe como argumento a constante "value"
}

//agora vamos a invocar a função myFunc passando-lhe como argumento a declaração de uma função, e esta declaração de função será o valor que tomará o parâmetro callbackFunction
myFunc( item => {
  console.log(item);
})

//Resposta
Peter
```

E muito comum usar um callback com os métodos de arreglos . A seguir vamos a mostrar o uso do método de arreglo forEach() passando-lhe uma função como argumento, ou seja, um callback. O que o  método forEach() faz é executar um callback para cada elemento do arreglo que o invoque. Segue exemplo:
```js
const socialNetworks = ['youtube', 'tweitter', 'instagram', 'facebook'];

socialNetworks.forEach(socialNetwork => {
  console.log(socialNetwork)
})

//Resposta
youtube
tweitter
instagram
facebook
```

O método **forEach()** pode receber dois parâmetros mais que são opcionais, o **index** e o **array**. O parâmetro index faz referencia à posição do item atual sobre o qual o callback se está executando , e o parâmetro array faz referencia ao arreglo que está executando o método forEach().

Segue um exemplo de uso do método forEach que recebe um callback como argumento, e o callback tem três parâmetros, o primeiro faz referencia a cada item do arreglo, e como segundo e terceiro argumentos recebe o index e o array:
```js
const socialNetworks = ['youtube', 'tweitter', 'instagram', 'facebook'];

socialNetworks.forEach((socialNetwork, index, array) => {
  console.log(index, socialNetwork, array)
})

//Resposta
0 youtube [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
1 tweitter [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
2 instagram [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
3 facebook [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
```

Uma forma mais elegante de escrever o código acima seria a seguinte:
```js
const socialNetworks = ['youtube', 'tweitter', 'instagram', 'facebook'];

const callbackFunction =  (socialNetwork, index, array) => {
  console.log(index, socialNetwork, array);
}
socialNetworks.forEach(callbackFunction);

//Resposta
0 youtube [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
1 tweitter [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
2 instagram [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
3 facebook [ 'youtube', 'tweitter', 'instagram', 'facebook' ]
```
### No resumo um callback é simplesmente uma função que é passada como argumento da invocação de uma outra função ou método.

**Comment by MivlaM** [comment]
Excelente @OnielStgo, rumo à fluência! 🎯
