### ISSUE TITLE
Factory functions 

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#6551]
### Etapa da aula

14

### Nome da aula

Factory functions e composição de objetos - Aula 03-09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/1926080

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá, minha duvida é com relação a factore function, realmente a sintax é melhor e menos cansativa de ler, porém com relação a perfomece factore function não seria uma escolha ruim, onde não consigo fazer herança prototipal, e cada metodo de um objeto criado é unico na memória, diferente de usar classes que consegue fazer a herança e pendurar os metodos no prototype para que as instancias podem usar com menos gasto de memoria. 

Outra duvida ficoucom relção a closer e ao scopo lexico, não só com a definição, mas o que realmente acontece no background 

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Sansanoski

> ## não seria uma escolha ruim, onde não consigo fazer herança prototipal, e cada metodo de um objeto criado é unico na memória,

As Factory functions evitam que “caiamos na tentação” de usarmos e abusarmos de níveis de heranças, e também possibilitam uma refatoração mais simples apenas usando funções, além de diminuir a necessidade de uso do this, tornando o código mais previsível. Uma desvantagem seria a micro performance (que as torna um pouco mais lentas que classes e funções construtoras), mas nada que impacte demasiadamente a performance percebida do usuário, a não ser que se esteja se preocupando com a micro-otimização da aplicação, mas isso não vem ao caso no momento.

> ## Outra duvida ficoucom relção a closer e ao scopo lexico, não só com a definição, mas o que realmente acontece no background

Em relação as closures, o que foi mostrado sobre elas nessa aula foi apenas uma leve introdução, mas fique tranquilo que elas vão ser mais aprofundadas futuramente, na aula `Correção dos exercícios da aula 03 da etapa 14 - Aula 01-09` você vai ver de forma mais aprofundada sobre as closures e também a sua implementação em uma aplicação. Porém, enquanto isso, o que eu sugiro para você é que você tenha em mente que há um mecanismo da linguagem chamado closures que são a combinação de uma função com seu escopo léxico. Veja o código abaixo:

```js
const createUser = (name, email) => {
  let counter = 0

  return {
    name,
    email,
    incrementCounter: () => ++counter
  }
}
```

No exemplo acima, utilizando factory function, para termos um método, apenas declaramos uma propriedade `incrementCounter` que retorna uma arrow function que incremente o contador. E independente de quantos objetos forem criados a partir de uma factory function, cada uma terá o seu próprio contador. E isso é possível por causa das closures, que são a combinação de uma função com seu escopo léxico. E escopo léxico, utilizando a factory function acima como exemplo, é todo o escopo que envolve a declaração da arrow function da incrementCounter. Como nessa arrow function é usada uma let que foi declarada no escopo léxico, essa arrow function agora é uma closure. Porque ela é uma combinação de uma função com seu escopo léxico. Certo? Como disse anteriormente, é um assunto que vai ser aprofundado nas aulas futuras, se você não entendeu por completo, não se preocupe ainda, apenas certifique-se de compreender o que foi mostrado nas aulas de agora e no exemplo =)


Está ficando mais claro o entendimento? Qualquer coisa, sinta-se livre para perguntar novamente.

**Comment by Roger-Melo** [comment]
@Sansanoski apenas para complementar a resposta do @MivlaM, na aula 02-03 da etapa 15 vc verá uma forma de fazer herança em factory function. 

Se depois de ver essa aula ainda restarem dúvidas sobre prototypes com factory functions, é só dar o toque.

**Comment by Sansanoski** [comment]
Opaaa !!! Verdade, ficou bem claro comm  sua explicação e vou esperar as proximas aulas para saber como que faz a herança na factore funcation !!!! obrigado

**Comment by MivlaM** [comment]
Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
