### ISSUE TITLE
Resumo da Aula Aula 01-06 Etapa 01

### ISSUE THREAD

**Issue by bivar37** [roger-melo-treinamentos/curso-de-js-roger-melo#656]
Constantes e variáveis.

Variável tem como objetivo armazenar valor.

Existem formas de declarar uma  variável:
Variável como o nome ja diz , você pode mudar o valor:
Let 

Ex.
let name = ‘Diego’
name=’Paulo’
inicialmente a let name era Diego depois mudei para Paulo

Se quiser uma variável que nao queira mudar o valor:
Use  a palavra chave : Const

Algumas regras ao criar uma variável :

Ao nomear uma variável  tem que  usar uma só palavra.
Ex.
let name = ’Bivar’

Caso queira usar duas ou mais  palavras a primeira tem q ser minúscula e as outras maiúsculas.
let firstName=’Paulo’
 
Existem palavras reservadas que não podem ser  declaradas , ou seja não podem dar o nome a uma variável.

Nota
console.log pode receber mais de um  valor, que são separados por vírgula.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @bivar37, rumo à fluência! 🔥
