### ISSUE TITLE
Qualquer pessoa pode clonar o repositório?

### ISSUE THREAD

**Issue by erickslohan** [roger-melo-treinamentos/curso-de-js-roger-melo#6564]
Ola, tenho uma duvida! Mesmo eu nao sendo aluno posso clonar o repositorio e tentar resolver  os problemas?

**Comment by Roger-Melo** [comment]
Olá @erickslohan. Pode sim =)

**Comment by erickslohan** [comment]
Bacana! valeu professor roger!
