### ISSUE TITLE
Etapa 3,Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#659]
Não só neste caso,mas geralmente perco algum tempo pesquisando conteúdo para resolver os exercícios e por vezes sinto que acumulo muitos abas abertas e não encontro nada. No exercício 7 em questão esta instrução:
````JS
                      myWords += functions[x]()
````
  Aonde tenho acesso aos elementos do array através da invocação das 'functions' ,é uma instrução padrão onde encontraria dentro de um artigo no MDN, ou está mais para uma dedução lógica usada com 'mini-teste' para alunos?
  Gostaria de pedir algumas dicas para melhor me organizar durante as pesquisas de conteúdo.....Obrigado Roger.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcos.

Legal, vamos lá =)

> Não só neste caso,mas geralmente perco algum tempo pesquisando conteúdo para resolver os exercícios e por vezes sinto que acumulo muitos abas abertas e não encontro nada. No exercício 7 em questão esta instrução:

Na maioria das vezes, para resolver uma bateria de exercícios, você usará apenas o que viu até aquele ponto do treinamento. A expressão `myWords += functions[x]()`, por exemplo, usa apenas conceitos que foram mostrados até aqui. Quando é necessário pesquisar algo que ainda não foi mostrado, isso é feito de forma intencional e fica explícito no enunciado.

> Aonde tenho acesso aos elementos do array através da invocação das 'functions'

Na verdade, como o array contém declarações de funções, observe que é possível acessar qualquer uma das declarações através da sintaxe de colchetes, que é a sintaxe que acessa um item em um array:

```javascript
const arr = [
  function myFunc1 () {},
  function myFunc2 () {}
]

console.log(arr[1]) // function myFunc2 () {}
```

Como `arr[1]` resulta na referência da função, ao invés de simplesmente exibir a função no console, eu posso invocar ela:

```javascript
const arr = [
  function myFunc1 () {},
  function myFunc2 () {}
]

console.log(arr[1]()) // undefined (por que 'myFunc2' não retorna um valor)
```

Já se eu fizer `myFunc2` retornar um valor:

```javascript
const arr = [
  function myFunc1 () {},
  function myFunc2 () { return 'Olá' }
]

console.log(arr[1]()) // 'Olá'
```

Então resumindo o que está acontecendo no código acima: 

- `arr[1]` resulta na referência de `function myFunc2 () { return 'Olá' }`
- como a sintaxe de parênteses `()` executa uma função, eu executo a `myFunc2` inserindo um parênteses no final da expressão `arr[1]()`;
- e como ao ser invocada, `myFunc2` retorna uma string `'Olá'`, essa string é exibida no console por que a expressão `arr[1]()` foi inserida como argumento da invocação de um `console.log()`.

No fim das contas, é isso que está acontecendo a cada execução do loop do exercício 7.

Ficou mais claro? 

Sobre buscar conteúdos na internet, eu recomendo que você pesquise sobre o que foi falado nas aulas no MDN. E ainda assim, é necessário [um pouco de paciência](https://youtu.be/p3W1hbNr6vc?t=71), pois nem sempre você entenderá tudo de uma vez. Algumas coisas vem com a prática e o tempo =)

> ou está mais para uma dedução lógica usada com 'mini-teste' para alunos

Geralmente, os últimos exercícios das baterias de exercícios são mais complexos e vão exigir mais do aluno. Se fosse fácil, todo mundo faria =)

A dica que eu dou é seguir este [passo a passo](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Esse é o mecanismo que eu uso quando preciso que meu cérebro se acostume com um novo padrão.

Faz sentido?

@marcosyoggy
