### ISSUE TITLE
Etapa 14, Factory functions e composição de objetos - Aula 03-09

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#660]
Olá Roger, Tudo bem? Nessa aula você comentou sobre Closure. Poderia me explicar de novo por que para mim não ficou 100% claro no vídeo. E outra dúvida, poderia me dizer as diferenças entre Funções Construtoras e Factory Functions? Achei ambas bem parecidas. :)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel. Tudo certinho, e tu? xD

Na verdade, nessa aula eu só dei uma leve introdução sobre closures. Na aula 01-09 da etapa 14 eu falo de forma mais aprodundada sobre closures e implemento em uma aplicação. Você pode ver essa aula agora, mas acho que o ideal seria você ir progredindo até lá e, se após a explicação ainda restar alguma dúvida, pode perguntar =)

O objetivo era introduzir pra que ficasse uma puga atrás da orelha mesmo (funcionou) xD

Sobre as diferenças entre Funções Construtoras e Factory Functions, ambas fazem a mesma coisa (criam objetos) de formas diferentes.

Uma factory function é qualquer função que não é uma classe, não é uma função construtora, mas retorna um novo objeto. 

Já uma função construtora te obriga a usar a palavra-chave `new` ao invocá-la e, por convenção, precisam ter a primeira letra maiúscula.

Sacou a ideia?

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
hmmm, Saquei 100%. Valeu Roger!!
