### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6615]
Para remover um elemento da página, podemos usar o método remove().

```
const lis = document.querySelectorAll('li')
lis.forEach(li => {
    li.addEventListener('click', event => {
        const clickedElement = event.target
        clickedElement.remove()
    })
})
```
No exemplo da aula anterior, em vez de mudar o estilo, desta vez removemos o elemento clicado utilizando o código 'clickedElement.remove()'. Desta forma, o elemento é excluído da página.

---------------

```
const button = document.querySelector('button')
const ul = document.querySelector('ul')
button.addEventListener('click', () => {
    const li = document.createElement('li') 
    li.textContent = 'Novo item'
    ul.append(li)
})
```
No exemplo de código, armazenamos a referência do botão na constante 'button'. Também buscamos a referência da lista ul e armazenamos em uma constante chamada ul. Criamos um escutador de eventos (addEventListener), que escuta o evento de clique (click) e passamos como argumento uma função de callback.

Uma forma alternativa ao innerHTML de criar um elemento HTML é através do método createElement() do objeto document. Passamos como argumento uma string com o nome da tag desejada, no caso 'li'. então armazenamos o resultado em uma constante chamada li.

Com a propriedade textContent, inserimos uma string 'Novo item' como conteúdo do elemento criado.  Por fim, o novo elemento é inserido no DOM utilizando o método append() no elemento pai, que adiciona o novo elemento como último filho. Se desejar adicioná-lo como primeiro filho, pode-se utilizar o método prepend().

**Comment by MivlaM** [comment]
Excelente @dev-jefferson-lopes, rumo à fluência! 🎯
