### ISSUE TITLE
Correção exercicio 7 

### ISSUE THREAD

**Issue by matheusmoraesn** [roger-melo-treinamentos/curso-de-js-roger-melo#6622]
### Etapa da aula

1

### Nome da aula

Dom - Aula 04 - 01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706725

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Porque no codigo abaixo foi usado 

```
body.innerHTML = ' '
```

e nao :
```
body.remove()
```
verifiquei que ambos dão o mersmo resultado, a duvida é mais para questão de curiosidade mesmo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @matheusmoraesn.

O método `remove` remove o elemento no qual ele foi encadeado. Ou seja, `body.remove()` removeu a tag `<body>`, e o exercício pede para que apenas o conteúdo dentro do body seja removido. 

Sacou a ideia? =)

**Comment by matheusmoraesn** [comment]
Perfeito. Não havia enxergado essa diferença
Agora entendi.

**Comment by Roger-Melo** [comment]
Boa! Vou fechar a issue, mas no que precisar, é só abrir uma nova =)
