### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#663]
Em JavaScript, tipos primitivos são *numbers*, *strings*, *booleans*, *null*, *undefined*, *symbol* e *bigInt*. Os tipos de referência são os objetos, de qualquer tipo, seja um objeto literal, um *array*, uma função, etc.
A diferença entre estes tipos basicamente é a forma como são armazenados na memória. Os tipos primitivos são armazenados em um lugar na memória chamado *stack* e os de referência são armazenados em outro lugar da memória chamado *heap*. Numa tradução literal, *stack* significa pilha e *heap* significa amontoado.

Na *stack*, os valores são acessados de forma mais rápida, porém é um espaço mais limitado. Um dado é armazenado na *stack* assim que o atribuímos a uma variável. Então se eu declaro uma variável *name* que recebe como valor a *string* 'Ricardo', nesse momento este valor é armazenado na *stack*.

No *heap*, os valores são acessados de forma mais lenta, mas tem mais espaço disponível para que sejam armazenados objetos maiores e mais complexos. Então no momento em que criamos uma variável e atribuímos a ela um objeto literal, por exemplo, este objeto literal é criado no *heap*, porém a variável que acessa esse objeto fica na *stack*, e o que ela armazena não é um valor, e sim um ponteiro que aponta para o objeto.

Então os tipos primitivos ficam armazenados na *stack*, e os objetos ficam armazenados no *heap*, porém seus ponteiros ficam na *stack*. Para entendermos melhor os conceitos, vamos criar uma variável que armazena um tipo primitivo. Agora vamos criar uma segunda variável e atribuir a ela a variável criada anteriormente. Nesse caso dois valores iguais foram criados na *stack*. Então temos duas variáveis, cada uma com seu valor independente. Se precisarmos alterar o valor de uma das variáveis, o valor da outra não será afetado. Já no caso de uma variável armazenar um objeto e quisermos criar uma outra variável e atribuir o objeto criado anteriormente, o que está sendo copiado é o ponteiro para o mesmo objeto. Então nesse caso temos dois ponteiros criados na *stack* apontando para o mesmo objeto no *heap*. Logo, se precisarmos alterar o valor de alguma propriedade do objeto, ao acessar por qualquer um dos ponteiros, será mostrado o valor alterado. Vamos ver na prática:

```jsx
// valores primitivos
let scoreOne = 50;
let scoreTwo = scoreOne;

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);
// scoreOne: 50 | scoreTwo: 50

scoreOne = 100;

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);
// scoreOne: 100 | scoreTwo: 50

// valores de referência
let userOne = { name: 'Ricardo', age: 38 };
let userTwo = userOne;

console.log(userOne, userTwo);
// {name: "Ricardo", age: 38} {name: "Ricardo", age: 38}

userOne.age = 39;

console.log(userOne, userTwo);
// {name: "Ricardo", age: 39} {name: "Ricardo", age: 39}
```

O que aconteceu acima foi que no tipo primitivo o valor é que foi copiado para a nova variável, e no tipo de referência, o que é copiado é o ponteiro (que está apontando para o objeto no *heap*), e não seu valor. Então tipos primitivos armazenam valor, e tipos de referência (objetos, por exemplo), armazenam uma referência para o objeto criado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência! 🔥
