### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#6630]
<h1>A palavra-chave this</h1>

This é um objeto de contexto, ele representa o contexto no qual o codigo atual ta sendo executado e dependendo de onde ou como eu usar o valor do this vai mudar.

Se eu usar this na raiz do documento ele vai referênciar um contexto global que é objeto Window. Não é recomendado usar arrow functions com this, pois na hora da invocação da arrow function o this vai referênciar o objeto window, usasse functions declarations para usar this.

**Comment by MivlaM** [comment]
Excelente @MateusCavalheiro-prog, rumo à fluência! 🎯
