### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by Sansanoski** [roger-melo-treinamentos/curso-de-js-roger-melo#6635]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 03 da etapa 14 - Aula 01-09

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/2245729

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá tudo bem ? 
Eu consegui entender o uso de IIFEs, que evitam que sejam criadas variaveis em escopo global, se declara uma varialvel apenas uma vez e consege usa-la novamente . 

```
const state = (() => {
  let exchangeRate = {}

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
})()
```
No exemplo acima,  ficou claro o uso da IIFE, porém o que me gerou duvida foi  :  

Dentro da função declaramos uma let exchangeRate = {} e tambem a funcção ela retorna um objeto {}

```
return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }
```

Assim, quando acessar exchangeRate usando o metodo getExchangeRate não deveria retornar um objecto aninhado ? 

state.getExchangeRate() // { {} }

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Sansanoski. Tudo bom?

Você abriu [esta issue](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/6551) e não nos deu retorno. Há duas respostas lá te esperando. 

É importante que a gente tenha retorno da sua parte para ter certeza de que você está pelo-menos lendo o que estamos orientando, ok?

Após ler a issue linkada acima e nos dar um retorno, tratamos desta issue de dúvida sobre IIFE, combinado?

**Comment by MivlaM** [comment]
Olá @Sansanoski 

No contexto da aula, acredito que o que foi mostrado no vídeo é caso essa função state não fosse uma IIFE, cada vez que ela fosse invocada, um novo objeto estaria sendo criado pela let `exchangeRate`, porém, quando essa função é uma IIFE, a auto execução dessa função declarou um objeto `exchangeRate` na memória, ou seja, não existem dois objetos `exchangeRate` sendo armazenados na memória (como seria numa função comum), sempre que a `getExchangeRate` for invocada, você sempre vai obter único objeto armazenado inicialmente pela let `exchangeRate`.

Ademais, vale a pena mencionar que o objeto que a let `exchangeRate` está armazenando foi criado e o objeto que está sendo retornado também é criado. O objeto que a função está exportando (return) contém métodos que apenas utilizam essa let `exchangeRate`. O que não está sendo criado, como o que foi mostrado no vídeo, são dois objetos diferentes na memória, pois isso só acontece se a função state não for uma IIFE. 

```js
const state = (() => {
  let exchangeRate = {} // Aqui, um objeto é criado uma única vez na memória

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
})()
```

**Comment by Sansanoski** [comment]
Olá @MivlaM 

Obrigado pela explicação. Ficou claro  as coias !

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
