### ISSUE TITLE
Aula 04 etapa 05 

### ISSUE THREAD

**Issue by matheusmoraesn** [roger-melo-treinamentos/curso-de-js-roger-melo#6647]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 04 da etapa 05 - Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/6b300556444e6ff43f4a78991d84996d17c050a9/curso-de-javascript-roger-melo-cjrm-mar2023/aula/6706729

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Professor, nao sei se há uma resolução mais a frente sobre isso, mas ate onde assisti não existe.
eu usei o botão mudar cor do ovo, para alterar para cores aleatorias
criei o codigo abaixo, porém só está atualizando ao dar F5 na pagina
gostaria de verificar qual meu erro que não faz a cor atualizar a cada vez que aperto o botão

```
const div = document.querySelector('div')
const elementsInsideDiv = Array.from(div.children)
const h2 = document.querySelector('h2')
const ovo = document.querySelector('.egg')
const button = document.querySelector('button')
const colors =  [
  '#ff0000', '#00ff00', '#0000ff',
  '#ff3333', '#ffff00', '#ff6600'
]

const random_color = colors[Math.floor(
  Math.random() * colors.length)]


ovo.addEventListener('mousemove',event =>{
  ovo.textContent = `Pos.X ${event.offsetX} | Pos.Y ${event.offsetY}`
})

button.addEventListener('click', event =>{
 colors.some(cor => ovo.style.background = random_color)
    
})

```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @matheusmoraesn

Para ser mais preciso na hora de replicar o problema e te ajudar com a sua dúvida, preciso do código html e também (se houver) o código css que você está usando até o momento que ocorre o problema que você está relatando. Por gentileza, poderia me passar essas informações?

**Comment by matheusmoraesn** [comment]
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="./style.css">
  <title>Exercícios da aula 04 da etapa 05</title>
</head>
<body>
  <div>
    <h2></h2>
    <h1>3 objetos que toda casa brasileira já teve</h1>
    
    <p>TV portátil</p>
    <p>Antena UHF</p>
    <p>Galinha da Maggi</p>
  </div>

  <div class="egg">Mova o mouse aqui dentro</div>
  <button>Mudar cor do ovo</button>

  <script src="./app.js"></script>
</body>
</html>

```

```css
.egg {
  width: 300px;
  height: 300px;
  background: lightblue;
  border-radius: 50%;
  margin: 30px auto;
  text-align: center;
  padding-top: 50px;
}

```

**Comment by MivlaM** [comment]
Olá @matheusmoraesn 

Para a cor do ovo atualizar cada vez que se aperta o botão, é necessário colocar a const `random_color` dentro do listener de clique. O que está acontecendo é o seguinte, a const `random_color` está armazenando um dos hashes aleatórios dentro da const `colors` cada vez que a página é atualizada, portanto, ao clicar uma única vez no botão, a cor do ovo muda de acordo com o hash que a `random_color` armazenou. Porém, ao clicar uma segunda vez, o hash permanece o mesmo, pois a página não foi atualizada. 

Para mudar a cor sempre que apertar o botão, é necessário que `random_color` esteja dentro do listener, pois aí, esse cálculo interno para armazenar um novo hash de cor vai ser feito sempre que o botão de clique for pressionado. Ficaria assim (detalhe, não é necessário o método some para essa funcionalidade, você pode fazer o mesmo funcionamento sem utilizá-lo) :

```js
button.addEventListener('click', event =>{

const random_color = colors[Math.floor(
  Math.random() * colors.length)]

ovo.style.background = random_color
})
```

Consegui esclarecer a sua dúvida? Qualquer coisa, sinta-se livre para comentar logo abaixo =)

**Comment by matheusmoraesn** [comment]
Esclareceu de forma perfeita ! 
muito bom
agradeço !

**Comment by MivlaM** [comment]
Ok, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
