### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6659]
# Modificando estilos CSS (inline)

Quando agente quer manipular estilos de forma pontual em um elemento, é preferível usar a propriedade **style** ao invés de usar o método **setAttribute()**, já que o método **setAttribute()** sobrescreve os estilos já existentes nos elementos.

**NOTA:** A maior parte do tempo a forma mais eficiente de adicionar estilos aos elementos de uma pagina html, é através de classes CSS em um arquivo .css externo, para então adicionar, modificar ou remover essas classes através de JavaScript.

Para realizar os exemplos seguintes vamos supor que dentro de um documento html temos o seguinte elemento:
```html
<h1 style="color: blue;">Modificando estilos CSS (inline)</h1>
```
### Segue exemplo que mostra como o método **setAttribute()** sobrescreve os estilos já existentes no elemento h1:
```js
const title = document.querySelector('h1');

console.log(title);        // <h1 style="color: blue;">Modificando estilos CSS (inline)</h1>

title.setAttribute('style', 'margin: 50px');

console.log(title);        // <h1 style="margin: 50px;">Modificando estilos CSS (inline)</h1>
```
### Agora segue exemplo que mostra como a propriedade **style** adiciona estilos ao elemento h1 mas sem sobrescrever os estilos existentes:
```js
console.log(title);        // <h1 style="margin: 50px;">Modificando estilos CSS (inline)</h1>

title.style.padding = '2px';

console.log(title);        // <h1 style="margin: 50px; padding: 2px;">Modificando estilos CSS (inline)</h1>

//agora vamos modificar o valor da propriredade margin:
title.style.margin= '10px';
console.log(title);        // <h1 style="margin: 10px; padding: 2px;">Modificando estilos CSS (inline)</h1>

//agora vamos eliminar a propiedade margin assignando para ela um string vazio:
title.style.margin= '';  
console.log(title);        // <h1 style="padding: 2px;">Modificando estilos CSS (inline)</h1>


//NOTA: se imprimimos por consola title.style poderemos ver um objeto que contem todas as propriedades css que podem ser aplicadas no elemento title (ou seja, ou h1).

//NOTA:  se imprimimos por consola title.style.padding poderemos ver o valor do padding do elemento h1
```
**NOTA:** Quando usamos JavaScript e  vamos escrever uma propiedade css que está composta por duas ou mais palavras temos que usar o camelCase para eliminar a barra entre as palavras. Exemplo:
```js
title.style.font-size = '12pz';        // forma incorreta. Aqui o JavaScript interpreta que estamos tentando restar size de font

title.style.fontSize = '12pz';        // forma correta.

//Se temos dúvida na hora de escrever o nome de uma propriedade podemos imprimir por consola a propriedade style do elemento para ver todas as propriedades dele.
```

**Comment by MivlaM** [comment]
Excelente @OnielStgo rumo à fluência! 🎯
