### ISSUE TITLE
Resumo da Aula Mais eventos do DOM - Aula 04-03 da etapa 05

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6666]
O evento de cópia é disparado quando o usuário copia um texto selecionado utilizando o "ctrl + c" ou então o botão direito do mouse e clicando em "copiar".

```
const paragraph = document.querySelector('.copy-me')
paragraph.addEventListener('copy', () => {
    console.log('Texto copiado!')
})
```

No exemplo de código, armazenamos em uma constante a referência de um parágrafo cuja classe se chama "copy-me". Em seguida, adicionamos um listener de eventos no parágrafo. Como primeiro argumento, passamos o evento 'copy' e como segundo argumento, passamos uma função de callback. Dentro desta função, temos um console.log que imprimirá no console "Texto copiado!" caso o usuário acione o evento.

--------------
Evento de movimento do mouse utilizando as coordenadas X e Y do cursor.

```
const div = document.querySelector('.box')
div.addEventListener('mousemove', event => {
   div.textContent =`X ${event.offsetX} | Y ${event.offsetY} `
})
```

No código, armazenamos em uma constante a referência de uma div com a classe ".box" e, em seguida, adicionamos um listener de eventos na constante div. passamos o evento 'mousemove' como primeiro argumento e uma função de callback com o parâmetro "event" como segundo argumento, dentro da função de callback, modificamos o texto da div utilizando a propriedade textContent e interpolando event.offsetX para a coordenada X e event.offsetY para a coordenada Y.

Dessa forma, o código irá renderizar no navegador atualizando continuamente o valor da coordenada de pixels dentro da div conforme o usuário movimenta o mouse. Essa funcionalidade pode ser útil em situações em que precisamos saber a posição atual do mouse.

-----
O evento 'wheel' é disparado quando o usuário roda a roda de rolagem do mouse. 
```
document.addEventListener('wheel', event => {
    console.log(event.pageX, event.pageY)
})
```
O código utiliza o método 'addEventListener' para adicionar um ouvinte de evento 'wheel' no elemento 'document'. Quando o usuário faz o scroll no documento, o callback do evento é executado. Nesse caso, o callback simplesmente imprime as coordenadas do cursor do mouse no console

**Comment by MivlaM** [comment]
Excelente @dev-jefferson-lopes rumo à fluência! 🎯
