### ISSUE TITLE
Resumo da Aula Criando e removendo elementos do DOM - Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6677]
# Criando e removendo elementos do DOM
Para criar ou remover um elemento html usando JavaScript podemos usar os seguintes métodos:
- **createElement()** --> para criar um elemento. Dentro das chaves colocaremos entre aspas o elemento que queremos criar
- **remove()** -->  para remover um elemento.

Para criar um elemento no DOM temos que realizar o seguiente:
- Obter a referência do elemento (parent ou sibling) onde vamos inserir o elemento que vamos criar
- Criar o novo elemento
- Inserir o elemento criado usando o método **append()** ou o método **prepend()**.

O método **append()** insere um elemento como último filho do elemento usado como referência para realizar a inserção, e o método **prepend()** insere o elemento como primeiro filho do elemento usado como referência.

Para os exemplos que seguem vamos usar o seguinte código html:
```html
<ul>
    <li>Comprar frango</li>
    <li>Ler livro</li>
    <li>Tocar violão</li>
    <li>Pagar as contas</li>
</ul>

<button>Criar elemento</button>
```
### Agora vamos ver como criar um elemento e inseri-lo no final da lista. O elemento será criado cada vez que o usuário clique no botão:
```js
const ul = document.querySelector('ul');

const button = document.querySelector('button');

button.addEventListener('click', () => {
  const li = document.createElement('li');        //criamos um elemento li
  li.innerText = 'Novo item';                      //colocamos um texto no li
  ul.append(li);                                 //adicionamos o li no final da lista
})

//então cada vez que o usuário faça click no botão um novo elemento li será inserido no final da lista
//se tivéssemos querido inserir o elemento no principio da lista, a última instrução dentro da função de callback acima teria sido a seguinte:

   ul.prepend(li);
```
### Então agora vamos ver como remover um elemento. No exemplo que segue vamos supor que queremos apagar a lista completa:
```js
const ul = document.querySelector('ul');

ul.remove();        //esta instrução automaticamente apagará a lista completa, ou seja, a tag pai "ul" mas também seus filhos
```

**Comment by MivlaM** [comment]
Excelente @OnielStgo rumo à fluência! 🎯
