### ISSUE TITLE
Resumo da Aula Um overview sobre tipos de dados - Aula 02-02 da etapa 01

### ISSUE THREAD

**Issue by davidcso** [roger-melo-treinamentos/curso-de-js-roger-melo#6678]
Tipos de Dados
---
Em javascript atualmente temos um total de 8 tipos de dados e cada um tem suas particularidades. Esses tipos de dados são:

**Numbers:** Variável numérica. Pode ser inteira ou de ponto flutuante, exemplo: 1, 2, 3, 100, 3,14

**Strings:**  São uma cadeia de caracteres, é usado para representar dados textuais. Para representar textos em javascript, devemos utilizar dentro de aspas simples ou duplas. Exemplo: “Olá Mundo!”, “david@outlook.com“.

**Boolean:** São lógicas de valores verdadeiros ou falsos. Utilizamos para verificar se certas condições são verdadeiras ou falsas. Exemplo: true / false. 

**Null:** É uma forma de dizer explicitamente que uma variável não tem valor, podemos criar uma variável e atribuir o null para ela, pra indicar que essa variável não tem valor. Exemplo: let age = null.

**Undefined:** Representa um valor não-setado, um valor vazio. Ele é inserido automaticamente pelo javascript.

**Object:** São estruturas mais complexas de dados e dentro dela você pode ter múltiplas  propriedades e funções. Exemplo: Arrays, Datas, Literais, etc. 

**Symbol:** É utilizado com objetos.

**BigInt:** Utilizado para manipular números inteiros muito grande.

**Comment by MivlaM** [comment]
Excelente @davidcso rumo à fluência! 🎯
