### ISSUE TITLE
Etapa 04 , Objetos - Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#67]
**Roger, fiquei com duvida nesse exercício.**

/*
  05

  - Crie uma função que adiciona mais uma cor à cor do gato;
  - Utilize a sintaxe de colchetes para fazer isso;
  - Exiba a nova cor do gato no console, também utilizando a sintaxe de  
    colchetes.
*/

**E eu fiz assim**

```js

const adicionaCor = (cores) => {
  cat.color = [cores]
  console.log(cat.color)
}

adicionaCor([cat.color, 'cinza'])

console.log(cat)

```

**A duvida, eu pensei que era para criar outro array tipo o do (bestFriends).
O codigo que eu fiz, foi uma boa forma de criar um novo array lá, já com um dado lá.**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Edinaldo.

Não é comum um objeto ser inicializado com propriedades com um tipo de valor e, no meio do código, o tipo de valor dessa propriedade ser modificado. Exemplo: atribuir um objeto para uma propriedade que armazena um array.

Como o valor da `color` do objeto `cat` é uma string, o ideal é que esse valor continue sendo uma string. O objetivo desse exercício é checar se você entendeu como usar a sintaxe de colchetes ao trabalhar com propriedades de objetos.

Sacou a ideia?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
Roger, entendi mais ou menos.
Eu pensei que colchetes é criar um array  não?
Você passando outro exemplo agradeço amigo.

**Comment by Roger-Melo** [comment]
Oi Edinaldo.

Quando você insere um colchetes e coloca valores dentro deles, assim `[1, 2, 3]`, você criou um array. Quando apenas os colchetes sãousados assim `[]`, um array foi criado. Para acessar um item de um array os colchetes também são utilizados `myArray[indexDoItem]`.

Mas se tratando de objetos, haverão momentos em que será necessário criar e/ou declarar propriedades usando a sintaxe de colchetes. Eu apresentei esse conceito [nessa](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/816557) aula.

Então assista ela novamente e se surgir alguma dúvida específica, é só avisar =)

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
@Roger-Melo ciente meu amigo!
