### ISSUE TITLE
Etapa 07, setInterval() e animação da pontuação - Aula 02-03

### ISSUE THREAD

**Issue by Roger-Melo** [roger-melo-treinamentos/curso-de-js-roger-melo#670]
Roger, Como que o setInterval é executado/invocado se ele está agora dentro de uma const, e em nenhum momento do código você faz a invocação dele após a sua atribuição a const? É o próprio browser que faz essa invocação automaticamente após o intervalo de tempo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Raimundo.

Você se refere ao código abaixo, certo?

```javascript
const timer = setInterval(() => {
  if (counter === score) {
    clearInterval(timer)
  }
  
  // ...
}, 10)
```

> e em nenhum momento do código você faz a invocação dele após a sua atribuição a const

A expressão `setInterval()` é uma invocação. No código acima, a invocação dele recebe uma função como 1º argumento e um intervalo de tempo como 2º argumento.

O `setInterval` é um método do `window` que pode ser invocado sem a especificação do `window.`. Ou seja, tanto faz invocar `window.setInterval()` ou `setInterval()`.

A invocação do `setInterval` retorna um `id` - um número de identificação único daquele `setInterval` que pode ser usado para pará-lo.

Lembra que invocações de métodos/funções podem retornar valores? Então... o valor que a invocação do `setInterval` retorna é um número (number). Isso significa que a const `timer` recebeu um número e não uma função. Então não faz sentido invocar `timer()`.

> É o próprio browser que faz essa invocação automaticamente após o intervalo de tempo?

Sim, o `setInterval` é um método assíncrono de uma [API web](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope). Você verá o que é uma API e o que são operações assíncronas na etapa 11.

Ficou mais claro?

---

Issue respondendo a dúvida do aluno Raimundo Rezende após a desabilitação de comentários no Nutror.

**Comment by rezendenetto** [comment]
Perfeito! 👍
Acabei confundindo mesmo, como o primeiro argumento da setInterval é uma função de callback, estava confundindo declaração com invocação, mas agora ficou claro.

A setInterval está sendo invocada no exemplo e a função de callback é que está sendo declarada dentro dos argumentos da setInterval

Obrigado.

**Comment by Roger-Melo** [comment]
No que precisar, é só abrir uma nova issue =)
