### ISSUE TITLE
Aplicação: [JOGO-DA-VELHA-COM-PLACAR]

### ISSUE THREAD

**Issue by Latorreander** [roger-melo-treinamentos/curso-de-js-roger-melo#6707]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Latorreander/app-jogo-da-velha

### Maiores dificuldades durante a implementação

Não consegui pensar em uma forma mais limpa de fazer as possibilidades de vitória no operador condicional if, fiz do jeito que funcionou mas acredito que exista uma forma mais fácil.

### Menores dificuldades durante a implementação

consegui pensar em tudo de forma lenta, indo resolvendo pelo mais fácil até chegar na lógica alvo

**Comment by Roger-Melo** [comment]
@Latorreander manda como issue de dúvida, como recomendei na mensagem no grupo. Senão vai ficar junto das outras issues de análise de aplicações.

**Comment by Roger-Melo** [comment]
@Latorreander dá uma olhada no que mandei no grupo do Telegram dos alunos =)
