### ISSUE TITLE
Etapa 04, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by Mlluiz39** [roger-melo-treinamentos/curso-de-js-roger-melo#672]
Roger no exercício 06 fiquei na dúvida da comparação por que foi comparado com a string  'object' , pensei que teria que ser com Object
```js
const isObject = valeu => typeof valeu === 'object'

console.log(isObject (cat))
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcelo.

Neste caso é necessário especificar uma string `'object'` por que é essa string que a expressão `typeof value` retornará caso `value` seja um objeto.

Você pode comprovar isso se executar (no console do browser, por exemplo) o `typeof` e um valor em seguida:

```javascript
typeof '' // 'string'
typeof {} // 'object'
```

Como o parâmetro `value` armazena um objeto e `typeof value` resulta em `'object'`, no fim das contas, a comparação que está acontecendo por baixo dos panos no exemplo do exercício é essa: `'object' === 'object'`.

`Object` é uma função construtora embutida na linguagem, por isso não faria sentido verificar se o resultado de `typeof value` é igual a `Object`, pois o `typeof` sempre retorna uma string. Você não precisa se preocupar em entender funções construtoras nesse momento, pois elas serão mostradas na etapa 14.

Ficou mais claro?

@Mlluiz39

**Comment by Mlluiz39** [comment]
Boa noite !
Roger ficou muito claro perfeito sua explicação obrigado.

**Comment by Roger-Melo** [comment]
Show @Mlluiz39. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
