### ISSUE TITLE
Resumo da Aula Obtendo e setando atributos - Aula 02-03 da etapa 05

### ISSUE THREAD

**Issue by Latorreander** [roger-melo-treinamentos/curso-de-js-roger-melo#6728]
OBTENDO E SETANDO ATRIBUTOS

 Com o método get atribute() obtemos o valor do atributo de uma tag, dentro dos parênteses inserimos o nome do atributo em forma de string:
```js
 const link = document.querySelector('a')

console.log(link.getAttribute('href'))
```

 Com o setAtribute() podemos alterar o valor do atributo, dentro dos parênteses é acito dois valores, o primeiro é o atributo 0 outro é o novo conteúdo que o atributo irá receber:

```js
link.setAttribute('href', 'https://rogermelo.com.br')

link.innerText = 'website do Roger Melo'


const paragraph = document.querySelector('p')


paragraph.setAttribute('class', 'error3')

console.log(paragraph.getAttribute('class'))
```

A classe style não existe na tag 'p', então o JS cria essa tag:

```js
paragraph.setAttribute('style', 'color: red;' )
```

**Comment by MivlaM** [comment]
Show @Latorreander . Vamo que vamo, rumo à fluência! 🙌
