### ISSUE TITLE
Aplicação: [Quiz JavaScript]

### ISSUE THREAD

**Issue by DanThug** [roger-melo-treinamentos/curso-de-js-roger-melo#673]
- Repositório do Quiz [https://github.com/DanThug/QuizJavaScript.git](url)
- Minhas maiores dúvidas foram em relação a quais nomes atribuir às funções e variáveis, para uma fácil compreensão do código.
- Minhas menores dificuldades foram na criação e execução do código. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @DanThug.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @DanThug.

Parabéns pelo esforço em implementar a primeira aplicação =)

A exibição dos pontos ficou consistente com o visual do restante da aplicação com o uso do alert do bootstrap.

Antes de postar a análise, deixa eu dar uma dica...

Para inserir a url de um repositório em issues do GitHub, basta colar o link desta forma: `[texto do link](url)`. A `url` entre os parênteses deve ser a da página do respositório (https://github.com/DanThug/QuizJavaScript.git).

Vou deixar abaixo alguns pontos de atenção sobre os critérios que vejo que podem ser melhorados.

---

## Lógica

Posso estar equivocado, mas a forma com que o código da função de callback do envio do form foi implementado me faz parecer que você tem uma certa bagagem com orientação a objetos. 

Em JavaScript, criar objetos com métodos é uma prática que pode deixar o código mais complexo e atrapalhar sua evolução conforme for progredindo no curso. 

No treinamento, você perceberá que eu vou mostrar a maioria das soluções usando simples funções ao invés de métodos e, quanto mais você se acostumar a esse design de código mostrado nas aulas, mais rápido irá se adaptar à linguagem =)

---

O `return` no método `showResult` é desnecessário, pois nada está sendo feito com o valor retornado.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no `input` type radio a ser exibido por padrão como "marcado".

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele acredita que seja a verdadeira.

### Inputs e labels

Ao clicar em uma alternativa, o usuário da aplicação precisa posicionar o mouse e clicar exatamente no input type radio. Isso pode causar um certo desconforto, pois o input é muito pequeno.

Por isso, eu preferi demonstrar na aula como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

---

As observações acima fizeram sentido?

**Comment by Roger-Melo** [comment]
@DanThug vou fechar a issue mas no que precisar, é só dar o toque =)
