### ISSUE TITLE
Resumo da Aula Try/catch em requests e erros personalizados - Aula 06-05 da etapa 11

### ISSUE THREAD

**Issue by rafael-rodrigues01** [roger-melo-treinamentos/curso-de-js-roger-melo#6733]
![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/106329803/b0f8cc8b-b0fc-4592-87e3-8c30f873cc67)
![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/106329803/9831835b-f2a7-45d7-8a9a-4a5c956ceaac)
![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/106329803/3c14e0b7-d8d0-4c36-96a2-15a3362f3a2b)

**Comment by MivlaM** [comment]
Show @rafael-rodrigues01. Vamo que vamo, rumo à fluência! 🙌
