### ISSUE TITLE
Resumo da Aula Uma introdução ao Bootstrap - Aula 01-02 da etapa 07

### ISSUE THREAD

**Issue by DevNeves** [roger-melo-treinamentos/curso-de-js-roger-melo#6736]
<h1> Uma introdução ao Bootstrap - Aula 01-02 </h1>

+ Bootstrap é uma biblioteca de componentes front-end (elementos e partes da interface que podem ser ultilizados)

+ Podemos ultilizar elementos predefinidos assim, conseguimos fazer uma interface interessante sem se preocupar muito com o CSS.

+ Melhor maneira de ultilizalo é atraves do CDN dele.

**Comment by MivlaM** [comment]
Show @DevNeves . Vamo que vamo, rumo à fluência! 🙌
