### ISSUE TITLE
Resumo da Aula Tratando erros com try/catch - Aula 06-04

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6738]
### Tratando erros com try/catch 
---

Contornando erros para a aplicacao nao parar de ser executada com try/catch. 
Se o codigo executado lancar algum erro vamos poder executar algum outro codigo e o erro que foi lancado nao vai travar restante do codigo da aplicacao.

Se o codigo lancado dentro do bloco do **try** lancar algum erro o erro e recebido dentro dos parenteces do
**catch** e ainda dentro do bloco do **catch** podemos executar alguma outra acao 

```javascript
try{
  console.log(oi)
} catch(error) {
  console.log(error)
}
console.log('oi')
```

Em JS todo objeto de erro tem as propriedades de **error** e **mensage** que armazenam o erro e a mensagem de erro

```javascript
try{
  console.log(oi)
} catch(error) {
    console.log(error.name, error.message)
  }
}
console.log('oi')

```

A partir das informacoes desse objeto de erro podemos fazer algum tratamento

```javascript
try{
  console.log(oi)
} catch(error) {
  if(error.name === 'ReferenceError' && error.message === 'oi is not defined'){
    const oi = 'const oi criada'
    console.log(oi)
  }
}
console.log('oi')
```

### Quando usar try/catch ??

Quando voce quiser fazer alguma coisa em relacao ao objeto de erro que o **catch** recebe, try/catch existe para
sabermos lidar com o erro que o codigo pode lancar.

try/catch exige mais do poder de processamento do que uma condicionais comuns como if, entao usar muitas vezes o 
try/catch como alternativa do if vai deixar a aplicacao mais lenta

**Comment by MivlaM** [comment]
Show @dzpoke. Vamo que vamo, rumo à fluência! 🙌
