### ISSUE TITLE
Resumo da Aula O evento submit - Aula 01-03 da etapa 06

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6748]
# O evento submit

Anteriormente já vimos que quando agente queria adicionar um evento de clique em um elemento, agente atrelava um **listener de eventos** diretamente no elemento que ia ser clicado. Também sabemos que para enviar o conteúdo de um formulário, um botão "Enviar" vai ser clicado.

Mas acontece que quando agente quer **escutar** o envio de um formulário, ao invés de **atrelhar** o listener de evento no botão "Enviar", agente vai **atrelar o listener de evento diretamente no formulário**, ou seja, na tag **form**. Issto é assim porque no final o que está sendo enviado é o formulário e não o botão, o botão é só um elemento dentro do formulário. Ou seja, o que importa para agente é o **submit** (o envio ) do formulário.

Para ver um exemplo vamos supor o que temos o seguinte código dentro de um arquivo html:
```html
<form action="" class="signup-form">
    <input type="text" id="username" placeholder="user" autofocus>
    <button>Enviar</button>
</form>
```
Agora no código JavaScript que segue vamos capturar o evento **submit** do formulário, ou seja, na tag form vamos colocar um listener de evento que vai escutar quando o formulário for enviado, ou seja, quando o botão dentro do form for cliclado, ou quando o imput estiver com o foco e o usuário pressionar a tecla enter:
```js
const form = document.querySelector('.signup-form');
const usernameInput = document.querySelector('#username')

form.addEventListener('submit', (event) => {
  
  event.preventDefault();             // o método "preventDefault" impede que a página seja recargada quando o botão Enviar é clicado

  console.log(usernameInput.value)           //a propiedade "value"  armazena o conteúdo do input

})

//Então cada vez que o usuário escreva uma coisa dentro de campo input e faça click no botão Enviar, por consola se mostrará o que ele escreveu. Issto é possível porque estamos usando a propriedade "value" do input para capturar o que o usuário escreveu.
```
Outra forma de ter escrito o código anterior seria usando a tag form para obter a referência do input, ou seja, quando um input dentro de um formulário tem um atributo **id** (ou um atributo name), agente pode obter a referência desse input através da referência do formulário e do id do input da seguinte forma:
```js
const form = document.querySelector('.signup-form');

form.addEventListener('submit', (event) => {
  
  event.preventDefault();

  console.log(form.username.value)       

})

//No código acima "form.username" faz referência ao input com a id "username" que está dentro do formulário, portanto usando a propriedade "value" vamos capturar o conteúdo do input.
```
E outra forma de ter escrito o código anterior seria usando o **event.target** encadeado com o id (ou o atributo name também) do input. Esta forma é muito usada na biblioteca **React**:
```js
const form = document.querySelector('.signup-form');

form.addEventListener('submit', (event) => {
  
  event.preventDefault();

  console.log(event.target.username.value)

})

//No código acima o "event.target" faz referência ao formulário, ou seja, é o formulário quem disparou o evento de submit. Portanto "event.target.username" faz referência ao input com a id "username" que está dentro do formulário, e usando a propriedade "value" vamos capturar o conteúdo do input.
```

**Comment by MivlaM** [comment]
Show @OnielStgo. Vamo que vamo, rumo à fluência! 🙌
