### ISSUE TITLE
Obter a chave da api para montar a url da cidade

### ISSUE THREAD

**Issue by MateusCavalheiro-prog** [roger-melo-treinamentos/curso-de-js-roger-melo#6749]
### Etapa da aula

12

### Nome da aula

Obtendo informações da cidade - Aula 01-06

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6371042

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá não estou conseguindo consumir a API da AccuWeather, pois quando faço o request to recebendo um erro "401 Unauthorized", desde a a primeira tentativa após eu criar a chave da api estou recebendo esse erro, fiz uma nova conta na AccuWeather com outro email e estou recebendo o mesmo erro.

Estou com receio de perder o prazo pra receber o code review, teria como eu consumir outra API como a Open Weather no lugar da AccuWeather pra tentar fazer essa aplicação e receber o code review?

Obrigado pela atenção.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MateusCavalheiro-prog. 

Vc está usando o Live server?

Se sim, sobe o projeto no GitHub e avisa aqui para testarmos =)

**Comment by MateusCavalheiro-prog** [comment]
Sim! estou usando o Live server.

repositório: https://github.com/MateusCavalheiro-prog/weather-application-master.git

Esse print é do app dentro do site:

![app-weather-api-key](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/119822795/17e88059-00e3-484b-8629-6b5eee2b8e9e)

Esse print foi o teste de request que fiz no próprio site:

![request-no-proprio-site](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/119822795/09197253-7575-4d85-a7a0-fe51660f7efd)

**Comment by MivlaM** [comment]
Olá @MateusCavalheiro-prog 

Eu fiz alguns testes aqui, e realmente, testei com a chave que você passou na aplicação e não estava funcionando de nenhuma forma. Porém, eu testei a aplicação que você disponibilizou com uma nova chave gerada no site e funcionou completamente. Há algumas possibilidades que você pode tentar:

Entende-se que um dos motivos mais comuns pelos quais você pode encontrar um erro 401 é que o cache e os cookies do seu navegador estão desatualizados, impedindo que a autorização seja aprovada. Aqui, vale a sugestão para que você tente executar a aplicação em um outro browser (só pra tirar do caminho uma possível hipótese de que não há uma configuração em seu browser padrão que está causando o problema). Você também pode optar por deletar todas as chaves antigas, gerar uma nova chave no site da accuweather e, antes de testar a nova chave, derrube o live server. Quando levantar o live server novamente, esteja com a nova chave no arquivo. Sugiro que você faça esses testes e depois comenta aqui em baixo se alguma delas funcionou =)

**Comment by MateusCavalheiro-prog** [comment]
Deu certo! Eu desinstalei o Live Server e reinstalei, troquei a chave antes de usar ele novamente  e mudei pro Firefox ai consegui ter acesso aos dados a API.

Obrigado pela atenção
