### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by eduardosgn** [roger-melo-treinamentos/curso-de-js-roger-melo#675]
Repositório do Quiz: [Link para o projeto](https://github.com/eduardosgn/quizinterativojs)

- Minha maior dúvida foi como implementar os nomes das variáveis, e como implementar o código para que não ficasse muito confuso de ler.

- Minha menor dificuldade foi pensar em como solucionar a atividade no geral.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @eduardosgn.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Eduardo.

Parabéns pelo esforço em construir a primeira aplicação, deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo alguns pontos de atenção baseados em um critério que pode ser melhorado.

---

## Organização de código

### Nomes de variáveis e funções

A `const` results pode ter um nome mais descritivo em relação à ela ser um elemento que contém a pontuação do quiz. Com esse ponto de vista, eu nomearia ela escolhendo alguma das opções abaixo:

- `scoreContainer`
- `quizScoreContainer`
- `finalScoreContainer`

Um outro ponto a considerar na hora de nomear é evitar abreviações que podem não ser tão óbvias caso outra pessoa leia o código. Então eu evitaria abreviar "Answers" em `correctAns`.

Existem casos em que não há problema abreviar. Na declaração do parâmetro `index` de um callback de um `forEach`, por exemplo, é ok abreviar o parâmetro para `i`, por que é sabido que o 2º argumento dessa função corresponde ao index do item do array:

```javascript
myArray.forEach((item, i) => {
  // ...
})
```

Sacou a ideia?

### Comentários

Evite comentários na hora de subir a aplicação para produção.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Se você faz questão de usar comentários como objeto de estudos, é melhor manter duas versões do código; a de produção (sem comentários) e a de desenvolvimento/estudos.

### O princípio das linhas em branco

Linhas em branco quando bem aplicadas indicam, visualmente, a separação entre conceitos.

Ao declarar as consts no topo do código, você utilizou bem as linhas em branco.

Eu só não deixaria linhas em branco nas linhas 9 e 41 (início e fim do código do bloco do callback). É uma convenção iniciar e terminar um bloco com linhas de código. Caso contrário, o olho precisa pular linhas em branco desnecessárias e a fluidez da leitura é prejudicada.

---

Novamente, parabéns pelo esforço =)

As observações acima fizerma sentido?

@eduardosgn

**Comment by eduardosgn** [comment]
Muito obrigado pelas observações prof! as vezes os nomes das variáveis para nós digitando o código esta totalmente coerente.. mas temos que sempre pensar na manutenção do código.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso mesmo =)

Vou fechar a issue mas no que precisar, é só abrir uma nova =D

@eduardosgn
