### ISSUE TITLE
Resumo da Aula Expressões regulares - Aula 01-04 da etapa 06

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6772]
Um site para ver padrões de regex é o regex101.com

Quando criamos campos de formulários, é comum estabelecermos regras de validação, como no caso de um campo de senha, que pode exigir, por exemplo, no mínimo 8 caracteres, incluindo letras maiúsculas e minúsculas, números ou caracteres especiais. Para validar essas regras, usamos as expressões regulares (REGEX).

As expressões regulares são delimitadas pelo símbolo de barra (/) no início e no fim, como em `/JavaScript/gm`. Nesse exemplo, se o usuário digitar uma sequência de caracteres que contenha a palavra "JavaScript", a expressão irá coincidir (dar match), permitindo que o formulário seja enviado corretamente. O termo "match" indica que a expressão foi validada com sucesso.

Se adicionarmos o acento circunflexo (^) no início e o cifrão ($) no final da expressão 
`/^JavaScript$/gm` , a coincidência (match) só será encontrada se a sequência de caracteres digitada pelo usuário for exatamente "JavaScript". Qualquer outra entrada não irá coincidir com a expressão, fazendo com que o formulário não possa ser enviado.

No exemplo de expressão regular `/^[a-z]$/gm`, apenas uma letra minúscula de "a" a "z" pode ser inserida para que a expressão dê match. Qualquer outra entrada, com mais de uma letra ou uma letra maiúscula, não irá coincidir com a expressão, resultando em um erro na validação do formulário.

A expressão regular `/^[a-zA-Z0-9]{6,10}$/gm` valida caracteres alfanuméricos (letras maiúsculas e minúsculas de "a" a "z" e números) e permite um comprimento de 6 a 10 caracteres. As chaves {} representam um quantificador, que especifica o número exato de caracteres ou um intervalo de caracteres permitidos na expressão. Esta expressão é útil em campos de senha ou outros campos em que é necessário um padrão específico de caracteres para validar o formulário.

A expressão regular `/^.{6,10}$/gm` permite qualquer tipo de caractere, incluindo símbolos como @ # % * etc.

**Comment by MivlaM** [comment]
Excelente @dev-jefferson-lopes rumo à fluência! 🎯
