### ISSUE TITLE
Resumo da Aula A Aula Mais Importante do CJRM da etapa 00

### ISSUE THREAD

**Issue by RogDevcodar** [roger-melo-treinamentos/curso-de-js-roger-melo#6774]
Fluência significa construir aplicações web com Java script "puro."
Se for coelhinho não pule etapas e se for tartaruga cuidado para não virar pedra. Tartaruga vai de vagar mas não para, ela vai sem pressa e sem pausa.  O coelho já quer ir pulando etapas sem entender os conceitos direito.
Evite fazer comparações entre você e outros colegas. 
Os 8 marcos para chegar a fluência em Javascripts estão divididos em: Alicerce, validação, evolução e comemoração.
Faça uso do github para por o resumo das aulas, postar dúvidas e enviar projetos.
Fonte de pesquisa fora do CJRM é a documentação MDN.
Vi também a importância da revisão X => Entender não significa aprender. Para aprender é necessário apagar e fazer de novo. Embora esse processo possa parecer demorado, só assim iremos entender para atingirmos a fluência.
A única coisa que cura o medo é a ação. Não importa a descrição das vagas, 80% das descrições de vagas estão mentindo pra você.

**Comment by MivlaM** [comment]
Excelente @RogDevcodar rumo à fluência! 🎯
