### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários - Aula 01-04 da etapa 01

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#6779]
Aprendemos nessa aula o conceito de variáveis, que nada mais é um nome que armazenará um valor para nós. Atualmente podemos declarar uma variável usando as palavras reservadas "let" e "const". Antigamente se declarava variáveis usando a palavra reservada "var", mas esse método caiu em desuso.
Vimos também que para declarar uma variável utilizando a palavra let a declaração fica mais ou menos assim: ``` let = age = 31 ```. e caso seja necessário podemos alterar o valor dessa variável apenas escrevendo o nome da variável seguida do sinal de atribuição e o novo valor, assim ```age = 54```. E para declarar uma variável usando "const" escrevemos ```const points = 100```, o que diferencia o let do const é que enquanto é possível alterar o valor de uma variável declarada com let, com const não existe essa possibilidade, tentar alterar o valor de uma "const" gerará um erro. 
Outra coisa que aprendemos é que existem algumas regrinhas para nomear as variáveis.
Essas regras são:
- Devemos utilizar apenas uma palavra. Nada de espaço separando caracteres.
- Devem conter apenas letras, números, underscore ou cifrão. Não pode começar com número.
- Não pode usar palavras reservadas do javascript como nome de variável.

Por fim, aprendemos como adicionar comentários no nosso código utilizando alguns símbolos. Para uma linha usamos //, para mais de uma linha, como um parágrafo ou trecho de código, por exemplo, podemos usar ``` /* comentário aqui */ ```. Existe um atalho no teclado para fazer isso, caso usemos o vs code. É o ```ctrl + ;```

**Comment by MivlaM** [comment]
Excelente @adlagomes rumo à fluência! 🎯
