### ISSUE TITLE
Resumo da Aula  02-03 Etapa 01

### ISSUE THREAD

**Issue by bivar37** [roger-melo-treinamentos/curso-de-js-roger-melo#679]
**Strings**

São Caracteres entre aspas.
Ex 
`let name = ‘Bivar’`

**1.Podem conter:**

Letras e números.
Ex 
`let name = ‘Bivar37’`

**2.Podem ser concatenadas com o sinal de +**
Ex
`console.log(‘Bivar + ‘ ’ + ‘37’)` // Bivar 37
Nota: Para ter espaço entre duas strings usa-se uma string vazia.

**3.Tem algumas propriedades**
Ex.
.length
	
**4.Tem métodos**
Ex.
`.toUpperCase()`
	Todos caracteres maiúsculos
`.toLowerCase()`
	Todos caracteres minúsculos

Nota : tem pegadinha. 
Abraços
 Bivar

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @bivar37, rumo à fluência! 🚀
