### ISSUE TITLE
Resumo da Aula Conversão de tipos e 3 avisos - Aula 04-04 da etapa 01

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#6797]
**Conversão de tipo** - É possível converter um tipo em outro usando métodos. As vezes será necessário fazer a conversão de um tipo porque alguns métodos só retornam um determinado valor em um tipo específico, sendo necessária sua conversão para devidas manipulações.

**Funções de conversão explícitas**
- Number() -> converte uma string numérica em number. Tentar converter um texto pode resultar em um NaN.
- String() -> converte qualquer tipo em string.
- Boolean() -> alguns numbers e strings, além de objetos podem ser convertidos para true ou false.

As funções de conversão implícitas são feitas pelo próprio javascript antes de comparar valores.

**Comment by MivlaM** [comment]
Boa @adlagomes rumo à fluência! 🔥
