### ISSUE TITLE
Exercicio do CJRM – Etapa 7 – Aplicação: Quiz Interativo OBS: Para as imagens funcionar tem que botar elas dentro de uma pasta images e os js dentro de uma pasta js

### ISSUE THREAD

**Issue by Jubs11** [roger-melo-treinamentos/curso-de-js-roger-melo#68]
Exercicio do CJRM – Etapa 7 – Aplicação: Quiz Interativo

Professor Roger,

Conforme solicitado com relação ao exercício mencionado.

Dúvidas/dificuldades:

  1.Tive problemas com o css no meu primeiro quiz pois não soube qual cores escolher e ai ficou um muito 
     estranho, mas já no segundo quiz eu fiz um pouco melhor visualmente mais ficou mais bagunçado o código

  2.Tive algumas dificuldades de pegar o valor da resposta e fazer com que parecesse que a tela atualizou e foi pra outra pergunta
     mas sem ela atualizar de fato

   3.Tive dificuldades também em organizar as classes .

Menores dificuldades:

Fazer com que o resultado aparecesse na tela.
Resolução do exercicio pode ser vista em:

https://github.com/Jubs11/Etapa-07-Quiz-interativo

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Luiz! Legal os Quizes e os assuntos deles. Parabéns pelo esforço! =)

> Para as imagens funcionar tem que botar elas dentro de uma pasta images e os js dentro de uma pasta js

Você teve dúvidas em como subir as pastas para o GitHub? Se foi o caso, faça um mini-curso de Git/GitHub. Você encontra alguns gratuitos no YouTube. Não demora muito e vale a pena =)

---

Vou deixar algumas observações sobre o código .js da aplicação.

  - **Mantenha a consistência ao nomear variáveis e constantes**
    Escolha nomeá-las ou apenas em português ou apenas em inglês.

  - **Prefira manipular a visibilidade das classes CSS com a propriedade `display`**
    Manipular classes CSS com `z-index` é mais complicado, pois você precisará trabalhar com números ao invés de palavras. Isso tente a deixar o código mais ilegível.

  - **Não use sinal de atribuição em if's**
    Raramente você precisará fazer isso. Sempre use os operadores de igualdade estrita (`===` ou `!==`). Se precisar revisar como eles funcionam, assista novamente a [aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/751262) em que começo a falar deles.
    Observe que no `if` abaixo, foi usado `sectionQuestionOne.style.zIndex = 4`. Essa expressão retorna o valor que a variável recebeu (`4`), por isso o if é executado.

```javascript
    if(sectionQuestionOne.style.zIndex = 4) {
        parede.style.zIndex = 5
        parede.style.backgroundColor = "#ffd1d9"
        sectionQuestionTwo.style.zIndex = 5
    }
```

---

Tente fazer as mudanças acima, subir o código e me enviar. Se tiver dúvidas, pode perguntar que te ajudo =)

@Jubs11

**Comment by Roger-Melo** [comment]
Oi Luiz. Vou fechar a issue. Se não tiver ficado claro ou quiser enviar as modificações, eu reabro ela, ok? =)

**Comment by gustavocoutinh** [comment]
Oi, desculpa pela demora mas esses meses estava corrido e esqueci de reenviar o repositório, mas se quiser pode olhar o repositório que eu fiz as modificações de z-index para display e adicionei o link do quiz.
