### ISSUE TITLE
Etapa 14, nome do vídeo: Introdução a Classes - Aula 02-06

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#680]
Oi professor, tudo bem?
Fiquei um pouco confuso em relação a invocação do construtor. O responsável por invocar o construtor dentro da classe é o operador new, isso está claro, mas a invocação da função construtora User() nada mais é do que o próprio método construtor declarado dentro da classe?
Um outro ponto professor, o método constructor não cria o novo objeto no corpo da classe, mas sim apenas seta propriedades do objeto que é gerado pelo operador new, ou seja, o new cria o objeto e o constructor apenas constrói, modela esse objeto criado em memória pelo new, correto professor?
Confesso que foi senti um impacto nesse inicio da etapa 14, mas estou superando aos pouquinhos seguindo o método rs'

Obrigado desde já professor.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel.

`User` não é uma função construtora. Embora no fim das contas funções construtoras e classes criem objetos, `User` é uma classe. Tanto é que ela foi especificada com a palavra-chave `class` =)

O [constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor) é o método responsável por criar as propriedades do objeto da classe. No código abaixo, a invocação da classe (usando o `new`) criou um novo objeto:

```javascript
class MyClass {}

new MyClass() // MyClass {}
```

Porém, isso não é lá muito útil por que não faz muito sentido invocar uma classe para criar um objeto sem propriedades. É aí que o `constructor` entra =)

Ficou mais claro?

@sou-gabriel

**Comment by sou-gabriel** [comment]
> Ficou mais claro?

Claríssimo professor. Fiquei um pouco confuso a primeira vista, mas agora está claro a ideia.

Muito obrigado =)
