### ISSUE TITLE
Acesso a plataforma

### ISSUE THREAD

**Issue by Renatonapoli** [roger-melo-treinamentos/curso-de-js-roger-melo#6802]
### Etapa da aula

11

### Nome da aula

 Utilizando fetch

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá Roger, tudo bem!

Primeiro quero te parabenizar por todo conteúdo disponibilizado na redes sociais e pela sua didática em transmitir todo conhecimento adquirido durante sua caminhada como desenvolvedor.
Admito que me tornou um desenvolvedor frontend muito melhor.

Venho aqui não com dúvidas mas para relatar que pela primeira vez, depois de quase dois anos, a plataforma de acesso esta fora do ar durante toda manhã, não consigo acessar para revisar os estudos. Fica em loop infinito, apenas o looding em tela.

Agradeço desde já.
Até mais!

@Roger-Melo

**Comment by Renatonapoli** [comment]
Opa, muito obrigado pelo feedback Maykell.
Normalizou aqui e já estou de volta aos estudos.

Agradeço desde já!
Boa semana pra ti.

*Atenciosamente,*
*Renato Napoli Guimarães*

*Tel: **(21) 9 7694-0387 / (21) 9 8722-1919*


Em qua., 17 de mai. de 2023 às 12:16, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, mas qualquer coisa, sinta-se livre para abrir uma nova.
