### ISSUE TITLE
Resumo da etapa 05

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#682]
[Visao 2019.pdf](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/files/6487669/Visao.2019.pdf)
![11](https://user-images.githubusercontent.com/49795140/118369033-36cce500-b579-11eb-987c-32c223a9291b.jpeg)
![10](https://user-images.githubusercontent.com/49795140/118369034-37657b80-b579-11eb-8f90-78538fca3abf.jpeg)
![9](https://user-images.githubusercontent.com/49795140/118369035-37fe1200-b579-11eb-9490-edbcb5b678b3.jpeg)
![8](https://user-images.githubusercontent.com/49795140/118369036-3896a880-b579-11eb-9120-65003f3f6d06.jpeg)
![7](https://user-images.githubusercontent.com/49795140/118369038-392f3f00-b579-11eb-9ae9-4c79c18e48e1.jpeg)
![6](https://user-images.githubusercontent.com/49795140/118369039-392f3f00-b579-11eb-83f9-cdae2cd59859.jpeg)
![5](https://user-images.githubusercontent.com/49795140/118369040-39c7d580-b579-11eb-87c7-38bfad8fd87d.jpeg)
![4](https://user-images.githubusercontent.com/49795140/118369041-3a606c00-b579-11eb-8eb1-876d8ae996ba.jpeg)
![3](https://user-images.githubusercontent.com/49795140/118369042-3af90280-b579-11eb-84e3-3911ecf85a70.jpeg)
![2](https://user-images.githubusercontent.com/49795140/118369045-3b919900-b579-11eb-96cc-08691dbf721a.jpeg)
![1](https://user-images.githubusercontent.com/49795140/118369046-3c2a2f80-b579-11eb-8e86-e0a8577ba261.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @azulinho10, rumo à fluência! 🚀
