### ISSUE TITLE
Resumo da Aula Template HTML e checando as respostas - Aula 01-03 da etapa 07

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6824]
# Interfaz RadioNodeList
La **interface RadioNodeList** representa uma coleção de elementos de radio dentro de uma tag "form" ou uma tag "fieldset"

A interface RadioNodeList herda as propriedades de NodeList, ou seja, uma RadioNodeList é uma estrutura parecida a um arreglo mas não é exatamente um arreglo, portanto tem alguns métodos e propriedades de arreglos tais como a  **length** e **forEach()**.

Para entender melhor vamos supor que temos o seguinte código html:
```html
<form action="">
    <label for="radio">Masculino</label>
    <input type="radio" name="sexo" id="M" value="M">
    <label for="radio">Feminino</label>
    <input type="radio" name="sexo" id="F" value="F">
</form>
```
Agora vamos supor que o usuário selecionou o radio button Masculino, então podemos obter um RadioNodeList da seguinte forma:
```js
const form = document.querySelector('form');

console.log(form.sexo)         //lembrar que podemos acessar elementos dentro do form usando o atributo id ou name

//Resposta:

RadioNodeList(2) [input#M, input#F, value: 'M']
0:  input#M
1:  input#F
length:  2
value:  "M"
[[Prototype]]:  RadioNodeList

//Na resposta acima podemos ver que foi impresso uma RadioNodeList, e que sua propriedade "value" tem o valor "M", por tanto para obter diretamente o "radio button" selecionado podemos faze-lo usando a propriedade "value" da seguinte forma:

console.log(form.sexo.value)              // M
```

**Comment by MivlaM** [comment]
Show @OnielStgo. Vamo que vamo, rumo à fluência! 🙌
