### ISSUE TITLE
Etapa 02, nome do vídeo: Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#683]
Fala Roger, tudo bem?

Tive algumas dúvidas na **questão 5** dessa aula.

Eu vi que você inseriu a declaração de algumas consts dentro do for, com isso sempre que o laço for repetido as consts serão recriadas certo? Isso seria um problema ou é algo comum de se fazer? É mais vantajoso deixar dentro do for, fora do for ou tanto faz? E também caso a const fosse declarada fora do for, então deveria ser declarada como let certo?

Outra dúvida é a seguinte, percebi que para deixar o código o mais legível possível, é preciso usar mais variáveis/constantes, como foi feito nessa aula. Isso acabaria implicando em uma aplicação que usaria mais memória ou em uma aplicação mais pesada? Ou seja, seria um ponto negativo em tentar deixar o código mais legível possível ou não?

Abraços!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, quase xará =)

> sempre que o laço for repetido as consts serão recriadas certo?

Isso mesmo. A cada execução do bloco do `for`, as declarações de variáveis/constantes são declaradas em um escopo diferente do escopo da execução anterior. Você verá os que são escopos na etapa 05 =)

Mas apenas para simplificar... se uma const é declarada dentro de um loop que é executado 3x, à cada execução do loop, essa const é declarada novamente mas em um espaço diferente na memória. Isso faz com que a declaração da const da execução anterior não "colida" com a declaração da execução atual:

```javascript
for (let i = 0; i < 3; i++) {
  const cardinal = i + 1
  console.log(`${cardinal}ª execução do loop`)
}

// 1ª execução do loop
// 2ª execução do loop
// 3ª execução do loop
```

No código acima, na 1ª execução do loop, uma const `cardinal` foi declarada em um espaço da memória, na 2ª execução, uma outra const foi declarada em outro espaço e assim por diante. 

Sacou a ideia?

> Isso seria um problema ou é algo comum de se fazer? É mais vantajoso deixar dentro do for, fora do for ou tanto faz?

Depende do problema que você quer resolver. No exemplo acima, faz mais sentido deixar a declaração de `cardinal` dentro do loop. 

Agora, vão haver casos em que será necessário acumular um valor a cada execução do loop. Nesse tipo de situação, é preciso deixar do lado de fora a let que vai acumular esse valor:

```javascript
let accumulator = 0

for (let i = 0; i < 3; i++) {
  accumulator++
}

console.log(accumulator)
```

No código acima, à cada execução do `for`, accumulator é incrementada e, quando o for termina de ser executado, ela é exibida no console.

Ou seja, como eu preciso acumular um valor à cada execução do `for` e preciso usar esse valor fora do loop, faz sentido que a declaração da let seja feita fora do loop. 

Observe que se a declaração é feita dentro do loop, não é possível incrementar o valor de `accumulator` pois a cada execução do loop, ela é declarada iniciando em zero:

```javascript
for (let i = 0; i < 3; i++) {
  let accumulator = 0

  console.log(accumulator)
  accumulator++
}

// 0
// 0
// 0
```

E também não é possível usar `accumulator` fora do bloco do `for` (você entenderá isso na etapa 05):

```javascript
for (let i = 0; i < 3; i++) {
  let accumulator = 0

  console.log(accumulator)
  accumulator++
}

console.log(accumulator) // ReferenceError: accumulator is not defined
```

E claro, se restarem dúvidas ao chegar na etapa onde mostro escopos, é só abrir uma issue =)

> E também caso a const fosse declarada fora do for, então deveria ser declarada como let certo?

Geralmente sim. O uso de `let` no código é um indicador visual de que aquele valor será modificado no decorrer da aplicação. 

> percebi que para deixar o código o mais legível possível, é preciso usar mais variáveis/constantes, como foi feito nessa aula

No começo, é o que eu indico. 

Com a prática, você vai perceber que "legível" acaba sendo subjetivo, vários autores tem definições diferentes sobre isso. Mas no início, eu prefiro que haja um cuidado especial em deixar o código mais legível, mesmo que isso signifique aumentar o número de linhas. Conforme for avançando no treinamento, eu vou falando sobre isso e você perceberá em quais momentos "quebrar as regras" =)

> Isso acabaria implicando em uma aplicação que usaria mais memória ou em uma aplicação mais pesada? Ou seja, seria um ponto negativo em tentar deixar o código mais legível possível ou não?

Não se preocupe com performance no início. Foque em entender os fundamentos das etapas iniciais. Performance vem depois.

Mas respondendo a pergunta, são microsegundos à mais insignificantes a ponto de merecer sua preocupação. Se tratando de performance, existem outros aspectos que devem ser priorizados (falo sobre isso em etapas mais avançadas) =)

Ficou mais claro?

@rohyer

**Comment by rohyer** [comment]
Boa noite, Roger, desculpe a demora pra responder.

Quase xará? Haha também tem o "Guilherme" então? Bacana!

Ficou tudo muito claro sim! Obrigado pela explicação e disposição!

Estou gostando bastante do curso e sentindo um bom progresso, parabéns pela ótima didática!

Abraços!

**Comment by Roger-Melo** [comment]
@rohyer show! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
