### ISSUE TITLE
Resumo da Aula Validação básica de formulários - Aula 02-02 da etapa 06

### ISSUE THREAD

**Issue by dev-jefferson-lopes** [roger-melo-treinamentos/curso-de-js-roger-melo#6836]
```
const form = document.querySelector('.signup-form')
const feedback = document.querySelector('.feedback')

form.addEventListener('submit', event => {
    event.preventDefault()
    const username = event.target.username.value 
    const usernameRegex = /^[a-zA-Z]{6,12}$/
    const isAValidUsername = usernameRegex.test(username)
    
    if(isAValidUsername){
        feedback.textContent = 'username valido =)'
        return
    }
    feedback.textContent = 'O user name deve conter entre 6 a 12 caracteres e deve conter apenas letras' 
})
```

Este código realiza a validação de um campo de entrada em um formulário e fornece um feedback informativo ao usuário.

No início do código, são armazenadas as referências do formulário (form) e do campo de 	feedback (feedback) em suas respectivas constantes. Em seguida, um ouvinte de evento é adicionado para capturar o evento submit. e uma função de callback que recebe event como parametro.
	
Dentro da função do evento, é utilizado o método preventDefault() para evitar que a página seja recarregada quando o formulário for enviado. O valor do campo de entrada é obtido e armazenado na constante username.

Em seguida, é definida uma expressão regular (usernameRegex) que especifica a regra de validação. No exemplo, são permitidas apenas letras maiúsculas e minúsculas e deve ter entre 6 e 12 caracteres.

Após isso, a constante isAValidUsername é criada para armazenar o resultado do método test() aplicado à expressão regular. Esse método testa o input, se corresponde ao padrão definido na expressão regular.

Se for válido de acordo com a expressão regular, o conteúdo do campo de feedback é atualizado para exibir a mensagem "username válido =)".

Caso contrário, não atender aos critérios especificados na expressão regular, o conteúdo do campo de feedback é atualizado para exibir a mensagem "O username deve conter entre 6 e 12 caracteres e deve incluir apenas letras".

**Comment by MivlaM** [comment]
Show @dev-jefferson-lopes . Vamo que vamo, rumo à fluência! 🙌
