### ISSUE TITLE
const e let

### ISSUE THREAD

**Issue by Andre7973** [roger-melo-treinamentos/curso-de-js-roger-melo#6837]
### Etapa da aula

1

### Nome da aula

Exercício 01

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991172

A minha duvida é sobre o uso de const para armazenar currentYear, pois, neste ano estaremos atribuindo 2023, no entanto, no próximo ano esta const precisará assumir o valor de 2024, sendo assim, acredito que haverá problemas em altera-la não??
Idem para a const myAge, pois, no ano vigente será uma idade, no próximo ano o usuário que estamos fazendo o calculo haverá uma outra idade...
OPINIÃO MINHA: Acredito que se for algo automático, as const usadas para receber o ano atual e a idade atual irão dar problemas, pois, vamos estar alterando os valores desta const... No caso, eu declararia da seguinte forma..
POR FAVOR ME INFORME SE ESTIVER ERRADO 

```js
const myBirthYear = 1973
let currentYear= 2023
let myAge = myBirthYear - currentYear
```

**Comment by MivlaM** [comment]
Olá @Andre7973

> ## A minha duvida é sobre o uso de const para armazenar currentYear, pois, neste ano estaremos atribuindo 2023, no entanto, no próximo ano esta const precisará assumir o valor de 2024, sendo assim, acredito que haverá problemas em altera-la não??

Prefira usar const no lugar de let, quando possível.

Uma let pode ser usada apenas em casos em que é necessário fazer uma reatribuição de valor e esse valor é um tipo primitivo (Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt. Você vai ver mais sobre esses casos específicos conforme você for avançando no treinamento. 

Entretanto, o que você descreveu na dúvida faz sentido e também funciona, porém é mais apropriado para aplicações que envolvem muitas linhas de código e que estejam sujeitas a constantes atualizações no futuro, como esse exercício é um exercício inicial e fechado cujo código não vai passar constantemente por atualizações nos valores de suas variáveis, como as de um software, por exemplo. Acredito que você não precise se preocupar tanto quanto a reatribuição de valores nesse caso, pois o foco desse exercício é introduzir o aluno a esses conceitos de forma didática. Sabendo disso, conforme você for avançando no treinamento, você vai aprender mais sobre as particularidades da const e let, mas por agora, prefira seguir essa boa prática e fazer com que `currentYear` e `myAge` sejam consts.

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
