### ISSUE TITLE
comando indexOf e Slice para recuperar o primeiro nome

### ISSUE THREAD

**Issue by Andre7973** [roger-melo-treinamentos/curso-de-js-roger-melo#6855]
### Etapa da aula

1

### Nome da aula

exercícios da aula 02

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991181

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá, realizando as atividades da aula 02, eu resolvi fazer um exercício a parte para recuperar o primeiro nome de uma cadeia de caracteres para isto utilizei os métodos indexOf e slice.... vc pode me informar se é desta forma que consigo recuperar o primeiro nome do usuário descartando o resto.

```js
let nomeCliente = "Adriana Cristina Santos Souza"
let espacoBco = nomeCliente.indexOf(" ")
console.log(`Olá ${nomeCliente.slice(0,espacoBco)}, seja bem vindo ao sistema.`)
```

**Comment by Roger-Melo** [comment]
Olá @Andre7973. 

O meu comprometimento e o da equipe está em ajudar a resolver os exercícios do CJRM. Recomendo que na primeira vez que estiver fazendo o CJRM, você foque apenas nas baterias de exercícios do treinamento. No CJRM, você ainda verá muitas formas de resolver até mesmo esse desafio que vc postou. 

```js
const nomeCliente = 'Adriana Cristina Santos Souza'
const [primeiroNome] = nomeCliente.split(' ')

console.log(primeiroNome)
```

Essa é uma forma de resolver, mas não faz sentido explicar as linhas deste código agora por que são coisas que você verá à fundo no CJRM. Neste caso, qualquer explicação aqui não vai substituir a jornada que você precisa trilhar para entender de fato.

Vou repetir pq quero deixar claro: na primeira vez que estiver fazendo o CJRM, foque apenas nas baterias de exercícios do treinamento, por que isso é o que vai te dar a base pra depois resolver exercícios de fora.

Foco no CJRM.

**Comment by Andre7973** [comment]
Fala Roger e equipe, tudo bem??? Quanto a pergunta  que fiz acima, elas eram referente a aula 2 -aula 03 -01. Na aula Métodos comuns de strings - Aula 02-04 foram abordados conceitos sobre  indexOf, lastIndexOf, Slice e eu realizei todos os exercícios postados na aula e não desviei do teu conteúdo, eu apenas  resolvi perguntar "SE" conseguia recuperar o primeiro nome de uma cadeia de caracteres com o conteúdo que vc passou até aquela aula, era uma resposta de SIM ou NÃO.... quanto ao método split que vc passou acima nós não vimos ainda até a aula número 2, no entanto, eu consegui recuperar o primeiro nome daquela string utilizando apenas os conceitos ministrados naqueles tópicos referente aos métodos da aula de string. Repetindo, eu queria saber se o que fiz era uma boa prática ou não. 

** let nomeCliente = "Adriana Cristina Santos Souza"
** let espacoBco = nomeCliente.indexOf(" ")
** console.log(`Olá ${nomeCliente.slice(0,espacoBco)}, seja bem vindo ao sistema.`)

OBS: Não é permitido ao cursista tentar criar algo("com os conteúdos abordados em aula") e perguntar se esta correto a aplicação de determinado conteúdo para resolver um problema?

**Comment by MivlaM** [comment]
Olá @Andre7973

Você pode fazer esse tipo de pergunta também, mas o que geralmente recomendamos aos alunos que estão começando o curso é seguir a risca o que é ensinado e geralmente focar mais em aprender e entender os exercícios que estão na lista, pois eles são os mais importantes para construir uma base que permitirá fazer dos mais diversos tipos de questões futuramente. 

Quanto a funcionalidade do seu código, ele está ok e funciona também. A única observação que eu faria no momento é trocar as `lets` por `consts`, pois essas variáveis não estão passando por nenhuma retribuição de valor, esse conceito também vai ser abordado ao longo do treinamento, portanto, não se preocupe muito com isso agora. É possível que haja vários caminhos para chegar em um resultado. Se você conseguiu chegar numa solução, com o que aprendeu até agora, e a sua solução funciona conforme o objetivo do exercício, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Entretanto, tenha em mente que futuramente, você vai ir aprendendo novas maneiras de chegar ao mesmo resultado que você obteve acima, porém com um menor número de linhas de código e de forma mais simples, como o exemplo que o Roger mostrou acima.

Com a prática, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, entende? =)

Acredito que seja isso. Se restou alguma dúvida, sinta-se livre para comentar logo abaixo que eu vou te ajudar.

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
