### ISSUE TITLE
Sobre o uso de constantes com o mesmo nome repetidas vezes (quando estão contidas em loops diferentes)

### ISSUE THREAD

**Issue by widneyds** [roger-melo-treinamentos/curso-de-js-roger-melo#6858]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 02 - Aula 03-01

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991198

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Gostaria de saber se há problema em utilizar constantes com mesmo nome repetidas vezes, desde que elas estejam dentro de loops diferentes? A princípio eu diria que sim, mas como nesta aula houve essa repetição, quero entender se foi algum erro ou se é válido fazer esse tipo de uso.

Estou me referindo aos exercícios 04 e 06, onde no momento da refatoração de cada exercício teve a modificação de seus respectivos array[index] (dentro do for) para uma const com o mesmo nome (number).
```js 
/*
  04

  - Utilize um for loop para gerar um novo array com apenas os números entre  
    11 e 90 presentes no array "numbers" (incluindo 11 e 90);
  - Exiba o novo array no console;
  - O resultado deve ser: [34, 46, 90, 25, 11, 89, 76].
*/

const numbers = [7, 92, 34, 46, 90, 25, 11, 3, 89, 76, 99];
const numbersBetween11And90 = [];

for (let i = 0; i < numbers.length; i++) {
  const number = numbers[i];
  const isNumberBetween11And90 = number >= 11 && number <= 90;
  
  if (isNumberBetween11And90) {
    numbersBetween11And90.push(number);
  }
}

console.log(numbersBetween11And90);
```

```js
/*
  06

  - Abaixo do array "randomNumbers", utilize um for loop para gerar 2 novos  
    arrays: um array com apenas os números ímpares do "randomNumbers" e um outro  
    array com apenas os números pares;
  - Após isso, utilizando os dois arrays que você criou, exiba a frase abaixo  
    no console, substituindo "XX, XX e XX" pelos números corretos. Os números  
    da frase não devem ser inseridos com a notação "item[index]" e os "e" antes  
    do último número ímpar e do último número par devem constar na frase;
  
  - Dica: para saber se um número é par, o restante da divisão dele por 2 deve  
    ser 0.

  "Numeros ímpares: XX, XX e XX. Números pares: XX, XX e XX."
*/

const randomNumbers = [73, 4, 67, 10, 31, 58];
const oddNumbers = [];
const evenNumbers = [];

for (let i = 0; i < randomNumbers.length; i++) {
  const number = randomNumbers[i];
  const isOddNumber = number % 2 == 1;
  
  if (isOddNumber) {
    oddNumbers.push(number);
  } else {
    evenNumbers.push(number);
  }
}

const oddNumbersString = oddNumbers.join(', ').replace(', 3', ' e 3');
const evenNumbersString = evenNumbers.join(', ').replace(', 5', ' e 5');

console.log(`Números ímpares: ${oddNumbersString}. Números pares: ${evenNumbersString}.`);
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @widneyds

> ## Gostaria de saber se há problema em utilizar constantes com mesmo nome repetidas vezes, desde que elas estejam dentro de loops diferentes?

A questão da nomenclatura é algo que você vai ver constantemente sendo abordada ao longo do curso. No entanto, como foi o caso desta aula que você viu a correção dos exercícios, haverá casos em que utilizar uma const em um bloco de código de um outro escopo com um mesmo nome que já foi utilizado anteriormente na aplicação será a melhor opção em termos de legibilidade. Vale a pena ressaltar também a questão da facilidade na hora de escrever o código e torná-lo de simples entendimento para quem for ler esse código depois, nesses casos, acredito que um nome familiar a algum outro usado anteriormente pode ser bastante interessante para a aplicação. 

Consegui resolver a sua dúvida? Caso ainda tenha ficado confuso, sinta-se livre para comentar que te ajudarei! =)

**Comment by widneyds** [comment]
> Consegui resolver a sua dúvida? Caso ainda tenha ficado confuso, sinta-se livre para comentar que te ajudarei! =)

Olá @MivlaM. Sim, agora entendi, obrigado por esclarecer minha dúvida!

Então já que posso fazer uso sem problemas, com certeza irei continuar utilizando esse mesmo padrão. Porque de fato é muito bom em questão de legibilidade.
