### ISSUE TITLE
Sobre função e for loop

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#6869]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991207

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá Roger, na resolução do exercício 5 dessa aula, você criou uma função que retorna um número e criou um for loop fora da função. Eu resolvi essa questão criando o for loop dentro da função, assim:

```js
const positiveNumbers = function (array) {
  for (let i = 0; i < array.length; i++){
    if (array[i] > 0) {
      positiveAmount++
    } else {
      negativeAmount++
    }
    totalNumbers++
  }
  return `O array "randomNumbers" possui ${totalNumbers} números, sendo ${positiveAmount} positivos e ${negativeAmount} negativos.`
}
```
Existe alguma vantagem em escrever a function e o for separados ou tanto faz?

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @adlagomes

Para esse momento que você está no treinamento, o seu código funciona também. Há tanto vantagens quanto desvantagens em deixar o for dentro da função, e você verá cada detalhe especificamente sobre elas nas aulas de escopos, esses assuntos serão abordados mais à frente no treinamento. A minha recomendação para vc no momento é apenas entender que é possível que haja vários caminhos para chegar em um resultado. Se a sua solução funciona conforme o exercício pediu, o mais importante num primeiro momento vc já fez, que é fazer funcionar. Com a prática e conforme você for avançando no treinamento, você pode voltar em códigos que implementou no passado e melhorá-los baseando-se em novos conhecimentos que você adquiriu, entende? =)

Compreenda também que é importante que você entenda a lógica da forma que os exercícios são resolvidos na correção, pois nela há princípios que serão intensificados conforme você avança no CJRM.

Ok? Sinta-se livre para comentar logo abaixo caso ainda tenha alguma dúvida =)
