### ISSUE TITLE
uso método includes()

### ISSUE THREAD

**Issue by AngelicaCamp** [roger-melo-treinamentos/curso-de-js-roger-melo#6877]
### Etapa da aula

2

### Nome da aula

Correção dos exercícios da aula 03 -Aula 01-01

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991202

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

```js
for (let i=0; i < sentence.length; i++){
  if (sentence[i] === 'certeza'){
    continue
  }
```

Tentei usar também no if a seguinte expressão:

```js
if (sentence.includes('certeza'))
```
Porém, não funcionou. Poderia me explicar porque?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @AngelicaCamp! 

Isso mesmo, se a expressão `sentence.includes('certeza')` for inserida como condição do `if`, a condição sempre resultará em `true` (pq o array contém um item `'certeza'`) e o bloco do `if` vai ser executado a cada iteração do `for` =)

Se vc inserir um `console.log()` dentro do `if`, irá constatar que o `if` basicamente foi executado para cada item do array. E como no bloco do if há um `continue`, o código abaixo do `if` não é lido:

```js
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']
let newSentence = ''

for (let i = 0; i < sentence.length; i++) {
  if (sentence.includes('certeza')) {
    // 👇🏻 experimente inserir este console.log e veja o resultado no console
    console.log('If executado. O código abaixo do bloco não será lido')
    continue
  }

  newSentence += `${sentence[i]} `
}

console.log(newSentence)
```

Como o cóigo abaixo do if nunca é lido, a reatribuição da let `newSentence` (abaixo do if) não acontece, por isso `console.log(newSentence)` exibe o valor inicial que ela tem (string vazia). 

Está ficando mais claro? =)

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
