### ISSUE TITLE
Resumo da Aula A condicional switch e exercícios - Aula 03-04 da etapa 02

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#688]
# Switch Statement

o Switch statement é um outro tipo de controle de fluxo, é semelhante ao if / if else, porém é mais usado quando é necessário realizar várias checagens. Também é possível fazer isso com o if, porem o switch é mais adequado para esses casos.

```js
const grade = 'A';

switch (grade) {
  case 'A':
    console.log('Você tirou nota A');
    break;
  case 'B':
    console.log('Você tirou nota B');
    break;
  case 'C':
    console.log('Você tirou nota C');
    break;
  case 'D':
    console.log('Você tirou nota D');
    break;
  case 'E':
    console.log('Você tirou nota E');
    break;
  default:
    console.log('Nota Inválida');
}
```

É necessário ter o break dentro de cada case para que quando um case for executado, nenhum outro abaixo dele seja executado também. Se nenhum dos cases for executado então o default será executado e ele não precisar ter break já que não existe nenhum case após ele.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer, rumo à fluência! 🚀
