### ISSUE TITLE
Resumo da Aula 01 - 04 da etapa 01

### ISSUE THREAD

**Issue by wellmelo** [roger-melo-treinamentos/curso-de-js-roger-melo#6882]
# Constantes, Variáveis e Comentários

---

## Tipos de variáveis

`Variável` é responsável por armazenar um `valor`.

-   Você pode armazenar `textos`, `numeros`, `emails`,

Uma váriavel pode ser declarada como `let` ou `const`.

-   `let` - **aceita** retribuição de valores.
-   `const` - **não aceita** retribuição devalores para.
-   `var` - **forma antiga** de se criar variáveis. (não é recomendado o uso)

```javascript title="exemplo de let"
let age = 31;
let currentYear = 2020;

console.log(age, currentYear); //retorna: 31 2020

age = 35; //estamos retribuindo um novo valor

console.log(age); //retorna: 32
```

Uma `let` pode ser usada apenas em casos em que é necessário fazer uma `reatribuição de valor` e esse valor é um tipo primitivo:

-   **Numbers, Strings, Booleans, Null, Undefined, Symbol e BigInt.**

```javascript title="exemplo de const"
const points = 100;

console.log(points); //retorna: 100

// se dentro do mesmo script tentarmos reatribuir
// um valor para a `const points`, retonará error, exemplo:

const points = 100;

points = 101;

console.log(points); //retorna: TypeError: Atribuição à variável constante.
```

## Regras para nomear variáveis:

Uma váriavel deve ser uma `única palavra`.

-   Para utilizar 2 ou mais palavras, escreva a segunda palavra junta com a `primeira letra maiúscula`. Convenção chamada `camelCase`.

```javascript
let currentYear = 2020;

console.log(age, currentYear);
```

-   Nomes de váriaveis podem ter apenas `letras`, `números`, `underscore _ ` ou `cifrão`. Mas o nome `não pode` começar com número.

```javascript title="Exemplo de bons nomes"
idade;
minhaIdade;
inicio;
corInicial;
valorFinalDeSaida;
audio1;
audio2;
```

```javascript title="Exemplos ruins de nomes"
1
a
\_12
minhaidade
MINHAIDADE
var
Document
skjfndskjfnbdskjfb
esseeumnomedevariavelbemlongoeruim
```

-   Alguns nomes não podem ser utilizados porque já são `palavras reservadas` pelo JS. `let`, `const` ou `var` (como usado acima) são exemplos.

Lista com palavras `reservadas da linguagem`:

-   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

## Comentários

É possível fazer comentário de uma linha, inserindo 2 `//` no início da linha.

```javascript
// let myName = Wellington;
```

É possível fazer comentário em bloco, adicionando `/* conteúdo */`

```javascript
/*
const cars = ['Saab', 'Volvo', 'BMW'];

// Exemplo de acesso aos dados de um array:
console.log(cars); //Retorna: (3) ['Saab', 'Volvo', 'BMW']
*/
```

**Comment by MivlaM** [comment]
Show @wellmelo. Vamo que vamo, rumo à fluência! 🙌
