### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#6884]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/OnielStgo/quiz

### Maiores dificuldades durante a implementação

Mudar as cores da aplicação usando Bootstrap

### Menores dificuldades durante a implementação

- Selecionar todas as tags "inputs".
- Apagar a mensagem de erro ("Escolha uma opção") correspondente, depois de selecionar uma opção.

**Comment by MivlaM** [comment]
Olá @OnielStgo

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou analisar sua aplicação =)

Mas antes disso, verifiquei a sua aplicação e identifiquei que alguns critérios para que a análise seja feita estão em falta.

O critério é o seguinte:

## Critério 2: A aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas da construção da aplicação.

Para esse critério, estão irregulares duas funções: `setErrorMsg` e `handleClickOnInputs`. Essas funções são relativas a novas funcionalidades que não foram mostradas na aplicação original, como a de exibir uma mensagem caso o usuário não tenha marcado uma opção. De acordo com o critério, a aplicação deve conter apenas as funcionalidades exibidas da primeira aula que começa o desenvolvimento do quiz até a aula "Exibindo a pontuação - Aula 02-01", da etapa 07. Eu recomendo que você revise essa etapa para conseguir visualizar melhor o que está sendo demandado. 

Contudo, tudo isso é muito interessante que você tenha feito, mas novas funcionalidades não devem ser adicionadas agora, o mais importante no momento que estamos analisando uma aplicação é ver se o aluno assimilou e conseguiu compreender bem o que foi falado até aqui. A sua capacidade de ler e seguir à risca o que foi pedido também está sendo analisada. Foi descrito no email "[Alunos CJRM] Análise de aplicações" que a aplicação não tenha funcionalidades que ainda não foram mostradas nas aulas.  A prioridade é fazer funcionar com o que foi mostrado nas aulas, notavelmente até a última aula de construção do quiz antes da demanda para enviar a sua aplicação para análise. O que não foi mostrado nas aulas não será analisado. Depois, quando estiver em etapas mais avançadas, você vai ter mais bagagem e pode voltar nesse código e refatorá-lo.

Eu recomendo que você salve esse email em algum lugar e marque ele com estrela (no gmail). Por que ele é importante e você terá que voltar nele quando enviar as aplicações.

Solicito que, por favor, remova as funcionalidades relativas às funções acima para podermos prosseguir com o processo de análise de aplicação.

Avise por aqui quando fizer a mudança =)

Fico no aguardo.

**Comment by OnielStgo** [comment]
Boa noite  Maykell,

Peço desculpa por ter colocado funcionalidades a mais. Acabei de
eliminá-las agora.

Att,

Em ter., 23 de mai. de 2023 às 09:43, MivlaM ***@***.***>
escreveu:

**Comment by OnielStgo** [comment]
Olá Maykell,

Muito obrigado por toda a explicação. Achei todas as observações que você
fez *muito boas*. Com certeza vou revisar este e-mail várias vezes no
futuro próximo para fixar as dicas.

Att,

Em qui., 25 de mai. de 2023 às 12:01, MivlaM ***@***.***>
escreveu:

**Comment by MivlaM** [comment]
Ok! Vou fechar essa issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
