### ISSUE TITLE
Etapa 04 - Objetos, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#69]
Roger, estou com duvida nesse exercício.
Por exemplo, eu tentei usando um **switch**
mais acabei me engando, pensei que era para comparar
os tipos também.

E também fiquei com duvida novamente nos colchetes do return,
ele serve como uma verificação?

/*
  09

  - Crie uma função que recebe um parâmetro 'type';
  - Dentro da função, crie um objeto com as seguintes propriedades:
    - null, que recebe a mensagem 'Seta, explicitamente, uma variável sem valor.'
    - undefined, que recebe a mensagem 'Representa um valor não-setado.'
    - object, que recebe a mensagem 'Arrays, Datas, Objetos literais, Funções, etc.'
  - Se o valor que o parâmetro type receber corresponder à alguma das 3  
    propriedades, retorne a mensagem que a propriedade armazena;
  - Teste a função, exibindo no console a mensagem de cada propriedade.
*/
 

```js

const getType = type => {
  const obj = { 
    null : 'Seta, explicitamente, uma variável sem valor.',
    undefined : 'Representa um valor não-setado.',
    object : 'Arrays, Datas, Objetos literais, Funções, etc.'
  }
  
  return obj[type]
}

console.log(getType('null'))
console.log(getType('object'))
console.log(getType('undefined'))

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Edinaldo.

> Se o valor que o parâmetro type receber corresponder à alguma das 3 propriedades, retorne a mensagem que a propriedade armazena;

Esse é o ponto chave do exercício. A sintaxe `objeto['propriedade']` resulta no valor da propriedade que tem o mesmo nome da string inserida dentro dos colchetes. 

Recomendo que reassista a [aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/816557) em que apresento a sintaxe de colchetes para acessar propriedades. Depois de revê-la, acho que ficará mais claro.

Se depois de assistir ainda houverem dúvidas, é só dar o toque =)

**Comment by naldowebdeveloper** [comment]
@Roger-Melo Entendi  vou com mais calmo no curso,
esta muito acelerado.

Entendi o sentido dos colchetes.

**Comment by Roger-Melo** [comment]
Legal Edinaldo. Vou fechar as issues por agora, mas no que precisar, é só abrir uma nova =)
