### ISSUE TITLE
Resumo da Aula Variáveis e escopo de bloco - Aula 02-02 da etapa 04 - Objetos

### ISSUE THREAD

**Issue by widneyds** [roger-melo-treinamentos/curso-de-js-roger-melo#6903]
### Principais pontos desta aula:
- Escopo é a área em que o valor de uma variável está disponível para uso;
- Toda variável está limitada ao escopo em que foi criada, porém caso ela esteja na raiz do documento então terá escopo global;
- Dentro de um mesmo escopo, não é possível criar uma variável com o mesmo nome de outra que já foi criada.  Porém, é possível que variáveis de mesmo nome sejam criadas em escopos diferentes;
- A palavra chave `var` (que era comumente usada em versões anteriores do JavaScript) ignora o escopo em que está inserida, tendo sempre um escopo global. 
```js
let age = 31;

if (true) {
    let age = 41;
    console.log(`dentro do 1° bloco de código: ${age}`); // Expected output: "dentro do 1° bloco de código: 41"

    if (true) {
        console.log(`dentro do 2° bloco de código: ${age}`) // Expected output: "dentro do 2° bloco de código: 41"
    }
}

console.log(`fora do bloco de código: ${age}`); // Expected output: "fora do bloco de código: 31"
```

**Comment by MivlaM** [comment]
Show @widneyds. Vamo que vamo, rumo à fluência! 🙌
