### ISSUE TITLE
Resumo da Aula Numbers - Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by fabiocosta123** [roger-melo-treinamentos/curso-de-js-roger-melo#6933]
// inteiros e decimais

const radius = 10;
const pi = 3.14;

console.log(radius,pi);

// operadores aritiméticos
const reminder = 5 % 2;
console.log(reminder);

const area = pi * radius ** 2;
console.log(area);
const crazyOperation = 5 * (10-3) ** 2;
console.log(crazyOperation);

// ordem de operações

// 1 parenteses
// 2 expoentes ou raizes
// 3 multiplicação e divisao
// 4 adicao e subtração

// operadores de incremento e decremento
let postLikes = 10;
//postLikes = postLikes + 1;
postLikes++;

console.log(postLikes);

// Nan - not a number 
console.log(7 / "oi");

// concatenação de string com numero 
const likesMessage = 'O post tem ' + postLikes + ' likes';

console.log(likesMessage);

**Comment by MivlaM** [comment]
Excelente @fabiocosta123 rumo à fluência! 🎯
