### ISSUE TITLE
Etapa 14, nome do vídeo: Correção dos exercícios da aula 03 da etapa 14 - Aula 01-09

### ISSUE THREAD

**Issue by GabrielMerigo** [roger-melo-treinamentos/curso-de-js-roger-melo#694]
Fala Roger! Tudo bem? Eu fiquei com um pouco de dúvida do porquê eu devo usar uma IIFE ao invés de fazer a atribuição de variavel. E para quais casos seria ideal ou melhor usar uma IIFE? para quais finalidades ela é necessária e desnecessária?

Ela é necessária apenas para o caso mostrado abaixo?
```js

const state = (() => {
  let exchangeRate = {}
  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        showAlert(
          { message: 'O objeto precisa ter uma propriedade convertion_rates.' }
        );
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
}
)()
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Gabriel! Tudo certinho, e tu? xD

No exemplo mostrado na aula, eu usei a IIFE para "fixar" a `exchangeRate` na memória e manter a referência dela "viva" para usar os métodos (closures) `setExchangeRate` e `getExchangeRate` quando necessário. E claro, para fazer com que `exchangeRate` exista apenas no escopo da função e não haja a possibilidade dela ser acessada diretamente. 

O código abaixo tem o mesmo princípio:

```javascript
const state = (() => {
  let counter = 0

  return {
    getCounter: () => counter,
    setCounter: newCounterValue => {
      counter = newCounterValue
      return counter
    }
  }
}
)()

state // {getCounter: ƒ, setCounter: ƒ}
state.setCounter(7) // 7
state.getCounter()  // 7
```

`state` armazenou o objeto que a execução da IIFE retornou e os métodos `getCounter` e `setCounter` desse objeto guardam uma referência de `counter`. Se alguém quiser acessar ou manipular o counter, terá que usar os métodos. [Aqui](https://medium.com/javascript-scene/encapsulation-in-javascript-26be60e325b4) você pode saber mais sobre a importância desse design de código.

Observe que se ao invés da IIFE eu usasse uma função tradicional, `state` receberia uma função e a cada invocação dela, um novo `obj` recebendo `{}` seria declarado na memória:

```javascript
const state = () => {
  let obj = {}

  return {
    getCounter: () => obj,
    setCounter: newCounterValue => {
      obj = newCounterValue
      return obj
    }
  }
}

state().getCounter() === state().getCounter() // false
```

Claro que eu poderia invocar `state` e armazenar o objeto em uma `const`, mas aí perderia o sentido, pois o objetivo é não deixar `obj` exposto globalmente.

No exemplo da aula, eu queria que a let que eu declarei dentro da função fosse declarada apenas 1x e toda vez que eu usasse os métodos do objeto `state`, o objeto da let `exchangeRate` fosse usado. 

Isso sem falar na verificação dentro do `setExchangeRate` que evita que o objeto `exchangeRate` receba um valor não-adequado.

Sacou a ideia?

Sobre o uso tradicional das IIFES, eu pretendo falar disso em outra oportunidade no treinamento, mas antigamente, elas eram usadas para não deixar variáveis no escopo global de uma aplicação. Com a chegada do ES Modules (também um assunto sobre o qual ainda vou falar), IIFES não são mais necessárias, pois ES Modules tem escopo próprio, ou seja, não deixam variáveis "vazarem" para o escopo global. Você pode ver mais sobre isso nos links que deixarei abaixo:

- [IIFE - MDN](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)
- [JavaScript Modules: From IIFEs to CommonJS to ES6 Modules](https://ui.dev/javascript-modules-iifes-commonjs-esmodules/)

Ficou mais claro?

@GabrielMerigo

**Comment by GabrielMerigo** [comment]
Hmm, saquei. Mas por que é necessário a "auto invocação" na IIFE? isso mudaria algo no retorno do objeto? 

Por que não é mais fácil eu criar a função normal e apenas invoca-la abaixo? Esse ponto que eu não saquei muito bem...

**Comment by Roger-Melo** [comment]
> Hmm, saquei. Mas por que é necessário a "auto invocação" na IIFE? isso mudaria algo no retorno do objeto?

Toda IIFE, por definição, é auto-executável. Por isso o nome "Immediately Invoked Function Expression" =)

> Por que não é mais fácil eu criar a função normal e apenas invoca-la abaixo? Esse ponto que eu não saquei muito bem...

Vc pode criar a função, mas observe abaixo o que iria acontecer se fizesse isso...

Imagine que quando a página for carregada, eu precise atribuir um novo objeto para a `exchangeRate`:

```javascript
const state = () => {
  let exchangeRate = {}

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
}

// {conversion_rates: 1} é atribuído para a let exchangeRate (dentro de state)
state().setExchangeRate({ conversion_rates: 1 })
```

Agora imagine que eu precise acessar o objeto `exchangeRate` em duas funções diferentes da aplicação:

```javascript
const state = () => {
  let exchangeRate = {}

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
}

state().setExchangeRate({ conversion_rates: 1 })

const func1 = () => {
  console.log(state().getExchangeRate())
}

const func2 = () => {
  console.log(state().getExchangeRate())
}

func1() // {}
func2() // {}
```

Se vc executar o código acima, verá que a invocação das funções resultou em um objeto vazio. Isso aconteceu por que cada vez que `state()` é invocada, um novo objeto `exchangeRate` é criado na memória.

Ou seja, o objeto no qual a expressão `state().setExchangeRate({ conversion_rates: 1 })` resultou não foi aproveitado dentro de func1 e func2. Para aproveitar o mesmo objeto, é necessário declarar uma const no escopo global que armazene o objeto:

```javascript
const state = () => {
  let exchangeRate = {}

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
}

const globalConst = state().setExchangeRate({ conversion_rates: 1 })

const func1 = () => {
  console.log(globalConst)
}

const func2 = () => {
  console.log(globalConst)
}

func1() // {conversion_rates: 1}
func2() // {conversion_rates: 1}
```

O problema disso é que, diferente da abordagem com IIFE, uma const global desnecessária foi declarada e apesar dessa const agora armazenar o objeto `exchangeRate`, as referências dos métodos `setExchangeRate` e `getExchangeRate` foram perdidas. Ou seja, o objeto foi exposto globalmente e só será possível manipulá-lo acessando-o diretamente (através da `globalConst`).

---

Com IIFE, eu consigo usar exatamente o mesmo objeto `exchangeRate`, mas:

- sem declarar variável global;
- sem manipular `exchangeRate` diretamente;
- sem perder as referências dos métodos `getExchangeRate` e `setExchangeRate`.

```javascript
const state = (() => {
  let exchangeRate = {}

  return {
    getExchangeRate: () => exchangeRate,
    setExchangeRate: newExchangeRate => {
      if (!newExchangeRate.conversion_rates) {
        console.log('O objeto precisa ter uma propriedade convertion_rates.')
        return
      }

      exchangeRate = newExchangeRate
      return exchangeRate
    }
  }
})()

const func1 = () => {
  console.log(state)
}

const func2 = () => {
  console.log(state)
}

func1() // {getExchangeRate: ƒ, setExchangeRate: ƒ}
func2() // {getExchangeRate: ƒ, setExchangeRate: ƒ}
```

Para comprovar que as referências de `state` dentro das funções armazenam o mesmo objeto, eu posso fazer as duas funções retornarem `state` e fazer uma comparação:

```javascript
const func1 = () => {
  return state
}

const func2 = () => {
  return state
}

console.log(func1() === func2()) // true
```

E claro, eu posso manipular o valor de `exchangeRate` dentro de uma das funções, por que o objeto state contém os métodos `setExchangeRate` e `getExchangeRate` (que mantém uma referência única e viva de exchangeRate):

```javascript
const func1 = () => {
  // retorna o obj {conversion_rates: 1}
  return state.setExchangeRate({ conversion_rates: 1 })
}

const func2 = () => {
  // retorna o mesmo obj {conversion_rates: 1}
  return state.getExchangeRate()
}

console.log(func1() === func2()) // true
```

Clareou mais as ideias? =)

@GabrielMerigo

**Comment by Roger-Melo** [comment]
@GabrielMerigo vou fechar a issue mas no que precisar, é só dar o toque =)

**Comment by GabrielMerigo** [comment]
Oh, perdão Roger. Acabei caindo no esquecimento da Issue. Mas clareou 100% meu querido. Obrigado!!!

**Comment by Roger-Melo** [comment]
Tranquilo @GabrielMerigo. Quando eu for na sua cidade, tu me paga uma coca 😄
