### ISSUE TITLE
Nao consigo carregar o app.js no index.html. Erro no navegador. Erro anexo com foto

### ISSUE THREAD

**Issue by juniormelo45** [roger-melo-treinamentos/curso-de-js-roger-melo#6963]
### Etapa da aula

1

### Nome da aula

aula 01-02

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991169

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Professor... fiz tudo certo nesta aula inicial...no entanto mesmo com o live server ligado, arquivo app.js, criado com alert e console log, nao aparece no inspector do meu navegador chrome! Ele so atualiza o index.html, mas nao atualiza o arquivo js. Coloquei o <script> './app.js '</script> no index.html... tudo certinho e ele nao atualiza, nao lê no console!!
Enviei um issue do navegador em  foto , em anexo.

grato,
jose

@Roger-Melo
![Screen Shot 2023-05-27 at 18 43 13](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/112781520/b35e71ea-467f-44a7-8d7f-b8f789bb12a8)

**Comment by OnielStgo** [comment]
Olá Juniormelo45, tudo bem?

Eu sou um estudante do curso assim como você, mas vi que você tem uma dúvida e talvez eu possa te ajudar.
Vi que suas tags script não tem o atributo src (este atributo especifica o caminho do arquivo JavaScirpt que deve ser carregado).
Tenta mudar <script> './app.js '</script> pelo seguinte:
```js
<script src="./app.js"></script>
```

**Comment by juniormelo45** [comment]
Olá Oniel. Agradeço o retorno. No código coloquei o <script src="./app.js"></script>. Escrevi a sintaxe errada aqui. Creio que o problema é algo de incompatibildade do Browser. Enviei uma foto anexa

**Comment by Roger-Melo** [comment]
Olá @juniormelo45.

Pode ignorar a aba `Issues` do navegador. 

O que você precisa testar é se o valor no console.log que você escreveu está sendo exibindo na aba `Console` do navegador. 

Se não estiver, sobe o projeto com todos os arquivos no Google Drive e manda o link da pasta =)

@OnielStgo valeu pela contribuição =)
