### ISSUE TITLE
Dúvida no geral

### ISSUE THREAD

**Issue by Rodolfo-ss** [roger-melo-treinamentos/curso-de-js-roger-melo#6965]
### Etapa da aula

1

### Nome da aula

111

### Link da aula

11

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Professor tenho uma dúvida boba até, acerto alguns exercicios poucos na verdade, refaço uns, faço anotações e resumos. Minha dúvida é, posso tocar o curso em frente sem medo mesmo, ou é bom refazer as aulas e exercicios ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodolfo-ss. 

Segue o que foi falado n'A Aula Mais importante do CJRM (1ª aula na plataforma). 

Lá eu falo sobre a revisão raio-x e quando você deve fazê-la. 

É normal errar exercícios, vc vai errar mesmo. Se fosse fácil, todo mundo faria. 

Se chegar ao ponto de não conseguir prosseguir por falta de entendimento de conceitos anteriores, volte, refaça, e peça ajuda aqui ou (ainda melhor) no grupo dos alunos no Telegram. Estamos aqui para te ajudar =)
