### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters - Aula 01-04 da etapa 03

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#697]
# Argumentos, Parâmetros e Default Parameters

## Argumentos e Parâmetros

Abaixo será visto com se passa valores para uma função para que ela possa manipulá-los podendo também retornar algo.

```js
// Declaração da função sem parâmetros e chamada da função sem argumentos
const myFunc = function() {
  console.lo(`Oi, nome!`); // Oi, nome!
}
myFunc();

// Declaração da função com parâmetro name e chamada da função com argumento name
const myFunc = function(name) {
  console.lo(`Oi, ${name}!`); // Oi Roger!
}
myFunc('Roger');
```

O nome dentro dos parênteses na declaração da função é uma variável que é chamada de parâmetro e o nome dentro do parênteses na chamada da função é chamado de argumento, também é possível passar uma variável como argumento na chamada da função.

Uma função pode ter **vários parâmetros e argumentos**

```js
const myFunc = function(name, lastName) {
  console.lo(`Oi, ${name} ${lastName}!`); // Oi, Roger Melo!
}
myFunc('Roger', 'Melo');
```

A **ordem do argumento deve corresponder a ordem dos parâmetros**, mas dentro do bloco de código da função não precisa corresponder.

## Default Parameters

Se houver parâmetros mas não houver argumentos para eles os parâmetros serão definidos como undefined, pois não foi definido nenhum valor para eles, assim como acontece em uma declaração de variável.

Assim, é possível inicializar os parâmetros com algum valor inicial:

```js
const myFunc = function(name = 'Roger', lastName = 'Melo') {
  console.lo(`Oi, ${name} ${lastName}!`); // Oi Roger Melo!
}
myFunc();
```

Caso seja passado os argumentos na chamada da função, esses valores irão sobrepor os valores default inseridos no parâmetro.

```js
// Exemplo sobrepondo os dois valores
const myFunc = function(name = 'Roger', lastName = 'Melo') {
  console.lo(`Oi, ${name} ${lastName}!`); // Oi Guilherme Rodrigues!
}
myFunc('Guilherme', 'Rodrigues');

// Exemplo sobrepondo apenas o primeiro valor
const myFunc = function(name = 'Roger', lastName = 'Melo') {
  console.lo(`Oi, ${name} ${lastName}!`); // Oi Guilherme Melo!
}
myFunc('Guilherme');
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer! Rumo à fluência 👊🏻
