### ISSUE TITLE
Computed Property Names

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#6973]
### Etapa da aula

12

### Nome da aula

Correção dos exercícios da aula 01 da etapa 12 - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/curso-de-javascript-roger-melo-cjrm-jan2023/aula/6371048

Minuto: 07:01

Olá!

Podem me explicar como funciona o Computed Property Names ?

Eu não consegui compreender como ele funciona e muito menos como consigo aplica ló.

Já revi a correção algumas vezes e mesmo assim não consegui compreender a sua utilização

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dzpoke. 

Como foi mencionado na aula, vc irá usar computed property names quando não souber o nome exato de uma propriedade que irá criar, ou seja, quando a propriedade precisa ser criada dinamicamente. 

Você ainda irá ver outros casos dessa funcionalidade/técnica sendo aplicada no CJRM, então não precisa se preocupar se não entender muito bem neste momento =)

Acredito também que o material abaixo pode ajudar a ir clareando aos poucos esse conceito:

- [Objetos em JavaScript: ponto x colchetes. Qual usar?](https://youtu.be/y0OXya1C-po)

**Comment by dzpoke** [comment]
Entendi mestre

Obrigado pela ajuda!
