### ISSUE TITLE
Resumo da Aula Function declaration, function expression e hoisting - Aula 01-03 da etapa 03

### ISSUE THREAD

**Issue by fabiocosta123** [roger-melo-treinamentos/curso-de-js-roger-melo#6992]
function declaration - para criar uma função, usa a palavra reservada function seguido do nome da função, abre e fecha parentêses, e abre e fecha chaves. Dentro de chaves inserimos o código que queremos executar.
function sayHi () {
    console.log('oi')
}

a função acima irá mostrar no console a palavra 'oi'. Para invocar essa função bastar digitar o nome da função seguida de abrir e fechar parentêses.
sayHi ()

- function expression -- é a maneira de criar função atribuindo a uma variavel. Nesse caso a função não recebe nome, ela herdará o nome da variavel.

const showFood = function () {
    console.log('pizza')
}

Está função quando invocada irá mostrar no console a palavra ' pizza ', e para invocar uma function expression, escrevendo o nome da variavel a qual atribuida em seguida abrir e fechar parentêses.

showFood ()

Temos que levar em consideração que o javascript faz o hoisting para funções declarativas, ou seja, não importa onde sua função está sendo declarada no código, por debaixo dos panos o javascript vai pegar a função e levar pra cima na execução. No caso de uma function expression, isso já não ocorre.

**Comment by MivlaM** [comment]
Show @fabiocosta123. Vamo que vamo, rumo à fluência! 🙌
