### ISSUE TITLE
Quiz - Séries em português de Portugal

### ISSUE THREAD

**Issue by viniciuscosta89** [roger-melo-treinamentos/curso-de-js-roger-melo#7]
https://github.com/viniciuscosta89/quiz-interativo

- Talvez a maior dificuldade foi escolher as séries e as cores do Quiz. 
- Achei bem tranquilo de fazer, após acompanhar a aula e fazer o quiz dos filmes junto, o que acabou facilitando, sem a necessidade de rever a aula.

**Comment by Roger-Melo** [comment]
Boa @viniciuscosta89!

Parabéns pela proatividade em pesquisar o argumento do `scrollTo()` =)

No próximo exercício e revisão vamos aperfeiçoar ainda mais esse projeto com o que vimos até aqui.

Vou fechar a issue mas no que precisar, é só abrir uma nova =D
