### ISSUE TITLE
Etapa 07, Exercícios da aula 01

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#70]
https://github.com/lucasfads/cjrm-exercicio19
Maior dificuldade: usar o Boostrap pq eu tô mais acostumado a fazer meu CSS todo do zero
Menor dificuldade: bolar a lógica do JS

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

Parabéns pela aplicação! Deu pra perceber que mesmo com as dificuldades com o Bootstrap, você soube implementá-lo bem =D

Fico feliz que não houve dificuldades em implementar a lógica da aplicação. Apenas tome cuidado para não esquecer os `console.log()`. Sempre remova-os do código.

Mais uma vez, parabéns pelo esforço! No que precisar, conte comigo para te ajudar a chegar na fluência em JavaScript =)

@lucasfads

**Comment by lucasfads** [comment]
Obrigado!
