### ISSUE TITLE
Dúvidas sobre return

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#7004]
### Etapa da aula

6

### Nome da aula

Validação básica de formulários - Aula 02-02

### Link da aula

https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo-cjrm/aula/924880

Bom dia, @Roger-Melo/@MivlaM!

Gostaria de saber se há diferenças ainda que sutis entre os dois modos de retornar, por gentileza. 
Roger fez do primeiro exemplo(aula), já eu fiz da segunda forma.
No primeiro caso o `return` veio abaixo da linha de código, no segundo é escrito na mesma linha antes do código. 
Grato.
```js
//1º exemplo - aula
    if(isValidUsername){
        feedback.textContent = "Username válido!"
        return 
    }

//2º exemplo 
    if(isValidUsername){
        return feedback.textContent = "Username válido!"
    }
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Bruno-Luna

> ## Gostaria de saber se há diferenças ainda que sutis entre os dois modos de retornar

Recapitulando que o return é usado dentro de funções e sempre quando você precisa retornar um valor e parar a execução da função naquele ponto.

--> No 1º exemplo, undefined está sendo retornado, porque em JavaScript, toda função que não retorna valor explicitamente, retorna undefined.

--> No 2º exemplo, o return está retornando o retorno da atribuição, que é a própria string 'Username válido'.

Em conclusão, não tem problema optar pelo 2º ou 1º exemplo, desde que você esteja consciente de qual valor está sendo retornado em ambos os casos, ainda que o valor retornado não esteja sendo aproveitado. Independente do exemplo escolhido, para o código em questão, o funcionamento será igual.

Consegui responder a sua dúvida? Qualquer coisa, sinta-se livre para comentar aqui abaixo que vou te ajudar =)

**Comment by Bruno-Luna** [comment]
Certinho. Obrigado @MivlaM!

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
