### ISSUE TITLE
template strings

### ISSUE THREAD

**Issue by carmelo3039** [roger-melo-treinamentos/curso-de-js-roger-melo#7009]
### Etapa da aula

1

### Nome da aula

Template strings - Aula 02-06

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991179

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

 Minha duvida não entendi muito bem , quando deve usar ou não template strings?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @carmelo3039!

Sempre que você precisa interpolar uma variável em sua string, é uma boa ideia usar template strings. 

Interpolações podem ser feitas com strings tradicionais também, mas geralmente elas ficam menos legíveis. 

Olha só:

```js
const myName = 'Wagner'

const traditionalString = 'Meu nome é ' + myName
const templateString = `Meu nome é ${myName}`
```

Com string tradicional, é necessário deixar o espaço em branco no final da string e usar o operador `+` para fazer concatenações, e isso tende a deixar o código menos legível. 

Se mesmo após essa explicação não tiver ficado claro, fique tranquilo, você ainda verá muitos casos de uso de template strings conforme for avançando e aos poucos as coisas vão clareando mais, ok? =)

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova
