### ISSUE TITLE
Duvida sobre callbak

### ISSUE THREAD

**Issue by juniormelo45** [roger-melo-treinamentos/curso-de-js-roger-melo#7034]
### Etapa da aula

3

### Nome da aula

O método forEach e callbacks -aula02-04

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991210

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Professor,

Logo no início da aula, não seria correto invocar a função myFunc usando callback como parâmetro( ex : myFunc(callback)), ao invés de callback(value), como está descrito na aula? Como está descrito na aula, parece que invoca função usando o parâmetro callback e isso deu um bug no meu cérebro. rs

Agradeço a atenção

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @juniormelo45!

É isso mesmo, o parâmetro `callback` recebe a referência da função que foi inserida como argumento da invocação da função `myFunc`. 

Lembre-se que um parâmetro é uma variável. Então da mesma forma que uma variável armazena a referência de uma função, um parâmetro também pode armazenar:

```js
const myFunc = param => {
  console.log(param) // () => 'oi'
}

myFunc(() => 'oi')
```

```js
const abc = () => 'oi'

console.log(abc) // () => 'oi'
```

Execute ambos os códigos acima. Eles servem pra provar o ponto que mencionei: parâmetro/variável armazenam a referência da função. E se armazena a referência da função, vc pode invocar a função através do parâmetro/variável:

```js
const myFunc = param => {
  console.log(param()) // 'oi'
}

myFunc(() => 'oi')
```

```js
const abc = () => 'oi'

console.log(abc()) // 'oi'
```

Recomendo também que execute [este passo a passo](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/574) para ir clareando as ideias. 

Callback no começo dá um pouquinho de dor de cabeça para entender, isso é normal. Com a prática vc irá pegar o jeito =)

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova
