### ISSUE TITLE
Resumo da Aula O método reduce - Aula 01-04 da etapa 08

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#7037]
# O método reduce

Quando devemos usar o método **reduce**? Usamos o método reduce quando baseado no array original nós precisamos reduzir um array a algum outro tipo de dado, e esse outro tipo de dado pode ser um objeto literal, uma string, um número, ou até mesmo um novo array.

Ao contrario dos métodos map e filter, o método reduce pode devolver um elemento que não necessariamente tem que ser um array. 

De igual forma aos métodos map e filter, o método reduce também recebe uma função (callback) como argumento e executa essa função para cada item do array original, e essa função sempre tem que devolver um valor após cada execução, ou seja, essa funçaõ tem que ter um "return".

O método reduce recebe dois argumentos
- **callback** --> função que será executada para cada item do array original
- **accumulator** (este argumento é opcional) --> valor inicial do acumulador. Este elemento irá recebendo (acumulando) o valor devolvido depois de cada execução da função de callback, e no final é este o valor que será devolvido quando termine a execução do método reduce. É muito recomendável usar este argumento já que além de servir para inicializar o acumulador, visualmente nós indica o tipo do valor que vai devolver a execução do método reduce.

Ao igual que os métodos map e filter, a função de callback que executa o método reduce pode receber três parâmetros: 
- **valorAtual** --> elemento atual do array original que está sendo processado
- **index** (este parâmetro é opcional) O índice do elemento atual que está sendo processado
- **array** (este parâmetro é opcional) O Array original

Segue um exemplo de uso do método reduce. Neste exemplo temos um array de números e queremos obter a suma de todos esses números. Ou seja, em outras palavras, agente vai reduzir o array a um único valor, neste caso a um número.
```js
const numbers = [4, 8, 10];

const sumTotal = numbers.reduce((accumulator, number) => accumulator + number, 0)

console.log(sumTotal);

//Cómo foi executado ó código acima:
// Na primeira execução da função de callback, "accumulator" vale 0, "number" vale 4, e a função de callback retorna a soma de "accumulator" mais "number" (0 + 4), ou seja, 4 é devolvido e esse valor é armazenado (acumulado) no "accumulator".
// Na segunda execução da função de callback, "accumulator" vale 4, "number" vale 8, e a função de callback retorna a soma de "accumulator" mais "number" (4 + 8), ou seja, 12 é devolvido e esse valor é armazenado (acumulado) no "accumulator".
// Na terceira e última execução da função de callback (o array numbers só tem 3 elementos) , "accumulator" vale 12, "number" vale 10, e a função de callback retorna a soma de "accumulator" mais "number" (12 + 10), ou seja, 22 é devolvido e esse valor é armazenado (acumulado) no "accumulator".
//Então por último o método reduce devolve 22.

NOTA: Se ao executar o método reduce no programa anterior não tivéramos especificado o valor inicial do "accumulator", na primeira execução da função de callback o valor de "accumulator" tivera sido o valor do primeiro elemento do array "numbers" (ou seja, 4), e o valor de "number" tivera sido o valor do segundo elemento do array "numbers" (ou seja, 8).
```
### No exemplo que segue temos um array de objetos que representa a pontuação de alguns jogadores em uma competição. Mas acontece que alguns jogadores aparecem mais de uma vez no array. Então nós queremos saber a pontuação acumulada por um único jogador nessa competição, neste caso queremos saber a pontuação do jogador chamado "Roger Melo". Então para calcular a pontuação acumulada pelo jogador "Roger Melo" vamos usar o método reduce da seguinte forma:
```js
const phaseScores = [
  { name: 'Vinicius Costa', score: 337 },
  { name: 'Roger Melo', score: 43 },
  { name: 'Alfredo Braga', score: 234 },
  { name: 'Pedro H. Silva', score: 261 },
  { name: 'Ana Paula Rocha', score: 491 },
  { name: 'Vinicius Costa', score: 167 },
  { name: 'Roger Melo', score: 137 },
  { name: 'Alfredo Braga', score: 135 },
  { name: 'Ana Paula Rocha', score: 359 },
  { name: 'Pedro H. Silva', score: 133 }
]

const rogerMeloScore = phaseScores.reduce((accumulator, phaseScore) => {
  if (phaseScore.name === 'Roger Melo') {
    accumulator += phaseScore.score;
  }
  return accumulator;
}, 0)

console.log(rogerMeloScore);                    // 180

//Como podemos ver o jogador "Roger Melo" teve uma pontuação final é de 180 pontos, ou seja, na primeira participação ele obteve 43 pontos, e na segunda vez obteve 137 pontos, o que dá um total de 180.

//Dica: na declaração do método reduce acima, poderíamos ter usado a desestruturação de objetos da seguinte forma para obter o mesmo resultado:
const rogerMeloScore = phaseScores.reduce((accumulator, phaseScore) => {
  const { name, score } = phaseScore;
  if (name === 'Roger Melo') {
    accumulator += score;
  }
  return accumulator;
}, 0)
```

**Comment by MivlaM** [comment]
Boa @OnielStgo rumo à fluência! 🔥
