### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by fabiocosta123** [roger-melo-treinamentos/curso-de-js-roger-melo#7038]
Funções são blocos de códigos que podem ser invocadas em qualquer lugar do nosso código.
Métodos são funções, a diferença entre eles é de como invocamos um método e onde ele é declarado.
Os métodos são usado logo após um ponto. 'Ex:' 
para transformar um nome todo em maísuculo.
let name = ' fábio ';
name.toUpperCase();
o método 'toUpperCase()' é uma função, a diferença está em como invocamos, pois a usamos logo após a variavel 'name', depois de um ponto.

**Comment by MivlaM** [comment]
Boa @fabiocosta123 rumo à fluência! 🔥
