### ISSUE TITLE
Resumo da Aula 03 da etapa 02 Array

### ISSUE THREAD

**Issue by jonathasmatos** [roger-melo-treinamentos/curso-de-js-roger-melo#7041]
```js
let heros = ['Batman', 'Capiatão Americana', 'Homen Aranha']
```
//Criando uma Array

```js
const joinHeros = heros.join()
```
//O método join() junta todos os elementos de um array  em uma string e retorna esta string.

```js
const indexOf25 = ages.indexOf(25)
```
//O método indexOf() retorna o primeiro índice em que o elemento pode ser encontrado no array, retorna -1 caso o mesmo não esteja presente.

```js
const moreHeros = heros.concat(['Jhonatan', 'Leila'])
```
// O método concat() é utilizado para mesclar dois ou mais arrays. Esse método não altera os arrays existentes, mas, em vez disso, retorna um novo array.

```js
const pushToHeros = heros.push('Cyclops', 'Hulk')
```
//O método push() adiciona um ou mais elementos ao final de um array e retorna o novo comprimento desse array.

```js
const popHeros = heros.pop()
```
// ".pop" Remove o ultimo iten de uma array e retorna este iten. hulk virou um container é esta atribuido para "popHeros. e automaticamente modificando a array original"

**Comment by MivlaM** [comment]
Boa @jonathasmatos rumo à fluência! 🔥
