### ISSUE TITLE
Resumo da Aula Correção dos exercícios da aula 01 da etapa 08

### ISSUE THREAD

**Issue by widneyds** [roger-melo-treinamentos/curso-de-js-roger-melo#7049]
### Principais pontos desta aula:
  - A palavra-chave `debugger` serve pro interpretador do JavaScript pausar a execução e permitir inspecionar o estado do programa e analisar o fluxo de execução;
  - O ternário é uma forma mais concisa de criar uma condicional;
  ```js
  const crazyNumbers = [937, 5, 395, 402, 501, 333, 502, 781, 3, 691];
  
  const countNumbersLessThan501 = (accumulator, crazyNumber) => 
    crazyNumber < 501 ? ++accumulator : accumulator
  
  const numbersLessThan501 = crazyNumbers.reduce(countNumbersLessThan501, 0);
  
  console.log(numbersLessThan501); // Expected output: 5
  ```
  - Side effect (ou efeito colateral) é qualquer mudança de estado em uma aplicação que pode ser percebida do lado de fora da função e que não é um valor retornado pela função. Exemplos de efeito colateral:
       - Modificar alguma variável ou propriedade de objeto que tá do lado de fora da função;
       - Logar no console;
       - Manipular o DOM;
       - Desencadear qualquer processo do lado de fora da função;
       - Invocar outra função que produza efeito colateral.
  - Mudança de estado em uma aplicação é tudo que armazena um valor;
  - Os métodos map, filter e reduce não devem ser usados para gerar efeitos colaterais.

**Comment by MivlaM** [comment]
Boa @widneyds rumo à fluência! 🔥
