### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08  da etapa 05

### ISSUE THREAD

**Issue by LDrigues** [roger-melo-treinamentos/curso-de-js-roger-melo#7053]
### Getting Element 

Podemos acessar elemento ou elementos já criados usando JavaScript. Para acessar ou obter 
elementos, usamos diferentes métodos. 

- getElementsByTagName()
- getElementsByClassName()
- getElementsById()

### Getting elements by using querySelector methods

- document.querySelector()
- document.querySelectorAll()

**Comment by MivlaM** [comment]
Boa @LDrigues rumo à fluência! 🔥
