### ISSUE TITLE
Etapa 4, Correção dos Exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#706]
Roger na resolução do exercício nº 2, defini o método asim:
````js
    sound: function () {
    return console.log('MEAO...')} //Linha 19;
````
    E o resultado foi:
![image](https://user-images.githubusercontent.com/44072541/118901381-80a32b80-b8e9-11eb-9dc9-6b39b25e4530.png)

    No local do 'X' retornou 'undefined' e, atentando para a linha 19, onde estava a instrução do método, apareceu o retorno do método; Então para acertar a questão:
````js
    sound: function () {
    let catSound =  'MEAO.....'
    return catSound  }
  
````
    A dúvida seria...como eu poderia analisar o que aconteceu, tem haver com o escopo da função? Por que a invocação está num local e o retorno está em outro( no local de origem da instrução)?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcos. 

Se você executar `console.log('oi')` no console do browser, por exemplo, verá que na linha abaixo do `'oi'`, `undefined` é exibido. 

Isso acontece por que a invocação do `console.log()` não retorna um valor (apenas exibe o valor no console). E em JavaScript, toda função ou método que não retorna um valor, retorna `undefined` por baixo dos panos. 

No código abaixo, a invocação de `obj.method()` retorna o valor que a invocação `console.log('abc')` retorna. 

```javascript
const obj = {
  method: function () {
    return console.log('abc')
  }
}

console.log(obj.method())
// 'abc'
// undefined
```

Como a invocação do `console.log` retorna `undefined`, `obj.method()` resultou em `undefined` e como esse `undefined` está dentro de um `console.log()`, `undefined`le foi exibido no console.

Porém, observe que `'abc'` foi exibida no console. Isso acontece por que as execuções da linha `return console.log('abc')` acontecem da direita para a esquerda. Ou seja, a invocação `console.log('abc')` exibiu `'abc'` no console, retornou `undefined` e só então o `return` retornou `undefined`.

Para comprovar que a invocação de um `console.log()` retorna `undefined`, você pode aninhar as invocações:

```javascript
console.log(console.log()) // undefined
```

Se um argumento for inserido na invocação do console.log aninhado, o valor é exibido no console normalmente, por que a invocação aninhada exibe o valor no console e retorna `undefined`:

```javascript
console.log(console.log('olá'))
// 'olá'
// undefined
```

Ps: se quiser postar todo o código nas issues, pode postar. Fica até mais legível e melhor para eu reproduzir em minha máquina, se necessário =)

Ficou mais claro?

**Comment by Roger-Melo** [comment]
@marcosyoggy vou fechar a issue mas no que precisar, é só dar o toque =)
