### ISSUE TITLE
exercício 3 

### ISSUE THREAD

**Issue by Karpegianny** [roger-melo-treinamentos/curso-de-js-roger-melo#7060]
### Etapa da aula

1

### Nome da aula

Exercícios Aula 03

### Link da aula

https://app.nutror.com/v3/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/curso-de-javascript-roger-melo-cjrm-mai2023/aula/6991185

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá Professor! Fiz o Exercicio 3  e na questão 05 fiz exatamente como vc fez só que simplesmente meu codigo não aparece no console.

const foodsInfo = 'Até aqui, o array "brazilianFoods" possui ${brazilianFoods.length} itens: ${brazilianFoods[0]}, ${brazilianFoods[1]} e ${brazilian.Foods[2]}'

console.log(foodsInfo)

pode ajudar a entender porq não foi relacionado nem no metodo length nem nas interpolações.

Abs

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Karpegianny

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Fiz o Exercicio 3 e na questão 05 fiz exatamente como vc fez só que simplesmente meu codigo não aparece no console.

Acredito que o motivo de não aparecer o resultado esperado é porque no seu código, você utilizou aspas simples ao invés de template strings.

Sempre que você precisa interpolar uma variável em sua string, é uma boa ideia usar template strings. 

Interpolações podem ser feitas com strings tradicionais também, mas geralmente elas ficam menos legíveis. 

Olha só:

```js
const myName = 'Wagner'

const traditionalString = 'Meu nome é ' + myName
const templateString = `Meu nome é ${myName}`
```

Com string tradicional, é necessário deixar o espaço em branco no final da string e usar o operador `+` para fazer concatenações, e isso tende a deixar o código menos legível. 

Usando template strings no código que você mostrou de exemplo, ele ficaria assim:

```js
// antes
const foodsInfo = 'Até aqui, o array "brazilianFoods" possui ${brazilianFoods.length} itens: ${brazilianFoods[0]}, ${brazilianFoods[1]} e ${brazilian.Foods[2]}'

console.log(foodsInfo)
```

```js
// depois
const foodsInfo = `Até aqui, o array "brazilianFoods" possui ${brazilianFoods.length} itens: ${brazilianFoods[0]}, ${brazilianFoods[1]} e ${brazilian.Foods[2]}`

console.log(foodsInfo)
```

Se mesmo após essa explicação não tiver ficado claro, fique tranquilo, você ainda verá muitos casos de uso de template strings conforme for avançando e aos poucos as coisas vão clareando mais, ok? =)

Se ainda tiver restado qualquer dúvida, sinta-se livre para comentar aqui abaixo que eu te ajudo =)

**Comment by MivlaM** [comment]
Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
