### ISSUE TITLE
Aplicação: [To-Do_List]

### ISSUE THREAD

**Issue by DiegoFrancoGiusti** [roger-melo-treinamentos/curso-de-js-roger-melo#7061]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/DiegoFrancoGiusti/TodoList

### Maiores dificuldades durante a implementação

- Criar a lógica para deletar os to-dos sem usar a propriedade parentElement.
- Entender a função de um atributo data.
- nomear funções e variáveis.

### Menores dificuldades durante a implementação

- Refatorar o código.
- A lógica do código.

**Comment by DiegoFrancoGiusti** [comment]
Cores alteradas

**Comment by MivlaM** [comment]
Olá @DiegoFrancoGiusti

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @DiegoFrancoGiusti.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Criar a lógica para deletar os to-dos sem usar a propriedade parentElement.

A lógica que você fez ficou muito interessante, parabéns! Não é bom usar parentElement, pois é um design de código que tende a ser frágil. Se futuramente a marcação html dessa aplicação mudar e o parentElement não for mais o elemento que você tinha em mente quando escreveu o código, o código pode quebrar. De qualquer forma, vou abordar esse ponto na análise.

> ## Entender a função de um atributo data.

Sem problemas! Para os dois pontos que você escreveu que teve dificuldade acima, parte do desafio era fazer você exercitar e pesquisar o assunto =)

Vou abordar parte do assunto aqui na análise, mas você ainda vai aprender mais sobre os atributos data nas próximas aulas.

> ## nomear funções e variáveis.

Em relação a nomenclatura, ela será abordada no decorrer da análise. O que é importante é que mesmo com as dificuldades relatadas, você conseguiu fazer funcionar =)

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Linhas em branco

Princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, a sugestão aqui é que você mantenha uma linha em branco para separar as lets da consts do topo do código, pois estas desempenharão um papel diferente do atribuído às consts. Sabendo disso, pode ter uma linha em branco acima da declaração de `liGroupItem`.

```js
// antes
const formAddTodo = document.querySelector('.form-add-todo')
const todosContainer = document.querySelector('.todos-container')
const formSearch = document.querySelector('.form-search')
let liGroupItem = document.querySelectorAll('li.list-group-item')
let deleteIcons = document.querySelectorAll('.delete')
```

```js
// depois
const formAddTodo = document.querySelector('.form-add-todo')
const todosContainer = document.querySelector('.todos-container')
const formSearch = document.querySelector('.form-search')

let liGroupItem = document.querySelectorAll('li.list-group-item')
let deleteIcons = document.querySelectorAll('.delete')
```

---

## Função addTodo

Nessa função, há algumas modificações que podemos fazer. Primeiramente, se fizer sentido para você, você pode renomear a const de `isDifferentFromZero` para algo como `isNotZero`. A vantagem aqui é deixarmos o nome mais curto e de forma que mantenha seu sentido.

```js
// antes
const addTodo = inputValue => {
  const isDifferentFromZero = inputValue.length

  // ...
}
```

```js
// depois
const addTodo = inputValue => {
  const isNotZero = inputValue.length

  // ...
}
```

Você também pode, se achar que faz sentido, remover por completo a const `isNotZero` do código, pois a lógica que ela armazena não é de entendimento tão complexo e como ela só é usada uma única vez, pode ser vantajoso inseri-la diretamente no bloco do if. Algo similar acontece com o `todoIndex`, cuja lógica também é simples e também pode ser colocado diretamente dentro da interpolação. Ficaria assim:

```js
// antes
const addTodo = inputValue => {
  const isNotZero = inputValue.length

  if(isNotZero){
    todoIndex = liGroupItem.length

    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete" data-todo-index="${todoIndex}"></i>
      </li>
    `
    updateNodeLists()
    formAddTodo.reset()
  }
}
```

```js
// depois
const addTodo = inputValue => {

  if(inputValue.length){

    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete" data-todo-index="${liGroupItem.length}"></i>
      </li>
    `
    updateNodeLists()
    formAddTodo.reset()
  }
}
```

Feito isso, agora, podemos usar parte do código que você colocou no listener de evento diretamente nessa função, a ideia é deixarmos o listener para executar apenas o envio do código. Um detalhe aqui, é que ao invés de usar `formAddTodo.reset()`, você pode usar o `event` para resetar, como `event.target.reset()`, por exemplo. Após isso, há a possibilidade de criarmos uma validação, é mais ou menos isso que a `inputValue.length` faz, porém, podemos deixá-la mais completa e abrangente ao criarmos uma verificação para o `inputValue`. Esse `inputValue` pode ter uma verificação para caso uma string vazia ou string com menos de três caracteres for enviada como input. Numa situação assim, você pode, se achar que faz sentido, exibir uma mensagem na tela por meio do `alert` comunicando que é necessário inserir um texto válido. As refatorações completas nessa função ficariam assim:

```js
// antes
const addTodo = inputValue => {

  if(inputValue.length){

    todosContainer.innerHTML += `
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete" data-todo-index="${liGroupItem.length}"></i>
      </li>
    `
    updateNodeLists()
    formAddTodo.reset()
  }
}

formAddTodo.addEventListener('submit', event => {
  event.preventDefault()

  const inputValue = event.target.add.value.trim()
  addTodo(inputValue)
})
```

```js
// depois
const addTodo = event => {
  event.preventDefault()

  const inputValue = event.target.add.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert("Por favor, insira um texto valido")  
    return
  }
 
  todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>${inputValue}</span>
        <i class="far fa-trash-alt delete" data-todo-index="${liGroupItem.length}"></i>
      </li>
    `

  updateNodeLists()
  event.target.reset()
}

formAddTodo.addEventListener('submit', addTodo)
```

---

## Refatoração da função deleteTodo

Antes de começar a refatoração de fato nessa função, acredito que, nesse momento, vale a pena abordar o uso dos atributos data. Como mencionei no início da análise, em breve você chegará nas aulas sobre esses atributos. Mas para você ter uma ideia, você pode inserir o atributo data-todo na li do todo e colocar seu valor como o mesmo conteúdo da tag de `span`, depois adicionar um outro atributo data-trash no elemento html `i` da lixeira com novamente o mesmo conteúdo de `span`. Por exemplo, no código html, dentro da ul, vou criar um todo chamado "Estudar Javascript". Ficaria assim:

```html
<ul class="todos-container list-group mx-auto text-light scrolling">
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="Estudar Javascript">
    <span>Estudar Javascript</span>
    <i class="far fa-trash-alt delete" data-trash="Estudar Javascript"></i>
  </li>
</ul>
```

Depois, na função `addToDo`, você pode adicionar, dentro da template string, a nova marcação html atualizada com os atributos data. data-trash vai receber o conteúdo textual do todo, que no caso é o `inputValue`. `liGroupItem.length` não vai ser mais necessário, na li, o data-todo vai receber uma interpolação com o texto do todo do `inputValue`:

```js
todosContainer.innerHTML += `
  <li class="list-group-item d-flex justify-content-between align-items-center" data-todo="${inputValue}">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
  </li>`
``` 

Após inserir os atributos data acima na marcação html. Agora, na função `deleteTodo`, vamos usá-los também para fazer uma nova refatoração. Para isso, você pode fazer o seguinte:

Vamos remover todo o código e fazer com que `deleteTodo` receba um elemento `event`, dentro dessa função, você pode criar uma const `trashWasClicked` que vai receber o valor retornado pelo dataset que contém uma propriedade trash. Ou seja, quando a lixeira for clicada, o valor do atributo data-trash vai ser atribuida para a const `trashWasClicked`. Ficaria assim:

```js
const deleteTodo = event => {
  const trashWasClicked = event.target.dataset.trash

  if (!trashWasClicked) {
    return
  }

  const todo = document.querySelector(`[data-todo="${trashWasClicked}"]`)
  todo.remove()
}
```

Ao clicar fora da lixeira, essa const vai armazenar `undefined`, que por ser um valor `falsy`, o if do early return vai ser executado. A vantagem do early return é parar a execução da função naquele ponto caso a condição seja falsa, assim não se torna necessário ler a parte do código que vem em seguida. Além disso, usando um early return, você não precisa inserir código dentro do bloco do if, reduzindo então o número de indentações para essa marcação e tornando o código mais legível. Quando a lixeira for clicada, `trashWasClicked` vai estar armazenando uma string preenchida, e uma string preenchida é um valor `truthy`, o if não será executado.

Você pode criar uma const `todo` que vai conter o todo, ou seja, a li que deve ser removida. Para selecionar essa li, você pode usar os atributos data. O data-todo tem o mesmo valor que data-trash, assim, você vai selecionar a li que contém o texto que `trashWasClicked` está armazenando, pois tanto data-todo quanto data-trash contém essa string que `trashWasClicked` está armazenando. Após a const `todo` receber a li que deve ser removida, você pode invocar o método `todo.remove()` para excluir a li escolhida do DOM.

Sendo assim, você só precisará do listener de eventos para executar essa função e da nova função `deleteTodo` atualizada para fazer o papel de deletar os todos. Ficaria assim:

```js
// antes
const deleteTodo = (getDeleteIcon,clickedElement) => {
  if(getDeleteIcon){
    const indexTodo = clickedElement.dataset.todoIndex

    liGroupItem[indexTodo].remove()

    updateNodeLists()
    setElementsAttribute(liGroupItem,'data-todo-index')
  }
}

const setClassList = (element,removeClass,addClass) => {
  element.classList.remove(removeClass)
  element.classList.add(addClass)
}

todosContainer.addEventListener('click',event => {
  const clickedElement = event.target
  const getDeleteIcon = Array.from(clickedElement.classList).includes('delete')

  deleteTodo(getDeleteIcon,clickedElement)
})
```

```js
// depois
const deleteTodo = event => {
  const trashWasClicked = event.target.dataset.trash

  if (!trashWasClicked) {
    return
  }

  const todo = document.querySelector(`[data-todo="${trashWasClicked}"]`)
  todo.remove()
}

todosContainer.addEventListener('click', deleteTodo)
``` 

Você irá aprender mais sobre os atributos data e suas particularidades nas próximas aulas do treinamento =)

---

## searchTodo

Para a função `searchTodo`, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

Vamos aproveitar parte do código que você escreveu e vamos inserir essa parte na função `searchTodo`. Até o momento, temos uma const `todos` que contem as lis que representam os todos e uma const `inputValue`:

```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
}
```

Feito isso, podemos percorrer cada um dos todos por meio do forEach, e após isso, podemos criar uma const `shouldBeVisible` que irá armazenar um boolean indicando se a li do todo deve ficar vísivel ou não dependendo do que o usuário escrever, depois disso, podemos manipular as classes dos to-dos considerando `shouldBeVisible`. Ficaria assim:

```js
// antes
const setClassList = (element,removeClass,addClass) => {
  element.classList.remove(removeClass)
  element.classList.add(addClass)
}

const searchTodo = (todos,inputValue) => {
  todos.forEach(todo => {
    let valueIncludedInList = todo.textContent.toLowerCase().includes(inputValue)

    !valueIncludedInList ? setClassList(todo,'d-flex','hidden') : setClassList(todo,'hidden','d-flex')
  })
}

formSearch.addEventListener('input',event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
   
  searchTodo(todos,inputValue)
})
```

```js
// depois
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  todos.forEach(todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  })
}

formSearch.addEventListener('input', searchTodo)
```

Após todas essas refatorações, o código reduziu de 78 linhas para 48, uma redução de 30 linhas! =)

---

Mas, tenha em mente que o mais importante num primeiro momento vc já havia feito, que é fazer funcionar com uma lógica que também é muito efetiva e interessante. O que sugeri é apenas uma lapidação envolvendo uma abordagem diferente de um código que já funciona =)


Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by DiegoFrancoGiusti** [comment]
Boa tarde, muito obrigado pela análise da aplicação. Aplicarei as observações feitas no meu projeto.

Desculpa pela demorar em responder a issue.

**Comment by MivlaM** [comment]
Ok! Eu vou fechar essa issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
