### ISSUE TITLE
Erro: TypeError: (intermediate value)

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#7062]
### Etapa da aula

12

### Nome da aula

Obtendo as informações que serão exibidas na interface - Aula 02-04

### Link da aula

https://app.nutror.com/v3/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6371050

> Minuto:  04:20

> Repositorio: https://github.com/dzpoke/weather

Estou tentando refazer o exercício sozinho sem refatorar porem estou tentando alguns problemas, na verdade esse módulo para mim esta sendo o mais difícil, não estou conseguindo encaixar as coisas sem olhar a resolução sempre esqueço, **pode me dar uma dica quanto a isso ?** estou me sentindo bem preso nesse modulo...

Por isso estou tentando fazer sem refatorar.

No arquivo APP não consigo fazer a desestruturação, sempre que tento retorna esse erro

> **Erro: TypeError: (intermediate value) is not iterable at HTMLFormElement.<anonymous>**

Dessa maneira consigo visualizar o retorno do objeto armazenado na const **teste**

```js
cityForm.addEventListener('submit', async event => {
    event.preventDefault()

    const inputCity = event.target.city.value
    const teste = await getCityData(inputCity)
    console.log(teste )

    cityForm.reset()
})
```

Agora se eu aplicar a desestruturação para  desempacotar comente a Key, recebo o erro mencionado 

```js
cityForm.addEventListener('submit', async event => {
    event.preventDefault()

    const inputCity = event.target.city.value
    const [{ Key }] = await getCityData(inputCity)

    console.log(Key)

    cityForm.reset()
})
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @dzpoke

> ## esse módulo para mim esta sendo o mais difícil, não estou conseguindo encaixar as coisas sem olhar a resolução sempre esqueço, pode me dar uma dica quanto a isso ? estou me sentindo bem preso nesse modulo...

Essa etapa realmente leva um tempo maior para entender do que as demais, eu também passei por algo semelhante e te digo por experiência própria. Mas, se esse módulo te causou essas dúvidas, eu recomendo que revise toda a etapa 11 desde o início buscando preencher esses gaps. Ela é muito importante para que você entenda os conceitos de assincronismo que você levará pelo restante de sua carreira de desenvolvedor.

Além disso, recomendo que leia a documentação de introdução à JavaScript assíncrono no MDN:

[Asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous)

Não vai ser rápido, mas entender assincronismo é crucial para um Desenvolvedor JS, caso contrário certamente a carreira será prejudicada. E eu não quero isso para você.

Quanto a dúvida referente ao código que você postou:

Se você executar o primeiro código que você postou, você verá que o objeto e suas propriedades aparecerão no console.log, entretanto, na hora de fazer o destructuring, você está colocando colchetes, esses colchetes não são necessários lá, porque o objeto que aparece no console não está dentro de um array. Para resolver esse problema, você pode apenas remover os colchetes que o código funcionará corretamente. Ficaria assim:

```js
cityForm.addEventListener('submit', async event => {
    event.preventDefault()

    const inputCity = event.target.city.value
    const { Key, LocalizedName } = await getCityData(inputCity)
    // const teste2  = await getCityTemperature(Key)

    console.log(Key, LocalizedName)

    cityForm.reset()
})
```

Entretanto, se eu não me engano, a ideia de remover esses colchetes é abordada de forma bem mais completa mais para o fim do módulo, portanto, se você fizer essa alteração agora, pode ser que alguns conceitos que serão mostrados nas aulas antes dessa de remover o colchetes não funcionem como exibido em vídeo. Novamente, se você ainda está aprendendo os conceitos dessa etapa, eu recomendo que você acompanhe o código mostrado nas aulas à risca, digitando e codando em sua máquina, acredito ser a maneira mais apropriada para você nesse momento, essas outras alterações vão sendo apresentadas em sequência no momento que elas forem fazer mais sentido para a aplicação. Ok?

Consegui resolver a sua dúvida? Se ainda restou alguma, pode comentar aqui em baixo.

Se tiver alguma outra dúvida, referente a algum conteúdo abordado na etapa, pode abrir outras issues que te ajudo =)

**Comment by dzpoke** [comment]
Consegui compreender as orientações, obriga\do pela ajuda @MivlaM
