### ISSUE TITLE
Aplicação: Todo-List

### ISSUE THREAD

**Issue by DevNeves** [roger-melo-treinamentos/curso-de-js-roger-melo#7069]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/DevNeves/Todo-List

### Maiores dificuldades durante a implementação

+ Primeiro de tudo, não consegui fazer sozinho a parte de remover e filtrar isso me deixou um pouco frustrado....  então assisti a aula uma vez e tentei fazer sozinho e consegui.

+ Pensar em um nome bom para as consts/funcs

+ Tive dificuldade para usar os valores data

+ Refatorar o código (não vi como o roger refatorou essa aplicação)

### Menores dificuldades durante a implementação

+ Adicionar novos Todos

+ Utilizar os listeners

+ Utilizar o event

**Comment by MivlaM** [comment]
Olá @DevNeves

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @DevNeves.

Parabéns pelo esforço em construir a segunda aplicação do treinamento =)

> ## Primeiro de tudo, não consegui fazer sozinho a parte de remover e filtrar isso me deixou um pouco frustrado.... então assisti a aula uma vez e tentei fazer sozinho e consegui.

Ok, o que é importante é que depois de você ter assistido a aula, você conseguiu fazer funcionar =)

> ## Pensar em um nome bom para as consts/funcs

Pelo que vi aqui, os nomes que você escolheu não foram ruins. De qualquer forma, também mencionarei sobre isso na análise.

> ## Tive dificuldade para usar os valores data

Pelo que eu vi aqui no código, você conseguiu aplicá-las corretamente! Parabéns! Parte do desafio era fazer você exercitar e pesquisar o assunto =)

Você ainda vai aprender mais sobre os atributos data nas próximas aulas, mas em resumo, não é bom usar `parentElement`, pois é um design de código que tende a ser frágil. Se futuramente a marcação html dessa aplicação mudar e o `parentElement` não for mais o elemento que você tinha em mente quando escreveu o código, o seu código pode quebrar. O que não acontece quando você usa os atributos data. Mas de certa forma, não há problema em usá-lo nesse momento do treinamento, mas nas próximas aulas você também vai poder aprender mais sobre o porquê e como usar atributos data-* em suas aplicações =)

> ## Refatorar o código (não vi como o roger refatorou essa aplicação)

Tenha consciência que refatoração é uma habilidade que vai sendo elevada conforme vc pratica. Vou te mostrar algumas possibilidades de refatoração na análise.

---

Vou deixar abaixo algumas observações sobre sua aplicação.

---

## Comentários no código

Há uma linha de código comentado na função `addNewTodo`, não é uma regra, mas evite comentários.

Comentários podem mentir se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

Entretanto, acho que é uma boa ideia manter esse trecho de código sem ser num comentário, ele pode complementar essa função.

```js
// antes
const addNewTodo = inputValue => {
  if (!inputValue) {
    // alert ('Por favor insira um TODO antes de adicionar')  
    return
  }
    
  // ...  
}
```

```js
// depois
const addNewTodo = inputValue => {
  if (!inputValue) {
    alert ('Por favor insira um TODO antes de adicionar')  
    return
  }
    
  // ...  
}
```

---

## Funções addTodo e addNewTodo

Nessas funções, podemos fazer algumas modificações. Primeiramente, uma sugestão seria, se você achar que faz sentido, ter apenas uma única função para lidar com a funcionalidade de adicionar to-dos. Para isso, você pode colocar todo o código da função `addNewTodo` dentro da função `addTodo`. A vantagem aqui, além de reduzir as linhas de código, é deixarmos mais simples a visualização e leitura ao termos apenas uma única função lidando com essa funcionalidade. Dentro desse novo código, `inputValueToNewTODO` é um nome muito longo e pode ser substituído por `inputValue`, que tem um nome similar e já satisfaz no sentido de exibir o que está armazenando. Essas refatorações ficariam assim:

```js
// antes
const addNewTodo = inputValue => {

  if (!inputValue) {
    alert ('Por favor insira um TODO antes de adicionar')  
    return
  }
    
  todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center bg-dark" data-selected-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
    </li>`    
}

const addTodo = event => {
  event.preventDefault()
    
  const inputValueToNewTODO = event.target.add.value.trim()
  addNewTodo(inputValueToNewTODO)
  cleanInput(event.target)
}
```

```js
// depois
const addTodo = event => {
  event.preventDefault()

  const inputValue = event.target.add.value.trim()

  if (!inputValue) {
    alert ('Por favor insira um TODO antes de adicionar')  
    return
  }
    
  todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center bg-dark" data-selected-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
    </li>
   `

  cleanInput(event.target)
}
```

Após isso, há a possibilidade de criarmos uma validação, é mais ou menos isso que o early return e o `!inputValue` faz, porém, podemos deixá-la mais completa e abrangente. Esse `inputValue` pode ter uma verificação para caso uma string vazia ou string com menos de três caracteres for enviada como input. Numa situação assim, você pode, se achar que faz sentido, manter a mensagem na tela por meio do `alert` comunicando que é necessário inserir um texto válido. As refatorações completas nessa função ficariam assim:

```js
// antes
if (!inputValue) {
  alert ('Por favor insira um TODO antes de adicionar')  
  return
}
```

```js
// depois
if (inputValue.length < 3 || inputValue === ''){
  alert ('Por favor insira um TODO antes de adicionar')  
  return
}
```

---

## Função cleanInput

Um detalhe aqui, essa função é usada apenas uma vez, portanto, se você achar interessante, você pode manter o código dela dentro da função `AddTodo`. A vantagem aqui é economizarmos algumas linhas de código e deixar o código mais compacto e simples de entender, sem necessitar ficar olhando o que uma função diferente faz no código. é que ao invés de usar `inputValue.reset()`, você pode usar o `event` para resetar, por meio do `event.target.reset()`, por exemplo

```js
// antes
const cleanInput = inputValue => {
  inputValue.reset()
}
```

```js
// depois
const addTodo = event => {
  event.preventDefault()

  const inputValue = event.target.add.value.trim()

  if (inputValue.length < 3 || inputValue === ''){
    alert('Por favor insira um TODO antes de adicionar')  
    return
  }
    
  todosContainer.innerHTML += `
    <li class="list-group-item d-flex justify-content-between align-items-center bg-dark" data-selected-todo="${inputValue}">
      <span>${inputValue}</span>
      <i class="far fa-trash-alt delete" data-trash="${inputValue}"></i>
    </li>
    `

  event.target.reset()
}
```

---

## Função deletedTodo

Nessa função, acredito que possa ser vantajoso renomeá-la para algo como `deleteTodo`, o motivo disso é que `deletedTodo` está no tempo verbal passado, e apenas lendo o nome, dá a entender que essa função vai trabalhar com os todos que já foram deletados, o que não é o caso. Ficaria assim:

```js
// antes
const deletedTodo = event => {
  // ...
}
```

```js
// depois
const deleteTodo = event => {
  // ...
}
```

Também pode ser interessante usarmos um early return nessa função. Vai funcionar da seguinte forma, ao clicar fora da lixeira, essa const vai armazenar undefined, que por ser um valor falsy, o if do early return vai ser executado. Para complementar, podemos juntar o código de `clickedElement` e de `dataTrash` em uma só variável que será responsável por armazenar o código para quando a lixeira for clicada, podemos renomear essa nova const para algo como `trashWasClicked` vai estar armazenando uma string preenchida, e uma string preenchida é um valor truthy, o if não será executado. Ficaria assim:

```js
// antes
const deleteTodo = event => {
  const clickedElement = event.target
  const dataTrash = clickedElement.dataset.trash
  const selectedTodo = document.querySelector(`[data-selected-todo='${dataTrash}']`)
    
  if (dataTrash) {
    selectedTodo.remove()      
  }
}
```

```js
// depois
const deleteTodo = event => {
  const trashWasClicked = event.target.dataset.trash

  if (!trashWasClicked) {
    return
  }

  const selectedTodo = document.querySelector(`[data-selected-todo='${trashWasClicked}']`)
  selectedTodo.remove() 
}
```

## Função searchTodo

Para a função `searchTodo`, vou deixar uma possível abordagem de refatoração do código que busca os to-dos. Acredito que isso pode te dar uma luz =)

O fato é que vc pode modificar um pouco da lógica para deixar esse código menos propenso a ter repetições.

Para entender de fato essa forma de refatorar a filtragem de to-dos que vou mostrar, você precisa escrever e executar cada código do passo a passo abaixo junto comigo, ok?

Olha só...

Uma forma de abstrair as repetições desse código é usar a transformação de dados ao seu favor.

Como assim?

Vamos aproveitar parte do código que você escreveu e vamos inserir essa parte na função `searchTodo`. Até o momento, temos uma const `todos` que contem as lis que representam os todos e uma const `inputValue`:

```js
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)
}
```

Feito isso, podemos percorrer cada um dos todos por meio do forEach, e após isso, podemos criar uma const `shouldBeVisible` que irá armazenar um boolean indicando se a li do todo deve ficar vísivel ou não dependendo do que o usuário escrever, depois disso, podemos manipular as classes dos to-dos considerando `shouldBeVisible`. Ficaria assim:

```js
// depois
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  const todos = Array.from(todosContainer.children)

  todos.forEach(todo => {
    const shouldBeVisible = todo.textContent.toLowerCase().trim().includes(inputValue)
    todo.classList.add(shouldBeVisible ? 'd-flex' : 'd-none')
    todo.classList.remove(shouldBeVisible ? 'd-none' : 'd-flex')
  })
}
```

Após todas essas refatorações, o código reduziu de 68 linhas para 48, uma redução de 20 linhas! =)

Mas, tenha em mente que o mais importante num primeiro momento vc já havia feito, que é fazer funcionar. O que sugeri é apenas uma lapidação envolvendo uma abordagem diferente de um código que já funciona =)

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by DevNeves** [comment]
Obrigado pela avaliação, me ajudou bastante

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
