### ISSUE TITLE
Resumo da Aula 02-03 Encadeando métodos da etapa 08

### ISSUE THREAD

**Issue by holivei531** [roger-melo-treinamentos/curso-de-js-roger-melo#708]
# Encadeando métodos

###  → Criando dois novos arrays com base no array de objetos books

- Array que mostra apenas os livros que tenham o valor maior que 20.
- Array que mostra quais livros estão em promoção.

const books = [
    { name: 'Código Limpo', price: 30 },
    { name: 'O milagre da manhã', price: 5 },
    { name: 'Alice no País das Maravilhas', price: 10 },
    { name: 'Quem Pensa Enriquece', price: 50 },
    { name: 'O livro da ciência', price: 40 }
  ];

const filteredBooks = books.filter(book => book.price > 20);

const booksOnSale = filteredBooks.map(book => `O preço do livro "${book.name}" caiu para ${book.price} reais`);

---

### → Encadeando os arrays gerados no exemplo acima:

- Podemos usar uma convenção para formatar esse encadeamento: cada método fica em uma linha.
-  Também podemos utilizar o destructuring assignment, que possibilita extrair dados de arrays ou objetos em variáveis distintas.

const booksOnSale = books
    .filter(({ price }) => price > 20)
    .map(({ name, price}) =>
        `O preço do livro "${name}" caiu para ${price} reais`);

---

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @holivei531! 🔥
