### ISSUE TITLE
Etapa 7, Aplicação Quiz Interativo- Exercício - 19

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#71]
Boa noite Roger! Eu estudo JS a fundo vai fazer 1 mês e foi com o seu curso que a mina evolução disparou absurdamente e estou muito feliz com os resultados! 

Sobre a aplicação eu refiz por parte conforma as aulas foi avançando, eu assistia a aula e depois montava e depois assistia novamente e corrigia mais por trás entendendo a lógica e acho que assim eu fixei mais, foi sensacional o entendimento, show mesmo!

**Maiores Duvidas:** Em montar a logica ainda continua sendo meio dificil.

**Menores dificuldades:** HTML e CSS pois eu solidifiquei esses conhecimento antes de estudar **JS**

**Link do repositório do Quiz:** https://github.com/GoharaJunior/developer-quiz-interativo

**OBS:** Muito feliz com os resultados dos meus estudos em cima do curso, agora sim sinto digno de continuar da **Etapa 07** pra frente, pois desde de que comprei o curso eu prometi que não iria deixar nada passar sem entendimento, nem se fosse o raso. 🚀

****

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gohara!

Fico muito feliz que esteja percebendo progresso e evoluindo. A evolução vicia, não há como "desver" o progresso =)

> **Maiores Duvidas:** Em montar a logica ainda continua sendo meio dificil.

Quando estamos aprendendo algo novo, precisamos passar por essa fase. Muitas vezes é difícil pensar de forma lógica, quando não estamos ainda acostumados com a linguagem. Mas não se preocupe: isso vem com o tempo e a execução do método.

Apenas siga em frente, consulte a solução sempre que não conseguir resolver sozinho, e não deixe de tirar dúvidas.

Não tem problema não saber algo. O problema é desistir! Quem caiu muito e desistiu, não aprendeu a andar de bicicleta. Quem parou de ir às aulas de natação, não aprendeu a nadar.

Só não chega lá quem desiste.

Siga em frente, continue estudando e praticando. À medida que você aplicar o ATER, com o tempo, a parte lógica vai ficando mais clara na sua mente, conforme vai aprendendo e conhecendo mais da linguagem =)

---

Parabéns pelo README, cuidar da apresentação da aplicação é importante.

Cuidado com as linhas em branco. Prefira inserir linhas em branco apenas para dividir blocos de código que fazem coisas diferentes. Apenas uma linha em branco é o suficiente.

No código abaixo,

```javascript
  scrollTo(0, 0)


  finalResult.classList.remove('d-none')
```

como as duas linhas invocam métodos (fazem o mesmo tipo de ação), elas podem ficar juntas. Ficaria assim:

```javascript
  scrollTo(0, 0)
  finalResult.classList.remove('d-none')
```

No mais, parabéns pela aplicação, meu caro 🎉. Continue seguindo o método e você vai longe.

Conte comigo para o que precisar! Estou à disposição para te ajudar a chegar na fluência =)

**Comment by GoharaJunior** [comment]
Obrigado Roger! Rumo a fluencia
