### ISSUE TITLE
Resumo da Aula While loop e exercicios - Aula 01-04 da etapa 02

### ISSUE THREAD

**Issue by guilepereira** [roger-melo-treinamentos/curso-de-js-roger-melo#7104]
# While loop e exercicios - Aula 01-04
- A função do while loop é a mesma que a do loop for, muda apenas a sintaxe;
- Assim como o loop for, o while loop também possui o número de iterações definido em seu escopo;

<br />

## Sintaxe
- While possui apenas uma expressão como parâmetro, diferente de loop for, mas as mesmas expressões são necessárias para seu funcionamento, porém em locais diferentes;
- A variável contadora deve ser iniciada ANTES do loop, ou seja, não está inclusa na sintaxe padrão do loop while;

```js
let i = 0 // variável de controle

while (i < 3) { // condição de iteração
  console.log(i)
  i++ // modificador (incremento/decremento)
}
```

<br />

## Loop infinito
- É importante que todas as partes do loop sejam declaradas antes da execução e da maneira correta:
  - Variável contadora (i); 
  - Condição possível;
  - Expressão de incremento/decremento;

- Caso contrário, pode acontecer um loop infinito, por:
  - Variável contadora não declarada;
  - Condição inalcançável (sempre verdadeira);
  - Ausência de incremento no bloco de código;

- Caso isso ocorra, o loop nunca terá sua condição satisfeita, executando até que cause uma sobrecarga no sistema;

<br />

## Aplicação de While
- Assim como em loop for, while pode ser usada de diversas formas, inclusive na iteração de um array;

```js
const array = ['Domingo', 'Terça', 'Quinta']

let i = 0

while (i < array.length) {
  console.log(array[i])
  i++
}

// Domingo
// Terça
// Quinta
```

<br />

----

<br />

# MDN | Loop While
- Podemos definir o loop while pela sua tradução, que significa "enquanto", que basicamente resume "enquanto a condição for verdadeira, executar o bloco de códigos";
- Assim como no loop for, o loop While executa uma iteração sempre que a condição retornar true, também possui seu número de iterações predefinido e a condição será sempre avaliada antes da iteração;

## Sintaxe
Loop while é composto por:
- Identificador (while);
- Condição ((expressão));
- Bloco de códigos ({Instruções});
- Além destes elementos básicos da sintaxe, existem também as expressões necessárias para o funcionamento do loop, independente de sua forma e são:
  - Variável contadora (declarada antes do loop while);
  - Modificador (incremento/decremento) no bloco de código;

<br />

-------

<br />

**Referências**

[MDN - Loop While](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/while)

**Comment by MivlaM** [comment]
Excelente @guilepereira rumo à fluência! 🎯
