### ISSUE TITLE
Resumo da Aula Conhecendo a date-fns - Aula 02-03 da etapa 10 - Datas

### ISSUE THREAD

**Issue by widneyds** [roger-melo-treinamentos/curso-de-js-roger-melo#7114]
### Principais pontos desta aula:
- A date-fns é uma lib (biblioteca) para trabalhar com datas;
- Ao importar a date-fns podemos fazer uso dela com o objeto `dateFns` através da utilização de seus métodos;
- No [site da date-fns](https://date-fns.org/) está disponível a documentação que pode ser usada para se orientar a respeito dos métodos disponíveis e como eles funcionam;
- Um dos métodos do objeto `dateFns` é o `format()`, que espera receber como argumento: uma data para ser formatada, uma string com os tokens que vão definir como vai ser a formatação (opcional) e um objeto que contém as opções de idioma da data (opcional);
```js
const present = new Date();

const currentDay = dateFns.format(present, 'DD');

const currentMonth = dateFns.format(present, 'MM');

const currentYear = dateFns.format(present, 'YYYY');

const currentDate = dateFns.format(present, 'DD/MM/YYYY');
```
- Outro método do objeto `dateFns` é o `distanceInWords()` que retorna uma string que representa a distância entre duas datas que forem recebidas como argumento. Tem um terceiro argumento que espera um objeto que pode alterar algumas opções mas que é opcional.
```js
const present = new Date();

const past = new Date('April 7 2023 17:00:00');

const distanceBetweenTwoDates = dateFns.distanceInWords(present, past, {addSuffix: true});
```

**Comment by MivlaM** [comment]
Excelente @widneyds rumo à fluência! 🎯
