### ISSUE TITLE
Resumo da Aula A palavra-chave this - Aula 02-03 da etapa 04

### ISSUE THREAD

**Issue by fabiocosta123** [roger-melo-treinamentos/curso-de-js-roger-melo#7118]
A palavra chave ' this ' é um objeto de contexto, ele representa o objeto daquele contexto.
A palavra-chave ' this ' é usada para acessar uma propriedade / referenciar, que está dentro de um objeto ou bloco de código.

**Comment by MivlaM** [comment]
Excelente @fabiocosta123 rumo à fluência! 🎯
