### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#7122]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/adlagomes/quiz_curso_cjrm_2023

### Maiores dificuldades durante a implementação

A maior dificuldade foi em pegar a referência correta das respostas do usuário, e entender que eu precisava criar um array com todas as respostas de uma vez para envia-las. Inicialmente eu estava tentando pegar uma resposta de cada vez e não soube fazer isso.

### Menores dificuldades durante a implementação

pensar no algoritmo e tentar 'dividir para conquistar'.

**Comment by Roger-Melo** [comment]
Olá @adlagomes!

Pode implementar a exibição dos pontos na tela, como a [linha 8 deste exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js#L8) pede. 

Depois de implementar, é só avisar por aqui =)

**Comment by adlagomes** [comment]
Exibição de pontos adicionada e commit realizado =)

**Comment by MivlaM** [comment]
Olá @adlagomes

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by MivlaM** [comment]
Olá @adlagomes

Parabéns pelo esforço em construir a primeira aplicação do treinamento =)

> ## A maior dificuldade foi em pegar a referência correta das respostas do usuário, e entender que eu precisava criar um array com todas as respostas de uma vez para envia-las. Inicialmente eu estava tentando pegar uma resposta de cada vez e não soube fazer isso.

Mesmo com a dificuldade relatada, você conseguiu!

Conforme vc praticar, vc vai entendo e percebendo aos poucos o que pode ser feito.

E você ainda irá praticar bastante no decorrer do treinamento =)

---

## Boas decisões

Você deixou a primeira alternativa de cada pergunta marcada por padrão. Acredito que isso incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

Outra boa decisão que você tomou foi a de deixar o input dentro da label. Isso faz com que o usuário não precise posicionar o mouse e clicar exatamente no input type radio. Basta clicar no texto da alternativa =)

Uma ideia interessante que você teve em relação à usabilidade foi a de posicionar a mensagem dos pontos de forma que ela estivesse no centro da tela após clicar no botão. Isso é bom pois a pontuação aparece justamente onde o usuário estará olhando após enviar as respostas.

Você entendeu que não era necessário manipular DOM dentro do forEach (um erro comum que algumas pessoas cometem). A ideia do forEach ali naquele momento era apenas calcular os pontos, exatamente como vc fez =)

---

Vou deixar abaixo algumas observações sobre sua aplicação

---

## Comentários no código

No index.html há alguns trechos de código comentados, não é uma regra, mas evite comentários.

Comentários podem mentir se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho de atualizar comentários.

---

## Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, dentro da função `quizResult`, a let `score` pode ter um espaço após sua declaração, além disso, após o fechamento do colchete do array `userAnswers` e após o fechamento do bloco do forEach, também podemos adicionar uma linha em branco. Ficaria assim:

```Js
// antes
const quizResult = event => {
  event.preventDefault();
  let score = 0;
  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ];
  userAnswers.forEach((answer, index) => {
    if (answer === questionAnswers[index]) {
      score += 25;
    }
  });
  modal.classList.remove('d-none')
  result.textContent = `Você acertou ${score}% das perguntas.`
}
```

```Js
// depois
const quizResult = event => {
  event.preventDefault();
  let score = 0;

  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ];

  userAnswers.forEach((answer, index) => {
    if (answer === questionAnswers[index]) {
      score += 25;
    }
  });

  modal.classList.remove('d-none')
  result.textContent = `Você acertou ${score}% das perguntas.`
}
```

---

## Code Styling

Ao longo do código, em alguns trechos, há algumas inconsistências em relação às aspas duplas e simples, e ao ponto e vírgula:

```js
// Linha de código de declaração com ponto e vírgula no final e aspas duplas
const form = document.querySelector(".quiz-form");

// Linha de código de declaração sem ponto e vírgula no final e sem aspas duplas
const modal = document.querySelector('#modal')
```

Uma sugestão é que você escolha uma das formas e seja consistente com essa escolha no decorrer do código.

Futuramente, você pode usar uma ferramenta automatizada de formatação de código, mas nesse momento da sua jornada, eu recomendo que vc formate manualmente.

Isso vai "forçar" vc a adotar um estilo de escrita de código e ser consistente com esse estilo ao implementar suas aplicações.

---

## Nomenclatura

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Considerando isso...

Se fizer sentido para você, você pode renomear a const `closeModal` para algo como `closeModalButton`, a ideia aqui é facilitar o entendimento do código por meio de um nome mais específico para o que essa const está armazenando. Ficaria assim:

```js
// antes
const closeModal = document.querySelector('.btn-modal')
```

```js
// depois
const closeModalButton = document.querySelector('.btn-modal')
```

Agora, se você achar interessante, mais a frente na análise vamos dividir essa função `quizResult` em algumas funções menores e mais concisas e específicas para cada trecho de código, tendo isso em mente, no momento, a sugestão aqui é renomear a função `quizResult` para algo mais abrangente, algo como `handleFormSubmit` a ideia aqui é fazer com que essa função seja responsável apenas para passar adiante a informação que ela vai receber das outras partes do código. Ficaria assim:

```js
// antes
const quizResult = event => {
  // ... 
}
```

```js
// depois
const handleFormSubmit = event => {
  // ... 
}
```  

---

## Nome para o callback do listener de evento

Podemos nomear o callback do listener de evento que é responsável por fechar o modal como `closeModal`, por exemplo. A vantagem aqui, é que nomear callbacks de listeners de eventos dá mais legibilidade ao seu código, o intuito aqui é nomeá-lo descrevendo a ação mais significativa que a função irá executar na aplicação quando for executada, no caso é a função de fechar o modal. Assim ao bater o olho no nome da função, a ação que ela executa fica explícita:

```js
// antes
closeModalButton.addEventListener('click', () => {
  modal.classList.add('d-none')
})
```

```js
// depois
const closeModal = () => {
  modal.classList.add('d-none')
}

closeModalButton.addEventListener('click', closeModal)
```

---

## Função getUserScore

Feito esses ajustes, vou te mostrar algumas abordagens de refactoring envolvendo a criação de algumas funções para deixarmos o código mais conciso em relação a cada trecho de seu funcionamento. O que quero que você entenda, nesse primeiro momento, é o conceito por trás delas. Sabendo disso, observe o código abaixo:

```js
let score = 0
  
userAnswers.forEach((answer, index) => {
  if (answer === questionAnswers[index]) {
    score += 25
  }
})
```

No código acima, está a lógica que você usou para calcular a pontuação. A sugestão aqui, é criarmos uma nova função específica para lidar com a pontuação, como vai ser uma função para obter a pontuação, um nome interessante para ela seria algo como `getUserScore`. Nessa nova função, podemos simplificar a lógica de obter os pontos ao declarar `score` dentro dessa função e fazer com que a função retorne `score`. Ficaria assim:

```js
const getUserScore = userAnswers => {
  let score = 0
  
  userAnswers.forEach((answer, index) => {
    if (answer === questionAnswers[index]) {
      score += 25
    }
  })
  return score
}
```

Sendo assim, você pode invocar a função `getUserScore` dentro da função que ela estava anteriormente, ou seja, em `handleFormSubmit` recebendo o array armazenado por `userAnswers` como argumento. Ficaria assim:

```js
const handleFormSubmit = event => {
  // ...
  const score = getUserScore(userAnswers)
  // ...
}
```

---

## Função getUserAnswers

A segunda abordagem é a seguinte. Vamos criar uma função especificamente para obter a resposta do usuário. Essa função pode se chamar `getUserAnswers`, nela podemos criar uma const `userAnswer` que vai receber uma expressão que pega o valor de cada inputQuestion do form. `userAnswers` vai receber um array vazio que será preenchido após percorrermos cada item dentro do array `questionAnswers` por meio do método forEach, e por fim, esse valor que contém as respostas do usuário e que foi armazenado em `userAnswers` vai ser retornado. Ficaria assim:

```js
const getUserAnswers = () => {
  const userAnswers = []
  
  questionAnswers.forEach((_, index) => {
    const userAnswer = form[`inputQuestion${index + 1}`].value
    userAnswers.push(userAnswer)
  })
  
  return userAnswers
}
```

Por fim, você também pode invocar essa função dentro da função `handleFormSubmit` que o código funcionará normalmente =)

```js
const handleFormSubmit = event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()

  const score = getUserScore(userAnswers)

  // ...
}
```

---

## Função showScore

Agora, a sugestão aqui é criarmos uma nova função responsável unicamente pela manipulação de DOM e invocarmos ela nessa função também. Atualmente, a função `handleFormSubmit` também é responsável pelas linhas de manipulação de DOM, e para deixar mais claro o papel de apenas passar informações para a frente, podemos criar uma função `showScore` que vai ser unicamente responsável pela manipulação de DOM e invocar essa função em `handleFormSubmit`. Assim, além de facilitar o fluxo de leitura, você separa mais as responsabilidades, agora que não tem manipulação de DOM em `handleFormSubmit`, essa função agora é apenas responsável por passar informações para frente, para que outras partes da aplicação executem o que precisa ser executado, como por exemplo, exibir a pontuação. Ficaria assim:

```js
const showScore = score => {
  modal.classList.remove('d-none')
  result.textContent = `Você acertou ${score}% das perguntas.`
}

const handleFormSubmit = event => {
  event.preventDefault()
  
  const userAnswers = getUserAnswers()

  const score = getUserScore(userAnswers)

  showScore(score)  
}
```

---

Nas aulas seguintes, você verá outras formas de refatorar o código dessa aplicação.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by MivlaM** [comment]
Ok! Bem, vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
