### ISSUE TITLE
Etapa 4, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#714]
Esse é o exercício nº9 , vou colar abaixo a minha primeira tentativa de resolução( logo após a leitura do
 enunciado):
````js
/*
  09

  - Crie uma função que recebe um parâmetro 'type';
  - Dentro da função, crie um objeto com as seguintes propriedades:
    - null, que recebe a mensagem 'Seta, explicitamente, uma variável sem valor.'
    - undefined, que recebe a mensagem 'Representa um valor não-setado.'
    - object, que recebe a mensagem 'Arrays, Datas, Objetos literais, Funções, etc.'
  - Se o valor que o parâmetro type receber corresponder à alguma das 3  
    propriedades, retorne a mensagem que a propriedade armazena;
  - Teste a função, exibindo no console a mensagem de cada propriedade.
*/
const myFuncTypes = function (type) {
  const myObj = {
    null: 'Seta, explicitamente, uma variável sem valor.',
    undefined: 'Representa um valor não-setado.',
    object: 'Arrays, Datas, Objetos literais, Funções, etc.'
  }
    switch (type) {
      case null:console.log(myObj.null)
        break;
      case undefined:console.log(myObj.undefined)
        break;
      case 'object':console.log(myObj.object)
        break;
        
      default:console.log(`O Valor atual "${type}" difere dos anteriores, pois seu Tipo é: "${typeof type}"`)
        break;
    }
}
let foo  = null
myFuncTypes(foo)

let foo2
myFuncTypes(foo2)

let foo3 = ['sdfgd','sdfg','sgs']
myFuncTypes(foo3)

let numb = 123
myFuncTypes(numb)
````
    E logo abaixo o Browser :

![image](https://user-images.githubusercontent.com/44072541/119207190-cab81880-ba73-11eb-8bc5-312daee81b67.png)

    

    Eu travei nesse ponto , não consegui fazer 'object' funcionar ,ou melhor apenas quando transformei o nome 
da propriedade em 'string' , mas o 'Type object' não consegui;
    Por favor me ajude a usar esse 'impecílio' como material de estudo.
 
    Dúvidas : &gt;nº 1 - Mesmo pesquisando sobre 'null' pra mim não ficou claro como criar uma expressão
que retorne um valor 'null', os parágrafos abaixo eu tirei do MDN:

  &lt;..representa a intencional ausência de qualquer valor de objeto...&gt;
  &lt;...expressa um vazio de identificação, indicando que a variável não aponta para um objeto...&gt;

   Essa foi a tradução que fiz, a expressão ' let foo = null' eu coloquei apenas para testar o código;

    &gt;nº 2 - Object e suas Porperties agem de forma similar aos Arrays e seus elementos?

    &gt;nº 3 - Teria alguma dica para melhorar meu método de pesquisa , a sensação que tenho é que, dedico
um bom tempo lendo(traduzindo) os artigos do MDN, mas na hora dos exercícios parece que esse conteúdo 
"não floresce"

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá Marcos!

> Eu travei nesse ponto , não consegui fazer 'object' funcionar ,ou melhor apenas quando transformei o nome da propriedade em 'string' , mas o 'Type object' não consegui;

`null` e `undefined` são palavras reservadas da linguagem. Então o interpretador consegue buscar as propriedades com esse nome, apenas transformando essas palavras que ele já entende em strings pra pegar as props do objeto.

Já `object` não é uma palavra reservada, e é uma palavra válida para nome de variável. Então o interpretador espera que exista uma variável chamada `object` e que ela contenha um valor para ser avaliado, e então conseguir tentar buscar a propriedade do objeto. Por isso, `Uncaught ReferenceError: object is not defined` é lançado no console se `object` não for uma string =)

> Mesmo pesquisando sobre 'null' pra mim não ficou claro como criar uma expressão que retorne um valor 'null'

Vc vai retornar o `null` quando quiser **indicar intencionalmente** que não existe valor em uma variável. Como vc fez no código abaixo:

```javascript
let foo = null
```

Se você quiser que a invocação de uma função retorne `null`, por exemplo, basta inserí-lo após o `return`:

```javascript
const myFunc = () => {
  // várias linhas de código aqui...
  return null
}

// ou

function myFunc2 () {
  // várias linhas de código aqui...
  return null
}

console.log(myFunc())  // null
console.log(myFunc2()) // null
```

Esse é um exemplo de expressão que retorna `null` =)

> Teria alguma dica para melhorar meu método de pesquisa?

Na verdade, eu recomendo seguir [estes passos](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) e ter paciência. Você não precisa acertar de primeira e alguns conceitos são absorvidos apenas com o tempo e a prática (mesmo com a ajuda do MDN). 

Geralmente os últimos exercícios das baterias de exercícios são exercícios-modelo. Então são exercícios que vão exigir mais da sua atenção.

O enunciado desse exercício, por exemplo, pede para que a mensagem que a propriedade que `type` armazena seja **retornada**. 

Um outro ponto importante é o uso da sintaxe `obj[prop]`. Dentro desses colchetes, o nome da propriedade precisa ser uma string ou uma variável que armazena uma string, como mencionado [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/816557). 

```javascript
const obj = { prop1: 1 }

obj['prop1'] // 1
```

Você pode inserir qualquer expressão dentro dos colchetes, mas por baixo dos panos, para acessar a propriedade, o resultado dessa expressão será convertido para string:

```javascript
const obj = { prop1: 1 }
const obj2 = { 1234: 'olá' }

obj['prop' + 1] // 1
obj2[1234] // 'olá'
```

Além disso, objetos javascript podem ter strings como propriedades:

```javascript
const obj3 = { 'prop1': 1 }

obj3['prop1'] // 1
obj3.prop1 // 1

obj3['prop2'] = 2

obj3['prop2'] // 2
obj3.prop2 // 2
```

Por isso, é possível acessar as propriedades de um objeto através da invocação de `getTypeDefinition('null')`, por exemplo.

Com o uso da sintaxe `obj[prop]`, vc pode descartar o uso do `switch/case` e deixar o código mais simples =)

Ficou mais claro?

@marcosyoggy

**Comment by Roger-Melo** [comment]
@marcosyoggy se não tiver ficado claro é só dar o toque que explico de outra forma. Por hora vou fechar a issue mas se quiser prosseguir o assunto, eu reabro =)
