### ISSUE TITLE
Resumo da Aula Um overview sobre tipos de dados - Aula 02-02 da etapa 01

### ISSUE THREAD

**Issue by AdalbertoEscandiel** [roger-melo-treinamentos/curso-de-js-roger-melo#7140]
Em JS se trabalha com oito tipos de dados:

Number  números 1,2, 100.
String  "texto" ou 'texto'.
Boolean condição de verdadeiro ou falso.
Null  forma de dizer que a variável não tem valor. valor vazio feito pelo programador
Undefined também sem valor, mas definido automaticamente pelo programa.
Object estruturas complexas cujo dentro dela vc pode ter múltiplas propriedades e funções. Muito usado no JS e com muitos tipos diferentes embutidos na linguagem. ex arrays, objetos e funções. Na realidade, tudo no JS é objeto.
Symbol relacionado a objetos.
Bigint usado para representar números inteiros muito grandes.

Uma variável pode armazenar qualquer tipo de dados.

**Comment by MivlaM** [comment]
Excelente @AdalbertoEscandiel !! Rumo a fluência.
