### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by Bruno-Luna** [roger-melo-treinamentos/curso-de-js-roger-melo#7161]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/Bruno-Luna/js-quiz

### Maiores dificuldades durante a implementação

> Validação simultânea de todos os campos. (ainda precisa ser feita)
> Capturar os valores do inputs do tipo `radio`
> Refatoração em certos pontos em especial od `IF`

### Menores dificuldades durante a implementação

> Utilizar o `addEventListener`
> Utilizar o `preventDefault`
> Capturar os elementos html via javascript, como botões e form

**Comment by Bruno-Luna** [comment]
Olá, boa noite!

@MivlaM , agradeço as orientações. As alterações foram feitas, o link mudou e inserir no campo principal acima.

Aguardo o retorno.

Grato.

**Comment by MivlaM** [comment]
Olá @Bruno-Luna

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Bruno-Luna** [comment]
@MivlaM, grato!

**Comment by Bruno-Luna** [comment]
Grato pela correção/atenção, @MivlaM

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
