### ISSUE TITLE
Aplicação: [Quiz-Interativo]

### ISSUE THREAD

**Issue by CaioHTeixeira** [roger-melo-treinamentos/curso-de-js-roger-melo#717]
Repositório do Quiz: https://github.com/CaioHTeixeira/Quiz-Interativo.git
Minhas maiores dúvidas foram em relação a implementação do CSS e do HTML pois fiquei em dúvida em como montar o layout da página e acabei aproveitando o popup que implementei das aulas anteriores para exibir o resultado.
Minhas menores dificuldades foram na lógica e organização do programa.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CaioHTeixeira.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by CaioHTeixeira** [comment]
Está tudo ok, aguardo feedback :)

**Comment by Roger-Melo** [comment]
Olá Caio.

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar a aplicação.

## Usabilidade

Acredito que recarregar a página após o fechamento do popup pode prejudicar um pouco da previsibilidade da aplicação para o usuário, pois isso impede que o usuário continue vendo as alternativas que ele marcou antes de fazer um próximo envio.

Observe também que a propriedade `.reload` não foi mostrada no treinamento. O desafio é fazer os exercícios e aplicações usando apenas o que você viu no treinamento =)

Nas aulas seguintes, eu mostro uma forma de não precisar recarregar a página após o envio do quiz e fazer o 2º submit em diante não considerar a pontuação do envio anterior.

## Organização de código

### Comentários

Evite comentários na hora de subir a aplicação para produção.

Comentários podem mentir. Se o código for modificado e o comentário correspondente não for atualizado, o comentário perde o sentido. Isso sem mencionar o retrabalho em atualizá-los.

Se você faz questão de usar comentários como objeto de estudos, é melhor manter duas versões do código: a de produção (sem comentários) e a de desenvolvimento/estudos.

### Nomes de variáveis e funções

A const `popup` pode ser mais descritiva sobre o que ela armazena se for renomeada como `scorePopup` ou algo parecido.

### Convenções

É uma convenção que operadores de pós/pré incremento não sejam separados por espaço. Então ao invés de `rightAnswers ++`, prefira `rightAnswers++`.

---

No mais, é isso. Novamente, parabéns pelo esforço em construir a primeira aplicação do treinamento =)

As observações acima fizeram sentido?

@CaioHTeixeira

**Comment by CaioHTeixeira** [comment]
Obrigado pelo feedback, fizeram sentido sim. Vou aplicar as devidas melhorias :)

**Comment by Roger-Melo** [comment]
Excelente. Vou fechar a issue mas no que precisar, é só dar o toque =)
