### ISSUE TITLE
Aplicação: Os inputs radios estão com algum problema

### ISSUE THREAD

**Issue by Rodrigo-M-Brazao** [roger-melo-treinamentos/curso-de-js-roger-melo#718]
meu código funciona porém por algum motivo a pergunta 4 está com os dois radios ligados aos radios da pergunta 3 gostaria de saber qual o problema que eu não consigo ver segue o html que acho q está o problema:
<body>
  <div class="intro py-3 bg-warning text-center">
    <div class="container">
      <h2 class="text-light display-3 my-4">Quiz</h2>
      <p class = "score">Pontuação: </p>
    </div>
  </div>

  <div class="quiz py-4 bg-secondary">
    <div class="container">
      <h2 class="my-5 text-white">Você consegue acertar essas perguntas sobre Filmes?</h2>

      <form class="quiz-form text-light">
        <div class="my-5">
          <p class="lead font-weight-normal">1. Quantos filmes do universo dos livros de Harry Potter foram lançados até o ano de 2021: </p>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion1" value="A" checked>
              8
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion1" value="B">
              10
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="C">
              9
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="D">
              7
            </label>
          </div>

          
        </div>

        <div class="my-5">
          <p class="lead font-weight-normal">2. Qual ator foi o último a interpretar o Batman nos cinemas até o ano de 2021: </p>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion2" value="A" checked>
              Ben Affleck
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion2" value="B">
              Christian Bale
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="C">
              Robert Pattison
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="D">
              George Clooney
            </label>
          </div>

        </div>

        <div class="my-5">
          <p class="lead font-weight-normal">3. Qual o data no futuro Martin Mcfly viaja: </p>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="A" checked>
              26/10/2015
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="B">
              21/10/2015
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="C">
              21/09/2016
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="D">
              26/09/2017
            </label>
          </div>

        </div>

        <div class="my-5">
          <p class="lead font-weight-normal">4. Qual o nome do primeiro filme lançado da franquia Star Wars: </p>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="A" checked>
               Star Wars: O Despertar da Força
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="B">
              Star Wars: A Ameaça Fantasma
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion3" value="C">
              Star Wars: O Retorno do Jedi
            </label>
          </div>
          <div class="form-check my-2 text-white-50">
            <label class="form-check-label">
              <input type="radio" name="inputQuestion4" value="D">
              Star Wars: Uma Nova Esperança
            </label>
          </div>

        </div>
        
        <div class="text-center">
          <button class="btn bg-primary text-light">Enviar</button>
        </div>
      </form>
    </div>
  </div>

  <script src="./app.js"></script>
</body>
</html>

@Roger-Melo

**Comment by Roger-Melo** [comment]
Vou fechar a issue mas no que precisar, é só abrir uma nova =)
