### ISSUE TITLE
Etapa 7, Aplicaçao Quiz Interativo - Exercício 19

### ISSUE THREAD

**Issue by fran-special-19** [roger-melo-treinamentos/curso-de-js-roger-melo#72]
Oi Roger.

Eu sou Francisco e estudo JavaScript há 3 meses.

- Maiores dificuldades: A minha maior dificuldade foi na implementação dos botões de rádio do Bootstrap. Quando eu cliquei em uma das opções de uma pergunta, a opção escolhida da pergunta anterior some e o que eu escolhi era marcada. Eu então percebi que o problema era na nomeação de id de cada item da pergunta pois tinham os mesmos nomes. Quando renomeei os ids, o problema foi resolvido.

- Menores dificuldades: O que mais me animou foi na codificação do JavaScript pois eu lembrei do que você tinha feito na aula passada. Quando testei a minha versão funcionou corretamente sem erros no console.

Link: [Repositório do meu exercício](https://github.com/fran-special-19/quiz-interativo-francisco)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá, Francisco!

> Menores dificuldades: O que mais me animou foi na codificação do JavaScript pois eu lembrei do que você tinha feito na aula passada. Quando testei a minha versão funcionou corretamente sem erros no console.

Fico muito feliz que esteja percebendo progresso =)

> Maiores dificuldades: A minha maior dificuldade foi na implementação dos botões de rádio do Bootstrap. Quando eu cliquei em uma das opções de uma pergunta, a opção escolhida da pergunta anterior some e o que eu escolhi era marcada. Eu então percebi que o problema era na nomeação de id de cada item da pergunta pois tinham os mesmos nomes. Quando renomeei os ids, o problema foi resolvido.

Entendi. Esses erros bobos também nos ensinam. Devido a essa experiência, a probabilidade de você, futuramente, não cometer o mesmo erro é maior.

---

Vou deixar abaixo alguns pontos que você pode considerar para melhorar a aplicação.

- O local da exibição dos pontos

Observe que após o envio do form, a única modificação visual imediata é a barra de rolagem. Um usuário comum pode interpretar que nada aconteceu quando ele pressionou o botão de envio, quando na verdade, os pontos foram exibidos abaixo da borda inferior da tela. Neste caso, uma opção seria exibir a pontuação ao lado do botão. Mas é apenas um detalhe de usabilidade. Nas aulas seguintes, mostro uma forma de implementar a exibição dos pontos =)

- A falta de linhas em branco

Há apenas uma linha em branco no código, entre a `const results` e o `addEventListener` do form.

Você pode inserir linhas em branco em todo o código para dividir blocos de código que fazem coisas diferentes.

Então ao invés do código ficar assim:

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()
  let points = 0
  let htmlMessage = ''
  const userAnswers = [
    // valores do array...
  ]

  // restante do código...
}
```

Prefira deixá-lo assim:

```javascript
form.addEventListener('submit', event => {
  event.preventDefault()

  let points = 0
  let htmlMessage = ''
  
  const userAnswers = [
    // valores do array...
  ]

  // restante do código...
}
```

No código acima, as linhas em branco são usadas para separar invocações de métodos, declarações de valores iniciais, declarações de arrays.

- Indentação de templates HTML

Observe que o código abaixo está com as quebras de linhas corretas. Só faltou indentar a marcação HTML, para indicar que ela está dentro da abertura e fechamento da template string.

```javascript
  htmlMessage += `
  <p>Sua pontuação:</p>
  <h1>${finalScore}%</h1>
  <p>Questões acertadas: ${points}</p>
  <p>Obrigado por jogar :)</p>
  `
```

Com o HTML indentado, ficaria assim:

```javascript
  htmlMessage += `
    <p>Sua pontuação:</p>
    <h1>${finalScore}%</h1>
    <p>Questões acertadas: ${points}</p>
    <p>Obrigado por jogar :)</p>
  `
```

---

No mais, parabéns pelo esforço, meu caro 🎉. Continue seguindo o método e você vai longe.

Conte comigo para o que precisar! Estou à disposição para te ajudar a chegar na fluência =)

@fran-special-19

**Comment by fran-special-19** [comment]
Obrigado Roger. Boa noite.
