### ISSUE TITLE
Resumo da Aula Event bubbling e event delegation - Aula 04-02 da etapa 05

### ISSUE THREAD

**Issue by fabiocosta123** [roger-melo-treinamentos/curso-de-js-roger-melo#7207]
Event bubbling - Começam quando clicamos em um elemento, esse elemento se torna o target e aciona uma função de callback, porém essa propagação continua para o elemento pai do target. Por exemplo:

<body>
    <h1>Criando e removendo elementos do DOM</h1>

    <h2>Todos</h2>

    <ul>
        <li>Comprar Frango</li>
        <li>Ler Livros</li>
        <li>Tocar Violão</li>
        <li>Pagar Contas</li>
    </ul>
</body>

Ao clicar na tag li (Comprar Frango) - essa " li " passa a ser target, suponhamos que nessa " li " temos uma função que ao ser clicado muda a cor do elemento, então ao ser clicada, será acionada uma função de callback e além disso, esse evento será propagado para todo o DOM em busca de alguma ação relacionada, ou seja, esse evento de target na " li " será propagada para o elemento pai da " li " que é a "ul " e caso tenha algum evento na 'ul' esse evento de propagação irá acionar a função de callback da 'ul' que por sua vez passa a ser o target que irá se propagar para o elemento pai da 'ul' que é o body e será assim até o topo do DOM. Para evitar esse tipo de comportamento, podemos usar o método stopPropagation(), ele vai impedir a propagação do clique pelo DOM, ou seja, ele para o event bubbling.

**Comment by MivlaM** [comment]
Excelente @fabiocosta123 rumo à fluência! 🎯
