### ISSUE TITLE
Resumo da Aula Funções vs Métodos - Aula 02-03 da etapa 03

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#7218]
## Funções vs Métodos

> Funções são blocos de código que executam uma tarefa que não estão associadas a um objeto ou classe específica, enquanto os métodos são funções associadas a um objeto ou classe.

### Sintaxe básica:

```js
// função
const hello = () => 'Hello!'

// método
const name = 'Roger'
const nameInUpperCase = name.toUpperCase()
```

<!-- ### Exemplo:

> Descrição do exemplo

```js

```

> console

```js

``` -->

<!-- Escreva/insira as imagens após essa linha -->

**Comment by MivlaM** [comment]
Excelente @Geisonszo rumo à fluência! 🎯
