### ISSUE TITLE
Resumo da Aula O que são requests HTTP - Aula 01-04 da etapa 11

### ISSUE THREAD

**Issue by DevNeves** [roger-melo-treinamentos/curso-de-js-roger-melo#7227]
<h1> O que são requests HTTP - Aula 01-04 </h1>

+ requests HTTP é uma operação que leva um certo tempo para serem finalizadas

<h3> Por que precisamos deles? </h3>

<p> Haverá momentos em que precisaremos dentro das nossas aplicações exibir certas informações que estão armazenadas em outro lugar (servidor) que pode ser um banco de dados ou uma API. </p>

<h3> O que é uma API ?</h3>

<p> Application Programming Interface, API é uma ferramenta para que um sistema se comunique com outro sistema </p>

<h2> Para obter essas informações (se conectar com uma API ou banco de dados) ultilizamos os requests HTTP (Requisisões HTTP)</h2>
<h3> HTTP : Hypertext Transfer Protocol, é um protocolo principal de comunicação entre computadores na internet</h3>
<h3> Quando se faz um requests HTTP para um API ou servidor esse request é feito para um END POINT, é uma URL que o servidor disponibiliza para que podemos para usar e obter informações que a API ou servidor armazena </h3>

![Screenshot_1](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/102633306/b6b18af9-3114-4c5e-ba5f-1275bf85bee3)

<h3> Quando se faz um request para um end point geralmente o formato da resposta é um JSON </h3>

<h3> JSON Javascript Object Notation : que é um padrão usado para troca e armazenamento de informações entre sistemas, o JSON é se parece com um objeto js </h3>

**Comment by MivlaM** [comment]
Excelente @DevNeves rumo à fluência! 🎯
