### ISSUE TITLE
Resumo da Aula Tipos de refêrencia vs Tipos primitivos - Aula 03-04 da etapa 04

### ISSUE THREAD

**Issue by Geisonszo** [roger-melo-treinamentos/curso-de-js-roger-melo#7236]
## Tipos de refêrencia vs Tipos primitivos

> Em JavaScript, existem dois tipos principais de dados: tipos de referência e tipos primitivos.

> Os **tipos de referência** são objetos e são armazenados por referência. Isso significa que, quando uma variável é atribuída a um tipo de referência, a variável não contém diretamente os dados, mas sim uma referência (endereço de memória) para o objeto onde os dados estão armazenados. Quando você atribui um tipo de referência a outra variável ou passa-o como argumento para uma função, a referência é copiada, não os dados reais. Isso significa que ambas as variáveis ou parâmetros da função apontam para o mesmo objeto na memória.

> Os **tipos primitivos** são valores imutáveis ​​e são armazenados diretamente na variável. Eles são atribuídos por valor, o que significa que, quando uma variável é atribuída a um tipo primitivo, o valor real desse tipo é copiado para a variável. Os tipos primitivos são copiados por valor quando atribuídos a outras variáveis ou passados como argumentos para funções. Cada variável contém uma cópia independente do valor.

### Exemplo - Tipos de Referência:

> Objetos Literais:

```js
const objeto = { chave: "valor" };
```

> Arrays:

```js
const array = [1, 2, 3];
```

> Funções:

```js
const funcao = function() { /* código da função */ };
```

### Exemplo - Tipos de Primitivos:

> String:

```js
const nome = "João";
```

> Number:

```js
const idade = 25;
```

> Boolean:

```js
const valido = true;
```

### Exemplo - Tipos de refêrencia vs Tipos primitivos :

```js
// valores primitivos
let scoreOne = 50
let scoreTwo = scoreOne

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);
// Saída: scoreOne: 50 | scoreTwo: 50

scoreOne = 100

console.log(`scoreOne: ${scoreOne} | scoreTwo: ${scoreTwo}`);
// Saída: scoreOne: 100 | scoreTwo: 50

// valores de referência
let userOne = { name: 'Roger', age: 31 }
let userTwo = userOne

console.log(userOne, userTwo);
// Saída: { name: 'Roger', age: 31 } { name: 'Roger', age: 31 }

userOne.age = 32

console.log(userOne, userTwo);
// Saída: { name: 'Roger', age: 32 } { name: 'Roger', age: 32 }
```

**Comment by MivlaM** [comment]
Excelente @Geisonszo rumo à fluência! 🎯
