### ISSUE TITLE
Etapa 14, Factory functions e composição de objetos - Aula 03-09

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#724]
Olá Roger, tudo bem?
Uma função como mostrada no código abaixo, que não retorna diretamente um objeto literal, mas sim a referência de um objeto criado no próprio escopo da função, é uma factory function também?

```js
const createUser = (name) => {
  const user = Object.create({ getName: () => this.name })
  user.name = name

  return user
}
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel! Tudo certinho, e contigo? xD

Com certeza. Se cria um novo objeto e o retorna, é uma factory function (independente de como o objeto é criado) =)

Sua dúvida não foi sobre isso mas cuidado ao usar o `this`. No exemplo que você deu, como `getName` é uma arrow function, o `this` dela referencia o `this` do escopo da `createUser`. E como `createUser` também é uma arrow function, o `this` dela referencia o escopo global (que é o escopo no qual ela foi declarada). Por isso, ao invocar o `getName`, `this` referencia o objeto `window` e como o `window` tem uma propriedade `name` que armazena uma string vazia, a string é exibida no console.

```javascript
const createUser = name => {
  console.log(this) // Window {window: Window, …}

  const user = Object.create({ getName: () => this.name })
  
  user.name = name
  return user
}

console.log(createUser('Roger').getName()) // ''
```

Para que o `this` do método `getName` referencie o objeto no qual a invocação de `getName` é encadeada, `getName` precisa ser uma função ES5 tradicional (ou uma abreviação):

```javascript
const createUser = name => {
  console.log(this) // Window {window: Window, …}

  const user = Object.create({
    getName () {
      return this.name 
    }
  })
  
  user.name = name
  return user
}

console.log(createUser('Roger').getName()) // 'Roger'

const user2 = createUser('Zé')
console.log(user2.getName()) // Zé
```

Neste caso, mesmo que o `this` dentro da `createUser` referencie o objeto `window`, o `this` da `getName` referencia o objeto no qual o método `getName` é invocado (e não o `this` do escopo da `createUser`).

Sacou a ideia?

@sou-gabriel

**Comment by sou-gabriel** [comment]
O this realmente é muito imprevisível professor. Mas, com sua explicação consegui sacar esses detalhes dele. 
Um outro adento professor, ainda sobre o this, uma function declaration (ES5) quando declarada no escopo global faz o this se conectar ao objeto global ```Window``` por que ele é o objeto na qual essa função está declarada ou é por que o comportamento de uma function declaration dentro de um objeto é um e fora é outro?

**Comment by Roger-Melo** [comment]
O `this` referencia o objeto no qual a invocação da função/método foi encadeado. Ou seja, em `obj.myFunc()` o `this` vai referenciar o que vem à esquerda do ponto na invocação do método:

```javascript
const obj = {
  myFunc () {
    return this // referencia o que está à esquerda do .
  }
}

// como o que está à esquerda do . é obj, {myFunc: ƒ} foi retornado
obj.myFunc()
```

Sabendo disso, agora vem o lance: funções ES5 declaradas em escopo global são propriedades do `window`:

```javascript
function myFunc () {}

console.log(window.myFunc) // ƒ myFunc () {}
```

Como não é necessário especificar `window.` antes de usar propriedades ou métodos do `window`, `myFunc` pode ser referenciada ou invocada apenas assim:

```javascript
myFunc
myFunc()
```

Porém, o mesmo conceito se aplica: o `this` de `myFunc` referencia o objeto no qual a invocação dela foi encadeada. Como `myFunc` é um método no qual a invocação é encadeada (mesmo que "invisivelmente") no objeto `window`, o `this` dentro dela referencia o objeto `window`:

```javascript
function myFunc () {
  return this
}

console.log(myFunc()) // Window {…}
console.log(window.myFunc()) // Window {…}
```

Sacou a ideia? =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
> Sacou a ideia? =)

Plenamente Roger, esta era a minha última dúvida a respeito do this. Obrigado por me ajudar professor! 😁
