### ISSUE TITLE
Resumo da Aula Aula 03-04 da etapa 05

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#725]
# - Resumo da aula Criando e removendo elementos do DOM

Para remover elementos do DOM podemos usar o conhecido método `.remove()`.

ex.:
```js
const myP = document.querySelector('p') // Obtém a referência de u parágrafo

myP.addEventListener('click', event => {

    const triggerEvent = event.target

    triggerEvent.remove()
})

```

Para adicionar elementos ao DOM, além da propriedade `.innerHTML`, podemos utilizar
o método `.createElement()`. Podemos adicionar conteúdo ao elemento criado através da 
conhecida propriedade `.textContent`.

As formas de adicionar o elemento criado ao DOM, são através dos métodos `.append()` e `.prepend()` no pai do elemento.

O método `.append()` adiciona o elemento criado como último filho e o `.prepend` adiciona o elemento criado como primeiro filho.

ex.:
```js

const myBtn = document.querySelector('button')

const myUl = document.querySelector('ul')

myBtn.addEventListener('click', () => {

  const myLi = document.createElement('li')

  myLi.textContent = 'Novo Item'

  myUl.append(myLi) // Adiciona elemento como último filho da ul

  /* myUl.prepend(myLi) // Adiciona elemento como primeiro filho da ul*/
})

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @WebDevCampos, rumo à fluência!!! 🚀
