### ISSUE TITLE
Resumo da Aula Adicionando métodos - Aula 01-04 da etapa 04

### ISSUE THREAD

**Issue by guilepereira** [roger-melo-treinamentos/curso-de-js-roger-melo#7255]
# Adicionando métodos - Aula 01-04

## Conteúdo de um objeto: **métodos**
- Métodos são ações armazenadas à propriedades de um objeto;
- Métodos devem ser invocados como funções (uso de parênteses);
```js
let compra = {
  carrinho: ['Produto X', 'Produto Y', 'Produto Z'],
  finalizar: function () {

    console.log(`Produtos comprados:`)

    const quantidadeProdutos = compra.carrinho.length
    for (let i = 0; i < quantidadeProdutos ; i++) {
      
      const produto = compra.carrinho[i]
      console.log(`- ${produto}`)
    }

    console.log('Compra finalizada!')
  } 
}

compra.finalizar()
// Produtos comprados:
// - Produto X
// - Produto Y
// - Produto Z
// Compra finalizada!
```

## Invocando métodos
A invocação do método é similar ao de uma função, o que difere é a presença do objeto encadeado no início da expressão de invocação;
```js
compra.finalizar()
```
> Funções criadas fora de um objeto são funções (tradicionais) e métodos são funções criadas dentro de objetos;

**Comment by MivlaM** [comment]
Boa @guilepereira , rumo a fluência!!
