### ISSUE TITLE
Etapa 7, Exibindo a pontuação - Aula 02-01

### ISSUE THREAD

**Issue by CaioHTeixeira** [roger-melo-treinamentos/curso-de-js-roger-melo#727]
No label que exibe o resultado do quiz o símbolo de % não está aparecendo. Está aparecendo somente o valor da porcentagem mas o símbolo dela não está.
Ex: "Você acertou 75 do quiz!"

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @CaioHTeixeira. Poste o código na issue ou suba os arquivos em um repositório no github e poste o link. Assim fica mais fácil eu reproduzir o código em minha máquina e dizer o que está acontecendo =)

Se preferir postar na issue, poste o código de todos os arquivos =)

**Comment by Roger-Melo** [comment]
Tranquilo. No que precisar, é só dar o toque =)
