### ISSUE TITLE
Resumo da Aula Conhecendo a date-fns - Aula 02-03 da etapa 10

### ISSUE THREAD

**Issue by OnielStgo** [roger-melo-treinamentos/curso-de-js-roger-melo#7271]
# Biblioteca date-fns

A biblioteca (ou lib) **date-fns** é muito útil para manipular datas em JavaScript

Para usar a lib date-fns devemos colocar no nosso arquivo html o link da CDN dela, mas as últimas versões da lib date-fns não disponibilizam o link de CDN para sua utilização, ou seja, para usá-la temos que instalá-la num projeto no Nodejs. Mas acontece que até versão 1.9.0 a lib date-fns sim disponibiliza o link da CDN e portanto podemos colocar esse link no nosso arquivo html. 

Então, por exemplo, para usar o link da CDN da versão 1.9.0 no nosso arquivo html, devemos ir até a página oficial da lib (https://date-fns.org/) e aí dentro fazer click em "Documentation > Getting Started > Selecionar a versão na borda superior direita > Fazer click em CND & Download" então copiamos um código parecido ao seguinte: 
```js
<script src="http://cdn.date-fns.org/VERSION/date_fns.min.js"></script>

// Nota: devemos apagar VERSION e colocar o número da versão que queiramos usar, exemplo: v1.9.0 
// Nota: O link podemos colocá-lo antes de fechar a tag body, acima das tags de script de nosso arquivo js principal.
```
Agora, supondo que já colocamos o link da CDN no nosso arquivo html, no arquivo JavaScript principal (que está linkado também no nosso arquivo html) podemos colocar o seguinte código:
```js
console.log(dateFns)

//Resposta:
{addDays: ƒ, addHours: ƒ, addISOYears: ƒ, addMilliseconds: ƒ, addMinutes: ƒ, …}

//Então, ao executar o código acima na consola do navegador, poderemos ver que foi impresso o objeto dateFns, e se fazemos clique nele podemos ver todas as propriedades e métodos que o objeto dateFns tem. 
```
## Alguns dos tantos métodos do objeto dateFns são:
- **isToday** --> diz se a data passada como argumento corresponde à data atual. Retorna "true" caso a data passada como argumento corresponda com a data atual, caso contrario false é devolvido.
- **format** --> formata uma data. Pode receber três argumentos (dois obrigatórios e um opcional). O primeiro argumento é a data que queremos formatar, o segundo é o formato (token) que queremos que tenha a data, e o terceiro argumento é um objeto que serve para modificar a formatação da data. Nota: para colocar a data em outro idioma (por default está em inglês) é necessário usar um "require" no Nodejs.
- **distanceInWords** --> retorna uma string que representa a distancia entre as datas que ele recebe como argumento. Pode receber três argumentos (dois obrigatórios e um opcional).

Segue exemplo de uso dos métodos anteriores:
```js
const present = new Date();

console.log(present);              // Thu Jun 29 2023 21:39:39 GMT-0300 (Horário Padrão de Brasília)

//saber se uma data corresponde a data atual usando o método "isToday"
console.log(dateFns.isToday(present))     // true

//formatar datas usando o método "format". Para saber mas sobre os tokens (o segundo argumento que passamos para o método) podemos ver a documentação do método format no site da Date-fns:
console.log(dateFns.format(present, 'MMMM'));      // June
console.log(dateFns.format(present, 'YYYY'));      // 2023
console.log(dateFns.format(present, 'dddd'));      // Thursday
console.log(dateFns.format(present, 'Do'));      // 29th

console.log(dateFns.format(present, 'DD/MM/YYYY'));      // 9/06/2023

//comparar dos datas usando o método "distanceInWords"
const past = new Date('April 7 2015 17:30:00');

const diference = dateFns.distanceInWords(present, past);

console.log(diference);      // about 8 years

//para colocar a palavra 'ago' no final da resposta anterior, podemos usar um sufixo como terceiro argumento na invocação do método da seguinte forma:
const diference = dateFns.distanceInWords(present, past, {addSuffix: true})

console.log(diference)      // about 8 years ago
```
Para encontrar mais métodos podemos usar a documentação oficial da lib date-fns no seguinte link:
https://date-fns.org/docs/Getting-Started

**Comment by MivlaM** [comment]
Boa @OnielStgo rumo à fluência! 🔥
