### ISSUE TITLE
Etapa  1, Correção dos exercícios da aula 03 - Aula 04-01

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#728]
### Professor na correção da atividade a seguir:

11 - Comente o console.log acima e:

- Declare uma const "dessert" e faça com que ela receba uma template  
string que contém a parte "co" do 1º item do array "dogNames", a  
parte "ca" do 2º item e a parte "na" do 4º item;
- A string deve resultar na palavra 'cocana', que não deve ser  
digitada diretamente;
- No final da string, faça com que a letra "n" seja substituída por  
"d", utilizando o método adequado para isso;
- Exiba no console a string abaixo, substituindo "SOBREMESA" pela  
constante que você criou.

'A SOBREMESA é um doce à base de coco, tradicional na América Latina e em Angola.'
*/

```
const dessert = `${dogNames[0].slice(3)}${dogNames[1].slice(2)}${dogNames[3].slice(2)}`.replace('n', 'd')
```
#### Por quê colocar o assim?
```
${dogNames[3].slice(2)}`.replace('n', 'd')
```

#### E não  assim?
```
${dogNames[3].slice(2).replace('n', 'd')}`
```
Essa segunda forma foi a que fiz e deu certo também.
**Desculpe se a pergunta é boba!!**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Nikson.

A pergunta não é boba, o que não pode é você ficar com dúvidas. Então pergunte sempre que precisar =)

O que muda na real é um pouco de como o código será lido, mas nesse caso tanto faz, por que a expressão `arr[index].slice(index)` sempre irá retornar uma string, independente se está ou não dentro de uma interpolação de uma template string, e o `replace` é um método de string. Então o resultado nos dois casos é o mesmo:

```javascript
const arr = ['alô', 'oi', 'olá']

console.log(`${arr[1].slice(0)}`.replace('i', 'e')) // oe
console.log(`${arr[1].slice(0).replace('i', 'e')}`) // oe
```

Respondi sua dúvida?

@NiksonDiniz

**Comment by NiksonDiniz** [comment]
Opa obrigado pela atenção.
Dúvida respondida!
