### ISSUE TITLE
Etapa 05 - O Document Object Model - DOM, Correção dos exercícios da aula passada - Aula 02-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#73]
Roger estou com uma duvida de estagiário,
e que você explica tão bem, que vou recorrer a você. 

No exercício a baixo, você falou do callback no method find,
Aí vem a duvida, sempre ouço falar de callback e fico com uma puga
atrás da orelha. 
Um callcack é uma função anônima dentro de outra invocada?  

/*
  05

  - Encontre no array abaixo o cão com o nome "Zequinha" e exiba esse objeto  
    no console;

  Dica: procure pelo método find, no MDN.
*/

```js

const dogs = [
  { name: 'Olivia', age: 3, gender: 'Female', breed: 'Maltês' },
  { name: 'Zé', age: 2, gender: 'Male', breed: 'Pug' },
  { name: 'Jade', age: 4, gender: 'Female', breed: 'Shiba inu' },
  { name: 'Zequinha', age: 7, gender: 'Male', breed: 'Poodle' },
  { name: 'Xica', age: 6, gender: 'Female', breed: 'Chihuahua' }
]

const zequinha = dogs.find(dog => dog.name === 'Zequinha')

console.log(zequinha)

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo. Não existe dúvida de estagiário. A única dúvida que existe é a que você precisa esclarecer =)

> Um callback é uma função anônima dentro de outra invocada?  

Um callback é uma função inserida como argumento da invocação de outra função. Apenas isso.

```javascript
const zequinha = dogs.find(dog => dog.name === 'Zequinha')
```

No código acima, a invocação do `find` recebeu como argumento a função de callback `dog => dog.name === 'Zequinha'`.

Uma função de callback pode ou não ser anônima. A função de callback do código acima é anônima, pois ela não foi atribuída a uma `const`.

Mas se eu atribuir essa função a uma `const` e apenas referenciar ela na invocação do `find`,

```javascript
const getZequinha = dog => dog.name === 'Zequinha'
const zequinha = dogs.find(getZequinha)
```

ela continua sendo uma função de callback, mas agora, nomeada. Sacou a ideia?

**Comment by naldowebdeveloper** [comment]
Roger entendi perfeitamente.
valeu mesmo...vou parar mais de ter medo de errar.
obrigado amigo

**Comment by Roger-Melo** [comment]
Show, Ednaldo! Várias dúvidas surgirão em sua trajetória rumo à fluência. Conte comigo para te ajudar.

Vou fechar a issue por agora, mas se rolar outra dúvida, é só abrir uma nova =)
