### ISSUE TITLE
Etapa 4, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by marcosyoggy** [roger-melo-treinamentos/curso-de-js-roger-melo#730]
Roger eu colei abaixo a tela da minha resolução do exercício nº 3, será um bug no VSCODE?
**NA: O array está diferente pois tinha refeito o exercício e testei aumentando o nº de itens.

![image](https://user-images.githubusercontent.com/44072541/119675232-3c48eb80-be13-11eb-9385-6742a7137877.png)
![image](https://user-images.githubusercontent.com/44072541/119675710-a9f51780-be13-11eb-8bcb-b533f5ac4d9f.png)

  Quando percebi que o código funcionou sem o 'this', eu abri o MDN no atigo sobre 'This' e colei o primeiro exemplo abaixo  dos exercícios e funcionou, mostrando um erro quando retirei o 'this' do código;
  Tem mais uma coisa...percebi que tenho um hábito de colocar console.log dentro da function/method e minha interpretação dos enunciados ainda está abaixo do aceitável..na minha percepção...mesmo assim, ainda consigo chegar ao mesmo resultado em 80% das resoluções, mas não quer dizer muita coisa..."..chegar no destino, dando 10 voltas em torno do local e ainda ter que refazer o trajeto ...". Obrigado Roger.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @marcosyoggy, vc pode postar o código do exercício? Assim fica mais fácil eu testar aqui em minha máquina e te ajudar =)

**Comment by marcosyoggy** [comment]
````js
console.log("_______________Exrecício 03____________________________")

let car = {
  name: 'Deloren',
  brand: 'DMC',
  colors: ['silver','black','ice','Bronx','yellow','Jasmin'],

  isRunning (carState) {
    if(carState == true) car.run()
    else { car.stop()}
  },

  run () {
    console.log(`O ${car.name} está em movimento.`)
  },

  stop () {
    console.log(`O ${car.name} está parado.`)
  },

  getColorsMessage () {
    console.log(`O ${car.name} está disponível nas cores ${car.colors[0]} , ${car.colors[1]} e ${car.colors[2]}.`)
  }
}
console.log(car)

console.log("_______________Exrecício 04____________________________")
car.isRunning(1)

/*
  05

  - Faça o carro parar e exiba no console se ele realmente está parado.
*/
console.log("_______________Exrecício 05____________________________")
car.isRunning(0)


/*
  06

  - Exiba, no console, a mensagem com as cores do carro.
*/
console.log("_______________Exrecício 06____________________________")
car.getColorsMessage()

/*
  07

  - Exiba, no console, a mensagem "O carro é um MARCA_DO_CARRO NOME_DO_CARRO";
  - Utilize a notação de colchetes para acessar as propriedades do carro.
*/
console.log("_______________Exrecício 07____________________________")
console.log(`O carro é um ${car['brand']} ${car['name']}`)
````

**Comment by Roger-Melo** [comment]
> será um bug no VSCODE?

O que você achou que é um bug? Não entendi.

> Quando percebi que o código funcionou sem o 'this', eu abri o MDN no atigo sobre 'This' e colei o primeiro exemplo abaixo dos exercícios e funcionou, mostrando um erro quando retirei o 'this' do código;

O que o erro exibido dizia?

---

Sobre usar o nome do objeto ao invés do `this`, é possível mas não-recomendado. 

Isso e um assunto mais avançado que você entenderá no decorrer do treinamento e na etapa 14. 

Mas apenas para não ficar muito vago... no código abaixo, `user2` é um objeto que acessa propriedades e métodos do objeto `user`:

```javascript
const user = {
  name: 'abc',
  showName () {
    console.log(this.name)
  }
}

let user2 = Object.create(user)

user2.showName() // 'abc'
user2.name = 'def'
user2.showName() // 'def'
```

Quando a primeira invocação de `showName` é encadeada em `user2`, `'abc'` é exibida no console e, após a modificação de valor da propriedade `name`, a segunda invocação de `showName` encadeada em `user2` exibe no console `'def'`, que é o novo valor que `name` recebeu, certo?

Agora, observe os valores exibidos se eu substituir o `this` pelo nome do objeto:

```javascript
const user = {
  name: 'abc',
  showName () {
    console.log(user.name)
  }
}

let user2 = Object.create(user)

user2.showName() // 'abc'
user2.name = 'def'
user2.showName() // 'abc'
```

Agora, mesmo que `'def'` seja atribuído para a propriedade `name` de `user2`, como dentro do `showName` o console.log está exibindo o valor da propriedade `name` de `user`, a invocação de `user2.showName()` sempre exibirá o valor dessa propriedade `name` de `user`.

Então usar o `this` ao invés do nome do objeto é importante por que o `this` irá referenciar o objeto no qual a invocação do método `showName` foi encadeada.

Mas novamente, você não precisa entender isso à fundo agora. Até chegar na etapa 14 (e durante ela) você terá visto muito sobre o `this`, conhecerá `Object.create` e prototypes. Minha recomendação, por enquanto, é apenas que não substitua o `this` pelo nome do objeto =)

Ficou mais claro?

@marcosyoggy

**Comment by marcosyoggy** [comment]
Lendo o exemplo que você enviou, lembrei da aula 'Tipos de Referência x Tipos Primitivos' , sem usar o 'this' é como se perdesse a referência do local da propriedade user.name e não é possível realizar a reatribuição de valor....Então(...até pra  falar besteira tem que ter um pouco de coragem...rsrsrsrs.), 'this' age como um ponteiro interno dentro do método? Obrigado, Roger.

**Comment by Roger-Melo** [comment]
Não tem que ter medo de "falar besteira". Nada é tão pedagógico quanto errar.

O `this` sempre referencia um objeto. 

Esse objeto pode mudar dependendo do tipo de função no qual o `this` está inserido ou de como a função é invocada. Mas isso vai ficar mais claro no decorrer do treinamento =)

@marcosyoggy

**Comment by marcosyoggy** [comment]
Lembrei das referencias e esqueci do 'this', mensagem entendida..."Vamo usar o menino..então!!...". Obrigado Roger, pode fechar.

**Comment by Roger-Melo** [comment]
Tranquilo.

Conforme for avançando nas aulas você vai aprender a usar o `this`, e depois vai aprender como evitá-lo xD

Vou fechar e no que precisar, estamos às ordens =)

@marcosyoggy
