### ISSUE TITLE
Duvida no exercício 012 

### ISSUE THREAD

**Issue by viniciusnunhez27** [roger-melo-treinamentos/curso-de-js-roger-melo#7303]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 03 da etapa 04 - Aula 01-01

### Link da aula

https://app.nutror.com/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/842107

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

No execicio 012 - 

- No objeto abaixo, implemente um método que exibe a seguinte mensagem no 
    console:

    Vídeos recentes de Roger Melo:
    Introdução ao TDD - Parte 02 | JavaScript | Jest
    Introdução ao TDD | JavaScript | Jest
    Higher-order Functions | JavaScript
  
  - As 4 linhas da mensagem, podem ser exibidas **separadamente.**
  
```js 
const youtubeUser = {
  name: 'Roger Melo',
  chanelUrl: 'https://www.youtube.com/channel/UCmjDevp9Y8r-qi-xueD3Izg',
  videos: {
    total: 111,
    recentVideos: [
      { title: 'Introdução ao TDD - Parte 02 | JavaScript | Jest', length: '28:28' },
      { title: 'Introdução ao TDD | JavaScript | Jest', length: '19:29' },
      { title: 'Higher-order Functions | JavaScript', length: '47:38' }
    ]
  },

  about: {
    description: '🔥 Ensino as pessoas a alcançarem a fluência em JavaScript! 🔥',
    socialNetworks: {
      twitter: 'https://twitter.com/rogermelodev',
      gitHub: 'https://github.com/Roger-Melo'
    },
    country: 'Brasil'
  },
  getRecentVideos() {
    console.log(`Videos recentes de  ${this.name} `)

    this.videos.recentVideos.forEach( video => {
       console.log(video.title)
    })
  }
}

```

 Minha Duvida é a seguinte:  
 
-Sempre que eu quiser manipular o objeto ou filtar um informação é necessário criar um nova função ? Exemplo da resolução do exercicio. 

```js

 getRecentVideos() {
    console.log(`Videos recentes de  ${this.name} `)

    this.videos.recentVideos.forEach( video => {
       console.log(video.title)
    })
  }
  
```
Não poderia fazer um forEach direto  dentro do objeto sem precisar criar a função (?

( pergunto pois fiquei meio perdido nesta questão ) .

Desde já agradeço a atenção. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @viniciusnunhez27! 

> Sempre que eu quiser manipular o objeto ou filtar um informação é necessário criar um nova função?

Não necessariamente. Vão ter casos em que você irá decidir se quer usar função ou não. Mas esse tipo de feeling vc só vai perceber conforme for praticando e avançando no CJRM =)

---

> Não poderia fazer um forEach direto dentro do objeto sem precisar criar a função?

O forEach é um método de array. Isso significa que a invocação dele precisa estar encadeada em um array (`seuArray.forEach()`).

O exercício pediu para fazer desta forma pq vc está em uma etapa em que o this está sendo apresentado, então vc precisa treinar este conceito.

Mais à frente, conforme for avançando, vc verá outras formas de resolver este tipo de problema. Tudo bem? =)

**Comment by viniciusnunhez27** [comment]
Tudo bem.

Obrigado pela explicação.

Em seg., 3 de jul. de 2023 às 18:05, Roger Melo ***@***.***>
escreveu:
