### ISSUE TITLE
Duvida na hora de lancar os erros (conversor de moedas)

### ISSUE THREAD

**Issue by gabriel-valino** [roger-melo-treinamentos/curso-de-js-roger-melo#7304]
### Etapa da aula

14

### Nome da aula

Correção dos exercícios da aula 03 da etapa 14 - Aula 01-07

### Link da aula

https://app.nutror.com/curso/6b300556444e6ff43f4a78991d84996d17c050a9/aula/6706879

Estou tendo problema na hora de lancar o erro "unsupported-code": "A moeda não é suportada no nosso banco de dados.", visto que, modifiquei a moeda da Url para uma moeda que nao existe:  "...c495a286/latest/**aaaa**"
Entretanto, o erro que esta aparencendo na div é o "Sua conexão falhou. Não foi possível obter as informações"

Nao era pra estar sendo  lancado o Error "unsupported-code", como mostrado na resolucao?  

codigo: 
```js
const currenciesEl = document.querySelector('[data-js="currencies-container"]')
const url = "https://v6.exchangerate-api.com/v6/20bd9bbccb3cd31ac495a286/latest/aaaa"

const getErrorMessage = errorType => ({
  "unsupported-code": "A moeda não é suportada no nosso banco de dados.",
  "malformed-request": "Quando alguma parte do seu pedido não segue a estrutura mostrada acima.",
  "invalid-key": "A chave da API não é válida.",
  "inactive-account": "Seu endereço de e-mail não foi confirmado.",
  "quota-reached": "Sua conta atingiu o limite de solicitações permitido pelo seu plano."
})[errorType]

const fetchData = async() =>{
  try{
    const response = await fetch(url)

    if(!response.ok){
      throw new Error("Sua conexão falhou. Não foi possível obter as informações")
    }

    const exchangeRateDate = await response.json()

    if(exchangeRateDate.result === "error"){
      throw new Error(getErrorMessage(exchangeRateDate['error-type']))
    }
    
    }catch(err){
      const div = document.createElement("div")
      const button = document.createElement("button")

      div.textContent = err.message

      div.classList.add("alert","alert-warning", "alert-dismissible","fade", "show")
      div.setAttribute("role","alert")
      button.classList.add("btn-close")
      button.setAttribute("type","button")
      button.setAttribute("aria-label","Close")

      div.appendChild(button)
      currenciesEl.insertAdjacentElement('afterend', div)
    }
}

fetchData()


<!-- Não apague daqui para baixo! -->
@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @gabriel-valino!

Dê uma olhada se, ao testar este caso inesperado, todos os valores que vc está esperando realmente são os que estão chegando. Isto é, coloque um console.log abaixo de `response`. Depois, outro console.log verificando o valor de response.ok. 

Se quando uma moeda inválida for enviada para a API ela responde com .ok resultando em false, o primeiro if será executado e o throw será lançado. Saca?

**Comment by gabriel-valino** [comment]
Boa noite, mestre!!! tudo certo?

É isso mesmo que está acontecendo, o response.ok está resultando em false e o primeiro if está sendo executado. Entao o comportamento esperando era que ele retorna-se true certo?

Na sua resolução voce altera o final da url, assim como eu fiz, mas o response.ok continua retornando true. Nao entendi pq o meu codigo nao retorna true tb

**Comment by gabriel-valino** [comment]
muito obg @MivlaM e @Roger-Melo, era isso mesmo! duvida esclarecida apos ver essa issue

**Comment by MivlaM** [comment]
Ok! Vou fechar a issue aqui, qualquer coisa, sinta-se livre para abrir uma nova.
