### ISSUE TITLE
Correção dos exercícios da aula 04 da etapa 11 - Aula 05-01

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#7307]
### Etapa da aula

11

### Nome da aula

A fetch API - Aula 05-03

### Link da aula

https://app.nutror.com/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6371024

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

> Essa dúvida não é sobre essa aula mas sim sobre o Destructuring assignment, estou me aventurando estudando como acessar as propriedades dos retornos das APIS.

Queria entender melhor como faço para ir descendo nas chaves e retornar os valores dela, exemplo:

O retorno que tenho da API PlaceHolder e esse aqui:

![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/60947491/efff78cc-5a48-4da3-8538-662d366eb768)

Quero acessar address e pegar o valor  city, acessar  geo e pegar os valores de LAT E LNG.

Usei o ChatGPT para me ajudar a entender como eu podia fazer isso e depois dei uma lida da DOC na MDN, esse foi o resultado.

```js
const url = `https://jsonplaceholder.typicode.com/users/`

const getPlaceHolder = async url => {
  try {
    const getUsers = await fetch(url)
    const getUser = await getUsers.json()

    getUser.map( user => {
      const { address: { city }, address: { geo: { lat, lng } } }= user 
      console.log(`City: ${city}\n Geolocalizacao:\n   Latitude:${lat}\n   Longitude:${lng}`)
    } )

  } catch(error){
    console.log(error)
  }
}

getPlaceHolder(url)
```

> Esse foi o meu entendimento, me ajude se eu estiver errado por favor.

Para acessar os valores de address e geo preciso:

01 - Desempacotar a propriedade denominada *address*

```js
const { address: { city }
```

02 - Desempacotar a propriedade denominada *address* novamente  e depois mais uma vez para descer até o nível de acesso a geo e por fim finalmente  desempacotar *lat* e *lng*

```js
const { address: { city }, address: { geo: { lat, lng } } }
```

O acesso principal tem sempre que partir do PAI(address) porque é ele que vai dar acesso ao segundo array filho(geo) concedendo acesso aos seus valores

Na minha mente é esse o esquema de acesso. Minha explicação faz sentido para você ?

![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/60947491/6250be05-dfd5-464a-afe6-5630d05bbbcf)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @dzpoke! Tudo bem?

Cara, isso funciona mas não é legível. 

Acho que vc ainda irá chegar no ponto em que eu recomendo não aninhar expresões de destructuring. 

Ao invés de fazer aninhamento de destructuring, vc pode usar a sintaxe `obj.propriedade` para obter o valor da propriedade aninhada e armazenar toda a expressão em uma const. O código fica mais simples e legível =)
