### ISSUE TITLE
Resumo da Aula 02/05 da etapa 01

### ISSUE THREAD

**Issue by bivar37** [roger-melo-treinamentos/curso-de-js-roger-melo#731]
Numbers

 Ao usar números usa-se  (.) ponto e não vírgulas em Js 
Ex : 9.9 e não 9,0.
Pode usar todos operadores aritméticos 
(-)Subtração, (+) Adição, (/)Divisão, (*)  Multiplicação,(%) resto da divisão.
Nota: O **_%_** é chamado de modulo.

Num cálculo no JS segue precedências entre operadores, similar à matemática:
1 parênteses
2 expoente ou  raiz
 Ex. 3** 2
3 multiplicação, divisão
4 adição e subtração. 

**Operadores de incremento e decremento**

 _Incremento:_
Ao acrescentar ++ numa let já declarada. a let aumenta +1
```
let silver = 37
silver++
console.log(silver) 
// 38
```
 _Decremento:_
Ao acrescentar -- numa let já declarada. a let subtrai 
```
let silver = 37
silver--
console.log(silver) 
// 36
```

 **_Operadores Assignments_**
Adiciona, subtrai, divide e multiplica valores maiores que 1.

_Adcionando_ (Addition)
```
let silver = 40
silver += 5
console.log( silver) 
//45
```

_Subtraindo_ (Subtraction)
```
let silver = 40
silver -= 5
console.log( silver)
 //35
```
_Mutiplicando_ (Mutiplication)
```
let silver = 40
silver *= 5
console.log( silver)
 //200
```
_Dividindo_ (Division)
```
let silver = 40
silver /= 5
console.log( silver) 
//8
```
**_NaN (Não um é Numero)_**
 Aparece no resultado quando é feita uma operação sem sentido, tipo divisão um number  + uma string.
Ex
```
console.log (40 / 'Bivar')
//NaN
```
**_Concatenação de Number e String._**

Vamos ver no próximo resumo, pois aí já vamos usar a forma nova.

Templates Strings!!

 até a próxima.

Bivar Dourado

__________________________________________________________________________________________

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @bivar37. Vamo que vamo, rumo à fluência! 🔥
