### ISSUE TITLE
Como saber o local correto da invocação de uma função?

### ISSUE THREAD

**Issue by phlopesprogrammer** [roger-melo-treinamentos/curso-de-js-roger-melo#7312]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6370935

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa tarde. 
As vezes tenho dúvidas em relação a colchetes , quando têm muitos.  Fico com dificuldade de entender onde fazer a execução corretamente.
exemplo :   }
    extraInternal( )
  }
  internal( )
}

external1( )

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @phlopesprogrammer! Baixe [estes vídeos](https://drive.google.com/drive/folders/1JgDhalhdcVPlqlDe3fI9VKg45AhxLkym?usp=sharing) para a sua máquina e siga o que foi recomendado neles. Fico no aguardo =)

**Comment by phlopesprogrammer** [comment]
Obrigado e desculpe o inconveniente. 
Abri outra issue de forma correta.
