### ISSUE TITLE
Exibição de informações com Promisses

### ISSUE THREAD

**Issue by dzpoke** [roger-melo-treinamentos/curso-de-js-roger-melo#7314]
### Etapa da aula

11

### Nome da aula

Introdução a promises - Aula 04-03

### Link da aula

https://app.nutror.com/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6371020

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Professor, estou voltando algumas aulas para tirar as dúvidas restantes que ainda tenho nesse módulo, 

> Isso aqui é somente para fins de curiosidade

Eu ainda tenho um pouco de dúvida sobre as Promisses mas depois de tirar uns dias para descansar a cabeça agora que voltei parece que tu faz mais sentido que antes, muito louco kk

A minha dúvida é a seguinte, apesar de termos uma maneira mais moderna de fazer requisições com fetch eu queria saber como eu poderia recuperar as informações e exibir na tela usando Promisses.

Queria saber se da maneira que fiz abaixo seria a forma adequada para recuperar e exibir na tela

/*
  01 - Exercicio 31

  - Utilizando a fetch API, implemente uma função assíncrona que busca dados do 
    seu perfil de usuário no GitHub, através do seguinte endpoint:
    - https://api.github.com/users/SEU_NOME_DE_USUARIO_NO_GITHUB
  - Implemente uma segunda função que exibe, no console, seus dados de usuário 
    do GitHub.
*/

```js
const gitName = document.querySelector('.gitName')
const gitLocation = document.querySelector('.gitLocation')
const gitBio = document.querySelector('.gitBio')
const gitURL = document.querySelector('.gitURL')


const getUsers = url => new Promise(( resolve, reject) => {
  const request = new XMLHttpRequest

  request.addEventListener('readystatechange', () => {
    const isResquestOK = request.readyState === 4 && request.status === 200
    const isResquestNotOK = request.readyState === 4

    if(isResquestOK) {
      const data = JSON.parse(request.responseText)
      resolve(data)
    } 

    if(isResquestNotOK) {
      reject ('Erro aqui!')
    }
  })

  request.open('GET', url)
  request.send()
})

getUsers(`https://api.github.com/users/dzpoke`)
  .then(dzpoke => {
    const teste = dzpoke
    const {name, location, bio, url} = teste

    gitName.innerHTML = name
    gitLocation.innerHTML = location
    gitBio.innerHTML = bio
    gitURL.innerHTML = url
  })
  .catch(erro => console.log(`${erro}`))

```

![image](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/assets/60947491/ccbef56a-52fc-45e5-8bce-e7ab1c21b17d)

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @dzpoke 

> ## Queria saber se da maneira que fiz abaixo seria a forma adequada para recuperar e exibir na tela

O código que você escreveu acima, nas condições que você se propôs a executá-lo, está muito legível e claro em relação ao que está fazendo. Não achei nenhum dos trechos difícil de entender, qualquer outra refatoração nos trechos acima, na minha opinião, poderia complicar um pouco o entendimento. Além disso, você também conseguiu concluir bem o objetivo que é o de recuperar as informações e exibi-las na tela. Parabéns =)

**Comment by dzpoke** [comment]
vlw @MivlaM
