### ISSUE TITLE
Aplicação: QUIZ

### ISSUE THREAD

**Issue by renarfreitas** [roger-melo-treinamentos/curso-de-js-roger-melo#732]
- O link da sua versão do quiz:
  link: https://github.com/renarfreitas/CJRM

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
  
 1 - Duvidas na escolha do tema, acabei ficando com uma simples implementação css;
 2 - Organização com a identação do código html;
 3 - Por falta de prática e costume tive que rever aulas de CSS3, por já haver esquecido de como implementa-lo no código

  Não imaginei que uma aplicação aparentemente simples, seria tão difícil de implementar, grande 
  contradição, na verdade, por parte do meu nervosismo de ser avaliado, acabou deixando as coisas mais simples, um  trabalho hercúleo.

- Quais foram as suas menores dificuldades durante a execução desse exercício:
  O código em js não foi muito complicado, como havia acompanhado o quiz da primeira aula, foi um tanto tranquilo   seguir o caminho.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @renarfreitas.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá Renar.

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica da aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser exibido por padrão como "marcado".

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

### Local da pontuação na tela (mobile)

Talvez, depois de você hospedar o quiz no Netlify (como orientado no exercício 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela.:

![image](https://user-images.githubusercontent.com/29297788/119900565-13138280-bf1b-11eb-9a73-0b8c5119f074.png)

Então uma alternativa seria inserir o parágrafo acima do botão. 

Nas aulas seguintes eu mostro uma forma de implementar a pontuação =)

## Organização de código

### Nomes de variáveis e funções

`corretcAnswers`, `answares` e `answare` não estão com a ortografia correta. Renomeie-as como `correctAnswers`, `answer` e `answers`. Para não ficar na dúvida, você pode consultar o google tradutor quando precisar.

`bragging` é um nome de função não muito descritivo. Como essa função lida com o que vai acontecer quando o form é enviado (e várias ações diferentes acontecem dentro dela), você pode nomeá-la como `handleFormSubmit` ao algo parecido.

Ao invés de `iteratingComparingAdding`, prefira sintetizar o que a função faz. No fim das contas, essa função existe para calcular a pontuação. Então ela pode ser nomeada como `calculateScore` ou `calculateUserScore`.

A `const` que armazena o parágrafo da pontuação pode ter um nome mais descritivo. Ao invés de `p` ela pode se chamar `scoreContainer`, por exemplo.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem começar com `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

## Lógica

Já que uma classe `'score'` é inserida no `p`, a declaração dessa classe no arquivo .css pode conter a cor do parágrafo e a atribuição `p.style.color = 'red'` pode ser removida do app.js.

---

Uma observação sobre as perguntas: o JavaScript não foi concebido para rodar no servidor, como descreve a primeira pergunta do quiz. [Aqui](https://pt.wikipedia.org/wiki/JavaScript#Hist%C3%B3ria) vc pode ter mais informações sobre o nascimento da linguagem =)

---

No mais, é isso. Parabéns novamente pelo esforço em construir a primeira aplicação do treinamento =)

As observações acima fizeram sentido?

@renarfreitas

**Comment by renarfreitas** [comment]
Maravilha professor!! Estou muito agradecido pela atenção, e  com toda
certeza, as observações fazem sentido.
Irei refazer todo o quiz e implementar as correções a partir das
observações pontuadas.

Muito Obrigado.

**Comment by Roger-Melo** [comment]
Show @renarfreitas. No que precisar, estou à disposição =)
