### ISSUE TITLE
funções

### ISSUE THREAD

**Issue by Andre7973** [roger-melo-treinamentos/curso-de-js-roger-melo#7332]
### Etapa da aula

1

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991207

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Andre7973 

Aconteceu um problema na formatação da sua issue na hora de postar o código. Então, acredito que seja melhor resolvermos essa questão da formatação primeiro, para depois te ajudar com a sua dúvida em relação às funções. 

Eu recomendo que você assista estes [vídeos](https://drive.google.com/drive/folders/1JgDhalhdcVPlqlDe3fI9VKg45AhxLkym) e depois, abra uma nova issue seguindo o passo a passo e as recomendações mostradas nos vídeos.

Se ficou alguma dúvida em relação a isso, pode comentar aqui embaixo que vou te ajudar =)
