### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by guilepereira** [roger-melo-treinamentos/curso-de-js-roger-melo#7336]
# Outras maneiras de fazer queries no DOM - Aula 01-08

## Selecionando pelo atributo id | getElementById( )
Este é um método alternativo ao querySelector, em que o argumento que receberá para a seleçeção do elemento será uma string contendo o id, sem hash;
```html
<h1 id='title'>Titulo</h1>
```
```js
const title = document.getElementById('title')
console.log(title)
// <h1 id="title">Outras maneiras de fazer queries no DOM</h1>
```

<br />

## Selecionando pelo atribuito classe | getElementsByClassName( )
Este método também é uma alternativa ao querySelector, em que tem foco na seleção de um ou mais elementos que possuam a classe passada como argumento ao método;
```html
<h1 class='title'>Titulo</h1>
```
```js
const title = document.getElementsByClassName('title')
console.log(title)
// <h1 class='title'>Outras maneiras de fazer queries no DOM</h1>
```
### HTMLCollection
- Este método poderá retornar mais de um elemento, e no caso de mais de um elemento escontrado, será retornado um HTMLCollection, que é similar ao nodeList de querySelector, e que contém os elementos encontrados com a classe especificada;
- Ao contrário do nodeList e de arrays, o HTMLCollection não permite iteração por forEach, e possui uma lista restrita de métodos aplicáveis;

<br />

## Selecionando pela tag | getElementsByTagName( )
- Assim como os dois métodos anteriores, este busca elementos por sua tag HTML, possibilitando o retorno de um ou mais elementos correspondente à string passada como argumento;
- Assim como os metodos anteriores, getElementsByTagName também retorna um HTMLCollection;

```html
  <div>
    <h1>Hello World!</h1>
    <p>Conteúdo descritivo da página</p>
    <p class="error">Essa é uma mensagem de erro</p>
  </div>
```
```js
const paragraphs = document.getElementsByTagName('p')
// <p>Conteúdo descritivo da página</p>
// <p class="error">Essa é uma mensagem de erro</p>
```

<br />

## Vantagens de usar querySelector e querySelectorAll
- Ambos os métodos permitem selecionar por diversos tipos de elementos (tags, classes, ids, seletores CSS etc);
- querySelectorAll retorna um nodeList, que possui mais possibilidades de acesso e manipulação do agrupamento de elementos retornado;

<br />

----

<br />

# MDN | getElementById, getElementsByClassName e getElementsByTagName

## getElementById
- Este método de document retorna o elemento que contém a id que corresponde à string passada como argumento;
- Devida a natureza dos ids, de serem elementos únicos no código, o método retornará apenas um elemento, o que justifica o nome do método ser o único no singular;
- Em caso de ids duplicados, o método getElementById retornará apenas o primeiro elemento encontrado;
- Este método é exclusivo do objeto document, visto que ids são únicos em todo o documento, não há necessidade de versões locais;
- O parâmetro diferencia maúsculas de minusculas e este detalhe pode resultar em falha na busca de um elemento divergente do esperado, e neste caso, retornará null;

<br />

## getElementsByClassName
- Este método de document retorna um conjunto de elementos que correspondem com a classe ou as classes passadas como argumento;
- O conjunto retornado é um HTMLCollector, que se assemelha ao nodeList, porém com restrições de acesso e iterações por métodos como forEach e etc;
- Seu parâmetro pode receber apenas um argumento (classe), porém irá retornar até mesmo elementos que possuam mais de uma classe ou até mesmo é possível passar a combinação de duas classes como argumento, retornando de maneira específica todos os elementos que possuem as referidas classes;

```html
<div>
  <h3 class="green title">Hello World!</h3>
  <p class="green">Oi</p>
  <p class="green error">Essa é uma mensagem de erro</p>
</div>
```
```js
const green = document.getElementsByClassName('green')
// HTMLCollection(3) [h3.green.title, p.green, p.green.error]
// 0: h3.green.title
// 1: p.green
// 2: p.green.error
// length: 3
// [[Prototype]]
```

<br />

## getElementsByTagName
- Este método retorna um HTMLCollection do tipo live, buscando todas as tags correspondentes a tag especificada como argumento e caso haja alterações na estrutura DOM, este HTMLCollection se atualiza sem que seja necessário chama-lo novamente;

<br />

### Encadeando buscas
- É possível encadear buscas, de maneira a especificar dentro de qual conjunto de elementos o elemento será buscado;
```js
document.getElementById("main").getElementsByClassName("test");
```

### Especificando elemento do conjunto no momento da busca
- Por meio de notação de colchetes é possível indicar qual elemento do HTMLCollector a busca deverá retornar;
```js
document.getElementsByClassName("test")[0];
```

<br />

-------

<br />

**Referências**

[MDN - getElementById](https://developer.mozilla.org/pt-BR/docs/Web/API/Document/getElementById)

[MDN - getElementsByClassName](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName)

[MDN - getElementsByTagName](https://developer.mozilla.org/pt-BR/docs/Web/API/document/getElementsByTagName)

**Comment by MivlaM** [comment]
Excelente @guilepereira rumo à fluência! 🎯
