### ISSUE TITLE
Como saber o local correto da invocação de uma função? 

### ISSUE THREAD

**Issue by phlopesprogrammer** [roger-melo-treinamentos/curso-de-js-roger-melo#7337]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/curso/b76b47ec3eb42bd6b6cca5dab541deb83e7c160b/aula/6370935

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa noite Roger. 
Desculpe pelo erro cometido na issue , agradeço pela sua disposição em me ajudar. 

Sobre a dúvida : 
As vezes tenho dificuldade de entender a ordem do código , qual local correto executar uma função, pelo fato de ter vários colchetes,parênteses . O que preciso fazer para melhorar na intepretação ? Como saber o local correto da invocação de uma função? 
```js
const external1 = () => {
const movie = 'Parasite'

  const internal = () => {
    const extraInternal = () => {
      console.log(movie.toUpperCase())
    }
    extraInternal()
  }
  internal()
}
external1()

Coloquei o código acima exemplificando a minha dúvida.
Desde já, muito obrigado.
```

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @phlopesprogrammer 

Meu nome é Maykell, faço parte da equipe de suporte na Roger Melo Treinamentos e vou te ajudar com sua dúvida =)

> ## Como saber o local correto da invocação de uma função?

Isso depende de quando e como você quer que o seu código se comporte. Para invocar uma função, você primeiro precisa declará-la, veja o exemplo abaixo:

```js
const funcaoTeste = () => {
  // ...
}
``` 

Na função acima, o que está após a abertura de chaves é o conteúdo inserido dentro do escopo da função, você pode colocar qualquer tipo de código que você deseja que a função seja responsável por executar. Após o fechamento de chaves, você vai poder invocar essa função.

Tendo esse princípio em mente, gostaria que focássemos um pouco no código que você postou na issue. Eu marquei por comentários onde começa a declaração de cada função:

```js
const external1 = () => { // A abertura de chaves da função external1 começa aqui e só termina na penúltima linha abaixo, portanto, você só pode invocá-la após essa linha.
const movie = 'Parasite'

  const internal = () => { // Aqui é declarado a abertura de chaves da função internal, o que estiver entre as chaves corresponde ao código dessa função.
    const extraInternal = () => { // Aqui começa o código correspondente a função extraInternal.
      console.log(movie.toUpperCase())
    } 
    extraInternal()
  } 
  internal()
} 
external1()
```
Futuramente você vai aprender sobre um conceito chamado escopos, mas no momento, quero que foque no que está sendo mostrado acima, essas funções tem o seu início delimitado pela abertura de chaves ` { ` e o seu final pelo fechamento de chaves ` } `. A identação é uma grande aliada nesse aspecto visual, pois ela nos ajuda a perceber onde começa e termina cada função.

> ## O que preciso fazer para melhorar na interpretação ?

A forma mais eficiente que eu conheço para interpretar a descrição de um desafio/exercício é ler toda a descrição e só então, dar um primeiro passo para resolver.

Um problema de cada vez.

Você também pode assistir a correção quando travar. Você tem a opção de ver toda a correção do exercício ou apenas até o ponto em que travou.

Se chegar ao ponto de não conseguir prosseguir por falta de entendimento de conceitos anteriores, volte, refaça, e peça ajuda aqui ou no grupo dos alunos no Telegram, geralmente lá no grupo de alunos a resposta vem mais rápido. Mas é só uma dica =)

Acredito que seja isso. Consegui responder suas dúvidas? Caso tenha ficado confuso alguma coisa ainda, sinta-se livre para comentar aqui embaixo que te ajudarei, ok?

**Comment by phlopesprogrammer** [comment]
Sim ,conseguir entender , obrigado.
