### ISSUE TITLE
Dúvida do exercício número 4

### ISSUE THREAD

**Issue by Polianeh** [roger-melo-treinamentos/curso-de-js-roger-melo#7340]
### Etapa da aula

3

### Nome da aula

Correção dos exercícios da aula 01 - Aula 02-01

### Link da aula

https://app.nutror.com/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/803284

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Na resolução deste exercício 04, eu não entendi porque usamos a "log" para apresentar os valores no console. Porque eu só consegui com utilizando o "console.log".

@Roger-Melo

**Comment by MivlaM** [comment]
Olá @Polianeh 

> ## Na resolução deste exercício 04, eu não entendi porque usamos a "log" para apresentar os valores no console. Porque eu só consegui com utilizando o "console.log".

No enunciado do exercício 03, é demandado que criemos uma função que exiba no console o valor recebido por parâmetro e que previna que o parâmetro dessa função receba `undefined`. Para isso, na correção em vídeo, o Roger criou uma função log:

```js
const log = function (value = 'Você deve passar um valor como argumento') {
  console.log(value)
}
```

Essa função `log` é que é invocada na hora da correção do exercício 04. Pode ter acontecido de você ter criado uma função com outro nome no exercício anterior, e por isso não ter associado ela com essa função `log` mostrada no vídeo. Mas de qualquer forma, se o seu código está funcionando perfeitamente como o exercício pediu, essa questão do nome da função é apenas um detalhe.

Consegui resolver a sua dúvida? Caso tenha restado alguma, sinta-se livre para comentar aqui abaixo que eu te ajudo =)
