### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#7342]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/adlagomes/todo-curso-cjrm_2023

### Maiores dificuldades durante a implementação

* Definitivamente não consegui remover as li usando dataset, tentei várias formas mas ou resultava em erros ou não funcionava como o esperado, mesmo não gerando erros. Nesse caso não apliquei o dataset. Simplesmente deixei o parentElement e refatorei o que consegui.

* Não sei refatorar código, tenho muita preguiça devido a dificuldade de destrinchar em partes menores aquilo que já está pronto e que muitas vezes me parece bom o suficiente e facilmente compreensível. Até consigo fazer alguma refatoração, mas dificilmente consigo pensar em tudo que posso deixar melhor.. 

* Me complico facilmente com o uso de callbacks, mas tentei usa-las o máximo possível para me acostumar.

### Menores dificuldades durante a implementação

* Adicionar uma nova li usando createElement ao invés de passar todo o html numa template literals foi algo que pensei desde a primeira criação do to-do list, então foi algo que eu desejei fazer, mas colocar o span e o icone da lixeira acabei passando sem criar esses elementos dentro da li com create, pensei que já havia diminuído o tamanho do conteúdo que inner.HTML receberia, então fiquei satisfeita com isso.
* Perceber a maioria das partes que eu poderia transformar em função foi fácil até, mas muitas que daria apenas uma linha me questionei e ainda me questiono se realmente era necessário criar uma função de uma linha apenas para separar "tarefas".
* O uso de toggle para adicionar ou remover uma classe na busca pelas li deu certo mas achei que poderia não funcionar, uma vez que primeiro tentei usar um ternário para adicionar ou não a classe, mas que acabou não funcionando e não avaliei muito bem o motivo.

**Comment by Roger-Melo** [comment]
Olá @adlagomes.

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @adlagomes!

Você pode baixar a análise de sua aplicação [neste link](https://drive.google.com/file/d/1TlSkmVsBpPXt0MmN1f-s0I03yOcobpPG/view?usp=sharing).

Se tiver qualquer dúvida, é só dar o toque =)

**Comment by Roger-Melo** [comment]
@adlagomes baixou o vídeo para a sua máquina?

**Comment by adlagomes** [comment]
Olá @Roger-Melo , eu baixei sim, obrigada. A sua avaliação foi de grande ajuda, sou super aberta a melhorias no código e a ideias sobre nomes e refatorações. Ainda não fiz a comparação entre o meu código e os ajustes que você fez, mas assim que possível farei isso. To andando devagar porque já tive pressa e minha base tá cheia de buracos, dessa vez quero me permitir demorar o tanto quanto necessário pra ter uma base bem firme e sólida. E mais uma vez, obrigada pelo feedback!

**Comment by Roger-Melo** [comment]
Boa! Fico no aguardo da próxima aplicação =D
