### ISSUE TITLE
Conflito de inicialização durante troca de valores entre variáveis usando destructuring assignment

### ISSUE THREAD

**Issue by guilepereira** [roger-melo-treinamentos/curso-de-js-roger-melo#7343]
### Etapa da aula

5

### Nome da aula

Correção dos exercícios da aula passada - Aula 02-01

### Link da aula

https://app.nutror.com/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991232

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Estava estudando a página do [MDN sobre Destructuring assignment ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) e no tópico **sobre troca de valores entre variáveis**, por meio de destructuring, ao testar e tentar formular um exemplo para minhas anotações, me deparei com um erro de inicialização de variável que não consegui encontrar uma solução sozinho;

Tentei usar uma estrutura similar ao exemplo funcional do MDN mas o erro acontece da mesma forma, a segunda variável é dada como não inicializada mas no exemplo do MDN funciona normalmente; "Uncaught ReferenceError: Cannot access 'comprador' before initialization"

### Exemplo funcional MDN
```js
let a = 1;
let b = 3;

[a, b] = [b, a];
console.log(a); // 3
console.log(b); // 1
```

### Minha tentativa
```js
let vendedor = 'produto'
let comprador = 'dinheiro'

[vendedor, comprador] = [comprador, vendedor]
console.log(vendedor, comprador)
// Uncaught ReferenceError: Cannot access 'comprador' before initialization
```

Tentei trocar os valores de string para numbers, tentei trocar let por var, mas sem sucesso em descobrir a origem do erro.
Pode ser que seja algum detalhe que veremos mais a frente no curso, porém fiquei curioso pra entender 🥵

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @guilepereira! Faça o download [deste vídeo](https://drive.google.com/file/d/10WbL0df5PZduIqxq86vWhe6gBdQIitAE/view?usp=sharing) para ver a resposta =)

**Comment by guilepereira** [comment]
Hey Roger, obrigado pela explicação!

Na verdade, a dúvida não é exatamente sobre a declaração das variáveis, mas sim sobre o uso de destructuring na inversão de valores entre duas variáveis, este é um dos exemplos que o MDN disponibiliza. Lembro que certa vez precisei fazer isso e demandou uma variável temporária pra armazenar um dos valores, e com destructuring isso não é necessário, porém, quando tentei seguindo o próprio exemplo do MDN, não funcionou. Vou tentar explicar um pouco melhor:

### Inversão de variáveis convencional
```js
let vendedor = 'produto';
let comprador = 'dinheiro';

let temp = vendedor;
vendedor = comprador;
comprador = temp;

console.log(vendedor, comprador);
// 
```

**Comment by guilepereira** [comment]
Hey Roger, muito obrigado pela explicação!

Acabei tentando novamente agora pela manhã e consegui resolver, não entendi o motivo do erro de inicialização anterior já que executei o mesmo código agora e funcionou, penso que possa ter sido algum bug no liveserver, todos os outros códigos executando normalmente até então mas não tive nenhum erro neste sentido :(

Na verdade, a dúvida era sobre o uso de destructuring na inversão de valores entre duas variáveis, este é um dos exemplos que o MDN disponibiliza. Lembro que certa vez precisei fazer isso e demandou uma variável temporária para armazenar um dos valores, e com destructuring isso não foi necessário, por isso meu interesse em descobrir como usar.

Apenas para registro, deixo abaixo os exemplos que usei!

### Inversão de variáveis convencional
```js
let vendedor = 'produto';
let comprador = 'dinheiro';

let temp = vendedor;
vendedor = comprador;
comprador = temp;

console.log(vendedor, comprador);
// dinheiro produto
```

### Inversão de variáveis com destructuring
```js
let vendedor = 'produto';
let comprador = 'dinheiro';

[vendedor, comprador] = [comprador, vendedor];

console.log(vendedor, comprador);
// dinheiro produto
```

De toda forma, muito obrigado pela ajuda! 😉⭐
