### ISSUE TITLE
Resumo da Aula Factory functions e composição de objetos - Aula 03-09 da etapa 14

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#736]
### Factory Function

É uma alternativa para criar e compor objetos. É uma função que não é uma classe; não é uma função construtora; não é um construtor, mas que retorna um novo objeto.

Em JavaScript qualquer função pode retornar um novo objeto. Porém a utilização de factory function me permite criar e compor objetos de uma forma simples, manutenível, flexível e testável.

Para declararmos um dado privado em uma classe utilizávamos a feature private field, mas para criar um dado privado em uma factory function basta atribuirmos ela a uma variável ou constante declarada dentro do escopo da função, pois ai esse valor só estará visível no escopo dessa função.

### Clousures

São criadas todas as vezes que uma função aninhada é criada a partir da invocação de uma função externa. É a combinação de uma função aninhada e seu escopo léxico. Ou seja, quando temos uma clousure a referência da variável declarada no escopo léxico há função aninhada é mantida em memória para que quando a função aninhada for invocada ela tenha acesso ao valor desta variável. 

```jsx
const external = () => {
	let score = 0
	
	const internal = () => {
		console.log(score)
	}
	
	return internal
}

const internal1 = external() // ƒ internal () {} -> ambiente léxico 1
const internal2 = external() // ƒ internal () {} -> ambiente léxico 2
```

Quando a **external** é invocada ela retorna a referência de uma função **internal** que armazena uma referência ao seu escopo léxico, ou seja, mantém a referência da **let score** viva na memória. Porém toda vez que a **internal** é retornada múltiplas vezes uma nova referência do seu escopo léxico é criado em uma posição diferente na memória, isso porque durante essa invocação uma nova clousure foi criada. Por isso quando a **external** é invocada pela segunda vez nenhum erro é disparado dizendo que uma **let score** já foi criada em memória, pois uma nova **let score** é criada nessa invocação e alocada em uma posição singular em memória. Ou seja, possuo 2 **let's score** com mesmo nome, mas em posições diferentes na memória, isso por causa das clousures.

---

### Desvantagens ao utilizar classes ou funções construtoras

- Vou tender a fazer herança clássica, e isso não é bom.
    - É inflexível;
    - The gorilla banana problem;
- Complexidade;
- Preciso me preocupar com **new**, **this**, construtor com a primeira letra maiúscula, constructor, etc.

### Vantagens das factory functions

- Menos problema para refatoração;
- Não preciso me preocupar com o **new**;
- O valor do this volta ao padrão. Proporciona também menos o uso do próprio **this**, e isso é bom porque o **this** é imprevisível e quanto mais previsível é minha aplicação melhor.

### Desvantagens das factory functions

- Microotimizadamente mais lenta que as classes. Porém isso só devo me preocupar depois de fazer a perceived perfomance (performance percebida).

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @sou-gabriel. Vamo que vamo, rumo à fluência! 🔥
