### ISSUE TITLE
Dúvida sobre o uso do filter() e forEach()

### ISSUE THREAD

**Issue by adlagomes** [roger-melo-treinamentos/curso-de-js-roger-melo#7388]
### Etapa da aula

9

### Nome da aula

Buscando e filtrando to-dos - Aula 02-03

### Link da aula

https://app.nutror.com/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991283

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Boa tarde, a dúvida surgiu quando eu estava no exercício 25 tentando criar meu próprio to-do list.
Na parte de filtrar senti certa dificuldade em desenrolar, mesmo já tendo feito antes e refatorado. Senti que estava seguindo mais pela lembrança do código que tinha sido escrito antes do que pelo meu próprio raciocínio de quando usar determinada função ou método etc.
Ocorre que acabei usando o filter() sem encadear o forEach() para adicionar a classe na li que receberia o "hidden".
```js
inputSearchTodo.addEventListener('input', event =>{
  const inputValue = event.target.value.trim()
  Array.from(todosContainer.children).filter(todo => {
    if(!todo.textContent.includes(inputValue)){
       todo.classList.add('hidden')
    }
  })
```
Isso está funcionando aqui, a classe é adicionada e as li desaparecem. Só que vendo a aula do Roger, fiquei me questionando sobre o uso do forEach(), se realmente é necessário ou se dá pra usar só o filter() sem sofrer nenhuma repercussão negativa futura.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @adlagomes!

O ideal é usar o filter quando precisamos fazer algo com o array que ele retorna. Ou seja, usamos o filter com a expectativa de fazer algo com o array que ele retorna e que, potencialmente, será menor que o array original. 

Em seu exemplo, o filter foi usado apenas para executar efeito colateral (manipulação de DOM). Quando precisar executar efeito colateral, o forEach é um método mais adequado. Até pq ele foi feito exatamente para isso e nunca retorna valor. 

Se vc ainda não chegou na parte onde explico o que é efeito colateral, em breve vc irá chegar =)

Está ficando mais claro?

**Comment by adlagomes** [comment]
Ainda não cheguei na parte do efeito colateral. Era isso mesmo que eu tinha dúvida. Obrigada por responder. Depois vou arrumar o código que escrevi. ;)

**Comment by Roger-Melo** [comment]
Boa! No que precisar, é só dar o toque =)
