### ISSUE TITLE
Etapa 07, Aplicação: Quiz Interativo - Aula Exercícios da Aula 01

### ISSUE THREAD

**Issue by luiizsilverio** [roger-melo-treinamentos/curso-de-js-roger-melo#74]
@Roger-Melo

Roger, segue o link do meu repositório:
https://github.com/luiizsilverio/quiz-livros

A maior dificuldade foi com a parte visual, pois a parte de javascript foi tranquilo.

**Comment by Roger-Melo** [comment]
Oi Luiz. Parabéns pelo esforço! =D

Deu pra perceber que você se preocupou com a aparência da aplicação e teve cuidado com a lógica e nomes das variáveis.

---

Vou deixar abaixo alguns pontos que você pode considerar para melhorar a aplicação:

- Observe que na pergunta 2, "Único livro de ficção do famoso astrônomo e divulgador científico", faltou o nome do Carl Sagan.

- Não utilize o `some` como loop. O propósito do `some` é verificar se algum dos itens do array atende a condição especificada na função. A função do `some` sempre precisa retornar um boolean ou uma expressão que resulte em um boolean. 

Se a função retornar `true` para pelo-menos 1 item do array, o some vai parar a execução da função e retornar true. Caso contrário, ele retornará `false`.

Exemplo:

```javascript
const array = [1, 2, 3, 4, 5]

array.some(number => number % 2 === 0)
```

No código acima, a função recebe um número do array por parâmetro e retorna um boolean indicando se o número é par. Se algum número desse array é par, a função retorna `true` e o some para de ser executado imediatamente.

Esse é o propósito do some. Verificar se algum dos itens do array atende a condição especificada na função.

No código abaixo, o `some` foi usado apenas para executar a função a para cada item do array.

```javascript
  respostas.some((item, indice) => {
    if (item === corretas[indice]) {
      acertos += (100 / qtdPerguntas)
    }
  })
```

Se é necessário apenas executar uma função para cada item de um array, prefira usar o `forEach`:

```javascript
  respostas.forEach((item, indice) => {
    if (item === corretas[indice]) {
      acertos += (100 / qtdPerguntas)
    }
  })
```

- Sempre verifique se não há `console.log`'s no código antes de entregá-lo. Esse método é necessário apenas enquanto a implementação do código está sendo feita.

- Linhas em branco podem ser inseridas no código para indicar, visualmente, a separação entre conceitos. Exemplo:

```javascript
// antes
scrollTo(0, 0)
const resultado = document.getElementById('resultado')
const total = resultado.querySelector('h3 > span')
const dica = resultado.querySelector('#dica')

// depois (invocação de método separado de declarações de consts)
scrollTo(0, 0)

const resultado = document.getElementById('resultado')
const total = resultado.querySelector('h3 > span')
const dica = resultado.querySelector('#dica')
```

Por convenção, prefira não deixar linhas em branco no topo de um bloco. Ao invés de deixar o topo do bloco em branco,

```javascript
const enviaQuiz = ev => {

    let acertos = 0
    ev.preventDefault()
}
```

prefira deixá-lo assim:

```javascript
const enviaQuiz = ev => {
    let acertos = 0
    ev.preventDefault()
} 
```

Novamente, por convenção, ao invocar o `preventDefault`, prefira deixá-lo na primeira linha:

```javascript
const enviaQuiz = ev => {
    ev.preventDefault()
    
    let acertos = 0

    // ...
} 
```

- Elimine a redundância em atribuições. Observe que no código abaixo,

```javascript
acertos = acertos += (100 / qtdPerguntas)
```

a `let acertos` está recebendo o resultado da expressão `acertos += (100 / qtdPerguntas)`.

O mesmo resultado é obtido se a primeira atribuição, da esquerda para a direita, for removida:

```javascript
acertos += (100 / qtdPerguntas)
```

No código acima, a `let acertos` está recebendo o valor que ela já tem somado ao resultado de `(100 / qtdPerguntas)`. Isso é o mesmo que fazer `acertos = acertos + (100 / qtdPerguntas)`.

---

No mais, parabéns pelo esforço. Continue seguindo o método e conte comigo para chegar na fluência na linguagem =)

@luiizsilverio

**Comment by luiizsilverio** [comment]
Obrigado.

**Comment by luiizsilverio** [comment]
Obrigado.
