### ISSUE TITLE
Resumo da Aula String da etapa 01

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#744]
## Strings

- Uma sequência de caracteres segurados por aspas simples ou duplas
    - quando se inicia com aspas simples deve-se fechar com aspas simples
    - e tudo que estiver entre as aspas é uma string inclusive números

```jsx
//Ex:
let text = 'Olá mundo do JS'
console.log(text)
const mission = "Rumo à fluência :)"
console.log(mission)
```

- possui propriedades e métodos
    - Length é uma propriedade ex: `text.length`
    - toUpperCase é um método ex: `text.toUpperCase()`
- Podemos concatenar duas strings utilizando o operador "+"

    ```jsx
    const firstName = 'Abel'
    const secondName = 'Gomes'

    let fullName = firstName + secondName
    console.log(myName)  // no console será mostrado o AbelGomes

    // para criar o espaço entre as duas palavras do fullName podemos concatenar um string vazia entre as duas variaveis
    fullName = firstName + ' ' + secondName
    // no console será mostrado o Abel Gomes
    ```

- Podemos acessar caracteres de uma string com a notação [x] ex: `fullName[0]`

    ```jsx
    //mostrando no console o primeiro caractere do fullName do exemplo acima
    console.log(fullName[0])
    // no console será mostrado o A
    ```

    - *Mas porquê zero (0)? Porque o JS é uma linguagem zero based, ou seja, a contagem começa no zero*
- Propriedade length
    - informa o comprimento de uma String ou quantidade de caracteres de uma string
    - atenção que espaço em branco é contando como um caracter

    ```jsx
    console.log(fullName.length) // no console será mostrado o 10

    console.log(' '.length) // no console será mostrado o 1

    ```

- Alguns métodos

    ```jsx
    console.log(fullName.toUpperCase()) // no console será mostrado ABEL GOMES
    console.log(fullName.toLowerCase()) // no console será mostrado abel gomes

    // Estes dois metodos não alteram o valor da string original ex: fullName

    console.log(fullName) // no console será mostrado Abel Gomes

    // Existem alguns métodos necessitam que sejam passados valores dentro dos Parênteses () 
    // esse valor passado entre os (x) é chamado de argumento

    //**indexOf** retorna o índece da string na qual o caractere entre os Parênteses ou argumento se encontra 
    console.log(fullName.indexOf('o'))// no console será mostrado 6

    ```

### Relevantes

Diferença entre métodos e funções:
- **funções** - pedaço de um código que executa uma ação especifica
- **método** - é uma função associado a um objecto ou tipo de dado `ex String`
    - reconhecemos pelo `()` - invocação
    - podem ou não receber **argumentos** ( e não parametros)

### Referências MDN:

- [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Rumo à fluência @cdfortes! 🔥
