### ISSUE TITLE
Aplicação: [QUIZ DE ASSUNTOS GERAIS]

### ISSUE THREAD

**Issue by RogDevcodar** [roger-melo-treinamentos/curso-de-js-roger-melo#7462]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/RogDevcodar/quiz_assuntos_gerais.git

### Maiores dificuldades durante a implementação

Foi bem tranquilo. As explicações do professor Roger me deixa bem confortável para entender como realizar os exercícios.

### Menores dificuldades durante a implementação

Não tive menores dificuldades.

**Comment by Roger-Melo** [comment]
Olá @RogDevcodar.

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
Olá @RogDevcodar! Sua análise está [neste link](https://youtube.com/live/HwKw_pgvroA). Qualquer dúvida, é só dar o toque =)

Parabéns pela aplicação! Rumo à Fluência 🔥
