### ISSUE TITLE
map e sort

### ISSUE THREAD

**Issue by Rodolfo-ss** [roger-melo-treinamentos/curso-de-js-roger-melo#7491]
### Etapa da aula

9

### Nome da aula

correcao exercicios 

### Link da aula

https://app.nutror.com/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991281

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Oi professor blz? entao tenho uma duvida em relação o exercicio 1 da correção que linkei acima, e resolvi assim, teve o resultado que pede no exercicio, e pq nao seria o melhor jeito.

const people = [
  { firstName: 'Estevão', lastName: 'Rodriguez', score: 90 },
  { firstName: 'José', lastName: 'Antônio', score: 100 },
  { firstName: 'Felipe', lastName: 'Tavares', score: 71 },
  { firstName: 'Eric', lastName: 'Silva', score: 82 }
]

const inPeople = people.map(item => item)

const inTime = inPeople.sort((item1, item2) => item1.score - item2.score)

console.log(inTime)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Rodolfo-ss. 

Eu fiz criando novos objetos para reforçar como retornar novos objetos, mas pode fazer da forma que você fez sem problemas, pois não está havendo reatribuição nas propriedades dos objetos originais =)
