### ISSUE TITLE
Etapa 07, Exercício Quiz - Aula 01

### ISSUE THREAD

**Issue by aureliocampos** [roger-melo-treinamentos/curso-de-js-roger-melo#75]
@Roger-Melo

Link do repositório : https://github.com/aureliocampos/cjrm-quiz-exercicio.git

### Maiores dúvidas ou dificuldades:
 * Ainda tenho um pouco de dificuldade quando chega a hora de refatorar meu código, ainda não consigo visualizar com facilidade todos os trechos necessitam e os que não necessitam também. Algumas sacadas eu comecei a pegar com as aulas claro, mas quando o meu código vai crescendo ainda fico um pouco perdido.

* Dúvidas quando preciso "agrupar funções", dentro de outra função, pelo que eu entendi uma função deve executar apenas uma ação, depois disso a dúvida se tornou maior ainda.
Nesse exercício tenho esse exemplo( linha 81 );

```
const resetQuiz = () => {
  form.reset()
  score = 0
  button.style.display = 'inline-block'
  removeFeedbackMessage()
}

```
A função resetQuiz, contém outras funções e executa outras coisas para diferentes pontos da aplicação, ainda não consigo visualizar uma melhor maneira de tornar isso mais "limpo", particularmente isso me incomoda, mas eu quero muito de saber se isso seria ok ou péssimo, e como posso melhorar.

### Menores dificuldades:
* Utilizar Javascript - Nesse exercício procurei adicionar 2 funcionalidades por conta própria pra ver como me sairia, consegui perceber minha evolução ao elaborar tais funcionalidades, compreender, ter certeza do que vai fazer e como fazer pro seu código funcionar, foi fantástico.

**Comment by Roger-Melo** [comment]
Oi Aurélio. Parabéns pelo esforço em construir a aplicação =)

> Ainda tenho um pouco de dificuldade quando chega a hora de refatorar meu código, ainda não consigo visualizar com facilidade todos os trechos necessitam e os que não necessitam também. Algumas sacadas eu comecei a pegar com as aulas claro, mas quando o meu código vai crescendo ainda fico um pouco perdido.

Essa dificuldade é natural. Primeiro é importante fazer funcionar, como você fez. A partir disso, com o conhecimento que você for adquirindo nas próximas aulas do treinamento, você pode voltar e tentar refatorar o que já fez nessa aplicação.

Com a prática, essa habilidade vai ficar mais forte em você. O importante é praticar, e perguntar sempre que tiver dúvidas.

Mas lembre-se: a prioridade é codar para fazer funcionar. Sem se preocupar com refatoração.

> Dúvidas quando preciso "agrupar funções", dentro de outra função, pelo que eu entendi uma função deve executar apenas uma ação, depois disso a dúvida se tornou maior ainda.
Nesse exercício tenho esse exemplo( linha 81 ).

Acho que você o que você quis dizer é invocar uma função dentro da declaração de outra função. Sim, há casos em que é necessário fazer isso, sem problemas.

> A função resetQuiz, contém outras funções e executa outras coisas para diferentes pontos da aplicação, ainda não consigo visualizar uma melhor maneira de tornar isso mais "limpo", particularmente isso me incomoda, mas eu quero muito de saber se isso seria ok ou péssimo, e como posso melhorar.

Isso ressalta a importância do que eu disse antes: é uma habilidade que vem com o tempo e a prática. Não se preocupe excessivamente com esse ponto. Faça o melhor com o conhecimento que você tem hoje. Com o tempo, você vai praticar e adquirir experiência com a linguagem, olhar para trás e ver no que está fazendo bem e o que pode ser melhorado.

Dito isso, vou deixar abaixo alguns pontos que você pode dar prioridade e focar em melhorar.

---

### Consistência no visual da aplicação

Você posicionou bem a mensagem com a pontuação após o envio. Para deixar a aparência dos botões "Enviar" e "Tentar novamente" parecidas, prefira usar o mesmo estilo para os dois. Você pode estilizar o botão de tentar novamente como um botão do bootstrap, por exemplo.

### Linhas em branco como separação entre conceitos

Linhas em branco podem ser inseridas no código para indicar, visualmente, a separação entre conceitos. 

Como cada função representa um conceito, você pode deixar uma linha em branco entre a declaração delas:

```javascript
// antes
const insertButtonReset = target => {
  // ...
}
const createFeedbackMessage = text => {
  // ...
}
const setFeedbackMessage = score => {
  // ...
}

// depois
const insertButtonReset = target => {
  // ...
}

const createFeedbackMessage = text => {
  // ...
}

const setFeedbackMessage = score => {
  // ...
}
```

Esse princípio também pode ser usado para separar atribuições de invocações de métodos, por exemplo.

```javascript
// antes
const resetQuiz = () => {
  form.reset()
  score = 0
  button.style.display = 'inline-block'
  removeFeedbackMessage()
}

// depois
const resetQuiz = () => {
  score = 0
  button.style.display = 'inline-block'
  
  form.reset()
  removeFeedbackMessage()
}

// ou
const resetQuiz = () => {
  form.reset()
  removeFeedbackMessage()

  score = 0
  button.style.display = 'inline-block'
}
```

Se a função tiver apenas duas linhas dentro do bloco, você pode desconsiderar o princípio.

### Identificação dos elementos da aplicação

Como a aplicação tem 2 botões diferentes, ao invés de nomear um dos botões como "button", prefira especificar o que o botão faz.

```javascript
// antes
const resetQuiz = () => {
  // ...
  button.style.display = 'inline-block'
}

// depois
const resetQuiz = () => {
  // ...
  submitFormButton.style.display = 'inline-block'
}
```

Se a aplicação tivesse 2 forms com um botão em cada form, os nomes dos botões precisariam ser ainda mais específicos. 

### Declaração e configuração de elementos

Observe que no código abaixo,

```javascript
const paragraphFeedbackMessage = document.createElement('p')
paragraphFeedbackMessage.setAttribute('class', 'text-center my-4')
```

a declaração e configuração do elemento estão unidas, em escopo global.

Se for necessário usar a `paragraphFeedbackMessage` em duas funções diferentes, você pode apenas declará-la em escopo global,

```javascript
const paragraphFeedbackMessage = document.createElement('p')
```

e deixar para fazer as configurações do elemento dentro da função que vai ser executada quando a configuração do elemento precisar acontecer.

Essa separação deixa o código mais organizado. Ele ficaria assim:

```javascript
const form = document.querySelector('.quiz-form')
const button = document.querySelector('button')

const paragraphFeedbackMessage = document.createElement('p')
const buttonResetQuiz = document.createElement('button')

const correctAsnwers = ['B', 'A', 'B', 'A']

let score = 0

// declarações de funções

// addEventListeners
```

Sacou a ideia?

### Refatoração

Nas aulas seguintes, você verá que eu vou mostrar como melhorar esse código.

Fique atento à ordem na qual vou refatorar as funções, o que vou refatorar primeiro, qual nome vou dar às funções... Isso vai te dar um bom norte. Após assistir, tente fazer sozinho o que eu mostrei, sem olhar a aula. Isso vai te deixar mais confiante =)

---

Respondi suas dúvidas?

@aureliocampos

**Comment by aureliocampos** [comment]
Olá @Roger-Melo, obrigado pelas respostas, vou ficar atento e praticar! Um abraço.
