### ISSUE TITLE
Etapa 1, nome do vídeo: Aviso sobre a correção dos exercícios

### ISSUE THREAD

**Issue by claudiogmoreira** [roger-melo-treinamentos/curso-de-js-roger-melo#751]
Onde encontro exercícios modelos de javascript?
Exercícios propostos são os do treinamento, correto?
Sobre a documentação do MDN, ela é atualizada?
Tive a impressão que o conteúdo parece estar desatualizado,
exemplo: buscando por variáveis, mostra como declarar usando VAR

obrigado,
Claudio

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @claudiogmoreira.

> Onde encontro exercícios modelos de javascript?

Conforme for avançando no treinamento, você perceberá que os últimos 2/3 exercícios de cada bateria de exercícios são mais complexos. Eles são exercícios-modelo =)

> Exercícios propostos são os do treinamento, correto?

Isso mesmo.

> Sobre a documentação do MDN, ela é atualizada?

Sim. E é a mais confiável.

> Tive a impressão que o conteúdo parece estar desatualizado, exemplo: buscando por variáveis, mostra como declarar usando VAR

Na verdade é o contrário. A forma antiga de se criar variáveis é usando a palavra chave `var`. Falei sobre isso mais ou menos aos 04:40 [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/733507) =)

**Comment by Roger-Melo** [comment]
@claudiogmoreira vou fechar a issue mas no que precisar, é só abrir uma nova =)
