### ISSUE TITLE
Video do dia 29/05

### ISSUE THREAD

**Issue by bivar37** [roger-melo-treinamentos/curso-de-js-roger-melo#752]
Tinha um video que seria postado dia 29/ 5/21.

kd?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @bivar37. O vídeo foi postado, é a [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928) de quem entrou no treinamento semana passada =)

**Comment by Roger-Melo** [comment]
@bivar37 vou fechar a issue mas no que precisar, é só abrir uma nova =)
