### ISSUE TITLE
Aplicação: Weather App

### ISSUE THREAD

**Issue by DevNeves** [roger-melo-treinamentos/curso-de-js-roger-melo#7523]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Não

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://github.com/DevNeves/Weather-App

### Maiores dificuldades durante a implementação

A questão de nomear as constantes/funções, mas acho que ja to ficando melhor nisso kk ve os nomes e me fala oq você achou.
Fiquei meio perdido no começo em relação dos diretórios pois até agora as aplicações ficavam tudo junto em uma pasta só mas depois consegui entender tudo.
A desestruturação de arrays e objetos ainda me deixa um POUCO confuso, mas conseguir compreender

### Menores dificuldades durante a implementação

Inserir os dados, imagem e icones do clima no DOM
Refatorar não foi tão dificil, e também não sei como o Roger fez, eu preferi fazer sozinho para ter uma avaliação no que eu devo melhorar
Em relação com os requests não tive muita dificuldade

**Comment by Roger-Melo** [comment]
Olá @DevNeves!

Passando para dizer que a issue foi visualizada e em até 10 dias úteis a análise será feita =)

**Comment by Roger-Melo** [comment]
constantes: substantivos

**Comment by Roger-Melo** [comment]
Olá @DevNeves!

Você verá em seu repositório um pull request com sugestões de refatoração. 

Em breve envio aqui o vídeo com a análise completa para você entender cada uma delas =)

**Comment by DevNeves** [comment]
obrigado Roger

**Comment by Roger-Melo** [comment]
Olá @DevNeves! Sua análise da aplicação está no link abaixo. Qualquer dúvida, é só dar o toque =)

https://vimeo.com/856615866

Parabéns pela aplicação! Rumo à Fluência 🔥

**Comment by DevNeves** [comment]
<h2>Obrigado pela avaliação Roger me ajudou muito a entender ainda mais. Está sendo um bom  processo de aprendizagem e sinto que cada dia que passa eu aprendo algo a mais e seguindo para que um dia eu chegue na fluencia em JS. O CJRM até hoje foi o melhor curso que eu ja fiz (to fazendo né kk) que voce continue com essa sua ótima didática.  </h2>

**Comment by Roger-Melo** [comment]
Hahah, valeu demais @DevNeves! Fico no aguardo de sua próxima aplicação. 

Rumo à Fluência 🔥
