### ISSUE TITLE
Resumo da Aula Controle de Fluxo da etapa 02

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#754]
## Controle de fluxo de dados

Para controle de fluxo temos o For Loop e o While

**For loop** - Faz uma iteração, de acordo com número de voltas passado como parâmetro, sobre cada item e executa a rotina dentro dele. Muito usado em arrays para percorrer os itens. O número de voltas é definido pelo tamanho do array com a propriedade **.length**. 

No exemplo abaixo, podemos ver que a variável [i] é o índice do array, a cada volta no loop, ela vai lá no array e traz a informação para o console:
```js
const myFavoriteGames = ['COD', 'Fortnite', 'Horizon', 'GTAV']

for(let i = 0; i < myFavoriteGames; i++){
console.log(`Eu gosto de jogar: ${myFavoriteGames[i]}`)
} 
// Eu gosto de jogar: COD
// Eu gosto de jogar: Fortnite
// Eu gosto de jogar: Horizon
// Eu gosto de jogar: GTAV
```

While faz parecido, mas é necessário indicar o **limitador** fora do loop e ter um **incrementador** dentro do loop
```js
const myFavoriteGames = ['COD', 'Fortnite', 'Horizon', 'GTAV']

let i = 0

while(count < myFavoriteGames.length;){
console.log(`Eu gosto de jogar: ${myFavoriteGames[i]}`)
i++
} 
// Eu gosto de jogar: COD
// Eu gosto de jogar: Fortnite
// Eu gosto de jogar: Horizon
// Eu gosto de jogar: GTAV
```
**Obs: Muito cuidado com o loop infinito**

Nota: Achei bastante interessante a junção de loop com operadores de incremento. Posso criar uma variável vazia fora do loop e ir incrementando o valor dela ao decorrer da iteração e ter o valor atualizado para usar depois.

```js
const numbers = [31, 32, 33, 30]
let sumNumbers = 0

for(let i=0; i < numbers.length; i++){
sumNumbers += numbers[i] 
}
console.log(sumNumbers) // 126
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @edcabralc. Rumo à fluência! 🔥
