### ISSUE TITLE
Resumo da Aula 01-06 sobre constantes, variáveis e comentários da Etapa 01

### ISSUE THREAD

**Issue by rogerioopaiva** [roger-melo-treinamentos/curso-de-js-roger-melo#755]
### O que é uma variável e uma constante?

É um local onde é armazenado um dado, um valor. Esse valor pode ser uma letra, texto ou número.

  Existe três tipos de definições para uma variável que são: let, var e const.

**Let** = Define como variável onde permite armazenar alguma informação dentro do escopo de onde é acessada como por exemplo, de dentro de um array permitindo ser alterada sempre que possível.
```js
let lastMonth = "April"              // Poderá ser acessada apenas dentro de um escopo. Por exemplo um array, uma função.
```

 **var** = É um tipo antigo que permite acessar a variável de forma global permitindo ser acessada fora do escopo onde é utilizada, ou seja, fora de um array ou função. A utilização deste tipo não é mais recomendada por correr grandes riscos de alterar o valor caso seja criada com o mesmo nome em escopos diferentes.
```js
var currentMonth = "May"       // Poderá ser acessada dentro e fora de um escopo.
```

  Uma constante é uma variável que não modifica. No caso do javascript é definida com o tipo **const**.
```js
const currentYear = 2020
currentYear = 2021                  // Esse código apresentará um erro pois a constante currentYear não pode receber um novo valor. 
```

  Existem também os comentários de código que são a escrita de um texto informativo junto ao código de forma que apenas o desenvolvedor consiga ler e não interfira ou modifique a escrita do código. Para isso existem duas maneiras de comentar um código que são comentário em uma linha e comentário de bloco.

  Através da utilização de duas barras, é possível comentar uma linha de um código. 
Exemplo:
```js
// Isso é um comentário em uma linha
```
E temos também o comentário em bloco:
```js
/* 
Isto é um bloco
 de código 
 comentado.
*/
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rogerioopaiva. Rumo à fluência! 🔥
