### ISSUE TITLE
Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by Henrique-SPinheiro** [roger-melo-treinamentos/curso-de-js-roger-melo#76]
Roger, tudo bem?

Estou com uma dúvida rápida. Estou na Correção dos exercícios da aula 02, etapa 06 (Aula 01-01), e quando eu rodo os elementos do HTML e do CSS minha página fica lerda e parece que não "roda" o CSS. Sabe o que pode estar acontecendo?

Obrigado.

**Comment by Roger-Melo** [comment]
Oi Henrique.

Suba o projeto no GitHub e me envie o link. Assim posso testar em minha máquina e ver se o mesmo acontce aqui =)

@Henrique-SPinheiro

**Comment by Roger-Melo** [comment]
Oi Henrique. Vou fechar a issue mas se ainda houver dúvidas, é só chamar =)
