### ISSUE TITLE
Resumo da Aula Uma introdução ao Bootstrap - Aula 01-02 da etapa 07

### ISSUE THREAD

**Issue by guilepereira** [roger-melo-treinamentos/curso-de-js-roger-melo#7608]
# Uma introdução ao Bootstrap - Aula 01-02
- Bootstrap é uma biblioteca CSS e JavaScript, que compõe diversos componentes frontend;
- Permite reutilizar elementos e parte da interface do usuário;
- Componentes predefinidos ajudam no design do projeto;
- Usado para prototipar o visual das interfaces das aplicações por meio das regras de CSS que ele oferece;
- CDN -> Content Delivery Network é uma maneira de importar os padrões oferecidos pelo bootstrap como uma forma de biblioteca de elementos a serem reaproveitados;

> [Acessar Bootstrap](https://getbootstrap.com/)

<br />

----

<br />

# Bootstrap | Funcionamento e Conceitos básicos

- Bootstrap é um framework criado pela equipe do Twitter e oferece estilos predefinidos, componentes e utilitários, de maneira responsiva e ágil;
- É desenvolvido na abordagem "mobile first" e posteriomente ajustando o layout por meio de media queries e para garantir responsividade integral, é mandatório a presença da configuração de viewport abaixo:
  ```html
  <meta name="viewport" content="width=device-width, initial-scale=1">
  ```

## Adicionando o Bootstrap
- Por meio de CDN (Content delivery network) podemos acessar os recursos que o bootstrap fornece;
- O acesso ocorre ao usar a tag link no head do documento para vincular o conteúdo CSS do bootstrap e conteúdo JavaScript com a tag script no final do body;

  Link CSS
  ```html
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  ```

  Link JavaScript
  ```html
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  ```

> A iniciativa Bootstrap também oferece o [Popper](https://popper.js.org/), uma ferramenta para auxiliar no desenvolvimento de popups e posicionamentos;

## Box-sizing
- Como estratégia de simplificação de estilo, é padrão o uso do atributo CSS box-sizing com valor "border-box";
- Essa alteração evita que o padding altere o tamanho final do elemento;
- Em casos de conflito, alterar o valor para "content-box";

## Reboot
- É uma forma de reset dos aspectos CSS padrões dos navegadores, evitando inconsistências que possam renderizar os elementos/componentes de maneira fora do esperado; Essa abordagem visa otimizar pela simplicidade e agilidade;

> Conferir alterações pelo [Reboot](https://getbootstrap.com/docs/5.3/content/reboot/)

<br />

-------

<br />

**Referências**

[DOC Bootstrap - Introdução](https://getbootstrap.com/docs/5.3/getting-started/introduction/)

**Comment by Roger-Melo** [comment]
@guilepereira não esquece de abrir as issues de resumo com a label de resumo =)

**Comment by guilepereira** [comment]
Perdão Roger, foi desatenção! Precisei postar pelo tablet e lá as opções eram reduzidas, acabei não vendo.
Estou procurando como adicionar na edição da issue mas não encontro, deleto essa e posto novamente?

**Comment by Roger-Melo** [comment]
Não sei como é no tablet, mas tem uma sessão aqui na página chamada "Labels". Através dela vc consegue adicionar a label "📄resumo" =)
