### ISSUE TITLE
Resumo da Aula Aula 02-05 da etapa 01

### ISSUE THREAD

**Issue by MacedoGuilherme** [roger-melo-treinamentos/curso-de-js-roger-melo#761]
### Numbers

**Inteiros e decimais**

É possível trabalhar no JavaScript com números inteiros e decimais.

`const radius = 10`
`const pi = 3.14`

**Operadores aritméticos**

Os operadores aritméticos são responsáveis por executar cálculos matemáticos.

Operadores:

Adição            ( + )
Subtração      ( - )
Multiplicação ( * )
Divisão           ( / )
Restante        ( % )

`console.log(10 + 5) // retorna 15`
`console.log(10 - 5) // retorna 5`
`console.log(10 * 5) // retorna 50`
`console.log(10 / 5) // retorna 2`
`console.log(10 % 5) // retorna 0`

**Ordem de operações**

Algumas operações serão aplicadas antes de outras quando calculamos o resultado de uma expressão, a precedência de operadores em JavaScript é semelhante a matemática ensinada na escola:

1. Parênteses
2. Expoentes ou raízes
3. Multiplicação ou divisão
4. Adição ou subtração

`console.log( 10 + (5 * 3) / 5 ) // retorna 13`

**Operadores de incremento e decremento**

É possível utilizar os operadores de incremento ( ++ ) e decremento ( -- ) para incrementar ou decrementar um número ou variável em JavaScript.

`let number = 8`
`number++`
`console.log(number) // retorna 9`
`number--`
`console.log(number) //retorna 8`

**NaN - Not a Number**

Normalmente o valor de NaN é retornado quando uma operação matemática falha ou quando uma função tenta transformar uma string em inteiro.

`console.log(Math.sqrt(-1)) // retorna NaN`
`console.log(parseInt("blabla"))`

**Concatenando string com número**

Sempre que houver uma tentativa de concatenar números com string, o JavaScript implicitamente converte os números em string.

`console.log('Eu tenho ' + 10 + ' reais') // retorna 'Eu tenho 10 reais'`

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @MacedoGuilherme. Rumo à fluência! 🔥
