### ISSUE TITLE
Aplicação: [weatherAplication]

### ISSUE THREAD

**Issue by allanpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#764]
Link do repositório da aplicação weatherAplication 

https://github.com/allanpedro/weatherAplication

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @allanpedro.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @allanpedro.

Parabéns pelo esforço em construir a segunda aplicação.

Você esqueceu de colocar na issue quais foram as suas maiores e menores dificuldades durante a construção da aplicação. Mas pelo que percebi, você tem pegado bem a lógica até aqui e não cometeu os mesmos pontos de atenção da aplicação passada =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

### Indentação

Agora que você está avançando no treinamento, eu vou começar a observar um pouco mais a organização do código.

Dentro do callback do envio do form, apenas a primeira linha está indentada. A indentação do restante do código é importante para evidenciar que ele está dentro do bloco.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso e/ou a falta delas no código.

Seguindo esse princípio, no `app.js`, as linhas em branco 8, 22 e 36 podem ser removidas.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Afinal, não faz sentido deixar um buraco entre apenas duas linhas de código.

### Lógica

Na aula, eu deixei a `let` timeImg como let para indicar que o valor dela seria modificado no decorrer da aplicação. Mas não fez muito sentido porque o que foi modificado é o valor de uma propriedade do objeto que ela armazena, e não o valor da let em si. Então se quiser, pode deixar a timeImg como `const`.

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
@allanpedro vou fechar a issue mas no que precisar, fique à vontade para perguntar =)
