### ISSUE TITLE
Etapa 09, nome do vídeo: Aviso importante

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#767]
Qual versão do todo eu devo enviar? A refatorada(feita na primeira aula da etapa 10) ou a normal(construída ao decorrer da etapa 09)?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a. Vou deixar as instruções aqui abaixo e se tiver alguma dúvida, é só dar o toque =)

---

Passo 1

Você tem o prazo de 7 dias para implementar a aplicação, começando no dia em que você viu as aulas descritas logo abaixo. A plataforma disponibiliza para mim um relatório com as aulas que você acessou.

Se você viu as aulas de como construir a aplicação de quiz interativo, por exemplo, você tem 7 dias para implementar essa aplicação *sozinho(a).

*O que eu quero dizer com "sozinho" é:

1. Sem assistir as aulas da aplicação novamente, implemente-a. 

2. Se travar em um ponto, assista a aula, apague todo o código e implemente-o novamente, sozinho. Se não conseguir implementar sem assistir a aula, veja-a novamente. Após sanar a dúvida, apague o código e implemente-o, sozinho.

3. Execute o item acima quantas vezes forem necessárias para que seu cérebro entenda o padrão de implementação da aplicação. Isso te deixará mais "afiado" para os próximos desafios do treinamento.

E claro, se mesmo executando os itens acima as dúvidas permanecerem, não hesite em abrir uma issue no repositório do treinamento.

*Após a primeira aula mostrando como construir o quiz interativo, além de seguir os passos e critérios abaixo, implemente o que o exercício após a aula pede.

Você verá que apenas essa primeira aplicação (quiz) tem um exercício pedindo para você enviá-la ao repositório. Porém, se você está recebendo este email, esteja ciente de que você pode executar o que estou descrevendo nele para todas as aplicações do treinamento.

Segue abaixo o momento em que você deve enviar cada aplicação para a análise:

a) Quiz interativo: antes de assistir a aula "Exibindo a pontuação - Aula 02-01", da etapa 07;

b) To-do list: antes de assistir a aula "Correção dos exercícios da aula 02 da etapa 09 - Aula 01-01", da etapa 10;

c) Weather Application: antes de assistir a aula "Correção dos exercícios da aula 02 da etapa 12 - Aula 01-01", da etapa 13;

d) Conversor de moedas: antes de assistir a aula "Correção dos exercícios da aula 03 da etapa 14 - Aula 01-01", da etapa 15.

Passo 2

Após implementar a aplicação (no prazo estipulado acima), abra uma issue no repositório do treinamento seguindo os critérios descritos abaixo.

A issue deve ser aberta com o issue template "aplicação" (por favor, não utilize outro template de issue).

Passo 3

Eu irei ler a sua issue e iniciarei a análise (ou pedirei ajuste, se necessário).

Abaixo seguem os critérios das análises:

- Critério 1: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula;
- Critério 2: a aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas anteriores;
- Critério 3: a aplicação só deve conter features da linguagem que foram mostradas nas aulas anteriores;
- Critério 4: a issue deve conter o link do repositório da sua versão da aplicação e quais foram as suas maiores e menores dificuldades durante a implementação dela.

Ao passar por todos os passos e critérios, você garante que suas aplicações serão analisadas. Preto no branco.

Por isso, o quanto antes você avançar no treinamento e construir as aplicações, mais cedo vou conseguir fazer a sua análise personalizada com sacadas que vão te dar mais clareza na sua jornada para chegar na fluência.

**Comment by YureK-a** [comment]
Solucionei minha dúvida, obrigado!
