### ISSUE TITLE
Como validar um input de username e aplicar um estilo em tempo real.

### ISSUE THREAD

**Issue by Mikahel-Lucas** [roger-melo-treinamentos/curso-de-js-roger-melo#7679]
### Etapa da aula

6

### Nome da aula

Eventos do teclado - Aula 02-03

### Link da aula

https://app.nutror.com/curso/d93d9d39043a327b54e12aaf47b57ab48c2fef2b/aula/6991252

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Olá Roger.
Primeiro quero agradecer pelo conteúdo do curso, estou aprendendo muito.
Vamos para a dúvida.

Eu segui o mesmo código que você passou na aula. 

Por algum motivo que não consegui entender, o meu input só é estilizado quando eu clico fora dele. 

Por exemplo, se eu colocar um username que não dá match com a regex, o input não é validado, e o estilo da borda vermelha do input é aplicado. Se eu colocar um username que dá match com a regex, o input é validado e o estilo da borda verde do input é aplicado.
Mas a borda do input só muda de cor quando eu clico fora do input. Enquanto o cursor está no input e eu estou digitando, o input não muda de cor.

Você consegue me passar uma ideia do que está acontecendo?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Mikahel-Lucas!

Dá uma olhada na resposta [deste link](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/1932). Se ainda restar alguma dúvida, é só dar o toque =)
