### ISSUE TITLE
Resumo da Aula Funções da etapa 03

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#768]
## Funções

Bloco de código ou conjunto de ações para se reutilizar novamente em qualquer parte do código. 

- **O ideal é que uma função sempre retorne o mesmo tipo de dado**
- **Executar, chamar, invocar são sinônimos**

As funções estão diretamente ligadas ao escopo, visto no inicio do curso.

> MDN -> As variáveis definidas no interior de uma função não podem ser acessadas de nenhum lugar fora da função, porque a variável está definida apenas no escopo da função. No entanto, uma função pode acessar todas variáveis e funções definida fora do escopo onde ela está definida. Em outras palavras, a função definida no escopo global pode acessar todas as variáveis definidas no escopo global. A função definida dentro de outra função também pode acessar todas as variáveis definidas na função hospedeira e outras variáveis ao qual a função hospedeira tem acesso.

## Tipos de Função

1. **Function declaration**

Declarada junto com a palavra reservada `function` e o nome da função seguido de (). Dentro dos parênteses podemos passar valores que chamamos de **parâmetros**, para informar valores padrões basta fazer a atribuição ao valor usando o sinal de atribuição `=`:

```js
function myFunction(param, param2 = 1){ 
// o param é obrigatório ser passado
//o param2 nesse caso é opcional e por padrão tem o valor 1
console.log(param, param2)
}
```

2. **Function expressions**

A função é atribuída a uma variável e é invocada da mesma forma que uma **Function declaration**:
```js
let myFunction = function(param, param2 = 1){ 
// o param é obrigatório ser passado
//o param2 nesse caso é opcional e por padrão tem o valor 1
console.log(param, param2)
}

myFunction(1)//
```
**Obs: O **hoisting** não funciona em Function expression, pois a criação da função não é içada para o topo do código**

3. **Arrow function - ES06**

É uma sintaxe mais curta de uma função usamos o simbolo `=>`:

```js
const chart = (caracter) => {
    return `Eu sou o parametro ${caracter}`;
};

console.log(chart);
```

Outra forma mais simples:
```js
const chart = caracter => { `Eu sou o parametro ${caracter}`

console.log(chart);
```
Podemos retornar em apenas uma linha quando se tem apenas um argumento.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @edcabralc! Rumo à fluência! 🚀
