### ISSUE TITLE
Aplicação: To-do

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#769]
link do github: https://github.com/YureK-a/Meu-portfolio/tree/main/To-do

Maior dificuldade:
A parte de pesquisa de to-dos. Tive que rever algumas vezes a aula(segui o protocolo de apagar e refazer) para conseguir fazer essa parte. Além disso, sofri para conseguir isolar os Array.from(), e depois de várias tentativas achei uma forma mais agradável de colocá-los no código.

Menor dificuldade:
Escolher as cores. Mesmo que seja mais fácil do que as outras partes do código, tenho muita dificuldade em escolher cores senão preto e branco, por isso mantive o background do body e modifiquei apenas a lixeira e o texto do to-do.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @YureK-a.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @YureK-a!

Parabéns pelo esforço em construir a segunda aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Lógica

### Callbacks

A `removeTodo` pode ser apenas referenciada como callback do evento de clique do `todosContainer`:

```javascript
// antes
todosContainer.addEventListener('click', event => {
  removeTodo(event)
})

// depois
todosContainer.addEventListener('click', removeTodo)
```

No fim das contas dá na mesma, mas com menos código =)

O mesmo pode ser feito com a `filteredTodos`:

```javascript
// antes
searchFormTodo.addEventListener('input', event => {
  const inputValue = event.target.value.trim().toLowerCase()
  filteredTodos(inputValue)
})

// depois
searchFormTodo.addEventListener('input', filteredTodos)
```

A diferença é que agora a declaração da `filteredTodos` irá receber o `event` por parâmetro:

```javascript
const filteredTodos = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  
  hideTodo(inputValue)
  showTodo(inputValue)
}
```

### Input de busca

Observe que ao inserir `co` no input de busca, 'Concertar a biscicleta' não é exibido. 

Isso aconteceu por que durante a filtragem dos to-dos, o `toLowerCase()` não foi usado. E isso faz com que `co` não dê match com `Co` (início da string do 1º to-do). No momento da comparação, as strings nas quais `todo.textContent.includes` e `inputValue` resultam precisam ter todos os caracteres em lower case ou upper case =)

## Organização de código

### Nomes dos arquivos

Tome cuidado com caracteres especiais como `ç` e `ã` em nomes de arquivos.

[Aqui](https://reactjs.org/docs/faq-structure.html) tem uma convenção de como nomear arquivos em ReactJS, por exemplo. Não é a converção que eu sigo (gosto-de-nomear-assim.js), mas acho que pode ajudar xD

### Indentação

Na marcação HTML que todoToAdd armazena, para deixar o código mais legível, você pode indentar as tags da marcação:

```javascript
// antes
const todoToAdd = `<li class="list-group-item d-flex justify-content-between align-items-center">
<span>${inputValue}</span>
<i class="far fa-trash-alt delete text-danger"></i>
</li>`

// depois
const todoToAdd = `
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <span>${inputValue}</span>
    <i class="far fa-trash-alt delete text-danger"></i>
  </li>
`
```

### Nomes de variáveis

Como `filteredTodos` é uma função, prefira nomeá-la como `filterTodos`.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem começar com `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso e/ou a falta delas no código.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

Sabendo disso, eu removeria as linhas em branco 44, 51 e 59.

Sobre a refatoração, nas aulas seguintes você verá uma forma de melhorar o código =)

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by YureK-a** [comment]
Fizeram sim, obrigado pela correção! =)
