### ISSUE TITLE
Etapa 9, Exercícios da aula 01

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#77]
Essa é bizarra hein: o navegador está pausando o código mesmo com o debugger comentado. Se eu tiver mais de um debugger ele vai pausar no último.

![image](https://user-images.githubusercontent.com/2471569/97502361-bda9cf80-1951-11eb-927e-cc992d1b95e0.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

Suba o projeto no GitHub e me envie o link. Assim posso testar em minha máquina e ver se o mesmo acontce aqui =)

@lucasfads

**Comment by lucasfads** [comment]
@Roger-Melo cá está: https://github.com/lucasfads/cjrm-debuggererror

**Comment by Roger-Melo** [comment]
Oi Lucas.

Tudo certo aqui. Você já tentou atualizar o chrome? Depois que você fechou e abriu ele, o problema continuou?

@lucasfads

**Comment by lucasfads** [comment]
Depois de testar um pouco mais aqui eu acho que entendi:
O Chrome deixa fazer breakpoints dentro dele mesmo, independentes do código. Pelo visto era isso que tava rolando.

**Comment by Roger-Melo** [comment]
Como esse?

![breakpoint](https://user-images.githubusercontent.com/29297788/97823298-4cdb1e00-1c97-11eb-9b11-753fbf9303a1.jpg)

É uma outra forma de inserir breakpoints no código, ainda vou falar sobre isso. Mas você "descobriu" antes 😂

**Comment by lucasfads** [comment]
Sim, exatamente.
Devo ter clicado em algum momento por acidente.
Enfim, resolvido né.
