### ISSUE TITLE
Resumo da Aula Constante, variáveis da etapa 01

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#770]
Variável é um espaço na memoria do computador destinado a guardar um dado que pode ser acessado e alterado em tempo de execução. Em javascript temos 3 tipos de variáveis, const, let e var.

# CONST
const é um tipo de variável de escopo de bloco cujo o valor não pode ser alterado ou redeclarada.

# LET
Let assim com const, é também uma variável de escopo de bloco, mas diferentemente da const é possivel ter seu valor alterado ou redeclarado.

# VAR
O var funciona como o let, porem seu escopo não é de bloco e sim global.

```
O escopo define em que partes do programa a variável será acessível.
 - Escopo global permite a variável ser acessada em qualquer local do código.
 - Escopo de bloco permite que a variável só fica acessível no bloco onde esta esta sendo declarada,
 Ex: for, if, functions e etc.
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @JuniorAlvesbr! Rumo à fluência! 🚀
