### ISSUE TITLE
Resumo da Aula Conversão de tipos da etapa 01

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#774]
# Conversão de tipos

- quando queremos transformar um tipo de dado é um outro tipo de dado `string em number por exemplo`
- utilizando uma função construtora  `Number()`
- quando tentamos converter alguma `string` que não faça sentido em `number` `NaN` é retornado
- Para converter em String usamos o `String()`
- para converter em tipo boolean utilizamos o `Boolean()`
- estes são **conversões explicitas**, temos as implícitas que são os que o **JS** faz por baixo dos panos

```jsx
let score = '100'

score = Number(score) o '100' agora é 100

console.log(score + 1) // 101 é mostrado

let crazyConversion = 'Maça'

crazyConversion = Number(crazyConversion) 

console.log(crazyConversion) // NaN
```

Para verificar um tipo de dado podemos utilizar o `typeof`

- retorna o tipo da variável

```jsx
let score = '100'

console.log(typeof score) // retorna string
```

**Valores Falsy**

- `false`
- `0`
- ```, '', ""`
- `null`
- `undefined`
- `NaN`

**OBS**: qualquer deles passados como argumento do `Boolean()` retorna `false`

**Valores Truthy**

- todos os outros que não estão na lista acima [link](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

### Referências MDN

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)

[https://developer.mozilla.org/en-US/docs/Glossary/Falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

[https://developer.mozilla.org/en-US/docs/Glossary/Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @cdfortes! Rumo à fluência! 🚀
