### ISSUE TITLE
Resumo da Aula 01-02  à 01-05  da etapa 03

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#775]
## O que são funções - Aula 01-02

- Fazem parte do tipo object
- Seu papel principal é permitir que a gente crie um bloco de código que pode ser invocado e executar quando necessário.

 Por exemplo, o código a seguir define uma função simples chamada square:

```
function square(numero) {
  return numero * numero;
}

console.log(square( 10, 10))
```

------

## Function declaration, function expression e hoisting - Aula 01-03

- Function declaration

```
// function declaration
function sayHi() {
  console.log('oi')
}

// invocação / chamar / executar
sayHi()
```

- Function expression

```
// atribui a função a uma variável

const showFood = function () {
  console.log('pizza')
}

showFood()
```

 **Diferença importante entre as duas**

1. function declaration possui Hoisting (içamento, em português) 
2. function expression não possui Hoisting

  **Hoisting (içamento, em português)** é como se a função fosse movida para o topo do seu código

  *De acordo com o mdn, as declarações de variável e função são colocadas na memória durante a fase de compilação, mas permanecem exatamente onde você as digitou no seu código.*

**exemplo:**

```
function catName(name) {
  console.log('O nome da minha gata é' + name)
}

catName('Lilie')
 
/*
O resultado do código acima é: "O nome da minha gata é Lilie"
*/
catName('Lilie')

function catName(name) {
  console.log('O nome da minha gata é' + name)
}

/*
Mesmo que chamemos a função em nosso código primeiro, antes que a função seja escrita, 
o código ainda funciona. Isso é o hoisting.
*/
```

------

## Argumentos, parâmetros e default parameters - Aula 01-04

```
const myFunc = function (name = 'Jhon', lastName = 'Limonada') {
  /* onde "name" e "lastName" são parâmetros, inicializados com valores defaults, 
caso não se passe os argumentos o resultado não será undefined. */
  console.log(` Oi, ${name} ${lastName}`)
}

myFunc('Nikson', 'Diniz')
// onde "Nikson" e "Diniz" são argumentos
```

------

## Retornando valores e exercícios - Aula 01-05

```
// Retornando valores
// usa-se return para que a constante não fique só no escopo do bloco da função

const double = function  (number) {
  return number * 2
}

const result  = double(3) // 6

const showResult  = function  (value) {
  return `O resultado é: ${value}`
}

console.log(showResult(result)) // O resultado é: 6
```

------

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @NiksonDiniz! Rumo à fluência! 🚀
