### ISSUE TITLE
Etapa 1, nome do vídeo: Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by Sephyros** [roger-melo-treinamentos/curso-de-js-roger-melo#776]
Boa noite @Roger-Melo!
Estava realizando a correção dos exercícios citados no titulo e estava tudo igual a correção, mas quando cheguei ao exercício 21 reparei que as solução era diferente do que eu havia implementado, entendi completamente a lógica usada na correção, gostaria de saber se a minha solução também pode ser considerada correta.
OBS: conforme orientado no video inaugural não utilizei nada de fora do que foi ensinado nas aulas anteriores.

Minha implementação:
```js
const name = "walter white";
let newName = name.replace('w','W').replace('w','W');
```

Correção do exercicio:
```js
const name = "walter white";
let newName = name[0].toUpperCase() + name.slice(1,6) + ' ' + name[7].toUpperCase() + name.slice(8)
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Sephyros.

Quando houver diferentes formas de resolução, tente captar os princípios que usei para resolver daquela forma, pois eles serão potencializados em exercícios seguintes. 

Observe que um dos itens do exercício especifica para não digitar a nova string manualmente. O objetivo é você treinar o uso dos métodos `toUpperCase` e `slice` apresentados nas aulas anteriores.

Então se vc conseguir implementar usando esses métodos, tá tudo certo =)

**Comment by Sephyros** [comment]
Compreendido, vou ter isso em mente nos próximos exercícios! Rumo a fluência!

**Comment by Roger-Melo** [comment]
Rumo à fluência @Sephyros! Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova =)
