### ISSUE TITLE
Correção de exercícios de módulos anteriores nos módulos seguintes

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#777]
Fala Roger, blz?

Tem uma coisa na plataforma que me incomoda muito, pode ser só um toque meu com organização, sei lá, não sei se sou só eu acho isso, talvez, mas como no título já deu pra sacar a ideia do que seja, acho bem poluído os módulos seguintes conter correções de módulos passados, aos mais ansiosos por novos módulos acaba sendo um pouco frustrante entrar em um módulo como por exemplo o de Orientação a Objetos e se deparar com 12 aulas antes de tocar no assunto de Orientação a Objetos... seria possível colocar cada correção de exercício relacionado ao seu módulo e manter eles somente dentro do mesmo?
 
Valeu Roger, seu curso até agora é o melhor que eu já fiz, estou no módulo 12 e vejo que estou quase no fim e já bate um desespero, espero que você não pare nunca com o curso e que "quem sabe um dia" ensine React e Node a fundo =)
Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RicarGit. Valeu pelo feedback =)

A ideia é que a resolução de exercícios de uma aula aconteça no início da próxima mesmo. É só um detalhe técnico, acho que não vale dar muita atenção a isso.

Eu sei que bate uma certa ansiedade em ver o quevem após a correção dos exercícios. Mas antes de aprender coisas novas, eu preferiria ter certeza de que masterizei o que foi visto até aqui, e isso é feito através dos exercícios e correções =)

**Comment by RicarGit** [comment]
Sem problemas, Roger, é só um toque meu mesmo, não interfere em nada, só visualmente mesmo haha

**Comment by Roger-Melo** [comment]
Tranquilo @RicarGit =)

Por agora vou fechar a issue, mas no que precisar, é só abrir uma nova =)
