### ISSUE TITLE
Como posso saber se a função retorna uma promise?

### ISSUE THREAD

**Issue by FillipeDiord** [roger-melo-treinamentos/curso-de-js-roger-melo#7775]
### Etapa da aula

11

### Nome da aula

A fetch API - Aula 05-03

### Link da aula

https://app.nutror.com/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1332937

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Roger,

Como posso saber se a função retorna uma promise sem precisar olhar a implementação da função?

Obrigado pelo suporte :)

@Roger-Melo

**Comment by Roger-Melo** [comment]
@FillipeDiord não me lembr de um caso em que eu não pude olhar a implementação de uma função, ou a documentação dela. Geralmente, isso não é uma restrição.

Funções async, por exemplo, retornam uma promise por padrão. 

Mas respondendo a pergunta, uma forma de saber se a função retornou uma promise é invocar ela dentro de um console.log.

**Comment by FillipeDiord** [comment]
@Roger-Melo obrigado pela resposta!
