### ISSUE TITLE
Como posso tornar uma função assíncrona em função bloqueante?

### ISSUE THREAD

**Issue by FillipeDiord** [roger-melo-treinamentos/curso-de-js-roger-melo#7779]
### Etapa da aula

11

### Nome da aula

Async/await - Aula 05-04

### Link da aula

https://app.nutror.com/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/aula/1338555

### Descreva a dúvida. DICA - deixe um passo a passo para a reprodução do problema, o comportamento que você esperava e o comportamento que está tendo.

Roger,

Uma pergunta sobre o contexto global, quando temos várias declarações de funções e invocações e algumas delas não são funções assíncronas e não quero que essas funções que não assíncronas sejam executadas primeiramente, mas sim as funções assíncronas e após elas executar as funções síncronas o que posso fazer para tal resultado?

Exemplo de código:

``` 
const teste = async () => {
	const response = await fetch('https://jsonplaceholder.typicode.com/users');
	return await response.json();
}

async function executarTeste() {
    const users = await teste();
    console.log(users);
}

console.log('1');
console.log('2');

executarTeste();

console.log('3');
console.log('4');
```

Ao executar este código, você verá que os console.log serão executados primeiro, mas eu não quero isso, tem alguma forma de executar nessa sequência da invocação de funções?

@Roger-Melo

**Comment by Roger-Melo** [comment]
@FillipeDiord qual seria o caso de uso para fazer isso?

Tem como fazer muita gambiarra com setTimeout e executar algo só depois de um determinado tempo. Mas novamente: gambiarra. 

A ideia é justamente deixar síncrono e assíncrono de acordo com o que faz sentido. Não me lembro de um caso em que tive que fazer este tipo de modificação no fluxo de dados. 

Dito isso, dá uma olhada por favor nos 46:23 d'A Aula mais importante do CJRM (primeira aula na plataforma). Lá, eu recomendo tirar as dúvidas no Telegram e explico porque é mais efetivo para os alunos tirarem dúvidas lá =)

**Comment by FillipeDiord** [comment]
Vou visualizar sim!
