### ISSUE TITLE
Dificuldade com a lógica do JS.

### ISSUE THREAD

**Issue by higoroficial-city** [roger-melo-treinamentos/curso-de-js-roger-melo#78]
Olá professor, estou com dúvidas não em um exercício em específico, mas no geral, pois comecei a etapa 3 a alguns dias mas estou  agarrado nos primeiros exercícios, porque não quero simplesmente assistir a resposta e não ter tentado completá-los eu mesmo.
  O que usar, quando usar e como usar o que o JS tem a oferecer, esse é o meu maior problema. Aprender a lógica vem com o tempo ou existem livros, vídeos e outros materiais quem podem me ajudar mais rapidamente?

  Agradeço desde já a resposta!

**Comment by Roger-Melo** [comment]
Oi Higor.

> Olá professor, estou com dúvidas não em um exercício em específico, mas no geral, pois comecei a etapa 3 a alguns dias mas estou agarrado nos primeiros exercícios, porque não quero simplesmente assistir a resposta e não ter tentado completá-los eu mesmo.

Como você está na etapa 3 (fundamentos da linguagem), provavelmente a "dúvida geral" escalou à partir do momento em que uma dúvida surgiu em um exercício passado específico e você não abriu uma issue para saná-la. Não acumule dúvidas.

Não encare o problema como um todo. Quebre-o em partes, como vou descrever abaixo.

### Faça uma revisão

1. Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios;
2. Quando travar em um exercício, assista a correção, apague o código e implemente-o novamente, sozinho. Se não conseguir implementar sem olhar a correção, veja a correção. Nessa fase, provavelmente você notará que suas dúvidas sobre o exercícios vão ficar mais específicas. Após sanar a dúvida, apague e refaça, sozinho.
3. Execute o item acima quantas vezes forem necessárias para que seu cérebro entenda o padrão do exercício;
3. Após executar os itens acima, parta para o próximo exercício;
4. Faça isso até chegar no ponto em que você está agora. As chances são de que você estará mais seguro para fazer os exercícios atuais.

E claro, se mesmo executando o passo-a-passo acima alguma dúvida permanecer, pode abrir uma issue aqui que te ajudo =)

> O que usar, quando usar e como usar o que o JS tem a oferecer, esse é o meu maior problema. Aprender a lógica vem com o tempo ou existem livros, vídeos e outros materiais quem podem me ajudar mais rapidamente?

Não se preocupe com questões como "quando usar e como usar o que o JS tem a oferecer" e "lógica do js". Apenas faça o que recomendei acima. Foque em resolver um exercício de cada vez, sem pressa.

### O que você precisa já está no treinamento

Você está no treinamento que mais potencializa a sua chegada na fluência na linguagem. Cada milímetro do conteúdo foi pensado para que você atingisse esse objetivo. Então foque nele. Depois, mais à frente, chegará o momento em que eu vou recomendar vídeos, livros e outros materiais de estudos. Mas definitivamente não é agora.

Siga o método, implemente o que recomendei acima e me conte os resultados.

No que precisar, estou à sua disposição =)

@higoroficial-city

**Comment by higoroficial-city** [comment]
Pois é Roger, agora me lembro de você falar sobre quebrar o problema em partes, o que realmente me falta aqui. Vou implementá-lo a partir de agora.
Obrigado!

**Comment by Roger-Melo** [comment]
Legal, Higor.

Vou fechar a issue por agora e no que precisar é só abrir uma nova =)
