### ISSUE TITLE
Resumo da Aula Argumentos, parâmetros e default parameters da etapa 03

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#781]
# Argumentos, parâmetros e default parameters

- muitas vamos ter que passar valores para nossas funções
- os valores passados na declaração da função são chamados de **parâmetros**
- são **variáveis locais** que estão restritos ao bloco de código da função
- os valores passados na invocação da função são chamados de **argumentos**
- caso não passarmos nenhum argumento à uma função que tenha parâmetros, quando executada a variável mostrará undefined (aula 3 esta 01)
- para prevenir isso podemos utilizar **default parameters** na declaração da função
- assim ao invocarmos a função sem nenhum argumento será executada com os valores defaults
- podemos passar múltiplos argumentos e parâmetros
- a ordem dos argumentos e parâmetros devem se corresponder respectivamente na invocação e na declaração
- são separados por vírgula
- mas dentro do bloco a ordem não importa

```jsx
const myFunc = function(name, lastName){
	console.log(`oi, ${name] ${lastName}!`)
}

myFunc() 
// mostrará oi, undefined undefined
myFunc('Carlos', 'Fortes') 
//mostrará oi, Carlos Fortes

//default parameters

const myFunc2 = function(name='Jon', lastName='Barros'){
	console.log(`oi, ${name] ${lastName}!`)
}

myFunc() 
// mostrará oi, Jon Barros!
myFunc('Carlos')
 //mostrará oi, Carlos Barros! ou seja, o argumento vai subscrever 
//a default parameter
```

### Referências MDN

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @cdfortes. Rumo à fluência 🔥
