### ISSUE TITLE
Aplicação: Quiz do futebol

### ISSUE THREAD

**Issue by gustavo-viana** [roger-melo-treinamentos/curso-de-js-roger-melo#7823]
### As cores da sua versão da aplicação são diferentes das cores da aplicação mostrada na aula?

Sim

### Sua aplicação contém funcionalidades que não foram mostradas nas aulas da aplicação?

Sim

### Sua aplicação contém funcionalidades da linguagem que não foram mostradas no CJRM até aqui?

Não

### Link do repositório da aplicação (ou pasta pública no Google Drive)

https://drive.google.com/drive/folders/1QGuXvv_cnpPA5aMFo_IIUj8dnNkKuDMg?usp=drive_link

### Sem dificuldades

**Comment by Roger-Melo** [comment]
O "(marque errado)" no h2 pode confundir as pessoas. Eu mesmo não entendi.

O array userAnswers pode ser refatorado com menos repetições. 

Antes:

```js
  const userAnswers = [
    form.inputQuestion1.value,
    form.inputQuestion2.value,
    form.inputQuestion3.value,
    form.inputQuestion4.value,
  ]
```

Depois:

```js
const getUserAnswers = () => {
  const answers = []
  correctAnswers.forEach((_, i) => answers.push(form[`inputQuestion${i + 1}`].value))
  return answers
}

form.addEventListener('submit', event => {
  event.preventDefault()

  const userAnswers = getUserAnswers()
  // ...
}
```

Em breve vc conhecerá o método map e poderá fazer a operação dentro da função `getUserAnswers` sem precisar usar `forEach`.

`CheckAnswer` não precisa do "C" maiúsculo, pq não é uma função construtora. 

Não deixe console.log em seu código nem faça qualquer aviso da aplicação ser exibido nele, pois o usuário comum não vai abrir o console enquanto usa a aplicação. 

Não use dois idiomas para nomear suas variáveis/funções. Escolha um. 

Pra evitar ter que tratar campo sem resposta marcada, é só deixar um input de cada alternativa marcado por padrão, como mostrado nas aulas. 

Não nomeie o parâmetro do callback do forEach com o mesmo nome do array. O parâmetro recebe um item do array, então pode ser nomeado como singular:

```js
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === correctAnswers[index]) {
      // ...
    }
  })

  // ...
```

A função acima retorna a pontuação, então pode ser nomeada como `getScore` e a const que recebe o retorno dela pode se chamar `score`:

```js
form.addEventListener('submit', event => {
  // ...
  const score = getScore(userAnswers)
  // ...
}
```

Não precisa usar if e repetir innerHTML para obter a mensagem a ser inserida na tela. Vc pode usar objeto para isso.

Antes:

```js
  if (score === 100) {
    scoreMessage.innerHTML = `Ainda bem que tu sabe o BRAZA era fora do normal! Acertou ${score}%`
  } else {
    scoreMessage.innerHTML = `Deu mole, errou feio, errou rude! Brasil dominava! Acertou ${score}%`
  }
```

Depois:

```js
const getScoreMessage = score => ({
  100: `Ainda bem que tu sabe o BRAZA era fora do normal! Acertou ${score}%`
})[score] || `Deu mole, errou feio, errou rude! Brasil dominava! Acertou ${score}%`

form.addEventListener('submit', event => {
  // ...
  const message = getScoreMessage(score)

  scoreMessage.innerHTML = message
})
```

Se vc ainda não chegou no ponto em que mostro como funciona a técnica que a função `getScoreMessage` está usando, não se preocupe. Vai chegar. 

Ficaram claras as observações?

@gustavo-viana

**Comment by gustavo-viana** [comment]
Clarrissimas, mais foi só lenhada kkkkk, brincadeiras a parte, entendi oque quis dizer, talvez eu tenha feito de forma desleixada e me concentrado mais na funcionalidade da piada de corrigir o formulário caso a pessoa não marcasse a resposta, obrigado mestre !
