### ISSUE TITLE
Resumo da Aula Conversão de Tipos 04-03 da etapa 01

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#788]
@Roger-Melo
![conversao de tipos](https://user-images.githubusercontent.com/35525950/120695613-f8448f00-c481-11eb-8c5a-b33a95c9eaec.jpeg)

**Comment by Roger-Melo** [comment]
Excelente @AnaCosta29. Rumo à fluência 🔥
