### ISSUE TITLE
Etapa 06 - Correção dos exercícios da aula 04 da etapa 05 - Aula 01-01

### ISSUE THREAD

**Issue by naldowebdeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#79]
Roger, estou em correia vida de desenvolvedor não é
fácil, tem que estudar bastante e trabalhar bastante.

Em primeiro lugar estou acompanhando as aulas seguindo
um ritmo mais lento para ir assimilando, eu tento resolver do 
meu jeito e depois vejo a correção.

Por exemplo nesse exercício, tem um array com objetos dentro,
esse modo de organização de dados é um json?

Sempre fico nessa duvida, um array com objeto pra parece um json.

Quando vejo os dados já penso no forEach e ele não funcionou por q
não é um array, mais acabei colocando em objeto, gambiarra mais queria
muito fazer funcionar.

Essa função some, ele percorre qualquer tipo de dado, array, objeto?

Meu código
/*
  07

  - Se o array de pessoas abaixo conter, no mínimo, um(a) Front-end developer,
    exiba a mensagem abaixo no console.

    "O array people contém, no mínimo, um(a) Front-end developer."
*/

```js

const people = [
  { id: 1, name: 'Pedro Henrique', profession: 'Dentista' },
  { id: 2, name: 'Fábio Alexandre', profession: 'Físico' },
  { id: 3, name: 'Thiago Ferreira', profession: 'Veterinário' },
  { id: 4, name: 'Marcelo Antonio', profession: 'Matemático' },
  { id: 5, name: 'Camilla Midori', profession: 'Engenheira Civil' },
  { id: 6, name: 'Gustavo D\'Aqui', profession: 'Gerente de Marketing' },
  { id: 7, name: 'Ana Paula', profession: 'Front-end developer' },
  { id: 8, name: 'Matheus Manucci', profession: 'Piloto' },
  { id: 9, name: 'Hamilton Silva', profession: 'Advogado' }
]

people.forEach(item => {
  //console.log(item.profession)
  
  const frontend = 'Front-end developer'
  const professions = [item.profession]
  //console.log(professions)
  
  const verificaProfession = professions.some(profession => profession === frontend)
  
  if(verificaProfession){
    console.log("O array people contém, no mínimo, um(a) Front-end developer.")
  }
  
})


``` 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ednaldo.

> Por exemplo nesse exercício, tem um array com objetos dentro, esse modo de organização de dados é um json?

Não. É apenas um array com objetos JavaScript. Pode ficar tranquilo que nas etapas posteriores, você encontrará as aulas em que o `JSON` será apresentado =)

> Quando vejo os dados já penso no forEach e ele não funcionou por q não é um array, mais acabei colocando em objeto, gambiarra mais queria muito fazer funcionar.

Na verdade o `forEach` é um método de array, não existe um forEach para objetos. Mas existem formas de percorrer um objeto sim, elas são mostradas em aulas de etapas mais avançadas.

> Essa função some, ele percorre qualquer tipo de dado, array, objeto?

O `some` é um método apenas de array.

Como eu disse na aula de [apresentação](https://youtu.be/fxQNvGGd3tg?t=1128) do some, o `some` itera por um array e verifica se pelo-menos 1 item desse array atende à condição especificada na função de callback dele.

"Iterar" e "percorrer" são sinônimos. Então observe que no código abaixo,

```javascript
people.forEach(item => {
  const frontend = 'Front-end developer'
  const professions = [item.profession]
  
  const verificaProfession = professions.some(profession => profession === frontend)
  
  if (verificaProfession) {
    console.log("O array people contém, no mínimo, um(a) Front-end developer.")
  }
})
```

podemos eliminar o `forEach` porque como o `some` já vai percorrer o array, não é necessário usar o `forEach` para isso.

Observe que se simplesmente inserirmos um `console.log(person)` no callback do `some`, à cada vez que a função de callback é executada o item do array pro qual a função está sendo executada é exibido no console:

```javascript
people.some(person => console.log(person))

/*
{ id: 1, name: 'Pedro Henrique', profession: 'Dentista' }
{ id: 2, name: 'Fábio Alexandre', profession: 'Físico' }
// ...
*/
```

Ou seja, o array foi percorrido, a função de callback foi executada para cada item do array.

Só que eu coloquei o `console.log` ali apenas para exemplificar. Não faça isso ao usar o `some`.

A função de callback do some é executada para cada item do array até que o item que faz a função retornar um valor `truthy` seja encontrado. Quando a função retorna um valor `truthy`, o `some` retorna `true` imediatamente. Se a função não retorna um valor `truthy`, o `some` retorna `false`.

Então perceba que são dois métodos de array com propósitos diferentes. Você usará o `some` quando precisar percorrer um array e verificar se pelo-menos 1 item do array atende à condição especificada no retorno da função.

Já o `forEach` será usado em casos onde é necessário percorrer o array, executar alguma ação para cada item mas, não retornar um valor. Perceba que todas as vezes que uso o `forEach`, não especifico um `return` no callback dele, até porque o `forEach` nunca retorna um valor.

À medida em que você for avançando no treinamento, irá conhecer métodos distintos de array. Cada um tem o seu propósito. Quando um método for apresentado, sempre fique atento ao momento em que eu digo "porquê" esse método existe. Isso te dará um norte de quando usar ou não usar o método =)

Ficou mais claro?

@naldowebdeveloper

**Comment by naldowebdeveloper** [comment]
Roger, estou ciente!

**Comment by Roger-Melo** [comment]
Legal Ednaldo.

Já que ficou mais claro, vou fechar a issue mas no que precisar, é só dar o toque =)
