### ISSUE TITLE
Aplicação: Todo list

### ISSUE THREAD

**Issue by Thesamuel01** [roger-melo-treinamentos/curso-de-js-roger-melo#792]
Olá Roger!

Espero que eu esteja no tempo estimado para enviar a aplicação, pois nas últimas semanas foi um pouco corrido por aqui, mas segue minha aplicação todo list para a análise. Diferente da minha última aplicação me atentei a utilizar somente as features utilizadas em aula.

**Facilidades encontradas:**
- Buscar um elemento do HTML;
- Saber quando utilizar os métodos de arrays (filter, map e reduce);
- Utilizar o event delegation.

**Dificuldades encontradas:**
- Realizar a filtragem dos todos, como já havia feito visto de outra forma utilizando regex, quando fui fazer da forma lecionada até o momento em aula, confundi alguns conceitos.
- Refatorar o código, na função que filtra os `todos`, percebi que há código repetido e tentei refatorar, mas não consegui de uma forma que fique legível e concisa .

Link para o GitHub da aplicação: 
- [GitHub Todo List App](https://github.com/Thesamuel01/todo-list)
- [Deploy Todo List App](https://webapp-todo-list.netlify.app/)

Obrigado e aguardo seu feedback!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Thesamuel01.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Thesamuel01!

Parabéns pelo esforço em construir a segunda aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Lógica

### Input de busca

Observe que ao inserir `ass` no input de busca, 'Assistir Breaking Bad' não é exibido.

Isso aconteceu por que durante a filtragem dos to-dos, o `toLowerCase()` não foi usado. E isso faz com que `ass` não dê match com `Ass` (início da string do 1º to-do). No momento da comparação, as strings nas quais `todo.textContent` e `filterInput` resultam precisam ter todos os caracteres em lower case ou upper case =)

## Organização de código

### Nomes de variáveis e funções

"Blank" pode ser traduzido como "em branco", então `isFormBlank` precisaria ter outro nome, por que ela está sendo usada como condição de um `if` que deve ser executado quando o input está preenchido. Na real, como `inputValue.length` é uma expressão legível e não-extensa, ela pode ser referenciada como condição do `if`.

Como não é o ícone que está sendo deletado mas sim o todo, `isToDeleteIcon` pode ser renomeada para `shouldRemoveTodo`, por exemplo.

`filterElements` acaba sendo vago. Você pode ser mais específico em relação do que se trata esses elementos. Então eu renomearia essa const como `filterTodos`. O mesmo vale para a `removeElement`.

Como `filterInput` está armazenando **o valor** do input (e não a referência do input), ela pode ser renomeada como `filterInputValue`. Como o nome da função já diz do que ela se trata, eu renomearia ela para apenas `inputValue`.

`filterForm` não armazena um form, mas sim um `input`. Então um nome mais adequado seria `filterInput` ou `inputSearchTodo`.

### Refatoração

Sobre a refatoração, nas aulas seguintes você verá uma forma de melhorar o código =)

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
@Thesamuel01 vou fechar a issue mas no que precisar, fique à vontade para perguntar =)
