### ISSUE TITLE
Resumo da Aula Xxxxxxxxx da etapa XX

### ISSUE THREAD

**Issue by ederdaniel22** [roger-melo-treinamentos/curso-de-js-roger-melo#793]
Resumo aula 01-01 a 01-06: Neste módulo demos os primeiros passos em JavaScript, aprendemos a configurar o ambiente de estudos.
Começamos a criar um html e incluir a tag <script>.
Criamos o primeiro app.js, incluímos os primeiros comandos em JS e fizemos o link com html.
Aprendemos o que é uma string e como manipula-las, aprendemos ainda o que são numbers e booleans.
Trabalhamos com o terminal do browser.
Ao final fizemos os primeiros exercícios do curso.
O resultado deste módulo está postado em:
https://github.com/ederdaniel22/JS-RM-modulo01

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @ederdaniel22! Rumo à fluência 👊🏻 

Ps: lembre-se de especificar o nome da aula no título da issue =)
