### ISSUE TITLE
Resumo da Aula Arrays 03-02 da etapa 01

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#794]
# Array
![](https://img.shields.io/badge/DEV.TO-Artigo-lightgrey)
https://dev.to/junioralvesbr/basicos-de-arrays-1305

Array é uma sequencia não ordenada de dados, cujo os elementos residem em um local especifico na memória do computador e podem se acessado através de index.

No javaScript a forma mais comum de declarar um a array é atribuindo ele a uma variavel.

```javascript
const meuArray = []
```
Em que os colchetes (brackets) é o proprio array.

Para declarar os valores do array, inserimos cada um dos valores dentro dos colchetes separados por virgula.

```javascript
const meuArray = ['valor1', 'valor2', 3]
```

É possivel construir arrays com qualquer tipo de valor misturados como strings, numbers e objetos. Porem é recomendado que sejam construido arrays com valores que tenham a mesma relação como no exemplo a baixo.

```javascript
const minhasFrutas = ['banana', 'abacaxi', 'laranja']
const idades = [20, 10, 30]
```

## Index
Quando um array é criado, cada posição do array é relacionado a um index que por padrão começa em "0", e aumenta de forma linear. Ou seja a primeira posição do array tem o index 0, a segunda posição tem o index 1, o segundo tem o index 2 e assim por diante.
Portanto para acessarmos o valor "laranja" do nosso array "minhasFrutas" basta colocar entre colchete o index da posição que este valor está.

```javascript
console.log(minhasFrutas[2])
'laranja'
```

OBS
``
muitos confundem a posição do valor com o index. Veja:
``
``
O valor 'laranja' do array 'minhasFrutas' é o terceiro valor do array, mas esta na posição de index 2.
``
``
Isso se dá porque o index de um array começa em "0". Portanto
``
```javascript
console.log(minhasFrutas[0])
'banana'
```

## Métodos
Para manipulação de arrays temos vários métodos que facilita nossa vida no dia dia. Veja alguns:

### Ver tamanho total do array
```javascript
console.log(minhasFrutas.length)
```

### Adicionar um item ao final de um array
```javascript
minhasFrutas.push('limão')
console.log(minhasFrutas)
['banana', 'abacaxi', 'laranja', 'limão']
```

### Remover um item do final do array
```javascript
minhasFrutas.pop()
```

### Procurar um indice no array
```javascript
minhasFrutas.indexOf('abacaxi')
```

### Adicionar ao início do Array
```javascript
minhasFrutas.unshift('Morango')
```

### Remover ao início do Array
```javascript
frutas.shift()
```

Estes são os métodos basicos de manipulação de array.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @JuniorAlvesbr! Rumo à fluência 👊🏻
