### ISSUE TITLE
Resumo da Aula 01 da etapa 01

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#795]
# Variáveis

- São utilizadas para armazenar 'valores';
- Esses valores podem ser do tipo:
    - **number** (*números em geral*);
    - **string** (*textos*);
    - **booleans** (*true* ou *false*);
    - **arrays** (*conjunto de items de qualquer tipo*);
    - **objects** (*conjunto de items de qualquer tipo*);

## Utilizando o 'let'

Podemos declarar uma variável, utilizando a seguinte sintaxe:
``` let age = 31; ``` (lê-se: a **variável** ***"age"*** recebe o valor numérico **31**)

Se após declarar a variável **"age"**, eu fizer: ``` age = 35```. Isso significa que eu estarei reatribuindo para a variável **"age"**, o valor de **35**.

### Observação
Isso só é possível, pois declaramos a variável **age**, utilizando o **let**. Isso significa que é possível alterar o valor atribuído à variável.
Se tivéssemos feito ```const age = 31```, e tentássemos reatribuir o valor de **"age"** (fazendo  ``` age = 42```, por exemplo), obteríamos um erro, pois dizemos que **"age"** é uma **constante**, ou seja, ela **não pode ser alterada**.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Isso aí @raphaelprsilva! Rumo à fluência 👊🏻
