### ISSUE TITLE
Resumo da Aula Factory functions e composição de objetos - Aula 03-09 da etapa 14

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#798]
Oi professor, tudo bom?

Tenho 2 dúvidas. Foi falado em aula que devo utilizar construtores todas as vezes que preciso criar múltiplos objetos com características semelhantes. A partir de quantos objetos com as mesmas características que devo ter na minha aplicação para ligar um sinal de alerta e dizer que preciso de um construtor? 
A segunda dúvida: há o problema de criarmos instâncias que partilham métodos que realizam a mesma ação, mas que estão em posições diferentes na memória. Mas, com factory functions parece que esse problema também "reaparece" - digamos assim - uma alternativa para contornar essa redundância de métodos poderia ser definindo o protótipo dessa instância da factory function antes mesmo de retorná-la? É uma boa prática ficar acessando e manipulando o prototype de um objeto quando utilizamos as factory functions?

@Roger-Melo

**Comment by Roger-Melo** [comment]
> Foi falado em aula que devo utilizar construtores todas as vezes que preciso criar múltiplos objetos com características semelhantes.

Constructor/class é uma forma, factory function é outra. No fim das contas, são apenas mecanismos de reaproveitamento de código e você pode escolher qual delas prefere. Eu recomendo factory functions =)

> A partir de quantos objetos com as mesmas características que devo ter na minha aplicação para ligar um sinal de alerta e dizer que preciso de um construtor? 

Não existe um número específico, você perceberá quando estiver duplicando muito código para criar objetos. Mas na real, esse tipo de situação é mais provável que aconteça ao construir uma lib ou um framework, e não em aplicações web.

> A segunda dúvida: há o problema de criarmos instâncias que partilham métodos que realizam a mesma ação, mas que estão em posições diferentes na memória.

Na aula 02-06 da etapa 15 você verá como criar factory functions aproveitando a mesma referência do método para todos os novos objetos criados =)

> É uma boa prática ficar acessando e manipulando o prototype de um objeto quando utilizamos as factory functions?

Se você manipula o prototype **do objeto** que a factory cria e não o prototype da própria factory, tá tudo certo. Por baixo dos panos, o JS já faz isso. Prototypes são acessados toda vez que vc cria um objeto e usa uma propriedade/método da linguagem. 

```javascript
// filter é um método do prototype do array
[1, 2, 3].filter(num => num >= 2)
```

Mas como eu disse, o uso explícito de prototype em uma aplicação não é algo comum. Dificilmente você vai precisar de um objeto personalizado, isso seria mais útil em libs, ou algo do tipo =)

Ficou mais claro?

**Comment by sou-gabriel** [comment]
> Ficou mais claro?


100% professor. Obrigado por me ajudar! 😀
