### ISSUE TITLE
Resumo da Aula 03- 02 da etapa 01

### ISSUE THREAD

**Issue by bivar37** [roger-melo-treinamentos/curso-de-js-roger-melo#799]
**Arrays**
 Pra que serve?
Armazenar uma relação de valores que tem relação entre si.
`let  bible = [ 'mateus','marcos,'lucas','joão']`

Pode também obter só um dos item do array.
```
console.log ( bible[3])
// joão
```
Pode atribuir um novo valor para qualquer item do array
```
bible[3] = 'atos'
console.log(bible)
//(4)["mateus", "marcos", "lucas", "atos"]
```
**Metodos de Arrays**

**_.length_**
Exibe quantidade de itens do array

_**.join**_
Retorna uma string de todos itens do array concatenados por virgula.
```
const joinBible =bible.join()
console.log(bible)
//mateus, marcos, lucas, atos
```

O _join_ pode receber um argumento adicional, um separador.
```
const joinBible =bible.join('|')
console.log(bible)
//mateus|marcos|lucas|atos
```
Um hifem tambem pode ser um argumento (-)

**_.indexOf_**
Esse metodo pode ser usado da mesma forma que se usa em uma string

Nota : Se passar por argumento um item que não tenha no array, o -1 retorna.

**_.concat_**
Pode concatenar dois arryas, formando um só, com os itens dos dois arrays.
```
const moreBiblie = bible.concat('romanos', '1 Coríntios")
console.log(moreBible)
////(6)["mateus", "marcos", "lucas", "atos","romanos", "1 Coríntios"]
```
Nota : Esse método não modifica o array original , **_bible_**

**_.push_**
Adiciona itens no array original, e retorna a quantidade de itens do array.
```
const pushBible = bible.push('2 Coríntios")
console.log(pushBible)
// 5
```
```
console.log(bible)
 (5)  ["mateus", "marcos", "lucas", "atos","2 Coríntios"]
```
Alterou o valor original , ou seja mutação de valores.

**_.pop_**
Remove o ultimo item do array e retorna o item modificando o array original.

const popBible = bible.pop()
console.log(popBible)
//2 Coríntios

console.log(Bible)
// (4)  ["mateus", "marcos", "lucas", "atos"]

Bivar
________________________________________________________________________________________________________________________________________

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @bivar37! Vamo que vamo, rumo à fluência! 🔥
