### ISSUE TITLE
Duvida do exercício 20

### ISSUE THREAD

**Issue by tuxpedro** [roger-melo-treinamentos/curso-de-js-roger-melo#8]
Olá @Roger-Melo! Tudo bom?

Não consigo compreender a diferença entre os seguintes trechos de código

`const timer = setInterval(() => {
    if (stopCounter) {
      clearInterval(timer)
      counter = 0
      modifiesValueCounter(counter)
      return
    }
    counter++
    modifiesValueCounter(counter)
  }, 1000);`

Acima a `const timer` recebe a função `setInterval()` e dentro da função eu chamo timer compreendo que timer guarda o id gerado pela função e acredito que nesse trecho temos um conceito de recursividade.

Os mesmo conceitos do código acima se aplica ao código abaixo? 

`const returnNumber = valor => valor * 3;
const number =  (number => {
 console.log(number)
});
number(returnNumber(9));`

**Comment by Roger-Melo** [comment]
Olá @tuxpedro!

Recursão é fazer uma função invocar a si mesma.

Uma função recursiva possui duas premissas:

1. Invocar a si mesma;
2. Possuir uma condição para parar de se invocar.

---

[Neste vídeo](https://youtu.be/FgATjBEvmSw), falo sobre o que acontece por baixo dos panos em uma recursão.

Os dois trechos de código que você mencionou não possuem recursão.

No 1º trecho, a invocação do `clearInterval` apenas recebe a referência da `const timer` (que como você sabe, armazena o id que a invocação do `setInterval` retorna).

Ou seja, o fato do `clearInterval` receber `timer` como argumento não quer dizer que a `timer` irá se invocar.

Observe que se criarmos uma função que exibe no console sua própria referência (o que não faz muito sentido), o output é a própria declaração da função.

```javascript
const doSomething = () => {
  console.log(doSomething)
}

doSomething()
/*
() => {
  console.log(doSomething)
}
*/
```

Um exemplo de recursão utilizando o `setTimeout`:

```javascript
let counter = 1

function incrementCounter () {
  counter++

  if (counter > 5) { // condição de parada
    return
  }

  setTimeout(incrementCounter, 1000)
  // incrementCounter invoca a si mesma (sabemos que o setTimeout invoca a função do 1º argumento)
}

incrementCounter()
```

Se não tiver ficado claro, é só dar o toque que tento explicar de outra forma.

P.s recursão é um dos assuntos que veremos em etapas mais avançadas do curso, quando conversarmos sobre programação funcional =)

**Comment by Roger-Melo** [comment]
@tuxpedro, vou fechar a issue, mas qualquer dúvida que surgir é só chamar!
