### ISSUE TITLE
Etapa 11, Fazendo requests HTTP - Aula 02-03

### ISSUE THREAD

**Issue by GoharaJunior** [roger-melo-treinamentos/curso-de-js-roger-melo#80]
Roger esatava vendo essa aula e me lembrei do livro (Refatoração), no caso o livro tem arquivos '.json' 

Os dados estão aramazenados em 'plays.json & invoices.json'

Eu queria acompanhar o livro escrevendo e vendo os resultados, teria como puxar esses dados de arquivos '.json' igual é explicada nessa aula ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gohara.

Na aula [Trabalhando com JSON (JavaScript Object Notation) - Aula 03-04](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/1255410) eu mostro como fazer requests para obter dados JSON que estão no diretório do seu projeto.

Porém, se você apenas pular para essa aula, pode acabar se confundindo, pois ela exige conhecimentos prévios que você ainda não possui por ainda não ter visto aulas anteriores a ela. Sequência é importante.

Então o que eu recomendo é que você continue seguindo as aulas do treinamento e não foque muito no livro por agora. Ele usa, por exemplo, features de etapas mais avançadas que você ainda não viu, como classes.

Quando você estiver em etapas mais avançadas, estará mais treinado e entenderá melhor conceitos apresentados no livro =)

@GoharaJunior

**Comment by GoharaJunior** [comment]
Entendi, o outro você também acha melhor eu ler mais para frente pra não confundir muita coisa ?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Quero mais contexto antes de responder essa pergunta =)

Como está a sua taxa de acertos nos exercícios?

@GoharaJunior

**Comment by GoharaJunior** [comment]
Eu estou me dedicando umas 3 horas por dia e a taxa de acerto está um pouco a a cima da metade. São muitas info então sempre estou revendo conteúdo e refazendo exercícios dos módulos que errei bastante.

**Comment by Roger-Melo** [comment]
Show. 

Foque em melhorar a taxa de acerto nos exercícios. Principalmente nos últimos exercícios das listas de exercícios, que são os mais complexos.

Sempre seguindo [esse](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661) passo-a-passo quando ver (na correção) que errou um exercício ou travou nele =)

Sacou a ideia?

@GoharaJunior

**Comment by GoharaJunior** [comment]
Pode deixar, irei voltar em alguns módulos específicos e só vou sair deles quando acerta todos os exercícios hehe 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só dar o toque =)
