### ISSUE TITLE
Resumo da Aula A Condicional Switch 03-04 da etapa 02

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#807]
@Roger-Melo
![condicionalSwitch](https://user-images.githubusercontent.com/35525950/120907346-fc65dd80-c636-11eb-9e57-ac267d2ce920.jpeg)

**Comment by Roger-Melo** [comment]
Excelente @AnaCosta29! Vamo que vamo, rumo à fluência! 🔥
