### ISSUE TITLE
Resumo da Aula 01 da etapa02

### ISSUE THREAD

**Issue by henriquesabarah** [roger-melo-treinamentos/curso-de-js-roger-melo#808]
Controle de fluxo for e while, usamos para executar pequenos códigos repetidas vezes.
Tanto o for como o while fazem a mesma coisa.  A diferença está na sintaxe:
for com 3 condições:
for (inicialização; condição; incremento) {
     bloco de código
}
for apenas uma:  a condição.
while (condição) {
     bloco de código
}
No entanto é preciso declarações de variáveis antes do while e não esquecer de seu incremento para não ficar em um loop infinito.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @henriquesabarah! Rumo à fluência! \o/
