### ISSUE TITLE
Etapa 11, JavaScript assíncrono - Aula 02-04

### ISSUE THREAD

**Issue by lucasfads** [roger-melo-treinamentos/curso-de-js-roger-melo#81]
Duas coisas:
1. Qual a diferença de `response` para `responseText`?
2. Tu tá usando algum plugin pro response aparecer direitinho no console? Pq pra mim aparece como um texto todo grudado, sem quebra de linha nem nada.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Lucas.

A propriedade `responseText` armazena o texto da resposta que a requisição obteve. Não estou usando plugin. Mande um print =)

Sobre a "response", preciso que você me mostre o código para que eu dê uma resposta adequada e contextual ao seu momento no treinamento. Se eu responder exemplificando com um tipo de código que você ainda não viu nas aulas, vou te confundir.

A [aula 02-04 da etapa 11](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascreipt-roger-melo/aula/1189625) não contém uma const `response`. Manda o código aí =)

@lucasfads

**Comment by Roger-Melo** [comment]
Oi Lucas.

A propriedade `responseText` armazena o texto da resposta que a requisição obteve. Não estou usando plugin. Mande um print =)

Se estiver falando da propriedade `XMLHttpRequest.response`, é o seguinte...

A propriedade `XMLHttpRequest.responseText` retorna texto da resposta que a requisição obteve ou `null`, caso a resposta do request não tenha sido obtida com sucesso.

Já a `XMLHttpRequest.response` pode retornar alguma das alternativas abaixo:

- Um objeto javascript; 
- Uma string; 
- Um [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)
- Um [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
- Um [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document)

O valor que a `XMLHttpRequest.response` retorna depende do valor da propriedade [XMLHttpRequest.responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType), que contém o formato de dado que a resposta contém (JSON, texto, etc).

Ficou mais claro?

@lucasfads

**Comment by lucasfads** [comment]
Ah, blz. Acho que agora entendi.

Sobre o formato do response no console. No vídeo o seu aparece assim:
![image](https://user-images.githubusercontent.com/2471569/98886734-5de41600-2473-11eb-88b8-3a681d995021.png)
Enquanto para mim aparece assim:
![image](https://user-images.githubusercontent.com/2471569/98886847-8f5ce180-2473-11eb-89da-6c6249f8b054.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Entendi.

Veja se você está usando a versão mais recente do chrome. O meu é a 86.0.4240.193.

Se o problema permanecer, veja se formatar da forma que mostro [aqui](https://youtu.be/yqAiTyWuSR0?t=48) resolverá o problema =)

@lucasfads
