### ISSUE TITLE
Etapa Aula inaugural, nome do vídeo: 0

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#810]
Oi professor, eu novamente. Tudo bom? espero que sim =)

Estou realizando a aplicação de conversão de moedas da etapa 14, posso começar uma revisão raio-x a partir da etapa atual até a etapa da última aplicação realizada? Esse tipo de engenharia reversa pode me ajudar ou preciso realmente começar do "começo"?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Gabriel.

A [revisão raio-x](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues/96#user-content-revisao-raio-x) sempre começa à partir das baterias de exercícios após a aplicação anterior. 

Como você vai implementar o conversor de moedas e aplicação anterior foi a Weather Application, você pode fazer a engenharia reversa à partir [daqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1451629).

Não faz muito sentido revisar desde a primeira bateria de exercícios da etapa 1, você já domina o que foi exigido lá =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Fechou professor, obrigado 😁
