### ISSUE TITLE
Etapa Semana do Javascript, nome do vídeo: Aula 02

### ISSUE THREAD

**Issue by RosaliGouveia** [roger-melo-treinamentos/curso-de-js-roger-melo#817]
Professor Melo, bom dia. Tudo bem? Sinto até vergonha de dizer isso, mas perdi o caderno de anotações
que continha os dados sobre a metodologia do ATER e estou me sentindo perdida. Tem algum material sobre ele que o senhor possa compartilhar?

Desde já, grata
Rosali Gouveia

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rosali. Essas coisas acontecem, não tem que ter vergonha não =)

Dá uma olhada no vídeo que eu inseri [neste post](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). 

No que precisar, estou à disposição =)

@RosaliGouveia

**Comment by Roger-Melo** [comment]
@RosaliGouveia vou fechar a issue mas no que precisar, fique à vontade para perguntar =)
