### ISSUE TITLE
Etapa 7, Correção dos exercícios da aula 02 da etapa 06 - Aula 01-01

### ISSUE THREAD

**Issue by israelisaque** [roger-melo-treinamentos/curso-de-js-roger-melo#82]
Boa noite Roger, 

No primeiro exercício da etapa 6, sendo mais específico, e exercício 18, você utiliza o setAttribute() para adicionar as classes 'username-help-feedback' e 'username-success-feedback' no parágrafo. Até tudo bem, porém percebi que poderia ser utilizado a propriedade className, pois a mesma sempre sobrescreve a classe adicionada ao parágrafo. 
No código abaixo eu deixei a solução com o className comentada. 
A minha dúvida é por que não utilizamos o className para esse caso? já que ele sempre vai sobrescrever a classe adicionada? 

```
const inputUsername = document.querySelector('#username')
const p = document.createElement('p')

inputUsername.addEventListener('keyup', event => {
  const inputValue = event.target.value
  const usernameRegex = /^[a-zA-Z]{6,}$/

  if (!usernameRegex.test(inputValue)) {
    p.textContent = "O valor deve conter no mínimo 6 caracteres, com apenas letras maiúsculas e/ou minúsculas"
    // p.className = 'username-help-feedback'
    p.setAttribute('class', 'username-help-feedback')
    event.target.insertAdjacentElement('afterend', p)
    return
  }

  p.textContent = "Username válido =)"
  // p.className = 'username-success-feedback'
  p.setAttribute('class', 'username-success-feedback')
  event.target.insertAdjacentElement('afterend', p)
})

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Israel. Na verdade é o 1º exercício da etapa 7 =)

> A minha dúvida é por que não utilizamos o className para esse caso? já que ele sempre vai sobrescrever a classe adicionada?

São duas formas de resolver o mesmo problema.

A diferença é que `element.setAttribute('class', 'some-class')` adiciona ou sobrescreve a classe e `element.className = 'some-class'` apenas adiciona a classe.

Neste caso do exercício, não vai fazer diferença usar um ou outro =)

Ficou claro?

@israelisaque

**Comment by israelisaque** [comment]
Ficou! Obrigado!

**Comment by Roger-Melo** [comment]
Show. Vou fechar a issue, mas no que precisar, pode abrir outra =)
