### ISSUE TITLE
Resumo da Aula 2-3 e 2-4 (strings) da etapa 1

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#824]
## Strings 

// Strings armazenam letras, numeros, todo tipo d ecaracteres 
// incluindo conjunto de todos os anteriores 
// strings são armazenadas por aspas simples ou duplas,
// devendo abrir e fechar com o mesmo tipo de aspas.

console.log('Hello Javascript!') 

const email = 'delgado.elaine03@gmail.com'
console.log(email)

// Qualquer valor passado entre aspas é uma string 
const firstNumber = '9'
const secondNumber = '0'
console.log(firstNumber + secondNumber) // 90, strings concatendas em vez de números somadas

// Concatenando strings 
// Quando usamos o sinal de + entre strings, elas são concatenadas, formando uma única string 
const firstName = 'Elaine'
const lastName = 'Delgado'
let fullName = firstName + lastName
console.log(fullName) //ElaineDelgado 

//Para adicionar espaço entre as strings concatenadas, devemos concatenar tb um espaço vazio:

fullName = firstName + ' ' + lastName
console.log(fullName) 

// Podemos acessar os caracteres de uma string especificando sua posição na mesma
// com o número de sua posição dentro de colchetes (lembrando que Javascript é uma linguagem zero based)
// ou seja, a primeira posição é 0.

console.log(fullName[0]) // retorna o primeiro caractere da string: E 
console.log(fullName[6]) // retorna o sexto caractere da string: o espaço vazio  

// Propriedade 'length' de string: determina o comprimento da string 
console.log(fullName.length) // 14, pois o espaço vazio também é considerado  

// Métodos (funções associadas a objeto ou tipo de dado) que vão executar alguma ação específica 
// Um método possui um nome e é seguido de parênteses, podendo ou não ter um argumento

// Método toUpperCase, toLowerCase (esses métodos não modificam o valor original)
console.log(fullName.toLocaleUpperCase()) // ELAINE DELGADO 
console.log(fullName.toLocaleLowerCase()) // elaine delgado 

const nameLowerCase = fullName.toLowerCase() 
console.log(nameLowerCase, fullName) //elaine delgado Elaine Delgado

// indexOf() procura uma string dentro de outra string 
// passando o valor a ser procurado (o parâmetro) dentro dos parênteses do método
// (o valor a ser procurado deve ser passado dentro de aspas pois também são strings):
const index = email.indexOf('@')
console.log(index) // retorna 16 que é a posição do caractere '@' dentro de email  

## /* MÉTODOS COMUNS DE STRINGS*/
// Aula 2-4 

// lastIndexOf()
// Obtem o index da última ocorrência do caractere passado por argumento 
const email = 'laracroft@rogermelo.com.br'
const lastIndexOfA = email.lastIndexOf('a')
console.log(lastIndexOfA) // 3, pois o último 'a' está na posição 3 da string original

const randomString = 'paralelepipedo'
console.log(randomString.lastIndexOf('p')) 
// retorna 10 pois o 'p' aparece pela última vez na posição 10 da string 

// Método slice(): corta a string passando por argumento as partes da strings a serem 'cortadas'
// Não modifica a string original
 // passando 1 argumento: a string é cortada a partir desse ondex até o final 
 // passando dois números como argumento: a string é fatiada a partir do index referente 
 // ao primeiro argumento até (mas sem incluir) o index do segundo argumento

 console.log(email.slice(10)) /**
 retorna'rogermelo.com.br', pega a partir do caractere de index 10('r') até o final da string
 */

console.log(email.slice(10, 15)) /**
retorna 'roger', a string email foi cortada a partir do index 10 mas parou na 15, não incluindo 
o caractere de index 15  
*/

console.log(email.slice(-11)) /**
retorna melo.com.br, único agumento negativo pega os últimos 11 caracteres da string 
*/

console.log(email.slice(10,-3)) /**
retorna rogermelo.com, a partir do item 10 fatia até o penúltimo não incluido 
* os últimos 3 caracteres  
*/

const professor = email.slice(10,15) // roger
console.log(professor, email) /**
* roger laracroft@rogermelo.com.br (a string original não é modoficada)
*/

const emailClone = email.slice().toLocaleUpperCase()
console.log(emailClone, email) /**
LARACROFT@ROGERMELO.COM.BR laracroft@rogermelo.com.br
* cria uma cópia sem modificar a string original */

// Método replace() 
// Substitui caractere de string passado por argumento 

const emailReplace = email.replace('l', 'y') /**
Substitui o arguemnto passado no 1º argumento pelo argumento passado no 2º  argumento*/

const siteLink = email.replace('laracroft@','www.')
console.log(siteLink, email) /*
* www.rogermelo.com.br laracroft@rogermelo.com.br
* não modifica a string original 
 */ 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ElaineDelgado! Rumo à fluência!!! 💥
