### ISSUE TITLE
Resumo da Aula Query selector & query selector all - Aula 01-07da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#825]
Para manipularmos um objeto do DOM, primeiro é preciso decidir qual elemento da página queremos manipular, e depois disso buscar a referência desse elemento. Mas o que é DOM? DOM significa Document Object Model, e é uma representação do documento HTML, que pode ser manipulada. Então depois de decidir o elemento que será manipulado, será necessário fazer uma consulta ao DOM, e os métodos mais recomendados para fazer a *query* no DOM são: `document.querySelector()` e o `document.querySelectorAll()`.

Então agora vamos imaginar que temos uma página HTML que contém um bloco de texto dentro de uma tag `<p>`. Neste caso podemos utilizar o `document.querySelector('p')` para selecionar o elemento através de sua tag. Basta passarmos como argumento do método o nome da *tag* como *string*. Veja no exemplo abaixo:

```jsx
const paragraph = document.querySelector('p');
console.log(paragraph);
// <p>Um texto qualquer</p>
```

Podemos obter também um elemento através de sua classe CSS. Então se temos diversas tags `<p>` e queremos apenas selecionar a que tenha uma determinada classe CSS, "author" por exemplo, podemos passar essa classe como argumento do método. Podemos também utilizar a tag com a classe CSS em conjunto, bastando passar como argumento o nome da tag, seguido de "." (ponto) e depois pelo nome da classe. Veja o exemplo abaixo:

```jsx
const authorParagraph = document.querySelector('.author');
console.log(authorParagraph);
// <p class="author">Um texto qualquer</p>

const errorDiv = document.querySelector('div.error');
console.log(errorDiv);
// <div class="error">Uma mensagem de erro</div>
```

Uma outra maneira de obter o seletor é pelo browser. Para isso, basta clica com o botão direito do mouse sobre o elemento (numa página aberta no browser), e clicar em 'Inspecionar'. Com isso o developer tools do browser é aberto, e na aba *Elements*, basta clicar com o botão direto sobre o elemento (no código), depois clicar em *Copy* e em seguida na opção *Copy selector*. Isso fará com que seja criado um seletor específico para o elemento, e depois basta passar o resultado da cópia como argumento do método.

Os casos falados acima servem para selecionar um elemento apenas. Porém há casos em que existem diversos elementos da mesma tag, ou com a mesma classe, e que de fato seja necessário selecionar todos de uma vez. Para este caso usaremos o método `document.querySelectorAll()`, que receberá como argumento a referência para os elementos, seja uma tag, uma classe, ou algum outro tipo de referência.

Quando utilizamos o *query selector all*, é retornado um Node List, que é uma lista com os elementos que foram selecionados. É uma lista que parece um *array*, mas não é um *array*. Mas podemos utilizar esta lista como se fosse um *array* em alguns casos. Um exemplo é acessar um elemento da lista através da notação de colchete. Um outro caso é percorrer uma lista utilizando o método `forEach()`. Então vamos imaginar uma página HTML que contenha três blocos de texto, cada um em sua tag `<p>`. Vamos selecionar estes elementos e exibir no console cada um deles através do laço `forEach()`. Veja no exemplo:

```jsx
const paragraphs = document.querySelectorAll('p');

console.log(paragraphs);
// NodeList(3)
// Neste NodeList temos os três parágrafos citados no exemplo
// que podem ser acessados por notação de colchetes, por exemplo
// paragraphs[0]

paragraphs.forEach(paragraph => console.log(paragraph));
// <p>Parágrafo 1</p>
// <p>Parágrafo 2</p>
// <p>Parágrafo 3</p>
```

Estes são os métodos mais eficientes para selecionarmos elementos do DOM.

Métodos possíveis em um *Node List*: [https://developer.mozilla.org/en-US/docs/Web/API/NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)

Seletores CSS: [https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ricardopontesdantas! Rumo à fluência!!! 💥
