### ISSUE TITLE
Aplicação: Weather Application

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#826]
Fala Roger, passando pra deixar o link do repositório, inclusive no readme tem o link do netlify caso queira testar!
--- https://github.com/RicarGit/Preject-Weather-Application ---

Não lembro se foi pedido pra ser feito uma nova versão, se foi, passou despercebido.

Falando em mudanças no visual, a única mudança que fiz foi colocar o estado correspondente à cidade logo ao lado dela!

Fiz a aplicação quase que sem ver os vídeos, fazia funcionar do meu jeito e depois via as aulas, ia mudando o código só conforme ia vendo como você fazia o seu, confesso que a maioria das mudanças eram nomes de constantes e funções.

Estou começando a pegar o jeito da refatoração, essa é minha maior dificuldade ainda mas já consigo refatorar alguns ifs pra ternário e curto circuito, destructuring é uma coisa que curto muito fazer mas ainda enrosco em perceber que posso fazer destructuring em alguns retornos de funções mas creio que tudo isso é questão de praticar mais pra ir entrando na cabeça!

Ler documentação ainda é uma dificuldade mas estou treinando isso também e olha que não tenho tanta dificuldade com o inglês.

Uma dúvida que me surgiu no momento que gostaria de tirar é que teve uma parte no meu código que eu fiz um ternário de um único if e não de um if else, se o if está alí só pra checar se algo vai retornar true pra aí eu fazer alguma coisa, eu posso refatorar pra um ternário e já que não da pra omitir o resultado logo após os dois pontos : poderia retornar false ou null, não sei se é uma boa prática isso...

Uma coisinha boba que aconteceu esses dias foi ter criado meu LinkedIn e ter feito o teste de competência de JavaScript e acabei recebendo o selo de competência em JavaScript e dizia que eu fiquei entre os 15% de 1M de pessoas que fizeram o teste, não sei se é grande coisa mas pelo menos dizia que o mínimo era estar entre 30% pra poder ganhar o selo, fora que o teste era todo em inglês... fiz o de HTML e passei entre os 30% e CSS reprovei, isso porque JavaScript era minha maior dificuldade, hoje tá sendo a tecnologia que eu mais sou bom haha

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RicarGit.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise e as respostas das dúvidas serão postadas aqui =)

**Comment by RicarGit** [comment]
> As observações fizeram sentido?
Com certeza ajudaram muito, algumas coisas foram falta de atenção mesmo, como espaços, função no top do código e variáveis que armazenei em outras variáveis! foram coisas que não deviam ter acontecido, pura falta de atenção hehe

Roger, eu dei uma refatorada no código, inclusive fiz com que dependendo do dia o background muda pra acompanhar a imagem e adicionei a cidade no localStorage, se você puder dar uma olhadinha rápida novamente eu agradeço!

Uma pergunta que surgiu na criação do código da localStorage, talvez mais pra frente você ensine mas só por curiosidade rápida mesmo, tem como armazenar toda informação que vem da API e então usar essa info pra não ficar fazendo request toda hora?
eu sei que como a API da accuWeather precisa ser atualizada toda hora porque são informações em tempo real, mas deve ter casos que dá pra fazer isso certo? no caso guarda o objeto todo ou só as informações extraídas daí?

**Comment by RicarGit** [comment]
Roger, 
Aproveitando ainda essa aula e sobre seu feedback, logo após a aplicação da accuWeather teve o exercício de fazer o slide ser funcional, fiz esse código aqui e está funcionando perfeitamente mas só vou postar ele, gostaria que você desse uma olhada na estrutura que montei e refatorei já me baseando no seu feedback anterior.

Lembrando que eu não assisti a aula de correção ainda, verei assim que você der o seu feedback!
Obrigado!

```js
const carouselContainer = document.querySelector('.carousel')
const carouselImagesContainer = document
  .querySelectorAll('[data-js="carousel__item"]')

let slideIndex = 0
const lastImageIndex = carouselImagesContainer.length - 1

const hideImages = imagesContainer => {
  imagesContainer.forEach(img => {
    img.classList.remove('carousel__item--visible')
    img.classList.add('carousel__item--hidden')
  })
}

const checkClickedButton = clickedButton => {
  if (clickedButton === 'carousel__button--next') {
    slideIndex = (slideIndex >= lastImageIndex) ? 0 : ++slideIndex //coloquei entre ( ) pra melhor leitura
  }

  if (clickedButton === 'carousel__button--prev') {
    slideIndex = (slideIndex <= 0) ? lastImageIndex : --slideIndex //idem aqui
  }
}

const showCurrentSlideImage = slideIndex => {
  const currentSlide = carouselImagesContainer[slideIndex]

  currentSlide.classList.remove('carousel__item--hidden')
  currentSlide.classList.add('carousel__item--visible')
}

const manipulateSlider = event => {
  const clickedButton = event.target.dataset.js

  hideImages(carouselImagesContainer)
  checkClickedButton(clickedButton)
  showCurrentSlideImage(slideIndex)
}

carouselContainer.addEventListener('click', manipulateSlider)
```

**Comment by Roger-Melo** [comment]
> Lembrando que eu não assisti a aula de correção ainda, verei assim que você der o seu feedback!

Não recomendo fazer isso. A aula com a correção do exercício está disponível. Eu tento responder as issues o mais rápido possível, mas as vezes acaba levando mais tempo do que eu gostaria.

Ficou legal a refatoração da Weather app. Apenas tome cuidado com o contraste entre a cor do texto superior ao input em relação à cor de background. Quando é noite na cidade, fica complicado ler.

Sobre o localStorage, na etapa 15 eu mostro uma técnica para evitar fazer muitos requests =)

O código do carousel é por aí mesmo. Mas pra eu testar com mais precisão aqui, fica melhor se vc subir todos os arquivos em um repositório.

@RicarGit

**Comment by RicarGit** [comment]
> Não recomendo fazer isso. A aula com a correção do exercício está disponível. Eu tento responder as issues o mais rápido possível, mas as vezes acaba levando mais tempo do que eu gostaria.

Eu não ví pq eu sempre acabo pegando alguma coisa do vídeo e mudando, quis manter o código do meu jeito mesmo, sem "roubar" nomes de variáveis nem funções, não se preocupe, não pausei os estudos por conta disso.

> O código do carousel é por aí mesmo. Mas pra eu testar com mais precisão aqui, fica melhor se vc subir todos os arquivos em um repositório.

Eu coloquei mais pra você visualizar a estrutura e os nomes mesmo, espero melhorar a organização do meu código!

**Comment by Roger-Melo** [comment]
Ah, saquei xD

Cara, no geral os nomes estão descritivos sim. 

Eu apenas mudaria algumas coisas, tipo o nome da `carouselImagesContainer`. Já que ela contém um nodeList com vários itens, eu nomearia ela como `images` ou `slides`. Como vc nomeou a maioria com `image`, eu manteria o padrão.

`lastImageIndex` e `slideIndex` podem ser mais consistentes. Ou fica `lastSlideIndex` e `slideIndex` ou `lastSlideImage` e `slideImage`.

Como `slideIndex` representa o index do slide exibido atualmente, eu adicionaria "current" no começo do nome dela.

E eu tb evitaria ternários dentro de ifs (como mostrei na correção), porque no fim das contas é um aninhamento de condicionais e isso deixa o código mais complexo. 

No mais, é isso =)

@RicarGit

**Comment by RicarGit** [comment]
Valeu pelas dicas Roger, tentarei manter padronizado os nomes também, rumo a fluência!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)

**Comment by RicarGit** [comment]
Sabe me dizer o porque do erro que dá no site do netlify? "TypeError: NetworkError when attempting to fetch resource"
Quando vou na aba redes eu vejo que o status está com um circulo vermelho e na tranferência diz Mixed Block

Será que o netlify está bloqueando o fetch por achar não ser seguro?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @RicarGit. Manda os prints do erro, assim fica mais fácil ajudar =)

Ps: prefira não comentar em issues fechadas. Abra uma nova issue ou abra a issue e comente. Se não a issue não é exibida no painel de issues e eu posso não ver.

**Comment by RicarGit** [comment]
> Ps: prefira não comentar em issues fechadas. Abra uma nova issue ou reabra a issue e comente. Se não, a issue não é exibida no painel de issues e eu posso não ver.

Vou lembrar disso na próxima haha, fica tranquilo Roger, ja resolvi, era o link que estava com http e não https, foi só acrescentar um s em http pro netlify parar de achar a conexão não segura.

Aproveitando aqui, pode me dar um spoiler do próximo modulo depois do firebase? vem TDD por aí? as vagas hoje pedem muuuito TDD como requisito obrigatório...

Desculpe atrapalhar @Roger-Melo, pode fechar a issue novamente, Obrigado!

**Comment by Roger-Melo** [comment]
Ah, show! =)

A etapa de TDD vai chegar, mas ainda não é a próxima. Você pode conferir o plano de aulas do treinamento [aqui](https://drive.google.com/file/d/13RaAC8qjibWEx5wBhaXsSzPuyY0yeZvA/view?usp=sharing) =)

@RicarGit
