### ISSUE TITLE
Etapa 3, Correção dos exercícios da aula 01 - Aula 02-01

### ISSUE THREAD

**Issue by rodrigoljpereira** [roger-melo-treinamentos/curso-de-js-roger-melo#828]
Olá professor. Tudo bem.

Conforme instruido, eu retornei algumas aulas para trás pra garantir que não tenha ficado nenhuma duvida, e ao assistir as correções dos exercicios mensionados no titulo fiquei com uma duvida.

1ª Eu percebi que você cria várias constantes para inserir as expressões que vão aparecendo ao longo dos codigos. Para facilitar a leitura. Minha pergunta é: Existe alguma regra especifica pra identificarmos onde devemos substituir uma determinada expressão por uma const ou let que a contenha? Ou é mais uma questão que muda de programador para programador?

Desde já agradeço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Rodrigo.

Legibilidade é um critério quase subjetivo, por que contém muitas nuances e vários autores terão abordagens distintas. Mas o ponto em comum entre todos eles é: um código legível é mais fácil de ler e, principalmente: manter. Essa é a sacada.

No começo do treinamento, eu crio mais variáveis para enfatizar para o novo aluno o quanto escrever código legível é importante. À medida em que as aulas vão se passando, depois do aluno sacar essa importância, eu vou deixando isso mais "flexível". Você está na etapa 3 mas aos poucos irá perceber isso.

Então respondendo a pergunta de forma mais direta...

> Existe alguma regra especifica pra identificarmos onde devemos substituir uma determinada expressão por uma const ou let que a contenha?

Não existe regra mas, eu recomendo que você siga a risca como é mostrado no CJRM. Na maioria das vezes, eu vou armazenar em consts expressões que são complicadas para ler, ou são extensas.

E claro, se houver qualquer dúvida específica em relação à isso ou a algum código que eu mostrei, pode perguntar que eu te ajudo a sanar a dúvida =)

Ficou mais claro?

@rodrigoljpereira

**Comment by Roger-Melo** [comment]
@rodrigoljpereira vou fechar a issue mas no que precisar, fique à vontade para perguntar =)
