### ISSUE TITLE
Etapa 07, Aplicação: Quiz Interativo - Aula Exercícios da Aula 01

### ISSUE THREAD

**Issue by jonathan93silva** [roger-melo-treinamentos/curso-de-js-roger-melo#83]
Bom dia Roger Melo!
Segue o link do meu repositório https://github.com/jonathan93silva/quiz-interativo.git

Minhas dificuldades: Deixar o código mais legível, com escolhas de nomes para variáveis. Tive que assisti a aula sobre o popup novamente para inserir no meu projeto, na hora de mostrar o resultado! Também gastei um pouco de tempo para encontrar as classes que queria na documentação do bootstrap.

Minhas facilidades: Criar a logica para mostrar mensagens diferentes de acordo com o resultado e adicionar os eventos também foi bem tranquilo!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Jonathan.

Passando para te avisar que estou ciente da sua issue, em breve lhe darei um feedback com mais calma =)

@jonathan93silva

**Comment by Roger-Melo** [comment]
Oi Jonathan! 

Parabéns pelo esforço em desenvolver a aplicação =)

No momento, não se preocupe tanto em deixar o código mais legível possível. No decorrer das aulas do treinamento, observe como eu nomeio as consts e propriedades e você perceberá, aos poucos, o padrão. Essa habilidade demanda tempo e prática.

Foi uma boa sacada inserir o popup para exibir os pontos.

Nas aulas seguintes eu mostro como podemos melhorar o código dessa aplicação.

Inclusive, em aulas posteriores, você verá uma técnica para substituir switch por objeto. Isso deixará o código menos verboso e mais legível =)

Cuidado ao dar nomes muito parecidos às variáveis, isso pode lhe confundir caso precise relembrar (no futuro) o que cada variável armazena.

Ao invés de deixar nomes muito similares assim,

```javascript
const classListToClosePopup = ['popup-wrapper', 'btn-closePopup']
const classInListToClosePopup = classListToClosePopup.includes(classNameElementClicked)
```

prefira dar nomes mais distintos, 

```javascript
const classListToClosePopup = ['popup-wrapper', 'btn-closePopup']
const shouldClosePopup = classListToClosePopup.includes(classNameElementClicked)
```

ou apenas encadear a invocação do método no próprio array:

```javascript
const classInListToClosePopup = ['popup-wrapper', 'btn-closePopup']
  .includes(classNameElementClicked)
```

Continue seguindo o método e ao corrigir os exercícios, execute o passo-a-passo que descrevi [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Isso solidificará a lógica em seu cérebro e você tenderá a ganhar mais velocidade para alcançar a fluência.

Novamente, parabéns pelo esforço e conte comigo para chegar na fluência =)

@jonathan93silva

**Comment by jonathan93silva** [comment]
Bom dia Roger!
Obrigado pelo feedback!
Utilizei o popup para exibir os pontos, pois não tinha assistido as aulas seguintes à aula 01-03 da etapa 07!
Como você pediu para refatorar e melhorar a aplicação para inserir no portfolio, vou fazer como as aulas seguintes e mostrar o os pontos através de uma div no inicio da página!

**Comment by Roger-Melo** [comment]
Legal Jonathan! =D

Vou fechar a issue, mas no que precisar é só abrir uma nova =)
