### ISSUE TITLE
Resumo da Aula 02-02 à 02-05 da etapa X3

### ISSUE THREAD

**Issue by NiksonDiniz** [roger-melo-treinamentos/curso-de-js-roger-melo#831]
## Arrow functions - Aula 02-02

Uma expressão arrow function possui uma sintaxe mais curta quando comparada a uma expressão de função

#### Função tradicional

```
const double = function (number) {
  return number * 2
}

const result = double(3)
console.log(`O resultado é: ${result}`) //  saída: O resultado é: 6
```

#### Arrow function

```
const double = (number) => {
  return number * 2
}
```

**Importante!**

- Não é necessário o uso da palavra **'function'**;
- Quando é só um parâmetro, os parenteses são opcionais; 
- Default  parâmetro não  funciona  nessa  sintaxe exemplo: **number = 0**;
- Se a função não  receber um parâmetro será necessário colocar os parenteses;
- Se o bloco de código for uma linha retornando valor, não é necessário a palavra **return**;
- Retornam valor: uma string, um array, um boolean, um número ou uma expressão;
- Não retornam valor: bloco if, switch

#### Seguindo todas as normas a função fica assim:

```
const double = number => number * 2
```

------

## Funções vs Métodos - Aula 02-03

- Funções e métodos são sinônimos.
- Método é um função, com forma diferente de ser invocado e ser declarado.

```
const name = 'Nikson'

// Funções
const sayHi = () => 'Oi'

const greet = sayHi()
console.log(greet)

// Métodos
const nameInUpperCase =  name.toUpperCase()

console.log(nameInUpperCase)
```

- métodos são funções que estão associadas a objetos ou tipos de dados como strings eles são criados no objeto ou no tipo de dado em si.
- as funções são criadas sozinhas.

------

## O método forEach e callbacks - Aula 02-04

Uma função callback é uma função passada a outra função como argumento, que é então invocado dentro da função externa para completar algum tipo de rotina ou ação.

**exemplo:**

```
const myFunc = callback => {
  const value = 77

  callback(value)
}

myFunc( number =>{
  console.log(number)
})
```

#### forEach

- O método forEach() executa uma dada função em cada elemento de um array.
- Em tradução literal será **para cada**

**exemplo:**

```
const socialNetworks = ['youtube', 'twitter', 'instagram', 'facebook']

// a função de callback  passada dentrodo forEach pode receber 3 parametros:
// O primeiro é o item atual sendo iterado 'socialNetwork' em singular pq representa um item do arraay
// o segundo é o index (opcional)
// o terceiro é o array (opcional)



socialNetworks.forEach((socialNetwork, index, array) => {
  console.log(index, socialNetwork, array)
})

/* saída:
  0 "youtube"   (4) ["youtube", "twitter", "instagram", "facebook"]
  1 "twitter"   (4) ["youtube", "twitter", "instagram", "facebook"]
  2 "instagram" (4) ["youtube", "twitter", "instagram", "facebook"]
  3 "facebook"  (4) ["youtube", "twitter", "instagram", "facebook"]
*/



// Tem a vantagem de ser desacoplada
// ficando assim:
const logArrayInfo = (socialNetwork, index, array) => {
  console.log(index, socialNetwork, array)
}

// socialNetworks.forEach(logArrayInfo)
```

------

## Utilizando callbacks e exercícios - Aula 02-05

```
const ul = document.querySelector('[data-js="ul"]')
const socialNetworks = ['youtube', 'twitter', 'instagram', 'facebook']
let HTMLtemplate = ''

socialNetworks.forEach( socialNetwork => {
  HTMLtemplate += `<li style="color: deeppink;">${socialNetwork}</li>`
})

ul.innerHTML = HTMLtemplate

// Gera um template HTML através de dados
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @NiksonDiniz! Rumo à fluência!!! 💥
