### ISSUE TITLE
Etapa 10, nome do vídeo: Conhecendo a date-fns - Aula 02-03

### ISSUE THREAD

**Issue by YureK-a** [roger-melo-treinamentos/curso-de-js-roger-melo#833]
Não estou conseguindo adicionar o date-fns, pois quando entro no site não aparece o CDN e nem o link para adicionar

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @YureK-a. Veja a aula com calma. Lá eu explico por que o link para a CDN não está visível à primeira vista e mostro, passo a passo, onde e como você irá encontrá-lo. Acabei de fazer aqui os passos que mostro na aula e o link foi disponibilizado.

Se ainda restar alguma dúvida, é só dar o toque =)

**Comment by YureK-a** [comment]
Obrigado pela resposta, professor! Consegui fazer o processo. Desculpe pela falta de atenção!
