### ISSUE TITLE
Aplicação: [QUIZ INTERATIVO]

### ISSUE THREAD

**Issue by woodmutran** [roger-melo-treinamentos/curso-de-js-roger-melo#838]
Opa, @Roger-Melo ! Segue a minha aplicação do QUIZ.

**Facilidades:**
- manipular a maioria dos elementos do DOM
- adicionar eventos

**Dificuldades:**
- lembrar do uso do array para alcançar os values dos inputs

Adicionei alguns recursos que foram ensinados durante o curso, especificamente na exibição do score. Trabalhei no layout da página também, fazendo uso do bootstrap e elementos adicionais de CSS.

Veja se está nos conformes. Agradeço desde já pela análise.

[Repositório do QUIZ](https://github.com/woodmutran/quiz-supermario.git)

Abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @woodmutran.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @woodmutran!

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui. 

Muito legal o tema do quiz =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

Talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, após enviar o form, a pontuação é exibida na parte inferior (não-visível) da tela:

![pontuacao](https://user-images.githubusercontent.com/29297788/121689532-1706df00-ca9b-11eb-91ba-f9c63c77faf5.jpg)

Então uma alternativa seria inserir o parágrafo acima do botão.

Nas aulas seguintes eu mostro uma forma de implementar a pontuação =)

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio... 

`p` é um nome vago para uma `const`. Você pode nomeá-la como `score`, `finalScore` ou algo do tipo.

`congratulations` pode ser nomeada como `getCongratulationsMessage`.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu removeria a linha 25 em branco e adicionaria uma linha em branco na linha 30.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by woodmutran** [comment]
Maravilha, @Roger-Melo ! Entendi perfeitamente. Acabei de assistir as aula seguintes e agora vou fazer o exercício 20. 

Não havia me atentado para essa questão de usabilidade no resultado. Me preocupei apenas com a funcionalidade. Como também não setei as medias de css. Vou dar um talento nesses detalhes que você pontuou.

Muito obrigado!
Abraço

**Comment by Roger-Melo** [comment]
Show @woodmutran. Vou fechar essa issue mas no que precisar, é só abrir uma nova =)
