### ISSUE TITLE
Etapa 3, O método forEach e callbacks - Aula 02-04

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#84]
**Roger, Me explica uma coisa, ontem passei horas tentando entender isso e nada...**

**Porque diabos essa função não retorna undefined**

```js
const getValue = callback => {
const value = 33

callback(value)
}

const getTripleValue = number => console.log(number * 3)

getValue(getTripleValue)
```

**e essa aqui retorna undefined...**

```js
const getValue = callback => {
const value = 33

callback(value)
}

const getTripleValue = number => number * 3

console.log(getValue(getTripleValue))
```

**Perceba que a única mudança foi aonde eu coloquei o console.log(), porém, se eu colocar um return assim:**

```js
const getValue = callback => {
const value = 33

return callback(value)
}

const getTripleValue = number => number * 3

console.log(getValue(getTripleValue))
```

**Lendo a documentação na MDN lá é criada a callback sem o return, porém o resultado da outra função está com um console.log() dentro dela, não entendi o porquê do consolo.log() mostrar o valor dentro da função mas não mostrar quando vc invoca as funções dentro do console.log()**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Em JavaScript, qualquer pedaço de código que não retorna um valor, retorna `undefined`.

Ou seja, uma função que não retorna um valor, por baixo dos panos, retorna `undefined`.

Em seu primeiro exemplo, se inserirmos a invocação da `getValue` como argumento de um `console.log()`, o retorno será `undefined`.

```javascript
const getValue = callback => {
  const value = 33

  callback(value)
}

const getTripleValue = number => console.log(number * 3)

console.log(getValue(getTripleValue)) // undefined
```

Observe que neste código,

```javascript
const getTripleValue = number => console.log(number * 3)
```

a arrow function está retornando o valor que a invocação do `console.log(number * 3)` retorna.

Se você for agora no console do browser e invocar um `console.log()`, verá que a primeira linha abaixo dessa invocação exibe o valor inserido como argumento da invocação do console.log, e a 2ª linha abaixo da invocação exibe `<- undefined`.

Isso acontece porque como eu disse lá em cima, em JavaScript, qualquer pedaço de código que não retorna um valor, retorna `undefined`.

A invocação `console.log()` não retorna um valor. Ela apenas exibe um valor no console.

Como a invocação `console.log()` resulta em `undefined`, e como no código abaixo a arrow function está retornando o valor que a invocação do `console.log(number * 3)` retorna, quando essa arrow function for invocada, ela executará `console.log(number * 3)` e retornará o `undefined` que a invocação do console.log retornou.

```javascript
const getTripleValue = number => console.log(number * 3)

getTripleValue(7) // exibe 21 no console e retorna undefined

// Para provar que getTripleValue(7) retorna undefined, basta exibir no console o resultado/retorno dessa invocação
console.log(getTripleValue(7)) // undefined
```

Ficou mais claro?

@RicarGit

**Comment by RicarGit** [comment]
Essa dúvida está quebrando toda função que eu faço agora hahaha, cheguei até a ficar nervoso umas horas aí...

1º - Vamos lá, deixa eu ver se eu entendi, toda função sem return resulta em undefined porém ela executa! Se eu quiser exibir algo não preciso usar um return, porém se eu quiser armazenar esse valor e modificar eu preciso usar o return pra "pegar" esse valor certo!?

2º - Eu entendi que o console.log() não possui um return interno, logo ele mostra o valor mas não repassa ele pra guardar em uma variável por exemplo, nessa função então digamos que o valor mostrado no console não quer dizer que o exercício esteja certo sendo que lá no final ela pode resultar em undefined na variável que vc for guardar, isso pode até quebrar uma aplicação se esquecer um console.log() lá dentro, certo!?

Outra coisa... acho que eu não estou entendendo o fluxo que essa função faz... estou vendo que mesmo eu não usando o return na getValue ela passa o valor para o parâmetro da getTripleValue, porque debugando a função o number recebe a value 33 e o return da arrow function que deveria retornar 99 desaparece com o valor, mas afinal de contas, qual return ta sendo executado por último?

Na minha cabeça o return da getValue retornava o valor pra dentro do parâmetro da getTripleValue e ala pegava esse retorno e multiplicava por 3 e ela retornava o resultado pra alguma variável, mas vendo no debugger a getValue passa o value 33 pro parâmetro number da getTripleValue e a getTripleValue retorna pra getValue novamente?

**Comment by Roger-Melo** [comment]
Oi Ricardo.

> 1º - Vamos lá, deixa eu ver se eu entendi, toda função sem return resulta em undefined porém ela executa! Se eu quiser exibir algo não preciso usar um return, porém se eu quiser armazenar esse valor e modificar eu preciso usar o return pra "pegar" esse valor certo!?

Não há relação da declaração do `return` com a execução da função.

A execução da função depende apenas se você quer [executar o código dentro dela](https://youtu.be/evaDwiFb4eU?t=29).

```javascript
myFunc() // execução da função (através dos parênteses)

myFunc // referência da função
```

O `return` deve ser usado quando você precisa que [a invocação da função retorne algum valor](https://youtu.be/Tzhz7psos1U?t=110).

> 2º - Eu entendi que o console.log() não possui um return interno, logo ele mostra o valor mas não repassa ele pra guardar em uma variável por exemplo, nessa função então digamos que o valor mostrado no console não quer dizer que o exercício esteja certo sendo que lá no final ela pode resultar em undefined na variável que vc for guardar, isso pode até quebrar uma aplicação se esquecer um console.log() lá dentro, certo!?

O `console.log()` só existe para você exibir um valor no console. Mais nada. 

Não faz sentido armazenar em uma variável o `undefined` que a invocaçao do `console.log()` retorna. Como eu disse, ele só existe para exibir um valor no console.

Esquecer uma invocação do `console.log()` no código não quebra aplicação, mas demonstra negligência.

---

Recomendo que, por enquanto, esqueça forçar entender os 3 exemplos das funções da 1ª issue que você abriu (lá em cima). 

Quando temos dificuldade em entender um conceito e deixamos nossa mente acelerar e fazer variações do exemplo do conceito, as chances são que vamos ficar mais confusos. É como querer aprender o solo de guitarra de uma música que você gosta sem ter um bom conhecimento de escalas e acordes.

Vou fazer abaixo um outro exemplo-chave para você entender callbacks. Vamos entendê-lo primeiro e deixar variações para depois.

Ao implementar o passo-a-passo abaixo, me diga **apenas em qual passo** você começou a ter dificuldades em entender.

Preciso que você acompanhe o passo-a-passo abaixo codando comigo em seu editor, vamos lá:

- 1º passo: vou declarar a função normalmente, sem parâmetro algum:

```javascript
const myFunc = () => {}
```

Se salvarmos o arquivo e invocarmos essa função, nada acontece pois invocamos 
uma função vazia. 

Como dentro dela não existe um `return`, `undefined` foi retornado. E não há problema algum nisso. 

```javascript
const myFunc = () => {}

myFunc() // undefined
```

- 2º passo: para que essa função exiba algum valor no console, vou especificar 
que ela receberá uma string por parâmetro,

```javascript
const myFunc = string => {}

myFunc()
```

e agora que eu especifiquei esse parâmetro, eu posso passar uma string como 
argumento da invocação da função:

```javascript
const myFunc = string => {}

myFunc('Minha string')
```

Então agora temos uma função que recebe 'Minha string' no parâmetro `string`.

Só que a invocação dessa função ainda não causará efeito algum, pois eu estou 
fazendo nada com a 'Minha string' que recebi no parâmetro string.

Então para exibir no console o valor que o parâmetro `string` recebeu, dentro 
da função eu vou executar um `console.log()` que recebe o valor que o parâmetro 
`string` recebeu:

```javascript
const myFunc = string => {
  console.log(string)
}

myFunc('Minha string')
```

Se você olhar o console, verá que 'Minha string' foi exibida.

Até nesse ponto do curso, os valores que foram passados como argumentos para 
as funções foram strings (como essa que codamos agora), números, arrays e etc.

Só que em JavaScript, assim como números e strings são valores que podem ser 
recebidos por parâmetro, uma função também é um valor (que pode ser recebido 
por parâmetro).

Sabendo disso, vamos ao próximo passo.

- 3º passo: para que a `myFunc` receba uma função como parâmetro, eu vou 
substituir o parâmetro `string` por um parâmetro `aFunction`,

```javascript
const myFunc = aFunction => {
  console.log(string)
}
```

e para que a função recebida no parâmetro `aFunction` da myFunc seja exibida 
no console, no argumento do `console.log()`, vou substituir `string` por 
`aFunction`:

```javascript
const myFunc = aFunction => {
  console.log(aFunction)
}
```

Então agora, se eu inserir a declaração de uma função como argumento da 
invocação da `myFunc`,

```javascript
const myFunc = aFunction => {
  console.log(aFunction)
}

myFunc(() => {}) // função declarada como argumento
```

como em JavaScript uma função também é um valor que pode ser recebido por 
parâmetro (como qualquer outro valor), se salvarmos o arquivo e olharmos o 
console, a função que declaramos como argumento da invocação da `myFunc` é 
exibida.

- 4º passo: agora que sabemos que o argumento `aFunction` do `console.log()` é uma 
função, eu posso invocar essa função inserindo os parênteses:

```javascript
const myFunc = aFunction => {
  console.log(aFunction()) // função invocada
}

myFunc(() => {})
```

Se salvarmos o arquivo, o console exibe undefined. Por que?

Por que a função que inserimos como argumento da invocação da myFunc não está 
retornando um valor.

Se fizermos a função retornar um `'Oi'`,

```javascript
const myFunc = aFunction => {
  console.log(aFunction())
}

myFunc(() => 'Oi') // fiz a função retornar 'Oi'
```

como a invocação da `() => 'Oi'` retorna uma string, a invocação dela no 
argumento do console.log() dentro da myFunc resultará na string 'Oi'.

Se salvarmos o arquivo, agora sim o console exibe a string.

A diferença entre o exemplo mostrado na aula e esse, é que a função de callback 
invocada dentro da myFunc recebe um argumento. Se você entender esse exemplo 
acima, penso que será mais fácil entender o exemplo da [aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/803293).

Em qual passo você começou a ter dificuldades em entender?

@RicarGit

**Comment by RicarGit** [comment]
Beleza, Roger!
Uma coisa que estava me quebrando era o forEach, vi na documentação que ele não retorna, logo ele eh uma função que modifica valores mas não retorna, uma função de efeito colateral, o map, filter e reduce sim são funções que retornam e precisam ser guardadas em variáveis já que ela não modificam a variável original, esse undefined que vinha do forEach que eu tava quebrando a cabeça...

sobre a criação de callbacks, se eu preciso que ela retorne algo, eu preciso retornar tanto a callback quanto a função que está executando é isso?

const myFunc = callback => callback()

const sayHi = myFunc(() => "Hi")

console.log(result)

teria que retornar as duas é isso?

mais uma coisinha, ainda não consegui entender pq callbacks existem, pq chamar uma função para executar outra? funções da "vida real" guardam valores e callbacks pegam esses valores pra fazer diferentes coisas? seria isso?

**Comment by Roger-Melo** [comment]
Ricardo, eu fiz uma pergunta e ela não foi respondida.

Como eu preciso da resposta para te ajudar, vou tentar novamente:

Em qual passo, do passo à passo que eu expliquei na issue mais recente, você começou a ter dificuldades em entender?

@RicarGit

**Comment by RicarGit** [comment]
Roger, eu entendi 100% da sua explicação e eu entendo como fazê-las, acho que não me expressei muito bem sobre a função que eu coloquei na primeira issue.
Eu estava tentando exibir no console o resultado da invocação da função Exemplo: console.log(myFunc()) eu não quero exibir NADA dentro da função, queria que a invocação mostrasse o resultado, sua explicação sobre o return foi esclarecedora pra mim e estou usando o return depois disso e está funcionando agora todas que faço, porém eu não entendi o fluxo que a callback tem, eu estou fazendo direito agora mas gostaria de entender como ela funciona por dentro desde a declaração até a execução e qual return das duas é executado por último.
quando a myFunc é invocada, o return da função invocada que entrega o resultado final ou o resultado é entregue pra myFunc e ela que retorna o resultado, era só pra entender qual caminho o js faz pra entregar o resultado!
Acho que agora fui mais claro, não tenho mais dificultade em retornar valores mas sim em entender o fluxo desses 2 returns

**Comment by Roger-Melo** [comment]
Não existem 2 returns.

### Caso 1

No exemplo abaixo, 

```javascript
const myFunc = aFunction => {
  console.log(aFunction())
}

myFunc(() => 'Oi')
```

na última linha, quando `myFunc` é invocada, o código da declaração dela será executado. 

Observe que após o sinal de atribuição deste trecho de código: `const myFunc =`, o código abaixo será executado.

```javascript
aFunction => {
  console.log(aFunction())
}
```

O parâmetro `aFunction` recebeu `() => 'Oi'`.

Dentro do bloco da função acima, `() => 'Oi'` é executada como argumento do `console.log()` e como a execução dela retorna a string `'Oi'`, por baixo dos panos, isso está acontecendo: `console.log('Oi')`.

---

### Caso 2

Se eu modificar esse código para 

```javascript
const myFunc = aFunction => {
  return aFunction()
}

myFunc(() => 'Oi')
```

Quando `myFunc` é invocada:

1. O parâmetro `aFunction` recebeu `() => 'Oi'`;
2. Dentro do bloco da função myFunc, `() => 'Oi'` é executada, então a invocação `aFunction()` resulta em `'Oi'`. Ou seja, por baixo dos panos, isso está acontecendo dentro do bloco da função: `return 'Oi'`;
3. Após isso, na última linha, a expressão `myFunc(() => 'Oi')` resulta em `'Oi'`.

---

### Caso 3

Se eu modificar esse código para 

```javascript
const myFunc = aFunction => aFunction()

myFunc(() => 'Oi')
```

Quando `myFunc` é invocada:

1. O parâmetro `aFunction` recebeu `() => 'Oi'`; 
2. Mesmo a função não tendo bloco agora, a invocação de `aFunction()` executa `() => 'Oi'`; 
3. Como `() => 'Oi'` retorna `'Oi'`, a invocação `aFunction()` resulta em `'Oi'`. Ou seja, por baixo dos panos, isso está acontecendo: `const myFunc = aFunction => 'Oi'`;
4. Após isso, na última linha, a expressão `myFunc(() => 'Oi')` resulta em `'Oi'`.

Ficou mais claro?

@RicarGit

**Comment by RicarGit** [comment]
Perfeito, estou fazendo exatamente como no caso 2 e 3 só que armazenando o resultado em constantes!

Fiz um exemplo aqui bem genérico que chega perto do que eu imagino que dê pra fazer com callbacks para poder pensar em soluções para usa-lás futuramente:

```js
const soma1 = callback => {
  const number1 = 30

  return callback(number1)
}

const soma2 = number1 => {
  const number2 = 15

  return number1 + number2
}

const result = soma1(soma2)

console.log(result)
```
O nome dos parâmetros estão com mesmo nome das variáveis só pra demonstrar o que está sendo passado.

Quando me referi a 2 returns era 1 do soma1 e 1 do soma2, caso eu retire a palavra chave return de um deles a variável result resulta em undefined!

**Pra você ver como entendi:**
1. soma1 é invocada recebendo soma2 como parâmetro ```soma1(soma2)```
2. number1 é declarado com o valor de 30, callback é invocada recebendo soma2 com number1 de parâmetro ```callback(number1)``` é o mesmo que ```soma2(30)```
3. soma2 declara number2 com valor de 15 e retorna a soma de number1 e number2, resultando em 45
4. agora dentro da soma1 o ```callback(number1)``` agora vale 45 e fica assim: ``` return 45```
5. então soma1 retorna o 45 para a variável result!
6. usando um ```console.log(result)``` agora 45 é exibido no console!

Creio que é assim que a função execute, se não for, pelo menos está funcionando hahaha

Desculpe a dor de cabeça Roger, estou aprendendo muito com sua didática e estou curtindo muito os exercícios, está abrindo bastante a minha cabeça na hora de pensar em soluções, eu sempre reclamei nos grupos de outros cursos que precisavam passar exercícios ao invés de só aulas e aulas e só fazer algo quando o professor estivesse fazendo algum projeto, aquilo não era aprender!

@Roger-Melo

**Comment by Roger-Melo** [comment]
> **Pra você ver como entendi:**

É isso mesmo =)

> Quando me referi a 2 returns era 1 do soma1 e 1 do soma2, caso eu retire a palavra chave return de um deles a variável result resulta em undefined!

Sim. Se `return` for removido de dentro do bloco da `soma1`, a expressão `callback(number1)` resultará em 45, mas como nenhum valor está sendo retornado pela função, `undefined` será retornado quando ela for invocada.

```js
const soma1 = callback => {
  const number1 = 30

  callback(number1) // 45 ficou "preso" dentro do bloco da soma1
}

const soma2 = number1 => {
  const number2 = 15

  return number1 + number2
}

const result = soma1(soma2)

console.log(result)
```

Se `return` for removido de dentro do bloco de `soma2`, dentro do bloco de `soma2` a expressão `number1 + number2` resultará em 45, mas como nenhum valor está sendo retornado pela função, `undefined` será retornado quando ela é invocada.

Ou seja, como nenhum valor está sendo retornado pela `soma2`, dentro do bloco da `soma1` a expressão `callback(number1)` resultará em `undefined`. E esse `undefined` será retornado pelo `return` fazendo a expressão `soma1(soma2)` resultar em `undefined`:

```js
const soma1 = callback => {
  const number1 = 30

  return callback(number1) // retorna undefined
}

const soma2 = number1 => {
  const number2 = 15

  number1 + number2 // 45 ficou "preso" dentro do bloco da soma2
}

const result = soma1(soma2) // resultou em undefined

console.log(result)
```

---

Uma observação off-topic: fique atento à padronização do idioma do código. Escolher nomear os identificadores em apenas português ou inglês é um indicativo de consistência.

---

> Mais uma coisinha, ainda não consegui entender pq callbacks existem, pq chamar uma função para executar outra? funções da "vida real" guardam valores e callbacks pegam esses valores pra fazer diferentes coisas? seria isso?

Um callback é uma função inserida como argumento da invocação de outra função.

Toda vez que você executar um forEach, você precisa inserir um callback como argumento para que esse callback seja executado para cada item do array.

Ou seja, o `forEach` precisa receber uma função informando qual ação ele irá fazer para cada item do array no qual ele foi encadeado. Esse é um caso de uso.

No decorrer do treinamento, você verá outros casos de uso em que callbacks são necessários, principalmente na etapa onde mostro operações assíncronas.

Então não se preocupe, você ainda verá muitos exemplos no decorrer do treinamento.

---

> Desculpe a dor de cabeça Roger, estou aprendendo muito com sua didática e estou curtindo muito os exercícios, está abrindo bastante a minha cabeça na hora de pensar em soluções, eu sempre reclamei nos grupos de outros cursos que precisavam passar exercícios ao invés de só aulas e aulas e só fazer algo quando o professor estivesse fazendo algum projeto, aquilo não era aprender!

Não tem dor de cabeça não. Pode perguntar sempre que tiver dúvidas, estou aqui para solucioná-las =)

Continue se esforçando para seguir o método e você tenderá a chegar na fluência mais rápido.

---

Não sei se já lhe recomendei isso, mas prefiro pecar pelo excesso do que pela falta: eu escrevi um passo-a-passo do que você deve fazer quando errar um exercício. E o mesmo princípio desse passo-a-passo pode ser aplicado quando você me vê refatorando um código de forma diferente da que você fez.

Vou deixar o link para o passo-a-passo [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Depois me diga se ajudou =)

@RicarGit

**Comment by RicarGit** [comment]
> Uma observação off-topic: fique atento à padronização do idioma do código. Escolher nomear os identificadores em apenas português ou inglês é um indicativo de consistência.

hahaha, eu nem sei o porquê de eu ter colocado soma1 e soma2, eu geralmente coloco tudo em inglês, fiz na correria pra demonstrar o que eu entendi da função e nem reparei nisso, pode ficar sossegado que eu não misturo os idiomas haha

> Não sei se já lhe recomendei isso, mas prefiro pecar pelo excesso do que pela falta: eu escrevi um passo-a-passo do que você deve fazer quando errar um exercício. E o mesmo princípio desse passo-a-passo pode ser aplicado quando você me vê refatorando um código de forma diferente da que você fez.
> 
> Vou deixar o link para o passo-a-passo aqui. Depois me diga se ajudou =)

Eu já tinha visto isso em alguma das aulas, sigo fazendo o mesmo, não quero copiar mais códigos e sim fazer os meus, as vezes eu refaço várias vezes e até busco no MDN ou na W3SHOOL que eu acho ótimo também com vários exemplos.
Fora isso eu estou escutando os áudios do Telegram, o manual da disciplina, escuto quando faço minhas caminhadas, estou curtindo bastante!
Agradeço pela ajuda @Roger-Melo, até uma próxima Issue! Haha

**Comment by Roger-Melo** [comment]
Show Ricardo! Fico feliz em saber que está curtindo.

Já que ficou mais claro, por agora vou fechar a issue. Mas no que precisar, é só abrir uma nova =)
