### ISSUE TITLE
Resumo da Aula Arrow functions - Aula 02-02 da etapa 03

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#840]
# Arrow functions

Arrow Function é uma da adições do JS moderno. É uma forma mais curta de escrever uma função.

```js
// Função Tradicional
const double = function(number) {
  return number * 2;
}

// Arrow Function
const double = (number) => {
  return number * 2;
}
```

Quando a arrow function possuir apenas 1 parâmetro podemos tirar os parênteses do parâmetro. No entanto só se deve fazer isso se o parâmetro não receber nenhum valor default:

```js
// Com parâmetro normal
const double = number => {
  return number * 2;
}

// Com parâmetro com valor default precisa dos parênteses
const double = (number = 0) => {
  return number * 2;
}
```

Quando a arrow function não tiver parâmetro é preciso deixar os parênteses vazios:

```js
const double = () => {
  // código...
}
```

Outro ponto importante é que se a função tiver só 1 linha e essa linha for o código de retorno da função, podemos remover o return, as chaves e deixar toda a função em apenas 1 linha. Com isso, o retorno acontecerá implicitamente:

```js
const double = () => {
  return 'Hello, World';
}

// A função acima pode ser escrita da maneira abaixo

const double = () => 'Hello, World';
```

**Outra diferença desses 2 tipos de funções é o biding da palavra chave this, que será visto mais a frente no curso.**

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @rohyer! Rumo à fluência!!! 💥
