### ISSUE TITLE
Etapa 14, Correção dos exercícios da aula 01 da etapa 14 - Aula 02-01

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#845]
Oi professor, estou realizando a revisão raio-x, e me deparei com uma dúvida que por algum acaso acabou passando despercebida quando assisti esta aula anteriormente.

Foi dito que uma instrução é qualquer pedaço de código que não resulta em um valor. Logo, uma função que não retorna nada, e por consquência retorna undefined também é considerada uma instrução?

Obrigado desde já professor.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Algumas expressões são indistinguíveis de instruções. O mesmo código pode funcionar de forma diferente dependendo de onde ele é inserido em uma expressão ou em uma instrução.

Nas aulas, há momentos em que eu simplifico algumas coisas ao custo de não ser 100% preciso.

Vou deixar algumas fontes abaixo caso você queira aprofundar no assunto. 

- [Statements and declarations - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements)
- [Expressions and operators - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#expressions)
- [Expressions versus statements in JavaScript - Axel Rauschmayer](https://2ality.com/2012/09/expressions-vs-statements.html)

Mas na real, considerando o seu momento, talvez não vale a pena se aprofundar nisso (tanto é que eu não aprodundei na aula). É algo que não vai fazer grande diferença se seu objetivo continua sendo montar um portfólio com aplicações para conquistar uma vaga.

Mais valioso do que aprender, é aprender e executar o que faz sentido para o seu momento =)

@sou-gabriel

**Comment by sou-gabriel** [comment]
Hmmm! Total sentido professor. As vezes me prendo muito nas nuances, e isso sinto que me prejudica. Mas continuarei seguindo firme nos conteúdos que realmente importam pro meu momento através das aulas.
 
Muitíssimo obrigado professor =)

**Comment by Roger-Melo** [comment]
Show. No que precisar, é só abrir uma nova issue =)
