### ISSUE TITLE
Etapa 3, Funções

### ISSUE THREAD

**Issue by PhAssis** [roger-melo-treinamentos/curso-de-js-roger-melo#85]
Fala Rober blz? A minha dúvida a princípio não é sobre nenhum exercício específico, acredito ser mais uma dúvida técnica mesmo de boas práticas talvez. 
Mas então, eu geralmente dou preferência para arrow function pela escrita simplificada e o costume mesmo. Mas pensei em usa-lá em casos que precise de um retorno imediato ou pra encandear métodos de arrays (um outro mentor me deu essa dica)...O resto só usaria function expression, principalmente se eu estiver lhe dando com classes de objetos pra não perder a referência dos this. Queria saber o que você acha dessa lógica e como você analisa cada situação.
Outra dúvida seria em relação a testes, as functions declarations seriam mais recomendadas que functions expressions? 
Pois não teria a preocupação de chamar uma função indevidamente antes de ela ser declarada. (Na verdade não sei bem se isso seria uma vantagem, em poder chamar uma função antes de ela ser declarada).
É isso, parabéns pela didática e conteúdo do curso. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi PhAssis.

> Mas pensei em usa-lá em casos que precise de um retorno imediato ou pra encandear métodos de arrays (um outro mentor me deu essa dica)...

Pode me dar um exemplo?

> O resto só usaria function expression, principalmente se eu estiver lhe dando com classes de objetos pra não perder a referência dos this. Queria saber o que você acha dessa lógica e como você analisa cada situação.

Se eu não preciso usar o this, uso arrow functions pela concisão que ganho ao usá-las.

```javascript
const myFunc = aParameter => ({
  prop1: 'a'
})

function myFunc (aParameter) {
  return {
    prop1: 'a'
  }
}
```

As funções acima fazem o mesmo (retornam um objeto - você verá mais detalhes sobre essa sintaxe no decorrer do treinamento). A arrow function além de deixar o código mais conciso, me faz digitar menos.

A verbosidade fica ainda mais explícita ao usar currying functions. A arrow function e a function declaration abaixo também fazem a mesma coisa.

```javascript
const getDiscount = discount => price => price * discount

// function getDiscount (discount) {
//   return function (price) {
//     return price * discount
//   }
// }

const getLoyalCustomerDiscount = getDiscount(.10)
const getExcellentCustomerDiscount = getDiscount(.20)
const getAmazingCustomerDiscount = getDiscount(.30)

console.log(
  getLoyalCustomerDiscount(747),
  getExcellentCustomerDiscount(747),
  getAmazingCustomerDiscount(747)
)
```

> Outra dúvida seria em relação a testes, as functions declarations seriam mais recomendadas que functions expressions?

Tanto faz. O que vai dificultar ou deixar os testes mais fáceis são o design do seu código =)

> Pois não teria a preocupação de chamar uma função indevidamente antes de ela ser declarada. (Na verdade não sei bem se isso seria uma vantagem, em poder chamar uma função antes de ela ser declarada).

No TDD, primeiro você testa o happy path, que é a etapa em que esperados são testados.

Na etapa posterior (unhappy path), você testa casos inesperados. É nesta etapa que você pode implementar um teste que verifica se a função existe, por exemplo.

---

Dito isso, quando preciso lidar com o this (dentro de classes, por exemplo), uso function declaration:

```javascript
class Counter {
  #count = 0

  get value () { // sintaxe abreviada de function declaration
    return this.#count
  }
}
```

A grande sacada é evitar o this. E na maioria das vezes, é possível evitá-lo, pois em JavaScript, classes são desnecessárias. É mais prático e descomplicado usar factory functions ou funções construtoras =)

Ficou mais claro?

@PhAssis

**Comment by PhAssis** [comment]
"Mas pensei em usa-lá em casos que precise de um retorno imediato ou pra encandear métodos de arrays (um outro mentor me deu essa dica)..."

O que eu quis dizer sobre o retorno imediato seria não precisar da palavra "return"...
Exemplo:
Usar a função abaixo:  
const dobro = number => number * 2; 

Em vez de usar essa:
function dobro(number){
return number * 2;
}

Sobre o encadeamento, me confundi, na verdade os métodos de array envolve como primeiro parâmetro uma função de callback e independente se eu uso nessa função uma arrow function ou uma function declaration, eu consigo emendar outro método caso seja preciso rsrs
Essa parte de orientação a objeto é a que me preocupava um pouco mais, domino mais a parte do paradigma funcional. 
Mas já nas primeiras aulas vi que não é um bicho de sete cabeças... hehe
Mas é isso, o resto foi bastante esclarecedor...
Obrigado Roger!

**Comment by Roger-Melo** [comment]
Oi PhAssis.

Isso mesmo, se o corpo da função não possui linhas adicionais de processamento, o retorno implícito da arrow function pode ser usado =)

> Sobre o encadeamento, me confundi, na verdade os métodos de array envolve como primeiro parâmetro uma função de callback e independente se eu uso nessa função uma arrow function ou uma function declaration, eu consigo emendar outro método caso seja preciso rsrs

Exatamente!

> Essa parte de orientação a objeto é a que me preocupava um pouco mais, domino mais a parte do paradigma funcional.

Entendi. A grande sacada do JavaScript é que ele é multi-paradigma. Então você pode explorar o melhor de cada paradigma e aproveitar ao máximo o uso da linguagem =)

Fico feliz que as aulas estejam ajudando a esclarecer.

No que precisar, estou à disposição. Conte comigo para chegar na fluência 👊

**Comment by PhAssis** [comment]
Boa Roger, bastante esclarecedor. 
Obrigado mesmo!!!
