### ISSUE TITLE
Etapa 02, nome do vídeo: Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by JuniorAlvesbr** [roger-melo-treinamentos/curso-de-js-roger-melo#850]
Boa tarde Roger tudo bem. Uma duvida

Em vários exercícios como este abaixo, o exercício 5,
```js
const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false, "teste"]

let booleanAmount = 0
let numberAmount = 0
let stringamount = 0

for (let i = 0; i < crazyArray.length; i++) {
  const typeofItem = typeof crazyArray[i]
  const isItemABoolean = typeofItem === 'boolean'
  const isItemANumber = typeofItem === 'number'
  
  if (isItemABoolean) {
    booleanAmount++
  } else if (isItemANumber) {
    numberAmount++
  } else {
    stringamount++
  }
}

console.log(`O crazyArray tem ${booleanAmount} booleans, ${numberAmount} números e ${stringamount} strings.`)
``` 
Eu percebi que dentro do loop for() você declara as variáveis como const, e eu achava que isso daria erro, por 2 dois motivos.
1 - Erro ao tentar redeclarar uma variável existente visto que na primeira interação a variável seria criada e nas próximas daria erro.
2 - Declarar uma variável na primeira interação do for() como const resultaria em erro nas próximas interações já que seu valor não pode ser reatribuído.
Mas pelo que vi o código funcionou normal.

Gostaria de saber porque isso funciona?
Tipo para cada interação do for() as variáveis são deletadas e recriadas, e por isso pode ser usado const ao invés de let?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @JuniorAlvesbr. Você pode declarar consts dentro de um `for` por que a cada execução dele, essas consts vão ser criadas em escopos diferentes. 

Nas primeiras aulas da etapa 5, você verá o que é escopo. Mas claro, se alguma dúvida permanecer, pode abrir uma issue que te ajudo =)

**Comment by JuniorAlvesbr** [comment]
Entendi, eu tinha visto sobre escopo na aula, mas eu achava que o for() rodava em 1 escopo apenas. Pelo que você falou, cada interação do loop é realizado em um escopo diferente próprio, por isso que as conts não colidem . Bacana saber isso.

**Comment by JuniorAlvesbr** [comment]
Respondido

**Comment by Roger-Melo** [comment]
Isso mesmo, cada execução do `for` é feita em um escopo diferente. 

Quando rolarem mais dúvidas, é só abrir uma nova issue =)
