### ISSUE TITLE
Resumo da Aula O método forEach e callbacks - Aula 02-04 da etapa 03

### ISSUE THREAD

**Issue by rohyer** [roger-melo-treinamentos/curso-de-js-roger-melo#854]
# O método forEach e callbacks

## Função de Callback

Também é possível passar funções como argumento em uma função. Essa função que é passada como argumento é chamada de função de callback.

```js
const myFunc = callback => {
  const value = 77;

  callback(value);
}

myFunc(number => {
  console.log(number);
}
```

## ForEach

É um método que itera sobre um array. ForEach significa "para cada", ou seja, para cada item de um array uma ação será executada.

ForEach recebe uma função de callback que pode receber até 3 parâmetros.

1º parâmetro é o item que será iterado em cada execução do forEach;
2º parâmetro é o índice do item que está sendo iterado naquele momento;
3º parâmetro é o array.

**Uma vantagem do forEach em relação ao for é que a função de callback pode ser desaclopada do forEach, deixando o código mais legível, também fazendo com que a função possa ser reutilizável.**

Abaixo, um exemplo com a função sendo declarada dentro do forEach:

```js
const socialNetwork = ['Youtube', 'Twitter', 'Instagram', 'Facebook'];

socialNetwork.forEach((item, index, array) => {
  console.log(index, item, array);
});
```

No exemplo abaixo a função está sendo declarada foram do forEach, fazendo com que ela possa ser reutilizável:

```js
const socialNetwork = ['Youtube', 'Twitter', 'Instagram', 'Facebook'];

const logArrayInfo = (item, index, array) => {
  console.log(index, item, array);
}

socialNetwork.forEach(logArrayInfo);
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @rohyer! Rumo à fluência 🚀
