### ISSUE TITLE
Resumo da Aula Outras maneiras de fazer queries no DOM - Aula 01-08 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#855]
Além do `document.querySelector()` e do `document.querySelectorAll()`, temos outras três maneiras alternativas de fazer *queries* no DOM para obter referências de elementos.

A primeira maneira é obter a referência de um elemento através do ID (este método retorna uma única referência). Então basta verificarmos o atributo id da *tag* que queremos a referência, e passarmos como argumento do método `document.getElementById()`. Vamos supor que tenhamos uma *tag* qualquer com o id *subtitle*. Veja no exemplo abaixo como utilizamos este novo método:

```jsx
const subtitle = document.getElementById('subtitle');
```

A segunda maneira é obter a referência de um elemento através do nome de sua classe CSS. Vamos supor que tenhamos algumas *tags* com a classe *service* e queremos as referências para estes elementos. Veja no exemplo abaixo:

```jsx
const serviceElements = document.getElementsByClassName('service');
```

Este método retorna uma *HTML Collection*, que é uma lista com as referências, ou a referência encontrada. Mas mesmo que retorne apenas uma referência, sempre será uma *HTML Collection*, que é similar ao *Node List*, porém com lista de métodos reduzida, limitada. Por exemplo, não há como utilizarmos o método `forEach()` diretamente em uma *HTML Collection*, mas podemos acessar um elemento através da notação de colchetes.

A terceira maneira é obter a referência para elementos através do nome da *tag*. Para isto utilizamos o método `document.getElementsByTagName()`. O tipo de retorno é uma *HTML Collection*, mesmo que tenhamos apenas uma referência retornada. Veja no exemplo abaixo:

```jsx
const paragraphs = document.getElementsByTagName('p');
```

Mais sobre o *HMTL Collection*: [https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência 🚀
