### ISSUE TITLE
Problemas com a evolução das aulas. Etapa 01 do overview sobre tipos de dados até a aula 03-02

### ISSUE THREAD

**Issue by Euricodeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#857]
Roger, bom dia! 

Minha evolução foi perdida dentro da janela das aulas mencionadas. Ja conclui todas estas aulas porém foram "desmarcadas do progresso".

Pode resolver isso pra mim? Estou nos exercícios da aula 03 neste momento. 

Obrigado.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Euricodeveloper.

Segundo os testes que o pessoal do suporte da plataforma fez, o progresso está funcionando normalmente:

![progresso-01](https://user-images.githubusercontent.com/29297788/121728975-5269d380-cac4-11eb-8cee-871cf4073d03.jpg)
![progresso-02](https://user-images.githubusercontent.com/29297788/121728977-53026a00-cac4-11eb-8df3-a470d6df7767.jpg)

Talvez seja algo em seu navegador, porque até o momento, não houveram queixas de outros alunos com o mesmo problema.

**Comment by Euricodeveloper** [comment]
Perfeito Roger, reiniciei a pagina e voltou ao normal!

**Comment by Roger-Melo** [comment]
Show @Euricodeveloper. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
