### ISSUE TITLE
Etapa 08, Correção dos exercícios da aula 02 da etapa 07 - Aula 01-01

### ISSUE THREAD

**Issue by jonathan93silva** [roger-melo-treinamentos/curso-de-js-roger-melo#86]
Bom dia Roger!

Só me tira umas duvidas por favor, sobre os exercicios que não estão relacionados ao Quiz!

Na hora de converter o texto do counter para "Number", existe uma outra forma que seria utilizando o sinal de "+"
vc fez assim:
```js
const incrementedCounter = Number(counterContainer.textContent) + 1
```
outra forma:
```js
const incrementedCounter = +(counterContainer.textContent) + 1
```

Tem alguma diferença técnica entre os dois? Ou só a legibilidade do código?

E na hora de chamar as funções dentro do evento de click, eu passei a função já como argumento:
```js
const resetCounter = () => {
  clearInterval(timer)
  counterContainer.textContent = 0
}

buttonStop.addEventListener('click', resetCounter)
```

Tem algum problema nessa forma de fazer?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Jonathan.

Isso mesmo, o operador unário `+` e a invocação do constructor `Number()` nesse caso fazem a mesma coisa.

Eu tendo a preferir o `Number()` pela legibilidade. Se você trabalha em um time com pessoas que ainda não tem tanta experiência com a linguagem, por exemplo, em um primeiro momento, o operador unário pode causar confusão =)

Sobre as funções de callback de event listeners, quando referenciamos a função como argumento, o código tende a ficar mais legível, pois estamos nomeando a ação da função.

É mais rápido ler

```javascript
buttonStop.addEventListener('click', resetCounter)
```

do que ler

```javascript
buttonStop.addEventListener('click', () => {
  clearInterval(timer)
  counterContainer.textContent = 0
})
```

Então sim, quando possível, é preferível nomear e deixar explícita a ação que acontecerá quando o evento for disparado =)

@jonathan93silva

**Comment by Roger-Melo** [comment]
Oi Jonathan.

Vou fechar a issue por agora, mas no que precisar, é só abrir uma nova =)
