### ISSUE TITLE
Resumo da Aula Constantes, variáveis e comentários Aula 01-06 da etapa 01

### ISSUE THREAD

**Issue by Marcus2298** [roger-melo-treinamentos/curso-de-js-roger-melo#861]
Resumo da aula

Variáveis são containers onde você armazena valores que podem ser usados pela sua aplicação

Existem alguns tipos de variáveis
  - Let - tipo de variável que pode receber outros valores após sua declaração (volátil)
  - Const - tipo de variável que recebe um valor único e não pode ser alterado 
  - Var - tipo de variável utilizada em versões mais antigas do Java Script, contem propriedades semelhantes a Let

Existem regras para a declaração de variáveis, como:
 - palavras-chave usadas no Java Script, como Const e Let nao podem ser declaradas como variáveis
 - Nao pode conter espaços
 - Podem conter letras, undercase(_), $ e números(exceto no inicio da variável)

Comentários podem ser usados dentro do código sem interferir na aplicação

use // no começo da linha que será comenta

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @Marcus2298. Rumo à fluência! 👊🏻
