### ISSUE TITLE
Resumo da Aula O metodo forEach e callback da etapa 03

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#869]
![foreach_part1](https://user-images.githubusercontent.com/35525950/121819893-08b8ee80-cc66-11eb-9e43-81be0849bc85.jpeg)
![foreach_part2](https://user-images.githubusercontent.com/35525950/121819901-11a9c000-cc66-11eb-913b-0ec109b7cbb0.jpeg)
![foreach_part3](https://user-images.githubusercontent.com/35525950/121819904-15d5dd80-cc66-11eb-8943-40cabf2cb6ff.jpeg)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @AnaCosta29! Rumo à fluência! 🔥
