### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by azulinho10** [roger-melo-treinamentos/curso-de-js-roger-melo#870]
--- https://github.com/azulinho10/Quiz.git ---

Dificulades:

- Foi criar o html. Usei o bootstrap para facilitar na construção da aplicação.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @azulinho10.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise e as respostas das dúvidas serão postadas aqui =)

**Comment by Roger-Melo** [comment]
Olá @azulinho10!

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

Para marcar uma alternativa, o usuário precisa clicar exatamente no input type radio. Isso pode causar um certo desconforto, pois o input é muito pequeno.

Por isso, na aula eu mostrei como inserir o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

Um outro ponto é que talvez, depois de você hospedar o quiz no Netlify (como orientado na bateria de exercícios 20), alguém execute a aplicação no celular. Nesse caso, é bom ficar atento ao o local onde a pontuação é exibida na tela.

No print abaixo, o form foi enviado mas a pontuação é exibida na parte inferior (não-visível) da tela:

![form-enviado](https://user-images.githubusercontent.com/29297788/121883666-642bc080-cce8-11eb-96d5-3a8db98c1d42.png)

Uma alternativa seria inserir o parágrafo acima do botão.

Nas aulas seguintes eu mostro uma forma de implementar a pontuação =)

## Lógica

Como o que está sendo inserido no `paragraph` é uma string e não um HTML, faz mais sentido substituir `paragraph.innerHTML` por `paragraph.textContent`.

## Organização de código

Cuidado para não esquecer console.log's. O `console.log` é útil apenas no momento em que você está desenvolvendo a aplicação. Sempre que enviar código para outra pessoa, prefira removê-los (a não ser que a outra pessoa precise executar aquele console.log também) =)

Para organizar a manipulação do `paragraph`, você pode fazer toda a manipulação primeiro e só depois inserí-lo no DOM. A ordem ficaria mais ou menos assim:

```javascript
  if (score === 0) {
    paragraph.textContent = //...
  } // ...

  paragraph.setAttribute('class', 'container')
  form.insertAdjacentElement('afterend', paragraph)
```

### Local de declaração de variáveis

Você também pode separar consts por tipo para deixar o código mais organizado. 

No exemplo abaixo, as consts que armazenam elementos do DOM foram agrupadas e as outras foram separadas por linhas em branco:

```javascript
// antes
const correctAnswers = ['D', 'C', 'A', 'B']

const form = document.querySelector('.form')
const paragraph = document.createElement('p')
let score = 0

// depois
const form = document.querySelector('.form')
const paragraph = document.createElement('p')

const correctAnswers = ['D', 'C', 'A', 'B']

let score = 0
```

É uma convenção deixar consts que armazenam elementos do DOM no topo do código.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio, `paragraph` é um nome vago para uma const.

Você pode sintetizar no nome, de forma breve, do que se trata o valor que ela armazena. Ela pode ser nomeada como `finalScoreContainer` ou algo do tipo. 

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu deixaria a linha 22 em branco.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by azulinho10** [comment]
Sim. Observarei mais  o código para evitar alguns erros, notei uma evolução
no aprendizado.

Em seg., 14 de jun. de 2021 às 08:22, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @azulinho10! Vou fechar a issue mas no que precisar, é só abrir uma nova =)
