### ISSUE TITLE
Aplicação: QUIZ 

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#871]
### Minha versão
[LINK do Repositorio da aplicação](https://github.com/cdfortes/js-quiz-app.git)

### Maiores dificuldades
- A refatoração e nomear as variaveis/constantes/funções (por forma a fazerem sentido) criam sempre alguma dificuldade, mas com a revisão raio-x têm sido sanados

### Menores dificuldades 
- alterar as cores

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @cdfortes.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise e as respostas das dúvidas serão postadas aqui =)

**Comment by Roger-Melo** [comment]
Olá @cdfortes!

Parabéns pelo esforço em construir a primeira aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar.

### Nomes de variáveis e funções

Como em inglês as palavras possuem uma ordem diferente do português, eu renomearia `alertResult` para `resultAlert` e `insertAlertOfResultInDOM` para `insertResultAlertInDOM`.

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio, para descrever a ação que `hasCorrectAnswer` executa, eu a renomearia como `calculateUserScore` ou `calculateScore`.

### Organização de declaração de variáveis

Você pode separar consts por tipo para deixar o código mais organizado.

No exemplo abaixo, as consts que armazenam elementos do DOM foram agrupadas e as outras foram separadas por linhas em branco:

```javascript
// antes
const correctAnswers = ['B', 'B', 'B', 'A']
const form = document.querySelector('.quiz-form')
let score = 0

const alertResult = document.createElement('div')

// depois
const form = document.querySelector('.quiz-form')
const alertResult = document.createElement('div')

const correctAnswers = ['B', 'B', 'B', 'A']

let score = 0
```

É uma convenção deixar consts que armazenam elementos do DOM no topo do código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by cdfortes** [comment]
olá @Roger-Melo,

Obrigado pelo feedback!

observações muito esclarecedoras, concerteza melhorarão muito o meu código!
Rumo a Fluência 👍🏿 💯

**Comment by Roger-Melo** [comment]
Show! No que precisar, é só abrir uma nova issue =)

Rumo à fluência! 🔥
