### ISSUE TITLE
Resumo das Aulas 4-2, 4-3 e 4-4 da etapa 1

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#872]
# Aula 4-2
## Booleans 
Valores especiais usados para verificar se uma pedaço de código é true ou false

console.log(true, false, 'true', 'false');
 true e false são booleans, e 'true' e 'false' são strings 
'false' === false retorna false, pois são dados de tipos diferentes.

##  includes() 
 método que verifica se o argumento passado existe dentro da string e retorna um boolean 

const email = 'brucewaine@elaine.com.br'
const includes = email.includes('@') 
console.log(includes)
retorna: true, pois '@ está incluso na string includes  

const people = ['dio', 'elaine', 'joao']
const arrayIncludes = people.includes('rob')
console.log(arrayIncludes); 
retorna: false, não existe 'rob' dentro da array people 

const age = 31  

console.log(age == 31);
retorna: true 

console.log(age == '31')
retorna: true, a string '31' foi convertida implicitamente pelo javascript pois quando usamos o sinal duplo de = (ou !=)
uma expressão envolvendo tipos de dados diferentes podem resultar em true devido a conversão de tipos.
console.log(age != 35) 
retorna: true, 31 não é igual a 35

console.log(age > 30)
retorna: false, 31 não é maior que 35

console.log(age >= 31)
retorna: false, 31 não é maior que 31, mas é igual

const myName = 'Elaine'

console.log(myName == 'elaine')
retorna: false, pois o javascript difere caracteres maiúsculas de caracteres minúculas

console.log(myName > 'Ana')
retorna: true, e > a porque a letra 'e' vem antes de 'a' no alfabeto, portanto seu valor é menor  

console.log(myName > 'elaine')
retorna: false pois em javascript caracteres maiusculos são menores que maiusculos 

# Aula 4-3 
## Comparação estrita 
O sinal === (strict comparison) é usado para comparar  se os dados e seus tipos são iguais 

###  == para comparar dois valores:
const age = 31 

console.log(age == 31)
retorna: true

console.log(age == '31')
retorna: true, 31 é igual a 31, embora não sejam do mesmo tipo o javascript executa a conversão de tipos quando usamos == ou != para comparar dois valores que são de tipos diferentes

### usando === e !=== para comparar dois valores
Quando usamos esses operadores para comparar valores o javascript não executa a conversão de tipo 
e a comparação é extremamente precisa

console.log(age === 31)
retorna: true, 31 é 31 e é do mesmo tipo

console.log(age === '31') 
retorna: false , pois 31 é igual a 31, mas não é do mesmo tipo 

console.log(age !== 31) 
retorna: false, 31 não é diferente de 31, e não são de tipos diferentes tampouco

console.log(age !== '31') 
retorna:  true, embora 31 seja igual a '31', não são do mesmo tipo 

# Aula 4-4 
## Conversão de tipos 
 Podemos converter explicitamente, de forma intencional, a conversão de valores quando precisamos.

let score = '100' 
console.log(score + 1) 
retorna: 1001,  como o sinal de + pode ser usado
 para concatenar strings, é isso que o javascript faz, ele usa o sinal de  + para concaternar, juntar, os valores, em vez de somá-los

console.log(score - 1) 
retorna: 99
o sinal de menos só serve para subtrair, então o javascript converte a string para número 

###  Podemos utilizar a função construtora Number() para converter uma string em número
score = Number(score)
console.log(score + 1) 
retorna: 101 , pois Number() coverteu a string, que agora é um número, e podemos somar os valor de 100 a 1

### Um dos meios de se verificar o tipo de um dado usando typeof 
console.log(typeof score)
retorna: number

###  Convertendo uma string em number quando essa é formada por letras:

const crazyConversion = Number('Maçã') 
console.log(crazyConversion) 
retorna: NaN, pois tentamos converter um valor que não pode ser convertido em number,
 então essa operação foi fracassada e retornou um NaN.

###  Convertendo um number em string:

const convertedNumber = String(97)
console.log(convertedNumber, typeof convertedNumber)
retorna: 97 string 
podemos converter string para number e number para string desde que seja formada por número(s), mas 
não é possível converter, obviamente, uma string formada por letras em number 

###  Convertendo uma valor em Boolean: 
const booleanConvertion = Boolean(10)
console.log(booleanConvertion, typeof booleanConvertion)
retorna: true "boolean" 
console.log(Boolean(0)) 
retorna: false, pois 0 é um valor falsy em javascript 

###  Valores falsy em Javascript: 
false, '', "" e `` (strings vazias), null, undefined, NaN

console.log(Boolean('0')) 
retorna true, pois agora 0 é uma string com um valor, e não o número zero (falsy) em javascript 

Essas foram conversões explícitas, conversões feitas intencionalmente para converter tipos de dados.
Existem também as conversões implícitas que são as que o javascript faz por baixo dos panos,
como por exemplo: 

let age = '43'
console.log(age - 20) 
que retorna 23, pois como o sinal de subtração é usado apenas para esse propósito em javascript,
ele tenta converter essa string para número, e conseguindo, ele resolve a operação. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Excelente @ElaineDelgado! Rumo à fluência! 🔥
