### ISSUE TITLE
Aplicação: Conversor de moedas

### ISSUE THREAD

**Issue by sou-gabriel** [roger-melo-treinamentos/curso-de-js-roger-melo#873]
Fala professor, tudo ótimo contigo? 😁
Venho compartilhar minha aplicação de conversor de moedas. 

### Maiores dificuldades
- Acredito que uma das minhas maiores dificuldades foi querer implementar a minha aplicação muito parecida com a tua, mesmo antes de ver a correção, não parece algo intuitivo, óbvio, mas uma explicação é que sempre tento deixar minha aplicação como se já estivesse visto a correção, ou seja, como você a faria, e isso me rouba muito tempo e até as vezes me desmotiva por não alcançar um resultado esperado. Desculpas se não foi muito claro este ponto.
- Refatoração do código. Ainda não me sinto muito confiante para refatorar ou até mesmo escrever um bom código professor, mas isso acredito que virá com a prática, e essa aplicação me ajudou a elevar essa habilidade um pouco, apesar das dificuldades.
- Definir bons nomes para minhas funções, e isso implica em outra coisa: definir se minha função está ou não com excesso de responsabilidade

### Menores dificuldades
- Entender cada detalhe técnico da minha aplicação e o que cada instrução da minha aplicação está realizando. Neste ponto do treinamento me sinto bem afiado e a vontade com todas as features da linguagem apresentadas até então;
- Implementar os estilos com Bootstrap;
- Manipulação do DOM.

## Links
- Repositório: https://github.com/sou-gabriel/conversor-de-moedas
- Aplicação: https://conversor-de-moedas.netlify.app/

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @sou-gabriel.

Passando para dizer que visualizei sua issue e se estiver tudo ok com a aplicação, em breve a análise e as respostas das dúvidas serão postadas aqui =)

**Comment by Roger-Melo** [comment]
Olá @sou-gabriel! Tudo certinho, e tu?

Parabéns pelo esforço em construir a quarta aplicação. Deu pra perceber que você pegou bem a lógica até aqui =)

> Acredito que uma das minhas maiores dificuldades foi querer implementar a minha aplicação muito parecida com a tua...

Isso é natural. Com a prática e o tempo, você irá desenvolver o seu estilo (caso trabalhe sozinho) ou irá fazer um fit com o estilo do seu time. Tomara que o time tenha uma pegada mais funcional 😂

> Refatoração do código. Ainda não me sinto muito confiante para refatorar...

Isso mesmo, aos poucos vai entrando na cabeça =)

Mas no caso das aplicações do CJRM, o ideal é enviá-las antes de refatorar mesmo. A prioridade é checar se o aluno entendeu como fazer funcionar. Nas aulas seguintes você verá formas de refatorar esse código.

> Definir bons nomes para minhas funções, e isso implica em outra coisa: definir se minha função está ou não com excesso de responsabilidade.

Pelo que vi, os nomes que você deu estão bem descritivos.

Sobre o excesso de responsabilidade, acredito que isso vai começar a ficar mais claro quando entrarmos em testes. Um dos maiores problemas de funções que fazem mais de uma ação é que elas são difíceis de testar e manter.

Um ponto de atenção segundo os critérios que usei para analisar foi uma ocorrência de inconsistência ao declarar funções com apenas 1 parâmetro.

No caso, essas funções:

```javascript
const populateSelects = conversionRates => { 
  //... 
}

const showConversionRateInfo = (conversionRates) => { 
  //... 
}
```

O ideal é você escolher se, quando uma função tiver apenas um parâmetro, ele será envolvido ou não entre parênteses e aplicar essa escolha em todas as funções. 

---

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by sou-gabriel** [comment]
> Tomara que o time tenha uma pegada mais funcional 😂

Real professor, será o melhor para ambos, disso não tenho dúvidas 😁.

> Um ponto de atenção segundo os critérios que usei para analisar foi uma ocorrência de inconsistência ao declarar funções com apenas 1 parâmetro.

Hmm, é verdade professor, não me atentei neste detalhe durante a implementação da aplicação. Vou padronizar todos esses casos.

> As observações fizeram sentido?

110%. Fiquei muito feliz em ter esta análise professor. Fiquei ainda mais motivado por ter essa percepção do meu progresso na linguagem.

**Comment by Roger-Melo** [comment]
Excelente @sou-gabriel. 

Vou fechar a issue mas no que precisar, é só abrir uma nova =)
