### ISSUE TITLE
Resumo da Aula 01-03 da etapa 04

### ISSUE THREAD

**Issue by henriquesabarah** [roger-melo-treinamentos/curso-de-js-roger-melo#877]
Usa-se as chaves {} para criar um objeto literal. Dentro das chaves o objeto terá uma propriedade com um valor atribuído a ela, separado por dois pontos : e cada propriedade é separada por vírgulas.

let users = {
name: 'João',
age: 31,
email: 'joao@email.com'
} 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @henriquesabarah, vamo que vamo, rumo à fluência! 🚀
