### ISSUE TITLE
Etapa 7, Exercício da Aula 01

### ISSUE THREAD

**Issue by erichporto** [roger-melo-treinamentos/curso-de-js-roger-melo#88]
Link da minha versão do exercício 
https://github.com/erichporto/quiz-cjrm

Minha maior dificuldade foi tentar utilizar o componente modal do próprio Bootstrap para apresentar o resultado do usuário na tela. Não consegui utilizar o modal do Bootstrap com o evento 'submit' do form pelos os métodos que o Bootstrap indica, então fiz um modal do zero baseado na aula do Popup.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Erich.

Passando para avisar que sua issue foi recebida e visualizada, e que o feedback será publicado aqui em breve =)

@erichporto

**Comment by Roger-Melo** [comment]
Oi Erich. Parabéns pelo esforço em implementar a aplicação =)

Vou deixar abaixo algumas considerações.

## 3 Pontos fortes do projeto

### 1. Modal para exibir o resultado

Mesmo que não tenha usado o modal do Bootstrap, você fez o seu baseado no que foi mostrado em aulas anteriores. Muito bom, isso demonstra que você se empenhou em usar o que viu até aqui para implementar uma feature.

### 2. Bons nomes de variáveis

No geral, os nomes de suas variáveis, e funções estão legíveis e fáceis de entender.

### 3. Evitou if/else

No código abaixo, 

```javascript
if(isBadResult){
   modalResultMessage('Podia ser melhor',score)
   return
}
modalResultMessage('Muito bem =)',score)
```

você soube usar o `return` ao invés de encadear um `if/else`. Isso deixa o código mais limpo e legível.

## 3 principais oportunidades de melhoria

### 1. Lógica

Para alcançar o mesmo resultado e deixar a expressão `const isBadResult = !(score > 50)` mais legível, você pode eliminar o operador not e inverter a lógica:

```javascript
// antes
const isBadResult = !(score > 50)

// depois
const isBadResult = score <= 50
```

Dessa forma, a `const isBadResult` receberá `true` se o score é menor ou igual 50.

O código abaixo possui uma outra oportunidade de melhoria:

```javascript
const modalNotClose = ['modal-frame','modal-message','modal-score','modal-container']

// ...

const closeable = !(modalNotClose.some( item => item === clickedElement))
```

Observe que se a `const closeable` for renomeada para `closeableElementWasClicked` e a lógica que ela contém for invertida (ou até simplificada com um `includes` e a remoção do `!`), podemos inserir como itens do array da `modalNotClose` apenas os elementos do DOM que devem fechar o popup ao serem clicados. Isso iria inserir menos itens no array, pois o popup contém menos elementos que devem fechá-lo ao serem clicados do que o contrário. E claro, a `modalNotClose` teria que ser renomeada para `closeableElements`, por exemplo:

```javascript
modal.addEventListener('click', event => {
  const clickedElement = event.target.classList[0]
  const closeableElements = ['modal-button', 'modal-close', 'modal-wrapper']
  const closeableElementWasClicked = closeableElements.includes(clickedElement)

  if (closeableElementWasClicked) {
    modal.style.display = 'none'
  }
})
```

Existem várias formas de identificar elementos. A abordagem usando classes é só uma delas. Mais a frente no treinamento, você verá uma aula onde mostro qual é o atributo ideal a ser inserido em um elemento quando é necessário manipulá-lo via JavaScript.

Tome cuidado com o uso do `not` operator (`!`). Evitá-lo pode deixar o código menos complexo.

Sempre que possível, evite reatribuir valores para parâmetros de funções. No código abaixo, a expressão `index += 1` faz o parâmetro `index` receber o valor que ele tem somado a 1. Ao aproveitar o `index` para executar uma contagem não-zero-based, prefira apenas somar 1 ao `index` e o resultado será o mesmo.

```javascript
// antes
correctAnswers.forEach((answer, index) => {
  index += 1
  
  const userAnswer = form[`inputQuestion${index}`].value
  // ...
})

// depois
correctAnswers.forEach((answer, index) => {  
  const userAnswer = form[`inputQuestion${index + 1}`].value

  // ...
})
```

Ao fazer comparações, sempre use o operador de igualdade estrita `===` ('igual a, e do mesmo tipo'). Os resultados dele são mais previsíveis e seguros, pois ele não faz conversão de tipos por baixo dos panos, como mostrei e recomendei [nessa aula](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/751262).

Então ao invés de `if(answer == userAnswer) {}`, use `if(answer === userAnswer) {}`.

A `const tryAgainButton` foi declarada no topo do código, mas não está sendo usada.

### 2. Local em que as consts são declaradas

No bloco de declarações de consts abaixo,

```javascript
const correctAnswers = ['B','B','B','B']
const form = document.querySelector('form')
const tryAgainButton = document.querySelector('.modal-button')
const modal = document.querySelector('.modal-wrapper')
const modalMessage = document.querySelector('.modal-message')
const modalScore = document.querySelector('.modal-score')
const modalNotClose = ['modal-frame','modal-message','modal-score','modal-container']
```

há consts que obtém referências de nós do DOM e consts que armazenam arrays. Prefira separar consts que fazem coisas diferentes. Isso dará mais consistência ao código:

```javascript
const form = document.querySelector('form')
const tryAgainButton = document.querySelector('.modal-button')
const modal = document.querySelector('.modal-wrapper')
const modalMessage = document.querySelector('.modal-message')
const modalScore = document.querySelector('.modal-score')

const correctAnswers = ['B','B','B','B']
const modalNotClose = ['modal-frame','modal-message','modal-score','modal-container']
```

Faz mais sentido deixar a const `modalNotClose` próxima de onde ela é usada, pois não é um array que será usado em mais de uma funçao da aplicação. Por isso, ao renomeá-la, deixei ela dentro do callback do listener de eventos do modal:

```javascript
modal.addEventListener('click', event => {
  // ...
  const closeableElements = ['modal-button', 'modal-close', 'modal-wrapper']
  const closeableElementWasClicked = closeableElements.includes(clickedElement)
  // a const closeableElements só é usada na linha acima

  // ...
})
```

### 3. Linhas em branco

Use linhas em branco para indicar, visualmente, a separação entre conceitos.

Como armazenar um valor, verificar se esse valor é `truthy` e executar uma função são conceitos distintos, você pode deixar uma linha em branco entre eles:

```javascript
// antes
const showResult = score => {
  const isBadResult = !(score > 50)
  if (isBadResult) {
    modalResultMessage('Podia ser melhor', score)
    return
  }
  modalResultMessage('Muito bem =)', score)
}

// depois
const showResult = score => {
  const isBadResult = !(score > 50)

  if (isBadResult) {
    modalResultMessage('Podia ser melhor', score)
    return
  }

  modalResultMessage('Muito bem =)', score)
}
```

Se o bloco conter apenas duas linhas (como o do if acima), você pode quebrar o princípio.

No mais, é isso meu caro. Parabéns novamente pelo esforço em impementar a aplicação. Conte comigo para chegar na fluência =)

@erichporto

**Comment by erichporto** [comment]
Gratidão pela correção, Roger! Em frente em busca da fluência! Abraço!

**Comment by Roger-Melo** [comment]
Show, Erich! Por agora vou fechar a issue, mas no que precisar, é só dar o toque =)

Rumo à fluência 👊
