### ISSUE TITLE
Aplicação: To-do List

### ISSUE THREAD

**Issue by DanThug** [roger-melo-treinamentos/curso-de-js-roger-melo#881]
Repositório da aplicação to-do [To-do List](https://github.com/DanThug/To-do-List)
Minhas maiores dúvidas foram em como refatorar a remoção da LI sem navegar pelo DOM utilizando parentElement e refatorar a busca.
Minhas menores dificuldades foram na separação das funções.

PS: Desculpe não ter respondido a Issue da aplicação do Quiz, ainda não me acostumei a usar o GitHub e acabei só vendo hoje a sua resposta. Devo realizar as correções e criar outra Issue? ou segue o jogo? rs

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @DanThug.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

Quanto às observações do quiz, não precisa enviar novamente. Apenas veja se as observações fizeram sentido e se houver alguma dúvida, é só perguntar =)

**Comment by Roger-Melo** [comment]
Olá @DanThug!

Parabéns pelo esforço em construir a segunda aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Lógica

Nunca declare consts ou lets sem as palavras-chave `const` ou `let`, pois isso pendura uma variável global no objeto `window`:

```javascript
deleteTodo = index => {
  // ...
}

console.log(window.deleteTodo) // index => {...}
```

Sempre que possível, evite variáveis globais. Elas podem ser modificadas de qualquer lugar da aplicação, podem se sobrescrever (se duas variáveis globais tiverem o mesmo nome) e minam a modularidade do código.

A `searchTodo` pode ser apenas referenciada como callback do listener de input:

```javascript
const searchTodo = event => {
  const inputValue = event.target.value.trim().toLowerCase()
  // ...
}

// ...

inputSearchTodo.addEventListener('input', searchTodo)
```

Eu não mostrei `toLocaleLowerCase` no treinamento. O desafio é você resolver exercícios e construir aplicações com apenas o que viu no treinamento.

`if`s de uma ou duas linhas tendem a ser mais legíveis que `if/else` (minha opinião). Ao fazer isso, você está aplicando uma técnica de design de código chamada [early return](https://dev.to/jenniferlynparsons/early-returns-in-javascript-5hfb).

```javascript
// antes
if (containsValue) {
  todo.classList.remove('hidden')
} else {
  todo.classList.add('hidden')
}

// depois
if (containsValue) {
  todo.classList.remove('hidden')
  return
}
  
todo.classList.add('hidden')
```

No código acima, um nível de indentação desnecessário e um caminho à mais que seu cérebro precisava percorrer foram removidos.

## Organização de código

### Nomes de variáveis e funções

`firstElementOfLi` não seria `firstElementOfUl`?

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio, vou deixar abaixo algumas sugestões de nomes.

`ul` é um nome muito vago. Ela pode ser renomeada para `todosContainer` ou `todosList`. 

`form` e `alert` podem ser renomeadas para `formAddTodo` e `alertForInvalidTodo`. Vou falar sobre tratamento de erros, como o alert, quando entrarmos em TDD.

`trashClicked` pode ser renomeada para `trashWasClicked`.

`todosInArray` não é um nome muito adequado para uma função pois não descreve a ação que ela executa. Ela pode ser renomeada para `getTodos`. O mesmo vale para `todoAlreadyExists`, que pode ser renomeada para `checkIfTodoAlreadyExists` ou `checkForDuplicatedTodos`.

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by DanThug** [comment]
Obrigado pelo excelente feedback, com certeza foi falta de atenção minha, pois sei que não se deve declarar uma variável sem a palavra chave "_const_" ou "_let_", o mesmo ocorreu com o "_toLocaleLowerCase_", era para ser "_toLowerCase_", provavelmente o autocomplete trocou e como não gerou erro, acabei nem percebendo. Na questão de nomear variaveis e funções, realmente eu tenho dificuldade, geralmente eu penso em algo rápido só para não parar o ritmo de escrita do código. Já fiz outros cursos de JS e acostumei a usar **if/else**, mas vou tentar utilizar apenas **ifs** nesses casos. Farei as correções e se as dúvidas forem aparecendo eu aviso aqui. :)

**Comment by Roger-Melo** [comment]
Legal @DanThug. No que precisar, é só dar o toque =)
