### ISSUE TITLE
Resumo da Aula Adicionando e modificando conteúdo em uma página - Aula 02-02 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#884]
Além de obter a referência de um elemento no DOM, também é possível manipular este elemento, para alterar seu conteúdo, por exemplo. Então para exemplificar, vamos partir da seguinte estrutura mínima de HTML:

```html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title>Adicionando e modificando conteúdo em uma página</title>
  </head>
  <body>
    <h1>Adicionando e modificando conteúdo em uma página</h1>

    <div>
      <p>Hello world!</p>
      <p>Oi</p>
      <p class="error">Essa é uma mensagem de erro</p>
    </div>

    <div class="content">
      <p>Conteúdo aqui</p>
    </div>

    <script src="./app.js"></script>
  </body>
</html>
```

No mesmo diretório, vamos criar o arquivo app.js e começar a trabalhar nele para fazer as manipulações.

Primeiro vamos fazer um `querySelector()` para obter a referência do primeiro parágrafo, para em seguida modificar seu texto. Então para isso declaramos uma constante *paragraph* com o método `querySelector()`, passando como argumento a *string* 'p', e irá resultar no primeiro parágrafo que foi encontrado na página. Se exibirmos o conteúdo da constante *paragraph* no console, veremos que ela irá exibir as *tags* e seu conteúdo. Para exibirmos apenas seus texto, podemos utilizar a propriedade `.innerText`. Ao encadearmos ao *paragraph* a `.innerText`, iremos obter apenas seu texto. Se quisermos modificar este texto, basta atribuir um novo valor ao `.innerText` da constante *paragraph*. Se quisermos adicionar um texto ao já existente, podemos utilizar o operador *addition assignment* (+=), e então o texto que já existia permanecerá, e o novo texto será adicionado ao fim do já existente. Vamos ver na prática:

```jsx
const paragraph = document.querySelector('p');

console.log(paragraph.innerTexto); // Hello world!

paragraph.innerTexto += " Texto inserido."; // Resultado no DOM: <p>Hello world! Texto inserido.</p>
```

Agora vamos modificar o texto de múltiplos elementos, por exemplo, modificar o texto de todas as *tags* `<p>` da página. Para isso criamos uma constante *paragraphs* e utilizamos o `querySelectorAll()` passando como argumento a *string* 'p'. Com isso obtemos um *NodeList* com as referências das *tags* `<p>` da página. Então como temos um *NodeList*, podemos utilizar  `forEach()` para iterar sobre ele e modificar o texto de cada um. Vamos ver na prática:

```jsx
const paragraphs = document.querySelectorAll('p');

paragraphs.forEach((paragraph, index) => {
	paragraph.innerText += ` Novo texto ${index + 1}`
});

// No cópdigo HTML, os parágrafos ficarão assim:
// <p>Hello world! Novo texto 1</p>
// <p>Oi Novo texto 2</p>
// <p class="error">Essa é uma mensagem de erro Novo texto 3</p>
// <p>Conteúdo aqui Novo texto 4</p>
```

Também podemos adicionar ou modificar o HTML, e para isso utilizamos a propriedade `.innerHTML`. Para exemplificar isso vamos obter a referência da `<div>` com a classe 'content', e em seguida vamos inserir um novo HTML.

```jsx
const div = document.querySelector('.content');

div.innerHTML = '<h2>Novo h2</h2>';

// No cópdigo HTML, a div ficará assim
// <div class="content">
// <h2>Novo h2</h2>
// </div>
```

Ao invés de substituir todo o conteúdo, podemos com o `.innerHTML` também adicionar um novo código HTML ao já existente utilizando o *addition assignment* (+=).

Agora imagine que tenhamos uma lista de nomes vinda do banco, em um *array*, e queremos inserir estes nomes dentro da `<div>` que temos como referência. Para isso basta utilizamos o `forEach()` para iterarmos sobre esta lista e utilizarmos a propriedade `.innerHTML` para inserirmos cada um dos nomes. Vamos ver na prática:

```jsx
const people = ["Phoebe", "Monica", "Rachel"];

people.forEach((person) => {
  div.innerHTML += `<p>${person}</p>`;
});
```

Com isto, cada um dos nomes estará dentro da *tag* `<p>` e as *tags* `<p>` estarão listadas dentro da *tag* `<div>` que temos como referência. As propriedades `.innerText` e `.innerHTML` são tanto *getters* como *setters*. Elas tanto obtém um elemento como atribuem um novo valor a este elemento.

Mais sobre o innerText: [https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText)

Mais sobre o innerHTML: [https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas, rumo à fluência! 👊🏻
