### ISSUE TITLE
callback is not a function error

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#89]
Roger, primeiro gostaria de agradecer pelo curso, ja venho com uma pequena bagagem inicial de js de alguns cursos e estou conseguindo acompanhar tranquilo. 

bom estou no exercício 09-09 callbacks

montei a seguinte resolução.

160 const callCallback = callback => {
161  callback()
162 }
163const name = 'henrique'
164
165 const showMyName = name => console.log(`meu nome é ${name}`)
166
167 const myName = showMyName(name)
168
169 callCallback(myName)
170 

porém, no console do chrome, além de exibir a string 'meu nome é henrique', também exibe o erro dizendo que callback is not a function  app.js 161 conforme abaixo. 

![image](https://user-images.githubusercontent.com/68160678/99910795-d1392380-2cce-11eb-8c80-95a20c2cc44a.png)

como em sua correção não ocorreu o erro, saberia me ajudar com qual o motivo deste?

**Comment by henriquebazi** [comment]
> Roger, primeiro gostaria de agradecer pelo curso, ja venho com uma pequena bagagem inicial de js de alguns cursos e estou conseguindo acompanhar tranquilo.
> 
> bom estou no exercício 09-09 callbacks
> 
> montei a seguinte resolução.
> 
> 160 const callCallback = callback => {
> 161 callback()
> 162 }
> 163const name = 'henrique'
> 164
> 165 const showMyName = name => console.log(`meu nome é ${name}`)
> 166
> 167 const myName = showMyName(name)
> 168
> 169 callCallback(myName)
> 170
> 
> porém, no console do chrome, além de exibir a string 'meu nome é henrique', também exibe o erro dizendo que callback is not a function app.js 161 conforme abaixo.
> 
> ![image](https://user-images.githubusercontent.com/68160678/99910795-d1392380-2cce-11eb-8c80-95a20c2cc44a.png)
> 
> como em sua correção não ocorreu o erro, saberia me ajudar com qual o motivo deste?

**Comment by henriquebazi** [comment]
Bom, pela falta de atenção havia um console.log, e por isso a string no console.
mas ainda sim, ainda tenho o  erro.

**Comment by Roger-Melo** [comment]
Oi Henrique.

Legal, o que está acontecendo é que o parâmetro `callback` não está recebendo **a declaração** de uma função.

No código abaixo,

```javascript
const callCallback = callback => {
  callback()
}

const name = 'henrique'

const showMyName = name => console.log(`meu nome é ${name}`)
const myName = showMyName(name)

callCallback(myName)
```

observe que a invocação da função `showMyName(name)` retorna o valor que a invocação de `console.log(`meu nome é ${name}`)` retorna.

A invocação do `console.log()` é um pedaço de código que exibe algo no console mas não retorna um valor. E em JavaScript, toda expressão ou pedaço de código que não retorna um valor, retorna `undefined`. Então `console.log(`meu nome é ${name}`)` retorna `undefined`.

```javascript
// retorna undefined ao ser invocada
const showMyName = name => console.log(`meu nome é ${name}`)
```

Ou seja, como a invocação da `showMyName(name)` está retornando `undefined` e a `const myName` está armazenando esse `undefined`, quando `callCallback(myName)` é invocada, o argumento `myName` armazena `undefined` e o parâmetro `callback` da função `callCallback` está armazenando o `undefined`.

Se antes da invocação do callback você invocar um `console.log()` que recebe `callback`,

```javascript
const callCallback = callback => {
  console.log(callback)
  callback()
}
```

no console, acima da linha do erro, `undefined` será exibido.

Para resolver este problema, é só você inserir a **declaração** ou a **referência** de uma função como argumento da invocação da `callCallback`.

```javascript
const callCallback = callback => {
  callback()
}

// Opção 1: a declaração da função é inserida como argumento
callCallback(() => console.log('oi'))

// ou

// Opção 2: myFunc é referenciada como argumento
const myFunc = () => console.log('oi')

callCallback(myFunc)
```

Como em seu exemplo, a função `showMyName` precisa receber um valor no parâmetro `name`, a invocação da `callback` precisa receber esse valor como argumento. Para inserir a const `name` como argumento, você pode mover a declaração dela para acima ou para dentro da declaração da função `callCallback`.

Sacou a ideia?

@henriquebazi

**Comment by henriquebazi** [comment]
Saquei sim! obrigado ;)

**Comment by Roger-Melo** [comment]
Legal! Como a dúvida foi esclarecida, vou fechar a issue. Mas no que precisar, é so abrir uma nova =)
