### ISSUE TITLE
Etapa 2, nome do vídeo: correção exercicios da aula 02 -Aula 03-01

### ISSUE THREAD

**Issue by Euricodeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#891]
Roger, bom dia! 

Não me sinto a vontade em refatorar mesmo acompanhando você. Isto é normal? Posso continuar assim mais um tempo?

Abraço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Euricodeveloper! Não se preocupe, isso é natural. 

No início, o mais importante é fazer funcionar. A refatoração vai fazer mais sentido com a prática e o tempo =)

**Comment by Roger-Melo** [comment]
@Euricodeveloper vou fechar a issue mas no que precisar, é só abrir uma nova =)
