### ISSUE TITLE
Resumo da Aula O método forEach da etapa 03

### ISSUE THREAD

**Issue by edcabralc** [roger-melo-treinamentos/curso-de-js-roger-melo#894]
## Método forEach

- Uma forma mais eficiente e moderna de iterar sobre dados. 
- Recebe uma função de `callback` como parâmetro onde podemos passar três argumentos: o elemento a ser iterado, o index desse elemento e o `array` que está sendo iterado, esses dois últimos são opcionais.

```js
const numbers = [22, 33, 44, 55, 66]

numbers.forEach(number => {
  console.log(number)
})
```

**Obs**: Métodos e funções são basicamente a mesma coisa, muda o nome e a forma de invocar.**

**Para melhorar o entendimento do código podemos desacoplar a função de `callback` do `forEach` e referenciar essa função com uma `const`**

```js
const numbers = [22, 33, 44, 55, 66]

const getNumbers = number => console.log(number)

numbers.forEach(getNumbers) \\ 22 33 44 55 66
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @edcabralc, rumo à fluência! 👊🏻
