### ISSUE TITLE
Etapa 03, nome do vídeo: O que são funções - Aula 01-02

### ISSUE THREAD

**Issue by Euricodeveloper** [roger-melo-treinamentos/curso-de-js-roger-melo#897]
Roger, boa noite! 

A partir de qual momento eu posso estudar um framework em paralelo, como o NODE JS ou REACT JS? 

Abraço.

@Roger-Melo

**Comment by Roger-Melo** [comment]
A minha recomendação é que você estude isso após conseguir construir aplicações web com JavaScript puro. Antes disso, você ficará confuso. Eu falei sobre isso na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Lá tem o passo a passo do que eu recomendo que você faça =)

@Euricodeveloper
