### ISSUE TITLE
Dúvida na correção do quiz

### ISSUE THREAD

**Issue by viniciuscosta89** [roger-melo-treinamentos/curso-de-js-roger-melo#9]
Boa tarde, @Roger-Melo .

Uma coisa que notei aqui, é que ao clicar a primeira vez no botão "Enviar" com as respostas selecionadas (somente algumas corretas), ele calcula e mostra o resultado lá em cima. Beleza.

Só que se você muda suas respostas e seleciona mais uma alternativa correta, o que faz aumentar seu score, ao clicar em "Enviar", ele mostra um score diferente do que deveria mostrar.

Por ex:
- Você só pontua em uma questão na primeira vez. Ao clicar no "Enviar", o Score é 25.
- Você agora acerta outra questão e clica em "Enviar" novamente. O score deveria ser 50, mas aqui ficou dando 75. É como se ele pegasse o Score anterior, que era 25, e somado a essas respostas novamente. 25 + 50. Seria porquê, ao clicar no "Enviar", você não está zerando o Score, ñ é?

Eu coloquei um `score = 0` dentro do "submit" do form e resolveu esse bug. É isso mesmo?

**Comment by Roger-Melo** [comment]
Oi @viniciuscosta89! Legal cara, faz todo o sentido sim =)

**Comment by Roger-Melo** [comment]
@viniciuscosta89 você também pode adicionar uma verificação se a pontuação é maior que zero no momento do envio do form.

Se for, a pontuação recebe 0 antes de ser calculada novamente. Sacou a ideia?

**Comment by viniciuscosta89** [comment]
> @viniciuscosta89 ou então você pode adicionar uma verificação se a pontuação é maior que zero no momento do envio do form.
> 
> Se for, a pontuação recebe 0 antes de ser calculada novamente. Sacou a ideia?

Sim! Pode ser tbm =)

**Comment by Roger-Melo** [comment]
Oi @viniciuscosta89.

Estou fechando a issue, mas no que precisar é só dar o toque!
