### ISSUE TITLE
Etapa 7 - Exercícios da aula 1 (Quiz)

### ISSUE THREAD

**Issue by Galvaothiago** [roger-melo-treinamentos/curso-de-js-roger-melo#90]
Bom dia. Estou adorando o curso, sua didática e tudo mais, sensacional.
Nesse exercício a minha maior dificuldade foi decidir como iria inserir o feedback para o usuário no contexto do HTML, testei algumas maneiras e fiz algumas pesquisas. Tive facilidade em implementar a logica já vista durante o curso, não precisei revisar essa parte, consegui executar tranquilamente. Espero conseguir manter esse ritmo até o final do curso. Muito Obrigado!

@Roger-Melo
[https://github.com/Galvaothiago/aula-quiz.git](https://github.com/Galvaothiago/aula-quiz.git)

**Comment by Roger-Melo** [comment]
Oi Thiago.

Passando para avisar que sua issue foi recebida e visualizada, e que o feedback será publicado aqui em breve =)

@Galvaothiago

**Comment by Roger-Melo** [comment]
Oi Thiago. Fico feliz em saber que o treinamento está lhe ajudando rumo à fluência =)

Antes de dar o feedback, vou te dar uma dica para linkar urls aqui no GitHub. 

Quando precisar linkar uma url, você irá inserir, entre colchetes, o texto que ao ser clicado deve levar ao link. Em seguida, insira a url entre os parênteses. Ficará assim: `[texto clicável](https://url.com.br)`. Eu editei sua issue para que o link direcionasse ao repositório da aplicação. Antes estava assim `[https://...](url)`.

---

Mesmo com dificuldade em decidir, você conseguiu inserir o feedback de pontuação do usuário. Parabéns pelo esforço =)

Vou deixar abaixo algumas oportunidades de melhoria na aplicação.

## 3 principais oportunidades de melhoria

### Usabilidade

Observe que ao enviar o form, a pontuação é exibida na parte inferior da tela, exibindo apenas um pouco da parte superior do botão.

É possível posicionar esse feedback para que ele fique em uma área mais visível da tela, para que o usuário não precise rolar para baixo para visualizar a pontuação.

### Lógica

No código abaixo, 

```javascript
    userAnswers.forEach((userAnswer, index) => {
        const isCorrect = userAnswer === correctsAnswers[index]
        if (isCorrect) {
            score += questionOfValue
            form.insertAdjacentElement('beforeend', feedbackUserSpan)
            feedbackUserSpan.textContent = `Parabens! Voce acertou ${score}% das perguntas :)`
            feedbackUserSpan.setAttribute('class', 'feedback-span-more-twenty-five')
    
        } else if (score === 0) {
            form.insertAdjacentElement('beforeend', feedbackUserSpan)
            feedbackUserSpan.textContent = 'Que pena! Voce não acertou nenhuma questão :('
            feedbackUserSpan.setAttribute('class', 'feedback-span-less-twenty-five')
        }
    } )
```

como o if e o else if estão dentro de uma função de callback do forEach, toda vez que a condição do if ou do else if é atendida, uma manipulação no DOM é feita. Isso não é necessário.

Como a manipulação do DOM deve ser feita apenas **após** contabilizar os pontos, você pode deixar dentro do forEach só a lógica para a `score` receber pontos ou não.

Feito isso, após o loop, você pode checar o valor da score. Se for `0`, você executa o código do feedback de nenhuma questão correta. Caso contrário, o código informando a porcentagem de perguntas acertadas é executado.

Perceba também que o bloco do `else if` pode ser evitado se um return for inserido na última linha do if. Encadeamentos de if/else if/else tendem a deixar o código menos legível, menos conciso e exigem mais esforço cognitivo para serem lidos.

Para evitar o `else if`, basta fazer algo desse tipo:

```javascript
if (score === 0) {
  // código a ser executado se o usuário acertou zero respostas
  return
}

// código a ser executado se o usuário acertou uma ou mais respostas
```

Fique ligado que independente se o usuário acerta nenhuma resposta ou uma resposta ou mais, o código que exibe o feedback é o mesmo. A única diferença será a string da pontuação e a cor.

Então você pode eliminar essa duplicação isolando esse código em uma função que recebe esses parâmetros.

Ficaria assim:

```javascript
if (score === 0) {
  showFeedbackAnswer('mensagem 1', 'classe da cor1')
  return
}

showFeedbackAnswer('mensagem 2', 'classe da cor2')
```

Sacou a ideia?

Tome cuidado com o nome de variáveis e constantes. O nome deve ser o mais claro possível. No caso da const abaixo, 

```javascript
const questionOfValue = 100 / correctsAnswers.length
```

a ordem está invertida. O mais adequado seria `valueOfQuestion`, ou apenas `questionValue`.

### Organização do código

No código abaixo, a `const correctsAnswers` ficou "perdida" em meio às consts que armazenam nós do DOM.

```javascript
const form = document.querySelector('.form-question')
const correctsAnswers = ['A', 'B', 'C', 'C']
const feedbackUserSpan = document.createElement('span')
```

O ideal é que haja uma separação visual entre conceitos. Um agrupamento de consts que armazenam nós do DOM e que a correctsAnswers não faça parte desse agrupamento.

```javascript
const form = document.querySelector('.form-question')
const feedbackUserSpan = document.createElement('span')

const correctsAnswers = ['A', 'B', 'C', 'C']
```

O próximo ponto de atenção está relacionado ao ponto acima: a falta de linhas em branco.

Use linhas em branco para indicar, visualmente, a separação entre conceitos.

```javascript
userAnswers.forEach((userAnswer, index) => {
  const isCorrect = userAnswer === correctsAnswers[index]
  if (isCorrect) {
    score += questionOfValue
    form.insertAdjacentElement('beforeend', feedbackUserSpan)
    feedbackUserSpan.textContent = `Parabens! Voce acertou ${score}% das perguntas :)`
    feedbackUserSpan.setAttribute('class', 'feedback-span-more-twenty-five')
  }
  // ...
})
```

O código acima possui 4 conceitos:

- Armazenar um valor; 
- Verificar se esse valor é truthy;
- Fazer uma variável receber o valor que ela já tem somado a um outro valor; 
- Manipular o DOM.

São conceitos distintos, você pode deixar uma linha em branco entre eles. Ficaria assim:

```javascript
userAnswers.forEach((userAnswer, index) => {
  const isCorrect = userAnswer === correctsAnswers[index]

  if (isCorrect) {
    score += questionOfValue

    form.insertAdjacentElement('beforeend', feedbackUserSpan)
    feedbackUserSpan.textContent = `Parabens! Voce acertou ${score}% das perguntas :)`
    feedbackUserSpan.setAttribute('class', 'feedback-span-more-twenty-five')
  }
  // ...
})
```

Se um bloco do código conter apenas duas linhas, você pode quebrar o princípio. Para não deixar um bloco de duas linhas com um "buraco" no meio.

E claro, o código acima será modificado após as recomendações, usei ele apenas como exemplo.

Nas aulas seguintes, eu mostro como melhorar o código desta aplicação. Porém, sugiro que treine implementar os passos acima antes de vê-las =)

Mais uma vez, parabéns meu caro. Continue seguindo o método e você chegará na fluência na linguagem.

---

Antes de terminar este feedback, tenho mais uma recomendação. 

Eu escrevi um passo-a-passo do que eu sugiro que você faça quando errar algum exercício das baterias de exercícios do CJRM. 

Vou deixar o link para este passo-a-passo [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Depois me diga se fez sentido para você.

No que eu puder ajudar, estou aqui. Conte comigo para chegar à fluência em JavaScript =)

@Galvaothiago

**Comment by Galvaothiago** [comment]
Boa noite, Roger! Valeu pelo feedback, já estou colocando em pratica todos os pontos citados, e valeu pela dica no GitHub, comecei a usar recentemente. Notei que tenho muita dificuldade em refatorar o código após faze-lo funcionar, fico muito perdido por onde começar, o que eu posso mexer sem afetar o resultado final, e as vezes sinto que me apeguei aquela versão que funcionou a principio, mas estou trabalhando muito nesse aspecto. Sua didática é fora de série, parabéns e obrigado.

**Comment by Roger-Melo** [comment]
A dificuldade na refatoração é natural. Você está aprendendo. Refatoração deve ser uma preocupação posterior à solidificação de uma lógica coesa.

Antes de se preocupar com as paredes e os andares da torre, invista sua energia na construção da base. As torres mais altas possuem as fundações mais profundas.

Conte comigo para chegar na fluência. No que precisar, é só dar o toque =)
