### ISSUE TITLE
Etapa 8, nome do vídeo: Correção dos exercícios da aula 02 da etapa 07

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#900]
Olá Roger,

Verifiquei que no exercicio 3 (mostrado abaixo), ao fazer click mais de uma de uma vez  no botão `Inicar contador`, já não conseguimos fazer parar o contador utilizando o botão `Parar contador`. Isso é algum efeito colateral?? Tem alguma forma de prevenir isso???

obrigado!

```
/* 
  03

  - Faça o contador do index.html funcionar;
  - O clique no botão "Parar contador" deve fazer com que o contador exiba 0.
*/
const buttonInitCounter = document.querySelector('.button-init-counter')
const buttonStopCounter = document.querySelector('.button-stop-counter')
const counterContainer = document.querySelector('.counter-container')

let timer = null

const incrementCounter = () => {
  const increment = Number(counterContainer.textContent) + 1
  counterContainer.textContent = increment
}
const stopCounter = () => {
  clearInterval(timer)
  counterContainer.textContent = 0
}

buttonInitCounter.addEventListener('click', () => {
  timer = setInterval(incrementCounter, 1000)
})

buttonStopCounter.addEventListener('click', ()=>{
  stopCounter()
})
```
![imagem](https://user-images.githubusercontent.com/8411016/122408110-43be6900-cf69-11eb-891b-f9ef9225ebc5.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @cdfortes.

Na verdade esse comportamento do `setInterval` é esperado, afinal, ao clicar pela 2ª vez no botão "Iniciar contador", a função `incrementCounter` irá ser invocada novamente, de um em um segundo. Ou seja, 2 `setntervals` estão invocando a função de 1 em 1 segundo, cada um em seu tempo. 

Para que isso não aconteça, você pode fazer o seguinte:

1. Uma let `isCounterRunning` é inicializada com `false`, no topo do código.

```javascript
let timer = null
let isCounterRunning = false
```

2. Quando o botão de iniciar o contador é clicado, se `isCounterRunning` não é `true`, o `setInterval()` é executado e `isCounterRunning` recebe true.

```javascript
buttonInitCounter.addEventListener('click', () => {
  if (!isCounterRunning) {
    timer = setInterval(incrementCounter, 1000)
  }

  isCounterRunning = true
})
```

3. Quando o botão de parar o contador é clicado, `isCounterRunning` recebe false.

```javascript
buttonStopCounter.addEventListener('click', () => {
  clearInterval(timer)

  counterContainer.textContent = 0
  isCounterRunning = false
})
```

Essa é uma forma de resolver. O código ficará mais ou menos assim:

```javascript
const buttonInitCounter = document.querySelector('.button-init-counter')
const buttonStopCounter = document.querySelector('.button-stop-counter')
const counterContainer = document.querySelector('.counter-container')

let timer = null
let isCounterRunning = false

const incrementCounter = () => {
  const increment = Number(counterContainer.textContent) + 1
  counterContainer.textContent = increment
}

buttonInitCounter.addEventListener('click', () => {
  if (!isCounterRunning) {
    timer = setInterval(incrementCounter, 1000)
  }

  isCounterRunning = true
})

buttonStopCounter.addEventListener('click', () => {
  clearInterval(timer)

  counterContainer.textContent = 0
  isCounterRunning = false
})
```

Pegou a ideia?

**Comment by cdfortes** [comment]
Hi @Roger-Melo ,

Sim peguei! Obrigado pelo retorno! 🙏🏿🚀

**Comment by Roger-Melo** [comment]
Legal @cdfortes. Vou fechar a issue mas no que precisar, é só abrir uma nova =)
