### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by emanuelcontinib** [roger-melo-treinamentos/curso-de-js-roger-melo#901]
Olá Roger, fazendo certo dessa vez kk

Link do repositório: https://github.com/emanuelcontinib/Aplica-o-Quiz-Interativo/blob/main/README.md

-Maior dificuldade: Foi em relação a quais métodos para obtenção dos valores HTML e um pouco na compreensão do que o exercício pedia. Mas acho que é só falta de atenção minha.

-Menor dificuldade: Foi em relação a estruturação e exibição da pontuação na tela do usuário e o javascript da aplicação pois acabei fazendo junto e reutilizei muito.  

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @emanuelcontinib. Visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @emanuelcontinib. Estou passando para dar satisfações sobre a análise de sua aplicação. 

Ainda não pude concluí-la, pois ontem e hoje tive que resolver alguns problemas contábeis que, se não resolvidos logo, poderiam gerar problemas fiscais para a empresa. Acabou que isso tomou muito do meu tempo.

Então peço um pouco de paciência, pois a partir de amanhã, darei continuidade e publicarei as análises de aplicações pendentes =)

Obrigado pela compreensão.

Abraço.

**Comment by Roger-Melo** [comment]
Olá @emanuelcontinib!

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

A exibição da pontuação não aconteceu ao enviar o form. Isso pode fazer o usuário achar que ele fez algo errado ou simplesmente se frustrar ao usar a aplicação.

## Lógica

Os pontos não foram exibidos por causa do atributo `type="button"` no `<button>`:

```html
<button type="button" class="btn btn-outline-light" btn-lg>Criar discórdia </button>
```

Esse atributo faz com que nada aconteça quando o `form` é enviado. Você pode ver mais sobre isso [aqui](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) e [aqui](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type).

É por isso que na aula, eu mostrei um `<button>` que não contém o atributo `type`. A omissão desse atributo faz com que o `button` tenha o comportamento padrão, que é o mesmo comportamento do `type="submit"`.

Outro ponto que você precisa ficar atento é que independente das alternativas marcadas, o `score` exibido no parágrafo sempre vai ser zero, pois a let `score` está sendo renderizada antes do cálculo dentro do `forEach` ser executado:

```javascript
const paragraph = `<h5>Você acertou ${score}% das questões </h5>`
button.insertAdjacentHTML('beforebegin', paragraph) // renderizou a pontuação na tela
button.innerText = 'Jogar de novo'
  
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === correctAswers[index])
  score += 25 // mas a pontuação é calculada aqui
})
```

Então essa ordem precisa ser inversa: primeiro o cálculo dos pontos é feito e depois é exibido na tela:

```javascript
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === correctAswers[index])
  score += 25
})

const paragraph = `<h5>Você acertou ${score}% das questões </h5>`
button.insertAdjacentHTML('beforebegin', paragraph)
button.innerText = 'Jogar de novo'
```

Sempre teste a aplicação antes de mostrá-la para alguém ou subir para produção, isso vai te dar mais certeza de que ela está funcionando como o esperado.

Um outro ponto é que eu não mostrei o `reload()`. É legal você estudar outras coisas da linguagem, mas o desafio no CJRM consiste em você resolver exercícios e construir aplicações com apenas o que viu no treinamento.

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio, `button` e `paragraph` são nomes vagos para consts.

Elas podem ser renomeadas como `buttonQuizSubmit` e `finalScore`, por exemplo.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu removeria as linhas em branco 1 e 40.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by emanuelcontinib** [comment]
Olá Roger!

Sim, fizeram muito sentido!
Fiz as alteração e anotei isso, às vezes deixo passar detalhes importantes,
mas trabalhando nisso.
Muito interessante a correção, ter esse feedback com apontamentos é melhor
ainda.

Valeu Roger,abraço!



Em sáb., 19 de jun. de 2021 às 09:11, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @emanuelcontinib, no que precisar, estamos às ordens =)
