### ISSUE TITLE
Aplicação: Quiz

### ISSUE THREAD

**Issue by rogerioopaiva** [roger-melo-treinamentos/curso-de-js-roger-melo#902]
Boa noite professor,

Link do repositório: https://github.com/rogerioopaiva/stranger-quiz

Maior dificuldade: Consegui finalizar o projeto porém sem grandes alterações, nada muito diferente da aula. Ainda não consegui fazer do zero ou seguindo outras formas alternativas de fazer. 

Menores dificuldades: Interagir do DOM e com html.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @rogerioopaiva.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @rogerioopaiva. Estou passando para dar satisfações sobre a análise de sua aplicação. 

Ainda não pude concluí-la, pois ontem e hoje tive que resolver alguns problemas contábeis que, se não resolvidos logo, poderiam gerar problemas fiscais para a empresa. Acabou que isso tomou muito do meu tempo.

Então peço um pouco de paciência, pois a partir de amanhã, darei continuidade e publicarei as análises de aplicações pendentes =)

Obrigado pela compreensão.

Abraço.

**Comment by Roger-Melo** [comment]
Olá @rogerioopaiva!

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Organização de código

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio, `result` pode ser mais descritiva se for renomeada como `finalScore`, por exemplo.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu deixaria a linha 23 em branco.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

> Maior dificuldade: Consegui finalizar o projeto porém sem grandes alterações, nada muito diferente da aula. Ainda não consegui fazer do zero ou seguindo outras formas alternativas de fazer.

Não sei o que você quiz dizer com fazer do zero, mas o ideal é que você se esforce para implementar as aplicações sozinho. Por isso, eu recomendo que você siga à risca o passo a passo que eu mostrei na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). Isso vai te deixar bem mais afiado para construir as aplicações.

E claro, se alguma dúvida permanecer, não hesite em abrir uma issue.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by rogerioopaiva** [comment]
Boa tarde Roger,

Obrigado pela análise.

As observações fizeram sentido sim. Principalmente os espaços em branco.
Já tinha observado isso mas não tinha compreendido o motivo. Achei bem interessante.

Mais uma vez obrigado e bora para o próximo.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @rogerioopaiva, no que precisar, estamos às ordens =)
