### ISSUE TITLE
Resumo da Aula Modificando estilos CSS (inline) - Aula 02-04 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#904]
Para modificar estilos *inline* de elementos HTML, antes de mais nada é necessário ter a referência para algum elemento. Então vamos supor que temos um HTML com apenas uma tag `<h1>` com qualquer título escrito. Para obtermos esta referência, basta atribuirmos a uma constante `title` (por exemplo) o resultado de `document.querySelector('h1')`. Com essa referência, podemos utilizar a propriedade `style`, e encadear com qualquer propriedade CSS. Então para fazermos com que o elemento tenha a cor azul, basta atribuirmos o valor `'blue'` a `title.style.color`. A diferença de utilizar a propriedade `style` e utilizar o método `setAttribute()` é que ao utilizar o `style` não sobrescrevemos o que já existe (a não ser que queiramos que isto aconteça). Vamos ver na prática:

```jsx
const h1 = document.querySelector('h1');

h1.style.color = 'blue';
h1.style.margin = '20px';
```

O código acima fará com que o elemento que temos como referência fique na cor azul e tenha 20px de margem.

Poderíamos ainda ver a lista de propriedades CSS disponíveis para utilizarmos, imprimindo no console `title.style`, com o `title` sendo a referência para o elemento.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @ricardopontesdantas. Rumo à fluência! 🔥
