### ISSUE TITLE
Resumo da Aula 03-02,03 da etapa 01

### ISSUE THREAD

**Issue by davidtheblane** [roger-melo-treinamentos/curso-de-js-roger-melo#907]
### Aula 03-02 - Métodos de Arrays

Arrays servem para armazer uma lista de itens que tem relações entre si, podem ser de diferentes tipos de dados.

SINTAXE: 
```javascript
let arrayName = ["item1",  "item2", 1, 2, 3]
``` 
Os itens do array podem ser chamados via notação de colchetes '[]', cada item tem um seu index.

Métodos

- **.join()** = Retorna uma string com todos os itens do array concatenados e separados por virgula. A virgula pode ser substituida por outro elemento, basta especificar.

```javascript
const marketList = ["banana", "pera", "uva"]
console.log(marketList.join(", "))
//banana, pera, uva
ou
marketList.join(" - ")
//banana - pera - uva
```

- **.indexOf()** = Retorna o indice do item no array, se o item não existir ele retorna -1

```javascript
const marketList = ["banana", "pera", "uva"]
console.log(marketList.indexOf("uva"));
//banana, pera, uva
ou
console.log(marketList.indexOf("maçã"));
//-1
```

- **.concat()** = Concatena o conteúdo de 2 arrays em apenas 1

```javascript
const marketList1 = ["banana", "pera"];
const marketList2 = ["uva", "maça"];
console.log(marketList1.concat(marketList2));
// ["banana", "pera", "uva", "maça"]
```

- **.push()** = Adiciona itens novos no array e também retorna o novo número de itens do array.
```javascript
const marketList = ["banana", "pera", "uva"];

let newItem = marketList.push("maçã");

console.log(marketList);
 //["banana", "pera", "uva", "maçã"]
console.log(newItem);
//4
```

- **.pop()** = Retira o ultimo item de um array e também retorna esse ultimo item.
```javascript
const marketList = ["banana", "pera", "uva", "maçã"]

let removedItem = marketList.pop();

console.log(marketList);
//["banana", "pera", "uva"]
console.log(removedItem);
//maçã
```

<hr>

### Aula 03-03 - Null e Undefined

- **Undefined** = Toda vez que não atribuímos valor a uma variável e tentamos utilizá-la, o javascript retorna automaticamente undefined.

- **Null** = Pode ser atribuído de forma intencional, geralmente usado para evitar erros em soluções complexas.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Show @davidtheblane. Rumo à fluência! 🔥
