### ISSUE TITLE
Etapa 5, nome do vídeo: Desenvolvendo um popup - Aula 04-04

### ISSUE THREAD

**Issue by Sephyros** [roger-melo-treinamentos/curso-de-js-roger-melo#908]
Aproximadamente aos 18:42 da referida aula é explicada a utilização do Array.some() e pelo que notei neste caso especifico (onde a regra para validação é apenas se o array de classes possíveis para fechamento do popup contem a classe do alvo do evento) poderia ser utilizado o Array.includes() sem nenhum problema, mas a utilização do Array.some() foi preferida (além do motivo de ensinar outro método do tipo Array) devido este ultimo ter a possibilidade da utilização de um callback mais elaborado em outras situações mais "complexas" de validação. Está correto isso ou existe outro motivo para a preferencia do some neste caso? que seja uma convenção/boa prática adotada?

```js
...
popup.addEventListener("click", event => {
  const classNameOfClickedElement = event.target.classList[0];
  const classNames = ["popup-close", "popup-wrapper", "popup-link"];
  const shouldClosePopup = classNames.some(className =>
    className === classNameOfClickedElement);
...
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Sephyros. 

Neste caso, eu apenas aproveitei a oportunidade para apresentar o `some`. Mas sim, o `includes` pode ser usado tranquilamente neste caso e isso deixaria o código mais conciso, afinal, a função de callback não seria necessária =)

A vantagem do `some` é que a função de callback dele te dá a oportunidade de especificar uma lógica mais refinada. Mas nem sempre você precisará disso. 

Na aula 01-02 da etapa 14 eu mostro um exemplo em que é preferível usar o `some` ao invés do `includes` =)

**Comment by Sephyros** [comment]
Entendi! obrigado!

**Comment by AnaCosta29** [comment]
Eu pesquisei aqui se tinha o mesma lógica que a minha do uso includes já que retorno dele e boolean

**Comment by Roger-Melo** [comment]
Pode usar o `includes` sim @AnaCosta29. Se surgir qualquer dúvida, é só abrir uma nova issue =)
