### ISSUE TITLE
Etapa 02, Correção dos exercícios da aula 02 - Aula 03-01

### ISSUE THREAD

**Issue by joaowilian01** [roger-melo-treinamentos/curso-de-js-roger-melo#91]
Roger, gostaria de agradecer até aqui! Sua didática é excelente para o entendimento dos conceitos!

Abri essa issue mais para deixar uma sugestão no exercício número 6. Acho que é mais interessante armazenar o último elemento do array em uma constante e depois utilizar a constante para fazer o replace. Pois utilizando no formato de string como foi feito no vídeo pode causar um resultado não esperado. Eu resolvi o exercício dessa forma.

```js
const randomNumbers = [73, 4, 67, 10, 31, 58];
const evenNumbers = [];
const oddNumbers = [];

for (let i = 0; i < randomNumbers.length; i++) {
  const number = randomNumbers[i];
  const isEven = number % 2 == 0;
  
  if (isEven) {
    evenNumbers.push(number);
  } else {
    oddNumbers.push(number);
  }
}

const lastEvenNumber = evenNumbers[evenNumbers.length - 1];
const lastOddNumber = oddNumbers[oddNumbers.length - 1];

const evenNumbersString = evenNumbers.join(', ').replace(`, ${lastEvenNumber}`, ` e ${lastEvenNumber}`);
const oddNumbersString = oddNumbers.join(', ').replace(`, ${lastOddNumber}`, ` e ${lastOddNumber}`);

console.log(`Numeros ímpares: ${oddNumbersString}. Números pares: ${evenNumbersString}.`);
}
```
Mas com certeza ao passar pelo conteúdo de regex terá uma solução melhor ainda, como foi falado no vídeo dessa aula.

Ah muito obrigado pelas dicas de refatoração também. Vou começar a utilizar mais vezes!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi João Wilian!

Perfeito, muito obrigado pela contribuição =)

Revendo a aula, a solução ficou meio "conveniente" por não considerar a variabilidade dos números. 

Mas sim, com regex fica mais simples manipular strings.

Caso essa aula seja regravada no futuro, vou apresentar um raciocínio gradativo até chegar nesta solução e lhe e dar os créditos. Muito obrigado =D

@joaowilian01

**Comment by joaowilian01** [comment]
Fico feliz em poder contribuir para conteúdo do curso!
