### ISSUE TITLE
Exercicio 13 - 02

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#92]
No exercício 13 - 02 ao incluir as chamadas extraInternal e internal conforme abaixo funciona corretamente.
Minha dúvida é que a ultima chamada no meu VS code aparece riscada e diz @deprecated, conforme imagem. 
Li no mdn que ocorre quando determinada função/método está descontinuado, e foi substituido ou alterado em atualizações para novos. Porém neste caso não consegui identificar o por que e nem qual seria a melhor alternativa.

```js
const external = () => {
  const movie = 'Parasite'

  const internal = () => {
    const extraInternal = () => {
      console.log(movie.toUpperCase())
    }
    extraInternal()
  }
  
  internal()
}

external()
```

OBS durante a aula sobre escopos, o mesmo ocorreu. 

![image](https://user-images.githubusercontent.com/68160678/100399118-43dc3300-3030-11eb-8fcd-7f762dafd5c4.png)

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique.

O VSCode insere [um traço](https://code.visualstudio.com/updates/v1_49#_deprecated-tag-support-for-javascript-and-typescript) no meio de propriedades e métodos que foram descontinuados.

Neste caso, perceba que se você retirar os parênteses da invocação da `external`, o traço continuará sendo exibido. Isso acontece por que antigamente, o window tinha uma propriedade [external](https://developer.mozilla.org/en-US/docs/Web/API/Window/external) que foi descontinuada. Então o VSCode está lhe "avisando" isso.

Há pelo-menos duas opções para resolver este problema:

1. Você modifica o nome da const. Ela poderia se chamar `externalFunc`, por exemplo;
2. Você desabilita essa feature do VSCode.

Se escolher a segunda opção, segure `ctrl+shift` e pressione `P` para que a command pallete seja exibida e então, insira "settings" para que a opção "Preferences: Open Settings (JSON)" seja exibida.

Ao clicar nessa opção, um JSON de configurações do VSCode será aberto. Insira a chave "editor.showDeprecated" e atribua `false` a ela.

Pesceba que essa segunda opção desabilita o aviso do VSCode para todas as outras propriedades e métodos descontinuados.

Recomendo que escolha a primeira opção. Listei a segunda para que você ficasse ciente de que é possível fazer isso.

Me avise se resolveu =)

@henriquebazi

**Comment by Roger-Melo** [comment]
Oi Henrique. Por agora, vou fechar a issue mas se surgir alguma outra dúvida é só perguntar =)
