### ISSUE TITLE
Etapa 4, nome do vídeo: Correção dos exercícios da aula 02 da etapa 03 - Aula 01-01

### ISSUE THREAD

**Issue by eduardophilip** [roger-melo-treinamentos/curso-de-js-roger-melo#928]
```js
const location = ['Porto', 'Lisboa', 'Viana do castelo', 'Braga'];

const existInArray = (item, array) => array.includes(item);

console.log(existInArray('Lisboa', location))
```

Olá, Roger, tudo bem?

A minha dúvia é a seguinte este código está a dar este erro: 
**`Uncaught SyntaxError: Identifier 'location' has already been declared`**

não entendo, pois estou a passa-la como argumento.

podes me ajudar a entnder?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @eduardophilip. 

Esse erro está sendo lançado por que no objeto window existe uma propriedade `location`:

```javascript
console.log(location) // Location {…}
```

Não se preocupe em saber o que é o objeto window agora, você o conhecerá na etapa 5. Apenas modifique o nome da `const` para `cities` ou algo do tipo e o código funcionará normalmente =)

**Comment by eduardophilip** [comment]
Olá, @Roger-Melo!

muito obrigado, Problema resolvido!

**Comment by Roger-Melo** [comment]
Excelente @eduardophilip. No que precisar, é só dar o toque =)
