### ISSUE TITLE
Error 404 favicon not found

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#93]
Roger, eu estava com uma mensagem chata de erro no console dizendo "favicon not found" erro 404, eu sei que o browser procura automaticamente o favicon no projeto, porém como é pra estudos eu nem importava muito, porém esse erro começou a cansar já, pesquisei na net e vi uma solução pra ele adicionando: ```<link rel="shortcut icon" href="about:blank">``` ao head da pagina html.
se quiser implementar nos arquivos html dos exercícios para outros alunos deixarem de ter esse erro chatinho fique a vontade para usar, eu já coloquei em todos os exercícios que eu baixei, mas pra futuros alunos já ajuda, um abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Uso o mesmo repositório dos alunos para resolver os exercícios e, geralmente, os warnings de favicon aparecem raramente no console do browser. Às vezes aparecem quando subo o servidor e desaparecem assim que pressiono F5. 

E também é a primeira vez que ouço que os warnings estão muito frequentes, vou ficar atento.

Mas sim, essa solução funciona =)

Apenas não esqueça de remover a tag quando subir a aplicação para produção.

@RicarGit
