### ISSUE TITLE
Resumo da Aula A palavra-chave this 02-03 da etapa 04

### ISSUE THREAD

**Issue by AnaCosta29** [roger-melo-treinamentos/curso-de-js-roger-melo#933]
@Roger-Melo
![this_part1](https://user-images.githubusercontent.com/35525950/122658051-28a55200-d13f-11eb-896e-9e74af8a32c6.jpeg)
![this_part2](https://user-images.githubusercontent.com/35525950/122658050-280cbb80-d13f-11eb-9e84-7504b9698e5f.jpeg)

**Comment by Roger-Melo** [comment]
Show @AnaCosta29. Rumo à fluência! 🔥
