### ISSUE TITLE
Etapa 7, Quiz Interativo

### ISSUE THREAD

**Issue by RicarGit** [roger-melo-treinamentos/curso-de-js-roger-melo#94]
Aqui está o link do repositório do exercício 19 - Quiz Interativo
https://github.com/RicarGit/exercicio-19.git

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Para que a aplicação seja avaliada, é necessário que você poste exatamente o que foi pedido no exercício. Além do link da aplicação, você precisa postar os 2 itens listados abaixo do link:

>- O link da sua versão do quiz;
>- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício;
>- Quais foram as suas menores dificuldades durante a execução desse exercício.

@RicarGit

**Comment by RicarGit** [comment]
https://github.com/RicarGit/exercicio-19.git

Minha dificuldade é em dar nomes pra variáveis haha, refatoração ainda não é meu ponto forte, parece que consigo entender mais o código sem refatorar, não sei porquê... dei uma refatorada mas não sei se ficou bom, talvez dê pra refatorar mais ainda mas não sei onde... setInterval() deu uma dor de cabeça, as vezes eu esqueço que ele é um loop e acabo colocando coisa dentro que acaba criando elementos e resetando outros por conta de ter colocado dentro do setInterval(), eu esqueci que tinha que criar uma variável pra ele do lado de fora e não conseguia parar ele com o clearInterval()!

O que ando achando fácil de fazer é selecionar classes e itens do html com javascript, coisa que eu não entendia muito, adicionar classes, criar elementos em javascript pra mim hoje já não é mais uma dificuldade, iterar por arrays, criar eventos já estão sendo muito mais fáceis!

**Comment by Roger-Melo** [comment]
Oi Ricardo.

Parabéns pelo esforço em desenvolver a aplicação =)

A dificuldade na refatoração é natural. Você está aprendendo. Refatoração deve ser uma preocupação posterior à solidificação de uma lógica coesa.

Sim, o setInterval tem esse comportamento de executar o código dentro do callback dele em um determinado intervalo de tempo. Quanto mais você usá-lo, mais se acostumará com ele.

Excelente que sacou bem trabalhar com arrays, eventos e manipulação de DOM. Esse último será importante quando você começar a trabalhar com uma lib ou framework futuramente.

---

Sei que você teve dificuldades com o favicon e deixou um placeholder que impedia os warnings em seu navegador.

Porém, ao subir a aplicação em produção e/ou enviá-la para um recrutador, não se esqueça de inserir um placeholder ou retirar a `<link rel="shortcut icon" href="about:blank">`. 

Se você mantê-la e o recrutador for uma pessoa técnica, ele verá `GET about:blank net::ERR_UNKNOWN_URL_SCHEME` exibido no console e investigará a causa do erro.

Vou deixar abaixo algumas oportunidades de melhoria na aplicação.

## Lógica

No código abaixo,

```javascript
const p = document.createElement('p')
p.setAttribute('class', 'text-info')
```

a `const p` foi declarada e teve um atributo setado, mas não está sendo usada no decorrer da aplicação. Então ela pode ser removida do código.

Neste pedaço de código,

```javascript
getUserAnswers = () => {
  const userAnswers = []

  quizAnswers.forEach((_, index) => {
    userAnswers.push(form[`inputQuestion${index + 1}`].value)
  })

  return userAnswers
}
```

mesmo que o código tenha funcionado, a declaração da `getUserAnswers` precisa ser atribuída à um identificador, uma const.

O código só funcionou por que `getUserAnswers` foi pendurada no objeto global window:

```javascript
window.getUserAnswers // () => { const userAnswers = [] ... }
```

Pendurar propriedades no objeto global pode demandar mais consumo de memória de forma desnecessária.

## Organização do código

Novamente, sobre o código abaixo,

```javascript
const p = document.createElement('p')
p.setAttribute('class', 'text-info')
```

`p` é um nome genérico. Prefira deixar explícito no nome da `const` sobre o quê é o parágrafo que ela está armazenando.

A localização da declaração da `p` no código é importante. Se ela é declarada em escopo global mas não for usada em duas ou mais funções no decorrer do código, ou ainda se não há alguma justificativa para declará-la no escopo global da aplicação, faz mais sentido declará-la e setar seus atributos dentro da função onde o parágrafo será manipulado.

Uma última observação: use linhas em branco para indicar, visualmente, a separação entre conceitos.

No código abaixo,

```javascript
const calculateUserScore = userAnswers => {
  userAnswers.forEach((userAnswer, index) => {
    const isUserAnswerCorrect = userAnswer === quizAnswers[index]
    if (isUserAnswerCorrect) {
      score += 25
    }
  })
}
```

Armazenar um valor e verificar se o valor é `truthy` são conceitos distintos. Você pode deixar uma linha em branco entre eles:

```javascript
const calculateUserScore = userAnswers => {
  userAnswers.forEach((userAnswer, index) => {
    const isUserAnswerCorrect = userAnswer === quizAnswers[index]
    
    if (isUserAnswerCorrect) {
      score += 25
    }
  })
}
```

Se o bloco conter apenas duas linhas, você pode quebrar o princípio.

Tome cuidado também com a inserção de linhas em branco onde não é necessário.

```javascript
const timer = setInterval(() => {

  if (counter === score) {
    clearInterval(timer)
    score = 0
  }

  scoreResultDiv.textContent = `Você acertou ${counter++}% do quiz!`
}, 13)
```

Convencionalmente, o esperado é que a primeira linha de um bloco contenha uma expressão.

---

No mais, é isso meu caro. Parabéns novamente pelo esforço em impementar a aplicação. Conte comigo para chegar na fluência =)

@RicarGit

**Comment by RicarGit** [comment]
```js 
const p = document.createElement('p')
p.setAttribute('class', 'text-info')
```
Eu bobiei aqui mesmo, esse p foi usado na primeira vez que fiz o código para mostrar o resultado em cima do botão Enviar, agora substituída pela scoreContainer

```js
const calculateUserScore = userAnswers => {
  userAnswers.forEach((userAnswer, index) => {
    const isUserAnswerCorrect = userAnswer === quizAnswers[index]
    if (isUserAnswerCorrect) {
      score += 25
    }
  })
}
```
Aqui também pequei em separar o if, costumo separar também, de resto peguei suas dicas e vou ficar mais atento ao código, nunca estive tão empenhado em aprender assim, já estou com 50% do curso concluído e sei que daqui pra frente vai ficar cada vez mais difícil, porém estou nessa tentativa de aprender a programar a mais ou menos 1 ano e meio e ainda sinto que não sei nada, porém agora parece que achei meu caminho, vlw @Roger-Melo

**Comment by Roger-Melo** [comment]
Legal Ricardo!

Estou dando o meu melhor para que você e todos os alunos saiam desse treinamento fluentes! Aptos a construírem aplicações web com JavaScript puro.

No que eu puder lhe ajudar para alcançar a fluência, conte comigo =)
