### ISSUE TITLE
Outros

### ISSUE THREAD

**Issue by CleitonRReis** [roger-melo-treinamentos/curso-de-js-roger-melo#943]
Fala, Roger! Blz?

Mestre, consegue me passar uma lista de livros, que você recomenda, voltados a JS que sejam essenciais para me aprofundar? 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @CleitonRReis. 

Na real, considerando o seu estágio de aprendizado eu não recomendo livros não. 

Minha recomendação é que você siga à risca o que eu disse na [aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928). 

E claro, qualquer dúvida que rolar sobre isso, é só dar o toque =)
