### ISSUE TITLE
Etapa 9, nome do vídeo: aplicação To-do-list

### ISSUE THREAD

**Issue by MauroGith** [roger-melo-treinamentos/curso-de-js-roger-melo#946]
Desenvolver essa aplicação foi um verdadeiro desafio, pois eu não sabia como conseguir as informações sem navegar pelo DOM, procurei nas anotações das aulas até encontrar sobre o data-js, no exercício 9. Também tive um problema em conseguir apagar os itens que eram criados depois da página carregada. 
Já estava quase abrindo uma issue em dúvidas quando fiz uma pequena alteração e tudo funcionou. MDN me ajudou nessa !
 A parte fácil foi alterar o estilo e algumas funções criadas para refatoração.

Link da aplicação no GitHub : 
https://github.com/MauroGith/Projetos-JS/tree/main/to-do-list

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @MauroGith.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @MauroGith!

Parabéns pelo esforço em construir a segunda aplicação =)

Vou deixar abaixo alguns poucos pontos de atenção, segundo os critérios que usei para analisar.

## Organização de código

### Espaços em branco

Prefira não deixar espaços em branco na hora de especificar atributos HTML, como `data-js = "li"`. Os espaços em branco não necessariamente vão lançar algum erro, mas é uma convenção especificá-los assim: `atributo="valor"`.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, eu removeria a linha em branco 5 e adicionaria uma linha em branco nas linhas 27, 36 e 46.

Se um bloco de código conter apenas duas linhas, você pode quebrar este princípio. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

---

Nas aulas seguintes você verá formas de melhorar esse código usando, por exemplo, o event delegation, visto na aula 04-02 da etapa 05, para não precisar usar `forEach` na hora de remover todos.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by MauroGith** [comment]
Muito obrigado @Roger-Melo , eu fiquei meio focado em fazer funcionar e nem reparei esses detalhes, fiz algumas alterações e vou ver as aulas seguintes para melhorar ainda mais.
