### ISSUE TITLE
Resumo da Aula Obtendo, adicionando, removendo e alternando classes CSS - Aula 02-05 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#947]
Para adicionar uma classe CSS em um elemento HTML, antes de mais nada precisamos obter a referência desse elemento, atribuindo a uma constante `paragraph`, por exemplo, para a partir daí começarmos a manipular as classes CSS. Vamos supor que tenhamos um código HTML com uma *tag* `<p class='content'>` com um texto qualquer. Essa classe '*content*' foi adicionada apenas para termos um exemplo mais completo. Então com a referência do elemento já obtida, utilizamos a propriedade `classList`, encadeando o método `add()`, passando como valor a classe que queremos adicionar, '*success*' por exemplo. Então a partir daí, se salvarmos o arquivo, vemos que no HTML a classe CSS '*success'* foi adicionada ao parágrafo. Vamos ver no exemplo abaixo:

```jsx
const paragraph = document.querySelector('p');

paragraph.classList.add('success');

// No HTML, o parágrafo ficará assim: <p class='content success'>Lorem ipsum dolor sit amet</p>
```

Já para removermos uma classe CSS de um elemento, utilizaremos o método `remove()`, passando o nome da classe CSS que queremos remover, que nesse exemplo será a classe CSS '*success*'. Veja o exemplo abaixo:

```jsx
paragraph.classList.remove('success');

// No HTML, o parágrafo ficará assim: <p class='content'>Lorem ipsum dolor sit amet</p>
```

Podemos também listar todas as classes CSS atribuídas ao elemento apenas chamando a propriedade `classList`. Então dando continuidade ao exemplo que estamos utilizando, neste momento temos apenas a classe CSS '*content*' atribuída ao elemento `<p>`. Veja o exemplo abaixo:

```jsx
console.log(paragraph.classList);

// No console, obtemos a lista de classes, onde neste momento teremos apenas 'content' na lista
```

Além de adicionar, remover e listar as classes CSS de um elemento, podemos também alternar uma classe em um elemento através do método `toggle()` (presente na propriedade `classList`), passando como argumento uma *string* com o nome da classe CSS que queremos alternar. Então se passarmos por exemplo a classe CSS '*success*' como argumento, caso ela não exista na referência, ela será adicionada, e caso ela já exista, ela será removida. Veja o exemplo abaixo:

```jsx
// Neste momento, temos apenas a classe CSS 'content' atribuída ao elemento <p>

paragraph.classList.toggle('success');

// No HTML, o parágrafo ficará assim: <p class='content success'>Lorem ipsum dolor sit amet</p>

paragraph.classList.toggle('success');

// No HTML, o parágrafo ficará assim: <p class='content'>Lorem ipsum dolor sit amet</p>
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas! Rumo à fluência 👊🏻
