### ISSUE TITLE
Etapa 11, Funções de callback - Aula 03-03

### ISSUE THREAD

**Issue by luisotacilio** [roger-melo-treinamentos/curso-de-js-roger-melo#95]
Professor Roger, boa tarde, por causa do código abaixo, deu um “nó na cabeça” :

linha 1, a palavra callback é declarada;

linha 9 e 13, ela é instanciada agora com dois parâmetros

linha 21, a função é acionada 

Duvidas: Como o código da função esta espalhado, torna-se pra mim pouco legível.  E como se fosse uma função implícita, tem de ficar procurando os pedaços pra compreender o todo.

Fiz testes de console.log(type of   [nome parametro]) e a engine do js  interpreta esses parâmetros
como esperado. E por isso, temos de aceitar que é assim mesmo que a linguagem trabalha e “por baixa dos panos” ele torna uma função implícita em explicita?Afinal de contas funciona!

Talvez por conhecer outra linguagem isso é mais difícil de “digerir”?  Fico imaginando um código fonte com 2000 linhas,  inúmeras callbacks espalhadas ao longo da aplicação: “Ai o bicho vai pegar bonito?”, vai dar um trabalhão encontrar um bug.

Ps: Na Divida Comédia: Dante Alighieri leu nas portas de entrada do inferno a seguinte inscrição:
“Deixai toda a esperança, ó vós que entrais”.  Depois dessa lição  minha esperança ficou meio abalada, por favor, se tiver algumas palavras de conforto: (tipo)  JS é dinâmico, aceita tudo em tempo de execução, acho que ficarei confiante novamente...rs
```
1    const getTodos = (callback) => {
2     const request = new XMLHttpRequest();
3
4     request.addEventListener('readystatechange', () => {
5       const isRequestOk = request.readyState === 4 && request.status === 200;
6       const isRequestNotOk = request.readyState === 4;
7
8    if (isRequestOk) {
9      callback(null, request.responseText);
10      return;
11     }
12    if (isRequestNotOk) {
13      callback('Não foi possivel obter os dados', null);
14    }
15    });
16
17    request.open('GET', 'https://jsonplaceholder.typicode.com/todos');
18      request.send();
19    };
20
21    getTodos((error, data) => {
22      console.log('callback executado');
23      if (error) {
24        console.log(error);
25      return;
26      }
27      console.log(data);
28  });

```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Luis.

É natural que no começo de sua jornada à fluência, callbacks sejam um pouquinho mais complexos para se entender. Mas não são um bicho de 7 cabeças. Vamos lá =D

### - Passo 1

Comece a leitura pela invocação da `getTodos`. É a invocação dela que desencadeia o fluxo da execução do callback:

```javascript
getTodos((error, data) => {
  console.log('callback executado');
  if (error) {
    console.log(error);
    return;
  }
  console.log(data);
});
```

No código acima, `getTodos` é invocada e recebe uma função como argumento.

### - Passo 2

Isso faz com que o parâmetro callback (abaixo),

```javascript
const getTodos = (callback) => {
  // ...
};
```

receba a declaração desta função:

```javascript
(error, data) => {
  console.log('callback executado');
  if (error) {
    console.log(error);
    return;
  }
  console.log(data);
}
```

### - Passo 3

Dentro da `getTodos`, se o bloco do if abaixo é executado, a função é invocada.

```javascript
if (isRequestOk) {
  callback(null, request.responseText);
  return;
}
```

Quando a função é invocada, ela recebe `null` como 1º argumento e o resultado de `request.responseText` como 2º argumento.

### - Passo 4

Ou seja, na declaração da função, o parâmetro `error` recebeu `null` e o parâmetro `data` recebeu a string com a resposta do request:

```javascript
(error, data) => {
  // error recebeu null e data recebeu a string
  console.log('callback executado');
  if (error) {
    console.log(error);
    return;
  }
  console.log(data);
}
```

### - Passo 5

Agora basta ler o corpo da função.

Como `error` recebeu `null`, que é um valor `falsy`, o bloco do `if` não foi executado e `console.log(data)` exibiu a string no console.

A única variação no passo a passo dessa leitura é no passo 3, quando o outro `if` é executado.

Sacou a ideia?

---

> Talvez por conhecer outra linguagem isso é mais difícil de “digerir”?  Fico imaginando um código fonte com 2000 linhas,  inúmeras callbacks espalhadas ao longo da aplicação: “Ai o bicho vai pegar bonito?”, vai dar um trabalhão encontrar um bug.

Você só trabalhará em um código com duas mil linhas se deixar a negligência tomar conta (a sua ou a da empresa em que trabalha).

Ainda vamos chegar na etapa em que mostrarei isso, mas existem formas de trabalhar com módulos em JavaScript. 

Módulos são arquivos separados, normalmente agrupados por features de uma aplicação. No processo de build, aí sim todo o código da aplicação é entregue em um "bundle" com a versão final dos arquivos que o browser deve servir.

@luisotacilio

**Comment by luisotacilio** [comment]
Entendi...( uma parte da dúvida era 1 argumento se transformar em 2)

Num acionamento "clássico ou padrão" se faz a chamada da função em única
“etapa” : como na linha 4 do trecho de código abaixo (o nome-da-função e
seus argumentos)

*********************************************

*1     function soma(a, b){*

*2         return a + b*

*3    }*

*4   console.log(soma(5,2));   // 7*

*********************************************


Numa callback pode se fazer em duas etapas :

1) o* nome-da-função* passado como argumento de outra função;

2) Ai na invocação é que  passa-se   o    *nome-da-função + seus argumento*
s.


Obrigado pelas orientações!




Em qua., 2 de dez. de 2020 às 23:03, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Isso mesmo, Luis.

Lembre-se: **callback é uma função inserida com argumento da invocação de outra função**.

Independente de quantos parâmetros uma função tem, você pode inserir a **declaração** ou a **referência** dessa função como argumento da invocação de outra função.

```javascript
const callCallback = callback => {
  // o parâmetro callback recebeu a referência ou declaração da função
}

// Opção 1: a declaração da função é inserida como argumento
callCallback(() => console.log('oi'))

// ou

// Opção 2: myFunc é referenciada como argumento
const myFunc = () => console.log('oi')

callCallback(myFunc)
```

Organize o caos mental e primeiro, acostume-se com o conceito acima. 

Depois, comece a se preocupar com quantos parâmetros a função de callback tem e (por consequência) quantos argumentos a invocação dela precisa receber.

@luisotacilio

**Comment by luisotacilio** [comment]
Professor Roger,
Muito obrigado.. dúvidas resolvidas!

Em sex., 4 de dez. de 2020 às 19:50, Roger Melo <notifications@github.com>
escreveu:

**Comment by Roger-Melo** [comment]
Legal Luis. Já que ficou mais claro, vou fechar a issue. No que precisar, é só abrir uma nova. 

Conte comigo para construir aplicações com JavaScript puro =)
