### ISSUE TITLE
Etapa 2, nome do vídeo: Exercicios das aulas 2-2, 2-3 e 2-4

### ISSUE THREAD

**Issue by ElaineDelgado** [roger-melo-treinamentos/curso-de-js-roger-melo#956]
## Bom dia, professor!
Estava tentando resolver os exercícios sobre condicionais e tive um problema que nunca ocorreu. Se o senhor souber, poderia me esclarecer o que o causou?
Problema: quando fiz o código do else (que está comentado no código abaixo) ele travou o dev tools, na verdade ele desconectou. O Chrome não mais exibia o index, mas uma página de erro. Tirei alguns prints pro senhor ter uma ideia melhor, e postarei abaixo dos exercícios.
Ainda não fiz a correção dos exercícios, pois queria consertar esse antes e tentar fazê-lo funcionar. 

```js

 /* 05
  - O array "crazyArray" (abaixo) possui 3 tipos de dados: numbers, booleans  
    e strings;
  - Considerando este array, substitua os "X" da frase abaixo pelas informações  
    corretas;
  - Gere essas informações à partir de um for loop;
  - Exiba a frase no console.
  "O crazyArray tem X booleans, X números e X strings."
*/

const crazyArray = [true, 869, 'oi', 71, false, 83, '35', true, 397, 'js', false] 
let isBoolean = []
let isString = []
let isNumber = []

for (let i = 0; i < crazyArray.length; i++) {
  if (typeof crazyArray[i] === 'boolean') {
    isBoolean.push(crazyArray[i])
  } else if (typeof crazyArray[i] === 'string') {
    isString.push(crazyArray[i])
  } /*else {
    isNumber.push(crazyArray.push(crazyArray[i]))
  }*/
}
console.log(`O crazyArray tem ${isBoolean.length} booleans, X números e ${isString.length} strings.`)
console.log(isBoolean.length) // retorna 4
console.log(isString.length) // retorna 3
}
```

## O que acontece se eu descomentar o bloco do else:

![Screenshot_2](https://user-images.githubusercontent.com/69869482/122768909-6fe42d80-d27a-11eb-87ff-cb4117c7835b.png)

## Erro na página:

![Screenshot_3](https://user-images.githubusercontent.com/69869482/122769048-973afa80-d27a-11eb-8d85-28f6288e7d12.png)

## Comentando o else o resultado no console fica assim: 

![Screenshot_1](https://user-images.githubusercontent.com/69869482/122769131-a91c9d80-d27a-11eb-974d-8907328e2249.png)

## Obrigada desde já!!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi @ElaineDelgado. O problema está na expressão abaixo:

```javascript
isNumber.push(crazyArray.push(crazyArray[i]))
```

O que está acontecendo é que `crazyArray.push(crazyArray[i])` está inserindo um item no array `crazyArray`, e isso faz com que a expressão `i < crazyArray.length` do for nunca resulte em `true`, por que o `crazyArray` não para de aumentar o tamanho dele. Isso faz com que a execução do loop seja infinita, causando um aumento absurdo na memória do browser até que a aba simplesmente não aguente mais e pare de funcionar.

Para resolver isso, basta fazer com que apenas o item seja inserido no array `isNumber`:

```javascript
else {
  isNumber.push(crazyArray[i])
}
```

Ficou mais claro?

**Comment by ElaineDelgado** [comment]
Bom dia professor!!
Hoje quando olhei sua resposta, a primeira coisa que dizia era "O problema está na expressão abaixo:
isNumber.push(crazyArray.push(crazyArray[i])) 
Quando eu bati o olho nessa expressão eu pensei: de onde ele tirou isso? Fui olhar meu código e vi que eu mesma fiz isso. 
Eu não faço ideia de onde eu tirei esse código maluco, sendo que no if e no else if eu tinha feito certinho, e o mais estranho foi que enquanto eu fazia os exercícios, eu procurava o erro e não enxergava esse absurdo aí.  
Está muito claro pra mim porque bugou, não faz sentido essa expressão e eu não faço ideia do porquê eu fiz isso se estava no caminho certo nas expressões anteriores!
Da próxima vez que eu tiver um erro, vou deixar o código de lado e voltar depois, pois esse foi um erro que nem eu sei como consegui cometê-lo mas que poderia ter sido facilmente identificado se eu não tivesse tão apegada em resolver.
Muito obrigada!!!

**Comment by Roger-Melo** [comment]
Haha! As vezes isso acontece quando a gente fica muito tempo olhando um mesmo código... é preciso um segundo olho.

No que precisar, é só abrir uma nova issue =)

@ElaineDelgado
