### ISSUE TITLE
Aplicação: TO-DO LIST

### ISSUE THREAD

**Issue by cdfortes** [roger-melo-treinamentos/curso-de-js-roger-melo#959]
[Minha versão da Aplicação ](https://github.com/cdfortes/js-to-do-list-app)

### Minhas maiores dificuldades
- A lógica para refatorar o remover de tarefas sem utilizar o parentElement, acho que consegui encontrar uma que funcione :)

### Minhas menores dificuldades
- recriar o que já tinha sido feito em aula

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @cdfortes!

Parabéns pelo esforço em construir a segunda aplicação. Seu progresso é notável, pois corrigiu os pontos de atenção mencionados na análise passada =)

Uma única observação que tenho é sobre a `const` isClassDelete. Como ela contém um `includes` que verifica se o array **tem** alguma classe, eu a nomearia como `hasDeleteClass` ou `hasClassDelete`.

Eu também adicionaria uma linha em branco nas linhas 60 e 78, para separar mais os conceitos.

Mas o mais importante você já fez, que é fazer funcionar. Nas aulas seguintes você verá formas de melhorar esse código.

Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by cdfortes** [comment]
Obrigado! 
Eu também senti que evolui...o que me dá mais força pra continuar! 🙏🏿🙏🏿

Simm, fizeram muito sentido!🤛🏿

Abraço!

**Comment by Roger-Melo** [comment]
Show @cdfortes. No que precisar, é só dar o toque =)
