### ISSUE TITLE
Etapa 7,Quiz

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#96]
Olá, segue link do meu quiz.
https://github.com/henriquebazi/curso-cjrm

Minha dificuldade ainda é desenvolver sem precisar "colar". Por mais que acredito estar indo bem nos exercícios, ainda sim acabo consultando as aulas para resolve-los, como foi o caso da const userAnswers. 
Além disso, tive dificuldades, simples, mas existentes na leitura e entendimento da documentação do bootstrap para montar o layout da pagina.

Uma dúvida que fico, e peço desculpas caso eu não tenha prestado a devida atenção se foi explicado em alguma das aulas é sobre o condicional if. Percebi nas aulas que você sempre faz o not dentro do condicional. Eu tenho feito o true.
Isto seria uma boa prática para melhorar o desempenho do código, como por exemplo evitar os elses usando return ? 

 O conteúdo de dom tem sido bem tranquilo, acredito estar indo bem nessa questão.
Entender o que está sendo feio também esta ficando mais fácil a cada aula.

No mais, gostaria de agradecer pelo conteúdo, tem sido de bastante ajuda e aprendizado. 

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique.

Fico feliz que você esteja sacando manipulações de DOM. Elas são importantes quando combinadas com a base da linguagem para que, no futuro, você entenda o que uma lib como o React, por exemplo, está fazendo por baixo dos panos.

Mesmo com dificuldades no layout da página com o bootstrap, você enviou a aplicação. Parabéns pelo esforço =)

Antes de responder as perguntas, vou deixar abaixo oportunidades de melhoria na aplicação.

### Usabilidade

#### Inputs e labels

Ao clicar em uma alternativa, o usuário da aplicação precisa posicionar e clicar exatamente no input radio. E isso pode incomodá-lo, pois o input é muito pequeno.

Por isso, quando demonstrei na aula como construir a aplicação, inseri o input dentro da label. Isso faz com que o texto da label seja clicável e o clique dê um check no input.

#### Ortografia

A terceira pergunta contém a palavra riquesas, com "s" (o correto é com "z"). Isso pode incomodar um usuário mais detalhista.

#### Localização da exibição dos pontos

Ao enviar o form, a pontuação é exibida na parte inferior da tela. O único feedback visual que algo aconteceu ao enviar os pontos é a mudança da altura da barra de rolagem.

É possível posicionar a exibição dos pontos para que ele fique em uma área mais visível da tela, para que o usuário não precise rolar para baixo para visualizar.

### Organização do código

#### Linhas em branco

Use linhas em branco para indicar, visualmente, a separação entre conceitos.

No código abaixo,


```javascript
userAnswers.forEach((userAnswer, index) => {
  const checkAnswer = userAnswer === correctAnswers[index]

  if (checkAnswer) {
    score += 25
  }

})
paragraph.textContent = `Sua pontuação foi de ${score} pontos!`
paragraph.setAttribute('class', 'my-3 lead font-weight-bold')
button.insertAdjacentElement('afterend', paragraph)
```

O parênteses de fechamento do `forEach` indica o término de um conceito (loop) e o início da linha abaixo indica o início de outro conceito (manipulações do DOM). Então você pode deixar uma linha em branco entre esses dois conceitos:

```javascript
userAnswers.forEach((userAnswer, index) => {
  // ...
})

paragraph.textContent = `Sua pontuação foi de ${score} pontos!`
// ...
```

Tome cuidado também com a inserção de linhas em branco onde não é necessário.

Observe que há uma linha abaixo do final do bloco do `if`. Fim da parte interna de blocos não requerem linhas em branco, então você pode removê-la. Ficaria assim:

```javascript
userAnswers.forEach((userAnswer, index) => {
  const checkAnswer = userAnswer === correctAnswers[index]

  if (checkAnswer) {
    score += 25
  }
})

paragraph.textContent = `Sua pontuação foi de ${score} pontos!`
// ...
```

Se o bloco conter apenas duas linhas, você pode quebrar este princípio.

---

Agora vamos às respostas às suas perguntas (a mais urgente é a última) =)

> Uma dúvida que fico, e peço desculpas caso eu não tenha prestado a devida atenção se foi explicado em alguma das aulas é sobre o condicional if. Percebi nas aulas que você sempre faz o not dentro do condicional. Eu tenho feito o true.
Isto seria uma boa prática para melhorar o desempenho do código, como por exemplo evitar os elses usando return ?

Não precisa pedir desculpas, estou aqui para te ajudar.

Sempre aplico o fail fast. A sacada desse pattern é que quando o seu código falha rápido, ele se torna mais robusto, pois o foco inicial é encontrar as condições onde a execução do código pode ser encerrada.

Essa abordagem faz com que seja mais fácil encontrar bugs e consertá-los.

> Minha dificuldade ainda é desenvolver sem precisar "colar". Por mais que acredito estar indo bem nos exercícios, ainda sim acabo consultando as aulas para resolve-los, como foi o caso da const userAnswers.

Esse e o ponto crucial que deve ser resolvido com mais urgência.

O objetivo é que você esteja afiado para construir sozinho essa primeira aplicação.

Se isso ainda não está acontecendo, é por que algo está te fazendo andar "com o freio de mão puxado".

E eu posso especular que o que está te travando são dúvidas que se acumularam. Dúvidas que se acumulam ao longo do tempo, escalam.

Você abriu apenas duas issues até aqui (sem contar a de hoje, pois não é uma issue totalmente de dúvidas). Isso significa que postou apenas duas dúvidas. E eu posso estar errado, mas não acredito que você tenha tido apenas duas dúvidas até chegar aqui.

Por isso, vou te indicar uma revisão raio-x. Essa revisão vai diagnosticar o provável lugar em que as dúvidas começaram a surgir. À partir disso, vai ficar mais fácil você corrigir seus erros.

Vou deixar o passo a passo da Revisão Raio-x abaixo. 

#### Passo a passo da Revisão Raio-x

1. Sem assistir as aulas novamente, refaça as baterias anteriores de exercícios (começando da primeira bateria);

2. Quando travar em um exercício, assista a correção, apague o código e implemente-o novamente, sozinho. Se não conseguir implementar sem olhar a correção do exercício, veja a correção. Nessa fase, você notará que provavelmente suas dúvidas sobre o exercício vai ficar mais específica. Após sanar a dúvida, apague o código e implemente-o, sozinho.

3. Execute o item acima quantas vezes forem necessárias para que seu cérebro entenda o padrão de resolução do exercício;

4. Após executar os itens acima, parta para o próximo exercício;

5. Faça isso até chegar no ponto do treinamento em que você está agora. As chances são de que você estará mais afiado para fazer os exercícios atuais e construir essa primeira aplicação sozinho.

E claro, se mesmo executando a Revisão Raio-x a dúvida permanecer, não hesite em abrir uma issue. 

Ficar afiado para construir essa primeira aplicação sozinho não vai ser fácil, não vai ser prazeroso. Mas a longo prazo, é esse hábito da revisão raio-x que vai fundar o seu alicerce para construir aplicações com JavaScript puro =)

@henriquebazi

**Comment by henriquebazi** [comment]
Obrigado Roger pelo feedback. Acredito que eu também possa estar um pouco acelerado.
Sobre as dúvida, sim algumas acabaram surgindo nesta jornada, porém normalmente nas correções dos exercícios são sanadas. 

Realizei os ajustes conforme recomendados, segue : https://github.com/henriquebazi/curso-cjrm
Ainda não inclui o scroll automático, pois não assisti a aula. Acho super válido a revisão Raio-x e pretendo faze-la.

Obrigado!

**Comment by Roger-Melo** [comment]
Legal Henrique. Parabéns pelo esforço =)

Só uma observação, que foi um erro de comunicação da minha parte.

Quando eu disse que "sempre aplico o fail fast", na verdade eu queria dizer que faço isso **sempre que o código tem duas ou mais** opções a serem executadas.

No código abaixo,

```javascript
  userAnswers.forEach((userAnswer, index) => {
    const checkAnswer = userAnswer === correctAnswers[index]

    if (!checkAnswer) {
      return
    }

    score += 25
  })
```

veja que no fim das contas, só existe uma ação a ser executada: aumentar a pontuação do usuário.

Então neste caso, o código fica mais simples se a pontuação do usuário for aumentada apenas se `checkAnswer` armazenar `true`.

```javascript
  userAnswers.forEach((userAnswer, index) => {
    const checkAnswer = userAnswer === correctAnswers[index]
    
    if (checkAnswer) {
      score += 25
    }
  })
```

Sacou a ideia?

@henriquebazi

**Comment by henriquebazi** [comment]
Sim, obrigado!

**Comment by Roger-Melo** [comment]
Legal Henrique. Já que ficou mais claro, vou fechar a issue por agora. No que precisar, é só abrir uma nova =)
