### ISSUE TITLE
Aplicação: Minha aplicação Quiz-Curso-CJRM

### ISSUE THREAD

**Issue by francisbc** [roger-melo-treinamentos/curso-de-js-roger-melo#962]
- O link da sua versão do quiz: https://github.com/francisbc/quiz-curso-CJRM

- Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício?

1. Dentro daquilo que foi exigido para esse exercício não tive dificuldades que me fizessem ter que rever a aula.

- Quais foram as suas menores dificuldades durante a execução desse exercício.

1. Encontrar o escopo correto para a declaração da let score.
2. Entender a dinâmica de inclusão dos valores de input diretamente dentro de um array.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @francisbc!

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser exibido por padrão como "marcado".

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

## Organização de código

### Declarações de variáveis semelhantes

A declaração das consts no topo do código pode ser mais organizada. Você pode organizá-las agrupando-as pelo tipo de valor que elas armazenam. No exemplo abaixo, eu agrupei as consts que armazenam elementos do DOM e separei a const que armazena as respostas corretas:

```javascript
const form = document.querySelector('.quiz-form')
const button = document.querySelector('button')
const resultParagraph = document.createElement('p')

const correctAnswers = ['A','B','B','A']
```

Vou falar mais sobre linhas em branco logo abaixo.

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Seguindo este raciocínio... 

`button` é um nome genérico, não descreve bem sobre o que é o botão. Ela poderia se chamar `buttonSubmitQuiz` por exemplo.

Não é o caso dessa aplicação mas, em aplicações que tem muita manipulação de DOM, geralmente não é uma boa ideia nomear consts com tags que podem ser modificadas. Se a `resultParagraph` por exemplo, viesse a armazenar uma `<div>` no futuro, ela teria que ser renomeada. O que não teria que acontecer se ela recebesse um nome que descreve apenas o valor que ela armazena, como `finalScore`.

`quizSubmitEvent` é um substantivo. Para descrever a ação que a função executa, eu a nomearia como `handleQuizSubmit`, pois ela lida com o que acontece quando o form é enviado.

Como `reviewAnswers` armazena um boolean, eu a nomearia como `isCorrectAnswer` ou `isUserAnswerCorrect`.

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode separar mais as linhas no topo da `quizSubmitEvent`:

```javascript
const quizSubmitEvent = event => {
    event.preventDefault()
    
    let score = 0
    
    const userAnswers = [
        // ...
    ]

// ...
```

Se um bloco de código conter apenas duas linhas, você pode quebrar o princípio das linhas em branco. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by Roger-Melo** [comment]
@francisbc vou fechar a issue mas no que precisar, é só abrir uma nova =)
