### ISSUE TITLE
Raio-X Exercícios

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#97]
Roger, finalizei os primeiros 5 módulos de exercícios e me surpreendi por ter conseguido fazer sem checar as correções ou aulas.
De padrão já queria sair usando métodos como o forEach rsrs, mas consegui fazer de forma mais simples.

Bom, 2 pontos que fiquei com dúvidas.

Exercício 04-01 - Por que quando faço sentence.replace() e logo em seguida chamo a sentence no console.log() o replace não é execultado? Caso eu ja use diretamente no console, então ocorre normalmente. 

```
const my3FavoriteTVShows = [
  'Prision Break',
  'Dark',
  'O Atirador'
]

const sentence = 'Minhas 3 séries favoritas são: '+my3FavoriteTVShows.join(', ')

sentence.replace('ark, ', 'ark e ')
console.log(sentence) // o replace aqui parece não funcionar.

console.log(sentence.replace('ark, ', 'ark e '))

````

a segunda, Exercício 04-07 - Resulta True pois a soma Null + 1 é differente de 0, que é falsy, tornando assim um valor Truthy?

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal Henrique. Agora sim temos material para esclarecer as dúvidas =D

> Exercício 04-01 - Por que quando faço sentence.replace() e logo em seguida chamo a sentence no console.log() o replace não é execultado? Caso eu ja use diretamente no console, então ocorre normalmente.

Isso acontece por que a invocação do `replace`, ao invés de modificar a string original, retorna uma nova string.

Ou seja, no código abaixo, a expressão `sentence.replace('ark, ', 'ark e ')` retornou uma nova string com `'ark, '` substituído por `'ark e '`. Mas nada está sendo feito com o retorno da expressão:

```javascript
const sentence = 'Minhas 3 séries favoritas são: '+my3FavoriteTVShows.join(', ')

sentence.replace('ark, ', 'ark e ')
```

Como o replace retorna uma nova string ao invés de modificar a string original, quando você executa `console.log(sentence)` depois do replace, `sentence` continua com o mesmo valor que ela já tinha.

Para visualizar a nova string, você pode armazenar o retorno de `sentence.replace('ark, ', 'ark e ')` em uma const ou simplesmente inserir a expressão como argumento de um `console.log`, como você fez na última linha:

```javascript
const newSentence = sentence.replace('ark, ', 'ark e ')

console.log(newSentence)

// ou

console.log(sentence.replace('ark, ', 'ark e '))
```

---

> A segunda, Exercício 04-07 - Resulta True pois a soma Null + 1 é differente de 0, que é falsy, tornando assim um valor Truthy?

É o seguinte... 

```javascript
const crazyOperation = null + 1
const crazyConversion = Boolean(crazyOperation)

crazyConversion // true
```

Quando inserimos o `null` em uma operação matemática, antes da operação acontecer `null` é, automaticamente, convertido para 0.

Então o que está acontecendo na expressão `null + 1` é `0 + 1`.

Como `0 + 1` resulta em `1`, a `const crazyOperation` armazenou `1`.

Após isso, na linha abaixo, `Boolean(crazyOperation)` está convertendo `1` para seu equivalente booleano (`true` ou `false`). Como `1` é um valor truthy, a expressão `Boolean(crazyOperation)` resulta em `true`, e então `true` é armazenado na `const crazyConversion`.

Está ficando mais claro? =)

@henriquebazi

**Comment by henriquebazi** [comment]
Obrigado pelas respostas.

Terminei a segunda leva, do exercícios 05 a 10.

Exercício 07-04 - O continue é usado para "ignorar" a interação em questão caso seja chamado. Não ficou claro o para mim a diferença entre continue e return, que usamos em condicionais para ignorar a necessidade de um else.

```
const sentence = ['A', 'certeza', 'dúvida', 'é', 'o', 'princípio', 'da', 'sabedoria.']
let sentenceConcat = ''

for(let i=0;i<sentence.length; i++){
  const validation = sentence[i] === 'certeza'
  if(validation){
    continue // continue ignora o resto do código dentro do for. 
  }

  sentenceConcat += `${sentence[i]} `
}
```

Precisei consultar sobre function expression, pois não lembrava desta. Apenas o método tradicional chamado function () e arrow armazenada em uma const. Após a consulta, consegui desenvolver.

Já no ex 08-03 fiquei com dúvida se o método utilizado esta correto. Utilizei um for chamando a função criada para exibir o valor i, além da frase pedida.

```
function showMessage (value = 'digite um valor') {
  console.log(value)
}

for(let i=1; i<=7;i++){
  showMessage(i)
  return `Esta é a ${i}ª vez que essa string é exibida`
}
```

após rever a aula de correção entendi qual era a solicitação e percebi que foi um erro de interpretação.
```
function showMessage (value = 'digite um valor') {
  console.log(value)
}

for(let i=1; i<=7;i++){
  showMessage(`Esta é a ${i}ª vez que essa string é exibida`)
}
```

No Exercício 09-10 da primeira vez e desta novamente esqueci o return na callback. 

```
function callbackFunction2 (value, callback) {
  return callback(value)
}

const triple = number => number * 3

console.log(callbackFunction2(11, triple))
```

e por fim, exercício 10 - 05 não lembrei sobre os colchetes. Precisei rever. 

Por enquanto é isso, obrigado!

**Comment by Roger-Melo** [comment]
Oi Henrique.

> Não ficou claro o para mim a diferença entre continue e return, que usamos em condicionais para ignorar a necessidade de um else.

Não há uma relação direta entre `continue` e `return` serem usados apenas em condicionais.

Na verdade, o `continue` deve ser usado apenas dentro de loops. Ele conclui a execução **da iteração atual** do loop e executa imediatamente a próxima iteração.

```javascript
let text = ''

for (let i = 0; i < 5; i++) {
  if (i === 3) {
    continue
  }

  text = text + i
}

text // '0124'
```

No código acima, embora o `continue` esteja dentro de um `if`, o que faz ele funcionar ali é o fato dele estar dentro de um loop.

---

Já o `return` é usado apenas em funções. Ele faz duas coisas:

1. Termina a execução da função, fazendo com que o código abaixo dele seja ignorado;
2. Retorna um valor quando a função é invocada.

---

Sobre os esquecimentos pontuais, eles são naturais. Apenas certifique-se de que ao fazer a revisão raio-x você executou todas as etapas.

Ex: se esqueceu um return na 2ª vez que revisou o exercício (sozinho), apague o código e refaça todo o exercício novamente (sozinho). Se lembrar do return na 3ª vez, ótimo, vá para o próximo exercício. Se não lembrar, apague o código e refaça o exercício novamente. Esse loop é fundamental para que seu cérebro realmente absorva os padrões de resoluções.

Está ficando mais claro?

@henriquebazi

**Comment by Roger-Melo** [comment]
Oi Henrique. Por agora vou fechar a issue, mas quando rolarem mais dúvidas, é só abrir novas issues =)
