### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by Sephyros** [roger-melo-treinamentos/curso-de-js-roger-melo#978]
Bom dia @Roger-Melo!

- **Meu quiz:**
[Quiz Interativo](https://github.com/Sephyros/quiz-interativo)

- **Maiores dificuldades:**
Bem, no quesito da lógica e utilização da linguagem em si apenas em um momento devido o cansaço (ou nervosismo quem sabe) já não lembrava como obter o valor escolhido do input, mas após uns minutos exibindo os dados do event, target e input no console consegui recuperar o caminho e tudo voltou a fluir! Já em outros aspectos o bicho pegou, criatividade para escolher tema, nomeação e organização de consts e variáveis... essas coisas realmente são um calcanhar de aquiles. No caso de CSS e HTML eu realmente tenho que me policiar, tenho um deficit de atenção gigantesco, se inventar de mudar a cor de um botão eu acabo perdendo horas pesquisando como arredondar mais o botão, como fazer ele mudar de cor entre diversas "inutilidades" (entre aspas pois não considero inutilidades no geral, mas no momento tenho que administrar meu tempo exclusivamente para o JS). Graças as sábias palavras proferidas na semana JS, aula inaugural e no manual da disciplina estou me policiando melhor nesse quesito! Por isso acabei deixando o design do quiz quase inalterado, apenas mudei algumas cores e adicionei alguns elementos.

- **Menores dificuldades:**
Bem, a lógica e utilização da linguagem foram coisas que fluíram muito bem, então acho que esses fatores devem ter sido os mais tranquilos.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @Sephyros.

Passando para dizer que visualizei a issue e se estiver tudo ok com a aplicação, em breve a análise será postada aqui =)

**Comment by Roger-Melo** [comment]
Olá @Sephyros!

Parabéns pelo esforço em construir a primeira aplicação, deu pra perceber que você entendeu bem a lógica até aqui =)

Na real, o código não deixou a desejar em nenhum dos critérios que uso para analizar as aplicações (e olha que são vários).

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

**Comment by Sephyros** [comment]
Agradeço imensamente pela análise e feedback! é extremamente motivacional para continuar me empenhando para manter essa qualidade! Rumo a fluência!
