### ISSUE TITLE
Etapa 02, Correção dos exercícios da aula 02 (if else statements) - Aula 03-01

### ISSUE THREAD

**Issue by marcosmaiadev** [roger-melo-treinamentos/curso-de-js-roger-melo#98]
Olá, Roger.

Eu acertei os exercícios desta aula, conforme pedido. Veja que coloquei os testes da condição em constantes e, até aqui, (**código 1**) funcionou. 

**Código 1 - que funcionou**
```js
const fruits = ['morango', 'banana', 'mamão']
const testAbacaxi = fruits.includes('abacaxi')
const testPera = fruits.includes('pera')


if (testAbacaxi){
  console.log(`A string "abacaxi" existe no array fruits.`)
} else if(testPera){
  console.log(`A string "pera" existe no array fruits.`)
} else {
  console.log(`Nem pera nem abacaxi existem no array "fruits".`)
}
```

Mas tentando melhorar o código, eu tentei colocar os resultados (console.log) em variáveis e chamá-las na declaração dos If e else, conforme **código 2**.
Mas ao invés de funcionar como estava antes, o console passou a exibir todas os console.log. 
Minha intenção era saber se eu poderia criar uma lista/tabela de mensagens padrão em um sistema, como respostas padrão, e durante a execução dos códigos, chamar a mensagem que me interessa. (ou até combinar algumas). Mas aí ele passou a ignorar os IFs...

**Código 2 - que não funcionou**

```js
const fruits = ['morango', 'banana', 'mamão']
let testAbacaxi = fruits.includes('abacaxi')
let testPera = fruits.includes('pera')
const messageA = console.log(`A string "abacaxi" existe no array fruits.`)
const messageB = console.log(`A string "pera" existe no array fruits.`)
const messageC = console.log(`Nem pera nem abacaxi existem no array "fruits".`)

if (testAbacaxi){
  messageA
} else if(testPera){
  messageB
} else {
  messageC
}
```

 

Tem alguma coisa a ver especificamente com o console.log?  Não posso incluir uma função como variável? Ou é apenas com o IF else? Ou tem outra explicação? obrigado! 

@Roger-Melo

**Comment by marcosmaiadev** [comment]
Eu entendi que consigo colocar apenas as mensagens em si, nas const. E invocar um console.log(const com a mensagem), como o exercício seguinte.
Mas queria entender o porque incluir um console.log na variável ou constante não funciona.

**Comment by Roger-Melo** [comment]
Oi Marcos! Parabéns por abrir a primeira issue aqui =D

O retorno de funções/métodos será explicado na próxima etapa que você verá, "Etapa 03 - Funções e Métodos".

Porém, para não confundí-lo e ao mesmo tempo esclarecer um pouco do que acontece, é o seguinte: 

```javascript
const myConst = console.log('My message')
```

Quando você atribui a invocação de um `console.log()` a uma variável, o que está acontecendo por baixo dos panos é:

1. `console.log('My message')` é executado e a string `My message` é exibida no console;
2. Ao invés de `'My message'` ser atribuída para a `const`, o valor retornado pela invocação do método `console.log` é atribuído para a `const`.

Ou seja, o que a `const` está armazenando é o resultado da expressão `console.log('My message')`.

E o resultado de uma invocação do `console.log()` sempre será `undefined`.

Se logo abaixo da `const messageA`, por exemplo, você exibir `messageA` no console, verá que ela armazenou `undefined`:

```javascript
const messageA = console.log(`A string "abacaxi" existe no array fruits.`)

console.log(messageA) // undefined
```

Isso acontece por que em JavaScript, todo pedaço de código que não lança um erro ou não retorna um valor, retorna `undefined`.

Alguns métodos/funções retornam valores, outros não.

Nas aulas anteriores você viu, por exemplo, que a invocação do método `lastIndexOf` retorna/resulta no `index` da última ocorrência do caractere na string:

```javascript
'abcba'.lastIndexOf('b') // 3
```

Já o console.log não retorna valor. Portanto, retorna `undefined`.

Está ficando mais claro?

@marcosmaiadev

**Comment by marcosmaiadev** [comment]
:D obrigado.  
Eu comecei a Etapa 3 sobre funções e, comecei a aprender melhor sobre funções (incluindo o function expression que começou a fazer sentido pra mim e ,acredito, serviria pra esse propósito de guardar console.logs) - se eu não estiver errado...
 Mas esse exemplo do lastIndexOf em relação ao console.log esclareceu totalmente. Pelo que entendi métodos como lastIndexOf e o Includes retornam um valor, no caso do Includes, um boolean , e nas vezes que colocamos uma variável antes da atribuição, estávamos atribuindo, na verdade, o resultado do método, certo?! Se eu entendi bem.
 
já métodos como console.log e Join() não retornam nada, apenas exibem no console o  dado inserido... (O Join converte. Caso eu tenha falado bobagem, de qualquer forma, entendi sobre o console.log...

Obrigado pela aula, Roger. Vc é o melhor professor de JavaScript!

**Comment by Roger-Melo** [comment]
Oi Marcos.

Function expression quer dizer apenas que você atribuiu uma função (criada por você) à uma variável.

Ao desenvolver suas aplicações em JavaScript puro, você não usará o `console.log()` para outro propósito, a não ser exibir valor(res) no console.

> Mas esse exemplo do lastIndexOf em relação ao console.log esclareceu totalmente. Pelo que entendi métodos como lastIndexOf e o Includes retornam um valor, no caso do Includes, um boolean , e nas vezes que colocamos uma variável antes da atribuição, estávamos atribuindo, na verdade, o resultado do método, certo?! Se eu entendi bem.

Isso mesmo. A invocação desses métodos retornam valores. Ainda nesta etapa 3 você descobrirá como =)

> Minha intenção era saber se eu poderia criar uma lista/tabela de mensagens padrão em um sistema, como respostas padrão, e durante a execução dos códigos, chamar a mensagem que me interessa. (ou até combinar algumas).

Da quarta etapa em diante, você começará a conhecer objetos mais à fundo. Eles serão a estrutura de dados ideal para você criar esse tipo de lista de mensagens.

Segura o coração, você ainda vai conhecer muitos fundamentos que irão te ajudar a construir aplicações web com JS puro =D

---

Vou aproveitar a oportunidade para te fazer uma recomendação.

Talvez você tenha visto, talvez não, mas eu escrevi um passo-a-passo do que eu sugiro que você faça quando errar algum exercício das baterias de exercícios do CJRM.

Vou deixar o link para este passo-a-passo [aqui](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/1801661). Depois me diga se fez sentido para você =)

**Comment by marcosmaiadev** [comment]
Sim. Na verdade segui a sugestão de deixar a aba aberta ao lado da que vejo o curso. Entendi os comentários. Muito empolgado.
Obrigado pelas explicações e pelo seu tempo!
Issue resolvida.

**Comment by Roger-Melo** [comment]
Fico feliz que esteja ficando mais claro, Marcos.

Vou fechar essa issue, mas no que precisar, é só abrir uma nova =)
