### ISSUE TITLE
Etapa 07 - Aula 01-03 - Template HTML e checando as respostas

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#989]
Boa tarde Roger,

Cheguei na Etapa 07, cuja Aula 01-03, era relacionada a primeira aplicação, o "Quiz Interativo" e acabei ficando um pouco confuso, pois:

1. Na aula, você mostra como deve ser o quiz, e ainda implementa a lógica para obter a pontuação. A dúvida é: "Era para eu ter visto o vídeo explicando a lógica mesmo, ou já partir para a execução do projeto, antes de ver o vídeo? Pergunto, pois não encontrei nada no course, indicando uma direção.";

2. No exercício da Aula 01, é para eu implementar a aplicação do quiz, do zero, utilizando a lógica semelhante às da Aula 01-03, com a diferença que eu devo exibir na tela (não foi especificado a maneira que o resultado deverá ser exibido), o resultado do quiz, para o usuário? É isso mesmo?

Agradeço desde já o auxílio.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva. 

> 1. Na aula, você mostra...

Sim, você verá a aula explicando a lógica. Logo após ela, você vai chegar nos exercícios e depois no aviso lembrando de enviar a sua versão do quiz para análise antes de prosseguir, como mostrado abaixo. 

![avisos](https://user-images.githubusercontent.com/29297788/123143477-05c1b900-d431-11eb-8cf7-e4ef277f5fe5.jpg)

Não se preocupe, coloquei avisos estratégicos na plataforma em cada uma das aplicações =)

> 2. No exercício da Aula 01...

Exatamente. O desafio é você desenvolver a sua versão do quiz e implementar a exibição da pontuação por conta própria, como está [descrito no exercício](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/blob/master/exercicio-19/app.js) =)

Ficou mais claro?

**Comment by raphaelprsilva** [comment]
@Roger-Melo, ficou mais claro sim. Eu só fiquei com dúvida, pois você havia implementado a lógica de raciocínio.

Muito obrigado!

**Comment by Roger-Melo** [comment]
Sim, na maioria das aplicações eu mostro. Mas na etapa 15, por exemplo, o último exercício da primeira bateria de exercícios é uma aplicação em que eu apenas dou dicas de como implementá-la =)

@raphaelprsilva

**Comment by raphaelprsilva** [comment]
Entendi. Para mim, está solucionada a questão. Se quiser fechar a issue, sinta-se à vontade.

Obrigado, mais uma vez.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Legal @raphaelprsilva. Fico no arguardo das suas aplicações.

Se houver alguma dúvida, é só abrir uma nova issue =)
