### ISSUE TITLE
raio-x do 01 a 19

### ISSUE THREAD

**Issue by henriquebazi** [roger-melo-treinamentos/curso-de-js-roger-melo#99]
Roger, finalizei os exercícios de revisão, até o quiz novamente, e fiz um novo quiz:

https://github.com/henriquebazi/curso-cjrm/tree/quiz-raio-x

sobre os demais exercícios seguem meus comentários:

12 - precisei rever os métodos do Math.

14-02 fiz : 

```
numbers.forEach( number => {

const li = document.createElement('li')

ul.appendChild(li)

li.setAttribute('class', 'number')

li.textContent = number

})
```

analisando a correção, vi a alternativa:

```
numbers.forEach(number => {
  ul.innerHTML += `<li class="number">${number}</li>`
})

``` 

15 -01 o código abaixo retornar uma HTMLCollection, onde não podemos usar o forEach. Durante a resolução, lembrei que devemos transfomar o retorno em um NodeList, porém necessitei consultar a transformação. Array.from('').

16-07 consegui fazer o exercico com o código abaixo, mas lembrava que o modo que realizamos anteriormente era outro. Apenas consultei para ver a outra alternativa, logo em seguida, utilizando o some().

```for(i = 0; i<people.length; i++){

  if (people[i].profession === 'Front-end developer') {

  console.log("O array people contém, no mínimo, um(a) Front-end developer.", i)

  break

  }
}

```
```
const showPeople = people.some( ({profession}) => profession === 'Front-end developer')

if( showPeople ) {

console.log("O array people contém, no mínimo, um(a) Front-end developer.")

}
```

17-03 erro de sintax usei {a-z} ao inveis de [a-z]

@Roger-Melo

**Comment by Roger-Melo** [comment]
Oi Henrique.

Sobre a revisão raio-x, é importante você entender principalmente o passo 2:

> 2. Quando travar em um exercício, assista a correção, apague o código e implemente-o novamente, sozinho. Se não conseguir implementar sem olhar a correção do exercício, veja a correção. Nessa fase, você notará que provavelmente suas dúvidas sobre o exercício vai ficar mais específica. Após sanar a dúvida, apague o código e implemente-o, sozinho.

Ou seja, nos exercícios que você mencionou acima, se você travou ou não se lembrou de algo, apague o código do exercício e implemente-o novamente, sozinho. Sem olhar.

Se você olhar a resolução e depois não fizer sozinho, seu cérebro não vai sacar o padrão de resolução do exercício.

---

Sobre a aplicação, vi que você resolveu os problemas de usabilidade com inputs e labels e exibição dos pontos. É bom ver que você deu atenção a alguns pontos que foram falados na análise.

Vou deixar abaixo novamente oportunidades de melhoria na aplicação. Houveram alguns erros sobre linhas em branco que foram observados anteriormente e se repetiram nessa segunda versão da aplicação. Cuidado com isso, procure não repetir os mesmos erros.

### Organização do código

#### Código comentado no final do arquivo

Não deixe código comentado em sua aplicação. Seja para subir para produção ou enviar para alguém, não faz sentido manter linhas de código comentadas.

#### Linhas em branco

Lembre-se, linhas em branco devem ser usadas para indicar, visualmente, a separação entre conceitos.

No código abaixo,

```javascript
const paragraphScore = document.querySelector('p')
paragraphScore.setAttribute('class', 'score text-center text-light fw-bold bg-dark py-3') 


let counter = 0 
```

não há necessidade de deixar duas linhas em branco. Apenas uma já separa um conceito do outro.

```javascript
form.addEventListener('submit', event => { 
    // ...
    counter++ 
    
  }, 10)

})
```

No código acima, evite deixar linhas em branco na parte interna do fim do bloco. A última linha de um bloco deve sempre estar preenchida com a última expressão inserida nele.

No código abaixo, você pode separar consts que foram declaradas com ideias distintas. Prefira separar consts que armazenam arrays de consts que armazenam nós do DOM.

```javascript
// evite
const correctAnswer = ['B', 'A', 'B', 'A']
const answers = []
const form = document.querySelector('.quiz')
const paragraphScores = document.createElement('p')
const h2 = document.querySelector('.subtitle')

// prefira
const form = document.querySelector('.quiz')
const paragraphScores = document.createElement('p')
const h2 = document.querySelector('.subtitle')

const correctAnswer = ['B', 'A', 'B', 'A']
const answers = []
```

### Lógica do código

#### return desnecessário

O return é usado em funções para fazer duas coisas:

1. Terminar a execução da função, fazendo com que o código abaixo dele seja ignorado;
2. Retornar um valor quando a função é invocada.

No código abaixo,

```javascript
userAnswers.forEach((userAnswer, index) => {
  if (userAnswer === correctAnswer[index]) {
      score += 25
  }
  return
})
```

não há necessidade de inserir um `return` abaixo do `if`, pois a função não precisa retornar um valor e também não precisa do `return` para terminar a execução naquela linha. Afinal, aquela é a última linha, não há código abaixo do if.

#### Const declarada mas não usada

A `const answers` declarada no topo do código não foi usada no decorrer da aplicação.

---

Está ficando mais claro?

@henriquebazi

**Comment by henriquebazi** [comment]
Obrigado Roger, vou ajustar mais estes pontos!
