### ISSUE TITLE
Aplicação: [QUIZ]

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#993]
Olá @Roger-Melo, tudo bem contigo? Segue o link para o QUIZ que eu FIZ, rs.
https://github.com/WebDevCampos/QuizApp
https://webdevcampos.github.io/QuizApp/

# - Quais foram as suas maiores dúvidas ou dificuldades durante a execução desse exercício?

Eu fiz várias vezes, quis implementar algo mais visual, pois a lógica eu havia entendido. Usei como referência, a aula que me fez comprar o curso, a aula do carrossel. 

Minhas maiores dúvidas e dificuldades estiveram no momento de nomear as variáveis e na refatoração do código. Fiz uma segunda versão com objetos, acreditando que seria melhor, mas resolvi voltar à maneira mais "comum".  Como escolhi algo mais visual, o CSS, apesar de usar o **BS** há um tempo, foi um pouco chato de formatar e ainda acredito que não terminei. 
Há um erro no **JS** que não consegui burlar: 

 -  Se um usuário quiser, pode fazer mais de 100 pontos, bastando clicar várias vezes em uma opção. Por isso eu optei pelo EventListener 'input'  e mesmo assim, o usuário pode fazer mais de 100 pontos bastando marcar e desmarcar uma opção. Caso eu faça o usuário perder 25 pontos por opção errada, é possível evitar que ele faça mais de 100 pontos, e menos de 0 pontos, mas pode ser que ele não consiga fazer 100 pontos. Contudo vale lembrar que somente se o usuário fizer de má fé e tem muito por aí.
 
Pensei em alocar estes pontos em uma outra variável, ou em um objeto, independente de quantas vezes o usuário selecione, mas ainda não tive tempo. Demorei para entregar por causa do fechamento de período das faculdades.

# - Quais foram as suas menores dificuldades durante a execução desse exercício?

Não tive dificuldade alguma em implantar o código em si, se eu não tivesse que nomear corretamente ou refatorar, teria feito em alguns minutos. Todas as aulas estão bem vivas na minha mente e eu sempre revejo alguma pois penso se alguma ideia pode funcionar. 

Ah sim, reparei que eu não precisava de um array caso todas as respostas tivessem o mesmo `value`, mas compreendo o porquê do array e como usá-lo.
 
Gosto muito das suas aulas e não vejo problema nos desafios ou exercícios, embora alguns conceitos sejam explicados no final de um exercício quando não foram passados durante a etapa. Mas de forma geral, seus enunciados são muito bem claros e os objetivos a serem alcançados também. Muito obrigado, rumo à fluência!

P.S.:  Desculpe pela outra issue, foi sem querer.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @WebDevCampos.

Parabéns pelo esforço em implementar a aplicação, porém, ela não está cumprindo os critérios necessários para ser analisada.

No dia 4 de abril, às 7:45h da manhã (horário de Brasília), eu enviei um e-mail chamado "[Alunos CJRM] Análises de Aplicações", para os alunos que se matricularam em março.

Esse e-mail contém tudo o que é necessário saber para que uma aplicação seja analisada. 

Essa sua versão atual do quiz pode ser mantida para fins de estudos, mas para que a aplicação seja de fato analisada, eu sugiro que você envie uma nova versão atendendo os critérios especificados abaixo.

Vou deixar abaixo o e-mail que enviei para os alunos e mencionei acima, dá uma olhada nos critérios do passo 3. Fico no aguardo de seu novo envio =)

---

Olá, Roger aqui.

Estou passando para te lembrar de algo importante que eu comentei na aula inaugural.

Se você ainda não assistiu essa aula, é só tocar no botão abaixo.

Uma recomendação: assista do início ao fim:

[Quero assistir à aula inaugural](https://app.nutror.com/v3/curso/a977a43d31cedcb6e7d064649ddd6c5436155aaf/curso-de-javascript-roger-melo/aula/2186928)

Esse email é para te avisar sobre as regras que você precisa seguir para que você possa enviar as suas aplicações às análises que serão feitas por mim.

Eu recomendo que você salve esse email em algum lugar, marque ele com estrela (gmail), e faça o que tiver que ser feito para o seu serviço de email entender a importância dele. Por que ele é importante e você terá que voltar nele nos próximos dias.

Talvez você já saiba, talvez não, mas essa é uma oportunidade para aumentar as suas chances de chegar na fluência (construir aplicações web com JavaScript puro).

Você nem imagina a quantidade de pessoas que me pedem para analisar o código delas, seja por inbox nas redes sociais ou por e-mail, e, a minha resposta é sempre a mesma.

Embora muita gente ofereça grana para eu analisar o código delas, eu sempre digo não.

Eu faço isso porque o meu tempo é escasso e, sinceramente, esse dinheiro não faz diferença para mim.

Só que é o seguinte.

A minha missão é te ensinar a chegar na fluência, por isso o que eu vou te falar agora é justamente para estimular você a executar o método o mais rápido possível e ter um feedback real.

Eu vou passar um pente fino em suas aplicações e te dar sacadas que podem virar a chave na sua mente na hora de construir aplicações web com JavaScript puro.

Por isso, se você entrou no CJRM, eu recomendo fortemente que você fique atento a cada detalhe dos critérios que eu estou te mandando para não deixar essa oportunidade escapar.

Agora, eu vou te mostrar tim tim por tim tim, tudo o que você precisa fazer para que as suas aplicações sejam analisadas por mim.

Fica ligado.

**Passo 1**

Você tem o prazo de 7 dias para implementar a aplicação, começando no dia em que você viu as aulas descritas logo abaixo. A plataforma disponibiliza para mim um relatório com as aulas que você acessou.

Se você viu as aulas de como construir a aplicação de quiz interativo, por exemplo, você tem 7 dias para implementar essa aplicação *sozinho(a).

*O que eu quero dizer com "sozinho" é:

1. Sem assistir as aulas da aplicação novamente, implemente-a.

2. Se travar em um ponto, assista a aula, apague todo o código e implemente-o novamente, sozinho. Se não conseguir implementar sem assistir a aula, veja-a novamente. Após sanar a dúvida, apague o código e implemente-o, sozinho.

3. Execute o item acima quantas vezes forem necessárias para que seu cérebro entenda o padrão de implementação da aplicação. Isso te deixará mais "afiado" para os próximos desafios do treinamento.

E claro, se mesmo executando os itens acima as dúvidas permanecerem, não hesite em abrir uma issue no [repositório do treinamento](https://github.com/roger-melo-treinamentos/curso-de-js-roger-melo/issues).

*Após a primeira aula mostrando como construir o quiz interativo, além de seguir os passos e critérios abaixo, implemente o que o exercício após a aula pede.

Você verá que apenas essa primeira aplicação (quiz) tem um exercício pedindo para você enviá-la ao repositório. Porém, se você está recebendo este email, esteja ciente de que você pode executar o que estou descrevendo nele para **todas as aplicações do treinamento**.

Segue abaixo o momento em que você deve enviar cada aplicação para a análise:

a) **Quiz interativo**: antes de assistir a aula "Exibindo a pontuação - Aula 02-01", da etapa 07;

b) **To-do list**: antes de assistir a aula "Correção dos exercícios da aula 02 da etapa 09 - Aula 01-01", da etapa 10;

c) **Weather Application**: antes de assistir a aula "Correção dos exercícios da aula 02 da etapa 12 - Aula 01-01", da etapa 13;

d) **Conversor de moedas**: antes de assistir a aula "Correção dos exercícios da aula 03 da etapa 14 - Aula 01-01", da etapa 15.

**Passo 2**

Após implementar a aplicação (no prazo estipulado acima), abra uma issue no repositório do treinamento seguindo os critérios descritos abaixo.

A issue deve ser aberta com o issue template "aplicação", como mostra a imagem abaixo (por favor, não utilize outro template de issue).

![template-issue](https://user-images.githubusercontent.com/29297788/123246882-ac06d080-d4bc-11eb-8ac7-7ce1a5b1c5a1.jpg)

**Passo 3**

Eu irei ler a sua issue e iniciarei a análise (ou pedirei ajuste, se necessário).

Abaixo seguem os critérios das análises:

- **Critério 1**: as cores da sua versão da aplicação devem ser diferentes das cores da aplicação mostrada na aula;
- **Critério 2**: a aplicação deve conter nenhuma funcionalidade à mais do que as que foram mostradas nas aulas anteriores;
- **Critério 3**: a aplicação só deve conter features da linguagem que foram mostradas nas aulas anteriores;
- **Critério 4**: a issue deve conter o link do repositório da sua versão da aplicação e quais foram as suas maiores e menores dificuldades durante a implementação dela.

Ao passar por todos os passos e critérios, você garante que suas aplicações serão analisadas. Preto no branco.

Por isso, o quanto antes você avançar no treinamento e construir as aplicações, mais cedo vou conseguir fazer a sua análise personalizada com sacadas que vão te dar mais clareza na sua jornada para chegar na fluência.

Abraço,

Roger

P.S: Caso tenha qualquer dúvida, é só responder este e-mail.

**Comment by WebDevCampos** [comment]
Ok, então daqui a pouco eu mando.

Em qui, 24 de jun de 2021 07:24, Roger Melo ***@***.***>
escreveu:
