### ISSUE TITLE
Resumo da Aula Parents, children e siblings - Aula 03-02 da etapa 05

### ISSUE THREAD

**Issue by ricardopontesdantas** [roger-melo-treinamentos/curso-de-js-roger-melo#994]
Três tipos de relação que temos no DOM entre os nós são *parent*, *children* e *siblings*. *Siblings*, na tradução, são irmãos, e no caso dos nós, é quando os elementos estão no mesmo nível dentro do DOM. *Children* é o elemento que está dentro do elemento *Parent*. Por exemplo, imagine que temos a seguinte estrutura:

```html
<div>
	<h2></h2>
	<p></p>
</div>
```

No exemplo acima, os elementos `<h2>` e `<p>` estão no mesmo nível no DOM, então a relação entre eles é de *siblings*. Já se formos ver a relação entre `<h2>` e a `<div>`, por exemplo, a `<h2>` está dentro da `<div>`, então a `<h2>` tem uma relação *children* para a `<div>`, e consequentemente a `<div>` é a *parent* do `<h2>`.

Agora, vamos partir da seguinte estrutura HTML

```html
<article>
  <h2>Título do post</h2>

  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>

  <div>Escrito por Ricardo Dantas</div>
</article>
```

Imagine que tenhamos que aplicar uma classe CSS para todos os elementos dentro do `<article>`. E se esse conteúdo for dinâmico? Neste caso o ideal é armazenar a referência para o `<article>` e a partir daí utilizar a propriedade `children` para obter todas as referências dos elementos filhos de `<article>`. Então armazenamos a referência de `<article>` com `document.querySelector('article')` e atribuímos a uma constante `article`, e se dermos um `console.log(article.children)`, vemos uma *HTMLCollection* com todos os elementos filhos de `<article>`. Como sabemos, em uma *HTMLCollection* não é permitido utilizar o `forEach()` para percorrer os elementos, então precisamos converter essa *HTMLCollection* em um *array* a partir do método `from()` da função construtora `Array`, bastando enviar como argumento de `from()` a nossa *HTMLCollection*, ou seja, o `article.children`. E aí observamos no console que agora temos um *array*, e que o método que utilizamos não modifica a informação original, ouseja, nós criamos outra informação a partir dela.

Agora com o array, podemos percorrê-lo e adicionar uma nova classe a cada elemento, da seguinte forma:

```jsx
const article = document.querySelector('article');

Array.from(article.children).forEach(element => {
	element.classList.add('article-element');
});
```

Podemos também descobrir o elemento pai de alguma referência. Continuando com o exemplo HTML, podemos obter a referência do elemento `<h2>` e a partir dele obter o elemento pai, que será o `<article>`. E podemos ainda encadear a propriedade que retorna o elemento pai, e se chamamos novamente a propriedade, temos o `<body>` retornado. Veja no exemplo:

```jsx
const title = document.querySelector('h2')

console.log(title.parentElement); // <article>...</article>
console.log(title.parentElement.parentElement); // <body>...</body>
```

E podemos obter o elemento irmão seguinte através da propriedade `nextElementSibling`, e o anterior com o `previousElementSibling`, e caso não existam, `null` será retornado. Veja no exemplo:

```jsx
console.log(title.nextElementSibling); // <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
console.log(title.previousElementSibling); // null
```

@Roger-Melo

**Comment by Roger-Melo** [comment]
Boa @ricardopontesdantas, rumo à fluência! 👊🏻
