### ISSUE TITLE
Aplicação: [Quiz]

### ISSUE THREAD

**Issue by WebDevCampos** [roger-melo-treinamentos/curso-de-js-roger-melo#995]
https://github.com/WebDevCampos/QuizApp
https://webdevcampos.github.io/QuizApp/

Olá Roger, tudo certo? Bom, aí está o link para a aplicação do Quiz. 

### Maiores dificuldades
  No código em si, nenhuma, mas sempre tenho dificuldade na refatoração e na nomeação de variáveis.
  
### Menores dificuldades:
 implantar a lógica não foi difícil, suas aulas são bem explicativas.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @WebDevCampos!

Parabéns pelo esforço em construir a primeira aplicação =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## jQuery

No `index.html`, a tag `<script src="jquery-3.6.0.js"></script>` está carregando um arquivo jQuery.

Não faz sentido carregar jQuery em uma aplicação de um treinamento de JavaScript puro.

## Organização de código

### Linhas em branco

Um princípio: linhas em branco indicam, visualmente, a separação entre conceitos. Procure evitar o excesso ou a falta delas no código.

Sabendo disso, você pode remover as linhas em branco 1, 3, 5, 16, 20, 24, 26, 27, 29 e 30, e inserir uma linha em branco nas linhas 9 e 11.

Se um bloco de código conter apenas duas linhas, você pode quebrar o princípio das linhas em branco. Não faz muito sentido deixar um "buraco" entre apenas duas linhas de código.

### Indentação

Uma indentação correta é essencial na legibilidade de um código. Então ao invés de indentar assim:

```javascript
if(answer.value === correctAnswers[index]){
   score += 25
        }
```

Prefira indentar assim:

```javascript
if (answer.value === correctAnswers[index]) {
  score += 25
}
```

### Declarações de variáveis semelhantes

A declaração das consts no topo do código pode ser mais organizada. Você pode organizá-las agrupando-as pelo tipo de valor que elas armazenam. No exemplo abaixo, eu agrupei as consts que armazenam elementos do DOM e separei a const que armazena as respostas corretas:

```javascript
const form = document.querySelector('form')
const points = document.querySelector('.points')

const correctAnswers = ['A', 'B', 'B', 'A']
```

## Lógica

Como a `let` score foi declarada fora do callback do listener de envio do form, do segundo envio seguido em diante, os pontos continuam aumentando. Nas aulas seguintes, você verá como consertar isso.

---

> ## ...sempre tenho dificuldade na refatoração e na nomeação de variáveis

Refatoração vem com a prática e o tempo. É natural ter mais dificuldades no começo =)

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by WebDevCampos** [comment]
Obrigado pela avaliação. O JQery é por conta de estar em em todos os
projetos que faço, está lá, porque eu uso um template padrão.

Vou ter mais cuidado nas linhas em branco e com a indentacão, mas tenho
quase certeza que é a indentacão do próprio VS Code que está estranha.

Realmente os nomes das variáveis é uma dificuldade minha.

Obrigado pela análise.

Em sex, 25 de jun de 2021 08:07, Roger Melo ***@***.***>
escreveu:

**Comment by Roger-Melo** [comment]
Show @WebDevCampos. No que precisar, é só dar o toque =)
