### ISSUE TITLE
Aplicação: Quiz Interativo

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#998]
#### Link da Aplicação
https://github.com/raphaelprsilva/interactive-quiz

#### Maiores Dificuldades
- Tentar utilizar o **Bootstrap** e fazer algo do zero, foi um pouco complicado, pois, eu não tenho muita prática com frameworks desse tipo. De alguma maneira, acabei olhando parte do código do ```index.html``` feito na aula 01-03, para tentar seguir uma linha de pensamento com relação ao layout;
- Tentar refatorar/melhorar a legibilidade do código foi um pouco complicado, de maneira, que não a minha sensação, é de que não obtive tanto êxito, pois o ```eventListener``` do meu form, ficou muito grande, e me incomodou bastante;
- Nomear variáveis, de maneira com que elas não se repitam ou que façam sentido, também é algo que me faz "botar os neurônios" para trabalhar, então considero sim, que esta foi uma dificuldade;

#### Menores Dificuldades
- Não tive tanta dificuldade em implementar a lógica dos pontos, pois a aula deu um bom embasamento e uma linha de raciocínio para seguir;

Acho que cumpri os requisitos mínimos do projeto, mas fico com a sensação de que poderia fazer mais e melhor.

Desde já, muito obrigado pela análise, e aguardo ansiosamente pelos feedbacks.

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva!

Parabéns pelo esforço em construir a primeira aplicação =)

O uso do Bootstrap é opcional, incluí agora uma observação sobre isso na descrição do exercício.

Nomeação de variáveis e refatoração são habilidades que evoluem com a prática e o tempo. É natural ter uma certa dificuldade no início. Não se preocupe tanto com a refatoração ao enviar as aplicações. O mais importante é fazer funcionar, depois você vai melhorando o código =)

Vou deixar abaixo alguns pontos de atenção, segundo os critérios que usei para analisar.

## Usabilidade

### Inputs desmarcados por padrão

Antes do usuário selecionar as alternativas, é bom que a primeira alternativa de cada pergunta esteja marcada por padrão. Para fazer isso, basta inserir o atributo `checked` no input type radio a ser marcado por padrão.

Isso é mais uma preferência pessoal mas acredito que incentiva o usuário a marcar a resposta que ele realmente acredita que seja a verdadeira.

## Lógica

Prefira usar `textContent` apenas para manipular strings. Como a intenção é remover os elementos internos do form, você pode usar o `innerHTML`:

```javascript
form.innerHTML = '';
```

## Organização de código

### Atribuições e invocações de métodos

O código dentro da `feedbackMessageToUser` pode ser "agrupado" por atribuições e depois invocações de métodos:

```javascript
// antes
form.textContent = '';
element.setAttribute('class', classAttribute);
element.textContent = message;
form.insertAdjacentElement('afterend', element);

// depois
form.textContent = '';
element.textContent = message;
element.setAttribute('class', classAttribute);
form.insertAdjacentElement('afterend', element);
```

### Local de declaração de destructuring

Se você quiser, pra deixar o código mais conciso, você pode fazer o destructuring na declaração de parâmetros da função:

```javascript
// antes
const feedbackMessageToUser = (userScoreFeedbackInfo) => {
  const { element, classAttribute, message } = userScoreFeedbackInfo;
  // ...
};

// depois
const feedbackMessageToUser = ({ element, classAttribute, message }) => {
  // ...
};
```

### Nomes de variáveis e funções

Um princípio que gosto de seguir ao nomear é:

- Funções são verbos que descrevem a ação que a função executa. 
  - Exemplos: `getName`, `setName`, `incrementCounter`;
- Variáveis/consts são substantivos que descrevem o valor armazenado. 
  - Exemplos: `user`, `score`, `color`. 
  - Quando o valor armazenado é um boolean, podem conter `is`, `has` ou `should`. 
    - Exemplos: `isOdd`, `hasSevenItems`, `shouldUpdate`.

Sabendo disso, `feedbackMessageToUser` pode ser renomeada para `showUserScore`, por exemplo.

`feedbackUser` pode ser mais descritiva em relação ao valor que ela armazena. `finalScoreContainer` seria uma opção de nome.

---

Nas aulas seguintes, você verá formas de refatorar o código dessa aplicação. Mais uma vez, parabéns pelo esforço =)

As observações fizeram sentido?

**Comment by raphaelprsilva** [comment]
Fala Roger, tudo bem? Desde já, muito obrigado, pelo retorno. 😃

### Inputs desmarcados por padrão
Sobre isso, eu realmente, eu percebi que, na aplicação do exemplo, todas as já estavam todos com o atributo ``checked``, mas eu pensei: "Poxa, quando eu vou preencher algo, não vem com nada marcado. Deve ter passado despercebido. Vou tirar esse atributo."

### Lógica
Realmente, foi algo que passou desapercebido. Usei o ``form.textContent``, pois em alguma aula, você havia dito que seria melhor, mas não me atentei que, seria mais adequado para quando fosse manipular strings.

### Atribuições e invocações de métodos
Acabou que isso passou desapercebido, mas faz sentido sim.

### Local de declaração de destructuring
Em uma das aulas, você fez um destructuring, da maneira como eu fiz, mas agora, vejo que você o fez (acredito), pelo fato de exceder a quantidade máxima de caracteres por linha.

## Pergunta

- A ideia, agora que eu recebi o feedback, é refatorar o quiz que eu fiz, da maneira como você desenvolve no course, ou apenas alterar esses pontos destacados por você neste feedback?

Eu pergunto isso, pois comecei a fazer os exercícios finais da etapa 07, e nas questões 04, 05 e 06, eu fiquei confuso.

- Questão 04
  - A partir deste exercício, vamos voltar a trabalhar na sua versão do Quiz =D
  - Adicione mais 2 alternativas em cada pergunta do quiz.

- Questão 05
  - Modifique a ordem das alternativas corretas. Ou seja, faça com que a alternativa correta das perguntas não seja apenas a alternativa "B".

- Questão 06
  - Refatore o código.

Muito obrigado, desde já! Abração. 🚀

**Comment by Roger-Melo** [comment]
> ### A ideia, agora que eu recebi o feedback, é refatorar o quiz que eu fiz, da maneira como você desenvolve no course, ou apenas alterar esses pontos destacados por você neste feedback?

Os pontos que eu citei na análise não são conflitantes com o que você verá nas aulas seguintes. A refatoração que vc vai ver nas aulas seguintes cobre a maioria dos pontos que eu citei na análise e apresentam novas formas de resolver alguns problemas =)

@raphaelprsilva

**Comment by raphaelprsilva** [comment]
Olá Roger,

Obrigado pelo retorno, mas não ficou claro ainda.

Eu fiz a minha versão do quiz, certo? Mostrando na tela a pontuação, da maneira como eu pensei. Agora, quando cheguei nos exercícios, os mesmos pedem para eu voltar na minha aplicação e fazer o que se pede.

A dúvida é:
 - Eu devo deixar a minha aplicação semelhante à que você fez?

Não sei se ficou claro... Mas essa é a dúvida. hehehe

@Roger-Melo

**Comment by Roger-Melo** [comment]
Se quiser, pode manter as duas versões (a do curso e a sua).

Sempre vão haver essas pequenas diferenças, as aplicações construídas no treinamento vão ter manutenção, melhorias e refactoring.

Cabe a vc decidir qual versão (ou versões) irá manter =)

@raphaelprsilva

**Comment by raphaelprsilva** [comment]
Entendi. Muito obrigado pelo retorno! 😃

Sinta-se à vontade para fechar a issue.

Abraço!

**Comment by Roger-Melo** [comment]
Show @raphaelprsilva. No que precisar, é só dar o toque =)
