### ISSUE TITLE
Etapa 07  - Aula 02-01 - Exibindo a pontuação

### ISSUE THREAD

**Issue by raphaelprsilva** [roger-melo-treinamentos/curso-de-js-roger-melo#999]
Fala Roger, tudo bem?

A pergunta é meio boba, mas foi algo que não ficou tão óbvio para mim.

Após finalizar a execução da aplicação e enviá-la para você analisar, eu posso dar sequência no curso e ver como você implementou, como no exemplo desta aula, ou eu sempre aguardo seu feedback e tento melhorar o código só após isso?

Um grande abraço!

@Roger-Melo

**Comment by Roger-Melo** [comment]
Olá @raphaelprsilva.

A pergunta não é boba não, pode perguntar sempre que tiver dúvidas =)

Pode seguir com o treinamento sim, já clonei o estado atual da aplicação.

Se estiver tudo ok com ela, em breve a análise será postada na issue =)

**Comment by raphaelprsilva** [comment]
@Roger-Melo, muito obrigado pelo retorno. 😃

Pode fechar a issue, se quiser.

Abraço! 🚀
